### ISSUE TITLE
Problem in Shifting between Tabs

### ISSUE THREAD

**Issue by ammarsabir26** [Microsoft/vscode#30322]
- VSCode Version: 1.13.1
- OS Version: 10.11.6

Steps to Reproduce:

1.Tab no. 1 , working on line number 13
2. Move to Tab no.2 , do some code
3. Move back to tab. 1 and your code is focusing somewhere else instead of line no. 13, everytime you have to scroll back to where you left

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What language are you working in? Can you please provide more detailed repo steps or try capturing a short gif/video of the problem

**Comment by ammarsabir26** [comment]
I am working in c# , IDE unity 5.3.2
shift from one tab to the other ,
move back to the 1st tab , 1st tab will no longer focus at the code where
you left it , it will focus somewhere down in the code. i've to scroll
everytime to move back to the code where i left it

**Comment by mjbvz** [comment]
Can you please try taking screenshots or a video of the problem? Also, does this happen if you disable all extensions? Just run the `Extensions: Disable All Extensions` command to check.
