### ISSUE TITLE
C# Intellisense does not refresh after class (symbol) rename and also adding Nuget package

### ISSUE THREAD

**Issue by THuffam** [Microsoft/vscode#30324]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Rename a class - or adding a NuGet package using dotnet add package <packagename>
At this point the intellisense error highlighter indicates that the referenced classes have an error (in the case of a renamed class is says the class and ctor already exist, in the case of a newly added package, it says it cannot find it.

To work around this I have to restart VS Code.

Reproduces without extensions: No.. but this disabled the 'Rename Symbol' option and it also disabled the intellisense - so kind of a mute point (I think?).

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
