### ISSUE TITLE
Flickering when switching themes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#30326]
- open some source code (e.g. of type Java)
- Open the theme switcher dialog
- go through the themes
- note that the token colors flicker
- it looks to me (from debugging at ViewLine.renderLine) that there is a moment where each line has all scopes removed from the lines, and that all text gets draws with the default foreground color (mtk1)
![image](https://user-images.githubusercontent.com/6461412/28006870-bea971cc-6583-11e7-8b6d-af7f9d2504bc.png)

**Comment by alexandrudima** [comment]
This is by design. Tokens from the previous theme point to color ids that make no sense in the new theme. That's why when switching a theme, we reset all tokens to the default foreground color.
