### ISSUE TITLE
Typescript died five times after it started (???)

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#30329]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fresh-material|2ndshift|2.2.2|
|Bookmarks|alefragnani|0.15.2|
|project-manager|alefragnani|0.18.1|
|htmltagwrap|bradgashler|0.0.3|
|gotemplate|casualjim|0.1.1|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|mustache|dawhite|1.0.0|
|gitlens|eamodio|4.3.1|
|vscode-html-css|ecmel|0.1.7|
|json-tools|eriklynd|1.0.2|
|beautify|HookyQR|1.1.1|
|automagic-code|jairzjunior|0.0.2|
|theme-material-dark-soda|jbw91|1.3.0|
|theme-atomic-dark|kimkwanka|0.2.0|
|git-indicators|lamartire|1.2.1|
|vs-color-picker|lihui|0.6.0|
|start-git-bash|McCarter|1.2.1|
|code-beautifier|michelemelluso|1.7.2|
|prettify-json|mohsen1|0.0.3|
|vscode-scss|mrmlnc|0.6.2|
|atom-keybindings|ms-vscode|2.9.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|subtle-brackets|rafamel|2.0.2|
|vscode-icons|robertohuertasm|7.10.1|
|vscode-theme-superonedark|seansassenrath|0.0.15|
|code-settings-sync|Shan|2.8.2|
|vscode-todo-highlight|wayou|0.5.5|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|
|Material-theme|zhuangtongfa|2.9.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Can you please provide some repo steps? Also does it happen if you disable all extensions?  Just start code with `--disable-extensions` to check

**Comment by mjbvz** [comment]
Closing as there is not enough info to investigate this

**Comment by euk-anthonyb** [comment]
Sorry for not getting back to you sooner, but it has happened again.

All I did was edit some JavaScript in an HTML file (i.e. selected a line). The first time it happened, I just opened a JavaScript file and did nothing to it before the error occurred.

![image](https://user-images.githubusercontent.com/14346320/28304622-560d27fe-6b90-11e7-8c33-2215e45ac7b7.png)
