### ISSUE TITLE
Some terminal text invisible with the default Solarized Dark theme

### ISSUE THREAD

**Issue by donghaoren** [Microsoft/vscode#30325]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.9.2|
|pegjs-language|SirTobi|0.1.0|
|python|donjayamanne|0.6.7|
|Theme-Solarized-dark|gerane|0.0.2|
|ftp-simple|humy2833|0.5.1|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|latex|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|3.1.6|
|java|redhat|0.7.0|
|vscode-icons|robertohuertasm|7.10.1|
|sass-indented|robinbentley|1.4.1|;

---

I encountered this when using the *default* Solarized Dark theme (not to be confused with the `Solarized-Dark` theme module, which works fine.) and mocha 3.0.2.

Steps to Reproduce:

1. Install mocha (my version is 3.0.2)
2. Write a simple test script, save as `test.js`, for example:

        describe("test", () => {
            it("test 1", () => { });
            it("test 2", () => { });
        });

3. Use the default "Solarized Dark" theme
4. Open the VSCode Terminal, type "mocha `test.js`"

The test names such as `test 1` and `test 2` are missing because the background color is the same as the text colors for them.

<img width="301" alt="issue" src="https://user-images.githubusercontent.com/1595237/28006863-fd5403f2-6505-11e7-90ad-e5f95d417ba3.png">

**Comment by Tyriar** [comment]
@donghaoren could you open devtools (Help > Toggle developer tools) and inspect the element with the invisible text? I'm interested in the classes on their `<span>`s.

**Comment by donghaoren** [comment]
I just upgraded to version 1.14.0 and those texts are visible now. For both version 1.13.1 (which had the issue) and 1.14.0, the class is `xterm-color-8`.

**Comment by Tyriar** [comment]
@donghaoren great, thanks. I think I did tweak some colors in solarized dark now that you mention it. Glad it's fixed! :+1:
