### ISSUE TITLE
Missing editorGroupHeader colorization option

### ISSUE THREAD

**Issue by imanrp** [Microsoft/vscode#30331]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04

![sc_vs_code](https://user-images.githubusercontent.com/2027300/28017876-3b535014-65a5-11e7-8f7f-b2bf6bfba076.png)

There seems to be no editable foreground color properties for **editorGroupHeader** in the **workbench.colorCustomizations** option. What I want to do is to change the color of the icons on the top right corner of the editor. Options that are available: editorGroupHeader.tabsBackground, editorGroupHeader.noTabsBackground, and editorGroupHeader.tabsBorder.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26130
