### ISSUE TITLE
[scss] extend multiple classes highlighted as error

### ISSUE THREAD

**Issue by magic890** [Microsoft/vscode#30335]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|Theme-FlatlandMonokai|gerane|0.0.4|
|debugger-for-chrome|msjsdiag|3.1.6|
|debugger-for-ios-web|msjsdiag|0.1.2|;

---

Steps to Reproduce:

1. Create `.scss` file
2. Extend two classes inside one selector, like `@extend .text-center, .uppercase;`
3. As a Problem is highlighted: 
```
severity: 'Error'
message: 'semi-colon expected'
source: 'scss'
```

It should not be an error since it's feasible in SASS to extend two classes using the comma as separation.

**Comment by yuetsh** [comment]
![image](https://user-images.githubusercontent.com/10295672/28057383-6fe49902-6652-11e7-8135-6e05da6934c4.png)
