### ISSUE TITLE
Wrong syntax highlighting for JavaScript with inline php code returning JavaScript objects

### ISSUE THREAD

**Issue by amadeann** [Microsoft/vscode#30339]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Home 64-bit

Steps to Reproduce:

1. Open a new file with the .php extension
2. Try to assign the value returned by an inline php function to a JavaScript object.

For example:

```
<script>

    var jsObject = <?php echo json_encode($somePHPArray); ?>;
    var anotherJsObject = <?php echo json_encode($anotherPHPArray) ?>;

    var someVariable = "value";

    function storePreviousFormData(formData) {
        // some comments
    }
    
</script>
<script>
    functionInAnotherScriptBlock() {
        var hereHighlighting = "is still broken";
    }

    var colors = {
        do: "not work as they should";
    }
</script>
```

Reproduces without extensions: Yes

This is related to the issue #4646. Highlighting of the values enclosed in quotation marks works. There is a problem only with objects, since they cannot be enclosed in quotation marks.

**Comment by roblourens** [comment]
Should be fixed in 1.14
