### ISSUE TITLE
Feature Request: Clear Search Field/Halt Searching

### ISSUE THREAD

**Issue by ryanjavens** [Microsoft/vscode#30336]
Hi everyone! 

Not sure if this is a feature already that I just can't seem to find, but I'd like to make a feature request if it isn't. When searching for a keyword across all files in my project, I would like to be able to clear the search field to stop a search. Currently, if I search for a keyword that might have a lot of results, I don't see any UI element to stop the search and I workaround this by just typing in some gibberish string in place of what I was originally searching for. I find that if I don't clear a search out, it slows down VS Code quite a bit, so it would be nice to be able to stop that. 

My proposed solution would be adding an 'X' button on the right side of the search field to allow for easy search term clearing. 

Thanks for hearing me out and I appreciate this product!

**Comment by roblourens** [comment]
You can press escape to end a search. I thought there was an issue to add a button for this, but I can't find it...

**Comment by iulia-codes** [comment]
I also support this request. Maybe a stop button should exist, so it will be more intuitive that we can simply stop search by pressing that, on top of hitting ESC.

**Comment by jjaeger4** [comment]
@roblourens Thanks for the mention of hitting ESC. I actually thought this was a bug that after running a search I couldn't just hit a button to stop it and the rg.exe application was eating up my system resources to the point I'd have to kill the process manually every time I did a search.

One would expect that "Clear Search Results" would not be grey'd out when performing a search so that you could clear the search and stop it from eating up resources.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L786

**Comment by roblourens** [comment]
And the action buttons at the top are set up here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L251

**Comment by RMacfarlane** [comment]
A 'Cancel Search' button now appears when a search takes longer than 2 seconds to complete
![search_delayed_cancel](https://user-images.githubusercontent.com/3672607/35422257-90a79a90-01fc-11e8-99c3-65497a614a3e.gif)

**Comment by ryanjavens** [comment]
@RMacfarlane thank you so much!
