### ISSUE TITLE
Display required / type quick info in the type helper

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#30334]
As a feature request/suggestion:

It would be very useful if type helper would display at least what fields in the interface are required, or which can be omitted (undefined). This is really useful for new/unfamiliar libraries with complex interfaces: user can quickly define and fill required properties.

Required fields could be marked with (*) or another color.

![image](https://user-images.githubusercontent.com/736697/28019388-394ff822-659a-11e7-8dc6-4b792696d857.png)

Maybe also this free space could be used to output type value preview in an unobtrusive manner.

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/12458
