### ISSUE TITLE
VS Code Intellisense suddenly stops functioning correctly (JavaScript)

### ISSUE THREAD

**Issue by Trivaxy** [Microsoft/vscode#30342]
- VSCode Version: 1.13.1
- OS Version: Windows 7 professional, 32-bit

Unsure of how to reproduce.
The issue suddenly came to be when intellisense started to think of value types as "any" and even confusing them with other value types rarely, it started right before I updated VS Code to 1.13.1.
This is mainly happening with only one node.js module that I'm using, and I'm unsure if it could be the module itself, since I have not updated the module and the issue came out of nowhere.

Here's an example:
![any](https://user-images.githubusercontent.com/13611030/28027877-5dced0ac-65a3-11e7-8720-1b5f1311282d.png)
Before, it used to say that the type was "Message", now, it just says "any".

Here's another example:
![any2](https://user-images.githubusercontent.com/13611030/28028033-e754bbca-65a3-11e7-8dea-eb9e38728aba.png)
"get" does not return that type, yet intellisense fails to tell me that, again, it used to never do this before.

With a little testing on other modules, they *seem* to work fine, and the intellisense on this certain module that I'm having trouble with gets it right on some places, but not all of them.

Again, this could be a problem with VS Code, or the module itself, but the problem is so random I'm unsure of it. I've searched for an answer and I didn't get what I was looking for.

Apologies if this is not supposed to be said here, and I'll be happy to provide info you need.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Is this issue consistent? Does it happen when you first start vscode or randomly after a little while?

**Comment by Trivaxy** [comment]
Consistent, so far. It happens when I start VS Code.

**Comment by mjbvz** [comment]
I suspect there is a pattern in your code that we cannot understand. To help investigate, can you please share some sample code or a small sample project. I'm mainly interested in how the modules are being imported and referenced

You can also try [enabling type checking in your JavaScript files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) to track down what may be going wrong
