### ISSUE TITLE
Does the javascript inside HTML cannot include typings?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#30344]
I try to install typings and get it work on js file. But the same type that got registered in intellisense of js file was not shown in javascript inside HTML

![image](https://user-images.githubusercontent.com/1042507/28032078-7c788234-65d3-11e7-887e-6571e1f96755.png)

**Comment by mjbvz** [comment]
We currently don't support intellisense between inline script blocks and external files, including typings. This is being tracked by #26338
