### ISSUE TITLE
 Can not start, stay in the process

### ISSUE THREAD

**Issue by wjtGitHub** [Microsoft/vscode#30341]
- VSCode Version:1.13.1
- OS Version:window10

Steps to Reproduce:

1.double click.Can not start,stay in the process.
2.After uninstalling, double-click to start, the problem still exists
note:
>***After the editor is upgraded, there is a problem***

Reproduces without extensions: No

picture
![image](https://user-images.githubusercontent.com/17404628/28025477-1e801da2-65c6-11e7-8b39-001cfd177afa.png)

**Comment by chrmarti** [comment]
Have you tried restarting your machine? Did it work with version 1.12?

**Comment by wjtGitHub** [comment]
I restarted the computer many times, and the problem still exists
the vscode version is 1.13.1
![image](https://user-images.githubusercontent.com/17404628/28043869-a60769e8-6606-11e7-87e6-33c3cbc1816e.png)

![image](https://user-images.githubusercontent.com/17404628/28043835-6d02096e-6606-11e7-8ae3-4079432aeea6.png)

**Comment by wjtGitHub** [comment]
# ***Who can help me?***

**Comment by chrmarti** [comment]
Can you try starting from the command line with `code --verbose` and post the output here?

**Comment by wjtGitHub** [comment]
@chrmarti 
I'm sorry I didn't see your reply. I reset my computer, and then the problem was solved. However, the reasons for the problem are still unclear. The problem was that I upgraded from 1.12 to 1.13. So vscode couldn't run. But the program will stay in the process.
