### ISSUE TITLE
Git Erorr

### ISSUE THREAD

**Issue by constantinmoon** [Microsoft/vscode#30345]
- VSCode Version:1.13.1
- OS Version:Windows 10 Creators Update

Steps to Reproduce:

1.In the Git menu,over 8000 files are there.The files are from my computer 
2.

![screenshot 129](https://user-images.githubusercontent.com/26605473/28033302-7a6b480e-65b6-11e7-9d82-2779f7782779.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by constantinmoon** [comment]
Thank you so much.?Now it's fixed😀 

Sent from Outlook
