### ISSUE TITLE
Feature request: 'New project' API

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/vscode#30340]
I would like to suggest an API for extensions to hook into for starting new projects of a certain type.

My motivation is creating a user-friendly way of creating a new project, similar to an experience found in Big Brother Visual Studio, but better. [CMake Tools](https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools) provides a command `CMake: Quick Start` which creates a stub project with a single CMakeLists.txt file and a "Hello, World" level main.cpp. This is great way to skip some of the boilerplate associated by just getting a text editor with a compiler hooked up to it locally. (Something like godbolt, but locally, just to test something or get going on a new project.)

[Windows Template Studio](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio) is awesome and it were nice if a similar API could come integrated into VS Code where extensions could register their own quick start templates, or even more convoluted ones, as found in WTS.

If such a feature existed, I would gladly take the time and contribute to CMake Tools to create composable CMake script stubs. Something like:

I need a library that will:
- depend on clFFT and clBLAS
- have unit tests
- have docs created by doxygen

Plus I will need an executable:
- that links to the library
- which depends on Boost program options
- have docs created by doxygen

So something similar to WTS, but for CMake and baked into VS Code for seamless integration. Because this feature I believe is of general interest, it could be worth the effort to create an API for.

Ideas?

**Comment by chrmarti** [comment]
I think this is covered with #12322.
