### ISSUE TITLE
Command+Click on line in OUTPUT console should go to line in already open file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#30355]
_From @tylerb on July 10, 2017 18:34_

Repro:

1. Use two code views
2. Left view open an unrelated file
3. Right view open a test file with a failing test
4. Run test to generate output in the OUTPUT pane
5. Click on the left view to select it
6. command+click the failing line in OUTPUT

Expected result: the right view jumps to the line that was just command+clicked
Actual result: the file is opened, again, in the left view and then jumps to the line

I'd really like it if this process would first search to see if any view has the file open already.

Thanks!

_Copied from original issue: Microsoft/vscode-go#1080_

**Comment by ramya-rao-a** [comment]
The Go extension only prints out the links to the output pane.
The links are implemented by core VS Code

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/23917
https://github.com/Microsoft/vscode/issues/24027
