### ISSUE TITLE
Tasks smoke test fails

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30357]
The smoketest build task produces the expected error, but the test is not able to find it. Maybe due to color or the `x` on the line in front of it.

```
  4) Smoke Test Suite Tasks ensures that build task produces error in index.js:

      AssertionError: Output does not contain error in index.js
      + expected - actual

      -false
      +true

      at Context.<anonymous> (out/tests/tasks.js:54:24)
      at Generator.next (<anonymous>)
      at fulfilled (out/tests/tasks.js:8:58)
```

And this one for probably the same reason:

```
  5) Smoke Test Suite Tasks verifies build error is reflected in 'Problems View':
     Error: the string "Could not retrieve the element in 45 seconds." was thrown, throw an Error :)
```

**Comment by michelkaporin** [comment]
This is due release/1.14 was not inline with smoke test code on master after we introduced Tasks 2.0 to express repository.

Fixed in af5d64c6db95ea179079af6dc672d3c1cfa5a35f.
