### ISSUE TITLE
Word wrap settings are forgotten when switching tabs for untitled files

### ISSUE THREAD

**Issue by dkoontz** [microsoft/vscode#30360]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Steps to Reproduce:

1. Add text long enough to go off the right side of your screen.
2. Open a file and turn on `View: Toggle Word Wrap`.
3. See that the line has wrapped.
4. Switch tabs to another file.
5. Switch back
6. See that the word wrap setting has been forgotten and the text is extending past your screen again

**Comment by rbenson** [comment]
Is this with any files or certain files? I had this with markdown + any other file. I use the "bounded" setting. To fix it, I had to add:

    "[markdown]": {
      "editor.wordWrap": "bounded"
    }

to make it work the same across files

**Comment by kkwillmert** [comment]
I'm having similar word wrapping issues in version 1.14.0.  In my case, I have editor.wordWrap set to "off", and when I open a new file and past in a large chunk of wide text, it honors that setting until I switch to another tab and back to it (this is on an unsaved new file).  Other files open don't seem to have issues.

Operating System: Windows 10
![image](https://user-images.githubusercontent.com/26722519/28225015-205cd044-689f-11e7-9b4f-55f6f46784e2.png)

**Comment by alexdima** [comment]
This has been fixed in the meantime.
