### ISSUE TITLE
Extension command drops promise reject 

### ISSUE THREAD

**Issue by mvhenderson** [Microsoft/vscode#30369]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

The `catch` for built-in node `Promise` when rejected using `Error` isn't firing from command handler function.

Steps to Reproduce:

1. Create extension using `yo code`
2. Replace `src/extension.ts` with the code below
3. Lauch the debugger and run the `Hello World` command

```
/// src/extension.ts
'use strict';
import {commands,window,ExtensionContext} from 'vscode';

export function activate(context: ExtensionContext) {
    let cmd = commands.registerCommand('extension.sayHello', sayHello)
	context.subscriptions.push(cmd);
}
function sayHello() {
    doSomethingAsync()
    .then(  res => window.showInformationMessage('Success!') )
    .catch( err => window.showErrorMessage(err) )
}
function doSomethingAsync(): Promise<string> {
    return new Promise <string> ( (resolve, reject) => {

        // this works as expected (error popup shown)...
        //                          vvvvvvvvvvv
        // setTimeout( () => reject('Rejected!') , 250 )

        // but this does not
        //                       vvvvvvvvvvvvvvvvvvvvvv
        setTimeout( () => reject(new Error('Rejected!')) , 250 )

   });
}
```

I've confirmed that `reject(new Error('Rejected!'))` works as expected in vanilla node. It also works when attached to the chain returned by a `TextDocumentContentProvider`.  

Same result if the extension is setup into `~/.vscode/extensions` and run without the debugger.

**Comment by weinand** [comment]
Since the problem occurs even if not running the extension in the debugger, it is not a debugging issue.

**Comment by jrieken** [comment]
With ` setTimeout( () => reject(new Error('Rejected!')) , 250 )` and `   .catch( err => window.showErrorMessage(err) )` the type of `err` is *not* `string` but `Error`. However, the `show[Information|Warning|Error]Message`-function expect a string
