### ISSUE TITLE
Allow changing 'Free' label in the extension gallery

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#3036]
In Visual Studio Code marketplace/gallery all extensions are currently labeled as 'Free':
![screen shot 2016-02-16 at 9 37 52 am](https://cloud.githubusercontent.com/assets/979966/13063167/01568436-d491-11e5-8799-b137db1b11be.png)

However ours is not free and requires a license. Is there a field in `package.json` or some other way to change the label?

**Comment by egamma** [comment]
@joaomoreno @seanmcbreen do you know? I'll also check with the market place team.

**Comment by egamma** [comment]
We had some discussion on this. Our conclusion was that the wallaby extension **is** free, it is the backend service that requires a license. So the market place shows the right information about the extension. Our suggestion is to clarify this in the `Readme.md`. You can also try to add a hint in the description in the `package.json`.

My understanding that support for paid extensions is on the backlog of the market place.

**Comment by ArtemGovorov** [comment]
Thanks Erich, makes sense. Will update the readme file.

**Comment by ArtemGovorov** [comment]
Though it'd be great to be able to specify a 'Trial' label for the extension like they can in Visual Studio marketplace:

![screen shot 2016-02-16 at 10 22 07 pm](https://cloud.githubusercontent.com/assets/979966/13076130/ec22f070-d4fb-11e5-9c3b-1a300c12b4e4.png)

**Comment by egamma** [comment]
@ArtemGovorov fyi we have added support to label an extension with `preview` https://github.com/Microsoft/vscode-vsce/issues/82#issuecomment-196791767

**Comment by ArtemGovorov** [comment]
@egamma Great, thanks for the update!
