### ISSUE TITLE
Bug: Improper syntax highlighting in JS

### ISSUE THREAD

**Issue by anaskhan96** [Microsoft/vscode#30362]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.5
- Theme: Solarized Dark

Other DOM functions apart from `getSelection()` shown below follow the same improper highlighting as well, i.e. the first letter of the function isn't highlighted.

![image](https://user-images.githubusercontent.com/23240518/28045683-3064e166-65fc-11e7-9764-65bab7833374.png)

**Comment by mjbvz** [comment]
Can you please share the source along with the screenshot? Also does this still happen if you disable extensions?

**Comment by anaskhan96** [comment]
I can't share the source file for legally binding reasons.
Yes, it does happen even on disabling any or all extensions.

However, I just noticed that this problem only seems to occur when the file has template insertions, for example `{{ variable }}`.

**Comment by mjbvz** [comment]
@anaskhan96 Please reduce the source code to a minimal example that shows this problem. You should be able to strip out any proprietary info. It doesn't matter if the code runs, all I'm interested in is its structure
