### ISSUE TITLE
BUG: PHP code is not recognized when within <script> tag and comment issue after </script> tag when PHP included between tags

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#30368]
VSCODE: Version 1.13.1 (1.13.1)
OS VERSION: MacOS 10.12.5 

DETAILS:

1. Color coding in <script> tag is shown as Javascript not PHP
2. After the ending </script>, HTML blocks are not commented out  _(Note: this does not happen if PHP is not placed inside <script></script> tags!_

Steps to Reproduce.

1. Create .php file
2. 
```
<html>
<body>
<script>
<? 

// PHP here is color coded as Javascript not PHP
 
?>
</script>
<!-- <div> this comment is not grayed out, shows as color coded html </div> -->
</body>
</html>

```

**Comment by roblourens** [comment]
Fixed in 1.14 - #28354
