### ISSUE TITLE
Add editorCursor.background

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30361]
We are adding foreground and background settings for the terminal cursor -
 https://github.com/Microsoft/vscode/issues/30294

Currently when using a block cursor, the editor sets the color of the overlapped character to the opposite of the cursor foreground color. But you can end up with strange color combinations, and it's not necessarily high contrast. For example with `"editorCursor.foreground": "#808080"`, the character color is also #808080.

**Comment by rebornix** [comment]
@roblourens I like this idea. The only catch is they way we set CSS make it confusing

`editorCursor.foreground` --> `.cursor { background: } `
`editorCursor.background` --> `.cursor { color: }`

**Comment by roblourens** [comment]
Yeah, @Tyriar and I were just talking about that. I think it makes sense that the cursor "foreground" is the color of the actual cursor block, and the 'background' is the color of the overlapped character. The implementation just looks odd.

**Comment by Tyriar** [comment]
Yeah it's confusing, styling the block cursor are the opposite of what you would intuitively think, but it feels correct for the other cursor styles.
