### ISSUE TITLE
Applying workspace settings for multiple folders requires multiple settings.json files

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#30375]
When two folders or more are open in the same workspace and the view is split, displaying one file on the left from folder A and another file on the right from folder B, the settings.json file is only applied to the file in folder A when you create a new settings.json file with the palette:

- CTRL + SHFT + P
- Preference: Open workspace settings

**settings.json**

```
// Place your settings in this file to overwrite default and user settings.
{
     "editor.wordWrap": "on",
      "files.autoSave": "onFocusChange",
      "editor.fontSize": 13
}
```

I don;t know if this is by design, but for now, I have to copy the settings.json file from folder A to folder B to have the same font size in the editor on both open files. One would expect to have settings like these applied to all open folders by default.

- VSCode Version: 1.14.0-insider (64 bit)
- OS Version: Windows Server 2012 64 bit

Steps to Reproduce:: [StackOverflow question](https://stackoverflow.com/questions/45028263/setting-editor-fontsize-for-multiple-folders-in-vs-code)

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@DarkLite1 Thanks for filing the issue. It seems you are in multi-root workspace environment which is not fully functional and is still in preview and development mode. 

I am currently working in supporting workspace settings in a multi-root workspace which will fix your problem.

**Comment by sandy081** [comment]
Duplicates #29456
