### ISSUE TITLE
Open HTML file in default browser

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#30371]
- VSCode Version: 1.13
- OS Version: Mac OS x

Steps to Reproduce:

1. right click on any static html file
2. a menu should appear to open the file in default browser.

Now have to reveal in finder and then have to open from there to chrome.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Try the marketplace. There are a number of extensions that provide this functionality already: https://marketplace.visualstudio.com/search?term=open%20in%20browser&target=VSCode&category=All%20categories&sortBy=Relevance
