### ISSUE TITLE
Electron  global variable error 

### ISSUE THREAD

**Issue by GryoMx** [Microsoft/vscode#30376]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.create a electron project
2.create file cookie.js,code as blow
```
//demo
'use strict';
let cookies = {};
const fun = {
    getAllCookie: function () {return cookies;},
    getCookie: function (name) { return eval("cookies['" + name + "']");},
    setCookie: function (name, value) { cookies[name] = value;}
};
module.exports = fun;
```
3.open file main.js 
const cookies = require('./cookies.js');//declare as global
cookies.setCookie('curSystem', process.platform);//code in function
4.open file index.html
const cookies = require('electron').remote.require(`${__dirname}/cookies.js`);//declare as global
cookies.setCookie('UserID','test');;//code in function
console.log(cookies.getAllCookie());
5.when test using cmd.exe or electron-packager,it works all right.cookies contains curSystem and UserID
6.when debug with vscode cookies only contains UserID,and i don't know why

**Comment by mjbvz** [comment]
This looks like an question on debugging electron with vscode rather than any issue with vscode . Please try searching for info about debugging electron apps with vscode or asking on [stackoverflow](https://stackoverflow.com)
