### ISSUE TITLE
IntelliSense for Mac isn't working properly

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#30373]
- VSCode Version: 1.13.1
- ProductName: Mac OS X
- ProductVersion: 10.12.5
- BuildVersion: 16F73

![image](https://user-images.githubusercontent.com/30043375/28055782-16f2cf0a-6623-11e7-9d80-81b4d9240468.png)

```
[js] Cannot find name 'process'.
any
```

But if I download for e.g. `express` with Yarn or NPM I get the autocomplete for Node.js built-in objects and so on. As I get VS Code doesn't download typescript declaration file. It is related with Automatic Type Acquisition (ATA)?

**Comment by bsvipas** [comment]
I tried to add `jsconfig.json` file empty or with `compilerOptions` and it was same.

**Comment by bsvipas** [comment]
Same for `require`, `module` and so on.

![image](https://user-images.githubusercontent.com/30043375/28077250-eae8442a-6669-11e7-940f-2cb2146919b3.png)

**Comment by mjbvz** [comment]
Yes, we don't include typings for node by default. The presence of a standard node import like `fs` or `path` should trigger them being automatically included but you don't seem to have any of these imports

Just run `npm install @types/node` to install them in  your workspace manually or list `node` types in the `jsconfig.json`:

```json
{
    "compilerOptions": {
        ...
    },
    "typeAcquisition": {
        "include": [
            "node"
        ]
    }
}
```

**Comment by bsvipas** [comment]
@mjbvz Thanks!
