### ISSUE TITLE
[php] Add color to class and/or function names in Dark+ theme

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#3037]
![vscode-php-whiteness](https://cloud.githubusercontent.com/assets/1007463/13063279/b5028af4-d403-11e5-963c-2062fbd1d7a0.png)

Everything is still so white! Can we get some color for function/class names?

**Comment by brunnopleffken** [comment]
Indeed. Maybe borrow some colors from the TypeScript syntax highlight.

<img width="592" alt="screen shot 2016-03-07 at 17 25 54" src="https://cloud.githubusercontent.com/assets/3427344/13582204/c8dda5fe-e489-11e5-9be2-61f56c1cf8d7.png">

**Comment by roblourens** [comment]
Looks much better now, anything else to be done?

![image](https://cloud.githubusercontent.com/assets/323878/25768733/dc3e81d0-31be-11e7-92fc-2a3010a85861.png)
