### ISSUE TITLE
Git: Add a substitution variable for the current git repository

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#30378]
The equivalent of:

`
$(git rev-parse --show-toplevel 2>/dev/null)
`

would be really useful...

**Comment by joaomoreno** [comment]
Where would you use it in?

**Comment by Gruntfuggly** [comment]
In the browse and include paths used by the cpp plugin - assuming it would be available...

**Comment by joaomoreno** [comment]
OK, wouldn't the current workspace path be enough for you?

**Comment by Gruntfuggly** [comment]
No - unfortunately our code base is large, so I have multiple workspaces within the same repo. The browse and includes paths have several entries which are outside the workspace, but within the git repo. Relative paths don't always work, but some workspaces are at different levels within the repo. The repo can also be checked out in any other folder. So the one thing that is consistent between them all is the root of the repository.

**Comment by Thaina** [comment]
Also want this feature. I want to set environment variable for `launch.json` and `tasks.json` to match the current branch name

**Comment by Thaina** [comment]
@joaomoreno Isn't this already be a variable in vscode?

https://github.com/Microsoft/vscode/blob/eac49a321b84cb9828430e9dcd3f34243a3480f7/extensions/git/src/statusbar.ts#L36

Can we access it in variable substitution?

**Comment by db4** [comment]
@joaomoreno, I'm second to @Thaina question. Maybe `$(git-branch)` can be accessed via `${command:CommandID}` syntax?

**Comment by Gruntfuggly** [comment]
@Thaina You can actually do this for the tasks.json file. You can add 
```
            "options": {
                "env": {
                    "WHATEVER": "VALUE"
                }
            }
```
The cool thing I found out today is that you can do something like:
```
"GIT_BRANCH":"echo `git rev-parse --abbrev-ref HEAD`"
```
which will set $GIT_BRANCH to your current branch, which can be accessed using ${GIT_BRANCH} in the command...

**Comment by Thaina** [comment]
@Gruntfuggly I suspect that it only be accessed in command which will execute that. If I access environment variable directly in the code would it be the branch name or that git command text?

**Comment by Gruntfuggly** [comment]
@Thaina I currently do:
```
           "command": ". ${WORKSPACE}/env.sh; qmake <etc.> ; make <etc.> \"",
            "options": {
                "env": {
                    "WORKSPACE": "`echo $(git rev-parse --show-toplevel 2>/dev/null)`"
                }
            },
```
Which finds the root folder of the git repo and exectutes the env.sh script in the right place, but also the qmake has access to the WORKSPACE variable and is used to pull in other files.

_I've realised I put the quotes in the wrong place in my first example (fixed now)._

**Comment by Thaina** [comment]
I have found that vscode can make variable substitution with command

https://code.visualstudio.com/docs/editor/variables-reference#_settings-and-command-variables

Do we have git command that return branch?

**Comment by Thaina** [comment]
@joaomoreno Really, can we have a command that just return that `$(git-branch)` variable?

**Comment by joaomoreno** [comment]
Since you can have multiple git repositories open, what would you expect in that case?

**Comment by Thaina** [comment]
@joaomoreno It should be the git repo of the project itself when it running or debugging

**Comment by joaomoreno** [comment]
We can implement it as a command. But commands don't have any context...

**Comment by Thaina** [comment]
@joaomoreno OK but then what would happen in this line of code?

https://github.com/Microsoft/vscode/blob/eac49a321b84cb9828430e9dcd3f34243a3480f7/extensions/git/src/statusbar.ts#L36

**Comment by joaomoreno** [comment]
That is an icon.

**Comment by Thaina** [comment]
Still not possible?
