### ISSUE TITLE
Debug async await with vscode

### ISSUE THREAD

**Issue by libchaos** [Microsoft/vscode#30382]
- **node version 8.1.2**
- **vscode version 1.13.1**
- description:
 - when debugging such code as follows,  I countered such problems
    I made a breakpoint at line ```const v = await add2(10)``` and I counld not come into 
    ```add2```function.
    but when I made a breakpoint at line ```const x = 1```, then I could come into  function ```add2```

```javascript
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 500);
  });
}
async function add2(x) {
  var a = await resolveAfter2Seconds(20);
  var b = await resolveAfter2Seconds(30);
  return x + a + b;
}
async function b() {
  const x = 1;
  const v = await add2(10)
  console.log(v);

}
b().then(() => console.log('done'))
```

**Comment by ShiftySituation** [comment]
I've noticed a similar issue but only happens after the awaited functions run the first time... ie; make a imperative selection that triggers an awaited async call... the code runs in order as it should.  Make another selection to trigger it again and the awaited functions are not awaited and any code after the awaited function runs immediately, then the async functions finish.

**Comment by Deilan** [comment]
Somewhat related with #11645.

**Comment by roblourens** [comment]
Are you using typescript or babel or any other transpilation, or is this running native async/await in node?
