### ISSUE TITLE
Untitled files needs to be saved or discarded when you open a folder

### ISSUE THREAD

**Issue by aaccioly** [Microsoft/vscode#30385]
- VSCode Version: 1.13.1
- OS Version: Windows 7 Enterprise, Windows 10 Pro and openSUSE Tumbleweed (probably OS independent)

Steps to Reproduce:

1. Start with an empty workspace
2. Create a new file (<kbd>Ctrl</kbd>+<kbd>N</kbd>)
3. Type something (don't save the file)
4. Open any Folder... (<kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>O</kbd>)

What happens?

A prompt is displayed asking if I want to save the file:

![Confirm Dialog](http://i.imgur.com/x70JNug.png)

<kbd>Save</kbd> - Correctly assumes the folder that you are opening
<kbd>Don't Save</kbd> - Discard the file
<kbd>Cancel</kbd> - Leave the file as is, folder will not be open

Desired behavior: 

There should be a way to "bind" the unsaved file to a folder without saving it. My suggestion is that instead of the Confirmation Dialog, "Untitled" files are automatically moved to the folder context.

Extra notes: 

Currently I can't find a way to bind untitled files to a folder context or even to different window. Drag and drop between windows does not work either.

The new behavior would be very welcome for users that uses vscode to take notes. 

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@bpasero if we can add folders without reloading extensions eventually this would be trivial, just add the folder and keep the untitled file as is. Trying to support this with the reload seemed like it would be more effort than it's worth. Thoughts?
