### ISSUE TITLE
String enums are not recognized by intellisense (TypeScript 2.4.0 + Latest vscode)

### ISSUE THREAD

**Issue by SlimDogs** [Microsoft/vscode#30386]
- VSCode Version: 1.13.1
- OS Version: Mac OS Sierra 10.12.3

Steps to Reproduce:

1. Create a file for newly introduced string enum e.g. test.enum.ts with such content:
```
export enum DefaultImages {
  defaultMerchantHeader = "/assets/default_merchant_header.jpg"
}
```
2. Create another file where you import string enum and try to set variable with it e.g. logic.ts
`const test = DefaultImages.defaultMerchantHeader;`

While compilator doesn't complain and compiles code nicely (using angular-cli setup) vscode is highlighting the usage of string enum as not correct...

Screenshots:
http://imgur.com/0a5mqqO

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Please try in VSCode 1.14. I see this working properly:

![screen shot 2017-07-11 at 11 00 27 am](https://user-images.githubusercontent.com/12821956/28082741-28e24f6a-6628-11e7-82b6-14d00a871cdc.png)

Also please make sure that TS 2.4.1 is active in your workspace: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by SlimDogs** [comment]
Yes, newer version fixed it :) At the moment when I was posting it there were no updates available yet... :)
