### ISSUE TITLE
[Terminal] Can't follow link which ends with #something

### ISSUE THREAD

**Issue by vladamx** [Microsoft/vscode#30389]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.10.0-26-generic
---

Steps to Reproduce:

1. Run npm/yarn info package
2. See urls like: https://github.com/npm/node-semver#readme can't be followed via ctrl+click

**Comment by Tyriar** [comment]
Seems to work in both 1.13 and 1.14?

![image](https://user-images.githubusercontent.com/2193314/28082264-dacba53e-6626-11e7-8b54-f838f3043bfd.png)

Perhaps the problem was that the line was wrapped?
