### ISSUE TITLE
Typescript highlighting after "extends" keyword

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#3038]
It seems everything after "extends" turns into an identifier, when it should just be the very next word since there's only single inheritance. This is a problem if you implement an interface...

![vscode-implements-keyword](https://cloud.githubusercontent.com/assets/1007463/13063687/d2bca7f6-d407-11e5-91a5-37ba6b8cc4e7.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#89
