### ISSUE TITLE
(Hover inspecting) Make JS/TS debugging great again

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/vscode#30399]
This is more a subjective plea/rant then a bug report itself.

I remember back in ~jan/2017, hover tooltips used to work very well. Even if maybe they had a more humble formatting (ex: a simple JSON.stringify of the object).

Then in some release around february or march we got things like the new node inspector protocol, and some changes in what the debug console uses as a source (in practice, making a lot of messages disappear from it, even if it is not VS code fault).

Another thing that maybe entered into account was the increase of usage of async/await (which breaks debug stacks I guess). Gets worse with TS+sourcemaps.

Since then, debugging has never been the same. Hovering over variables rarely yield something (sometimes it works, sometimes it takes a bit of time). Now I dont even bother hovering anymore, I just go straight to typing the variable in the console or in the watch.

Not to mention that using `console: "integratedTerminal"` became mostly mandatory, since who knows when you will be losing any message.

So, probably things are this way for a reason, probably I'm doing something wrong, and certainly I should help instead of ranting. Just wanted to let this out. Thanks for all the great work!

**Comment by roblourens** [comment]
> and some changes in what the debug console uses as a source (in practice, making a lot of messages disappear from it, even if it is not VS code fault).

I'm not sure what you're talking about. Missing messages that don't go through `console.log`? https://github.com/Microsoft/vscode/issues/19750 - that's the only issue with the console that I'm aware of.

> Another thing that maybe entered into account was the increase of usage of async/await (which breaks debug stacks I guess). Gets worse with TS+sourcemaps.

Using async/await can lead to confusing stacks just by the nature of how async debugging works. Is there something that vscode is doing wrong compared to chrome devtools (or legacy vs inspector) her?

**Comment by wkrueger** [comment]
So, now to bring a bit of objectiveness ill try to print some examples as I come into them... I actually mentioned many different things...

Example from async code
![image](https://user-images.githubusercontent.com/2209181/28078343-e90d01ec-663a-11e7-85ff-1000577b657b.png)

In that snippet, `mainPersistedSubject` can be obtained through watch (or typing in console) but when hovering it a tooltip will never be shown.

**Comment by roblourens** [comment]
Yeah it seems that async/await transpilation would exacerbate the problem of hovering across scopes from #30286.

**Comment by wkrueger** [comment]
Hmm, yeah, i think #30286 and #19750 mostly covers it all.

Personally, I think those 2 issues have a big impact in the debugging experience. Naming it: I can still do debugging, but it is now a lot less pleasant/straightforward. Gets even more impact for new users.

Closin it, ty!

**Comment by roblourens** [comment]
If there's a particular library or another scenario that's impacted by #19750, please weigh in on that issue, to help me understand the scope. One way around it would be to add a launch config option to simply use stdout instead of the debug protocol messages.

**Comment by wkrueger** [comment]
That would definitely help. While the main case here is winston (already mentioned in that thread), we never know when one of the libs we use will have some special logging schema. I should pay attention and post here if I see something.

Ideal scenario would be having both in the same tab (but that probably will bring duplicates). Even if the console tab is slower. But being able to tweak that is already great.

Using `console:integratedTerminal` is a bit bad since that enforces changing context between the console and the terminal for the usual debugging.
