### ISSUE TITLE
VScode doesn't understand its scope C-CPP plugin

### ISSUE THREAD

**Issue by rohitp93** [Microsoft/vscode#30396]
If you try to jump from function to function declaration of an interface. Then the scope is too large if the function used a lot in the code base. So this can be considered an issue especially if you are a user coming from Eclipse. Any plans of creating a better send of scope or context in the show declaration functionality?

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 3.10.0-327.36.3.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.10|
|python|donjayamanne|0.6.7|
|Theme-Blackboard|gerane|0.0.2|
|hopscotch|idleberg|0.1.5|
|plantuml|jebbs|2.0.1|
|intellij-idea-keybindings|k--kato|0.2.12|
|cpptools|ms-vscode|0.12.0|
|trailing-spaces|shardulm94|0.2.11|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.10.1|
|markdown-all-in-one|yzhang|0.7.2|
|Material-theme|zhuangtongfa|2.9.2|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#876
