### ISSUE TITLE
open editors in explorer section is not supposed to be important.

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#30398]
Open editors is not so important when tab is available in vs code. open editor and tab are doing just same there. I guess Tab is only better. 
This is just a suggestion but I always appreciate the decision what vs code team is making to make vs code a better editor. 
Thanks vs team

**Comment by bpasero** [comment]
You can hide the "Open Editors" section via this setting: `"explorer.openEditors.visible": 0`
