### ISSUE TITLE
Code chokes on bunyan

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#30390]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|pgsql|doublefint|0.0.8|
|EditorConfig|EditorConfig|0.9.3|
|JSDocTagComplete|HookyQR|0.0.2|
|vscode-esformatter|howardzuo|1.5.2|
|output-colorizer|IBM|0.1.2|
|vscode-puglint|mrmlnc|2.3.0|;

---

Steps to Reproduce:

When I open https://github.com/trentm/node-bunyan/blob/13c86f1d15c192f7b4f73c0cbef18f37606d81ea/lib/bunyan.js Code will freeze for about 1 minute.

I have this file in my project tree and it is part of a stack trace. I navigate to the file by clicking a link that is located in the **Debug Console** panel.

**Comment by weinand** [comment]
@oliversalzburg do you see the freeze when selecting the file in the VS Code explorer (instead of clicking on a link in Debug Console)?

**Comment by oliversalzburg** [comment]
@weinand Interestingly, when I navigate to the file in the explorer panel and open it, Code doesn't freeze.

When I Ctrl+P and select the file, Code freezes. However, something is a bit weird here:

![image](https://user-images.githubusercontent.com/1658949/28074513-0d587e82-6659-11e7-8700-5381823d4502.png)

The project I have currently open lives in `C:\Users\OliverSalzburg\FairManager Projects\core-dms`. So the two `bunyan.js` files should be identical. However, when I open the top one, Code does not freeze. When I open the bottom one, Code freezes.

**Comment by weinand** [comment]
@oliversalzburg thanks for this info.
The second bunyan.js in the QuickPick is probably the one opened from the debug console. It was not recognized as a workspace file, so that's the reason why it got an absolute path.

It would be great if you could temporarily replace the space character in "FairManager Projects" by an underscore (or any other character) and see whether this makes a difference. I suspect that the space is the problem. But this is just a wild speculation... 

@michelkaporin does this ring a bell with you? You worked on the link detection lately, correct?

**Comment by oliversalzburg** [comment]
I left work for the day and will have to verify that tomorrow.

However, I tried to repro the issue at home and was not able to. I have the identical project structure here. No matter how I open `bunyan.js`, no freeze. I was not able to create a scenario where I would get the path in the Debug Console though. In case that actually is relevant to the issue.

I also tried to open other files from the bunyan project and other dependency's files, both at work and on my home workstation. None of those caused any freezes.

**Comment by oliversalzburg** [comment]
Alright. I was able to repro the issue at home. It is really the link in the debug console that causes the behavior.

```js
process.stdout.write( "at this.works (C:\\Users\\Oliver\\FairManager Projects\\core-dms\\node_modules\\bunyan\\lib\\bunyan.js:1:1)\n" );
process.stdout.write( "at this.will.freeze (C:\\\\Users\\\\Oliver\\\\FairManager Projects\\\\core-dms\\\\node_modules\\\\bunyan\\\\lib\\\\bunyan.js:1:1)\n" );
```

I didn't try to simplify the path further. But I assume the double-backslash is to blame.

**Comment by oliversalzburg** [comment]
Also verified that it is still present in 1.14.0

**Comment by michelkaporin** [comment]
Seems like an issue with the way link is opened. I am calling `editorService.openEditor()` for that, might be that I am passing wrong arguments or should migrate detector to fit multi-root. I will get back once I looked into it.

**Comment by weinand** [comment]
Too old. Closing.
