### ISSUE TITLE
Attempting to start from command line fails with ASN error

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#30394]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|githistory|donjayamanne|0.2.1|
|python|donjayamanne|0.6.7|
|gitlens|eamodio|4.3.1|
|Go|lukehoban|0.6.62|
|cpptools|ms-vscode|0.12.0|
|Ruby|rebornix|0.12.1|
|java|redhat|0.7.0|
|vscode-open-in-github|sysoev|1.6.0|
|vscode-proto3|zxh404|0.1.1|;

---

Steps to Reproduce:

Tried this in two different directories, both when the process was and was not already running:
```
$ code --verbose .
_RegisterApplication(), unable to get application ASN from launchservicesd, and this application requires an ASN, so aborting.  error=#-1.
```

**Comment by josh-tepper** [comment]
Weirdly enough, restarting the iterm terminal session seems to resolve.  It also was resolved this issue with git:
https://gitlab.com/gitlab-com/support-forum/issues/1406

Not sure what caused this bad state

**Comment by chrmarti** [comment]
I'll close this if you agree. Seems like a transient problem.

**Comment by josh-tepper** [comment]
sounds good
