### ISSUE TITLE
Allow Opening Symlink Directories

### ISSUE THREAD

**Issue by premiercoil** [Microsoft/vscode#30391]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. "Open Folder" -> select a symlink/shortcut folder
2. Silently fails

Opening a local folder containing the linked folder works and allows browsing down into the linked folder.

**Comment by bpasero** [comment]
Still happens?
