### ISSUE TITLE
Problem with HTML pretty print

### ISSUE THREAD

**Issue by fredinger** [Microsoft/vscode#30392]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|vscode-html-css|ecmel|0.1.7|
|php-intellisense|felixfbecker|1.4.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Create an HTML-Page
2. In the body, you have to use an svg tag and put in some other elements (<g> and inside <g> -> <path>, <rect> etc.)
3. Press Save or Alt+Shift+F -> wrong format (could be because of the /> ending or because vsc doesn't recognize the svg - Tag)
4. The format in my case was:
`   (tab) <svg>
    (tab*2)<g class="svgContent">
    (tab*2)<path class="..." d="..."/>
    (tab*2)<rect class="..." x="50" y="25" height="40" width="45"/>
     (tab*2)<rect class="menuStripe" x="56" y="32" width="34" height="5"/>
     (tab*2)<rect class="menuStripe" x="56" y="42" width="34" height="5"/>
     (tab*2)<rect class="menuStripe" x="56" y="52" width="34" height="5"/>
    (tab*2)</g>
    (tab*2)</svg>`

**Comment by chrmarti** [comment]
Does it reproduce when launching with `code --disable-extensions`?

**Comment by fredinger** [comment]
I just disabled the vscode-JS-CSS-HTML-formatter by lonefy. Now it works! Thank you very much for the tip!
