### ISSUE TITLE
Emmet bem filter problem

### ISSUE THREAD

**Issue by roamn** [Microsoft/vscode#30395]
- VSCode Version: 1.13.1
- OS Version: Windows 10/64bit

Emmet "bem" filter does not work properly and with `"emmet.useNewEmmet": true,` does not work at all.

Steps to Reproduce:
![3215](https://user-images.githubusercontent.com/5599071/28075143-3c90e50e-6663-11e7-81dc-eaea4e24d150.jpg)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@sergeche You mention that we do support bet here: https://github.com/emmetio/expand-abbreviation#options 

When I try the add-on I get the below for `div.hello>.--there`

```
<div class="hello">
         <div class="undefined--there"></div>
</div>
```

Am I missing something?

**Comment by sergeche** [comment]
Filters are removed from new Emmet in favour of explicit options.

Seems like a bug with `div.hello>.--there`, but actual (working) abbreviation should be `div.hello>.-there`

**Comment by sergeche** [comment]
Please create a new issue with your abbreviation in Emmet repo

**Comment by ramya-rao-a** [comment]
Thanks @sergeche 
Created https://github.com/emmetio/expand-abbreviation/issues/6

Another question, what are your plans on other filters like the ones mentioned in https://docs.emmet.io/filters/

And how do you plan to surface the bem add-on for eg. for your atom plugin
Previously the user had to type `div.hello>.-there|bem`, do you plan to retain this format?

**Comment by ramya-rao-a** [comment]
The current way of using filters ( using `|bem` in the end) will be supported in the new model as well

**Comment by sergeche** [comment]
Filters are deprecated in favour of expand abbreviation options. Most developers don’t write filters explicitly, they configure default set of filters in Emmet  snippets (old version).

**Comment by ramya-rao-a** [comment]
How do you plan to surface that in the new Emmet?

**Comment by roblourens** [comment]
Verified that `|bem` works
