### ISSUE TITLE
Autocomplete advanced snippet sorting

### ISSUE THREAD

**Issue by whitevo** [Microsoft/vscode#30409]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
javadebugger|don|0.1.2
java|red|0.7.0
vscode-lua|tri|0.5.0

---

Steps to Reproduce:

1. create several custom custom snippets (Examples down)

```
"playerPos": {
		"prefix": "playerPos",
		"body": "local playerPos = player:getPosition()",
		"description": "playerPos"
	},
	"objectID 1": {
		"prefix": "playerID",
		"body": "local ${1:player}ID = ${1:player}:getId()",
		"description": "objectID"
	},
```
2. when snippets created and I write on new file: player
I get over 10 suggestions as to be expected.
So first time I write out the full word playerPos to get the snippet.

Next time when I start writing: player
First 3 suggestions should be last 3 used
Then next 3 suggestions for most used snippets (don't overlap)
Rest of suggestions param/func/snippets which used above lines
If suggestion bar not filled up by now then can continue as it is right now

(of course all suggestions should start or be similar with prefix)

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Can you provide a screen shot? In what language does this happen? What are the other suggestions?

**Comment by whitevo** [comment]
I'm not aware if this happening anywhere in any language.

Under other suggestions I meant what it displays right now,
I don't know how is the order structured.

How do I provide screenshot if this feature does not exist?

Currently what it shows:
![image](https://user-images.githubusercontent.com/10964567/28110864-4db1bc34-66fc-11e7-9469-6d8778648a54.png)
Now when I choose my option and go to next line:
![image](https://user-images.githubusercontent.com/10964567/28110920-78bbb704-66fc-11e7-834c-dafffe1b159e.png)
Currently the first suggestion is parameter? And then suggest me the full list again with that unknown order, But I would prefer if the next suggestion would be last one what I just used.

You understand? Idea is to make the suggestion predict (with simple formulas) what I'm about to write next.

**Comment by jrieken** [comment]
Thanks for getting back to me. The little `ABC` icon means that it is a textual suggestion that was computed by looking at what words have been typed so far (`function`, `func`, `player`, etc). The other suggestions are snippet suggestions which by default sort below other suggestion. Extensions might also add more suggestions to the list. 

There are a few options to tweak this behaviour. Use `"editor.wordBasedSuggestions"` to control if you want suggestions that are computed off words, use `"editor.snippetSuggestions"` to change how snippets suggestions are sorted wrt other suggestions. 

Last, remembering what suggestion was selected last and boosting that is tracked here: #22839. Closing this as dupe and question

**Comment by whitevo** [comment]
I already have:
"editor.wordBasedSuggestions": true
"editor.snippetSuggestions": "inline"

remembering last suggestion, you pointed to topic which has no answers how to make it work for me.

I know what are these suggestions. I am asking how can we make the suggestions sorted in different order or will this feature come.

**Comment by jrieken** [comment]
> remembering last suggestion, you pointed to topic which has no answers how to make it work for me.

It's label as feature request. That means it is not available yet and still needs to be implemented. I'd suggest to subscribe to that issue and then notified when schedule and tackle this. Also, pull requests are always welcome.
