### ISSUE TITLE
Rename/Delete/Duplicate/Move the currently open file

### ISSUE THREAD

**Issue by adrianoresende** [Microsoft/vscode#30400]
It would be good to reopen this issue #1886

**Comment by mlhamel** [comment]
Yes having this natively would be amazing

**Comment by MikeWeller** [comment]
Yes, I just tried to find a way to rename the currently open file/tab... this apparently doesn't exist at all, and when I renamed the file via the Finder (macOS) the tab got closed in vscode.

**Comment by austenc** [comment]
Agreed, surprised a move/rename feature isn't included by default. This is something that should be in core functionality via the command palette (or whatever VSCode calls it) accessible with `Cmd+Shift+P`.

This may be an extension already, but shouldn't have to be.

**Comment by mupkoo** [comment]
I think that this counts as core functionality. Shame that I had to search in Google and find out that I need an extension to have this.
