### ISSUE TITLE
multiple line indent is blowing my code

### ISSUE THREAD

**Issue by juliencousineau** [Microsoft/vscode#3040]
When I do a multiple line indent : Shift + tab

It erase my code and when I do cmd-z . it blew it worst... I'm stuck !

**Comment by xujihui1985** [comment]
yes I have the same problem, I'm using Version 0.10.8 (0.10.8)
![image](https://cloud.githubusercontent.com/assets/1619030/13066562/53200e98-d4a2-11e5-81c9-78be6f444d4b.png)

**Comment by egamma** [comment]
Sorry this is #2829. Work arounds are described here: https://github.com/Microsoft/vscode/issues/2829#issuecomment-182485227

closing as a dup.
