### ISSUE TITLE
Quote marks are doubled when typing inside of other quote marks

### ISSUE THREAD

**Issue by Brickcaster** [Microsoft/vscode#30401]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.Create a string (eg: type a single quote ( ' )).  It's pair is created automatically ( '' )
2.Type the other kind of quote ( " ).  Its pair is created automatically ( '""' ).

Expected behavior: automatic quote paring does not occur inside strings.

This behavior is frustrating as it makes it harder than it needs to be to build strings.  For example, attempting to type the following will result in extra unwanted quote marks:
`(json_object` = "{'" + foo + "':' + bar '}'

**Comment by rebornix** [comment]
@Brickcaster can you share what file/language you are working on? I can't reproduce this in TypeScript. Besides, can you try our latest Stable 1.14.1?

**Comment by Brickcaster** [comment]
I updated to 1.14.1 and it still happens.  I am working in .lua

Another example of this behavior:
Typing: test = '" + str + '"
Result: test = '""' + str + '""'
expected: test = '"' + str + '"'
Pressing " then backspace deletes both quotes.  I have to press " then delete to eliminate only one for the desired result.

**Comment by rebornix** [comment]
@Brickcaster I didn't reproduce this with lua files in vanilla VSCode

![lua](https://user-images.githubusercontent.com/876920/28341483-d0c1588e-6bc8-11e7-893d-3f6139acfdec.gif)

Did you happen to install any Lua extension which might change this behavior?

**Comment by Brickcaster** [comment]
I think you misunderstand, I'm trying to build a string within a string (I made a big mistake using + operator instead of concatenation operator (..), but that's not related )

My goal is to create a single double quote inside of two single quotes.  I am trying to build json objects in code, which means I need to do:

quote mark .. varname .. quotemark .. colon .. varvalue

so that they can be parsed as json objects.  I build this in lua as a string, which means I need to pass quote marks inside of a string, but I only need one to do this, not a pair.

This means I have to type:

single quote + doublequote + delete key (delete surplus double quote) + right arrow

to open my string, then I can concatenate my variable onto it, then I have to do it again to close the string within a string.

**Comment by Brickcaster** [comment]
I'm just gonna chalk this up to me using the program wrong and not thinking ahead to type between the old and new quote marks.
