### ISSUE TITLE
Allow quick open to filter on folder names by typing folder name after the file

### ISSUE THREAD

**Issue by enozero** [microsoft/vscode#30404]
Quick Open (using `Command P`) is a great tool. However, if you are in a framework like Rails, you'll often have files that are named the same across many different folders, particularly for views. You may have 10s or 100s of `index.html.haml` or `index.json.jbuilder` files. Being able to narrow down the file is practically impossible with VSCode without the ability to also narrow down the folder, which provides a more descriptive name.

It would be great to have Quick Open use the filter to search the names of folders to help narrow down the list and find the file quickly.

**Comment by bpasero** [comment]
@enozero you can type the folder name (before the file name) and it should narrow down, does that not work for you?

**Comment by enozero** [comment]
Ah... interesting. I hadn't ever thought to try the folder before the filename in the quick open tool. My mind automatically thinks of the file name then to narrow down the search from there once I see that the search has too many listings and that I can just keep typing to narrow down the search. Is there a way to allow searching the folder names after the file name? If not, that would be a fantastic addition.

**Comment by ImJeevesh** [comment]
I think it is the filter for files and folders in explorer pane kinda like we have it in Xcode's project navigator.

![screen shot 2017-08-03 at 12 37 39 pm](https://user-images.githubusercontent.com/4705965/28910045-b618c80a-7848-11e7-8fe1-792cc503f6f6.png)

**Comment by mrmachine** [comment]
What about treating `:` as a special character that begins to apply an additional fuzzy filter against the existing results for any additional characters? so you type `inhtm` then you see that there are 100 `index.html.haml` files and you realise you need to filter on directory as well. You could then type `:foo` to filter the existing results and push `foo/index.html.haml` to the top of the result list?

You can probably achieve the same thing now by jumping the cursor back to the beginning of the quick open input field, but this might be a bit quicker to type (and you could then even apply further filters again).

**Comment by aleksey-bykov** [comment]
miss this feature so bad

**Comment by imyellow** [comment]
xcode files filter is very useful, it will show some files always listed in sidebar, but in vscode must Command P everytime when i want to open some files
![image](https://user-images.githubusercontent.com/3270774/50439522-5671fd00-092d-11e9-9916-cada1aa2404c.png)

**Comment by keyeMyria** [comment]
This feature definitely super useful. But, I bet this features will be added after ten years.

**Comment by danielo515** [comment]
I think that directories should be treated as first-class citizens on the quick open. As the requester of this feature, first I think on the file name, then on the folder name. Having to add the folder as a prefix is not practical, and it is not even fuzzy, you need to make a perfect match. Emacs has this feature and it is just wonderful.
To give you an example, to narrow down to a file on `core/api/assignments/edit.js` I want to be able to write `edt assapi`

**Comment by bpasero** [comment]
Pushed a change so that quick open now runs a search over each segment of the input that is separated by space. This allows to further narrow down the results based on additional values. These additional values can either match on the label or description part and their scores will add up for each match:

![Kapture 2020-03-27 at 11 23 48](https://user-images.githubusercontent.com/900690/77746614-76efa200-701d-11ea-98df-3918fabbb990.gif)
