### ISSUE TITLE
Add preference to turn off "recently used tasks"

### ISSUE THREAD

**Issue by todddcls** [microsoft/vscode#30419]
I'm use to using the arrow keys to quickly select which task I want to use.  Now with the addition of this new feature, now the list is constantly changing order.  Please provide a preference to turn this off.

**Comment by Zyphrax** [comment]
Can I revive this feature-request?

It is kinda annoying when you only have 4 tasks that the list is in a different order every time you open it. For example in my Rails project it looks like this:

![image](https://user-images.githubusercontent.com/966500/46837515-a0623280-cd83-11e8-9d3f-00601220f89d.png)

A simple setting to disable the recently used feature would be great.

**Comment by dbaeumer** [comment]
@Zyphrax a PR for this is welcome.

**Comment by crstamps2** [comment]
I would like to tackle this issue. I am going to follow @dbaeumer's suggestion.

**Comment by abhigyank** [comment]
@dbaeumer Hello, I understand that you mean to put the settings in Workbench-> Tasks-> QuickOpen: History` Is this correct?
Also could you help to look into which file I should update in order for the settings to reflect in the actual task list?

**Comment by dbaeumer** [comment]
Yes, `tasks.quickOpen.history` as a name is correct.

- the actual code is in task.contributions.ts
- the recently used list is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/browser/quickOpen.ts#L95
- the schema for the setting is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/jsonSchemaCommon.ts#L11

**Comment by praveentiru** [comment]
@kumarharsh Just wanted to check if this issue is closed with PR from you?

**Comment by geajack** [comment]
Can we get this merged soon?

**Comment by dtwilliams10** [comment]
Is this issue still open to be worked or is it being merged?

**Comment by alexr00** [comment]
I will take a look at the existing PR for this and we'll see if we can get it merged for June :)

**Comment by alexr00** [comment]
Verification steps are the same as https://github.com/microsoft/vscode/issues/80649. If that's verified, then so's this!
