### ISSUE TITLE
Ubuntu - Launching with desktop icon doesn't remember open folders

### ISSUE THREAD

**Issue by xparabolax** [Microsoft/vscode#30412]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
  - Note: This was occurring on the prior version as well.
- OS Version: Linux x64 4.8.0-58-generic (Ubuntu 16.10 64-bit)
- Extensions: none
---

Steps to Reproduce:

1. Install fresh version of VSCode 1.14.0 (cleared local cache files, ~/.vscode, ~/.config/Code)
2. Launch VSCode, open a folder within VSCode, close VSCode (either by top-right X, or Ctrl+Q)
3. Reopen VSCode from desktop icon created by installer

Expected functionality:

VSCode should reopen the previously opened folders

Actual functionality:

VSCode opens to the main startup screen with no folder opened.

I cannot reproduce this by launching a terminal and running /usr/share/code/code. However, if I close the terminal's instance of VSCode and launch one from the desktop, then close that one and open VSCode from the same terminal, the folders remain forgotten (as expected, I think).

I can provide any relevant debugging or screenshots / screencaptures.

As an update, I can confirm clicking "reload" when an extension installs keeps the folders open, for whatever that's worth.

**Comment by nzod** [comment]
As additional data point, Code doesn't reopen folder on Fedora/Gnome either, regardless of the window.restoreWindows value. This behaviour started with 1.13.
