### ISSUE TITLE
Add "Convert to React TypeScript" as a refactoring options 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#30418]
I wrote [this TS AST transformer](https://github.com/lyft/react-javascript-to-typescript-transform) to convert React from JS to TS. It's a good candidate for the new auto-refactoring feature.

**Comment by mjbvz** [comment]
Very nice work

To bring this feature to VSCode, you may want to look into bundling the refactoring into a TypeScript Server plugin. Plugins augment TypeScript editor functionality and can be used on other editors  besides VSCode. Here's a sample plugin with more information on getting started: https://github.com/RyanCavanaugh/sample-ts-plugin

That being said, this refactoring presumably would create a new file ts file from the js one, which I'm not sure a TSServer plugins can do currently.  @rbuckton @RyanCavanaugh any thoughts?

**Comment by RyanCavanaugh** [comment]
Currently refactoring can only make a formatting-style edit (changing content within the set of files the project already knows about)

**Comment by mjbvz** [comment]
Closing as extension candidate / ts plugin candidate
