### ISSUE TITLE
Cannot connect to runtime process, timeout after updating to 1.14.0

### ISSUE THREAD

**Issue by AudioW** [Microsoft/vscode#30416]
- VSCode Version: 1.14.0
- OS Version: W10 - 16237

Steps to Reproduce:

1. Update to 1.14
2. Try build electron app again

Reproduces without extensions: Yes

After updating to 1.14.0 I get following error when attempting launch:
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:29840).

Tried reinstalling all modules, restarted pc

Here is my launch.json:
```js
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        "name": "Launch Electron App",

        "type": "node2",
        "request": "launch",

        "program": "${workspaceRoot}/app/main.js", // important

        "stopOnEntry": false,

        "args": [" --disable-extensions"],

        "cwd": "${workspaceRoot}/",

        "preLaunchTask": "webpack",

        "runtimeExecutable": "${workspaceRoot}/node_modules/electron/dist/electron.exe",

        "osx": { "runtimeExecutable": "${workspaceRoot}/node_modules/electron/dist/electron.app/Contents/MacOS/electron" },

        "windows": { "runtimeExecutable": "${workspaceRoot}/node_modules/electron/dist/electron.exe" },

        "linux": {},

        "env": {},

        "sourceMaps": true
    }]
}
```

**Comment by weinand** [comment]
Please do not use "type" with "node2".
You can control the protocol to use with the "protocol" attribute.
 
What version of Electron are you using?
Does it support the "legacy" or the "inspector" protocol?

**Comment by AudioW** [comment]
Electron Version 1.6.11

When setting protocol to legacy, the application starts. Is this the intended behavior?

**Comment by weinand** [comment]
Yes, Electron supports either "legacy" or "inspector". Since we do not know which version you are using, you will have to specify the protocol.

**Comment by lucas-natraj** [comment]
I'm getting the same issue.. my launch config is 
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "server",
            "cwd": "${workspaceRoot}/dist",
            "runtimeExecutable": "nodemon",
            "runtimeArgs": [
                "--debug=5858"
            ],
            "args": [
                "--watch", "distilled",
                "--ext=*",
                "--verbose",
                "--delay", "5"
            ],
            "program": "${workspaceRoot}/dist/server.js",
            "port": 5858,
            "console": "integratedTerminal",
            "restart": true
        }
    ]
}
```
the config could be wrong, but it was working pretty flawlessly until the update.
i've confirmed that reverting to the earlier version of vscode does NOT fail with `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error).`

**Comment by AudioW** [comment]
Thanks for the fast response!

**Comment by weinand** [comment]
@lucas-natraj set "protocol" to "legacy" and if this works you can remove the "runtimeArgs" and the "port" attributes. VS Code will use the correct port based on the value of the "protocol" attribute.

**Comment by lucas-natraj** [comment]
👍
that worked great.. much obliged!

**Comment by weinand** [comment]
BTW, we spend lots of effort on the release note. You could have found answers about this issue here:
https://code.visualstudio.com/updates/v1_14#_node-debugging

**Comment by lucas-natraj** [comment]
indeed, i've found the documentation excellent.
however, my cursory search (after things suddenly started failing today), yielded this issue so I thought I'd mention it in case others followed the same search route.
apologies for the inconvenience.
