### ISSUE TITLE
Default tasks.json "echo Hello" does not work

### ISSUE THREAD

**Issue by 0not** [Microsoft/vscode#30417]
- VSCode Version: 1.14.0
- OS Version: Windows 10
- Terminal: Git Bash

My default terminal is `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`.

For some reason that I do not understand, arguments are either not passed to bash correctly, or bash does not understand them. The default command is `"command": "echo Hello"`, but bash acts as if it just received `echo` (just prints a newline). Admittedly, I am new to vscode and I've never used tasks before 1.14, so this might just be user error or the fact I'm using bash. However, I figure the default case should work.

This bug prevents me from creating a build task for Haskell `stack`. I would like to do `"command": "stack build"`, but all bash sees is `stack`. My workaround is to do `"command": "\"stack build\""`.

Steps to Reproduce:

1. Delete (or rename) old `tasks.json`.
2. In the top menu select "Tasks > Configure Tasks".
3. In command palette drop-down select the last item, "Others: Example to run arbitrary external command".
4. In the top menu select "Tasks > Run Tasks..." and choose `echo` from the palette drop-down.
5. In the command palette drop-down select the first item "Continue without scanning the build output".
6. Check the Tasks terminal and notice the lack of `Hello`.

tasks.json:
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "echo",
            "command": "echo Hello",
            "type": "shell"
        }
    ]
}
```
Output:
```
> Executing task: echo Hello <



Terminal will be reused by tasks, press any key to close it.
```

This is also reproducible with using `args`, for example, the following doesn't work:
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "echo",
            "command": "echo",
            "args": ["Hello"],
            "type": "shell"
        }
    ]
}
```

This can be fixed by passing the entire command in escaped quotes.

```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "echo",
            "command": "\"echo Hello\"",
            "type": "shell"
        }
    ]
}
```

Output:
```
> Executing task: "echo Hello" <

Hello

Terminal will be reused by tasks, press any key to close it.
```

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Very likely a dup of #28036

**Comment by egamma** [comment]
>This bug prevents me from creating a build task for Haskell stack. 

@0not have you considered implementing a TaskProvider for the Haskell stack tool https://code.visualstudio.com/updates/v1_14#_new-task-api. The benefit of a TaskProvider for stack is that user will not have to customize a task.json file.

**Comment by dbaeumer** [comment]
Fixed for Git bash and WSL bash
