### ISSUE TITLE
Formatting HTML <span> tags sometimes doesn't work

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode#30413]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.3.8
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.9.1
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
python|don|0.6.7
xml|Dot|1.9.2
EditorConfig|Edi|0.9.4
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
vscode-npm|fkn|3.3.0
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.1.1
docthis|joe|0.4.7
Angular1|joh|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.10
easy-less|mrc|1.4.5
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
vscode-icons|rob|7.10.1
code-settings-sync|Sha|2.8.2
python|tht|0.2.3
gitblame|wad|1.11.3
wallaby-vscode|Wal|1.0.52
blade-runner|yuk|1.0.0

(19 theme extensions excluded)

---

Steps to Reproduce:

1. Copy this code:
```
<div class="md-toolbar-tools md-subhead">
    <span class="md-subhead">
          <span>{{ ctrl.category.name }} - </span>
    <span>subject<span ng-if="filteredSubjects.length != 1">s</span> </span>
    </span>
</div>
```
2. Use the command pallete to Format the Document. It doesn't format the second <span> element.

Reproduces without extensions: Yes

**Comment by AskYous** [comment]
I've had this problem for a long time now. It's not due to the new-release.

**Comment by aeschli** [comment]
Check out the setting "html.format.unformatted". It defines the elements that are not formatted. Span is part of this, that's why the inner span is not formatted.
