### ISSUE TITLE
I'm going to have to downgrade from 1.14 - Hangs every 10 - 15 minutes.

### ISSUE THREAD

**Issue by mdenson-dayspring** [Microsoft/vscode#30427]
Upgraded to 1.14 when it available today. Since then I get about 10 - 15 to work and then I get the message (attached).

Going to figure out how to downgrade to the previous version.

- VSCode Version: 1.14
- OS Version: Windows 10 Pro 1703 / Build 15063.413

![screenshot](https://user-images.githubusercontent.com/1828232/28090463-328b5f20-6641-11e7-9b34-6d646fd679ff.png)

Steps to Reproduce:

1. Upgrade to 1.14
2. Use the editor for a few minutes

**Comment by ndneighbor** [comment]
Confirmed that is also breaks the Mac build of 1.14 this one really screwed the pooch.

**Comment by chrmarti** [comment]
Does this reproduce without extensions? Launch with `code --disable-extensions` to check.

**Comment by chrmarti** [comment]
@mdenson-dayspring Also: What kind of files are you working on? Could you attach a screenshot of the window when it is frozen?

**Comment by tuxagon** [comment]
I'm getting this same error on Ubuntu 16.10. I can interact with code when I run `code --disable-extensions`; however, if I disable all installed extensions and restart code, then code will still hang like the OP's issue.

**Comment by chrmarti** [comment]
@tuxagon When starting with `code --disable-extensions` extensions can only be uninstalled, but not disabled. Do you by chance have `atefth.ruby-on-rails-snippets-0.0.1` installed and does uninstalling it resolve the issue?

**Comment by mikejpoirier** [comment]
I experienced the same issue when working on a NativeScript project.  Editing TypeScript files would cause VSCode to hang after just a few key presses.  Rolled back to 1.13.

**Comment by chrmarti** [comment]
Likely #30449, where the TypeScript service eats the CPU. Try https://github.com/Microsoft/vscode/issues/30449#issuecomment-314666925 to help investigate / as a workaround.
