### ISSUE TITLE
"Invalid Argument" error when pressing tab ranomly?

### ISSUE THREAD

**Issue by Niichie** [Microsoft/vscode#30423]
- VSCode Version: 1.14.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open html file
2. Will ranomdly happen after working on it for a bit

![errors](https://user-images.githubusercontent.com/16381287/28088869-1bad232e-6655-11e7-9ddf-d3fdb7377d7d.gif)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
@Niichie do you still run into this problem constantly?

**Comment by itcuihao** [comment]
@Niichie Hi,I have also encountered this problem today,How did you solve it?

**Comment by Niichie** [comment]
I actually didn't do anything. It just stopped doing it suddenly, or at least I haven't done anything to trigger it again. Kind of hard to diagnose since I don't know what was causing it in the first place.

**Comment by EmirHazir** [comment]
I have also same problem :(

**Comment by itcuihao** [comment]
This situation lasted for a few hours. I didn't do anything.It's good now.
