### ISSUE TITLE
右键弹出菜单位置错误

### ISSUE THREAD

**Issue by liqianglai** [Microsoft/vscode#3042]
### 右键弹出菜单位置错误

* 在放大的情况下（ctrl + +)，右键点击弹出的菜单，位置偏左，放大倍数越大，偏左越明显。

**Comment by egamma** [comment]
Hello thanks for the issue, but please report issues in English.

**Comment by TheLevenCreations** [comment]
+1

I met this issue too. If you use Ctrl++ to zoom in and use mouse to right click. The right menu will pop up with a floating position.


See the captured screenshots: https://github.com/TheLevenCreations/electron_typescript_template/blob/master/capture-1.gif

**Comment by liqianglai** [comment]
@egamma My English is very weak, this issue as described in "TheLevenCreations"

**Comment by bpasero** [comment]
@joaomoreno I believe this is an Electron issue?

**Comment by joaomoreno** [comment]
Can everyone suddenly speak Chinese?

Closing as duplicate of #821.
