### ISSUE TITLE
Terminal: Duplicate shell startup lines

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#30429]
- VSCode Version:  1.14.0
- OS Version: <code>Windows_NT x64 6.1.7601</code>

Problem:

In certain codes to sizes opening a new Windows integrated terminal
will show duplicate shell startup lines.
The problem seems associated with the code window size. For instance
A half screen docked code window with the activity and sidebar visible
is more likely to show the problem, but as the left side screenshot shows
even without the sidebar it's possible to happen sometimes.
The problem seems to also happen on the first terminal launch.

Steps to reproduce:

- open code with no terminal
- dock code or size to half screen
- display sidebar - increases probability of Problem
- open new integrated terminal
- observe duplicates startup lines (see screenshot)

![terminal duplicate lines](https://user-images.githubusercontent.com/25272315/28091607-77655ad4-665e-11e7-99ee-112c6ca0022c.png)

**Comment by Tyriar** [comment]
I can't seem to reproduce. I do see weird wrapping happening *during* a resize but there isn't anything we can do about that (related to upstream https://github.com/rprichard/winpty).

**Comment by cleidigh** [comment]
@Tyriar 
Hmm, so you never see duplicate lines of the window shell? I can reproduce this easily, it's quite consistent.
I have a suspicion it may be related to the PTY startup time.
I'll try to look into it more

**Comment by fabiospampinato** [comment]
I think I can reproduce it, it happened to me after writing this code in an extension:

```ts
const term = vscode.window.createTerminal ();
term.sendText ( 'mycommand', true );
```

I thought it had something to do with the process not being ready to accept some text, so I added:

```ts
await term.processId;
```

after those lines, but it didn't work.

The only workaround I found was to wait an extra 100ms or so, but this doesn't seem an optimal solution, probably an older machine than mine, or one under heavy load might require a larger delay.

**Comment by Tyriar** [comment]
@fabiospampinato I think that's unrelated. I suspect this issue is related to winpty acting weird when the console is sized narrowly. You issue is just the text is sent before the pty is ready to pick it up so you see it at the top, this is kind of as designed. You're on a mac right?

**Comment by fabiospampinato** [comment]
Yes, I tried to reproduce it but without success.

I'd try it in my Windows virtual machine as well, if only it didn't break after I upgraded macOS.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
