### ISSUE TITLE
Bug: Select For Compare feature broken

### ISSUE THREAD

**Issue by erikpaasonen** [Microsoft/vscode#30421]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
gitlens|eam|4.3.1
terraform|mau|0.0.16
terraform-snippets|min|1.4.2
PowerShell|ms-|1.4.1
python|tht|0.2.3

---

Steps to Reproduce:

1. Open multiple files
2. In the Open Editors, right-click one file and select Select For Compare.
3. Attempt to right-click on a different file either in Open Editors or in the currently open folder
   Expected: context menu appears, from which "Compare with [filename]" can be selected
   Observed: no apparent response to right-click, no context menu

Reproduces without extensions: Yes

**Comment by erikpaasonen** [comment]
Can no longer reproduce. Feel free to close this issue if you can't either/anymore.

**Comment by wastingoctober** [comment]
I'm still seeing this issue. Right-click doesn't work for me after I select a file to compare.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269

**Comment by dapidmini** [comment]
I'm still getting this issue. how to fix it?
