### ISSUE TITLE
IntelliSense  Not work properly for NodeJS (Latest Version 1.14.0)

### ISSUE THREAD

**Issue by GavinDu** [Microsoft/vscode#30420]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063

The IntelliSense does not work properly for nodejs.

**Comment by mjbvz** [comment]
Please describe what is not working and provide some steps to reproduce the issue

**Comment by GavinDu** [comment]
Before this update, I can have IntelliSense for NodeJS. But now I have to add the jsconfig.json file to enable it.

**Comment by mjbvz** [comment]
We'll only enable node intellisense if we see a standard nodejs import such as `require('fs')`. You can also install the typings by running `npm install @types/node` to install them in  your workspace manually or list `node` types in the `jsconfig.json`:

```json
{
    "compilerOptions": {
        ...
    },
    "typeAcquisition": {
        "include": [
            "node"
        ]
    }
}
```

**Comment by GavinDu** [comment]
@mjbvz I got it. Thank you very much.
