### ISSUE TITLE
VScode randomly inserting multiple cursors

### ISSUE THREAD

**Issue by Niichie** [Microsoft/vscode#30424]
- VSCode Version: 1.14.0 + 1.14.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. open HTML file
2. when quickly adding lines, for example paragraphs, it will randomly insert characters. This happens randomly, but is most easily reproduced if you insert several <p> tags quickly.

![multicursor](https://user-images.githubusercontent.com/16381287/28088942-4e8a6522-6655-11e7-8c72-9ae915cc6551.gif)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
The first auto complete is a code snippet which will insert new cursors for you to replace placeholders. Besides, the snippets are provided by html-snippets.
