### ISSUE TITLE
cut and past NOT working

### ISSUE THREAD

**Issue by w1lujeng** [Microsoft/vscode#30436]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
live-html-previewer|hdg|0.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Does this reproduce when launching with `code --disable-extensions`?
