### ISSUE TITLE
Hover Popup: Ghosting/Overflow into panel when resized

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#30433]
- VSCode Version:  1.14.0
- OS Version: <code>Windows_NT x64 6.1.7601</code>

Problem:

The code lens hover view overflows/partially ghosts into panel
when panel resized with keyboard command Increase View Size.
It does not matter which panel output or terminal is visible.

Steps to reproduce:

- open code with code in editor and panel visible
- hover over some code to get popup
- focus on terminal with keyboard
- expand panel vertically with keyboard 
- popup will ghost into panel without a border
- see before-and-after screenshots

![hover overflow 1](https://user-images.githubusercontent.com/25272315/28093541-b65d201c-6665-11e7-9eb0-663515788811.png)

![hover overflow 2](https://user-images.githubusercontent.com/25272315/28093563-d274dbaa-6665-11e7-9144-472f766b8bba.png)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/36479
