### ISSUE TITLE
VS Code 1.14 breaks heads-up notification coloring

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#30432]
- VSCode Version: 1.14.0
- OS Version: Windows 10

Color of label 'Info' and of button reverts to default even though is provided in the theme.

![capture](https://user-images.githubusercontent.com/26769888/28093195-e30b8844-66b3-11e7-98a7-3b3d54e7c58c.PNG)

**Comment by bpasero** [comment]
Somehow missed to release note this, it came in as PR. See https://github.com/Microsoft/vscode/issues/28280
