### ISSUE TITLE
Show/Hide `Running Tasks` StatusBar 

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#30435]
- VSCode Version: 1.15 Insiders
- OS Version: Windows

The new `Running Tasks` item in the StatusBar is show even for _Empty Folders/Workspaces_ or Folders/Workspaces that don't have any `.vscode/tasks.json` defined.

It's a great addition to have this new StatusBar item available 👍  , but I think that it should be hidden if the opened Folder/Workspace don't have any task available, or maybe a `User Setting` to decide if/when it is shown/hidden.

Thanks

**Comment by dbaeumer** [comment]
Agree. I am currently polishing it.
