### ISSUE TITLE
gulpfile.babel.js support

### ISSUE THREAD

**Issue by legendecas** [Microsoft/vscode#3043]
gulp configuration file can also be named `gulpfile.babel.js` then gulp will automatically require babel registry before running gulp tasks.
But it seems VSCode cannot recognize `gulpfile.babel.js`.

**Comment by Klemensas** [comment]
I would like to have this feature. @dbaeumer can I do a pull request to speed up the process?

**Comment by dbaeumer** [comment]
Yes, PRs always help to speed things up. The file to look at is: vscode\src\vs\workbench\parts\tasks\node\processRunnerDetector.ts

**Comment by dbaeumer** [comment]
Task 2.0.0 auto detection has support for gulpfile.babel.js.
