### ISSUE TITLE
package.json with a png icon shows a seemingly bogus warning

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#30434]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.0

---

Steps to Reproduce:

1. Open a package.json with a png for the icon.

Bug: It gives the warning "Relative image URLs require a repository with HTTPS protocol in the package.json". The message seems bogus.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@joaomoreno Wasn't there a requirement for the icon to be available in the repository for when the extension is not installed yet? Has that changed?

**Comment by joaomoreno** [comment]
@chrmarti I don't understand the question. It seems the user gets a squiggly error.

**Comment by chrmarti** [comment]
@joaomoreno I'm generating the squiggly error assuming there needs to be a repository for the icon lookup when the extension is not installed yet. Maybe that's only the case for the marketplace?

**Comment by joaomoreno** [comment]
I'm confused.

If the user is editing a `package.json` from a VS Code extension, maybe the problem is that the message is not clear enough. He needs a repository field.

If the user is editing a `package.json` from any other project type, there shouldn't be a message there any way.

**Comment by sean-mcmanus** [comment]
Yeah, the message was not clear enough. We will try to add the repository field to our package.json. Thanks.

**Comment by chrmarti** [comment]
Changing it for the icon to: "An icon requires a repository with HTTPS protocol to be specified in this package.json."

For relative URLs in README/CHANGLOG: "Relative image URLs require a repository with HTTPS protocol to be specified in the package.json."

**Comment by sean-mcmanus** [comment]
@chrmarti We added a repository to your package.json in our pending release, but our icon isn't in the repository (it's at the root of the extension installation). Is that okay or are we supposed to provide a URL to an online icon?

`  "icon": "LanguageCCPP_color_128x.png",
  "repository": {
    "type": "git",
    "url": "https://github.com/Microsoft/vscode-cpptools.git"
  },`

**Comment by chrmarti** [comment]
@sean-mcmanus My understanding is that the icon should also exist in the repository at the same relative URL it exists in the extension's VSIX. @joaomoreno might clarify.

**Comment by sean-mcmanus** [comment]
@chrmarti @joaomoreno I've added the icon to the root of our repository: https://github.com/Microsoft/vscode-cpptools/blob/master/LanguageCCPP_color_128x.png
