### ISSUE TITLE
Any Git operations requiring credentials no longer work

### ISSUE THREAD

**Issue by homer666** [Microsoft/vscode#30437]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.1
godot-tools|gee|0.2.7
cpptools|ms-|0.12.0

(1 theme extensions excluded)

Reproduces without extensions: Yes

---

VSCode would display a prompt asking for my credentials whenever interacting with a private repo of mine, but with this new update that prompt no longer appears, making the repo unusable. It's worth noting that these operations still work fine via the terminal (both external and vscode's built-in).

---

To reproduce this, try to execute a Git operation that would typically ask for credentials. For example:
 * Push some changes to a repo
 * Interact with a private repo
   * Cloning
   * Pushing/pulling
   * etc. 
 
Doing the latter (pushing to a private repo) gives me these error messages under OUTPUT:
```
fatal: cannot exec '/usr/share/code/resources/app/extensions/git/out/askpass.sh': Permission denied
fatal: could not read Password for 'https://[nope]@bitbucket.org': No such device or address
```

Probably worth noting that attempting to clone my private repo gives me this error prompt at the top:
```
Git: Cloning into '/home/user/Repositories/test-repo'...
```
And no logs under OUTPUT.

**Comment by joaomoreno** [comment]
What does `ls -la /usr/share/code/resources/app/extensions/git/out/askpass.sh` return?

**Comment by mertcelen** [comment]
@joaomoreno 
I had the same issue, the permission list is below
`-rw-r--r-- 1 root root`

Giving run permission is solve this issue as expected.

**Comment by leixu2txtek** [comment]
@joaomoreno  I had the same issue.

```sh
-rw-r--r-- 1 root root
```

**Comment by joaomoreno** [comment]
Pushed to `release/1.14` branch

**Comment by joaomoreno** [comment]
Verification on Linux only:

1. Disable any git credential helper
2. Clone a repository which needs credentials

Code should ask for your credentials while cloning/fetching/pulling, etc.

**Comment by scapicIntern** [comment]
You can also go to location and type `chmod +x askpass.sh` This will also fix it.
