### ISSUE TITLE
Resizing project explorer after clicking menu key while hovering context menu

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vscode#3044]
Pressing the menu key ("RMB" on keyboard) while the mouse is hovering over a context menu opened by right-clicking (or using the menu key) in the document will start resizing the project explorer.

Steps:
1.  Open a document (empty or not, does not matter)
2.  Right-click in the document to bring up the context menu
3.  Hover over one of the entries in the context menu with the mouse
4.  Press the menu key ([Wikipedia picture](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Kontextmen%C3%BC.jpg/220px-Kontextmen%C3%BC.jpg))

I'm not sure what I expect to happen, but it's not this.

And webm: http://morten242.com/sharex/2016/02/2016-02-16_08-59-52.webm

Version 10.8
Reproducible even with --disable-extensions
No errors created in console
Running Windows 10

**Comment by bpasero** [comment]
For some weird reason Chrome/Electron decides to fire the mouse-down event on our sash when the context menu opens from this context menu button.

**Comment by bpasero** [comment]
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
