### ISSUE TITLE
Emmet (HTML) not honoring grouping syntax

### ISSUE THREAD

**Issue by dskad** [Microsoft/vscode#30446]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.16237
- Extensions: (tested with all extensions disabled)

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.1.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
vuejs-extension-pack|mub|0.1.7
vetur|oct|0.9.0
vuehelper|oys|0.1.0
Align|ste|0.2.0
JavaScriptSnippets|xab|1.4.1

---

**Steps to Reproduce:**

`div#app>(div>p#test*2)` correctly expands to:
````html
<div id="app">
  <div>
    <p id="test"></p>
    <p id="test"></p>
  </div>
</div>
````

while `div#app>(div>p#test*2)*2` incorrectly expands to:
````html
<div id="app">
</div>
````
it should expand to:
````html
<div id="app">
  <div>
    <p id="test"></p>
    <p id="test"></p>
  </div>
  <div>
    <p id="test"></p>
    <p id="test"></p>
  </div>
</div>
````

The same abbreviation expands correctly in Atom with the official Emmet plugin. (Tested just in case I was typing emmet jibberish!)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
We are tracking this in #27784 and https://github.com/emmetio/atom-plugin/issues/23

Thanks for reporting!
