### ISSUE TITLE
PowerShell Integrated Console unusable with no internet

### ISSUE THREAD

**Issue by marckassay** [Microsoft/vscode#30447]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
tslint|eg2|0.16.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6

---

Steps to Reproduce:

1.  Disconnect computer from internet
2.  Launch VSCode with a project that uses PowerShell Integrated Console.

Expected:

- To be able to use the Integrated Console without internet.

The picture below shows the console that is unusable.
![powershell_integrated](https://user-images.githubusercontent.com/459665/28096801-9d5e1ff8-6679-11e7-8b99-72e3d2a9a820.PNG)

**Comment by Tyriar** [comment]
Please report against the powershell extension https://github.com/PowerShell/vscode-powershell

**Comment by marckassay** [comment]
Right!  Sorry for the time spent.  I noticed today I inadvertently posted this issue here.  Thanks and no problem, here is the [issue ](https://github.com/PowerShell/vscode-powershell/issues/954)in vscode-powershell.
