### ISSUE TITLE
Extensions are not displayed after switching to Explorer

### ISSUE THREAD

**Issue by CarlosAzocar** [Microsoft/vscode#30441]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10 x64

Reproduces without extensions: Yes/No
![issue](https://user-images.githubusercontent.com/18235355/28095806-8229bb22-6672-11e7-90d8-5d0fc5c7fa9d.gif)

**Comment by sandy081** [comment]
Sorry for that. My changes to support view management has broken it. Fixed.
