### ISSUE TITLE
Repeated notification of update already installed

### ISSUE THREAD

**Issue by pjgoodall** [Microsoft/vscode#30445]
- VSCode Version:
- OS Version: Ubuntu Xenial

Steps to Reproduce:

1. Start, or reinstall and start vscode from commandline `code .`
2. Wait for update notification, or check for updates.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What version do you have installed? What version does it tell you to download?

**Comment by Tyriar** [comment]
There was a 1-2 hour delay to publishing the deb this release, that was likely the cause.

**Comment by pjgoodall** [comment]
When I asked for release notes on the update notification at the top of vscode I get:
`Unable to open 'Release Notes: 1.14.1': Cannot read property 'replace' of null`

1.14.1 is the release which is repeatedly notified, and I have downloaded several times. I have also tried installing it several times - no change.
I have uninstalled and `sudo apt purge` on VS-Code, and reinstalled - getting the same result.

Ubuntu Xenial - which I update daily.

**Comment by pjgoodall** [comment]
Just did `sudo aptitude purge code`, which duly completed - reporting it was removing 1 package.
I typed `code` at the command-line, and vs-code ran!
Reporting from the 'About' dialog 

```
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
There is an executable linked in my `$HOME/bin directory to $HOME/local/VSCode-linux-x64/`
The binary says it was modified `Wed, Nov  9 2016 23:18:58` . 

I have deleted the directory and the link. Rebooting before reinstall. The 'Ubuntu Software' app seems to stall when it starts to load the vs-code package.

**Comment by pjgoodall** [comment]
OK - reinstalled vs-code after removal of link and directory and reboot.
Now reporting from 'About' dialog:
```

Version 1.14.1
Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
Date 2017-07-13T19:12:01.887Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
feeling much more modern `:-)`

In conclusion - installed twice, once unpacked manually into a directory on path ahead of package install location. 

--Cheers...

**Comment by Tyriar** [comment]
You might have installed the older version using a non-official apt repo which could cause some issue?

**Comment by pjgoodall** [comment]
That seems likely. <tears>
I keep hoping that something like snap or NixOS will make configuration
precise.
Apologies for consuming people's time...

**Comment by Tyriar** [comment]
@pjgoodall we have a snap set up https://github.com/Microsoft/vscode/issues/5458, we haven't completed the hand over and integrated it into our build yet though.
