### ISSUE TITLE
Microsoft Visual Code - Suggestion 

### ISSUE THREAD

**Issue by JohnMagdy** [Microsoft/vscode#30442]
Hello all, so iam intersted on suggesting every idea i might get for this Amazing Editor.
it 'd be much better if you sir added a feature which we might Backup our opened files with an schedule (like every 5 seconds but it could be customized) and the backup file will be saved as ${File_Name}.${File_Type}@${Time}_${Date}.bak for example `index.html@3:01 AM_12/7/2017.bak` on an temporary directory which will be created on Application installion step   on Microsoft Visual Code's Installion Directory (it could be customized) and on every file save will be created anbackup file (optional - disabled by default and it could be enabled from the ./vscode/settings.json or what ever you want)

**Comment by Tyriar** [comment]
Files are actually backed up to support our hot exit feature, they are however deleted when the file is closed by the user. I suggest looking at extensions to fill this need or write one yourself to backup active files to disk.
