### ISSUE TITLE
HTML saving as RHTML

### ISSUE THREAD

**Issue by J404** [Microsoft/vscode#30444]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Usually, when I save HTML files in Visual Studio Code they save as the type HTML. So, when I open the files in my file explorer, I have an option to "Open with Google Chrome" and I can see my HTML page from there in the browser (or any other browser I choose). However, when I updated to the most recent version of Visual Studio Code, whenever I save my HTML files they save in the type of RHTML. When they are in this type, I can not preview/render them with any browser. I need help to get my files to save as HTML files, and not RHTML files so I can actually use Visual Studio Code.

Steps to Reproduce:

1. Create any HTML file with any content.
2. Save the file (in my experience it will save as RHTML).

**Comment by J404** [comment]
Thank you for the fix! I saw the file, but do I have to implement this myself or will I just have to wait until the next update?
Thank you!

**Comment by bpasero** [comment]
This should be available in tomorrows insider release and for the June recovery release soon.

**Comment by J404** [comment]
Okay, thank you!!
