### ISSUE TITLE
Got a pink background color status bar

### ISSUE THREAD

**Issue by iahu** [Microsoft/vscode#30457]
<img width="1024" alt="dingtalk20170712113735" src="https://user-images.githubusercontent.com/1704588/28100791-dca76f16-66f6-11e7-9bd2-eb7e07f3a656.png">
Pink is not my color. I want change a different color. The question is how to change it?
Thanks.

**Comment by jens1o** [comment]
Open your user settings, and insert this:
```json
{
    "workbench.colorCustomizations": {
        "statusBar.noFolderBackground": "#0078CD"
    }
}
```

You can change the color code at any given time.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
