### ISSUE TITLE
vscode stuck

### ISSUE THREAD

**Issue by modarend** [Microsoft/vscode#30451]
- VSCode Version:    1.14.0 (1.14.0)
- OS Version:  macos 10.12.5 (16F73)

Steps to Reproduce:

1.Jammed tip: window can no longer response to open or close the window, or keep waiting.
2.Choose to wait.
3.Restart or failure has no effect

Reproduces without extensions: Yes/No

**Comment by lokyoung** [comment]
Having this issue too. VSCode just stuck after updated. Can't do anything now.

**Comment by rafaelsouza** [comment]
I'm having the same issue, tried to remove extensions but same result.

**Comment by meanphil** [comment]
Same here, additionally 'Code Helper' seems to be spinning in the background on 150%+ CPU usage

**Comment by fbandrey** [comment]
+1

**Comment by andrewzielinski** [comment]
+1

**Comment by Magnusvb** [comment]
+1

**Comment by bpasero** [comment]
This looks like https://github.com/Microsoft/vscode/issues/30407

**Comment by chrmarti** [comment]
- Does it freeze immediately after startup?
- Do you have the Rails snippets installed? (`code --list-extensions` showing `atefth.ruby-on-rails-snippets`)
  - If so try uninstalling that. (`code --uninstall-extension atefth.ruby-on-rails-snippets`)
  - If not, try launching with all extensions disabled (`code --disable-extensions`) posting the result here.

Let us know if any of that helps. If not please post the list of installed extensions here (`code --list-extensions`).

**Comment by chrmarti** [comment]
@bpasero Was faster :D

**Comment by Magnusvb** [comment]
Solved. Thanks!
The Terminal way did not worked for me, so I manually removed "atefth.ruby-on-rails-snippets-0.0.1" from .vscode/extensions

**Comment by chukwu** [comment]
Yeah...ruby on rails snippet extension was the bad guy.
Thanks
