### ISSUE TITLE
How can I extend tree view from the main explorer?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#30455]
Suppose I have `.cs` file in my project and it was shown in explorer properly. But then I want to add symbol tree view to that `.cs` file

Can I register my tree on the main explorer?
Where could I hook the main explorer instead of create custom tree?

**Comment by sandy081** [comment]
@Thaina Please refer to the documentation here https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews
