### ISSUE TITLE
Insider builds not being published to the Debian repo since July 5th

### ISSUE THREAD

**Issue by AaronFriel** [Microsoft/vscode#30452]
- VSCode Version:  1.15.0-insider / 1.15.0-1499795530 (ec5b0498651bde043ec357a8f36d475cc0880cfc)
- OS Version: Ubuntu 17.04 / `uname --srop`: Linux 4.10.0-26-generic GNU/Linux`

Steps to Reproduce:

1. `apt-get update`
2. See that no updates are available
3. Do this for several more days and wonder why code-insiders doesn't show up
4. Go to the package repo in a browser and observe that this is because there are [no updates published](https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/) 😢 
5. Think maybe there is a blocking issue, but can find nothing obvious with that commit
6. Download code-insiders manually and see that you get a newer version (1.15.0-1499795530), so be sad that the repo is just out of date.

Too much post-4th of July partying at the VS Code team? 😉

Reproduces without extensions: Yes

**Comment by AaronFriel** [comment]
neat bot

**Comment by fdvmarkus** [comment]
Looks like the update released on 11th of July was [not published in the yum-repo for the normal (not insider) release](https://packages.microsoft.com/yumrepos/vscode/), either.

**Comment by Tyriar** [comment]
@AaronFriel the insiders build is frozen when we are stabilizing the stable channel. It took particularly long this iteration but this was expected. Everything's back to normal now :+1:  https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/

@fdvmarkus I published v1.14.0 to the repo earlier this morning, for the rpm we need to get it manually signed by another team which takes a little time unfortunately.

**Comment by AaronFriel** [comment]
@Tyriar: is there a reason the insiders build & the repositories go out of sync when this happens?

**Comment by Tyriar** [comment]
@AaronFriel there is. The first 2 insiders builds got automatically published on the 4th and 5th. I believe the build was not properly frozen in our internal release tool and were instead "unpublished" manually which does not touch the apt repo. macOS and Windows support downgrading just fine but unpublishing a deb package from apt would probably do more harm than good.
