### ISSUE TITLE
New emmet(HTML) does not work with pure number value

### ISSUE THREAD

**Issue by easykid** [Microsoft/vscode#30454]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1.open a HTML file
2.type ```div[custom-attr=123]``` then press ```Tab```
It does not work.

Text abbreviation like ```div{123}``` does not work either.

Reproduces without extensions: Yes

**Comment by bestvow** [comment]
![snipaste_20170712_110713](https://user-images.githubusercontent.com/24888709/28100024-4dab6ffa-66f2-11e7-8a85-9890f972a880.png)

**Comment by ramya-rao-a** [comment]
@easykid 

- Can you share the version of the Insiders build you are using?
- Do you have `emmet.useNewEmmet` set to `true` or `false` ?

Using the `Emmet: Expand Abbreviation` command in the examples you have shown work as expected.

The suggestion list doesn't show the emmet expansion when `emmet.useNewEmmet` is set to `true` in you cases.

Can you confirm?

**Comment by easykid** [comment]
@ramya-rao-a

I have ```emmet.useNewEmmet``` set to ```true```.

I'm not sure about the version of the Insiders, I just downloaded the latest stable version this morning.

Using ```Emmet: Expand Abbreviation``` command work as expected, but not with ```tab```.

**Comment by easykid** [comment]
When the value is mixed with non-numeric characters, like ```div{1a}``` or ```div[attr=a1]```, ```tab``` works fine.

**Comment by ramya-rao-a** [comment]
I am assuming when you say `tab` you mean the tabbing to choose the first item in the suggestion list.

This is happening because typing pure numbers doesn't trigger the completion provider

@jrieken I believe the reason is that `ab12` is treated as a word but `12` isn't.
Can you confirm?

**Comment by jrieken** [comment]
> @jrieken I believe the reason is that ab12 is treated as a word but 12 isn't.
Can you confirm?

Ultimately it depends on the language specific word definition but in general "yes", numbers aren't considered words, IntelliSense needs to be invoked manually, e.g by pressing Ctrl+Space

**Comment by ramya-rao-a** [comment]
Thanks @jrieken 

@easykid @bestvow I am closing this as this is how the completion triggering works. 

Workaround is to manually trigger the completion (`Ctrl+Space`)
