### ISSUE TITLE
Pick latest stable version automatically when generating extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#30466]
It should now generate 1.14

**Comment by bpasero** [comment]
Ideally we would just automate this so that the generator always points to latest (e.g. by looking at the latest tag at https://github.com/Microsoft/vscode/releases

**Comment by egamma** [comment]
@joaomoreno mentioned to me a way to fetch this information that is not dependent on the existance of a tag, but uses the information from our builds website.

**Comment by bpasero** [comment]
Yeah, see https://github.com/Microsoft/vscode-update-server/issues/12#issuecomment-314710581

**Comment by aeschli** [comment]
@joaomoreno What's the full URL of the /api/releases API ?

**Comment by aeschli** [comment]
I updated the generator plugin (manually) with https://github.com/Microsoft/vscode-generator-code/commit/e9d184bcaec806786ad92802243627ed4f82a657

**Comment by bpasero** [comment]
@aeschli see https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/install#L69 where I adopted this.
