### ISSUE TITLE
Drag and drop files not working

### ISSUE THREAD

**Issue by spences10** [Microsoft/vscode#30462]
- VSCode Version: Code - Insiders 1.15.0-insider (7bb3b89031cbce46536ba870868d889d639e12f1, 2017-07-11T17:55:51.921Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
markdown-toc|Ala|1.5.5
Bookmarks|ale|0.15.2
vscode-color|ans|0.4.1
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
react-native-react-redux|EQu|1.0.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
react-jest-vscode-snippets|jal|0.0.3
search-node-modules|jas|1.1.1
vscode-styled-components|jpo|0.0.7
code-stats-vscode|juh|1.0.7
tag-rename|kri|0.2.1
graphql-for-vscode|kum|1.4.2
node-module-intellisense|lei|1.3.0
VBScript|lug|0.0.1
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
editorconfiggenerator|nep|0.2.1
prettier-now|rem|1.3.1
view-in-default-application|see|3.3.0
code-settings-sync|Sha|2.8.2
vba|spe|1.0.17
language-stylus|sys|1.7.3
vscode-react-redux-snippets|tha|0.3.3
bootstrap4-vscode|the|2.3.3
write-good-linter|tra|0.0.3
lorem-ipsum|Tyr|1.0.0
vscode-wakatime|Wak|1.1.12
JavaScriptSnippets|xab|1.4.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Install latest VSCode insiders
2. Try to drag and drop a file in the explorer

Reproduces without extensions: Yes/~~No~~

**Comment by bpasero** [comment]
I can reproduce (in insiders only). @sandy081 could this be a regression from your DND work of sections?

**Comment by sandy081** [comment]
@bpasero Yes this is caused from that. Looking into it.

**Comment by sandy081** [comment]
It seems tree view is listening on `window` for `drop` and split view is stopping the event. @joaomoreno provided the fix in tree view to listen on tree element for `drop`.
