### ISSUE TITLE
Automatic line feed failure

### ISSUE THREAD

**Issue by hasubasora** [Microsoft/vscode#30465]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ivue|dai|0.1.0
Vue2|duc|0.1.3
vscode-html-css|ecm|0.1.7
vscode-great-icons|emm|2.1.9
vue-snippets|hol|0.1.2
weex|jay|0.4.0
format-indent|Kas|1.3.0
format-php|Kas|1.1.2
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vetur|oct|0.9.0
vuehelper|oys|0.1.0
vscode-html-scss|P-d|0.0.42
php-ci|sma|0.2.1
php-formatter|Sop|0.2.4
html-snippets|wge|0.1.5

(8 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
More details?
