### ISSUE TITLE
Bug: Markdown Preview does not work; shows a blank page: VSCode 1.14.0

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#30464]
- VSCode Version: 1.14.0
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open an empty file, type in some words, and save it as "test.md"
2. Commands "Markdown: Open Preview" and "Markdown: Open Preview to the Side" both do not work: a blank preview page is open, no words displayed.

Reproduces without extensions: Yes, the bug still exists.
![image](https://user-images.githubusercontent.com/18319900/28105172-36360ede-6693-11e7-96d6-f861e6d844c9.png)
![image](https://user-images.githubusercontent.com/18319900/28105216-671cdf8c-6693-11e7-9be4-a39a9c20e455.png)

**Comment by bgraeb** [comment]
Same on Windows 10.0.15063

**Comment by Darep** [comment]
Similar here on OSX 10.10.5 but instead of showing up empty, I get a "command not found" on VSCode 1.14.0:

![image](https://user-images.githubusercontent.com/218910/28105943-6c30ee76-66ea-11e7-8100-f5121e59e17a.png)

**Comment by flyingtassel** [comment]
Same on Windows 7 SP1

**Comment by okonon** [comment]
same on OSX 10.12.4 running VSCode 1.14.0 (1.14.0)

**Comment by davegregg** [comment]
Same on Ubuntu 17.10 alpha running VSCode 1.15.0-insider

**Comment by sindbach** [comment]
Thanks for the quick commit/fix for this issue. 
Just wondering, when would this fix be released ? 
Would the alternative to downgrade to version 1.13 for now until next release (1.15 -July edition) ?

**Comment by mjbvz** [comment]
The fix first will land in the next [insiders build](https://code.visualstudio.com/insiders). This should come out sometime within the next 12 hours

We also are taking this into a VScode 1.14.1 patch update. We are aiming to get that out sometime this week

**Comment by LaneyQUT** [comment]
Is this Bug fixed yet? I met the same problem here, Win 10, Rstudio 1.044. Thanks
