### ISSUE TITLE
Javascript definitions break with node_modules

### ISSUE THREAD

**Issue by bugs181** [Microsoft/vscode#30463]
- VSCode Version: 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40)
- OS Version: OSX 10.10.1

Steps to Reproduce:

1. Open first file, hold command, hover above item. Item turns blue and is underlined with a preview.
2. Open second file, hold command, hovering above item does nothing.
3. Additionally, right clicking item and selecting context menu 'Go to definition' will provide the error 'No definitions found for ...'

Reproduces without extensions: Yes

Additional info: Using ES6 in Nodejs projects. Files include module.exports, let/const keywords and multi-line comments.

Edit:
- The second file can be completely empty and the first file still provides no definitions.
- Bug is inconsistence and only happens for particular files. Perhaps a linting problem?
- ~~I think I've narrowed the bug down to a path problem. It happens when files are nested 3 layers deep. Example: root/1/2/3/file.js (Needs more verification)~~
- Path problem assumption was wrong and it appears to be a `node_modules` issue.

**Comment by mjbvz** [comment]
Can you please share some code or a small project that demonstrates this issue.

Also try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project to ensure all JS files are part of the same project

**Comment by bugs181** [comment]
I was originally wrong about the subdirectories. I've found the culprit but don't know why yet. It appears to happen when I have `cheerio` as a `node_module` dependency.

Attached is an example project. Opening `file1.js` and `file2.js` work as expected until you open `broken/broken.js`. It may have something to do with the `package.json`. I've even tried removing `jshint` and `mocha` in that file but it still breaks.

[example.zip](https://github.com/Microsoft/vscode/files/1142617/example.zip)

**Comment by mjbvz** [comment]
Thanks. Looking at the trace, I see a few errors reported on the TS Server. I've opened https://github.com/Microsoft/TypeScript/issues/17131 to track this

As a workaround, try downgrading your TS version to 2.3.4.  [Here are the instructions on that](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

Closing as upstream
