### ISSUE TITLE
Test failing in Code 1.14 checking isActive on extension after openTextDocument

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#30461]
I had this test in my extension which began failing with the 1.14 release:

```ts
const ext = vs.extensions.getExtension("DanTup.dart-code");

it("is not activated initially", () => {
  assert.equal(ext.isActive, false);
});
it("is activated successfully upon opening a Dart file", done => {
  vs.workspace.openTextDocument(sampleFileUri)
    .then(() => assert.equal(ext.isActive, true)) // This fails with false !== true
    .then(() => assert.notEqual(extension.sdks.dart, null))
    .then(() => assert.notEqual(extension.analyzer, null))
    .then(() => done(), e => done(new Error(e)));
  });
```

The extension works fine so I don't think there are no real consequences of this but before I change the test I wanted to make sure this was an expected change (I tried looking through source of getExtension/openTextDocument but couldn't see any obvious change). My guess is that some either timing changed in openTextDocument such that it returns earlier (before related extensions are activated) or the result from `getExtension` isn't "live" anymore and won't automatically return an updated value?

**Comment by jrieken** [comment]
@DanTup What is the activation event you are using?

**Comment by DanTup** [comment]
@jrieken `.dart` files or workspace containing `pubspec.yaml`.

```js
"activationEvents": [
  "onLanguage:dart",
  "workspaceContains:**/pubspec.yaml"
],
// ...

"contributes": {
  "languages": [
  {
    "id": "dart",
    "extensions": [ ".dart" ],
    "aliases": [ "Dart" ],
```

Looking closer in the tests, it's an untitled file with a temp path:

```ts
const sampleFilePath = (isWin ? "X:\\" : "/tmp/") + "sample.dart";
const sampleFileUri = vs.Uri.parse(`untitled:${sampleFilePath}`);
```

So maybe something changed around there. I'll try and dig into it further tomorrow; was a bit short on time last night.

**Comment by DanTup** [comment]
It's not related to the `untitled` file, since it still fails if I use this:

```ts
const sampleFileUri = vs.Uri.parse(`file:///C:/Users/danny/Desktop/DartSample/lib/thing.dart`);
```

Wrapping a `setTimeout` around is causes it to pass if the timeout is large enough (50ms), but fail if it's small (< 10ms):

```ts
it("is activated successfully upon opening a Dart file", done => {
		vs.workspace.openTextDocument(sampleFileUri);
		setTimeout(function () {
			try {
				assert.equal(ext.isActive, true);
				assert.notEqual(extension.sdks.dart, null);
				assert.notEqual(extension.analyzer, null);
				done()
			}
			catch (e) {
				done(new Error(e));
			}
		}, 50);
	});
```

It's possible my test was based on a flawed assumption (it assumed openTextDocument would return after the extension was activated), I'm not sure? (I can see advantages to both ways).

**Comment by jrieken** [comment]
> (it assumed openTextDocument would return after the extension was activated)

Nah, we don't wait for extensions to be ready. We don't want to delay typing, see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/mode/common/workbenchModeService.ts#L129

**Comment by DanTup** [comment]
@jrieken Ok thanks! What's the preferred way to wait for extension activation in a test? (I don't understand the linked code if that's related). For most tests I guess I can explicitly call `activate`, but the purpose of this test was to ensure the activation happened automatically for the criteria I expected (though I appreciate this test is probably a bit redundant, since it seems like something you're already testing as part of Code).

**Comment by jrieken** [comment]
>  since it seems like something you're already testing as part of Code).

Yes
