### ISSUE TITLE
1.14.0 version don't debug start Electron 

### ISSUE THREAD

**Issue by neotiango** [Microsoft/vscode#30469]
- VSCode Version: 1.14.0
- OS Version: MAC 10.12

`    {  

      "name": "Debug",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "program": "${workspaceRoot}/win.js"  

    }    `

Result error: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:29675).

But, the configuration settings was work in 1.13.1

**Comment by DuskDweller** [comment]
For the time being try adding this to your launch.json 

"protocol": "legacy"

**Comment by weinand** [comment]
from the VS Code 1.14 [release notes](https://code.visualstudio.com/updates/v1_14#_node-debugging):
> In this release, Node.js debugging will assume the "inspector" protocol whenever the runtimeExecutable attribute of a launch configuration is set. If you see your debug configurations failing, this change could be the reason. To fix this, you can either upgrade Node.js to version 8.x or you can explicitly force the use of the "legacy" protocol by adding "protocol": "legacy" to your launch configuration.
