### ISSUE TITLE
Javascript formatting has changed considerably

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#30475]
1. Open `vscode/build/gulpfile.vscode.js` in Code
2. Run Format (or simply save the file, in case you have auto format on save)

The file changes considerably, and forbids me to use a more compact formatting, like it used to. Some examples:

```es6
const builtInExtensions = [
	{ name: 'ms-vscode.node-debug', version: '1.15.2' },
	{ name: 'ms-vscode.node-debug2', version: '1.14.4' }
];
```

becomes

```es6
const builtInExtensions = [
  {
    name: 'ms-vscode.node-debug',
    version: '1.15.2'
  },
  {
    name: 'ms-vscode.node-debug2',
    version: '1.14.4'
  }
];
```

or

```es6
	const localExtensionDependencies = gulp.src('extensions/node_modules/**', { base: '.' });
```

becomes

```es6
    const localExtensionDependencies = gulp.src('extensions/node_modules/**', {
      base: '.'
    });
```

I am forced to disable auto format on save for javascript files. 😢

**Comment by mjbvz** [comment]
I'm unable to reproduce this with TS 2.4.1. Could it be coming from one of your installed extensions?

**Comment by joaomoreno** [comment]
Could be, especially because it doesn't reproduce with TypeScript, let me see.

**Comment by joaomoreno** [comment]
Duh, I did have some `esformatter` extension installed, as part of a bug I had to investigate yesterday.

![doh](https://media.giphy.com/media/xT5LMpBWU96Yivdfeo/giphy.gif)

Sorry about that!
