### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by sirzxj** [Microsoft/vscode#30476]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 15.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
velocity|sod|0.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Missing details.
