### ISSUE TITLE
 Cannot read property 'detail' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3047]
Issue Id: <b>9e437b6f-a825-7be6-553b-fca923120dcd</b><br /><br />*Versions* <br />- 0.10.8<br />*Stack* <br />TypeError: Cannot read property 'detail' of null<br />[/vs/platform/telemetry/common/abstractTelemetryService.ts#L73:7 (AbstractTelemetryService.onErrorEvent)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/platform/telemetry/common/abstractTelemetryService.ts#L73:7 (AbstractTelemetryService.onErrorEvent))<br />[/vs/base/common/errors.ts#L55:3 (ErrorHandler.emit)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/errors.ts#L55:3 (ErrorHandler.emit))<br />    at Array.forEach (native)<br />[/vs/base/common/errors.ts#L54:17 (ErrorHandler.emit)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/errors.ts#L54:17 (ErrorHandler.emit))<br />[/vs/base/common/errors.ts#L73:7 (ErrorHandler.onUnexpectedError)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/errors.ts#L73:7 (ErrorHandler.onUnexpectedError))<br />[/vs/base/common/errors.ts#L87:15 (onUnexpectedError)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/errors.ts#L87:15 (onUnexpectedError))<br />[/vs/workbench/api/node/extHost.api.impl.ts#L556:9 (MainProcessVSCodeAPIHelper.onUnexpectedPluginHostError)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/workbench/api/node/extHost.api.impl.ts#L556:9 (MainProcessVSCodeAPIHelper.onUnexpectedPluginHostError))<br />[/vs/platform/thread/common/abstractThreadService.ts#L141:16 (AbstractThreadService.handle)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/platform/thread/common/abstractThreadService.ts#L141:16 (AbstractThreadService.handle))<br />[/vs/platform/plugins/common/ipcRemoteCom.ts#L143:39 (create.invokeHandler)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/platform/plugins/common/ipcRemoteCom.ts#L143:39 (create.invokeHandler))<br />[/vs/platform/plugins/common/ipcRemoteCom.ts#L117:26 (create)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/platform/plugins/common/ipcRemoteCom.ts#L117:26 (create))<br />

**Comment by joaomoreno** [comment]
Related to #3231?

**Comment by SofianHn** [comment]
Yes, close as dup
