### ISSUE TITLE
Two windows at a time

### ISSUE THREAD

**Issue by psingl** [Microsoft/vscode#30479]
- VSCode Version: 1.14.0
- OS Version: Windows 8
When trying to open a specific folder in VSCode through command line using command <code>code .</code> Instead of opening a folder in a single new window only it opens two new windows and that folder in both the windows.

**Comment by bpasero** [comment]
@psingl can you share your settings? can you also maybe share a video of how this looks like?

**Comment by psingl** [comment]
Hey @bpasero 
Here is a screenshot of my settings
![image](https://user-images.githubusercontent.com/13885706/28150570-ed69f5d2-67b2-11e7-9f06-3a816335774e.png)

**Comment by bpasero** [comment]
@psingl so to be clear, you see this:
* VS Code is not running
* from a command line you type "code ."
* 2 windows open and each shows the folder

?

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
