### ISSUE TITLE
macOS: Select all does not work in file picker

### ISSUE THREAD

**Issue by tholu** [Microsoft/vscode#30477]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open a new File, Save As... (file picker appears)
2. Click at the end of the filename or use cursor (selection of "Untitled-1" gone)
3. Cmd+A or to select all characters does not work in the filepicker

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by tholu** [comment]
@bpasero I did a quick search before reporting, obviously not thorough enough. It would have been nice to reference the issue. I guess it's https://github.com/Microsoft/vscode/issues/19003.
