### ISSUE TITLE
Insiders: rename file, then right click

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#30472]
- VSCode Version: Code - Insiders 1.15.0-insider (74f5073c54f1139d2fb0eccb251cae5ed6e8215b, 2017-07-12T05:16:04.162Z)
- OS Version: Windows_NT x64 10.0.15063

![xx](https://user-images.githubusercontent.com/11925432/28106938-59998880-6718-11e7-81fd-cebec744418c.png)

**Comment by bpasero** [comment]
Looks like a regression from the views management changes.
