### ISSUE TITLE
Support custom views in Debug viewlet

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#30478]
With loaded scripts view feature, we need to support custom views in Debug viewlet. `debug` is the location to contribute views to Debug viewlet.

**Comment by weinand** [comment]
@sandy081 is there a way to determine the location (= slot within the others views) where the view will appear?

**Comment by sandy081** [comment]
@weinand No order of the view cannot be defined. By default all custom views go to the bottom.
