### ISSUE TITLE
User settings now has a lot of "javascript.format..." options that should be in the defaults instead

### ISSUE THREAD

**Issue by simonl65** [Microsoft/vscode#30483]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.18.1
code-gnu-global|aus|0.2.2
phpserver|bra|1.1.0
gitignore|cod|0.5.0
vscode-stylesheet-formatter|dba|0.2.0
git-extension-pack|don|0.1.2
githistory|don|0.2.1
python|don|0.6.7
Vue2|duc|0.1.3
gitlens|eam|4.3.1
vscode-html-css|ecm|0.1.7
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
auto-close-tag|for|0.4.3
vue-snippets|hol|0.1.2
crane|Hvy|0.3.6
php-symbols|lin|2.1.0
HTMLHint|mka|0.3.3
prettify-json|moh|0.0.3
vscode-devskim|MS-|0.1.4
windowsiot|ms-|0.0.20
autorest|ms-|0.12.4
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
js-atom-grammar|ms-|0.1.13
typescript-javascript-grammar|ms-|0.0.23
debugger-for-chrome|msj|3.1.6
php-docblocker|nei|1.2.0
vetur|oct|0.9.1
vue-beautify|pea|2.0.4
vscode-docker|Pet|0.0.16
view-in-browser|qin|0.0.5
java|red|0.7.0
sass-indented|rob|1.4.1
sc-themes|Syn|1.4.1
vscode-arduino|vsc|0.2.4
bootstrap-3-snippets|wcw|0.1.0
better-align|wwm|1.1.6
html-css-class-completion|Zig|1.7.0
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Ctrl + comma
2.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@simonl65 Did you mean to say 'on by default'? Which ones would you want to see on by default?

**Comment by simonl65** [comment]
Thanks for the response.

No, I'm meaning that since the update I now see a bunch of these lines in the **user** settings, but I didn't put them there. They are as follows:

-   "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
-  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
-  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
-  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
-  "javascript.format.placeOpenBraceOnNewLineForFunctions": true,
-  "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
-  "typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
-  "typescript.format.placeOpenBraceOnNewLineForFunctions": true,
-  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
-  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
-  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
-  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
-  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,

The defaults for these are all false, so I don't know why they appeared.

It's no "biigy" for me - just thought I'd report it :-)

**Comment by mjbvz** [comment]
I suspect this is caused by a misbehaving extension.

@simonl65 If you delete these settings are they recreated? If you then delete them again and disable all extensions (just start code with the `--disable-extensions` command line flag) are they still recreated?

**Comment by simonl65** [comment]
@mjbvz If I delete these settings they do **not** return. I've also just tried the update on another machine and these settings did **not** appear, so I guess it could've been a misbehaving extension as I don't have all the same extensions on that PC.
