### ISSUE TITLE
[Installer] Update failed when another user using VS code

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#30484]
- VSCode Version: 1.14
- OS Version: Windows Server 2012 R2

Steps to Reproduce:
Background: We have a remote server and allow two developer log in for development by their account.
1. Two people open VS code for coding
2. Update available. One user click update then update VS code.
3. Another user VS code still running, update failed, and can't fallback. Must uninstall then re-install VS code. -  FAIL

I think it's better to end all VS code process when install VS code.
![image](https://user-images.githubusercontent.com/26138585/28109760-c94ab8de-6722-11e7-8648-5a9bcc1592b9.png)

Reproduces without extensions: Yes/No

[**7/14/2017 Update**]
I found another issue about right click menu "Open with Code".
For two user login system, if one user install VS code and select add "Open with Code" option, his/her right menu display normally. But can't add the menu to another user's right menu. Another user need to re-install VS code. (Or provide a method how to add it to right menu?)

**Comment by joaomoreno** [comment]
This is as designed for now.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by vscpp** [comment]
@joaomoreno, not happy coding :(. I share a Server with team by different account login. As you know, VS code update 2 or 3 times every month. When he or I all open the vs code, then update vs code. VS code will update failed and can't start again. I must re install the vs code.

At least, VS code installer should support fallback to previous state if install failed, and make it works.

**Comment by joaomoreno** [comment]
You really don't have to share: why don't you simply use the ZIP version?
