### ISSUE TITLE
Path to OneDrive does not exist

### ISSUE THREAD

**Issue by hokm** [Microsoft/vscode#30482]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
vscode-icons|rob|7.10.1
twig|wha|1.0.2

---

Steps to Reproduce:

1. Install Windows Insider Build 16232
2. Turn on "Files on demand" in OneDrive
3. Try open folder on OneDrive in Visual Studio Code - "Path does not exist"
4. Set OneDrive folder to "Always keep on this device", wait for download and then try to open in Visual Studio Code - "Path does not exist"

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Looks like #27285.

**Comment by bpasero** [comment]
#27285

**Comment by orixa** [comment]
I have same issue, I can not open anything on stored on onedrive from Code.. I have to copy it to a local folder.. I think I will try Sublime, I am giving up..
