### ISSUE TITLE
Need to reopen all windows to update scope of inner terminal

### ISSUE THREAD

**Issue by parzh** [Microsoft/vscode#30481]
#### Versions:
- VSCode: 1.14.0
- OS: Windows 10 [10.0.14393]

#### Steps to Reproduce:

1. Open one or more VSCode windows (instances, projects);
2. Using any terminal, install any library globally (i.e. Java, or `npm install -g <package>`);
3. Without exiting the opened VSCode window, launch one more;

#### Expected:
the installed library to be visible in the inner terminal of newly opened VSCode window.

#### Reproduces without extensions:
Yes

**Comment by Tyriar** [comment]
@parzh does the package happen to edit the `PATH` environment variable?

**Comment by parzh** [comment]
@Tyriar: Yes, it does

**Comment by Tyriar** [comment]
In that case this is by design. All VS Code windows inherit the main processes' environment, and the terminal inherits the window's environment.

You will have to either relaunch or modify `PATH` yourself via the terminal.
