### ISSUE TITLE
NPM scripts not running with new task runner 2.0

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#30488]
- VSCode Version: 1.14.0
- OS Version: Windows 10 CU
- Reproduces without extensions: Yes

I saw #28595 but this seems to be a slightly different problem. Just upgraded to v1.14 and trying the new task runner. But it's not working for npm tasks: it just outputs the npm help text.

tasks.json:
``` json5
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "compile",
            "problemMatcher": []
        }
    ]
}
```

Output:
```
> Executing task: npm run compile <


Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
[snip]
```

Using npm v5.0.3

In settings.json: `"terminal.integrated.shell.windows": "bash.exe"` (Git bash)

Additionally, the task runner only finds 1 of the 7 scripts in my package.json file.

Will provide more info if needed.

**Comment by englund** [comment]
I have this problem as well. Running git bash and latest vscode 1.14.0 with npm 4.1.2 on Windows 7.

**Comment by dbaeumer** [comment]
@stkb @englund this is a problem of using bash. The corresponding issue is tracked here: https://github.com/Microsoft/vscode/issues/28036 and https://github.com/Microsoft/vscode/issues/30417

**Comment by stkb** [comment]
@dbaeumer Thanks, can confirm it does work if I switch back to cmd for the terminal. Will close this as it seems to be a dup of #30417.
