### ISSUE TITLE
Upgrade to V1.14.0 is a bad dream

### ISSUE THREAD

**Issue by adyanced** [Microsoft/vscode#30480]
I am using VS Code to debug a RN project. as I upgrade to V1.14.0 this morning, a bad dream is coming:
1. The 'Stop Debug' button act as 'Reset', have to double-click to stop debugging
2. The 'Reset' button reload the apk endlessly
3. The apk always stopped at 
![image](https://user-images.githubusercontent.com/6321512/28108896-b4f47ce2-671f-11e7-96cb-61045d81e284.png)
except the first load

How to downgrade VS Code?

**Comment by weinand** [comment]
How does your launch configuration look like?

**Comment by weinand** [comment]
Or you are suffering from this:
from the VS Code 1.14 [release notes](https://code.visualstudio.com/updates/v1_14#_nodejs-v80-related-changes):
> In this release, Node.js debugging will assume the "inspector" protocol whenever the runtimeExecutable attribute of a launch configuration is set. If you see your debug configurations failing, this change could be the reason. To fix this, you can either upgrade Node.js to version 8.x or you can explicitly force the use of the "legacy" protocol by adding "protocol": "legacy" to your launch configuration.

**Comment by adyanced** [comment]
This is launch.json:

{
    "version": "0.2.0",
    "configurations": [
{
    "name": "Debug Android",
    "program": "${workspaceRoot}/.vscode/launchReactNative.js",
    "type": "reactnative",
    "request": "launch",
    "platform": "android",
    "sourceMaps": true,
    "outDir": "${workspaceRoot}/.vscode/.react"
},
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "target": "iPhone 5s",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Attach to packager",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "attach",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Debug in Exponent",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        }
    ]
}

**Comment by weinand** [comment]
You are using the React Native extension (which is not a standard part of VS Code).
I'll move this issue to the React Native repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-react-native#471
