### ISSUE TITLE
Excessive logging of `vscode.workspace.rootPath`-usage causes high CPU load

### ISSUE THREAD

**Issue by nadircan** [Microsoft/vscode#30486]
- VSCode Version: 1.14.0
- OS Version:  Microsoft Windows 10 Enterprise  10.0.15063
I updated my vscode this morning. My system cpu usage increased to %100. It was not like that before.
My cpu is i7 6500u.

**Comment by jrieken** [comment]
@nadircan Are you using the `atefth.ruby-on-rails-snippets` extension? It contains a (valid snippet) that makes us choke. See https://github.com/Microsoft/vscode/issues/30407 for more details. It might be that

**Comment by juanmirod** [comment]
I just updated and VSCode is unusable, I can navigate between tabs and open/close files, but the moment I start to write cpu use goes up and the editor starts lagging.

**Comment by nadircan** [comment]
![errorvscode](https://user-images.githubusercontent.com/11965934/28114309-f5a1e14c-6708-11e7-8683-4c15026c44d7.PNG)

Also i get this error. @jrieken I remember,  I dont use that extension. I cant access extension tab. It comes empty.

**Comment by F0rt1s** [comment]
I have the same problem. After opening an angular 4 project, when I start typing in a typescript file processor load rises, typing is sluggish and after a while I get "The window is no longer responding".  Only running extensions are the ones installed by "Angular Essentials".

**Comment by MickeySegal** [comment]
I'm having the same huge CPU usage in an Angular 4 project, resulting in freezes for ~15 seconds on a fast computer.  The problem occurs whether or not the code is running in a browser.  I first saw the problem within minutes of the VSCode Version: 1.14.0 release.  OS=Windows 10 (both before and after the updates of 11 July).

Extensions: 
- angular2-inline
- Bracket Pair Colorizer
- Debugger for Chrome
- NgBootstrap Snippets
- TSLint
- TypeScript Hero

**Comment by jrieken** [comment]
Ok, different folks with potential different problems. Everyone here please do the following

* F1 > Toggle Developer Tools > Select *Profile* tab
* Select *Record JavaScript CPU Profile*, select *Start*
* Now do whatever you did you make it hang, appear as slow, show the not responsive warning
* Stop recording, *Save* the profile, and attach it here. 

Thanks.

**Comment by F0rt1s** [comment]
As reported on a different thread: Changing the typescript workspace version to 2.3.4 fixes the problem.

**Comment by jrieken** [comment]
This is a kitchen sink issue. /cc @mjbvz since some folks suggest this has something to do with angular & TypeScript

**Comment by simonneedham** [comment]
I upgraded 4 hours ago. Since then I've seen slow/unresponsive intellisense and plenty of  'not responding' & 'the window has crashed' messages.

Extensions Installed:
- Angular Language Service
- Angular v4 TypeScript Snippets
- C#
- Debugger for Chrome
- TSLint
- TypeScript Hero
- Visual Studio Keymap
- vscode-icons

I've run a few profile captures, but only been able to capture a slow/non-responsive intellisense so far.

[Waiting-a-minute-for-intellisense-completion-to-suggest-a-local-variable-name-CPU-20170712T144506.zip](https://github.com/Microsoft/vscode/files/1142274/Waiting-a-minute-for-intellisense-completion-to-suggest-a-local-variable-name-CPU-20170712T144506.zip)

**Comment by johnnyreilly** [comment]
I'm wondering if TypeScript Hero is the problem here...  Just disabled it and **so far** it hasn't locked up again.

**Comment by MickeySegal** [comment]
The other main thread on this issue is https://github.com/Microsoft/vscode/issues/30449, discussing changing the typescript workspace version to 2.3.4

**Comment by jrieken** [comment]
Thanks @simonneedham and @johnnyreilly. There is something fishy with us and TypeScriptHero. I'll make sure to have local repro to confirm my theory and update this issue

**Comment by simonneedham** [comment]
@johnnyreilly @jrieken  I just switched off TypeScript Hero. Instant improvement.

**Comment by jrieken** [comment]
So, the following is happening here and a good example for how easy things can go south... As some of you already know, we are currently working on supporting [multiple root folders](https://github.com/Microsoft/vscode/labels/multi-root) in VS Code. Many things have already happened in that area and one thing we focus on is extensions. Until now, there is just the `vscode.workspace.rootPath`-API which isn't sufficient anymore once multiple (root) paths come into play. We will keep that API stable but also want extensions to eventually adopt the new and better [API for multiple root paths](https://github.com/Microsoft/vscode/issues/28526). To get an understanding how the current API is used and to be able to help out extensions authors with advise, PRs, etc. we have added telemetry ala "*extension 'foo' uses 'rootPath'*". What we didn't account for is extensions using this a lot (like in loops) and making us choke on many, many repeated events. So, TypeScript Hero is [doing that](https://github.com/buehler/typescript-hero/blob/master/src/extension/extensions/ImportResolveExtension.ts#L100) and that's totally OK.  I make sure we send less events...

**Comment by jrieken** [comment]
Pushed a fix to `master` and `release/1.14` which mean Insiders is fixed in ~12 hours and stable as soon as we release 1.14.1

**Comment by buehler** [comment]
I'm currently working on a hot fix for typescript hero, so that the extension only accesses `workspace.rootPath` once and passes it down to the components via DI.

**Comment by buehler** [comment]
@jrieken Out of curiosity, when did you guys add the reporting for rootPath?

**Comment by MickeySegal** [comment]
A new version of TypeScript Hero was released with a workaround to this problem. More information at buehler/typescript-hero#242

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/30486#issuecomment-314814776 [Early](https://github.com/Microsoft/vscode/commit/2792c5cd97c44b9e299008a62a071ed54bc9cc06) June, so it should have been in Insiders for quite a while.

**Comment by sandy081** [comment]
Fix looks good. Verified by code review.
