### ISSUE TITLE
Make update process faster on Windows

### ISSUE THREAD

**Issue by Clarkey** [Microsoft/vscode#30491]
I'm in a corp environment where we have a policy-driven on-demand virus scanner. This painfully slows down the update process of VS Code due to the scanning of every individual .js file.

I'm using a HP Z620 with SSDs... I can't imagine how slow it is for the average user with the same virus scanner.

Is there a way to 'bundle' the installation files together to increase speed during installation, or even maybe  update VS Code in the background and ask me for confirmation before the update-enabling relaunch?

**Comment by joaomoreno** [comment]
Going with #13308 instead. It should just be done in the background, regardless of speed.
