### ISSUE TITLE
Close quick open when opening a menu

### ISSUE THREAD

**Issue by OMGasm** [microsoft/vscode#30495]
Clicking on the preferences icon/update indicator does not close the command palette or similar menus.
(Also applies to the 'open changes' and '...' buttons)

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
---

Steps to Reproduce:

1. Open the command palette(or similar)
2. Click(any button) on the preferences/update indicator icon
3. $$$ Watch as inconsistency ensues.

Reproduces without extensions: Yes

![2017-07-12_20-10-22](https://user-images.githubusercontent.com/1008183/28112918-08e31174-673e-11e7-8d5b-e92860191e24.gif)

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

In my opinion regardless of the `workbench.quickOpen.closeOnFocusLost` option being set to `false`, I think the mouse click should remove the Command Palette. That is, if I click in the middle of the file the Command Palette should close.

So @bpasero , can this request be followed in this case or should I create another?

**Comment by bpasero** [comment]
@Tekbr yours sound like a separate request

**Comment by Tekbr** [comment]
@bpasero Thanks for the answer. I created this issue #30540.
