### ISSUE TITLE
Configure excludes is not suitable for mono-repos

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#30498]
Probably related with #26337 and #16115

- VSCode Version: 1.14 insiders
- OS Version: Mac OSx El capitan

Steps to Reproduce:

1. Create any kind of mono_repo, with subfolders including node modules
2. Intellisense will ask you to configure excludes very often

Reproduces without extensions: Yes

Basically the problem is that you can not exclude recursive subdirectories. I have a mono-repo structure, where each package has it's own node_modules folder. I tried with all kind of exclude patterns, but none of them works

```json
{
    "exclude": [
        "node_modules",
        "**/node_modules",
        "**/*.log"
    ]
}
```

**Comment by chrmarti** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1633

**Comment by Gama11** [comment]
@chrmarti I think "Mono" in this issue was referring to the [monorepo "workflow"](https://danluu.com/monorepo/), rather than a "(C# ) Mono repo"?

**Comment by chrmarti** [comment]
Thanks @Gama11 . @danielo515 In which file are you specifying these excludes? That doesn't seem to be a built-in config file.

**Comment by danielo515** [comment]
That is the JavaScript config file that visual studio code generates. I'll try to post my folder structure in more detail later

**Comment by chrmarti** [comment]
@danielo515 Can you post your entire `jsconfig.json` here?

**Comment by danielo515** [comment]
The one that I posted is my entire jsconfig.json . What are you missing ?

**Comment by chrmarti** [comment]
Ack. Looks like you need to specify a 'list of files': `"**/node_modules/*.js"` works.

**Comment by danielo515** [comment]
Why are you closing the issue ? If that is the expected way of doing things, where is it documented?

**Comment by chrmarti** [comment]
There is some documentation here: https://code.visualstudio.com/docs/languages/jsconfig#_using-the-exclude-property

Unfortunately the example isn't good, `"node_modules"` in the same folder as the jsconfig.json is excluded by default. @mjbvz Could you confirm? Should we change the example to exclude `"lib/*.js"`?

**Comment by danielo515** [comment]
@chrmarti your suggestion does not work, the configure excludes message still appearing. Have tried it? This is my folder structure


```
.
├── jsconfig.json
├── lerna.json
├── node_modules [511 entries exceeds filelimit, not opening dir]
├── package.json
└── src
    ├── case-alerts-config-to-query
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-configs-poller
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-db-connect
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-evaluator
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-evaluator-service
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-examples
    │   ├── node_modules
    │   ├── package.json
    │   └── src
    ├── case-alerts-filter
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-input-service
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-result-processor
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-results-fetcher
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-results-multiplexer
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    ├── case-alerts-simplify-result
    │   ├── node_modules
    │   ├── package.json
    │   ├── src
    │   └── test
    └── case-alerts-test-utils
        ├── node_modules
        ├── package.json
        ├── src
        └── test
```

**Comment by chrmarti** [comment]
@danielo515 Maybe `"**/node_modules/**/*.js"` works better?

**Comment by danielo515** [comment]
@chrmarti are you sure that should work ? According to Microsoft/TypeScript#16115  this may not work

**Comment by chrmarti** [comment]
Good catch, I should have tested that first. That leaves you with the option of listing each `"case-alerts-test-utils/node_modules/**/*.js"` I guess (haven't tested it).

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12750

Try:

```json
    "exclude": [
        "**/node_modules/*"
    ]
```

This is super confusing though. `"exclude": ["**/node_modules"]` really should work too. That's what https://github.com/Microsoft/TypeScript/issues/12750 tracks

Closing as upstream

**Comment by danielo515** [comment]
Hello @mjbvz 

> This is super confusing though. "exclude": ["**/node_modules"] really should work too. That's what Microsoft/TypeScript#12750 tracks
>
>Closing as upstream

Maybe this is a duplicate of Microsoft/TypeScript#12750, however there is no issue on VSCode repository about this topic. Maybe it will be a good thing to keep this one open (linked to their typescript counterpart) so people reaching VSCode repository with this problem can easily spot the actual source of the problem. What do you think ?

**Comment by mjbvz** [comment]
@danielo515 To help with issue tracking, we generally close upstream issues if no action can be take on the VSCode side

**Comment by danielo515** [comment]
@mjbvz I understand. However the solution you proposed works ( I confirmed it today) could you at least at it as part of the documentation? I understand that you can not do anything in the upstream issue, but at least you are able to warn the users on the documentation instead of keeping an example that is absolutely useless.

Thanks and regard
