### ISSUE TITLE
Unrequested (wrong) indentation

### ISSUE THREAD

**Issue by Avol-V** [Microsoft/vscode#30497]
- VSCode Version: 1.14.0
- OS Version: Ubuntu 16.04.2

Steps to Reproduce:

Just type `if ( some )` in ts file and press `Enter`
```ts
if ( some )
	// Indentation is there
```
But i use brace-in-new-line code style so then I type `{` and `Enter` with this result:
```ts
if ( some )
	{
		// Cursor
	}
```
should be:
```ts
if ( some )
{
	// Cursor
}
```

There was no such annoying indentation in version before 1.14, and it was OK — I decide how to make indentation by myself.

Changing `editor.autoIndent` setting has no effect.

**Comment by rebornix** [comment]
We no longer indent after entering on a line without opening bracket, which means entering after `if (some)` will get 

```
if (some)
|
```

The following typing works as expected.
