### ISSUE TITLE
XSLT Emmet stopped working

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#30496]
- VSCode Version: Insiders 1.15.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Make an XSL file with a basic XML structure
2. Type 'wh' + tab, it incorrectly expands to '\<wh\>\</wh\>'
3. Set "emmet.useNewEmmet":false in preferences
4. Type 'wh' + tab in the XSL file... it expands (correctly) to: '<xsl:when test=""></xsl:when>'

Same for other xsl emmet extensions.

'if' expands to '\<if\>', but should expand to '<xsl:if test=""></xsl:if>'

**Comment by ramya-rao-a** [comment]
@sergeche I believe this is because [xml snippets](https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L920) are not present in https://github.com/emmetio/snippets

What are your plans to support xml in Emmet 2.0?

**Comment by sergeche** [comment]
Yes, these snippets are missing now, will add them

**Comment by ramya-rao-a** [comment]
Thanks @sergeche 

I created https://github.com/emmetio/atom-plugin/issues/30 to track this, since you are using that repo for tracking general issues

**Comment by ramya-rao-a** [comment]
Created PR https://github.com/emmetio/snippets/pull/1 to fix this upstream
