### ISSUE TITLE
Correct translation: Change of 'miToggleDevTools' in german (deu)

### ISSUE THREAD

**Issue by mesche** [Microsoft/vscode#30492]
- VSCode Version: Code 1.14.0  
- OS Version: Darwin x64 16.6.0

File: i18n/deu/src/vs/code/electron-main/menus.i18n.json 
Line 143
Key: miToggleDevTools
Correct value: '&&Entwicklungertools umschalten' to '&&Entwicklertools umschalten'

**Comment by danyeh** [comment]
Fixed by Carsten Kneip. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/111042318?q=Toggle Developer Tools
