### ISSUE TITLE
suggestion: delete a couple of empty brackets quotes and html tags more easily

### ISSUE THREAD

**Issue by meritozh** [Microsoft/vscode#3049]
Some snippets generated by Emmet shipped with VSCode will add some attributes automatically that i needn't. Please add this feature for all languages.

**Comment by egamma** [comment]
Pls add an example/snippet that illustrates the problem.

**Comment by meritozh** [comment]
![delete](https://cloud.githubusercontent.com/assets/7543300/13103555/379dcc14-d592-11e5-9fd3-65dfbcdb5cb4.gif)
like this, can delete a couple of empty brackets quotes and html tags by pressing once

**Comment by alexandrudima** [comment]
@meritozh Is this still an issue?

Backspace deletes both brackets:

![siy7soppaj](https://cloud.githubusercontent.com/assets/5047891/16652738/3e15662e-4455-11e6-8fd7-57574f2b2099.gif)

**Comment by meritozh** [comment]
Works fine.
Thanks for your working.
