### ISSUE TITLE
Global search: shows in results when excluded

### ISSUE THREAD

**Issue by NitroGhost** [Microsoft/vscode#30493]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-eslint|dba|1.2.11
python|don|0.6.7
pgsql|dou|0.0.8
vscode-scss|mrm|0.6.2
mssql|ms-|1.0.0
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
dust|nem|0.0.1
vscode-docker|Pet|0.0.16
material-icon-theme|PKi|2.0.10
java|red|0.7.0
sass-indented|rob|1.4.1
code-settings-sync|Sha|2.8.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. add folder name to excludes list within search
2. have a file open that's within that folder
3. search something you want to find in other files within other non-excluded folders, but could also match the open, excluded file
4. revel in the marvelous results

screenshot:

![screenshot](http://i.imgur.com/xdmXywR.png)

**Comment by roblourens** [comment]
Covered by https://github.com/Microsoft/vscode/issues/29658
