### ISSUE TITLE
Debug Active Bar - usability feature-request

### ISSUE THREAD

**Issue by Jusys** [Microsoft/vscode#30490]
I like to use Debug Action Bar but it's somewhat inconvenient - it covers open tabs and I must move it around constantly (see image):
![vsc-old](https://user-images.githubusercontent.com/30110941/28110505-555e579a-66fb-11e7-99ac-e0e41e0695fb.jpg)

Suggestion:
Please, add a config file option "debug.actionBarPosition": "default" || "workbench".
"default" or not specified - classic behavior
"workbench" - debug controls are moved to workbench (see image):
![vsc-debug](https://user-images.githubusercontent.com/30110941/28111212-6bcac1b0-66fd-11e7-8c1d-8b9c9463501e.jpg)

For colored controls you can add third option if you like "workbenchColor" (see image):
![vsc-debug-color](https://user-images.githubusercontent.com/30110941/28111385-f5e01d0a-66fd-11e7-8d65-6f51c98c08d9.jpg)

- VSCode Version: 1.14
- OS Version: Windows 7

Steps to Reproduce:

1. Remove ["debug.hideActionBar": true] from VSC configuration (if any) or set it to "false".
2. Press [F5] to launch debugging session.
3. Debug Action Bar opens and covers open tabs.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2513
