### ISSUE TITLE
SCM: Disable Preview   ：cannot find the command 

### ISSUE THREAD

**Issue by peanutDD** [Microsoft/vscode#30506]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
That command no longer exists. How do you trigger that?
