### ISSUE TITLE
Extra space appears at the beginning of uncommented line in html/css

### ISSUE THREAD

**Issue by dial8gue** [Microsoft/vscode#30501]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
---

Steps to Reproduce:

1. Open any html/css file
2. Comment line with ctll+/
3. Uncomment line with ctll+/
4. Extra space appears at the beginning of uncommented line

Reproduces without extensions: Yes

**Comment by rcktscnc** [comment]
If you comment and uncomment a block using Shift+Alt+A in any language, two extra spaces are added -- one in the beginning and another in end of the block.

**Comment by rebornix** [comment]
Already fixed by https://github.com/Microsoft/vscode/pull/30818 . Thank you.
