### ISSUE TITLE
The clean all button in the changes header of the git tab does not behave as expected.

### ISSUE THREAD

**Issue by jockjocko** [Microsoft/vscode#3050]
Pressing the clean all button (Designed to look like an undo button) removes all untracked files and folders as it calls _git clean -fd_
We would expect it to clean only the files shown in the changes list.
We think this was how it use to work with an older version of vscode.

Thanks.

**Comment by joaomoreno** [comment]
![bug](https://cloud.githubusercontent.com/assets/22350/13080063/649aee34-d4c7-11e5-98b2-21ca12d906df.gif)

The `Clean All` button cleans all changes in the `Changes` section. Untracked files and folders appear in the `Changes` section, so they are also cleaned up. It has always worked that way since the first release.

**Comment by jockjocko** [comment]
Yes but this doesn't seem to be taking into account the git ignored files and folders which in our case include the node_modules directories.

**Comment by joaomoreno** [comment]
Ignored files and folders should not be *cleaned* since they don't appear in the list. Are you saying that in your machine they are being cleaned up?

**Comment by jockjocko** [comment]
Correct, it appears that the command being run is git clean -fd which is removing my git ignored files and folders. should it not be running _git reset --hard_ which will reset all changes to tracked files ?

**Comment by joaomoreno** [comment]
What is interesting is that we never call `git clean -fd` without any other arguments. Can you please open the Git Output view and show me the exact `clean` command Code is running?

![image](https://cloud.githubusercontent.com/assets/22350/13082050/56258d2a-d4cf-11e5-865a-dc21f8d4265d.png)

**Comment by jockjocko** [comment]
![vscode-gitoutput](https://cloud.githubusercontent.com/assets/8030087/13082942/bc268d2c-d4ca-11e5-8777-747b0522fcb4.png)

**Comment by joaomoreno** [comment]
Oh, I take it back, it doesn run `git clean -fd`. Sorry about that.

But what I find strange is that it doesn't happen to me. I always have a bunch of stuff inside `node_modules` which never gets erased. Git would only remove them if passing the [`-x` option](https://git-scm.com/docs/git-clean) to the `clean` command, which we don't.

Did you maybe update `git` itself? What version of git do you have? Do you ignore `node_modules` in `.gitignore`?

**Comment by jockjocko** [comment]
Yeah it is ignored. my git version is 2.6.4.
It does seem like this is now a git issue rather than a vscode issue i will investigate it further.

Thanks for the assistance.

**Comment by joaomoreno** [comment]
Alright, let me know what you find, I'm curious in knowing.
