### ISSUE TITLE
No snippet suggestions after whitespace

### ISSUE THREAD

**Issue by alesmik** [Microsoft/vscode#30508]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11

---

Steps to Reproduce:

1. Create new "*.html" file, <Ctrl+Space>, choose a snippet from suggestions, insert it... Ok.
<img width="514" alt="1" src="https://user-images.githubusercontent.com/29822207/28117861-ad4186d2-6717-11e7-9ea9-3121805df526.png">

2. Place cursor somewhere inside, <Ctrl+Space> to choose another one... no snippets.
<img width="531" alt="2" src="https://user-images.githubusercontent.com/29822207/28117867-b611f0a8-6717-11e7-864e-4ad3e72b7700.png">

Reproduces without extensions: Yes

**Comment by PunchyRascal** [comment]
I have the same problem, but when I invoke the suggest second time, the snippets suddenly appear.

**Comment by alphang** [comment]
I'm seeing the same problem as well. In my case, pressing Ctrl+Space only works at the beginning of a line. 

![user-snippet](https://user-images.githubusercontent.com/2280666/28293212-f41e9704-6b07-11e7-83fa-8429871731da.gif)

I suspected this has to do with `emmet.showAbbreviationSuggestions`, but the same behaviour occurs even when I have `"emmet.useNewEmmet": false,`
