### ISSUE TITLE
start debugging "Cannot connect to runtime process, timeout..."  error

### ISSUE THREAD

**Issue by simlw** [Microsoft/vscode#30504]
- VSCode Version: 1.14
- OS Version: macOS 10.12.5

When I start debugging, I get this error: 
```
Cannot connect to runtime process, timeout after 20000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:21937).
```
But VSCode Version 1.13 is OK. I have saw that the debug console info is different between the two versions. In the console log of Version 1.14, there is one more parameter **--inspect=21937**.
The following is the log info:
```
// V1.14
... node_modules/electron/dist/electron.app/Contents/MacOS/electron --inspect=21937 --debug-brk --nolazy app/main.js 

// V1.13
node_modules/electron/dist/electron.app/Contents/MacOS/electron --debug-brk=36090 --nolazy app/main.js 
```

And here is my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "timeout": 20000,
            "name": "启动",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app/main.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": "${workspaceRoot}/app/node_modules/electron/dist/electron.app/Contents/MacOS/electron",
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development",
                "DEBUG": "device, recium, script, socketServer, tracker"
            },
            "sourceMaps": true
        }
    ]
}
```
Is this a bug or something wrong with my launch.json file?

**Comment by roncli** [comment]
Adding `"protocol": "legacy"` temporarily resolves the problem for me.

**Comment by simlw** [comment]
@roncli, yes that works for me too, thank you

**Comment by weinand** [comment]
This is not a bug but the excepted behaviour.
from the VS Code 1.14 [release notes](https://code.visualstudio.com/updates/v1_14#_nodejs-v80-related-changes):
> In this release, Node.js debugging will assume the "inspector" protocol whenever the runtimeExecutable attribute of a launch configuration is set. If you see your debug configurations failing, this change could be the reason. To fix this, you can either upgrade Node.js to version 8.x or you can explicitly force the use of the "legacy" protocol by adding "protocol": "legacy" to your launch configuration.

**Comment by roncli** [comment]
@weinand While legacy is working for me, I'm curious how one would go about debugging with the "inspector" protocol?  It is sending `-debug-brk` as a switch, which basically causes Electron to do nothing on start.

**Comment by weinand** [comment]
Electron versions only support a single protocol. So if your Electron supports the "legacy" protocol, it won't support "inspector" and vice versa. This behaviour is different from node.js (which supports both protocols in versions < 8.0). 
Electron will support the "inspector" protocol in version 1.7.2.
VS Code will support debugging with the "inspector" protocol, as soon as we have verified that it works with Electron 1.7.2.
