### ISSUE TITLE
Quick recommended time setting invalid

### ISSUE THREAD

**Issue by Lurkerc** [Microsoft/vscode#30507]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.1.0
copy-relative-path|ale|0.0.1
file-smart-reopener-vscode|big|0.0.1
githistory|don|0.2.1
windows-explorer-context-menu|ele|1.0.2
vscode-element-helper|Ele|0.1.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.6.25
beautify|Hoo|1.1.1
path-autocomplete|ion|1.5.1
docthis|joe|0.4.7
code-beautifier|mic|1.7.2
gitignore|mic|1.0.1
HTMLHint|mka|0.3.3
debugger-for-chrome|msj|3.1.6
color-highlight|nau|2.3.0
syncing|non|1.4.0
vetur|oct|0.9.1
vuehelper|oys|0.1.0
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.10.1
indenticator|Sir|0.4.2
guides|spy|0.8.4
JavaScriptSnippets|xab|1.4.1
vscode-preview-server|yui|0.6.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. `F1` , Open User Settings, set `"editor.quickSuggestionsDelay":1`; 
2. quick advice is only shown after 10 milliseconds

Reproduces without extensions: No

**Comment by chrmarti** [comment]
I don't think there is any guarantee we can make here. How are you measuring this and why do the 9 ms matter?

**Comment by Lurkerc** [comment]
In the JS file, the quick advice is displayed based on the user setup time, but in non JS files such as Vue, the quick advice display time is the default 10ms and is not loaded as per the user settings.
There was no problem with the previous version.

**Comment by ramya-rao-a** [comment]
I set the delay to 1000 (1s)
And it works as expected ( I tested in HTML file)

I am curious, how are you measuring this time in milliseconds?
