### ISSUE TITLE
Monokai PHP Syntax Highlighting Broken on New Release

### ISSUE THREAD

**Issue by kucharovic** [Microsoft/vscode#30500]
Syntax highlighting of method names, `$this` variable, `::class` constant for PHP language in Monokai theme is broken. See screenshot:

![monokai-php-syntax](https://user-images.githubusercontent.com/1418898/28114320-a3bbbba8-6700-11e7-8315-4b73482b1d78.png)

- VSCode Version: 1.14
- OS Version: Ubuntu 16.04

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Is it broken? I see it marked as `keyword.other.class.php` which seems correct.

**Comment by aidantwoods** [comment]
I've noticed some strange changes too (quiet-light)

* `$this` variable is coloured same as class constant, should be coloured same as other vars (purple).
  <img width="188" alt="screen shot 2017-07-12 at 22 25 04" src="https://user-images.githubusercontent.com/3288888/28140631-02a59742-6751-11e7-847b-34502b4d1948.png">

* Class name coloured same as class constant after `instanceof` language keyword, should be coloured same as class (bold purple)
  <img width="317" alt="screen shot 2017-07-12 at 22 24 16" src="https://user-images.githubusercontent.com/3288888/28140632-02a61b36-6751-11e7-9843-825bb0184154.png">
  <img width="340" alt="screen shot 2017-07-12 at 22 24 23" src="https://user-images.githubusercontent.com/3288888/28140630-02a36c2e-6751-11e7-96a1-b55a7f884530.png">

**Comment by smuuf** [comment]
Well, the recent update *did* quite change the way the PHP code looks *(I noticed that also in themes other than Monokai)*, and that - imo -  is usually not something one would totally expect from upgrade of the editor. 

I know *I* was surprised and I had to immediately go edit the third-party theme I use so it would look like yesterday. :)

**Comment by smuuf** [comment]
And since we're reporting strange syntax highlighting issues here, I'll add mine:

**Weird stuff happens if one tries to `use` a trait with absolute namespace.**

![aaa](https://user-images.githubusercontent.com/6860713/28140883-8123b87a-675a-11e7-9884-d3485bdb8190.gif)

**Comment by aidantwoods** [comment]
Forget to mention this one. Class name doesn't seem to be recognised when using the Paamayim Nekudotayim operator.

<img width="154" alt="screen shot 2017-07-14 at 18 22 57" src="https://user-images.githubusercontent.com/3288888/28222979-80ba62d6-68c1-11e7-9a5b-3fcfc55d0484.png">

See that new instance of class, class name is purple. Yet in the first line it is not.

**Comment by roblourens** [comment]
The issue in the OP is just due to changes in the grammer which I think are correct. Same goes for @aidantwoods' post about $this and class names. Issues for that could be tracked at https://github.com/atom/language-php but it looks like it's applying the right tokens to me.

However there are at least a couple legit syntax highlighting issues in the past release - the `use \Foo` issue is #30448 and the `Foo::Bar` issue is https://github.com/Microsoft/vscode-textmate/issues/50

**Comment by aidantwoods** [comment]
>  Same goes for @aidantwoods' post about $this and class names

I can kind of see why `$this` might have a special colour. I'm confused as to why the class name colour would change when it is used with a different operator though? (i.e. the `instanceof` v.s. `new` operator).

> it looks like it's applying the right tokens to me

Any pointers as to how I could debug this myself? Noticing a lot of things that look like highlighter bugs recently. Hard to know from the outset if these are bugs or colour scheme changes.

I'm also a little unsure where I should report new issues RE this, you referenced three different repos ;p

**Comment by roblourens** [comment]
If you want to see what's going on, you can run the command `Developer: Inspect TM Scopes`. 

![image](https://user-images.githubusercontent.com/323878/28693540-052e965a-72da-11e7-9882-96207831ffc9.png)

You can see that for `instanceof Xyz`, it's coloring Xyz as a constant. If you use `\Xyz` then it knows it must be a class. If you think that's wrong, you could open an issue in the atom/language-php repo which is where the actual grammar lives. We share it with the Atom editor so you can check there too (although they may be on a different version of the grammar than us).

This is all quite complicated because it's never obvious what the "right" token names are, and sometimes a theme expects something different than what the grammar provides. But my first stop in debugging is examining the scopes and trying to decide whether they sort of make sense.

**Comment by aidantwoods** [comment]
Cheers for the tip for that debug menu.

Using the information there (in-fact just from the screengrab) can confirm that this is indeed a bug. In PHP you can only use variables for a string representation of a class (putting a constant there is ambiguous as you can have a class with the same name). Not sure how well known this is though, but it is the case nonetheless 😉  (meaning constants and variables with the same value aren't interchangable 🤷‍♂️ ).

<img width="194" alt="screen shot 2017-07-27 at 23 26 26" src="https://user-images.githubusercontent.com/3288888/28694723-1f111a86-7323-11e7-8df8-d106e7178f4f.png">


Just like `new`, `instanceof` is really an object operator, so you can unambiguously know that the RHS cannot be a `const`.

<img width="306" alt="screen shot 2017-07-27 at 23 24 17" src="https://user-images.githubusercontent.com/3288888/28694747-3a24cd9a-7323-11e7-93f7-1cc2833ff04e.png">

I'll open a bug in atom/language-php :)

**Comment by kucharovic** [comment]
@roblourens PHP syntax highlighting for method names, `$this` and `::class` constant is still broken – even in Insiders build. Now are additionaly broken phpDoc comments:

![broken-syntax](https://user-images.githubusercontent.com/1418898/29204577-29cc0bb0-7e78-11e7-88f3-f04d24b1309e.png)

**Comment by roblourens** [comment]
Like I said above, those are expected. The colorization in phpdoc comments is correct too. Different types are colored different ways.

**Comment by kucharovic** [comment]
@roblourens as I look into scope inspector – it's not correctly detected. If I understand correctly, vscode uses [atom/language-php](https://github.com/atom/language-php) for PHP syntax highlight. But in latest version of Atom is everything detected fine (as in v1.13 of vscode) – see:

Method call (function name):
![function name](https://user-images.githubusercontent.com/1418898/29261747-7a44d3f0-80d1-11e7-9508-a801f45bd159.png)
`$this` keyword:
![this](https://user-images.githubusercontent.com/1418898/29261763-8965619c-80d1-11e7-96a3-8fe26dec1391.png)
`::class` constant
![class](https://user-images.githubusercontent.com/1418898/29261753-7fa2ae12-80d1-11e7-8771-122ac2fa2f49.png)
phpDoc `invalidargumentexception`:
![invalidargumentexception](https://user-images.githubusercontent.com/1418898/29261774-96c39d68-80d1-11e7-8a66-cfd28bb59be5.png)
phpDoc `string`:
![string](https://user-images.githubusercontent.com/1418898/29261779-9c765354-80d1-11e7-907f-b3489d9745ee.png)

**Comment by roblourens** [comment]
Atom has been less proactive in shipping updates to the PHP grammar, so you probably are just seeing the impact of the old grammar.

Thanks for all the screenshots, but what are you arguing exactly? The 1.16 scopes look accurate or more so than the 1.13 scopes.

**Comment by acb** [comment]
@roblourens here's at least part of the issue: in the following code you can see that referring to classes statically isn't getting highlighted.
![code](https://user-images.githubusercontent.com/4690898/29377600-4bbc18ee-828a-11e7-8cab-eb73fca09b0f.png)
If you inspect the class that is detected (`\Path\To\Class`), you can see that the string has `support.class.php` on it as you would expect.
![class-detected](https://user-images.githubusercontent.com/4690898/29377666-7aa79fca-828a-11e7-8894-ca49e31f116c.png)
For the static calls they don't have `support.class.php`, and they should.
![class-not-detected](https://user-images.githubusercontent.com/4690898/29377755-c1cb48f2-828a-11e7-8c9c-f026e1a07179.png)

**Comment by roblourens** [comment]
This one is a real issue. And not just a grammar issue but possibly an issue with our grammar parser: https://github.com/Microsoft/vscode-textmate/issues/50
