### ISSUE TITLE
Visual Studio code not responding

### ISSUE THREAD

**Issue by thorwins** [Microsoft/vscode#30502]
- VSCode Version: 1.14.0
- OS Version: MacOS Sierra (10.12.5)

Steps to Reproduce:

1.launch Visual Studio
2. it will be frozen, after a bit it show a dialog window: The window is not longer responding

Reproduces without extensions: Yes/No

**Comment by brunoeris** [comment]
The same here : /

VSCode: 1.14.0
MacOS Sierra 10.12.5

**Comment by RobinNord** [comment]
Same here at:
Win 10 Enterprise: OS 14393.1358,
VSCode: 1.14

**Comment by thorwins** [comment]
I solved the issue uninstalling VSCode completely and reinstalling it
