### ISSUE TITLE
The find windows still hides the first line when it wraps.

### ISSUE THREAD

**Issue by DeeHants** [Microsoft/vscode#30503]
Following the fixes in #5525 (#10662, #24994, etc) the first line of content is moved below the search box when it's open.
However, it still seems to have issues with word wrapping in 1.13.1.
When the first line is short, it is moved down fully below the find window.
When it's too long and wraps, the line isn't moved down as far, and is still half occluded.

1. Ensure wordwrap is on
   "editor.wordWrap": "on"
2. Type this into a new text window (expanding to make sure it wraps):
   > abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc
3. press ctrl+f

**Comment by rbenson** [comment]
For me it isn't moved, but I can scroll above line one  1+n where n =1 if just find is open, or 2 if find/replace is open

**Comment by PunchyRascal** [comment]
Would it be possible to turn this off altogether - I mean the offsetting of the first line. It can actually get a bit annoying, wondering why the file starts on 3rd line and then having to close the search widget over and over again.

**Comment by rebornix** [comment]
Right now we don't scroll the window down directly instead we show the find widget on top of the text but you can still scroll up. For more discussion, let's track it in https://github.com/Microsoft/vscode/issues/28390
