### ISSUE TITLE
Copy-Paste and other keyboard functionality stops working

### ISSUE THREAD

**Issue by logidelic** [Microsoft/vscode#30511]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.0.27
prettify-json|moh|0.0.3
cpptools|ms-|0.12.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6

---

Steps to Reproduce:

1. Use vscode for a while

Result: Copy-paste stops working. In addition, other keyboard functionality stops working. For example, if I try to find find some text (Ctrl-F) and then press the Escape key, it will no longer close the find fields. If I close and re-open vscode, the problem is solved (for a while).

I've had this sporadic issue with all versions of vscode, but the problem seems much worse with the most recent version. It happens soon after I re-start.

Reproduces without extensions: Yes

**Comment by thekashifmalik** [comment]
Came across the exact same issue on OSX today.

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
postgresql|JPT|0.0.2
swift|Kas|0.0.3
vscode-docker|Pet|0.0.16
project-manager|ale|0.18.1
vscode-puppet|bit|0.4.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-yaml-validation|dja|0.0.1
python|don|0.6.9
tslint|eg2|0.17.0
vimL|fal|0.0.3
auto-close-tag|for|0.4.3
restructuredtext|lex|34.0.0
Go|luk|0.6.62
MagicPython|mag|1.0.11
mssql|ms-|1.1.0
debugger-for-chrome|msj|3.1.6
java|red|0.7.0
vscode-icons|rob|7.10.1
vscode-nginx|sha|0.3.1
slack|soz|0.0.13
expand-selection-to-scope|vit|0.2.0
vim|vsc|0.9.0
gitblame|wad|2.0.2
jinja|who|0.0.8
change-case|wma|1.0.0

(1 theme extensions excluded)


---

Steps to Reproduce:

1. Use VScode for a while.

**Comment by rebornix** [comment]
@logidelic @thekashifmalik did you happen to launch VSCode from tmux?

**Comment by thekashifmalik** [comment]
I did.

**Comment by rebornix** [comment]
@thekashifmalik it's an upstream issue https://github.com/electron/electron/issues/916#issuecomment-68567844 , please follow instructions there to workaround.

Close this first and if @logidelic is not running into the same problem, we can reopen.
