### ISSUE TITLE
EH debugging: use a better name for the launch config's preLaunchTask

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#30510]
(from a gitter question)

Currently the generated launch.json for the "hello world" extension uses a "preLaunchTask" named "npm" which confuses users, because they think that this is the raw "npm" command.

But this "npm" refers to the "npm" task configured in the task.json.
Only after understanding this connection it becomes clear what this "npm" really means:

```json
    // we run the custom script "compile" as defined in package.json
    "args": ["run", "compile", "--loglevel", "silent"],
```

I suggest that we rename the "npm" task to something more expressive like "compileAndWatch".

**Comment by bpasero** [comment]
Moved to https://github.com/Microsoft/vscode-generator-code/issues/83
