### ISSUE TITLE
script tag indent error

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#30517]
- VSCode Version:1.14.0
- OS Version:Windows 8.1

Steps to Reproduce:

1.create an HTML file
2.type a script tag `<script></script>`
3.when hit Enter before the `</script>` the indent is wrong, `</script>` should has the same indent with `<script>`
4 then hit the Enter after the `</script>`, the `</script>` will have no indent

Reproduces without extensions: Yes/No

**Comment by ZhangPuXi** [comment]
I want to keep my code like this
![image](https://user-images.githubusercontent.com/15119639/28121098-9e482746-674c-11e7-95e7-9f986f7cf537.png)
with step 3, it's like this
![image](https://user-images.githubusercontent.com/15119639/28121132-bcbcdce4-674c-11e7-983b-5384e51d57be.png)
with step 4, it's like this
![image](https://user-images.githubusercontent.com/15119639/28121149-cc0e2856-674c-11e7-8196-228ab99d9e66.png)
this is so strange

**Comment by ZhangPuXi** [comment]
I need to remove the empty line and add spaces before the `</script>` to make my code looks good. But if I have another script tag, I need to do the same operation again and again. Would you like to fix this? Great thanks advance. Thank you!

**Comment by powermr** [comment]
I have met with the same problem！

**Comment by sailor103** [comment]
same to me.

**Comment by ZhangPuXi** [comment]
These issues are same for `style` tag.

**Comment by Shawer** [comment]
some as me.:(

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/28393627-a88a4ca2-6c9c-11e7-8305-9ba80627821e.png)

@aeschli the open angle bracket `<` of `</script>` is seen as JavaScript, is this expected? The grammar seems ignoring `<` by purpose https://github.com/Microsoft/vscode/blob/master/extensions/html/syntaxes/html.json#L290

```
"end": "((<))(?=/(?i:script))",
"endCaptures": {
	"0": {
		"name": "meta.tag.metadata.script.html"
	},
	"1": {
		"name": "punctuation.definition.tag.begin.html"
	},
	"2": {
		"name": "source.js"
	}
}
```

Let me know if you think we should mark `</` as the beginning of a closing tag and then we can have a good guess whether the embed language source code is empty or not.

**Comment by aeschli** [comment]
The html grammar is from https://github.com/textmate/html.tmbundle and they just recently changed this to be as you observed. I don't know the reasoning. Why does it matter? How do you rely on the tokens?

**Comment by rebornix** [comment]
@aeschli I tried to be precise about what language I'm in when doing indentation adjustment. But seems I can live with this info. Thanks for your help!
