### ISSUE TITLE
Make the compare action label easier to understand when file names are identical

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#30515]
If I've selected a file `a.yaml` for comparison in multi-root folder `rootA` and use the context-menu on another file `b.yaml` in root folder `rootB`, then showing "Compare with `rootA/a.yaml`", i.e. adding the root path `rootA`, instead of just `a.yaml` would be helpful. 

cc #28344

**Comment by bpasero** [comment]
@Dominik-K well we actually never show any parent in that menu simply because we do not have much space. I think your suggestion applies already for single folder case too where you might want to know which file to compare to.

**Comment by Dominik-K** [comment]
@bpasero Oh, you're right. I didn't noticed this before as inside one project == folder, the filenames are mostly unique. But with the new, useful multi-root folders, it offers the opportunity to easily compare files with the same name, e.g. Kubernetes configurations, across different projects.

**Comment by bpasero** [comment]
Pushed changes for 2 things:

1) always show both file names in the compare action label

![image](https://user-images.githubusercontent.com/900690/29404804-5273daa2-833c-11e7-9e7d-003ff974d2d6.png)

2) show enough context in case the filenames are identical (using the same algorithm we have when having the same file name opened multiple times

![image](https://user-images.githubusercontent.com/900690/29404837-6b2df0dc-833c-11e7-9392-3dbaf8afd311.png)
