### ISSUE TITLE
VSCode as difftool does not work without --wait

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#30518]
- VSCode Version: 1.14 insiders
- OS Version: OSX El capitan

Steps to Reproduce:

1. configure vscode as difftool as explained here https://code.visualstudio.com/docs/editor/versioncontrol
2. Remove the --wait option

For some reason that I'm unable to understand, VSCode can not be used as a git difftool if you remove the --wait option. What happens is that the vscode is opened with no content, no diff, no file, just like you were just clicking on its' icon. 
If you do `code --diff fileA fileB` directly on the console it works perfectly, but it fails if you run it directly from git.

**Comment by joaomoreno** [comment]
The `--wait` version exists exactly for this purpose.

**Comment by danielo515** [comment]
Why can't just open all the files on diff state in one go?

**Comment by DominikJaniec** [comment]
@danielo515, I also do not understand why every diff should block Git for opening more tabs / windows in VS Code. I just want to see all changes, it is not a merge or commit message, where exit code of your editor matters, it is just diff...

Lets assume that I have 20 edited files, and I would like to examine them all - inside a familiar and configured environment with coding features. I would type in external console: `$ git difftool`, then being aware that this could take a while, I would go for water or something and then see them all.
