### ISSUE TITLE
Inline actions in diff view for copy, replace, previous and next

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#30519]
This proposal requests inline actions in diff view, like the inline merge actions are provided for git merge markers within the editor-
![image](https://user-images.githubusercontent.com/751732/29218899-314ce20a-7ed8-11e7-839c-3113d226a28f.png)

The code actions can be `Copy to left/right/other side`, `Replace left/right/other side`, `Previous` and `Next` (for going to previous/next diff). And as copying original is prohibited in inline diff view, there can be a `Copy original` action as well.

This proposal can be regarded as an implementation detail of the proposal #25887 .

**Comment by gulshan** [comment]
The issue is auto-labeled `git`, but it's more related to diff in general and should go into `editor` label I guess. Pinging @alexandrudima as the author of recent improvements to diff editor.

**Comment by alexandrudima** [comment]
I suggest we track in #25887 and take this suggestion into consideration when looking into #25887.
