### ISSUE TITLE
Convert to ES2015 class feature does not acknowledge tab size

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#30528]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
gitlens|eam|4.3.1
vscode-html-css|ecm|0.1.7
vscode-npm-script|eg2|0.2.0
JSDocTagComplete|Hoo|0.0.2
docthis|joe|0.4.7
csharp|ms-|1.11.0
js-atom-grammar|ms-|0.1.13
vscode-icons|rob|7.10.1
bootstrap-3-snippets|wcw|0.1.0
html-css-class-completion|Zig|1.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Right-click "Convert Function to ES2015 Class"
(2 space tab-size)
<img width="523" alt="screen shot 2017-07-12 at 11 57 36 am" src="https://user-images.githubusercontent.com/13835886/28127131-8fe7c420-66f9-11e7-8e81-572acd658c38.png">
(4 space tab-size)
<img width="412" alt="screen shot 2017-07-12 at 11 57 47 am" src="https://user-images.githubusercontent.com/13835886/28127152-9d689110-66f9-11e7-95fa-504fa4f1e4b5.png">

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/17129
