### ISSUE TITLE
Autocomplete/Intellisense Does Not Show All Options For Object Value

### ISSUE THREAD

**Issue by JonnyBoy333** [Microsoft/vscode#30526]
- VSCode Version: 1.14.0
- OS Version: macOS 10.12.5

Autocomplete/intellisense is not showing all the options for an object that goes into a function parameter even though it is defined in a typescript interface.

Example:
```
interface Fruit {
    /** Returns a fruit color. */
    getFruitColor(options: { fruit: 'apple' | 'orange' }): string;
    getFruitColor(options: { fruit: 'banana' }): boolean;
}

function testFunction (fruit: Fruit) {
    let color = fruit.getFruitColor({ fruit: '' }); // <-- Autocomplete only shows apple and orange as options and not banana
}
```
![screen shot 2017-07-12 at 10 27 36 am](https://user-images.githubusercontent.com/15164008/28125639-cae175a6-66ec-11e7-813c-22a579c65554.png)

It appears that only the first method's options object is getting indexed by VS autocomplete but not the second one.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17127

**Comment by JonnyBoy333** [comment]
Thanks the quick action. I would like to note, however, that other IDE's seem to be able to handle this situation, which is why I put it under the vscode github instead of typescript.

Example:
WebStorm
![screen shot 2017-07-12 at 12 14 13 pm](https://user-images.githubusercontent.com/15164008/28130252-ed73d99c-66fb-11e7-9f1b-fad40f1a1fc0.png)
