### ISSUE TITLE
any shortcuts for multi selections?

### ISSUE THREAD

**Issue by goddyZhao** [Microsoft/vscode#3052]
For example, I want to change a variable name which is used in multiple places in one file, so, I want to select all of them by selecting one of them and enter shortcut to select the others as well, just wonder whether by default code has such shortcut? I only find an action named `editor.action.addSelectionToNextFindMatch`, which actually only adds one selection

**Comment by Tyriar** [comment]
I'm not 100% if exactly what you want is supported but something similar can be accomplished using find and replace. Here is what you use on Linux/Windows:

- Select word
- <kbd>ctrl</kbd>+<kbd>h</kbd>
- Type new word
- <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>enter</kbd> to replace all

**Comment by colbyrussell** [comment]
@goddyZhao, does the above comment work for you?  If not, what about Ctrl+F2?

@alexandrudima/@egamma, is there anything special that's going to happen with this?  I would have thought this could be closed pending a confirmation from goddyZhao, but I see this has been assigned.

**Comment by egamma** [comment]
>@alexandrudima/@egamma, is there anything special that's going to happen with this? I would have thought this could be closed pending a confirmation from goddyZhao, but I see this has been assigned.

We assign issues once it has been initially triaged, pls see https://github.com/Microsoft/vscode/wiki/Issue-Tracking

Having said this, when @goddyZhao confirms, then the issue should be closed.

**Comment by alexandrudima** [comment]
@goddyZhao I use `Ctrl+D` a lot for this scenario.

**Comment by goddyZhao** [comment]
Hi, @Tyriar , `ctrl+h` by default is the command for `deleteLeft` when `editorTextFocus` (I am using Mac), I don't think this is the command as you suggested

**Comment by goddyZhao** [comment]
Hi, @alexandrudima , `ctrl+d` by default is the command for `deleteRight`. Did you customize this shortcut?

**Comment by goddyZhao** [comment]
By the way, the feature that I am asking is the `super+ctrl+g` in sublime text: https://gist.github.com/nuxlli/1207014

**Comment by Tyriar** [comment]
@goddyZhao I think it's <kbd>cmd</kbd>+<kbd>d</kbd>/<kbd>h</kbd> for Mac instead of <kbd>ctrl</kbd>.

**Comment by alexandrudima** [comment]
@goddyZhao `Cmd+F2` selects all occurences of the word under cursor.

**Comment by goddyZhao** [comment]
Thanks @alexandrudima , `cmd+f2` works!
