### ISSUE TITLE
Problem collector should shorten buffer if longest problem matcher < buffer size

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#30520]

**Comment by alexr00** [comment]
If I'm understanding correctly, it looks like the buffer is always kept to only be as long as the longest matcher already: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L61
and
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/common/problemCollectors.ts#L134
