### ISSUE TITLE
[coffeescript] syntax highlighting breaks when using embedded JS

### ISSUE THREAD

**Issue by pzuraq** [Microsoft/vscode#30527]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.0.10
vscode-paste-and-indent|Rub|0.0.8
vscode-custom-css|be5|2.3.2
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.1
vscode-elixir|mjm|0.5.0
prettify-json|moh|0.0.3
seti-icons|qin|0.1.3
final-newline|sam|0.3.2
vscode-fileutils|sle|2.6.2
guides|spy|0.8.4
vscode-open-in-github|sys|1.6.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a coffeescript file with embedded JS imports at the top
2. Syntax highlighting is all JS based

![screen shot 2017-07-12 at 8 49 40 am](https://user-images.githubusercontent.com/685518/28126709-1b6fb90a-66df-11e7-8b16-4c9b91ed3089.png)
![screen shot 2017-07-12 at 8 49 44 am](https://user-images.githubusercontent.com/685518/28126708-1b354270-66df-11e7-934c-9640a4f85773.png)

Reproduces without extensions: Yes

**Comment by schallereqo** [comment]
Having the same problem

**Comment by jcaffey** [comment]
Same problem here too.

**Comment by aeschli** [comment]
If you add a semicolon to the import statement it seems to work.

Looks like the problem is with our javascript grammar. The import statement does not end until there is a ':' or the end of the line. For supporting embedded cases like this, it would be better to end with the string literal.

**Comment by aeschli** [comment]
I created https://github.com/Microsoft/TypeScript-TmLanguage/issues/497
