### ISSUE TITLE
PHP: Incorrect syntax highlighting in Class::constant

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#30531]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
codeception-snippets|die|0.0.4
githistory|don|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
AWK|lug|0.0.2
ftp-sync|luk|0.3.3
mads|mir|0.0.5
HTMLHint|mka|0.3.3
vscode-icons|rob|7.10.1
code-spell-checker|str|1.2.1

---

Steps to Reproduce:

1. Set color theme "Dark+ (default dark)"
2. Use the expression `Headers::MCONTENT` anywhere in PHP code
3. See color of `Headers`

Expected result:

- green (IMHO the same color as in definition of class)

Actual result:

- white
![selection_030](https://user-images.githubusercontent.com/12584138/28131191-721e2caa-6739-11e7-8cd7-afcbe31e89ae.png)

It's a **regression** in vscode 1.14. It worked well in 1.13.

Reproduces without extensions: Yes

**Comment by vinsonyung** [comment]
+1 Got the same problem.

**Comment by AshPowell** [comment]
Same.. I think the TM scope to style it is missing

**Comment by roblourens** [comment]
Yes, we are tracking it in https://github.com/Microsoft/vscode-textmate/issues/50
