### ISSUE TITLE
Copy/paste to clipboard not working

### ISSUE THREAD

**Issue by rufusroflpunch** [Microsoft/vscode#30533]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open VS Code
2. Attempt to copy from editor, or paste text into the editor.

Reproduces without extensions: Yes

**Comment by rufusroflpunch** [comment]
Interestingly enough, this only seems to be happening when I launch vscode from within tmux. If I launch from a normal terminal, it behaves correctly. Also, when launched from tmux, the editor freezes when dragging and dropping tabs.

**Comment by josephroque** [comment]
I noticed this same behaviour on macOS Sierra 10.12.4 immediately after updating VSCode. I open VSCode from the dock, and VSCode was relaunched to update, then copy/paste was broken.

Even after quitting and relaunching, no success. Also cannot right click copy/paste.

**Comment by rufusroflpunch** [comment]
This appears to be resolved in 1.14.1. Since @josephroque also had a similar issue, I'll wait and see if his issue is also resolved before I close it.

**Comment by josephroque** [comment]
I'm still unable to copy/paste after the update to 1.14.1.

**Comment by rufusroflpunch** [comment]
I may have spoken too soon. The issue has cropped up again so it appears to be intermittent as well.

**Comment by rebornix** [comment]
@rufusroflpunch 's issue was dup of https://github.com/Microsoft/vscode/issues/24112 . 

@josephroque  it would be helpful if you provide more info, like if invoking copy/paste from command palette or Menu bar works or not, your extension list, etc.

**Comment by josephroque** [comment]
Copy/paste wouldn't work with CMD+C / CMD+V, nor from right clicking copy/paste, nor from the menu bar. CMD+X (didn't try any other methods to cut) removed the text, but would not move it to the clipboard so I couldn't paste it anywhere later, not within or outside of vscode.

I always open vscode from the Dock / application icon.

Extensions:
- Dracula Official
- Python
- Subword Navigation
- vscode-icons

I ended up removing and redownloading vscode so I could continue working with my workflow, and have not re-encountered the problem since.

**Comment by rebornix** [comment]
@josephroque did you launch VSCode from tmux? If so the clipboard API is not avail (Electron issue).

**Comment by josephroque** [comment]
@rebornix No, just launched from the macOS dock.

**Comment by rebornix** [comment]
@josephroque let me know if you run into this again.

**Comment by jldeen** [comment]
@rebornix Bumping this - experiencing the same issue in v 1.16 on MacOS 10.12.6f from within tmux and ZSH Shell.

**Comment by John-Lin** [comment]
Same issue here. VSCode 1.16.1 on MacOS 10.12.6. Using tmux type `code` to open the project then I couldn't use copy/paste shortcut key combination.

**Comment by jjjjeeffff** [comment]
Still an issue for me, launched via `code` outside of tmux.
