### ISSUE TITLE
Keyboard Shortcut to Skip Preview Using Quick Open

### ISSUE THREAD

**Issue by seesemichaelj** [Microsoft/vscode#30530]
I almost always use Quick Open (Ctrl/Command + P) to open my files. Sometimes I want to open multiple files, but they open in Preview by default when using the Quick Open.

I know that there is a user setting that allows you to disable Preview, but 85% of the time I enjoy the Preview.

This is a feature request to add a keyboard shortcut to open the selected file in Quick Open and skip Preview mode. The default behavior on Enter should still open it in Preview mode.

- VSCode Version: 1.14.0
- OS Version: Windows 10/elementary OS

Steps to Reproduce:

1. Open "Quick Open" view using Ctrl (or Command) + P
2. Type in a name
3. Press Enter
4. Verify that files is open in Preview mode

**Comment by Kampfmoehre** [comment]
+1 I would also like to see this feature implemented.

**Comment by chrmarti** [comment]
You could use `Keep Editor` bound to `Ctrl+K Enter` (`Cmd+K Enter` on Mac) on the open editor.

**Comment by seesemichaelj** [comment]
I'll use that in the meantime while this gets implemented. Thanks for the tip!

**Comment by bpasero** [comment]
Yeah I do agree that quick open is missing a way to open an entry in pinned mode, similar to how double clicking in the explorer will pin a file.

**Comment by bpasero** [comment]
Settled on `Alt+Enter`.

**Comment by cleidigh** [comment]
@bpasero 
Great!  I've been wanting this command, have had to use 'Space' then Undo as touch.
Any reason not to add to explorer, file search, git?
If you agree I will do an issue and PR.

**Comment by bpasero** [comment]
@cleidigh let me look into that, it should be done on a layer where every tree benefits from this...

**Comment by bpasero** [comment]
I extracted https://github.com/Microsoft/vscode/issues/39101 for that purpose.
