### ISSUE TITLE
Any plan to have the ability to resize the font size in VSCode?

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#30538]
Just wondering is there any plan to resize the font when you code.  I've been doing a lot of presentation using VSCode and makes it ough not to have a way to (at least) increase the font size.

:)

- VSCode Version: 1.14.0
- VSCode Insider Version: 1.15.0-insider
- OS Version: Windows 10 Build 16237 and Ubuntu 16.04.2

**Comment by Chillee** [comment]
@MaximoTrinidad Set the `editor.fontSize` option.

**Comment by MaximoTrinidad** [comment]
@Chillee ,

That helps!  Thanks.  I forgot to look under the settings JSON file.

But, maybe an option under the pull-down menu to make it more visible and/or a Ctrl-key implementation.

:)

**Comment by smuuf** [comment]
I believe the option to zoom in/out is right there in the *View* menu.

![image](https://user-images.githubusercontent.com/6860713/28139948-90475748-6756-11e7-9733-ee80accbdf89.png)

Albeit this **zooms in the whole window** and does not *just make the font bigger*; I give you that. But that might be actually a good thing - *for doing presentations*?

**Comment by MaximoTrinidad** [comment]
AAAH!  That's it!  Sorry I missed it... Big Time!

Thanks @smuuf!!

I'm closing this issue.  
:)
