### ISSUE TITLE
é character showing up as ? in text files

### ISSUE THREAD

**Issue by danlfarnell** [Microsoft/vscode#3053]
When I open a text file containing the é special character it shows up as a ? with a white diamond around it.

**Comment by alexandrudima** [comment]
@danlfarnell This is most likely a file with a different encoding than UTF8. Please use the switcher at the bottom right to open the file with a different encoding or use the `"files.encoding"` setting to change the default from UTF8 to something else.

**Comment by danlfarnell** [comment]
Awesome thanks.  Dos format works like a charm :)

**Comment by egamma** [comment]
Closing
