### ISSUE TITLE
JavaScript Intellisense Try/Catch Variable Type

### ISSUE THREAD

**Issue by adman2002** [Microsoft/vscode#30534]
- VSCode Version: 1.14.0
- OS Version: Windows 10

Steps to Reproduce:

When writing javascript, variable in try catch block is type of any instead of Error:

![image](https://user-images.githubusercontent.com/29957980/28133364-6504c634-6705-11e7-8658-f91afb8ac71d.png)

**Comment by mjbvz** [comment]
This is by-design since you can throw any type in JS. 

I've opened https://github.com/Microsoft/TypeScript/issues/17142 to track support for annotation the caught exception value's type using jsdocs

**Comment by adman2002** [comment]
Error is the base type, why would it not? I understand you don’t know the actual type until runtime, but the base type can be assumed to have access to the global properties.

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 542-1558
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!

**Comment by mjbvz** [comment]
This is not required.  JavaScript allows you to throw basically anything:

```js
try {
     throw 'abc';
} catch (e) {
    console.log(typeof e)
}
```

**Comment by adman2002** [comment]
I understand that, thanks for opening the thread on this. Hopefully this will be added in a future release, because this feature is there in several other IDE’s

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 542-1558
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!
