### ISSUE TITLE
Intellisense not detecting array type

### ISSUE THREAD

**Issue by benjaminmillhouse** [Microsoft/vscode#30537]
- VSCode Version: 1.14.0

Steps to Reproduce:

1. Add an array as a property of an object and document the @type
2. View Intellisense for the property

<img width="489" alt="screen shot 2017-07-12 at 2 44 36 pm" src="https://user-images.githubusercontent.com/13835886/28134836-3646bd68-6712-11e7-9627-245b251d13d8.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17140
