### ISSUE TITLE
Expose the collapsible state of the tree item

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#30535]
That would allow the TreeDataProvider to preserve the collapsibleState on updates.

**Comment by weinand** [comment]
For me it would even be sufficient to preserve the expand/collapse state that the user has changed. So the TreeItem.collapsibleState would be only used for the initial state.

**Comment by Noderino** [comment]
+1

**Comment by chrisdias** [comment]
This would let me run an expensive refresh operation in the docker extension only when the parent node is expanded. right now it runs even if the parent node is collapsed because I can't see the state  of the node.

**Comment by eamodio** [comment]
Same for me with GitLens. Though ideally I'd want an state change event so that I could hook/unhook other handlers (file system watchers) only if needed.

**Comment by hbenl** [comment]
+1
Right now it is impossible to preserve the visible state on updates (which can be very annoying for the user). Even when I'm reusing the old `TreeItem`s, their state is replaced with the _initial_ `collapsibleState`.

**Comment by weinand** [comment]
I'm bumping the severity of this since it makes the tree very difficult to use for users.

**Comment by GordonSmith** [comment]
@weinand If you also made label + collapsibleState refresh their UI when they are written to, then it would allow a simple way to refresh a single node. 

Or support: ```tree._onDidChangeTreeData.fire(T);``` to trigger a refresh of single node?

**Comment by sandy081** [comment]
As I do not see any scenarios to support this request after other fixes/enhancements done to custom view, I am inclined to close this.

If there is still need of it, please reopen it with the supporting use cases. 

Thanks.

**Comment by eamodio** [comment]
I would vote to re-open this. GitLens has certain nodes that when expanded, start file watchers and other event hooks, but currently I have no way to undo them if the node is collapsed. These leads to wasted performance, battery, etc

**Comment by chrisdias** [comment]
The Docker extension has `Images` and `Containers` nodes. When expanded, I poll Docker for status updates (start, stopped, creation date/time). This is expensive and when the `Images` or `Containers` nodes are collapsed, I would like to get an event and be able to test the state so I can stop polling.

**Comment by sandy081** [comment]
Added following events in the `Treeview`

```typescript
/**
 * Event that is fired when an element is expanded
 */
readonly onDidExpandElement: Event<T>;

/**
 * Event that is fired when an element is collapsed
 */
readonly onDidCollapseElement: Event<T>;
```

**Comment by sandy081** [comment]
All, please note that there is a slight change done to the events

```typescript

export interface TreeViewExpansionEvent<T> {

	/**
	 * Element that is expanded or collapsed.
	 */
	element: T;

}

/**
 * Event that is fired when an element is expanded
 */
readonly onDidExpandElement: Event<TreeViewExpansionEvent<T>>;

/**
 * Event that is fired when an element is collapsed
 */
readonly onDidCollapseElement: Event<TreeViewExpansionEvent<T>>;
```
