### ISSUE TITLE
Context menu for unsaved buffers not appearing after selecting one buffer for compare

### ISSUE THREAD

**Issue by teqonix** [Microsoft/vscode#30539]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3

---

Steps to Reproduce:

1.  Launch VS Code
2.  Create a new file (File --> New)
3.  Write some example text in the "Untitled-1" buffer (e.g. "Test123")
![image](https://user-images.githubusercontent.com/30127452/28136565-668c982c-6707-11e7-9c69-c61624d162ee.png)

4.  Create a second new file (File --> New)
5.  Write some example text (that differs from your example text in step 4) in the "Untitled-2" buffer (e.g. "Test234")
![image](https://user-images.githubusercontent.com/30127452/28136599-821fe72e-6707-11e7-8afa-d61aa7de0ff1.png)

6.  Open the context menu for the "Untitled-1" buffer (Right Click on "Untitled-1")

7.  Click "Select for Compare"
![image](https://user-images.githubusercontent.com/30127452/28136624-9974979e-6707-11e7-863d-01d09432295b.png)

8.  Attempt to open the context menu for "Untitled-2" (Right click on "Untitled-2").  The context menu will fail to appear for any unmodified buffers in the "Open Editor" menu pane.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269
