### ISSUE TITLE
PHP regex syntax coloring breaks on empty square brackets

### ISSUE THREAD

**Issue by mister-glass** [Microsoft/vscode#30548]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open a php file
2. Type somewhere: "/[]/"

Here's a GIF for a better idea:
![php-regex](https://user-images.githubusercontent.com/4302588/28140049-63e542ce-675f-11e7-8653-2c8b92f4a844.gif)

Reproduces without extensions: **Yes**

**Comment by roblourens** [comment]
Filed upstream at https://github.com/atom/language-php/issues/244
