### ISSUE TITLE
Format HTML file which contains JS/JSX

### ISSUE THREAD

**Issue by giorgim** [Microsoft/vscode#30544]
After trying to format (Shift + Alt + F) HTML file which contains JS/JSX, this is the result I got:

![screenshot_1](https://user-images.githubusercontent.com/26545183/28138484-0194a788-6762-11e7-8e08-58a963963eb6.png)

What did I do wrong?
You can see it especially failed on formatting the JS class. Put all in one line etc.

**Comment by aeschli** [comment]
The formatter we use (jsbeautifier.org) does not support jsx inside script tags. Please file an issue against http://jsbeautifier.org/
