### ISSUE TITLE
Auto import for React components (Feature request).

### ISSUE THREAD

**Issue by giorgim** [Microsoft/vscode#30545]
Would be nice if you can add feature of "Auto import for React components".
When I type component name in JSX, then VS Code should be able to allow me to auto import the component. 

Web storm does it:  https://blog.jetbrains.com/webstorm/2017/02/webstorm-2017-1-eap-171-3566/
(top of the article).
 ![auto-import-react](https://user-images.githubusercontent.com/26545183/28138866-4d97a6ca-6763-11e7-89af-0d4cce642918.gif)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17145
