### ISSUE TITLE
PHP auto indent when pressing tab on new line

### ISSUE THREAD

**Issue by mister-glass** [Microsoft/vscode#30547]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Go to a nested block of code and press enter a couple of times
2. Go to the above line that is empty and press TAB
It doesn't auto add the necessary indentation anymore, for the current nesting.

I have made 2 GIFS to demonstrate this, by comparing behavior from VSCode version 1.13 with VSCode version 1.14.
Also, this seems to be reproducible only in PHP, In Javascript it works as expected.
Indent character is also not important, as I have tested with both tabs and spaces.
As a side-note, I need to mention that once you get used with the editor auto adding necessary indentation, it's very difficult and very annoying adjusting otherwise, until this is fixed :(

**VSCode v1.14**
![php-indent-bug](https://user-images.githubusercontent.com/4302588/28139649-b4fb1fdc-675d-11e7-9a55-d9d3ec054af1.gif)

**VSCode v1.13**
![php-indent-good](https://user-images.githubusercontent.com/4302588/28139704-e1fc0e24-675d-11e7-9acf-f04b46075ccc.gif)

Reproduces without extensions: **Yes**

**Comment by smuuf** [comment]
I noticed this issue when editing *SASS* files today - after the update. So this might not be just "a PHP thing".
