### ISSUE TITLE
Cannot disable extensions when launching with --disable-extensions

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#30546]
- VSCode Version: 1.14.0
- OS Version: All

With the recent issue of the Ruby snippets extension triggering an endless loop in the snippet code it would have been helpful if users could start with `--disable-extensions` and then permanently disable individual extensions through the extensions viewlet.

The Disable actions do not seem to work when launched with `--disable-extensions`, uninstalling extensions was the only option to try and find the extension triggering the problem.

**Comment by sandy081** [comment]
There is a new blame extension feature to help you in these cases.
