### ISSUE TITLE
'Change Keybinding' doesn't work everytime.

### ISSUE THREAD

**Issue by james2mid** [Microsoft/vscode#30542]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0

When hitting enter quickly after typing a keybinding, the keybinding is not always set.

**Comment by james2mid** [comment]
Update: Actually only occurs when the action doesn't already have a keybinding attached to it. To make it work, you need to 'Reset Keybinding' and then change it.

**Comment by sandy081** [comment]
@james2mid It works for me for all (even for those with keybinding attached). Are there more precise steps I would follow?
