### ISSUE TITLE
Anonymous class missing references / missing in implementations

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#30541]
- VSCode Version: Code - Insiders 1.15.0-insider (74f5073c54f1139d2fb0eccb251cae5ed6e8215b, 2017-07-12T05:07:15.561Z)
- OS Version: Darwin x64 16.6.0
- Extensions: Many

```
interface Test {
    bar();
}

const intstance: Test = new class {
    bar() {}
}

intstance.bar();
```

Test.bar() does not show an implementation and the implementation does not show a reference:
![image](https://user-images.githubusercontent.com/9205389/28137232-66daed7a-6701-11e7-9e10-1764214d92c8.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17139
