### ISSUE TITLE
No longer able to drag files between folders in the side bar

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#30549]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Drag a file in the sidebar from one folder to another
2. Drop. Nothing happens.

Reproduces without extensions: Yes

Note that I am not using multi-root workspaces in this case. I have only one root folder.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30462
