### ISSUE TITLE
After "disable all extensions" and clicking reload, all extensions vanish until Code is restarted

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#30551]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Go to the extensions panel
2. Disable all extensions from the `...` menu
3. Click one of the "reload" buttons

Extensions are all gone and cannot be re-enabled without restarting VSCode.

**Comment by sandy081** [comment]
@axefrog Can you please see if there are any errors in the console. You can open the development tools using the command `Developer: Toggle Development Tools`.

Also try starting VS Code with verbose mode from command prompt `$code --verbose` and see if there is any info
