### ISSUE TITLE
Have Windows support for the new launcher script

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3055]
ping @Tyriar

**Comment by Tyriar** [comment]
This was going to be part of https://github.com/Microsoft/vscode/issues/1704 - did you want me to handle this?

**Comment by joaomoreno** [comment]
Nah, this issue is just for the Command Prompt and Powershell. I'll take it.

**Comment by Tyriar** [comment]
Not bash shells? Got it.

**Comment by joaomoreno** [comment]
:+1:

**Comment by joaomoreno** [comment]
Verification by running `code-alpha -v`, for example. It should print out Code's version.

**Comment by joaomoreno** [comment]
@Tyriar I decided to push this last minute change, it would be a shame not to get it. Plus, fixing #1704 led me to the solution. :+1:
