### ISSUE TITLE
Folding is susceptible to indentation

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30558]
Folding doesn't work properly in this case:

```ts
  if ( !foo ) {
    const tmpl = `
{
  "foo": "bar"
}
`;
  }
```
If I try to fold the `if` block I get:

```ts
  if ( !foo ) {...
{
  "foo": "bar"
}
`;
  }
```

While it should be:

```ts
  if ( !foo ) {...
  }
```

I'd like to point out that this use case may happen pretty frequently, since that when using JS's template strings it will add extra spaces at the beginning of each line if the indentation isn't removed.

**Comment by aeschli** [comment]
The current folding only depends on indentation and is not language aware.
The request for language aware folding is #3422
