### ISSUE TITLE
VS Code freezes on launch

### ISSUE THREAD

**Issue by izzydoesit** [Microsoft/vscode#30553]
Pls help.  VS code freezes on launch.  Cannot click on anything in window.  Totally unresponsive. Works fine with extensions disabled (command below).  

- VSCode Version: latest stable 1.14.0
- OS Version: OSX 10.12.5

Steps to Reproduce:

1. Download latest version of VS Code from code.visualstudio.com
2. open program with 'code' command in terminal or clicking on icon in dock. Watch it freeze instantly upon opening.

Reproduces without extensions: Yes/No   NO

**Comment by HaominZhang** [comment]
- VSCode Version: latest stable 1.14.0
- OS Version: OSX 10.11.6

I have exactly the same problem

**Comment by mjbvz** [comment]
Possibly #30407

Do you have the `atefth.ruby-on-rails-snippets` extension installed? If so, [try uninstalling it](https://github.com/Microsoft/vscode/issues/30407#issuecomment-314642537)

**Comment by HaominZhang** [comment]
@mjbvz That's the problem. Thanks for pointing it out.

**Comment by chrmarti** [comment]
#30407

**Comment by Serg-zefir** [comment]
ubuntu 16.04  I have exactly the same problem VSCode Version: latest stable 1.14.0

**Comment by chrmarti** [comment]
@Serg-zefir Make sure you're running the latest release 1.14.2.
