### ISSUE TITLE
Problem matchers can't match correctlly if output line is longer than width of Integrated Terminal

### ISSUE THREAD

**Issue by MasaakiSonoda** [Microsoft/vscode#30550]
- VSCode Version: 1.14.0
- OS Version: Windows7 and 8.1
- Extensions: C/C++ 0.12.0

Steps to Reproduce:

1. Narrow down the width of Integrated Terminal.
2. Run build task with problem matchers.

VSCode 1.14.0 with tasks.json 2.0.0 executes tasks in Integrated Terminal and compiler's outputs are wrapped to match with terminal width. This causes issue on problem matchers.

Here is example.
![image](https://user-images.githubusercontent.com/30130109/28141491-9f9a5974-6711-11e7-8c24-953938a7efe1.png)
![image](https://user-images.githubusercontent.com/30130109/28141497-a72e140a-6711-11e7-9245-f2e425f70e60.png)

![image](https://user-images.githubusercontent.com/30130109/28141504-ae865866-6711-11e7-9963-ba5939df0448.png)
![image](https://user-images.githubusercontent.com/30130109/28141507-b2055e2e-6711-11e7-8271-8ff855616e28.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@dbaeumer should we close this in favor of https://github.com/Microsoft/vscode/issues/29840?

**Comment by dbaeumer** [comment]
@Tyriar I will keep it open so that I can still track it.

**Comment by dbaeumer** [comment]
Dups #32042
