### ISSUE TITLE
Missing setting for adding a border below the titlebar

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30555]
There are settings under `workbench.colorCustomizations` for adding a border between all the main parts of the editor, except for the titlebar.

I think there should be a `titleBar.border` setting for this, depending on the color scheme one uses it will look pretty ugly without a it.

Of course this only applies for `"window.titleBarStyle": "native"`.

**Comment by bpasero** [comment]
With our 1.14 release we added `titleBar.border` (macOS only).

**Comment by fabiospampinato** [comment]
There's no mention of it in the [docs](https://code.visualstudio.com/docs/getstarted/theme-color-reference). I'm using v1.14 right now and there's no autocompletion for it and setting it anyway doesn't work.

Did you mean 1.15 maybe?
