### ISSUE TITLE
Annoying "[Unsupported]" suffix in the titlebar

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30556]
The "[Unsupported]" suffix in the titlebar is pretty annoying.

In my case it's there because I use the [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension, just for removing some stuff I don't use via CSS.

I understand why it's there, but I'd like to have a way to remove it.

Perhaps a `window.titleShowUnsupported` setting?
Perhaps add it via a `${unsupported}` placeholder under the `window.title` setting?

**Comment by bpasero** [comment]
As we do not support extensions that patch our bits on disk, we would not want to push a change that reverts this UI annoyance. Please uninstall this extension.

**Comment by fabiospampinato** [comment]
I think I should be able to run any extension I choose, whether you "support" it or not, without having VSC explicitly behaving differently because of it.

I wish VSC was more hackable, like Atom. The ability to load a custom CSS is pretty important to me. 

Btw, if anybody else finds it annoying I made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-no-unsupported) for removing it.

**Comment by Kaffiend** [comment]
I removed the extension and the preference and its still there..

**Comment by Kaffiend** [comment]
had to reinstall.

**Comment by peteplays** [comment]
I agree 💯  with @fabiospampinato.  If vscode does not want thier `bits` messed with, they **need** to support more robust custom theming options.  I am using `Custom CSS and JS Loader` as a temp workaround with the hopes that an option like this will be rolled out as part of vscode 👈  @bpasero
