### ISSUE TITLE
New tasks don't work in WSL

### ISSUE THREAD

**Issue by JanPokorny** [Microsoft/vscode#30552]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

It seems that when using the Bash on Windows as the VSC's shell, commands ran through tasks act as if they received no arguments (npm showing just the default help, etc.).

Steps to Reproduce:

1. Have `"terminal.external.windowsExec": "C:\\Windows\\sysnative\\bash.exe",  "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"` in your settings
2. Open empty folder
3. `Tasks -> Configure Tasks -> Others` (this will add the default `echo Hello` task)
4. Run the `echo` task, which will **not** actually echo "Hello"
5. Editing the task command to `echo Hello > test.txt` and running the task will create the `test.txt` file, but the file will contain just two newlines

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@JanPokorny  this is a problem of using bash. The corresponding issue is tracked here: #28036, #30417 and here https://github.com/Microsoft/vscode/issues/30592

**Comment by JanPokorny** [comment]
This may be related to how weird the bash.exe actually acts. Running (in cmd) `bash -c 'command'` does **not** run `command` in bash, but rather runs the whole `bash -c ...` in bash -- performing substitutions etc. in process. 
Compare running `bash -c 'PATH=/bin/something; echo $PATH'` and `bash -c "PATH=/bin/something; echo $PATH"` (single/double quotes)

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
