### ISSUE TITLE
Problem Matcher dynamic fileLocation setting

### ISSUE THREAD

**Issue by antmerlino** [Microsoft/vscode#30559]
I have the following output from my build:

make[1]: Entering directory '/vagrant/nuttx/sched'
make[1]: 'libsched.a' is up to date.
make[1]: Leaving directory '/vagrant/nuttx/sched'
make[1]: Entering directory '/vagrant/nuttx/drivers'
CC:  wireless/ieee802154/mrf24j40/mrf24j40_regops.c
wireless/ieee802154/mrf24j40/mrf24j40_regops.c: In function 'mrf24j40_getreg':
wireless/ieee802154/mrf24j40/mrf24j40_regops.c:130:2: error: 'dev' undeclared (first use in this function)

The issue is that the path needs to be /nuttx/drivers/wireless/ieee802154/mrf24j40/mrf24j40_regops.c

As you can see, that means when the "Entering directory" line is printed, I need to somehow change the path mapping so that the path on the line with the error/warning is linked.

I realize I could fix it for this one case using the fileLocation setting, but that won't work if it's any of the other directories in the project.  Regex could solve it if there were some clever way of combining them.

I am hoping someone here has a clever solution in mind for this, or if maybe there is an easy-enough workaround.  I'd be awesome to be able to get the problem matcher working with this setup!

**Comment by dbaeumer** [comment]
Dups #11663.
