### ISSUE TITLE
macOS Sierra 10.12.5 Update to 1.14.0 and crash

### ISSUE THREAD

**Issue by azhao1981** [Microsoft/vscode#30560]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. update to 1.14.0 (auto)
2. click restart vscode
3. code can't response anything (click/cmd+q/cmd+p....)
4. Os show me app not response and waitting or quit ..

Reproduces without extensions: Yes/No

YES

![error images](https://github.com/azhao1981/my-notes/raw/master/images/vccod_error.jpeg)

**Comment by azhao1981** [comment]
Seem same issue #30553

I remove atefth.ruby-on-rails-snippets-0.0.1 and it work!

**Comment by chrmarti** [comment]
#30407
