### ISSUE TITLE
highlight cannot work on some case

### ISSUE THREAD

**Issue by jeffy-g** [Microsoft/vscode#30561]
- VSCode Version: 1.14
- OS Version: windows 7 SP1

Steps to Reproduce:

1.  paste following code on .ts or .js file.

``` javascript
    let ZX = {
        "(": "()",
        "[": "[]",
        "{": "{}",
        "'": "''",
        '"': '""',
        "`": "``"
    }

    // The highlight after this will be not work.
    /**
     * ... @see https://github.com/Microsoft/vscode/issues/new
     */
    function fail(): void {
        ; // ...
    }
```
2. then, check the code highlight.

Reproduces without extensions: No

these not occurrence on `1.13.1`

**Comment by mjbvz** [comment]
Can you share a sceenshot. Here's what I see:

<img width="620" alt="screen shot 2017-07-12 at 9 49 05 pm" src="https://user-images.githubusercontent.com/12821956/28150845-0bde179e-674c-11e7-9d0b-910b47277ecd.png">

Looks correct

**Comment by jeffy-g** [comment]
oh..., in my environment it will be as follows:

![fail](https://user-images.githubusercontent.com/26692481/28156094-388ac152-67ec-11e7-9f62-68f493df7748.png)

on `1.14.0`

**Comment by jeffy-g** [comment]
I have not examined it in detail,
maybe the settings of the previous version etc may be involved...

**Comment by jeffy-g** [comment]
The same problem also occurred in version 1.15.0-insider.

![fail2](https://user-images.githubusercontent.com/26692481/28156562-40704746-67ee-11e7-9df3-b30a4e7ea55b.png)

this is the state where the extensions not installed,
and it is also in the state where the user setting file of vscode is not edit.

**Comment by jeffy-g** [comment]
by the way, this is the result in `1.13.1`:

![ok](https://user-images.githubusercontent.com/26692481/28156986-e829ff4e-67ef-11e7-98b0-889e79e3ae2a.png)

**Comment by jeffy-g** [comment]
tried a little more verification.
`1.14.0`

![sample-0](https://user-images.githubusercontent.com/26692481/28158131-b7a79ee0-67f3-11e7-8b5b-b8b9cc527df4.png)

![sample-1](https://user-images.githubusercontent.com/26692481/28158134-bc088fb2-67f3-11e7-9310-d53035693905.png)

**Comment by mjbvz** [comment]
Thanks. Confirmed on 1.14. This is already fixed in insiders: https://code.visualstudio.com/insiders

**Comment by jeffy-g** [comment]
It was certainly fixed :-)
gj :+1:
