### ISSUE TITLE
V1.14.0 Does not work correctly (MacOS Sierra)

### ISSUE THREAD

**Issue by juanarbol** [Microsoft/vscode#30565]
VS code must be re-opened a lot of times, it just freezes when is opened.

<img width="475" alt="screen shot 2017-07-12 at 11 14 34 pm" src="https://user-images.githubusercontent.com/17013303/28150173-83a34806-6758-11e7-8ebd-d98944a9ae59.png">

**Comment by CaliosD** [comment]
I've got this problem, too. How can I roll back to the version before?

**Comment by juanarbol** [comment]
This is a duplicate of #30407 , and the answer of @alexkrolick works for me!

**Comment by CaliosD** [comment]
@juanarbol Thanks! I've tried and it works! Shall we close this issue then?
