### ISSUE TITLE
askpass.sh not executable

### ISSUE THREAD

**Issue by cenomla** [Microsoft/vscode#30566]
After the update to 1.14.0 the file: 
`/opt/visual-studio-code/resources/app/extensions/git/out/askpass.sh` is not marked as executable and therefore when trying to sync a git repository it fails. Had to manually change permissions to fix. I am using Arch Linux.

**Comment by tuxedojoe** [comment]
Seems something else is fishy here than just the permissions. However,
I got it working by running the commands one by one found in askpass.sh (see below). Now vscode asks for the password again.

VSCODE_GIT_ASKPASS_PIPE=`mktemp`

VSCODE_GIT_ASKPASS_PIPE="$VSCODE_GIT_ASKPASS_PIPE" "$VSCODE_GIT_ASKPASS_NODE" "$VSCODE_GIT_ASKPASS_MAIN" $*

cat $VSCODE_GIT_ASKPASS_PIPE

rm $VSCODE_GIT_ASKPASS_PIPE

**Comment by joaomoreno** [comment]
#30437
