### ISSUE TITLE
Zen mode remove top bar

### ISSUE THREAD

**Issue by igor-sky** [Microsoft/vscode#30567]
Please add option to remove top bar in Zen mode. 
Atom & Webstorm have a clear screen in Zen mode without any distraction on top.

<img width="1440" alt="screen shot 2017-07-12 at 9 22 25 pm" src="https://user-images.githubusercontent.com/29221620/28150393-230e196c-6749-11e7-9f20-f8d4f43133be.png">

**Comment by polygrimm** [comment]
Yeah, its not zen mode when there are distractions

**Comment by isidorn** [comment]
Closing as a duplicate of https://github.com/Microsoft/vscode/issues/44593 since there I skethced out the implementation which should be done this milestone. Thanks
