### ISSUE TITLE
Unable to Sync with Git repo after latest update

### ISSUE THREAD

**Issue by bhargavkonkathi** [Microsoft/vscode#30569]
- VSCode Version:- 1.14.0
- Commit b8cd5b9556d8b70ea560d35b903422363f6c5c40
- Date 2017-07-10T20:36:40.018Z
- Shell 1.6.6
- Renderer 56.0.2924.87
- Node 7.4.0

- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Unable to sync with git repository.
2. fatal: cannot exec '/usr/share/code/resources/app/extensions/git/out/askpass.sh': Permission denied
fatal: could not read Password for 'https://xxxx@bitbucket.org': No such device or address
3. Not asking for any authentication.
4. Working properly from shell.

Reproduces without extensions: Yes/No

**Comment by niccolomeloni** [comment]
Same problem here!

**Comment by victorschinaider** [comment]
Same problem.

**Comment by rahulkumar26** [comment]
try git pull from Terminal/CMD (not vscode one), and enter your credentials (if required). Then, try git operation from VS code.

**Comment by niccolomeloni** [comment]
From terminal it works. However VS code still has some problem when trying to access `/usr/share/code/resources/app/extensions/git/out/askpass.sh` file.

**Comment by jlongshore** [comment]
Same Issue here too on OSX 10.12.5

From the GIT output window:
```
git pull
fatal: cannot exec '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/out/askpass.sh': Permission denied
fatal: could not read Password for 'https://xxxxxxxx@bitbucket.org': Device not configured
```

**Comment by joaomoreno** [comment]
#30437
