### ISSUE TITLE
feature request: possibility to disable auto update for certain extensions

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#30579]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5

The autoupdate feature for extensions is a huge plus! I just have a minor issue with it. When you develop an extension, and the package.json version does not exactly match (or semver check?) it downloads the "newer" version. Despite the fact that I'm on my latest development branch locally.

![fikqqvd4](https://user-images.githubusercontent.com/1067213/28152957-5501f75e-67a3-11e7-9b1b-893f91cce47d.png)

It would be a really cool feature to disable auto update (maybe with a setting or a file or whatever) for that specific extension locally, since it's compiled on my machine and loaded via a symbolic link.

An annoying workaround would be to fill in the package.json version every time. But since someone may use semantic releasing (like I do), that's kind of a downer.

Cheers!

**Comment by sandy081** [comment]
@buehler How come the development version is lesser than the published one. I assume it should be at least same or greater?

**Comment by buehler** [comment]
@sandy081 this can happen when you use `semantic-release` for tagging and releasing your software. (https://github.com/semantic-release/semantic-release)

So you don't set your package.json version and let it be set by semantic release

**Comment by diogosalazar** [comment]
Please allow for disabling / blacklisting auto-update for certain extensions.

I have a key for a paid (pro) version of an extension that is valid only up to a specific version of that extension. If I install an earlier version that works with my key vscode auto-updates it to the latest version unless I disable auto-updates globally -- problem is that I would like to auto-update all other extensions.

Thanks.

**Comment by therealpeterhua** [comment]
+1 to this. Some extensions are pretty low-traffic / abandoned by author and I've patched in my own fixes, would like some guarantee of steady-state

**Comment by sandy081** [comment]
Auto updates are disabled if you install a specific version (not latest) which is now supported. Let me know if that fixes your problems?

**Comment by philippludwig** [comment]
> Auto updates are disabled if you install a specific version (not latest) which is now supported. 

How exactly do you do that?

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/51469413-9a5ff280-1d71-11e9-9b15-2cddd8b90938.png)
