### ISSUE TITLE
Add setting to show cross project find results in a tab like Sublime

### ISSUE THREAD

**Issue by esprehn** [Microsoft/vscode#30575]
VSCode shows the find results squished into a narrow sidebar which makes them very hard to use if your window and sidebar isn't huge. You also can't have the find results and the file view at the same time, since the actions sidebar only lets you see one thing at a time.

Instead have a mode where the find results are a regular tab. Then you could tear it off, or toggle back and forth from code windows while the file view is still open and also have lots more room to see the find results. Also provide control over the number of context lines shown there.

**Comment by roblourens** [comment]
Popular request :)

#23931
