### ISSUE TITLE
"The Window is no Longer responding"

### ISSUE THREAD

**Issue by ankita199** [Microsoft/vscode#30576]
I had taken a new update of vsCode and after that i am not able to do anything in vs coe.. AfterSometime i open editor it showing "The Window is not Longer responding" and error message like "You can reopen or close the window or keep waiting".

I am using windows 8 os and vs code latest version

![error](https://user-images.githubusercontent.com/9448677/28152382-bcd2c024-67bd-11e7-9700-8b376087d0af.png)

**Comment by rdeneau** [comment]
I've got the same issue, working on a "small" Angular2 project, on Windows 10.

**Comment by jrieken** [comment]
Please do the following

F1 > Toggle Developer Tools > Select Profile tab
Select Record JavaScript CPU Profile, select Start
Now do whatever you did you make it hang, appear as slow, show the not responsive warning
Stop recording, Save the profile, and attach it here.
Also try to reproduce without extensions enabled (start from the command line via code --disableExtensions) Thanks.

**Comment by Jcool1979** [comment]
I have the same issue on Mac Sierra, you can't click on anywhere on the canvas because it froze and you get the pop up, I uninstalled and reinstalled it same result, anyone please knows how to fix this problem?????

**Comment by jrieken** [comment]
@Jcool1979 Did you try this https://github.com/Microsoft/vscode/issues/30576#issuecomment-314995204?
