### ISSUE TITLE
Command to open specified file from opened folder for editing

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [Microsoft/vscode#3057]
While working with large flat folders it would be nice to be able to type the first few letters of a filename and see a list of files that match for quick opening. Maybe a `File: Edit File...` command that displays a list of files that match the typed name, similar to <kbd>CTRL</kbd>-<kbd>Tab</kbd> maybe?

Scrolling to the file can take awhile and feels clunky and if the folder structure is large enough it is easy to fly right past the file you are looking for.

**Comment by alexandrudima** [comment]
@ZombieProtectionAgency would `Ctrl+P` work?

**Comment by ZombieProtectionAgency** [comment]
Oh... Yes. That was what I had in mind, sorry!

**Comment by colbyrussell** [comment]
Close this?

**Comment by egamma** [comment]
@ghost thanks!

 Closing
