### ISSUE TITLE
Running the contributed command:'extension.node-debug.startSession' failed.

### ISSUE THREAD

**Issue by mpvpraveen** [Microsoft/vscode#30574]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@mpvpraveen Which VS Code version? Which OS?
Do you have node.js installed?
Which version of node.js?

**Comment by weinand** [comment]
I suspect that you have no node.js installed on your system.
In this case our version probing for node was crashing the 'startSession' command.

**Comment by weinand** [comment]
If no node.js is installed, VS Code now shows the following error message if F5 is pressed:

![2017-07-21_11-39-15](https://user-images.githubusercontent.com/1898161/28458259-6f182ca0-6e09-11e7-8c30-542e00527c7a.png)
