### ISSUE TITLE
Latest update get hang on startup, I'm unble to use it.

### ISSUE THREAD

**Issue by kasim1011** [Microsoft/vscode#30571]
- VSCode Version: 1.14
- OS Version: Ubuntu 16.04 64-bit

Steps to Reproduce:

1. VS code get hang on startup.

I've Launch with `code --disable-extensions` to check. It works fine.

My Extension List.
- C/C++ 0.12.0 (Microsoft)
- Cordova Tools 1.2.7 (Visual Studio Mobile Tools)
- Java Debugger 0.1.2 (Don Jayamanne)
- Odoo Snippets 0.3.8 (jeffery)
- Python 0.6.7 (Don Jayamanne)
- vscode-icons 7.10.1 (Roberto Huertas)

**Comment by mjbvz** [comment]
Sounds like a duplicate of #30407

Please try uninstalling the snippets extension to see if that fixes the issue. We are preparing a 1.14.1 recovery build with a fix

**Comment by kasim1011** [comment]
@mjbvz I've remove all extension except following.

- C/C++ 0.12.0 (Microsoft)
- Java Debugger 0.1.2 (Don Jayamanne)
- Python 0.6.7 (Don Jayamanne)

Now, VS Code runs like charm.
