### ISSUE TITLE
Add it to Windows Store

### ISSUE THREAD

**Issue by luksireiku** [Microsoft/vscode#30577]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Just add it to the Windows Store, it would be easier to install and update it.

Steps to Reproduce:

1.
2.

**Comment by wangweixuan** [comment]
This is being tracked in #10759.
Please follow the discussion there.

**Comment by luksireiku** [comment]
Should I close this for duplicate or what?
