### ISSUE TITLE
Tasks: gulp tasks are not being loaded after update to 1.14

### ISSUE THREAD

**Issue by sethstha** [Microsoft/vscode#30570]
- VSCode Version: 1.14
- OS Version: Windows 10

After updating to VSCode 1.14 yesterday. Gulp tasks are not being loaded.

I got this error on output 
`Auto detecting gulp failed with error: Error: Command failed: node_modules\.bin\gulp.cmd --tasks-simple --no-color`

So I have gone to root directory of my project and hit `gulp --tasks-simple`. I got this error

```
[10:32:52] Task never defined: default
[10:32:52] To list available tasks, try running: gulp --tasks

```
But, hitting `gulp --tasks`, tasks are being listed. 

It was working fine before the update. Is something there I am missing

Thanks

**Comment by dbaeumer** [comment]
@sethstha can you share a project / setup that demonstrates this. I am not able to reproduce this.

In 1.14 we changed the way how tasks are auto detected.

**Comment by sethstha** [comment]
Hi @dbaeumer 

Here is the repo I made with my package.json and gulpfile.js. You may try running `npm-install` and trying loading tasks on vscode.

https://github.com/sethstha/gulp-task-vscode

**Comment by dbaeumer** [comment]
@sethstha I can partly reproduce this however I see a different error. Which version of the gulp cli do you have installed

**Comment by sethstha** [comment]
Hi, @dbaeumer 

Here are the infomation
OS: Windows 10
Gulp-cli: 1.3.0
Gulp: 4.0

I am not sure but this should be a problem with using gulp 4.0. However, it was working fine before.

Thanks

**Comment by dbaeumer** [comment]
I did some more investigation and even on the command line gulp doesn't list any tasks for your example. Executing `.\node_modules\.bin\gulp.cmd --tasks --gulpfile .\gulpfile.js` prints not tasks at all. Are you seeing the same ?

**Comment by sethstha** [comment]
Yes, same thing here. I see nothing. No tasks are being listed.

**Comment by sethstha** [comment]
Found a solution.

Issue was with the installation of 2 gulp 

If you look at `package.json`

```
 "gulp": "git+https://git@github.com/gulpjs/gulp.git#4.0",
 "gulp-4.0.build": "^4.0.0-build.a271520",
```

Removed the second one and it works fine.

**Comment by dbaeumer** [comment]
Great to hear that you got it working.
