### ISSUE TITLE
No progress visible if message length exceeds space

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#30581]
The Java extension uses the `withProgress` API to run the potentially very long running 'Start Java Server' operation. As library need to be fetched this can last several minutes.

Problem is that the progress indication seems to go on and off
- If the message does not fit on the status line, nothing is shown, not even the turning wheel
- It appears that after a time out and no change the message also disappears (I'm not sure about this one, maybe it's also just that message gets longer)

It would be good if the message could be cropped and that the turning wheel stays visible so that the user knows that the initialization is still ongoing.

**Comment by roblourens** [comment]
![aug-03-2017 17-53-10](https://user-images.githubusercontent.com/323878/28949888-ac3d38da-7874-11e7-83d4-98fbd0c2c2ae.gif)

It wraps but it could still technically be lost, especially if the status bar is already full.
