### ISSUE TITLE
`OPEN EDITORS` pop up menu(mouse right click) is not working after `Select For Compare` is triggered

### ISSUE THREAD

**Issue by Parannarae** [Microsoft/vscode#30587]
- VSCode Version: 1.14.0
- OS Version: macOS Sierra 10.12.5(16F73)

Steps to Reproduce:

1. Open few files so there exists at least two files on `OPEN EDITORS` menu
2. Select any file and right click to choose `Select For Compare`
3. Try to right click any file on `OPEN EDITORS` menu but the pop up menu is not shown

Reproduces without extensions: Yes

**Comment by MFathirIrhas** [comment]
Same here. 
VS Code Version: 1.14.0
OS : Windows 7
Can't right click on files inside 'OPEN EDITORS' section(sidebar) **after** right clicking on a file before and choose _Select For Compare_

**Comment by Endlessmist** [comment]
Same problem after update to version 1.14.0, can't compare files, because right click menu won't show any more after I choose first file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269
