### ISSUE TITLE
Git diff view is wrong.

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode#30582]
- VSCode Version: 1.14.0
- OS Version: macOS 10.12.5

This is what I have in VSCode:

<img width="943" alt="screen shot 2017-07-13 at 3 09 05 pm" src="https://user-images.githubusercontent.com/1091472/28154582-4212bb44-67dd-11e7-9e24-2553d96a5846.png">

And this is in SourceTree:

<img width="1130" alt="screen shot 2017-07-13 at 3 09 59 pm" src="https://user-images.githubusercontent.com/1091472/28154629-64577ab4-67dd-11e7-8dc6-87cabc62e190.png">

What I got in VSCode is wrong.

I reported this problem when running 1.11.2 in https://github.com/Microsoft/vscode/issues/25274. Now seems it's back.

**Comment by chrmarti** [comment]
Is this with Git as SCM provider?

**Comment by joaomoreno** [comment]
Can you scroll all the way down? I believe Code is showing you those changes further down.
