### ISSUE TITLE
Choose one option from dropdown make duplication

### ISSUE THREAD

**Issue by sagarvd01** [Microsoft/vscode#30586]
In angular development while importing components, if we choose one component from the drop down list, it fill the rest of line and at the same time make a duplicate line contain the part we typed just below the line

![http://g.recordit.co/K4hVUHxaQR.gif](http://g.recordit.co/K4hVUHxaQR.gif)

**Comment by rebornix** [comment]
@sagarvd01 it looks like an issue with the Angular extension you are using, can we start invesigation there first?

**Comment by sagarvd01** [comment]
hmm u r right. Sorry for this.
