### ISSUE TITLE
VSC does not open required document when activated from explorer

### ISSUE THREAD

**Issue by StrangeBeing** [Microsoft/vscode#30585]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Double click on a 'C' source code file
2. Admire blank 'Untitled-1' window available for editing

Presumably this is a shell integration issue but I have tried re-installing VSC and it is not resolved.
Typing 'assoc .c' in a cmd.exe window gives:
.c=VisualStudio.c.14.0

**Comment by bpasero** [comment]
Uninstall => Reinstall

**Comment by StrangeBeing** [comment]
tried,

no effect

uninstall, end of problem
