### ISSUE TITLE
debug toolbar disappear after debugging

### ISSUE THREAD

**Issue by whj768702** [Microsoft/vscode#30589]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.2.11
file-icons|fil|1.0.4
canvas-snippets|hol|0.3.1
vim|vsc|0.9.0

(2 theme extensions excluded)

---

1.13 version,toolbar always exist when i started debug.
please forgive my poor English.

**Comment by weinand** [comment]
If the debug toolbar disappears, this means that the debug sessions has ended.
What are you debugging? How does your launch config look like?
