### ISSUE TITLE
Improve support for Linux shells under Windows

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#30592]
Currently we make certain assumptions depending on the OS which are incorrect when running tasks in *nix shells under Windows (e.g. bash, Linux SubSystem, ...). These are:

- path separator
- folder paths

We should improve this.

**Comment by dbaeumer** [comment]
//cc @weinand

**Comment by dbaeumer** [comment]
We looked into this together with Debug and this is quite some work to do it right and therefore needs some planning to when this can happen in a milestone. Keeping on deck.

**Comment by RMacfarlane** [comment]
We just announced remote development with VS Code, Check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
