### ISSUE TITLE
After update to 1.14 word wrap doesn't work anymore

### ISSUE THREAD

**Issue by xanathar** [Microsoft/vscode#30591]
After updating vscode to 1.14, word wrap does not work anymore.
I tried toggling it with alt+Z, the menu item and the command palette command, none of these worked.

- VSCode Version: 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40)
- OS Version: MacOS Sierra 10.12.5 (16F73)

Steps to Reproduce:

1. mmmh upgrade to 1.14.0 from - I guess - 1.13.x. I had word wrap enabled at the time of upgrade. I used the automatic upgrade functionality of vscode.

2. try toggling wordwrap on and off

Reproduces without extensions: Yes

**Comment by J0rgeSerran0** [comment]
I get the next windows when I try to open VSCode and after update VSCode from 1.13 to 1.14.

![vscode_1 14_error](https://user-images.githubusercontent.com/6237500/28169038-6377b088-67e1-11e7-9675-ba52942b0b18.png)

**Comment by joaquimg** [comment]
Word wrap problem here on windows after updating to 1.14

**Comment by eja-git** [comment]
Check your settings.json, it probably has "editor.wordWrap":"true".  "true" is no longer a valid value:

// Controls how lines should wrap. Can be:
  //  - 'off' (disable wrapping),
  //  - 'on' (viewport wrapping),
  //  - 'wordWrapColumn' (wrap at `editor.wordWrapColumn`) or
  //  - 'bounded' (wrap at minimum of viewport and `editor.wordWrapColumn`).

Set it to one of the above and your toggle will start to work again.

**Comment by joaquimg** [comment]
Solved

**Comment by xanathar** [comment]
I confirm changing the setting fixed the issue here, too.
