### ISSUE TITLE
Cannot read property 'args' of undefined

### ISSUE THREAD

**Issue by o-t-w** [Microsoft/vscode#30594]
I am making my first attempt at transpiling Typescript. 
```
My tsconfig.json jile looks like this:
{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true
    }
}

```
I have one ts file

```
class Startup {
    public static main(): number {
        console.log('Hello World');
        return 0;
    }
}

Startup.main();
```

When i go to view > Command Pallette > Tasks: Run Build Task I get the error message 
"Cannot read property 'args' of undefined"

**Comment by dbaeumer** [comment]
@o-t-w I can't reproduce this. Can you provide a GitHub repository I can clone to reproduce this. 

![cast](https://user-images.githubusercontent.com/1931590/28923215-8b1e6262-785d-11e7-8fe4-4ef05b4ae1d9.gif)

Do you have TypeScript installed (e.g. npm install -g typescript)
