### ISSUE TITLE
Auto detected task name changed and lets npm PrelauchTask fail 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#30597]
Setup:

- task auto detection in VS code 1.13. Detects grunt task name 'build'
- launch.json references the grunt task using `"preLaunchTask": "build"`.
- upgrade to 1.14
- pre lauch tasks failes.

The reason is that we now auto detect n build systems in parallel and therefore qualify the name of the prelaunch task. To fix this change the property to `"preLaunchTask": "grunt: build"`.

Same is true for gulp and jake autodetected tasks.

We should document this in the release notes.

We should document this in the release notes.
--

**Comment by dbaeumer** [comment]
Documented in release notes which ship with 1.14.1

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/d9d25a53ff37d7bb9dd700de3c24918f23df79c6
