### ISSUE TITLE
Debugger is not working

### ISSUE THREAD

**Issue by wtang3** [Microsoft/vscode#306]
Getting error when running app in debug mode.

When hitting play on debugger, debugger options appear for split second and exception occurs.

error while processing request '{_request}' (exception: {_exception})

![screen shot 2015-11-19 at 10 09 28 pm](https://cloud.githubusercontent.com/assets/3191584/11291059/57dd9988-8f0a-11e5-9a1b-1b5804581e54.png)

OS: Mac

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#1
