### ISSUE TITLE
No intellisens when using model in views

### ISSUE THREAD

**Issue by Vikingjonsson** [Microsoft/vscode#30606]
Edit:
<img width="1039" alt="attachment" src="https://user-images.githubusercontent.com/8763236/28173967-6908a002-67f0-11e7-870d-365b80716bbb.PNG">

In the image the namespace (@using AddressBook.Models;) is in _ViewImports.cshtml 
If namespace is importet directly in the view  the problem still exists.
End of edit.

When i use @model <Namespace.Models.ModelName> in my views  I get red lines under @Model.Property and a messages saying that the property don't exist in the model, also there is no intellisense. I compiles and runs fine but gets a bit annyoing. Maybe it is something with my set up.

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
ng-template|Ang|0.1.4
cdn-list|Ary|1.0.0
vscode-icontheme-nomo-dark|be5|1.3.2
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.15
eppz-code|epp|1.2.22
azure-iot-toolkit|for|0.1.3
csharpextensions|jch|1.3.0
Angular2|joh|2.3.3
vscode-icon-theme|jtl|1.5.0
node-module-intellisense|lei|1.3.0
Angular-BeastCode|Mik|4.2.18
Arduino|moo|0.0.4
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
vs-keybindings|ms-|0.1.7
indent-rainbow|ode|0.6.1
material-icon-theme|PKi|2.0.10
Csharp-ASPNETCore|rah|1.0.5
vscode-icons|rob|7.10.1
aspnet-helper|sch|0.6.3
Align|ste|0.2.0
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
expresssnippet|vla|0.1.0
vscode-arduino|vsc|0.2.4
unity-snippets|Ycl|0.1.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1. create a empty webb (not mvc)
2. Implement MVC by your self
3. Use a model in a view

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Could you attach an example?

**Comment by Vikingjonsson** [comment]
I added an image and some lines of text to explain.

**Comment by chrmarti** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1637
