### ISSUE TITLE
Proposed setting: editor.wordWrapRuler

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#30609]
Currently there's no way to make `editor.wordWrapColumn` visible (except using the workaround of defining `editor.rulers` to contain the same value of `editor.wordWrapColumn`).

I'd like to propose a new`editor.wordWrapRuler` setting, which would control whether the a vertical line should be drawn at `editor.wordWrapColumn`, similar to those drawn by `editor.rulers`.

The allowed values could be similar to those for `editor.wordWrap`:
- 'off' (never show the ruler),
- 'on' (always show the ruler),
- 'wordWrap' (show the ruler whenever `editor.wordWrap` is "on").

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by waldyrious** [comment]
@rebornix is there a process for reopening issues like these? For example, is it acceptable if I submit it again (or request reopening here) after 12 months?
