### ISSUE TITLE
Multi-root: Drag&drop in file explorer not working [regression?]

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#30605]
It did work with files & folders in the Insiders build if I remember correctly. But not with the current: Version 1.15.0-insider (1.15.0-insider), 74f5073c54f1139d2fb0eccb251cae5ed6e8215b on OS X 10.11.6

There's no message shown in the developer tools console.

cc #28344

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30462
