### ISSUE TITLE
Emmet tab expansion problem

### ISSUE THREAD

**Issue by o-t-w** [Microsoft/vscode#30600]
By default the tab key should expand emmet.
This was not the case for me in VS Code. For example typing p followed by tab expanded to the word DOCTYPE

I went to Keyboard Shortcuts and set emmet.expandAbbreviation to tab.

I am now getting the Info message "Cannot resolve language at cursor" everytime I try to use tab key to expand emmet. 

I haven't installed any auto-completion Extensions so I don't understand why DOCTYPE is being suggested. 

The only way I have managed to get Emmet to work is to make the following user settings:

  // Configures if the built-in HTML language support suggests Ionic tags, properties and values.
  "html.suggest.ionic": false,
// Configures if the built-in HTML language support suggests HTML5 tags, properties and values.
  "html.suggest.html5": false,
  // Controls if suggestions should automatically show up when typing trigger characters
  "editor.suggestOnTriggerCharacters": false,
    // Controls if quick suggestions should show up or not while typing
  "editor.quickSuggestions": false,

But with all this stuff set I no longer get suggestions for JavaScript!

**Comment by jtokoph** [comment]
I'm having the same issue with "Cannot resolve language at cursor"

```json
{
  "editor.snippetSuggestions": "top",
  "emmet.useNewEmmet": true,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "emmet.showExpandedAbbreviation": "never",
  "emmet.showAbbreviationSuggestions": false
}
```

**Comment by jtokoph** [comment]
I think I've found the solution to our problem. My custom keybinding was incorrect.

The incorrect keybind:
```json
{
  "key": "ctrl+q",
  "command": "emmet.expandAbbreviation",
  "when": "editorTextFocus"
}
```

The fixed keybind
```json
{
  "key": "ctrl+q",
  "command": "editor.emmet.action.expandAbbreviation",
  "when": "editorTextFocus"
}
```

**Comment by ramya-rao-a** [comment]
I have pushed a fix for the "Cannot resolve language at cursor" issue. The fix will be available in Tuesday's Insiders build

If you are on Stable build, then the workaround is to bind the shortcut to "editor.emmet.action.expandAbbreviation" as @jtokoph has mentioned above

About using tab for emmet....

In the old emmet model, `tab` key was bound to the expand emmet abbreviation command by default. This caused issues which you can read here: https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list

This is why, in the new emmet model, we discourage users from binding the `tab` key to the expand emmet abbreviation command. You can use any other keybinding. Even better is to make use of the emmet suggestions that show up in the suggestion list.

Can either of you tell me the reason for turning off  the`editor.quickSuggestions` setting?

**Comment by Ollie-w** [comment]
"Can either of you tell me the reason for turning off theeditor.quickSuggestions setting?"

Because it suggests a bunch of unnecessary random irrelevant stuff that is distracting and adds to cognitive load rather than being helpful.
Is it possible to turn it off only for HTML but not for other languages?

**Comment by ramya-rao-a** [comment]
@Ollie-w 

In HTML, the emmet suggestion is almost always the first one. So if you do have `editor.quickSuggestions` turned on, pressing tab (which selects the first item in the suggestion list) should ultimately give you what you need.

Can you turn on `editor.quickSuggestions` and then set `emmet.showAbbreviationSuggestions` to `false` and let me know if that is any better?
Say you type `img`, then the doing the above will result in just show one result which is the expansion of `img` to `<img src="" alt="">`
If `emmet.showAbbreviationSuggestions` is `true`, then in addition to the above, you also get 
- img:s
- img:sizes
- img:srcset
- img:z
which I believe is what you mean by irrelevant stuff?

**Comment by mran3** [comment]
Just wanted to say that emmet was not working for me fine because it was not the first item on the autocomplete list, but after switching to "new emmet" it seems to be working nice, even with Tab.

**Comment by prohle** [comment]
Inside VSCode, you can choose 'Preference'>'Settings', search for 'Emmet' then set "emmet.triggerExpansionOnTab": to true
