### ISSUE TITLE
'registerOnTypeFormattingEditProvider' subscription does not work

### ISSUE THREAD

**Issue by yageek** [Microsoft/vscode#3060]
I'm currently trying to create a basic extension for VSCode. I would like to register a provider with the function `registerOnTypeFormattingEditProvider`.

I found some examples of code on Github to write the provider and make the subscription.

The code of the provider:

    'use strict';
    
    import { OnTypeFormattingEditProvider, TextDocument, Position, FormattingOptions, CancellationToken, TextEdit } from 'vscode';
    
    export class DartCommentsProvider implements OnTypeFormattingEditProvider {
    	
    	public provideOnTypeFormattingEdits(document: TextDocument, position: Position, ch: string, options: FormattingOptions, token: CancellationToken): Thenable<TextEdit[]>{
    		console.log("Character typed:", ch);	
    		
            return new Promise((resolve, reject) => {
    		  return [];
    		});
    	} 
    }

The subscription:

    import * as vscode from 'vscode'; 
    
    import { DartDocumentFormattingEditProvider, Formatter} from './dartFormat';
    import { DartCommentsProvider } from './dartComments';
    import { DartHoverCustomProvider } from './dartHover';
    
    // this method is called when your extension is activated
    // your extension is activated the very first time the command is executed
    export function activate(ctx: vscode.ExtensionContext) {
           
        let dartDocumentFilter: vscode.DocumentFilter = {language : 'dart', scheme:'file'};
        
        ctx.subscriptions.push(vscode.languages.registerHoverProvider(dartDocumentFilter,new DartHoverCustomProvider()));
        
        //Registration
        ctx.subscriptions.push(vscode.languages.registerOnTypeFormattingEditProvider(dartDocumentFilter,new DartCommentsProvider(), ';', '/'));   
    }
    
    // this method is called when your extension is deactivated
    export function deactivate() {
    }

When I press `;` or  `/`, the function `provideOnTypeFormattingEdits` is not called.

**Comment by alexandrudima** [comment]
@yageek The code looks good to me. Can you please also share the `package.json` contents?

i.e. is your extension activated?

**Comment by yageek** [comment]
Here is the contents of the package.json:

```
{
	"name": "Dart",
	"displayName": "Dart",
	"description": "Dart support",
	"version": "0.0.1",
	"publisher": "yageek",
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Languages"
	],
	"activationEvents": [
		"onLanguage:dart"
	],
	"main": "./out/src/extension",
	"contributes": {
		"commands": [{
			"command": "dart.format",
			"title": "Dart: Format file",
            "description" : "Launch Dart format file"
		}],
        "languages": [{
			"id": "dart",
			"aliases": ["Dart", "dart"],
			"extensions": [".dart"],
			"configuration": "./dart.configuration.json"
		}],
		"grammars": [{
			"language": "dart",
			"scopeName": "source.dart",
			"path": "./syntaxes/dart.tmLanguage"
		}]
	},
	"scripts": {
		"vscode:prepublish": "node ./node_modules/vscode/bin/compile",
		"compile": "node ./node_modules/vscode/bin/compile -watch -p ./"
	},
	"devDependencies": {
		"typescript": "^1.6.2",
		"vscode": "0.10.x"
	}
}
```

**Comment by alexandrudima** [comment]
@yageek Also didn't work for me until I realized that `formatOnType` is a setting that must be turned on before this functionality works. So, in your test folder or in your settings please try adding `"editor.formatOnType": true`

**Comment by yageek** [comment]
Thanks for the help. Should not this pointed out in the documentation of `registerOnTypeFormattingEditProvider` ?

**Comment by egamma** [comment]
@yageek agreed updated the doc comment
