### ISSUE TITLE
Why the programme not responding after last update!!

### ISSUE THREAD

**Issue by Basselfathy** [Microsoft/vscode#30607]
- VSCode Version: 1.14.0
- OS Version: Windows 8.1

Reproduces without extensions: Yes/No
![capture](https://user-images.githubusercontent.com/22766655/28164640-977d53d0-67d0-11e7-851e-2c46cbe33860.PNG)

**Comment by Lornz-** [comment]
Same issue here on Mac OS Sierra

**Comment by BobFromAccounting** [comment]
Same issue here :
• Mac OS Sierra version 10.12.5
• VSCode version 1.14.0

**Comment by chrmarti** [comment]
Try `code --uninstall-extension atefth.ruby-on-rails-snippets`

#30407
