### ISSUE TITLE
Cannot Synchronise Changes With Github

### ISSUE THREAD

**Issue by chgibb** [Microsoft/vscode#30618]
- VSCode Version: 1.14.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Update from 1.13.1 to 1.14.0
2. Edit file, commit and click synchronise changes
Git log output:
```
git pull
fatal: cannot exec '/usr/share/code/resources/app/extensions/git/out/askpass.sh': Permission denied
fatal: could not read Username for 'https://github.com': No such device or address
```
3. Fixed by setting exec permission on ```/usr/share/code/resources/app/extensions/git/out/askpass.sh```

Reproduces without extensions: Yes/No
No

**Comment by LionelBino** [comment]
this affect too me.

**Comment by joaomoreno** [comment]
#30437
