### ISSUE TITLE
Multi-stroke keyboard shortcuts render differently in context menu

### ISSUE THREAD

**Issue by mdickin** [Microsoft/vscode#30617]
- VSCode Version: 1.13.1 and 1.14.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install my extension [Markdown Shortcuts] (https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts)
2. Open a new or existing Markdown file
3. Right-click in the editor

![md](https://user-images.githubusercontent.com/22337329/28129272-00909bc8-6733-11e7-8c98-2fcaea3278a7.PNG)

You can see that the commands with single-stroke shortcuts (e.g. "ctrl+B") render differently than the multi-stroke shortcuts (e.g. "Ctrl+M Ctrl+C")

Shortcuts still work correctly, this is just a cosmetic issue

**Comment by chrmarti** [comment]
This is a limitation in Electron which doesn't support rendering the combo shortdcuts.

**Comment by freMea** [comment]
And could the VSCode team involve in that electron bug solution since it affects VSCode user experience?

**Comment by chrmarti** [comment]
I think we looked into that, but don't recall the reason why we didn't do that. The current solution is a workaround.
