### ISSUE TITLE
Can we have something like Visual Studio's Browserlink in vscode ?

### ISSUE THREAD

**Issue by lucianFXD** [Microsoft/vscode#3061]
Maybe through a extension  ? Would be a great feature in vscode.

**Comment by farzadmf** [comment]
+1 for this feature 👍

**Comment by mjbvz** [comment]
This functionality can be contributed by an extension. See the browser-sync extension for example: https://marketplace.visualstudio.com/items?itemName=jasonlhy.vscode-browser-sync

Closing as extension-canidate
