### ISSUE TITLE
Ambiguity in the term "ruler"

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#30610]
Currently the term "ruler" is used for two distinct concepts. One of them is effectively a thin vertical line (as in `editor.rulers`), and the other is the "[overview ruler](https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings)", which isn't a line at all. Honestly I don't think "overview ruler" is an intuitive name. I think something like "scrollbar overlay" would convey the meaning much more clearly.

To add to the confusion, there are other thin vertical lines that are not called "rulers", but "guides" (i.e. the indentation guides). I don't think this distinction is problematic, since such guides are local and contextual, whereas rulers (in the sense used by "editor.rulers") are global and span the entire height of the editor. But I'd be OK if instead it was decided to rename "editor.rulers" to "editor.guides", since that would resolve the ambiguity as well.

Note that #30609 would depend on the choice made here, in order to maintain internal naming coherence an avoid introducing another ambiguity :)

**Comment by alexandrudima** [comment]
I agree on the possible ambiguity on the overload of "ruler". Here is how we got these terms:

* The term "overview ruler" was introduced by [Eclipse](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Feditors_annotations.htm) and we've used it since before launching VS Code.

* I think the term "indent guide" is widely accepted in the editor industry and we're using it correctly and that's how the feature was requested in VS Code [January 2016](https://github.com/Microsoft/vscode/issues/2192).

* I think the term "rulers" was introduced by SublimeText and that's how the feature was requested in VS Code [in February 2016](https://github.com/Microsoft/vscode/issues/1673).

**Comment by waldyrious** [comment]
Thanks for the historical background. Given what we both said:
> I don't think this distinction [indent guides vs. editor rulers] is problematic, since such guides are local and contextual, whereas rulers (in the sense used by "editor.rulers") are global and span the entire height of the editor.

and:
> the term "indent guide" is widely accepted in the editor industry and we're using it correctly

I think there's agreement that the term "indent guides" is not ambiguous and can be set aside for the purposes of this discussion.

On the other hand, when you say

> The term "overview ruler" was introduced by Eclipse and we've used it since before launching VS Code.

It isn't clear to me how consensual you're considering that term to be (say, in a scale from 0 to "indent guides"). My understanding is that (1) "overview ruler" isn't as established in the general space of text editors, although there certainly is some historical baggage that needs to be taken into consideration if a rename is to be considered. Is that interpretation fair?

If so, I'll suggest that (2) the name "overview ruler" is markedly more likely to confuse users unfamiliar with the concept than the name "scrollbar overlay", *especially given the ambiguity with "editor rulers"* mentioned above. I also suggest that this would apply to users familiar with the concept but under a different name than "overview ruler".

On the other hand, I'm assuming (3) that "scrollbar overlay" is not very likely to confuse users who *are* familiar with the concept under the name "overview ruler".

If all 3 points above can be considered plausible, then I think it the sensible option to resolve the ambiguity is to rename "overview ruler" to "scrollbar overlay".

Then again, as I mentioned before, renaming "editor.rulers" to "editor.guides" would also be an option. I'd prefer the former because the overall naming scheme would be more intuitive (and we'd preserve the semantic distinction of full-height rulers vs. block-specific guides), but the latter would at least remove the ambiguity in terminology used by VS Code.

(sorry for the wall of text :innocent:)

**Comment by waldyrious** [comment]
@alexandrudima I realize my last comment might have been too long and not very actionable -- sorry about that. In the interest of moving this forward: is there any nomenclature change you'd consider compatible to the context you described above? Would you like me to clarify/summarize my questions, or make a specific proposal?

**Comment by waldyrious** [comment]
@mjbvz I'd appreciate if you could add some words about why this is considered out of scope. Is that a priority marker, or does it mean this will never be considered?

**Comment by Kemeros** [comment]
I had to find this issue to understand what the Overview Ruler Border was in the settings.
