### ISSUE TITLE
`Use ignore files` option combined with `files to include` set seems to be broken in 1.14 (works fine in 1.13.1)

### ISSUE THREAD

**Issue by kompot** [Microsoft/vscode#30612]
- VSCode Version: 
1.14.0 final and
Code - Insiders 1.15.0-insider (74f5073c54f1139d2fb0eccb251cae5ed6e8215b, 2017-07-12T05:07:15.561Z)
- OS Version: Darwin x64 16.6.0

Steps to Reproduce:

1. Open project with some `.gitignore`d files
2. Search with `Use ignore files` option enabled and `files to include` set to some subfolder (like `./back` that belongs to the project root).
3. 1.13.1 does not include ignored files within `./back`, 1.14.0 final and 1.15.0-insiders do include
4. If `files to include` is empty - everything work as expected.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This will be fixed as part of https://github.com/Microsoft/vscode/issues/27226#issuecomment-313827054
