### ISSUE TITLE
Unable to compare files by right clicking file

### ISSUE THREAD

**Issue by nilact** [Microsoft/vscode#30613]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.7
EditorConfig|Edi|0.9.4
tslint|eg2|0.16.0
angular-essentials|joh|0.2.0
Angular2|joh|2.3.3
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.0.10

---

Steps to Reproduce:

1. Right click on any file and choose an option 'Select for compare' from context menu 
2. Right click on any other file to compare with and it won't display context menu.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269
