### ISSUE TITLE
js inproper syntax highlighting

### ISSUE THREAD

**Issue by minomikula** [Microsoft/vscode#30615]
- VSCode Version:
Version 1.14.0
Commit b8cd5b9556d8b70ea560d35b903422363f6c5c40
Date 2017-07-10T18:36:31.751Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version:
Microsoft Windows 7 Professional

Steps to Reproduce:

1. Open .js file with content:
`
var x = { '01': '<' }; console.log('c', x);
`
2. Code after `<` char have wrong syntax highlightingting.

![wrong](https://user-images.githubusercontent.com/11662000/28167257-4a0ee1bc-67db-11e7-86ac-db857a880339.png)

Correct:

![correct1](https://user-images.githubusercontent.com/11662000/28167488-12c0b39c-67dc-11e7-8c21-3db2cd4a6d18.png)
![correct2](https://user-images.githubusercontent.com/11662000/28167499-14e80756-67dc-11e7-9b1f-e636be9fca28.png)

Reproduces without extensions: Yes

Thanks!

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/487 to track this upstream
