### ISSUE TITLE
Cannot open folders inside onedrive folder 

### ISSUE THREAD

**Issue by PrateekArya** [Microsoft/vscode#30619]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.16237
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.7
code-runner|for|0.6.25

---

Steps to Reproduce:

1. Open VS Code
2. Try to open your Onedrive folder or any other folder inside Onedrive folder
3. Will get an error saying "The path '......' does not seem to exist anymore on disk."

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#27285
