### ISSUE TITLE
Right click does not work in the Explorer after selecting "Select for compare".

### ISSUE THREAD

**Issue by tldr650** [Microsoft/vscode#30614]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0

---
Right click does not work in the Explorer after selecting "Select for compare".
Steps to Reproduce:

1. Open 2 files
2. On the Explorer tab/pane whatever it is called. Right click and select "Select for compare"
3. Right click on the file to compare to. Right click no longer works. 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269
