### ISSUE TITLE
A little bit more margin please 

### ISSUE THREAD

**Issue by thimmy687** [Microsoft/vscode#30626]
- VSCode Version: latest
- OS Version: Win10

A little bit more space between last line from terminal and the blue line below would be nice

![image](https://user-images.githubusercontent.com/7715216/28171585-3158cf80-67e9-11e7-9415-fef38ff4108a.png)

**Comment by Tyriar** [comment]
I 1px border on the bottom would be fine, opening to PRs. Who ever wants to pick this up, you need to make sure the size of the terminal is calculated correctly given the new margin. Relevant files: `TerminalPanel.ts`, `TerminalInstance.ts`.

**Comment by cleidigh** [comment]
@Tyriar 
I'll pick this up. pretty much all of the other termination was already taken, or out of my realm.
just let me know somebody's not already working on this ;-)

**Comment by Tyriar** [comment]
@cleidigh sounds good

**Comment by cleidigh** [comment]
@Tyriar 
PR #30728 posted
