### ISSUE TITLE
Even if doing nothing, takes more and more memory

### ISSUE THREAD

**Issue by Radouch** [Microsoft/vscode#30623]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jshintrc-generator|ben|1.0.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
githistory|don|0.2.1
vscode-html-css|ecm|0.1.7
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
code-select-until|jak|0.6.0
docthis|joe|0.4.7
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
material-icon-theme|PKi|2.0.10
qub-xml|qub|1.2.1
sass-indented|rob|1.4.1
trailing-spaces|sha|0.2.11
easysass|spo|0.0.6
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Update Visual Studio Code to the latest version (June 2017).
2. Run it (just open, do nothing)
3. Open Task Manager.
4. Sit, drink tea or coffee and watch, how it takes more and more memory and processor.
5. Finally, it will display window that it is not responding any more.
6. Close it and write this bugreport.

Reproduces without extensions: No
Or it takes more memory much more slowly, so I do not enough coffee to observe it. :-)

**Comment by Adondriel** [comment]
This is 100% a certain extension. I have a bunch of extensions, with a theme and all, and i've been watching my process for a good while, and the memory usage has not gone up yet.

**Comment by Radouch** [comment]
Adondriel, you are right. And I already know which extension is guilty:
https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion
On the other hand, the update of Visual Studio Code broke it. It worked fine before.

**Comment by Adondriel** [comment]
Ah, I tried using that previously, but it never worked for my projects, cause I use SCSS and could never be bothered to configure it, if it even had a config. Hopefully they update soon.

**Comment by chrmarti** [comment]
Please open an issue with the extension if this also occurs with the upcoming 1.14.1. (Could be #30486)

**Comment by chrmarti** [comment]
Also: Could you try the insiders build and see if the problem still occurs with that? (https://code.visualstudio.com/insiders)

**Comment by Radouch** [comment]
1. Installed insiders build.
2, Installed this extension:
https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion
3. Reloaded window, then closed and open Visual Studio Code.
All seems OK, the error is probably fixed in the insider build.

**Comment by chrmarti** [comment]
Great, thanks.
