### ISSUE TITLE
Provide an option to stop scrolling revealing active file in explorer

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#3062]
I would love to see a user option to disable this feature; it really is a hassle when comparing across multiple files in large projects.

**Comment by ironcladlou** [comment]
Has anyone found a workaround for this?

**Comment by isinbahadir** [comment]
i really need a workaround for this.

**Comment by bpasero** [comment]
@ianwesterfield @ironcladlou @isinbahadir  to be clear, you would still want the working files to reveal the active file but not the folder view below?

**Comment by ironcladlou** [comment]
>@ianwesterfield @ironcladlou @isinbahadir to be clear, you would still want the working files to reveal the active file but not the folder view below?

IMO, yes. I have no issue with the active file being highlighted in the working files section, but for the folder view below, I expect:

1. A way to keep the folder view static regardless of my working file
2. A command to reveal the current working file in the folder view

**Comment by bpasero** [comment]
April release will have a new flag `autoReveal` (default: `true`) to control this behaviour. In addition there is a new command `Show Active File in Explorer`

**Comment by ironcladlou** [comment]
@bpasero That's great news. Thanks.

**Comment by ironcladlou** [comment]
@bpasero I've been using a master build of VSCode to test this feature and it's working great. Thanks again.

**Comment by bpasero** [comment]
@ironcladlou very cool!

**Comment by ianwesterfield** [comment]
The latest release notes say a new "explorer.autoReveal" is exposed, but I'm not seeing it in the defaults. Tried setting it anyway in the user but the behavior isn't altered. Am I missing something?

**Comment by bpasero** [comment]
@ianwesterfield yes, only coming for our post 1.0 release end of this month

**Comment by ianwesterfield** [comment]
Sounds good, and thanks for the speedy update!

**Comment by Fconstant** [comment]
Just for information, `Show Active File in Explorer` was renamed to `Reveal Active File in Side Bar` (in case you don't find it)
