### ISSUE TITLE
Git push should ask for an upstream branch if non has been set

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#30622]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0

---

When working on a new branch and trying to `git push` when no upstream branch has been set, an error pops up stating: `Git: fatal: The current branch relaunch-observations has no upstream branch.`

It would be nice if it could ask for the user to input a branch name to set as an upstream branch for the local one.

**Comment by joaomoreno** [comment]
We should instead ask the user if he wants to `Publish` the branch instead. Want to attempt a PR?

**Comment by BruceGitHub** [comment]
I'm in the beginning, but I would like to contribute.
Can you give me some initial help? 

To define the problem

**Comment by joaomoreno** [comment]
@BruceGitHub You don't need to check if the upstream is set. You can actually try to figure out which error comes from git ([example](https://github.com/Microsoft/vscode/blob/win32-bump64/extensions/git/src/git.ts#L807). If you detect that the error is related to the fact that there is no upstream branch configured, you can ask the user whether he wants to publish the current branch in a message. If so, just run the `git.publish` command.

**Comment by BruceGitHub** [comment]
@joaomoreno the link is broken.

I try to debug the git extension but the breakpoint, It does not work because source map not present... 

how to ?

**Comment by joaomoreno** [comment]
Fixed the link. Debugging is currently not set up. Sorry.

**Comment by BruceGitHub** [comment]
right light ok.

So i add  the if condition, in try catch block related to err.stderr ?

**Comment by BruceGitHub** [comment]
It seems to me

this message:

git remote -v
pipop   /Users/userpippo/Desktop/progetti/remote/ (fetch)
pipop   /Users/userpippo/Desktop/progetti/remote/ (push)

git push
**fatal: No configured push destination.**
....

or this ? 

git push pipop
**fatal: The current branch master has no upstream branch.**
To push the current branch and set the remote as upstream, use

git push --set-upstream pipop master
