### ISSUE TITLE
Unsaved document keeps getting restored no matter what I do

### ISSUE THREAD

**Issue by highestblue** [Microsoft/vscode#30621]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.0.1
EditorConfig|Edi|0.9.4
vscode-placeholder-images|Jak|0.1.0
ionic2|Tha|2.4.0
html-snippets|abu|0.1.0
Handlebars|and|0.2.0
riot-tag|cri|0.1.7
vscode-eslint|dba|1.2.11
vscode-material2-snippets|dee|2.0.0
ember-syntax|dhe|0.5.0
githistory|don|0.2.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
vscode-ember|emb|0.1.0
vscode-great-icons|emm|2.1.9
sass-lint|gle|0.0.4
icon-fonts|idl|1.7.2
react-component|jer|1.0.0
Angular1|joh|0.2.0
Angular2|joh|2.3.3
vscode-styled-components|jpo|0.0.7
ionic1-snippets|jus|1.0.1
haml|kar|0.7.2
bem-expand|luk|0.1.3
ruby-rubocop|mis|0.4.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.1.6
language-liquid|nei|0.0.2
vetur|oct|0.9.1
vuehelper|oys|0.1.0
EmberES6Snippets|pha|2.1.2
Ruby|reb|0.12.1
language-stylus|sys|1.7.3
hipsum|thi|1.0.7
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0
editorconfig-vscode-snippet|zgu|0.2.0

---

Steps to Reproduce:

1. Create new document. 
2. Close the document on the prompt without saving. 
3. Quit VSCode.
4. Document is restored as unsaved document.

I tried setting `files.hotExit` to `off`, saving the document, but when I quit and reopen VSCode. It always gets restored as unsaved document.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@highestblue can you share a video of how this looks like please?

**Comment by highestblue** [comment]
@bpasero http://jmp.sh/2OdKMox 
At `00:08` I just did `CMD+Q` to close the editor.
