### ISSUE TITLE
Debugger not working for npm tasks

### ISSUE THREAD

**Issue by Yahkob** [Microsoft/vscode#30629]
- VSCode Version:Version 1.14.0 (1.14.0)
- OS Version: El Capitan 10.11.6

Steps to Reproduce:

1. Create npm task in .vscode 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script", "dev"
            ],
            "port": 5858
        }
    ]
}
```

2. Configure package.json script 
```    "dev": "node --debug-brk -- /Users/yahkob/myApp/index.js",```

3. make simple index file 

```
module.exports = (function () {
  console.log('hi')
  setTimeout(() => {
    console.log('stuff')
  },120000)
})();

```

after running I get ```Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error).```

**Comment by Yahkob** [comment]
Just confirmed rolling back fixes this

**Comment by weinand** [comment]
from the VS Code 1.14 [release notes](https://code.visualstudio.com/updates/v1_14#_nodejs-v80-related-changes):
> In this release, Node.js debugging will assume the "inspector" protocol whenever the runtimeExecutable attribute of a launch configuration is set. If you see your debug configurations failing, this change could be the reason. To fix this, you can either upgrade Node.js to version 8.x or you can explicitly force the use of the "legacy" protocol by adding "protocol": "legacy" to your launch configuration.

**Comment by Yahkob** [comment]
Thanks @weinand some how missed that :)

**Comment by weinand** [comment]
I hope that my guess is correct... :-)

**Comment by Yahkob** [comment]
Will try and confirm here later @weinand .

**Comment by fattydevelop** [comment]
it works for me.   👍  
release 1.14.1

**Comment by Yahkob** [comment]
Yep can confirm changing to use `"protocol": "legacy"` fixed my issue thanks @weinand

**Comment by rob3c** [comment]
The `legacy` protocol setting fixed my issue, as well.

There's already a message printed to the console that says "Debugging with inspector protocol because a runtime executable is set." Why not add a note there about the  legacy protocol setting for when the affected devs are actually hitting the problem, instead of burying it in the release notes and closed issues? I shudder to think of the cumulative time wasted across all devs for breaking changes like this.
