### ISSUE TITLE
Extension Host hangs the CPU 

### ISSUE THREAD

**Issue by rstoica** [Microsoft/vscode#30639]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.9.1
vscode-docker|Pet|0.0.16
gitignore|cod|0.5.0
githistory|don|0.2.1
python|don|0.6.7
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
latex|ms-|0.1.3
vscode-hexdump|sle|1.4.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.1
vscode-arduino|vsc|0.2.4

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Start code normally with all extensions
Effect: after startup and extension load extension host loads the CPU up to 100% and fails to stop even after exiting vscode. The process causing this is under linux:
/usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost
2. To verify this one can check htop - the process above will always be on top.

Reproduces without extensions: No

Please fix this issue, before the June release Code was a dream.

**Comment by chrmarti** [comment]
Can you retry with the just released 1.14.1?

**Comment by rstoica** [comment]
This patch seems to fix the issue. Thank you!

**Comment by rstoica** [comment]
Hmm, after some time of usage the problem is still there. Absolutely same behavior, just that now it does not start immediately after start-up but with some delay.

**Comment by chrmarti** [comment]
Could you try to find the extension that triggers this by disabling them one by one?

**Comment by rstoica** [comment]
Ok, I will do that during the weekend and post a summary here

**Comment by rstoica** [comment]
I believe I found the culprit. Is the vscode-arduino extension and its support for autocomplete. On my machine, whenever I try to use autocomplete within an Arduino initialized workspace the extension seems to hang trying to load suggestions of APIs (for everything, not only Arduino API). This makes the process listed above to overload the CPU and not even exit after code is terminated. 

Only way I could get rid of this was to sigterm it. Disabling the arduino extension everything seems fine and works as it should.

**Comment by yaohaizh** [comment]
@rstoica  The arduino extension is relying on the C++ extension for autocomplete. The arduino extension only generates the c_cpp_properties.json file for C++ extension to work, without directly provides the autocomplete or trigger events. With this being said, 
1. I open large project with C++ code base, with both arduino and C++ extension installed,  see CPU 100%
2. Uninstall arduino extension, only keep C++ extension, still the CPU is 100%. 
3. Given enough time(depends on project/workspace size), the CPU usage will down to normal case. 

Could you help verify only with C++ extension installed for your project?

**Comment by rstoica** [comment]
@yaohaizh sorry for the late reply. Got down to the issue. I had a mixed dev environment where I have tried platformio extension within code before and then was running the arduino extension. 

On one side the [platformio ide extension](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide) was setting the path to the ARM toolchain, arduino platform and uploader tools I was using within the inner structure of the build framework, while on the other hand the arduino extension was relying on the Arduino official toolchain in another project external location. 

These paths were passed to the C/C++ extension which in terms was indexing everything and then seemed to run itself into an endless loop of searching for definitions and symbols. Removing either of the arduino or platformio extensions and keeping only one upon also cleaning the other's paths resolved the issue for me.

Thanks for the suggestions along the way ! I would close this as I don't see it as a bug imho
