### ISSUE TITLE
Make splited editors (panes) like vim or tmux.

### ISSUE THREAD

**Issue by deryagin** [Microsoft/vscode#30637]
- Let's to think about removing LEFT/CENTER/RIGHT (or TOP/CENTER/BOTTOM) separation.
- Instead of it we could have just one shared tabs bar and as many as you want panes.
- Click on some tab just loads a corresponding file into current pane.
- It will be cool to resize and move this panes as you wish.
- We could also to attach hotkeys for speedy pane movements.

After all, the pane-based interface has long proved its usefulness.
See for example to vim/tmux/i3wm user expirience.

- VSCode Version: 1.14.0
- OS Version: Xubuntu 16.04

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14909
