### ISSUE TITLE
Constant Pop-Up to Log In to GIT

### ISSUE THREAD

**Issue by therealcode** [Microsoft/vscode#30631]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
xml|Dot|1.9.2
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.1.6
html-preview-vscode|tht|0.1.1
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Open VSC.
2. Windows Pop Up to enter GIT credentials for gitlab.com continuously pops up. Have same installation with same extensions on a similar desktop that doesn't produce this issue. 

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
You need to configure a git credential manager: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
