### ISSUE TITLE
Add ability to group tasks in tasks.json so common parameters can be shared

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#30636]
- VSCode Version: 1.14.0
- OS Version: Windows 7 Professsional

Steps to Reproduce:

1. Create task.
2. Create another task with similar configuration. Have to repeat all the configuration parameters such as:
"type": "shell",
"problemMatcher": [],
"presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "dedicated"
      },
      "options": {
        "cwd": "${fileDirname}"
      },
      "command": "",
The only thing is different could be the "args", so why have to repeat everything. If tasks could be grouped they could share/inherit the same parameters. They could add or override the shared parameters, This would make it easier to create multiple tasks (e.g. build tasks for different build configurations).

BTW: The Help, Report Issues menu entry has stopped filling in the VS Code, OS, extensions in the new issues window. Just tried to again and the details were filled in. May be an intermittent problem or a mistake on my part.

**Comment by dbaeumer** [comment]
The is some global attribute definition. `presentation`, `options` and `command` can be defined globally (outside the tasks section) and are then valid for all tasks.

**Comment by alexr00** [comment]
It sounds like the global attribute definitions should solve this well enough. Feel free to ping this issue if that's not the case.
