### ISSUE TITLE
Search in files never completes

### ISSUE THREAD

**Issue by matgr1** [Microsoft/vscode#30630]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
vs-keybindings|ms-|0.1.7
shader|sle|0.2.3

---

Steps to Reproduce:

1. search for something...

The developer console shows the error "[IPC Library: Search] Error: spawn d:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg ENOENT"

Note that "d:" is my boot drive (unfortunately...) and "rg.exe" does exist at that path. Also, I just downgraded to 1.13.1 and search works fine in that version

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Strange. Maybe I need to be spawning it with `rg.exe`, but I don't know why it would only matter for you in this case. And the only relevant change I can think of is updating electron.

**Comment by matgr1** [comment]
I just did a quick check: upgrading to the latest again results in the same problem.  And running as admin makes no difference either

**Comment by roblourens** [comment]
Thanks for checking. Wondering if you could try renaming that file from `rg.exe` to `rg`?

**Comment by matgr1** [comment]
renaming to rg didn't seem to have any effect.

I did also notice that it will find results in files that I have viewed - as in if there's a bunch of tabs open when the process starts it won't find anything in them, but if I click on one of those tabs and run the search again, then it will get results from that file

**Comment by roblourens** [comment]
Thanks for trying. Yeah, search in open files doesn't require `rg.exe`.

**Comment by matgr1** [comment]
No problem, let me know if you'd like me to try anything else!

**Comment by roblourens** [comment]
Is this still an issue? I never reproed it or got another report.

**Comment by matgr1** [comment]
I ended up reinstalling Windows (to the default C: drive) and it went away, so not an issue for me anymore...
