### ISSUE TITLE
Autocomplete with CTRL+SPACE after . does not work

### ISSUE THREAD

**Issue by tomsontom** [Microsoft/vscode#3063]
Use the following snippet:

```typescript
class Bla {
    items : string[];
    item : string;
    
    constructor() {
        this.item.
    }
    
    public blarg() {
        
    }
}
```
Place the cursor after the "this.item." and trigger autocomplete with CTRL+SPACE and notice that no suggestions are displayed. In contrast if you remove the "." and type "." again suggestions are shown.

**Comment by alexandrudima** [comment]
@tomsontom I'm assuming you're in a TypeScript file?

Works for me:
![ts-completion](https://cloud.githubusercontent.com/assets/5047891/13093781/5b986cf4-d507-11e5-9fda-3457fd79dfb5.gif)

**Comment by meritozh** [comment]
maybe you don't set `Salsa` rightly, look this: #3005 , hope help you.

**Comment by tomsontom** [comment]
@alexandrudima yes I am in ts-file - but i just saw that I have been on 0.10.6 - update to 0.10.8 and now things work!
