### ISSUE TITLE
Context menu in OPEN EDITORS pane only displays once

### ISSUE THREAD

**Issue by CalvinDale** [Microsoft/vscode#30641]
- VSCode Version: 1.14.0
- OS Version: Windows 10, v1607

Steps to Reproduce:

1. Open a file
2. Click on the file in the OPEN EDITORS pane to select it
3. Right-click to display its context menu
4. Click on `Select to compare`
5. Right-click again to display the context menu (it doesn't appear)

Reproduces without extensions: Yes

The context menu will subsequently appear on files in the FOLDER-NAME pane; but not in the OPEN EDITORS pane.

**Comment by Tekbr** [comment]
@CalvinDale  See#30269

**Comment by CalvinDale** [comment]
Thanks @Tekbr. I looked for this issue. I'm sure why Google didn't surface it for me.
