### ISSUE TITLE
Add Global Undo and Redo

### ISSUE THREAD

**Issue by joonoro** [Microsoft/vscode#30643]
It would be nice if VS Code could support global undo and redo like in Visual Studio:

>In addition to the typical undo and redo functionality that affects only individual files, the Visual Studio editor includes commands to undo or redo global actions that affect multiple files.

>Global actions include renaming a class or namespace, performing a find-and-replace operation across a solution, refactoring a database, or any other action that changes multiple files.

https://msdn.microsoft.com/en-us/library/ee839600(v=vs.100).aspx

Right now it's difficult to undo a search and replace or refactoring because you have to go through every file.

See also: atom/find-and-replace#331

**Comment by joonoro** [comment]
See also: atom/find-and-replace#331

**Comment by chrmarti** [comment]
Actually #638
