### ISSUE TITLE
VS code Failed to Encode Restorable State - Data Loss

### ISSUE THREAD

**Issue by awiebe** [Microsoft/vscode#30649]
Mac OS applications should either prompt to save or, save application state so next time they run, they can restore unsaved documents.  My computer just automatically rebooted to install updates, and VSCode exited without prompting me, when it came back after reboot it only remembered one of my unsaved documents.  I just lost a significant list of important snippets that I will now have to scrub through my browser history to recover.  This is an **unacceptable** bug, if VSCode can't be trusted to encode state on exit, it should at the very least ignore the autosave flag and create a recovery version of **all** unsaved files.

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
php-formatter|Sop|0.2.4
jsrefactor|cms|1.3.0
python|don|0.6.7
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
php-pack|fel|1.0.1
ftp-simple|hum|0.5.2
debugger-for-chrome|msj|3.1.6

---

Steps to Reproduce:

1. Run VSCode with autosave off
2. Create 2 unsaved documents, one significantly longer than the other
3. For good measure open some saved documents
4. Reboot the system 

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Sorry to hear that. I just tried to reproduce with your steps and could not. We always keep a backup for each file with changes and we restore these backups on a restart. I wonder what could cause some of the files to not restore in your case...

**Comment by awiebe** [comment]
Are these files stored in a location where they could be easily recovered by the end-user?  If so where might I find them?
If I can recover the file it might be a bug in the application relaunching with multiple windows.  If I can't find the file anywhere including my backups it might have failed to properly save the file.

I just ran it again and it seemed to start with fewer windows than I exited it with.  Thankfully the window it lost this time contained only saved files.

**Comment by bpasero** [comment]
@awiebe the location would be: `/Users/<your name>/Library/Application Support/Code/Backups`

There is a setting to control if all windows should restore (`window.restoreWindows: all`) but if any of the windows has dirty files we will restore that window in any case so you do not have to configure this.

Would you be willing to do a little experiment and try to reproduce your issue (open some windows, make some files dirty, trigger a OS restart and see if things restore?)

**Comment by awiebe** [comment]
Hmm so I successfully restored the workspace to the state when the bug occurred from backup, but the bug doesn't seem to have reoccurred, however I remember that a change log came up when it happened.  The only thing I can think is that it was a one off thing that happened because the self-update screwed something up( I didn't bother testing reverting the version of VSCode from backup, because I figure this is a strange edge case).

In any event I was successfully able to retrieve the lost file by restoring the workspace from a Time Machine backup.  **Thank you, you've saved me a lot of trouble.**

So if anyone else has an issue, you can tell them to restore 
`~/Library/Application Support/Code/Backups` from their backup disk.

You might also want to start keeping a rolling backup for the last few launches, just in case something like this happens again.

I would recommend
```
Backups/
  Latest/   #A full copy of the latest backup
  DateTime1/ #Has the same contents of Latest, but is not modified after being creates(so if latest screws up you can recover)
  DateTime2/  #An older backup
  ...
```
Deleting backups older than a certain(user configurable) age at **exit(not launch)**

**Comment by Tyriar** [comment]
@bpasero does the Windows updater perhaps kill windows ungracefully, not giving them a chance to tidy up `Backups/workspaces.json` or something?

**Comment by bpasero** [comment]
@Tyriar could be, but isn't our backup stuff always up to date after 1s of the user typing? Do we rely on the application shutting down gracefully?

**Comment by Tyriar** [comment]
@bpasero yeah you're right, I was remembering back to when the renderer needed to tell main about what to save in workspaces.json. I believe this is now all done on windows creation.
