### ISSUE TITLE
Contributor Tags: Add contributor assignment or help in progress

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#30644]
As a contributor it would be great if there could be some way to acknowledge when
contributors pick up on an issue. There may be some time before PR is ready
and having an issue flagged as in progress from a contributor, or picked up by a team member
would allow for sorting and avoidance of duplicate work. IMHO ;-)

**Comment by chrmarti** [comment]
The way I see this handled currently is by the contributor announcing the start of work on the issue in a comment. That seemed to work so far because the assignee could then always check back or let the contributor know that in fact work on the issue is already being done by the team.

**Comment by cleidigh** [comment]
@chrmarti 
just started be nice if looking at all the help-wanted issues to be able to know what's already been worked on by a tag versus going into each one and looking if anybody picked it up .
not a biggie..

**Comment by chrmarti** [comment]
The problem with this is that it needs to be maintained to be useful. There will be issues labeled that are no longer being worked on because the contributor doesn't have time or lost interest.

**Comment by cleidigh** [comment]
@chrmarti 
that is true, understood.
I guess close this up.
