### ISSUE TITLE
Should we clean package-lock.json files from node_modules when packaging?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#30640]
xterm.js is about to introduce one (~0.5mb) and I'm sure many more modules will in the near future due to npm@5. The package-lock.json file contains a complete, quite verbose, list of dependencies, both dev and non-dev.

<img width="492" alt="screen shot 2017-07-13 at 10 27 33 am" src="https://user-images.githubusercontent.com/2193314/28179191-0c59b614-67b6-11e7-8a7e-9ab0e0dc78d1.png">

**Comment by joaomoreno** [comment]
Sure.
