### ISSUE TITLE
Typo in deployment section

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#30645]
- VSCode Version: Code - Insiders 1.15.0-insider (56a5bf1724f3b882e149a3e7a24e6105a7b837c2, 2017-07-13T06:21:15.951Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.27.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:
![screen shot 2017-07-13 at 3 09 42 pm](https://user-images.githubusercontent.com/835148/28183426-68577c22-67dd-11e7-94fd-f2dff6b0c293.png)

"Application" is spelled wrong.

**Comment by Tekbr** [comment]
@smlombardi See #30611

**Comment by smlombardi** [comment]
Damn, I searched open issues for "typo" and didn't find that one.
