### ISSUE TITLE
Close default settings and keyboard bindings when closing user's settings file.

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#3064]
1) cmd+, to show the side-by-side of the default and user settings
2) cmd+w closes the user settings
3) the default settings pane is now full width
4) cmd+w then shows "There is currently no file opened to close"

You have to click the close glyph or select a file to get rid of the default settings. 

Is this by design? I would think step 2 should close both panes since you can't do anything directly to the default settings anyway.

**Comment by ianwesterfield** [comment]
This also should go for the keyboard bindings.

**Comment by cesaraaron** [comment]
Close the default settings when closing the user's (or vice versa) should be the default behaviour if "workbench.settings.openDefaultSettings" is set to true. _It is the default behaviour in sublime for example._

@bpasero are you still considering this?

**Comment by bpasero** [comment]
This is solved for 1.8 because both default and settings editor moved into 1 editor, see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_8.md#one-side-by-side-settings-editor
