### ISSUE TITLE
SCM and extensions viewlet - uneven margins

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30648]
From https://github.com/Microsoft/vscode/issues/30250#issuecomment-314949017

The input boxes at the top of these two viewlets have much larger margins on the left than the right. The extensions box kind of lines up with the extension item text below, which maybe is the goal. In the SCM viewlet, it doesn't seem to line up with anything. Never noticed it before, but I think they would look better centered.

<img width="1032" alt="gutter" src="https://user-images.githubusercontent.com/1812093/28147371-41ee18d2-6780-11e7-86da-529fa59d7175.png">

**Comment by joaomoreno** [comment]
I am a strong believer that type should have the highest alignment priority. Aligning the type inside the input box with the title in those two viewlets was definitely a purposeful change.

![image](https://user-images.githubusercontent.com/22350/28262819-c8012bdc-6ae4-11e7-8c29-daae84272e70.png)

Somehow that alignment fails in the extension viewlet, when icons aren't visible. Seems like a bug.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
