### ISSUE TITLE
Release notes showing screencasts with Mac shortcuts on a Windows machine

### ISSUE THREAD

**Issue by aarumug** [Microsoft/vscode#30654]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.16244
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.7
beautify|Hoo|1.1.1
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
debugger-for-edge|msj|0.4.1
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Update vscode to 1.14.1
2. After installation in the release notes window see the screencasts under "Command Palette improvements" and "Restore empty workspaces". They show the Mac version on a Windows 10 machine.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
cc @gregvanl
