### ISSUE TITLE
the vscode have a problem for the update.

### ISSUE THREAD

**Issue by lalalawututu** [Microsoft/vscode#30659]
When i update the vscode.It have a dialog box of error.Let me stop updates or retry.

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by lalalawututu** [comment]
![image](https://user-images.githubusercontent.com/22983816/28235455-57c87e7e-6940-11e7-8455-3cb5ebd7a075.png)
Sure.When i update it and it have this problem.I use it very happy and i hope this problem  not to trouble you.Thanks for you contribution.

**Comment by King66** [comment]
An error occurred trying to replace the existing file: 
DeleteFile failed; code 5.
Access is denied.

**Comment by lalalawututu** [comment]
![image](https://user-images.githubusercontent.com/22983816/28236030-c4d3b986-694d-11e7-888e-ae29e112f6af.png)

**Comment by King66** [comment]
you can try to reinstall

**Comment by lalalawututu** [comment]
yeah. I reinstall it.

**Comment by joaomoreno** [comment]
Could you reinstall it?

**Comment by lalalawututu** [comment]
@ joaomoreno  Yes. I reinstall it. Because visual studio code have a error when i update it.So i reinstall it and not update it again.

**Comment by joaomoreno** [comment]
Once you reinstalled it, updates stopped working? Or updates never worked at all?

**Comment by King66** [comment]
I think he means he reinstalled the latest VSCode, and there is no updates available now.

**Comment by lalalawututu** [comment]
Ah，I am sorry that I see you messages now. I use it of no updates. When I update it, it will have a error. So I choose to use old versions.
![_20170724105838](https://user-images.githubusercontent.com/22983816/28506621-367c1be2-705f-11e7-9123-37ae1c29988f.png)

**Comment by lalalawututu** [comment]
This is translate.
版本 = version
提交 = commit
日期 = date
渲染器 = renderer

This problem affect your job.That i use it feel happy now. It is not a big problem.

**Comment by lalalawututu** [comment]
In addition,the visual studio code have a function what it can be open a folder directly.I feel it very cool,I hope use it for Javascript.
![_20170724111554](https://user-images.githubusercontent.com/22983816/28506947-9cdefda8-7061-11e7-8e72-678aa1010a5f.png)
Do you have an example? Thank you very much.

**Comment by King66** [comment]
@lalalawututu 
Why don't you try to install version 1.14?
You can download and install 1.14.

**Comment by lalalawututu** [comment]
OK! I install 1.14 directly.

**Comment by lalalawututu** [comment]
Can you tell me Where can I find the "open folder" api with javascript?Thanks.

**Comment by King66** [comment]
@lalalawututu 
You should learn how to use VSCode at
https://code.visualstudio.com/docs
