### ISSUE TITLE
"Rename Symbol" operations combine with the previous undo step

### ISSUE THREAD

**Issue by benblank** [Microsoft/vscode#30652]
When editing a JavaScript file (I haven't tested with other file types), renaming multiple symbols in a row, then attempting to undo the last one, will result in all of them being undone.

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.1
vscode-ember|emb|0.1.0
vsc-ember-cli|fel|0.3.3
csstriggers|kis|0.3.1
cpptools|ms-|0.12.0
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

1. Open a new file (Cmd-N).
2. Change the language mode to JavaScript (Cmd-Shift-P, "mode", Enter, "javas", Enter).
3. Type `const foo = 1;` and press Enter.
4. Type `const bar = 2;` and press Enter.
5. Ctrl-click on the token "foo", select "Rename Symbol", type "foo1", and press Enter.
6. Ctrl-click on the token "bar", select "Rename Symbol", type "bar2", and press Enter.
7. Undo a single step (Cmd-Z).
8. Observe that both rename operations have been undone.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This does not seem JavaScript specific. @alexandrudima or @rebornix Can you please take a look since this involves the undo history

**Comment by alexandrudima** [comment]
@jrieken undo stops can be pushed via `model.pushStackElement`

two calls should be made, before and after the call to `model.pushEditOperations` in
https://github.com/Microsoft/vscode/blob/7494a1b944e9a81c504a0a6f1bc33f5522cd81cc/src/vs/editor/common/services/bulkEdit.ts#L117
