### ISSUE TITLE
Support fuzzy matching of task names

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30655]
Would love to type something like `task ccb` to select `gulp: clean-client-build` or something like that. Just using the same fuzzy logic as quickopen.

**Comment by dbaeumer** [comment]
I should use matchesFuzzy.

**Comment by dbaeumer** [comment]
To verify: make sure task filtering is using fuzzy matching

**Comment by jrieken** [comment]
@dbaeumer you could have used `fuzzyScore`  :-)

**Comment by dbaeumer** [comment]
@jrieken wasn't aware of that. :-)
