### ISSUE TITLE
Theme applied slowly on window startup

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30662]
- VSCode Version: Code - Insiders 1.15.0-insider (56a5bf1724f3b882e149a3e7a24e6105a7b837c2, 2017-07-13T06:21:15.951Z)
- OS Version: Darwin x64 16.5.0

Been seeing this for a couple days in insiders? Dark+ is noticeably applied for a few seconds when the window loads

![jul-13-2017 19-56-53](https://user-images.githubusercontent.com/323878/28196450-98a7497a-6805-11e7-8617-90b3846bcf08.gif)

**Comment by bpasero** [comment]
I can reproduce.

**Comment by aeschli** [comment]
The fix tackles a regression from the PR on custom token colors, but I'm not sure if that's what you are referring to.  The slow refreshing of the editor tokens is nothing new.

**Comment by bpasero** [comment]
No I was mainly referring to the workbench colors loading slowly.
