### ISSUE TITLE
Switch to regular editor from diff editor when switching to Explorer

### ISSUE THREAD

**Issue by huizhougit** [Microsoft/vscode#30666]
- VSCode Version: 1.14
- OS Version: Win10

Steps to Reproduce:

1. Open a file which is tracked in Git repository.
2. Do any modification on the file.
3. View -> SCM. Click the changed file. The active document is the comparison. 
4. View-> Explorer. 

Expect: After 4, the active document is still the comparison.
Actual: The active document changed after step 4.

Actually, all the documents created by TextDocumentContentProvider have this issue. This is a regression of 1.14.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you show me what you mean by

> This is a regression of 1.14.

?

**Comment by huizhougit** [comment]
I mean v1.13 doesn't have this issue.

**Comment by joaomoreno** [comment]
Can you record a screen recording, showing me the behaviour in 1.13, where this issue doesn't happen?

**Comment by huizhougit** [comment]
I re-install the old version and seems it also has the issue. Looks like it is not a regression.
Anyway, it is a 100% reproduced bug, isn't it?
