### ISSUE TITLE
Emmet single or multicursor not working on Laravel Blade

### ISSUE THREAD

**Issue by mrkalmdn** [Microsoft/vscode#30664]
- VSCode Version: 1.14.1
- OS Version: Windows 7 32bit

Steps to Reproduce:

1. Followed instruction on the release notes. Single cursor works if I removed the change the `emmet.useNewEmmet` to `false`
2. Blade extension [https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade](url)

```
"emmet.syntaxProfiles": {
    "blade": "html"
},
"emmet.useNewEmmet": true,
```

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
@mrkalmdn You need to use `emmet.includeLanguages` and not `emmet.syntaxProfiles`

In the new emmet model, we are restricting the use of `emmet.syntaxProfiles` setting to as described in https://docs.emmet.io/customization/syntax-profiles/ 

As in to define how the output should look like. eg: use case, self closing tags etc.

Also, when you set `emmet.includeLanguages`, reload VS Code for the change to take affect.
I just fixed this issue of needing the reload, so you won't need to reload in Insiders from tomorrow.

**Comment by mrkalmdn** [comment]
Thank you @ramya-rao-a. However, your suggestion only works for single cursor.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ramya-rao-a** [comment]
Works for multi cursor as well

![blade](https://user-images.githubusercontent.com/16890566/28351285-ac76c776-6c03-11e7-87ff-30745e1d849e.gif)

**Comment by mrkalmdn** [comment]
That's wierd. I will try it again later and will update you with the result. Thanks again.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mrkalmdn** [comment]
Its working. I just forgot to set the `emmet.showExpandedAbbreviation` to always. Thanks

**Comment by ramya-rao-a** [comment]
no problem, Happy Coding!
