### ISSUE TITLE
When the "Watch" debug pane is empty there is no watermark and no action on hover

### ISSUE THREAD

**Issue by AngelosP** [Microsoft/vscode#3066]
When the debug pane "Watch" doesn't have any expressions in it, there is no watermark text telling the user that expressions can be added to this pane. As a result the user is not sure how this pane is different to the "Variables" debug pane.

Related to this, when you hover your mouse over the "Watch" debug pane nothing happens. You have to hover over the title of the pane in order to make the "Add Expression" button visible.

**Comment by bgashler1** [comment]
@AngelosP we just talked about this issue today in a UX meeting.  Would your concern be resolved if any time you mouse is hovered over this pane, it will reveal the controls immediately—no need to hover specifically over the header (we would also apply this behavior to other panes).
<img width="212" alt="screen shot 2016-03-02 at 12 34 44 pm" src="https://cloud.githubusercontent.com/assets/11839736/13474516/2f8c5900-e073-11e5-8f7f-8ecd0cbafe38.png">

**Comment by AngelosP** [comment]
Yep! That's probably the best compromise. Having watermark text would be
adding visual noise for very little gain, IMHO.
