### ISSUE TITLE
Python自动增加括号的问题

### ISSUE THREAD

**Issue by shixuexeon** [Microsoft/vscode#30661]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
vscode-database|baj|1.2.0
django-html|bib|1.2.0
jquerysnippets|don|0.0.1
python|don|0.6.7
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
vscode-icons|rob|7.10.1
bootstrap-3-snippets|wcw|0.1.0
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

python增加配置"python.autoComplete.addBrackets": true,时加出来的括号是这样的：
print({{}})
正常应该是print()

**Comment by CnSimonChan** [comment]
You should report extension problems to the extension repo.

Dup of DonJayamanne/pythonVSCode#1031

**Comment by chrmarti** [comment]
Thanks @CnSimonChan .
