### ISSUE TITLE
VS Code Insiders won't update behind proxy

### ISSUE THREAD

**Issue by kannan-balasubramanian** [Microsoft/vscode#30668]
- VSCode Version:1.15.0-insider
- OS Version: Windows 10 64-BIT (v1607 - OS Build: 14393.1358)
- VSCode Date: 2017-07-12T05:16:04.162Z

**Steps to Reproduce:**
01. Download zipped insider build.
02. Extract to a location (After 'unblocking' the zipped filed)
03. Run 'Code - Insiders.exe'.
04. Once VSCode loaded, click on gear icon (At top left bottom).
05. Shows a disabled menu item "Updates Not Available".
06. Tried with and without extensions, no updates.
07. Machine is behind corporate proxy.
08. Extensions are updating fine without issues.
09. Have set authenticated proxy with "proxyStrictSSL" set to "false".
10. Tried "update.channel" with "default" as well as "insiders", still no updates after multiple restarts.
11. I can see the that next insider build for date 2017-07-13 is available, but VSCode is not updating.
12. I have to resort to downloading manually.

PS: Same is the case for stable VSCode version.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Please try it all over again, clearing all your settings. It should just work.

**Comment by kannan-balasubramanian** [comment]
I forgot to mention that, the issue was with a freshly extracted one on a new machine.

Can you please let me know if the following locations are the ones where the settings and extensions are stored ? I will clear them and try again.

C:\Users\<user>\.vscode-insiders
C:\Users\<user>\AppData\Roaming\Code - Insiders

**Comment by joaomoreno** [comment]
Yes they are.

**Comment by kannan-balasubramanian** [comment]
@joaomoreno I tried the following still doesn't work.

1. Deleted the folders "C:\Users<user>\.vscode-insiders", "C:\Users<user>\AppData\Roaming\Code - Insiders\","C:\Users<user>\.vscode\", "C:\Users<user>\AppData\Roaming\Code\"
2. Deleted the extracted "Code" as well as "Code-Insiders" folders.
3. Extracted the VSCode Version:1.14.0-insider 64 BIT.

Still no updates or anything.
Now I have manually updated to 1.14.0-insider 64 BIT.

**Comment by kannan-balasubramanian** [comment]
An update, the issue still persists, but seems like this is not related to proxy. Reason being, in my home PC, I am connected directly to internet without any proxies and there too the insider version is not updating.

My home PC too uses Windows 10 Pro 64-BIT latest anniversary edition.

**Comment by joaomoreno** [comment]
Have you noticed that update notifications now appear in the gear icon, bottom left corner?

**Comment by kannan-balasubramanian** [comment]
Yes I saw it, and there is a menu "Update Not Available" which is disabled.
I am still using 14th Build of 1.15.0-insider at home. Should I update?

**Comment by joaomoreno** [comment]
What do you mean by _14th Build_?

**Comment by kannan-balasubramanian** [comment]
My apologies. I mean the insider version build of 14th of July.

**Comment by joaomoreno** [comment]
You are sure you have not disabled updates in your settings?

Can you use Wireshark to see what outgoing connections to `https://vscode-update.azurewebsites.net` result in?

**Comment by joaomoreno** [comment]
You are sure you have not disabled updates in your settings?

Can you use Wireshark to see what outgoing connections to `https://vscode-update.azurewebsites.net` result in?

**Comment by kannan-balasubramanian** [comment]
Hi @joaomoreno,
I could use only fiddler.
On start of VSCode, there was only one request and response. Attached are the JSON request and response for that request.
Hope this would be useful for you.

[request.txt](https://github.com/Microsoft/vscode/files/1174063/request.txt)
[response.txt](https://github.com/Microsoft/vscode/files/1174062/response.txt)

**Comment by kannan-balasubramanian** [comment]
Following is what I did.
Previously I used only zipped 64bit version. There the Updates menu in bottom settings icons was disabled and in the fiddler no requests went.

But now I installed using the 64 bit installer version and viola, I can see the update menu enabled and also a request to check on updates to https://vscode-update.azurewebsites.net was fired!.

Now again I uninstalled the installer version and extracted the zipped version. I could reproduce the issue with zipped version. 

So seems like the issue is with zipped version only!

**Comment by kannan-balasubramanian** [comment]
With installer version, behind proxy, the update menu is stuck at "Checking For Updates..."

I'm using the following settings.
`{
"http.proxy": "http://xxxx:yyyy@aaa.bbb.com:nnnn/",
"https.proxy": "http://xxxx:yyyy@aaa.bbb.com:nnnn/",
"http.proxyStrictSSL": false,
"update.channel": "insiders"
}`

**Comment by joaomoreno** [comment]
We don't support updates in the zipped version.

**Comment by kannan-balasubramanian** [comment]
At personal laptop, when I click "Check for updates", I get a progress dropdown which says "Checking for updates" but the same doesn't happen at the machine which is behind proxy.

**Comment by barecool** [comment]
@joaomoreno @kannan-balasubramanian 

there is a workaround for updating the zipped version, however you have to manually install the file once VSCode downloads it. 

in order to do this you must have a file with the name unins000.exe in the folder containing the Code - Insiders.exe 

The update will be located in %tmp%\vscode-update-x64 (in a windows 7 64bit machine)

See (vscode/src/vs/platform/update/electron-main/updateService.ts)

`private getUpdateFeedUrl(channel: string): string {
		if (!channel) {
			return null;
		}
		if (process.platform === 'win32' && !fs.existsSync(path.join(path.dirname(process.execPath), 'unins000.exe'))) {
			return null;
		}
		if (!product.updateUrl || !product.commit) {
			return null;
		}
		const platform = this.getUpdatePlatform();
		return `${product.updateUrl}/api/update/${platform}/${channel}/${product.commit}`;
	}`

VSCode will show the badge that an update is available, close VSCode and manually open the file 

%tmp%\vscode-update-x64\Code-(git commit version).exe 

updating is kind of a manual process as you have to point it to the location of the unzipped file. 

In the ends its about the same as going to the download page and obtaining the latest insider version. 

One thing to note is that neither the installed version or the zipped version failed to check for updated behind a corporate proxy, in a non proxy environment they work.  

you will get a banner showing no updates available and in the console the following message;

**net::ERR_NO_SUPPORTED_PROXIES

Error: net::ERR_NO_SUPPORTED_PROXIES: Error: net::ERR_NO_SUPPORTED_PROXIES

Error: net::ERR_NO_SUPPORTED_PROXIES
    at Timeout._onTimeout (C:\TMP\VSCodeInsidersPortable\App\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:77973)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)**

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by kannan-balasubramanian** [comment]
Hi Joaomoreno, I understand that you would like to keep the bug counts under control.

But as a developer in an organization where the policy restricts installing applications/software, you can't expect us to use zipped version and say that zipped versions don't support auto updates.

Please try to work this auto update feature, when possible and thanks for your time in trying to identify the issue.

**Comment by joaomoreno** [comment]
Unfortunately, proxy issues are many and wide. Having a zip which you can manually replace doesn't seem like such a bad solution, considering the restrictions of your network/machine.
