### ISSUE TITLE
Typo on deployment panel "applciation"

### ISSUE THREAD

**Issue by datdoan** [Microsoft/vscode#30669]
- VSCode Version: Code - Insiders 1.15.0-insider (56a5bf1724f3b882e149a3e7a24e6105a7b837c2, 2017-07-13T06:21:15.951Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

---

Steps to Reproduce:

1. Go to Source Control
2. Expand Deployment

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/3129504/28199715-254836aa-68ab-11e7-8110-72084aa8ddaa.png)

**Comment by chrmarti** [comment]
#30611
