### ISSUE TITLE
Modules autocomplete is brocken

### ISSUE THREAD

**Issue by lamartire** [Microsoft/vscode#30673]
- VSCode Version: 1.14
- OS Version: Ubuntu Gnome 17.04

Steps to Reproduce:

1. Create some js modules and import it to some file (must be `js`, not `jsx` extension)
2. Require module
3. Press `ctrl + space`
4. There are not methods or variables of module in suggestions list.

When I downgraded verison of VSCode to 1.13 it works again (the same configuration and extensions).

Reproduces without extensions: Yes

**Comment by ZhangPuXi** [comment]
Me too!

**Comment by ZhangPuXi** [comment]
I am sorry. My case is a little different. The module which written by myself works well. Only the intellisense of third-party modules are broken.

**Comment by mjbvz** [comment]
Can you please try out VSCode 2.4.2 which was just published. This update fixed a few bugs that could be causing this behavior

**Comment by lamartire** [comment]
@mjbvz okay, I'll try it now.

**Comment by lamartire** [comment]
Yeah, it works! Thank you! :+1:
