### ISSUE TITLE
Won't open after 1.14 patch update on macOS

### ISSUE THREAD

**Issue by sorab2142** [Microsoft/vscode#30679]
- VSCode Version: 1.14.1 (Patch release)
- OS Version: Mac 10.12.5

The 1.14 release worked fine, but after updating to the patch release Code will no longer start. In Activity Monitor the process is running but there is no UI. It appears in the dock for a second and then disappears.

Tried a fresh install but issue still persists. I am guessing the update did not install correctly but then the fresh install should have worked but it did not.

**Comment by bpasero** [comment]
@sorab2142 when you run "code --verbose" from the command line, does that show anything?

**Comment by sorab2142** [comment]
@bpasero This is the output:

`[main 14:01:32] Sending env to running instance...`

**Comment by bsvipas** [comment]
Same here.

**Comment by bsvipas** [comment]
Okey, I managed to fix it. You need to check for another VS Code processes and kill it, when you will be able to run VS Code.

Run: `ps aux | grep -i "visual studio"`
And kill it with: `kill -9 ID`

**Comment by bpasero** [comment]
@sorab2142 yes, can you try what @bsvipas suggests?

**Comment by sorab2142** [comment]
Restarting the machine worked.
