### ISSUE TITLE
"Add to Watch" should be available while not debugging

### ISSUE THREAD

**Issue by AngelosP** [Microsoft/vscode#3067]
It would be nice to have the ability to add expression to the "Watch" debug pane even while not debugging. Right now the right-click context menu doesn't have this action when not debugging.

**Comment by egamma** [comment]
@weinand fyi

**Comment by isidorn** [comment]
@egamma @weinand do we really want this? We originally had it but it is polluting the context menu thus we removed it.
Most of our users are not using the debugger and this would be useless to them in the context menu. Maybe I can add it to the context menu only if the user has a `launch.json` in his workspace
