### ISSUE TITLE
Status title is appended to status message

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#30672]
In the Java extension, we use the `window.withProgress' API with a title(in ProgressOptions) and messages.

When rendered the label that is shown is `messages` followed by `title`.
That's a bit strange and only works well if the message is just a percentage. If it also contains text, appending the title looks wrong.

**Comment by jrieken** [comment]
@aeschli What is your suggestions? Where should the title go?

**Comment by aeschli** [comment]
Intuitively, I'd say 'title' before 'message'. But I understand that some users put the percentage in the message. So maybe the API should include a percentage field. (I know I once recommend to remove it as it wasn't used at the time). Or the title just shows up as a tooltip on the wheel or when there is no message.

**Comment by jrieken** [comment]
@aeschli Feel free to do whatever change is needed. I am not really a consumer of that UX and don't know well enough what is needed. Now that we have a good and rich usage, I suggest to make it work for that and see what feedback we get

**Comment by aeschli** [comment]
I made a change that the title is only used when there is no message or when there is no tooltip.
