### ISSUE TITLE
Adopt dynamic-imports for node module

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#30685]
With TypeScript 2.4 we can now use [dynamic imports](https://github.com/Microsoft/TypeScript/issues/12364) to improve startup performance. The idea is to *lazy load* certain modules that aren't (always) needed for starting up. Generally, lazy loading requires some amd-bundle-gymnastics but with node-modules everything is easy. The motivation is that 20% of code loading (from cached data) is spend loading node-modules. 

To see how long it takes to load a certain module do the following:

* start code with the `--performance` flag
* in code hit F1 and show startup performance
* below the table with startup times are different sections outlining times to load and execute all modules we have. Look at everything taking 10ms or longer

In short, the idea here to explore using dynamic imports for lazying. Already today this can be done with late `require`-calls but you lose typing inference with that. Dynamic imports give you both, late and lazy loading *and* type safety/inference.

Sample times when not having cached data (very first startup, ~200 of 1500ms)

<img width="538" alt="screen shot 2017-07-14 at 11 27 43" src="https://user-images.githubusercontent.com/1794099/28206916-1489eb88-6888-11e7-8b48-a69598db5759.png">

Sample times when having cached data (also node modules are cached, ~100 of 500ms) 

<img width="557" alt="screen shot 2017-07-14 at 11 29 04" src="https://user-images.githubusercontent.com/1794099/28206926-1bb63fa6-6888-11e7-9048-f9c696cfd7c2.png">

**Comment by jrieken** [comment]
@Tyriar for evaluating what it means to load `xterm` only when needed.

**Comment by Tyriar** [comment]
@jrieken https://github.com/Microsoft/vscode/commit/6d71f770d217bfa2832897e1c33b72071a30ec15 removes it completely from startup, just need to work out how to pull in types without requiring the code, while still keeping them inside xterm.d.ts.

<img width="368" alt="screen shot 2017-07-14 at 10 02 18 am" src="https://user-images.githubusercontent.com/2193314/28222276-9aec509c-687b-11e7-9c5a-9eec50484ea9.png">

**Comment by jrieken** [comment]
Great. For having types without loading you can use some on-thin-ice-trick which is keeping `import xyzzy from 'xterm'`-statement globally but making sure you reference nothing that exists at runtime. So, if you only reference interfaces and purely-declared-things there will be no global dependency in the emitted JS code. A proper variant of that might be have two d.ts-files, one for runtime types and one for interfaces et al.

**Comment by Tyriar** [comment]
Actually in the process of doing that exact thing https://github.com/Microsoft/TypeScript/issues/15902, getting a weird error though:

<img width="368" alt="screen shot 2017-07-14 at 10 02 18 am" src="https://user-images.githubusercontent.com/2193314/28222574-ef825876-687c-11e7-8340-377a31994dd2.png">

> A proper variant of that might be have two d.ts-files

Soon the types will be handles entirely by the module, it would be a shame to have to keep them in Microsoft/vscode as well when that happens.

**Comment by Tyriar** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/17200

**Comment by jrieken** [comment]
Closing this as most work is done except for `xterm` which is tracked in #31216
