### ISSUE TITLE
I don't see powershell as an option in integrated terminal. I've installed Git bash and that's the only option I see. 

### ISSUE THREAD

**Issue by manishrw** [Microsoft/vscode#30689]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.1
python|don|0.6.7
xml|Dot|1.9.2
gitlens|eam|4.3.1
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
vim|vsc|0.9.0
gitblame|wad|1.11.3
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Install Git bash.
2. Switch to Git bash as default.
3. Restart the VSC to see powershell not as an option.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You're only shown the selection when you haven't made a choice. You can pull the shell selector up by running the "Select Default Shell" command via command palette (`F1`). You can also manually point to a shell path in your settings (`ctrl+.`)

**Comment by manishrw** [comment]
Thanks for the reply!
I was able to change the Default shell. Is there a way I can directly switch from one shell to another from the terminal box?

**Comment by Tyriar** [comment]
You can run cmd/powershell from your shell since they're on the path. To do this without nested shells you have https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher as an option
