### ISSUE TITLE
Cannot displays Extension list after updated to 1.14.1

### ISSUE THREAD

**Issue by ylhyh** [Microsoft/vscode#30687]
- VSCode Version: 1.14.1
- OS Version: Windows 7 Pro x64

Steps to Reproduce:
1. Behind in a corp proxy with authentication.
2. configured http.proxy in settings
3. upgraded to 1.14.1
4. Search C# in EXTENSIONS, nothing to be displayed.

It's work well in VS code 1.13.1

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by ylhyh** [comment]
@joaomoreno , thanks for the follow up.
I have tried the version 1.15.0-insider, it still not work. I used the same proxy setting in 1.13.1 and 1.15.0-insider, but 1.13.1 works.

**Comment by ylhyh** [comment]
The internet connection may be blocked by the corp security policy. I will try a workaround and feedback later.

**Comment by joaomoreno** [comment]
Thanks. Take a look at this: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/setup/network.md
