### ISSUE TITLE
Double clicking a file in Unity to open VSCode always show update note

### ISSUE THREAD

**Issue by 5argon** [Microsoft/vscode#30683]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.2
unity-debug|Uni|1.2.1
code-runner|for|0.6.26
docomment|k--|0.0.17
graphql-for-vscode|kum|1.4.2
HTMLHint|mka|0.3.3
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
java|red|0.7.0
PostCSS|ric|1.0.1
stylelint|shi|0.27.0
ink|tom|0.1.0
vim|vsc|0.9.0
vscode-proto3|zxh|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Wait for a new update
2. Double clicking a file in Unity to open VSCode always show update note.
3. To make the release note stop automatically popping up, you have to open VSCode manually. (not by double clicking file)

To fix : Make the double click open have the same "already read the release note" effect as manually open VSCode.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I think the release notes should open in the background if other files are opening in the workbench...

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
