### ISSUE TITLE
Full path in debug callstack

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#30686]
_From @ubershmekel on June 5, 2017 21:18_

I have an app with `index.js` that's calling my library that has an entry point of `index.js` which relies on `node_modules/express/lib/router/index.js` so my stack trace is entirely `index.js` with no way of telling which part of it is actually in my code.

Is there a way to give a user-configurable option or perhaps expand the path when there's room for it?

![index.js](http://i.imgur.com/v0lJZb7.png)

Related to:
* https://github.com/Microsoft/vscode-node-debug/commit/c4a38ad0c70dccbb3b35c0ab5cd44891541dc300
* https://github.com/Microsoft/vscode/issues/18447

_Copied from original issue: Microsoft/vscode-node-debug#146_

**Comment by weinand** [comment]
You can hover over the name to see the full path of the name.

**Comment by weinand** [comment]
I'm move this request over to VS Code because this is a general debug UI issue and not node-debug specific.

**Comment by ubershmekel** [comment]
@weinand thank you.

**Comment by auchenberg** [comment]
Could we render the full path and simple use right-aligned text ellipsis to mask the overflow?

**Comment by isidorn** [comment]
Thanks for the suggestions however rendering the full path would give more details to an already clutterd UI imho.
Though we some scatches are a good first start for a PR.

**Comment by weinand** [comment]
To avoid the clutter when always showing the full path we could only show those segments from the end of the path that allow to distinguish files with the same name, e.g. something like this:

```
foo.js
src/index.js
router/index.js
main.js
```

With this approach most callstacks will continue to look compact.

**Comment by isidorn** [comment]
I like this idea, it goes well with some other places in the workbench where we in tabs we show path of a file only if the file name is duplicated.

**Comment by weinand** [comment]
Oh, I didn't know that. So even better!

**Comment by isidorn** [comment]
We know show the path segments which distunguish the sources. You can try it in tomorrow's insiders

![screen shot 2018-05-11 at 15 16 42](https://user-images.githubusercontent.com/1926584/39926061-5bec5b80-552e-11e8-838b-e147882cb7a7.png)
