### ISSUE TITLE
如何同步配置或者导出配置，gist方法用的不爽，同步经常有问题，微软是否有自家的同步

### ISSUE THREAD

**Issue by bsqsbylt** [Microsoft/vscode#30684]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
You could try https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync . There is no built-in synchronization for settings.

**Comment by bsqsbylt** [comment]
can we dev one key export，one key import ？

**Comment by chrmarti** [comment]
Yes, you can copy the `settings.json` around. There is a 'Copy Path' action in the context menu on the editor tab, if you need to find the file first.
