### ISSUE TITLE
VS Code Dark+ theme PHP syntax highlighting broken on certain code

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#30681]
- VSCode Version: 1.14.0
- VSCode Version: 1.14.1
- VSCode Version: 1.15.0-Insiders

This code worked with 1.13
```php
<?php 
return array("Template", function ($id) { 
    ?>
    <div class="<?php echo $id ?>">
        <span></span>
    </div>
<?php });
```

Minimal repro:

```php
<?php 
return array(function () { 
    ?><img /><?php 
});
```

Now with 1.14.1 it renders as mostly white:

![image](https://user-images.githubusercontent.com/64731/28203561-fa78302e-6882-11e7-8692-932c42d26c34.png)

It looks like it goes awry when function is passed to array and then `?>`

**Comment by d0x2f** [comment]
I see this as well whenever traits are used.

![image](https://user-images.githubusercontent.com/8149130/28256728-5c7db4ba-6b08-11e7-9a5e-bd8310b2d350.png)

**Comment by lucas-viewup** [comment]
![err-hl](https://user-images.githubusercontent.com/28161720/28316175-19663752-6b98-11e7-826d-f52a8523f85c.PNG)

Yup, I had this error, too, It's clear that not a specific color theme, I switched all the color themes available and all of them showed the same behavior.

**Comment by Ciantic** [comment]
I must note too that with monokai dimmed I can get a lot of PHP syntax highlighting brokeness. So there must be some underlieng problems there.

**Comment by roblourens** [comment]
Filed https://github.com/atom/language-php/issues/246 for the first issue.

https://github.com/atom/language-php/issues/235 is tracking the second.

@lucas-viewup Are you looking at `function_exists` being two different colors? I don't repro that in Insiders. Can you try there?

@Ciantic There are several issues around right now :)

**Comment by carloDellarossa** [comment]
this is happening inside a foreach loop too
