### ISSUE TITLE
Perl: Incorrect Syntax Highlighting

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#30699]
VSCode Version: Code 1.14.0
OS Version: Mac OSX
Configured Language: Perl

The the following code

```
if ( $product->{url} and $memcached_search ) {
    $product->{url}.=$product->{url}=~m{\?}?";":"?";
    $product->{url}.='s='.$memcached_search.'X'.++$pos;
}
```

Near `~m{\?}?` if you add space between closing `}` and `?` then the syntax looks fine otherwise it looks broken. I'm using the material theme but this appears on any theme.

I think the fix has something to do with the Perl tmLanguage file but I don't know where to find it and what rule I should be looking for :(

Demo : http://i.imgur.com/bjhypxh.gif

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#25

**Comment by atif089** [comment]
@aeschli Thanks for forwarding the issue to TextMate. If I want to fix this locally, can you point me the path of the file where I can make changes to in order to fix this for myself?

I can also probably send a pull request to TextMate repo but I'm not sure when they will merge it.

Or is it possible to override this in form of a plugin?

**Comment by aeschli** [comment]
Yes, grammars from extensions will replace the built-in grammar.
See [here](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-language-colorizer) for a starting point.

But the best would be a pull request against the perl grammar and to avoid forking the grammar.
