### ISSUE TITLE
[vbs] Commenting is broken

### ISSUE THREAD

**Issue by zspitz** [Microsoft/vscode#30696]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a `.vbs` file with the following code, or type into a new file with VBScript as the selected language:

       Dim a

2. Choose "Add line comment" from the command palette

**Expected resiult**

    ' Dim a

**Actual result**

    // Dim a

Note that the Visual Basic language selection handles this properly.

**Comment by rebornix** [comment]
@zspitz did you install any extension which might change the behavior? I can't reproduce with a vanilla VSCode. You can try with `code --disable-extensions`.

**Comment by zspitz** [comment]
@rebornix VBScript support is only added with [this extension](https://marketplace.visualstudio.com/items?itemName=luggage66.VBScript). I will take this up with the authors of the extension.
