### ISSUE TITLE
[TAB] not inserting tab character when using "Indent using Spaces"

### ISSUE THREAD

**Issue by kbakk** [Microsoft/vscode#30692]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open new file (plain text), type `hello`<kbd>TAB</kbd>`world`

Expected: Tab is inserted, text is 

```
hello	world
```
Actual:  Spaces (4) are inserted, not tabs, text is 

```
hello   world
```

* Changing indentation from space to tabs yields expected behavior. 

Reproduces without extensions: Yes

_Edit: Markdown_

**Comment by rebornix** [comment]
@kbakk can you check your personal setting or workspace setting to see if there is any overriden value for `editor.insertSpaces`?

**Comment by kbakk** [comment]
@rebornix For me, `editor.insertSpaces` is not overriden in settings.json, and I don't have workspace settings (using a new window). 

I do see in Default Settings however, `"editor.insertSpaces": true`. Changing to false does result in expected behavior (tab character is inserted). A little strange default behavior I think, but being able to override this works for me.

**Comment by alexandrudima** [comment]
There are 3 settings that configure the editor:
```
// The number of spaces a tab is equal to. This setting is overriden based on the file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,

  // Insert spaces when pressing Tab. This setting is overriden based on the file contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
  "editor.detectIndentation": true,
``` 

Based on those 3 settings, when a file is opened, an indentation is chosen for the file. The current indentation settings are reflected in the status bar of the editor:
e.g.
![image](https://user-images.githubusercontent.com/5047891/32044532-1b814cbc-ba3e-11e7-95ef-f1ff3392c832.png)

or

![image](https://user-images.githubusercontent.com/5047891/32044549-258447d2-ba3e-11e7-9ef8-e6bb7811cfc1.png)


Pressing <kbd>Enter</kbd> or <kbd>Tab</kbd> will respect what the current indentation configuration is, as presented in the status bar.
