### ISSUE TITLE
[vb] 'As' keyword not highlighted

### ISSUE THREAD

**Issue by zspitz** [Microsoft/vscode#30695]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a `.vb` file with the following code, or type into a new file with Visual Basic as the selected language:

    Dim a As Integer

**Expected resiult**: The keyword `As` should be highlighted
**Actual result**: `As` is considered regular text

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
The VS default theme render operators with the default foreground color. Typically that's `+` or `-` but in the case VS it's also `as`.
Either user a different theme or file an issue against https://github.com/textmate/asp.vb.net.tmbundle that `as` should be a keyword, not an operator.
