### ISSUE TITLE
VS Code Connection to TFVC very slow

### ISSUE THREAD

**Issue by dlokman** [Microsoft/vscode#30697]
Hello,

I connected VSCode folder to TFVC Source Control. I am able to  checkout files and then modify them and then check them in. However, after modifying code in VSCode it take a while for them to be checked out under Included changes section. Why is it taking so long for the files to appear under Included Changes in VSCode once the change is made? 

I'm evaluating VSCode integration with TFVC instead of Git. But it seems like integration with TFVC is very slow and may just avoid using VSCode altogether if our company just sticks with TFS instead of Git.

Will this improve? 

FYI-  TFS is locally installed on the same computer.

Dan

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vsts-vscode#286
