### ISSUE TITLE
EH debugging: identify debug window through session ID

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30698]
This issue is about enabling a multi-root workspace to launch and debug extensions via extension host debugging.

We have code in the extension host to broadcast messages to that window which launched the extension host. We use the simple extension development path as a way to find the target window. This cannot work anymore once you are in a multi-root workspace where you can have multiple paths (and you can have multiple windows with the same path).

After talking to @weinand we think that the best approach would be that the broadcast message is send to simply all windows and that it includes the debug session ID. With that information we can do the correct thing where we receive the message (in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L162). 

I have pushed the change to broadcast to all windows and I added some workaround for now to enable EH debugging by simply checking if a EH session is active. This unblocks us for now. Once we have the debug session ID, we can do the real fix.

**Comment by isidorn** [comment]
I am now passing a `__sessionId` from the vscode debug to the debug adapter, the debug adapter then forwards this as `--debugId` to the extension host. Now extension host will always include this `debugId` in the `broadcast` `payload`.

Seems to work fine for all cases. I have removed the workarounds on the debug side but I am not sure if @bpasero added more workarounds on the extension host side which can now be removed

**Comment by bpasero** [comment]
@isidorn very cool, the only place where I had a "hack" in was the one you seem to have taken care of: https://github.com/Microsoft/vscode/commit/0f731a79dfa8f3d14f6312ebef181697e7ad2dad#diff-4e8f1e1f9a43a95b525cbbe5abc3b2e8R169
