### ISSUE TITLE
Default to use font with programming ligatures if they are installed

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#30693]
Just a suggestion, VSCode should set `editor.fontLigatures` to `true` if it finds programming ligature fonts in the user's system 👍

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
