### ISSUE TITLE
createTerminal doesn't run js files on windows

### ISSUE THREAD

**Issue by RalphHogenbirk** [Microsoft/vscode#30706]
In my plugin, I'm running a js file in the terminal using createTerminal. This works fine in linux and osx, but on windows it doesn't. It opens the terminal with the right name but the contents stay black instead of printing the output from the js file. Clicking with the mouse inside the empty terminal results in the console opening and displaying the following two errors:

```
[uncaught exception]: TypeError: Cannot read property 'NaN' of undefined
onError @ index.js:5
```
```
index.js:5 TypeError: Cannot read property 'NaN' of undefined
    at SelectionManager._onSingleClick (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:228:71)
    at SelectionManager._onMouseDown (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:192:22)
    at HTMLDivElement.SelectionManager._initListeners._mouseDownListener (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\xterm\lib\SelectionManager.js:53:67)
onError @ index.js:5
```

Minimal code to reproduce is putting the following code in the activate function of my plugin:

_main.js_
```
var term = vscode.window.createTerminal({name: "Terminal Test", shellPath: "c:/users/me/test.js"} )
term.show()
```
(I've tried multiple ways to write this createTerminal line; relative and absolute path, using "node" as the shellPath and passing the js file in the shellArgs, but all end up with the same result)

_test.js_
```
#!/usr/bin/env node

console.log('Test')
```

- VSCode Version: 1.14.1
- OS Version: windows 10 (tested on 64bit machine and 32bit vm)

My vscode installation is fresh and unused, so not a single other plugin installed

I hope this is not me doing something stupid, in which case I apologise for posting here instead of stackoverflow. Looking at the stacktrace it does seem to be an internal issue with xterm, although the click error might be unrelated to the fact that is just doesn't start the js file. 

I hope someone can give me a hand with this, or check if it's indeed an issue with vsc itself.

**Comment by Tyriar** [comment]
This is because the shebang notation isn't understood by Windows and you haven't associated a program to run .js files with. You should use shell `node.exe` and args: `[file.js]` instead

**Comment by RalphHogenbirk** [comment]
Thanks @Tyriar, my mistake! Sorry for bothering you with it.

**Comment by Tyriar** [comment]
No worries :smiley:
