### ISSUE TITLE
Go to definition (bash script) doesn't work

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#30705]
- VSCode Version: 1.14.1
- OS Version: 10.12.5

Steps to Reproduce:
1. Create a simple bash script
```bash
#!/bin/bash

main() {
  echo "You're in!"
}

main
```

2. Put the cursor on the last line, where `main` is. Press `F12`
3. Cursor doesn't move to the function definition.

Reproduces without extensions: Yes

I don't remember this ever working.

**Comment by rebornix** [comment]
I don't think we have intellisense for bash at this moment. It's definitely a good candidate for extensions. Thanks for reporting.

**Comment by dmlemos** [comment]
Intellisense for bash would be great.

**Comment by mjbvz** [comment]
Duplicate of #309. This could be contributed by an extension
