### ISSUE TITLE
VS Code blinking on VMWare macOS

### ISSUE THREAD

**Issue by mifkys** [Microsoft/vscode#30703]
Example: https://youtu.be/_cJAXvYl6xY

- VSCode Version: 1.14
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Download from https://code.visualstudio.com/
2. Run on VMWare virtual machine with macOS

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Does it reproduce if you run "code --disable-gpu"?

**Comment by mifkys** [comment]
No, `./Electron --disable-gpu` didn't help.
