### ISSUE TITLE
ftp-sync does not work and no any error can be debugged.

### ISSUE THREAD

**Issue by nincompoopcn** [Microsoft/vscode#30704]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
python|don|0.6.7
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.0
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Please report this issue at the ftp-sync extension.
