### ISSUE TITLE
Add a setting to not reload a file when it changes externally

### ISSUE THREAD

**Issue by cirelramos** [Microsoft/vscode#30702]
how i can stop the file reload again, when lost the focus of a file?

- VSCode Version:1.14.1
- OS Version: Linux mint 18.1

Reproduces without extensions:  No

**Comment by bpasero** [comment]
Can you explain please what you mean?

**Comment by cirelramos** [comment]
okey my friend, you imagine that try work remote, but when you change between files, it reload again the vscode, anybody modified the files.
i want stop this  files reload.
 how do it?

**Comment by bpasero** [comment]
@cirelramos I see, so you have other people edit the same files that you are editing and the changes show up when you switch between the files? Isn't that a useful thing to have?

**Comment by cirelramos** [comment]
yes my friend, but i need that when change between files does not refresh or reload the same again if no was had modification the file

**Comment by cirelramos** [comment]
i show my settings 


`{
    "markdown.preview.breaks": true,
    "git.enabled": false,
    "git.autorefresh": false,
    "workbench.colorTheme": "Monokai",
    "editor.tabSize": 1,
    "files.autoSave": "off",
    "editor.wordWrap": "on",
    "editor.formatOnSave": false,
    "workbench.quickOpen.closeOnFocusLost": false,
    "workbench.editor.closeOnFileDelete": false,
    "explorer.autoReveal": false,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/node_modules": true,
        "**/.DS_Store": true
    },
    "editor.multiCursorModifier": "ctrlCmd",
    "react.beautify.onSave": false,
    "editor.fontSize": 18,
    "editor.mouseWheelZoom": true,
    "editor.formatOnPaste": false,
    "editor.autoIndent": true,
    "problems.autoReveal": false,
    "markdown.previewFrontMatter": "show",
    "editor.detectIndentation": true,
    "window.zoomLevel": -1
}`


which options i can add for solved it?

**Comment by bpasero** [comment]
Ok, such a setting does not exist yet.

**Comment by bpasero** [comment]
@cirelramos would it help you id you got a dialog prompting you to accept or ignore the remote changes?

**Comment by cirelramos** [comment]
not yet :/ but you remember not is accept or ignore changes, the issue is when i switch between remote files, that it not has change or difference between the load in vscode and the file remote, the vscode reload again :s

**Comment by bpasero** [comment]
@cirelramos well, once you switch to the other file (and the contents have changed), it could then prompt and ask to accept the changes or not?

**Comment by cirelramos** [comment]
Well, maybe it's an option, but i think in automatic reload when it's changed and when it's not changed not reload

**Comment by bpasero** [comment]
@cirelramos if there was no modification in the file, in what way is the reload of the file then causing issues for you? Sorry, trying to understand the underlying issue here.

**Comment by bpasero** [comment]
Closing for missing details from https://github.com/Microsoft/vscode/issues/30702#issuecomment-321853235
