### ISSUE TITLE
Move file/folder not working in insiders 1.15.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by pouyana** [Microsoft/vscode#30700]
- VSCode Version:
> Version 1.15.0-insider
> Commit 74f5073c54f1139d2fb0eccb251cae5ed6e8215b
> Date 2017-07-12T05:10:47.810Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0
> Architecture x64
- OS Version:
> Ubuntu 16.04.2 LTS

Steps to Reproduce:

1. Create a project folder (testFolder)
2. Create a new folder inside it. (testSubFolder)
3. Create a test file in testFolder
4. try to drag and drop the file from testFoler to testSubFolder.
5. The test file stays where it is which should not happen
6. The same applies to folders too

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@pouyana please update your insiders, this was meanwhile fixed.
