### ISSUE TITLE
Wrong autocomplete suggestion after typing "end" in Ruby mode

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#30701]
- VSCode Version: 1.14.0
- OS Version: macOS 10.12.5

![vsc](https://user-images.githubusercontent.com/50314/28212156-602826aa-68a0-11e7-89ae-eb1bc7fbd3cc.gif)

Steps to Reproduce:

1. Type `def methodname`
2. Hit Enter.
3. Type `end`
4. Autocompletions will suggest `def` and other things starting with `d` as the options.
5. Hit backspace and trigger autocompletions again; it will be correct.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
It seems that after the indentation adjustment, the autocomplete box loses the context what word it's working on.

**Comment by jrieken** [comment]
@atombender Can you still reproduce? It took a while for this issue to reach me, but I cannot repo (anymore)

![oct-30-2017 17-42-45](https://user-images.githubusercontent.com/1794099/32183531-da93a60a-bd99-11e7-9a02-97ed4c478067.gif)

**Comment by atombender** [comment]
Looks like someone fixed this. Thanks.
