### ISSUE TITLE
Test: Improved --wait behaviour

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30717]
Test for https://github.com/Microsoft/vscode/issues/18199 and https://github.com/Microsoft/vscode/issues/28661

Complexity: 3

- [x] Windows - **@egamma**
- [x] macOS - **@weinand**
- [x] Linux - **@joaomoreno**

VS Code can be started with the `--wait` argument from the command line and this will cause the terminal to wait until the VS Code instance is closed. A popular use case is to configure VS Code as git editor to edit git commit messages (see https://stackoverflow.com/questions/30024353/how-to-use-visual-studio-code-as-default-editor-for-git)

The implementation of this feature was rewritten to fix https://github.com/Microsoft/vscode/issues/18199. Verify using the CLI (e.g. `code --wait <path to some file>`):
* you get back to the prompt when starting an initial instance and closing that instance
* same when starting a second instance and closing that instance or all instances
* same when starting an initial instance, opening a second window and closing the first window

In addition, we will close the window when the last editor is closed of that instance (this is https://github.com/Microsoft/vscode/issues/28661). Verify:
* the window closes and you get back to the prompt when closing the last editor of the instance that was opened with `--wait`

Finally, verify that VS Code can still be used as git editor as outlined in https://stackoverflow.com/questions/30024353/how-to-use-visual-studio-code-as-default-editor-for-git

**Comment by joaomoreno** [comment]
Works like a charm!!
