### ISSUE TITLE
Right click file options dissappear after selecting a first file for compare

### ISSUE THREAD

**Issue by gregparadee** [Microsoft/vscode#30710]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
html-snippets|abu|0.1.0
javadebugger|don|0.1.2
python|don|0.6.7
mssql|ms-|1.0.0
vscode-icons|rob|7.10.1
vscode-sql-beautify|sen|0.0.4
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1. Open two files and view them in the Explorer > Open Editors pane
2. Right click on a file and "select for compare"
3. Right click on another file and no options will appear

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30269
