### ISSUE TITLE
Format Selection formats everything

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#30712]
- VSCode Version: 1.14.1
- ProductName: Mac OS X
- ProductVersion: 10.12.5
- BuildVersion: 16F73

Format Selection formats everything, but not the selected part.

**Comment by rebornix** [comment]
@bsvipas what's the language of that file and what extensions you installed? Formatting selections is related to these two factors.

**Comment by bsvipas** [comment]
@rebornix Hi, it is JavaScript (.js) file.

**Comment by rebornix** [comment]
![jsformat](https://user-images.githubusercontent.com/876920/28341679-952d923c-6bc9-11e7-921b-c4900d79716b.gif)

@bsvipas I didn't reproduce this issue. Is it possible that you installed some extensions which might change this behavior? You can try by running `code --disable-extensions`

**Comment by bsvipas** [comment]
@rebornix Yes, you're right this is `Prettier` problem.
