### ISSUE TITLE
Default keyboard shortcuts for Accept Incoming / Current gone

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#30713]
- VSCode Version: 1.14.0
- OS Version: Linux

After updating to 1.14 `merge-conflict.accept.current` and `merge-conflict.accept.incoming` no longer have their keyboard shortcut Alt+M, 1 / Alt+M, 2 assigned to them. I found them really handy and would like to keep my custom keybindings as short as possible (makes it easier when switching machines or sitting in front of another person's VS Code).

**Comment by chrmarti** [comment]
The `Alt` combinations were causing problems, see #28376.

**Comment by chrmarti** [comment]
You can add them back through File > Preferences > Keyboard Shortcuts.
