### ISSUE TITLE
Missing Octicons usage documentation

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30714]
I discovered by chance that in many places VSC replaces a placeholder like this `$(icon-name)` with an icon, and that the supported icons can be seen [here](https://octicons.github.com/).

Other than a tiny reference [here](https://code.visualstudio.com/docs/extensions/example-word-count#_customizing-the-status-bar) to this feature I believe it is completely undocumented, or at least I wasn't able to find anything on Google.

I believe such useful feature deserves proper documentation.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1094
