### ISSUE TITLE
Detect File's Git Repository

### ISSUE THREAD

**Issue by 8SheldonS8** [Microsoft/vscode#30711]
- VSCode Version: 1.14.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create a folder to hold repositories
2. Clone multiple repositories into this folder
3. Open the top level folder
4. Open a file in the editor
5. Notice the Source Control wants you to initialize the repository, as if it is only looking at the top folder and not the folder that contains the file already under Git.  I know VS2017 can do this once you add your local repositories.

Reproduces without extensions: Yes

**Comment by rlingineni** [comment]
+1 any update?

**Comment by joaomoreno** [comment]
This is now fixed.
