### ISSUE TITLE
Test: Multi Root Workspaces

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30722]
Test for: Multi Root Workspaces

Complexity: 5

- [x] Windows @isidorn 
- [x] Linux @weinand
- [x] macOS @chrisdias 

In this milestone we rewrote how multi root workspaces surface in VS Code. The previous solution with having a `workspace` setting in user settings is obsolete (there is no migration). See https://github.com/Microsoft/vscode/issues/396#issuecomment-315079618 for more details on our approach.

**Note:** to see the workspace name in the window title (helps for testing), configure `"window.title": "${activeEditorShort}${separator}${rootName}"`

**Basics**
Most workspace related operations center around a new submenu under the file menu:

![image](https://user-images.githubusercontent.com/900690/28329168-25e080a4-6be9-11e7-826d-0d82d2ac5607.png)

Try to work with multi root workspaces and play around with the available actions. Transition between empty workspaces, single folder workspaces and multi-root workspaces. Some things to keep an eye on:
* explorer and search operations work as before in any of the contexts
* you can save "Untitled Workspace" to some location on disk and open them from there
* saving an untitled workspace works without requiring a window reload
* you can switch saved workspaces via `File > Open Recent` as well as the recently opened picker (F1 `>open recent`)
* you can add and remove root folders from a multi-root workspace
* you see that you are inside a workspace by a new status bar color as well as the workspace name showing up in the explorer section for folders (only in our default dark and light theme)
* workspaces that are opened will restore in the same way as folder do (you can set `window.restoreWindows: all` to restore multiple windows)
* debugging (node.js and extension host debugging) work as before

**Untitled Workspaces**
Workspaces that are not saved are called "Untitled Workspace". Verify:
* you get asked to save an untitled workspace when you load something else into the window or when you open a second window and close the first window with the untitled workspace
* all of the actions from the question dialog work
* untitled workspaces (not just the last active window but all windows) restore properly the next time you start up

**Data**
Once you are in a workspace context, we use the workspaces identifier to associate:
* UI state (e.g. the files you have opened as tabs)
* hot-exit state (e.g. dirty files you left dirty when quitting)
* extension storage (a location on disk where extensions can store data via the [`ExtensionContext.storagePath`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3513) API)

Verify:
* UI state you have inside a workspace is restored next time you open it
* dirty files are restored when you quit and reopen the workspace
* extensions have a stable `ExtensionContext.storagePath` location per workspace

## Settings
Once you are in a workspace context, workspace settings are no longer stored within the `.vscode` folder, but within the workspace file. 

**NOTE:** Opening workspace settings in a Multi-root workspace currently shows the complete workspace config file. To show only Settings, is pending for next week.

**Verify:**
* Defining workspace settings applies to whole workspace as usual.
* Defining folder settings applies to resources under that folder. Currently following resource settings are supported.

```
editor.*
files.exclude
files.trimTrailingWhitespace
files.insertFinalNewLine
files.encoding
files.autoGuessEncoding
files.watcherExclude
search.exclude
```

* Intelli-sense in workspace settings works.
* Edit actions in Default Settings works correctly in all targets.
* Actions to open Folder settings in Command Pallette.

**Comment by glarue** [comment]
Sorry in advance if this is the wrong place to put this question, but is there any way to achieve the following functionality?

I have folder A and folder B, both under separate git repos. I open file A1 from folder A and file B1 from folder B. When I am editing A1, git is processed via folder A; when editing B1, git switches to folder B.

**Comment by bpasero** [comment]
@glarue currently not but we are working on SCM support for multi root scenarios.

**Comment by bpasero** [comment]
@isidorn @weinand @chrisdias todays insider build should be good to go for testing 👍

**Comment by sandy081** [comment]
@isidorn @weinand @chrisdias Please update to latest insiders for testing. Thanks.

**Comment by bpasero** [comment]
@weinand @isidorn @chrisdias thanks so much for taking the time to test, you found awesome bugs ❤️
