### ISSUE TITLE
Whitespace added after Commenting and Uncommenting in HTML, CSS

### ISSUE THREAD

**Issue by sarthak7gupta** [Microsoft/vscode#30729]
- VSCode Version: 10.14.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. I have only tried it HTML and CSS. Probably for other file types, too.
2. Comment a line by CMD+/, then uncomment using the same key combination.
3. You will notice a white space added to start and end of the part commented.
4. Checked with disabling all extensions, too.

**Comment by cleidigh** [comment]
@rebornix 
Duplicate of #30656 
Fixed with PR #30818 
All Languages
