### ISSUE TITLE
Feature Request: IntelliSense for require(path(...))

### ISSUE THREAD

**Issue by FloEdelmann** [Microsoft/vscode#30725]
IntelliSense captures definitions from external modules when they are imported like this:

```js
require('../path/to/module.js')
```

However, when the `path` module is used, it doesn't:

```js
require(path.join(__dirname, '..', 'path', 'to', 'module.js'))
```

Since this syntax is preferred for cross-platform applications, it would be great to see it supported!

**Comment by mjbvz** [comment]
This is as-designed. Our Js and TS language features use static analysis for performance and reliability reasons. Understanding imports that use expression like the above would require significant effort that is just not worth it.

What are your use cases for this? There may be alternative approaches that work

**Comment by FloEdelmann** [comment]
I did some research again and apparently, one can always use forward slashes and the correct file will be `required`: https://stackoverflow.com/questions/9756567/do-you-need-to-use-path-join-in-node-js

So I should rather change *my* code ;)
