### ISSUE TITLE
Workspace files.excludes for sub-folders no longer works

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#30723]
- VSCode Version:1.14.0
- OS Version:Win 10

Filtering sub-folders via workspace files.excludes no longer works. This worked correctly in previous version.  

```
  "files.exclude": {
    "folder/subfolder/": true,
  }
```

<img width="815" alt="capture" src="https://user-images.githubusercontent.com/3818866/28220082-cc8326f0-6883-11e7-9cdf-fc5d696920eb.PNG">

**Comment by bpasero** [comment]
Fixed on master and 1.14 recovery.

**Comment by isidorn** [comment]
@bpasero thanks for fixing

**Comment by mfrost66** [comment]
@bpasero not actually fixed in 1.14.1.  Maybe a regression test is in order...

**Comment by bpasero** [comment]
@mfrost66 1.14.1 does not include the fix

**Comment by DanTup** [comment]
@bpasero 

> 1.14.1 does not include the fix

This is a bit confusing - the link in the release notes that says "Update 1.14.1: The update addresses these issues." links to [this page](https://github.com/Microsoft/vscode/milestone/47?closed=1) which includes this case. Should it be in another milestone?

**Comment by bpasero** [comment]
@gregvanl fyi that is a bit unhappy

**Comment by mfrost66** [comment]
1.14.1 does not fix the issue for me.  Unless you are maintaining that you did in fact fix it in 1.14.1 ( I can't tell from your responses), can we re-open the issue until its resolved?

**Comment by bpasero** [comment]
Guys, wait for 1.14.2 release 👍

**Comment by bpasero** [comment]
Or even better, start to use insiders where the fix is in: http://code.visualstudio.com/Download#insiders

**Comment by DanTup** [comment]
@bpasero No rush for the fix from me, I was just raising that it's a bit confusing that the release notes links are showing cases as fixed that aren't. I presume it's because you're using this milestone for both recovery releases. Whether it's worth changing things to fix this (eg. having two recover release milestones) I don't know; I just wanted to make sure you understood why people are thinking cases are resolved in 1.14.1 that are not :-)

**Comment by mfrost66** [comment]
@bpasero still not fixed in 1.14.2.  Confusing that the issue is closed and tagged as fixed in multiple release notes but not actually fixed. 

<img width="942" alt="capture" src="https://user-images.githubusercontent.com/3818866/29074874-61730cd0-7c16-11e7-84bb-bff125b6474d.PNG">

**Comment by roblourens** [comment]
That's a different issue, with search not handling patterns that end in / correctly. https://github.com/Microsoft/vscode/issues/30266#issuecomment-314576765 Can you try in Insiders?

**Comment by mfrost66** [comment]
Works in 13.1 and is exactly the original issue as posted.

**Comment by roblourens** [comment]
Here you are doing a search, originally you were seeing the files show up in the file explorer.

**Comment by mfrost66** [comment]
The submitted bug was that "files.excludes no longer works".  I attached an
image to visually show an example which happened to show the explorer as
that seemed like the simplest was to capture the problem.

If the team has a desire to split this into multiple issues reflecting the
various permutations of its brokeness, that's fine.  I don't personally
have the insight to do so.  But the current state of "closed" is not an
accurate reflection of "files.excludes for sub-folders no longer works" and
is confusing to anyone currently having trouble with the files.excludes
setting.
