### ISSUE TITLE
Do not use electron's remote in event handlers

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3072]
See #2829

**Comment by bpasero** [comment]
I have pushed changes to greatly reduce use of remote in the renderer. The only thing I left out for now is the context menu which I extracted into https://github.com/Microsoft/vscode/issues/3638. I pushed a change though to use a timeout of 0 to make sure that we are not using remote from event handlers.

Areas to verify:
* most importantly: the bug with pressing "Tab" getting wrong is not happening anymore
* toggle dev tools
* reload window
* mac: shows "represented" file name in window title area when opening files and removes it when closing last editor
* mac: window shows as "dirty" when having dirty files by drawing a black dot in the close button of the window and removes this dot when no more dirty files are present
* save dialog still works and shows up for dirty files when closing workbench or closing the working file
* going full screen, leaving full screen
* toggling menu bar visibility
* context menu still works (in trees, editor, dropdown "...")

**Comment by alexandrudima** [comment]
Nice!!

**Comment by alexandrudima** [comment]
I didn't start reviewing the commit, I trust you do the right thing. Thank you!

**Comment by bpasero** [comment]
I feel honoured ;)
