### ISSUE TITLE
UI always renders at DPI scale of primary screen, not current screen

### ISSUE THREAD

**Issue by DrTacoMD** [Microsoft/vscode#30733]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Have a hardware setup where your primary display is at a different DPI scale than your external
2. Launch VSCode and move the window to the secondary display

Expected:
App content renders at the DPI scale factor of the external display

Actual:
App content continues to render at the DPI scale factor of the original display. Here's an example where my primary display is at 100% but my secondary is at 225% (exaggerated slightly to make the problem extra obvious). Note the radical difference between the title bar and the entire rest of the UI:

![blurrycode](https://user-images.githubusercontent.com/4934719/28229826-20fbc7fe-6899-11e7-93bd-61d8554a33d5.PNG)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6196
