### ISSUE TITLE
Feature request: Shortcut for new terminal window

### ISSUE THREAD

**Issue by Hum4n01d** [Microsoft/vscode#30730]
- VSCode Version: Code - Insiders 1.14.0-insider (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-06T20:14:49.095Z)
- OS Version: Darwin x64 16.6.0

Hi, this is a feature request, not an issue so I’m deleting all of the boilerplate. 

I want to be able to open a new terminal tab via a keyboard shortcut. Right now I can do this:

![vscode new terminal](https://user-images.githubusercontent.com/17228477/28226790-3dcffc7c-688c-11e7-9df5-f489a15f13dc.gif)

I would like to achieve the exact same thing via a keyboard shortcut. Can this be implemented? Thanks for the awesome editors by the way.

**Comment by Tyriar** [comment]
ctrl+shift+` should do this now

**Comment by Hum4n01d** [comment]
Ok, that works but why isn’t it in the command panel?

**Comment by Hum4n01d** [comment]
Apparently it is. Strange. Thank you!

**Comment by Tyriar** [comment]
😉
