### ISSUE TITLE
Workspaces change wiped "Open Recent..." history

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30737]
After the insiders upgrade to e026e5e8b891075cef13ca6ec0cad452f28b66d0, my "Open Recent" history was gone, I assume from multiroot work. Just a little annoying but we should try not to do that for upgrading 1.14 -> 1.15

**Comment by bpasero** [comment]
@roblourens this should have been a one time glitch when going from one particular insiders build to another and not reproduce on a fresh install. I just verified that it is not lost when going from stable to insiders using the `--user-data-dir` trick. Please confirm.
