### ISSUE TITLE
Jsdoc tooltip showing raw tags

### ISSUE THREAD

**Issue by madcampos** [Microsoft/vscode#3073]
The tooltip is showing all the jsdoc information except for the `@param` tags.
Eg. jsdoc:
```javascript
/**
 * Filters a path based on a regexp or glob pattern.
 * @param {String} basePath The base path where the search will be performed.
 * @param {String} pattern A string defining a regexp of a glob pattern.
 * @param {String} type The search pattern type, can be a regexp or a glob.
 * @param {Object} options A object containing options to the search.
 * @return {Array} A list containing the filtered paths.
 */
function pathFilter(basePath, pattern, type, options){
//...
}
```
The tooltip shows like this:
![Tooltip](http://imgh.us/error_18.png)

I'm using the january version without Salsa enabled.

**Comment by egamma** [comment]
Also the type paramater of the `type` argument is shown as `any` in the parameter hints

![image](https://cloud.githubusercontent.com/assets/172399/13148686/a2192f3a-d65e-11e5-9bc6-4e972b63acb8.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7136
