### ISSUE TITLE
application stops working when a git pull or git checkout is done in git bash.

### ISSUE THREAD

**Issue by edwinabraham1** [Microsoft/vscode#30731]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
angular2-snippets|dan|1.0.15
tslint|eg2|0.16.0
Angular2|joh|2.3.3
TypeScriptImport|kev|1.17.0
vscode-extension-auto-import|mop|1.3.3
vscode-format|rya|0.0.6
git-merger|sha|0.3.2
autoimport|ste|1.2.2
sublime-commands|Zar|0.1.0

---

Steps to Reproduce:

1. simply checkout different branch or pull in git bash.
The VS application hangs and stops working. Will have to close VS code and gives a pop up with options like re-open. And yes, we have to re-open the VS code again.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
What are your machine specs? How large is your repository? How many active changes?

**Comment by edwinabraham1** [comment]
It is not dependent on changes. 16gb ram, i7 processor, 64bit windows10 os.
Size repository is less than 20mb.

On Jul 17, 2017 2:56 AM, "João Moreno" <notifications@github.com> wrote:

What are your machine specs? How large is your repository? How many active
changes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/30731#issuecomment-315712703>,
or mute the thread

**Comment by joaomoreno** [comment]
Can you reproduce the same behaviour without using git? For example moving files/folders around using the Windows Explorer?
