### ISSUE TITLE
Snippset and emmet

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#30734]
- VSCode Version: 1.14.1
- OS Version: Windows 8.1 and Linux Ubuntu Gnome 16.04.2 LTS

Steps to Reproduce:

1. http://s24.postimg.org/dgjx73oxh/screenshot_10.png when I press enter it do http://s24.postimg.org/fmitfchrp/screenshot_11.png instead http://s24.postimg.org/brffcrylx/screenshot_12.png
2. When I use emmet and confirm it, it do new line instead of replace cursor to end of line. (In older version it work correctly, and it's faster and easyer to use it as in old version)

Reproduces without extensions: Yes/No

Extension: none.

**Comment by ramya-rao-a** [comment]
@ghost what is the abbreviation that you tried to expand?
Is it a custom snippet? Or an emmet abbreviation?
