### ISSUE TITLE
Negative look-ahead regexp doesn't work in search

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#30735]
- VSCode Version: 1.14.1
- OS Version: Windows 7

Steps to Reproduce:

1. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>
2. Type in `(?!Studio Code)Studio`. Press <kbd>Enter</kbd>
3. Error tooltip: `Error parsing regex near '(?!' at character offset 2: Unrecognized flag: '!'. (Allowed flags: i, m, s, U, u, x.)` 
4. Sometimes the search will actually work regardless (it's a valid JavaScript RegExp)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected as some features aren't supported by ripgrep, the tool that powers search: #29112

**Comment by ctsstc** [comment]
Did this work previously? I actually have a screenshot of this working back in february. Now I'm back trying to run my regex from an old story and running into this issue.

**Comment by vp2177** [comment]
@ctsstc Is it possible you had the matching files already opened? It works on opened files, but doesn't find matches in one's that aren't open in an editor tab

**Comment by roblourens** [comment]
It did work pre-ripgrep @ctsstc. Also in open files.

A workaround is setting `"search.useRipgrep": false`, but don't count on it existing forever.

**Comment by bric3** [comment]
> This is expected as some features aren't supported by ripgrep, the tool that powers search: #29112

From a user perspective it isn't expected.
