### ISSUE TITLE
Unexpected folder and filename case sensitivity in search

### ISSUE THREAD

**Issue by yves-dolce** [Microsoft/vscode#30739]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
githistory|don|0.2.1
gitlens|eam|4.3.1
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
code-spell-checker|str|1.2.1
gitblame|wad|1.11.3

---

Steps to Reproduce:
*  Windows OS
*  Make sure you have a file under a folder named Abc. With an uppercase A at the beginning
*  Search for a word that file contains but in the files to include field, specify `**/abc/*.*`
* It won't find it! To find it you have to look for `**/Abc/*.*`

This is unexpected and annoying to say the least: folders and files names are case insensitive on Windows.

Reproduces without extensions: **Don't know**

**Comment by roblourens** [comment]
#30224
