### ISSUE TITLE
After uploading to version 1.14.1 I can no longer used command prompt from the editor

### ISSUE THREAD

**Issue by Bandito11** [Microsoft/vscode#30743]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|0.0.2
ionic3-vs-ionView-snippets|dan|1.0.1
python|don|0.6.7
tslint|eg2|0.16.0
ionic2-vscode|jgw|1.0.0
docthis|joe|0.4.7
Angular2|joh|2.3.3
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
debugger-for-edge|msj|0.4.1
ionic2-snippets|oud|1.0.0
vscode-docker|Pet|0.0.16
sass-indented|rob|1.4.1
code-spell-checker|str|1.2.1
nativescript|Tel|0.7.2
cordova-tools|vsm|1.2.7

---

Steps to Reproduce:

1. updated from the editor the Version 1.14.1 of VS code
2. Tried to use the terminal (PowerShell) from vscode with no luck. I restarted the computer, restarted the editor with no luck. 
3. Forgot to add what happens is that it doesn't see any of the node related commands. Ex. node, gulp, ionic etc...
4. When starting powershell from the windows 10 start menu it works as it should. 

Reproduces without extensions: Yes/No

Yes

**Comment by praveenpuglia** [comment]
Did you see any errors in the integrated terminal?

**Comment by Bandito11** [comment]
Only that it couldn't recognize node. 

After deleting and reinstalling everything work as expected. 

The issue was only when updating to that version of  code.

**Comment by chrmarti** [comment]
Sounds like a problem with the update. /cc @Tyriar

**Comment by joaomoreno** [comment]
I'm glad the issue got resolved after reinstallation. Sorry about that.
