### ISSUE TITLE
[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. 

### ISSUE THREAD

**Issue by myGitHubLxd** [Microsoft/vscode#30745]
[Error] "Could not debug. Unable to set up communication with VSCode react-native extension. Is this a react-native project, and have you made sure that the react-native npm package is installed at the root?"

- VSCode Version:版本 1.14.1 (1.14.1)
- OS Version:macOS 10.12.5 (16F73)
我已经安装了npm,并且用命令可以跑起来，Xcode也可以跑起来，就是VScode起不来。
Steps to Reproduce:

1.Open my project.
2.click run.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-react-native#475
