### ISSUE TITLE
Fonts in Extensions dont update when changing themes

### ISSUE THREAD

**Issue by changavila** [Microsoft/vscode#30747]
- VSCode Version: Code - Insiders 1.15.0-insider (47a49c7fb8138fd27e2a95259ae96e9ac49a65a5, 2017-07-14T07:45:27.194Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm-script|eg2|0.2.0
search-node-modules|jas|1.1.1
vscode-icons|rob|7.10.1
code-settings-sync|Sha|2.8.2
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open Any Extension
2. Change Theme
3. Check Fonts (Please refer to attached GIF)

![2017-07-15_12-52-11](https://user-images.githubusercontent.com/13307287/28236633-29c3816e-695d-11e7-857e-f88e8bca0d96.gif)

**Comment by joaomoreno** [comment]
#25370
