### ISSUE TITLE
Support than an extension can be labeled as a 'Trial'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3074]
Extracted from #3036 submitted 

From @ArtemGovorov
>Though it'd be great to be able to specify a 'Trial' label for the extension like they can in Visual Studio marketplace:

![screen shot 2016-02-16 at 10 22 07 pm](https://cloud.githubusercontent.com/assets/979966/13076130/ec22f070-d4fb-11e5-9c3b-1a300c12b4e4.png)

**Comment by waderyan** [comment]
Is preview satisfactory? 

![image](https://cloud.githubusercontent.com/assets/2449568/18853426/eaad95c6-83f9-11e6-8918-a731bba1ca3f.png)

**Comment by ArtemGovorov** [comment]
@waderyan It is, thanks! I didn't manage to make it work for our extension yet, but it's probably a separate issue.

**Comment by waderyan** [comment]
You can set `"preview": true` in the extension's `package.json` file to have it work.
