### ISSUE TITLE
Allow to create multiple folders from the explorer at once

### ISSUE THREAD

**Issue by lyquocnam** [Microsoft/vscode#30744]
Hi author, i think we can simple create multi folders with "/" when input the name of folder.
ex:
- When click "New Folder"
- Enter: "src/components/module1"....
It will create a tree of Folders src>components>module1.

If this ok, i think we can expand this:
-> Create a file and multi folders
click new file -> enter: "src/component/app.js"
it will create src>components>app.js file and create folder tree if not exist.

Create multi file and multi folder
enter: "src/components/app.js, main.js, router.js"
it will create app.js file, main.js file, router.js file in src>components  folder.

i think this good feature for more comfortable.

**Comment by praveenpuglia** [comment]
I think the first part about multifolders mean creating folders and files that do not already exist by analyzing the path the user provides. Exactly like how Advanced New File(ANF) work in Sublime Text.
https://www.youtube.com/watch?v=ZXvSMeNS91Q

I think it'll make a good extension like ANF is for sublime text.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12893
