### ISSUE TITLE
Can't drag-and-drop file into directory

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#30741]
- VSCode Version: 1.15.0-insider
- OS Version: Linux Mint 18.1

Steps to Reproduce:

1. Drag file
2. Hover over a directory. It is highlighted as if you're about to drop the file into the directory.
3. Release the mouse. Nothing happens.

Reproduces without extensions: Yes

This works fine in vscode 1.14.0.

**Comment by bpasero** [comment]
@andy-ms are you on latest insiders? I think we fixed that issue.

**Comment by jens1o** [comment]
Since when the `Report: Issues` won't leave a watermark on what git commit it's based on @bpasero ?

**Comment by bpasero** [comment]
@jens1o it works for me, I just tried.

**Comment by andy-ms** [comment]
You're right. It was broken in the latest Linux Mint release(Commit 74f5073c54f1139d2fb0eccb251cae5ed6e8215b, Date 2017-07-12T05:10:47.810Z), but is fixed if I download directly from the website (Commit 56a5bf1724f3b882e149a3e7a24e6105a7b837c2, Date 2017-07-13T06:24:22.570Z). Thanks!
