### ISSUE TITLE
IntelliSense failure for version 1.14+

### ISSUE THREAD

**Issue by ifzm** [Microsoft/vscode#30751]
I upgraded the version and found the failure of intelliSense (
return to 1.13.1 version after the return to normal.
OS：Ubuntu 16.04

![image](https://user-images.githubusercontent.com/12740295/28237621-19465e06-6976-11e7-80ce-525cf3b883bf.png)
- vsc version：1.13.1

![image](https://user-images.githubusercontent.com/12740295/28237643-cb62b2c4-6976-11e7-9efc-305bdf95f43f.png)
- vsc version：1.14.1

**Comment by Majirefy** [comment]
#30716 See this, hope will fix soon.

**Comment by ifzm** [comment]
I can use the windows under normal, is it environmental problems?

**Comment by mjbvz** [comment]
This is likely a duplicate of one of a few other bugs. @ifzm, can you please:

1. Open the output panel and go the `TypeScript` section. Do you see any error messages printed in there?
2. Run the`Toggle Developer Tools` command and open the developer console. Do you see any errors printed in there?

**Comment by mjbvz** [comment]
Please try VScode 1.14.2 which was just released. It includes TS 2.4.2 which fixes a number of issues that could be causing this

**Comment by ifzm** [comment]
After the update is normal, great 👍
