### ISSUE TITLE
Can not update language specific configuration

### ISSUE THREAD

**Issue by michalyao** [Microsoft/vscode#30756]
- VSCode Version: 1.14.1 
- OS Version: macOS 10.12.5

I have developed a markdown extension. To improve experience, I want to set the `markdown quickSuggetions: true` as default when activating my extension. Here is my code, but the configuration did not update correctly. Other settings, such as `files.eol` works fine. Did I miss anything? Or the API does not support modify?

``` js
const markdownSettings = vscode.workspace.getConfiguration("[markdown]");
markdownSettings.update("editor.quickSuggestions", true, true);
```

**Comment by sandy081** [comment]
API currently does not short cut the values. You have to update back with the same value structure  that you receive in `getConfiguration`. In this case the, update call should be

```
markdownSettings.update("[markdown]", {"editor.quickSuggestions": true}, true);
```

**Note** that, value should be complete not the diff.

**Comment by michalyao** [comment]
Thanks a lot, it works.
