### ISSUE TITLE
Allow extensions to contribute margin decorations

### ISSUE THREAD

**Issue by MacFlurry** [Microsoft/vscode#30753]
Hello,

is it possible to add php symbol like class overrode , extend method like this : 

![capture d ecran 2017-07-15 a 10 17 41](https://user-images.githubusercontent.com/8139322/28237858-9373a3c4-6948-11e7-81cb-906469fd51ef.png)

![capture d ecran 2017-07-15 a 10 17 59](https://user-images.githubusercontent.com/8139322/28237859-95e432f4-6948-11e7-826c-f4956b9e851a.png)

![capture d ecran 2017-07-15 a 10 22 37](https://user-images.githubusercontent.com/8139322/28237862-97ec834e-6948-11e7-9681-08a05d0cd88d.png)

![capture d ecran 2017-07-15 a 10 25 35](https://user-images.githubusercontent.com/8139322/28237863-9a765d4c-6948-11e7-8970-b1bd3eba5c9b.png)

![28234864-e0dd7458-6904-11e7-875b-70dac4d85f80](https://user-images.githubusercontent.com/8139322/28237864-9e584a9c-6948-11e7-8ff1-5ebc3a091dce.png)

Best regards,

MF

**Comment by roblourens** [comment]
Not exactly like that, but an extension could probably show similar decorations.

**Comment by MacFlurry** [comment]
hello,

Do you know which extension could do that ?

**Comment by roblourens** [comment]
I guess VS Code would have to add support for an extension to add icons like this.

**Comment by roblourens** [comment]
Actually, I guess you could do this with text decorations currently. Not as part of the language server protocol but the extension host could add them.
