### ISSUE TITLE
Automatic tsconfig.json tasks don't use local `tsc`

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#30754]
VSCode 1.14 introduced [autodetection and building of `tsconfig.json` files](https://code.visualstudio.com/updates/v1_14#_simpler-building-typescript-using-tasks) and as shown in that feature description, the task should correctly pick up `node_modules/.bin/tsc` instead of global `tsc`. However, I'm not seeing this. I get this:

```
> Executing task: tsc -p "c:\Dev\my-project\subproject\tsconfig.json" <
```

instead of:

```
> Executing task: node_modules/.bin/tsc -p "c:\Dev\my-project\subproject\tsconfig.json" <
```

Maybe it's because my `tsconfig.json`s are nested and I don't have any project-level `node_modules`? My workspace looks like this:

```
- my-project
    - subproject
        - node_modules
        - tsconfig.json
    - subproject2
        - node_modules
        - tsconfig.json
```

**Comment by mjbvz** [comment]
Yes, we currently only check the root folder's `node_modules`. To fix this I think we should add logic to walk back up from the tsconfig path while checking for `node_modules`, or at the very least check next to the `tsconfig` as well
