### ISSUE TITLE
Horrible debugging hell

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#30752]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-theme-onelight|akamud|2.0.2|
|vscode-npm-script|eg2|0.2.0|
|task-master|ianhoney|0.1.39|
|quicktask|lkytal|2.8.1|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.6|
|Material-theme|zhuangtongfa|2.9.3|;

---

Steps to Reproduce:

1. Have a go program
2. Run a goroutine
3. Block the main routine
4. Break in the goroutine
5. Try to step through the goroutine

---

When the main routine is blocked and I try to step through a 'worker' goroutine, on **EVERY SINGLE BLEEPING STEP** VSCode switches the currently viewed frame to the main routine. So on *every step* I have to reselect the worker goroutine in the 'call stack' panel. It's quite painful.

Maybe this is an issue with delve? Not sure.

**Comment by firelizzard18** [comment]
Update: since the main thread is blocked, I can step twice and it goes back properly to the goroutine. So at least there's that.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-go#1091
