### ISSUE TITLE
Ubuntu Unity: VSCode doesn't restore windows after Quit from Launcher

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#30755]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Ubuntu 17.04 Unity, Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
codeception-snippets|die|0.0.4
githistory|don|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
AWK|lug|0.0.2
ftp-sync|luk|0.3.3
code-beautifier|mic|1.7.2
mads|mir|0.0.5
HTMLHint|mka|0.3.3
vscode-icons|rob|7.10.1
code-spell-checker|str|1.2.1

---

**Steps to Reproduce:**

1. Open VSCode using shortcut in Unity Launcher
2. Set `"window.restoreWindows": "folders"` or `"window.restoreWindows": "all"` in your user settings
3. Open folder A
4. Open folder B
5. Close VSCode using the action Quit in Launcher:
![fayngjtens](https://user-images.githubusercontent.com/12584138/28238088-98fc37da-694c-11e7-9bd6-09740329e2ea.png)
6. Open VScode again using shortcut in Unity Launcher

**Expected result:**
- the windows with the folders A and B are restored

**Actual result**
- no window is restored, you get only an empty window

**Note:** If you close VSCode using the shortcut `Ctrl + Q`, the windows are restored well.

**Comment by bpasero** [comment]
I can reproduce. I can only assume that maybe a "Close All Windows" command is executed instead of quit.

**Comment by bpasero** [comment]
This is the same as https://github.com/Microsoft/vscode/issues/30377
