### ISSUE TITLE
TypeScript types autocomplete stopped working

### ISSUE THREAD

**Issue by ddwwcruz** [Microsoft/vscode#30763]
Autocomplete on types doesn't work in typescript files.

- VSCode Version: 1.14.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open typescript file
2. Declare the type of a variable

Reproduces without extensions: Yes

**Comment by cantsdmr** [comment]
This problem exists on Windows 10 too, even for JavaScript.

**Comment by Zorbing** [comment]
This might be related to #30716.

**Comment by hanpari** [comment]
I can confirm on Win10. 
I tried insider version and disabled all extensions. 
It is not working at all.

For instance:

function (x:st...) should bring string but nothing has happened.

**Comment by MartinHaeusler** [comment]
Can confirm this for VSCode 1.14 on Windows 10 too. It's super annoying, I hope this gets fixed soon... Only types seem to be affected though, other autocompletions (e.g. variable names) work just fine.

**Comment by Ikderrr** [comment]
I also confirm this, Windows 10 with VS Code 1.14.1

**Comment by SDSLeon** [comment]
I also confirm this, Windows 10 (build.15063) with VS Code 1.14.1 or VS Code 1.15-insiders and typescript 2.4.1 or 2.4.2-insiders.

For typescript 2.3.4 all works fine.

**Comment by mjbvz** [comment]
This is a duplicate of #30580. I'm working with the TS team to get a fix out soon
