### ISSUE TITLE
Extensions can break other extensions' validation schemas

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#30762]
Steps to Reproduce:

1. Create a new extension
2. Add this block to the `contributes` section of `package.json`
```
"jsonValidation": [
    {
        "fileMatch": "settings.json",
        "url": "badurl"
    }
],
```
3. Launch the extension
4. Go to `settings.json`
5. Try to get intellisense for ANY settings

**Expected:** Existing intellisense will still work
**Actual:** No intellisense works

There are two problems here:
1) It's problematic that extensions can clobber other extensions validations rather than their results being merged. It's doubly problematic that an extension can break built-in validations

2) It's tedious to include a complex configuration schema inside the package.json but the only documented way of registering a schema that I've found is the way above. I can try to do it in a way that will only contribute the specific section I want, but given the damage that can be caused if I mess up, I would rather not, at least not without clear documentation on how to do it properly. I would actually prefer to reference it directly in the contributes section using something like what I have below, but the local path would need to be resolved by VS Code to the extension installation path.
```
"contributes": {
  "configuration": {
    "properties": {
      "extension.configuration": {
        "$ref": "config-schema.json#/schema-id"
      }
    }
  }
}
```

**Comment by aeschli** [comment]
The schemas are actually merged, not replaced. But I suspect the badurl is the problem. 

For configuration we need the real schema right there as we also use it to get the default values.

**Comment by aeschli** [comment]
Schemas are or'ed as long as they use the same file pattern. VSCode uses a full URI when doing the schema association, so your contribution does not match the internal one.
Yours happens to be first in the list, so it wins.

I changed the code to combine all matching schemas.

However, your use case is not supportted. Your settings must only use the configuration contribution point. You must not make any assumptions on how the underlying schema is created. $ref should only use external refs. Contributing a schema to settings.json is not valid, asks for trouble and is considered a user / extension-developer error.
