### ISSUE TITLE
Intelisense for "import" statements

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode#3076]
Hello, is it possible to add intellisense for import statements? Either disaply all files in the project that match the pattern relative to the current file, or display whatever is in the path.

E.g. 

"../" + ctr+space  will pop whatever is in the parent directory 
"my" + ctrl + space will pop up all files that contain "my" showing path relative to the currrent file

**Comment by egamma** [comment]
Moving to typescript

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7135
