### ISSUE TITLE
Follow link in terminal results in save dialog

### ISSUE THREAD

**Issue by MartinNuc** [Microsoft/vscode#30761]
- VSCode Version: 1.14.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. settings: `"editor.multiCursorModifier": "ctrlCmd"`
2. open integrated terminal
3. run `echo https://github.com`
4. alt+click on the link
5. save file dialog appears with filename `download.html`

![screen shot 2017-07-15 at 14 15 27](https://user-images.githubusercontent.com/681176/28239252-142b2266-6968-11e7-8429-096ff3132931.png)

Expected behaviour: it opens link in a browser

> Also the shortcut used to be CMD+click and not ALT+click. I couldn't find where to change it back :-(

This is actually caused by `editor.multiCursorModifier` settings. I was not aware of that when I created issue.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Hmm, I can't reproduce, what is your default browser and what is the active program that shows up in the top-left of the screen when you have the save dialog focused?

**Comment by MartinNuc** [comment]
@Tyriar my default browser is Safari. When I focus download dialog the active program remains `Code`.

**Comment by Tyriar** [comment]
I'm guessing this is because I just defer to Electron to handle clicking an `<a>` properly which for some reason isn't behaving in your case. The fix would probably be to explicitly handle opening of the URL at https://github.com/Microsoft/vscode/blob/b4d4d0128fe08798d7fd684d96c0819389eb6bf6/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L75 in the same way that the editor does it.

**Comment by cleidigh** [comment]
@Tyriar 
Seems like something different to work on. Shall I pick this up?

**Comment by Tyriar** [comment]
@cleidigh sounds good :+1:

**Comment by cleidigh** [comment]
@Tyriar 
Clicking links in the integrated terminal on Windows 7 works as expected.
Have to reproduce on OS X, seems surprising that would be platform dependent...

**Comment by MartinNuc** [comment]
@cleidigh If there is anything you need feel free to contact me.

**Comment by cleidigh** [comment]
@MartinNuc 
Unfortunately I cannot reproduce on OS X Sierra either. I tried to code 1.14.1 as well as several insiders versions including a 1.15.0 from a week and a half ago. all of these will launch a browser, either Firefox or Safari.

What is particularly suspicious is that you reference and your screenshot shows Alt + Click for the link pop-up. On my OS X set up it pops up as Cmd+Click as you assumed it should.

@Tyriar Correct me if I am wrong, but Alt as a key should never be valid on OS X, the meta- key should be Command.  You cannot set a key binding for the term link, but you can for the editor. I am wondering if there is something corrupted with your key bindings.  

Do you have an Insiders build installed? I would try to install one, it will use a totally separate configuration set up that will not change or conflict with your Code install.
Also look at your key bindings, the meta- key should always be Command.

**Comment by MartinNuc** [comment]
@cleidigh Your suggestion actually lead to solving my issue.

I had in my user's settings the new

`"editor.multiCursorModifier": "ctrlCmd"`

Which apparently moved opening links to ALT key. This is described in [changelog](https://code.visualstudio.com/updates/v1_13#_add-multiple-cursors-with-ctrl-cmd-click):

```The Go To Definition and Open Link gestures will also respect this setting and adapt such that they do not conflict. For example, when the setting is ctrlCmd, multiple cursors can be added with Ctrl/Cmd+Click, and opening links or going to definition can be invoked with Alt+Click.```

However opening link with ALT key results in download dialog. When I remove this setting both links from editor and terminal open as expected.

**Comment by cleidigh** [comment]
@MartinNuc 
Full disclosure I am not a Mac user normally, though I do have an airbook with Sierra.  I cannot use OS X directly I have to use VNC and Dragon for voice operation as I am disabled. This sometimes makes keyboard issues difficult to assess.  
What I am curious about is how the alt key would be different than Command ?
in any event it's good you got it working.
I assume this can be closed?

**Comment by Tyriar** [comment]
When `"editor.multiCursorModifier": "ctrlCmd"` is set, alt+clicking should open the link, ctrl+click should do nothing. When it's not set, ctrl+click should open the link, alt+click should do nothing.

**Comment by MartinNuc** [comment]
Ah, yes option is alt :-)

Still I think when user uses `"editor.multiCursorModifier": "ctrlCmd"` ALT-click on link should open links from terminal and not download dialog.

Should I update steps to reproduce of this issue or should I make a new one and close this one?

**Comment by Tyriar** [comment]
@MartinNuc no this issue is fine

**Comment by cleidigh** [comment]
@Tyriar 
So I should still try and determine why the download link is opening, correct?
Also , shouldn't the pop-up be "Option+ Click" as opposed to "Alt + Click" when on OS X?

**Comment by Tyriar** [comment]
Yes, we need to figure out why the download link is opening.

Option and alt are the same key, typically both words are features on the key. We also use alt elsewhere.

**Comment by cleidigh** [comment]
@MartinNuc 
I set "editor.multiCursorModifier": "ctrlCmd" on my OS X Sierra system:
- hover over a terminal linked, pop-up is "Alt + Click"
- do Alt+Click - no action (should launch link)
- The same behavior occurs on Windows
- according to discussion this  should launch links on both platforms (a bug but slightly different than your problem , possibly related)

Is it possible you have some key binding conflict? can you comment everything out and see what happens?

**Comment by MartinNuc** [comment]
Tried to comment all my custom settings and keybindings, restart and the behaviour was same.

I also tried `Code - Insiders` and download dialog is still opening.

I updated steps to reproduce in the first post.

**Comment by cleidigh** [comment]
@MartinNuc 
Thanks for trying that out.

Good news , I can reproduce the problem ! In fact it does the same thing on Windows !
It will be much easier for me to debug this way
and I think I have some ideas about what's going on.
Stay tuned...

**Comment by cleidigh** [comment]
@Tyriar 
Your prior comment surmising that the default electron link handling might be an issue
was spot on. The default chromium behavior for clicking on links with Alt is to save the link contents
thus the save dialog - doesn't matter the platform.

Have a working fix:
I created a hypertext link handler and bypassed the default behavior in terminallinkhandler.
I should be able to cleanup and post a PR by tomorrow afternoon in case you want to include in Sunday's build.
Cheers

**Comment by cleidigh** [comment]
@MartinNuc 
@Tyriar 
Addressed with PR #31263
