### ISSUE TITLE
Build task does not stop launch with Tasks 2.0.0

### ISSUE THREAD

**Issue by zeroskyx** [Microsoft/vscode#30766]
VSCode 1.14.1
C# 1.11.0

When moving from Tasks 0.1.0 to Tasks 2.0.0 an unsuccessful build no longer displays the following message:
![image](https://user-images.githubusercontent.com/7782966/28240356-c4f9d624-6980-11e7-8cc6-38fafd4c52b8.png)

Instead, the previously generated code is executed and the debugger attached.

Steps to reproduce:
Create a new C# console application:

    dotnet new console

Allow VSCode to add tasks.json and launch.json.
Create an error in the code (like CConsole.WriteLine) and launch it. This displays the error and does NOT launch a debug session.

Then open tasks.json and modify to

    "version": "2.0.0"

Build and launch again. This time, the terminal displays the error but still attempts to execute the previous build output.

A minimal solution is attached to this post:
[TasksRepro.zip](https://github.com/Microsoft/vscode/files/1150422/TasksRepro.zip)

**Comment by dbaeumer** [comment]
I can reproduce this. The underlying problem here is that the terminal swallows the real exit code. See https://github.com/Microsoft/vscode/issues/31965
