### ISSUE TITLE
Snippet placeholder index incorrect after using 2+ snippets in a row that each end with a placeholder

### ISSUE THREAD

**Issue by zvinless** [Microsoft/vscode#30769]
- VSCode Version: 1.14.1
- OS Version: macOS Sierra 10.12.5

![snip](https://user-images.githubusercontent.com/24303763/28240960-a4e1252c-693f-11e7-972f-d7e836404c70.gif)

Steps to Reproduce:

1. Add this snippet to any language (I used Batch but the language doesn't seem to matter)
```json
"Test": {
	"prefix": "test",
	"body": [ "test ${1:replaceme}" ]
}
```
2. Open a fresh file in the snippet's language
3. Type "te" and hit return to activate the snippet
4. Type a value to replace the placeholder
5. Hit return to go to the next line
6. Repeat steps 2-5
7. Repeat step 3
8. Observe that your curser is now AFTER the placeholder and the placeholder isn't selected
9. Optionally continue repeating and observe that previous placeholders become highlighted unexpectedly

I expected that the snippets would continue to behave as they did for the first two lines. This issue also occurs when using a `CompletionItemProvider` in an extension to provide completions with `SnippetString`s. Note that if that there are any characters after the placeholder in the snippet, e.g. `"body": [ "test ${1:replaceme}_" ]`, the issue does not occur. 

EDIT: I tested this issue against version 1.15.0-insider, and the behavior is different, but it is still reproducible in the same way (fewer steps, actually). Let me know if a separate issue for that version would be helpful!

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Thanks for reporting, I can repro. I believe this because on Enter the placeholder gets expanded and what you insert is then actually a nested snippet, not a new snippet. Somewhere down the road we seems to get into trouble... I'll take a look
