### ISSUE TITLE
Allow editor inputs to opt out of showing icons based on resource

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#30768]
- VSCode Version: 1.14.1
- OS Version: Windows 10 Creators Update

Only Go icon show in Extensions:

![image](https://user-images.githubusercontent.com/27698189/28240871-6e0a685a-69b3-11e7-9d7e-82d35f7e00ca.png)
![image](https://user-images.githubusercontent.com/27698189/28240894-acd777da-69b3-11e7-84b3-8098032d6f65.png)
![image](https://user-images.githubusercontent.com/27698189/28240883-9660aeae-69b3-11e7-9a2f-33ddbe18abe9.png)

I tested with Seti-icons and vscode-icons.

**Comment by aeschli** [comment]
Ah, you mean the icon in the editor tab. Go happens to show go as the name ends with go.
Should probably better be no icon at all or a marketplace icon, if we have something like that.

**Comment by joaomoreno** [comment]
@bpasero @aeschli At least explain what I can do.

The resource label widget seems to believe that the name of an input is indeed a file name. That is wrong.

Here's my input:

https://github.com/Microsoft/vscode/blob/win32-bump64/src/vs/workbench/parts/extensions/common/extensionsInput.ts#L14

**Comment by bpasero** [comment]
@joaomoreno the tab widget currently simply asks the input for its resource (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L287) and then goes on and sets CSS classes. I guess in this case the extension luckily hits the GO extension and the icons shows up.

What is missing is a way for an editor input to indicate that it does not want to show icons. I think in this case it is fair to say that the tab should not show any icon.

**Comment by torn4dom4n** [comment]
Same issue with `vscode-pdf`:

![image](https://user-images.githubusercontent.com/27698189/32146195-233c5f62-bd06-11e7-9bfc-bb042ebbabea.png)
