### ISSUE TITLE
Allow disable of recent history in "go to file" command

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#30770]
I'd like the ability to disable showing the "recent history" portion of the file list in the `go to file` command, or at least collapsed so I don't have to visually scan to find the files list. 

For me, it quickly becomes both noisey (lots of false matches that I have to visually skip) and incorrect (debugger files, old files, etc).  

I find myself clearing the history multiple times daily to limit the noise.  The pattern matching as currently implemented is great, quickly gets me a short list of matching files, and the "recent" list just adds noise.

**Comment by karlhorky** [comment]
I suppose there hasn't been any update on this one in the meantime, right? Tried searching a bit, but didn't see anything that could be a solution yet...

**Comment by ensky** [comment]
+1, really annoying

**Comment by ryanaltvater** [comment]
+1

Really hoping for an update to this. Slows down the workflow of wanting to search current project files, but other projects' files (Recently Opened) are listed first (some times with the same names as files you're looking for in the current project).

**Comment by counterlogik** [comment]
+1, having major issues as I have to folders for a current project one for dev efforts and one for technical debt and constantly keep opening the wrong version of a file due to this feature

**Comment by drunksheep** [comment]
+1 also. 
Can be really counterproductive.

**Comment by twig** [comment]
+1 i keep going to the wrong files because of this due to similar filenames under different folders (main.html, component.jsx, style.scss, etc)

**Comment by bpasero** [comment]
I added a new setting `search.quickOpen.includeHistory` to control this. Default is `true`.

**Comment by bpasero** [comment]
**Verify:** if `search.quickOpen.includeHistory` is configured, typing into Cmd+P will not show any results from the "recently opened" bucket. The list of recently opened is still shown when initially opening quick open or having no search at all.

**Comment by utilityboy** [comment]
This will be a nice companion to this feature as well: https://github.com/Microsoft/vscode/pull/55752
