### ISSUE TITLE
issue javascript jsdoc @author

### ISSUE THREAD

**Issue by JStiller** [Microsoft/vscode#30773]
- OS Version: Microsoft Windows 10 Pro (10.0.14393)
- VSCode Version: 1.14.1
- Extensions
  - ESLint (1.2.11)
  - Git Lens (4.3.1)
  - IntelliSense for CSS class names (1.7.0)
  - Less IntelliSense (0.6.3)
  - PHP Debug (1.11.1)
  - PHP IntelliSense (1.4.3)
  - phpcs (0.7.0)
  - PHPUnit (1.0.0)
  - Smarty (0.2.0)
  - Vagrantfile Support (0.0.5)
- Reproduces without extensions: Yes

![unbenannt](https://user-images.githubusercontent.com/646868/28241787-849fc8ac-699b-11e7-99c4-0ab90b708862.PNG)

Example code

```js
/**
 * @author name <text@text.tld>
 * @param {string} parameter
 * @return {boolean}
 **/
function name(parameter) {
  return true;
}
```

It seems that the `@` of the email address is always interpreted, no matter what follows.

**Comment by mjbvz** [comment]
Thanks. Looks like the TypeScript server that powers our JS and TS intellisense is handing the incorrect response in this case. 

I've opened https://github.com/Microsoft/TypeScript/issues/17244 to track this upstream
