### ISSUE TITLE
Menu keybinding labels are not translated according to locale

### ISSUE THREAD

**Issue by ygoe** [Microsoft/vscode#30771]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0

---

The menu "Los" is not understandable. Is it a fate, or a lot, or a batch, or does it mean "Let's go!" Go … where? Was that "Go" in English? That would be "gehen" in German. Probably just a stupid as in English. It might be helpful to use the translation for "Go to" which would be "Gehe zu". Some commands in that menu are actually called "Gehe zu (…)".

The second command in that menu is "Weiterleiten" which means forwarding something to somebody. An e-mail message for example, that can be forwarded. From the surrounding commands I guess that you did not mean "to forward" but "the direction forward" which is "vorwärts" in German. The opposite of "zurück" ("back").

Also, the hotkeys are highly inconsistent. Some are positioned at the right end of the menu popup, in grey colour, but completely in English. Others are appended to the command text, left-aligned, in black colour, and partially translated ("Ctrl" was translated to "STRG" (correct would be "Strg") and arrow key names are still in English). These have brackets around them. Why does it look like somebody threw a bomb in there?

**Comment by johnliu2016** [comment]
Thanks so much for the feedback, @ygoe, could you kindly attach some screenshot so as to understand the issue precisely?

**Comment by ygoe** [comment]
"Los" and "Weiterleiten":

![vscode1](https://user-images.githubusercontent.com/868315/28285305-8728f16c-6b34-11e7-9867-0cc6f3864dc8.png)

Half-translated, capitalised and inconsistent keyboard hotkey names:

![vscode2](https://user-images.githubusercontent.com/868315/28285322-9965e8e4-6b34-11e7-8c38-01d6ae461eae.png)

**Comment by johnliu2016** [comment]
"&&Go" main menu and "&&Forward" both come from vscode-workbench/vscode.xliff, current German string is "Los", "&&Weiterleiten", checking with linguistic

as for key bindings, "STRG" is used consistently in uppercase for "Ctrl"/'Control" across projects, for weird display behavior of localized key bindings, also unlocalized key bindings in correct display behavior, @dbaeumer, can you take a look as it looks not loc related.

**Comment by dbaeumer** [comment]
Assigning to @bpasero: this mismatch between STRG and Ctrl comes from the fact that one a cord ('Order oeffnen' needs to short cuts to be pressed) and the another not. Windows has no native support to render cords. So we do it by ourselves.

But never the less we should align the names (consistently use Ctrl).

**Comment by ygoe** [comment]
I'm not sure what a "cord" is, but anyway, this is not Windows rendering the key shortcut, it's the Chrome rendering engine used for VS Code. (That's also responsible for the poor text rendering quality compared to Windows native ClearType or WPF ≥ 4.0 or Firefox DirectWrite.)

And the only issue I see in "STRG" is that it's all-capitals. The letters are correct but should read "Strg", just like in the English "Ctrl" (which is not "CTRL" either).

**Comment by dbaeumer** [comment]
It is use. For "Order oeffnen" we render the two keyboard short cuts STRG+K STRG+O ourselves and but square brackets around.

**Comment by bpasero** [comment]
@dbaeumer "But never the less we should align the names (consistently use Ctrl)." <- shouldn't it consistently be STRG because the german locale is used? It looks to me like a bug in Electron that the german variant of the keybinding is not picked up?

**Comment by dbaeumer** [comment]
@bpasero agree that STRG would be preferable but I thought Ctrl this is given by the OS / Election. In addition my Swiss German keyboard on the Surface says Ctrl on the keyboard as well.

**Comment by bpasero** [comment]
I find "Ctrl" unusual for german speakers. But maybe that changed over time.

**Comment by ygoe** [comment]
The de-DE type cover says "Strg" on it, as do all my other keyboards. Not "Ctrl" and not "STRG". Some only read "strg" because they stylised everything in lower case. (I could imagine the de-CH variant has "Ctrl" because it can't be in three languages at a time.)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4771
