### ISSUE TITLE
Typescript syntax highlighting issue

### ISSUE THREAD

**Issue by Ikderrr** [Microsoft/vscode#30779]
I just found an issue with Typescript syntax highlighting:

**Theme in screenshots:** `Dark +` (default)

**With a regular expression inside an object**:

![image](https://user-images.githubusercontent.com/29985257/28242902-40924f08-69b0-11e7-90bf-fed2686ee8b5.png)

**Without the regular expression:**

![image](https://user-images.githubusercontent.com/29985257/28242905-54292e42-69b0-11e7-9218-adb9e641fb99.png)

The code:

```
export default class MyClass {
    public static GetData(Body: string) {
        var Combinaisons = [{
            "testtt": /"foo\.dddddd\.testtt": "(.*?)"/g
        }];

        var Data = {
            testtt: null,
            fooo: null,
            kkkkkkk: null
        }

        return Data;
    }
}
```

- **VSCode Version**: 1.14.1
- **OS Version**: Windows 10

**Steps to Reproduce:**

1. Create a new Typescript file 
2. Paste the code above

**Reproduces without extensions**: No

**P.S:** the issue is affecting all themes and not only Dark+

**Comment by mjbvz** [comment]
Thanks, this is already fixed in insiders.
