### ISSUE TITLE
Keybindings list doesn't show all contexts a command is available in

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#30778]
Edit: I've updated the title of this case to better reflect the issue now being discussed, which is that custo contexts and those such as `inDebugMode` are not visible in the `when` column of the keybindings editor.

~In the keybinding section I can see internal commands my extension uses like `dart.applySourceChange`. It's not really useful (or valid) for a user to call this since it's for applying source edits that come back from my language service in the Code Actions provided (the user wouldn't be able to pass the correct arguments).~

<img width="816" alt="screen shot 2017-07-15 at 20 52 28" src="https://user-images.githubusercontent.com/1078012/28242309-e55cddde-699f-11e7-961f-825fcf7e067f.png">

~Am I able to do something to hide these?~

**Comment by sandy081** [comment]
@DanTup We do not show those commands those take args. 

@jrieken Can you help in explaining how to register a command with args in this case so that the system knows the command has args?

**Comment by DanTup** [comment]
Ah, that makes sense. How is it detecting args? Here's what I'm doing:

```ts
vs.commands.registerCommand("dart.applySourceChange", this.applyEdits, this)
```

```ts
private applyEdits(document: vs.TextDocument, change: as.SourceChange) {
    // ...
}
```

**Comment by jrieken** [comment]
> @jrieken Can you help in explaining how to register a command with args in this case so that the system knows the command has args?

Extensions cannot do that, also questionable if the core should continue doing that because keybinding can now also have arguments. 

@DanTup Are you just calling `registerCommand` or do you also list that command in package.json? Also, try prefixing your command id with `_` (underscore) which marks it as *"private"*

**Comment by sandy081** [comment]
@jrieken 

>>
Extensions cannot do that, also questionable if the core should continue doing that because keybinding can now also have arguments.

Good point 👍

**Comment by DanTup** [comment]
@jrieken Just calling `registerCommand`; nothing in `packages.json`. Same as some of the others which don't appear, strangely.

Prefixing with underscore works fine; I'll change them to that - cheers!

**Comment by DanTup** [comment]
@jrieken btw, is it expected that the `when` column doesn't include custom conditions? Eg. if I have  `"when": "dart-code:dartProjectLoaded && editorLangId == dart"` then it only shows the `editorLangId` part.

**Comment by jrieken** [comment]
How do you specify the `when`-condition?

**Comment by DanTup** [comment]
It's in the `package.json` in menu/commandPalette, eg:

https://github.com/Dart-Code/Dart-Code/blob/3235290bc77426e6f3b729d6f7c59154efa27e84/package.json#L159

Seems to pick up the language part but not the other (possible because it doesn't really know how to render it, it's a custom context set via `vs.commands.executeCommand('setContext', "dart-code:dartProjectLoaded", enable);`)

**Comment by DanTup** [comment]
(Note: It works correctly, it's just the display on the keybinding page that doesn't show this info - I'm not really sure if a custom context name is something you'd want to to the user, but the `when` column seems slightly misleading otherwise).

**Comment by DanTup** [comment]
@jrieken Also, it seems like the `inDebugMode` condition doesn't appear in that column either.

(Feel free to rename this case, the title seems somewhat misleading now if you're using it to track the `when` column not showing all conditions).

**Comment by DanTup** [comment]
I've updated the title of this case to better reflect the issue now being discussed, which is that custo contexts and those such as `inDebugMode` are not visible in the `when` column of the keybindings editor.

**Comment by DanTup** [comment]
Ok, I realised what this is - my conditions are in the `commandPalette` section.. I thought this was where we could globally describe when a command is available, but maybe that's not the case? If it is, then I think the users keybindings page should reflect this?

![commands](https://user-images.githubusercontent.com/1078012/28686940-d9e4a676-7304-11e7-8d30-8421489e1050.png)

**Comment by sandy081** [comment]
@DanTup Keybindings editor shows only those when contexts you provide while defining a keybinding. 

Example:

```
"keybindings": [
	{
		"command": "markdown.showPreview",
		"key": "shift+ctrl+v",
		"mac": "shift+cmd+v",
		"when": "editorLangId == markdown"
	}
]
```

Please check if the when context in keybindings definition is shown or not.

**Comment by DanTup** [comment]
@sandy081 I don't declare keybindings for these commands; the user is free to add some of just execute from the command palette. I thought the context added in the `commandPalette` section was a global context for when the command was available - if so, wouldn't it make sense to list here? If not, is there a way to apply a context to a command so that it can only be invoked when that context is valid (eg. if the user keybinds it, but I didn't provide a default keybinding)?
