### ISSUE TITLE
import problem about python

### ISSUE THREAD

**Issue by HopeCollector** [Microsoft/vscode#30789]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-new-file|dku|3.1.0
python|don|0.6.7
auto-close-tag|for|0.4.3
code-runner|for|0.6.26
vscode-emacs|hir|0.1.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.0
org-mode|too|0.1.3
cmake|twx|0.0.17
cmake-tools|vec|0.10.1

---

Steps to Reproduce:

1. create a virtualenv
2. use pip to install some packages (such as bs4)
3. create a sample .py file
4. import the packages you just installed
![p1](https://user-images.githubusercontent.com/20982951/28243760-e110e126-6a08-11e7-8e7f-d9313959d56d.jpeg)
5. select the python interpreter in the virtualenv (you can add it setting your `python.pythonPath`)
![p3](https://user-images.githubusercontent.com/20982951/28243777-70b1c32c-6a09-11e7-9289-319036bfb6ac.jpeg)
6. debug it
7. the program will enter the imp.py
![p2](https://user-images.githubusercontent.com/20982951/28243759-e0fda9a8-6a08-11e7-886c-b4e20f8def0f.jpeg)

Reproduces without extensions: Yes

**Comment by HopeCollector** [comment]
Sorry my English is a little strange😅

**Comment by circler3** [comment]
I am sorry that I cannot reproduce the issue on win10.
I have a settings.json of
```json
{
    "python.pythonPath": "d:/myproject/env/scripts/python.exe"
}
```
and the result
![Uploading image.png…]()
Moreover, I suggest that you could use  *"python.venvPath": "",* in the settings.json to make the use of virtualenv instead of modifying the *pythonPath* setting.
*Python: Select Workspace Interpreter* in the Command Palette will give you the access to custom virtualenvs.

**Comment by HopeCollector** [comment]
@circler3    Thank you for your suggestion, I can find my virtualenv through _Python : Select Workspace  Interpreter_ now 
But I still cannot get off this problem
When I use python interpreter which is in vitualenv, the problem will came out

**Comment by HopeCollector** [comment]
@circler3 I just found that python2.7 will work fun, but when you use python3.6 in virtualenv the problem will come out

**Comment by circler3** [comment]
@HopeCollector I am using a official build of python 3.6.1. Vitualenv was installed by pip3. 
Maybe there are problems in the extensions since I have only installed the *python* extension. Besides, can you debug python 3 file without the virtualenv being activated?

**Comment by HopeCollector** [comment]
@circler3 It works perfect

**Comment by HopeCollector** [comment]
After many test and read some docs, I understand [how python import a module](https://docs.python.org/3/reference/import.html), and what will happen[ if I import module](https://leemendelowitz.github.io/blog/how-does-python-find-packages.html). But all of these seems not help. 
When I debug a python file with python3 in virtualenv python seems to create a new module whose name is `__main__`
 I did some [google search](https://www.google.com/search?q=why+python+create+a+__main__+module+at+first&oq=why+python+create+a+__main__+module+at+first&aqs=chrome..69i57.13814j0j7&sourceid=chrome&ie=UTF-8) but failed, I can find any thing useful

**Comment by circler3** [comment]
I'm afraid that I can't help since I am not able to reproduce the problem. 
FYI. **\___main\___** is always the start module's *\___name\___* property whether you are using a virtualenv or not.

**Comment by chrmarti** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1092
