### ISSUE TITLE
Feature Request: "Save Workspace As..."

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30787]
Version: 1.15.0-insider
Commit SHA: 56a5bf1
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

It would be nice to have the same options as files and folder for "Save..", and "Save As.." for workspaces by adding "Save Workspace As..." to the toolbar.

**Comment by bpasero** [comment]
@timelsass how is that different from todays File > Workspaces > Save Workspace...?

**Comment by timelsass** [comment]
I guess generally I was thinking "Save Workspace..." as saving my current named workspace environment without a prompt coming up - which would be handy with a hotkey.  Then "Save Workspace As..." as allowing a workspace to be saved by always forcing the prompt to come up so it can be saved as a different workspace.  The behavior of "Save Workspace..." would bring up the prompt if the current workspace was a new and modified workspace.

**Comment by bpasero** [comment]
@timelsass good point, I will rename the action label to be "Save Workspace As...", it will always bring up the dialog.

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/commit/a1789df48de00c143ea75a065cf143460b778a5b
