### ISSUE TITLE
Feature Request: Update application window with Workspace name prepended

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30785]
Version: 1.15.0-insider
Commit SHA: 56a5bf1724f3b882e149a3e7a24e6105a7b837c2
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

When I select a file the application's toolbar is updated with the filename followed by an emdash Visual Studio (in this case - Insider ).  This is great so I can reference the window easily when I have multiple windows open.  When I'm in a Workspace and have multiple Workspaces open in different windows, it's hard to tell which window is what at a glance since I usually am looking at that area.

**Comment by praveenpuglia** [comment]
Isn't it already there? I see `fileName - Workspace Root Directory`. or I might be missing something silly.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/commit/4d8a487b95be4c9aa7b35f3ea8c8ce93da9333fb
