### ISSUE TITLE
Some settings for customizing the statusbar colors are missing

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30780]
A couple of settings are missing:

`statusBar.debuggingBorder`
`statusBar.noFolderBorder`

This is what it would currently look like if I decided to have a red statusbar by default and a blue one while debugging:

<img width="850" alt="statusbars" src="https://user-images.githubusercontent.com/1812093/28243313-35851f40-69c5-11e7-8a36-bbfdc8d28290.png">

**Comment by bpasero** [comment]
**To verify:** I added
* `statusBar.debuggingBorder`
* `statusBar.noFolderBorder`

**Comment by fabiospampinato** [comment]
That's perfect, thanks.
