### ISSUE TITLE
Workspace can't be saved with same name error

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30786]
Version: 1.15.0-insider
Commit SHA: 56a5bf1
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

Steps to Reproduce:

1. Create a workspace as "asdf" and save it.
2. Create another workspace "asdf" and save it.  
3. The file window prompts the warning about overriding a file like normal, and I select to override this file, but then I'm presented with an error inside of the editor after the file save process:
Error: A workspace with the same name already exists at the provided location.

I would expect that my workspace name would be overwritten, and the contents of asdf.code would be updated with the new workspace asdf.code data since I already instructed that I wanted this to happen to the system.  Another approach might be prompting the user to pick a directory for their workspace and enter a name, but only allow dir selection, not file and require the name to be entered

Does this with and without extension enabled.

**Comment by bpasero** [comment]
I took out the check but we need to keep https://github.com/Microsoft/vscode/issues/30864 in mind.
