### ISSUE TITLE
Adding multiple folders to Workspace only remembers last folder added in new session after closing.

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30783]
Version: 1.15.0-insider
Commit SHA: 56a5bf1
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

Steps to Reproduce:

1. Create a new Workspace by going to "File > Workspaces > New Workspace..."  This adds the "UNTITLED WORKSPACE" to the sidebar.
2. Add an existing folder to Workspace - I right clicked then clicked "Add Folder to Workspace."  The folder was a .git repo, and it did not appear in the side bar mentioned in Issue #30782
3. Add another existing folder to Workspace -  I right clicked then clicked "Add Folder to Workspace."  The folder was a .git repo, and it did not appear in the side bar also.
4. Close the editor, and then reopen it.

The result is that only the last folder added to Workspace is added in the sidebar.  I expected to see both folders that were added .

Does this with and without extension enabled.

**Comment by bpasero** [comment]
I cannot reproduce, but maybe this is a case of a missing file event. @timelsass can you attach a video how this looks like for you?

**Comment by timelsass** [comment]
Sorry for the delay!  I just ran through testing on Commit SHA: cf9726da54472f1e268135a64abd4365b91109f4

This and issue #30782 no longer exists for me on latest insiders.  :+1: 

If you wish for me to rollback and test the old commit and record a video feel free to reopen - I'll be happy to do so, but whatever changes have been made around workspaces - they all seem to work as expected now.
