### ISSUE TITLE
Workspace name is always UNTITLED WORKSPACE

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30784]
Version: 1.15.0-insider
Commit SHA: 56a5bf1
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

Steps to Reproduce:

1. Create a new workspace by going to "File > Workspaces > New Workspace..."  This adds the "UNTITLED WORKSPACE" to the sidebar.
2. I added a new file to the workspace called asdf.txt with contents asdf by pressing the icon to add file next to workspace name.
3.  Next I went to "File > Workspaces > Save Workspace..."  I saved the workspace as ~/asdfworkspace.code
4. Close the editor, and then reopen it.

The result is that the workspace still has the name UNTITLED WORKSPACE.  I expected this to have the name given to the workspace when saved.

Does this with and without extension enabled.

**Comment by bpasero** [comment]
@timelsass please let us know if you can still reproduce with tomorrows insider build. I cannot reproduce with latest from master.
