### ISSUE TITLE
Workspace folders not displaying when added

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30782]
Version: 1.15.0-insider
Commit SHA: 56a5bf1724f3b882e149a3e7a24e6105a7b837c2
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

Steps to Reproduce:

1. Create a new workspace. This adds the "UNTITLED WORKSPACE" to the sidebar.
2. Add an existing folder to workspace - I right clicked then clicked "Add Folder to Workspace."  The folders do not appear under the UNTITLED WORKSPACE or anywhere in the sidebar.  The folder contained a .git repo.
3. Close the editor.
4. Reopen the editor.  Now the folder that you have added will appear in the sidebar.

Does this with and without extension enabled.

**Comment by bpasero** [comment]
Same comment as https://github.com/Microsoft/vscode/issues/30783 :

I cannot reproduce, but maybe this is a case of a missing file event. @timelsass can you attach a video how this looks like for you?

**Comment by timelsass** [comment]
Sorry for the delay!  I just ran through testing on Commit SHA: cf9726da54472f1e268135a64abd4365b91109f4

This and issue #30783 no longer exists for me on latest insiders.  :+1:
