### ISSUE TITLE
[feature request]: Track file position navigation history

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#3078]
Full Visual Studio has a nice feature where the file position navigation history is tracked, such that if we go to a particular position in any file (eg. From a "Go to definition" command), we can go back to the previous position by pressing `Ctrl--` and going forward again by pressing `Ctrl-+`

Having this in vscode would be valuable as we can easily preserve our mental editing context by being able to easily switch to various file locations back and forth.

**Comment by colbyrussell** [comment]
The default keybindings include these:

```json
{ "key": "ctrl+alt+-", "command": "workbench.action.navigateBack" },
{ "key": "ctrl+shift+-", "command": "workbench.action.navigateForward" }
```

Do these differ from your request?

**Comment by jumpinjackie** [comment]
Ah, I must've missed that. Disregard this.
