### ISSUE TITLE
Allow workspace to be renamed inline in sidebar

### ISSUE THREAD

**Issue by timelsass** [Microsoft/vscode#30788]
Version: 1.15.0-insider
Commit SHA: 56a5bf1
Date: 2017-07-13T06:24:22.570Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
Ubuntu 16.04

Files and folders can be renamed in the sidebar, and it would be a nice feature to provide the same quick access to editing workspace names in the sidebar as well.

**Comment by bpasero** [comment]
@timelsass can you make clear what you mean with "workspace name". Do you mean the root folders of a workspace or the workspace itself?

**Comment by bpasero** [comment]
@timelsass ping

**Comment by tdi** [comment]
Is there any way to rename a workspace at all?

**Comment by bpasero** [comment]
@tdi the name of the workspace file is used as name for the workspace

**Comment by timelsass** [comment]
@bpasero  sorry didn't see these notifications!  In reviewing this I was looking at the rename file/folder functionality, and the Save Workspace As... feature.  It seems like perhaps allowing uses to right click the Workspace name and given a menu with a "Rename" option would follow the file/folder renaming UI.  Another option maybe would be adding an icon on hover over the workspace section like the add file/ add folder things allowing them to rename workspace there.  

It does appear that Save Workspace As... updates the sidebar and changes the name on successful save, so that has served well for me in the mean time.

**Comment by bpasero** [comment]
I am merging this info https://github.com/Microsoft/vscode/issues/33340
