### ISSUE TITLE
selectionHighlight not working on the settings.json default setting view

### ISSUE THREAD

**Issue by evandrocoan** [Microsoft/vscode#30796]
- VSCode Version: 1.14.1
- OS Version: Windows 10 build 15063

On the User settings side, it is working correctly:

![image](https://user-images.githubusercontent.com/5332158/28245915-512f45d2-69e7-11e7-8537-a30a135b1dc6.png)

However on the default side, it is not highlighting anything, never ever, neither even if you select the whole word:

![image](https://user-images.githubusercontent.com/5332158/28245900-20aec180-69e7-11e7-9948-c77a577818c4.png)

Steps to Reproduce:

1. Open the settings.json 
2. Select a common word on the default settings side

___ 

Related issues:

1. https://github.com/Microsoft/vscode/issues/8050 additional options for `editor.selectionHighlight` 
1. https://github.com/Microsoft/vscode/issues/11354 Editor selection colors should be simplified

**Comment by sandy081** [comment]
This is as designed. Default settings is made special editor by providing some features like filtering on Search. In favour of these some editor features like Find, Selection are not supported.
