### ISSUE TITLE
Show tooltip bellow the mouse cursor, instead of above it

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/vscode#30797]
- VSCode Version: 1.14.1
- OS Version: Windows 10 build 15063

Help tool tip should be placed bellow the mouse cursor on the `settings.json` file, instead of above item. For me it is horribly confusing putting it above it, beyond blocking my vision, as I read what is above my mouse cursor, not bellow it. Perhaps a setting to configure this behavior.

![image](https://user-images.githubusercontent.com/5332158/28245994-b03f8d9c-69e8-11e7-8208-bb279bd477a2.png)

* The mouse cursor is where the big red arrow is pointing.

Steps to Reproduce:

1. Open the `settings.json`
2. Place the cursor in of of the settings

Reproduces without extensions: Yes/No

___ 

Related threads:

1. [Disable tooltip hint in Visual Studio Code](https://stackoverflow.com/questions/41115285/disable-tooltip-hint-in-visual-studio-code)

**Comment by rebornix** [comment]
We don't have a setting for this while we decide where to show the hover internally, for example, if you hover on code in the first line and there is no space above the cursor then we show the hover below the line.

**Comment by evandrocoan** [comment]
But internally you prefer to show them above. For example, if the space both above and bellow are available, you decide for above. This is really annoying, and is the opposite for other editors as Sublime Text, which favors to show bellow:

![image](https://user-images.githubusercontent.com/5332158/28294500-05b1b842-6b31-11e7-930a-601642ba75a5.png)

Most my vision is focused on what is above of the cursors, so favoring it to show above simply blocks my vision field. Hence would be very welcome this issue be a enhancement setting for the internal algorithm to favor bellow the cursor:

![image](https://user-images.githubusercontent.com/5332158/28294500-05b1b842-6b31-11e7-930a-601642ba75a5.png)

, over the above the cursor:

![](https://user-images.githubusercontent.com/5332158/28245994-b03f8d9c-69e8-11e7-8208-bb279bd477a2.png)

**Comment by rebornix** [comment]
Reopen this and see ppl's feedback on this. @evandrocoan Thank you for your patience and detailed info.

**Comment by ahaswell** [comment]
Wholeheartedly agree. Its extremely frustrating having the previous 4 lines of code obscured by the tooltips when it could just be placed below where Im typing in the empty space. Please allow us to choose above of below at the very least! cheers!

**Comment by a-heryani** [comment]
I completely agree. This is annoying as hell. Blocks my view of the code lines above. I need to see those. I don't care what is below. Having to move the cursor away just so that I can see what I have written above is poor UX

**Comment by jaymcgrath** [comment]
VS code is awesome, thanks to the contributors for all your work!

That said,these tool tips are driving me nuts! I've never been bothered by intellisense before, and I actually rely on it, so I don't want to turn it off.  Like most other people have said, showing tips above the line makes it hard to tell what I'm doing.

**Comment by Fung-yuantao** [comment]
Do we have a solution for this now? Showing tooltip above the cursor does block my view of code lines above. Though tooltip is useful, I still have to turn it off since I found no way to make it show below the cursor.

**Comment by fiblit** [comment]
Is it possible to make an extension for this while we wait?

**Comment by Noiredd** [comment]
Yep, whatever productivity I might have gained from having the tooltip is lost because I have to hit escape repeatedly to close it. Because not only it blocks view, but also reappears every time I hit a comma in an argument list for example.  
Real shame because VS Code deals with Python really well and the hints are useful :(

**Comment by ramya-rao-a** [comment]
This is similar to #33752

**Comment by rv-cturley** [comment]
Would still love to see this worked on, I am with @dustinfast if someone could point me where to start looking I could help out.

**Comment by targetcreature** [comment]
Any movement on this? Would love to be using tooltips, but currently have them off for this reason.

**Comment by rjhilgefort** [comment]
Would love to see tooltips below as well. Disabling for now.

**Comment by phuein** [comment]
Same issue. One of a handful that now made me go back to ST3. How is this 2 years open and still not fixed, at least with a settings option?

**Comment by futscdav** [comment]
@rebornix Is this enough feedback? Please implement this as an option or allows us to change the default somehow.

**Comment by rebornix** [comment]
@misolori if I remember correctly, we have an issue tracking the experiments of Hovers/Suggestions/ParameterHints, right?

**Comment by misolori** [comment]
@rebornix yep, this one https://github.com/microsoft/vscode/issues/63144

**Comment by tomboland** [comment]
Can I clarify. Do we upvote the vscodebot comment, or the original comment?

**Comment by misolori** [comment]
@tomboland please upvote the original comment

**Comment by NickWoodward** [comment]
Only took 3 years!

**Comment by freMea** [comment]
A bar/panel at the bottom of the editor that would appear with no delay could do the trick too.

But with the new flexible layout released in may 2020, a parameter info view that one can move everywhere would be nice too. Maybe a new activity being oriented towards code documentation that would implements the current parameter info tooltip as well as other documentation aggregator like DevDocs would be nice and complete.

I have a workaround to have access to this info tooltip without being annoyed by them. I explain it here #102198 because this highlighted another bug.

Here are other related issues more or less duplicate : #33752, #16221 (an awesome feature suggestion), #15667, #51253, #63144.

**Comment by steinhh** [comment]
It's sooo sad that this is now unassigned 😫😭. Can't believe that none of the VS Code developers find this so incredibly annoying that they haven't made it their personal number one priority to get it "fixed".

Any suggested place to raise the issue to get more upvotes? It's killing me!

**Comment by freMea** [comment]
> It's sooo sad that this is now unassigned 😫😭. Can't believe that none of the VS Code developers find this so incredibly annoying that they haven't made it their personal number one priority to get it "fixed".
> 
> I'd be perfectly happy with almost any change in the position... always in the upper corner, always in any other corner, always below (even if it crashes VS Code!). Any annoying behaviour resulting from such a fix can be fixed by a simple habit change: just make sure the lines you're currently editing is not in a place where the new behaviour will trigger the problem.
> 
> Any suggested place to raise the issue to get more upvotes? It's killing me!

Meanwhile it gets fixed someday you can disable this tooltip and replace with extension that show its content in a panel.
https://marketplace.visualstudio.com/items?itemName=bierner.docs-view

Or add very long delay and check the shortkey to show it when needed.

**Comment by tomboland** [comment]
Nearly a year ago people voted for this to be added to the backlog. Enough people voted to reach the prescribed threshold. Did it not mean anything? 

![IMG_20210131_090029](https://user-images.githubusercontent.com/8832878/106379302-df787f80-63a2-11eb-953d-ed51f1f47f59.jpg)

**Comment by ganindu7** [comment]
Come on vs-code you can do this!! (Or have you done this already and I can't find the toggle ):

**Comment by vkoivula** [comment]
These tooltips should always be below mouse cursor or below the line your keyboard cursor is currently at. Currently this just blocks view! For example now in one exercise I am working on.

<img width="752" alt="Screenshot 2021-09-04 at 16 24 41" src="https://user-images.githubusercontent.com/43766/132096025-e8c7a4a2-129b-4d6b-9cad-ec385747222f.png">

**Comment by Pingear** [comment]
Hello)
This option unfortunately does not give the full ability to place a tooltip below the cursor. Does anyone know how to prevent the tooltip from being placed over the word I'm currently typing?
![tooltip_fail](https://user-images.githubusercontent.com/16469484/201449502-d5ece80a-2b1e-4036-92fe-24542e240ca6.gif)

**Comment by freMea** [comment]
It seems disabling this option addresses the initial issue in post 1, putting the tooltip below instead of above.
![image](https://user-images.githubusercontent.com/22337329/203481741-1941960d-ec6f-4366-89d3-e4dc839c7b4b.png)

**Comment by freMea** [comment]
@Pingear Disabling the hover and replace it by [docs view](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) extension in this situation would be the best in your case. A keybinding can be set to call the tooltip even when disabled.

**Comment by gjsjohnmurray** [comment]
@Pingear it looks slike your view of code is being obstructed by the additional help for the item highlighted in the completion list. When that list is open, press Ctrl/Cmd+space to toggle that additional help off.

**Comment by Timmmm** [comment]
@Pingear That isn't technically a tooltip so I don't think it's related to this option. Maybe worth another issue if you think it can be improved. Your recording does look a little annoying but I can't say I've ever got annoyed by it.

**Comment by aiday-mar** [comment]
This issue has been fixed as is written here: https://github.com/microsoft/vscode/issues/30797#issuecomment-953045648 and will be closed. The new setting `editor.hover.above` can be used to specify a preference for the hover position (either above or below the current line). If the content hover does not fit above or below, and you want it rendered on a specific side, it will soon be possible to resize the hover (make it fit into the available space) and see it rendered on the preferred side.
