### ISSUE TITLE
Salsa: symbols not found (ES5)

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#3079]
I have activated salsa and when activated, some symbols cannot be found anymore in ES5 files.

For example, if I have a a file with only:

    function toto() {
    }

Typing `@toto`will work and highlight the toto function.

But if I wrap the code into a closure, it doesn't work anymore:

![salsa](https://cloud.githubusercontent.com/assets/199648/13107988/b5b09720-d570-11e5-8e1a-9a00e8c5984b.jpg)

Without salsa, it works as expected, highlighting the toto function even if it is wrapped into a closure.

Code 0.10.8
Windows 10

**Comment by egamma** [comment]
Moving to TypeScript

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7134
