### ISSUE TITLE
Consolas font rendered narrower than Sublime Text one

### ISSUE THREAD

**Issue by evandrocoan** [Microsoft/vscode#30794]
- VSCode Version:  1.14.1
- OS Version: Windows 10 build 15063

The font `Consolas 15pt` with `"window.zoomLevel": 1.1,` is rendered narrowed, comparing to Sublime Text with the same font size:

**VSCode 1.14.1**
![image](https://user-images.githubusercontent.com/5332158/28245579-bba795a6-69e0-11e7-87f1-f3728993a6c7.png)

**Sublime Text build 3141**
![image](https://user-images.githubusercontent.com/5332158/28245601-19c57162-69e1-11e7-9f66-1db2bec07d49.png)

**Notepad++ 7.4.1**
![image](https://user-images.githubusercontent.com/5332158/28245812-fab9e6aa-69e4-11e7-9e82-5fa7d4a525ef.png)

From these screenshots we may notice the VSCode fonts are a little less weaker than the Sublime Text one. They give the impression VSCode is saving "paint" to draw the lines. From the 3 images, the VSCode is the worst of them. Where Sublime Text is only a little stronger than Notepad++.

How make the VSCode font stronger as the Sublime Text one?

Steps to Reproduce:

1. Set the setting `"editor.fontSize": 15,`
1. Set the setting `"window.zoomLevel": 1.1,`
1. Create the text file:
```
<!-- Do you have a question? Please ask it on http://stackoverflow.com/questions/tagged/vscode. -->

<!-- Use Help > Report Issues to prefill these. -->
- VSCode Version: 1.14.1: 
- OS Version: Windows 10 build 15063

Add border options to `selectionBackground` and `findMatchBackground`. 

<!-- Launch with `code --disable-extensions` to check. -->
Reproduces without extensions: Yes
```

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I believe Chromium uses only DirectWrite when rendering fonts.

**Comment by foisonocean** [comment]
![image](https://user-images.githubusercontent.com/15059605/31754900-4ac34816-b4cd-11e7-99e1-367e564126b6.png)

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
