### ISSUE TITLE
Enhance brackets features

### ISSUE THREAD

**Issue by rodgobbi** [Microsoft/vscode#30809]
I'm migrating from Atom to vscode and one of the few features that I constantly use is `Select Inside Brackets`, I'd like to ask if there's any planning to implement this feature.
Vscode already has `Go to Bracket`, but I can't go to any wrapping bracket when the cursor is in any line inside the wrapping brackets, it would be a helpful enhancement being able to do that (I'm used to this in Atom).
By the way, I am really enjoying vscode and at the same time expecting it to get even better.

**Comment by rodgobbi** [comment]
I found `expand-selection-to-scope` to solve my first problem.
But the enhancement to `Go to Bracket` still useful.

**Comment by rebornix** [comment]
@rodgobbi thank you sir, let's track in this issue in https://github.com/Microsoft/vscode/issues/9768
