### ISSUE TITLE
Code doesn't work with on demand files from onedrive

### ISSUE THREAD

**Issue by shanyp** [Microsoft/vscode#30803]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.16231
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
jshint|dba|0.10.15
python|don|0.6.7
CppSnippets|har|0.0.12
beautify|Hoo|1.1.1
MagicPython|mag|1.0.10
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vscode-icons|rob|7.10.1
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
#30619
