### ISSUE TITLE
Task sequences

### ISSUE THREAD

**Issue by fis-cz** [microsoft/vscode#30808]
Hello,

As far as I know it is not possible to run sequence of tasks directly from VSCode (I know I can manage it using Gulp or another task runners, but I'll welcome if it can be integrated directly to VSCode).

It would be great if it can be possible to run sequences i.e. "Launch" -> "Attach" or "Lint" -> "Compile" -> "Pack" directly with configurable actions based on results of previous tasks (i.e. continue on fail or stop on fail).

**Comment by dbaeumer** [comment]
Parts of it is possible with the "dependsOn" attribute of the task 2.0 version.

**Comment by alexr00** [comment]
Check out dependsOrder! https://code.visualstudio.com/docs/editor/tasks#_compound-tasks
