### ISSUE TITLE
Commenting and uncommenting codes using shortcut key (ctrl+/) adds spaces around the syntax

### ISSUE THREAD

**Issue by ajyotirmay** [Microsoft/vscode#30804]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.8.0-58-generic (Ubuntu 16.04.2 LTS)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
compulim-vscode-closetag|Com|1.1.0
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.7
highlight-matching-tag|vin|0.3.0

---

Steps to Reproduce:

1. comment code (press ctrl+/)
2. uncomment code (press ctrl+/)

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Tracked with #30800
