### ISSUE TITLE
intellisense for json objects

### ISSUE THREAD

**Issue by Meir017** [Microsoft/vscode#30812]
I have the files `config.js`:
```js
module.exports = {
    username: 'meir',
    password: '123456'
};
```
and `config.json`:
```json
{
    "username": "meir",
    "password": "123456"
}
```

when requiring that file from another file I get intellisense on that object.
`app.js`:
```js
const config = require('./config.js');

config. // suggests username & password
```
However when using raw json file I get no intellisense at all:
```js
const config = require('./config.json');

config. // random stuff
```

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/7071
