### ISSUE TITLE
Offer the user to configure a task when the 'preLaunchTask' isn't found

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3081]
When a launch config refers to a `preLaunchTask` that does not exist then we show this message:

![image](https://cloud.githubusercontent.com/assets/172399/13108138/9d90aed6-d571-11e5-83dc-f40bbcd6ecce.png)

We should handle this error situation more gracefully:
- inform the which preLaunchTask could not be found and that task.json should be configured
- offer the user to create a task.json by presenting the `configure task runner` command: 
![image](https://cloud.githubusercontent.com/assets/172399/13108298/74210df6-d572-11e5-98d4-267ee25da8b1.png)
- the default generated task template should include a task.json for .net

**Comment by dbaeumer** [comment]
@isidorn as discussed I made the configure task runner action public. You can reach it via the ITaskSystem#configureAction(). Simply embed it into the message you are showing.
