### ISSUE TITLE
Expose debug status

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#30810]
I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-statusbar-debugger) that puts a debugger into the statusbar, in order to workaround a year-old issue with the default floating debugger widget (#2513 #9093) but I cannot quite make it work perfectly because there's no API for getting the status of the debugger.

In order to do that it would be necessary to know:
- if a debug session is currently active
- when it started/stopped 
- if code execution is paused

A decent, and maybe more general, starting point might be to expose the switches used in keybindings under the `when` key, like `inDebugMode` for instance. 

What do you think?

**Comment by weinand** [comment]
@fabiospampinato Makes sense. We are working on the debug api right now...

**Comment by fabiospampinato** [comment]
@weinand Great!

**Comment by seesemichaelj** [comment]
@fabiospampinato I'm guessing this is what is preventing the issues I created https://github.com/fabiospampinato/vscode-statusbar-debugger/issues/1 and https://github.com/fabiospampinato/vscode-statusbar-debugger/issues/2?

**Comment by fabiospampinato** [comment]
@seesemichaelj Exactly.

**Comment by fabiospampinato** [comment]
@weinand Information about compound debugging should be exposed as well, I've got an issue about it (https://github.com/fabiospampinato/vscode-statusbar-debugger/issues/4) which I cannot fix without it.

Can you provide an estimate for when this issue will be resolved?

**Comment by arthurchumak** [comment]
https://code.visualstudio.com/updates/v1_24#_debug-toolbar-location

**Comment by fabiospampinato** [comment]
@weinand As there been any progress on this?

**Comment by hediet** [comment]
You can do [this](https://github.com/hediet/vscode-debug-visualizer/blob/master/extension/src/VsCodeDebugger.ts#L31) btw. to sniff the communcation between the debug adapter and VS Code.

**Comment by EverlastEngineering** [comment]
You can have a look at my code for this extention which reveals the debug in the titlebar:

https://github.com/EverlastEngineering/debugInTitlebar/blob/master/package.json

The only thing I wanted and wasn't able to get was whether breakpoints are globally enabled or disabled, but I am able to see status like stopped, paused, initializing, etc.

**Comment by fabiospampinato** [comment]
> You can do this btw. to sniff the communcation between the debug adapter and VS Code.

@hediet I'm a little late to the party but that looks really interesting, thanks for linking to that.

**Comment by roblourens** [comment]
I think a `DebugAdapterTracker` will probably be the best bet here
