### ISSUE TITLE
Enable Text/Code Wrapping

### ISSUE THREAD

**Issue by Ailyn09** [Microsoft/vscode#30823]
It's been a month when I started using Visual Basic Code, I try this and I love to use it in every day coding due to its extension, plug-ins and theme, even though this make me mesmerize with the application, but I even  still compare this to other text editors such as Sublime, Atom and Notepad++ and one behavior.

> The one that I compare is the word wrapping, this behavior of this application that really bugged and annoyed me. Whenever I would browse a document I would always get frustrated by the way the application would horizontally scroll whenever a document had really long lines of code. 

Is there's a possibility for me or us to enhanced word wrap or make a soft automatic text or command wrapping?

**Comment by DarkLite1** [comment]
If I understand you correctly, you just want to enable `Word wrap`? To do this there are several options:

- Open the `command palette` by clicking `F1` or `CTRL + SHFT + P`
- Type `Wrap` and select `View Toggle Word wrap`
![image](https://user-images.githubusercontent.com/10828570/28267545-d855d9fe-6afa-11e7-837e-3af759408735.png)

This can also be doen without the `command palette` and just slicking `ALT + Z` on the keyboard.

**Comment by rebornix** [comment]
Thanks @DarkLite1 and yes we already have word wrapping.
