### ISSUE TITLE
Ubuntu Icon option seems to require a full path.

### ISSUE THREAD

**Issue by tim-field** [Microsoft/vscode#30826]
The contents of `/usr/share/applications/code.desktop`

Includes 

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %U
Icon=code
```

If I change this use an absolute path

\-  `Icon=code`
\+ `Icon=/usr/share/code/resources/app/resources/linux/code.png`

I get the expected icon showing. 

But this is undone on the next update.

**Comment by Tyriar** [comment]
It pulls the icon from `/usr/share/pixmaps/code.png` which should have been installed via the deb package:  https://github.com/Microsoft/vscode/blob/23f80bae3594818416a469b29dd4d9d45207fb76/build/gulpfile.vscode.linux.js#L66
