### ISSUE TITLE
Expose document.hidden

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30827]
It would be helpful if VSC exposed `document.hidden` via an API, so that extensions could take advantage of it in order to skip some work.

Just to provide a concrete use case: I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-github-notifications-bell) that calls a GitHub API endpoint every X seconds, the problem is that if I have N workspaces the extension will make N requests instead of 1, it would be better if it could avoid making requests for hidden workspaces.

What do you think?

**Comment by jrieken** [comment]
Actually, there is [`TextDocument#isClosed`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L128) telling you that a document is detached.

**Comment by fabiospampinato** [comment]
Which is not the same thing, actually.

In Chrome you get this behavior (probably over simplified):
- if the tab is active and the window is visible then you get `true`
- if the tab is not the active one or the window is in another virtual desktop then you get `false`

Even if the `#isClosed` property worked in the same way, In the case where `vscode.workspace.textDocuments.length === 0` we would have no way of knowing if the app is hidden or not. But it actually works differently. `#isClosed` always returned `false` to me in the cases where Chrome's `document.hidden` would have returned `true`, proving that they are not the same thing.

Please reopen the issue.

**Comment by jrieken** [comment]
Then you want this: #15178

**Comment by fabiospampinato** [comment]
No, that's not what I want.

If I used that information I might be tempted to only updated one editor, but what if 2 are open and both of them are **visible**? Then I should updated both. Similarly maybe none of them is visible and none should get updated.

I want to know when an editor is **hidden** or not, I don't care how many editors there are and what documents they have open.

Please reopen the issue.

**Comment by jrieken** [comment]
Then you want this: #18263

**Comment by fabiospampinato** [comment]
That's exactly what I want! Thanks.
