### ISSUE TITLE
Breakpoint hover: use fixed-width font only when showing the breakpoint condition

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3082]
Currently the breakpoint hover always uses a fixed-width font which makes messages appear wider than necessary. I suggest to use a variable-pitch font by default and switch to the fixed-width font only when showing the expression of a conditional breakpoint.

**Comment by isidorn** [comment]
Fixed by @joaomoreno :beers:

**Comment by joaomoreno** [comment]
Nice
