### ISSUE TITLE
vscode.workspace.onDidCloseTextDocument callback not called

### ISSUE THREAD

**Issue by rafaelmaiolla** [Microsoft/vscode#30820]
In my extension, I'm opening a local file using `vscode.workspace.openTextDocument` and then `vscode.window.showTextDocument`.  And it seems to be working fine.

I'm also listening for events using `vscode.workspace.onDidOpenTextDocument`,  `vscode.workspace.onDidSaveTextDocument` and `vscode.workspace.onDidCloseTextDocument`.

Both `vscode.workspace.onDidOpenTextDocument` and  `vscode.workspace.onDidSaveTextDocument` callbacks are called as expected. However 
`vscode.workspace.onDidCloseTextDocument` callback is not called when I close the file in the UI.

Am I missing anything?

- VSCode Version: 1.14.1
- OS Version: Windows 10 Version 1703

Steps to Reproduce:

1. Open the file using `vscode.workspace.openTextDocument` and then `vscode.window.showTextDocument`;
2. Listen for events in `vscode.workspace.onDidCloseTextDocument`.
3. Close the file in the editor;
4. Check that `vscode.workspace.onDidCloseTextDocument` callback is not called as expected. 

Reproduces without extensions: It is the extension code that is not working.

**Comment by jrieken** [comment]
The API just reflect what the workbench does. That might not be what you expect but in general it's up to the editor to decide when to close a document. When that happens the event will fire.

**Comment by rafaelmaiolla** [comment]
So, what you are saying is that `vscode.workspace.onDidCloseTextDocument callback` is not guaranteed to be called?

Why does it work as expected if I open the file using the menu options File > Open File?

**Comment by rafaelmaiolla** [comment]
It seems that something has changed in version 1.13.1.

I tested in version 1.12.2 and everything was working fine.
I tested again in version 1.13.1 and it was not working as expected.

**Comment by bpasero** [comment]
@rafaelmaiolla is this a untitled file that you close after saving? I cannot reproduce with a normal file.

**Comment by rafaelmaiolla** [comment]
@bpasero I will reproduce the issue again and add the details here.

**Comment by rafaelmaiolla** [comment]
@bpasero, I can still reproduce the issue in the last VSCode version.

You can check the code from my extension [here](https://github.com/rafaelmaiolla/remote-vscode/blob/master/src/lib/Session.ts).

You should check the methods `openInEditor` and `handleChanges`.

But basically, the code is doing the following steps:
1. Receive a file through a socket connection;
2. Save it in the temp folder;
3. Open that file using `vscode.workspace.openTextDocument` and `vscode.window.showTextDocument`;
4. Listen for the events `Save`, `Close` and `Open`;

What I could see is that the `Save` and `Open` events are working as expected. However, the `Close` is not working as expected.

It seems that the event is triggered after some time, but I can't say it exactly.

**Comment by bpasero** [comment]
@rafaelmaiolla I would prefer a simple sample to verify this, here is how I try to reproduce (and cannot).

* generate a hello world typescript extension via (`npm install -g generator-code` and `yo code`)
* run the following code:

```typescript
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    vscode.workspace.onDidOpenTextDocument(() => {
        console.log("onDidOpenTextDocument");
    });

    vscode.workspace.onDidSaveTextDocument(() => {
        console.log("onDidSaveTextDocument");
    });

    vscode.workspace.onDidCloseTextDocument(() => {
        console.log("onDidCloseTextDocument");
    });

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.workspace.openTextDocument(__filename).then(doc => {
            vscode.window.showTextDocument(doc).then(() => {
                console.log("Showing text document");
            });
        });

    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

* run "Hello World" command
* close the file

=> events are fired

**Comment by mprobst** [comment]
I've debugged this a bit (I'm trying to use the extension). I do see the onDidCloseTextDocument fire, so that might not be the problem.

@rafaelmaiolla's extension doesn't seem to work because it keeps a reference to the text document it opened. When the close notification happens, it happens with a different text document.

The text document the extension keeps a reference to has the file name `"/var/folders/9h/hrqcx5mn6xx8pr33qwddwxmw003zyt/T/cgDcg0Qm3i/foo.txt"`. The text document that is closed has the file name `"/var/folders/9h/hrqcx5mn6xx8pr33qwddwxmw003zyt/T/8IuAZeqcfX/foo.txt.git"`.

Maybe some git plugin is interfering here?

**Comment by mprobst** [comment]
@rafaelmaiolla I'm just some random dude trying to use your extension (which is nice, thanks for it!), I have no deeper insight into what's going on here.

**Comment by bpasero** [comment]
@rafaelmaiolla reproducible steps for what you see? Are you saving a new untitled file? If so, that behaviour is expected.

**Comment by mprobst** [comment]
@bpasero my repro is sadly a bit involved (check out the extension, debug it, set breakpoint at the line I'm referencing, run an `rmate` command to trigger behaviour). The file that's being closed is an existing file on disk, in the temp folder.

**Comment by rafaelmaiolla** [comment]
@bpasero, the file is saved to disk before opening in vscode.

What do you mean by untitled file?

**Comment by bpasero** [comment]
@rafaelmaiolla is it an existing file that is saved or a new file

**Comment by mprobst** [comment]
The file is an existing file.
