### ISSUE TITLE
VSCode 1.14.1 version not pushed in stable repo

### ISSUE THREAD

**Issue by marcevrard** [Microsoft/vscode#30824]
- VSCode Version: 1.14.0
- OS Version: Ubuntu 16.04.2

Steps to Reproduce:

1. `sudo apt-get update`
2. `sudo apt-get upgrade`

(Repository: `https://packages.microsoft.com/repos/vscode stable main`)

**Comment by rmunn** [comment]
Can confirm: https://packages.microsoft.com/repos/vscode/pool/main/c/code/ still only has 1.14.0. I can download the .deb file for 1.14.1 from the https://code.visualstudio.com/Download page, but not via `apt-get upgrade`.

**Comment by vladimir-novoseltsev** [comment]
No RPM version as well.

**Comment by Tyriar** [comment]
Submitted the deb just now and sent the rpm for signing.

**Comment by Tyriar** [comment]
Submitted the signed rpm 👍

**Comment by marcevrard** [comment]
Super quick, thanks!
