### ISSUE TITLE
 Request textDocument/documentHighlight failed

### ISSUE THREAD

**Issue by Nebomzh** [Microsoft/vscode#30822]
![screenshot from 2017-07-16 22-08-38](https://user-images.githubusercontent.com/30219898/28251960-8e33ed5a-6aa2-11e7-8465-acad7b40be05.png)

- VSCode Version: 1.14.1
- OS Version: Ubuntu 14.04 or Windows 7 (the same bug in different OS)

Steps to Reproduce:

1.  Create html document
2.  even without any html tags or with all standard html tags
3. add script tag and type any script
4. comment this script
5. select string with commented script 

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Tracked with #30774
