### ISSUE TITLE
Question marks instead of Hebrew in UTF-U

### ISSUE THREAD

**Issue by Benqzq** [Microsoft/vscode#30832]
I use Win10 home, and in a JS file encoded in UTF-8 the (Hebrew) innerHTML I wrote a few weeks ago in Notepad++ appears as question marks in VSC. This doesn't happen in Notepad++.

It is interesting to note that if I delete the question marks and re writes the Hebrew it appears fine but I have a few files and I would prefer to save the rewriting in each place.

![a](https://user-images.githubusercontent.com/13021900/28257651-1600e940-6ad5-11e7-9142-9e1a730b14f5.PNG)

**Comment by bpasero** [comment]
Make sure to set the encoding for this file accordingly.

**Comment by Benqzq** [comment]
I don't understand @bpasero , I went through some documentation and also read in StackExchange. 

I did all I can, seemingly. I tried to:

Save the file with the UTF-U encoding.
Repopen the file with the new encoding.

What else is there?

**Comment by bpasero** [comment]
@Benqzq you saved the file using VS Code and which encoding exactly? I am talking about this list: 
![image](https://user-images.githubusercontent.com/900690/28263851-d9ff3a32-6ae8-11e7-83a8-7712cd62fa56.png)

**Comment by Benqzq** [comment]
Exactly. I used this exact list to save the file.

**Comment by bpasero** [comment]
@Benqzq and which encoding did you pick?

**Comment by Benqzq** [comment]
UTF-8 (the regular option, not the BOM including option).

**Comment by bpasero** [comment]
@Benqzq can you attach the file here?

**Comment by Benqzq** [comment]
Sure, here it is:

**Comment by bpasero** [comment]
@Benqzq ?

**Comment by Benqzq** [comment]
Sorry, wasn't uploaded (they don't support .js files). Here it is in a zip. See middle of the file.
[callfuncs.zip](https://github.com/Microsoft/vscode/files/1154186/callfuncs.zip)

**Comment by bpasero** [comment]
@Benqzq that file does not seem to be UTF-8, I can see the question marks when opening with other editors too. Can you create a new file (in UTF-8) in VS Code with Hebrew and try to reproduce?

**Comment by Benqzq** [comment]
I created a new file, saved it as UTF-8, pasted the code and again question marks appear even though I can write in Hebrew.

![1](https://user-images.githubusercontent.com/13021900/28302489-48466f12-6b96-11e7-93bf-a3aa1608c5cf.PNG)
![2](https://user-images.githubusercontent.com/13021900/28302490-484a94f2-6b96-11e7-9053-cf873bd43350.PNG)

**Comment by bpasero** [comment]
@Benqzq yeah, copy and paste will not help to reproduce, you need to type the characters again as you did before.

**Comment by Benqzq** [comment]
So there seems to be a discrepancy between UTF-U created files in Notepad++ to VSC... The only editor I used to create any programming file is basically Notepad++.

**Comment by bpasero** [comment]
@Benqzq what is UTF-U you keep referring to, are you sure it is UTF-8?

**Comment by Benqzq** [comment]
WOW! This is wired! I always wrote UTF-8 (8, if it will changed to U) but somehow it changes here from 8 to U... Funny.

**Comment by Benqzq** [comment]
This is wired. I meant UTF-8 anyway, in all cases.

**Comment by bpasero** [comment]
@Benqzq can you paste the actual content of the file here without encoding issues?

**Comment by Benqzq** [comment]
if (window.innerWidth <= 1024) {
			document.querySelector(".logo-text a").innerHTML = "ForMen <br> ������� ������";
		} else {
			document.querySelector(".logo-text a").innerHTML = " ForMen | ������� ������";
		}

**Comment by King66** [comment]
@Benqzq 
I think you should upload the file which is opened correctly by Notepad++, not the file which has been changed by VSCode (callfuncs.zip).

**Comment by Benqzq** [comment]
I don't have another version of the file. This is the only file I have in this context.

![a](https://user-images.githubusercontent.com/13021900/28351862-57bbc012-6c5b-11e7-914e-63db3b77fab5.PNG)

I know notice that it was changed in Notepad++ as well. Indeed, it seems VSC changed the Hebrew to gibberish anyway. 

Is there any solution?

**Comment by King66** [comment]
@Benqzq 
I think you can use git or cloud drive to save correct files first, once a file is changed incorrectly by vscode, you can get back the origin file.

It's hard to help you If you don't provide a file to reproduce,

**Comment by Benqzq** [comment]
wired, I cannot reproduce from scratch with new files created in Notpad++.

**Comment by pettid43517** [comment]
I need somepussy!
