### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times

### ISSUE THREAD

**Issue by abhiagg123** [Microsoft/vscode#30830]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
tslint|eg2|0.16.0
code-runner|for|0.6.26
Angular2|joh|2.4.0
react-beautify|tai|0.3.0

---

Steps to Reproduce:

The TypeScript language service died unexpectedly 5 times

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Can you please provide a screenshot of the error message? Does this error happen for any JavaScript or TypeScript project you open, or only for certain ones?
