### ISSUE TITLE
Update - show the user that a download is in progress

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#30833]
During a download the menu label shows 'Checking For Updates' (see below) it should better show 'Downloading' when a download is in progress.

![image](https://user-images.githubusercontent.com/172399/28257818-c67d2764-6acd-11e7-907e-cbe9b2af90ac.png)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
