### ISSUE TITLE
Automatic got crashed

### ISSUE THREAD

**Issue by ambikesh9** [Microsoft/vscode#30831]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-angular2-emmet|jakethashi|2.0.3|
|vscode-extension-auto-import|moppitz|1.3.3|
|auto-format-imports|pitermarx|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Could you explain in more detail? Do you mean the automatic update? Please update to the latest version.
