### ISSUE TITLE
Typescript file syntax highlighting

### ISSUE THREAD

**Issue by nenadvicentic** [Microsoft/vscode#30835]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
python|don|0.6.7
tslint|eg2|0.16.0
csharp|ms-|1.11.0
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

1. Create new Typescript file and paste the code:
```
this.myMethod({
    "attribution": "<a>bla, bla</a>"
});

L.tileLayer.wms("http://tempuri.org");
```

Because of "<" in "&lt;a&gt;bla, bla&lt;/a&gt;", ending of the last line "//tempuri.org" is highlited as a comment. Delete "<" and highlighting works properly.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is already fixed in the current insiders builds:

<img width="351" alt="screen shot 2017-07-17 at 7 51 48 am" src="https://user-images.githubusercontent.com/12821956/28274120-d440a686-6ac4-11e7-9118-c791b408373c.png">
