### ISSUE TITLE
"editor.formatOnSave": false

### ISSUE THREAD

**Issue by Sylvenas** [Microsoft/vscode#30839]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-stylesheet-formatter|dba|0.2.0
vscode-html-css|ecm|0.1.7
mcss|Enj|0.0.2
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
docthis|joe|0.4.7
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.1.6
vscode-icons|rob|7.10.1
react-redux-es6-snippets|sle|0.4.0
react-redux-es6-snippets|tim|2.1.0
ReactSnippets|xab|1.4.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. "editor.formatOnSave": false
2. save some file

Reproduces without extensions: Yes/No

When I save a file, why is it formatted automatically?And I'm sure editor.formatOnSave is set false

**Comment by mjbvz** [comment]
What language are you working in? Does it reproduce if you disable all of your extensions?

**Comment by gpuido** [comment]
Good call mjbvz,

for me it was :
https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter 
It format on save by default.

**Comment by eliprand** [comment]
FWIW,
I have the same [issue](https://github.com/editorconfig/editorconfig/issues/316). For me, it seems to be caused by [`editorconfig` ](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
I can't recall if I only recently installed this extension or if it had been installed for awhile.
