### ISSUE TITLE
点击文件打开方式

### ISSUE THREAD

**Issue by bbinauk** [Microsoft/vscode#30836]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.打开文件夹，点击文件打开方式居然是替换，而不是新标签页打开，希望修复，很难受现在
2.

**Comment by bingzheyuan** [comment]
This is actually not a bug. Please check the doc if you want to disable this feature.
https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by chrmarti** [comment]
You can set `"workbench.editor.enablePreview": false` to turn this off.
