### ISSUE TITLE
Sort "Open Editors" by name, folder, etc

### ISSUE THREAD

**Issue by mattcobley** [Microsoft/vscode#30846]
There doesn't seem to be any way at present of sorting the "Open Editors" section of the explorer menu by name or similar.  If I can't find a tab I tend to then look in Open Editors, but due to the inability to sort it can be almost as difficult to then find what I need.  I think the ability to sort by name at least would be a big improvement.

**Comment by isidorn** [comment]
Valid feature request, however please try using quick open (ctrl + p) for text searching through files

**Comment by will-stone** [comment]
I'm really hoping this feature arrives. It'd make scanning the Open Editors pane a lot quicker. Does anybody know if there's an extension that can achieve this? I can imagine it's possible by mimicking the Open Editors pane...?
