### ISSUE TITLE
No longer seeing console output

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#30842]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0

---

Steps to Reproduce:

1. Start a program that uses bunyan for logging.
2. To make the bunyan output readable, pipe the output through bunyan-cli.
To do so, create a `pipe-bunyan.cmd` with the following content:
```
@ECHO OFF
node %* | bunyan -o short
```
3. Specify the script as a `runtimeExecutable`, like so:
```
"runtimeExecutable": "${workspaceRoot}\\.scripts\\pipe-bunyan.cmd",
```

There is no output in the debug console. This used to work fine before.

**Comment by weinand** [comment]
@oliversalzburg I'd like to reproduce this. How does your launch configuration look like?

**Comment by oliversalzburg** [comment]
@weinand This is it:
```json
{
	// Use IntelliSense to learn about possible Node.js debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Development",
			"runtimeExecutable": "${workspaceRoot}\\.scripts\\pipe-bunyan.cmd",
			"program": "${workspaceRoot}\\lib\\app.js",
			"cwd": "${workspaceRoot}",
			"env": {
				"DATABASE:HOST": "localhost",
				"MQ:USER": "guest",
				"MQ:PASSWORD": "guest",
				"NODE_ENV": "development"
			}
		}
	]
}
```

**Comment by oliversalzburg** [comment]
This regression was not introduced in 1.14.1 AFAIK. This stopped working in 1.13 IIRC.

**Comment by weinand** [comment]
What version of node are you using?
How is debugging configured in the `pipe-bunyan.cmd` script?

**Comment by oliversalzburg** [comment]
I'm using Node 6.11.2 and the contents of `pipe-bunyan.cmd` are this:

```shell
@ECHO OFF
node %* | bunyan -o short
```

I'm not sure what you're referring to in regards of debug configuration in this script.

**Comment by weinand** [comment]
does it make a difference if you add a `"protocol": "legacy"` to your launch config?

**Comment by weinand** [comment]
The logging works fine for me with "legacy" protocol:

![2017-08-21_16-35-31](https://user-images.githubusercontent.com/1898161/29523954-d6269ede-868e-11e7-83d8-e427daa01387.png)

but not with "inspector" protocol:
![2017-08-21_16-37-57](https://user-images.githubusercontent.com/1898161/29524033-19daf4fe-868f-11e7-87ce-8c2614c36fbb.png)

However, a simple `console.log("hello")` still works for "inspector" protocol.

**Comment by oliversalzburg** [comment]
@weinand I can confirm that it works with `legacy` protocol.

What a relief! :D

**Comment by weinand** [comment]
@oliversalzburg if you do not want to switch to the "legacy" protocol, you can use a different console and continue to use the "inspector" protocol: just add a `"console": "integratedTerminal"` to your launch config.

**Comment by roblourens** [comment]
This is the slightly infamous issue, https://github.com/Microsoft/vscode/issues/19750

`"console": "integratedTerminal"` is probably the best workaround unless you can find a bunyan-specific solution.

**Comment by oliversalzburg** [comment]
@weinand Ugh, that just creates new problems. When I switch the console, the application doesn't even start anymore, because of insufficient command line escaping.

```shell
$ cd "c:\Users\OliverSalzburg\FairManager Projects\core-web3" ; "c:\Users\OliverSalzburg\Fai
rManager Projects\core-web3\.scripts\pipe-bunyan.cmd" --inspect=17380 --debug-brk lib\app.js
Debugger listening on port 17380.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:17380/755a6691-d053-4759-b44a-d343878da79c
Debugger attached.
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\OliverSalzburg\FairManager Projects\core-web3\libapp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
Waiting for the debugger to disconnect...
```

**Comment by oliversalzburg** [comment]
Somewhat annoying that I have to adjust our application code *around* our IDE, but I'm now using https://github.com/ibm-watson-data-lab/bunyan-console-stream to work around the issue.

**Comment by weinand** [comment]
I don't understand in what way you have to adjust your code around VS Code?

**Comment by oliversalzburg** [comment]
If adjusting the `launch.json` would have yielded the desired results, then I would agree. But the only adjustment I could make that did yield any solution, without introducing new issues, was to revert to the legacy protocol. This is undesirable. So, unless I'm missing something, I'm left with adjusting our application code to use a form of logging that VS Code is able to work with.

It is understandable that an IDE doesn't have to cover every possible configuration in existence, but it would definitely be nicer if transitioning from one debug protocol to another (or, for that matter, from one console to another), wouldn't cause so much friction.

**Comment by weinand** [comment]
Sorry, but I'm not able to reproduce the "insufficient command line escaping" with VS Code 1.15.2 on Windows:
![2017-08-22_16-28-29](https://user-images.githubusercontent.com/1898161/29570558-16851046-8757-11e7-81af-6cc62c89c2f8.png)

It would be great if you could point me to the location with the insufficient command line escaping. Thanks!

**Comment by weinand** [comment]
Are you using WSL?

**Comment by weinand** [comment]
this could be another instance of https://github.com/Microsoft/vscode/issues/21635

**Comment by oliversalzburg** [comment]
I'm assuming this is the problem:
```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
```

**Comment by weinand** [comment]
yes, that's the problem. Now I can reproduce (and fix).

**Comment by weinand** [comment]
A fix will be available in the next Insiders.

**Comment by weinand** [comment]
@oliversalzburg please note, that VS Code does not support `git/bin/bash.exe` or `bash.exe` (WSL) yet. So, the fact that it's now working for debug, doesn't mean that it works for tasks as well...

**Comment by oliversalzburg** [comment]
@weinand Understandable. We'll probably just stop using `process.stdout` and similar for direct output in the future though. The module by IBM works well for us. It allows us to stay closer to the default launch configurations without being impacted by possible user settings.

So, in the end, we probably ended up with a better setup overall. Thanks for the help.
