### ISSUE TITLE
'when' clause can not support the configurations who have string values.

### ISSUE THREAD

**Issue by t1ngyu** [Microsoft/vscode#30845]
- VSCode Version: 1.14.1
- OS Version: *

It seems ContextKeyExpr supports this form of  'when' clause: "config.myextension.somekey == 'abc' ", the value field is a string, but ContextKeyService 's member '_contexts' only contains configurations of those who's value are type of boolean.

**Comment by alexandrudima** [comment]
@jrieken for your consideration
