### ISSUE TITLE
Incorrect capitalization in Spanish "Execute task" string

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#30844]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|2.0.10
githistory|don|0.2.1
php-intellisense|fel|1.4.3
ftp-sync|luk|0.3.3
vscode-apache|mrm|1.1.1
typescript-javascript-grammar|ms-|0.0.23
language-stylus|sys|1.7.3
twig|wha|1.0.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Set VS code locale to Spanish
2. Open Tasks (Tareas) menu from system Menu Bar

The general rule for capitalization appears to be to capitalize just the first word, so "Ejecutar Tarea" should be "Ejecutar tarea" to match the same style
<img width="402" alt="screen shot 2017-07-17 at 09 57 26" src="https://user-images.githubusercontent.com/11057501/28261300-81c7b450-6ad6-11e7-8a15-fadce69bc039.png">

**Comment by johnliu2016** [comment]
inconsistent Capitalization in vs_code.xliff

ENU: &&Run Task... 
ESN; &&Ejecutar Tarea...

**Comment by seanpoulter** [comment]
Should we capitalize Tarea since we're using it as a proper noun? Here's a [style guide](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-and-glossaries-grammar/#capitalization) for reference.

**Comment by johnliu2016** [comment]
//cc @lukaschal

**Comment by Lantaros** [comment]
I'm working on it!

**Comment by lukaschal** [comment]
Fixed as suggested.

https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/114440152?qt=Ejecutar tarea
