### ISSUE TITLE
Autoindent: Wrong automatic indent with multiple line expression/string

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#30859]
- VSCode Version: 1.14
- OS Version: 10.12.5

![vsc](https://user-images.githubusercontent.com/50314/28269787-8c5de70e-6b03-11e7-96d1-0584f5ec7dad.gif)

Steps to Reproduce:

* Type this:

```javascript
if (true ||
  false) {
```

* Hit Enter.
* Automatically inserted brace are intended wrong and the cursor ends up at the wrong indentation level:

```javascript
if (true ||
  false) {
    <caret>
}
```

The indent must follow the `if`, not the indented second line of the condition expression.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Closing this due to lack of user interest in the issue over the past 2 years.

I suggest enabling `format on type` which is generally more reliable and consistent than our indent rules
