### ISSUE TITLE
Can't install extensions anymore

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#30850]
- VSCode Version: 1.15.0 insider
- OS Version: Win Srv 2012 64 bit

## Steps to Reproduce:

1. Go the the `Extensions` side bar `CTRL + SHFT + X`
2. Search for an extension, for example `Bimbo Theme`
3. Click the button `Install`

Nothing happens, the text `Install` changes to `Installing` and then gets back to `Install` without anything installed or any notification of what happened.

![image](https://user-images.githubusercontent.com/10828570/28265761-a716bee8-6af1-11e7-8e9e-7d7e796f5f7c.png)

This is for all extensions the case, not just this theme.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by DarkLite1** [comment]
Yes, I think so, we're on the company network behind a firewall. I can access the internet fine, like google.com and such.

**Comment by joaomoreno** [comment]
OK, if you open the Developer tools and look into the Network tab, what failed requests appear?

**Comment by DarkLite1** [comment]
I hope this is what you're looking for:

![image](https://user-images.githubusercontent.com/10828570/28370651-1c83c342-6c9b-11e7-9fc2-1a9eaf632d3f.png)

**Comment by joaomoreno** [comment]
Can you toggle the Shared Process (<kbd>F1</kbd>, `Shared Process`) and check those Developer Tools, while installing an extension?

**Comment by DarkLite1** [comment]
I didn't find the option you are referring to, but I think I did find the error log for you. 
![image](https://user-images.githubusercontent.com/10828570/28403634-e6fc7e2c-6d25-11e7-935c-de958da9c2cb.png)
[workbench.main.zip](https://github.com/Microsoft/vscode/files/1161369/workbench.main.zip)

I think it might be related to these: #17574, #1069, #26982.

**Comment by joaomoreno** [comment]
You must have this option:

![image](https://user-images.githubusercontent.com/22350/28405074-1323d724-6d2c-11e7-85e2-57e203f96418.png)

**Comment by DarkLite1** [comment]
Found it, thanks. Which tab would you like to see?

![image](https://user-images.githubusercontent.com/10828570/28410030-b81f87f4-6d3c-11e7-8367-e08d2fbfa4e5.png)

**Comment by joaomoreno** [comment]
The Network tab, during the attempt to install an extension.

**Comment by DarkLite1** [comment]
Got it
![image](https://user-images.githubusercontent.com/10828570/28414031-0f668bea-6d4a-11e7-8354-f95170d61a46.png)

**Comment by joaomoreno** [comment]
So is this `grouphc.net` your proxy?

**Comment by DarkLite1** [comment]
That is our domain yes

**Comment by joaomoreno** [comment]
@mattbierner I see some changes have been done which directly relate to this: c364d3a61736234361066f5859cd3c02fc114ed5

What can be done here?

**Comment by mjbvz** [comment]
@joaomoreno Yes, we don't allow http connections for connecting to the extension marketplace or installing extensions because this opens you up to some very bad security scenarios. @DarkLite1 Does your company have a https endpoint you can use instead?

**Comment by DarkLite1** [comment]
I'm not really sure how one can set another HTTPS endpoint? Anyhow, the strange thing is that this wasn't a problem a couple of weeks ago but now it is. On top of this, if security is indeed the culprit, then why is it still possible to update the entire VS Code app without changing any settings but not an extension? 

Side remark, when clicking on the [link](http://deunp7845fran1p.grouphc.net:8080/auth/?du=aHR0cHM6Ly9wYXdlbGdyenliZWsuZ2FsbGVyeS52c2Fzc2V0cy5pby9fYXBpcy9wdWJsaWMvZ2FsbGVyeS9wdWJsaXNoZXIvcGF3ZWxncnp5YmVrL2V4dGVuc2lvbi9iaW1iby10aGVtZS8wLjEuMS9hc3NldGJ5bmFtZS9NaWNyb3NvZnQuVmlzdWFsU3R1ZGlvLlNlcnZpY2VzLlZTSVhQYWNrYWdlP2luc3RhbGw9dHJ1ZQ==&ip=MTAuNzUuNDcuMjIyOjgwODA=) and pasting it in IE, the extension can be downloaded manually. Visiting HTTPS websites is also not a problem. So I wonder if this shouldn't be fixed internally instead of on our side?

![image](https://user-images.githubusercontent.com/10828570/28512320-b087b562-7051-11e7-8134-f5be4f14e473.png)

**Comment by mjbvz** [comment]
Yes, we make fixes for potential security concerns as they come to our attention. This one was fixed fairly recently. I don't know about vscode updates themselves or how these are being delivered on your network.

Blocking http downloads in the client is by-design though. I am against adding a setting to disable the behavior. Can you add an exception to your proxy so that connections to the vscode extension gallery are not sent through it?

**Comment by DarkLite1** [comment]
Fixed the downloading of extensions by setting an **Explicit proxy** :
Internet Explorer settings > Internet options > Connections > LAN Settings
![image](https://user-images.githubusercontent.com/10828570/28559722-03d226c8-7118-11e7-9c9f-4407ffa21c07.png)

However, I do believe that the behavior for updating/installing extensions should be similar to updating/installing the app. I'm quite sure other users on company networks will run into this issue too.

**Comment by mjbvz** [comment]
Glad you found a workaround

As I mentioned though, this change in behavior is by design. I can't speak to the installer or updater but I know that we do not want to allow VScode itself to use http connections for pretty much anything. The proper fix is to setup an https proxy endpoint
