### ISSUE TITLE
Cursor jumping to end of line and formatting incorrectly after 2 sec.

### ISSUE THREAD

**Issue by RuanKruger** [Microsoft/vscode#30853]
- VSCode Version: 1.14.1
- OS Version: Win 7 Build 7301 - SP1

Steps to Reproduce:

1. After typing code the cursor jumps to the end of the line and formats the code.
2. I have tried the following: Added below to settings.json:
"typescript.check.tscVersion": false,
    "editor.detectIndentation": false,
    "editor.autoClosingBrackets": false,
    "editor.autoIndent": false,
    "editor.roundedSelection": false,
    "editor.scrollBeyondLastLine": false

Extensions: 
- Angular v$ TypeScript
- C#
- Git History
- JS-CSS-HTML Formatter
- NPM
- NPM Intellisense.

Could not find a solution in the Issues tab.

**Comment by rebornix** [comment]
It sounds like your JS-CSS-HTML Formatter is formatting the code for you. Can you try to run vscode without any extension, `code --disable-extensions` and see if you still have the problem?

**Comment by RuanKruger** [comment]
It works! Thank you very much.
