### ISSUE TITLE
disturbing alert when adding another folder to a workspace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#30854]
[I'm filing this issue as a long time VS Code user, not as a dev who understands what's going on...]
 
When trying to add a new folder to an existing workspace, I get the following alert:

![2017-07-17_14-23-45](https://user-images.githubusercontent.com/1898161/28267867-45022318-6afc-11e7-8003-3f8b003960fe.png)

As a long time VS Code user, I am a bit surprised by the wording because in my current understanding I have already a "workspace" and I cannot really understand why the alert says that I do not have a "workspace".

Could we change the wording so that it sounds less scary, e.g. something like:
"Before we can add another folder we need to upgrade your workspace to support multiple folders..."

**Comment by sandy081** [comment]
Agreed that above dialog is not helping in understanding the transition from *Opening a folder* to *Opening a multi folder* workspace. I have changed the wordings and behaviour today so that the existing or new user understands what is happening. 

@weinand Please verify with the insiders tomorrow and let us know if it makes sense to you.

**Comment by weinand** [comment]
IMO the new wording is even worse:

![2017-07-18_15-25-42](https://user-images.githubusercontent.com/1898161/28319215-9189c700-6bcd-11e7-88d4-0a1ef72dba62.png)

Adding "window" to the wording doesn't help.

I still believe that the wording should be more along the lines of this:
"Before we can add another folder we need to upgrade your workspace to support multiple folders..."

**Comment by chrmarti** [comment]
I missed why there is a confirmation dialog at all. Why not just "upgrade" silently?

**Comment by sandy081** [comment]
We cannot upgrade without window reload due to the fact that we have to migrate some state in the background for which we are not ready yet. Hence there is a confirmation dialog. 

Upgrade without reload is on the cards for future.

Currently shifting from 1-2 is heavy weight operation of creating a new workspace and opening it.

**Comment by bpasero** [comment]
We do not upgrade yet so that I can have some nice vacation without being worried.

**Comment by michelkaporin** [comment]
Agree with @weinand. We should not use phrasing that makes you too cautious about loosing your working state, such as "not supported", or restrictive sentence as "you can do only ...". We just need to inform a user on what will happen.

@weinand proposal sounds good to me
> "Before we can add another folder we need to upgrade your workspace to support multiple folders..."

**Comment by chrmarti** [comment]
"Adding a second folder requires a one-time reload of the workbench so @bpasero can go on vacation without worries?"

**Comment by sandy081** [comment]
I am happy to have suggestions on the wordings in the dialog here. What we are trying to convey to user is that any multi root operation on a current workspace (opened with a folder) needs:

**Creating a multi root workspace with current folder in the background, do the operation and open it, which needs window reload.**

I accept suggestion from @weinand and the new dialogs shown as follows

![image](https://user-images.githubusercontent.com/10746682/28323748-4c1d421c-6bf7-11e7-86c0-51f908fd7f0a.png)

![image](https://user-images.githubusercontent.com/10746682/28323772-58ea2884-6bf7-11e7-9673-d3a71189df60.png)

**Comment by roblourens** [comment]
I would have the focus on reloading the window, since that's more interesting to the user. Maybe if the button said "Reload and Add". As a user I'm not sure what upgrading is going to do or if it's going to be reversible.

**Comment by bpasero** [comment]
Btw here is my comment on the famous multi root issue why we currently require an explicit step when entering workspace mode: https://github.com/Microsoft/vscode/issues/396#issuecomment-315402932

**Comment by sandy081** [comment]
@weinand Today's insiders have above dialogs. Please reopen if you think they are not good enough. Thanks.

**Comment by weinand** [comment]
I think the wording is fine now but there is still the typo "updgrade"  (see your screenshot above).

How important is it to mention the "reload the window"?
There will be no data loss, right?
So on a regular "Open..." we do not show a "reload window" warning either.

**Comment by sandy081** [comment]
Will fix the typo.

As mentioned earlier, we do not retain any state (UI, workspace settings, extensions storage and hot exit). It means after reload user will see a different workspace, opened editors dirty files are not retained. If there are workbench settings like different themes and colours in the workspace, these will not be retained too.

In `Open...` case, user is explicitly asking to open a new workspace. But in this case, I am not sure if we are clear enough in the dialog that upgrading is opening a brand new workspace.

**Comment by weinand** [comment]
Ok, I see. So leave the "reload window" in.

**Comment by weinand** [comment]
saw this while testing #30722

**Comment by chrisdias** [comment]
I react negatively to the "upgrade your workspace" portion of the message. This sounds like the tool is going to do something to my files and it scares me. Can I revert whatever is going to happen? Is this a one way street? It is very daunting :)

Have we considered providing an info message _after_ we restart the environment? We could provide a "more info" link where we can describe what is different now that you are in MRW mode.

**Comment by weinand** [comment]
Are you also scared when VS Code offers you an "upgrade"?
Would "prepare" sound less scary than "upgrade"?

**Comment by chrisdias** [comment]
something like this...

![image](https://user-images.githubusercontent.com/1487073/28384429-8eab3e40-6c79-11e7-8f24-cacfcb9e24dd.png)

**Comment by chrisdias** [comment]
Or, we can really simplify the message to:

"To open multiple folders, VS Code requires a reload."

As a user, what else do I need to know?

**Comment by weinand** [comment]
Yes, this is in line with https://github.com/Microsoft/vscode/issues/31014#issuecomment-316396043

**Comment by sandy081** [comment]
Liked the suggestion from @chrisdias. It is simple and short. Will change to it. Thanks.

**Comment by bpasero** [comment]
+1, the new flow is very cool.

@weinand @sandy081 @chrisdias my only concern now is that it is not just a window reload that we are doing compared to a normal window reload: UI state, hot-exit (dirty files) and extension state is lost after the window reload. I can look into what it would take to keep and restore these things after the reload. E.g. as a user I would not expect to be asked to save files only for a window reload (we do not ask this for a manual window reload either).
