### ISSUE TITLE
MarkDown highlighting doesn't work for indented headings 

### ISSUE THREAD

**Issue by Benqzq** [Microsoft/vscode#30852]
I run VSC 1.1.40 on Win10home. 

I indented my H2 headings and their nice ocean-blue coloring dissapeared (unlike the H1 at the top which is still colored).

De-indenting brings back the color.

This is a fresh copy of VSC. I changed nothing in the program, so I believe this is a minor coloring bug.

![a](https://user-images.githubusercontent.com/13021900/28267355-6aa7ce96-6b02-11e7-93ef-c02d08896fdc.PNG)

**Comment by mjbvz** [comment]
This is correct. Because these headings are indented by four spaces, they will be treated as code blocks. Here's how github handles this for example:

```markdown
# a
    # b
```

# a
    # b
