### ISSUE TITLE
Javascript coloring: function keyword not colored in default themes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3085]
![capture](https://cloud.githubusercontent.com/assets/1931590/13110406/3373941e-d580-11e5-856c-46d8fbc0b382.png)

**Comment by dbaeumer** [comment]
@egamma FYI

**Comment by Nimzozo** [comment]
I would like to add that I've seen other reserved word not being correctly colored (I'm in dark theme).

- `default` is blue but in switch statement turns back to normal color when followed by `:`
- `typeof`
- `instanceof`

I'm still looking for other...

**Comment by egamma** [comment]
@Nimzozo can you check whether these keywords are are colored when you use the Dark+ theme?

In the example from @dbaeumer above the Dark+ theme colors  `function` as a key word.

**Comment by Nimzozo** [comment]
@egamma When I use Dark+ theme, that's exactly the same behaviours that I described. 

I just see there are new colors for parameters, identifers, etc...

**Comment by Nimzozo** [comment]
In _monokai_ theme :

- `constructor`
- `default` followed by `:` inside a `switch` statement
- `extends`
- `static`
- `yield`

are not in pink color.

**Comment by Tyriar** [comment]
@Nimzozo for those 5 it is likely because https://github.com/Microsoft/TypeScript-TmLanguage doesn't support highlighting them yet.

**Comment by felixfbecker** [comment]
I can confirm that @Nimzozo list does not get colored in Dark+ theme.

**Comment by aeschli** [comment]
@dbaeumer The reason for function not beeing colored in the Default Visual Studio theme is https://github.com/Microsoft/TypeScript-TmLanguage/issues/44
(Please always append the code example to save some time on reproducing the issue)

**Comment by aeschli** [comment]
@Nimzozo Thanks for reporting. The issues you are mentioning are mostly caused by
https://github.com/Microsoft/TypeScript-TmLanguage/issues/37
We are working with the TypeScript team to get these fixed.
