### ISSUE TITLE
autoGuessEncoding improvements

### ISSUE THREAD

**Issue by irudoy** [Microsoft/vscode#30857]
At the moment, Code is not very good with automatic guessing the encoding, and work on projects with non-utf8 encodings.
There are 2 proposals that could improve the current situation:

1. Cache the previously selected encodings for files in the format `{ filepath: encoding }`. You can set a limit on the N most recently opened files, for example. This will give an increase in performance when opening recent files and will save you from incorrect recognition of the encoding. This feature can be implemented in the context of the project, workspace or globally.

2. Provide the possibility to specify used encodings in the project settings. Suppose we are working on a project that has legacy codebase in windows1251, and the rest of the files are in utf8. We can specify something like `{ projectEncodings: ['windows1251', 'utf8'] }`, and if the file's encoding is auto-detected, the editor will notify you, that the encoding is most likely not detected correctly. This option is perfectly matched with the first paragraph.

**Comment by irudoy** [comment]
Any news on this feature? Maybe someone can propose an implementation ideas, and I'll do a pull request?

**Comment by bpasero** [comment]
@irudoy encodings when set on an opened tab now survive restarts and we added support to configure encoding per file extension. Is there something missing?

**Comment by irudoy** [comment]
@bpasero, imagine that you are working on a project that has more than 32,000 files. More than half of them are files in the `cp1251` encoding, others in the `utf8`. Every day at work, you open a total of about 100 files, and the encoding is very often detected incorrectly. In this case, you need to always make sure that it has been detected correctly, otherwise, you must set it manually. But if the editor could remember which encoding was set for a certain file, even after closing tab, it would be great and would save developers from many countries a lot of nerves and time. Moreover, the editor already knows how to remember the last position of the cursor, so why not add the encoding as well?

**Comment by zzoe** [comment]
Any News on this feature?
Why not refer to the implementation of vimrc？
[https://stackoverflow.com/questions/48277674/in-vscode-how-can-i-set-the-range-of-file-autoguessencoding/48277776#48277776](url)

**Comment by bpasero** [comment]
I am merging this into https://github.com/Microsoft/vscode/issues/23570 and https://github.com/Microsoft/vscode/issues/36951
