### ISSUE TITLE
Visual Studio Code已停止工作

### ISSUE THREAD

**Issue by githubclose2me** [Microsoft/vscode#30851]
- VSCode Version:
	1.14.1.0
- OS Version:
        win7 sp1
Steps to Reproduce:

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Code.exe
  应用程序版本:	1.14.1.0
  应用程序时间戳:	591206a2
  故障模块名称:	Code.exe
  故障模块版本:	1.14.1.0
  故障模块时间戳:	591206a2
  异常代码:	80000003
  异常偏移:	00308d19
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this issue in english with reproduacble steps, thanks
