### ISSUE TITLE
large css files autocomplete is slow and linter also

### ISSUE THREAD

**Issue by rrobles9112** [Microsoft/vscode#30868]
- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:15:46.760Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
react-toolbox-snippets|ale|0.12.0
copy-relative-path|ale|0.0.1
ng-template|Ang|0.1.4
All-Autocomplete|Ati|0.0.8
vscode-database|baj|1.2.0
typings-installer|ben|0.2.0
vscode-intelephense-client|bme|0.7.2
htmltagwrap|bra|0.0.3
phpserver|bra|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
compulim-vscode-closetag|Com|1.1.0
vscode-svgviewer|css|1.4.2
python|don|0.6.7
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
vscode-great-icons|emm|2.1.11
php-debug|fel|1.11.1
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.4
RelativePath|jak|0.12.0
gitlab-mr|jas|1.3.0
autofilename|Jer|0.1.3
docthis|joe|0.4.7
format-indent|Kas|1.3.0
laravel-blade|KTa|0.0.1
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.3
vscode-scss|mrm|0.6.2
csharp|ms-|1.11.0
js-atom-grammar|ms-|0.1.13
php-docblocker|nei|1.2.0
laravel-blade|one|1.8.1
laravel5-snippets|one|1.3.4
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|2.0.10
sass-indented|rob|1.4.1
ftp-kr|rua|1.0.10
php-formatter|Sop|0.2.4
create-jsconfig|Tom|0.2.0
vscode-react-native|vsm|0.3.2
twig|wha|1.0.2

(13 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rrobles9112** [comment]
on Intel processor is more faster

**Comment by rrobles9112** [comment]
and amd A10 7300 is more slowly

**Comment by aeschli** [comment]
@rrobles9112 Can you point to the css file where you see this issue?

**Comment by aeschli** [comment]
Closing, need more information...
