### ISSUE TITLE
Save Workspace As: use new ID when workspace already saved?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30869]
We should decide if saving an already saved workspace should put a new unique ID into the workspace configuration file or keep the same. The downside of using the same ID is that you suddenly end up having state spread across multiple locations (path of the config file for settings and the ID for the rest).

**Comment by bpasero** [comment]
Thinking about this, imho it does not make a lot of sense to always change the ID when you save the workspace. Let's discuss when you are back.

**Comment by sandy081** [comment]
@bpasero Currently actions says `Save Workspace As...`. This is similar to `Save File as...`. So this action might expect to create a new separate workspace with a different id.

**Comment by bpasero** [comment]
Now that we can actually migrate data over, maybe this is less of a pain if the workspace id changes. Let's talk.

**Comment by bpasero** [comment]
Obsolete via workspace format change where ID is being removed (https://github.com/Microsoft/vscode/pull/33097)
