### ISSUE TITLE
Bundled node.dll v7.4.0 insecure

### ISSUE THREAD

**Issue by dipstar** [Microsoft/vscode#30866]
- VSCode Version: 1.14.1
- OS Version: Windows 7 x64

Bundled node.js v7.4.0 is being flagged up as insecure as it contains an older version of OpenSSL

Further info: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/28582
