### ISSUE TITLE
Spelling error (EN)

### ISSUE THREAD

**Issue by Isotop7** [Microsoft/vscode#30862]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

1. Open VSCode Insiders

Reproduces without extensions: Yes

Spelling of 'application' is wrong as seen in screenshot.

![image](https://user-images.githubusercontent.com/8883656/28273107-b41d979e-6b0d-11e7-9454-894aca49e0b0.png)

The string is found under DEPLOYMENT in the source code sidebar entry.

**Comment by Tekbr** [comment]
@Isotop7 See #30611

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/30611
