### ISSUE TITLE
Can't activate word wrap

### ISSUE THREAD

**Issue by TomVal** [Microsoft/vscode#30875]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open text with lines longer than screen width
2. Click View/Toggle Word Wrap (or press Alt+Z)

Expected result: the long line is wrapped into more screen lines
Current result: nothing happens

**Comment by adamvoss** [comment]
I confirm this on Linux Ubuntu/Mint.  I believe it just happened with the 1.14.1 release.

**Comment by adamvoss** [comment]
Just downgraded versions till it worked (this feature if very important to me in some projects).  Looks like it was introduced in 1.14, 1.13.1 is working fine.

**Comment by rebornix** [comment]
Sorry I can't reproduce this issue on 1.14. Can you check whether you've touched `editor.wordWrap` setting in your personal settings file or workspace settings.

**Comment by adamvoss** [comment]
I see I have:

```
"editor.wordWrap": true,
```

in my user settings.  It also tells me that is invalid and should be a string.

**Comment by femot** [comment]
See #30892 (added more info there)
