### ISSUE TITLE
Screen doesn't follow cursor beyond screen's edge when using multiple cursors

### ISSUE THREAD

**Issue by 01abhishekjain** [microsoft/vscode#30878]
- VSCode Version: 1.14.1
- OS Version: OSX Sierra 10.12.4

Steps to Reproduce:

1. Drop multiple cursors
2. Move the cursor to a place beyond the edge of the screen
3. content wont move with cursor, basically hiding the cursor.

Reproduces without extensions: Yes
![untitled2](https://user-images.githubusercontent.com/11534188/28283580-c2d0423a-6b4b-11e7-8fbb-765b59a28c3a.gif)

**Comment by alexdima** [comment]
Let's track in #6995
