### ISSUE TITLE
Newline (enter/ctrl+enter) still auto indents.

### ISSUE THREAD

**Issue by VinceMalone** [microsoft/vscode#30872]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
EditorConfig|Edi|0.9.4
tslint|eg2|0.16.0
typescript-javascript-grammar|ms-|0.0.23

---

Steps to Reproduce:

```
"editor.formatOnType": false,
"editor.autoIndent": false
```

1. Change lang mode to JavaScript.
2. Insert into editor:
```js
var x = {

};
```
3. Ensure there is no whitespace in the empty line from the code in step 2.
4. Create a newline from the empty line (`enter`/`ctrl+enter`)

Reproduces without extensions: Yes

The expected result, at least historically, is that the new line doesn't auto indent.

**Comment by DaanDeMeyer** [comment]
Not sure if this is the right place to post this, but I'm also having an issue with indentation in C++ source files after a newline. I'm not using the VSCode C++ extension so I'm assuming this behaviour is coming from stock VSCode.

When writing a function definition, after writing the opening brace (vscode automatically inserts the closing brace) and pressing Enter, vscode indents the next line and closing brace way too far. I've not found a setting to disable this. Setting `autoIndent` to false does not change the behaviour.

Example:

Before:

```c++
void IQuicHttpStream::OnReadComplete(CompletionOnceCallback callback,
                                     int result) {<cursor-is-here>}
```

After pressing Enter:

```c++
void IQuicHttpStream::OnReadComplete(CompletionOnceCallback callback,
                                     int result) {
                                       <cursor-is-here>
                                     }
```

Desired:

```c++
void IQuicHttpStream::OnReadComplete(CompletionOnceCallback callback,
                                     int result) {
  <cursor-is-here>
}
```

**Comment by rebornix** [comment]
For the original issue, you will not see auto indent when setting `"editor.autoIndent": "none"`.
