### ISSUE TITLE
Odd green and black horizontal lines in diff editor

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#30885]
- VSCode Version: 1.14.1, Doesn't repro on 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a multiple line change to a file.
2. Bring up the diff view (either inline or side by side mode).
3. Scroll the diff out of view then back into the editor.

Odd bright green and black horizontal lines appear in the diff view.

![wierd lines](https://user-images.githubusercontent.com/12818376/28291453-655bf186-6aff-11e7-8a6e-1bdce8ca778d.png)

Reproduces without extensions: Yes

**Comment by gregvanl** [comment]
Here's the green lines if the current line is outside the added region.
![wierd lines](https://user-images.githubusercontent.com/12818376/28291524-aaf2a762-6aff-11e7-8fb1-ee008abd0a3f.png)

**Comment by gregvanl** [comment]
Repros on all in-the-box themes (Dark+, Light+, Abyss, Red, etc).
I'm using an Asus laptop with Intel HD Graphics 4000.

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/28293352-95315640-6b08-11e7-9457-722218f9413c.png)

**Comment by alexandrudima** [comment]
@gregvanl @rebornix  Are you using a zoomLevel different than 0 ? (i.e. does View > Reset Zoom resolve the issue? )

**Comment by gregvanl** [comment]
No, using default zoom level 0. To get it to repro, I've often had to scroll the diff region out of view and then back in.

**Comment by alexandrudima** [comment]
@gregvanl Is Windows configured to use scaling?

i.e. is this at 100% or some other value:
<img width="488" alt="screen shot 2017-08-10 at 18 22 55" src="https://user-images.githubusercontent.com/5047891/29180733-fa7d5f28-7df8-11e7-9c92-1e65c3806a4e.png">

**Comment by gregvanl** [comment]
I'm set at 125% but also repros at 100%
