### ISSUE TITLE
JSON copy-paste results in truncated text on Mac

### ISSUE THREAD

**Issue by zhmur** [Microsoft/vscode#30887]
- VSCode Version: 1.14.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Copy-paste JSON into the editor:
```
{"token":"KELNl4n1WxJBd582ySec0w3Z","team_id":"T4SP6MBMX","api_app_id":"A6051HHRD","event":{"type":"message","user":"U4TDQ4BA6","text":"Test test INC0000037 test INC0000032","ts":"1500328326.246566","channel":"G5ZCYLQ4D","event_ts":"1500328326.246566"},"type":"event_callback","authed_users":["U69JFNZAR"],"event_id":"Ev6B2MLZK9","event_time":1500328326}
```
2. Result:
<img width="1022" alt="screen shot 2017-07-18 at 00 58 51" src="https://user-images.githubusercontent.com/8842448/28291711-4e6eb670-6b54-11e7-970a-43c4aecaa16c.png">

Selected file type: Plain Text.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Can you try to run vscode without extensions by running `code --disable-extensions` and see if you can still reproduce?

**Comment by zhmur** [comment]
Can't reproduce after VSCode restart. Think can be closed.
