### ISSUE TITLE
File browser enhancement 

### ISSUE THREAD

**Issue by DAddYE** [Microsoft/vscode#30886]
Hi guys,

There are few things I miss from [Nerdtree](https://github.com/scrooloose/nerdtree).

Most notably:

1. Ability within the file browser to search filenames and dirnames so I can easily jump / navigate within very large file structures
2. Add more commands like the one provided by [File utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils)

<img width="550" alt="screen shot 2017-07-17 at 2 44 11 pm" src="https://user-images.githubusercontent.com/6537/28291501-9238753a-6aff-11e7-9188-46c646a5e1eb.png">
<img width="307" alt="screen shot 2017-07-17 at 2 43 58 pm" src="https://user-images.githubusercontent.com/6537/28291502-92398eca-6aff-11e7-8d56-be0c4487254c.png">

**Comment by isidorn** [comment]
Duplicate. You can search our issue repository to find the original issue and upvote it. Thanks
