### ISSUE TITLE
C/C++ Code format,

### ISSUE THREAD

**Issue by RodAgrto** [Microsoft/vscode#30880]
C/C++ code format add spaces after pointer operators *, &  and  splits **->** .

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
python|don|0.6.7
vscode-html-css|ecm|0.1.7
code-runner|for|0.6.26
azure-functions-tools|joh|0.3.0
vscode-codemetrics|kis|1.8.0
perl-debug|mor|0.2.3
cpptools|ms-|0.12.0
debugger-for-chrome|msj|3.1.6
vscode-for-node-js-development-pack|nod|1.0.1
vscode-docker|Pet|0.0.16
vscode-format|rya|0.0.6
tt|sam|0.0.4
perltidy|sfo|1.1.1
code-settings-sync|Sha|2.8.2
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the vscode c++ extension here https://github.com/Microsoft/vscode-cpptools
