### ISSUE TITLE
Code hangs when trying to open C# File

### ISSUE THREAD

**Issue by leadZERO** [Microsoft/vscode#30884]
I have a CSharp file that will cause Code to become unresponsive every time it is opened. I've tried to narrow it down to what about the file causes it, but it doesn't seem to be a single line, nor consistent. I've uninstalled all the extensions, tried running with --disable-extensions, and closing the active folder. I've also run code with --verbose, but it doesn't report anything after the arg display other than:

[main 3:02:30 PM] IPC#vscode-machineId
[main 3:02:30 PM] IPC#vscode-workbenchLoaded
[VS Code]: detected unresponsive 

I'd be happy to email the file to one of the devs, but don't want to post on the open Internet.

R

- VSCode Version: 1.14.1
- OS Version: OS X 10.12.5

Steps to Reproduce:

1. Launch Code
2. Try to open file.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#79
