### ISSUE TITLE
It failed to install pylint

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#30893]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
prettify-json|moh|0.0.3
cpptools|ms-|0.12.0
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1. Click 'Install' when it pop up the prompt for pylint installation.
The command failed to execute because lack of '&'
![image](https://user-images.githubusercontent.com/1937472/28296754-af475a18-6b9c-11e7-9749-f5e4ced03494.png)

Reproduces without extensions: No

**Comment by isidorn** [comment]
This issue has nothing to do with vscode from what I see. You would get the same problem if you try that from a command line outside of vscode.
For questions on how to solve this I recommend going to stack overlfow

**Comment by hanbaobao2005** [comment]
@isidorn , I know what you mean and what I mean is
1. the command is not inputted by me
2. it was executed automatically when I click 'Install' when the pylint installation prompt pop up.

**Comment by isidorn** [comment]
@hanbaobao2005 then it triggered by the pylint extension, so please file this issue in their github repository. Thank you

**Comment by hanbaobao2005** [comment]
The prompt is triggered by the extension. Extension: Python prompts me to install pylint with executing an incorrect command.
