### ISSUE TITLE
Angular ngif less than syntax highlighting

### ISSUE THREAD

**Issue by mterczynski** [Microsoft/vscode#30891]
![image](https://user-images.githubusercontent.com/27309340/28294388-190bddd6-6b5a-11e7-830b-3116c486e9a1.png)

"Greater than" works fine:
![image](https://user-images.githubusercontent.com/27309340/28294408-4738802e-6b5a-11e7-85e9-56286939d0a8.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#70
