### ISSUE TITLE
previewHtml() support to define the server root path

### ISSUE THREAD

**Issue by flynnwt** [Microsoft/vscode#3089]
0. Is scripting enabled?   (#2099 implies so, but I'm not seeing it)
0. Can the server root path be configured?  It looks like by default it's pointing somewhere in the vscode executable path, so references have to be absolute.

**Comment by egamma** [comment]
Re 1) Scripting is currently not enabled see also: #2912.
Re 2) Currently not, tagged as a feature request.

**Comment by jrieken** [comment]
@flynnwt Idea is to set the base to the workspace URI
