### ISSUE TITLE
The node debugging problems

### ISSUE THREAD

**Issue by Cyclone77** [Microsoft/vscode#30896]
![Animation display](https://raw.githubusercontent.com/Cyclone77/JavaScript/master/123.gif)

**Can't enter the breakpoint, is this why? But occasionally will enter again!**
**不能进入断点,这是为什么?但是偶尔会再次进入!**

**Comment by weinand** [comment]
I do not understand what you mean by "Can't enter the breakpoint"?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
