### ISSUE TITLE
The terminal shortcut key is wrong

### ISSUE THREAD

**Issue by smalllong** [Microsoft/vscode#30898]
- VSCode Version: 1.14.1
- OS Version: windows 8.1

In the menu, the shortcut key is "ctrl + `".
However, I can't call terminal out using "ctrl + `". But I use "ctrl + shift + `" can call terminal out.

**Comment by Tyriar** [comment]
There are 2 keybindings:

```js
{ "key": "ctrl+`",                "command": "workbench.action.terminal.toggleTerminal" },
{ "key": "ctrl+shift+`",          "command": "workbench.action.terminal.new" },
```

ctrl+` is meant to toggle the terminal, which will create a terminal if it doesn't exist. Is this not happening?

**Comment by smalllong** [comment]
Yes, ctrl+` won't create a terminal in my machine.

**Comment by cleidigh** [comment]
@smalllong 
This works fine for me on Windows 7, Code 1.14.2
Perhaps it is a key binding conflict. Have you tried to disable all your custom key bindings
and verify in the key binding editor that it has the correct key assignment?

**Comment by smalllong** [comment]
@cleidigh I found that ctrl + ` is a shortcut key for QQ pinyin input so it conflicts. I closed the QQ pinyin shortcut and then the vs code works fine.

**Comment by Tyriar** [comment]
Makes sense, thanks for clearing that up @smalllong 👍
