### ISSUE TITLE
Missing a MRU list in search & replace tab

### ISSUE THREAD

**Issue by Huseriato** [Microsoft/vscode#30899]
- VSCode Version: 1.14.1
- OS Version: Windows 10

It would be really nice to have a simple mru list for the latest searches. Sometimes when refactoring or navigating through code I need multiple searches. With a MRU it would be easy to switch between different results. I wondering that there are so much powerful features every release, but such a basic simple thing is missing. 😄

**Comment by roblourens** [comment]
You can use alt+tab to toggle through past search queries - hope that helps.

**Comment by Huseriato** [comment]
That does not work with windows. Alt+Tab switches between applications.

**Comment by roblourens** [comment]
Sorry, I meant alt+up/down. Late night githubbing.

**Comment by Huseriato** [comment]
Thank you, I really missed that.
