### ISSUE TITLE
Proposal: Add support for bash/sh file type

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#309]
Please add bash/sh file type support (code highlight, code complete, symbol navigations)

shell script programming were very common development in unix/linux world.

If you can provided support for it. that's would be very impressive feature.

**Comment by Tyriar** [comment]
Note that code highlighting already exists for shell scripts, the following extensions are supported: ".sh", ".bash", ".zsh", ".bashrc", ".bash_profile", ".bash_login", ".profile", ".bash_logout"

**Comment by joaomoreno** [comment]
Perfect opportunity to shine as an extension author. ;)

**Comment by himanshub16** [comment]
Please provide this feature. Syntax highlighting for bash works fine. But, there's much more support required. For example, after if, adjacent "fi" gets automatically aligned.. etc. If there's any extension available for it, please provide a link to it (I couldn't find any).

**Comment by adampfoster** [comment]
Syntax highlighting is one (very small) thing, but utilising ~/.bash_profile within VS Code terminal, opens the door to the flexibility that ~/.bash_profile provides to a dev on their machine, to access their own custom aliases and functions for example.

**Comment by Tyriar** [comment]
@adampfoster `~/.bash_profile` will run by default on macOS in the upcoming v1.11. This issue is more about code navigation in bash.

**Comment by adampfoster** [comment]
@Tyriar ok apologies for my confusion. Great to hear about ~/.bash_profile running in 1.11 :)

**Comment by mjbvz** [comment]
Closing as shell language support can be added by an extension. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about writing a language extension
