### ISSUE TITLE
Node.js debug causes tons of lag in editor - high CPU/Memory

### ISSUE THREAD

**Issue by JWess** [Microsoft/vscode#30903]
- VSCode Version: I reproduced this issue with the latest Insiders build and regular build, but the issue does not occur when using 1.13.1.
- OS Version: Windows 8.1
- Node Version: 6.10.0 (64-bit)

Steps to Reproduce:

1. F5 to start my app.
2. Navigate to any page. Refresh it quickly a few times. Notice that CPU of VSCode goes up to 12-ish percent. Memory starts climbing. Editor becomes mostly unresponsive...can't even click on the "stop debugging" button or move my cursor. After 10-30 seconds, CPU goes back to 0%, and VSCode becomes responsive again.

When I tried this in 1.13.1, the CPU never goes higher than 1% and stays at 0% most of the time. 

I tried using typescript 2.3.4 just in case my issue was typescript related (even though my project doesn't have any typescript), and that didn't make a difference.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@JWess Could you share your launch.json?

**Comment by JWess** [comment]
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}\\bin\\www",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "babel",
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],

            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": false,
            "outFiles": []
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outFiles": [],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}
```

**Comment by weinand** [comment]
@JWess does it make a difference if you disable (or remove) the `"preLaunchTask": "babel"` temporarily?

**Comment by JWess** [comment]
I just tried that...no difference.

**Comment by JWess** [comment]
I just updated to the latest VS Code Insiders (1.15.0-Insider), and this issue is no longer happening.
