### ISSUE TITLE
Color for 'cursor' for sass (SCSS) is wrong

### ISSUE THREAD

**Issue by Binaryify** [Microsoft/vscode#30907]
- VSCode Version:1.14.1
- OS Version: 10.12.5
'cursor' had wrong color in SCSS file, but in the css file it had right color
![image](https://user-images.githubusercontent.com/12221718/28305141-1a491574-6bcd-11e7-8e66-bf9c342983ec.png)
![image](https://user-images.githubusercontent.com/12221718/28305153-21d9d08a-6bcd-11e7-8292-d0aca564563c.png)
 The 'cursor' key had the same scope with html tag in the 'scss' file
![image](https://user-images.githubusercontent.com/12221718/28305185-41968a3a-6bcd-11e7-8aea-5669b3e43649.png)
![image](https://user-images.githubusercontent.com/12221718/28305188-46ca8718-6bcd-11e7-8601-1de8e1605246.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#226
