### ISSUE TITLE
New insiders: extensions side bar empty

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#30902]
![1](https://user-images.githubusercontent.com/11925432/28303287-f4fcac02-6bc4-11e7-8fda-d54213ccf800.jpg)

![2](https://user-images.githubusercontent.com/11925432/28303304-1271608e-6bc5-11e7-8579-2f6711f32e3a.jpg)

and this link is broken..

![3](https://user-images.githubusercontent.com/11925432/28303388-7cfbccb4-6bc5-11e7-87c4-371cd30da462.jpg)

**Comment by sandy081** [comment]
@joaomoreno Looks like [extensionManagementService.getInstalled()](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L207) call is not returning. Do you know why?

**Comment by vvs** [comment]
Same here, and once I click on the "Extension button", the VS Code starts to behave very weirdly. Git tab is empty, search tab looks weird and incorrect.

`Help -> Report Issues` doesn't work as well. :)

I am on the latest Insiders Build: 1.15.0-insider (3245039b4f78).

**Comment by sandy081** [comment]
Further investigating.. I see that Shared process is broken and hence methods to shared process services are not returning. Here are the logs from Shared process

![image](https://user-images.githubusercontent.com/10746682/28312658-89d7f97e-6bd1-11e7-988e-5afbbb4baa28.png)

**Comment by sandy081** [comment]
Some how #30759 broke the Shared Process which caused this.

Thanks @joaomoreno for reverting #30759 in #30923

**Comment by duanehutchins** [comment]
Same here.

If I try to open "Extensions: Install Extension," I get the error `Cannot read property 'getHTMLElement' of undefined`

![image](https://user-images.githubusercontent.com/1530028/28316020-f8591312-6b8e-11e7-9ffc-03d6cfc7502c.png)

**Comment by sandy081** [comment]
Yes there is a new insiders build with the fix. Please update to it.

**Comment by jtsom** [comment]
Hm. It did update (or downgrade) to the previous insiders release, but I'm not seeing anything new yet. (OS X version is 3cfa565abbd6e162b7ae6f3055c231128da63df2).

Thx, I'll keep checking.

**Comment by sandy081** [comment]
Sorry I just checked that we downgraded first (which makes sense) and span new builds with the fix. New builds are not not released and not generated for all platforms yet. Will check on that and let you know.

**Comment by sandy081** [comment]
Today's insiders has the fix.
