### ISSUE TITLE
don't create .vscode subdirectory where I opened vscode

### ISSUE THREAD

**Issue by bialix** [Microsoft/vscode#30905]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.8.2
python|don|0.6.7
LogFileHighlighter|emi|1.1.1
innosetup|idl|0.7.3
MagicPython|mag|1.0.10

---

Steps to Reproduce:

1. After last updates VS Code started to create .vscode folder every time I open it from command line, using following command:

`code .`

2. Check the directory with command 

```
C:\\some\\path>dir /b
.vscode
...
```

I don't want this junk everywhere I work with Code. And there was no such behavior before.

Reproduces without extensions: No

**Comment by bialix** [comment]
I probably found the extension that causes this: Python. Will try to contact the author.

**Comment by isidorn** [comment]
Caused by extension, please file the issue in the extension repo. Thanks
