### ISSUE TITLE
Enhance tab (hover) styling

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#30901]
1.  Hover over tab
 2. Hover over close tab icon

1:
current:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9638156/28302304-2d7a6932-6b95-11e7-81cd-3eacffd3ac97.gif)
desired:
![555](https://user-images.githubusercontent.com/9638156/28302545-b38093f2-6b96-11e7-89bc-e31b0af58dfb.gif)

2:
vscode:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9638156/28302381-9c334aa6-6b95-11e7-9a97-9ee85eda29e2.gif)

chrome:
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/9638156/28302392-a6ed4352-6b95-11e7-80a7-29446ae33d8a.gif)

**Comment by bpasero** [comment]
Thinking of introducing a couple of new colors:
* hover background
* hover border

This would enable stuff like this:

![before](https://user-images.githubusercontent.com/900690/33756365-7be1a146-dbf5-11e7-9e12-15b68c59a1b4.gif)

**Comment by bpasero** [comment]
Added new colors:
* `tab.hoverBackground`: Tab background color when hovering
* `tab.unfocusedHoverBackground`: Tab background color in an unfocused group when hovering
* `tab.hoverBorder`: Border to highlight tabs when hovering
* `tab.unfocusedHoverBorder`: Border to highlight tabs in an unfocused group when hovering
