### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wuyasong** [Microsoft/vscode#30900]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|0.0.2
html-class-suggestions|And|1.0.7
vscode-color|ans|0.4.1
jsrefactor|cms|1.3.0
vscode-wxml|cod|0.1.9
jquerysnippets|don|0.0.1
python|don|0.6.7
vscode-html-css|ecm|0.1.7
vscode-npm|fkn|3.3.0
node-module-intellisense|lei|1.3.0
ftp-sync|luk|0.3.3
MagicPython|mag|1.0.10
debugger-for-chrome|msj|3.1.6
js-patterns-snippets|nik|0.0.5
vetur|oct|0.9.1
ejs-language-support|Qas|0.0.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1.win10 睡眠后唤醒  原本打开的vscode编辑器会出现未响应的情况（白屏），点哪都不管用，只能点叉子关了重新启动

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps. Thanks
