### ISSUE TITLE
The snippet error and program crash in Developer mode.

### ISSUE THREAD

**Issue by LiarOnce** [Microsoft/vscode#30914]
- VSCode Version: 1.14.1
- OS Version: Windows 10 Pro 1703

When I debug my plugin, there is a code snippet obfuscated of the tips, which in the previous version of VSCode have not appeared.

And the program crashed when I wanted to use the developer mode for further debugging, So I did not see more errors.

Steps to Reproduce:

1.Press Ctrl+Shift+I --> Console tab(A certain probability)
![snipaste_20170718_165324](https://user-images.githubusercontent.com/11171892/28308885-345f7cb6-6bda-11e7-90dd-aebd0f13b990.png)

2.There was a snippet confusing error, but I did not know where it caused confusion in debugging.
These are part of the code snippet that has the problem:
```
"do … until …": {
	"prefix": "dountil",
	"body": [
		"do {",
		"\t${4:STATEMENT}",
		"} until (${1:${2:$a} <= ${3:10}});"
	],
	"description": "Do-until loop"
},
"while …": {
	"prefix": "while",
	"body": [
		"while (${1:$a <= 10}) {",
		"\t${2:STATEMENT}",
		"}"
	],
	"description": "While-loop"
},
```

**Comment by jrieken** [comment]
The problem with the snippets is the usage of `$a` which in the TM Snippet Syntax references to a variable. To get that text inserted as is use backslashes to escape the dollar, `\\$a` or have a placeholder for it, e.g. `${3:a}`. Note that this isn't an error but an information message to make sure snippets eventually get migrated.
