### ISSUE TITLE
bin directory

### ISSUE THREAD

**Issue by itmitica** [Microsoft/vscode#30919]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.1
csharp|ms-|1.11.0
seti-icons|qin|0.1.3
ab-html-formatter|zov|0.0.2

---

Steps to Reproduce:

1. create a bin directory inside a solution directory
2. the bin directory does not appear on file explorer

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
It is probably hidden, check your user and workspace setting for `files.exclude`. Also try to reproduce with no extensions.

I can not reproduce this problem

**Comment by itmitica** [comment]
You are correct, I had this and forgot about it. I'm sorry.

```
    "files.exclude": {
        "**/bin": true,
        "**/obj": true,
    },
```
