### ISSUE TITLE
Color theme does not recognize all the keywords as it used to

### ISSUE THREAD

**Issue by bvanderplanck** [Microsoft/vscode#30917]
* VSCode Version:
** Version 1.14.1
** Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
** Date 2017-07-13T19:12:01.887Z
** Shell 1.6.6
** Renderer 56.0.2924.87
** Node 7.4.0
- OS Version: Linux Mint XFCE 18.1

It looks like some keyword in PHP are missing making the color theme not being applied to all of them.
You will find below a screenshot comparing the current VS Code PHP keyword and how it uses to be:

**_Now_**
![image](https://user-images.githubusercontent.com/17257969/28310543-1cce172e-6bad-11e7-8cf4-2e7795002d27.png)

**_Before_**
![image](https://user-images.githubusercontent.com/17257969/28310582-31981722-6bad-11e7-96f1-f8b175969323.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
The `default` keyword is tracked in https://github.com/atom/language-php/issues/236.

The static class accessor is tracked in https://github.com/Microsoft/vscode-textmate/issues/50.
