### ISSUE TITLE
Status bar color can not be set in multi root workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#30915]
Refs: #30722

1. Have the following user settings

```json
"workbench.colorCustomizations": {
		"statusBar.foreground": "#828c99",
		"statusBar.background": "#ffffff",
		"activityBar.background": "#ffffff",
		"activityBar.foreground": "#828c99",
		"activityBarBadge.background": "#b3b2b1",
		"activityBarBadge.foreground": "#fff",
		"editor.background": "#fafafa"
	},
"workbench.colorTheme": "Default Light+",
```
2. Notice that the status bar has some funky blue color instead of the white color which I configured it to.. Changing the statubBar.background color to anything else has no effect

**Comment by bpasero** [comment]
@isidorn I added a new color when you are in workspace state, to override you have to set:

```json
"workbench.colorCustomizations": {
    "statusBar.multiFolderBackground": "#ffffff",
    "statusBar.multiFolderForeground": "#828c99"
}
```

Not sure we decide to keep this color, but we wanted to indicate explicitly that you are in workspace context through a new color.
