### ISSUE TITLE
Cannot split editor to more than 3 groups

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#30911]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
gherkin-indent|Ara|2.0.0
vscode-bad-code-highlighter|bha|0.1.6
vscode-markdownlint|Dav|0.9.1
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
vscode-turtle|fei|1.0.30
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
php-pack|fel|1.0.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.1.1
crane|Hvy|0.3.6
phpcs|ika|0.7.0
format-indent|Kas|1.3.0
phpmd|lin|1.1.4
vscode-apache|mrm|1.1.1
vscode-duplicate|mrm|1.1.0
oracle-plsql|myc|1.0.3
selectline-statusbar|tom|0.0.2
gitblame|wad|1.11.3
twig|wha|1.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. split editor to 3 groups
2. trying to split editor from now on does nothing

Reproduces without extensions: Yes

I would expect to be able to split the editor as many times as I want. Maybe a have a 21:9 monitor or I write really narrow files or all my split editors are folded on the side.

Thanks for your effort.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14909
