### ISSUE TITLE
truncated window on startup in i3wm on ubuntu

### ISSUE THREAD

**Issue by abonec** [Microsoft/vscode#30910]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.4.0-83-generic (Ubuntu 16.04 with i3wm window manager)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.7
vscode-babel-coloring|dza|0.0.4
tslint|eg2|0.16.0
Go|luk|0.6.62
cpptools|ms-|0.12.0
Ruby|reb|0.12.1
vim|vsc|0.9.0

---

Steps to Reproduce:

1. Open project in i3wm environment on ubuntu
2. Got a some window:
![image](https://user-images.githubusercontent.com/240587/28307721-795016ba-6bac-11e7-8eb8-94b75898eb7f.png)

Reproduces without extensions: Yes

**Comment by abonec** [comment]
I think it's related to the specific window manager (i3wm) and sometimes it appears in other programs but basically, i3wm works fine with all kind of windows appeared in the system. I don't know what problem is, may be window size should be set up explicitly or something else.

By any way I don't even know what this window about and what to do. This window appears on every vscode start up and disappeared after entering pressing but appears again after new start-up

**Comment by Tyriar** [comment]
@abonec When you see the window could you open devtools (Help > Toggle Developer Tools) and try to inspect the element?
