### ISSUE TITLE
OPEN EDITORS: open files not shown as expected by explorer.openEditors.visible

### ISSUE THREAD

**Issue by javafuns** [Microsoft/vscode#30913]
- VSCode Version: Version 1.14.0 (1.14.0)
- OS Version: Mac OS 10.12.5 (16F73)

Steps to Reproduce:

1. set "explorer.openEditors.visible": 10 // Number of editors shown in the Open Editors pane. Set it to 0 to hide the pane.
2. Keeping opening files, only 3, or 4, or sometimes 4 files are shown in OPEN EDITORS pane.
3. lauhcn with `code --disable-extensions`, repeat step 2, all of opened files shown in OPEN EDITORS pane, the number of opened files is more than limit.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Can you please try reproducing with the latest vscode insiders https://code.visualstudio.com/insiders

If yes, can you attach an animated gif / video showing this?
Do you just have one editor group open or multiple?
