### ISSUE TITLE
Extension host terminated Unexpectedly

### ISSUE THREAD

**Issue by DanielContreras18881** [Microsoft/vscode#30916]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Extension host terminated Unexpectedly appears continuously, just open an wait

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
If you open the developer tools, do you see anything interesting in there?
