### ISSUE TITLE
Include Only a number of folders inside a solution

### ISSUE THREAD

**Issue by eyeris** [Microsoft/vscode#30921]
vscode currently support only including folders inside a solution.
```
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true

}
```
However, its very useful to add` include` option to add only a selected/filtered list of directories to the solution.

**Comment by isidorn** [comment]
I think this is a duplicate of multi root folder work we are currently working on
