### ISSUE TITLE
Merge conflict reference added to file as text

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#30928]
- VSCode Version: 1.14.1
- OS Version: Windows 10 Pro, 10.0.15063.483

Steps to Reproduce:

1. When files have merge conflict it shows the `<<<<<<< HEAD` and `=======` within the file.
2. Resolve merge conflicts and then commit
3. Review committed file and those references are now part of the file and committed.
![image](https://user-images.githubusercontent.com/11204251/28316760-b5956062-6b89-11e7-9a0a-459c8dda7e1d.png)

Reproduces without extensions: Unknown, can't reproduce the merge conflict now

**Comment by chrmarti** [comment]
The references are written to the file by Git (or any other semi-automatic merge). You seem to have missed that conflict and forgotten to resolve it before creating the commit. Sound plausible?

**Comment by wsmelton** [comment]
Nope. On files I did resolve the conflict the actual text is added to the file and does not get removed.

So now each time you open a file that has that text the CodeLens is kicking in like it has a conflict, but the Git side bar is not showing any merge conflicts.

**Comment by wsmelton** [comment]
As well, if this is an issue with Git why is it now just showing up since the CodeLens feature was added to Code. I have had conflicts before and NEVER had this problem.

**Comment by chrmarti** [comment]
To clarify: The textual annotation of merge conflicts is not added by VSCode, it is added by Git's merge / rebase / etc.. VSCode simply decorates that kind of text with the code lenses. The code lenses show independently of whether Git sees a merge conflict or not because the textual annotations can also be added by other SCMs or CLIs like `patch`.

**Comment by wsmelton** [comment]
So if I use Git CLI and stop using Code I should not have the issue?

**Comment by chrmarti** [comment]
You get the textual annotations from the Git CLI. No VSCode involved. VSCode only adds the code lenses. Maybe I'm missing something?

**Comment by wsmelton** [comment]
So I went through to build out a duplication of this issue...it could be a Git issue but it seems VS Code is not making it clear that I'm viewing a merged conflict file, it appears I'm just editing a "normal" file.

[git_repo_conflict_2.zip](https://github.com/Microsoft/vscode/files/1156681/git_repo_conflict_2.zip)

I mean if you open a file to see the merge conflict but are not going to take action and close, and you have auto save enabled in Code...then that file just changed. The annotations are now part of the file so there is no longer a merge conflict, which I'm assuming is why it let me commit without resolving the conflict (since there wasn't one).

**Comment by chrmarti** [comment]
The Git Merge... command runs `git merge new_branch` after which the file has the content you are reporting. You will get the same result from running `git merge new_branch` and then immediately opening the file in Notepad.

**Comment by wsmelton** [comment]
So if we want to use Code for viewing merge conflict I have to make sure any auto save setting is turned off in VSCode. 

If you save the file before you resolve the conflict with the CodeLens in VSCode those annotations are saved to the file.

Unless you see an alternative I will let folks know about it that contribute to our repo using VSCode. 

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wsmelton** [comment]
Is there any option that can be done to open the file with merge conflict that will prevent the ability to overwrite the original file until the conflict is resolved. Or at most show some indicator, opening a file where the conflict is hundred lines down out of view I don't see any way of knowing. You don't have to open the merge conflict file from the git sidebar. It seems VSCode reads the annotations as being a merge conflict file straight out.

_Sent from my Samsung SM-G900V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chrmarti** [comment]
There is a misunderstanding: It is Git that adds that text, not VSCode. You will get the same result using Git and Notepad.

**Comment by wsmelton** [comment]
It is Code saving the text. No misunderstanding on where the annotations are coming from it is how they are getting saved in the file: because I'm using VS Code to look at the file.

Notepad will not prompt me to save the file, nor does it offer an auto-save feature so it will never happen in Notepad unless I manually save the file.

I'm clear on why the issue happened and that I don't need to use VS Code to view files with a merge conflict.
