### ISSUE TITLE
lua format

### ISSUE THREAD

**Issue by darklost** [Microsoft/vscode#30924]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.2.0
python|don|0.6.7
text-transform|flo|0.1.0
sproto-support|ily|0.0.1
vscode-icons|rob|7.10.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Is this a request to add format for lua files? This would be something to be provided by an extension.
Check out the market place. E.g. https://marketplace.visualstudio.com/items?itemName=stanzilla.vscode-luaformatter
