### ISSUE TITLE
Status bar theme color overrides are not followed in work space mode

### ISSUE THREAD

**Issue by kannan-balasubramanian** [Microsoft/vscode#30920]
- VSCode Version:1.15.0-insider
- OS Version: Windows 10 64-BIT (v1607 - OS Build: 14393.1358)
- VSCode Date: 2017-07-17T05:15:46.760Z

Steps to Reproduce:
1. Applied the following theme in user settings.
2. For status bar, the theme color is followed when in non-workspace mode.
3. But in workspace mode, the theme colors are not followed, and the status bar stays in dark blue color.

Please check attached images.

`{
    "workbench.iconTheme": "material-icon-theme",
    "material-icon-theme.showUpdateMessage": false,
    "workbench.colorTheme": "One Dark+ (Sublime)",
    "workbench.colorCustomizations": {
        "editor.background": "#000000",
        "editor.lineHighlightBackground": "#333333",
        "activityBar.background": "#000000",
        "activityBar.border": "#333333",
        "sideBar.background": "#000000",
        "sideBar.border": "#333333",
        "editorGroup.background": "#000000",
        "editorGroup.border": "#333333",
        "editorGroupHeader.tabsBackground": "#000000",
        "editorGroupHeader.tabsBorder": "#333333",
        "tab.inactiveBackground": "#000000",
        "tab.activeBackground": "#333333",
        "tab.border": "#333333",
        "tab.unfocusedActiveForeground": "#000000",
        "tab.border": "#333333",
        "statusBar.background": "#000000",        
        "statusBar.border": "#333333",
        "statusBar.noFolderBackground": "#000000",
        "statusBar.activeBackground": "#000000",        
        "button.background": "#333333",
        "dropdown.background": "#333333",
        "dropdown.border": "#333333"
    },
    "material-icon-theme.folders.icons": "blue"
}`

Reproduces without extensions: Yes

![without-workspace](https://user-images.githubusercontent.com/30168417/28311898-c5f308de-6bce-11e7-9811-f62f88f8e6b0.png)
![with-workspace](https://user-images.githubusercontent.com/30168417/28311910-cfbec632-6bce-11e7-9a7b-64d8bb4adede.png)

**Comment by bpasero** [comment]
We should maybe derive the color.

**Comment by bpasero** [comment]
You can use: `statusBar.multiFolderBackground`

**Comment by kannan-balasubramanian** [comment]
Thanks @bpasero, it worked!

But the documentation for `statusBar.multiFolderBackground` is missing at [theme color reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference)

Request you or the relevant team to add it.

**Comment by bpasero** [comment]
Added via https://github.com/Microsoft/vscode-docs/commit/7e7223ffd9f85ec81d65f3bea0c31a4a5bdb5e27

It is not 100% clear yet that we keep this color.
