### ISSUE TITLE
Lightbulb / quick fix is referencing the old filename after rename

### ISSUE THREAD

**Issue by khellinx** [Microsoft/vscode#30929]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
bower|don|0.0.3
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
vscode-nuget-package-manager|jmr|1.1.4
Angular2|joh|2.4.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vscode-gulp|tan|0.0.4

---

Steps to Reproduce:

1. Create/Open a c# project
2. Create/Open a file
e.g. test.cs
3. Write some new code using a type not included in the referenced usings
e.g. (IEnumerable is an unknown type because the System.Collections.Generic namespace is not included in the using statements):
```
namespace MyApp
{
    public class Test
    {
        public IEnumerable<string> GetStrings()
        {
            return null;
        }
    }
}
```
4. Rename the file, only changing a character casing
e.g.: test.cs to Test.cs
5. Use the lightbulb or the quick fix shortcut
6. Select 'using <namespacetoinclude>' or the '<namespacetoinclude>' from the menu.
7. VS Code will create a new file, using the old filename.
e.g.: A new file 'test.cs' will be created where the selected fix has been applied instead of fixing the issue in the renamed file.

Reproduces without extensions: N/A

**Comment by jrieken** [comment]
Please file this against the C# extension
