### ISSUE TITLE
Can't open extension view

### ISSUE THREAD

**Issue by sumanx** [Microsoft/vscode#30926]
- VSCode Version: 1.15.0-insider (1.15.0-insider), 2017-07-18T05:03:32.965Z
- OS Version: macOS 10.12

Steps to Reproduce:

1. try to open extension view, empty:
<img width="656" alt="2017-07-18 7 44 23" src="https://user-images.githubusercontent.com/620733/28315766-863cfa50-6bf2-11e7-9ec7-71fff251575b.png">

2. try to back to explorer view, an error message appears:
<img width="897" alt="2" src="https://user-images.githubusercontent.com/620733/28316036-9e97ab30-6bf3-11e7-8428-55bac0e3df73.png">

3. try to open extension view again:
<img width="887" alt="3" src="https://user-images.githubusercontent.com/620733/28316044-a9f3ef34-6bf3-11e7-9d55-9ae91505be91.png">

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Yeah, will be fixed tomorrow, sorry about that.
Duplicate
