### ISSUE TITLE
Extension view not visible after click on Extensions and problem with Activity Bar after second click on Extensions

### ISSUE THREAD

**Issue by CarlosAzocar** [Microsoft/vscode#30922]
Extension view not visible after click on Extensions and problem with Activity Bar after second click on Extensions

- VSCode Version: 1.15.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Click on Extensions 

Reproduces without extensions: Yes/No

## Extension view not visible
![step1](https://user-images.githubusercontent.com/18235355/28312199-4e837156-6b80-11e7-8ebb-7f7ac262f4d2.png)
## After second click on Extensions
![step2](https://user-images.githubusercontent.com/18235355/28312200-4eb6b714-6b80-11e7-8fe7-aa2bbbb2d55f.png)
![step3](https://user-images.githubusercontent.com/18235355/28312201-4ee716f2-6b80-11e7-8aba-280d9262ef31.png)

**Comment by duanehutchins** [comment]
Same here.

If I try to open "Extensions: Install Extension," I get the error `Cannot read property 'getHTMLElement' of undefined`

![image](https://user-images.githubusercontent.com/1530028/28316020-f8591312-6b8e-11e7-9ffc-03d6cfc7502c.png)

**Comment by isidorn** [comment]
Sorry about that, dup of https://github.com/Microsoft/vscode/issues/30902
