### ISSUE TITLE
Page Up/Down don't work in integrated terminal

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#30930]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|0.6.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
python|don|0.6.7
EditorConfig|Edi|0.9.4
matlab|Gim|0.5.0
triggertaskonsave|Gru|0.1.2
vscode-dimmer|hoo|2.1.0
docthis|joe|0.4.7
center-editor-window|kai|2.0.2
select-part-of-word|mle|1.0.1
cpptools|ms-|0.12.0
indent-rainbow|ode|0.6.1
vscode-clearcase|Ope|1.9.2
vscode-icons|rob|7.10.1
indenticator|Sir|0.4.2
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.0
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Do a build or something which generates a lot of output in the terminal.
2. Press Page Up or Down. Nothing happens.

Expected to be able to look at all of the output without using scroll bar.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
The keybinding is shift+pageup/pagedown on Windows.

**Comment by Tyriar** [comment]
You can make this just pageup/pagedown by adding these custom keybindings:

```js
{ "key": "pagedown",        "command": "workbench.action.terminal.scrollDownPage",
                               "when": "terminalFocus" },
{ "key": "pageup",          "command": "workbench.action.terminal.scrollUpPage",
                               "when": "terminalFocus" },
```

**Comment by BillDenton** [comment]
Thanks. I've reconfigured the keys using the Keyboard Shortcut editor.
