### ISSUE TITLE
Error: disposed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#30938]
Issue Id: <b>70041719-8d0b-690d-4415-271807b3509e</b><br /><br />*Versions* <br />- 1.14.1<br />*Stack* <br />Error: disposed<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L98:28](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/base/parts/ipc/node/ipc.cp.ts#L98:28)<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L92:38 (request)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/base/parts/ipc/node/ipc.cp.ts#L92:38 (request))<br />[/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 (call)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 (call))<br />[/vs/platform/telemetry/common/telemetryService.ts#L122:18 (log)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/platform/telemetry/common/telemetryService.ts#L122:18 (log))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/platform/telemetry/common/telemetryService.ts#L109:32 (then)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/platform/telemetry/common/telemetryService.ts#L109:32 (then))<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L161:34 (publicLog)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L161:34 (publicLog))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />

**Comment by joaomoreno** [comment]
This is OK.
