### ISSUE TITLE
Cannot select/copy from readonly portion in diff editor inline view

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#30935]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.1

---

Steps to Reproduce:

1. Compare any two files.
2. Make the diff view inline.
3. Try to select/copy from the readonly portion with which the file is being compared. Does not work.

Reproduces without extensions: Could not check

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/8226
