### ISSUE TITLE
VSCode window size too small when launched via associated file extension

### ISSUE THREAD

**Issue by ChadMcCaffery** [Microsoft/vscode#30936]
Steps to Reproduce:

1. Double-clicked a README.MD from a folder on my local hard drive.
2. Windows asked what app I wanted to use to open it.
3. I selected Visual Studio Code, and checked "Always use this app to open ..."
4. Clicked OK, and this was the result in the upper-left of my screen:

![image](https://user-images.githubusercontent.com/22089594/28328258-d88006ca-6b9a-11e7-8178-34cd97502819.png)

Looks like VS Code doesn't have reasonable defaults set for position and size?

Reproduces without extensions: Unknown

---
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
githistory|don|0.2.1
python|don|0.6.7
xml|Dot|1.9.2
vscode-simple-icons|Lau|1.4.1
MagicPython|mag|1.0.10
cpptools|ms-|0.12.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
python|tht|0.2.3

(1 theme extensions excluded)

**Comment by joaomoreno** [comment]
@bpasero I thought we remember the last width and height of the window and use that.

**Comment by bpasero** [comment]
Yeah we do, but maybe this is upon initial startup.

**Comment by ChadMcCaffery** [comment]
@bpasero : FYI, what is the definition of "initial startup" here? Is it when the app is run for the _very_ first time ever, or the first time after an update? I ask because I've been using VS Code for several months, but the day before this occurred I had updated it to the latest release.

**Comment by bpasero** [comment]
@ChadMcCaffery so this happens everytime even after you have resized the window to a good size? Does it restore the good size if you just start VS Code?

**Comment by ChadMcCaffery** [comment]
@bpasero Yes, normal usage seems to work just fine. I think the key is when Windows launches VS Code for a brand-new file association. However, I can't reproduce the problem. I removed all associations using assoc.exe and deleted reg keys before retrying. It launched with reasonable size.

**Comment by bpasero** [comment]
Does this still happen?

**Comment by ChadMcCaffery** [comment]
I can't repro this with latest versions, so I'm closing it.
