### ISSUE TITLE
Render Whitespaces 'all' setting does not work. (has no effect)

### ISSUE THREAD

**Issue by ramparvathaneni1** [Microsoft/vscode#30937]

**Comment by rebornix** [comment]
@ramparvathaneni1 do you mind sharing screenshot with us as I didn't reproduce this issue

![image](https://user-images.githubusercontent.com/876920/28381037-4de104f4-6c6e-11e7-80f6-d229f5cce2ef.png)

You can see after pasting the options to the settings page, whitespaces are rendered.

**Comment by ramparvathaneni1** [comment]
Hello @rebornix,

Please pardon me. I realized that the Workspace Settings are overriding my User Settings.
`.vscode/settings.json` had `"editor.renderWhitespace": "true",`
In my User Settings I had `"editor.renderWhitespace": "all",` (this is being overwritten by workspace settings).
When I corrected this, I am seeing the whitespaces.

Now I learned that Workspace Settings take priority over User Settings.

Sorry for the trouble.

Thanks a lot!

**Comment by rebornix** [comment]
@ramparvathaneni1 thank you sir!
