### ISSUE TITLE
Files with the same name, but in different views are not followed by their path

### ISSUE THREAD

**Issue by g-harel** [Microsoft/vscode#30932]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.4|
|vscode-cdnjs|JakeWilson|0.14.3|
|sort-lines|Tyriar|1.3.0|
|vscode-icontheme-nomo-dark|be5invis|1.3.2|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|auto-close-tag|formulahendry|0.4.3|
|gitblame|waderyan|1.11.3|;

---

Steps to Reproduce:

1. open file `index.html`
2. open second file also named `index.html`
3. drag one of the files to the side to split editor

![image](https://user-images.githubusercontent.com/9319710/28320312-3eead78e-6b9e-11e7-8d00-ffa8b4c92a8b.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13350
