### ISSUE TITLE
Emmet 2.0: Occasionally insertion point is misplaced

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#30934]
- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:07:20.317Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.27.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. This situation triggers this most often:
````
      <section>
        <h1>Some title</h1>
        <h2></h2>hello
      </section>
````

2. The `section`, `h1` and `h2` tags all complete as expected, but then the H2 insertion point is outside the tag.

![jul-18-2017 09-56-36](https://user-images.githubusercontent.com/835148/28320864-b24878d4-6b9f-11e7-81cf-8f8b930fc641.gif)

**Comment by ramya-rao-a** [comment]
I can repro it, not sure why this would happen though...

**Comment by Niichie** [comment]
This also used to happens when using something like `url()` where the selection would be outside of the parentheses, but it seems to be fixed, so maybe it is a similar issue to that?

**Comment by ramya-rao-a** [comment]
@Niichie I don't recall the issue you are talking about, so don't know what fixed it :)

**Comment by Niichie** [comment]
Actually, it seems it was not fixed in css!

![url](https://user-images.githubusercontent.com/16381287/28407684-06a7c2cc-6d03-11e7-9cf6-7faa3da571fa.gif)

**Comment by ramya-rao-a** [comment]
@Niichie The issue with url() snippet is unrelated to emmet. Can you log a separate issue for that?

@smlombardi I was able to repro this once when you first logged this issue, but not anymore.
Can you try again on the next Insiders (21st July)

**Comment by smlombardi** [comment]
New emmet is completely unusable at this point.  I tried to re-create but, as you can see, it doesn't even correctly suggest `<section>`.  It suggests `sect` as I type (which is not a tag AFAIK) and does not offer or complete `<section></section>` even after I type the whole tag.

![jul-21-2017 09-36-41](https://user-images.githubusercontent.com/835148/28465886-5fa989d2-6df8-11e7-9540-c260547427d6.gif)

**Comment by Niichie** [comment]
@smlombardi This is actually exactly how it works. You need to have a look at this cheat sheet. 

https://docs.emmet.io/cheat-sheet/

Basically now that emmet doesn't expand every word (woo!) It will only look for the complete abbreviation, which is actually `sect` not `section`.

@ramya-rao-a added a "whitelist" of sorts that inclued some commonly used tags to be expanded by emmet which can be found here. 

https://github.com/ramya-rao-a/vscode-emmet-helper/commit/772bca6f09126256d4b0494ab33ae2728150aad9

I think the new emmet is working far better than it used to an is less intrusive!

**Comment by ramya-rao-a** [comment]
Also, feel free to add to the whitelist here: https://github.com/ramya-rao-a/vscode-emmet-helper/commit/772bca6f09126256d4b0494ab33ae2728150aad9 and send a PR. I'll be happy to accept all the commonly used html tags

**Comment by ramya-rao-a** [comment]
@smlombardi @Niichie Can either of you repro this?

**Comment by Niichie** [comment]
I just did the same steps @smlombardi did in his gif and i'm getting correct insertion points.

![test](https://user-images.githubusercontent.com/16381287/28554182-162d2810-70c6-11e7-9914-8cf4509736fa.gif)

**Comment by smlombardi** [comment]
So far, this is working as expected now.

**Comment by ramya-rao-a** [comment]
Thanks, will close this for now then
