### ISSUE TITLE
Feature Request: File Preview on file mouseover

### ISSUE THREAD

**Issue by fivefishstudios** [Microsoft/vscode#30931]
Would be nice to have a file preview when mouseover the filename... like in Visual Studio

**Comment by mjbvz** [comment]
Can you please provide more information about what this feature would look like and how it would behave

**Comment by fivefishstudios** [comment]
Oops, my bad. VS Code already has this feature. I just had to click on the filename. (I thought I just had to hover over the filename in VStudio (Win), but no I also had to click on the filename.) Closing this.
