### ISSUE TITLE
 Cannot read property 'onDidChangeContent' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#30940]
Issue Id: <b>417afc5f-2549-60c9-ee3a-193e8d7adcc9</b><br /><br />*Versions* <br />- 1.14.1<br />*Stack* <br />TypeError: Cannot read property 'onDidChangeContent' of null<br />[/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L84:40 (onDidChangeContent)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L84:40 (onDidChangeContent))<br />[/vs/base/common/types.ts#L168:6 (apply)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/base/common/types.ts#L168:6 (apply))<br />[/vs/platform/instantiation/common/instantiationService.ts#L162:26 (apply)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/platform/instantiation/common/instantiationService.ts#L162:26 (apply))<br />[/vs/platform/instantiation/common/instantiationService.ts#L78:15 (_createInstance)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/platform/instantiation/common/instantiationService.ts#L78:15 (_createInstance))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L700:39 (createInstance)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L700:39 (createInstance))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1813:0 (complete)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1813:0 (complete))<br />

**Comment by sandy081** [comment]
Fixed by #32895
