### ISSUE TITLE
 Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#30947]
Issue Id: <b>99348f52-f7f8-598c-e45e-8e6cd5fc8a8b</b><br /><br />*Versions* <br />- 1.14.1<br />*Stack* <br />TypeError: Cannot read property 'properties' of undefined<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1149:31 (properties)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1149:31 (properties))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1384:41 (from)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1384:41 (from))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1733:23 (from)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1733:23 (from))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1692:29 (createTaskRunnerConfiguration)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1692:29 (createTaskRunnerConfiguration))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1780:52 (run)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1780:52 (run))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1366:33 (parse)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1366:33 (parse))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1361:43 (then)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1361:43 (then))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1360:23 (then)](https://github.com/microsoft/vscode/blob/2648980a697a4c8fb5777dcfb2ab110cec8a2f58/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1360:23 (then))<br />

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/30758
