### ISSUE TITLE
Terminal does not highlight text matching search in 'less'

### ISSUE THREAD

**Issue by haz-mat** [Microsoft/vscode#30956]
- VSCode Version: 1.14
- OS Version: OSX 10.12.5

Steps to Reproduce:

1. Open vscode terminal
2. run `less /etc/group`
3. do a search for root user by typing `/root`

Expected Result:

Terminal highlights the word "root"

Actual Result:

Terminal scrolls to the next occurrence of "root" without highlight.

Reproduces without extensions: Yes

**Comment by haz-mat** [comment]
Aha! That was the issue @Tyriar. I am using the included Solarized Light theme.

**Comment by Tyriar** [comment]
You can add this to your settings to fix it for the theme:

```js
  "workbench.colorCustomizations": {
    "terminal.ansiBrightWhite": "#eee8d5"
  }
```
