### ISSUE TITLE
CodeHelper.exe taking 30% cpu while idle

### ISSUE THREAD

**Issue by blargfoot** [Microsoft/vscode#30959]
- VSCode Version: 1.14.1
- OS Version: Microsoft Windows 10 Pro 10.0.15063 Build 15603

Steps to Reproduce:

1. Run 'code --disable-extensions' from an empty folder.
2. Open Task Manager and observe CodeHelper.exe consistently consuming cpu at 30%.

Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/1591860/28338888-4762fd44-6bd8-11e7-965f-8a79047611c6.png)

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by blargfoot** [comment]
Thank you for the quick response.

Here you go ...

![image](https://user-images.githubusercontent.com/1591860/28371055-e3ce0214-6c69-11e7-992c-f9ed8f9cd14f.png)

![image](https://user-images.githubusercontent.com/1591860/28371067-efbc553a-6c69-11e7-96f7-0907505628c3.png)

![image](https://user-images.githubusercontent.com/1591860/28371081-f5ae33e6-6c69-11e7-8008-420c0848727c.png)

![image](https://user-images.githubusercontent.com/1591860/28371110-06b20226-6c6a-11e7-8ecc-fbad54124826.png)

**Comment by blargfoot** [comment]
Btw, this is a brand new fresh install of VS Code 1.14.1.  No extensions installed and running on an empty folder.

**Comment by bpasero** [comment]
@blargfoot that is weird, it seems to be the file watcher (weird because the folder you open is empty?). Does it reproduce if you configure: `"files.useExperimentalFileWatcher": true` and restart?

**Comment by blargfoot** [comment]
That fixed it!  Thank you sir!
