### ISSUE TITLE
Messages like “Unable to activate XX analyzer”

### ISSUE THREAD

**Issue by AndersBillLinden** [Microsoft/vscode#30958]
When I with vscode 1.14.1 in Windows 10 pro add the following extensions:

* C/C++ 0.12.0
* C/C++ Advanced List 0.2.3
* C/C++ Clang Command Adapter 0.2.2
* C# 1.11.0
* C++ Intellisense 0.2.2
* Code Runner 0.6.26
* Debugger for Chrome 3.1.6
* Git History (git log) 0.2.1

opening a C file will result in a dropdown with the following messages:

* Unable to activate Flexelint analyzer.
* Unable to activate CppCheck analyzer.
* Unable to activate Clang analyzer.

The error messages will not go away and appears every time I switch to an editor with a file with that extension.

* There are no clues on why those "analysers" could not be "activated".
* The error message reappears every time a file with some extension instead of only informing the user once.
* The error messages are partly covering the editor.
* There is no way to close a single line, the close button on each line has to be clicked.

Screenshots on https://stackoverflow.com/questions/45160650/why-do-i-get-error-messages-like-unable-to-activate-xx-analyzer-in-vscode

**Comment by isidorn** [comment]
Please file this agains the c++ extension. Thanks

**Comment by AndersBillLinden** [comment]
Ok, wrong place, now I instead filed it in https://github.com/jbenden/vscode-c-cpp-flylint.
