### ISSUE TITLE
Editor loses focus when you click or drag the window title bar

### ISSUE THREAD

**Issue by arelenas** [Microsoft/vscode#30967]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 
jshint|dba|0.10.15
debugger-for-chrome|msj|3.1.6

When editing a file, if you click or drag the window title bar, editor loses focus. You need to click in the editor window again to set focus and cursor position before being able to type again.

---

Steps to Reproduce:

1. Click anywhere in the editor window of currently open tab
2. Click on the window title bar or drag it

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I am open to ideas how to solve this. I think this does not only apply to the title bar but also e.g. when you click into the status bar. Ideally we correctly restore the last focussed element (this can also be something else, not the editor, e.g. a search input box) whenever the body element gets focus (that is what seems to happen when you click the title). 

I could not find an elegant solution (e.g. CSS only) to solve this...

**Comment by brandonrninefive** [comment]
I am unable to reproduce this bug on VSCode 1.15.1 on Debian 64-bit with KDE Plasma 5. It appears that @bpasero's suggestion of restoring the last focused element is already taking place, both when clicking into the window title bar, as well as clicking into the status bar. Perhaps this bug is OS-dependent?

**Comment by bpasero** [comment]
Yeah I was testing on macOS.
