### ISSUE TITLE
A bug was introduced (latest update?)

### ISSUE THREAD

**Issue by contreras-jorgev** [Microsoft/vscode#3096]
While editing Javascript file in OS X:

Select block of code w/comments (not sure having comments is required) hit TAB:
    Expected: increase indent.
    Result: text is messed-up thru the end of file. Undo does not recover text.

**Comment by Beng89** [comment]
This also happens in typescript with shift+tab. 

Restarting code fixes the issue temporarily.

**Comment by alexandrudima** [comment]
Dup of #2829. We are preparing a recovery build.

**Comment by egamma** [comment]
Recovery build 0.10.9 is now available
