### ISSUE TITLE
staleSaveError is a bad experience

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#30966]
- VSCode Version: 1.14.1
- OS Version: Win10.

Steps to Reproduce:

1. Open an existing file and make some edits.
2. Modify the file with another editor or write it with another program.
3. VS Code quietly when an edited file be modified externally.
4. `staleSaveError` popup when save the edited file in VS Code.

Expected results:
1. VS Code should not be quiet when an edited file be modified externally, it should popup an tip earlier to indicate the file has been modified externally, for avoid a greater merge conflict.
2. If possible, it should to guide more effectively or auto merge the conflicts (diff).
3. If possible, it should displaye an message (box / tip) to ask actions, like take current, take external, resolve the conflict, cancel (back to editing).
4. Allow the user to reload the file without saving, #17643.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@yfdyh000 the error message is guiding you to a diff editor to compare your version with the version on disk and provides actions to resolve the save conflict (take version from disk / take version from VS Code). Are you not seeing that?

**Comment by yfdyh000** [comment]
I see it, but the message is too late and diff may be complicated, I might just want to give up the edited version (probably inadvertently), or get the conflict notification earlier.

**Comment by bpasero** [comment]
@yfdyh000 I do not understand what you are asking for. If you have a save conflict you get:
* a diff to see what is going on
* an action to "take the version on disk"
* an action to "overwrite the version on disk"

What is missing?

**Comment by yfdyh000** [comment]
1. An earlier notice to aware it will be conflict, avoid a wider range of conflicts.
2. Maybe I thought adds noticeable and quick buttons in the notification, not just start to compare. Or larger buttons in the comparison toolbar, I was ignores them because they are small so it looks difficult to use / advanced.
3. In addition, if both content is accidentally the same, it still tell me to compare.
4. "Discard local changes and revert to content on disk" is vague, "your version" or "editor content" should be used, like "Click on **Compare** to compare your version with the one on disk.".

**Comment by bpasero** [comment]
1. yeah there are other issues for this reported already
2. can you add this to https://github.com/Microsoft/vscode/issues/31063
3. can you add this to https://github.com/Microsoft/vscode/issues/31063
4. I can make that change to:

`Use your changes and overwrite disk contents`

and

`Discard your changes and revert to content on disk`

**Comment by bpasero** [comment]
I pushed the wording change. Closing this one in favour of the other issues that got reported on this topic already.
