### ISSUE TITLE
plz add Search for the Setting.Json !

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#30961]
ihi is possible to add search in the Setting.Json. CTRL+F
the search work in the para only !, but not in the custom para list !!.
I have a lot of para , i need searche in.
thank guy and girl
![aefaq34efa3g](https://user-images.githubusercontent.com/24865815/28339537-63388604-6bda-11e7-93ba-1e45d1968934.png)

**Comment by roblourens** [comment]
Yes, ctrl+f in the settings explorer searches the settings list but not the settings.json editor. Don't know if there's an issue for this experience, @sandy081? I have it disabled because I prefer to search the file :)

**Comment by djmisterjon** [comment]
is possible to make searche if open folder .vscode and file settings.json.
But I find this way not very operational, and is lost precious seconds for work.

**Comment by sandy081** [comment]
Please note that this is a Special Settings editor that will show Defaults, User, Workspace settings in Single editor with a consistent Search experience. Hence find is triggered to Search box. It will search in both Defaults and Settings.json. Agreed that it is not as powerful as Find widget, but it serves the basic purpose of finding settings which is the most you need here.

@djmisterjon Please let us know what is missing in current Search, it will be helpful to improve.

If you are an advanced user, here are some tips

- You can customise the Find behaviour to use Find widget as follows
```
{
    "key": "cmd+f",
    "command": "-settings.action.search",
    "when": "inSettingsEditor"
  },
  {
    "key": "alt+cmd+f",
    "command": "settings.action.search",
    "when": "inSettingsEditor"
  }
```

- You can always opt to just see the Settings file by using the setting `"workbench.settings.openDefaultSettings": false`
