### ISSUE TITLE
Screen Reader Detected when Remoting Into Machine

### ISSUE THREAD

**Issue by xplusplus** [Microsoft/vscode#30962]
I am seeing the Screen Reader Detected banner when remoting into a machine with VSCode on it.

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@xplusplus We are listening to an event our platform (Electron) exposes when it *thinks* a screen reader is attached. It *thinks* a screen reader is attached when it receives low-level OS events that typically are generated by Screen Reader software.

If this is a case of a false positive (which it appears to be) i.e. you are not using Screen Reader software, then please configure `"editor.accessibilitySupport"` from `"auto"` to `"off"`.
