### ISSUE TITLE
VSCode doesn't see files in OneDrive with Files On-Demand

### ISSUE THREAD

**Issue by vavane-ms** [Microsoft/vscode#30965]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
python|don|0.6.7
xml|Dot|1.9.2
nuget4code|ffo|0.0.2
Untabify|ili|0.0.2
Ionide-fsharp|Ion|2.27.14
vscode-omnisharp|jri|0.3.0
restructuredtext|lex|32.0.0
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6
PowerShell|ms-|1.4.1
sort-lines|Tyr|1.3.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Try to open a folder or a file in a OneDrive folder with Files On-Demand turned on.
2. Files/folders cannot be found even though they are in the locally available state (see https://support.office.com/en-us/article/Learn-about-OneDrive-Files-On-Demand-0e6860d3-d9f3-4971-b321-7092438fb38e?ui=en-US&rs=en-US&ad=US). Windows Explorer/Notepad have no issues with those folders and files.

I have OneDrive 2016 (Build 17.3.6955.0712).

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#27285
