### ISSUE TITLE
hi,my vscode this  setting "editor.renderWhitespace": "all",  it does not work, i donot know why ？

### ISSUE THREAD

**Issue by xilianxiaoli** [Microsoft/vscode#30975]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.7
jshint|dba|0.10.15
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
pug2html|gin|0.0.4
vue-snippets|hol|0.1.2
path-autocomplete|ion|1.5.1
weex|jay|0.4.0
intellij-idea-keybindings|k--|0.2.12
vue|liu|0.1.5
vscode-csscomb|mrm|4.0.1
jscs|ms-|0.1.9
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
node-modules-resolve|nau|1.0.2
vetur|oct|0.9.1
vscode-icons|rob|7.10.1
html2jade|wma|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@xilianxiaoli can you share more info with us, like your personal settings, workspace settings or other info that might help troubleshoot?

**Comment by xilianxiaoli** [comment]
sure, this my setting 
`
"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    // Defines space handling after a comma delimiter
    "javascript.format.insertSpaceAfterCommaDelimiter": true,
    //  Defines space handling after a semicolon in a for statement
    "javascript.format.insertSpaceAfterSemicolonInForStatements": true,
    // Defines space handling after a binary operator
    "javascript.format.insertSpaceBeforeAndAfterBinaryOperators": true,
    // Defines space handling after keywords in control flow statement
    "javascript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
    // Defines space handling after opening and before closing non empty parenthesis
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
    // Defines space handling after opening and before closing non empty brackets
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
    "window.zoomLevel": 0,
    "vsicons.projectDetection.autoReload": true,
    "workbench.iconTheme": "vscode-icons",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "editor.detectIndentation": true,
    "terminal.integrated.shell.windows": "D:\\Program Files (x86)\\Git\\bin\\bash.exe",
    "window.menuBarVisibility": "default",
    "[vue]": {
    },
    "files.associations": {
        "*.vue": "vue"
    },
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    },
    "editor.matchBrackets": true
`
Thank you for your help ~

**Comment by aaayushsingh** [comment]
i have the same problem too, it doesn't render whitespace, doesn't match parentheses, however the problem is only in current user account and everything works fine in another user account.

**Comment by AlekseiKudelia** [comment]
Same problem happened to me too. I does not work when I run vs code in my user account. I also noticed, that when I just open code, it renders bullets for spaces, but they disappear next moment. However, when I run vs code with admin privileges, it works fine.

Version 1.14.0
Commit b8cd5b9556d8b70ea560d35b903422363f6c5c40
Date 2017-07-10T18:36:31.751Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

settings.json:
```
{
    "editor.fontSize": 18,
    "editor.minimap.enabled": true,
    "editor.renderWhitespace": "all",
    "http.proxyStrictSSL": false,
    "eslint.validate": [ "javascript", "javascriptreact", "html" ],
    "prettier.printWidth": 100,
    "prettier.tabWidth": 4,
    "prettier.singleQuote": true
}
```

**Comment by aaayushsingh** [comment]
@AlekseiKudelia I installed the new 64-bit version and everything started working fine. Give it a try.

**Comment by xilianxiaoli** [comment]
@aaayushsingh  hi , you update or reInstall ? i had try update  , but it still not work

**Comment by rebornix** [comment]
@xilianxiaoli did you try `code --disable-extensions` ?

**Comment by aaayushsingh** [comment]
@xilianxiaoli You are on windows, try this. Right click code, and select run as administrator. If it works, the in the compatibility options, select run as admin as default.

**Comment by kimsk** [comment]
I also start having the same issue (not seeing whitespace dots) lately on windows. I tried 64-bit version, extensions disabled, running as admin, and nothing seems to help. I also tried with minimal settings like this:

```
{
   "editor.renderWhitespace": "all"
}
```

**Comment by alexandrudima** [comment]
This might be caused by our detection of a Screen Reader attached.

Have any of you experienced this recently ?

Could you please try using `"editor.accessibilitySupport": "off"`
