### ISSUE TITLE
⌥F12 is broken in 1.14.1

### ISSUE THREAD

**Issue by huangxubo23** [Microsoft/vscode#30976]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
jsx|Twe|0.0.1
githistory|don|0.2.1
jsx-beautify|gog|0.0.5
vue-snippets|hol|0.1.2
vetur|oct|0.9.1
vscode-wechat|qin|0.0.6
java|red|0.7.0
vscode-icons|rob|7.10.1
react-beautify|tai|0.3.0
vscode-react-native|vsm|0.3.2
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Press ⌥ + F12
2. Can not redirect

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Please provide a small example project and some steps to reproduce the issue so that we can investigate

**Comment by mjbvz** [comment]
Also, please try out VSCode 1.14.2 which was just released. The update includes typescript 2.4.2 which fixes a number of bugs that could cause this behavior

Let me know if you still see this behavior after updating

**Comment by mjbvz** [comment]
Closing as we need more info to investigate. Please try VSCode 1.14.2 which may have fixed this issue
