### ISSUE TITLE
[json] Incorrect version string when adding dependency to package.json

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#30977]
- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:15:46.760Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open up a package.json file.
2. Type in a new dependency name, then press tab to insert the version.

Expected result:
A version string.

Actual result:
`${1:}`

**Comment by aeschli** [comment]
@jrieken See 159fa62. Not sure if this was a change in the API and if empty placeholders are supposed to still work.

**Comment by jrieken** [comment]
grey-zone, I can check
