### ISSUE TITLE
Do not force to create a Workspace to use multiple folders

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#30972]
- VSCode Version: 1.15.0 Insiders ( 3cfa565 , Date 2017-07-17T05:15:33.728Z)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

From [#30608](https://github.com/Microsoft/vscode/issues/30608#issue-242682053)

But why am I forced to create a work area?

I simply want to add a second folder, without having to create a specific workspace

This window should have a third option, "Add only the folder".

![menu2](https://user-images.githubusercontent.com/19866231/28346243-13534df0-6c06-11e7-9e11-955c6cc84e5d.png)

That is, the options would be: "New Workspace", "Add only the folder", "Cancel".

Something very similar, seen in @alefragnani [commentary](https://github.com/Microsoft/vscode/issues/396#issuecomment-315627805)

> It shouldn't force to create a workspace just to add another folder to the current window. It should just add the new folder in the tree, and leave the newly created workspace as an internal info. If the user decides to save the workspace, then the workspace is really created. And even if I don't save the workspace, while reopening the top-folder, it would remember my temporary workspace_ and open the other folders as well, just like it remembers the opened files when you open a folder today.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
The explanation why we do this currently is here: https://github.com/Microsoft/vscode/issues/396#issuecomment-315402932

**Comment by vadimcn** [comment]
I concur with @Tekbr: In my workflow, I typically have a "main" folder where most of my work happens, to which I then add miscellaneous folders from elsewhere on my hard drive.
As such, I would prefer to have the option to keep using `settings.json` of my "main" folder as the workspace file. 
Of course, I could just save workspace into `project/.vscode/project.code-workspace.`, but then VSCode won't automatically load it when I open the `project` folder.

**Comment by bpasero** [comment]
I am closing this "as designed", there are no plans to change this for now.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero  Sad about it 😢  . Even though it's not in the plan, but it was something that works well even on the insiders and once it was withdrawn it was reported.

Something that there are in other editors in which we are not forced to save. This should still be kept open, even if not for now, but it is essential.

Something that was even asked in the related case by a development partner of you.

**Comment by bpasero** [comment]
@Tekbr I am sorry to close this but how useful is an open issue that we will not address in the next 6-12 months? We want to keep issues open that are actionable, and this one would only be actionable if we had an agreement about what to do, no?

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero How do I do not know, but as I said it was something that works. And other editors do not require me to create a Worksapce. Very sad for this. 😢 

Even if they do not approach us in the coming months, it does not lead to the fact of closing the issue / request for appeal.

Instead of simply closing out the questions they should try to check with the creator of the question whether the problem still exists or whether it has been circumvented. If it did not return to a closed case list, but would probably return if it was reopened (or even without the need to respond).

**Comment by bpasero** [comment]
@Tekbr but other editors also did not decide to store workspace settings for a multi root workspace. How do you suggest to solve the problem of storing workspace settings when there is no workspace file for multi root?

**Comment by bpasero** [comment]
Given multi-root is a relatively new feature, I am willing to be less strict and wait for more user feedback. But please understand that this issue will not get much attention from me unless it ends up highly requested also from others.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero I really use the simple at the moment. I consult other projects that have no direct link. But then I remove. And being forced to save the Workspace is bad.

You did it and then you took it. How to solve it I do not know. I would really like to be able to help, but I still do not have the knowledge for this .. But it bothers me to be forced to save the Workspace.

Anyway thank you. I still ask you to watch this case with care.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero , in case #42657 it looks like @DavidLudwig was wanting to send a PR, I do not know if he came to see .. or could that question only be resolved by the members?
