### ISSUE TITLE
Closing developer tools multiple times causes VSCode to crash

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#30978]
- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:15:46.760Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:
1. Help > Toggle Developer Tools
2. Click the 'X' on the panel.
3. Help > Toggle Developer Tools
4. Click the 'X' on the panel.

Looks like this is an actual crash and not an unexpected close. The only files in `VSCode Crashes` are from just now when I was reproducing this...

**Comment by NoxWings** [comment]
It is happening on Linux too 
OS Version: Debian 9.1

About atom:
----
Version 1.17.0
Commit be377c0faf7574a59f84940f593a6849f12e4de7
Date 2017-10-04T23:33:45.303Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
----

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by mattacosta** [comment]
That is always easier said than done.

"[developer tools](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20developer%20tools)" = nothing
"[devtools](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20devtools%20)" = nothing
"[label:freeze-slow-crash](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Afreeze-slow-crash%20)" = nothing

Since you said that it exists, I poked around and finally went through the comment in #35203 to get to #29063... so yea, just link it (if possible) for me next time will ya. 😄
