### ISSUE TITLE
Git ignoring Proxy settings

### ISSUE THREAD

**Issue by alexshak** [Microsoft/vscode#30973]
**- VSCode Version:** 1.14.1
**- OS Version:** Windows 10 Pro 1703

I work both on site and externally for a project and when on site I configure my system to run through the company proxy. This works fine for VS Code generally, I can access and use extensions, receive updates etc. But when I go to sync my work to the existing Git repository the connection times out and gives a: 

> git fetch
> fatal: unable to access 'https://our.git.repo': Failed to connect to our.git.repo port 443: Timed out

Some investigation with our network specialist reveals that the request being made when I sync is ignoring the proxy settings. I can access the repo directly through the browser just not in VS Code. 

My settings.json is currently set to: 

> "http.proxy": "http://our.proxy:port/",

have tried adding as well: 

> "https.proxy": "https://our.proxy:port/",

**Steps to Reproduce:**

1. Set some functional proxy settings in User/Workspace settings.
2. Sync existing git repository. 

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
You'll want to [configure git](https://stackoverflow.com/a/3406766) for this, not vs code.
