### ISSUE TITLE
Show untitled workspaces in recently opened list with their creation date

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#30971]
- VSCode Version: 1.15.0 Insiders ( 3cfa565 , Date 2017-07-17T05:15:33.728Z)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Workspace Untitled could have creation date and time in File> Open Recent

From [#30608](https://github.com/Microsoft/vscode/issues/30608#issuecomment-315416709)

> Showing next to the name untitled the date / time it was created (DD / MM / YYYY - HH: MM: SS) in File recent

From [comment](https://github.com/Microsoft/vscode/issues/30608#issuecomment-315509349) by @bpasero 

> Good idea about showing the date for untitled workspaces.

As for the date / time do not forget to use the format according to OS settings.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
We are no longer showing "Untitled Workspaces" in the recent history. Untitled workspaces are removed when you close the window and do not save.

**Comment by bpasero** [comment]
Reopening, and treating as feature request.

**Comment by bpasero** [comment]
Not planning to change this for now, closing.
