### ISSUE TITLE
Relative Include Paths On Dependencies Not Being Detected With Intellisense

### ISSUE THREAD

**Issue by weshoke** [Microsoft/vscode#30979]
- VSCode Version: Version 1.14.1 (1.14.1)
- OS Version: 10.12.4 (16E195)

Steps to Reproduce:

1.  Open a C++ project and set strict semantic checking for IntelliSense
2. Observer that include dependencies in other directories are unresolved due to the folder not being included explicitly.  However, from the perspective of the C++ compiler when it's processing the dependency, the include path of the file itself is available and thus the second order dependency is valid

For example for folder structure
```
/path
        inc_p.h
        /subpath
                        /inc1.h
                        /subsubpath/inc2.h
```

If inc_p.h includes "subpath/inc1.h" and inc1.h includes "subsubpath/inc2.h", inc_p.h will have a red squiggly error since inc2.h is not detected by IntelliSense despite the code compiling just fine.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-cpptools#901
