### ISSUE TITLE
in Win10 half screen mode, cannot take full size of half screen

### ISSUE THREAD

**Issue by frozenluo** [Microsoft/vscode#30984]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
jshint|dba|0.10.15

vscode-eslint|dba|1.2.11
githistory|don|0.2.1
xml|Dot|1.9.2
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
beautify|Hoo|1.1.1
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
sass-indented|rob|1.4.1
gitblame|wad|1.11.3

---

Steps to Reproduce:

1.  drag window to the right/left side of screen
2. make it half screen
![popo 2017719143724](https://user-images.githubusercontent.com/1532735/28353786-d389bb02-6c8f-11e7-9860-2005d5b25904.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/22010
