### ISSUE TITLE
File explorer that can be open in any window

### ISSUE THREAD

**Issue by medikoo** [Microsoft/vscode#30987]
I was searching the issues and extensions and didn't succeed in finding something close.

Emacs has neat functionality that in normal window we can open a files explorer ([Dired](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html)) I find it very handy and more practical than explorer tree which can only be shown aside, which in turn takes valuable part of a screen most of the time

Short film showcasing how toggling between file explorer and typical file content view works in Emacs:

![2017-07-19 09 39 41](https://user-images.githubusercontent.com/122434/28356091-06f20162-6c67-11e7-9bc6-6b716254cf98.gif)

In VSCode it could just open typical file explorer with focus on file that were open in given window, then traversing the file explorer with keyboard and specified shortcuts should work, pressing enter on file should just open the file in same window.

**Comment by bpasero** [comment]
If you do not want to use the file explorer, there is quick open to search for files.

**Comment by medikoo** [comment]
> If you do not want to use the file explorer, there is quick open to search for files.

@bpasero I don't see how it gives this functionality. If you mean "Quick open view" it just opens explorer bar in sidebar and moves my focus there. it's not about that. It's about **reusing existing window** so windows layout remains not changed

Can you please reopen the request?

**Comment by bpasero** [comment]
@medikoo I am talking about Cmd+P:

![image](https://user-images.githubusercontent.com/900690/32931658-a4ebc1f2-cb65-11e7-80fa-71b1207e7a80.png)

**Comment by medikoo** [comment]
> @medikoo I am talking about Cmd+P:

Again this is very different functionality. It shows just previously opened files in LRU order.

Here it's about directory overview, so I can easily traverse system and be able to easily access files of which names I'm not sure and which were not necessarily visited before.

e.g. I need to modify each file in given directory. inspect the project file by file as a whole. Go to file, which I know where is located but I'm uncertain of it's exact name (or I know the name but it's accessible, or easily accessible in Quick view)

It should reflect the list exactly as it's in explorer, but it doesn't have to expand tree nodes (it's fine that to see folder contents I need to enter it).

Currently addressing those use cases in VS code is not possible without taking 20-30% of workspace area by Sidebar. Not to mention that I need to jump between sidebar and editor group which additionally reduces productivity.

Extension that's closest to this functionality is [File Navigator](https://marketplace.visualstudio.com/items?itemName=jakelucas.code-file-nav) by @jakelucas but it looks as not maintaned anymore, and it's still not good enough to be valid counterpart.
