### ISSUE TITLE
editor not matching brackets, even when "editor.matchBrackets": true is set, "editor.renderWhitespace": "all" doesnt work either.

### ISSUE THREAD

**Issue by aaayushsingh** [Microsoft/vscode#30985]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.7
tslint|eg2|0.16.0
beautify|Hoo|1.1.1
cpptools|ms-|0.12.1
Ruby|reb|0.12.1
nativescript|Tel|0.7.2
html-preview-vscode|tht|0.1.1

---

Steps to Reproduce:

1. Launch VS code
2. Open any file.

Also, the navigation pane on the right is not visible.(the one that allows easier navigation, scroll), whitespaces aren't rendered.

![image](https://user-images.githubusercontent.com/19550852/28355113-462661b6-6c80-11e7-943e-8898b911b7a4.png)

 Works fine on my Linux.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
@aaayushsingh is there any chance that the project you are working on has workspace settings that override your user setting? Besides,

**Comment by aaayushsingh** [comment]
@rebornix I've tried opening single python files as well, doesn't work. Also I've added `" editor.matchBrackets": true` in the user settings as well. 

Is there a way to get logs from vscode that I can put here?

**Comment by aaayushsingh** [comment]
Update: I downloaded vs code insider, launched the application, created a new js file, wrote some code and the same problem persists. 

OS: Windows 10 home single language edition.

**Comment by aaayushsingh** [comment]
@chrmarti you removed the label, any updates on the issue?

**Comment by chrmarti** [comment]
@aaayushsingh I have removed it from all issues because we are preparing the next release and will want only that to be labeled as 'new release'. We mainly use that label for a few days after a new release to quickly spot issues that could indicate regressions.

**Comment by aaayushsingh** [comment]
@chrmarti so is this getting fixed? Did anyone even look at this?

**Comment by chrmarti** [comment]
@aaayushsingh Yes, it is assigned and you have been asked for your workspace settings. No ETA on the resolution though.

**Comment by aaayushsingh** [comment]
Installed the new 64-bit version, everything is working fine now with the same settings.
looks like `new-release` fixed my issue.
