### ISSUE TITLE
Show corresponding commands when hovering over Git menu items

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#3098]
The Git menu has a couple items that use terminology that doesn't originate from within Git. ("Sync", "Clean All", "Publish"?  What are these going to do?)  Even when they do, it's still not always clear what exactly will happen when you click them.  ("Pull" pulls from where?  Origin?  Using its branch of of the same name as the one that's checked out on your repo?)

Hovering over any of these items should show the commands that these items correspond with, so you know exactly what they're going to do.

**Comment by felixfbecker** [comment]
Pull does the same as executing `git pull` without any special arguments.
