### ISSUE TITLE
Bottom panel height is maximized after resizing VSCode window

### ISSUE THREAD

**Issue by Danthar** [Microsoft/vscode#30988]
- VSCode Version: 1.14
- OS Version: Windows 10

Steps to Reproduce:

1. Have the bottom panel open at its default height
2. Resize the VSCode window, keep an eye on the "Maximise panel size" button for the bottom panel. Once you make the window small enough, it automatically switches to the "maximised" state.
3. Press the maximise button of the VSCode window.

The panel now stays at the maximised setting covering most of the code view. Where imo it should have never switched to the maximised setting in the first place.

It affects me because when my computer goes into standby it decides to resize VSCode to a size where the above described behavior is triggered (irregardless of window state). Im running at a resolution of 3840x2160. So that might have something to do with it.

**Comment by isidorn** [comment]
Currently panel computes the sizes and figures out it is in a maximized state.
Due to that you get into this strange situtation.

Not sure how to best tackle it though.
Here's a [code pointer](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/workbench/browser/layout.ts#L335), if somebody has a good idea we are accepting PRs

**Comment by Danthar** [comment]
Fix seems exceedingly simple. Remove this line of code: 
https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/workbench/browser/layout.ts#L350

Don't set the panel toggled state, based on its height. Only change it upon user interaction (clicking on the toggle button), and initialize it on client startup. 
For the rest, keep the behavior as is.

**Comment by isidorn** [comment]
Thanks for the idea, PRs are very welcome

**Comment by isidorn** [comment]
This is fixed now
