### ISSUE TITLE
Toggle block comment add extra single space 

### ISSUE THREAD

**Issue by gyansoft786** [Microsoft/vscode#30980]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-simpler-icons|dav|1.3.0
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
vscode-icons|rob|7.10.1
html-css-class-completion|Zig|1.7.0

(3 theme extensions excluded)

---

Steps to Reproduce:

Toggle block comment **(shift + alt + a)** add extra single space at the start and end of the block.  
If remove comment again by pressing shift + alt + a , the white space added previously should remove. 

Please do the needful. 

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
It's already fixed and you can see that in Insider or next Stable release. Thanks!
