### ISSUE TITLE
View/Toogle Word Wrap not working in lasted version 1.14.1

### ISSUE THREAD

**Issue by phangia2712** [Microsoft/vscode#30986]
Please check this issue, I'm using win 10 Pro. Tks

**Comment by phr3nzii** [comment]
I have the same issue on 1.14.1. I'm running Windows 10 Enterprise (build 15063.483). I think I also had this issue in the previous version too.

**Comment by rebornix** [comment]
Already fixed and will ship with next recovery build.

**Comment by codemcu** [comment]
Hi, 

file > preferences > settings
**"editor.wordWrap": "on",**
and smile ;-)
