### ISSUE TITLE
Explorer keeps saying Untitled Workspace

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#30991]
See screen shot. I have two folders in my workspace and saved in a file `Work.code-workspace`. The title is correct, the explorer isn't. 

<img width="1198" alt="screen shot 2017-07-19 at 10 00 10" src="https://user-images.githubusercontent.com/1794099/28356660-2e13b5b8-6c69-11e7-8193-9b5cfb7f728b.png">

**Comment by isidorn** [comment]
Seems to be working fine with latest out of source. I could repro it with insiders so I build vscode with latest from source and also could not repro.
My specualtion is that @sandy081 fixed this in the last 24hrs

@jrieken can you please retry in tomorrow's insiders - thanks

**Comment by isidorn** [comment]
The issue is only being surfaced when openEditors is not visible. That's why I could only repro in insiders.
