### ISSUE TITLE
Root folders need a different icon as regular folders 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#30998]
testing #30722:

Multi root:
![2017-07-19_11-19-47](https://user-images.githubusercontent.com/1898161/28359997-615413a4-6c74-11e7-825c-cdd09bedfe6b.png)

Single root:
![2017-07-19_11-22-37](https://user-images.githubusercontent.com/1898161/28360067-abc9354a-6c74-11e7-935d-813b6e641dfe.png)

**Comment by bpasero** [comment]
Yeah I would also like to distinguish workspaces in the recently opened list better:

![image](https://user-images.githubusercontent.com/900690/28361522-5560a9e0-6c79-11e7-9806-94ab5bf6ab3e.png)

@aeschli I guess we would need to introduce a new icon category (file vs folder vs root folder) or could an extension author actually contribute icons for root folders in some way?

**Comment by aeschli** [comment]
I added a new 'rootFolder' and 'rootFolderExpanded' entry to the icons theme.
If not set, the icon set as 'folder' and 'folderExpanded' is used instead.

@bpasero Can you add the css rule 'rootfolder-icon' to the explorer for root folders?

**Comment by bpasero** [comment]
@aeschli thanks for picking this up so quickly, I made the relevant changes.

@isidorn I leave the icon in your capable hands, the minimal icon theme that we ship should get a new icon for the root category. It needs to be added here: https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/fileicons/vs_minimal_icons.json#L25

E.g.:

```
"rootFolderExpanded": "_root_folder_open_dark",
"rootFolder": "_root_folder_dark"
```

**Comment by isidorn** [comment]
I have looked into the available Visual Studio icons and the following are potential canddiates
![screen shot 2017-07-20 at 11 15 51](https://user-images.githubusercontent.com/1926584/28410090-dd9e15ae-6d3c-11e7-9914-fd83f83783d9.png)
![screen shot 2017-07-20 at 11 16 28](https://user-images.githubusercontent.com/1926584/28410095-e557acd8-6d3c-11e7-8ac3-2e7b3fd2c81f.png)

Note that we would need to strip the color from these and that the second option does not have the expanded icon. 
The issue with these icons is that they do not go perfectly with the original minimal icons. Idealy the root icon would have the same geometric shape as the minimal folder icon but with some special deocration on top.

@aeschli where did you get the original minimal theme icons?

If none of these works then we would need to ask for a design from @chryw - not sure if you have time atm

**Comment by chryw** [comment]
@isidorn I think the folder with dot may work. I'll make a VS Code version. I'm on vacation and will return next Monday. ETA next Friday the latest.

**Comment by isidorn** [comment]
@chryw that would be great
Here are the links for the current folder icons for the minimal theme
https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/fileicons/images/Folder_16x.svg#L1

Next to that file you can find both the light / dark / expanded / colapsed version.

**Comment by chryw** [comment]
[GHVSCode30998_RootFolderIcon.zip](https://github.com/Microsoft/vscode/files/1174442/GHVSCode30998_RootFolderIcon.zip)
@isidorn Please try the attached icons and let me know if there is any issue. :-)

**Comment by isidorn** [comment]
@chryw great work, I really like it

![screen shot 2017-07-26 at 09 30 08](https://user-images.githubusercontent.com/1926584/28609464-0da25a10-71e5-11e7-8df3-2d807f14b458.png)

![screen shot 2017-07-26 at 09 31 07](https://user-images.githubusercontent.com/1926584/28609488-2cc65482-71e5-11e7-9376-710f9a446290.png)
