### ISSUE TITLE
As of 1.14 update, Peek & Go To definition report "No Definition Found" (Plain JS)

### ISSUE THREAD

**Issue by Sacrekin** [Microsoft/vscode#30990]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by jmaleonard** [comment]
The same on MacOS 10.12.5

**Comment by mjbvz** [comment]
Please provide a small example project or some example code that shows this issue

**Comment by Sacrekin** [comment]
As requested. Kind regards.



Jean-Marie Sacré
jm@sacre.us
GSM: +33.68281.3011
Skype: sacrekin

**Comment by jmaleonard** [comment]
I downgraded my typescript version to 2.3.4 to resolve the issue. Seems the issue is Typescript 2.4.1

**Comment by NickHeiner** [comment]
I may be seeing the same issue.

![image](https://user-images.githubusercontent.com/829827/28424849-ae90a45c-6d3c-11e7-9c54-74ffe72878cf.png)

Here is the entirety of the file, named **Accordion.jsx**: 

```js
const CLASS_NAME_MAPPING = {
  bordered: 'usa-accordion-bordered',
  borderless: 'usa-accordion',
  outline: 'usa-accordion-bordered-outline'
};

console.log(CLASS_NAME_MAPPING);
```

The file comes from https://github.com/department-of-veterans-affairs/caseflow.

My JSConfig:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "client/node_modules",
        "tmp"
    ]
}

```

VSCode version: 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
MacOS version: 10.12.5

**Comment by mjbvz** [comment]
Please try out VSCode 1.14.2 which was just released. The update includes typescript 2.4.2 which fixes a number of bugs that could cause this behavior

Let me know if you still see this behavior after updating

**Comment by NickHeiner** [comment]
Yep, confirmed that it's fixed for me.
