### ISSUE TITLE
Ctrl+F on selection does rarely use selection as search term

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3099]
Since january update, when I select some text and hit Ctrl+F, only very rarely does this selection get used as the search term. Instead, most of the time, the old value is still there and the "replace" input gets focused.

**Comment by alexandrudima** [comment]
In the January release, `Ctrl+F` always seeds the search string from the selection, while `Ctrl+H` only seeds it if there was no search string.

We have fixed this in #2953
