### ISSUE TITLE
安卓build release包，需要重写关闭打开才会出现

### ISSUE THREAD

**Issue by angularbaby** [Microsoft/vscode#30992]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|prettier-vscode|esbenp|0.21.0|
|cpptools|ms-vscode|0.12.1|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please file this issue with reproducable steps in english. Thank you
