### ISSUE TITLE
Allow to create multiple files at once from the command line with glob patterns

### ISSUE THREAD

**Issue by gkTim** [Microsoft/vscode#310]
I would like to have a feature to create multiple file at once.

For example if you type the following pattern as a filename for a new file:

```
test.{css,ts,html}, test2.{css,ts,html}
```

It should create the following files:
- test.css
- test.ts
- test.html
- test2.css
- test2.ts
- test2.html

This would save a lot time.

Is this something I can do with an extension or must I edit the electron-browser to get it running?

I think an extension would be the better way because it is something special and not directly obvious to the user. What do you think? Of cause we can discuss the format for this operation. The example above is just a first try.

I would implement it and do a pull request (if I must change vscode directly).

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
