### ISSUE TITLE
Allow to open *.code-workspace file as text file

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31008]
Testing #30722:

just a nit...

Since I was curious how my test.code-workspace file looks like, I tried to open it in VS Code. But this had no effect because VS Code tries to open it as a workspace and that workspace was already open.

**Comment by sandy081** [comment]
I think we should provide an action / command to open the current workspace file. 

Do we also need a way to open any workspace file as is from outside?

**Comment by bpasero** [comment]
Yeah maybe a global "Edit Workspace" action that simply opens that file? I do not think there is a use case to edit another workspace outside the current scope.

One risk is that the user can tamper with the workspace ID and folders array (e.g. even empty it) which is something we are not fit for yet so I am not sure we should expose it so prominently.

**Comment by sandy081** [comment]
Added Edit Workspace Action

![image](https://user-images.githubusercontent.com/10746682/28370244-6604db34-6cb7-11e7-9f2d-7c60fe479363.png)

**Comment by bpasero** [comment]
@sandy081 I wonder if this is a bit too prominent. an alternative would be to just allow to open the workspace file via "File > Open" (Windows/Linux: "File > Open File"). If we decide to keep "Open Workspace" as separate entry then it would even make sense that the other action allows to open the file and not the workspace itself.

**Comment by weinand** [comment]
IMO, users do not expect that "Open File" of a *.code-workspace file opens the workspace, and not the file as text. As a user I would use the "Open Workspace" action for opening a workspace.

But: double-clicking a *.code-workspace file should open the workspace and not the file as text (if VS Code is registered for that file extension).

**Comment by sandy081** [comment]
How about changing the above action to `Workspaces: Open Workspace Configuration File` in addition to supporting `File > Open` ?

**Comment by bpasero** [comment]
@sandy081 yeah I think it is OK to leave that global action in, but then in the menu I can look into supporting to open it just via the File > Open gesture.

**Comment by sandy081** [comment]
@bpasero Do you mean to have global action `Edit Workspace` or `Open Workspace Configuration File`?

**Comment by bpasero** [comment]
@sandy081 both work for me, but maybe `Open Workspace Configuration File` is less likely to be used accidentally :)

**Comment by bpasero** [comment]
I added support to open a workspace file via File > Open. Also, the workspace file will show up as normal file in the recently opened section (File > Open Recent, and picker) and can be opened from there too.
