### ISSUE TITLE
Multiple selection editing does not always work

### ISSUE THREAD

**Issue by Pszek** [Microsoft/vscode#31000]
In some cases, it seems that I cannot edit multiple selected items (only the first one is edited). 

- VSCode Version: 1.14.1
- OS Version: 10.12.5

Reproduces without extensions: Yes

Below there is a GIF with that behaviour:
(as you can see, both selection and info in the status bar, there are two items multiple selected - `currentType` and `places`,  yet edited is the only first instance of it. `currentItem` on the other hand is properly edited in two places.

![aaa](https://user-images.githubusercontent.com/10253750/28360104-c230f67e-6c74-11e7-86cd-3262ad4b786c.gif)

I didn't stumble upon this behaviour in other than `javascript` type of files (probably, because I rarely use them).

Please tell me how can I help you further with that issue (some debugging in the console, etc. ?)
(opinion about visible code quality always welcome :wink: )

**Comment by rebornix** [comment]
@Pszek can you help check

* Run `code --disable-extensions` and see if you can still reproduce? I can't reproduce it with vanilla VSCode so hope you can help verify
* If it still happens, can you check Help -> Toggle Developer Tools and see if there is any error log there?

Thanks for your help in advance.
