### ISSUE TITLE
Opening *.code-workspace file with non-existing paths leaves workspace in bad state

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31001]
testing #30722:

I tried to use a *.code-workspace file from macOS on linux. Since the paths are invalid, I got this error:
![2017-07-19_11-27-19](https://user-images.githubusercontent.com/1898161/28360595-3b7fb9e2-6c76-11e7-8ab0-caa734729935.png)

After dismissing the error the workspace showed up like this: 
![2017-07-19_11-35-40](https://user-images.githubusercontent.com/1898161/28360656-6786a7b2-6c76-11e7-97d1-b78e5750cf3b.png)

But no files showed up in the two folders and trying to create a new file resulted in this error:
![2017-07-19_11-37-32](https://user-images.githubusercontent.com/1898161/28360733-a9969efa-6c76-11e7-9765-a7d38835a50b.png)

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/29738

**Comment by isidorn** [comment]
Fixed via fixes for #29738
