### ISSUE TITLE
Do not use special color for multi root workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31007]
Refs: #30722

I understand you added a new color to the status bar to make it more distinugshable than the usual experience. Here are my arguments why it should not have a special color:

* We already have indication in the explorer that there are mutliple roots and that the title is different
* The new color is brand new and we do not use it anywhere else, unlike the light blue which goes nicely with the tree selection, some buttons and so on...
* The new color will break exisiting themes and will force them to adpot, in the meantime it will look ugly
* The regular user does not care if he is in a mutli root vs single root. The color difference in no root vs multi root is needed since in no-root we are lacking functionality. While in this situation that is not the case

**Comment by bpasero** [comment]
@isidorn yeah I wanted to bring this up during UX meeting if we should have it. Fyi even though I introduced a new color, it is currently only being used in our default dark and light theme. For all other themes I am not overriding it. Theme authors are free to implement it (there are new color keys for it).

@Microsoft/vscode happy for suggestions what you would expect if you are in workspace mode (e.g. do we need other indicators compared to what we have today).

**Comment by bpasero** [comment]
Outcome of todays UX meeting was that we do not want to introduce a new color.
