### ISSUE TITLE
Why use brackets in workspace title

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31009]
Refs: #30722

Imho brackets look ugly (especially after 1 or 2 words) and this should just be TEST WORKSPACE. Or an alternative WORKSPACE: TEST

![screen shot 2017-07-19 at 12 14 35](https://user-images.githubusercontent.com/1926584/28362222-e7e6cd6a-6c7b-11e7-891c-518f8531e7e3.png)

**Comment by bpasero** [comment]
Just to keep in mind, we show this in more places throughout the UI:

![image](https://user-images.githubusercontent.com/900690/28362515-f4520ff0-6c7c-11e7-8513-e56b5f685b3d.png)

![image](https://user-images.githubusercontent.com/900690/28362525-f9619416-6c7c-11e7-8663-744db8100fc8.png)

![image](https://user-images.githubusercontent.com/900690/28362530-fee2506a-6c7c-11e7-8ddf-0b3f598e15d6.png)

**Comment by bpasero** [comment]
Also not to forget, space is limited and showing "Workspace" first might not be a good idea:

![image](https://user-images.githubusercontent.com/900690/28362723-ca57216c-6c7d-11e7-8f3e-a6e43c327288.png)

**Comment by isidorn** [comment]
@bpasero ok in those places I think the brackets are better suited. So I might be fine with going with the brackets everywhere

**Comment by isidorn** [comment]
Also +1 for your limited space comment. Closing as designed
