### ISSUE TITLE
loaded scripts explorer: show '~' for paths outside of workspace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31002]
show '~' for paths outside of workspace (identical to workbench behavior)

**Comment by bpasero** [comment]
@weinand here is the code we use for that: https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L74

**Comment by weinand** [comment]
@bpasero great, thx!

**Comment by weinand** [comment]
@bpasero it would make sense to offer getPathLabel() from https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L31 in vscode.d.ts
This could ensure that paths in the UI are rendered in a consistent way.

**Comment by bpasero** [comment]
@weinand I would actually argue that we should use `getPathLabel()` by default when you show an item in the custom views and give it a resource but no label. Maybe only if that resource uses the file:// scheme.

/cc @sandy081

**Comment by sandy081** [comment]
This would need to expose a resource property in TreeItem object. This will also helps in resolving the icon.

**Comment by bpasero** [comment]
Yeah that's what I thought 👍

**Comment by weinand** [comment]
In my case I would use "getPathLabel()" to convert a debug resource into a "standard" path, but I need my own extension code to break that path into a hierarchy for the TreeDataProvider. I'm not sure that this could be done in a generic way.

**Comment by bpasero** [comment]
@jrieken @egamma (since you did something similar via https://github.com/Microsoft/vscode/commit/f911acfa493cab2ff54370903207fecf5f8ed0c8) after talking to @weinand we wonder if we should not have a API method similar to `asRelativePath` that allows to put in a resource URI with a path (not necessarily a file URI) and that returns:
* the value of `asRelativePath` if the resource is inside the workspace
* the result of todays `getPathLabel()` otherwise

**Comment by jrieken** [comment]
> the result of todays getPathLabel() otherwise

That is just a *nix-special-case to replace my home-directory with `~`, right?

**Comment by bpasero** [comment]
@jrieken yeah this method actually already does what `asRelativePath` does but on top of that will shorten long paths by adding a "~" prefix on macOS and Linux in case the path is within `user.home` and removing the `user.home` portion.

That said I wonder if we need to be careful about changing `asRelativePath` when you are in multi-root (by adding the root folder as prefix). That seems like a somewhat breaking change for extensions that expect a certain format here. We could leave `asRelativePath` as is and only support the first folder when converting to a relative path.

I would deprecate `asRelativePath` in favour of a new method `getPathLabel` that supports multi root and leave `asRelativePath` for using the single `rootPath` even in multi root environment.

It is easy to find out how extensions use `asRelativePath`: https://github.com/search?l=TypeScript&q=asRelativePath&type=Code&utf8=%E2%9C%93

I think as long as an extension is using this method purely as a way to get a label, it is fine. But having this method be more explicit that the use case is for labels only makes sense to  me.
