### ISSUE TITLE
Git: "Discard Changes" dialog button defaults are flipped

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#31006]
* do some changes
* undo from the git viewlet

macOS: you can hit enter and the changes get discarded
Linux: the cancel button is selected by default so hitting enter means to cancel

It should be consistent across OS imho.

**Comment by joaomoreno** [comment]
I have looked into this many times and failed to come up with a decent solution. Electron on Linux makes this very very hard.

**Comment by bpasero** [comment]
@joaomoreno I think we have many examples where this works just fine, e.g. see our "Save Untitled Workspace" dialog: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L1290

The thing is to set the cancelId properly.

**Comment by joaomoreno** [comment]
Related: https://github.com/electron/electron/pull/4029

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
