### ISSUE TITLE
Show workspace name in the title bar (windows)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31013]
Testing #30722

I've a workspace  called 'npm-vscode':
![image](https://user-images.githubusercontent.com/172399/28362827-4b8011b8-6c7e-11e7-88a9-eeba327b67c1.png)

When I open this workspace then the window title shows:

![image](https://user-images.githubusercontent.com/172399/28362844-5a37848e-6c7e-11e7-8848-ed182450c8aa.png)

I would have expected that the workspace title 'npm-vscode' shows up somewhere in the title bar.

**Comment by egamma** [comment]
Also when switching windows I'd like to switch to a workspace

![image](https://user-images.githubusercontent.com/172399/28363041-281c771a-6c7f-11e7-8a82-38915f445d57.png)

Notice the first two entries are workspaces.

**Comment by bpasero** [comment]
@egamma please retest again with latest insider 👍

**Comment by egamma** [comment]
works in the latest - closing
