### ISSUE TITLE
Wokspace folder was removed requires restart -> cancel leaves in strange state

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31010]
Refs: #30722

1. Remove the first root folder
2. Get the Ben vacation dialog -> say cancel
3. The folder still gets removed and me as the user I am puzzled why was the reload even needed.

Expected -> if I press cancel the folder does not get removed

**Comment by bpasero** [comment]
@isidorn how did you remove the first root folder?

**Comment by bpasero** [comment]
Oh I see. The dialog is actually asking to reload the window because we need to reload the extension host (we use the first root folder as legacy root path). If you cancel that you just cancel the window reload, but not the removal of the first folder.

**Comment by isidorn** [comment]
@bpasero yes

**Comment by bpasero** [comment]
Wording will be improved via https://github.com/Microsoft/vscode/issues/31014
