### ISSUE TITLE
Is there a way to delete an untitled workspace?

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31016]
Testing #30722

I've created several untitled workspaces. How do I get rid of them?

![image](https://user-images.githubusercontent.com/172399/28363308-5d8fd7ce-6c80-11e7-9137-4f792ee98609.png)

**Comment by bpasero** [comment]
@egamma please retest this on a later build where you get prompted when closing a window and the window contains an untitled workspace (similar to hot exit).

**Comment by egamma** [comment]
Cannot repro - closing
