### ISSUE TITLE
Show StoppedEvent.text in the UI

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3101]
The StoppedEvent defines a text attribute that can include the exception message if type is "exception", and I use this in my adapter:
```ts
/** Event message for "stopped" event type.
	The event indicates that the execution of the debugee has stopped due to a break condition.
	This can be caused by by a break point previously set, a stepping action has completed or by executing a debugger statement.
*/
export interface StoppedEvent extends Event {
	body: {
		/** The reason for the event (such as: 'step', 'breakpoint', 'exception', 'pause') */
		reason: string;
		/** The thread which was stopped. */
		threadId?: number;
		/** Additional information. E.g. if reason is 'exception', text contains the exception name. */
		text?: string;
	};
}
```
Howevery, VS Code currently ignores this.

```
<- stoppedEvent
StoppedEvent {
  seq: 0,
  type: 'event',
  event: 'stopped',
  body: 
   { reason: 'exception',
     threadId: 1,
     text: 'Warning: Illegal offset type' } }
```

![image](https://cloud.githubusercontent.com/assets/10532611/13129893/65f1c46e-d5e0-11e5-86dd-4e16829d24b1.png)

I would expect it to show something like 

> Paused on exception
> _Warning: Illegal offset type_

but it doesn't use the text at all. It is therefor not possible for my debug adapter to show the exception message to the user without creating a virtual scope "Exception" like the Node debugger does.

**Comment by isidorn** [comment]
I can show it in the hover message on the exception. Notice that we have removed the exception box for this milestone.

Creating a vritual scope 'Exception' might make it more clear to the user what is going on

![screen shot 2016-02-18 at 16 16 49](https://cloud.githubusercontent.com/assets/1926584/13147878/08d657f6-d65b-11e5-9788-0cad5e2788d7.png)

**Comment by felixfbecker** [comment]
I now implemented a virtual error scope. But it doesn't make much sense. I have to go through a lot of hurdes to keep it, keep Sets and Maps of all these virtual scopes. I have to take care of cases where an error occurs but the stack trace is empty (PHP Fatal Errors) and generate a virtual stack frame for the virtual scope to show up. I then have a virtual stack frame named "Error", a virtual scope named "Error" and inside it a single variable named "message" that contains the error message. It would be much simpler and better UI if VS Code had a way to show the exception message directly.

**Comment by isidorn** [comment]
We will show the exception message on hover over the 'paused on exception' box. This is not very visible, but I suggest we start with that.
As a workaround you can do the virtual error scope which I understand is a hurdle for you.
