### ISSUE TITLE
Error when adding a non-existing folder to the *.code-workspace file

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31011]
Testing #30722:

while I had a workspace open, I've edited the underlying *.code-workspace file in another VS Code window and added a path for a non-existing folder. 
I was impressed that the original VS Code workspace picked up the change and immediately showed the folder in the explorer. However clicking on the folder resulted in this error (for obvious reasons):

![2017-07-19_12-16-42](https://user-images.githubusercontent.com/1898161/28362399-90a93938-6c7c-11e7-8f8d-f32da0b8f36d.png)
 
Fixing the problem by creating the missing folder outside of VS Code seemed to fix the problem for VS Code too (since selecting the folder no longer showed an error).
However, trying to create a file in that folder had no effect and did not produce an error (even in chrome dev tools).

After a window reload I was able to create a file.

**Comment by bpasero** [comment]
Again related to: https://github.com/Microsoft/vscode/issues/29738

**Comment by isidorn** [comment]
Fixed via fix for #29738
