### ISSUE TITLE
Word Wrap not working in ubuntu 14.04 - 32 bit os 

### ISSUE THREAD

**Issue by maheprasath** [Microsoft/vscode#31028]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:11:38.274Z)
- OS Version: Linux ia32 3.13.0-63-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
format-php|Kas|1.1.2
php-formatter|Sop|0.2.4
better-comments|aar|0.1.3
html-snippets|abu|0.1.0
githistory|don|0.2.1
php-debug|fel|1.11.1
sublime-keybindings|ms-|2.9.1
vscode-icons|rob|7.10.1
react-beautify|tai|0.3.0
wordpress-snippet|tun|1.1.2

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@maheprasath  do you have `editor.wordWrap = true` in your settings file?

**Comment by maheprasath** [comment]
Yes Off Course 

"editor.wordWrap": true,

**Comment by rebornix** [comment]
@magnushiie this issue is fixed and will be shipped in our next recovery build. We changed the value from boolean to enum so to make it work at this moment, you can change the value to `"on"`. Thanks!

**Comment by magnushiie** [comment]
I believe the last comment was meant for @maheprasath
