### ISSUE TITLE
New Workspace should be seeded with the original folder

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31023]
Testing #30722

I have two folders carbon-core and carbon-extension and I want to create a workspace that contains these folders.

- open the folder carbon-core
- select 'Add Folder to Workspace'
- the info box shows up
![image](https://user-images.githubusercontent.com/172399/28363555-466991c4-6c81-11e7-9060-b4972960d84b.png)
- I confirm that I want to create a workspace and select 'New Workspace'
- A folder dialog shows up and I select carbon-extension, the folder I wanted to add to the workspace
- A new workspace opens with the status bar indication, that only shows the carbon-extension with the root folder hidden:
![image](https://user-images.githubusercontent.com/172399/28363680-b7960288-6c81-11e7-83d9-0804d32cb950.png)

At this point I was confused. I would have expected that this new workspace also includes carbon-core, since I wanted to add folder to carbon-core. In addition, since the root folder is hidden the only differentiation to an open folder is the different color in the status bar. 

I suggest that the info box wording is changed to:
"Do you want to create a new workspace _for the open folder_"
And the new workspace is then seeded with the currently opened folder.

**Comment by bpasero** [comment]
@egamma I think you must have used an old build for testing, e.g. the experience changed a lot and now you will see:

![image](https://user-images.githubusercontent.com/900690/28367923-f06008be-6c92-11e7-8c53-bd07f0a7cc56.png)

Can you confirm?

**Comment by egamma** [comment]
Verified much better flow now - closing.
