### ISSUE TITLE
Navigate to previous/ next SCM edit in a file

### ISSUE THREAD

**Issue by sagrawal-idrc** [Microsoft/vscode#31021]
- VSCode Version: Any
- OS Version: Any

Feature Proposal
In JetBrains IDEs such as PyCharm, one can press Ctrl+Atl+Shift+Up Arrow to navigate to the last SCM edit (even for a saved file) and Ctrl+Atl+Shift+Down Arrow to navigate to the next such edit. This is very handy in navigating to & further editing existing edits in a file.

**Comment by joaomoreno** [comment]
There are arrows which let you do this on a diff editor:

![image](https://user-images.githubusercontent.com/22350/28371329-f7760842-6c9c-11e7-80f4-80a7ba8798f2.png)

We still need global commands, which should work both on the diff editor as well as in the regular editor.

**Comment by sagrawal-idrc** [comment]
> We still need global commands, which should work both on the diff editor as well as in the regular editor.

Yes, thanks. 

Then, there is also Ctrl+Alt+Shift+Z, which restores an edit to the previous version. :-)

**Comment by joaomoreno** [comment]
The commands are: `Move the Next Change` and `Move the Previous Change` 👍
