### ISSUE TITLE
*.code-workspace files are always auto-saved

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31024]
Testing #30722:

- Turn of auto-save and hot-exit
- add or remove folders from workspace and notice the modification time of the corresponding *.code-workspace file

Observe: the file is immediately updated on disk

**Comment by bpasero** [comment]
I would not let the auto save configuration have an impact on the workspace file. The same is true when changing settings programmatically. 

Ideally the file is updated in the background without showing it (e.g. also no unsaved indicator). This will be possible once the writing to the file no longer goes through our text model layer.

**Comment by sandy081** [comment]
So we want always to write into the file (workspace config file) directly and gets auto saved. If so, we can close this. Writing directly to the disk is an implementation detail which will be handled as debt.
