### ISSUE TITLE
Better detection of unused variables

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#3102]
I don't know for the other languages, but in Javascript, if I write :

```Javacript
var myVar = 0;
myVar = 1;

// Do nothing more with myVar...
```

`myVar` is not considered as unused, but it should be.

**Comment by meritozh** [comment]
you can do it with a lint tool such as eslint

**Comment by Nimzozo** [comment]
@meritozh That's a suggestion. I use JSLint.

**Comment by egamma** [comment]
The new JS infrastructure Salsa will no longer report unused variables and defers this to a linter like JSLint, ESLint. For both ESLint and JSHint there are extensions for Code available.

**Comment by Nimzozo** [comment]
Ok, that's clearer.
