### ISSUE TITLE
Clicking object method triggers to change the active file in explorer window

### ISSUE THREAD

**Issue by wdmeeste1** [Microsoft/vscode#31025]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04
- Project code example for following use case: asp.net core application

In visual studio code when you click on a method of an object, to view the code of that method, the explorer (project) window will change the active file (where you did the click on the method) to the file of the method you clicked.

Is there a way to disable this behavior: so to open the file of the method but keep the explorer window on the file that you were working in? If this is not possible, could you create an option to change this behaviour?

See also stackoverflow question: https://stackoverflow.com/questions/45082909/clicking-object-method-triggers-to-change-the-active-file-in-explorer-window

**Comment by isidorn** [comment]
Set in your settings
"explorer.autoReveal": false
