### ISSUE TITLE
Auto indent doesn't work with code blocks JavaScript

### ISSUE THREAD

**Issue by chiv33s** [Microsoft/vscode#31027]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---
Language: Javascript:

When creating first code block "{" and pressing enter the auto fill and indent doesn't quite work as it used to, it creates the closing block and creates new lines, but does not indent them back to where they should be

a for loop looks like:
```
for(var key in object)
    {

    }
```

instead of:
```
for(var key in object)
{

}
```

the other way of doing it works fine when it looks like:
```
for(var key in object){

}
```

The same happens with if statements too, but it doesn't happen with switch statements
Steps to Reproduce:

1. create one side of code block "{" 
2. press enter to auto fill the rest

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/30933
