### ISSUE TITLE
IntelliSense does not follow "files" order in tsconfig.json unless you restart code

### ISSUE THREAD

**Issue by hoegge** [Microsoft/vscode#31030]
The visual studio code intellisense does not follow the order of files provided in tsconfig.json unless your restart code (or close and open the folder) and therefore produce false or "outdated" errors: 
`[ts] Class 'classname' used before its declaration`. 

- VSCode Version: 1.14.1
- OS Version: Windows 10 (up-to-date)

**Steps to Reproduce:**

1. Define classes in different files and use them in other files:

```ts
./a/b/b.ts:
class Bruno {
	constructor () {
		console.log("new Bruno");
	}
}

./a/c/c.ts
class Cecilie {
	constructor () {
		console.log("new Cecilie");
	}
}

./a/a.ts:
class Anne {
	constructor () {
		console.log("new Anne");
	}
}
//  instantiate b-class in a.ts
let BrunoObject:Bruno = new Bruno;
let CecilieObject: Cecilie = new Cecilie;

./main.ts
// instantiate a-class in main.ts
let AnneObject:Anne = new Anne;
// end main.ts
```

2. Code shows The `new Anne` works fine but `new Bruno` and `new Cecilie` do not, which is probably because the order intellisense use is random order. 
3. TSC will also give error messages:
```
a/a.ts(15,29): error TS2449: Class 'Bruno' used before its declaration.
a/a.ts(16,34): error TS2449: Class 'Cecilie' used before its declaration.
main.ts(11,27): error TS2449: Class 'Anne' used before its declaration.
```
4. Add the following to `tsconfig.json`:
```
"files": [
    "a/b/b.ts",
    "a/c/c.ts",
    "a/a.ts",
    "main.ts"
  ]
```
and save
5. TSC now compiles without any error messages, but intellisense still reports the TS error.
6. Close Code (or just Folder)
7. Open Code (or folder)
8. Intellisense does not show errors anymore
9. Remove files section from `tsconfig.json`
10. Intellisense does still not show errors
11. TSC cannot compile without errors.

Functions do not have the same issue (due to JS hoisting I assume)

**Expected behavior:**

I would expect Code to re-read tsconfig.json, when saved.

**Reproduces without extensions: **
No. The intellisense error messages (red lines) does not appear when loading with `code --disable-extensions`. If I load normally and unload all extensions, the intellisense errors show up, so not sure what produces them.

**Comment by codespear** [comment]
I found the same problem on version

VSCode Version: 1.15
OS Version: MacOS

**Comment by mjbvz** [comment]
I'm unable to reproduce this anymore with VSCode 1.16. I see the errors but no restart was required to clear them

In cases like the example where you are relying on global symbols being shared between files, you must have a TSConfig. I suspect that you were seeing errors in some cases without the `tsconfig.json` because only `a.ts` had been loaded while `b.ts` and `c.ts` had not been loaded. The `tsconfig.json` will force all the files to be loaded when you open the workspace
