### ISSUE TITLE
Wrap text with tags (html) deletes word instances starting $ sign

### ISSUE THREAD

**Issue by demosp** [Microsoft/vscode#31032]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
vscode-docker|Pet|0.0.16
Bookmarks|ale|0.15.2
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
vscode-npm-source|dku|1.0.0
jquerysnippets|don|0.0.1
flow-for-vscode|flo|0.7.1
knockoutjs|fur|0.1.0
vscode-text-pastry|jkj|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.3.3
csharp|ms-|1.11.0
sublime-keybindings|ms-|2.9.1
team|ms-|1.121.1
debugger-for-chrome|msj|3.1.6
debugger-for-ios-web|msj|0.1.2
vscode-css-peek|pra|1.3.1
vscode-react-native|vsm|0.3.2
change-case|wma|1.0.0
---
Using [knockout.js](http://knockoutjs.com/) data binds in html elements like:

```html
<ul data-bind="foreach: contactsArray">   
   <li data-bind="text: $data.name"></li>
</ul>
```
If I want to wrap the above in another div tag via CTRL+SHIFT+W, the command strips out the `$data` instance and am left with:

```html
<div>
    <ul data-bind="foreach: contactsArray">
        <li data-bind="text: .name"></li>
    </ul>
</div>
```

Same with `$root`, `$parent` etc. 

Works  fine if the `$` sign is escaped with a backslash.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Nice catch @demosp 

I am assuming that you have bound `Ctrl+Shift+W` to `Emmet: Wrap with Abbreviation` command.

@sergeche To implement the `Wrap with Abbreviation` feature, I used the `expand` module and passed the text to be wrapped via the `text` option.
Is escaping `$` from the `text` what you suggest?
If yes, what else should I be escaping?

**Comment by demosp** [comment]
Yes @ramya-rao-a , I have bound `Ctrl+Shift+W` to `Emmet: Wrap with Abbreviation`.

So far I only noticed the issue with a `$`

**Comment by ramya-rao-a** [comment]
Turns out the problem was not with emmet expansion.
When we form the snippet and send it to VS Code, they get treated as variables and get replaced.

Fixed with https://github.com/Microsoft/vscode/commit/24ca702d2358970585c885fad9dd0f6784f29a9d
