### ISSUE TITLE
About using Ctrl+R to Switch folder in current window

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#31031]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

https://code.visualstudio.com/updates/v1_14#_switch-window-improvements

>Press Ctrl+R and leave the Ctrl key pressed. As long as you now press the R key, you can navigate through the list of windows. Release all keys to focus it.

1. have one vscode window opening.
2. want to use Ctrl+R to switch to a recently used window, I press Ctrl+R only once and then release all keys.

Then I have to click the second line to switch to the most recent folder.

Is this by design?

**Comment by bpasero** [comment]
@King66 did you configure your keybinding like this:

```json
{
    "key": "ctrl+r",
    "command": "workbench.action.quickSwitchWindow"
},
{
    "key": "ctrl+r",
    "command": "workbench.action.quickOpenNavigateNext",
    "when": "inWindowsPicker"
}
```

**Comment by King66** [comment]
hello, I use default settings:
```
{
    "key": "ctrl+r", 
    "command": "workbench.action.openRecent"
},
{
    "key": "ctrl+r",
    "command": "workbench.action.quickOpenNavigateNextInRecentFilesPicker",
    "when": "inQuickOpen && inRecentFilesPicker"
}
```

So I can use "ctrl+r" to switch to a recent folder(usually most recent folder).
But after releasing all keys, I have to do one more step: click the second line.

**Comment by bpasero** [comment]
@King66 yes you have to change your keybindings in the way I described to get the behaviour.

**Comment by King66** [comment]
Sorry , I didn't express clearly. I don't want to switch window, I want to switch folder in current Window.(want to use default settings)
```
want to use Ctrl+R to switch to a recently used window, 
I press Ctrl+R only once and then release all keys.
```
Should be
```
want to use Ctrl+R to switch to a recently used folder, 
I press Ctrl+R only once and then release all keys.
then I have to do one more step: click the second line.
```

**Comment by bpasero** [comment]
@King66 sorry, I copied the wrong keybinding. Here you go:

```
{
    "key": "ctrl+j",
    "command": "workbench.action.quickOpenRecent"
},
{
    "key": "ctrl+j",
    "command": "workbench.action.quickOpenNavigateNext",
    "when": "inRecentFilesPicker"
}
```

**Comment by King66** [comment]
It works, thanks!
