### ISSUE TITLE
Eliminate Workspace submenu by merging actions into the File menu

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31036]
Testing #30722:

Having workspaces appearing under "Open Recent..." and in the "Workspace" menu is a bit confusing.
I suggest to eliminate the Workspace submenu by merging its actions directly into the corresponding sections of the File menu.

**Comment by bpasero** [comment]
![pasted image at 2017_07_20 08_17 am](https://user-images.githubusercontent.com/900690/28403275-61b83d2e-6d24-11e7-8e79-41c4c6e1585f.png)
![pasted image at 2017_07_20 08_17 am 1](https://user-images.githubusercontent.com/900690/28403276-61b9231a-6d24-11e7-8032-665f01b9ee4f.png)
