### ISSUE TITLE
Flickering on mac OS with external display

### ISSUE THREAD

**Issue by MFairley** [Microsoft/vscode#31049]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.7
language-julia|jul|0.6.2
ftp-sync|luk|0.3.3

---

Steps to Reproduce:

1. Open Visual Studio Code with external monitor and put VSCode window on the external monitor
2. Move mouse over the window with window in focus.

Reproduces without extensions: Yes/No

I am having an issue with parts of the UI flickering when using an external monitor (4k). I previously never had this issue with VSCode on this monitor. I have tried these settings. They helped but did not completely eliminate the flickering.

```
// Fix flickering
"editor.disableTranslate3d": true,
"window.zoomLevel": 0
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/25934
