### ISSUE TITLE
Brand new storage for workspaces can be frustrating

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31043]
Refs: #30722

I am working on vscode all the time and now I started working on multi root with also vscode-docs. Everything is great except I get pestered by a lot of ux things which I have dismissed already in the past. These include:

1. Welcome page
2. Workspace recommendations
3. TS check

Probably many others.
I do not have a suggestion on how to improve this, but we should be aware that this can be frustrating. Maybe some transition strategy for the storage would be useful.

**Comment by isidorn** [comment]
Actually the main problem is that some of those should be saved in user storage not in workspace storage

**Comment by bpasero** [comment]
Yes, one idea eventually is to make the transition from single folder to workspace not require the extra step through the workspace. I would like to close this one as duplicate of https://github.com/Microsoft/vscode/issues/30972
