### ISSUE TITLE
ShellTask executed in wrong working directory when the Terminal is reused

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31058]
I've added multi root support for the npm script runner. I now pass the cwd of the package.json containing the script to the ShellTask as an option. This works fine in the single root case and the reuse of the terminal works.

In the multi root case a different cwd can be passed for npm scripts that are located in different root folders. In this setup a script can be executed inside the wrong working directory.

As a workaround I killed the Terminal in between task runs and the issue doesn't show up.

**Comment by dbaeumer** [comment]
I can reproduce this even in a config file setup. I debugged and everzthing is passed correctly to the terminal `reuseTerminal` call but for some reason the terminal uses the cwd of its initial first launch. Here are steps to reproduce (tested under Windows):

- Workspace, now multi root with a folder client and server and different files in it.
- tasks.json
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"taskName": "build",
			"command": "dir",
			"problemMatcher": [],
			"options": {
				"cwd": "${workspaceRoot}\\client"
			}
		}
	]
}
```
- run the task
- Observe: the content of the client folder is listed
- change the options literal to
```
			"options": {
				"cwd": "${workspaceRoot}\\server"
			}
```
- run the task
- Observe: the content of the client folder is listed. It should list the content of the server folder.

**Comment by dbaeumer** [comment]
I debugged it and `TerminalInstance._createProcess` receives a shell configuration with the correct cwd set. So it seems to be a problem how a process is launched if the terminal is reused.
