### ISSUE TITLE
Add Sync (Rebase)

### ISSUE THREAD

**Issue by simplysh** [Microsoft/vscode#31055]
I suggest having a *Sync (Rebase)* option under *Sync*.

Most of the times I find myself having to manually run the two commands simply because sync uses regular pull. I don't want to edit my git configuration to always rebase either.

I think it makes sense to have a *Sync (Rebase)* option since there already is a *Pull (Rebase)*, and sync uses pull.

**Comment by joaomoreno** [comment]
This is a git configuration: https://git-scm.com/docs/git-config#git-config-pullrebase

**Comment by simplysh** [comment]
Hi @joaomoreno thanks for replying, but I already said:

>I don't want to edit my git configuration to always rebase either.

If I should edit my configuration, what's the purpose of Pull (Rebase)?

As it stands, the sync command is barely useful to me. I have to always switch to the terminal to sync my changes after committing within VSCode. In my opinion, a pull with rebase is a far better use case for sync.

**Comment by joaomoreno** [comment]
I missed that sentence, sorry about that.

**Comment by simplysh** [comment]
No worries! Sure, I can definitely have a go at it!

**Comment by excerebrose** [comment]
@joaomoreno I have created a PR for this that should hopefully work! #31416

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/31416

**Comment by dbaeumer** [comment]
Verified that Sync (Rebase) exists as a command. It is not available in the Git action drop down.
