### ISSUE TITLE
Format code breaks plain text inside tags for no reason

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31050]
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:31:43.209Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.27.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Take a simple paragraph of text, such as
````html
<p>Our forms for collecting address-related information follow a standard design. Specific input elements will vary according to the form’s audience and purpose.</p>
````
2. Run "Format Document" (shift-option-F)
3. You get 
````html
<p>Our forms for collecting address-related information follow a standard design. Specific input elements will vary
              according to the form’s audience and purpose.</p>
````
I don't see why this is.  I would expect the text inside the `p` tags to remain as is.

![jul-19-2017 11-03-16](https://user-images.githubusercontent.com/835148/28374293-52d2a98c-6c72-11e7-9fcc-7c7b6c662254.gif)

**Comment by ramya-rao-a** [comment]
@isidorn html formatting would be @aeschli

**Comment by aeschli** [comment]
You can configure which tags should not be formatted with the setting "html.format.unformatted"

**Comment by smlombardi** [comment]
@aeschli Well, i _do_ want `p` tags formatted.  But why does "formatting" the tag arbitrary break the plain text inside the tag?  That makes no sense.

**Comment by aeschli** [comment]
Please file an issue against https://github.com/beautify-web/js-beautify/issues... It's the html formatter we use under the hood.
