### ISSUE TITLE
Var and function keywords not colored in js

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3105]
I know you mentioned `function` not being colored, but I do not remember you saying that `var` is not coloured.

![screen shot 2016-02-18 at 09 45 52](https://cloud.githubusercontent.com/assets/1926584/13137942/7351c318-d624-11e5-9242-f25ffeb8a571.png)

**Comment by dbaeumer** [comment]
@isidorn  which theme are you using. The light one ? And theming is @aeschli :-)

**Comment by isidorn** [comment]
Regular light theme, not light+. Light+ does a proper job.
I would expect var, function to be coloured in all themes. Thought that just might be me

**Comment by Tyriar** [comment]
Light/Dark (Visual Studio) seem to be very broken on latest stable. Is the plan to delete them and migrate users to Dark/Light+ for next release?

**Comment by aeschli** [comment]
This is issue https://github.com/Microsoft/TypeScript-TmLanguage/issues/44
