### ISSUE TITLE
Emmet wrap with abbreviation does not work with multiple cursors

### ISSUE THREAD

**Issue by michou** [Microsoft/vscode#31051]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. In an HTML document, select text on multiple lines
2. Use the `insertCursorAtEndOfEachLine` shortcut (`Alt` + `Shift` + `I` on Mac) to create a multi-cursor selection
3. Select multiple words on each line (e.g. with `Shift` + `⬅️`)  
4. Call up the _Emmet: Wrap with abbreviation_ command and enter e.g. `span`

Results:
Only the first selection is wrapped with the abbreviation and the multiple cursors / selections are discarded.

Expected:
All selections are wrapped with the abbreviation and the selections are preserved.

**Comment by ramya-rao-a** [comment]
@michou Do you have `emmet.useNewEmmet` set to `true`?

**Comment by michou** [comment]
@ramya-rao-a this reproduced with `emmet.useNewEmmet: false`. It doesn't reproduce anymore when setting it to `true`.

**Comment by ramya-rao-a** [comment]
In the old emmet model, multi cursor was never supported. It is a new feature in the new model.
