### ISSUE TITLE
"View file in explorer" (CMD-SHIFT-E) doesn't work anymore

### ISSUE THREAD

**Issue by gotofritz** [Microsoft/vscode#31057]
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:31:43.209Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-tidyhtml|anw|1.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.1
RelativePath|jak|1.0.0
vscode-duplicate|mrm|1.1.0
debugger-for-chrome|msj|3.1.6
json-organizer|rin|0.0.3
vim|vsc|0.9.0

---

Steps to Reproduce:

1. In the preferences, set explorer.autoReveal to false
2. open a project, open file A
3. open another file, B
4. select file A again the editor
3. Do cmd-shit-E to "view file in explorer"

Expected: the explorer should scroll to where the file is (opening folders as necessary)
Actual: the explorer is selected, but it only highlights and focuses on whatever was already selected

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@gotofritz showing the explorer will not reveal the file automatically, what you need to use is "Reveal active file in side bar": 

![image](https://user-images.githubusercontent.com/900690/28401180-8cb7c2a8-6d18-11e7-9089-641c3da237c1.png)

Are you seeing issues with that command? This could be a regression from our multi root work.

**Comment by gotofritz** [comment]
Yes you are right. Sorry for wasting your time.
