### ISSUE TITLE
cannot connect to java servers?

### ISSUE THREAD

**Issue by cshi0** [Microsoft/vscode#31053]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
java|red|0.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this issue to the java vscode extension, thank you
