### ISSUE TITLE
Support that a task can show auxilliary information - e.g. the path

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31064]
Pls see the screenshot below:

![image](https://user-images.githubusercontent.com/172399/28382475-851fe714-6cbe-11e7-8a2c-f74fe243dc6c.png)

I would like to the path to the npm script in the same 'dimmed' way as is done here

![image](https://user-images.githubusercontent.com/172399/28382517-acd86b5a-6cbe-11e7-8304-7ba69556b5b2.png)

**Comment by dbaeumer** [comment]
This got address by additional API in the extension host. The rendering is subject to VS Code.
