### ISSUE TITLE
Leading whitespace is compacted when using unicode overline, dot above, etc.

### ISSUE THREAD

**Issue by tkoolen** [Microsoft/vscode#31068]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.1
language-julia|jul|0.6.2
cpptools|ms-|0.12.1

---

Steps to Reproduce:

1. Create new file
2. Type `<tab>`, then `x`, then `<return>`
3. New line is auto-indented. Type or copy-paste `ẋ` (note the overdot)
4. Compare indentation between first line and second line. The number of spaces is the same between the two lines, but the spaces on the second line are thinner.

This also happens with ẍ, x̄, etc.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I cannot reproduce on OSX, will try on Linux:

<img width="136" alt="screen shot 2017-08-09 at 08 42 06" src="https://user-images.githubusercontent.com/5047891/29108316-a6bf5ba4-7cde-11e7-81ab-4444ffcd6b84.png">

<img width="142" alt="screen shot 2017-08-09 at 08 42 45" src="https://user-images.githubusercontent.com/5047891/29108338-be9e2fca-7cde-11e7-94a8-b63852f2e7a5.png">

**Comment by alexandrudima** [comment]
I also cannot reproduce on linux:

<img width="131" alt="image" src="https://user-images.githubusercontent.com/5047891/33659873-2a8478d8-da82-11e7-9b3a-c37a4ae843f2.png">

<img width="132" alt="image" src="https://user-images.githubusercontent.com/5047891/33659885-34eb8bea-da82-11e7-8621-2be3f322b0e9.png">

**Comment by tkoolen** [comment]
Sorry, yes, I confirm that this has been fixed on Linux now. Thanks!
