### ISSUE TITLE
Typescript intellisense and autocomplete not working when tsconfig.json has "extends" field

### ISSUE THREAD

**Issue by ecephas** [Microsoft/vscode#31067]
- VSCode Version:  1.14.0
- OS Version: Windows 7

Steps to Reproduce:

1. create a base tsconfig
2. create a tsconfig.json and add the field "extends" to it and provide relative path to another tsconfig

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
To help investigate:

1. Please share your `tsconfig`s. 
1. Do you see any errors in the `TypeScript` section of the output pane?
1. If you run the `Go to project configuration` command in a TS file in your project, does it open the `tsconfig`?

**Comment by simonua** [comment]
#30580 may relate. Had a coworker who had similar issue as @ecephas. After upgrading to 1.14.2, Intellisense was working for him again.

**Comment by ecephas** [comment]
This issue has been resolved in VSCODE 1.14.2.  Thank you.

**Comment by ecephas** [comment]
@mjbvz thanks for the follow up.
