### ISSUE TITLE
 Uncaught Error: Could not find file: '

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3106]
Issue Id: <b>b30f73b1-cbf2-03a2-8b40-b55804997341</b><br /><br />*Versions* <br />- 0.10.8<br />*Stack* <br />Error: Could not find file: '<br />[vs/languages/typescript/common/lib/vs/languages/typescript/common/lib/raw.typescriptServices.js#L39478:0](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/srcvs/languages/typescript/common/lib/vs/languages/typescript/common/lib/raw.typescriptServices.js#L39478:0)<br />[vs/languages/typescript/common/lib/vs/languages/typescript/common/lib/raw.typescriptServices.js#L39630:0 (getValidSourceFile)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/srcvs/languages/typescript/common/lib/vs/languages/typescript/common/lib/raw.typescriptServices.js#L39630:0 (getValidSourceFile))<br />[/vs/languages/typescript/common/features/diagnostics.ts#L23:33 (getSyntacticDiagnostics)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/languages/typescript/common/features/diagnostics.ts#L23:33 (getSyntacticDiagnostics))<br />[/vs/languages/typescript/common/typescriptWorker2.ts#L159:42 (TypeScriptWorker2.doValidate)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/languages/typescript/common/typescriptWorker2.ts#L159:42 (TypeScriptWorker2.doValidate))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L95:9 (AbstractModeWorker.doValidateOnChange)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/common/modes/abstractModeWorker.ts#L95:9 (AbstractModeWorker.doValidateOnChange))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L78:7 (AbstractModeWorker._newValidate)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/common/modes/abstractModeWorker.ts#L78:7 (AbstractModeWorker._newValidate))<br />[/vs/editor/common/modes/abstractModeWorker.ts#L46:59 (AbstractModeWorker.constructor)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/common/modes/abstractModeWorker.ts#L46:59 (AbstractModeWorker.constructor))<br />[/vs/editor/common/worker/validationHelper.ts#L182:7 (ValidationHelper._invokeCallback)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/common/worker/validationHelper.ts#L182:7 (ValidationHelper._invokeCallback))<br />[/vs/editor/common/worker/validationHelper.ts#L103:51 (ValidationHelper.constructor)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/editor/common/worker/validationHelper.ts#L103:51 (ValidationHelper.constructor))<br />[/vs/base/common/async.ts#L493:8 (RunOnceScheduler.onTimeout)](https://github.com/microsoft/vscode/blob/db71ac615ddf9f33b133ff2536f5d33a77d4774e/src/vs/base/common/async.ts#L493:8 (RunOnceScheduler.onTimeout))<br />

**Comment by egamma** [comment]
// @alexandrudima

**Comment by dbaeumer** [comment]
Closing. This is the typescript language worker code I removed yesterday. Not shipping anymore :-)
