### ISSUE TITLE
vscode calls `git status` when in background, which can cause other git usages to fail

### ISSUE THREAD

**Issue by joelhock** [Microsoft/vscode#31069]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
you-complete-me|Ric|1.0.36
project-manager|ale|0.18.1
githistory|don|0.2.1
python|don|0.6.7
gitlens|eam|4.3.1
vscode-great-icons|emm|2.1.11
cpptools|ms-|0.11.4
rewrap|stk|1.4.1
better-align|wwm|1.1.6

---

This is a new issue to track the discussion starting at this point on an old issue starting here:
https://github.com/Microsoft/vscode/issues/901#issuecomment-309294814

@fredizzimo @alexjeffburke @benesch have all recently reported the same problem.

Steps to Reproduce:

1. open vscode to a git project
2. switch away from vscode to a terminal
3. touch a file in in git project
4. observe the blue "clock" on top of the version control icon flashes in vscode
5. occasionally, trying to do a rebase in the terminal window with vscode open in the background will fail with `fatal: Unable to create '.git/index.lock': File exists`

You can avoid the problem with `"git.autorefresh": false`, but it's sad to have to lose all the functionality just to avoid this problem.  I posit that the protections against background `git status` calls added in faeb58e were lost when the git code was refactored into an extension.

I've gone so far as to run this in the background, but it's a bit convoluted to expect people to do that.
```
#!/usr/bin/env osascript -l JavaScript

function run(argv) {
    var app = Application.currentApplication()
    app.includeStandardAdditions = true

    vscode = Application('Electron')
    // add git.autorefresh to user config file if it isn't already there
    app.doShellScript('grep -q git.autorefresh ~/Library/Application\\ Support/Code/User/settings.json || ' +
                      'perl -i -0pe \'s%(.*)}(.*)%$1\\n    //updated by external script\\n    , "git.autorefresh": true\\n}$2%s\' ~/Library/Application\\ Support/Code/User/settings.json')
    while (vscode.running()) {
        delay(1)
        if (vscode.frontmost()) {
            app.doShellScript(
                'grep -q \'"git.autorefresh": false\' ~/Library/Application\\ Support/Code/User/settings.json && ' +
                'sed -e \'s/"git.autorefresh": false/"git.autorefresh": true/\' -i .bak  ~/Library/Application\\ Support/Code/User/settings.json || true')
        } else {
            app.doShellScript(
                'grep -q \'"git.autorefresh": true\' ~/Library/Application\\ Support/Code/User/settings.json && ' +
                'sed -e \'s/"git.autorefresh": true/"git.autorefresh": false/\' -i .bak  ~/Library/Application\\ Support/Code/User/settings.json || true')
        }
    }
}
```

**Comment by joaomoreno** [comment]
Thanks for the details. We already have a discussion going on here: #11918, merging with that. Will promote it to July.
