### ISSUE TITLE
Set.prototype.entries does not work in debugger

### ISSUE THREAD

**Issue by mgwhitfield** [Microsoft/vscode#31066]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Add file with "(new Set('1')).entries();"
2. Add debug target in launch.json to run this file
3. Set a breakpoint and notice the watch value of Set.prototype.entries/.keys/.values resolves to undefined

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@mgwhitfield 
What version of node are you using?
Are you using the "legacy" or the "inspector" protocol?
