### ISSUE TITLE
VS Code not honoring editor.tabSize override in user settings

### ISSUE THREAD

**Issue by Petertaylor9999** [Microsoft/vscode#31062]
I would like the tab key to insert two spaces in JSON and markdown files when I press it. According to the status bar "Spaces: 2". When I press the tab key, it inserts 4 spaces.

I know I need to override editor.detectIndentation, so I've done that. Here's what my user settings look like:

```JSON
{
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 5000,
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.wordWrap":"wordWrapColumn"
}
```

Any suggestions?

**Comment by rebornix** [comment]
@Petertaylor9999 did you already have 4 spaces in your content? For example, 

```
if (true) {
    if (true) {
        console.log();
|
    }
}
```

Let's say we were using 4 spaces tab and now we change the tabSize settings, pressing tag at current cursor position will lead to 4 spaces tab as we try to align indentation. However if you put your cursor after the last closing bracket, tab will generate 2 spaces. Can you double check this?

BTW, you may also want to check whether you have workspace settings which override the tabsize settings, which is not very likely but just in case.
