### ISSUE TITLE
Automatically add dnf repository on .rpm install

### ISSUE THREAD

**Issue by ayuopy** [Microsoft/vscode#31071]
I recently installed the Skype for Linux .rpm via dnf - doing so added a skype-stable yum repository automatically. I could then agree to key signing upon the next dnf upgrade. 

I thought that this might be an idea for future releases of the VSC .rpm, rather than having to add it manually.

**Comment by Tyriar** [comment]
https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
