### ISSUE TITLE
 Uncaught Error: Could not find file: '

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#3107]
Issue Id: <b>b30f73b1-cbf2-03a2-8b40-b55804997341</b><br /><br />*Versions* <br />- 0.10.8<br />*Stack* <br />Error: Could not find file: '<br />    at i (out/vs/languages/typescript/common/lib/typescriptServices.js:26:16691)<br />    at Object.v [as getSyntacticDiagnostics] (out/vs/languages/typescript/common/lib/typescriptServices.js:26:18364)<br />    at Object.s [as getSyntacticDiagnostics] (out/vs/languages/typescript/common/typescriptWorker2.js:5:4074)<br />    at t.doValidate (out/vs/languages/typescript/common/typescriptWorker2.js:5:24034)<br />    at t.e.doValidateOnChange (out/vs/editor/common/worker/editorWorkerServer.js:11:30659)<br />    at t.e._newValidate (out/vs/editor/common/worker/editorWorkerServer.js:11:30370)<br />    at e._callback (out/vs/editor/common/worker/editorWorkerServer.js:11:29716)<br />    at e._invokeCallback (out/vs/editor/common/worker/editorWorkerServer.js:11:20059)<br />    at e.runner (out/vs/editor/common/worker/editorWorkerServer.js:11:18576)<br />    at e.onTimeout (out/vs/editor/common/worker/editorWorkerServer.js:6:30299)<br />

**Comment by dbaeumer** [comment]
I removed that code yesterday from VSCode.

**Comment by dbaeumer** [comment]
@jrieken FYI. If this reappears in the standalone editor since it is the JS language service using typescript.
