### ISSUE TITLE
Regex Find works differently than Find in Files

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Microsoft/vscode#31077]
The **Find** command, with regex turned on, seems to be implemented with a different flavor of regex than the **Find in Files** command. The latter returns errors when not escaping braces, while the former does not.

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
dart-code|Dan|2.1.0
xml|Dot|1.9.2
vscode-docker|Pet|0.0.16
Bookmarks|ale|0.15.2
thrift|cdu|0.0.1
vscode-yaml-validation|dja|0.0.1
python|don|0.6.7
Go|luk|0.6.62
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|2.9.1
java|red|0.7.0
gitblame|wad|1.11.3

(2 theme extensions excluded)

Steps to Reproduce:

1. Create a document with `foo{}` in it.
2. Initiate the **Find** command, turn on Regex
3. Type `foo{}` in the Find field. You should get a match.
4. Try **Find in Files**, with the same search.
5. This results in a parse error, shown below.
6. A character group results in a different error — see the 2nd screenshot below.
7. Add a backslash before brackets — `foo\{\}` — and the searches now work.

![screen shot 2017-07-19 at 2 19 45 pm](https://user-images.githubusercontent.com/7768348/28390102-86f7fe54-6c8d-11e7-94a1-dbdf51b2ff03.png)

![screen shot 2017-07-19 at 2 20 57 pm](https://user-images.githubusercontent.com/7768348/28390106-8fe895d2-6c8d-11e7-97e2-9a02280caa40.png)

Reproduces without extensions: **Yes**

**Comment by rebornix** [comment]
The Find widget is using JavaScript regex while the Search Viewlet is using ripgrep under the hood, which is based on Rust's regex engine. @roblourens can confirm the difference.

**Comment by roblourens** [comment]
That's correct

**Comment by aaronkavlie-wf** [comment]
The underlying reason for the difference is clear now, and it was nice to get a rapid reply explaining that.
However, as a user I think it's sensible to expect that the regex search functionality behaves the same, whether search across the project, or within a single file. Might these be unified in a future release?

**Comment by roblourens** [comment]
Well, it's probably not likely. From what I understand, the Rust regex engine is built with some tradeoffs that preclude some regex features like lookaround. I think it's reasonable to expect that consistency too, but I decided I'd rather have an extremely fast search, and that's the compromise we made by using the ripgrep search tool. If you absolutely need advanced regex features, you can set `"search.useRipgrep": false`.
