### ISSUE TITLE
VSIX: Right click -> Install

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#31079]
It happens fairly frequently to package an extension and install it while developing them. 

Right now we have to do this:
- Open the command palette
- Run `Extensions: Install from VSIX...`
- Locate the right folder
- Select the *.vsix file

I think this can be shortened quite a bit by adding an `Install` option 
- Drag and dropping the visx onto VSC
- when right clicking *.vsix files from the tree view.
- when double clicking the .vsix file

What do you think?

**Comment by sandy081** [comment]
This can be contributed by an extension by providing a context menu action

**Comment by fabiospampinato** [comment]
I've just published such [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix).

But IMHO the UX is sub-optimal. Since there's no API for triggering an installation programmatically the extension calls `code --install-extension /path/to/extension.vsix` in a terminal. This approach as a few problems:
- The user must have the `code` command installed
- There's basically no way of knowing if the installation succeeded or not
- It can't show the information message prompting for a restart right after the `code` command terminated, because there's basically no way of knowing when it terminated.

If for whatever reasons you don't want to include a feature like this, couldn't you implement an API for installing extensions so that this feature can be implemented properly?

**Comment by sandy081** [comment]
@fabiospampinato Appreciated with trying out. Reopening to consider providing an option to install vsix extension.

**Comment by fabiospampinato** [comment]
Great, thanks!

**Comment by octref** [comment]
Just adding that the feature requested in my issue is "Drag and Drop to install", which is different than this one.

**Comment by sandy081** [comment]
@octref You are right. I think all of these are related so wanted to have single issue tracking them.

**Comment by yozlet** [comment]
Does this issue also cover invoking the VSCode executable, providing a `.vsix` file as a file parameter? For example:

1. `code my-extension.vsix`
2. Opening the `.vsix` extension from the OS's file explorer, with VSCode set as the handler for that file type

... because those would be really handy too.

**Comment by sandy081** [comment]
No. There is already a way to install a vsix from command line.

`code --install-extension my-extension.vsix`

**Comment by DanTup** [comment]
Maybe slightly off-topic, but is there any possibility that double-clicking a vsix on Windows can be "fixed"? It's confusing and people seem to skip over the instructions on the page they download vsix from... It'd be nice if Code has its own file extension (even if it's the same file), or a future VS update could be taught how to handle these better (currently you get a nice big error/stack on the screen).

**Comment by usernamehw** [comment]
Context menu item seems to be implemented: #108787.

**Comment by sandy081** [comment]
@usernamehw  Thanks for finding the dup.
