### ISSUE TITLE
Error: Cannot connect to runtime process (reason: read ECONNRESET)

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31072]
Version Info

![image](https://user-images.githubusercontent.com/1487073/28386930-0be442f0-6c82-11e7-94c2-6c685919c472.png)

Steps to Reproduce:

1. Start VS Code, open a simple extension workspace (e.g. the "Hello World" extension generated by `yo code`)
2. File | New Window
3. in the new window, open another folder (doesn't matter what)
4. In the extension instance, press F5

Result:

In the second instance of VS Code, I see an Error Cannot connect to runtime process (reason: read ECONNRESET)

![image](https://user-images.githubusercontent.com/1487073/28386901-f007acac-6c81-11e7-8c30-28b89e7ec176.png)

The extension development host opens fine.

**Comment by weinand** [comment]
@chrisdias we are aware of this issue and the fix has been pushed.
In the second window we just listen on a broadcast and do the wrong thing.
However debugging in the first window works fine.
