### ISSUE TITLE
Need a way for extensions to disable textmate quickSuggestions during textDocument/completion

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#31075]
- VSCode Version: 1.14.1
- OS Version: All

Steps to Reproduce:

1. Enable quickSuggestions and wordBasedSuggestions.
2. Type some C++ code like "#pragma o<Enter>".

Bug: The "o" on Enter will get autocompleted undesirably and there's no way for the language extension to disable the wordBasedSuggestion. VS Code has the comments and strings settings, but it doesn't allow extensions to have it's own classification to disable quickSuggestions (i.e. if the extension knows the code is like a comment/etc. and shouldn't autocomplete).

Reproduces without extensions: No

**Comment by jrieken** [comment]
There is a user setting `snippetSuggestions` which controls that. Tho, just repeating what I have said many times before: The fact that CPP tools try to force me into a certain style of working is considered bad style. It's up to the user to configure the IntelliSense behaviour and not up to you guys. @sean-mcmanus How would you feel if the TypeScript extensions enforces that the explorer shows on the right instead and that the status bar color is pink?

**Comment by sean-mcmanus** [comment]
`snippetSuggestions` doesn't control that -- VS Code itself doesn't provide snippets for C++. I think mean the `quickSuggestions` and `wordBasedSuggestions` settings. The problem is that we only want it disabled in certain language-specific context. In a #pragma or variable declaration, quickSuggestions is not desirable, so trying to do a `#pragma once` or `class oClass` will autocomplete to some bogus pre-existing variable starting with o whenever Enter is pressed. We want C++ users to have a good out of the box default experience, similar to in VS 2017, which doesn't invoke a quickSuggestion in places were it is not desirable. It's okay if a user explicitly chooses to show a completion list there via a keyboard shortcut. VS Code has already added the comment and string settings for quick suggestions, but C++ has other context where we want to disable quickSuggestions by default.

**Comment by bobbrow** [comment]
@jrieken, this is not a case of style.  We are not changing editor settings. We are responding to language service requests.  This is a case of the extension saying "there is no good suggestion for you at this time."  When we tell VS Code that there is no good suggestion, VS Code is stepping in and overriding our language service.  How would you feel if your language service was trying to do the right thing and then VS Code stepped in and said, "no, I want to do it this way instead"?

Please reconsider.
