### ISSUE TITLE
Lose config almost on every upgrade

### ISSUE THREAD

**Issue by qoops-1** [Microsoft/vscode#31076]
- VSCode Version: 1.14.1
- OS Version: mac os el capitan

I lose my configuration on almost every upgrade of VS Code to the next version ever since some time in the spring. I have seen a similar issue #21676 but is seems to be resolved there. 

In my case, the whole /User folder gets deleted inside `~/Library/Application\ Support/Code`, what could cause this? Could it be that I've setup locale inside VS Code different from default on my laptop? 

I thought it stopped for me recently, however, it has just happened again with upgrade to 1.14.1. I have cleared caches right before upgrading, though, by removing all folders from `~/Library/Caches/`.

VS Code is an awesome product, but this issue is a stopper for me

**Comment by joaomoreno** [comment]
What extensions do you have installed?

**Comment by qoops-1** [comment]
- Emacs Keymap
- ESLint
- Git Project Manager
- Go
- Intellisense for CSS class names
- language-Ansible
- npm
- Intellisense
- npm
- Path Intellisense
- Python
- vscode-icons

**Comment by joaomoreno** [comment]
This might be an issue with one of your extensions doing this.

If you want to reproduce, [here's the link to 1.13.1](https://az764295.vo.msecnd.net/stable/379d2efb5539b09112c793d3d9a413017d736f89/VSCode-darwin-stable.zip). Install that, run it, wait for an update. Does it happen?

If so, remove all your extensions and try again. Does it still happen?

**Comment by qoops-1** [comment]
Tried it. Config still in place this time, nothing got lost

**Comment by joaomoreno** [comment]
cc @bpasero Have you seen this before?

**Comment by bpasero** [comment]
@qoops-1 are you sure the entire folder gets deleted or is it "just" your settings.json file becoming empty?

**Comment by qoops-1** [comment]
The folder stays in place but all the contents are deleted. Pretty sure about it because as well as my settings my locale gets reset. I have also checked the folder then and I am pretty sure it was empty

**Comment by Tehnix** [comment]
Not entirely sure if this should go here, but I *just* experienced my settings being overwritten for the first time. For some reason it behaved as if it just updated to version 1.18, and I suspect either _vscodevim_ or _Atom Keymap_ was involved, since I briefly saw a ton of errors popping up from them.

I noticed that @qoops-1 had _Emacs Keymap_, is there any logic in the keymaps that toy with the settings file?

**Comment by joaomoreno** [comment]
There could be. Please reach out to those extensions and check with them.

VS Code won't clear your settings on update.
