### ISSUE TITLE
Incorrect comment string

### ISSUE THREAD

**Issue by towry** [Microsoft/vscode#31087]
- VSCode Version: 1.14.1
- OS Version: 10.12.5

Steps to Reproduce:

1. Open this file in vscode: https://github.com/mozilla-mobile/firefox-ios/blob/master/Telemetry/Events.swift#L3
2. You will find that the whole file is a comment string.

The reason is line 3 has such characters: `//` in the url, and the comment string terminate character `*/`  is at the end of the line.

Reproduces without extensions: Yes

![dfemmgpuaaapm38](https://user-images.githubusercontent.com/8279858/28395461-d973bd5a-6d26-11e7-9b04-69377f44566e.jpg)

**Comment by rebornix** [comment]
This is an issue with Swift grammar.

**Comment by towry** [comment]
You are right, this only happened in swift file.

**Comment by aeschli** [comment]
This is a known but accepted limitation of our comment feature which does not escape anything inside the comment. The user has to do that.
