### ISSUE TITLE
javascript.format.insertSpaceBeforeFunctionParenthesis setting being ignored

### ISSUE THREAD

**Issue by edwinramirez** [Microsoft/vscode#31085]
- VSCode Version: 1.14.1
- OS Version: MacOS Sierra 10.12.5

Steps to Reproduce:

1. Set "javascript.format.insertSpaceBeforeFunctionParenthesis" to false in User settings.
2. Type in any function like `var blabla = function();`
3. VS Code automatically inserts a space before the function parenthesis. 

Reproduces without extensions: Yes.

**Comment by mjbvz** [comment]
Try setting `"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false` instead
