### ISSUE TITLE
Folder Settings could just open workspace settings in no-MRU workspace

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31086]
testing https://github.com/Microsoft/vscode/issues/30722

insiders 1.15.0 9a308d11

in a non-multi-root workspace instance, opening the command palette and choosing "Preferences: Open Folder Settings" results in an info message:

![image](https://user-images.githubusercontent.com/1487073/28394618-3872cc3a-6ca3-11e7-8953-2704b042e3cd.png)

In a multi-root workspace, this opens the settings for the folder.

Is there a reason we don't simply open the workspace settings in the non-MRW scenario?  It would be one less message for the user.

**Comment by sandy081** [comment]
Folder settings are not same as Workspace settings. Opening workspace settings in one case and folder settings in another case will be confusing. It would be same as Opening workspace settings in an empty workspace scenario.
