### ISSUE TITLE
Sorting: Desc Folder or file

### ISSUE THREAD

**Issue by billsteve** [Microsoft/vscode#31089]
- VSCode Version:1.14.1
- OS Version:Win 10

1.The Folder or file is :
   a.x
   b.x
   c.x

2.What i want is:
  c.x
  b.x
  a.x

Sorry, my English is poor
email:billsteve@126.com

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
