### ISSUE TITLE
MRW: Cannot debug any folder except first

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31083]
testing https://github.com/Microsoft/vscode/issues/30722, specifically "debugging (node.js and extension host debugging) work as before".

Insiders 1.15.0 9a308d11

I've created a workspace with all of my extensions and the idea is that I could do a lot of copy/paste between folders and then run/debug any of the individual extensions.  

However, it appears I can only debug the first folder of my multi-root workspace, there is no way for me to pick which one I wish to launch.

On backlog?

**Comment by bpasero** [comment]
Yeah: https://github.com/Microsoft/vscode/issues/29245
