### ISSUE TITLE
Duplicate folders in .code-workspace

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31084]
testing https://github.com/Microsoft/vscode/issues/30722

Insiders 1.15.0
9a308d11

Loading of folders stops if a folder is repeated in the .code-workspace file. admittedly a poorly formed file :) 

loading `foo.code-workspace`

``` json
{
	"id": "1500494428473",
	"folders": [
		"file:///Users/chris/src/vscode-mongodb",
		"file:///Users/chris/src/vscode-docker",
		"file:///Users/chris/src/vscode-docker",
		"file:///Users/chris/src/vscode-azurelogin",
		"file:///Users/chris/src/vscode-azureappservice",
		"file:///Users/chris/src/vscode-extension-samples"
	]
}
```

results in only the vscode-mongodb and vscode-docker folders being loaded.

![image](https://user-images.githubusercontent.com/1487073/28393376-33d3fe40-6c9b-11e7-9404-e146bd7a6942.png)

i would expect it to keep on loading the rest of the folders in this case since the vscode-docker folder is valid, you just don't have to load it 2x.

**Comment by bpasero** [comment]
@sandy081 this should be de-duplicated on the level of the workspace service imho within the workbench.

**Comment by sandy081** [comment]
Hmm strange.. will look into it.
