### ISSUE TITLE
New Workspace - add a folder or write a file?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31080]
Testing https://github.com/Microsoft/vscode/issues/30722

Version:
![image](https://user-images.githubusercontent.com/1487073/28392741-1845e196-6c98-11e7-842b-8d3463eddfab.png)

"Save Workspace" prompts me to save a file on disk, "Open Workspace" prompts me for a file on disk, but "New Workspace" prompts me to open a folder(s). 

I would expect the same file prompt behavior for New Workspace, where I give the workspace a name and location on disk, VS Code is reloaded, and then I Add Folder to Workspace to begin to populate it.

**Comment by bpasero** [comment]
We decided to remove the "New Workspace" action entirely.
