### ISSUE TITLE
在Vue中不用使用html代码快速补全

### ISSUE THREAD

**Issue by sweetheartly** [Microsoft/vscode#31092]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
wrap|dt|0.0.1
html-tag-wrapper|hwe|0.1.7
vetur|oct|0.9.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by HaitianLiu** [comment]
可以在setting.json里设置和emmet相关的配置吧。
建议用英文啊，问题有价值的话可以给更多的人帮助。😊

**Comment by isidorn** [comment]
Can you please file this issue in english and with reproducable steps.
We do not speak chinese.

**Comment by rebornix** [comment]
Please file issues against Vetur.
