### ISSUE TITLE
Compiling and running c/C++ code 

### ISSUE THREAD

**Issue by NejiHyuuga** [Microsoft/vscode#31095]
I am new to vs code and have been working quite comfortably before the july update.
I tried a very basic Hello World Example and configured my Task.json and launch.json file.
I am able to build my code successfully but i am not able to view my output.
In my debug console, I see few warning messages too. I could not get that.
Help me resolve this issue.

- VSCode Version:1.14.1
- OS Version: Windows 7

Steps to Reproduce:

1. Build tasks.json by Ctrl+Shift+B
2. Run the code by F5.

[C.zip](https://github.com/Microsoft/vscode/files/1161150/C.zip)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please file this agains the C++ extension here https://github.com/Microsoft/vscode-cpptools
