### ISSUE TITLE
Could not install typing files for JavaScript language features

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vscode#31094]
- VSCode Version: 1.14.1 64bit
- OS Version: Windows 7
- npm Version: 5.0.3

Steps to Reproduce: (I don't know the exact repro step, this does not repro on my Windows 10 machines)

1. Open any .js file (The following short file in my case)
   ```
   module.exports = __dirname;
   ```
2. VSCode says *Could not install typings files for JavaScript language features. Please ensure that NPM is installed or configure 'typescript.npm' in your user settings*
3. Set `typescript.npm` to `C:\\Program Files\\nodejs\\npm.cmd` or `C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm.cmd` but both don't help

Reproduces without extensions: Yes

**Comment by carlosvigil** [comment]
- VSCode Version: 1.14.2 (1.14.2)
- OS Version: macOS 10.12.6 (16G29) 
- npm Version: 5.3

set to `where` `/usr/local/bin/npm`
and actual `/usr/local/lib/node_modules/npm/bin/npm`

**Comment by mjbvz** [comment]
Hey sorry I overlooked this issue. If you are still seeing this in VScode 1.16, please try collecting the typings installer logs:

1. Set `"typescript.tsserver.log": "normal"`
1. Restart VSCode and reproduce the issue
1. Run the `TypeScript: Open TSServer log`  command in vscode
1. Look in the `ti-xxx.log` file in there

Near the top of this file there should be an error message about why typings install failed. See https://github.com/Microsoft/TypeScript/issues/18344 for example

**Comment by larsch** [comment]
```
larsch@t420arch ~ % npm -v
5.4.2

larsch@t420arch ~ % node -v
v8.6.0
```

tsserver.log:
```
...
Info 32   [18:47:23.507] Sending request: {"projectName":"/dev/null/inferredProject1*","fileNames":["/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/lib.es6.d.ts","/home/larsch/src/pixel/pixel.js"],"compilerOptions":{"module":1,"target":2,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"allowJs":true,"jsx":1,"checkJs":false,"noEmitForJsFiles":true,"maxNodeModuleJsDepth":2},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":["buffer","crypto","events","fs","http","net","path","process","querystring","stream","tty","url","util","zlib"],"projectRootPath":"","kind":"discover"}
Info 33   [18:47:23.515] Received response: {"kind":"event::initializationFailed","message":"Command failed: npm install --ignore-scripts types-registry"}
Info 34   [18:47:23.515] event: {"seq":0,"type":"event","event":"typesInstallerInitializationFailed","body":{"message":"Command failed: npm install --ignore-scripts types-registry"}}
...
```

Output of `npm install`:

```
larsch@t420arch ~/src/pixel (git)-[master] % npm install --ignore-scripts types-registry                                                                                 :(
npm WARN pixel@1.0.0 No description
npm WARN pixel@1.0.0 No repository field.

npm ERR! path /home/larsch/src/pixel/node_modules/.staging/types-registry-9f09bb8c/node_modules
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall lstat
npm ERR! ENOTDIR: not a directory, lstat '/home/larsch/src/pixel/node_modules/.staging/types-registry-9f09bb8c/node_modules'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/larsch/.npm/_logs/2017-10-05T16_55_56_658Z-debug.log
```
