### ISSUE TITLE
[Feature Request] "Special Exit" Feature That Remembers the Screen Orientations and Opened Folders

### ISSUE THREAD

**Issue by MehmetKaplan** [Microsoft/vscode#31097]
While using vscode for complex projects, the developers usually use more than 1 window. And usually they place those windows to certain desktops (in Mac) or workspaces (in Ubuntu).

On the other hand, the nature of development requires relatively frequent restarts of physical or virtual machines.

And each restart is actually a pain since you always need to re-open all your windows and project folders one by one. And of course you need to place them to the related desktop or workspace screens.

In order to reduce that pain I suggest, if possible, a "special exit" feature so that;

1. it saves all open windows' desktop or workspace screens and their opened folders while exiting
2. and using that saved information when the vscode is opened next time, it automatically opens and orients the windows (with their opened folders) to the places that they were closed from.

**Comment by bpasero** [comment]
Configure: `"window.restoreWindows": "all"`

**Comment by MehmetKaplan** [comment]
It is not the exact behavior that I suggested.

> 1. **it saves all open windows' desktop or workspace screens** and their opened folders while exiting
> 2. and using that saved information when the vscode is opened next time, it automatically opens and **orients the windows** (with their opened folders) **to the places that they were closed from**.

To be more specific, assume you use 2x2 4 screens. And assume you have got 2 vscode windows in second and third screens. What I suggest is, when reopening the vscode, the windows are oriented to their respective screens, i.e. 2nd and 3rd screens in my example.
