### ISSUE TITLE
The brace-expansion dependency in v1.14 contains a vulnerability

### ISSUE THREAD

**Issue by LonnyGomes** [Microsoft/vscode#31096]
The 1.14 release of Visual Studio Code ships with [version 1.1.6 of the brace-expansion dependency](https://github.com/Microsoft/vscode/blob/master/npm-shrinkwrap.json#L55) which contains a [Regular Expression Denial of Service attack](https://nodesecurity.io/advisories/338) according to the node security platform. 

The solution is to upgrade `brace-expansion` to v1.1.7 or above. Since this update is a patch version, no code changes would be required as the patched version will be pulled in when VSCode gets repackaged.

- VSCode Version: *v1.14*
- OS Version: macOS Sierra *(v10.12.5)*

Steps to Reproduce:

1. clone version v.1.14 of vscode
2. install the node security platform cli: `npm install -g nsp`
3. run a security check on the module dependencies: `nsp check --output summary`

*Three vulnerabilities should be returned:*
```
Name              Installed   Patched   Path                                                                                                                                                               More Info
 brace-expansion   1.1.6       >=1.1.7   ... > chokidar@1.6.0 > ... > brace-expansion@1.1.6
 brace-expansion   1.1.6       >=1.1.7   ... > nsfw@1.0.16 > ... > brace-expansion@1.1.6
 brace-expansion   1.1.6       >=1.1.7   ... > v8-profiler@5.6.5 > ... > brace-expansion@1.1.6 
```

To confirm that the suggest fix will work, perform the following steps:

1. `rm npm-shrinkwrap.json`
2. `./scripts/npm.sh install`
3. `nsp check --output summary`

*The latest version of `brace-expansion` (currently v1.1.8) should be defined in the generated `package-lock.json` file.*

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Assigning people due to `chokidar`, `nsfw` and `v8-profiler`.

**Comment by Tyriar** [comment]
nsfw has 1.1.8 already https://github.com/Microsoft/vscode/blob/d185c3190c3c2601c2e11030b169e8e593271897/npm-shrinkwrap.json#L479

**Comment by Tyriar** [comment]
The latest version of chokidar depends on 1.1.7 (rimraf > glob > minimatch) and 1.1.8 (readdirp > minimatch).

**Comment by jrieken** [comment]
Updated v8-profiler, event tho it uses this just as devDependency which we shouldnt be shipping...

**Comment by Tyriar** [comment]
I think we can close this now. I pulled out dependencies and devDependencies into a new npm package.json and did an install and only brace-expansion@1.1.8 was installed to verify.
