### ISSUE TITLE
Word Wrap not Working

### ISSUE THREAD

**Issue by Randize** [Microsoft/vscode#31098]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
python|don|0.6.7
ftp-simple|hum|0.5.4
csharpfixformat|Leo|0.0.30
prettify-json|moh|0.0.3
csharp|ms-|1.11.0
python|tht|0.2.3
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Toggling word wrap via View > Toggle Word Wrap doesn't work
2. ALT + Z doesn't work either

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
It has been fixed and you are supposed to see it after today's Stable update.
