### ISSUE TITLE
target not support ES7 in jsconfig.json file

### ISSUE THREAD

**Issue by welefen** [Microsoft/vscode#311]
target not support ES7 in jsconfig.json file

**Comment by scottaddie** [comment]
@welefen Not sure if you noticed or not, but there is experimental support for ES7 decorators. In your jsconfig.json file, use the `experimentalDecorators` option:

```json
{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs",
		"experimentalDecorators": true
	}
}
```

That seems to be all the ES7 support you get at this time.

**Comment by felixfbecker** [comment]
What about `async`/`await`?! See #408

**Comment by warpdesign** [comment]
+1
Would love support for ES7 too.

Maybe it has changed since last year and there are new ES7-related options available ?

For example new function bind `::` operator would be great.

**Comment by jrieken** [comment]
moving this to TypeScript from which VS Code gets TS and JS smartness

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#8495
