### ISSUE TITLE
Getting issues with React Development?

### ISSUE THREAD

**Issue by neevan1e** [Microsoft/vscode#31101]
I am facing issues in react development like not getting intelligence, unable to format code (shift+alt+f). So can anyone tell me what all extension should I use for the react, I have searched in extension manager but there are so many, don't know what to use.

**Comment by inter8ection** [comment]
The lastest VSCode release does appear to have caused issues with React Native development
https://github.com/Microsoft/vscode/issues/30995

**Comment by mjbvz** [comment]
Please try VScode 1.14.2 which was just released. It includes TS 2.4.2 which fixes a number of issues that could be causing this

**Comment by inter8ection** [comment]
Yep looks fixed after a restart, thanks for quick turn around and heads up.

**Comment by neevan1e** [comment]
Thanks yeah looks good
