### ISSUE TITLE
Search: searching in a folder includes results from opened editors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#31100]
Steps to Reproduce:

1. right click on a folder to search in
2. get some results from that folder
3. open files outside of that folder that also happen to have the results matching
4. search again

=> results from the opened file appear even though you have a include pattern that specifies a particular folder

**Comment by BruceGitHub** [comment]
Are at the beginning. I look at code first if I can try to contribute

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/29658
