### ISSUE TITLE
Autorevealing only works for primary folder

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31104]
I've set explorer.autoReveal to true, but it only works for the master/primary folder.

![autoreveal](https://user-images.githubusercontent.com/172399/28405719-efe34dce-6d2d-11e7-82d5-a33d9a5f9dcf.gif)

Notice, that label.ts is not reveals inside the vscode folder.

**Comment by isidorn** [comment]
I can not reproduce this, notice that I tried with the same vscode repo / labels file
I tried both on os x and win.
@egamma do you still see this with latest insiders? Can you constantly repro?

![reveal](https://user-images.githubusercontent.com/1926584/28409404-d98fa8b2-6d3a-11e7-9fb2-cea6be78bd60.gif)

**Comment by egamma** [comment]
This happens when the resource is opened from a search result. The path of the search result resource is incorrect.  Filed a separate issue on this, closing.
