### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by himrathana** [Microsoft/vscode#31102]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
@himrathana sorry as there is no info in both title and description, I'll close it first and reopen when more info are put here.
