### ISSUE TITLE
User custom shortcut with user snippet (different by extension)

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#31109]
Hi,

I usually like auto insert file header by file extension in sublime (with a plugin).
Since there is no a function full file-header extension in vscode market. And ide developer doesn't tend to add this feature (I am not asking for it) ,  I choose to use snippet instead.

But I find that, it is still not convenient to insert a snippet with out shortcut,
It would be nice to have a "shortcut" attribute for each snippet, like
```
python.json
{
    "header": {
        "prefix": "header",
        "body": [
            "# -*- coding: utf-8 -*-",
            "# @Author: mithril",
            "",
            "from __future__ import unicode_literals, print_function, absolute_import",
            ""
        ],
        "description": "python file header",
        "shortcut": "ctrl+alt+h"
    }
}
```

Once vscode detect current file extension is `.py` , then it allow to use this snippet. In this way, I can create different headers for different language with same shortcut.

**Comment by jrieken** [comment]
You can do that, see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets. 

I haven't test it but it should be like this (in `keybindings.json`):

```json
{
  "key": "cmd+k 1",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": { "langId": "python", "name": "header" }
}
```
