### ISSUE TITLE
Provide git extension interface API

### ISSUE THREAD

**Issue by ole1986** [Microsoft/vscode#31103]
While I was trying to use parts of the git extension I noted there is no "exports" variable available when using the following snippet:

```
let gitExt = vscode.extensions.getExtension('vscode.git');
console.log(gitExt.exports);
```

Wouldn't  it be good to have such exports available for other extension developers the way it is described [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_extensions)

Kind of an API for important git commands, like checkout, branch, commit.

**Comment by stianhoiland** [comment]
How's this coming along?

**Comment by batjko** [comment]
Another checkup.
I've just run into having to find a project's git remote from my extension, and this would really be useful!.

Instead, for now, I'll copy/paste the code from the extension to re-implement it for my purposes 😒: https://github.com/Microsoft/vscode/blob/b161ce4305a101a54c3088040fa2dc544755e2d5/extensions/git/src/git.ts

**Comment by joaomoreno** [comment]
This is now in.

**Comment by joaomoreno** [comment]
Verifier: check out https://github.com/Microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts
