### ISSUE TITLE
tsserver.js high cpu usage

### ISSUE THREAD

**Issue by teterovic** [Microsoft/vscode#31105]
- VSCode Version: Version 1.14.1 (1.14.1)
- OS Version: MacOs 10.12.5 (16F73)

Steps to Reproduce:

1. Open an angular 2 project
2. Open a TS file(other files are fine) and type any content (space is enough)
3. The CPU in monitor goes to 100+%
![image](https://user-images.githubusercontent.com/7413906/28406031-1b50b590-6d2f-11e7-847e-7c2bec670e5a.png)

Reproduces without extensions: **Yes**

me and my coworker have the same issue. As soon as we type a single space in a .ts file the Code Helper goes crazy.
First my coworker had the issue, after a week i got the same problem (not sure if because of VS Code update or our code)

`8664 100.0 9.3 4769000 1559904 ?? R 10:36PM 0:58.20 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/3c/czwwfy150ns0kb3tcw5kcntm0000gn/T/vscode-tscancellation-abc31803ac049e820ccd.sock*`

```
97.9 18584 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/teterovic/.vscode/extensions/Angular.ng-template-0.1.4/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/teterovic/.vscode/extensions/Angular.ng-template-0.1.4/server/server.js --node-ipc
i will get some debug info tomorrow. Tested with the latest versions(also inside) without extensions
```

Even more, TS output  log
`
[Info  - 9:32:53 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:32:53 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Info  - 9:33:48 AM] TSServer exited
[Error  - 9:33:48 AM] 'getSupportedCodeFixes' request failed with error.
Error: Service died.
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:650:32)
    at ChildProcess.childProcess.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:454:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 9:33:48 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:33:48 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Info  - 9:34:19 AM] TSServer exited
[Info  - 9:34:19 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:34:19 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Error  - 9:34:20 AM] 'format' request failed with error.
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:75710:23)
    at IOSession.Session.getFileAndProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80056:42)
    at IOSession.Session.getFileAndProjectWithoutRefreshingInferredProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80050:29)
    at IOSession.Session.getFormattingEditsForRange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80122:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79331:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80657:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80648:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80657:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80677:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81864:27)
[Info  - 9:35:05 AM] TSServer exited
[Error  - 9:35:05 AM] 'format' request failed with error.
Error: Service died.
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:650:32)
    at ChildProcess.childProcess.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:454:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 9:35:05 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:35:05 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Info  - 9:39:19 AM] TSServer exited
[Error  - 9:39:19 AM] 'configure' request failed with error.
Error: Service died.
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:650:32)
    at ChildProcess.childProcess.on (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:454:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 9:39:19 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:39:19 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Info  - 9:40:07 AM] TSServer exited
[Info  - 9:40:07 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:40:07 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[Info  - 9:41:12 AM] TSServer exited
[Info  - 9:41:12 AM] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 9:41:12 AM] Forking TSServer
PATH: /Applications/oracle/product/instantclient_64/11.2.0.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Firefox.app/Contents/MacOS/:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

`

**Comment by teterovic** [comment]
`Info 0    Binding...
Info 1    request: {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode"}}
Info 2    Host information vscode
Info 3    response: {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 4    0::configure: async elapsed time (in milliseconds) 1.5084
Info 5    request: {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"CommonJS","target":"ES6","allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"allowJs":true,"jsx":"Preserve","checkJs":false}}}
Perf 6    1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.8036
Info 7    response: {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 8    request: {"seq":2,"type":"request","command":"open","arguments":{"file":"/Users/teterovic/dev/ability2/src/client/app/collection/chapter-tree/chapter-tree-search/chapter-tree-search.component.ts","fileContent":"import { Component, OnInit, Input, Output, EventEmitter, OnDestroy, ViewChild, ElementRef } from '@angular/core';\nimport { BehaviorSubject } from 'rxjs/Rx';\nimport { FilterStrat$
Info 9    Search path: /Users/teterovic/dev/ability2/src/client/app/collection/chapter-tree/chapter-tree-search
Info 10   Config file name: /Users/teterovic/dev/ability2/src/client/tsconfig.json
Info 11   Loading  from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules)
Info 12   Failed to load module: {}
Info 13   Loading  from  (resolved to /Users/teterovic/dev/ability2/node_modules)
Info 14   Failed to load module: {}
Info 15   Couldn't find  anywhere in paths: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..,
`

**Comment by teterovic** [comment]
Can i turn off tsserver somehow it's kind of a blocker?

**Comment by teterovic** [comment]
Ok i deleted the:
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js

file so its not going 100% anymore still doesnt work

**Comment by teterovic** [comment]
I realised that it's project specific. Some code inside the project makes tsserver go crazy. Don't have the issue in another project just this one

**Comment by enkol** [comment]
I've similar issues. The Code.exe process for tsserver.js or a sub process with typingsinstaller.js eat a lot of cpu time. I think they scan my ember-cli projects tmp folder, despite it being on files.exclude and files.watcherExclude

VSCode 1.14.2 
Windows 10 10.0.14393

**Comment by teterovic** [comment]
It works on windows, so only a macos problem. @mjbvz i can give you a remote connection to check the error if needed

**Comment by teterovic** [comment]
I found the issue, it was the 
`"allowJS":"true"`

property in tsconfig. A colleague of my put it in both tsconfig.ts files in mgechev angular seed and it caused two code helper tasks to go up to 130% in activity monitor and stayed like that even after closing VSCode. I think I tested it under Windows 10 it worked, but the problem was only under MacOS but i would have to retest this

**Comment by mjbvz** [comment]
Hey sorry this fell off my radar.

Please let me know if you see this in VS Code 1.18. You may also want to configure `includes` in your `jsconfig`/`tsconfig` (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) to make sure that only the files you are working with are being included in the javascript project
