### ISSUE TITLE
Smoke test: Synchronous require cannot resolve module 'electron'

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31106]
Sometimes Spectron cannot hook into Electron with the following message (_TFS build ID 30801_):

> Check dependency list! Synchronous require cannot resolve module 'electron'. This is the first mention of this module!

As a fix I have tried exposing Electron require to Spectron as per [Node Integration documentation](https://github.com/electron/spectron#node-integration) in 47794539771b5e755fe1886466af6ea0b64eece3, however it did not work. Moreover, we do not access the core Electron APIs in our tests.

This is not happening on consistent basis, therefore no idea how to reproduce.

@joaomoreno I might need your help on this.

**Comment by michelkaporin** [comment]
Seems like #29731 appears subsequently after this issue happens (see TFS build ID 30787 ran after 30777).

**Comment by Sweetman** [comment]
@michelkaporin @bpasero is this still an issue y'all run into or has a fix been found for this? Started seeing this in our integration tests for the Salesforce DX Extension for VSCode inconsistently as well.

https://travis-ci.org/forcedotcom/salesforcedx-vscode/jobs/269377544 - line 1234

**Comment by joaomoreno** [comment]
Not an issue any more.

**Comment by michelkaporin** [comment]
@joaomoreno what was the fix for it, if not a secret ㊙️ ?

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/commit/30e81176abe4f501d40906d3fbf3c53ee10edc0e

🎆
