### ISSUE TITLE
Searching in all files with regexp with `\n` not working as expected

### ISSUE THREAD

**Issue by hasumashi** [Microsoft/vscode#31117]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Ubuntu 17.04 (Linux x64 4.10.0-28-generic)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-docker|Pet|0.0.16
html-css-class-completion|Zig|1.7.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.6.7
vscode-npm-script|eg2|0.2.0
Angular1|joh|0.2.0
block-travel|sas|0.0.2

(3 theme extensions excluded)

This bug exists with and without extensions enabled, however to avoid anything unexpected I am running VSCode with `$ code --disable-extensions`.

---

Steps to Reproduce:

1. Let's assume we have opened repo directory in Explorer with some directories inside:
```
/repo
   |- /node
   |   |- /routes
   |   |   |- firstApi.js
   |   |   |- secondApi.js
   |   |   |- thirdApi.js
   |- public
```   
2. In each *Api.js file we have line:
`var m = require('../views/messages.json');`
or
`var m = require('../views/messages');`

3. I want to remove these lines, so I am right clicking _node_ directory an choosing __Find in Folder__ and trying to match regexp `.*messages.*\n?`

4. VSCode writes: `No results found in './node' - Search again in all files` and `No results found. Review your settings for configured exclusions - Open Settings` when clicking __Search again in all files__.
I also tried to set __files to include__ option to `./node/**/*.js` but it still doesn't find anything.

5. This is wrong because I can match this regexp in each file respectively by:
  * opening these files double-clicking it in Explorer (e.g. first and second Api.js files)
  * hitting *Ctrl+F* and typing the same regexp `.*messages.*\n?`

6. With _firstApi.js_ and _secondApi.js_ still opened (but _thirdApi.js_ closed) I am repeating step 3 and now it still doesn't find anything but when clicking _Search again in all files_ or searching in `./node/**/*.js` it matches proper lines only in opened files (if we close second and open third Api.js file result will be only in these files then).

7. Things are different when **I remove `\n?` from regexp** as follows: `.*messages.*`
With this changed regexp I get results in every file (with _files to include_ set to `**/*.js` or blank, with any files opened or everything closed).

The `\n?` part is important for me because I don't want to leave empty line.

**Comment by roblourens** [comment]
Open files are searched using the editor which supports multiline matching, but other files are searched using a different search tool that doesn't support it. So to match the newline you'll have to search in the editor or search open files, unfortunately.

**Comment by hasumashi** [comment]
I see, but is there any possibility it will be improved in the future? I mean it's rather unexpected behaviour that when searching through many files some of them are being searched by slightly different tool which doesn't support multiline matching. For me that feature would be very useful.

**Comment by roblourens** [comment]
Possibly in the future but not the near future. I agree that the difference is confusing. https://github.com/BurntSushi/ripgrep/issues/176
