### ISSUE TITLE
Identation Problem in Workspace Menu Items of Menu "File" (Spanish translation)

### ISSUE THREAD

**Issue by CarlosAzocar** [Microsoft/vscode#31116]
Identation Problem in Workspace Menu Item of Menu "File" (Spanish translation)

![issue](https://user-images.githubusercontent.com/18235355/28411454-c750e17e-6d0e-11e7-9df7-02de976b3115.png)

- VSCode Version:  1.15.0-insider  (f5c4b7a, 2017-07-20T08:30:48.273Z)
- OS Version: Windows 10 x64

Reproduces without extensions: Yes/No

**Comment by michelkaporin** [comment]
@danyeh please fix it in Transifex. There is unnecessary whitespace after double ampersand https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/vs_code/115488521

**Comment by danyeh** [comment]
It repro in v1.18 but the translation doesn't exist in Transifex.
Source string: ["Open Workspace ..."](https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/115544511?q=Open Workspace...)
Source string: "[Add Folder to Workspace...](https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/115544495?q=Add Folder to Workspace...)"
@dbaeumer , any hint? The resource file became static file or we have issue to update the file?

**Comment by dbaeumer** [comment]
Looks ok for me in the latest insider.
![capture](https://user-images.githubusercontent.com/1931590/33548157-92c16a5c-d8e6-11e7-97f8-aca7e8ebc98c.png)

**Comment by danyeh** [comment]
Verified again on 1.20.0. No longer repro. Close now.
Versión: 1.20.0-insider
Confirmación: c0278341edcb6d831d24b5da3e854c6189829b12
Fecha: 2018-01-16T05:14:43.522Z
Shell: 1.7.9
Representador: 58.0.3029.110
Nodo 7.9.0
Arquitectura x64
