### ISSUE TITLE
Assertion failed: object->InternalFieldCount() > 0

### ISSUE THREAD

**Issue by MaxOlsson** [Microsoft/vscode#3111]
When debugging a NodeJS Express.js POST method using Postman (The Chrome app) with babeljs transpiled code this error is thrown:
`Assertion failed: object->InternalFieldCount() > 0, file d:\jenkins\workspace\nodejs-msi-julien\d8c2e2bb\src\util-inl.h, line 117`

* This bug is reproducable over different POST url's.
* Developer Tools doesn't say anything.
I'm not allowed to share code but if absolutely necessary I might try and create an isolated use case where it's reproducable...

How to reproduce:
* Create a NodeJS Express.js server with ES6 syntax and create a POST REST method, and transpile it using npm-babel (https://www.npmjs.com/package/babel).
* Place a breakpoint at the first entry point in your POST function
* Using Postman, send a POST request and wait
* It should first stop at the breakpoint and shortly after throw the error and exit the debugger.

**Comment by weinand** [comment]
@MaxOlsson what node version are you using?

**Comment by weinand** [comment]
Most likely this is a node issue: https://github.com/nodejs/node-v0.x-archive/issues/9028

**Comment by MaxOlsson** [comment]
Sorry for not posting my node version. It's an old one, `v0.12.7`. I'll update my node version to latest stable and if I can't reproduce this bug I'll close this issue.

**Comment by MaxOlsson** [comment]
Sorry for the late reply! I can't reproduce this with Node version 4.4. Closing the bug.

**Comment by hagechad** [comment]
I am able to reproduce this problem with a breakpoint on a request callback handler. I am using version 
1.9.1 on Windows 10 with a date stamp of 2017-02-09T00:26:45:394Z
Commit: f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Shell 1.4.6 and Node 6.5.0
