### ISSUE TITLE
Intellisense stops working and just loading.. and extensions terminatly interupt

### ISSUE THREAD

**Issue by mrbigwolf67** [Microsoft/vscode#31110]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.7
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
tslint|eg2|0.16.0
Angular2|joh|2.4.0
debugger-for-chrome|msj|3.1.6
angular2-inline|nat|0.0.17
vscode-css-peek|pra|1.3.1
html-css-class-completion|Zig|1.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide reproducable steps.
Can you also reproduce this issue if you disable all extensions?

**Comment by mrbigwolf67** [comment]
Hi. Found problem. I uninstall an extension Angular 2 fr.o.m. John papa. Fixed the problem.
Regards Uffe
Skickat från min iPhone



Skickat från min iPhone
20 juli 2017 kl. 15:45 skrev Isidor Nikolic <notifications@github.com<mailto:notifications@github.com>>:


Please provide reproducable steps.
Can you also reproduce this issue if you disable all extensions?
