### ISSUE TITLE
Feature Request : Bookmark Line

### ISSUE THREAD

**Issue by satriowibowo123** [Microsoft/vscode#31118]
I want you adding bookmark line feature. for easy to jump over from line to another bookmarked line. thanks.

**Comment by fashoom** [comment]
This is my number one feature request. Please implement as a colored horizontal line, the full width of the line, not just a marker next to the line number. VSCode is the only code editor I'm aware of that doesn't have this feature.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by fashoom** [comment]
That's OK, I've stopped using your awful IDE.
