### ISSUE TITLE
Code Formate Like Visual Studio 2017

### ISSUE THREAD

**Issue by MarkSky** [Microsoft/vscode#31119]
- VSCode Version:1.14.1
- OS Version:Windows 10

Steps to Reproduce:
I have used many beautify code extension from the markertplace.
But I still think the beautify code in Visual Studio 2017 is better.
Could you let Visual Studio Code have the same beautify code function as Visual Studio 2017?

Reproduces without extensions: No

**Comment by aeschli** [comment]
Which programming language do you refer to?

**Comment by MarkSky** [comment]
HTML、SCSS、CSS、JavaScript(include .jx and .jsx of React JS).

**Comment by King66** [comment]
https://github.com/Microsoft/vscode/issues/31190

want format like VS too...

**Comment by aeschli** [comment]
All our formatters use different implementations. Using the same implementation as VS is not possible. So please file specific improvement requests against the each formatter.
