### ISSUE TITLE
support needed for xsd based intellisence in xml files

### ISSUE THREAD

**Issue by sonymoparthi** [Microsoft/vscode#31126]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against an xml extension.

**Comment by sonymoparthi** [comment]
support needed for xsd based intelligence for xml files in VSCODE.
or
please provide me the link to xml extension to file this
