### ISSUE TITLE
Feature request: Add ability to remove a keyboard shortcut using GUI

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#31122]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|0.6.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
python|don|0.6.7
EditorConfig|Edi|0.9.4
matlab|Gim|0.5.0
triggertaskonsave|Gru|0.1.2
vscode-dimmer|hoo|2.1.0
docthis|joe|0.4.7
select-part-of-word|mle|1.0.1
cpptools|ms-|0.12.1
indent-rainbow|ode|0.6.1
vscode-clearcase|Ope|1.10.0
vscode-icons|rob|7.10.1
indenticator|Sir|0.4.2
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.0
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open Keyboard Shortcuts GUI
2. Disable/remove keyboard shortcut binding. Have to open the keybindings.json. Would be much easier if it could be disabled in the GUI.

Reproduces without extensions: N/A

**Comment by bpasero** [comment]
@BillDenton Right Click > Remove Keybinding?

![image](https://user-images.githubusercontent.com/900690/28427238-d5d05768-6d75-11e7-83da-6a4f526244ad.png)

**Comment by BillDenton** [comment]
Oh, didn't see that, I was just trying to use the edit icon 
![image](https://user-images.githubusercontent.com/17859340/28427621-b468eaa6-6d6e-11e7-931f-2f28d5d02483.png)
