### ISSUE TITLE
Severe performance issue when debugging our unit tests

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#31123]
- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. add a breakpoint into `workspacesMainService.test.ts#211`
2. change our unit test launch config:

```json
"args": [
  "/Users/bpasero/Development/monaco",
  "--timeout",
  "2000",
  "-g",
  "getUntitledWorkspaceSync"
]
```
3. hit F5

=> everything freezes
=> this reproduces for me without settings

**Comment by bpasero** [comment]
[CPU-20170720T125151.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1162022/CPU-20170720T125151.cpuprofile.txt)

Some tree refresh issue?

![image](https://user-images.githubusercontent.com/900690/28414087-4d5de4c0-6d4a-11e7-965e-5d809e0ae6d6.png)

**Comment by weinand** [comment]
@bpasero the latest workspacesMainService.test.ts has no line 211?
"/Users/bpasero/Development/monaco" is your vscode project?

**Comment by bpasero** [comment]
@weinand now it does. I can reproduce when opening just vscode as folder.

**Comment by weinand** [comment]
5000 refresh events seem to overwhelm VS Code...

**Comment by weinand** [comment]
I'm now throttling refresh events.

**Comment by jrieken** [comment]
@sandy081 re https://github.com/Microsoft/vscode/issues/31123#issuecomment-316706485 We should make sure to throttle update events for *all* extensions and protected with that from overeager extensions. It seems any extension can freeze us with that trick.
