### ISSUE TITLE
Snippet variable text isn't whitespace normalised

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31124]
* have a snippet like this `<div>\n\t$TM_SELECTED_TEXT\n</div>$0`
* select indented text on two lines
* insert that snippet
* :bug: the second line of the selection isn't correctly indented. 

This is because we normalise whitespace *before* parsing and snippet resolving: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippetSession.ts#L291

![jul-20-2017 12-47-31](https://user-images.githubusercontent.com/1794099/28413922-9fc04dee-6d49-11e7-9a66-6124087d14f6.gif)

**Comment by jrieken** [comment]
fyi @ramya-rao-a You ran into this

**Comment by ramya-rao-a** [comment]
Works when selected text is single line or is multi line with 1 level indentation.

In the below case, you have multiple lines with multiple indentations.

![snippet](https://user-images.githubusercontent.com/16890566/28447638-dec37538-6d86-11e7-893d-41b1fe72dfb6.gif)

**Comment by jrieken** [comment]
@ramya-rao-a Stop filling "bugs" using nothing more than animated gif. Such a waste of time, just copy&paste the code and snippet in question

**Comment by ramya-rao-a** [comment]
**Code in question:**

Exactly what you used when you filed this "bug". Just add another indent in the beginning of the selected text.

Unless you meant the code behind? In which case, I'll take a look at snippetSession.ts and get back.

**Snippet in question:**

The same that you used.

**Comment by jrieken** [comment]
> Exactly what you used when you filed this "bug". Just add another indent in the beginning of the selected text.

So how hard is it to copy&paste? You have just tried it, I trust you when you say it doesn't work with *that* sample. Why make me interpret a movie that doesn't show tab vs spaces, is very hard to get the exact selection from, takes you more time to create and attach etc etc.

**Comment by ramya-rao-a** [comment]
good point. lesson learnt.

**Comment by jrieken** [comment]
Sorry, slipping to August. This is complicated...

**Comment by jrieken** [comment]
I might have gotten smarter over night

**Comment by ramya-rao-a** [comment]
thanks! I tested this with a variety of different cases and am loving it.

I was able to remove a lot of indent and newline handling I had put in place for `Emmet: Wrap with abbreviation` feature to work well with multi cursors.

With this fix, I can remove all of it.

Thanks again!

**Comment by isidorn** [comment]
Adding verified tag since ramya clearly verified it from the comment above

**Comment by roblourens** [comment]
I can repro something like this, but I'm not sure if it's this issue or an emmet specific thing @ramya-rao-a?

Before:
```html
<html>
	<div>
        <div></div>
        <div></div>
    </div>
</html>
```

- Select the inner 2 divs
- Emmet: wrap with abbreviation, `p`

After:
```html
<html>
	<div>
        <p>
			<div></div>
			        <div></div>
		</p>
    </div>
</html>
```

**Comment by ramya-rao-a** [comment]
@roblourens I don't see it..

![wrap](https://user-images.githubusercontent.com/16890566/28999928-a210b386-7a0f-11e7-9034-6ba4f9ee25b6.gif)

**Comment by roblourens** [comment]
Today I don't see it either.
