### ISSUE TITLE
VSCode cannot open files/folders in OneDrive after enabling Files On-Demand

### ISSUE THREAD

**Issue by ismet** [Microsoft/vscode#31127]
- VSCode Version: Code - Insiders 1.15.0-insider (f5c4b7abd3188b51883a6a4ab30d73d2ade2af63, 2017-07-20T08:30:39.430Z)
- OS Version: Windows_NT ia32 10.0.16241
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-npm-script|eg2|0.2.0
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
rest-client|hum|0.14.6
vs-deploy|mkl|9.27.0
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
vetur|oct|0.9.1
vuehelper|oys|0.1.0
vscode-icons|rob|7.10.1

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Enable "Files On-Demand" feature in OneDrive
2. In VSCode, try to open Files/Folders which are located in OneDrive folders
3. You get an error "Path does not exist : The path does not seem to exist anymore on disk".  If you try to open files/folders in Windows Explorer, everything looks ok.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#27285
