### ISSUE TITLE
SaveAs takes up whole screen

### ISSUE THREAD

**Issue by DAD713** [Microsoft/vscode#31134]
When I try to do a SaveAs the dialog takes up the whole screen and I can't move it.

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
python|don|0.6.7
xml|Dot|1.9.2
vscode-sql-connect|dvd|0.2.1
tslint|eg2|0.16.0
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
vscode-tfs|iva|0.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
VBScript|lug|0.0.2
ftp-sync|luk|0.3.3
MagicPython|mag|1.0.10
mssql|ms-|1.1.0
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
team|ms-|1.121.1
debugger-for-chrome|msj|3.1.6
new-cmd|odo|0.2.0
vscode-icons|rob|7.10.1
yo|sam|0.9.3
Spell|sea|1.0.0
vscode-sql-beautify|sen|0.0.4
vscode-hexdump|sle|1.4.0
guides|spy|0.8.4
code-spell-checker|str|1.3.0
python|tht|0.2.3
asp|tro|0.0.1
python-extended-snippets|tus|0.0.1
iis-express|war|1.0.0
jira|web|0.1.0
change-case|wma|1.0.0
jira-search|xce|0.1.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by DAD713** [comment]
Open File and Open Folder do the same thing in v1.15.0
They take the full screen and are unmovable and non-resizable.

**Comment by bpasero** [comment]
The OS decides how to show this dialog, not under our control.
