### ISSUE TITLE
I can't do vsce package on my mac but on the pc (It has to do with the EventEmitter)

### ISSUE THREAD

**Issue by buzzfrog** [Microsoft/vscode#3113]
Hi
Here is the output:
(~/git/vscode-imagepreview): vsce package
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: /bin/sh -c node ./node_modules/vscode/bin/compile

This is the repository I try to package: https://github.com/buzzfrog/vscode-imagepreview

/dag

**Comment by egamma** [comment]
Is this still an issue I see your package in the gallery?

**Comment by buzzfrog** [comment]
Yes,
I started this morning trying to use my mac to publish, but after a couple of hours I switched to PC and published from that machine.

By the way, I tried your example, Erich, also. The one with CSS preview. Had the same problem with that one.

**Comment by joaomoreno** [comment]
Maybe it has to do with the node version used? Which versions do you have in each machine?

What do you get when running `node ./node_modules/vscode/bin/compile` in the mac?

**Comment by buzzfrog** [comment]
(~/git/vscode-imagepreview/node_modules/vscode/bin): node compile
../../../src/extension.ts(3,25): error TS2307: Cannot find module 'vscode'.
../../../test/extension.test.ts(11,25): error TS2307: Cannot find module 'vscode'.

**Comment by joaomoreno** [comment]
Can you remove the `node_modules` folder and run `npm install`?

**Comment by buzzfrog** [comment]
It worked. Great.
