### ISSUE TITLE
Windows - search result resource path is incorrect in multi root folder setup

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31135]
Happens on Windows only.

- in multi root folder setup search for a pattern using "Find in Folder"
- open the result from the search result view
-> the path to the resource is not correct, the volume name is missing (see below). As a consequence the workbench opens this file as an external file.

![image](https://user-images.githubusercontent.com/172399/28419817-886ca02c-6d60-11e7-8479-bf91a9cd800a.png)

Opening from the same resource from the explorer shows the following resource path:
![image](https://user-images.githubusercontent.com/172399/28419887-ba9b7b72-6d60-11e7-87dc-5b80c806ef6b.png)

**Comment by egamma** [comment]
Additional info from @bpasero 

>I can reproduce the search issue as soon as I do "Find in Folder" of the root folder where "shorten" is in
not if I do not do that (e.g. without include rule)

**Comment by roblourens** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/8201d4606b3eff92505898528d8e19b77d52633c or https://github.com/Microsoft/vscode/commit/75fd5a7f29602537705a221006aeee7fa1445a9d
