### ISSUE TITLE
Toggle word wrap not working after update

### ISSUE THREAD

**Issue by ibunubi** [Microsoft/vscode#31139]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:24:22.120Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-simple-icons|Lau|1.4.1
material-icon-theme|PKi|2.0.11
php-formatter|Sop|0.2.4
ReactSnippetsStandard|Tim|1.1.0
vscode-wakatime|Wak|1.1.12
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
vscode-icontheme-nomo-dark|be5|1.3.2
vscode-babel-coloring|dza|0.0.4
easy-icons|jam|0.3.1
react-component|jer|1.0.0
php-symbols|lin|2.1.0
laravel5-snippets|one|1.3.4
seti-icons|qin|0.1.3
vscode-icons|rob|7.10.1
html5-boilerplate|sid|1.0.1
vscode-gulp|tan|0.0.4
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open file
2. Go to View > Toggle Word Wrap > nothing happen

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
This is already fixed and you'll see it with today's Stable 1.14.2 update.
