### ISSUE TITLE
Duality between single-folder workspaces and multi-folder workspaces

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#31147]
I looked at the multi-root workspace implementation and noticed that the internal API differentiates between a "single-folder workspace" (an opened folder) and a "multi-folder workspace" (a workspace with possibly multiple roots that can be persisted to a file). Depending on the kind of workspace, different code paths are taken in multiple places.

When a user has a folder open and wants to add a second one, he is prompted with this dialog:

![Upgrade Workspace](https://user-images.githubusercontent.com/900690/28367923-f06008be-6c92-11e7-8c53-bd07f0a7cc56.png)

This makes the UX heavier than in e.g. Sublime, where you can just open a single folder, then drag-and-drop other folders to add them to the workspace without having to reload.

New "multi-folder" workspace already don't need to be explicitely saved in VS Code, there is a concept of an untitled workspace and VS Code is able to restore even untitled workspaces from a previous session.

I am wondering whether it would be easier to not differentiate between "single-folder" and "multi-folder", but let single-folder just be an untitled workspace with a single folder in it. That way
- a user could add more folders without having to "upgrade" the workspace and reload
- the internal API becomes a lot simpler (smaller bug area, e.g. #31142)

Users who don't want to use multi-folder workspaces would not notice the change. The single folder would always be opened in the "default" untitled workspace. File -> Open Folder would just replace the `roots` array with a new array that only contains the new folder. This would also provide the ability to change folders completely without reloading the window once extensions handle the `onDidChangeWorkspaceRoots` event.

Would love to hear your thoughts!

**Comment by bpasero** [comment]
@felixfbecker please read my comments here: https://github.com/Microsoft/vscode/issues/396#issuecomment-315079618 and here: https://github.com/Microsoft/vscode/issues/396#issuecomment-315402932

**Comment by felixfbecker** [comment]
Yeah, I have been following all the threads closely. Here are my thoughts:

#### Re: Workspace settings (or better _folder settings_)
As I see it, all settings in VS Code fall into one of two categories: Global settings that change the editor (like fontSize, zoomLevel, colourTheme, autocompletion preferences...) and settings that make sense for a folder scope (indentStyle, search.exclude, ...). The settings for a folder scope can be just that, folder-scoped. If you edit a file in a multi-folder workspace context, VS Code can walk the parent directories up to find the right indentStyle setting. If you search in a multi-folder workspace context, VS Code can honour the search.exclude settings for each folder. This handling needs to be solved anyway for multi-folder workspaces, I think it should be possible to solve them in a way so that single-folder workspace == multi-folder workspace with one folder.

#### Re: Extensions
Extensions that don't yet support the new API, will have to work with only `roots[0]` or by running one extension instance per folder. If the roots change, the extension for that folder can be killed and/or a new instance spawned. As I understand it that is the planned approach for language servers. Like the above, this is a general challenge of multi-folder workspaces and not better or worse with ditching single-folder workspaces.

Am I missing a case?

**Comment by bpasero** [comment]
@felixfbecker yes, for settings we try to support more settings per folder to solve this. however, the vast majority of settings cannot be supported while users might still have it configured per workspace (e.g. the workbench theme). so we need to have a solution in place that explains this to the user. if the user starts with a red theme for one workspace and then goes into multi root workspace, we have to consider asking the user to "migrate" this setting into the workspace file.

Extensions: you are outlining what extensions will have to do to adopt multi root but the reality is that this will take a lot of time (we see this by just looking at the extensions we ship with). So we will have a period of time where extensions are not working properly for multi root workspaces. Falling back to the first root folder for `workspace.rootPath` is just to avoid a breaking API change, but functionality wise extensions that only support `workspace.rootPath` are not multi-root capable and the user will be confused why an extension in single-folder case works good but not in multi-folder case. 

Btw @sandy081 is working on making the transition from 1 to multi folder smoother. His latest change hides the fact that we have explicit workspaces elegantly. After selecting "Add Folders to Workspace..." and picking the folder, all you are presented with is this dialog:

![image](https://user-images.githubusercontent.com/900690/28449699-429e73cc-6de2-11e7-8e42-4385aa694d28.png)

This is very similar to the transition from 0-1 folders where we also do a window reload.

**Comment by felixfbecker** [comment]
> if the user starts with a red theme for one workspace and then goes into multi root workspace, we have to consider asking the user to "migrate" this setting into the workspace file.

This is about when a user has defined a red theme in a folder setting, correct? I personally don't think anyone would want to put themes in folder setting, so I would simply only support that setting in the user settings.

Extensions: Wouldn't it be possible to run one extension instance per folder? There could be a feature flag for extensions (e.g. in package.json) to opt-in to multi-folder support so they only get spawned once.

I just saw the new API to react to root path changes and saw the opportunity to make folder switching possible without having to reload the window (no matter if multi-folder or single-folder, by consolidating the two). The amount of reloading required for switching folders or installing extensions is one of the few thing that I always disliked about VS Code, so wanted to start the discussion how some of this could be avoided. Do you think that would be possible with the new APIs?

**Comment by bpasero** [comment]
> This is about when a user has defined a red theme in a folder setting, correct? I personally don't think anyone would want to put themes in folder setting, so I would simply only support that setting in the user settings.

That would be a breaking settings change for all our users: As long as we used to support all settings as a folder setting we cannot simply stop supporting that only because of multi-root because many users might not even care about multi root and never use it. Having the workbench theme defined per folder is a perfectly valid use case: a user might want to distinguish different projects she is working on when having multiple windows opened by using a different theme per folder (and thus, per window). Now, supporting different themes per folder when multiple folders are opened in a single instance (= multi root) is rather unlikely (imagine the theme changing depending on the active file you have opened - that is a bit weird). 

Bottom line:
* whatever we do for multi-root cannot break anyone that is used to our current single-folder behaviour
* going from 1 folder to many folders is a step where we need to consider migrating the workspace settings which are defined in the one folder the user started to the workspace config file (imagine you start with a folder that has the Red theme defined as folder setting and you add another folder and suddenly your theme is back to default dark)

> Extensions: Wouldn't it be possible to run one extension instance per folder? There could be a feature flag for extensions (e.g. in package.json) to opt-in to multi-folder support so they only get spawned once.

We discussed this and felt it was not possible to run an extension host per folder. One of the reasons is that each extension can make UI contributions (e.g. a status bar entry like the Travis CI extension) and we want to avoid that one extension is adding something to the UI multiple times instead of providing one integration that is multi-root capable. In other words, running one extension host per folder prevents our extensions from properly supporting multi-root APIs. 

> I just saw the new API to react to root path changes and saw the opportunity to make folder switching possible without having to reload the window (no matter if multi-folder or single-folder, by consolidating the two). The amount of reloading required for switching folders or installing extensions is one of the few thing that I always disliked about VS Code, so wanted to start the discussion how some of this could be avoided. Do you think that would be possible with the new APIs?

Yes it would be possible with the new APIs. However we need to continue to reload the window as long as `workspace.rootPath` is not removed from our extension API. In other words, if we were to release VS Code 2.0 with all our deprecated API removed, we can talk about disabling the window reload.

Btw the window reload is bad, but what we really need is to reload the extension host process. Another idea is to keep the window around but reload that process in the background.

**Comment by felixfbecker** [comment]
Makes sense, thanks for explaining.

> Yes it would be possible with the new APIs. However we need to continue to reload the window as long as workspace.rootPath is not removed from our extension API. In other words, if we were to release VS Code 2.0 with all our deprecated API removed, we can talk about disabling the window reload.
> 
> Btw the window reload is bad, but what we really need is to reload the extension host process. Another idea is to keep the window around but reload that extension host process in the background.

That would be much better. Do you mean just for upgrading a workspace or also for switching folders?

**Comment by bpasero** [comment]
@felixfbecker I would think probably any transition where we force a window reload today. However there is a gotcha: a window reload also helps us for getting a fresh JS V8 context and as such, any previously created caches and data structures are cleaned up and freed. Supporting everything without window reload not only means to be able to restart the extension host independent from the window but also means that we have to make all of our code fit for such a context switch. 

We might start simple and make the transition from 1 to N folders smooth for now, which is already a bit of work. Then we can think about the other transitions.

**Comment by bpasero** [comment]
Closing as we shipped multi root.
