### ISSUE TITLE
Settings view: Focus moves from active buffer to searchbar after executing command

### ISSUE THREAD

**Issue by MichaelZalla** [Microsoft/vscode#31146]
- VSCode Version: Code - Insiders 1.15.0-insider (3cfa565abbd6e162b7ae6f3055c231128da63df2, 2017-07-17T05:07:20.317Z)
- OS Version: Darwin x64 16.6.0
- Extensions: Reproduces without extensions.

![vscode-insiders-settings-focus](https://user-images.githubusercontent.com/2955510/28428795-5b00fd58-6d2f-11e7-8615-028b2258c20f.gif)

Steps to Reproduce:

1. Open the Settings view (`⌘ + ,`).
2. Focus one of the buffers ("User Settings", "Workspace Settings", etc).
3. Run a command through the Command Palette (e.g., `Sort Lines Ascending`).

Expected result:

- Command executes and focus remains in the active buffer.

Actual result:

- Command executes and focus is moved to the Settings searchbar.

Is this by design?

**Comment by sandy081** [comment]
It's not by design. It's a bug. Sorry for that.
