### ISSUE TITLE
Titlebar color

### ISSUE THREAD

**Issue by adrianoresende** [Microsoft/vscode#31145]
How i change color this titlebar?
I would change to green or white

![image](https://user-images.githubusercontent.com/798755/28428806-ed8f4f28-6d50-11e7-8545-fb0726feeee7.png)

**Comment by bpasero** [comment]
This can be done via settings:

```json
"workbench.colorCustomizations": {
    "titleBar.activeBackground": "#ff0000"
}
```

**Comment by adrianoresende** [comment]
@bpasero I meant the color of the letters =P

**Comment by bpasero** [comment]
```json
"workbench.colorCustomizations": {
    "titleBar.activeForeground": "#ff0000"
}
```

?

**Comment by adrianoresende** [comment]
Thanks!
