### ISSUE TITLE
After updating VS code to latest version Code sysntax color not working

### ISSUE THREAD

**Issue by cpatel22** [Microsoft/vscode#31154]
![image](https://user-images.githubusercontent.com/7018966/28434604-eb46f196-6d5d-11e7-997a-f52ba0982394.png)

**Comment by mjbvz** [comment]
Your file is set to plaintext mode. Try changing the language mode to js: https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file

**Comment by cpatel22** [comment]
[image: Inline image 1]

can you tell me why it's showing red line and no color syntax

*Chirag Patel*

Sr.Software Engineer

Mobile: +1 (813) 546 9309

Email:  er.patelchirag@gmail.com

Connect With Me On:

  <https://www.linkedin.com/in/erchiragpatel>  [image: http://is.gd/p0yarn]
<http://is.gd/p0yarn>

**Comment by cpatel22** [comment]
![image](https://user-images.githubusercontent.com/7018966/28439251-1860a8dc-6d6f-11e7-8201-ebadda33e9c0.png)

**Comment by mjbvz** [comment]
You are using the `typescript` language mode. Try `javascript` or `typescriptreact` if this really is TS code
