### ISSUE TITLE
Editor text on Fedora is aligned to top, not middle

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31152]
Fedora 24 64-bit

The editor text is being aligned to the top of the line, not the middle. This happens at all zoom levels on v1.13.1, 1.14.0 and 1.14.2.

<img width="347" alt="screen shot 2017-07-20 at 11 21 09 am" src="https://user-images.githubusercontent.com/2193314/28432955-d30e3fcc-6d3e-11e7-8ef5-78c7f4b19824.png">

Reproduces with no settings or extensions.

**Comment by rebornix** [comment]
I need new 👓 .

**Comment by alexandrudima** [comment]
Appears to be a Fedora thing or a bug shared by both Firefox and Chrome (via Skia), as Firefox also aligns the text to the top


![image](https://user-images.githubusercontent.com/5047891/30924873-51f3b086-a3b0-11e7-8f67-25446f5175a5.png)

**Comment by alexandrudima** [comment]
This aligning of text to the top appears everywhere in our UI:

I therefore don't think this is an editor specific issue. Please create upstream issues...

![image](https://user-images.githubusercontent.com/5047891/30924912-67ab4c54-a3b0-11e7-8223-c561020e484e.png)

![image](https://user-images.githubusercontent.com/5047891/30924938-7e0996f4-a3b0-11e7-8b78-58ee4a142986.png)

![image](https://user-images.githubusercontent.com/5047891/30924969-959a53a8-a3b0-11e7-8fb8-8899a42b4976.png)

![image](https://user-images.githubusercontent.com/5047891/30924995-b40c5e08-a3b0-11e7-93f3-e8eb608f7742.png)

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
