### ISSUE TITLE
Trying to move new file during creation moves existing file 

### ISSUE THREAD

**Issue by glennpeters** [Microsoft/vscode#31157]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vue|liu|0.1.5
csharp|ms-|1.11.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
vetur|oct|0.9.1

---

Steps to Reproduce:

1. Click New File
2. Before naming the file, click on the icon to the left of the file name input field (if it's not meant to be a "move me" icon, it certainly looks like one) and drag to move the pending file.
3. Instead of moving the pending new file, VS Code will abort new file creation and instead move the file that was in that spot before "New File" was clicked.

Optional additional step: User is very confused.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
@bpasero the issue is that the new file placeholder gets an icon, is it possible to specify that a tree entry does not get an icon? Where do you add these icons in the explorer?

**Comment by bpasero** [comment]
@isidorn I disagree that we should not show an icon for the new-file placeholder, because you will notice that while you type the extension, the icon updates and reflects the file type.

I suggest to restore the previous title of this issue because that seems like the issue to resolve (e.g. do not close the input box if the user is clicking still somewhere into the row of the tree item.

**Comment by 4O4** [comment]
I'd like to try to fix this. Is PR welcome or someone is already working on this?

**Comment by isidorn** [comment]
@4O4 a PR is welcome
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L326

**Comment by 4O4** [comment]
Thanks @isidorn , I'm going to work on this then :)

**Comment by jeanp413** [comment]
Hi, I'd like to take this up if you are no longer working on it @4O4

**Comment by 4O4** [comment]
@jeanp413 Unfortunately I haven't made any progress with this so feel free to take this 🙂
