### ISSUE TITLE
Debugger: Call Stack frame duplicate display 

### ISSUE THREAD

**Issue by rajkumar42** [Microsoft/vscode#31150]
_From @qian6 on July 20, 2017 9:25_

## Environment data
 dotnet --info  output:

- OS Name: Windows
- OS Version: 10.0.15063
- OS Platform: Windows
- RID: win10-x64
- Base Path: C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.14.1
 C# Extension version: https://github.com/OmniSharp/omnisharpvscode/releases/download/v1.12.0-beta3

## Steps to reproduce

1. Run command to create dotnet project as following:

   dotnet new console -o hwapp
   cd hwapp
   dotnet restore
   dotnet run

2. Open hwapp project in vscode.

3. Press F5 to start debugging.

5. Observer Call Stack window.

## Expected  behavior
It can display normally.

## Actual behavior
![capture](https://user-images.githubusercontent.com/20922638/28410314-dcd16648-6d6f-11e7-9ffd-7bdffdb1f902.PNG)

_Copied from original issue: OmniSharp/omnisharp-vscode#1653_

**Comment by rajkumar42** [comment]
_From @qian6 on July 20, 2017 9:27_

This issue can reproduce in all OS(windows/mac/Linux)

**Comment by rajkumar42** [comment]
@weinand @isidorn this reproduces with stable VSCode + stable C# extensions.

**Comment by isidorn** [comment]
Please try with vscode insiders tomorrow.
Closing as dup of https://github.com/Microsoft/vscode/issues/30660
