### ISSUE TITLE
Feature request: Pre-populate lua blocks

### ISSUE THREAD

**Issue by Brickcaster** [Microsoft/vscode#31158]
When a new block is detected (for example, after doing function myfunc() (enter)) the editor should automatically indent the next line and insert an extra line containing "end".

Other obvious triggers:

function ...(...)
- for  ... do
- while ...
- if ... then
- do

**Comment by rebornix** [comment]
This is actually a good candidate for Lua snippets :)

**Comment by nikeinikei** [comment]
I would go with the more "natural feeling" vim (and also atom) behaviour, where the next line is indented after a keyword, but there wont be an "end" inserted automatically) in the next line. It will just indent back when you type end (or return). (I dont know if I worded that badly)

**Comment by mjbvz** [comment]
Closing as this can be added by an extension
