### ISSUE TITLE
Code integration with OneDrive Place Holders

### ISSUE THREAD

**Issue by anwmoment** [Microsoft/vscode#31151]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.5
vscode-markdownlint|Dav|0.9.1
python|don|0.6.8
vscode-pandoc|Dou|0.0.8
PowerShell|ms-|1.4.1
spellchecker|swy|1.2.13

---

The latest release of OneDrive (insider Preview)  now supports place holders --- yay
VS Code treats Directories in OneDrive as files --- boo

Can we expect that Code will soon understand the difference between the place holder and the real deal? 
Steps to Reproduce:

1. Attempt to open a folder in OneDrive with following version installed.

![image](https://user-images.githubusercontent.com/3435170/28431707-1b84406c-6d3a-11e7-8a58-28545f1724c1.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
#27285
