### ISSUE TITLE
Option to start different type of terminal sh/ps1/cmd.exe

### ISSUE THREAD

**Issue by mysticole928** [Microsoft/vscode#31156]
Please create an option to start a different type of terminal session.

For example, if I want a PowerShell terminal, I have to create/open a .ps1 file before I can start it.  Currently, on Windows 10, I have my default as bash but I am doing some cross-platform testing and want to have both.

**Comment by Tyriar** [comment]
You can configure multiple shells using this extension https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

**Comment by mysticole928** [comment]
Thank you for this.


However, I have zero idea on how to make this work.  I've looked at the docs as well as the repository.


I've installed the extension.  I've looked at the key bindings and configuration files.  The next steps may be intuitive for power users.


So, I'm going to go with, for mere mortals, this is not possible.


Stephen

________________________________

**Comment by Tyriar** [comment]
@mysticole928 try adding this to your settings:

```js
"shellLauncher.shells.linux": [
{
  "shell": "C:\\Windows\\System32\\bash.exe",
  "label": "WSL Bash"
},
{
  "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  "label": "PowerShell"
}
]
```

Something like that should work.
