### ISSUE TITLE
Feature request: highlight deprecated functions (JS/TS)

### ISSUE THREAD

**Issue by lmmfranco** [Microsoft/vscode#31159]
It would be nice if the editor somehow highlighted functions annotated with `@deprecated`, maybe strikethrough text.

**Comment by mjbvz** [comment]
I believe that tslint already can generated warnings for `@deprecated` functions: https://palantir.github.io/tslint/rules/deprecation/

This may be a good fit for a TypeScript Server plugin, which can also be used for JavaScript: https://github.com/angelozerr/tsserver-plugins
