### ISSUE TITLE
Go To Definition Javascript file - is not working on last couple updates

### ISSUE THREAD

**Issue by jnystrom** [Microsoft/vscode#3116]
I have a function like:
```
function InventoryController(inventoryService) {
    return {
        init: init,
    };
    function init(){ return 'test'; }
}
```

I used to be able to do a go to definition (F12) when my cursor was in the right hand side of the `init: init` in the return of the Controller function.  I am unable to do this now in the stable release or the Insiders version.

**Comment by egamma** [comment]
Works for me when I have Salsa enabled (which is the new infrastructure that will be the default in the next update). pls see https://code.visualstudio.com/Updates#_javascript-salsa-preview.

**Comment by jnystrom** [comment]
@egamma you are correct...Salsa was not enabled on my instance.  I sure hope that getting salsa enabled becomes something users do not have to worry about.

**Comment by egamma** [comment]
@jnystrom absolutely the user will not have to configure anything to get Salsa after the next update.
