### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by zackarycw** [Microsoft/vscode#31165]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 
C# + C/C++ from Microsoft

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
latex|ms-|0.1.3
debugger-for-edge|msj|0.4.1

---

Steps to Reproduce:

1. Running any program with .cs, .tex, .cpp

Reproduces without extensions: Yes

Intellisense was working recently, then it stopped working. It's kind of annoying to type EVERYTHING by hand, I think it would be nice to have Intellisense like in Visual Studio. It gets tiring typing "\documentclass{article}" and the "using System;" then "namespace {name}" then "class Program {}" then "static void Main(string[] args) {}" again and again and again. I've been using Notepad++ as a replacement until this can get fixed. It's also annoying how it doesn't recognize classes and methods that I've called by typing by hand previously. i.e. "Console.WriteLine();" over and over again. Intellisense stopped working after I did an update for VS Code and is annoying. Any way to install older versions of VS Code to get Intellisense working again maybe?

**Comment by chrisdias** [comment]
@zackarycw what language are you seeing this issue with? Looks like C#, but I want to confirm.

**Comment by chrisdias** [comment]
//CC @DustinCampbell

**Comment by zackarycw** [comment]
Multiple, C#, C++, LaTex, Intellisense used to work but now it doesn't anymore. I miss Intellisense, I thought it was such a great tool. Did it get removed in an update or something?

**Comment by isidorn** [comment]
Please file this against the extension for which you do not get inteli-sense. IN this case C#

**Comment by DustinCampbell** [comment]
FWIW, it seems suspicious that this would be an issue in the C# extension if IntelliSense isn't working in three different extensions.
