### ISSUE TITLE
PHP Syntax broken by `@var array(string)` in a comment

### ISSUE THREAD

**Issue by neerolyte** [Microsoft/vscode#31169]
- VSCode Version: Code - Insiders 1.15.0-insider (cf9726da54472f1e268135a64abd4365b91109f4, 2017-07-20T05:07:26.027Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
puppet|Bor|0.3.2
vscode-docker|Pet|0.0.16
vscode-intelephense-client|bme|0.7.2
vscode-phpmd|eco|1.0.1
php-debug|fel|1.11.1
php-symbols|lin|2.1.0
php-docblocker|nei|1.2.0
vim|vsc|0.9.0
gitblame|wad|2.0.1
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Create a php file with code like:

```php
<?php
/**
* @var array(string)
*/
$foo = 'bar';
```

2. Observe incorrect syntax highlighting:

![image](https://user-images.githubusercontent.com/1070702/28444320-ab9e1356-6dff-11e7-92fe-3dbfba48be59.png)

This started in the last few days and the current stable version doesn't do it (it's just in insiders atm):

![image](https://user-images.githubusercontent.com/1070702/28444300-8ab16aee-6dff-11e7-86c4-e03ae827f52c.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Filed https://github.com/atom/language-php/issues/245

**Comment by neerolyte** [comment]
The upstream fix in atom/language-php#245 does resolve this issue, but VSCode 1.15.0 came out without this fix, so it's now broken.

**Comment by roblourens** [comment]
Yeah, the fix didn't come soon enough, but it should be fixed in Insiders if you want to use that instead.

**Comment by mattacosta** [comment]
Confirmed, this has been fixed in the mean time.

**Comment by neerolyte** [comment]
Fixed in Version 1.17.0.
