### ISSUE TITLE
Editor rulers disappear at lower zoom levels

### ISSUE THREAD

**Issue by jdatskuid** [Microsoft/vscode#31160]
- VSCode Version: Code - Insiders 1.14.0-insider (6afdf303bb8f70d840c12a43c036e98a9da50d41, 2017-07-05T09:01:45.828Z)
- OS Version: Darwin x64 16.6.0

Steps to Reproduce:

1. Zoom out the text editor one step (Cm + -)
2. Toggle the side bar so that it is visible then slowly resize it. At certain positions, the ruler dissapears.

I'm _guessing_ that this is happening because scaling is handled using a cheap algorithm that's throwing away the one-pixel ruler at certain widths. In which case it might be handy to have an `editor.rulerWidth` property so that I can set the ruler to be 2 or 3 pixels wide, etc.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9634 and please try latest version.
