### ISSUE TITLE
Node JS Debugging often incredibly slow

### ISSUE THREAD

**Issue by dungeontiger** [Microsoft/vscode#31164]
Sometimes its fine, most of the time it is unusably slow.  It does not seem to matter if I create a configuration or not.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
vscode-svgviewer|css|1.4.2
python|don|0.6.8
file-icons|fil|1.0.4
vscode-icon-theme|jtl|1.5.0
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.6
vscode-jsp|pth|0.0.2
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@dungeontiger please be more specific: what version of node? how does your launch config look like? what kind of program are you debugging?
Without reproducible steps we cannot investigate.

**Comment by dungeontiger** [comment]
Sorry.  I should know better.

Node version v0.12.2

Its a very simple script that reads a CSV file and writes output.  I have attached the file below.  Nothing special about it I think.

I have no launch configuration.  I just pressed run and selected "node.js" from the menu.  

This has been frustrating me for a while.   In the past I tried creating a configuration and tried using 'node2' as has been suggested but that is no longer supported.

Let me know what else you need from me and I will do my best to provide it.

[app.js.zip](https://github.com/Microsoft/vscode/files/1163943/app.js.zip)

**Comment by weinand** [comment]
The current version of node is 8.2.1. 
Node 0.12.2 is eight (!) versions behind the current shipping version.
VS Code has never supported 0.12.2 (which is incredible old and unsecure).

The former debug type "node2" is now the default if you are using node 8.x.

If you would use node > 6.3 and < 8.0 you could force to use "node2" by setting the "protocol" attribute to "inspector". 

I recommend to read the release notes (or the documentation) to get up-to-date with the fast evolution of VS code.
E.g. the currently supported version of node are explained here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes

I will not investigate your problem with node v0.12.2. But I'll try to reproduce it on node 7.4.

**Comment by weinand** [comment]
To reproduce I would need a CSV input file.

**Comment by dungeontiger** [comment]
Bizzare!  I had just done what I thought would update the version.  

TrainingSetBuilder/> npm install npm@latest -g
npm WARN package.json path-is-inside@1.0.2 No README data
npm WARN package.json sorted-object@2.0.1 No README data
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm@5.3.0 /usr/local/lib/node_modules/npm
TrainingSetBuilder/> node -v
v0.12.2

No reason for me to use an old version like this.  Let me update properly and see what happens.

After some other unsuccessful attempts to update node, I just installed version 8 from the website.  I had no idea what I was using was so old.  Seems to work now.  I will reopen this issue if it comes back.

Sorry for the trouble and thanks for your help.

**Comment by weinand** [comment]
@dungeontiger I find updating node.js pretty painless. I'm installing the latest version by pressing one of the green buttons on this page https://nodejs.org/en/
