### ISSUE TITLE
Scandinavian characters

### ISSUE THREAD

**Issue by PauliSu** [Microsoft/vscode#3117]
Hi!

I created a file with VS Code:

<!DOCTYPE html>
<html>
    <p>How this shows in browser ääÄÄ?</p>
</html>

When I open this in browser it shows like this:

How this shows in browser Ã¤Ã¤Ã„Ã„?

If I reopen this file in notepad and save it then the characters are ok. Why?

In settings:

// The default character set encoding to use when reading and writing files.
	"files.encoding": "utf8",

Br, Pauli

Br, Pauli

**Comment by alexandrudima** [comment]
@PauliSu It is a good idea to keep your files as UTF8, as you've been doing so far. But browsers have no way of knowing the charset, therefore you should use an HTTP header to indicate content type or use `<meta charset="UTF-8">` in the `<head>` section.

**Comment by PauliSu** [comment]
ok, thanks! I'll try that.
