### ISSUE TITLE
extension recommendation sash gone on first start

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31171]
Insiders 1.15.0  f5c4b7

Cold start VS Code, open extension viewlet
notice that the recommended extensions sash/explorer is missing

![image](https://user-images.githubusercontent.com/1487073/28444670-b7281ad2-6d73-11e7-94b1-a2b28e8f2e6b.png)

type in some search criteria...

![image](https://user-images.githubusercontent.com/1487073/28444707-00a3184c-6d74-11e7-94a5-ba7aa332bf14.png)

Then press delete/backspace to clear the search box.
voila, the recommended sash/explorer is now there

![image](https://user-images.githubusercontent.com/1487073/28444673-bf5e7a5c-6d73-11e7-831b-446f34b2113b.png)

**Comment by isidorn** [comment]
I still get this behavior.
Reopening and assigning to August since I do not think it is criticall

![extensions](https://user-images.githubusercontent.com/1926584/28869753-070cdca4-777e-11e7-9696-d6abd2f4d564.gif)

**Comment by sandy081** [comment]
@isidorn Would like to confirm from the above video that Installed and Recommended sections are shown after you typed `escape` in Search field ?

**Comment by isidorn** [comment]
@sandy081 yes, that is correct
