### ISSUE TITLE
Show Preview of file while in Go to File... 

### ISSUE THREAD

**Issue by xiaogwu** [Microsoft/vscode#31170]
Feature Request

It would be awesome if when using Go to File... (Command-P) that a preview of the current highlighted file is show and as you up/down arrow key a different file, you see a preview of the current selected file.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by myfairsyer** [comment]
See #8939 (I guess)
