### ISSUE TITLE
Count extension downloads per IP

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#31176]
Please, count extension downloads per IP, because somebody can execute an script to auto download an extension, cheating results.

example script:

```shell
for i in $(seq 0 1000000)
do
  code --uninstall-extension EditorConfig.EditorConfig
  sleep 0.1
  code --install-extension EditorConfig.EditorConfig
  sleep 0.1
done
```

In one night, the above script would add 1 million downloads, cheating the marketplace counter.

**Comment by agauniyal** [comment]
I agree this should be done but otoh what could someone possibly achieve by doing this?

**Comment by joaomoreno** [comment]
cc @modigrv

**Comment by faustinoaq** [comment]
> I agree this should be done but otoh what could someone possibly achieve
by doing this?

Some Men Just Want to Watch the World Burn

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
