### ISSUE TITLE
When you use multiple lines of annotations to hold ctrl+s several times, the code in the comment section moves right to the right (click Move)

### ISSUE THREAD

**Issue by sky-xsk** [Microsoft/vscode#31174]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
compulim-vscode-closetag|Com|1.1.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
live-html-previewer|hdg|0.0.1
canvas-snippets|hol|0.3.1
vue-snippets|hol|0.1.2
weex|jay|0.4.0
vscode-lebab|jer|1.0.1
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vetur|oct|0.9.1
sort-imports|pet|2.4.0
vue|sea|0.4.2
open-in-browser|tec|1.0.0
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@sky-xsk do you mind providing some code sample or gif even better ?

**Comment by sky-xsk** [comment]
![bug](https://user-images.githubusercontent.com/22072132/28550915-0264f9b0-7117-11e7-902b-dde67cd10799.gif)

Like the GIF above，If you press' ctrl+s' many times, the code will move to the right! （Sorry, my English is not very good!  I don't know. Did I make it clear?）

**Comment by my9074** [comment]
I had the same problem for vue template, when i format the html.@rebornix
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
EditorConfig|Edi|0.9.4
code-settings-sync|Sha|2.8.2
html-css-class-completion|Zig|1.8.0
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
vscode-npm-script|eg2|0.2.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
path-autocomplete|ion|1.6.1
search-node-modules|jas|1.1.1
docthis|joe|0.4.7
debugger-for-chrome|msj|3.1.7
vetur|oct|0.9.3
vuehelper|oys|0.1.0
stylelint|shi|0.28.0
gitblame|wad|2.0.2



---
![8 -03-2017 11-52-31](https://user-images.githubusercontent.com/4555635/28906403-ee33430e-7849-11e7-8660-9dfc4d44397d.gif)

**Comment by rebornix** [comment]
@sky-xsk @my9074 can you reproduce this issue when running vscode without extensions by `code --disable-extensions`? It looks like a formatter issue to me.

**Comment by my9074** [comment]
@rebornix The vue file cannot be identified after I disable all plug-ins，But when I only load the vetur plug-in, It's going to happen.

**Comment by alexandrudima** [comment]
fyi @octref

**Comment by octref** [comment]
You are probably using one of the formatter dependent on js-beautify: https://github.com/beautify-web/js-beautify/issues/1185

My guess is vscode-JS-CSS-HTML-formatter.
In Vetur we moved away from js-beautify already.
