### ISSUE TITLE
After clicking 'Uninstall' on an extension, it sometimes still shows up as if it is installed

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#31173]
_From @qian6 on July 20, 2017 8:46_

## Environment data
`dotnet --info` output:

- OS Name: Windows
- OS Version: 10.0.15063
- OS Platform: Windows
- RID: win10-x64
- Base Path: C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.14.1
C# Extension version: [https://github.com/OmniSharp/omnisharpvscode/releases/download/v1.12.0-beta3](https://github.com/OmniSharp/omnisharpvscode/releases/download/v1.12.0-beta3)

## Steps to reproduce

1. Open VSCode.
2. Install .VSIX and click Reload button as following:
 ![capture](https://user-images.githubusercontent.com/20922638/28407989-ac558834-6d68-11e7-8296-7921ef3e58ee.PNG)
 ![capture1](https://user-images.githubusercontent.com/20922638/28408030-d1f4af7a-6d68-11e7-8f14-914a90c7cb03.PNG)
3. Uninstall .VSIX as following:
 ![capture3](https://user-images.githubusercontent.com/20922638/28408109-f76787aa-6d68-11e7-90a9-00a1c9dae66c.PNG)

## Expected  behavior
![capture4](https://user-images.githubusercontent.com/20922638/28408139-0bf46882-6d69-11e7-9f7e-83d48736737c.PNG)

## Actual behavior
![capture5](https://user-images.githubusercontent.com/20922638/28408162-288643a8-6d69-11e7-91e1-d2c4da444781.PNG)

##Investigate

1. When I closed VSCode and again open ,VSIX had already uninstalled and not display in the UI.
2. This issue reproduce only in windows ,mac/Linux is ok.

_Copied from original issue: OmniSharp/omnisharp-vscode#1651_

**Comment by gregg-miskelly** [comment]
This isn't related to the C# extension, so moving to VS Code.

**Comment by sandy081** [comment]
No longer able to reproduce this. Please try with latest version and try.

**Comment by qian6** [comment]
This issue can reproduce in latest version. You can uninstall the extension after opening the folder(you should delete your alias .vscode folder)
VSCode: 1.18.1
C# Extension version:1.14.0-beta1.
![capture1111111111111](https://user-images.githubusercontent.com/20922638/33204006-ff9b1e18-d13c-11e7-842b-412e70adc333.PNG)

**Comment by sandy081** [comment]
@qian6 Please try with insiders - https://code.visualstudio.com/insiders/
