### ISSUE TITLE
Why doesn't VSCode delete an old extension?

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#31175]
When I updated an extension with Atom, an old version was replaced by a new version. Why doesn't VSCode delete an old extension?

![image](https://user-images.githubusercontent.com/27698189/28447520-71fb63dc-6dfb-11e7-926f-05be65035419.png)

**Comment by faustinoaq** [comment]
If you reload VScode the old extension folder is deleted. At least is my current behavior.

**Comment by sandy081** [comment]
Yes, We do not delete immediately because one of the opened windows could be still running the old version of the extension. We delete it after reload (only when no window is not running old version)
