### ISSUE TITLE
Marketplace rendering of images from README decodes URL characters

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#31189]
Apologies, I don't know if this is the best place to raise this; feel free to point me elsewhere!

In [my readme](https://github.com/Dart-Code/Dart-Code/blob/master/README.md) I have an image with an encoded ampersand (%26) in the URL. It renders correctly on GitHub but on the marketplace is has been decoded to an ampersand in the source, which result in it not being rendered correctly (note it says `Mac` instead of `Mac & Linux`).

<img width="916" alt="screen shot 2017-07-21 at 08 21 25" src="https://user-images.githubusercontent.com/1078012/28453172-010c4a72-6dee-11e7-828d-09b408312e55.png">

<img width="606" alt="screen shot 2017-07-21 at 08 22 12" src="https://user-images.githubusercontent.com/1078012/28453176-05c24e2c-6dee-11e7-848d-4330aacb5f21.png">

**Comment by joaomoreno** [comment]
@chrmarti This is a consequence of running the image URL through url.parse at validation time.

**Comment by chrmarti** [comment]
@joaomoreno I'm discarding the parsed URI after validating it. Let me know if anything needs to be done on my side.

**Comment by joaomoreno** [comment]
No, I think you are fine 👍

**Comment by joaomoreno** [comment]
Moved to https://github.com/Microsoft/vscode-vsce/issues/197
