### ISSUE TITLE
Terminal Find/Search Highlighting

### ISSUE THREAD

**Issue by SahilAgarwal321** [Microsoft/vscode#31183]
Feature Request - Terminal Find/Search Highlighting

- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl + ` for terminal
2. Ctrl + F for find

Implement Term Highlighting for the find/search feature in the internal terminal, like the one present in file search or project search.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/28768
