### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#31184]
Issue Id: <b>2e2231ea-a95c-5caa-1aef-6b8a54bcf134</b><br /><br />*Versions* <br />- 1.14.1<br />-  56a5bf1724f3b882e149a3e7a24e6105a7b837c2<br />-  74f5073c54f1139d2fb0eccb251cae5ed6e8215b<br />-  b8cd5b9556d8b70ea560d35b903422363f6c5c40<br />-  954193248183c7bb4d70c89898bc5337ce57fe98<br />-  6afdf303bb8f70d840c12a43c036e98a9da50d41<br />-  7e2937237620501705e4a5276e76726d35a31905<br />-  cea00a71bef01a5ecbae39a8dd4f1bd08fd50c57<br />-  5cb4570007af28b5e0c0b4177e0283dc961ebbb8<br />-  478365bce508cc391e4cfc5c9e1eeee7c87c39c9<br />-  7bb3b89031cbce46536ba870868d889d639e12f1<br />-  5df9a157abe3243af639f8c1b9503f1b5e7a4a95<br />*Stack* <br />TypeError: Cannot read property 'NaN' of undefined<br />    at SelectionManager._onSingleClick (\node_modules\xterm\lib\SelectionManager.js:228:71) <no sourcemaps><br />    at SelectionManager._onMouseDown (\node_modules\xterm\lib\SelectionManager.js:192:22) <no sourcemaps><br />    at HTMLDivElement._mouseDownListener (\node_modules\xterm\lib\SelectionManager.js:53:67) <no sourcemaps><br />

**Comment by bpasero** [comment]
Another error telemetry issue that seems to originate from Xterm, not sure if already covered.

**Comment by Tyriar** [comment]
I'd also expect https://github.com/Microsoft/vscode/issues/20505 to have resolved this but will add a null check anyway.
