### ISSUE TITLE
Need stash save/pop in git module

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#31187]
- VSCode Version: Win7
- OS Version: 1.15.0 Insiders

Steps to Reproduce:

1. Change `A.ts` `B.ts` 2 files
2. Commit `A.ts` 
3. Wanna sync with remote (rebase and push)
4. Cannot rebase (for there is unstaged changes)

To do the same things in TortoiseGit, it can stash save -> rebase -> stash pop automatically.
Hope have this feature in vscode git.

Once in this situation in vscode , I could only switch to TortoiseGit to finish rebase.

**Comment by joaomoreno** [comment]
#1904

**Comment by johnbillion** [comment]
@joaomoreno You've created a duplicate loop!

This issue is a duplicate of #1904, which is a duplicate of #31187, which is a duplicate of this issue, which is a duplicate of...

**Comment by joaomoreno** [comment]
@johnbillion #1904 is an open issue... What are you talking about?

**Comment by johnbillion** [comment]
Right, but 1904 was still marked as a duplicate of 31187. Thanks anyway!
