### ISSUE TITLE
Additionally open an unnecessary page when using VScode as the default editor of cscope

### ISSUE THREAD

**Issue by csyuanc** [Microsoft/vscode#31185]
- VSCode Version: lastest Linux version
- OS Version: elementaryOS Loki 0.4.1

Steps to Reproduce:

I've set VScode as the default editor when I want to open the file searched from cscope.
By adding the following line into ~/.bashrc:
`export CSCOPE_EDITOR=code`

1. The figure below is a scenario of using cscope at the build-in terminal of VScode, which before opening a file.  
[Figure 1](http://imgur.com/y5fLQmY)

2. And then I pressed number "2" to open the file, it would open the target-file but also an unnecessary file. In this case, the filename was "113", which was the line number showed on cscope screen.
[Figure 2](http://imgur.com/zWlPTt1)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I guess code doesn't support opening a file to a specific line from the command prompt, or doesn't support the format cscope is using. Do you know what command cscope is invoking on `CSCOPE_EDITOR`?

**Comment by bpasero** [comment]
Make sure you pass in the `--goto` command line argument if you have a line number to go to:

![image](https://user-images.githubusercontent.com/900690/28488883-e2576748-6eb4-11e7-9586-ed2493380bae.png)
