### ISSUE TITLE
Error with Inputing Chinese

### ISSUE THREAD

**Issue by maquedexiju** [Microsoft/vscode#31181]
Hi, I set a keybing to my Chinese IME, so I can use control+H to delete wrong characters, and I meet some problems when using vscode.
First I input some characters and get the input candidates, and then I hit control+H in suppose to delete the wrong character, but the ones I've input before are deleted.
The GIF can help you understand my idea.I've input "你好世界" already, then I input "ni hao" and get the character candidates, when I want to delete "ni hao", I got "你好世界" deleted too.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6948576/28449680-7b7b1fb0-6e14-11e7-9e08-90cd34b89722.gif)

**Comment by rebornix** [comment]
@maquedexiju what kind of IME you are using? I have a feeling that we don't understand the custom keybinding from IME side.

**Comment by maquedexiju** [comment]
This is the link for that IME https://github.com/rime/squirrel
But it's all in Chinese, and I think you might not understand that. But even if I use the IME of Mac OS, it still have some problem. 
when I hit Backspace, it works fine, but if I hit control+H, the candidate will disappear, and the character I typed before will be deleted too.

I  think it might be caused because vs code has a keybinding on Mac that when hitting control+H, deleteleft will be sent.

```
{
  "command": "deleteLeft",
  "key": "ctrl+h",
  "when": "editorTextFocus && !editorReadonly"
}
```

Will it be possible for you to detect the status that the character candidate is open and in this case, hitting control+H will not work?

**Comment by maquedexiju** [comment]
Fixed now
