### ISSUE TITLE
HTML ident/autoformatting handling <br> tags: please keep/add new lines

### ISSUE THREAD

**Issue by mariusa** [Microsoft/vscode#31180]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.11.9-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
debugger-for-chrome|msj|3.1.6
vscode-sql-beautify|sen|0.0.4

---

Steps to Reproduce:

1. Enable "Format On Save" by setting
"editor.formatOnSave": true
2. create test.html
3. write this code (don't save)
```
<div class="row">
    <div class="col-md-6">
        Some text<br>
        Line 2<br>
        Line 3<br>
    </div>
</div>
```
4. Save

Expected result: have new lines after <br> tags (add them if not existing), like above

Actual result:
```
<div class="row">
    <div class="col-md-6">
        Some text<br> Line 2<br> Line 3<br>
    </div>
</div>
```

This breaks visibility, makes maintenance harder (lines are longer in real life pages)

Reproduces without extensions: Yes

**Comment by joshuaptfan** [comment]
Also present in 1.14.2

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as the formatter for HTML and what you see is how it supposed to work.

You'd have to file this as a feature request against https://github.com/beautify-web/js-beautify/issues

**Comment by mariusa** [comment]
Already filed 3 years ago:
https://github.com/beautify-web/js-beautify/issues/510
