### ISSUE TITLE
VSCode disable large folders warning

### ISSUE THREAD

**Issue by amihaylov** [Microsoft/vscode#31188]
Is there a way to disable the "To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on." warning as it is displayed on each opening of files? I have configured jsconfig.json excluding folders such as node_moduels, but my source files are in the range of thousands. I couldnt find such option in the preferences so I guess it is a typescript option?
- VSCode Version: 1.14.2
- TS Version 2.4.1

**Comment by mflux** [comment]
I have this issue as well. VS code is showing this warning up to 5 times as I open the project and start skimming through files it's extremely annoying.

I have node_modules and the bundles excluded in the jsconfig as mentioned by other bug reports but it's still happening.

**Comment by psachs21** [comment]
Encountering to exact same issues. Excluding node_modules and other larger directories (dist, static, etc) does nothing. Warning persists.

**Comment by mjbvz** [comment]
This warning means that TypeScript has disabled itself after trying to include too many files.

After adding the excludes, did you restart VSCode? Can you try looking in the TSServer log to see what files are being included:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart vscode
1. Reproduce the issue
1. Run the `TypeScript: Open TSServer log` command in VSCode
1. Open the `tsserver.log` file

In the log file, look for blocks where file names are listed. For example:

```
Info 130  Project '/Users/matb/projects/vscode/extensions/typescript/tsconfig.json' (Configured) 0
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.reflect.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.proxy.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts
/Users/matb/projects/vscode/extensions/typescript/src/protocol.const.ts
/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/protocol.d.ts
/Users/matb/projects/vscode/extensions/typescript/src/protocol.d.ts
/Users/matb/projects/vscode/extensions/typescript/node_modules/vscode-nls/lib/main.d.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/is.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/logger.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/electron.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/wireProtocol.ts
/Users/matb/projects/vscode/extensions/typescript/node_modules/@types/semver/index.d.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/api.ts
/Users/matb/projects/vscode/extensions/typescript/src/typescriptService.ts
/Users/matb/projects/vscode/extensions/typescript/src/utils/plugins.ts
...
```


Glance through these files and see if there are any unexpected files being included. Please share your `tsconfig` or `jsconfig` and the paths of some of the unexpectedly included files so that I can investigate

**Comment by mflux** [comment]
Thanks @mjbvz I reproduced it and it looks like it's including node_modules

    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/modules/meshgenerator/structure/shapes/setback.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/modules/threejs_extra/SubdivisionModifier.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/abbrev/abbrev.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/acorn/dist/acorn_loose.es.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/acorn/dist/acorn_loose.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/acorn/dist/acorn.es.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/acorn/dist/acorn.js",
    "c:/Users/Flux/Documents/Unreal Projects/CPCS/Content/Scripts/game/node_modules/acorn/dist/walk.es.js",

Despite my jsconfig.json declaring otherwise:

		{
			"compilerOptions": {
				"target": "ES6",
				"noLib": false,
				"charset": "utf8",
				"module": "es6"
			},
			"exclude": [
					"node_modules",
					"game/gameview.js",
					"game/gamecore.js"
			]
		}

Any ideas on why it's not excluded?

**Comment by mflux** [comment]
I got it, node_modules is not root to my project. I think there's a misunderstanding on my part in how exclude decides to match the folder. I thought "node_modules" would exclude any folder or file named node_modules.

I think to correct this confusion, the example in the documentation here: https://code.visualstudio.com/docs/languages/jsconfig should either 

1. make a note of the matching rules for folder and 
2. Include some kind of **.*node_modules wildcard directly in the example

**Comment by mjbvz** [comment]
Thanks, I believe you are running into this bug: https://github.com/Microsoft/TypeScript/issues/12750

Try changing you exclude to `"exclude": ["**/node_modules/*"]`. I'm going to update the docs with the workaround

**Comment by mjbvz** [comment]
I've updated the docs: https://github.com/Microsoft/vscode-docs/commit/4834f955cb286b739b0c729ebd6437a5a67aadc8

Let me know if you still see this issue after using the glob exclude for `node_modules`

**Comment by amihaylov** [comment]
Looks this worked for me as well.

**Comment by schreifels** [comment]
I'm also receiving this warning regularly, but it does not seem to be actionable for me. Our project has ~2400 JS files, not including any 3rd party code. I turned on verbose mode and verified that `tsserver.log` only outputs references to our files and that it had the same number of files I would expect.

Is TS Server just not able to handle this number of files? (For what it's worth, these are all source files; there are no bundles included in the glob.)

Any help would be appreciated. Thanks!

**Comment by aarongoldenthal** [comment]
With the glob exclude for node_modules I was still having this issue with every .js file that I opened.  What eventually resolved it was updating jsconfig.json to exclude another large folder (~300 files) that I already had excluded in settings.json.

I expected settings.config exclusions to take precedence, then apply jsconfig.json exclusions, but it appears that's not the case.

**Comment by ericnoguchi** [comment]
I still am getting  this warning when opening js files

**To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.**

My jsconfig.js
```
{
    // This file is required for VSCode to understand webpack aliases
    "compilerOptions": {
        // This must be specified if "paths" is set
        "baseUrl": ".",
        // Relative to "baseUrl"
        "paths": {
            "common/utils": ["./somepath/*"]
        }
    },
    "exclude": [
        "**/node_modules/*",
        "**/webroots/*",
        "**/vendor/*",
        "**/Wpe/*",
        "**/scripts/*"
    ]
}

```
