### ISSUE TITLE
When the right mouse button opens, several vscode versions appear.

### ISSUE THREAD

**Issue by smallxiaotongxue** [Microsoft/vscode#31186]
<img width="491" alt="jietu20170721-141645" src="https://user-images.githubusercontent.com/24557122/28451371-790c02ac-6e1f-11e7-9f88-a07d33d247be.png">
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.1.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
cssrem|cip|0.0.3
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.2
vue|jcb|0.1.5
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|3.1.6
vscode-css-peek|pra|1.3.1
open-in-browser|tec|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
You have them somewhere in your system. Locate them and delete them.
