### ISSUE TITLE
reactive extension library issue?

### ISSUE THREAD

**Issue by zaritzki** [Microsoft/vscode#31194]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
mustache|daw|1.0.0
coldfusion|ili|0.0.10
automagic-code|jai|0.0.2
sde|jin|2.0.20170209
Angular2|joh|2.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.62
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.1.6
cordova-tools|vsm|1.2.7
vscode-react-native|vsm|0.3.2
twig|wha|1.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this agains the react native extension
