### ISSUE TITLE
HTML: format document issue

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#31190]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063

the origin file is:
![1](https://user-images.githubusercontent.com/11925432/28453164-a70084fe-6e28-11e7-9a04-bd9e6d13b78b.jpg)

"Format Document" does nothing with default settings.

If I remove "span" from "html.format.unformatted"
![2](https://user-images.githubusercontent.com/11925432/28453276-33882cec-6e29-11e7-8ab5-01d79a69b409.jpg)

The first "a" element is formatted too, and it's unnecessary.

The Visual Studio's format:

![3](https://user-images.githubusercontent.com/11925432/28453337-7e8ae374-6e29-11e7-9182-df2e34a9f29f.jpg)

As a user, I don't like some html.format.unformatted settings, Visual Studio's format(html, xml etc) is what I want.

[test.html.zip](https://github.com/Microsoft/vscode/files/1164726/test.html.zip)

**Comment by King66** [comment]
Another format issue:
```
<address>
    Written by <a href="mailto:webmaster@example.com">Jon Doe</a>.<br>
   Visit us at:<br>
    Example.com<br>
    Box 564, Disneyland<br>
    USA
</address>
```

format using VSCode:
![1](https://user-images.githubusercontent.com/11925432/28505001-e7b39876-7051-11e7-9aac-e295c62da3e8.jpg)

format using VS:
![2](https://user-images.githubusercontent.com/11925432/28505054-5c2fc404-7052-11e7-9cce-62c648b4553e.jpg)



VSCode shouldn't change it to 2 lines.

**Comment by aeschli** [comment]
Please file these suggestions against https://github.com/beautify-web/js-beautify/issues which is the formatter we use under the hood.
