### ISSUE TITLE
Smoke test: No Build Task found

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31192]
1. Add the following tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "eslint",
            "problemMatcher": {
                "base": "$eslint-stylish",
                "fileLocation": "absolute"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

2. Run `>Tasks: Run Build Task`

Results in `No Build Task found. Press 'Configure Build Task' to define one.`

_Reported by smoke tests (tfs build ids 30819, 30820, 30821)._

**Comment by egamma** [comment]
Issue introduced as part of the multi root folder exploration, added a required `path` attribute to the npm task definition. Remove this attribute for now.
