### ISSUE TITLE
Display the full workspace path in UI

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#3119]
I have two workspaces:

`c:\docs\dev\version1\js`
and
`c:\docs\dev\version2\js`

If I open one VisualCode instance with the workspace `c:\docs\dev\version1\js` and another one with `c:\docs\dev\version2\js` there no easy way to know which window points to which workspace.

The only information that is displayed in the UI is the last folder of the workspace's path which is in both cases `js` so it's not really helpful.

It would be great if there was an option to show the full path to the workspace instead of the last folder in the UI.

**Comment by rodo79** [comment]
+1

**Comment by lfurzewaddock** [comment]
Perhaps installing the [Active File In StatusBar](https://marketplace.visualstudio.com/items?itemName=RoscoP.ActiveFileInStatusBar) extension would answer the problem.

**Comment by prufrock123** [comment]
+1

**Comment by bpasero** [comment]
Added a new setting `window.showFullPath`. If enabled the window title shows like this:

![image](https://cloud.githubusercontent.com/assets/900690/19919435/15dc503e-a0d3-11e6-849a-32f77c81f306.png)

**Comment by kentor** [comment]
@bpasero will that be released next month?

**Comment by mrmlnc** [comment]
@kentor, yes, November release.

**Comment by martynchamberlin** [comment]
The  only bummer here is that if you go full screen, which I do often with a split pane view in macOS (VSCode on the left, Chrome browser on the right), then you can't see the title bar of the application.

**Comment by bpasero** [comment]
@martynchamberlin I think that is the point of going fullscreen in the first place. What is useful is to disable tabs and just benefit from the fact that the space you get from disabling tabs is used to show the path of the file:

![image](https://cloud.githubusercontent.com/assets/900690/21325804/5417ece4-c628-11e6-84bd-d3027878eb5d.png)

(though arguably this does not have a setting to show the full path, only on hover it gets revealed)

**Comment by martynchamberlin** [comment]
Oh cool, didn't know about this. Thanks! Trying it now.

**Comment by bsienn** [comment]
@bpasero  `window.showFullPath` gone in v1.10.1 why...... :(

**Comment by bpasero** [comment]
@bsienn 

> Note: We no longer support window.showFullPath in favor of the window.title setting. The variable ${activeEditorLong} will give you the full path.

from http://code.visualstudio.com/updates/v1_10#_configurable-window-title

**Comment by bsienn** [comment]
Ahh, I didn't read the whole change log. My bad.
Got it working.

Thanks for super quick response.

**Comment by itumoraes** [comment]
Thanks @bpasero!

**Comment by jackiilong** [comment]
add this line "window.title": "${activeEditorLong}", works for me
