### ISSUE TITLE
Selecting text from left to right, and choosing item messes up code

### ISSUE THREAD

**Issue by markknol** [Microsoft/vscode#31199]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Select text from left to right or double click text and trigger completion
2. Select option from completion
3. Notice the code (removes a bit of code written) 

![oops](https://user-images.githubusercontent.com/576184/28457954-462bf50c-6e08-11e7-9e35-d491300c7fb5.gif)

I would expect the selection of the completion menu would only replace the selected text.

Reproduces without extensions: Haven't tried. I use vshaxe 1.9.0, but also seems to happen in typescript.

**Comment by ramya-rao-a** [comment]
@markknol can you share the sample code and the programming language being used?

**Comment by markknol** [comment]
If you open new document (ctrl-n) (no particular programming), this is the most minimal snippet:
```
broken br
```
Now select the last word "br" by double clicking, then ctrl-space, then select "broken" the output looks like:

``` 
brokebroken
```

**Comment by ramya-rao-a** [comment]
Thanks! I can repro

**Comment by ramya-rao-a** [comment]
@jrieken I could trace down the issue till https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippetSession.ts#L233

Take the case of `broken br` in a plain text file. 
- Trigger suggestions with cursor after the `br`
- Trigger suggestions after selecting `br`

In both cases `overwriteBefore` is 2
The `startColumn` is different for the 2 and so the final range is different too.
