### ISSUE TITLE
Running a launch config with a missing "request" attribute fails silently

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31197]
I was just bitten by this:
Running a debug session that is missing the "request" attribute fails silently and the only indication is the tiny green squiggly:

![2017-07-21_11-20-23](https://user-images.githubusercontent.com/1898161/28457983-55984c66-6e08-11e7-8271-0264bb76581e.png)

Since the "request" attribute is mandatory I suggest that we show an error notification like the one for an unknown debug type.

![2017-07-21_11-34-45](https://user-images.githubusercontent.com/1898161/28458065-9f9c880e-6e08-11e7-8d56-3a2d0f83af06.png)

**Comment by roblourens** [comment]
I don't see an error message

- Open vscode workspace
- Delete 'request' line from "Launch VS Code"
- Try to start the launch config
- Nothing happens

**Comment by weinand** [comment]
I get the error message if the "request" attribute is missing:

![2017-09-28_10-33-26](https://user-images.githubusercontent.com/1898161/30956769-98435a5e-a438-11e7-8727-74b481ea14a2.png)

However, I do not like the wording: What exactly is a "debug request"?

I recommend:
"Attribute 'request' is missing from the chosen debug configuration."

(Make sure that 'request' is not translated by nls by adding it as an message argument)

**Comment by isidorn** [comment]
@roblourens nice catch. However this only does not work for that chrome corner case, since chrome is contributing a startSessionCommand and in that case we do not do the `request` check.
This will be handled in october via https://github.com/Microsoft/vscode/issues/33791
Due to that closing

**Comment by isidorn** [comment]
@weinand thanks for feedback, will update the message

**Comment by weinand** [comment]
Reopening because there is still no error message after #33791 has been closed.

**Comment by isidorn** [comment]
@weinand good catch

**Comment by weinand** [comment]
Verified!

But please don't use backticks when quoting arguments or attributes:

![2017-11-02_11-02-44](https://user-images.githubusercontent.com/1898161/32320238-64426d1c-bfbd-11e7-88d9-b51539bea225.png)

I've fixed that.

**Comment by weinand** [comment]
The error still does not show up if a debug session is launched from the status line.
I've created https://github.com/Microsoft/vscode/issues/37507 for this.
