### ISSUE TITLE
Adding folder to workspace should reveal and expand that folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#31195]
Steps to Reproduce:

1. have lots of stuff in the tree so that a scrollbar shows up
2. add a folder to the explorer
3. something scrolls but you are nowhere close to the folder that was added

I would:
* reveal the folder that was added
* expand it automatically to reveal its contents

**Comment by isidorn** [comment]
Ok, I agree this would be optimal behavior, however currently onDidChangeWorkspaceRoots event does not give me the delta of what changed. So I would have to keep track in my model of previous root and new roots to figure out what was just added and specially treat it.
This feels a bit ugly.

A workaround is to have a more general approach. On roots change just expand all roots.

Not a fan of either of these aproacehs -> assigning to august for discussion

**Comment by isidorn** [comment]
@bpasero what do you think about my pondering from above

**Comment by bpasero** [comment]
@sandy081 is it complicated to change the `onDidChangeWorkspaceRoots` event to include the information about added or removed roots?

@isidorn I would not just blindly expand root folders that have not been added. Ideally the event can tell you which folders are added and for these you should:
* expand them all (one level)
* reveal one of the added folders (e.g. the first)

**Comment by sandy081** [comment]
No, can be done.

**Comment by isidorn** [comment]
Great, then once we have a more detailed event we can improve this.
Assigning also to @sandy081 and moving to september

**Comment by bpasero** [comment]
@isidorn added [`IWorkspaceFoldersChangeEvent`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/workspace/common/workspace.ts#L24)

I think the logic within doRefresh is a bit complicated towards distinguishing between a first time refresh (where we check the memento) and subsequent refresh (where we seem to check the expanded elements). I think there is a bit of cleanup needed to make it work properly, but the event should give you all the info now.

**Comment by isidorn** [comment]
Verifier:
* Make sure that adding a new root to the workspace expands that root
* Removing a root does not touch expansion state
* Expansion is preserved across reloads
* Expansion works as before in a folder case

**Comment by jrieken** [comment]
Verified, tho it doesn't reveal the new workspace folder as initially wished for

**Comment by bpasero** [comment]
Yeah I also noticed this, I think its fine now the way it works.
