### ISSUE TITLE
Throttle tree provider refresh events

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31191]
Extracted from https://github.com/Microsoft/vscode/issues/31123#issuecomment-316928133.

**Comment by ppggff** [comment]
It seems this commit break extension "patrys.vscode-code-outline" ? (Guess)
It cannot do refresh right now...

**Comment by sandy081** [comment]
@ppggff Can you please file a separate issue with what is not working with the API with a sample to reproduce it.

**Comment by weinand** [comment]
@sandy081 my loaded scripts explorer doesn't refresh any more.

**Comment by sandy081** [comment]
Strange.. I had tests for refresh. Will see what caused it and fix it. Sorry for that.

**Comment by sandy081** [comment]
My bad, It seems [tree api](https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/tree.ts#L77) does not support refreshing more than one element. I was calling refresh on more than one element.

**Comment by ppggff** [comment]
@sandy081 Fixed, thanks very much. Wait for updating...
