### ISSUE TITLE
JS syntax highlighting breaks when quoted property name and left parenthesis in value

### ISSUE THREAD

**Issue by mickeypearce** [Microsoft/vscode#31193]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601

Object's property name in quotes (ex.:'--file') and left parenthesis ('(') in value break the JS syntax in subsequent code.

Steps to Reproduce:
1. Open JS file with following code:

(with left parenthesis and quoted name) - broken
![synth0](https://user-images.githubusercontent.com/1925433/28454104-49564dc6-6dfa-11e7-981e-5cf387c8147a.PNG)
(without left parenthesis)
![synth1](https://user-images.githubusercontent.com/1925433/28454387-639e6adc-6dfb-11e7-8097-7eff303647bc.PNG)

Works when bracket notation is used. :+1: 
![synth](https://user-images.githubusercontent.com/1925433/28454105-495eac8c-6dfa-11e7-99ac-04450a81c05c.PNG)

Reproduces without extensions: Yes

This code worked with 1.13

**Comment by mjbvz** [comment]
This should already be fixed in insiders. 

You can also install the latest ts grammar in 1.14 to test this out: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar
