### ISSUE TITLE
Find and replace with regex on does not allow replacing with \n

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#312]
The same applies to `\r` and `\t`, not sure if there are any others.

**Repro**

1. Open a file
2. Ctrl+H to bring up find and replace
3. Turn on regular expression matching
4. Match a word
5. Put `\n` in the replace text box
6. Press Replace All

**Expected**

The matched words are replaced with new lines

**Actual**

The matched words are replaces with `\n`

**Comment by Tyriar** [comment]
Thanks for fixing this!

**Comment by egamma** [comment]
When verifying this issue please also consider this test case: https://github.com/Microsoft/vscode/issues/1227#issuecomment-164392805

**Comment by karlti** [comment]
With version 0.10.4 the issue is partially solved.
 
That is, "Test Case 2" is solved.
Thanks for that!

"Test Case 1" is  still open, in that searching for '\n' does not work.
Searching for '\t' works.

Furthermore '\r' is not recognized. 
'\n' apparentely is the RexEx for CRLF....

**Comment by alexandrudima** [comment]
@karlti thank you for verifying :+1:. Let's track searching for `\r` and `\n` in #313
