### ISSUE TITLE
Support relative paths in .code-workspace files

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#31203]
- VSCode Version: Code - Insiders 1.15.0-insider (9912a545c9728ce5e6b3cdfcc9442ee47955aa42, 2017-07-21T05:16:15.475Z)
- OS Version: Windows_NT ia32 10.0.15063

---

I'd like to be able to share a `.code-workspace` file in a Git repo. For that, the file paths have to be relative. It seems this already _sort of_ works if you manually edit the file to use relative file URIs starting with `file:./`. However, that seems to make the path relative to the VSCode installation dir, rather than the directory that contains the workspace file:

![](http://i.imgur.com/p1HnRg0.png)

```json
{
	"id": "1500632094036",
	"folders": [
		"file:./TestProject"
	]
}
```

**Comment by bpasero** [comment]
Yes, this is planned for the future. I find the syntax interesting to use file protocol with a relative path, @jrieken could maybe advise if this is OK to do instead of just having a relative path in there. What I like about keeping it a file URI is to know that this is a resource on disk.

**Comment by jrieken** [comment]
> @jrieken could maybe advise if this is OK to do instead of just having a relative path in there. What I like about keeping it a file URI is to know that this is a resource on disk.

Yep, that is valid uri and should be parsed into `{scheme: file, path: ./TestProject}`. Just make sure to normalise and resolve them *early* before passing it around. Actually the same is true for `file:///User/foo/../bar/./far` etc etc

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/33097
