### ISSUE TITLE
advise setting of encoding

### ISSUE THREAD

**Issue by ruan11223344** [Microsoft/vscode#31205]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.advise setting of  ' "files.autoGuessEncoding": false,'  on windows value is true.
2.thank you.

**Comment by bpasero** [comment]
@ruan11223344 can you explain what you mean?

**Comment by ruan11223344** [comment]
In windows I opened a GBK character encoding contains the txt file, the document shows the garbled I must manually set the character encoding for gbk, the text can show normal

**Comment by King66** [comment]
I think this is a feature request, he want the default value of "files.autoGuessEncoding" is true.

@ruan11223344 
you can set "files.autoGuessEncoding": true by yourself.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23417
