### ISSUE TITLE
Visual Studio Code bug

### ISSUE THREAD

**Issue by haimereyes2** [Microsoft/vscode#31204]
Im new to web development and I just installed Visual Studio Code. I installed some extensions. I'm bothered and annoyed when suddenly some very long text automatically inserted in my code. It start in the end tag of html(). It is very long so im just gonna show here some of it.

when encoutered I just delete it but it comes back every a couple of minute or so. Please help I do not know what to do to fix/avoid/stop this.

Kindly view my attached photo to see what im talking about.
![1](https://user-images.githubusercontent.com/30342527/28461143-d4825b86-6e47-11e7-8eaf-80d1f5b34032.PNG)
![2](https://user-images.githubusercontent.com/30342527/28461141-d4808c8e-6e47-11e7-8af2-840f9dc15bae.PNG)
![3](https://user-images.githubusercontent.com/30342527/28461142-d481ed7c-6e47-11e7-9f4c-6195e09702c3.PNG)
![5](https://user-images.githubusercontent.com/30342527/28461144-d48b40a2-6e47-11e7-82f8-a78c3f378704.PNG)

**Comment by isidorn** [comment]
One of you extensions is doing that. Please delete all extensions and add them one by one to figure out which extension is to blame.
Thanks
