### ISSUE TITLE
JSX: Highlight tag-definition when selecting usage

### ISSUE THREAD

**Issue by misantronic** [Microsoft/vscode#31201]
- VSCode Version: 1.14.2
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Define a Component like `const Button = () => <button/>`
2. Reference it e.g. in the `render` function
3. Select it via mouseclick

Reproduces without extensions: Yes

Highlighting works:

![screen shot 2017-07-21 at 12 24 08](https://user-images.githubusercontent.com/6033531/28459855-8fab7052-6e0f-11e7-99c5-73a0faca2bba.png)

Highlighting doesn't work:

![screen shot 2017-07-21 at 12 24 45](https://user-images.githubusercontent.com/6033531/28459874-a09bac38-6e0f-11e7-8155-58e478b19e17.png)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/17350 to track this upstream
