### ISSUE TITLE
[Feature request] Setting Syncronization

### ISSUE THREAD

**Issue by rungtrucxanh1997** [Microsoft/vscode#31209]
Dear VS Code Dev Team

I always use many different PCs, and each time I want to add/change some settings/snippets/extensions/keyboard shortcuts/etc,  I have to do the same thing in all the PCs. It's kinda unfavorable. 
So I hope you, The VS Code Dev Team will make things easier for me (And everyone else of course) <3 

From VN with hope  ɛɝ
Gấu

**Comment by isidorn** [comment]
FYI There is already a extension that deos this
