### ISSUE TITLE
Window title bar doesn't show correct folder when swapping folders

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#31218]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|0.6.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
python|don|0.6.8
EditorConfig|Edi|0.9.4
matlab|Gim|0.5.0
triggertaskonsave|Gru|0.1.2
vscode-dimmer|hoo|2.1.0
docthis|joe|0.4.7
select-part-of-word|mle|1.0.1
cpptools|ms-|0.12.1
indent-rainbow|ode|0.6.1
vscode-clearcase|Ope|1.10.0
vscode-icons|rob|7.10.1
indenticator|Sir|0.4.2
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.0
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Load a different folder (I used File, Open Recent)
2. The window title bar still shows the <original folder> - <file in that folder>
3. Clicking on a file fixes it. Not sure if always does. I think it may get stuck not updating.
4. Clicking on a file tab rather than in the file (sometimes) doesn't change the window title.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Closing as duplicate, already reported.
