### ISSUE TITLE
npm script not detected if the package.json is not in root folder

### ISSUE THREAD

**Issue by lski** [Microsoft/vscode#31217]
- VSCode Version: 1.14.2
- OS Version: Win 10 (14393)

When the package.json file is in a sub folder of the one opened in VSCode (therefore not in the root), the tasks in the scripts section are not auto detected. I did test opening VSCode with the folder that contains the package.json file directly and the tasks were autodetected correctly, it just seems to be if its in a parent folder that the issue is caused.

This might be expected behaviour, although in the same project I had a tsconfig.json file in the same folder as package.json and it was detected in a subfolder when the package.json tasks were not detected. Ideally it would be better to autodetect in a sub folder like the tsconfig.json file does.

Steps to Reproduce:

1. Open VSCode with parent folder above the folder containing package.json (so its not in the root) 
2. Click task in menu bar
3. Click Run Task to get the list of auto detected scripts. List should not show the tasks from the scripts section of package.json

Reproduces without extensions: Yes

Thank you, apologies if I missed something

**Comment by craigbrett17** [comment]
Might it not be better to specify the rootDir of the package.json you're looking for in the task? Akin to the options object in other types of task.

**Comment by craigbrett17** [comment]
Actualy, trying this out, the path property doesn't seem to work even on specified tasks. May or may not be related. If not related, I'll add a separate issue.

**Comment by lski** [comment]
Sorry for not replying or adding information to this issue, I am in the middle of moving home and have very limited PC access for a couple of weeks.

**Comment by satoyan** [comment]
I have same problem.
My folder structure looks like below.
```
.
├── client
│   ├── package.json
│   ├── src
│   └── tsconfig.json
├── host
│   ├── package.json
│   ├── src
│   └── tsconfig.json
├── README.md
└── workspace.code-workspace
```

I have two TypeScript project each __client__ and __host__ directories.

I defined npm task each package.json(client and host).
Tasks I defined are very simple like this.

```
# host/package.json
"build": "parcel watch --no-hmr --no-source-maps src/main.ts",
```

```
# client/package.json
"build": "parcel watch --no-hmr src/main.ts"
```

I opend these projects with VSCode as multi-workspace-projects and I tried to show task list with ">Tasks: Run Task".
Unfortunately I could see only defaut tasks provided by VSCode not tasks I defined. This looks like this.
```
tsc:build - client/tsconfig.json
tsc:build - host/tsconfig.json
```

So I switched to open each one project with VSCode in the terminal.

```
cd host # or client
code .
```

And did the same thing as above.

Then I could see a npm task (npm:build) which I defined in package.json

I guess VSCode does not auto-detect npm tasks when it is opend as multi-workspace-projects.

Thank you.

**Comment by egamma** [comment]
The task provider is now searching for package.json file inside the workspace with the exception of node_modules. Additional exclusions can be defined using the npm.exclude setting.

**Comment by egamma** [comment]
To verify:
- create folder structure with package.json as described here https://github.com/Microsoft/vscode/issues/31217#issuecomment-368513047
- verify that scripts in a package.json in a subfolder are detected and provided when you execute `Tasks>Run Task`
- verify that you can exclude folders using the npm.exclude setting

**Comment by DanTup** [comment]
I think the problem of people having projects in sub-folders is much wider than just here. I've proposed that sub-folders should be able to be full-fledged WorkspaceFolders so they can have their own settings, debug configs, etc. here -> https://github.com/Microsoft/vscode/issues/45399

I think it'd solve a bunch of issues!

**Comment by jtokoph** [comment]
I think this has caused a regression in performance and usability in large repositories.

The change here https://github.com/Microsoft/vscode/commit/a6dde81592febe579a24ada7b0e6d63b15a37cfd#diff-3b21ed98f2447f0d29ed636bdcf00c98R103 is calling `vscode.workspace.findFiles` before checking if the main workspace settings have `npm.autoDetect` set to on/off.

In my large workspaces I have disabled all `npm.autoDetect` configuration options so that my default build task (cmd+shift+b) doesn't have to wait for vscode to look for all build tasks.

Before this change, my default build task started running immediately.
After this change, my default build task spends 20 seconds `Fetching build tasks...` before finally running my build script.

**Comment by jtokoph** [comment]
Github doesn't seem to link to diff lines properly, this is the line that I believe is causing the slowdown with a call to `vscode.workspace.findFiles`: https://github.com/Microsoft/vscode/blob/a6dde81592febe579a24ada7b0e6d63b15a37cfd/extensions/npm/src/main.ts#L103
