### ISSUE TITLE
Revert to old update process or make the gear more prominent

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [Microsoft/vscode#31215]
Please revert to the old update process via the notification bar. The "Lighter update experience" would be fine as a flag, but it's SO out of the way that I end up not noticing it for days.

So my request would be that the old notification is a toggle or the "gear" that houses the update notification be moved up next to the other icons on the side bar so that it's in my field of vision at a location that I'm used to looking.

**Comment by isidorn** [comment]
If you do not update for a couple of days we show a notification.
Closing as designed.

@joaomoreno fyi
