### ISSUE TITLE
Suggest wigets should react to mode changes.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3121]
To reproduce:

- open a first json file
- quickly request code complete (best done programmatically by executing the code complete command )
```typescript
this.keybindingService.executeCommand('editor.action.triggerSuggest');
``` 

Observe: the suggest widget is empty. The reason is that the json support now comes in through an extension that the json mode dynamically gets the suggest support. Since json starts a server this can take a while.

**Comment by joaomoreno** [comment]
The fix should happen in the promise chain from the suggest contribution through the mode to the extension.

**Comment by jrieken** [comment]
related to #6057
