### ISSUE TITLE
The cog hides new visual studio code updates too well

### ISSUE THREAD

**Issue by Jarrio** [Microsoft/vscode#31219]
- VSCode Version: 1.14.*
- OS Version: Windows 10

Since the update which added the cog I've already missed 2 versions as I just don't look at that region of the screen very much - It is *too* hidden and out of the way. I'm not sure what other people's experience is with this but I thought I would put it out there just in case people agree with me.

1) There's no real reason look in that region of the screen. Apart from updates, but it seems a bit odd to have people learn to consciously check just for updates as that can lead to distracting behaviour. 
2) I have a bigger than average monitor 1440p @ 27" which just hides the cog in so much more space. It is slightly easier to accidentally come across on a 1080p 15.4" laptop monitor but again it's not ideal.

If the optional settings approach isn't ideal, maybe some of these other solutions may be more appealing:

- Add a small notification to the extensions tab as well? With it being so close to the other menu options it would be easier to spot
- Move the cog above the `Finder` option and add a break line to separate it from the rest of the menu options
- Add a somewhat noticeable gradient to the menu bar when vscode has an update? Nothing too bright like red. But the idea is to draw your eyes to the cog with a noticeable change

This is more of a quality of life suggestion rather than a need, so other user feedback would benefit this post more than others.

**Comment by joaomoreno** [comment]
This is as designed, in order to reduce update noise.

If after 5 days you haven't updated we will show you the good old message at the top.

For further improvements in this area follow this issue: #13308
