### ISSUE TITLE
Git commit field should have a monospace font

### ISSUE THREAD

**Issue by marcoms** [Microsoft/vscode#31228]
As git commit messages are often constrained to a certain number of characters, it makes sense for the commit field to have a monospace font (and probably a ruler at a configurable position, like the editor), so each line can be aligned predictably.

It would be nice to extend monospace fonts to more things, like the command palette, which would fit more in line with the command-line metaphor (same as Atom)

**Comment by joaomoreno** [comment]
We used to have this before and went away from it. Although you are correct that messages are often constrained in length, they should always be proper prose. We take that attribute as the rule to make it non-monospace.

**Comment by marcoms** [comment]
The same could be said about markdown documents no? I don't see why having a monospace font will limit the quality of the message.

For me I end up having to use another tool like the CLI or another GUI just to make commits, because not being able to see how characters will line up makes vscode's UI really poorly-suited for working under a style guide that enforces line-widths.
