### ISSUE TITLE
Auto Indent - Indent After Enclosing Code In Block

### ISSUE THREAD

**Issue by g5codyswartz** [Microsoft/vscode#31229]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Start with code at a given indent
1. Wrap a block around the code (if/end, def/end)
1. Upon closing the block the inner code should auto-indent

I did test cutting and pasting it, the auto indent worked fine, so upon closing a block the same instruction needs to be ran. This is how other IDEs that behave if I recall correctly.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@g5codyswartz can you share part of your code snippet to help reproduce?

**Comment by g5codyswartz** [comment]
```
  def hello
  world
```
Then type `end`
 I would expect `world` to indent automatically after end is completed and runs it's auto indenting on it.

### Actual
```
  def hello
  world
  end
```

### Expected
```
  def hello
    world
  end
```

**Comment by rebornix** [comment]
For this feature, I'll suggest to use a formatter instead of the indentation adjustment, which is more stable and accurate and we can control when the formatting should be run, typing, pasting or saving.
