### ISSUE TITLE
clear terminal not working after upgrade to 1.14.2

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#31223]
Clearing the terminal is not working. I found #30533 in issues, but as the issue is from 8 days ago and mine was working with `1.14.1` I'm creating a new issue.

- VSCode Version: 1.14.2
- OS Version: windows 10

Steps to Reproduce:

1. use bash.exe as the terminal (MINGW64_NT-10.0)
2. run some commands and try to clear the terminal

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Was it just a one off thing? It would surprise me if this was a regression in 1.14.2 as nothing happening with the terminal from 1.14.1 https://github.com/Microsoft/vscode/milestone/49?closed=1

**Comment by sfabriece** [comment]
Everything is suddenly working fine today.
