### ISSUE TITLE
VSCode Insiders not added to context menu after automatic upgrade to 64 bit version

### ISSUE THREAD

**Issue by fjsuarez** [Microsoft/vscode#31226]
- VSCode Version: 1.15.0-insider x64
- OS Version: Windows 10 Version 1703 Build 16241.1001

Today VSCode Insiders asked me if I wanted to upgrade to the 64 bit version. I clicked on yes and apparently the download started on background. After some time, a number showed up on top of the Gear icon on the bottom left corner (updates available). After selecting restart and install updates, it first uninstalled the current version and then it installed the 64 bit version. The process executed and completed automatically, there were no prompts.
App runs normally so far, but it was not added to the context menu in Explorer.

**Comment by iursevla** [comment]
Same problem here.
