### ISSUE TITLE
Incorrect JavaScript syntax highlighting

### ISSUE THREAD

**Issue by venning** [Microsoft/vscode#31230]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ansible|haa|0.2.5

---

Steps to Reproduce:

1. Create new file
2. Select "JavaScript" Language Mode
3. Enter the following into the file:

```javascript
var foo = {
    'anything quoted': '(anything starting with an left parenthesis or angle bracket'
};

// comment highlighted incorrectly "highlighted like a string literal (incorrect)"
var highlightedIncorrectly;
```

Reproduces without extensions: Yes

---

### Problem

Creating an object that has a value that is a single-quoted string that starts with a left parenthesis `(` or left angle bracket `<`, causes all following code to highlight incorrectly.

I thought this was related to #30425, but 1.14.2 didn't fix it.

---

### Base case

Starting with the following base case that highlights all following code incorrectly:

```javascript
var foo = {
    'hello': '(world'
};
```

Certain changes will fix or not fix the subsequent syntax highlighting problem, as detailed here:

### Cases that will highlight correctly

```javascript
// double-quoting the object value
var foo = {
    'hello': "(world"
};

// un-quoting or double-quoting the object key
var foo = {
    hello: '(world'
};
// or
var foo = {
    "hello": '(world'
};

// not starting the value with the left parenthesis
var foo = {
    'hello': 'world('
};

// using a left curly bracket or left square bracket instead
var foo = {
    'hello': '{world'
};
// or
var foo = {
    'hello': '[world'
};
```

### Cases that will *not* highlight correctly

```javascript
// using a left angle bracket instead
var foo = {
    'hello': '<world'
};

// closing the paren in the object value
var foo = {
    'hello': '(world)'
};

// adding properties to the object
var foo = {
    one: 1,
    'hello': '(world',
    "stuff": 'things'
};

// using an expression instead of an assignment statement
foo = {
    'hello': '(world'
};
// or
({
    'hello': '(world'
});

```

All of these register as valid code (no errors reported), but do not highlight the following code correctly.

---

For what it's worth, the use case that provoked this was a lookup map for brackets:

```javascript
var pairs = {
    ')': '(',
    '}': '{',
    ']': '['
};
```

**Comment by mjbvz** [comment]
This should already be fixed in insiders: https://code.visualstudio.com/insiders

You can also install the latest ts/js grammar in 1.14: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by venning** [comment]
@mjbvz That fixed it.  Thank you.
