### ISSUE TITLE
Feature request: Go to method declaration

### ISSUE THREAD

**Issue by alvinsight** [Microsoft/vscode#3123]
Hi everyone, 
Thanks for the work on this editor and its open nature, it's a really good move from Microsoft, and a promising one.

The only 2 things missing from my point of view are: 
- a proper settings panel, I understand that it is not trivial, but it's something I guess people could get used to not have, so it's not what this issue is about.
-  a go-to-function shortcut, I find the ability to jump to a function by pressing Ctrl + R invaluable, and it's supported by Atom too, so it shouldn't be too much of a hassle to find the right package in the atom repo and port some of the code, I think a lot of people will find it useful too.

So it would be great to get it implemented!

Thank you in advance, 
Alvin

**Comment by egamma** [comment]
Thanks for your kind words.

>a proper settings panel,
This is a feature request we already have, thanks.

>a go-to-function shortcut
did you try ctrl-shift-0? You can rebind this key to if desired.

>so it shouldn't be too much of a hassle to find the right package
Not sure I understand, there is no common code between Atom and VS Code except the underlying Electron framework.

**Comment by alvinsight** [comment]
Hi, 
Thanks for the quick reply, I just tried Ctrl + shift + o which doesn't work properly for me, using the same JS file I can only go to the constructor in Visual Studio, whereas Atom and Sublime allow me to go to the declaration of each method/ function in this file.

I was taking about Atom in case it would be useful for you to have a look at how they parse the file to extract the statements.

Thanks,
Alvin

**Comment by avidas** [comment]
Is there any update on supporting this functionality similar to Atom in vscode?

**Comment by crucialfelix** [comment]
"goto definition" is the command to go to the definition of the word under the cursor. You can map that to a key command.

shift-command-O (on mac) is to quickly search and go to a definition on the current page.

**Comment by Rafeethu** [comment]
@alvinsight ctrl+shift+o will work similar to ctrl+r in sublime if you install language support. for me it start working after installing php language extension.
