### ISSUE TITLE
Feature request: split gulp build into multiple processes

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode#31239]
I doubt gulp supports this, but it would be great if the `gulp watch` build task could be split into multiple processes. For example, I imagine the extensions could be built the same time that the rest of the source is built.

Maybe if there was a way, two gulp processes could be spawned, then waited upon before tasks dependent upon those two are run.

This is because on my system, the initial steps before incrementally building the modified typescript files seems to take very long.

**Comment by joaomoreno** [comment]
`gulp --tasks` shows you that we have at least the following tasks: `watch-extensions`, `watch-client`.

**Comment by rianadon** [comment]
Oh thanks! I didn't know about those.

And since there are already two separate tasks it would be nice if `gulp watch` ran them both in two separate processes rather than doing `watch-client` after `watch-extensions`.

However the compilation still takes some time. Would it be possible to further split up the watch tasks, maybe by the `editor`, `platform`, or `workbench` folders if they aren't dependent on each other? Or if they are, maybe split them between the electron main process & render process?
