### ISSUE TITLE
Fedora & DNF minor changes.

### ISSUE THREAD

**Issue by concatime** [Microsoft/vscode#31236]
Just an enhancement for Fedora. Now, we can add a repo file directly from dnf.
```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo dnf config-manager --add-repo https://gist.github.com/concatime/0b3f579a7812045069b6dcacfc0f239a/raw/vscode.repo
```
The second line will add the file from the link to ` /etc/yum.repos.d/vscode.repo`.
**The path file needs to finish with `.repo`.**
So It could be nice If You provide the link to the file and update the wiki/setup page.

Sources:
> https://docs.fedoraproject.org/en-US/Fedora/23/html/System_Administrators_Guide/sec-Managing_DNF_Repositories.html
https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

**Comment by Tyriar** [comment]
This would not support distros that only have `yum` though, I don't think it's time to drop support for `yum` yet.

**Comment by concatime** [comment]
Well, actually, you can also use `yum-config-manager` like [here](https://negativo17.org/nvidia-driver).
