### ISSUE TITLE
Request: make help > about text selectable

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#31237]
Since it's useful to report the exact commit that have an issue, could make the text inside the about dialog selectable, so it can be copied and pasted

**Comment by isidorn** [comment]
It is selectable for me, what platofrm are you using?

**Comment by pocesar** [comment]
Windows 10 x64, doesn't select for me on both insiders and stable

**Comment by isidorn** [comment]
Yes this is simply how electron is rendering this dialog, this is not under our control unforutnetely. You can file it against electron

**Comment by pocesar** [comment]
maybe change the dialog to an HTML modal?

**Comment by pocesar** [comment]
pressing Ctrl + C in the screen copies the text to the clipboard
