### ISSUE TITLE
open in terminal fails with TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#31235]
- VSCode Version: 81e812c x64
- OS Version: Windows 10 x64

```
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

![image](https://user-images.githubusercontent.com/461084/28487391-746d0c5a-6e65-11e7-94ca-bf4370b0c6d7.png)

Steps to Reproduce:

1. Right click any file and choose "Open in terminal"

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I'll fix try this up before the next build on Sunday evening.

/cc @cleidigh

**Comment by cleidigh** [comment]
@Tyriar 
just saw this , sounds like a separate issue from the hyperlinks within the terminal.
Will re-sync once you do a commit...

**Comment by Tyriar** [comment]
@cleidigh I think it's related to the bottom padding
