### ISSUE TITLE
Feature Request: Highlight regex groups

### ISSUE THREAD

**Issue by xobust** [Microsoft/vscode#31249]
I was doing a advanced regex replace in VSCODE yesterday and i could see that what i wanted to replace got selected, but i kept messing up the grouping. 
It would be nice if the different groups could be highlited in diferent collors like on https://regex101.com/

**Comment by rebornix** [comment]
It would be a cool feature.

**Comment by xobust** [comment]
@rebornix  How can I help out? If you give me some guidance I can try to implement it.

**Comment by rebornix** [comment]
@xobust the entry file for Find Widget is https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/findWidget.ts , you can play around with it to get some ideas from it.

This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. If you have some prototype or so about this feature, we can then re-open it.

Thanks for understanding and happy coding!
