### ISSUE TITLE
< and > history navigation within the active tab

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#31242]
I have been using VS Code for a few months now (switched over from Sublime 3), and I have to say that this IDE is really easy to work with and configure! Bravo to the dev team, really appreciate your hard work!

Now, I have Feature Request after having used it for a while:

When you single-click on a file in the project explorer, it will open in the existing tab if no changes have been made to the file or it was not opened with a double-click. When I am navigating about the files in my project, I often only have 1 or 2 files that I am currently editing, several files open in other tabs and one tab that I am using to browse other files. When you have a really long list of files in the explorer, sometimes going back to a file you had open in the tab after <kbd>Ctrl</kbd>+`Left Click`ing into a definition or simply browsing a bit can be a PITA.

Opening files like this in the current tab is great to avoid clutter, but wouldn't it be cool if we had Forward `>` and Back `<` text icons that sat in the same bar as the menu, but adjusted to the position of the currently opened tab? Maybe something like this?

![screenshot_20170722_155327](https://user-images.githubusercontent.com/2549985/28489192-9c62811c-6ef7-11e7-8e90-395c7626862d.png)

**Comment by LachlanArthur** [comment]
You can use the "Go Back" and "Go Forward" commands to move the cursor between its historical positions.

These commands are found in the Go menu.

Their hotkeys are (go back, go forward):
Windows: Alt+Left, Alt+Right
macOS: Ctrl+-, Ctrl+Shift+-
Linux: Ctrl+Alt+-, Ctrl+Shift+-

**Comment by Panoplos** [comment]
I certainly know these hotkeys exist, but they function slightly differently to what these buttons would seek to achieve. With the hotkeys, you are also dealing with cursers in and around different files. These buttons would be solely dedicated to navigation in the current tab, and have nothing to do with the cursor, like the forward and back buttons in a browser.

**Comment by bpasero** [comment]
@Panoplos did you try `Ctrl+Tab` to jump between recently opened tabs?

**Comment by Panoplos** [comment]
<kbd>Ctrl</kbd>+<kbd>tab</kbd> does let you navigate between open tabs, but that is not what I am suggesting. ;^)

There is a working tab, denoted with the file name in _italics_. This tab is used to navigate through newly opened files and jump-to-definition. As I am constantly going back and forth in these, it would be cool to have Go Back and Forward solely for the purpose of navigating back and forth between **files** in the working tab, not **cursor positions**, which can often times take you out of the working tab.

**Comment by bpasero** [comment]
@Panoplos I see, so this navigation would go through every file that was opened in that exact tab

**Comment by bpasero** [comment]
@Panoplos you could try Ctrl+Q instead for navigating between files you had recently open. However, this will not scope to the active tab alone but any file you opened.

**Comment by lobsterkatie** [comment]
Seconding this request (and thirding and fourthing and fifthing, etc if I could...)

I, too, have come over to VSCode after many years with Sublime, and am overall really enjoying the experience. However, one consistent frustration is that sometimes, as I'm browsing through files, I forget to double click to make the tab "permanent." I then go do a few other things, and start to browse through files again. The first file I browse to replaces whatever "non-permanent" tab I had open and often enough I'm like, "Shoot! I needed that file! What was it? Oh, I know, I can go back... oh, wait, damn, that just took me to whatever other file I was just editing, not whatever file this tab used to have open. Drat, now I've lost that file. :-/"

Forward and back ought to work just like they do in a browser - each tab has its own history.

**Comment by bpasero** [comment]
Really, Cmd/Ctrl+Q is the only shortcut you need to go back, it does not matter if the file was pinned or not. Everyone in the team is using it, I suggest to give it a try.
