### ISSUE TITLE
CTRL K + CTRL F is not working anymore if you have JS file

### ISSUE THREAD

**Issue by Lacika1981** [Microsoft/vscode#31244]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:12:01.887Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-auto-open-markdown-preview|hnw|0.0.4
debugger-for-chrome|msj|3.1.6

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
What is expected to happen, what does not happen?
Can you repro without extensions?
