### ISSUE TITLE
[css] @imports with media queries show syntax errors

### ISSUE THREAD

**Issue by lyonzy** [Microsoft/vscode#31240]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vs-code-xml-format|fab|0.1.5
ejs-language-support|Qas|0.0.1

---

Steps to Reproduce:

1. Put this in a CSS file:
`@import url('mobile.css') (screen and max-width: 700px);`
2. VS Code shows red squiggly underlines

Reproduces without extensions: Yes

**Comment by lyonzy** [comment]
This seems be the same for most forms specified [here](https://stackoverflow.com/questions/14943719/import-styles-not-working-in-a-media-query):
 - `@import url("/inc/Styles/full.css") (min-width: 940px);`
 - `@import url(style.css) (screen and min-width:600px);`
 - `@import url("./700.css") only screen and (max-width: 700px);`

**Comment by lyonzy** [comment]
This is the error:

![image](https://user-images.githubusercontent.com/11625419/28488679-0acaed88-6ef3-11e7-9a79-38f4ddc4180d.png)

**Comment by ramya-rao-a** [comment]
Now I see a `) expected` error

![image](https://user-images.githubusercontent.com/16890566/30939440-47c19c9a-a392-11e7-9078-a2681dd353dd.png)

**Comment by aeschli** [comment]
`@import url('mobile.css') (screen and max-width: 700px);` is actually invalid.
It has to be `@import url('mobile.css') screen and (max-width: 700px);`

See the spec here: https://developer.mozilla.org/en-US/docs/Web/CSS/@import.
or check here: https://jigsaw.w3.org/css-validator/#validate_by_input
