### ISSUE TITLE
High CPU with all plugins disabled!

### ISSUE THREAD

**Issue by turtlegood** [Microsoft/vscode#31245]
- VSCode Version: 1.14.2
- OS Version: Win10 Home Version

Steps to Reproduce:

1. Open VSCode.
2. Then ~30% cpu is used by `Code.exe`. (4 core cpu)

Reproduces without extensions: Yes!

**Comment by turtlegood** [comment]
More details: the process having 30% cpu is:

    "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/fzyzcjy/AppData/Local/Microsoft/TypeScript/2.4 --enableTelemetry

@bpasero Anyone can help? I would appreciate it if you could offer some help!

**Comment by mjbvz** [comment]
Hey, sorry this fell of my radar.

Please let me know if you are still seeing this in VS Code 1.18 with TypeScript 2.6
