### ISSUE TITLE
zsh theme  fonts not working in vs code terminal

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#31254]
![image](https://user-images.githubusercontent.com/1202528/28491652-f0f97634-6ec2-11e7-8568-9e6433124715.png)

macOS 10.12.5 Sierra

I'm not sure if this is a zsh thing or a Code thing … see how my terminal using zsh and its theme looks? Notice vs code? Is there a setting to say “hey, use the font that the terminal uses” ?

![image](https://user-images.githubusercontent.com/1202528/28491648-e32fbc16-6ec2-11e7-9a40-6ab7af8e6782.png)

cc @chrisdias

**Comment by Tyriar** [comment]
@johnpapa does setting the font in your settings.json like this work? https://github.com/Microsoft/vscode/issues/15119#issuecomment-259248159

**Comment by johnpapa** [comment]
Yes, thanks! didnt see that before
