### ISSUE TITLE
Line unindents when typing in regexp literal (JavaScript)

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#31256]
- VSCode Version: 1.14.2
- OS Version: 10.12.5

![vsc](https://user-images.githubusercontent.com/50314/28492013-163f9ad0-6efb-11e7-999c-96ef4098b37e.gif)

Steps to Reproduce:

* Have this code:

```javascript
it('something', () => {
  expect(path.basename(appender.fileName)).toMatch(/^dingbat-./);
});
```

* Type `*` inside the regexp.
* Line will be unindented (!).

Also this — same issue, probably:

* Start with this line (indented by _one_ space) as the only contents of the file:

```javascript
 expect(path.basename(appender.fileName)).toMatch(/^dingbat-./);
```

* Try typing `*` inside the regexp. VSCode won't let you (!). It seems related to the fact that the line is the first line in the file.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
This issue is already fixed. Pressing * will not lead to an indent adjustment.
