### ISSUE TITLE
Results failt to display correctly when searching for ^$

### ISSUE THREAD

**Issue by retep998** [Microsoft/vscode#31252]
- VSCode Version: 1.14.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use find in files, enable regex, and search for `^$`

Reproduces without extensions: Yes

![](http://i.imgur.com/W0Fa2ui.png)

Installed extensions
![](http://i.imgur.com/jO8IiC4.png)

Sometimes only some of the results display incorrectly and after a certain point in the list it is fine again.

**Comment by roblourens** [comment]
Filed upstream: https://github.com/BurntSushi/ripgrep/issues/599

**Comment by roblourens** [comment]
Just need rg 0.7.0 for this
