### ISSUE TITLE
Autoindent on paste causes wrong indentation (JavaScript)

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#31255]
- VSCode Version: 1.14.2
- OS Version: 10.12.5

![vsc](https://user-images.githubusercontent.com/50314/28491967-3cbc6464-6efa-11e7-94d0-36c42133fcef.gif)

Steps to Reproduce:

* Take this code:

```javascript
something(() => {

  42;

});
```

* Copy it and try pasting it before the said block.
* The inner lines will be indented too much:

```javascript
something(() => {
  
    42;
  
  });
  something(() => {

  42;

});
```

Notice that the end of the block will also contain an indent.

Reproduces without extensions: Yes

**Comment by gotofritz** [comment]
Yes, even selecting a multiline block of text, cutting it, then pasting it back exactly where it was without moving the cursor adds an extra indentation

    function blah() {
       let a = 1;
      console.log(a);
   }

select from "let..." to "...(a);"
cut it CMD-X
don't move the cursor
paste it CMD-V

    function blah() {
         let a = 1;
         console.log(a);
   }

Now the pasted code snippet has an extra indentetation

**Comment by rebornix** [comment]
No longer see this issue with latest version with both issues described above.

![31255](https://user-images.githubusercontent.com/876920/45785716-3b9f3680-bc22-11e8-8ebc-50281e443a70.gif)

![31255-1](https://user-images.githubusercontent.com/876920/45785721-3e9a2700-bc22-11e8-8f81-53f44351e809.gif)
