### ISSUE TITLE
Error message no Build Task found, when there is a build task defined in the task.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31250]
I've added an attribute to the taskDefinition of the npm task provider:

```json
    "taskDefinitions": [
      {
        "type": "npm",
        "required": ["script"],
        "properties": {
          "script": {
            "type": "string",
            "description": "The npm script to customize"
          },
          "path": {
            "type": "string",
            "description": "The path to the folder of the package.json file that provides the script. Can be ommitted."
          }
        }
      }
    ]
```

Notice that the property `path` is not defined as a required property.

This is the code to create the task definition:

```typescript
	let kind: NpmTaskDefinition = {
		type: 'npm',
		script: script,
		path: rootPath
	};
```

In our [smoke test repository](https://github.com/Microsoft/vscode-smoketest-express.git) we have a setup with an existing task.json file with this contents, that defines a build task:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "eslint",
            "problemMatcher": {
                "base": "$eslint-stylish",
                "fileLocation": "absolute"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Running Tasks>Run Build Task... results in:

![image](https://user-images.githubusercontent.com/172399/28462595-27b62728-6e1c-11e7-810c-f5306c126919.png)

The error message should be more specific and tell that the build task was found but that the definition has issues. However, since the property  `path` is not required property, I would have expected that the task the existing build task still works. 

So there appear to be two issues:
- the non-required property in the task definition is not properly handled
- the error message is misleading.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/31970
