### ISSUE TITLE
[snippets] Support snippet contribution on a specific file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3125]
I would like to contribute snippets to .vscode/tasks.json. However currently I can only contribute snippets using the snippet extension point on a language mode.

**Comment by felixfbecker** [comment]
I think an additional `filter` setting would be nice, that accepts a glob. So snippets (custom ones too) could be scoped to `tasks.json`, `package.json`, `.vscode/*.*`, `gulpfile.*`, etc etc

**Comment by aeschli** [comment]
@dbaeumer  This is about completion in task.json, right?
The mechanism for that are the default values in the task.json schema. The variable syntax ('{{..}}' is supported there as well. If what we have is not good enough, then we should rather extend the support there. Snippets are not context sensitive.

**Comment by felixfbecker** [comment]
@aeschli it's not about default values for keys, it's for entire snippets, for example an entire task configuration for a build task that a language extension can contribute

**Comment by dbaeumer** [comment]
@aeschli I would for example like to insert the following lines:

```json
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["-p", "."],
    "problemMatcher": "$tsc"
```

How would I do that with default values and how would I provide more than one default value the user can pick from ?

**Comment by aeschli** [comment]
@dbaeumer  Schemas now support a 'defaultSnippets' property.
Check out src/vs/workbench/parts/snippets/electron-browser/snippets.contribution.ts, line 135.
It's an array of snippets, using our internal snippet syntax ({{...}}). label and description are optional.
You can add them top level, but also for arrays and objects deeper down in the JSON structure..

Let me know if that suits your needs.

**Comment by waderyan** [comment]
:+1:

**Comment by jrieken** [comment]
@dbaeumer Is this still needed given @aeschli's support for default snippets in schemata?

**Comment by dbaeumer** [comment]
I started using the default snippet support from the JSON schema.
