### ISSUE TITLE
Arrow keys no longer work.

### ISSUE THREAD

**Issue by manifolded** [Microsoft/vscode#31259]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
php-debug|fel|1.11.1
cpptools|ms-|0.12.1
debugger-for-chrome|msj|3.1.6
python|tht|0.2.3

---

Steps to Reproduce:

1.  Open source code.
2.  Attempt to navigate source code with the four arrow keys.
3.  Note the failure of any navigation to occur.

Reproduces without extensions: Haven't attempted.

**Comment by manifolded** [comment]
I'm now finding that my return key and space bar only work when I hold down shift.  The same is true of the arrow keys, but of course this causes them to produce a selection which is not what I want at the moment.

**Comment by isidorn** [comment]
Please try reproducing if you disable all extensions. Thank you

**Comment by manifolded** [comment]
The next time I went back and started up VS Code all the keys worked just fine.  I am unable to reproduce the problem, even with the extensions remaining enabled.  As far as I can tell this problem only occurred the first time I started the software after I upgraded to this latest version.  Sorry I'm unable to provide any better details.

**Comment by isidorn** [comment]
Then closing until more details are provided. Thanks
