### ISSUE TITLE
How get/change from api shape/color in place inline after number (near break point)

### ISSUE THREAD

**Issue by szechem** [Microsoft/vscode#31258]
I writing an extension. On API page of VSC, i don't find a solution for change/set/get/update the color of shape in line after a number of the line. And how to call the element of Visual Studio Code, where the number is shown, left the bar ?

**Comment by aeschli** [comment]
You mean the the 'gutter'.
![image](https://user-images.githubusercontent.com/6461412/28878780-96752a5a-77a0-11e7-8638-8b6de14a945e.png)

What exactly do you want to define? Can you add a screenshot?

**Comment by aeschli** [comment]
Closing due to lack of information.
