### ISSUE TITLE
error C2397: conversion from 'intmax_t' to '::size_t' requires a narrowing conversion should be warning

### ISSUE THREAD

**Issue by jmichae3** [Microsoft/vscode#31265]
stackoverflow.com licenses all content with with CC by SA.

- VSCode Version:???how?
- OS Version:windows 7 sp1 retail x64

error C2397: conversion from 'intmax_t' to '::size_t' requires a narrowing conversion
Steps to Reproduce:
intmax_t i=-1LL;
size_t n=i;

Reproduces without extensions: Yes/No

**Comment by jmichae3** [comment]
this should be a warning, not an error. isn't there something about that in the ISO standard?

**Comment by isidorn** [comment]
Please file this agains the C++ extension or to the language extension you are using. Thank you
