### ISSUE TITLE
Command to send literal key press to terminal

### ISSUE THREAD

**Issue by mikelward** [Microsoft/vscode#31262]
Originally https://stackoverflow.com/questions/45257525/ctrlc-inside-vscode-terminal

Inside the integrated terminal, I'd like to be able to make `Ctrl+C`/`Ctrl+V` copy and paste, and have `Ctrl+Shift+C` and `Ctrl+Shift+V` send literal `Ctrl+C`/`Ctrl+V`.

I can do the first two by setting custom key bindings for `workbench.action.terminal.copySelection` and `workbench.action.terminal.paste`.

It looked like maybe I could do the second two using `workbench.action.terminal.sendText`, but when I try it I get `command 'workbench.action.terminal.sendText' not found`, presumably because it's not defined in `terminalActions.ts`.

And if it was available as a command, I'm not sure how I'd pass arguments, or specify control characters.  I would try something like:

       {
            "key": "ctrl+shift+c",
            "command": "workbench.action.terminal.sendText",
            "args": ["\003", false],
            "when": "terminalFocus"
        }

but maybe something more explicit would be better.

**Comment by raphadko** [comment]
This would be incredibly useful for running all sorts of commands in the terminal. For example I would like to create a macro to switch to terminal and run the last command I ran (CTRL + P) or (arrow up), currently I can't find a way to do this.

**Comment by Tyriar** [comment]
This is actually a pretty great idea that I hadn't thought about before. There issue for this is https://github.com/Microsoft/vscode/issues/11314, I'm going to copy over your comment to there.

**Comment by Tyriar** [comment]
Let's continue the discussion there
