### ISSUE TITLE
Issue while Debugging

### ISSUE THREAD

**Issue by racterub** [Microsoft/vscode#31261]
- VSCode Version:1.14.2
- OS Version:Windows 10 build 1703

Steps to Reproduce:

1.Into Debug Mode
2.While running python through `import` command, is will also step info module's function.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1112

**Comment by weinand** [comment]
Python debugging is not part of VS Code, it is provided by separate extension.
