### ISSUE TITLE
Debugger does not return pointer in powershell when using call operator (&)

### ISSUE THREAD

**Issue by mohakraaj** [Microsoft/vscode#31264]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
xml|Dot|1.9.2
intellij-idea-keybindings|k--|0.2.12
MagicPython|mag|1.0.11
mssql|ms-|1.1.0
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6
PowerShell|ms-|1.4.1
resharper9-keybindings|ms-|1.1.0
vscode-docker|Pet|0.0.16
python|tht|0.2.3

---

Steps to Reproduce:

1. Start debugging powershell script 
2. If script has '&' operator, debug does not return pointer

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Powershell debugging is provided by an extension; it is not part of VS Code.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#968
