### ISSUE TITLE
useNewEmmet doesn't honor tab key in a specific usecase

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#31269]
- VSCode Version: 1.14.1
- OS Version: Windows 10 and OS X Sierra

## Problem

when `useNewEmmet` is set to true, Emmet expressions are only evaluated if the tab key is pressed immediately after writing an expression and do not work for an existing string.

## Steps to Reproduce:

1. Type an emmet expression but don't press tab immediately
2. Move the cursor to different lines and go back to the emmet expression
3. Pressing TAB will insert a TAB stop instead of evaluating an emmet expression

Demo : http://i.imgur.com/b1rTXsz.gif

**Comment by atif089** [comment]
Just found out that `useNewEmmet` disables auto-completion using the TAB key.

**Comment by ramya-rao-a** [comment]
https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list
