### ISSUE TITLE
vscode.startDebug with type "node" does not work, regardless of protocol

### ISSUE THREAD

**Issue by SAKryukov** [Microsoft/vscode#31266]
"vscode.startDebug" does not respect `type: "node2"` when the configuration supplies `type: "node"`, as it happens in the embedded extension for node.js debugging.

## Background

Visual Studio Code tracing shows that the embedded extension for node.js debugging actually uses `type: "node2"`, even when the auto-generated file "launch.json" provides `type: "node"`. Moreover, `type: "node"` if supplied to the "complex command" "vscode.startDebug" does not work anymore (see steps to reproduce below).

This is very confusing and not documented. The cases of "node2" and "node" should be merged to eliminate "node2". In worst case, this peculiarity should be thoroughly documented.

Related to [24762](https://github.com/Microsoft/vscode/issues/24762).

### 1) Try node.js debugging with "launch.json":

```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "program": "${file}",
            "protocol": "auto" // anything but "legacy"
            ],
        }
    ]
}
```
It does work.

### 2) Now, in some extension code:

```
        const launchConfiguration = {
            type: "node", // a real confusion! found by tracing Visual Studio Code
            name: "Launch Extension",
            request: "launch",
            stopOnEntry: false,
            protocol: "auto"
        };
        vscode.commands.executeCommand("vscode.startDebug", launchConfiguration);
```
It shows the error:
> [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead

Even when the protocol is specified explicitly, the problem is the same:

```
        const launchConfiguration = {
            type: "node", // a real confusion! found by tracing Visual Studio Code
            name: "Launch Extension",
            request: "launch",
            stopOnEntry: false,
            protocol: "inspector"
        };
        vscode.commands.executeCommand("vscode.startDebug", launchConfiguration);
```

By documentation and logically, the type "`node`" should work. See also below.

### 3) The workaround:

Change `type: "node"` to `type: "node2"`. It works. But this is not a real solution, because "officially", only `type: "node"` is supported. I do understand that operation with `type: "node2"` may eventually fail with some VSCode update.

## 
Reproduces without extensions: No (the problem appears in extension, more exactly)

**Comment by weinand** [comment]
Please use the new proposed debug API ["vscode.debug.startDebugging"](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L149). It has the identical semantics as a manual launch of a launch config. Specifically it will run the same code in the extension that probes for the node.js version and picks the correct implementation of the protocol.

The current "vscode.startDebug" command will be deprecated and replaced by the official debug API ["vscode.debug.startDebugSession"](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5477). This is the low-level API which should only be used by debug extension authors.

**Comment by weinand** [comment]
"vscode.debug.startDebugging" should be available in Monday's Insiders build as proposed API.

**Comment by SAKryukov** [comment]
Thank you, Andre.

It sounds really good.

I hope I can safely wait for *production* release, as my product is public. If the lifetime of temporary "code2" functionality overlaps with some beginning period of time after introduction of "vscode.debug.startDebugging" in a production release, new dependency records in my package will resolve the situation by requiring this newer VsCode version before 'code2" goes out of production.

Is it supposed to work this way? Can you give me a rough idea of a typical time frame for transition of a feature from Insiders to production?

Now, looking at the [proposed code](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L149) you pointed out: how about `getConfiguration2` and `WorkspaceConfiguration2`? Are they really supposed to stay with their "2" names?

Thank you.
—SA

**Comment by weinand** [comment]
@SAKryukov as you can see in "vscode.proposed.d.ts": `getConfiguration2` and `WorkspaceConfiguration2` are gone.

**Comment by SAKryukov** [comment]
Andre,

As of VSCode 1.15.0,  `vscode.debug.startDebugging(launchConfiguration)` does work, but it looks like having a defect.

when a configuration is passed as the parameter `launchConfiguration`, such as
```
const launchConfiguration = {
            type: "node",
            name: "Launch Extension",
            request: "launch",
            stopOnEntry: false,
            protocol: "auto"
        };
```
In this case, the UI request for launch configuration, a choice from the predefined list. despite the fact the configuration is already passed. When "node.js" is selected from the list, debugging starts to work. It stops working when launch.json file is prescribed in the target workspace, which is understandable though. Don't you think this is a defect which should be reported?

—SA

**Comment by weinand** [comment]
@SAKryukov sounds like a bug to me. Please file an issue.
