### ISSUE TITLE
Multiple RenameProviders for same language issue

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode#31268]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Description:
I would like to have a callback, which is set in an xml file, renamed when I rename the correlating method in my typescript file. So I wrote a custom `RenameProvider` and added it via `c.subscriptions.push(languages.registerRenameProvider({ language: "typescript", scheme: "file", pattern: "**/*.controller.ts" }, new CallbackRenameProvider()));`. 

ut my provider seems to override the result of the `RenameProvider` of the typescript extension. Is there a possibility to have them both coexist? The problem is, if the method is used in another method in the typescript files it will not be renamed there.

**Steps to Reproduce:**

1. Create a custom `RenameProvider` (for example for typescript)
2. Successfully return the `WorkspaceEdit`
3. Rename a method on a class and do some edits somewhere else

**Expected Result:**
The typescript rename provider should rename the symbol in the other file (in my example xml) and the symbol on the typescript class.

**Actual Result:**
The text in the other file does get renamed, but the method name stays the same.
If I deactivate my provider, it does get renamed.
It seems to me my WorkspaceEdit replaces the WorkspaceEdit provided by the typescript extension.

Please let me know, if you need some examples, then I can publish my extension and you can check it out yourself.

For now here is my repo:
https://github.com/apazureck/openui5vscodeTypescriptTools (checkout the develop branch, please)

And here is a test scenario:
https://github.com/apazureck/UI5TypescriptDeclarations/tree/master/generator (master branch)

**Comment by jrieken** [comment]
Today the first rename provider that is creating a valid rename result is the winner and we don't continue asking other providers. Honestly I also don't know that should work because if multiple rename providers are active at the same time conflicts are very to happen and I am not sure how to resolve those conflicts. 

It seems like you have a very special case which affects TypeScript and XML-files and I wonder if the monaco/vscode-api is the right layer or if you should be a plugin to the TypeScript server. There you can participate in the rename of a TypeScript symbol and perform other operations. For a sample see https://github.com/RyanCavanaugh/sample-ts-plugin

**Comment by apazureck** [comment]
OK, using the language server sounds like a reasonable alternative. Thank you for the hint.

I see the point it would be tough to prevent crashes between the Plug-Ins. But it would be possible to combine them and check if the uris and ranges are the same and otherwise prefer the first provider. But I don't see any need here.

But could you document this behavior in the vscode namespace API? I did not find any hint on that.

**Comment by jrieken** [comment]
> But could you document this behavior in the vscode namespace API? I did not find any hint on that.

We have a slightly weird way of [saying it](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5109-L5111): 

```
Multiple providers can be registered for a language. In that case providers are sorted
by their [score](#languages.match) and the best-matching provider is used. Failure
of the selected provider will cause a failure of the whole operation.
```

**Comment by apazureck** [comment]
Hi @jrieken,

Fair enough, I was a little bit ocnfused, as other providers are not working that way, but it makes sense. Thank you for your help there.

But I have another problem:

I would really like to use the vscode language server, as it reads the input and is better suitable to provide renaming. But I really do not get how I can do that.

I read the readme for the typescript language service plug-in and I have another question:

How would I be able to activate it in my vscode extension? As I understood I would have to manipulate the user's tsconfig.json being able to activate my plug-in at all. Is there some way to bind my plugin tothe already running typescript server of the typescript extension?

**Comment by jrieken** [comment]
@mjbvz is the expert on TypeScript and its plugins

**Comment by jrieken** [comment]
closing because no code change is planed
