### ISSUE TITLE
Action buttons for folder search result nodes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31260]
I think this is the only remaining task from https://github.com/Microsoft/vscode/pull/29964#pullrequestreview-51625410

> The action buttons are hidden for folders. Maybe could be done as a follow-up PR?
>> I think the folders should have action buttons, but I don't need everything in one PR.

@keegancsmith Would take a PR for this if you're up for it, otherwise I can do it.

**Comment by keegancsmith** [comment]
@roblourens Thanks for filing. I can tackle this, but will only have time at the end of this week / early next week if that is alright (I see you added to this months iteration milestone).

**Comment by roblourens** [comment]
That would be fine, thanks!

**Comment by keegancsmith** [comment]
@roblourens apologies, the other work on my plate is taking more time than I expected. I don't think I'll be able to address it this week.

**Comment by roblourens** [comment]
This is complete now, right?

**Comment by keegancsmith** [comment]
We are still missing the replace action on FolderMatch. However, that should be a much smaller PR (but requires more testing) than the above.

**Comment by roblourens** [comment]
Oh right, I'll leave this issue open for that.
