### ISSUE TITLE
Add keyboard shortcut for Intellisense full-text

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#3126]
Currently, when Intellisense text is too long to be displayed, the user must click the **(i)** icon to reveal the whole text:

![january_intellisense-1](https://cloud.githubusercontent.com/assets/9283914/13150666/11459e90-d667-11e5-8388-703dcd5de60f.png)

![january_intellisense-2](https://cloud.githubusercontent.com/assets/9283914/13150880/e3b9bf28-d667-11e5-8511-ebe8d7cb6ea2.png)
<br/>
It's rather cumbersome to be required to use the mouse or track pad for switching Intellisense content because the fingers are down on the keyboard when Intellisense comes into play.
<br/>
I propose to introduce a keyboard shortcut to switch between "preview" and "full" Intellisense mode. Hitting that keyboard shortcut would emulate clicking the **(i)** and **<-** icons, resp.

I suggest to use the `<CTRL> + <ARROW DOWN>` keyboard combination by default for the proposed functionality.

**Comment by egamma** [comment]
You can type <CTRL>+<SPACE> again to toggle between the completion list and the doc.

**Comment by SetTrend** [comment]
I'm not sure if I understand your answer correctly: Whenever I type `+`, a `+` character is added to the text, but Intellisense display mode is not gettinge changed.

I also noticed that neither `<CTRL> + <SPACE>` nor `<SHIFT> + <CTRL> + <SPACE>` pressed from within an existing function parameter list show the above Intellisense feature.

**Comment by egamma** [comment]
@SetTrend sorry markdown mistake... this is what I typed

>You can type <CTRL>+<SPACE> again to toggle between the completion list and the doc.

**Comment by SetTrend** [comment]
@egamma :

I'm very sorry for causing this trouble, but you need to put text containing angle brackets into code quotes, I'm afraid. Otherwise, GitHub deletes them as invalid tags:

```html
<p>You can type + again to toggle between the completion list and the doc.</p>
```

Would you mind repeating your reply and putting the keyboard shortcuts into code quotes?

**Comment by egamma** [comment]
tsss, sorry

You can type CTRL+SPACE again to toggle between the documentation and the completion suggestions.

**Comment by egamma** [comment]
so this is the way to do this :smile: 
<kbd>CTRL</kbd>+<kbd>Space</kbd>

**Comment by SetTrend** [comment]
Ahh.. works like a charm. Brilliant! :clap: :smile:

**Comment by MagisDing** [comment]
@egamma But `CTRL`+`Space` is set to switch input method by default on my Mac, is there a way to customize the shortcut for IntelliSense?

**Comment by egamma** [comment]
@MagisDing you can customize key bindings, see `Preferences>Keyboard Shortcuts` and then switch to JSON

``` json
{ "key": "ctrl+space",            "command": "editor.action.triggerSuggest",
                                     "when": "editorHasCompletionItemProvider && editorTextFocus && !editorReadonly" },
```
