### ISSUE TITLE
stopOnEntry not working

### ISSUE THREAD

**Issue by ewrayjohnson** [Microsoft/vscode#31267]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typings-installer|ben|0.2.0
jsrefactor|cms|1.3.0
typings-autoinstaller|jvi|1.2.0
debugger-for-chrome|msj|3.1.6
loopback-json-schemas|seq|1.0.0

The default "stopOnEntry' behavior has been changed to "stopOnEntry": true  and "stopOnEntry": false, set in launch.json is ignored.

---

Steps to Reproduce:

1. Run Node.js application in debug - note debugger stops on first line.
2. Edit lauch.json and add "stopOnEntry": false to the configuration.  Repeat #1

Reproduces without extensions: Yes

**Comment by crabicode** [comment]
@weinand same issue here

**Comment by weinand** [comment]
What version of node?

**Comment by crabicode** [comment]
@weinand v8.2.1

**Comment by weinand** [comment]
I cannot reproduce with this code:
```js
console.log("hello");
```
Debugging does not break on the first line if the launch config has no "stopOnEntry" attribute or if the value is set to false.

**Comment by crabicode** [comment]
@weinand,

My setup is the following,

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to node",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "smartStep": true,
      "restart": true,
      "sourceMaps": true,
      "stopOnEntry": false,
      "timeout": 60000,
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

When I connect to the running `node --inspect-brk bin/start.js`, it stops right at the first line disrespecting the value of `"stopOnEntry"`.

Any thoughts?

**Comment by crabicode** [comment]
@weinand,

Or don't I simply see the use case of "stopOnEntry" in my scenario.

**Comment by ewrayjohnson** [comment]
VSCode Version: Code 1.14.2

**Comment by roblourens** [comment]
Was an exception thrown? Can you share teh code?

**Comment by weinand** [comment]
Does it make a difference if you add a `"protocol": "inspector"` to your launch config?

**Comment by weinand** [comment]
@ewrayjohnson does it make a difference if you add a "protocol": "legacy" to your launch config?

**Comment by crabicode** [comment]
@weinand,

Stops on entry with:
`{ "protocol": "inspector", "stopOnEntry": true }`
`{ "protocol": "inspector", "stopOnEntry": false }`
`{ "protocol": "inspector", "stopOnEntry": false, "protocol": "inspector" }`

Node: v8.2.1, vscode 1.14.2

**Comment by crabicode** [comment]
@weinand,

If legacy:

`Cannot connect to runtime process (reason: This socket has been ended by the other party).`

Due to debugging node with inspector.

**Comment by weinand** [comment]
@ewrayjohnson how does your launch config look like?

**Comment by weinand** [comment]
@crabicode node 8.x no longer supports "legacy" protocol.

Please note: I suspect that the issue @ewrayjohnson is totally unrelated to the issue of @crabicode.
@ewrayjohnson uses node 7.4 (which uses the "legacy" protocol) and @crabicode uses node 8.2.1 (which uses the "inspector" protocol). The underlying debugger implementations are independent.
So it does not really make sense to discuss them in one issue.

@ewrayjohnson to be 100% sure: you are seeing this issue even if you add `"protocol": "legacy"` to your launch config (@crabicode: this question is irrelevant to you, please don't answer).

**Comment by ewrayjohnson** [comment]
You do not need to have the stopOnEntry setting.

Wray Johnson
(m) 704-293-9008

**Comment by roblourens** [comment]
In https://github.com/Microsoft/vscode-node-debug2/issues/144 I made some changes to prevent an issue like this. It's not totally fixed but if you're seeing the same thing, it may work more often. Let me know if it's still an issue.
