### ISSUE TITLE
code .  opens the current directory, code .. also opens the current directory - not the parent

### ISSUE THREAD

**Issue by jjmartin** [Microsoft/vscode#3127]
`code .`  opens the current directory, `code ..` also opens the current directory - not the parent

**Comment by Tyriar** [comment]
Repros on master. Also:

- `code ../..` opens `..`
- `code ../../..` opens `../..`
- etc.

**Comment by jjmartin** [comment]
i see the bug and the fix is in - i guess a short term work around is `code ../` opens the parent directory

**Comment by Tyriar** [comment]
@jjmartin yes the fix should be in the next release, adding a slash is a good work around in the meantime.

**Comment by deejayguess** [comment]
I hope something good happens here. cause the way things are going. pretty much saying microsoft has lost all control of windows
