### ISSUE TITLE
Problem that I can't ran my Python code correctly.

### ISSUE THREAD

**Issue by THINKmake** [Microsoft/vscode#31271]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9

---

Steps to Reproduce:

1.In my code,tha line raw_input('Something: ')
2.I just run code using 'F5',and it works.
3.But I can't put anything in the Debug console.
Details:
    Python 2.7 
    Example code:
        width = input('Please enter width: ')
        print '=' * width
When I run the code, I can't input anything in the Debug console.
I think that's something Visual Studio Code should improve.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please flle against python issues against the python extension.
