### ISSUE TITLE
SavingProblem

### ISSUE THREAD

**Issue by huang2002** [Microsoft/vscode#31273]
I saved some files, then the one I am looking at covered others. For example:
```
<!-- a.html -->
<!DOCTYPE html>
<html>

<head>
    <title>Document</title>
</head>

<body>
</body>

</html>

/* b.css */
/* I'm looking at this file */
* {
    color: red;
}
```
When I leave the window, they save automatically, and *b.css* become:
```
<!DOCTYPE html><html><head><title>Document</title></head><body></body></html>
```

**Comment by aeschli** [comment]
@huang2002 What extension do you use to format css?

**Comment by huang2002** [comment]
@aeschli lonefy.vscode-js-css-html-formatter

**Comment by aeschli** [comment]
@huang2002 Do you have reproducible steps? What are your settings? I tried with 
```
	"editor.formatOnSave": true,
	"files.autoSave": "onFocusChange",
```
and the lonefy.vscode-js-css-html-formatter

- Edit the html, change to the css file.
- edit the css, change to the html file

No luck to reproduce the issue you describe (where css turns into html)

**Comment by huang2002** [comment]
@aeschli My settings:
```
"files.autoSave": "onWindowChange",
"editor.formatOnSave": true
```
* create `a.css`, then type something without saving.
![image](https://user-images.githubusercontent.com/25705146/29165220-9aea2e28-7df4-11e7-93fd-2423dec986bb.png)
* create `b.html`, then type somthing without saving.
![image](https://user-images.githubusercontent.com/25705146/29165327-e77a7540-7df4-11e7-9f06-81601a379ab2.png)
* leave the window(for example, turn to my browser) without saving any file.
* finally,
![image](https://user-images.githubusercontent.com/25705146/29165363-feb499f2-7df4-11e7-8fc3-259d6a000690.png)
![image](https://user-images.githubusercontent.com/25705146/29165373-0bc78cd0-7df5-11e7-8189-2e38bcbffb9b.png)
Also, if I look at `a.css` and leave, css will turn into html. 

In addition, if I open more files, the file which I was looking at (before leaving) will cover all the others.

**Comment by aeschli** [comment]
Oh, now I see it. Looks like a bug with onWillSaveTextDocument> It's called twice. For the hidden editor, it sends a document that contains the wrong content.

```
[Extension Host] onWillSaveTextDocument 
fileName: "/home/aeschli/workspaces/samples/languages/css/b.html"
content: <!-- a.html -->
<!DOCTYPE html>
<html>

<head>
    <title>Document</title>
</head>

<body>
</body>

</html>
extensionHost.js:306 [Extension Host] onWillSaveTextDocument  
fileName: "/home/aeschli/workspaces/samples/languages/css/a.css"
content: <!-- a.html -->
<!DOCTYPE html>
<html>

<head>
    <title>Document</title>
</head>

<body>
</body>

</html>
```

**Comment by jrieken** [comment]
The formatter extension is known to confuse the files. Please forward this issue accordingly.
