### ISSUE TITLE
Menu text is too small and barely readable

### ISSUE THREAD

**Issue by Deathangel908** [Microsoft/vscode#31278]
Menu text is too small (2 times smaller than others), barely readable w/o any way to increase their size (`window.zoomLevel`, `editor.fontSize` doesn't affect them.):  
![image](https://user-images.githubusercontent.com/1336703/28500454-55b2add4-6fd1-11e7-9863-14407641ef61.png))
Also it's hard to read light-grey text on dark grey background. Is there  any way it can be tuned? 
 - If it's VSCode specific how do I change it?
 - But I feel like it's QML/GTK specific, if it's so maybe it's worth considering move this to HTML layout? Or maybe there's anything I can do to edit in gtk\qml conf? (Other QML apps don't have this issue in my setup).

My setup:
- VSCode Version: `1.14.2-1` from [aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code)
- OS Version: ArchLinux + Kde (bleeding edge, latest)

**Comment by isidorn** [comment]
This is just how electron renders menus on your OS, please file this against electron directly. Thank you

**Comment by Deathangel908** [comment]
If anyone else faces this issue, you can start VSCode with `--force-device-scale-factor=1.2` where 1.2 is a scale. Or you can add this to executable: `/usr/bin/code`:
```
ELECTRON="$VSCODE_PATH/code"
CLI="$VSCODE_PATH/resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --force-device-scale-factor=1.2 "$@"
exit $?
```
