### ISSUE TITLE
terminal in python does not support rtl languages

### ISSUE THREAD

**Issue by aminmesbahi** [Microsoft/vscode#31280]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.6.9
vscode-html-css|ecm|0.1.7
mssql|ms-|1.1.0
csharp|ms-|1.11.0
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28571
