### ISSUE TITLE
vscode.workspace.getConfiguration2 doesn't return folder setting

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31282]
Not sure what the status of this API is, but in this setup:

![image](https://user-images.githubusercontent.com/172399/28502246-a732f4c6-6fee-11e7-968a-0ddf31582989.png)

The call with the active editor showing `folderA/no-var-keyword.ts` returns undefined, but in the `folderA/.vscode.settings.json` it is defined as `folderA`:
```ts
        let editor = vscode.window.activeTextEditor;
        let result = vscode.workspace.getConfiguration2('tslint', editor.document.uri);
        vscode.window.showInformationMessage('Hello World! configFile='+result.get<string>('configFile'));
```

**Comment by sandy081** [comment]
Could have broken due to the latest changes to multi-root set up.

**Comment by sandy081** [comment]
@egamma Fixed with latest API changes. Please try again.
