### ISSUE TITLE
.NetCore Intellisense not refreshing when packages added

### ISSUE THREAD

**Issue by jsheely** [Microsoft/vscode#31287]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:
1. Open VSCode
2. Use Terminal to dotnet new webapi
3. dotnet add package serilog.sinks.elasticsearch
4. Yes to restore packages
5. Try to configure ```new LoggerConfiguration().writeTo.Elasticsearch``` (Elasticsearch is not available)
6. Close VSCode & Reopen
7. Elasticsearch will now be available to intellisense

Is there a way to force refresh of intellisense as a band-aid?

**Comment by jsheely** [comment]
I made a quick video to illustrate the problem more clearly

https://dl.dropboxusercontent.com/u/10620012/2017-07-23_18-42-06.mp4

**Comment by jsheely** [comment]
This may be related to https://github.com/OmniSharp/omnisharp-vscode/issues/1104

**Comment by isidorn** [comment]
Please file this directly against the c# extension in the repo you already pointed. Thanks
