### ISSUE TITLE
Multi remote desktop session use of VS Code does not behave as expected

### ISSUE THREAD

**Issue by KingofBeast** [Microsoft/vscode#31288]
In [this video](https://thed3vine.net/files/QrzWV.mp4), you're looking at two Remote Desktop connections to the same machine. Notice how Code will only open in one session at a time. If a file is opened with Code and another session already has Code running, the file opens in that session instead of the intended one.

- VSCode Version:1.14.2
- OS Version: Windows Server 2016 x64 1607 (14393.1480)

Steps to reproduce:
1. Have a machine with multiple active login sessions
2. Use Code on both sessions

What should have happened:
- Each session should have gotten its own copy of Code

What actually happened:
- Code only opened in one session at a time, and received open commands from other sessions

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15674
