### ISSUE TITLE
Uncaught exception when calling connection.console.info()

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3128]
_From @mattacosta on February 13, 2016 7:26_

I received the following error when trying to use the `info()` method of the `RemoteConsole` object  while in my completion provider. The other console methods were not affected and operated normally.

`Notification handler 'window/logMessage' failed with message: EPERM: operation not permitted, write`

Essentially the relevant code I was using boiled down to:
```javascript
connection.onCompletion((position: TextDocumentPosition): CompletionItem[] => {
  connection.console.info('...');
});
```

vscode-languageserver: 1.3.1
os: windows 10

_Copied from original issue: Microsoft/vscode-languageserver-node#25_

**Comment by dbaeumer** [comment]
This is an issue in the extension host. Moving to vscode

**Comment by dbaeumer** [comment]
The problem is that the extension host calls console.info which seems to be not monkey patched. The default implementation does stdout.write which fails due to the fact that we run in electron-node.

@bpasero please reassign if you aren't the right owner. I somehow remember that you implemented it.

**Comment by bpasero** [comment]
@joaomoreno I think you changed this recently. I wonder if we ever patched console.info or just log/error/warn?

**Comment by joaomoreno** [comment]
Don't think you ever patched the `info`:

https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L81

**Comment by bpasero** [comment]
Ah right, we still have this code, I can take care of console.info

**Comment by dbaeumer** [comment]
@bpasero thanks
