### ISSUE TITLE
[Feature Request] Search symbol across files

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/vscode#31283]
VSCode Version: Any version
OS Version: Mac

Steps to Reproduce:

Currently you can only list and open a symbol within the current file (https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name). It would be nice to have the option to search across all open files, similar to Sublime Text.

**Comment by roblourens** [comment]
Your link does describe symbol search across files, using cmd+T.
