### ISSUE TITLE
View invisible characters

### ISSUE THREAD

**Issue by JuanPotato** [Microsoft/vscode#31291]
- VSCode Version: 1.14.1
- OS Version: Arch Linux

I just want a way to view invisible characters like zero width joiners and separate emojis that are combining. Like 👨‍💻 being separated into 👨 [box for zero width joiner] 💻

**Comment by JuanPotato** [comment]
https://github.com/JuanPotato/Tofu

I made this as I plan to attempt to have a `@font-face` that takes this and only applies to zero width characters.

**Comment by JuanPotato** [comment]
Zero width spaces are still invisible after using a font that has them as a glyph. It should be using the font

**Comment by JuanPotato** [comment]
I remember using this, but found that it still didn't work completely. Not sure anymore as I've switched to vim.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
