### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by 2637309949** [Microsoft/vscode#31295]
- VSCode Version: Code - Insiders 1.15.0-insider (81e812c06540d1bd2636cf70ff7d0edd1bb0e866, 2017-07-21T13:15:10.775Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps
