### ISSUE TITLE
Menu font is very small on HiDPI monitor

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/vscode#31296]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.8.0-58-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-html-scss|P-d|0.0.42
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.2
html-css-class-completion|Zig|1.8.0
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
vscode-npm-script|eg2|0.2.0
nuget4code|ffo|0.0.2
CppSnippets|har|0.0.12
azure-functions-tools|joh|0.3.0
vscode-codemetrics|kis|1.8.0
net-core-project-manager|ksu|0.3.6
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
vscode-for-node-js-development-pack|nod|1.0.1
reloaded-cpp|rel|0.1.5
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

1. Installed KDE Plasma 5.10 with HiDPI support. All applications works fine with real 52 DPI on my 42" FullHD monitor. Font in VS Code menu is very small.
2.  "window.zoomLevel" parameter has no effect on this.
3. Can fix this to set fake screen DPI to 72 or 96 however in all other applications fonts become VERY big.
![screenshot_20170724_051913](https://user-images.githubusercontent.com/3843657/28505856-dceb79d0-702f-11e7-8877-fc212e2eaa26.png)

Reproduces without extensions: Yes

**Comment by akontsevich** [comment]
I have FullHD screen with 52 DPI (42"), following command works for me:
`code --force-device-scale-factor=0.8`
However good to have VS Code do this automatically or have correspondent settings.

**Comment by isidorn** [comment]
Please file this directly agains electron since it is in control of rendering the font

**Comment by akontsevich** [comment]
> Please file this directly agains electron since it is in control of rendering the font
Sorry, did not catch You, what do You mean? What need to do?

**Comment by isidorn** [comment]
Sorry for not being more clear. VSCode is built on top of a framework called Electron, please file this issue there https://github.com/electron/electron/issues

**Comment by akontsevich** [comment]
I see, thanks! Will do.

**Comment by akontsevich** [comment]
`--force-device-scale-factor` less than 1 does not work any more in VS Code 1.6 - fonts become huge!
