### ISSUE TITLE
Opening a certain folder causes Code to lock up.

### ISSUE THREAD

**Issue by kthompson** [Microsoft/vscode#3129]
I have tried opening code via the following command:
`code --disable-extensions .` but it doesnt seem to help.

Also it will work for about 3 or 4 seconds giving me enough time to open dev tools but I do not see any errors before it locks up completely.

Devtools seem to continue to work but the text window, explorer, and side bar are unresponsive.
Also the explorer doesnt seem to fully load. It only shows the header "Explorer": 

![screenshot 2016-02-18 09 40 55](https://cloud.githubusercontent.com/assets/15068/13152381/bfc52b46-d623-11e5-9783-a10020696b23.png)

I am running version 0.10.8 currently on Windows 10.

This only happens for one particular folder that has ruby code in it. Other folders with ruby or other code open fine. There is no .vscode folder for this project so I am not sure where project specific settings might reside. It appears to try and open the same two files every time I open this folder.

Another thing, I moved my project to a different path and the issue seemed to go away but upon moving the project back to the previous location the issue returns.

Please let me know if there is any additional data I can provide that would be helpful.

**Comment by bpasero** [comment]
@kthompson can you share the workspace and its location?
