### ISSUE TITLE
Do NOT support Fedora26？

### ISSUE THREAD

**Issue by Aitkots** [Microsoft/vscode#31297]
- VSCode Version: Latest
- OS Version: Fedora26

Steps to Reproduce:

1.Fresh install
2.vs code no-response

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Well we certainly supported Fedora 25, something must have changed in 26.

**Comment by David-Else** [comment]
It's working here in Fedora 26 in X mode with a load of extensions... was a fresh install after a fresh Fedora install.

There is no Update 1.14.2 in the repo yet...

**Comment by Aitkots** [comment]
Manually installed VSC 1.14.2 in fresh Fedora 26，it didn't work...
Atom is not work neither....
That is weird...

**Comment by David-Else** [comment]
I am using the Code repository rather than downloading and running in case that is relevant...

> RHEL, Fedora and CentOS based distributions
> 
> We currently ship the stable 64-bit VS Code in a yum repository, the following script will install the key and repository:
> 
> sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
> sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
> 
> Then update the package cache and install the package using dnf (Fedora 22 and above):
> 
> dnf check-update
> sudo dnf install code

Did you do a full `sudo dnf update` on Fedora 26 in case something got fixed since release?

**Comment by Aitkots** [comment]
:) thanks a lot~

**Comment by Tyriar** [comment]
Sounds like it's fine then? 😃

**Comment by Aitkots** [comment]
I think this is the problem caused by Wayland,when I switch back to Xorg,everything goes normal~
