### ISSUE TITLE
Setting watch mode for TypeScript is now not straightforward

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vscode#31294]
- VSCode Version: 1.4.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install a new VSCode instance
2. Open a TS file
3. Control+Shift+B does not show TS watch mode option

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
See #29580

If you add compileOnSave to your `tsconfig.json`, it will now be build in watch mode. You can also still contribute your own task definitions

**Comment by CoenraadS** [comment]
@mjbvz 

It works, but complains a bit:

![image](https://user-images.githubusercontent.com/5593825/28637776-f8d11622-7242-11e7-816f-83679e443245.png)

**Comment by SaschaNaz** [comment]
Both `compileOnSave` and manual `"watch": true` don't help me :/

**Comment by mjbvz** [comment]
@SaschaNaz You're using the old typescript task. Using tasks 2.0, we should automatically detect any `tsconfig.json` in your project and create build tasks for these. `compileOnSave` is only observed in these auto detected tasks. We need to update the documentation on this

**Comment by SaschaNaz** [comment]
I added that tasks.json just to try adding `"watch": true`. I didn't have it before and it didn't work anyway.

**Comment by mjbvz** [comment]
Actually I think using `compileOnSave` to enable watch is only in VScode 1.15. Can you please try VSCode insiders

**Comment by SaschaNaz** [comment]
Ah yes, it works on Insiders. Thanks :smile:

**Comment by SaschaNaz** [comment]
@mjbvz Now VSCode 1.15 and Insiders both ignores `compileOnSave`. I see there is a new PR for it, is this feature disabled before that PR?
