### ISSUE TITLE
不知道你们有没有看懂汉语的，一个本地起的项目，没有进行远程仓库，只是node创建的，但是会有默认git包，所以在修改代码的时候，git会计算哪里代码改动了，比如用脚手架vue-cli创建的一个项目，在本地使用的时候，这个时候会出现卡死的情况

### ISSUE THREAD

**Issue by nujey** [Microsoft/vscode#31292]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|stylus|Alan|0.0.4|
|vscode-theme-onedark|akamud|1.3.2|
|vscode-wxml|coderfee|0.1.9|
|auto-rename-tag|formulahendry|0.0.14|
|vetur|octref|0.9.1|
|vscode-icons|robertohuertasm|7.10.1|;

---

Steps to Reproduce:

1.
2.

**Comment by blusoul** [comment]
不知道你的情况，会不会是你目录下没创建 .gitignore 文件来排除不需要 git 跟踪的文件（如：node_modules/）？ 你可以试下 [Node.gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore)

**Comment by binsee** [comment]
我在英文社区发内容是用百度翻译成英文发出来... 😂

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps. Thanks you

**Comment by rebornix** [comment]
Please at least provide reproduce steps and put them into the description of this issue, thanks in advance.
