### ISSUE TITLE
Starting AutoRest-Manager.

### ISSUE THREAD

**Issue by ChakritRakuang** [Microsoft/vscode#31299]
Starting AutoRest-Manager.
[Error - 1:52:31 PM] Error Starting Autorest-Manager : Cannot find module 'C:\Users\Chakrit  Rakhuang\.autorest\plugins\autorest\1.1.0-20170711-2300-nightly\node_modules\autorest-core'

windows 10 64 bit enterprise

**Comment by isidorn** [comment]
Please file this issue with reproducable steps and I will reopen
