### ISSUE TITLE
Emmet: Implement Reflect CSS Value in emmet extension

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31298]
Use new emmet modules for implementing "Reflect CSS Value" feature in the emmet extension

The last of the emmet features to be implemented in the emmet extension.

Woohoo!

cc @jens1o @vvs @@smlombardi give this one a try in tomorrow's Insiders (July 25)

**Comment by vvs** [comment]
Hi @ramya-rao-a , this feature does work with CSS files, but not with SCSS ones. :(

**Comment by smlombardi** [comment]
I never use this feature with scss since I always have a process to run Autoprefixer to add all the alternates as needed.

**Comment by jens1o** [comment]
Can reproduce what @vvs said.

**Comment by ramya-rao-a** [comment]
@vvs @jens1o Silly me, the command was still using the old implementation (which didn't support scss)

I have made the change to use the right command in the new extension. Should be out in tomorrow's insides.

**Comment by jens1o** [comment]
Okay, happy to test that. :)

**Comment by vvs** [comment]
The latest insiders build works fine w.r.t. this feature for me, including SCSS. 👍

**Comment by jens1o** [comment]
Also working fine for me. :)

**Comment by ramya-rao-a** [comment]
perfect, thanks!
