### ISSUE TITLE
Creating multiple sub folders at once

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#31305]
- VSCode Version: 1.15.0 insider
- OS Version: Win Srv 2012 64 bit

## Steps to Reproduce:

In Java, and probably other languages, it is common to have deep directory structures. In those cases a directory structure can often look like this:
- src/main/java/com/domain/projectname

Results in the following folder tree:
```
\src
\src\main
\src\main\java
\src\main\java\com
\src\main\java\com\domain
\src\main\java\com\domain\projectname
```

In IDE's like `Intellij` or `Eclipse` folders like these are easily created by just typing the whole string with slashes `/` or backslashes `\`. This doesn't seem to be possible in `VS Code`.

1. Select `New Folder`
![image](https://user-images.githubusercontent.com/10828570/28513819-e7e38e68-7057-11e7-8ffa-334b612813be.png)
2. Type the string `src/main/java/com/domain/projectname`
![image](https://user-images.githubusercontent.com/10828570/28513850-03f69186-7058-11e7-82d7-d846a4adb832.png)

I believe this is a feature request.

**Comment by GuskiS** [comment]
This is a must have feature.
