### ISSUE TITLE
Integrated terminal scrolling choppy

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#31306]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. Open terminal
2. Type random things in and press enter a bunch so you can scroll up and down in the terminal
3. Scroll especially using two finger scroll on a laptop

Expected: Smooth scrolling (like in the normal editor, a standalone terminal, or in any other app like a browser)
Actual: Really choppy scrolling that's maybe 5-10 fps.

Reproduces without extensions: Yes/No

**Comment by justlurking** [comment]
Are there any Unicode characters in the text you used to test this? Wonder if there is any relation to issue #24795?

**Comment by azydevelopment** [comment]
There was just plain garbage text.  "asdf" type of stuff.

**Comment by Tyriar** [comment]
I've noticed the terminal slowing down significantly s well, but only on Windows.

**Comment by azydevelopment** [comment]
Ok well there you go, looks like there is some investigation to do I guess.  Thanks for the confirm @Tyriar.

**Comment by Tyriar** [comment]
Scrolling performance should be way better now, except when the editor is having an issue with GPU rendering, in which case launching via `code --disable-gpu` should fix it.

**Comment by azydevelopment** [comment]
Thanks. Can you define 'having an issue with GPU rendering?'. It isn't good for battery if accelerated rendering is off I'd imagine.

**Comment by Tyriar** [comment]
@azydevelopment some computers have problems with rendering to canvas, this can be due to Chromium/OS/hardware AFAIK so it's hard to tell what the problem could be for sure. It's certainly better to have GPU acceleration on if it works.
