### ISSUE TITLE
Cannot navigate through Menus using right/left arrow keys on the keyboard

### ISSUE THREAD

**Issue by alenjalex** [Microsoft/vscode#31302]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Gradle|caz|1.1.2
csharp|ms-|1.11.0
java|red|0.7.0

---

Steps to Reproduce:

1. Open File Menu using the keyboard (Alt + F)
2. Press the right arrow on the keyboard.

Expected Outcome : 
Edit Menu is selected/displayed/opened.

Actual Outcome : 
Selection doesn't change from File Menu.

Note : 
1. This is applicable for all the Menu items
2. This is only with reference to the right and left arrows.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This is a known issue, please go through our issues to find a duplicate. The root cause is electron
