### ISSUE TITLE
Encoding format error

### ISSUE THREAD

**Issue by leo-leoleo** [Microsoft/vscode#31300]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-in-browser|tec|1.0.0

---

Steps to Reproduce:

1. use browserify to bale code, if use command line of the vscode, utf-8 will be baled to utf-16le.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this issue with exact reproducable steps. What is the expected behavior, what is the actual behavior?
