### ISSUE TITLE
Block comment introduces spaces

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#31318]
Adding a block comment adds spacing around the selection. Removing the comment leaves the space?

I'm sure this wasn't happening before 1.14...

**Comment by rebornix** [comment]
Yes we added this to align with line comment, cc @cleidigh

**Comment by cleidigh** [comment]
@Gruntfuggly 
@rebornix 
In the latest insiders Code both block comment and line comment should remove the spaces on toggle.
The stable code added the space in Block comment, but did not remove it (bug is now resolved)

**Comment by rebornix** [comment]
@cleidigh nice explaination :)
