### ISSUE TITLE
Passing extra arguments with executeCommand

### ISSUE THREAD

**Issue by anacierdem** [Microsoft/vscode#31319]
Currently I am using

    vscode.commands.executeCommand('vscode.executeDefinitionProvider', uri, pos).then(refs => {

    });

on my [extension](https://github.com/anacierdem/vscode-requirejs) to re-invoke the provider recursively.

During this process I like to pass around a state object to keep track of the initiating point. Currently using a static value (`ReferenceProvider.childWord`) for this, which is not appropriate as it is possible to enqueue other providers during any asynchronous operation that will overwrite this value.

I suggest;

    vscode.languages.registerDefinitionProvider(
                { scheme: 'file' }, 
                new ReferenceProvider(),
                "providerIdentifier"
            )

    vscode.commands.executeCommand('vscode.executeDefinitionProvider', uri, pos, extraParams).then(refs => {

    });

Where;

    extraParams = {
        "id": "providerIdentifier",
        "customParam1": "value",
        ...
    }

vscode API then should check if providerIdentifier is registered and pass custom params when it is being invoked. This will make it possible to use persistent states with this recursive strategy.

**Comment by jrieken** [comment]
Can you step back and explain me your use-case? There might be a simpler solution to the problem

**Comment by anacierdem** [comment]
Ok, at some point in my extension, I want to invoke vscode's definition provider as I do not want to perform generic js definition extraction. This gives me the correct js definition at any caret position that I want to query efficiently. During this I'd like to keep track some state of the initiating (or an intermediate) definition provider, as the final resolution may depend on this.

I'd rather use the simpler solution if there is any. I could not find one yet.

**Comment by jrieken** [comment]
> I'd rather use the simpler solution if there is any. I could not find one yet.

Kind of lame but you can set/unset state outside of your provider. Set state, call command, reach provider, read and unset state.

To make these extra args available to providers API changes are required because they must be fed into the `provide`-functions. Unsure if that will happen easily...

**Comment by anacierdem** [comment]
Yes, this is what I am doing right now I think. Just keeping it on a static variable (effectively outside the provider) and clearing when I'm done. But this does not guarantee it is not being overwritten while there is an asynchronous action happening. If all was synchronous, this would not be an issue.

I understand that the change is not an easy one. A simpler solution may be providing a means of tracking definition provider history by some id assigned to each invocation and passing them in an array to the provider?

But this improvement will make developing better performing and conforming definition providers by reusing already present providers, isn't my rationale right?
