### ISSUE TITLE
There is an extension to customise vscode using JavaScript API?

### ISSUE THREAD

**Issue by Aminadav** [Microsoft/vscode#31313]
Hi.

I want, to create specific key binding to many things.
For example, press CTRL+U resize the window
Bind specific hotkeys, to vbcode JavaScript API's.

**Comment by mjbvz** [comment]
Take a look at our docs on extension authoring: https://code.visualstudio.com/docs/extensions/overview

Please ask any questions on stackoverflow: https://stackoverflow.com/questions/tagged/vscode
