### ISSUE TITLE
VSCode doesn't launch at all from the terminal (Ubuntu 15) after v0.10.8

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#3131]
![screenshot from 2016-02-19 00-03-15](https://cloud.githubusercontent.com/assets/10473142/13153885/3e96cef2-d69c-11e5-8273-bd0b8dda36fd.png)

All the system information is available in the image.

**Comment by Tyriar** [comment]
@hashhar I'm assuming `code` is a symlink to `Code`, as in https://github.com/hashhar/vscode-universal-installer/blob/master/install.py? I haven't had any issues so far using Ubuntu/Compiz 15.10 and plain Debian 8.3.0. Did this just start happening with a newer version? How do you normally launch code on Linux?

Launching using `sudo` is a known issue https://github.com/Microsoft/vscode/issues/3068

**Comment by hashhar** [comment]
`/usr/local/bin/code` is a symlink to `/opt/VSCode/Code`.
It started with 0.10.8. But I had also uninstalled some packages before that so it could be that. Does VSCode have any external dependencies?

**Comment by hashhar** [comment]
**I can't reproduce this on other systems**. Seems to be something wrong with my machine.

**Comment by Tyriar** [comment]
@hashhar ok, if you end up figuring it out please ping this issue as vscode may be able to warn/advise about the situation.

**Comment by hashhar** [comment]
@Tyriar Some more context. I cannot even start Code even if I build it locally.

This is what happens.

![screenshot from 2016-02-21 17-01-41](https://cloud.githubusercontent.com/assets/10473142/13202328/e0a6f290-d8bc-11e5-888c-ae2dd1b56622.png)

**Comment by hashhar** [comment]
Running with --verbose gives:

```
ashhar@xenon:[/media/ashhar/Resources/GitHub/_Forks/vscode]🚗 
$ ./scripts/code.sh --verbose
[17:16:12] Using gulpfile /media/ashhar/Resources/GitHub/_Forks/vscode/gulpfile.js
[17:16:12] Starting 'electron'...
[17:16:12] Finished 'electron' after 670 μs
[30150:0221/171612:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
{ [Error: ENOENT: no such file or directory, open '/home/ashhar/.config/Code-Development/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ashhar/.config/Code-Development/storage.json' }
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by hashhar** [comment]
It only happens when I try to start it from the shell. Double clicking on the symlink as well as the executable launches it without problem. I even tried clearing `~/.config/Code`.

Using a different Window Manager also didn't help.
I'll now try using a different shell.

**Comment by hashhar** [comment]
Yup. It's the SHELL. Using zsh also gave the error. But as soon as I set `SHELL=/bin/zsh`, it started.

@Tyriar Maybe add this to the docs or FAQ. I'll try narrowing down the source of this. I was able to reproduce it on another install. This happens after some system updates.

**Comment by hashhar** [comment]
Works for every possible value of SHELL. I don't even have to install another shell. It just doesn't work when SHELL=/bin/bash. /bin/sh works.

This is a workaround but I would like a fix.

**Comment by Tyriar** [comment]
Interesting, I can run it just fine with `bash` as well as `zsh`.

**Comment by hashhar** [comment]
It's not the terminal emulator. It's the shell that $SHELL is pointing to.

Try setting $SHELL to /bin/bash or /bin/sh.

**Comment by Tyriar** [comment]
It works when `$SHELL` is `/bin/bash`, `/bin/sh` and `/bin/zsh`.

**Comment by hashhar** [comment]
Thanks. Consider this closed then. A workaround is known atleast.
