### ISSUE TITLE
Cursor is invisible when adjacent to minimap with word wrap enabled

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#31312]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.0.27
python|don|0.6.9
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
sort-lines|Tyr|1.3.0
---

If you have word wrap enabled, and move the cursor right to the end of the line, immediately next to the minimap, then the cursor becomes invisible.

Here is an example screenshot where the cursor at at character 79 and is visible.

![cursor_visible](https://user-images.githubusercontent.com/3789849/28517401-25795664-705c-11e7-9eb5-047647bcbb3c.png)

Here is a screenshot where I've moved the cursor one position to the right, to character 80, and now the cursor is invisible.

![cursor_invisible](https://user-images.githubusercontent.com/3789849/28517410-30795f14-705c-11e7-9287-0b9c2fc5bed2.png)

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@Eldaw From what I can tell from the screenshot, the word wrap is not turned on in your case, can you help confirm that? When the wordwrap is turned on, you are not likely to see minimap covering the code.

**Comment by Eldaw** [comment]
As I mentioned in the title and in the description, word wrap is on.

I have been able to work around this issue by making the entire application window a few pixels wider in order to create a small gap (less than the size of one character) between the end of the text and the start of the minimap.

So the issue is that it's possible for the application window to be sized such that there is no gap between the final visible character and the start of the minimap area, and in these cases there is no space for the cursor to be visible and so it isn't visible.

If you experiment with changing the width of the application window (by a pixel at a time if necessary), then you will also be able to reproduce this issue.
