### ISSUE TITLE
cannot run vscode commands from the developers tools

### ISSUE THREAD

**Issue by Aminadav** [Microsoft/vscode#31311]
![image](https://user-images.githubusercontent.com/3584317/28516435-ebb08cb4-7069-11e7-8f0a-e2f22330bbdd.png)

Hi. I'm trying to launch some vscode API command from the developer tools.
But I don't success to `require('vscode')`.

There is any other way, to launch JavaScript API without a custom made extension?

**Comment by mjbvz** [comment]
Extension run in their own process while the developer tools are in a separate one. You'll want to write an extension if you want to use the API
