### ISSUE TITLE
Environment variable syntax in tasks.json and c_cpp_properties.json is different

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#31310]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. Create project with c_cpp_properties.json include path that has "${INCLUDE}" where INCLUDE is an environment variable
2. Create tasks file where the command is "${env:MSBUILD}" where MSBUILD is an environment variable

Expected: Syntax is the same for both environment variable expansions.
Actual: c_cpp_properties.json and tasks use different syntaxes.  One of them requires the "env:" prefix and the other one doesn't.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
The syntax ${env:...} is consistent in vscode itself and used that way in tasks.json and launch.json. Please file an issue against the cpp tools. 

VS Code uses that syntax to differentiate between env variables and VS Code variables like ${file} which denotes the current file.
