### ISSUE TITLE
Add a Linux man page for 'code' command line

### ISSUE THREAD

**Issue by Naereen** [Microsoft/vscode#31317]
Hi,
I looked in the issues and in the documentation, apparently there is no Linux/UNIX manpage for the `code` command which is installed on *NIX systems when install VSCode.
Could it be added? It could be minimalist, generated automatically (e.g., with `pandoc`) from the `code --help` message.

**Comment by rocketinventor** [comment]
I am using Windows 10 and out of curiosity, I decided to run the `code` command inside of bash. It appears to work in the same way as VIM or cat and opens files code (or a file if in the cd if a name is specified).

@Naereen Is that the same way it works in Linux?

**Comment by Naereen** [comment]
Hi @rocketinventor. I don't see the link between your question and the issue/question I raised here.
But to answer, it works as `subl` or `gedit` works: it starts the program with no file if just `code` is called, or opens one or more FILE if `code FILE [FILE...]` is called (same with directory/ies).

**Comment by Tyriar** [comment]
The reason I didn't pursue this was because on macOS there is already a code command and I'm not sure how conflicts would be handled. If we had a man page on Linux it should also be on macOS.

<img width="574" alt="screen shot 2017-07-24 at 11 02 16 am" src="https://user-images.githubusercontent.com/2193314/28537419-9fd53966-705f-11e7-8f15-9f6695d03c5f.png">

Any insights on the subject would be useful.

**Comment by Naereen** [comment]
Hum, I didn't know that. No idea how to handle this situation if there is already a `code` command on Mac OS.

But if the shell is able to use `$PATH` to know which is `code`, then `man` should be able to use `$MANPATH` and its order to know which manpage to open from `man code`... no?

**Comment by sumnerevans** [comment]
The man page for `code` on macOS doesn't have a section. (Note that it has `code(n)`.)

VSCode could use the `code(1)` man page. See [man-pages(7)](http://man7.org/linux/man-pages/man7/man-pages.7.html) for more information about the man page sections.

**Comment by rmunn** [comment]
Apparently on Mac OS (and maybe other places as well?), `n` is a valid code page section, for Tcl/Tk functions / routines / whatever the right term is:

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/manpages.5.html#//apple_ref/doc/man/5/manpages

So it's not that the existing `code` manpage has no section, it's just that it's in section `n`. Either way, though, there will be no conflict if VS Code adds a `code` manpage in section 1 (which is the correct section for any command the user would type at the terminal prompt).

**Comment by Naereen** [comment]
@Tyriar @sumnerevans @rmunn 
I think this can be resolved very quickly: one could add a script in the build process that does these steps:

1. take https://code.visualstudio.com/docs/editor/command-line#_additional-command-line-arguments (https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/command-line.md) and copy this part of the Markdown file
2. use [`pandoc --to man`](http://pandoc.org/) (or --to groff I never know) to convert the markdown file to a man page
3. include it in the install script to deploy it to /usr/share/man or whever you want

**Comment by Tyriar** [comment]
@rmunn we're focusing on getting our issue count down currently. We would probably still accept a PR for this but I don't think there's that much point tracking it as it's been open for PRs for over a year, opened longer and only has 3 votes. You can read more about how we classify out of scope here: https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests

**Comment by tripleee** [comment]
Can you provide a link where we can read the documentation until you figure this out?

**Comment by Tyriar** [comment]
@tripleee `code --help`, https://code.visualstudio.com/docs/editor/command-line?
