### ISSUE TITLE
Search fails when "files.encoding": "cp852"

### ISSUE THREAD

**Issue by adelchi** [Microsoft/vscode#31314]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
tslint|eg2|0.17.0
harbour|eko|0.0.8
mssql|ms-|1.1.0
csharp|ms-|1.11.0
code-settings-sync|Sha|2.8.2
Align|ste|0.2.0

---

Steps to Reproduce:

1. Open any folder
2. Set "files.encoding": "cp852"
3. Search does not work

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Some encodings which the editor supports are not supported by ripgrep, which we use to power search. #29090 tracks adding an error message for this. You can work around by setting `"search.useRipgrep": false`.
