### ISSUE TITLE
SVN integration same as Git

### ISSUE THREAD

**Issue by ankitkamboj0** [Microsoft/vscode#31316]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ankitkamboj0** [comment]
There is no extension for svn integration in it. 
We want svn support same as you support git

**Comment by joaomoreno** [comment]
#206 

Why not taking the opportunity to create such an extension? Many people seem to want itt oo.
