### ISSUE TITLE
Test: loaded scripts explorer

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31327]
Test for #28521 and #31002:

Complexity: 3

- [x] Windows - **@egamma**
- [x] macOS- **@isidorn**
- [x] Linux - **@joaomoreno**

Previously loaded scripts could only be accessed via the "Open Loaded Script" action which uses a QuickPick UI.
With the new "Loaded Scripts" explorer it is possible to view and select loaded scripts in an explorer section in the debug viewlet.

Verify for both "legacy" and "inspector" protocols:
- the "Loaded Scripts" explorer is only visible if a node debug session is active
- the explorer shows new scripts as they are loaded
- scripts show up under the correct top level nodes:
  - first come the workspace root folders,
  - then scripts outside of the workspace
    - scripts under the user's home directory are abbreviated to '~' in linux and macOS 
  - then internal node scripts
- scripts show up under the correct top level nodes for (legacy) single folder workspaces and in non-folder mode 
- scripts in the explorer have the same path as the scripts shown in the QuickPick UI
- if more than one debug session is active, the explorer shows session nodes (which will not disappear if the number of debug sessions drops below two).
- selecting a leaf opens the script in a read only editor

**Comment by joaomoreno** [comment]
Due to #31523, I couldn't get very far. This should get more testing next week. 👍
