### ISSUE TITLE
[php] Incorrect color for switch default label when using alt-syntax

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#31320]
The keyword `default` is white like a regular label instead of purple if it is on a new line, has leading whitespace, and is followed by a colon.

```php
switch ($a):
  default:
    break;
endswitch;
```

**Comment by jens1o** [comment]
That has been fixed in the latest insiders version.

**Comment by mattacosta** [comment]
![default-label-color](https://user-images.githubusercontent.com/1007463/28540714-31afedb2-706b-11e7-9e3d-367b35e68337.png)
Odd, I had just updated...

**Comment by jens1o** [comment]
Okay, it isn't fixed here, but in the grammar. 

https://github.com/atom/language-php/commit/8b4ab3e8acaf50da14d6fac4d797a69f0918f760

but the vscode team didn't updated the grammar, yet, or the parser does not understood the grammar correctly.

**Comment by mattacosta** [comment]
Ah, well judging by the comment in that commit, it seems the problem is upstream:
`# but NOT switch(expression):`

Note the trailing colon...

**Comment by jens1o** [comment]
Then you need to file this issue there.

**Comment by mattacosta** [comment]
Oh right. Didn't really want to go through their wall-of-text issue template while at work yesterday.

I'll leave this open until the change gets pulled into vscode.

**Comment by mattacosta** [comment]
Fixed by f31c369.
