### ISSUE TITLE
Display git message warning for 50 character

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#31322]
Git message is not showing in win 10 vs code after 50 characters. This is working fine on my win 7 machine. 

- VSCode Version: 1.14.2
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/2848185/28526840-be42f69e-7056-11e7-9644-7e703a2a629c.png)

Steps to Reproduce:

1. Type git message longer than 50 characters
2. 50 character limit message not showing

Reproduces without extensions: Yes

**Comment by rmunn** [comment]
Probably related:
#21144
#18807
#2718

**Comment by joaomoreno** [comment]
Yeah, I couldn't find that one, duplicate of #21144, thanks @rmunn
