### ISSUE TITLE
Debug Console suppressing URL output to stderr when line is of form "x.x:# http://x.x:#"

### ISSUE THREAD

**Issue by jonathanfrisco** [Microsoft/vscode#31330]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.4.0
vscode-markdownlint|Dav|0.10.0
xml|Dot|1.9.2
vscode-docker|Pet|0.0.16
Bookmarks|ale|0.15.2
code-gnu-global|aus|0.2.2
githistory|don|0.2.2
CppSnippets|har|0.0.12
asciidoctor-vscode|joa|0.3.5
vscode-insertdatestring|jsy|2.1.0
Go|luk|0.6.62
vscode-clang|mit|0.2.2
mssql|ms-|1.1.0
cpptools|ms-|0.12.1
peep|nwa|0.0.5
code-spell-checker|str|1.3.2
gotimeformat|v4r|1.0.1

---

Steps to Reproduce:

1. Short Go program:  
```
package main

import "fmt"
import "os"

func main() {
    fmt.Fprintln(os.Stderr, "x.y:1 http://x.y:1")
}
```
Should output: "x.y:1 http://x.y:1"
Outpust: "x.y:1 "
Running in terminal is fine and sending to stdout in debug console is also fine.  If character(s) after colon are not numeric, fine, if http:// is not there, fine, if either period is not there, fine.  Only when all conditions are met is the URL portion and everything after on line suppressed.

Reproduces without extensions: Cannot determine (need Go extension), but reproduces with ALL other extensions disabled.

**Comment by weinand** [comment]
@isidorn I can reproduce this with node/node2 and the debug console. It works fine with the integrated terminal.

**Comment by isidorn** [comment]
This is probably due to the link detection - since it is a link.
Giving to @michelkaporin - feel free to give back to me if you do not find time in you last week 😉

**Comment by weinand** [comment]
Why is link detection destructive?

**Comment by michelkaporin** [comment]
@isidorn thanks for that! Otherwise I can pick it up myself in my free time in the beginning of August as a PR :) 

Seems that https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/linkDetector.ts#L82 this IF should be outside of while-loop.

@weinand unfortunately due to incorrect output string reconstruction.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
