### ISSUE TITLE
Transparent proxy and uses users NT credentials

### ISSUE THREAD

**Issue by BryanLaValley** [Microsoft/vscode#31338]
Our network uses a transparent proxy and uses users NT credentials to authenticate to the proxy. In powershell I can create a WebClient object which will fail on all requests (Error 401 - Unauthorized) until I set UseDefaultCredentials = $true.

Sorry if this is a duplicate request. I searched and didn't find a match and closest one was for a customizable 'User Agent String'.

Please enable this functionality.
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1
vscode-icons|rob|7.10.1

---

Steps to Reproduce:

From Extensions I get no results when I select any of the 'Show' commands. Also when I 'Check for Updates' I'll get the 401 error.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you open the Shared Process window (<kbd>F1</kbd>, `Shared Process`), and inside open its Developer Tools, Network tab, and then try to list extensions? Show me the requests going on in there.
