### ISSUE TITLE
"Code language not supported or defined" Message after terminal clear

### ISSUE THREAD

**Issue by 1d82fdaaf812** [Microsoft/vscode#31334]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
code-runner|for|0.6.28
Kotlin|mat|1.3.0
---

Steps to Reproduce:

1. Clear the terminal, OUPUT tab should be active
2. Press the "play green button" as quick as posible

As you notice the warning it is triggered.

Reproduces without extensions: No

**Comment by 1d82fdaaf812** [comment]
![image](https://user-images.githubusercontent.com/15732201/28534286-d47ed6ee-7065-11e7-8823-089d0cdc9fc6.png)

**Comment by 1d82fdaaf812** [comment]
I think this is not a blocker since we can wait a while and then the play button it works. Not sure if the problem is something async.

**Comment by isidorn** [comment]
Terminal clear should not have any effect on debugging. I can not reproduce with the steps you provided - gif attached. Let me know if you are doing something different

Also try reproducing with all extensions disabled and reproducing in a vanilla repositry. Thanks
![repro](https://user-images.githubusercontent.com/1926584/28559628-961bb590-7117-11e7-9ea7-e6bb7dbe773c.gif)

**Comment by 1d82fdaaf812** [comment]
The play button is not for debugging is to run code. That is the purpose of the extension, run code without  to be compiled in other place.
Normaly we have an ouput like:
````
[Running] cd "@userl\test\" && kotlinc main.kt -include-runtime -d main.jar && java -jar main.jar
Kotling run

[Done] exited with code=0 in 2.04 seconds
`````
But when you press clear and quickly the 'play' not the debug button the message appears and until you close it does not allow you to run code.

![image](https://user-images.githubusercontent.com/15732201/28570687-db9db3a6-7104-11e7-981d-0019308b7abd.png)

**Comment by 1d82fdaaf812** [comment]
https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

**Comment by 1d82fdaaf812** [comment]
@isidorn I think this is a problem with the extension itself.

**Comment by 1d82fdaaf812** [comment]
I found the message here:
https://github.com/formulahendry/vscode-code-runner/blob/1b14d7940475573d08ffaa09695b0f5edecd5a8e/src/codeManager.ts

We have:
`````
    public onDidCloseTerminal(): void {
        this._terminal = null;
    }
....
    vscode.window.showInformationMessage('Code language not supported or defined.');
`````

**Comment by isidorn** [comment]
Yes please file this issue against that extension directly, thank you

**Comment by rfnxinger** [comment]
I also had this issue also using OpenVPN 2.4.3 code:
"Code language not supported or defined." whn compiling the Project.
 in locale.json I tried en, en:Us, de but no success
	
![image](https://user-images.githubusercontent.com/31359191/29735345-8f9fb4ec-89f8-11e7-98aa-b4eedd897943.png)

> "locale":"en-US"

any ideas?
Thank you! @

**Comment by JanisE** [comment]
The related issue is this one: https://github.com/formulahendry/vscode-code-runner/issues/147

As you can see, this isn't planned to be improved. Even when the tab/window with the file to run is active, the code runner needs you to focus to it explicitly / click on it in order for the "Run Code" command to work.
