### ISSUE TITLE
Code Outline does not show class methods

### ISSUE THREAD

**Issue by iRoachie** [Microsoft/vscode#31337]
- VSCode Version: 1.14.2
- OS Version: 10.12.6

#### Steps to Reproduce:
1. Create a class with methods
2. Open the Code Outline

Reproduces without extensions: `Yes`
Environment: `React Native with Typescript`
File extension: `tsx`
Typescript Version: `2.4.1`

## Test file

```tsx
import React, { Component } from 'react'
import { connect } from 'react-redux'
import redux from 'redux'
import {
  NavigationScreenProps,
  NavigationScreenConfigProps,
} from 'react-navigation'
import { ActionButton } from 'react-native-material-ui'

import { NavButton } from '@components'
import { updateTicket } from '@actions'
import { Store, Ticket } from '@models'
import NoTickets from './components/NoTickets'
import { Content } from './styles'
import TicketList from './components/TicketsList'

interface ConnectedDispatch {
  toggleSidebar(): void
  updateTicket(ticket: Ticket): void
}

interface ConnectedProps {
  tickets: Ticket[]
}

interface State {
  newTicketModalOpen: boolean
}

interface Props
  extends NavigationScreenProps<{}>,
    ConnectedDispatch,
    ConnectedProps {}

class Support extends Component<Props, State> {
  static navigationOptions = ({ navigation }: NavigationScreenConfigProps) => ({
    title: 'Support',
    headerLeft: (
      <NavButton
        iconName="menu"
        onPress={() => navigation.navigate('DrawerOpen')}
      />
    ),
    headerRight: (
      <NavButton
        text="FAQ"
        onPress={() => {})}
      />
    ),
  })

  state = {
    newTicketModalOpen: false,
  }

  toggleNewTicketModal() {

  }

  viewTicket(ticket: Ticket) {
  }

  addNewTicket() {
    this.props.navigation.navigate('NewTicket')
  }

  render() {
    return (
      <Content>
        {this.props.tickets.length === 0
          ? <NoTickets />
          : <TicketList
              tickets={this.props.tickets}
              viewTicket={a => this.viewTicket(a)}
            />}

        <ActionButton icon="add" onPress={() => this.addNewTicket()} />
      </Content>
    )
  }
}

const mapStateToProps = (state: Store) => ({
  tickets: state.tickets,
})

const mapDispatchToProps = (dispatch: redux.Dispatch<Store>) => ({
  updateTicket: (ticket: Ticket) => dispatch(updateTicket(ticket)),
})

export default connect<ConnectedProps, ConnectedDispatch, null>(
  mapStateToProps,
  mapDispatchToProps
)(Support)

```

## Code Outline Output
![screen shot 2017-07-24 at 2 16 12 pm](https://user-images.githubusercontent.com/5962998/28537993-ab341dde-707a-11e7-9ac6-5dc67a5b2071.png)

Only shows static members

**Comment by mjbvz** [comment]
I believe there is a syntax error in your code. Inside `headerRight`, there is a stray `)` in `onPress={() => {})}`

After deleting this, I see the code outline working as expected:

![screen shot 2017-07-24 at 1 22 38 pm](https://user-images.githubusercontent.com/12821956/28543001-32079fd2-7073-11e7-8097-cb2a1c81d94f.png)

**Comment by iRoachie** [comment]
@mjbvz They aren't any stray `)` the code and compiles through tsc. I just edit a portion of it to post

**Comment by iRoachie** [comment]
Full header right.

```jsx
  headerRight: (
      <NavButton
        text="FAQ"
        onPress={() => Linking.openURL('https://google.html')}
      />
    ),
```

**Comment by iRoachie** [comment]
@mjbvz Could you reopen this? There's nothing wrong with what i provided. This simple example fails:

```jsx
static navigationOptions = ({ navigation }) => ({
    headerLeft: (
      <NavButton
        iconName="menu"
        onPress={() => navigation.navigate('DrawerOpen')}
      />
    ),
  })
```

**Comment by mjbvz** [comment]
The code you first pasted up has a syntax error. Using that replacement definition for `navigationOptions`, here's what our built-in outline shows:

![screen shot 2017-07-24 at 1 45 03 pm](https://user-images.githubusercontent.com/12821956/28543931-577b8ee2-7076-11e7-9c15-10bad8537a96.png)

The code outline panel in your screenshots comes from an extension. If it is not displaying results correctly, please try filing an issue against that extension

**Comment by iRoachie** [comment]
Thanks. I thought it was a built in section all time. I found the extension. Thanks 👍🏽
