### ISSUE TITLE
Could not install typings behind proxy

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31336]
From @dakisxx in https://github.com/Microsoft/vscode/issues/24961#issuecomment-316960416:

- VS code `1.14.2` (doesn't work with latest insiders either - `1.15.0-insider`)
- Typescript `2.4.2`
- OS kubuntu, fish shell
```
NPM location: "/home/daniel/n/bin/npm" (explicit '--npmLocation'  provided)
Npm config file: /home/daniel/.cache/typescript/2.4/package.json
Updating types-registry npm package...
Error updating types-registry package: Command failed: "/home/daniel/n/bin/npm" install types-registry
Types registry file '/home/daniel/.cache/typescript/2.4/node_modules/types-registry/index.json' does not exist
Sending response: {"kind":"event::initializationFailed","message":"Command failed: \"/home/daniel/n/bin/npm\" install types-registry"}
Response has been sent.
```
Some notes:

1. If I try to manually run the same failing command from console: `"/home/daniel/n/bin/npm" install types-registry`, it works fine
2. Referenced file (`/home/daniel/.cache/typescript/2.4/package.json`) is empty (content is `{}`)
3. `Types registry file '/home/daniel/.cache/typescript/2.4/node_modules/types-registry/index.json' does not exist`. There is no `node_modules` under `/home/daniel/.cache/typescript/2.4/` - the only file there is an empty package.json
4. If I start code from console, it works:
```
NPM location: "/home/daniel/n/bin/npm" (explicit '--npmLocation'  provided)
Npm config file: /home/daniel/.cache/typescript/2.4/package.json
Updating types-registry npm package...
Updated types-registry npm package
```
Could it be that it doesn't use the proxy setting correctly? (I have a corporate proxy set in VScode settings and in $HTTP_PROXY)

**Comment by joaomoreno** [comment]
This is a problem of either NPM or TypeScript, not Code. Please configure NPM/TypeScript to use your proxy.

**Comment by chrmarti** [comment]
@dakisxx Where do you set the environment variable HTTP_PROXY?

@joaomoreno This sounds to me like that environment variable doesn't make it to the tsserver. We have seen this in the past with certain setups using fish or other shells because our code failed to pick up all environment variables from a temporary shell process. (Can't find the code right now.)

**Comment by joaomoreno** [comment]
That could be. #21655

**Comment by chrmarti** [comment]
Also: "If I start code from console, it works". That matches #21655 too.

Should we check the settings for a proxy and pass that as HTTP_PROXY to the tsserver when HTTP_PROXY is not set? Maybe we could do that as a fallback when npm has failed once. @joaomoreno @mjbvz ?

**Comment by mjbvz** [comment]
@chrmarti We already should forward code's environment to the TSServer when we spawn it. The environment can just differ based on how you start code. That's one of the reasons we had to add the explicit `typescript.tsdk` setting instead of picking it up from the `PATH`

**Comment by chrmarti** [comment]
@mjbvz Are we reading the proxy config from the settings and forward these to the tsserver too? The problem here seems to be that HTTP_PROXY isn't set in VSCode's process.

**Comment by mjbvz** [comment]
No we don't do anything with the `http.proxy` setting, just the environment. Do you think we need to forward `http.proxy` to the tsserver using `HTTP_PROXY`?

**Comment by chrmarti** [comment]
It might fix some of the issues we see because the user's regular `HTTP_PROXY` might not be set due to #21655. Ideally we would only set it once the type acquisition has failed so we are sure we are not breaking working setups.

**Comment by dakisxx** [comment]
> @dakisxx Where do you set the environment variable HTTP_PROXY?

    set -Ux HTTP_PROXY "xxx"

that should be the "fish way" to globally set an env variable. If I run code from fish by running `code`, doing `echo $HTTP_PROXY` from vscode integrated terminal outputs the correct proxy url.

Is `http.proxy` generally not used any more? If it is still used, it should probably be used for retrieving typings as well. 

Of course, I realize that if it weren't for #21655 this wouldn't be needed.

**Comment by dakisxx** [comment]
Actually, even if I don't run vscode from terminal, http_proxy seems to be set just fine, so it's possible that proxy is not the issue

`process.env.http_proxy` from dev tools gives the correct url
