### ISSUE TITLE
Windows 1.14.2 python view has "No symbol information for the file"

### ISSUE THREAD

**Issue by Xyc0** [Microsoft/vscode#31343]
- VSCode Version: 1.14.2 
- OS Version: Windows x86

Steps to Reproduce:

1. Open Python file
2. Set syntax to Python
3. Ctrl-T to Show all Symbols

Reproduces without extensions: Yes, though --disable-extensions doesn't seem to have an effect, checked manually.

**Comment by Xyc0** [comment]
Checked on Ubuntu 17.04 64-bit, issue is not present.
I am not entirely sure this is a vscode issue if it requires extensions for Python symbols.

**Comment by mjbvz** [comment]
Do you have the python extension installed?

**Comment by Xyc0** [comment]
I was using donjayamanne.python but disabled all extensions to check if that was causing the problem.
I don't recall if vscode was able to parse python symbols without it, I can't find an earlier version of the vscode installer to check.

**Comment by mjbvz** [comment]
No, we don't have built-in python support. You'll need `donjayamanne.python` or another python extension for this. If you are not seeing the expected results, please file an issue against that extension: https://github.com/DonJayamanne/pythonVSCode/issues/new
