### ISSUE TITLE
code slows my mac to a halt on encountering a single line of php code

### ISSUE THREAD

**Issue by rayehizoba** [Microsoft/vscode#31349]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
dart-code|Dan|2.3.1
beautify|Hoo|1.1.1
laravel-blade|KTa|0.0.1
format-indent|Kas|1.3.0
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|2.0.11
nativescript|Tel|0.7.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.4.3
php-pack|fel|1.0.1
fs-flutter-snippets|fra|0.1.3
phpcs|ika|0.7.0
vscode-icon-theme|jtl|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.62
vscode-pugbeautify|mrm|1.0.2
vetur|oct|0.9.3
vue|sea|0.4.2

---

Steps to Reproduce:

1. Create a simple laravel project
2. Create any controller method and type `return response()->json($foo);`

Code highlights the above php snippet as having a syntax error (even though that is not correct) and after a few minutes, my mac will completely slow down to a halt. I always have to do a hard shut down :(

I have run into this problem countless of times in this past few days for me to be very sure of this. Please fix this issue. Its rather annoying to have to restart my mac every now and then just for a seemingly simple line of php code. 

Thanks for making such a wonderful companion guys!

**Comment by roblourens** [comment]
This is probably due to the php-intellisense extension that you have installed, which you can confirm by disabling it (or starting with `--disable-extensions`). Can you try that, and file an issue at https://github.com/felixfbecker/php-language-server/issues?

**Comment by roblourens** [comment]
> my mac will completely slow down to a halt. I always have to do a hard shut down :(

That sounds pretty severe - If you open Activity Monitor, you can probably find the busy process and kill it.

**Comment by rayehizoba** [comment]
Ok, thanks for the feedback.

**Comment by Darival** [comment]
i had the same issue and fixed it by adding a limit to the memory with:

`    "php.memoryLimit": "1G",
`
in the vscode settings file
