### ISSUE TITLE
Terminal dropdown showing empty title on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31346]
When running VS Code tests:

![image](https://user-images.githubusercontent.com/2193314/28548736-865f7ca0-708a-11e7-818b-cad4d6fe269e.png)

**Comment by Tyriar** [comment]
Shell is `"terminal.integrated.shell.windows": "C:\\Windows\\SysWow64\\cmd.exe"`

**Comment by Lixire** [comment]
Strange, I get Code - OSS as the title. Did the title go back to normal (cmd) after you hit enter again?

**Comment by Tyriar** [comment]
Stayed empty, I didn't check if there were errors.

It became Code - OSS?? It can't go up the process tree can it? 😕

**Comment by Lixire** [comment]
It makes sense though since test.bat would open a build of your code to test.

**Comment by Tyriar** [comment]
Yeah you're right since test.bat is not a new process. Not sure if the original issue is fixed yet or not.

**Comment by Tyriar** [comment]
This still happens briefly, but the blank is replaced with Code - OSS shortly after. Let's keep this open to track the blank in-between part. We should wait to switch until the process title is known. Probably best to wait for the native module for this.

**Comment by Tyriar** [comment]
I think this is fixed.
