### ISSUE TITLE
Reflect squiggle and other colors at scrollbar

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#31357]
VS Code: 1.14.2
Squiggle color is changed but it is still showing green at scrollbar.
Caret color is reflected but squiggle colors aren't.
![screenshot 231](https://user-images.githubusercontent.com/26769888/28556053-46edf500-7121-11e7-9f24-aca8d4cc17d1.png)

**Comment by praveenpuglia** [comment]
Hi,

I am facing difficulty in understanding what the issue is. The green squiggle and the green bar in scrollbar is shown because that's vscode advising you to not use empty rulesets.

**Comment by ajitid** [comment]
![screenshot 232](https://user-images.githubusercontent.com/26769888/28557414-db4a8b98-7129-11e7-85cc-aa6695424603.png)
If caret color is changed, I see same color in scrollbar, but this thing doesn't happen for squiggles.

**Comment by rmunn** [comment]
So this is about custom color themes: the wavy lines' color can be configured, but the color of the corresponding notification line in the scrollbar doesn't update to match the color selected for the wavy line — and you're saying that these two *should* match. Do I have it right?

**Comment by ajitid** [comment]
Yes

**Comment by praveenpuglia** [comment]
Looks like something needs to be done here - `/src/vs/editor/browser/viewParts/overviewRuler/overviewRulerImpl.ts`
