### ISSUE TITLE
gbk

### ISSUE THREAD

**Issue by zhouzm110** [Microsoft/vscode#31354]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
code-gnu-global|aus|0.2.2
githistory|don|0.2.2
terminal|for|0.0.10
uncrustify|Lau|2.5.0
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.1
java|red|0.7.0
vscode-icons|rob|7.10.1
highlight-words|rsb|0.0.5
code-settings-sync|Sha|2.8.2
gitblame|wad|2.0.2
vscode-jumpy|wma|0.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rmunn** [comment]
Looks like this was an accidental submission that should be closed; #31355 is the real issue.
