### ISSUE TITLE
Nodejs Require autocomplete not working anymore

### ISSUE THREAD

**Issue by sonyarouje** [Microsoft/vscode#3135]
Hi,
   I used VS Code since it launched, one of the feature i loved so much is the intellisense while adding a file using require when coding for node js.

After the latest update (Version: 0.10.8, Shell: 0.35.6) require intellisense is not working at all, it always says 'No suggestions'

Can someone help me to get the intellisense for 'require' command.

**Comment by laverite** [comment]
+1

**Comment by codyrigney92** [comment]
I'm guessing this is the same issue: https://github.com/Microsoft/vscode/issues/2923

**Comment by egamma** [comment]
Closing as a duplicate of #2923
