### ISSUE TITLE
modify gbk file then ctrl+shift_g into git diff will display messy code

### ISSUE THREAD

**Issue by zhouzm110** [Microsoft/vscode#31355]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
code-gnu-global|aus|0.2.2
githistory|don|0.2.2
terminal|for|0.0.10
uncrustify|Lau|2.5.0
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.1
java|red|0.7.0
vscode-icons|rob|7.10.1
highlight-words|rsb|0.0.5
code-settings-sync|Sha|2.8.2
gitblame|wad|2.0.2
vscode-jumpy|wma|0.3.1

---

Steps to Reproduce:

1.modify gbk file 
2.ctrl+shift_g into git diff

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Please describe what gbk is.

Please describe what modifications to the gkb file you actually do.

Please show us a screenshot of what you mean by messy code.

**Comment by King66** [comment]
https://github.com/Microsoft/vscode/issues/21146

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
