### ISSUE TITLE
Debugger frequently fails to connect to extension host

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#31352]
- VSCode Version: Code - Insiders 1.15.0-insider (9b6cc9f774f424b4e8a91d4a2d3d4ad8efb9cfb9, 2017-07-24T05:16:28.556Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

**Steps to Reproduce:**

1. Open an extension folder and start debugging a client
2. Wait for the extension to actually start
3. Close the extension host
4. Start debugging the client again
5. Repeat steps 2 through 4 until it fails to connect

**Notes:**

- It doesn't always happen, but I can usually reproduce it after 2-3 tries.

**Comment by weinand** [comment]
closing since EH debugging now uses "inspector" protocol.
