### ISSUE TITLE
Adopt new configuration resolver service in tasks

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31365]
Due to the multi root work now the configuration resolver service needs to take in the workspace root uri when resolving variables.
This is needed for reolving variables like `${workspaceRoot}`

The tasks frameworks needs to adpot this, I have left TODO in the following places:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L176
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L219
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L636
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processTaskSystem.ts#L380

**Comment by dbaeumer** [comment]
Will tackle this is September with the user tasks related multi root work.

**Comment by dbaeumer** [comment]
Done.
