### ISSUE TITLE
Error when saving files to OneDrive

### ISSUE THREAD

**Issue by mars000** [Microsoft/vscode#31361]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
platformio|for|0.2.2
cpptools|ms-|0.12.1
platformio-ide|pla|0.5.1
arduino-vscode|ste|0.2.2
vscode-arduino|vsc|0.2.4
debug|web|0.21.2

(3 theme extensions excluded)

Hi, I am storing all my source files on OneDrive so can easily sync and share across PC and Mac etc.
I find very regularly that I get an error when trying to save files - I get a file it locked or busy. I check on other devices and they are not open and in some cases and close OneDrive on all devices and sill same issue.

---

Steps to Reproduce:

1. Saving a file to OneDrive folder (issue occurs at random)
2.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
very likely dup of https://github.com/Microsoft/vscode/issues/27285

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
