### ISSUE TITLE
Test: Token color customizations

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#31360]
Tests #27894

- [x]  linux- **@joaomoreno**
- [x] windows - **@michelkaporin**

Complexity 2

Test the new setting "editor.tokenColorCustomizations" to modify the token colorization.
The colors and styles configured with this setting will override the color of the current theme.

- try `comments`, `strings`, `numbers`, `keywords`, `types`, `functions`, `variables` with a hex color (e.g. '#FF0000`) to modify the foreground of the given concepts
- try `textMateRules` to pass in an array text mate grammar rules

**Comment by joaomoreno** [comment]
I don't understand how `textMateRules` should work. An example would've been great.
