### ISSUE TITLE
VSCode does not display some unicode characters

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#31366]
- VSCode Version: 1.14.2 (https://aur.archlinux.org/packages/visual-studio-code)
- OS Version: Archlinux x64 (4.11.9-1-ARCH)

Steps to Reproduce:

1. Paste this string `發電廠 樂` into VSCode (not integrated terminal).
2. Observe that VSCode does not display these characters correctly - they are displayed as "empty squares". 

Reproduces without extensions: Yes

File is saved as UTF-8 encoded and VSCode shows UTF-8 at the bottom too. Strange thing is that I can copy this string in VSCode into clipboard and they are correct. My language in Arch is en-US with UTF-8 and since I can see this string correctly at least in Firefox and terminal, I don't think it is an issue with distro.

**Comment by tSte** [comment]
@vscodebot[bot] added two labels, but they are both incorrect.
1. I don't have this issue with integratet terminal.
2. I just tried this with 1.13.x and faced the same issue.

**Comment by tSte** [comment]
Guys, do you have some update on this? I do ;) It seems I have the same issue with [NightmareJS](http://www.nightmarejs.org/) and [Google Chrome from AUR](https://aur.archlinux.org/packages/google-chrome/).

**Comment by ZenMittal** [comment]
These two characters are encoded perfectly in Brackets but shown as blank boxes in VS Code. Is there any way to fix it?
[http://prntscr.com/h8nn8y](url)

**Comment by alexandrudima** [comment]
The OP's characters render fine in VSCode on Windows:
![image](https://user-images.githubusercontent.com/5047891/32724362-44cf4524-c871-11e7-9158-cf1bf26d9c84.png)

So it might be an issue specific to Archlinux.

**Comment by rebornix** [comment]
I don't see any issue on CentOS and Ubuntu, to me it's an upstream issue on Archlinux.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
