### ISSUE TITLE
:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 345

### ISSUE THREAD

**Issue by evandrocoan** [Microsoft/vscode#31362]
- VSCode Version: 1.15.0, commit b689bbe99ea8ecc602520ed8c8b775d46429bc4f
- OS Version: Windows 10 build 15063

Steps to Reproduce:

1. Compile VSCode locally
2. Run the `scripts\code.bat` from console window
3. This error will show up:

    ![image](https://user-images.githubusercontent.com/5332158/28559022-1c245124-70eb-11e7-93de-a9b703bc35f5.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Is this just about a message popping up in the console, or is something actually broken?

**Comment by evandrocoan** [comment]
For now, I only know of about the message popping up on the console. If it is breaking something I did not noticed yet.

**Comment by joaomoreno** [comment]
Great. I'll close it. Electron often prints out such messages.
