### ISSUE TITLE
Redesign Feedback Form dialog

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3136]
To resolve issue #2662 we're going to redesign the form to eliminate the input box. This makes sense because we are using twitter now. 

@bgashler1 hoping to get your help on this.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
