### ISSUE TITLE
Explorer: Should alert confirm when folders moved

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#31374]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.10.0-27-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-emacs|hiro-sun|0.1.1|;

---

Steps to Reproduce:

1.  move a folder to some other folders
2.  no confirm shown.

expected:
1.  move a folder to some other folders
2.  show confirm dialog.
3. if confirmed => move folder
4. if cancelled => do nothing.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1414
