### ISSUE TITLE
Switching between debugs outputs.

### ISSUE THREAD

**Issue by Deathangel908** [Microsoft/vscode#31377]
It would be great if VSCode supported switching between debug outputs, when there are multiple debug targets (atm they are merged):
![image](https://user-images.githubusercontent.com/1336703/28566891-2fa5a466-7139-11e7-890d-f420ebc32fad.png)

- VSCode Version: 1.14.2-1

**Comment by isidorn** [comment]
For this we would need multiple instances of the debug repl -> backlog

**Comment by weinand** [comment]
We have two other console implementations and they already support multiple instances.

**Comment by isidorn** [comment]
Assigning to myself and october to investigate what would it take to have a debug console per session
