### ISSUE TITLE
Git changes split view title does not show actions on hover

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31376]
The actions are there (stage all) but they are not shown on hover.
Started happening today. If I change the theme or reload I am still in the same state

Notice in the screenshot that I am hovering over the CHANGES section and that no actions are being shown

![screen shot 2017-07-25 at 11 32 46](https://user-images.githubusercontent.com/1926584/28565650-1b06e4ae-712d-11e7-885e-b52d0f254b98.png)

**Comment by joaomoreno** [comment]
Sorry about that!
