### ISSUE TITLE
Multi-Cursor, Split Into Lines

### ISSUE THREAD

**Issue by Sub-Xaero** [Microsoft/vscode#31373]
A feature that Sublime Text in particular makes particularly easy, is making a selection with the mouse and then hitting Ctrl+Shift+L, and each of the lines in the selection gets its own cursor. Which is a lot quicker than using the keyboard to one-by-one ad cursors in a line, and seems more intuitive.

This is particularly important is cases such as when the lines you want multiple cursors on are not sequential in the code. So it would be a lot easier to make multiple selections with the mouse, and then split those selections into cursors. 

This functionality is currently implemented by 2 extensions in the marketplace, I have tried both and they're clumsy and don't always work. First-party support seems to be the only solution.

**Comment by Sub-Xaero** [comment]
I hasten to add, column select achieves this partially. But the case I mentioned where the lines you want to edit are not near eachother in the code is not possible with column select

**Comment by rebornix** [comment]
@Sub-Xaero it sounds like the behaviors of the existing extensions are not what you want while it means ppl expect different things about this feature, making it first-class and choose one doesn't 100% solve this problem.

**Comment by rvighne** [comment]
Isn't this already achieved with <q>Add Cursor to Line Ends</q> (<kbd>Shift</kbd>-<kbd>Alt</kbd>-<kbd>I</kbd>)?

Unlike Sublime Text, this does not select whole lines, but it does place a cursor on each one, which seems to be what you want. It would also then be trivial to select each line with <kbd>Shift</kbd>-<kbd>Home</kbd>.

**Comment by Sub-Xaero** [comment]
That's exactly what I want. Thank you. I saw that keybind in the setting but could never get it working. Just worked first time. I think the font in the Keybinds menu is mildly ambiguous, I always assumed it was <kbd>SHIFT</kbd>+<kbd>Alt</kbd>+<kbd>L</kbd, but I tried both and it never worked. Nevermind, thank you, you're a star.
