### ISSUE TITLE
go run: cannot run *_test.go files 

### ISSUE THREAD

**Issue by ChakritRakuang** [Microsoft/vscode#31371]
Installing 3 tools
  godef
  goreturns
  dlv

Installing godef FAILED
Installing goreturns FAILED
Installing dlv FAILED

3 tools failed to install.

godef:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/rogpeppe/godef
# cd C:\Users\Chakrit  Rakhuang\go\src\github.com\rogpeppe\godef; git config remote.origin.url
package github.com/rogpeppe/godef: remote origin not found
# cd C:\Users\Chakrit  Rakhuang\go\src\github.com\rogpeppe\godef; git config remote.origin.url
package github.com/rogpeppe/godef: remote origin not found

goreturns:
Error: Command failed: C:\Go\bin\go.exe get -u -v sourcegraph.com/sqs/goreturns
# cd C:\Users\Chakrit  Rakhuang\go\src\sourcegraph.com\sqs\goreturns; git config remote.origin.url
package sourcegraph.com/sqs/goreturns: remote origin not found
# cd C:\Users\Chakrit  Rakhuang\go\src\sourcegraph.com\sqs\goreturns; git config remote.origin.url
package sourcegraph.com/sqs/goreturns: remote origin not found

dlv:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
# cd C:\Users\Chakrit  Rakhuang\go\src\github.com\derekparker\delve; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/derekparker/delve/cmd/dlv: exit status 128
github.com/derekparker/delve (download)
# cd C:\Users\Chakrit  Rakhuang\go\src\github.com\derekparker\delve; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/derekparker/delve/cmd/dlv: exit status 128

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go
