### ISSUE TITLE
Data in Text data type column gets truncated to 64,096 characters when copied

### ISSUE THREAD

**Issue by aadon** [Microsoft/vscode#31378]
- VSCode Version: 1.14.1
- OS Version: Mac OS X El Capitan 10.11.6

Steps to Reproduce:

1. Create a table with text column and insert a text of size greater than 64096 characters.
2. Select that row, copy the data in text column and paste it in Microsoft Word or somewhere else and count the number of characters. You will see that the number of characters got truncated to 64,096.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@aadon sorry I can't reproduce this issue when pasting to Code or Word on macOS. Can you provide some samples for me to troubleshoot? Updating to latest stable version of VSCode and verify first would be better.

**Comment by aadon** [comment]
I tried it again and it gives the same problem.
```
create table test(temp text);
insert into test values ('some very big text with at least 70000 characters');
select * from test;
```
Now copy the row and paste it somewhere, you will see that the text is truncated.

**Comment by ramya-rao-a** [comment]
@aadon Your example is SQL code. I am guessing your using an extension for this. When copying the row, are you copying from the editor where you typed the sql query or from the results that show up in a different editor?
