### ISSUE TITLE
Cannot contribute keybindings with arguments

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#31372]
According to #14854, we support arguments when defining keybindings.
If we defining keybindings in the `keybindings.json`, it works well.
But when building my extension, I find that `args` field in `package.json` is not recognized and has no effect.

**Comment by jrieken** [comment]
Unsure, why you would do that? A static/default argument could just be in the command implementation, right?

**Comment by neilsustc** [comment]
Because I would like to use built-in command `insertSnippet`

```
{
    "command": "editor.action.insertSnippet",
    "args": "[$TM_SELECTED_TEXT]($0)",
    "key": "ctrl+l",
    "mac": "cmd+l",
    "when": "editorTextFocus && editorLangId == markdown"
}
```

**Comment by jrieken** [comment]
I see, makes sense

**Comment by hei5enbrg** [comment]
Hi all, any update on this?

I'm trying to build an extension, it run certain tasks, like
`        {
            "label": "serial",
            "type": "shell",
            "command": "screen /dev/ttyACM0 9600",
            "problemMatcher": []
        }`

Before I used to add shortcuts to keybindings.json, like
`    {
        "key": "ctrl+shift+alt+p",
        "command": "workbench.action.tasks.runTask",
        "args": "serial"
    }`

Now I as part of the extension try to add it inside 'contributes', as
`        "keybindings": [
            {
                "linux": "ctrl+shift+alt+p",
                "key": "ctrl+shift+alt+p",
                "command": "workbench.action.tasks.runTask",
                "args": "serial"
            }
        ]`
`
Which won't work  :\
Is there any other way to do this?

**Comment by nehayward** [comment]
Is this still ope? If so I can work on this.

**Comment by Raydir** [comment]
@nehayward  you would be my hero :P

**Comment by jrieken** [comment]
@nehayward Go for it!

* this is were the [model](https://github.com/Microsoft/vscode/blob/72fcd264c552ddd94dfbd0807813ba938d8af8d2/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L157) and [json schema](https://github.com/Microsoft/vscode/blob/72fcd264c552ddd94dfbd0807813ba938d8af8d2/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L206) is defined 
* this is where contributed keybindings are [read and fed into the system](https://github.com/Microsoft/vscode/blob/72fcd264c552ddd94dfbd0807813ba938d8af8d2/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L446)
* then I'd update [`IKeybindingsRule2`](https://github.com/Microsoft/vscode/blob/72fcd264c552ddd94dfbd0807813ba938d8af8d2/src/vs/platform/keybinding/common/keybindingsRegistry.ts#L45) with args and pass them along till `_registerDefaultKeybinding` where `commandArgs` is already waiting for you

**Comment by nehayward** [comment]
Whoa! Thanks for the detailed walkthrough @jrieken. I'm going to start today!

**Comment by tecosaur** [comment]
@nehayward Yes!!!!!!!!!!!!!!

\<insert love eyes emoji>

**Comment by nehayward** [comment]
Okay I have some initial changes but I still need help with testing and doing a proper PR. Here's a [PR]( https://github.com/Microsoft/vscode/pull/59911) which will need more work. Thanks for all the help!
