### ISSUE TITLE
[Feature Request] - Folder level settings for a workspace

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/vscode#31379]
- VSCode Version: Insiders
- OS Version: Mac

I am experimenting with VS Code and have several python project folders setup in my workspace. Currently it doesn't seem possible to have folder level settings to specify different virtual environments to use for each folder as well as subfolder/file exclusion rules.

This is a common requirement where - in the case of having multiple python projects - each one has its own rules (virtualenv path to use, python version etc.)

**Comment by sandy081** [comment]
@imdadahad Would like to know what is your project set up? We are working on a Multi root workspace support which is in preview mode now and available in insiders now. In which, you can open multiple folders as roots in the workspace and settings of each root folder are respected.
