### ISSUE TITLE
Show root folder name in tabs when same file name is opened in different group

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#31384]
If I have two files with the same name from different root folders open, the root folder is displayed in the tab in grey, as well (there was an issue for this, but didn't found it):
![image](https://user-images.githubusercontent.com/5795847/28571918-464c71ac-7145-11e7-9524-caa327f8b9c0.png)

Viewing one of this files on the side, the root folders are not displayed but should as well:
![image](https://user-images.githubusercontent.com/5795847/28572244-6fbe8e2a-7146-11e7-9092-91c0a25ead10.png)

cc #28344

**Comment by bpasero** [comment]
This actually is https://github.com/Microsoft/vscode/issues/13350
