### ISSUE TITLE
Git rename and move

### ISSUE THREAD

**Issue by croraf** [Microsoft/vscode#31380]
Is there a way (vscode natively or plugin) to make git file and folder move/rename command so that git doesn't consider my rename and move as deletion and addition of new file.

If not it would be good to add that feature.

**Comment by croraf** [comment]
It seems that git mv is no different than removing and adding a new file? If so this request is not relevant.

**Comment by joaomoreno** [comment]
You got it. :+1:

**Comment by alixaxel** [comment]
@croraf They should be different.

@joaomoreno I think this issue should be reopened.

**Comment by jedmao** [comment]
@joaomoreno I also believe this issue should be reopened. I was just going to submit an issue myself, but saw this issue already exists.

## Expectations
1. If I rename a folder under Git version control, perform the appropriate [`git mv`](https://git-scm.com/docs/git-mv) command (e.g., `git mv ./foo ./bar`).
1. If I rename a file under Git version control, perform the appropriate [`git mv`](https://git-scm.com/docs/git-mv) command (e.g., `git mv foo.js bar.js`).

![good-bad](https://user-images.githubusercontent.com/1058243/32141874-6a8a3a56-bc48-11e7-9269-4f604a8093c7.gif)

**Comment by alixaxel** [comment]
All the changes need to be staged for the renames to be aknowledged.

**Comment by jedmao** [comment]
@alixaxel good point! vscode is showing my changes as renamed. I don't see an issue here any more.
