### ISSUE TITLE
Color issue with Typescript

### ISSUE THREAD

**Issue by Ehstrali** [Microsoft/vscode#31389]
- VSCode Version: 1.14.2 and before
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

In a .ts file:

let a: number = w, // number is colored
b: string = x,          // string is not colored
c: any = y,              // any is not colored
d: boolean = z;      // boolean is not colored

let e: any;              // any is colored
let f: boolean;       // boolean is colored
...

(It also works with const and var).

All the types should be colored but they are not when using commas: 
let something, somethingelse: any

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/491 to track this upstream

Closing as upstream
