### ISSUE TITLE
SCSS not suggesting nested tag completions

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31385]
- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:20:25.274Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. if you type a tag at the root level of a SCSS file, it will suggest tags as expected.  Here it suggests `input`:

![screen shot 2017-07-25 at 9 05 41 am](https://user-images.githubusercontent.com/835148/28573416-9654d644-7118-11e7-8a29-f65c52f43e05.png)

2. However, inside a nested selector, it forgets all about `input`:

![screen shot 2017-07-25 at 9 04 44 am](https://user-images.githubusercontent.com/835148/28573454-b189b22c-7118-11e7-92d8-f960ff0f0916.png)

by nested selector, i mean

````
.my-outer-selector {
    input {
      color: green;
    }
}
`````

Same happens with every tag I've tried:  `button`, `div`, etc.

**Comment by ramya-rao-a** [comment]
The tag suggestions are coming from css completion provider and not emmet, re-labeling

**Comment by aeschli** [comment]
That's was a request from https://github.com/Microsoft/vscode/issues/17578 as it is, rather uncommon to nest tags.

**Comment by smlombardi** [comment]
@aeschli It's not as uncommon as you think.  we frequently apply a class to the `body` tag (this is especially common in Wordpress) and then add tags and classes inside of that to make overrides for just that page.
