### ISSUE TITLE
Code helper : High CPU usage on macOS Sierra 

### ISSUE THREAD

**Issue by sanghin** [Microsoft/vscode#31388]
- VSCode Version: 1.14.2
- OS Version: macOS Sierra Version 10.12.5

Steps to Reproduce:

1. Open vs code
2. wait 

Reproduces without extensions: Yes

`ps aux | grep -i code`
````
damien           29107 100,0  3,1  3428428 261784   ??  R     3:45     8:39.02 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/damien/Library/Caches/typescript/2.4 --enableTelemetry
damien           29165   0,0  0,4  3238904  29772   ??  S     3:46     0:01.34 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
damien           29106   0,0  0,5  3318432  40732   ??  S     3:45     0:10.41 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/yn/660wq__n6js538lhbm47gd0c0000gn/T/vscode-tscancellation-378a3d8805953d4e2451.sock*
damien           28897   0,0  0,4  3158564  29432   ??  S     3:44     0:00.41 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css/node_modules/vscode-languageclient/lib/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css/server/out/cssServerMain.js --node-ipc
damien           28895   0,0  0,1  2464108  11160   ??  S     3:44     0:00.01 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/yn/660wq__n6js538lhbm47gd0c0000gn/T/VSCode Crashes --metrics-dir=/var/folders/yn/660wq__n6js538lhbm47gd0c0000gn/T/VSCode Crashes --url=https://rink.hockeyapp.net/api/2/apps/21a48a66799e47fea4f52c0ff81e803d/crashes/upload --handshake-fd=58
damien           28893   0,0  0,4  3232568  35024   ??  S     3:44     0:01.48 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
damien           28892   0,0  0,5  3247868  43104   ??  S     3:44     0:03.78 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
damien           28881   0,0  0,8  3313816  64880   ??  S     3:44     0:01.28 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=17E325E1422625ABDF38593DBB836E22 --lang=fr --node-integration=true --hidden-page --enable-pinch --num-raster-threads=2 --enable-gpu-rasterization --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,34037;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,34037;2,13,3553;2,14,34037;2,15,34037;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037 --service-request-channel-token=17E325E1422625ABDF38593DBB836E22 --renderer-client-id=6
damien           28880   0,0  1,7  4381240 143020   ??  S     3:44     0:36.70 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=6B472CBBD9BAE0A2E8ED0AE61DAE4FC1 --lang=fr --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=2 --enable-gpu-rasterization --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,34037;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,34037;2,13,3553;2,14,34037;2,15,34037;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037 --service-request-channel-token=6B472CBBD9BAE0A2E8ED0AE61DAE4FC1 --renderer-client-id=4
damien           28877   0,0  0,8  2920532  63376   ??  S     3:44     0:10.28 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=0,1,10,23,25,35,38,45,51,59,61,62,63,64,66,70,71,73,81,82,83,86,88,89 --gpu-vendor-id=0x8086 --gpu-device-id=0x5926 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x5926 --service-request-channel-token=3B0208FFC95A3A5EB09BA8F6066FB68D
damien           28876   0,0  1,1  3529428  94840   ??  S     3:44     0:11.94 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
root             28548   0,0  0,1  2471644   5420   ??  Ss    3:39     0:00.03 /System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper
damien           27978   0,0  0,2  2557844  13716   ??  Ss    3:32     3:17.48 /System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService
damien           30196   0,0  0,0  2451236   2004 s003  S+    3:56     0:00.00 grep -i code````
````
Extensions : 

![image](https://user-images.githubusercontent.com/3429798/28575585-a7f2c968-7151-11e7-806e-e01e5c007555.png)

**Comment by App1905** [comment]
you can try restarting you mac, hope helpful

**Comment by jkwuc89** [comment]
I am seeing this as well inside VS Code 1.14.2. To make matters worse, the Code Helper process is left running when I quit VS Code.

**Comment by jkwuc89** [comment]
Here are some simple reproduction steps for this issue:

1. Open a terminal and change to your $HOME directory
2. Run `code --disable-extensions .`
3. Open Activity Monitor. Observe that the Code Helper process is running at well over 100% CPU usage. My guess is that this is caused by it parsing through the entire $HOME directory tree structure.
4. Quit code by pressing Cmd + Q. Inside Activity Monitor, observe that Code Helper is still running and its CPU usage is still over 100%. It does eventually go away.

**Comment by bpasero** [comment]
The original authors process that is 100% seems to be TypeScript: `damien           29107 100,0  3,1  3428428 261784   ??  R     3:45     8:39.02 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/damien/Library/Caches/typescript/2.4 --enableTelemetry`

**Comment by arxpoetica** [comment]
Following @jkwuc89's steps, I can confirm that it's freaking out, specifically in the $HOME directory:

![image](https://user-images.githubusercontent.com/111424/30387878-365064fa-986b-11e7-88bc-ea49c5257fa6.png)
![image](https://user-images.githubusercontent.com/111424/30387901-459c6292-986b-11e7-9264-08089d7066fc.png)

**Comment by wind2412** [comment]
I have the same problem. Vscode version is the newest `1.16.1` now. However the CPU level is so high and my mac got very hot. Although I quitted vscode, the two `code helper` processes are working background so that I must kill them by myself. I'm writing c++.

**Comment by darkdescendant** [comment]
Ditto with VSCode 1.7X I just updated today. Even after quitting VSCode Code helper and it's python processes absorbed all the memory on my machine (disk and RAM). The only time I've ever seen Mac OS X complain about  system put of memory is the 2 times I've tried to use VSCode at work. Not sure what is going on but obviously there is some sort of run away processing going on with codehelper.

The code base I am using this on is a large C++ and C# code base.

**Comment by xiaoshuw** [comment]
I have the same problem with 1.17. What is strange is it only occurs to one project directory. Don't know why is that as other directory used to develop vue component seems all right. I have tried to set useExperimentalWater and add file.excludes etc. It is the same result.

**Comment by wind2412** [comment]
@darkdescendant After I banned the Microsoft C++ extensions, my cpu level seems to be normal again. My Activity Monitor tells me the Microsoft C++ extensions make cpu in a high level. However, C++ extensions got updated yesterday and I didn't make a test. @xiaoshuw Vue I don't know...

**Comment by darkdescendant** [comment]
Yeah, I figured it was that extension. But since that is the whole reason for me in using VSCode over Sublime it kind of kills it for me. :-(

I might re-install and see what happens since you noted the extension was updated.

**Comment by darkdescendant** [comment]
Maybe this issue is related: https://github.com/Microsoft/vscode-cpptools/issues/1114

**Comment by xiaoshuw** [comment]
Well, mine doesn't have the C/C++ extension. Also, it doesn't have issues in one project but does have on another. As I am using the vscodevim, it renders the vscode useless because after one key stroke, it seems waiting for the run-away process so it effectively useless. I didn't have problem with 1.16, it only started after recent update.

**Comment by markeissler** [comment]
High CPU on macOS is the number one thing that drives me nuts on VSCode and the very next thing is the fact that it's such a pain to debug. MS really needs to provide some tools outside of the standard Google Dev Tools (which don't make it easy).

What I want to see is that VSCode monitors resource usage and runaway extensions. I want to see a pop up or some other easy-to-read diagnostic along with an offer to disable the offending extension. The last thing I want to do is to spend so much time debugging my development tools themselves.

**Comment by mjbvz** [comment]
@sanghin Do you still see the originally reported TypeScript cpu issue on [VSCode 1.18 insiders](https://code.visualstudio.com/insiders/)? If so, does this reproduce for all folders you open or just some of them?

For anyone seeing high cpu usage with the C++ extension, please try following up with that extension instead

**Comment by xiaoshuw** [comment]
I can no longer see the run away process anymore -- with the same 1.17. I didn't do anything - besides in between I have probably rebooted my machine a few times. I didn't use TypeScript. As I said earlier, I have two projects of similar setup. Only one project had this issue.

**Comment by wind2412** [comment]
In fact, I think the C/C++ Extension gets much better after updating its version. These days there is only one time getting very hot but soon it gets normal cpu level.

**Comment by sanghin** [comment]
@mjbvz Sorry for my late (late) response. This issue can be closed. I'm now on : 

- VSCode 1.17.2 (1.17.2)
- High Sierra Version 10.13

I'm pretty sure that the issue was caused by an incomplete configuration of file.exclude and search.exclude options

**Comment by arxpoetica** [comment]
It's still burning extremely hot in my `$HOME` folder on Mac:

1. Go to $HOME directory
1. type `code --disable-extensions .`
1. watch it burn:

![image](https://user-images.githubusercontent.com/111424/32265846-6c18c9d8-bf17-11e7-8a3a-3710e0aa99c1.png)

![image](https://user-images.githubusercontent.com/111424/32265858-78b6d7b6-bf17-11e7-8048-43de56c8a415.png)

**Comment by francoiscabrol** [comment]
I have the same issue with macos sierra, Code helper takes 100% CPU

**Comment by sanghin** [comment]
> Code Version 1.17.2 (1.17.2) is still burning extremely hot in my $HOME folder on Mac:

You should add some ignore rules in your user settings (files.exclude and search.exclude), vscode tries to index every files in your $HOME folder

**Comment by francoiscabrol** [comment]
I have added the rules but it didn't fix the issue. But finally I installed the old 1.17.2 version (instead of the 1.18) and it looks stable now

**Comment by r-kat** [comment]
I had to uninstall Visual Studio because of high CPU usage with maximum of over 120% and minimum of 5% even at the lowest usage it is insane. Could not kill process, restart took more than few minutes.

I am using latest version and really wanted to like it due to it's very good look and feel and prebuilt extensions compared to other editors which has no control over external extensions.

**Comment by arxpoetica** [comment]
@sanghin one shouldn't have to install ignore rules to keep an index from crashing ms code.

![image](https://user-images.githubusercontent.com/111424/32884964-9e5f9132-caee-11e7-86ee-8c552763ec96.png)

**Comment by fpiraneo** [comment]
Same issue here! I don't use any C++ extension... just writing LaTeX document.
Again please: What I have to do to preserve my battery level from falling down at 10% in less than 10 minutes?
