### ISSUE TITLE
code crashes when I leave it running overnight

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#3138]
Every morning i have the crash screen waiting to greet me.
This happens with both production and insiders builds.
Is there a log i can send you so you can assign so you can match it with your crash logs assuming you are getting them from me.

**Comment by DickvdBrink** [comment]
Dup of #508?

**Comment by egamma** [comment]
Yes looks like a dup of #508. @justin-romano we would appreciate if you could characterize the workspace you have open that causes the crash.
