### ISSUE TITLE
Search and replace of a text only on selected code lines

### ISSUE THREAD

**Issue by IlyaSofronov** [Microsoft/vscode#31386]
Sometimes I just need to find the keywords in some paragraphs of code, not in whole code.
It's useful just to select part of a text and find that I need

**Comment by thw0rted** [comment]
This feature already exists.  Edit --> Find, click the "Find in selection" button on the search widget, select some text, type your word.  It should search only in the selected text.  There is also a preference you can set, `editor.find.autoFindInSelection`, which does exactly what it says.

**Comment by rebornix** [comment]
@thw0rted thanks!
