### ISSUE TITLE
Incorrect link underline in template string

### ISSUE THREAD

**Issue by g-harel** [Microsoft/vscode#31397]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-cdnjs|Jak|0.14.3
sort-lines|Tyr|1.3.0
vscode-icontheme-nomo-dark|be5|1.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
auto-close-tag|for|0.4.3
gitblame|wad|2.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. use `https://www.scribd.com/embeds/'${scribdId}` in a template string in a javascript file

This will interpret the whole thing to be a link, underline it and allow cmd/ctrl clicks to a broken url.
![image](https://user-images.githubusercontent.com/9319710/28580889-c87a9c6a-712e-11e7-9754-4775516011a7.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This is by design and not js specific. The default link highlighter looks for url-like sequences of characters in code. It does not attempt to evaluate what the string will actually be a runtime

If this is getting in the way, you can disable it by setting: `editor.links": false`

**Comment by g-harel** [comment]
@mjbvz 

Yes, It should not evaluate it, but it also shouldn't consider the code to be part of the url. It is inconsistent with the syntax highlighting and can cause confusion. 

Right now it redirects to `https://www.scribd.com/embeds/'$%7BscribdId%7D`.

I am not sure how feasible it would be, but I would make urls terminate when they run into the `${` sequence in a template string.
