### ISSUE TITLE
[Feature request] Scroll offset/cursor margin parameter

### ISSUE THREAD

**Issue by pgrz** [Microsoft/vscode#31393]
I'd love to see a similar feature to vims scroll offset: parameter that controls how many columns/rows from the window edge can the cursor be at minimum. Right now it seems to be set to 2 for rows at bottom, 1 for rows at the top, 2 for columns on the right and about 5 for columns on the left.

[Vim wikia page](http://vim.wikia.com/wiki/Keep_your_cursor_centered_vertically_on_the_screen) for reference.

**Comment by pgrz** [comment]
For the record: there is an [extension](https://marketplace.visualstudio.com/items?itemName=kaiwood.center-editor-window) that adds a hotkey to center scroll on the cursor - without parameters or autocentering.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/12048.
