### ISSUE TITLE
Add action for "Switch to Editor View"

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#3139]
![switchtoeditor](https://cloud.githubusercontent.com/assets/6125444/13159282/3486d2f0-d691-11e5-93a2-7e59e3eedd58.png)

The "Switch to Changes View" button in the top right of an editor has the command ```workbench.git.action.globalOpenChange```, but the corresponding "Switch to Editor View" button has no command. Well it looks like it might be ```workbench.git.action.openInEditor``` but that isn't made public or something because trying to execute it doesn't work, and I can't find anything in the list of commands.
 
I'd like them both to have commands so I can switch back & forth between changes and editor view with keyboard shortcuts.

**Comment by joaomoreno** [comment]
Added `workbench.git.action.globalOpenFile` global workbench action.

**Comment by stkb** [comment]
thanks :)

**Comment by bpasero** [comment]
:+1:
