### ISSUE TITLE
No way to choose format of doc if not saved

### ISSUE THREAD

**Issue by timheuer** [Microsoft/vscode#31392]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0
mono-debug|ms-|0.15.6

---

Steps to Reproduce:

1. Create a new file
2. Start typing markdown (or something else)
3. Open preview mode
EXPECT: Syntax hilighting for MD format and preview
ACTUAL: no highlighting or preview 

You need to save the file first to get this based on the file extension.  This is a good start, but it should enable me to select a format first before saving to get this.  Notepad++ allows me to do this easily before saving and enables me to save a doc as tim.foo (random file extension) and still select the format of the contents to be a file type.

![screenshot 12](https://user-images.githubusercontent.com/4821/28578371-6cd21fde-710e-11e7-817c-691c8bc590dd.png)

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
You can run `Change Language Mode` from command palette or click the language name on the right bottom of the editor (on the status bar) and switch the Markdown.

**Comment by timheuer** [comment]
WHAAAAAAT.  Awesome thanks.  Weird that menus are in status bars.  Options/settings for Code seem to be in various places.
