### ISSUE TITLE
Integrated Terminal is not working

### ISSUE THREAD

**Issue by bemartin** [Microsoft/vscode#31400]
- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:30:52.414Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
gitlens|eam|4.3.2
tslint|eg2|0.17.0
beautify|Hoo|1.1.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vscode-icons|rob|7.11.0

---

Steps to Reproduce:

1. Launch VS Code
2. Launch Terminal
![image](https://user-images.githubusercontent.com/6611598/28583909-b3b9ed12-711f-11e7-85dd-8d52b30609a2.png)

Reproduces without extensions: Yes

**Comment by batjko** [comment]
I am seeing the same thing, also with the `undefined` as the terminal name in the drop down.

To add: I have the 64-bit version of cmd set up as my terminal in the settings:

```json
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe"
```

**Comment by bemartin** [comment]
I didn't realize that the integrated shell was configured. The issue is that there is no such directory as "sysnative". Changing the setting to the correct path fixes the issue:
`terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\cmd.exe`

**Comment by batjko** [comment]
@bemartin Yup, indeed.
I don't remember where that path was suggested. But either way, for some reason this worked for weeks though.

Not sure, but this is fixed for me, as well.

**Comment by Tyriar** [comment]
You will need to use `C:\\Windows\\System32\\cmd.exe` in the 64-bit client.

**Comment by fjsuarez** [comment]
@bemartin Using `terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\cmd.exe"` will not allow you to launch `bash` . It returns
```
'bash' is not recognized as an internal or external command,
operable program or batch file.```
Use `C:\\Windows\\System32\\cmd.exe` instead, as @Tyriar said.

**Comment by rozzzly** [comment]
@batjko `C:\\Windows\\System32\\cmd.exe` will run the plain old Windows console which might work for some programs/commands like how you had it set up before (depending on what software you've installed in the past) but I'm assuming you're trying to get your shell to be bash from WSL (Windows Subsystem Linux). This can be achieved by setting `terminal.integrated.shell.window` to  "C:\\Windows\\System32\\bash.exe"

**Comment by batjko** [comment]
@rozzzly Thanks for that. I wasn't looking to use bash, actually. I'm quite happy with the plain old Windows console ;)

**Comment by josersleal** [comment]
you should test before releasing
