### ISSUE TITLE
Open new file at the end of open files tab

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#31404]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.3.9600
---------------------------------------------

Hi,
Please enable on setting when opening new file, this file show at the end of opened files tab on top.

![image_67](https://user-images.githubusercontent.com/5067331/28586495-4fcb91f6-7189-11e7-87f8-2ea6454ed8b3.jpg)

Now for example when I working on second file, then open new file, this file show after of before opened file and I have problem by this because the order of the open files tab, mixed.

Thanks
@rebornix @alexandrudima

**Comment by miladghiravani** [comment]
@rebornix @alexandrudima

**Comment by miladghiravani** [comment]
Hi dear @rebornix 
This feature will be in the next version?

**Comment by bpasero** [comment]
`workbench.editor.openPositioning: last`
