### ISSUE TITLE
Linter does not find all errors that the browsers do

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#3140]
a `continue;` that is not within a `for` should be an error.

**Comment by egamma** [comment]
Given that there are now high quality linters for JS available (eslint, jshint) and there are also extensions for these linters with Code available, the will deprecate the built-in linter support in the next update. 

Is this decision a problem for you? Can you try the eslint or jshint code extensions?

**Comment by justin-romano** [comment]
What about Type Script? (not using it yet in this project but will)
But fair enough. Which is the best JS linter for vscode?

**Comment by egamma** [comment]
>Which is the best JS linter for vscode?

Based on the download# of the extensions I'd say eslint, it has 25% more downloads.

>What about Type Script? (not using it yet in this project but will)

Actually the JavaScript language support is powered by TS. TypeScript 1.8 will add more linting checks. If you want linting for TypeScript then we recommend to use tslint (for which there is also a Code extension.

**Comment by justin-romano** [comment]
Well i think you will kill code if you remove the linting.
Its i bit buggy but i uninstalled both alternatives in disgust.
They are awkward to configure and put big red lines under things that don't
matter like indenting and line endings.
You need something there but its just got to pick up real error. Something
you have done which will not run or just dumb things like missing `var` or
extra commas


On Fri, Feb 19, 2016 at 11:44 AM, Erich Gamma <notifications@github.com>
wrote:

> Closed #3140 <https://github.com/Microsoft/vscode/issues/3140>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/3140#event-555824216>.
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by justin-romano** [comment]
You need this to be instantly useful for editing JS in my opinion :)

On Fri, Feb 19, 2016 at 12:07 PM, Justin Romaine <justin.romaine@gmail.com>
wrote:

> Well i think you will kill code if you remove the linting.
> Its i bit buggy but i uninstalled both alternatives in disgust.
> They are awkward to configure and put big red lines under things that
> don't matter like indenting and line endings.
> You need something there but its just got to pick up real error. Something
> you have done which will not run or just dumb things like missing `var` or
> extra commas
>
>
> On Fri, Feb 19, 2016 at 11:44 AM, Erich Gamma <notifications@github.com>
> wrote:
>
>> Closed #3140 <https://github.com/Microsoft/vscode/issues/3140>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Microsoft/vscode/issues/3140#event-555824216>.
>>
>
>
>
> --
> Justin Romaine
> Senior Systems Architect
> Spark Dental Technology
> justin.romaine@gmail.com
> ph 021 764 506
> hm 09 445 9166
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by egamma** [comment]
>Well i think you will kill code if you remove the linting.

Thanks for your open feedback.  I agree that the out of the box experience isn't that nice anymore. I'll try to some fixing/band-aid in the change notes docs for now. We can help with the setup of eslint by providing you with an action to create an eslintrc. At the same the Salsa team has started discussion on providing more warnings. Pls see: Microsoft/TypeScript#6802.

**Comment by egamma** [comment]
Another option is that we bundle vscode-eslint
