### ISSUE TITLE
"Tasks: Run test task" doesn't pickup detected task that is in the TaskGroup.Test group

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#31406]
- VSCode Version: 1.14.2
- OS Version: Win10

I'm adding a custom detected task with code like this in the julia extension:
````julia
            let testTask = new vscode.Task({ type: 'julia', command: 'test' }, `Run tests`, 'julia', new vscode.ProcessExecution(juliaExecutable, ['--color=yes', '-e', 'Pkg.test(Base.ARGS[1])', vscode.workspace.rootPath]), "");
            testTask.group = vscode.TaskGroup.Test;
            testTask.presentationOptions = { echo: false };
            result.push(testTask);
````
The task gets detected, i.e. it shows up when I run the "Tasks: Run task" command. I would have expected that it also shows up when I run the "Tasks: Run Test Task" command, but it doesn't.

**Comment by dbaeumer** [comment]
This got already fixed. The test group was internally wrongly label clean :-(
