### ISSUE TITLE
Git integration and built-in terminal do not "understand" from which root the current file is open

### ISSUE THREAD

**Issue by dr-nafanya** [Microsoft/vscode#31401]
- VSCode Version: **1.15 - Insiders**
- OS Version: **macOS Sierra 10.12.5**

Steps to Reproduce:

1. Create a multi-root workspace, where every root is separate repository, for example roots **A**, **B** and **C**.
2. Try opening file from root **A** and then from **B** and then from **C**.

The following issues are observed:

1. The VS Code Git integration does not "understand" from which root/repository the file is open and hence cannot highlight the changes in file opened from roots **B** and **C**.
2. The built-in terminal also does not "understand" from which root the **current** file is open, and no matter from which root the file is open, will still be opening the root **A** directory.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This will come with #31325
