### ISSUE TITLE
Add support for opening text documents as readonly (API)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#31410]
I've had a contribution of an explorer tree to show packages referenced by the current project. Because it's Dart, the packages are text on disk (not binary). Clicking on them opens the packages files so you can browse through them using `openTextDocument` however they're editable by the user.

As far as I can tell, there's no way to open a document as readonly? I saw that I can provide a readonly text document as HTML, but that means losing all the langauge support (highlighting, etc.) and having to convert code files into HTML!

It would be great if we could specific that a file should be readonly when calling `openTextDocument`.

**Comment by jrieken** [comment]
> Because it's Dart, the packages are text on disk (not binary)

With or without write access? What you can do is, not use `file`-uris but register a text document content provider with a custom uri-scheme. That will open them as readonly, no need for html

**Comment by DanTup** [comment]
@jrieken Oh, I'd come across [this sample](https://github.com/Microsoft/vscode-extension-samples/blob/ad39f8c2dde7b19b3e872341c00d7d0396642a06/previewhtml-sample/src/extension.ts#L56) which returns HTML  and assumed a text content provider always returns HTML. If not, how does it decide which language to use for highlighting etc.?

Thanks!

**Comment by jrieken** [comment]
Yeah, totally possible. To determine the language it does what it always does, looking at the name/suffix and in doubt also at the first line. So, a `dart:somefile.dart`-resource will be resolved using the provider registered for `dart`, the name will derived from the `somefile.dart`-path

**Comment by DanTup** [comment]
@jrieken Awesome; thanks! In that case there's probably nothing to do here, so feel free to close if you don't think other explicit support for readonly is necessary 👍

**Comment by jrieken** [comment]
Ok, closing in that case. Thanks for getting back to me.

**Comment by DanTup** [comment]
Tested it out; worked perfectly 👍
