### ISSUE TITLE
Feature request: Language completion in Terminal

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode#31411]
Terminal/Console is fundamental to languages like R and Python. VS provides completion in the Interactive Window so it would be great if VSC allowed extension to

a. Set language to the terminal (say, "R")
b. If language is set, call the respective language server for the completion

**Comment by Tyriar** [comment]
You can do this using the current API, you just need to find the executable to launch in the executable yourself. No plans to add this to core though.

**Comment by MikhailArkhipov** [comment]
What is the current API to display the completion window over the terminal?
