### ISSUE TITLE
Clear in integrated console does not remove scroll bar

### ISSUE THREAD

**Issue by shimmy568** [Microsoft/vscode#31415]
- VSCode Version: 1.14.2
- OS Version: Linux Mint 18.1 64bit

Steps to Reproduce:

1. Open integrated console
2. Enter commands until scroll bar appears on right hand side
3. Run clear command in terminal to clear

Reproduces without extensions: Yes

Issue: 
When using the integrated console and you use the clear command the console scroll bar does not go away and is like it was before running the clear command.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
