### ISSUE TITLE
JS linter randomly kicks in, even though it's disabled

### ISSUE THREAD

**Issue by SEAPUNK** [Microsoft/vscode#31419]
For some reason, even though in the settings I have:

```json
{
  "javascript.validate.enable": false,
  "typescript.validate.enable": false
}
```

after editing a bunch of files, the JS linter randomly kicks in on random open files:

![screen shot 2017-07-25 at 4 29 46 pm](https://user-images.githubusercontent.com/4400726/28598148-8c4bf860-7156-11e7-8784-422174610827.png)

![screen shot 2017-07-25 at 4 28 14 pm](https://user-images.githubusercontent.com/4400726/28598107-51c71062-7156-11e7-961a-592d805f062b.png)

Reloading the window temporarily fixes the issue.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
python|don|0.6.9
vscode-npm-script|eg2|0.2.0
prettier-vscode|esb|0.21.0
vscode-npm|fkn|3.3.0
flow-for-vscode|flo|0.7.1
path-autocomplete|ion|1.6.0
vscode-elixir|mjm|0.5.0
atom-keybindings|ms-|2.9.1
cpptools|ms-|0.12.1
PostCSS|ric|1.0.1
partial-diff|ryu|0.3.1
stylelint|shi|0.28.0
gitblame|wad|2.0.2

---

Steps to Reproduce:

1. Edit files, open files, close files
2. JS linter randomly kicks in

Reproduces without extensions: ???

**Comment by mjbvz** [comment]
This should have been fixed by 19e74856910189ffc465be31988ba88a7984d2e0, at least for the `[js]` problems.

Please try out the [current VSCode insiders builds](https://code.visualstudio.com/insiders) or VS Code 1.15 once it comes out and let me know if you still see this problem
