### ISSUE TITLE
Improve UI of API 

### ISSUE THREAD

**Issue by triphosphate** [Microsoft/vscode#31413]
![image](https://user-images.githubusercontent.com/3376668/28589986-7c61322e-714e-11e7-9279-221f1e182e50.png)
When I use mouse to check these API, I found it is not easy for me to check which part is api help string.
It would be great if u guys improve the UI... 

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@triphosphate what theme are you using? It looks like the theme doesn't have enough contrast to the background of hover.

**Comment by triphosphate** [comment]
Monokai… Yes, some themes work well but others not. 

Sent from Mail for Windows 10

**Comment by aeschli** [comment]
@triphosphate Please name the theme that need improvement. I went through the built-in themes and found that they all either have a hover border or a background color that is different enough from the editor background.

**Comment by aeschli** [comment]
Monokai shipped with VSCode:
![image](https://user-images.githubusercontent.com/6461412/29079624-efc5e60a-7c5d-11e7-8785-51e66db8feb1.png)
Monokai dimmed:
![image](https://user-images.githubusercontent.com/6461412/29079702-1a7d6756-7c5e-11e7-9635-02ca5b616411.png)

IMO the built-in themes look good. Please file the issue against the theme extension where you see the problem.
