### ISSUE TITLE
Allow dragging and dropping of files from explorer across multiple windows

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode#31414]
Currently, if you have two VS Code windows open with different folders, and try to drag a file from the explorer window of one into the explorer window of another, nothing happens.

It would be nice if this moved or copied the file (or maybe asked whether you wanted to move or copy it).

**Comment by Polyergic** [comment]
On macOS, I can hold alt and get the + icon that indicates copy instead of move.  But the file doesn't get copied.

Why isn't this a bug?

**Comment by Polyergic** [comment]
@isidorn, which other issue already tracks this problem?
