### ISSUE TITLE
Could vscode support search/replace history feature?

### ISSUE THREAD

**Issue by ricardo0624** [Microsoft/vscode#31426]
like the title,could vscode support search/replace history feature?

- VSCode Version:1.14.1
- OS Version:win10 64

Steps to Reproduce:

1.open a file anyway
2.ctrl+f,this is no way to show the search history

Reproduces without extensions: no

thanks a lot, I enjoy using vscode.

**Comment by cleidigh** [comment]
@ricardo0624 
The Code  Find widget does support history.
The default key bindings are:
- Alt+ArrowDown
- Alt+ArrowUp
- Focus must be on the widget

There is not currently a drop-down list, you can just navigate up and down in the history.
The integrated terminal Find will also have history after an upcoming PR.

**Comment by roblourens** [comment]
Right, alt+up/alt+down is the right way to do this.

**Comment by ricardo0624** [comment]
Thanks a lot,I don't find the key bindings!
