### ISSUE TITLE
No errror tips

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#31424]
- VSCode Version: 1.14.2
- OS Version: Windows 7

Steps to Reproduce:

1. Create a js file
2. Write `const a='test'; let a = 'a';`, there is no error tips.
3. It works well on 1.13

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
We only report semantic errors in JS files if you [enable checkJS](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files)

Extensions like eslint can also report these errors
