### ISSUE TITLE
Need a new setting for toggle Find widget can be over first line or not.

### ISSUE THREAD

**Issue by zheung** [Microsoft/vscode#31423]
- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:30:52.414Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:
1. ctrl+f to show the `Find widget`;

It's good feature but i hate it. It try to change my focus.
In my custom, after scroll the file to top, the top is always the first line of file.
But now, I can't sure the top is the first line of file or the Find widge.
It's uncertain! So I need a setting for toggle feature.

eg. when compare two file with two row, only one file show the Find widget, two file is not sync after scroll to top.
![1](https://user-images.githubusercontent.com/894004/28600690-20056304-71e6-11e7-80f3-892806577174.gif)

![3](https://code.visualstudio.com/images/1_13_uncover-matched-results.gif)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28390 , let's track it there.
