### ISSUE TITLE
Terminal with ID 1 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#31428]
**TypeScript Version:**  fed03b66 

![image](https://user-images.githubusercontent.com/461084/28605193-8822cfde-71a6-11e7-936d-9a37d858b764.png)

![image](https://user-images.githubusercontent.com/461084/28605201-93e3457e-71a6-11e7-9d64-eff60a3d43be.png)

happens when running a TS watch task using Ctrl + Shift + B. On Windows 10 x64 (using x64 version of vscode insider as well)

**Comment by Tyriar** [comment]
I believe this has been fixed, either that or it's related to https://github.com/Microsoft/vscode/issues/31737
