### ISSUE TITLE
Win10: Open Vscode Windows Repeatedly at the same time

### ISSUE THREAD

**Issue by YonglianQian** [Microsoft/vscode#31421]
--when i use [code.] powershell to open vscode.it may cause that open vscode repeatedly at the same time.i Just only wanna code Project In the current directory.
在命令行工具powershell使用code.命令打开当前目录项目，会同时打开之前编辑保存的vscode窗口.导致打开两个vscode窗口。这似乎不是我想要的.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
vue|liu|0.1.5
csharp|ms-|1.11.0
vetur|oct|0.9.3
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by YonglianQian** [comment]
powershell 命令行使用code.命令打开当前目录项目，会同时打开之前编辑保存的vscode窗口.导致打开两个vscode窗口。这似乎不是我想要的.win10 ,vscode1.14.2

**Comment by rebornix** [comment]
You can change setting `window.restoreWindows` to what you want :)

**Comment by YonglianQian** [comment]
Worked Perfectly ,Thanks very much
