### ISSUE TITLE
Request: Close working tree diff when a file is staged

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode#31429]
Personally, I like to view the working tree diffs before staging a file (by clicking the unstaged file in the git pane). After staging the file, the diffs disappear, and the diff tab stays open.

Given that after staging a file the diff tab displays only the file itself, it is useless after staging the file, and I frequently end up closing these. It would be nice if either these diffs closed automatically or if they switched to index diffs so that the diff is still shown (or maybe have an option between doing those two).

**Comment by joaomoreno** [comment]
#18651
