### ISSUE TITLE
Can not open folder that contain non binary file

### ISSUE THREAD

**Issue by ssuupper** [Microsoft/vscode#31427]
In resource manager ,when I expand folder that contains non binary file,Error will prompted:窗口故障 

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

**Comment by bpasero** [comment]
@ssuupper can you share a screenshot?
