### ISSUE TITLE
Smoke test: Failed to create autodetected launch.json

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31438]
See TFS build id 30914 for details.

**Failed test:**
 3) Smoke Test Suite Debugging JavaScript autodetects program attribute for launch.json
**Other tests impacted by this failure:**
 4) Smoke Test Suite Git verifies current changes are picked up by Git viewlet

Seems like Node.js debug environment configuration failed to create launch.json file. I've tried to manually perform test steps, and I wasn't able to get even to debug environment selection on Windows (pressing 'Configure' gear button in Debug viewlet did not give any result with the following error in Chromium console:
`TypeError: Cannot read property 'openConfigFile' of undefined`.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/31435
Good catch smoke test!
