### ISSUE TITLE
更新后缩进有问题

### ISSUE THREAD

**Issue by bestime** [Microsoft/vscode#31430]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.4.3
vue-snippets|hol|0.1.2
vscode-icon-theme|jtl|1.5.0

---

Steps to Reproduce:

1.<style>和<script>标签自动缩进错乱

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
This should be fixed in insider and you can see the update from next Stable.
