### ISSUE TITLE
"Open Recent" doesn't remember the most recent items

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#3143]
It seems that when "Open Recent" fills up, it doesn't expunge the oldest item and move everything else down the list in favor of the newest item at the top. This same behavior applies equally to recent folders and recent files. 

This is on Windows 7.

**Comment by bpasero** [comment]
I cannot reproduce this on Mac at least, but that should not make a difference. If you can record a video and show me what goes on?

**Comment by pflannery** [comment]
@rhires I use https://screentogif.codeplex.com/ on Windows 10

**Comment by bpasero** [comment]
"Open Recent" is not updated with making a file a working file within the workbench and I do not think it should.
