### ISSUE TITLE
Smoke test: Failed to change user settings configuration

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31437]
See TFS build id 30914.

This caused the following tests to fail:
1) Smoke Test Suite Configuration and views turns off editor line numbers and verifies the live change
2) Smoke Test Suite CSS verifies that warning becomes an error once setting changed

Seems that it did not type in the editor due to some problems. Could be because wrong element focus because we have new header text in the editor 'Place your settings here to override the Default' or editor was not editable.

**Comment by sandy081** [comment]
@michelkaporin I do not think settings are not editable.. could be due to the new header.. Can you point me how you edit the settings file in the smoke test?

Thanks

**Comment by michelkaporin** [comment]
@sandy081 
The call from https://github.com/Microsoft/vscode/blob/master/test/smoke/src/tests/configuration-views.ts#L35  to https://github.com/Microsoft/vscode/blob/master/test/smoke/src/areas/common.ts#L27, where settings file is touched. Code seem to be self-explanatory, let me know if you have any other questions 😉
