### ISSUE TITLE
Search bar squeeze editor area

### ISSUE THREAD

**Issue by deart1mer** [Microsoft/vscode#31431]
- VSCode Version: 1.14.1 (1.14.1)
- OS Version: macOS Sierra 10.12.4 (16E195)

Steps to Reproduce:
![ctf](https://user-images.githubusercontent.com/10653243/28607885-6b4c6248-7210-11e7-8a5e-b890fa235545.gif)

1. Search a keyword. The search bar appears at the top right.
2. Change another tab. The first line was squeezed by the search bar.
![image](https://user-images.githubusercontent.com/10653243/28607989-0ff0e404-7211-11e7-8f55-8f977595a66f.png)

Reproduces without extensions: No

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28390
