### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by kartheekiitk** [Microsoft/vscode#31434]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.8.0-59-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.17.0|
|indentation-level-movement|kaiwood|1.1.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Have you set `typescript.tsdk` in your workspace or user settings?

Also please try upgrading VSCode from 1.13 to 1.14.
