### ISSUE TITLE
Fail early when electron-mksnapshot comes in the wrong version

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31441]
The version of `electron-mksnapshot` we are using must be in sync with the electron version we are using. This requirement is not obvious and not enforced when running the tool. The result is an invalid snapshot and a brick-build.

fyi @Tyriar @joaomoreno

**Comment by jrieken** [comment]
@Tyriar @bpasero Do you already have `mksnapshot` from our special builds?

**Comment by bpasero** [comment]
@jrieken no update yet, I think they still have this as backlog item to look at. @Tyriar not sure this came up during your time in Tokyo?

**Comment by Tyriar** [comment]
Nothing about this was mentioned.
