### ISSUE TITLE
Visual Studio Code not working on Windows 7

### ISSUE THREAD

**Issue by okocaoglu** [Microsoft/vscode#31447]
- VSCode Version: 1.14.2
- OS Version: Windows 7 Enterprise Service Pack 1 (64-bit)

I have never been able to run any version of VSCode on my work computer. I have tried several recommended methods but none succeeded. I have verified that .NET 4.5.2 is installed. 

Reproduced the problem under following: 
* Downloaded VSCodeSetup-x64-1.14.2.exe and ran setup. Setup terminated at some point without leaving any message. All files seemed to be copied to the installation folder. Launching code.cmd produced no result. Only a blank command prompt popped up and disappeared.  
* Downloaded VSCode-win32-x64-1.14.2.zip and extracted contents. Again, launching code.cmd produced no results leaving no traces (no error, dump file, event log etc.) 
* Tried insiders-build without any success
* Tried 32-bit versions but the outcome did not change.
* Tried --disable-extensions and --disable-gpu options without any success.
* Tried --version, --verbose and --help options to extract some output on the command line. Nothing happened.
* Also tried version 1.12.2 but no changes.

Note: Checked AppData\Roaming\Code folder. It is empty.

**Comment by joaomoreno** [comment]
Try this only on the extracted `VSCode-win32-x64-1.14.2.zip`:

- double click Code.exe
- run `bin\code.cmd --help`
- run `bin\code.cmd --verbose`

What are the outcomes of all those 3 experiments?

**Comment by okocaoglu** [comment]
** double click Code.exe**: A few seconds of busy cursor, then nothing
**run bin\code.cmd --help**: No reaction on command prompt
**run bin\code.cmd --verbose**: No reaction on command prompt

**Comment by joaomoreno** [comment]
How about running `Code.exe` in the command line? How about `Code.exe --verbose`?

**Comment by okocaoglu** [comment]
I have found the cause of the problem: 

Symantec Endpoint Protection software (and may be a second low level extension like a file system filter) are preventing the creation of a folder named "uc.micro" and silently terminating the zip extractor or the setup exe. 

When the blocker is Symantec Endpoint Protection, following trace is logged:

_27/07/17 11:56:12	0	Terminate	Production	
Monitor File Creation for Known Cryptolocker Extensions - Caller MD5=775b5ab4b2904acdf02f8021fe0b5c90	
File Write	CryptoLocker Block File Creation Rule | CryptoLocker File and Folder Access Attempts	
...	
D:\VSCode\resources\app\extensions\extension-editing\node_modules\uc.micro	

In order to verify this, I tried to create a folder with .micro extension. The command prompt got terminated immediately.

**Comment by okocaoglu** [comment]
Same result with code.exe and code.exe --verbose in command line. 

I have also compared zip file and installation folder contents. Folder contains 130MB, whereas extracted size of zip file is reported as around 190MB.

**Comment by joaomoreno** [comment]
Can you open up an exception for Code?

**Comment by okocaoglu** [comment]
I don't have direct access to virus control tool but I can file up a request for that. 

Right now I am in the tool evaluation process for a project and I have been able to install VS Code by renaming the uc.micro folders inside the zip file. This seems sufficient for my current purpose.

If we choose to go forward with VS Code, I will definitely consider your suggestion as it's a more permanent solution. Thanks.

**Comment by joaomoreno** [comment]
Thanks!
