### ISSUE TITLE
display utf-8 characters on debug watch panel

### ISSUE THREAD

**Issue by KuddLim** [Microsoft/vscode#31442]
- VSCode  #Version: 1.14.2
- OS Version:  LMDE 2 Betsy x86_64

Steps to Reproduce:

1. Make a simple c++ project
2. declare std::string (or std::wstring) and put some CJK string to it.
3. Launch gdb session 
4. Watch variable

Reproduces without extensions: Yes

in vscode, variables are represented in numerics
![vscode](https://user-images.githubusercontent.com/9252346/28611664-88250df4-7227-11e7-8491-5cadbf823200.png)

in gdb, variable are represented correctly,
![gdb](https://user-images.githubusercontent.com/9252346/28611706-a4427800-7227-11e7-9c14-8a8dc3f81fb1.png)

Here's the content of ~/.gdbinit
`set target-wide-charset UCS-4`

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#918
