### ISSUE TITLE
cant find \r in regex mode

### ISSUE THREAD

**Issue by baslr** [microsoft/vscode#31449]
- VSCode Version: Insider ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95
Stable: cb82febafda0c8c199b9201ad274e25d9a76874e 1.14.2

Steps to Reproduce:
select CRLF for line end sequence
write some lines
abc\r\n
def

ctrl + f to open search
select regex mode (.*)
try `\n` (is selected)
try `\r` prints alternative fact no results.

Reproduces without extensions: Yes, tested Insiders only.

**Comment by baslr** [comment]
persistent in v1.17.2

**Comment by alexandrudima** [comment]
In the find widget, it is possible to target the EOL sequence (`\n` or `\r\n`) in a file via `\n` in regex mode. It is not possible to target only the `\r` in a `\r\n` EOL sequence. We enforce this to prevent that mixed line endings are created by accident.

**Comment by eliu** [comment]
@alexandrudima What if I want to just replace all \r\n (CRLF) to \n (LF) in multiple files? I guess this is quite common case right?

**Comment by mbomb007** [comment]
**Why is this not fixed yet?** I have a linter that reports \r\n as invalid, and it would be really nice if, instead of having to open 50 files individually and change CRLF to LF on the lower bar, if I could just Find & Replace \r\n with \n.
