### ISSUE TITLE
Test Settings 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31448]
- [x] Windows - **@jrieken**
- [x] macOS - **@isidorn**
- [x] Linux - **@joaomoreno**

Complexity: 4

## No Workspace

- Settings are read and applied from Default / User settings. Make sure user settings override defaults.
- Update User settings and verify the update.
- Update settings using User actions like `Toggling Sidebar Visibility` and verify updates

## Folder Workspace

- Settings are read and applied from Default / User / Workspace settings. Make sure workspace settings override user settings and default settings.
- Workspace settings come from `.vscode` folder under the folder.
- Update User settings and Workspace settings and verify the updates.
- Update settings using User actions and verify updates
-- Have `files.associations` setting in Workspace scope and try to update the file association using the language mode on the status bar. Verify workspace setting is updated.

## Multi folder Workspace

- Open a workspace with multiple folders 

Source of Settings are 
- Defaults come from Default settings
- User settings come from User settings file
- Workspace settings come from Settings file of first root folder excluding Folder scoped settings
- Folder settings come from Settings file of root folders excluding Workspace scoped settings.

Supported resource scoped settings in Core 
```
editor.*
files.exclude
files.trimTrailingWhitespace
files.insertFinalNewLine
files.encoding
files.autoGuessEncoding
files.watcherExclude
search.exclude
```
Rest are Workbench settings.

Verify:

- Default setting is applied to all folders unless overridden
- User setting is applied to all folders unless overridden
- Workspace setting is applied to all folders unless overridden
- Workspace settings show non setting properties dimmed.
- Folder settings are applied only to the resources under folders.
- Folder settings show not supported workbench settings as dimmed with an info icon
- Default settings shows only default folder settings when folder settings are opened.

## Test Configuration API

- Verify that you can define a configuration scoped to `resource` or `workbench` using `configuration` contribution point. E.g.
```json
"configuration": {
            "type": "object",
            "properties": {
                "testExtension.resourceConfiguration": {
                    "type": "boolean",
                    "scope": "resource"
                }
            }
        }
```

Remember to change `engines.vscode` to `*` and running `npm install` to get the latest `vscode.d.ts`. Then:

```ts
const configuration = vscode.workspace.getConfiguration('testExtension', vscode.window.activeTextEditor.document.uri);

// Verify the methods on configuration object are working as expected
configuration.get('resourceConfiguration');
configuration.inspect('resourceConfiguration');
configuration.update('resourceConfiguration', false, vscode.ConfigurationTarget.WorkspaceFolder)
```

- Verify you can read and write settings correctly in all kinds of workspaces. 

### Configuration API behaviour in Empty workspace

When configuration is asked with or without a resource
- There will be no workspace and folder settings.
- Inspect returns undefined for workspace and folder values always
- Writing into workspace or folder settings results to an error.

### Configuration API behaviour in Folder workspace

When configuration is asked with or without a resource
- There will be no folder settings.
- Inspect returns undefined for folder values always
- Writing into folder settings results to an error.

### Configuration API behaviour in Multi Folder workspace

When configuration is asked for a resource

- Inspect returns values for all targets unless undefined.
- You can only write `resource` scoped setting into folder. Writing `workbench` scoped setting results to an error.

When configuration is not asked for a resource

- Inspect returns undefined for folder values always
- Writing into folder settings results to an error.

**Comment by isidorn** [comment]
I feel like the last part "Configuration API behavior" would be better coverd by unit tests.

**Comment by joaomoreno** [comment]
@sandy081 Next time consider setting this to a 5 complexity level. :fire:

**Comment by sandy081** [comment]
@joaomoreno Sure. Happy to share the same pain :)

**Comment by sandy081** [comment]
@isidorn Yeah we have mostly unit test coverage but not integration tests. Will definitely improve there.

**Comment by sandy081** [comment]
Thanks @isidorn @joaomoreno @jrieken for testing and providing valuable feedback.
