### ISSUE TITLE
EH debugging: "Restart" doesn't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31445]
- create hello world extension
- F5
- press "Restart" button

Observe: nothing happens.

- "reload window" in EH

Observe: window reloads.

"Restart" should do the same as "reload window"

("Restart" for regular node programs works fine)

**Comment by isidorn** [comment]
I am not sure how this was working before, but now I am explictily sending a msg to reload to the extension host once I see that a user wants to restart extension host debugging

fyi @bpasero
