### ISSUE TITLE
ConfigurationUpdateEvent should have sourceConfig.launch if launch.json deleted

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31440]
I know you wanted to refactor this, but currently if a user edits a `launch.json` the ConfigurationUpdateEvent correctly has `event.sourceConfig.launch`.
However if the user deletes the `launch.json` another configuration update event is recieved however the `event.sourceConfig.launch` is missing.

If we decide to continue supporting this I believe that in both cases we should send out the `event.sourceConfig.launch`.

**Comment by sandy081** [comment]
I am planning to remove the `sourceConfig` from `event` and have an API to just get the sourceConfig.

**Comment by isidorn** [comment]
Ok, in that case it would be great if the API could notify me that launch.json got deleted - e.g that sourceConfig.event somehow has launch.

If that is not the case then both Tasks and Debug would have to listen on file events and react properly on tasks / launch.json deletion.
The alternative is to react on all configuraiton change events which feels like too much for me

**Comment by sandy081** [comment]
if `getConfiguration('launch)'` is `undefined`, then does that mean `launch` file is not there?

**Comment by isidorn** [comment]
Yes, but I do not think that would be helpful for me.
Just think of it frmo a debug or tasks point of view, we need an event when something changes in launc.json or tasks.json respectively (including the deletion of that file).

I am opne to suggestions on what to do from my side, though I find it ugly that I would need to listen deletion file events

**Comment by sandy081** [comment]
I see the use case. I think exposing such an event with source does not scale well in a MR workspace. In a MR workspace we can have n+1 launches or tasks. 

The general pattern I see in the consumers of configuration API is to listen to the configuration change event and compare the old and previous value to see if the configuration they are interested in is changed or not. Compare can result in following states

- created
- changed
- deleted
- not changed

**Comment by sandy081** [comment]
This problem got solved by new fine grained configuration change event. Please reopen if there is anything missing.
