### ISSUE TITLE
Emmet completion for HTML cannot be disabled, works poorly with text.

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#31453]
Let me begin with a general description of my problem. I'm writing a book that uses HTML as the base format. I'll type something like so:

    <p>
    My name is Ray.

And when I hit the period for the end of the sentence, Emmet tries to autocomplete it. Since I'm hitting enter to add a newline for the closing paragraph tag, this ends up converting it to something like <Ray class=""></Ray>. I tried disabling the 'auto complete on enter' setting, but that messed with my snippets and muscle memory. Frankly, I just don't want to use Emmet. So I added HTML to emmet.excludeLanguage, but it still fires off in my HTML doc. 

- VSCode Version: Code - Insiders 1.15.0-insider (fed03b66ac8acdac93897727a1d19ee0f6898bf2, 2017-07-25T07:30:52.414Z)
- OS Version: Windows_NT x64 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
wordcount|ms-|0.1.0

---

Steps to Reproduce:

1. Add "html" to emmet.excludeLanguages
2. Notice that emmet still tries to work in HTML pages.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@cfjedimaster Thanks for reporting, both the issues (`.` expanding to empty class and exlcudeLanguages not working on html) are very valid issues.

I'll have a fix out for both in the next Insiders.

Until then, you can set `"emmet.showExpandedAbbreviation": "never"` to stop having emmet in your suggestion list

**Comment by cfjedimaster** [comment]
Thanks - that worked perfectly!

**Comment by ramya-rao-a** [comment]
The fixes are in and you should see them in tomorrow's Insiders (July 27, 2017)

**Comment by cfjedimaster** [comment]
Cool, and to be clear, are you saying I won't see Emmet fire in the example I gave above? So in theory, I can roll back my preference change too?

**Comment by ramya-rao-a** [comment]
@cfjedimaster Yes and Yes. :)

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Test that the languages in the `emmet.excludedLanguages` do not get the emmet expansion in the suggestion list. The commands `Emmet: Expand Abbreviation` and `Emmet: Wrap with Abbreviation` should nt work either
- Test that a word ending with `.` does not trigger emmet completion. But words like `before.after` should trigger the completion giving you `<before class="after"></before>`
