### ISSUE TITLE
Suggestion: 1-click enable of settings in release notes

### ISSUE THREAD

**Issue by leoj3n** [microsoft/vscode#31458]
A lot of times in release notes there's a new setting that can be enabled for the new feature.

Would be cool and easier to have a button that is clickable in the release notes that adds the needed setting to enable the feature, so can quickly enable the feature in one click without having to do multiple steps of editing the user settings config manually.

**Comment by as-it** [comment]
Yes, please :)
Especially when you are in the middle of Release Notes tab then you go to settings to set something up and when you return to RN tab you are scrolled back to top (maybe this is bug?).

**Comment by BertelBB** [comment]
I was about to post a feature request relating to this. My suggestion would be to allow the user to see his current setting for the setting in question by hovering over it or clicking it, from there the user could also change the setting.
