### ISSUE TITLE
[css] Order suggested CSS properties based on usage not alphabetically 

### ISSUE THREAD

**Issue by mohsen1** [microsoft/vscode#3145]
For example: for `b` the first suggested property is `backface-visibility:` which is rarely used compared to `background:`

**Comment by mohsen1** [comment]
To find the most popular CSS properties we ca use GitHub data on Google Big Query. For example:

```sql
SELECT
  COUNT(path), content
FROM [bigquery-public-data:github_repos.files] files
JOIN [bigquery-public-data:github_repos.contents] contents 
  ON contents.id = files.id
WHERE
  path LIKE '%.css'
  OR path LIKE '%.scss'
  OR path LIKE '%.less'
  OR path LIKE '%.sass'
AND content CONTAINS 'background-color'
```

Where can I find a table of all CSS properties so I can build the popularity table based on GitHub data?

**Comment by aeschli** [comment]
You find the table in https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/data/browsers.js

**Comment by wallyzielinski** [comment]
+1 I came here to ask for the same thing. There are some selectors which really are never used and should never be pushed to the top of the auto-suggest. For example, if you type "wid", the first suggestion is "widows", a property I didn't even know existed until VS Code tried to autocomplete it for me.

**Comment by flower17** [comment]
+1
Same here. I usually type 'wid' and press enter expecting to get 'width', but it prints 'widows'.

**Comment by Tyriar** [comment]
There's a big discussion thread about this on reddit https://www.reddit.com/r/webdev/comments/c6pfay/the_most_stupid_autocompletion_in_the_entire_world/

**Comment by octref** [comment]
Chrome publishes its stats: https://www.chromestatus.com/metrics/css/popularity

We could its ordering to assign a ranking order to CSS properties.

![image](https://user-images.githubusercontent.com/4033249/67226143-4f9b0600-f3e9-11e9-9de6-9b8b9c51746f.png)
