### ISSUE TITLE
Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by johnnyignatov** [Microsoft/vscode#31452]
I have the folowing package.json

"devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "clean-webpack-plugin": "^0.1.16",
    "cross-env": "^5.0.1",
    "css-hot-loader": "^1.3.0",
    "css-loader": "^0.28.4",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-import": "^2.6.1",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.29.0",
    "img-loader": "^2.0.0",
    "node-sass": "^4.5.3",
    "postcss-loader": "^2.0.6",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-textarea-autosize": "^5.0.7",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "webpack": "^3.2.0",
    "webpack-dev-server": "^2.5.1"
  },
  "dependencies": {
    "classnames": "^2.2.5",
    "history": "^4.6.3",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-onclickoutside": "^6.4.0",
    "react-router-dom": "^4.1.1",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-redux": "^5.0.5",
    "react-textarea-autosize": "^5.0.7",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "uuid": "^3.1.0"
  }

And my eslintrc in the root folder:

module.exports = {
  "extends": "airbnb",
  "rules": {
    "max-len": [1, 100, 2, {ignoreComments: true}],
    "quote-props": [1, "consistent-as-needed"],
    "no-unused-vars": [2, {"args": "none"}],
    "radix": 0,
    "func-names": ["error", "never"],
    "linebreak-style": [
      "error",
      "unix"
    ],
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "plugins": [
    "react",
    "jsx-a11y",
    "import"
  ],
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "webpack.config.js"
      }
    }
  },
  "globals": {
    "_": true
  },
};

Can't understand why this error happens!

**Comment by mjbvz** [comment]
This error does not seem related to VSCode. Please try asking on stackoverflow or provide more context if you think this is a VSCode issue

**Comment by AbhayShiro** [comment]
I was facing this issue. I was working on ES6 MERN stack project.

> ERROR: babel-eslint is not found

This error was bugging me a lot.
It turns out that I had to disable the eslint extension of VS Code. Once this was done i reloaded the VS Code and the error stopped coming.
