### ISSUE TITLE
regression: find-in-files not excluding files.exclude folders

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#31459]
- VSCode Version:1.14.2
- OS Version:WIn 10

```Find-in-files``` is not excluding folders in workspace settings ```files.exclude``` .  Was working in 1.13

<img width="872" alt="capture" src="https://user-images.githubusercontent.com/3818866/28631121-cb83dc46-71f1-11e7-9888-4ebfffc3eaae.PNG">

**Comment by roblourens** [comment]
The file is open, and exclude patterns don't apply to open files right now due to https://github.com/Microsoft/vscode/issues/29658

**Comment by mfrost66** [comment]
Just to be clear, if by "the file is open" you are refering to the excluded file, this is not true - that file is not open.  Do you mean that the search will match any file in any sub-folder that happens to match the base filename of any open file regardless of files.exclude?
