### ISSUE TITLE
Test colour picker

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31457]
Test for #28587

- [x] windows - @weinand
- [x] macOS - @isidorn 
- [x] linux - @jrieken 

**Complexity**: 3

Hover over any color definition in CSS files to see the color picker.

**Test:**
- Behaviour of picker is as expected.
- Changing color modes works as expected (done through clicking on the header). 
- Color mode goes to transparent (e.g. to RGBA) if opacity slider is not at the top. And goes back to opaque (e.g. RGB), when no opacity is set. 
- If color mode is in format that doesn't support opacity and color mode change triggered, it should fall back to the next format that supports opacity.

Please raise most important issues first to jump faster on fixing them. No need for API tests in this milestone.

_Apologise for the delay._

**Comment by weinand** [comment]
@michelkaporin could you please provide some details for how to test this?
Without that complexity of 3 sounds rather high...

**Comment by michelkaporin** [comment]
@weinand 😄 sorry, will do as soon as it's merged into master. I will let you and @isidorn know.

**Comment by isidorn** [comment]
@michelkaporin should we also try out the VSCode color picer api changes or is that covered in a seperate issue (or is it still in flux)?

**Comment by michelkaporin** [comment]
@isidorn it's in flux. No API tests are needed.

**Comment by isidorn** [comment]
@michelkaporin overall nice work, I filled a bunch of enhancments, the ones I believe should be adressed asap I assigned to July

**Comment by michelkaporin** [comment]
@isidorn thanks, great coverage

**Comment by weinand** [comment]
Good stuff!
a bit annoying are bugs #31639 and #31640.
