### ISSUE TITLE
Show project README when opening a project

### ISSUE THREAD

**Issue by arendjr** [Microsoft/vscode#31450]
When I open a project in VS Code, I get presented with the Welcome screen. While that screen is nice, I believe it would be even more valuable to present the project's README (or README.md or .txt, whichever is present) in that same screen or even instead of that screen. This way, when you open VS Code without any open project you would be presented with the Welcome screen as it currently is, whereas if you open a project the README would be shown prominently (possibly with some of the shortcuts of the Welcome screen still on the right-hand side or something similar).

**Comment by jens1o** [comment]
That's a quite good idea!

**Comment by iamnapo** [comment]
Hello, can I work on that?

**Comment by chrmarti** [comment]
@iamnapo It might be easiest to add it somewhere here: https://github.com/Microsoft/vscode/blob/9588b6fe87647452d8e1432e45c54d28839c9495/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.ts#L63

You could add a setting to turn it on / off and would let the README win over the Welcome Page in the above code.

**Comment by iamnapo** [comment]
On it! :octocat:
