### ISSUE TITLE
Be more memory-efficient, please

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#31454]
- VSCode Version: Code - Insiders 1.15.0-insider (ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95, 2017-07-26T07:47:53.848Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-dash|dee|1.7.0
vscode-npm-source|dku|1.0.0
python|don|0.6.9
gitlens|eam|4.3.2
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.11.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
gc-excelviewer|Gra|1.1.15
composer|ika|0.5.0
smarty|imp|0.2.0
code-guid|jam|1.0.1
StretchTimer|jpa|0.0.1
json-to-ts|Mar|1.4.3
Runner|mat|0.1.14
vscode-apache|mrm|1.1.1
cpptools|ms-|0.12.1
github-issues-prs|ms-|0.3.1
php-docblocker|nei|1.2.0
emoji|Per|0.0.3
vscode-versionlens|pfl|0.19.1
datetime|rid|1.0.5
vscode-icons|rob|7.11.0
sharecode|Rol|0.4.1
todotasks|san|0.5.0
code-settings-sync|Sha|2.8.2
packagelinker|sin|0.0.3
code-spell-checker|str|1.3.2
pdf|tom|0.2.0
lorem-ipsum|Tyr|1.0.0
vscode-arduino|vsc|0.2.4
vscode-todo-highlight|way|0.5.8
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Start vscode with no workspace opened.
2. Open your task manager.
3. See it takes around 300mb of RAM. Why???

Please try to use less memory, maybe an electron update helps, otherwise, maybe you can explore in memory-efficientness?

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I am going to close this issue as I feel it is too generic. Best is to jump in and report a specific memory issue by using the built in profiler. That is an actionable thing to work on for us.

**Comment by jens1o** [comment]
Okay, will dothat.
