### ISSUE TITLE
Cannot read property 'openConfigFile' of undefined

### ISSUE THREAD

**Issue by littleShy** [Microsoft/vscode#31456]
- VSCode Version: Code - Insiders 1.15.0-insider (ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95, 2017-07-26T07:47:53.848Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
cpptools|ms-|0.12.1

---

Steps to Reproduce:

1.点击调试添加配置，提示Cannot read property 'openConfigFile' of undefined
2.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/31435

**Comment by Panoplos** [comment]
Is this a dupe? I am getting this error in the latest build when attempting `Debug > Add Configuration...` on a fresh project.

**Comment by isidorn** [comment]
@Panoplos yes this is a dup, however there has not been a build in a couple of days so maybe the latest build did not yet pick up this fix.
It will definetely be included in the next one coming tomorrow

**Comment by Panoplos** [comment]
@isidorn Comfirmed fixed in:
Version 1.15.0-insider
Commit da83dff300d40d1d9ae292c72d113a74b2a07951
