### ISSUE TITLE
Disabling recommended extensions not working

### ISSUE THREAD

**Issue by Dragon-Bytes** [Microsoft/vscode#31463]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.11.11-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.add "extensions.ignoreRecommendations": true, (user settings)

Reproduces without extensions: Yes

![ex](https://user-images.githubusercontent.com/29342448/28632593-65002ac0-7231-11e7-9855-93cde8dfb7eb.png)

**Comment by sandy081** [comment]
This setting just disables the prompt saying that there are some recommendations to the file you open. It is nothing to do with the recommendations view. 

@Dragon-Bytes May I know what are you expecting?

**Comment by Dragon-Bytes** [comment]
@sandy081 i would love to disable that recommendation section on the left. where it shows 2 extensions

**Comment by sandy081** [comment]
@Dragon-Bytes With latest insiders you can do it by right click and hiding it.
