### ISSUE TITLE
After installing Ubuntu-WSL on Windows, the [VSCode] keyboad is no longer working properly

### ISSUE THREAD

**Issue by dcu-sharepoint** [Microsoft/vscode#31462]
I asked the question here at  http://stackoverflow.com/questions/tagged/vscode. with no comments or responses

- VSCode Version: 1.14.2
- OS Version: Microsoft Windows 10 Enterprise/10.0.14393 Build 14393

Steps to Reproduce:

I installed Ubuntu on Windows (WSL) and now my [VSCode] keyboard no longer works correctly.

vsCode no longer allows me it insert/copy/delete lines on a text or javascript files and I'm wondering if anyone has experienced the same.

I had to move back to sublime to edit my react apps because vsCode no longer allows me to edit my files or makes it VERY difficult to make changes I don't know how to debug something like this.//

I can reproduce it every time I edit a file and try to a. select a word/line to delete and IT IS NOT deleted.
I can't insert.

Launch with `code --disable-extensions` to check. 

I'm in the process of doing just that: renaming the .vscode windows folder and testing. however, I have over 75 extensions installed and it's going to be a **PITA** to have to add each extension to test

so far I identified all of the extensions I installed in July

1.  `esbenp.prettier-vscode-0.21.0`
2.  `davidhouchin.whitespace-plus-0.0.5`
3.  `leizongmin.node-module-intellisense-1.4.0`
4.  `vscodevim.vim-0.9.0`
5.  `dbaeumer.vscode-eslint-1.2.11`
6.  `PeterJausovec.vscode-docker-0.0.16`
7.  `ivanzusko.theme-chrome-devtools-dark-0.0.1`
8.  `azemoh.theme-onedark-0.5.2`
9.  `joshpeng.theme-charcoal-oceanicnext-1.1.5`
**10.** `ms-vscode.vs-keybindings-0.1.7`** 
11. `WallabyJs.wallaby-vscode-1.0.55`

number **10** seems like a likely suspect and I'll be working to see if that is where the trouble is and report back.

is there a way to trouble shoot this inside vscode, listing all of your enabled extensions & disabled extensions side by side?

any help will be greatly appreciated.

**Comment by alexandrudima** [comment]
@dcu-sharepoint if you have installed the vim extension, then you must use the vim way of editing. It is an entirely different way of editing. Perhaps you'd want to uninstall the vim extension if you installed it by accident.
