### ISSUE TITLE
Markdown code block in editor mode not colored if more than 4 spaces in the beginning of the line

### ISSUE THREAD

**Issue by cwliu** [Microsoft/vscode#3146]
Here is the screenshot: 
![code](https://www.evernote.com/shard/s16/sh/8efb904f-5bb3-4ecb-a888-2cab131524c5/d6685628bbc28d06/res/aac02ce6-50b9-4a04-b246-d3311a9449cc/skitch.png?resizeSmall&width=832)

It would better if the 
`a = a - 1` line also colored as orange

**Comment by bpasero** [comment]
@cwliu as a workaround you can put a leading and trailing 3 * backtick to indicate a code block.

**Comment by cwliu** [comment]
@bpasero Thanks for your information. 

I have tried as below:
![markdown-cdoe](http://i.imgur.com/OHUXh17.png). It has no color applied on the code block, but it better than partially colored.

**Comment by bpasero** [comment]
@cwliu it should look better if you use the Dark+ theme. You can also add the language type after the backticks to color it for the language.

**Comment by cwliu** [comment]
Indeed, There is the screenshot using Dark+ theme and set the type to JAVA

![image](http://i.imgur.com/OHUXh17.png)

**Comment by cwliu** [comment]
Indeed, There is the screenshot using Dark+ theme and set the type to JAVA

![image](http://i.imgur.com/OHUXh17.png)

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension we ship for June.
