### ISSUE TITLE
Is there a feature that offers a shortcut to reset zoom?

### ISSUE THREAD

**Issue by juniormayhe** [Microsoft/vscode#31464]
Another question related to zoom is that CTRL + and CTRL - zoom in and out, but how to reset it to default? CTRL + 0 could be an option? I do not see nothing about zoom level reset in https://github.com/Microsoft/vscode-tips-and-tricks#editing-hacks

Regarding touchpad

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Go to terminal or code editor
2. Press CTRL +  to zoom in
3. Press CTRL + 0 to reset
4. Nothing happens (you have to press CTRL -

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
You can go to command palette and search reset Zoom and you can see the shortcut key there for your platform.
