### ISSUE TITLE
No tooltip on hover over a variable within closure and async function while debugging

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#31469]
- VS Code Version: 1.14.2
- OS Version: Windows 8.1 x64

Steps to Reproduce:

0. `git clone https://github.com/Deilan/vscode-issue-31469.git`.
1. `yarn install` or `npm install`.
2. Set debug breakpoint in `src/index.ts` at lines 10 and 19
3. Launch debug configuration `Launch via nodemon`.
4. Wait till breakpoint at line 10 hits.
5. Hover over `syncBeforeDelayArg` at line 5 and 6 - tooltip exists.
   Hover over `syncDelayResult` at line 7 - tooltip exists.
   Hover over `syncAfterDelayArg` at line 8 - tooltip exists.
   **Hover over `syncBeforeDelayArg` at line 9 - tooltip does not exist.**
   Hover over `syncDelayResult` at line 9 - tooltip exists.
   Hover over `syncAfterDelayArg` at line 9 - tooltip exists.
   **No `syncBeforeDelayArg` at debug sidebar's local variables list.**
6. Continue and wait till breakpoint at line 19 hits.
7. **Hover over `asyncBeforeDelayArg` at line 15 and 16 - tooltip does not exist.**
   **Hover over `asyncDelayResult` at line 16 - tooltip does not exist.**
   **Hover over `asyncAfterDelayArg` at line 17 - tooltip does not exist.**
   **Hover over `asyncBeforeDelayArg` at line 19 - tooltip does not exist.**
   **Hover over `asyncDelayResult` at line 19 - tooltip does not exist.**
   **Hover over `asyncAfterDelayArg` at line 19 - tooltip does not exist.**

Reproduces without extensions: Yes.

![image](https://user-images.githubusercontent.com/4777512/28635841-b4a89b30-7244-11e7-85fa-a1a63103cf69.png)

![image](https://user-images.githubusercontent.com/4777512/28635847-b864638a-7244-11e7-8fda-60aac0aaae92.png)

**Comment by martypdx** [comment]
Experiencing this too. My project is purely synchronous library, during debug hover only works for "Local" scoped variables, everything else doesn't show tooltip.

**Comment by isidorn** [comment]
Can you please try with vscode insiders since we did some work that improved this
https://code.visualstudio.com/insiders

**Comment by martypdx** [comment]
@isidorn tried vscode insiders, still just Locals working. In screenshot below, only `quasi` and `i` have hover.

![image](https://user-images.githubusercontent.com/478864/28691193-e6da20ec-72d0-11e7-9006-3cde4ad2f3f3.png)

**Comment by isidorn** [comment]
@Deilan first of all thanks for the awesome repro steps, I wish all our issues are filed like this

In step 5 everything works fine for in latest vscode insiders. Note that `syncBeforeDelayArg` should not be in locals but in closure.
In step 7 I get the same issues you described. This comes from the fact that the protocol debug adapter returns wrong scope range information, namely for the local scope it says it starts on line 22 and is until line 28, becuase the hovered line is not in that range we do not even look at that scope (which contains all the valuable information).

Forwarding to @roblourens 
If the scope range issue can not be fixed then we need to consider not using the falsy ranges information provided by the adapter.

**Comment by weinand** [comment]
The scope ranges are source mapped from TS to JS, right?

**Comment by roblourens** [comment]
Thanks for the repro case. The scope starts on the function definition line. In this case that line is inserted by TS, so it doesn't have a sourcemapping, and we fail to sourcemap it. I can probably deal with this by trying again on lineNum+1 when it fails for a scope line.
