### ISSUE TITLE
Test Windows 64 bit ad

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31461]
Testing #30860

Complexity: 1

- [x] windows - **@egamma**

Test that in Windows 32 bit you will get a message notifying that a 64 bit version is available. If you decide to read more, Code should open up a browser either to the [Insider release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_15.md#windows-64-bit) or the [stable release notes](https://code.visualstudio.com/updates/v1_15#_windows-64-bit) (not yet available).

**Comment by cleidigh** [comment]
Will work for "commits" ;-)

@joaomoreno 
@bpasero 
@Tyriar 
@rebornix 
I know this is not exactly the place, but did not think it was appropriate for an issue...
Just installed the 64-bit versions.
Not sure if you are soliciting/wanting nonmember help in testing, but I'm happy to volunteer
if there any assignments especially keyboard centric that I can help with.
Christopher

**Comment by egamma** [comment]
@cleidigh testing help is always welcome. These is the [test plan](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Atestplan-item+milestone%3A%22July+2017%22) for July.

**Comment by egamma** [comment]
Tested this item (we will have a tracking item to make sure that the link from the message box points to a good location in the doc).

**Comment by cleidigh** [comment]
@joaomoreno 
@egamma 
Not sure if it is by design, but the 64-bit ad message will not be cleared with ESC like other messages
you have to click one of the buttons. Accessibility issue?
Tested Windows 7 Insiders 7-28
