### ISSUE TITLE
Format code don't work on macos

### ISSUE THREAD

**Issue by xavores** [Microsoft/vscode#31468]
- VSCode Version:  1.14.2 (1.14.2)
- OS Version: Macos 10.12.6

Format code don't work. 

cmd + alt + F don't format but write '.' in my code.

If i use shift + cmd + p i haven't '>format' command

Thanks for you help

**Comment by mjbvz** [comment]
A few questions:

- What is the language mode of your document? This is shown in the lower right corner in the status bar
- What extensions do you have installed?

**Comment by xavores** [comment]
Thanks for you respond, i attached img. 

<img width="479" alt="capture d ecran 2017-07-26 a 21 08 38" src="https://user-images.githubusercontent.com/19587923/28639078-34a78e70-7247-11e7-94c9-ae52399442b2.png">
<img width="370" alt="capture d ecran 2017-07-26 a 21 09 38" src="https://user-images.githubusercontent.com/19587923/28639079-34acb968-7247-11e7-9c41-bf2c7c31ff2b.png">

**Comment by mjbvz** [comment]
We don't ship a built-in php formatter. Try installing one of them from the marketplace: https://marketplace.visualstudio.com/search?term=php%20formatter&target=VSCode&category=All%20categories&sortBy=Relevance
