### ISSUE TITLE
[icons] Support to allow re-using VSCode icons in user extensions

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode#31466]
It would be nice if there's a supported API to access VSCode inbox icons.

**Expected**:

I want to reuse icons in the IntelliSense suggestion window outside of completion items (for example a TreeDataProvider).

**Actual**:

I had to copy the icon files to my extension project to use them

**Comment by sandy081** [comment]
@aeschli I do not think intelli-sense icons can be customised?  I am planning to support resource based icons in custom views.https://github.com/Microsoft/vscode/issues/27823

**Comment by aeschli** [comment]
This request is related to #10455

**Comment by patrys** [comment]
Huge 👍 from me, my extension currently includes a copy of all of the Symbol Picker icons.

**Comment by peni4142** [comment]
I am working on a tree-view. I would like use vscode icons too. A extension has to like it belong to that, which it is extending! I am looking for icons to refresh the tree or delete a tree item etc..

**Comment by Thaina** [comment]
Had been request this since #28519 But then you @sandy081 said it was duplicate. And then you just state this in >27823

>Hence, I asked to create an issue per feature request.

And my issue was locked. What's wrong with this? Please reopen my old issue

**Comment by aeschli** [comment]
FYI @misolori

**Comment by misolori** [comment]
Also related to https://github.com/microsoft/vscode/issues/78889

**Comment by KamasamaK** [comment]
What exactly is still pending for this? It seems codicons can be used in most places now, and where it can't there are specific issues opened.

**Comment by sandy081** [comment]
Codicons can be used now as tree item icons. Hence closing this.

Please file an issue for codicons if needed.

**Comment by aaronfranke** [comment]
What about doing this for file icons? In my extension, I have `"iconThemes"` under `"contributes"`, and my extension does provide the icon, but all of the other icons are gone too.
