### ISSUE TITLE
Visual Studio Code's Terminal allows click in URL but truncates its string if comma is found

### ISSUE THREAD

**Issue by juniormayhe** [Microsoft/vscode#31460]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions:

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|0.0.2

---

Steps to Reproduce:

1. Create a free account at https://darksky.net/dev/ and copy your API Key
2. Install node, open VS Code, open a folder for your node project 
3. Show your terminal ( CTRL + ' ) bash.exe in VS Code
4. In temrinal run npm init to initialize package.json and node_modules folder
5. Still in your project folder create a app.js with the statement and save the file: console.log('https://api.darksky.net/forecast/YOURAPIKEY/-23.5567497,-46.6541193');
6. Run the app in terminal: node app.js
7. On Terminal your app will print the URL
8. try to click the url displayed in Terminal
9. Terminal (bash.exe) will open your browser and take you to a truncated URL:
https://api.darksky.net/forecast/YOURAPIKEY/-23.5567497
10. The trailing part of URL ',-46.6541193' is being ignored!

Reproduces without extensions: Yes/No - Doesn't matter

**Comment by cleidigh** [comment]
@juniormayhe 
cc @Tyriar 
This is platform-independent, I have verified the same behavior in Windows.
It is also a different URL handling than the editor links.
The terminal link handler will truncate links with either comma or & whereas the editor will handle both.
I think this can be addressed within VS code, however, if it entails changes to xterm
it would become an upstream issue.

**Comment by Tyriar** [comment]
Easier repro 😃 

1. Open terminal
2. `echo 'https://api.darksky.net/forecast/YOURAPIKEY/-23.5567497,-46.6541193'`
3. ctrl/cmd+hover the link

<img width="680" alt="screen shot 2017-07-28 at 9 38 30 am" src="https://user-images.githubusercontent.com/2193314/28727141-a9b37c7e-7378-11e7-96cd-2018e637154d.png">

@cleidigh this is an upstream issue as all the URL detection is done in xterm.js. Upstream issue: https://github.com/sourcelair/xterm.js/issues/583

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/21125
