### ISSUE TITLE
"Find in Folder" finding matches outside of folder

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31471]
- VSCode Version: Code - Insiders 1.15.0-insider (ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95, 2017-07-26T07:37:19.081Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Right-click a folder in the Explorer tree.  Here, I right click "Examples" and choose "find in folder".

![screen shot 2017-07-26 at 2 22 32 pm](https://user-images.githubusercontent.com/835148/28636993-00209a90-720e-11e7-9825-f0ec6aa9274f.png)

2. I search for `abc.` and set replace with to `ctrl.`

3. It shows all the matches but **also** matches found items in `addressblocks.html` which is **NOT** in the "Examples" folder.  You can see the path.

![screen shot 2017-07-26 at 2 21 40 pm](https://user-images.githubusercontent.com/835148/28637059-3b225cb4-720e-11e7-91a5-e8a97bf0bd1c.png)

**Comment by roblourens** [comment]
Is the file open? It may be included anyway in that case, due to https://github.com/Microsoft/vscode/issues/29658

**Comment by smlombardi** [comment]
Indeed it was.  This bug is affecting me too, apparently.
