### ISSUE TITLE
Feature Request: Column Guides

### ISSUE THREAD

**Issue by bryanjclark** [Microsoft/vscode#31477]
I'm a long-time iOS developer, using VSCode to write React Native. I really enjoy Xcode's "page guide at column" feature, which (in my searching the web to see if I could solve this myself) seems to be called "column guides" in Visual Studio.

Here's what it looks like in Xcode:
![screen shot 2017-07-26 at 12 46 23 pm](https://user-images.githubusercontent.com/868389/28640416-7b1f936c-7200-11e7-95b9-72ccb67e9c7d.png)

If there's an existing setting for this, then I'd love to know so I can update the VSCode settings documentation to be more clear about it!

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.9
flow-for-vscode|flo|0.7.1
python|tht|0.2.3
vscode-react-native|vsm|0.3.2

---

Steps to Reproduce:

1. Look for a column guide setting in VSCode.
2. Can't find one; search the web & StackOverflow.
3. Still can't find one; file a ticket on GitHub for the issue and cross your fingers! ❤️ 

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
We call it `editor.rulers`

**Comment by bryanjclark** [comment]
Thank you!

**Comment by anlexN** [comment]
"editor.rulers": [], how can i set this setting? i also like this feature.
