### ISSUE TITLE
Git discard changes permanantly deletes files on Linux

### ISSUE THREAD

**Issue by nickdonato** [Microsoft/vscode#31479]
Steps to Reproduce:

1. add new files to a folder/repo
2. undo the pending changes, the newly added files will be permanently deleted from the system

Reproduces without extensions: Yes

I don't know why undo/discarding pending changes using the source control built in to VS Code would permanently delete files on linux as opposed to moving them to the trash bin. Lost a few hundred files thanks to this (though I have a backup as of 6 days ago so I'm not at a complete loss).

**Comment by joaomoreno** [comment]
I'm sorry you lost your changes.

This feature does work as designed, though. It's what git does. That's why we have the dialog showing up, asking if you are sure. That's why `This is IRREVERSIBLE` is written in ALL-CAPS.
