### ISSUE TITLE
Output window grabbing focus extremely frustrating

### ISSUE THREAD

**Issue by lemoinem** [Microsoft/vscode#31474]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
xml|Dot|1.9.2
vscode-npm-script|eg2|0.2.0
Hg|jak|0.0.4
Angular2|joh|2.4.0
HTMLHint|mka|0.3.3
hg|mrc|1.1.4
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
typescript-hero|rbb|1.3.0
stylelint|shi|0.28.0
autoimport|ste|1.2.2
JavaScriptSnippets|xab|1.4.1

---

Please refer to #15018 for reproduction steps.
This still happens (triggered by the Angular2 extension) and since the Output window is a tab along with "Problems" and "Terminal", which we use, it keeps hiding important information and is extremely distracting and prevents me from working.

Can't we have a setting somewhere to just disable the output window? Or at least prevent it from grabbing focus and becoming visible over the other tabs? I don't really care about the never-ending error/log messages from some badly written extension. If need be, I'll go and re-enable the output window when I want to have a look at it.

The fact that the extension generate error message/verbose logs is one thing, but not what I expect you to fix. The fact that VSCode does not prevent these verbose logs from showing up is what I have trouble with here.

Reproduces without extensions: No

**Comment by rebornix** [comment]
Don't know where to start but assign to @Tyriar first, we talked about the unpredictable focus issue of panels before.

**Comment by Tyriar** [comment]
@lemoinem you might want to create an issue against the angular2 extension as it's the thing telling VS Code to show the output panel.

/cc @isidorn @jrieken

**Comment by isidorn** [comment]
This is an issue with the extension, our current api allows extensions to say preserveFocus: true
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3325

Please file this against the angular2 extension
