### ISSUE TITLE
Code Helper opens too many files when opening a project

### ISSUE THREAD

**Issue by stouset** [Microsoft/vscode#31478]
Upon opening a project, Code Helper opens an excessive number of files simultaneously. Checking `lsof -p ${pid}` output at a random point, it's reading over 4500 files, mostly in `vendor/bundler/**` (this is a Ruby project). On OSX, `kern.maxfiles` is set to 12,288 and `kern.maxfilesproc` to 10,240. At the point I was able to run `lsof`, I'm guessing Code Helper had already closed many of the files it had opened.

I've added this directory to files.watcherExclude, which I believed would exempt these files from this behavior, but is apparently not the case.

The specific process causing the problem:

```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
```

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
gitignore|cod|0.5.0
githistory|don|0.2.2
proto|pet|0.0.2
Ruby|reb|0.12.1
RustyCode|sav|0.19.1
org-mode|too|0.1.3
gitblame|wad|2.0.2
better-align|wwm|1.1.6

---

Steps to Reproduce:

1. Create a project with hundreds of thousands of files spread throughout subdirectories. 
2. Open the project from the command line (`code .`).

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I think this `--type=extensionHost` is implying that it's an extension doing this? Are you sure you tried launching with `--disable-extensions`?

**Comment by stouset** [comment]
You might be right. I didn't completely shut down Code before launching without extensions, I'll attempt to reproduce again and ensure it's not extension-related.

**Comment by MynockSpit** [comment]
I have the same issue even when all extensions are disabled. 

When viewed Activity Monitor, the 'Code Helper' process has a huge number of threads (around 620 for me.) Inspecting the 'Code Helper' process and opening the 'Open Files and Ports' tab lists out a huge number of files open by the program (in my case it's around 8400).

I can't use any terminal commands when it's open -- it gives me varying errors including 'Login incorrect' and 'too many files open in system.' It also breaks most web browsers including Chrome, Firefox and Safari.

**Comment by joaomoreno** [comment]
@stouset Please let us know what happens with `--disable-extensions`.

**Comment by stouset** [comment]
Bug disappears. I'll file with the relevant extension, thanks.
