### ISSUE TITLE
Test: Search viewlet changes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31480]
This covers https://github.com/Microsoft/vscode/issues/27226 and https://github.com/Microsoft/vscode/issues/29977

- [x] Mac @Lixire 
- [x] Windows @Tyriar 

Complexity: 4

- Try search viewlet in multiroot and non-multiroot mode. The multiroot UI should be usable and make sense. The non-multiroot UI should look the same.
- Try the "Find in Folder" context menu item. In multiroot mode it should use `./` syntax, with the root's basename, in "files to include" unless there is another root folder with the same basename. In that case it should use an absolute path. In single root mode, it should always use `./`
- Try combinations of `./` and glob patterns in "files to include"
- Should get a reasonable error message for `./` and absolute paths that don't exist
- Try different things in include/exclude. Now that the glob buttons are missing, `foo` should match `**/foo,foo/**` (ie, a folder at the root named foo, or all files named foo)
- Don't forget to try things with `"search.useRipgrep": false`.
- Open files should now respect the include/exclude settings

**Comment by roblourens** [comment]
One of you, please try Windows

**Comment by Tyriar** [comment]
I'll do Windows
