### ISSUE TITLE
Issue Opening Folder When Debugging Extension

### ISSUE THREAD

**Issue by adstep** [Microsoft/vscode#31482]
While debugging an extension I execute:
```
vscode.commands.executeCommand('vscode.openFolder', tmpDirUri)
```
The folder is opened in the 'debugging' code instance instead of the 'debug' code instance. Then the 'debug' instance gets shut down because the 'debugging' instance closes on changes folders.

- VSCode Version: 1.14.2
- OS Version: Win 10

Steps to Reproduce:
1. Run a custom exectension.
2. Execute vscode.commands.executeCommand('vscode.openFolder', tmpDirUri)

**Comment by bpasero** [comment]
This has been fixed meanwhile via https://github.com/Microsoft/vscode/commit/3fa0bdbb9af40d5ac137f6fc4504d886c0e6440c
