### ISSUE TITLE
"Configure or fix launch.json" button doesnt create or open launch.json file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31486]
Using Insiders dated 26th July 2017

Clicking on the "gear" in the debug viewlet that usually opens the launch.json file (or creates it if it doesnt exist) doesnt work.

![image](https://user-images.githubusercontent.com/16890566/28648751-df9b0a1e-7224-11e7-9ff1-8f29c38fe3e0.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/31435
