### ISSUE TITLE
Minimap noise artifact after resume from suspend on Linux with NVIDIA GPU.

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#31489]
- VSCode Version: 
Version 1.15.0-insider
Commit f21c311e8db9eff11a605b517525aa6c4dd0f09b
Date 2017-07-25T05:10:14.622Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
- OS Version:
Ubuntu 17.04 (Zesty) w/ Kubuntu backported Plasma Desktop 15.10.4 (Should be irrelevant, but noted just in case.)
- NVIDIA Info:
GeForce GTX 750
Driver Version 381.22

Steps to Reproduce:

1. Have document open in vscode.
2. Suspend machine to RAM.
3. Resume from suspend

![minimap-noise](https://user-images.githubusercontent.com/2549985/28651270-d817e6c6-72bb-11e7-8e7d-a492c71060e8.png)

Reproduces without extensions: Yes

Extra Notes:

KWin had this problem with several applications, too, but they fixed it here: https://bugs.kde.org/show_bug.cgi?id=344326
Perhaps you can reference their fix when addressing this.

**Comment by alexandrudima** [comment]
@Panoplos Thank you for the report.

May I kindly ask if this issue reproduces in Chromium when opening the following webpage where the same minimap implementation surfaces: https://microsoft.github.io/monaco-editor/

If that is the case, could you please open an issue against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here. I believe it is their responsibility to manage that pixel surface.

**Comment by alexandrudima** [comment]
Similar: #30292
