### ISSUE TITLE
[json] different syntax highlighting for level

### ISSUE THREAD

**Issue by mo** [microsoft/vscode#31483]
atom-json-color has different colors per level inside json files, makes it so much easier to read

![image](https://user-images.githubusercontent.com/7117/28648032-21926e44-726b-11e7-98a7-cc949972ba0e.png)

**Comment by peteplays** [comment]
please add this feature 👍

**Comment by usernamehw** [comment]
@aeschli, isn't this already possible? Example of token customization for `Monokai Dimmed`:
```json
"[Monokai Dimmed]": {
    "textMateRules": [
        {
            "name": "JSON Key - Level 0",
            "scope": [
                "source.json meta.structure.dictionary.json support.type.property-name.json"
            ],
            "settings": {
                "foreground": "#0056f5"
            }
        },
        {
            "name": "JSON Key - Level 1",
            "scope": [
                "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
            ],
            "settings": {
                "foreground": "#fbff19"
            }
        },
        {
            "name": "JSON Key - Level 2",
            "scope": [
                "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
            ],
            "settings": {
                "foreground": "#ff2e2e"
            }
        },
    ]
},
```

**Comment by aeschli** [comment]
Yes, correct, good solution!

**Comment by peteplays** [comment]
@usernamehw or @aeschli where is that file located or where do you create it?

**Comment by usernamehw** [comment]
@peteplays In your `Settings` "editor.tokenColorCustomizations": https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by stalkerg** [comment]
> @aeschli, isn't this already possible?

But this colors will not rotate...

**Comment by stalkerg** [comment]
Looks like Sublime support same way but themes usually use this approach:
https://github.com/equinusocio/material-theme/blob/master/schemes/Material-Theme.tmTheme#L470

hmm interesting, at least I can convert Sublime theme to VS Code.

**Comment by stalkerg** [comment]
Ok, thanks! I add JSON level rules to JS for Material Theme, looks great.
But for better effect, we should wait https://github.com/Microsoft/vscode-textmate/issues/52 this feature.

**Comment by peteplays** [comment]
im not sure how to do this myself, but it seems like this code base could be adapted to colorize json too https://github.com/CoenraadS/BracketPair

**Comment by uocxp** [comment]
this would also be nice for yaml !

**Comment by aeschli** [comment]
Best be done by an extension.
We're also happy to switch our JSON textmate grammar to a better JSON grammar. Please file an issue with the repo URL of the improved grammar.
