### ISSUE TITLE
Description of explorer.sortOrder setting does not contain all values.

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31498]
Testing ##30719

Steps to reproduce

- Open Settings
- Look for setting `explorer.sortOrder`
Description should mention about all values

**Comment by bpasero** [comment]
They are all described:

![image](https://user-images.githubusercontent.com/900690/29204771-37b70fbc-7e79-11e7-9278-aa5d14f7bca9.png)

![image](https://user-images.githubusercontent.com/900690/29204777-3f511682-7e79-11e7-8c24-7f89babbba8a.png)

**Comment by sandy081** [comment]
@bpasero By description I mean the description of the setting like follow

![image](https://user-images.githubusercontent.com/10746682/29515424-f63d0a96-8689-11e7-803f-fa29891c4b2e.png)

**Comment by bpasero** [comment]
Changed to this:

![image](https://user-images.githubusercontent.com/900690/29515956-d44c156e-866e-11e7-805e-b98d61749f7a.png)
