### ISSUE TITLE
Shortcut Ctrl + P some times not working on windows 10

### ISSUE THREAD

**Issue by ganny26** [Microsoft/vscode#31497]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-nsp|adambaldwin|1.0.1|
|JSDocTagComplete|HookyQR|0.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|short-js-doc|myax|0.1.5|
|type-doc-vscode|Trezm|0.0.34|;

---

Steps to Reproduce:

1.Open VS Code after Update/Keep VS Code for long time say (2-3 days) without shutdown
2.Use shortcut Ctrl + P - Go to file will not work
3.To get again restart machine,getting activated

**Comment by chrmarti** [comment]
Does the drop-down open and can you type in it?

Anything in the console? (Help > Toggle Developer Tools)

**Comment by ganny26** [comment]
No drop-down visible if shortcut applied
Rather I'm able to go on a particular file from Menu bar (Go > Go to file)

**Comment by chrmarti** [comment]
Does this reproduce when you start with `code --disable-extensions`?

**Comment by ganny26** [comment]
5workbench.main.js:29 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 Line (!function(t){fu...): longer than 20k characters, tokenization skipped.
workbench.main.js:29 Line (he(e),v(e)&&(o+...): longer than 20k characters, tokenization skipped.
workbench.main.js:29 Line (var m=this&&thi...): longer than 20k characters, tokenization skipped.

**Comment by chrmarti** [comment]
@ganny26 Does this reproduce when you start with `code --disable-extensions`?

**Comment by ganny26** [comment]
@chrmarti yes i can see the errors even after disable extensions

**Comment by chrmarti** [comment]
Could you upgrade to the latest release 1.15.0, preferably the 64-bit variant, and check if the problem is still there?

The errors suggest that you are working on a minified file with long lines. Does the problem also reproduce when you work on regular files?

**Comment by ganny26** [comment]
it happen sometimes after upgrading to latest x64 bit variant when long lines (i.e) more than 15 k

**Comment by ganny26** [comment]
@chrmarti  **see below error i'm getting after updating to x64**

[Extension Host] Error: TextEditor disposed
    at t.$trySetDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:3140408)
    at t.e.handle (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:3100044)
    at s (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1029376)
    at f (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1030031)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
t.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29

**Comment by chrmarti** [comment]
That shouldn't affect Ctrl + P, it's more like a warning. (#30578)
