### ISSUE TITLE
Cannot disable Global Identifiers for IntelliSense

### ISSUE THREAD

**Issue by kaala** [Microsoft/vscode#31499]
VS Code IntelliSense offers different types of completions, but there are too many completions for Global Identifiers type
It collects all words inside a file, better we can have a setting to disable this type

**Comment by thw0rted** [comment]
I would love to see this work like autocomplete in a browser URL bar -- use the cursor keys to select a "bad" selection, press the Delete key, it's removed from the list.  You could store a "stop-word list" somewhere in user preferences so it's easy to edit.

**Comment by kaala** [comment]
Delete unwanted items is not enough to me.
If you open a large javascript file, and the variable type is any, IntelliSense will show all the keywords in that file, this is a list of more than 100 items, and almost all of them are useless.
Probably a dynamic adjustment by use frequency would help.

**Comment by ramya-rao-a** [comment]
@kaala Is this concern specific to javascript/typescript?

**Comment by thw0rted** [comment]
I think this is specific to weakly-typed languages where autocomplete needs to be inferred / best-guess.  Technically it could be an issue for Typescript but suggestions for strongly-typed variables are quite good.  I can't personally come up with anything else that would be nearly as problematic as JS.

**Comment by kaala** [comment]
javascript only

**Comment by ramya-rao-a** [comment]
Thanks @thw0rted and @kaala 

Assigning to @mjbvz who works on the language service for javascript and typescript which provides the completions.

**Comment by mjbvz** [comment]
Try setting:

```
"editor.wordBasedSuggestions": false,
"javascript.nameSuggestions": false
```

If these settings do not address what you are after, please provide an screenshot of the unexpected suggestions that are showing up

**Comment by kaala** [comment]
Thanks
`"javascript.nameSuggestions": false` is enough to make the unwanted suggestions disappear.
