### ISSUE TITLE
Inconsistent multi-line regex replace within 1 file vs multiple files

### ISSUE THREAD

**Issue by endragor** [Microsoft/vscode#31491]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.2
nim|kos|0.5.26
gitblame|wad|2.0.2
clang-format|xav|1.5.0

(1 theme extensions excluded)
---

Steps to Reproduce:

1. Create a file containing:
```
hello
  world
```
2. Open "Find in Files" panel.
3. Enter a multiline regex, for example: `o[\s\n]*world`
4. Observe the preview only matches `o`. Try to click "Replace All" and see that only `o` is replaced.
5. Open "Find" panel (for the current file). Enter the same regex. Observe it matches both lines, as expected. Click "Replace" and observe it replaces the whole match, as expected.

![Example](https://i.imgur.com/3tQ8tJ7.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected, the search viewlet is powered by ripgrep which doesn't support all the features like multiline search and advanced regex features that the editor find widget supports. Sorry it isn't more clear.

**Comment by endragor** [comment]
Hmm, and you don't plan to fix/enhance it? Sublime Text supports this use case well. It's currently impossible to replace multiline matches in the whole project with VSCode.

**Comment by roblourens** [comment]
It may be supported by ripgrep in the future. We would need support from the Rust regex engine upstream, so there's nothing we can do about it right now, unfortunately.
