### ISSUE TITLE
Search viewlet can take highlighted text at inappropriate times

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31496]
- Open search viewlet
- Have some text in the query input box
- Highlight some portion of a line in the editor
- Have focus in the search viewlet
- Press cmd+shift+j to toggle the search query details area
- :bug: Now the search input box unexpectedly has the selected text

Anything that calls `SearchViewlet.focus()` will do the same. I think that should only happen when focus was originally in the editor.

Long-standing bug.

**Comment by dbaeumer** [comment]
I can still reproduce this if the search input box has no focus (if I give focus to the header of the search viewlet)

![cast](https://user-images.githubusercontent.com/1931590/31017553-298873e6-a529-11e7-99ac-4630d1994fb2.gif)

**Comment by roblourens** [comment]
Also triggered by just clicking the viewlet buttons to show the search viewlet, show/hiding the sidebar, etc. It should *only* be triggered when specifically intended, with focus in the editor.

FYI @sandy081 I added new actions for this, `replace/findInFilesWithSelectedText`. I guess it has the potential to confuse someone's keybindings but hopefully not a problem.
