### ISSUE TITLE
While creating a new file input box should be placed at the beginning when sort type is modified

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31500]
Testing #30719

- Set the setting `explorer.sortOrder` to `modified`
- Right click on a folder in explorer and create a file

Expected: Input box should be placed at the beginning. Because with this setting, new entry will be always placed at the top

**Comment by bpasero** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/900690/29204820-72361746-7e79-11e7-9fdd-35979c9dd47e.png)

**Comment by sandy081** [comment]
@bpasero I meant input box can be the first child of the parent. Because new entry will be always first child.

**Comment by bpasero** [comment]
@sandy081 in your example you are creating a file and with sort order `modified` we do not sort files before folders. So I think your steps produce still the correct result for me.

**Comment by sandy081** [comment]
@bpasero True. Thanks for clarification.
