### ISSUE TITLE
intellisense stops working after a while in Linux

### ISSUE THREAD

**Issue by khaledkbadr** [Microsoft/vscode#31508]
- VSCode Version: 1.14.2
- OS Version: Fedora 26

I'm using vscode to write Python and Go using the recommended extensions, after working for a while the intellisense suddenly stops working and every time I had to restart vscode to get a working intellisense again. This is a persistent issue for a while now

This issue can be reproduced in Ubuntu 16.04, Arch, Fedora 25, 26
And this issue was there also into 1.13 version

**Comment by mjbvz** [comment]
From the description this sounds like an extension issue. Please try disabling all extensions except the python or go ones. If you still see this problem, then please try filing an issue against either the Python or Go extension repos
