### ISSUE TITLE
Extension readme doesn't render

### ISSUE THREAD

**Issue by andriipalchik** [Microsoft/vscode#31507]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.12
vsc-material-theme|Equ|1.0.2
easy-icons|jam|0.3.1
material-icon-theme|PKi|2.0.11
vscode-icons|rob|7.11.0
ReactSnippets|xab|1.4.0

(2 theme extensions excluded)

I can't see the description of extensions in marketplace + I hate tiny view on the right, I'd like to customize that. Win10 x64
---

Steps to Reproduce:

1. Open the marketplace
2. Can't see description of an add.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@joaomoreno can help pass the issue to marketplace team IMO

**Comment by joaomoreno** [comment]
@andriipalchik  Please show me a screenshot of what you mean.

**Comment by andriipalchik** [comment]
This is what I mean, an empty view where the description suppose to be. And about a tiny view on the upper right corner, I’d like to hide that: 
Від: João Moreno
Надіслано: 27 липня 2017 р. о 22:57
Кому: Microsoft/vscode
Копія: Andrii; Mention
Тема: Re: [Microsoft/vscode] Issue (#31507)

@andriipalchik Please show me a screenshot of what you mean.

**Comment by joaomoreno** [comment]
Please shared your screenshot directly in GitHub. It doesn't work if you send it via email.

**Comment by andriipalchik** [comment]
This is what I mean, an empty view where the description suppose to be. 
![1](https://user-images.githubusercontent.com/17823606/28705189-5f53e4e4-7377-11e7-97a2-b1e6c78b372a.png) 

And about a tiny view on the upper right corner, I’d like to hide that:

![2](https://user-images.githubusercontent.com/17823606/28705192-68ec861e-7377-11e7-8342-6dc026b68e9b.png)

**Comment by joaomoreno** [comment]
So... you're talking about two different issues here. Let's talk about the marketplace one only. Please file another issue for the tiny view, which we call *minimap*. If you file that issue, please let us know exactly *how* you'd like to customise that. Note that you can hide it by setting `editor.minimap.enabled` to `false`.

---

As for the description of extensions:

- Does it happen for every extension?
- Can you open the Shared Process developer tools (<kbd>F1</kbd>, `Shared Process`), go to its `Network Tab` and track it while you click an extension in Code? What do the requests look like? Do they fail?

**Comment by andriipalchik** [comment]
"Note that you can hide it by setting editor.minimap.enabled to false." Thanks, that's enough for me, I'll do that. "Does it happen for every extension?" Yes 
![3](https://user-images.githubusercontent.com/17823606/28705630-5f331064-7379-11e7-85cb-c41f722db158.png) "Can you open..." Yes, I have clicked, but nothing happends: 
![4](https://user-images.githubusercontent.com/17823606/28705834-3e101b56-737a-11e7-89d2-03bb176be702.png)

**Comment by joaomoreno** [comment]
What about in the Developer Tools of the main window? Simply <kbd>F1</kbd>, `Developer tools`?

**Comment by andriipalchik** [comment]
I've made three requests (clicks) on extensions and, as you can see, 33 errors, I guess they were there at first. 
![1](https://user-images.githubusercontent.com/17823606/28707671-ef734a92-7381-11e7-85c7-02f28756b902.png)
 Than 42 errors... Than I realized: when I expand or collapse dev-tools window the number of errors is growing. But, as you can see, status-code 200 shows after each request of an item on the list. 
![2](https://user-images.githubusercontent.com/17823606/28707792-6383436a-7382-11e7-9487-ae0cc4245db3.png)

**Comment by joaomoreno** [comment]
@mjbvz @bpasero Please take a look at the exceptions in the last screenshots. They are very suspicious, have you seen this before?

@andriipalchik Can you try to open a preview of a Markdown file? Simply create a `file.md` with some markdown contents and click the preview action at the top of the editor.

**Comment by andriipalchik** [comment]
I didn't completely understand, what you mean, but I did it as I could. Here we go...  
![image](https://user-images.githubusercontent.com/17823606/28709003-0f08410a-7387-11e7-8d49-5e2068426281.png)

**Comment by joaomoreno** [comment]
Awesome, thanks: I can clearly see this is an issue with the webview.

Found out we already fixed this on `master`: #28749

Can you reproduce in our latest insider? https://code.visualstudio.com/insiders

**Comment by andriipalchik** [comment]
I guess it means that I have to delete my current build and install the one you recommend. Is that correct?

**Comment by joaomoreno** [comment]
Not really. Just download the [insider ZIP](https://go.microsoft.com/fwlink/?LinkID=733265). Try it out there.

**Comment by andriipalchik** [comment]
I downloaded an x64 zip insider build and installed 2 extensions. But still nothing. At the beginning there is a loding animation, but it disappears quickly and the readme frame remains still empty. 
![image](https://user-images.githubusercontent.com/17823606/28711728-4e7b36da-7391-11e7-810f-d9847dd40d19.png)

**Comment by andriipalchik** [comment]
I will try x32 version...

**Comment by andriipalchik** [comment]
And the same story with x32 
![image](https://user-images.githubusercontent.com/17823606/28713279-1f5e3b9e-7397-11e7-9157-dd2e2a2c3b12.png) Even when I move the border between items and the main frame, like it was with the border between dev-tools and main frame -- the number of errors in console only grows. All builds were installed on E drive, not C. That's that...

**Comment by joaomoreno** [comment]
cc @mjbvz

**Comment by mjbvz** [comment]
I can't repo the original issue but have checked in a fix for the `getOwnerBrowserWindow` call failing
