### ISSUE TITLE
Panel actions are cropped when window is narrow

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31503]
![image](https://user-images.githubusercontent.com/10746682/28659190-2350a3f2-72cc-11e7-8a49-d89b7f4ff4c4.png)

**Comment by Tyriar** [comment]
Do you mean the actions on the panel?

**Comment by sandy081** [comment]
Yes

**Comment by isidorn** [comment]
Can not repro.
How did you get in that state?
Was the editor croped as well, or only the terminal?

**Comment by Tyriar** [comment]
@isidorn the actions at the top of the panel (new terminal, kill terminal). Just make the window narrow.

**Comment by isidorn** [comment]
@Tyriar thanks for clarifying.
What would you expect @sandy081 to happen in this case.

I believe the elements are getting hidden in the correct order.

![shrink](https://user-images.githubusercontent.com/1926584/28725198-0bdb5fe0-73bd-11e7-92e9-9f1b48b1092a.gif)

**Comment by Tyriar** [comment]
We need some way of accessing the elements in the overflow, the tasks panel is making this a bigger problem than it was before.

**Comment by isidorn** [comment]
@Tyriar can you please elaborate on that?

**Comment by Tyriar** [comment]
We should strive to be usable at very narrow widths, a triple dot menu is probably the solution, just like to the right of the tab well.

Trying to use 2 instances side by side isn't too bad except for with the panel:

![image](https://user-images.githubusercontent.com/2193314/28786907-99df92c0-75cf-11e7-9d76-535ec8fe4b2e.png)

The Tasks button exacerbated the problem as it hides actions when the window is wider.

**Comment by isidorn** [comment]
I like the triple dot idea, I can look into it in the next couple of milestones

**Comment by bpasero** [comment]
@isidorn @Tyriar Ideally the panel overflow behaviour is the same as the activity bar when the window gets small:

![image](https://user-images.githubusercontent.com/900690/29348136-c37d3450-8251-11e7-91c6-3941d1a25288.png)

I suggest to:
* keep the panel actions visible at all times
* start to show a "..." for the actual panels similar to how we do it for viewlets
* when you click "..." you can pick another panel

**Comment by equinusocio** [comment]
I can suggest an overflow menu that appear under a determinate window width.

**Comment by isidorn** [comment]
Fixed via composite bar commits on master
