### ISSUE TITLE
Enablement of Compare with Saved action is not consistent

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31509]
Testing #30721

If a file is same as in disk, then 

- In Open editors, action is disabled
- But action can be run from the Command Pallette.

**Comment by PaulTFreedman** [comment]
I'd like to take a look at this as a first contribution to the project but any pointers would be great. I'm guessing a list of Actions is returned somewhere when the Command Palette is opened but I haven't found where yet.

**Comment by bpasero** [comment]
We have a general issue to adopt the when context for the command palette, closing.
