### ISSUE TITLE
Refresh in Debug is not reloading the debug session

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31504]
Testing #31107

See the attached video, Refresh in Debug is not reloading the debug session

![kapture 2017-07-27 at 13 07 31](https://user-images.githubusercontent.com/10746682/28659343-c30243c4-72cc-11e7-952a-177a8f65cc42.gif)

**Comment by isidorn** [comment]
This is fixed in latest vscode. Please try latest (builds were blocked during the night)
Thanks!

**Comment by sandy081** [comment]
@isidorn Sorry, I just saw that in slack that Mac build is not yet ready... I have latest build on Windows.. and thought the same on Mac. Will check again on latest on Mac.

**Comment by isidorn** [comment]
@sandy081 Thanks :)

**Comment by sandy081** [comment]
Confirmed it works.
