### ISSUE TITLE
Impersonating

### ISSUE THREAD

**Issue by a250188** [Microsoft/vscode#31516]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. We have local TFS and logging to this through impersonating. Team Explorer work fine with it, but Visual Studio Team Services doesnt work. When i try "Team: signin" nothing are happening. Nothing is in log too.

**Comment by egamma** [comment]
Please file the issue against the https://marketplace.visualstudio.com/items?itemName=ms-vsts.team extension.
