### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31517]
testing #31107

* create hello world extension
* have breakpoint in `extension.ts` line 12 and 21
* run debuggee, run Hello World
* step into on line 21
* 💥 in 3 out of 4 cases the DA terminates

**Comment by weinand** [comment]
I'm not able to reproduce this on "Elementary OS" and this VS Code:
Version 1.15.0-insider
Commit 0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7
Date 2017-07-28T11:16:26.188Z

**Comment by weinand** [comment]
EH debugging is now using node-debug2.
