### ISSUE TITLE
Suggest widget doesn't show whitespace characters

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31518]
Refs: #31324

Notice in the screenshot that I have a snippet choice whith a whitespace in it " 5", however the whitespace is not shown in the suggest box but is inserted once I select it.

![screen shot 2017-07-27 at 10 39 41](https://user-images.githubusercontent.com/1926584/28661891-90759c76-72b8-11e7-9b90-d50addd3ffb1.png)

**Comment by jrieken** [comment]
This is a more generic issue with the suggest widget not showing whitespace characters.
