### ISSUE TITLE
Debugger continues instead of stepping

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31519]
testing #31107

* create hello world extension
* have breakpoint in extension.ts line 12 and 21
* run debuggee, run Hello World
* break on line 12 and step through each line
* 🐛 eventually the debuggee continues, executing the command which isn't excepted

**Comment by jrieken** [comment]
This might be the same as #31517

**Comment by weinand** [comment]
closing since EH debugging now using "inspector" protocol.
