### ISSUE TITLE
Snippets: give me a way to choose diferently per each snippet choice location

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31520]
Refs: #31324

Notice in the screenshot below that I have two times $1 referenced in my snippet definition. When I trigger my snippet there is no way for me to choose different options for each place where $1 is referenced. I can only choose one thing and it will be inserted in all places

![screen shot 2017-07-27 at 10 47 21](https://user-images.githubusercontent.com/1926584/28662050-12bfaf8c-72b9-11e7-804e-825c44ebbbde.png)

**Comment by jrieken** [comment]
> trigger my snippet there is no way for me to choose different options for each place where $1 is referenced

Yeah, that is the design of "mirrors" (see 7.6 in https://manual.macromates.com/en/snippets). Repeating placeholders all get the same value. To get different values you must use different placeholder indices, like `${1|one,two|} and ${2|one,two|} with $1 and $2`

**Comment by isidorn** [comment]
Thanks for explanation
