### ISSUE TITLE
Loaded Scripts explorer: normal files are not shown in single folder workspace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31523]
testing #31327:

- file hello.js in "test" folder; test opened in VS Code

Explorer shows "test" node without children:

![2017-07-27_10-39-58](https://user-images.githubusercontent.com/1898161/28661956-c8fe42c8-72b8-11e7-8e53-ab1cbc52c3af.png)

This works fine in multi folder setup:

![2017-07-27_11-19-17](https://user-images.githubusercontent.com/1898161/28663367-723f434c-72bd-11e7-9f41-828ad62bf359.png)

**Comment by weinand** [comment]
I accidentally introduced this bug because of an unexpected behaviour of `asRelativePath`. See #31553.

**Comment by joaomoreno** [comment]
Just hit this during my testing too. 👍

**Comment by weinand** [comment]
@joaomoreno this is fixed in the latest Insiders. Did you try that one?

**Comment by joaomoreno** [comment]
Not yet 👍
