### ISSUE TITLE
‘window size bug’ when instances share one screen in Win10

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#3152]
when i run the Extension by using 'debug start', the size of the two instance windows are not same with  last time I shut them off;
Here is the screen shot:
the height of the right side window is shorter than before.
![a](https://cloud.githubusercontent.com/assets/7921431/13168847/b1644fd4-d71b-11e5-90e2-934bc088c181.jpg)

when press F1 and run the command , the size of main window .

![b](https://cloud.githubusercontent.com/assets/7921431/13169442/779059d8-d720-11e5-9cdf-43035de24264.jpg)

**Comment by bpasero** [comment]
Fixed for Feb.
