### ISSUE TITLE
Error "Extension host terminated unexpectedly. Please reload the window to recover."

### ISSUE THREAD

**Issue by leekirby6** [Microsoft/vscode#31525]
![img](http://2.pik.vn/2017483324d7-ae4f-436d-af9b-35f840a0a9ab.png)
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
vscode-angular2-files|ale|1.3.10
ng-template|Ang|0.1.4
vscode-color|ans|0.4.1
aurelia|Aur|0.3.4
Aurelia|beh|1.2.2
vscode-opennewinstance|chr|0.0.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.12
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
Angular2|joh|2.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.3.3
vscode-extension-auto-import|mop|1.3.3
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
code-settings-sync|Sha|2.8.2
autoimport|ste|1.2.2
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.8.0

(1 theme extensions excluded)

---

Steps to Reproduce:
1.  The Dialogs show usually when I'm using VS Code

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Does it reproduce without extensions?

`code --disable-extensions`

**Comment by leekirby6** [comment]
@joaomoreno No, I disabled all my extension and seem the error dialogs disappear !

**Comment by leekirby6** [comment]
I remove some extensions, and now I have 16 extensions and i don't get this error.

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-angular2-files|ale|1.3.10
vscode-color|ans|0.4.1
aurelia|Aur|0.3.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
Angular2|joh|2.4.0
code-settings-sync|Sha|2.8.2
autoimport|ste|1.2.2
bootstrap-3-snippets|wcw|0.1.0
html-css-class-completion|Zig|1.8.0

(1 theme extensions excluded)

---

**Comment by joaomoreno** [comment]
Alright. If you continue investigating towards finding the culprit, you can file that extension an issue.
