### ISSUE TITLE
Setting is missing?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31522]
Testing #31448 on Ubuntu Linux 16.04

Notice the difference:

![image](https://user-images.githubusercontent.com/22350/28662298-ef6a3eb6-72b9-11e7-9fbf-f76e4bd1538d.png)

![image](https://user-images.githubusercontent.com/22350/28662305-f3d3772e-72b9-11e7-93b3-85bcd278cf14.png)

The count in the sections on each scope both sum to 357. So, the user settings sum seems to be wrong.

**Comment by sandy081** [comment]
I am counting all the settings in the current window (defaults + right hand side). It could happen that that in your case, workspace settings has an invalid setting?

@joaomoreno Can you confirm?

**Comment by joaomoreno** [comment]
Oh I see.
