### ISSUE TITLE
files.associations setting overrides user choice

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#31524]
Testing #31448 on Ubuntu Linux 16.04

1. Create `file.foo` and open it
2. Using the status bar, change its mode to CSS
3. Without closing `file.foo`, open settings and add `"files.associations": { "*.foo": "javascript" }`
4. Switch back to `file.foo`

The mode will have been changed to JavaScript, although it should really be CSS since that's what I picked. IMO `files.associations` should only affect the choice of a mode when a file is about to open, not when it is already open, much less when I have explicitly chosen a mode.

**Comment by sandy081** [comment]
@joaomoreno When you change the `files.associations` from the status bar, I am guessing it would have added the setting to your workspace settings file because, I also guess, you would have `files.associations` setting defined there. Hence any changes done in User settings are over written by the workspace settings.

Please confirm if it is true?

**Comment by joaomoreno** [comment]
I didn't change `files.associations` from the status bar. I used the status bar to change the mode of `file.foo` only.

**Comment by sandy081** [comment]
Yeah, implicitly this will update `files.associations` setting in
- workspace settings, if it already configured here
- otherwise in user settings

**Comment by joaomoreno** [comment]
Interesting, I didn't know that.

**Comment by sandy081** [comment]
@joaomoreno Do you mind closing this issue, or do you expect a different behaviour?

@bpasero FYI

**Comment by joaomoreno** [comment]
It feels like an issue to me. 😕

**Comment by bpasero** [comment]
Yeah in [`textFileEditorModel#onFilesAssociationChange()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L187) we update the mode based on config changes. We currently have no tracking of the user changing the mode. The change from the status bar actually goes right to the Alex model.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73678
