### ISSUE TITLE
`workbench.colorCustomizations` doesn't work as a user setting

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31529]
Testing #31448 on Ubuntu Linux 16.04

![image](https://user-images.githubusercontent.com/22350/28662948-399dd540-72bc-11e7-8c81-606b117122f9.png)

Is this on purpose?

**Comment by sandy081** [comment]
@joaomoreno It works for me.. Is there a workspace setting overriding this in your case?

**Comment by joaomoreno** [comment]
Sorry, forgot to mention that it only happens on windows with no folders open.

**Comment by sandy081** [comment]
Hmm my bad its pretty clear in the picture. Sorry.

**Comment by sandy081** [comment]
Looks to me this is intentional. Because status bar indicates the type of the workspace.

**Comment by joaomoreno** [comment]
@sandy081 I don't think so. :confused: 

Look here:

![image](https://user-images.githubusercontent.com/22350/28678649-3ad3e442-72f1-11e7-90c3-87c03eab9a3f.png)

I set a status bar color in my user settings. It gets applied in both a multi-root workspace window, a single root workspace window and it doesn't get applied in a non-workspace window.

**Comment by sandy081** [comment]
Leaving this decision to @bpasero

**Comment by bpasero** [comment]
@joaomoreno you need to configure `statusBar.noFolderBackground` to change the color in an empty workspace. The basic `statusBar.background` color is only applied to workspaces with a single or multiple folders. Same is true when configuring color when debugging. 

I have updated the description of this color key to make clear the color is only when a workspace is opened.
