### ISSUE TITLE
Debugging 2 extensions doesn't work

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31533]
testing #31107

* generate two hello world extensions (foodoo, bardoo)
* have a multi-root workspace with the extension folders
* in both `extension.ts` files set a break point
* select one launch config, start, happy
* select the other launch config, start, nothing

**Comment by isidorn** [comment]
Note that I have fixed the initial problem, however there are still issues with mutliple prelaunch tasks in different session. Because this would be a larger refactoring I created a seperate issue https://github.com/Microsoft/vscode/issues/31674
