### ISSUE TITLE
Jobber.exe makes trouble with virus scanner F-Secure

### ISSUE THREAD

**Issue by iamhjr** [Microsoft/vscode#31539]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
githistory|don|0.2.2
gitlens|eam|4.3.2
rest-client|hum|0.14.6

---

Steps to Reproduce:

1.   I updated VScode to the current version
2.   I restarted the app for the changes take effect and get the following F-Secure warning: 
PotentiallyUnwanted:W32/App.0750e025c8!Online, 
<Users>\<me>\.vscode\extensions\eamodio.gitlens-4.3.2\node_modules\spawn-rx\vendor\jobber\Jobber.exe

3. I disabled scanning for this file (created exception)

Reproduces without extensions: Yes/No

Sorry, didn't check without extensions (gitlens), since I'm  working with git.
I suppose the file properties and/or  the lack of digital signature  might be a source of this trouble. 
Try code signing it.

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://github.com/eamodio/vscode-gitlens/issues

**Comment by iamhjr** [comment]
This issue was moved to eamodio/vscode-gitlens#123

**Comment by iamhjr** [comment]
Done so far.

I couldn't find any built in functionality for moving issues at your 
repo . Is there anything available that  I've overlooked?

I used the online mover from:
https://github-issue-mover.appspot.com/

Mit freundlichen Grüßen , with best regards,
Hans-Jürgen Reindt.

Am 27.07.2017 um 21:57 schrieb João Moreno:
