### ISSUE TITLE
Too subtle progress while pre-launch task is running

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31530]
I keep starting multiple debug sessions (of the same type) because don't see anything happening after clicking. What actually happens is that a pre-launch task is running and that is very easy to miss. I'd suggest to immediately show the view progress bar (as does later for a short time)

![jul-27-2017 11-10-43](https://user-images.githubusercontent.com/1794099/28663018-6e958716-72bc-11e7-99c8-84d20c5e175f.gif)

**Comment by isidorn** [comment]
This is due to the progress service which updates based on change of state in the debug world. Since change of state is always delicate I prefer to do this in debt week -> august
