### ISSUE TITLE
Window title only repainting when window is resized

### ISSUE THREAD

**Issue by pipwilson** [Microsoft/vscode#31536]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
cucumberautocomplete|ale|2.3.1
vscode-eclipse-keybindings|alp|0.9.6
xml|Dot|1.9.2
LogFileHighlighter|emi|1.1.1
tortoise-svn|fan|0.1.1
vscode-javac|geo|0.0.46
wordcount|ms-|0.1.0
seti-icons|qin|0.1.3
java|red|0.7.0
vscode-icons|rob|7.11.0
velocity|sod|0.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file with vscode - its name is not placed into the window title
2. Resize the vscode window by either dragging one of the application borders or double-clicking the window title
3. Window title will update

This also applies to tabs - changing tab does not repaint the window title, only a resize will. I had previously changed my `window.title` setting but since removed it from my settings.json and since I've been seeing this problem I'd even explicitly put the default `window.title` setting into settings.json, but it didn't make any difference.

Reproduces without extensions: Yes

**Comment by mtsh1000** [comment]
This bug seems to be fixed in Electron 2.0.4.
"Windows
 Fixed windows causing repaint issues when DWM composition is disabled. #12501"
