### ISSUE TITLE
Open loaded scripts from quick open and viewlet show different content

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#31535]
Refs: #31327

1. Put a breakpoints somewhere in vsocde unit tests
2. Start debugging our unit tests (they use legacy protocol)
3. Open the loaded scripts view, vscode/amdefine/amdefine.js -> notice how the content is nicely shown

Now open F1 > loaded scripts > find amdefine.js (notice 2 copies, both of them give "Content could not be retrieved"

**Comment by connor4312** [comment]
With tree view filtering we no longer have a loaded scripts command, so this is not relevant.
