### ISSUE TITLE
Allow to auto resize a custom view or take initial size as input from custom view contributions.

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#31532]
#31327

Start node debugging, hit a brekapoint, notice the loaded scripts view is very small. Expand an element in the loaded scripts -> you do not see anything.
Optimally the loaded scripts view should also resize a bit in this case.

An alternative is that loaded scripts by default has a bit more space

**Comment by sandy081** [comment]
I set to a default size of 5 * 22 px for all custom views. I agree that this should be configurable. Not sure if we want to have auto resizing of views like `Break points view`.

**Comment by isidorn** [comment]
I think this is needed for the remote SSH extension since by default the Help view takes 50% of the view making it look overly imporant

fyi @roblours @kieferrm
