### ISSUE TITLE
200 MB file opens but crashes after several edits

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31543]
Testing #30243

OS: Windows 32bit
Extensions: none
Hardware configuration: 8 GB RAM (7.82 usable), x64

1. Generate 200MB non-random content file using Dummy File Creator (46 lines of spaces)
2.  Open it
3. Do single edit
Observe crash. 

Seems like 300MB limit for 32bit is very rough and is probably very hardware specific. Maybe we should have more variables to define limit size?

This is how memory looks when editor opened untouched:
![image](https://user-images.githubusercontent.com/2239563/28664517-0eda0fd6-72c1-11e7-9df8-46ff5f3125ef.png)

Opening and editing for 100MB works fine (although with lags obviously).

_Dummy File Creator: http://www.mynikko.com/dummy/_

**Comment by rebornix** [comment]
@michelkaporin do you still have the machine you put in the description? We changed the buffer implementation and this issue is mitigated but I don't have similar machine to test.

**Comment by michelkaporin** [comment]
@rebornix unfortunately not, but perhaps @dbaeumer can try to reproduce on his Windows machine.

**Comment by rebornix** [comment]
Shares the same root cause (the string length limit) as https://github.com/Microsoft/vscode/issues/51625 and can be mitigated when we adopt Electron 3.
