### ISSUE TITLE
Configuration contribution scope is poorly described

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31541]
Testing #31448 on Ubuntu Linux 16.04

Here's my extension's contribution:

```json
        "configuration": {
            "properties": {
                "banana.brand": {
                    "type": "string",
                    "scope": "workbench"
                },
                "banana.resourceBrand": {
                    "type": "string",
                    "scope": "resource"
                }
            }
        }
```

Here's what I get as the description for `scope` when contributing a configuration:

![image](https://user-images.githubusercontent.com/22350/28663939-1b6714d0-72bf-11e7-8a4f-b6bfdda08dff.png)

> Scope in which the configuration is applicable. `workbench` scope defines configuration can be applied everywhere. `resource` scope defines configuration is applied only to folders and files.

I was very puzzled by this.

As I debugged my extension I opened VS Code in 3 separate windows:

- With no folder scope, I was able to set both settings in user settings
- With a folder opened, I was able to set both settings in user and workspace settings
- With a workspace opened, I was able to set both settings in user and workspace settings. When attempting to set them in one of my folder settings, I get the info, greyed-out decoration on `banana.brand`

So, it seems to me we're having a communication problem. The Intellisense description makes me think that the `resource` scope is more restricted than the `workbench` scope. And it turns out it's actually the other way around: if I contribute a `workbench` scoped configuration, I won't be able to change its value per folder, as part of a workspace. On the other hand, the `resource` scoped configuration setting is able to be overridden everywhere, in any scenario.

Should we have different names for these scopes? Should the description be different, and address the limitation of the `workbench` scope in contrast to the `resource` scope?

**Comment by sandy081** [comment]
Agreed bad description.

**Comment by sandy081** [comment]
Here is the updated simplified descriptions about `workspace` and `resource` values respectively

`Configuration to customise workbench. Can be configured only in User and Workspace Settings.`
`Configuration to customise resources. Can be configured in User, Workspace and Folder Settings.`

Any suggestions are welcome.

**Comment by joaomoreno** [comment]
How about

> Workbench specific configuration, which can be configured in the User or Workspace settings.

> Resource specific configuration, which can be configured in the User, Workspace or Folder settings.
