### ISSUE TITLE
Move focus to editor when scrolling with mouse wheel

### ISSUE THREAD

**Issue by ryanhalley** [Microsoft/vscode#31548]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|0.17.0
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.1.6
tsimporter|pmn|1.2.14
vscode-icons|rob|7.11.0
cordova-tools|vsm|1.2.7

---

Steps to Reproduce:

0. Open VSCode, with some previous tabs still open.
1. Hovering over any open tab's file, use the up/down mouse wheel to scroll around the file.
2. Press page up or page down, expecting the same file to page up or down. It doesn't, because the screen was not given focus, so the Explorer window pages up and down through the files; please change this.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
