### ISSUE TITLE
File with ‘@’ character not visible in explorer tab

### ISSUE THREAD

**Issue by alvarto** [Microsoft/vscode#3154]
I've got images for retina screens named 'discovery@2x.png'. It's both visible and accessible in Explorer:

![image](https://cloud.githubusercontent.com/assets/1797855/13169581/9f06e558-d721-11e5-9a31-82caff14c94c.png)

But not visible in VSCode Explorer tab:

![image](https://cloud.githubusercontent.com/assets/1797855/13169595/b9ea5ada-d721-11e5-948c-2c05f9999e63.png)

My "settings.json" lies below. I believe '@2x.png' file doesn't match any of those rules:

```
{
	"files.exclude": {
		"**/.git": true,
		"**/.DS_Store": true,
		"**/.vscode": false,
		"**/node_modules": true,
		"**/destination": true,
		"**/.gitignore": true,
		"**/.cache": true,
		"**/.tmp": true
	}
}
```

**Comment by Tyriar** [comment]
Cannot reproduce on Windows 10, is that Vista you are on?

If you reload Code does the file appear?

**Comment by alvarto** [comment]
OS is Win 7. After restarting the computer the problem is gone.
If this problem reproduces, I'll post here.

**Comment by bpasero** [comment]
Please do.
