### ISSUE TITLE
Open loaded script quick open command only takes first session into account

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31540]
Refs: #31327

1. Start two debug sessions
2. Quick open > open scripts
3. Notice that the quick open entries only show results for the first session

I would expect that the quick open and the viewlet view are alligned, so in quick open I would expect that multiple groups are used. Each group for a session (not sure if this is possible from an extension though). If not, then just showing them together is better than just showing one.

**Comment by weinand** [comment]
Good find. Your API was always using the active debug session.

**Comment by weinand** [comment]
This seems to work fine.
