### ISSUE TITLE
Make PowerShell a first class citizen of VS Code

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#31555]
VS Code is a powerful and loved editor by many, especially web developers. The open source nature, the extensions, the cross platform functionality, multiple language support and many other features make it a real power tool.

As a professional PowerShell developer and novice Java developer I can say that at the moment the editor is not ready for production, when writing `PowerShell` code. It feels like @daviwil  and @rkeithhill are the only ones helping out on the PowerShell part. With so many tickets it feels like they could use some extra help. Hence, this ticket.

Given that `PowerShell` is Microsofts number one scripting language, it would be great if more people could help out. I've taken the opportunity to list the most important issue of making the editor a succes below.

# Show stoppers:

1. Enable PSReadline support in the integrated console (syntax highlighting, keyboard navigation) (PowerShell/vscode-powershell#535)
   See IntelliSense in debug mode is behaving strange (PowerShell/vscode-powershell#948)
2. Copying code with a here string is incorrect (PowerShell/vscode-powershell#961)
    See: Language-aware folding (PowerShell/vscode-powershell#3422)

# Nice to haves

1. Debugger issues (PowerShell/vscode-powershell#956, PowerShell/vscode-powershell#985, PowerShell/vscode-powershell#987, PowerShell/vscode-powershell#1004)
2. 'Go to Definition' not opening the correct file (PowerShell/vscode-powershell#946)

Thank you for giving `PowerShell` a bit more TLC.

**Comment by rebornix** [comment]
@DarkLite1 thanks for the big shout out for Powershell.  @daviwil this is a good roadmap for you actually.

**Comment by rkeithhill** [comment]
I believe @daviwil is actively working on integrating support for PSReadline into the integrated console.  

RE copying code with here strings, I can't repro that but given the myriad settings available to customize, it could be related to a setting you have enabled that I don't.  I updated that issue with a request for your settings values.

On the "nice to haves" regarding the debugger, there is an important distinction between wanting to run code and debug it.  For instance, in Visual Studio 2015 when I use F#'s `Execute in Interactive` breakpoints are not honored.  OTOH there is a `Debug in Interactive` menu pick that does honor breakpoints.  I think it is reasonable to have such a feature in the PowerShell extension i.e. `Debug Selection`.

**Comment by DarkLite1** [comment]
Thx for the feedback @rkeithhill, I've updated the questions with answers for you.

It's clear that multiple PowerShell users experience similar issues about the `here strings` and the `debugging process`. See PowerShell/vscode-powershell#981 and PowerShell/vscode-powershell#977.

**Comment by TheIncorrigible1** [comment]
One thing I've noticed and read as well, is excessive RAM usage by the VSCode PowerShell host.  If MS is ending support for the ISE (5.1 last version) in exchange for VSCode becoming the default desired editor, it needs to have the features and niceties of the ISE.

**Comment by daviwil** [comment]
@TheIncorrigible1 can you give me an example of a time when the PowerShell language server uses excessive RAM?

**Comment by leoniDEV** [comment]
I think also that the Powershell integrated terminal should have its own host and load its own profile, like the terminal provided by the [PowerShell/vscode-powershell](https://github.com/PowerShell/vscode-powershell), or would be better if vscode uses the same terminal as the Powershell extention

**Comment by daviwil** [comment]
@leoniDEV running `powershell.exe` inside of the integrated terminal UI gives you plain old PowerShell with the standard ConsoleHost and profile.  If you had a different PowerShell host that worked in the terminal with its own EXE you could run that instead.

The ultimate goal for the PowerShell extension's Integrated Console is to have it reuse as much of the standard ConsoleHost as possible for maximum compatibility.  Once that happens your wish will be granted :)

**Comment by daviwil** [comment]
By the way, I think this issue can be closed since the work requested is already being tracked at the PowerShell/vscode-powershell repo.  VS Code shouldn't need any "special" built-in support for PowerShell other than what's already coming from the PowerShell extension.

**Comment by DarkLite1** [comment]
I understand your remark but I don't fully agree. There's been for over 2 months no release of an updated vscode-PowerShell extension. This proves my point that there isn't enough development going on for Microsofts number one scripting language.

**Comment by daviwil** [comment]
As always, this is a matter of resource prioritization.  I'm busy on some internal work right now so I haven't had as much time to devote to the PowerShell extension.  There's not much the VS Code team can do about that because this extension requires PowerShell language and runtime expertise.  Making it a built-in part of VS Code also gives it no extra benefits.  Sorry things aren't moving faster at the moment!
