### ISSUE TITLE
Invalid validation warning

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31557]
testing #31448 

* create a workspace and add a folder form a UNC drive
* open workspace file (e.g. via settings)
* 🐛 there is warning on the `file://authorty/path`-uri which isn't valid

<img width="599" alt="screen shot 2017-07-27 at 14 23 44" src="https://user-images.githubusercontent.com/1794099/28670094-6c08bb7e-72d7-11e7-937e-c1725861b8b7.png">

**Comment by sandy081** [comment]
@jrieken At present we only support file paths. So the pattern `^file://` is ok?

**Comment by jrieken** [comment]
Yeah, should be ok... A third slash is required but not always after the second. Try [`^file:\/\/[^/]*\/`](https://regexper.com/#%5Efile%3A%5C%2F%5C%2F%5B%5E%2F%5D*%5C%2F), it should match `file:///local/file` and `file://shares/file`
