### ISSUE TITLE
Issue with closing brakets

### ISSUE THREAD

**Issue by Stephanevg** [Microsoft/vscode#31550]
Hi guys!

- VSCode Version:

![image](https://user-images.githubusercontent.com/6302961/28665498-1aa13d96-72c4-11e7-89c1-0802e993987a.png)

- OS Version: Windows 10

Steps to Reproduce:

For some reason, some times, the powershell functions I write cannot be collapsed. In the GIF here under you that the small "+" in front of the function Manage-PowerPlan doesn't appears.

Sometimes adding more spaces between the function body and the command based help solves the issue, but it doesn't fix the issue at 100% of the time. I haven't found a logic on 'why it occurs', it seems to be random.

see here the recorded issue:

![closing brakets](https://user-images.githubusercontent.com/6302961/28665401-d5c2214a-72c3-11e7-9f52-93cf271a9c77.gif)

Cheers

1. copy code from gist--> https://gist.github.com/Stephanevg/5e345eb976da1eb276384b694fe8e5cd
2. Try to open close the function brakets

Reproduces without extensions: No

**Comment by aeschli** [comment]
Folding is purely based on indentation. You have to indent the function body.
