### ISSUE TITLE
when console.log an Object, the attributes are showed as 'undefined'

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#3155]
in the extension debug mode,many attributes of the object `doc` is showed as 'undefined'(actually, the value of `doc.languageId` is 'markdown'.)  

Here is  the screen shot
![image](https://cloud.githubusercontent.com/assets/7921431/13169780/f250c8d6-d722-11e5-98ff-7a39ecff7f89.png)

**Comment by weinand** [comment]
no longer an issue.
