### ISSUE TITLE
slightly inconsistent behaviour of asRelativePath and getWorkspaceFolder

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#31553]
Testing #31369:

Assume a folder "test" with a single file "hello.js".

- Open the folder "test" in VS Code. This is the "single folder" case.
- Add another folder. This becomes the "multi folder" case.

Dependent on these cases `getWorkspaceFolder` and `asRelativePath` return these values:

API                              | single folder  | multi folder |
---------------------| ------------- | ------------- |
getWorkspaceFolder| test                     | test              |
asRelativePath          | hello.js              | test/hello.js  |

The problem: `getWorkspaceFolder` returns the same value, but `asRelativePath` returns different values.
If you use both functions in your code you'll probably need an additional check for `workspaceFolders.length > 1` to really understand what is going on.
(I was running into this problem already: #31523)

After discussion with @jrieken we came to the conclusion that we should keep the current behaviour of   `asRelativePath` (since it is convenient if you just need a short but unique path) but introduce an additional boolean argument that allows to get a more stable/robust behaviour: e.g. a value of true returns the path with a prepended folder name, and a value of false omits the folder name.

**Comment by jrieken** [comment]
The signature is now like this: 

```ts
export function asRelativePath(pathOrUri: string | Uri, includeWorkspaceFolder?: boolean): string;
```

and value of `includeWorkspaceFolder` defaults to `true` when there are multiple workspace folders, otherwise it's `false`.

**Comment by vrachels** [comment]
I mentioned a bug in https://github.com/Microsoft/vscode/issues/33709 in that `asRelativePath` returns the normalized(input) the workspace root is provided.  How does this behave in the new multiple workspace environment?  with includeWorkspaceFolder true | false?
