### ISSUE TITLE
OOM crash when searching from the viewlet in a file that consists of a single 100MB line

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31551]
Testing #30243 

1. Generate file as in #31545 and open it.
2. Add some text you would like to search for in several places.
3. Open search **viewlet** and search for the text.

VS Code crashes.

**Comment by alexandrudima** [comment]
@roblourens Do we restrict the search results preview in the viewlet to a region around the match or do we dump the entire matching line in the DOM ?

**Comment by roblourens** [comment]
Searching in files with long lines has always been an issue. I think there's another issue for this but I can't find it. With better large file support, I should work on this.

**Comment by alexandrudima** [comment]
@roblourens :+1: . I would consider this a low-priority, source code or log files that consist of a single 100MB line sound pretty unrealistic to me.

**Comment by sbatten** [comment]
verified but did see the other known issue of reporting one extra character on matches
