### ISSUE TITLE
Trailing white spaces diffs are not rendered

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#31556]
Testing #30259

See the attached video

![kapture 2017-07-27 at 17 14 54](https://user-images.githubusercontent.com/10746682/28668849-67e94ac8-72ef-11e7-887c-4c5ccd142f48.gif)

I have the setting `"diffEditor.ignoreTrimWhitespace": false`. In the above video when I edit, trailing white spaces diffs are not rendered

**Comment by alexandrudima** [comment]
I believe I fixed this in the meantime:

![kapture 2018-04-30 at 11 56 01](https://user-images.githubusercontent.com/5047891/39422419-7f909a7a-4c6d-11e8-9847-0213584b6d42.gif)
