### ISSUE TITLE
Expose keyup/keydown events to extensions

### ISSUE THREAD

**Issue by Nicd** [Microsoft/vscode#31552]
- VSCode Version: 1.14
- OS Version: Any

It would be useful if an extension could hook into keydown/keyup events when _any_ key is pressed, not just when a keybind matches. So to have an event that is sent every time a key is pressed or released.

We have a plugin that attempts to detect how much the user is typing in any given language and it would be much more accurate to use keyup events instead of `onDidChangeTextDocument`, where you have problems with copy & pasting, editing of ranges and that sort.

**Comment by rebornix** [comment]
There is an undocumented command called `type` which you can override and it's how the Vim extension is implemented. But only the last override command can win so it won't work together with Vim extension.

Besides, we don't expose KeyDown or KeyUp events to extension host.

**Comment by Nicd** [comment]
What is the reason for not exposing keydown/keyup events for extensions? Is this a hard rule or can a feature request be added?
