### ISSUE TITLE
Duplicate edit actions in settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31563]
Refs: #31448

1. Hover over the edit action in the settings margin
2. Notice double hover

Also sometimes there are multiple edit actions in the margin, even though there should always be exactly one.

![screen shot 2017-07-27 at 14 49 24](https://user-images.githubusercontent.com/1926584/28670880-f190b9d8-72da-11e7-82b8-7d6999bcc35e.png)

**Comment by isidorn** [comment]
Also when executing those actions I am offered multiple choices so it seems that actions are lying on top of each other and they all get executed upon click.

**Comment by sandy081** [comment]
@isidorn May I know how do you get into this state?

**Comment by sandy081** [comment]
I could reproduce it.

**Comment by isidorn** [comment]
Ok great
