### ISSUE TITLE
Javascript syntax highlighting breaks on object literal with "<" in value

### ISSUE THREAD

**Issue by MaartenStaa** [Microsoft/vscode#31566]
- VSCode Version: 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e)
- OS Version: macOS 10.12.5

Steps to Reproduce:

```javascript
const foo = {
  '\n': '<br />' // this is the problematic line
}

function bar (text) {
  return String(text).replace(/[\n]/g, s => foo[s])
}
```

1. Put the following code in a new file and make sure the language mode is set to JavaScript
2. Note that the syntax coloring breaks (function keyword has the same color as the function name). If the indicated line is removed, it works.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks this should already be fixed in the current VSCode insiders builds
