### ISSUE TITLE
nls support for package.json and common-js

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3156]
### Assignments

- [x] Windows @joaomoreno 
- [x] OS X @weinand  
- [x] Linux @Tyriar 

### Details

We now have nls support for package.json and common-js. To test do the following:

#### Package.json for Extensions
- create a package.nls.json file as a sibling to your package.json file
- in `package.json`, replace strings that should be localized with a key surrounded by %%. For example
```json
"commands": [
			{
				"command": "typescript.reloadProjects",
				"title": "%typescript.reloadProjects.title%",
				"category": "TypeScript"
			}
		],
```
- In the package.nls.json add a key value pair that maps the key to a human readable value for our default language (which is English).
```json
{
	"typescript.reloadProjects.title": "Reload Project",
}
```

Ensure that when you start  the extension the correct string is presented in the user interface. Also ensure that pseudo translation works. To do so start vscode with --locale=pseudo. The strings from the package.nls.json should be enclosed in [] and vowels should be doubled.

#### CommonJS Extensions

Install `vscode-nls` as a dependency of your extension. In the extension main add the following code:
```typescript
import * as nls from 'vscode-nls';
let localize = nls.config({ locale: 'pseudo' })();
```
And in the activate function add
```typescript
console.log(localize('key', 'Extension activated'));
```
This should show the following in the console:
```
[Plugin Host] ［Exteensiioon aactiivaateed］
```

In other files in the extension you don't need to configure the nls module again. You can simple do:
```typescript
import * as nls from 'vscode-nls';
let localize = nls.loadMessageBundle();
```

If you want to leave the code in since you tested it with your extension code then simply remove the locale property and initialize as follows:
```typescript
import * as nls from 'vscode-nls';
let localize = nls.config()();
```

**Comment by joaomoreno** [comment]
More detailed testing steps would be appreciated.

Also, I have no idea how to test a Portuguese translation, for example...

**Comment by weinand** [comment]
@joaomoreno we do not have any translations other than the pseudo translation. If we had, you could test Portuguese by launching code with "--locale=pt_PT" or "--locale=pt_BR".

**Comment by joaomoreno** [comment]
Isn't each extension supposed to ship its own translations files? If so, how can I set up a Portuguese file?

**Comment by weinand** [comment]
@joaomoreno the process (i.e. tools) that produces these files is not yet ready (https://github.com/Microsoft/vscode-nls-dev). The default package.nls.json I've created manually. I assume that you can make a Portuguese clone of it but we would have to reverse engineer the name of that file from the source in vscode-nls-dev.
For the other nls files it is even more complex to manually doing it because the keys that you pass to localize() are converted into sequential numbers...

**Comment by joaomoreno** [comment]
Got it
