### ISSUE TITLE
Settings: wording feedback

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31564]
Refs: #31448

"Place your folder settings here to overwrite those from the Workspace Settings". I would prefer
"Place your ${nameOfFolder} folder settings here to overwrite Workspace Settings"

"This setting cannot be currently applied because it does not support the folder resource scope. Changing it might impact other workspaces."

I would prefer 
"This setting cannot be currently applied because it does not support the folder resource scope. Changing it will have impact when {nameOfFolder} is opened outside of a workspaces."

![screen shot 2017-07-27 at 14 52 57](https://user-images.githubusercontent.com/1926584/28670967-51162b5e-72db-11e7-9695-d279693c5ba5.png)

**Comment by egamma** [comment]
We should try to simplify this even more and try to avoid the close to the implementation words`folder resource scope`. 

Suggestion:
This setting is not applicable when the folder is a root of a workspace. It is only applicable when you open the folder "FOLDERNAME" directly."

Not clear why we explain "Changing it might impact other workspaces".

**Comment by sandy081** [comment]
How about following?

<img width="663" alt="unsupported_setting_info" src="https://user-images.githubusercontent.com/10746682/28707979-029702e2-7398-11e7-8ba9-90ff556f04be.png">

**Comment by sandy081** [comment]
Updated with suggestions from the team. Cannot include the folder name for now. Will add it in next milestone.

**Comment by configurator** [comment]
May I suggest "This setting cannot be applied as part of a workspace." instead of "This setting cannot be applied now."? The word _now_ introduces ambiguity.

**Comment by sandy081** [comment]
No plans

**Comment by isidorn** [comment]
@sandy081 cant we fix this, should be less than 2 minutes? Just changing strings?
I can also do it if you prefer that.

**Comment by sandy081** [comment]
@isidorn It is just not the string change, it also needs the folder of the setting in which it is. I think it is not trivial as the message is registered to JSON schema where I do not know about folders.

One alternative is to generate the diagnostic programatically by the settings editor. 

Since it is not trivial and I see no others complained about it, I closed it.

**Comment by isidorn** [comment]
@sandy081 got it. Ok, makes sense.
