### ISSUE TITLE
Settings editor doesn't update when folder is removed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31561]
testing #31396

* have a workspace with three folders a, b, and c
* open settings editor and edit settings for folder b
* in the explorer remove folder b from the workspace
* 🐛 the settings editor doesn't update, the drop down does...

<img width="375" alt="screen shot 2017-07-27 at 14 38 18" src="https://user-images.githubusercontent.com/1794099/28670517-63ed6168-72d9-11e7-9df1-2ce146a30faf.png">

**Comment by sandy081** [comment]
This happens when Folder Settings is open and at the same time Folder is removed. 
Moving this to next milestone.

**Comment by sandy081** [comment]
Settings editor switches to User settings in this case.
