### ISSUE TITLE
Token color customisations not applied live

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31567]
Testing #31360

1. Open file with some variables defined.
2. Add 
`"editor.tokenColorCustomizations": {
		"variables": "#00f000"
}`
No live editor update is happening, although when closing and opening again, css colors are applied.

Works for `comments` and `keywords` color customisations.

**Comment by LeviticusMB** [comment]
I'm using

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
          {
            "name": "Comment",
            "scope": "comment",
            "settings": {
              "foreground": "#7b88a1"
            }
          }
        ]
      }
```

to override the *Nord* comment color, but the override does not happen when I start VSCode. I need to modify and save `settings.json` for the override to take.
