### ISSUE TITLE
Bogous message when reordering workspace folders

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31562]
testing #31396

* have a workspace with three folders
* open workspace settings
* swap the second and first path in the folders-section
* 🐛 a popup tells me that our "extension system" needs to restart

<img width="718" alt="screen shot 2017-07-27 at 14 41 39" src="https://user-images.githubusercontent.com/1794099/28670661-f25aff82-72d9-11e7-8d42-aa36af9eb74d.png">

For once I doubt that is correct because only 0-1, 1-N transitions require a restart. Then I believe "extension system" isn't good wording. Let's just say the window needs to be reloaded (and obviously only when actually required to do so)

**Comment by bpasero** [comment]
@jrieken I would love to get rid of this ugly dialog but my understanding is that our (now deprecated) `workspace.rootPath` is using the "first root folder" you have configured. So if that one changes, how can we propagate this change to extensions with reloading our extension system?

Btw the wording came out of a discussion I had with @weinand (please read https://github.com/Microsoft/vscode/issues/31014).

**Comment by bpasero** [comment]
We should remove this prompt once we can restart the extension host (which @alexandrudima is working on).

**Comment by bpasero** [comment]
**Verification:** The extension host is now restarted when the first root folder changes. Any extension accessing the `workspace.rootPath` should get the new root folder, this needs verification with an extension that is active while the root folders are changed.
