### ISSUE TITLE
Use comments on top of settings file to explain complex relationship between different settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31565]
Refs: #31448

1. Notice how there are comments on the first line of the user settings
2. There are no comments in folder or workspace settings

I suggest to add a one line comment to better explain the complex relationship between each of the settings.
Also in the folder settings you could specify that only some settings are supported and that their list can be seen on the left.

**Comment by sandy081** [comment]
We cannot use comments because a settings file will be source of workspace settings in a workspace and also a folder settings in different workspace. Hence I used a header instead of comments. The reason you see comments in User settings is because, you would have created previously when we add comment to the file while creating.

**Comment by isidorn** [comment]
@sandy081 I do not fully understand why we can not add comments to the workspace settings at least?
Since they only have one purpose

**Comment by sandy081** [comment]
Because, Settings file in Single Folder case is shown as Workspace settings and the same is shown as Folder settings in MR workspace.

**Comment by isidorn** [comment]
I meant the workspace setting, like this one
```json
 {
	"id": "1501162277821",
	"folders": [
		"file:///Users/isidor/Development/w/ts-extension",
		"file:///Users/isidor/Development/w/standup"
	],
	"settings": {}
}
```

**Comment by sandy081** [comment]
So we do not have comments in workspace settings in single folder case?

**Comment by isidorn** [comment]
Correct.

**Comment by sandy081** [comment]
Wont be inconsistent?

**Comment by isidorn** [comment]
I misunderstoo your previous quesion.
I would always add comments to this file -> explainig what it does and what is the relatinship to the other settings files. Try to make it one line like the user settings

**Comment by sandy081** [comment]
So, it means that existing comment has to be updated based on the context? What happens if user updates the comment in the file ?

**Comment by isidorn** [comment]
Can't we put a general comment not dependet on the context. SOmething like
"// Place your settings in this file to overwrite user settings. These settings can beoverwritten by folder settings."

As when the user updates the comment in the file I suggest to have the same behavior as if the user updates the comment in the user settings

**Comment by sandy081** [comment]
Not sure if we can have a simple comment explaining both the contexts. Might be confusing to the user. It would be nice, if the comment is very specific to the context like header.
