### ISSUE TITLE
Editor settings apply to settings editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31560]
testing #31396

Maybe not a bug, at least funny... 

* have a workspace with multiple folders
* for both folders configure different font sizes, faces, etc
* switch between user, workspace, and each folder setting and see how the editor always changes its appearance. While I understand why that is it is a little unexpected in our ui'ish settings "editor"

**Comment by sandy081** [comment]
As per design this is expected given that our settings editor is file based editor. Its the same behaviour if you open the settings files from two folders separately. 

But I agree, in this Settings editor we can have consistent UI.
