### ISSUE TITLE
Weird selection color of setting on margin hover

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31570]
Refs: #31448

Hover over the margin in the settings, notice we use a weird color to decorate the settings line.
In light theme it is banana yellow and in dark it is gray.
I do not think we use these colors in other places. Could we instead use a well known color?

Maybe the debug top stack frame decoration color?

![screen shot 2017-07-27 at 15 10 49](https://user-images.githubusercontent.com/1926584/28671749-0ec70ffe-72de-11e7-9e48-6440b9566439.png)

**Comment by sandy081** [comment]
I use the same line highlight color that is used in editor `find` because they are similar behaviours.

**Comment by isidorn** [comment]
Editor find is much less subtle 

![screen shot 2017-07-27 at 15 40 37](https://user-images.githubusercontent.com/1926584/28673109-f8b131c8-72e1-11e7-8cec-01c94f370cb4.png)

**Comment by sandy081** [comment]
Ok it looks to me a bug that, there are overlapping decorations (undisposed decorations). May I know how do you get into this state. 

I think if you try fresh you see a subtle colour.

**Comment by isidorn** [comment]
@sandy081 It is probably then a duplicate of the other issue I marked as important, where there are mutiple actions pilling up.

**Comment by sandy081** [comment]
Yes could be

**Comment by sandy081** [comment]
Duplicate of #31563
