### ISSUE TITLE
Simplify configuration api docs

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31575]
Refs: #31448

Currently the documentation around confgurations in vscode.d.ts sound very puzzling to me. Could we somehow simplify this - make it nicer?

If you agree this is needed I can come up with a proposal

fyi @jrieken 

![screen shot 2017-07-27 at 15 36 38](https://user-images.githubusercontent.com/1926584/28673012-a0eaceea-72e1-11e7-8ece-556f884f0a7c.png)

**Comment by sandy081** [comment]
Sure, suggestion are very much appreciated

**Comment by sandy081** [comment]
@isidorn Do you thought about any suggestions?

**Comment by isidorn** [comment]
If nobody else complained then I believe it is good.
Also nothing better comes to mind at the moment
