### ISSUE TITLE
Resource setting decoration doesn't show up when opening `settings.json`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31577]
Testing #31448 

In a workspace with two folders, I opened one of the folder's `settings.json` file directly.

Notice how the dimmed decoration and info icon don't show up when opening the folder `settings.json` file directly:

![image](https://user-images.githubusercontent.com/22350/28673601-31084be6-72e3-11e7-8b4c-a31225ae1157.png)

**Comment by sandy081** [comment]
Yeah, Decorations are rendered only in Settings editor.
