### ISSUE TITLE
can read/write folder settings in single folder setup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31573]
testing #31448

* don't open a workspace but just a folder (old world)
* have extension like below, it doesn't fail tho the test plan suggests something different
* also, `inspect` doesn't set the `workspaceFolder`-value to `undefined`

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello', async () => {

        if (!vscode.window.activeTextEditor) {
            return;
        }

        let value = await vscode.window.showInputBox({
            prompt: 'Insert font size',
            validateInput(input) {
                if (!/\d+/.test(input)) {
                    return "Input a number";
                }
            }
        });

        if (!value) {
            return;
        }

        let config = vscode.workspace.getConfiguration(undefined, vscode.window.activeTextEditor.document.uri);
        try {
            console.log(`inspect("editor.fontSize")`, config.inspect('editor.fontSize'))
            await config.update('editor.fontSize', Number(value), vscode.ConfigurationTarget.WorkspaceFolder);
        } catch (e) {
            console.error(e);
        }
    });
}
```

**Comment by jrieken** [comment]
I have files this because it disagrees with the test plan. However, I don't necessarily dislike this behaviour...

**Comment by sandy081** [comment]
To be strict, update to folder target in single folder workspace should throw an exception. Writing into FOLDER target is always not common and special. Hence, if a user intends to write into folder, this should go into folder target not to workspace target. Being setting file is same is an implementation detail.

**Comment by sandy081** [comment]
I always set all values even though they are undefined. But Console is smartly skipping properties with undefined values.

```
defaultValue: config.default,
globalValue: config.user,
workspaceValue: config.workspace,
workspaceFolderValue: config.folder
```
