### ISSUE TITLE
Configuration.update does not seem to have effect

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31584]
Refs: #31448

Have an extension with the following code

```js
configuration.get('resourceConfiguration');
console.log(configuration.inspect('resourceConfiguration'));
configuration.update('resourceConfiguration', true, vscode.ConfigurationTarget.WorkspaceFolder)
console.log(configuration.inspect('resourceConfiguration'));
```

I would expect the last console.log to ptrin out true, it prints out false instead

**Comment by joaomoreno** [comment]
@isidorn `update` is async. Make sure you `await` or `then` it.

**Comment by isidorn** [comment]
I actually could get it to repro by just executing commands in the repl, and in the end doing a get. By that time the async finished, so the bug still holds

**Comment by joaomoreno** [comment]
The repl is different. There is time for it to complete between the two statements.

**Comment by sandy081** [comment]
@isidorn Are you able to reproduce it by placing `await` before `update` call?

**Comment by eamodio** [comment]
FWIW, I haven't seen any issue where `await` on the `update` doesn't work. (GitLens relies on this heavily in a few areas)

**Comment by isidorn** [comment]
All good, the async function was throwing an error which I was not catching.
My bad
