### ISSUE TITLE
Improve API configuration `update()` error message

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31583]
Testing #31448 

I attempted to write to a non-resource setting from an extension, under the folder scope. I got this error:

![image](https://user-images.githubusercontent.com/22350/28674991-cb081b24-72e6-11e7-849b-99309e2db133.png)

Shouldn't the error be more specific? Something in the lines of:

> The `xxx` setting can't be set under the `yyy` configuration target because zzz.

Something like that?

---

Related to #31541 due to wording

**Comment by joaomoreno** [comment]
Similarly, I'm now trying to update a setting on the `WorkspaceFolder` target, but I scope to a resource which isn't contained by any of the open folders. I get the same generic message:

![image](https://user-images.githubusercontent.com/22350/28675457-38b0f4f6-72e8-11e7-9a1d-a09db96e4cdb.png)

It should describe why I can't do what I'm trying to do.

**Comment by sandy081** [comment]
Yah this is how we had been reporting for invalid configuration target. Good that we discover such old issues (with wordings) too.
