### ISSUE TITLE
menu bar shortcut not work

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#31586]
origionally when I **press** and then **release** Alt key the menu bar would show the hot keys with underscores, and then I could type the key to activate the menu:
i.e. press and release alt would show the help with 'h' underscored, and then press h, the help menu would showup.
this is the default feature works in all the editors, i.e. visual studio, and windows explorer

**Problem:**  
recently the feature is not work.
currently it's not work, if I press 'h', i will type 'h' in the editor

**Comment by jens1o** [comment]
@metasong Well yes, there are going to fix it, but its priority is not very high. Quite the opposite is true. When somebody has time, he should file a pr, and then this issue can be resolved faster.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24514
