### ISSUE TITLE
Add option to open recent workspace in new window

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#31581]
It should be possible to open a recently closed workspace in a new window by clicking on "Open Recent" -> "NAME (workspace)". Currently, it seems to replace the workspace in the current window.

**Comment by bpasero** [comment]
@Dominik-K if you hold the Ctrl key or Shift key (macOS: Alt key or Cmd key) you can force open in a new window. 

You can also configure: `"window.openFoldersInNewWindow": "on"`

**Comment by Dominik-K** [comment]
@bpasero Thanks for your kind answer. Didn't know this.
