### ISSUE TITLE
VSCode : connection problems even when connection works in one tab, and refuses to work in another tab. :((

### ISSUE THREAD

**Issue by Hitoshma** [Microsoft/vscode#31587]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jsontotype|dan|0.0.3
json-tools|eri|1.0.2
code-runner|for|0.6.28
macros|ged|1.2.0
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
Csharp-ASPNETCore|rah|1.0.5
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Hitoshma** [comment]
Connection problems even when connection works in one tab, and refuses to work in another tab. :((

**Comment by rebornix** [comment]
@Hitoshma sorry I don't get what's the connection problem you have?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
