### ISSUE TITLE
Recently opened files is just a bucket and not sorted by recency

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31591]
I have a multi-root workspace with the vscode-sources and an extension (called 'virtual'). Both folders have `vscode.d.ts` and while I surely have opened both files at least once, I have opened `vscode.d.ts` from the vscode-sources at least 1000-times more often (and more recent). Still, the file picker presents the `vscode.d.ts` from the extension on top, always. It seems like I once made a mistake to open the wrong vscode.d.ts-file and I am still being punished for that. 

<img width="944" alt="screen shot 2017-07-27 at 17 12 07" src="https://user-images.githubusercontent.com/1794099/28677856-12e45cd4-72ef-11e7-8806-8dc37eda1a11.png">

**Comment by bpasero** [comment]
@jrieken if you now select the `vscode.d.ts` from the `vscode` folder and bring up the picker again, you are not seeing the one from `vscode` first?

**Comment by bpasero** [comment]
@jrieken I think I see what happens, you are starting to search and in that case the sorting order of the "recently opened" section is no longer by recency but using a similar matching and sorting as we have for the file results below. 

One way of getting rid of the result is to trigger the "Remove From History" command and pick the file you want to remove. It will not help though if you ever open it again:

![image](https://user-images.githubusercontent.com/900690/29216959-94b81f12-7eb0-11e7-8ea7-f4e5ff49d1de.png)

**Comment by jrieken** [comment]
> In this case it seems the shorter path is just winning over the longer one.

For IntelliSense matching length is only penalised between the first and last matching character, not on the ratio of covered characters. That usually yields much better results

**Comment by bpasero** [comment]
I am now sorting by recency of items in this bucket if the score of the elements are identical instead of sorting by path length.
