### ISSUE TITLE
onDidChangeWorkspaceRoots comes too early

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31597]
`onDidChangeWorkspaceRoots` event comes too early. If i try to get the configuration of one of the roots I get undefined results.

I believe the onDidChangeWorkspaceRoots events should come only after I am able to read settings from all the roots

**Comment by sandy081** [comment]
Right, roots changes are detected first and then configuration is computed and notified. Let me know how important is it for you to get this fixed?

I would like to move it to next milestone if not important.

**Comment by isidorn** [comment]
Not that important, next milestone is fine

**Comment by sandy081** [comment]
Thanks
