### ISSUE TITLE
Consider to move optional argument to the end

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31592]
testing #31475

The signature of `startDebugging` marks the first parameter as optional'ish which looks a little weird to me. I would have written it the other way around. Unsure why it done this way?

```ts
export function startDebugging(nameOrConfiguration: string | DebugConfiguration, folder?: WorkspaceFolder): Thenable<boolean>;

```

**Comment by weinand** [comment]
The only alternative would be something like this:
```
function startDebugging(folder: WorkspaceFolder, nameOrConfiguration: string | DebugConfiguration)
function startDebugging(configuration: DebugConfiguration)
```
But again, the existence of the second conveys the wrong message: the simple API is probably not what you need.

**Comment by jrieken** [comment]
I understand, if `DebugConfiguration` makes use of variables like `${workspaceRoot}` it needs a folder. I believe I just not a friend of the `foo | undefined` declaration but I can live with it

**Comment by weinand** [comment]
No change planned.
