### ISSUE TITLE
Is `workbench` a good name?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31593]
testing #31448

When defining a config setting from an extension I can define its scope. One value is `workbench` which looks like an internal name. How about `editor`?

**Comment by egamma** [comment]
@jrieken The settings scopes are _resource_ and _workbench_. All the 'editor.*' settings are in the resource setting scope and they are honored as a folder setting. Using the term term editor for workbench settings (which are not honored as folder settings) would be confusing.

**Comment by jrieken** [comment]
Fair point, taking back `editor` still wondering if have used `workbench` in an API-style before

**Comment by egamma** [comment]
In the API there is `window`. So we could change to:
- workbench -> window
- resource -> editor

@sandy081 we should discuss this is in the stand up.

There are 2 references to `workbench` in vscode.d.ts:
![image](https://user-images.githubusercontent.com/172399/28688959-20cf6cec-7314-11e7-96b8-c79e87ecd1fe.png)

**Comment by sandy081** [comment]
I think calling workbench - `window` makes sense. We call `window` at multiple places.
But I would stick to `resource` than editor. In API, we call VS Code editor as `editor`. This might also confuse with `editor.*` settings.
