### ISSUE TITLE
Select next and previous problem

### ISSUE THREAD

**Issue by pedrov-sh** [Microsoft/vscode#31595]
I've found a bug in VSCode. In first, I'm using MacOSX.  
  
When I press **Command+U** to go back to the previous selection (or point of a snippet) and I press **Command+D** again to select the next match (or point of a snippet), the VSCode takes me to the point **AFTER of what I expect**.  
  
**IN EXAMPLE:** we have the points **1**, **2**, **3**, **4**, **5** of a snippet. I'm currently in the 2. I press **Command+U** to back to the **1**, so I press **Command+D** to match the next (and **I expect to go to 2** again) and it takes me to the 3 (it continues increasing erroneous).  
  
What we could do to solve that?

**Comment by alexandrudima** [comment]
@pedrov-sh Can you provide more simple steps (reduce the level of abstraction) so I can try to reproduce ?
