### ISSUE TITLE
Color Theme Error: Sorry, this language is not supported. Only support Javascript, CSS and HTML.

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode#31596]
Every time I start VSCode, or I change the zoom level, I get this error message. The theme I'm using is "Dark+ (Default Dark)." I think when I switch to **any** theme, I get this error. Here's a screenshot:

![image](https://user-images.githubusercontent.com/791996/28679706-eb2cd8ba-72a8-11e7-8616-eba46078a98f.png)

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.3.10
ng-template|Ang|0.1.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.7
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
python|don|0.6.9
xml|Dot|1.9.2
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
vscode-npm|fkn|3.3.0
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.1.1
docthis|joe|0.4.7
angular-essentials|joh|0.2.0
Angular1|joh|0.2.0
Angular2|joh|2.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.11
easy-less|mrc|1.4.5
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.0.11
vscode-icons|rob|7.11.0
code-settings-sync|Sha|2.8.2
python|tht|0.2.3
gitblame|wad|2.0.2
wallaby-vscode|Wal|1.0.55
blade-runner|yuk|1.0.0

(19 theme extensions excluded)

---

Steps to Reproduce:

1. I don't know. It just happened.

Reproduces without extensions: **No**

**Comment by mjbvz** [comment]
This is caused by one of your extensions. You can verify this by starting code with the `--disable-extensions` command line flag.

Please try going through your installed extensions to identify which one is causing this and report the issue against them

**Comment by ramya-rao-a** [comment]
@AskYous I believe the extension that is giving that error is vscode-JS-CSS-HTML-formatter.

I found this: https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/blob/master/src/extension.ts#L56

**Comment by AskYous** [comment]
@ramya-rao-a thanks.
