### ISSUE TITLE
Test stable Windows 64 bit ad

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31598]
@egamma Remember that we moved the windows 64 bit ad to the top of the release notes: https://github.com/Microsoft/vscode-docs/commit/7f7d770e921f91250ec94cd897ec832832cb06a8

Once the docs are published, and ideally before they actually are, we should test that the following URL puts users in the right place:

`https://code.visualstudio.com/updates/v1_15#_windows-64-bit`

cc @gregvanl

**Comment by egamma** [comment]
Assigning to @gregvanl pls check before the release.

**Comment by egamma** [comment]
@gregvanl just read through the latest version of the releasenotes an noticed that the 64bit section got moved to the bottom. has this been tested with the latest upgrade-to-64 bits message box we are showing?

**Comment by gregvanl** [comment]
@egamma @joaomoreno Yes, the location of the H2 header doesn't matter for the link. 
Sean wanted the section moved down. Is there another reason to have it at the top for the final release notes? It is also included in the 1.15 highlight links.

**Comment by gregvanl** [comment]
Verified on 1.15.
