### ISSUE TITLE
Snippet support for tasks.json

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3159]
### Assignments

- [ ] Windows @alexandrudima 
- [ ] OS X @chrisdias 
- [ ] Linux @isidorn

### Details

Instead of generating a tasks.json with a lot of well know tasks.json examples we now present the user a list of snippets to choose from. To test do the following:

- new workspace
- F1 > Task Configure > Enter

Expected: the editor opens and it looks like this:

![capture](https://cloud.githubusercontent.com/assets/1931590/13424945/084d5a44-dfa4-11e5-94db-20749b95792f.png)

You can pick a snippet and it gets correctly inserted into the task.json

**Comment by felixfbecker** [comment]
can extensions provide new snippets for tasks.json? For example, a Java language support extension might want to provide a build task with javac and a problem matcher.

**Comment by egamma** [comment]
@felixfbecker not yet, pls see #3125

**Comment by dbaeumer** [comment]
Reopen to retest in March

**Comment by felixfbecker** [comment]
Please consider to also add a snippet for npm scripts, many people use them.

**Comment by dbaeumer** [comment]
Closing in favour of https://github.com/Microsoft/vscode/issues/4019.
Created https://github.com/Microsoft/vscode/issues/4115 for the npm request.
