### ISSUE TITLE
2 UIs to open loaded scripts: view extension and command to show loaded scripts

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#31605]
Testing #31327

There are new 2 UIs for loaded scripts:
- view contribution in the debug viewlet
- command to show loaded scripts in the quick pick

Suggest to unify/simplify. The quick pick has the benefit that you can search for scripts. So one suggestion is to add a search scripts toolbar button to the view contribution that shows the quick pick dialog. Selecting an item from the quick pick opens the script and selects it in the loaded scripts view.

**Comment by weinand** [comment]
Agreed, we should unify.
But currently the Tree does not support to expand/reveal/select items.

**Comment by weinand** [comment]
The Loaded Scripts view supports filtering/searching and the QuickPick menu is gone.
