### ISSUE TITLE
Broken intellisense

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#3160]
I don't get any intellisense in my project anymore. VSCode just treats typescript files as a normal text files. Though it works for other TypeScript projects. 

I cannot narrow down what it is.

**Comment by DickvdBrink** [comment]
You have a workspace you can share?

**Comment by tinganho** [comment]
Unfortunately no, I use tsx files if that helps. 

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "outDir": "Build",
        "rootDir": ".",
        "experimentalDecorators": true,
        "jsx": "react",
        "removeComments": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by tinganho** [comment]
It works on a local computer. If I mount on a local VM it doesn't work, though it seems only specific to this project. Since I can mount a local VM for other projects.

Any thought on what could go wrong? It also works if I don't specify this settings:
```
{
	"typescript.tsdk": null,
}
```
I use bleeding edge TypeScript otherwise.

**Comment by tinganho** [comment]
It seems like this is a TypeScript problem. It works if I install older version of TypeScript. `typescript@1.8.0-dev.20151223` is the latest I've tried so far that works.

**Comment by tinganho** [comment]
I can probably get you the day when it didn't work.

**Comment by tinganho** [comment]
This was the the date when it didn't work: typescript@1.8.0-dev.20160116. So everything before that works.

**Comment by tinganho** [comment]
TypeScript problem
