### ISSUE TITLE
Feature Request: Don't include file extension in file sorting

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#31608]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0

---

Feature Request:

I'd like it if the `EXPLORER` view did not sort files using their file extensions (unless necessary).

E.g.,
- schema-grid.js
- schema-grid-aggregator.js

The above files should appear in the order I've specified. However they appear in reverse order, I'm guessing because `-` comes before `.` in some imaginary ordinal system. I figure if we remove extensions from this equation it'll appear in the order I've specified.

All the same I love VSCode. Keep up the good work.

**Comment by isidorn** [comment]
We already have 5 sort orders in the explorer, please try them out if this fixes the issue for you. If not, let us know and we will reopen this feature request 

![screen shot 2017-10-26 at 15 28 32](https://user-images.githubusercontent.com/1926584/32055527-614d0eec-ba62-11e7-9707-f5c8944a0c08.png)

**Comment by klick-barakgall** [comment]
Hello @isidorn 

None of the sort orders appear to address my concern. Is there something I'm missing?

**Comment by isidorn** [comment]
@klick-barakgall then we can reopen this as a feature request

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
