### ISSUE TITLE
Copy the error in problems view

### ISSUE THREAD

**Issue by lidderupk** [Microsoft/vscode#31606]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.4.0
- Extensions: the listing length exceeds browsers' URL characters limit
---
Steps to Reproduce:

1. Create a python file and add some problematic code
`from requests import hello`
2. The problems view says `No name 'hello' in module 'requests'`

When I right click on copy this problem it copies the following:
``` 
file: 'file:abc.py'
severity: 'Error'
message: 'E0611:No name 'hello' in module 'requests''
at: '5,1'
source: 'pylint'
```
Possible to expose another `copy` command to copy just the error itself for quick googling? This is a feature request and probably low priority. Still wanted to document and get feedback. 

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Added a new action to context menu to copy message

![image](https://user-images.githubusercontent.com/10746682/31988190-863c8ab0-b96e-11e7-96a3-dc121ad2d66f.png)
