### ISSUE TITLE
Documentation popup always on...

### ISSUE THREAD

**Issue by okram69** [Microsoft/vscode#31601]
{
  "workbench.activityBar.visible": false,
  "editor.minimap.enabled": true,
  "workbench.iconTheme": "vscode-great-icons",
  "workbench.colorTheme": "Atom One Dark",
  "window.zoomLevel": 0,
  "editor.dragAndDrop": true,
  "editor.wordWrap": "on",
  "editor.parameterHints": false,
  "files.associations": {
    "*.asp": "asp",
    "*.vbs": "asp"
  },
  "editor.occurrencesHighlight": false,
  "editor.multiCursorModifier": "ctrlCmd",
  "emmet.useNewEmmet": true,
  "emmet.includeLanguages": {
      "javascript": "javascriptreact",
      "vue-html": "html",
      "plaintext": "jade",
      "asp": "asp"
  },
  "auto-close-tag.SublimeText3Mode": true
}

Above my user configuration, but the popup hint still appears every time the mouse cursor hover a tag, this is annoying and time consuming. Any way to get rid of this documentation popup?

![suggestionpopup](https://user-images.githubusercontent.com/26657309/28686168-a33aac64-730a-11e7-963f-64bee023cd68.png)

**Comment by ramya-rao-a** [comment]
I am not aware of any way other than pressing ESCAPE once the hover pop shows up.

cc @jrieken to confirm

**Comment by jrieken** [comment]
Not sure, @alexandrudima  or @rebornix should know. The `editor.parameterHints`-setting won't do it as this isn't parameter hints but just the normal hover

**Comment by alexandrudima** [comment]
There is a "hidden" setting `"editor.hover": false` that can be used to permanently disable the editor's hover.
