### ISSUE TITLE
FileSystemWatcher created with just filename does not pick up changes

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#31602]
I'm trying to watch for changes in a file named `.packages` in the root of my workspace; I would've expected one of these to work:

```ts
this.watcher = vs.workspace.createFileSystemWatcher(".packages");
this.watcher = vs.workspace.createFileSystemWatcher("./.packages");
this.watcher = vs.workspace.createFileSystemWatcher("/.packages");
```

However, none of them result in events firing when the `.packages` file is modified. If I do this, it works:

```ts
this.watcher = vs.workspace.createFileSystemWatcher("**/.packages");
```

But obviously this will pick up changes in any folders. Is it intended that the the top options should work?

**Comment by jrieken** [comment]
> But obviously this will pick up changes in any folders. 

No, it only watches files in the current workspace. So, currently roughly within `rootPath` and when we ship multi-root workspaces with those.

**Comment by Tyriar** [comment]
@jrieken I would also expect `vs.workspace.createFileSystemWatcher(".packages");` to work, is this a bug?

**Comment by DanTup** [comment]
> No, it only watches files in the current workspace

Sorry, what I meant was in the whole workspace tree - I was specifically trying to only watch the root workspace folder (or I guess in the case of multi-root project, each root folder).

**Comment by jrieken** [comment]
> @jrieken I would also expect vs.workspace.createFileSystemWatcher(".packages"); to work, is this a bug?

Maybe with the glob-pattern implementation then but generally the provided pattern is matched against the full file path, not the workspace relative file path

**Comment by DanTup** [comment]
I think it's confusing that it only watches things inside the workspace root, yet isn't compared as a relative path. I don't feel strongly though; if that's how it's expected to work I think a clarification in the docs would be fine.

**Comment by bpasero** [comment]
@DanTup you can use the new `RelativePattern` in our APIs to use relative patterns. Did you see that? We introduced that when we added multi-root support.

**Comment by DanTup** [comment]
I haven't seen it - seems to work perfectly, thanks! 👍
