### ISSUE TITLE
Show a message if "typescript.tsdk" points to a bad path

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#31613]
- VSCode Version: Code - Insiders 1.15.0-insider (b67fee36dedecc0b59c14147b8f1a0dad89209b4, 2017-07-26T05:10:18.002Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

1. Add `"typescript.tsdk": "wrong"` to user settings.
2. Open a TypeScript file.

It seems to fall back to VSCode's installed version. I would prefer to see some indication that I'm not using the TypeScript installation I intended to use.

**Comment by SHAHIN-PC** [comment]
ok

**Comment by SHAHIN-PC** [comment]
ok

**Comment by mjbvz** [comment]
Fixed by 8eb1c45
