### ISSUE TITLE
Terminal cannot input any Characters

### ISSUE THREAD

**Issue by cmp2080** [Microsoft/vscode#31616]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.7
vue-snippets|hol|0.1.2
vue|jcb|0.1.5
vue|liu|0.1.5
vetur|oct|0.9.3

---

Steps to Reproduce:

1. "1." instead of "cmd "
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@cmp2080 I'm sorry but the reproduce steps are not clear, can you elaborate?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
