### ISSUE TITLE
Tasks/Terminal: Run Selected Text in Terminal won't launch terminal with background task in progress

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#31611]
Code 1.14.2 and the insiders 7-24
Windows 7

Steps to reproduce:
- Use background or watch task such as build VS Code
- select file with whatever shell commands, select line
- Attempt to use Run Selected Text
- no new terminal or previously open terminal will be used, command is ignored
- It does not matter if the task is currently executing or idle

**Comment by Tyriar** [comment]
Interesting find. I don't think it's worth moving on this as the tasks will eventually be moved to their own panel which will solve this. In the meantime it's kind of as designed as task terminals are regular terminal instances that can receive text just like non task terminals.
