### ISSUE TITLE
call setExceptionBreakpoints only if more than one filter is specified in the corresponding capability

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3161]

**Comment by isidorn** [comment]
@weinand I propose to do this in march so we do not break any adapters that are not yet supporting exceptionBreakpoint capability?

**Comment by weinand** [comment]
@isidorn sure, this was not meant to be for this sprint.

**Comment by isidorn** [comment]
Please note that I no longer manually set 'all', 'uncaught' in case the adapter is not sending exception breakpoints as part of capabalities. 
Due to this all adapters should send a list of exception breakpoints that they support as part of capabilities returned by the initialise call.
[Debug Protocol Capabilites] (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L498)
[Example how node debug does it](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L315)

@daviwil @roblourens @lukehoban @gregg-miskelly @felixfbecker

**Comment by daviwil** [comment]
cc @rkeithhill

**Comment by rkeithhill** [comment]
We support returning Capabilities from the `initialize` request now in the PowerShell extension.  We do not return the `exceptionBreakpointFilters` field.  I believe this should be effectively declaring that we do not support exception filters but we still get the setExceptionBreakpoints request. Sounds like this change, would eliminate those messages.

BTW WRT to the debug protocol, is it better (more efficient) to not return a field at all versus returning `null` or `false`?

**Comment by gregg-miskelly** [comment]
@isidorn I think I know the answer, but just to confirm -- this is for March, correct?

**Comment by felixfbecker** [comment]
This will break all adapters that do not use `configurationDoneRequest` yet but rely on `setExceptionBreakpointsRequest` to run

**Comment by isidorn** [comment]
@rkeithhill yes the UI will be fixed as well, exception breakpoints will not appear if you do not return a field or if you return null

@gregg-miskelly yes, for march, we usually try to set our issues to the correct milestone

@felixfbecker true. Adapters should not rely on this behavior that setExceptionBreakpointsRequest is the last called

**Comment by weinand** [comment]
@isidorn "Adapters should not rely on this behavior that setExceptionBreakpointsRequest is the last called": This is only true after we have improved the spec by introducing the `configurationDoneRequest`.

For backward compatibility we will have to support the old behaviour if `configurationDoneRequest` does not exist or is false.

**Comment by felixfbecker** [comment]
@weinand @isidorn You should still send the exception request if the adapter does not support configurationDoneRequest

**Comment by weinand** [comment]
@isidorn this issue has broken the go-debugger. I've created a PR for them but I still think that we should have provide backward compatibility as was suggested above.
