### ISSUE TITLE
Must tab through deleted tab stops in snippets

### ISSUE THREAD

**Issue by Nais777** [Microsoft/vscode#31619]
- VSCode Version: 1.14.2
- OS Version: OSX 10.12.5

Using the following PHP snippet:

```json
"function …": {
	"prefix": "fun",
	"body": [
		"${1:public }function ${2:FunctionName}(${3:${4:${5:Type} }$${6:var}${7: = ${8:null}}})",
		"{",
		"\t${0:# code...}",
		"}"
	],
	"description": "Function"
},
```
Which generates:
```php
public function FunctionName(Type $var = null)
{
    # code...
}
```
If I don't want any function arguements and I delete the code inbetween `(` and `)` that is generated from the snippet, I have to press tab 6 times after entering tabstop `3` to get to tabstop `0`.

It would be ideal if the snippet controller and session were able to understand that tab stop `3` was deleted so the nested tab stops would then be ignored.

**Comment by jrieken** [comment]
Yes. This month is issue grooming month and that also means we get look at and fix old issues. Such as this one ;-)

**Comment by yangshuairocks** [comment]
Thanks for the hard work :)
