### ISSUE TITLE
VSCode Defaults to PS Integrated Terminal instead of Native PS

### ISSUE THREAD

**Issue by pooptatoship** [Microsoft/vscode#31610]
Hello,

The issue I'm experiencing with VSCode is the only thing preventing me from using it full time.

I want to force VSCode to default to 'powershell.exe' not 'Powershell Integrated Terminal' for various reasons. Better code completion, color formatting, etc. It seems however; no matter what it defaults back to the integrated terminal **_on code execution and on startup._** This is a bare-bones VSCode installation on Windows with just the Powershell extension installed.

Here is my settings file.

```
{
    "terminal.integrated.shell.windows": 
    "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "powershell.integratedConsole.showOnStartup": false,
    "powershell.integratedConsole.focusConsoleOnExecute": false
}
```

VS Code version running default 32 bit as administrator on a Windows x64 10 install.
```
- VSCode Version:
Visual Studio Code
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:34:09.706Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

Windows 10 OS Version
```
- OS Version:
>> [Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0
```

Powershell version from native powershell.exe in Windows 10.
```
-PS Version:
>> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Tyriar** [comment]
This is the PowerShell extension doing this, you can follow this up in https://github.com/PowerShell/vscode-powershell
