### ISSUE TITLE
No coloring for embedded JS in HTML

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3162]
fyi @dbaeumer 

![image](https://cloud.githubusercontent.com/assets/5047891/13174363/7c223132-d703-11e5-8eef-7abaabcad1b1.png)

**Comment by alexandrudima** [comment]
It might be just me refactoring things on my dev machine

**Comment by mike-eason** [comment]
It looks like scripts in HTML documents are not *colourized* because the document is expecting HTML, naturally.

**Comment by Tyriar** [comment]
This seems to be a regression. Works fine for HTML and PHP in stable 0.10.8.

**Comment by Tyriar** [comment]
Cannot reproduce on master.

It's likely either local changes or the Dark/Light (Visual Studio) theme highlighting issues.

**Comment by alexandrudima** [comment]
False alarm, it was a bad edit on my machine
