### ISSUE TITLE
Picking loaded script via quick open doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31626]
Testing #31327

I keep getting `Could not retrieve content.` when picking scripts from my app which are indeed loaded, using the quick open action. It happens with all the scripts.

Possibly duplicate of #31327 ?

![image](https://user-images.githubusercontent.com/22350/28705942-511b493a-7372-11e7-9a36-2424b5ad5e0d.png)

**Comment by joaomoreno** [comment]
Seems to happen on both protocols.

**Comment by weinand** [comment]
I cannot reproduce this with this VS Code:
Version 1.15.0-insider
Commit 0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7
Date 2017-07-28T11:16:26.188Z
