### ISSUE TITLE
Feature request for easier terminals switching

### ISSUE THREAD

**Issue by manuanalakkad** [Microsoft/vscode#31625]
- VSCode Version: 1.14.2
- OS Version: Windows 10

It is very difficult to open the next terminal with the select box. It is very good if we have a next level of tab to open different terminals as shown below. Now i am finding very difficult to switch between terminals.

Steps to Reproduce:

1. Open multiple terminals

**Current screen -** 
![cr](https://user-images.githubusercontent.com/2102862/28705531-deda4f26-738d-11e7-93f5-75d58ac6ab5b.PNG)

--------------------------------------------------------

**Suggestion for some more easily usable multi terminals view**
![easily-usable](https://user-images.githubusercontent.com/2102862/28705568-051af2c6-738e-11e7-84be-881e1b0dc7ca.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/29879 https://github.com/Microsoft/vscode/issues/10546
