### ISSUE TITLE
Using vscode node debugger is not working anymore for Protractor

### ISSUE THREAD

**Issue by scenage** [Microsoft/vscode#31623]
**- VSCode Version:** 1.14.2
**- OS Version:** Windows 10 Pro, 64 bit
**- Node Version:** `v.7.9.0`
**- Protractor Version:** `5.1.2` (Javascript test framework - http://www.protractortest.org/#/)
**Launch.json**
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "cwd": "${workspaceRoot}",
            "program": "C:\\Users\\<username>\\AppData\\Roaming\\npm\\protractor",
            "args": ["${workspaceRoot}\\conf.js"],
            "outFiles": ["${workspaceRoot}/**/*.js"],
            "sourceMaps": true,
            "protocol": "inspector",
            "trace": true
        }
    ]
}

Alternatively, I've tried the following too:

{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}\\node_modules\\.bin\\protractor",
            "args": ["${workspaceRoot}\\conf.js"],
            "outFiles": ["${workspaceRoot}/**/*.js"],
            "sourceMaps": true,
            "protocol": "inspector",
            "trace": true
        }
    ]
}

**- Steps to reproduce the bug**
Setup the launch.json file and run the debugger.

VS code shows the error message: "Cannot launch program 'c:\Repos\leo.tests\node_modules\.bin\protractor'; setting the 'outDir or outFiles' attribute might help."

![image](https://user-images.githubusercontent.com/8476191/28704127-f1a2205c-73ab-11e7-9393-d9b3ecf9c222.png)

In the trace logs, I keep getting the message. I would love to use the vscode debugger as it's handy as was working! It looks like it's looking for a sourcemapURL which isn't available.

[vscode-node-debug2.txt](https://github.com/angular/protractor/files/1182116/vscode-node-debug2.txt)

Below is the message to the client from the log file:
```
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot launch program '{path}'; setting the 'outDir or outFiles' attribute might help.","body":{"error":{"id":2003,"format":"Cannot launch program '{path}'; setting the 'outDir or outFiles' attribute might help.","variables":{"path":"c:\\Repos\\leo.tests\\node_modules\\.bin\\protractor"}}}}
From client: disconnect({"restart":false})
Terminated: Got disconnect request
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

**Comment by roblourens** [comment]
The file in `.bin` at least is a shell script:

![image](https://user-images.githubusercontent.com/323878/29477410-31404af0-841d-11e7-8745-c5aa120c7a1f.png)

You can reference `protractor.cmd` instead as your `runtimeExecutable`, or you can reference the actual .js file under `node_modules/protractor` as your `program`.
