### ISSUE TITLE
Provide shortcuts for actions in dialogs

### ISSUE THREAD

**Issue by sascha-andres** [Microsoft/vscode#31624]
- VSCode Version: 1.14.2
- OS Version: KDE neon 5.10.4

It would be good to have shortcuts in a dialog. This would make it possible to answer questions without moving a hand from keyboard to mouse. For example the **Do you want to save the changes you made to Untitled-1?** forces me to use the mouse. I can cancel with `esc` but what I want is to press `n` for do not save.

**Comment by rebornix** [comment]
If it's native popup, macOS provides shortcuts, not sure if KDE has this feature. For our own popup, it's a good feature request (maybe already filed)

**Comment by bpasero** [comment]
There is something called `normalizeAccessKeys` on https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback that seems to hint at mnemonics support in dialogs (using "_") even on Linux but I have not tried this out myself.

**Comment by bpasero** [comment]
We are setting mnemonics on platforms that support it.
