### ISSUE TITLE
The result of "Format document" is weird of certain HTML content.

### ISSUE THREAD

**Issue by slayerxj** [Microsoft/vscode#31628]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. The origin code is
```
...<p>EDA system <a href="http://www.jedat.co.jp"><i>Alpha-SX</i></a> series</p>
```
2. Execute "Format Document".
3. The result is
```
...<p>EDA system <a href="http://www.jedat.co.jp"><i>Alpha-SX</i></a>                series</p>
```

The setting "editor.wordWrap": "off", which is the default value. But actually most lines are wrapped.
But in this case the line is not wrapped and have a lot of redundant white-spaces.

Here is a minimum file to reproduce this issue.
```
<!DOCTYPE html>
<html>

<head></head>

<body>
    <div>
        <div>
            <p>Reconstruct the schematic editor the EDA system <a href="http://www.jedat.co.jp/eng/products.html"><i>AlphaSX</i></a> series</p>
        </div>
    </div>
</body>

</html>
```

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as underlying formatter.
To repruduce on http://jsbeautifier.org/:
- paste example above to http://jsbeautifier.org/
- set 'Wrap lines near 120 characters'
- format

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1223
