### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by cmp2080** [Microsoft/vscode#31622]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.7
vue-snippets|hol|0.1.2
vue|jcb|0.1.5
vue|liu|0.1.5
vetur|oct|0.9.3

---

Steps to Reproduce:

1.
E:\项目文件夹\17Vue\FastFood>npm -v
'CALL "C:\nodejs\\node.exe" "C:\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
5.0.3

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
It's an issue with your nodejs setup, not a Code issue.
