### ISSUE TITLE
[plugin-dev] question: when plugin cannot find the definition of a symbol for completion, how to do to fallback to editor raw completion ?

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#31636]
- VSCode Version: 1.14.0
- OS Version: windows 7

i have develope a language plugin which provide completion support, the plugin use symbol definitions as completion list, but when the plugin cannot find the definition of a symbol for completion, how can i do to fallback to the editor word completion ?

**Comment by jrieken** [comment]
> how can i do to fallback to the editor word completion ?

The editor does that automatically when no other completions are returns. So, when you plugin fails to look up symbols then just let is return `undefined` or an empty array
