### ISSUE TITLE
Setting tokenColorCustomizations has refresh issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#31632]
Testing #31360 on Ubuntu

Notice in the recording how:

- The tokens don't refresh when I change the `fontStyle`. Only when I change `foreground`.
- The tokens don't appear customised after a reload

![kapture 2017-07-28 at 9 44 41](https://user-images.githubusercontent.com/22350/28707648-7a95c3ce-7379-11e7-90d5-b937e6da6cfc.gif)

**Comment by aeschli** [comment]
duplicate of #29421
