### ISSUE TITLE
VScode did not set BOM into UTF-8 file when you create a new file and save it

### ISSUE THREAD

**Issue by matsukawa-exv** [Microsoft/vscode#31633]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
Ruby|reb|0.12.1

---

Steps to Reproduce:

1.Create a new file and put Unicode string.
ex.
Write-Host "Unicode characters"
2.Save it as PowerShell file
3.Run powershell and type below
PS>type "saved file"

.ps1 file does not have BOM, then Unicode characters will be corrupted

Reproduces without extensions: Yes

**Comment by yfdyh000** [comment]
1. Set `"files.encoding": "utf8bom"` in settings.json
2. Set `"files.autoGuessEncoding": true,` will work?

**Comment by matsukawa-exv** [comment]
It does work.

Thanks,
Takayoshi
