### ISSUE TITLE
Color picker: disable other hovers

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31647]
Refs: #31457

I understand that currently there is some limiation and you can not stop the other hover from showing up, however this is confusing as the other hover seems to be a part of the color picker (in the example below: "color of an element's text")

Like debug, when you are showing the color picker you should disable the regular hover.
Assigning to July for discussion.

![screen shot 2017-07-28 at 11 58 15](https://user-images.githubusercontent.com/1926584/28712603-10e9e186-738c-11e7-82ca-384bd4b42ce8.png)

**Comment by michelkaporin** [comment]
We can disable other hover messages to pop up but I think it is not fair to block other hovers just because we decided to show colour picker. I find it's quite useful to see other message to know what over what the color picker is opened against.

**Comment by isidorn** [comment]
If you decide that the best experience for the user is to see both then we need a more clear seperation.
Currently due to the size of the color picker the small hover feels like it belongs to the color picker

**Comment by michelkaporin** [comment]
That's the idea we stuck to when moved color picker to a hover. That's why I would say we keep it as-designed, but I can add more clear separation. Do you think bigger bottom border would be enough or you have a better idea?

**Comment by isidorn** [comment]
If you can not hide it then maybe leave it as it is.
Let's also ping @joaomoreno and @jrieken to get their inpu

**Comment by michelkaporin** [comment]
I can hide it, no problem, though we discussed not to with @joaomoreno. Lets leave it for a discussion and move to the next milestone.

**Comment by joaomoreno** [comment]
Not going with this for now.
