### ISSUE TITLE
Color picker: initial state of color pointer is bogus

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31642]
Refs: #31457

Trigger color picker on a color, notice the initial state of the color pointer is always in the top left corner which is wrong.
I always get this on my machine, assining to the july milestone as I think this should be fixed before we ship/

![screen shot 2017-07-28 at 11 38 54](https://user-images.githubusercontent.com/1926584/28711883-5a760e7c-7389-11e7-85bf-0d9f7652c0a4.png)

**Comment by michelkaporin** [comment]
Agree, I have to do more changes for this to happen (storing HSV model of the color). Hope I can finish it in time, otherwise we should not show selection by default when we ship.
