### ISSUE TITLE
Color picker do not show focus borders

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31646]
Refs: #31457

When you click on the color picker (which you surely will) we show a blue focus border. This is not needed, as it is there to indicate when the focus swtichtes to some element, hover in this case it is quite obvious that you are woring with the color picker.

We are also disabling focus boxes in the repl input for example.

![screen shot 2017-07-28 at 11 53 20](https://user-images.githubusercontent.com/1926584/28712426-6291097a-738b-11e7-826b-9623f675241a.png)

**Comment by michelkaporin** [comment]
This outline color is coming from hover itself, not colour picker, and I think is is there for accessibility reasons. 

We have the same when clicking on a hover without a colour picker, do you still think we should remove it?

**Comment by isidorn** [comment]
Color picker using the hover is an implementation detail. I believe these two experiences are different.
Also we should be careful with using colors in the color picker and removing this one would give us one less color.
So yes I still think we should remove it for the color picker

**Comment by michelkaporin** [comment]
I see. Apparently that is not as easy as it sounds. We define focus for all elements with tabIndex 0 in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L557 and I am not sure about the logic pipeline to assign tabIndex to the hover. Seems like any editor contribution receives that from the builder class in https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/builder.ts#L849. 

How do you disable it in the REPL?

**Comment by isidorn** [comment]
@michelkaporin there are some synthethic focus tricks, try something like this
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L212
