### ISSUE TITLE
Broken HTML on website (https://code.visualstudio.com/insiders)

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#3164]
See the bottom just above the footer.

![screenshot from 2016-02-19 18-46-39](https://cloud.githubusercontent.com/assets/10473142/13176613/9d32e5b6-d739-11e5-9ed7-0388111f8ac3.png)

**Comment by waderyan** [comment]
Moved to vscode-website repo #109

**Comment by waderyan** [comment]
@hashhar we aren't able to reproduce this. Can you point out the specific page you are seeing this on and what your OS / browser configuration is?

**Comment by waderyan** [comment]
Ah nevermind I found it - http://code.visualstudio.com/insiders
