### ISSUE TITLE
Color picker: Suport actual picker outside of the widget

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#31648]
Refs: #31457

My favorite google chrome color feature is the ability to open the picker click on the pen and just pick any color on the page. That color is immedaitly applied to the picker.
That way I steal colors from all over vscode happily.

I guess it is a bit complex, but opening as a feature request.

![pick](https://user-images.githubusercontent.com/1926584/28712777-ae34fbd8-738c-11e7-817f-44b7b390908f.gif)

**Comment by michelkaporin** [comment]
That's my gift for you @joaomoreno

**Comment by rebornix** [comment]
Marking it as out-of-scope as we are going to work on it in the near term.
