### ISSUE TITLE
EH debugging: use massaged launch for attach

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31659]
As Andre pointed out:

@isidorn in EH debugging, the launchRequest starts the extension host (via VS Code) but the DA does not connect (aka "attach") to it (in normal "node" debugging the DA connects to the launched debuggee automatically).

Instead VS Code knows when the EH is ready and then broadcasts an event that you will pick up and issue the missing "attach" request for it. This is basically the same sequence as the "reload EH window" sequence.

For the "attach" request that you issue in response to the broadcast, you use the initial "launch" configuration and just change the "request" attribute from "launch" to "attach".
Since the initial "launch" config uses the type "extensionHost", the "attach" uses that too.

The fix is to remember the massaged launch config (that got the type "extensionHost2"), and create the "attach" config based on this.

**Comment by isidorn** [comment]
[Code pointer](https://github.com/Microsoft/vscode/blob/isidorn/next/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L159)

@weinand the issue here is that the terminate event sometimes comes before the attach. So in order to get the massaged config I would have to remember all the configs for all the sessions that ever existed. Which I can do, but maybe a nicer alternative would be for me to ask the extension to massage the config again. Thoughts?

fyi @roblourens

**Comment by weinand** [comment]
Most likely this is not an issue anymore since we no longer rewrite the type for EH debugging from `extensionHost` to `extensionHost2`

**Comment by isidorn** [comment]
This is actually fixed via 9eec2b451bdb28084c028fad296b828fed778c52
