### ISSUE TITLE
rxjs/Observable - [ts] Argument of type '"Hello"' is not assignable to parameter of type 'number[]'

### ISSUE THREAD

**Issue by wts20** [Microsoft/vscode#31658]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Create a "data service" file and importing rxjs/Observable
2. Create an observer and using method next of observer
3. Warning and error => [ts] Argument of type '"Hello"' is not assignable to parameter of type 'number[]'

**Comment by rebornix** [comment]
@wts20 it looks like an issue of the code or the library you are using, please file issues there.
