### ISSUE TITLE
switching input method to zhuyin would change default key binding of editor.action.commentLine from cmd+/ to ctrl+alt+cmd+/

### ISSUE THREAD

**Issue by up9cloud** [Microsoft/vscode#31650]
- VSCode Version:v1.13.0
- OS Version:OSX 10.11.6

Steps to Reproduce:

1.switch to Zhuyin input method.
2.~~ctrl + '/' to comment a line~~(typo)
2. cmd+/ to comment a line 

Reproduces without extensions: No

Tried uninstalling all my extentions, same issue.

With `--disable-extensions` mode, I can type `nothing` ~~(the ctrl+/ works) (typo)~~ (the cmd+/ works).
In fact, all my inputs are broken with no extention mode except English input.

my input list
![screen shot 2017-07-28 at 17 32 01](https://user-images.githubusercontent.com/8325632/28711624-c5eb34d0-73ba-11e7-9318-af7dae652c21.png)

**Comment by rebornix** [comment]
The comment shortcut is cmd+/ instead of ctrl+/. Can you verify that?

**Comment by up9cloud** [comment]
Yes. it's my typo...
I'll update it.

**Comment by up9cloud** [comment]
@alexandrudima , @rebornix 

i figure out why...
when i switch to input US, the default key of `editor.action.commentLine` is `cmd+/`
when i switch to input `Zhuyin`, the default key of `editor.action.commentLine` would be `ctrl+alt+cmd+/`

so i solve this issue by set keybindings.json to
```json
[
  {
    "key": "cmd+[Slash]",
    "command": "editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+alt+cmd+[Slash]",
    "command": "-editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  }
]
```
dose it work as expected?

**Comment by alexandrudima** [comment]
@up9cloud The keyboard engine does the following with a default keybinding on OSX. 

Let's consider `cmd + /`:
* it will search for your current keyboard layout all possible keypresses and determine what character gets produced.
* Under the US layout, `[Slash]` produces the `/`. The keybinding will be `cmd+[Slash]`.
* Under the DE layout, `shift + [Digit7]` produces the `/`. The keybinding will be `cmd+shift+[Digit7]`.
* I assume `ctrl + alt + [Slash]` produces the `/` under the `Zhuyin` keyboard layout. This can be verified by opening an editor and running `F1 > Developer: Inspect Key Mappings`. The keybinding will be `ctrl+alt+cmd+[Slash]`.

It is perhaps unfortunate, but it tries to do the best it can given the plethora of keyboard layouts. You can upvote that we ship with keyboard layout optimized default keybindings in #1240

**Comment by up9cloud** [comment]
@alexandrudima 

the keybinding based on keyboard layout might cause issue here, because of

the zhuyin input has 2 mode

- [caps lock] button off: this is zhuyin input with `chinese` mode
  - press `[Slash]` it will produce `ㄥ`
  - press `ctrl + [Slash]` it will produce `／`
  - press `ctrl + alt + [Slash]` it will produce `／`
  - press `alt + [Slash]` it will produce `／`
  - press `shift + [Slash]` it will produce `？`
  - press `ctrl + shift + [Slash]` it will produce `／`
  - press `alt + shift + [Slash]` it will produce `？`
- [caps lock] button on: this is zhuyin input with `english` mode
  - press `[Slash]` it will produce `/`  **<= should work? **
  - press `ctrl + [Slash]` it will produce ``
  - press `ctrl + alt + [Slash]` it will produce `/`
  - press `alt + [Slash]` it will produce `/`
  - press `shift + [Slash]` it will produce `?`
  - press `ctrl + shift + [Slash]` it will produce ``
  - press `alt + shift + [Slash]` it will produce `?`

### the `F1 > Developer: Inspect Key Mappings`

> zhuyin chinese mode

```json
...
	"Slash": {
		"value": "ㄥ",
		"valueIsDeadKey": false,
		"withShift": "?",
		"withShiftIsDeadKey": false,
		"withAltGr": "/",
		"withAltGrIsDeadKey": false,
		"withShiftAltGr": "?",
		"withShiftAltGrIsDeadKey": false
	},
...
```

> zhuyin english mode

```json
...
	"Slash": {
		"value": "ㄥ",
		"valueIsDeadKey": false,
		"withShift": "?",
		"withShiftIsDeadKey": false,
		"withAltGr": "/",
		"withAltGrIsDeadKey": false,
		"withShiftAltGr": "?",
		"withShiftAltGrIsDeadKey": false
	},
...
```
