### ISSUE TITLE
Color Picker: Pressing RETURN should accept the current value and dismiss the picker

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#31651]
I can dismiss the picker when pressing ESCAPE I would have expected that I can also accept the current value by pressing ENTER/RETRUN.

**Comment by michelkaporin** [comment]
Shouldn't it instead apply the selected color when pressing return?

**Comment by egamma** [comment]
yes this is what I meant, I've tweaked my original description.

**Comment by ghiscoding** [comment]
@egamma correct me if I'm wrong but I think the title of the issue is still wrong and is not reflecting your updated description of the problem. Thanks

**Comment by egamma** [comment]
@ghiscoding I've updated the title, thanks for catching.

**Comment by alexdima** [comment]
This issue is very old, probably from a time when the color picker did not insert the selected color on mouse up. As it is today, the color is inserted as soon as mouse up occurs, so there is no need to press Enter to accept the new color.
