### ISSUE TITLE
I often end up scrolling instead of color-picking...

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#31653]
testing #31457

See attached screen shot. By stirring around in the colours I must somehow to something* that dismisses the picker and starts scrolling towards...

![jul-28-2017 12-06-13](https://user-images.githubusercontent.com/1794099/28712936-616e3ea8-738d-11e7-9264-e3f8aa759b07.gif)

* I believe mouse up is the trigger to this

**Comment by jrieken** [comment]
Probably related; I have managed to move the viewport while still having the color picker open. 

<img width="481" alt="screen shot 2017-07-28 at 12 10 18" src="https://user-images.githubusercontent.com/1794099/28713043-cfd987d0-738d-11e7-88cd-d18cf81981bf.png">

**Comment by michelkaporin** [comment]
Seems like same issue as in https://github.com/Microsoft/vscode/issues/31686#issuecomment-318756538, that was fixed already.
