### ISSUE TITLE
Multi cursor does not scroll view

### ISSUE THREAD

**Issue by mcarpenterjr** [microsoft/vscode#31669]
- VSCode Version: 1.14.2
- OS Version: Linux Mint 18.2

Steps to Reproduce:

1.  Open a file containing enough lines to scroll
2.  Add some cursors.
3.  move cursors out of the top or bottom of the view.

Reproduces without extensions: ??

IMHO I would expect the original cursor to track in the view.

**Comment by dorellang** [comment]
This also fails when scrolling horizontally. Please fix this. It's very annoying to reach the mouse to do multiline changes in lines that don't fit in the view.

**Comment by sleighsoft** [comment]
This is annoying. The only solution is to use word wrap which also kinda breaks the usability of multiline cursors.

**Comment by mcarpenterjr** [comment]
That's even worse! If you're adding cursors above or below you could inadvertently add a cursor into a wrapped line.

This isn't a feature request either it's a bug, the cursor is the tool for navigating the document if the cursor moves off-screen the editor scrolls the cursor back into view, if there are enough cursors to fit in the viewport of the document they should always all be in view, that's the gist of the issue here.

**Comment by borysl** [comment]
Really annoying. The workaround is to press Alt-Z to wrap lines of code

**Comment by sleighsoft** [comment]
Or have a mouse that can tilt the scroll wheel to move left right ...

**Comment by alexandrudima** [comment]
Alternatively, you can hold Shift + mouse wheel to scroll horizontally.

**Comment by alexdima** [comment]
Let's track in #6995
