### ISSUE TITLE
Color Picker: Explore peek UI

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#31660]
testing #31457

As discussion over lunch, Suggesting to explore showing the color picker in a peek view as it allows for a more stable UI, which which unlock features like showing all colours of the document, host a pipette tool etc.

**Comment by michelkaporin** [comment]
@joaomoreno this can be as a part of further development of colour picker. From #28587 people would like to see such features as color pallete, ability to select any color from the editor, etc. Currently it is small on the hover, however going forward with more features eventually we can move it to the peek UI. 

Also as a next step we can make a setting where and what to show in the color picker. Current code is quite flexible to show it on the hover or in the peek UI.
