### ISSUE TITLE
Go to implementation should support loading indicators

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode#31666]
I suggest that `ImplementationProvider` should support asynchronous loading indication in the same way as `ReferenceProvider`.

My understanding based on [other conversation](https://github.com/Microsoft/vscode-go/pull/1100#issuecomment-318285633) is that the current assumption with `ImplementationProviders` is that they will return almost immediately.

In popular languages which actually enable the static analysis to drive implementation finding (e.g. Java, Go), I think it's reasonable to expect the analysis to take more than a few seconds (see https://github.com/Microsoft/vscode-go/pull/1100), and the current API behavior means users are in the dark about what's happening while the analysis is processing.

**Comment by ramya-rao-a** [comment]
cc @mjbvz

**Comment by ramya-rao-a** [comment]
The progress indicator should be available in tomorrow's Insiders
