### ISSUE TITLE
Theme: Allow scrollbar different border color

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#31668]
- VSCode Version: 1.15.0 (insiders)

Steps to Reproduce:

1. Open a long file
2. Click inside the editor
3. When you click inside the editor the scrollbar have an hardcoded border color

<img width="105" alt="screen shot 2017-07-28 at 16 09 46" src="https://user-images.githubusercontent.com/10454741/28721029-31c3d6fa-73af-11e7-8b34-2d16fae081cb.png">

**Comment by alexandrudima** [comment]
```
    "workbench.colorCustomizations": {
        "editorOverviewRuler.border": "#ff0000"
    }
```

or

```
"editor.overviewRulerBorder": false
```

**Comment by equinusocio** [comment]
@alexandrudima thank you.
