### ISSUE TITLE
Feature request: vscode extensions in json file

### ISSUE THREAD

**Issue by thibaultsavary** [Microsoft/vscode#31662]
# Feature request
## Feature
It would be nice to have a JSON file with all installed extensions and their versions, like package.json for node modules.

## Example
`extensions.json`
```json
 {
  "akamud.vscode-theme-onedark": "2.0.3",
  "ms-vscode.js-atom-grammar": "0.1.13",
  "...": "...",
}
```

## Use case
For those of us who switches often  between devices it would be easier to manage extensions.

**Comment by yfdyh000** [comment]
#28652, #2743.
