### ISSUE TITLE
Add more progress UI locations, e.g editor and sidebar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#31664]
- VSCode Version: Code - Insiders 1.15.0-insider (0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7, 2017-07-28T11:23:06.089Z)
- OS Version: Windows_NT x64 10.0.16251

Currently `withProgress` supports 2 locations: `SourceControl` which shows a nice "progress bar" on the source control activity, and `Window` which shows a spinner and message in the statusbar (imo this should be called `StatusBar`). I would love to have 1 or 2 additional locations -- something like `SideBar` where it would show the "progress bar" on any activity currently active in the the side bar, and/or `Editor` (would call it `Window` but that is used) where it would show the similar "progress bar" but instead of in the side bar, it would be on the active editor.

As an aside, I also found it confusing that when using `SourceControl` no progress message or anything needs to be set, but to use `Window` you must set at least 1 progress message otherwise no indicator shows.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
> on any activity currently active in the the side bar

Unsure, as progress should be shown "in context" and I wonder what operation is worth showing in any viewlet, e.g. extension viewlet, debug, and explorer. 

Still, request is valid as the API was design for future progress locations, like editor, app icon etc

**Comment by eamodio** [comment]
Honestly I didn't realize at first (before looking at the progress API) that the viewlet progress indicator was viewlet specific, I thought that the top of the sidebar was *the* location for progress (not dependent on the active activity). 

The ship has already sailed, but here is what I would have liked to see ;)

`withProgress` with the following locations:
- `SourceControl` - same as today
- `Editor` - shows the same style progress indicator as `SourceControl` but at the top of the active editor (for active editor specific actions -- e.g. GitLens blame calculation, VersionLens dependency calcs, etc)
- `StatusBar` (optional) - shows the same style progress indicator as `SourceControl` but at the bottom of the status bar -- useful for full editor progress
- etc as needed/desired

`withStatus` (or `withProgressStatus` or something like that) which would take the options for the current `withProgress` `Window` location. So that the options for messages and how the API works is clearer imo.

That way all the "progress" indicators (without any extra information just "working" indicator bars) are grouped together with similar options. And `withStatus` can have a separate api since it requires a message and has different options.

**Above all** I would love to see the `Editor` location above. IMO the status bar progress is too disconnected from the editor to effectively provide editor progress.

**Comment by orta** [comment]
To plus 1 on this with respect to status bars, perhaps being able to attach a progress indicator to a `vscode.StatusBarItem`?

Right now in both vscode-jest and code-flow we have a background process using [elegant-spinnter](https://github.com/sindresorhus/elegant-spinner) which blocks the clicking action on the item and feels like overkill.

**Comment by hanfengcan** [comment]
who can offer a example
