### ISSUE TITLE
Whitespaces should be more readable

### ISSUE THREAD

**Issue by lechuckcaptain** [Microsoft/vscode#31670]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file adding some text with multiple lines
2. Ctrl-Shift-P: Enter Toggle Render Whitespace
3. Some whitespaces are correctly shown (\t and \s), some are not visible at all (\r and \n). 

See screenshot ov VSCode with High Contrast Theme:

![image](https://user-images.githubusercontent.com/341895/28721745-b342d31e-73b1-11e7-8de1-1e02bf73ccd2.png)

See screenshot of Notepad++ (my personal favourite):

![image](https://user-images.githubusercontent.com/341895/28721830-e72d20f8-73b1-11e7-85bb-fbed45defb18.png)

See screenshot of Atom:

 ![image](https://user-images.githubusercontent.com/341895/28722055-a98e7d40-73b2-11e7-965b-e9aa06caa017.png)

Reproduces without extensions: No

**Comment by yfdyh000** [comment]
1. set "editor.renderWhitespace" in settings.json

**Comment by lechuckcaptain** [comment]
That's exactly what it does the second step to reproduce: 

> Ctrl-Shift-P: Enter Toggle Render Whitespace

But I'm quite unhappy about the result that you can see from attached the screenshots
