### ISSUE TITLE
Feature request: Search references (Ctrl + Shift + O) in embeeded editor (Peek definition) (Alt+ F12)

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#31672]
A feature very cool is possibility search references in editor embeeded file. I saw this necessity when I needed search one method using the embeeded file resource.
Today this resource works only with the file opened.
Thanks!!! :)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
