### ISSUE TITLE
Drop support for variable substition for program and runtime in package.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#31675]
Stop supporting variable substitution (e.g. `${workspaceRoot}`) inside the `package.json` `runtime` and `program` fields.
We have never marketed this feature and now it is providing some debt when introducing multi root workspaces (as the package.json can not specify against which root to resolve the variables against)

**Comment by weinand** [comment]
Please see "Variable substitution in package.json will no longer be supported" in the [upcoming July release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_15.md#debug-contributions).

Namedrops:
@DanTup @DonJayamanne @MSLaguana @WebFreak001 @andysterland @daviwil @delmyers @devoncarew @felixfbecker @gregg-miskelly @hbenl @lukaszunity @ramya-rao-a @rebornix @rkeithhill @roblourens @svaarala @vadimcn

**Comment by WebFreak001** [comment]
Did you mean the debug launch.json or the actual extension package.json? If it's the launch.json, is `"cwd": "${workspaceRoot}"` still supported? There isn't really a solution to change the cwd to if you want to commit the debug file to a project if that variable gets removed from cwd.

**Comment by weinand** [comment]
@WebFreak001 as the titles says, I only mean variable substitution in the "package.json" of a debugger extension.

**Comment by DonJayamanne** [comment]
Phew. 
Thanks for the clarification @weinand . Almost started panicking here.

**Comment by DanTup** [comment]
@weinand I'm slightly confused by what's being dropped. I do have some instances of `${workspaceRoot}` in my `packages.json` however I believe that all of them are just written into the `launch.json` literally, so no substitution is done.

Two of them (`configurationAttributes/launch/properties/program/default` [here](https://github.com/Dart-Code/Dart-Code/blob/af6632ebd0007f47743b52e4efdd33d1cbb5fd1a/package.json#L427) and `initialConfigurations/program` [here](https://github.com/Dart-Code/Dart-Code/blob/af6632ebd0007f47743b52e4efdd33d1cbb5fd1a/package.json#L444)) appear as the string `${workspaceRoot}` and the other (`configurationSnippets/bodyprogram` [here](https://github.com/Dart-Code/Dart-Code/blob/af6632ebd0007f47743b52e4efdd33d1cbb5fd1a/package.json#L455)) is written as `"^\"\\${workspaceRoot}/bin/main.dart\""`.

Would I be right in assuming that none of this would be affected, but after the change maybe the last one would not need the escaping?

Thanks!

**Comment by weinand** [comment]
@DanTup yes, variable substitution in the package.json does not affect your contributions (and you can verify this easily because the generated launch.json should contain the `${workspaceRoot}` variable literally).
The escaping for the snippets is needed because of the snippet syntax, not to prevent the variable substitution.

**Comment by DanTup** [comment]
@weinand Gotcha! Thanks!
