### ISSUE TITLE
Holding down a key in the terminal only sends a single key on Mac

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31676]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/265
Related: https://github.com/Microsoft/vscode/issues/10398

Repro steps:

1. Focus terminal and hold the <kbd>a</kbd> key, only a single character is added to the prompt

**Comment by lamielle** [comment]
Note that #10398 was for arrow key repeats.  That works fine, along with backspace. However, repeating other keys, like 'a' (or hjkl for vi usage) does not trigger repeats.  It appears that once the referenced xterm.js issue is resolved and VSCode updates to the version with that fix, then this issue can be closed.

**Comment by Tyriar** [comment]
Right now we're acting the same as the editor which is fine. If this makes it into https://github.com/xtermjs/xterm.js/issues/265 we might be able to add a configurable option in vscode.
