### ISSUE TITLE
Emmet conflicts with Intellisense while editing HTML

### ISSUE THREAD

**Issue by davidmogar** [Microsoft/vscode#31671]
I'm new to VS Code and as a Emmet user I'm finding problems using it with this editor. The most annoying part for me is that seems to be a conflict between Emmet and Intellisense. I'm giving an example bellow.

Steps to Reproduce:
1. Create an html file.
2. Write `!` and press tab to generate an html skeleton.
3. On the body section, type `p` and press tab.

The expected behavior would be to generate a `p` element. Instead, the editor (intellisense) show `DOCTYPE` as an autocomplete option and when I press tab, `DOCTYPE` is written in the file.

The same problem occurs if disabling extensions, and for other html files, other options are suggested. In a bigger html file inside a subdirectory, options like `pack` are shown.

**Comment by jens1o** [comment]
just for clarification: 
In your user settings, is `"emmet.useNewEmmet"` turned on?

I can't reproduce it(it's enabled at my end), when clicking somewhere after insert `!`:
I get this, when pressing tab or enter with `!`:
![image](https://user-images.githubusercontent.com/11234139/28733657-73ba9b92-73dd-11e7-90b9-66f270e92fab.png)


Then click inside the body tag:
I get this:
![image](https://user-images.githubusercontent.com/11234139/28733673-807d1be8-73dd-11e7-9667-275132cfc431.png)

After accepting that suggestion, I get:
![image](https://user-images.githubusercontent.com/11234139/28733687-8fd3e798-73dd-11e7-8e32-21520dfc18e2.png)


which is what you want, isn't it?

**Comment by davidmogar** [comment]
Thanks for your reply. Changing `"emmet.useNewEmmet"` to `true` totally fixes the problem. Is this supposed to be true by default?

Any way, I'm closing the issue now. Thanks for your help.

**Comment by jens1o** [comment]
Well, as of the next release, it will be set as default and it is recommend to activate it. :)

**Comment by ramya-rao-a** [comment]
Thanks @jens1o for stepping in

@davidmogar Everything @jens1o is absolutely right. I am working on enabling this by default for the next update.

There is only one blocking bug for this to happen: https://github.com/Microsoft/vscode/issues/27784

I am waiting on @sergeche to merge my PR to fix it https://github.com/emmetio/output-renderer/pull/1 :)

@sergeche Help!
