### ISSUE TITLE
Show all results count in the find widget (even if not highlighted)

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#31673]
Hi,
Currently it shows the 999 occurrences and highlights them.
But i need to get all the occurrences like in Notepad++ count in Find Dialog.

Selection should tell the count of all the occurrences and can highlight of first 999 and can highlight more when scrolled down.
But All Occurrences Count is very important.

![image](https://user-images.githubusercontent.com/8774556/28724017-1fb243e8-73d2-11e7-9353-23f6fe2d7951.png)

**Comment by hamxabaig** [comment]
Its [this file](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L266) , right ?
Do we need to change the current behaviour or we can add a config for this ? Let me know happy to provide PR for this one.

**Comment by holodoc** [comment]
This is a biggie for me. I often use search to count occurrences in files and not being able to do it for larger files completely defeats the purpose of using VSCode for that.

**Comment by hamxabaig** [comment]
@rebornix May you check my comment if thats correct. I can work on this one then

**Comment by ToMakeSense** [comment]
totally agree on you!!!
[#11973](https://github.com/Microsoft/vscode/issues/11973)
[#11973](https://github.com/Microsoft/vscode/issues/19208)

**Comment by alexandrudima** [comment]
The only update is that the visual decorations are now drawn on the first 20.000 results. All operations in the find widget work correctly for the entire set, it is just the visual highlights that are painted only for the first 20.000.
