### ISSUE TITLE
Scope toggleFind* keyboard shortcuts to a new context

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#31683]
- VSCode Version: Code - Insiders 1.15.0-insider (0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7, 2017-07-28T11:23:06.089Z)
- OS Version: Windows_NT x64 10.0.16251
---

Originally reported here https://github.com/eamodio/vscode-gitlens/issues/113

Could `ctrl+d` (select next occurrence) start a context/scope so that the keyboard shortcuts below could be registered in vscode with a `when` on that new context?

For example:
```json
{ "key": "alt+c",                 "command": "toggleFindCaseSensitive",
                                     "when": "editorFocus && inFindNext" },
{ "key": "alt+l",                 "command": "toggleFindInSelection",
                                     "when": "editorFocus && inFindNext" },
{ "key": "alt+r",                 "command": "toggleFindRegex",
                                     "when": "editorFocus && inFindNext" },
{ "key": "alt+w",                 "command": "toggleFindWholeWord",
                                     "when": "editorFocus && inFindNext" },
```

Is that reasonable and feasible?

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
