### ISSUE TITLE
Copy one file from a VS Code window(project) to another one

### ISSUE THREAD

**Issue by sepehrr** [Microsoft/vscode#31682]
Right now in left side explorer if you right click on a file and copy it, you can easily paste it in that explorer in another place, which is a very good thing.
but you cannot copy and paste it to explorer which is opened for another project in another VS Code window.

**Comment by nimat-netlinks** [comment]
any update ?

**Comment by cretz** [comment]
For others seeing this issue from Google, I believe this is a duplicate of #27837. Unsure why it was marked as a duplicate without saying what it was a duplicate of.
