### ISSUE TITLE
How to sort snippets manually?

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#31680]
- VSCode Version: 1.14.2
- OS Version: win7x64

![image](https://user-images.githubusercontent.com/24613274/28733427-c54af356-73e4-11e7-8d27-694e5f600712.png)

Can someone tell me, how can I organize in my order these snippets?

I created one, called "fi", but its on the second place, I want it to be on the first place, so I don't need to move cursor and press mouse button etc...

If the prefix of the snippet would be just letter "f" - it would be in the middle of nowhere.

So, how can I sort it manually?

Thanks!

**Comment by jens1o** [comment]
You may want to edit the  `editor.snippetSuggestions` setting, it controls that thing and has these options:
![image](https://user-images.githubusercontent.com/11234139/28734723-9265f960-73e2-11e7-9f67-269e89b3e481.png)

**Comment by user3323** [comment]
@jens1o  thanks a lot! I edited it to "top" and that's what I was looking for!
