### ISSUE TITLE
Consider renaming the "window" classification of settings to "workbench"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#31688]
The 1.15 release notes mention the new classification of settings into "window" specific and "resource" specific. "Window" is a much used term in VS Code docs and usually applies to a specific VS Code instance (New Window, Switch Window, Reload Window). I think a better term for these types of settings would be "workbench" specific and we use the "workbench." scope on many settings that apply to the overall VS Code UI.

I'm not sure if the "window" setting classification is surfaced in the UI or if the distinction is just for documentation descriptions and perhaps the internal implementation.

**Comment by gregvanl** [comment]
It is exposed to extension authors as the `scope` value when they add configurations.

**Comment by egamma** [comment]
@gregvanl we have intentionally switched from `workbench` to `window`. The `scope` configuration attribute is used by extension authors and in the extension API the corresponding term is `window`. We do not talk about workbench in the API (there are 2 references in comments that we should change).
