### ISSUE TITLE
webview search results highlights too bright

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#31689]
- VSCode Version: 1.15 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1.Bring up release notes (Help > Release Notes)
2.Ctrl+F to open the new search and type "bugs"

The first selection is bright orange and the second is yellow. They look very bright on Dark+ theme.

We should use the same search selection colors as the editor and be theme aware.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Requires electron fix upstream:

https://github.com/electron/electron/issues/10010

**Comment by mjbvz** [comment]
Electron closed this as wont fix upstream
