### ISSUE TITLE
Latest releases not on GitHub

### ISSUE THREAD

**Issue by nchammas** [Microsoft/vscode#3168]
Not sure if this is intentional or not, but we're currently at [release 0.10.9](https://code.visualstudio.com/updates#vscode). However, the [releases page](https://github.com/Microsoft/vscode/releases) here on GitHub only shows up to 0.10.6.

**Comment by Tyriar** [comment]
This may be a manual step currently, we may be able to automate with the [GitHub API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

**Comment by egamma** [comment]
Yes it is a manual step, since a relase on github only provides a zip of the source files it is not really valuable and we should either remove the releases or make them useful.

**Comment by nchammas** [comment]
Right. You can attach arbitrary files to each release on GitHub, but since y'all already have a means of distributing binaries and the like, perhaps you don't need this feature of GitHub.

**Comment by joaomoreno** [comment]
@egamma should we simply not use this github feature?

**Comment by egamma** [comment]
:+1:  I've deleted the existing releases

**Comment by nchammas** [comment]
0.10.9 still isn't tagged via git. I imagine that's something we still need to do? Since tagging versions is separate from uploading release artifacts.

**Comment by joaomoreno** [comment]
Tagged.

**Comment by nchammas** [comment]
:+1:
