### ISSUE TITLE
TypeScript formatter -- insertSpaceBeforeFunctionParenthesis -- fails when generic arguments are present

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#31692]
- VSCode Version: 1.14.2
- OS Version: Windows 10

```ts
function sample1<A, B, C> (a: A, b?: B, c?: C) {
}

function sample2 (a: any, b?: any, c?: any) {
}
```

When typing a completion character (the closing curly braces in the above example), the autoformatter removes the space before the function parentheses in `sample1` but not in `sample2`, with the former leading to linting complaints in my code.

My settings:

```json
{
  "typescript.format.insertSpaceBeforeFunctionParenthesis": true,
  "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true
}
```

Generic arguments affect both of the above settings.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17531
