### ISSUE TITLE
How do I clear up what appears to be a corrupted environment?

### ISSUE THREAD

**Issue by yaronyg** [Microsoft/vscode#31693]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Enterprise - 1703 - 15063.483

Steps to Reproduce:

1. Open apparently corrupted folder
2. See that ctrl+space leads to eternal "loading" and that alt-p -> run tasks -> will just sit loading possible tasks forever

Reproduces without extensions: Yes

The way I worked around this problem is that I copied my entire folder into a new location and then opened the new location and VS Code works like a champ.

And yes, I really did repo this with --disable-extensions. Even with --disable-extensions submitted the 'corrupt' location won't work and the new one will in terms of things like intellisense.

What appears to be happening is that during our tests we create a directory test/testRoot and in there are actual Node projects which contain node_modules which contain a reference to the project we are developing. Now, not being completely stupid, I early on added testRoot as an entry to tesconfig.json/exclude. But somehow VS Code is still "seeing" testRoot and especially when I use npm link (which presumably creates a loop from the project entry in node_modules in testRoot back to the production project) things break. What I have done is added include to our tsconfig.json and specify our src and test directory and I have hoisted testRoot out of the test directory and made it its own directory (it has, btw, always been in .gitignore). So far that seems to have fixed the issue.

So the bug seems to be that even though the testRoot directory was in tsconfig.json/exclude, in some way VS Code appears to be 'seeing' it, even if possibly just enumerating directory contents and that causes it to fail somehow. But why was it looking in that directory at all when it was on the exclude list?

**Comment by yaronyg** [comment]
BTW this is getting worse and worse. I used to only have to change the directory's name once every day or two. Now I have to do it every few hours before things get corrupted. Help!

**Comment by yaronyg** [comment]
So it seems like the problem related to npm link. For example, when I npm link project foo and then I go create a brand new project bar which has no relationship to foo, tsc stops working. But if I unlike project foo then tsc starts working on both foo and bar.

**Comment by yaronyg** [comment]
So I checked now (the problem re-occurred) and I had the link and TSC was still running. Most likely because I excluded a troublesome folder that contained some tests results. But auto-complete still wasn't working. I removed the link but that didn't actually fix anything. So I think the tsc problem was a red herring. Nevertheless I'm back to F12 not working. To auto-complete not working. It's really frustrating.

**Comment by yaronyg** [comment]
I was able to work for many hours today without 'npm link'ing the project before the environment went bad and I had to change the folder name and reopen it. But as soon as I did a 'npm link' of the project boom, everything stopped.

So while 'npm link' makes the problem worse, it does not appear to be the root cause of the problem.

**Comment by yaronyg** [comment]
So I seemed to have narrowed the problem down. What appears to be happening is that during our tests we create a directory test/testRoot and in there are actual Node projects which contain node_modules which contain a reference to the project we are developing. Now, not being completely stupid, I early on added testRoot as an entry to tesconfig.json/exclude. But somehow VS Code is still "seeing" testRoot and especially when I use npm link (which presumably creates a loop from the project entry in node_modules in testRoot back to the production project) things break. What I have done is added include to specify our src and test directory and I have hoisted testRoot out of the test directory and made it its own directory (it has, btw, always been in .gitignore). So far that seems to have fixed the issue.

So the question is - why was VSCode looking in an excluded directory at all?

**Comment by mjbvz** [comment]
Hey sorry I lost track of this issue.

Please let me know if you are still running into this problem with VS Code 1.18. If so, it's also possible that you just need to add more explicit `includes` or `excludes` in your `jsconfig`. Something like:

```json
{
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
