### ISSUE TITLE
F5 debugger for Python does not pick up the fact it's Python3!

### ISSUE THREAD

**Issue by programmin1** [Microsoft/vscode#31698]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9

---

Steps to Reproduce:

1. Run this simple script ("./test.py") and it will fail, showing that it correctly is trying python3:
```
#! /usr/bin/env python3
print( "hello" )
import urllib2
print( "success")

```
2. Press F5 and note it is not stopping, not actually debugging in python3 despite the first line pointing to python3!

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1130

**Comment by duxbuse** [comment]
This is still an issue. Why is it closed?
