### ISSUE TITLE
Formatting problem with VSCode and JS

### ISSUE THREAD

**Issue by giorgim** [Microsoft/vscode#31703]
`this.create` and `this.data` are not on the same distance from the left border of the screen as you can see.
This is how VS Code arranged them after using format feature.
Why?

![screenshot_1](https://user-images.githubusercontent.com/26545183/28743510-b168e9e2-745c-11e7-9e25-740c843b1c01.png)

**Comment by mjbvz** [comment]
This is because you have ended the line `this.data = [],` with a comma. We indent all lines after a comma by design
