### ISSUE TITLE
Test Salsa as the default JS infrastructure

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3170]
Only the opening of the release notes in the browser needs to be tested across platforms
- [x] Win @alexandrudima  
- [x] OS X @chrisdias 
- [x] Linux @aeschli  *I confess... I didn't get to test the opening of the browser on Linux*

Salsa is now the default JS infrastructure. 

- you get an info message that Salsa is now the default when you open a .js file for the first time. The message provides you with the option to read the change notes/migration guide. Verify that this message is only shown once (the state is stored in (`storage://global/vscode.javascript-migration`).
- follow migrating to Salsa guide to setup your JavaScript project to enable warnings etc.
- use an Ember project setup to test Salsa. The old JavaScript service excluded several directories by default (e.g. tmp) which Salsa doesn't do. Verify the experience and in particular that Code doesn't crash.

```
npm install -g ember-cli
npm install -g bower
npm install -g ember-cli-windows
 
ember-cli-windows    (you may need to ‘Set-ExecutionPolicy Unrestricted -scope CurrentUser’ for this to execute)
npm install
bower install
ember serve
 
Then browse at localhost:4200 to run server.
```

**Comment by aeschli** [comment]
Tested that the browser opens as expected.
Wasn't able to get a good Ember experience. Completions, hovers never seem to complete. I excluded `tmp` and `node_modules` but not sure if that really worked due to lack of feedback and status.

**Comment by egamma** [comment]
>Wasn't able to get a good Ember experience. Completions, hovers never seem to complete.

@aeschli can you confirm that you did not crash with or without excluding `node_modules` and `tmp`. I think we never had a good intellisense experience even when we tried to use the ember.d.ts.

**Comment by aeschli** [comment]
@egamma  I finally figured out how to exclude 'tmp' and 'node_modules' correctly (no leading '/' and restart). Completions now show.
Before all I got was 'Loading'. No visible crash, but also no useful behavior.

**Comment by egamma** [comment]
@aeschli thanks, can you include your jsconfig.json you used for ember, I'm working on the change notes. I will not forget to mention the restart.

**Comment by aeschli** [comment]
```json
{
    "exclude": [
        "tmp", "node_modules" 
    ],
    
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}
```

**Comment by chrisdias** [comment]
Ember looks ok, i was able to get some IntelliSense with ember.d.ts, no crashes.

**Comment by alexandrudima** [comment]
I didn't try the Ember scenario, but given Martin and Chris tried it, I think its ok :)

**Comment by egamma** [comment]
>Ember looks ok, i was able to get some IntelliSense with ember.d.ts, no crashes.

This is good news Salsa fixed the limitation we have with the 'default export'.

@chrisdias you should mention this to MS teams that build ember apps :smile:
