### ISSUE TITLE
CSS Property Autocomplete shows invalid values?

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode#31700]
- VSCode Version: 1.14.2
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Set syntax to CSS
2. Try applying `display` property in a rule
3. It shows `border` and `gradient` as values for display but that's wrong.

![image](https://user-images.githubusercontent.com/313363/28743279-ef639b3c-7463-11e7-9283-ad370ce3a154.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
border and gradient are snippets, as you can see from the image.
Snippets are unfortunately not context-aware.

If you never use snippets I suggest using the setting `"editor.snippetSuggestions"` to configure if and where they are shown
