### ISSUE TITLE
Problem in Starting AutoRest-Manager

### ISSUE THREAD

**Issue by Swapnil2095** [Microsoft/vscode#31708]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---
Starting AutoRest-Manager.
[Error - 7:32:51 PM] Error Starting Autorest-Manager : Cannot find module 'C:\Users\Dell\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core'
[Error - 7:39:03 PM] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@Swapnil2095 sorry I don't think it's related to VSCode. Please file issues against the package or extension you are using.
