### ISSUE TITLE
[css] Lower precedence for property values with browser prefix

### ISSUE THREAD

**Issue by praveenpuglia** [microsoft/vscode#31702]
Currently, VSCode CSS Autocomplete lists browser prefixed values for CSS properties but I think it should just list the standard properties. 

## Why?

1. No new properties are going to be created with prefixes.
2. It seems like a real good extension usecase. More like a snippet.
3. Most people needing prefixes would actually use autoprefixer or similar tools in build chain to get that part automated.

## Benefits?
- Reduces the maintenance on the language-server side.
- Encourages use of standard properties and using a tool to get prefixes when needed.
- Reduces the amount of options shown in the intellisense list so it's easier to navigate and provides better UX.

## Example
Here the list shows `-ms-` and `-webkit-` prefixed version of values even before the standard value comes in.
![image](https://user-images.githubusercontent.com/313363/28743309-9b724da6-7464-11e7-8b54-699c3ac8ed56.png)

**Comment by aeschli** [comment]
I'm not in favor of removing them. Maybe it would be good to sort them at the end.

**Comment by octref** [comment]
Seems already fixed:

![image](https://user-images.githubusercontent.com/4033249/67228557-5a0bce80-f3ee-11e9-8da5-f1e956b8f9c5.png)
