### ISSUE TITLE
Hyper terminal (external) using BASH shell opens to user home, rather than VSCode's working directory

### ISSUE THREAD

**Issue by TheFirstDeity** [Microsoft/vscode#31704]
**Summary**

When using [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) (bash) as the shell for [Hyper](https://hyper.is/) terminal, `ctrl+shift+c` defaults to the user's home instead of the current folder. (Presumably because it wants a path starting with `/mnt/c/...`)

Hyper+bash opens correctly from Windows explorer if you right click and select "Open Hyper here", and bash.exe (by itself) opens correctly from VSCode as external terminal. The problem only occurs when Hyper+bash is set as the external terminal (see steps to reproduce.)

--- 

**System Info**
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063

- Extensions: 
Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.7
githistory|don|0.2.2
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-yarn|gam|1.2.0
Angular2|joh|2.4.0
vscode-scss|mrm|0.6.2
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.0.11
json-template|sto|0.3.1

---

**Steps to Reproduce**:

1. Install [Hyper](https://hyper.is/) and configure `.hyper.js` for use with bash
```
config: {
  ...
  shell: 'C:\\Windows\\System32\\bash.exe',
  shellArgs: [],
  ...
}
```
2. Open vscode, edit User Settings
3. Set your Hyper.exe as external terminal (replace <username> for your own install dir)
```
"terminal.external.windowsExec": "C:\\Users\\<username>\\AppData\\Local\\hyper\\Hyper.exe",
```
4. Launch external terminal (default `ctrl+shift+c`)
5. Note the directory is set to user's home instead of the one open in vscode

Try again with bash alone, and it opens to the correct directory:
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe",
```

--- 

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I created https://github.com/zeit/hyper/issues/1213 upstream a while ago so Hyper works like other terminal emulators.
