### ISSUE TITLE
Bug in auto indent of <style> tag in html-css emmet.

### ISSUE THREAD

**Issue by hoon0422** [Microsoft/vscode#31709]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Make html file and type 
```
<!DOCTYPE html>
<html lang="en">
<head>
    
</head>
<body>
    
</body>
</html>
```

2. Type "style" between <head> tag and press Tab key. It will produce <style></style> and the position of cursor will be in the middle of the open tag and the close tag.
3. Press Enter key.

The result should be, ( "||" symbol means current cursor position)

```
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        ||
    </style>
</head>
<body>
    
</body>
</html>
```

However, the result is
```
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        ||</style>
</head>
<body>
    
</body>
</html>
```

And when I press Enter key again, the result is
```
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        
||</style>
</head>
<body>
    
</body>
</html>
```

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Right now the behavior of entering after `<style>` tag is 

![31709](https://user-images.githubusercontent.com/876920/45836244-21686580-bcc1-11e8-817c-e6bb744ebf69.gif)

We don't indent after `<style>` tag as we think it's the multile language boundary.

**Comment by rebornix** [comment]
let's track this issue in https://github.com/Microsoft/vscode/issues/46426 which has more conversations. Your feedback is really helpful, thanks!
