### ISSUE TITLE
Directories with "special chars" like "dot" in name won't open as a project-folder

### ISSUE THREAD

**Issue by telekommander** [Microsoft/vscode#31707]
... but handled as a file while open from contextmenu.

First steps to reproduce:
1. Mark directory in Win-Explorer like this `D:\Projects\4.2_0`
2. Select from contextmenu "Open in VSCode"
3. VSCode handeled as a file

Second steps to reproduce:

1. Open Menu , go to "Open Folder ... "
2. Select a directory like this `D:\Projects\4.2_0`
3. Error Message: _Path not exist_

Reproduces without extensions: Yes

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16232

**Comment by bpasero** [comment]
@telekommander a complete uninstall and reinstall should help!
