### ISSUE TITLE
Multiple prompts to exclude large folders

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#31711]
- VSCode Version: Code - Insiders 1.15.0-insider (0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7, 2017-07-28T11:23:06.089Z)
- OS Version: Windows_NT x64 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
coldfusion|ili|0.0.10
wordcount|ms-|0.1.0

I just opened a large(ish) project and I got a prompt from VSC to configure excludes to enable project-wide JS/TS features. So I clicked "Configure Excludes", on the file that popped up I simply saved it and carried on. 

Then I got the prompt again.
And again. 3 times now. 

And I'm pretty sure jsconfig.json already existed.

Ok, I can confirm that if I switch to another project and then come back, the warnings come back too. So there's something about this project that is tripping up VSC. If it helps, this is the project:

https://github.com/cfjedimaster/Serverless-Examples

and this is the existing jsconfig.json

{
    "compilerOptions":{
        "target": "es6"
    },
    "exclude": [
        "node_modules"
    ]
}

---

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by nealoke** [comment]
I also get this prompt (not in insiders build though, regular build (x64), latest version. I don't want any exclusions and this warning keeps showing up during coding sessions. 

![warning](https://user-images.githubusercontent.com/17417414/29268990-8cdd5f78-80ef-11e7-9d87-a4cb920f8be4.PNG)

**Comment by cfjedimaster** [comment]
Just to be clear though- the issue isn't the prompt per se, but it coming up multiple times in the same project.

**Comment by nealoke** [comment]
@cfjedimaster yep this is also the case for me :) 1 time per project is more then enough

**Comment by jake-daniels** [comment]
Same here. But it happens randomly. Sometimes I open some file - the prompt is shown, sometimes not. I wasn't able to determine any pattern.

**Comment by Fasani** [comment]
I have a lot of JS in my project, I have all my excludes set up, this message should pop once or I should be able to disable it altogether.

**Comment by mjbvz** [comment]
A few things to try: 

In your `jsconfig.json`, try excluding all `node_modules` files by writing:

```
"exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
```

If that does not fix things,  try looking through the TypeScript server logs to make sure all the files being included in your project make sense:

1. In VS Code, set `"typescript.tsserver.trace": "verbose"`
2. Restart VS Code and reproduce the issue
3. Run the `Open TS Server log` command in VS Code
4. In the `tsserver.log` file, look near the bottom of the logs for long lists of file paths tha tlook like:

```
Info 32   [17:32:45.151] Project '/Users/matb/projects/san/tsconfig.json' (Configured) 0
Info 32   [17:32:45.151] 	Files (30)
	/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/lib.es6.d.ts
	/Users/matb/projects/san/b.ts
        ....
```

Do a quick scan to make sure all the files listed here make sense. If not, try excluding those files in your `jsconfig.json`

---

If none of this works and your project really does just have a lot of JS code, you are likely running into https://github.com/Microsoft/TypeScript/issues/19326 . We are investigating ways to improve this.

Closing as upstream
