### ISSUE TITLE
Scrollbar slider on minimap isn't active after click on the track place

### ISSUE THREAD

**Issue by totalamd** [Microsoft/vscode#31718]
Scrollbar slider on minimap doesn't become dragged by the click on the free track place like it does on simple slider [with disabled minimap].

- VSCode Version: 1.14.2
- OS Version: Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:

1. Open any document large enough to have free track place on the scrollbar
2. Enable minimap
3. Mousedown on the free track space of the scrollbar
4. Try to drag mouse (not releasing the button from the previous item)\
Result: slider should be dragged on simple scrollbar, but it isn't. It's not dragged until you release the mouse and grab it again. On the normal scrollbar slider becomes dragged during the first click on free track space.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Clicking on the minimap does not necessarily mean the minimap slider will move to where the click happened. I try to explain this by-design limitation in #21708.
