### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#31715]
- VSCode Version: Code - Insiders 1.15.0-insider (81e812c06540d1bd2636cf70ff7d0edd1bb0e866, 2017-07-21T13:15:10.775Z)
- OS Version: Windows_NT x64 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-mocha|Com|0.1.1
vscode-mocha-test-runner|cst|0.2.1
angular2-snippets|dan|1.0.15
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
xml|Dot|1.9.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.9.4
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.1.1
cpptools|ms-|0.12.1
debugger-for-chrome|msj|3.1.6
vuejs-extension-pack|mub|0.1.7
vetur|oct|0.9.3
vuehelper|oys|0.1.0
babelrc|wad|1.0.0
gitblame|wad|2.0.2
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. 打开 code insider.
2. 查看 => 集成终端

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@Aladdin-ADD  are you constantly getting this error message when you open the terminal?

**Comment by Aladdin-ADD** [comment]
no. I restarted the app, the error message was gone.

**Comment by rebornix** [comment]
Close it first and reopen when you run into it again, thanks:)
