### ISSUE TITLE
Unable to set bitmap font

### ISSUE THREAD

**Issue by warptozero** [Microsoft/vscode#31710]
VSCode Version: 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

OS Version: Fedora 26: 4.11.9-300.fc26.x86_64

Steps to Reproduce:

1. Set a bitmap font in settings: `"editor.fontFamily": "'xos4 Terminus', monospace",`
2. Save file and notice font doesn't change (even after restart).

Note that `monospace` is also aliased to `xos4 Terminus` by fontconfig and other applications such as chromium and xfce4-terminal correctly pick it up:
```
$ fc-match "xos4 Terminus"
ter-112n.pcf.gz: "xos4 Terminus" "Regular"
$ fc-match monospace
ter-112n.pcf.gz: "xos4 Terminus" "Regular"
```

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@warptozero we rely on Chromium to handle font loading and rendering. If you can use it in Chrome you should be able to use it in VS Code.

**Comment by warptozero** [comment]
Thanks for the answer. I just checked chrome and chromium again and it doesn't seem to work. So either chromium stopped supporting bitmap fonts in the last year or I am mistaken that it had previously worked.
