### ISSUE TITLE
Sync configs

### ISSUE THREAD

**Issue by and3rsonsousa** [Microsoft/vscode#31714]
I love vscode, but everytime I have to install it on a new computer I always have to download all extensions and make the same config. I would love to have an account to login into vscode and have all my extensions and config synced around with all my devices, just like Google Chrome.

**Comment by cleidigh** [comment]
@and3rsonsousa 
There is a great extension by https://github.com/shanalikhan
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
This will do exactly as you express via gist/github
