### ISSUE TITLE
TAB not working

### ISSUE THREAD

**Issue by jpfrontbr** [Microsoft/vscode#31713]
- VSCode Version: Code - Insiders 1.15.0-insider
- OS Version: WINDOWS 10 x64

Steps to Reproduce:

Open an HTML file or create and save a new one
Type any tag, for example div
Hit "tab" -- it should display <div></div>
Same thing with Emmet shortcuts, and in SCSS files as well.

Nothing happens. This used to work, I believe it worked in yesterday's Insider build.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@jpfrontbr In the Insiders for 1.15,we have set `emmet.useNewEmmet` to `true`
Meaning the new emmet model is in effect where tab is no longer bound to the emmet expand abbreviation command.

Read https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list and https://code.visualstudio.com/updates/v1_14#_emmet-abbreviation-improvements to know more on this.
