### ISSUE TITLE
Feature request: Add option to reload extension

### ISSUE THREAD

**Issue by hrastnik** [Microsoft/vscode#31712]
feature-request:
I think it would be nice to have the option to reload extensions. Currently I do it by disabling and re-enabling the extension, which is not practical and requires two window reloads (one after disabling and one after enabling the extension).

The reason why I did this in the first place is because of a bug in the extension itself that made the extension stop working and the only option was to reload the extension.

**Comment by joaomoreno** [comment]
A simple window reload will reload the extension.
