### ISSUE TITLE
[debt] Actions should be allowed to be created with no service dependency

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3171]
Currently it is not possible to create an action that has no service dependency, so we have to create a fake service dependecy to `NullService`.

Could this be solved by removing our old injection way. I think this is something we should tackle in a debt week.

**Comment by aeschli** [comment]
We can remove the NullService once we have removed all references to platformservice.
For that I removed the old constructor APIs and migrated the remaining code (just the tests were remaining, in fact)
I left in a console log to warn if there are still usages of the old style. That would have to be code written in JavaScript or using anys.
I'll remove the old code and the NullService beginning next release

**Comment by isidorn** [comment]
:+1:
