### ISSUE TITLE
Cannot type full command in integrated terminal

### ISSUE THREAD

**Issue by napoleonit76** [Microsoft/vscode#31727]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.8.0-56-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
vscode-eclipse-keybindings|alp|0.9.6
vscode-database|baj|1.2.0
vscode-npm-script|eg2|0.2.0
rest-client|hum|0.15.0

---
I have a super weird issue with the integrated terminal in VS Code v1.14.1 on Ubuntu 16.04.
Whenever I try to type any command (like clear, ls, htop...) the whole command is not fully visible on the terminal until I press Enter or Space. Instead of that, it keeps showing every single character of the command.
For example:
Expected: `c` --> `cl` --> `cle` --> `clea` --> `clear`
Actual: `c` then `l` then `e` and so on...
How can it be??

Steps to Reproduce:

1. Open VSCode, then open the integrated Terminal
2. Type any command (`clear`, `ls`)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Some questions:

- What's your $SHELL set to?
- Can you share your settings?
- Do you have any shell plugins installed?
