### ISSUE TITLE
There is no shortcut for toggling the menu bar

### ISSUE THREAD

**Issue by Josh68** [Microsoft/vscode#3172]
I inadvertently hid the menu bar and then spent 30 minutes trying to figure out how to get it back, only to find there is no shortcut (that I can find) to permanently toggle it. So you have to use the ALT key to toggle it back on temporarily (found that in online help) and then use the menu itself to toggle it back on permanently. Unless I'm missing something. Editing the boolean in a config file (storage.json) also does not change the setting permanently. Thanks.

**Comment by egamma** [comment]
You can invoke all the commands from the Command Palette.

You are not the first one that reports this issue I suggest to show an info message  to the user hides with information for how to bring back the menu bar. The info message would only be shown on first use or it could disappear after some time.

**Comment by Josh68** [comment]
Thanks. I didn't even know how to access the Command Palette, but now I've found it. I'd still suggest adding a default shortcut for toggling the menu bar, or some other affordance. But I added a keybinding (File -> Preferences -> Keyboard Shortcuts) to my custom set, and all's good.
