### ISSUE TITLE
I get new instance of VS Code every time with new code signature

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#31723]
- VSCode Version: 1.14.1
- OS Version: 10.11.6

Steps to Reproduce:

1. Quit VS Code
2. Open it again

Reproduces without extensions:  Yes

It seems that VS Code always launches as completely new instance, requiring a new code signature. Not sure what to do to fix this but this is very annoying. :(

**Comment by nikitavoloboev** [comment]
There are two apps in the Dock too : 

![2017-07-31 at 12 27](https://user-images.githubusercontent.com/6391776/28773923-bcd19bb8-75eb-11e7-8008-0a718125cdcd.png)

**Comment by joaomoreno** [comment]
What OS? What makes you say it has a _new code signature_?
