### ISSUE TITLE
Allow to open a diff editor from command line where one side does not exist

### ISSUE THREAD

**Issue by DominikJaniec** [microsoft/vscode#31726]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.2
haskell-linter|hoo|0.0.6
Ionide-fsharp|Ion|2.28.0
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.3.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
elm|sbr|0.14.1
code-spell-checker|str|1.3.2
haskero|Van|1.3.1
vim|vsc|0.9.0
markdown-pdf|yza|0.1.7

Reproduces without extensions: Yes (via disable them all, before)

---

I have Git (_2.13.3.windows.1_), configured as:
```
[diff]
  tool = vs_code
[difftool]
  prompt = false
[difftool "vs_code"]
  cmd = code --wait --diff \"$LOCAL\" \"$REMOTE\"
```

I have a sample repository which contains: one new, one removed and one edited file. All those files are added to the index.

Steps to Reproduce:
1. In an external console, just type: `$ git difftool --cached`
2. An existing and modified files will display in two column diff - as expected.
3. Added file will display as just opened file - nothing indicates it is a diff's window.
4. Removed file displays also like opened file, but with strange name suffix (from Git?) - also hard to spot as diff.

![diff-new deleted](https://user-images.githubusercontent.com/3832797/28753568-74b3807c-7536-11e7-9249-b50693419209.png)

I would expect that new or removed files will be display with empty left or right column respectively. New file has not any previous version, so left side of diff is empty. Deleted file has not any future version, so current version (right side of diff) should be empty.

Also I do not understand why we have to run VS Code with a `--wait` flag for diff, and block Git until VS Code window was closed. Without the flag: `--wait`, Git could open multiple VS Code's tabs (with a flag: `--reuse-window`), so I could start difftool and then go for a coffee and then just see all changes without wait for open every instance of VS Code. But `--diff` without `--wait` does not work at all: modified files are displayed in separated tabs without the _diff view_ and new or deleted files behave as described in this issue.

**Comment by joaomoreno** [comment]
@bpasero If one of the diff files is empty, is should appear as empty in the workbench.
