### ISSUE TITLE
Autocomplete hangs with "Loading..." on Go 

### ISSUE THREAD

**Issue by ijt** [Microsoft/vscode#31721]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
terminal|for|0.0.10
vscode-rust|kal|0.4.2
Go|luk|0.6.63
live-server-preview|neg|0.0.4

---

Steps to Reproduce:

1. Install go1.8.3. I'm not sure if this matters.
2. Update the Go tools within Visual Studio Code.
3. Open a Go file.
4. Try for example adding import "encoding/csv" and then typing csv.<ctrl+space> somewhere. A grey, horizontal bar comes up saying "Loading..." but no autocompletion menu comes up.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@ijt Can you run `gocode close` in a terminal and restart VS Code and try again?

If that still doesnt work can you try running gocode from the command line and see if that works? This is to identifiy if the problem is with gocode or the Go extension

**Comment by ijt** [comment]
@ramya-rao-a, that worked. I ran `gocode close` in a terminal and restarted VS Code and now completion is working again.

**Comment by ramya-rao-a** [comment]
Glad to hear that, Happy Coding!
