### ISSUE TITLE
Not able to run test for .net core in vs code

### ISSUE THREAD

**Issue by d-saravanan** [Microsoft/vscode#31725]
I have the source code for aspnet security github repo.

Installed new version of VS Code
Tried to build > Succeeded
When running test case, getting the following errror

Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0'.

Total tests: 0. Passed: 0. Failed: 0. Skipped: 0

- VSCode Version: 1.14.2
- OS Version:Windows 10

Steps to Reproduce:

1. git clone https://github.com/aspnet/Security.git
2. run the following in vs code > Terminal
2.1 dotnet build
2.2 dotnet test

Reproduces without extensions: Not sure, I have only installed Omnisharp for C#

**Comment by d-saravanan** [comment]
Also, while debugging, why does this always try to use the internet to build?

C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\NuGet.targets(102,5): error : Failed to retrieve information about 'Internal.AspNetCore.Sdk' from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-ci-dev/nuget/v3/flatcontainer/internal.aspnetcore.sdk/index.json'. [g:\DS\Security\test\Microsoft.AspNetCore.Authentication.Test\Microsoft.AspNetCore.Authentication.Test.csproj]
C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\NuGet.targets(102,5): error :   An error occurred while sending the request. [g:\DS\Security\test\Microsoft.AspNetCore.Authentication.Test\Microsoft.AspNetCore.Authentication.Test.csproj]
C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\NuGet.targets(102,5): error :   The server name or address could not be resolved [g:\DS\Security\test\Microsoft.AspNetCore.Authentication.Test\Microsoft.AspNetCore.Authentication.Test.csproj]

**Comment by rebornix** [comment]
@d-saravanan we don't have .NET Core in VSCode natively so if you are using a C# related extension, please file issues there.
