### ISSUE TITLE
User Snippets Stop Working in OSX

### ISSUE THREAD

**Issue by kevmon** [Microsoft/vscode#31724]
After creating user snippets in both CSS and JavaScript, they were working fine for a while, but intellisense has stopped detecting them.  After I restart my computer (restarting the app doesn't help) it will work again for a while, then stop again.

- VSCode Version: 1.13.1 (1.13.1)
- OS Version: Apple OS 10.12.6

Steps to Reproduce:

Not exactly sure how to reproduce, but when I create user snippets, they were working at first (have installed on two machines) then intellisense stopped recognizing them.  

Reproduces without extensions: Yes, disabling extensions makes no difference for me

**Comment by jrieken** [comment]
Sorry, nothing I can do with that information. Do snippets show when going via F1 > Insert Snippets?

**Comment by kevmon** [comment]
Hi jrieken,

Thanks for getting back.  Right now it seems to be working (it's unpredictable when it happens), but if it happens again, I'll try to get more helpful information your way.  

Cheers
