### ISSUE TITLE
VS CODE app

### ISSUE THREAD

**Issue by GazGuitar** [Microsoft/vscode#31730]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.11.0

using System;

namespace console2
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

---

Steps to Reproduce:

1. run console app (having built with errors)
2.The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.

version 1.14.2 of VS Code.

Wondering if this as a result of having several versions of VS Community editions already installed on this machine (2013, 2015, 2017).
Wanted to test VS Code to see if I could use lighter weight app at work.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@GazGuitar we don't have builtin support for .NET Core, if you are using any C# related extension, you may want to file issues there, thanks.
