### ISSUE TITLE
C# parameter hints does not dismiss after newline

### ISSUE THREAD

**Issue by jeffschwMSFT** [Microsoft/vscode#3173]
![csharp intellisense](https://cloud.githubusercontent.com/assets/9561583/13184238/852514b6-d6ef-11e5-9a05-8dd241d8d41b.gif)

To dismiss an intellisense suggestion, you should be able to hit <esc> (that works) or complete the line (;<newline>).  On OS X Yosemite the suggestion does not dismiss once I hit return and will stay there as I type a new line of code.

**Comment by egamma** [comment]
@joaomoreno this could be the code assist/paremeter hints widget and the be an issue independent of C#.

**Comment by joaomoreno** [comment]
A hunch tells me it is a C# language service issue, which keeps informing Code that there is a method call, even after leaving the parens. Might be wrong though.

**Comment by scrudgey** [comment]
I came here to say this. Very annoying bug, I keep having to hit "esc" after I go to a new line.

**Comment by joaomoreno** [comment]
Ultimately this is an extension's issue: OmniSharp/omnisharp-vscode#64.

But I've modified the code on our side to be more resilient to errors happening during the parameter hints call.
