### ISSUE TITLE
Ruby syntax highlighter fails when parameter defaults contain a nested Hash

### ISSUE THREAD

**Issue by nelseric** [Microsoft/vscode#31738]
- VSCode Version: 1.14.2
- OS Version: Mac OS X 10.11.6 

Steps to Reproduce:

1. Create a new ruby file with the contents
```ruby
def complicated_params(options = {
  column_mapping: {
    'account_number' => 'acct_no',
    'mailing_address' => 'mail_addr_line_1',
    'customer_name' => ['customer_name', 'company_name'],
  },
})

  pp options
end
```
![image](https://user-images.githubusercontent.com/133228/28758362-43641038-755c-11e7-941b-289a045ca230.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/ruby.tmbundle#113
