### ISSUE TITLE
Terminal broken

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#31739]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
Go|luk|0.6.63
vscode-icons|rob|7.12.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open the go project
2. ctrl + ` to open Terminal, it seems broken like this
![terminal](https://user-images.githubusercontent.com/10704251/28759832-44ccd680-75d4-11e7-9fbe-78f32bed5f8e.png)

3. disable the Go plugin, the problem still exists. but if open with other folder, not the go project, the terminal works fine.

**Comment by Tyriar** [comment]
@CAIJUNYI you likely have the shell setting pointing at a sysnative path, can you try changing sysnative to system32?

**Comment by CAIJUNYI** [comment]
Thx, the problem was solved. I found the sysnative path in the Go project workspace settings which i have neglected.
