### ISSUE TITLE
Not able to connect mssql using Visual Studio Code 2017

### ISSUE THREAD

**Issue by Swapnil2095** [Microsoft/vscode#31734]
- VSCode Version: 2017
- OS Version: Windows 10- Home

I am not able to login my SQLEXPRESS database server using VC2017.
I am using windows credentials for authentication purpose.
So in that case, what will be my username and password, please explain this with example or step by step.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@Swapnil2095 sorry I don't think this has anything to do with VSCode. If the functionality is provided by an extension, please file issues there.
