### ISSUE TITLE
 integrated terminal not working cannot type anything in it

### ISSUE THREAD

**Issue by swapu258** [Microsoft/vscode#31746]
- VSCode Version: Code 1.14.2 [(cb82febafda0c8c199b9201ad274e25d9a76874e,]() 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.6.9
vscode-npm-script|eg2|0.2.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
phpcs|ika|0.7.0
phpcsfixer|mak|0.0.1
laravel-blade|one|1.8.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Can you share some more information? Screenshot and your settings file would be a good start, thanks 😃

**Comment by silasjmatson** [comment]
I've run into this issue several times. If memory serves, it usually happened with long-running processes such as an open ssh connection or a repl.

I ran into it most often when running [guard](https://github.com/guard/guard), which itself was managing a redis process, sidekiq process, puma webserver, and a test runner process. I usually discovered the issue when I'd hit <kbd>Enter</kbd> and nothing happened.

If I run into the issue again, I'll post further information here.

**Comment by jgemmaEIS** [comment]
I have the same issue

version 1.15.1

**Comment by rgogulakrishnan** [comment]
Im also facing the same issue. Able to open terminal using ctrl+`. But unable to type anything. Its stuck. Other than that im able to use everything.

Version: 1.17.2 zip version for windows.

**Comment by Tyriar** [comment]
Let's track this in https://github.com/Microsoft/vscode/issues/37044
