### ISSUE TITLE
在style 标签中 点个 . 或者是 。或者是 打个 空格就会卡死

### ISSUE THREAD

**Issue by RoronoaLu** [Microsoft/vscode#31743]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
vscode-colorize|kam|0.6.2
easy-less|mrc|1.4.5
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.1.6
material-icon-theme|PKi|2.0.11
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
MDTools|sea|1.0.1
stylelint|shi|0.28.0
open-in-browser|tec|1.0.0
JavaScriptSnippets|xab|1.4.1
vscode-preview-server|yui|0.7.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@RoronoaLu can you provide more detailed reproduce steps ?

**Comment by varHarrie** [comment]
会不会是`stylelint`的问题，我遇到过在less文件中输入`.`，报错

**Comment by yuhj86** [comment]
@rebornix Try this snippet in php language mode.
```
<style>

</style>
//[1]我在这里随便打点中文字符我在这里随便打点中文字符我在这里随便打点中文字符

```

**Comment by CnSimonChan** [comment]
I can reproduce this issue in 1.15

Steps:

1. Create a new file.
2. Set file mode to php.
3. Paste the above snippet into the file.
4. Type `.` between the `style` tag.

What happened:

Code becomes unresponsive, a process of Code consumes all CPU time of one core. 

@RoronoaLu I recommend you to change the issue title to English for better understanding to the developers. 最好把标题换成英文的这样开发者能比较容易理解。

**Comment by rebornix** [comment]
I tried above steps but can't reproduce, it looks like it's an extension issue, you can verify by running vscode without extensions `code --disable-extensions`.
