### ISSUE TITLE
hotExit setting not respected

### ISSUE THREAD

**Issue by ChaseGrant** [Microsoft/vscode#31749]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
beautify|Hoo|1.1.1
mssql|ms-|1.1.0
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. Set the preference files.hotExit to off
2. Load up a file that's saved
3. Close the app
4. Re-open the app
5. No prompt on closing or opening and the file is automatically re-opened despite the preference being set

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This is as designed, hot exit is about retaining *unsaved* changes between sessions. `"window.restoreWindows": "none"` might be what you're after?

**Comment by ChaseGrant** [comment]
You are correct. I could have sworn it worked in a previous release.
Thank you.
