### ISSUE TITLE
In the Zen mode,the screen will flicker when i input Chinese characters

### ISSUE THREAD

**Issue by Michael-Zhang-Xian-Sen** [Microsoft/vscode#31741]
- VSCode Version: Code - Insiders 1.15.0-insider (ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95, 2017-07-26T07:40:44.551Z)
- OS Version: Linux x64 4.8.0-59-generic
- Extensions: none
---

Steps to Reproduce:

1.Switch to Zen mode.
2.Input some Chinese characters at "Chinese input method".
3.Hit space in your keyboard,the Chinese characters put to vsc's edit area,at the same time the screen may flicker.(the screen won't flicker when I input English )

**Comment by rebornix** [comment]
@Michael-Zhang-Xian-Sen what do you mean by screen flicker? Are you referring the IME suggestion window?

**Comment by Michael-Zhang-Xian-Sen** [comment]
No,the screen is my pc screen,not my IME suggestion window.
There are some interesting things i found.
1. I test it in my windows 10 os,all is well.
2. When I power-off my pc and open visual-studio code,enter to Zen mode,input some Chinese characters ,my pc screen won't flicker.But after doing some another thing for a while,I use Zen mode and input some Chinese characters again,my computer screen will flicker.
3. I wanted use software to record a video about my problem ,and i did.But my problem won't show out at my video.It's very interesting.
4. Finally,I use my mobile phone to recording a video,it's show my problem.I have sent it to your mailbox.
3q :-)

**Comment by isidorn** [comment]
@Michael-Zhang-Xian-Sen thanks. Can you
1. Reproduce this issue if vscode goes into full screen mode and not zen mode
2. Can you reproduce this problem in Chrome if you go into full screen chrome?

**Comment by Michael-Zhang-Xian-Sen** [comment]
All is well in vscode's full screen and Chrome's full screen.Nothing special happend when I input Chinese character.

**Comment by Michael-Zhang-Xian-Sen** [comment]
Oops, my vscode's full screen flicked just now when I input Chinese characters....

**Comment by isidorn** [comment]
Please try more in Chrome full screen.
Also try in vscode with no full screen

**Comment by Michael-Zhang-Xian-Sen** [comment]
I have two pc screens.
One shows chrome in full screen,another shows vscode with no full screen..
Something interesting showed again..
When I right-click in vscode,my screen which showing chrome in full screen will flicker.
It seems that it's my os's problem..
Sry to bother..

**Comment by isidorn** [comment]
No problem. It might aslo be a chrome issue.
If you think it is a chrome issue please file it against the chromium repository
