### ISSUE TITLE
Can't navigate by call stack in same file if exception thrown when attached to chrome

### ISSUE THREAD

**Issue by zxxc** [Microsoft/vscode#31748]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated

[vscode_bug.zip](https://github.com/Microsoft/vscode/files/1186656/vscode_bug.zip)

)|Version
---|---|---
project-manager|ale|0.18.1
gitignore|cod|0.5.0
git-extension-pack|don|0.1.2
githistory|don|0.2.2
gitlens|eam|4.3.3
vscode-npm-script|eg2|0.2.0
sublime-babel-vscode|jos|0.2.6
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.6
react-redux-es6-snippets|tim|2.1.0
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Open vscode
2. attach to chrome
3. catch unhandled exception 
4. try to navigate in call stack in same file where exception thrown
video is attached(open in chrome)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/29097
