### ISSUE TITLE
Code reports errors in removed source files

### ISSUE THREAD

**Issue by jeffschwMSFT** [Microsoft/vscode#3174]
![removedfiles](https://cloud.githubusercontent.com/assets/9561583/13184519/42ae62d4-d6f1-11e5-8b4b-0668f44d7e4a.gif)

On my OS X Yosemite machine running Code, I was adding/removing code in a solution.  One of the files I removed had a C# build error.  The interesting thing was the the error persisted in my Code session even after deleting the file (control - click - delete).  The error only went away once I closed the folder and reopened.

**Comment by egamma** [comment]
Not clear whether this is Omnisharp or the Code marker infrastructure. The fact that the error count drops to 0 indicates that the marker is properly removed when the file is deleted.

**Comment by dbaeumer** [comment]
Since the error counts drops to zero I suspect this being a problem in OmniSharp land

**Comment by jrieken** [comment]
Omnisharp doesn't really support delete...

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#87
