### ISSUE TITLE
c++ preview-define  will blocking the folding

### ISSUE THREAD

**Issue by lianzisong** [Microsoft/vscode#31740]
- VSCode Version: 1.14.2
- OS Version: win 10

Steps to Reproduce:

1.open the vs code.
2.write a simple test code like below.
![code](https://user-images.githubusercontent.com/16344340/28760515-61bde3b4-75da-11e7-98ee-bd90b26e4f33.png)

and after I folding the code after the #endif , it shows :
![code2](https://user-images.githubusercontent.com/16344340/28760552-9f351384-75da-11e7-8eb9-4c96d8a6dff0.png)

in fact I want to folding the tyr{}, but it lead a incorrect result.
I hope the content is clearly enough.
thanks . 

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
The problem is that our current folding strategy is indentation based. To support what you want we need to add language awareness to the folding regions. That's #30963.
