### ISSUE TITLE
Code folding options disappears after init

### ISSUE THREAD

**Issue by lalena205** [Microsoft/vscode#31756]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
dakara-foldplus|dak|1.1.0
githistory|don|0.2.2
Angular2|joh|2.4.0
gitblame|wad|2.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Launch vs code
2. After initialization is done (when proper folding is shown for code for around 1 second), lines disappear and i cannot enable folding again

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Can you attach a screenshot?

**Comment by aeschli** [comment]
Can you check the status bar if it says 'screenreader detected'?
I just learned that this would remove folding.

**Comment by lalena205** [comment]
Yes, it was the active Screenreader, i discovered it after reporting this.
Everything's back in place now, thank you !

**Comment by aeschli** [comment]
Assigning to @alexandrudima to follow up here.
