### ISSUE TITLE
Error: Cannot find module 'vscode' when use vscode in server

### ISSUE THREAD

**Issue by hechaochao** [Microsoft/vscode#31755]
- VSCode Version:1.14.2
- OS Version:win10 X64

Steps to Reproduce:

1.clone the official example for language server from https://github.com/Microsoft/vscode-languageserver-node-example
2.then follow these steps:
> cd client
> npm install
> code .
> cd ../server
> npm install
append "post install": "node ./node_modules/vscode/bin/install" to scripts in package.json
> npm install vscode -save
> code .
3. open server.ts which located in server/src folder, then add a line import * as vscode from 'vscode' at the beginning  of server.ts.
4. press ctrl+shift+B to build task.
5. after build finished press f5 under client folder
6. error message is shown below:
Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please file issues against the sample repo you are working on, thanks.
