### ISSUE TITLE
"No definition found" despite balloon showing correct signature (C++)

### ISSUE THREAD

**Issue by burtondanj** [Microsoft/vscode#31757]
- VSCode Version: Code - Insiders 1.15.0-insider (9dd41b52a2487bd5595f7ac234fb1f251b902c12, 2017-07-28T05:17:00.444Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1

(2 theme extensions excluded)

---

C++: Hovering over a function at a call site results in a balloon with the correct signature (+2 overloads), but all 4 of go to / peek definition/declaration say "no definition found". Function is a class static. in a named namespace in a different translation unit to where it's being called

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please file issue against the C++ extension you are using.
