### ISSUE TITLE
Taskbar icon's white borders

### ISSUE THREAD

**Issue by Eduardogbg** [Microsoft/vscode#3175]
After January update, VS Code's icons smaller than 128x128 have its borders pixelated, probably because when its size goes down, the borders start losing smoothness and become very sharp, leaving a visually unpleasant effect.

**Comment by bgashler1** [comment]
@Eduardogbg can you show me a screenshot of what you're seeing.  Also what operating system are you on?

**Comment by bgashler1** [comment]
We're addressing this in the upcoming release.  Thanks for the feedback!
