### ISSUE TITLE
Feature request: Export/Import settings just like Jetbrains IDE

### ISSUE THREAD

**Issue by rashidul0405** [Microsoft/vscode#31750]
Export all the settings including themes, plugins etc. And while import settings, vscode automatically download all required themes and plugins etc.

**Comment by jens1o** [comment]
There's something called [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) which provides that functionality you want.

**Comment by Levelleor** [comment]
@jens1o I had a lot of problems using it. It says some code is "dirty" somewhy and that data on this PC is newer than data I wan't to download. I mean no sh** it's newer, but I need to replace it with that anyway! I need the working export/import thing that works with dropbox and stuff too and works just simply fine, without dumb errors from nowhere and useless features.

**Comment by rashidul0405** [comment]
Forgot to post any feedback, me too face difficulties in synchronization. 

My proposal is something very straightforward like Jetbrains IDE. Export all settings as a file (put it on Dropbox folder), import that file from another machine.

**Comment by shanalikhan** [comment]
You guys should post the issues [here](https://github.com/shanalikhan/code-settings-sync/issues)
Check this also, https://github.com/shanalikhan/code-settings-sync/issues/256 : Extension will have that feature in futures updates.

**Comment by rashidul0405** [comment]
@shanalikhan Thank you very much. looking forward to that.
