### ISSUE TITLE
Closing VSC with active processes in integrated terminal doesn't close them.

### ISSUE THREAD

**Issue by primosdace** [Microsoft/vscode#31758]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063

---

Steps to Reproduce:

1. Run for example a node.js server (anything that doesn't close as soon as the code is finished).
2. Close VSC.
3. Send a request to the server. It is still avaible, which means closing VSC doesn't close active processes in integrated terminal.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/26807
