### ISSUE TITLE
Color API: Support hex triplets #abc

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#31751]
Surface triple character hex color declarations: `#abc` means `#aabbcc`

**Comment by starball5** [comment]
I disagree with #32376's closure as a duplicate of this one. Yes, this one covers the part about three-character hex-codes, but it _doesn't_ cover the part about uppercase versus lowercase hex-codes. Could #32376 please be reopened? Edit it to narrow its scope to the part that is unique about it if you have to and can.
