### ISSUE TITLE
Occasional code mangling with tab on blocks of highlighted code

### ISSUE THREAD

**Issue by Sammons** [Microsoft/vscode#3176]
I haven't found a way to deterministically repeat this, but when I highlight several lines of code and hit tab, sometimes it mangles the code (hitting ctrl+z only further mangles the code), unless I copy the code first, I can't go backwards.

My settings.json only has the following
`    "editor.renderWhitespace": true,
    "editor.insertSpaces": true`

EDIT: this is running Version 0.10.8 db71ac615ddf9f33b133ff2536f5d33a77d4774e

**Comment by egamma** [comment]
This looks like issue #2829 on OS X that has been address in the 0.10.9 update. Pls reopen if this is not the case.

**Comment by Sammons** [comment]
@egamma that's the one. Thanks!
