### ISSUE TITLE
Paste entire line between braces

### ISSUE THREAD

**Issue by zhaomiing** [Microsoft/vscode#31762]
- VSCode Version:Version 1.14.2 (1.14.2)
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. move cursor to any line, press cmd+c to copy  entire line
2. move cursor between two empty braces, press cmd + v to paste
3. expect: content was pasted in braces
4. what happened: content was pasted up to the braces

Reproduces without extensions: Yes
![2017-07-31 23 37 49](https://user-images.githubusercontent.com/6185738/28785574-63460f4e-7649-11e7-8789-1f037750ed44.gif)

**Comment by rebornix** [comment]
We did this by purpose and @alexandrudima can elaborate :)

**Comment by alexandrudima** [comment]
`Ctrl+C` or `Copy` with a collapsed selection is kind of a very special action specific to a bunch of code editors.

Other applications refuse to copy anything to the clipboard unless a selection is made.

Anyways, copying with a collapsed selection will also influence the paste action such that the copied line is pasted above the line you are pasting in. AFAIK, this is what other editors do and what users coming from those other editors expect... a way to duplicate a line via `ctrl+c` and `ctrl+v`...
