### ISSUE TITLE
${workspaceRoot} not found in .ts file

### ISSUE THREAD

**Issue by FlorianTaut** [Microsoft/vscode#31765]
- VSCode Version: latest
- OS Version: Windows 10

Steps to Reproduce:

1. Try to use it

Reproduces without extensions: Not sure

When i try to access `${workspaceRoot}` vscode tells me that it cant be found.
But i thought its an "enviroment variable" in vscode: https://code.visualstudio.com/docs/editor/tasks#_variable-substitution

Here is a screen
![unbenannt](https://user-images.githubusercontent.com/18403881/28789828-4a06ce6e-7627-11e7-8475-f6f3b9e2b3cf.PNG)

Do i have to enable it anywhere first?

**Comment by mjbvz** [comment]
Variables are only for the `task.json` file. If you need these variables, try passing them to your js script in the task as command line argument

**Comment by FlorianTaut** [comment]
@mjbvz how can I include the variable. Can't see this in the task.json docs

**Comment by mjbvz** [comment]
@FlorianTaut Tasks can just be command line scripts. In your `tasks.json`, just put ` `${workspaceRoot}` somewhere in the `command` section:

```json
 {
            "taskName": "My task",
            "type": "shell",
            "command": "node ./index.js ${workspaceRoot}"
}
```
