### ISSUE TITLE
Cannot use JSDoc for use Class in other file

### ISSUE THREAD

**Issue by Aminadav** [Microsoft/vscode#31763]
file1.js:

     class abc(){
     }

file2.js:

    /** @type {abc}
    var y

Error:
[js] Cannot find name 'abc'

I have a tsconfig.json, and I tried to use `///refrence` and it doesn't work.

**Comment by mjbvz** [comment]
Is `class abc(){ }` valid syntax?

Also, if you have a `tsconfig.json` instead of a `jsconfig.json`, be sure to set `allowJs` in the `compilerOptions` so that JavaScript files are properly included

**Comment by Aminadav** [comment]
- Yes `class abc(){}` is valid syntax. It doesn't help if I add a constructor.
- I set `allowJs` and include all the files to my `tsconfig.json`

**Comment by mjbvz** [comment]
In which version of ES? I get syntax errors in all the engines I try `class abc(){}` in
