### ISSUE TITLE
Debugging with legacy protocol because Node.js v6.11.0 was detected. /usr/local/bin/node --debug-brk=19804 --nolazy dist/bundle.js 

### ISSUE THREAD

**Issue by yaodehaung** [Microsoft/vscode#31761]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@yaodehaung I do not understand. Please explain the problem you are seeing.

**Comment by yaodehaung** [comment]
thx . I save this proproblem

**Comment by yaodehaung** [comment]
I don't know how to close this issue.
