### ISSUE TITLE
Markdown Preview is not working

### ISSUE THREAD

**Issue by coreyzev** [Microsoft/vscode#31767]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.12.0
markdown-all-in-one|yzh|0.8.1

---

Steps to Reproduce:

1. Download fresh install of VSCode
2. Open a Markdown (*.md) file
3. Try and preview it via any method: Command Palette, **⇧⌘V**, **(⌘K, V)**

Reproduces without extensions: Yes

---

This does not seem to be working at all. Preview doesnt seem to be supported at the moment. Even the status bar says:

> The key combination (⌘K, V) is not a command.

**Comment by mjbvz** [comment]
If you disable all extensions, and specifically `markdown-all-in-one`, does this still happen?

**Comment by coreyzev** [comment]
Yes

> Reproduces without extensions: Yes
\- https://github.com/Microsoft/vscode/issues/31767#issue-246831403

**Comment by mjbvz** [comment]
Are you opening the markdown file directly or did you open a folder?

If you run `Developer: Toggle developer tools`, do you see any error messages printed in the developer console?

**Comment by coreyzev** [comment]
I apologize. I have figured out the issue. 

VSCode is functioning as expected. 

Please delete this issue if desired.

**Comment by gustamora** [comment]
Closed
