### ISSUE TITLE
Allow search by snippet name in Insert Snippet menu

### ISSUE THREAD

**Issue by TrevorBurnham** [Microsoft/vscode#31768]
After installing a snippet pack, it's common for me to think: "I know I have a snippet for this, but I don't know the prefix." To find the prefix, I have to either `Insert Snippet` and scroll until I find it, or open the documentation for the relevant snippet pack.

My proposed solution is to make text typed in the `Insert Snippet` menu match both Snippet prefixes and descriptions. For example, to find "Add event listener," I could type `add` rather than having to guess that its prefix is `ae`:

![snippet-search](https://user-images.githubusercontent.com/224895/28787960-5d3443f8-75ec-11e7-8cab-1ee6987a2df5.gif)

**Comment by jrieken** [comment]
Was rather easy to do...

<img width="629" alt="screen shot 2017-08-21 at 17 39 29" src="https://user-images.githubusercontent.com/1794099/29527001-bb020f7c-8697-11e7-9b4a-359f4057b8ae.png">

**Comment by TrevorBurnham** [comment]
👏 👏 👏
