### ISSUE TITLE
mssql is stuck on connecting, but never connects to the server

### ISSUE THREAD

**Issue by Spenmetsa** [Microsoft/vscode#31764]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
start-git-bash|McC|1.2.1
mssql|ms-|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please file against the mysql extension you are using.
