### ISSUE TITLE
launch.json configuration generated command can't be parsed by external program because multi-word argument has single quotes around it

### ISSUE THREAD

**Issue by eduardogz** [Microsoft/vscode#31772]
In debug configurations (launch.json), when arguments are multi-word such as "--config someArg someVal", they are parsed into '--config someArg someVal' and appended to the final run command (including single-quotes). Is there a way to prevent this behaviour and keep them as they are?

After running the config below I get the following command:
`'C:\Program Files\nodejs\node.exe' --debug-brk=32795 --nolazy node_modules\jasmine-node\lib\jasmine-node\cli.js --color --verbose --captureExceptions '--config someArg someVal' someDir`

jasmine-node does not recognize its format and displays the help text, so the debug output is:

```
USAGE: jasmine-node [--color|--noColor] [--verbose] [--coffee] directory
Options:
...
--config NAME VALUE- set a global variable in process.env
...
```

If I remove the --config arg the debug session starts (and an exception is thrown since the env arg is missing).

Now, if I remove the single quotes around '--config someVar someVal' and then run the command in a terminal, the program runs.

It seems jasmine is unable to parse the argument when it's around single quotes, and I can't use the VSCode debugger. Any help would be greatly appreciated.

Thanks!

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
bower|don|0.0.3
githistory|don|0.2.2
python|don|0.6.9
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.1.6
perforce|sle|2.1.1

---

Steps to Reproduce:

1. npm install jasmine-node
2. create debug configuration:

```javascript
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        "type": "node",
        "request": "launch",
        "name": "Some debug",
        "program": "${workspaceRoot}/node_modules/jasmine-node/lib/jasmine-node/cli.js",
        "args": [
            "--color",
            "--verbose",
            "--captureExceptions",
            "--config someArg someVal",
            "someDir"
        ]
    }]
}
```
3. run config

Reproduces without extensions: Yes

**Comment by weinand** [comment]
If something like "--config someArg someVal" should be passed as individual arguments to node.js, you'll have to break this into individual arguments:
```javascript
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        "type": "node",
        "request": "launch",
        "name": "Some debug",
        "program": "${workspaceRoot}/node_modules/jasmine-node/lib/jasmine-node/cli.js",
        "args": [
            "--color",
            "--verbose",
            "--captureExceptions",
            "--config", "someArg", "someVal",
            "someDir"
        ]
    }]
}
```

**Comment by eduardogz** [comment]
:astonished:
Of course!! :blush: :blush: :rofl: 
Thanks for the quick response!
