### ISSUE TITLE
Test: Using basename for terminal title

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#31778]
Covers https://github.com/Microsoft/vscode/issues/30152
- [x] Windows @rebornix 
- [x] Linux @roblourens 
- [x] Mac @ramya-rao-a 

Complexity: 1
- We are now using basename to trim terminal titles, verify that various process titles are as expected (ie: when `$SHELL=/bin/bash` -> `bash`)
- In Windows we strip the `.exe` from the title (`powershell.exe -> powershell`)
- Verify that the terminal does not flicker to undefined or blank when creating a terminal

**Comment by ramya-rao-a** [comment]
@Lixire I can confirm that the flicker no longer exists in the latest Insiders when compared to the previous stable.

But the previous stable (in mac) was already showing the base name. So what's the change here?

**Comment by Lixire** [comment]
We're testing that the names stay the same (on Mac/Linux) since I changed the method that sets the title. There should be no visible difference.

**Comment by Tyriar** [comment]
@ramya-rao-a you're likely on a machine that has `$SHELL` set to `bash` which is fine and common. It's also common to set `$SHELL` to `/bin/bash` which would come up at "/bin/bash" in the dropdown previously.

**Comment by ramya-rao-a** [comment]
Nope. Had it as `/bin/bash` all along. Below is stable

<img width="478" alt="screen shot 2017-08-01 at 11 14 32 am" src="https://user-images.githubusercontent.com/16890566/28840045-8b81dc34-76aa-11e7-87b6-0e6d3bf8e591.png">

**Comment by Tyriar** [comment]
Huh, when did that happen lol

**Comment by roblourens** [comment]
It was showing `/bin/bash` for me on stable Linux

**Comment by Tyriar** [comment]
@roblourens sanity verified 👍

**Comment by rebornix** [comment]
Looks good to me on Windows.
