### ISSUE TITLE
Ctrl+Shift+F search runs on the UI thread and makes the UI unusable on even small projects.

### ISSUE THREAD

**Issue by JoshSnider** [Microsoft/vscode#31779]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
debugger-for-chrome|msj|3.1.6
tsimporter|pmn|1.2.14
vscode-icons|rob|7.11.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you provide some more details about the problem? The search itself does not run on the UI thread. There could be some brief slowdown when you get a large number of results. But I wouldn't expect it to be unusable.

**Comment by Adondriel** [comment]
I find this issue presents itself for me, personally when it hits large, compiled .js files, or .js map files. I'll add a recording in a second.

**Comment by JoshSnider** [comment]
@Adondriel's video shows the same UI lockup behavior I was seeing when I reported this.

**Comment by roblourens** [comment]
Thanks, that's pretty extreme. @JoshSnider does your search also hit large .js/.js.map files? I would recommend excluding those from search for now with the `search.exclude` setting.

**Comment by roblourens** [comment]
There are some other issues for searching in large files like https://github.com/Microsoft/vscode/issues/31551
