### ISSUE TITLE
[Important] Microsoft Visual C++ Runtime Library: "Assertion failed" when closing a terminal process

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#31782]
- VSCode Version: Code - Insiders 1.15.0-insider (0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7, 2017-07-28T11:23:06.089Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
gitignore|cod|0.5.0
vscode-dash|dee|1.7.0
css-minify|Die|0.0.4
vscode-npm-source|dku|1.0.0
python|don|0.6.9
gitlens|eam|4.3.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
gc-excelviewer|Gra|1.1.15
composer|ika|0.5.0
smarty|imp|0.2.0
code-guid|jam|1.0.1
StretchTimer|jpa|0.0.1
json-to-ts|Mar|1.5.2
Runner|mat|0.1.14
vscode-apache|mrm|1.1.1
cpptools|ms-|0.12.1
github-issues-prs|ms-|0.3.1
php-docblocker|nei|1.2.0
emoji|Per|0.0.3
vscode-versionlens|pfl|0.19.1
datetime|rid|1.0.5
vscode-icons|rob|7.12.0
sharecode|Rol|0.4.1
todotasks|san|0.5.0
code-settings-sync|Sha|2.8.2
vscode-spotify|shy|2.0.0
packagelinker|sin|0.0.3
code-spell-checker|str|1.3.2
pdf|tom|0.2.0
lorem-ipsum|Tyr|1.0.0
vscode-arduino|vsc|0.2.4
vscode-todo-highlight|way|0.5.8
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open up an empty folder on windows. 
2. Open up an terminal.
3. Kill that terminal process.
4. Get this error message:
![image](https://user-images.githubusercontent.com/11234139/28799313-5fcbdab6-7648-11e7-89cf-88ac59235c07.png)

This issue is quite annoying, because it also reproduces when changing the current folder... :/ Most likely, this is upstream, but still important.

Reproduces without extensions: Yes **!!!**

I think you need more details, but which ones?

**Comment by pocesar** [comment]
and, after the error, the following message apepars

![image](https://user-images.githubusercontent.com/461084/28847790-e4ec27b6-76e6-11e7-8ae4-b0638efc5066.png)

**Comment by jens1o** [comment]
Yep, that's also true. I missed that, sorry.

**Comment by Tyriar** [comment]
Hmm, I can't reproduce. can you share your settings.json? Also how are you killing the terminal exactly?

**Comment by jens1o** [comment]
Using the trashbin: 
![image](https://user-images.githubusercontent.com/11234139/28891962-95822bbc-77cc-11e7-9fac-99401f9a4f18.png)

My user settings are quite complex...
But here you go: https://gist.github.com/jens1o/9b80018dd19f6745db862f56edea07ef

**Comment by roblourens** [comment]
@jens1o Can you confirm that this is fixed for you using the latest insiders?

**Comment by jens1o** [comment]
Yes, this is fixed for me @roblourens .
