### ISSUE TITLE
Ampersands in context menu not displayed

### ISSUE THREAD

**Issue by idleberg** [Microsoft/vscode#31787]
- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a command with ampersand in title
2. Create a context menu for the command (see example below)
3. Reload Code

**Example:**

```json
"commands": [
    {
        "command": "extension.nsis.compile",
        "title": "NSIS: Save & Compile Script"
    }
],
"menus": {
    "editor/context": [
        {
            "when": "resourceLangId == nsis",
            "command": "extension.nsis.compile"
        }
    ]
}
```

When opening the context-menu, the ampersand will not be displayed:

![vscode](https://user-images.githubusercontent.com/1504938/28800965-a8b85d38-764f-11e7-90ec-445ad3d2f498.png)

**Comment by bpasero** [comment]
@jrieken It looks like we need to escape a single `&` with `&&` at the location where this editor menu is being created. Not sure where exactly the contributed actions are coming in though.

**Comment by jrieken** [comment]
@bpasero Are there other characters that need escaping?

**Comment by jrieken** [comment]
@bpasero I have the strong feeling this should tackled as close as possible to the location which requires this kind of escaping. From my understanding that is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L81 and your code, re-assign if not
