### ISSUE TITLE
`Switch active terminal`  should be `Terminal: Switch Active Terminal`

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#31789]
- VSCode Version: Code - Insiders 1.15.0-insider (19f17905e7ecd62c3f0cb14c30a66db1ebfe8069, 2017-07-31T13:20:54.088Z)
- OS Version: Darwin x64 16.7.0

`Switch active terminal`  should be `Terminal: Switch Active Terminal`

**Comment by Lixire** [comment]
This is fixed already here https://github.com/Microsoft/vscode/pull/31781/files
