### ISSUE TITLE
i cannot uninstall any extend plugin

### ISSUE THREAD

**Issue by momobile** [Microsoft/vscode#31794]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
google-search-ext|ade|0.1.2
vscode-eclipse-keybindings|alp|0.9.6
django-html|bib|1.2.0
django-snippets|bib|1.1.0
python-snippets|cst|0.0.5
jupyter|don|1.1.3
python|don|0.6.9
python-extension-pack|don|1.0.0
code-python-isort|fre|0.0.3
py-paste-indent|hye|0.0.2
file-ext-switcher|Joh|3.0.0
python-traceback-jumper|lin|1.0.8
MagicPython|mag|1.0.11
vscode-icons|rob|7.12.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8

---

Steps to Reproduce:

1.ctrl+shift+x switch to extend
2.find jinja and uninstall it

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
@momobile you use the drop down on the gear to uninstall, correct? What happened afterwards? Any error messages? Did you reload the window afterwards? Did the extension still show up being installed after reload?
