### ISSUE TITLE
Extentions can not work correctly on macOS

### ISSUE THREAD

**Issue by HuangYanQi** [Microsoft/vscode#31793]
The extension Yeoman an OmniCSharp can not work on macOS and I had install Visual Studio again
[samverschueren.yo-0.9.3.zip](https://github.com/Microsoft/vscode/files/1189242/samverschueren.yo-0.9.3.zip)

**Comment by kieferrm** [comment]
Please file an issue here: https://github.com/OmniSharp/omnisharp-vscode/issues
Thanks!
