### ISSUE TITLE
Error opening when upgrading to VSCode 64-bits.

### ISSUE THREAD

**Issue by osnoser1** [Microsoft/vscode#31792]
- VSCode Version: 1.14.2 x64
- OS Version: Windows 10 14393.953

Steps to Reproduce:

1. Update to VSCode 64 bits.
2. Open VSCode instance.
3. Open integrated terminal.

Error code: 

```No se pudo iniciar el comando de proceso terminal "C:\WINDOWS\sysnative\WindowsPowerShell\v1.0\powershell.exe" (código de salida: 3221225477)```

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/1179744/28804119-5684bfea-762f-11e7-94d6-22dfcdaecbe9.png)

**Comment by jens1o** [comment]
Afaik, this has been fixed in latest insider. Patch to come on Friday to public. ;)

**Comment by ngetchell** [comment]
Thanks @jens1o . Ran into this problem earlier today.

**Comment by Tyriar** [comment]
Well this is for stable, the fix will come in 1.15.0 which will be a little while off yet. To fix this you need to change your terminal.integrated.shell.windows setting to point to "System32", not "Sysnative".
