### ISSUE TITLE
Issues with Code Signatures

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#31790]
- VSCode Version:  1.14.1 
- OS Version: 10.11.6

Steps to Reproduce:

1. Open VS Code
2. Open another instance of VS Code

I get two versions of VS Code. 

![2017-08-01 at 01 03](https://user-images.githubusercontent.com/6391776/28802124-3be22a1c-7655-11e7-9f10-6646b3a9cb23.png)

And each has a different code signature. I don't know what to do to fix this. This did not happen before this update. Thank you for any help.

**Comment by kieferrm** [comment]
@nikitavoloboev This is on macOS? How many different versions do you have installed? How do you launch? If it's macOS, do you end up on the same file when you open the context menu on the icon in the dock and select Options>Show in Finder?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
