### ISSUE TITLE
C++: IntelliSense does not recognize type from literals

### ISSUE THREAD

**Issue by Ptomaine** [Microsoft/vscode#31791]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.12.1
cmake-tools|vec|0.10.2

---

Screenshot:

![literals](https://user-images.githubusercontent.com/2706546/28803365-c892dabe-7610-11e7-9e15-aaa80ced3c3c.png)

Reproduces without extensions: No

**Comment by kieferrm** [comment]
Pls file an issue here: https://github.com/Microsoft/vscode-cpptools/issues
Thanks!
