### ISSUE TITLE
开启多个进程实例情况下:菜单文件->退出时导致其他所有实例都退出bug

### ISSUE THREAD

**Issue by seainchina** [Microsoft/vscode#31795]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.6.9
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.7
csharpextensions|jch|1.3.0
mssql|ms-|1.1.0
cpptools|ms-|0.12.1
csharp|ms-|1.11.0
mono-debug|ms-|0.15.7
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.1.7
vscode-docker|Pet|0.0.16
vscode-icons|rob|7.12.0
python|tht|0.2.3
vim|vsc|0.9.0
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by King66** [comment]
“文件-退出”就是关闭所有窗口
“文件-关闭窗口”是关闭当前窗口

**Comment by rebornix** [comment]
Like @kzhui125 mentioned, this is by design.
