### ISSUE TITLE
x64-1.15.0-insider find in folder not work

### ISSUE THREAD

**Issue by DeyuanTan** [Microsoft/vscode#31798]
- VSCode Version: VSCodeSetup-x64-1.15.0-insider
- OS Version: windows 7

Steps to Reproduce:

1. find in folder
2. search something
3. No results found in PATH

if **delete files to include** then can find the code

**Comment by roblourens** [comment]
It works for me. Can you include more details about what it shows in "files to include" and your folder structure?

And can you open the "search" part of the Output pane and show the output?

**Comment by DeyuanTan** [comment]
I have few *.module.js
![image 4](https://user-images.githubusercontent.com/8966624/28812779-ecd61aea-76c8-11e7-9a69-371c9af75ce0.png)

when use find in folder and file open
![image 5](https://user-images.githubusercontent.com/8966624/28812812-16550750-76c9-11e7-8c47-87da37f43c36.png)

when close file

![image 6](https://user-images.githubusercontent.com/8966624/28812829-2bf605be-76c9-11e7-9892-5a16106426cd.png)

when delete path
![image 7](https://user-images.githubusercontent.com/8966624/28812912-8afc2246-76c9-11e7-9423-4c96eca6e930.png)

Version 1.14.2 
![image 8](https://user-images.githubusercontent.com/8966624/28813111-68d92348-76ca-11e7-8d1f-408b7f217f82.png)

**Comment by roblourens** [comment]
Thanks, can you open the Search output panel and show the output from a failed search?

![image](https://user-images.githubusercontent.com/323878/28831314-16528fec-768e-11e7-984c-ff59f959f88b.png)

**Comment by DeyuanTan** [comment]
It's seems path error! files on D: but search on C:
![image1](https://user-images.githubusercontent.com/8966624/28854957-6f8f9c4c-776c-11e7-9bec-a8544c4db0cc.png)

**Comment by roblourens** [comment]
Wow, that's odd. I still can't repro - am trying on Windows 7, searching across drives.

Are you on the latest insiders build? Can you look in Help > About and post the commit version?

**Comment by DeyuanTan** [comment]
![image5](https://user-images.githubusercontent.com/8966624/28865727-6ba7d040-77a3-11e7-8f15-2dd4a1a17962.png)

**Comment by DeyuanTan** [comment]
download latest insider and it's work! Thanks!

**Comment by roblourens** [comment]
phew! Thanks
