### ISSUE TITLE
Should ES6 be the JavaScript Default?

### ISSUE THREAD

**Issue by felixrieseberg** [Microsoft/vscode#318]
Hey everyone, 2015 is almost over, but we still need an editor configuration file to edit what is currently "JavaScript as supported by browsers". I'd like to avoid [reactions like these](https://twitter.com/sugarpirate_/status/667029989695582208). That would also solve issues like #54.

I'll make a PR to pressure y'all even more :stuck_out_tongue_winking_eye:

**Comment by joaomoreno** [comment]
:+1:

**Comment by stoufa88** [comment]
yes

**Comment by alessandromuresan** [comment]
:+1: :+1: :+1:

**Comment by jrieken** [comment]
Closing for now: https://github.com/Microsoft/vscode/pull/337#issuecomment-158404957

**Comment by jrieken** [comment]
We are save to make this change for Dec because going forward with project salsa the default will be the latest for JS files (#Microsoft/TypeScript/6017)
