### ISSUE TITLE
Go to next/previous breakpoint

### ISSUE THREAD

**Issue by CTimmerman** [Microsoft/vscode#31806]
- VSCode Version: 1.14.2
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Set some breakpoints.
2. Fail to find shortcut to navigate between breakpoints without running the file.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
We accept PRs that fix this - especaially if more users ask for this feature request

**Comment by mbeatrizmagalhaes** [comment]
Hi, I'm working on this. Will submit a PR soon.

**Comment by CTimmerman** [comment]
Having this feature could remove the need for bookmarks, fixing https://github.com/Microsoft/vscode/issues/5923

**Comment by weinand** [comment]
Does not work for me:
- set breakpoints in various files.
- run "Go To Next Breakpoint" action

Observe:
completely random behaviour. Sometimes I can only go through the breakpoints in one file, sometimes I can switch back and forth between two files. But I'm not able to step through all breakpoints in all files in deterministic order.

**Comment by isidorn** [comment]
Dup of 50864

**Comment by dbaeumer** [comment]
Verified #50864. Marking this as verified as well.
