### ISSUE TITLE
VS Code through Windows Explorer integration doesn't function if there is another instance of VS Code already open

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#3180]
If you already have VS Code open (either with an open folder/file or an empty window), if you try to open up a **second** instance of VS Code by right-clicking on a file/folder in Windows Explorer and click *Open with Code*, nothing happens.  The desired functionality would be for opening files/folders through Windows Explorer integration to function even if there are already opened instances of VS Code.

### Repro Steps

1. Open up VS Code (doesn't matter if you open up VS Code with no file or folder, the behavior is the same)
2. In Windows Explorer, navigate to a folder with a flat file
3. Right-click on the file and select *Open with Code*
4. Note that this attempt at opening a 2nd instance of VS Code through Windows Explorer doesn't succeed

**Comment by anandgupta08** [comment]
I am also experiencing the same problem. However i seem to have this issue in one machine, but not in another even though the both have the same VS Code version.

**Comment by Tyriar** [comment]
I think this is intentional behavior since Code doesn't launch two instances for the same folder. Related discussion https://github.com/Microsoft/vscode/issues/48

**Comment by tstringer** [comment]
@Tyriar that isn't the behavior I'm seeing.  You say for the **same folder**.  The second instance launch attempt could/would be for a totally different folder.  That's the problem.  Folder1 is open in VSCode instance1, trying to open Folder2 for a 2nd VSCode instance from Windows Explorer fails.

**Comment by bpasero** [comment]
@tstringer Windows 10?

**Comment by tstringer** [comment]
@bpasero That's correct, Windows 10.

**Comment by bpasero** [comment]
very likely https://github.com/Microsoft/vscode/issues/929

**Comment by DanTup** [comment]
@bpasero I don't believe this is #929.

I'm on Windows 10 and have Code open for a folder (`M:\Coding\Applications\Dart-Code`) and I'm double-clicking on a Markdown file `M:\Apps\Dart\lib\analysis_server\README.md` and nothing is happening. If I manually switch to the Code window I have open, the README has most certainly not opened.

(It's not isolated to this time, I've never been able to open a second instance, not even by clicking the "New Window" task under VS Code from the Taskbar!)

**Comment by DanTup** [comment]
Ok, figured this out - it happens when the instance of Code already open is elevated - I launched it from an Admin PoSh window. If I open it as non-Admin then I don't see this behaviour.

It definitely doesn't make sense to behave like this; let me know if I should open a new issue or you'll just reuse this one.
