### ISSUE TITLE
Sometimes indent 4 spaces pressing tab when I have defined tab size 2 spaces

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#31803]
- VSCode Version: 1.14.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. I have set tab size: 2 spaces, and in most files when I press tab, it will indent 2 spaces.
2. But in a few files (cloned from github), when I press tab, it will still indent 4 spaces.

Reproduces without extensions: Yes

**Comment by Kongsea** [comment]
For example:
This file [dense_net.py](https://github.com/ikhlestov/vision_networks/blob/master/models/dense_net.py) in [this repository](https://github.com/ikhlestov/vision_networks).

**Comment by larssn** [comment]
I'm having a similar issue. Maybe from the most recent VSCode release.

Basically my tab size is 2 spaces. But some files revert to 4 spaces after being closed and reopened. It doesn't happen to all files. This is with all extensions disabled.

**Comment by alexandrudima** [comment]
There are 3 distinct settings regarding editor indentation:

```
  // The number of spaces a tab is equal to. This setting is overriden based on the 
  // file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,

  // Insert spaces when pressing Tab. This setting is overriden based on the 
  // file contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be 
  // detected based on the file contents.
  "editor.detectIndentation": true,
```

Perhaps you would like to set `editor.detectIndentation` to `false`.
