### ISSUE TITLE
Code editor does not scroll horizontally when using multiple carets

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#31809]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
code-spell-checker|str|1.3.2

---

Steps to Reproduce:

1. Open a code editor where the width of the tab is smaller than the longest line of code.
2. Place multiple carets (2 is enough), one being on the longest line of code.
3. Mark to the end of the line, either by dragging horizontally or using keyboard shortcuts.

![image](https://user-images.githubusercontent.com/1658949/28823553-6891e8cc-76be-11e7-9173-163df2082e0c.gif)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/31809. Let's track it there but I like you gif, will revisit this one when we improve the behavior, thanks!

**Comment by oliversalzburg** [comment]
@rebornix This *is* #31809
