### ISSUE TITLE
Doubling up of filenames, differing only by case

### ISSUE THREAD

**Issue by burtondanj** [Microsoft/vscode#31804]
- VSCode Version: Code - Insiders 1.15.0-insider (9dd41b52a2487bd5595f7ac234fb1f251b902c12, 2017-07-28T05:17:00.444Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
vscode-icons|rob|7.12.0

(3 theme extensions excluded)

---

a ctrl+shift+f find doubles up on results with each pair only differing by case: first has the camel case as the filesystem exists, the second is all lower case.

Reproduces without extensions: Yes/No

**Comment by burtondanj** [comment]
Also affecting breakpoints:
![image](https://user-images.githubusercontent.com/13609013/28821692-579ecd24-76ae-11e7-8c97-1d1cb9dae631.png)

**Comment by kieferrm** [comment]
@burtondanj can you pls provide us with the concrete steps to reproduce the search problem? What is in your workspace? What do you search for? Which file system type are you on? etc. Thanks!
