### ISSUE TITLE
VSCode crashed on startup, Windows 7

### ISSUE THREAD

**Issue by Aenoa** [Microsoft/vscode#31802]
- VSCode Version: 1.14.2 cb82febafda0c8c199b9201ad274e25d9a76874e
- OS Version: Windows 7 x64

Steps to Reproduce:
1. Open VS Code
2. watch the windows error reporting tool pop on screen

Reproduces without extensions: Yes

When launching VS Code, it crashes. Yesterday i worked fine and no changes were made to the client, nor to the OS, no app was installed, no path got changed.

When starting Code with the --verbose, i get the following output:

> $ code --verbose
> 
> [main 9:36:12 AM] Starting VS Code in verbose mode
> [main 9:36:12 AM] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
> [main 9:36:12 AM] args: { _: [],
>   help: false,
>   h: false,
>   version: false,
>   v: false,
>   wait: false,
>   w: false,
>   diff: false,
>   d: false,
>   goto: false,
>   g: false,
>   'new-window': false,
>   n: false,
>   'unity-launch': false,
>   'reuse-window': false,
>   r: false,
>   performance: false,
>   p: false,
>   'prof-startup': false,
>   verbose: true,
>   logExtensionHostCommunication: false,
>   'disable-extensions': false,
>   disableExtensions: false,
>   'list-extensions': false,
>   'show-versions': false,
>   nolazy: false,
>   'skip-getting-started': false }
> [3408:0801/093612.314:FATAL:direct_manipulation.cc(38)] Check failed: SUCCEEDED(hr).
> Backtrace:
>         GetHandleVerifier [0x00364C47+16999]
>         (No symbol) [0x0035EA41]
>         IsSandboxedProcess [0x00AF0B5D+5345393]
>         IsSandboxedProcess [0x008442C8+2541532]
>         GetHandleVerifier [0x005B3037+2434647]
>         GetHandleVerifier [0x005AF903+2420515]
>         GetHandleVerifier [0x005A0405+2357797]
>         (No symbol) [0x0030B8ED]
>         (No symbol) [0x0030C251]
>         (No symbol) [0x00290F3B]
>         (No symbol) [0x0028C20B]
>         (No symbol) [0x002913EF]
>         (No symbol) [0x00269408]
>         (No symbol) [0x00269711]
>         (No symbol) [0x00265744]
>         (No symbol) [0x00269422]
>         (No symbol) [0x00269730]
>         (No symbol) [0x002689F3]
>         (No symbol) [0x00268291]
>         v8::internal::CompilerDispatcherTracer::RecordPrepareToParse [0x69BB8615+291445]
>         v8::internal::Builtins::UnsupportedThrower [0x69AD765E+5486]
>         v8::internal::Builtins::UnsupportedThrower [0x69AD7C7C+7052]

When starting with the extensions disabled, the error is the same:

> $ code --disable-extensions --verbose
> 
> [main 9:40:26 AM] Starting VS Code in verbose mode
> [main 9:40:26 AM] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
> [main 9:40:26 AM] args: { _: [],
>   help: false,
>   h: false,
>   version: false,
>   v: false,
>   wait: false,
>   w: false,
>   diff: false,
>   d: false,
>   goto: false,
>   g: false,
>   'new-window': false,
>   n: false,
>   'unity-launch': false,
>   'reuse-window': false,
>   r: false,
>   performance: false,
>   p: false,
>   'prof-startup': false,
>   verbose: true,
>   logExtensionHostCommunication: false,
>   'disable-extensions': true,
>   disableExtensions: true,
>   'list-extensions': false,
>   'show-versions': false,
>   nolazy: false,
>   'skip-getting-started': false }
> [3644:0801/094026.330:FATAL:direct_manipulation.cc(38)] Check failed: SUCCEEDED(hr).
> Backtrace:
>         GetHandleVerifier [0x01504C47+16999]
>         (No symbol) [0x014FEA41]
>         IsSandboxedProcess [0x01C90B5D+5345393]
>         IsSandboxedProcess [0x019E42C8+2541532]
>         GetHandleVerifier [0x01753037+2434647]
>         GetHandleVerifier [0x0174F903+2420515]
>         GetHandleVerifier [0x01740405+2357797]
>         (No symbol) [0x014AB8ED]
>         (No symbol) [0x014AC251]
>         (No symbol) [0x01430F3B]
>         (No symbol) [0x0142C20B]
>         (No symbol) [0x014313EF]
>         (No symbol) [0x01409408]
>         (No symbol) [0x01409711]
>         (No symbol) [0x01405744]
>         (No symbol) [0x01409422]
>         (No symbol) [0x01409730]
>         (No symbol) [0x014089F3]
>         (No symbol) [0x01408291]
>         v8::internal::CompilerDispatcherTracer::RecordPrepareToParse [0x69BB8615+291445]
>         v8::internal::Builtins::UnsupportedThrower [0x69AD765E+5486]
>         v8::internal::Builtins::UnsupportedThrower [0x69AD7C7C+7052]

My system:

> ------------------
> System Information
> ------------------
> Time of this report: 8/1/2017, 09:42:11
> Machine name: BE-BRU-HP-B3D1
> Operating System: Windows 7 Professional 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.170512-0600)
> Language: French (Regional Setting: French)
> System Manufacturer: Dell Inc.
> System Model: Latitude E7450
> BIOS: BIOS Date: 12/26/16 20:26:34 Ver: A15.00 
> Processor: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 CPUs), ~2.6GHz
> Memory: 8192MB RAM
> Available OS Memory: 8064MB RAM
> Page File: 3472MB used, 12654MB available
> Windows Dir: C:\Windows
> DirectX Version: DirectX 11
> DX Setup Parameters: Not found
> User DPI Setting: Using System DPI
> System DPI Setting: 96 DPI (100 percent)
> DWM DPI Scaling: Disabled
> DxDiag Version: 6.01.7601.17514 64bit Unicode

(VS Code insider works just fine. Even reinstalling VSCode isnt fixing the issue)

**Comment by Aenoa** [comment]
Update, launching VSCode as Vista compatibility mode works; Disabling compatibility mode makes the application crash again;

**Comment by bpasero** [comment]
@Aenoa is that the 32bit or 64bit version?

/cc @joaomoreno

**Comment by Aenoa** [comment]
32 bits

**Comment by bpasero** [comment]
@Aenoa we are using the Electron framework, can I ask you to try to run the bare Electron application (download from https://github.com/electron/electron/releases/download/v1.6.6/electron-v1.6.6-win32-ia32.zip) to see if that shows the same crash on startup?

**Comment by Aenoa** [comment]
Works fine for me on the provided link

**Comment by bpasero** [comment]
This looks like https://github.com/electron/electron/issues/9646

**Comment by Aenoa** [comment]
release 1.15.0 fixed the issue

**Comment by Aenoa** [comment]
Updated to 1.15.0, issue is still there.
attached is a verbose console log of VSCode, with on its side Electron app you asked me to test out.

![sqqq](https://user-images.githubusercontent.com/928928/29353188-a2f96b50-8269-11e7-9c31-ba0ad5df5a54.png)

**Comment by Aenoa** [comment]
as of version 1.17.2, the problem is fixed and does not need any compatibility mode to be launching successfully.
