### ISSUE TITLE
VSCode only see Environment variables when launched via terminal "code"

### ISSUE THREAD

**Issue by rendomnet** [Microsoft/vscode#31800]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.9.39-1-MANJARO

When I start Vscode via "icon shortcut click" it do not see my current environment variables.  For example react-native-cli PATH so my react native tools not working.

But when I start vscode via "code" terminal command it works correctly.

**Comment by logme1** [comment]
Get Outlook for Android<https://aka.ms/ghei36>



From: rendomnet
Sent: Tuesday, August 1, 1:05 AM
Subject: [Microsoft/vscode] VSCode only see Environment variables when lauch via terminal "code" (#31800)
To: Microsoft/vscode
Cc: Subscribed


VSCode Version: Code 1.14.2 (cb82feb<https://github.com/Microsoft/vscode/commit/cb82febafda0c8c199b9201ad274e25d9a76874e>, 2017-07-19T23:26:08.116Z) OS Version: Linux x64 4.9.39-1-MANJARO
When I start Vscode via "icon shortcut click" it do not see my current environment variables. For example react-native-cli PATH so my react native tools not working.
But when I start vscode via "code" terminal command it works correctly.

**Comment by Adondriel** [comment]
I feel like this is just going to end up being due to how environment variables work. What you could do, is create a bat/cmd file that just runs the "code" command, and then use that instead of the basic shortcut that they give.

**Comment by D219** [comment]
Have the same problem. When opened from the dock (wich in fact use the .desktop file, which itself start the binary directly), the environment is not carried.
It seems like in that case, nor `.bashrc` nor `.profile` is read, and since it is where most of the environment is set...

However, when opened from the terminal, since the environment is inherited from the terminal, which itself did read `.bashrc`, the environment variable are set.

In my case, it mess up things with node and npm, since I use `n` (alternative to `nvm` to use multiple version of node).

**Comment by joaomoreno** [comment]
@rendomnet @D219 What's your default shell?

**Comment by Adondriel** [comment]
I'm on windows, and my path is fine, just to add that bit of info... I'm guessing this is related to linux(possibly mac). The integrated terminal gets all my path info perfectly fine, on windows. I'll have to try this with linux at some point.

**Comment by rendomnet** [comment]
@joaomoreno zsh

**Comment by joaomoreno** [comment]
@rendomnet If you open the developer tools (<kbd>F1</kbd>, `Developer Tools`) is there any warning/error message showing up?

**Comment by D219** [comment]
@joaomoreno Default Debian Jessie, so bash. Can't say a lot more, I ended up reinstalling my machine, and it work anew :)

**Comment by ephphatha** [comment]
You can change the arguments vscode passes to the shell by adding a `terminal.integrated.shellArgs.<os>` key to your user settings.json file. I'd been struggling with the same issue until I saw your comment @D219 and simply adding `-i` on windows was enough to get it to execute the .bashrc for both terminals (those launched by tasks and the interactive terminal).

    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "-i"
    ],
