### ISSUE TITLE
CSS grid grid-row-start not recognized

### ISSUE THREAD

**Issue by wsw70** [Microsoft/vscode#31807]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

When editing a CSS file, the [`display: grid`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) elements are recognized, except for `grid-row-start`:

![](http://i.imgur.com/ue0i5Ch.png)

![](http://i.imgur.com/7S75h2c.png)

Reproduces without extensions: Yes

**Comment by wsw70** [comment]
@aeschli I am not sure how you handle these submissions but it is a bug, right? If so why is it closed? (or has it been fixed already?)

**Comment by aeschli** [comment]
I added a fix. It will be in 1.15
