### ISSUE TITLE
Better support of cursor movement keybinding.

### ISSUE THREAD

**Issue by giyyapan** [Microsoft/vscode#31812]
I'm an emacs-style keybinding user, and I'm willing to use emacs-style cursor movement shortcut everywhere in VSCode.
Though this goal can be achieved in most case, there's still some trouble:
- In popup input window like findWidget and renameWidget, there's no way to modify the cursor movment key(.e.g C-b/f to move cursor left/right).
- In referenceSearch widget, there's no way to make C-p/n to focusUp/focusDown through the result list in the right side, I have to use arrow key to do that.

I believe I've tried every available options, please tell me if I missed anything.
Thanks!

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
