### ISSUE TITLE
VSCode reporting Typescript errors incorrectly when opened from a subdirectory from tsconfig

### ISSUE THREAD

**Issue by jamirvin** [Microsoft/vscode#31816]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a folder structure where the TS files are in a subdirectory from the location of tsconfig.json
2. Open the directory with the TS files in VSCode.
3. Symbols from unopened files are not recognized even though running tsc works fine as does opening the root folder in VSCode.

Example repo: https://github.com/jamirvin/VSCodeBug

One strange thing I've noticed is that if you change the version number in the Typescript directory's package.json to be lower than 2.3 it works, regardless of the actual Typescript version being used. 

Demo:
![vscode_bug](https://user-images.githubusercontent.com/14207652/28834670-e950f092-76b0-11e7-827d-573eba67c1a9.gif)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Your `tsconfig.json` needs to live in the top level of whatever folder you opened.

In versions of TS < 2.3, we traverse up the file system to find parent `tsconfig` files, even if these fall outside of the currently opened folder in VSCode. This can cause major performance issues when someone puts a `tsconfig.json` in their home directory, so newer versions of TS only traverse as far as the VSCode folder root when searching for a `tsconfig.json`
