### ISSUE TITLE
Telemetry application insights refactor

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#3181]
- [x] windows @joaomoreno
- [x] mac @weinand 
- [x] linux @Tyriar 

The application insights adapter has been refactored, that code path is critical as it affects all the telemetry data flowing from VSCode. 

To test:

1. Open the Chrome Dev Tools within Code and set a breakpoint in `...\resources\app\node_modules\applicationinsights\Library\Channel.js`.
2. Do some work in the product 
3. Once the breakpoint is hit, inspect the `batch` variable by running `batch.split('\n').map(JSON.parse)` in the console.
4. Verify that:
   1. all events' `data.baseData.name` is prefixed with `monacoworkbench/`
   2. numeric values are under `measurements`
   3. textual values are under `properties`

**Comment by joaomoreno** [comment]
This test description was bad. I've updated with better steps.
