### ISSUE TITLE
VSCode 1.15 on macOS: Scroll to Top and Scroll to Bottom not working

### ISSUE THREAD

**Issue by jkwuc89** [Microsoft/vscode#31811]
- VSCode Version: 1.15 (1.15)
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open Code
2. Open any file
3. Press Cmd + Home, the Scroll to Top default keyboard shortcut. Observe that nothing happens.
4. Press Cmd + End, the Scroll to Bottom default keyboard shortcut. Observe that nothing happens.

I also tried binding Ctrl + Home to Scroll to Top and Ctrl + End to Scroll to Bottom. Neither of those bound shortcuts worked.

Reproduces without extensions: Yes

**Comment by jkwuc89** [comment]
This remains an issue in version 1.15.

**Comment by rebornix** [comment]
@jkwuc89 for now we only bind `cmd+home` to Scroll To Top in Integrated Terminal, not in the editor.

**Comment by jkwuc89** [comment]
Key bindings to Scroll to Top and Scroll to Bottom were working in version 1.13. 1.14 is where this stopped working. Are there plans to fix this in a future version?

**Comment by joelhock** [comment]
this works for me in the editor:
```{ "key": "ctrl+home",                "command": "cursorTop", "when": "editorTextFocus" },```
I think you just need the to use the `cursorTop` action

**Comment by jkwuc89** [comment]
Adding the following to my key mappings did the trick. Thanks @joelhock.

```
{
        "key": "ctrl+home",
        "command": "cursorTop",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+end",
        "command": "cursorBottom",
        "when": "editorTextFocus"
    }
```
