### ISSUE TITLE
Closing tabs with middle-mouse-click propagates through save confirmation popup

### ISSUE THREAD

**Issue by DHainzl** [Microsoft/vscode#31810]
Most of the time I have one or more unsaved "Untitled" files open for quick notes, etc. When I am now going on a streak of middle-clicking all tabs to close them, I often hit the middle mouse button on the unsaved file multiple times, which results in the "Do you want to save the changes ..." popup appearing multiple times for the same file.

---

How to reproduce:

* Open up a new file, add some text but don't save it
* Click the middle mouse button multiple times on the tab to close it
* The popup appears asking you if you want to save "Untitled-1".
    * Click "Cancel"
* The popup appears again and again (=> the amount of time you've middle-clicked the tab).

This can also be reproduced in the "Open Editors" pane to the left.

Also, the actions are queued - trying to close a second (saved) file while the dialog is shown closes the saved file correctly after all the dialogs are dismissed.

---

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions (all disabled):

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-simpler-icons|davidbabel|1.3.0|
|tslint|eg2|0.17.0|
|code-runner|formulahendry|0.6.29|
|path-autocomplete|ionutvmi|1.6.1|
|debugger-for-chrome|msjsdiag|3.1.7|
|java|redhat|0.8.0|;

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by DHainzl** [comment]
Hi @bpasero,

Thanks for your reply! I actually _did_ use the search function, but couldn't find anything (I found some tickets related to scrolling but not to closing tabs) ... can you please point me to the ticket which this one duplicates? Maybe I've just used the wrong keywords :)

Thanks!

**Comment by bpasero** [comment]
@DHainzl https://github.com/Microsoft/vscode/issues/11928

**Comment by DHainzl** [comment]
@bpasero Aahh, I see ... that ticket does only include the keyboard event, but not the mouse event, that's why I couldn't find it :) Thanks! I will add a comment to that ticket to document that this does not only affect Cmd+W but also the middle mouse click.
