### ISSUE TITLE
Emmet 2.0: wrap lines with list broken

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31814]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.1
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. create a bunch of lines that you want to be a bulleted list, or paste a bulleted text list like I did, in this format:
````
• lorem ipsum
• lorem ipsum
• lorem ipsum
````
2. select the block and use the "Emmet: Wrap with abbreviation" command
3. Issue the command `ul>li*|t`
4. you get an error: 

````
Failed to expand abbreviation
e.doShow @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
````

This command, in Emmet 1.0, would wrap the lines with a list and remove the bullets, as in 

````
<ul>
    <li>lorem ipsum</li>
    <li>lorem ipsum</li>
    <li>lorem ipsum</li>
</ul>
````

**Comment by ramya-rao-a** [comment]
What filter is the `|t` at the end of your abbreviation? Is there any documentation on that?

**Comment by ramya-rao-a** [comment]
Ah! Never mind. Found it here: https://docs.emmet.io/actions/wrap-with-abbreviation/

**Comment by ramya-rao-a** [comment]
wow.. I just scrolled down that page (https://docs.emmet.io/actions/wrap-with-abbreviation/) didn't know the wrapping feature has so many more features. I just thought the first demo was the one!

It sure is complicated to implement all that in the current model.

@sergeche The wrap with abbreviation feature is not yet in the new atom plugin in.... Do you plan to implement it keeping parity with current set of features?

**Comment by sergeche** [comment]
Will implement it for sure but first I have to experiment with better UI/UX for it to provide instant feedback on wrapped result

**Comment by sergeche** [comment]
All the Wrap with Abbreviation features are already implemented in Emmet 2

**Comment by ramya-rao-a** [comment]
I know you have the support via the `text` option in the `expand` method from the `expand-abbreviation` module, but its not surfaced as a command in the atom beta plugin correct?

**Comment by sergeche** [comment]
No command yet because of absent UI/UX concept

**Comment by ramya-rao-a** [comment]
The main issue here is that the Wrap command doesn't make use of implicit repeaters (`*` without the number) and so individual lines do not get wrapped.

Logged https://github.com/Microsoft/vscode/issues/31893 for the trimming part of this issue.

With https://github.com/Microsoft/vscode/commit/211ffdf184329179ddca9c1fe993f5f11f3c4dda there will be a new command `Emmet: Wrap individual lines with abbreviation` that can be used for https://docs.emmet.io/actions/wrap-with-abbreviation/#wrapping-individual-lines

Reason for creating new command instead of re-using existing wrap command is that the `Wrap with Abbreviation` command makes use of `$TM_SELECTED_TEXT` and does not really pass the individual lines to the [expand](https://github.com/emmetio/expand-abbreviation) module.

We make use `$TM_SELECTED_TEXT` so as to take advantage of all the indenting support we get out of the box for snippets.

**Comment by ramya-rao-a** [comment]
And @smlombardi, nice find!

**Comment by smlombardi** [comment]
I use that Emmet feature all the time to take lists from manuscript and make html lists out of them quickly.  Without this feature working, I have to open the file in Sublime just to do this.  Still faster than any other way of making a list.

**Comment by smlombardi** [comment]
It works, except the `|t` does not work.

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/31893 has been logged for the `|t` part of the issue

**Comment by ramya-rao-a** [comment]
Note to verifier:

Use the new command `Emmet: Wrap individual lines with abbreviation` and verify it works as described in https://docs.emmet.io/actions/wrap-with-abbreviation/#wrapping-individual-lines

**Comment by sergeche** [comment]
As I mentioned earlier, filters are deprecated in favour of expand options. In this case, you have to simply remove list markers in lines before sending it to expand abbreviation function
