### ISSUE TITLE
Search viewlet searching opened files regardless or include and exclude patterns

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#31819]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:16:44.254Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.3.2
seti-icons|qin|0.1.3

(1 theme extensions excluded)

---

Testing #31480

Searching https://github.com/sourcelair/xterm.js, notice that dist is excluded in settings, I have an explicit include setting, but because dist/xterm.js is opened (not active) search results are still presented.

![image](https://user-images.githubusercontent.com/2193314/28836868-879095e4-769f-11e7-8aba-b2a9731d0a10.png)

**Comment by roblourens** [comment]
I did miss a case

**Comment by Tyriar** [comment]
This is also causing the results to look particularly confusing when there actually are results:

![image](https://user-images.githubusercontent.com/2193314/28836966-f89befea-769f-11e7-88a5-ead2044230a3.png)

Notice that the other results are in ./src but it's not shown next to the files because there's an assumption that only 1 folder is showing.

**Comment by mjbvz** [comment]
I'm still seeing results from non-active opened files returned even though they are excluded from `search.exclude`:

<img width="1000" alt="screen shot 2017-08-04 at 11 53 01 am" src="https://user-images.githubusercontent.com/12821956/28982680-9371e390-790b-11e7-9363-48852b87ee4b.png">


@roblourens  Are these the correct test steps?

**Comment by jpike88** [comment]
This is driving me insane! It renders search almost unusable... this should be a priority bug fix!

![screen shot 2018-01-25 at 4 20 24 pm](https://user-images.githubusercontent.com/9585787/35380392-b25f9a2c-01eb-11e8-9c83-f2cc3a574a56.png)

**Comment by alvipeo** [comment]
Guys, can you please fix this? It searches within node_modules in my angular app even if I exclude it!!! You can imagine what a mess it shows as a result!

**Comment by xsburg** [comment]
For those who come across this thread like I did.
Double check that the cog icon is enabled like in the picture below. When disabled, the search mechanism disregards the settings and goes over all directories. Solved the problem for me.

<img src="https://user-images.githubusercontent.com/830824/37913087-b8394cc6-311c-11e8-9028-c8d1a9c33c94.png" width="50%" height="50%">

**Comment by gdlx** [comment]
Same problem here with files excluded in `.gitignore`. The cog icon is checked (when unchecking it, I get far more results from log directory):

![image](https://user-images.githubusercontent.com/1533042/53239448-5b88c980-369c-11e9-8e5e-acde84a97187.png)

When adding `**/.terraform` in `search.exclude` (my current workaround), I don't get results from this directory.

VSCode 1.31.1
Windows 10 1803

**Comment by graph** [comment]
same problem if you just list directories to exclude in the exclude list below the search box. This bug should have higher priority. Search filtering is very important for navigating.

**Comment by akbyrd** [comment]
This is super frustrating.

**Comment by tudor07** [comment]
This issue is really 3 year old?

**Comment by tudor07** [comment]
`**dist/`did not work for me but `dist/**` did

**Comment by tokomeno** [comment]
3 years past after the issue has been opened and still not fixed :(

**Frustrating**

**Comment by sujithmathewthomas** [comment]
Any luck on this?

**Comment by gigitux** [comment]
Same problem here

**Comment by braddialpad** [comment]
Man I just spent over an hour trying to figure out why my package-lock.json kept getting included in search when I had it specifically excluded in settings. Then I found this bug.. yeah I had it open.

**Comment by julee** [comment]
Five years past. Any help can I provide to resolve this issue. It's troublesome.

**Comment by glasser** [comment]
I don't suppose anyone has found a workaround?  eg, I'd use an extension with a "close editors associated with `search.exclude`d files" command...

**Comment by abyrd-phx** [comment]
There's a related but different feature request to ignore opened editors entirely here https://github.com/microsoft/vscode/issues/153747 if folks following this thread are looking for that behavior as well.

**Comment by dizys** [comment]
How is this still an issue?!? 😫

**Comment by andreamah** [comment]
I believe this is fixed.
<img width="880" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/cd38149d-cc94-42be-b064-1eff9cc4130a">

Notice that the results from `notebook.css` are not appearing in the search results.
