### ISSUE TITLE
F12 to jump to definition when a webpack context is set up blocks jumping to definition

### ISSUE THREAD

**Issue by PaulInglis** [Microsoft/vscode#31813]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.7
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-close-tag|for|0.4.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-language-babel|mgm|0.0.7
csharp|ms-|1.11.0
autoimport|ste|1.2.2
react-redux-es6-snippets|tim|2.1.0
sort-lines|Tyr|1.3.0
markdown-all-in-one|yzh|0.8.1
html-css-class-completion|Zig|1.8.0

---

This may well have something to do with the set up of my project.

If I set up a context configuration in webpack and remove relative ../../ parts of imports I find I cannot navigate to definitions via the gift of the F12 button.

Steps to Reproduce:

1. Create a new project
2. Create a folder called src, then in that folder create a folder called components. In this folder create a file in it with a basic "hello world" component.
3. Create another file which imports that component, but make sure that the import name is 'components/HelloWorld'
4. Set up a webpack.config file to have context set to the src folder: `context: path.join(__dirname, './src'),`
5. Build the project - it will build and it will run, but when you try to navigate to the code via the F12 button, an "No definition found for <last part of file path>" error is shown.

Error shown
![f12 bug](https://user-images.githubusercontent.com/3604276/28831484-950b531c-76d1-11e7-9b40-7b61fe6c6384.png)

Actions folder (files does exist in that location)
![actionsfolder](https://user-images.githubusercontent.com/3604276/28831493-99fda348-76d1-11e7-96be-a1c21c4333ce.PNG)

Webpack context section
![projectcontext](https://user-images.githubusercontent.com/3604276/28831654-12a92376-76d2-11e7-92e7-b22daa348459.PNG)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Try creating a [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig#_what-is-jsconfigjson) file at and configuring it as described in our documentation: https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases

I don't think you even need the `paths` part if you are just using the folder names. Setting the `baseUrl` should be enough
