### ISSUE TITLE
Can we present multiple search results on the same line more effectively?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31817]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:16:44.254Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.3.2
seti-icons|qin|0.1.3

(1 theme extensions excluded)

---

Testing #31480

(I may have created an issue similar to this before)

It's always annoyed me the same line shows up multiple times in the search results, even when the line is really small and would fit in the viewlet just fine. Consider this example where the first line is complete:

![image](https://user-images.githubusercontent.com/2193314/28835792-7c2ecd1e-769b-11e7-8283-d6ec46cb9ece.png)

This would be better ideal in this case (I modified the DOM):

![image](https://user-images.githubusercontent.com/2193314/28835931-f4940c74-769b-11e7-87ef-17e9044ab191.png)

I understand the argument against this, where really long lines cannot show multiple results like this. Maybe we can size the search results to suit the width of the search viewlet, re-laying out the results when the viewlet is resized?

---

Here's the extreme case illustrating the issue:

![image](https://user-images.githubusercontent.com/2193314/28836054-59be6df6-769c-11e7-8414-44cb2c240cd1.png)

**Comment by Tyriar** [comment]
It's worth pointing out that the proposed solution would make it more in line with how search results are presented in the editor as well:

![image](https://user-images.githubusercontent.com/2193314/28836175-c16c8550-769c-11e7-9811-133d7612a66d.png)

**Comment by roblourens** [comment]
That would be cool but the viewlet is very narrow and rendering the tree takes a long time.

**Comment by roblourens** [comment]
I think most real world searches wouldn't benefit much. There are other issues for search viewlet UX in general though.
