### ISSUE TITLE
deleteWordLeft and deleteWordRight inconsistent on Windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31821]
#30276

Have 

```
 {
        "key": "ctrl+9",
        "command": "workbench.action.terminal.deleteWordLeft",
        "when": "terminalFocus"
    },

    {
        "key": "ctrl+0",
        "command": "workbench.action.terminal.deleteWordRight",
        "when": "terminalFocus"
    }
```

ctrl+9 should delete back, but inserts `^W`
ctrl+0 should delete right, but inserts `D`

**Comment by Tyriar** [comment]
@roblourens does it work using the normal keybinding but not this one? If so, what shell are you using?

**Comment by roblourens** [comment]
ctrl+delete works but ctrl+backspace doesn't, probably because of Parallels, so I'm trying in remote desktop. cmd.exe

**Comment by roblourens** [comment]
Actually it's just inconsistent in general, I'll just use this issue to write out the status...

** Win10 (Parallels) **
- Powershell
  - ctrl+delete works
  - ctrl+backspace does a single backspace
  - With custom bindings, `deleteWordLeft` inserts `^W`, and `deleteWordRight` inserts `D`
- cmd
  - ctrl+delete has no effect
  - ctrl+backspace does single backspace
  - With custom bindings, same as above

** Win7 (Remote desktop)
- Powershell
  - ctrl+backspace inserts `^W`, and ctrl+delete inserts `D`
  - Custom bindings => same as above
- cmd
  - Same as above

**Comment by csalv5** [comment]
Same here, using bash...any progress?

**Comment by Tyriar** [comment]
There isn't really anything that can be done here since we don't send keystrokes directly to cmd.exe but via winpty which takes a different format.
