### ISSUE TITLE
Terminal: Delete word right of cursor not working on fish shell

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#31823]
Testing #30276.

- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:10:12.703Z)
- OS Version: Linux x64 4.4.0-59-generic
- Extensions: none
---

Steps to Reproduce:

1. launch VS Code
2. open the integrated terminal
3. install fish
4. launch fish
5. enter `echo hello world`
6. <kbd>Ctrl+A</kbd> to jump with the cursor to the beginning of the line
7. <kbd>Ctrl+Delete</kbd> to delete `echo`
-> `D` is inserted before `echo`

**Comment by cleidigh** [comment]
Windows 7
Delete Left or Right do not work on cmd.exe

^W is emitted for Delete Left
D is emitted for Delete Right

**Comment by Tyriar** [comment]
alt+delete seems to work fine on macOS/fish, need to see what's going on with Linux.

**Comment by Tyriar** [comment]
fish uses different keybindings to bash https://github.com/fish-shell/fish-shell/issues/1047

This is probably best fixed via https://github.com/Microsoft/vscode/issues/11314 by allowing users to customize what keys send what control sequences
