### ISSUE TITLE
Single-click gesture to get rid of all custom keybindings

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#31826]
While testing #30276.

The keybindings editor should have a simple way to reset to the out-of-the-box keybindings.

Steps to reproduce:
1. From the command palette choose `Preferences: Open Keyboard Shortcuts`
2. Customize a key binding, save, close
3. Do something else
4. Try to undo your key binding change
-> You need to go to advanced settings to delete the blob of json.

We should have a single-click gesture to get rid of all custom keybindings.

**Comment by usernamehw** [comment]
I think this is a pretty narrow use case. 

Possible to do from extension (replace `keybindings.json` contents with `{}`)
Users accidentally executed that command will not be happy.
