### ISSUE TITLE
tsconfig build tasks does not list not excluded tsconfig

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31825]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:16:44.254Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #31232

Steps to Reproduce:

1. Turn off excluding a tsconfig by changing the setting to `false` (see screenshot)
2. Reload window to avoid #31822
3. That tsconfig is still filtered:
![image](https://user-images.githubusercontent.com/9205389/28838043-daa81c44-76a3-11e7-83fc-2e0994f24a44.png)

**Comment by mjbvz** [comment]
Hey @roblourens, using `vscode.workspace.findFiles` I don't see any results from files that are matched by the exclude pattern but marked `false`. I tried looking through the search code to determine why this is but got a little lost. Can you take a look?
