### ISSUE TITLE
"Run Build Task" first refuses to work then shows list of tsconfigs

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31820]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:16:44.254Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #31232 

Steps to Reproduce:

1. Open or reload workbench on a folder with tsconfig.json
2. "Run Build Task"
3. Unexpected:
![image](https://user-images.githubusercontent.com/9205389/28837051-3ca8a20a-76a0-11e7-986f-c784069987c9.png)
4. "Run Build Task" again
5. Now this shows the expected:
![image](https://user-images.githubusercontent.com/9205389/28837143-916e6310-76a0-11e7-836c-c881a2857341.png)

**Comment by mjbvz** [comment]
Fixed by 20519a8fe1fe565cd3a7618089beba6d66266b5b
