### ISSUE TITLE
Unexpected results when using / in include on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31824]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:16:44.254Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.3.2
seti-icons|qin|0.1.3

(1 theme extensions excluded)

---

Testing #31480

I say search in `./src` but it appears to be searching everything. Note that using include `.\src` works perfectly fine.

Single folder:

![image](https://user-images.githubusercontent.com/2193314/28837775-d626cb08-76a2-11e7-8574-53b188306df1.png)

Multi-root workspace:

![image](https://user-images.githubusercontent.com/2193314/28837862-2a30125e-76a3-11e7-93d2-8c0b1be8d8c9.png)

So there's two things here:

- Why is it searching everything when a folder literally named "./src" does not exist
- Maybe it would be best to assume `\` when `/` is used on Windows? This is what I do with links in the terminal, it's common for `/` path separators to show up on Windows. Personally I used `/` just now without even thinking about it because I jump around OS's all the time.

**Comment by roblourens** [comment]
In the first case, is there a folder named `src/` but it's searching everything? This works for me.

In the second case, it's ignoring it since a root folder with that name doesn't exist, but it should throw an error.

**Comment by Tyriar** [comment]
@roblourens in the first case: Yes there is a folder called "src" in one of the roots

**Comment by roblourens** [comment]
In one of the roots? I thought this was a single-folder workspace?

**Comment by roblourens** [comment]
I now show an error when using `./` for a root folder, when there isn't one with that name. Let me know if that's not what you meant.
