### ISSUE TITLE
Markdown security settings disables svgs from Travis and Appveyor

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#31837]
re https://github.com/Microsoft/vscode/issues/30879
 
I have following content in a markdown file

```
[![Join the chat at https://rubyide-slackin.azurewebsites.net](https://rubyide-slackin.azurewebsites.net/badge.svg)](https://rubyide-slackin.azurewebsites.net) [![Build Status](https://api.travis-ci.org/rubyide/vscode-ruby.svg?branch=master)](https://travis-ci.org/rubyide/vscode-ruby) [![Build status](https://ci.appveyor.com/api/projects/status/vlgs2y7tsc4xpj4c?svg=true)](https://ci.appveyor.com/project/rebornix/vscode-ruby)
```
* Preview
* It's saying some content has been disabled and none of these svgs is shown
* Switch back to the content, the editor hints that the first svg is not secure. However the latter two are travis and appveyor, which we should allow rendering

**Comment by mjbvz** [comment]
I believe this has been fixed in master. Please try out the next insiders build to confirm

**Comment by roblourens** [comment]
So these should now be visible on the second security setting, since they are svgs? That's what I see.

**Comment by roblourens** [comment]
On strict

![image](https://user-images.githubusercontent.com/323878/28946499-e97ffd5a-785f-11e7-8eb8-dbd5ab3b3c62.png)

**Comment by mjbvz** [comment]
Thanks @roblourens. I've opened #32001 to track this

**Comment by mjbvz** [comment]
To verify, either wait for the next insiders build or copy the `product.json` from insiders into your local build
