### ISSUE TITLE
Images in markdown preview are not always reloaded when increasing security setting

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31833]
Testing #30879

- Open the suggested cat markdown preview
- Change security setting to the most permissive
- Change security setting to "Strict"
- The https cat is not visible.
- But if I open the security picker and click "Strict" again, it shows up. Or if I just close/reopen the preview

**Comment by mjbvz** [comment]
I believe this has been fixed in master

Please try out the next insiders build to confirm
