### ISSUE TITLE
Terminal Switcher closes on Arrow key

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#31836]
While testing #31784.

- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Open 3 terminals
2. Select `Terminal: Switch Active Terminal` from the command palette
3. <kbd>ArrowDown</kbd> to the first terminal in the switcher
4. Move keyboard focus to rename action using 2 <kbd>Tab</kbd>s. See #31835.
5. <kbd>ArrowDown</kbd> to move focus to row below
-> terminal switcher closes. It should remain open and move the selection to the row below.

**Comment by Lixire** [comment]
Also an issue with tasks

**Comment by Lixire** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/32502
