### ISSUE TITLE
Indent rules don't work in PHP

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31838]
Testing #31831

Any basic PHP snippet

```php
if ($x) {
  $y = 1;
}
```

If I move the inner line up and down, the indentation rules are not respected. I think it worked at some point.

**Comment by jens1o** [comment]
Those were improved in #31786, where I had fixed some regex syntax errors, too. But @rebornix said that they are working(https://github.com/Microsoft/vscode/pull/31786#issuecomment-319221280). (I couldn't test them at this time, I must have been in bed.
