### ISSUE TITLE
The security level of markdown preview is not honored after refreshing the content

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#31839]
re https://github.com/Microsoft/vscode/issues/30879

I have following content in a markdown file 

```
[![Join the chat at https://rubyide-slackin.azurewebsites.net](https://rubyide-slackin.azurewebsites.net/badge.svg)](https://rubyide-slackin.azurewebsites.net) [![Build Status](https://api.travis-ci.org/rubyide/vscode-ruby.svg?branch=master)](https://travis-ci.org/rubyide/vscode-ruby) [![Build status](https://ci.appveyor.com/api/projects/status/vlgs2y7tsc4xpj4c?svg=true)](https://ci.appveyor.com/project/rebornix/vscode-ruby)
```

* Preview the content
* It's saying some content are not secure, none of the three image is shown
* Change the security setting to allow http
* All images are shown now. Click the title bar and the content gets refreshed.
* None of the images is shown and the alert is there again. Click on the alert, the quick pick pops up and it's saying current security level is `allow http` but it doesn't really work.

Maybe related to https://github.com/Microsoft/vscode/issues/31837

**Comment by mjbvz** [comment]
This should be fixed by a few changes I've made to the webview. Please try out the next insiders build which should have these fixes
