### ISSUE TITLE
Keybindings editor retains selection across instantiations

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#31830]
While testing #31784.

- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Select `Preferences: Open Keyboard Shortcuts` from the command palette
-> search box has the keyboard focus
2. Type `switch `
3. <kbd>ArrowDown</kbd> to `Switch Terminal`
4. <kbd>Enter</kbd> to set keyboard focus in this row
5. <kdb>Cmd+W</kbd> to close the editor
6. Select `Preferences: Open Keyboard Shortcuts` from the command palette
-> the first row has the keyboard focus instead of the search field

**Comment by sandy081** [comment]
Implementing #23543 fixes this behaviour.

Duplicates #23543

**Comment by kieferrm** [comment]
@sandy081 this is because in #23543 you would explicitly reset the selection when the editor is opened?

**Comment by sandy081** [comment]
@kieferrm In #23543 I will retain the filter, filtered results. Selection will be retained as it is now.
