### ISSUE TITLE
No error shown when typescript.tsdk points to invalid path

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31846]
Testing #31785

`/usr/local/lib/node_modules/typescript/bin2` doesn't exist.

But the version selector doesn't seem to mind

![screen shot 2017-08-01 at 11 44 43 am](https://user-images.githubusercontent.com/16890566/28841421-084f13e0-76af-11e7-9fe8-7c231e41a79a.png)

According to the below, it should fall back to the bundled one, but it doesn't

> Set typescript.tsdk to an invalid path. An error message should be shown and we should fallback to the bundled ts version

**Comment by mjbvz** [comment]
The currently behavior is that we only show an error when you try to pick that item. Do you see a warning message about using the bundled version of TS when you open a JS or TS file?

**Comment by ramya-rao-a** [comment]
Yes, I see the error after picking the item. But it is helpful if we can indicate something is wrong, before the user chooses the item.

One thing to do is when we can't figure out the version, then show a warning/message next to the label instead of showing the whole path again

![screen shot 2017-08-01 at 11 44 43 am](https://user-images.githubusercontent.com/16890566/28841421-084f13e0-76af-11e7-9fe8-7c231e41a79a.png)

**Comment by mjbvz** [comment]
Ok, here's the UI for presenting this as an error:

![screen shot 2017-08-01 at 1 29 18 pm](https://user-images.githubusercontent.com/12821956/28845605-790317fe-76bd-11e7-9940-204211280405.png)

**Comment by roblourens** [comment]
In 1.14 I got a warning popup when I set the tsdk path to something invalid, `The path /foo/bar doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.` In 1.15 I get the warning above, but not the notification. Is that expected? It seems worth a notification.

**Comment by mjbvz** [comment]
@roblourens It should still show the warning. Can we take a look at this?

**Comment by roblourens** [comment]
NVM, I do see it.
