### ISSUE TITLE
TS Version Selector shows wrong label

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31843]
Testing #31785

Followed these steps:

<img width="633" alt="screen shot 2017-08-01 at 11 35 38 am" src="https://user-images.githubusercontent.com/16890566/28840956-8452fbde-76ad-11e7-9d58-6241b1f2dd3a.png">

On new folder without user settings, version selector shows this

![screen shot 2017-08-01 at 11 37 25 am](https://user-images.githubusercontent.com/16890566/28841014-bba2b4f8-76ad-11e7-9d50-45c0630075ec.png)

On same folder with user setting `typescript.tsdk` pointing to a global TS, version selector shows this

![screen shot 2017-08-01 at 11 34 30 am](https://user-images.githubusercontent.com/16890566/28841003-adb15d0e-76ad-11e7-8934-40a4309dae90.png)

Both are labeled as `Use VS Code's version`
Shouldn't the former say "Use Bundled version"
and the latter say `Use configured version`?

**Comment by mjbvz** [comment]
I think we should keep the `VSCode's Version` bit for now but show a better path under it. Something like `Bundled Version`
