### ISSUE TITLE
Opening settings causes error

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31845]
- VSCode Version: Insiders dated August 1st 2017
- OS Version: Mac

I had user settings with a trailing comma, went to another active editor, hit `Cmd+,` to go back to the settings.

Got the below

![screen shot 2017-08-01 at 11 39 40 am](https://user-images.githubusercontent.com/16890566/28841243-718b351a-76ae-11e7-9cd2-da47dc451f15.png)
![screen shot 2017-08-01 at 11 40 02 am](https://user-images.githubusercontent.com/16890566/28841245-73dce87c-76ae-11e7-8e98-492f79ce14ec.png)

Cant reproduce again though

**Comment by ramya-rao-a** [comment]
Ok, now I have fixed the trailing comma, but I keep getting the same error as above when moving between another editor and the settings editor :(

The settings editor that is open, gets closed after showing the above error

**Comment by sandy081** [comment]
@ramya-rao-a Thanks for reporting it. Unfortunately I am not able to reproduce this issue. 

Let me know if you are still able to reproduce it? If so, it would be great if you can get more information from the dev tools which will be helpful to find out what is causing this. Thanks.

**Comment by ramya-rao-a** [comment]
What other info would you like from the dev tools other than the call stacks?

**Comment by sandy081** [comment]
Above call stack is not helping me to diagnose where the error is.. if you are able to reproduce, it would be very much helpful if we can debug and diagnose the root cause.

**Comment by ramya-rao-a** [comment]
I'll close it for now as I haven't see this issue in a while.
If I do again, then I'll re-open with more info if possible
