### ISSUE TITLE
The VSCode is showing a different file version if comparable with git version

### ISSUE THREAD

**Issue by renatobezerra** [Microsoft/vscode#31849]
This error occurs forever. The file is different of the last version in git.
I tried change the branch but don't works. If I open the same file in another editor, it works.

- macOS Sierra version 10.12.5 (16F73)
- git version 2.11.0 (Apple Git-81)
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-svgviewer|css|1.4.2
vue|liu|0.1.5
---

Steps to Reproduce:

1. Open project (in my case its cordova app).
2. Edit the project and commit this progress in git.
3. Change branch without VSCode, and continue to edit this project and commit the changes.
4. Returns to previous branch, and follow the step 3.
5. Compare the version files between VSCode and another Editor.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you share a screen recording?

**Comment by renatobezerra** [comment]
I'm so sorry. But I can't do this because I can't show this code.

**Comment by joaomoreno** [comment]
When you change the current branch without VS Code in step 3, does the branch name update in VS Code's status bar, on the left?

What exactly are you comparing? The right-hand side of the diff editor? The SCM viewlet contents?

Can you reproduce with another project for which you can record a screen recording?

**Comment by renatobezerra** [comment]
Yes. The branch name is updated.

I compare with VS Code and Sublime Text 3 or Vi. I open the project in VS Code like a normal edit, and make same in another editor.

In VS Code don't show diffs.

I will see if I reproduce this issue in another project.

**Comment by joaomoreno** [comment]
Please let me know if it repros in another project, and if so send us a screen recording.
