### ISSUE TITLE
List: onContextMenu  double event /popup 

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#31850]
Windows 7
Code 1.14.2
Insiders 8-1

Related/Expanded Issue #23614

Steps to reproduce: (note all operations by keyboard)

- open KeyBindings Editor
- Tab into key bindings list
- Arrow down several lines
- Use ContextMenu key (Shift-F10)

-PopUp menu appears and list entry jumps several lines up or  down
- Selecting Edit KeyBinding causes a second PopUp menu to appear
- If a new key binding is set, it will be applied to the entry after the jump

- After doing the above trying to edit again will cause the second pop up again but without list jumping

I would like to post a video if it will make it clearer can someone suggest a screen capture program especially that has good keyword activation ?

**Comment by cleidigh** [comment]
After getting some time on this and doing some debugging, I determined this issue lies in the list widget.
The onContextMenu event propagates twice causing a secondary popUp after the first.  Currently
this only appears to affect the keybindings editor.  Adding stopPropagation and preventDefault
to the event chain prevents this bug.

**Comment by cleidigh** [comment]
Fixed with PR #38843

**Comment by sandy081** [comment]
@cleidigh Thanks for the investigation and the PR.

**Comment by sandy081** [comment]
Assigning @joaomoreno

This is the same case in SCM view with multiple repositories.

**Comment by joaomoreno** [comment]
Closing as per https://github.com/joaomoreno/vscode/commit/a20fe8521d8ec7fb0ab7acc4841e6c9a1721e4e4
