### ISSUE TITLE
C/CPP should autoindent blocks without { }

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31857]
Testing #31831

In a case like 
```c
if (foo)
    x = 1
```

It doesn't autoindent the `x = 1` while typing or moving lines, but it does in TS.

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
