### ISSUE TITLE
Tasks in tsconfig.*.json files are not picked up

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#31858]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.1
sort-lines|Tyr|1.3.0
emojisense|bie|0.2.3
vscode-svgviewer|css|1.4.2
python|don|0.6.9
git-project-manager|fel|1.3.2
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
ayu|tea|0.4.0

(2 theme extensions excluded)

---

Testing #31232

This may only be true in a multi-root workspace context.

<img width="706" alt="screen shot 2017-08-01 at 1 33 44 pm" src="https://user-images.githubusercontent.com/2193314/28845826-1cb9ecba-76be-11e7-8180-c79bdc93860a.png">

**Comment by mjbvz** [comment]
@Tyriar I'm going to submit a workaround for this. Is it expected that you don't see a `create` event fired when using `createFileSystemWatcher` when a file is renamed though?
