### ISSUE TITLE
C/CPP should deindent preprocessor directives

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31856]
Testing #31831

I think it's fairly standard for preprocessor directives to be deindented

```c
int foo() {
    int x = 1;
#ifdef BAR
    return x;
#else
    return x+1;
#endif
}
```

But autoindent will put them at the same indentation level as the other code in the function body.

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
