### ISSUE TITLE
Pasting html double-indents second line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31868]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Testing #31831
Pasting into an empty html file, then formatting:
![pastehtml](https://user-images.githubusercontent.com/9205389/28847603-b106d65c-76c4-11e7-9282-c31d2bcff7ab.gif)

It might make sense to align with the formatter's result. Maybe just run the formatter when the file's content is replaced?

**Comment by chrmarti** [comment]
The clipboard has the tags without indentation:
```html
<html>
<head>
</head>
<body>
</body>
</html>
```

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/32320 which has a lot of user inputs there. This case will be considered as well .
