### ISSUE TITLE
Multiline start tag: End tag double outdented

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31869]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Testing #31831

Inserting the `>` of the closing tag:
![closingdivdoubleoutdent](https://user-images.githubusercontent.com/9205389/28848161-cbef078a-76c6-11e7-8998-77a041ff178b.gif)

Text:
```html
<html>

<head>
</head>

<body>
    <div data-foo="abc"
            data-bar="def">
        abc
        </div
</body>

</html>
```

**Comment by rebornix** [comment]
This issue is talking about indentation of multiple line expression, which shares the same root cause as https://github.com/Microsoft/vscode/issues/30859, let's track it there. Thanks @QwertyZW for doing the investigation into the solution for this problem.
