### ISSUE TITLE
unresolved markdown link in IntelliSense description for ExtensionContext.globalState

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3186]
unresolved markdown link in IntelliSense description for ExtensionContext.globalState, see:

![image](https://cloud.githubusercontent.com/assets/1487073/13192991/ea2cd8f8-d726-11e5-87bb-1bd4d4f6e78b.png)

**Comment by joaomoreno** [comment]
Definitely not a bug, but big feature work. Maybe create a story for this?
