### ISSUE TITLE
Terminal: Cannot rename task terminal

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31866]
testing #31784

ubuntu 16.04
Version 1.15.0-insider
Commit f39385b8326671dc6389f21f8c2e2f6afdb352a1
Date 2017-08-01T05:10:12.703Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

Start a task that runs in a terminal
`cmd+p` then `Terminal: switch active terminal`
Hover over the terminal that has a task
Click on the gear

result: nothing happens

I would expect to be able to rename it since it shows up in the list and I can rename the others.

**Comment by Lixire** [comment]
I think this is related to this https://github.com/Microsoft/vscode/issues/31859 .

**Comment by Lixire** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/31865
