### ISSUE TITLE
C/CPP doesn't adjust indentation on paste

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31860]
Testing #31831

Before:

```c
if (foo) {
  x = 1
}

if (bar) {
  y = 2;
}
```

Cut/paste the lower block below the `x = 1` line.

After:

```c
if (foo) {
  x = 1
  if (bar) {
  y = 2;
}
}
```

But if I move the `y = 2` line up and down, the indentation is correct

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
