### ISSUE TITLE
Move JS 'if' line in HTML wrongly indents

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31861]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Testing #31831

The Gif shows a single 'move line down':

![movejslineinhtml](https://user-images.githubusercontent.com/9205389/28846352-f3b98576-76bf-11e7-8cd6-548660b9e9b0.gif)

**Comment by rebornix** [comment]
Already fixed.
