### ISSUE TITLE
Show terminal name instead of number in command palette

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31863]
Testing #31784

Once I rename a terminal, I would like the commands `Terminal: Focus Terminal [blank-9]` to show the terminal name rather than the number.

![image](https://user-images.githubusercontent.com/1487073/28846701-3c0cd00c-76c1-11e7-9d70-1abbb6dcb4e7.png)

**Comment by Lixire** [comment]
This is what the terminal picker is supposed to cover

**Comment by chrisdias** [comment]
It seems redundant then to have these commands now that there is a better way to switch terminals.

**Comment by Lixire** [comment]
True

**Comment by chrisdias** [comment]
but we still have the number in the dropdown, so maybe it is ok. 

![image](https://user-images.githubusercontent.com/1487073/28850044-0f757392-76cf-11e7-93cf-9a7458220df6.png)

**Comment by Tyriar** [comment]
Focus terminal x commands are there so that people can bind them to cmd+x or whatever they want.
