### ISSUE TITLE
Open New Terminal does nothing

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#31862]
testing #31784

Ubuntu 16.04 LTS

Version 1.15.0-insider
Commit f39385b8326671dc6389f21f8c2e2f6afdb352a1
Date 2017-08-01T05:10:12.703Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

press `F1`
Choose `Open New Terminal`

Result: Nothing happens

**Comment by chrisdias** [comment]
`Terminal: Create New Integrated Terminal` works fine... what is `Open New Terminal` supposed to do?

**Comment by cleidigh** [comment]
@chrisdias 
cc @Tyriar 
Open New Terminal (Open New Command Prompt - on Windows)
Should open a separate terminal/command prompt process (eg outside Code)

Works as expected on Windows.

**Comment by chrisdias** [comment]
ya, my bad.  On Linux the external terminal doesn't open on top of the editor so I wasn't seeing it open.
