### ISSUE TITLE
VS on mac removes semicolon (;) when formatting javascript

### ISSUE THREAD

**Issue by erassynathingo** [Microsoft/vscode#31870]
My VS code removes the semicolon throughout my whole code  whenever i format. Please help, i cannot minify javascript code without semicolon

**Comment by kieferrm** [comment]
Any extensions you use? ES Lint for example?

**Comment by mjbvz** [comment]
Yes, our built-in JS formatter should never delete semicolons. Please try disabling some of your extensions to track down which one may be causing this

**Comment by erassynathingo** [comment]
i removed the plugins one by one, turns out it was TS-Lint...thanks @kieferrm
