### ISSUE TITLE
Moving line adds/removes unneeded indentation

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#31872]
Testing https://github.com/Microsoft/vscode/issues/31831 with Less

Before moving `#box {` :
![image](https://user-images.githubusercontent.com/13241824/28849796-a83e71a2-76cd-11e7-8fb5-46f7839e1d5d.png)
After:
![image](https://user-images.githubusercontent.com/13241824/28849809-bac358ce-76cd-11e7-8383-5a13b36dca8d.png)
Expected:
![image](https://user-images.githubusercontent.com/13241824/28849849-f6d97bcc-76cd-11e7-9438-6e28fd70d73a.png)

--- 
Before:
![image](https://user-images.githubusercontent.com/13241824/28849876-1463faf0-76ce-11e7-9ed7-b0831e5d7e0e.png)
After:
![image](https://user-images.githubusercontent.com/13241824/28849881-22047bbc-76ce-11e7-9fc7-d9dfe9ebbe9e.png)
Expected:
![image](https://user-images.githubusercontent.com/13241824/28849888-2c53d7ca-76ce-11e7-8073-50c7cc2a0943.png)

**Comment by rebornix** [comment]
@Lixire dup of https://github.com/Microsoft/vscode/issues/31867, already fixed. Thanks!
