### ISSUE TITLE
git.defaultCloneDirectory doesn't handle '~' for home directory well

### ISSUE THREAD

**Issue by flipphillips** [Microsoft/vscode#31878]
- VSCode Version: Code - Insiders 1.15.0-insider (f39385b8326671dc6389f21f8c2e2f6afdb352a1, 2017-08-01T05:07:59.267Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
latex-workshop|Jam|3.1.2
code-settings-sync|Sha|2.8.2
project-manager|ale|0.18.1
githistory|don|0.2.2
python|don|0.6.9
gitlens|eam|4.3.3
git-project-manager|fel|1.3.2
sftp|lix|0.7.7
vscode-zipexplorer|sle|0.2.0

---

Steps to Reproduce:

1. set git.defaultCloneDirectory ala
`"git.defaultCloneDirectory": "~/GitHub"`

2. checkout repository

Expected result:

1. git clone to home directory/GitHub
2. proper opening of folder/project w/ VSC

Actual result:

1. checkout goes to the ether somewhere
2. when saying 'OK' to open the project an error appears saying "/~/GitHub" does not exist (which, of course, it shouldn't)

Regression:

The main reason I'm doing this is because I like to share my settings across machines where each has a different users directory (e.g., `/usr/flip` on unix boxes, `/Users/flip` on macOS, etc.

Alternately, some sort of HOME directory token might make sense? $HOME or some such?

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Would you like to submit a PR?

**Comment by dericcain** [comment]
@joaomoreno I would like to help with this. It will be my first time contributing to this project, so I may have some questions. I'll read over the contributing guide and get started.

**Comment by dericcain** [comment]
@joaomoreno I have [committed a fix in my fork](https://github.com/dericcain/vscode/commit/209afc6c7a203951ab50e94c1acecd6bc1c1aa25?diff=unified), but I cannot figure out where I should add a test for it. I looked [here](https://github.com/Microsoft/vscode/blob/master/test/smoke/src/tests/git.ts) but that doesn't seem like it's the correct place for it. Can you point me in the right direction?

Also, if you have any suggestions on the fix, I would love that as well. Thanks for your help!!

**Comment by joaomoreno** [comment]
We don't have a good enough test bed set up for you to write tests on, unfortunately.

Feel free to submit that PR.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/32222
