### ISSUE TITLE
FileSystemWatcher API to handle changes to files.exclude?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#31882]
From:
https://github.com/Microsoft/vscode/issues/31825
https://github.com/Microsoft/vscode/issues/31822

**Problem**
The `tsconfig.json` build task provider currently detects `tsconfig.json` files in the workspace using `findFiles` on first run and then using a `FileSystemWatcher` after wards to keep the list of  `tsconfig.json` up to date. This approach does not handle changes to `files.exclude` properly.

My current workaround is to only rely on `findFiles` to pick up the configs. I'm not sure if this will cause performance issues for very large workspaces for users on HDDs compared to the mixed find and watcher approach.

**Questions**
- Will `findFiles` be fast enough on its own for this scenario? I've done basic testing and it seems quick
- Would there be any other extensions that could benefit from understanding when a file is excluded or included? Should there be an official API for this?

**Comment by bpasero** [comment]
I would stay away from a solution that is calling `findFiles` constantly and rather use the solution of doing an initial scan once and then relying on the file watcher. 

I wonder if we should have an option to respect the files.exclude setting when calling into the file watcher and then leaving out those changes. Or, provide an overload where you can pass in glob patterns to ignore (this would then mean you have to resolve the patterns from the `files.exclude` setting first and pass it over).

/cc @jrieken

**Comment by jrieken** [comment]
> I wonder if we should have an option to respect the files.exclude setting when calling into the file watcher and then leaving out those changes.

The `files.exclude` really seems like a UX setting and not something fundamental to the API. @bpasero Doesn't glob support negations as we use it our build scripts?

**Comment by bpasero** [comment]
Yes, normal glob patterns support negations, while the "simple" glob implementation that we have in our core is not supporting that.

**Comment by joaomoreno** [comment]
I just hit a similar issue. The `findFiles` API respects the settings as well, so I can't go looking for folders called `.git` in the user's workspace folders. :cry: cc @roblourens

**Comment by jrieken** [comment]
Not cool

**Comment by bpasero** [comment]
@roblourens didn't you make the search viewlet support the case where an include pattern overrules a possible exclude pattern? Is that only for ripgrep?

**Comment by jrieken** [comment]
I'd say that is a regression from https://github.com/Microsoft/vscode/commit/d618f0da, because `extendQuery` simply adds exclude params. I'll extract this to another issue

**Comment by bpasero** [comment]
Ok I was not aware the previously we would not add the standard configured excludes to this API call.

**Comment by jrieken** [comment]
Yeah, at least that is my firm believe. The change added the `extendQuery`-call, unless that was extracted from the `search`-call (which I don't think)...

**Comment by roblourens** [comment]
The `extendQuery` call was put there because I removed it from `SearchService.search`. Are you sure it didn't use those excludes previously? Here is a point when it was still there: https://github.com/Microsoft/vscode/blob/3800e5ec4074e1d8510037f8ce8f2b746ac48940/src/vs/workbench/services/search/node/searchService.ts#L63

**Comment by roblourens** [comment]
> @roblourens didn't you make the search viewlet support the case where an include pattern overrules a possible exclude pattern? Is that only for ripgrep?

That didn't really pan out

**Comment by jrieken** [comment]
> Are you sure it didn't use those excludes previously?

Not sure, it is some years ago... I believe it shouldn't pick up the defaults without users opting in to it...

**Comment by roblourens** [comment]
In 1.14.2, I see it using these by default. I don't think we should search .git and node_modules by default, because that can take a long time. But I'm open to providing a way to turn that off or override it.

**Comment by bpasero** [comment]
I also think we should be careful about changing the defaults. @roblourens are we using ripgrep for the findFiles call or our old slow find mechanism?

**Comment by jrieken** [comment]
@roblourens @bpasero Please discuss `findFiles` issues here: https://github.com/Microsoft/vscode/issues/33528. This item is about file watching.
