### ISSUE TITLE
TS Version Selector does not update path and label from user settings

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#31888]
Testing #31785

1. Set `typescript.tsdk` to an invalid path in user settings (I set it to `"typescript.tsdk": "potato"`). An error message is shown when selected and we fall back to the bundled ts version
2. Run `npm install typescript`. Version selector now has two entries
3. Remove user setting and revert `typescript.tsdk` to null.

The version selector still contains the old invalid path and label, even when the user setting is deleted or updated to match the default. Also occurs even if local TS is not installed.
![image](https://user-images.githubusercontent.com/7109548/28855859-568df4b4-76f4-11e7-8cb6-9bc33c9f565e.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this in the current build from master. Can you double check that you saved and closed the settings file
