### ISSUE TITLE
Files starting with hexadecimal numbers are sorted in no apparent order

### ISSUE THREAD

**Issue by texonidas** [Microsoft/vscode#31887]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.7
vscode-eslint|dba|1.2.11
python|don|0.6.9
docthis-customize-tags|dwe|0.4.5
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
json2ts|Gre|0.0.6
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
vscode-angular-components-intellisense|ipa|0.6.8
angular-essentials|joh|0.2.0
Angular2|joh|2.4.0
StretchTimer|jpa|0.0.1
MagicPython|mag|1.0.11
HTMLHint|mka|0.3.3
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.1.7
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.0.11
vscode-icons|rob|7.12.0
stylelint|shi|0.28.0
addDocComments|ste|0.0.8
react-redux-es6-snippets|tim|2.1.0
gitblame|wad|2.0.2
jinja|who|0.0.8

Using Alembic (Python db migration framework), migration scripts are generated with a 12 digit hexadecimal number, followed by the commit name of the migration. They appear in an order that generally trends downwards, however they appear to be in no real order. I have included file list for reproduction.

---

Steps to Reproduce:

1. Create the following files:
04f48d644b92_add_reference_check_and_file_upload.py
06765d43a5b3_configure_linkedin_signups.py
079f290a1d33_switch_share_from_employers_to_role.py
0d01ac3011d8_add_job_desc_filepath_to_role.py
105bce8204c5_add_rejected_flag.py
1141676c672d_make_critical_columns_longer.py
2051ebc8ef4b_add_memberships_to_database.py
26d685b1579b_make_image_longer.py
298017f90fa3_convert_interested_and_selected_to_.py
2ced02fdbef7_add_enumerated_types_to_reminders_and_.py
2d901c65f142_add_periodic_reminder_emails.py
30e83583d989_add_final_hire_info_to_role.py
325bb7c14659_add_referral_table.py
333bf14c4399_update_submission_table.py
42df4be05333_expand_lead_object.py
616a0cb69972_update_booleans_to_datetimes.py
6543b2a364f0_add_stats_table.py
671deffc4e66_add_interview_times_to_submissions.py
6b4109628d87_add_lead_table.py
70a8068070f3_add_placed_by_us_flag_to_role.py
73aa256719ad_add_country_id_to_employer_too.py
73eeb5ef831c_change_candidate_to_name_in_submissions.py
75424c2301b8_convert_edited_field_to_text.py
7574b03ed9c9_add_review_table.py
79649f18d8d7_remove_deadline_email_column.py
8183efb149ab_update_role_to_new_model.py
9c4f0441eff2_add_confirm_and_no_confirm_migration.py
9cffa25ee8b6_add_single_primary_key_id_to_role_agents.py
9e1e408070df_add_role_and_agent_back_to_submission.py
9f69e7802a0b_add_recommended_to_bids.py
a63fadfece67_update_length_of_resume_and_cover_.py
a8b65fac38d0_extend_allowable_role_name_length.py
b07cce7fe3c5_remove_selected_from_reminder_enum.py
c2605f3b9180_add_a_million_things_for_candidate_.py
cf7c604a5302_increase_reminder_frequency_precision_.py
d0440c7f1297_add_regions_countries_and_add_regions_.py
db0845f3aa97_improved_precision_of_frequency.py
e14207c47b0d_add_counter_offer_files.py
ea225036f367_convert_ref_check_to_datetime.py
eb9f5df4654a_add_file_upload_list.py
fd8996b0be5f_add_image_column_to_agent_table.py
fe14d0fbc176_add_nps_to_role_object.py

2. Open the folder in Visual Studio Code.

Reproduces without extensions: Yes

**Comment by texonidas** [comment]
I have just identified that it is only reading the numbers at the start of the hex string and ordering it by those instead. If this is the intended behaviour then this issue can be closed, however I'm not sure where this would be the preferred behaviour over ordering it by the entire string.

**Comment by kieferrm** [comment]
The strings are sorted lexicographical. Since no number appears twice you get the impression that only the number is considered.
