### ISSUE TITLE
I cant update visualstudio code in MacbookPro

### ISSUE THREAD

**Issue by qiansheng2** [Microsoft/vscode#31886]
- VSCode Version:
    1.14.1
- OS Version:
    macOS sierra
Steps to Reproduce:

1.open 1.14.1
2.select update

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
@qiansheng2 does your account has the rights to modify the files of VS Code? For example, when you installed VS Code in `Applications` which requires admin rights and your account does not have admin rights by default, you would see issues with update.

**Comment by carlosvigil** [comment]
@kieferrm That seems to describe my situation. How is it resolved? The issue is that it continues to ask for updates even when "About" reports the latest version.

**Comment by kieferrm** [comment]
The About dialog shouldn't report the latest version if the update fails. @joaomoreno thoughts?

**Comment by joaomoreno** [comment]
It does report the latest version, but not the same commit ID, which for us means a different version.

https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
