### ISSUE TITLE
Unable to connect after a disconnect. Need to restart Visual Studio Code to get a connection again

### ISSUE THREAD

**Issue by TheDenverNaidoo** [Microsoft/vscode#31885]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.4|
|EditorConfig|EditorConfig|0.9.4|
|Angular-BeastCode|Mikael|4.3.2|
|vscode-html-scss|P-de-Jong|0.0.42|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|angular-productivity-pack|devboosts|1.6.0|
|tslint|eg2|0.17.0|
|auto-close-tag|formulahendry|0.4.3|
|auto-rename-tag|formulahendry|0.0.14|
|angular-bootstrap|herrherrmann|4.0.6|
|githd|huizhou|0.2.2|
|angular2-switcher|infinity1207|0.1.4|
|vscode-angular2-emmet|jakethashi|2.0.3|
|Angular2|johnpapa|2.4.0|
|mssql|ms-mssql|1.1.0|
|angular2-inline|natewallace|0.0.17|
|vscode-css-peek|pranaygp|1.3.1|
|vscode-icons|robertohuertasm|7.12.0|
|html-snippets|wgenial|0.1.5|;

---

Steps to Reproduce:

1.
2.

**Comment by kieferrm** [comment]
@TheDenverNaidoo pls provide steps for reproduction. Thanks!

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
