### ISSUE TITLE
Extension: does the contribution explorer view provide collapse/expand events

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#31883]
- VSCode Version: V1.14.2
- OS Version: Win10 64-bit

Steps to Reproduce:

1. Follow an example from https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample to provide a tree view contribution to explorer
2. Add icons to the views, want to provide different icons based on the status of collapse. 

Issues: 
Cannot find an expand/collapse event.

**Comment by sandy081** [comment]
@yaohaizh No.

You can only contribute data provider through VS Code API. There are no UI gestures propagated.
