### ISSUE TITLE
Indentation Lost When Paste to Other Application

### ISSUE THREAD

**Issue by frankyuan** [Microsoft/vscode#31889]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.9.0

When I copy and paste the code to evernote, the indentation lost.

---

Steps to Reproduce:

1.Copy code from vscode
2. Paste to evernote

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Let's track this in https://github.com/Microsoft/vscode/issues/31829 . This is because that we use non-break-spaces in html but they are not being rendered as expected in some applications, we probably want to think about what we want to use there.
