### ISSUE TITLE
Linting Node_Modules Folder

### ISSUE THREAD

**Issue by ModernWebService** [Microsoft/vscode#31881]
Love using VSCode, however, in a recent Laravel project I installed a few dev tools with npm and once I have the project open in vscode my errors and warning panel shows 99+ for both and shortly after spins up the fan. The computer is a spec'ed out mbp 2015 model from 2016, so I am doubting the issue is hardware related. Curious if there is a way to ignore the node_modules folder in the linter as I do not plan on using any of the tools i installed in the local version for the remote version.

- VSCode Version:1.14.2
- OS Version: OSX 10.12.6

**Comment by mjbvz** [comment]
Which linting extension are you using?

**Comment by ModernWebService** [comment]
I have js standard lint, python linter, jshint, and eslint. Other than that
for php I have the crane extension. My vscode setup is geared towards
angular, vue and laravel. Ony saw it start to lint node_modules in laravel
though.

I also had styelint installed at some point.

**Comment by mjbvz** [comment]
Please try filing this issue against whatever linter is going into the `node_modules` folder. The `files.exclude` setting should prevent `node_modules` from being picked up, but the individual linters may require different configurations to exclude a folder
