### ISSUE TITLE
The variable emmet always flashing

### ISSUE THREAD

**Issue by lagelalegal** [Microsoft/vscode#31884]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
swift|Kas|0.0.3
vscode-ava-runner|Kni|0.0.3
Angular2Tests|Mar|0.7.3
vscode-todo|Mat|0.8.0
vscode-docker|Pet|0.0.16
ejs-language-support|Qas|0.0.1
typescript-react-snippets|abo|0.2.0
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
django-snippets|bib|1.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
python|don|0.6.9
tslint|eg2|0.17.0
Python-autopep8|him|1.0.2
javascript-unit-test-snippet|iZD|1.0.0
vscode-angular2-emmet|jak|2.0.3
vscode-flake8|jay|0.0.4
docthis|joe|0.4.7
KiteCode|kit|0.1.0
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
seti-icons|qin|0.1.3
vscode-icons|rob|7.12.0
ava|sam|0.4.0
autoimport|ste|1.2.2
react-beautify|tai|0.3.0
python|tht|0.2.3
gitblame|wad|2.0.2
jira|web|0.1.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a constants file.
2. the variable always flashing when I move the mouse on hover it.
3. so, I want use `Cmd` + `leftclick` can't redirect the variable define.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
First, please make sure an extension is not causing this. Start code with the `--disable-extensions` command line flag to disable extensions

The issue is also unclear to me. Please provide some code examples and/or screenshots that show what is going wrong

**Comment by lagelalegal** [comment]
Ok, The issue no appearing agin when I restart vscode.
