### ISSUE TITLE
Search for ./ does not work properly with backslashes on windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31892]
Forked from https://github.com/Microsoft/vscode/issues/31824

`.\src` will not show only results in `src/`.

**Comment by Tyriar** [comment]
It appears to still be broken?

![image](https://user-images.githubusercontent.com/2193314/28886664-251b1a30-776f-11e7-94e4-32309fdedf1b.png)

The project has a src dir:

![image](https://user-images.githubusercontent.com/2193314/28886687-35c4856a-776f-11e7-80ec-bf08ed5fc335.png)

**Comment by roblourens** [comment]
It looks like it's showing results from just in src? `src/Renderer.ts`, `src/test/...`

**Comment by roblourens** [comment]
It doesn't repeat the full path on each line, which maybe you're expecting

**Comment by Tyriar** [comment]
Oh you're right, what threw me off was I searched "src" and then ".\src" and the results differed (the folder was different).
