### ISSUE TITLE
Emmet: Support the trim filter

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31893]
See https://docs.emmet.io/actions/wrap-with-abbreviation/#removing-list-markers

**Comment by jens1o** [comment]
Why did you removed the `emmet` label @ramya-rao-a making it hard to find?

**Comment by ramya-rao-a** [comment]
I think there was a race condition between me applying the labels "feature request" and "help wanted" and the bot applying the label "emmet".

**Comment by ramya-rao-a** [comment]
@sergeche can you point us to how you did this in the older emmet?

**Comment by ramya-rao-a** [comment]
Found it. Just regex. Should be simple to do. https://github.com/emmetio/emmet/blob/master/lib/filter/trim.js

**Comment by ramya-rao-a** [comment]
Done

**Comment by rebornix** [comment]
Not sure if I'm doing correctly but in the sample page I can wrap Abbreviation with filters by running 

```
ul>li*|t
```

or 
```
ul>li*|trim
```

However I can't do anyone of them in VSCode, it's saying "Failed to expand abbreviation"

**Comment by ramya-rao-a** [comment]
`|trim` was not a valid filter to begin with.
`|t` is the one to be used
