### ISSUE TITLE
Can we run multiple task in vscode?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#31890]
I have create a test runner in vscode that would run my engine for long long times and generate test result for million average

While it was run I still working on the same project and want to build/debug it in another module. But it seem vscode can run only one task at a time

I want to launch the tester I write to use env variable in tasks.json and still log output in the vscode while I edit and debug another part of code

How can I do? Should vscode able to run multiple task?

**Comment by kieferrm** [comment]
@Thaina yes, you can run multiple tasks at once. Pls see https://code.visualstudio.com/docs/editor/tasks. Please be aware that tasks before 1.13 where more limited.

**Comment by Thaina** [comment]
@kieferrm When I try to run multiple task I got this error

> There is a task run running. Can not run pre launch task build.

I don't want to run all the task at once. I want to run task in parallel. I want to run test task that last 1 hour and then I would run build task while the test task still running eventually

**Comment by kieferrm** [comment]
@Thaina you need to use version 2.0 of tasks. Pls change the version number in your `tasks.json` file:
```json
"version": "2.0.0"
```

Pls see https://code.visualstudio.com/docs/editor/tasks for how the format differs from the previous version.
