### ISSUE TITLE
CMD+` does not switch through open vs.code windows

### ISSUE THREAD

**Issue by yhaskell** [Microsoft/vscode#3189]
Also, there is no actual way to switch between different vscode windows on mac.

**Comment by egamma** [comment]
I thought I use CMD+` all the time, but I currently have no Mac with me to confirm.

**Comment by nisheetjain** [comment]
I can confirm that cmd+` does work to switch between different VS code windows..

**Comment by yhaskell** [comment]
Update: 
I've tried to reproduce.
This appears to happen only if windows are maximised. Otherwise everything works fine.
Is this is expected behaviour?

**Comment by joaomoreno** [comment]
This is OS behaviour.

**Comment by yukulele** [comment]
this occurs only when editor text is focus

**Comment by yukulele** [comment]
You can use <tt>cmd+alt+`</tt> to switch between different vscode windows on mac.
