### ISSUE TITLE
Adding of multiple cursor not working properly

### ISSUE THREAD

**Issue by sr08** [Microsoft/vscode#31897]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
open-html-in-browser|cod|0.1.21
beautify|Hoo|1.1.1
cpptools|ms-|0.12.1
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sr08** [comment]
Multiple lines selection is not working in a proper way. The shortcuts shown in the command plate changes the orientation of the window it self to upside down. Please resolve this issue.

**Comment by kieferrm** [comment]
@sr08 What locale are you on? What does the keyboard shortcut editor show you?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
