### ISSUE TITLE
Be proactive about defending against unauthorized telemetry collection

### ISSUE THREAD

**Issue by hach-que** [microsoft/vscode#31891]
In the past couple of weeks we've seen plugins in two popular editors taken over by a commercial entity, who has then added seemingly identifiable telemetry collection to those plugins:

- Atom (atom-minimap and autocomplete-python): https://github.com/atom-minimap/minimap/issues/588, summary: https://theoutline.com/post/1953/how-a-vc-funded-company-is-undermining-the-open-source-community
> Back to autocomplete-python. A number of developers who reviewed the tool found that the changes Kite made were far more invasive than what it had done to Minimap. The new version of autocomplete-python demoted the open source engine it had been using, called Jedi, and enabled Kite’s engine by default.
> 
> Kite’s engine required code be processed on Kite’s cloud server, while the previous version did this work on the user’s machine. This is a crucial difference because sending data to the cloud is a privacy issue, especially given the wide-ranging access permission requested by the tool. Developers said they worried that various scenarios could lead to medical data, payment data, and other data that should be kept private being uploaded to Kite. Furthermore, many private companies have policies against uploading data to third parties, which would make Kite unusable for developers at those companies.

- Sublime Text (SideBarEnhancements package): https://forum.sublimetext.com/t/rfc-default-package-control-channel-and-package-telemetry/30157, summary: https://www.reddit.com/r/programming/comments/6qwtfz/kite_injected_telemetry_into_the_third_most/dl0psv0/

With the revelation that this has not been limited to one editor, I think it's important that Visual Studio Code implements a proactive policy to either scan uploaded extensions for telemetry collection or sandbox extensions with a permissions system similar to Chrome Extensions / WebExtensions.

I realise that this is a significant undertaking, but with what's come to light in recent weeks, there's a non-zero chance that this is occurring in Visual Studio extensions as well, without user knowledge.

**Comment by seanmcbreen** [comment]
Thanks for bringing this up. This is definitely on our radar and we will investigate how we can protect VS Code extension consumer from such behavior. At this point in time we have no concrete plans yet other than that we are watching this issue very carefully.

Sean - VS Code Team Member

**Comment by Almenon** [comment]
How do you define what telemetry collection is good and what collection is bad? Telemetry is very useful towards extension authors. For me it's not about profit, it's about knowning when errors happen and being able to fix them asap.  If you're using a library like https://github.com/Microsoft/vscode-extension-telemetry it will automatically skip telemetry if the user has it disabled anyways.

**Comment by ShanConn** [comment]
"what telemetry collection is good and what collection is bad" anything that can be statistically used to personally identify users, such as geo-location, pieces of what they are writing, their machine data, feature usage, enabled settings, ab-experiments, enabled extensions, etc.

**Comment by ShanConn** [comment]
For example, we're seeing a lot of vscode engineers and contributors moving into adtechs and all sorts of weird privacy invasive companies. 

@RMacfarlane  contributes to https://github.com/adazzle
