### ISSUE TITLE
Wrong keyboard or shortcuts after starting VScode ?

### ISSUE THREAD

**Issue by Jimskapt** [Microsoft/vscode#31899]
Hello !

Sometimes (not systematic), when I start VS code, when I do a Ctrl+Z (undo) shortcut on my AZERTY keyboard, it is interpreted as a Ctrl+W (close tab).

I think there is an error on the keyboard mapping on shortcuts which will be as QWERTY.
There is no problems with my code, which is correctly writen with AZERTY keyboard.

My solution to fix it is to close and re-open VS code.

System informations :
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.12.3-1-ARCH (installed [AUR visual-studio-code](https://aur.archlinux.org/packages/visual-studio-code))
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-rust|kal|0.4.2
vue|liu|0.1.5
Go|luk|0.6.63
vetur|oct|0.9.3
vscode-icons|rob|7.12.0

I can't find a way to reproduce systematically the problem, sorry :-/
If you have an idea, i'll try !

Thank you !

**Comment by alexandrudima** [comment]
@Jimskapt Could you please go through our Linux Keybinding Troubleshooting guide and check if any of the cases apply to you -- https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings
