### ISSUE TITLE
[Debug] Continue one thread will cause other threads' stack frames lost in CallStack panel when debugging multi-threads

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#31896]
- VSCode Version: VSCode 1.14.0
- OS Version: Windows 10

We're developing java debugger, and found that VSCode debug panel will lose some threads' call stacks  for multi-threads case.

See the screenshot below. There are two breakpoints hitted simultaneously by different threads (Thread-0 and Thread-1), and VSCode CallStack panel could display their call stacks correctly. (Note: When the breakpoint was hitted, i send a StoppedEvent with flag allThreadsStopped=false)
![image](https://user-images.githubusercontent.com/14052197/28860267-76f9cecc-778e-11e7-94a1-e8e20520c433.png)

Then i choose to continue Thread-0 (threadId is 444) first. Thread-0 completed as expected. But Thread-1's call stacks are lost in VSCode CallStack panel. The whole debug process hanging there. See the screenshot.
![image](https://user-images.githubusercontent.com/14052197/28860526-9b03293e-778f-11e7-8160-d59a542f4f47.png)
Below are the DA requests and responses after the continue operation.
[REQUEST]
{"command":"continue","arguments":{"threadId":444},"type":"request","seq":18}
[[RESPONSE]]
{"success":true,"request_seq":18,"command":"continue","body":{"allThreadsContinued":false},"seq":28,"type":"response"}
[[RESPONSE]]
{"event":"thread","body":{"reason":"exited","threadId":444,"type":"thread"},"seq":29,"type":"event"}

[Expected]:
Because Thread-1 is still suspended by breakpoint, VSCode is supposed to keep Thread-1's call stacks after Thread-0 continued and terminated.

**Comment by isidorn** [comment]
@testforstephen nice catch, we were not respecting the allThreadsContinued in the ContinueReponse.
I have puhsed a fix to my branch - you can expect the fix to land in insiders some time next week since we are now in endgame week and are only taking specific fixes.

**Comment by testforstephen** [comment]
@isidorn it's fixed in the latest 1.16.0-insider. thanks for the work.

**Comment by isidorn** [comment]
@testforstephen thanks, adding verified label since you checked it works
