### ISSUE TITLE
Missing file events when connected to mounted network drive

### ISSUE THREAD

**Issue by nguyenbathanh** [Microsoft/vscode#31908]
- VSCode Version: 1.5.3
- OS Version: Windows 7 Ultimate x64

Steps to Reproduce:

Open any file on sidebar, webpack detected change and re-compile but it didn't show any changes by git.

Video:
http://recordit.co/P5h9fY1bjp

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@nguyenbathanh does it reproduce if you set `"files.useExperimentalFileWatcher": true` ?

**Comment by nguyenbathanh** [comment]
@bpasero Yes, it is still happening with that flag enabled or disabled.
I'm sorry, I'm missing one point that I'm working with SFTP mounted as network drive, may it be the problem?

**Comment by bpasero** [comment]
@nguyenbathanh yes, we have some known issues around file watching via network drives.

**Comment by nguyenbathanh** [comment]
@bpasero Thank you for your helpful information.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/29807
