### ISSUE TITLE
Find in Files doesn't work normally,when "files.encoding" isn't 'utf-8'

### ISSUE THREAD

**Issue by easters14** [Microsoft/vscode#31903]
- VSCode Version: 1.14.2

Steps to Reproduce:

Here is my setting.json:

```
  "files.autoGuessEncoding": true,
  "files.encoding": "Big5-HKSCS"
```

and Find in Files didn't work normally, it can just find out the result which is in opening file,

 ```
  "files.autoGuessEncoding": true,

```
After I change setting, it become normally,
it seems like same problem as #31742.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
The problem with `big5-hkscs` is a typo on my part. But I should also point out that `files.autoGuessEncoding` isn't supported by search, because our search tool doesn't support autodetection of encodings.

**Comment by rebornix** [comment]
One thing I note here is to use `Big5-HKSCS `, the encoding setting name is `big5hkscs `

**Comment by roblourens** [comment]
Yeah there's a discrepancy between our setting names and the "canonical" names that ripgrep respects, which is why the function I changed in https://github.com/Microsoft/vscode/commit/e12b42560905f665719860c0a27ea28b977d0528 exists

**Comment by hackerick4** [comment]
Why search all function cannot work although I disabled encoding-autodetection ?
