### ISSUE TITLE
Go to definition stopped working completly

### ISSUE THREAD

**Issue by dreszczyk** [Microsoft/vscode#31909]
- VSCode Version: 1.14.2
- OS Version: Ubuntu 17.10

Steps to Reproduce:
1. Open .jsx file
2. Ctrl + click on variable is not working

Reproduces without extensions: Yes

**Comment by Jeyanthinath** [comment]
Try restarting the vscode more than one time and wait for some time and then try 

**make sure than multi-cursor  opiton is disabled**

**Comment by dreszczyk** [comment]
I disabled the multi-cursor and it's working, but not as expected. It goes to import declaration instead of opening file with the definition.
Please check this gif:
![peek 2017-08-02 15-28](https://user-images.githubusercontent.com/5095527/28875921-a4e041e6-7797-11e7-83b6-a28d6a56c1cb.gif)

**Comment by Jeyanthinath** [comment]
Can you reply what are all the extensions you are using related to javascript @dreszczyk

**Comment by mjbvz** [comment]
I'm unable to reproduce this with TS 2.4.2 (the default version for VSCode 1.14)

@dreszczyk Can you please share a minimal code example that demonstrates this problem

**Comment by dreszczyk** [comment]
@Jeyanthinath there are all of my extensions:
![image](https://user-images.githubusercontent.com/5095527/28910295-77f57422-782c-11e7-987a-b690dcee3411.png)

**Comment by dreszczyk** [comment]
Ok, I found out what was the problem. I had `tsconfig.json` with these options in it:
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "allowJs": true
    }
}
```
I added it because VSC was showing an error on component declaration:
![image](https://user-images.githubusercontent.com/5095527/28910564-b0d22b90-782d-11e7-8a3b-45aa550d0977.png)
```
file: 'file:///xxx.jsx'
severity: 'Error'
message: 'Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.'
at: '43,14'
source: 'js'
```

**Comment by Jeyanthinath** [comment]
@dreszczyk  is it now working ?

**Comment by dbraynard** [comment]
I also have Version 1.14.2 and ctrl-click doesn't work completely. I can ctrl-click on the first call to handleGridSort(), but I cannot ctrl-click on the nested call that is embedded in the ReactDataGrid.

```
render() {

    this.handleGridSort()
   
    return (
      <div>
        <p>Schedule</p>
        <ReactDataGrid
          columns={columns}
          rowHeight={35}
          onGridSort={this
          .handleGridSort
          .bind(this)}
          rowGetter={this
          .rowGetter
          .bind(this)}
          rowsCount={this.getSize()}
          enableCellSelect={true}          
          toolbar={< Toolbar enableFilter = {
          true
        } />}
          onAddFilter={this
          .handleFilterChange
          .bind(this)}
          onClearFilters={this
          .onClearFilters
          .bind(this)}
          minHeight={300}/>
      </div>

    )

  }
```

**Comment by mjbvz** [comment]
@dbaeumer Please file a new issue with a small sample project. I need more context than the snippet provides, such as how you are importing things, and where and how `handleGridSort` is defined
