### ISSUE TITLE
code helper 100 cpu

### ISSUE THREAD

**Issue by phm622848** [Microsoft/vscode#31900]
- VSCode Version: <code>Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)</code>
- Memory (System): <code>16.00GB (3.98GB free)</code>
- Memory (Process): <code>200.14MB working set (0.00MB peak, 164.97MB private, 150.64MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|163|
|renderer|require(workbench.main.js)|419|
|renderer|-> of which require() node_modules|140|
|renderer|create extension host => extensions onReady()|386|
|renderer|restore viewlet|203|
|renderer|restore editor view state|404|
|renderer|overall workbench load|496|
|main + renderer|start => extensions ready|995|
|main + renderer|start => workbench ready|1097|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by mcarpenterjr** [comment]
Not to hijack this issue, but I had to do a `CTRL + Backspace` reload of Nux Mint to get code to stop chewing up the CPU. Just curious if it might be a similar issue in this case.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
