### ISSUE TITLE
Remove prompt when there is only one build task

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#31907]
I only have one build task defined, but when I press Ctrl+Shift+B or "Run Build Task..." it prompts me to select from a list of one...

**Comment by dbaeumer** [comment]
You can marks a task as the default build task then we don't prompt anymore. Run Tasks > Configure Default Build Task from the global menu.

**Comment by Gruntfuggly** [comment]
Thanks - that does work, however I get a warning in the tasks.json, saying "Property group is not allowed"?

**Comment by dbaeumer** [comment]
@Gruntfuggly this is strange. Can you post your tasks.json here.

**Comment by Gruntfuggly** [comment]
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "runner": "terminal",
    "tasks": [
        {
            "taskName": "buildme",
            "command": "reset; docker exec -u `whoami` -it `docker ps | grep ivencs | cut -c1-12` bash -c \"cd ${workspaceRoot};. ~/workspace/init.sh; qmake CONFIG-=debug CONFIG+=nodebug CONFIG+=localemcs CONFIG+=extraDebug  && make -j 4 && qmake CONFIG+=localemcs ut/ut.pro -o Makefile.ut && make -j 4 -f Makefile.ut && ./ut/bin/debug/ut && qmake test/test.pro -o Makefile.test && make -j 4 -f Makefile.test\"",
            "isShellCommand": true,
            "isBuildCommand": true,
            "showOutput": "always",
            "problemMatcher": [
                {
                    "owner": "cpp",
                    "fileLocation": [
                        "relative",
                        "${workspaceRoot}"
                    ],
                    "pattern": {
                        "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.+)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                },
                {
                    "owner": "cpp",
                    "fileLocation": [
                        "relative",
                        "${workspaceRoot}"
                    ],
                    "pattern": {
                        "regexp": "^(.*):(\\d+):\\s+(warning|error|note):\\s+(.*)$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "message": 4
                    }
                },
                {
                    "owner": "ut",
                    "fileLocation": [
                        "relative",
                        "${workspaceRoot}"
                    ],
                    "pattern": [
                        {
                            "regexp": "^(.*):(\\d+):\\s+(FAILED):",
                            "file": 1,
                            "line": 2,
                            "code": 3
                        },
                        {
                            "regexp": "\\s\\s(.*)",
                            "message": 1
                        }
                    ]
                }
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`

**Comment by Stevenic** [comment]
So I'm having the same issue... I have a single default build task and I'm getting prompted to chose from a list of one every time. The only time it doesn't prompt me is if I literally have the task as my active document. See my JSON below:

```
 {
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by Stevenic** [comment]
I can also get it to run without prompting if I close all open file editors. Any time one of my source files are open it prompts me to select the build task.

**Comment by Stevenic** [comment]
If I use the old task format everything builds fine so for now I'll just manually configure the task below for all new projects.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "."],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}

**Comment by dbaeumer** [comment]
@Stevenic your problem is a dup of https://github.com/Microsoft/vscode/issues/31527.

@Gruntfuggly the new group property is only support for task version `2.0.0`. I should handle this better when adding it through the action.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/32083
