### ISSUE TITLE
Linting Extension is not working properly after long usage of vscode

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#31904]
- VSCode Version:1.14.1
- OS Version: ubuntu 16.04.2 LTS

Steps to Reproduce:

1. After long usage of vscodde extension the linting is not working in python, and ctrl + click is also not working 

Temporary Fix:

1. Restarting vscode make things works after some time 

Extension for python:

1. Python for vscode by Thomas Haakon
2. Python by Don Jayamanne

[https://github.com/DonJayamanne/pythonVSCode/issues/1114](https://github.com/DonJayamanne/pythonVSCode/issues/1114)

**Comment by kieferrm** [comment]
This should be fixed with https://github.com/DonJayamanne/pythonVSCode/issues/1072.
