### ISSUE TITLE
Find In Files doesn't search outside of workspace

### ISSUE THREAD

**Issue by reddevil7nine** [Microsoft/vscode#31912]
- VSCode Version: 1.14.2; 1.15.0-insider
- OS Version: Windows 10 (1703.15063.502); MacOS 10.12.5 (Sierra)

Steps to Reproduce:

According to issue [#17164](https://github.com/Microsoft/vscode/issues/17164), in version 1.14, Find in Files should allow you to search outside of the workspace much like every other advanced text editor available. However, this still doesn't appear to work.

Reproduces without extensions: No

**Comment by roblourens** [comment]
This does work, what are you trying?

**Comment by rwatts3** [comment]
Not sure if this is related, but when I try to search for a file deep within the folder structure, it does not return results with the latest release. However if you search the exact name of the file, the results. come up. 

Example, 

In my directory structure there is a file called layout_list that can be in several different folders listings, offers, events, etc. ...

I used to be able to search listings widget_layout_list, and the results would return the one that 's in listings, now it shows no results.

**Comment by roblourens** [comment]
That doesn't sound related, @rwatts3 can you open a new issue with more details about exactly what you are trying to search for? I don't quite follow.
