### ISSUE TITLE
Getting Errror : Port 3000 requires elevated privileges

### ISSUE THREAD

**Issue by hardik85** [Microsoft/vscode#31917]
- VSCode Version: 1.14.2
- OS Version: Window 10

Steps to Reproduce:

1.  Following is the code snipppet. which shows error as well the version of node and npm too.
------------------------------------------------------------------------------------------------------------
**C:\Users\hardik.pancholi\myExpressApp>npm start

> myexpressapp@0.0.0 start C:\Users\hardik.pancholi\myExpressApp
> node ./bin/www

Port 3000 requires elevated privileges

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! myexpressapp@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myexpressapp@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myexpressapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myexpressapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myexpressapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hardik.pancholi\myExpressApp\npm-debug.log

C:\Users\hardik.pancholi\myExpressApp>npm -v
3.10.10

C:\Users\hardik.pancholi\myExpressApp>node -v
v6.10.2

C:\Users\hardik.pancholi\myExpressApp>**
------------------------------------------------------------------------------------------------------------

Reproduces without extensions: Yes/No

**Comment by Jeyanthinath** [comment]
@hardik85 I guess this is nothing to do with vscode ,This is related to nodejs.

but can you reply with `C:\Users\hardik.pancholi\myExpressApp\npm-debug.log`

**Comment by weinand** [comment]
Yes, this is unrelated to VS Code.
