### ISSUE TITLE
Open file opens in a new vscode instance

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#3191]
When we open a file from the OS, it should open in the existing instance of vscode. 

As of now it opens in a totally new instance.

**Comment by egamma** [comment]
This is possible when you use the `-r` or `--reusewindow` option, pls see https://code.visualstudio.com/docs/editor/codebasics#_launching-from-the-command-line

**Comment by thewhitetulip** [comment]
When we do an open file in vscode from the file manager, I do not have the liberty of using command line flags, by default the behaviour of vs code should be that it opens files in an existing instance rather than in a new instance and giving ability to open in an existing instance.

This is totally out of line with basic UI/UX behaviour!
