### ISSUE TITLE
Make Ctrl+Right/Left aka cursorWordEndLeft/Right treat multiple spaces as a "subword".

### ISSUE THREAD

**Issue by EliasCK** [Microsoft/vscode#31910]
Here is how Visual Studio does it, which I much prefer:
![visual studio](https://user-images.githubusercontent.com/11874914/28873293-55c981e4-778d-11e7-99dc-fdd8c6cdb7b2.gif)

And here is how it looks in VS Code:
![vs code](https://user-images.githubusercontent.com/11874914/28873295-57cf235e-778d-11e7-9440-07119902340a.gif)

Is there any possibility of changing this, so that if there is a huge blank space, it doesn't skip next word as well? but only the huge blank space? I often use it to set the cursor at the beginning of the next scope.

**Comment by alexandrudima** [comment]
To control this behaviour and get VS-style Ctrl+Right, please edit your `keybindings.json` and add:

```
{ "key":"ctrl+right",       "command":"cursorWordStartRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordStartRightSelect", "when":"editorTextFocus" }
```

This will overwrite the defaults:

```
{ "key":"ctrl+right",       "command":"cursorWordEndRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordEndRightSelect", "when":"editorTextFocus" }
```

You can also use a keymap extension like the Visual Studio keymap extension.
