### ISSUE TITLE
Characters don't repeat when `ApplePressAndHoldEnabled` is disabled for VSCode

### ISSUE THREAD

**Issue by colepeters** [Microsoft/vscode#31919]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
material-icon-theme|PKi|2.0.11
code-settings-sync|Sha|2.8.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vim|vsc|0.9.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Disable `ApplePressAndHoldEnabled` for VSCode: `defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false` to turn off the press-and-hold character picker behaviour for VSCode only (I don't want to disable this behaviour globally, hence writing to VSCode's defaults).
2. Restart VSCode
3. Press and hold any key (except arrows). You’ll see the press-and-hold character picker appear.

Reproduces without extensions: Yes

---

**Possibly related but not the same issue:** #31676, #19764 

I’ve seen lots of issues around the Vim plugin stating the writing the global `ApplePressAndHoldEnabled` boolean to `false` will enable key repeats in VSCode, and this is true. But since I use the press-and-hold character picker in other apps, I don't want to disable it globally. When writing this default to `false` just for VSCode, it doesn’t seem to respect it. Screenshot of my `com.microsoft.VSCode.plist` file to verify:

![image](https://user-images.githubusercontent.com/1713932/28877436-4509b2e6-7794-11e7-9539-8f4dfe51d5fa.png)

**Comment by colepeters** [comment]
Just to note: this does seem to be working for some people ([see this issue, for example](https://github.com/VSCodeVim/Vim/issues/345#issuecomment-327994811)), however I've just tried this again with a completely clean install of VSCode (having removed all prefs, externsions, etc. beforehand), and I still can't get this to work. Prefs file indicates that `ApplePressAndHoldEnabled` is set to `false`, but the press-and-hold character picker still comes up when holding down a key, and key repeat doesn't work.

A fix for this would be super appreciated! :)

**Comment by colepeters** [comment]
I think I've found the solution for this. It looks like, if you've set `ApplePressAndHoldEnabled` at a global level (i.e. defaults write -g `ApplePressAndHoldEnabled -bool true`), this will override app-level preferences.

My solution was to reset that global with `defaults delete -g ApplePressAndHoldEnabled`, ensure the VSCode has an app-level pref disabling PressAndHold (`defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false`), and to then restart VSCode. Now works exactly as expected (and PressAndHold still works in other apps which I haven't turned it off for).

**Comment by choldrim** [comment]
@colepeters 👍  thanks
but I got it done little differently
```
defaults delete com.microsoft.VSCode ApplePressAndHoldEnabled
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
```
