### ISSUE TITLE
Duplicated intellisense messages following Julia language server crash

### ISSUE THREAD

**Issue by ZacLN** [Microsoft/vscode#31915]
- VSCode Version: 1.4.1
- OS Version: Linux

When the julia-vscode language server plugin crashes and restarts intellisense messages from the server are duplicated.

Steps to Reproduce:

1. Install the julia-vscode extension: https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.7.0-beta.2 (requires julia v0.6)
2. Open a file,  switch the language to Julia and enter `rand()`, hover over `rand`
![julia-vscode1](https://user-images.githubusercontent.com/5861046/28875256-762394a6-7784-11e7-9756-47182edee7ae.png)
3. Simulate a crash by killing the language server (`ps -A |grep julia`, then `kill` _`pid`_)
4. wait for language server to restart and hover over `rand`
![julia-vscode2](https://user-images.githubusercontent.com/5861046/28875296-9f61bf50-7784-11e7-9872-9d58e64bbf82.png)

There is no difference in the message sent from language server but the client duplicates the display results by n (the number of times the server has crashed). 

We get the same duplication for other displayed language server responses.

**Comment by kieferrm** [comment]
@ZacLN how is the language client written? Do you use `vscode-languageclient` or is it custom?

**Comment by ZacLN** [comment]
we use `"vscode-languageclient": "^3.0.0",`

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#246
