### ISSUE TITLE
Format Document changes the cursor position.

### ISSUE THREAD

**Issue by EliasCK** [Microsoft/vscode#31911]
I have set it to format the document when ever I save the file. And I save the file constantly, sometimes just to format the document and other times out of muscle memory for no good reason. So It's annoying that it takes away the cursor from where I'm at each time it happens.

![format document](https://user-images.githubusercontent.com/11874914/28874347-c71e8da4-7791-11e7-87ac-644172986b63.gif)

**Comment by kieferrm** [comment]
@EliasCK I'm guessing you're using the C# extension. If so, pls file the issue here: https://github.com/OmniSharp/omnisharp-vscode/issues. If not, pls file against the extension you're using for formatting.
