### ISSUE TITLE
MacOS preview files in Finder if VS Code is default option.

### ISSUE THREAD

**Issue by omorgan7** [Microsoft/vscode#31914]
- VSCode Version: 1.14.1
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. Set VS Code to the default program for that type of file.
2. Select a file, press spacebar.

Expected: You can see a preview of that file, instead you just get the VSC icon.

![screen shot 2017-08-02 at 14 17 42](https://user-images.githubusercontent.com/24505529/28875416-656bc2d8-778d-11e7-803d-064abeaa7db2.png)

**Comment by bpasero** [comment]
@joaomoreno didn't you do this for 1.18?

**Comment by omorgan7** [comment]
It looks the same as before. 
![screen shot 2017-11-13 at 10 17 40](https://user-images.githubusercontent.com/24505529/32720580-e6df83bc-c85b-11e7-9b84-e18ee30e0f77.png)

**Comment by joaomoreno** [comment]
It didn't really work: #25843
