### ISSUE TITLE
Context menu of custom tree view items opens twice and on wrong entry if accessed via keyboard

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#31918]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Create/use an extension contributing a custom tree view which has context menu entries on elements.
2. Navigate through the entries via up/down keys of your keyboard.
3. Press the context menu button on your keyboard.
4. Observe that the highlight moved one entry downwards. Any action on the context menu is linked to the wrong item now.
5. Observe that after pressing Escape to dismiss the context menu, the context menu pops up again at a different place. Another Escape gets rid of it completely.

This behaviour is different to the main file explorer and is probably a bug or two.

**Comment by cleidigh** [comment]
@letmaik 
cc @sandy081 
This is almost definitely another scenario related to #31850

**Comment by sandy081** [comment]
@joaomoreno Is this dup of #31850?

**Comment by joaomoreno** [comment]
Yes!
