### ISSUE TITLE
Scrollbar and text selection no longer working after reseting powershell integrated terminal

### ISSUE THREAD

**Issue by BeardInASuit** [Microsoft/vscode#31913]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/20505
