### ISSUE TITLE
Request: Allow switching activity bar to minimalist layout

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#31922]
The activity bar is by default very wide, despite only providing a place for a few icons to click on. 

It would be nice if it was possible to switch the activity bar to some kind of a "minimalist mode", meaning that the width would shrink to accommodate the also scaled down (eg. 16×16) icons (Git, Explorer, Search...)

**Comment by kieferrm** [comment]
@PunchyRascal  while not supporting a smaller version of the activity bar, we have the `Toggle Activity Bar Visibility` command. It's also in the `View` menu. You can assign a keyboard shortcut for convenience. Zen mode might also something that helps your screen real estate challenges.

**Comment by PunchyRascal** [comment]
Yes, I know about these and I used them in the past, but now I found myself switching between explorer and search view more often and the buttons are handy, however the bar seems a bit unnecessarily large -
 given it only hosts few icons. But obviously it is a very minor issue.

**Comment by fabiospampinato** [comment]
@PunchyRascal you might want to add those buttons you use the most to the statusbar using [Commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands)

**Comment by hujianxin** [comment]
@fabiospampinato Thanks, that's great!
