### ISSUE TITLE
Typescript Server Error: 'configure' request failed with error

### ISSUE THREAD

**Issue by OrbitalJeffL** [Microsoft/vscode#31924]
- VSCode Version: 1.14.2
- OS Version: Windows 10.0.15063 Build 15063

Steps to Reproduce:

Run VSCode with Typescript settings:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "include": [
    "node_modules/@types"
  ]
}
```

Reproduces without extensions: Yes

Error:

> [Info  - 9:43:23 AM] Using tsserver from: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js
> [Info  - 9:43:23 AM] TSServer log file: C:\Users\Jeffl\AppData\Local\Temp\vscode-tsserver-log-XeondG\tsserver.log
> [Info  - 9:43:23 AM] Forking TSServer
> PATH: undefined
> [Info  - 9:43:23 AM] TSServer exited
> [Info  - 9:43:23 AM] TSServer log file: C:\Users\Jeffl\AppData\Local\Temp\vscode-tsserver-log-XeondG\tsserver.log
> [Error  - 9:43:23 AM] 'configure' request failed with error.
> Error: Could not create TS service
>     at TypeScriptServiceClient.service (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:284:31)
>     at TypeScriptServiceClient.sendRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:789:14)
>     at TypeScriptServiceClient.sendNextRequests (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:779:22)
>     at TypeScriptServiceClient.execute (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:772:14)
>     at TypeScriptServiceClient.serviceStarted (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:592:14)
>     at electron.fork (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:461:30)
>     at resolve (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\utils\electron.js:56:9)
>     at Socket.stdOutStream.once (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\utils\electron.js:85:13)
>     at Object.onceWrapper (events.js:290:19)
>     at emitOne (events.js:96:13)

**Comment by mjbvz** [comment]
Sorry this fell off my radar. 

Please let me know if you are still running into this problem with VS Code 1.18 and TypeScript 2.6
