### ISSUE TITLE
Terminal remains blank when # visible lines > terminal.integrated.scrollback

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31925]
- VSCode Version: Code - Insiders 1.15.0-insider (211ffdf184329179ddca9c1fe993f5f11f3c4dda, 2017-08-02T05:07:49.324Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Verifying #19193

Steps to Reproduce:

1. `terminal.integrated.scrollback`: 10
2. Open new terminal with more than 10 visible lines
3. Remains blank
4. Reload
5. Opens fine
6. Make it show <= 10 lines in viewport
7. Close terminal and reopen
6. Opens fine

**Comment by cleidigh** [comment]
@chrmarti 
@Tyriar 
FYI
Just reproduce the same behavior on Windows 7/cmd.exe

**Comment by Tyriar** [comment]
This was meant to be fixed via https://github.com/sourcelair/xterm.js/pull/750

**Comment by Tyriar** [comment]
This should be fixed in latest. Also I'm preventing negative values in https://github.com/sourcelair/xterm.js/issues/911
