### ISSUE TITLE
Themed Title Bar

### ISSUE THREAD

**Issue by WLLR9505** [Microsoft/vscode#31926]
The current title bar does not match VS Code, I suggest a themed title bar, just like in Visual Studio 201x.

**Comment by rheh** [comment]
To visualise this Visual Studio

![image](https://user-images.githubusercontent.com/1724245/28940462-bd068794-788c-11e7-85b2-2e88c4820bae.png)


And, VSCode

![image](https://user-images.githubusercontent.com/1724245/28940486-cbd7b838-788c-11e7-8acb-b2b5b339fcbc.png)

Themed title bar is a good suggestion.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16363
