### ISSUE TITLE
Assertion Failure in pty.node

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31920]
I get the following exception when running tasks:

![image](https://user-images.githubusercontent.com/172399/28877911-167f4710-779e-11e7-87f5-3b57385560fd.png)

Setup:
- unzip [folders.zip](https://github.com/Microsoft/vscode/files/1194168/folders.zip)
- create a workspace with the folders empty2 and empty2

Steps:
- Tasks>Task2 (continue without scanning)
- Tasks>Task4 (continue without scanning)

The following output shows up in the terminal and then the assertion failure dialog appears
![image](https://user-images.githubusercontent.com/172399/28878546-e6f7bb60-779f-11e7-9be2-4c3124573e5e.png)

->Assertion Failure

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31782
