### ISSUE TITLE
I cannot even zoom out

### ISSUE THREAD

**Issue by thisistrash** [Microsoft/vscode#31928]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@thisistrash 

First - Expletives in issues are completely inappropriate and unnecessary
Second - Your issue lacks any useful information other than the version of code
Third - I have been using Code on Windows 7 with no problems in this regard
Finally - I suggest changing your ID

**Comment by rheh** [comment]
This could be that zoom doesn't work when you pinch a mouse pad on a laptop - this behaviour is present in Chrome / Edge / Visual Studio etc.  Thus, the report may assumed this feature should be in VsCode.  One also assumes a mouse when turned should zoom in/out ,but, I am unable to test to no being on laptop.  I can confirmed Ctrl+, Ctrl+ and Ctrl+Numpad0 work.
