### ISSUE TITLE
Keep tab open key combination not working

### ISSUE THREAD

**Issue by KinsonDigital** [Microsoft/vscode#31929]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
bracket-pair-colorizer|Coe|0.10.7
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.7
vscode-icons|rob|7.12.0
cordova-tools|vsm|1.2.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Open brand new file with code
2.  The title of the tab will be italicized.
3.  Use the key combination to set the tab as "Keep Opened".  Ctrl + K + Enter
4.  Observe that the tab is not affected and the tab title is still in italics.

Tried to use this with extensions disabled like requested below and it works fine.

Reproduces without extensions: No

**Comment by kieferrm** [comment]
@kinsondigital I'm guessing one of the extensions is registering a conflicting command for the same keyboard shortcut. To verify:
- Do you see the same issue when you run the command from the command palette?
- When you run `Open Keyboard Shortcuts` from the command palette and search for `Enter`, what binding(s) do you see for <kbd>Cmd+K Enter</kbd>?
