### ISSUE TITLE
Unable to Install Extensions behind Corporate Proxy/firewall

### ISSUE THREAD

**Issue by Qtan75** [Microsoft/vscode#31931]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open  VSCode
2. Click Extensions icon to the left
3. All the extensions' icons are missing (see attached picture)
4. When click "Install" of any extensions, it will flash installing but then back to Install button
5. No extensions can be installed
6. I am behind a corporate proxy/firewall, however I have setup http.proxy in custom settings and it seems to be working
![extensions](https://user-images.githubusercontent.com/17502718/28892009-79194d98-779a-11e7-9f16-aadb2e51c181.PNG)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you open the Developer Tools Network tab?

Can you open the Shared Process Developer Tools Network tab? (<kbd>F1</kbd>, `Shared Process`).

Any interesting output there?

**Comment by Qtan75** [comment]
Not sure if this is what you were asking about:
![image](https://user-images.githubusercontent.com/17502718/29093337-7b5375fe-7c57-11e7-98a1-8a57b0507feb.png)

![image](https://user-images.githubusercontent.com/17502718/29093464-f0e70ee8-7c57-11e7-83ae-200f4f671311.png)

**Comment by joaomoreno** [comment]
Can you tell your system administrator to open up a few domains?

https://code.visualstudio.com/docs/setup/network#_common-hostnames

**Comment by kannan-balasubramanian** [comment]
I am also facing the same issue with the following showing up in developer tools.

Version: 1.15.1 standard build.
OS: Windows 10 64-bit.
Behind proxy.

1. Getting 200 OK for VSIXpackage download, but shows up as error in console.
2. Then getting the following warning.

> ApplicationInsights:Sender Error: connect ECONNREFUSED 111.221.29.254:443 at Object.exports._errnoException (util.js:1022:11) at exports._exceptionWithHostPort (util.js:1045:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

PS: I am also able to download the VSIXpackage without any issues in Chrome browser.
