### ISSUE TITLE
support "find usages" (like webstorm)

### ISSUE THREAD

**Issue by mo** [Microsoft/vscode#31938]
If you right click a symbol in webstorm you can select "find usages". If the current symbol is a function, then "find usages" searches for all places where this function is called. If the current symbol is a variable, then "find usages" searches for all places where this variable is used etc etc.

This functionality is invaluable when refactoring and you want to know how many places I have to fix if I change the function signature etc.

I could not even find an extension that offers this functionality, even though I think it should be built-in to the language support just like "go to definition" etc.

**Comment by mjbvz** [comment]
`Find all references` should do this. What language are you working in?

**Comment by mo** [comment]
I use it for Javascript mostly, but it is just as useful in other languages.

"Find all references" only lists references in the current file?

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json` file](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project. This will make sure that all JS files are included in the same JS project

**Comment by mo** [comment]
@mjbvz It doesn't work even if I create such a file. I have a file with a function "foo" and at the bottom I have "module.exports = { foo }". I tried to rewrite the export without ES6, i.e. "module.exports = { foo: foo }" and then I used "Find all references" on the left "foo" but that didn't work either. I still get only the references in the current file. The places I want to find is where it says:

import {foo} from './foo.js'
...
foo()
...


Is this possible in VS code?

**Comment by mo** [comment]
@mjbvz I created this example repo that shows the problem: https://github.com/mo/find-all-references

I also searched for similar bugs and found #21507 where you assigned it to yourself instead of closing? There was also #1416 which was moved to the typescript project, not sure if that is really the same issue though since I'm not using typescript.

**Comment by mjbvz** [comment]
Thanks. Looks like a bug when using `module.exports`. `export function foo() {... }` seems to work thought

I've opened https://github.com/Microsoft/TypeScript/issues/17599 to track this

**Comment by darky** [comment]
I notice, that "Find all references" only works with open files.
VSCode: 1.15.1
