### ISSUE TITLE
Search include filter applies to full path of open files

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#31939]
- VSCode Version: Code - Insiders 1.15.0-insider (211ffdf184329179ddca9c1fe993f5f11f3c4dda, 2017-08-02T05:07:49.324Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Verifying #29660

Including `repos` when the folder opened in the workbench is `~/repos/test` will include `~/repos/test/some.css` if that is open in an editor, but not otherwise.

**Comment by roblourens** [comment]
No longer reproes
