### ISSUE TITLE
I broke the terminal

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31934]
![image](https://user-images.githubusercontent.com/323878/28893302-c24506fc-7785-11e7-9239-85eb6564453a.png)

I wasn't doing anything unusual with the terminal. A bit later I noticed that the terminal was blank and that error was in devtools.

I've been messing around trying to repro it and I can't, so... 🤷‍♂️

**Comment by Lixire** [comment]
Me too!

![image](https://user-images.githubusercontent.com/13241824/29043265-4953b6a6-7b6f-11e7-85f5-667d9b16d70c.png)

**Comment by Tyriar** [comment]
Closing since heaps of changes have been made to xterm.js since
