### ISSUE TITLE
Show Task Log command shows Output

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#31930]
The Show Task Log command redirects to the output panel, which seems inconsistent with the move to terminal. 
![image](https://user-images.githubusercontent.com/7109548/28890349-9c7f099a-777b-11e7-9c22-07fafd8bdea7.png)

**Comment by dbaeumer** [comment]
The task system still has an output channel which is used to show parsing errors or other task related things. It is about the task system and not a special running task. OK  to close ?

**Comment by dbaeumer** [comment]
Closing the issue due to above comment.
