### ISSUE TITLE
GIT: If "(Working Tree)" window kept open between commits, it will be comparing any new changes against the SHA it was opened initially

### ISSUE THREAD

**Issue by dmytroua** [Microsoft/vscode#31937]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you share a screen recording?
