### ISSUE TITLE
PowerShell regions fold to next hash instead of to #endregion

### ISSUE THREAD

**Issue by aydeisen** [Microsoft/vscode#31936]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.2.9
vscode-eslint|dba|1.2.11
azure-iot-toolkit|for|0.1.3
azure-functions-tools|joh|0.3.0
vscode-devskim|MS-|0.1.4
mssql|ms-|1.1.0
azurecli|ms-|0.1.0
csharp|ms-|1.11.0
js-atom-grammar|ms-|0.1.13
PowerShell|ms-|1.4.1
typescript-javascript-grammar|ms-|0.0.23
vscode-azureextensionpack|ms-|0.0.4
team|ms-|1.121.1
azurerm-vscode-tools|msa|0.3.6
vscode-docker|Pet|0.0.16
velocity|sod|0.1.0
usql-vscode-ext|usq|0.2.4

---

Steps to Reproduce:

1. Create PowerShell script section starting with #region *string* and ending with #endregion
2. Put a comment inside the region
3. Fold script at #region *string*
Result: vscode folds the region to the comment, and not to #endregion

Screenshots for clarification:
<img width="421" alt="regionexpanded" src="https://user-images.githubusercontent.com/14042645/28895392-36d0932c-77a6-11e7-9cf5-40addcda0f61.PNG">
<img width="433" alt="regioncollapsed" src="https://user-images.githubusercontent.com/14042645/28895393-36d454b2-77a6-11e7-9c68-debd7f7140a7.PNG">

Reproduces without extensions: Yes

**Comment by aydeisen** [comment]
Looking at it further, it looks like there's a dependency on the indentation level.  If the comment was indented, it folds correctly:
<img width="392" alt="indentedcommentexpanded" src="https://user-images.githubusercontent.com/14042645/28895808-e34426f4-77a7-11e7-82d6-327be468423b.PNG">
<img width="148" alt="indentedcommentcollapsed" src="https://user-images.githubusercontent.com/14042645/28895817-e6da19a4-77a7-11e7-9d80-b3007d4060e2.PNG">

It also appears that lines that shouldn't trigger a fold (no square brackets, curly braces, parenthesis, or hash) do:
<img width="401" alt="cmdletnotindentedexpanded" src="https://user-images.githubusercontent.com/14042645/28895957-733aac6a-77a8-11e7-84d9-0dde0c190e25.PNG">
<img width="247" alt="cmdletnotindentedcollapsed" src="https://user-images.githubusercontent.com/14042645/28895963-7742ead4-77a8-11e7-8640-cac6e307ef3b.PNG">

**Comment by kieferrm** [comment]
Indentation currently is indentation based. Pls see #3422.
