### ISSUE TITLE
If I have some files open in VSCode, and then I try to open another file from a different repo via command line ("code path/to/file.json"), it doesn't open the file.

### ISSUE THREAD

**Issue by rupalivohra** [Microsoft/vscode#31943]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open files in repo 1 from the command line (code repo1/path/to/file.txt)
2. Open up a different command line, and try to open a file from a different repo (code repo2/path/to/file2.txt).

**Comment by kieferrm** [comment]
@rupalivohra I'm unable to reproduce the problem on the latest insider. I tried with and without ever having opened repo1 or repo2 in VS Code. In all case the second file open worked as expected. If you have any addition repro steps, pls add them here and we'll reopen the issue.
