### ISSUE TITLE
Unknown property,   source: 'css'

### ISSUE THREAD

**Issue by Andrei079** [Microsoft/vscode#31940]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
open-html-in-browser|cod|0.1.21
githistory|don|0.2.2
vscode-npm-script|eg2|0.2.0
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
LiveServer|rit|1.6.7
vscode-icons|rob|7.12.0

---

Steps to Reproduce:
 text-decoration-color  -  write message: 'Unknown property.'  source: 'css'

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
@Andrei079 pls provide steps that allow us to reproduce the problem.

**Comment by Andrei079** [comment]
I edited the file( .CSS) in the webstorm (EAP version). There were no mistakes. When I opened an error message in the VS. Thank you.
![01](https://user-images.githubusercontent.com/29665690/28978898-82168138-7950-11e7-9648-7c2486f04306.png)

**Comment by kieferrm** [comment]
@Andrei079 thanks! This is fixed in the latest insider builds and will be in the next stable.
