### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by taavikuusik** [Microsoft/vscode#31945]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.9
java|red|0.8.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What is the exact error message you see. Can you provide a screenshot?

**Comment by taavikuusik** [comment]
The title of the report is the exact error message I copied and pasted.
Screenshot below. It actually just happened again, the only way to get rid
of the bar is to report it :D


​

**Comment by mjbvz** [comment]
Try opening the output panel in VSCode and pasting up the contents of the `TypeScript` section. It should provide more info about why the server is exiting

**Comment by taavikuusik** [comment]
[Info - 5:59:03 PM] TSServer exited
[Info - 5:59:03 PM] Using tsserver from: /Applications/Visual Studio
Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info - 5:59:03 PM] Forking TSServer
PATH:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/android-sdk:/usr/local/opt/android-sdk/platform-tools:/usr/local/opt/android-sdk/tools:/usr/local/Cellar/android-ndk-r10e/r10e
[Info - 6:00:24 PM] TSServer exited
[Info - 6:00:24 PM] Using tsserver from: /Applications/Visual Studio
Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info - 6:00:24 PM] Forking TSServer
PATH:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/android-sdk:/usr/local/opt/android-sdk/platform-tools:/usr/local/opt/android-sdk/tools:/usr/local/Cellar/android-ndk-r10e/r10e

...
More of the same. Doesn't look super informative.

**Comment by mjbvz** [comment]
Thanks. You're right, there is not much to go by. Can you please try collecting more detailed logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the crash
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
