### ISSUE TITLE
[css] Automatically show css value suggestions after completing property name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#31948]
From https://stackoverflow.com/questions/45470541/visual-studio-code-html-suggestion-not-working/45470614

**Repo Steps**
In a css file:

```css
body {
   backgro|
}
```

Accept the suggestion for the `background-position` property name.

**Feature request**
After completing the property name, we should automatically show suggestions for the possible values. You currently have to start typing or trigger suggestions manually to see them.

**Comment by aeschli** [comment]
@jrieken @joaomoreno not sure who owns 7/24 nowadays

**Comment by jrieken** [comment]
@aeschli You could actually implement that yourself by use the post-completion command, just set it to trigger completions again.

**Comment by aeschli** [comment]
@jrieken I tried that by putting the 'editor.action.triggerSuggest' to the proposals, but the new completion window is not sowing. I filed #34565.

**Comment by aeschli** [comment]
It's in 1.19
