### ISSUE TITLE
Terminal quickpick should have a "Create new terminal" option

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31949]
Inspired by the "create new branch" option under the git checkout command

![image](https://user-images.githubusercontent.com/323878/28901780-7fe2ee1c-77af-11e7-8c3f-f93888a5c8b1.png)

**Comment by Lixire** [comment]
Should that option be at the bottom or at the top of the generated list? I agree that this should at least be an option when there are no terminals.

**Comment by roblourens** [comment]
Maybe at the bottom, since the picker's primary purpose is switching, and creating terminals will happen much less often.

**Comment by roblourens** [comment]
Oops, I meant August

**Comment by Lixire** [comment]
Closed in https://github.com/Microsoft/vscode/pull/32105
