### ISSUE TITLE
Meteor dev: A lot of undefined variables highlighted in VSCode

### ISSUE THREAD

**Issue by ls42** [Microsoft/vscode#3194]
Hi,

first of all: Thanks for VSCode and open sourcing it. It's on a good road to becoming my favourite editor and also introduced me to TypeScript, which is really awesome, too!

When developing for Meteor with VSCode it often appears that there are some undefined variables, like `Template` or `Meteor`. Of course these variables are not defined in the one of the many files in my project, since they are part of the framework themselves.

I already downloaded the `.d.ts` files from http://definitelytyped.org - and VSCode already recognises them. I.e. it gives hints for function params and I can go to the definition of the variable when CMD-clicking the variable.

<img width="274" alt="screen shot 2016-02-20 at 12 46 47" src="https://cloud.githubusercontent.com/assets/498359/13196516/128c8c2c-d7d0-11e5-8e10-30915f2a8ae9.png">

As can be seen in the the screenshot this (of course) also appears to packages that have been installed via `meteor add` (here it's the i18n package).

Just to be clear: In meteor it's not an issue, since all files get automatically bundled in meteors automatic build process.

**Comment by D1no** [comment]
you should use this, following the readme:
https://github.com/meteor-typescript/meteor-typescript-libs

**Comment by egamma** [comment]
We will migrate to the Salsa infrastructure in our next update. Salsa provides less warnings and defers this to a linter like eslint. You can enable a preview of Salsa, pls give it a try https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by ls42** [comment]
That's not doing it. VSCode thinks that the variables aren't defined since they are not defined in the current source file.

**Comment by ls42** [comment]
That's very cool, thanks for the link. Will give it a try.

**Comment by ls42** [comment]
I'm happy with a solution that involves eslint, an eslint environment (`"env": {'meteor': true}`) and a big array of globals that lists my meteor collections and all exported variables of my used packages.

Everyone having similar issues might have a look [at this gist](https://gist.github.com/ls42/bc6aebda6c66bebe0c53).

Since this is solved (for me) I'm feeling free to close this issue.

**Comment by egamma** [comment]
Thanks for the gist. 

I notice that in your `eslintrc.json` you enable `experimentalObjectRestSpread`. Support for this feature isn't yet provided by Salsa, so using is will degrade the Intellisense experience.

**Comment by ls42** [comment]
@egamma Thanks for the hint. It's an option that `eslint --init` generated. I removed it from the config and updated the gist.

Have a nice day!
