### ISSUE TITLE
Ctrl + ` in win10，can't use cmd and display undefined.

### ISSUE THREAD

**Issue by YeaseonZhang** [Microsoft/vscode#31957]
- VSCode Version: Code - Insiders 1.15.0-insider (0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7, 2017-07-28T11:23:06.089Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.18.1
angular1-code-snippets|ale|0.0.3
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
vscode-npm-script|eg2|0.2.0
mithril-emmet|Fal|0.6.1
code-runner|for|0.6.30
terminal|for|0.0.10
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
Angular2|joh|2.4.0
vscode-codemetrics|kis|1.8.0
vue|liu|0.1.5
markdown-shortcuts|mdi|0.8.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.7
debugger-for-edge|msj|0.4.1
vetur|oct|0.9.3
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
partial-diff|ryu|0.3.1
vue|sea|0.4.2
Angular2|UVB|0.4.1
vim|vsc|0.9.0
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Ctrl + `

Reproduces without extensions: Yes/No

![image](https://user-images.githubusercontent.com/17896253/28910282-af57b1a0-785e-11e7-9b30-5841d1f3a6cb.png)

![image](https://user-images.githubusercontent.com/17896253/28910193-5971d0fe-785e-11e7-8502-1ae82e1c4783.png)

**Comment by King66** [comment]
You are not using latest insiders, and if you are using 64bit Code, use System32 instead of Sysnative

**Comment by YeaseonZhang** [comment]
@King66 Thx, Use System32 instead of Sysnative can work. But vscode (not insider) terminal path is Sysnative. At last, You can close this issue.

**Comment by King66** [comment]
@YeaseonZhang you can close it, I am a user too.
