### ISSUE TITLE
VS Code cannot treat java file which contains large 'enum'.

### ISSUE THREAD

**Issue by ciiwol** [Microsoft/vscode#31958]
- VSCode Version: 1.14.2 (32bit, 64bit both have problem with this)
- OS Version: Windows 7

Steps to Reproduce:

1. Create an empty java file.

2. Open it with notepad.exe and type this -> 3 times or more.
> public enum test {
AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, AAAAAAAAAAA, BBBBBBBBBB, CCCCCCCCCC, DDDDDDDDDD, EEEEEEEEEE, FFFFFFFFFF, 
}

3. Save the file, and open it with VS Code.

4. Observe. It'll take very long time to open and applying syntax highlight.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to atom/language-java#103
