### ISSUE TITLE
cannot write system files even with administrator previlage in windows 10

### ISSUE THREAD

**Issue by hariharank6** [Microsoft/vscode#31959]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
FreeMarker|dco|0.0.9

cannot edit system files such as hosts file even with administrator previlage.
worked well in windows 7 but isn't working in 10.

---

Steps to Reproduce:

1. win + R and enter drivers.
2. open etc -> hosts file with VS code and try to save it.

Reproduces without extensions: Yes/No

**Comment by Jeyanthinath** [comment]
Try running vscode as administrator and then open the same file, try to save

**Comment by kieferrm** [comment]
@hariharank6 can't reproduce when running vscode as admin.
