### ISSUE TITLE
My vscode always stucked when I Alt+tab  from Chrome

### ISSUE THREAD

**Issue by Ryuurock** [Microsoft/vscode#31955]
- VSCode Version: 1.14.2
- OS Version: windows 10 15063

Steps to Reproduce:

1. open vscode, open a js file
2. open a other application, then press Alt+tab to vscode，If it doesn't reappear, we can focus vscode then  Alt+tab， repeat the action
this is timeline
![tim 20170803134854](https://user-images.githubusercontent.com/25604544/28908243-27c2f802-7855-11e7-90c1-0f5fab0afac4.jpg)

emmmm, not only at chorme, some time between desktop app also stucked

Reproduces without extensions: Yes

**Comment by Ryuurock** [comment]
I think chrome and vscode are grabbing some resource, causing a crash, and my device is the surface laptop

**Comment by jrieken** [comment]
Can you try with latest stable and insiders and see this still happens?

**Comment by Ryuurock** [comment]
The latest stable already solve this problem. Thanks
