### ISSUE TITLE
Error - The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#31962]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
Handlebars|and|0.2.0
htmltagwrap|bra|0.0.3
gotemplate|cas|0.1.1
bracket-pair-colorizer|Coe|0.10.7
mustache|daw|1.0.0
gitlens|eam|4.3.3
vscode-html-css|ecm|0.1.7
json-tools|eri|1.0.2
beautify|Hoo|1.1.1
automagic-code|jai|0.0.2
git-indicators|lam|1.2.1
start-git-bash|McC|1.2.1
code-beautifier|mic|1.7.2
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.1.7
subtle-brackets|raf|2.0.2
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
vscode-todo-highlight|way|0.5.8

(6 theme extensions excluded)

---

Steps to Reproduce:

1. Open any js file in the editor
2. Click on a line as if you are about to edit the code
3. 
![image](https://user-images.githubusercontent.com/14346320/28913861-6b9195e4-7831-11e7-859d-3293bed29702.png)

Reproduces without extensions: Yes/No

**Comment by euk-anthonyb** [comment]
This happens quite often now, for seemingly no specific reason...

**Comment by kieferrm** [comment]
@euk-anthonyb Can you pls attach the smallest workspace you have in which this is still happening. Thanks!

**Comment by euk-anthonyb** [comment]
Hi Kai,

I'm sorry, I don't understand. How can I send you my Workspace?


*Anthony Browne*
Senior Designer

Eukleia Training Limited
Sherborne House, 5th Floor, 119-121 Cannon Street, London EC4N 5AT

*t*   +44 (0)2072204057 (direct)
    +44 (0)2072204050 (general)
*f*   +44 (0)2072204051

*e* anthony.browne@eukleia.com
*w* eukleia.com
<http://eukleia-training.com>

​
We use *Google* Hangouts

**Comment by mjbvz** [comment]
@euk-anthonyb Please create the minimal project that demonstrates the problem and either upload a zip file of the project or create a new repository on github with the project contents
