### ISSUE TITLE
Linting message about image URLs of extensions

### ISSUE THREAD

**Issue by anseki** [Microsoft/vscode#31960]
- VSCode Version: 1.14.2
- OS Version: Windows

Since v1.14, VS Code shows linting errors about image URLs for extensions.
https://code.visualstudio.com/updates/v1_14#_extension-authoring

A message "Relative image URLs require a repository with HTTPS protocol in the package.json." with green is shown when the URL is relative even if that is not SVG, in `README.md` and `package.json`.

For example:

`package.json`

```js
"icon": "icon.png"
```

`README.md` (but message says "`package.json`")

```js
![screen-01](screen-01.gif)
```

Now, it seems that these images that are not SVG with relative URL are shown correctly.

I think that the linting message should not be shown.
Or, should we fix the URLs? (e.g. the `icon` in `package.json` should be `https://...`.)
(but `"icon": "images/icon.png"` is shown in https://code.visualstudio.com/docs/extensionAPI/extension-manifest)

**Comment by kieferrm** [comment]
@anseki do you have a `repository` property defined in your `package.json` file? Is the value of this property a `https://` URL?

**Comment by anseki** [comment]
Hi @kieferrm, thank you.
The `repository.url` was `"git://github.com/....git"`.
I changed that to ``"https://github.com/....git"``, and this issue was solved. Thank you! 😄
