### ISSUE TITLE
Extension editor state is not retained

### ISSUE THREAD

**Issue by akliyiping** [Microsoft/vscode#31967]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
code-settings-sync|Sha|2.8.2
html-snippets|abu|0.1.0
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.3
vscode-browser-sync|jas|1.0.1
search-node-modules|jas|1.1.1
Angular2|joh|2.4.0
expand-region|let|0.0.3
vscode-icons|rob|7.12.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.Open extension panel
2.Click on an extension to scroll through the extended details page
3.Click on this extension again，Scroll bar back to top

Reproduces without extensions: No

**Comment by kieferrm** [comment]
This reproduces without extensions.
