### ISSUE TITLE
Go to definition points wrong line,when file has changed without saving.

### ISSUE THREAD

**Issue by easters14** [Microsoft/vscode#31961]
- VSCode Version:1.14.2

Steps to Reproduce:

1.Change any code into another line 
2.Don't save file
3.Click "go to definition"
4."go to definition" point out old line of select text 

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
@easters14 In what language does this happen?

**Comment by easters14** [comment]
@jrieken It happens on C/C++

**Comment by jrieken** [comment]
Please file this issue against that extension. Thanks and Happy Coding.
