### ISSUE TITLE
Files list layout in Ctrl+P menu is not user friendly

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#31975]
- VSCode Version: 1.14.2

Steps to Reproduce:

1. Search for a file using Ctrl+P
2. The search files menu shows up
3. The way the file name is displayed first and then the path is a little hard to scan.
4. If this order is reversed, it will be very easy to scan the list 

http://i.imgur.com/kYD5X1u.png

**Comment by mjbvz** [comment]
This is by-design. We show the filename first since this is often the most important part of what you are looking for. It also is consistent and makes scanning for different file name matches easier. With the current layout, files names are always in the left most position
