### ISSUE TITLE
TypeScript provides two identical tasks

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#31977]
Steps to reproduce:

- create a fresh workspace
- create a tsconfig.json
```ts
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "./bld",
        "rootDir": "./",
        "strict": true,
        "alwaysStrict": true,
        "moduleResolution": "node"
    }
}
```
- create a test.ts file
```ts
console.log("Hello World");
```
- F1 > Run Task

Observe: you have two tsc build tasks listed.

<img width="551" alt="capture" src="https://user-images.githubusercontent.com/1931590/28925097-269dcfd8-7864-11e7-820b-8454a15ffb7e.png">

**Comment by mjbvz** [comment]
Possible duplicate of #29929 

This should already have been fixed in current insiders builds. Are you still seeing the issue?

**Comment by dbaeumer** [comment]
I saw this yesterday when running out of sources. The key is to have focus in the test.ts file after you created it.

**Comment by mjbvz** [comment]
I'm still unable to reproduce this. What OS are you on?

**Comment by onlineservices283418** [comment]
Complete STR is here #31527

**Comment by dbaeumer** [comment]
I am using Windows 10. I tried it again this morning and the steps from above still reproduce this. I do have auto save on so both tsconfig.json and the test.ts are save to disk.

**Comment by dbaeumer** [comment]
Reopening...

**Comment by dbaeumer** [comment]
@mjbvz anything I can help with tracking this down?

**Comment by mjbvz** [comment]
@dbaeumer Thanks, I think I've tracked it down. It came down to a path using `/` instead of `\` on windows. Testing now and will submit a fix shortly
