### ISSUE TITLE
Problems View - add option to restrict to current viewed file

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#31973]
I have seen people request the option (opt-in) to have the problems include the summary for all files. I was wondering if you could also add an option to restrict the PROBLEMS output and count in the status bar to only the currently edited file (not all opened ones).

I have several different scripts opened and would find it much cleaner to see errors for a single file. Many thanks for considering this!

**Comment by fbricon** [comment]
Having the option to enable problems filtering on currently focussed editor would be very convenient for Java projects with massive amounts of warnings

**Comment by sandy081** [comment]
Duplicate of #7248
