### ISSUE TITLE
Bulk changes not showing in Git working copy

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#31976]
- VSCode Version: Code - Insiders 1.15.0-insider (c26f8a312b9aa792f45a7baf06e31576470236a8, 2017-08-03T05:07:45.056Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.1
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. change many files at once, as in a find/replace/save all
2. the working copy pane done not recognize the changed files
3. a separate Git client (here Tower) correctly realizes 7 files are touched.

![screen shot 2017-08-03 at 8 57 24 am](https://user-images.githubusercontent.com/835148/28922921-f9b0a2f0-7829-11e7-86f7-e906e4bda09c.png)

**Comment by joaomoreno** [comment]
What does `git status` in a command line report?
