### ISSUE TITLE
Disable TypeScript watch support

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#31971]
We should disable the TypeScript watch support again due to the following issues:

- the support adds a watch property to the task definition which results in the fact that is doesn't make existing task customizations anymore. The task engine needs to falsify these value when computing the identifier key. See https://github.com/Microsoft/vscode/issues/31970. It basicallz broke the default build task support.
- the task engine currently writes the problem matcher into the tasks.json file however the matcher is now dynamic passed on `compileOnSave` from the tsconfig.json.
- the task provider should set the isBackground correctly and should use the correct problem matcher.

@mjbvz sorry for detecting this so late but I was on vacation until yesterday.

**Comment by dbaeumer** [comment]
//cc @egamma

**Comment by mjbvz** [comment]
Original issue: #29580
// cc @kieferrm 


@dbaeumer What is the proposal? Leave this disabled in 1.15? What about next iteration then?

**Comment by dbaeumer** [comment]
The proposal is to leave it disabled for 1.15. For next iteration we can either do:

- have two tasks one for build and one for watch (is actually @egamma suggestion)
- respect the compileOnSave in tsconfig.json and fix the fact the the problem matcher gets inlined when customizing a task
- work on a real compileOnSave support without starting the tsc -watch.
