### ISSUE TITLE
RSS feed for code.visualstudio.com

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#3197]
You recently moved to VS Code blog to code.visualstudio.com, but in the move, RSS feed support was lost.

I'd like to request RSS feed for the blog (https://code.visualstudio.com/blogs) and updates (https://code.visualstudio.com/Updates).

Thanks

**Comment by waderyan** [comment]
This has been moved to vscode-website repo. Top of the backlog :)

**Comment by arolson101** [comment]
Could someone link the new issue?  I can't find the vscode-website repo

**Comment by Tyriar** [comment]
@arolson101 the vscode-website repo is closed. @waderyan is currently working on getting the RSS/Atom feed up and running.

**Comment by waderyan** [comment]
@arolson101 yeah sorry. Unfortunately we're not quite there where we can make the website open sourced.

**Comment by mo** [comment]
@Tyriar any news on the RSS? I would like RSS for:
https://code.visualstudio.com/updates/
...but the RSS link in the bottom right corner is some other blog or something?
