### ISSUE TITLE
Search Marketplace for Extensions for 'language Id' is broken

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#31972]
The recommendation filtering is broken and currently all language extensions are shown ignoring the actual language id.

![image](https://user-images.githubusercontent.com/172399/28922451-7c82fae0-785a-11e7-9184-4be14b373559.png)

I've removed the action for now from the menu.

**Comment by sandy081** [comment]
Looks like this [commit](https://github.com/Microsoft/vscode/commit/e5983e699c33df7983820ed9cf56ef041c663b50) broke this behaviour. There was a command that shows extensions with given language id. But this change added a new action with same id as the other, to show extensions with language category.
