### ISSUE TITLE
Extensions not up to date

### ISSUE THREAD

**Issue by ixxie** [Microsoft/vscode#31978]
Extensions on VSCode are not up to date with the marketplace, and offer no way to update:

![](http://i.imgur.com/4dwjWat.png)

Scala Language Server, for example, [should be at 1.1.6](https://marketplace.visualstudio.com/items?itemName=dragos.scala-lsp).

**Technical Details**

On [NixOS 17.03](https://nixos.org/) (works with as [unusual package manager](https://nixos.org/nix/), may be involved in the issue).

*Version 1.9.1*
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-08T23:44:55.542Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by kieferrm** [comment]
You don't see available update to the scala language server because it requires a higher VS Code version than you have installed. This is from its `package.json` file:
```json
"engines": {
		"vscode": "^1.10.0"
	}
```

**Comment by ixxie** [comment]
@kieferrm - thanks for schooling me, good to know!
