### ISSUE TITLE
Request to add Tamil language to VS Code

### ISSUE THREAD

**Issue by solomonsunder** [Microsoft/vscode#31974]
We expect at least three language contributors sign up and product team sign off before adding new language to transifex.
Please vote by adding your transifex account name here.

**Comment by atif089** [comment]
Fellow Indian here and I mean no disrespect. Just curious, do you use the IDE in the Tamil language?

**Comment by solomonsunder** [comment]
I would use it if it were present.
There are Computer Science Polytechnics in TN which are completely in Tamil. So, yes, there is large audience.

**Comment by vikramnr** [comment]
@solomonsunder  Is there a link? I couldn't find one?

**Comment by solomonsunder** [comment]
https://www.transifex.com/user/profile/solomonsunder/

@vikramnr I think you just put in your transifex link in here to vote. Once we have three people voting in with their Transifex link, it'll probably get enabled on transifex.
@danyeh might be able to comment.

**Comment by solomonsunder** [comment]
@vikramnr https://www.transifex.com/microsoft-oss/public/
You can check it out here. The ones with vscode-* are the one related to this project. Tamil isn't on it yet.

**Comment by Avinashachu007** [comment]
Hi @solomonsunder . I would like to contribute for the VSCode Tamil Translation. Please guide me get started.

**Comment by Avinashachu007** [comment]
@solomonsunder  Created Language request for Tamil in Transfix for vscode-editor, vscode-workbench & vscode-setup

**Comment by danyeh** [comment]
Thank you @solomonsunder and @Avinashachu007 for showing interests! Can you help to attract more people to vote here. We need one more vote.
@Avinashachu007, please state your transifex account like Solomon did here as vote.
Adding language criteria is here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.

**Comment by Avinashachu007** [comment]
Transifex Account https://www.transifex.com/user/profile/AvinashRavi/
Thank you @danyeh & @solomonsunder

**Comment by Avinashachu007** [comment]
https://www.transifex.com/user/profile/AvinashRavi/

Thank you @danyeh & @solomonsunder

**Comment by prasphy** [comment]
+1

**Comment by Jeyanthinath** [comment]
I vote( transifex username: jeyanthinath )

**Comment by Avinashachu007** [comment]
Thank you @Jeyanthinath

**Comment by danyeh** [comment]
Tamil (ta) language enabled in Transifex today for VS Code projects (Editor, extensions and workbench).
Thank you @solomonsunder @Avinashachu007 @Jeyanthinath for contributing!
Once have good coverage of translation of Tamil in Transifex. We will look at integration to VS Code.
