### ISSUE TITLE
[Feature] Have an extension to learn VSCode shortcuts the "FlashCard" way

### ISSUE THREAD

**Issue by MeTaNoV** [Microsoft/vscode#31979]
Using FlashCard is the best way I found to learn a lot of different things, especially with foreign languages where the vocabulary corpus learning task is one of the main time-consuming activity.
The same can be applied when learning VScode shortcuts. I would say that most of the developers stay with the one they know because they are reluctant to spend time learning new ones. ( @naure )
Having an extension that proposes at the beginning of every day to spend 5-10 minutes learning some shortcuts using a FlashCard system would I think lead to a progressive increase of productivity.
This extension could be then used to monitor the evolution of keyboard shortcut usage and provide insight on the time gained using those shortcuts.

@egamma, @dbaeumer WDYT?

**Comment by mjbvz** [comment]
Yes this sounds like a good extension idea. Check out our [extension authoring docs](https://code.visualstudio.com/docs/extensions/overview) for information on getting started with this

Closing as  extension-candidate
