### ISSUE TITLE
PHP use trait with namespace highlight break

### ISSUE THREAD

**Issue by luxifer** [Microsoft/vscode#31980]
The highlighting of a PHP file is broken for this case:

```php
<?php

namespace Foo;

class Bar
{
    use \Foo\Bar\Baz;

    public function baz()
    {
    }
}
```

It produces the following highlight:

<img width="271" alt="capture d ecran 2017-08-03 a 16 50 37" src="https://user-images.githubusercontent.com/419078/28927857-ed50988e-786b-11e7-9ca0-02170e025377.png">

- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Use class with fully qualified namespace like `use \Foo\Bar\Baz`;

Reproduces without extensions: Yes

The issue has been resolved in https://github.com/atom/language-php/pull/249 so I wonder when the PHP grammar will be synced.

Thanks!

**Comment by jackwilsdon** [comment]
You may be better asking in #30448, as this just seems to be a duplicate of that with a question attached.

**Comment by luxifer** [comment]
Yep its a duplicate
