### ISSUE TITLE
[json] Extra quotes get added when trying to add a closing quote in json file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#31989]
In a json file
- add double quotes, closing quotes get added
- delete the closing quotes
- add the closing quote yourself

Observe that another double quotes get added.

Repros without any extensions as well

![jsonquotes](https://user-images.githubusercontent.com/16890566/28935957-fce73144-783a-11e7-9809-283b9d2fda1f.gif)

**Comment by aeschli** [comment]
Same problem as #26637
