### ISSUE TITLE
VS Code\PowerShell - "Formatting Document" Long Execution Time

### ISSUE THREAD

**Issue by RickFlist** [Microsoft/vscode#31985]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.2.9
azure-iot-toolkit|for|0.1.3
azure-functions-tools|joh|0.3.0
mssql|ms-|1.1.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
vscode-azureextensionpack|ms-|0.0.4
azurerm-vscode-tools|msa|0.3.6
vscode-docker|Pet|0.0.16
easy-snippet-maker|tar|0.0.6
usql-vscode-ext|usq|0.2.4

---

Hello!
I've noticed over the last couple days/week that VS Code is taking a very long time on "Formatting Document". I have my VS Code instance configured to format the document on every save, and I save constantly, so this is a real PITA. :( I have attached the contents of $env:APPDATA\Code\User to this report. 
[v-toddle@microsoft.com.zip](https://github.com/Microsoft/vscode/files/1197772/v-toddle.microsoft.com.zip)

Steps to Reproduce:

1. Configure VS Code using my settings.json
2. Open up any Posh Script. I have encountered this on scripts with as few as 120 lines
3. Make a change
4. Save file
5. Blue bar at bottom of VS Code states "Formatting Document". VS Code is responsive, but Snippets and Intellisense do not function until it completes doing whatever it was doing.

Reproduces without extensions: No

**Comment by RickFlist** [comment]
Okay the "Formatting Document" issues seems to be caused by easy-snippet-maker. Disabling that extension fixed the Formatting Document long pause time. However snippets and Intellisense is still laggy?

**Comment by kieferrm** [comment]
@RickFlist can you pls file the issue against the powershell extension? Thanks a ton! Here is the link https://github.com/PowerShell/vscode-powershell/issues.

**Comment by RickFlist** [comment]
Which one? The only way it goes away is if I launch VS Code with the --disable-extensions, which seems to disable more than what i download. If I launch VS Code and then go and disable all the extension, the issue still repros.

**Comment by RickFlist** [comment]
Oh I see what you mean. Will do.
