### ISSUE TITLE
`extensions.ignoreRecommendations` doesn't work

### ISSUE THREAD

**Issue by mojaveazure** [Microsoft/vscode#31981]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.5.0
Ionide-fsharp|Ion|2.31.0
material-icon-theme|PKi|2.0.11
vscode-svgviewer|css|1.4.2
scala|dal|0.0.4
python|don|0.7.0
language-julia|jul|0.6.2
cpptools|ms-|0.12.2
csharp|ms-|1.11.0
java|red|0.8.0
elm|sbr|0.14.1

---

Steps to Reproduce:

1. Set `extensions.ignoreRecommendations` to `true` in user settings.
2. Open Code and the extensions menu (ctrl/cmd + shift + x), watch as the recommended extensions pop up.
3. This happens around every third day. Please stop marketing to me when I'm trying to get work done.

Reproduces without extensions: Yes

**Comment by CnSimonChan** [comment]
`extensions.ignoreRecommendations` controls whether Code will suggest you extensions when opening a file without language server installed, not the "Recommendation" panel in the Extension sidebar.

But with 1.15 update you can right click on the panel to remove it.
