### ISSUE TITLE
CPU usage rises to 90%

### ISSUE THREAD

**Issue by necaimi** [Microsoft/vscode#31984]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jshint|dba|0.10.15
vscode-html-css|ecm|0.1.7
HTMLHint|mka|0.3.3

---

Steps to Reproduce:

**1. when i open the savefiledialog from vscode， then CPU usage rises to 90%;
   but the openfiledialog is normal usage**

Reproduces without extensions: **Yes**

**Comment by kieferrm** [comment]
@necaimi I can't reproduce. Can you provide a bit more detail for us? Does it happen with any workspace or even without having a workspace open? Any file type or only specific file types? Is the folder you want to save to on a network drive? etc. Anything that helps us pinpointing it. Thanks!

**Comment by necaimi** [comment]
apologize for my strictness.

**Comment by necaimi** [comment]
hi kieferrm,
apologize for my haste.
and i do more test for it and found maybe this bug is between electron and explorer (Win10 1703),
...
call the savefiledialog and search specific folder A (test vscode.exe @latest and electron.exe ) , i found the **iconcache_48.db** file created by explorer.exe read local hard drive crazily and continuously in resource monitor.
Some file type in this folder A(.pem, .zip, .xlsx, .psd, .crx, .html), then i call savefiledialog by other program (like google chrome, photoshop) to read folder A and it seem stably.
The html file is default open by IE Edge, so i guess the reason for the bug is to scramble to register the default open mode and default icon?!
@kieferrm

**Comment by miaojiuchen** [comment]
I encounter this problem in macOS, please check this issue, I describe my situation in it:
https://github.com/Microsoft/vscode/issues/32532

**Comment by bpasero** [comment]
Please reopen if you can still reproduce in newer builds.
