### ISSUE TITLE
Terminal processes exit too eagerly if window close is canceled

### ISSUE THREAD

**Issue by delicb** [Microsoft/vscode#31988]
- VSCode Version: 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e)
- OS Version: macOS Siera (10.12.6)

Steps to Reproduce:

1. Open VSCode and open integrated terminal
2. Make changes to some file
3. Invoke VSCode shutdown (e.g. via clicking `x` button)
3. When prompted with question if you want to save file content click `Cancel`
4. I expected everything to continue working, but terminal was terminated
5. After closing it and opening it again it did start and was functional, but selection of text in terminal is not possible.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I believe the selection issue is fixed in latest.

As for closing terminals this seems like a bug.
