### ISSUE TITLE
JS Syntax coloration breaks at generic usage

### ISSUE THREAD

**Issue by yleflour** [Microsoft/vscode#31983]
- VSCode Version: 1.14.2
- OS Version: macOS Sierra - 10.12.5

Steps to Reproduce:

Please note that this is Flow typing and not Typescript typing.

1. Copy and paste [this gist](https://gist.github.com/yleflour/0f57b68d55c24ee0bf35f6e0b17fd077) in VSCode in a .js file
2. Coloration is broken at `Record<UserType>`

![image](https://user-images.githubusercontent.com/1863461/28929585-a0a484d2-7870-11e7-8974-f3a90a7763cd.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#495
