### ISSUE TITLE
task not run with integrated shell args

### ISSUE THREAD

**Issue by Clet** [Microsoft/vscode#31998]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Shell commands in tasks does not get run if there's a startup call linked to the integrated terminal.

shell.bat
`echo Test`

Steps to Reproduce:
1. Use these settings :
```
    "terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
         "/k .\\shell.bat"
    ],
```
with this task :
```
"version": "2.0.0",
"tasks": [{
    "taskName": "Hello World!",
    "command": "echo Hello World!",
    "type": "shell",
    "presentation": {
      "echo": true,
      "reveal": "always",
      "focus": false,
      "panel": "shared"
    }
  }
```
2. Run task.
3. See that "Test" is printed out, but not "Hello World!"

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Dups #32955
