### ISSUE TITLE
Can a debug adapter indicate variables with possible-side-effects/expensive?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#31995]
Currently my Dart debugger only shows fields from objects in debugging tooltips (no properties/getters) to avoid executing user code or causing side effects (that's the behaviour of the debugger, not my adapter, though I understand why they've done it).

I believe I could get these values from the debugger by executing the getters but it could be slow/cause side effects.

Is there a way when returning objects to provide variables that require user-input to evaluate? Similar to how in Visual Studio you can expand iterators when debugging but they're not executed automatically?

I saw https://github.com/Microsoft/vscode-node-debug/issues/14 which seemed like it might be related, but I didn't understand the resolution after clicking through the related cases. I also found the `expensive` flag on `Scope` but couldn't figure out if that would be useful here.

**Comment by DanTup** [comment]
I need to get me a @vscodebot[bot], I think it could automate half of what I do at work =D

**Comment by weinand** [comment]
If you enable "evaluate" based hovers, you could use the "context" argument to decide whether the "evaluate" is used for the variables view or the hover. With this info you could ignore properties/getters for the hover, but include them for the variables view.
Without enabling "evaluate" based hovers, VS Code will use the variables view's data for the hover as well.

**Comment by DanTup** [comment]
@weinand I actually want both to behave the same, rather just have user input to invoke any getter. I could probably take it by hiding then inside an object that needs expanding, but I think it'd probably look rather misleading?

**Comment by weinand** [comment]
and with "user input" you mean a context menu action?

**Comment by DanTup** [comment]
Or some icon or something. Similar to in Visual Studio's refresh button like this:

![ic851786](https://user-images.githubusercontent.com/1078012/28942360-fe8eb33e-7892-11e7-9c5b-09da19c838a5.jpeg)

Something simple a user has to do to invoke the getter (both to avoid unwanted side-effects and also for performance reasons, since I need to send individual requests for each getter to the debugger to get their values).
