### ISSUE TITLE
Recent files/directories suggestion from this branch on checkout

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#31994]
This is a feature request.

I'm sometimes obligated to switch development contexts, which often involves a branch switch. I would normally close all the active tabs, switch branches. Then open the relevant files; usually the 'recent' files associated with checked out branch.

I'd like to have some sort of section, maybe under the scm tab on the sidebar, that lists several of the files that were open last when this branch was checked out.

I think an easy start, in terms of implementation, would be to list directories under which files have been recently commited; check the latest commits on the branch and suggest as appropriate.

Let me know if further clarification is required.

**Comment by joaomoreno** [comment]
This sounds a lot like working file sets, which can be API accessible.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by QwertyZW** [comment]
@isidorn I can reopen this issue in 6-12 months if you like. Just let me know if you'd like that to happen.
