### ISSUE TITLE
Sass variables in selector breaks emmet

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#31990]
Have a .scss file using this pattern:

```scss
p.#{$name} {
}
```

Now emmet doesn't work in the file

**Comment by ramya-rao-a** [comment]
Also control directives

```
/* if else statement */
$type: monster;
p {
  @if $type == ocean {
    color: blue;
  } @else {
    color: black;
  }
}
```

```
/* for statement */
@for $i from 1 through 3 {
  .item-#{$i} { width: 2em * $i;  }
}
```

```
/* while statement */
$i: 6;
@while $i > 0 {
  .item-#{$i} { width: 2em * $i; }
  $i: $i - 2;
}
```

**Comment by ramya-rao-a** [comment]
Apart from the emmet completions, this breaks all emmet commands that are applicable to stylesheets
   - Expand Abbreviation
   - Select Next/Prev item
   - Toggle Comment
   - Update Image Size
   - Reflect CSS Value
