### ISSUE TITLE
Terminal line background color split when terminal line-height set higher than 1.0.

### ISSUE THREAD

**Issue by russianryebread** [Microsoft/vscode#31991]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
html-css-class-completion|Zig|1.8.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
vscode-auto-open-markdown-preview|hnw|0.0.4
phpcs|ika|0.7.0
vscode-duplicate|mrm|1.1.0
atom-keybindings|ms-|3.0.1
vetur|oct|0.9.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Set user setting: `"terminal.integrated.lineHeight": 1.5`
2. Run a command in the integrated terminal that has background coloring: `echo -e "\033[1;41m                 \n - OUTPUT LINE - \n                 \033[0m"`

<img width="160" alt="screen shot 2017-08-03 at 1 40 43 pm" src="https://user-images.githubusercontent.com/747085/28937714-5f569fb6-7851-11e7-879c-9f0e6837bdc6.png">

**Comment by Tyriar** [comment]
Should be fixed in latest
