### ISSUE TITLE
Program appears to continue executing after pressing stop in the debugger

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#32]
In a simple node app, I step through a loop in the debugger. Before exiting the loop, I press the stop button
![snip_20151116130725](https://cloud.githubusercontent.com/assets/1704059/11185295/f6af8bbe-8c73-11e5-9a4a-f30d84c14b07.png)
I expect the program to stop executing right at that point but it appears to continue executing due to the fact that the console.log statement is executed (highlighted below) and the value of the string being output looks like the loop continued to execute even after pressing stop:
![snip_20151116150729](https://cloud.githubusercontent.com/assets/1704059/11185303/ff729908-8c73-11e5-8446-f88aa3559d02.png)

**Comment by jel-massih** [comment]
Wouldnt this be an issue with https://github.com/microsoft/vscode-node-debug rather than base vscode?

**Comment by weinand** [comment]
Yes, correct. But there seems to be no way to move this issue over to vscode-node-debug.

**Comment by lukehoban** [comment]
@weinand I've used https://github-issue-mover.appspot.com/ successfully for one-off issue moves.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#6
