### ISSUE TITLE
terminal not working.

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#32004]
- VSCode Version: Code - Insiders 1.15.0-insider (81e812c06540d1bd2636cf70ff7d0edd1bb0e866, 2017-07-21T13:15:10.775Z)
- OS Version: Windows_NT x64 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-mocha|Com|0.1.1
vscode-mocha-test-runner|cst|0.2.1
angular2-snippets|dan|1.0.15
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
xml|Dot|1.9.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.1.1
cpptools|ms-|0.12.2
debugger-for-chrome|msj|3.1.7
vuejs-extension-pack|mub|0.1.7
vetur|oct|0.9.3
vuehelper|oys|0.1.0
babelrc|wad|1.0.0
gitblame|wad|2.0.2
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

actually I've no idea how it is happening. I just click the "terminal", and it's not working. <del>so I opened devtool and saw the error stack as in the picture.</del>

Reproduces without extensions: No

**Comment by kieferrm** [comment]
@Aladdin-ADD the error doesn't seem to be related to the terminal issue you experienced.

**Comment by Aladdin-ADD** [comment]
thanks. how can I get the error message on terminal?

**Comment by kieferrm** [comment]
I'm not sure there is any error message. You can try to run Vs Code in verbose mode (`--verbose` command line option) and see if that's bringing us any closer. Any hints about your setup?

**Comment by weinand** [comment]
@Aladdin-ADD what do you mean by "I just click the 'terminal'"?
Does the problem reproduce without extensions?

**Comment by Aladdin-ADD** [comment]
![image](https://user-images.githubusercontent.com/13050025/29065243-0ba09b90-7c5e-11e7-804c-f25623e93c2c.png)

when I restarted the app, it works well, so I didn't have a certain way to repro.

**Comment by weinand** [comment]
So, you can no longer reproduce the problem?

**Comment by Aladdin-ADD** [comment]
yes, But I got this several times. and I've no idea to give you more info. --

**Comment by Tyriar** [comment]
Let us know if you hit it again :smiley:
