### ISSUE TITLE
Can't close the markdown preview, when it's untitled and the security setting has been changed

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32009]
- Open an untitled editor and set the language mode as markdown
- Add the cat markdown from #30879
- Open preview
- Change the security setting
- Click the 'x' or cmd+w to close the preview
- No response 😱 

Debugged out of curiosity and seems like this check in `editorPart.doCloseEditor` fails: `if (group.activeEditor && group.activeEditor.matches(input)) {` because in `areHtmlInputOptionsEqual`, `left.allowSvgs !== right.allowSvgs`.

**Comment by mjbvz** [comment]
Good find.

The `x` doesn't work for you? I can repo the issue with `cmd+w` but can still close the editor when I press `x` on the tab

**Comment by roblourens** [comment]
I have tabs disabled, different code path?

**Comment by roblourens** [comment]
I don't follow how the change fixes it, because it looks like the same code from `matches` is basically inlined in the `if`? But I tried it in master and it works.

**Comment by mjbvz** [comment]
Yes, not a great fix but I wanted to keep the fix scoped this late in the ship cycle.

The logic: we want `editorInput.matches(otherInput)` to return true for the htmlPreview even if the otherInput's security options do not match the current input's. Removing the custom `match` from `HtmlInput` fixes this bug. However when we update the input of the htmlPreview, we want to rerender the contents if the security options have changed. That's where the inlining comes in

**Comment by roblourens** [comment]
Ah now I understand, I was thinking the line in `setInput` was the `closeEditor` line I was looking at last night.
