### ISSUE TITLE
Include root folder name in other usages of the launch config name

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32000]
Picker
![image](https://user-images.githubusercontent.com/323878/28943909-5c4f9b66-7855-11e7-82dc-b2d5aec31970.png)

and callstack

![image](https://user-images.githubusercontent.com/323878/28943919-645c35f8-7855-11e7-99ea-04fff09f9a0c.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/31542
