### ISSUE TITLE
Add a partial filename match to "when context" in key bindings and menu context. (feature request)

### ISSUE THREAD

**Issue by rgilling** [Microsoft/vscode#32006]
- VSCode Version: 1.10.2
- OS Version: MAC OSX

I've searched for a way to do this but cannot find one. I would really love a "when" rule to include a menu or command based on a partial match or a regex match of the filename. It would solve a lot of challenges I'm facing authoring a complex extension.

Something like:

"explorer/context": [{
          "when": "resourceFilename ~= **.jpg",
          "title": "Resize Image",
          "command": "myapp.resizeImage",
          "group": "myapp-nav"
        }
]

**Comment by jrieken** [comment]
There is now `resourceExtname`

**Comment by jrieken** [comment]
and there is actually a regex-match operator, e.g. `foo ~= /o{1,2}/`
