### ISSUE TITLE
High contrast theme accentuates misaligned explorer header border and open tab bar

### ISSUE THREAD

**Issue by DBosley** [Microsoft/vscode#32003]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Switch to high contrast theme
2. Open explorer window
3. Notice the misaligned borders
![image](https://user-images.githubusercontent.com/2766936/28948709-ccd559c4-7874-11e7-9612-b06047263e3c.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@sandy081 moving to you, we never showed a border below the viewlet title and the first section. It seems this is a recent change you did.

**Comment by bpasero** [comment]
There also seems to be a weird bug that this border removes once I click around a little bit:

![image](https://user-images.githubusercontent.com/900690/29206351-e11d8f4c-7e81-11e7-9ac3-1d161b97d328.png)

**Comment by bpasero** [comment]
@sandy081 thanks 👍

**Comment by sandy081** [comment]
@mjbvz There should not be any border below Explorer.
