### ISSUE TITLE
ignores built-in, eslint and prettier settings

### ISSUE THREAD

**Issue by stevensacks** [Microsoft/vscode#32019]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vsc-material-theme|Equ|1.0.2
jsx|Twe|0.0.1
Handlebars|and|0.2.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|0.22.1
auto-rename-tag|for|0.0.14
node-module-intellisense|lei|1.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
peep|nwa|0.0.5
vscode-icons|rob|7.12.0

(2 theme extensions excluded)

---

I am trying out VSC to see if it's worth it to switch from WebStorm and I ran into a deal-breaking show-stopping bug which is preventing me from using it.

I have explicitly set rules for my Javascript formatting in 3 places and VSC just straight up ignores them when I save a file.

I tried using the built-in settings. They didn't work.
I tried including prettier extension. Its settings are being ignored.
I tried using eslint settings as the basis for prettier via prettier-eslint. Also being ignored.

Problem 1:
`const foo = async () => {}` becomes `const foo = async() => {}`

It "eats" the space after async.

Problem 2:
`import {foo} from 'package'` becomes `import { foo } from 'package'`

It injects spaces inside the braces. Even though I have explicitly set not to in two places.

These are my relevant settings:

.eslint (v4.3.0)
```json
"keyword-spacing": ["error", {
    "before": true,
    "after": true
}],
"arrow-spacing": ["error", {
    "before": true,
    "after": true
}],
"object-curly-spacing": ["error", "never"],
```

settings.json
```json
    "prettier.bracketSpacing": false,
    "prettier.eslintIntegration": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
```

This means that as soon as I save a file, it eats spaces after every instance of "async (", and injects spaces inside of import braces. This causes eslint to throw errors (and show them in the editor itself) and the code won't compile in CI.

**Comment by mjbvz** [comment]
You have a number of different formatters all active. Try narrowing things down by deactivating some of them. Start by uninstalling `vscode-JS-CSS-HTML-formatter` because this one has been known to cause issues. You can also disable the builtin vscode formatter by setting:

```json
"javascript.format.enable": false,
"typescript.format.enable": false,
```

**Comment by stevensacks** [comment]
Indeed that plugin was to blame. Uninstalling it fixed the issue.

It's one of the recommended ones when you first install Code. Might want to change that.
