### ISSUE TITLE
Fast two finger scroll in integrated terminal sometimes does not execute

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#32016]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.2
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. Open vscode
2. Open terminal
3. Type enough stuff that you can scroll up and down
4. Do a fast two finger scroll flick (has to be quick enough; essentially something like where you're trying to get back to the bottom after scrolling up a bunch)

Expected: Scrolls down fast
Actual: Nothing; actually nothing happens.  Note: It appears to be an input event queue issue.  If you do a two finger flick and it doesn't scroll, then you just move the mouse (while still in the terminal), the scroll will occur correctly implying that the events are in the queue but just not being drained.  Note also that I'm on a Surface Book (in case that matters) and that this issue does not occur in any other two finger scrolling scenarios so far implying it's not an OS issue.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Tracking in https://github.com/sourcelair/xterm.js/issues/594
