### ISSUE TITLE
Fails to Open File in Local OneDrive Folder

### ISSUE THREAD

**Issue by spncrgr** [Microsoft/vscode#32011]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
javadebugger|don|0.1.3
PowerShell|ms-|1.4.1
java|red|0.8.0

It appears as though vscode is unable to "see" files that are in OneDrive when the Files On-Demand feature is enabled. Repro steps below and I'm including Steps Recorder output.

---

Steps to Reproduce:

1. OneDrive Settings:
  - Enable the new Files On-Demand feature (Settings tab)
  - Set option to save documents and pictures on OneDrive (Auto Save tab)
2. Attempt to open PowerShell profile file saved at `..\OneDrive\Documents\PowerShell\Microsoft.PowerShell_profile.ps1` in vscode
  - Using the command line to open the file in vscode: 
`C:\> code C:\Users\spncr\OneDrive\PowerShell\Microsoft.PowerShell_profile.ps1`
  - Using the vscode UI: Select `File > Open File...` navigate to PS profile file, select it and click OK

Reproduces without extensions: Yes

[vscode-20170803.zip](https://github.com/Microsoft/vscode/files/1199156/vscode-20170803.zip)

**Comment by spncrgr** [comment]
Ironically, I stumbled across issue #27285 a few moments ago while troubleshooting a problem with a different node/electron app. Anyway, I assume it's related to the issue I'm having with vscode.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
