### ISSUE TITLE
The char '(' in a array object ruin the color theme of all code bellow

### ISSUE THREAD

**Issue by hakonamatata** [Microsoft/vscode#32018]
- VSCode Version: 1.14.2
- OS Version: Windows 10
- Node: 7.4.0

The number values are not recognized:

![image](https://user-images.githubusercontent.com/4003969/28957433-2fa48264-78f2-11e7-8595-2bea24e165ea.png)

export, classname etc is also not the right color, everything bellow '(' gets the wrong colors...

![image](https://user-images.githubusercontent.com/4003969/28957581-ba5232ee-78f2-11e7-9a27-f6a2aebd28d7.png)

Removing the '(' character fixes the problem 

![image](https://user-images.githubusercontent.com/4003969/28957490-5d38f4b2-78f2-11e7-8cb2-15f33d4a49be.png)

Removing all instances of '(' above my code fixes the colors of import, class name, etc

![image](https://user-images.githubusercontent.com/4003969/28957595-d154bdc2-78f2-11e7-809b-8abe3a0eeba9.png)

Steps to Reproduce:

1. Add the following: 

```
export class Employee {
  ID: number;
  Head_ID: number;
  Full_Name: string;
  Prefix: string;
  Title: string;
  City: string;
  State: string;
  Email: string;
  Skype: string;
  Mobile_Phone: string;
  Birth_Date: string;
  Hire_Date: string;
}
```

```
const employees: Employee[] = [{
  "ID": 1,
  "Head_ID": 0,
  "Full_Name": "John Heart",
  "Prefix": "Mr.",
  "Title": "CEO",
  "City": "Los Angeles",
  "State": "California",
  "Email": "jheart@dx-email.com",
  "Skype": "jheart_DX_skype",
  "Mobile_Phone": "(213) 555-9392",
  "Birth_Date": "1964-03-16",
  "Hire_Date": "1995-01-15"
}, {
  "ID": 2,
  "Head_ID": 1,
  "Full_Name": "Samantha Bright",
  "Prefix": "Dr.",
  "Title": "COO",
  "City": "Los Angeles",
  "State": "California",
  "Email": "samanthab@dx-email.com",
  "Skype": "samanthab_DX_skype",
  "Mobile_Phone": "(213) 555-2858",
  "Birth_Date": "1966-05-02",
  "Hire_Date": "2004-05-24"
},
```

2.

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
@hakonamatata this is fixed in the latest insiders and will be in the next stable. Thanks!
