### ISSUE TITLE
Profile submission

### ISSUE THREAD

**Issue by e-buttelli** [Microsoft/vscode#32010]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (af2752dad442341000b0bf95861b91ecd8263ca0, 2017-06-02T05:14:12.971Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)</code>
- Memory (System): <code>3.96GB (0.79GB free)</code>
- Memory (Process): <code>152.23MB working set (159.03MB peak, 128.85MB private, 39.05MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>20%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|338|
|main|app.isReady => window.loadUrl()|567|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2257|
|renderer|require(workbench.main.js)|1149|
|renderer|create extension host => extensions onReady()|4804|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1794|
|renderer|overall workbench load|2531|
|main + renderer|start => extensions ready|9529|
|main + renderer|start => workbench ready|6854|

---
[300e_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1199057/300e_main.cpuprofile.txt)
[300e_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1199056/300e_renderer.cpuprofile.txt)

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Buttelli\300e_main.cpuprofile.txt`
-`C:\Users\Buttelli\300e_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Actually nothing suspicious here... Closing without concrete actions but be assured that this Nov we'll solely focus on general performance improvements. Thanks and Happy Coding.
