### ISSUE TITLE
[Feature request] Add squiggles under filenames that have issues

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#32015]
Basically something like this. For some reason I couldn't find an existing feature request for this.  Apologies if it does indeed exist.

![capture](https://user-images.githubusercontent.com/29720335/28956904-34a90abc-78a4-11e7-9711-5f6a31b895e6.PNG)

**Comment by azydevelopment** [comment]
Ping.  Looks like this had the assignee removed without a replacement.

**Comment by mjbvz** [comment]
Support for this has been added with VS Code 1.18 (the current insiders builds). Try setting: `problems.decorations.enabled": true` to enable marking files with problems in the explorer
