### ISSUE TITLE
Snippet expansion drops escaped backslashes.

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#32020]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.12.3-1-ARCH

For snippets with escaped backslashes more backslashes are required than expected. For example, if the snippet has the format `"a\\b"` with `n` backslashes the outputs for various `n` are as follows:

```
2  -> a\b
4  -> a\b
6  -> a\\b
8  -> a\\b
10 -> a\\\b
12 -> a\\\b
...
```

Given that the output for 2 backslashes is identical to the output with 4 backslashes suggests that something is off here.

Steps to Reproduce:

1. Create a snippet like this:

```JavaScript
"Test": {
	"prefix": "test",
	"body": "a\\\\b"
}
```

2. Insert snippet.
3. Check output for number of backslashes.
4. Expected: 2 | Actual: 1

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
> Expected: 2 | Actual: 1

Actually, no. Apologies, but it's messy. Textmate escapes a backslash with a backslash, so to insert one backslash, `\\` must be typed. Now comes, JSON which also needs a backslash to escape a backslash making this `\\\\`

**Comment by brunnerh** [comment]
That is rather inconsistent and confusing, but if nothing can be done about this anyway because this is an issue with an external component this might as well be closed.

**Comment by jrieken** [comment]
> That is rather inconsistent and confusing, but if nothing can be done about this anyway because

Yeah, unfortunate. #25661 is about allowing to write snippets in another non-json format. That would remove the need for double backslashes. However, the backslash vs escaped backslash issue is how text mate works. 

Closing this with the pointer towards #25661
