### ISSUE TITLE
C# for visual studio code extension and omni sharp not installing correctly

### ISSUE THREAD

**Issue by dvkpl** [Microsoft/vscode#32025]
- VSCode Version: 1.14.2
- OS Version: win10 64bit

Steps to Reproduce:

1. Install C# extension
2. Create a .cs file

Expect

1. Extension to work correctly 

Actual 

1. In output after  downloading and installing  packages this shows up : 
Failed to spawn 'dotnet --info'

Reproduces without extensions: No

**Comment by kieferrm** [comment]
@dvkpl pls file an issue against the C# extension. This is the link https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks a ton!
