### ISSUE TITLE
Cannot recognize .gitignore when open subfolder of a repository

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#32023]
- VSCode Version: 1.14.2
- OS Version: win10

Steps to Reproduce:

1. Make a git repository (assume it's `E:/repo`)
2. Open folder `E:/repo/sub` in VsCode
3. `E:/repo/.gitignore` ignored /sub/test.txt
4. create a file `E:/repo/sub/test.txt`

**Expect**
`test.txt` not appear in changelist

**Actual**
`test.txt` does appear in changelist

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What does `git status` return?

**Comment by k8w** [comment]
in `E:/repo/sub`, `git status` return changelist include `test.txt`
but
in `E:/repo`, it not include.

And in `1.14.0` and `1.14.1` there is no this problem

**Comment by k8w** [comment]
Expect changelist is relative to git repository path, rather than VsCode open folder.

**Comment by k8w** [comment]
.gitignore in git repository root folder (not vscode open folder) not work.

**Comment by joaomoreno** [comment]
> in E:/repo/sub, git status return changelist include test.txt

So, git itself shows `test.txt`... just like Code.

Are you sure there's no folder `E:/repo/sub/.git`?

**Comment by k8w** [comment]
@joaomoreno Oh... yes...
Truely there is `E:/repo/sub/.git`...
Don't know how this appear... 
Works well after remove it...
