### ISSUE TITLE
Command window not auto close after open code

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#32024]
- VSCode Version: 1.14.2
- OS Version: win10

Steps to Reproduce:

1. Win+R
2. type code
3. Enter

**Expect**
1. VsCode open and cmd close

**Actual**
1. cmd was closed until vscode close

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
The problem with this is that Windows promotes `code.cmd` instead of `code.exe`. We've filed that issue to Windows and got confirmation that they will fix it in the future.
