### ISSUE TITLE
[jade] Incorrect syntax highlighting of comments

### ISSUE THREAD

**Issue by jomeier** [Microsoft/vscode#3202]
Hi,

comments in '//' style only get syntax highlighting, if no empty line is above them.

'' style comments don't work at all.

Best regards,

Josef

**Comment by Tyriar** [comment]
Verified, reported again here http://stackoverflow.com/questions/35504612/vs-codes-jade-syntax-highlighting-is-bad

**Comment by aeschli** [comment]
Filed against the Jade grammar as https://github.com/davidrios/jade-tmbundle/issues/74

**Comment by aeschli** [comment]
This got fixed in the meantime.
