### ISSUE TITLE
Markdown mode cannot open links that contains some codes by percent-encoding.

### ISSUE THREAD

**Issue by kou1okada** [Microsoft/vscode#32026]
I wrote some links to web page and clicked it.
But all links, that were containing code of 0x80-0xff by percent-encoding, could not open browser.

For example:

~~~
* Following links can open browser:
  * [@](https://www.google.co.jp/search?q=%62%69%67)
  * [@](https://www.google.co.jp/search?q=%00) (only Linux)
  * [@](https://www.google.co.jp/search?q=%01)
  * ...
  * [@](https://www.google.co.jp/search?q=%7f)
* Following links cannot open browser:
  * [@](https://www.google.co.jp/search?q=%91%E5)
  * [@](https://www.google.co.jp/search?q=%00) (only Windows)
  * [@](https://www.google.co.jp/search?q=%80)
  * ...
  * [@](https://www.google.co.jp/search?q=%ff)
~~~

Every links show balloon tips of "Ctrl + click to follow link".
And the preview mode of markdown shows same behavior.

My environment is below:
* Windows
  * Windows 7 Ultimate 64bit Japanese
  * vscode 1.14.2
  * Firefox 54.0.1 64bit
* Linux
  * Ubuntu 14.04.5 LTS 64bit
  * vscode 1.14.2
  * Firefox 54.0 64bit

Good regard.

**Comment by mjbvz** [comment]
@jrieken The root cause is that `Uri.parse('https://www.google.co.jp/search?q=%91%E5')` throws an error when we call `decodeUriComponent('q=%91%E5')`

Problem is also related to #31805

**Comment by jrieken** [comment]
Interesting...

**Comment by kou1okada** [comment]
Related issues:
* #25852 : still open.
* #31805 : [closed](https://github.com/Microsoft/vscode/issues/31805#event-1317096973) by @jrieken because dupe of #25852.
* #32026 (this issue) : [auto closed](https://github.com/Microsoft/vscode/issues/32026#event-1837981804) by @vscodebot because `*out-of-scope` label was [set](#event-1837981592) by @jrieken.
* #41837 : [closed](https://github.com/Microsoft/vscode/issues/41837#event-1435421239) by @jrieken because dupe of #25852.
* #53824 : [auto closed](https://github.com/Microsoft/vscode/issues/53824#event-1722811339) by @vscodebot because `needs more info` label was [set](https://github.com/Microsoft/vscode/issues/53824#event-1722811339) by @jrieken.

Does this issue take over to #25852?
But I could not find progress about #25852 since 31 Oct 2017.
I hope this issue will be solved.

Good regard.
