### ISSUE TITLE
How to write a code snippet generating current time?

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#32021]
- VSCode Version: 1.14
- OS Version: Ubuntu 14.04

I want to write a code snippet used to write the time when I write the code.
For example, I define a code snippet named timeit, and then when I write timeit, it will generate:

> write on 2017.8.4

However, I don't know how to generate the current time. Please give me some advice. Thank you.

Reproduces without extensions: Yes/No

**Comment by matt-erhart** [comment]
Yea, I'd like to know this as well.

**Comment by Kongsea** [comment]
@matt-erhart This extension https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring can also insert date and time.
However, both this one and your extension need manual insertions. I wonder if the snippets can support to generate time automatically.
Anyway, thank you.
