### ISSUE TITLE
Clicking in console when VSCode not current app requires another click

### ISSUE THREAD

**Issue by probedb** [Microsoft/vscode#32027]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:08:57.197Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.2
sublime-babel-vscode|jos|0.2.6
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.7
vscode-react-native|vsm|0.4.0

---

Steps to Reproduce:

1. Open any VSCode window and open the built in console
2. Focus on any other application
3. Click back to console in VSCode
4. Expect cursor to activate in console but instead main editor window becomes active

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/24634
