### ISSUE TITLE
FR: File: Avoid saying "file is not a valid filename"

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#32022]
- VSCode Version: Code - Insiders 1.15.0-insider (1af52c0470d6f445966b5c8a3065233b34303d9a, 2017-08-04T05:16:35.372Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
gitignore|cod|0.5.0
vscode-dash|dee|1.7.0
css-minify|Die|0.0.4
vscode-npm-source|dku|1.0.0
python|don|0.7.0
gitlens|eam|4.3.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
gc-excelviewer|Gra|1.1.15
composer|ika|0.5.0
smarty|imp|0.2.0
code-guid|jam|1.0.1
StretchTimer|jpa|0.0.1
json-to-ts|Mar|1.5.2
Runner|mat|0.1.14
vscode-apache|mrm|1.1.1
cpptools|ms-|0.12.2
github-issues-prs|ms-|0.4.0
php-docblocker|nei|1.2.0
emoji|Per|0.0.3
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.12.0
sharecode|Rol|0.4.1
todotasks|san|0.5.0
code-settings-sync|Sha|2.8.2
vscode-spotify|shy|2.0.0
packagelinker|sin|0.0.3
code-spell-checker|str|1.3.2
pdf|tom|0.2.0
lorem-ipsum|Tyr|1.0.0
vscode-arduino|vsc|0.2.4
vscode-todo-highlight|way|0.5.8
vscode-import-cost|wix|1.3.1
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

I want to create a file inside a folder, but this folder does not exist, yet. I would like when it automatically makes the path, instead of complaining about my filename.
![image](https://user-images.githubusercontent.com/11234139/28965422-41697e4a-7911-11e7-9245-d2edc1a1a901.png)

**Comment by wangweixuan** [comment]
Duplicate of #12893.
Currently you can have a look at the ['vscode-new-file' extension](https://github.com/dkundel/vscode-new-file).

**Comment by jens1o** [comment]
Ah, okay, thanks for the hint. :)
