### ISSUE TITLE
Quick Open | Quick Search no longer finding files deeply nested within project root.

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#32031]
- VSCode Version: Code - Insiders 1.15.0-insider (1af52c0470d6f445966b5c8a3065233b34303d9a, 2017-08-04T05:16:35.372Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
Handlebars|and|0.2.0
extlibraries|dan|0.0.3
vscode-eslint|dba|1.2.11
template-generator-vscode|Den|0.1.0
html-symbols|Die|0.0.2
python|don|0.7.0
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.6.31
r|Iku|0.4.1
coldfusion|ili|0.0.10
google-complete-me|jay|1.0.6
graphql-for-vscode|kum|1.4.2
vscode-simple-icons|Lau|1.5.0
evermonkey|mic|2.3.15
dotenv|mik|1.0.0
vscode-todo-parser|min|1.9.0
mssql|ms-|1.1.0
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.1.7
embrace|myc|1.0.0
vetur|oct|0.9.3
vscode-docker|Pet|0.0.16
vscode-template-literal-editor|pli|0.8.4
java|red|0.8.0
code-settings-sync|Sha|2.8.2
language-stylus|sys|1.7.3
vscode-todo-highlight|way|0.5.8
licenser|ymo|1.0.1
vsc-docker|Zim|0.9.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Type `ctrl+p` search for a file within a specific folder by name returns no results.

Reproduces without extensions: Yes 

Prior to the last 2 insider builds, I was able to search for a file anywhere within the project, or a file within a specific directory example :
- listings folder deeply nested within the root of the project, `ctrl+p` `listings layout.html`
- the results used to return the layout.html file within that folder. 
- it now returns no result, almost seems as if the quick open doesn't respect folders in the search

**Comment by roblourens** [comment]
Stuff around quickopen search has changed, but nothing that should have affected this. I can't repro it. Can you try some more things to help me figure it out?

- Do you get the right file if you just search `layout.html`?
- What about `listings/layout.html`?
- If you just enter `listings`, do you see files in that folder?
- Do you have any `files.exclude` settings that might be interfering?

**Comment by rwatts3** [comment]
Ah, good catch. 

So it looks like by default in one of the last releases, files.exclude automatically excludes files in node_modules.

The folder structure uses node_modules to put all of the template files, which is where one of the files I was trying to update was located.

It's not a true node_modules directory, but rather a pattern that we use to extend the core functionality. 

After removing **/node_modules in project settings I am now able to search just as I was before.
