### ISSUE TITLE
Enable search.useIgnoreFilesByDefault by default

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32035]
When we enabled .gitignore support in search, we couldn't enable it by default, because we didn't want to confuse people who upgrade vscode and then see fewer search results. So, we added this option to determine whether .gitignore files should be respected by default in new workspaces. After you do a search in a workspace for the first time, it will persist whether respecting .gitignore files is enabled. This has led to some confusion, #28332, #24030, and more.

I think that setting was only necessary for a couple releases. Now that the button is out there, current states are persisted, I think we should enable the setting by default. It won't fix the problem necessarily but it should diminish it over time.

**Comment by roblourens** [comment]
Related, @chrmarti let's think about how to enable gitignore support for ripgrep in quickopen. Do we need a UI button like search, or can we get by with a setting to enable/disable it?

**Comment by chrmarti** [comment]
I'd go with a setting initially. If/when we add UI to quickly turn this on/off, I'd also like a button to turn off all filters. (E.g., to open a generated .js that is normally filtered.)

**Comment by roblourens** [comment]
Do you think it would be ok for it to be enabled by default initially, or should we wait a month for that?

**Comment by chrmarti** [comment]
I'd keep it disabled by default because it is not as easily discoverable as a button in the UI and users might wonder why they are missing results when filtering by .gitignore is not what they want.

**Comment by roblourens** [comment]
Per our discussion the default here should match quickopen and we can change that next month or later.
