### ISSUE TITLE
Syntax Highlighting For PHP Broken When Using Trait Classes

### ISSUE THREAD

**Issue by M-Porter** [Microsoft/vscode#32036]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
EditorConfig|Edi|0.9.4
laravel-blade|KTa|0.0.1
ejs-language-support|Qas|0.0.1
ActiveFileInStatusBar|Ros|1.0.2
jsx|Twe|0.0.1
sort-lines|Tyr|1.3.0
scratchpad|awe|0.1.0
gotemplate|cas|0.1.1
code-wsync|mpo|0.0.1
vscode-eslint|dba|1.2.11
python|don|0.7.0
prettier-vscode|esb|0.22.1
php-debug|fel|1.11.1
docthis|joe|0.4.7
php-symbols|lin|2.1.0
Go|luk|0.6.63
prettify-json|moh|0.0.3
atom-keybindings|ms-|3.0.1
php-docblocker|nei|1.2.0
vetur|oct|0.9.3
Ruby|reb|0.13.0
vscode-icons|rob|7.12.0
stylelint|shi|0.28.0
simple-ruby-erb|vor|0.2.1
twig|wha|1.0.2
jinja|who|0.0.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. New File
2. Set Syntax to PHP
3. Insert code snippet:
    ```php
    <?php

    class MyClass
    {
        use \My\TraitClass;

        /**
         * @param string $a
         * @return string
         */
        public function myFunction($a)
        {
            return ':(';
        }
    }
    ```

Reproduces without extensions: Yes

---

I believe this a very recent breakage because I have not noticed this before and I use a decent amount of trait classes.

Currently what it looks like:

<img width="385" alt="screen shot 2017-08-04 at 11 34 19 am" src="https://user-images.githubusercontent.com/2313263/28982141-902f39c8-7909-11e7-8d4e-9a34f19daef8.png">

Expected (had to set syntax to blade to get it to look correct):

<img width="399" alt="screen shot 2017-08-04 at 11 34 11 am" src="https://user-images.githubusercontent.com/2313263/28982156-9bdecdb0-7909-11e7-934a-0f9f7d726394.png">

**Comment by roblourens** [comment]
This should be fixed in the Insiders build, would appreciate it if you try it out there.

https://code.visualstudio.com/insiders

**Comment by M-Porter** [comment]
Oh dope. Works. Thanks @roblourens!
