### ISSUE TITLE
[json] project.json intellisense broken due to server change

### ISSUE THREAD

**Issue by richarddavenport** [Microsoft/vscode#3204]
Trying to get packages from nuget. I'm not getting intellisense in project.json. In the JSON server output window I see a lot of this:
`Request to the nuget repository failed: <?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code /><m:message xml:lang="en-US">URI or query string invalid. Query option 'Format' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.</m:message></m:error>`

Running OS X 10.11.3 VS Code 0.10.9-insider and 0.10.9

**Comment by aeschli** [comment]
Looks like the nuget server disabled JSON accesses

**Comment by aeschli** [comment]
Delivered to 0.10.11 branch
