### ISSUE TITLE
"---" is not seen as a block delimiter

### ISSUE THREAD

**Issue by wsw70** [Microsoft/vscode#32047]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. create an `.html` file
2. add the following content:

```
---
this is frontmatter
---
<div>
this is a normal block
</div>
```

3. reformat the code via `F1 -> Format Document`

The reformatted code is 

```
--- this is frontmatter ---
<div>
this is a normal block
</div>

```

--> frontmatter information was destroyed and the file is not usable as a template anymore.

Reproduces without extensions: Yes

This problem is somewhere in the gray  zone between a bug (strictly speaking, it is not) and configuration (the behaviour as it is now breaks template files, making a function unusable)

**Is it possible to have `---` treated as a block delimiter?**

**Comment by aeschli** [comment]
We use jsbeatify as formatter for HTML.
The bug there is https://github.com/beautify-web/js-beautify/issues/510
