### ISSUE TITLE
Plug-in installation command problem

### ISSUE THREAD

**Issue by bcahlit** [Microsoft/vscode#32046]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-docker|Pet|0.0.16

---

Steps to Reproduce:

1.Create a new .py file and save, prompt to install the pylint plugin.
2.Click on the installation, run the command in poershell:
`"D: \Program Files\Python36\python.exe" -m pip install pulint`
Will perform the error, it should actually be
`&"D: \Program Files\Python36\python.exe" -m pip install pulint`
or
`python -m pip install pulint`

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
I'm guessing the Python extension is prompting you to install `pylint`. Pls file the issue against the Python extension here: https://github.com/DonJayamanne/pythonVSCode/issues. Thanks!
