### ISSUE TITLE
Exception if file is missing.

### ISSUE THREAD

**Issue by anacierdem** [Microsoft/vscode#32040]
Steps to Reproduce:
In a definition provider extension;

1. Call `let newDocument = vscode.workspace.openTextDocument(newUri);` with a non existent file.
2. Handle the promise with `.then(resolve, reject)`

In the console, the extension throws;

`[uncaught exception]: [object Object]`

Also see [this](https://github.com/anacierdem/vscode-requirejs/pull/34)

**Comment by weinand** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/32138
