### ISSUE TITLE
textEditor.revealRange always scrolls to left horizontally

### ISSUE THREAD

**Issue by kirill-kruchkov** [Microsoft/vscode#32049]
- VSCode Version: 1.15.0-Insider
- OS Version: MacOS Sierra 10.12.6

`textEditor.revealRange` with specified lines range and character scrolls to the `0` character:
```
onCursorMove(e: vscode.TextEditorSelectionChangeEvent) {
  e.textEditor.revealRange(new vscode.Range(
                        Math.max(selection.active.line - 10, 0), selection.active.character,
                        selection.active.line + 10, selection.active.character),
                        vscode.TextEditorRevealType.Default
  );
}
```

So when I navigate to the EOL it's okay, then I press e.g. left then cursor goes one position left and horizontal scroll goes to zero:
![](https://media.giphy.com/media/3o6vXSBQtyFEtBGVdm/giphy.gif)

Also:
- selection.active.character is not zero (at the end of the line),
- seems like it doesn't depend on the revealType.

**Comment by alexandrudima** [comment]
@kirill-kruchkov You are revealing a range of 20 lines, 10 lines above and 10 lines below the current selection. A range of 20 lines is visibly a rectangle:

In the following picture I've highlighted what a range of 20 lines looks like.
<img width="1048" alt="screen shot 2018-04-18 at 21 55 36" src="https://user-images.githubusercontent.com/5047891/38954900-555957f6-4353-11e8-8fec-47b2edaf4f6f.png">

The editor will try to reveal as much as possible from the area of those 20 lines and that happens to always be at `scrollLeft` = 0, as if the editor would scroll to the right (for example) the lines without any characters or with a single character would not be visible.
