### ISSUE TITLE
怎样调整代码折叠的风格?

### ISSUE THREAD

**Issue by jstcodes** [Microsoft/vscode#32052]
- VSCode Version:
- OS Version:

Steps to Reproduce:

希望的风格
[查看图片](https://raw.githubusercontent.com/jstcodes/source/60603aada06ba4750a5849d00cbddcb11454b6bb/img2.png)

实际的风格
[查看图片](https://raw.githubusercontent.com/jstcodes/source/master/img1.png)

Reproduces without extensions: Yes/No

**Comment by yoyo837** [comment]
extension：js-beautify for VS Code

use .jsbeautifyrc configration file.

https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify

```
code --install-extension HookyQR.beautify
```

**Comment by jstcodes** [comment]
[还是不行啊](https://raw.githubusercontent.com/jstcodes/source/master/img3.png)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/3352
