### ISSUE TITLE
Bug in stylelint: Value is not accepted. Valid values: ["between-comments","stylelint-commands"]

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#32056]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Install this [stylelint](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint) extension
2. Add a `.stylelintrc.json`  file
3. Copy the stylelint configuration from https://stylelint.io/demo/ and paste it on `.stylelintrc.json` 
4. Add a `"after-comment"` option to the `ignore` of `comment-empty-line-before`. Your code should look like this:
```
      "comment-empty-line-before": [
        "always",
        {
          "except": [
            "first-nested"
          ],
          "ignore": [
            "after-comment", "stylelint-commands"
          ]
        }
      ],
```
Reproduces without extensions: No

I have checked the extension source code and it uses **stylelint 8.0.0**

**Comment by kieferrm** [comment]
@fab1o Although you already figured out that this is an issue with the `stylelint` extension, you unfortunately ended up in the wrong repo. Pls file the issue against the extension here: https://github.com/shinnn/vscode-stylelint/issues Thanks!
