### ISSUE TITLE
A error message of comment print in output of console 

### ISSUE THREAD

**Issue by ygxdxx** [Microsoft/vscode#32059]
- VSCode Version: 1.14.2
- OS Version: 10.12.5 

Steps to Reproduce:

when clicking on comment on HTML file .A error message `Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined` printed in console of output

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
@ygxdxx I can't reproduce with a vanilla 1.14.2 and a html file. Anything else you can provide to reproduce the issue?

**Comment by xithiox** [comment]
@kieferrm I've also had this issue in VSCode Version 1.14.2 and macOS 10.12.6. It only seems to occur for me when clicking on JavaScript comments within the <script></script> tags. It does not occur on normal HTML comments. It also does not occur in normal JavaScript files.

**Comment by aeschli** [comment]
duplicate of #30774
