### ISSUE TITLE
Support similar font in explorer and editor views

### ISSUE THREAD

**Issue by qdoop** [Microsoft/vscode#32051]
Currently explorer uses a different font from editor and worse it is a poportional one making work with files and folders little bit confusing.
A setting like explorer.fontFamily is missing while editor.fontFamily exists.

IMO having at least an option for  editor and explorer to share the same font family would be great.
I could prepare a PR for this feature if approved.

FYI the following patch in workbench,main.css does the trick for me but VSCODE complains about integrity
```
.folder-icon.explorer-item > a.label-name{color: white!important}
.file-icon.explorer-item > a.label-name{color: green!important}
.explorer-item > a.label-name{font-family: Consolas!important}
```

**Comment by rektrex** [comment]
Can you tell me where the css file is located, please?

**Comment by sbovyrin** [comment]
+1

**Comment by luqiangbo** [comment]
+1

**Comment by joezimjs** [comment]
+1

**Comment by Xarkam** [comment]
@isidorn if you tag as duplicate, thanks to link the other issue.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/519

**Comment by Xarkam** [comment]
@isidorn Thank you very much
