### ISSUE TITLE
Can't hide activity bar if two VSCode windows opened

### ISSUE THREAD

**Issue by life777** [Microsoft/vscode#32055]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open two VSCode (two different projects) 
2. Make a right click on Activity bar in the first window
3. Click "Hide activity bar"

![1](https://user-images.githubusercontent.com/891497/28999267-15b8d596-7a49-11e7-9fac-fcd7b3cda308.png)

Expected: Activity bar is closed  (in second window it works)
Actual: Activity bar isn't closed

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
The first hide worked for me as expected but subsequent toggle commands reproduced the issue.

**Comment by bpasero** [comment]
I cannot reproduce. @kieferrm can you share your exact steps?

**Comment by life777** [comment]
@bpasero 

1) Open first VSCode window with some project with shown active bar:

![1](https://user-images.githubusercontent.com/891497/29208982-e5bda100-7e94-11e7-86b0-c235e6346794.png)

2) Open second VSCode window with **another** project (Ctrl + Shift + N).
3) In just opened second window hide and show again active bar
4) Go to the first window and try to hide active bar

**Comment by bpasero** [comment]
@sandy081 this looks like a bug to me with regards to the configuration editing service. I verified that I call the configuration editing service correctly inside the [`ToggleActivityBarVisibilityAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions/toggleActivityBarVisibility.ts#L38) but the value is never applied to the settings file after all. There is also no error thrown.

I assume that maybe the one window's configuration editing service sits on a stale version of the thing and that prevents the update from being written to the settings file?

**Comment by sandy081** [comment]
@bpasero Do not understand how the configuration editing services has a stale version of the settings file. Going a bit deep, it uses `[ITextModelService](https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/services/resolverService.ts#L1)` to get the model. 

Also will investigate, why there was no error shown if it is stale.

**Comment by bpasero** [comment]
We can also debug together.

**Comment by sandy081** [comment]
I am no longer able to reproducing this issue in Stable and Insiders.

@life777 Can you please try on Insiders/Stable version and let me know  if you do ?

**Comment by life777** [comment]
Everytihng is great. 
Thanks a lot
