### ISSUE TITLE
Disable auto-completion for Chinese language

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#32057]
I am now using VS Code to writing some articles in Chinese language. However, the auto-completion is annoying when typing Chinese words.

Look at this picture. Even when I type into a comma, it will give you some advice. Really unnecessary!

![default](https://user-images.githubusercontent.com/18233088/29000024-c8242892-7a90-11e7-8a60-7e32fd625db1.png)

How to disable auto-completion *only* for Chinese language? Or at least I hope to disable it at specific characters like punctuations (eg. `，`, `；` and `。` in Chinese).

- VSCode Version: 1.14.2
- OS Version: Windows 10

PS: I'm writing LaTeX articles with extension LaTeX Workshop.

**Comment by kieferrm** [comment]
@Stone-Zeng we don't have a way to disable it based on locale. You could disable it for latex files though. Use the following snippet for your user settings. Rather than `markdown` use the language mode your extension contributes:
```json
    "[markdown]": {
        "editor.wordBasedSuggestions": false
    }
```
