### ISSUE TITLE
Incorrect syntax highlighting without semicolon

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#3206]
![before](https://cloud.githubusercontent.com/assets/3099626/13201755/ae74be3c-d8a4-11e5-951b-b3edc1f85223.png)

![after](https://cloud.githubusercontent.com/assets/3099626/13201756/c258c114-d8a4-11e5-9f59-a9a2f8968707.png)

**Comment by egamma** [comment]
@aeschli I thought I saw a fix on this in the tmGrammar repository. We should look into taking a newer drop of the grammars for the Feb update.

**Comment by aeschli** [comment]
We have already updated a week ago and this seems to work now.

**Comment by xeoneux** [comment]
@aeschli This is from version 0.10.9, if it helps. :smile:
