### ISSUE TITLE
Grammar error in the Info prompt

### ISSUE THREAD

**Issue by ankitscribbles** [Microsoft/vscode#32068]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm-script|eg2|0.2.0
search-node-modules|jas|1.1.1
gauntlet|Mic|2.0.0
csharp|ms-|1.11.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. There is a grammatical error in the Info dialog that prompts the user to open a folder first. Instead of "Please open an folder first" it should say "Please open a folder first"
![image](https://user-images.githubusercontent.com/28040485/29005718-3e68a028-7a96-11e7-98a7-2fe055c5cdc9.png)

2.

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
@ankitscribbles I just searched for the string in our core code and there is no such string. Please file an issue against the extension that opens this alert. Thanks!
