### ISSUE TITLE
Use vscode as textarea in my webpage to edit code

### ISSUE THREAD

**Issue by SoftTimur** [Microsoft/vscode#32065]
I have a website built by mean-stack, and a page containing a textarea to edit some web code (html & css & javascript) like a playground. I used to use `ui-codemirror` and `ui-ace` to implement this textarea, but now, I am wondering if it is possible to use vscode?

So my questions are:

1. is it legal, given the IP of my website does not belong to Microsoft?
2. does vscode work well with angularjs 1.6 or 1.5 (ie, `ng-model`)?
3. is there any tutorial to let me get started?

Thank you

**Comment by mjbvz** [comment]
You probably want the Monaco editor: https://github.com/Microsoft/monaco-editor It is licensed under the MIT License and should work with any framework with the correct adapters
