### ISSUE TITLE
VS Code Windows installer unnecessarily slow due to text rendering

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#32067]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16257
- Extensions: none
---

Steps to Reproduce:

1. Install an update or new version of VS Code.
2. Observe system CPU usage and how long the installer takes.

VS Code's Windows installer appears to be CPU-bound. The installer has to copy a large number of small files (particularly in node_modules). It also appears to update a string in the UI with the name of the current file being copied. Text layout and rendering is a CPU-expensive operation, and the CPU overhead of updating the UI string with the current filename can be larger than the actual time it takes to copy the file. Therefore installation time is mainly bound on how quickly the system can layout and render text, rather than I/O performance. This is the same reason modern versions of Windows throttle the updates when copying files to ~4 times a second, since it helps achieve better throughput with fast storage.

I would guess VS Code's installer could be a lot faster if it did the same kind of throttling, and that would be nice to make update prompts less inconvenient.

**Comment by jens1o** [comment]
Maybe this would improve the performance for Insider users, too. Because yeah, it takes really long.

**Comment by joaomoreno** [comment]
I hardly doubt that text layout and rendering is what makes the update slow. There are really a LOT of highly compressed files in the update package and that is what really makes it slow.

Improving update (percepted) speed can be tracked in #13308

**Comment by AshleyScirra** [comment]
@joaomoreno - I wouldn't be so quick to dismiss it, it's known that skipping window painting can improve performance: https://blogs.msdn.microsoft.com/oldnewthing/20060220-00/?p=32233/

**Comment by jens1o** [comment]
Sorry for the rant:

Microsoft developers are using techniques Microsoft highly discourages when other developers are using those techniques.

**Comment by joaomoreno** [comment]
Note that we leverage Inno Setup for our setup package, which has its own issue repository: https://github.com/jrsoftware/issrc

**Comment by jens1o** [comment]
But why are you(or we?) depend on that, while electron provides a very nice, awesome api to implement that in our way?

**Comment by joaomoreno** [comment]
@jens1o https://code.visualstudio.com/updates/v0_8_0

Maybe those issues have been fixed then, but the move was purposeful.
