### ISSUE TITLE
Nodejs Infinity printed as undefined

### ISSUE THREAD

**Issue by buckle2000** [Microsoft/vscode#32064]
- VSCode Version: 1.14.2 (currently latest stable release)
- OS Version: Windows 10.0.10586
- nodejs version: 8.2.1

Steps to Reproduce:

1. create a nodejs script
> console.log(Infinity)
> console.log(-Infinity)

2. run in **debug** mode

See the output in vscode "debug output" panel! 😄 

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Problem occurs with the "inspector" protocol.
Works fine for "legacy" (but only for node versions < 8.0).
