### ISSUE TITLE
Setting to Open VSCode with Open Editors Closed

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#32066]
By default, when you open a project in VSCode it always has the Open Editors tab open in the side column. As you start working, all the open files show up here, pushing your project files below it down. 

![open editor](https://user-images.githubusercontent.com/249218/29004354-e3c24932-7a7a-11e7-9c77-a4c64baae518.png)

I always have to immediately close the Open Editors tab to stop it from pushing all my files down. I'd prefer a user setting like:
```
{
   editor.openEditors: false
}
```
That way Open Editors would be closed when I open VSCode.

**Comment by kieferrm** [comment]
@rbiggs this is the setting that does the trick:
```json
    "explorer.openEditors.visible": 0
```

**Comment by rbiggs** [comment]
OMG! That works. Of course, it completely hides the open editor. But in my case I never use it, so I won't miss it.
