### ISSUE TITLE
can not recognize '.pyx' file (python C extensions)

### ISSUE THREAD

**Issue by ChainGank** [Microsoft/vscode#32063]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.4.0-89-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
@ChainGank please file an issue against the python extension here: https://github.com/DonJayamanne/pythonVSCode/issues Thanks!
