### ISSUE TITLE
Feature request: Action for opening a new integrated terminal with a non-default shell

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode#32062]
There is currently a keyboard shortcut mapping for `workbench.action.terminal.new`, which opens a new terminal instance of the default shell type. There's also a mapping for `workbench.action.terminal.selectDefaultShell`, although I can't find a setting in `settings.json` that this changes.

I'd like to see a new action, e.g. `workbench.action.terminal.newNonDefault`, which opens up the same select list as for `selectDefaultShell` but instead of setting the default, just opens an instance of the selected type. This would enable me to have PowerShell as my default, but open a bash or cmd shell every now and then without having to change the default back and forth.

**Comment by Tyriar** [comment]
I recommend checking out this extension which gives you a command to select the shell https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
