### ISSUE TITLE
Text is blurring 

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#32071]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1.Install VSCode and compare the window header with all other texts in the app. Notice the window header is rendered with good quality, but all other text is blurring:
![image](https://user-images.githubusercontent.com/12115586/29007227-4356d88a-7ab3-11e7-9b58-f2e3ee9086ac.png)

2.Open properties of code.exe and change compatibility settings:
![image](https://user-images.githubusercontent.com/12115586/29007188-b4c592d2-7ab2-11e7-8c86-2630b35c0e19.png)

3. Restart VSCode and see blurring disappeared:
![image](https://user-images.githubusercontent.com/12115586/29007215-1c7aea76-7ab3-11e7-8001-17a43afdadc7.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24957
