### ISSUE TITLE
[html] Incorrect auto formatting JavaScript in .html file

### ISSUE THREAD

**Issue by Yoctillion** [microsoft/vscode#32076]
- VSCode Version: 1.14.2
- OS Version: Windows 10, macOS 10.12 (tested)

Steps to Reproduce:

1. Copy a code block that contains line break
2. Paste it to anywhere

For example
![screenshot1](https://user-images.githubusercontent.com/11324635/29011676-8588b4ee-7b67-11e7-8504-db10ed8309ce.png)
or
![screenshot2](https://user-images.githubusercontent.com/11324635/29011690-a3cd9410-7b67-11e7-8903-3409f05d6825.png)
expected:
![2017-08-07 11 59 37](https://user-images.githubusercontent.com/11324635/29011750-1f57900e-7b68-11e7-921a-71622e2b7d1a.png)

HTML and css block also have this problem.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
```
<html>

<head>
	<script>
		console.log();
		console.log();
	</script>
</head>

</html>
```
Tried in  1.39.0-insider and this seems to work now.
