### ISSUE TITLE
Don't show right sidebar when there is only one definition

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3207]
For the screenshot below I did a quick on a function for which there is only a single definition.

If there is only a single defintion, then right sidebar adds no value and it should not be shown. 

![image](https://cloud.githubusercontent.com/assets/172399/13202003/a3bf817c-d889-11e5-9578-c5f25b74959c.png)

**Comment by jrieken** [comment]
> This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
