### ISSUE TITLE
Delete files not found in trash

### ISSUE THREAD

**Issue by anandchakru** [Microsoft/vscode#32078]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions:

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
java|red|0.8.0

---

Steps to Reproduce:

1. Delete a directory using r-click ->Delete
2. Select Move to Trash
3. Go to Trash, get disappointed

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
AFAIK electron attempts to do this using various libraries on Linux already.

**Comment by malone6** [comment]
I have the same problem. After my test, I found the deleted file where 
<mounted_disk>**/.Trash-1000/files/**<deleted_file_name>

you can use command`find / -name "delete_file_name"` to find the deleted file.
this ".trash-1000" floder in the mounted disk.
And, every file that is deleted will be classified under the mount disk where the project is located.
@anandchakru

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by anandchakru** [comment]
@bpasero I'm **not** able to reproduce it with
VSCode Version: 1.30.2
OS Version: 4.15.0-43-generic
