### ISSUE TITLE
遇到中文注释就会报错

### ISSUE THREAD

**Issue by qianzhangsheng** [Microsoft/vscode#32072]
- VSCode Version:版本 1.14.2 (1.14.2)
- OS Version:macOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1.光标点击到中文注释以后，“输出”会报错，禁用所有插件也还是报错，报错信息如下:
```
[Error - 8:12:49 AM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603 

```
视频连接：http://weibo.com/tv/v/Ffyra51bl?fid=1034:f43532daf33598d212e0910f9d5c9d1c

Reproduces without extensions: Yes

**Comment by King66** [comment]
https://github.com/Microsoft/vscode/issues/30774

和中文没关系。👎

comments in script tag in html files.

**Comment by qianzhangsheng** [comment]
谢谢楼上指点

**Comment by qianzhangsheng** [comment]
谢谢楼上 💯

**Comment by xjy666** [comment]
这个问题您是怎么解决的？或者可以告诉我这个输出窗口怎么不让它继续弹出来？

**Comment by King66** [comment]
这是bug，点到html里script里的注释时会发生，已经有issue了没看到吗

**Comment by kzhui125** [comment]
@xjy666 已经有open的issue了，Microsoft/TypeScript#17245， 你重复提有意思吗？
难道你想让微软程序员加班加点给你修复这个问题？
