### ISSUE TITLE
不连接网络不能打开软件

### ISSUE THREAD

**Issue by YDDxiaoyu** [Microsoft/vscode#32073]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by tigercosmos** [comment]
Too little information to judge the problem.

**Comment by rebornix** [comment]
Please file in more details like extensions you are using, if this only happens when you upgrade to 1.14.2, does it still happen with latest Stable or so. Close it first and reopen once we have more info.
