### ISSUE TITLE
Feature request: Escape key should not exit zen mode, Ctrl+W should not exit VSCode

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#32075]
While I'm editting in Zen mode I may open a search dialog, and then after finding something I may make a selection and hit Ctrl+D a bunch of times to select throughout the document and finally I will make my edits. To return to a single cursor state with the find window closed I usually hit escape 5 or 6 times in sequence. In regular mode this is not an issue, in Zen mode this drops me out of zen mode entirely. Can we get an option to disable the "escape zen mode" keyboard shortcut? I feel leaving Zen mode should be a more deliberate action.

In addition while I'm editting in VSCode in Zen mode, I may have multiple files open in the same tab. Eventually I get to a point where I feel comfortable closing out all of those files and starting from a clean slate. In this case I'll rapidly hit Ctrl+W and watch the files disappear, however unexpectedly when I hit Ctrl+W with no tabs open VSCode shutsdown entirely. I don't know of any other program that does this, except for maybe chrome where no tabs = no program. I feel this should be rectified entirely (not just hidden behind an option).

VSCode is awesome, thanks so much for building and maintaining it.

**Comment by Mardoxx** [comment]
Slack closes with Ctrl+W

**Comment by King66** [comment]
You can change shortcuts by yourself


![1](https://user-images.githubusercontent.com/11925432/29031145-d6607e58-7bbf-11e7-9a32-a5deaa5ba89e.PNG)

![2](https://user-images.githubusercontent.com/11925432/29031254-348e5f04-7bc0-11e7-9ac8-77df18980b5e.PNG)

**Comment by mjbvz** [comment]
Thanks @King66. Yes, you can customize the keybindings for these actions.

@klick-barakgall  Let me know if this does not solve the problem

**Comment by klick-barakgall** [comment]
I feel dumb. This is awesome. I should have known that these were separate actions in the keybindings. I learn something new about VSCode everyday and it's always pleasant. Thanks again!
