### ISSUE TITLE
Support match for end keywords

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#32085]
Hi community!

I'm happy user of Vim and VSCode :smile: 

On Vim I can match Ruby, Crystal, Elixir, Lua, Julia `end` keywords using [matchit](https://github.com/tmhedberg/matchit).

By example, the following code is in [Crystal](https://crystal-lang.org/) on Vim:

![ezgif-4-d0a15b60f4](https://user-images.githubusercontent.com/3067335/29022601-a35ac1f2-7b2f-11e7-9067-fd6b626068ed.gif)

Would be nice to have something similar on VSCode.

My proposal is something like `autoClosingPairs` configuration allowing `open` and `close` info:

```json
{
  "comments": {
    "lineComment": "#",
    "blockComment": ["=begin", "=end"]
  },
  "brackets": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    { "open": ["do", "if", "else"], "close": "end", "notIn": ["string", "comment"] }
  ],
  "autoClosingPairs": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["`", "`"],
    { "open": "'", "close": "'", "notIn": ["string", "comment"] },
    { "open": "\"", "close": "\"", "notIn": ["string"] }
  ],
  "surroundingPairs": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["\"", "\""],
    ["'", "'"],
    ["`", "`"]
  ]
}
```

Thanks for this great editor! :+1:

**Comment by faustinoaq** [comment]
@kieferrm So you think would be possible to achieve this with an extension?

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
