### ISSUE TITLE
Shell script coloration issue

### ISSUE THREAD

**Issue by sthonnard** [Microsoft/vscode#32089]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Create a new Shell Script

2. Write the following:

PUT_FILES=$( ls -1 *$RUN_DATE* | while read a; do echo "put $a"; done) 
GET_FILES=$( ls -1 *$RUN_DATE* | while read a; do echo "get $a"; done)

**Comment by aeschli** [comment]
This issue was moved to textmate/shellscript.tmbundle#39
