### ISSUE TITLE
Grey out files ignored by version control

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3208]
The project explorer can get very messy when you use a language where the build process produces a lot of temporary or binary files. For example, in Java you get a .class file for every single .java file, if you are using BlueJ you also get another .cxtc file for every class, for Latex you get a .log, .pdf, .dvi and a .synctex. Those files are of course all excluded through .gitignore and I will probably never ever need to edit or show those in VS Code because they are only a product of the source files.

It would reduce the clutter a lot if VS Code would give these files a greyed out color.

At the same time, I think the .git folder should show up in VS Code, just like .vscode or node_modules does. It should be greyed out like ignored files, but there are many interesting files in there that a user might want to edit, like `info/exclue` and the hooks.

**Comment by egamma** [comment]
You can control this using the `files.exclude` setting.

From https://code.visualstudio.com/Docs/editor/codebasics#_explorer

>By default, VS Code excludes some folders from the explorer (for example. .git). Use the files.exclude setting to configure rules for hiding files and folders from the explorer.

Tip: This is really useful to hide derived resources files, like \*.meta in Unity, or \*.js in a TypeScript project. For Unity to exclude the \*.cs.meta files, the pattern to choose would be: "**/*.cs.meta": true

**Comment by felixfbecker** [comment]
This is not exactly the same as greying out, but thanks for the tip.

**Comment by ksmithut** [comment]
Just as a use case, I would like files that I can see in my editor and can open quickly and change (such as local config files), but I want it visually indicated that it's ignored from source control. No need to reopen, but seems like this could be a plugin...

**Comment by kamok** [comment]
So this Issue was closed without ever being achieved? Just hide it from the view?

**Comment by jameschetwood** [comment]
+1

**Comment by RTSchriner** [comment]
+1, I loved this feature in Atom.

**Comment by treyp** [comment]
I think this is covered in #178
