### ISSUE TITLE
Culture specific Import-Module error in PowerShell integrated console

### ISSUE THREAD

**Issue by rfresow** [Microsoft/vscode#32087]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1. Window 10 in nl-NL culture.
2. In PowerShell integrated console:
```
Import-Module Microsoft.PowerShell.Archive
```
3. Reported error:
```
Cannot find the Windows PowerShell data file 'ArchiveResources.psd1' in directory 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\nl-NL\', or in any parent culture directories.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:27 char:1
+ Import-LocalizedData  LocalizedData -filename ArchiveResources
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\syst...eResources.psd1:String) [Import-LocalizedData], PSInvalidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```
4. The same in powershell.exe console in VSCode of PowerShell ISE does not report an error.

Reproduces without extensions: not possible without PowerShell extension.

**Comment by Tyriar** [comment]
Please report to the PS extension https://github.com/PowerShell/vscode-powershell

**Comment by rfresow** [comment]
Can not reproduce anymore as of latest update.
