### ISSUE TITLE
No warning for name conflict when renaming parameter 

### ISSUE THREAD

**Issue by fantaclaus** [Microsoft/vscode#32091]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
- typescript compiler: v2.4.2
---

**Steps to Reproduce:**
1. create code:

```typescript
function f(p1: string)
{
	return ["a", "b", "c"].findIndex(p => p == p1);
}
```

2. rename parameter `p1` to `p` using *Rename Symbol* command.

**What is expected:**

VS Code shows a warning that the name `p` conflicts with the name of the inner variable `p` (the parameter of the arrow function used as an argument to `findIndex`) and doesn't rename the parameter `p1`.

**The actual result:**

There is no warning and the code is changed to this:

```typescript
function f(p: string)
{
	return ["a", "b", "c"].findIndex(p => p == p);
}
```

In fact, the code is corrupted now because `p == p` is always `true` and the parameter of the function `f` is not used anymore.

Moreover, nor the intellisense nor the compiler complains, because the code is syntactically valid. Thus the damage remains unnoticed.

The same behavior is observed with ordinary functions (non-arrow).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17670
