### ISSUE TITLE
Debugging PowerShell scripts yeilds an error in text that no longer exist in the file!

### ISSUE THREAD

**Issue by swinster** [Microsoft/vscode#32096]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
beautify|Hoo|1.1.1
rest-client|hum|0.15.1
prettify-json|moh|0.0.3
PowerShell|ms-|1.4.1
vscode-nginx|sha|0.3.1

---

Steps to Reproduce:

1.Open vScode
2. Debug PS Script

Reproduces without extensions: Yes/No 

N/A as native PS is not supported for debugging

The issue is that when I attempt debug a file, VScode throws an error, however, it points to code that no longer exists in the file. In addition, thing like bracket highlighting is not working.

TBH, I have to shutdown and restart VScode every few minutes as after debugging I often find something breaks, perhaps the terminal won't scroll or the debugger will crash.

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
