### ISSUE TITLE
Resizing can reset markdown preview scroll location

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32092]
**Repo**
1. Open markdown preview for long doc
1. Scroll partway down page
1. Resize the preview window

**Bug**
Scroll location reset

**Comment by mjbvz** [comment]
Looks like `onDidChangeTextEditorSelection` is being fired when the window is resized

**Comment by isidorn** [comment]
Verified by openeing our prevous release notes -> opened preview to the side and resized it both horizontally and vertically and the position was preserved
