### ISSUE TITLE
Searching for string in files does not always find all files

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#32095]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
gherkin-indent|Ara|2.0.0
vscode-bad-code-highlighter|bha|0.1.6
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
vscode-turtle|fei|1.0.30
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
format-indent|Kas|1.3.0
phpmd|lin|1.1.4
vscode-apache|mrm|1.1.1
vscode-duplicate|mrm|1.1.0
oracle-plsql|myc|1.0.3
selectline-statusbar|tom|0.0.2
gitblame|wad|2.0.2
twig|wha|1.0.2

(1 theme extensions excluded)

---

Searching for a file with a given string inside does not always find all files. I searched the files in a separate terminal and 40 matching files were found. Then I opened one of the files in VS code and then tried the search there again and it returned results for this one file, so I opened another, repeated search and the "another" file was found too etc.

The strange thing is I did this whole operation once shortly before this and it worked fine, all files were found and all texts replaced.

Reproduces without extensions: hard to say - after I disabled them all (in UI), it still didn't work (I don't know if they are disabled right away), but after restarting VS code, it suddenly worked again.

Steps to Reproduce:

Hard to say. I am working on a NFS network drive.

1. look for a string in a large amount of files
2. all is found, replace, save, all is fine
3. revert these changes and try again
4. search result says there are some matches, but not all
5. search through terminal confirms that matches are there, but vscode won't see them
6. restart vscode
7. now it works again

**Comment by PunchyRascal** [comment]
Just happened again, so it somehow seems to be reproducible. Again I searched, found about 50 instances of a word, replaced it (with a mistake), saved. Realized my mistake, reverted the changes (via git) and repeated the search - but now only 20 instances were found, only in 1 file (before it was 17 files). 

Now I restarted vscode again, performed the search, found all correctly, replaced, saved. All is fine again. Weird.

**Comment by roblourens** [comment]
If the file is open in vscode, search will probably always work for it since search works differently for open files. The only issue I'm aware of with searching in network drives, is that there was once an issue reported for network shares using "dedupe", which we never got to the bottom of: #24968 - could that be the case here?

**Comment by PunchyRascal** [comment]
I am not sure what dedupe is, is it some option when setting up NFS share?

**Comment by roblourens** [comment]
I think so, I don't know much about it. It probably wouldn't be enabled if you didn't set it up.

When you said

> I searched the files in a separate terminal and 40 matching files were found.

what did you use to do the search?

**Comment by PunchyRascal** [comment]
> what did you use to do the search?

find + git grep in a putty terminal

----
Regarding the dedupe option, I will ask our sysadmin about it tomorrow.

**Comment by roblourens** [comment]
Do you use vscode on any local folders? Have you seen any issues there, or just in the network share?

If you'd like, it would be really helpful if you installed ripgrep - https://github.com/BurntSushi/ripgrep#installation - which is the tool that provides our search, and try to do the search against the network share from the command line. vscode just runs ripgrep and displays the results.

**Comment by PunchyRascal** [comment]
I do use vscode on local folders as well, but not nearly as much as on the NFS drive. But I haven't had any issues on the local projects.

I will try the ripgrep thing and will let you know.

**Comment by PunchyRascal** [comment]
I am sorry, but I probably won't be able to try to ripgrep atm :(

**Comment by roblourens** [comment]
If you get a chance it would also be useful to try with ripgrep disabled in vscode - `"search.useRipgrep": false`
