### ISSUE TITLE
Flicker in keybindings editor on every keystroke

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#32099]
- VSCode Version: Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:43:56.658Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
quokka-vscode|Wal|1.0.46
crazy|kie|0.0.1
githistory|don|0.2.2
python|don|0.7.0
gitlens|eam|4.3.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vsc-travis-ci-status|fel|1.1.0
svgpreview|kis|0.2.0
Go|luk|0.6.63
mssql|ms-|1.1.0
github-issues-prs|ms-|0.4.0
debugger-for-chrome|msj|3.1.7
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.13.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.2.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open the json based keyboard shortcut editor
2. On the right paste the following:
```json
[
    {
        "key": "cmd+k",
        "command": "workbench.action.terminal.clear",
        "when": "ter"
    }
]
```
3. type a character within the `when` clause
-> the left side is re-colorized resulting in a flashing editor and minimap

This is a regression.

**Comment by alexandrudima** [comment]
I can reproduce in 1.14.2, so I don't believe this is a regression introduced in the 1.15 timeframe.

I would suggest we ship 1.15 with this bug.

![kapture 2017-08-08 at 11 25 40](https://user-images.githubusercontent.com/5047891/29065436-5f4c26ec-7c2c-11e7-893d-5634be6978b1.gif)
