### ISSUE TITLE
你好，我想问下，编辑区最右侧的缩小版代码如何去掉，放上去可以当滚动条使用的那个

### ISSUE THREAD

**Issue by monty086** [Microsoft/vscode#32094]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.9.3
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Mischanix** [comment]
In `settings.json` (File > Preferences > Settings), add the setting: `"editor.minimap.enabled": false`.

**Comment by yoyo837** [comment]
editor.minimap.enabled:false

**Comment by rebornix** [comment]
Thanks everyone who helps out :)
