### ISSUE TITLE
Make keywords bold

### ISSUE THREAD

**Issue by anks333** [Microsoft/vscode#32098]
How to make keywords bold, I'm using default dark theme then I tried Github Bold theme which renders keywords in bold but it has light theme only, 
![screenshot from 2017-08-08 00-40-18](https://user-images.githubusercontent.com/8553106/29041932-85ccb174-7bd2-11e7-8d01-b210a64ce9c7.png)

let me know how to make the keywords bold, and please add "Github Bold theme" like theme with dark background

**Comment by kieferrm** [comment]
@anks333 most themes are contributed by others. Please contact the theme author.

In the meantime, with the latest insiders, you can customize how tokens are presented in your settings like this:
```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "keyword",
                "settings": {
                    "fontStyle": "bold"
                }
            },
            {
                "scope": "storage",
                "settings": {
                    "fontStyle": "bold"
                }
            },
            {
                "scope": "constant.language",
                "settings": {
                    "fontStyle": "bold"
                }
            },
            {
                "scope": "support.class.builtin",
                "settings": {
                    "fontStyle": "bold"
                }
            }
        ]
    }
```

**Comment by anks333** [comment]
@kieferrm  `"editor.tokenColorCustomizations"`  unknown configuration setting, even though i have latest insider build.
