### ISSUE TITLE
Default Keyboard Mappings have conflict between "Change Language Mode" and "Keymaps"

### ISSUE THREAD

**Issue by MarlonRodriguez** [Microsoft/vscode#32100]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
puppet|Bor|0.3.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.2
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|4.3.3
git-project-manager|fel|1.3.2
code-runner|for|0.6.31
beautify|Hoo|1.1.1
rpm-spec|Lau|0.2.1
PowerShell|ms-|1.4.1
vscode-icons|rob|7.12.0
html-preview-vscode|tht|0.1.1

---

Steps to Reproduce:
Simply try to change language mode using ctrl+k+m.  You will get keymappings instead.  The conflict detection needs to catch combinations like: "ctrl+k,ctrl+m" and "ctrl+k+m".

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@MarlonRodriguez The keybindings `ctrl+k m` and `ctrl+k ctrl+m` are not in conflict and they can be both triggered independently:

#### `ctrl+k m`
* press <kbd>Ctrl</kbd>
* press <kbd>K</kbd> (gets dispatched as `ctrl+k`)
* release <kbd>K</kbd> and <kbd>Ctrl</kbd> in any order
* press <kbd>M</kbd> (gets dispatched as `m`)
* release <kbd>M</kbd>

#### `ctrl+k ctrl+m`
* press <kbd>Ctrl</kbd>
* press <kbd>K</kbd> (gets dispatched as `ctrl+k`)
* release <kbd>K</kbd>
* (you can optionally release <kbd>Ctrl</kbd>, but have it pressed again before next bullet point)
* press <kbd>M</kbd> (gets dispatched as `ctrl+m`)
* release <kbd>M</kbd> and <kbd>Ctrl</kbd> in any order

**Comment by MarlonRodriguez** [comment]
@alexandrudima Ahh, thanks, that's a behavior I hadn't seen or used before.  It makes sense,just like pressing alt, releasing, then pressing a letter for a menu item will work.  Had not seen that with ctrl and assumed I needed to keep it pressed.  My bad.
