### ISSUE TITLE
When terminal is open the debug console shortcut isn't working

### ISSUE THREAD

**Issue by vmarchaud** [Microsoft/vscode#32102]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
ejs-language-support|Qas|0.0.1
Gradle|caz|1.1.2
vscode-standardjs|che|1.1.7
vscode-semistandard|fle|1.1.2
vue|liu|0.1.5
proto|pet|0.0.2
java|red|0.8.0
gitblame|wad|2.0.2

---

Steps to Reproduce:

1. Open the terminal embed inside vscode
2. Do the debug console shortcut
3. Observe that the shortcut doesn't work

Note that it work in the opposite way, if i have the debug console open and then i do the terminal shortcut, the terminal popup

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
ctrl+shift+y works for me on my machine.

You may need to add the `"workbench.debug.action.toggleRepl"` command to the `"terminal.integrated.commandsToSkipShell"` setting if your shell is eating the keystrokes.

**Comment by vmarchaud** [comment]
Sorry indeed it was the shell that was eating the keystrokes, thanks for the tips
