### ISSUE TITLE
Investigate improving webpack support

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32108]
Explore how we can improve support for webpack such as help configuring your `tsconfig.json` file to be in sync with your `webpack.config`.

**Comment by kieferrm** [comment]
See https://github.com/Microsoft/vscode/issues/9594#issuecomment-321332050.

**Comment by TheLarkInn** [comment]
Hi there!! Sean from [webpack](https://github.com/webpack/webpack). Is this still on your backlog?? I was just thinking about the many ways that this could integrate really well. One thing is our configuration validation schema which stays 100% up to date with webpack, found here: https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json

Happy to help hack on this if needed! Feel free and ping me. (If I don't respond here catch me on MS mail or Teams).

**Comment by mjbvz** [comment]
Yes. There are two areas that I think we could improve to start with:

- Better support for `webpack.config.js` files. Provide proper intellisense and error reporting when editing one of these. This may be something that we could implement as a TypeScript server plugin or a vscode extension

- Support for generating/syncing a `jsconfig.json` from a `webpack.config.js`. This one may make more sense as a VS Code extension.

Let me know if you have any other ideas as well or are interested in getting started. We should also meet up some time to talk more about this

**Comment by adityapurwa** [comment]
Is there any news on this?

**Comment by ajhyndman** [comment]
I love the idea of better support for `webpack.config.js` and `jsconfig.js` files!  But I wanted to throw another idea in the ring, too.

I'm working on a few webpack-based projects now, which I have been able to successfully write `jsconfig.js` files for.  However, I have not been able to get path-completion working working for absolute paths which match my `baseUrl` and `paths` configurations.

This also means that symbol discovery and automatic import statement generation works in `node_modules` packages, but not local source code.

I would be keen to take a look at improving support for this, if it's something VS Code would consider accepting.

**Comment by gulshan** [comment]
@ajhyndman You can use `typescript.tsdk` settings to use a different version of typescript.

**Comment by ajhyndman** [comment]
@gulshan Thanks!  I'll give it a shot.

**Comment by ajhyndman** [comment]
Okay, I'm not really sure I understand what's going on, anymore.

It looks like, even with the version of typescript that's shipped with VS Code, I can actually get symbol discovery across local source code, if my **jsconfig** looks like this:

```
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": "./src",
    "paths": {
      "*": ["*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}
```

However, if I have a deeply nested package structure (with import statements that look like `import Code from 'folder/below/src.jsx'`) paths are not resolved unless I use a **jsconfig** something like this:

```
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": "./src",
    "paths": {
      "**/*": ["**/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}
```

In this latter case, "jump to definition" functionality works correctly, but symbol discovery does not.

**Comment by dnistreanu** [comment]
My opinion is that webpack intellisense is important. I can confirm that it's not working.

```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by NaviMarella** [comment]
@TheLarkInn  Is there any update on this??

I would love to contribute, in developing an VS Code extension for supporting webpack intellisense. Please provide your ideas on this.

**Comment by mjbvz** [comment]
Closing this exploration. Please open feature requests or bug reports for any specific problems you run into when working with webpack
