### ISSUE TITLE
No intellisense in keybindings editor

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#32101]
- VSCode Version: Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:43:56.658Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
quokka-vscode|Wal|1.0.46
crazy|kie|0.0.1
githistory|don|0.2.2
python|don|0.7.0
gitlens|eam|4.3.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vsc-travis-ci-status|fel|1.1.0
svgpreview|kis|0.2.0
Go|luk|0.6.63
mssql|ms-|1.1.0
github-issues-prs|ms-|0.4.0
debugger-for-chrome|msj|3.1.7
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.13.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.2.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open the json based keyboard shortcut editor
2. On the right paste the following:
```json
[
    {
        "key": "cmd+k",
        "command": "workbench.action.terminal.clear",
        "when": ""
    }
]
```
3. Trigger Intellisense in the value with the when clause.
-> no completion proposals

**Comment by alexandrudima** [comment]
The `configuration-editing` extension we ship with adds a completion item provider for `keybindings.json` files, but at this time only completes in the `command` field. Given @jrieken implemented this, I'll forward this feature request to him.
