### ISSUE TITLE
setting-sync don't use

### ISSUE THREAD

**Issue by 1475142232** [Microsoft/vscode#32116]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

I didn't respond to shift + Alt + d

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
I do not understand. Please clarify and add reproducible steps.

**Comment by 1475142232** [comment]
Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

**Comment by joaomoreno** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/321

**Comment by 1475142232** [comment]
The problem has been solved. Thank you

**Comment by ikzjfr0** [comment]
+1, can visual studio code team provide a built-in tool to support this :)
