### ISSUE TITLE
Add markdown preview refresh command

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32111]
**Feature Request**
Add a command to manually refresh the markdown preview

**Comment by mjbvz** [comment]
**To verify**:
1. In a workspace with a markdown file, create a `style.css` file that sets the background color:

```css
body {
    background: hotpink !important;
}
```

1. Set `"markdown.styles": [ "./style.css" ]` 
1. Open the markdown preview to the side
1. With the preview still open, edit the css file in the other panel to change the background color.
1. Verify that the refresh command updates the preview. `Refresh` should be both in the command palette and in the `...` in the preview's status bar

**Comment by bpasero** [comment]
@mjbvz the refresh command in the "..." works, but the global command does not:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29817796-b25c6f52-8cb9-11e7-9c22-ff9719074dc3.gif)
