### ISSUE TITLE
Remove or support toggle off option for this multiple versions of same file rubbish

### ISSUE THREAD

**Issue by cmartin99** [Microsoft/vscode#32115]
Feature request.

This feature you have added (I'm not sure when, I've come back to using VSCode after several months off) where it is now possible to have two versions of the same file in the editor (one is the same name but all lower case) is the worst design decision I have ever encountered for a source code editor app. It is a disaster. It causes me constant doubt, confusion and frustration, even losing code changes on occasion. 

It will likely mean the end of me using VSCode. It's a game breaker for me.
Unless I can turn it off.

**Comment by bpasero** [comment]
We never changed that, it has always been like it: https://github.com/Microsoft/vscode/issues/12448
