### ISSUE TITLE
the comment in cpp file can't align with chinese character

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#32114]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
code-gnu-global|aus|0.2.2
GBKtoUTF8|buk|0.0.2
compulim-vscode-dictionary|Com|0.0.5
xml|Dot|1.9.2
java-debug|DSn|0.0.2
vscode-javac|geo|0.0.46
CppSnippets|har|0.0.12
start-git-bash|McC|1.2.1
vscode-csscomb|mrm|4.0.1
cpptools|ms-|0.12.2
PowerShell|ms-|1.4.1
vscode-icons|rob|7.12.0
vscode-header-source|ryz|1.1.0
code-settings-sync|Sha|2.8.2
guides|spy|0.8.4
java-imports-snippets|tus|0.0.1
java-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-react-native|vsm|0.4.1
change-case|wma|1.0.0
plsql-language|xyz|1.0.4
vscode-proto3|zxh|0.1.2

---
see the attach pic：
![image](https://user-images.githubusercontent.com/22406984/29054334-32010148-7c28-11e7-8067-63e88032c5a9.png)

but view it in other editors, it's Ok.

source code:
[match_processors.zip](https://github.com/Microsoft/vscode/files/1206793/match_processors.zip)

**Comment by weinand** [comment]
Please use a fixed width font where all characters have the same width.

**Comment by AbelaroJiang** [comment]
Sorry, I can't find the setting.

**Comment by weinand** [comment]
You can find the font setting here:

![2017-08-10_10-24-25](https://user-images.githubusercontent.com/1898161/29161348-2c72db40-7db6-11e7-8669-1e01cd9e66b3.png)
