### ISSUE TITLE
Debug console show nothing in Python Flask App

### ISSUE THREAD

**Issue by nighttiger1990** [Microsoft/vscode#32124]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Pro v1703 Build 15063.483

Steps to Reproduce:

1. When i run app using cmd.exe something below is shown: (Or some request from client shown, too)
 * Serving Flask app "app"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2. But when i Start Debug (F5) in VS Code.  Nothing showing in Debug Console (No information from request shown) App still run well
This is my config:
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/app.py",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1143
