### ISSUE TITLE
JS Object Inline Feature

### ISSUE THREAD

**Issue by boosters** [Microsoft/vscode#32127]
I am looking the feature which I can inline the object instead of collapse like

**Example:**
{id: 1, title: 'Book1' , publisher: "Unknown"}

**instead of** 
{
id:1,
title:'Book1',
publisher:'Unknown'
}

**Comment by weinand** [comment]
Is this a feature when editing JSON or while debugging JavaScript?

**Comment by boosters** [comment]
It is adding objects inside an array or you can say editing JSON.

**Comment by aeschli** [comment]
Please give more details. Is it like a formatting action?

**Comment by aeschli** [comment]
Closing, lack of information...
