### ISSUE TITLE
angular4 autoimport problem

### ISSUE THREAD

**Issue by GilHyeon** [Microsoft/vscode#32120]
I wrote code Angular4 with vscode. some module auto import is wrong.

for example, Routes, RouterModule auto import like this

```typescript
import { Routes, RouterModule } from "@angular/router/router";
```

but it's not correct. this is correct import statement
```typescript
import { Routes, RouterModule } from "@angular/router";
```

this problem have also 'angular/forms' modules import
```typescript
// wrong import
import { FormGroup } from "@angular/forms/forms";

// correct import 
import { FormGroup } from "@angular/forms";
```

- VSCode Version: 1.14.2
- OS Version: MacOS 10.12.5(16F73)

Steps to Reproduce:

1. wrote Routes and click yellow lamb.
2. select import but there is no correct import statement
* this step has 3 recommend statements
```
 import { Routes } from "@angular/router/src";
 import { Routes } from "@angular/router/public_api";
 import { Routes } from "@angular/router/router";
```
3. I select third statement. but it occurred build error.
4. I changed statement correctly 
```typescript
import { Routes } from "@angular/router
```
5. next, RouterModule add auto import is done correctly like this
```typescript
import { Routes, RouterModule } from "@angular/router";
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17705
