### ISSUE TITLE
CPU load increase when making a new blank file

### ISSUE THREAD

**Issue by tonyvanhain** [Microsoft/vscode#32121]
- VSCode Version: 1.14
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1.Open a new blank file, do not save it yet (leave it as untitled)
2.When that blank file opens, my CPU load suddenly increases a lot

the problem doesnt happen when I am opening other files in vscode. The problem also dissapears when I saved the untitled file as a python file for example. 

Reproduces without extensions: Yes/No ( happens on both

**Comment by alexandrudima** [comment]
@tonyvanhain I have just tried version 1.14.2 on Ubuntu 16.04.3 LTS and I am sorry, but I could not reproduce:
* I run `top` in a terminal
* I use File > New File in VS Code
* there is a CPU spike for a couple of seconds, after which the `code` processes I could spot do not consume more than 1% CPU for me

**Comment by tonyvanhain** [comment]
@alexandrudima maybe it is because of my computer then, thanks for the info. I will try to fix it later
