### ISSUE TITLE
column (box) selection with mouse not working anymore on linux

### ISSUE THREAD

**Issue by byggwir** [Microsoft/vscode#32125]
- VSCode Version: Code 1.14.2  cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z  - OS Version: Linux x64 4.10.0-30-generic - Extensions:  Extension|Author  truncated |Version -|-|- csharp|ms-|1.11.0 - Steps to Reproduce: 1. 2. !- Launch with  code -disable-extensions  to check. -> Reproduces without extensions: Yes/No

If I try alt+shift+mouse drag it does not box select anymore. The window minimizes and gets dragged around whereever I drag the mouse. So essential the new behavior is moving the visual studio code program window around. Selecting a box with the mouse does not work.

Checking the keyboard shortcuts it is still described with this combination to make a box selection.

**Comment by rebornix** [comment]
Since Linux system takes Alt key, so you may want to change `"editor.multiCursorModifier"` to `ctrlCmd` to avoid conflicts.
