### ISSUE TITLE
code helper take up more CPU and code hint is invalid

### ISSUE THREAD

**Issue by shaodahong** [Microsoft/vscode#32122]
- VSCode Version: `Version 1.14.2 (1.14.2)`
- OS Version: macOs sierra Version 10.12.6 (16G29)

![image](https://user-images.githubusercontent.com/14831261/29058368-8d1c4fa0-7c42-11e7-89b6-55ed1142e0b8.png)

Steps to Reproduce:

1. When I run webpack HMR or grunt watch, will monitor the file changes, But I will find the file changed once or twice after the manual save very slowly(2-3 seconds), And the code hints are gone

Reproduces without extensions: Yes/No

No

**Comment by weinand** [comment]
Please add precise steps that let us reproduce the problem.
