### ISSUE TITLE
Keep the original file window when saving file

### ISSUE THREAD

**Issue by qtline** [Microsoft/vscode#32123]
- VSCode Version: 1.14.2
- OS Version: win10

Steps to Reproduce:

1.ZH: 增加禁止‘另存为’操作后切换为新文件设置
2.EN: Add a ban on 'save as' and switch to new file Settings

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
I do not understand. Why should we "ban 'save as'" and what are the new file settings?

**Comment by qtline** [comment]
You got it wrong,I mean whether you can add settings:"Save As", the editing window does not jump to the new file window, keep the original file window!  
>By the way, Can you read Chinese!

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
