### ISSUE TITLE
activationEvents.workspaceContains only know full file name??

### ISSUE THREAD

**Issue by sofgod** [Microsoft/vscode#3213]
can support file extension name ?? like "*.config" etc..

**Comment by joaomoreno** [comment]
@alexandrudima maybe you know this?

**Comment by alexandrudima** [comment]
@sofgod The use-case for `workspaceContains` is to have an extension that gets activated when a top level file exists. E.g. `.editorconfig` should be a top-level file in a folder that uses editor config. What is your exact use-case? You can always use `activationEvents:['*']` if none of the existing fine-grained activation events matches your use-case.
