### ISSUE TITLE
When run in Terminal a programs unhandled exceptions don't produce debug dialog in win32 

### ISSUE THREAD

**Issue by stephen-d-hill** [Microsoft/vscode#32134]
- VSCode Version: 1.14.2
- OS Version: Windows 7

Steps to Reproduce:
Run a C program with this code in the terminal:
`
void main(void)
{
   char *p = NULL;
   *p = 0;
}
`
and no dialog will appear. Run it outside of VSCode and it will.

Reproduces without extensions: Yes

**Comment by stephen-d-hill** [comment]
Suspicion is that VSCode is catching all unhandled exceptions even when the debugger isn't being used.

**Comment by stephen-d-hill** [comment]
Using 
`"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
`
in preferences works around the problem

**Comment by Tyriar** [comment]
@rprichard this is probably related to winpty?

**Comment by rprichard** [comment]
@Tyriar It seems plausible that this issue is related to winpty. I should investigate this at some point.
