### ISSUE TITLE
Scroll changes on window focus

### ISSUE THREAD

**Issue by mooioom** [Microsoft/vscode#32131]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-tfs|iva|0.6.0
csharp|ms-|1.11.0

(2 theme extensions excluded)

when changing focus to a different instance window of VS CODE scroll changes when returning
(not a tab within vs code, but another instance window of vs code)
---

Steps to Reproduce:

1. change (tab) a window to a different VS Code instance
2. return to the original one, scroll changed - moved down

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@mooioom can you share a video?
