### ISSUE TITLE
Find and replace does not replace correctly when replacing many occurrences

### ISSUE THREAD

**Issue by TomGroeneboer** [Microsoft/vscode#32137]
When trying to find & replace many occurrences at once, the value that is put in does not seem right.

E.g. if I try to replace 'Code.Abstractions' with 'MoreCode.Abstractions' at 500 occurrences in 100 files (or 4000 occurrences in 1200 files, does not matter), some occurrences (maybe 30-50) end up with 'CCode.Abstractions' or 'CodeAbstractions'. This seems to happen every time I try to mass replace a value.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
azure-functions-tools|joh|0.3.0
csharp|ms-|1.11.0
vscode-docker|Pet|0.0.16

Steps to Reproduce:

1. Open a large .NET solution
2. Replace a namespace occurrence that is used a lot with something else (try to hit 1000+ occurrences)

Reproduces without extensions: Yes

If you need any further information, please let me know!

**Comment by rebornix** [comment]
Considering it's multi file, pass to @roblourens

**Comment by roblourens** [comment]
Does it only happen in certain files, or randomly? Is there something different about the places where it happens - very long lines, non-utf8 encoding?

**Comment by TomGroeneboer** [comment]
It seems to happen randomly, we were trying to replace using statements in C# files created by the full blown Visual Studio. I guess these lines were around 50 characters each.

**Comment by TomGroeneboer** [comment]
Any updates on this?

**Comment by roblourens** [comment]
I haven't been able to repro it. Have you tried with 1.15?

**Comment by MynockSpit** [comment]
Might be different, but seems related. Check and see if the instances that failed to update correctly happened more than once on the same line.

![weirdmultilinebehavior](https://user-images.githubusercontent.com/5713867/31561986-a0b93654-b00e-11e7-9d18-661796f60786.gif)

**Comment by roblourens** [comment]
No, that's not related.

@TomGroeneboer Based on your description I think it's actually https://github.com/Microsoft/vscode/issues/35633 - affecting files encoded with a UTF8 BOM, and matches on the first line. That's now fixed in insiders.
