### ISSUE TITLE
HELP !! Cannot find runtime 'node' on PATH !

### ISSUE THREAD

**Issue by Geolage** [Microsoft/vscode#32130]
VS Code cannot find runtime 'node' on PATH. I've tried some ways to handle it, but failed.

- VSCode Version:  v1.14.2 (x64)
- OS Version:  windows 7 (x64)

Environment variables checked contains:
B:\Users\Geolage\AppData\Roaming\npm;B:\Program Files\nodejs\;B:\Program Files\nodejs\node.exe;B:\Program Files\Microsoft VS Code\bin
seems no problem there.

launch.json:
```js
{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/js/app.js",
            "runtimeExecutable": null,
            "cwd": "${workspaceRoot}"
        }
```

well, there's another problem that occurred before the prompt"cannot find...":
   alert 
   says " C:\Windows\System32\where.exe is not a valid Win32 application. "
and the debugger console below also logs that 
"Debugging with inspector protocol because Node.js v8.2.1 was detected." 
then nothing more

I also tried this: input "where node" insides integrated terminal, luckily it responsed:
"B:\Users\Geolage\Desktop\Projects\Web\Vottery>where node
B:\Program Files\nodejs\node.exe"

So, in that situation, what should I do? 
@weinand

**Comment by Geolage** [comment]
oh my!! I just figured it out! 
It solved since I tried rewriting "**runtimeExecutable**" this property's value in **launch.json**, and reset it to nodejs path which I already knew right after typed "where node" insides **integrated terminal** at the end of vscode window, like this: "runtimeExecutable": "B:/Program Files/nodejs/"
thx everyone! If there anyone who has the same problem, try this one may help.

**Comment by Geolage** [comment]
Well, to explain this issue more specifically, the debugger seems not working well ! Anytime as I run it, there'll always be an alert prompt showing up later, says "  C:\Windows\System32\taskkill.exe is not a valid Win32 application. " , but console does show the results.
So what is the matter with my nodejs debugger in vs code? Why always turn out a prompt " C:\Windows\System32\where.exe is not a valid Win32 application."or " C:\Windows\System32\taskkill.exe is not a valid Win32 application."? Hope that anyone can offer me some help, thx so much!

**Comment by aluanhaddad** [comment]
Why have you specified
```json
"runtimeExecutable": null
```
in your launch config?

**Comment by Geolage** [comment]
@aluanhaddad  oooh, I just tried to make it work according to a web guy's advice, but lately I changed it to "runtimeExecutable": "B:/Program Files/nodejs/"

**Comment by weinand** [comment]
@Geolage VS Code node debugger uses standard Windows utilities "taskkill.exe" and "where.exe". If VS Code cannot find them on your system, then something is either non-standard (or broken). One reason for this can be a broken `%Path%` variable.

Can you try to run `where` in a command prompt?
If it cannot be found, then your `%Path%` is definitively broken.
Run `echo %Path%` in a command prompt and verify it (or post it here and I can verify too).

How did you install node.js? With the official installer node.exe should be automatically found on the path and setting "runtimeExecutable" should not be necessary.

Please run `where node` in a command prompt. It should output `C:\Program Files\nodejs\node.exe`

**Comment by Geolage** [comment]
@weinand Yep, commands both `where` and `echo %Path%` can be run in the command prompt, and I 
 exactly used the official nodejs installer, there can't be anything wrong with nodejs I think. Also run `where node`, it outputs `B:\Program Files\nodejs\node.exe` on this OS.

**Comment by weinand** [comment]
And if you use the integrated terminal inside VS Code to run `where` and `echo %Path%` and `where node` you get the same results?

**Comment by Geolage** [comment]
@weinand  Here's the echo. Sorry, that's a real mess.
B:\Users\Geolage>echo %Path%
B:\PROGRAMDATA\ORACLE\JAVA\JAVAPATH;B:\PROGRAM FILES\JAVA\JDK1.7.0_80\BIN;B:\PRO
GRAM FILES (X86)\COMMON FILES\INTEL\SHARED FILES\CPP\BIN\INTEL64;B:\WINDOWS\SYST
EM32;B:\WINDOWS;B:\WINDOWS\SYSTEM32\WBEM;B:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V
1.0\;B:\ADB;B:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;B:\PROGRAM FI
LES (X86)\QUICKTIME\QTSYSTEM\;B:\Program Files\WIDCOMM\Bluetooth Software\;B:\Pr
ogram Files\WIDCOMM\Bluetooth Software\syswow64;B:\Program Files\Microsoft SQL S
erver\120\Tools\Binn\;B:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\
Tools\Binn\;B:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;B:\Progr
am Files\Microsoft SQL Server\120\DTS\Binn\;B:\Program Files (x86)\Microsoft SQL
 Server\120\Tools\Binn\ManagementStudio\;B:\Program Files (x86)\Microsoft SQL Se
rver\120\DTS\Binn\;B:\Program Files (x86)\Brackets\command;B:\Program Files\Git\
cmd;B:\Program Files\nodejs\;B:\Users\Geolage\AppData\Local\atom\bin;B:\Users\Ge
olage\AppData\Roaming\npm;B:\Program Files\nodejs\;B:\Program Files\nodejs\node.
exe;B:\Program Files\Microsoft VS Code\bin

B:\Users\Geolage>where node
B:\Program Files\nodejs\node.exe

**Comment by Geolage** [comment]
@weinand  Yes! I got the same results.

**Comment by weinand** [comment]
But this minimal launch config still doesn't work?
```js
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/js/app.js"
}
```

**Comment by Geolage** [comment]
Yep, it still doesn't work! Neither does that annoying prompt "where.exe is not a valid..."! Only with "runtimeExecutable": "B:/Program Files/nodejs/node.exe" can console goes well

**Comment by weinand** [comment]
What is your path to "where"?
Just run `where where`

**Comment by Geolage** [comment]
@weinand  OK, here it is:
B:\Windows\System32\where.exe

**Comment by weinand** [comment]
aha, that's the problem: you do not have a standard "C" drive. So all hardcoded programs paths that start with "C:" fail.

**Comment by Geolage** [comment]
allright, so what should I do?

**Comment by weinand** [comment]
If you have nothing mounted under `C:` you can try to mount `B:` under `C:` by this command:
```
subst C: B:\
```

**Comment by weinand** [comment]
Does it help?

**Comment by Geolage** [comment]
@weinand sorry, I do have something mounted under `C: ` ..

**Comment by weinand** [comment]
You could try to copy `B:\Windows\System32\where.exe` to `C:\Windows\System32\where.exe` (same for taskkill.exe). I haven't tried this so I don't know whether this works.

**Comment by weinand** [comment]
@roblourens for "legacy" I've eliminated the assumption that Windows lives on the `C:` drive for `where` and `taskkill`.

**Comment by Geolage** [comment]
@weinand I thought both where.exe and taskkill.exe could take their place on C: , but I was rejected due to no permission to doing replacing work( probably C: is my another OS disk, win 10 is right there)

**Comment by weinand** [comment]
you could unmount C: and then use the "subst" workaround from above.

Other than that I have no workaround. You'll have to wait until the fix has made it into the VS Code Insiders build.

**Comment by Geolage** [comment]
I'm thinking whether there is a way that can help me redirect the right path of where.exe through rewriting a config json or whatever ..

**Comment by weinand** [comment]
you could just fix the drive letter in the JavaScript files in VS Code:

![2017-08-09_16-27-24](https://user-images.githubusercontent.com/1898161/29126868-ccbf1524-7d1f-11e7-8630-55114df2ae8b.png)

**Comment by Geolage** [comment]
@weinand THANK YOU SO... SO MUCH !!! This one does really help!
Well, I think it is the best recommended way!! LOL o(￣▽￣)d ..

**Comment by Rajazpandi** [comment]
I am not able debug my Typescript program from VS Code its showing "Cannot find runtime 'node' on PATH. Make sure to have 'node' installed." this error what can i do for this problem pls help me

**Comment by weinand** [comment]
@Rajazpandi what platform are you on? What version of node do you have installed?

**Comment by Rajazpandi** [comment]
@weinand  my node version is 6.11.2
