### ISSUE TITLE
Code takes incredibly long for tiny path suggestions

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#32140]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
code-spell-checker|str|1.3.5

---

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1658949/29072766-60e16b76-7c49-11e7-9bc9-9a89dd8ded90.png)

This keeps happening. Code will take forever to complete loading the suggestions, even though there are only 5 or 6 items. When I restart Code, it works instantly for a couple of minutes. Then it gets stuck on "Loading..." again.

**Comment by mjbvz** [comment]
That doesn't sound good. Can you please try collecting the TS Server logs to see which request is taking a long time:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the problem
3. Run the `Open TS Server log` command and open`tsserver.log` file in the log directory

At the end of the log, look for messages about `completions` requests or requests that take  large amount of time to complete. If you can share the logs, I can also take a look

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by oliversalzburg** [comment]
Just FYI, I enabled the option, but I did very little coding today so far, so I wasn't able to repro the issue yet. I'm still on it though and I'll update once it repros or if it's simply gone :P

**Comment by oliversalzburg** [comment]
I'm not seeing this issue anymore. I also updated to 1.14 x64 now. I know now where to collect better information if I run into this again. I will open a new ticket if it comes up again.

**Comment by oliversalzburg** [comment]
I had the issue again, but the log doesn't tell me anything obvious. What I read from the log only took milliseconds.

@mjbvz I'd be happy to share the log with you. Please let me know how I can send it over.

**Comment by mjbvz** [comment]
You can email me the log at `matb AT micrsoft.com`. I'll take a look to see if anything stands out

**Comment by oliversalzburg** [comment]
@mjbvz I'm guessing there was nothing of note?
