### ISSUE TITLE
Php file alternative syntax with html markup: Code highlighting fail

### ISSUE THREAD

**Issue by dwengs** [Microsoft/vscode#32142]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
indent-rainbow|ode|0.6.1
vscode-input-sequence|tom|0.2.0

---

Steps to Reproduce:

1. Open a .php file
2. Use alternative syntax for if/else statements with html markup.
3. Code something like this:
```php
if($foo):?>
<p>Bar</p>
<?
$fuu = "baz";
else:
```

If you write "else" right after shorthand php opening tag, code highlighting is correct. But if you code like above, "else" word colored as white like a text, not like a function as purple.

Reproduces without extensions: Yes, same without ext.

**Comment by roblourens** [comment]
I don't quite follow, is this what it should look like?

![image](https://user-images.githubusercontent.com/323878/29080108-ca980f92-7c13-11e7-9dd4-1bcc048ba2be.png)

**Comment by dwengs** [comment]
Exactly.
And... Interestingly, that was office computer which is Mac.
I tried again at my home now, with my own Win computer and it works correct like you have posted.

I will try again tomorrow at office and post the result. (uninstall extensions, reinstall vscode etc.) Maybe it is about version or OS.

**Comment by roblourens** [comment]
Check the vscode version too. The grammar usually changes with every release.

**Comment by dwengs** [comment]
I've checked this issue at office Mac, after reinstalling vscode; results:
1. Normal, just like you've posted:
![normal-else](https://user-images.githubusercontent.com/17884352/29108597-5dade03e-7ce8-11e7-90c8-606397a462eb.jpg)
2. If I indent those lines:
![indented-else](https://user-images.githubusercontent.com/17884352/29108616-75d5e026-7ce8-11e7-9cc6-c8471cce5a9b.jpg)

Same without extensions.

**Comment by roblourens** [comment]
Filed an issue upstream: https://github.com/atom/language-php/issues/253. Seems to only affect `else` and only when it's indented?

**Comment by dwengs** [comment]
Yep, just "else" if it is indented.
Thank you.

**Comment by mattacosta** [comment]
Fixed.
