### ISSUE TITLE
VS Code issues when launched from cli

### ISSUE THREAD

**Issue by RohithKumbharkar** [Microsoft/vscode#32144]
- VSCode Version: 1.14.2
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/5032439/29075058-efa00546-7c6e-11e7-844d-23aae0066053.png)

Steps to Reproduce:

1. Open a terminal on Windows (CMD or PowerShell)
2. Launch VS Code by typing in "code"
3. Close the CMD / PowerShell
4. VS Code crashes with "[VS Code]: render process crashed!" message in the terminal

![image](https://user-images.githubusercontent.com/5032439/29075222-61db3a54-7c6f-11e7-838e-90abbfb2ad30.png)

Reproduces without extensions: Yes

Code doesn't seem to revert back the control to terminal window after it's started which is causing this issue.

**Comment by RohithKumbharkar** [comment]
This is much worse, most of the cli options are not working like here

![code cli](https://user-images.githubusercontent.com/5032439/29078961-792c4a72-7c79-11e7-94f1-852fbb40853f.gif)

**Comment by ndrafahl** [comment]
I'm not sure how much this entirely helps - but I'm on the same version of Windows 10 OS and the same version of Code, and do not experience this issue from either CMD or Powershell.

**Comment by joaomoreno** [comment]
@RohithKumbharkar What does `where code` return?

**Comment by RohithKumbharkar** [comment]
@joaomoreno where code returns this
![image](https://user-images.githubusercontent.com/5032439/29366977-12c6e1fc-82b9-11e7-899f-7631b82a513a.png)

**Comment by RohithKumbharkar** [comment]
@joaomoreno I've upgraded to 64 bit VS Code & running `where code` now returns the below response

![image](https://user-images.githubusercontent.com/5032439/29369996-cac1f6cc-82c1-11e7-955f-8e8aad2b38ab.png)

I no longer have this issue, it might've occurred due to the Code.exe being present in the path

**Comment by joaomoreno** [comment]
Yep exactly. 👍
