### ISSUE TITLE
Php "include" statement code highlighting issue

### ISSUE THREAD

**Issue by dwengs** [Microsoft/vscode#32145]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
indent-rainbow|ode|0.6.1
vscode-input-sequence|tom|0.2.0

---

Steps to Reproduce:

1. Use include statement in if statement like this:

```php
<?php
if(!include "foo/bar.php"){
    echo 'Failed to include';
}
?>
<p>Other</p>
</div>
```

after curly brackets, all HTML markup hights as white like text.

But if you write include statement like it is a function:
```php
<?php
if(!include("foo/bar.php")){
    echo 'Failed to include';
}
?>
<p>Other</p>
</div>
```
This works well, but the thing is; include is not a function. Works like function with parameter but its more like statement.

Reproduces without extensions: Yes.

**Comment by roblourens** [comment]
Works now
