### ISSUE TITLE
No Intellisense for linked library

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#32147]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063

---

I am not sure if this is an issue with `TypeScript` or `VSCode`, but I created an `npm link`, and typescript doesn't seem to be able to pick up my typings within the linked library. Following the instructions on npmjs.com I did the following:

```
cd /libs/my-awesome-library
npm link
cd /projects/my-awesome-project
npm link my-awesome-library
```

I have a `tsconfig.json` file, in the root of my project:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "app"
  },
  "files": [
    "src/index"
  ]
}
```

I have tried adding: 
```json
  "include": [
    "node_modules/my-awesome-library/typings/**/*.d.ts"
  ],
```

But I still don't get completions for my library. The only completions that I get are the ones defined in the `js`, which suggests almost everything as `any` when they should be `string`, `object`, `number`, etc.

**Comment by mjbvz** [comment]
I see you opened the excat same bug against TS: https://github.com/Microsoft/TypeScript/issues/17684 Closing as upstream

Please only post issues once, and then reference it from other issues if needed. We will move the issue to the correct repo if needed
