### ISSUE TITLE
Integrated Terminal won't accept focus 

### ISSUE THREAD

**Issue by apayani** [Microsoft/vscode#32155]
- VSCode Version: 1.14.2
- OS Version: Windows 10 ( 1703)

 
I am using vscode ( 1.14.2) for python developement in windows 10 ( 1703)
very often when I  click inside the terminal and press ctrl+C to terminate my program , I realize that the terminal doesn't accept focus. when this happens I can't even copy text from terminal or to scroll to see it's previous content. Atthis point the only solution is to resize the terminal window ( or to resize vscode main window ) . After the restart things go back to normal

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by apayani** [comment]
I am still experiencing this issue after installing the version 1.15 ( both 32 and 64 bits editions ). The integrated terminal wont accept focus until resized . I can easily reproduce this.  I am using python extension with vscode. Everytime I start vscode, it automatically reopens my last python file . Without doing anything else upon startup, I just select the command ( Python: run python file in Terminal ) from the Show All Commands popup ( CTRL+SHIFT+P ). and while my program starts running in terminal I cannot select anything in terminal windows with mouse unless  I resize the terminal windows.

**Comment by Tyriar** [comment]
@apayani could you check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by apayani** [comment]
@Tyriar  devtools console does not show anything when this happens. 
y the way when this happens , other than resize, I can fix it also by selecting any other tabs ( PROBLEMS,OUTPUTS,...) and then going back to TERMINAL tab. 
Any other diagnostics steps ?

**Comment by Tyriar** [comment]
Can you take a screenshot of the terminal (including dropdown) and also try with the latest stable version 1.15.1?
