### ISSUE TITLE
"Go to Next Error or Warning" doesn't

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#32159]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
mssql|ms-|1.1.0
cpptools|ms-|0.12.2
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.7
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. open a typescript project containing many files, more than one, but not all of which have build errors.
2. build, so that the 'Problems' tab contains build errors
3. open a file that DOESN'T contain any build errors
4. execute "Go to Next Error or Warning" (editor.action.marker.next)

it doesn't.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
> execute "Go to Next Error or Warning" (editor.action.marker.next)

That actually is an editor command, so only sees what errors/warning are in an editor. The problems view is using other commands to reveal the next/prev marker since it also uses its own marker-sorting logic. 

@sandy081 I believe this issue should go back to you.

**Comment by sandy081** [comment]
Not sure what user is expecting here. @Spongman can you please elaborate what is your use case and expected result?

**Comment by Spongman** [comment]
I'd expect it to work like it does in VS. eg. Hit f4 (or whatever) to cycle through all the build errors, make an edit here or there and f4 to the next one. Right now f4 doesn't do anything if there aren't any errors in the current file, and if there are, it only cycles through the errors in that file - it doesn't go to the next file.


On Aug 21, 2017, at 9:18 AM, Sandeep Somavarapu <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what user is expecting here. @Spongman<https://github.com/spongman> can you please elaborate what is your use case and expected result?

**Comment by safield** [comment]
Is this going to be fixed?

**Comment by sandy081** [comment]
There was a command `Go to Next Problem in Files (Error, Warning, Info)` that does problem navigation across files.

**Comment by jrieken** [comment]
@sandy081 I don't think so. Those are all editor commands: https://github.com/Microsoft/vscode/issues/32159#issuecomment-323717852

**Comment by sandy081** [comment]
@jrieken Is not the mentioned editor command suffice what user is asking for in the description?

**Comment by jrieken** [comment]
That's actually true. I was mentally on a different issue.

**Comment by Spongman** [comment]
Isn’t that only for _open_ files?

**Comment by sandy081** [comment]
No, I think it iterate over all files which has problems generated already and you have to start navigating by opening a file.
