### ISSUE TITLE
Quick Open View doesn't work consistently

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#32154]
On Mac from Command Palette:
1. Open Command Palette, type "Quick Open View"
2. Select by clicking: the quick open view appears
3. Select using enter: the quick open view flashes and then disappears :x:

On Mac from Keybinding:
1. Open "Quick Open View" using Ctrl+Q
2. View disappears when Ctrl key is released :x:
3. Navigation works when holding down Ctrl and pressing Q 
4. Navigation does not work when holding down Ctrl and pressing arrow keys :x:

On Windows:
1. Open Command Palette, type "Quick Open View"
2. Select by clicking: the quick open view appears
3. Select using enter: the quick open view flashes and then disappears :x:
4. Navigation works by pressing arrow keys without holding down Ctrl

**Comment by bpasero** [comment]
@aefernandes there are some commands which only really work when invoked via keybinding ("quick navigate" commands). It is true that you cannot really execute them via mouse, so they should probably either be supported or filtered out (though it is still good to show them for discoverability reasons).

**Comment by aefernandes** [comment]
Actually I think a problem is that some of these commands don't work via keybinding, but only mouse. 

I expect Quick Open View to show me the menu below whether I run the command via command palette + enter, command palette + click, or the quick open keybinding. Right now it only works as expected through command palette + click. (The brief flash and disappear that occurs for the other options is visually jarring.)

![image](https://user-images.githubusercontent.com/7109548/29308975-b22ecbfa-815c-11e7-9742-5bb127e5a45b.png)

**Comment by bpasero** [comment]
Closing "as designed".
