### ISSUE TITLE
Suggestion: Order files and tabs by the same parameters precedence

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#32156]
Hi,

I need to opens a file sequence in same order from type from terminal.

- VSCode Version:
```
Versão 1.16.0-insider
Confirmação f980319f5c4bf3f0878c5fcc68a3aa2795119c57
Data 2017-08-08T05:10:13.016Z
Shell 1.6.6
Renderizador 56.0.2924.87
Nó 7.4.0
Arquitetura x64
```
- OS Version: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu Artful Aardvark (development branch)"
```

```
Linux wellington-Inspiron-3647 4.11.0-10-generic #15-Ubuntu SMP Thu Jun 29 15:03:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to Reproduce:

1. Try open multiple files from terminal: 
2. Like:  code-insiders  $( echo {0000607..0000624}.sql |sort --numeric-sort )
3. Or: code-insiders 0000607.sql 0000608.sql 0000609.sql 0000610.sql 0000611.sql 0000612.sql 0000613.sql 0000614.sql 0000615.sql 0000616.sql 0000617.sql 0000618.sql 0000619.sql 0000620.sql 0000621.sql 0000622.sql 0000623.sql 0000624.sql
4. I expected to files opened in tabs and at menu in numeric order.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
