### ISSUE TITLE
Visual Code terminal takes too long to abort nodemon with CTRL+C

### ISSUE THREAD

**Issue by juniormayhe** [Microsoft/vscode#32157]
When you press `CTRL + C` when running `nodemon your-file.js`, Visual Code takes several seconds to show prompt again.

Not sure if this is related to mongodb open connection while running the server. Packages used: 

```
{
...
  "engines": {
    "node": "8.2.1"
  },
  "dependencies": {
    "body-parser": "^1.17.2",
    "express": "^4.15.3",
    "lodash": "^4.17.4",
    "mongodb": "^2.2.30",
    "mongoose": "^4.11.5"
  },
  "devDependencies": {
    "expect": "^1.20.2",
    "mocha": "^3.5.0",
    "nodemon": "^1.11.0",
    "supertest": "^3.0.0"
  }
}

```

- VSCode Version: 1.14.2
- OS Version: Microsoft Windows [Version 10.0.15063]

![image](https://user-images.githubusercontent.com/205577/29091510-97217a4a-7c59-11e7-8111-69336a980db0.png)

Steps to Reproduce:

1. Run `nodemon your-file.js`
2. node app will be running (on a port such as 3000)
3.  click on terminal and press `CTRL+C`
4. Visual Code takes too long to cancel nodemon execution
5. There is no UI info showing if terminal (bash.exe) is processing this cancel request
6. The prompt will be shown after a big delay `youruser@YourPC MINGW64 ~/YourFolder/your-node-rest-api (master)`

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Tracking these issues in https://github.com/Tyriar/node-pty/issues/7
