### ISSUE TITLE
Highlighting for PHP breaks when using a namespaced trait

### ISSUE THREAD

**Issue by jrbloemhof** [Microsoft/vscode#32153]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: N/A

Steps to Reproduce:

1. Open/Create PHP file with content as follows:

```php
<?php

class ExampleClass {
     // Referencing a trait without namespace works as expected:
    use ExampleTrait;
    $foo = "SUCCESS: This line will highlight properly.";

    // Referencing a trait with a namespace will break highlighting:
    use ExampleNamespace\ExampleTrait;
    $bar = "ERROR: This line will NOT highlight properly.";

    /* Highlighting remains broken across multiple lines,
        and will color ignore things like keywords, comments or quotation marks.
        However, highlighting appears to reset the moment it scans a closing brace, as such: }

        Note that while highlighting has been reset, this line is still broken because VS code did not register the start of this comment block. */

    $baz = "SUCCESS: This line, and subsequent lines, will highlight properly again.";
}

```
2. Compare VS Code highlighting to Markdown highlighting as presented above. After referencing a namespaced trait, syntax highlighting remains broken until the first brace, even if additional content is inserted before or after the $bar.

The issue might be caused by highlighting rules set up for the "use" keyword for importing/aliases or the "use" keyword for delegates, which are two different syntaxes.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This should be fixed in the Insiders build, try it out there if you get a chance. #30448
