### ISSUE TITLE
Static functions not found with 'Go to Definition' in C#/Unity

### ISSUE THREAD

**Issue by simontgs** [Microsoft/vscode#32162]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
vscode-eslint|dba|1.2.11
csharp|ms-|1.11.0
mono-debug|ms-|0.15.7
perforce|sle|2.1.1

---

Steps to Reproduce:

1. Setup VS Code per instructions for Unity+C#
2.Right-click on a static function to find it in project via Go to definition.
   VScode says 'no definition found for >blah<'

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please move this issue to the csharp or unity extension with this tool: https://github-issue-mover.appspot.com
