### ISSUE TITLE
Feature Request: Please add the ability to select multiple files/folders in the explorer view

### ISSUE THREAD

**Issue by xueyunquan** [Microsoft/vscode#32168]
Hi, 

I'd like to ask you to add the ability to select and operate multiple files/folders in the explorer view. 

It is a common practice to select multiple items on a GUI by holding CTRL and clicking the items. Alternatively, one can select consecutive items by clicking the first item and then SHIFT+clicking the last item. But multi-selection is not supported in the VS code explorer view. When working on a large project sometimes it is needed to select multiple files/folders and operate them together, such as opening, deleting, or submitting to VCS, etc.

Without this functionality it could be tedious to operate files. Please consider this. Thank you.

**Comment by wangweixuan** [comment]
Duplicate of #1023.
