### ISSUE TITLE
[C++] Cann't rename symbol and F2 not found.

### ISSUE THREAD

**Issue by 91devel** [Microsoft/vscode#32167]
- VSCode Version: 1.14.2
- OS Version:ubuntu 16.04 LTS

Steps to Reproduce:

1. c++ can not rename symbol or F2 not found
2. python, i can find F2 and rename symbol. 

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file issue against C++ extension.

**Comment by 91devel** [comment]
When I write C++ code, I select the functions that need to be renamed, press F2, do not pop up the renamed small form, right-click menu, nor rename the options. But when I write Python code, select the need to rename the function name, press F2, small form will pop up rename, right-click menu can see rename symbols after the rename option, press Enter all refer to this function file will be updated.
