### ISSUE TITLE
Error: Cannot find module '/home/travis/build/obrejla/vscode-jsthis/out/test'

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#3216]
Hi, 

I have a problem running my extension code on Travis. The problem is, that my extension is NOT TypeScript project, so:

1. `- npm run vscode:prepublish` section in `.travis.yml`is not needed (when I have it there, it prints an error that typescript can not be found) and
2. because my code is not "prepublished", then no "out" dir is created, but
3. `vscode/bin/test`, which is called by a "test" script, sets current working dir to: `path.join(process.cwd(), 'out', 'test')` when my test dir is NOT set manually.

So it's a bit more complicated and solutions could be:

1. describe it somewhere, how exactly should configuration for travis and plain javascript project look like, that one must define env var in `.travis.yml` - `- CODE_TESTS_PATH="$TRAVIS_BUILD_DIR/test"` (write differencies [to web](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines))
2. detect whether user uses prepublish, and if so, then add an "out" dir to path

Or maybe I'm missing something :))

Thanks!

**Comment by bpasero** [comment]
Good catch, I pushed vscode@0.11.4 to address this.

**Comment by alexandrudima** [comment]
@bpasero Not sure what I should verify?

**Comment by bpasero** [comment]
Should be ok and verified by @obrejla
