### ISSUE TITLE
Using -parameters in the terminal doesn't show them

### ISSUE THREAD

**Issue by CrispyBacon1999** [Microsoft/vscode#32165]
When using the built in terminal, running a program with arguments using a dash makes the text become invisible.

**Comment by Tyriar** [comment]
Please provide more information:

- OS
- VS Code version
- What command are you running?
- What other commands have you tried?
- Can I get a screenshot of the error?
- Can you open devtools (Help > Toggle Developer Tools) and check the console for errors?

**Comment by CrispyBacon1999** [comment]
Just tested a bit and it turns out that it's an issue with the color theme I'm using. Apparently the color for the parameters is the same color as the terminal background because hovering over the invisible letters shows them.
