### ISSUE TITLE
spawn EACCES error alerts all the time

### ISSUE THREAD

**Issue by ganeshrahul** [Microsoft/vscode#32171]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-project|Fro|2.1.0
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.1.0
php-formatter|Sop|0.2.4
html-css-class-completion|Zig|1.8.0
vscode-database|baj|1.2.0
vscode-intelephense-client|bme|0.7.2
php-autocomplete|bsc|0.4.2
vscode-html-css|ecm|0.1.7
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.6.32
mysql-scratchpad|jbl|0.1.1
php-symbols|lin|2.1.0
code-beautifier|mic|1.7.2
HTMLHint|mka|0.3.3
atom-keybindings|ms-|3.0.1
mysql-inline-decorator|odu|0.0.4
vscode-icons|rob|7.12.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I'm curious whether an extension could be causing this. Can you launch vscode with `--disable-extensions` and check whether it reproes?
