### ISSUE TITLE
Explorer: Allow to cut and paste via Cmd+Option+V

### ISSUE THREAD

**Issue by akliyiping** [Microsoft/vscode#32172]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
vsc-material-theme|Equ|1.0.2
code-settings-sync|Sha|2.8.2
html-snippets|abu|0.1.0
project-manager|ale|0.19.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
code-runner|for|0.6.32
search-node-modules|jas|1.1.1
Angular2|joh|2.4.0
vscode-icons|rob|7.12.0
vim|vsc|0.9.0
vscode-preview-server|yui|0.7.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. command+shift+e and choose a file name 
2. command+c
3. click a other folder
4. command+option+v
5. There was no response

**Comment by akliyiping** [comment]
command+option+v can cut this file in finder

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
