### ISSUE TITLE
Bug autocomplete : string not replaced completely

### ISSUE THREAD

**Issue by devistar** [Microsoft/vscode#32174]
- VSCode Version: 1.14.1
- OS Version: Windows 8.1

![bug-vscode-autocomplete](https://user-images.githubusercontent.com/11228594/29110342-a9256c1e-7ce6-11e7-926b-b0e405ff2b3a.gif)

Extension : Vetur
Editing stylus code in a .vue file.
It uses word based suggestion.

Is it related to extension or vscode ?

**Comment by weinand** [comment]
Please file issue against extension
