### ISSUE TITLE
vsce package fails (Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node ./node_modules/vscode/bin/compile")

### ISSUE THREAD

**Issue by elonmallin** [Microsoft/vscode#3217]
Trying to package an extension fails with this output:
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node ./node_modules/vscode/bin/compile"

I saw the issue #3113 but it didn't help me even though I'm on windows.
My setup:
Windows 10
Node v4.3.1
VSCode 0.10.8

I tried deleting the node_modules directory and running npm install again but that didn't help.
Closed all vscode windows open, restarted computer, reinstalled node, removed %appdata%/roaming/npm and npm_cache.

Please help

**Comment by pflannery** [comment]
I had the same problem today. 

When I ran 
```cmd
node node_modules\vscode\bin\compile
```

I got

```
node_modules/vscode/vscode.d.ts(2761,16): error TS2435: Ambient modules cannot be nested in other modules or namespaces.
```

So I commented out the lines at `node_modules/vscode/vscode.d.ts(2761,16)`
```js
// declare module 'vscode' {
// 	export = vscode;
// }
```

and then `vsce package` worked for me.

@elonmallin  try running `node node_modules\vscode\bin\compile` from the root folder of your extention and see what errors (if any) are outputted.

**Comment by elonmallin** [comment]
Hey, thanks a lot. I noticed there was an error in my code when I ran that. Fixed it, and now it's working.
