### ISSUE TITLE
C语言环境配置

### ISSUE THREAD

**Issue by Ai-Maxis** [Microsoft/vscode#32179]
![2017-07-26_li](https://user-images.githubusercontent.com/26027395/29113157-e03d6a30-7d22-11e7-9cee-c0107a3f7d05.jpg)
![2017-07-26 2 _li](https://user-images.githubusercontent.com/26027395/29113243-1c16040e-7d23-11e7-9893-d6a0d6b3ec2b.jpg)

这是什么问题？我的代码保存在E:\code\c文件夹下

**Comment by King66** [comment]
逗比

**Comment by weinand** [comment]
Please file issue against C++ extension
