### ISSUE TITLE
Files Stored in oneDrive can not be opened at all

### ISSUE THREAD

**Issue by a1development** [Microsoft/vscode#32176]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
coldfusion|ili|0.0.10
new-cmd|odo|0.2.0
Angular2|UVB|0.4.1
cordova-tools|vsm|1.2.9

---

Steps to Reproduce:

1. Open a file stored in your OneDrive folder on your local machine. 
2. Error Message comes up "The path ... .. seams to be not present" ( translated from german )

Reproduces without extensions: no

**Comment by weinand** [comment]
@a1development I cannot reproduce this problem.
How exactly are you opening a file from your OneFolder?

**Comment by a1development** [comment]
I have tried 2 different methods:

1.	Using the File -> Open File Menu ( translated from german )
2.	Using Drag & Drop 

 

Both version lead to the same result. 

 

Maybe it has something to do with the windows version that I am using? It s an insider build that already has the new oneDrive placeholder feature.

 

Von: Andre Weinand [mailto:notifications@github.com] 
Gesendet: Mittwoch, 9. August 2017 17:25
An: Microsoft/vscode <vscode@noreply.github.com>
Cc: a1development <mboltersdorf@a1development.net>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/vscode] Files Stored in oneDrive can not be opened at all (#32176)

 

@a1development <https://github.com/a1development>  I cannot reproduce this problem.
How exactly are you opening a file from your OneFolder?

**Comment by weinand** [comment]
Above you said: "Reproduces without extensions: No"
So, the problem does not occur if you are not using any extensions.
This means that most likely an extension causes this problem (and not VS Code).
Could you please try to find the extension that causes this? Thanks.

**Comment by a1development** [comment]
OK i just tested it without extensions using „code --disable-extensions” to start code. 
The problem remains the same. 
It s only inside my onedrive folder. Other folders are fine.

And it only happens since the update to onedrive where they reintroduced the file placeholders. ( The system where you can choose if the file remains on your system or not ) I checked all different stats but the problem stays.

 

Von: Andre Weinand [mailto:notifications@github.com] 
Gesendet: Donnerstag, 10. August 2017 14:55
An: Microsoft/vscode <vscode@noreply.github.com>
Cc: a1development <mboltersdorf@a1development.net>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/vscode] Files Stored in oneDrive can not be opened at all (#32176)

 

Above you said: "Reproduces without extensions: No"
So, the problem does not occur if you are not using any extensions.
This means that most likely an extension causes this problem (and not VS Code).
Could you please try to find the extension that causes this? Thanks.

**Comment by weinand** [comment]
@a1development thanks for the additional info. We'll look into this.

**Comment by bpasero** [comment]
#32011
