### ISSUE TITLE
Clicking on JavaScript comment lines in HTML causes error

### ISSUE THREAD

**Issue by xjy666** [Microsoft/vscode#32178]
The problem has been raised, but I haven't found an effective solution.Does anybody know how to solve this?For example, you won't report wrong after clicking.

**Comment by King66** [comment]
you have found the issue: https://github.com/Microsoft/vscode/issues/30774, why do you report again?

**Comment by kzhui125** [comment]
有意思吗？
一个issue提了又提，人家已经在解决了没看到？
