### ISSUE TITLE
Problem with Toggle block comment (space is added after uncomment)

### ISSUE THREAD

**Issue by s-mikhailov** [Microsoft/vscode#32177]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
vscode-eslint|dba|1.2.11
intellij-idea-keybindings|k--|0.2.13

---

Steps to Reproduce:

1. Create a new .js (or html) file
2. Add some text
3. Select the text
4. Comment the text (Toggle block comment, Shift+Alt+A)
4. Uncomment the text => space (blank character) will be added at the beginning of the text.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
It's fixed in 1.15.
