### ISSUE TITLE
iOS VSCode (iPad pro) i know it was discussed several times, but is it even potentially possible?

### ISSUE THREAD

**Issue by idchlife** [Microsoft/vscode#32180]
I love VSCode with all of my heart. I'm using it for everything but exclusively I'm using it for TypeScript coding.

Right now there are no official apps from IDE giants (jetbrains, microsoft) for iOS (by iOS I mean iPad 
(likely) with keyboard).

There are 10.5 and 12.9 iPads now. And as I can guess with iOS 11 there are much more possibilities to develop "proish" apps.
And right now there are several so-so apps for coding on ipads.

I mean I think it's one part of the future - coding on the go with tablet which works fast, stable and has a nice screen and can have a keyboard to be attached and used. Need more screen? Attach monitor or connect to it wireless.

And I think VSCode has huge part of such future and in general VSCode has potential to become (if it's not yet) one of the best IDEs for web+ development.

If it's not possible now, what can be changed in community, or numbers of coders with iPads or maybe some restrictions on iOS which can be removed?

**Comment by weinand** [comment]
VS Code implementation is based on Electron which doesn't run on iOS.

**Comment by tywang2006** [comment]
I think You are wrong, Electron is able to run in mac. there are many desktop app built in electron which are running in mac. there is vscode mac version running perfectly so I believe it could be possible to deploy vscode into ios.

**Comment by pheuter** [comment]
While VS Code may not run on iOS due to Electron incompatibilities, there may be hope for [Monaco](https://github.com/Microsoft/monaco-editor) to be accessible from Safari or integrated into the Azure iPad app using the Azure Cloud Shell.

**Comment by chrisdias** [comment]
the monaco editor has been integrated into the Azure Cloud Shell: https://azure.microsoft.com/en-us/blog/cloudshelleditor/

as far as running on iOS, we're grooming our backlog this milestone and it is unlikely to make our backlog in the next 6-12 months so i'm closing this suggestion.

**Comment by Morialkar** [comment]
As does Slack, Spotify and many desktop Electron applications with iOS apps available
