### ISSUE TITLE
Is there any keyboard shortcut to open context menu on a highlighted file/folder?

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#3218]
**Using mouse, creating a file in a desired folder is super easy via context menu.**

With ⇧⌘E  followed by ↓ or ↑ and ← it is possible to highlight the folders in the explorer. 
Wondering if there is any keyboard shortcut to bring up the context menu on highlighted folder:question: 
It would be easy to create a **file** in a **desired folder** without using mouse.

I could create a new file with ⌘N, but the **default save location** is the **root folder**, navigating to a **desired folder** via **keyboard** in the **save dialogue** is not very easy. 
Would it be possible to **default** the **save location** to the currently **highlighted folder** in the explorer:question: 

Any other work around/pointer would be very helpful. Thanks!!

**Comment by sarbbottam** [comment]
Just noticed a (very) long path :smile: 
* ⇧⌘E followed by ↓ or ↑ and ← to highlight the desired folder
* ⌘K E to focus the *Working Files* panel
* Tab to focus the new file icon ![screen shot 2016-02-21 at 1 12 21 pm](https://cloud.githubusercontent.com/assets/949380/13205436/d984b04e-d89c-11e5-9bb0-be3ee92e2e97.png)
* Press Enter

Using mouse seems a better option than the one I listed above. Any better work around/pointer would be very helpful. Thanks!!

**Comment by joaomoreno** [comment]
This extension looks useful: [dkundel.vscode-new-file](https://marketplace.visualstudio.com/items?itemName=dkundel.vscode-new-file).

**Comment by sarbbottam** [comment]
Thanks @joaomoreno
