### ISSUE TITLE
Emmet for Yandex BEM support in JSX

### ISSUE THREAD

**Issue by yujiaze** [Microsoft/vscode#32183]
- VSCode Version: 1.14.2
- OS Version: 10.12.5

Steps to Reproduce:

1. typein `.b_m1._m2|bem` in a React Component `render` function
2. press `tab`
3. got  `<div className="b_m1 _m2"></div>`
4. expected `<div className="b b_m1 b_m2"></div> `	

Reproduces without extensions: Yes

FYI：[Yandex BEM](https://docs.emmet.io/filters/bem/)

**Comment by mrmlnc** [comment]
Hello, @yujiaze,

You use the original Emmet or Emmet with `emmet.useNewEmmet: true` option?

**Comment by ramya-rao-a** [comment]
Looks like the bem filter never worked for in jsx in VS Code.

**Comment by ramya-rao-a** [comment]
Bem for jsx never worked before VS Code 1.15

In VS code 1.15, there is a broken experience for bem
Its too late in the game to push a fix for 1.15... We are just about to release 1.15

So I have fixed it for VS Code 1.16 and you should be able to see the fix in 1.16 insiders next week.

If there ever is a recovery build for 1.15, I'll try and get this in for 1.15.1

**Comment by ramya-rao-a** [comment]
The fix for this made it to 1.15.1 already
