### ISSUE TITLE
Support bell character in terminal

### ISSUE THREAD

**Issue by sumproxy** [Microsoft/vscode#32184]
- VSCode Version: 1.14.2 cb82febafda0c8c199b9201ad274e25d9a76874e
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Start VSCode
2. Launch a Terminal
3. Run 
> echo -ne '\007'
4. Check if any sound is emitted

Reproduces without extensions: Yes

**Comment by felipenmoura** [comment]
Hi.
Any update on that?
:)
