### ISSUE TITLE
Remove git repository

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#32187]
I add a directory to my Git view, how can i remove it?

**Comment by joaomoreno** [comment]
This doesn't seem to be a Code issue at all. If you feel otherwise please elaborate. Screenshots are always helpful.

**Comment by ShalokShalom** [comment]
How to remove the git directory from its view module ~ in Visual Studio Code ~

I think i solved it by removing and readding the module at all. Very strange.
