### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by siva151** [Microsoft/vscode#32190]
- VSCode Version:   1.15.insider
- OS Version: win 10

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Do you remember the context in which this occurred?

**Comment by siva151** [comment]
I don't no it  occurs when i open visual code

**Comment by weinand** [comment]
And you see this problem whenever you open VS Code?

**Comment by alexandrudima** [comment]
@siva151 Does this issue occur when launching VS Code with extensions disabled `code --disable-extensions` ?
