### ISSUE TITLE
vscode should not try to contact the internet when computer is disconnected

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32196]
_From @aybabtme on August 9, 2017 18:54_

When I go offline, on planes or whatever, I want to be able to use my editor without issues. Currently, parts of VS Code appear to be trying to check for upgrades or things like that, and does so even when my wifi is completely off. When those upgrades fail, it shows pops up that are distracting.

VS Code should detect that there's no connectivity and avoid spamming user with connection error messages.

_Copied from original issue: Microsoft/vscode-go#1137_

**Comment by ramya-rao-a** [comment]
@aybabtme Can you share one of the error messages that you see?

**Comment by aybabtme** [comment]
@ramya-rao-a yup next time I see the pop-up, I'll try to take a screenshot and loop back.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
