### ISSUE TITLE
Why do Windows .zip builds include "win32" in the filename?

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#32195]
Installer: VSCodeSetup-x64-1.14.2.exe
.zip: VSCode-**win32**-x64-1.14.2.zip
32-bit Installer: VSCodeSetup-ia32-1.14.2.exe
32-bit .zip: VSCode-**win32**-ia32-1.14.2.zip

This may cause users to be confused as to whether they are installing a 32-bit or 64-bit build.

Should the .zip file names also start with "VSCodeSetup"? 
VSCodeSetup-{bitness}-{version}.zip where the only change between installer and .zip is the file extension

**Comment by joaomoreno** [comment]
We follow exactly the same format as [Electron](https://github.com/electron/electron/releases), Node, etc.

Win32 is an API name, not a reference to 32 bits.
