### ISSUE TITLE
[ Feature Request ] Previous and Next buttons / Tabs to switch terminals

### ISSUE THREAD

**Issue by Aetherall** [Microsoft/vscode#32194]
Hi ! It would be more easy for us to switch between terms via two buttons instead of a selector list
Even better, we could wave a tab for each term and the ability to switch between them by click & prev/next shortcuts

Thanks team !

**Comment by Tyriar** [comment]
Tabs are tracked in https://github.com/Microsoft/vscode/issues/10546 which is the direction we will eventually go.

In the meantime I recommend setting up some keybindings to make switching easier. Here's what I use:

```js
{ "key": "ctrl+shift+j",    "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",    "command": "workbench.action.terminal.focusPrevious" }
```
