### ISSUE TITLE
C/C++ Go to/Peek definition not working and parsing is stuck

### ISSUE THREAD

**Issue by hagaishapira** [Microsoft/vscode#32191]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
meson|asa|1.0.0
python|don|0.7.0
cpptools|ms-|0.12.2
vim|vsc|0.9.0

(1 theme extensions excluded)

Opening my project on a new instance of code non of the navigation to definition / declaration work and all result in "No definition found for <Symbol>". 
Little read flame in the bottom right corner gets stuck after a while saying "Parsing..."

---

Reproduces without extensions:  No (extension related)

**Comment by hagaishapira** [comment]
however, definition does show upon hovering.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#962
