### ISSUE TITLE
Make Outdated extensions prominent in the Extensions view

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32198]
- VSCode Version: 1.14.2
- OS Version: win7x64

Steps to Reproduce:

You have 3 extensions to update, I click on a button and..... I see no extensions to update. First I thought it's a bug. But then I noticed (looking at tiny 12), that I have already installed 12 extensions, and the problem in this "Recommended list of whatever", that covers a half of whole extensions area.

Well, guys, that's confusing and annoying! If some genius in VS Code dev team decided to add this "recommended list of some annoying stuff", why he or she didn't think about showing a scroll bar BY DEFAULT in "Installed exts list"? Is it so hard? Why was it so necessary to make a list of "recommended exts" to cover half height of whole extensions area? If it's only, by the way, 5 extensions there you have to recommend me to install.

If you will look at screenshot, and you don't remember how many of exts you have already installed, doesn't it look like you installed only 7 exts? And only super-extra-tiny number 12 will remind you, that you have installed 12 exts, and that you should scroll list a little bit down.

You just should find a way to fix this confusing UI component.

Thanks.

![image](https://user-images.githubusercontent.com/24613274/29145546-4ec32c40-7d66-11e7-9296-2e735f7a04f2.png)

**Comment by jens1o** [comment]
I know that feeling, but I use 
![image](https://user-images.githubusercontent.com/11234139/29253579-40341144-8081-11e7-8485-91bf764229c3.png)

and then it's quite easy to do that.

Alternatively, you can automatically let vscode update your extensions.

**Comment by user3323** [comment]
@sandy081 

how about to give a different background color to the list of recommended exts?
a little bit brighter .... so it will definitely look like anything from another group of items

**Comment by sandy081** [comment]
@user3323 In latest, we show different badge/flag for recommended extensions

![image](https://user-images.githubusercontent.com/10746682/36418478-46a824c2-162f-11e8-944c-58ea70546a03.png)

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/32198#issuecomment-323748060 covers all the points of the recommended section taking up the space.

We now have the "Update to ..." button available on the outdated extension which makes it stand out

![image](https://user-images.githubusercontent.com/16890566/41367066-d609ac6e-6ef2-11e8-89fa-72dc0793233a.png)

I dont see any other remaining concerns to be addressed here...

@sandy081 If you agree, we can either close the issue or add the "needs more info" label and which will then close the issue in a few days

**Comment by sandy081** [comment]
Adding needs more info label is a good option to check if user is expecting more or not.
