### ISSUE TITLE
Emmet sometimes triggered at a bad time in PHP

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32207]
```php
<?php
foo::bar
```

Emmet will be triggered at the end of the line, but it seems like it shouldn't be. It's only when the `::` is present. `foo` doesn't trigger it, but `div` does, which is correct.

There might have been other times when it showed up in PHP in an inappropriate place, will keep track of it...

**Comment by ramya-rao-a** [comment]
Ideally we wouldnt want any emmet suggestions inside the `<?php ?>` block. But lets use #29354 for that discussion.

This current issue can be used for problems that can be fixed with easy regex solutions

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-emmet-helper/commit/b8ab87406883f9c41a0289af08f4439558689a0f
