### ISSUE TITLE
Support extended Markdown API for MarkedString during Hover

### ISSUE THREAD

**Issue by FabienPean** [Microsoft/vscode#32205]
- VSCode Version: 0.15
- OS Version: Windows 10 Pro x64

With the new [Markdown API](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-markdown.md), one can extend the markdown engine of vscode to render things like equations using the katex or mathjax markdown-it plugin in the markdown preview window of a file. 

However, after some test on the latest insider, I could not make the system of markdown-it extension work when using the hover function in the editor to render what the API calls "MarkedString".

This would be beneficial for many reasons, specifically in my case, when there are mathematical equations in comments formatted in latex.

This is somewhat related to #11877 #21141 #17298 #1920. Feel free to close it if it is considered as duplicate.

**Comment by mjbvz** [comment]
The new markdown API is an API exposed by the markdown extension. The core editor has no knowledge of this API and uses a completely different engine for rendering markdown.

I don't think allowing extending `MarkedString` in a manner akin the the markdown API something we'd ever really want to support, and certainly not the css and script contributions.

For this case, can you preprocess the markdown to convert mathematical equations into images?

**Comment by mjbvz** [comment]
Closing this for now. Allowing extensions to provide richer docs/hover content is an interesting idea but I don't think markdown extensions are how we want to go about supporting this

**Comment by FabienPean** [comment]
I was giving a try with potential options. Unfortunately, I could not make anything really working, and which would be convenient.

Another alternative would be the support of doxygen. It does not seem to happen quite soon from other issues I could see. Having equation processed when browsing code would certainly please scientists. Hopefully hearing about such possibility soon :)
