### ISSUE TITLE
chrome debugger can't hit breakpoint in html file

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#32203]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.1.7

---

Steps to Reproduce:

1. open new folder in code
2. new file 'index.html':
````
<script>
    var i = 3;
</script>
````
3. set breakpoint on line 2
4. `http-server .`
5. f5 - add 'Chrome' configuration, set port, etc...
6. f5

doesn't stop.

Reproduces without extensions: N/A

**Comment by weinand** [comment]
Please file this issue against debugger-for-chrome

**Comment by Spongman** [comment]
ugh. can't you just move it?

**Comment by weinand** [comment]
Yes, but I think you can do this too: https://github-issue-mover.appspot.com
If not, I'll do it...

**Comment by Spongman** [comment]
yeah. i'm already too far into the "i wish this would just work, why am i wasting my time" territory.

**Comment by weinand** [comment]
If we would not have to move all these misplaced issues, we would have more time to make this work.

**Comment by Spongman** [comment]
you fail at PR.
