### ISSUE TITLE
vscode generated too many GIT processes consuming considerable CPU to cause computer caton

### ISSUE THREAD

**Issue by Ruy-Zhou** [Microsoft/vscode#32209]
vscode generated too many GIT processes consuming considerable CPU to cause computer caton. If I close vscode, this issue was not exsited.

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.2.0
stylus|buz|0.1.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
EditorConfig|Edi|0.9.4
php-debug|fel|1.11.1
vetur|oct|0.9.3
java|red|0.8.0
vscode-icons|rob|7.12.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. open vscode, keep it running above a day (all night);
2. the next day: do some changes on files in vscode;
3. the issue should be reproduced.

**Caution**：`all night` which can get the compute into dormant or sleeping, which may cause the issue above.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Do the processes eventually quit?

Note that if you don't need the git integration, you can disable it with `git.enabled = false`.

**Comment by Ruy-Zhou** [comment]
Yes, quited. But it's reproduced in every 5~10 minutes. 
It's a nodejs project on git.

**Comment by joaomoreno** [comment]
That is how VS Code works. In order to get the git features working we spawn `git.exe`. If you don't want those features, you can disable them with `git.enabled = false`.

**Comment by guhuajun** [comment]
That's too bad. I am missing the legacy git behavior.
