### ISSUE TITLE
长时间不操作，会出现黑屏，或者黑块现象

### ISSUE THREAD

**Issue by 1227233860** [Microsoft/vscode#32208]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.长时间不对VSCode进行操作，程序会发生黑屏，必须重启

Reproduces without extensions: No

**Comment by weinand** [comment]
Could you please translate your issue to English, thanks.

**Comment by 1227233860** [comment]
Oh,sorry.My problem is that If I do not operate for a long time, there will be black screen, or black block phenomenon.So I have to close it and solve it.

**Comment by weinand** [comment]
Above you said: "Reproduces without extensions: No"
So, the problem does not occur if you are not using any extensions.
This means that most likely an extension causes this problem (and not VS Code).
Could you please try to find the extension that causes this.

**Comment by 1227233860** [comment]
I think what you said is useful, I will try to use your method, thanks.

**Comment by aeschli** [comment]
Closing.
