### ISSUE TITLE
Debugger Hangs Without Any Debugger Console Errors And Or "Error: no such module 'icu'"

### ISSUE THREAD

**Issue by gdad-s-river** [Microsoft/vscode#32219]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

**Extension|Author (truncated)|Version**

material-icon-theme|PKi|2.1.0
vscode-docker|Pet|0.0.16
ejs-language-support|Qas|0.0.1
theme-verdandi|be5|1.5.0
css-in-js|gda|0.0.1
vscode-eslint|dba|1.2.11
python|don|0.7.0
prettier-vscode|esb|0.22.1
vscode-jade-snippets|mrm|1.0.1

(21 theme extensions excluded)

Reproduces without extensions: Yes

---

This seems to be happening only on my local machine, so I'm not sure if this is reproducible.

I'm trying to get the [Hello World](https://code.visualstudio.com/docs/extensions/example-hello-world) extension example. I've generated the example code with `yo code` yeoman generator inside `~/.vscode/extensions`.

**Without extensions**:
When I debug it, it shows me this: 

<img width="1280" alt="screen shot 2017-08-10 at 1 17 27 pm" src="https://user-images.githubusercontent.com/4655633/29160250-1f9eb8f8-7dcf-11e7-8134-573c9d405b51.png">

It also seems to keep having errors of absence of `*.nls.en-gb.json` files at various locations inside `'/Applications/Visual Studio Code.app/Contents/Resources/app/extensions`. I've reinstalled vscode multiple times, but these files are never there, instead the en files are available without any language suffix `*.nls.json`. 

and there seems to be no `Hello World` command available. 

**With Extentions**:

When I run the command `Hello Word`, it seems to show the information message **Hello World** fine. 

<img width="1280" alt="screen shot 2017-08-10 at 1 28 42 pm" src="https://user-images.githubusercontent.com/4655633/29160438-d94682ae-7dcf-11e7-81d2-9c34b425ae2e.png">

But after the breakpoint at the starting of `/Applications/Visual Studio Code.app/Contents/resources/app/out/bootstrap.js` the debugger either gets stuck or it throws the same error of `Error: no such module 'icu'` randomly (but mostly it hangs). I've tried it multiple times.

**Comment by weinand** [comment]
You have checked the option "All Exceptions" in the breakpoints view. This means that even caught exceptions (like the one you are seeing) are breaking into the debugging.
Please disable "All Exceptions" and see whether this helps.

**Comment by gdad-s-river** [comment]
Thanks for the quick reply! I unchecked both "All Exceptions" and "Promise Rejects" (which was the default case I guess?). Debugs jumps at the top of bootstrap.js like I mentioned before, but on continuing it, hangs. No extra debug console information either.

**Comment by weinand** [comment]
If I check all three exception options, I'm seeing the same exceptions as you (which is correct and expected).

So for extension debugging the exception options should be set like this:
![2017-08-10_11-04-14](https://user-images.githubusercontent.com/1898161/29163091-aad5f3aa-7dbb-11e7-8ae5-5974afe60761.png)

With these options I can press F5 and a new VS Code window opens.
Inside that window I press F1 and then type "Hello" which selects the Hello action.
Running this commands hits the breakpoint in the other window:

![2017-08-10_11-08-29](https://user-images.githubusercontent.com/1898161/29163348-7a477eb0-7dbc-11e7-9a18-8783129db353.png)

So extension debugging works for me in VS Code 1.14.2 on macOS 10.12.6

**Comment by weinand** [comment]
I assume your mac is connected to the internet?
When hitting the breakpoint the debugger has to load some additional source from our servers so that you can step through the source.
The source archive is 1.8 MB and it needs some time to download (but it is cached after that).
If you have a slow connection that could be the reason why you think the debugger is stuck.

You can find it in your macOS tmp folder:
![2017-08-10_11-15-21](https://user-images.githubusercontent.com/1898161/29163702-90e95a70-7dbd-11e7-8b20-14da65d06564.png)

**Comment by gdad-s-river** [comment]
(facepalm moment): I was trying to execute **hello word** in the original window (before hitting F5/debug). Everything working now 😄. Thanks! We can close this now.

**Comment by weinand** [comment]
My pleasure!
