### ISSUE TITLE
Ability to choose different shells on create new terminal

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#32215]
Hello,

I couldn't find a feature request for this and I saw that you're struggling with similar things at #10546 and #7504
But I'd like to be able to configure multiple shells and be able to choose one on the fly (without having to switch the one configured all the time)
So for example sometimes I need to use powershell and sometimes bash on windows - it would be awesome to have them pre configured and be able to choose one of them while creating a new terminal within VSCode.

**Comment by Tyriar** [comment]
This extension solves this problem https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
