### ISSUE TITLE
Feature request: Display wrap mark

### ISSUE THREAD

**Issue by akliyiping** [Microsoft/vscode#32214]
when auto word wrap  , I can't tell whether one line or more lines.

**Comment by rebornix** [comment]
@akliyiping doesn't the line number indicates whether it's wrapped or not? 

(Line 14)
![image](https://user-images.githubusercontent.com/876920/29296605-41a8e4b6-8110-11e7-93ea-6ee47788d354.png)

**Comment by akliyiping** [comment]
the line number indicates it's wrapped
