### ISSUE TITLE
System environment in VSCode terminal is different with OS (MacOS)

### ISSUE THREAD

**Issue by hoksilato** [Microsoft/vscode#32213]
- VSCode Version: Version 1.14.2 (1.14.2)
- OS Version: macOS Sierra 10.12.6 (16G29)
- Extensions:

<img width="229" alt="vscode-extensions" src="https://user-images.githubusercontent.com/2535342/29155621-822beb2e-7dc7-11e7-8347-8abcd3f84b10.png">

Here is the screenshot. 

![vscode](https://user-images.githubusercontent.com/2535342/29155454-65474fea-7dc6-11e7-90c2-4f3bc13a3ec1.png)

The first and second is iTerm2 (Build 3.1.beta.6) and the last one is VSCode terminal. I tried to echo GOOGLE_API_KEY from environment variables and get the different results.

My project is using Ruby on Rails with `dotenv-rails` gem.

Sorry, I don't know how to reproduce. But I tried to open VSCode without extension and still get the same issue.

**Comment by Tyriar** [comment]
`GOOGLE_API_KEY` is set by Electron, we haven't had any reason to remove it. Is this just an inconsistency you noticed or is this causing a problem?

**Comment by hoksilato** [comment]
Because the `GOOGLE_API_KEY` is set by Electron was expired so that I want to use my own but whenever I start the web server (Puma - I'm using Rails) in integrated-terminal, it keeps using the one is set by Electron.

**Comment by Tyriar** [comment]
Out of curiosity, where do you set your `GOOGLE_API_KEY`?

**Comment by hoksilato** [comment]
My project is using Ruby on Rails with `dotenv-rails` gem. So that I set my `GOOGLE_API_KEY` in `.env` file in my project root.
