### ISSUE TITLE
Alt+F, A doesn't work as expected

### ISSUE THREAD

**Issue by amithegde** [Microsoft/vscode#32218]
- VSCode Version: Code - Insiders 1.15.0-insider (2c3e2c291c515619f64e7c9cddf14c565b7f3d92, 2017-08-08T21:31:39.272Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.2.3
gitlens|eam|4.3.3
vscode-great-icons|emm|2.1.13
json-tools|eri|1.0.2
cpptools|ms-|0.12.2
csharp|ms-|1.11.0
code-spell-checker|str|1.3.6

---

Both `Save As` and `Add Folder to Workspace` use same keyboard shortcut Alt=F, A. Please fix.
 
Steps to Reproduce:

1. Open a file and try typing Alt+F, A

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@isidorn didn't you fix this?

**Comment by isidorn** [comment]
Yeah, the user is using 1.15 insiders.
@amithegde please update to latest vscode insiders
