### ISSUE TITLE
Task runner problemMatcher could use an origin or source field

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#3221]
If you have multiple tools contributing errors and warnings e.g. linters, unit test runners, etc, it can be hard to tell which tool an error or warning it associated with.  Here's an example from the PowerShell extension where we are working on Pester (test framework) integration.  Note that a linter is already integrated.
![vscodepestermessage](https://cloud.githubusercontent.com/assets/5177512/13206850/9b26ce1e-d8c3-11e5-8108-77526abc10b8.png)
In this case, all the errors "happen" to be test errors and the warnings are from the linter (PSScriptAnalyzer). However, the linter can contribute errors as well.  I and I think users of the extension, would like to know from which source a particular entry came from.  Perhaps this is a bit of text that prefixes each message e.g.:

```
x Pester: Expected: {False}
  Foo Tests.ps1(7,1)
! PSScriptAnalyzer: The variable 'd' is assigned by never used.
  DebugTest.ps1(1,1)
```

or maybe the text is added afterwards:

```
x Expected: {False} [Pester]
  Foo Tests.ps1(7,1)
! The variable 'd' is assigned by never used. [PSScriptAnalyzer]
  DebugTest.ps1(1,1)
```

**Comment by ramya-rao-a** [comment]
@dbaeumer Is this still meant for the January milestone? If not, can you move it to February milestone?

**Comment by dbaeumer** [comment]
To verify:

- use one of the predefined matchers like `$tsc` or `$eslint-stylish` and ensure that captured problem from a task run have a `[ts]` or `[eslint]` prefix.

**Comment by dbaeumer** [comment]
@egamma you might want to use this in TSLint.
