### ISSUE TITLE
[Enhancement] PyCharm-like "where am I in the hierarchy?" feature

### ISSUE THREAD

**Issue by marmistrz** [Microsoft/vscode#32227]
There's a really handy feature (they only one from PyCharm I'm missing). If I'm in a deeply nested block, PyCharm will tell me that 
```
def foo(): 
  for i in list:
    # very
    # long
    # code
    if condition:
        # more 
        # long
        # code
        while...: 
    while....:
        if...:
```
that the current cursor position is positioned in hierarchy that way: 
` for i in list | if condition | while ... `

It would be great if VS Code provided such a feature!

**Comment by rebornix** [comment]
This is a good extension candidate :)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
