### ISSUE TITLE
Clear recent clears files AS WELL as projects

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#32223]
- VSCode Version: 1.14.2
- OS Version: win10

Steps to Reproduce:

1. ctrl-shift-p
2. clear recent files
3. open file from menu to the top left
4. choose "open recent"
5. recent *projects* that were listed in "open recent" are gone.

I presume this is expected behaviour. Should it be? I use the clear recent to clean up the ctrl-p menu. But I don't my recent projects to disappear, I use that menu quite often, `alt-f r` gets me quite fast there.

**Comment by bpasero** [comment]
@wildeyes use "Clear Editor History" instead.
