### ISSUE TITLE
New window size

### ISSUE THREAD

**Issue by MrAndersen1** [Microsoft/vscode#32225]
- VSCode Version: 1.14.2 (1.14.2)
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. File -> new window.
2. Resize the new window.
3. File -> new window.

Every time I do file->new window it has forgotten the previous size I wanted a new window to be in.
VSCode is usually very good at remembering the size but not for "new window".
Maybe it could remember the size it is in, for the next time I open a new window, before I go to the next step of opening a project, creating a new file or using a link on the Welcome-page?
Or simply use the size of the last window.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Try via setting: `"window.newWindowDimensions": "inherit"`

**Comment by MrAndersen1** [comment]
Oh, thanks!
