### ISSUE TITLE
Try-catch in VS Code call to Get-Mailbox don't catch error

### ISSUE THREAD

**Issue by AndersElonGroup** [Microsoft/vscode#32228]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows 10 1703 (OS-version 16232.1000)
- PS Version: 5.1.16232.1000
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

---

When connecting to Office365 in Powershell and call the cmd Get-Mailbox, VS Code do not Catch the Error thrown if the object (the email-address) cannot be found. 
I use this method to check if requested email-addresses is available. If the email-address is available the -ErrorAction Stop should throw an Error and the Catch will just display a message that the adress is available. If the email-adress is occupied I get information about the accountowning the adress.

When running the code in Powershell ISE i get the expected output, Catching the error.
When running the code in VS Code, the error is not caught.

Steps to Reproduce:
VS Code
1. Open O365 Session in VS Code
2. call the function with a adress that do not exist in O365
3. VS Code do not Catch the error thrown by Get-Mailbox or Get-User

PS ISE
4. Open O365 Session in PS ISE
5. call the function with a adress that do not exist in O365
6. PS ISE Catch the error thrown by Get-Mailbox or Get-User and show the Catch-output

Reproduces without extensions: Yes

`#Open O365 Session
#Get your credentials 
$cred=Get-Credential
#Connect to O365
Connect-MsolService -Credential $cred

#import  O365 Session commands
$session=New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell -Credential $cred -Authentication Basic –AllowRedirection
Import-PSSession $session -AllowClobber`

`Function ListAllEmailAdresses
{
  param ($ID)
  Try
  {
    $Mailbox = Get-Mailbox -Identity $ID -ErrorAction Stop
    $VarUser = Get-User -Identity $ID -ErrorAction Stop
    Write-Output "Email is occupied by: $Mailbox, $($VarUser.Title)"
    Write-Output $Mailbox.EmailAddresses
  }
  Catch
  {
    Write-Output "E-mail $ID is available"
  }
}`

Output when called fromVS Code:
PS C:\script> ListAllEmailAdresses -ID 'lidingo@elon.se'
The operation couldn't be performed because object 'lidingo@elon.se' couldn't be found on 'VI1PR03DC0025.eurprd03.prod.outlook.com'.
+ CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
+ FullyQualifiedErrorId : [Server=VI1PR03MB3165,RequestId=62016320-c687-41ed-9949-4b0fe854d821,TimeStamp=2017-08-09 13:54:40] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] 2CD51ECE,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
+ PSComputerName        : ps.outlook.com

The operation couldn't be performed because object 'lidingo@elon.se' couldn't be found on 'VI1PR03DC0025.eurprd03.prod.outlook.com'.
+ CategoryInfo          : NotSpecified: (:) [Get-User], ManagementObjectNotFoundException
+ FullyQualifiedErrorId : [Server=VI1PR03MB3165,RequestId=db435869-8b64-4edf-bb90-a2eb836b07fa,TimeStamp=2017-08-09 13:54:41] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] DAFB12B9,Microsoft.Exchange.Management.RecipientTasks.GetUser
+ PSComputerName        : ps.outlook.com

Email is occupied by: ,

Output when called from PS ISE:
PS C:\Script> ListAllEmailAdresses -ID 'lidingo@elon.se'
E-mail lidingo@elon.se is available

**Comment by weinand** [comment]
@AndersElonGroup I do not understand the first step "connect to O365 with VS Code". Could you please provide more details.

**Comment by AndersElonGroup** [comment]
I meant Open a new O365 session, have updated my post.

**Comment by weinand** [comment]
I still don't understand whether you are running PowerShell scripts in the integrated terminal built into VS Code or in an interactive (debugging) session of the PowerShell extension?

**Comment by AndersElonGroup** [comment]
Sorry, started using VS Code two Days ago.
Just upgraded VS Code this morning and now I cannot get the code to run at all :(

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

**Comment by weinand** [comment]
Could you please answer my question from above first.

If you have an unrelated problem with the new VS Code 1.15.0 please create a new issue to avoid confusion.

**Comment by AndersElonGroup** [comment]
I open my .ps1-file in VS Code, select each row to start the O365 session and press F8.
Then I select my function and press F8.
lastly I type a call to the function and press F8
The Result is shown in "Terminal"

**Comment by weinand** [comment]
Thanks. The functionality you are using is provided by the PowerShell extension.
I'll move this issue to their repo.

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#991
