### ISSUE TITLE
Intellisense, interface implementation and automatic using resolving doesn't work on mac

### ISSUE THREAD

**Issue by oleksiivasylenko** [Microsoft/vscode#32229]
- VSCode Version: June 2017 (version 1.14)
- OS Version: mac os sierra 10.12.16

Reproduces without extensions: Yes

Steps: 
(names in steps can be changed to another)
1) add folder issue1
2) navigate to the folder using terminal
3) run "dotnet new console"
4) run "code --disable-extensions"
5) Try to add iUser interface and the User class as the following
-------------------
using System;

namespace issue1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
    
    public interface IUser
    {
        int Id {get;set;}
        string Name {get;set;}
        List<int> Ids {get;set;}
    }

    public class User : IUser
    {

    }
}

Expected result:
    In a moment when I add List<int> property to IUser - intellisence resolve using for that 
    dependency. Adding inheriting from IUser suggests you to add missing fields and resolving it 
    automatically.  
Actual result:
    No resolved usings and no implemented properties from IUser. And what more interesting that 
    VS doesn't show you that any error exists until you build the project. Using CMD+. doesn't do 
    anything.
![program cs issue1](https://user-images.githubusercontent.com/28143505/29174868-38c8c79e-7df0-11e7-8979-46ab468b67dc.png)

**Comment by weinand** [comment]
C# and dotnet support is provided by the C# (OmniSharp) extension. If you disable all extension, there is no longer C# and dotnet support. So you cannot expect Intellisense to work properly.

**Comment by oleksiivasylenko** [comment]
Same situation with enabled extensions. Oaky then I will add this issue to OmniSharp. Thanks.

**Comment by weinand** [comment]
You can move the issue with this tool: https://github-issue-mover.appspot.com
