### ISSUE TITLE
Create Directory

### ISSUE THREAD

**Issue by ashu01** [Microsoft/vscode#32221]
* There is no option for creating a directory or creating a new project. 
* If you all would add this feature this editor will become more awesome.

**Comment by weinand** [comment]
a project in VS Code is just a folder.

To create a new project just use the "Open..." action and press the "New Folder" button:

![2017-08-10_12-15-02](https://user-images.githubusercontent.com/1898161/29166178-a2ab92e8-7dc5-11e7-90f5-1f03505a208a.png)

**Comment by ashu01** [comment]
thanks
