### ISSUE TITLE
Git diff shows same line removed and added when we save file without any change

### ISSUE THREAD

**Issue by justin-john** [Microsoft/vscode#32226]
- VSCode Version: 1.14.2
- OS Version: Ubuntu 16.04.2 LTS

Steps to Reproduce:

1. Open a file save it without any change. 
2. Goto terminal and see run command "git diff"
3. You will see several same line removed and added it again in GIT.

![image](https://user-images.githubusercontent.com/2345128/29170529-a9a40e5a-7df6-11e7-804b-c779b8749af9.png)

Reproduces without extensions: No extensions installed

**Comment by DickvdBrink** [comment]
Maybe lineending related or spaces are getting removed?

**Comment by joaomoreno** [comment]
Code is fixing your line endings for you.

**Comment by justin-john** [comment]
@joaomoreno  How to suppress this behaviour? I don't want code to fix line endings.

**Comment by joaomoreno** [comment]
cc @alexandrudima

**Comment by alexandrudima** [comment]
@justin-john You can upvote in #127

What is your scenario for wishing that your source code files contain mixed line endings ?

**Comment by justin-john** [comment]
Thank you @alexandrudima. In my repo, there are lot of files where additional white spaces are there after the actual line ends.

 In my opinion, the tool shouldn't need to be too intelligent to automatically remove these white spaces as it will create lot of problems when you worked in some other editors which doesn't have this restriction. When we save it will create lot of changes in file and reviewing will be little hard task. This auto remove line endings feature should be configurable one in setting and by default disabled.
