### ISSUE TITLE
Cann't find rename symbol menu item, F2 is not working

### ISSUE THREAD

**Issue by 91devel** [Microsoft/vscode#32224]
When I write C++ code, I select the functions that need to be renamed, press F2, do not pop up the renamed small form, right-click menu, nor rename the options. But when I write Python code, select the need to rename the function name, press F2, small form will pop up rename, right-click menu can see rename symbols after the rename option, press Enter all refer to this function file will be updated.

**Comment by weinand** [comment]
Please file C++ issues against the C++ extension. VS Code has no builtin C++ so we cannot do anything about this. You can move the issue with this tool: https://github-issue-mover.appspot.com

**Comment by 91devel** [comment]
I got it, thank you very much!

发自我的 iPhone
