### ISSUE TITLE
Caps lock is not working with Ubuntu

### ISSUE THREAD

**Issue by segmentationfaulter** [Microsoft/vscode#3223]
I have installed VSCode (version 0.10.8) in Ubuntu via umake, I can't write capital letters even if caps lock is turned on. Caps lock works fine in all other apps.

**Comment by alexandrudima** [comment]
@segmentationfaulter I cannot reproduce. Is there any input field in VS Code where Caps Lock is honored (e.g. the find widget input, the `F1` input) or is it not working anywhere?

Also, do you run Ubuntu in a VM, or have a special version of Ubuntu... or any other customizations you've done that could help us reproduce the problem.

**Comment by segmentationfaulter** [comment]
@alexandrudima I tested it, the problem was being caused by this vim extension https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

After uninstalling this extension, caps lock is working fine.
