### ISSUE TITLE
Shift-Click does not open new window

### ISSUE THREAD

**Issue by danebou** [Microsoft/vscode#32230]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
terminal|for|0.0.10
cpptools|ms-|0.12.2
csharp|ms-|1.11.0
code-spell-checker|str|1.3.6

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Shift click application in task bar. Nothing happens. Common practice is that a new window should open.

Reproduces without extensions: Yes/No

Shift-Clicking the Application icon in the taskbar doesn't launch a new window.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
