### ISSUE TITLE
[GRIPE] unedited files are replaced in current when trying to open a new file

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#32245]
please provide a configuration setting causing clicking a file to simply open a new tab, rather than replacing the current. sometimes you must reference cross file by having both files open in editor.

**Comment by cleidigh** [comment]
@r3wt 
If I understand your requirement what you want to do is to disable "preview" mode which is the temporary open file mode. In your user settings file add:

"workbench.editor.enablePreview": false,

**Comment by r3wt** [comment]
@cleidigh That's perfect, but now i want to change the issue to "stop naming things so ambiguously". 


In this case wouldn't a property called `workbench.editor.fileOpenMode` be better as an `enum` with options like `new-tab`, `current-tab`, etc. ?

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by r3wt** [comment]
wow, what a bunch of jerks to ignore my second message
