### ISSUE TITLE
Refactor FindWidget: shareable find component with history/commands

### ISSUE THREAD

**Issue by cleidigh** [microsoft/vscode#32241]
We added find widget for terminal and webview in last two iterations. Right now the way we reuse this component is still at view level, but features like history navigation, command registration, search state maintaining should be put into the component as well, instead of duplicating code in different areas.

Task list:
* [ ] History navigation
* [ ] Sharable component with commands
* [ ] Move search states into Find Widget

@cleidigh already started https://github.com/Microsoft/vscode/pull/32113 and it's a pretty good start.

**Comment by weinand** [comment]
Is this on the August plan? Who will own this?

**Comment by rebornix** [comment]
Thanks for creating this issue for me. I'll fill in more details.

**Comment by cleidigh** [comment]
@rebornix 
Shall we add the following task items?
- Add FindWidget service (BTW I figured out the skeleton for this already !)
- Make find options configurable for each widget eg: case sensitivity, regex et cetera

**Comment by rebornix** [comment]
@cleidigh yes, they can be added when above items are finished. Let's try not to make the PR too large.

**Comment by cleidigh** [comment]
Addressed with PR #31113

**Comment by alexandrudima** [comment]
Moving to September.

**Comment by cleidigh** [comment]
@rebornix 
Just wanted to touch base.
I saw you used an intermediary approach just for the find history.
I wanted to check to see what I could do to help out for the September with these issues.
I would like to "redeem myself" ;-) with some more contribution.
Can you let me know if there is an appropriate area to help?
Cheers

**Comment by rebornix** [comment]
@cleidigh thank you sir for your help ;) I'll take parental leave from next week and be away for about two months, sorry I can't guarantee to be online. Luckily we have quite a few help-wanted issues https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 , you can pick what interests you and once you file PRs, mention bot can find appropriate reviewers, have fun!

**Comment by cleidigh** [comment]
@rebornix 
That's fantastic !! Congratulations !
have a great leave.  Thanks for working with me and sorry for the confusion on the last PR.
I look forward to working with you again when you return.
in the meantime enjoy life with your new arrival :1st_place_medal: 
AllTheBest Christopher

**Comment by cleidigh** [comment]
@alexandrudima 
will you be picking this up while @rebornix is out?
I'd like to continue to help on this issue since I was so deep into it already.
Adding Find Next/Find Previous is still an open issue #29661.  I have code from an intermediary PR 
that addresses this with separate commands parallel to the current implementation and without
the problems I inadvertently introduced attempting to use a global service/commands.
This does not address either the later issues you identified or the re- factoring.

Has anyone decided the next steps on this?  I will sign up to help if it makes sense.  Trying to flesh out
what I will I help out on next.

**Comment by cleidigh** [comment]
@alexandrudima 
Would you like me to submit the partial prior PR to address #29661 ?

**Comment by rebornix** [comment]
Close it for now as we don't have plans for this task at this moment.
