### ISSUE TITLE
Feature Request: Open next file with problems

### ISSUE THREAD

**Issue by pzuraq** [Microsoft/vscode#32249]
The problems panel is incredibly helpful, especially when used with linters on large projects during refactors. However, it would be really helpful if there was a command that would allow you to open the next unopened file that has problems. This would allow users to quickly track down and remove errors during large code shifts.

**Comment by sandy081** [comment]
Not sure how much helpful it is to have it in core. Probably an extension can contribute this command.

**Comment by pzuraq** [comment]
It's not actually possible to do this in an extension, I tried. The MarkerService is not accessible through any API.

**Comment by sandy081** [comment]
@pzuraq Yes you are right, API does not support getting all diagnostics / markers. Reopening it.

**Comment by sandy081** [comment]
Duplicate of #32159
