### ISSUE TITLE
How to debug javascript code on VS Code Terminal?

### ISSUE THREAD

**Issue by ezequias** [Microsoft/vscode#32240]
Hi

I just made a code and I am trying to debug it using Visual Studio Code (using it's Terminal).

I have no problem to debug my javascript code but the issue is that I am passing parameters via console.

Here is a sample of it: ` C:\projs\myProject> node app.js arg1 arg2 arg3`

**Comment by weinand** [comment]
- Click on the debug icon on the left and VS Code switches to the debug viewlet.
- click on the gear icon at the top left. The `launch.json` is opened in the editor.
- replace the contents of the file with this: 
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch app.js",
			"program": "${workspaceRoot}/app.js",
			"stopOnEntry": true,
			"args": [
				"arg1", "arg2", "arg3"
			]
		}
	]
}
```
- change the command line arguments in "args" to what you need
- press F5 and debugging should stop at the beginning of your program
- step through your code

If your program reads from stdin, please add a "console" attribute to the launch config:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch app.js",
			"program": "${workspaceRoot}/app.js",
			"stopOnEntry": true,
			"args": [
				"arg1", "arg2", "arg3"
			],
			"console": "integratedTerminal"
		}
	]
}
```

**Comment by ezequias** [comment]
Thank you @weinand but I think my doubt was misunderstood.

I don't want to have fixed parameters in any config file. I just would like to start debugging and than open the Terminal and execute my command. After that I would like VSCode could reach my code at a specific breakpoint.

I hope I made myself much more clear now.

**Comment by weinand** [comment]
With node debugging it is impossible to start debugging before node runs in debug mode.
So, first you have to start your program in debug mode and then you can attach the debugger.

To do this in VS Code use this launch config:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to app.js",
			"port": "5858"
		}
	]
}
```

Then start your program in debug mode in the Terminal (any terminal):
```
node --debug-brk app.js arg1 arg2 arg3
```
Your program will wait for the debugger to attach.

Then press F5 to attach the debugger.

**Comment by ezequias** [comment]
Sorry to be so insistent.

Now I am having this message(using the last configuration you sent):
![image](https://user-images.githubusercontent.com/539561/29187299-956e5708-7de5-11e7-97ed-0225135b8ae9.png)

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by ezequias** [comment]
v4.6.0 @weinand

**Comment by weinand** [comment]
[Oops, that's a rather old version (with lots of security problems). If you are not relying on such an old version I would recommend to use the current 6.11.2 LTS.]

And you did start your node program first and then pressed F5 to attach the debugger (and not the other way around)?

**Comment by ezequias** [comment]
I can't start node program `node app.js` because my app.js is not a service.  It is just a code I would like to test. I'm not sure if it is possible indeed.

What I was trying to do is to run debug (F5) with a breakpoint right at first line of code.

But it does not work @weinand 🙁

**Comment by weinand** [comment]
I do not understand what you mean by "I can't start node program node app.js because my app.js is not a service."? That makes no sense to me.

Please just run this in a terminal:
```js
node --debug-brk app.js arg1 arg2 arg3
```

And then press run the "attach" config:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to app.js",
			"port": "5858"
		}
	]
}
```

The port is the **debug port**, it has nothing to do with your program or the fact that it is a service or not.

**Comment by ezequias** [comment]
Now it worked. Many thanks @weinand ✌😁

**Comment by weinand** [comment]
Great! Glad that I could help.

**Comment by ezequias** [comment]
I just updated node to the version you recommended. Thank you! @weinand

**Comment by weinand** [comment]
That's good (and much more secure). Happy sailing!
