### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by JasonSunday** [Microsoft/vscode#32248]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
php-intellisense|fel|1.5.0
beautify|Hoo|1.1.1
vscode-angular2-emmet|jak|2.0.3
csharpextensions|jch|1.3.0
angular-essentials|joh|0.2.0
Angular2|joh|2.4.0
pwa-tools|joh|0.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|1.7.2
easy-less|mrc|1.4.5
vscode-scss|mrm|0.6.2
csharp|ms-|1.11.0
debugger-for-chrome|msj|3.1.7
angular2-inline|nat|0.0.17
material-icon-theme|PKi|2.1.0
live-sass|rit|0.3.3
LiveServer|rit|1.6.8
sass-indented|rob|1.4.1
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1. This seems to happen on save when saving.
2.

Reproduces without extensions: No

**Comment by weinand** [comment]
If the problem doesn't occur if all extensions are disabled, then an extension seems to be the culprit and not VS Code. Please try to find the extension my manual bisect.
