### ISSUE TITLE
When restarting VSCode, only one window restored to fullscreen

### ISSUE THREAD

**Issue by SaladFork** [microsoft/vscode#32247]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.6.0

---

Steps to Reproduce:

1. Ensure `window.restoreFullscreen` is set to `true`
2. Open multiple VSCode windows and fullscreen them
3. Restart VSCode
4. Observe only one of the windows is fullscreen; the rest are now windowed.

**Comment by bpasero** [comment]
I verified that we set the fullscreen flag on startup, but somehow only the one window is actually put into fullscreen mode while the other is not. 

I suspect an issue with electron but could not find any reported one. If someone wants to chime in and investigate further, be my guest 👍

**Comment by bpasero** [comment]
This is https://github.com/electron/electron/issues/13077

**Comment by bpasero** [comment]
Closing as this is tracked upstream.
