### ISSUE TITLE
Curly braces for arrow functions are not auto completing/pairing.

### ISSUE THREAD

**Issue by segmentationfaulter** [Microsoft/vscode#3224]
I have VSCode version 0.10.8 running on Ubuntu, the problem I am facing is that while typing a javascript arrow function expression, the pairing curly brace is not auto typed/completed.

**Comment by alexandrudima** [comment]
@segmentationfaulter This also works for me, maybe it was caused by the same vim extension?

![js-arrow-brackets](https://cloud.githubusercontent.com/assets/5047891/13217217/2952de56-d961-11e5-804a-85e67e2add6a.gif)
