### ISSUE TITLE
Update ctrl+left and ctrl+right word boundary commands to be consistent with other platforms

### ISSUE THREAD

**Issue by stringham** [Microsoft/vscode#32246]
In vscode when I navigate with ctrl+left and ctrl+right it stops on either side of word boundary characters rather than going to the beginning/end of each word. This behavior is inconsistent from other platforms. I've checked both sublime text, and chrome. (Even as I type in this submit an issue text box.)

If you have text that looks like:

`this.is.a.test` and navigate with ctrl+left or ctrl+right, in most platforms you get from the beginning to the end with 4 key presses. With vscode it takes 7.

A few gifs to illustrate, pressing ctrl+left to get to the beginning and then ctrl+right to get to the end.:

Sublime Text:
![sublime-word](https://user-images.githubusercontent.com/1206952/29186618-43f20692-7dca-11e7-923d-3708b3da5803.gif)

Chrome:
![chrome-word](https://user-images.githubusercontent.com/1206952/29186623-49bca44c-7dca-11e7-8e51-e15c74a8e21b.gif)

vscode:
![vscode-word](https://user-images.githubusercontent.com/1206952/29186631-4f51e520-7dca-11e7-82a3-7a077c014868.gif)

**Comment by stringham** [comment]
It's probably worthwhile figuring out if we should change this behavior by default.

I saw this relevant article on hackernews today: http://www.niladicpodcast.com/blog/2017/1/whats-the-deal-with-ctrlleft-and-ctrlright/

In the meantime, I've implemented this behavior as an extension: https://marketplace.visualstudio.com/items?itemName=stringham.cursor-move

**Comment by alexandrudima** [comment]
Done via #41199 and #48046
