### ISSUE TITLE
Windows: Emmet suggestions don't appear for snippets

### ISSUE THREAD

**Issue by akabrainstorm** [Microsoft/vscode#32254]
- VSCode Version: 1.15.0
- OS Version: Windows 10 Creators Update

After updating to new version (1.15) emmet doesn't work properly

Steps to Reproduce:
![emmet](https://user-images.githubusercontent.com/27922234/29190118-fac044ce-7e29-11e7-855b-89a0bd8888af.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@akabrainstorm Am not able to repro this. Can you share your settings?

We had seen something similar https://github.com/Microsoft/vscode/issues/31003#issuecomment-316810393 but that was fixed.

![emmet](https://user-images.githubusercontent.com/16890566/29196167-93156008-7de7-11e7-9ad3-42a41370b1c7.gif)

**Comment by kzhui125** [comment]
@ramya-rao-a 
1.15.0 Win10 Code x64
all extensions disabled, all settings commented
![emmet](https://user-images.githubusercontent.com/11925432/29201109-fd073382-7e8d-11e7-96a8-cf865273d2e8.gif)

If I type "l", I only get "lang"
![my](https://user-images.githubusercontent.com/11925432/29201174-9ae15786-7e8e-11e7-8396-8d46987afd56.PNG)

but you get "label", "leg" and so on...
![l](https://user-images.githubusercontent.com/11925432/29201198-bcfe44be-7e8e-11e7-8b3f-69d09e5e9950.jpg)

**Comment by ramya-rao-a** [comment]
@kzhui125 The label, leg etc are emmet snippets and show up when `"emmet.showAbbreviationSuggestions"` is set to `true`. Have you disabled this by any chance?

**Comment by kzhui125** [comment]
@ramya-rao-a  the default "emmet.showAbbreviationSuggestions" setting is true
![1](https://user-images.githubusercontent.com/11925432/29203809-e9cb4b24-7ea5-11e7-8fc5-7821877e75c7.PNG)
![2](https://user-images.githubusercontent.com/11925432/29203845-1a5ae402-7ea6-11e7-8ffb-7fa7393769cb.PNG)

**Comment by ramya-rao-a** [comment]
@kzhui125 

I see your user settings is empty like you said, can you check the workspace settings has not disabled `emmet.showAbbreviationSuggestion` either?

Can you try disabling all extensions and seeing if that makes any changes? You can temporarily do this by running the command "Extensions: Disable all Installed Extensions".

**Comment by kzhui125** [comment]
@ramya-rao-a 
![emmet5](https://user-images.githubusercontent.com/11925432/29204652-e07ea034-7eaa-11e7-94d6-decaebff141a.gif)

**Comment by akabrainstorm** [comment]
I have fresh (1.15.0) installation without any extension and any configuration

Also I noticed this problem only occur inside of closed tags:
![emmettags](https://user-images.githubusercontent.com/27922234/29211695-969e09e0-7eab-11e7-8356-40becf4038f8.gif)

**Comment by akabrainstorm** [comment]
@ramya-rao-a Please have a look

**Comment by ramya-rao-a** [comment]
@akabrainstorm I tried your repro steps, but I still can't repro.

I will need a little more time to get to the bottom of this.

Until then, please try out Insiders build from http://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`

That brings back the feature of having tab expanding emmet abbreviations.

**Comment by ramya-rao-a** [comment]
I can repro!!!!!!

But only on my Windows machine and not my Mac.... this is super weird

@akabrainstorm @kzhui125 You both are on Windows as well.

**Comment by ramya-rao-a** [comment]
Fix is in master and should be available in Monday's Insiders.

**Comment by ramya-rao-a** [comment]
@akabrainstorm @kzhui125 Can you try the latest insiders from https://code.visualstudio.com/insiders ?

The fix is in it.

**Comment by kzhui125** [comment]
@ramya-rao-a Yes, it's fixed in latest insiders, thanks.

**Comment by roblourens** [comment]
I can't repro in stable. But I also can't repro in insiders.
