### ISSUE TITLE
Ability to ignore whitespace within Source Control file compare

### ISSUE THREAD

**Issue by jestersoftware** [Microsoft/vscode#32252]
Add an option when file comparing to **ignore all whitespace**. **ALL** of it. Every last bit of it. Please and thanks!

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
