### ISSUE TITLE
Documentation should be updated for Typings now that TSD is deprecated.

### ISSUE THREAD

**Issue by Elusive138** [Microsoft/vscode#3225]
The VS Code documentation still contains instructions for TSD: https://code.visualstudio.com/Docs/runtimes/nodejs

TSD is now deprecated and listed as such (warning on install) on npm: https://github.com/DefinitelyTyped/tsd/issues/269

Typings is the replacement.

VS Code's documentation probably should probably be updated to reflect this change.

**Comment by jpierson** [comment]
Is there any compatibilities using [typings](https://github.com/typings/typings) instead of _TSD_ with VSCode?

**Comment by egamma** [comment]
I spent some time on this and using 'typings install --ambient xxx' is the backward compatible way to do this.

We should do this change to:
- docs @gregvanl 
- vscode-sample @chrisdias 

moving to vscode-docs.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#181

**Comment by Elusive138** [comment]
Ah, sorry, I missed that there was a docs repo.

**Comment by egamma** [comment]
@Elusive138 no problem the issue is good and found its home eventually :smile:
