### ISSUE TITLE
Visibility of custom view icons should be independent of File Icon Theme option

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#32255]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063

Since 1.15.0 the item icons of custom views disappear if File Icon Theme is set to None. This is a bug in my opinion as custom views don't necessarily have anything to do with files and more critically the icons may carry semantic information that is now lost, making some extensions (including mine, see below) unusable. The extension that provides the view should have the ability to decide whether the view should follow the File Icon Theme option or not. I suggest to revert the relevant change and discuss the intended behaviour before committing to anything.

[![](https://github.com/letmaik/vscode-git-tree-compare/raw/master/screenshots/main.png)](https://github.com/letmaik/vscode-git-tree-compare)

![image](https://user-images.githubusercontent.com/530988/29190260-557b0a66-7e11-11e7-9a56-68c599956388.png)

**Comment by aeschli** [comment]
@joaomoreno It's up to your tree to use file icons (by having a span with the file-icon or folder-icon classes) and to listen to the IWorkbenchThemeService.onDidFileIconThemeChange event.

**Comment by sandy081** [comment]
@letmaik I see your argument. This change was introduced as a bug fix #30333. 
Thinking thoroughly, I feel File icon theme should not impact custom views as not all custom views show file resources.

**Comment by sandy081** [comment]
@egamma Would like to revert the change #30333 due to the argument mentioned in above comment.

**Comment by egamma** [comment]
@sandy081 reverting the change makes sense to me given the above discussion.

**Comment by aeschli** [comment]
Verifed using the https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline extension
