### ISSUE TITLE
Emmet suggestions is not at the top of the suggestion dialog

### ISSUE THREAD

**Issue by pisarivskiy** [Microsoft/vscode#32256]
- VSCode Version: 1.15.0 8b95971d8cccd3afd86b35d4a0e098c189294ff2
- OS Version: macOS Sierra 10.12.5, Windows 10

Fresh installation, without plugins.

Steps to Reproduce:

1. Create .css or .scss file
2. Start typing CSS rule ("w" for width, for example)
3. At the top, you will get "white-space" suggestion.

This also works for the following rules:
h (height) -> height (but Emmet's abbreviation at the third place)
t (top) -> tab-size
l (left) -> left (but Emmet's abbreviation at the ninth place)
tac (text-align: center) -> touch-action
...and much more. 

ttu not working, while tdn works just fine (Emmet's abbreviation at the first place)

Reproduces without extensions: Yes

To avoid this issue in the previous version, I've used these keybinding settings

```
{
        "key": "tab",
        "command": "tab",
        "when": "editorTextFocus && !editorTabMovesFocus"
},
{
        "key": "tab",
        "command": "editor.emmet.action.expandAbbreviation",
        "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus"
}
```
but now I'm getting an error:

"Warn: Running the contributed command:'emmet.expandAbbreviation' failed."

**Comment by ramya-rao-a** [comment]
> emmet css suggestions not always showing on top

The emmet suggestion is sorted alphabetically along with rest of the suggestions that are coming from css and so are showing up as they do. With #29113 we can look into ranking emmet higher.

> "Warn: Running the contributed command:'emmet.expandAbbreviation' failed."

Previously, if tab was bound to emmet and there was no abbreviation to expand, there was a fallback to the normal tab that would add the indent.

In the current implementation, we have removed the default association of tab with emmet along with the said fallback.

Read the [Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) for reasons as to why we went that route.

For your current situation, a quick workaround is to bind some other key (other than tab) to the Emmet expand abbreviation command, and you should be good to go.

To take part in the discussion on wanting the tab back, please participate in #32243
