### ISSUE TITLE
[bug] rapidly using keyboard short cut combines them resulting in strange error message

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#32258]
I came from other editor, and keyboard shortcut is `ctrl+k` for line comment, and `ctrl+shift+k` for undo line comment.

so i tried this:

i hit `ctrl+k` to try and comment, and error message displayed about being a wrong key commands.
i then immediately remembered and hit `ctrl+/` for the line comment, now it says:
- `ctrl+k,ctrl+/` is an invalid key command.

**Comment by rebornix** [comment]
@r3wt what platform you are on?

**Comment by r3wt** [comment]
@rebornix i am on windows 10.

**Comment by kzhui125** [comment]
on windows,
default comment keyboard shortcut:
ctrl + /
or
ctrl +k, ctrl + c

**Comment by r3wt** [comment]
@kzhui125 i know, its some type of timeout issue causing rapid use of keyboard shortcuts to count as one command.

**Comment by alexandrudima** [comment]
@r3wt We ship with a lot of chords keybindings bound to `ctrl+k`. The status bar shows a message when entering a chord. What are exactly your customizations to `keybindings.json` and what would you expect ?
