### ISSUE TITLE
get a black screen

### ISSUE THREAD

**Issue by qzzsunly** [Microsoft/vscode#32268]
- VSCode Version: 1.14.2
- OS Version: win10
[version ](http://i1.bvimg.com/1949/3faed1aee1abd4c8.png)
Steps to Reproduce:

1. start vscode directly and I get a black screen. I can click the menu and then see the menu.
2. reinstall it , the problem also exist.
[black screen](http://i1.bvimg.com/1949/8c909b9f0f1b7a06.png)

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Do you experience this problem with the new version (1.15) as well?

**Comment by qzzsunly** [comment]
1.15 has the save problem, my computer has a high dpi screen(2560x1440)

[1.15](http://i1.bvimg.com/1949/adf2d8ee7c81a478.png)

**Comment by bpasero** [comment]
@qzzsunly is this the 64bit version? Does it reproduce when you run "`code --disable-gpu`" from the command line?

**Comment by qzzsunly** [comment]
@bpasero yeah, it works .thanks

**Comment by nicolasayotte** [comment]
I have the problem too. Putting Code in Zen mode renders correctly (CTRL-K, Z) if that can cue the devs to the problem. code --disable-gpu works even better. :)

**Comment by bpasero** [comment]
Closing, unlikely that we can do anything about it.
