### ISSUE TITLE
Can't attach to node process with debug port 60005

### ISSUE THREAD

**Issue by gordody** [Microsoft/vscode#32262]
- VSCode Version: Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:43:56.658Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
xml|Dot|1.9.2
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
output-colorizer|IBM|0.1.2
vscode-mocha-two|Mys|1.2.1
vscode-docker|Pet|0.0.16
lorem-ipsum|Tyr|1.0.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
vagrant|bbe|0.5.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.3.3
restore-editors|eam|0.2.1
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-projects-plus|fab|1.4.7
file-icons|fil|1.0.4
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
docker-linter|hen|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.15.1
search-node-modules|jas|1.1.1
restructuredtext|lex|35.0.0
vs-cron|mkl|1.5.1
vs-rest-api|mkl|1.18.2
vs-script-commands|mkl|4.14.0
lit-it|moh|1.2.12
createGUID|nwa|0.0.2
proto|pet|0.0.2
vscode-icons|rob|7.12.0
spellchecker|swy|1.2.13
vscode-open-in-github|sys|1.6.0
vscode-js-console-utils|wht|0.7.0

---

Steps to Reproduce:
0. using node 8.1.4 on MacOS X 10.12.5 (Sierra)
1. Run process `node --inspect=60005 <absolute_path_to_your_process>/server.js --port=123456`
2. Try to attach to it using debugger with launch.config:
<pre>
...
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process with fixed Process ID",
            "protocol": "inspector",
            "port": 60005,
            "processId": "<your_process_id>"
        } 
...
</pre>
3. I get the following error:
<pre>
messageService.ts:125 Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).
</pre>

The error should at least have the right port in it.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@gordody your launch config is bogus. Using it results in this error for me:

![2017-08-11_11-34-36](https://user-images.githubusercontent.com/1898161/29208160-3e5d00aa-7e89-11e7-8c82-b0efe6a4c277.png)

If you are not seeing this error, then you are probably not using this launch config.

It does not make sense to use a launch config with a "processId" attribute if you want to attach with a port number. So please remove the "processId" attribute:

```
{
	"type": "node",
	"request": "attach",
	"name": "Attach",
        "protocol": "inspector",
	"port": 60005
}
```

This launch config works fine for me.

**Comment by gordody** [comment]
I had a copy paste error in this one. Sorry. I did have the correct process Id in my launch.config.

**Comment by weinand** [comment]
If you launch node with the debug or inspect flags like this:
```
node --inspect=60005 <absolute_path_to_your_process>/server.js --port=123456
```
then it is wrong to use a process Id!



The process Id should only be used if you have started node **without the debug or inspect flags**. In this case node is not in debug mode and it is not listening on a debug port.
Specifying a process Id allows VS Code to send a special signal to node which brings it to debug mode. But in this case the port is fixed and you have no freedom to change it.

**Comment by gordody** [comment]
Thank you! I was able to attach to my process!

What you describe here was not clear to me from the docs -- this page https://code.visualstudio.com/docs/nodejs/nodejs-debugging tells me that I can attach to a process that not was started in debug mode, however it should explicitly say that it *will not* attach to anything that was started with the `--inspect` flag.

Furthermore the error message has the wrong port number in it that is also confusing:
`...reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).`

In fact, vscode should be able to figure out that I started my process with the --inspect flag and tell me so. :)

In any case, thank you for the help!

**Comment by weinand** [comment]
Yes, I will fix the doc and I will produce an error message if both a port and a processId is specified.

The error message shows the correct port: if attach via processId is used, node uses the default port which is 9229 for the inspect protocol.
