### ISSUE TITLE
Mapping emmet mode to a different emmet mode results in double emmet suggestions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32260]
Use this setting
```
"emmet.includeLanguages": {
	"javascriptreact": "css"
}
```

Below can be see in a jsx file 

![image](https://user-images.githubusercontent.com/16890566/29192379-16152bee-7dd6-11e7-8750-c7fc4a07a0c8.png)

**Comment by ramya-rao-a** [comment]
cc @jens1o 

You want to take this one up?

What's happening is that the emmet completion provider gets registered twice for `javascriptreact` in the above case.

Once because it is one of the default modes, the other because it was mapped to css.

We should be able to dispose the existing completion provider before registering a new completion provider for the same language.

**Comment by jens1o** [comment]
Yeah, I'll take a shot!

**Comment by jens1o** [comment]
@ramya-rao-a Tiny question: It is by design that only one mode will work, but not both?

**Comment by jens1o** [comment]
Can you give me feedback on my attempt? It looks like it fixes this case, but personally, I'm unhappy with the codestyle.
