### ISSUE TITLE
No option to automatically terminate previous task when a new instance of the same task is started

### ISSUE THREAD

**Issue by ishanjain28** [microsoft/vscode#32264]
- VSCode Version:  1.14.2
- OS Version: Windows 10 Creators Update

This is just a suggestion. 

Almost all IDEs allow us to set a 'Single Instance Only' option, When this option is true, And you try to run a task that is already running, It'll kill the running task and then restart it.

VS Code gives an error stating that the task is already running, go to F1->Terminate Task to terminate the task.
This gets really annoying on some machines where to access Function keys, You also need to hold down a separate  "Fn" key. 

My suggestion is to let people specify a `SingleInstanceOnly` option in `tasks.json`, If this option is true, then instead of giving an error to user, It should kill the existing task and restart it. 
And if this option is false, Then just do what it does currently.
Default value should be `false`, So, Only the people who really need this option can set it and others will see the usual behavior 

And, I'd like to work on this, if that's okay. 

Regards 
Ishan

**Comment by dbaeumer** [comment]
@ishanjain28 the request makes sense and PRs are always welcome.

**Comment by ishanjain28** [comment]
@dbaeumer So, I'll start working on it.

**Comment by ishanjain28** [comment]
Hi, @dbaeumer, Submitted a PR to add this feature [here](https://github.com/Microsoft/vscode/pull/32384)

**Comment by alexr00** [comment]
It seems like this should be three options:
- Prompt (current behavior)
- Restart
- Use existing

**Comment by alpalla** [comment]
Hi! I'd be glad to continue working on this from where we left off with [this PR](https://github.com/microsoft/vscode/pull/62538). Let me know if there's anything else I should know.

**Comment by alexr00** [comment]
I think [this comment](https://github.com/microsoft/vscode/pull/62538#issuecomment-540954744) has the most useful and up to date information. To make review easier and faster, I recommend making two PRs, one for `instanceLimit` and one for `instancePolicy` and finishing one before starting the next (assuming you wanted to implement both).

**Comment by Gama11** [comment]
Note: people subscribed to this issue may want to follow #90125 (for `instancePolicy`) instead now, which is the second part required for the behavior originally described here to work. With the `instanceLimit` that has been added, there is still a prompt.
