### ISSUE TITLE
emmet blog wrong words

### ISSUE THREAD

**Issue by zouhangwithsweet** [Microsoft/vscode#32278]
![image](https://user-images.githubusercontent.com/21095710/29200574-1fd3f422-7e89-11e7-83a1-a44b1fa8418a.png)

`editor.action.emmet.expandAbbreviation` should be 
`editor.emmet.action.expandAbbreviation`

**Comment by ramya-rao-a** [comment]
Thanks for the pointing this out @zouhangwithsweet!

Fixed with https://github.com/Microsoft/vscode-docs/commit/667f9c8c24e8de4ea6daf7f052ac941ff5dd3ea5

@gregvanl Can you update the website?

**Comment by ramya-rao-a** [comment]
The website has been updated
