### ISSUE TITLE
The incorrect IME position when the first character is entered

### ISSUE THREAD

**Issue by imeoer** [Microsoft/vscode#32275]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.1.0
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.2
go|Twe|0.0.1
html-css-class-completion|Zig|1.8.0
vscode-color|ans|0.4.5
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|4.3.3
vscode-html-css|ecm|0.1.7
tslint|eg2|0.17.0
nim|kos|0.5.26
Go|luk|0.6.63
markdown-shortcuts|mdi|0.8.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.7
color-highlight|nau|2.3.0
vetur|oct|0.9.3
proto|pet|0.0.2
Ruby|reb|0.13.0
PostCSS|ric|1.0.1
stylelint|shi|0.28.0
babelrc|wad|1.0.0
vscode-import-cost|wix|2.0.0
vscode-proto3|zxh|0.1.2

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Switch to Chinese IME (e.g. Sougou / Baidu)
2. See the screenshot:

![ime-issue](https://user-images.githubusercontent.com/1524576/29199567-a3d12dc4-7e13-11e7-8010-83864223b644.gif)

I reproduced this problem in the [monaco editor](https://microsoft.github.io/monaco-editor/), I think it should be the text input implementation issue using textarea, did not find this problem in [ace editor](https://ace.c9.io/).

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/356 , let's track it there.
