### ISSUE TITLE
The terminal.integrated.env.<platform> doesn't support the variables like ${workspaceRoot}

### ISSUE THREAD

**Issue by ansencumt** [Microsoft/vscode#32273]
- VSCode Version: 1.5.0
- OS Version: windows 10

Steps to Reproduce:

1.Set the configuration  terminal.integrated.env.windows : {E:\\golang\\golibs;D:\\golang\\path;${workspaceRoot}}

2. Open the terminal and check the golang env:
![image](https://user-images.githubusercontent.com/5181385/29199511-2a4d74cc-7e80-11e7-99c7-65d795b9cf8a.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34337
