### ISSUE TITLE
osx - git crash and create some unknown git track on failed checkout

### ISSUE THREAD

**Issue by sj82516** [Microsoft/vscode#32271]
- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6
- Git Version: 2.12.2

I am using vscode intergrated terminal to run git instructions.
Steps to Reproduce: It happens occasionally.
Here is all I did
1. `git add .` The terminal hang for a long time and I closed it.
2.  reopen terminal, try to `git add .` again but throw some error "git .... index.lock". 
3. I manually remove index.lock file and `git add .` again. It works.
4. Now I was in feature-branch. run `git commit .`. 
5. I would like to change to master branch. run `git checkout master`. The terminal hang again.
6. I restart vscode IDE 
7. The git tree is not I expected. Here is the picture
![Imgur](http://i.imgur.com/06dBO28.jpg)  

The refund-page is my feature branch. The files I commit on refund-page is preserved.
However, the git tree checkout to an unknown branch. 
The data of unknown branch is the same as master so my files on refund-page is disappeared.

Currently my solution is to rebase and checkout again.
But this happen twice in a day!

My current git tree is really small, around 10 branch and 15 commits.

I am not pretty sure this issue is about git / zsh or vscode ?
I hope I am not report to the wrong place.

Thanks

**Comment by joaomoreno** [comment]
> `git add .` The terminal hang for a long time and I closed it.

You shouldn't have done that. You killed the `git` process.

> reopen terminal, try to `git add .` again but throw some error "git .... index.lock".

That's exactly what happens when you kill `git` halfway it's done.

I suggest you have patience and wait for the git commands to complete.

Try to do the same in the Terminal. You'll see exactly the same behavior.
