### ISSUE TITLE
autoGuessEncoding Cannot recognize Chinese code automatically

### ISSUE THREAD

**Issue by littleShy** [Microsoft/vscode#32274]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
copy-markdown-as-html|jer|1.0.0
cpptools|ms-|0.12.2

---

Steps to Reproduce:

autoGuessEncoding  cann't recognize GBK /GB2312/GB18030, i only can modify it manually

1. change file.autoGuessEncoding to true. 
2. open a gbk file, but it opened iwth utf-8, not gbk.

**Comment by weinand** [comment]
most likely a dup of https://github.com/Microsoft/vscode/issues/24195
