### ISSUE TITLE
Should trees be focused on tab?

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#32270]
Steps to reproduce (In stable):
1. `cmd + p` quick pick
2. Focus first item (down arrow)
3. Press `tab` . The whole tree is selected. Another tab to get to the actionbar item.

I feel like it should only be one tab to get to the action item once an entry is focused. Is there any reason why the whole tree is focusable in quick pick? I checked narrator and nvda and they don't seem to read out the tree.

We changed it to not be focusable here: 
https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L448

Is there a reason why the index needs to be 0?

**Comment by joaomoreno** [comment]
Trees are widgets, they require focus. This should be the default behavior.

Quick pick is another widget. Its implementation requires an input box and a tree. When quick open has focus, the input box has focus and any some keys like <kbd>Up</kbd> and <kbd>Down</kbd> are interpreted as tree methods. It doesn't make sense that the specific tree instance inside quick open would ever have focus.

So, I see a use case for having a tree which doesn't ever catch focus. But the default isn't that case.
