### ISSUE TITLE
The comment shortcut key "ctrl+/" cannot be used

### ISSUE THREAD

**Issue by flyingpig2016** [Microsoft/vscode#32272]
#- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.The comment shortcut key "ctrl+/" cannot be used
2.The comment shortcut key "ctrl+/" cannot be used

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@flyingpig2016 do you have any extension installed which might change the behavior of ctrl+/? What language you are working on? Please provide reproduce steps.
