### ISSUE TITLE
shift+tab not work

### ISSUE THREAD

**Issue by MunNaaS** [Microsoft/vscode#32280]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.10.0-30-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
atom-keybindings|ms-|3.0.1

(2 theme extensions excluded)

---
I've been experiencing this problem since version 1.14.2, and I've also encountered this problem with atom editor. I think that would be a problem to the electron but I was not sure so I decided to report a problem with the way vscode, which is where I first encountered this problem.

Steps to Reproduce:

1. shift+tab for outdent

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Do we correctly receive `shift+tab` ?

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by MunNaaS** [comment]
![vscode-shift-tab-issure](https://user-images.githubusercontent.com/29003348/29218212-3d07700a-7ede-11e7-9f2f-9d6befa1e0cc.gif)

Last scene I tried to press shift+tab

**Comment by alexandrudima** [comment]
@MunNaaS Are you perhaps connecting to the linux machine through remote desktoping software?

Here's a good place to troubleshoot issues: https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

**Comment by martinsuchan** [comment]
Same here, Shift+Tab does not outdent. Tested in *.ps1 files. No idea if this has worked in previous versions, just noticed it now.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 
Kotlin|mat|1.3.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
java|red|0.11.0

**Comment by alexandrudima** [comment]
@MunNaaS For you unindenting does not work because it appears we are not receiving `shift+tab`.

@martinsuchan You would like something different. You would like for unindenting to occur within a line and not just at the start of the line. I have extracted that to #36809
