### ISSUE TITLE
Emmet: compact boolean attributes won't work

### ISSUE THREAD

**Issue by noinkling** [Microsoft/vscode#32282]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
vscode-color|ans|0.4.5
vscode-simpler-icons|dav|1.3.0
githistory|don|0.2.3
pgsql|dou|0.0.8
vscode-babel-coloring|dza|0.0.4
vscode-great-icons|emm|2.1.14
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
RelativePath|jak|1.0.0
sublime-babel-vscode|jos|0.2.6
sublime-keybindings|ms-|2.9.1
material-icon-theme|PKi|2.1.0
vscode-css-peek|pra|1.3.1
seti-icons|qin|0.1.3
quokka-vscode|Wal|1.0.48

(3 theme extensions excluded)

---

Emmet has a `profile.allowCompactBoolean` preference [shown here](https://docs.emmet.io/customization/preferences/) that defaults to `true`. For some reason it's not documented in the [syntax profile options](https://docs.emmet.io/customization/syntax-profiles/#create-your-own-profile), but in the code the functionality [seems to also rely on a `compact_bool` flag being set on the profile](https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/assets/profile.js#L153), which [should be `true` by default for HTML](https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/assets/profile.js#L187), and [`false` by default for other profiles](https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/assets/profile.js#L54).

I can't seem to find a way to make this work in VS Code, it will always use the attribute name as the value. I've tried in both HTML and JSX.

Steps to Reproduce:

1. In an HTML file or similar type `div[contenteditable]` or `div[whatever.]` and expand with Emmet
2. Observe that the output is `<div contenteditable="contenteditable"></div>` or `<div whatever="whatever"></div>`
3. Set `emmet.syntaxProfiles` to:

```json
{
  "html": {
    "compact_bool": true
  }
}
```

4. Try again, no luck.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@sergeche Is this feature available in Emmet 2.0?

**Comment by sergeche** [comment]
It’s called `compactBooleanAttributes` now: https://github.com/emmetio/output-profile/blob/master/defaults.js#L60

**Comment by noinkling** [comment]
@sergeche That works, thanks!

Have all the profile options been renamed then? It's a bit confusing because the [Emmet 2.0 blog post](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) still references the documentation with the old names and gives an example using `attr_quotes` and `self_closing_tag`, which still seem to work (along with their new names).

**Comment by sergeche** [comment]
@noinkling yes, almost everything was changed in Emmet 2.0. The purpose of these changes is to create a unified UI for tweaking Emmet per user/project basis, e.g. in future, somewhere on emmet.io you’ll have a UI for quick tuning your Emmet instance

**Comment by noinkling** [comment]
Sounds great 👍 

If the other old option names still work, maybe `compact_bool` should as well, just to be consistent?

**Comment by sergeche** [comment]
A better solution is to provide import from v1 to v2 that will automatically update old configs to new format

**Comment by ramya-rao-a** [comment]
Thanks @sergeche!

@noinkling Yes, to keep people's existing profile settings working, I internally mapped the old names to the new names, and any that I didn't have a mapping for, I pass it right along.

But looks like I have missed a few.

Will use this issue to add mapping for the rest of them.

**Comment by ramya-rao-a** [comment]
Since I didn't find `compact_bool` in the documentation for syntax profiles, I was not aware that it exists!

Right now I map the below
- tag_case
- atrr_case
- attr_quotes
- tag_nl
- inline_break
- self_closing_tag

@sergeche Apart from compact_bool, is there anything else I am missing that users might have had before?

**Comment by ramya-rao-a** [comment]
Added support to map `compact_bool` to `compactBooleanAttributes` with https://github.com/Microsoft/vscode-emmet-helper/commit/52e1d6f6568bdf532b5159fa3cf83c74cfaec0d7
