### ISSUE TITLE
New emmet doesn't work in sass files

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32281]
Emmet works as expected in css,less,scss files, but not sass files.

Root cause: 

https://github.com/emmetio/css-parser is used to parse the file.
For sass files, this doesn't work and the current node turns out to be null which gets invalidated at https://github.com/Microsoft/vscode/blob/release/1.15/extensions/emmet/src/abbreviationActions.ts#L161

**Comment by ramya-rao-a** [comment]
Until there is module that supports parsing sass files, we can skip the check based on cursor location for sass files

**Comment by roblourens** [comment]
Verified that emmet doesn't show up for sass files, if that's the right thing to check.

**Comment by ramya-rao-a** [comment]
@roblourens 

You need the Sass extension for VS Code to identify the sass file type
https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented

Once that is installed, you can then use emmet

**Comment by roblourens** [comment]
I see, I thought this was removing emmet support. I verify that it works with the extension installed.
