### ISSUE TITLE
Why remove open in terminal(ctrl+shift+c) button from right menu?

### ISSUE THREAD

**Issue by BrillanceZhang** [Microsoft/vscode#32287]
- VSCode Version:1.15.0
- OS Version:Windows 7

Steps to Reproduce:
Why remove open in terminal(ctrl+shift+c) button from right menu? I feel so uncomfortable!
1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
It wasn't removed, it will just open in the integrated terminal by default now.

You can change it back to the previous behavior by adding this to your settings.json:

```js
"terminal.explorerKind": "external"
```

**Comment by BrillanceZhang** [comment]
Wow! This is a perfect solution to my problem, thanks a lot~
