### ISSUE TITLE
Warning in folder settings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32289]
Steps to Reproduce:

1. be in a multi folder workspace
2. open folder settings of one folder

=> notice a warning showing up

![image](https://user-images.githubusercontent.com/900690/29204269-4ad48d98-7e76-11e7-8f68-c6df67dce117.png)

**Comment by sandy081** [comment]
@bpasero I do not see this warning. Do you have an extension causing this?

**Comment by bpasero** [comment]
I am also no longer seeing this.
