### ISSUE TITLE
tsconfig baseUrl in angular app not working

### ISSUE THREAD

**Issue by yokots** [Microsoft/vscode#32284]
# tsconfig baseUrl in angular app not working. 

- VSCode Version: 1.15.0
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. The tsdk version is 2.4.2.
2. The app is created by angular-cli, the src/tsconfig.app.json extend rootDirectory/tsconfig.json.
3. The src/tsconfig.app.json configure baseUrl with './'. 
4. There are two ts files, src/environments/environment.ts and src/app/test.ts
5. In src/app/test.ts, Import { environments } from 'environments/environment', and it show cannot find module 'environments/environment'. but it can be compiled successfully.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
We currently only pick up a config file if it is named `tsconfig.json` files. The `tsconfig.app.json` project file is probably not being recognized at all in this case. Can you try renaming the file to `tsconfig.json` or creating an empty `tsconfig.json` that [`extends`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) `tsconfig.app.json`

We are tracking support for specifying `tsconfig` files explicitly with #12463
