### ISSUE TITLE
Executing a task: Cannot find module 'semver'

### ISSUE THREAD

**Issue by screendriver** [Microsoft/vscode#32286]
- VSCode Version: 1.15.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. I created following scripts in my `package.json`: 

```json
"scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch"
},
```
2. my `tasks.json` looks like this:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "build:watch",
      "problemMatcher": ["$tsc-watch"]
    }
  ]
}
```
3. when I execute this tasks I get following error

```sh
> Executing task: npm run build <

module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
The terminal process terminated with exit code: 1
```

4. I also can't execute the `build` script

5. my `package.json` is really simple at the moment

```json
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch"
  },
  "devDependencies": {
    "@types/node": "^8.0.20",
    "typescript": "^2.4.2"
  },
  "dependencies": {}
}
```

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
The exception is thrown from the npm module `/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14`. What happens when you execute this directly from the integrated terminal (e.g. npm run build or npm run build:watch)

**Comment by screendriver** [comment]
> What happens when you execute this directly from the integrated terminal (e.g. npm run build or npm run build:watch)

Then it works. At the moment I am doing this all the time.

**Comment by dbaeumer** [comment]
Can you provide me with a GitHub repository I can clone that demonstrates this. I can't reproduce it.

**Comment by screendriver** [comment]
[Sure](https://github.com/screendriver/vscode-task-fail) You will be surprised how simple this project is 😁

**Comment by jbenoit2011** [comment]
I encountered the same problem. Now it is working, here is what I did:
1. Upgrade node version (managed through NVM) and NPM
2. Remove `/usr/local/lib/node_modules` dir to delete all global packages
3. Remove previous `tslint` installation from `yarn`
4. Reinstall global packages (In my case: `npm install typescript mocha nyc tslint`

And it worked. I think, the step 3 really helped to solve the case.

**Comment by screendriver** [comment]
Hmm you are right. On my second machine it does work 🤔 So anything on my first machine is different.

What is really strange: what is the relationship between a **local** task run and a globally installed npm package?

**Comment by jbenoit2011** [comment]
The shell context and its environment variables?

**Comment by screendriver** [comment]
Both machines has nearly exact the same installation. But I get it to work:

> 2. Remove /usr/local/lib/node_modules dir to delete all global packages

did it in my case 😉

**Comment by dbaeumer** [comment]
@jbenoit2011 thanks for jumping in and provided a resolution for this.

**Comment by screendriver** [comment]
Maybe this one should be documented somewhere. I could imagine that I am not the only one with that issue.
