### ISSUE TITLE
Function keys don't work in terminal in WSL

### ISSUE THREAD

**Issue by traversc** [Microsoft/vscode#32285]
- VSCode Version:  1.15.0
- OS Version: Windows 10

Settings:

```
{
    "terminal.integrated.commandsToSkipShell": []
}
```

Extensions: none

Steps to Reproduce:

1. Open a new terminal
2. Load bash
3. Press any function key F1-F12

A tilde is inserted rather than passing the function key to the terminal.  

Edit: I found a previous workaround based on a similar issue, suggesting to use wsltty, but it doesn't work perfectly either.  https://github.com/Microsoft/vscode/issues/10163

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
