### ISSUE TITLE
"json.format.enable" is invalid.

### ISSUE THREAD

**Issue by cdoco** [Microsoft/vscode#32288]
- VSCode Version: 1.15.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. I set my `settings.json`:

```json
{
    "json.format.enable": false
}
```

2. It is invalid.

![image](https://user-images.githubusercontent.com/8597204/29204018-fd3cbb38-7ea6-11e7-93ae-f7258c6df6b5.png)

Reproduces without extensions: No

**Comment by weinand** [comment]
I do not understand what you mean by "It is invalid"?

**Comment by cdoco** [comment]
I don't want to use json format, But I set the `json.format.enable": "false"`, It has no work, json is still formatted.

**Comment by weinand** [comment]
Setting the `json.format.enable` to false prevents any new formatting, but it does not undo the existing formatting in any way. 
So, this works as designed.
