### ISSUE TITLE
Color picker: top right corner is not clear to me

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32297]
It seems the top-right corner shows the color I had in the beginning, if so, we should:
* allow to restore it when I click it
* maybe show a description or make it otherwise more clear that this was the original color

Otherwise it looks like a UX bug where we fail to update parts of the box with the selected color

![image](https://user-images.githubusercontent.com/900690/29206804-d6015c54-7e83-11e7-8699-cd323f6c08ad.png)

**Comment by joaomoreno** [comment]
#31640
