### ISSUE TITLE
i can't use 'tab' to fast create tag.

### ISSUE THREAD

**Issue by zzzzzyb** [Microsoft/vscode#32290]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.2.11
python|don|0.7.0
mithril-emmet|Fal|0.6.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-autoprefixer|mrm|2.1.2
debugger-for-chrome|msj|3.1.7
vetur|oct|0.9.3
JavaScriptSnippets|xab|1.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by zzzzzyb** [comment]
when vscode update something today

**Comment by kovacevjosip** [comment]
Actually it works only if Emmet Abbreviation is displayed.
![image](https://user-images.githubusercontent.com/14251756/29204632-754d67b4-7e78-11e7-9175-0b4021387098.png)

But if you use ESC key on keyboard or if you click with mouse somewhere else and get back to that line,
Emmet Abbreviation is not displayed so tab won't create tag.
![screenshot from 2017-08-11 09-34-23](https://user-images.githubusercontent.com/14251756/29204701-d7f663de-7e78-11e7-9299-52902f89c539.png)

**Comment by zzzzzyb** [comment]
tks @kovacevjosip
