### ISSUE TITLE
体验建议

### ISSUE THREAD

**Issue by YSHIDM** [Microsoft/vscode#32299]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.希望git文件对比能以树状结构展示；

2.文档结构功能不怎么用，怎么关闭？

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@YSHIDM If your native language isn't English, may I suggest that you use a translation tool to translate your language to English. This save us a bit of time. Thanks.

Translation:
Experience advice
1. Hope git file comparison can be displayed in a tree structure
2. Document structure function is not how to use, how closed?

**Comment by weinand** [comment]
@YSHIDM I do not understand what you mean with the second question.

**Comment by CnSimonChan** [comment]
@weinand The second question is "I don't use the document structure feature much, how to turn it off?"

But I also have no idea what's the "document structure feature" is, maybe he is referring the minimap?

@YSHIDM  文档结构功能是指编辑器右侧的微缩图？如果是的话可以在设置中添加 "editor.minimap.enabled": false 来关闭。如果不是请说明。

**Comment by joaomoreno** [comment]
First question: `"editor.minimap.enabled": false`

Second question: #14582
