### ISSUE TITLE
Color Picker: Integrate inline color boxes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#32295]
Currently, languages are forced to create decorations in order to have those inline color boxes.

With the new color API, the core should be doing this for them.

**Comment by kobenauf** [comment]
I agree.  For example doing a project with material-ui, the style is in the javascript:
```const styleSheet = createStyleSheet({
  App: {
    backgroundColor: '#F0E1D2',
    height: '100%'
  }
})```
It would be very helpful to have some way of invoking the color picker for `backgroundColor` above.
