### ISSUE TITLE
[json] hover over color box doesn't show color picker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32298]
It seems I am not presented with the color picker when I hover over colors inside settings (e.g. `workbench.colorCustomizations`). 

![image](https://user-images.githubusercontent.com/900690/29206840-01968be6-7e84-11e7-83f3-f8ecf0801185.png)

**Comment by aeschli** [comment]
Are you on the final 1.15 or latest insiders?
![image](https://user-images.githubusercontent.com/6461412/29208596-fa31c468-7e8a-11e7-8c89-a04a9b333143.png)

**Comment by bpasero** [comment]
@aeschli this is running from sources, I do not see this hover.

**Comment by bpasero** [comment]
![panel-red](https://user-images.githubusercontent.com/900690/29214065-2dcd7fa4-7ea6-11e7-8980-23ab4b0fc366.gif)

Looks like an exception is logged:

```
Illegal argument: range: Error: Illegal argument: range
    at Object.illegalArgument (/Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/errors.js:161:20)
    at new ColorInfo (/Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/node/extHostTypes.js:978:32)
    at ColorProvider.<anonymous> (/Users/bpasero/Development/Microsoft/monaco/extensions/json/client/out/colorDecorators.js:181:45)
    at step (/Users/bpasero/Development/Microsoft/monaco/extensions/json/client/out/colorDecorators.js:36:23)
    at Object.f [as next] (/Users/bpasero/Development/Microsoft/monaco/extensions/json/client/out/colorDecorators.js:17:53)
    at fulfilled (/Users/bpasero/Development/Microsoft/monaco/extensions/json/client/out/colorDecorators.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by aeschli** [comment]
@bpasero Can you attach the full file content?

**Comment by bpasero** [comment]
@aeschli here:

```json
{
    "window.zoomLevel": 1,
    "files.autoSave": "off",
    "explorer.openEditors.visible": 9,
    "workbench.editor.enablePreview": false,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "debug.inlineValues": true,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "editor.minimap.enabled": false,
    "editor.renderIndentGuides": false,
    "editor.dragAndDrop": false,
    "search.quickOpen.includeSymbols": false,
    "workbench.startupEditor": "newUntitledFile",
    "window.restoreWindows": "all",
    "window.restoreFullscreen": true,
    "workbench.activityBar.visible": true,
    "workbench.colorCustomizations": {
        "statusBar.background": "#adadad"
    }
}
```

**Comment by aditp91** [comment]
I'm not even able to get the hover on json files. It works on others like js, css, etc. Anyone else having this issue?

**Comment by aeschli** [comment]
@bpasero Still can't reproduce, also not with your content. Can you enable:
`"css.trace.server": "verbose"` and see what ranges are returned for colors?
Or I'll debug it on your machine next week.

**Comment by bpasero** [comment]
@aeschli I can reproduce even with a simple example of just opening the settings file directly (in this case a settings.json file within a workspace).

![image](https://user-images.githubusercontent.com/900690/29221708-0ad32b92-7ec0-11e7-8469-c19ef0467c22.png)

Not seeing any output, where should I look at?

Btw the exception could be a red herring, now I am not seeing the exception anymore but I still do not get the color picker.

**Comment by aeschli** [comment]
@aditp91 Please file a separate issue...

**Comment by bpasero** [comment]
@aeschli I know what is different, in JSON I need to hover over the value, I cannot hover over the color box. The hover works fine once I hover over the string value of the color.
