### ISSUE TITLE
dotnet project build output chinese mess code

### ISSUE THREAD

**Issue by junjiangao** [Microsoft/vscode#32292]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.0
---

Steps to Reproduce:

1.dotnet new console
2. just run f5，task ouput like this
![2](https://user-images.githubusercontent.com/7577432/29204095-964adc60-7ea7-11e7-96a2-620307d35ede.PNG)
3. change code Console.WriteLine("**中文**123");
![3](https://user-images.githubusercontent.com/7577432/29204130-cfed89f4-7ea7-11e7-8005-86433ace11fb.PNG)
4.run above in the cmd.exe
![4](https://user-images.githubusercontent.com/7577432/29204191-2760b0f8-7ea8-11e7-8fce-b0e40a438362.PNG)
![5](https://user-images.githubusercontent.com/7577432/29204198-2e352972-7ea8-11e7-87cc-0de2f5ed3501.PNG)

`dotnet --info` output:
![1](https://user-images.githubusercontent.com/7577432/29204042-2db05aa4-7ea7-11e7-92b9-d96ebc0441d1.PNG)

Reproduces without extensions: No

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1701
