### ISSUE TITLE
Unhandled exception during update. (1.14.0 -> 1.15.0)

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#32293]
I just updated to the latest vscode. Everything is working fine, but I got an exception right after the update.

Please help me find out if it is a bug of an extension. I am not sure.

- VSCode Version: 1.14.0 -> 1.15.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Update vscode to version: 1.15.0

![image](https://user-images.githubusercontent.com/11232402/29205613-aee2cc36-7e86-11e7-9891-c7e72049527c.png)

![screenshot_2](https://user-images.githubusercontent.com/11232402/29205641-db2e4824-7e86-11e7-9fac-6c500be5ca20.png)

**Comment by joaomoreno** [comment]
Strange. Are you in a good state now? Does Code work fine?

**Comment by cprogrammer1994** [comment]
Code works fine. Cannot reproduce the error on my other machines.

**Comment by cprogrammer1994** [comment]
Are the files from the stack trace part of the vscode? or they are part of an extension?

**Comment by joaomoreno** [comment]
Glad it works fine. :+1:
