### ISSUE TITLE
    Team 00 关闭 错误command 'team.Signin' not found

### ISSUE THREAD

**Issue by tatgck** [Microsoft/vscode#32301]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.1.7
code-runner|for|0.6.33
csharp|ms-|1.12.0
team|ms-|1.121.1
debugger-for-chrome|msj|3.1.7
vscode-icons|rob|7.12.0
vscode-extjs|Sen|1.0.1

---

Steps to Reproduce:

1.设置tfvc："tfvc.location": "C:\\Program Files (x86)\\TEE-CLC-14.114.0\\TEE-CLC-14.114.0\\tf\\" 
2.打开Visual Studio Team Services Extension for Visual Studio Code
3.输入：team.Signin 
4.报错：command 'team.Signin' not found

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vsts-vscode#301
