### ISSUE TITLE
The VCS tab only shows changes for first folder in workspace

### ISSUE THREAD

**Issue by asux** [Microsoft/vscode#32307]
- VSCode Version: Code - Insiders 1.15.0-insider (dc3a6df693da5ad6e9219cb0269439cc6a8c401a, 2017-08-08T21:45:23.133Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
elixir-ls|Jak|0.0.9
vscode-github|Kni|0.18.1
vscode-docker|Pet|0.0.16
project-manager|ale|0.19.0
rails|bun|0.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
ember-syntax|dhe|0.5.0
githistory|don|0.2.3
gitlens|eam|4.3.3
emberjs|emb|1.0.1
vscode-ember|emb|0.1.0
crystal-lang|fau|0.2.17
git-project-manager|fel|1.3.2
vsc-ember-cli|fel|0.3.3
code-runner|for|0.6.33
sass-lint|gle|0.0.4
docker-linter|hen|0.3.0
elixirlinter|iam|0.4.1
github-pr|jas|1.0.0
ember-related-files|jos|1.1.0
rspec-snippets|kar|0.0.3
ruby-rubocop|mis|0.4.0
vscode-elixir|mjm|0.5.1
EmberES6Snippets|pha|2.1.2
Ruby|reb|0.13.0
vscode-icons|rob|7.12.0
rails-go-to-spec|spo|0.0.1
vscode-open-in-github|ziy|1.2.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open some folder with Git repo
2. Add another folder with Git repo
3. Make change in second folder
4. Open VCS sidebar tab

Expected:
- Changed file appears

Actual:
- No changed files in list

Tried disable Git related extensions and still reproduce.
Screenshots: [Folders](https://cl.ly/lxpZ) & [VCS tab](https://cl.ly/ly0Z).

Reproduces without extensions: No

Can you help me find extension brokes this?

**Comment by joaomoreno** [comment]
This will come with #32234

Multi folder support is still ongoing.
