### ISSUE TITLE
[css] support named grid lines

### ISSUE THREAD

**Issue by Aqours** [Microsoft/vscode#32309]
- VSCode Version: 1.15.0
- OS Version: Windows 10 x64

![qq 20170811183455](https://user-images.githubusercontent.com/8586286/29209963-dc8a4ece-7ec3-11e7-8a35-d3ebba74a37e.png)

Reproduces without extensions: Yes

**Comment by codeofsumit** [comment]
![image](https://user-images.githubusercontent.com/2399810/30684856-20de9c88-9eb3-11e7-99cb-380ca0d330db.png)

experiencing the same

**Comment by zhanba** [comment]
+1
