### ISSUE TITLE
ARM is not included in Electron targets

### ISSUE THREAD

**Issue by headmelted** [Microsoft/vscode#32306]
Currently the targets list does not include ARMv7, even though Electron releases builds for this architecture (and VS Code supports it).  This is fine if building on ARMv7 directly, but inhibits cross-compilation.

https://github.com/Microsoft/vscode/blob/3e27c42d7a832f49e569b9d20d0aeb1911db6b37/build/gulpfile.vscode.js#L171-L173

Suggest adding an electron-arm target to this list.

**Comment by joaomoreno** [comment]
#6442
