### ISSUE TITLE
emmet doesn't recognize some html elelements

### ISSUE THREAD

**Issue by guyvanbael** [Microsoft/vscode#32302]
after the upgrade to vscode 1.15 (and therefore emmet 2.0), some html5 elements are not in the abreviations list. I'm talking about  things like header, nav, footer, aside.
things like div, ul, li, img etc still work.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @guyvanbael 

We are tracking this in https://github.com/Microsoft/vscode-emmet-helper/issues/5.
