### ISSUE TITLE
Emmet doesn`t work in .vue files

### ISSUE THREAD

**Issue by jsteacat** [Microsoft/vscode#32311]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.5
expand-region|let|0.0.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vetur|oct|0.9.3
vscode-html-scss|P-d|0.0.42
LiveServer|rit|1.6.8
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
vue|sea|0.4.2
easysass|spo|0.0.6
language-stylus|sys|1.7.3
jsx|Twe|0.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@jsteacat Have you added the below setting?
```
"emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
}
```

**Comment by lemontree2000** [comment]
@jsteacat 

> An important change is that the Tab key is no longer the dedicated keyboard shortcut for expanding Emmet abbreviations. Instead, Emmet abbreviations will now appear in the suggestion list. They can be selected like any other smart completion and on selection, the abbreviation will be expanded.

> This may take some getting used to but we think you'll see the benefits of Emmet abbreviations being treated as suggestions or smart completions. You can still bind any keyboard shortcut (other than Tab key) to the editor.emmet.action.expandAbbreviation command or use Emmet: Expand Abbreviation from the Command Palette.

The latest version of vs code does not enable the tab shortcut by default，You need to set it up

**Comment by jsteacat** [comment]
@ramya-rao-a 
Thank you so much! It works))
