### ISSUE TITLE
[Microsoft Visual C++ Updates] 2015 and 2005 Redistributable

### ISSUE THREAD

**Issue by marianamoraes** [Microsoft/vscode#32314]
Hello :) My Windows 10 PC is currently requesting updates on Microsoft Visual C++ Redistributables from 2015 and 2005. Where can I download both files for update and why do I need to download two different versions released within 10 years time? Thanks a lot. Best, Mariana.

**Comment by weinand** [comment]
@marianamoraes how is this question related to VS Code?

**Comment by marianamoraes** [comment]
@weinand I'm sorry Andre, I don't know how it is related. I thought I was on Microsoft's service desk. Nonetheless, thanks for your reply. Best, Mariana.

**Comment by weinand** [comment]
No problem.

**Comment by marianamoraes** [comment]
it is not related then? do you work at Microsoft? I solved the problem with the Visual C++ updates, but now I am having problem updating MXSML 4.0... If you'd by any chance know what to do, please let me know. Anyways, have a good weekend xx

**Comment by weinand** [comment]
This issue tracking system is for the Microsoft product "Visual Studio Code".
Are you using "Visual Studio Code"?
