### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#32317]
- VSCode Version: Code 1.15.0

Плагин emmet для некоторых тэгов html5 не показывает предложения (например, header, nav, footer, canvas).

Для тэгов, которые не входят в состав HTML5 тоже не работают. 
Список тэгов:
- table
- blockquote
- pre
- sup
- sub
- title
- plaintext
- noscript
- legend
- u
- code
- comment
- caption
- colgroup
- button
- big
- applet
- address
- strong
- small

**Comment by guyvanbael** [comment]
That's the same issue as #32302

**Comment by ramya-rao-a** [comment]
Thanks for reporting @opencreative 

We are tracking this in https://github.com/Microsoft/vscode-emmet-helper/issues/5.
