### ISSUE TITLE
[feature reqeust] Use emmet grammar to write json code

### ISSUE THREAD

**Issue by jiming** [Microsoft/vscode#32313]
Since we can use emmet to generate xml/html, it should be easy to generage json as well.

And I believe this could be one killer feature ...

Thanks!

**Comment by sergeche** [comment]
It better to provide some samples of abbreviations and expected output in JSON

**Comment by jiming** [comment]
```
div>ul>li
 --------------------
<div>
    <ul>
        <li></li>
    </ul>
</div>

--------------------
{
  "div": {
    "ul": { "li": "$cursor$" }
  }
}

```

and 


```
div>(p>span)*2
--------------------
<div>
    <p><span></span></p>
    <p><span></span></p>
</div>
--------------------
{
  "div": [
    {p: {span: $cursor$}}
    ,{p: {span: $nextCursor$}}
  ]
}
```

I will try figure some more later

**Comment by sergeche** [comment]
And event in your examples there are inconsistencies: why `li` in first example is a property of `ul` and `p` is a property of standalone object which is an entry of array of `div`? I don’t see actual use case of JSON output here

**Comment by jiming** [comment]
@sergeche 

If with multiply sign, it should be an List, otherwise it should be a key of an Object.

ul.nav>li.item*3>a+b+a  should be look like this, I am not sure how class(.) and id(#) should be process.

{
    "ul" : {
        "li" : [
            {"a": "$cursor$", "b": "$cursor$"}
            , {"a": "$cursor$", "b": "$cursor$"}
            , {"a": "$cursor$", "b": "$cursor$"}
        ]
    }
}

Nowadays, we need writing a lot of json documents, I haven't found a very good editor the fast create json document. As fas as I can think of, emmet is a good idea to start. By using emmet to compose json document, a subset of emmet grammar is enough, no need to implement all of them.

Thanks!

**Comment by sergeche** [comment]
This is not how things should be done. Without a complete specs of how every feature of Emmet abbreviation should be treated and how to output different value types (strings, numbers, booleans, null) I woudn’t personally spend my time on it. Providing inconsistent results would do more harm than good

**Comment by jiming** [comment]
@sergeche 

Thank you for your reply. I agree with you. Let me close this for now.

Have a nice day!
