### ISSUE TITLE
Javascript syntax highlighting fails with ES6 arrow functions with arguments split over multiple lines, if arguments contain default array or string

### ISSUE THREAD

**Issue by bjeanes** [Microsoft/vscode#32310]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
Ionide-fsharp|Ion|2.32.0
vscode-docker|Pet|0.0.16
html-css-class-completion|Zig|1.8.0
project-manager|ale|0.19.0
vscode-database|baj|1.2.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
pgsql|dou|0.0.8
gitlens|eam|4.3.3
crystal-lang|fau|0.2.17
auto-close-tag|for|0.4.3
haml|kar|0.7.2
comment|kar|4.0.8
Go|luk|0.6.63
vscode-elixir|mjm|0.5.1
debugger-for-chrome|msj|3.1.7
Ruby|reb|0.13.0
RustyCode|sav|0.19.1
vscode-parinfer|sha|0.6.1
vim|vsc|0.9.0
vscode-todo-highlight|way|0.5.8
JavaScriptSnippets|xab|1.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Just paste this code into a new buffer and configure it to be JavaScript:

    ``` javascript
    const fn = ({
      arg = [],
    }) => {
      return "This line should be highlighted correctly";
    }
    ```

2. Compare highlighting between:

    1. Code above _(incorrect highlighting)_:
        ![2017-08-11 at 8 30 pm](https://user-images.githubusercontent.com/2560/29209859-106572cc-7ed4-11e7-9d7e-70139a9526ad.png)

    2. Arguments on single line _(correct highlighting)_:
        ![2017-08-11 at 8 32 pm](https://user-images.githubusercontent.com/2560/29209907-46e9ec2e-7ed4-11e7-8023-f024073a1aab.png)

    3. No `[]` or `"string"` as default argument value _(correct highlighting)_:
        ![2017-08-11 at 8 33 pm](https://user-images.githubusercontent.com/2560/29209918-593792aa-7ed4-11e7-8162-63a5c98f3cac.png)

This example is obviously simplified from where I encountered it. Highlighting resumed midway through my function after a ternary expression (the `:` specifically). I could replicate the behaviour with either a string or array default value (empty or non-empty did not matter).

Reproduces without extensions: *Yes*

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#499
