### ISSUE TITLE
Hangs when deleting an open file in the editor

### ISSUE THREAD

**Issue by Antoxa1081** [Microsoft/vscode#32324]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.19.0
vscode-color|ans|0.4.5
vscode-svgviewer|css|1.4.2
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.2.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
ftp-simple|hum|0.5.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.3
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.7
view-in-browser|qin|0.0.5
code-spell-checker|str|1.3.6
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@Antoxa1081 Please provide detailed steps.
