### ISSUE TITLE
Cannot store or use files stored on OneDrive or OneDrive for business and synced with the new Windows 10 Onedrive sync client in vscode

### ISSUE THREAD

**Issue by RebekkaAalbers** [Microsoft/vscode#32321]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Enterprise Insider Preview, Version 1703, Build 16251.0

Steps to Reproduce:
Scenario save new file to OD or ODFB:
1. Create new file in vscode
2. Enter some code or random text
3. Save file to OneDrive or OneDrive for Business sync location
4. A system error occured

Scenario open file with script or code thats is saved on OD or ODFB:
1. Klik menu File > Open or Ctrl-O
2. Navigate to file location in OneDrive of OneDrive for Business sync location
3. Open file - File is empty
5. Open the same file in Notepad - File contains data

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
