### ISSUE TITLE
Slow to switch to/from tab with large collapsed section

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#32330]
- VSCode Version: Code - Insiders 1.16.0-insider (dc3a6df693da5ad6e9219cb0269439cc6a8c401a, 2017-08-11T07:07:15.518Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. New empty directory
2. `npm install @types/lodash`
3. Create a file `a.ts` containing `_.add(1, 2)`
4. Go to definition on `_` to get taken to `node_modules/@types/lodash/index.d.ts`
5. Collapse the `declare namespace _` section, which spans nearly 20000 lines.
6. Go back to the tab from `a.ts`, then back to `index.d.ts`, repeat. It's noticeably slow. No issue if you uncollapse everything.

**Comment by bpasero** [comment]
I think in this case a CPU profile would help:

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by andy-ms** [comment]
OK, here it is:
[CPU-20170811T083908.zip](https://github.com/Microsoft/vscode/files/1218355/CPU-20170811T083908.zip)

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/29308831-852f27bc-81a7-11e7-840d-086a8f3dd89b.png)

Trace when the the editor that shows `index.d.ts` gets active.
Note how the decoration are all computed in 'setModel', disposed and recomputed again in 'restoreViewState'.

@sandy081 You made these changes in https://github.com/Microsoft/vscode/commit/de731511f57a7b89884a5358970ad5cb2eafafea.
Do you remember why?

**Comment by aeschli** [comment]
@sandy081 I changed the code of restoreViewState to no longer rebuild the folded ranges. Looks like the settings default editor no longer requires that anyway.

**Comment by sandy081** [comment]
@aeschli Yes that was done to restore the folding state of default settings editor which is not the case anymore.

**Comment by rodrigobutta** [comment]
Same problem here. Switching tabs and i think almost everything is having a slow response since a few days ago, My pc has an I7, 12GB RAB and SSD. Windows 10, 64.
