### ISSUE TITLE
Ignore all sessions where Code was opened with a specific file by double-clicking in a file manager or from the command line with file paths

### ISSUE THREAD

**Issue by BobbyBabes** [Microsoft/vscode#32338]
Referring to this QA in issue 207 :
Q: https://github.com/Microsoft/vscode/issues/207#issuecomment-318012379
A: https://github.com/Microsoft/vscode/issues/207#issuecomment-321826340

**My request :**
When starting Code from its icon, or from the command line without file paths as argument : Restore the previous `window.restoreWindows` context, and ignore all sessions where Code was opened with a specific file by double-clicking in a file manager or from the command line with file paths.
Right now, those sessions are not ignored, and replace the last `window.restoreWindows` context.

Situation:
- VSCode Version:
```
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
- OS Version:
```
"uname --all" output:
Linux ladyluck 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux
```

- Reproduces without extensions: Yes

**Steps to Reproduce:**

```
Preferences: `"window.restoreWindows": "all"`
```
`window.restoreWindows` context :
```
One VSC window with a project folder opened. All files saved.
One VSC window with just a bunch of files opened. Some with unsaved changes.
Ctrl+Q to close all VSC windows and quit VSC.
```

1. **Reopening** VSC (as per the title of  issue https://github.com/Microsoft/vscode/issues/207) works as expected. Both windows are restored with all files.
2. Ctrl+Q again.
3. Then double-clicking a source file in the file manager, opens one VSC window with just the double-clicked file.
4. Ctrl+Q again.
5. Start VSC from its icon, and one window opened with just the one file (that was double-clicked from the file manager).
6. I restored the initial 2 windows with Ctrl+N, followed by Open recent.

At step 5, starting VSC from its icon, I had expected that would first open the 2 VSC windows. And that the source file (double clicked from the file manager) would be added to one of the 2 VSC windows. And that that window would be pushed to the foreground.
Similar to what happens now when there are already VSC windows opened, and you then double-click a source file from the file manager.

Adding the double-clicked file manager or command line file(s) to the 2 VSC windows is of course debatable. Some users might want a complete separation between whether Code was already started before the first file was double-clicked, and whether Code was still closed before the first double-click.

**Comment by avently** [comment]
Hate this behaviour too.
This is how we (users) can fix it:
add this line to your ~/.bashrc (or ~/.zshrc):
For Insiders edition:
alias code="code-insiders && code-insiders"

For regular edition:
alias code="code && code"


Copy file(s) Visual Studio Code or/and Visual Studio Code Insiders from /usr/share/applications to ~/.local/share/applications

Edit those files
Change Exec command to:
For Insiders edition:
Exec=sh -c "/usr/bin/code-insiders && /usr/bin/code-insiders %f"

For regular edition:
Exec=sh -c "/usr/bin/code && /usr/bin/code %f"


Done. Now you can open files via file manager and open files via terminal ("code something.txt") and those files will be opened in your current session even if app was closed.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14675
