### ISSUE TITLE
terminal.integrated.rightClickCopyPaste isn't working on x64 build

### ISSUE THREAD

**Issue by nborko** [Microsoft/vscode#32336]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|0.0.2
swagger-viewer|Arj|1.4.0
vscode-eslint|dba|1.2.11
vscode-great-icons|emm|2.1.14
vscode-tfs|iva|0.6.0
sublime-babel-vscode|jos|0.2.6
vscode-csscomb|mrm|5.1.0
vscode-less|mrm|0.6.3
csharp|ms-|1.12.0
vetur|oct|0.9.3
rewrap|stk|1.4.2
highlight-trailing-white-spaces|yba|0.0.2
ActionScript3|yop|0.0.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Enable terminal.integrated.rightClickCopyPaste (seems to be true by default)
2. Select text and right click in the integrated terminal window. Context menu appears.

Reproduces without extensions: Yes

**Comment by markalexandercastillo** [comment]
Also running into this.

VSCode info:
> Version 1.15.0
> Commit 8b95971d8cccd3afd86b35d4a0e098c189294ff2
> Date 2017-08-09T20:09:15.006Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0
> Architecture x64

Same reproduction steps as nborko

**Comment by ihalip** [comment]
Repro'd this. It looks like the `mousedown` event (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L178) is not received when there is text selected in the terminal. It doesn't matter if you right-click inside or outside the selection.

**Comment by Tyriar** [comment]
Thanks for the tip @ihalip. Looks like this line is the problem:

https://github.com/sourcelair/xterm.js/blob/6e9d60d76d6cfb3d279f9e58499ba62ca6af479c/src/SelectionManager.ts#L319
