### ISSUE TITLE
the cursor automatic line feed

### ISSUE THREAD

**Issue by xunzhaoshitouyu** [Microsoft/vscode#32331]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1.Set to open automatically save
2.After writing the JavaScript code on the HTML page, press the Enter key, and after a few seconds, the cursor automatically changes to the end of the script tag
3.When you write code in the JS file, type the space after ‘var’. After a few seconds, the cursor is positioned after ‘var’, and the space is gone

**Comment by mjbvz** [comment]
A few questions:

1. If you disable all extensions, do you still see this issue? Here's how to disable extensions: https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension
1. Can you record a short gif or series of screenshots of the problem.

**Comment by aeschli** [comment]
Also check if you have `"editor.formatOnSave": true` in your settings. Please check if you still see the problems when you turn that off.

**Comment by xunzhaoshitouyu** [comment]
If disable all extensions,the issue does not exist. @mjbvz @aeschli

**Comment by aeschli** [comment]
Thanks @xunzhaoshitouyu for finding that out. It would be great if you could file the issue against the problematic extension. Closing.
