### ISSUE TITLE
Debug: Add configuration option doesn't do anything anymore

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#32337]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ignoregit|And|1.0.1
code-settings-sync|Sha|2.8.2
jsx|Twe|0.0.1
vscode-open-file-folder|auc|0.0.3
gltf-vscode|ces|2.0.5
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
gitlens|eam|4.3.3
prettier-vscode|esb|0.22.1
ionic-preview|ion|0.0.15
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.7
vscode-sort-json|ric|1.9.0
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
wast|uky|0.2.6
vscode-react-native|vsm|0.4.1

---
 
**Steps**
1. Open a folder with no `launch.json`
2. Select Add Configuration

**Actual:**
Nothing happens

![code config](https://user-images.githubusercontent.com/173559/29223369-31ce49d8-7e7b-11e7-9c9f-65c7102a3fbd.gif)

**Expected:**
Quick pick list to be shown/

**Comment by weinand** [comment]
@isidorn this is a regression in 1.15. It was working fine in 1.14.2

**Comment by weinand** [comment]
@isidorn yes, keeping the [two arrays](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L155-L156) in sync is hard. :-)

It would be less error prone if your "executeOnSelect" array would consist of objects of the form `{ label: string, handler: () => {} )` and in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L183 you would "map" them to the required array of strings.

**Comment by isidorn** [comment]
@weinand thanks for the nice analysis, I have pushed a fix which you propose - having everything in one array to be less error prone
