### ISSUE TITLE
Not stopping at breakpoint ( IIS + VSCode)

### ISSUE THREAD

**Issue by tiaraju** [Microsoft/vscode#32332]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
net-core-starters-pack|bla|0.3.0
bracket-pair-colorizer|Coe|0.10.8
gitlens|eam|4.3.3
EditorConfig|Edi|0.9.4
git-project-manager|fel|1.3.2
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.31
csharp|ms-|1.12.0
mono-debug|ms-|0.15.7
resharper9-keybindings|ms-|1.1.0
material-icon-theme|PKi|2.1.0
aspnet-helper|sch|0.6.3
autoimport|ste|1.2.2
gitblame|wad|2.0.2
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Run a .NET web application on IIS
2. Attach vs code to an existing process 
3. Try to debug using breakpoints

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
VS Code has no builtin C#/.net debugger. Moving.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1706
