### ISSUE TITLE
Tab doesn't always create element automatically

### ISSUE THREAD

**Issue by AmirSavand** [Microsoft/vscode#32340]
- VSCode Version: 1.15.0
- OS Version: Windows 10

Steps to Reproduce:

- Open an `.html` file and type in `div`
- Press tab, nothing happens (except inserting spaces)
- Or type in `div.hello` nothing happens here too (if hello is already there in the file)

Really annoying.

**Comment by AmirSavand** [comment]
Really annoying.

**Comment by weinand** [comment]
What should happen?

**Comment by AmirSavand** [comment]
It should create the element, pressing tab on `div` should create: `<div></div>` and `div.hello` should create: `<div class="hello"></div>` which it did, but not after the update.

**Comment by weinand** [comment]
@ramya-rao-a is this emmet related?

**Comment by ramya-rao-a** [comment]
@AmirSavand Please read the [release notes](https://code.visualstudio.com/updates/v1_15#_emmet-20) for changes in emmet

Have you turned `editor.quickSuggestions` off? If not, they you should be able to see emmet related suggestions when you type the above examples.

If you are specifically looking for tab support in the absence of the suggestion list, Please follow the issue number 32243

**Comment by AmirSavand** [comment]
@ramya-rao-a I didn't turn anything off, it happened exactly after update and installation of 64bit version.
I can see the suggestions, and sometimes they work, but sometimes they don't.

I hope it gets fixed in the feature, this is really annoying, slows me down.

**Comment by ramya-rao-a** [comment]
@AmirSavand Try out our Insiders from http://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`. 

That should help

**Comment by ramya-rao-a** [comment]
@AmirSavand 

If you don't want to use Insiders, you can bind a keyboard shortcut (not tab) to the command `editor.emmet.action.expandAbbreviation` and use that to expand emmet

**Comment by HengCC** [comment]
After the update I also encountered this problem. sometimes it work .

**Comment by ramya-rao-a** [comment]
@HengCC Please give an example

**Comment by AmirSavand** [comment]
@ramya-rao-a ok, I will try that, but the tab key was really common in editors, I know by changing that it solves other issues. Thanks.

**Comment by AmirSavand** [comment]
I changes it and it works.
```json
  {
    "key": "tab",
    "command": "editor.emmet.action.expandAbbreviation"
  }
```

**Comment by ramya-rao-a** [comment]
@AmirSavand Yes, We really wanted to move away from using tab for emmet due to the problems it brings for non emmet users. But there has been feedback requesting the tab->emmet feature back, and so it is now available in the latest Insiders

**Comment by HengCC** [comment]
@ramya-rao-a  I see the change log of version 1.15.

There is an item that is described below

> Now that Emmet abbreviations are displayed in the suggestion/auto-completion list, VS Code no longer triggers Emmet abbreviations with the Tab key. Removing this keyboard shortcut solves 2 major issues:

Unexpected Emmet expansions occurring when the user wanted to just add an indent using the Tab key.
Items from the suggestion list getting inserted when the user actually wanted to expand an Emmet abbreviation.


so it's the really reason that cause the tab key faild. 

i was down the version to 1.14. and now it's working fine

**Comment by ramya-rao-a** [comment]
@HengCC Once VS Code 1.15.1 is released sometime tomorrow, you can set `emmet.triggerExpansionOnTab` to `true` to get the tab -> emmet feature back.
