### ISSUE TITLE
Unable to run grep in shell task

### ISSUE THREAD

**Issue by rteshnizi** [Microsoft/vscode#32349]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Reproduces without extensions: Yes

## Steps to Reproduce:

I made a `task.json` in my project's workspace. Apparently there is a problem with the way command arguments are being parsed.

1. make the following `task.json` in `.vscode` directory in the workspace.

```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "myTask",
            "command": "grep \"HELLO\" \"${file}\"",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
2. Since this is the default task now, hit `CTRL+SHIFT+B`

## Output
```
> Executing task: grep "HELLO" "c:\Users\rteshnizi\project\.vscode\tasks.json" <

Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

Terminal will be reused by tasks, press any key to close it.
```
## Expected Behavior
Output from Git Bash in vscode terminal
```
            "command": "grep \"HELLO\" \"${file}\"",
warning: LF will be replaced by CRLF in .vscode/settings.json.
The file will have its original line endings in your working directory.
```
Output from cmd in vscode terminal
```
            "command": "grep \"HELLO\" \"${file}\"",
```

**Comment by rteshnizi** [comment]
After updating VSCode the output has changed.

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
```
> Executing task: grep "HELLO" "c:\Users\rteshnizi\GitLab\cpd-docs\.vscode\tasks.json" <

/usr/bin/bash: /d: No such file or directory

Terminal will be reused by tasks, press any key to close it.
```

**Comment by rteshnizi** [comment]
After updating to 1.15.0 the task works fine if integrated terminal is set to cmd
`"terminal.integrated.shell.windows": "C:\\WINDOWS\\system32\\cmd.exe"`

The error in the above comment happens if integrated terminal is set to Git Bash.
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\sh.exe"`

With that said, the command executes successfully in the integrated terminal when it is set to Git Bash. See below screenshots.

![image](https://user-images.githubusercontent.com/1209547/29234217-147902ac-7ebb-11e7-8654-9288cf0a0d10.png)

![image](https://user-images.githubusercontent.com/1209547/29234206-fe62149a-7eba-11e7-9191-65043b0e6528.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/28036
