### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3234]
**Owner:** @isidorn 
**Assignees:**

- [ ] Windows @alexandrudima 
- [x] OS X @chrisdias 
- [x] Linux @joaomoreno

To address #1228 we have added **indentation support** to the editor. Verify:
* Actions `Convert Indentation to Spaces` and `Convert Indentation to Tabs` properly convert white space on the start of each line to spaces or tabs respectively
* Actions 'Indent Using Tabs' and 'Indent Using Spaces' change future indentation for the current editor
* Status bar always shows indentation status and clicking on it show the above actions
* These actions can not be invoked in read only text editors

**Comment by chrisdias** [comment]
Looks really good with latest changes.

**Comment by alexandrudima** [comment]
@isidorn Looks great!
