### ISSUE TITLE
[Feature Request] editor.links should be true, false or hover

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/vscode#32345]
```
// Controls whether the editor should detect links and make them clickable
"editor.links": true,
```

Amazing feature, but it's bad when we have interpolation in urls.
This setting should be a three-state setting: true for showing links and make them clickable, false for turn off and "hover" for link and clickable only if mouse is on top of it (so it doesn't interfere with interpolation)

**Comment by kanlukasz** [comment]
Now you can vote for this feature -> https://github.com/microsoft/vscode/issues/113220
