### ISSUE TITLE
[Feature Request] Visual Studio formatters

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/vscode#32343]
There is a lot of conflicting formatters in the market place and none of them format code as I like (Visual Studio does): expanded { on CSS and JavaScript, XML, JSON (expanded {), etc.

It would be nice a package with the same formatters found in Visual Studio (as they are perfect), and one for each language (because today when I need a JS formatter, I get a JS and a CSS formater, but another plugin formats CSS better than the first one, so I end up with not optimal choices or more than one formatter installed).

**Comment by mjbvz** [comment]
Custom formatters can be provided by extensions. We only ship with builtin support for formatting a limited number of languages and rely of extensions for the rest
