### ISSUE TITLE
Emmet: Parsing error when using loops in less file

### ISSUE THREAD

**Issue by anyclub** [Microsoft/vscode#32354]
- VSCode Version:1.15.0
- OS Version:windows 10.0.15063

When I use the loop in the LESS file,
EMMET error

`less code:`

`.loop-bg(@n, @i: 1) when (@i =< @n) {

        .list@{i} {
            background: url('../img/banner/list@{i}.png') center center no-repeat;
        }
        .loop-bg(@n, (@i + 1));

    }
`

then, in this file, i can't use emmet
error msg "Emmet: Failed to parse the file"

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@anyclub It works when you change `.list@{i}` to `.list(@i)`

I am not very familiar with less, but in your case `i` is a variable to be passed to `.list()` correct?
So shouldn't the syntax be `.list(@i)` ?

**Comment by anyclub** [comment]
@ramya-rao-a 
thx for your reply, my English is not very good.

less loop 
http://lesscss.org/features/#loops-feature
it's should use {},not ();

and its work in win10 32-bit,
Today, after the 64-bit update this problem

**Comment by ramya-rao-a** [comment]
I am sure its not a win 64 problem.

It is a problem with the update to 1.15 where we have made changes to the way Emmet works.

I'll remove the parsing check for now, so that you will be able to use emmet. 
The fix will be out on the Insiders build on Monday.

**Comment by ramya-rao-a** [comment]
@anyclub 

The new Emmet uses a different css parser which is failing to parse your example.

I have submitted a PR upstream to fix it

https://github.com/emmetio/css-parser/pull/1

cc @sergeche

**Comment by anyclub** [comment]
I updated to version 1.15.1 today.

#32345 The problem still exists 

发送自 Windows 10 版邮件应用

发件人: Ramya Rao
发送时间: 2017年8月12日 7:26
收件人: Microsoft/vscode
抄送: anyc; Mention
主题: Re: [Microsoft/vscode] windows 64-bit in less file emmet error(#32354)

@anyclub
The new Emmet uses a different css parser which is failing to parse your example.
I have submitted a PR upstream to fix it
emmetio/css-parser#1
cc @sergeche

**Comment by ramya-rao-a** [comment]
@anyclub The fix was not part of 1.15.1

I have pushed a fix that should be available in the [Insiders](https://code.visualstudio.com/insiders) on 18th August

Sorry for the trouble

**Comment by ramya-rao-a** [comment]
@anyclub Please try again in the latest Insiders and this issue should be fixed there.
