### ISSUE TITLE
[FR][Explorer View] Provide a way to hide certain view 

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#32357]
My [Docker Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer) has 5 Explorer Views. Some users complain about some views are not used in their scenarios: https://github.com/formulahendry/vscode-docker-explorer/issues/22. In v1.15 of VS Code, it is able to remove the views from existing windows. But every time we open up a new folder in a separate window, all the views still show up. When user do this, could we make this behavior permanent to hide certain view instead of a temporary setting? Thanks a lot!

**Comment by sandy081** [comment]
IMO this is a request to disable certain feature of an extension globally.

**Comment by sandy081** [comment]
Hiding views is global now
