### ISSUE TITLE
ExtensionContext.storagePath is empty if no workspace is open

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#32353]
- VSCode Version: Code - Insiders 1.16.0-insider (0b6da14128b4e61e331193f18786e8db2792a643, 2017-08-11T19:14:29.146Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-azurelogin|chr|0.0.1
---

Steps to Reproduce:
1. Create a hello world typescript extension using 'yo code' (as described [here](https://code.visualstudio.com/docs/extensions/example-hello-world))
2. Set a breakpoint in extension.ts activate() 
3. F5 the extension
4. In the new instance of VS, make sure *no* workspace is open
5. Active the extension by opening the command pallet and selecting the 'Hello World' command

Expected: When you hit the breakpoint, context.storagePath has a value
Actual: context.storagePath is 'undefined'

NOTE: This does *not* reproduce if you have a workspace open and I believe it was introduced with this change https://github.com/Microsoft/vscode/commit/73dad2ebb9ee82fd40d358fbdf39e1403ced342e?diff=unified#diff-c61682f360a18cf690ac59fe3f625db7L133 @bpasero

**Comment by bpasero** [comment]
@EricJizbaMSFT no, the storagePath is undefined when there is no workspace (see https://github.com/Microsoft/vscode/blob/6147b54439130c117fe6d27805656126ba480f2a/src/vs/workbench/api/node/extHostExtensionService.ts#L134 how it was before).

I am however not sure about the documentation of this property not mentioning this:

![image](https://user-images.githubusercontent.com/900690/29238390-c5b9dffe-7f34-11e7-8d09-beacb608b1ab.png)

@jrieken this should probably be documented?

**Comment by jrieken** [comment]
@dbaeumer To explain why this actually is and @bpasero since we now store state for the non-workspace. Is there now a place to persist things for that workspace? Some id or so?

**Comment by dbaeumer** [comment]
If a VS Code is in file mode the `storagePath` is `undefined`. This is to make it consistent with the rootPath.

**Comment by EricJizbaMSFT** [comment]
@bpasero Thanks for the clarification. It turns out we don't want to store stuff per workspace, so I'll use globalState instead. I'm okay to close this issue, but I'll leave it open in case you want to improve the documentation

**Comment by jrieken** [comment]
Assigning to @dbaeumer for more clarity in the comment

**Comment by bpasero** [comment]
@jrieken @dbaeumer yes in theory I can now assign an identifier even for the non-workspace case (we have one to support restoring of hot-exit and UI state for empty workspaces) but I agree that we should not change this, given we used to have `undefined` in this case.

**Comment by bpasero** [comment]
@sandy081 you since added `globalStoragePath` right? I suggest to maybe update the documentation of `storagePath` so that extensions can use `globalStoragePath` as a fallback location. 

Closing.

**Comment by sandy081** [comment]
It is documented here already - https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage
