### ISSUE TITLE
Update opened editor properly when renaming file externally

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#32355]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Steps to Reproduce:

1. have a git repo with test.txt
2. rename test.txt to TEST.txt
3. sync changes using VSCode

OPEN EDITORS is still test.txt, not TEST.txt

![1](https://user-images.githubusercontent.com/11925432/29234506-07df3268-7f2a-11e7-9438-f3688a79aa0e.PNG)

**Comment by bpasero** [comment]
@kzhui125 does it make any difference in this case if you rename the file

a) within VSCode
b) outside VSCode (not via GIT but through Windows explorer)

?

**Comment by kzhui125** [comment]
a) rename within VSCode
     file name case in "OPEN EDITORS" will update.
b) outside VSCode (not via GIT but through Windows explorer)
    file name case in explorer tree will update, but file name case in "OPEN EDITORS" won't update.(the same with via git)

**Comment by bpasero** [comment]
@kzhui125 does the editor tab update when you have the file opened in the editor? does the file name update if you have the parent folder opened in the explorer?

Trying to find out if this is an issue specific to the "OPEN EDITORS" section or a more general issue.

**Comment by kzhui125** [comment]
rename test.txt to TEST.txt using Windows explorer, the editor tab and the "OPEN EDITORS" section won't update, still "test.txt", but the file in vscode explorer tree will be updated to "TEST.txt".

**Comment by bpasero** [comment]
There is two issues:
* renaming a file to another name externally lets the opened editor close
* renaming a file to same name but different case does nothing

The challenge here is to get proper file events to understand what is going on. E.g. the file watcher service we have currently is not fit for reporting renames. These events will show up as delete (of the original name) and add (of the new name).
