### ISSUE TITLE
Themes's colors whose value is null assume red by default

### ISSUE THREAD

**Issue by heronsilva** [Microsoft/vscode#32359]
- VSCode Version: 1.16.0-insider
- OS Version: Debian 9.1 / Ubuntu 16.04

Steps to Reproduce:

1. Install the 'Dracula' theme
2. Select any theme you have installed
3. Switcth to 'dracula' or 'dracula soft'
4. Elements in the editor should turn red, like borders, sidebar text, etc.

Reproduces without extensions: No

Screenshot:
![](https://user-images.githubusercontent.com/9641348/29187241-69233aba-7de5-11e7-9300-80960e5c39fb.gif)

**Comment by aeschli** [comment]
It a bug in the dracula theme to use 'null' as color value.
To disable a color, use a transparent color (e.g. #00000000)

**Comment by aeschli** [comment]
This issue was moved to dracula/visual-studio-code#50

**Comment by heronsilva** [comment]
@aeschli Thanks!
Should I close the PR [#32360](https://github.com/Microsoft/vscode/pull/32360) then?
