### ISSUE TITLE
#include file not found in browse path

### ISSUE THREAD

**Issue by sophoc8** [Microsoft/vscode#32358]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.11.11-300.fc26.x86_64
- Extensions: 
INCLUDE FILE NOT FOUND IN BROWSE PATH, library is in usr/include/

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
python|don|0.7.0
code-runner|for|0.6.33
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.2
vscode-autohotkey|sle|0.2.1
vim|vsc|0.9.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#969
