### ISSUE TITLE
[Misconfiguration?] Control + Tab in OSX displays popup, not switching

### ISSUE THREAD

**Issue by darkguy2008** [Microsoft/vscode#32356]
- VSCode Version: Code - Insiders 1.16.0-insider (f1a3bc4f714123eaff5e15ad976d7f403cc1bfa2, 2017-08-11T05:08:07.764Z)
- OS Version: Darwin x64 16.6.0 (macOS Sierra)

Steps to Reproduce:

1. Open 2+ files
2. Hit Control + Tab

A few releases ago Control + Tab used to work pretty well. Now I'm trying to fast-switch between some files and a stupid popup appears. I mean, okay, well, you guys added a popup... but without focus! so I can't even use my arrow keys to choose the file (like in ST). This misbehavior (it wasn't working like this a few releases ago...) disrupts my current workflow and it is an unexpected change. 

There's nothing in the settings either to restore the default behavior. Please stop playing around with hotkeys :(

Is there any way to fix this? Thanks!

**Comment by bpasero** [comment]
@darkguy2008 you can navigate in that popup by just pressing the Tab key again and when you release you get to the editor.

There is another more stable popup with input box where arrow keys are working but I encourage you to try the Ctrl+Tab one

![image](https://user-images.githubusercontent.com/900690/29242263-fd8b6880-7f89-11e7-8aa2-a2e4073da1e6.png)

**Comment by darkguy2008** [comment]
Hello @bpasero, actually I updated my VSCode to version Code - Insiders 1.16.0-insider (0b6da14128b4e61e331193f18786e8db2792a643, 2017-08-11T19:14:29.146Z) and the error seems to have been fixed. Somehow the previous version lost focus in the popup and releasing the Tab key didn't work :)
