### ISSUE TITLE
Weird terminal title when using 'less' in bash

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32351]
- VSCode Version: Code - Insiders 1.16.0-insider (dc3a6df693da5ad6e9219cb0269439cc6a8c401a, 2017-08-11T06:58:01.143Z)
- OS Version: Darwin x64 16.5.0

- Open terminal
- Run some text through `less`. e.g., `cat package.json | less`
- Sometimes, the terminal title goes blank or gets weird characters
- If not, click around and select text in the window

See empty terminal title or something like this:
![image](https://user-images.githubusercontent.com/323878/29231974-36ce9a50-7e9e-11e7-8cff-3c7cd09b04a0.png)

**Comment by Tyriar** [comment]
Weird, I see the same but with an X, and then it goes blank. I guess this is the string that this native call is returning? https://github.com/Tyriar/node-pty/blob/a281a731f4c135f3a54143986fd4daabc7466610/src/unix/pty.cc#L391

**Comment by Tyriar** [comment]
Sometimes pty.process returns these weird characters. The root cause is probably in this function https://github.com/Tyriar/node-pty/blob/12caa78c871caa388b013ab9d2e327f2b0a3a76e/src/unix/pty.cc#L531
