### ISSUE TITLE
support for extract-method refactoring 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#32366]
the feature was merged in typescript: https://github.com/Microsoft/TypeScript/pull/17625
is there a way to use it in vscode?

```
Version 1.16.0-insider
Commit 0b6da14128b4e61e331193f18786e8db2792a643
Date 2017-08-11T19:30:08.812Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
```

**Comment by mjbvz** [comment]
This actually should already be supported if you use TypeScript 2.5. Try installing `typescript@next` in your workspace and selecting it as the active TS version: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

Here's a quick video of this in action: https://twitter.com/mattbierner/status/897933843151192065

Please try this out and report any issues you encounter with it
