### ISSUE TITLE
MacOS keyboard shortcuts don't (all) apply when File Open/Save dialog is presented

### ISSUE THREAD

**Issue by technicalflaw** [Microsoft/vscode#32364]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
beautify|Hoo|1.1.1
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
python|don|0.7.0
vscode-html-css|ecm|0.1.7
vscode-npm-dependency|how|1.1.4
svg|joc|0.0.9
docthis|joe|0.4.7
Go|luk|0.6.63
HTMLHint|mka|0.3.3
debugger-for-chrome|msj|3.1.7
stylelint|shi|0.28.0

---

Steps to Reproduce:

1. Do something to cause the standard Mac 'Save As' sheet to open (e.g. create a new file and go to File->Save As
2. Use a standard shortcut combination (standard in the context of the OS, not VSCode), such as cmd-A to select all text in the 'Save As:' field, or Ctrl-Tab to switch focus to the file list.
3. These expected actions don't occur for these specific examples, and presumably others as well, because they are still handled by the app (hence the flash of the relevant menu item when the aforementioned examples are used.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by brandonbloom** [comment]
@bpasero When closing duplicates, please link to the original. I was able to find this issue, but it took several tries to find the other one that is already closed: https://github.com/Microsoft/vscode/issues/797

I can not find an open issue. I'm experiencing this issue. Is this a regression?
