### ISSUE TITLE
Workspace folder paths should be relative to workspace file location

### ISSUE THREAD

**Issue by mvestergaard** [Microsoft/vscode#32368]
When you save a workspace file, the path to each folder is currently absolute.

Working in a team where it has practical value to check the workspace file into source control, that won't work.

So when the workspace is saved to a file, each folder path should be converted to a relative path.

**Comment by bpasero** [comment]
I disagree that the path should be relative as soon as you save it because once you move this file to another location, it is basically broken.

But allowing relative paths makes sense, if explicitly chosen: https://github.com/Microsoft/vscode/issues/31203
