### ISSUE TITLE
Debug console truncates strings longer than 100 characters

### ISSUE THREAD

**Issue by greay** [Microsoft/vscode#32361]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
uncrustify|Lau|2.6.0
unity-debug|Uni|1.2.1
vscode-nuget-package-manager|jmr|1.1.4
cpptools|ms-|0.12.2
csharp|ms-|1.12.0
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

Try to print any string longer than 100 characters in the debug console.
Alternatively, simply input:

"12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"

which outputs:

"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890…"

**Comment by weinand** [comment]
@greay what language are you debugging and what debug extension are you using?
If it is not Node Debug, please file this issue against the debug extension you are using.

**Comment by greay** [comment]
C#, Unity. I'll create a new issue.
