### ISSUE TITLE
paste indentation starting 1.15

### ISSUE THREAD

**Issue by alexfung888** [Microsoft/vscode#32365]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.2.3
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
debugger-for-chrome|msj|3.1.7
angular2-inline|nat|0.0.17
autoimport|ste|1.2.2

---

Steps to Reproduce:

1. copy the following from a template html
    <input 
      mdInput
      name='mdSelectedDate0'
      [ngModel]='mdSelectedDate0'
      [mdDatepicker]="picker0"
    >

2. paste it
    <input 
      mdInput
      name='mdSelectedDate0'
      [ngModel]='mdSelectedDate0'
      [mdDatepicker]="picker0"
    >
    <input 
    mdInput
    name='mdSelectedDate0'
    [ngModel]='mdSelectedDate0'
    [mdDatepicker]="picker0"
  >

3. Code 1.15 really doesn't like my style of indentation, which indents all the attributes of a tag and close it with the closing > (because unfortunately <input> cannot be closed by </input> or />

Code aligns the attributes (mdInput etc) with the <input, and outdates the closing ">". If pasted several times, the indentation will be shallower and shallower.

4. Pressing Undo will revert the change in indentation, back to what happens after a normal paste.

Reproduces without extensions: Yes/No

Yes, it is reproduced without extensions.

BTW, I suggest moving this question to the top. If it is not reproducible after disabling, that means I would have typed a lot of stuff to explain in futile.

**Comment by rebornix** [comment]
![html-paste](https://user-images.githubusercontent.com/876920/33458974-27b0cf3e-d5dd-11e7-8d97-e5f8e89ba03c.gif)

Already fixed in latest Insider, thanks!
