### ISSUE TITLE
Backspace (Old Caps Lock) on Colemak Not Working

### ISSUE THREAD

**Issue by R0gueHunt3R** [Microsoft/vscode#32369]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.12.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
sort-lines|Tyr|1.3.0
quokka-vscode|Wal|1.0.48
html-css-class-completion|Zig|1.8.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-eslint|dba|1.2.11
vscode-faker|dee|1.1.0
githistory|don|0.2.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
code-runner|for|0.6.33
csharpextensions|jch|1.3.0
csharp|ms-|1.12.0
debugger-for-chrome|msj|3.1.7
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0
stylelint|shi|0.28.0
html5-boilerplate|sid|1.0.1
autoimport|ste|1.2.2
code-spell-checker|str|1.3.6
open-in-browser|tec|1.1.0
vscode-todo-highlight|way|0.5.8
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Change layout to Colemak in XFCE 4.
2. Left backspace doesn't do anything (works as expected in Windows version). 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
May I suggest using `"keyboard.dispatch": "keyCode"`
From https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
![image](https://user-images.githubusercontent.com/5047891/32545654-b3509190-c47c-11e7-969e-f1ba1b1528b3.png)
