### ISSUE TITLE
Adopt official electron.d.ts

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32363]
Now that we are going to Electron 1.7.x we should drop our outdated electron.d.ts and replace it with the official one that Electron ships: https://github.com/electron/electron/releases/download/v1.7.4/electron.d.ts

**Comment by Tyriar** [comment]
I had trouble getting the official xterm.d.ts integrated last week. I ended up just copying it over to typings.

It would be good if someone more familiar with our setup/TS config could look into pulling the typings directly from the modules when available /cc @mjbvz

**Comment by bpasero** [comment]
Yeah, tricky because we always end up patching the d.ts. I think we can only do that if our changes are 0. I pushed it in.
