### ISSUE TITLE
Java syntax highlighting breaks on quote-parentheses combo

### ISSUE THREAD

**Issue by oakad** [Microsoft/vscode#32367]
Version: 1.14.2, Linux

The following line `IGNORE_SPACE(8, "ignore spaces before '('")`, seen inside enum declaration breaks highlighting, while being a perfectly valid Java.

**Comment by weinand** [comment]
Is this reproducible when running VS Code with extensions disabled?

**Comment by oakad** [comment]
Yes, disabling all extensions via command palette makes no difference. Feels like regex error in the highlighting profile to me.

**Comment by aeschli** [comment]
This issue was moved to atom/language-java#107
