### ISSUE TITLE
How to hide "扩展主机意外终止。请重新加载窗口以恢复。"dialog?

### ISSUE THREAD

**Issue by fzh917** [Microsoft/vscode#32378]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-format|rya|0.0.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by fzh917** [comment]
It hampers my works seriously.

**Comment by weinand** [comment]
Translation:
The extended host terminated unexpectedly. Please reload the window to restore.

@fzh917 when does this happen? Do you see a pattern? How frequently does this occur?
Does the problem disappear if you disable extensions?

You can get rid of the dialog by "Reloading the Windows" (press F1 and type "reload...).

**Comment by fzh917** [comment]
When I click the button "Reload the window to restore", this dialog shows again and hides the "Close "button of file resource manager.

**Comment by fzh917** [comment]
I have tried to reload window for many times.

**Comment by alexandrudima** [comment]
@fzh917 Does this reproduce when running `code --disable-extensions` ?

**Comment by fzh917** [comment]
@alexandrudima The Console shows:
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:386

**Comment by alexandrudima** [comment]
At this time, I don't know of any possible code change to do to improve the situation, as I cannot reproduce this in any way. 

@fzh917 Can you please try running out of a zip? Perhaps the VS Code installation is corrupt ?

* 64bit: https://az764295.vo.msecnd.net/stable/27492b6bf3acb0775d82d2f87b25a93490673c6d/VSCode-win32-x64-1.16.1.zip
* 32bit: https://az764295.vo.msecnd.net/stable/27492b6bf3acb0775d82d2f87b25a93490673c6d/VSCode-win32-ia32-1.16.1.zip
