### ISSUE TITLE
No Workspace option

### ISSUE THREAD

**Issue by SabeehMurtaza** [Microsoft/vscode#32377]
Hi,
I am having an issue with my vscode copy. It recently got updated to vscode 1.15.0. Now i have no workspace option like open workspace or close workspace or add folder to workspace in menu.
- VSCode Version: 1.15.0
- OS Version: Windows 10

**Comment by mvestergaard** [comment]
It's only in the insiders build.
From the release notes:

> Note: Multi-root functionality is only available in the Insiders build until we are confident enough that we can make it available in Stable. To try it out, grab our Insiders build from https://code.visualstudio.com/insiders.

**Comment by SabeehMurtaza** [comment]
Thankyou. Can u tell me what is the difference b/w insiders build and stable build?

**Comment by mvestergaard** [comment]
Insiders is the beta release track
