### ISSUE TITLE
editor.acceptSuggestionOnEnter": "smart" does not work

### ISSUE THREAD

**Issue by gegiskhan** [Microsoft/vscode#32370]
- VSCode 64 bit Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. Change editor.acceptSuggestionOnEnter": "on" to editor.acceptSuggestionOnEnter": "smart"
2. Write some word and wait for suggestions
3. Hit enter
4. The code should begins a new line instead of completing the suggestion

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@gegiskhan For adding new line on enter when the suggestion list is open set `editor.acceptSuggestionOnEnter` to `off`

When you set to `smart` it will only add a new line if the item being suggested and the current text typed are the same.
