### ISSUE TITLE
Add active(working) extensions counter

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#32375]
Extensions component have a counter showing overall number of installed extensions:
![current](https://user-images.githubusercontent.com/9638156/29241182-900694d0-7f7d-11e7-85bd-2b2e03b6c6d2.png)

I have a bunch of them disabled and I'd like to see how many of installed extensions are **active** (not disabled):
![desired](https://user-images.githubusercontent.com/9638156/29241191-b07c72c0-7f7d-11e7-9ff9-a000f0e6dccb.png)

**Comment by sandy081** [comment]
I see your requirement.. but not sure if I like the idea of showing `x` out of `y`. It is not clear what does that mean. I would not bother about the number of disabled extensions and will make my experience not good by showing this number. We already have a filter/command to show disabled extensions.
