### ISSUE TITLE
color picker uses wrong format

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#32379]
latest on master (2017-08-12)

- open the settings, add
```json
"workbench.colorCustomizations": {
        "statusBar.background": "#7A6969"
}
```
- hover over the color, see that the color picker header shows `"#7A6969"` (including the quotes)
- open a css file, have
```
 --toolbar-title-theme: {
    color: #357C35;
  };
```
- hover over the color. see that color picker header is `#357C35` (no quotes)
- switch back to the json file, hover, now the title is `#7A6969`, without quotes 
-> Should be with quotes again, like the first time we hovered. picking a different color will result in invalid JSON.
![image](https://user-images.githubusercontent.com/6461412/29241686-ba284a8c-7f7e-11e7-8fd0-afdc98877463.png)

**Comment by praveenpuglia** [comment]
I see it with quotes again. Can you put a screencast or something that helps in reproducing steps?

**Comment by joaomoreno** [comment]
Great catch, terrible bug.
