### ISSUE TITLE
Investigate HTML Linting support

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#32380]
We currently recommend vscode-htmlhint which is based on htmlhint for linting html files. Since linters will need to migrate to support multiple root folders it is a good time to investigate what HTML linter we want to recommend and help migrate to multi root support.

@mrmlnc I've seen your comment https://github.com/Microsoft/vscode/issues/30209#issuecomment-321357615, what is your opinion/recommendation.

FYI @aeschli @ramya-rao-a

**Comment by glen-84** [comment]
https://github.com/yaniswang/HTMLHint/issues/214 😞

**Comment by ArmorDarks** [comment]
Yeap, HTMHint seems to be mostly dead. Besides, because it does not support nor Stylelint, nor ESLint, it is problematic tool for inline CSS and JavaScript.

Few my notes here https://github.com/LotusTM/Kotsu/issues/268 might be helpful too.

**Comment by glen-84** [comment]
There's another one [here](https://github.com/htmllint/htmllint).

Not really very active either.

**Comment by mjbvz** [comment]
Closing this investigation as out of date
