### ISSUE TITLE
Problem tab on variable name and create tag from this!

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#32389]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.3.9600
---------------------------------------------------
Hi,
This feature is very good when tab on html tags (h1, h2, b, div & ... ) but when you tab on other things, no good to see tag from this!
Please see this gif:
![untitled4](https://user-images.githubusercontent.com/5067331/29243473-1699ba7c-7fb5-11e7-9d03-124ba0ac04b7.gif)

Thanks
@bpasero @rebornix @alexandrudima

**Comment by ramya-rao-a** [comment]
@miladghiravani That's the old emmet doing the expansion. It gets triggered on tab. It doesn't differentiate between a valid emmet abbreviation and a simple word.

Please upgrade to VS Code 1.15.
Tab no longer triggers emmet by default.

**Comment by miladghiravani** [comment]
@ramya-rao-a Thank's, this problem solved on new version. But when on HTML file you need to create **title** tag, **title** and some HTML tags not emmet.

**Comment by ramya-rao-a** [comment]
@miladghiravani Are you saying some of the tags don't appear in the suggestion/auto-completion list?

**Comment by miladghiravani** [comment]
@ramya-rao-a Yes show on suggestion/auto-completion list but can't emmet by tab.
For example:

- `<title>`
- `<nav>`
- `<sub>`
- `<sup>`
.
.
.

**Comment by ramya-rao-a** [comment]
@miladghiravani Got it. That is being tracked in https://github.com/Microsoft/vscode-emmet-helper/issues/5

The fix is in and will be available on Monday's Insiders build.
You can get the Insiders build from https://code.visualstudio.com/insiders
