### ISSUE TITLE
How to define a default for a new theme colour?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#32386]
I've added a new feature to my extension and want the user to be able to customise the colour. I figured it makes sense to have it in the `workbench.colorCustomizations` section, so planned to allow the user to do it like this:

```js
"workbench.colorCustomizations": {
	"dart.closingLabels": "#ff0000"
},
```

Then in my code I'm doing this:

```ts
new vs.ThemeColor("dart.closingLabels")
```

This works fine, but I don't know how to set a default. Ideally I'd like to fall back to the `tab.inactiveForeground` colour (so that it has a reasonable default for any theme). However, I can't see a way to do this.

Is there a nice way to handle this? Or is the best thing just to look for `workbench.colorCustomizations.dart.closingLabels` in the settings and if it's not set, use the string  `tab.inactiveForeground` for the colour?

**Comment by DanTup** [comment]
This seems to work; but feels a bit wonky:

```ts
vs.workspace.getConfiguration("workbench").get("colorCustomizations")["dart.closingLabels"]
```

**Comment by aeschli** [comment]
We need a contribution point for user defined theme colors, this is #14309.
That way user colors can define default and can also be defined in themes.
I'll add that for August.
