### ISSUE TITLE
New function vscode.debug.startDebugging is defunct

### ISSUE THREAD

**Issue by SAKryukov** [Microsoft/vscode#32383]
### Version Information:
- VSCode Version: 1.15.0
- OS Version: Microsoft Windows [Version 6.1.7601] (Windows 7)

### Related to:
The issue is related to [31266](https://github.com/Microsoft/vscode/issues/31266), [30865](https://github.com/Microsoft/vscode/issues/30865).

### Summary

New API `vscode.debug.startDebugging` is supposed to replace `vscode.commands.executeCommand("vscode.startDebug", launchConfiguration)` which does work correctly, but, with node.js "inspector" protocol, only with undocumented `type` `"node2"`, as explained in [31266](https://github.com/Microsoft/vscode/issues/31266), [30865](https://github.com/Microsoft/vscode/issues/30865). 

Not only `vscode.debug.startDebugging` does not reproduce correct functionality, but the symptoms look as if the `launchConfiguration` argument in `vscode.debug.startDebugging(launchConfiguration)` is ignored.

### Steps to Reproduce:

Code in extension:
```
        const launchConfiguration = {
            type: "node",  
            name: "launch",
            request: "launch",
            stopOnEntry: false,
            protocol: "auto"
        };
        launchConfiguration.program = ... // assign appropriate program
        vscode.debug.startDebugging(launchConfiguration);
```
The result of the call depends on the presence of the workspace file ".vscode/launch.json" of the target workspace using the extension. If the file is absent, the behavior is identical to the behavior when the user activates main menu item "Debug" => "Start Debugging" (F5): the user is requested for the choice and, if "node.js" is selected, the debugging starts with the currently opened JavaScript file (if any and if it is valid for the start of debugging).

**Important**: this is not the file specified as `launchConfiguration.program`. Basically, the behavior suggests that the entire structure passed as `launchConfiguration` is ignored.

If the file ".vscode/launch.json" is present, nothing happens, even if this file correctly prescribes debugging of the currently opened JavaScript file.

### Reproduces without extensions:
No (the issue is itself related to extension development)

**Comment by weinand** [comment]
@SAKryukov you are not passing a `folder` argument to `vscode.debug.startDebugging(...)`.
Please see the correct syntax here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5544

Probably you are not seeing a compiler error in the editor because you are using a stale `vscode.d.ts`.
Please remove the node_modules from your project and run `npm install` again.
Please remove your

**Comment by SAKryukov** [comment]
Andre,

Your assumptions were perfectly correct. This is what really happened, but it is unrelated to node_models.

It works correctly. Additionally, I checked up passing `undefined` as workspace directory (value for first argument), it also works correctly, as I expected. This is because all required data is passed through `launchConfiguration`.

Thank you.
—SA
