### ISSUE TITLE
Fix all auto-fixable problems not fixing everything

### ISSUE THREAD

**Issue by stibay** [Microsoft/vscode#32392]
- VSCode Version: 1.15.0
- OS Version: Windows 10

When I try to fix all issues with f.ex quotemark, no-inferrable-types and semicolon it fixes everything but the quotemarks.

It doesn't matter which problem I am starting the command from. Even from the quotemarks it doesn't fix them.

I also see now it's the same with the missing whitespace rule (didn't notice since I have this being formatted on save)

If quotemark is the only issue the option works.

**Comment by weinand** [comment]
Sorry, but I don't know whether this is a VS Code or an extension issue.
What language/extension are you using?

**Comment by stibay** [comment]
Aha I see. Figgured out it's coming from the TSLint extension. So maybe the issue should be logged there instead?

**Comment by weinand** [comment]
I'll move the issue to TSLint then.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-tslint#239
