### ISSUE TITLE
Minimum not version is not correct on How to Contribute wiki page

### ISSUE THREAD

**Issue by dlech** [Microsoft/vscode#32391]
At <https://github.com/Microsoft/vscode/wiki/How-to-Contribute#installing-prerequisites>, it says:
> You'll need git and a recent version of Node.JS (any v6.x is recommended, on Windows you need at least v6.x). nvm is also highly recommended.

However, I was not able to build with v6.x. Perhaps the minimum now is v7.x?

**Comment by weinand** [comment]
Yes, that info is outdated.
I always use the version that comes with VS Code's Electron version. Currently this is 7.4.
