### ISSUE TITLE
VSC on Windows 10 (only) with OneDrive gets EBUSY error when saving

### ISSUE THREAD

**Issue by mars000** [Microsoft/vscode#32398]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.10.0
platformio|for|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.2
platformio-ide|pla|0.6.0
debug|web|0.21.2

(3 theme extensions excluded)

---

Steps to Reproduce:

1. OneDrive installed on Windows 10, VSC latest version installed. I have Onedrive installed on other PC's and MAC syncing the same folders. [Note: same issue experience with Dropbox and Google Backup&Sync clients]
2.Open file in onedrive e.g. *.ino or *.cpp and edit it
3. Save file - on what seems to be random occasions I get the following error from VSC.
4. **Note: I have reproduced problem using both Google Backup&Sync cliend and DropBox.**
5. **Note: This error does not occur on my MAC version of VSC, only Windows 10**

![bug report screen capture](https://user-images.githubusercontent.com/19469711/29244986-604dcdc2-800d-11e7-88fc-13622d12ebcc.JPG)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
