### ISSUE TITLE
The downloading progress of C# dependencies stucked in China

### ISSUE THREAD

**Issue by IcyPoint** [Microsoft/vscode#32399]
- VSCode Version: 1.15.0
- OS Version: win7 sp1

Steps to Reproduce:

1.Update to 1.15.0
2.Restart VS Code and check output window

Reproduces without extensions: No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#972

**Comment by sean-mcmanus** [comment]
@weinand vscode-cpptools is for the C++ extension and not the C# extension. Can you move it to the correct location?
