### ISSUE TITLE
Implement soft text wrapping

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#324]
Wrap text when it would otherwise create a horizontal scrollbar.

**Comment by joaomoreno** [comment]
Open Settings and add `"editor.wrappingColumn": 0`.

**Comment by Tyriar** [comment]
Any thoughts on exposing this through the view menu to improve discoverability?

**Comment by joaomoreno** [comment]
@alexandrudima what do you think?

**Comment by alexandrudima** [comment]
That would be a nice feature, would also be cool to have right click on the line numbers to toggle "show line numbers"
