### ISSUE TITLE
Code Selection Artifacts with "window.zoomLevel": some_fraction_number

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#32404]
- VSCode Version: 1.15.0
- OS Version: Windows 10 Version 1703 Build 15063.540

Steps to Reproduce:

1. Use `"window.zoomLevel": 0.5` in config
2. Select all contents of file (example data https://gist.githubusercontent.com/Miserlou/c5cd8364bf9b2420bb29/raw/2bf258763cdddd704f8ffd3ea9a3e81d25e2c6f6/cities.json)

Reproduces without extensions: Yes

Issue not present with natural number in `"window.zoomLevel"`.

Screenshot:

![13-08-2017 00-48-35](https://user-images.githubusercontent.com/20873402/29247984-2c81830e-7fc1-11e7-984d-8027edddb3f3.png)

My config file:

```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 17,
    "editor.fontFamily": "Fira Code Regular",
    "editor.fontWeight": "normal",
    "editor.tabSize": 4,
    "editor.cursorStyle": "line-thin",
    "git.enabled": true,
    "explorer.openEditors.visible": 9,
    "explorer.enableDragAndDrop": true,
    "files.encoding": "utf8",
    "files.eol": "\r\n",
    "files.insertFinalNewline": true,
    "files.autoSave": "off",
    "window.openFilesInNewWindow": "default",
    "editor.renderWhitespace": "none",
    "window.zoomLevel": 0.5,
    "workbench.startupEditor": "welcomePage",
    "editor.lineHeight": 24,
    "editor.fontLigatures": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "eq-material-theme-icons",
    "editor.minimap.enabled": true,
    "editor.dragAndDrop": true,
    "editor.minimap.renderCharacters": false,
    "editor.cursorBlinking": "blink",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "editor.mouseWheelZoom": false,
    "editor.renderIndentGuides": true,
    "editor.renderLineHighlight": "all",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.matchBrackets": false,
    "diffEditor.renderSideBySide": true,
    "extensions.autoUpdate": false,
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    },
    "subtleBrackets.disableNative": true,
    "subtleBrackets.parse": true,
    "subtleBrackets.styles": {
        "global": {
            "borderWidth": "1px",
            "borderStyle": "none none solid none",
            "borderColor": "#FFCC00"
        }
    },
    "editor.find.seedSearchStringFromSelection": true,
    "editor.find.autoFindInSelection": false,
    "editor.selectionHighlight": true,
    "editor.occurrencesHighlight": true,
    // https://github.com/Microsoft/TypeScript/issues/6209
    "typescript.disableAutomaticTypeAcquisition": true,
    "css.colorDecorators.enable": false,
    "scss.colorDecorators.enable": false,
    "less.colorDecorators.enable": false,
    "json.colorDecorators.enable": false,
    "window.restoreWindows": "all",
    "extensions.ignoreRecommendations": true
}
```

**Comment by alexandrudima** [comment]
Selection is painted as a list of discrete rows, which in css pixels are covering a region entirely. When these coordinates get multiplied by the browser and the zoom level is applied, rounding errors in the browser engine lead to such smearing.

I suggest to not use `window.zoomLevel` unless you are projecting to an audience and need a quick way to zoom in.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side, **short of removing window.zoomLevel entirely**. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
