### ISSUE TITLE
vs Code is not working because of unknown error [0x800700c1]  

### ISSUE THREAD

**Issue by Nikhil1R** [Microsoft/vscode#32403]
- VSCode Version:1.14.2
- OS Version:Windows 10 pro

Steps to Reproduce:

1.im using extension for c and c++ and also for python and c# but its is showing error 0x800700c1 unknown error 
2.it is showing also showing [clang] error clang executable.
please fix this unknown error issue as soon as possible 
suggest me a idea to run my first hello world program in any (python,c,c++,c#) languages in vs code 
![vs code error 0x800700c1](https://user-images.githubusercontent.com/23690578/29246889-230911cc-8023-11e7-9d2e-6178b9cc83a8.jpg)
 

Reproduces without extensions: Yes/No it is not working even when etensions are disabled please help . help me launch my first c and c++, c# and python program of hello world.

**Comment by weinand** [comment]
This looks like a problem with the C/C++ extension. Please try to open the JSON file that appears in the error message and either fix it, or post it here so that I can look into it.

**Comment by weinand** [comment]
I will move the issue to the C/C++ extension.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#971
