### ISSUE TITLE
error TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by MerickOWA** [Microsoft/vscode#32400]
- VSCode Version: 1.14.2
- OS Version: Windows 7

Steps to Reproduce:

1.  Create a project folder which **contains a space separator character** somewhere in the name 
2. Create a .vscode/tasks.json as the following

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

3. Create a blank file .vscode/tsconfig.json

Launch build task results in 

```
> Executing task: tsc -p "c:\Temp\Project Space\.vscode\tsconfig.json" <

error TS5042: Option 'project' cannot be mixed with source files on a command line.

Terminal will be reused by tasks, press any key to close it.
```
Task manager shows the launched process as
```
C:\Windows\system32\cmd.exe /c ""C:\Users\lsmith1\AppData\Roaming\npm\tsc.cmd" -p c:\Temp\Project Space\.vscode\tsconfig.json"
```
which is missing the quotes around the tsconfig.json file path.

**Comment by dbaeumer** [comment]
This needs some major work. The original idea was that providers of the command do the quoting since it can be rather complicated (under Linux single, double quote and escaping). But this doesn't cover variables. So I need to think about where to best do the escaping.

**Comment by dbaeumer** [comment]
Need to shift. I spent September to work on multi root for tasks.

**Comment by dbaeumer** [comment]
We discussed several solutions and agreed that the extensions contributing the tasks need some OS / Shell independent API to do command line quoting. This is major API work and needs some time. Will start to work on it in November.

**Comment by HelloEdit** [comment]
Any news .

**Comment by dbaeumer** [comment]
This is still something that has priority to get addressed but due to the openness of the shell execution environment not so easy to address. It is assigned to a milestone for that reason and not on the backlog. But I have to admit it might not happen in February either since I went on a well deserved vacation :-)

**Comment by dbaeumer** [comment]
FIxed via https://github.com/Microsoft/vscode/issues/45576 which contains the necessary commit. Will work for tsc tasks out of the box.

Closing as dup of https://github.com/Microsoft/vscode/issues/45576
