### ISSUE TITLE
Emmet and Format Document: why are the new lines added?

### ISSUE THREAD

**Issue by albrin** [Microsoft/vscode#32406]
- VSCode Version: Version 1.16.0-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. ! and press tab
2. Alt+Shift+F

![Emmet and Format Document: why are the new lines added?](http://g.recordit.co/DiYNk63Rdt.gif)

**Comment by mrmlnc** [comment]
Hello, @albrin,

This feature not related to Emmet – it's related to built-in HTML Formatter. You can change this preferences by `html.format.*` options in the settings of Editor.

**Comment by albrin** [comment]
@mrmlnc, thank you!

This solved my "problem". Once again, everything is very flexible in the Visual Studio Code!

```javascript
{
    "html.format.extraLiners": ""
}
```
