### ISSUE TITLE
Support to preview selected suggestion as inserted text

### ISSUE THREAD

**Issue by Shuumatsu** [Microsoft/vscode#32402]
- VSCode Version: 1.15.0

I hope there can be a option in user setting, so I can use tab and shit-tab to select suggestions like in vim.

I tried the following keybindings.json 

```
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "shift+tab",
    "command": "selectPrevSuggestion",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
  },
  {
    "key": "tab",
    "command": "selectNextSuggestion",
    "when": "editorTextFocus && parameterHintsMultipleSignatures && parameterHintsVisible"
  }
]
```

but the following keybinding in the Default Keybindings cannot be removed by configuring the  keybinding.json file.
```
  {
    "key": "tab",
    "command": "acceptSelectedSuggestion",
    "when": "editorTextFocus && suggestWidgetVisible"
  }
```

In vim, selected suggestion is automatically inserted, VSCode do not until I press the enter.

In summary:

1. I want to use tab and shift-tab to select suggestion like I do in vim.
2. selected suggestion can be automatically inserted, changing selected suggestion resulting in replacing the inserted suggestion, and the suggestWidget will not be hide until I press esc or some char after the inserted.(like in vim)

![out](https://user-images.githubusercontent.com/15049134/29246567-ad067000-8031-11e7-9f3d-1e626f58e654.gif)

Hope my poor english can be understood.

**Comment by roachsinai** [comment]
Any update for this? @jrieken
