### ISSUE TITLE
"Terminal Delete Word Left" sends `^W` to terminal instead of deleting the word (powershell)

### ISSUE THREAD

**Issue by mrahhal** [Microsoft/vscode#32407]
- VSCode Version: 1.15
- OS Version: Windows 10

Steps to Reproduce:

1. Open the powershell integrated terminal and write something.
2. Hit `ctrl+backspace` or execute the "Terminal Delete Word Left" command.

A `^W` will show up instead of deleting the word:

![capture](https://user-images.githubusercontent.com/4404199/29248169-249dc298-801a-11e7-8280-6307b692a5cc.PNG)

Also, "Delete Word Right" sends a `D`.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31821

**Comment by dmaisano** [comment]
Having the same issue, `ctrl+backspace` inserts a `^w` in the current position in the terminal, `ctrl+delete` will insert a `d`. The functionality works in the powershell.exe that ships with windows. Checked [#31821](https://github.com/Microsoft/vscode/issues/31821) & [#39312](https://github.com/Microsoft/vscode/issues/39312) to no avail and found no solutions. Hopefully there's some sort of solution as I would use the WSL bash as my go to terminal however there's poor support for using dependencies installed within the WSL, ie. having vscode use the git.path point to the git installed in the wsl `/usr/bin/git`
