### ISSUE TITLE
FreeBSD version wanted!

### ISSUE THREAD

**Issue by SchrodingerZhu** [Microsoft/vscode#32409]
I wonder if we have the plan to build a version for freeBSD?

**Comment by NateLing** [comment]
lol,.freebsd needn't,vim is the best editor for freebsd.

**Comment by SchrodingerZhu** [comment]
FreeBSD and linux both have x，both enjoy emacs and vim. So vim is no an excuse. As bsd has some feature that linux cannot enjoy，there are still some people use bsd as the desktop work station. Therefore，there exist a need.

**Comment by ykla** [comment]
I think so. 
We should have VS on FreeBSD.
@SchrodingerZhu

**Comment by jhalbrecht** [comment]
Hope that means you'll port it to [OpenBSD](https://www.openbsd.org/)

Microsoft is certainly supporting OpenBSD financially! :-) [Microsoft becomes OpenBSD's first gold contributor | ZDNet](http://www.zdnet.com/article/microsoft-becomes-openbsds-first-gold-contributor/)

**Comment by marcker** [comment]
+1

**Comment by paulopinda** [comment]
+1

**Comment by GeometricAlgorithm** [comment]
+1

**Comment by lapo-luchini** [comment]
There is an unofficial but working build here:
https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/releases/tag/v1.17.2

**Comment by zoujiaqing** [comment]
how to use VSCode in FreeBSD now?

**Comment by lapo-luchini** [comment]
Waiting for an upcoming official commit in FreeBSD Ports, I think the best way is still to use the release linked in my previous message.

**Comment by SchrodingerZhu** [comment]
Still looking forward!

**Comment by Tyriar** [comment]
#1359
