### ISSUE TITLE
Support for PostCSS syntax and color picker in postcss files

### ISSUE THREAD

**Issue by mhshakouri** [Microsoft/vscode#32410]
- VSCode Version: 1.15.0
- OS Version: Win10 v1511(build 10586.1007 64bit)

Steps to Reproduce:

1. Install PostCSS Syntax plugin
2. try to use color picker (introduced in new version)

Reproduces without extensions: Yes/No Yes

It's not actually a problem I just wanted to ask you guys to enable support of PCSS file formats for postcss syntax and also let the color picker work in pcss files too. Thanks

**Comment by mhshakouri** [comment]
I will take a look at the source codes later my self and see if I can help add above features my self

**Comment by joaomoreno** [comment]
We will release a color picker API #32235 and the PostCSS Syntax extension needs to adopt it.
