### ISSUE TITLE
On linux the defalut `$SHELL` is` /bin/zsh` But Task runner run taks in `/bin/bash`

### ISSUE THREAD

**Issue by p0ooo0ya** [Microsoft/vscode#32418]
In my Linux machine the default shell is zsh but when i run tasks it run them in /bin/bash. It doesn't make any problem when you are not printing to the console like compiling a C program a bash session starts and ends in the integrated terminal but when you want to read the output it results in a flashing behavior. Maybe there is a setting that says use the default shell for running tasks but unfortunately i can't find it. 

I'm using Ubuntu zesty (17.04) with VS Code 1.16.0-insider

**Comment by dbaeumer** [comment]
You need to tell VS Code which shell to use. When you open the integrated terminal which shell does VS Code use? If it uses zsh can you post your tasks.json file here.
