### ISSUE TITLE
How to disable the annoying <?php drop suggestion in .php files 

### ISSUE THREAD

**Issue by a-eid** [Microsoft/vscode#32413]
![](https://i.imgur.com/yvz7xQU.png) 
 
I have disable the suggest basic for php ! 
` "php.suggest.basic": false`

thank you .

**Comment by roblourens** [comment]
I don't see that when I have basic suggestions disabled, do you have any extensions that could be contributing it?

**Comment by a-eid** [comment]
It was definitely an extension issue , I have removed all php extension and problem has been resolved .
