### ISSUE TITLE
Can "Welcome page" close itself when I chose a file from my lateral files list?

### ISSUE THREAD

**Issue by johnunclesam** [Microsoft/vscode#32416]
Can I close "Welcome page" when I chose a file from my lateral files list?

Everytime I sit on my PCI open VSCode and I have "Welcome Page" in front of me, which is really a good thing. But if I have already open my last project in my lateral bar I want that Welcome page closes itself when I pick a file from that list.

Is my issue clear?

**Comment by bpasero** [comment]
@chrmarti this would be possible if the welcome editor itself was not "pinned" but showing as preview.

**Comment by chrmarti** [comment]
Will give opening the Welcome page as a "preview" editor a try. /cc @seanmcbreen
