### ISSUE TITLE
Alternative line comment behaviour

### ISSUE THREAD

**Issue by paidhi** [Microsoft/vscode#32411]
It would be great for efficiency if a setting could be introduced to change the behaviour of the editor when `editor.action.commentLine` is performed.

Currently the cursor stays at the current line und performing `editor.action.commentLine` repeatedly switches between comment and uncomment for that line.

I very much like the behaviour of the editor in Jetbrains IntelliJ based products (PyCharm, WebStorm, IDEA, RubyMine, etc.). When you comment a single line the cursor moves down to the line below. Thus subsequently performing this action one can quickly comment multiple lines without having to mark the lines first. However having marked some lines and then performing this action does not move the cursor or the marking. As it should be IMHO.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
