### ISSUE TITLE
Replicate functionality of "build system" in Sublime Text

### ISSUE THREAD

**Issue by corvusblack** [microsoft/vscode#32429]
I am looking for something like what Sublime Text does. In Sublime Text, you can define a "build system" which may be associated with a file extension. The build system is a user-defined shell command. You can then build a file with your build system without having to have a project or workspace set up. However when I try to do the same thing in vscode using "build tasks", I get an error saying "Tasks are only available on a workspace folder". I don't want to have to create/open a workspace folder if I want to build a simple script.

Could you possibly imitate the functionality of Sublime Text?

- VSCode Version: 1.15
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file (i.e. index.php)
2. Go to `Tasks > Run Build Tasks` or `Tasks > Configure Tasks`
3. A error notification pops up saying "Tasks are only available on a workspace folder"

Expected Outcome:
Instead of the error notification, I should be able to run and configure tasks without having a project. This is how Sublime Text works.

**Comment by kodos84** [comment]
Just to update anyone watching this issue. I found out about global launch configurations (mentioned here: https://github.com/Microsoft/vscode/issues/18401#issuecomment-272400316) which solves what I was trying to do. So this ticket could be closed unless anyone else has a good reason to keep it open.

**Comment by dbaeumer** [comment]
@kodos84 thanks for coming back. Actually global launch configs still don't allow global tasks. So I think the request is still valid even though our specific problem is addressed.

**Comment by alexr00** [comment]
Shared task configurations is tracked by https://github.com/microsoft/vscode/issues/1435
