### ISSUE TITLE
Ability to toggle showing CodeLens [feature request]

### ISSUE THREAD

**Issue by SirIntruder** [Microsoft/vscode#32421]
First, big shout out for guy behind Toggle CodeLens extensions, which toggles editor.codeLens value in the settings on keyboard shortcut.

CodeLens is very useful, the problem with it is it can easily take an unhealthy amount of space in some situations relatively to the amount of code. I keep it on most of the time, and want to the hide it from time to time.

What is currently missing with "toggle editor.codeLens" method is that: 1) it does full rebuild of the index, which can take up some time and is annoying 2) I think enabling it while on page doesn't make CodeLens pop in back as you would expect, looks like it checks for value only on page load.

I can imagine having "codeLensHidden" bool which would just toggle code lens on UI level, but I assume keeping cache between codeLens disable/enable to be possible

**Comment by Gama11** [comment]
>I think enabling it while on page doesn't make CodeLens pop in back as you would expect

That might have to do with the extension for the language you're using not checking the `onDidChangeCodeLenses` event - that's quite likely because the language server protocol doesn't support that yet: https://github.com/Microsoft/language-server-protocol/issues/192

**Comment by weinand** [comment]
Is this an issue of VS Code or the "Toggle CodeLens" extension?

**Comment by SirIntruder** [comment]
I assumed rebuilding of codeLens index every time codeLens property is toggled was general vscode behaviour, but good thing is I was mistaken, this doesn't happen all the time, looks like it fluked when I was testing first time. 

Since second issue is already covered and not general vscode issue, this issue can be closed

**Comment by weinand** [comment]
Great, thanks for investigating!
