### ISSUE TITLE
Improve extension recommendations

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32422]
Currently the extension recommendations come from 2 sources
- a curated list of extensions mapped to filetypes maintained by the VS Code team. 
- the extension list inside the `.vscode/extensions.json` file in a workspace which is maintained by the workspace owners

A framework that can help explain to the user why and how these recommendations are made is missing

This issue tracks work in improving the extension recommendation system and will span over several iterations.

Things to achieve
- Users should **understand why** a recommendation is being made. A recommendation can be
    - based on current file type
    - based on current workspace
    - history of types of files opened
- [x] **Recommendations should be relevant**. For example: User opens a php file long time ago, gets recommendation for a php extension, never again opens a php file. The recommendation continues to show up today. Files/workspaces used more often should influence recommendations than files/workspaces rarely used
- **Recommendations list should be short and well sorted as per relevance**. For example: the recommendation for current file type and workspace can show up before the ones based on historical usage (moved to September milestone)

We need telemetry in place to
- [x] determine whether recommendations are successful
- [x] assess the success of different ways of presenting recommendations
- associate extensions with features like format/lint/completion/outline etc This can in the future help in recommending by category (moved to September milestone)

**Comment by jens1o** [comment]
Sounds great, because personally I have disabled that view, because I don't need those extensions that are suggested.

How do you want to improve the algorithm?

**Comment by ramya-rao-a** [comment]
Adding a way to calculate relevance of an extension recommendation can help in pruning the list.
Currently extensions recommended by file type gets stored in the local storage and they appear in the recommended view.

The simplest way to go about this is storing a timestamp along with the recommendation. If that date is more than a week old, the extension is removed from the list.

cc @sandy081 @kieferrm @seanmcbreen

**Comment by gep13** [comment]
@ramya-rao-a would it be possible to add an entry onto the `list of extensions mapped to filetypes maintained by the VS Code team.`?

Ideally, if there is a .cake file in the current workspace, it would be great if the user were recommended to add the Cake Extension:

https://marketplace.visualstudio.com/items?itemName=cake-build.cake-vscode

Thanks

**Comment by ramya-rao-a** [comment]
@gep13 That's a valid request. I have created an issue to track this. See #38543
Once we have a good list there and few of us from the team verify the extensions, we will update the recommendations

**Comment by gep13** [comment]
@ramya-rao-a that is great, thank you!
