### ISSUE TITLE
Enhancement: Ability to transliterate and auto-complete

### ISSUE THREAD

**Issue by psankar** [Microsoft/vscode#32425]
This is an enhancement request.

I like Visual Studio Code. It is truly cross platform and is easily available everywhere. I would request to add support for transliteration to visual studio code. Right now, if I have to type a text in a non-roman language, say Tamil, (may be for a web page or a .po file, etc.) I need to go to a browser, type the content that I want, copy it and then come back to Code and paste here. This workflow could be optimised if there is native support for transliteration within Code.

We can already change the keyboard language setting from the browser and type with a different keyboard. But what I would like to have is a more intelligent transliteration system that can potentially talk to a web API (like google https://www.google.com/inputtools/try/ ) or my own plugin. This will save some typing by intelligent auto-completion without expecting the user to type all the text. 

I would even try to contribute this, if this can be achieved as an extension. In case, something is not clear, please ask and I can elaborate. Thanks.

**Comment by alexandrudima** [comment]
I believe an extension could use our `CompletionItemProvider` api to provide such suggestions.

**Comment by psankar** [comment]
Is there any open source extension that I can look for reference, that makes use of the above mentioned API ? Thanks.

**Comment by varunkumar** [comment]
@psankar I gave it a try today. It was pretty easy to build an extension in VS Code. https://github.com/varunkumar/google-input-tools
