### ISSUE TITLE
php: Order of emmet suggestions is different in php in quick suggestions vs manually triggered suggestions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32424]
In the below example, `ul>li` should have been at the top.

While typing, it appears at the bottom.
When suggestions is manually triggered (using Ctrl+Space), it shows up top

![emmetphp](https://user-images.githubusercontent.com/16890566/29252042-05a1d17c-8015-11e7-89c3-8e7fdcec4405.gif)

**Comment by roblourens** [comment]
Seems fixed now

**Comment by ramya-rao-a** [comment]
But how... but when ...  :)
