### ISSUE TITLE
Install update - Improve extension selection performance

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3242]
**Issue:** #2621 
**Assignees:**

- [x] Windows @alexandrudima 
- [x] OS X @weinand 
- [x] Linux @isidorn 

**Details:**

We now cache the extension gallery results in an Azure blob. This cache helps us in being faster in displaying the extension list but introduces another level of complications.

The cache itself lives at `http://vscode.blob.core.windows.net/gallery/index`. It is updated every minute due to a Scheduler service in Azure.

- Make sure searching for extensions inside Code works as before, but is faster.
- Using a firewall, try blocking the cache's requests. Make sure Code falls back to the original Gallery API.
- You can (and should) also go into our Azure subscription, stop the scheduler that updates the cache every minute and test the query once 5 minutes have passed. The rule is: if the gallery index is stale for more than 5 minutes, Code should fall back to the original service call. Ultimately, you should always see extensions.

![image](https://cloud.githubusercontent.com/assets/22350/13230063/3adcd882-d9a4-11e5-9e33-ae5c79bbe55c.png)

**Comment by weinand** [comment]
@joaomoreno I'm using Little Snitch on OS X as a firewall for outgoing requests:

![2016-02-23 22-54-37](https://cloud.githubusercontent.com/assets/1898161/13268113/fa39992c-da80-11e5-8b85-693ccf0db17c.png)

But I could not see a noticable difference when blocking access to the caching service or even stopping the service for more than 5 minutes.

So i wasn't able to find any problems, but I couldn't see a noticeable speed difference either.

**Comment by alexandrudima** [comment]
I added the following to my hosts file:
```
127.0.0.1 vscode.blob.core.windows.net
```

and it still works
