### ISSUE TITLE
Twig Emmet Issues when Classes have hyphens and numbers

### ISSUE THREAD

**Issue by timknight** [Microsoft/vscode#32438]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0

Extension|Author (truncated)|Version
---|---|---
sublime-keybindings|ms-|2.9.1
twig|wha|1.0.2
vscode-twig-pack|baj|1.0.0

Steps to Reproduce:

1. I have twig configured with emmet by added `"twig": "html"` to `emmet.syntaxProfiles` and `emmet.includeLanguages` so emmet as a whole works okay. 
2. From an HTML twig template when I execute something like `.row>.col-md` emmet will respond just fine. If however I do `.row>.col-md-5` emmet doesn't respond at all.

Issues still happen when vscode-twig-pack is deactivated which leads me to think it's associated with the built in extension.

**Comment by ramya-rao-a** [comment]
@timknight I am not very familiar with twig.

Can you share a self contained example that I can try?

**Comment by timknight** [comment]
Hi Ramya, no problem at all. Just know that for the most part Twig is basically just HTML. The only thing that changes is where dynamic output happens. It would probably help too to have the [Twig extension](https://marketplace.visualstudio.com/items?itemName=whatwedo.twig) installed just for syntax coloring.

Then to get started, you can use the base Emmet `!` template on a page that's defined as HTML (Twig):

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

Within the body just starting:

`.container>.row>.col-md-5`

You'll notice that all the way through typing `md` you'll see Emmet still respond. Until you type `-5` and nothing will happen. If you take the same exact template and change the language mode to `HTML` it will behave correctly. I thought it might be the whatwedo twig extension at first, but it looks like all that extension does is define a language template for syntax coloring for the twig language. Aside from adding the `emmet.syntaxProfiles` and `mmet.includeLanguages` options I mentioned in my OP that's all the special configuration I've done. 

I hope that counts as a self-contained example, but let me know if I can provide something better to help you test what I'm seeing.

**Comment by timknight** [comment]
Though I should note executing "Emmet: Expand Abbreviation" manually will work. It just seems odd to me that the same class would stop detecting for tab abbreviation between HTML and HTML (Twig).

**Comment by ramya-rao-a** [comment]
Thanks for the clarification. I was able to repro.

So what is happening is that running the command `Emmet: Expand Abbreviation` works.
Triggering suggestions manually (via `Ctrl+Space`) works.

But suggestions stop showing the emmet abbreviation as soon as you type the number

The quick suggestions feature (suggestions showing up as you type) is triggered when you type anything that matches the word pattern as defined for the language.

In case of html, the word pattern is defined to include numbers. See https://github.com/Microsoft/vscode/blob/master/extensions/html/client/src/htmlMain.ts#L85

In case of twig, no word pattern is registered in the extension that provides the twig support. So VS Code falls back to the default word pattern it uses which doesn't include numbers.

I'd suggest to create an issue in the whatwedo extension to include a word pattern for twig. Since it is basically html, you can copy the one from https://github.com/Microsoft/vscode/blob/master/extensions/html/client/src/htmlMain.ts#L85

Until then, hit `Ctrl+Space` whenever you feel there should have been an emmet suggestion, but its not.

Makes sense?

**Comment by timknight** [comment]
Ah yes okay that makes sense. Looks like it would probably have to go within the language-configuration.json, but I'll have to do some research to see how that actually works and how to properly escape the regex. I figured, I might as well try to address it and send a pull request for them. Thank you so much for clarification on this!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!

**Comment by timknight** [comment]
@ramya-rao-a, this might be a little out of scope for our question I'm just hoping you can tell me if I'm on the right track or let me know if there's a way to test that it's reading the wordPattern. I have a fork of this project at https://github.com/timknight/vscode-twig. I've included a JS file that it's referenced in the package.json and the script is just a basic `setLanguageConfiguration` to set the wordPattern. Nothing errors for me, but I still don't get a fix to the problem. Is there more I need to do to define the wordPattern to correct the issue?

**Comment by ramya-rao-a** [comment]
Since a couple of months, you dont need to add the wordPattern via code. You can add it in the `language-configuration.json` file directly. Have you tried that?

**Comment by timknight** [comment]
I considered that first, from what I read it would be doing something like this...

```
{
  "wordPattern": {
    "pattern": "..."
  },
  "comments": {
    "blockComment": [ "{#", "#}" ]
  },
  "brackets": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"]
  ]
}
```

Or it could be just a string right off of "wordPattern" right? Where I struggled however was properly escaping the Regex in question into a string in the JSON file. So I jumped into the `.js` file option instead. Open to thoughts on how to best approach that within the `language-configuration.json` though.

**Comment by ramya-rao-a** [comment]
Its supposed to be just `"wordPattern": "...."` in the `twig.configuration.json` file in that repo

Below is the escaped version of the word pattern for html. I placed it in the `twig.configuration.json` file, and I can get emmet suggestions on the last `-5` now.

`"wordPattern": "/(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\$\\^\\&\\*\\(\\)\\=\\+\\[\\{\\]\\}\\\\|\\;\\:\\'\"\\,\\.\\<\\>\/\\s]+)/"`

**Comment by ramya-rao-a** [comment]
What you have done works as well, except you need to add another field in the package.json file

You cannot have a `main` without the `activationEvents`, else the extension host in VS Code will not know when to activate the extension.

```
"activationEvents": [
        "onLanguage:twig"
    ]
```

**Comment by timknight** [comment]
Thank you so much. This has been incredibly helpful just for me to grasp how all of the various configuration is setup for vscode. Strangely, adding it to `twig.configuration.json` stops all but `!` from working.

```
{
	"comments": {
		// symbols used for start and end a block comment. Remove this entry if your language does not support block comments
		"blockComment": [ "{#", "#}" ]
	},
	// symbols used as brackets
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"]
	],
	"wordPattern": "/(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\$\\^\\&\\*\\(\\)\\=\\+\\[\\{\\]\\}\\\\|\\;\\:\\'\"\\,\\.\\<\\>\/\\s]+)/"
}
```

Am I missing something with that? 

However adding activationEvents worked great. 🎉

**Comment by ramya-rao-a** [comment]
Maybe I missed an escape sequence somewhere when copy pasting :)

Either model (programatic vs declarative) works

**Comment by ramya-rao-a** [comment]
Shall we close this issue then?

**Comment by timknight** [comment]
Absolutely, thank you so much for your time @ramya-rao-a. Way more than I could have expected on this!

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!
