### ISSUE TITLE
Visual Studio Code v1.15 Crashing Immediately

### ISSUE THREAD

**Issue by collenjones** [Microsoft/vscode#32433]
- VSCode Version: 1.15
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Start VS Code (either from command line with `code` or by dbl-clicking the Application)
2. Crashes Immediately

I wish I could provide you more information -- how can I check the editor log? 

Reproduces without extensions: Yes

```
$ code
$ code --disable-extensions
$ code --verbose --disable-extensions
$
```

**Comment by jens1o** [comment]
Err... VSCode Version 6.0 is not existent?

**Comment by collenjones** [comment]
Ha! Whoops -- I misread the `Info.plist`. It's version 1.15, downloaded yesterday (Sunday).

**Comment by bpasero** [comment]
@collenjones can you share a video or screenshot how the crash manifests to you? Does it reproduce also when you run "`code -n`" to open an empty window?

**Comment by collenjones** [comment]
@bpasero I've put a screencap [here](https://drive.google.com/open?id=0B0Ed8jeyo0AUOUtmLW1YVDRvWDg) on Google Drive

`code -n` crashes the same as `code`

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by aron7** [comment]
maybe chaotic processes with unknown spinof? serendepity?

**Comment by collenjones** [comment]
@bpasero It crashes just the same with the insider build. 

I've actually experienced this with several versions of Code -- I filed a ticket before several months back but it was resolved when I didn't respond in time.

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by collenjones** [comment]
Hold up -- I  had *not* actually downloaded the Insiders build. It was below the fold in the link you gave me and I had just been downloading the regular stable build. The Insiders build works!

What can I do to get you more information about what was going wrong with the regular build?

**Comment by collenjones** [comment]
Here is your checklist when I was using regular `Code`:

[X] it reproduces with extensions disabled (code --disable-extensions from the command line - NOT the integrated terminal of Code)
[] it was not happening in the previous stable release
  (collen) It has occurred across multiple versions (1.12, 1.15)
[] it reproduces in insiders builds
  (collen) This works!
[X] there is no suspicious output when running from the command line (code --verbose)
[] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
  (collen) I cannot test this since the app crashes immediately.
[] it reproduces on Windows, Linux and Mac
  (collen) I only have access to a Mac environment
[X] it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json 
[X] it reproduces when opening empty (code -n from the command line)
[X] it reproduces opening any folder
[X] it reproduces opening any file
[X] it reproduces when only having a single window open
[X] it reproduces by just using Code without external tools running on the same folder
[X] it reproduces from a workspace that is not under Git version control
[X] it reproduces independently if a file is opened or not after startup
[X] it reproduces when running with GPU disabled (code --disable-gpu)
[X] it reproduces when being offline
[X] it reproduces when disabling the file watching (set files.watcherExclude to "**/**": true)
[X] it reproduces after uninstalling and reinstalling
[X] it reproduces after deleting the application data directory
[X] I have not played around with permissions or ran Code as administrator
[X] I am seeing a single CPU process spin high (please share the full command line arguments)
[] I am seeing Code consuming lots of memory in a short time
  (collen) Code is crashing immediately

**Comment by bpasero** [comment]
@collenjones does it reproduce with stable if you run "`code --user-data-dir=<some dir>`"
