### ISSUE TITLE
Debug picker switches away from compound launch config

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32439]
- Select the "Debug VS Code Main and Renderer" compound launch config
- Click debug
- See it switch to one of the configs, so I have to fix it next time I want to debug

![aug-13-2017 20-19-25](https://user-images.githubusercontent.com/323878/29257181-bcbd88fc-8064-11e7-87b1-059abc7e0f8d.gif)

**Comment by octref** [comment]
Same issue. Pretty annoying for debugging...

**Comment by shakurass** [comment]
Definitely annoying. +1 for a fix to this issue.

**Comment by Gama11** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/32318?

**Comment by isidorn** [comment]
@Gama11 thanks, closing as duplicate. This should be fixed in latest insiders
