### ISSUE TITLE
Documentation issue on site

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#32432]
A quick fix -- simply miswording I believe 

On the [themes documentation page](https://code.visualstudio.com/docs/getstarted/themes) in `workbench.tokenColorCustomizations` is referenced in text and then the screenshot clearly shows the correct `editor.tokenColorCustomizations`. Ctrl+F will yield the location in two seconds.

**Comment by jens1o** [comment]
Please file your issue here: https://github.com/Microsoft/vscode-docs

Also, you can file a Pull Request there to fix the problem yourself. :)

**Comment by gregvanl** [comment]
Thanks!
Fixed with https://github.com/Microsoft/vscode-docs/commit/fd9641b255d4278377fff82abb6e0d15ebb96a86
