### ISSUE TITLE
Emmet snippets not working for XSL language mode

### ISSUE THREAD

**Issue by sintell** [Microsoft/vscode#32430]
- VSCode Version: Code - Insiders 1.16.0-insider (0b6da14128b4e61e331193f18786e8db2792a643, 2017-08-11T19:14:29.146Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. Create new file and set  language mode to `xsl`
2. Input `xsl` and call `Emmet: expand abbreviation`

The result is:
```
<!!!></!!!>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"> |</xsl:stylesheet>
```

Desired output is:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"> |</xsl:stylesheet>
```

Abbreviation being expanded:
```
"xsl": "!!!+xsl:stylesheet[version=1.0 xmlns:xsl=http://www.w3.org/1999/XSL/Transform]>{\n|}"
```
from default snippets.json

Snippet for `!!!` is:
```
"!!!": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
```
also from default snippets.json

I've also tried to expand `!!!` directly and an turns to `<!!!></!!!>` as well.

Expanding snippet `!!!` for HTML grammar works as expected.

I haven't set `"emmet.extensionsPath"`

**Comment by ramya-rao-a** [comment]
Thanks for reporting @sintell!

I have submitted an upstread PR to fix this in emmet snippets. https://github.com/emmetio/snippets/pull/2

That can take a while to get merged and then the change to be absorbed in VS Code.

Until then, a workaround is to add a custom snippet

**Comment by ramya-rao-a** [comment]
This is fixed and and you will be able to use both `!!!` and `xsl` snippets without the need for custom snippets in tomorrow's Insiders
