### ISSUE TITLE
Is there anyway to expand current focused editor?

### ISSUE THREAD

**Issue by lsps9150414** [Microsoft/vscode#32441]
I want to focus on one of the split editors with a command. Is anyway to do that?

**Comment by bpasero** [comment]
@lsps9150414 there is Cmd+1 (2, 3) to focus one of the three groups. To maximise the active editor you can use the command:

![image](https://user-images.githubusercontent.com/900690/29259331-62c4d28e-80c2-11e7-9f70-19d0ed080d33.png)

**Comment by lsps9150414** [comment]
@bpasero Thanks! Is there anyway to toggle between maximized and the state before it?

**Comment by bpasero** [comment]
@lsps9150414 there is this command:

![image](https://user-images.githubusercontent.com/900690/29303812-c676ccce-818f-11e7-929d-da03b6f7e411.png)
