### ISSUE TITLE
Git:spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by Lpbzzz** [Microsoft/vscode#32440]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
react-native-react-redux|EQu|1.1.0
auto-rename-tag|for|0.0.14
react-component|jer|1.0.0
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.1.7
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
react-beautify|tai|0.3.0
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1
vscode-react-native|vsm|0.4.1
ReactSnippets|xab|1.4.0
html-css-class-completion|Zig|1.8.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.git add .  (in disk:E)
2.can not cancel add    For reason:Git:spawn ENAMETOOLONG
3.How Can I cancel the "git add ."?   Now,my VS Code “Source code management“ have too many items

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Delete `E:\.git` and don't try to do that again.
