### ISSUE TITLE
Request a detailed diff between old and new Emmet

### ISSUE THREAD

**Issue by xlighting2017** [Microsoft/vscode#32442]
- VSCode Version: 1.15 x64
- OS Version: Win10 x64

Steps to Reproduce:
1. try some old working Emmet and find out it breaks;
2. search in the github issues and go through several pages to know "it's not working in the new emmet"

Here is the issue:
the new Emmet is now replacing the old one,  and people has no choice to fallback to the old behavior.

can we have a detailed list of "what has been changed/ not working now but works before/not possible before but now OK with new" ?

without such detailed list, people will always comes up with "surprises", “Tab no longer works” #32243  is one example, and  the   “$@- is broken” #31916 is another.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Thanks a valid ask @xlighting2017 

I'll work on a list soon

**Comment by ramya-rao-a** [comment]
@xlighting2017 I have added a new page under docs for all things Emmet in VS Code. This describes how to use Emmet, what settings are available, known issues and future work

https://code.visualstudio.com/docs/editor/emmet

Hope this helps.

**Comment by jens1o** [comment]
@ramya-rao-a maybe you can add a reference to your blog link, because this also explains the situation?

**Comment by ramya-rao-a** [comment]
@jens1o The blog is linked from the docs as well. But here it is for reference

[Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
