### ISSUE TITLE
Support "loaded scripts" for chrome-debug

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32445]
- Part 1, hook it up to 'chrome'-type sessions. We can do this by 
  - Changing loadedScripts.ts to listen for new 'chrome' sessions - it might be weird that a built-in extension has this link to an optional extension, although it's a special case
  - Or moving that code to vscode-chrome-debug-core, where node-debug2 can configure it for 'node' and 'node2' sessions, and vscode-chrome-debug can configure its own copy for 'chrome' sessions.

- Part 2, improve it to display URLs correctly, by parsing the protocol/hostname if present and combining it into a single row
![image](https://user-images.githubusercontent.com/323878/29259121-c46a0246-8074-11e7-974e-7ad289508219.png)

**Comment by weinand** [comment]
If we add loadedScripts support to the DAP, we should consider to move the loaded scripts explorer into VS Code (either in core or as a builtin extension). The primary reason for doing the loaded scripts explorer as an extension was for creating useful Debug API.

Having said that, I think we should not spend effort on moving copies of it to vscode-chrome-debug-core. I suggest that we just enable it for "chrome" and introduce the 'weird' dependency for now.

I will fix the display for URLs and then enable the loaded scripts explorer for "chrome".

**Comment by roblourens** [comment]
Oh right, that makes sense. Sounds good, thanks.

**Comment by roblourens** [comment]
Verifier: breakpoints aren't working in these files, so just verify that they appear... https://github.com/Microsoft/vscode-chrome-debug/issues/487
