### ISSUE TITLE
PHP code annotation color 

### ISSUE THREAD

**Issue by xiyuanpingtadi** [Microsoft/vscode#32449]
- VSCode Version:1.15.0
- OS Version:OS X EI capitan (10.11.6)

if write '_array()_'  Normal code will become comment code
![image](https://user-images.githubusercontent.com/13147676/29261212-fbc7390c-8100-11e7-808a-f14559537cba.png)

without '_()_' is right
![image](https://user-images.githubusercontent.com/13147676/29261318-7384646a-8101-11e7-9d84-1a2a0d628f3b.png)

**Comment by jens1o** [comment]
That's potential a known bug. This will be fixed then with 1.16.

https://github.com/atom/language-php/issues/245

I try to reproduce later with Insiders, when that test won't fail, it has been fixed already.

**Comment by jens1o** [comment]
Yes, that has been fixed already.
![image](https://user-images.githubusercontent.com/11234139/29266801-5d66578a-80e6-11e7-8b3c-366dafe8d4fe.png)

**Comment by roblourens** [comment]
Thanks @jens1o
