### ISSUE TITLE
File fast find in file explorer

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#32457]
It would be useful to have a fast find feature in the files explorer. For example node_modules can be a very long list of files to scroll through

The usual key sequence triggered search would be just fine. Eg as In windows explorer

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by SteveALee** [comment]
Apologies. I did search but obviously did not use the correct terms.

 Would help if you closed as a duplicate and gave the other issue. Number.

Thanks.
