### ISSUE TITLE
Evaluate based hover

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3245]
- [x] Win @alexandrudima 
- [x] OS X @joaomoreno
- [x] Linux @aeschli 

For node debugging when a user hover over a word we **evaluate** that word instead of traversing the variables scopes as we did previously. Due to this, user hovering over a function call can potentially **mutate** the program state and might be dangerous. We have not yet decided if we will ship this and are looking for feedback. Verify:
* hovering **works as before** and you can inspect both complex and primitive values
* be **creative** and by hovering try to trigger a function call which could mutate the program state

**Comment by alexandrudima** [comment]
I would not ship with this experiment.
