### ISSUE TITLE
Point line for all type format files

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#32458]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.3.9600
----
Hi, Please add point line for all type format files. It is very good if you add window or area to show all lines pointed for each files.
Please see this gif:
![a](https://user-images.githubusercontent.com/5067331/29266189-1277933e-80f9-11e7-8f2d-42777a3187d6.gif)

Thanks
 @bpasero @rebornix @alexandrudima

**Comment by rebornix** [comment]
I'm sorry I didn't figure what this feature is about from your gif, can you elaborate more? Thanks in advance!

**Comment by miladghiravani** [comment]
@rebornix In other editors, you can add red point or red circle by click on each line number. Please see this:
![ashampoo_snap_2017 08 16_12h52m25s_001_](https://user-images.githubusercontent.com/5067331/29354147-cd7c8962-8281-11e7-8df1-67575b48024d.png)

In vscode I can do this only on .js and .php but on .html and .css format files I can't do this.

**And another idea:**
It is very good if you add window or area to show all lines pointed for each files. For example in file abc.php, I red circle lines 30, 459, 1324. But I can't see all line red circle on one window or area.

**Example:**
----------------------------
|  All line with red circles |
| -------------------------  |
| File abc.php                   |
|    > line 30                     |
|    > line 459                   |
|    > line 1324                 |
|                                       |
| File style.css                   |
|    > line 45                     |
|    > line 159                   |
|    > line 820                   |
----------------------------
On all another code editors, this feature not exist.

Thx

**Comment by isidorn** [comment]
You can add breakpoints in any other file if you install the coresponding debugger or by using the option 
"debug.allowBreakpointsEverywhere": true,
