### ISSUE TITLE
Output window shows tofu characters 

### ISSUE THREAD

**Issue by ashutosh1211** [Microsoft/vscode#32450]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
code-runner|for|0.6.33
beautify|Hoo|1.1.1
rest-client|hum|0.15.1
docthis|joe|0.4.7
vscode-insertdatestring|jsy|2.1.0
perl-debug|mor|0.2.3
mssql|ms-|1.1.0
csharp|ms-|1.12.0
team|ms-|1.121.1
debugger-for-chrome|msj|3.1.7
code-settings-sync|Sha|2.8.2
stylelint|shi|0.28.0
autoimport|ste|1.2.2
vscode-react-native|vsm|0.4.1
vscode-todo-highlight|way|0.5.8
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Through .net core build configuration i added webpack build step. and when webpack is printing its progress it is showing tofu characters

![image](https://user-images.githubusercontent.com/4639147/29261669-67a9459c-80ee-11e7-911c-e535a7d27b5b.png)

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/3550
