### ISSUE TITLE
html error

### ISSUE THREAD

**Issue by silverpeng** [Microsoft/vscode#32451]
<img width="1333" alt="qq20170814-154829 2x" src="https://user-images.githubusercontent.com/25680922/29262676-35412c86-8108-11e7-9eb5-5c3c4f3ce115.png">

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please explain what the screenshot is showing. Is this log output? Where does this output comes from?

**Comment by silverpeng** [comment]
n the HTML file, when open, there will be active file does not link any stylesheets to, and then in the terminal output of error, please look at the picture I uploaded

**Comment by silverpeng** [comment]
In the HTML file, when open, there will be active file does not link any stylesheets to, and then in the terminal output of error, please look at the picture I uploaded

**Comment by aeschli** [comment]
Duplicate of #32059.
