### ISSUE TITLE
VS Code Slow Start

### ISSUE THREAD

**Issue by devendrapratap** [Microsoft/vscode#32454]
- VSCode Version: <code>Code - Insiders 1.15.0-insider (6feff11ed03402cf77e04e74e13c55529fdb4d09, 2017-08-04T17:43:56.658Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)</code>
- Memory (System): <code>8.00GB (0.06GB free)</code>
- Memory (Process): <code>207.88MB working set (0.00MB peak, 169.96MB private, 79.64MB shared)</code>
- Load (avg): <code>2, 2, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|1482|
|main|app.isReady => window.loadUrl()|1483|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2767|
|renderer|require(workbench.main.js)|5043|
|renderer|create extension host => extensions onReady()|14153|
|renderer|restore viewlet|5313|
|renderer|restore editor view state|5189|
|renderer|overall workbench load|12218|
|main + renderer|start => extensions ready|29939|
|main + renderer|start => workbench ready|27951|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`0569_main.cpuprofile.txt`
-`0569_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Please attach those profile files. Thanks
