### ISSUE TITLE
"Ctrl + U" undo last cursor operation, scroll bar don't scroll synchronously

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode#32466]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
githistory|don|0.2.3
vscode-html-css|ecm|0.1.7
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.6.1
vue|liu|0.1.5
vetur|oct|0.9.3
vue-beautify|pea|2.0.4
java|red|0.8.0
code-settings-sync|Sha|2.8.2
stylelint|shi|0.28.0
JavaScriptSnippets|xab|1.4.1

**Comment by weinand** [comment]
Does this issue occur when launching VS Code with extensions disabled (`code --disable-extensions`) ?

**Comment by Jancat** [comment]
@weinand 
My extensions are enable.

I had recorded the steps with screenshots.
1. First , the cursor in line 480
![1](https://user-images.githubusercontent.com/11827786/29274273-de4f782e-8139-11e7-85ec-c7f0467eb16f.png)

2. Then, the curson in line 177
![2](https://user-images.githubusercontent.com/11827786/29274275-df1ee7ee-8139-11e7-98ed-a8b5b9d81b61.png)

3. Finally, I click `Ctrl + U` and the cursor in the previous line 480, but the scroll bar had not scroll.
![3](https://user-images.githubusercontent.com/11827786/29274277-e0d31894-8139-11e7-87ab-2abb3929aea6.png)

**Comment by Jancat** [comment]
And the `Ctrl + U` don't support cross editor tab

**Comment by yume-chan** [comment]
cursorUndo is designed to not cross-tab.

Go Back/Go Forward will cross tabs, but it will omit small selection changes.
