### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by KillingSpark** [Microsoft/vscode#32463]
Hey there,
I took on the challenge to install vscode on void linux from source. The installation doesn't list all dependencies I needed. These were pkg-config, libXScrnSaver, gconfmm. Now its working, with the only exception being the integrated terminal. Would be neat if you could update the installation notes.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/13089, https://github.com/Microsoft/vscode/issues/17142
