### ISSUE TITLE
Code changed when app switches

### ISSUE THREAD

**Issue by UncleVic** [Microsoft/vscode#32462]
- VSCode Version:  1.15.0
- OS Version: macOS 10.12.6

What does it mean:
https://youtu.be/UYawt-5v078

**Comment by weinand** [comment]
Sorry, I do not understand the problem by watching the screencast.
Please provide steps in English.

**Comment by UncleVic** [comment]
When I'm pressing Cmd+Tab, sometimes I have changed text in active editor window.

**Comment by weinand** [comment]
Do you see this problem even when running VS Code with extensions disabled (`--disable-extensions`)?
