### ISSUE TITLE
Trying to install ms-vscode.csharp extension from command line fires exception

### ISSUE THREAD

**Issue by bertrandpsi** [Microsoft/vscode#32468]
C:\Users\WIN-PRO-TEST>code --install-extension ms-vscode.csharp
Found 'ms-vscode.csharp' in the marketplace.
Installing...
(node:3108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): TypeError: this._state.then is not a function
(node:3108) DeprecationWarning: Unhandled promise rejections are deprecated. In
the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.

- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
docomment|k--|0.0.17
csharp|ms-|1.12.0
team|ms-|1.121.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bertrandpsi** [comment]
Seems the same bug as https://github.com/Microsoft/vscode/issues/32464

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/32464
