### ISSUE TITLE
What happened with beautiful emmet!?

### ISSUE THREAD

**Issue by kolyaraketa** [Microsoft/vscode#32469]
- VSCode Version: 1.15.0
- OS Version: Windows 10

Steps to Reproduce:

1. Creaty css file
2. Use Emmet 

Reproduces without extensions: Yes

![screencast-2017-08-14](https://user-images.githubusercontent.com/14001747/29269776-0a5ebd64-80fc-11e7-82a7-9639cb596fa8.gif)

I very disappointed, because this code editor right now useless for me :( What happening? Any suggestions?

**Comment by charles8xu** [comment]
@kolyaraketa you can find the same issue here https://github.com/Microsoft/vscode/issues/32243

**Comment by kolyaraketa** [comment]
Solution:
1. Install insiders build
2. `"emmet.triggerExpansionOnTab": true,`
3. ```"[sass]": {
			"editor.quickSuggestions": false
		},```
