### ISSUE TITLE
C# Omnisharp (Intellisense) not running / working since last update

### ISSUE THREAD

**Issue by tonimarquez84** [Microsoft/vscode#32465]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.2
csharp|ms-|1.12.0

---

Steps to Reproduce:

1. Running a C# solution from Unity3D. Intellisense is not working.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file this issue against the C# extension.
