### ISSUE TITLE
Scrolling in diff view with non-default theme is laggy

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#32479]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.1.0
quokka-vscode|Wal|1.0.48
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
prettier-vscode|esb|0.22.1
Go|luk|0.6.63
debugger-for-chrome|msj|3.1.7
vetur|oct|0.9.3
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
language-stylus|sys|1.7.3
vim|vsc|0.9.0

(4 theme extensions excluded)

---

With Nord theme: https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code

![scroll](https://user-images.githubusercontent.com/4033249/29275537-78ed01c8-80d9-11e7-8cd5-4218582e19c1.gif)

Default theme scrolling:

![scroll2](https://user-images.githubusercontent.com/4033249/29275785-495a7c14-80da-11e7-9374-44bbd7f8767b.gif)

So this only happens if I'm using a custom theme and in diff view. Diff view works fine in default theme.

@rebornix

**Comment by rebornix** [comment]
@octref did you use the touchpad or mouse middle button? I'm using Nord as well but didn't see this issue (can't reproduce as well). Did you see the lag with every file in the diff view?

**Comment by octref** [comment]
Touchpad on macOS.
Not seeing it on every file. Only diff of files with a lot of additions / deletions.
