### ISSUE TITLE
There is no shortcut to open the integrated terminal on Linux

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#32473]
Hello,

There is no shortcut to open the integrated terminal on Linux.
 
- VSCode Version: 1.15
- OS Version: Ubuntu

**Comment by Tyriar** [comment]
ctrl+` opens the integrated terminal on Ubuntu. You can customize this using the keybindings system https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by Paviluf** [comment]
I'm sorry I should have been more precise. I know that there should be that shortcut ctrl+` to open integrated terminal on Ubuntu but I tried it and it doesn't work (tried ctrl+² too for my locale (fr) ). I looked for it in the keyboard shortcuts and keybindings and it doesn't exist !

**Comment by Tyriar** [comment]
@Paviluf what shows up when you search for "Toggle Terminal" in keybindings?

![image](https://user-images.githubusercontent.com/2193314/29285853-d572bfc2-80e4-11e7-9f2c-cbcbb6e25a05.png)

**Comment by Paviluf** [comment]
Here it is on Fedora (at home, the ubuntu one is at work)

![screenshot from 2017-08-14 22-56-31](https://user-images.githubusercontent.com/17159065/29291506-1fec0fe0-8144-11e7-9c1c-9ebabfbee8b7.png)

**Comment by Tyriar** [comment]
Looks like there is not shortcut by default for your locale, you can add one by hovering the row and hitting the pencil button on the left.

**Comment by Paviluf** [comment]
Thanks that work. Shouldn't it be working out of the box, even with french locale ?

**Comment by Tyriar** [comment]
Seems to work fine on Ubuntu, at least when I launch using `code --locale=fr`:

![image](https://user-images.githubusercontent.com/2193314/29438812-15e57c58-836e-11e7-8d88-736325ebc73c.png)

Let me know if your work Ubuntu machine is fine.

**Comment by Paviluf** [comment]
The shortcut isn't present even with --locale=fr on my Ubuntu computer.

**Comment by Tyriar** [comment]
Weird.. I assume you have fr set up as the system language? Maybe that's the issue. Moving to @alexandrudima as it seems to relate to the keybindings system.

**Comment by Paviluf** [comment]
Well on Fedora the "language" is set to english but the "formats" to french. However on Ubuntu it's full french.

**Comment by alexandrudima** [comment]
Our out-of-the-box keybinding for toggle terminal is ``ctrl + ` ``, which is interpreted as `ctrl` + the key combination that produces `` ` ``. If for your keyboard layout no key combination produces `` ` ``, then the toggle terminal command is unbound by default.

Simply click on the edit pencil next to the command and bind it to a keybinding.

**Comment by Paviluf** [comment]
You should reopen because there is a **`** on my keyboard.

**Comment by alexandrudima** [comment]
@Paviluf ok. Can you then please do the following:

* open an editor
* run F1 > Developer: Inspect key mappings
* save as a file and upload here

I can then take a look and see if our logic is flawed.

**Comment by Paviluf** [comment]
Here it is from my Chromebook.

[keyborad.txt](https://github.com/Microsoft/vscode/files/1344014/keyborad.txt)

![image](https://user-images.githubusercontent.com/17159065/31012921-f9846994-a513-11e7-95cc-9fc9a3fdfb81.png)

**Comment by alexandrudima** [comment]
@Paviluf

```
|       HW Code combination      |  Key  |
|                Ctrl+Alt+Digit7 |   `   |
```

```
"Digit7": {
	"value": "è",
	"withShift": "7",
	"withAltGr": "`",
	"withShiftAltGr": "⅞"
},
```

Indeed, `` ` `` can be produced by pressing `AltGr` + `[Digit7]`. i.e. `ctrl+alt+[Digit7]`. The relevant rows are:

This means that our out of the box keybinding for ``ctrl+` `` would map to `ctrl+ctrl+alt+[Digit7]`. Since this is not expressible in terms of modifiers (it would require some form of modifier chording which AFAIK no editor supports), the keybinding for toggle integrated terminal is not bound out of the box.

Does that make sense?

**Comment by Paviluf** [comment]
That make sense. Just note that only `AltGr + [Digit7]` produce ``` ` ``` not `ctrl+alt+[Digit7]`.

**Comment by alexandrudima** [comment]
`AltGr` is `Ctrl+Alt`
`AltGr+[Digit7]` is `Ctrl+Alt+[Digit7]`.

**Comment by alexandrudima** [comment]
Since I believe our algorithm for mapping default keybindings to the current keyboard layout is correct, I will close this issue for now. 

Please upvote #1240 which is about that we ship with keyboard layout optimized default keybindings.

**Comment by Paviluf** [comment]
>  AltGr+[Digit7] is Ctrl+Alt+[Digit7]

Maybe but if I press it, nothing happen.
