### ISSUE TITLE
Screen reading

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3247]
**Issue:** #3058
**Assignees:**

- [x] Windows @stevencl  
- [x] Windows @weinand 

**Details:**

* Download and install or simply run once (there is away to run without installing) NVDA from http://www.nvaccess.org/
* If you want to avoid hearing it: right click on the tray icon and choose Tools > Speech Viewer.  Optionally stop the voice via tray icon and Preferences > Synthesizer > No speech
* Edit your settings (user or workspace) and set `editor.experimentalScreenReader: true`.
* Validate the setting is turned on by going to an editor and pressing `Alt+F1`

**Learn basic NVDA operations**
* tray icon > Help > Commands Quick Reference
* AFAIK NVDA works in different modes and you need to be aware in what mode you are:
 * using `Tab` and cursor keys to navigate is ok, but you should be aware and perhaps try out other navigation options.
 * NVDA has another conceptual "review cursor" besides the normal one (e.g. allows for reading other parts of text without moving the editor cursor)
 * when in one of the browse modes, it is possible that keypresses are eaten up by NVDA for navigation purposes, so you should at least at a minimum understand that there are these modes and that you switch between them,
 * toggle browse/focus modes `NVDA+space`
 * Review modes: next via `NVDA+numpad7`, prev via `NVDA+numpad1`.
 * look at commands in the Object Navigation section, they allow to navigate the accessibility tree.
 * look at commands in the Reviewing Text section: e.g. move to previous word (`numpad4`), report current word (`numpad5`), move to next word (`numpad6`), move to previous character (`numpad1`), report current character (`numpad2`), move to next character (`numpad3`).
 * I am not sure what commands are most important or most used.

**Try to do a programming task such as fix a bug**
* We want to also discover what is not screen reader accessible, but also validate what we have done explicitly:
 * the text is paged for the screen reader in 10 line increments. Try to move the cursor around and see if the screen reader reads lines or letters. Also do this around 10 lines multiples to find out how NVDA handles the "page" switching.
 * errors should be announced when using `F8` and `Shift-F8`
 * the hover should be announced when using `Ctrl+K Ctrl+I`

**Comment by weinand** [comment]
Since I'm neither a keyboard nor a Windows user, it is incredibly difficult for me to test this since I had to lookup and map almost every keyboard shortcut (and this on a Swiss-German keyboard!). So I did not find any new issues but now I'm even more impressed that some user are able to use this...
