### ISSUE TITLE
Indent Guides for Python - End the lines when the function declaration is finished

### ISSUE THREAD

**Issue by alchermd** [Microsoft/vscode#32474]
See image below

![](http://i.imgur.com/kSnCGgh.png)

**Comment by rebornix** [comment]
our current indent guide is indentation based, which is context/language wise.

**Comment by affanshahid** [comment]
This is one of my biggest peeves right now, sublime handles this perfectly. I think PR https://github.com/Microsoft/vscode/pull/26258 fixes this

**Comment by affanshahid** [comment]
Also need to handle formatting situations like the following:
![2017-08-24 14_39_09-productcontrollertest java project-yavin visual studio code](https://user-images.githubusercontent.com/17955210/29660282-5c6d0490-88da-11e7-9fb9-44e6d071957e.png)

A simple check for empty lines would do in this case

**Comment by jkyeung** [comment]
Well, this rule is better expressed as: "Dedent one level (preferably ignoring continuation lines) whenever `return` is encountered." If the `return` is nested, you shouldn't dedent all the way out of the function. Similarly, it is generally the case that you want to dedent one level upon `pass`.

**Comment by alexandrudima** [comment]
This is now working as expected on master

![image](https://user-images.githubusercontent.com/5047891/32042294-582c77a6-ba37-11e7-850f-174fb54165c5.png)

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode/issues/32474#issuecomment-324587087 is still the same, please file a new issue if you think this should be corrected. Verified otherwise.
