### ISSUE TITLE
Color picker: Broken pixel along vertical axis

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#32470]
Version: Insiders b73b7df

![image](https://user-images.githubusercontent.com/2239563/29270091-bb26fff2-80fd-11e7-8a1b-b381a4e1816d.png)

See the screenshot above. Interestingly, not all color values produce this result (e.g. `#68c3a3` paints fine).

**Comment by joaomoreno** [comment]
He's alive!!! Do you like the new horizontal picker bars? :1st_place_medal: 

Funny broken pixel, though. Does it always reproduce on your machine? No steps, just open it?

**Comment by michelkaporin** [comment]
Haha, I am here! Yeah, they're awesome, like them 👍 Didn't have a time for a final touch on them, was focused on finishing off the core implementation 😄 

It always reproduces, no steps, just pick the  `#333333` color.

Also I've looked at your code refactorings around the picker, you made it really sleek 👍 nice work! 🔢

**Comment by joaomoreno** [comment]
Strange:

![image](https://user-images.githubusercontent.com/22350/29273170-78faab0a-8103-11e7-91f4-e303a6f3e90c.png)

**Comment by michelkaporin** [comment]
@joaomoreno really strange, and the code remained the same as I've seen.

If I tweak `window.zoomLevel` to values different to default, it starts to appear fine. 

_OS: Windows
Resolution: 1920x1080
Scaling: 100%_

**Comment by rebornix** [comment]
It took me a while to find the way to reproduce (before that I even wanted to ask you to check whether your screen is broken for a second ...). 

* No reproduce on macOS
* Reproduce on Windows 10, Scaling 100% and Zoom Level 0. If we change the Scaling or Zoom Level, the green line is gone.
* Chrome Dev Tools doesn't have this problem.

**Comment by rebornix** [comment]
After exposing the API to monaco, I can reproduce this issue in Chrome on macOS always with no scale. Once I scale the webpage, the green line is one.

![image](https://user-images.githubusercontent.com/876920/29639734-a51fdb10-8810-11e7-8558-ee9433ba3002.png)

This is probably a blocker for releasing to Monaco Editor @joaomoreno . @alexandrudima any idea of how this magic green dots happen in canvas?

**Comment by rebornix** [comment]
It only happens in Chrome (macOS 100% Zoom and Windows 10 Hdpi 100% Scale), didn't see any issue in Safari and Edge. Tried several ways to troubleshoot but didn't see what we did wrong. A workaround here is adding a middle stop point to the linear gradient, which makes Chromium canvas rendering correct.

**Comment by joaomoreno** [comment]
Their constant position might give us a clue on why they happen... although I got none. 😕

**Comment by rebornix** [comment]
The workaround seems good, so visually this issue is gone. I'd like to put it into backlog and one day I can know the root cause of this canvas problem.
