### ISSUE TITLE
Debugging: preLaunchTask window behavior not user-friendly

### ISSUE THREAD

**Issue by Rukenshia** [Microsoft/vscode#32477]
- VSCode Version: Code - Insiders 1.16.0-insider (b73b7df1290d0fe66ca8b8060743711a327af622, 2017-08-14T05:16:07.578Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-babel-coloring|dza|0.0.4
beautify|Hoo|1.1.1
cpptools|ms-|0.12.2
debugger-for-chrome|msj|3.1.7
vetur|oct|0.9.3
vscode-icons|rob|7.12.0
rust|rus|0.2.1
debug|web|0.21.2

(1 theme extensions excluded)

---

I wanted to start the pretty neat debugging functionality for my Rust code. I'm using the Native Debug extension to debug my executable, but need to run my `build` task before to ensure that I always have the most recent version of my code built. This ends up in a kind of unfriendly behavior for me because the window always switches to "Terminal" when running the build task but does not switch back to "Debug Console" afterwards. I think it makes a lot of sense to either switch to the Debug Console if I was on there before when the `preLaunchTask` finished with exit status 0 or do not switch to the Terminal at all.

Steps to Reproduce:

1. Configure a Build Task
2. Configure a Debug Task with `preLaunchTask` set to the Build Task
3. Switch to the "Debug Console"
4. Start Debugging (F5)
5. notice how the window goes to "Terminal" but does not switch back to Debug Console.

*Demonstration*: [Screen Recording (1.06MB)](https://in.fkn.space/i/2017-08-14_16-03-36-9a7ac213.mp4)

Reproduces without extensions: No (no debugger available for me)

**Comment by weinand** [comment]
Configure your build task to be "silent" e.g. with a "presentation" section which has an attribute "reveal" set to "silent" or "never".
