### ISSUE TITLE
Emmet doesn't expand my abbreviation

### ISSUE THREAD

**Issue by mrg0lden** [Microsoft/vscode#32482]
- VSCode Version: 1.15 x64
- OS Version: Win 10 Pro x64

Steps to Reproduce:

1. I use "div.column.is-2[data-num=$]*6>div.circled>img+(.circled>p{استمع لي})" and then try to expand it with edit menu's option "Emmet: expand..."
2. I get an error "Running the contributed command:'emmet.expandAbbreviation' failed." or I get only a single "p" tag expanded.

Reproduces without extensions: Yes/No
Yes

**Comment by timknight** [comment]
Hi @mrg0lden, I played with this in my editor and I think the issue comes down to assigning the index number to a data attribute without quoting the value. If you put quotes around the $ it should work. So instead of:

```
div.column.is-2[data-num=$]*6>div.circled>img+(.circled>p{استمع لي})
```

Try

```
div.column.is-2[data-num="$"]*6>div.circled>img+(.circled>p{استمع لي})
```

**Comment by ramya-rao-a** [comment]
Thanks @timknight! I would have taken a while to get to the bottom of that.

@mrg0lden Try the suggestion by @timknight and your abbreviation should expand as expected
