### ISSUE TITLE
Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET project directory 

### ISSUE THREAD

**Issue by GuruprasadYellappaK** [Microsoft/vscode#32485]
Hello,

I have an issue with debugging .NET console and web application from Visual studio code and when i run with debug getting the below Error. I am not sure, what is missing. even after reinstalling again the same issue continues.

**Run 'Debug: Download .NET Core Debugger' in the Command Palette or open a .NET project directory** 

below is the dotnet --info result
--------------------------------
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Kindly suggest.

Regards,
Guruprasad

**Comment by waacton** [comment]
I have the same issue, and the same dotnet --info result.

In my case I assume it also coincides with not being able to install the dependencies properly:

```
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (21928 KB) ....................	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.23.2.zip' (21928 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (39217 KB) ....................	Retrying from 'https://vsdebugger.blob.core.windows.net/coreclr-debug-1-12-5/coreclr-debug-win7-x64.zip' (39217 KB) .................... Done!

Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
Failed at stage: installPackages
Error: invalid central directory file header signature: 0xb5110011

Finished
```
Any thoughts on what's going on here?

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1712

**Comment by GuruprasadYellappaK** [comment]
Thank you for the suggestion.
I am getting the issue when i open the mvc core project from VS code. (after 2 -3 seconds).
I am not using any http proxy but I tryed with downloading the same Manually and kept under .bin and .debugger folder of extension. so luck.

Please suggest.
