### ISSUE TITLE
Make snippet highlights themeable

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32484]
- VSCode Version: 1.15
- OS Version: win7x64

Can someone tell, what setting is responsible for highlighting the "next label" in the "snippet mode"?

Cause, for example, I have this snippet "setAttribute(\"${1:attr}\", \"${2:value}\");$0"
but if you will look at the screenshot, I think you won't say that there is any highlighting on **"value"**, it's extra faded.

![image](https://user-images.githubusercontent.com/24613274/29277572-b63dd94e-811a-11e7-91e0-7ba737125203.png)

**Comment by jrieken** [comment]
This is now `snippetPlaceholder.brackground` and `snippetFinalPlaceholder.border`. 

/cc @bpasero in his role as color name police

**Comment by bpasero** [comment]
Sounds good to me, also @aeschli for editor-color name police

**Comment by bpasero** [comment]
@aeschli actually it seems to me many colors are in the editor. namespace, not sure what you rule is here:

![image](https://user-images.githubusercontent.com/900690/45631589-7b87e180-ba9b-11e8-9acc-3bffc12d5d80.png)

`editor.snippetPlaceholderBackground` seems a bit long to me, but so far we have no snippet category top level for theme colors.

**Comment by aeschli** [comment]
Definitely needs to be in the editor namespace. It's another highlight color, so I'd have that in the name too.

`editor.snippetPlaceholderHighlightBackground`
`editor.snippetTabStopForeground`

Maybe just call it
`editor.snippetHighlightBackground` ?

Normally the highlight colors also have a border variant, used in high contrast, but available for any theme.

**Comment by jrieken** [comment]
ok, the colors are now

* `editor.snippetTabstopHighlightBackground`
* `editor.snippetTabstopHighlightBorder`
* `editor.snippetFinalTabstopHighlightBackground`
* `editor.snippetFinalTabstopHighlightBorder`
