### ISSUE TITLE
Version 1.16 "Release Notes" has bad GitHub query

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#32488]
- VSCode Version: Code - Insiders 1.16.0-insider (b73b7df1290d0fe66ca8b8060743711a327af622, 2017-08-14T05:16:07.578Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Install new Insiders build.
2. Look at "Release Notes: 1.16.0-insider".
3. Click "Closed bugs" or "Closed feature requests".

Expected: GitHub is launched with results.
Actual: GitHub is launched with "No results matched your search." because the milestone query isn't in quotes. Repros in Chrome and Edge.

**Comment by jens1o** [comment]
works for me here: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_16.md

**Comment by martellaj** [comment]
![badreleasenotes](https://user-images.githubusercontent.com/1019478/29282613-4d592ec0-80d8-11e7-85cd-83890e416460.gif)

**Comment by jens1o** [comment]
Okay, now I can reproduce. But when using the documentation links, it's working fine. Looks like vscode is stripping something...

**Comment by mjbvz** [comment]
I confirmed this issue on Windows using Firefox and Chrome. Edge seems to work and I also haven't been able to repo this on mac

**Comment by mjbvz** [comment]
This may be an electron issue: https://github.com/electron/electron/issues/10285

@gregvanl Let's see if we can work around this by changing the url's encoding in the release notes

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1136

**Comment by gregvanl** [comment]
I think I can fix this by using the milestone number in the query.
