### ISSUE TITLE
High Contrast support

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3248]
**Issue:** #2711 #3184
**Assignees:**

- [x] Windows @alexandrudima 
- [x] OS X @isidorn 
- [x] Linux @joaomoreno

**Details:**
- For each platform, can you enable the "High Contrast" theme?
- Select some chunks of code.  Is any part of the selection illegible (e.g. light text on the white selection overlay)?
- Click on a variable in your code.  Verify word matching is visible.
- Use "Find" to find something.  Verify word matching is visible.
- Toggle on/off each viewlet from the activity bar.  Do any icons disappear or look weird?

**Comment by joaomoreno** [comment]
@bgashler1 Don't forget to add details of this test plan item, for us to test tomorrow.

**Comment by bgashler1** [comment]
Thanks @joaomoreno. Will do this right now.
