### ISSUE TITLE
Listing snippet prefixes and descriptions

### ISSUE THREAD

**Issue by jamesgecko** [Microsoft/vscode#32498]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0

---

I'd like a way to list all the snippets that are available for the current file. I have to either look up snippet definition files on github or use [_Trigger Suggest_](https://code.visualstudio.com/docs/languages/javascript#_snippets) and skim through the prefixes with other auto-complete entries mixed in.

This is particularly necessary for non-intuitive snippet prefixes added by extensions; the `Contributions` page does not include snippets.

**Comment by ramya-rao-a** [comment]
Have you tried the `Insert Snippet` command? It shows a list of all applicable snippets.
For example below is what I get in a typescript file

![image](https://user-images.githubusercontent.com/16890566/29285098-19952fa8-80e2-11e7-9384-9ed13fc75c82.png)

**Comment by jamesgecko** [comment]
Doh! This is exactly what I was looking for. Thanks! 😄

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding! :)
