### ISSUE TITLE
JSX syntax highlighting breaks when using default values for destructred parameter

### ISSUE THREAD

**Issue by chipit24** [Microsoft/vscode#32493]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.3.0
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
RelativePath|jak|1.0.0
cpptools|ms-|0.12.2
final-newline|sam|0.3.2
highlight-matching-tag|vin|0.4.4

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Create a new file and set the language mode to "JavaScript React"
2. Add the following code:
```
const button = ({
  className
}) => (
  <div className={className}>
    Click me!
  </div>
);
```
3. Add a default value for `className` in the destructured object parameter:
```
const button = ({
  className = 'button'
}) => (
  <div className={className}>
    Click me!
  </div>
);
```
4. After this change, observe that JSX syntax highlighting is broken.
![jsx-syntax-broken](https://user-images.githubusercontent.com/7561061/29282042-51328700-80ef-11e7-9714-0e04b056fe49.gif)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is already tracked upstream by https://github.com/Microsoft/TypeScript-TmLanguage/issues/499
