### ISSUE TITLE
Using Alt + ` shortcut will unintentionally input a ` character in current file

### ISSUE THREAD

**Issue by gyf304** [Microsoft/vscode#32492]
- VSCode Version: 1.15.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Assign a shortcut to Alt + `
2. Press Alt + ` in editor window.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
It's triggered by the IME you are using (usually the US English does support accent). You may want to avoid the conflicts between IME and your keybindings.
