### ISSUE TITLE
PHP Multi-line use statement breaks syntax highlighting

### ISSUE THREAD

**Issue by lagbox** [Microsoft/vscode#32495]
- VSCode Version: 1.15.0  and  previous version
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Add a multi-line use statement to a class.

Reproduces without extensions: Yes

Incorrect higlighting:
![broken-multi-line-use](https://user-images.githubusercontent.com/3752215/29282918-9fbeb08a-80f2-11e7-9c48-e44c70f04c2e.png)

Correct highlighting:
![correct-use-highlighting](https://user-images.githubusercontent.com/3752215/29282927-a80563ba-80f2-11e7-8f09-53a9495c1a7f.png)

Broken off from #30448

**Comment by jens1o** [comment]
FYI: This hasn't been fixed in Insiders version.

cc @roblourens

**Comment by roblourens** [comment]
Filed upstream: https://github.com/atom/language-php/issues/255

**Comment by roblourens** [comment]
Fixed with grammar update https://github.com/Microsoft/vscode/commit/44aa7c2f08057faf00207e770d9e19d387989c28#diff-d29ab7189a781bbc9879dd8484315ed5

**Comment by jens1o** [comment]
Thanks!
