### ISSUE TITLE
Extension Cannot be installed

### ISSUE THREAD

**Issue by AnvarPK** [Microsoft/vscode#325]
i am trying to install an extension, but while typing extention , there is showing 'No commands matching' messege
![screenshot from 2015-11-20 14 20 01](https://cloud.githubusercontent.com/assets/10231751/11295495/d5c1b3c0-8f91-11e5-88f6-c0fa41abfdad.png)

**Comment by joaomoreno** [comment]
What do you read in `About > Version`?

**Comment by AnvarPK** [comment]
![screenshot from 2015-11-24 10 14 09](https://cloud.githubusercontent.com/assets/10231751/11358029/26659742-9294-11e5-954b-bf0f9437253a.png)

**Comment by joaomoreno** [comment]
Extensions are only supported since version `0.10.1`.

**Comment by AnvarPK** [comment]
thank you..
