### ISSUE TITLE
Slack "team" for vscode extensions

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#32509]
Now that slack allows for permanent (though revocable) invite links it would be great if there was a "dedicated" slack for extension authors and of course the vscode team should they be willing ;)

I currently have one setup explicitly for [GitLens](https://join.slack.com/t/vscode-gitlens/shared_invite/MjIxOTgxNDE3NzM0LTE1MDE2Nzk1MTgtMjkwMmZjMzcxNQ), but I think it would be great to have more community around the extensions in a common place. Although if the vscode team isn't interested in "owning" this but other extension authors think this is a good idea, I could rename & repurpose the GitLens slack into a general vscode extensions one.

Just throwing this out there :)

**Comment by cleidigh** [comment]
One for contributors as well?

**Comment by eamodio** [comment]
Yeah -- in general a slack for the greater vscode code-contributing community

**Comment by jens1o** [comment]
Sounds awesome!

**Comment by eamodio** [comment]
Anyone have more thoughts on this?

**Comment by seanmcbreen** [comment]
Hi,

Not a bad idea - we do however have a Gitter https://gitter.im/Microsoft/vscode that could serve the same purpose.  The core VS Code team at times does show up in there - but no real SLA.  

From the team perspective our largest challenge is focusing on coding the product - so we really have tried to focus most of our interactions via GH Issues so we respond fast (I admit I was slow here :)).  Over time we have chosen to close additional channels e.g. User Voice.

So my question would be, could the Gitter work for this? (both for builders @eamodio and for contributors @cleidigh).

That way we have one less channel and done divide people up.  More extension builders in there would rock as more people could help each other out.

Sean

**Comment by cleidigh** [comment]
@seanmcbreen 
@eamodio 
I agree about not having multiple places.  I as I assume other people can spend a fair amount of time monitoring VSC issues both to help answer questions (whxen I feel appropriate) as well as to work on 
main code contributions (have not done extensions yet).

Sometimes I would like to post/discuss with fellow contributors work in progress.  Many times I don't think it's appropriate to post questions on the main issues thread for all the obvious reasons mentioned above.  StackOverflow doesn't fit the bill either since it's large and not  focused on code alone.

Having a forum specifically devoted to outside coders main contributors or extension developers would be useful.  I was unaware of the existence the Gitter site.  Having not used this can you have tags to help find relevant issues and possibly direct members ability to see issues they could possibly comment on?

**Comment by eamodio** [comment]
I would also agree about not having multiple places, but at the same time I don't feel the current gitter addresses the desires above.

My biggest issue with gitter (or at least as it is currently setup -- not as familiar with gitter as compared to slack) is that it is a single channel, that is just *vscode*, so there are lots of conversations that are focused on using the product vs development (i.e. contributors or extension developers) which drove me out of even paying attention to it. 

Next, is probably just my UX aversion to gitter vs slack (gitter just feels awkward, clunky, notification management is lacking, etc). I'm also a part of quite a few slack teams (dotnet, omnisharp, etc), so additional slack teams is easier to manage (self serving I know -- but slack imo is just a FAR better tool).

Another aspect of slack (maybe gitter supports this) that I really like, is being able easily have dedicated channels (contributors, extension development, even specific extensions, etc) so everything isn't all thrust into a single stream. And by allowing the community to be able to create their own channels, allows the whole thing to grow (organically) as well -- into a larger hub for all things in the vscode ecosystem. Finally, being able to spin up collaboration channels (public or private) on-demand with a group of people for a period of time is imo very valuable.

**Comment by cleidigh** [comment]
@eamodio 
Hmm...
At the risk of sounding inconsistent, you make some good points.  I have essentially zero experience
with gitter , however, I completely agree about the UX !  It is not at all friendly especially for keyboard only users.  The aspect of categorization on Slackware definitely sounds like a plus.

Could things be migrated to Slackware?  Is the gitter site very entrenched?

**Comment by eamodio** [comment]
@seanmcbreen any more thoughts on this?

**Comment by seanmcbreen** [comment]
This is a good conversation - a few points:
1. I think having a structured place for the community to connect with each other is a great idea
2. I'd love for this to be owned by the community - focused on peer-to-peer support
      - I'm sure members of the team will join but I'm very keen to keep us as focused as possible / not add an additional set of core team expectations

Reading through the comments I agree that Gitter does not seam as rich and if you guys are keen to lead the charge then I say go for it :)

So @eamodio do we think we could set something up but be clear it's community lead?  Once up and running and stabilized I'm sure we can help promote it.  

I can also add it into my Slack and see how things are going (we use Slack as well :)).

Sean

**Comment by eamodio** [comment]
@seanmcbreen So having it community owned/lead/etc I think is a great thing. I can certainly rename my `vscode-gitlens` slack to something else -- maybe `vscode-community-dev`?

The biggest issue in my mind on using Slack is that the free version only supports 10K messages before they start falling off -- so *if* this became popular you could lose message history quite quickly.

**Comment by seanmcbreen** [comment]
That's certainly true - but perhaps that's OK - should we try it and see how much of an issue it becomes?

**Comment by eamodio** [comment]
I'm good with that -- so is `vscode-community-dev.slack.com` a reasonable team url? I don't ❤️ it but don't have anything better on the tip of my tongue.

**Comment by cleidigh** [comment]
sounds good to me.
sign me up ! :+1:

**Comment by jens1o** [comment]
sign me up too, please 🗡

**Comment by eamodio** [comment]
OK, I've converted my GitLen slack into a broader [**Visual Studio Code Development Community** slack](https://join.slack.com/t/vscode-dev-community/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY).

Let me know what you all think.

**Comment by cleidigh** [comment]
@eamodio 
@seanmcbreen 
I am in...
let me know how can help.
FWIW
can I suggest we steal and post the Microsoft code of conduct and a little more description 
how the slack is supposed to work?

**Comment by Almenon** [comment]
> My biggest issue with gitter (or at least as it is currently setup?) is that it is a single channel -- just vscode. 

?? There is a add room button.  It doesn't work when I click on it, though - I think an admin has to do it.

**Comment by egamma** [comment]
Closing - @eamodio has created a slack channel for extension authors.
