### ISSUE TITLE
 Running the contributed command:'emmet.expandAbbreviation' failed.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32507]
Issue Id: <b>4e3ff632-6472-1e2c-630e-07fc6671b45f</b><br /><br />*Versions* <br />- 1.15.0<br />-  6feff11ed03402cf77e04e74e13c55529fdb4d09<br />-  2c3e2c291c515619f64e7c9cddf14c565b7f3d92<br />-  f980319f5c4bf3f0878c5fcc68a3aa2795119c57<br />-  dd7adcc1615d86c33e139b677f5adf69f1c2cf91<br />-  1af52c0470d6f445966b5c8a3065233b34303d9a<br />-  c26f8a312b9aa792f45a7baf06e31576470236a8<br />*Stack* <br />Error: Running the contributed command:'emmet.expandAbbreviation' failed.<br />[/vs/workbench/api/node/extHostCommands.ts#L134:32](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/api/node/extHostCommands.ts#L134:32)<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />

**Comment by miaoihan** [comment]
I met the same problem as you.

**Comment by ramya-rao-a** [comment]
@miaoihan Can you give an example of how you arrived at this error? Are you on VS Code 1.15.0 version and did you bind `tab` key to `editor.emmet.action.expandAbbreviation`?

In VS Code 1.15.0, you shouldn't bind `tab` key to the emmet command. If you do want to use tab for emmet, use the latest Insiders from https://code.visualstudio.com/insiders or wait for VS Code 1.15.1 which will release in a few days.

**Comment by imakou** [comment]
My situation is that `expandAbbreviation` works for few times then doesn't work anymore.
It seems very unstable to trigger the `expandAbbreviation` and it's very annoying to me nowadays.
However, I hope VScode can be better and better, but it just takes time to be.

**Comment by stefangabos** [comment]
Below is a video of my situation. Note that I set Emmet to activate on CTRL+. instead of default keyboard shortcut, as seen in the video. When called outside quotes, everything works as expected. The error message appears when trying to call Emmet from inside quotes.

![video](https://media.giphy.com/media/3o6vXMRcHWHxhQJTji/giphy.gif)

**Comment by ramya-rao-a** [comment]
@stefangabos I am not able to repro. Which version of VS Code are you using?

![jsonemmet](https://user-images.githubusercontent.com/16890566/29500206-763d6388-85d3-11e7-9890-2f8b940d7bb9.gif)

**Comment by stefangabos** [comment]
I was running the one previous to 1.15.1. Since 1.15.1 the problem is gone, but emmet is not working for me in json files anymore. In the files I usually work with this problem doesn't occur anymore. This can be closed, as far as I am concerned. Thank you!

**Comment by ramya-rao-a** [comment]
Thanks @stefangabos 

If you do want emmet in json files as well use the `emmet.includeLanguages` setting.
Read more on it at https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration

**Comment by ramya-rao-a** [comment]
@imakou @miaoihan Please share repro steps for the error you are seeing
