### ISSUE TITLE
Suggest should not force tokenization in very large files

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#32508]
Related to https://github.com/Microsoft/vscode/issues/21564 and https://github.com/Microsoft/vscode/issues/30181 .

When we open a large file (or whose tokenization takes a long time), any feature that requires accurate token information runs `model.forceTokenization` and it blocks the UI, including

* [x] Paste (Auto Indent checks token info)
* [x] Enter (Enter rules or Indentation)
* [x] Type 
   * [x] (Auto Indent or electric chars)
   * [x] Suggest (Suggestion and Snippet)
   * [ ] Others ?

Paste/Enter/Type relies on indentation/enter rules, right now I skipped the smart features if the tokenization is not yet ready for selections. But speaking of suggestions, some suggestion provider (like snippet) requires language id at position, some (quickSuggestions) requires token info, these two force tokenization for selection, which would lead to UI blocking.

Enable quick suggestion and snippet (default)

![typeblock](https://user-images.githubusercontent.com/876920/29296426-09b35b64-810f-11e7-8b9b-3979dd19e94e.gif)
 
Disable both of them by `"editor.quickSuggestions": false, "editor.snippetSuggestions": "none"`

![typenoblock](https://user-images.githubusercontent.com/876920/29296444-3bb45f14-810f-11e7-8bf2-09a334b2cffb.gif)

Any component that requires token/language info can lead to the UI blocking when users open a large file and modify real quick. As we increase the file size limit for tokenization, this may happen more often. cc @alexandrudima @jrieken @ramya-rao-a

**Comment by alexandrudima** [comment]
@rebornix I've taken care of quite a few of the code paths, here's one which we might want to tackle:

https://github.com/Microsoft/vscode/blob/cc5e2fb18d6288fb70a626ea93ae150293c56fe7/src/vs/editor/contrib/linesOperations/common/moveLinesCommand.ts#L264

**Comment by rebornix** [comment]
@alexandrudima thanks!
