### ISSUE TITLE
Ability to not to show the outdated extensions badge

### ISSUE THREAD

**Issue by tinmanjk** [microsoft/vscode#32505]
VSCode version: 1.13.1

![image](https://user-images.githubusercontent.com/22401916/29551351-f8118be4-871a-11e7-92de-1d917ce87a3b.png)
A feature request: option to switch off the notifier (in screenshot above - 3) of the available updates for extensions.

Thanks

**Comment by tinmanjk** [comment]
Thanks for the screenshot.
Sadly, I have disabled auto-updating. It works as expected.
What I wish for is to not see the count of extensions there are updates for.
![image](https://user-images.githubusercontent.com/22401916/29551351-f8118be4-871a-11e7-92de-1d917ce87a3b.png)

**Comment by sandy081** [comment]
Hmm there is no option to hide that. You can open a new issue or update this issue with this detail

**Comment by tinmanjk** [comment]
@sandy081 
I've edited my first post. Can you please reopen the issue as the title of the issue seems correct and I do not want to open redundant issues.
