### ISSUE TITLE
Command editor.emmet.action.matchingPair not found on macOS

### ISSUE THREAD

**Issue by dmrutherford** [Microsoft/vscode#32501]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
hg|mrc|1.1.5
vscode-apache|mrm|1.1.1

---

Keyboard shortcut command `editor.emmet.action.matchingPair` fails using v1.15.0 on macOS. I have added the same shortcut on a Windows machine and it appears to work fine. Error message:

>[warn] command 'editor.emmet.action.matchingPair' not found

The command is available and works normally from the command palette ('Emmet: Go to Matching Pair').

Steps to Reproduce:

1. Be using macOS
2. Add a custom keyboard shortcut with command `editor.emmet.action.matchingPair`
3. Attempt to use that shortcut in the Editor

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@dmrutherford I get the same error in Windows as well.

The command is `editor.emmet.action.matchTag` and not `editor.emmet.action.matchingPair`
