### ISSUE TITLE
copy line with spaces

### ISSUE THREAD

**Issue by lock1995** [Microsoft/vscode#32515]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.9.3

When I use Command/Ctrl+C to copy a line code(no selected), the behind of copied line will have some redundant spaces.
---

Steps to Reproduce:

1. Command/Ctrl+C
2. Command/Ctrl+V

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@lock1995 can you provide a gif to help troubleshoot?

**Comment by lock1995** [comment]
![issue12](https://user-images.githubusercontent.com/11797672/29304593-6ddc113c-81c6-11e7-97e8-b7c6d089ba19.gif)

**Comment by alexandrudima** [comment]
Those are not pasted. The tab is inserted when pressing Enter, and then the text is pasted before the tab that gets inserted when pressing Enter.

**Comment by alexandrudima** [comment]
Duplicate of #15118
