### ISSUE TITLE
The option editor.autoIndent makes VSCode behave strangely.

### ISSUE THREAD

**Issue by fenying** [Microsoft/vscode#32513]
- VSCode Version: v1.15.0
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Open a (typescript) file like:

    ```ts
    let test: string[] = [

        "a",

        "b",

        "c"
    ];
    ```

2. Copy following text

    ```ts
    ,

        "b",

        "c"
    ```

3. Paste it after `"c"`, we will get:

    ```ts
    const OK_CMDS: string[] = [

        "a",

        "b",

        "c",
        // Here is 4 spaces
            "b", // Here is 4 spaces more indentation
        // Here is 4 spaces
            "c" // Here is 4 spaces more indentation
    ];
    ```

And before v1.15.0, we should get

```ts
const OK_CMDS: string[] = [

    "a",

    "b",

    "c",
// here is no spaces
    "b", // here should be only 4 spaces as indentation
// here is no spaces
    "c" // here should be only 4 spaces as indentation
];
```

I search for **indent** in settings, and found the option `editor.autoIndent`. I set it to `false` and then all behavior is well, as v1.14.x did. Thus I wonder, what does it mean? This option makes VSCode behave so strangely as Eclipse does.

Reproduces without extensions: Yes

**Comment by starbuck3000** [comment]
Confirmed also with PHP coding. 
Copy pasting the following code:
if($a === $b)
    return(true);

results in both wrong indentation when typing and when copy-pasting. It worked well prior to this update.

**Comment by rebornix** [comment]
![32513](https://user-images.githubusercontent.com/876920/45786117-e3693400-bc23-11e8-8038-03da4890c688.gif)

This issue no longer exists in latest.

**Comment by fenying** [comment]
@rebornix Well thanks. This is a pretty useful feature.
