### ISSUE TITLE
How can I solve this problem without knowing why I often start git.exe automatically and then take up a few G of memory space?

### ISSUE THREAD

**Issue by BYicon** [Microsoft/vscode#32519]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
VS Code uses git.exe for its git features. It will call `git status` often to be up to date with the state of the repository. You can disable this integration with `git.enabled = false`.
