### ISSUE TITLE
signature and suggestion window layout

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#32511]
- VSCode Version: 1.16-Insider
- OS Version: macOS

Steps to Reproduce:

This is a duplication of https://github.com/Microsoft/monaco-editor/issues/524 actually but I'd like to raise it here for more feedback. A fixed signature help and a floating suggestion window makes typing pretty hard.

![paramater-suggestion](https://user-images.githubusercontent.com/876920/29298302-a7132a4a-811b-11e7-87a1-4049da279775.gif)

Reproduces without extensions: Yes/No

cc @ramya-rao-a

**Comment by KamasamaK** [comment]
This looks related to #14668

**Comment by ramya-rao-a** [comment]
@rebornix Are you saying that the signature help and suggest window shouldn't appear at the same time ?

**Comment by rebornix** [comment]
@ramya-rao-a I'm wondering whether the suggestion window can be smatter when the hover exists, for example not covering the signature help when it exists.

**Comment by ramya-rao-a** [comment]
@rebornix The suggestion widget is not aware of any other editors. Its up to the editor to layout multiple widgets in a way so as to not overlap.

See https://github.com/Microsoft/monaco-editor/issues/524#issuecomment-321543392 

On the other hand, if you are saying that suggest widget should not appear when signature help is shown, that is more do-able I believe
