### ISSUE TITLE
不知道为什么经常自动启动 git.exe， 然后占用几个G的内存空间 ，该怎么解决这个问题？

### ISSUE THREAD

**Issue by BYicon** [Microsoft/vscode#32518]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
sublime-keybindings|ms-|2.9.1
sass-indented|rob|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kzhui125** [comment]
占用空间的是git.exe?
自动启动 git.exe和占用几个G的空间是两码事。不一定有因果关系。

VSCode的是集成git的，当然会调用git.exe

**Comment by BYicon** [comment]
我说的是占用几个G的运行内存，才用这个开发 已经解决来 谢谢回答
