### ISSUE TITLE
Explorer view scroll broken when adding a new file

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#32510]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
vscode-eslint|dba|1.2.11
python|don|0.7.0
gitlens|eam|4.3.3
tslint|eg2|0.17.0
Go|luk|0.6.63
debugger-for-chrome|msj|3.1.7
sourcegraph|sou|1.0.9
vim|vsc|0.9.0

---

Steps to reproduce:

1. Open a project with enough files to scroll in the explorer view (e.g. Microsoft/vscode)
2. In the explorer viewlet, right click on src/vs/editor/common/services and select "New file"
3. Do not type anything in; instead, scroll down until it is out of view.
4. Start scrolling up.

Expected: You should be able to scroll the input field back into view.

Actual: lots of visual artifacts.

Reproduces without extensions: Yes

![screen recording 2017-08-14 at 05 42 pm](https://user-images.githubusercontent.com/754768/29297806-53d4c058-8118-11e7-824c-84312a4fc8d8.gif)

**Comment by bpasero** [comment]
@joaomoreno cool, this one has repro steps!

**Comment by joaomoreno** [comment]
Epic!

**Comment by kzhui125** [comment]
maybe https://github.com/Microsoft/vscode/issues/22269

**Comment by joaomoreno** [comment]
Oh, for sure.
