### ISSUE TITLE
VS code error

### ISSUE THREAD

**Issue by katerinaLu** [Microsoft/vscode#32514]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
tortoise-svn-for-vscode|cds|0.1.1
ionic3-vs-ionView-snippets|dan|1.0.1
jquerysnippets|don|0.0.1
tslint|eg2|0.17.0
sublime-keybindings|ms-|2.9.1
cordova-tools|vsm|1.2.9

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Please provide more information. Screenshots, steps to reproduce...
