### ISSUE TITLE
A new feature requirement: The tab head of the text editor for the default file of a module

### ISSUE THREAD

**Issue by stuartZhang** [Microsoft/vscode#32512]
Hello guys, 

I'm a Web Developer. Given the ES 6 Module (for Web page) and Rust Module (for Web Assembly), the entry file name under the module directory is senseless. For example, "index.js" is for ES; and "mod.rs" is for Rust.

If either of them is displayed in the Tab head of the text editor, I won't acquire sufficient information about what file I'm editing. It's frustrating to see a lot of "index.js" tab heads above the text editor, because the file name can't embody what it really is.

As a result, I suggest that the directory name of the "index.js" and "mod.rs" file is displayed in the tab head, which is helpful to the editors.

**Comment by stuartZhang** [comment]
It's better to make the default module entry file configurable. For example, the default module entry file is "index.bbjs" in my project. "bbjs" means the Babel Javascript.

**Comment by bpasero** [comment]
@stuartZhang to clarify what you want, is it to always show the parent folder of a file next to its name in the tab?

**Comment by stuartZhang** [comment]
Yes, it is. If the JS file name is "index.js" or the Rust file name is "mod.rs", the editor Tab head is titled with the directory name. I hope the file name is configurable in the workspace settings, because the module-default file is "index.bbjs" in my local project.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12965
