### ISSUE TITLE
Global Keybindings - input loses focus after changing keyboard language

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32516]
- VSCode Version: 1.15
- OS Version: win7x64

Input field in "Global Keybindings" loses focus after changing keyboard language (for me it's **Ctrl+Shift**)

So, all I do in the GIF - just pressing Ctrl+Shift:
![globalkeybindings input loses focus](https://user-images.githubusercontent.com/24613274/29300369-b9234eba-817d-11e7-8a71-ca12d1ae098f.gif)

PS: this bug "works" **only** if you will select (just click) on any keybinding in the list.

**Comment by sandy081** [comment]
@user3323 I am not able to reproduce this. Focus remains in search box. Can you please check if there `ctrl+shift` is bound to some command in your Code?
