### ISSUE TITLE
[Debug] Unexpected end of JSON input. Stopping the debug adapter.

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#32517]
- VSCode Version: 1.15.0-insider
- OS Version: Windows 10

We're developing java debugger. And we want to send the stdout message of the target debuggee console to vscode debug console using OutputEvent. Sometimes when the output messages are not utf8 characters but Chinese characters, DA will terminate with message box `Unexpected end of JSON input. Stopping the debug adapter.`, but send the `disconnect` request at a new debug session. This would cause the old debugger not to know when to release it's jvm resource.

See the DA pipeline below:
[[RESPONSE]]
{"event":"output","body":{"category":"stdout","output":"涓浗\r\n","type":"output"},"seq":31,"type":"event"}
**[DA terminated current debug session's communication channel and popup a message box "Unexpected end of JSON input. Stopping the debug adapter."]**
**[After that, DA will launch a new debug session with a disconnect request]**
[REQUEST]
{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":23}
[[RESPONSE]]
{"success":true,"request_seq":23,"command":"disconnect","body":{},"seq":1,"type":"response"}

Expected:
DA should be able to handle the non utf8 chars in OutputEvent. At least, even if it throws exception and terminated unexpectedly, it should send the last `disconnect` request at the end of current debug session instead of new debug session. That would give the debugger a chance to clean up its resource.

**Comment by weinand** [comment]
1. A JSON containing non-Unicode characters is not a valid JSON and can result in parsing errors. So I suggest not to send non-Unicode characters. BTW, this applies not only to the Debug Protocol but to the Language Protocol as well.

2. If the "disconnect" goes to the wrong session, this is a bug.

**Comment by testforstephen** [comment]
@weinand Thanks for your reply. 
YES, the "disconnect" goes to the wrong session, you could fix this bug first. 
And i'll revisit the non-Unicode issue to see if the debugger has the knowledge to resolve it.

**Comment by isidorn** [comment]
@testforstephen can you please file this bug with proper steps to reproduce the wrong disconnect session.
A good hint on how to do this is
1. Create a github repository which we can simply clone and see this issue
2. Or try reproducing this issue with a simple javascript multi session debug, as if it is visible in java it should also be visible in this scenario

I tried finding the issue just by looking at code but could not find a potential suspect.
You can also do a reveiw https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1
