### ISSUE TITLE
Chording Escape key breaks Find and Autocomplete

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/vscode#32520]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.8
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.3
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
auto-rename-tag|for|0.0.14
contextualduplicate|laf|0.2.0
debugger-for-chrome|msj|3.1.7
vscode-subword-navigation|ow|1.1.5
Align|ste|0.2.0
rewrap|stk|1.4.2
clang-format|xav|1.5.0
vscode-proto3|zxh|0.1.2

(3 theme extensions excluded)

---

**Steps to Reproduce:**

1. Use `escape` in a chorded keybinding:
```json
    {
        "key": "escape s",
        "command": "workbench.action.showCommands"
    },
    {
        "key": "escape a",
        "command": "workbench.action.quickOpen"
    },
```
2. Open the Find widget (Cmd+F) or trigger autocomplete (type `window.addEv` in a JavaScript file)
3. Hit the Escape key to close it.

**Expected Results:**
The autocomplete or find widget closes.

**Actual Results:**
Status bar says `(Escape) was pressed; waiting for second key of chord`.

**Note**:
I map Caps to Escape, so I can chord Caps+A and Caps+S to common commands.  I've used the same workflow in Sublime for a long time, and I've never had this problem.

Reproduces without extensions: **Yes**

**Comment by appsforartists** [comment]
Adding this line to each command fixed it:
```json
        "when": "!findWidgetVisible && !suggestWidgetVisible"
```

Though I'd hope there'd be an easier way.  Is there a way to see which ContextKeys are currently active (to set `when` correctly)?  How about a meta `widgetVisible`, so I don't have to manually enumerate each one in my `when`?

**Comment by appsforartists** [comment]
This also doesn't solve the problem that `escape` can't exit from multiple cursors if it's also chorded.

**Comment by alexandrudima** [comment]
When you write a rule for "escape" in the user keybindings.json, it will shadow and take precedence over all other bindings for escape, unless the `when` condition is *weaker*:

It doesn't help that `escape` is one of our most popular keybindings at 22 rules defined for it.

What you want is doable, although not nice:

#### step 1: grab all escape keybindings that define things for escape and duplicate them in your `keybindings.json`:
```
{ "key": "escape escape",         "command": "workbench.action.exitZenMode",
                                     "when": "inZenMode" },
{ "key": "escape",                "command": "closeReferenceSearchEditor",
                                     "when": "inReferenceSearchEditor && !config.editor.stablePeek" },
{ "key": "escape",                "command": "cancelSelection",
                                     "when": "editorHasSelection && editorTextFocus" },
{ "key": "escape",                "command": "removeSecondaryCursors",
                                     "when": "editorHasMultipleSelections && editorTextFocus" },
{ "key": "escape",                "command": "editor.action.webvieweditor.hideFind",
                                     "when": "webviewEditorFocus" },
{ "key": "escape",                "command": "closeFindWidget",
                                     "when": "editorFocus && findWidgetVisible" },
{ "key": "escape",                "command": "closeBreakpointWidget",
                                     "when": "breakpointWidgetVisible && editorFocus" },
{ "key": "escape",                "command": "leaveEditorMessage",
                                     "when": "messageVisible" },
{ "key": "escape",                "command": "leaveSnippet",
                                     "when": "editorTextFocus && inSnippetMode" },
{ "key": "escape",                "command": "closeMarkersNavigation",
                                     "when": "editorFocus && markersNavigationVisible" },
{ "key": "escape",                "command": "closeReferenceSearch",
                                     "when": "referenceSearchVisible && !config.editor.stablePeek" },
{ "key": "escape",                "command": "closeParameterHints",
                                     "when": "editorTextFocus && parameterHintsVisible" },
{ "key": "escape",                "command": "hideSuggestWidget",
                                     "when": "editorTextFocus && suggestWidgetVisible" },
{ "key": "escape",                "command": "cancelRenameInput",
                                     "when": "editorFocus && renameInputVisible" },
{ "key": "escape",                "command": "closeAccessibilityHelp",
                                     "when": "accessibilityHelpWidgetVisible && editorFocus" },
{ "key": "escape",                "command": "closeReplaceInFilesWidget",
                                     "when": "replaceInputBoxFocus && searchViewletVisible" },
{ "key": "escape",                "command": "list.clear",
                                     "when": "listFocus" },
{ "key": "escape",                "command": "search.action.cancel",
                                     "when": "listFocus && searchViewletVisible" },
{ "key": "escape",                "command": "workbench.action.closeMessages",
                                     "when": "globalMessageVisible" },
{ "key": "escape",                "command": "workbench.action.closeQuickOpen",
                                     "when": "inQuickOpen" },
{ "key": "escape",                "command": "workbench.action.hideInterfaceOverview",
                                     "when": "interfaceOverviewVisible" },
{ "key": "escape",                "command": "workbench.action.terminal.hideFindWidget",
                                     "when": "terminalFindWidgetVisible && terminalFocus" }
```

#### step2: find out where in the list you would like your chords to work (i.e. precedence).
I would argue that would be at the top. So you can paste:
```
    {
        "key": "escape s",
        "command": "workbench.action.showCommands"
    },
    {
        "key": "escape a",
        "command": "workbench.action.quickOpen"
    }
```

I'm sorry if this is not what you were expecting, but this is one way to make every existing escape work and *insert rules at the top* (least precedence).
