### ISSUE TITLE
Regex replace doesn't work if match line is more than 999

### ISSUE THREAD

**Issue by NishiokaTakeo** [Microsoft/vscode#32522]
Hi there.
I am having issue that vscode doesn't replace using regex properly if matched line is over the 999.
Also only first line is replaced even if I pressed "Replace All"

- VSCode Version: 1.14.2
- OS Version: Windows8

Steps to Reproduce:

1.create random lines more than 999. in my case I have 6567 lines I want to replace.
2.replace using Regex. my case is that I tried to add ",'" all lines.   target "^" , replace ",'"
3. then Press "Replace All". 

![screenshot_081517_010827_pm](https://user-images.githubusercontent.com/2171088/29303103-b99de578-81bc-11e7-94d7-1efa746ccc3a.jpg)

That happens is only first line is replaced .
![screenshot_081517_011303_pm](https://user-images.githubusercontent.com/2171088/29303162-531d0d78-81bd-11e7-8066-e64a5853c566.jpg)

then keep press "Replace All" then....

![screenshot_081517_011347_pm](https://user-images.githubusercontent.com/2171088/29303173-6d5afad8-81bd-11e7-8098-9128327ef6c6.jpg)

**Comment by ToMakeSense** [comment]
This issue does exist, I have a workaround:
ctrl+F with regex `^.{1,}$` then `Alt+Enter` to select all the matches, then press `Home` key to the begin of each line, then input `,'`. done!

**Comment by Kimi-Arthur** [comment]
Happens to me too. But doesn't require regex? Normal replacement may fail in a similar way.

**Comment by 9130khz** [comment]
I run into the same issue on macOS

VSC v1.15.1 
macOS 10.12.6
