### ISSUE TITLE
Code Spelling: ~100 instances of "focussed" in code base 

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#32521]
While working on the simple find widget I came across many instances of the misspelling. "focussed"
Most are in context key object names, however, there is one public facing instance, a context key
value that would appear in when clauses for key bindings.
I'm sure you do not want a PR for one hundred files ;-)

From: findController.ts

export const CONTEXT_FIND_WIDGET_VISIBLE = new RawContextKey<boolean>('findWidgetVisible', false);
export const CONTEXT_FIND_WIDGET_NOT_VISIBLE: ContextKeyExpr = CONTEXT_FIND_WIDGET_VISIBLE.toNegated();
export const CONTEXT_FIND_INPUT_FOCUSSED = new RawContextKey<boolean>('findInputFocussed', false);

**Comment by rebornix** [comment]
IMHO both focussed and focused are okay but I'm pretty sure @roblourens @Tyriar etc know English better than me.

**Comment by roblourens** [comment]
I had to look it up, but apparently `focussed` is the british spelling. I wouldn't want to change the name of a context key, so we might as well leave it.

**Comment by cleidigh** [comment]
Just not crazy that it's a singular exception to all the other when clauses, but I understand the reluctance to change it.

**Comment by Tyriar** [comment]
I came across that and thought it was a mistake. It's certainly not used in Australia, based on this graph we should change it imo:

https://books.google.com/ngrams/graph?content=focused%2C+focussed&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cfocused%3B%2Cc0%3B.t1%3B%2Cfocussed%3B%2Cc0

**Comment by roblourens** [comment]
We can't change the context key `findInputFocussed` unless we add a new one, deprecate the old one, get rid of it later... doesn't seem worth it. Might as well change everything else though?

**Comment by alexandrudima** [comment]
:+1: 

Let's leave `findInputFocussed` as it is (since it is "API").

I've renamed focussed -> focused in the find widget and the editor.

Most of the remaining usages belong I believe to @bpasero and @isidorn . They should decide what they want to do :)

**Comment by cleidigh** [comment]
@bpasero 
There are still quite a few code instances left.  I will do a PR for these, but it will touch about twenty five files.
I will leave the context key alone as discussed above.

**Comment by cleidigh** [comment]
Addressed with PR #32904
