### ISSUE TITLE
Add when clause support to command icons

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#32526]
- VSCode Version: Code - Insiders 1.16.0-insider (b73b7df1290d0fe66ca8b8060743711a327af622, 2017-08-14T05:16:07.578Z)
- OS Version: Windows_NT x64 10.0.16257
---

Currently it is difficult to "simulate" the changing of an icon of a command. Since the api doesn't allow changing the icon directly, it has to be simulated by using extra commands and contexts.

For example, in GitLens I've recently added a new "feature" to show a sort of progress indicator on the `gitlens.toggleFileBlame` command while I am computing the blame annotations (the icon pulses), and then once completed I change the blame icon to be in an "on" state to indicate that the blame is active (the icon turns orange).

To accomplish this I have to create 3 commands, the original `gitlens.toggleFileBlame` command for the `off` state, `gitlens.computingFileAnnotations` command which is a no-op for the `progress` state, and `gitlens.clearFileAnnotations` for the `on` state. You can see definition of 3 commands [here](https://github.com/eamodio/vscode-gitlens/blob/00cdd2e375e77c5cf5339d84c0287be30a80971b/package.json#L812-L838). And the usage of those commands can be seen [here](https://github.com/eamodio/vscode-gitlens/blob/00cdd2e375e77c5cf5339d84c0287be30a80971b/package.json#L1253-L1268)

Instead of having 3 command for this, I would much rather have been able to have a single command:
```json
{
    "command": "gitlens.toggleFileBlame",
    "title": "Toggle File Blame Annotations",
    "category": "GitLens",
    "icon": {
        "dark": "images/dark/git-icon.svg",
        "light": "images/light/git-icon.svg",
        "when": !gitlens:annotationStatus
    },
    "icon": {
        "dark": "images/dark/git-icon-progress.svg",
        "light": "images/light/git-icon-progress.svg",
        "when": gitlens:annotationStatus == computing
    },
    "icon": {
        "dark": "images/dark/git-icon-orange.svg",
        "light": "images/light/git-icon-orange.svg",
        "when": gitlens:annotationStatus == computed
    }
}
```

That way I wouldn't need to switch the commands out in each menu (currently I'm being lazy and only doing it on the editor/title navigation), the keyboard shortcuts show up as expect, and I don't need to register extra commands that I don't actually need.

**Comment by jrieken** [comment]
Don't you just want an "active" icon?

**Comment by eamodio** [comment]
@jrieken I think that could work for some cases -- certainly for progress. But for something like a on/off toggle state would you really want a long running promise to deal with that (for example, GitLens blame -- its a state more than a long running command)?

Here is gif of what I mean. As you can see the normal state is white, and then while the blame is being computed it pulses, and when the computation is complete and the blame annotations are shown it stays orange. And if the blame annotations get canceled (toggled off) it will go back to white.

![command-icon](https://user-images.githubusercontent.com/641685/29319403-ef0c7d52-81a1-11e7-8e04-55c8659281b7.gif)

**Comment by eamodio** [comment]
I think this should get closed in favor of https://github.com/Microsoft/vscode/issues/34048

Thoughts?
