### ISSUE TITLE
[xml] Highlight problem

### ISSUE THREAD

**Issue by tradzero** [Microsoft/vscode#32527]
Binaryify/OneDark-Pro#136

- VSCode Version:1.15.0 X64
- OS Version:Windows 10 15063

Steps to Reproduce:

1.comment a line

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/13845447/29305360-f0c890a8-81ca-11e7-8a0e-400431bdcef6.png)

file code is [here](https://github.com/laravel/laravel/blob/master/phpunit.xml)

**Comment by aeschli** [comment]
This is not valid XML, as confirmed by http://www.xmlvalidation.com/.
The comment can not be inside attributes.
