### ISSUE TITLE
PyinitModule 'requests.packages' has no 'urllib3' member

### ISSUE THREAD

**Issue by AxisRay** [Microsoft/vscode#32528]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
jquerysnippets|don|0.0.1
python|don|0.7.0
beautify|Hoo|1.1.1
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
debugger-for-chrome|msj|3.1.7
vscode-autohotkey|sle|0.2.1
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/6546326/29305958-d4c3300e-81cd-11e7-89ca-091d4ca7839e.png)
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1168

**Comment by weinand** [comment]
Please file Python issues against Python extension (since VS Code does not provide Python functionality out of the box).
