### ISSUE TITLE
Search in file: current item not always highlighted when cycling with F3

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#32535]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
gherkin-indent|Ara|2.0.0
vscode-bad-code-highlighter|bha|0.1.6
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
vscode-turtle|fei|1.0.30
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
format-indent|Kas|1.3.0
phpmd|lin|1.1.4
vscode-apache|mrm|1.1.1
vscode-duplicate|mrm|1.2.0
oracle-plsql|myc|1.0.3
selectline-statusbar|tom|0.0.2
gitblame|wad|2.1.0
twig|wha|1.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. search for text in file with multiple matches
2. when cycling through the result via F3, the current item is not highlighted with editor.findMatchBackground
3) when cycling with the arrows in find widget, the highlight works fine

Reproduces without extensions: hard to tell, because some time after restarting even with extensions it seems to work ok, but after a while, I observed the issue again.

**Comment by PunchyRascal** [comment]
In this animation I am cycling (F3 and Shift + F3) the found word "config", but it only gets highlighted properly sometimes.

![f3-unhighlighted gif](https://user-images.githubusercontent.com/821272/29519715-aae84c82-867e-11e7-9bf9-2855816541ca.gif)

**Comment by alexandrudima** [comment]
@PunchyRascal This might be due to using non-transparent custom colors.
