### ISSUE TITLE
Emmet doesn't work in jsx

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#32534]
- VSCode Version:1.15.0
- OS Version:Windows 7

Steps to Reproduce:

1.In React's render method, write html tag and press tab, it just a tab, emmet doesn't work
2.and the indent of the tag also has problem

Reproduces without extensions: Yes

**Comment by ZhangPuXi** [comment]
I found it doesn't work in html file too. And specifically, write div*1 and press tab, it works. write div and press tab, it doesn't work.

**Comment by nealoke** [comment]
See this issue #32243 , basically they broke emmet :D

**Comment by ramya-rao-a** [comment]
Set `emmet.triggerExpansionOnTab` in the latest Insiders (https://code.visualstudio.com/insiders)  or
Wait for July Recovery Build (1.15.1) which will be out tomorrow

**Comment by rohmanhm** [comment]
This is happened with tsx files too.
