### ISSUE TITLE
No longer possible to drop a folder into Code to open folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32537]
This is a regression from the Electron update and seems to be https://github.com/electron/electron/issues/9840

I would argue that this blocks an Electron update unless we find a workaround. The problem is that during drag we no longer can find out if the dragged resource is a file or folder. Only when dropping it seems we can find out.

We need to know if a folder is dropped vs file to show different drop feedback:
* dropping a folder shows a full drop feedback over the entire window to indicate that you open the folder
* dropping a file is showing individual feedback depending on where you drop (over the explorer: copy file into the folder, over the editor: open the folder)

/cc @kieferrm @Tyriar @roblourens

**Comment by Tyriar** [comment]
Dropping a folder on Windows appears that it's handled as a file

The behavior is a little odd in the terminal as well, adding a `/` at the start:

![image](https://user-images.githubusercontent.com/2193314/29424004-be3c2924-8332-11e7-9d0f-8f24a88f019b.png)

**Comment by Tyriar** [comment]
Ah that's probably unrelated.

**Comment by Tyriar** [comment]
We could take this as an opportunity to improve the current behavior, especially since the new `DataTransferItem` behavior is to spec. Dragging a folder could just show the drop area of a file but handle the folder in multiple ways.

- Dropping a folder in the editor:
  - Open all files in the folder in this editor group?
  - Open the folder?
  - Add folder as workspace?
- Dropping a folder in the explorer:
  - Copy the folder into the location?
  - Open the folder?
  - Add folder as workspace?

**Comment by bpasero** [comment]
@Tyriar yes, that is my thinking as well

**Comment by Tyriar** [comment]
@bpasero so is the plan to tweak the behavior to allow opening folders via DND with Electron 1.7.*? Do you need any help with that?

**Comment by darkguy2008** [comment]
@Tyriar I'd expect a similar behavior to Sublime Text: Folder dragged into Explorer: Add to workspace. Folder dragged into Editor: Open the folder instead. Opening all files is a very bad idea, what if you drag a folder with node_modules ? it'll be hell. Btw, thanks @bpasero for referencing my issue here :)

**Comment by Tyriar** [comment]
@darkguy2008 yeah good point, the main thing is squeezing in the "open folder" concept in there somehow as right now that's the only thing that's done (and it will require a full window reload for some time).

**Comment by bpasero** [comment]
@Tyriar I am waiting for Electron to revert the change of Chrome and if that does not happen I need to look into a fix.

**Comment by bpasero** [comment]
Pushed a fix that handles this, differently from before though (we cannot support our old model anymore given the Electron update).
* drop a folder over the editor area will open that folder in the window
* drop a folder over the explorer will add that folder to the workspace if a workspace is opened, otherwise inform the user that you need to open a workspace first (related https://github.com/Microsoft/vscode/issues/31082)

What we gain is the ability to add folders to a workspace by dropping to the explorer, which is cool. What we loose is the visual feedback when you drag that a folder is being dragged. You are now under the impression that you can always drop a folder onto the explorer and the editor will show unhelpful feedback when you drop a folder near the edge of an existing editor by indicating a split operation (which does not make much sense for folders).

**Comment by bpasero** [comment]
**Verification:** ensure that you can open a single folder by dropping it into the editor area (either with editors opened or not).
