### ISSUE TITLE
Feature request: Integrated Terminal: A way to run selected text or current line

### ISSUE THREAD

**Issue by rlipscombe** [Microsoft/vscode#32531]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 3.13.0-39-generic

The `workbench.action.terminal.runSelectedText` runs selected text _or the current file_. I'd prefer a way to run selected text _or the current line_.

**Comment by cleidigh** [comment]
@rlipscombe 
Actually the command already does that, with nothing selected on a line executing the command
will run the one line where the cursor is.  I use it all the time.

**Comment by rlipscombe** [comment]
Then this is a documentation bug:

> If no text is selected in the active editor, the entire file contents is run in the terminal. This is useful if you want to run an entire script or batch file.

https://code.visualstudio.com/docs/editor/integrated-terminal#_run-selected-text

**Comment by Tyriar** [comment]
Yes you're right @rlipscombe, the behavior was changed recently with the introduction of the `workbench.action.terminal.runActiveFile` command. I'll update the documentation 👍
