### ISSUE TITLE
Error when excluding files with a backslash in the filename

### ISSUE THREAD

**Issue by zorac** [Microsoft/vscode#32533]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.3.2
docomment|k--|0.0.17
mssql|ms-|1.1.0
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
debugger-for-chrome|msj|3.1.7
vscode-icons|rob|7.12.0
vim|vsc|0.9.0

---

Steps to Reproduce:

1. Add a file to the project folder containing a backslash, e.g. `c:\log\example.txt`
  a. File appears in Explorer view
2. Add a rule to the files.exclude setting, e.g.: `"**/**\log\**": true`
  a. File is excluded from Explorer view
  b. Error appears for settings.json in Problems view: `Invalid escape character in string`
3. Replace rule in files.exclude to escape backslashes, e.g.: `"**/**\\log\\**": true`
  a. File is not excluded from Explorer view
  b. No error appears for settings.json in Problems view

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Assigning @sandy081 for config and @isidorn for explorer.

**Comment by sandy081** [comment]
Since `files.exclude` setting is of string type, value should be valid. So, backslash should be escaped. I do not think config service should unescape it while reading but Whoever is asking this value should be aware of this and unescape it.

**Comment by isidorn** [comment]
@sandy081 I agree that the value is valid, however what I do not understand is why each configuration service client should unescape values they are getting from the configuration service.
Doesn't it make more sense that configuration service unescapes all string values?

Currently we have 5+ path settings that would all need to adop this code. Why not keep it centralized in the configurations service?
Also it goes well with our current conecpt of the configuration service -> it gives you the truth for that setting, not what is actually written in a file.

**Comment by sandy081** [comment]
Will investigate more and get back to it.

**Comment by isidorn** [comment]
Unassigning myself. 
@sandy081 assign back to me if you come to the conclusino that each configuration service client should escape seperatly.

**Comment by sandy081** [comment]
@isidorn Agreed with you.

@aeschli I think, it makes sense that the JSON parser does the escaping of strings.

**Comment by sandy081** [comment]
@isidorn After debugging, I see the value comes as unescaped from configuration service

![image](https://user-images.githubusercontent.com/10746682/33012135-4c813f38-cde0-11e7-9733-b5ae338111e0.png)

Since you are using the key as regex, you have to escape it back for to be regex compatible.

@aeschli You are off the hook

**Comment by sandy081** [comment]
I suspect, this also impacts Search land

@roblourens FYI

**Comment by isidorn** [comment]
@sandy081 well that is exactly what I am saying a couple of somments above. However I believe the configuration service should escape it (reasons specified above). https://github.com/Microsoft/vscode/issues/32533#issuecomment-328102584

**Comment by roblourens** [comment]
Chrome devtools usually writes a single `\` for a value with a literal backslash:

![image](https://user-images.githubusercontent.com/323878/33035954-cae0ee22-cde1-11e7-89cc-65add21fa8fa.png)

> I think, it makes sense that the JSON parser does the escaping of strings.

Maybe I misunderstand, but `\l` from the original repro is just not a valid escape sequence and it should error, not be parsed as a literal backslash + L.

**Comment by aeschli** [comment]
@roblourens You are looking at JavaScript literals. JSON is more strict, `\1` is not valid there. See http://json.org/ for details. The JSON parser correctly gives an error ('Invalid escape character in string'), but tries to be nice still return a object to work with.

**Comment by roblourens** [comment]
What actually needs to be done here? 

In https://github.com/Microsoft/vscode/issues/38464#issuecomment-346542331 @bpasero says that backslashes are not valid in glob patterns anyway.

**Comment by roblourens** [comment]
I was looking at #50098 and remembered this. The current state is that glob.ts doesn't support globs with backslashes. We need to decide whether we support globs with backslashes or not. If we do, we either change glob.ts to support backslashes in globs or normalize the slashes before passing them to glob.ts.

I don't think there is an issue around how the actual backslash is escaped or not escaped, it works as JSON should.

I vote that we close this and don't support backslashes in globs. On Windows right now, a pattern like `build\\**\\*.js` will *appear* to work but only to depth=1. The way it's handled by glob.ts, it will match `build/*.js` but not the `**`.

We could leave that behavior to avoid breaking people who are relying on this but show a validation error in settings for globs that use backslashes (maybe? can we do that for values in objects?)

This also leaves backslash to use to escape special characters in filenames. I could name a file `foo*.js` and match it with `"foo\\*.js": true`
