### ISSUE TITLE
when opening a big file (15880 rows from mmssql) in json file with users i.e, its not possible to use outlining to minimize one list of objects

### ISSUE THREAD

**Issue by sinanaltaii** [Microsoft/vscode#32538]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.2.0
php-debug|fel|1.11.1
mssql|ms-|1.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.7
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. create a big json file with alot of users and other object for instance 
FYI: in my case: my json-file contained 15880 row from MSSQL query, outlining is not available  :( 
please fix this <3

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
@sinanaltaii Can you please attach a screenshot that shows the problem?

**Comment by sinanaltaii** [comment]
here comes 2 screenshots showing what i mean, the first screenshot is a json file exported from database containing 129890 persons, notice that you can not minimize the entire People object

[cid:0e321fb0-4dd3-4b53-b48e-a829f00b11e8]




here comes the other screen shot and notice that i was able to collapse (minimize the object tree) the "minus sign" is there and i can click on it to collapse, this "minus sign" is missing when dealing with large files


[cid:342409ef-794d-4a7a-a936-85b8a6524f80]


Notice the collapse "button (the minus sign)" to the right of Cards witch makes is possible to collapse and expand, you cant collapse and expand when dealing with large files 😞
I hope i was able to deliver what i wanted to say


Good to know:

People-file is 78 mb

cards is  not more that 5 mb
I really hope that this will be fixed, i dont wanna use other tools


Best regards from Sweden
//  Sinan

________________________________
Från: Martin Aeschlimann <notifications@github.com>
Skickat: den 15 augusti 2017 16:53:41
Till: Microsoft/vscode
Kopia: sinanaltaii; Mention
Ämne: Re: [Microsoft/vscode] when opening a big file (15880 rows from mmssql) in json file with users i.e, its not possible to use outlining to minimize one list of objects (#32538)


@sinanaltaii<https://github.com/sinanaltaii> Can you please attach a screenshot that shows the problem?

**Comment by aeschli** [comment]
@sinanaltaii The screenshots don't show up, it probably has to do with using mail. Can you attach them using the github issue web page?

**Comment by aeschli** [comment]
Closing due to lack of information.
