### ISSUE TITLE
Git conflict decorations do not clean themselves

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3254]
* have a git conflict
* click around if the line conflict decorations don't show up
* delete the conflicting lines
* undo
* Observe: now the conflict decorations never disappear without a Reload window or a new model instantiation.

![git-conflict-decorations](https://cloud.githubusercontent.com/assets/5047891/13222873/2c86c896-d982-11e5-9a3e-6d5636690a9f.gif)

**Comment by joaomoreno** [comment]
Yeah... duplicate of #66 :/
