### ISSUE TITLE
Windows: Many new weird DLLs showing up with new electron

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32548]
It is not clear to me what those are. See left insiders and right our stable release:

![image](https://user-images.githubusercontent.com/900690/29318145-20f58fc0-81cf-11e7-8842-684ffb89fed3.png)

**Comment by jens1o** [comment]
I also noticed that, it's quite annoying, because the setup process of the new insiders versions are even longer now...

**Comment by Tyriar** [comment]
Asked Electron: https://github.com/electron/electron/issues/10291

**Comment by roblourens** [comment]
Is the install size larger, or is it just redistributed?

Some of these at least we weren't shipping before, like vcruntime140.dll - if that stays, I can probably get the ripgrep binary to find it, and we won't have to ship a statically linked rg.exe, to save some KB.

**Comment by Tyriar** [comment]
The dlls make it about ~1.5mb larger I think.

**Comment by Tyriar** [comment]
It was an intentional decision to dynamically link the lib for the various reasons outlined in https://github.com/electron/electron/issues/9443. Closing as not going to fix.
