### ISSUE TITLE
VS Code 1.15.0 jumps into wrong file line from Search menu in both 32 and 64bit Code editions

### ISSUE THREAD

**Issue by pegasus2013** [Microsoft/vscode#32547]
Visual Code is jumping into wrong line in result file from Search menu, since version 1.13, on Windows 10 64bit 1703 - with non extensions installed even after removing 32bit and installing 64bit version the problem still occurs every time.

- VS Code Version: 1.15.0 32bit and 64bit

Steps to reproduce:

1. Search for string in Search menu
2. Click on Search results in any file 
3. Code will jump into wrong line most of the time
4. After closing and opening that file in editor and cliking again will solve the problem for that file only
5. If you click on other results lines in files will reoccur the bug again

This happens in all files not any certain file or project.

**Comment by roblourens** [comment]
What's the text encoding of these files? Can you share a screenshot?

**Comment by pegasus2013** [comment]
Greetings Rob,

Thank your for replaying me, sorry on late response, the encoding is UTF-8 and this happens very often. After closing the file in Search results after first hit it points the correct line, but then again in another file...

![image](https://user-images.githubusercontent.com/2885976/29754623-4394ce6a-8b89-11e7-81e3-301c943323d7.png)

**Comment by roblourens** [comment]
That's pretty weird, I don't know why closing/opening the file would fix it.

After closing/opening, does it *always* work after that? Are you changing git branches, or doing something else that changes the file right before searching?

If you set `"search.useRipgrep": false`, does it repro?
