### ISSUE TITLE
EH debugging: "Restart" results in two debug sessions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32545]
- VS Code: Insiders with "inspector" based EH debugging
- OS: all

Pressing the "Restart" button on the debug floating window restarts the EH process just fine but in many cases results in a second debug session which makes the session drop down appear on the debug floating window.

Most likely this is a timing issue: a new session appears before the old session has terminated.

FYI @roblourens

**Comment by roblourens** [comment]
It seems to think that the first process never terminated. I can't tell whether the debug adapter is doing anything wrong. Let me know if you need anything from me. I'm OOF next week.

**Comment by weinand** [comment]
I've seen the same problem (less frequently) with "legacy" EH debugging, so I don't think this is a specific "inspector" problem. Most likely this is a timing issue: the "inspector" debugger is faster and hits the problem more often. I will investigate...

**Comment by weinand** [comment]
I'm seeing this issue on Windows too when testing #33305

**Comment by isidorn** [comment]
Verifier please verify this works fine now both on osx and windows.

**Comment by isidorn** [comment]
Created related https://github.com/Microsoft/vscode/issues/33507
