### ISSUE TITLE
Emmet providing inappropriate suggestions

### ISSUE THREAD

**Issue by nealoke** [Microsoft/vscode#32543]
- VSCode Version: Code 1.15.0
- OS Version: Windows_NT x64 10.0.14393

**Issue**
![issue vscode](https://user-images.githubusercontent.com/17417414/29315592-3b74a738-81c4-11e7-9f82-902c658cc921.gif)

Steps to Reproduce:

1. Go to a `.js` file
2. Write console.log(a <- You will see the suggestion from this point onward

**Settings for emmet**
```
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
```

**Comment by ramya-rao-a** [comment]
When you map new languages for emmet, emmet doesn't have any contextual knowledge of these new languages.

So whenever emmet sees anything resembling an emmet abbreviation, it will suggest expansion.

Default value for `emmet.showExpandedAbbreviation` is `always`.
You can change it to `inMarkupAndStylesheetFilesOnly`.

This way emmet will not show up in suggestions for languages that it doesn't have a contextual knowledge about.

In VS Code Insiders (https://code.visualstudio.com/insiders) or VS Code 1.15.1 (which will release tomorrow), you can set `emmet.triggerExpansionOnTab` to `true` to get emmet expansion on tab in the absence of the suggestion list.
