### ISSUE TITLE
Git commands

### ISSUE THREAD

**Issue by Nikoltod** [Microsoft/vscode#32544]
- VSCode Version: Latest
- OS Version: Win 10 x64

Hi guys will there be a way to customize the Git commands in VSCode ? 

For example in my work environment we're working with Gerrit and each time we update the code base we need to `<code>git fetch && git rebase</code>` in order to update the code base because Gerrit doesn't allow me to merge branches the same goes for seperate branches is there a way to enter custom commands for Git in VSCode or to fetch && rebase to a given branch from origin/master - the closest I've come is the 'Pull (Rebase)' in the Git section on the SIde Panel of VSCode - or you know you the terminal :D .

Ok thanks guys.

**Comment by joaomoreno** [comment]
You can easily write an extension which does this for you.

**Comment by Nikoltod** [comment]
👍
