### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'syncScrollArea' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32554]
Issue Id: <b>e7eca96d-874f-a2ab-6468-a62a81790d98</b><br /><br />*Versions* <br />- 1.15.0<br />-  1af52c0470d6f445966b5c8a3065233b34303d9a<br />-  211ffdf184329179ddca9c1fe993f5f11f3c4dda<br />-  c26f8a312b9aa792f45a7baf06e31576470236a8<br />-  dd7adcc1615d86c33e139b677f5adf69f1c2cf91<br />-  6feff11ed03402cf77e04e74e13c55529fdb4d09<br />-  19f17905e7ecd62c3f0cb14c30a66db1ebfe8069<br />-  0e7546c978fa1b62dbf36f07a77d1b9a4241d6f7<br />-  f39385b8326671dc6389f21f8c2e2f6afdb352a1<br />-  2c3e2c291c515619f64e7c9cddf14c565b7f3d92<br />*Stack* <br />TypeError: Cannot read property 'syncScrollArea' of undefined<br />    at Parser.parse (/node_modules/xterm/lib/Parser.js:260:52) <no sourcemaps><br />    at Terminal.innerWrite (/node_modules/xterm/lib/xterm.js:832:33) <no sourcemaps><br />    at /node_modules/xterm/lib/xterm.js:817:18 <no sourcemaps><br />

**Comment by Tyriar** [comment]
https://github.com/sourcelair/xterm.js/issues/892
