### ISSUE TITLE
 Path must be a string. Received { Error: spawn wmic.exe ENOENT

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32556]
Issue Id: <b>299fb1cc-0369-9f86-f69a-c001aca48871</b><br /><br />*Versions* <br />- 1.15.0<br />*Stack* <br />TypeError: Path must be a string. Received { Error: spawn wmic.exe ENOENT<br />    at exports._errnoException (util.js:1022:11)<br />    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32) <no sourcemaps><br />    at onErrorNT (internal/child_process.js:359:16) <no sourcemaps><br />    at _combinedTickCallback (internal/process/next_tick.js:74:11) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />  code: 'ENOENT',<br />  errno: 'ENOENT',<br />  syscall: 'spawn wmic.exe',<br />  path: 'wmic.exe',<br />  spawnargs: <br />   [ 'process',<br />     'where',<br />     'parentProcessId=3764',<br />     'get',<br />     'ExecutablePath,ProcessId' ],<br />  cmd: 'wmic.exe process where parentProcessId=3764 get ExecutablePath,ProcessId' }<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename))<br />[/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />    at<br />

**Comment by kieferrm** [comment]
This is currently spamming our error telemetry with thousands of events.

**Comment by Tyriar** [comment]
wmic.exe has been around since Windows XP, I believe this happens when `c:\Windows\System32\wbem` is not on `PATH`.

**Comment by Tyriar** [comment]
Verified on 64 and 32-bit Windows builds on a 64 bit Windows box. We also reproduced the error by removing the wbem path from `%PATH%`.

Pushed to master and release/1.15.
