### ISSUE TITLE
Integrated terminal should handle mouse scrolling in curses-style interfaces

### ISSUE THREAD

**Issue by MattSturgeon** [Microsoft/vscode#32552]
#### Summary

Scrolling within the integrated terminal doesn't scroll curses interfaces such as `less`, `vim`, `git log`, etc.

#### System setup

- VSCode Version: Version 1.15.0 8b95971d8cccd3afd86b35d4a0e098c189294ff2
- OS Version: Arch Linux
- Shell: ZSH (oh-my-zsh)

#### Steps to Reproduce:

1. Open the integrated terminal (`` Ctrl+` ``)
2. Open a curses style pager interface (e.g. `less`, `git log`, `git diff`, `vim`)
3. Use the mouse scrollwheel to try and scroll the pager
5. Nothing happens, using keyboard commands to scroll works fine (`j`, `k`, `PgUp`, `PgDown`, arrow keys, etc)

#### Compare with expected behaviour:

1. Open a seperate terminal (e.g. `gnome-terminal` or `tilix`)
2. Repeat step 2 & 3 above
3. Works as expected; pager scrolls

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This should be fixed in the next version. Note that this only applies to applications that launch the alt buffer however, so it does not apply to `git log` .

Upstream issue: https://github.com/sourcelair/xterm.js/issues/802

**Comment by MattSturgeon** [comment]
Sounds like the upstream issue might be a different one to this. It appears to be about the alternative buffer being rendered twice after a scroll.

This is about passing scroll events to pager style programs, such as less and git log.

**Comment by Tyriar** [comment]
The reason scroll isn't making it to the terminal app is because the scrollbar is grabbing the event and not passing it to the terminal. When there is no scrollback it gets sent to the terminal correctly.

**Comment by Tyriar** [comment]
It works in tmux fine now but not vim yet.

**Comment by Tyriar** [comment]
This has been working for a few versions now 👍
