### ISSUE TITLE
Configuration change events and workspace folder changes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#32558]
Consider the following steps:

- a file A is opened
- the user adds a workspace folder which contains file A
- this basically changes the 'configuration' for file A from a user configuration for a folder configuration

Some happens in the opposite case when a workspace folder is removed and files contained inside the folder stay open.

Should we signal the configuration change through a configuration change event?

**Comment by bpasero** [comment]
Yes, I think we should just emit a configuration change event when a root folder is added or removed so that everyone has a chance to re-resolve the configuration for any scope.

**Comment by sandy081** [comment]
When a root folder is added / removed, configuration change event is emitted only if there is a change in configuration after the fact.
