### ISSUE TITLE
 Path must be a string. Received { Error: spawn wmic.exe ENOENT

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32561]
Issue Id: <b>3cc4c2c1-96cf-4394-a3ce-8f83d5e6026e</b><br /><br />*Versions* <br />- 1.15.0<br />*Stack* <br />TypeError: Path must be a string. Received { Error: spawn wmic.exe ENOENT<br />    at exports._errnoException (util.js:1022:11)<br />    at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32) <no sourcemaps><br />    at onErrorNT (internal/child_process.js:359:16) <no sourcemaps><br />    at _combinedTickCallback (internal/process/next_tick.js:74:11) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />  code: 'ENOENT',<br />  errno: 'ENOENT',<br />  syscall: 'spawn wmic.exe',<br />  path: 'wmic.exe',<br />  spawnargs: <br />   [ 'process',<br />     'where',<br />     'parentProcessId=5132',<br />     'get',<br />     'ExecutablePath,ProcessId' ],<br />  cmd: 'wmic.exe process where parentProcessId=5132 get ExecutablePath,ProcessId' }<br />    at assertPath (path.js:7:11)<br />    at Object.basename (path.js:799:5)<br />[/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L894:16 (basename))<br />[/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/terminal/electron-browser/windowsShellHelper.ts#L49:28 (setTitle))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />    at<br />

**Comment by kieferrm** [comment]
Related to #32556.

**Comment by Tyriar** [comment]
It's a duplicate, the PID is the only difference https://github.com/Microsoft/vscode/issues/32556
