### ISSUE TITLE
BUG: The "new folder" action doesn't work well enough

### ISSUE THREAD

**Issue by romu70** [Microsoft/vscode#3256]
The "New Folder" action works pretty well except when one wants to create a new project top folder. Here is a test sequence.

Pre-requisite:

- One project has been created, let's call it P.
- This project P is opened
- This project contains a folder, let's call it F1.

1. Select the F1 folder
2. Click "New Folder"
-> A new folder is created in F1, great!
3. Select the project top folder P
4. Click "New Folder"
-> The new folder is still created in F1 and not directly in the P top folder.

**Comment by Tyriar** [comment]
@romu70 the workaround for this is to either select a folder in `P` or right click the empty area below the files (if there is room) and select new folder from the context menu.

Resolving this in favor of https://github.com/Microsoft/vscode/issues/1043 which highlights this plus another issue with the UX.

**Comment by romu70** [comment]
Thanks @Tyriar, obviously I didn't search enough before creating this issue.
