### ISSUE TITLE
Finding References (right-click) doesn't work.

### ISSUE THREAD

**Issue by tiagoacpinto** [Microsoft/vscode#32573]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
vsc-material-theme|Equ|1.0.2
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
vscode-JS-CSS-HTML-formatter|lon|0.2.3
sublime-keybindings|ms-|2.9.1
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1. Just try Find References on PHP, it doesnt work, i tried in 2 projects now, one at work, one at home for a side project of mine
Note: Also javascript finding references doesn't work.

Its the only thing stopping me from using it

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
The built-in PHP support does not support find references. You have to file that issue against the PHP extension that you use (php-intellisense).

For JavaScipt, please create a separate issue with sample code.
