### ISSUE TITLE
npm update hangs

### ISSUE THREAD

**Issue by RobGraham** [Microsoft/vscode#32576]
- VSCode Version: 1.15.0
- OS Version: OSX 10.12.5
- NPM Version: 5.3.0
- Node Version: 8.2.1

`npm install` works fine and successfully installs packages, yet `npm update` just hangs. 

Steps to Reproduce:
1. Open terminal window inside VS code
2. execute `npm update`

I've tried with no user settings as well as: 
`{
     "http.proxyStrictSSL": false,
    "terminal.external.osxExec": "iTerm.app"
}`

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Are there any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by RobGraham** [comment]
@Tyriar since Code updated to 1.15 I don't seem to be experiencing the problem anymore. Thanks
