### ISSUE TITLE
 Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#32571]
Issue Id: <b>9a3a98fb-db12-54cf-cea6-16b200c4be99</b><br /><br />*Versions* <br />- 1.15.0<br />-  6feff11ed03402cf77e04e74e13c55529fdb4d09<br />*Stack* <br />TypeError: Cannot read property 'properties' of undefined<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1149:31 (properties)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1149:31 (properties))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1384:41 (from)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1384:41 (from))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1733:23 (from)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1733:23 (from))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1692:29 (createTaskRunnerConfiguration)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1692:29 (createTaskRunnerConfiguration))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1780:52 (run)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1780:52 (run))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1462:33 (parse)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1462:33 (parse))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1457:43 (then)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1457:43 (then))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1456:23 (then)](https://github.com/microsoft/vscode/blob/8b95971d8cccd3afd86b35d4a0e098c189294ff2/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1456:23 (then))<br />

**Comment by dbaeumer** [comment]
Dups #30758
