### ISSUE TITLE
macOS: Unable to auto upgrade.

### ISSUE THREAD

**Issue by designbystephen** [Microsoft/vscode#32572]
macOS: Unable to auto upgrade.  New product updates require a download from web and a manual replacement in my Applications folder. 

- VSCode Version: 1.14.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Upon product update notice, click "Restart to Update" any number of ways.
2. The application will then close but the update never commences, nor does it restart

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
