### ISSUE TITLE
Import-Module WebAdministration has no affect, causes scripts to fail

### ISSUE THREAD

**Issue by burtonrodman** [Microsoft/vscode#32577]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
vscode-docker|Pet|0.0.16

---

Steps to Reproduce:

1.  Open ps1 file which contains "Import-Module WebAdministration"
2.  Hit F5
3.  Commands like Set-Location IIS:\ result in errors.
Manually executing Import-Module WebAdministration in the Terminal has no effect either.
Scripts works fine from external (non-integrated) PowerShell window.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Please file this against the PowerShell extension.
