### ISSUE TITLE
Customizable syntax highlighting

### ISSUE THREAD

**Issue by karljs** [Microsoft/vscode#32585]
As described in [this issue](https://github.com/James-Yu/LaTeX-Workshop/issues/237) for the LaTeX Workshop package, there are well-defined use cases for syntax highlighting that can be customized to some extent (aside from changing the grammar).

The relevant part of the grammar is here:
https://github.com/area/language-latex/blob/73943c33eba9f06eae2825d735b50327fee79536/grammars/latex.cson#L1249

I'm surprised there is not a way to achieve this with some kind of variable in the cson file, but this is not my area of expertise.

**Comment by aeschli** [comment]
There is now a user setting that lets you change how tokens are colored: https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme

Changing the grammar is only possible through an extension. Grammars can be replaced, or you can add additional rules through [grammar injections](http://blog.macromates.com/2012/injection-grammars-project-variables/).
It's an advanced topic, with only little documenation.

I'm not familiar with Latex and the ways you can customize it. You'd have to give some examples then I can point you to the right places, if you are interested to work on this.

**Comment by karljs** [comment]
@aeschli Thanks for the links.  I think grammar injections _might_ be what I need, but I'd still appreciate any further advice.  Here is a more detailed example:

In LaTeX, math code is often placed between matching dollar sign symbols `$` such as 
```
$x=y$
```

When typesetting code, it is generally wrapped in a special environment called `verbatim` (or `lstlisting` or a few others).  This might look like:

```
\begin{verbatim}
myFunction(a, b, c);
\end{verbatim}
```

The problem arises when a dollar sign is used as part of the code that is being typeset inside a verbatim environment (as is common with Haskell).

```
\begin{verbatim}
myFunc x = foo $ bar x
\end{verbatim}
```

Since the LaTeX grammar thinks the dollar sign is an open delimiter, like `{` or `(`, it will color the rest of the file a single color as if it were math code.  The language-latex package includes special exceptions in the grammar for `verbatim` and `lstlisting` environments to avoid this exact problem.

I sometimes need to define my own environments that work like verbatim, but with some customizations.  These might be called something like `myVerbatim`, so I'd have:

```
\DefineVerbatimEnvironment{myVerbatim}{Verbatim}
  { ... }
\begin{myVerbatim}
myFunc x = foo $ bar x
\end{myVerbatim}
```

Since the grammar doesn't know to treat me environment the way it treats other special cases, I get the incorrect highlighting.

**Comment by aeschli** [comment]
If I understand this right, it is a bug in the Latex grammar to not ignore content inside `\begin{myVerbatim}` and `\ end{myVerbatim}. At least for the verbatim environments, it doesn't know. I'd suggest filing an issue against https://github.com/area/language-latex

The purpose of a grammar injections is to add extra highlighting on top of an existing grammar. E.g. if you wanted to add verbatim specific highlighting. But not as a bug fix, but an addition.
Think of a grammar injection to add highlighting inside a string literal.

Closing, but I'm happy to reopen if I misunderstood the issue and there's something on our side we can do.
