### ISSUE TITLE
Using `code --install-extension abc` throws UnhandledPromiseRejectionWarning and blocks installation

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/vscode#32580]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 14.5.0

Steps to Reproduce:

1. Ensure that the `code` command is installed.
1. Try to install any extension using `code --install-extension`.
1. For illustrative purposes, let's use eg2.tslint but this issue is reproducible on other extensions as well.

Actual:

```
nchen@nchen-wsm1:~|⇒  code --install-extension eg2.tslint                                                                                           9:58:47
Found 'eg2.tslint' in the marketplace.
Installing...
(node:29845) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:29845) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And the extension is not installed.

Expected:

Extensions are installed successfully as they have in the past with 1.14.

**Comment by vazexqi** [comment]
This is reproducible on a Windows 10 box as well so it is not isolated to OS X.

**Comment by yujiangshui** [comment]
I have this too, days ago it's fine but recently it does not work.

**Comment by yujiangshui** [comment]
And there is already has one: https://github.com/Microsoft/vscode/issues/32381

**Comment by vazexqi** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/32381
