### ISSUE TITLE
Support case preserving find/replace

### ISSUE THREAD

**Issue by ribrdb** [Microsoft/vscode#32587]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
---

Steps to Reproduce:

1. Enter text into the editor:

> foo
> Foo
> FOO

2. Press cmd+f
3. Expand, enter "foo" to find and "bar" to replace
4. Replace all occurrences

In emacs this would result in

> bar
> Bar
> BAR

however vscode always replaces with the same case you enter into the field. This means you either have to do multiple replace operations with case matching, or fix up the case after doing a replace all.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
