### ISSUE TITLE
Intellisense does not work for large projects and also when multiple files are opened.

### ISSUE THREAD

**Issue by pwaykole** [Microsoft/vscode#32586]
1) Language: Javascript (React)
2) Disabling all the extensions doesn't work the problem still persists.
3) It takes usually 5 sec and it happens every time not only first load.
4) The project is 11mb excluding node_modules.
5) It is bit faster when you open only one tab at a time, multiple tabs slows it down

**Comment by pwaykole** [comment]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.19.0
run-current-test|asv|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
prettier-vscode|esb|0.22.1
flow-for-vscode|flo|0.7.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vscode-flow-ide|gca|1.2.0
beautify|Hoo|1.1.1
webpack|jer|2.0.0
chai-snippets|nwh|0.1.0
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
es6-mocha-snippets|spo|0.0.2
react-redux-es6-snippets|tim|2.1.0
vscode-react-native|vsm|0.4.1
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(2 theme extensions excluded)


---

Steps to Reproduce:

1) Language: Javascript (React)
2) Disabling all the extensions doesn't work the problem still persists.
3) It takes usually 5 sec and it happens every time not only first load.
4) The project is 11mb excluding node_modules.
5) It is bit faster when you open only one file at a time, multiple files open slows it down


Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Hey sorry this fell off my radar. 

Please let me know if you are still seeing this issue in VS Code 1.18
