### ISSUE TITLE
cannot open files or directories on OneDrive in Windows 10 Insider Preview

### ISSUE THREAD

**Issue by jdbruner** [Microsoft/vscode#32589]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.16264
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
plantuml|jeb|2.1.1
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
debugger-for-edge|msj|0.4.1

---

Steps to Reproduce:

1. Select "Open Folder" from the File menu
2. Navigate to a OneDrive folder on Windows 10 (Insider Preview)

Perhaps the reparse points used to implement OneDrive placeholders are confusing it.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
