### ISSUE TITLE
emmet not work

### ISSUE THREAD

**Issue by KanesYang** [Microsoft/vscode#32596]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-instant-markdown|dba|1.2.1
vscode-npm-script|eg2|0.2.0
vscode-great-icons|emm|2.1.14
react-native-react-redux|EQu|1.1.0
mithril-emmet|Fal|0.6.1
auto-close-tag|for|0.4.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
useful-react-snippets|igo|1.0.9
vscode-angular2-emmet|jak|2.0.3
search-node-modules|jas|1.1.1
NodeAssertionSnippets|jay|0.1.0
node-module-intellisense|lei|1.4.0
vscode-extension-auto-import|mop|1.3.3
angular2-inline|nat|0.0.17
LiveServer|rit|1.6.9
autoimport|ste|1.2.2
vscode-angular-support|vis|0.1.4
vscode-bemmet|vol|0.1.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1
D3Snippets|yoy|0.1.11

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by whj768702** [comment]
https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0

**Comment by ramya-rao-a** [comment]
@KanesYang 

You have 3 choices

- In VS Code 1.15, tab is no longer associated with Emmet. You can bind any other keyboard shortcut to the command `editor.emmet.action.expandAbbreviation`
- Install latest Insiders from https://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
- Wait for the VS Code 1.15.1 release which will be tomorrow. Set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
