### ISSUE TITLE
UI: Wrong tab look selected in editor when extension info is open with dark theme

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#32598]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.5.0
- Extensions: Built-in dark theme

**Steps to Reproduce:**

1. Open new file tab.
2. Open details for an extension, and stay on that tab

Actual:
Looks like the regular tab is selected due to the extension color header is clashing.

![extension tslint weblight 2017-08-15 17-00-08](https://user-images.githubusercontent.com/173559/29341779-8550dcde-81db-11e7-858b-9a46074a23ed.png)

**Comment by sandy081** [comment]
This is more confusing when two extensions are open

![image](https://user-images.githubusercontent.com/10746682/33213234-0da18210-d127-11e7-98d1-ac7c154ed20d.png)

I do not think background colour for extension header pane is necessary. This is after removing background color

![image](https://user-images.githubusercontent.com/10746682/33213344-780bfa18-d127-11e7-9f8c-af00c0c6a7b4.png)
