### ISSUE TITLE
Tab does not automatically complete tag matching

### ISSUE THREAD

**Issue by dongkang1993** [Microsoft/vscode#32599]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.2
vscode-eslint|dba|1.2.11
javadebugger|don|0.1.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
vscode-great-icons|emm|2.1.14
vsc-material-theme|Equ|1.0.2
vscode-javac|geo|0.0.46
vue-snippets|hol|0.1.2
beautify|Hoo|1.1.1
vscode-icon-theme|jtl|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.1.7
material-icon-theme|PKi|2.1.0
vscode-icons|rob|7.12.0
D3Snippets|yoy|0.1.11

(4 theme extensions excluded)

---

Steps to Reproduce:

1.Enter a div 
2.press the Tab key does not automatically complete the label match

Reproduces without extensions: Yes/No

**Comment by whj768702** [comment]
https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0

**Comment by ramya-rao-a** [comment]
You have 3 choices

- In VS Code 1.15, tab is no longer associated with Emmet. You can bind any other keyboard shortcut to the command `editor.emmet.action.expandAbbreviation`
- Install latest Insiders from https://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
- Wait for the VS Code 1.15.1 release which will be tomorrow. Set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
