### ISSUE TITLE
Unable to find/replace within selected area

### ISSUE THREAD

**Issue by scubazip** [Microsoft/vscode#32595]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:19.566Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cobol|bit|0.3.12
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.  Click on a column
2.  Alt+F  Highlight something 10 columns wide and 10 lines
3.  Ctrl+H
4.  Click "Find in Selection button" (withing the find/replace window)
5.  The text that was selected in step 2 is de-selected!  <---  the problem

NOTE:  This is not a problem if you select the enter line.  The problem only exists when using Alt+F

Reproduces without extensions: Yes/No

**Comment by scubazip** [comment]
Sorry not Alt-F  but Shift-Alt

**Comment by rianquinn** [comment]
I can confirm this issue with Cmd+D selections (i.e. selecting multiple of the same strings). As soon as you select the "Find in Selection" option, the current selection is deselected. For now, I have been using Sublime to perform this action as it works fine there, but it would be great if this worked in VSCode so I didn't have to swap back and forth.

**Comment by rebornix** [comment]
To find in a selection, you may want to select the range, toggle find in selection first to lock the selection, and then type in the query keyword. Find widget searches incrementally when you type so that's why the selection is not locked.
