### ISSUE TITLE
Add drag and drop for contributed tree views

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#32592]
We've been using new Tree View API to provide structured view of F# projects - in F# project files needs to be ordered according to compilation order so this additional view gives users better information about their project. We also include in the view list of project references, and assembly references so it's really similar to the Visual Studio solution explorer.

It looks like following:
![image](https://user-images.githubusercontent.com/5427083/29336346-be4fc22a-820d-11e7-9ea6-abe8b185989d.png)

As I've mentioned - ordering of files is really important for the F# projects, and we provide couple of helper commands to manage it (move file up/down etc).  Those commands work more or less, but I don't think it's best UX.
I think it would be super nice if users had ability to use normal drag and drop to manipulate the order - just as they are able to manipulate files in normal file explorer (drag and drop files to move them to subfolder for example)

**Comment by cartermp** [comment]
Just to add weight to this: file ordering is critically important for F# users.  We're also exploring adding click and drag for CPS in Visual Studio, which would leave VSCode as the only F# editor that doesn't support click and drag for file ordering.

**Comment by forki** [comment]
Oh that would be an awesome feature!

**Comment by mastoj** [comment]
💯 * 👍

**Comment by hakonrossebo** [comment]
+1

**Comment by DmitryBatalov** [comment]
+1

**Comment by priort** [comment]
That would be a really helpful feature.

**Comment by priort** [comment]
+1

**Comment by magnushammar** [comment]
This would be awesome. Some things are actually better done with a GUI and this is one.

**Comment by pirrmann** [comment]
+1

**Comment by Neftedollar** [comment]
F# developers need this feature as an air.

**Comment by MangelMaxime** [comment]
💯

**Comment by schaveyt** [comment]
+1

**Comment by DanTup** [comment]
I'd like to see this too for a UI tree we're building. Some things it'd be nice for the API to support:

- Declaring if a node is draggable or not
- Ability to drop on top of or in between items (re-order versus changing parent)
- Ability to provide feedback while dragging about whether a given location is valid to drop on

**Comment by FrederickBrier** [comment]
Someone wrote that we need to wait for the vscode team to implement the feature. Does that mean that we should not fork the repo and try to implement it? Because that that is not their process and a pull request would be rejected? Thank you.

**Comment by sandy081** [comment]
No plans yet.

**Comment by e-stets** [comment]
Is this still considered? It would be a great addition to simplify a lot of UI workarounds for TreeViews.

**Comment by barbaravaldez** [comment]
Are there any plans for implementing this in the near future?

**Comment by sirfuzzalot** [comment]
+1

This issue has been sitting on the backlog for three years now and in the meantime the Tree View API has grown and matured some, but we're still missing this key feature set. Users frequently compare the drag and drop capabilities they have inside of the Explorer/Folders view to what they are experiencing in the extension views. Would love to see this request get some traction!

**Comment by LighghtEeloo** [comment]
Another vote for this feature! A same logic with explorer will boost extension experience.

**Comment by gplumb** [comment]
This request was created in 2017! Come on... clearly people want this feature - what is it going to take to get this work into a sprint??

**Comment by worksofliam** [comment]
Also would be nice to have

**Comment by benedyktdryl** [comment]
@alexr00 @sandy081 is there any exact reason or obvious blocker to avoid start working on that feature? Is there any chance I can contribute to VSC to start any work in that area? Do you have any discussion group so you can share with me your vision about this feature? I will be more than happy to start working on it.

**Comment by alexr00** [comment]
@benedyktdryl thanks for offering to make a PR for this feature. It is, however, a large feature and likely not a good candidate for a PR. 

You can check out our roadmap for features that we have prioritized: https://github.com/microsoft/vscode/wiki/Roadmap

We do plan on investing more time in extension tree views, and this feature request will likely be part of that.

**Comment by TestUser013** [comment]
Hi,
Since there is no way to use Drag&Drop functionality I would like to add buttons to move Tree View items up and down. Is there any way to change the order of tree list items from plugin?

**Comment by gplumb** [comment]
You could do that via some commands in your view and a custom tree data
provider (https://code.visualstudio.com/api/extension-guides/tree-view).

Drag and drop would be much easier though ;-)

**Comment by LinkShen** [comment]
Mark. Look forward any new progress. I am making an extension used to organize source tree need this.

**Comment by alexr00** [comment]
We discussed this API:

https://github.com/microsoft/vscode/blob/39d180d6624d0471b9617d69d74f89da3345cf06/src/vs/vscode.proposed.d.ts#L884-L904

Problems with this approach:
- It is tree view specific.
- It doesn't allow reordering.
- It doesn't let us support drag feedback or other drag properties in the future.

Instead, we could add a `DragAndDropController` (final name TBD) to the `TreeView`:

```
	export interface TreeView<T> extends Disposable {

		readonly dragAndDropController: DragAndDropController<T>;
	}

	export interface DragAndDropController<T> extends Disposable {
		/**
		 * Extensions should fire `TreeDataProvider.onDidChangeTreeData` for any elements that need to be refreshed.
		 *
		 * @param source
		 * @param target
		 */
		onDrop(source: T[], target: T): Thenable<void>;
	}
```

Additionally, we should consider updating `TreeDataProvider.onDidChangeTreeData` to allow firing with an array,

**Comment by gplumb** [comment]
Great to see this being discussed :-)

I would like to suggest an addition to the DragAndDropController interface
in TreeView:

    export interface DragAndDropController<T> extends Disposable {
/**
* Extensions should fire `TreeDataProvider.onDidChangeTreeData` for any
elements that need to be refreshed.
*
* @param source
* @param target
*/
onDrop(source: T[], target: T): Thenable<void>;

        /**
         * Evaluate whether a given drag and drop operation is allowed.
         *
         * If false, VS Code will render a cursor equivalent to
"cursor:no-drop;", preventing onDrop()
         * from firing when a drag operation terminates
*
* @param source
* @param target
         * @returns boolean
*/
canDrop(source: T[], target: T): Thenable<boolean>;
    }

This would give authors so much more flexibility.  For example, level '0'
in a tree might represent a container of some sort, who's children can be
freely ordered within it, but cannot be moved to a different parent (a
contrived example on the face of it, but a use case I have in a simple user
interface editing extension, where such constraints exist).

Would love to hear your thoughts on this!


Thanks

G

**Comment by justinmk3** [comment]
Will this allow custom treeviews to receive drops from other sources, e.g.

- vscode editor tabs
- vscode file explorer
- the OS file explorer (e.g. macOS finder)

**Comment by alexr00** [comment]
We're only working on supporting drop from the same tree view. If the tree item is backed by a resource/file then drag-out into other places should have some support.

**Comment by alexr00** [comment]
Some thoughts on where we might go:

https://github.com/microsoft/vscode/blob/45784932359f3d1d9a59f7bdcfa988f5053eee62/src/vs/vscode.proposed.d.ts#L916-L937

**Comment by alexr00** [comment]
Other possible drag events, for reference: https://developer.mozilla.org/en-US/docs/Web/API/Document/drop_event#see_also

The HTML spec's `DataTransfer`: https://html.spec.whatwg.org/multipage/dnd.html#datatransfer

**Comment by idoprz** [comment]
> Will this allow custom treeviews to receive drops from other sources, e.g.
> 
> * vscode editor tabs
> * vscode file explorer
> * the OS file explorer (e.g. macOS finder)

Support of droping into editors tabs (custom editors) can be very helpfull for some scenarios.
Also, supporting drag from webview panels can be great!

**Comment by alexr00** [comment]
The current proposal sets us up for enabling many other drops into tree views. It would enable _some_ drags into places like editors, but not all. It will not support any drag from webview panels.

https://github.com/microsoft/vscode/blob/8f774f132e036347c018b9cc69c79a178322dacb/src/vs/vscode.proposed.d.ts#L916-L942

**Comment by gplumb** [comment]
I like this approach :-)

How come this isn't planned for the webview? Selfishly, it'd light up a few
useful scenarios for my extension!


G

**Comment by pwsses** [comment]
+1

**Comment by abflow** [comment]
We would find useful to drag from custom tree views into webview panels and from webview panels into custom tree views.

**Comment by nickzhums** [comment]
Hello folks, just wondering what the current plan for this feature is ? thanks!

**Comment by gplumb** [comment]
Hi all!  Would be good to know if this made the cut from last year's
roadmap or not :-)

**Comment by gjsjohnmurray** [comment]
> Would be good to know if this made the cut from last year's roadmap or not :-)

It was on the current iteration plan (#139607) until 10 days ago, then removed by @kieferrm (not moved into the Deferred section though). But there's evidence of work on it by @alexr00 recently, so I think it stands a chance of landing in 2022.

**Comment by alexr00** [comment]
@gjsjohnmurray is correct, it does stand a chance of landing in 2022. We're just going through our API process and refining it now.

Folks who are interested in it can try out the [current API proposal](https://github.com/Microsoft/vscode/blob/047901a24a47f26386e4c230500885a677d5c877/src/vscode-dts/vscode.proposed.treeViewDragAndDrop.d.ts) and provide feedback in this issue if you want to help!
