### ISSUE TITLE
Go to bracket doesn't scroll to reveal the off-screen bracket

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32597]
- Have a pair of brackets, where one is visible on screen and the other is off screen.
- Press cmd+shift+\
- The cursor goes to the off-screen bracket, but the viewport doesn't scroll to reveal it

**Comment by fixedmachine** [comment]
Yep. Same here. Very annoying behaviour. 

Version 1.16.0-insider - 787b31c0474e6165390b5a5989c9619e3e16f953
macOS 10.12.6 (16G29)

**Comment by anothergituser** [comment]
Why is this issue closed? The bug still persists in 1.6.1 and it's a major annoyance

**Comment by Christilut** [comment]
This is fixed for me in 1.7.0

**Comment by drcallaway** [comment]
I think you mean 1.17.0. Fixed for me now as well.
