### ISSUE TITLE
Detected indentation should take precedence over useSpaces preference

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3259]
> @alexandrudima We're not bad at detecting indentation. We're bad at respecting it.

> Our `useSpaces` setting always takes preference, regardless of detection. That setting should only be respected when the detection is inconclusive (e.g. a blank file, a mixed indentation file etc.). Having it set to `true`, opening a tabbed file and have spaces being inserted when automatically indenting is wrong.

**Comment by alexandrudima** [comment]
I half agree :).

I think this is the first time we need to distinguish between user settings and workbench settings.

If `insertSpaces = false` in a workspace, then it means that for no reason whatsoever should spaces be inserted.

If `insertSpaces = false` in the user settings, then you could argue that in case autodetection fails to get sufficient hints, it could be used as the fallback value.

**Comment by joaomoreno** [comment]
What would happen to a workspace with `insertSpaces` set to `false`, just as our own, and suddenly someone puts a perfectly valid YAML file in there? YAML files consider tabs to be syntax errors. Should I jump to Sublime Text every time I want to edit that file?

IMO there are a few issues here:

- a file's indentation should always be detected and respected, regardless of any setting
- if detection is inconclusive, be that due to mixed indentation or to lack of it, the setting should be taken into account for the decision
- `insertSpaces` should be a boolean setting. `auto` makes no sense at all to me
- `insertSpaces` is ultimately a bad name. It should be something around `preferSpaces`, `preferredIndentation`, `defaultIndentation`, etc

**Comment by joaomoreno** [comment]
@isidorn this is what I mean

**Comment by alexandrudima** [comment]
I want wrapping for .txt files and not for other files.
I want Arial for .txt files.

IMHO the YAML example you give is arguing for per-file settings, which, I definitely agree, is something we should have.

**Comment by joaomoreno** [comment]
Both wrapping and font are view-only attributes. Neither can they be determined by the syntax of the file nor can they affect the syntax itself. Per-file view settings are another feature altogether.

Indentation is not. It is strongly bound to the file's syntax. A change in indentation character actually changes the file's contents.

But let me pick up another argument.

The indentation problem is exactly the same as the end-of-line problem, at which we do an *almost* perfect job:

- We either show `LF` or `CRLF` in the status bar, always indicating what line endings the current opened file has.
- When the user presses <kbd>Enter</kbd> in a file, that value is respected. The detection itself defines the end-of-line character to use.
- Switching to another file with another end-of-line sequence will update this value.
- Switching the value itself will modify the file's contents.
- We are *almost* perfect simply because there isn't a configuration setting for the default case. But we do have a pretty good heuristic: the OS itself.

**Comment by alexandrudima** [comment]
Ok, I really like the analogy with LF/CRLF detection. I'm sold!

**Comment by joaomoreno** [comment]
![wolf](http://i.giphy.com/v18xOnxDRt8aI.gif)

**Comment by bpasero** [comment]
For this we should use the detection algorithm in

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModel.ts#L461

And set the editor to whatever it returns.

**Comment by joaomoreno** [comment]
This should also be done in the exact same way we detect EOL and encoding. @bpasero where and how do we do it?

**Comment by bpasero** [comment]
@joaomoreno we currently only detect encoding using BOM on the file service layer. Not sure about EOL.

**Comment by bpasero** [comment]
I am marking this important because of https://github.com/Microsoft/vscode/issues/3656 which is very confusing otherwise.

**Comment by joaomoreno** [comment]
:+1:

**Comment by isidorn** [comment]
Fixed by @alexandrudima
