### ISSUE TITLE
new update emmet tab not work

### ISSUE THREAD

**Issue by GoodProject** [Microsoft/vscode#32594]
i write: img + tab = not work..
Before updating: < img src="" alt="" >
help pls

![image](https://user-images.githubusercontent.com/14226563/29338595-9011a034-821e-11e7-904f-a4633d984f81.png)

**Comment by ramya-rao-a** [comment]
@GoodProject  You have 3 choices

- In VS Code 1.15, tab is no longer associated with Emmet. You can bind any other keyboard shortcut to the command `editor.emmet.action.expandAbbreviation`
- Install latest Insiders from https://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
- Wait for the VS Code 1.15.1 release which will be tomorrow. Set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab

**Comment by GoodProject** [comment]
@ramya-rao-a Thanks! )
