### ISSUE TITLE
Dead link on https://code.visualstudio.com/docs/extensions/patterns-and-principles

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode#326]
The last link on the [_Next Step_](https://code.visualstudio.com/docs/extensions/patterns-and-principles#_next-steps) Section is dead. The following page should be loaded, but does not exist:

https://code.visualstudio.com/docs/extensionAPI/documents-and-editors

**Comment by gregvanl** [comment]
Fixed and republished.
