### ISSUE TITLE
emmet's tab not useable

### ISSUE THREAD

**Issue by freeser** [Microsoft/vscode#32604]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-caniuse|aka|0.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
vscode-npm-script|eg2|0.2.0
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|1.0.0
vscode-autoprefixer|mrm|2.1.2
vetur|oct|0.9.3
vuehelper|oys|0.1.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.8.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@freeser 

You have 3 choices

- In VS Code 1.15, tab is no longer associated with Emmet. You can bind any other keyboard shortcut to the command `editor.emmet.action.expandAbbreviation`
- Install latest Insiders from https://code.visualstudio.com/insiders and set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
- Wait for the VS Code 1.15.1 release which will be tomorrow. Set `emmet.triggerExpansionOnTab` to `true`. You will get emmet back on pressing tab
