### ISSUE TITLE
Command k + Command j unfolds whole file even on selection

### ISSUE THREAD

**Issue by psankar** [Microsoft/vscode#32607]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
swagger-viewer|Arj|1.4.0
material-icon-theme|PKi|2.1.0
vscode-docker|Pet|0.0.16
vscode-wakatime|Wak|1.1.13
Bookmarks|ale|0.15.2
scratchpad|awe|0.1.0
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
json-tools|eri|1.0.2
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
sublime-babel-vscode|jos|0.2.6
Go|luk|0.6.63
debugger-for-chrome|msj|3.1.7
indent-rainbow|ode|0.6.1
trailing-spaces|sha|0.2.11
vscode-react-native|vsm|0.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Press Command k + 0, to fold all sections in a file
2. Select a function that you want to read. Press Command k + j (and now it opens all the folds in the whole file, until the previous version, only the selected code section will be unfolded)

Reproduces without extensions: Yes/No

Yes

**Comment by aeschli** [comment]
Ctrl + k Ctrl + J is 'unfold all', regardless of the cursor position, that's as designed.
Try Ctrl + K Ctrl + ] (unfold recursively) which unfolds all at the current cursor location
