### ISSUE TITLE
Unable to open an untitled document with large size content (approximate > 5MB)

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#32608]
- VSCode Version: 1.15.0
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Call the API `workspace.openTextDocument({ 'language': language, 'content': content })` to open a new untitled document. If `content` is larger than 5MB, our code receives following error __expected URI untitled:Untitled-1 to have come to LIFE__
2. 
![image](https://user-images.githubusercontent.com/2796177/29347528-d9105684-827f-11e7-98d5-4584b2ecea4c.png)

**Comment by Huachao** [comment]
Maybe the cause is that the file content is larger than the sync limit https://github.com/Microsoft/vscode/blob/ae58b6765beca28c621aa6b4a3ba48630d58daff/src/vs/editor/common/model/textModel.ts#L115-L118

So in `mainThreadDocument.ts` won't add this to _modelIsSynced. https://github.com/Microsoft/vscode/blob/ae58b6765beca28c621aa6b4a3ba48630d58daff/src/vs/workbench/api/electron-browser/mainThreadDocuments.ts#L151-L154

Which finally caused the sync model check failed https://github.com/Microsoft/vscode/blob/ae58b6765beca28c621aa6b4a3ba48630d58daff/src/vs/workbench/api/electron-browser/mainThreadDocuments.ts#L238-L240

So if so, is this a right behavior for opening a large file size content?

**Comment by alexandrudima** [comment]
Yes, that constant is the root cause. Let's continue discussion in #32118, we should probably simply increase the constant.
