### ISSUE TITLE
Updated after completion of react inside the HTML5 code has a problem. For example, the a tag

### ISSUE THREAD

**Issue by gwiron** [Microsoft/vscode#32602]
# such as
![image](https://user-images.githubusercontent.com/15274257/29344546-3a56c5aa-826b-11e7-9a93-7f1f1a8a1dfd.png)

### Footer can auto complete
![image](https://user-images.githubusercontent.com/15274257/29344569-5a233f94-826b-11e7-9cde-6149ef3eae19.png)
click tab
![image](https://user-images.githubusercontent.com/15274257/29344597-82e88f56-826b-11e7-8680-213b355020c7.png)

**Comment by aeschli** [comment]
Please give more information. What are you expecting?

**Comment by gwiron** [comment]
For example: I enter the a tag, and then click the tab button to appear
"<a href=" "></a>"
It seems that after the update, most of the tags are not valid for HTML5 (or custom tags)

On 08/16/2017 17:50, Martin Aeschlimann wrote: Please give more information. What are you expecting?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aeschli in #32602: Please give more information. What are you expecting?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/32602#issuecomment-322721326"}}}

**Comment by ramya-rao-a** [comment]
@gwiron Can you try the latest insiders from https://code.visualstudio.com/insiders ?

If you still have issues, please share the code sample and file type

**Comment by gwiron** [comment]
Thanks. I'll try it tomorrow

On 08/16/2017 22:46, Ramya Rao wrote: @gwiron Can you try the latest insiders from https://code.visualstudio.com/insiders ?
If you still have issues, please share the code sample and file type

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ramya-rao-a in #32602: @gwiron Can you try the latest insiders from https://code.visualstudio.com/insiders ?\r\n\r\nIf you still have issues, please share the code sample and file type "}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/32602#issuecomment-322795307"}}}

**Comment by ramya-rao-a** [comment]
@gwiron We havent heard back from you in a while. I am assuming that your issue is solved in the Insiders build. If not feel free to drop in a comment here and we can get back to this

**Comment by gwiron** [comment]
Thank you very much, your reply! Your efficiency will make your company better

On 08/27/2017 04:34, Ramya Rao wrote: Closed #32602.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #32602."}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/32602#event-1222611563"}}}
