### ISSUE TITLE
Filter out impossible types in autocompletion for TypeScript comparison based on compared type

### ISSUE THREAD

**Issue by sgronblo** [Microsoft/vscode#32603]
- VSCode Version: Version 1.15.0 (1.15.0)
- OS Version: MacOS 10.12.6 (16G29)

Steps to Reproduce:

1. Here is a sample file, never mind the stupidity or validity of the subject:

```
enum HorseType {
    Striped = 'striped',
    Plain = 'plain',
    Green = 'green'
}

interface Horse {
    type: HorseType
}

interface Zebra extends Horse {
    type: HorseType.Plain
    zooName: string
}

interface DomesticHorse extends Horse {
    type: HorseType.Plain
    horseName: string
}

type NormalHorse = Zebra | NormalHorse

const testZebra: Zebra = {
    zooName: 'Ueno Zoo'
}

function horseIsZebra(horse: NormalHorse): boolean {
    return horse.type === HorseType.<CURSOR_HERE>
}
```
2. The auto completion that shows up at `<CURSOR_HERE>` shows all the three options for `HorseType` even though we know that `horse` being of type `NormalHorse` can only have the values `Plain` or `Zebra`, not `Green`. So, `Green` should be filtered out in this case.

Reproduces without extensions: Yes

**Comment by sgronblo** [comment]
I might add that if you were to pick `Green` in this case you would of course get a compiler error.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17837
