### ISSUE TITLE
Enable color picker for HTML

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#32611]
- VSCode Version: 1.16 Insider
- OS Version: macOS

Steps to Reproduce:

We already support color picker in builtin CSS extension. This can be done in the same way for CSS in HTML. 

@aeschli let me know if you think it's a good idea to roll in this feature to styles immediately for gathering feedback or you want to wait for the stabilization/more enhancements of Color Picker.

**Comment by aeschli** [comment]
Sure, makes sense. I'll add the color provider to the HTML extension.
