### ISSUE TITLE
'Extension host terminated unexpectedly' when resuming work 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#32615]
This morning, when starting to work again, I bring back the VSCode window to the front. It shows the message: 'Extension host terminated unexpectedly', but all seems to work well.

Can it be that the timer expired while my machine was in sleep mode?

**Comment by gregvanl** [comment]
Here's my console output when it happened to me today:

index.js:44 Error: write EOF
    at exports._errnoException (util.js:1050)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813)
onError @ index.js:44
events.js:163 Uncaught Error: write EOF
    at exports._errnoException (util.js:1050)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813)
messageService.ts:125 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
extensionHost.ts:388 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:388

**Comment by alexandrudima** [comment]
Let's track in #32620
