### ISSUE TITLE
[folding] Please do not call setHiddenAreas on each model change!

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3261]
Just noticed some scrollLeft jumping around when editing near the end of lines that are scrolled.
It jumps around because I reset the cached max line width on a view model flush event.
It is really unexpected to get on each type a view model flush, almost the entire view is trashed away!.

I noticed the folding permanently calls setHiddenAreas after each model change. This is not good.

**Comment by aeschli** [comment]
I added code to avoid calling setHiddenAreas unless a folded region has been updated.
