### ISSUE TITLE
Unity工程无法通过Open C# Project 打开Vs项目

### ISSUE THREAD

**Issue by hubluesky** [Microsoft/vscode#32614]
- VSCode Version: Code - Insiders 1.16.0-insider (728b2f9ad74bbec1dcde55dc42e5ea028661447d, 2017-08-16T05:16:50.783Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
xml|Dot|1.9.2
csharpextensions|jch|1.3.0
luaide|kan|0.4.3
cpptools|ms-|0.12.2
csharp|ms-|1.12.1
vscode-icons|rob|7.12.0
unity-debug|Uni|1.2.1

---

Steps to Reproduce:

1.使用unity5.6.2f1版本，设置Preferences/External Tool/External Script Editor 为VsCode
2.在Unity工程中右键使用Open C# Project
3.VsCode会打开，但不是Unity的项目，而是VsCode的安装目录

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This looks like an extension and not a VS Code problem. Please move this to the unity or C# repositories with this tool: https://github-issue-mover.appspot.com

**Comment by jimmyko** [comment]
Please try your best to create the issue in English. It is more easy for others searching the same problem.
