### ISSUE TITLE
Feature: shortcut to close the search / edit views

### ISSUE THREAD

**Issue by osher** [Microsoft/vscode#32613]
I got that Ctrl+Shift+E opens the (E)xplore and that Ctrl+Shift+F opens the (F)ind views - which is great.

What is the shortcut to close them? 
small screen... I don't want them open when I'm not looking - and now I have to reach for the mouse for it...

Thanks :)

**Comment by roblourens** [comment]
"Toggle sidebar", ctrl+b by default
