### ISSUE TITLE
only show emmet's intelligence after twice type when typing inside another tag.

### ISSUE THREAD

**Issue by narrowizard** [Microsoft/vscode#32618]
- VSCode Version: 1.15.0
- OS Version: Windows 10 Pro version 1607 build 14393.1593

Steps to Reproduce:

![](http://g.recordit.co/HqkXVeI2ER.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@narrowizard  I believe this has already been fixed. Please try the latest Insiders from https://code.visualstudio.com/insiders or wait for the 1.15.1 release
