### ISSUE TITLE
Usability request: Options for the Find/Replace-fields when opening Replace dialog

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#32617]
Almost every time I want to replace something, I press Ctrl + H and find that I need to step backwards with Shift + Tab to get to the find part of the dialog, enter what I want to be replaced, then step back to the replace part and enter what I want to replace it with. (Technically speaking I could enter that first but it's a unintuitive).

Maybe there already is a way to do this but I haven't been able to find it. 

I'd like some kind of option or possibility that whenever I hit Ctrl +  H with nothing selected, I start the process "from scratch" - with typing in what I want in the find textfield.

Here's an example of what I mean:

![vscode_replace](https://user-images.githubusercontent.com/1578924/29353323-144ea202-826a-11e7-90c5-bb1c69b5ffa7.gif)

I'd also like an option to _always_ start in the find textfield even if I have something selected to be able to modify it first, or copy it to the clipboard so I can paste it in the replace part. 

I'd also like an option to have the same text in both the find and in the replace-part. It's common for me to want to replace "LONG STRING THING 1" with "LONG STRING THING 2" and right now I have to type all of that in again or ensure that it's in my clipboard.

**Comment by rebornix** [comment]
This is already fixed in Insiders.
