### ISSUE TITLE
Code can not open a folder or file in onedrive on windows rs3 preview

### ISSUE THREAD

**Issue by panyang1217** [Microsoft/vscode#32619]
Code can not open a folder or file in onedrive folder that enabled the feature of file-on-demand.
after I upgraded my windows to RS3 preview. 

Code consider the path which I want to open as not exist, and try to create a new file with that path. 

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-pandoc|Dou|0.0.8
vscode-great-icons|emm|2.1.14
live-html-previewer|hdg|0.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
azurerm-vscode-tools|msa|0.3.6
debugger-for-chrome|msj|3.1.8
vscode-json-transform|oct|0.1.2
startanyshell|rem|0.3.1
vscode-icons|rob|7.12.0
vsc-jsonsnippets|wmo|0.1.4
html-css-class-completion|Zig|1.8.0

---

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
