### ISSUE TITLE
Cannot see how many downloads of extension

### ISSUE THREAD

**Issue by tuanakka0101** [Microsoft/vscode#32622]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.8.0-36-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vscode-great-icons|emm|2.1.14
MagicPython|mag|1.0.12
cpptools|ms-|0.12.2

I cannot see how many downloads of extension when search.

**Comment by aeschli** [comment]
@tuanakka0101 Please add a screenshot

**Comment by tuanakka0101** [comment]
![screenshot from 2017-08-21 17-06-07](https://user-images.githubusercontent.com/10155837/29514622-63436956-8693-11e7-8322-64db6404e128.png)

**Comment by sandy081** [comment]
@tuanakka0101 Expand the size of the extensions view to see more details. We show only some information if the width is small.
