### ISSUE TITLE
$updateSourceControl blocks for 500ms

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#32629]
* Have the git viewlet open
* Have ~30-40 modified files
* Have auto-save on
* Type and wait for auto-save to kick in

[Profile-20170816T121756.json.zip](https://github.com/Microsoft/vscode/files/1227847/Profile-20170816T121756.json.zip)
<img width="408" alt="screen shot 2017-08-16 at 12 18 36" src="https://user-images.githubusercontent.com/5047891/29358916-125129bc-827d-11e7-8e8f-15d5b8392660.png">

<img width="832" alt="screen shot 2017-08-16 at 12 19 14" src="https://user-images.githubusercontent.com/5047891/29358927-24a268c4-827d-11e7-883a-4b85b8b166ab.png">

**Comment by joaomoreno** [comment]
Fixed!

**Comment by alexandrudima** [comment]
Nice!
