### ISSUE TITLE
on opening the folder, folder tree structure not showing in sidebar. It only shows the folder name in titlebar

### ISSUE THREAD

**Issue by anshul0888** [Microsoft/vscode#32628]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.4
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.8.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
javadebugger|don|0.1.3
tslint|eg2|0.17.0
auto-close-tag|for|0.4.3
html-tag-wrapper|hwe|0.1.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Please provide more information, including screenshots.

**Comment by anshul0888** [comment]
In the sidebar when I open folder the folder tree is not showing. I shows the folder name in title bar only.
<img width="1440" alt="screen shot 2017-08-16 at 10 04 01 pm" src="https://user-images.githubusercontent.com/25046216/29374647-c5ec1a20-82cf-11e7-9fba-eed53dfe3e28.png">

**Comment by anshul0888** [comment]
sorry solved
