### ISSUE TITLE
Open another window by shift clicking on icon in taskbar

### ISSUE THREAD

**Issue by JPtenBerge** [Microsoft/vscode#32623]
- VSCode Version: 1.15.0, though this applies to all versions I've used so far.
- OS Version: Windows 10.

Reproduces without extensions: Yes

Since Windows 7, it's possible to click on an icon in the taskbar ('superbar') while holding down shift and it will open a second, third, nth window. It's a small accessibility feature so users won't have to right click the icon and then click the jumplist menuitem of opening another window.

Somehow, VS Code does not support this or actively prevents this. It does have a jumplist menuitem for new window, but shift-clicking the icon does not result in the expected behavior, it simply goes to one of the already opened windows.

It's a small thing, but I would really appreciate it if this could be fixed. Or is the current behavior chosen for a good reason I'm not aware of?

Thanks in advance.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
