### ISSUE TITLE
PHP 5.6 @return keyword in function documentation upsets the code highlighting

### ISSUE THREAD

**Issue by lokeb** [Microsoft/vscode#32624]
- VSCode Version: 1.15.0 (1.15.0)
- OS Version: Mac OSX 10.12.6

Steps to Reproduce:
1. Add @return (boolean) keyword to a method documentation
2. @return boolean does not produce this error

It takes return (boolean) as valid code keywords and the rest of the code after that is highlighted like comments or text.

If @return is replaced with @retur or something not @return, the documentation highlight works just 
fine.

In my case the methods are static.

**Comment by roblourens** [comment]
This sounds like https://github.com/atom/language-php/issues/245, it should be fixed in Insiders currently.
