### ISSUE TITLE
EH watchdog is triggered after sleep/wakeup

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#32620]
Since two days I'm always seeing the following alert when arriving at home or work:

![2017-08-15_23-03-41](https://user-images.githubusercontent.com/1898161/29353980-5185501a-826c-11e7-8874-ed7fd27ce997.png)
 
The dev console shows this:
![2017-08-16_10-19-26](https://user-images.githubusercontent.com/1898161/29354033-7f69c448-826c-11e7-8628-1c4e5ca8316a.png)

I never had any problems with VS Code previously. Now with the watch dog timer I have ;-)

Could it be that we have to consider sleep/wakeup events so that your timeout logic knows that the sleep phase is not an indication for the EH being unresponsive?

**Comment by alexandrudima** [comment]
(fixed via https://github.com/Microsoft/node-native-watchdog/commit/1adf91ae6b5adc8e8858e0bbb30f28502f85adcd)
