### ISSUE TITLE
mac open more than one window.

### ISSUE THREAD

**Issue by believeZJP** [Microsoft/vscode#32621]
- VSCode Version: latest
- OS Version: mac 

Steps to Reproduce:

1. open two window
2. use command + tab to change window,it's not working~~
  in the docker, only one window is show.
# change window is very difficult!!!

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@believeZJP on macOS you cannot switch windows using Cmd+Tab. 

See https://apple.stackexchange.com/questions/193937/shortcut-for-toggling-between-different-windows-of-same-app
