### ISSUE TITLE
Why does Format Document(ShiftAltF) gives different formatting from Format Selection(CtrlKCtrlF)

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [Microsoft/vscode#32625]
- VSCode Version: Code - Insiders 1.16.0-insider (728b2f9ad74bbec1dcde55dc42e5ea028661447d, 2017-08-16T05:16:50.783Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
p5js-snippets|aci|0.0.6
html-class-suggestions|And|1.0.7
Handlebars|and|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
bracket-pair-colorizer|Coe|0.10.8
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vsc-material-theme|Equ|1.0.2
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
search-node-modules|jas|1.1.1
Angular2|joh|2.4.0
node-module-intellisense|lei|1.4.0
unity-snippets-modified|lio|0.3.2
debugger-for-chrome|msj|3.1.8
color-highlight|nau|2.3.0
live-server-preview|neg|0.0.4
ejs-language-support|Qas|0.0.1
typescript-hero|rbb|1.4.0
vscode-icons|rob|7.12.0
angular-follow-selector|san|1.1.1
code-settings-sync|Sha|2.8.2
autoimport|ste|1.2.2
code-spell-checker|str|1.3.6
ejs-snippets|Tao|0.1.0
unity-tools|Tob|0.1.9
nodejs-extension-pack|wad|0.1.9
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.8.0

(16 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
@Abdullah-AlAttar Please attach a code sample, with steps how to reproduce.
