### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#32637]
- VSCode Version: Code - Insiders 1.16.0-insider (baa6fbece9035e3d20cbcb776d73ebc6c4ddde26, 2017-08-15T05:08:02.380Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.5.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Not sure wha happened. I had just fetched and pulled from our Git repo (using Tower), and when I switched back to Code I saw this:

<img width="1218" alt="screen shot 2017-08-16 at 8 46 50 am" src="https://user-images.githubusercontent.com/835148/29363903-adca0a4e-825f-11e7-8e70-59b181ce2da8.png">

Clicking "developer tools", I see this:

<img width="1055" alt="screen shot 2017-08-16 at 8 46 42 am" src="https://user-images.githubusercontent.com/835148/29363919-bb221ed4-825f-11e7-987f-d4bccdac1738.png">

I reloaded the window and now it seems fine.  Never saw that before.

**Comment by jtsom** [comment]
Yep. You're not alone. Something in a recent update seems to have changed the Extension Host process and it's throwing errors all over. There's another issue here, if you want to join the fun: https://github.com/Microsoft/vscode/issues/32530#issuecomment-322768715

**Comment by alexandrudima** [comment]
@smlombardi I think you were running into #32620

i.e. our new watchdog thread incorrectly believed that the extension host is unresponsive after a wake-up from sleep. Sorry about it, a fix will be out with the Monday build of the Insiders.
