### ISSUE TITLE
"Add cursor above" shortcut does not work

### ISSUE THREAD

**Issue by zessx** [Microsoft/vscode#32635]
Environment:

- VSCode Version: 1.16.0-insider
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Try to add a cursor below with <kbd>⌥</kbd><kbd>⌘</kbd><kbd>↓</kbd>: works
2. Try to add a cursor below with <kbd>⌥</kbd><kbd>⌘</kbd><kbd>↑</kbd>: does not work

Reproduces without extensions: Yes

Below is a screen capture of my keybinding, filtered on "alt cmd up" (first line is in French: "Add a cursor above"):
![image](https://user-images.githubusercontent.com/3398490/29363733-60b5f0f6-8291-11e7-81ea-8448e6e9f2d9.png)

**Comment by zessx** [comment]
I'm talking about a macOS issue there.  
As far as I remember, I never had this problem with Windows.

I tried the keybinding definition, and you're right, <kbd>cmd+alt+up</kbd> does not reach VS Code.  
I'll try to investigate and see if other softwares are interfering.

**Comment by zessx** [comment]
The hovering text:

> code: MetaLeft, keyCode: 91, key: Meta => UI: Alt+Commande+, user settings: alt+cmd+, dispatch: none

**Comment by alexandrudima** [comment]
@zessx Yes, I included a recording of Windows, but the steps are the same for OSX. I try to avoid always recording the same gif again ... and again ... and again :).

Yeah, it appears that we do not receive the keypress from the OS. My best guess is that you have something, either an app, or an OS setting, where `cmd+alt+up` is "stolen" by some other application or the OS itself.

You can try searching for this online to find out which other application is "stealing" that key combo... or if it is the OS itself. AFAIK, out-of-the-box OSX will allow `cmd+alt+up` to reach applications.

**Comment by zessx** [comment]
It works with:
- <kbd>CmdRight+AltRight+Up</kbd>
- <kbd>CmdLeft+AltRight+Up</kbd>
- <kbd>CmdRight+AltLeft+Up</kbd>

But not with:
- <kbd>CmdLeft+AltLeft+Up</kbd>

**Comment by alexandrudima** [comment]
That is bizzare. I have just tried it on my machine and for me it works for any `cmd` / `alt` combo, both on the laptop keyboard and on an external keyboard.

**Comment by zessx** [comment]
*That*: it works on my laptop, but not on my external keyboard.  
So this definitely looks like hardware-related.
