### ISSUE TITLE
Debug console: be able to disable automatic scrolling to end

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#32632]
- VSCode Version: Version 1.15.0 (1.15.0)
- OS Version: Darwin ecvaawplun5.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Steps to Reproduce:

1. Run a debug session that generates a lot of output.
2. The debug console will automatically scroll to the end.

Reproduces without extensions: No

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/630613/29359808-cf34f9cc-8288-11e7-8f83-a952f74f4256.png">

This has been tested with https://github.com/rubyide/vscode-ruby, but I would guess the same happens with other languages as well. When the debug console receives lots of output (say 10s or 100s of lines), it automatically scrolls to the bottom.

For me, this is annoying since the errors I am most interested in are most likely at the _beginning_ of the output. Means I have to scroll up manually every time.

Could we make this an option? (Auto-scroll on/off)

**Comment by weinand** [comment]
VS code supports "smart scroll", that means automatic scrolling only occurs if you are at the very end of the debug console. If you scroll at least one line up, automatic scrolling should stop (see this feature request https://github.com/Microsoft/vscode/issues/10486)

@isidorn I could not find "smart scroll" in the doc. We should add this to the doc.
In addition we could introduce a button that shows the state of "smart scroll" and can be used to control the behaviour directly.

**Comment by perlun** [comment]
Thanks for the reply @weinand!

> VS code supports "smart scroll", that means automatic scrolling only occurs if you are at the very end of the debug console. If you scroll at least one line up, automatic scrolling should stop (see this feature request #10486)

For me, this is not what happens. Every time I launch a task, the debug console is cleared, and it scrolls down to the bottom.

So, to make things clear: this is not dealing with a continuous debugging session, but more referring to the fact that "every time a task is launched, the debug console is cleared and gets scrolled all the way to the bottom unconditionally". Sorry for not being clear about that initially.

**Comment by isidorn** [comment]
Smart scroll is only supported for the output, not the debug console.

**Comment by madchap** [comment]
Smart scroll works to some extent in the "terminal" tab, until it must hit some buffer limitations of sort then you can't stop it to go to the bottom anymore (Linux)

**Comment by isidorn** [comment]
"Smart scroll" actually works now in the debug console. Thus closing this

My program
```
setInterval(() => {
    var count = Math.random() * 50;
    var message = Date.now() + 'new log message: ';
    for (var i = 0; i < count; i++) {
        message += ' ' + Math.random();
    } 
    console.log(message);
}, 200);
```

I have verified that when I am scrolled all the way to the end that the debug console will follow the latest output, however when I am scrolled not at the end that the output will be locked as expected.

Please note related issue that I am investingating https://github.com/microsoft/vscode/issues/107704
