### ISSUE TITLE
Error in the php color scheme

### ISSUE THREAD

**Issue by MioVisman** [Microsoft/vscode#32639]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open https://github.com/fluxbb/fluxbb/blob/master/include/functions.php
2. Find _lang/*/stopwords.txt_
3. All code below is a comment :(

![err1](https://user-images.githubusercontent.com/5917956/29366699-ed970bee-82c4-11e7-8d93-06742dee441d.gif)

**Comment by roblourens** [comment]
The problem actually starts on line 1610 where the PHP section ends in the middle of a function body, triggering https://github.com/atom/language-php/issues/246
