### ISSUE TITLE
Request: Make quickOpen dialog selected item background configurable

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#32643]
The selection background in dark theme is veryx low-contrast and in glare conditions it is downright impossible to make out which item (row) is currently selected.

![image](https://user-images.githubusercontent.com/821272/29368667-b0319216-82a0-11e7-920a-574fa42d983e.png)

**Comment by bpasero** [comment]
All configurable: https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by PunchyRascal** [comment]
Oh, sorry then! 

I didn't think of `list.focusBackground:` and `list.focusForeground`  before.
