### ISSUE TITLE
Can we please just dock the running debugger, floaty thing?

### ISSUE THREAD

**Issue by Adondriel** [Microsoft/vscode#32644]
- VSCode Version:
![image](https://user-images.githubusercontent.com/1113496/29368956-2d549fb8-826f-11e7-8bca-83dfaf886adf.png)
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Launch your project

Reproduces without extensions: (shouldn't matter)

Can we please make it so that, 
![image](https://user-images.githubusercontent.com/1113496/29369089-97176732-826f-11e7-9e42-f0c8d5466b91.png)
thing can be docked to just sit above this area: 
![image](https://user-images.githubusercontent.com/1113496/29369116-a86ca8ee-826f-11e7-8d61-7c4e5a6d5074.png)
it gets REALLY annoying having to move it back and forth, because it just loves to sit on top of the one tab that I am actively using, then I go to launch my attach to chrome task, and then it gets in the way of that, since I just moved it out of the way of my tabs!

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2513
