### ISSUE TITLE
Do not resolve symlinks when opening into Code

### ISSUE THREAD

**Issue by cbluth** [Microsoft/vscode#32649]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.16
hugofy|akm|0.1.0
better-toml|bun|0.2.0
python|don|0.7.0
json-tools|eri|1.0.2
Go|luk|0.6.63
terraform|mau|0.0.16
cpptools|ms-|0.12.2
gitlink|qez|0.2.3
Ruby|reb|0.14.0
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. mkdir -p ~/.kube
2. touch ~/.kube/config # this file contains yaml
3. ln -s ~/.kube/config ~/.kube/config.yaml
4. code ~/.kube/config.yaml
5. < at this point i would expect vscode to open ~/.kube/config.yaml and read it as a YAML file because of the extension and the file contents; but instead it opens ~/.kube/config and for some reason decides the contents are "Properties" >

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
For me it opens as empty file just like that:

![image](https://user-images.githubusercontent.com/900690/29412724-36564c7e-835a-11e7-9f80-3bd06f3c93c0.png)

It is true however that we resolve symlinks to their real path, so that is the issue at hand here.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by bpasero** [comment]
And there is actually a duplicate that is still open :)
