### ISSUE TITLE
VSCode - Integrated Terminal not clearing multi-lines entry when pressing ESC key.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#32646]
Integrated Terminal PowerShell not clearing multi-lines entry when pressing ESC key.  Please see Mike Robbins video tweet: 
Mike F Robbins @mikefrobbins 
@daviwil When pressing escape in the #PowerShell integrated terminal within #VSCode, only the first line of a multi-line command is removed. https://twitter.com/mikefrobbins/status/897831328233775104/video/1

- VSCode Version: 1.16.0-insider
- OS Version: Windows 10 Insider Build 16257
- PowerShell Extension: 1.4.1

Steps to Reproduce:

1. In the Integrated Terminal PowerShell, type a multi-line command:

```
Get-Childitem 'C:\Program Files\PowerShell\6.0.0-beta.5\modules' `
| Where-Object{$_.name -match 'Microsoft.'} `
| Select-Object Name;
```
2. Highlight, "Run Selection" and then up-arrow to see the multi-line code.

3. Finally, press the Esc Key to clear the lines -> result in only the first line.

Apparently, the multi-line code has been cleared but the terminal session still showing left over code. So, the pressing Esc key is not clearing the cursor line

![vscodeinsider_2017-08-16_11-11-17](https://user-images.githubusercontent.com/19892435/29370922-d5884586-8274-11e7-829d-0d80a4d65e53.jpg)

**Comment by daviwil** [comment]
Hey Max, this issue belongs over at the PowerShell/vscode-powershell repo, do you mind moving it there?

**Comment by MaximoTrinidad** [comment]
OK!  Thanks!
