### ISSUE TITLE
Emmet suggestions in jsx/tsx files get triggered for js/ts objects

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#32647]
jsx and tsx files get emmet by default.

i.e they get the `Emmet: Expand Abbreviation` feature as well as the emmet suggestions feature by default.

The latter can be annoying when a js dev types in something like `this.someproperty`. The first suggestion would be emmet trying to expand it to `<this class="someproperty></this>`

Current workaround is to set `emmet.showExpandedAbbreviation` to `inMarkupAndStylesheetFilesOnly`

**Comment by Ciantic** [comment]
I think the whole concept of Emmet suggestions in the same UI as auto-completion is broken. If the Emmet suggestions must be in same list, they shouldn't be first choice.

**Comment by ramya-rao-a** [comment]
Emmet abbreviation expansion is considered useful if its quick to execute. `tab` for emmet helped in that regard. Since that model had issues of its own, we introduced emmet in suggestions.

It shows up as the first choice, because in the world of markup and css, it makes sense. You type abbreviation, hit tab, first choice from selection gets selected, abbreviation is expanded.

But outside the world of markup and css, emmet as first choice doesn't make sense as @Ciantic  points out above.

jsx is the only one that falls into the category of "emmet supported by default in a non markup/css language" which is causing the current mess.

Ideally for languages that are not pure markup/css, the decision of whether to have emmet in suggestions should be passed to extensions that understand the language.

So imagine an extension that can identify the html like areas of a jsx file and calls emmet completions only in those areas. That would be the ideal solution.

**Comment by mdurling** [comment]
As an interim step, moving emmet completions to the bottom of the suggestions might be a reasonable compromise to completely disabling them, but thanks for the workaround @ramya-rao-a

**Comment by aleksey-bykov** [comment]
please how do i remove this emmet crap from my editor?

**Comment by coreh** [comment]
> So imagine an extension that can identify the html like areas of a jsx file and calls emmet completions only in those areas. That would be the ideal solution.

The problem with that is that JSX tags can basically go _anywhere_ an expression can go, which is too many places.

The proper fix for this should be checking: "*Is this emmet expression also a valid JS expression? Is the first item in the emmet completion an existing variable in the current scope?*" If yes to both don't display the suggestion at all, or move it to the bottom of the autocomplete list.

**Comment by ramya-rao-a** [comment]
@aleksey-bykov You can disable it by setting `emmet.showExpandedAbbreviation` to `never`

@coreh That's a great idea. I can do that by using the `vscode.executeDocumentSymbolProvider` command that will give me the symbols in the current file. The only catch is that the react components also show up as "variables". So if I do add this check, you won't get emmet suggestion for say `MyComponenet.someClassName`. The `Emmet: Expand Abbreviation` command would work as expected. This check would be added only for emmet in suggestion list

**Comment by coreh** [comment]
Hmm, hadn't thought about that case. I guess the `Component.someClass` syntax is only valid for components that have `className` in their props... I've seen that being used but I'm not sure how common of a pattern that is. For TSX files we could probably use the type info to only provide suggestions for these components.

One thing we should keep an eye for, if we add the symbol check, is that JS will be getting `#` for private fields soon. (If we add a special check just for `.className` we'll  hit this issue again when `#` becomes widespread enough.)

**Comment by ramya-rao-a** [comment]
@coreh Can you point me to some docs on the # thing?

**Comment by coreh** [comment]
https://github.com/tc39/proposal-class-fields#private-fields
https://tc39.github.io/proposal-class-fields/

It's already Stage 3 so it should be on the next edition of the language spec

**Comment by ramya-rao-a** [comment]
Tonight's Insiders build (which should be out in about 5 hrs) will have the fix as suggested by @coreh in https://github.com/Microsoft/vscode/issues/32647#issuecomment-325378558

Give it a try and let me know if any other cases need to be taken care of.
