### ISSUE TITLE
[Feature Request] Parent multi-root folders

### ISSUE THREAD

**Issue by joshuaptfan** [Microsoft/vscode#32645]
You should be able to tell a workspace to **auto-populate live with all the folders in one or more parent folders.** It would work like how a single-root window does now when you add a folder containing multiple repos, except with git integration for folders one level down from the parent.

Before I switched to Insider, that was how I used VS Code. I had my "GitHub" folder with all my repos open in one window in single root, and I did all git commands from the integrated terminal because git integration didn't support my setup.

### Use case
I wager that it's extremely common for students to have all their projects for a class or language organized in a single folder. Also, most IDEs let you configure a default project folder. With the current multi-root setup, they have to manually add a folder to the workspace every time they start work on a new assignment. This can get arduous if they are creating and deleting projects rapidly while testing.

### Scaling
What if people want git integration two levels down? Or three? Perhaps, instead, VS Code can simply do git integration at the first level where it encounters a valid .git folder. That is a much more scalable solution, but there may be caveats I'm unaware of. It will probably become much more feasible [once enough extensions have updated to support multi-root.](https://github.com/Microsoft/vscode/issues/396#issuecomment-315402932)

The considerations in this feature request may become unavoidable for the optimal user experience in the future, when multi-root becomes mature enough to become the default.

**Comment by Adondriel** [comment]
I think this was actually just released with version 1.15 https://code.visualstudio.com/updates/v1_15

**Comment by joshuaptfan** [comment]
I'm using multi-root now on the Insider branch. It currently only does git integration at the top level of each root folder (you must add repos individually, not folders of repos), similar to how git integration was only available before for 1 folder at a time in single-root.

I am suggesting a tweak to the current multi-root implementation on the Insider branch, with an eye towards streamlining that in mature implementations of multi-root.

**Comment by joaomoreno** [comment]
This will come with #31325
