### ISSUE TITLE
Codelens: Contributed command 'editor.action.showReferences-no-args-wrapper-14' does not exist.

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#3265]
When clicking on a code lens link the following error is generated:

`Contributed command 'editor.action.showReferences-no-args-wrapper-14' does not exist.`

This happens when clicking on the code lens link during an update to the code lens item.

This is just an example to show the error.

![animation](https://cloud.githubusercontent.com/assets/1727302/13238469/138dd98a-d9cb-11e5-80a1-c7a7ace81677.gif)

I'm currently working on an extension that see's this error a lot.
It appears that the contributed command is still registered during provideCodeLenses call

**Comment by pflannery** [comment]
Command id gets created here:
https://github.com/Microsoft/vscode/blob/70430f5c8c90b1c9757887a27bb0612e15bef192/src/vs/workbench/api/node/extHostTypeConverters.ts#L480

and I believe the error is thrown here:
https://github.com/Microsoft/vscode/blob/a19740d09116dfa736f767c0d3a4385af877fab4/src/vs/workbench/api/node/extHostCommands.ts#L84

**Comment by jrieken** [comment]
I understand how this can happen but only during a short update window and not permanently. @pflannery Do you have a snippet which helps me to reproduce this?

**Comment by pflannery** [comment]
By adding 'r' to the end of line 8 you should be able to recreate the issue in c#, or
install my plugin and attempt to update multiple versions in a package.json https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens

```cs
public class Main
{
  int someNumber = 0;

  public void run1()
  {
    this.someNumber++;
    this.someNumbe
    }
}
```

**Comment by pflannery** [comment]
nice one!
