### ISSUE TITLE
[Visual Studio Keymap] Ctrl+Backspace/Ctrl+Delete keys within commit message are intercepted by extension in main editor

### ISSUE THREAD

**Issue by prenetic** [Microsoft/vscode#32651]
- VSCode Version: 1.15.0
- OS Version: Windows 10 version 1703 (build 15053.540)
- Visual Studio Keymap Version: 0.1.7

Steps to Reproduce:

1. Install Visual Studio Keymap extension and reload.
2. Open an editor with any non-empty text file.
3. Place the cursor somewhere in the middle of the text file (remember where) to observe behavior.
4. Select the Source Control tab.
5. Begin typing a commit message (does not matter if file belongs to a repository or not), and then press Ctrl+Backspace to delete a word to the left of the cursor within the commit message.
6. Observe that the open file is now dirty and the word to the left of where the cursor in the main editor was placed in step 2 is now missing.
7. In the same commit message, press Ctrl+Delete to delete a word to the right of the cursor within the commit message.
8. Observe that the word to the right of the cursor in the main editor is now missing.

Reproduces without extensions: No

**Comment by prenetic** [comment]
@rebornix just realized there's a separate repo for this extension. I can re-file over there if necessary. I mistakenly landed here from the extension details after keying in on the "issue on GitHub" link.

**Comment by rebornix** [comment]
This issue was moved to rebornix/vscode-vs-keybindings#24
