### ISSUE TITLE
Using custom TypeScript SDK broke with the latest update

### ISSUE THREAD

**Issue by ADobin** [Microsoft/vscode#32658]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|4.3.3
tslint|eg2|0.17.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.8
debugger-for-edge|msj|0.4.1
vscode-subword-navigation|ow|1.1.5
qub-xml|qub|1.2.1
code-settings-sync|Sha|2.8.2
code-spell-checker|str|1.3.6
vscode-mermaid-preview|vst|0.5.0
wallaby-vscode|Wal|1.0.56

(1 theme extensions excluded)

---

Steps to Reproduce:

We are using a custom TypeScript SDK version that we have checked in with our code. Prior to the latest update we could do this `"typescript.tsdk": "Project/Tools/TypeScript/TypeScript-2.4.1/lib",` in our workspace config and it would use that version of TypeScript. After taking the latest update VS Code now says it can't load this version of TypeScript at this path.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I can't repo this on windows using a typescript version installed with npm

How did you install  the TypeScript version at `Project/Tools/TypeScript/TypeScript-2.4.1/lib`? Does a folder at that path exist and do you also have a `Project/Tools/TypeScript/TypeScript-2.4.1/package.json` file?

**Comment by ADobin** [comment]
We somewhat use the NPM version. We copy the contents out of the NPM package, specifically the lib folder, and have that checked in with our project. We have some legacy reasons for why we do that but that's currently how it is handled.

It does not have a package.json file, it just has the `tsserver.js` that the [documentation](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) says is needed. This has worked until the most recent update to VS Code.

I will give adding a package.json from the NPM package a shot but the documentation should be updated to reflect that is needed if that is the case.

**Comment by mjbvz** [comment]
Yes, we pick up Typescript version from `package.json` so this file is required. The `typescript` directory really should be a full install of TypeScript

I've submitted an update to the documentation to make this clearer: https://github.com/Microsoft/vscode-docs/pull/1135/files

**Comment by ADobin** [comment]
Sounds good, thanks for the quick response!
