### ISSUE TITLE
Terminal - bash (cygwin - grep) problem

### ISSUE THREAD

**Issue by jastorgalj** [Microsoft/vscode#32656]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tortoise-svn-for-vscode|cds|0.1.1
python|don|0.7.0
xml|Dot|1.9.2
code-runner|for|0.6.33
vscode-map-preview|jum|0.4.2
MagicPython|mag|1.0.12
vscode-todo|Mat|0.8.0
mssql|ms-|1.1.0
java|red|0.8.0
python|tht|0.2.3
sort-lines|Tyr|1.3.0

---
Error: text file running inside terminal says "Binary file" with grep command (cygwin)
outside VSC run normal

Steps to Reproduce:

1.  install cygwin and open bash terminal in VSC
2.  run grep command in a large text file    grep -v "ZZZ" <text file>

Reproduces without extensions: **Yes** same result

**Comment by Tyriar** [comment]
Can you take a screenshot of the error?
