### ISSUE TITLE
git autorefresh not working when saving files.

### ISSUE THREAD

**Issue by icenold** [Microsoft/vscode#32657]
- VSCode Version: 1.15.0 8b95971d8cccd3afd86b35d4a0e098c189294ff2

- OS Version: Zorin 12

Steps to Reproduce:

1. Open an active repository
2. Edit a file, source control won't show any changes
3. Hit F1>execute git refresh, source control will now show changes(you have to do this all the time now)

Reproduces without extensions: Yes, still the same

**Comment by joaomoreno** [comment]
If you leave Code's window open in the explorer view, and create a new file in your workspace outside of Code (say, in a Terminal), does the file appear in Code's explorer? Are file events working at all?

**Comment by icenold** [comment]
` If you leave Code's window open in the explorer view, and create a new file in your workspace outside of Code (say, in a Terminal), does the file appear in Code's explorer? Are file events working at all?`

Yeah it does show the new file I created via vim.

**Comment by joaomoreno** [comment]
@icenold Is this still an issue for you?

**Comment by icenold** [comment]
> @icenold Is this still an issue for you?

Nope. As far as I remember I'm not encountering this issue anymore.
I'm no longer using Zorin btw
