### ISSUE TITLE
Installation appears corrupt [Unsupported]

### ISSUE THREAD

**Issue by Charliekenney23** [Microsoft/vscode#32663]
Got this bug while working on a project. Don't know if it has anything to do with it, but I couldn't return (make new line) in vscode. My first instinct was to command+q and restart. Then I got the error "installation appears corrupt" and "[Unsupported]" was appended to the electron window title.

- VSCode Version: 1.15.0
- OS Version: 10.12.5

Steps to Reproduce: Not easily reproduced
![unsupported_vscode_bug](https://user-images.githubusercontent.com/23623237/29382824-e4568272-829b-11e7-9bf7-7e47b8ea5610.png)

[VS Files](https://drive.google.com/drive/folders/0B0yWaRQO_jjAZk0tdVZ4djZ2V0k?usp=sharing)

**Comment by Adondriel** [comment]
Have you attempted to re-install VSCode? My first guess is either the update broke it, or your hard drive might be failing.

**Comment by Charliekenney23** [comment]
Yeah I ended up fixing it myself by reinstalling VSCode, but this is the second time it's happened. I also don't think it's my SSD as my iMac is fairly new. This issue was supposed to be fixed as of a patch in June, I read while researching. Just wanted to share my files and the context in light of reinvestigating why this happens.

**Comment by Adondriel** [comment]
Yea, always try to keep your VSCode up to date, as even the stable build can cause issues. I was going to jokingly say that the bug was 100% because you're using a mac :P

**Comment by bpasero** [comment]
@Charliekenney23 did this happen after an update came in for VS Code?

**Comment by Charliekenney23** [comment]
@bpasero No I don't think so. I had been working on a project for about 4 hours, and when switching back to vscode I noticed the issue. As you can see I got the error on 1.15.0.

**Comment by bpasero** [comment]
@Charliekenney23 did you install a new extension? some extensions are known to change the installation bits for certain features.

**Comment by aron7** [comment]
can be because iMac uefi-firmware (sold as must have product at the market with corrupt Certification -->. hashtaq. can exported or dumped by stackoverflow via open port on the internet. the OS is total demented, ignorant of tje Bios amd vice versa. pc is locked and canot function

**Comment by Charliekenney23** [comment]
@bpasero The last extension I installed was the SASS plugin about a week prior to the installation breaking.
