### ISSUE TITLE
Add navigation arrows (back/forward) for NOT pinned files

### ISSUE THREAD

**Issue by MiguelLattuada** [Microsoft/vscode#32662]
- VSCode Version: 1.15.0
- OS Version: macOS Sierra (10.12.5)

Steps to Reproduce:

1. Open a typescript file (or any that you can pick "Go to definition" option) without pin it as image shows.
![screen shot 2017-08-16 at 5 01 29 pm](https://user-images.githubusercontent.com/5618566/29382964-b7b0042e-82a4-11e7-8df5-9fbc0ad5b963.png)
2. Go to pick definition at any type/function.
![screen shot 2017-08-16 at 5 03 37 pm](https://user-images.githubusercontent.com/5618566/29382991-e098fdaa-82a4-11e7-938c-81a5ff519e9c.png)
3. You have no way to navigate back. This is annoying when you're finding definitions for third party libraries where code is distributed (calling fileA.classA -> fileB.classB -> ...), we need a way to navigate back and forward, in the same tab without opening several tabs.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This does not work?
![image](https://user-images.githubusercontent.com/900690/29412519-786d487a-8359-11e7-9ef4-422e96cadbc5.png)
