### ISSUE TITLE
Feature Request: Run and Run Selection toolbar

### ISSUE THREAD

**Issue by tmmuessig** [Microsoft/vscode#32661]
In all of my PowerShell development, I have relied on the ISE.  In moving to VSCode, which is far superior, I find myself missing a huge time saving feature, the Run and Run Selection buttons.  I know that when you run an entire script, the small toolbar pops up with some of those buttons. When writing my PoSH code, I rarely run the entire thing until the end.  I write a piece, select it with the mouse and then hit the run selection button. Currently I have to bounce around from mouse to keyboard far to much. I know you can run a selection with F8, but I do all of my work on a laptop, where the F keys are a dual purpose type of thing.

I guess my Request in a round about sort of way, is there a way to get this tool bar to stay up permanently and include a button for Run Selection?

**Comment by rebornix** [comment]
To me it sounds like running and debugging on a selection.

**Comment by isidorn** [comment]
Please file this against the powershell extension here https://github.com/PowerShell/vscode-powershell
As they know how to best to propose an alternative to this feature with regards what vscode can do.
