### ISSUE TITLE
"Tab moves focus" should not be the default

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vscode#32668]
- VSCode Version: 1.15.1
- OS Version: Win7 x64

Steps to Reproduce:

1.  open new install or updated install
2.  start a new file (language doesnt really matter)
3.  type "function MyFunction"
4. hit enter
5  Type "{"  see closing brace appear
6. hit enter a few times to put blank space between the curlies
7. hit Tab to indent and start typing. 

Expected: cursor moves one tab or 4 spaces (whichever, i dont care) - and i can start typing

Actual: cursor is effectively lost. There is no visual indication of where it went, and I'm hammering the keyboard and getting ready to mothball vscode **again** when i see the green "Tab moves focus" in the status bar. 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
"Tab moves focus" is definitely not the default. It must be especially enabled via `Ctrl+M`. I cannot reproduce that on startup "Tab moves focus" is activated by default.

**Comment by StingyJack** [comment]
I downloaded the latest recommended update, and then couldn't indent. I don't use VSCode that often, and this was reported with my former laptop (now only good as a hand dryer - thanks VS 15.3).  I wonder if Ctrl+M conflicts with another shortcut key combo that VSCode may have had in the past.

I would still question the need for having a shortcut key for this feature out of the box, when a menu entry would be enough.

**Comment by alexandrudima** [comment]
We have added the "Tab moves focus" feature for accessibility purposes. We will not remove it. It is very easy to remove a keybinding if you don't like it: `ctrl+k ctrl+s` -> search for `ctrl+m` -> right click -> Remove keybinding

**Comment by nickclasener** [comment]
@StingyJack 
Did you find a solution?
