### ISSUE TITLE
Bug: Quick open does not include non-derived files when attempting to hide derived files in user settings.

### ISSUE THREAD

**Issue by stringham** [Microsoft/vscode#32665]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.4.0-83-generic

Steps to Reproduce:

In user settings I am hiding derived .js files with the following settings:
```json
    "files.exclude": {
        "**/*.js": {
            "when": "$(basename).ts"
        },
```

This works correctly in the file explorer, but I cannot find any `.js` files with `ctrl+p` unless I remove this rule from my user settings.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This should be fixed in 1.15.1 which was just released today.
