### ISSUE TITLE
JSON auto indent string with opening bracket

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#32660]
- VSCode Version: 1.15.0
- OS Version: Windows 10

Steps to Reproduce:

1. Set language to JSON
2. Write string including `{` or `[`
3. Hit Enter

`"editor.autoIndent": false`

Object:

![obj](https://user-images.githubusercontent.com/9638156/29381323-70eac57e-82d1-11e7-89e8-79b23907fffb.gif)

Reproduces without extensions: Yes

**Comment by sbarzowski** [comment]
I have experienced the same behavior in Go mode on Linux. i.e: 
```
buf.WriteString("{")<enter>
    <cursor here>
```
Not sure if related, maybe it should be a separate issue.

**Comment by rebornix** [comment]
![32660](https://user-images.githubusercontent.com/876920/45786187-29be9300-bc24-11e8-9d61-8c804ac753fe.gif)

This issue is gone in latest version.

**Comment by rebornix** [comment]
@usernamehw above gif was tested when `editor.autoIndent` was set to `true` and the language for the file is JSON, I'd love to see more information about how to reproduce.

**Comment by usernamehw** [comment]
Still can repro
* All extensions disabled
* Almost all settings - default, `"editor.autoIndent": true`
* File - `json`
```
VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:19:52.215Z)
OS version: Windows_NT x64 10.0.17134
```
