### ISSUE TITLE
`this` next to object spread in JSX element incorrectly highlighted

### ISSUE THREAD

**Issue by praxxis** [Microsoft/vscode#32667]
- VSCode Version: 1.15.1
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. `this` next to object spread in JSX element incorrectly highlighted

If you have `this` directly preceded by an object spread, the TM scope is `variable.other.object.tsx`:

<img width="608" alt="screenshot 2017-08-16 17 23 22" src="https://user-images.githubusercontent.com/15754/29385945-b97a9b9a-82a7-11e7-8258-2d5539937aff.png">

If you add a space between the spread and `this`, you get `variable.language.this`:

<img width="657" alt="screenshot 2017-08-16 17 24 37" src="https://user-images.githubusercontent.com/15754/29385968-ce358086-82a7-11e7-83eb-7ec54e8c6c39.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Please share a stripped down version of the the source code in those examples so I can investigate.

Thanks

**Comment by praxxis** [comment]
```tsx
import * as React from 'react';

class Test extends React.Component {
  foobar() {
    return {id: 'foobar'};
  }

  render() {
    const incorrect = <div {...this.foobar()}></div>;
    const correct = <div {... this.foobar()}></div>;

    return null;
  }
}
```

Ha, it actually manifests in GitHub's highlighting too.

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/502 to track this upstream
