### ISSUE TITLE
Empty VSCode window when interactively rebasing with git from WSL Bash

### ISSUE THREAD

**Issue by jcjolley** [Microsoft/vscode#32669]
- VSCode Version: Code - Insiders 1.16.0-insider (728b2f9ad74bbec1dcde55dc42e5ea028661447d, 2017-08-16T05:16:50.783Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
bracket-pair-colorizer|Coe|0.10.8
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
docthis|joe|0.4.7
Angular2|joh|2.4.0
vscode-codemetrics|kis|1.9.0
typescript-hero|rbb|1.4.0
language-stylus|sys|1.7.3
vim|vsc|0.9.0

---

Steps to Reproduce:

1. in WSL bash, set vscode to be the git editor `git config --global core.editor "code-insiders --wait"
2. `git rebase HEAD~2 -i`

Reproduces without extensions: Yes

This works just fine when starting from any windows terminal window, but fails when using WSL bash.
![vscode_git_rebase_fail](https://user-images.githubusercontent.com/2086176/29387269-79339f9c-829c-11e7-834b-ecfecd5b8832.gif)

**Comment by joaomoreno** [comment]
#29812
