### ISSUE TITLE
Vertical Black Line

### ISSUE THREAD

**Issue by terrybrashaw** [Microsoft/vscode#32677]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
- User Settings:
```json
{
    "editor.autoClosingBrackets": false,
    "editor.codeLens": false,
    "editor.folding": false,
    "editor.fontFamily": "Fira Mono Medium",
    "editor.glyphMargin": false,
    "editor.mouseWheelScrollSensitivity": 2.5,
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    },
    "editor.dragAndDrop": false,
    "editor.minimap.enabled": false,
    "editor.renderIndentGuides": true,
    "editor.renderLineHighlight": "all",
    "editor.rulers": [
        100
    ],
    "editor.formatOnSave": true,
    "editor.suggestOnTriggerCharacters": false,
    "editor.wordBasedSuggestions": false,
    "editor.wordWrap": "off",
    "extensions.ignoreRecommendations": false,
    "files.autoSave": "onWindowChange",
    "files.insertFinalNewline": true,
    "git.enabled": true,
    "search.useIgnoreFilesByDefault": false,
    "telemetry.enableTelemetry": false,
    "typescript.check.npmIsInstalled": false,
    "window.menuBarVisibility": "toggle",
    "window.restoreWindows": "none",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": false,
    "workbench.colorTheme": "Default Light+",
    "workbench.editor.enablePreview": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.editor.tabCloseButton": "off",
    "workbench.iconTheme": "vs-seti",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.visible": false
}
```
---

Steps to Reproduce:

1. Set Windows display scaling to 125% (and probably 2560x1440 resolution, idk if that matters)
2. Resize the VSCode window, resize the sidebar, highlight random code, and scroll the window until the black line randomly appears in between the gutter and the code-window.

I haven't been able to narrow the cause down any more than that. Here's a video of me reproducing the issue: https://www.youtube.com/watch?v=tchm-VDwAGA

Screenshot:
![image](http://i.imgur.com/SWUjwA2.png)

**Comment by alexandrudima** [comment]
ugh, that is awful... 

The bad news is that we don't render anything in there, so it would be Chromium that has a bug of sorts (probably between different GPU layers, caused by rounding errors) where a line sneaks in.

You could try using our "hidden" setting `"editor.disableLayerHinting": false`. This will make it that we stop giving GPU layer hints and perhaps Chromium will stop making separate GPU layers for the text and the line numbers.

This might result in slower scrolling, but might lead to this annoyance going away
