### ISSUE TITLE
Expose 'getCurrentLanguage()' as a command

### ISSUE THREAD

**Issue by anthonyn60** [Microsoft/vscode#3267]
Right now, there's a method within the 'languages' namespace called getLanguages() which returns all available language identifiers.

It would be great if there was a similar method which returned the language the user has currently set. This is a method I'd like to have for an extension I'm writing.

**Comment by jrieken** [comment]
You can do that from a `document` using (document#languageId)[https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L126]
