### ISSUE TITLE
Color picker doesn't work in stylus file (*.styl), maybe it only work in *.css file.

### ISSUE THREAD

**Issue by vimcaw** [Microsoft/vscode#32678]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
yaml|ada|0.0.7
markdown-preview-github-styles|bie|0.0.2
regex|chr|0.1.0
vscode-hexo|cod|1.0.1
vscode-html-css|ecm|0.1.7
hexo-tag-snippets|max|0.1.7
cpptools|ms-|0.12.2
ejs-language-support|Qas|0.0.1
vscode-icons|rob|7.12.0
language-stylus|sys|1.7.3
ejs-snippets|Tao|0.1.0
open-in-browser|tec|1.1.0
vscode-arduino|vsc|0.2.4
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

Color picker doesn't work in stylus file (*.styl), maybe it only work in *.css file.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
The language-stylus has to adopt the color decoration provider. That said, the API is still in the 'proposed' state.

**Comment by aeschli** [comment]
This issue was moved to d4rkr00t/language-stylus#51
