### ISSUE TITLE
JQuery IntelliSense

### ISSUE THREAD

**Issue by Forguz** [Microsoft/vscode#32676]
An intellisense of JQuery would be good because it is an excellent framework and I did not find anything related to it in VS CODE

**Comment by CnSimonChan** [comment]
If you are using `npm`, you can run `npm i -D @types/jquery` to install the type definition (it will work even if your projects are not using `npm`).

Then add `/// <reference types="jquery" />` to the top of each files that using jQuery.

Now you should get IntelliSense of jQuery like this.

![image](https://user-images.githubusercontent.com/1330321/29392495-c39ce1d0-8330-11e7-99cf-b0416cdfc126.png)

(It's not a VS Code thing, it's powered by the TypeScript language server and the awesome [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) project, any editor with TypeScript support should work.)

**Comment by mjbvz** [comment]
Thanks @CnSimonChan! Closing as those steps should resolve this
