### ISSUE TITLE
Python syntax hilighter fail on multi-line """ string

### ISSUE THREAD

**Issue by ssteinerx** [Microsoft/vscode#32670]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
EditorConfig|Edi|0.9.4
mithril-emmet|Fal|0.6.1
beautify|Hoo|1.1.1
latex-workshop|Jam|3.3.2
vscode-docker|Pet|0.0.16
vscode-file-templates|bam|1.1.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
vscode-quick-select|dba|0.2.4
githistory|don|0.2.3
python|don|0.7.0
prettier-vscode|esb|0.22.1
code-runner|for|0.6.33
code-python-isort|fre|0.0.3
Python-autopep8|him|1.0.2
sublime-babel-vscode|jos|0.2.6
MagicPython|mag|1.0.12
vscode-icons|rob|7.12.0
rewrap|stk|1.4.2
bootstrap4-vscode|the|2.4.0
python|tht|0.2.3
expand-selection-to-scope|vit|0.2.0
vscode-react-native|vsm|0.4.1
gitblame|wad|2.1.0
ReactSnippets|xab|1.4.0
extractcomponent|zuc|1.0.1
---

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
restr = r"""
    \s* \{ ( [^}]+ ) \} # directive (meta or block)
|
    \[ ( [^\]]+ ) \]    # chord
|
    \s* \#  ( .+ )      # comment - only if # is not in chord or directive
|
    ( [^[]+ )           # lyric
"""

if False:
    print("This is not properly syntax hilighted")
```

Steps to Reproduce:

1. Open the enclosed hunk-o-python
2. Observe the not-syntax-hilightedness

**Comment by aeschli** [comment]
That's what I get in the latest:
![image](https://user-images.githubusercontent.com/6461412/29411396-ecc8be5c-8354-11e7-9e2c-e3163d408177.png)

That doesn't look too wrong to me, but I'm a novice with Python.
What's white are operators. The Default+ theme colors these the default foreground color, so it's the expected result.

**Comment by aeschli** [comment]
@ssteinerx please let me know if I should move this issue to the provider of the Python grammar (https://github.com/MagicStack/MagicPython)

**Comment by ssteinerx** [comment]
@aeschli Not sure what "latest" means, I've got what's shown in the original issue.  Is your version ahead of that?

Also, it doesn't show in my little snippet, but it never recovers...the entire rest of the file is hilighted as a string.  Interestingly, the entire triple-quoted string itself is not the reddish of the """ string as shown in your screenshot, it's the brown of the regular double-quoted string as in the print() shown in the snippet which may give a clue as to where it's getting lost.

**Comment by ssteinerx** [comment]
@aeschli as for whether to move it, the MagicPython repo says:
  >  Used by GitHub to highlight your Python code! 

and the code actually highlights properly here on GitHub, so this appears to be a VSCode issue.

**Comment by aeschli** [comment]
@ssteinerx I just updated VSCode to use the latest Python grammar, and my screenshot is based on that. It will be in tomorrows insiders build.
To me it looks like there was a fix. Closing the issue as fixed then.

**Comment by ssteinerx** [comment]
Just updated to Version 1.15.1 (1.15.1), 41abd21afdf7424c89319ee7cb0445cc6f376959
 and am still having the same issue.  Not sure I wasn't already on that version, though...

**Comment by ssteinerx** [comment]
Just grabbed the Insiders release, only installed the 3 Python extensions as recommended, exactly same as previously reported.

Please reopen unless the "Insiders release" I just downloaded is earlier than the one in which you're seeing it fixed and I guess I'll wait 'till tomorrow to reconfirm.

- VSCode Version: Code - Insiders 1.16.0-insider (9e7441df9f609500a13e8651bd01eccf1613f386, 2017-08-17T09:18:01.132Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
MagicPython|mag|1.0.12
python|tht|0.2.3



---

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
restr = r"""
    \s* \{ ( [^}]+ ) \} # directive (meta or block)
|
    \[ ( [^\]]+ ) \]    # chord
|
    \s* \#  ( .+ )      # comment - only if # is not in chord or directive
|
    ( [^[]+ )           # lyric
"""

if False:
    print("This is not properly syntax hilighted")
```

Steps to Reproduce:

1. Load the snippet above
2. Notice the not-properly-highlighted code.

![screen shot 2017-08-17 at 2 07 11 pm](https://user-images.githubusercontent.com/43063/29426685-6b3a958a-8355-11e7-9b67-559f89003046.png)

**Comment by aeschli** [comment]
Please give it a try today. The insiders builds are updated every night. The latest one 2 hours ago.

**Comment by ssteinerx** [comment]
Just updated to: 
```
    Version 1.16.0-insider (1.16.0-insider)
    aebaece67321b35f133be393fe8adcd50333d5ee
```

No further updates available, identical (not properly) highlighting.

**Comment by ssteinerx** [comment]
Extensions are the same as previous "insiders build" report, only the three Python ones, MagicPython 1.0.12, Python 0.7.0, and Python for VSCode 0.2.3.
