### ISSUE TITLE
a little bug when folding code block

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#32675]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
regex|chr|0.1.0
vscode-html-css|ecm|0.1.7
vscode-great-icons|emm|2.1.14
vsc-material-theme|Equ|1.0.2
json-tools|eri|1.0.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-rename-tag|for|0.0.14
mdhelper|jos|0.0.11
debugger-for-chrome|msj|3.1.8
material-icon-theme|PKi|2.1.0
vscode-css-peek|pra|1.3.1
markdown-preview-enhanced|shd|0.2.5
html5-boilerplate|sid|1.0.1
quokka-vscode|Wal|1.0.50
wallaby-vscode|Wal|1.0.56
html-css-class-completion|Zig|1.8.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.fold a code block

use tab to indentate

![000](https://user-images.githubusercontent.com/12824616/29394864-ca6f6f46-833f-11e7-888b-90ab0156a179.gif)

use dot to indentate
![001](https://user-images.githubusercontent.com/12824616/29394870-d0bc5daa-833f-11e7-9916-651d061c8e50.gif)

Reproduces without extensions: Yes

**Comment by deepkolos** [comment]
![000](https://user-images.githubusercontent.com/12824616/29394864-ca6f6f46-833f-11e7-888b-90ab0156a179.gif)

![001](https://user-images.githubusercontent.com/12824616/29394870-d0bc5daa-833f-11e7-9916-651d061c8e50.gif)

another bug is also obvious

![2017-08-17_113210](https://user-images.githubusercontent.com/12824616/29394883-e0bc084a-833f-11e7-948e-c0bbaa30a2a2.png)

**Comment by aeschli** [comment]
@deepkolos Sorry, I can't see the issue. Can you paste also the code snippet? Or make an animated gif that also shows the folding markers?

**Comment by aeschli** [comment]
For the second, issue, can you file a separate bug? Again with code sample and a description of the bug?

**Comment by deepkolos** [comment]
@aeschli done update the description and new another issue

**Comment by aeschli** [comment]
Please paste the code snippet...

**Comment by aeschli** [comment]
Closing due to lack of information.
