### ISSUE TITLE
When change the tab or input in the chrome, the VSCode will change the content of blank tab.

### ISSUE THREAD

**Issue by icesman** [Microsoft/vscode#32679]
- VSCode Version: 1.15.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1.Open the VSCode and close all the tab, only some introduction left, it looks like this
![2017-08-17 9 34 01 2](https://user-images.githubusercontent.com/12438996/29392248-3e6d8d44-832f-11e7-9017-50c0689ebf9a.png)

2.And the Chrome is running in the other screen, when you do some operations in the Chrome, the content in the VSCode '切换终端 ^`' will change to '切换终端 未绑定'. 

I wonder whether there is a timer in the VSCode to detect which terminal to use.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
So you are saying the introduction text changes when another application gets the focus?

**Comment by chrmarti** [comment]
The shortcut should only update when you change it through VSCode > Preferences > Keyboard Shortcuts. (Or: when you change the keybindings.json directly.)

**Comment by icesman** [comment]
@aeschli Yep! I put the VSCode on the other screen and stay focus on the screen of Macbook, when I operated on the current screen, it may trigger the introduction text changes.

**Comment by icesman** [comment]
@chrmarti  I don't change any configure of the VSCode and just operated on the other application. I think whether if the electron use the same context of the V8 and then cause the text change in the VSCode firstly, but I find the text also changes when I open another application such as Preview.

**Comment by alexandrudima** [comment]
The shortcuts update **also** when the keyboard layout is changed. We listen to the [`kTISNotifySelectedKeyboardInputSourceChanged`](https://github.com/Microsoft/node-native-keymap/blob/37c21529b2684d01c7a7527dbbde5382de9c698d/src/keyboard_mac.mm#L210) OSX notification. 

This gets sent to us by the OS when the keyboard layout changes and we then proceed to update all of our UI labels to reflect the new keyboard layout.
