### ISSUE TITLE
VSCode does note work with new win10 place holders.

### ISSUE THREAD

**Issue by jongross4** [Microsoft/vscode#32674]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.16252
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|4.3.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1.Open files in a One Drive "placeholder" folder.  Files are actually local to machine
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
#27285
