### ISSUE TITLE
Emmet not working on latest version

### ISSUE THREAD

**Issue by nguyen-tho-mulodo** [Microsoft/vscode#32684]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 15.5.0
- Extensions: 

Emmet not work when use tab key on document (php, html, twig,...) when i update to version 1.15.0

Please fix it, thanks 💯

**Comment by ramya-rao-a** [comment]
@nguyen-tho-mulodo Please upgrade to VS Code 1.15.1 and set `emmet.triggerExpansionOnTab` to `true`

There have been quite a few changes to Emmet. Please read go through the below links
[Emmet docs](https://code.visualstudio.com/docs/editor/emmet)
[Emmet 2.0 blog](https://code.visualstudio.com/docs/editor/emmet)

**Comment by nguyen-tho-mulodo** [comment]
@ramya-rao-a thanks very much! :)
