### ISSUE TITLE
VSCode add a semicolon automatically when define a struct or class?

### ISSUE THREAD

**Issue by Coresi7** [Microsoft/vscode#32685]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. create a .c file (effective for many file extensions, include .cpp, .shader, .cginc  etc)
2. type "struct" and a left brace, with setting "editor.autoClosingBrackets" is true.

**Comment by aeschli** [comment]
Sorry, I have to guess here. You want that left brace adds the right brace AND a semicolon?

Please complete the description with description and maybe a code snippet that shows what you propose.

**Comment by Coresi7** [comment]
@aeschli Yeah, you've got the point. This is what I mean.

**Comment by aeschli** [comment]
If this should only happen for structs, then you need to make this request against a c/c++ aware extension (https://github.com/Microsoft/vscode-cpptools/issues). Or have a look at providing this feature in your own extension.

**Comment by Coresi7** [comment]
@aeschli ... But  I dont know if c/c++ extension should take effect when editing a shader, however, vscode is the best editor tool i've ever find for shaderlab editing.
