### ISSUE TITLE
Environment variable not working as includePath for C++

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#32688]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.2

---

Steps to Reproduce:

1. Add environment variable as part of the includePath array.  Example:

"includePath": [
                "${env:INCLUDE}"
            ],

where INCLUDE is an environment variable of contents "C:/include; C:/include2; etc"

2. Note this neither works for standard delimited lists as part of the environment variable nor if the environment variable is just a single item like C:/include

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Please file this issue against https://github.com/Microsoft/vscode-cpptools/issues
