### ISSUE TITLE
Remove extension unknow error

### ISSUE THREAD

**Issue by purocean** [Microsoft/vscode#32683]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:
click uninstall extension
![image](https://user-images.githubusercontent.com/7115690/29394613-21ddf740-833e-11e7-88ba-7f256005803a.png)
![image](https://user-images.githubusercontent.com/7115690/29394632-33569752-833e-11e7-9f46-68d1580ca30d.png)

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
@rebornix Can you help with translation?

**Comment by purocean** [comment]
@aeschli 
*An unknown error occurred. For more information, see the log.*

Where is the log file?

**Comment by aeschli** [comment]
There's no other log file.

What extension did you uninstall?
