### ISSUE TITLE
WinSCP issue, Empty Editors

### ISSUE THREAD

**Issue by mizagog** [Microsoft/vscode#32687]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
google-search-ext|ade|0.1.2
jsrefactor|cms|1.4.1
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
python|don|0.7.0
xml|Dot|1.9.2
tslint|eg2|0.17.0
code-runner|for|0.6.33
macros|ged|1.2.0
gc-excelviewer|Gra|1.1.15
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
code-file-nav|jak|0.7.2
expand-region|let|0.0.3
sftp|lix|0.7.7
MagicPython|mag|1.0.12
Kotlin|mat|1.3.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.8
advanced-new-file|pat|0.5.0
material-icon-theme|PKi|2.1.0
typescript-hero|rbb|1.4.0
java|red|0.8.0
vscode-icons|rob|7.12.0
vscode-dired|rru|0.0.4
code-settings-sync|Sha|2.8.2
vscode-table-formatter|shu|1.2.1
code-clip-ring|Sir|0.0.4
vscode-fileutils|sle|2.6.2
vscode-multiclip|sle|0.1.2
code-spell-checker|str|1.3.6
org-mode|too|0.1.3
vim|vsc|0.9.0
JavaScriptSnippets|xab|1.4.1
local-history|xyz|1.3.0

(6 theme extensions excluded)

---

Steps to Reproduce:

1. Open file from WinSCP
2. Extra empty editors show up:
'Code.exe' 'VS' 'Microsoft' 'Files'

this was not an issue before 1.15

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@mizagog Please give more details, maybe with screenshots. Not clear how to 'Open file from WinSCP'

**Comment by mizagog** [comment]
Sorry, wasn't sure how to add an image to my post :')
But now that i've looked more carefully at my screenshot, i realized i add some extra words in my file path, and after removing them the issue is resolved. thanks for your swift reply :)
