### ISSUE TITLE
compile failed use typescript@1.8.2

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode#3269]
I use `scripts\npm install` 
get
typescript@1.8.2 node_modules\typescript.

and then run `gulp watch`

get

	*** Error: D:/workSpace/vscode/vscode/src/vs/editor/browser/standalone/standalon
	eCodeEditor.ts(199,3): 'super' must be called before accessing 'this' in the con
	structor of a derived class.
	*** Error: D:/workSpace/vscode/vscode/src/vs/editor/browser/standalone/simpleSer
	vices.ts(219,3): 'super' must be called before accessing 'this' in the construct
	or of a derived class.
	*** Error: D:/workSpace/vscode/vscode/src/vs/editor/browser/standalone/simpleSer
	vices.ts(220,3): 'super' must be called before accessing 'this' in the construct
	or of a derived class.
	*** Error: D:/workSpace/vscode/vscode/src/vs/editor/browser/config/configuration
	.ts(275,3): 'super' must be called before accessing 'this' in the constructor of
	a derived class.
	*** Finished with 57 errors.

I try to roll back typescript to 1.8.0. 

`gulp watch` will be successfully executed

**Comment by chadbr** [comment]
So... wait for the next vscode to upgrade to 1.8? @joaomoreno 

Thanks --

**Comment by joaomoreno** [comment]
@chadbr This issue was about the development of VS Code itself. It couldn't be compiled against 1.8.2.

The next VS Code will indeed come with the 1.8.2 **language service**, but that's another matter.

**Comment by bitflower** [comment]
I have the same problem in VS2015, TS 1.8.9, Gulp executes.
