### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover

### ISSUE THREAD

**Issue by cybernetics** [Microsoft/vscode#32699]
- VSCode Version: 1.16.0-insider
- OS Version: win7 (64-bit)

Steps to Reproduce:

1.
![ext-error](https://user-images.githubusercontent.com/79887/29400978-2d70b7e6-82e4-11e7-867e-81a61b6d189e.png)
2.
![extns-installed](https://user-images.githubusercontent.com/79887/29401077-95463832-82e4-11e7-8090-e68ee1eb769a.png)

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
@cybernetics

Is there any error printed in the Developer Tools ? What is the exit code of the extension host process ?

Does this happen for you every time you start VS Code (without doing anything with VS Code) or does the crash occur after doing specific steps ?

Have you recently upgraded from 32 bit to 64 bit VS Code and kept all of those extensions ?

Finally, do you think you were running into #32620 (i.e. putting the computer to sleep) -- a fix for it will make its way into the Insiders version coming out on Monday.

**Comment by cybernetics** [comment]
@alexandrudima 

Is there any error printed in the Developer Tools ? What is the exit code of the extension host process ?
![image](https://user-images.githubusercontent.com/79887/29490293-c4de479c-84ec-11e7-9280-7545c77d08d6.png)

Does this happen for you every time you start VS Code (without doing anything with VS Code) or does the crash occur after doing specific steps ? 
Yes, happens every time I start VS Code (without doing anything with VS Code)

Have you recently upgraded from 32 bit to 64 bit VS Code and kept all of those extensions ?
Yes, I uninstall 32-bit and then installed 64-bit VS Code

Finally, do you think you were running into #32620 (i.e. putting the computer to sleep) -- a fix for it will make its way into the Insiders version coming out on Monday.
No, I did not run into #32620... it happened just after installing and happens after every launch

**Comment by alexandrudima** [comment]
We've removed the watchdog for now (see #26445)
