### ISSUE TITLE
(Suggestion) Find in Files support include or exclude sub-directory

### ISSUE THREAD

**Issue by airthomas** [Microsoft/vscode#32690]
- VSCode Version:1.15.0
- OS Version:Windows 10

Suggestion only:
Find in Files support include or exclude sub-directory

**Comment by aeschli** [comment]
Search already supports including and excluding folders.
![image](https://user-images.githubusercontent.com/6461412/29406002-fa0dc810-833f-11e7-9ea0-124a7e8ccd4d.png)

@airthomas Please give more details on what's missing or what's not working

**Comment by airthomas** [comment]
For example, I only need to search current folder and the current folder has sub-folder x 20, any method to easier to change current exclude all sub-folders? suggest to add a checkbox etc to include/exclude sub-folder. Many thanks.

Below is JEdit search windows, if available, please also support "Ignore Case" search.
![image](https://user-images.githubusercontent.com/4132152/29419191-0ab7d58c-83a1-11e7-85eb-f60fb2060463.png)

**Comment by roblourens** [comment]
You can ignore them by name with the `exclude` boxes or the `search.exclude` setting, but I think a `Search subdirectories` option is too detailed for our search viewlet.

Some docs here: https://code.visualstudio.com/docs/editor/codebasics#_search-across-files
