### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dl-88** [Microsoft/vscode#32691]
- VSCode Version: Code 1.15.1 **[Unsupported]** (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.1.0
background|sha|1.1.15

---

Steps to Reproduce:

1.*.sql文件中，从某一行末尾开始往前选择一部分文本后，按下Ctrl+F键，再点击该行末尾处，会自动把选择的内容在末尾处复制粘贴出来。这是VSCODE一个特殊的复制粘贴功能吗？还是单纯的BUG？
2.

Reproduces without extensions: Yes/No

**Comment by CnSimonChan** [comment]
Translation:

> In a `.sql` file, select some text from the end, press `Ctrl + F`, then click at the end position of the line, the selected text will be duplicated at the end automatically, is this a special feature, or just a bug?

There is a feature allows you to use `Ctrl + Mouse drag` to duplicate selected text.

But seems press `Ctrl + F` doesn't clear the `Ctrl` press state, so drag anywhere will cause a duplication.

In fact you must move your mouse a little bit to trigger, just click somewhere will just move your cursor to there.

So in my opinion, it's a bug.

**Comment by r3wt** [comment]
@rebornix this is similar the issue i have reported, previously, the the ctrl commands are piling up into weird sequences that cause problems. this editor is GARBAGE!

**Comment by rebornix** [comment]
It's drag and drop, thanks ;)
