### ISSUE TITLE
Mac-The Window is no Longer responding

### ISSUE THREAD

**Issue by caronyan** [Microsoft/vscode#32697]
- VSCode Version: 1.15.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1.Occurred during coding frequently;
2.I have tried to record timeline and profile, results are shown below, it seems spend a lot of time scriping but I dont know why.
3.The following png and profile are record in difference cases, but point to the same question.
![timeline](https://user-images.githubusercontent.com/8968282/29399471-f39bca60-835b-11e7-827a-8fead48d84bc.png)
[profile.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1230339/profile.cpuprofile.zip)

Reproduces without extensions: No

**Comment by aeschli** [comment]
@caronyan Can you describe what actions you did before the window froze? Is it reproducible?

**Comment by caronyan** [comment]
@aeschli Nothing special. It happens randomly when I editing a file by cursor movement, code insert or window scroll, all actions that change the file may cause the problem.

And, it happens frequently in a short period of time,  but behave normally then, intermittently.

BTW, the file type is .vue.

**Comment by aeschli** [comment]
@caronyan Does it reproduce with extensions disabled?

**Comment by caronyan** [comment]
@aeschli I tried that and it is ok until now.But I still can't locate the wrong point because it sometimes behave normally with extensions.

**Comment by caronyan** [comment]
@aeschli Maybe you can close the issue because it never appear again.But I found some cases may cause the window froze(window respond after a while).When I keep the search panel opened with keyword and make some changes, like webpack rebuilding which generate masses of compressed js or css, window froze like there exists a thread blocking or something else.

**Comment by aeschli** [comment]
Thanks, closing then. If you see this again, it would be great if you could find out which extension caused the issue and file an issue against that extension.
