### ISSUE TITLE
Emmet in JSX is no longer expands "img", "input", etc. as self-closing tags

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#32698]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-92-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
sass-lint|gle|0.0.4
sass-indented|rob|1.4.1
vscode-multiclip|sle|0.1.2

(22 theme extensions excluded)

---

For example, the result of expanding img ins JSX is now
`<img src="" alt="">`
but before 1.15 it was
`<img src="" alt="" />`

**Comment by ramya-rao-a** [comment]
@antony-chopin Add the below setting, and you will get the self closing tags for jsx

```json
"emmet.syntaxProfiles": {
     "jsx": {
            "self_closing_tags": true
             }
}
```

And I will look into adding it as a default

**Comment by ramya-rao-a** [comment]
Learn more on what else you can customize using syntaxProfiles at https://docs.emmet.io/customization/syntax-profiles/

**Comment by ramya-rao-a** [comment]
@sergeche Was it intentional to have self closing tags for jsx in old emmet?
If yes, then in Emmet 2.0 would you expect the editor to pass the selfClosingTag option to the profile, or should it be enabled by default by the emmet modules when the `jsx` add-on is passed on?

**Comment by ramya-rao-a** [comment]
Closing this issue for now as there is a workaround for this. See https://github.com/Microsoft/vscode/issues/32698#issuecomment-323107334.

If and when we get more feedback that self closing tags are generally expected in jsx, we will hold off on making that as default

**Comment by hefei00** [comment]
@ramya-rao-a  if I write jsx syntax in .js file. how to set the emmet setting to get self closing tags. I tried the setting you had mentioned. but it didn't work. I add these config to the setting, it didn't work too. 
```
"emmet.syntaxProfiles": {
    "jsx": {
      "self_closing_tags": true
    },
    "javascript": {
      "self_closing_tags": true
    },
    "js": {
      "self_closing_tags": true
    },
    "javascriptreact": {
      "self_closing_tags": true
    }
  },
```

**Comment by sergeche** [comment]
@ramya-rao-a editor should pass predefined profile options (like self-closing tag for JSX) by default depending on editor’s syntax

**Comment by hefei00** [comment]
finally, after I add these line to setting.json, I get self closing tags.
```
"emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
"emmet.syntaxProfiles": {
    "jsx": {
      "self_closing_tag": true
    }
  },
```

**Comment by ramya-rao-a** [comment]
@hefei00 Since you were using emmet in a js file which is not supported by default you had to use `emmet.includeLanguages` setting to map it. Read https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration for more on Emmet settings

**Comment by ramya-rao-a** [comment]
Re-opening to pass self closing tag as default options for jsx

**Comment by ramya-rao-a** [comment]
Note to verifier:
1. Remove any customizations in `emmet.syntaxProfiles` for `jsx`, `xml`, `xsl`
2. Test abbreviations like `img`, `br`. They should get self closing tags in javascriptreact, xml and xml files, but not in html files
3. Add some customization in `emmet.syntaxProfiles` for `xml` like
```
"emmet: syntaxProfiles": {
    "xml": {
         "tag_case": "upper"
     }
}
```
4. You should still get self closing tags in xml
