### ISSUE TITLE
tab键不可以自动补全Html标签

### ISSUE THREAD

**Issue by freezerup** [Microsoft/vscode#32694]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.1.8
vetur|oct|0.9.3

---

Steps to Reproduce:

1.已经安装Vetur支持vue且设置emmet.triggerExpansionOnTab：true,但在vue文件中，tab不能补全标签
2.

Reproduces without extensions: Yes/No

**Comment by Ben07** [comment]
设置下`"emmet.triggerExpansionOnTab": true`就可以了。别的issue有提到

**Comment by CnSimonChan** [comment]
[**READ THE DOCS**](https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types)

**Comment by zdpeitang** [comment]
貌似需要设置：
```
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    }
```

**Comment by ramya-rao-a** [comment]
As mentioned in https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types, try the below

```
    "emmet.inlcudeLanguages": {
        "vue-html": "html",
        "vue": "html"
    }
```
