### ISSUE TITLE
Inserting electric char doesn't replace selected text

### ISSUE THREAD

**Issue by tomq42** [Microsoft/vscode#327]
Try this.
On a new, otherwise empty js or ts file, put in a simple one line program. Any text will do.

Select All.

Then type a single quote (or double quote or bracket etc, anything electric)

Rather than replacing the whole selection with the single quote as you might expect, it surrounds the selected text with a quote.

This is inconsistent with the behaviour if you do a select all and then type a normal character, where it just replaces the selection.

It doesn't feel like this is deliberate behaviour, but it might conceivably be. It's confusing if it is!

**Comment by tomq42** [comment]
Note that in "normal" visual studio, it does what I expect, that is that if you have highlighted text, then typing a quote char replaces the text. If there is nothing selected though it does it's magic thing and inserts two single quotes with the cursor between them.

**Comment by boki** [comment]
This behavior is used in quite a lot of editors these days, along wrapping selected text in parenthesis, brackets, and braces. The setting `editor.autoClosingBrackets` seems to control the quotes as well as the brackets in its name.

**Comment by tomq42** [comment]
It's not behaviour I've come across (I'd be interested in the editors in which it is present, it's in none of the ones I use regularly).
If it is deliberate, then it's confusing, as the behaviour is inconsistent. Without knowing what the electric characters are for the mode, I don't know how it's going to react when I select some text and type a character. If I type 'a' it replaces the selection. If I type (maybe, who knows, it's pot luck) '(', then it doesn't replace the selection.

Confusing.
Even more confusing is that if I make a selection and press (, then the text is surrounded by parent. Make a selection and press ), and it's replaced. So the behaviour on ( is different to the behaviour on ). To me, that's wrong.

**Comment by alexandrudima** [comment]
@joaomoreno 
I am also not a big fan of our current behaviour. Maybe we should change the default of `editor.autoClosingBrackets` to off by default?

**Comment by joaomoreno** [comment]
Against it.

Pop up Atom, Sublime Text, Textmate and see what happens there. I'd say it's pretty standard. Additionally, the confusion is always an undo away.

**Comment by tomq42** [comment]
Pop up Visual Studio(!), Eclipse, Notepad++. No such behaviour there.
This is NOT standard.

**Comment by tomq42** [comment]
What's actually even more curious is that if I make a selection and then press delete to delete the text, and THEN press quote, I only get ONE quote, not two! So the behaviour is inconsistent there too.

**Comment by alexandrudima** [comment]
I think there is the workaround today we can all use to turn it off. (set `editor.autoClosingBrackets` to `false`)

When it's on, it does have some rough edges, but we need to find them and improve such that the experience is pleasing. Can we nail down a list of concrete rough edges?

ccing @weinand @isidorn who also hit some rough edges for examples/input.

**Comment by joaomoreno** [comment]
I'd rather we close this all encompassing one and just file specific issues for each rough edge.

**Comment by MiguelQueiroz** [comment]
This worked before.. now that i updated, it does not works.. why this changed.. 
is this the editor.autoClosingBrackets option?

**Comment by newbiedoodle** [comment]
How can I reenable this behavior? I quite like being able to wrap things in brackets, parens, etc.

**Comment by joaomoreno** [comment]
@newbiedoodle Wrapping works for me. What file type are you on?

**Comment by newbiedoodle** [comment]
Oh, I missed the part about it only happening for certain file extensions. I'm in a .cpp; I didn't realize it only happened for .js or .ts.

**Comment by calebmosher** [comment]
I am experiencing this behavior even with `editor.autoClosingBrackets` set to false. Not sure if something changed or what, but it's extremely frustrating. Would it be possible to re-open this issue?
