### ISSUE TITLE
Current Git branch status bar label doesn't change 

### ISSUE THREAD

**Issue by NicoAiko** [Microsoft/vscode#32705]
- VSCode Version: Code - Insiders 1.16.0-insider (728b2f9ad74bbec1dcde55dc42e5ea028661447d, 2017-08-16T18:29:27.814Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
html-css-class-completion|Zig|1.8.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
vscode-npm-script|eg2|0.2.0
vscode-apache|mrm|1.1.1
typescript-javascript-grammar|ms-|0.0.23
vetur|oct|0.9.3
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
vscode-sql-beautify|sen|0.0.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a workspace with two or more folders, each with an own git repository. Only one of the folders loaded will be usable for the status bar.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#31325
