### ISSUE TITLE
Weird Syntax highlighting

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#32700]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-twig-pack|baj|1.0.0
path-intellisense|chr|1.4.2
xml|Dot|1.9.2
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
gc-excelviewer|Gra|1.1.15
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
composer|ika|0.5.0
Angular2|joh|2.4.0
PowerShell|ms-|1.4.1
php-docblocker|nei|1.2.0
vscode-docker|Pet|0.0.16
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0
vscode-autohotkey|sle|0.2.1

---

Steps to Reproduce:

1. Open a new php file
2. Copy & paste the following:
```
<ol class="
<?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>no-display-current <?php endif ?>
<?php
if($this->getSingleChoice()) {echo " single-choice ";}?>
<?php
if ($this->getSortFeaturedFirst() && in_array($doesnt, $matter)) {} ?>
">
```
3. It should look like this: 
![image](https://user-images.githubusercontent.com/7961978/29401773-d0da8c7e-8332-11e7-9213-946b3ef614c4.png)

Reproduces without extensions: Yes

---

I know that this code is crap by itself, but it's valid anyway.
And I didn't write it, so I don't care much, but I was just confused by the syntax highlighting my VSCode does.
It is able to highlight the php if the code is right next to the <?php but if it's at a new line then it's failing.

Maybe this is intended somehow, maybe not, I'm confused, that's why I reported it. 😁

**Comment by webluke** [comment]
I have experienced this with other file formats also, .mustache and HTML
![image](https://user-images.githubusercontent.com/5162188/29419523-93743d86-832c-11e7-977c-b5b4bf1687f5.png)
![image](https://user-images.githubusercontent.com/5162188/29419663-e802e028-832c-11e7-90cc-0da699b8a483.png)

**Comment by roblourens** [comment]
PHP issue filed upstream: https://github.com/atom/language-php/issues/259

@webluke I don't follow, that doesn't look related. Are you asking about the red `&` character? It's probably calling it out so you can escape it.

**Comment by webluke** [comment]
The highlighting is related, yet I see your are talking about the next line not being treated as part of the quoted class element. But that ampersand shouldn't be highlighted but rather underlined with an intellisense error.

**Comment by roblourens** [comment]
We don't have a language service that shows errors like that for html. You can file an issue at https://github.com/textmate/html.tmbundle if you want to discuss it but I think this is by design.

**Comment by roblourens** [comment]
Fixed upstream
