### ISSUE TITLE
Taskbar icon in 64bits version

### ISSUE THREAD

**Issue by pypardo** [Microsoft/vscode#32708]
Hi All,

- VSCode Version: Code 1.15.1  41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z  - OS Version: Windows_NT x64 6.1.7601 - 

Extensions:  

Extension|Author  truncated |Version 
-|-|- 
pascal|ale|0.8.2 
vscode-multimarkdown|and|0.1.1 
npm-intellisense|chr|1.3.0 
python|don|0.7.0 
gitlens|eam|4.3.3 
vscode-npm-script|eg2|0.2.0 
vscode-npm|fkn|3.3.0 
beautify|Hoo|1.1.1
latex-workshop|Jam|3.3.2 
easy-icons|jam|0.3.1 
ctags-support|jay|1.0.18 
markdown-shortcuts|mdi|0.8.1 
vscode-todo-parser|min|1.9.1 
cpptools|ms-|0.12.2 csharp|ms-|1.12.1 
vscode-code-outline|pat|0.0.8 
vscode-icons|rob|7.12.0 
trailing-spaces|sha|0.2.11 
omnipascal|Wos|0.14.1

**Just installed 64 bits version, Application icon is not the right one. My win7 just display an ugly default icon in task bar.**
With 32 bits version, the icon is fine.

**Comment by bpasero** [comment]
@pypardo can you share a screenshot?

**Comment by pypardo** [comment]
![image](https://user-images.githubusercontent.com/17902957/29408940-715ef2fe-834a-11e7-9890-78e97df504c3.png)

Here's a simple screenshot

**Comment by pypardo** [comment]
@bpasero 
After a reboot, everything works fine, the regular VSCode icon now appears in Task bar.
Sorry to disturbing community with this 'small' problem.
First time I saw this problem on Windows.
