### ISSUE TITLE
updated VS Code just now, it can't debug successfully.

### ISSUE THREAD

**Issue by SHocker-Yu** [Microsoft/vscode#32707]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
code-runner|for|0.6.33
cpptools|ms-|0.12.2
sublime-keybindings|ms-|2.9.1
debug|web|0.21.2

---

Steps to Reproduce:

1.node -v        v5.12.0
2.launch.json
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "manager",
            "port": 33330
        }]
}
```
3、Debugging with legacy protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:33330)

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What version of node are you using?
How are you launching your node app?

**Comment by SHocker-Yu** [comment]
@weinand  
1、node version:  v5.12.0
2、node app.js  to start
3、launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "manager",
            "port": 33330
        }]
}

**Comment by weinand** [comment]
If you start node manually from the command line, you must pass a debug flag, e.g.:
```
node --debug-brk=33330 app.js
```
After that you can use the "attach" configuration from above.

A simpler way to debug your app is by using a "launch" config:
```js
{
            "type": "node",
            "name": "manager",
            "request": "launch",
            "program": "app.js"
}
```
This starts "app.js" in debug mode and attaches the debugger in one go.

You can have both launch configs in one "launch.json" file:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"name": "attach manager",
			"request": "launch",
			"program": "app.js"
		},
		{
			"type": "node",
			"name": "launch manager",
			"request": "attach",
			"port": 33330
		}
	]
}
```
