### ISSUE TITLE
Color picker: jumps up and down with zoom level 1

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#32709]
Steps to Reproduce:

1. zoom in one level
2. change the color in the color picker slider

=> the picker jumps up and down

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29408279-ddc25678-8347-11e7-85bb-ba4f408f33d5.gif)

**Comment by rebornix** [comment]
It has been a long time since this issue was created. @bpasero can you still reproduce?

**Comment by bpasero** [comment]
No I think not.
