### ISSUE TITLE
emmet.extensionsPath doesnt work

### ISSUE THREAD

**Issue by anyclub** [Microsoft/vscode#32702]
- VSCode Version:1.15.1
- OS Version:win10.0.15063

Steps to Reproduce:

1. set "emmet.extensionsPath": "C:\\"
2. write snippets.json is 
`{
    "variables": {
        "lang": "zh-CN",
        "locale": "zh-CN"
    },
    "html": {
        "abbreviation": {
            "link:tpl|link:template": "<link rel=\"template\" href=\"${1:component.html}\" />"
        }
    }
}`
3. in a html file,   "variables" can work properly;
other settings, dont work.
into `link:tpl` -> tab `<link:tpl></link:tpl>`

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
We introduced Emmet 2.0 in VS Code 1.15

Please read the [Release Notes on Emmet 2.0](https://code.visualstudio.com/updates/v1_15#_emmet-20) or the [Emmet 2.0 blog post](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) to see what are the changes.

For you custom snippets, read the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets)

You will need to update your custom snippets for them to work in VS Code 1.15 onwards

**Comment by oktav777** [comment]
@ramya-rao-a the issue still persist.

I have the `<project-path>/.vscode` folder, where are the `settings.json` and `snippets.json` files.

When I try to add snippets file to the settings, I get the error:
```
The directory <project-path>\.vscode\snippets.json doesnt exist.
Update emmet.extensionsPath setting
```

`settings.json`
```json
{
    "emmet.extensionsPath": "./.vscode/snippets.json",
}
```

`snippets.json`
```json
{
    "css": {
        "snippets": {
            ...
        }
    }
}
```
I also tried to alter path separator with `\\` instead of `/` but I get the same error with updated paths.
Visual Studio Code version: 1.17.2
Windows 10 x64

**Comment by ramya-rao-a** [comment]
@oktav777 The `emmet.extensionsPath` should point to the folder that contains the `snippets.json` file not the path to the `snippets.json` file itself.
