### ISSUE TITLE
Ctrl + Shift + B can't find default typescript build task

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#32704]
Version 1.16.0-insider
Commit 9e7441df9f609500a13e8651bd01eccf1613f386
Date 2017-08-17T05:23:58.225Z
Shell 1.7.4
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Have this `.vscode/tasks.json` file

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "isBackground": true,
      "tsconfig": "tsconfig.json",
      "problemMatcher": "$tsc-watch",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

2. Press Ctrl + Shift + B

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/461084/29405848-8c83d1e2-8315-11e7-88db-2afa2c0843de.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/31977
