### ISSUE TITLE
Autocomplete unbearably slow when using `jsconfig.json` at root level

### ISSUE THREAD

**Issue by nealoke** [Microsoft/vscode#32715]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

**Problem**
Autocomplete is very slow in providing autocomplete suggestions (**+3 minutes!**). After trying to debug this problem I've found that the issue is only present when a `jsconfig.json` file is present. I guess it might be that the `jsconfig.json` is not picking up the `exclude` array as it should and therefor is scanning all the `node_modules` (around 700 MB). This problem also reproduces without extensions, after a full uninstall (including those extensions) and on a previous release (`x32 1.14.2`).

**Project structure**
```
| Workspace folder
|-> node_modules
|-> .jsconfig.json
|-> .gitignore

|-> app
  |-> node_modules
  |-> ... other files

|-> dashboard
  |-> node_modules
  |-> ... other files

|-> wizer-components
  |-> node_modules
  |-> ... other files
```

**The `jsconfig.json` at root level**
```
{
  "compilerOptions": {
    "target": "ES6"
  },
  "exclude": ["node_modules", "**/node_modules"]
}
```

**Comment by nealoke** [comment]
I tried installing the previous version I used - x32 `1.14.2` but it has the same result so it might be a plugin? How can I debug this? I frustrates me quite a lot that I don't get notified when something is updated of the plugins section :(.

**Example of what happens when reloading window**
![how it goes](https://user-images.githubusercontent.com/17417414/29416174-9b66773c-8365-11e7-9ab4-8e0abeae9336.gif)

1. Window reloads
2. Autocomplete works
3. ... magic ... (plugins load?)
4. Autocomplete stuck on `Loading...`

**Comment by nealoke** [comment]
I just noticed that this is not the case for `.scss` files, intellisense works fine there

**Comment by nealoke** [comment]
I've just double checked that it is not an extension that is causing this problem by turning them all off and reloading the window. I'll do a full uninstall tomorrow to see if that solves the issue.

**Comment by nealoke** [comment]
A full uninstall (so vscode and plugins), reboot and install of the latest version `1.15.1` does **not** solve my issue. There are no error logs in the console anymore 😞 and autocomplete still hangs on "loading".

**Comment by mjbvz** [comment]
Does this also reproduce in the [latest insiders builds](https://code.visualstudio.com/insiders)?

If you are still seeing the issue, can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the error
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look the 'completions' request at the end of the file. There should also be printed lists of all files that TS thinks are part of your project. Look through these to see if anything odd stands out.

If you can share the logs I can also take a look

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
