### ISSUE TITLE
Opening VS Code by double-clicking file in File Explorer forgets previously opened files

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#32711]
If you have a mixture of saved and non-saved files open in VS Code...

- Quitting and restarting VS Code restores all the files that were previously open. Saved and non-saved. As expected.

- However, if you quit VS Code and then double-click on a text file in File Explorer, when VS Code starts it only opens the non-saved files (i.e. the "hot-saved" files) that were open previously, in addition the the new file that you double-clicked on to launch VS Code. All of the saved files that were previously open are forgotten about, and they are not restored.

I usually have a variety of text files open in VS Code and I would like the session to be restored whenever I restart VS Code, whether that is by explicitly launching VS Code from its shortcut, or by launching VS Code by double-clicking a file that it is registered for. The former works as I expect, but unfortunately the latter does not.

**Comment by bpasero** [comment]
@Eldaw is that session as window without opened folder or with a folder opened?

**Comment by Eldaw** [comment]
@bpasero Without a folder opened.

**Comment by bpasero** [comment]
This may come to a surprise for people that are used to the current behaviour so it might need another setting for this...

**Comment by alexandrul** [comment]
Would it be possible to add a "SublimeText emulation" mode? (just like multiple product are having a "vim emulation" mode)

ST has no issues with opening multiple folders and has never ever lost an open file, regardless of its state.
Just use it for a while and implement the same behavior, please.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14675
