### ISSUE TITLE
Feature request: setting the default state of the "Toggle Word Wrap" option

### ISSUE THREAD

**Issue by stefangabos** [Microsoft/vscode#32712]
I use `"editor.wordWrap": "wordWrapColumn"` and `"editor.wordWrapColumn": 120` and that is perfect but I would love for files to not open with word-wrap applied. That's what the "Toggle Word Wrap" option is for. I only occasionally need to actually wrap the source code for better reading long-lines but, more often than not, I don't use the wrapping. Can an option like `"editor.toggleWordWrap": true/fase` be added?

**Comment by evanwarner** [comment]
@stefangabos Would my proposed settings in #38303 solve your issue?

**Comment by stefangabos** [comment]
yes, that's better explained than here. 
discussion moved to #38303
