### ISSUE TITLE
Unclear error message when discarding changes

### ISSUE THREAD

**Issue by XANi** [Microsoft/vscode#32714]
The angry hippo in #32405 does bring up a valid issue.

![img](https://user-images.githubusercontent.com/240625/29264526-c8a1b354-80dd-11e7-82d7-76e7b0066998.png)

Normally, with say Git, "revert all changes" means:

* Revert all **tracked** files to their VCS version
* Leave all **untracked** files alone

I do believe that SVN works in similiar way, altho I haven't used it for a while so I might be wrong.

"Discard all changes" should either clarify that (probably with big sign **THIS WILL DELETE EVERY FILE THAT IS NOT IN VCS** and smaller one "and ones commited will be reverted to upstream), or do not touch untracked files at all

**Comment by joaomoreno** [comment]
#32459
