### ISSUE TITLE
Show 'Do you want to save' centered on the application window, not centered on the monitor

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#32713]
Currently, if you try to close an unsaved file, the dialog 'Do you want to save the changes you made' appears centered on the monitor. It would be preferable to have this dialog appear centered on the Visual Studio application window.

**Comment by bpasero** [comment]
@Eldaw which OS?

**Comment by Eldaw** [comment]
Windows 10 x64.

**Comment by bpasero** [comment]
Looks like native behaviour to me, Notepad is the same:

![image](https://user-images.githubusercontent.com/900690/29412928-f662a062-835a-11e7-9f03-267d73daef8b.png)
