### ISSUE TITLE
Duplicate setting "npm.runSilent" in vscode://defaultsettings/settings.json

### ISSUE THREAD

**Issue by mrichman** [Microsoft/vscode#32716]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
xml|Dot|1.9.2
EditorConfig|Edi|0.9.4
material-icon-theme|PKi|2.1.0
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.2
html-css-class-completion|Zig|1.8.0
hugofy|akm|0.1.0
vscode-color|ans|0.4.5
cform|aws|0.0.10
better-toml|bun|0.2.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
typewriter|dan|1.0.1
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
gitlens|eam|4.3.3
vscode-npm-script|eg2|0.2.0
lambda-snippets|log|0.2.0
Go|luk|0.6.63
prettify-json|moh|0.0.3
debugger-for-chrome|msj|3.1.8
vscode-icons|rob|7.12.0
gitblame|wad|2.1.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Line 1975 and 2061 are duplicates.
2. Does NOT repro with extensions disabled.

Reproduces without extensions: No

**Comment by aeschli** [comment]
Looks like two extension contribute the same setting. Can you find out which extensions? Open the extensions viewlet, select each extension and examine the 'Contributions' tab.
We have to ask the extensions to use the extension name as prefix.

**Comment by mrichman** [comment]
I was only able to see the conflict when searching the Default Settings for "npm", which shows two sections: "npm Script Runner" and "Npm". The latter is obviously https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script but I'm not sure what "npm Script Runner" corresponds to.

**Comment by breathe** [comment]
I'm seeing the same error -- it appears to be this module https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script conflicting with npm script runner module

<img width="754" alt="screen shot 2017-08-17 at 10 51 17 pm" src="https://user-images.githubusercontent.com/434034/29442293-9d1feb74-839e-11e7-87fb-5c96594e4376.png">

**Comment by aeschli** [comment]
Oh, looks like npm is now part of vscode.

**Comment by egamma** [comment]
Corrct, both the `npm` extension that is now bundled with vscode and the `npm-script-runner` extension define a setting for `npm.runSilent`.

Need to investigate into whether it is better to rename one of the settings or to share the setting definition.

**Comment by egamma** [comment]
Changed in the npm_script runner extension, it no longer contribute its own npm.runSilent setting.
