### ISSUE TITLE
Auto Update of Folder Content Needed

### ISSUE THREAD

**Issue by Syed-Umair** [Microsoft/vscode#32729]
Please add auto reload of folder if the folder is updated in the disk.

Now the folder changes are not affected in the current instance.

**Comment by bpasero** [comment]
We have a file watcher in VS Code, but file watching is not easy and can fail from time to time depending on the setup.

**Comment by Tyriar** [comment]
@Syed-Umair what operating system are you using and what version of VS Code (Help > About, on mac VS Code > About...)?
