### ISSUE TITLE
Old/new snippets being summoned by Intellisense right after a change

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#32724]
- VSCode Version: 1.15.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Change an existing snippet (PowerShell in this case).
2. Open a script, type the snippet prefix.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/4306938/29419115-e338a8d2-8333-11e7-8f50-485112136a45.png)

**Comment by jrieken** [comment]
You are saying both are user snippets and on disk there is actually only one snippet? Does this persist?

**Comment by adbertram** [comment]
There is only one snippet for that prefix on disk but the old version and
the new version show up via Intellisense. I can restart VS Code and it's
back to only showing a single instance as it should.

**Comment by jrieken** [comment]
Hm, still cannot reproduce... For me the snippet isn't duplicated... What in the snippet are you changing, the `body` I assume?

**Comment by adbertram** [comment]
Yes. I'm just making a minor change. I'm not sure how it got in this
particular state.

**Comment by jrieken** [comment]
@adbertram Are you still seeing this? Can you try this with current insider: https://code.visualstudio.com/insiders?

**Comment by adbertram** [comment]
I don't see this behavior with the latest insiders build. Thanks!

**Comment by jrieken** [comment]
Ok, closing then. Thanks for getting back to me
