### ISSUE TITLE
Upgrading to VSC 1.15 64-bit Made It Unresponsive

### ISSUE THREAD

**Issue by johancyprich** [Microsoft/vscode#32728]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro :: 10.0.15063 Build 15063

I upgrade VSC to the latest 64-bit version and from there the app became unresponsive. Task Manager showed that VSC was using 98%+ CPU and the memory usage for the multiple instances was very large (100s of MB and typically 1 GB as well).

I tried installing earlier versions and also went back to 32-bit, but the same problem occurred. So, I did a complete uninstall and deleted the %USERS%/.vscode folder, and then did a reinstall of the 1.15 64-bit. While running Task Manager, I installed one extension at a time. When I tried to open a .cs file, VSC installed C# extensions and then the CPU/memory usage went to extreme levels which caused VSC to lag. When I disabled the C# extension, CPU/memory usage went to an acceptable level.

So I uninstall the C# extension and I'm happily using VSC. I think that the OmniSharp extension was causing the problems.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1723
