### ISSUE TITLE
C# auto attach to process

### ISSUE THREAD

**Issue by s130059660** [Microsoft/vscode#32726]
- VSCode Version: 1.15
- OS Version: Windows 10

![vscode_01_with_notes](https://user-images.githubusercontent.com/22569741/29419853-f17d7914-8378-11e7-824f-6f948313edff.jpg)

I've Just noticed that when I try to attach to a DotNet Core process using `command:pickProcess`, VSCode does a good job by enumerating all system's processes with their details.

As you can see from the picture above, VSCode seems to have the possibility of auto selecting the correct process automatically without the user jumping and scrolling through all the processes available from  `command:pickProcess`

I have a small suggestion. Allow VSCode attach (in Launch.json) to have two new settings:

`
"processId":"${command:autoPickProcessWithPattern:${workspaceRoot}/bin/Debug/netcoreapp2.0/TopTen-Server.dll}",
`

VSCode will then lookup the string, and when it find a match, It will retrieve the pid and attach to it automatically.

That will also open another possibility for a feature that I greatly miss from Node.Js; auto re-attach on change when using "Watcher".
`
"restart" : "true"
`

**Comment by weinand** [comment]
The re-attach feature and the filtered process picker is something that needs to be implemented by the C#/dot net extension and you should create a new issue there.

However, as a prereq for this feature VS Code needs to support passing arguments to command-based variables. I've created a [separate issue](https://github.com/Microsoft/vscode/issues/38327) for this.
