### ISSUE TITLE
Terminal should force selection on Windows/Linux with shift key

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#32725]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/869

Please verify this on Linux by opening tmux in mouse mode and ensuring regular mouse selection triggers "tmux selection" and shift+mouse selection triggers the regular terminal selection.

**Comment by roblourens** [comment]
I thought I verified this last month?

**Comment by Tyriar** [comment]
@roblourens this was Mac only last month, needs verification on Linux.
