### ISSUE TITLE
Creating new folder and then scrolling up messes directory tree

### ISSUE THREAD

**Issue by karaxuna** [Microsoft/vscode#3272]
Version 0.10.8

Steps to reproduce:

1. You shall have many folders so that scroll appears;
2. Click parent folder with right mouse button -> New Folder;
3. Don't do anything, just scroll up with mouse wheel;

Directory tree starts to behave strangely when scrolling up, items mess up.

**Comment by joaomoreno** [comment]
Can you maybe provide a video recording of what you are seeing?

[LICEcap](http://www.cockos.com/licecap/) is a useful tool for this.

**Comment by karaxuna** [comment]
Here

![bug](https://cloud.githubusercontent.com/assets/2152815/13259057/319d352a-da6f-11e5-83fa-be0e94b9dec1.gif)

**Comment by joaomoreno** [comment]
Very COOL. Thanks for the recording!
