### ISSUE TITLE
Emmet suggestions show in HTML file <script> tags

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#32732]
- VSCode Version: Code - Insiders 1.16.0-insider (9e7441df9f609500a13e8651bd01eccf1613f386, 2017-08-17T05:23:58.225Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.3.2
seti-icons|qin|0.1.3
vscode-import-cost|wix|2.3.0

(1 theme extensions excluded)

---

Repro:

1. Create a .html file with content:

```
<script>
document.addEventListener("drop", function( event ) {
	console.log("Drop");
	console.log(event);
	event.preventDefault();
	// If dropped items aren't files, reject them
	var dt = event.dataTransfer;
	console.log(dt.files.length);
	if (dt.items) {
		// Use DataTransferItemList interface to access the file(s)
		for (var i=0; i < dt.items.length; i++) {
			if (dt.items[i].kind == "file") {
				var f = dt.items[i].getAsFile();
				console.log(f);
			console.log("... file[" + i + "].name = " + f.name);
		}
		}
	} else {
		// Use DataTransfer interface to access the file(s)
		for (var i=0; i < dt.files.length; i++) {
		console.log("... file[" + i + "].name = " + dt.files[i].name);
		}
	}

}, false);
</script>
```

![image](https://user-images.githubusercontent.com/2193314/29424706-9cc946c0-8335-11e7-9aff-018e7a2c79e3.png)

**Comment by ramya-rao-a** [comment]
Current workaround for non emmet users is to set `emmet.showExpandedAbbreviation` to `never`

**Comment by ramya-rao-a** [comment]
The fix will be out in tomorrow's Insiders
