### ISSUE TITLE
Support renameLocation for TS/JS refactorings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32735]
From https://github.com/Microsoft/TypeScript/issues/17852

Expected refactor flow should trigger rename after applying the refactoring

**Comment by roblourens** [comment]
I still get `newFunction`, that doesn't seem right?

**Comment by mjbvz** [comment]
@roblourens Sorry, TS doesn't actually return the rename location yet so it is expected that this would not actually work. I should have marked this issue as a work item since it just was tracking our support for the rename location value once TS returns it.

I'm planning to create a new feature request next month to track fully supporting the rename flow
