### ISSUE TITLE
VSCode does not recognize tilde (~) for absolute file paths

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#32736]
- VSCode Version: All
- OS Version: OSX

Steps to Reproduce:

1. Press command-p to open a file
2. Paste in an absolute link to a file starting with tilde, as in ~/Desktop/some-file-that-exists.bmp

Expected result:

File path is found and openable

Actual result:

No file is found

Workaround:

Paste in the full expanded path, as in /Users/yourname/...

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
That would be nice 👍

**Comment by roblourens** [comment]
> Paste in the full expanded path, as in /Users/yourname/...

This doesn't work for me. Currently quickopen is only looking at the relative paths of files inside the open workspace. Do you expect to be able to open files outside the workspace with an absolute path? I think that makes sense.

**Comment by shivammittal99** [comment]
Is anybody still working on this. If not, I would like to work on this, with some help.
Thank you.
