### ISSUE TITLE
Spawning `git` crashes extension host

### ISSUE THREAD

**Issue by aman-manocha** [Microsoft/vscode#32739]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Run visual studio code on Windows 10
2. Click on "reload" button results in same error again
3. Rebooting/re-install doesn't help

**Comment by alexandrudima** [comment]
@aman-manocha 

Are you using the 64-bit version of VS Code or the 32-bit version ?

When the error is shown, can you please open the Developer Tools (Help > Toggle Developer Tools) and check if there is any additional information in there?

**Comment by aman-manocha** [comment]
I am using 64-bit version of VS Code.
I didn't try 32-bit version.
I didn't install any extensions.
No additional information in  Dev Tools

**Comment by Edmanbosch** [comment]
I also seem to keep getting this issue, it's weird since it used to never happen.

**Comment by alexandrudima** [comment]
@aman-manocha Can you consistently reproduce this? Even when opening a new empty window (i.e. File > New Window) ? or is it something reproducing only for a certain folder ?

**Comment by Edmanbosch** [comment]
Apparently, the reason why I got this error was because I didn't have git installed on my computer. If git is something required for VS Code, then it should be made a bit more obvious.

**Comment by joaomoreno** [comment]
This is very strange. @Edmanbosch let me ask you a favour: if you uninstall Git, does the issue start happening again?

**Comment by Edmanbosch** [comment]
So, I just uninstalled git, got the issue again. I installed git again and the issue was gone.

**Comment by joaomoreno** [comment]
Awesome! What's your exact OS?

**Comment by Edmanbosch** [comment]
Well, I'm using Windows 10.

**Comment by joaomoreno** [comment]
With _exact_, I meant the exact version number.

https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/

**Comment by Z-starts** [comment]
@joaomoreno 
![image](https://user-images.githubusercontent.com/1948235/31119914-3b00fbf4-a865-11e7-8801-745de9c3c1ab.png)

**Comment by Edmanbosch** [comment]
@joaomoreno Ah, sorry. The version number is 1703, with the build number being 15063.608.

**Comment by joaomoreno** [comment]
@Edmanbosch  @Z-starts @aman-manocha 

I got something else to try. Uninstall git, make sure you still get the issue. Then, edit `app/extensions/git/out/git.js` and comment out the following line. It should be around line 82.

```ts
        .then(void 0, () => findSpecificGit('git'));
```

Does the issue still reproduce with that commented out?

**Comment by joaomoreno** [comment]
@alexandrudima I could confirm what you saw in Procmon. Consider the following code:

```ts

function findGitWin32(): Promise<IGit> {
	return findSystemGitWin32(process.env['ProgramW6432'])
		.then(void 0, () => findSystemGitWin32(process.env['ProgramFiles(x86)']))
		.then(void 0, () => findSystemGitWin32(process.env['ProgramFiles']))
		.then(void 0, () => findSpecificGit('git'));
}
```

When `git` is not installed, that code will trickle down to `findSpecificGit('git')` which will simply do `cp.spawn('git'...`). In my machine, I can see that Node loops through all the paths in `%PATH%` and appends `git.com` and `git.exe` to them and tries to spawn that.

It could be that in these user's machines this will spawn something other than git but called the same way, causing the crash.

I want to wait for a reply from @Edmanbosch @Z-starts @aman-manocha but my gut feeling tells me to simply delete that last fallback case. If users install git on a different path other than the default ones, we have the `git.path` setting for that. What do you think?

**Comment by Edmanbosch** [comment]
Just tried it out, and VS Code loads and gives me zero problems.

**Comment by joaomoreno** [comment]
That's awesome. How about [this build](https://az764295.vo.msecnd.net/insider/14bec536cd355008680893caa2c3f01c8a5c5ebf/VSCode-win32-x64-1.18.0-insider.zip)? Still no problem?

**Comment by alexandrudima** [comment]
@joaomoreno Perhaps you could spawn `where git` and then check if there is a `cmd\git.exe` in the path ?

**Comment by joaomoreno** [comment]
@alexandrudima I'd actually be comfortable removing that _find git wherever_ code altogether. That build I linked to in the previous commit does that. 👍

**Comment by Edmanbosch** [comment]
@joaomoreno It works perfectly fine, even without having git installed.

**Comment by joaomoreno** [comment]
@aman-manocha Wanna give it a try?

**Comment by euk-anthonyb** [comment]
Same extension error occurs in the Insiders version. :(

![image](https://user-images.githubusercontent.com/14346320/32894865-0a39e998-cad6-11e7-87ad-c118e5480c38.png)

![image](https://user-images.githubusercontent.com/14346320/32894876-13a6df22-cad6-11e7-931b-6431a3e68b2b.png)

**Comment by Tyriar** [comment]
Git installed for specific user is no longer picked up because of this change, see https://github.com/Microsoft/vscode/issues/40229
