### ISSUE TITLE
macOS: Git commit with ⌘S saves foreground document before commit

### ISSUE THREAD

**Issue by zneak** [Microsoft/vscode#32740]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. Open project versioned with Git
2. Modify and save some file, and stage it for commit
3. Modify (but do not save) some file, and keep its editor in the foreground
3. In the source control pane, enter a commit message and commit using ⌘S

The file that has been modified but not saved is saved when ⌘S is pressed, *and* the staged changes are committed. This is the most visible when the foreground file is an untitled document that hasn't been saved anywhere yet because it brings up the save dialog.

The expected behavior would be that ⌘S commits the staged changes but does not attempt to save the foreground editor.

Reproduces without extensions: Haven't tested, but given my very bare setup, almost certainly.

**Comment by joaomoreno** [comment]
<kbd>⌘S</kbd> saves the current file, no matter where you are.

<kbd>Cmd Enter</kbd> submits the commit message.

**Comment by zneak** [comment]
So is it a bug that ⌘S also happens to commit the staged changes then?
