### ISSUE TITLE
装了插件导致使用触摸板滚动的时候出现卡顿

### ISSUE THREAD

**Issue by hsgogo** [Microsoft/vscode#32748]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yujiangshui** [comment]
装了插件，这应该是插件的问题吧，找到对应插件的 github 地址去反馈？

此外，最好用英语。

**Comment by aeschli** [comment]
Yes, please find out which extension causes this and file the issue against that extension.

**Comment by hsgogo** [comment]
I think it should be c/c++ plugin.

**Comment by ghostxdy** [comment]
I install C/C++ plugin .And how to fixed it ?

**Comment by hsgogo** [comment]
我发现了卡顿的一个原因。当我最小化vscode后再恢复，使用触摸板滚动时会卡顿。当我再最大化vscode，使用出模板滚动恢复正常。
