### ISSUE TITLE
open existing tab if available, with split editors (single instanced files across splits)

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#32747]
If there are split editors, then opening a file will open a copy in the split which has focus, even if that file is already open in another split. Feature request: an option such that if a file is open in any split, re-opening that file will navigate to the existing opened editor.

My use case is that I have one central file open in my first split, and many files open in a second split, and I navigate very frequently between different files while leaving my central file open. But opening a file creates a copy in whichever split has focus, so trying to click on a file obscures my central file with 50-50 chance unless I manually focus the second split beforehand.

This feature request allows me to pre-open all the files in my second split, so that opening any file will view it in the second split, leaving my central file open. An alternative solution would be a (configurable) "main" split in which all new files are opened, which would solve my use case directly without needing to pre-open files, but that opens up some UI issues since one of the splits is now special.

**Comment by bpasero** [comment]
`"workbench.editor.revealIfOpen": true`
