### ISSUE TITLE
[OSX & Win] Dragging folder to app window to open it in VSCode does not work

### ISSUE THREAD

**Issue by darkguy2008** [Microsoft/vscode#32749]
- VSCode Version: Code - Insiders 1.16.0-insider (9e7441df9f609500a13e8651bd01eccf1613f386, 2017-08-17T09:18:01.132Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vs-code-xml-format|fab|0.1.5
vscode-icon-theme|jtl|1.5.0
csharp|ms-|1.12.1
seti-icons|qin|0.1.3

---

Steps to Reproduce:

1. Drag a folder from either Finder or Explorer to VSCode Window
2. Some parts of the app highlight instead of the entire window as it used to be. Now, I can't open a folder by dragging it into the VSCode window, which is not the expected behavior.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/32537
