### ISSUE TITLE
Disabling auto-indent doesn't actually disable auto-indent

### ISSUE THREAD

**Issue by BillyONeal** [Microsoft/vscode#32746]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Disable editor.autoIndent.
![Auto Indent Disabled Image](https://user-images.githubusercontent.com/1544943/29439725-8aa51750-8374-11e7-835d-938c697db3ed.png)

2. Create a new file with this content and save it with a .cpp extension:
```
template<class _FwdIt,
	class _Ty,
	class _Fn>
	_Ty _Reduce_unchecked(_Parallel_policy_tag, _FwdIt _First, _FwdIt _Last, _Ty _Val, _Fn _Reduction)
	{	// return reduction, parallelized
	const size_t _Hw_threads = __std_parallel_algorithms_hw_threads();
	size_t _Count;
	if (_Hw_threads <= 1)
		{
		goto serial;
		}
	|| (_Count = _STD distance(_First, _Last)) < 2)
		{	// don't parallelize on uniprocessor machines or less than 2 elements
		return (_Reduce_unchecked(_First, _Last, _STD move(_Val), _Reduction));
		}
	}
```

3. Position the cursor on the line after "goto serial;" at the end. Press enter.
![Bug Demo](https://user-images.githubusercontent.com/1544943/29439748-b7accf18-8374-11e7-9d6f-3bee279c0c85.png)

4. VS code moved that closing curly brace back 1 indent instead of leaving it alone.
![Bug Reprod](https://user-images.githubusercontent.com/1544943/29439757-cd0e3ee6-8374-11e7-9a8b-314e751735d4.png)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
When setting `"editor.autoIndent": false`, after 004d0da57a05783797ca2860821d613095b346a8 (#36090) I can no longer reproduce. The fix will ship with our upcoming Monday Insiders build.

**Comment by BillyONeal** [comment]
Yaaaaaaaaay! :D

**Comment by mjbvz** [comment]
@alexandrudima I'm actually not sure I ever see auto indent working now. With `	"editor.autoIndent": true`, the original example code still should reindent when you press enter, correct?

**Comment by alexandrudima** [comment]
@mjbvz 004d0da57a05783797ca2860821d613095b346a8 does not change anything in the case where `editor.autoIndent: true`.
