### ISSUE TITLE
When save, it prompt a error "Failed to save 'contact.scss': A system error occurred (UNKNOWN: unknown error, open 'd:\nodejs\ionicApp\shop\src\pages\contact\contact"

### ISSUE THREAD

**Issue by coderkk** [Microsoft/vscode#32745]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.4.1
project-manager|ale|0.19.0
vscode-instant-markdown|dba|1.2.1
githistory|don|0.2.3
git-project-manager|fel|1.3.2
terminal|for|0.0.10
minify|Hoo|0.3.0
rest-client|hum|0.15.1
classic-asp|ili|0.0.2
format-indent|Kas|1.3.0
net-core-project-manager|ksu|0.3.6
git-indicators|lam|1.2.1
vscode-todo-parser|min|1.9.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-edge|msj|0.4.1
material-icon-theme|PKi|2.1.0
todotasks|san|0.5.0
code-spell-checker|str|1.3.6
spellchecker|swy|1.2.13
cordova-tools|vsm|1.2.9
vscode-react-native|vsm|0.4.1
---

Steps to Reproduce:

1. Build and run emulate the ionic android.
2. Edit the contact.scss file.
3. Save the file.
4. Get the error message.

Reproduces without extensions: No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
