### ISSUE TITLE
Sometime press 'space' was not work. 

### ISSUE THREAD

**Issue by manglobe** [Microsoft/vscode#32758]
- VSCode Version: Code - Insiders 1.16.0-insider (b73b7df1290d0fe66ca8b8060743711a327af622, 2017-08-14T05:16:07.578Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
javadebugger|don|0.1.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
react-native-react-redux|EQu|1.1.0
sass-lint|gle|0.0.4
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.1.8
vscode-icons|rob|7.12.0
react-beautify|tai|0.3.0
open-in-browser|tec|1.1.0
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

---

Sorry , I can't reproduce the steps .
The only things I know ,just this problem happend when I use embedded terminal , then everywhere in this vscode window, only 'space'  can't work .

This problem had happend three times . 
So I think maybe  I shoult open a issues.

**Comment by mjbvz** [comment]
Can you please try [disabling all extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension) and checking if the issue still occurs. Also, do you have any custom keybindings?

**Comment by jens1o** [comment]
Sometimes I can reproduce this. It doesn't matter whether extensions are enabled or not, Space just doesn't work then. I need to reload the window, and most of the times, it starts working again.

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this from the original issue
