### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by reggiekeene** [Microsoft/vscode#32750]
- VSCode Version:1.15.1
- OS Version: windows 10 pro

Steps to Reproduce: every time I start it

1.ver 1.15.1
2.every time I run it.  uninstalled it hard shut down  started up re-downloaded and reinstalled, same thing
O/s windows 10 pro 64

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
Possibly related #32739

@reggiekeene

Are you using the 64-bit version of VS Code or the 32-bit version ? 

Does this reproduce in both the 32-bit version and the 64-bit version of VS Code ? 

Does this reproduce when running `code --disable-extensions` ?

When the error is shown, can you please open the Developer Tools (Help > Toggle Developer Tools) and check if there is any additional information in there?

**Comment by jtsom** [comment]
Uh.. you may want to check this issue https://github.com/Microsoft/vscode/issues/32530  - I've been logging MANY extension host errors since they appeared after a recent update...

**Comment by reggiekeene** [comment]
Thanks Jon.   I  have been trying to install python 3.7 with zipline for trading.  I have worked for 10 days too many hours to tell.  I have tried 36. and 2.7 Anaconda, minconda and python by it self.  I have 3.6 and can not load blas or lapack so therefore I can not load Zipline.  I have cleaned the computer out.  all directores, regedit  sfc scan cc cleaner I have been in the computer business 41 years.  No I am not a programmer but I do so badly want to learn python for trading with zipline.  Any advise you could give me I would be so greatfulReggie Keene

On Friday, August 18, 2017, 11:01:20 AM EDT, John Tsombakos <notifications@github.com> wrote:


Uh.. you may want to check this issue #32530 - I've been logging MANY extension host errors since they appeared after a recent update...

**Comment by reggiekeene** [comment]
Visual Studio CodeVersion 1.15.1commit 41 abd21afdf742c89319ee7cb0445cc6f376959Date 2017-08-16t18:07:25.676zRendered 56.0.2924.87Nome 7.40    Architecture x64\It does not seem to matter if extensions or enabled or not.  I am an old man trying to learn python 3.7 with zipline for my stock trading. so for I have worked endless hours installing and uninstalling and cleaning out directories and rededit some many times. I have installed Anadaconda, miniconda , conda, python by it self. I can not get blas and lapack to load so therefore i can not load zipline. I have tried python 3.6 32 bit and 64 bit took it out and now I am trying 2.7 32.  I have windows 10 pro 64 bit.  However it is a amd cpu  I am not sure it that makes a difference or not.  Any help you could send my way would be greatly approached Thanks Reggie 
Possibly related #32739

@reggiekeene

Are you using the 64-bit version of VS Code or the 32-bit version ?

Does this reproduce in both the 32-bit version and the 64-bit version of VS Code ?

Does this reproduce when running code --disable-extensions ?

When the error is shown, can you please open the Developer Tools (Help > Toggle Developer Tools) and check if there is any additional information in there?

**Comment by Namatai** [comment]
Its easy to solve just disable all you plugins, reload window then restart vscode. then enable back all your plugins. **That will solve the Extension host terminated unexpectedly issue**.

**Comment by alexandrudima** [comment]
@reggiekeene If the error message pops up, can you please try clicking on "Developer Tools" to see if there are any errors logged in the console ?
