### ISSUE TITLE
Files shown twice in search results and quick-picker

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#32754]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
overtype|ada|0.2.0
markdown-emoji|bie|0.0.5
markdown-preview-github-styles|bie|0.0.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
smoothscroll|cya|1.0.4
vscode-markdownlint|Dav|0.10.0
lualinter|dcr|1.0.3
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.3.3
EditorConfig|Edi|0.9.4
LogFileHighlighter|emi|1.1.1
auto-close-tag|for|0.4.3
code-runner|for|0.6.33
cursoruler|fre|0.0.2
CppSnippets|har|0.0.12
tabsanity|jed|0.0.9
Lua|key|0.0.9
contextualduplicate|laf|0.2.0
MagicPython|mag|1.0.12
vscode-todo|Mat|0.8.0
lua-intellisense|met|0.2.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.2
indent-rainbow|ode|0.6.1
material-icon-theme|PKi|2.1.0
subtle-brackets|raf|2.0.2
you-complete-me|Ric|1.0.36
snake-trail|ric|0.6.0
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
trailing-spaces|sha|0.2.11
markdown-preview-enhanced|shd|0.2.5
indenticator|Sir|0.4.2
vscode-fileutils|sle|2.6.2
code-spell-checker|str|1.3.6
vscode-open-project|sve|0.0.9
python|tht|0.2.3
sort-lines|Tyr|1.3.0
clang-format|xav|1.5.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|0.8.3

(1 theme extensions excluded)

---

I frequently end up with "duplicate" file tabs open, one with the project-relative path and one with the file's absolute path. These shows up in the quick picker and in find-in-files results.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/1578924/29446000-311c26da-83ea-11e7-85f2-fbd4d4b7d792.png)

I restarted without extensions and then it seemed like it didn't come up in the quick picker but the find-in-files still found them. I only tried once and then restarted because I can't work well without my extensions.

Steps to Reproduce:

I'm not sure why or when this happens, sorry.

Reproduces without extensions: Yes (at least partly)

**Comment by Srekel** [comment]
Isn't it funny that after having lived with a bug for some time, it's not until you post the bug that the way it happens becomes apparent! :)

It seems like it's due to the C++ plugin - when I run and it hits a breakpoint, it doesn't open the file with the relative path, it opens it with the absolute path. So I should crosspost this to that extension.

So that explains why it shows up as a recent file. However, I'm not sure it makes sense for VS Code to still report it in the find-in-files pane? I don't mind closing this bug and reporting the same to the C++ plugin, but it would be great if someone could verify that this part of the bug is part of that extension or part of VS Code first.

**Comment by bpasero** [comment]
This most likely is due to case difference and that is https://github.com/Microsoft/vscode/issues/12448
