### ISSUE TITLE
切换文件夹以后就再也打不开老项目文件夹了

### ISSUE THREAD

**Issue by zhuxiao2004** [Microsoft/vscode#32751]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
vscode-standardjs|che|1.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
search-node-modules|jas|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.1.8
vuejs-extension-pack|mub|0.1.7
vetur|oct|0.9.3
vuehelper|oys|0.1.0
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
@zhuxiao2004 Please add details, steps and possibly screenshots (preferably in English...)
