### ISSUE TITLE
Git: failed to show text document

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32755]
With todays insider build I am often seeing this error when jumping from a diff to the source file or vice versa:

![image](https://user-images.githubusercontent.com/900690/29446788-64f66070-83ee-11e7-93e0-587430b2f3db.png)

**Comment by joaomoreno** [comment]
I can't reproduce.

Can you narrow down? Are you doing the jump through the editor title action? How many editor views do you have open?

**Comment by joaomoreno** [comment]
Reproduced with 2 editor panes.

**Comment by joaomoreno** [comment]
Bisect returns 4339a247abcdd7072336cd1731298cbca4c472b1 as the cause for this.

**Comment by alexandrudima** [comment]
Nice catch! Listeners were not registered for the already instantiated code editors, so the models and editors tracker was not updating when the workbench would call `.setModel()` on those code editors, thus failing in correlating things.
