### ISSUE TITLE
Implement extension host restarting

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#32768]
When the extension host crashes, the only way to recover is by reloading the window.

Implement a mechanism to correctly clean up state in the workbench due to the extension host and add an action to restart the extension host.

**Comment by jtsom** [comment]
I think instead of trying to work around the extension host restarting, maybe try to fix why it's crashing after a recent update! Having to click a Restart button after waking the system, or bringing the app to the front is a bit of a hack...

**Comment by jacobrillema** [comment]
I see they have a restart option now. However it keeps crashing for me even after clicking "restart extension host"

**Comment by jtsom** [comment]
The root of the crashing needs to be fixed - not just put a "restart the broken system" button!

**Comment by jens1o** [comment]
I absolutely agree with @jtsom ...

**Comment by alexandrudima** [comment]
@jtsom @jacobrillema 

This effort does not detract from making the extension host as stable as possible. It is, in fact, a precondition to get multi-root folders support working without a full window reload of VS Code when going from 0 folders -> 1 folder or from 1 folder -> N folders.

We are definitely interested in resolving the crashes, but please take into account that in order to produce a fix we need to be able to at least partially reproduce and/or understand what is the root problem of each crash.

Please create separate issues with as much as possible detailed information. e.g.:
* are you using VS Code insiders or stable ?
* are you on our new Windows 64 bit distribution ?
* does the crash reproduce when running `code --disable-extensions` ?
* does the crash reproduce on start-up (with no files opened) or is there a specific set of steps that leads to the crash ?
* what is printed in the Developer Tools when the crash occurs ? Is there any error message ?
* are you hitting #32620 i.e. you are on Insiders and the ext host crashes after a laptop sleep ? (**a fix will be out with the next Insiders build on Monday**)

Please create new issues with as much information as possible. We share the goal of making the extension host more stable.
