### ISSUE TITLE
support magic comments for specifying file encoding

### ISSUE THREAD

**Issue by vladdu** [Microsoft/vscode#32764]
Some programming languages use magic comments at the beginning of a file to specify the encoding of that file. From what I can see, this is not supported by vscode. I would like to suggest to have it implemented. It is a problem when one has projects where there are multiple encodings used across the code base.

**Comment by vladdu** [comment]
Eclipse has a nice mechanism where plugins can provide an encoding detector in code, but maybe it is enough to support searching for a magic regexp in the first two lines, as specified for example in https://www.python.org/dev/peps/pep-0263/

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/23132
