### ISSUE TITLE
workspace search: error parsing glob, nested alternate groups are not allowed

### ISSUE THREAD

**Issue by dominikschreiber** [Microsoft/vscode#32761]
### Setup

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
beautify|Hoo|1.1.1
java-properties|ith|0.0.2
vscode-jsp|pth|0.0.2
vscode-icons|rob|7.12.0
perforce|sle|2.1.1

(1 theme extensions excluded)

### Steps to Reproduce

with VSCode opened in folder `C:/MyFolder`

1. open workspace search (via `[CTRL][SHIFT][F]` or the magnifier icon in the activity bar)
2. specify a glob for *files to include*, e.g. `**/{MyFile1,MyFile2}.js`
3. search for anything

#### Expected:
search results only for files matching the glob

#### Actual: 
"search" field marked as invalid, shows the following error on focus:

> error parsing glob `'MyFolder\{**\{MyFile1,MyFile2}.js\**,**\{MyFile1,MyFile2}.js}'`: nested alternate groups are not allowed

Reproduces without extensions: Yes (started `code --disable-extensions`, reproduced the issue)

**Comment by dotlouis** [comment]
I have the same problem (also without extensions), It appeared with vscode 1.15. Worked well before.
Kinda annoying, I want to filter extensions: `**/*.{ts,scss,html,json}`
If there is another way to do it, I'd gladly take it.

**Comment by roblourens** [comment]
Workaround for now: if you use the `./` syntax, eg `./**/*.{ts,html}`, then it won't try to expand the glob with `{}`. 

I think I'll have to expand the pattern into two patterns, instead of expanding it with `{}`.
