### ISSUE TITLE
VSCode Version Issue

### ISSUE THREAD

**Issue by SensitiveMix** [Microsoft/vscode#32767]
- VSCode Version: <code>Code - Insiders 1.16.0-insider (aebaece67321b35f133be393fe8adcd50333d5ee, 2017-08-18T05:10:40.239Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)</code>
- Memory (System): <code>8.00GB (0.03GB free)</code>
- Memory (Process): <code>263.49MB working set (0.00MB peak, 169.09MB private, 87.54MB shared)</code>
- Load (avg): <code>3, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|78|
|main|app.isReady => window.loadUrl()|229|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|511|
|renderer|require(workbench.main.js)|1592|
|renderer|-> of which require() node_modules|164|
|renderer|create extension host => extensions onReady()|577|
|renderer|restore viewlet|0|
|renderer|restore editor view state|165|
|renderer|overall workbench load|293|
|main + renderer|start => extensions ready|3023|
|main + renderer|start => workbench ready|2722|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`683a_main.cpuprofile.txt`
-`683a_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
> ⚠️ Make sure to attach these files from your home-directory: ⚠️
> -683a_main.cpuprofile.txt
> -683a_renderer.cpuprofile.txt

@SensitiveMix ping
