### ISSUE TITLE
VSCode 1.15.1 Output default coding is not utf-8

### ISSUE THREAD

**Issue by iLibra** [Microsoft/vscode#32769]
- VSCode Version:1.15.1
- OS Version:MacOS 10.12.4

Steps to Reproduce:

1. I use Code-Runner plugin or Python plugin to run python codes

2. if I print some Chinese Char(encoded in utf-8)  in output window, it show below error:
UnicodeEncodeError: 'charmap' codec can't encode character
This is caused by the output window's default coding is not utf-8 but ascii. 

Please also refer to this issue: https://stackoverflow.com/questions/44724461/task-output-encoding-in-vscode

Sublime Text3 and Atom don't have this issue on Mac.

I changed python cmd as below for a workround:
 "python": "export PYTHONIOENCODING=utf-8 && cd $dir && python $fileName",

please fix this bug .
Thanks.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/3550

This got partly addressed by executing tasks in the terminal (e.g. tasks V2.0)

**Comment by iLibra** [comment]
@dbaeumer  Hi, I saw your comments in #3550, you said add "runner":"Terminal" for Task as a workaround. but I use the python plugin to run codes, I cannot set runner for the plugin. any suggestion?

**Comment by dbaeumer** [comment]
@iLibra you need to talk to the maintainers of the Python plugin then. They need to read the process output with the right encoding. The output panel is using strings in utf16 (this is how a string is defined in JS). The transformation of the enconding x into a JS string has to happen by the one running the process.
