### ISSUE TITLE
Slow startup detected

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#32774]
I'm guessing you'll be getting lots of these...
[a2ed_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1234162/a2ed_main.cpuprofile.txt)
[a2ed_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1234163/a2ed_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.16.0-insider (aebaece67321b35f133be393fe8adcd50333d5ee, 2017-08-18T05:10:40.239Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)</code>
- Memory (System): <code>8.00GB (1.50GB free)</code>
- Memory (Process): <code>209.39MB working set (0.00MB peak, 172.52MB private, 111.58MB shared)</code>
- Load (avg): <code>4, 3, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|80|
|main|app.isReady => window.loadUrl()|277|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|497|
|renderer|require(workbench.main.js)|566|
|renderer|-> of which require() node_modules|70|
|renderer|create extension host => extensions onReady()|1075|
|renderer|restore viewlet|648|
|renderer|restore editor view state|819|
|renderer|overall workbench load|1216|
|main + renderer|start => extensions ready|2569|
|main + renderer|start => workbench ready|2688|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`a2ed_main.cpuprofile.txt`
-`a2ed_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Actually nothing suspicious here... Closing without concrete actions but be assured that this Nov we'll solely focus on general performance improvements
