### ISSUE TITLE
Bad flex in quick open

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#32770]
Type `code-cli`:

![image](https://user-images.githubusercontent.com/22350/29454269-cf0d9bb8-840c-11e7-8025-d34359b60c2b.png)

**Comment by bpasero** [comment]
@joaomoreno I cannot repro. next time this happens if you can check dev tools to see if this is a browser issue or not.

There is a setting to keep quick open open on focus lost: `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by joaomoreno** [comment]
Seems like a browser issue from here. I'm using Linux, Ayu Mirage theme, zoom 0.

**Comment by bpasero** [comment]
Weird...

**Comment by bpasero** [comment]
Closing, unless we can repro.
