### ISSUE TITLE
Version 1.15.1 Code Expand/Collapse is not working

### ISSUE THREAD

**Issue by ssingh28** [Microsoft/vscode#32778]
- VSCode Version:  1.15.1
- OS Version: Win 10 64 bit

Steps to Reproduce:

1. Open any file (html, js, c#) in vs code
2. Press Ctrl+K, Ctrl+O
3. Expand / Collapse is not working

Reproduces without extensions: Yes

**Comment by JeremyLoy** [comment]
Are you referring to the `editor.fold` and `editor.unfold` actions if looking at the keyboard shortcuts json? I cannot reproduce on MacOS

**Comment by ssingh28** [comment]
Hey Jeremy,

Thanks for responding. But I am having this issue in win10, 64 bit. Below are the settings for workspace and user. I have tried uninstall and install multiple times but no success yet.

"editor.showFoldingControls": "mouseover",
"editor.folding": true,

**Comment by aeschli** [comment]
Do you see 'screenreader detected' in the status bar? If yes, turn this off. (see #32166)

**Comment by aeschli** [comment]
Closing due to lack of information.
