### ISSUE TITLE
[php] Incorrect Syntax Hghlighting in comment

### ISSUE THREAD

**Issue by ubtra** [Microsoft/vscode#32779]
Using a custom user snippet causes the green coloring of the comment to continue on past the end of comment. The issue seems to happen when the comment start with a double star /\*\* ... \*/ but goes away if /\*\*\* .. \*/ or /\* ... \*/. I've been using this snippet since I started using Code the issue seems have appeared in one the latest releases around 1.14.* 

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
phpunit|ema|1.0.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
code-spell-checker|str|1.3.6

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Create a PHP user snippet:
```JSON
        "Function Comments" : {
		"prefix": "doxy_func_comment",
		"body": [
			"/**",
			" * @brief $1",
			" * ",
			" * @param ($2) $3 - $4",
			" * @return $5, otherwise false",
			" *",
			" * @details $6",
			" */"
		],
		"description": "Doxygen Commenting with full description"
	}
```
2. Use the snippet
3. The green commenting color should stop at the end of the snippet. 

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
```php
/**
 * @brief 
 * 
 * @param ()  - 
 * @return , otherwise false
 *
 * @details 
 */
```
![image](https://user-images.githubusercontent.com/6461412/29461986-0753b54a-842e-11e7-98a9-a21f99c2eb24.png)

**Comment by ubtra** [comment]
Yes it appears fine it's by itself but if you have code under it the snippet it'll look like the code below is commented out as well.

![image](https://user-images.githubusercontent.com/7475151/29464805-16141a9e-8405-11e7-8920-821e2d170752.png)

**Comment by roblourens** [comment]
This looks fixed in the latest:
![image](https://user-images.githubusercontent.com/323878/30387212-b03ae7be-9860-11e7-9829-e35deee2b86f.png)

I think it was an issue that was fixed due to invalid `@param` not terminating at the end of the comment. You can see it still messes up highlighting of `@return` within the comment.

**Comment by ubtra** [comment]
Hm, I see. I guess my documenting formatting is incorrect that's fine. At least it's not causing the whole document to be all green now. Thanks!
