### ISSUE TITLE
C# code formatting ignoring EditorConfig settings

### ISSUE THREAD

**Issue by michaldudak** [Microsoft/vscode#32776]
Format selection / Format document commands seem to ignore the current EditorConfig settings when applied to a C# file.

I'm not sure if this repo is the right place for to log the issue. Please correct me if it should be elsewhere.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
EditorConfig|Edi|0.9.4
auto-rename-tag|for|0.0.14
vscode-flatland-icon-theme|geb|0.0.6
vscode-auto-open-markdown-preview|hnw|0.0.4
icon-fonts|idl|1.8.0
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.4.0
vscode-less|mrm|0.6.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
typescript-javascript-grammar|ms-|0.0.23
vs-keybindings|ms-|0.1.7
sass-indented|rob|1.4.1
autoimport|ste|1.2.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Have the following `.editorconfig` file in a directory:
```
root = true

[*]
indent_style = tab
````
2. Create a new C# file indented with tabs
3. Run Format Document command on it
4. See that tabs were converted to spaces.

One thing to note - `"omnisharp.useEditorFormattingSettings"` is set to `true` in my configuration.

Reproduces without extensions: No

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1726
