### ISSUE TITLE
No intellisense for node_module's JSDoc types referenced in another file

### ISSUE THREAD

**Issue by lyptt** [Microsoft/vscode#32771]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:06:21.685Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-nsp|ada|1.0.1
vscode-standardjs|che|1.1.7
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|4.3.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
vscode-firefox-debug|hbe|0.15.3
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.15.1
jenkins-declarative-support|jmM|0.1.0
VS-code-vagrantfile|mar|0.0.5
terraform|mau|0.0.16
vscode-duplicate|mrm|1.2.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.1.8
Ruby|reb|0.14.0
java|red|0.8.0
vscode-icons|rob|7.12.0
jenkinsfile-support|sec|0.1.0
ayu|tea|0.5.0
pdf|tom|0.2.0
vscode-todo-highlight|way|0.5.8
jinja|who|0.0.8
save-and-run|wk-|0.0.14

This may be due to circular type references. In my repro I have type A returning an instance of type B, which returns the original type A later. When this final return happens, all typing information is lost.

As a simple example:

```javascript

// File A

class A {
  something () {
    return new B(this)
  }
}

// File B

class B {
  constructor (a) {
    this.a = a
  }

  somethingElse () {
    return this.a
  }
}

// Consumer file

const a = new A().something().somethingElse() // determined to be 'any' instead of 'A'
```

Please see attached repro for a working example demonstrating this behaviour.

[repro.zip](https://github.com/Microsoft/vscode/files/1234091/repro.zip)

**Comment by mjbvz** [comment]
Yes, you currently need to import `A` in `b.js` for intellisense to pick up the types properly

We are discussing a better approach here: https://github.com/Microsoft/TypeScript/issues/14377 The proposal would allow you to reference types across files directly in jsdoc comments

Closing as upstream
