### ISSUE TITLE
open folder is not working

### ISSUE THREAD

**Issue by vikashartler** [Microsoft/vscode#32777]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-standard-format|che|0.0.12
vscode-eslint|dba|1.2.11
vscode-stylesheet-formatter|dba|0.2.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.7
tslint|eg2|0.17.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
json2ts|Gre|0.0.6
beautify|Hoo|1.1.1
TypeScriptImport|kev|1.17.0
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|1.7.2
sublime-keybindings|ms-|2.9.1
laravel-blade|one|1.8.1
vscode-html-scss|P-d|0.0.42
diff|raf|0.0.1
typescript-hero|rbb|1.4.0
sass-indented|rob|1.4.1
react-beautify|tai|0.3.0
html2jade|wma|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Need more details

**Comment by snarlynarwhal** [comment]
Definitely not working for me either. Yesterday it failed to open my project root folder (had to open only my scripts folder) and today it won't open any folder).

**Comment by roblourens** [comment]
I closed it because it doesn't have enough info to do anything about it. Could you open a new issue and give more details, like **exactly** what you're doing, how you're trying to open the folder, and what happens when you do that?

**Comment by snarlynarwhal** [comment]
I created a new issue and added as many details as I could. If you want more, please let me know what additional details you require.

#33289
