### ISSUE TITLE
Git can't handle non-ascii characters

### ISSUE THREAD

**Issue by khaosdoctor** [Microsoft/vscode#32782]
- VSCode Version: 1.15.1
- OS Version: MacOS Sierra

Steps to Reproduce:

It happens in some repositories, not in all of them. However the steps are simple:

1. Open a folder as a project
2. Use the embedded git to add ou restore changes (any action):
![image](https://user-images.githubusercontent.com/3200560/29462077-72225086-8404-11e7-9a56-f262de1fc3c9.png)

3. Message should appear

Message:
![image](https://user-images.githubusercontent.com/3200560/29462045-5766fcb0-8404-11e7-9c15-0b2a68bfd550.png)

![image](https://user-images.githubusercontent.com/3200560/29462058-63be7c68-8404-11e7-85d8-95bcaf35a70a.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you confirm that it only reproduces in repositories which path contains a _strange_ character like `ó`?

**Comment by khaosdoctor** [comment]
@joaomoreno Yep, it appears to happen only when there are different chars
