### ISSUE TITLE
Getting task to run in terminal in the current path.

### ISSUE THREAD

**Issue by cybertech99** [Microsoft/vscode#32781]
Just need to run command to the open terminal interface. not new process or output.

- VSCode Version: 1.15.1
- OS Version: Windows 7

Steps to Reproduce:

1. set powershell.exe as the terminal shell
2. open terminal
3. create task to run command dir
4. in terminal cd to any other folder then the root
5. run task it always returns the file sin root.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Add a `cwd` option to the task. This will run the task in that directory.

We don't have support to inject a task into a open terminal since there is no easy way to detect if a terminal is idle and can accept input. So we have no plans to add this.
