### ISSUE TITLE
Suggestion: Add Release Notes to Settings Gear

### ISSUE THREAD

**Issue by jovere** [Microsoft/vscode#32785]
A small request...
In the June version of VSCode, the update info menu was replaced with the gear in the bottom left corner.  However, with that gear, it no longer gives the opportunity to check the release notes before updating.

![image](https://user-images.githubusercontent.com/10420943/29462590-80d9b5f6-83f5-11e7-973a-12b45f334dfe.png)

**Comment by jens1o** [comment]
You can do that via `Help > Release Notes` can't you?

**Comment by jovere** [comment]
Oh, I guess you can.  That wasn't immediately obvious.  I would have thought the release notes in the help menu would be for the present revision, not the one it's going to download.

**Comment by csandfeld** [comment]
I would like to see that implemented as well (release notes for the new version in the gear menu).
The release notes available in the help menu as suggested by @jovere, shows release notes for the currently installed version.

**Comment by Kroc** [comment]
I have menu hidden by default so would appreciate this.
