### ISSUE TITLE
Tab Character Inserted During Tab Completion

### ISSUE THREAD

**Issue by aarontheadmin** [Microsoft/vscode#32789]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1. In editor pane, type **Test-Pa** and press tab to tab complete (should work).
2. Delete any character(s) in 'Path' and press tab again and see that a tab character is inserted instead of completing the syntax.

Any cmdlet, parameter or value will not be tab completed.

This issue doesn't appear when using the Terminal pane.

Reproduces without extensions: N/A

**Comment by ramya-rao-a** [comment]
Are you trying to completions in Powershell scripts?

If yes, then the completions come from the Powershell extension. Please log an issue in the repo for the extension
