### ISSUE TITLE
[High contrast] Activity bar icons look blurry on hover

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3278]
#3248

Hover over an activity bar icon - looks blurry imho

![screen shot 2016-02-23 at 10 55 44](https://cloud.githubusercontent.com/assets/1926584/13247901/15dfcada-da1c-11e5-976d-93a51cfa7994.png)

**Comment by bgashler1** [comment]
Thanks for catching this.  I solved a similar issue to this before the test plan, so hopefully it will be a similar solution that I can apply to this. Thanks!

**Comment by bpasero** [comment]
I am not seeing this anymore.
