### ISSUE TITLE
I want to know what happened

### ISSUE THREAD

**Issue by gquittet** [Microsoft/vscode#32795]
I saw this post that makes a bad advertising to Microsoft and VS Code:
https://9gag.com/gag/a247Nyp?ref=ios.s.cp

I want to know what happened. Is it a fake? Why his account has been deleted? And why the issue has been deleted too?

**Comment by SpaceK33z** [comment]
It is not fake, the issue has been deleted but you can see it in [google cache](https://webcache.googleusercontent.com/search?q=cache:7kX5VunbdlwJ:https://github.com/microsoft/vscode/issues/32405+&cd=1&hl=en&ct=clnk&gl=us).

**Comment by mjbvz** [comment]
For an explanation of the problem, please see @joaomoreno's comment on the original issue: https://web.archive.org/web/20170817134338/https://github.com/microsoft/vscode/issues/32405

The user did not understand the impact of running the git `Discard all changes` command. We already had an alert that warns you that `Discard all changes` would discard all changed files and was irreversible, but it we are looking into improving the messaging with https://github.com/Microsoft/vscode/issues/32459

**Comment by gquittet** [comment]
It's not a bug in VSCode. The user is so stupid lol I think he did not make a project. When you make a project, you've got backup ^^ He don't know how to use git ^^ It's a beginner. I don't know why he delete his github account.
