### ISSUE TITLE
How to use vscode namespace api in a Debug Adapter?

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode#32794]
- VSCode Version: 1.14.2
- OS Version: Win10 RS2

How can I use vscode namespace api in an implementation of DebugSession (or say Debug Adapter)?

For example, I want to use https://code.visualstudio.com/docs/extensionAPI/vscode-api#extensions.getExtension in my implementation of DebugSession. But this API is not available in the runtime of the DebugSession 

What is the recommended way to work around it? 

Reproduces without extensions: Yes

**Comment by weinand** [comment]
You **can not** use the VS Code extension API (vscode namespace) in a debug adapter because the debug adapter does not run in the extension host but is a separate process.

If you need to access some functionality from the vscode namespace, you'll have to create a regular extension that lives side by side to the adapter but runs in the extension host. In this extension you can directly talk to the DA and pass information along.

**Comment by changsi-an** [comment]
> you can directly talk to the DA and pass information along

Can you suggest how this is done? Is there any existing infrastructure that can assist implementing such cross process communication?

**Comment by weinand** [comment]
There are basically two mechanisms:
- the extension can intercept the start of a debug session and modify the launch configuration that is passed from VS Code to the debug adapter. With this you can pass additional information that you have gathered with the vscode extension API to the DA. [This example from node-debug](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/extension.ts#L194) shows (among other things) how a missing 'cwd' attribute is added to the launch config before it is passed to the DA. 

- you can send custom requests from the debug extension to the DA (via VS Code) and you can receive custom events from the DA in the debug extension. [This example](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/loadedScripts.ts#L298-L302) shows how a custom request is send to the DA to retrieve all loaded scripts. And [this example](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/loadedScripts.ts#L36-L48) shows how a custom event is handled.

**Comment by changsi-an** [comment]
How about sending information from the DA to the debug extension? What is the recommended way to do that?

**Comment by weinand** [comment]
As said above: [send a custom event from the DA to the debug extension](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L443-L446).

**Comment by changsi-an** [comment]
Gotcha. Thanks!
