### ISSUE TITLE
Moving the cursor should not cancel tab stops in a snippet

### ISSUE THREAD

**Issue by NiekPas** [Microsoft/vscode#32790]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.7.0
cpptools|ms-|0.12.3
Ruby|reb|0.14.0

---

Steps to Reproduce:

1. Open a .html file.
2. Type `a` and press `tab`. The cursor should now be between the double quotes after `href`.
3. Move the cursor.
4. Press `tab` again.
5. Verify that rather than jumping to the next tab stop, pressing `tab` has inserted a tab whitespace character.

The same issue occurs using the following user-defined snippet rather than the emmet abbreviation:

    "link": {
        "prefix": "a",
        "body": "<a href=\"$1\">$2</a>" 
    },

I'm assuming that this is not intended behavior, but if it is, I feel like there should be a setting to disable it. Moving the cursor to copy-paste text into snippet tab stops is an important part of some of my workflows, and I don't think I'm alone in that (this used to work in previous versions; I am not 100% sure in which version this issue first emerged).

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@NiekPas 

In you Step 3, where are you moving the cursor to? A separate location from where you wish to copy text?

When a snippet is inserted, tabbing moves you to the next tab stop, typing adds text and the next tab takes you to the next tab stop.
The moment you move the cursor manually, I believe you are taken out of the snippet mode

cc @jrieken for more snippet related info

**Comment by NiekPas** [comment]
Usually it's a separate location that contains text I want to copy into one of the tab stops. In the example of the `<a>` tag, this could be a hyperlink.

**Comment by jrieken** [comment]
That is the design of snippets. You can move your cursor into placeholders and tabstops but as soon as you move it somewhere else snippet insertion stops. The rational for this is to have a light snippet mode that isn't sticky and hard to get out of. Also note that snippets behave like this in Textmate and Sublime.
