### ISSUE TITLE
Quick navigate + arrow keys moves two entries at a time

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#32793]
- Press ctrl+tab, hold ctrl
- Use arrow keys
- The selection moves down two rows on each press

![aug-18-2017 10-57-58](https://user-images.githubusercontent.com/323878/29471254-2961a7c0-8404-11e7-9dd3-e7ce2f7aa100.gif)

Probably not related to your change @Lixire but can you check if your new arrow key handler is involved somehow?

**Comment by Lixire** [comment]
Looks like this is indeed my new arrow key handler's problem. I thought that the `DOM.EventHelper.stop(e, true)` would prevent things like this from happening though?

**Comment by roblourens** [comment]
It will keep it from bubbling up to other elements but I don't think it should prevent it from calling other handlers on the same element. So I think the other listener must actually be on the same element.
