### ISSUE TITLE
Mark occurrences don't show in high contrast theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3279]
Testing #3248

![image](https://cloud.githubusercontent.com/assets/22350/13247962/62565712-da1c-11e5-9f15-4eb325ddf6d1.png)

Here's what it looks like in another theme:

![image](https://cloud.githubusercontent.com/assets/22350/13247981/69074e22-da1c-11e5-83d3-ad67ecc670b5.png)

**Comment by bgashler1** [comment]
Just tested this, and it seems to have been resolved with another commit I made.  Assigning back to you for confirmation.

**Comment by joaomoreno** [comment]
I can't verify since you didn't push your changes to our master branch.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/25474109/3e07c536-2b32-11e7-872b-b4cafcf1a794.png)
