### ISSUE TITLE
VSCode 1.15 is not rendering the terminals for cmd.exe and bash.exe

### ISSUE THREAD

**Issue by diogo-paschoal** [Microsoft/vscode#32796]
I'm using the VSCode x32 to call for this report, but the problem happened on x64 distribution.
After i install it, it won't show the terminals for cmd.exe and bash.exe. The terminal opens and dot not show anything on its window.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
bower|don|0.0.3
python|don|0.7.0
vscode-npm-script|eg2|0.2.0
hg|mrc|1.1.5
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Install Version 1.15.1 on Windows 10 Professional x64, build 15063.
2. Select any terminal on user configurations.
3. Open the terminal.

My settings.json:
```
{
// Editor
    "editor.fontSize": 18,
    "editor.renderWhitespace": "boundary",
    "editor.minimap.enabled": true,
// Files
    "files.exclude": {
        "**/bin": true,
        "**/obj": true,
        "**/*.orig": true,       // backup files from version control
        "**/.idea": true,       // pycharm file
        "**/sessions.db": true, // linesman database
        "**/.sonarlint": true,
        "**/.sonar": true,
        "**/.vscode": true,
        "**/*.pyc": true,       // compiled python
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true    // OSX storage file
    },
    "files.autoSave": "onFocusChange",
    
    // Integrated Terminal
    "terminal.integrated.lineHeight": 1,
    "terminal.integrated.fontSize": 18,

    "workbench.colorTheme": "Monokai Dimmed",
    "window.zoomLevel": 0
}
```

**Comment by Tyriar** [comment]
Can you share your settings.json? Also you're running on a 64-bit version of Windows, correct?

**Comment by frezbo** [comment]
I have the same issue here, after the last two releases my Ctrl+` combination fails to render the integrated terminal on Fedora 26 x86_64. 

```
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
```

This is my settings as a gist: https://gist.github.com/frezbo/c748cca264592bf471b4ced00d5af4b9

**Comment by Tyriar** [comment]
Looks like e.isExpanded is probably unrelated https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=isExpanded&type=

@frezbo can you post a screenshot of the broken terminal, including the dropdown box?

**Comment by frezbo** [comment]
![screenshot from 2017-08-19 12-15-36](https://user-images.githubusercontent.com/18496730/29484249-29f716d2-84d8-11e7-8591-cb1f636252f6.png)
This is what happends when I do Ctrl+`

**Comment by Tyriar** [comment]
@isidorn It looks like the panel is getting shown but the terminal panel ID isn't getting focused, any ideas?

**Comment by frezbo** [comment]
@Tyriar When I quit VSCode at this point using Ctrl+Q and reopen and try Ctrl+` a few times then it corectly opens at terminal still throwing the e.isExpanded error, and it starts again when I switch between my git projects using GPM

**Comment by rstropek** [comment]
Same problem here. I had VSCode 32bit -> bash works fine. Upgrade to x64 -> bash terminal broken. Downgrade to 32bit -> fine again. Here are my settings:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 16,
    "window.zoomLevel": 0,
    //"editor.wordWrap": "bounded",
    "git.confirmSync": false,
    "search.exclude": {
        "**/node_modules": false,
        "**/bower_components": true
    },
    "workbench.colorTheme": "Default Light+",
    "typescript.check.tscVersion": false,
    "terminal.integrated.shell.windows": "\\WINDOWS\\sysnative\\bash.exe",    
    "editor.renderWhitespace": "none"
}
```
Environment: Windows 10, build 15063

**Comment by diogo-paschoal** [comment]
There is no error for me on developer tools console.
My settings.json:
`// Place your settings in this file to overwrite the default settings
{
// Editor
    "editor.fontSize": 18,
    "editor.renderWhitespace": "boundary",
    "editor.minimap.enabled": true,
// Files
    "files.exclude": {
        "**/bin": true,
        "**/obj": true,
        "**/*.orig": true,       // backup files from version control
        "**/.idea": true,       // pycharm file
        "**/sessions.db": true, // linesman database
        "**/.sonarlint": true,
        "**/.sonar": true,
        "**/.vscode": true,
        "**/*.pyc": true,       // compiled python
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true    // OSX storage file
    },
    "files.autoSave": "onFocusChange",
    
    // Integrated Terminal
    "terminal.integrated.lineHeight": 1,
    "terminal.integrated.fontSize": 18,

    "workbench.colorTheme": "Monokai Dimmed",
    "window.zoomLevel": 0
}`

**Comment by isidorn** [comment]
@Tyriar sorry for the slow response I was on vacation.  No ideas what could be wrong.
Can users reproduce this without any extensions (since in the screenshot I see around 10 contributed views)?
@Tyriar where you able to reproduce this?

**Comment by Tyriar** [comment]
@isidorn no I can't repro

**Comment by diogo-paschoal** [comment]
Please, do not close it. I've added all the informations requested before. Same problem with the new version: 1.16 even with extensions disabled (same for 1.15.1).
The screenshot is bellow:
![1 16](https://user-images.githubusercontent.com/2343337/30181108-929562ba-93e8-11e7-8f58-e0e9e2bd77d4.png)

**Comment by Tyriar** [comment]
@diogo-paschoal your settings file quoted above does not have a shell specified, so bash should not be in the dropdown?

**Comment by diogo-paschoal** [comment]
@Tyriar, sorry, i've forgot to add the workspace settings (the previous was the user settings):

```
{
    // Terminal
    "terminal.integrated.shell.windows": "C:/WINDOWS/Sysnative/bash.exe",

    // Python
    "python.pythonPath": "C:/Users/pasch/Envs/env/Scripts/python.exe",
    "python.linting.pylintPath": "C:/Users/pasch/Envs/env/Scripts/pylint.exe",
    "python.linting.enabled": true,
    "python.linting.mypyPath": "C:/Users/pasch/Envs/env_python3/Scripts/mypy.exe",
    "python.linting.mypyEnabled": true,

    //Editor
    "files.associations": {
        "*.jinja2": "html"
    },

    //ESLint
    "eslint.enable": true
}
```

**Comment by Tyriar** [comment]
@diogo-paschoal Try using "C:\\Windows\\System32\\bash.exe", also make sure you have bash.exe installed (run bash.exe in a cmd.exe window).

**Comment by diogo-paschoal** [comment]
@Tyriar, i've tested against the new version too (1.16.1) and the problem is the same.
Set the path as you mentioned (little change) made it work again.

```
"terminal.integrated.shell.windows": "C:/Windows/System32/bash.exe",
```
