### ISSUE TITLE
First time app not opening selected folder

### ISSUE THREAD

**Issue by mattewood-comcast** [Microsoft/vscode#32799]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Open the app for the first time
2. Click the big blue Open Folder button
3. Select any folder to open
4. Finder window closes and nothing happens

Expected Behavior:
When clicking open on the folder that I wanted the folder should have imported

Closing and reopening the app fixed the issue

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
