### ISSUE TITLE
Latin1 encoded files are not auto-detected

### ISSUE THREAD

**Issue by clarking** [Microsoft/vscode#32798]
I need to "Reopen file with Encoding" for a Latin-1 file every time i open that file to show accented chars correctly, i tried to save the file with the new encoding but does not work.

i wish Vscode can auto-detect the encoding or at least remember the encoding of the file when i open it.

Thank you guys, keep up the awesome work.

Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version:
Xubuntu 16.04 xenial 
4.10.0-30-generic #34~16.04.1-Ubuntu 

Steps to Reproduce:

1. Open a Latin-1 file in editor (displays in UTF-8 by default)
2. Change encoding to Western (ISO-8859-1)
3. Save and close the file
4. Open same file again and it's displayed as UTF-8

**Comment by bpasero** [comment]
@clarking does it help if you configure `"files.autoGuessEncoding": true` ?

**Comment by clarking** [comment]
thank you for the response, when i use the option `"files.autoGuessEncoding": true` the file displays correctly but assigns the Windows 1252 encoding which is very similar to ISO-8859-1, it will be amazing if the editor can remember the encoding you set to the file when you open it for the first time. In the meantime i will keep the autoguesscontent option enabled

thank you again and keep up the awesome work
