### ISSUE TITLE
I saw that you have deleted another issues

### ISSUE THREAD

**Issue by CitoplasmaX** [Microsoft/vscode#32797]
I saw that you have deleted another issues

http://cc.bingj.com/cache.aspx?d=1462716999241&mkt=de-DE&setlang=en-US&w=xEsMxqoa0KJSwMsTh3p_8w2qryykfDvB

https://github.com/Microsoft/vscode/issues/32405

**Comment by CitoplasmaX** [comment]
I think that you only want hide big problems into vscode.

**Comment by mjbvz** [comment]
We did not delete this issue. I believe the user who reported it deleted it along with their github account. For an explanation of the problem, please see joaomoreno's comment on the original issue: https://web.archive.org/web/20170817134338/https://github.com/microsoft/vscode/issues/32405

The user did not understand the impact of running the git `Discard all changes` command. We already had an alert that warns you that `Discard all changes` would discard all changed files and was irreversible, but we are looking into improving the messaging with https://github.com/Microsoft/vscode/issues/32459

**Comment by gquittet** [comment]
It's not a bug in VSCode. The user is so stupid lol I think he did not make a project. When you make a project, you've got backup ^^ He don't know how to use git ^^ It's a beginner. I don't know why he delete his github account.
