### ISSUE TITLE
Feature: allow editing the taskSampleConfig file

### ISSUE THREAD

**Issue by aochagavia** [Microsoft/vscode#328]
I am thinking of adding a command called "Tasks: Edit Sample tasks.json" which opens `workbench\parts\tasks\common\taskSampleConfig.json`.

Would this be a useful feature?

**Comment by dbaeumer** [comment]
[Addressed in new terminal runner]

The new terminal runner support contributing tasks via API. As soon as this is the default extensions will be able to provide tasks programmatically so there is no need for providing samples configs anymore.

**Comment by dbaeumer** [comment]
Closing since this is addressed in the new terminal runner and task 2.0.0.
