### ISSUE TITLE
Middle-clicking tab above editor to close document also sets cursor to scroll mode

### ISSUE THREAD

**Issue by JBoxman7** [Microsoft/vscode#32804]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
open-html-in-browser|cod|0.1.21
githistory|don|0.2.3
python|don|0.7.0
git-project-manager|fel|1.3.2
mdmath|goe|1.2.9
live-html-previewer|hdg|0.2.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
java|red|0.8.0
vscode-autohotkey|sle|0.2.1
html-preview-vscode|tht|0.1.1
vscode-preview-server|yui|0.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Middle-click tab above editor to close
2. Move mouse around and notice cursor change

The cursor can be returned to normal pointer mode by middle-clicking again

Reproduces without extensions: Yes/No

**Comment by CnSimonChan** [comment]
#16690

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
