### ISSUE TITLE
High contrast: suggest box needs love <3

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3280]
#3248 
Suggest box is not high contrast friendly

![screen shot 2016-02-23 at 10 59 01](https://cloud.githubusercontent.com/assets/1926584/13248011/8601c64c-da1c-11e5-8e8b-df65e3f61b59.png)

**Comment by joaomoreno** [comment]
This is not fixed.

![image](https://cloud.githubusercontent.com/assets/22350/13281102/1d6d644e-dae2-11e5-8e0a-a248507069bd.png)

**Comment by joaomoreno** [comment]
@bgashler1 I just noticed you keep your changes in your own fork of the repository... Either push them to our master branch or don't close your issues...

**Comment by joaomoreno** [comment]
:+1:
