### ISSUE TITLE
Ctrl-Delete in integrated terminal produces capital "D" instead of deleting word.

### ISSUE THREAD

**Issue by SabinT** [Microsoft/vscode#32807]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
tslint|eg2|0.17.0
gc-excelviewer|Gra|1.1.15
beautify|Hoo|1.1.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.8

---

Steps to Reproduce:

1. Open the integrated terminal
2. Type a word, move cursor to the start of the word, try to delete the word by using Ctrl-Delete (works in normal windows powershell) => The result is a capital "D" instead

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31821
