### ISSUE TITLE
Problem sorting line by Alt and arrow keys

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#32817]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 6.3.9600
---------------------------------------------
Hi, Please check this gif. (Problem sorting line by Alt and arrow keys)
![untitled](https://user-images.githubusercontent.com/5067331/29483835-1c69db10-84c6-11e7-855b-0365b13f825e.gif)

Thanks

**Comment by marhalpert** [comment]
Related: https://github.com/Microsoft/vscode/issues/33127

**Comment by rebornix** [comment]
This issue shares the same root cause of https://github.com/Microsoft/vscode/issues/32320. The root cause we check onEnter rules on wrong content when moving down. Let's track this issue there and thanks for the feedback.
