### ISSUE TITLE
'Git: Open Changes' doesn't focus the newly opened tab with the diffs

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#32816]
- VSCode Version: Code - Insiders 1.16.0-insider (aebaece67321b35f133be393fe8adcd50333d5ee, 2017-08-18T05:22:55.860Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.0
EditorConfig|Edi|0.9.4
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
atom-keybindings|ms-|3.0.1
vetur|oct|0.9.4
stylelint|shi|0.28.0
---

Steps to Reproduce:

1. Open the command pallet.
2. Invoke "Git: Open Changes"  (there must be some outstanding changes in the current git repo)
3. The new tab with the changes opens.
4. The tab is *NOT* focused, so I had to grab the mouse and perform the click. Without focus, the keyboard navigation in the diff view is not working (like the up/down arrow, for example).
5. I have some extra keybindings, specially for this diff view, and they don't work as well, until I focus the diff view.

This seems to be a regression, it worked fine earlier.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This came with #27411

We should be able to know when this happens and set focus accordingly.

**Comment by vvs** [comment]
@joaomoreno I can still  reproduce the problem on both, the latest VS Code Insiders and the freshly built from source as well.

Please note that I am using the keyboard shortcut for the "git.openChange". In my case it is `alt+d`.

So, currently, when I press `alt+d` on a file that has changes in it, a new tab with diffs opens, but not focused.

Should I file a separate bug for that?

I also noticed that when using the command palette to "Git: Open Changes", focus works.

**Comment by joaomoreno** [comment]
I actually pushed a change today which should address that too. Let me know with tomorrow's update if that fixes it for you.

**Comment by vvs** [comment]
Thank you, it works for me when VS Code is build from the sources! So I assume it will continue to work in tomorrow insiders build as well :)

👍

**Comment by joaomoreno** [comment]
Sweet, great to know. Thanks!
