### ISSUE TITLE
Problem with C++ scope detection

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#32815]
- VSCode Version: 1.15.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create this `.cpp` file, put the cursor in the function body of `foo()`.
<img width="609" alt="screen shot 2017-08-18 at 20 18 45" src="https://user-images.githubusercontent.com/18319900/29483043-d846cb96-8452-11e7-985e-1e3e8d3bda66.png">

2.Check the scope at the down-right corner of VSCode window. It says "Global scope", but it should be a function scope (if I understand this feature correctly).

3. If the cursor is inside a class definition, it still says "Global scope".

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vscode-cpptools/issues/1173
