### ISSUE TITLE
Can not click on error messages in the Integrated Terminal

### ISSUE THREAD

**Issue by ericfr** [Microsoft/vscode#32810]
I can not click on error message in the Terminal window. When an error is generated, it shows up in the Integrated Terminal.
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app/group/group-monthlycalendar/group-monthly-calendar.ts:180:24
    TS2339: Property 'getTrainerById' does not exist on type 'CalendarService'.

I can not click on the error so that the editor opens the file and highlights the line number.

- VSCode Version: 1.15.1
- OS Version: MacOS Sierra (10.12.5 (16F73))

Steps to Reproduce:

1. Using Typescript, generate a compilation error
2. An error message shows up in "Terminal"; click on the error
--> nothing happens

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
cmd+click is meant to work, provided that the folder containing `./src/` is the folder opened in VS Code. Is this the folder you have open?
