### ISSUE TITLE
Code action lightbulb not showing up for selections when no markers are set

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#32812]
- VSCode Version: code-oss-dev 1.16.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 16.7.0

---

**Steps to Reproduce:**

1. In a build of VSCode with TS 2.5
2. Write a `ts` file:

```ts
class FOO {
    bar() {
        return 123;
    }
}
```

3. In the file, highlight `123`

**Expected**
There are code actions to extract `123` to its own method. The lightbulb should be shown for these

**Actual**
The code action lightbulb only shows up when there is no selection, such as placing the cursor before the `123` like so: `|123`. If the `123` is selected, lightbulb goes away but you can still manually trigger the code action context menu

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Looking through the code action unittest for #29933, I'm not sure if this behavior is be by designed or not.

**Comment by jrieken** [comment]
Take a look at [_getActiveMarkerOrWordRange](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L89). The rule is that we either take a marker range or word range. The string `123` isn't considered a word I'd say and therefore we ignore it. So, yes that is the design. However, you can always manually request code actions and the current editor selection will be used.
