### ISSUE TITLE
ctrl+shift+p binding to commands palette broken

### ISSUE THREAD

**Issue by sldsrg** [Microsoft/vscode#32828]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
python|don|0.7.0
debugger-for-chrome|msj|3.1.8

---

Steps to Reproduce:

1. Configure keyboard layout switcher to use combination Ctrl+Shift
2. Press Ctrl+Shift+P in VSCode: command palette don't shown and keyboard layout switched

On Windows platform everything is fine.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
That's of course unfortunate, but such conflicts can't be avoided. 
The solution is to use `F1` to open the command palette. Or, configure the key binding on the key binding configuration page (or in your OS)
