### ISSUE TITLE
Find references background is wrong in High Contrast theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3282]
Testing #3248

![image](https://cloud.githubusercontent.com/assets/22350/13248071/d0577480-da1c-11e5-88ce-4f61ee53f0c0.png)

ping @jrieken

**Comment by joaomoreno** [comment]
Also in Peek Definition

**Comment by joaomoreno** [comment]
This looks even worse now.

![image](https://cloud.githubusercontent.com/assets/22350/13281058/dddaf4e0-dae1-11e5-9693-97a1ba767c96.png)

**Comment by bgashler1** [comment]
Sorry, forgot to assign this back to you for verification.

**Comment by joaomoreno** [comment]
Still broken:

![image](https://cloud.githubusercontent.com/assets/22350/14912153/a6dbac5e-0dfa-11e6-9709-cc311eeffdb5.png)
