### ISSUE TITLE
MacOS ctrl-h doesn't work correctly with IME

### ISSUE THREAD

**Issue by mazamachi** [Microsoft/vscode#32822]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.3.0 (macOS)
- Extensions: --disable-extensions

---

Steps to Reproduce:

1. Open any file.
2. Turn on an IME such as macOS standard IME or Google Japanese IME.
3. Write some texts with the IME.
4. Put `ctrl + h`.

Expected: Delete the last character on the IME just like backspace.
[![https://gyazo.com/4e87f8a0ace2e8dfde4ee4a0d0b11622](https://i.gyazo.com/4e87f8a0ace2e8dfde4ee4a0d0b11622.gif)](https://gyazo.com/4e87f8a0ace2e8dfde4ee4a0d0b11622)
(in CotEditor)

Actual: Delete the last character on the IME __and the character before the IME input.__
[![https://gyazo.com/64eb3ac6fda1cf14f95935bc41f6187d](https://i.gyazo.com/64eb3ac6fda1cf14f95935bc41f6187d.gif)](https://gyazo.com/64eb3ac6fda1cf14f95935bc41f6187d)

In the same way, ctrl-A, ctrl-F, and ctrl-B don't work correctly.
I think this is because key down event propagation is not stopped even if the IME is enabled.
https://github.com/Microsoft/vscode/issues/25023 and https://github.com/Microsoft/vscode/pull/24980 are related to this issue.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Fixed via PR #32826
