### ISSUE TITLE
i met a problem when i tried to open a folder

### ISSUE THREAD

**Issue by GH-Ryan** [Microsoft/vscode#32821]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.7
vsc-material-theme|Equ|1.0.2
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
Angular2|joh|2.4.0
code-beautifier|mic|1.7.2
easy-less|mrc|1.4.5
debugger-for-chrome|msj|3.1.8
LiveServer|rit|1.6.9
code-settings-sync|Sha|2.8.2
stylelint|shi|0.28.0
open-in-browser|tec|1.1.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.why can't I open a folder named"京东WEB"?if ichanged it to "京东",it works.
2.forgive my poor english.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@GH-Ryan What problem did you encounter? This seems to work for me just fine on Windows 10.

**Comment by GH-Ryan** [comment]
@rcjsuen  Thank you for your attention.It works now.I think my comtuper may has some problems.
