### ISSUE TITLE
'g++' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by akashhdr** [Microsoft/vscode#32827]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.4.1
javadebugger|don|0.1.3
python|don|0.7.0
php-debug|fel|1.11.1
code-runner|for|0.6.33
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.8
Ruby|reb|0.14.0
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

As I am running my cpp program, it's showing something like:    'g++' is not recognized as an internal or external command, operable program or batch file.

What should I do??
![error](https://user-images.githubusercontent.com/31161908/29487605-bab9e924-8519-11e7-98e6-4816efa30933.jpg)

**Comment by weinand** [comment]
How are you running your "cpp program"? As a task?
