### ISSUE TITLE
HTML feature:  Automatically update closing html tag

### ISSUE THREAD

**Issue by Lev09** [Microsoft/vscode#32824]
It would be great to have closing tag updated, when opening tag is edited.
like this there will be no need to change closing html tag manually, which is simply a lost of time.

**Comment by usernamehw** [comment]
[Extension - auto rename tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)

**Comment by ramya-rao-a** [comment]
You can use `Emmet: Update Tag` command to do this

Keep the cursor either in the opening tag or the closing tag or inside the tag (but outside any child tags)

![updatetag](https://user-images.githubusercontent.com/16890566/29489706-f95462f6-84db-11e7-92e0-3973dd1ed0bc.gif)
