### ISSUE TITLE
Error in  Italian i8n

### ISSUE THREAD

**Issue by nanomad** [Microsoft/vscode#32825]
- VSCode Version: 1.15.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Set language to Italian
2. Open search bar (Ctrl + F)
2. Type something that should have no results 
3. Notice the wrong translation: "Nessuna impostazione corrispondente"

**This actually makes the search input box too short to be useful**

Expected
- Translation should be the same as in other places: "Nessun risultato"

Reproduces without extensions: Yes

Affected files:
`i18n/ita/src/vs/editor/contrib/find/browser/findWidget.i18n.json`
(key: `label.noResults`)

**Comment by roblourens** [comment]
In what other places do we use `Nessun risultato`?

**Comment by nanomad** [comment]
Here:

i18n/ita/src/vs/editor/contrib/rename/browser/rename.i18n.json
i18n/ita/src/vs/editor/contrib/referenceSearch/browser/referencesWidget.i18n.json

It's the litteral translation of "No Results"

**Comment by danyeh** [comment]
This was fixed on 9/5 in Transifex. Fix now imported to vscode github project.
