### ISSUE TITLE
highlighting: nested field accesses colored inconsistently

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#32820]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
php-formatter|Sop|0.2.4
githistory|don|0.2.3
javadebugger|don|0.1.3
python|don|0.7.0
phpunit|ema|1.0.0
git-project-manager|fel|1.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
code-runner|for|0.6.33
vscode-javac|geo|0.0.46
phpcs|ika|0.7.0
Go|luk|0.6.63
prettify-json|moh|0.0.3
mssql|ms-|1.1.0
cpptools|ms-|0.12.3
Ruby|reb|0.14.0
gitblame|wad|2.1.0

---

Steps to Reproduce:

1. Enter into a function:

```go
a.b = 1
a.b.c = 2
a.b.c.d = 3
a.b.c.d.e = 3
```

2. See the following inconsistent field accessor syntax highlighting:

<img width="175" alt="screen shot 2017-08-19 at 1 21 38 am" src="https://user-images.githubusercontent.com/63830/29484886-3def6456-847d-11e7-869f-4b8bf83414cb.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
@willfaught That is go code, correct?

**Comment by willfaught** [comment]
Yes

**Comment by ramya-rao-a** [comment]
This issue was moved to atom/language-go#135
