### ISSUE TITLE
[x64] Unable to install extensions from command line

### ISSUE THREAD

**Issue by DominikJaniec** [Microsoft/vscode#32823]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: Not yet installed...

---

Steps to Reproduce:

1. Install the new one, 64 bit version of Visual Studio Code.
2. Try install any extension via CLI:
      * `$ code --install-extension ms-vscode.csharp`
3. Wait for the _Heat death of the universe_ with messages in console:
```
Found 'ms-vscode.csharp' in the marketplace.
Installing...
(node:6584) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:6584) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

4. It is possible that it will finish eventually, but I was waiting about 30 minutes (for the first time), and then I had pressed `Ctrl + C`. When I was checking all extensions which I would like to use, I was waiting less then one minute for each one, but in both cases Process Explorer shows 0% of CPU usage for VS Code.

---

Why I would like to install extensions from console? Well I have got PowerShell script which will install all of from my list, and then synchronizes configuration with OneDrive and Git repo via Hard Links (see: [GitHub](https://github.com/DominikJaniec/EnvConfigs/blob/6069a7aa53c5e950734a9645285c0927d397563a/vscode/_prepare.ps1#L37)). This script was working for previous version of VS Code which was 32 bit. Finally extensions were installed via _Extension Manager's tab_. Here is a list of extensions which I had checked:
  * donjayamanne.githistory
  * hoovercj.haskell-linter
  * Ionide.Ionide-fsharp
  * ms-vscode.csharp
  * ms-vscode.PowerShell
  * ms-vscode.vs-keybindings
  * sbrink.elm
  * streetsidesoftware.code-spell-checker
  * Vans.haskero
  * vscodevim.vim
  * yzane.markdown-pdf

**Comment by Findarato** [comment]
I can confirm that I am having the same issues 

```
Found 'wholroyd.jinja' in the marketplace.
Installing...
(node:13789) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:13789) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
Fedora 26
uname -a
Linux 4.12.5-300.fc26.x86_64 #1 SMP Mon Aug 7 15:27:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
node -v 
v6.11.2
code --version
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959

```

**Comment by joaomoreno** [comment]
#32381
