### ISSUE TITLE
'Reindent Lines' produces different indentation than 'Format Document' in TypeScript

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#32835]
- VSCode Version: Code **1.15.1** (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z), also in **1.16**
- OS Version: Windows_NT ia32 10.0.15063

Formatting via Format Document:

```tsx
const MyReactComponent = (props) => {
    return (
        <div>
            <Helmet titleTemplate='%s'>
                <title>Hello</title>
            </Helmet>
        </div>
    );
};
```

Formatting via Reindent Lines:

```tsx
const MyReactComponent = (props) => {
    return (
        <div>
        <Helmet titleTemplate='%s'>
        <title>Hello</title>
        </Helmet>
        </div>
    );
};
```

---

Another example; Format Document:

```ts
/**
 * Example
 */
function example() {
}
```

Reindent Lines:

```ts
/**
* Example
*/
function example() {   
}
```

Reindent Lines often gets it wrong, Format Document is much more reliable currently (but it does more than reindenting; I often want to just fix the indentation).

**Comment by borekb** [comment]
Oh, just found this issue: 'reindent all lines' removes leading space in comment #19142. This is probably a duplicate of it.

**Comment by borekb** [comment]
Another example:

Formatting via Format Document:

```tsx
const MyReactComponent = (props) => {
    return (
        <div>
            <Helmet titleTemplate='%s'>
                <title>Hello</title>
            </Helmet>
        </div>
    );
};
```

Formatting via Reindent Lines:

```tsx
const MyReactComponent = (props) => {
    return (
        <div>
        <Helmet titleTemplate='%s'>
        <title>Hello</title>
        </Helmet>
        </div>
    );
};
```

**Comment by borekb** [comment]
I've updated the original post, this React example shows the issue better.

**Comment by jonnysamps** [comment]
Please fix. Love VSCode but this drives me nuts.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/19140 which is talking about the same thing. For now, you can set `editor.autoIndent` to `false` to avoid indentation adjustment and probably turn on formatting for tying or saving.

**Comment by rebornix** [comment]
@borekb your feedback and reproduce steps will be considered even this issue is closed.
