### ISSUE TITLE
Unable to get Intellisense via JSDoc if referencing a type from other file

### ISSUE THREAD

**Issue by Gelio** [Microsoft/vscode#32831]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro 15063

_foo.js_:
``` javascript
export default class Foo {
  fooMethod() {
    console.log('Foo method called');
  }
}
```

_bar.js_:
``` javascript
/**
 * @param {Foo} foo 
 */
export default function bar(foo) {
  foo.
  // no Intellisense provided after the dot above
}
```

If I import Foo at the beginning of _bar.js_, like so:
``` javascript
import Foo from './foo';
```
then Intellisense works correctly. This is not ideal, though, as this `import` is not required for _bar.js_ and eslint will often complain that _Foo_ is not used.

Is there a way to get proper Intellisense without importing that module explicitly?

**Comment by mjbvz** [comment]
Yes, you currently need the import for intellisense to pick up the types properly. 

We are discussing a better approach here: https://github.com/Microsoft/TypeScript/issues/14377 The proposal would allow you to reference types across files directly in jsdoc comments

Closing as upstream
