### ISSUE TITLE
Customizable tabs in text editor: Multiple rows display, font size, grouping

### ISSUE THREAD

**Issue by pmunin** [Microsoft/vscode#32836]
Feature request

Users always have bunch of tabs opened that do not fit the width of the text editor. They can scroll it with a mouse wheel, but it's not very observant.

It would be really great if vscode could display those **tabs on a multi row wrap panel** (like visual studio does). And provide some customizable settings like font size of tabs and ability to pin tabs (=create groups) and display it separately.

- VSCode Version: 1.15.1
- OS Version: Windows

**Comment by dkniffin** [comment]
This issue is somewhat related to https://github.com/Microsoft/vscode/issues/15048 and https://github.com/Microsoft/vscode/issues/7987

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
