### ISSUE TITLE
Php is not working inside html tags

### ISSUE THREAD

**Issue by MENSAJERO27** [Microsoft/vscode#32832]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.can´t get php code inside html tags,
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@MENSAJERO27 Please provide sample code and repro steps

**Comment by MENSAJERO27** [comment]
![boceto](https://user-images.githubusercontent.com/4429943/29489861-b88bf7b4-84e7-11e7-9681-74d24381df5c.png)
No suggestion code inside html tags

**Comment by jens1o** [comment]
@MENSAJERO27 That's currently not possible, because the language server protocol does not support nested languages. If you want support in the current state, you would need to teach the php language server what html is, and thus what is css and js and so on...

**Comment by ramya-rao-a** [comment]
So the issue here is that php inside html is not getting the syntax highlighting done?

**Comment by generateui** [comment]
The issue here is vscode relies on "Language server"s to perform syntax highlighting. The html language server, which is used here because you open an html file, does not understand php. The php block in the html file is interpreted by vscode as html (as vscode does so for the whole file), and send to the html language server.

**Comment by ramya-rao-a** [comment]
Ah! And also the request for php suggestions inside html. Didn't notice that earlier.

Well, I'll leave it to @aeschli and @roblourens to respond

**Comment by roblourens** [comment]
Is it a .php file? Does it say PHP in the lower right corner?

**Comment by ugurozturk** [comment]
@MENSAJERO27 it works. Be sure Language mode to PHP 
![asd](https://user-images.githubusercontent.com/7994408/29494008-42a3f4de-85aa-11e7-8cee-453736f04d50.PNG)

**Comment by jens1o** [comment]
But then he loses the suggestions from intellisense for html, doesn't he?

**Comment by MENSAJERO27** [comment]
That's right

**Comment by MENSAJERO27** [comment]
Sorry. I solved the problem. You can see my problem in the picture
![boceto3](https://user-images.githubusercontent.com/4429943/29541468-74abf3ae-8691-11e7-8a74-421dbae47b08.png)

I had to choose the language mode php. Thanks for all.
