### ISSUE TITLE
Missing the tr tag, td tag, th tag. Emmet abbreviation

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#32839]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.1.7
autofilename|Jer|0.1.3
vscode-icons|rob|7.12.0
open-in-browser|tec|1.1.0

---
![vscode](https://user-images.githubusercontent.com/24318019/29491656-c9218394-8593-11e7-97e5-ddda45919a58.gif)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/0c079cb7df2e7f26fbed2ee97475ec9906be8e4b

The fix will be out in tomorrow's insiders
