### ISSUE TITLE
Mac OS Sierra - Space/Desktop problem pumping/bomb OS load - Improve organization and productivity.

### ISSUE THREAD

**Issue by MichelDiz** [Microsoft/vscode#32834]
similar issue https://bugs.chromium.org/p/chromium/issues/detail?id=74812
iterm2 possible solution https://github.com/gnachman/iTerm2/blob/master/sources/iTermWindowImpl.m
This iterm solution is a tip from that chromium issue above
PS. I use Iterm and have nothing to complain about it.

- VSCode Version: latest
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Open 3 projects. Separate it into 3 different spaces. Finalize the VS or restart the Mac. Using "window.restoreWindows": "all"
2. Reopen VS - all open right as before, but at the same space 0 (The current one).

The ideal would be re-open all three projects in the spaces as I determined. Thus improving productivity. And avoiding the stress of having to rearrange everything whenever you need to restart the MAC or even when there is a crash.

Best regards

Reproduces without extensions: doesn't matter for this.

**Comment by MichelDiz** [comment]
Does anyone have any position on this? Whether it is a priority, a problem or indifferent?

Thank you.

**Comment by bpasero** [comment]
There is another issue about this if you search for "spaces".
