### ISSUE TITLE
Paste in terminal doesn't work on macOS via ⌘+c -> ⌘+v

### ISSUE THREAD

**Issue by sumproxy** [Microsoft/vscode#32841]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crystal-lang|fau|0.3.1
vscode-emacs-friendly|lfs|0.8.0
Go|luk|0.6.63
RustyCode|sav|0.19.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start VSCode
2. Open integrated terminal
3. Copy some text from the terminal window with ⌘+c and try to paste it with ⌘+v

Reproduces without extensions: Yes

**Comment by sumproxy** [comment]
I found that the problem is due to key to "Paste into active terminal" command is unassigned as described [here](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf). So it will probably be an easy fix and suggests a simple workaround.

**Comment by Tyriar** [comment]
This should just work out of the box. Can you try this in the latest insiders build? https://code.visualstudio.com/insiders

**Comment by sumproxy** [comment]
@Tyriar tested it on the latest insiders and it works just fine!

**Comment by Tyriar** [comment]
Great 😃
