### ISSUE TITLE
problem with Extension Host

### ISSUE THREAD

**Issue by karlti** [Microsoft/vscode#32847]
always get error that Extension Host has to restart...

what can I do here?

Thanks,
/*Karl

- VSCode Version: Code - Insiders 1.16.0-insider (aebaece67321b35f133be393fe8adcd50333d5ee, 2017-08-18T05:22:55.860Z)
- OS Version: Windows_NT x64 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-svgviewer|css|1.4.2
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
python|don|0.7.0
CppSnippets|har|0.0.12
beautify|Hoo|1.1.1
haskell-linter|hoo|0.0.6
Ionide-fsharp|Ion|2.33.2
language-haskell|jus|2.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.63
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
PowerShell|ms-|1.4.1
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.2
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
stylish-haskell|vig|0.0.9

(15 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mubaidr** [comment]
This happened to me too, but is most probable cause by an malfunctioning extension. Mine was solved after update.

**Comment by karlti** [comment]
Thanks. after peeking into dev toolls, it looks like the "Ionide FSharp" extension caused that. after disabling that extension, noerror message came up any longer. 

anyway, extensionhost should not be so fragile in my opinion....

**Comment by karlti** [comment]
umhhh 
had to disable the "cpp snippets" extension too

**Comment by chriswiley** [comment]
I disabled all my extensions and still have the same error.

**Comment by alexandrudima** [comment]
We've removed the watchdog for now (see #26445)
