### ISSUE TITLE
no new line when pressing CTRL+C in terminal

### ISSUE THREAD

**Issue by atlanteh** [Microsoft/vscode#32846]
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1.  open integrated terminal
2.  run long running operation
3.  press ctrl + c
4.  `Terminate batch job (Y/N)?` Shows up
5.  press ctrl + c again

Expected to jump to a new cleared line, but actually just a ^C shows up:

`Terminate batch job (Y/N)? ^C`

Another variation of this issue is to just:
1.  open integrated terminal
2.  either enter some text or not.
3.  press ctrl + c

In a normal cmd this would jump to a new cleared line, but actually nothing happens

This happens only in windows and not in mac.
This happens both with cmd & powershell.

**Comment by rcjsuen** [comment]
I see this with PowerShell on 1.15.0 also but am pretty sure I have seen it on 1.14.x before. I am also on Windows 10.

**Comment by Tyriar** [comment]
Tracked in https://github.com/Tyriar/node-pty/issues/7
