### ISSUE TITLE
vscode首先有智能提示，没多久代码提示不见了

### ISSUE THREAD

**Issue by Salvador23** [Microsoft/vscode#32843]
我每次登陆VScode打开有提示代码，过几分钟后提示代码没反应，这是什么情况呀？

**Comment by aeschli** [comment]
Please run without extensions and see if this still happens (`code --disable-extensions`).
If this still happes, please give more details where VSCode frezzes. In which view or editor. Which file types do you open...

**Comment by Salvador23** [comment]
抱歉喔，我已经尝试过您使用方法和命令(code --disable-extensions),还是等没多久代码提示消失了呢，有什么办法解决不让代码提示不消失呢！ @aeschli

**Comment by alexandrudima** [comment]
I'm sorry, I do not understand.
