### ISSUE TITLE
Markdown `slugify` misses backticks

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#32844]
This pattern:

https://github.com/Microsoft/vscode/blob/40bd5d9859f9f2e33554cb5c3895978c50c6ae94/extensions/markdown/src/tableOfContentsProvider.ts#L75

should contain a backtick. It currently doesn't which for example breaks Ctrl+click navigation:

```md
Link to heading: [example](#hello-make)   <-- Ctrl+clicking should jump to heading but it doesn't

## Hello `make`
```

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063

**Comment by mjbvz** [comment]
Fixed by #32987
