### ISSUE TITLE
Java Debugger issue

### ISSUE THREAD

**Issue by Pandeyjidev** [Microsoft/vscode#32848]
- VSCode Version: 1.14.2
- OS Version:  Windows 10 

Steps to Reproduce:

1. Install Java Debug
2. Create a new file with just a print statement
3. Create a launch.json file 
    {
    "name": "Java",
    "type": "java",
    "request": "launch",
    "stopOnEntry": true,
    "preLaunchTask": "build",                 // Runs the task created above before running this configuration
    "jdkPath": "${env:JAVA_HOME}/bin",        // You need to set JAVA_HOME enviroment variable
    "cwd": "${workspaceRoot}",
    "startupClass": "my.package.MyMainClass", // The class you want to run
    "sourcePath": ["${workspaceRoot}/src"],   // Indicates where your source (.java) files are
    "classpath": ["${workspaceRoot}/bin"],    // Indicates the location of your .class files
    "options": [],                             // Additional options to pass to the java executable
    "args": []                                // Command line arguments to pass to the startup class
}
4. Run Code 
    ERROR 
    Error occurred during initialization of VM
    Unable to load native library: The specified procedure could not be found

I'm new to this so kindly help. My environment variable named JAVA_HOME has C:\Program Files\Java\jdk1.8.0_121

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@Pandeyjidev Did you install [this extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.javadebugger)?

If yes, I suggest you open an issue in the [DonJayamanne/javaVSCode repository](https://github.com/DonJayamanne/javaVSCode/issues) instead.

**Comment by weinand** [comment]
You can move this issue to the correct repo with this tool: https://github-issue-mover.appspot.com
