### ISSUE TITLE
Show Debug Console icon is broken in High Contrast theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3284]
![image](https://cloud.githubusercontent.com/assets/22350/13248141/1a891d2e-da1d-11e5-9847-d5f1f81eb186.png)

ping @isidorn

**Comment by isidorn** [comment]
Just pushed a fix

**Comment by joaomoreno** [comment]
I'd prefer if we focused on testing today...

**Comment by isidorn** [comment]
It's the endgame police 👮
