### ISSUE TITLE
lost icon

### ISSUE THREAD

**Issue by wclssdn** [Microsoft/vscode#32851]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
debugger-for-chrome|msj|3.1.8
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. install it
2. lost icon very soon

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@wclssdn which icon?

**Comment by wclssdn** [comment]
the application on desktop、task bar。
I had reinstall vscode，now it‘s good。。。
I think some plugins is the reason。
