### ISSUE TITLE
API: (built-in Markdown extension) interface `TocEntry` should have `level` as an attribute

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#32859]
Currently, we have this interface [vscode/extensions/markdown/src/tableOfContentsProvider.ts L12](https://github.com/Microsoft/vscode/blob/7e539de2f4a8872909a748cfe59f0dd1ea1ce0fc/extensions/markdown/src/tableOfContentsProvider.ts#L12)

```typescript
export interface TocEntry {
	slug: string;
	text: string;
	line: number;
	location: vscode.Location;
}
```

If we call `tocProvider.getToc()` on this example document

```markdown
Setext Heading 1
===

Setext Heading 2
---

<http://spec.commonmark.org/0.28/#setext-heading>

# ATX Heading
```

We get this result

![image](https://user-images.githubusercontent.com/7588612/29499664-3f178868-8649-11e7-9101-60d37a9aa576.png)

The information about (setext) heading level is missing.

**Comment by mjbvz** [comment]
What does this effect? The table of contents provider is internal to the markdown extension and we don't need `level` anywhere currently

**Comment by neilsustc** [comment]
The problem is about **Setext syntax heading**. A line followed by `===` is a H1, followed by `---` is H2.

![image](https://user-images.githubusercontent.com/7588612/29589700-ca071cce-87c8-11e7-877e-dcf12aa386b5.png)

 As announced in [May 2017#markdown-symbol-search-includes-heading-levels](https://code.visualstudio.com/updates/v1_13#_markdown-symbol-search-includes-heading-levels), headings with `#` syntax work well. But we cannot see the heading levels of headings defined by `===` and `---` when search symbol using <kbd>ctrl+shift+o</kbd>

![image](https://user-images.githubusercontent.com/7588612/29589681-b69979a2-87c8-11e7-839a-18760f2b1cc6.png)

**Comment by mjbvz** [comment]
Ok, thanks for the additional info. I've marked this as a `bug` and as `help wanted` if anyone wants to take a look

**Comment by neilsustc** [comment]
Of course I can make a PR. I just want to make sure it makes sense.

**Comment by neilsustc** [comment]
Here #32987
