### ISSUE TITLE
Copy line keyboard shortcut for Ubuntu

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#32855]
- VSCode Version: 1.15.1
- OS Version: Ubuntu 17.04

In Ubuntu `add cursor above/below` can be done with both <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Up/Down</kbd> and with <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Up/Down</kbd>. 
Instead of using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd> to `copy line up/down`, <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Up/Down</kbd> should be assigned for it as <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd> and <kbd>Ctrl</kbd>+<kbd>Alt</kbd> are already mapped in Ubuntu's Unity and in GNOME, and <kbd>Shift</kbd>+<kbd>Alt</kbd> is already being used for copying line up/down in Windows.

**Comment by christianbueno1** [comment]
on ubuntu 17.10 gnome and fedora 27 workstation(gnome) , ctrl+alt+shift+up/down doesn't work although those aren't system short-cuts , those short-cuts move the focused windows to a workspace below or above althought the real shortcuts are Super+shift+page-up/page-down.
On fedora 27 kde-plasma ctrl+alt+shift+up/down works well.
