### ISSUE TITLE
Test: Electron Update 1.7.5

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#32858]
Refs: #28582

**OS**
- [x] Windows @rebornix 
- [x] OS X @jrieken 
- [x] Linux @aeschli 

Complexity: 4

We have updated Electron to version `1.7.3` and thereby jumped 2 Chrome releases (from `56` to `58`) and 5 minor node.js release (from `7.4.0` to `7.9.0`) and many other dependency updates. This test item asks for exploratory testing focusing on native integration where possible:

- Drag and drop
- Menus and context menus
- Window management and multiple windows
- UI regressions
- Accessibility regressions

**Comment by weinand** [comment]
@Tyriar could you please update the information (since we rolled back to 1.7.3 plus patch).

**Comment by Tyriar** [comment]
@weinand done 👍
