### ISSUE TITLE
Text gets selected, to the next line, when the menu bar auto hides

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#32853]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.1.16
python|don|0.7.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
blank-line-organizer|rin|0.1.2
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Set your menu bar to auto hide (i.e. set it to toggle).
2. Press Alt to show the menu bar.
3. Click somewhere near the beginning of a line of text in your currently visible text document.
4. As the menu bar disappears, notice that the text gets selected, started from the position where you clicked and ending on the line below where you clicked.

Expected:
Nothing should get selected when the menu bar auto hides. The cursor should simply be wherever you clicked.

Reproduces without extensions: Yes/No

**Comment by sbatten** [comment]
This issue is resolved when setting `window.titleBarStyle` to `custom` which should be the default this milestone on Windows.

**Comment by bpasero** [comment]
Happened.
