### ISSUE TITLE
Diff editor is not High Constrast theme aware

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3286]
Testing #3248

![image](https://cloud.githubusercontent.com/assets/22350/13248188/541bd2ac-da1d-11e5-9452-ded715c02b2e.png)

It's very hard to distinguish insertions, deletions and modifications. We should somehow use the same colour code (red, green, etc), but in higher contrast.

**Comment by bgashler1** [comment]
Duplicate #3291
