### ISSUE TITLE
Dragging on tab bar with side-by-side split can select text in an unusual way 

### ISSUE THREAD

**Issue by RoryDungan** [Microsoft/vscode#32863]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
spellcheck|Jul|1.1.4
vscode-icons|rob|7.12.0
vim|vsc|0.9.0

---

Steps to Reproduce:

1. Create a vertical split with two documents open side-by-side
2. Move the cursor to the right of the area in the tab bar where the splits can be dragged to rearrange. While over the area used for rearranging splits, the cursor will change to a hand, and when over the buttons to the right the cursor will change to a pointer. However, there is a 2 pixel wide space in-between where the cursor will be a standard pointer.
3. Click and drag from this point across to the left sidebar or the status bar.
4. Text in the editor will become highlighted but in a bright blue colour different to the normal selection colour. If the find results window is open, text in that will be included in the selection.
5. Copy with the current selection. If the text in the left pane was highlighted, the titles of the tabs on the right pane will also be copied to the clipboard, and the "no results" or "x of x" text in the find results window will also be copied to the clipboard.  

Was not expecting to be able to select text from clicking outside the editor window and text was highlighted with a colour inconsistent with the selected theme. Although not visibly highlighted, text that formed part of the UI as opposed to the current buffer was selected and could be copied.

Reproduces without extensions: Yes

edit: added screenshot to better illustrate what happens. Annotations in red
![vscode](https://user-images.githubusercontent.com/8509978/29503730-be8c0cac-867d-11e7-9b49-252f1926de00.png)

**Comment by isidorn** [comment]
Please try treproducing this with latest vscode insiders
https://code.visualstudio.com/insiders/
