### ISSUE TITLE
Show the current function/method name in the toolbar

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#32869]
Like the "flagsChanged" part of the bottom toolbar in [this](https://camo.githubusercontent.com/a36aa85ba9cd3600fb7db5cd5cf2b306acd55a47/68747470733a2f2f7261772e6769746875622e636f6d2f746578746d6174652f746578746d6174652f67682d70616765732f696d616765732f73637265656e73686f742e706e67) screenshot of TextMate 2.

I don't see any indication of which function/method I'm in, which is handy if it's so long its name is scrolled up out of view.

**Comment by aeschli** [comment]
Sounds like a nice idea for an extension...

**Comment by willfaught** [comment]
Are the current line and column numbers from an extension too?

**Comment by Gruntfuggly** [comment]
Try this extension:
https://marketplace.visualstudio.com/items?itemName=amos402.scope-bar

**Comment by willfaught** [comment]
That seems to work fine, thanks!

But I think this should still be built-in. "Code" is in the app name; it's just a basic part of navigating code. Isn't it in Visual Studio (not Code)?

**Comment by bpasero** [comment]
Closing in favour of the mentioned extensions.
