### ISSUE TITLE
nuxt debug by npm 1.15.1 connect ECONNREFUSED

### ISSUE THREAD

**Issue by lazyhero** [Microsoft/vscode#32866]
- VSCode Version:1.15.1
- OS Version: 10.12.4
- Node Version:8.3.0
i learned debug nuxt from the article.But it don't work in 1.15.1 & node 8.3
[debugging-nuxt-js-with-visual-studio-code](https://medium.com/@marshallswain/debugging-nuxt-js-with-visual-studio-code-724920140b8f)
```
package.json
"dev-debug": "node --debug node_modules/.bin/nuxt",

launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "npm run dev",
      "runtimeExecutable": "npm",
      "windows": {
        "runtimeExecutable": "npm.cmd"
      },
      "runtimeArgs": [
        "run",
        "dev-debug"
      ],
      "port": 5858
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/start"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Port",
      "address": "localhost",
      "port": 5858
    }
  ]
}
```
i change '--debug' to '-- inspect' or 
```
"protocol": "debug"
to
"protocol":"inspector"
```
i have try use 'legacy' but still wrong
![image](https://user-images.githubusercontent.com/9362926/29505502-58a6cdd6-8679-11e7-9377-b1103ffb9ea6.png)

[vscode-debug-offical-documents](https://code.visualstudio.com/docs/nodejs/nodejs-debugging)

Reproduces without extensions: Yes/No

**Comment by lazyhero** [comment]
ps:
if use "protocol": "legacy" it can run but debug fail
![image](https://user-images.githubusercontent.com/9362926/29505617-eb49e998-8679-11e7-9ae4-c14113a158de.png)

**Comment by lazyhero** [comment]
@weinand 
I have read all the relevant issues.
But...vscode1.15+node8.3+inspector+'Launch via NPM' = connect ECONNREFUSED

**Comment by weinand** [comment]
If you are using recent versions of node (e.g. 8.x), you must configure both the npm script and VS Code to use the "inspector" protocol (and use the correct port 9229).

A good way to do this is by relying on the defaults (and do not specify a debug port at all).

Change the "dev-debug" script in your package.json to:
```
   "dev-debug": "node --inspect node_modules/.bin/nuxt",
```

And the launch configure to this:
```
{
      "type": "node",
      "request": "launch",
      "name": "npm run dev",
      "protocol": "inspector,
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run",
        "dev-debug"
      ]
}
```

Since both are configured for the inspector protocol they will use the correct port 9229 automatically.

An even easier way to launch nuxt in debug mode is to do everything in the launch config, so there is no need to touch the package.json at all
```
{
      "type": "node",
      "request": "launch",
      "name": "launch nuxt",
      "protocol": "inspector,
      "program": "${workspaceRoot}/node_modules/.bin/nuxt"
}
```

**Comment by lazyhero** [comment]
@weinand Thank you so much for your help.According to your tips.It work!
![image](https://user-images.githubusercontent.com/9362926/29526575-bdfad7be-86c8-11e7-8bc2-69976b693afa.png)
I should learn more about vscode and node.
Thank agin~:-D
