### ISSUE TITLE
Vscode can not run and can only be reopened

### ISSUE THREAD

**Issue by qifanrui** [Microsoft/vscode#32861]
- VSCode Version:1.15.1
- OS Version: macOS Sierra 10.12.5
- Android studio Version: 2.3.3

Steps to Reproduce:

1.Open the ionic project
2.Open android studio and perform compilation

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@qifanrui more details please on what is not running?

**Comment by qifanrui** [comment]
It will be stuck, and then prompted to re-open the window

**Comment by qifanrui** [comment]
Now I really want to find the reason, my android studio installed weex plugin, I suspect that it is caused by it, I should be uninstalled for him, until now there is no problem.

**Comment by bpasero** [comment]
@qifanrui can you share a video or screenshots?
