### ISSUE TITLE
Feature Request: Have the Code 64-bit installer migrate settings/extensions from 32-bit installation

### ISSUE THREAD

**Issue by jamesqo** [Microsoft/vscode#32862]
I was excited when I heard about the new 64-bit edition of Code for Windows, but when I opened the installer it said I had to manually uninstall the 32-bit version first. I already have a couple of extensions installed, so I'm hesitant to install them all again on the new edition. It would be great if the 64-bit installer automatically trasnsferred all of your extensions/settings from the 32-bit Code (and handled the uninstallation for you, too).

**Comment by joaomoreno** [comment]
The extensions are shared between them.
