### ISSUE TITLE
VS code is super slow 

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#32868]
- VSCode Version: Code 1.15.1
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.4
crane|Hvy|0.3.8
autofilename|Jer|0.1.3
format-php|Kas|1.1.2
vscode-simple-icons|Lau|1.5.3
material-icon-theme|PKi|2.1.0
html-css-class-completion|Zig|1.8.1
vscode-file-peek|abi|1.0.1
Bookmarks|ale|0.15.2
vscode-custom-css|be5|2.5.0
vscode-intelephense-client|bme|0.7.2
htmltagwrap|bra|0.0.3
php-autocomplete|bsc|0.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.2.3
jquerysnippets|don|0.0.1
tslint|eg2|0.17.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
angular2-switcher|inf|0.1.4
code-beautifier|mic|1.7.2
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.12.3
debugger-for-chrome|msj|3.1.8
php-docblocker|nei|1.2.0
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
ci-snippets|sec|0.0.2
stylelint|shi|0.28.0
php-ci|sma|0.2.2
autoimport|ste|1.2.2
ayu|tea|0.5.0
open-in-browser|tec|1.1.0
highlight-matching-tag|vin|0.4.4
gitblame|wad|2.1.0
bootstrap-3-snippets|wcw|0.1.0

(20 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by prasanthnv** [comment]
Vs code hangs while opening larger projects like angular one...and some times it shows an this error

> Extension host terminated unexpectedly. Please reload the window to recover.

it's very annoying and need to restart over and over

**Comment by aeschli** [comment]
Please disable all extensions and see if this still happens.
#18774 has more information on how to track this down.
