### ISSUE TITLE
Integrated terminal cursor style changes after certain commands

### ISSUE THREAD

**Issue by nvdv** [Microsoft/vscode#32870]
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6

I've set `"terminal.integrated.cursorStyle": "line"` in User Settings, but when I launch `vim` inside Integrated terminal cursor style changes to `"block"`.

Steps to Reproduce:

1. Set `"terminal.integrated.cursorStyle": "line"` in User Settings.
2. Launch and quit `vim`.
3. Observe cursor change.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
The terminal supports setting of the cursor via escape sequences which I assume vim is doing for you. Do you have the cursor style set in your .vimrc or something? I can't reproduce locally.

**Comment by nvdv** [comment]
Seems that cursor was changed by a `vim` setting, so I disabled it. 
Thanks! 😄
