### ISSUE TITLE
Add intellisense support for C++

### ISSUE THREAD

**Issue by nabeelomer** [Microsoft/vscode#3287]

**Comment by alefragnani** [comment]
There are two extensions already:

* [C++ Instelisense](https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global)
* [C/C++ Clang](https://marketplace.visualstudio.com/items?itemName=mitaki28.vscode-clang)

Hope this helps

**Comment by egamma** [comment]
Thanks @alefragnani - closing
