### ISSUE TITLE
Terminal breaks badly on window resize

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#32878]
Ubuntu

- Open tmux (or any terminal app which takes mouse control)
- Resize Code's window

![image](https://user-images.githubusercontent.com/22350/29516511-e2b29a4a-8670-11e7-89b3-8acaf59ae5f0.png)

Didn't see this last week at all, started happening today only, so it's probably due to a change delivered since Friday. I wonder if it's related to the <kbd>Shift</kbd> select changes?

**Comment by Tyriar** [comment]
Hmm, I can't repro after `tmux` and resizing both dimensions of the window rapidly. Could you try update to latest and try again? I pushed a massive update to xterm.js yesterday but it didn't appear to be published to the apt repo.

**Comment by joaomoreno** [comment]
Same happens on macOS in 9c5d505c995c73bfa8daf8c537eba6d3450eeca3. 😢

**Comment by joaomoreno** [comment]
Running out of `master`:

1. Open terminal
2. `htop`
3. Resize terminal

![image](https://user-images.githubusercontent.com/22350/29538830-c0e5019e-86c7-11e7-8851-9d82a031afd7.png)

**Comment by Tyriar** [comment]
I can repro on mac 👍

**Comment by joaomoreno** [comment]
Oh it doesn't repro on today's insiders. :confused:

**Comment by Tyriar** [comment]
:confused: 

Weird, I'll still have a look when I get a chance.

**Comment by joaomoreno** [comment]
What. Seems to have returned today!

I know @sandy081 hits it too.

**Comment by sandy081** [comment]
Yeah, I saw it yesterday and today (after update) I can't reproduce.

**Comment by joaomoreno** [comment]
@Tyriar Let me know if I can help somehow. This morning it was broken for a while... and somehow it was fixed when I alt-tabbed into it. So weird.

I'm forced to go back to an external terminal. :cry:

**Comment by sandy081** [comment]
I see the issue again in today's insiders. It is random.

**Comment by Tyriar** [comment]
I spent an hour or 2 on it yesterday and struggled to reproduce.

Something that would help diagnose: If you happen to reproduce it (ideally out of sources), break where it's throwing which is here:

https://github.com/sourcelair/xterm.js/blob/bfdc468d4bc823b242ada286c7e8ecc7978f2b72/src/Renderer.ts#L142-L145

It would be good to see what the following values are:

- `y`
- `this._terminal.buffer.ydisp`
- `this._terminal.buffer.ybase`
- `row`
- `this._terminal.buffer.lines.length`

**Comment by Tyriar** [comment]
I think I found the problem - PR out in https://github.com/sourcelair/xterm.js/pull/923

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/924
