### ISSUE TITLE
CTRL+P not finding node.js module files?

### ISSUE THREAD

**Issue by JerryGoyal** [Microsoft/vscode#32876]
Steps to Reproduce:

1. add a node.js project folder i.e. https://github.com/Azure-Samples/raspberry-pi-web-simulator
2. install a new module to node js project. In my case, I installed "npm install file-system"
3.  verify it by navigating to "raspberry-pi-web-simulator-source\node_modules\file-system\file-system.js" in VS Explorer.
4. Search for file-system.js using CTRL+P.
Current result: No file found
Expected result: file-system.js

I guess VS only search for recently open files, not all project files but not sure of the intention.

- VSCode Version: 1.15.1

- OS Version: Windows 10

**Comment by mjbvz** [comment]
We explicitly exclude files in `node_modules` from search and quick open. Try setting:

```json
  "search.exclude": {
    "**/node_modules": false
}
```

in your user settings to disable this
