### ISSUE TITLE
Hard-coded debug hover regexp is not suitable for OCaml language

### ISSUE THREAD

**Issue by db4** [Microsoft/vscode#32873]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
---
Current debug hover implementation uses hard-coded regexp to extract evaluated expression: (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L139)

```
// If there are non-word characters after the cursor, we want to truncate the expression then.
// For example in expression 'a.b.c.d', if the focus was under 'b', 'a.b' would be evaluated.
if (matchingExpression) {
	let subExpression: RegExp = /\w+/g;
```

For most programming languages this works ok, but not for OCaml whose identifiers can contain apostrophes: 
```
lowercase-ident ::= | (a … z ∣  _) { letter ∣  0 … 9 ∣  _ ∣  ' }
letter ::= | A … Z ∣  a … z
```

So when I debug an OCaml program using [vscode-ocaml extension](https://github.com/hackwaly/vscode-ocaml) and hover over `a'` variable, VS code tries to evaluate `a` instead (see https://github.com/hackwaly/vscode-ocaml/issues/110)

Can this regexp be made configurable so that an extension could change it if necessary?

**Comment by isidorn** [comment]
@db4 thanks for the nice analysis however it is currently not possible to configure this regex from the extension.
In a perfect world every debug adapter would somehow contribute what it considers expressions and based on that the hover would match. However we are not there yet thus keeping this open as a feature request

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
