### ISSUE TITLE
ctrl+shift+b - running default build task does not work when focused on TS script

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode#32875]
With VSC 1.15.1 (64 bit) triggering default build task does not work when I'm focused (open) TS file.
When focused on other type of files (HTML / JSON etc) - works fine.

When focused on TS file it opens list of tsc build tasks based on tsconfig file instead.

**Comment by dbaeumer** [comment]
This got fixed for the next VS code release. Problem was a wrong generation of the TS tasks.

**Comment by pankleks** [comment]
ok thanks!
