### ISSUE TITLE
Output view always moves to front

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#32872]
- install the Java Extension
- enable `"java.trace.server": "verbose"` is settings
- open a folder with Java with some errors
- try to look at the errors in the problems view
- the output view gets in the focus again as some message was printed
-> this makes it almost impossible to use the problems view

**Comment by aboe026** [comment]
Other extensions that also have this problem had to make changes to their own API (https://github.com/Microsoft/vscode/issues/31474). This change might need to be made in `redhat-developer/vscode-java` instead of the main project

**Comment by aeschli** [comment]
Thanks, didn't know this. @dbaeumer Would be great to avoid this for the LS-clients.

**Comment by dbaeumer** [comment]
Fixed in the LSP client.

**Comment by bawachhe** [comment]
It would be nice for us laymen (and for plugin developers researching this issue) to link your changes.

https://github.com/Microsoft/vscode-languageserver-node/commit/da70c14abde61a00c015100ab2e1405efa10917f
