### ISSUE TITLE
Launch.json/tasks.json only work if in first folder in multi-folder workspace

### ISSUE THREAD

**Issue by kobenauf** [Microsoft/vscode#32885]
- VSCode Version: 1.16.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Add a task or launch type.  
2. It adds it only to the first project (folder) even though you might want it in other projects.
3. Tasks/debug only work when launch.json/tasks.json are in the first folder.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
To add a launch config to a specific folder use the corresponding "Add Config" menu in the launch config drop down menu:

![2017-08-22_10-56-19](https://user-images.githubusercontent.com/1898161/29557204-90d5c2ca-8728-11e7-85e9-02daebcb0c44.png)

In addition the launch config drop down menu shows all launch configs from all folders of a multifolder workspace.

**Comment by dbaeumer** [comment]
Tasks have not been adopted to multi folder so far. This will happen in one of the next milestones.

**Comment by dbaeumer** [comment]
This got fixed for 1.17.
