### ISSUE TITLE
Code should prefer full match on intellisense

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#32886]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
code-spell-checker|str|1.3.6

(1 theme extensions excluded)

---

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1658949/29523208-8c40a500-868c-11e7-87d0-43a21316f542.png)

In the completion pictured above, there are 2 valid members:
- `body`
- `bodyUsed`

When I type `body`, I feel like that should be the highlighted match.

**Comment by jrieken** [comment]
We have actually made that change a while ago.
