### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by nprithviraj24** [Microsoft/vscode#32883]
- VSCode Version: 1.15.1
- OS Version: Windows 10

The following picture will tell you the extensions that are installed.

Steps to Reproduce:
No Steps to reproduce.
![vsprob](https://user-images.githubusercontent.com/13771513/29518556-79d96c84-8697-11e7-87b4-623d6215f7a4.JPG)

Reproduces without extensions: Yes/No

**Comment by tommck** [comment]
I've been having this issue for the last 2 builds

**Comment by smlombardi** [comment]
Same on OSX, although I got a much longer error message:

<img width="1053" alt="screen shot 2017-08-21 at 11 32 28 am" src="https://user-images.githubusercontent.com/835148/29526728-926044c2-8664-11e7-9010-52894c2206f9.png">

**Comment by tommck** [comment]
I might have tracked this down to the "vscode-tslint(vnext) PREVIEW" extension.  If I disable that extension, this problem goes away for me

**Comment by alexandrudima** [comment]
We've removed the watchdog for now (see #26445)
