### ISSUE TITLE
Duplicated expanded emmet abbreviation if for script tag

### ISSUE THREAD

**Issue by NickolasKyrylyuk** [Microsoft/vscode#32881]
- VsCode Version :1.15.1:
- OS Version: Windows 10 pro 64bit

Steps to Reproduce:

1. Type script in html
2. You will see duplicate of emmet expanded abbreviation

Reproduces without extensions: Yes

If you will try to type script tag in html you will see two exactly same abbreviations ( autocomplete variants )
![emmet-main](https://user-images.githubusercontent.com/30705537/29517892-d776d25e-867f-11e7-8664-1a3092ece9c5.gif)

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-emmet-helper/commit/8bdeaa14fdbab272be622ab12dd7d08677b0b6ef
