### ISSUE TITLE
cannot open folder on my drive

### ISSUE THREAD

**Issue by ltroamer** [Microsoft/vscode#32899]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
Go|luk|0.6.63
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1. open VSCode
2. FIle -> Open Folder -> Choose folder from C:\

Reproduces without extensions: Yes

**Comment by ddelrio1986** [comment]
I am having this problem too. Brand new installation of VS Code. When I select one specific folder it does not show in the explorer. All other folders work just fine. This folder is:

~/workspaces/hd-zendesk-theme

**Comment by bpasero** [comment]
#27285
