### ISSUE TITLE
[git] Improve `stash pop` label

### ISSUE THREAD

**Issue by qpegg** [Microsoft/vscode#32891]
VSCode Version: 1.16.0-insider (0626479859787fa87c7c57ba19195b939050a843)

I found a difficult  phrase to translate when translating.

[`Stash pop`](https://github.com/Microsoft/vscode/blob/bbe70bc9b930b0cd63d1b40720e516525db22e99/extensions/git/package.nls.json#L41) is the git command name and does not represent the action. Also, this command has 2 meaning; apply stash, remove it.  

So, it is difficult to translate correctly including these.  

Please change to an alternative label. 

Suggestions: 
Apply Stashed Changes And Delete - stash pop
(Apply Latest  Stashed Changes And Delete) - stash pop latest

**Comment by joaomoreno** [comment]
I just realized that they are even wrong in English. I'll change them to `VERB NOUN`:

- Pop Stash
- Pop Latest Stash

I would refrain from using a longer description of the action such as _Apply Stashed Changes And Delete_, I fear this will confuse people. Can you work with _pop_ as a verb?

**Comment by qpegg** [comment]
Thanks. I think that it is simple and will function as a verb.

By the way,  if you are requested to implement `git stash apply` command, will you change this label and able to select this interactively? (like other git clients)   Or, will you add the `Apply stash` label to the UI?

**Comment by qpegg** [comment]
This is necessary the additional information to me when translating.

**Comment by joaomoreno** [comment]
I will likely add the `Apply Stash` and `Apply Latest Stash` labels.

**Comment by phcoliveira** [comment]
Retrieve Stash?
Retrieve Latest Stash?
