### ISSUE TITLE
Output area garbled text

### ISSUE THREAD

**Issue by SunBrook** [Microsoft/vscode#32893]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.7.0
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
csharp|ms-|1.12.1
vscode-icons|rob|7.12.0

---

Steps to Reproduce:
���� .NET Core �� Microsoft (R) ��������汾 15.3.409.57025
��Ȩ����(C) Microsoft Corporation����������Ȩ����

  CSharpNote -> e:\CSharpNote\bin\Debug\netcoreapp2.0\CSharpNote.dll

�ѳɹ����ɡ�
    0 ������
    0 ������

����ʱ�� 00:00:00.79

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1728
