### ISSUE TITLE
Add type import declaration keyboard shortcut

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#32892]
![image](https://user-images.githubusercontent.com/736697/29526943-ba47ba3c-86b0-11e7-8f1e-6b404d661ff6.png)

Can't find out is it possible to set a keyboard shortcut for this? It would be very convenient.

**Comment by mjbvz** [comment]
Thanks. I don't think this is currently possible. I've opened #33049 to track a generic approach to binding specific code actions / quick fixes to keyboard shortcuts
