### ISSUE TITLE
nls support for package.json does not work in all cases

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#3289]
On testing #3156:

I've nls'ed the Mono Debug extension including the `displayName` and `description attributes. When publishing the extension to the marketplace, non-substituted strings show up in a few places:

![2016-02-19 19-00-31](https://cloud.githubusercontent.com/assets/1898161/13248302/cf39efd2-da1d-11e5-937c-f93b5654bff8.png)

and on the Marketplace:

![2016-02-19 19-03-52](https://cloud.githubusercontent.com/assets/1898161/13248335/f75210bc-da1d-11e5-857d-20a286110160.png)

**Comment by egamma** [comment]
This needs discussion/coordination with the marketplace team on their approach for localization. 

I suggest that for February we do not externalize the strings `extension.displayName` and `extension.description` in the package.json.

**Comment by weinand** [comment]
@egamma yes, that's what I'm doing for Mono Debug.

**Comment by dbaeumer** [comment]
I think there is still no market place support for NLS.

**Comment by dbaeumer** [comment]
Dups #54111. Closing this one since the other has more comments and information.
