### ISSUE TITLE
Setting to disable find's auto-selection

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#32901]
Thing that really annoys me:

- An editor is focused with **nothing selected**
- I hit Ctrl-F
- Whatever is under the cursor is selected and put into Find

Thing that I like:

- An editor is focused and **something is selected**
- I hit Ctrl-F
- Whatever is selected is put into find

**Please add a setting to disable the former.**

I like `editor.find.seedSearchStringFromSelection`. I simply don't want the editor to make a selection where none existed previously.

**Comment by rebornix** [comment]
This no longer exists in latest version ;)

**Comment by hamidnazari** [comment]
I'm on `1.19.0` and this behaviour still exists... what version are you referring to @rebornix?
