### ISSUE TITLE
Bad action label when having bad debug configuration

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3290]
![image](https://cloud.githubusercontent.com/assets/22350/13248340/03c8ffa4-da1e-11e5-834c-f90f50789892.png)

Shouldn't the action label be more like `Edit Configuration` instead of `launch.json`?

**Comment by isidorn** [comment]
@weinand and me were discussing this and came to the conlcussion to use launch.json here to make it very clear to the user what will open. I agree Edit Configuration would look nicer
@weinand opinions?

**Comment by isidorn** [comment]
After discussing with Andre we agreed on 'Open launch.json' since that is readable and makes it clear to the user what is going  to happen.

**Comment by joaomoreno** [comment]
Make sure you extract `launch.json` from the localize call.
