### ISSUE TITLE
Can emmet tsx/jsx be a little smarter?

### ISSUE THREAD

**Issue by richrout** [Microsoft/vscode#32906]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a typescript extending `React.Component` class with props
2. Start typing `this.props` or `this.state` in any method in your class and see emmet intellisense get all optimistic
![image](https://user-images.githubusercontent.com/2003142/29534777-7bcbe76a-8674-11e7-85e4-f4137a0431f2.png)

I'm mostly just wondering if it emmet can be a little smarter about when it makes it's suggestions? I really want to use it, but right now it's getting in my way 80% of the time.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Sorry for the trouble.

This is being tracked here: #32647

**Comment by ramya-rao-a** [comment]
@richrout This is fixed in the latest Insiders.

**Comment by richrout** [comment]
Awesome. I'll give it a try next week. Thanks for the update.

**Comment by richrout** [comment]
@ramya-rao-a - just got the latest update. After a quick try it's exactly what I wanted. Thanks 🥇

**Comment by ramya-rao-a** [comment]
@richrout Great! Feel free to log an issue if you find any other inconsistencies
