### ISSUE TITLE
Feature: search up the directory hierarchy for .vscode settings

### ISSUE THREAD

**Issue by ide** [Microsoft/vscode#32907]
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a workspace with a .vscode settings directory
2. Open a subdirectory in the workspace with VS Code
3. VS Code doesn't apply the parent directory's settings

Reproduces without extensions: Yes

The purpose of this feature is to let people open a project directory within a larger workspace (which contains multiple projects) and still retain the team's workspace-level VS Code settings. Put more abstractly: when I open a subdirectory in a workspace, I want VS Code to recognize I am in that workspace.

**Comment by sandy081** [comment]
Duplicate of #32693
