### ISSUE TITLE
Suggestion configure encoding by file type

### ISSUE THREAD

**Issue by JeffersonxD** [Microsoft/vscode#32903]
- VSCode Version: 1.15.1
- OS Version: Win10

Steps to Reproduce:

1.  Bug encoding file csharp and javascript, I always have to adjust manually.

I have a great difficulty when I need to work with .js and .cs files, Ideally, separate the encoding settings.

"[csharp]": {
  "files.encoding": "windows1252"
},
"[javascript]": {
  "files.encoding": "utf8"    
}

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/19890
