### ISSUE TITLE
Allow for case insensitive comparison

### ISSUE THREAD

**Issue by tip2tail** [Microsoft/vscode#32905]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5

---

Issue is that the ````vscode.diff```` tool does not allow a case-insensitive diff.  The programming language I work with is case insensitive.  As such when I compare two programs I get a lot of false positives in the diff due to text case.

I have been using the extension found: https://github.com/ryu1kn/vscode-partial-diff.

However when I raised an issue there I was advised this simply made use of ````vscode.diff```` hence my raising this issue:  https://github.com/ryu1kn/vscode-partial-diff/issues/10

t2t

Reproduces without extensions: Yes

**Comment by IamMille** [comment]
It's been a couple of years now. This still seems not possible?

VS Code has evolved much since. Would it perhaps be a lower effort to implement this from today's standpoint? Could it be considered?

**Comment by iwissemben** [comment]
would be useful indeed

**Comment by jtencer** [comment]
I would also benefit from this.  @iwissemben do you know if there's a duplicate issue open that they're likely to look at?  I'm guessing that there's no one who will look at this one that's been closed for so long.

**Comment by thefasquelle** [comment]
Would be very useful indeed. Currently I switch to winmerge when i need to diff case insensitive files (VB) but it's a pain when diffing with previous version from SVN for exemple.

I am not sure I understand the status of this issue though: It has been closed and marked as out of scope, so probably forgotten forever by MS, but at the same time it's in the backlog ?
