### ISSUE TITLE
Custom snippets in [language].json file -VS- Emmet snippets.json

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#32909]
- VSCode Version: 1.15
- OS Version: win7x64

I wonder what is the difference between custom snippets from, for example, css.json file and Emmet css snippets from snippets.json

They do the same work with the same speed, don't they?

**Comment by ramya-rao-a** [comment]
Custom snippets in Emmet follow the Emmet abbreviation style.

Say you want an html snippet for 
```
<ul>
    <li class="item"><span></span></li>
    <li class="item"><span></span></li>
    <li class="item"><span></span></li>
</ul>
```

If you try to add this via User Snippets, you will have to add the whole html above.

If you add it via Emmet, all you have to add is `ul>li.item*3>span`
Also, once you add this, you can use the same in html, jade, haml files and the right syntax would be used.

Similarly, if you add an custom css snippet for Emmet, same can be used for scss, less, sass, stylus etc.

Hope that helps.

Read more on [Emmet in VSCode](https://code.visualstudio.com/docs/editor/emmet)
