### ISSUE TITLE
Integrated Terminal: Add path variables for cwd setting

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#32919]
With the new multi-root folder capability it can be desirable to open an integrated terminal
using a CWD other than the root folder.

Adding path variables (subset of those used for the window title plus perhaps some for workspace folders)
would allow launching terminals in other locations more easily.

**Comment by Tyriar** [comment]
@cleidigh so `${workspaceRoot}` for the active file is the default (when .cwd is not set), what other variables would you expect need support?

**Comment by cleidigh** [comment]
@Tyriar 
The other variables would somehow be associated with other folders of a multi- folder workspace.
Not sure of the best way to represent these, ${wsFolder1} or perhaps the suffix of the folder.
Lastly a variable for the "parent"? folder (where the workspace file is)

**Comment by Tyriar** [comment]
I may be off, but I think you can accomplish a similar thing by only setting cwd in one of the folders. Let's close this for now and see if people run into the problem.
