### ISSUE TITLE
How to locate one of several files of the same name

### ISSUE THREAD

**Issue by Ltre** [Microsoft/vscode#32918]
- VSCode Version: 1.15
- OS Version: windows 7 x64

How to locate one of several files of the same name

![image](https://user-images.githubusercontent.com/7886064/29545548-9078e304-8721-11e7-8c64-0aff792a3d21.png)
As shown, I want to match the "config.php" of "adsys/protected". In SublimeTextEditor, it is easily to  enter some keywords on the left side of the config.php to match the target. 
But VSCODE can't do that.

**Comment by Tyriar** [comment]
You can hit home and type adsys to do this:

![image](https://user-images.githubusercontent.com/2193314/29584512-d4cf65b6-8738-11e7-8776-9a5cac3638d8.png)

**Comment by Ltre** [comment]
![image](https://user-images.githubusercontent.com/7886064/29699344-ac842bc0-898e-11e7-9878-49af05c737f8.png)

I typed "adsys" on the left side of the "config.php".

But it can not match the target.

For example, my target is "adsys/protected/config.php"

I can type "protected" on the left side of the "config.php", but it can not match it accurately.

![image](https://user-images.githubusercontent.com/7886064/29699440-4cc052b2-898f-11e7-844c-41c4322bb6ef.png)

When I type "adsys" on the left side of the "config.php".
It can not match any target which I need.

![image](https://user-images.githubusercontent.com/7886064/29699474-8ad3e618-898f-11e7-9ef3-6c5e3449d73c.png)

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/9d40f0c647bf1de0aaa813e6519b85a24e98da14
