### ISSUE TITLE
Add contrast ratio to color picker

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#32910]
Chrome DevTools recently added color contrasts to their color picker, which makes it much easier to do accessibility compliance.

![image](https://user-images.githubusercontent.com/173559/29541833-9c0e2a6c-868b-11e7-88c3-4b3cf241b365.png)

We should add the same to ours.

Blog post: https://remysharp.com/2017/08/17/contrast-ratio-in-devtools

**Comment by Tyriar** [comment]
We would need to know what the background color is to do this, inside Chrome it knows what the background is as it owns the DOM node. We don't have that information so it probably wouldn't be as intuitive (needing to manually pick a bg color).

**Comment by auchenberg** [comment]
It looks like Chrome has the option to select the color manually too, so I don't think it would be too un-intuitive.

**Comment by fabiospampinato** [comment]
Sounds too specific to be included by default. Perhaps a way of extending the default colorpicker and an extension implementing this functionality would be better.

**Comment by auchenberg** [comment]
What was the rationale of adding the color picker as a core component?

Applying the same principle an extension could probably have contributed
the color picker and we would have had multiple versions (with and without
contrast) competing.

**Comment by Tyriar** [comment]
@auchenberg it's not possible to integrate a color picker like this as an extension as we're quite restrictive on what UI extensions can display. See https://code.visualstudio.com/docs/extensionAPI/patterns-and-principles#_extensibility-api

Keeping the color picker simpler in this case would probably be better as contrast would be a little clunky requiring the user to select the background (color picker within a color picker?).

**Comment by auchenberg** [comment]
@Tyriar I'm fully familiar with our current extension model and it's limitation ;) I'm asking to the principles and rationale for adding the color picker as a built-in (core) component?

Given that's it's now a part of the product, we have to consider how our experience is compared to competitors, and make sure our color picker is competitive. With the recent additions in Chrome DevTools our color picker now "lacks" two features: Custom color inputs (hex) + color contrasts.

We know from speaking to developer who are doing accessibility work that color contrats and AAA validations are key to a more efficient workflow.

**Comment by octref** [comment]
The is only doable if you know the bg color of specific DOM element, which requires browser. Let's say we add it without a browser, now users need to manually configure a bg for the contrast ratio to show correctly. This doesn't sounds very useful.  Finally CSS language server has no knowledge of the HTML so this can't be done.
