### ISSUE TITLE
[Code formatting] {{else if}} doesn't work in handlebars files

### ISSUE THREAD

**Issue by shijistar** [Microsoft/vscode#32916]
- VSCode Version: 1.15.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Try to format the following code in `hbs` (Ember template) files
```hbs
{{#if conditionA}}
    Something when conditionA comes true
{{else if conditionB}}
     Otherwise, something when conditionB comes true
{{/if}}
```

Expected:
  Code indent like above.
Actually:
```hbs
  {{#if conditionA}}
    Something when conditionA comes true {{else if conditionB}} Otherwise, something when conditionB comes true
  {{/if}}
```

Reason:
```{{else if}}``` direction is not recognized as a block statement but regular handlebars tags.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as the formatter. It is foremost a HTML formatter, but has some support for handlebars.
I suggest to file this as a feature request there.

**Comment by shijistar** [comment]
This issue was created long ago. https://github.com/beautify-web/js-beautify/issues/870
