### ISSUE TITLE
Add deepscan.io to trusted badge providers

### ISSUE THREAD

**Issue by cimfalab** [Microsoft/vscode#32917]
I wanted to add a badge for my VS Code extension project like:
[![DeepScan Grade](https://deepscan.io/api/projects/369/branches/577/badge/grade.svg)](https://deepscan.io/dashboard/#view=project&pid=369&bid=577)

But I can't package my extension due to svg issue, SVGs are restricted in README.md.

Please consider adding [deepscan.io](https://deepscan.io) to trusted badge provider.

**Comment by cimfalab** [comment]
Hello,
Can I ask how far are you on this issue?

**Comment by mjbvz** [comment]
Should be fixed in the next insiders build

**Comment by roblourens** [comment]
Is this fixed @mjbvz? There's an open PR in vsce - https://github.com/Microsoft/vscode-vsce/pull/213/files - and I think there should be a change in distro which I don't see.

**Comment by mjbvz** [comment]
Yes, deepscan now renders for me in markdown:

![screen shot 2017-12-05 at 2 41 45 pm](https://user-images.githubusercontent.com/12821956/33634841-759ed628-d9ca-11e7-8355-e82107a46866.png)

See https://github.com/Microsoft/vscode-distro/blob/master/quality/insider/product.json#L540 as well
