### ISSUE TITLE
editor view - all branch close and open - feature missing

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#32913]
I'm not sure whether this functionality does exist, but i haven't found it yet.

I have tried to open a carto project.mml, it's not supported, but i have realized that VSCode is smartly looking for tabs, so at the side bar i can close and open nodes.

For big files, does not necessary c++/html javascript etc., it would be helpful to be able to close all the nodes in the editor window and open it selectively what the collapse all does in the file browser.

**Comment by CnSimonChan** [comment]
Are you asking for the `Fold All` command?

Your can press `Ctrl + Shift + P` then type `Fold All`, `Enter`, or the default keybinding for it on Windows is `Ctrl + K Ctrl + 0`.

**Comment by raxim1** [comment]
Thanks for that, can this functionality be accessible in a more natural way? At the top of the side bar of the editor with some sort of coloring? - it's good to have ctrl+shift+p for specific actions, but i probably never would figure out this.

**Comment by CnSimonChan** [comment]
I think Code (and maybe most editors for programmers) are designed to invoke most commands via keyboard, because they have too many commands to put on the UI (I even have the menu bar hidden, because I don't use it).

You can always reassign a keybinding for it, but that's all, I believe.
