### ISSUE TITLE
Search function always pending, restart VSCode may solve the problem

### ISSUE THREAD

**Issue by lijing666** [Microsoft/vscode#32915]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-todo|Mat|0.8.0
html-css-class-completion|Zig|1.8.1
vscode-eclipse-keybindings|alp|0.9.6
git-easy|bib|1.9.1
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
git-project-manager|fel|1.3.2
vue-snippets|hol|0.1.2
search-node-modules|jas|1.1.1
vue|liu|0.1.5
vscode-scss|mrm|0.6.2
vetur|oct|0.9.4
vscode-icons|rob|7.12.0
vue|sea|0.4.2
templex|sle|0.1.1

---

Steps to Reproduce:

1. Click the Search button or Shift+Command+F
2. Input some some keywords
3. Click Enter to do search
4. Pending....
5. Restart VSCode may solve the problem ,but some time later, it gets pending again

Reproduces without extensions: No

**Comment by roblourens** [comment]
Can you check whether there is a process named `rg` running when the search is pending? Or check for errors in the developer tools console?

**Comment by lijing666** [comment]
I have uninstalled all plugins and everything sames all right now! @roblourens Thank you! So I can't recheck! Sorry!

**Comment by roblourens** [comment]
Hm, glad it works at least!
