### ISSUE TITLE
Don't indent case labels within switch

### ISSUE THREAD

**Issue by jankalfus** [Microsoft/vscode#32925]
VSCode has started to indent case labels in switch statements in JavaScript since the July 2017 release. It didn't do this previously and there's no setting (AFAIK) to change this behaviour back. BTW most style guides and also ESLint by default prefer not to indent the case labels.

- VSCode Version: 1.15.1
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. Create a switch statement with case labels
2. Use the "Format Document" command

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/18682
