### ISSUE TITLE
Terminal drawing takes very long sometimes

### ISSUE THREAD

**Issue by StefanoChiodino** [Microsoft/vscode#32929]
- VSCode Version: 1.15.1
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. In my case run `cargo test` for the rust language. Test results show up in the console.
2. Sometimes the terminal can't be scrolled with the mouse wheel, and the text cannot be selected. However I can slowly scroll with `CMD + Up / Down`

Reproduces without extensions: No (cargo test is part of an extension)

**Comment by Tyriar** [comment]
@StefanoChiodino the next time this happens, could you check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by StefanoChiodino** [comment]
ok! Just had to run the task `cargo: test` about 5 times before this happened.

[-1503470352197.log.zip](https://github.com/Microsoft/vscode/files/1244379/-1503470352197.log.zip)

**Comment by justlurking** [comment]
Are there any Unicode characters in the output?  I wonder if there is any relation to issue #24795?

**Comment by StefanoChiodino** [comment]
I think so, because I'm using zsh agnoster theme! However I think I managed to do the same using the default terminal.

**Comment by franklin-ross** [comment]
I'm seeing this too sometimes (at least I think it's the same issue). Sometimes my terminal windows freeze up so I can't scroll or otherwise interact with them. They usually stay that way for around 5 seconds. This often happens every few seconds for a while, and then for some reason it'll come good again.

This only seems to happen when I'm running a watch. The most recent culprit was a fairly large Webpack watch, so I thought it must be something in that misbehaving, but when I profile VSCode while this is happening, I can see that there's some animation frame in xterm taking about 5 seconds, so now I'm not so sure.

![image](https://user-images.githubusercontent.com/2695677/32089233-6593f1e6-bb34-11e7-9724-9bd9e47342ae.png)

I can provide this profiler file, but it's about 33 meg.

**Comment by franklin-ross** [comment]
These console errors could be related too:

![image](https://user-images.githubusercontent.com/2695677/32089315-00526eba-bb35-11e7-8d53-d2124d7d5efc.png)

**Comment by Tyriar** [comment]
@franklin-ross that shouldn't be related but I fixed that null pointer exception in https://github.com/Microsoft/vscode/commit/af325c830e0fafaecaeb97e549b0c8a9d4241c06

**Comment by franklin-ross** [comment]
@Tyriar Did you mean just the console errors aren't related? Cos that makes sense.

Any ideas about the hangs? Can I provide any more info, or is it something I should post to the xterm repo?

**Comment by Tyriar** [comment]
@franklin-ross I'm not sure the hanging is related to scrolling, here's an issue tracking that: https://github.com/Microsoft/vscode/issues/37153

If you can repro in the xterm.js demo then please create an issue there :smiley:

**Comment by franklin-ross** [comment]
@Tyriar Yup, fair enough. I usually notice because it won't scroll, so it kind of presents that way.

I'll try and repro over in that issue if I get the time. Cheers.

**Comment by Tyriar** [comment]
Not sure why drawing is taking so long but you could try launching vscode using `code --disable-gpu` to see if that fixes the issue.

**Comment by Tyriar** [comment]
@franklin-ross also how large is the terminal panel typically on your setup? Do you have a super large monitor which allows heaps of cols/rows?

**Comment by franklin-ross** [comment]
Hey @Tyriar, sorry for not responding for a while. I haven't seen this issue lately, so maybe a patch for one of Windows/VSCode/xterm fixed it.

It was happening on my 15.6 inch laptop, which has a resolution of 3840x2160. So it wasn't so much about the number of rows and columns as the number of pixels.

Anyway, it's by me that this is closed now.

**Comment by Tyriar** [comment]
@franklin-ross thanks for the update, I'll keep an eye out for it in other issues
