### ISSUE TITLE
Indentation error when pasting html snippets in editor

### ISSUE THREAD

**Issue by aschrijver** [Microsoft/vscode#32928]
- VSCode Version: 1.15.0
- OS Version: 4.4.0-91-generic (Ubuntu 16.04)

**Steps to Reproduce**:

Given the following html in the editor window:

```html
        <section data-transition="fade">
          <h2 style="text-transform: none; color: #526ac8">what it is</h2>
          <div>
            <ul>
              <li>fun</li>
              <li>social</li>
              <li>beneficial</li>
              <li>relevant</li>
              <li>educative</li>                
              <li>rewarding</li>
            </ul>
          </div>
        </section>
```

If I Copy and Paste that on a new line at the first caret position,

Then the pasted html in editor now looks like this:

```html
        <section data-transition="fade">
            <h2 style="text-transform: none; color: #526ac8">what it is</h2>
            <div>
              <ul>
                <li>fun</li>
                <li>social</li>
                <li>beneficial</li>
                <li>relevant</li>
                <li>educative</li>                
                <li>rewarding</li>
              </ul>
            </div>
          </section>
```

**Error**: Everything in the pasted snippet except the first `<section>` is indented by 2 additional spaces

Sometimes after pasting only the last tag is indented with 2 pages and sporadically just the first tag.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Thanks all for your feedback, let's track this issue in https://github.com/Microsoft/vscode/issues/32320 , which talks about similar bug (indentation adjustment when pasting, moving, entering) in HTML/PHP like language. All your input will be considered when we tackle this issue. 

For you now if the indentation adjustment makes pasting worser, you can turn this off by setting `editor.autoIndent` to `false`. Thanks again for your help!
