### ISSUE TITLE
Open In Terminal does not work

### ISSUE THREAD

**Issue by shahbikash** [Microsoft/vscode#32924]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.1.8

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please provide more information:

- How are you opening the terminal?
- What happens?
- Are there errors in the devtools console? (Help > Toggle Developer Tools)
