### ISSUE TITLE
Node.js, open the project folder, rename the project folder and open it again

### ISSUE THREAD

**Issue by 641221621** [Microsoft/vscode#32921]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.Node.js, open the project folder, rename the project folder and open it again
2.

**Comment by Tyriar** [comment]
What's the issue?
