### ISSUE TITLE
why autocomplete is fuzzy matching

### ISSUE THREAD

**Issue by hechaochao** [Microsoft/vscode#32927]
I have a special scenario, when type string starts with '@' then a complete list will be given which is returned from server side by using the string after '@' for querying. But there is a question confused me, when continue type the handler registered through connection.onCompletion() will not triggered again if the previous list after filtering is not empty by default the strategy seems like fuzzy mathing but in my situtation the result may not the better.Details is below
1. in user setting set editor.quickSuggestions on
![1](https://user-images.githubusercontent.com/10389980/29550266-75cc8826-873f-11e7-817c-8400e95c19f5.gif)
2. if i set trigger characters on language-server connection.onInitialize() like 
completionProvider: {
					resolveProvider: false,
					triggerCharacters:["e","n","g","i","r"]
				},
then each time i type a char which is in triggerCharacters will trigger handler, this is what i want when type a char each time should trriger handler, is neccessary to assign all chacters? this seems not smart, is there simple method can reach my needs? any suggestions will appreciated.
![2](https://user-images.githubusercontent.com/10389980/29550480-861707a0-8740-11e7-93a8-5f46e5b4fc21.gif)

My project is based on official language-server demo, in order to implement code completion. But in my situation the completion list was got through sending http request to my server side. In one words, what i want is each time i type a char registered handler should be invoked.

**Comment by dbaeumer** [comment]
@hechaochao if you mark the result of the completion request as complete we will filter the list on the server assuming that the server even if the user type can't provide better matchers. You can mark the list as incomplete and then we will ask after every new character enter. 

See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request
