### ISSUE TITLE
Intellisense don't work

### ISSUE THREAD

**Issue by wonjurini** [Microsoft/vscode#32926]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
code-runner|for|0.7.0
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
csharp|ms-|1.12.1
mono-snippets|zra|0.0.2

---

Steps to Reproduce:

1. using Unity3d and updated vscode 1.15
2. Intellisense don't work 

Reproduces without extensions: Yes/No

**Comment by fleumari** [comment]
Did you try restarting VSCode? Does it say `Loading...` ?

**Comment by Tyriar** [comment]
It looks like this is an issue with the unity-tools extension you have installed.
