### ISSUE TITLE
Plugin HTML CSS Support and Emmet are conflicted.

### ISSUE THREAD

**Issue by shuang6** [Microsoft/vscode#32923]
- VSCode Version: 1.15.1 x64
- OS Version: Windows 10 Professional x64

Steps to Reproduce:

1. when I type “div.”, Emmet and HTML CSS Support will both give prompts.
But if I select the prompt HTML CSS Support given and press TAB, Emmet will do nothing.

![qq 20170822124750](https://user-images.githubusercontent.com/24518569/29549054-521176b4-8738-11e7-80d1-1e73e20ae31a.png)
![qq 20170822124807](https://user-images.githubusercontent.com/24518569/29549062-5a17644a-8738-11e7-9e59-180532309c54.png)

**Comment by ramya-rao-a** [comment]
When you select the suggestion from html css support why do you expect emmet to work instead?
