### ISSUE TITLE
vscode crash when i update vscode in mutiusers of iMac

### ISSUE THREAD

**Issue by flyketch** [Microsoft/vscode#32939]
- VSCode Version:1.13.1
- OS Version:macOS High Sierra

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by flyketch** [comment]
In my mac, I created admin account and three standard account, I installed vscode in admin account, my bro worked on standard account, vscode crashed when vscode remind him of installing new updates.

**Comment by joaomoreno** [comment]
Can you share a screenshot of the crash?
