### ISSUE TITLE
Change Default .vscode directory path

### ISSUE THREAD

**Issue by FlorianTaut** [Microsoft/vscode#32933]
Hey,

is it possible to change the path where the .vscode cirectory is created?

Im running Code on a USB-stick and dont want it to save extension on the local computer anytime.

Thank you!

**Comment by yume-chan** [comment]
You can use `--user-data-dir` and `--extensions-dir` command line arguments, see the [doc page](https://code.visualstudio.com/docs/editor/command-line#_additional-command-line-arguments).

**Comment by FlorianTaut** [comment]
@yume-chan thank you!

Does Code then still use the extensions installed in the namend Directory of do i have to install them everytime again?

**Comment by yume-chan** [comment]
Code will ONLY use extensions in your specified extension folder.

**Comment by FlorianTaut** [comment]
Ok thank you @yume-chan
