### ISSUE TITLE
Latest insiders build broke tig in integrated terminal

### ISSUE THREAD

**Issue by ilkka** [Microsoft/vscode#32932]
I've been using the ncurses-based tig for doing git right in the integrated terminal, and before today I remember it working just fine. Today it started acting up in several views, with cursor positions not getting correctly set before updating the view. Pieces of the UI that should update old pieces get written to different lines.

- VSCode Version: Code - Insiders 1.16.0-insider (f1e49caf99c0a9d5b41a699f052362bafa576f3d, 2017-08-22T05:11:15.052Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
vscode-docker|Pet|0.0.16
project-manager|ale|0.19.0
vscode-standardjs|che|1.1.8
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
markdown-table-prettify|dar|1.1.1
python|don|0.7.0
gitlens|eam|4.4.0
tslint|eg2|0.17.0
vscode-npm|fkn|3.3.0
ansible|haa|0.2.5
elixirlinter|iam|0.4.1
case-sensitive-add-next|jac|0.0.6
markdown-shortcuts|mdi|0.8.1
vscode-elixir|mjm|0.5.1
ide-purescript|nwo|0.11.5
language-purescript|nwo|0.1.1
vetur|oct|0.9.4
advanced-new-file|pat|0.5.0
vscode-icons|rob|7.12.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Open VS code
2. Open integrated terminal
3. Install tig
4. `$ git init test && cd test && touch foo bar && tig status`
5. Stage files with 'u', move cursor with arrows, exercise UI -> UI breaks

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@ilkka could you check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by ilkka** [comment]
No errors. Here is a screenshot showing how the console looks after running the commands in the original report:
![nayttokuva 2017-08-24 kello 13 10 57](https://user-images.githubusercontent.com/1549/29661837-e82b57a0-88cd-11e7-8bf4-78f70580f7f4.png)
The tig UI is rendered twice, one on top of the other.

Quitting and re-running `tig status` yields a normal looking UI:
![nayttokuva 2017-08-24 kello 13 11 17](https://user-images.githubusercontent.com/1549/29661875-09339cdc-88ce-11e7-9f8b-0e70483b0bf3.png)

But now staging files (with `u` being the standard hotkey IIRC) breaks it, note the bottom status bar:
![nayttokuva 2017-08-24 kello 13 11 25](https://user-images.githubusercontent.com/1549/29661901-23372496-88ce-11e7-8e9e-6d5789038447.png)

Continuing to navigate the UI breaks it further:
![nayttokuva 2017-08-24 kello 13 11 40](https://user-images.githubusercontent.com/1549/29661917-312fd9e4-88ce-11e7-82ea-cbb208b5706f.png)

**Comment by Tyriar** [comment]
Phew, that took a while to figure out. Upstream PR is out, expect the fix soon https://github.com/sourcelair/xterm.js/pull/923
