### ISSUE TITLE
unable to get the define with the import  . package

### ISSUE THREAD

**Issue by zz-bmj** [Microsoft/vscode#32935]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|python|donjayamanne|0.7.0|
|gitlens|eamodio|4.3.1|
|Go|lukehoban|0.6.63|
|java|redhat|0.8.0|
|vscode-icons|robertohuertasm|7.12.0|;

---

Steps to Reproduce:

1.golang code
2.when I import package with . package ,my func can't move to the defination
![image](https://user-images.githubusercontent.com/29789939/29555601-c566e348-8755-11e7-9822-d61a3aa0b8ae.png)

**Comment by zz-bmj** [comment]
the import is here

**Comment by yume-chan** [comment]
I don't know Go, but if the language server is provided by an extension, you might need to report it to the extension's repository, not here.

**Comment by zz-bmj** [comment]
Gogland can do it!

**Comment by zz-bmj** [comment]
@Tyriar with the latest version  v1.15.1, the problem still occurs. And I find that Gogland can work well.

**Comment by Tyriar** [comment]
@ramya-rao-a might be able to help you further.

**Comment by ramya-rao-a** [comment]
@zz-bmj The default tool used for finding definitions doesn't work well with dot imports. Set `go.docsTool` to `gogetdoc`, install `gogetdoc` when you get prompted and that should work.

In the future, please log an Go related issues in VS Code at https://github.com/Microsoft/vscode-go
