### ISSUE TITLE
We should have a workspace folder picker API in the Extension host

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#32936]
Extensions now need to scope certain actions (like settings changes) to a workspace folder. In a multi workspace folder setup the need to ask the user which folder to use. To make such a picker the same for all extensions we should offer API for this.

**Comment by sandy081** [comment]
How different is this that an extension show a quick pick with workspace folders and asking to pick?

**Comment by dbaeumer** [comment]
To always make it look the same and use the name as the label and the directory as the description.

**Comment by dbaeumer** [comment]
To always make it look the same and use the name as the label and the directory as the description.

**Comment by M0rdr3d** [comment]
Don't do this
