### ISSUE TITLE
Cursor not repositioned in terminal when using mouse

### ISSUE THREAD

**Issue by imonmyown** [Microsoft/vscode#32930]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crystal-lang|fau|0.3.1
vscode-emacs-friendly|lfs|0.8.0
Go|luk|0.6.63
RustyCode|sav|0.19.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start VSCode
2. Open integrated terminal
3. Type something in the input line
4. Try to reposition the cursor on the line using mouse.

Reproduces without extensions: Yes

(Reproduces in the latest insiders build as well)

**Comment by yume-chan** [comment]
Duplicate of #26401.

**Comment by imonmyown** [comment]
@yume-chan thanks
