### ISSUE TITLE
Import can only be used in a .ts file

### ISSUE THREAD

**Issue by pmesgari** [Microsoft/vscode#32938]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. trying to do an import .... from .... in a .vue file inside <script> tag
2. highlights the line and gives 4 error messages:
- 'import... =' can only be used in a .ts file
- '=' expected
- ';' expected
- ';' expected

There is no eslint plugin, file or anything related to eslint.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
I cannot reproduce this problem.

I tried:

```` html
<script>
import * as fs from "fs";
import readFile from "fs";
</script>
````

No error is reported.

**Comment by mjbvz** [comment]
Please try filing this issue with your vue extension. We don't provide vue file support out of the box
