### ISSUE TITLE
when will the menu can support switch theme or customizable ?

### ISSUE THREAD

**Issue by lizhuangs** [Microsoft/vscode#32940]
like idea,subline text.change all the menu black or other.
now It looks incongruous.
Tks.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/16363

**Comment by lizhuangs** [comment]
@Tyriar Is that any plan for this?Tks.

**Comment by Tyriar** [comment]
Not sure if we have access to this through [the platform](https://http://github.com/electron/electron) yet.
