### ISSUE TITLE
why can not update when I clicked the update now button？  it remind me to restart to update，but after I restart the VSCode， it still reminds me to restart to update。 Even after I reinstalled the VSCode， it still have the question

### ISSUE THREAD

**Issue by ahutyaoyj** [Microsoft/vscode#32942]
- VSCode Version:1.14.1
- OS Version:10.12.4

Steps to Reproduce:

1.restart VSCode to update
2.open VScode， still reminds me to update

Reproduces without extensions: Yes/No
![image](https://user-images.githubusercontent.com/9247427/29560558-e8e5ec7e-8764-11e7-8a17-119d36fdbd3a.png)

**Comment by Tyriar** [comment]
@ahutyaoyj are you on a Mac?

**Comment by ahutyaoyj** [comment]
@Tyriar yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
