### ISSUE TITLE
Commands: make title optional

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#32943]
When developing extensions I usually use a function that retrieves the contributed commands from `package.json` and for each of them calls `vscode.commands.registerCommand` with the proper handler.

The problem is that one can register a command that doens't have a title, but you can't write it in `package.json` because there the title is required.

I think commands shouldn't be forced to have a title. In case they don't have it those commands simply shouldn't be available in the Command Palette.

Another problem with the current approach is that those hard-coded commands won't be displayed under the `Contributions` page of an extension.

What do you think?

**Comment by jrieken** [comment]
> I think commands shouldn't be forced to have a title. In case they don't have it those commands simply shouldn't be available in the Command Palette.

Yeah, that's how it works. The naming is overloaded, but a command that you register in code, via `registerCommand`, is just an identifier to function binding. With just that your command is known to the system and can be executed by different gestures, e.g. a keybinding, the command palette, the `executeCommand`-function, etc

> I usually use a function that retrieves the contributed commands from package.json and for each of them calls vscode.commands.registerCommand with the proper handler.

That means that you always have a UI gesture (command palette entry) for each an every command. If you don't want that, you need to register your command from another source.

**Comment by fabiospampinato** [comment]
> Yeah, that's how it works. 

That's not how it works in `package.json`, you can't have a command without a title, not even with an empty title.

------

There's also another problem caused by this limitation, let's take as an example the following "Projects" explorer view:

![Projects+](https://raw.githubusercontent.com/fabiospampinato/vscode-projects-plus/master/resources/demo/explorer.gif)

What if I want to add a button to the header that changes the sorting order of things? With how things currently work I'm forced to define this command in `package.json`, meaning it will be shown in the command palette. But I think this behavior shouldn't be enforced, it doesn't really make much sense to have a "Sort the projects listed in the explorer view ascending by name" in the command palette, I mean, other than the awkward name maybe that explorer view is not even visible at that time.

**Comment by jrieken** [comment]
> That's not how it works in package.json, you can't have a command without a title, not even with an empty title.

Yes, but you don't need to declare each and every command in the commands section of 'package.json'. Tho, if it's defined in there it will show in the command palette. That's how the command-section was originally designed. With the introduction of menus, we kept that semantics but can define a when condition that tells when a command should show up in the palette: https://code.visualstudio.com/docs/extensionAPI/extension-points#_context-specific-visibility-of-command-palette-menu-items

**Comment by fabiospampinato** [comment]
> Yes, but you don't need to declare each and every command in the commands section of 'package.json'.

Except that you do if you want those commands to be called from menus.

The `when` property looks like a reasonable approach to the problem, but it's almost undocumented. For instance one of the provided sample extensions uses ["when": "view == nodeDependencies && viewItem == dependency"](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/package.json#L75); that `viewItem` looks pretty interesting, but a Google search to find out more about it (`site:https://code.visualstudio.com/docs viewItem`) basically returns 0 results.

**Comment by jrieken** [comment]
> Except that you do if you want those commands to be called from menus.

Yes, that is correct and kind of legacy. First came commands and they were 'global' by default because they were only living in the command palette. With menus we made them more 'local' and show up here and there...
