### ISSUE TITLE
Multi root: transition without window reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#32945]
Now that we can restart the extension host we should explore to enter multi-root workspace mode from 0 or 1 folder workspace without requiring a window reload.

This requires all users of the `IWorkspaceContextService` to be ready for the transition of zero or one folder into a workspace without window reload. The following larger components need to be adopted:
* [ ] Foundation (local storage, workspace, workspace editing, configuration, configuration editing) @sandy081 @bpasero
* [ ] Explorer @isidorn 
* [ ] Task @dbaeumer 
* [ ] Debug @isidorn 
* [ ] Preferences @sandy081 
* [ ] Search @roblourens 
* [ ] Extensions (enablement, recommendations) @sandy081 

Instead of statically checking for a workspace being present or not, these components should subscribe to the `onDidChangeWorkspaceRoots` event and handle all cases (0 folders, 1 folder, N folders).

**Comment by bpasero** [comment]
I did an initial investigation using the following query in fulltext search (regex, case sensitive, word) to find all clients of the workspace API:
`hasWorkspace|hasFolderWorkspace|hasMultiFolderWorkspace|getLegacyWorkspace|getWorkspace`

There are some larger components that need to be fit for the transition of "0 folder to workspace" as well as "1 folder to workspace". In general I would say that the transition from 1 folder to a workspace is already covered quite well, but the transition from no folder to a workspace is not covered yet.

I will update the summary of this issue with the components that need to adopt the transition.

**Comment by dbaeumer** [comment]
@bpasero I will fold this with making tasks multi workspace capable which is planned for September.

**Comment by bpasero** [comment]
@dbaeumer awesome 👍

**Comment by bpasero** [comment]
This landed in todays insider release.
