### ISSUE TITLE
Keyboard Focus shifts to body when removing a tree item that has focus

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#3294]
I used the keyboard to navigate to the add action on the watch expression title in the debug viewlet.

I entered an expression, then tabbed to the delete action for that expression. I hit enter. The expression was deleted. I expected focus to move back to the watch expression title so that I could easily add another expression but instead focus was set to the activity bar meaning I had to press tab repeatedly to get focus inside the debug viewlet.

Found while testing #3246

**Comment by bpasero** [comment]
This looks like a general issue when an action results in a tree item to be removed and thus the element with tabindex gets lost and the browser decides to move focus to the body.

**Comment by bpasero** [comment]
@joaomoreno after our discussion, it would be nice if the tree could just move focus to its tree DIV when it detects that a tree item gets removed from the DOM that contains the document.activeElement.

**Comment by joaomoreno** [comment]
Actually this specific issue is now fixed since the action to delete a watch expression isn't there any more.
