### ISSUE TITLE
Default target of Configuration API update should be derived from configuration and resource

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#32949]
To make it easier for extension author using workspace config update api, VS Code should derive the default target (if not provided) from the configuration and resource.

- If no resource is provided, then target should be Workspace.
- If configuration is workbench scoped, then target should be Workspace.
- If configuration is resource scoped and resource is provided then
-- target is WorkspaceFolder in MR case
-- target is Workspace otherwise

cc @dbaeumer

**Comment by dbaeumer** [comment]
@sandy081 thanks.

**Comment by sandy081** [comment]
For verifiers, there is already any issue that updating to user configuration is not working - #33440
