### ISSUE TITLE
Default settings seem to have duplicate object key "npm.runSilent": false

### ISSUE THREAD

**Issue by Nikki1993** [Microsoft/vscode#32944]
- VSCode Version: 1.15.1
- OS Version: Solus 3

Steps to Reproduce:

![duplciate](https://user-images.githubusercontent.com/1446529/29560860-0622be94-873c-11e7-9010-46c3dbd4f8f3.png)

1. Open User Settings,
2. See the warning at the bottom status bar about duplicate object key in defaultsettings/settings.json

**Comment by yume-chan** [comment]
Maybe a duplicate of #32716.

**Comment by Nikki1993** [comment]
Yes it is, closing this one.
