### ISSUE TITLE
Emmet not working since the July 2017 update

### ISSUE THREAD

**Issue by danielsamuels** [Microsoft/vscode#32948]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
GitHubIssues|Hoo|0.1.2
Handlebars|and|0.2.0
django-snippets|bib|1.1.0
stylelint|shi|0.28.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.4.0
auto-close-tag|for|0.4.3
vscode-nginx-conf-hint|han|0.0.4
vue-snippets|hol|0.1.2
vue|jcb|0.1.5
vue|liu|0.1.5
MagicPython|mag|1.0.12
github-issues-prs|ms-|0.4.0
sublime-keybindings|ms-|2.9.1
PostCSS|ric|1.0.1
nunjucks|ron|0.2.3
vscode-nginx|sha|0.3.1
expand-selection-to-scope|vit|0.2.0
twig|wha|1.0.2
jinja|who|0.0.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Enter an emmet abbreviation such as `mb10`
2. Attempt to expand it in any of the suggested ways (Command Panel -> Expand Abbreviation, Tab with `emmet.triggerExpansionOnTab` enabled)
3. Nothing happens

![vscode-emmet-broken mov](https://user-images.githubusercontent.com/1781176/29562340-c32aa5ee-8730-11e7-893b-1d5f9f22233f.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@daanschipper That is odd.

- Do you see any errors showing up in the dev console? Run `Developer: Toggle Developer Tools` to see the console.
- Is the problem only in css files? Have you tried Emmet in html or scss files?
- Can you share your settings?
- What is the language mode of the file you are trying emmet on?

**Comment by danielsamuels** [comment]
* No errors in the dev console.
* I don't get autocompletion in HTML or SCSS files either.
* [My settings file](https://gist.github.com/danielsamuels/ee910c0b9445776d59f4592d139bfb30) - I've been playing around with the `editor.quickSuggestions` and `emmet.triggerExpansionOnTab` settings, but neither of them seem to change anything.
* Language mode in my .css files is 'PostCSS'. For .html files it's Nunjucks (for Django / Jinja highlighting). I hadn't seen this option before, but changing it to CSS does make Emmet work, at the cost of my syntax highlighting.  Does this mean it's simply an extension issue? Perhaps I need to add a mapping for Emmet?

**Comment by danielsamuels** [comment]
It appears that including this in my settings file solves my problem:

```json
"emmet.includeLanguages": {
    "postcss": "css",
    "nunjucks": "html"
}
```

Sorry for wasting your time.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
