### ISSUE TITLE
Add command to close file below keyboard cursor

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#32952]
Here is what happened when i hit CMD+W (close file on MacOs) while i'm in the "opened files" block : 
Steps to Reproduce:
![closecurrent](https://user-images.githubusercontent.com/5599375/29564013-4f058fb6-8740-11e7-83bd-3cf8a3174d74.gif)

Current behaviour : 
- the CMD+W (MacOs) close the active file, event if we focus another one in opened file.

Expected option : 
- the CMD+W (MacOs) close the active focus opened file without focusing it in editor.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
