### ISSUE TITLE
Freezes on Search with "one line file" in result (typically map files)

### ISSUE THREAD

**Issue by mlaffargue** [Microsoft/vscode#32957]
- VSCode Version: 1.14.2
- OS Version: Windows 7 professional

Steps to Reproduce:
In a JS project using webpack for example
1. Search for a String
2.If the result as a "one line" file to show, the search tab freezes during several seconds.
3. Scroll so the file disappear "Search" behaving correctly
4. Scroll back until the file appears again, it freezes

File example :  0.chunk.js.map

From my point of view seems like it's creating a tooltip with the whole file inside.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Yes, this is #31551. Not a great experience, but I expect people to typically exclude these files from their search.
