### ISSUE TITLE
No way to setup the shell utf-8 encoding in windows.

### ISSUE THREAD

**Issue by artem-leonov** [Microsoft/vscode#32955]
- VSCode Version: 1.15.0
- OS Version: Windows 10 Pro 1703

I need to change shell encoding to utf-8, because default encoding not showing up cyrillic symbols. Only way to do this that I found is adding shell args as described in #19837. But when I use tasks with this workaround error happens. "Parameter format not correct - /d" for cmd and "Parameter format not correct - -Command" for powershell. There is no way to change shell encoding and use tasks both.

Steps to Reproduce:

1. Setup ```"terminal.integrated.shellArgs.windows": ["-NoExit", "/c", "chcp 65001"]``` in configuration
2. Run any task (E. g. build)

Reproduces without extensions: Yes

**Comment by verysimplenick** [comment]
For build tasks I use something like this
```json
{
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [
                "/C",
                "chcp 65001",
                "&&",
                "dotnet",
                "build",
                "${workspaceRoot}/NaturalBreaksClassification.csproj"
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by yumetodo** [comment]
When I use git-bash from this terminal, there is also no way to set up as utf-8.

ref(ja-JP): https://teratail.com/questions/90822

**Comment by artem-leonov** [comment]
@verysimplenick I just tried your configuration, but, unfortunately, "dotnet build" command's output is not in utf8-encoding.

**Comment by dbaeumer** [comment]
With the new task runner that executes task in the terminal using a shell this got simplified a lot. Tips and tricks on how to control the encoding can be found here: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/tasks.md#changing-the-encoding-for-a-task-output

As explained there is not generic way how this can reasonably be solved for different OSes and shells.
