### ISSUE TITLE
cpu 占用过高

### ISSUE THREAD

**Issue by zb1908** [Microsoft/vscode#32958]
-
![default](https://user-images.githubusercontent.com/29306753/29566305-f813f6b6-877b-11e7-9961-86cbc6aa86a9.JPG)
 VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typescript-react-snippets|abo|0.2.0
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.14
react-native-react-redux|EQu|1.1.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
canvas-snippets|hol|0.3.2
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
docthis|joe|0.4.8
node-module-intellisense|lei|1.4.0
debugger-for-chrome|msj|3.1.8
live-server-preview|neg|0.0.4
vscode-icons|rob|7.12.0
sass-indented|rob|1.4.1
code-settings-sync|Sha|2.8.3
stylelint|shi|0.28.0
guides|spy|0.8.4
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.4.1
vscode-preview-server|yui|0.7.0

(10 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
TO help investigate:

1. Try disabling all extensions by starting code with the `--disable-extensions` flag. One of them could be causing this
2. Right click for `more details`  on the process. What are the full command line arguments of the process with the high CPU usage?

**Comment by 350050183** [comment]
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron  --disable-extensions
It works.

**Comment by mjbvz** [comment]
Ok, since this issue does not occur when extensions are disabled, please try tracking down which extension causes the high CPU usage and reporting the issue against them. The process `more details` information may help with this
