### ISSUE TITLE
Visual Studio Code for MacOS will not update!

### ISSUE THREAD

**Issue by residentx10** [Microsoft/vscode#32953]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Open VS Code
2. Browse Extensions
3. Wait for VSCode Update Message
4. "Do you want to update?" Click "Yes"
5. Update will request password
6. After keying in credentials, application will close
7.  I'm forced to start again and replay the above.

**Comment by Tyriar** [comment]
@residentx10 you're on a *very* old version. It may be worth downloading and installing manually from code.visualstudio.com just in case something has broken since 1.7 (~8 months ago).

**Comment by joaomoreno** [comment]
#7426
