### ISSUE TITLE
Keep IntelliSense open when moving cursor through already written identifier

### ISSUE THREAD

**Issue by sglienke** [microsoft/vscode#3295]
Imagine I have the following code:

foo.Bar();

with the cursor after the dot and I invoke IntelliSense it shows all members of foo.
When I press the right arrow key to move the cursor after the B it should stay open and filter the suggestions to those that start with B. Currently it closes and I have to hit Ctrl+Space again to open it.

**Comment by Wosi** [comment]
The request makes sense. In a different editor it looks like this:
![delphiintellisense](https://cloud.githubusercontent.com/assets/3448684/13251046/18e44d52-da2e-11e5-9e8e-c34581f206ff.gif)

**Comment by joaomoreno** [comment]
:+1:

**Comment by mojo2012** [comment]
Any news on this? This is one of the most annoying usability issues with vscode (imho)

**Comment by jrieken** [comment]
Done

![Oct-26-2020 15-45-22](https://user-images.githubusercontent.com/1794099/97187074-5b5e9c80-17a2-11eb-849b-03ae37592519.gif)

**Comment by jrieken** [comment]
To verify:

* trigger suggest, e.g after the `.` in `console.log`
* move cursor right and see how suggestions get narrowed down
* move cursor left and see more suggestions
