### ISSUE TITLE
$ characters colorized as keyword in regex literal

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/vscode#32951]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
php-intellisense|fel|1.5.1
auto-close-tag|for|0.4.3
mssql|ms-|1.1.0
csharp|ms-|1.12.1
team|ms-|1.122.0
vscode-docker|Pet|0.0.16
---

Steps to Reproduce:
1. Create ASP.NET Core 2 project from Visual Studio 2017 template
2. Open webpack.config.js

![image](https://user-images.githubusercontent.com/9047283/29563876-cb14f37c-873f-11e7-8de1-bf3c75834567.png)

or just type `/$/`.

They get the same CSS class as the `const` keyword for example.

Reproduces without extensions: Yes

In Visual Studio 2017 it works fine, $ is not highlighted:
![image](https://user-images.githubusercontent.com/9047283/29563923-fa3f0912-873f-11e7-890b-042716b68969.png)

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/TypeScript-TmLanguage/issues/505
