### ISSUE TITLE
Fast open file from explorer without put focus on it

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#32950]
Steps to Reproduce:

Open multiple files with command+enter (MacOs) : 
![openfile](https://user-images.githubusercontent.com/5599375/29563083-5adbf482-873c-11e7-9376-16be32c1acdd.gif)

Each time a file open i automaticly switch into the editor. This is the only behaviour forcing me to use a mouse in vscode when i want to open multiples files.

Expected behaviour:
- I can open 3 files in a row, without focus each file once open.

We definitly need a way to fast open multiple file (and save then to opened files) without focusing each file.

I did not find an option or a key binding allowing that, and macro (with extensions) are not working.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/28710
