### ISSUE TITLE
VS Code does not officially support SASS

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#32963]
- VSCode Version: 1.15.1
- VSCode Insiders Version: 1.16.0-insider
- OS Version: Windows 7 Ultimate x64

Hello! Why in VS Code, scss is called as sass? VS Code Insiders has only scss. As far as I know, VS Code does not officially support SASS.

![figure_1](https://user-images.githubusercontent.com/29632606/29569865-1e6bf4be-8798-11e7-8a2a-2abff8516efd.jpg)
![figure_2](https://user-images.githubusercontent.com/29632606/29569866-1e7909a6-8798-11e7-8561-44a5b4067300.jpg)

**Comment by Tyriar** [comment]
We defer to extensions to provide this support, please see https://marketplace.visualstudio.com/search?term=sass&target=VSCode&category=All%20categories&sortBy=Relevance
