### ISSUE TITLE
Error while deleting nonempty dir on remote drive

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#32967]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
gherkin-indent|Ara|2.0.0
vscode-bad-code-highlighter|bha|0.1.6
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
vscode-turtle|fei|1.0.30
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
php-pack|fel|1.0.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
format-indent|Kas|1.3.0
phpmd|lin|1.1.4
vscode-apache|mrm|1.1.1
vscode-duplicate|mrm|1.2.0
oracle-plsql|myc|1.0.3
selectline-statusbar|tom|0.0.2
gitblame|wad|2.1.0
twig|wha|1.0.2

---

After I tried to confirm without extensions, I realized that all contents of the directory has actually been deleted (vscode showed the files as still present) - only the directory I was actually deleting remained behind. Weird. Also after trying on another dir, I could not reproduce the problem. :-(

Steps to (not) Reproduce:

1. try to delete non-empty dir, confirming direct delete after binning fails
2. error message pops up: `A system error occurred (ENOTEMPTY: directory not empty, rmdir 'z:\fooo\bar')`

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Did this ever happen again?

**Comment by PunchyRascal** [comment]
Nope, and I cannot reproduce it now either.
