### ISSUE TITLE
help with launch.json, php, xdebug

### ISSUE THREAD

**Issue by martinandersen3d** [Microsoft/vscode#32969]
I'm having a laravel(php) project, and having Xdebug working in vscode. But unfortunately doing this in a two step. I want to combine it into one.

What I'm doing now i write: 1. in cmd:
`php -S localhost:1000 -t public`
have a vscode > debug > launch.json
```
    {
    "name": "Listen for XDebug",
    "type": "php",
    "request": "launch",
    "port": 9000
     },
```
How can i combine this into one task?

I've try'ed to create the 1. part as a task, but didnt work.

task.json:

```
        {
        "taskName": "PhpServe",
        "type": "shell",
        "command": "php -S localhost:1000 -t public"
    }
```
launch.json

```
        {
        "name": "Listen for XDebug",
        "type": "php",
        "request": "launch",
        "preLaunchTask": "phpServe",
        "port": 9000
    },
```
the php server start up, and run until i close it. After i close it Xdebug start up.. not what i want.

How do i launch php server and xdebug at the same time?

**Comment by roblourens** [comment]
You need to set up the task as a "background" task, since it will be running constantly in the background. See this section of the docs: https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks

**Comment by martinandersen3d** [comment]
I have tryed this, but it didnt work... is this correct?

```
        {
            "taskName": "PhpServe",
            "type": "shell",
            "command": "php -S localhost:1000 -t public",
            "isBackground": true,
            "problemMatcher": []
            
            
        }
```

**Comment by roblourens** [comment]
You would also need to set the `beginsPattern` and `endsPattern` so it knows when the task is running. There are examples and details in the docs linked above.

Basically it assumes the task has to start up and do some stuff, then goes into its idle state, at which point it's safe to launch the debugger.
