### ISSUE TITLE
VSCode Install freezes PC for several seconds

### ISSUE THREAD

**Issue by JoBrad** [Microsoft/vscode#32965]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16257
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
markdown-toc|Ala|1.5.6
file-templates|brp|1.2.0
gitignore|cod|0.5.0
vscode-uriencode|die|0.0.1
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|4.4.0
vscode-html-css|ecm|0.1.8
eppz-code|epp|1.2.41
url-encode|fle|1.1.0
asciidecorator|hel|0.2.0
rest-client|hum|0.15.2
output-colorizer|IBM|0.1.2
easy-icons|jam|0.3.1
hive-sql|jos|0.0.2
vscode-colorize|kam|0.6.3
restructuredtext|lex|36.0.0
vs-color-picker|lih|0.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ecdc|mit|0.10.3
prettify-json|moh|0.0.3
cpptools|ms-|0.12.3
PowerShell|ms-|1.4.1
Chef|Pen|0.6.3
vscode-docker|Pet|0.0.16
heroku-command|pko|0.0.8
view-in-browser|qin|0.0.5
qub-xml|qub|1.2.1
Ruby|reb|0.15.0
toggle|reb|0.0.1
java|red|0.8.0
vscode-icons|rob|7.12.0
todotasks|san|0.5.0
MDTools|sea|1.0.1
html5-boilerplate|sid|1.0.1
html-css-class-completion|Zig|1.8.1

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Install VSCode
2. At the end of the install, the entire PC becomes unresponsive for several seconds

Reproduces without extensions: Yes

This has happened to me for the last 4 updates of VSCode (I wasn't certain if it was another process or not), and also just happened with the 64-bit install. At the very end of the install, before the step that indicates that the installation has completed, my entire PC freezes and will not accept keyboard or mouse input.

**Comment by Tyriar** [comment]
@JoBrad could you download the zip from https://code.visualstudio.com/#alt-downloads then run `bin\code.cmd --verbose` and check the output?
