### ISSUE TITLE
Project folder fails to open

### ISSUE THREAD

**Issue by kbrgl** [Microsoft/vscode#32962]
# The issue
I'm unable to open project folders in VS Code - attempting to open one results in seemingly nothing happening. However, going to the desired folder and running `code . --verbose --disable-extensions` gives:
```
Unable to read folders in /Users/kabir/Library/Application Support/Code/Workspaces (Error: ENOENT: no such file or directory, scandir '/Users/kabir/Library/Application Support/Code/Workspaces').
```

Reinstalling VS Code worked initially, but then the issue started occurring again.

# Details
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vsc-material-theme|Equ|1.0.2
python|don|0.7.0
file-icons|fil|1.0.5
Go|luk|0.6.63
atom-keybindings|ms-|3.0.1
laravel-blade|one|1.8.1
sass-indented|rob|1.4.1
nunjucks|ron|0.2.3
laravel-5-snippets|sac|2.0.1
standard|shi|0.2.3

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Try to open a project folder on macOS

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
What's the output of `ls -la /Users/kabir/Library/Application Support/Code | grep Workspaces` ?

**Comment by kbrgl** [comment]
@Tyriar that doesn't output anything, but I created the directory and the editor is still unable to open project folders. The earlier error `Unable to read folders...` doesn't appear though.

**Comment by bpasero** [comment]
@kbrgl is that a some remote drive (samba share) or similar?

**Comment by kbrgl** [comment]
@bpasero no, it's all local.

**Comment by NGorco** [comment]
The same issue on MacOS Sierra

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by kbrgl** [comment]
@bpasero sure, but the issue had taken a few days to come up, so I'll let you know when it turns up on the insider build

**Comment by kbrgl** [comment]
@bpasero welp, it turned up already. Yes, I can reproduce with the nightly builds.

**Comment by kbrgl** [comment]
Clean install of VS Code (after removing all folders, including those in ~/Library, ~/.code, etc) still shows the issue. I think the steps to reproduce might be a little more specific:
1. Do clean install of VS Code
2. Start VS Code
3. Open folder
4. Remove from sidebar
5. Try to open that or any other folder again

**Comment by bpasero** [comment]
@kbrgl maybe best to share a video of what you are doing and how it results in this error 👍

**Comment by defdata** [comment]
Having the same issue, preventing me from opening folders and doing work with vscode

**Comment by sandy081** [comment]
@kbrgl Looks like you removed the folder view and which will be remembered. You can get back the folder by adding it back. See the following video.

![kapture 2017-08-25 at 11 14 47](https://user-images.githubusercontent.com/10746682/29707745-a96996ee-8986-11e7-93e3-eb6d1182a8bd.gif)

**Comment by bpasero** [comment]
@sandy081 I wonder if we should make it harder to get into this state, e.g. prompt the user if he really wants to remove the files explorer view.

**Comment by sandy081** [comment]
I would also question do we need to provide an option to hide the files explorer?

**Comment by kbrgl** [comment]
Ah ,okay. That worked.

I'd question whether it makes sense though, since in other editors (e.g. Atom and Sublime) removing a dir from the sidebar has the effect of closing the folder as well. It's rather unexpected that the folder should just disappear.

Perhaps this behavior should be made clear the first time the user first tries to remove the folder, or perhaps the behavior should be removed altogether?

**Comment by bpasero** [comment]
@sandy081 yeah maybe not now that we can reorder sections around and collapsed state is persisted.

**Comment by sandy081** [comment]
Related to #31485

**Comment by honzajavorek** [comment]
I clicked the option by accident and it took me several hours of searching the internet to find https://github.com/Microsoft/vscode/issues/32962#issuecomment-324866098 and to get the folder back 😰
