### ISSUE TITLE
Some editing keys such as (CTRL + Backspace) are applying to the active editor while the cursor is in the source control's commit box with some text in it

### ISSUE THREAD

**Issue by nvmkpk** [Microsoft/vscode#32966]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.3.1
ng-template|Ang|0.1.4
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
file-icons|fil|1.0.5
rest-client|hum|0.15.2
debugger-for-phantomjs|ira|0.1.1
Angular1|joh|0.2.0
theme-dark-plus-contrast|k3a|0.1.101
csharp|ms-|1.12.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.1.8
debugger-for-edge|msj|0.4.1

---

Steps to Reproduce:

1. Ensure some non-empty file is open in the editor with cursor somewhere in between
2. Go to git source control side-bar with some staged changes
3. Type in some text in the commit message box and try hitting Ctrl + Backspace

The text in the editor gets deleted while the cursor is still in the commit message box.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
I can't seem to reproduce. Does it reproduce with `code --disable-extensions`?

**Comment by nvmkpk** [comment]
It appears to be due to 'Visual Studio Keymap' extension. If I disable this extension it does not happen.

**Comment by nvmkpk** [comment]
And it appears it is already logged in its repository.

**Comment by joaomoreno** [comment]
Thanks.
