### ISSUE TITLE
VS Code reopens the same project upon launch instead of the latest

### ISSUE THREAD

**Issue by valerianb** [Microsoft/vscode#32964]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-docker|Pet|0.0.16
jshint|dba|0.10.15
mssql|ms-|1.1.0
Ruby|reb|0.15.0
cucumber|ste|0.9.6

---

Steps to Reproduce:

Since the latest update, vscode keeps reopening the same project upon launch.

I close the project, open another one. CMD + Q, relaunch and it's the old project that opens.
Clearing the recently opened doesn't solve the issue.

Restore windows is set to one:
`"window.restoreWindows": "one"`

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by valerianb** [comment]
The insiders build works as expected

**Comment by bpasero** [comment]
@valerianb does the project have dirty files that restore on startup?

**Comment by valerianb** [comment]
There were two uncommitted npm debug log files in that project... removing those files solved the issue.
Thank you for your help !

**Comment by bpasero** [comment]
Ok, I am still puzzled why it happened though. Closing until further info can be provided.
