### ISSUE TITLE
Break Points do not clear for Powershell

### ISSUE THREAD

**Issue by Steve-Lewis** [Microsoft/vscode#32968]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
rest-client|hum|0.15.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
team|ms-|1.122.0
html-css-class-completion|Zig|1.8.1

---

Steps to Reproduce:

1. Open a powershell file
2. Set a breakpoint by clicking left of the number
3. Hit F5
4. Run your powershell
5. You should break on the breakpoint set in step 2
6. Step over until the code completed
7. Clear the breakpoint you set in step 2 the same way you set it
8. Run your powershell
9. Breakpoint hits again

Note:
If you type - Get-PSBreakPoint it will output the breakpoints you set in step 2 and tried to clear in Step 7. 
Type Get-PSBreakPoint | Remove-PsBreakPoint to remove the break points and you should be able to run the code again without it stopping.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#1037
