### ISSUE TITLE
VSCode URI module's driveLetterPath regex is incorrect

### ISSUE THREAD

**Issue by gatesn** [Microsoft/vscode#32961]
https://github.com/Microsoft/vscode-uri/blob/e59cab84f5df6265aed18ae5f43552d3eef13bb9/lib/index.ts#L56

The regex is `[a-zA-z]`, the `A-z` part will match ascii characters such as `^` and `_`.

This was spotted by @deathaxe when porting the module over for use in the Python Language Server https://github.com/palantir/python-language-server/pull/99/files

**Comment by Tyriar** [comment]
@gatesn nice find :smiley:

**Comment by jrieken** [comment]
Nice!

**Comment by Tyriar** [comment]
Verified via code review
