### ISSUE TITLE
Format on Save is laggy

### ISSUE THREAD

**Issue by Swailem95** [Microsoft/vscode#32979]
- VSCode Version: 1.15.1
- OS Version: Win 10

Steps to Reproduce:

1. Set "editor.formatOnSave" to true.
2. Save any file. 

Reproduces without extensions: Yes

You'll notice vscode just sort of hangs for ~2 seconds after a file is saved.

**Comment by Tyriar** [comment]
@Swailem95 what language is the file?

**Comment by Swailem95** [comment]
@Tyriar JS

**Comment by mjbvz** [comment]
A few questions to help investigate:

1. Are the files stored on a network drive or other remote location?
1. Does this happen for all files and any folder you open, or only sometimes?
1. If you run `Developer: Toggle Developer Tools`, do you see any error messages in the developer console?

**Comment by Swailem95** [comment]
@mjbvz 

1. No. Stored on my PC.
2. I believe it only happens sometimes. It seems to only happen when my current project has a lot of files or when the file I'm working on is long and/or needs a lot of formatting. 
3. Yes, there is one error but it only comes up once and not on every save. 

> javascript-snippet-0.2.1]: Unknown language in `contributes.snippets.language`. Provided value: vue
t.$localShowMessage @ mainThreadExtensionService.ts:117
