### ISSUE TITLE
emmet.showExpandedAbbreviation: false doesn't remove emmet from autocomplete

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#32974]
i hate this stupid emmet feature in my autocomplete, and there is no way to disable it:

![image](https://user-images.githubusercontent.com/937933/29580536-5679be4e-8744-11e7-8928-9e87ad18d208.png)

![image](https://user-images.githubusercontent.com/937933/29580575-7b1a3576-8744-11e7-9d4a-4f5bc7092fee.png)

**Comment by ramya-rao-a** [comment]
That's because you set `emmet.showAbbreviationSuggestions` to `false` instead of setting `emmet.showExpandedAbbreviation` to `false`

There is a difference between the 2

See the docs on [Emmet settings](https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration)

**Comment by ramya-rao-a** [comment]
Also, I am guessing you are working on a jsx/tsx file?

We are aware that emmet suggestions can be annoying in jsx/tsx file. We have a separate issue tracking that in case you are interested. #32647
