### ISSUE TITLE
[Ubuntu] Toggling dev tools

### ISSUE THREAD

**Issue by epatpol** [Microsoft/vscode#32975]
- VSCode Version: 1.14.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Add a custom keyboard shortcut to "workbench.action.toggleDevTools" i.e Ctrl+Shift+I (seems to also happen with other shortcuts)
2. Use the shortcut (Ctrl+Shift+I) to open the dev tools
3. Close the dev tools with the shortcut again
4. Repeat steps 2 and 3
5. VSCode crashes

I then noticed that even without the shortcut, just opening/closing a few times with the menu makes it crash

Reproduces without extensions: Yes

I have Debugger for Chrome/Auto-open Markdown Preview and TSLint installed. I haven't tried uninstalling them but I disabled all/reloaded vscode and I still have the issue.

Let me know if you need any more information! Thanks.

**Comment by Tyriar** [comment]
Could you try reproduce this on the [Insiders build](https://code.visualstudio.com/insiders)? The backing version of Electron changed there.

**Comment by epatpol** [comment]
@Tyriar Yep no problem.

I just tested it with the latest Insiders build and it crashed at the 3rd toggling (with no custom shortcut and no extensions installed).

**Comment by kzhui125** [comment]
https://github.com/Microsoft/vscode/issues/5628

**Comment by epatpol** [comment]
@kzhui125 my bad! I actually looked (probably too fast) to see if it was already reported. I'll close this one and follow the two other bugs (the one in VScode and the one in Electron).
