### ISSUE TITLE
"No Updates Available" notification appears every few minutes

### ISSUE THREAD

**Issue by chyndman** [Microsoft/vscode#32977]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
copy-markdown-as-html|jer|1.0.0
cpptools|ms-|0.12.3

---

Steps to Reproduce:

1. Work, hack, write code, work, hack, write code for a few minutes....
2. Notification appears saying "There are no updates currently available"
3. Goto 1

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Does this reproduce with `code --disable-extensions`?
