### ISSUE TITLE
Search and replace on a very large file causes VS Code to crash

### ISSUE THREAD

**Issue by mairaw** [Microsoft/vscode#32976]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a very large file (mine was a 115MB yml file)
2. CTRL + H
3. Type the string to search for and the replacement (999+ instances were found)
4. Choose Replace All
5. VS Code crashes

![image](https://user-images.githubusercontent.com/12971179/29581460-2e561c48-872e-11e7-9189-e6f1aa13e8d9.png)

I I replace just one instance, it doesn't crash.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@mairaw I wonder if we are running into an OOM situation. Does this work as expected when using VSCode 64bit ?

**Comment by mairaw** [comment]
Didn't realize there was a response here earlier. Just to close the loop, I'm now running the VS Code 64-bit version and I'm no longer having this issue. Thanks!
