### ISSUE TITLE
I can't generate any output, any solution?

### ISSUE THREAD

**Issue by luigivendetta** [Microsoft/vscode#32972]
file: 'file:///c%3A/Users/lenovo/Documents/Hello.cpp'
severity: 'Info'
message: 'Include file not found in browse.path.'
at: '1,1'
source: ''
![cpp](https://user-images.githubusercontent.com/10692823/29579664-16e0332e-8791-11e7-8514-bcc20da2afcb.jpg)

**Comment by Tyriar** [comment]
Looks like an issue with the C++ extension, please create an issue here https://github.com/Microsoft/vscode-cpptools
