### ISSUE TITLE
Linux: VS Code doesn't respect DISPLAY environment variable

### ISSUE THREAD

**Issue by d-fan** [Microsoft/vscode#32983]
- VSCode Version: 1.14.2
- OS Version: Debian + Linux 4.9.30

Steps to Reproduce:

1. Launch vscode in an X session with DISPLAY=:0
2. Start a second X session on DISPLAY=:1
3. Try to launch vscode on the second X session

vscode does not open on DISPLAY=:1. Instead, the running instance on DISPLAY=:0 is raised/activated.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
@d-fan could you try using Electron quick start https://github.com/electron/electron#quick-start ? I suspect it's an upstream problem.
