### ISSUE TITLE
Multiline Selection on click

### ISSUE THREAD

**Issue by Camos17** [Microsoft/vscode#32984]
- VSCode Version: 1.15.1
- OS Version: Ubuntu 16.4

Steps to Reproduce:

1 . ALT + click on multiple lines is not working.

Reproduces without extensions: Yes

**Comment by antony-chopin** [comment]
Not sure it will help, but i remember, that in new release the multiline trigger key is now CTRL (alike Sublime Text). Furthermore, now you can change it in user settings.

**Comment by Camos17** [comment]
Thank you, it was indeed a settings issue. Nevertheless, the linux version has 'Alt' as default but it does not work. I had to set the property "editor.multiCursorModifier" to "ctrlCmd".
