### ISSUE TITLE
VSCode fights fixing mismatched parens

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/vscode#32988]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
bazel-code|Dev|0.1.8
calculate|aca|1.1.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.0
tslint|eg2|0.17.0
git-project-manager|fel|1.3.2
auto-rename-tag|for|0.0.14
docthis|joe|0.4.8
contextualduplicate|laf|0.2.0
debugger-for-chrome|msj|3.1.8
vscode-subword-navigation|ow|1.1.5
Align|ste|0.2.0
rewrap|stk|1.4.2
vscode-import-cost|wix|2.5.0
clang-format|xav|1.5.0
vscode-proto3|zxh|0.1.2

(3 theme extensions excluded)
---

## Steps to Reproduce:

Given this code:
```typescript
if ((([].includes()) {

}
```
put your cursor before one of the `)`s and hit the `)` key.

## Expected result
A `)` is inserted

## Actual result
VSCode moves the cursor to the right each time you hit `)`, but doesn't insert a paren until the cursor is at the end of the closing parens.

**Comment by Tyriar** [comment]
I believe this is as designed. I have this feature disabled by having this in my settings:

```js
"editor.autoClosingBrackets": false,
```

**Comment by appsforartists** [comment]
I'm skeptical of a design that tells me there's a syntax error (by underlining the mismatch in red) and then ignores when I try to fix it.  If there are already matched parens and it skips adding a new one, that seems "by design":

```typescript
if () {
```
typing ) in between the parens there can be safely ignored

but when they are mismatched, you are actively fighting me fixing an error, and that feels wrong.

**Comment by Tyriar** [comment]
These are 2 completely different systems that know nothing about each other, one is an extenison (tslint/eslint) providing errors based on a CLI. The other is a bracket matching feature which is built in the core which you can control in settings, the extension cannot communicate with the bracket matching as that's how the extension architecture works. Also even if they could, it would be a little weird as typing `)` would then behave inconsistently depending on whether there was a nearly error.

I suggest turning off the setting if it bugs you (as it does me), or just remember that the bracket matching feature is not aware of tslint.
