### ISSUE TITLE
Text replacement support on macOS

### ISSUE THREAD

**Issue by kevinvavelin** [Microsoft/vscode#32985]
- VSCode Version: 1.15.1
- OS Version: 10.12.6

The key you type on keyboard is always shown but on macOS you can long press a key to see accent (in French at least, I don't know for other languages), giving a thing like that : eé or aà

Steps to Reproduce:

1. Stay pressed a keyboard touch
2. Replace with accent

Reproduces without extensions: Yes

**Comment by kevinvavelin** [comment]
Any news about it ? I think I'm gonna work on it, can I create a branch and work for a fix ?

**Comment by alexandrudima** [comment]
This used to work and it appears it has regressed again with our upgrade to a newer version of Chromium

**Comment by alexandrudima** [comment]
Fixed via f37884c28c93fe83b33ceb9f9da0a02e49571fcc
