### ISSUE TITLE
WordWrapping is ON regardless of User Settings

### ISSUE THREAD

**Issue by Zeddicus414ce** [Microsoft/vscode#32992]
The problem is that files with lines over 10000 characters are wordWrapped regardless of the user setting.

Here is a file that demonstrates word wrapping being turned on regardless of settings:
[test_wrapping.txt](https://github.com/Microsoft/vscode/files/1243731/test_wrapping.txt)

Steps to Reproduce:

1. Ensure "editor.wordWrap": "off"
2. Fill up any single line up to column 10001.
3. Switch to a different file and then back.
4. The file will show wrapped text regardless of the editor.wordWrap setting.
Note: It's not just the long lines getting wrapped either. It appears to be turned on for the entire file. 

Reproduces without extensions: Yes, this was reproduced without extensions.

---

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
python|don|0.7.0
xml|Dot|1.9.2
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
vscode-code-outline|pat|0.0.8
vscode-icons|rob|7.12.0

**Comment by alexandrudima** [comment]
If you search for `wordWrap` in user settings, by default, VS Code ships with:
```
"editor.wordWrap": "off"
...
"[markdown]":  {
    "editor.wordWrap": "on",
    ...
}
```
which means, **out of the box, word wrapping is enabled for markdown**.

**When opening a file that is dominated by long lines, VSCode will also word wrap**. e.g. try opening `jquery-3.2.1.min`. In such cases we show a button at the top of the editor:

![image](https://user-images.githubusercontent.com/5047891/33121223-706033d8-cf74-11e7-8455-c9d063b4a723.png)

**Comment by Zeddicus414ce** [comment]
Thank you very much for following up on this ticket and for making a wonderful text editor! Knowing that I can modify the behavior manually after opening is really helpful. 

As a note: As far as I can tell, the markdown WordWrap setting does not impact the behavior of my test file. I'm assuming that you were posting about the setting to be thorough in the conversation about WordWrap, rather than as a potential solution to the long line WordWrap behavior.
