### ISSUE TITLE
focus opened file when opened from Explorer Side Bar

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#32999]
Steps to Reproduce:

1. Ctrl+Shift+E to open Explorer Side Bar
2. Click on a file in the Explorer Side Bar, thus opening it or a preview of it
3. press some letter keys. the typed keys do not appear in the opened file, because the opened file isn't focused
4. Ctrl+1 to focus the file, and then type again; now text will appear.

Expected behavior: file should be focused without needing Ctrl+1

**Comment by Tyriar** [comment]
The opposite could also be considered an issue.

@bpasero do you recall the decisions behind focus handling in the explorer? enter will open and focus, clicking will open and retain focus.

**Comment by bpasero** [comment]
We do not move focus to the editor because otherwise if you click into the explorer with the mouse you could never use the keyboard to navigate in the file explorer.
