### ISSUE TITLE
Powershell integrated terminal "Execute Selection" (F8) doesn't work anymore.

### ISSUE THREAD

**Issue by brandubh** [Microsoft/vscode#33009]
Hitting F8 does nothing.
Cmdlet parameters autocompletion doesn't work in editor anymore, but it works in terminal window.

- VSCode Version: Code - Insiders 1.16.0-insider (1c6f2f9a8012565adcc50616c3aa90cb444e8797, 2017-08-23T05:23:27.861Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.2.9
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.10.0
python|don|0.7.0
xml|Dot|1.9.2
git-project-manager|fel|1.3.2
gitattributes|has|0.4.1
ruby-linter|hoo|1.0.0
Ionide-Paket|Ion|1.7.3
github-pr|jas|1.0.0
azure-functions-tools|joh|0.3.0
vscode-github|Kni|0.18.1
MagicPython|mag|1.0.12
start-git-bash|McC|1.2.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
azurerm-vscode-tools|msa|0.3.6
vscode-docker|Pet|0.0.16
Ruby|reb|0.15.0
arm-snippets|sam|1.0.1
python|tht|0.2.3
gitflow|vec|1.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please move this to the powershell repo https://github.com/PowerShell/vscode-powershell

**Comment by brandubh** [comment]
done! thx.
