### ISSUE TITLE
Does not perform "Go to Definition", "Peek definition" and so on.

### ISSUE THREAD

**Issue by VulcanMaster** [Microsoft/vscode#33008]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open Visual Studio Code
2. Locate on some function using in code, press F12 or left mouse click and select "Go To Definition". The result - studio does nothing.

**Comment by xanderberkein** [comment]
Not sure if it's the same usecase for you, but I noticed some issues with the Python extension for vscode, where IntelliSense stopped working in my Python code. A quick uninstall and reinstall of the Python extension fixed the problem however.

**Comment by alexandrudima** [comment]
@VulcanMaster what programming language are you using ? What extensions do you have installed ?

**Comment by VulcanMaster** [comment]
Hi Alexandr. Currently this is working for me. There was an issue for some version, but now is ok. However that was TypeScript with the ReactJS.
