### ISSUE TITLE
The .NET Core debugger cannot be installed. The debugger requires macOS 10.12 (Sierra) or newer.

### ISSUE THREAD

**Issue by HawkenKing** [Microsoft/vscode#33007]
Siera will probably not be installed on this machine anytime soon as other software I use for work is not compatible with it.

So what now?

**Comment by weinand** [comment]
Please ask the authors of the .net core debugger as this is not a bultin extension of VS Code.

**Comment by HawkenKing** [comment]
is there a way to mute this message? it comes up on start every time

**Comment by weinand** [comment]
@HawkenKing no one from the .net Core debugger will see your question if you continue to ask here.

**Comment by HawkenKing** [comment]
can you point me in the right direction? This isn't part of VScode?

**Comment by weinand** [comment]
@HawkenKing the .net Core debugger is a separate extension that you have installed from the Marketplace: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Go to that page and under "Resource" click on the Issues link and file your questions and issues there.
