### ISSUE TITLE
Editor scrolls twice

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33006]
See attach gif, the references of the first file reveal smoothly, those of file two and three reveal, pause, and then reveal again. 

![aug-23-2017 09-42-28](https://user-images.githubusercontent.com/1794099/29604354-83b6b2d8-87e7-11e7-957b-fe32d6bceda2.gif)

**Comment by yume-chan** [comment]
Seems caused by the newly added smooth scrolling.

When CodeLens info appears, the editor will try to scroll again to keep the originally displayed line in-screen, but with smooth scrolling it's observable now.

**Comment by alexandrudima** [comment]
Fixed via e070afceabc88e57190697c9a79dc3ab3a98d3d5
