### ISSUE TITLE
Unexpected behavior of conditional break

### ISSUE THREAD

**Issue by prandelicious** [Microsoft/vscode#33001]
- VSCode Version: 1.16.0-insider
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. Create a Python for loop using enumerate():
```
values = ['Testing1', 'Testing2', 'Testing3']
for index, value in enumerate(values):
    test = index
    print(test, value)
```
2. Create a conditional break in line after `for index...` with value `index = 1`. Expected behavior is to break when the value of `index` is equal to 1. It breaks/stops at `index = 0`

**Comment by weinand** [comment]
Please move this issue to the Python extension you are using. You can use this tool: https://github-issue-mover.appspot.com

**Comment by prandelicious** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1175
