### ISSUE TITLE
Commit should display warning if there are unsaved files in the project

### ISSUE THREAD

**Issue by jrysig** [Microsoft/vscode#33004]
I often forget to save some files before SCM commit, it would be great to receive warning. Maybe it should be an optional feature.

**Comment by joaomoreno** [comment]
There isn't any current API which lets us do this. cc @jrieken

**Comment by jrieken** [comment]
Well, you could call [`saveAll`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4796). Not exactly a warning but it will do the job

**Comment by rkeithhill** [comment]
OMG yes!  I do this way too often.  It would help if VSCode used the same "Save All" shortcut that every other app on Windows uses (ctrl+shift+s).  Still, this seems like a "no brainer" kind of warning.  Heck I'd be fine if were opt-in just as long as I could configure VSCode to warn me.

**Comment by jrieken** [comment]
> There isn't any current API which lets us do this. cc @jrieken

Actually not so sure about that. You can loop over the array of text document and check the `isDirty`-flag. Won't that do it @joaomoreno ?

**Comment by joaomoreno** [comment]
Isn't that array just the _visible_ ones? You can have unsaved documents that won't appear in that array right?

**Comment by jrieken** [comment]
Nope, that is all open documents, the visible once are for the editors, so no tabs

**Comment by pradeepmurugesan** [comment]
@joaomoreno & @jrieken  Looks like the window.visibleTextEditors is nothing but the file that is the user is currently viewing.

If I split the screen into 2 then I get the value 2 else its always 1 irrespective of the number of tabs.
 Kindly see the screen shot and let me know if I am looking at the wrong parameter under window. 

![screen shot 2017-10-13 at 17 58 40](https://user-images.githubusercontent.com/528317/31555215-77fe2152-b040-11e7-8354-e8b30adfd155.png)

**Comment by jrieken** [comment]
Yeah, don't look at editor but at documents, e.g. `vscode.workspace.textDocuments`

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/36364

**Comment by bpasero** [comment]
Does not work for me:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/35677025-61c35aa0-074e-11e8-86a1-a4ac5da5493f.gif)

**Comment by joaomoreno** [comment]
@bpasero Unfortunately this had to go behind a feature flag: `git.promptToSaveFilesBeforeCommit`. I had to disable it by default due to the smoketests. Please verify setting it to true.

**Comment by bpasero** [comment]
@joaomoreno oh ok, I was searching for a setting but was looking for "warning" and was not finding it by that.
