### ISSUE TITLE
Cmd+Click to follow link does not work with multiple lines

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#33005]
- VSCode Version: 1.15.1 (1.15.1) 41abd21afdf7424c89319ee7cb0445cc6f376959
- OS Version: macOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Open an integrated terminal
2. Write a really long text with a link that span into multiple lines
3. Try to `Cmd+Click` / `Ctrl+Click` the link
4. Link is opened but with incomplete URL

Reproduces without extensions: Yes

<img width="1082" alt="screen shot 2560-08-23 at 14 13 27" src="https://user-images.githubusercontent.com/1087399/29603314-ed0a9cd8-880d-11e7-9bb4-c542f63b55ec.png">

This one goes to `https://www.google.com/some` instead of `https://www.google.com/sometext`
<img width="1104" alt="screen shot 2560-08-23 at 14 22 29" src="https://user-images.githubusercontent.com/1087399/29603510-9fd0bf64-880e-11e7-8677-cc221eec9d20.png">

**Comment by martellaj** [comment]
Is there any update with this issue? It's been around for a while (definitely before this issue was opened), and it's a pain-point for sure.

**Comment by elmariofredo** [comment]
same here but in Version 1.17.0 (1.17.0) be377c0faf7574a59f84940f593a6849f12e4de7

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/24

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746
