### ISSUE TITLE
Indentation error when I pasting blocks of code in editor.

### ISSUE THREAD

**Issue by DoranYun** [Microsoft/vscode#33011]
- VSCode Version: 1.15.1
- OS Version: mac os 10.12.6

Steps to Reproduce:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16359169/29606694-9d1691be-8821-11e7-9ffc-dee11134d5dd.gif)

**Comment by rebornix** [comment]
![33011](https://user-images.githubusercontent.com/876920/45786321-cbde7b00-bc24-11e8-92b1-21c3c9bf2a8f.gif)

This issue was already fixed.
