### ISSUE TITLE
Feature request: allow skipFiles: "<eval>/*" pattern

### ISSUE THREAD

**Issue by guybedford** [Microsoft/vscode#33018]
- VSCode Version: 1.15.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Set `"skipFiles": ["node_modules/**", "<node_internals>/*", "<eval>/*"]` in `launch.json`
2. Use debugger to debug TypeScript or JavaScript
3. Eval scripts still stop the debugger

It would be nice if `<eval>/*` could be supported as a skip pattern just like `<node_internals>/*`. Apologies if I'm posting this in the wrong place!

**Comment by weinand** [comment]
@roblourens since the legacy debugger keeps eval scripts under "<node_internals>", it already supports to skip them.

**Comment by roblourens** [comment]
Will track this with https://github.com/Microsoft/vscode/issues/31537
