### ISSUE TITLE
tab is not work in jsx 

### ISSUE THREAD

**Issue by unsignedlinux** [Microsoft/vscode#33010]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
docthis|joe|0.4.8
color-highlight|nau|2.3.0
vscode-icons|rob|7.12.0
jsx|Twe|0.0.1
vscode-jss-snippets|vis|0.2.2
ReactSnippets|xab|1.4.0
html-css-class-completion|Zig|1.8.1

(2 theme extensions excluded)

---

Steps to Reproduce:

last day,i update my vscode ,when i write html in js file ,i found that the tab is not work, it just give 2 space,not complete the html tag,  anyone met this problem? please help me...

Reproduces without extensions: Yes/No

**Comment by TheHandsomeCoder** [comment]
I think this was disabled in the latest release. You need to rebind emmet autocomplete to a new key. `tab` is only for indentation now. [Release Notes Here](https://code.visualstudio.com/updates/v1_15#_auto-indentation)

**Comment by ramya-rao-a** [comment]
Set `emmet.triggerExpansionOnTab` to `true` to expand Emmet abbreviations and snippet by pressing tab.

There have been quite a few changes to Emmet in the July release.
Please read the [Release Notes on Emmet](https://code.visualstudio.com/updates/v1_15#_emmet-20) or [Emmet 2.0 blog](http://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) and the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet)

**Comment by unsignedlinux** [comment]
@ramya-rao-a oh! thank you!

**Comment by ramya-rao-a** [comment]
No problem @unsignedlinux, Happy Coding!
