### ISSUE TITLE
"Submit a bug" should include the command line and remove extensions if launched with --disable-extensions

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#33017]
The "report a bug" button opens a window with all the extensions filled in, which is great. But if you open code with all extensions disabled there is no indication of this in the pregenerated text.

It seems reasonable to not include the list of extensions at all and just say "Code was launched with all extensions disabled".

In addition it'd make sense I think to include all the command line options passed.

**Comment by ihalip** [comment]
What about adding another column to the table describing if each extension is enabled or not? Like this:

Extension|Author|Version|Enabled
----|----|----|----
e1|au1|1.0|Yes
e2|au2|1.1|No

**Comment by bpasero** [comment]
Pushed the portion of https://github.com/Microsoft/vscode/pull/33225 that will not show the extensions if they are all disabled.

**Comment by joaomoreno** [comment]
Improvements to Submit a bug are coming this milestone, closing this as a dupe.
