### ISSUE TITLE
Emmet update ruined my experience

### ISSUE THREAD

**Issue by yakovd33** [Microsoft/vscode#33013]
I used to be, until last update on July, that I used Emmet in the most elegant way - writing my emmet snippets and whenever I want after that I pressed the tab key, and as long as the text cursor was after the Emmet, it worked.
After the update, whenever I want to Emmet I need to check if an abbreviation is showing(which it isn't sometimes) and then press tab.

So certain behaviors like going to css file, writing bgc and pressing tab or simply HTML .class`ing is ruind for me.

**Comment by yakovd33** [comment]
I could just write something and press enter and it would have closed a tag like that for me.

**Comment by ramya-rao-a** [comment]
Set `emmet.triggerExpansionOnTab` to `true` to expand Emmet abbreviations and snippet by pressing tab.

There have been quite a few changes to Emmet in the July release.
Please read the [Emmet 2.0 blog](http://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) and the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet)

If there are abbreviations/snippets that still don't work, please drop a comment here and we will look into it

**Comment by yakovd33** [comment]
I thought it was already set to true.
Thank you @ramya-rao-a

**Comment by ramya-rao-a** [comment]
It was set to true by default before VS Code 1.15.0
We changed the default due to the issues it brought up for non Emmet users. You can read more on this in the links above
