### ISSUE TITLE
the spinach coloured extension tips hurt my eyes...

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3301]
![2016-02-23 12-09-32](https://cloud.githubusercontent.com/assets/1898161/13249767/70e82666-da26-11e5-85ee-7f6acdffe6cb.png)

**Comment by joaomoreno** [comment]
:+1:

**Comment by joaomoreno** [comment]
ping @jrieken

**Comment by joaomoreno** [comment]
Push the code, or don't close the issue.

**Comment by bgashler1** [comment]
@joaomoreno Just pushed all the code to master from my fork.

**Comment by joaomoreno** [comment]
:+1:
