### ISSUE TITLE
VS Code Insiders crashes on every exit on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33016]
* (with Electron 1.7.5)
* open VS Code
* close VS Code
* Observe in process explorer that there is a crash and the crash is presented in the Windows Event Log.

**Comment by joaomoreno** [comment]
I could repro this in Windows:

- 1.7.5 x64
- 1.7.5 ia32
- 1.7.4 x64

**Comment by alexandrudima** [comment]
Electron 1.7.5:

![image](https://user-images.githubusercontent.com/5047891/29608512-a7906462-87f4-11e7-8b9b-b143ddf08aa9.png)

Sometimes the greyed out process (marked Suspended) never finishes and this blocks our update mechanism on Windows.

**Comment by bpasero** [comment]
Btw this is https://github.com/electron/electron/issues/10188

**Comment by bpasero** [comment]
I cannot reproduce in Electron 1.7.3. Unfortunately we need at least 1.7.4 for the fix to have `--debug-inspect` work in forked processes.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/33099

**Comment by nileshmali** [comment]
@bpasero This is fixed in https://github.com/electron/electron/releases/tag/v1.7.7
