### ISSUE TITLE
Side bar / Explorer shouldn't move scroll when navigating between files

### ISSUE THREAD

**Issue by Josema** [Microsoft/vscode#33026]
Sorry is not a bug. Is more a suggestion.

When navigating between files the Side Bar / Explorer reflect the current file that you are on highlighting this file on the list. That is perfect but is so annoying when moves the scroll to the position of the file. If the tree is huge this behavior makes you crazy. 

Sublime Text doesn't have this behavior.

**Comment by Tyriar** [comment]
You want to add this to your settings.json:

```js
"explorer.autoReveal": false
```

I can't live without it :wink: 

To compliment this I have this keybinding that allows me to jump to the current file in the tree:

```js
{ "key": "ctrl+0", "command": "workbench.files.action.showActiveFileInExplorer" },
```

**Comment by Josema** [comment]
Wow! Thank you! 😃
