### ISSUE TITLE
Unit test coverage for multi root configuration

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33021]
Unit test coverage for multi root configuration

**Comment by DonJayamanne** [comment]
@sandy081 will this be available in the October release.
I have some unit tests in the Python extension, and would like to ensure I implement the same/similar UI workflow as you would for vscode (node/typescript projects).

**Comment by sandy081** [comment]
@DonJayamanne Yes, Planning to do it in October. If not in November. But not sure how these are related and helpful to yours.

But, I would be also providing a sample of how to read/write configurations in MR workspace in our MR Workspace wiki - https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

**Comment by DonJayamanne** [comment]
@sandy081 oh, yes this is unit test *coverage*, just focused on the words unit test and assumed you'd be working on some UI related work in detecting unit tests in a multiroot env.

Please ignore my previous comment.
>>But not sure how these are related and helpful to yours.

Agreed

**Comment by sandy081** [comment]
Added good coverage during this milestone. But still not complete.
