### ISSUE TITLE
Integrated terminal fails to load PowerShell on macOS

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33022]
- VSCode Version: stable or insiders
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. make sure to have PowerShell on macOS (I use version v6.0.0-beta.5)
2. add setting: `"terminal.integrated.shell.osx": "/usr/local/bin/powershell",`
3. try to create a new Integrated Terminal

Observe: for a brief moment this error appears and then the terminal closes:

![2017-08-23_12-15-29](https://user-images.githubusercontent.com/1898161/29611182-e4ad2e9a-87fc-11e7-94fa-7feac0ee3835.png)

I had to record a screencast in order to be able to see the error message.
After that it became clear that the culprit is the default argument '-l' being passed to PowerShell.
With this setting `"terminal.integrated.shellArgs.osx": []` PowerShell starts up fine.

**Comment by Tyriar** [comment]
This is as designed, I'd rather not get in the business of conditionally ignoring `terminal.integrated.shellArgs.osx` or giving it a special value sometimes. Given that Powershell is now cross platform, maybe we can add a shell switcher like on Windows to help alleviate the problem.

**Comment by weinand** [comment]
Given that Powershell is now cross platform, why do we then pass an argument '-l' to PowerShell that is not cross platform?

**Comment by Tyriar** [comment]
Because the default for `terminal.integrated.shellArgs.osx` is `["-l"]` as Mac's run shells as login shells by default. I might add some documentation around using PowerShell on Mac to help this.
