### ISSUE TITLE
autoIndent screws with template strings

### ISSUE THREAD

**Issue by igl** [Microsoft/vscode#33025]
- VSCode Version: 1.15.1
- OS Version: OSX

Steps to Reproduce:

1. Create template string
2. Move any line over it (alt + down)

Reproduces without extensions:

Yes

Workaround:

`"editor.autoIndent": false`

Pic:

![autoindent](https://user-images.githubusercontent.com/293519/29612727-fad52708-8802-11e7-8f13-f4fa893f960f.png)

**Comment by rebornix** [comment]
We didn't cover template string in indentation rules, that's why it behaves strangely while moving around templates. I'd like to mark it as under-discussion for now as you can set `editor.autoIndent` to `false` to mitigate this issue.

**Comment by rebornix** [comment]
Duplicate of #19420.
