### ISSUE TITLE
Can't set typescript task and custom task together in tasks.json

### ISSUE THREAD

**Issue by Franziskus1988** [Microsoft/vscode#33024]
- VSCode Version: 1.15.1 x64
- OS Version: Windows 10 x64

Steps to Reproduce:
1. My tasks.json looks like:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    },
    {
      "taskName": "Karma Run",
      "type": "shell",
      "command": "karma start --browsers Chrome --reporters progress",
      "group": {
        "kind": "test",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "dedicated"
      }
    }
  ]
}
```

2. When I want to run build task. This message appears:
![image](https://user-images.githubusercontent.com/5774027/29611974-fedcb120-87ff-11e7-8fe6-2e4a97bcd895.png)

3. When I press Ctrl+Shift+R I only see this:
![image](https://user-images.githubusercontent.com/5774027/29612080-4a66dcce-8800-11e7-9af5-75b5dc5e17d5.png)

So it seems that it is not possible to have a tsc task together with a custom task in tasks.json and I doubt that this is the desired behavior. 

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This got fixed for the next release. Please note that the workspace needs to have a tsconfig.json file in it to make the typescript build task work.

<img width="668" alt="capture" src="https://user-images.githubusercontent.com/1931590/29636207-0fe93a9c-8850-11e7-8248-fecf608fee27.png">
