### ISSUE TITLE
Code.exe lost its icon

### ISSUE THREAD

**Issue by wclssdn** [Microsoft/vscode#33032]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. i don't know why..

image: http://7xsne5.com1.z0.glb.clouddn.com/vscode-no-icon.png

**Comment by wclssdn** [comment]
on taskbar http://7xsne5.com1.z0.glb.clouddn.com/vscode-no-icon2.png

**Comment by joaomoreno** [comment]
I have no idea why this would happen on your machine. Can you reinstall VS Code?

**Comment by wclssdn** [comment]
I have try several times... after reinstall icon is normal, but soon(sometimes, after some days) .. it lost...
