### ISSUE TITLE
Shell script syntax highlighting error

### ISSUE THREAD

**Issue by fmercier** [Microsoft/vscode#33034]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
xml|Dot|1.9.2
tortoise-svn|fan|0.1.1
rest-client|hum|0.15.2
AWK|lug|0.0.2
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
partial-diff|ryu|0.3.1

---

Steps to Reproduce:

1. Create a new file 
2. Select Language shell script (Bash)
3. Enter the snippet
```
#!/bin/bash
CONT=`cat <<-END1 | wc -l
    line1
    line2
END1`
echo "$CONT"
```
4.- The last lime must be highlighted as a new statement

Reproduces without extensions: Yes

**Comment by LaurentTreguier** [comment]
I don't know if this is really related, but a similar problem arises with herestrings (`<<<`) :
```bash
format() {
    name=$(awk '{print tolower($0)}' <<< $1)
    name=$(sed 's/\s+//g;s/[^a-z]//g'<<< $name)
    echo $name
}
```
With this snippet, the 2 last lines of the function are not highlighted properly.
- VSCode Version: VSCode 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959)
- OS Version: Fedora 26 x86_64

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/29924025-d985da66-8e5b-11e7-949b-9e38b48a446f.png)

**Comment by LaurentTreguier** [comment]
Why was this closed ? Has this been fixed ?...
