### ISSUE TITLE
Feature Request: Please allow me to zoom in on the File Browser section of the editor by itself, without having to zoom in the whole window.

### ISSUE THREAD

**Issue by Adondriel** [Microsoft/vscode#33031]
I'de like to be able to keep this zoom level of the file browser (to make it easier to click files, because my mouse/hand has a tendency to go just a couple pixels too high, causing me to open the wrong file. But, I don't need it to zoom in on the text editor area, it would be nice to have separate zoom values for each of these, if possible.

![image](https://user-images.githubusercontent.com/1113496/29621302-59851c32-87ee-11e7-9a92-0dc8c1e82ae4.png)

**Comment by Tyriar** [comment]
You can do this by changing your `"editor.fontSize"` setting.
