### ISSUE TITLE
Mismatched types for "editor.acceptSuggestionOnEnter" user setting

### ISSUE THREAD

**Issue by ArcticLight** [Microsoft/vscode#33033]
editor.acceptSuggestionOnEnter used to be a boolean, but now expects a string, and this change broke my UserSettings and wasn't really documented anywhere that I could find.

Suggestion: `true`/`false` map to `"on"` and `"off"`, or update [the Intellisense documentation (https://code.visualstudio.com/docs/editor/intellisense)](https://code.visualstudio.com/docs/editor/intellisense) with the new options.

I'm not entirely sure whether this qualifies as a simple documentation issue or a real bug, but I'm reporting it here because I don't know where else to do so.

- VSCode Version: 1.14.1
- OS Version: Ubuntu 14.04LTS, last update 8/18/17

**Comment by jrieken** [comment]
Yeah, should have been automatically migrated. There is code check for it, but maybe some sanitise happens earlier...

**Comment by jrieken** [comment]
Fix the auto migration of things to ensure true/false still work. Passing on you @gregvanl for an update the documentation. The values for `acceptSuggestionOnEnter` are 'on', 'smart', and 'off'

**Comment by gregvanl** [comment]
Updated documentation with https://github.com/Microsoft/vscode-docs/commit/103f2925194eba45801687ab25dc225743888cc4
