### ISSUE TITLE
Multiple browser windows open occasionally

### ISSUE THREAD

**Issue by johnbirt** [Microsoft/vscode#33038]
- VSCode Version: Code - Insiders 1.16.0-insider (1c6f2f9a8012565adcc50616c3aa90cb444e8797, 2017-08-23T05:10:58.701Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
jshint|dba|0.10.15
vscode-icons|rob|7.12.0
open-in-browser|tec|1.1.0
vscode-preview-server|yui|0.7.0

vscode-preview-server works well apart from with certain pages,  2 will open in Chrome (default) and even when closed sometimes will re-load the page being worked on in VS. Doesn't seem to happen when using view in side panel just view in browser. May well have to do with pages where there is a JSCript timer that has run?

---

Steps to Reproduce:

1. Load page in browser with CTRL-SHIFT-L
2.Closing page

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You will need to create an issue against the extension. I'm guessing it's this one? https://github.com/YuichiNukiyama/vscode-preview-server
