### ISSUE TITLE
TSLint output window panel every time js file is opened

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#33036]
- VSCode Version: Code - Insiders 1.16.0-insider (1c6f2f9a8012565adcc50616c3aa90cb444e8797, 2017-08-23T05:10:58.701Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.2
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.5.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. open a js file.  for example, an AngularJS route file.
2. the "output" panel pops open (empty) for no apparent reason.

**Comment by Tyriar** [comment]
@dbaeumer might know more, please forward to the right person if not 😄

**Comment by egamma** [comment]
@smlombardi  I cannot reproduce this behaviour, when I open a .js with vscode-tslint installed. I'm using this setup https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests. 

- what is shown in the tslint output window?
- is anything shown in the developer console Help>Toggle Developer tools?
- what version of tslint are you using?

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#242
