### ISSUE TITLE
[Request] Allow a keybinding for "Maximize/Restore panel size" in the terminal panel.

### ISSUE THREAD

**Issue by oskarbero** [Microsoft/vscode#33040]
- VSCode Version: 1.15.1

[Feature request]
I would like to be able to bind a key shortcut to the "Maximize panel size" option in integrated terminal.
I like to glance over my test results without scrolling through the terminal and not having to click the maximize /restore button would make my life way easier. I could not find a keybind option in VS Code itself or any mention through google etc. 
The button in question:
![maximize_restore_panel](https://user-images.githubusercontent.com/6343126/29628922-098cc470-8805-11e7-9520-7dd43cd1ef84.PNG)

**Comment by Tyriar** [comment]
You will have to add your own. Here's mine:

```js
{ "key": "ctrl+shift+q",    "command": "workbench.action.toggleMaximizedPanel" },
```

See https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by oskarbero** [comment]
Thank you! Sorry to waste your time, I was looking for terminal specifically and could not for the life of me find it!

**Comment by Tyriar** [comment]
No problems 😃
