### ISSUE TITLE
Mark TS Extension Settings as Workspace or Folder for multiroot

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33048]
**Feature request**
Properly mark which TS extension settings are workspace settings vs folder settings

**Comment by sandy081** [comment]
@mjbvz What has to be verified here?

**Comment by mjbvz** [comment]
Any setting which applies to how the TS server operates should be a window settings instead of a resource setting. This includes:

- typescript.disableAutomaticTypeAcquisition
- typescript.npm
- typescript.check.npmIsInstalled

Just make sure these can only be put in the code-workspace settings and that you see the expected errors if you try putting them in a folder's settings

Also quickly scan through the other typescript and javascript settings and see if any that fit that description were overlooked.

**Comment by aeschli** [comment]
@mjbvz Looking ate [the code](https://github.com/Microsoft/vscode/blob/2534c2a07b5b98b4a81b2ba773fdcd4b655a6edb/extensions/typescript/package.json#L120), there are still many properties without a `scope` property.

I'd suggest to reopen the issue.

**Comment by mjbvz** [comment]
@aeschli Do they not default to folder scope otherwise? Or should an explicit scope be set on all of them?

**Comment by sandy081** [comment]
@mjbvz Defaults are `Window` scoped.

**Comment by aeschli** [comment]
I created #33674. Marking as verified.
