### ISSUE TITLE
Extremely Slow Mouse Scrolling when Updating Highlighted Selection

### ISSUE THREAD

**Issue by BobChao87** [Microsoft/vscode#33041]
Scroll drops to a crawl (less than one line per scroll "click") when also updating a highlight from the mouse. Scrolling speed is not affected when not actively updating a highlight area, including when a highlight exists on the screen. Scroll speed is not affected when updating a highlight area by using mouse position (i.e. side of the screen), indicating that this bug is related only to mouse scrolling, not to draw computations of updating the highlight.

- VSCode Version: Insiders 1.16.0-insiders (1c6f2f9a8012565adcc50616c3aa90cb444e8797)
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

1. Open any file.
2. Highlight some content with mouse
3. Continue to hold mouse button and attempt to scroll

Reproduces without extensions: Yes

Extension List (all disabled at once, issue still reproduces):
* Git Lens
* mssql
* TSLint
* vscode-icons

**Comment by elasti-liranm** [comment]
Also here.
vscode runs sedispatch in the background,also find in my Fedora
utilizing close to 200% of CPU usage.

**Comment by BobChao87** [comment]
Issue appears to have been resolved as of VS Code - Insiders 1.16.0-insider (8b942faaf).
