### ISSUE TITLE
Issue with powershell as default terminal and bash command.

### ISSUE THREAD

**Issue by Oscar-21** [Microsoft/vscode#33042]
In the PowerShell terminal, the command `bash` is weirdly inconsistent. It  will sometimes open the linux subsystem, other times it will invoke git bash. I have had this happen in several releases.

![image](https://user-images.githubusercontent.com/21151259/29633663-062043e2-8815-11e7-9ebd-6a4d60ea41e4.png)

**Comment by Tyriar** [comment]
I'm guessing this is something to do with your PATH being different each time. I suggest setting the path explicitly in your settings.json using the `terminal.integrated.shell.windows` settings.

**Comment by Tyriar** [comment]
You can also try this extension to support launching multiple terminal configs via a keybinding https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
