### ISSUE TITLE
Add git history

### ISSUE THREAD

**Issue by stephenbe** [Microsoft/vscode#33044]
Any plans to add git history in the core of vscode?

I know their is, but it's not the best because it's not part of the ui
https://github.com/DonJayamanne/gitHistoryVSCode

What would be cool if you can add it in a tabbed interface when you are looking at the git changes 

Something like this where you can switch easily switch from commit and git history
![github for windows](https://user-images.githubusercontent.com/3018441/29636531-f2cfddac-881e-11e7-9a7b-d82f122397c5.gif)

**Comment by joaomoreno** [comment]
#68
