### ISSUE TITLE
Color code file tabs by folder

### ISSUE THREAD

**Issue by kobenauf** [Microsoft/vscode#33043]
- VSCode Version: 1.16.0-insider

As a developer who loves the new ability to support multiple folders in a single workspace and who often has many files open from many folders, it would be nice to have a visual queue to identify which of my many open files come from which folders so I can more easily spot the files I'm interested in working on. 

**Acceptance criteria**
* For example, I'd like my AuthService folder as have a light green background, and the tabs of files opened from the AuthService folder should also be light green.
* The color would ideally be set in workspace settings or user settings.
* The color would ideally take a theme color or a manual hex or rgba color.  Setting transparency level (rgba) might be especially nice for this feature.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31308
