### ISSUE TITLE
Configure task runner should only open output if autodetection fails or provides output.

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3304]
#3159 
Configure task runner command reveals task output, it should not since there is no new output.

**Comment by joaomoreno** [comment]
:+1:

**Comment by seanmcbreen** [comment]
+1

**Comment by isidorn** [comment]
ping @dbaeumer so you are aware of the change

**Comment by dbaeumer** [comment]
Reopening and reverting the commit. The problem here is that if the autodetection fails output is shown in the console. Now the user is blind.

**Comment by dbaeumer** [comment]
Fixed.

**Comment by dbaeumer** [comment]
@isidorn let me know if you are more happy with the new implementation.

**Comment by isidorn** [comment]
@dbaeumer looks good to me
