### ISSUE TITLE
How do I export plug-in configurations?

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#33058]
Seemingly no direct export configuration plug-in configuration file. When you change a device and then re-install the time, to look at a look like a lot of trouble. Can I export plug-in configuration files, similar to package.json?

**Comment by iMahesh** [comment]
I guess you are talking about "User Settings"
![image](https://user-images.githubusercontent.com/19846657/29653165-97821c32-885d-11e7-80eb-18aa54dccac1.png)

If you are asking the same you can find the `settings.json` @ 

> C:\Users\`YOURNAME`\AppData\Roaming\Code\User

And you find a bunch of other files as well. I hope it'll help

**Comment by Tyriar** [comment]
@cw19931024 if what @iMahesh pointed out is not it, please explain in more detail. Ideally with screenshots 😃

**Comment by cw19931024** [comment]
In fact, I would like to express the ability to have a login function, to record all the personal configuration items, as well as the follow-up function? Used to migrate, it is not necessary to export settings.json to the new device.

**Comment by Tyriar** [comment]
@cw19931024 see https://github.com/Microsoft/vscode/issues/2743
