### ISSUE TITLE
node script file that extension name is '.njs' can't be debug，throw err：Cannot launch program setting the 'outFiles' attribute might help

### ISSUE THREAD

**Issue by purplestone** [Microsoft/vscode#33051]
- VSCode 1.15.1
- OS win7 x64
- Shell 1.6.6
- Render 56.0.2924.87
- Nodejs 7.4.0

launch.json:
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

Create a file name ： go.njs:
```
debugger;
console.log();
```

press F5 to debug throw: Cannot launch program ”xxx\js\go.njs“ setting the 'outFiles' attribute might help

But I rename that file extension name '.njs' to '.js', It works well.

**Comment by weinand** [comment]
I do not know the file extension "njs". Can you point me to a definition?

**Comment by purplestone** [comment]
In /Microsoft VS Code/resources/app/extensions/javascript/package.json
the js file extensions can be name:
        "extensions": [
          ".js",
          ".es6",
          ".jsx",
          ".mjs"
        ],

So I name my node script file to '*.njs', 
IDE should not restrict my script file extension name.

**Comment by MikeRalphson** [comment]
@purplestone note above the list of extensions includes `.mjs` not `.njs` (em, not en).

I'm not sure if renaming your module to `.mjs` will fix the debugger issue though, as I am getting the same error trying to debug a `.mjs` module in Node 9 nightly using the `--experimental-modules` runtimeArgs.

**Comment by MikeRalphson** [comment]
@weinand this looks to be an issue in https://github.com/microsoft/vscode-node-debug2

The javascript debugger only wants to debug files where

```js
            if (utils.isJavaScript(programPath)) {
```

is `true`. See line [467](https://github.com/Microsoft/vscode-node-debug2/blob/671dd3eb7089ee9c4959eb2da0db3447c618b967/src/nodeDebugAdapter.ts#L467)

This test is only satisfied if the `programPath` ends with `.js` **or** there is a specific node shebang string at the top of the file:

```js
const NODE_SHEBANG_MATCHER = new RegExp('#! */usr/bin/env +node');
//...
if (name.endsWith('.js')) {
        return true;
}
//...
if (NODE_SHEBANG_MATCHER.test(line)) {
```

Adding 

> #!/usr/bin/env node

to the top of the affected `.mjs` file allows it to be debugged.

The assumption seems to be that `.mjs` files will always generate `.js` source files (i.e. via babel etc), but this assumption is no longer true with native `.mjs` support in recent Node.js builds (even if this is currently behind a flag).

**Comment by JoseBalado** [comment]
Hi, I can not debug node.js modules with the `.mjs` extension unless I add `#!/usr/bin/env node` to the top of the module.
Tested with Node v8.5.0 and v8.6.0 using  `--experimental-modules` flag

Thanks for your solution @MikeRalphson

**Comment by weinand** [comment]
I've added the extensions ".js", ".es6", ".jsx", ".mjs" to the list of recognised JavaScript extensions.

**Comment by weinand** [comment]
Verify that you can debug a JavaScript program if the file extension is ".es6", ".jsx", ".mjs".

**Comment by JoseBalado** [comment]
@weinand It works with  ".mjs".
Thanks
