### ISSUE TITLE
Common html5 tags not recognized when tag_case is not lower

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33055]
- VSCode Version: 1.15.1
- OS Version: win7x64

-----------------------

The only value, that works fine is "lower":
div --> `<div></div>`
DIV --> `<div></div>`

```
"emmet.syntaxProfiles": {
  "html": {
    "tag_case": "lower"
  }
}
```

-----------------------

The "upper" value **doesn't see DIV**:
div --> `<DIV></DIV>`
DIV --> `nothing`

```
"emmet.syntaxProfiles": {
  "html": {
    "tag_case": "upper"
  }
}
```
-----------------------

The "asis", just as "upper" value **doesn't see DIV**:
div --> `<div></div>`
DIV --> `nothing`

```
"emmet.syntaxProfiles": {
  "html": {
    "tag_case": "asis"
  }
}
```

-----------------------
GIF:
![bugs on tag_case](https://user-images.githubusercontent.com/24613274/29649881-d7f73198-889f-11e7-85b0-95ee56bb00df.gif)

_Off topic. Does anybody know good software or online service that can easily convert videos into gifs, keep the optimal ratio quality/size?_

**Comment by ramya-rao-a** [comment]
abbreviations like ABCD>EFG work its only the common html5 tags when in upper case do not trigger the suggestions.

Will push the fix tomorrow and the Insiders for 25th Aug will have the fix.

Thanks for reporting!

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode-emmet-helper/commit/262554626607c07c01b514f888dd8d9bc8981f87.
