### ISSUE TITLE
Rename a file at the same time to switch the computer window，and then back to vscode, rename operation has been completed

### ISSUE THREAD

**Issue by lavyun** [Microsoft/vscode#33052]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
code-runner|for|0.7.0
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.4.2
intellij-idea-keybindings|k--|0.2.13
node-module-intellisense|lei|1.4.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
vetur|oct|0.9.5
open-in-browser|tec|1.1.0
vscode-js-console-utils|wht|0.7.0

---

Steps to Reproduce:

1.When I rename a file and switch the computer window (using cmd + tab) to browse other applications, and then back to vscode, rename operation has been completed, I have to re-rename. Is there any setting to solve? Thank you

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31600
