### ISSUE TITLE
Missing em Emmet abbreviation

### ISSUE THREAD

**Issue by mythz** [Microsoft/vscode#33057]
The latest update removed the emmet abbreviation for `<em>` tags. Does this need to be enabled in VS Code itself or is there a way we can add our own missing Emmet abbreviations?

**Comment by vvs** [comment]
@mythz You could provide your own emmet snippets via `snippets.json` file. Put it somewhere and specify `emmet.extensionsPath` in the settings to point to the folder where your `snippets.json` resides, and restart/reload the VS Code.

Here's a small example with `em` snippet added:
```
{
    "html": {
        "snippets": {
            "ull": "ul>li",
            "em": "em"
        }
    },
    "css": {
        "snippets": {
            "bs": "border: 1px solid ${1:red}"
        }
    }
}

```

**Comment by mythz** [comment]
@vvs Perfect, thx! I'm happy with this solution.

**Comment by mythz** [comment]
BTW surprised to see `<td>` and `<th>` missing as well. Why not include all standard html tags?

**Comment by vvs** [comment]
@mythz FWIF, `<td>` and `<th>` do work for me on VS Code - Insiders.

**Comment by ramya-rao-a** [comment]
@mythz We have a whitelist for common html5 tags which you can find here: https://github.com/Microsoft/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L20

`td` `th` were added recently and so are available in the Insiders (https://code.visualstudio.com/insiders)

If you find any missing, feel free to add them here: https://github.com/Microsoft/vscode-emmet-helper/blob/master/src/emmetHelper.ts send a PR.
