### ISSUE TITLE
Feature Request: Add "problems.exclude" setting

### ISSUE THREAD

**Issue by molovo** [microsoft/vscode#33063]
We have `files.exclude` which removes any ability to reference a file within the Workspace, as well as `search.exclude` to hide from search. In my case, I want to be able to view and search files within `vendor` directories, so I have not added them to either of the exclude settings, but as a result row upon row of issues flood the problems panel, which hide problems within my own code. It would be great to be able to exclude these directories only from appearing in the problems panel with a `problems.exclude` setting, which would still allow them to be used for search, go to definition and intellisense etc.

**Comment by roblourens** [comment]
This might make more sense as an extension-specific or language-specific setting. Not sure.

**Comment by molovo** [comment]
@roblourens the problem is, with lots of linter packages, in a field like web development where those cross multiple languages as well (html, css, js, back-end), you could have about 15-20 linters running on a single project. To exclude files from each of them individually would mean an awful lot of duplicated config.

**Comment by andremacola** [comment]
Agreed. I have a bunch CSS "problems" in folders that already in all .exclude options.
I did not find an option to remove these CSS problems.

**Comment by sandy081** [comment]
Related https://github.com/Microsoft/vscode/issues/22289
