### ISSUE TITLE
If we generate a non empty tasks.json it should not trigger intelisense

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3306]
#3159 

1. vscode workspace, delete `tasks.json`
2. command > configure tasks runner
3. a non empty `tasks.json` gets generated and we still trigger intelli-sense in some weird location
4. I would expect intelli-sense is not triggered in this scenario

**Comment by joaomoreno** [comment]
This is on purpose, related to #3305

**Comment by dbaeumer** [comment]
@isidorn the snippet story got replaced with the template story. Please verify that the new story is OK in this regard.
