### ISSUE TITLE
I am not able to debug its showing this error "Cannot find runtime 'node' on PATH. Make sure to have 'node' installed."

### ISSUE THREAD

**Issue by Rajazpandi** [Microsoft/vscode#33062]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
json-tools|eri|1.0.2
file-icons|fil|1.0.5
code-runner|for|0.7.0
search-node-modules|jas|1.1.1
debugger-for-chrome|msj|3.1.8
vscode-icons|rob|7.12.0
cucumber|ste|0.9.6
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Open the VS Code 
2. Press F5 for debug

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please open a command prompt and enter "node --version".
What is the result?
