### ISSUE TITLE
Truncate 'Open Recent' suggestions from left to right

### ISSUE THREAD

**Issue by SeamusConacher** [Microsoft/vscode#33068]
- VSCode Version: 1.15.1 (32 bit)
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

1. Open a folder with a long file path
2. Open another folder with a long file path that only differs at the end

If you have multiple recently opened folders that have long, mostly similar file paths, the current implementation of Open Recent will truncate from right to left; leaving you with multiple identical file paths and no way to tell which one is which. 

There are multiple possible solutions: 
-Truncating left to right starting with drive letter would work for my issue, but would make it impossible to tell which version of a file you are opening if you have multiple copies across different drives.
-Removing the middle of the path, showing the drive letter and the last few folder layers could be a better option.
-Allowing this setting to be configurable would prevent any fix breaking some workflows.
-Showing the full file path when a selection is highlighted/hovered over would at least allow you to know for certain which folder you are opening no matter what configuration you have.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@SeamusConacher are you talking about

![image](https://user-images.githubusercontent.com/900690/29743254-6ca55550-8a8e-11e7-8d77-c2866f59561e.png)

or

![image](https://user-images.githubusercontent.com/900690/29743256-72e866be-8a8e-11e7-978a-0483dd4a0c83.png)

?

**Comment by SeamusConacher** [comment]
Hello,

The issue appears in the File-> Open Recent drop down. Here is an example of the issue:
![vsissue](https://user-images.githubusercontent.com/16638857/29808521-60121086-8c90-11e7-92eb-31b46b3cdc4a.PNG)


As you can see I have five different items in the menu that all have the same file path displayed (\\cluster-fs1\data\ is mapped to Z).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10941
