### ISSUE TITLE
Integrated Terminal as New Tab

### ISSUE THREAD

**Issue by Mmannem** [Microsoft/vscode#33060]
In Visual Code, can we have 'Integrated Terminal' (Ctrl + ~) as New tab ?

We should be able to open it as normal tabs.

**Comment by fabiospampinato** [comment]
The [Open in Terminal](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-terminal) extension almost provides this functionality.

It adds an `Open in Integrated Terminal` command, which opens a new terminal tab in the current folder. You can bind <kbd>Ctrl+~</kbd> to it if you like.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/10546
