### ISSUE TITLE
IntelliSense not work in settings.json

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#33069]
- VSCode Version: Code - Insiders 1.16.0-insider (936fc3fdd9e5a47c5a626eec1ed5d81cead82d08, 2017-08-24T08:26:28.878Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
(1 theme extensions excluded)
---

Steps to Reproduce:

1. Open Setting
2. Type `"`
2. There is no suggestion of setting

~~(3. VS Code will crash (about 20s latter))~~

**Comment by EbXpJ6bp** [comment]
It seems to happen only when the folder is not open.

**Comment by EbXpJ6bp** [comment]
I can reproduce this yet.

![b6ddf1853e3b66eefcb1ee4845aa7378](https://user-images.githubusercontent.com/8474118/29736385-6e7ceea4-8a3b-11e7-9e04-4b16a2f0fc1b.gif)

![a2d5dfb645f286879491b2794236df2b](https://user-images.githubusercontent.com/8474118/29736405-a8ea3e8e-8a3b-11e7-9319-d43f7ea39f03.gif)

**Comment by EbXpJ6bp** [comment]
cc @sandy081

**Comment by sandy081** [comment]
@aeschli By any chance is this due to multi root changes in json extension / language server?
