### ISSUE TITLE
The Alt+Shift+ArrowRight does not select the next word. The only one char is being selected. The VSCode for Windows works correctly in the same scenario.

### ISSUE THREAD

**Issue by Matosov** [Microsoft/vscode#33066]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3
vs-keybindings|ms-|0.1.7
vscode-react-native|vsm|0.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
It works for me. You have the vs-keybindings extension installed, that's likely causing the issue.

**Comment by Tyriar** [comment]
Looks like it https://github.com/rebornix/vscode-vs-keybindings/blob/65e8e5ba3d8fc7773b8c56cc1329fc465f6aa7b5/package.json#L160

You can add these to your keybindings.json file to override it if you want to keep the extension:

```js
{ "key": "shift+alt+right",       "command": "cursorWordEndRightSelect",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+left",        "command": "cursorWordStartLeftSelect",
                                     "when": "editorTextFocus" },
```
