### ISSUE TITLE
Go to Definition / Peek Definition do not work when importing symbols via index.js resolution with jsconfig compilerOptions/targets above es5

### ISSUE THREAD

**Issue by Nimelrian** [Microsoft/vscode#33061]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro, Version 10.0.14393

Steps to Reproduce:

1. Create a directory `example` and open it with VS Code
2. Inside `example`, create a folder `src`
3. Inside src, create a file `bar.js` with the content `import foo from './foo`;
4. Inside src, create a folder "foo" with the files `foo.js` and `index.js` with the following contents:

```js
// foo/foo.js
export default "Foo";

// foo/index.js
import Foo from './foo';

export default Foo;
```

5. Open main.js and try to use "Go to Definition" on the imported `foo` symbol (It should work and take you to the export in `foo/foo.js`)
6. Create a jsconfig.json inside `example` with the following content

```
{
  "compilerOptions": {
    "target": "es3"
  }
}
```

7. Open main.js and try to use "Go to Definition" on the imported `foo` symbol (It should work and take you to the export in `foo/foo.js`)

8. Repeat steps 6 and 7 for the following compilerOptions.target values: es5, es2015, es2016, es2017, esnext.
9. The "Go to Definition" feature only opens the correct file when using the es3 and es5 targets, but not for the other targets
10. The "Go to Definition" feature only works with the other targets when specifying `"foo/foo.js"` as the source file to import from

Reproduces without extensions: Yes

**Comment by TimYi** [comment]
Target es2017 or es6 also have this issue. After I installed 1.17.
remove these config in jsconfig.json, go to definition works again:
```
{
    "compilerOptions": {
        "target": "ES2017"
    }
}
```

**Comment by mjbvz** [comment]
Try explicitly setting `"module": "commonjs"` in your `jsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

If module is not explicitly set, typescript sets it to: `target === "ES3" or "ES5" ? "CommonJS" : "ES6"`
