### ISSUE TITLE
Seeing the output of multiple terminals at the same time

### ISSUE THREAD

**Issue by millergarym** [Microsoft/vscode#33076]
It would be really helpful is the output from multiple terminals could be redirected to appear interleaved in one place.

The terminal extension add Terminal as a drop drop in the output tab, will a message about limited future support. And not output appear here.

I haven't found anything else that looks like it could support this.

Would be really nice whilst doing micro-services development.
Any ideas?

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7504
