### ISSUE TITLE
Duplicates added to PATH on macOS integrated terminal

### ISSUE THREAD

**Issue by imonmyown** [Microsoft/vscode#33077]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crystal-lang|fau|0.3.1
vscode-emacs-friendly|lfs|0.8.0
Go|luk|0.6.63
RustyCode|sav|0.19.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

(1 theme extensions excluded)

---

Steps to reproduce:

1. Open `~/.bash_profile`
2. Add an extra path to `$PATH` variable: `export PATH=${PATH}:/SOME_PATH`
3. Start VSCode
4. Start integrated terminal
5. Run `> echo $PATH` to see if the value added at step 2 has a duplicate.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@imonmyown are you sourcing your `~/.bash_profile` from your `~/.bashrc`?

**Comment by imonmyown** [comment]
@Tyriar I don't have one

**Comment by Tyriar** [comment]
This is happening because the VS Code environment is setup by launching a login shell. This is then inherited by the terminal which also launches a login shell. If the scripts setting up PATH are not idempotent (like the majority), you will get duplicates in PATH. This isn't particularly harmful but it's kind of ugly.

**Comment by imonmyown** [comment]
If I understand the logic correctly this slows down path search, so it _is_
kinda harmful.

**Comment by joaomoreno** [comment]
You could launch the shell inside the Terminal in a clean environment, but you'd surely hit many other issues like missing expected variables... my suggestion is not to do anything.
