### ISSUE TITLE
Some User's Emmet snippets are not shown in suggestion list in SCSS files

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#33072]
- VSCode Version: Code - Insiders 1.16.0-insider (936fc3fdd9e5a47c5a626eec1ed5d81cead82d08, 2017-08-24T08:26:28.878Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.1
EditorConfig|Edi|0.9.4
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
atom-keybindings|ms-|3.0.1
vetur|oct|0.9.5
stylelint|shi|0.28.0

---

Steps to Reproduce:

1. Here's my snippets.json file:
```
{
    "html": {
        "snippets": {
            "ull": "ul>li",
            "hello": "world",
            "em": "em",
            "ran": "{Use this format to get the snippet value as is}"
        }
    },
    "css": {
        "snippets": {
            "abbx": "color: black",
            "b": "border: 1px solid red",
            "hello": "world!"
        }
    }
}

```
2. In HTML file, type `hello`, and you'll see that `hello` is listed among other suggestions.

3. In SCSS file: type hello, no suggestions. Pressing TAB will produce the desired effect, which proves that the snippets are configured properly. They just not shown in SCSS among other suggestions for some reason.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
For html, emmet parses the abbreviation and only if it is valid, it gets expanded
For css, emmet fuzzy matches the given abbreviation with available snippet names. There is always something that can be returned. Try it, type gibberish and run the `Emmet: Expand Abbreviation` command in any css file.

For html, we show the abbreviation as the suggested item
For css, we show the expanded value as the suggested item. If we show the abbreviation itself as the suggested item, then you end up with #28933.

Suggestion lists in VS Code filter out items that do not fuzzy match with the text that has been typed. So you typed `hello`, the emmet suggestion is `world!`, vscode decides there is no match and filters out the item.

I have documented this in https://code.visualstudio.com/docs/editor/emmet#_css-emmet-snippets.

If you have ideas on making the documentation clearer around this, please do send a PR. The docs for emmet are here: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/emmet.md

**Comment by ramya-rao-a** [comment]
This is now fixed. In tonight's Insiders build you can have css custom snippets of any name for emmet

**Comment by vvs** [comment]
@ramya-rao-a Now things are getting pretty complicated from the user's point of view :)

Let's say, I've defined `"hello": "world"` css snippet for Emmet. I start typing "hel", the suggestion shows my "hello" snippet and I can quickly use it by pressing TAB. Nice and easy!

Now I define `"bsd": "border: 1px solid ${1:red}"` to speed-up entering the borders that I use quite often.

I type bsd, and there is no suggestion labeled 'bsd'.

I see the following:
* box-shadow
* break-inside
* border: 1px solid red

There are multiple problems with this:

1. Inconsistency. Some snippets are shown, others are not. As far as I understand how it works, it depends on the fact if the snippet trigger matches the content of the snippet output.

2. So the `bsd` snippet is more or less useless from the quick typing point of view. I cannot type `bsd` + TAB and get my border. If I do that, I'll end up with box-shadow.

3. Since literal `bsd` is not present in the suggestion list, I have to filter it through and search for what my snippet does, remembering the exact value of the snippet. Not to mention that there could be quite a lot of similar suggestions for borders.

* * *
Another similar issues. Let's say I've defined a `p` snippet, since it bothers me when I type `p` and TAB I *never* get the most useful and common thing for me: `"padding: |;"`

Well, this snippet `p` doesn't help as well, it does not present `padding` as a first entry in the suggestions.

**Comment by vvs** [comment]
I'd expect that user-provided snippets are shown in the list of suggestions (expanded and not-expanded), and when my input matches the snippet name exactly, that snippet MUST be the top suggestion, in order to quickly enter the snippet content.

@ramya-rao-a, should I file a separate issue for that?

**Comment by ramya-rao-a** [comment]
The issue that I tried to solve here is to ensure that the custom snippets that would otherwise get filtered out by VS Code's suggestion filtering mechanism (See https://github.com/Microsoft/vscode/issues/33072#issuecomment-324695687) get to stay in the list by adding a suggestion with snippet name instead of the expanded value

But I like your idea of never trying to show the expanded value for custom snippets but instead show the snippet name always, as you would remember the snippet name more than the snippet value.

Fixed with https://github.com/Microsoft/vscode-emmet-helper/commit/ed15dd47c93fde66438c0505660fc1bb92b3aa89

So now, if you start typing the name of any of your custom snippets, the corresponding emmet expansion in the suggestion list will have the snippet name

**Comment by vvs** [comment]
Thank you, exactly what I needed! 👍

**Comment by aeschli** [comment]
Verified in Version 1.16.0-insider Commit 8b942faafb2d1bee6fd6a346853548d528c7eb5a
