### ISSUE TITLE
Remove file dir from side bar

### ISSUE THREAD

**Issue by heartsec** [Microsoft/vscode#33070]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-haskell|jus|2.3.1
cpptools|ms-|0.12.3
vim|vsc|0.9.0

---

Steps to Reproduce:

1. open file dir
2. remove file from side bar
I can not find a way to add the file and see it in the explorer. Refresh the window and try to open the recent file won't work. Is there any hiding workspace file?

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Are you removing or adding a file? Can you post a screenshot and say what you did and what expect to see (what's on disk)?

**Comment by heartsec** [comment]
I found the solution. There is an option "Show folder" if you right click the "Explorer" on the top of Side Bar. But once you "Remove the Folder From the Side Bar"(I meant to close the project I was working on), you cannot get the Folder showing on the Side Bar unlesss you Select "Show Folder". I thought that was a bug.

**Comment by heartsec** [comment]
You cannot get the Folder showing on the Side Bar even if you restart the program.

**Comment by sandy081** [comment]
@heartsec Yeah, that was unexpected. We treated folder view same as other views in the explorer and provided an option to hide and show. But this hit back. Hence we removed the option to hide folder view - #32962
