### ISSUE TITLE
save file have some issue

### ISSUE THREAD

**Issue by desertLookForSpring** [Microsoft/vscode#33078]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3

there is a bug that I have saved file and find it in my folder, but it still warning me it not save, and I choose retry it will be ok

---

Steps to Reproduce:

1. when I save my c++ file it often occur  but not always, I don't know why
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Can you provide a screenshot?
