### ISSUE TITLE
[folding] Fold-All breaks folding for a large file and "editor.wrappingColumn" to 0

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3307]
On testing #2994:

- enable automatic line wrapping by setting "editor.wrappingColumn" to 0
- git clone https://github.com/Microsoft/vscode-node-debug
- open vscode-node-debug with VS Code
- open `src/node/nodeDebug.ts`
- do a "Fold All"
Observe: the '+' icons appear but the corresponding regions are not folded.
- click on a '+' icon
Observe: the folding state of the range doesn't change. Only visual difference is with the ellipsis at the end of the first line.

Please note: problem does not seem to occur if "editor.wrappingColumn" is set to a value > 0

**Comment by aeschli** [comment]
Fixed by @alexandrudima with 8b702c2
