### ISSUE TITLE
Running selected code taking a long time to action

### ISSUE THREAD

**Issue by Gizmo3k** [Microsoft/vscode#33071]
- VSCode Version: 1.15.1 x64
- OS Version: Windows 7 Enterprise SP1

Running selected code from the editor is taking a long time (30+ seconds) using the F8 key. On occasion, the F8 key doesn't appear to do anything at all. This was not an issue in the previous version. The complexity of the selected code does not seem to be an issue, running the following took over 30 seconds to appear in the terminal window:

    Write-Host "Test"

Sometimes the selection is run immediately, as in previous versions. I ran the same selection again and it performed instantly.

Steps to Reproduce:

PowerShell terminal
1.  Select code in editor window
2. Press F8

Reproduces without extensions: Run selection doesn't appear to be available without extensions.

**Comment by alexandrudima** [comment]
`F8` is not a keybinding we ship with. I wonder, is this something driven from an extension?

**Comment by robwesterby** [comment]
@alexandrudima The F8 keybinding applies to the PowerShell extension (ms-vscode.powershell). Action is 'Run Selection'.

I see the same slowness, though it's intermittent, and seems worse if editing a long .ps1 script, or if I've a whole function block selected. This is on a fresh install of VSCode, updated to 1.17.2. Only other installed extension is Windows Explorer Context Menu.

Typing commands directly in the PowerShell integrated terminal always respond immediately, so it seems that F8 is possibly taking a while to pass the selected content to the terminal.

**Comment by alexandrudima** [comment]
Moved to https://github.com/PowerShell/vscode-powershell/issues/1184
