### ISSUE TITLE
Emmet: ul>li produces WRONG result in some cases

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#33074]
- VSCode Version: Code - Insiders 1.16.0-insider (936fc3fdd9e5a47c5a626eec1ed5d81cead82d08, 2017-08-24T08:26:28.878Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.1
EditorConfig|Edi|0.9.4
prettier-vscode|esb|0.22.1
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
atom-keybindings|ms-|3.0.1
vetur|oct|0.9.5
stylelint|shi|0.28.0

---

Steps to Reproduce:

1. Open any HTML file, **make sure you're at the very first position on the line.**
2. Type `ul>li` and then TAB.

The end result is:
```
<ul></ul>
  <li></li>
</ul>
```
Notice the extra `</ul>` at the end of the first line, it shouldn't be there. And definitely the cursor shouldn't be there after expansion is completed.

**Comment by vvs** [comment]
Ping @ramya-rao-a  :)

**Comment by ramya-rao-a** [comment]
Is that with or without triggerExansionOnTab enabled?
I can't repro
Can you share your settings?

**Comment by vvs** [comment]
@ramya-rao-a I have "emmet.triggerExpansionOnTab": true, "editor.snippetSuggestions": "top", "editor.tabCompletion": true,

And you have to be at the very start of the line for this bug to be visible.

![vs_code_ull](https://user-images.githubusercontent.com/9781/29683278-0e6cd804-890e-11e7-82f9-8c0ce43713c3.gif)

**Comment by ramya-rao-a** [comment]
@vvs I still can't repro... 

- Can you try in an empty html file and see if you can still get this?
- Are you able to repro this with `emmet.triggerExpansionOnTab` is disabled?
- Are you able to repro this with `emmet.triggerExpansionOnTab` enabled but `emmet.showExpandedAbbreviation` set to `never` ?

**Comment by vvs** [comment]
> Can you try in an empty html file and see if you can still get this?

Yes, reproducible.

> Are you able to repro this with emmet.triggerExpansionOnTab is disabled?

Yes, reproducible.

> Are you able to repro this with emmet.triggerExpansionOnTab enabled but emmet.showExpandedAbbreviation set to never ?

No, not reproducible. `ul>li` is properly expanded in this case.

**Comment by vvs** [comment]
@ramya-rao-a OK, figured this out. It looks like a problem with "Auto Close Tag" extension.

Note to self: ALWAYS check your bug reports with no extensions mode as well! 

Sorry about that!

**Comment by ramya-rao-a** [comment]
phew 😅 I was worried there for a while

So I think the "Auto Close Tag" saw `ul>` assumed that it was `<ul>` and provided the `</ul>.

Please log an issue in the extension's repo
