### ISSUE TITLE
TOC extension not working on Convert Markdown to PDF

### ISSUE THREAD

**Issue by ezequias** [Microsoft/vscode#33082]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write a nice markdown text (with many #, ## and ###) 
2. Enable TOC on Markdown (with Markdown TOC extension)
3. Convert Markdown to PDF (with Markdown to PDF extension)

TOC works fine on vscode but not on generated PDF.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You should report this against the Markdown to pdf extension.
