### ISSUE TITLE
New icon looks bad / scaled in Windows installer.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33080]
<img width="72" alt="capture" src="https://user-images.githubusercontent.com/1931590/29668606-1c5a8ff6-88e1-11e7-8d71-4388c52d520a.png">

**Comment by qpegg** [comment]
I like new icon, but this has no border.  So if the tile's background color in windows start menu is orange , I can't see this too well.
Can you ship with .visualelementsmanifest.xml?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33090
