### ISSUE TITLE
Add an API for getting the shortcut bound to a command

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#33086]
Across the UI there are many tooltips displaying the shortcut that would execute a particular action:

<img width="150" alt="example" src="https://user-images.githubusercontent.com/1812093/29671224-451b02ce-88e9-11e7-8630-b3b3ecdb1144.png">

Unfortunately, as far as I know, this kind of information is not available via the API, so extensions cannot provide the same feature.

I'd be great if you added an API for getting a command's currently bound shortcut, as well as trigger an event when that changes.

**Comment by austenc** [comment]
I just ran into this too! Would love for a way to provide tooltips that match up to the user's current key binding config. Ideally you could grab the associated key binding for any command given its name. For extensions that do things like add status bar items or other UI elements this would be really helpful.
