### ISSUE TITLE
Output should not respect editor.rulers

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3308]
#3233

* Enable `editor.rulers`
* Open output, notice that the editor rulers are visible
* IMHO output should not respect the `editor.rulers`, as the output is readonly and rulers are mostly used when editing a document
* I could also argue that the left hand side of the diff view should not show rulers

![screen shot 2016-02-23 at 12 39 34](https://cloud.githubusercontent.com/assets/1926584/13250483/8773b87e-da2a-11e5-9e20-833430c41c69.png)

**Comment by seanmcbreen** [comment]
Markdown preview does not show rulers (which is good)
