### ISSUE TITLE
Allow changing the font family/settings in find/replace interface

### ISSUE THREAD

**Issue by BobDankert** [Microsoft/vscode#33089]
It would be ideal if we could change the font family and other settings used in the find/replace interface. The currently used font is pretty hard to work with when entering a complex regular expression in the input boxes (even a simple one, like "^`([^`]*)`,$", is hard to read - SS below). I'd ideally like a fixed-width font, but ultimately it seems best to have this as a setting in preferences.

![image](https://user-images.githubusercontent.com/1406827/29672224-3ad65d00-88b1-11e7-9314-d6f18742e77a.png)

- VSCode Version: 1.15.1 x64
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Unable to change the font family/settings that affect find/replace interface

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
