### ISSUE TITLE
Emmet not working any more - instead Js Types are shown in Intellisens

### ISSUE THREAD

**Issue by HansS** [Microsoft/vscode#33087]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@HansS 

- If you want to expand Emmet abbreviations and snippets using tab, set `emmet.triggerExpansionOnTab` to `true`
- If you are referring to js like `this.someproperty` triggering emmet suggestion like `<this class="some property"></this>`, please follow #32647

There have been quite a few changes to Emmet in the July release.
Please read the [Release Notes on Emmet](https://code.visualstudio.com/updates/v1_15#_emmet-20) or [Emmet 2.0 blog](http://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) and the [Emmet docs](https://code.visualstudio.com/docs/editor/emmet)

If the above still doesn't help, then please provide more details include screenshots/gifs and repro steps
