### ISSUE TITLE
Add a `inPausedDebugMode` flag

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33085]
There's already an `inDebugMode` flag that can be used in keystrokes' `when` clauses. It would be useful to have an `inPausedDebugMode` as well.

My use case: I've made my `workbench.action.debug.continue` shortcut be `cmd+\`, which is what Chrome uses, but that's also the same shortcut I use for splitting the editor. Basically without this flag I cannot split editors while debugging.

Having this flag would also partially fix #30810 if ever those `when` flags will be exposed via the API.

**Comment by isidorn** [comment]
There is `debugState` context key. Try it out

**Comment by fabiospampinato** [comment]
Great!

For future reference: the string to use is `debugState == 'stopped'`.
