### ISSUE TITLE
Feature Request: Manual updates on insider builds

### ISSUE THREAD

**Issue by fpqc** [Microsoft/vscode#33081]
I understand that in an earlier issue, you resisted adding the ability to manually update when automatic updates are disabled.  However, for those of us who use the insider builds, this makes sense to do.  We're by nature the kind of people who want to read patch notes or known issues before installing the latest bleeding-edge build.  Also, the frequency of updates on the insider channel is so high that it becomes extremely annoying.

Could you reconsider adding this feature?

**Comment by Tyriar** [comment]
You can always manually update by downloading from code.visualstudio.com ?

> Also, the frequency of updates on the insider channel is so high that it becomes extremely annoying.

This is the whole point of the Insiders build, we get changes out the next day which leads to a more stable release.
