### ISSUE TITLE
Insiders orange icon / logo mis-sized

### ISSUE THREAD

**Issue by alexcnichols** [Microsoft/vscode#33090]
- VSCode Version: Code - Insiders 1.16.0-insider (936fc3fdd9e5a47c5a626eec1ed5d81cead82d08, 2017-08-24T08:26:28.878Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.122.0

The new orange icon / logo for Insiders is cool but mis-sized in the installer, taskbar, and application window. 

![image](https://user-images.githubusercontent.com/19493383/29672402-fba9c2bc-88a0-11e7-9a06-6b710b2857af.png)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexcnichols** [comment]
Also, the logo on the welcome page is still the green one. 

![image](https://user-images.githubusercontent.com/19493383/29672496-45b199ca-88a1-11e7-8960-376dcc96250c.png)

**Comment by chrisdias** [comment]
The Setup issue is a dupe of #33080.  

@alexcnichols When you mention the taskbar and application window, are you still referring to setup, or the product itself?  If you can post images, that would be helpful.

I opened https://github.com/Microsoft/vscode/issues/33095 for the Welcome page.

**Comment by alexcnichols** [comment]
@chrisdias Product itself.

![image](https://user-images.githubusercontent.com/19493383/29675576-6a42b612-88aa-11e7-9f74-c531f181582e.png)

**Comment by chrisdias** [comment]
Taskbar looks consistent with VS, and it looks like our title bar is not as tall (the VS title bar is custom drawn), meaning the icon will be scaled down for VS Code, so I'm not sure if we can do anything there @bpasero ?

![image](https://user-images.githubusercontent.com/1487073/29676141-1a2fa7d2-88ac-11e7-9516-c9a3203abb06.png)

**Comment by alexcnichols** [comment]
The leftmost 1 or 2 pixels is clipped off in the new Insiders icon. Yeah, I can see how the title bar leaves less real estate.

**Comment by bpasero** [comment]
@joaomoreno can we use any other format in the installer than BMP or is that a limitation we cannot lift?

@chrisdias title bar is not under our control until we approach implementing a custom title and menu (https://github.com/Microsoft/vscode/issues/29024)

**Comment by bpasero** [comment]
To be fair, our current installer is also not a beauty:

![image](https://user-images.githubusercontent.com/900690/29680021-9889c868-8903-11e7-94d4-8ace86d3df38.png)

**Comment by bpasero** [comment]
Icon looks ok to me in the title bar on my Win10:

![image](https://user-images.githubusercontent.com/900690/29680056-b915ff2a-8903-11e7-8714-ffb1bb41b0c4.png)

**Comment by joaomoreno** [comment]
@bpasero AFAIK it needs to be a bitmap: http://www.jrsoftware.org/ishelp/topic_setup_wizardimagefile.htm

**Comment by alexcnichols** [comment]
The empty page has the problem too.

![image](https://user-images.githubusercontent.com/19493383/29682506-1f90dd36-88c0-11e7-8795-8ae3bf4b8f55.png)

**Comment by qpegg** [comment]
Is there any possibility that he point out the new icon is not the infinity symbol?

**Comment by chrisdias** [comment]
@qpegg you may be right...  @alexcnichols the fact that there is no vertical line on the left is intentional... please see https://github.com/Microsoft/vscode/issues/6607#issuecomment-324456824.

**Comment by alexcnichols** [comment]
My mistake. Sorry for the confusion. Closing as-designed.

**Comment by qpegg** [comment]
@chrisdias

https://github.com/Microsoft/vscode/issues/33080#issuecomment-324645104

**Comment by LucasArcega** [comment]
How can i go back to blue?

**Comment by LucasArcega** [comment]
How can i go back to the blue logo one?
