### ISSUE TITLE
The dialog Find don't keep the size

### ISSUE THREAD

**Issue by danilort** [Microsoft/vscode#33098]
Hello.
If I resize the dialog Find, it don't keep the size, after I reopen VSCODE.

- VSCode Version: 1.15.1  32-bit
- OS Version: Windows 10  64-bit

Steps to Reproduce:
1. open vscode
2. Edit > Find  (the dialog is too small)
3. resize the dialog 
4. close vscode
5. open vscode 
6. Edit > Find  (the dialog is too small)

Reproduces without extensions: Yes

Best regards
Danilo

**Comment by budus** [comment]
I have the same problem on different platform:

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

**Comment by danilort** [comment]
SOLVED.
On the VSCode 1.17.0
