### ISSUE TITLE
Add a TabBarItem object

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33091]
There's already a [StatusBarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#StatusBarItem) object, for adding items to the StatusBar, an analogous class for adding items to the TabBar would be awesome.

<img width="235" alt="tabbar" src="https://user-images.githubusercontent.com/1812093/29672503-bab0bd1e-88ec-11e7-894d-53f846bba112.png">

Don't you think?

**Comment by bpasero** [comment]
@fabiospampinato that place is open for actions that can have icons or text. The API is different from the status bar API in that you have to register a command and put it into the location `editor/title`. See our git extension for examples https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json#L673

**Comment by fabiospampinato** [comment]
Yes, it's possible to add buttons there, but not programmatically like it's possible with statusbar buttons, that's basically what my request is about. 

Is there any reason for not including this feature?
