### ISSUE TITLE
[c++] wrong syntax highlighting results when using decltype and '::'-specfied names in templates

### ISSUE THREAD

**Issue by gnaggnoyil** [Microsoft/vscode#3309]
I am using currently the latest VSCode version(0.10.8) with 'Dark+ (default dark)' color scheme and the piece of C++ code in the picture below produces wrong syntax highlighting results for following class/struct declarations/definations and endif macros(define, include, if and ifdef macros are not affected though).

![wrong syntax highlighting result](https://cloud.githubusercontent.com/assets/1560625/13250495/412c8338-da65-11e5-81db-09b6c4a82c26.png)

Changing foo::bar to somthing that does not use '::' will make all the wrong syntax highlighting results normal again.

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#37

**Comment by aeschli** [comment]
Looks like syntax in angle brackets is not correctly tokenized.
Please file this against https://github.com/atom/language-php

**Comment by gnaggnoyil** [comment]
I'm sorry, but I did not understand. Why is this to be filed against a PHP language supporter?
