### ISSUE TITLE
Add custom width property to terminal

### ISSUE THREAD

**Issue by Adobe-Android** [Microsoft/vscode#33093]
Something like "terminal.integrated.lineWidth": 1.4,
It really helps when you also have fontLigatures set to true as some ligatures can look be cut off without a custom property available like this.

**Comment by Tyriar** [comment]
Do you mean character width? If there are problems with ligatures, please share a screenshot as that sounds like a bug.

**Comment by Adobe-Android** [comment]
http://imgur.com/a/ObGAR

**Comment by Tyriar** [comment]
This looks like an issue with that character not being monospace in a monospace font. Could you copy and paste that "v" character (that's what you're talking about right?) and take a screenshot of a terminal where it works fine? Also what OS are you using?

**Comment by Adobe-Android** [comment]
I'm on Fedora 25 (Linux). http://imgur.com/a/LgTOp

**Comment by Adobe-Android** [comment]
It looks like it was fixed with a recent update. I think it's safe to say we can close this one.
