### ISSUE TITLE
Replace all doesn't replace everything

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#331]
Currently when we do a replace all, it only replaces content among the currently displayed buffer and not throughout the file.

I had a file with 20000 lines and I had to change the table name, so I had to click on replace all 1000 times to make that happen

**Comment by alexandrudima** [comment]
@thewhitetulip 

The find widget only highlights the first 1K hits, but I am confident Replace All replaces all occurences. It is something I changed rather recently. Can you please help with additional steps -- and are you seeing this in 0.10.1 ?

**Comment by thewhitetulip** [comment]
yes, 0.10.1

I have a huge file, 50MB they were sql statements and i had to change the database name, i had to hit replace all 100times before it was done

**Comment by alexandrudima** [comment]
Just checked again, `Replace All` on `master` replaces all find matches, regardless of the 1k decorations limit.

See https://github.com/Microsoft/vscode/blob/587854a5bcae72950da0e9412ab773933a350e6b/src/vs/editor/contrib/find/common/findModel.ts#L321

**Comment by ToMakeSense** [comment]
I knew some case of this issue. If you open a large file or text, you do some replacement, it needs time to finish(in my case, latest version of vs code , 200,000 cases for 20s or more, depends on the file size and your computer). Sometimes, we don't realize it‘s still running and not finished. So I think, a clear remind in  status bar is very much necessary.
