### ISSUE TITLE
cmd+shift+f (Find in Files) should always select the contents of the search field

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#33108]
The current behavior is that pressing cmd+shift+f toggles between the editor and the side panel, but this drives me crazy as I need to check my focus before pressing (or not pressing) that combo when doing a lot of hunting around.

The number of times I've accidentally typed my search into a random file instead of the search field is painful. Please make cmd+shift+f always focus the search field, or at least allow for such an option.

This issue was originally closed, here: https://github.com/Microsoft/vscode/issues/22814#issuecomment-324732891

I'm not certain why this isn't default behavior as it is common in other editors.

Thanks!

**Comment by jimmy-guo** [comment]
It should ideally also select-all in the search field in addition to focusing it when there is already text there.

**Comment by mherodev** [comment]
A related issue: It doesn't select-all in the search field when pressing cmd+shift+f if the field is already focused. It can be quite disorienting.

**Comment by roblourens** [comment]
It is possible to always focus the search field with a binding like this:
```
{
        "key": "shift+cmd+f",
        "command": "workbench.action.findInFiles"
}
```

I guess it's not the default just because I don't want to change it this late. But 

> It doesn't select-all in the search field when pressing cmd+shift+f if the field is already focused

that's a bug

**Comment by mherodev** [comment]
I'll take the little victory! Thanks Rob.

**Comment by jimmy-guo** [comment]
Thank you! Cheers to no more `git diff` surprises _and_ no extra `cmd+a` keystrokes :)
