### ISSUE TITLE
allow unix sockets to be created outside the --user-data-dir folder

### ISSUE THREAD

**Issue by ninrod** [Microsoft/vscode#33100]
- VSCode Version: all
- OS Version: GNU/Linux docker containers

this is a follow up of #28126. 

The core issue at play here is understanding that containers are not persistent. So, if I run vscode inside a docker container and user configurations are to be persistent, I need to mount the `--user-data-dir` folder into an user disk like `D:\`. This is fine in mac and linux, but not in windows using docker for windows. Example: 

```sh
$ docker run -i -t -v /d/vscode/config:/root/.vscode ninrod/vscode:latest bash
```

Sadly, I cannot do this because `/d/vscode/config` is a NTFS filesystem structure which does not understand unix sockets so `vscode` crashes on startup. 

Please, allow the user to tell vscode to create these sockets that are created on `--user-data-dir` elsewhere. Example: `/var/run/vscode` or something:

```sh
.vscode $ w
 ~/.vscode at root@container using -zsh $
.vscode $ l *.sock
srwxr-xr-x 1 root root 0 Aug 24 14:16 1.14.2-main.sock
srwxr-xr-x 1 root root 0 Aug 24 14:16 1.14.2-shared.sock
.vscode $
```

thanks in advance.

**Comment by AdilsonThanus** [comment]
+1

**Comment by Tyriar** [comment]
Reopened the other one, pretty sure it's an Electron thing though.
