### ISSUE TITLE
Default Ctrl+R Ctrl+R chord handling

### ISSUE THREAD

**Issue by nycdotnet** [microsoft/vscode#33101]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.7.0
EditorConfig|Edi|0.9.4
PowerShell|ms-|1.4.1
Ruby|reb|0.15.0

---

Steps to Reproduce:

1.  Open a JS file or any code file with `editorHasRenameProvider`.  Make a variable and put the cursor inside it.
2. Press and hold the Ctrl key.
3. Press R twice.
4. Release the Ctrl key.

Reproduces without extensions: Yes

Expected behavior: The variable will be renamed.  (`Ctrl+R Ctrl+R` is the default keyboard chord for renaming a variable in Visual Studio).
Actual behavior: VS Code will close the current project and open up some other project depending on what other things you've recently opened.

I wonder if there is a way to detect the chord and process the rename action.  `Ctrl+R Ctrl+R` is a keyboard shortcut that has been reinforced through years of muscle memory from using full Visual Studio.  Adding `{ "key": "ctrl+r ctrl+r",                "command": "editor.action.rename",
        "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly" }` appears to make stand-alone Ctrl+R not work because VS Code will be waiting for the second chord.  I am willing to forgo this, but I am wondering if there is a way to support the rename action and recent files.  Sorry for the "not a bug" ticket, but it's just very frustrating to keep getting thrown out of my project when I'm just trying to do some refactoring.  :-(

**Comment by rebornix** [comment]
I can see the pain point when you expect ctrl+r ctrl+r to work as usual. May I ask what's your expected behavior of a single ctrl+r (whether there is another ctrl+r coming or not)? Should the editor wait for the next keystroke or simply apply what's matched?

**Comment by nycdotnet** [comment]
Thanks.  As a long time Visual Studio user, I kind of expect CTRL+R to work like CTRL+K where it waits for the next command in the chord.  If CTRL+R is a command alone (especially by default), I honestly don't know how you reconcile that.

**Comment by carlocardella** [comment]
What about use Enter as a way to confirm the first shortcut and execute it? That would be different from "Ctrl+R Ctlr+Enter" and it's not possible to have "Ctrl+R+Enter" so there should be no overlapping with other shortcuts

**Comment by rosslovas** [comment]
I found the following keybinding can be used to achieve rename behaviour for Ctrl+R Ctrl+R:

    {
        "key": "ctrl+r",
        "command": "editor.action.rename",
        "when": "inQuickOpen && inRecentFilesPicker"
    }

This overrides the default action for Ctrl+R only when the recent files picker is open (i.e., after the first Ctrl+R keypress) which is `workbench.action.quickOpenNavigateNextInRecentFilesPicker`, the action that was previously causing VS Code to switch to a different project.

**Comment by rebornix** [comment]
Close as there is a proposed solution above.
