### ISSUE TITLE
Java Syntax Highlighting Inferior in macOS than Windows

### ISSUE THREAD

**Issue by janjulian** [Microsoft/vscode#33107]
Notice the syntax highlighting for the same file is better on Windows than Mac. Can this be fixed?

# OS: Windows 10 Enterprise; VSCode: Version 1.15.1
![image](https://user-images.githubusercontent.com/2403043/29684446-d4faee90-88c6-11e7-8f89-afd2062e4e49.png)

# OS: macOS Sierra 10.12.6; VSCode: Version 1.15.1
![image](https://user-images.githubusercontent.com/2403043/29684475-f9297bc4-88c6-11e7-8474-881d6fbc9556.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@janjulian It looks like on the Mac you are using the `Dark (Visual Studio)` color theme, but on Windows `Dark+`.

**Comment by julianACL** [comment]
Consider this fixed thanks to @aeschli!
