### ISSUE TITLE
search: regex matches '$' differently if file is open

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#33112]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
gitlens|eam|4.4.1
tslint|eg2|0.17.0
macros|ged|1.2.0
mssql|ms-|1.1.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.1.8
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. open code in new empty folder
2. create file containing several lines of text
3. open that file in the editor
4. regex search for '$' (no quotes)
5. note that the search results include every line
6. now close the file and repeat the search
7. note that the search results only includes the last line in the file

Reproduces without extensions: Yes

**Comment by Spongman** [comment]
also: if you disable 'repgrep' in the settings, it doesn't find _anything_ if the file isn't open in the editor.

**Comment by roblourens** [comment]
What do you expect `$` to match? It doesn't seem like a useful search. Ideally it would be consistent but it's up to the difference between the JS and Rust regex engines.

**Comment by Spongman** [comment]
sure, it's not a useful search, but it's the simplest example that repros the bug. _any_ search that includes the `$` anchor potentially yields inconsistent results depending on whether or not the file is open in the editor.

i guess the bug should just be: you're using two different regex engines.

**Comment by Spongman** [comment]
this still repos in 1.16.0: the '$' works completely differently if the file is open in the editor.

**Comment by roblourens** [comment]
`;$` now matches correctly from a bug fixed upstream. `$` only matches the first line of the file, but I'm not gonna follow it up.
