### ISSUE TITLE
Can't use tab.activeBorder with editorGroupHeader.tabsBorder

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#33111]
I tried the new `tab.activeBorder` but it doesn't work properly on the Ayu themes. The bottom border is hidden. If I decrease the tab element to 34px instead of 35px I can see the border. 

This is what I would like to achieve (original ST3 theme):
<img width="1296" alt="screen shot 2017-08-24 at 19 08 53" src="https://user-images.githubusercontent.com/353888/29678734-ef4997cc-88ff-11e7-900f-dbd2c734baab.png">

I did som adjustments in devtools and got pretty near by doing the following changes:

![screen shot 2017-08-24 at 23 04 48](https://user-images.githubusercontent.com/353888/29688637-bb0a65f6-8920-11e7-81be-a26c5ff979e2.png)

1. Removed `overflow: hidden` from selector `.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title, .monaco-workbench>.part>.title`

2. Removed inline style `overflow: hidden` on element with class `.monaco-scrollable-element`

3. Added `border-bottom: 1px solid #1d242c` to selector `.monaco-workbench>.part.editor>.content>.one-editor-silo>.container>.title .tabs-container>.tab`

**Comment by bpasero** [comment]
@pahen unfortunately that does not work, you have to check for when the tab control has so many entries that it overflows. In your example the actions are now pushed out to the right:

![image](https://user-images.githubusercontent.com/900690/29699709-1cba3a7c-895f-11e7-9b66-abe97690fb49.png)

I think this will be tricky, if someone wants to chime in with a reasonable PR, help is welcome.

**Comment by pahen** [comment]
If we could live with tab border being placed above the header border, one solution would be to use inset shadow instead of border @bpasero 

<img width="964" alt="screen shot 2017-08-25 at 20 52 34" src="https://user-images.githubusercontent.com/353888/29728221-5d85463c-89d7-11e7-967b-726a04a3759a.png">

<img width="679" alt="screen shot 2017-08-25 at 20 53 40" src="https://user-images.githubusercontent.com/353888/29728266-87207fb6-89d7-11e7-8a3b-c576cfb341e6.png">

I think it's pretty hard to notice as long as it's only 1px high.

**Comment by bpasero** [comment]
@pahen excellent idea, seems to work nicely!
