### ISSUE TITLE
TS shows Extract Function suggestion on `import`

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#33113]
- VSCode Version: 1.16 Insiders
- OS Version: macOS

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/876920/29691673-e694d408-88e0-11e7-9ffe-44287b8ad6ee.png)

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by: https://github.com/Microsoft/TypeScript/issues/17997
