### ISSUE TITLE
HTML file content changes on save - CSS collapses, cursor moves

### ISSUE THREAD

**Issue by rafaeldwan** [Microsoft/vscode#33119]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-tidyhtml|anw|1.5.0
ruby-rubocop|mis|0.4.0
HTMLHint|mka|0.3.3
Ruby|reb|0.15.0
open-in-browser|tec|1.1.0

html file is open with embedded style. on save cursor jumps much lower in file, css within <style> tag loses all carriage returns.

See .pdf here https://drive.google.com/file/d/0B10ND-qqpNQ4NVpVZndacFF0SUU/view?usp=sharing

So far only seen this on one file. Happens after VSCode reset. Happens when the file is new and the text is pasted in. Launching without extensions fixes issue. 

---

Steps to Reproduce:

1.  file was downloaded as .zip, extracted. opened fine. 
2. save 

Reproduces without extensions: No

**Comment by Tyriar** [comment]
It looks like your extension https://marketplace.visualstudio.com/items?itemName=anweber.vscode-tidyhtml is to blame
