### ISSUE TITLE
Touch scrolling broken in Microsoft Edge

### ISSUE THREAD

**Issue by jacobrossi** [Microsoft/vscode#33117]
- VSCode Version: 1.15.1
- OS Version: Windows 10 - Build 16271+

Steps to Reproduce:

1. Open any Monaco test page in Edge
2. Attempt to scroll with touch

Reproduces without extensions: Yes

**Comment by jacobrossi** [comment]
Monaco uses window.navigator.pointerEnabled to feature detect standard Pointer Events. This property was [deprecated in the standard](https://www.w3.org/Bugs/Public/show_bug.cgi?id=22890) and is being removed from Microsoft Edge as of build 16271.

I have a PR coming shortly with a fix. Note that this also breaks the F12 tools in Edge (which use monaco-editor).

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/monaco-editor/issues/644
