### ISSUE TITLE
Search bar creates white gap above code

### ISSUE THREAD

**Issue by Pfaeff** [Microsoft/vscode#33128]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.2.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.8.1
togglehs|bbe|0.1.2
tortoise-svn-for-vscode|cds|0.1.1
prototxt|dmi|0.0.6
jupyter|don|1.1.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.15
code-python-isort|fre|0.0.3
cppcheck|mat|0.2.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
java|red|0.8.0
vscode-icons|rob|7.12.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.2
debug|web|0.21.2
clang-format|xav|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file
2. Press CTRL+F
3. Scroll down
4. Scroll back up
5. Now there is a big white gap with the same height as the search bar above the code

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Could you take a screenshot?

**Comment by Pfaeff** [comment]
This is the gap:

https://www.dropbox.com/s/tvgc2dbt0py285h/the_gap.png?dl=1

Under Windows 10, it seems to pop up immediately when pressing ctrl+f. 
Under Ubuntu, the search bar first shows up on top of the code and only creates this gap after scrolling down and back up.

**Comment by Tyriar** [comment]
This is as designed, the find widget adds some extra space to the editor so that it will not overlap the text in the first couple of lines.

**Comment by Pfaeff** [comment]
It's clearly not, as the behaviour is different on Windows and Ubuntu. Also the space only shows up after scrolling.

**Comment by Tyriar** [comment]
@Pfaeff there are some rules around when it happens. @rebornix can elaborate

**Comment by rebornix** [comment]
For the search bar gap issue, let's track it in https://github.com/Microsoft/vscode/issues/28390
