### ISSUE TITLE
Build 'Problems' window navigation problem

### ISSUE THREAD

**Issue by Deliay** [Microsoft/vscode#33124]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
ftp-sync|luk|0.3.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.8

---

Steps to Reproduce:
![Screenshoot](https://user-images.githubusercontent.com/5661435/29701566-08c5c032-899f-11e7-94f4-422405bdcfd6.jpg)

Build a project, if the project in sub folder, the 'Problems' window will navigation file to current root folder.

Reproduces without extensions: No

**Comment by sandy081** [comment]
@Deliay It seems the extension creating the problems is not providing the right file URI. Please file an issue against corresponding extension.
