### ISSUE TITLE
Indentation being destroyed by moving multiple lines of code via Alt+Arrow Keys

### ISSUE THREAD

**Issue by Pfaeff** [Microsoft/vscode#33127]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.2.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.8.1
togglehs|bbe|0.1.2
tortoise-svn-for-vscode|cds|0.1.1
prototxt|dmi|0.0.6
jupyter|don|1.1.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.15
code-python-isort|fre|0.0.3
cppcheck|mat|0.2.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
java|red|0.8.0
vscode-icons|rob|7.12.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.2
debug|web|0.21.2
clang-format|xav|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Select multiple lines of code
2. Move them using Alt+Arrow keys
3. Every line of code that will be crossed by the moving lines will change its indentation.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Do you mind sharing the code snippet to help better troubleshoot?
