### ISSUE TITLE
Feature request - need more icons in snippets list (for Emmet, custom snippets, etc.)

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33121]
- VSCode Version: 1.15.1
- OS Version: win7x64

When you type and see these pile of snippets ...

![image](https://user-images.githubusercontent.com/24613274/29694356-460967e2-8944-11e7-838b-401691fb7d10.png)

... how can you say, which one is "VSCode core's snippet", and which one is "Emmet snippet"? You can't. You just need to press "Arrow Down" key infinite times to figure it out. I think, that icons at the left of snippet can be more useful.

For example, Emmet icon - ![image](https://user-images.githubusercontent.com/24613274/29694642-7075c6a4-8946-11e7-9a96-902ec9b304de.png)

how it can be:
![image](https://user-images.githubusercontent.com/24613274/29694620-56b7be48-8946-11e7-92ec-646a877c2969.png)

What do you guys think about it? For my humble opinion, it looks better, and what is really necessary - it is more useful for developer. How is it more useful? When a developer will glance at the list - he will know for sure - 1) that he has required Emmet snippets in the list (there are tons of situations when snippet DO NOT appear, because of user mistake, vscode's bug etc.), and 2) user will choose the right snippet, not vscode core's basic "dry" snippet with nothing in it, but the right Emmet snippet.

Also it would be great to implement user icons (for example,  ![image](https://user-images.githubusercontent.com/24613274/29694854-ea79355c-8947-11e7-8087-4bc18ce5014b.png) ), for custom user snippets in HTML, CSS, JS, etc.

**Comment by ramya-rao-a** [comment]
@jrieken What do you think of custom icon for emmet?

**Comment by ramya-rao-a** [comment]
I was considering showing emmet suggestions as snippets. That would automatically give the snippet icon for the emmet suggestions

<img width="761" alt="screen shot 2017-08-24 at 11 33 54 pm" src="https://user-images.githubusercontent.com/16890566/29702149-baddf51c-8924-11e7-9861-a31a2fba3afd.png">

**Comment by jrieken** [comment]
There has been a good discussion about more icon types, support for custom icons, and more here: https://github.com/Microsoft/vscode/issues/2628#issuecomment-275122181.

Given that and given that emmet has snippet-like-semantics, I am :+1: for using the snippet type.

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode/issues/32346#issuecomment-326147614

In tonight's insiders you can enable `emmet.showSuggestionsAsSnippets` to get emmet suggestions to show up as snippets.

@jrieken #2628 was concluded by including new completion kinds with different icons. Is there any issue tracking the need for custom icons that can be defined by extensions?
