### ISSUE TITLE
Reset styling for embedded languages in grammars?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33120]
# Problem
For grammars with embedded languages, the outside scope's colorization can leak into the embedded language:

![screen shot 2017-08-24 at 4 26 07 pm 1](https://user-images.githubusercontent.com/12821956/29693182-1203fd28-88e9-11e7-809c-104368320484.png)

The above example shows embedding the html grammar in a js template string. Notice that `text` is orange. No specific html grammar scope  applies to it so it picks up the foreground color of `string.template.js`

Instead, in most cases I feel it would make more sense that `text` be colored the same at it would be in a normal html file, which in this case would be the default foreground color of the theme

![screen shot 2017-08-24 at 4 38 32 pm](https://user-images.githubusercontent.com/12821956/29693473-b07f6e78-88ea-11e7-890d-28620964be20.png)

# Possible Approach
I've already fixed this issue for `${expressions}` in normal js template strings. Manually handling each language and embedded language combination will not scale however. 

One idea is to make themes treat the `meta.embedded` scope as a styling reset point. Themes would just use the same style for `meta.embedded` as for the default:

```
	"tokenColors": [
		{
			"settings": {
				"foreground": "#D4D4D4",
				"background": "#1E1E1E"
			}
		},
		{
			"scope": "meta.embedded",
			"settings": {
				"foreground": "#D4D4D4",
				"background": "#1E1E1E"
			}
		},
      ...
```

This works in my initial testing but may have unintended side effects. It also requires updating every theme

**Comment by mjbvz** [comment]
@Tyriar or @aeschli, any thoughts on this?

**Comment by Tyriar** [comment]
You essentially want to clear the scopes for the embedded language block right?

@alexandrudima is quite familiar with the textmate scopes.

**Comment by mjbvz** [comment]
Yes, I looked through some textmate grammars but didn't see any examples of this

**Comment by aeschli** [comment]
I'd argue that having red as default isn't wrong, it's still a string, after all. But themes are already free to define such rules such as setting the default background color for 'source' or 'meta.embedded'

I'm against any tricks and customizations of our textmate coloring engine, we should stay compatible. But if you want to add something to our default rules, no problem.

**Comment by alexandrudima** [comment]
:+1:
> I'm against any tricks and customizations of our textmate coloring engine, we should stay compatible. But if you want to add something to our default rules, no problem.

**Comment by mjbvz** [comment]
Ok, sounds like proposed theme changes is the way to go. I'll look into trying this next iteration
