### ISSUE TITLE
一些不完善的地方

### ISSUE THREAD

**Issue by 1136863240** [Microsoft/vscode#33123]
在PHP文件中编辑HTML标签时，标签参数无法补全
而且可以说输入的内容大部分都是PHP的东西而不是根据在哪里输入就提示什么样的东西，JS里也无法自动补全对应HTML里的东西
可能是我PHPStorm用多了吧，所以觉得VSCODE还是有些不方便的

**Comment by Tyriar** [comment]
You should install https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense if you haven't. We defer PHP support to extensions.
