### ISSUE TITLE
Welcome Tab icon is old in latest VSCode insiders.

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode#33126]
Love the new Icon. Guess it needs to change for the welcome tab too.

![image](https://user-images.githubusercontent.com/313363/29701654-9030cce8-898a-11e7-8014-ea06081f6a82.png)

**Comment by ihalip** [comment]
I didn't find the new icon anywhere in the source tree, which leads me to believe it's part of the Microsoft branding.

In the source tree, the [icon](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcome/code-icon.svg) displayed in the Welcome tab is the Code-OSS one, so maybe Microsoft needs to replace it with the new one before building the package.

**Comment by Tyriar** [comment]
Nice catch, this one slipped past and we fixed it yesterday. The latest build should look good 😄

**Comment by praveenpuglia** [comment]
Works flawlessly in the latest build. Thanks 👍
