### ISSUE TITLE
Cmd-Q won't quit the editor 

### ISSUE THREAD

**Issue by awbacker** [Microsoft/vscode#33131]
I really do not want to file this here, but.... "tweet" your feedback! is that a joke?  And the links in the feedback popup don't work either!   Let us file a normal feedback or other message here that goes somewhere, not github, that you control and without all this hassle.  

VSCode Version: 1.15.1
OS Version: OSX Sierra

Steps to Reproduce:

1.  Install C# plugin?
2.  Do stuff, compile, add to git, remove from git, ... ?
3.  Can't quit VS Code!

Reproduces without extensions: No Idea.  I can't quit it.

![image](https://user-images.githubusercontent.com/103330/29704180-41a1b0f8-89ab-11e7-990f-b6b92d02f5cc.png)

**Comment by rcjsuen** [comment]
@awbacker I tried clicking on both links in that feedback window and they both opened a browser window for me.

I think the general idea is that people are expected to open issues on GitHub. If you click on the 'Help > Report Issues' menu item, that too will open a browser window to GitHub.

What is wrong with GitHub and why do you want your feedback to go somewhere that is "not github"? Are there other methods that other open source projects are using to provide feedback that you feel are better than what VS Code has done?

Unfortunately, I can't help you with your Cmd-Q question as I'm on Windows. On Windows anyway there doesn't seem to be a default keybinding to the `workbench.action.quit` command.

**Comment by joaomoreno** [comment]
cc @chrisdias @seanmcbreen  for the feedback smiley. Can we delete this guy?

---

As for your quit problem... does the application quit when you use the Application menu (`Code` > `Quit Code`)?

Have you customized any keybindings? Do you have any extensions installed, like keymaps?

**Comment by seanmcbreen** [comment]
Hi @awbacker 

One thing we have worked really hard on as a team is to be as responsive as possible to user feedback,  We have learnt the hard way that a big part of that is to try and funnel as much feedback as possible into a few central locations.  In the majority case that means GitHub where we deal with (plans, feature requests, bugs, clarifications, ...).  

It is a little restrictive as we push you down a path - GitHub in this case - but at the same time it really accelerates the time to response and keeps the data manageable (we get well over 2,000 issues a month to review).

As for send a smile and frown using twitter, we do that as we love the idea of you sharing your feedback with the world.  It should not go into a black hole [which is what used to happen] and we really have nothing to hide.

Again the downside is it pushes you down a certain path i.e. Twitter.  The positive side is we see [feedback via this each and every day](https://twitter.com/search?q=%23HappyCoding&src=typd) and we even have it up on a monitor in the room to keep us all going.

We are always working to make VS Code better and the feedback experience.  For now we have found what we have to be the best balance.

Sean

**Comment by awbacker** [comment]
Sorry its taken me a bit to respond.  I should have included my reasons more clearly.  TL;DR: I only wanted to send up small data point, I was ok with being ignored, but had to use a public forum.  

For me, posting to github is easy since I'm here all the time anyway.   That said, it and twitter do have their drawbacks:

Psychologically, GitHub has a big barrier to posting `smallish` issues issue since its clearly a bug you are posting, even if the wording is not quite that.  It is for tracking technical problems (apparent even to a non-user) and so the hurdle of being "not worth the teams time" is quite large.  In addition, the issues are tracked and linked to you, and you get notifications, all things which I don't particularly want most of the time if its not stopping me from doing my work.  

Posting to twitter also has issues, since that is a public forum.  Going there would require me to engage in yet another unwanted social media platform, one I do not already use.  It also "feels" rude:  I don't want to say you guys are doing a "bad job"  _publicly_.  Despite that not being my meaning (you are doing amazing stuff), it *feels* like a public insult.

In cases like mine, the cmd-q issue, I just want to add to a metaphorical "pile" where if enough people report similar issues then it will be further looked at.  Issues like mine are inevitable, and expected, and do not reflect at all on the quality of your work. So from a technical perspective its not something I would hope anyone would actually investigate, but rather a very small data point.  Maybe in that context it makes more sense why the available options seem either overpowered or too public.  

### Technical Details

This is a new computer, so nothing has really been customized yet.  I have no keyboard shortcuts in that project, or globally, yet.  I had just installed the c# extension to try out selinum from .net on a mac (which worked, btw), but I somehow doubt thats the direct cause.  Quitting from the menu did not work either.  In the end I did a force-quit and haven't had the problem again.

**Comment by joaomoreno** [comment]
> In the end I did a force-quit and haven't had the problem again.

cc @bpasero 

Closing for now.
