### ISSUE TITLE
Wrong tooltip on PHP function password_verify

### ISSUE THREAD

**Issue by pascalbrax** [Microsoft/vscode#33132]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mysql-inline-decorator|odu|0.0.4
bootstrap-3-snippets|wcw|0.1.0

The PHP function password_verify has a wrong description in the editor's tooltip.

Editor says "PHP 5.5 only" while the PHP manual says PHP 5.5 and 7.0
http://php.net/manual/en/function.password-verify.php

---

Steps to Reproduce:

1. start typing password_verify in a PHP file
2. read the tooltip

Reproduces without extensions: Not relevant

Screenshot: http://i.imgur.com/oNU2vuT.png

**Comment by roblourens** [comment]
@aeschli Do you know how these were generated? They are getting out of date. Is there an easy way to regenerate them? https://github.com/Microsoft/vscode/blame/master/extensions/php/src/features/phpGlobals.ts#L24

**Comment by smuuf** [comment]
While you guys are at it, `array_column` function would also deserve a tooltip. :) *(there's none for it right now)*

**Comment by roblourens** [comment]
Ping @aeschli

**Comment by aeschli** [comment]
@roblourens Sorry, also before my time. @alexandrudima, do you know where the PHP53Schema.xml came from.

**Comment by alexandrudima** [comment]
@aeschli Sorry I don't remember. What does blame on the old repo reveal ?

**Comment by smuuf** [comment]
I'm not from Microsoft so this may well be very out of my league, but... *is it possible it came from Webmatrix?*

https://blogs.msdn.microsoft.com/web_/2011/10/25/memowebmatrix-2-beta-intellisense-php/

**Comment by mattacosta** [comment]
@roblourens So I figured out a way to regenerate these, are you guys interested in a PR for this?

If so, there are two things to note:
1. I would have to move the functions over to their own file. The variables, constants, and keywords seem to be custom, and I don't know if they could be added.
2. I would also have to more or less guess at a whitelist for the documentation. Including all core and bundled extensions, plus a handful of common external extensions like curl, openssl, simplexml, etc results in a list that's about the same size as the old version with about 150 additional entries. PECL extensions have been left out entirely.

Additionally, in the future it should be possible to change the structure of the data. For example, parameters and return types could be separated into their own properties.

**Comment by roblourens** [comment]
I'm interested, where does the data come from?

**Comment by mattacosta** [comment]
@roblourens It is exported directly from PHP's `.manual.xml` file.
