### ISSUE TITLE
Emmet - Expand element only works if it's unique

### ISSUE THREAD

**Issue by Chippi** [Microsoft/vscode#33134]
- VSCode Version: 1.15.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Write app-list, expand with enter
2. Write app-list again. Expand wont show up, unless you remove 1 char.

![](https://lh3.googleusercontent.com/-BoOAn7L_Oxw/WZ_jKKwLb2I/AAAAAAAACHg/00gP8jZ5-z8W6iRiD8NjRX7E4bodpKeZACHMYCw/s0/2017-08-25_10-43-16.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@Chippi This is fixed in the latest Insiders. You can download it from https://code.visualstudio.com/insiders 

Can you try the Insiders and let me know if things work as expected?
