### ISSUE TITLE
couldn't open the doucument that I want to

### ISSUE THREAD

**Issue by AMYwkl** [Microsoft/vscode#33139]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
vscode-npm-script|eg2|0.2.0
vscode-npm|fkn|3.3.0
Angular2|joh|2.4.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@AMYwkl What document are you trying to open? How can this bug be reproduced?
