### ISSUE TITLE
azure-account extensions always blocks extension host startup by 300ms

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33138]
* open e.g. a folder and close all files
* run `./scripts/code.sh --performance`
* `F1 > Developer: Startup Performance`
<img width="953" alt="screen shot 2017-08-25 at 11 46 45" src="https://user-images.githubusercontent.com/5047891/29709048-3120d6fc-898b-11e7-9a0f-6754c75ced79.png">

**Comment by alexandrudima** [comment]
I'd recommend that the `activationEvents` for this extension be changed to an empty array.

If I understand this correctly, everyone that wants to use the API exported by this extension will have an extension dependency to this extension. That would make this extension activate when the other extensions activate.

---

I'd also wanna figure out why it takes 400ms to load the code... (even after making it activate on demand) ... that's a whooping large number IMHO.

**Comment by chrmarti** [comment]
The original thinking was that we should check for an existing login session as early as possible, but I don't think that should still hold now that the extension is built-in. We can activate on one of the commands (or a dependent extension activating). Not sure where the 400ms come from, one guess is the `keytar` native module taking its time. /cc @chrisdias

**Comment by chrmarti** [comment]
Fixed with #33422
