### ISSUE TITLE
VSCode hangs or freezes

### ISSUE THREAD

**Issue by peltsi212** [Microsoft/vscode#33149]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 4.4.0-81-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11

---

Steps to Reproduce:

I cannot say exact pattern what to do to repeat freeze.
I am editing .js file which contains es2017 javascript code
Freezing happens after many hours of editing.
Freezing have happened know 3 times.
If I remember correctly freezing happens when I switch back from other program.
I was not doing anything special just editing file.
During freeze I cannot move cursor with cursor key.
If I click with mouse, the cursor is not moved to point where I click.
Only place which shows some reaction is that I can click menu and then menu dropdown appears.
If select action like Command Palette nothing happens.
This is so for all menu items.
One exception is Help About. It shows information of visual studio code version.
If I click x to close VSCode application, that works.

Reproduces without extensions: Not tested

**Comment by Tyriar** [comment]
@peltsi212 a new version has been released 1.15.1, please try on that as a lot of changes go in between versions and this could have been fixed.
