### ISSUE TITLE
extension-editing extension is slow to startup

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33141]
* open e.g. a folder and leave a `.ts` file opened
* run `./scripts/code.sh --performance`
* `F1 > Developer: Startup Performance`

<img width="949" alt="screen shot 2017-08-25 at 11 51 10" src="https://user-images.githubusercontent.com/5047891/29709196-cba0590a-898b-11e7-8ac2-4d475d847c22.png">

**Comment by jrieken** [comment]
Cool. It does use `jsonc-parser` and `vscode-nls` unsure if its them...

**Comment by jrieken** [comment]
It takes ~450ms to load TypeScript, the rest is spent for extensionLinter.ts which loads a markdown and xml parser

**Comment by chrmarti** [comment]
@jrieken Should I just defer the module loading until I actually need the parsers?

**Comment by jrieken** [comment]
Yeah, that's what I did. With the new TS supports it's easy to do

**Comment by alexandrudima** [comment]
Nice !
