### ISSUE TITLE
Starting Code results in "PowerShell language features are disabled due to an unsupported LanguageMode: ConstrainedLanguage" message

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/vscode#33143]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|0.17.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
vscode-docker|Pet|0.0.16
vscode-icons|rob|7.12.0
shell-launcher|Tyr|0.1.3

---

Steps to Reproduce:

1. Start up Code
2. Open up the Terminal
3. Observe "PowerShell language features are disabled due to an unsupported LanguageMode: ConstrainedLanguage" error

If you look at the logs you see this:

```
[10:58:54] Language server starting...
powershell.exe started --
    pid: 11060
    exe: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    args: C:\Users\jreilly\.vscode\extensions\ms-vscode.powershell-1.4.1\scripts\Start-EditorServices.ps1 -EditorServicesVersion '1.4.1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.4.1' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'C:\Users\jreilly\.vscode\extensions\ms-vscode.powershell-1.4.1\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'C:\Users\jreilly\.vscode\extensions\ms-vscode.powershell-1.4.1\logs\1503655134-00c42217-4248-45b7-a606-46f526fd4a5a1503655127754\EditorServices.log' -SessionDetailsPath 'C:\Users\jreilly\.vscode\extensions\ms-vscode.powershell-1.4.1\sessions\PSES-VSCode-3976-523561' -FeatureFlags @()


PowerShell language features are disabled due to an unsupported LanguageMode: ConstrainedLanguage

powershell.exe terminated or terminal UI was closed
```

Interestingly, I have my terminal configured using `userSettings.json`:

```
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
```

And I can open those terminals just fine.  Note that the erroring version is using a different exe: `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe`.  

Can we configure the integrated to use the `sysnative` version as well?  Would that solve the problem?

**Comment by Tyriar** [comment]
Creating an issue in https://github.com/PowerShell/vscode-powershell should get you an answer.

On sysnative, you should use sysnative only if you're running the 32-bit version of VS Code on 64-bit Windows. Otherwise, use System32.

**Comment by johnnyreilly** [comment]
I'm sorry I didn't quite follow that? This is a bug in the powershell vscode extension?

**Comment by Tyriar** [comment]
@johnnyreilly if the dropdown says "powershell" or "powershell.exe" it's a regular terminal, if not it's the extension. Still, vscode-powershell is generally the best place to start for PowerShell issues as there's more PS expertise over there.

**Comment by backpacked** [comment]
This may help: https://blogs.technet.microsoft.com/kfalde/2017/01/20/pslockdownpolicy-and-powershell-constrained-language-mode/
