### ISSUE TITLE
Inconsistent font usage on welcome screen

### ISSUE THREAD

**Issue by io8titan** [Microsoft/vscode#33146]
- VSCode Version: Code - Insiders 1.16.0-insider (b9ac10234f86f145fdbcf066758934e0857d7592, 2017-08-25T05:24:57.523Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
PowerShell|ms-|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:
##I am using a Taiwanese Windows 10 where the default font is "MS JhengHei" and I also set the following in the registry to set MS JhengHei as default for most of the legacy Windows apps.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\GRE_Initialize] 
"GUIFont.Facename"="Microsoft JhengHei" 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes] 
"MS Shell Dlg 2"="Microsoft JhengHei" 
"MS Shell Dlg"="Microsoft JhengHei"

1. Start with welcome screen
2. The welcome screen's font for items on the right side is a mixture of the system default font MS Jhenghei which is used in other parts of the UI as well and some Ming serif font which looks out of place.
Could this be fixed to have a consistent UI?

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/30977406/29710907-ffca231c-89c4-11e7-8ef0-fa6bbc7c2684.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/27876

**Comment by chrmarti** [comment]
The default font for buttons wins over the general css font-family rule.
