### ISSUE TITLE
Cannot set property 'animationFrameDisposable' of null

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33145]
![image](https://user-images.githubusercontent.com/5047891/29711377-c482f6b0-8994-11e7-9a19-5379cf9543a0.png)

**Comment by mjbvz** [comment]
Verified by enabling smooth scrolling and scrolling around a bunch in the editor and panes. Let me know if something more specific is needed to verify this

**Comment by alexandrudima** [comment]
I also didn't have any repro steps, I spotted it in the built version. I've added an emergency if check that avoids the NPE
