### ISSUE TITLE
References peek is not revelead when smoothScrolling is enabled

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33140]
Insiders

- Open a file (e.g. `preferencesRenderers.ts`)
- Place the cursor at the end of the file
- Open another file (e.g. `configurationEditing.ts`) which has a method referenced in above file
- Find references for that method which opens the peek view that has the entry of the first file
- Open the first file from the peek view 

See that file is opened but peek view is not revealed

![kapture 2017-08-25 at 11 51 05](https://user-images.githubusercontent.com/10746682/29709183-bb152c50-898b-11e7-8edc-290e1bd9fb7f.gif)

**Comment by jrieken** [comment]
No changes from my side... May smooth scrolling @alexandrudima ?

**Comment by alexandrudima** [comment]
@sandy081 Does this reproduce when using `editor.smoothScrolling: false` ?

**Comment by sandy081** [comment]
@alexandrudima It does not happen when `editor.smoothScrolling` is `false`.

**Comment by alexandrudima** [comment]
Fixed via e070afceabc88e57190697c9a79dc3ab3a98d3d5
