### ISSUE TITLE
[folding] File contents scrolls if folding is turned off

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3314]
On testing #2994 

- open the User preferences and prepare for editing "editor.folding" 
- in another VS Code column open a file that uses indentation and scroll to some position
- remember the line number of the top line
- collapse any region

Observe: top line doesn't change (which is good)
- set "editor.folding" to false

Observe: file contents scrolls and the top line changes

**Comment by aeschli** [comment]
I fixed it by making sure the cursor position stays visible when collapsing a region (instead of making sure the top line is the same)

**Comment by aeschli** [comment]
- when clicking on a fold icon, I make sure that line stays visible
- in all other cases we make sure the current cursor line stays visible
