### ISSUE TITLE
Global context keys

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33154]
Need a global context key support that is available in all locations (editor, sidebar)

From @jrieken [here](https://github.com/Microsoft/vscode/issues/30981#issuecomment-318328816)

>It doesn't work like that. The resourceLangId is defined only once but there multiple values associated to it. Think of a tree of context key values, only descendants see values from their containing context key service. So exposing a context key value "side-ways" from an editor to the sidebar doesn't make much sense. There is no definite answer here. Maybe a new context keys that only lives in the global/root context key service is needed, something like activeResource and that must be updated whenever the active editor or explorer updates...

**Comment by jrieken** [comment]
> Need a global context key support that is available in all locations (editor, sidebar)

What? There is a global context that is available everywhere but child values aren't bubbling up to their parents. @sandy081 Is that what you are suggesting?

**Comment by sandy081** [comment]
@jrieken Its a usecase from #30981 where a value of a context key can be set globally as you suggested in the description.

**Comment by jrieken** [comment]
Closing after discussions

**Comment by pltrant** [comment]
What's the resolution?  A lot of language extensions have custom views, but said views are only relevant when viewing a file associated with that language.  Being able to auto hide those views when not needed will make for a better end user experience.
