### ISSUE TITLE
Treat .pac as javascript file?

### ISSUE THREAD

**Issue by Coresi7** [Microsoft/vscode#33155]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: None

.pac (Proxy auto config) file is a kind of javascript file which helps browser (or other app supports proxy auto configuration) find a proper proxy, so could you let vscode treat it as a javascript file?
pac wiki:
https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by mjbvz** [comment]
Fixed by #33245
