### ISSUE TITLE
Snippets are only loaded when language is loaded

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33158]
- VSCode Version: 1.15.1
- OS Version: win7x64

You have CSS snippet, like this:
```
"border": {
  "prefix": "bd",
  "body": [
    "border: ${1:1px} solid #${2:000};$0"
  ],
  "description": "border"
}
```
And if you will try to type "bd" in the <style>bd</style> - it will not show you ur snippet in the list.
**Until you will visit the tab with .css file.**
So, you have to start VS Code and make sure, that .css file "is not chosen". And you will not see any of your custom snippets.

**The same bug with javascript snippets and .js files.
It's not about language problem, but about custom snippets trigger system.**

GIF:
![css custom snippets dont work from the start](https://user-images.githubusercontent.com/24613274/29719755-1dc77ff4-89c0-11e7-83d0-1e37ad7a5f7a.gif)

**Comment by jrieken** [comment]
Yes, we only load snippets when the language for them is loaded. A html file that just uses css doesn't cause a load event of the css-language.

**Comment by user3323** [comment]
@jrieken, you wanna tell, that it's not a bug, but by-design feature? =\

**Comment by user3323** [comment]
@jrieken, now in ver. 1.17.0-insiders it works great!
