### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#33159]
- VSCode Version: 1.15.1
- OS Version: Windows 7 Ultimate x64

Hello! If possible, it would be nice to add html entities. For example, if I type "&" and emmet shows suggestions for a choice.

Examples of entities:
- &copy (Copyright) - &copy;;
- &reg (Registered trademark) - &reg;.

![figure](https://user-images.githubusercontent.com/29632606/29719697-8d68fe48-89fa-11e7-9096-c2992497fdc9.jpg)

Complete list of HTML entities: [HTML Entity List](http://www.freeformatter.com/html-entities.html)

**Comment by ramya-rao-a** [comment]
Have you tried using User snippets? See https://code.visualstudio.com/docs/editor/userdefinedsnippets

You can define these html entities as snippets and they will show up in the suggestion list.

**Comment by ramya-rao-a** [comment]
The catch with defining these as user snippets is that you will have to repeat them for all the file types where you would want to use them.

This is a good idea for an extension. The extension can register a completion provider that is triggered for `&`, maintains list of all the entities and provide them as completions

**Comment by ramya-rao-a** [comment]
cc @aeschli if he has any other ideas

**Comment by opencreative** [comment]
I tried snippets. I've added a few entities to the snippet, but they are all substituted.

![snippet](https://user-images.githubusercontent.com/29632606/29739255-8a5ec1e2-8a7c-11e7-8b89-9956cb9dd67f.gif)

**Comment by ramya-rao-a** [comment]
You have to set them as separate snippets
```
     "Copy": {
        "prefix": "&copy",
        "body": [
            "&copy;"
        ],
        "description": "Html Entity for copy"
	},
	 "Reg": {
        "prefix": "&reg",
        "body": [
            "&reg;"
        ],
        "description": "Html Entity for reg"
    }
```

`&` will not trigger the suggestions because suggestions are triggered only for what is considers as a word and `&` is not a word as per language definition.

You will have to use `Ctrl+Space` to manually trigger the suggestions.

If you make an extension and use the completion provider, then you can have `&` as a trigger character and you will get the suggestions on just pressing `&`

**Comment by opencreative** [comment]
If I understand correctly, do I need to create an extension? Will I be able to do this?

**Comment by ramya-rao-a** [comment]
You don't need the extension if you are ok with creating multiple snippets in User snippets as I have shown above. Then press `&`, then press `Ctrl+Space`

**Comment by opencreative** [comment]
@ramya-rao-a, ok I understood. Thank you! I really like the VS Code editor.

**Comment by jrieken** [comment]
Closing this issue because 'extension candidates' don't make us do code changes in this repo
