### ISSUE TITLE
The Shortcut key(Ctrl+R) isn't available after upgrade to v1.15.1

### ISSUE THREAD

**Issue by dengyue** [Microsoft/vscode#33150]
- VSCode Version: 1.15.1
- OS Version: WIN 10 /Ubuntu

Steps to Reproduce:

1. Choose the File-->Open Recent-->More(Ctrl+R), it will show the all recent open project.
2. But I use the shortcut key(Ctrl+R),  nothing for me.  and the status bar show the Ctrl+R was pressed, Waiting for the second key.....

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@dengyue 
It sounds like you may have a key binding utilizing a chord (Control+R + AnotherKey)
You can search in the key findings editor for 'Control+R' and see all bindings using this key.

**Comment by rebornix** [comment]
@dengyue can you check whether you run into the problem @cleidigh (thanks!) mentioned above?
