### ISSUE TITLE
Git: handle repository creation & deletion gracefully

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33153]
This is still missing from the multiroot work.

**Comment by roblourens** [comment]
One issue at least:

- I have two folders next to each other, `gittest/` and `gittest2`, in a workspace
- `git init` in both
- in `gittest/`, do `rm -rf ./git/`
  - That folder's section correctly disappears from the sidebar
- `git init`
  - It correctly appears in the sidebar again
- `rm -rf ./git/`
  - On the second time, it doesn't disappear. 🐛 
- I click the 'refresh' button on that section, and nothing happens
  - Git output view shows:
```
...
git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
```

- Maybe another 🐛 , at this point if I try to commit `gittest/` by clicking the checkmark on its section, it actually commits `gittest2`

**Comment by joaomoreno** [comment]
Great catch!
