### ISSUE TITLE
Open a new terminal with on-the-fly shell

### ISSUE THREAD

**Issue by laszlofarkas** [Microsoft/vscode#33156]
Feature-request
Integrated-terminal

I wonder if I could open a new terminal with a non-default shell.

Mostly I'm working with PowerShell but, when I want to use Git Bash (or whatever different shell), I have to switch the default shell to Git, open a new terminal and then I have to switch the default back to PS.

It would be more comfortable to select the shell for the new terminal without any "default-shell" configuration. With a dropdown or with a different button, or maybe with a pop-up window.

**Comment by Tyriar** [comment]
This extension should solve your problem. https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
