### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5052).

### ISSUE THREAD

**Issue by JohannBlake** [Microsoft/vscode#33157]
I use to be able to debug my Electron app's main process. Now after an update of VS Code, I get the error:

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5052).`

My configuration has these settings:

```
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "/usr/local/bin/electron",
            "program": "${workspaceRoot}/main.js",
            "webRoot": "${workspaceRoot}"
```
I am able to run my Electron app by starting it with:

`npm start`

when I execute this command from a terminal in the project's root directory. I am using the latest version of VS Code (1.15.1)

**Comment by weinand** [comment]
What version of Electron are you using?

Starting with Electron 1.7, only the "inspector" protocol is supported, which requires that Electron is started with the "--inspect" flag (instead of "--debug").

Try to add a `"protocol": "legacy"` to your launch config.
This will pass the correct flags to electron and uses the correct protocol in VS Code.

**Comment by JohannBlake** [comment]
I took your suggestion and set protocol to legacy and it now works. Clearly something changed in newer versions since I last debugged a few months ago because that option was not in the configuration. Thanks.

**Comment by weinand** [comment]
Yes, in VS Code we changed the default protocol to "inspector", so VS Code launched electron with "--inspect", which is probably not supported on the electron version you are using.
