### ISSUE TITLE
Visual issue - empty screen on program start

### ISSUE THREAD

**Issue by Britskiy** [Microsoft/vscode#33152]
When I run an empty editor window and hover over or a place where there should be an element of the interface this element flashes and all editor "empty" I can't see edit area.

- VSCode Version:1.15.1 
- OS Version: MacOS 10.11.6 

Steps to Reproduce:

1. Run
2. Cry

Image: https://prnt.sc/gcwwel

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@Britskiy it's not just that you don't have a file opened? 

Also could you be more clear what you mean by "this element flashes"?

**Comment by Britskiy** [comment]
Opened files: http://prntscr.com/gd7oj9
Focused on UI element (sidebar): http://prntscr.com/gd7or6 
When I change focus all elements hide.

**Comment by AvatarWeb1** [comment]
Provenance : Courrier pour Windows 10

De : Britskiy
Envoyé le :samedi 26 août 2017 04:21
À : Microsoft/vscode
Cc : Subscribed
Objet :Re: [Microsoft/vscode] Visual issue - empty screen on program start(#33152)

Opened files: http://prntscr.com/gd7oj9
Focused on UI element (sidebar): http://prntscr.com/gd7or6
When I change focus all elements hide.

**Comment by Tyriar** [comment]
@Britskiy does it still happen when you run `code --disable-gpu`

**Comment by Britskiy** [comment]
@Tyriar as I was say before - no. After that everything runs perfect

**Comment by bpasero** [comment]
Closing, workaround is to run with --disable-gpu.
