### ISSUE TITLE
When toggling Full Screen off, the menu bar thinks Alt is being pressed

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#33168]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.1.24
python|don|0.7.0
wordcounter|kir|1.2.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
blank-line-organizer|rin|0.1.2
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

When toggling out of Full Screen (i.e. returning to a normal window), or when coming out of Zen Mode, the menu bar is a bit confused. The letters are underlined, as if the Alt key is being held down. See the attached screenshot.
![vscode_menubar](https://user-images.githubusercontent.com/3789849/29731051-cb92167a-89da-11e7-8acc-b6cefae9f38b.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14637
