### ISSUE TITLE
Menu not usable with Global Menu widget in KDE

### ISSUE THREAD

**Issue by Programie** [Microsoft/vscode#33166]
- VSCode Version: 1.15.1-1502903936
- OS Version: Ubuntu 17.04 with KDE 5

Steps to Reproduce:

1. Add the Global Menu widget to the KDE panel
2. Configure the menubar style of KDE to use the application menu widget
3 Try to open the menu of Code (in Global Menu) - the menu does not open

Reproduces without extensions: Yes

**Comment by Programie** [comment]
I just tested it again with the latest Insider build (version 1.17.0-insider) and the menu is now working as expected.

**Comment by FloVid** [comment]
That is great, did you try open a file without have to minimize and maximize the window?

**Comment by Programie** [comment]
Yes, the menu always works for me now.

Empty window -> menu works
Open a folder -> menu works
Open a file -> menu works
