### ISSUE TITLE
Another explorer.sortOrder option

### ISSUE THREAD

**Issue by oojacoboo** [Microsoft/vscode#33169]
Firstly, I'd like to see the following...

1. .dotHiddenDirectoriesAndFiles
2. directories
3. files

(all alphabetical)

Currently the `mixed` `sortOrder` is the closest thing.  However, it mixes directories and files.  It is nice to have the directories grouped together.

I'm sure everyone has their own preferences when it comes to this and I've read a number of issue tickets around the sort ordering.  Maybe it's possible to come up with a list of `sortOrder` options that solve everyone's quirks.  Or maybe a more customizable option here would be better so that users can build the ordering to best fit their needs.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
