### ISSUE TITLE
can not open when no internet

### ISSUE THREAD

**Issue by xuwanwanTT** [Microsoft/vscode#33160]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. close your internet
2. open vscode,you can not open it

**Comment by Tyriar** [comment]
Does an empty window appear? Does anything happen? If not, does the same thing happen after you restart the machine?

**Comment by xuwanwanTT** [comment]
restart the machine have no help, so I restall  vacode and restart the machine, and the problem is done, now, I can not reproduce the problem.

**Comment by Tyriar** [comment]
Weird. Oh well, glad you got it fixed 😃
