### ISSUE TITLE
PHP snippets no longer work outside of <?php ?> tags

### ISSUE THREAD

**Issue by jreljac** [Microsoft/vscode#33164]
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create PHP snippet 
`"TEST": { "prefix": "TEST", "body": ["TEST"], "description": "TEST" }`
2. Open new file
3. Set language to PHP
4. Add `<?php `  to new file
5. Make sure cursor is after `<?php`
6. `Ctrl+Shift+P` --> **Insert Snippet** --> Type **TEST** & hit `Enter`
7. TEST appears in file
8. Move cursor to before `<?php` - repeat step 6
9. As you type **TEST** Code tells you "_There are no entries to pick from_"

I would expect PHP snippets to work anywhere on a .php file, not just inside the `<?php` `?>` tags OR that html (or some other language) snippets would be available outside the `<?php` `?>` tags (They do not)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I do get HTML snippets outside of `<?php` - I think this is what is supposed to happen by design. Are you sure you don't?

**Comment by jreljac** [comment]
@roblourens After more checking you're right...html snippets work outside of the `<?php` `?>` tags.  Thanks for making me try it out...
