### ISSUE TITLE
old stype emmet not working

### ISSUE THREAD

**Issue by Walt-D-Cat** [Microsoft/vscode#33165]
- VSCode Version: 1.15.1 x64
- OS Version: w10

Steps to Reproduce:
1. setting file ->    "emmet.triggerExpansionOnTab": true
2. type `div>` 
3. TAB and expansion does not occur

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
`div>` is not a valid emmet abbreviation.
Try `div`
