### ISSUE TITLE
Find In Files broken

### ISSUE THREAD

**Issue by Rhywun** [Microsoft/vscode#33163]
Find In Files behavior is not predictable. If I have multiple files open which I know contains the search term, not all matching files will be shown.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
xml|Dot|1.9.2
Ionide-fsharp|Ion|2.33.2
vscode-insertdatestring|jsy|2.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
vscode-sql-beautify|sen|0.0.4

---

Steps to Reproduce:

1. Open multiple individual files which you know contains a search term.
2. Perform a Find In Files for the search term.
3. In my case, one matching file was displayed in the results.
4. Select the tab of another file - doesn't matter if this file matches or not.
5. Run the search again (hit Enter in the search field or use the Refresh icon)
6. This time multiple matching files are displayed.

Reproduces without extensions: Yes, except this time zero matches were found, then one, then two, depending on which file tab was selected.

**Comment by roblourens** [comment]
Can you give an example of a file and query that sometimes matches, and sometimes doesn't? And is it consistent, like always matching or never matching in the same scenario?

It might make a difference whether the file is open or not open, since search is implemented differently for the two cases.

**Comment by Rhywun** [comment]
I can't give actual code but I was able to reproduce the issue on 4 identical files with dummy text (attached). All 4 files are open when I perform a search for "nisi" - only 2 results were returned (screenshot attached). When I selected a different tab and refreshed the search, all 4 results were returned (2nd screenshot attached.) Repeating this process gives different results, sometimes 3 results are shown for example.

[lorem1.zip](https://github.com/Microsoft/vscode/files/1257841/lorem1.zip)

Thanks

**Comment by roblourens** [comment]
Do you have `files.encoding` set?

**Comment by roblourens** [comment]
Never mind, I see the issue - I regressed search in a window that doesn't have a folder open.

**Comment by Rhywun** [comment]
Correct, I don’t have a folder open.

**Comment by Rhywun** [comment]
I’ll check tomorrow, if you still need this.

**Comment by roblourens** [comment]
I don't need an answer to the `files.encoding` question anymore. Fix will be in tomorrow's Insiders build, and the next stable release.

**Comment by Rhywun** [comment]
Great, thanks
