### ISSUE TITLE
Switching to insiders version of code broke opening a file by running 'code <filename>'

### ISSUE THREAD

**Issue by ekoschik** [Microsoft/vscode#33167]
- VSCode Version: Code - Insiders 1.16.0-insider (0626479859787fa87c7c57ba19195b939050a843, 2017-08-21T07:17:17.874Z)
- OS Version: Windows_NT x64 10.0.16275
- Extensions: none
---

Steps to Reproduce:

1. Have normal version installed, then install insiders version
2. From cmd, run 'code <filename>'
3. uninstall original version (maybe this will work?)
4. rename code insiders to code since that could work right?
5. Nope, launch from cmd just broken.  Opens file but doesn't bring to foreground and cmd line gets set in wacky state until hard break. :'(

**Comment by Tyriar** [comment]
You need to use `code-insiders <filename>`
