### ISSUE TITLE
VSCode does not auto update from 1.15 to 1.15.1 on macOS Sierra

### ISSUE THREAD

**Issue by uday0408** [Microsoft/vscode#33170]
- VSCode Version: 1.15
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Launch VSCode 1.15. Wait for a while or select check for updates.
2. When the banner for version update shows up, select "update now" or from main menu "restart to update". VSCode shuts down and when manually launched again, it is not updated to 1.15.1.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Did you check https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 ?

**Comment by uday0408** [comment]
The BKM on  [#7426 (comment)](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150) worked. My VSCode updated to 1.15.1.

I ran:
`sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*`

The `xattr -lrv Visual\ Studio\ Code.app` did not show any attributes. 

I watched the console.app system.log and there was only a harmless error about removing temp bundle.

Thanks
