### ISSUE TITLE
Pointer is overlapping the text

### ISSUE THREAD

**Issue by yosualb** [Microsoft/vscode#33178]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Move the pointer to > 100 columns and it start to overlapping the text.

Reproduces without extensions: No

**Comment by yosualb** [comment]
![image](https://user-images.githubusercontent.com/3480390/29739159-658cd176-8a61-11e7-80b9-fbaf8bc040e2.png)
![image](https://user-images.githubusercontent.com/3480390/29739161-780aa558-8a61-11e7-9740-2a8130283cb1.png)

**Comment by alexandrudima** [comment]
I could reproduce on Windows, with the default settings, on a line around column 800. From experimentation, I have noticed that the rounding errors are negligible up to column 300, so that is the new value I have hard-coded in the view line rendering.
