### ISSUE TITLE
Fold action does not always fold the inner most uncollapsed region

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3317]
On testing #2994

In the following snippet place the caret on 'hello' and perform a 'Fold' operation:
```
class xyz {
	foo() {
		if (a == b) {	
			hello
		} else {
			world
		}
	}
}
```
Observe: 'foo()' get collapsed but I would expect that the 'if' gets collapsed.

**Comment by aeschli** [comment]
duplicate of #3398
