### ISSUE TITLE
Terminal/Output panel print '[Object]' instead of value from level-3 on within json disturbing debugging

### ISSUE THREAD

**Issue by gemmi** [Microsoft/vscode#33174]
- VSCode Version: 1.14.0
- OS Version: win7/64bit

Steps to Reproduce:

1. js:  
```js
console.log({a: {b: {c:  {d:1} } }})
```
2. print in Output Panel( same as Termial Panel):  
```js
{ a: { b: { c: [Object] } } }
```

Reproduces without extensions: No

**Comment by weinand** [comment]
What version of node are you using?

**Comment by weinand** [comment]
`{ a: { b: { c: [Object] } } }` is the expected output.
Just run node from the command line and you will get the same result.
So this behaviour is independent from VS Code.
