### ISSUE TITLE
Extremely high CPU load

### ISSUE THREAD

**Issue by virgo-coder** [Microsoft/vscode#33176]
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Install vscode
2. Install C/C++ tools extension
3. Open vscode and write some code, then the CPUs are fully loaded

<img width="456" alt="2017-08-26 1 17 12" src="https://user-images.githubusercontent.com/31362041/29738906-e9e3820c-8a62-11e7-8287-b130afcf09b3.png">

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Please create an issue in the cpptools repo https://github.com/Microsoft/vscode-cpptools
