### ISSUE TITLE
set  auto-detected tasks  to false

### ISSUE THREAD

**Issue by anchenbaba** [Microsoft/vscode#33172]
- VSCode Version: 1.15.1
- OS Version: win10

I don't want to use tasks with auto-detected
can i set it to false ?
i only use my Custom tasks

because when i using Task auto-detection
ctrl + shift + p   select tasks:run task
use a lot of time in scanning my project

**Comment by yume-chan** [comment]
Search for `autoDetect` in settings, there are several.

**Comment by dbaeumer** [comment]
Each provider can currently only be disabled separately. For example ` "gulp.autoDetect" = false`

**Comment by anchenbaba** [comment]
tks
