### ISSUE TITLE
suggest VS Code support copying feature from file type

### ISSUE THREAD

**Issue by vimcaw** [Microsoft/vscode#33175]
Such as, html file can use Emmet feature, css file can use Color Picker UI feature, js file can use auto complete, and some feature of extensions, but they only work on certain file type.
Suggest VS Code add config like this:
```json
"copying-feature": {
    "ejs": "html, js",
    "stylus": "css"
}
```
And then, ejs file can use all feature from html and js file, and stylus file can use all feature from css file.

**Comment by Tyriar** [comment]
@ramya-rao-a I think you're fairly familiar with the state of embedded languages?

**Comment by ramya-rao-a** [comment]
This is not about embedded languages.

This is getting features of one or more languages in another.

You can do this today by using the `files.associations` setting. But this is a 1:1 mapping i.e you cannot map multiple languages to a single language.

`copying-feature` is ambiguous. Different features work in different ways. There can be conflicts when multiple languages contribute to the same feature.

Instead it would be helpful to see which features you'd like to see in other languages and get support for that particular feature.

Example: Html files have emmet. You want the same for `ejs`. You can get that by using the setting `emmet.includeLanguages`. See https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration

@rebornix can speak about the color-picker ui feature.

**Comment by vimcaw** [comment]
Thanks, but I saw many language don't support the features which have been supported by similar language, such as, stylus don't have Color Picker UI, .ino file (Arduino file) don't have the features of C and C++, that is why I suggest this.

**Comment by rebornix** [comment]
Speaking of the color picker feature, it relies on language extensions to detect the correct range of colors, I don't think a simple language mode mapping can work perfectly. Mapping `ejs` to `html` and ask HTML language server to provide the color ranges doesn't make sense here (it may totally break). Maybe it's useful for other features.

**Comment by Tyriar** [comment]
Closing this off as this sort of support should be provided at the language extension level, not a blanket setting. Plus we already have files.associations for setting the language for file types.
