### ISSUE TITLE
Missing codelens

### ISSUE THREAD

**Issue by pointcache** [Microsoft/vscode#33182]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I opened a folder with cs files
2. No codelens

Reproduces without extensions: Yes/No

```
"typescript.implementationsCodeLens.enabled": true,
    "typescript.referencesCodeLens.enabled": true,
    "javascript.referencesCodeLens.enabled": true,
    "editor.codeLens": true
```
my user settings

**Comment by pointcache** [comment]
yeah ... typescript.. sure

**Comment by mjbvz** [comment]
This sounds like an issue with the C# extension. Please try filing an issue against that extension instead
