### ISSUE TITLE
Group Policies (GPO) support

### ISSUE THREAD

**Issue by alexhass** [microsoft/vscode#33185]
I need to pre-configure and force-configure settings in VSCode for a larger team. We need to make sure all of them are using the same settings or we end with a mess of tabs/spaces (2/4/8) just as one example.

Some other things that come in mind are:
- disable automatic update
- add required addons
- disable bad addons
- all settings that can be made in the json file.

If this is already possible and I just missed the documentation let me know, please.

**Comment by Tyriar** [comment]
We don't have group policy support AFAIK.

You might find these useful though:

- https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
- https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by joaomoreno** [comment]
Our support is limited to workspace configurations. Please leverage that in order to achieve a shared configuration.

**Comment by yamlfd** [comment]
Can you reopen this case, please? I do not see a solution here yet.

If you can share GPO per user that may work either. Than I make it global. But there are always settings like disable automatic update that need to be global. I'd like to install the software with an MSI via AD. That means I need full control over auto update. Name it global or per user, but I need to force it globally.

**Comment by yamlfd** [comment]
> This creates a extensions.json file located in the workspace .vscode folder where you can list extensions.

How should this work? All workspaces should start with the same settings. We have hundreds of projects what means hundreds of .vscode folders. No idea how this could work without GPO.

**Comment by yamlfd** [comment]
Please reopen the case! There are a lot of people who need this support (preconfiguration of settings):

https://github.com/Microsoft/vscode/issues/36499
https://github.com/Microsoft/vscode/issues/27758
https://github.com/Microsoft/vscode/issues/27972

**Comment by joaomoreno** [comment]
Merging into #147756
