### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by johnnycsy** [Microsoft/vscode#33187]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.10.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
beautify|Hoo|1.1.1
phpcs|ika|0.7.0
hg|mrc|1.1.5
team|ms-|1.122.0
java|red|0.8.0
perforce|sle|2.1.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I cannot reproduce given there are not steps.
