### ISSUE TITLE
"spawn ENAMETOOLONG" when searching in large workspaces

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#33189]
- VSCode Version: code-oss-dev 1.16.0 (9066eedcf7597779e3a710bf997d0d9f8748d597)
- OS Version: Windows_NT x64 10.0.15063
---

I have a [rather large `.code-workspace` file](https://github.com/HaxeFlixel/flixel-demos/blob/dev/flixel-demos.code-workspace) with 81 sub-directories. When I try to use find in files in that workspace, it fails with a `spawn ENAMETOOLONG` error:

![](http://i.imgur.com/zJPhuUY.png)

---

Steps to reproduce:

1. Clone [this](https://github.com/HaxeFlixel/flixel-demos) repository.
1. Open [the workspace file](https://github.com/HaxeFlixel/flixel-demos/blob/dev/flixel-demos.code-workspace).
1. Try to search for anything.

**Comment by Tyriar** [comment]
@Gama11 how long is the path that you clones the repository in?

**Comment by Gama11** [comment]
It's `C:\HaxeToolkit\haxe\lib\flixel-demos\git`, so not that long.

**Comment by roblourens** [comment]
I was wondering how many folders people would add to a workspace 😁 - this generates a really long command, but there are some easy things I can do to make it shorter. Thanks for the report!

**Comment by Gama11** [comment]
Works now. :)

**Comment by roblourens** [comment]
Excellent! It's still theoretically possible to run in to this, although it will be a lot harder now. But please let me know if you see it again.

**Comment by ChrisJefferson** [comment]
I'm seeing this error, on Windows 1.17.2.

**Comment by ChrisJefferson** [comment]
Oh, i deleted the .vscode directory and the problem went away. if you want me to try and recover a copy, to reproduce the problem I can, else I am happy now :)

**Comment by roblourens** [comment]
I am guessing that you had a ton of search.exclude entries in your workspace settings. This should be very difficult to hit without a multiroot workspace, so I'm curious what the settings were.

**Comment by ChrisJefferson** [comment]
I used the `ignore-gitignore` package to add files from `.gitignore` to vscode's ignore list. It turns out that package recursively searches the current directory for .gitignore, and I'm in a project with a bunch of subprojects.

This ended up adding 2,700 lines to settings.json.

**Comment by ChrisJefferson** [comment]
If you want, I can give you instructions to get exactly the project I'm using, it's open source and on github.

**Comment by roblourens** [comment]
> This ended up adding 2,700 lines to settings.json.

Yeah that would do it. I understand the problem, I'm not going to do anything about it right now.

You can avoid searching in .gitignore'd files by expanding the search viewlet details and toggling the "Use Ignore Files" button
