### ISSUE TITLE
folding method has a problem

### ISSUE THREAD

**Issue by amin67v** [Microsoft/vscode#33186]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1
unity-debug|Uni|1.2.1

---

Steps to Reproduce:

1. try to fold this method, and this doesnt fold the entire method :
```
    void aaa()
    {
        var bbb = 50;

#if CCC
            var ddd = 10;
#endif

    }
```

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
The current folding is purely indentation based.
What you are looking for is #3422
