### ISSUE TITLE
Can't read full InputBox validation error message if it is too long.

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode#33181]
![image](https://user-images.githubusercontent.com/15821566/29739539-0f2306f0-89f5-11e7-8e4a-bc7514b4d49b.png)

The message doesn't have a tooltip or any other means to show the full text.

**Comment by anirudhrb** [comment]
Is mentoring available for this?

**Comment by bpasero** [comment]
I added support for the input message and validation to show up in the hover when hovering over the item in the quick pick.
