### ISSUE TITLE
switching between editor tabs scrolls down past cursor repeatedly

### ISSUE THREAD

**Issue by negspect** [Microsoft/vscode#33198]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
unity-debug|Uni|1.2.1

---

Steps to Reproduce:

1. open a file with Ctrl+P.  put cursor on line 100, and center line 100 on screen.  note the top line number.
2. open another file with Ctrl+P.  put cursor on line 100, and center line 100 on screen.  note the top line number.
3. click on the tab for the first file.  cursor will not be visible as line 100 will be scrolled off the top of the screen, top line will be anywhere from 20 to 120 lines greater than it was before.
4. click on the tab for second file.  cursor will cursor will not be visible as line 100 will be scrolled off the top of the screen, anywhere from 20 to 120 lines greater than it was before.
5. click on the tab for the first file again.  note that each time you click back to a tab, it has scrolled even farther from the cursor and what was last visible, leaving you to search for whatever the heck you were just reading when you went to reference another file.  

this is really annoying.

 

Reproduces without extensions: Yes/No

**Comment by negspect** [comment]
this problem appears to be related to CodeLens, i tried adding "editor.codeLens": false, to my config, and it stopped happening.  the files i am editing are large c# classes.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/32397
