### ISSUE TITLE
Settings to make Preview behave as if it were hovered

### ISSUE THREAD

**Issue by iMatthias** [Microsoft/vscode#33192]
- VSCode Version: July 2017 (Version 1.15), 64-bit
- OS Version: Windows 10 64-bit

Reproduces without extensions: Yes

Steps to Reproduce:

1. Open a text file. The preview section is not hovered

![preview-no-hover](https://user-images.githubusercontent.com/13993613/29742685-05ac1950-8a49-11e7-965f-ea8a43d01c87.png)

2. Open a text file. Hover a mouse over the preview section. The current text area is displayed with a white/gray background in the preview section.

![preview-hovered](https://user-images.githubusercontent.com/13993613/29742680-feb7b262-8a48-11e7-9795-0ffd627a6fba.png)

Question:

I'm wondering if there is a setting to make the preview section always be displayed as in the second picture without the need of hovering a mouse. This will make it easy for users to identify where they are located easily.

I am opening an issue here instead of StackOverFlow because I feel like this was how it worked before, but I could be wrong. Please let me know if this issue should be posted on StackOverFlow instead.

Thanks in advance.

**Comment by yume-chan** [comment]
` "editor.minimap.showSlider": "always"`

**Comment by iMatthias** [comment]
Thanks @yume-chan, your suggestion solved my problem. It does exactly what I wanted it to.

While the keyword `always` may be obvious enough, it seems missing in the comment in `User Settings`. Here's what I can see from the settings file:

    // Controls whether the minimap slider is automatically hidden.
    "editor.minimap.showSlider": "mouseover",

I guess it would be good to provide a list of available keywords here. For instance, `lineNumbers` is documented as such:

	// Controls the display of line numbers. Possible values are 'on', 'off', and 'relative'. 'relative' shows the line count from the current cursor position.
	"editor.lineNumbers": "relative",

**Comment by alexandrudima** [comment]
Thanks to @brokenbacon , the description now contains the possible values.
