### ISSUE TITLE
Fold/Unfold action does not support multiple regions

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3319]
On testing #2994

In this snippet range select both 'foo' and 'bar' methods and then perform 'Fold' operation.
```
class xyz {
	foo() {
		hello
	}
	bar() {
		world
	}
}
```

Observe: only 'foo' is collapsed.
I would expect that all regions overlapping with the text selection are collapsed.

**Comment by aeschli** [comment]
duplicate of #3403
