### ISSUE TITLE
Revert extensionHost process.kill fix, once we use Electron with Node 8

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33196]
See https://github.com/Microsoft/vscode/issues/32990

This can probably be reverted, once Electron is using Node 8.

**Comment by alexandrudima** [comment]
Electron 2.0 will be reverted before we ship, so let's postpone this again ...

**Comment by roblourens** [comment]
FYI @weinand in case we see any EH debug weirdness.

**Comment by weinand** [comment]
@roblourens thanks for the heads-up.

**Comment by isidorn** [comment]
Verified via code review and that I can no longer repro the original issue https://github.com/Microsoft/vscode/issues/32990
