### ISSUE TITLE
Additional predefined variables for substitution in launch.json

### ISSUE THREAD

**Issue by Dimpl** [Microsoft/vscode#33191]
Could a ${relativeDir} variable be added which gives the directory of the file, relative to ${workspaceRoot}? i.e. ${relativefile%${filebasename}}. This would be useful in launch.json and related files (eg. tasks.json).

**Comment by weinand** [comment]
`${fileDirname}` does not work for you?

**Comment by Dimpl** [comment]
I am working with Windows Subsystem for Linux, so only relative paths work.

**Comment by isidorn** [comment]
PRs are welcome, code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L20

**Comment by Dimpl** [comment]
@isidorn Thanks for the code pointer. I didn't notice your reply until now, and have found another approach which doesn't require this variable.
