### ISSUE TITLE
new version vscode display error data on special conditions

### ISSUE THREAD

**Issue by githubao** [Microsoft/vscode#33203]
hey,guys. i am an old vscode user from China, a few days ago when i updated my vscode to version 1.15.1, i encountered some problems. i saw different contents in vscode vs other text editors(like vim and sublime3) while those editors show correct, so i wonder is it my fault or something goes wrong with vscode. following is details.

the plain txt is there:
[issue.txt](https://github.com/Microsoft/vscode/files/1254141/issue.txt) 
![issue](https://user-images.githubusercontent.com/8923601/29747117-71b0822a-8b21-11e7-9b96-c2193ccb5148.png)

my computer is Windows 7 64 bit(the same on ArchLinux) 
here is vscode infos:
version: 1.15.1
commit: 41abd21afdf7424c89319ee7cb0445cc6f376959
date: 2017-08-16T18:07:2S.676Z
Shell: 1.6.6
render: 56.0.2924.87
Node: 7.4.0
arch: x64

**Comment by Tyriar** [comment]
@rebornix any ideas based on what it says?
