### ISSUE TITLE
.hidden directory and file opacity

### ISSUE THREAD

**Issue by oojacoboo** [microsoft/vscode#33207]
I would like to suggest an improvement for the file explorer.

Basically, I'd like hidden files and directories to be able to have a lower opacity than the rest of the directories/files in the tree.

**Comment by jublo** [comment]
@oojacoboo How do you define hidden files and directories?

I would define them like this:

- On Windows, use the file system attributes.
- On Linux and macOS, use dotfiles.

**Comment by oojacoboo** [comment]
@jublo I define them the same.  I guess I'm more referring to linux/mac since I don't use Windows.  But yes, I'm speaking about those types of files and having the ability to decrease the opacity.  As it is now on mac/linux, it's difficult to see the leading "dot".  Which makes the files and directories appear to be the same as normal ones.

I do want them in the list, as they're needed for development.  I just want them to appear differently, and an opacity change makes the most sense.  Thanks.

**Comment by mattacosta** [comment]
I'd like to see this too, except it should use the project's `.gitignore` file to figure out what should be greyed-out.

**Comment by oojacoboo** [comment]
I definitely wouldn't want it relying on the .gitignore file.  We commit a lot of hidden directories and files.  The idea is to have hidden files and directories be visually different from standard files.

@mattacosta if you don't want to see the files, you could always add them to your `files.exclude` list.

**Comment by mattacosta** [comment]
Hmm, in my use case I would still want to see the config and/or generated files, so it would be more for visual confirmation that files wouldn't be committed, but I guess status badges on file icons would technically be better suited for that.

It does make more sense to have greyed-out files and directories be equivalent to what the OS file explorer does too.
