### ISSUE TITLE
when cursor between } and ) together, i want it focus on }, not )

### ISSUE THREAD

**Issue by zlbwonder** [Microsoft/vscode#33201]
os: window10
code version: 1.16 .0 insider

when cursor between }), may be it should focus on }, the issue like this:
![cursor](https://user-images.githubusercontent.com/3206813/29746315-82caa37e-8b08-11e7-8e09-08e98bffb24c.png)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
