### ISSUE TITLE
Unable to bind Cmd+` in key bindings

### ISSUE THREAD

**Issue by hgl** [Microsoft/vscode#33204]
- VSCode Version:
Version 1.16.0-insider (1.16.0-insider)
- OS Version:
macOS High Sierra Beta7
Steps to Reproduce:

1. Press <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>cmd</kbd>+<kbd>s</kbd>
2. Bind <kbd>cmd</kbd>+<kbd>`</kbd> to any command

Only <kbd>cmd</kbd> is displayed. I have disabled "Move focus to next window" option in the OS keyboard shortcuts settings, so nothing is intercepting that key combination. And I can register that key binding in atom.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@hgl 

Are you using an ANSI, ISO or JIS physical keyboard ?

**Comment by hgl** [comment]
@alexandrudima American keyboard comes with MacBook Air, I guess it's ANSI?

**Comment by hgl** [comment]
I bound Cmd+` to Find. Interestingly, the find menu item in the top menu bar shows the keyboard shortcut, but pressing the key combination does nothing.

**Comment by alexandrudima** [comment]
I'm asking about it, as Chromium has some nasty code where the scan codes of IntlBackslash and Backquote are swapped in the keyboard events for ISO keyboards -- see https://github.com/Microsoft/vscode/issues/24153#issuecomment-297986346.

We have some code which undoes the swap that Chromium does and I wanted to rule that out as a possible source for `` ` `` not working.

An ANSI keyboard would look like this (source -- https://apple.stackexchange.com/a/106059):
<img width="669" alt="screen shot 2017-08-30 at 15 59 06" src="https://user-images.githubusercontent.com/5047891/29876121-2f1261ea-8d9c-11e7-80c8-09a771af0875.png">

---

Yes, the keybindings labels reflect the configured keybindings. So the top level menu would show what we expect to receive.

---

The fact that we don't get a ``cmd + ` `` in the define keybinding box is problematic, as it indicates that we are not receiving the event. If you open this page in Chrome on your machine, is `` cmd + ` `` registered/received in there ?
https://jsfiddle.net/v1gz5c5m/1/

**Comment by hgl** [comment]
Pressing `` cmd+` `` gives

```
keydown --- code: Backquote, keyCode: 192, key: `
keydown --- code: MetaLeft, keyCode: 91, key: Meta
```

Chrome version `Version 60.0.3112.113 (Official Build) (64-bit)`

**Comment by hgl** [comment]
I was unclear in my description about binding to Find. I couldn't bind `` cmd+` `` to Find directly in the UI opened by `cmd+k cmd+s`, I manually added that binding to keybindings.json.

You're right, the event are not being received in vscode. But looks like it's fine in chrome, and I'm able to bind it in atom.

**Comment by hgl** [comment]
I'm sorry, but strangely it's working now. I don't think I touched any related settings.

**Comment by alexandrudima** [comment]
I'm really not sure what would have caused this.
