### ISSUE TITLE
How can we get a Live Preview Button for php  & web develop which will refresh the browser window automatic when we save the code just like Bracket

### ISSUE THREAD

**Issue by ta-riq** [Microsoft/vscode#33202]
We need to get a extension which provide live preview just like Bracket. And in that extension we will also can set up local server for php development. And need to make the  browser window refresh when we save the code from editor, And it will auto reload the page we are visiting and moreover the browser will  show the file which we are editing. Just like bracket.

**Comment by ta-riq** [comment]
We badly need this feature and i was in doubt from where to send future request.

**Comment by Tyriar** [comment]
We defer live preview and PHP support to extensions:

- https://marketplace.visualstudio.com/search?term=live%20preview&target=VSCode&category=All%20categories&sortBy=Relevance
- https://marketplace.visualstudio.com/search?__navigationState=%5Bobject%20Object%5D&term=php&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by ta-riq** [comment]
Sir, With due respect, you make a mistake. Theres no extention like I descripted avobe issue. May be its not a issue But theres no well extention for this support. only for HTML preview is available. I dopnt know how you made this issue closed. May be someone will start making one for me..

**Comment by ta-riq** [comment]
#33202
@Tyriar

**Comment by Tyriar** [comment]
We will not add support for this to the editor out of the box, it's up to extension authors (current and present) to fill this functionality.
