### ISSUE TITLE
Wrong syntax highlighting when combining JSX and Flowtype syntax

### ISSUE THREAD

**Issue by koluch** [Microsoft/vscode#33205]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

---

Steps to Reproduce:

1. Turn off "javascript.validate.enable" setting
1. Make a file with a following content:

```
/**
 * @flow
 */
import React, { Component } from 'react';

class Test extends Component {

  testMethod = (type: string) => {
    const a = ((type: any): string)
    console.log(a)
  }

  render() {
    return (
      <div>
        <button type={'submit'}/>
        <div>Test</div>
      </div>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/1646176/29747794-19669a18-8b0e-11e7-80bb-435263e6e2c3.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
We don't ship with built-in support for flow syntax. Try installing an extension that adds flow grammar support: https://marketplace.visualstudio.com/search?term=flow&target=VSCode&category=All%20categories&sortBy=Relevance

Closing as extension candidate
