### ISSUE TITLE
Cannot open folder

### ISSUE THREAD

**Issue by nosizi** [Microsoft/vscode#33206]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
jquerysnippets|don|0.0.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
easy-less|mrc|1.4.5
vetur|oct|0.9.5
vscode-icons|rob|7.12.0
markdown-preview-enhanced|shd|0.2.7
open-in-browser|tec|1.1.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@nosizi How can this bug be reproduced? Could you provide some more information and/or some screenshots?

**Comment by nosizi** [comment]
[GIF](http://omqzcac5s.bkt.clouddn.com/test-folder.gif)

**Comment by nosizi** [comment]
[Gif image](http://omqzcac5s.bkt.clouddn.com/test-folder.gif)

**Comment by bpasero** [comment]
@nosizi is that folder on OneDrive?

**Comment by nosizi** [comment]
@bpasero no, on E Disk

**Comment by nosizi** [comment]
@bpasero [Console Img](http://omqzcac5s.bkt.clouddn.com/console-log.png)

**Comment by bpasero** [comment]
@nosizi hm nothing in particular. Something in the terminal maybe where you started with?
