### ISSUE TITLE
deb.package shows License: Unknown, updates: Unknown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3321]
#3239 

When opening our .deb package in the software center I see that license and updates show unknown. This does not look user friendly, could we improve it somehow?

![screen shot 2016-02-23 at 14 52 10](https://cloud.githubusercontent.com/assets/1926584/13253597/13d7ba42-da3d-11e5-90ad-9107a9d32b8e.png)

**Comment by Tyriar** [comment]
Looks like license might be pulled from the `debian/copyright` file:

- https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
- https://www.debian.org/doc/manuals/maint-guide/dreq.en.html

Updates may be pulled from `debian/changelog`, not sure we would want to maintain this file though.

**Comment by Tyriar** [comment]
Ubuntu Software Center has an issue where it displays only those in official repos, not based on the `DEBIAN/copyright` file:

> What is currently in Karmic Beta is not very good nor useful.
> 
> it just says
> 
> "License: Open Source"
> 
>  For everything in main and universe
> 
> and "unknown" for things in multiverse
> "proprietary" for things in restricted
> 
> instead of "Open Source" software-center needs to use the copyright information from the packages
> 
> see http://dep.debian.net/deps/dep5/

https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183/comments/5

This issue can be closed when the `DEBIAN/copyright` file serves the correct license for both official and OSS builds.

**Comment by Tyriar** [comment]
Actually considering that this license does not seem to be exposed anywhere, just available by extracting the deb, I won't go ahead with this.
