### ISSUE TITLE
code --workspace option

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33211]
It's currently possible to execute something like `code ~/path1 ~/path2` and two different windows will be opened.

With the advent of multi-root I find it appropriate to have a `--workspace` option that will cause those paths to be opened in a single window.

This option would also be useful for extensions:
- [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus): it might be interesting to have the option to open all the projects under a group in a new workspace, without messing around with `Add Folder to Workspace...` commands and `.code-workspace` files.

**Comment by Tyriar** [comment]
We discussed this earlier. Not sure if there's an issue tracking this yet.

**Comment by bpasero** [comment]
Yeah: https://github.com/Microsoft/vscode/issues/30599
