### ISSUE TITLE
August endgame

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33215]
## Endgame Schedule
- *August 28*, Code freeze for the endgame
- *September 1*, Endgame done

#### Monday, August 28
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items are created (with "complexity" but not necessarily with full description) by 11pm ZRH time (2pm PT)
- [x] All test items contain comprehensive test descriptions by 10pm PT
- Testers who cannot participate in testing check-off from list below:
  - [x] @aeschli
  - [x] @alexandrudima
  - [ ] @auchenberg
  - [x] @bpasero
  - [x] @chrisdias
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @mjbvz
  - [x] @ramya-rao-a
  - [x] @rebornix
  - [x] @roblourens
  - [x] @sandy081
  - [x] @seanmcbreen
  - [x] @tyriar
  - [x] @weinand

#### Tuesday, August 29
- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A"August+2017") assigned
- [x] [All closed feature-requests either have a verification-needed or on-testplan tag](https://github.com/Microsoft/vscode/issues?q=label%3Afeature-request+-label%3Aon-testplan+-label%3Averification-needed+-label%3Aduplicate+milestone%3A%22August+2017%22+is%3Aclosed)
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

#### Wednesday, August 30
- [x] Remind team members to assign issues that they intend to fix to the August milestone
- [x] Testing
- [x] [Fixing](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22August+2017%22+label%3Abug) (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22August+2017%22)

#### Thursday, August 31
- [x] [Fixing last issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22August+2017%22+label%3Abug)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22August+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
  - do not forget to update the `distro` attribute in the package.json with the commit ID of the distro repo.
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**
  - [new modules](https://github.com/Microsoft/vscode-internalbacklog/issues/86)

#### Friday, September 1
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node-debugadapter-node **@weinand**
  - [x] node-debug **@weinand**
  - [x] node-debug2 **@roblourens**
- [x] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) @dbaeumer
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @isidorn  
  - [x] OS X - @sandy081 
  - [x] Linux - @joaomoreno 
- [ ] All release notes updated - release notes are collected in a file named *`v1_16.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [ ] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-filewatcher-windows **@bpasero**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [ ] vscode-jshint **@kieferrm**
  - [x] vscode-recipes **@weinand**
  - [x] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [ ] Trigger new insider build and publish it manually **@owner**

##### Friday/Monday
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@redmond**

##### Monday - Wednesday
- [x] Polish release notes **@redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@owner**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [ ] Documentation updated
  - [ ] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [ ] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Thursday/Friday
- [x] Merge translations **@zurich**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request @chrmarti
- [ ] Sanity check of installable bits
  - [ ] Windows
    - [ ] signed installer **@owner**
    - [ ] zip **@owner**
  - [x] OS X - **@owner**
  - [ ] Linux
    - [ ] deb package 32-bit **@owner**
    - [ ] deb package 64-bit **@owner**
    - [ ] rpm package 64-bit **@owner**
    - [ ] rpm package 32-bit **@owner**
    - [ ] archives **@owner**
- [ ] Publish website **@gregvanl**
- [ ] Publish to stable **@owner**
- [ ] Publish deb and rpms to repositories manually @chrmarti
- [x] Add version with symbols to HockeyApp @Tyriar 
- [ ] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [ ] Enable scheduled `insider` builds **endgame master**
- [ ] Twitter announcement **@seanmcbreen**

**Comment by gulshan** [comment]
I think this statement is not correct anymore-
>All release notes updated - release notes are collected in a file named Month_Year.md in this repo directory.

**Comment by weinand** [comment]
@gulshan I've fixed the release notes name.
