### ISSUE TITLE
VSCode multimon breaches boundaries when maximized

### ISSUE THREAD

**Issue by azydevelopment** [Microsoft/vscode#33226]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3

---

Steps to Reproduce:

1. Set up multimon (attached screenshot of my display config)
  a. My display config is a 1080 monitor plus a Surface Laptop
2. Start VSCode
3. Maximize VSCode on the 1080p monitor
4. Notice it bleeds into the other monitor
  a. Note that in the zoom in of the screenshot that it bleeds both out to the other monitor and down into the taskbar.

Screenshots attached.

![screenshot](https://user-images.githubusercontent.com/29720335/29754977-edab7fba-8b44-11e7-86a3-362b4023cc22.png)
<img width="711" alt="zoom_in" src="https://user-images.githubusercontent.com/29720335/29754975-eda97dbe-8b44-11e7-8742-9304709be5d0.PNG">
<img width="496" alt="display_config" src="https://user-images.githubusercontent.com/29720335/29754976-eda9dcfa-8b44-11e7-8ea2-95a78681d851.PNG">

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
This is likely an Electron issue.

**Comment by bpasero** [comment]
Could be https://github.com/electron/electron/issues/9688

**Comment by bpasero** [comment]
@azydevelopment do you still see this?
