### ISSUE TITLE
Emmet - spaces in snippets

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33229]
- VSCode Version: 1.15.1
- OS Version: win7x64

If you would make mistake in writing your custom snippets and type space inside the snippet (property or value), like this:
```
  "html": {
    "snippets": {
      "test1": "test 111",    <----
      "test2": "test22222",
      "test3": "test33333333"
    }
  }
```

... it will not show this "crashed" snippet in the list, and if you will try to force it to expand - VS Code will notify you about the error:

![image](https://user-images.githubusercontent.com/24613274/29755818-6950a166-8ba6-11e7-86f0-8168d8e22c12.png)

well, I believe, that users deserve errors with more specific information (like `"Emmet -- Forbidden symbol ("space") in D:/files/snippets.json on line 83"`)... not just "something gone wrong in abbr."... that's ridiculous.

But more important in this case, that this "crashed" snippet also makes all other snippets with "test..." in it - disappear from the snippets list.

GIF:
![space in snippets](https://user-images.githubusercontent.com/24613274/29755950-08cd2344-8ba8-11e7-841e-976605036856.gif)

**Comment by ramya-rao-a** [comment]
Fixed. The Insiders that will be out in a few hrs will have the fix.

Thanks for reporting!
