### ISSUE TITLE
Limit resource size to ensure resource inline

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#33223]
- VSCode Version: Insider
- OS Version: macOS

Our editor compile pipeline will merge CSS and inline resources (images) and the size limit is 5kb. As we added two large files, Monaco Editor shipped with a new contrib folder with two images which are over size limit.

![image](https://user-images.githubusercontent.com/876920/29754184-0c3ad53a-8b35-11e7-915b-6a4377414b8a.png)

All other icons are merged into `editor.main.css`, let's optimize `String_16x.svg`.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Yeah, we get these icons from our central repo. I am not authoring them, no clue how to make them smaller

**Comment by jrieken** [comment]
So, apparently this is done on purpose because IE fails to load this SVG when inlines. @alexandrudima knows the background story on this

**Comment by alexandrudima** [comment]
We can increase the size from 3000 to something that contains this svg size

But. IE cannot render specifically this svg file when it is inlined. 

See https://github.com/Microsoft/vscode/blob/a9398d49adc44ab8771275bccd197a50f975b0a4/build/gulpfile.editor.js#L67

See https://github.com/Microsoft/monaco-editor/issues/336

**Comment by jrieken** [comment]
@chryw Can you help?

**Comment by alexandrudima** [comment]
... It is an insane IE11 bug ... triggered specifically by this svg ... only when the svg is inlined in the CSS ...

https://github.com/Microsoft/monaco-editor/issues/336#issuecomment-275326624
> Note that the black squares only seem to appear in IE 11 on Windows 10, but not in IE 11 on Windows 8.1 or Windows 7.

**Comment by chryw** [comment]
@jrieken could you point me to the svg file that's broken? I don't have the one used in VS Code. The first batch of VS Code icon were added by someone who left the company a while ago. 

Now I only have the latest "String" icon for VS IDE that doesn't have a box around "abc". If that's ok then here are the files -
[String_vscode.zip](https://github.com/Microsoft/vscode/files/1288815/String_vscode.zip)

**Comment by jrieken** [comment]
its this and the inverted one: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/media/String_16x.svg#L1

**Comment by jrieken** [comment]
Yeah, I'll go with the new icons and hope that they work for IE too.

**Comment by jrieken** [comment]
We have a new icons here.
