### ISSUE TITLE
None of the task snippets resolve to a working tasks.json setup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3322]
Related to #3159

If you run `Configure Task Runner` on a brand new workspace, select `tsc` and run the `Run Task` action in the command palette, you get informed that there are no tasks found:

![image](https://cloud.githubusercontent.com/assets/22350/13253611/23823170-da3d-11e5-8ebd-ec5ce554464e.png)

This is true for all snippets.

**Comment by seanmcbreen** [comment]
I also observed this - in my case before you can run the task the file needed to be saved to disk - in that case the tasks would be picked up.

**Comment by dbaeumer** [comment]
There are two issues here: the tasks is only picked up when the file is actually existing on disk. That is how our settings story work. The second is the HelloWorld.ts file which is confusing as well. In the new version I exchanged "HelloWorld.ts" with a snippet variable.

**Comment by dbaeumer** [comment]
@joaomoreno the snippets got obsolete. Please close as verified if the new template story works for you.
