### ISSUE TITLE
SCM: Allow setting default provider in settings

### ISSUE THREAD

**Issue by adduc** [Microsoft/vscode#33228]
It would be nice to configure the SCM provider (e.g. git, mercurial) to use by default when opening a previously unopened folder.

As it currently stands, VSCode 1.15 defaults to git for every folder opened, even if the folder contains a mercurial repository.

**Comment by joaomoreno** [comment]
The concept of an _active_ provider is gone this milestone. We are now supporting multiple providers at once.
