### ISSUE TITLE
JSDoc for a chain assignment functions and objects don't work

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#33221]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
vscode-wakatime|Wak|1.1.13
vscode-icontheme-nomo-dark|be5|1.3.2
markdown-preview-github-styles|bie|0.0.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.2.11
Go|luk|0.6.63
typescript-javascript-grammar|ms-|0.0.23
vetur|oct|0.9.5
vscode-spotify|shy|2.0.0
language-stylus|sys|1.7.3

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Write JSDoc to a chain assignment function or object;
2. JSDoc for a chain assignment functions and objects don't work.

Screenshot

<img width="569" alt="Screenshot of that issue" src="https://user-images.githubusercontent.com/9027363/29753149-78d510e6-8b41-11e7-828c-0184a1b6655b.png" />

The code i'm used

```js
/**
 * Filter an iterable using a filter function.
 * @param {Iterable.<T>} list
 * @param {function(T, number, T[]):boolean} filter
 * @template T
 * @returns {Array.<T>}
 */
const all = exports.all = (list, filter) => [...list].filter(filter)
```

**Comment by mjbvz** [comment]
Thanks. This looks like an issue with TypeScript which powers our JavaScript language support. I've opened https://github.com/Microsoft/TypeScript/issues/18085 to track this upstream

Closing as upstream
