### ISSUE TITLE
g++ build Task can't find files on WSL 

### ISSUE THREAD

**Issue by DanielFNG** [Microsoft/vscode#33232]
- VSCode Version: Code 1.15.1 
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.3

---
### Description 

Trying to set up simple g++ build Task using VS Code with WSL. I can use g++ to compile just fine in the terminal, but when I try to set this up using tasks it can't find the source files. I have posted to StackOverflow but no response.

For illustration here's the output when I try with a simple hello world C++ program. I've shown a simple build task as well as an ls to show that the file is there. Both of these tasks were run while my focus was on the source code file window.

> Executing task: g++ helloworld.cpp <
>g++: fatal error: no input files compilation terminated.
>Terminal will be reused by tasks, press any key to close it.

>Executing task: ls <
>helloworld.cpp
>Terminal will be reused by tasks, press any key to close it.

I have tried with the exact example task specified in [the documentation](https://code.visualstudio.com/docs/languages/cpp) (converted to text for upload - [ tasks.txt](https://github.com/Microsoft/vscode/files/1255076/tasks.txt)) and some variants of this but no success. When I close the terminal created by the task and try to just build from the command line it works.

```
testvscpp$ ls
helloworld.cpp
testvscpp$ g++ helloworld.cpp
testvscpp$ ls
a.out helloworld.cpp
```

---

Steps to Reproduce:

1. Use WSL bash shell as default (user settings). 
2. Create build task for g++.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@dbaeumer not sure if this is cpptools or built in

**Comment by dbaeumer** [comment]
This is a more general problem of executing things in the WSL since we need to accommodate to the WSL mnt points to make this work.

**Comment by danblink** [comment]
I'm having the same issue but found a strange work-around. If your g++ compile command is the first thing run in the task, it can't find the files, but if you run another command directly before g++ with a semicolon separator, it will work properly. An example of what I mean:
`"command": "g++ file.cpp"` does not work but `"command": ":; g++ file.cpp"` does.

**Comment by DanielFNG** [comment]
I can confirm that I'm getting the same behaviour as @danblink, i.e. adding the do nothing command makes the task work as expected.

**Comment by dbaeumer** [comment]
@danblink this is very strange and I don't have an explanation for this. I fixed a bug were parameters weren't passed correctly for the next release (1.16) but I have no idea why an "do nothing" command would help here.

**Comment by danblink** [comment]
@dbaeumer for clarification it isn't specifically the null command but simply running any different command first before g++. I found this fix by making my task command `ls; g++ file.cpp` to make sure the files were there and visible to the task runner and was surprised that it miraculously compiled. I get really strange behavior with it though, as I noticed if I do `echo "example"; g++ file.cpp` the echo doesn't always print for me.

**Comment by alexr00** [comment]
I can't reproduce the odd do-nothing command behavior or the wrong folder/not finding files behavior. I installed g++ and used the task [here](https://github.com/Microsoft/vscode/files/1255076/tasks.txt) for reference. Feel free to ping here if your still seeing it!
