### ISSUE TITLE
Request vietnamese

### ISSUE THREAD

**Issue by itz1508** [Microsoft/vscode#33230]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by danyeh** [comment]
@itz1508 , we already have an item tracking Vietnamese enabling. First step is to enable in translation tool - Transifex. We already got 3 votes which met the criteria. We are reviewing and will enable the language in Transifex. If you are interested in contributing, please vote there so I can invite you when enable the language. 
https://github.com/Microsoft/vscode/issues/27163
