### ISSUE TITLE
Some punctuation causes incorrect wrapping when followed by quote.

### ISSUE THREAD

**Issue by andiPossess** [microsoft/vscode#33236]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. Create or open a file of any type compatible with VS Code that uses text, preferably .md or .txt but other file types work.
2. Insert text mixed with white space to ensure proper wrapping behavior.
3. At the end of the line, for the last character before wrapping would occur, insert a comma (`,`), a question mark (`?`), or an ampersand (`&`).
4. Follow that character with one of the above listed characters or with a double quotation mark (`"`) or single quotation mark (`'`) or a space (` `) with no other characters between.

Expected result: The entire chunk of punctuation wraps as though it were a single word.
Actual Result: The second punctuation mark wraps as though the previous mark was whitespace.

![wrapping](https://user-images.githubusercontent.com/31398891/29760298-480a0a4e-8b77-11e7-8fc9-0d39c3860c03.png)

This is particularly annoying when writing dialogue using markdown, as it causes the quotation mark to wrap and look odd.

**Comment by alexdevero** [comment]
This issue might be related. Punctuation sometimes causes wrong syntax rendering, or coloring. For example, dot (`.`) can cause that text in italic is rendered as plain text.

With dot (`.`):
![md-bad](https://user-images.githubusercontent.com/4237724/38812147-c0215274-418b-11e8-9043-e94c6827d0cc.JPG)

Without dot (`.`):
![md-good](https://user-images.githubusercontent.com/4237724/38812138-b8666b0a-418b-11e8-95ed-0d42ef44c8ab.JPG)

**Comment by alexandrudima** [comment]
@alexdevero the problem you are describing is not related to wrapping. It might be a problem with the tokenizer for markdown. i.e. I can reproduce when word wrapping is off:
![image](https://user-images.githubusercontent.com/5047891/38812548-ddaa2cca-418c-11e8-8c9a-f73274c6fac7.png)

Please create a separate issue

**Comment by alexdima** [comment]
Here is a copy-paste friendly version of the text:
```plaintext
"What in the world is going on? This is great,"

-------------------------------------------- ,"

-------------------------------------------- ."

-------------------------------------------- +"

-------------------------------------------- &"

-------------------------------------------- !"

-------------------------------------------- ?"

-------------------------------------------- /"

-------------------------------------------- -"
```

And settings:
```json
"[plaintext]": {
    "editor.fontLigatures": false,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 46,
    "editor.rulers": [46]
}
```

And the current result:
![image](https://user-images.githubusercontent.com/5047891/72142320-b6024580-3394-11ea-8bee-9071a20115b6.png)

**Comment by alexdima** [comment]
This has been fixed in the meantime:

![image](https://user-images.githubusercontent.com/5047891/99267377-2afba280-2824-11eb-8bfd-b3e23694a50c.png)
