### ISSUE TITLE
Cannot Open my old workspace

### ISSUE THREAD

**Issue by naviat** [Microsoft/vscode#33239]
- VSCode Version: Code - Insiders 1.16.0-insider (d30825f323a7f77e17d25b212fef6440e73fdc14, 2017-08-28T05:23:37.920Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-npm-script|eg2|0.2.0
beautify|Hoo|1.1.1
search-node-modules|jas|1.1.1
vscode-circleci|jva|0.1.2
lambda-snippets|log|0.2.0
Go|luk|0.6.63
MagicPython|mag|1.0.12
terraform|mau|0.0.16
terraform-snippets|min|1.9.1
csharp|ms-|1.12.1
vscode-docker|Pet|0.0.16
cf-templates|pra|0.0.4
vscode-icons|rob|7.12.0
jenkinsfile-support|sec|0.1.0
vscode-react-native|vsm|0.4.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. After update new version, reopen VS Code.
2. My old workspace cannot open : error A system error occurred (ENOENT: no such file or directory, stat '<my workspace path>'

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@naviat can you share the workspace file with me?

**Comment by naviat** [comment]
@bpasero thanks for your reply, this is my workspace file.
[WORKSPACE.zip](https://github.com/Microsoft/vscode/files/1255391/WORKSPACE.zip)

**Comment by pocesar** [comment]
for me, the editor is trying to access the wrong path. my sources are in G:\www and it's trying to access F:\www (insiders is installed in F:\ FWIW)

**Comment by bpasero** [comment]
Yeah I notice that once you remove or add a workspace, the drive letter is removed. I am looking into a fix...

**Comment by kzhui125** [comment]
![1](https://user-images.githubusercontent.com/11925432/29767821-78275322-8c16-11e7-8ef3-6fb42b5a0d9d.jpg)

**Comment by bpasero** [comment]
I will rebuild todays Windows insider for this fix to land.

**Comment by bpasero** [comment]
A new insider build is out, please everyone can you try it out and see if it works? You might have to manually fix your workspace file to add the drive letter back.

**Comment by naviat** [comment]
You are awesome @bpasero  👍
