### ISSUE TITLE
Moving tabs is cumbersome and don't snap left or right very well.

### ISSUE THREAD

**Issue by RockChalkBogota** [Microsoft/vscode#33231]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.7.0
cpptools|ms-|0.12.3
vim|vsc|0.9.0
vscode-wakatime|Wak|1.1.13

---

Steps to Reproduce:

1.  Try moving a tab to the right or to the left of another tab, especially if the tab is at the beginning and it will snap randomly. 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@RockChalkBogota the dropped tab should just always replace the tab you drop it to, can you share  a screen case of what you mean and see?
