### ISSUE TITLE
Closing files rapidly, multiple save confirms for one file when saving

### ISSUE THREAD

**Issue by flamerohr** [Microsoft/vscode#33233]
- VSCode Version: 1.15.1
- OS Version: Mac 10.11.6

Steps to Reproduce:
1. Make any change to a file
2. Press Cmd+W multiple times in quick succession (without confirming the dialog which shows up)
3. Click save in the dialog
4. Click save in the dialog
5. Click save in the dialog

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
