### ISSUE TITLE
Test vscode.debug.DebugConfigurationProvider

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33248]
Test for #32086:

Complexity: 3

- [x] Windows - **@roblourens**
- [x] OS X - **@jrieken**
- [x] Linux - **@isidorn**

In this milestone we've created a "real" API replacement for the 'startSession' and 'initialConfigurations' commands that we are currently using.
This API is proposed and can be found [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L212-L251).
To use the proposed API copy the vscode.proposed.d.ts it in your extension folder.

Verify that this API works as documented:
- use the "hello world" extension
- register a `DebugConfigurationProvider` for a specific debug type.
- implement `provideDebugConfigurations` by returning a real (or fake) launch configuration. Verify that this is added to the initial launch.json that is created if a project folder has none. Make sure that the correct workspaceFolder is passed to `provideDebugConfigurations` in the 0,1,n-folder workspace configurations. 
- implement `resolveDebugConfiguration` by massaging the passed launch config and verify that it is passed to the correct debug adapter. Make sure that you can even change the `type` of the config so that another debug adapter is started. Make sure that the correct workspaceFolder is passed to `resolveDebugConfiguration` in the 0,1,n-folder workspace configurations.

**Comment by roblourens** [comment]
How do I configure launch.json for other folders in a multiroot window? It only does it for the first one.

**Comment by weinand** [comment]
You have to create separate launch.json for the different folders.
The launch config drop down has actions to create entries in the different launch.jsons.
