### ISSUE TITLE
QuickOpen (Ctrl+P) search matching logic needs to be improved

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#33247]
- VSCode Version: 1.16-insider
- OS Version: Windows 10

If I have a file with path: `ui/src/ui/Icons/index.js`
and there are other files, such as: `ui/src/utils/constants.js`, etc...

![image](https://user-images.githubusercontent.com/760112/29767496-3be8a502-8c00-11e7-8af7-1b6c9affa80c.png)
after scrolling about 49 or so entries, I get the match I **need**:
![image](https://user-images.githubusercontent.com/760112/29767534-65bafa06-8c00-11e7-9601-29e65226705a.png)

Then, searching for `ui/Icons` puts the more relevant `ui/src/ui/Icons` path somewhere way down the list, not what I'd expect. I'd expect a matches with longer *runs* to be higher rated, no? It seems like this was (partially) fixed somewhere in previous builds because I always type these kind of path and stopped getting miffed with the results - they were not *perfect*, but they were passable, But lately I'm finding myself getting miffed again, so I think this bug is a regression?

Maybe possibly linked: #20546

Reproduces without extensions: Yes

**Comment by kumarharsh** [comment]
Another demo which paints a more stark picture for the need of a better ranking:

![image](https://user-images.githubusercontent.com/760112/30054799-ea48a336-924a-11e7-97c3-bf97a440dc3f.png)

The `ui/input/index.js` **should** be at the top - it has matches ALL of the search string, and should be the highest ranked. No idea why paths which match only bits and pieces of the search string show up at the top.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34210

**Comment by kumarharsh** [comment]
#27317
