### ISSUE TITLE
trying to log in to microsoft crashes

### ISSUE THREAD

**Issue by arielgabizon** [Microsoft/vscode#33250]
![image](https://user-images.githubusercontent.com/5689834/29768091-359f0b02-8be5-11e7-9729-7636bdabf1e2.png)
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-92-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
python|don|0.7.0
references-plusplus|jri|0.0.5
cpptools|ms-|0.12.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
What are you trying to log in to?

**Comment by arielgabizon** [comment]
Wrote my email here:
![image](https://user-images.githubusercontent.com/5689834/29779362-a88519a4-8c12-11e7-8f24-be6b7b4b9c98.png)
Got this:
![image](https://user-images.githubusercontent.com/5689834/29779402-bb673886-8c12-11e7-9b38-e8eb732bd563.png)
Pressed remain signed in and got here:
![image](https://user-images.githubusercontent.com/5689834/29779435-d59ecc8c-8c12-11e7-8718-43a0576b8e40.png)
Pressed next got here:
![image](https://user-images.githubusercontent.com/5689834/29779478-eff7857e-8c12-11e7-9a45-1898d5035310.png)
Pressed next again got here:
![image](https://user-images.githubusercontent.com/5689834/29779492-ff375a64-8c12-11e7-9fbd-95cd41eb5e9b.png)


pressed next once more, and got to the picture posted above

**Comment by chrmarti** [comment]
@arielgabizon How did you start this in VSCode?

**Comment by arielgabizon** [comment]
I tried to rate an extension inside code

**Comment by chrmarti** [comment]
Must be an issue with the web login we have no control over. Could you retry?

**Comment by arielgabizon** [comment]
tried a few times already

**Comment by chrmarti** [comment]
This seems to be related to how Skype handles its accounts. Could you try logging in on skype.com and see if that works?

**Comment by arielgabizon** [comment]
I have no problem logging in skype.co

**Comment by chrmarti** [comment]
Maybe an issue with cookies. Try using an incognito/anonymous browser window.
