### ISSUE TITLE
Introduce a mechanism that can be used to activate debug extensions just in time 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33258]
With the new debug API we need to register `DebugConfigurationProvider` early enough so that VS Code has them available when it needs them.

Since `DebugConfigurationProvider` are typically registered in the `activate` function of an extension, we have to find a way to activate the corresponding extensions before debugging starts.

I've tried to use these actions to activate the extension that registers a `DebugConfigurationProvider`:
```json
    "onCommand:workbench.action.debug.selectandstart",
    "onCommand:workbench.action.debug.configure",
    "onCommand:workbench.action.debug.start",
```
but most of the time the registration in the extension does not happen in time for VS Code  to pick it up. So I had to resort to `"*"` with the side effect that the extension now starts on startup of VS Code.

So we need a more robust mechanism that allows to activate extensions for registering `DebugConfigurationProvider` just in time before debugging starts.

@jrieken can provide the details.

**Comment by jrieken** [comment]
Yeah, we don't [*always*](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commandService.ts#L36) for the `onCommand:xyz` execution events, e.g. not when the extension host is still starting. You can either manually send out that activation events, like tasks [does](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/browser/taskQuickOpen.ts#L43), or (recommended) invent a new event, ala `onDebug:<type>` or `onDebug:*` etc

**Comment by isidorn** [comment]
I have introduced a `onDebug` activation event which should get triggered when a user is setting up his launch.json.
This activation event may be currently sent more than needed but I plan to clean this up once we remove all the depreacted items we plan for october (since then my code will be cleaner and this activation event will be more precies).

I have tried the event and it works fine for my extension

**Comment by weinand** [comment]
The "onDebug" activation event needs to be fired for everything debug related, not just when a user is setting up his launch.json.

E.g. in the no-folder case when the user has an arbitrary file open in the editor and presses F5. In this case there is no setting up launch.json involved.

The "onDebug" activation event should be as precise as possible even if you could not remove the deprecated code. The problem is that we can only remove the deprecated code if debug extension authors have migrated their extension to the DebugConfigurationProvider, but that needs an "onDebug" activation event that works already today and covers all cases.

**Comment by isidorn** [comment]
@weinand agree. I have cleaned this up via b601113ef6
Notice that I had to add a comment about this event in the schema and I went with the following
`An activation event emitted whenever a user is about to start debugging or about to setup debug configurations.`

**Comment by weinand** [comment]
@isidorn the event description is perfect.
