### ISSUE TITLE
Global search is very slow, indefinite loading

### ISSUE THREAD

**Issue by Houfeng** [Microsoft/vscode#33254]
- VSCode Version:  1.15.1 (1.15.1)
- OS Version: 10.12.6

**Global search is very slow, indefinite loading**

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you give more details? Does the search run forever and never return results? Does it ever work? Can you try other folders?

**Comment by snhasani** [comment]
@roblourens I had this experience too. In latest version when you search a keyword globally in entire open project, CPU usage overload and it cause editor be freezing and searching never stopped; until killing the search action.

**Comment by Houfeng** [comment]
@roblourens 
VSCode Version: 1.15.1 (1.15.1)
OS Version: OS X 10.12.6

![image](https://user-images.githubusercontent.com/1432335/29868974-9494e1de-8db3-11e7-9712-20026fb4529d.png)

In any folder, search for the first time, but write some code, search again, there will be problems

**Comment by roblourens** [comment]
Can you share the project/folder that you're searching in? Is it possible that there are matches in very long lines, or something?
