### ISSUE TITLE
cut and paste issue

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#33252]
- VSCode Version: Code - Insiders 1.16.0-insider (d30825f323a7f77e17d25b212fef6440e73fdc14, 2017-08-28T05:23:37.920Z)
- OS Version: Windows_NT x64 10.0.15063

![cut-paste](https://user-images.githubusercontent.com/11925432/29768505-18ef172a-8c19-11e7-849d-e683c7ead176.gif)

**Comment by alexandrudima** [comment]
This is as designed. It is a feature that can be disabled via `"editor.emptySelectionClipboard": false`
