### ISSUE TITLE
Code formating is not working properly 

### ISSUE THREAD

**Issue by shijithkm** [Microsoft/vscode#33257]
Format Document is not working properly , I have tried with Alt+Shift+F

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.10.0
angular-material-snippets|4tr|0.3.1
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
angular1-code-snippets|ale|0.0.3
ccd-typescript|cod|0.1.2
vscode-material2-snippets|dee|2.0.0
tslint|eg2|0.17.0
file-icons|fil|1.0.5
beautify|Hoo|1.1.1
Angular2|joh|2.4.3
contextualduplicate|laf|0.2.0
duplicatetext|riv|0.0.3
vscode-format|rya|0.0.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@shijithkm What are you formatting? JavaScript? TypeScript? Something else?

Can you reproduce the problem if you disable your [vscode-format extension](https://marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format)?

**Comment by sambaneko** [comment]
I am also experiencing this issue with 1.15.1 while trying to format PHP (Javascript works properly for me).  I do not currently have any extensions installed.

**Comment by shijithkm** [comment]
I was trying to format HTML only , but its not happening.

**Comment by mjbvz** [comment]
@sambaneko I don't think we ship with a built-in php formatter. Please try installing an extension to get this support

@shijithkm This sounds like it may be an issue with one of your extensions. If you start code with `--disable-extensions`, do you still run into this issue?

**Comment by sambaneko** [comment]
@mjbvz It was previously working to fix inconsistent indentation in PHP, at least.

**Comment by mjbvz** [comment]
@sambaneko Please open a new issue if you feel there has been a regression in behavior
