### ISSUE TITLE
Test: Multiple SCM repository support

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33267]
Complexity: 4

- [x] tester1 - @egamma
- [x] tester2 - @isidorn 
- [x] tester3 - @mjbvz 

This milestone we started supporting multiple SCM repositories.

- Make sure the legacy story of having a single repository works as before. Please test the git extension as well as one of the current SCM providers out there (Hg, TFS, Perforce).
- If you open a workspace with multiple folders, each of them being a git repository, they should all appear in the SCM viewlet as separate repositories. Make sure actions, gestures, global commands work as expected. Give it a proper smoke test.
- If you remove a folder from a workspace, its respective repository should also be removed iff there are no open files from that same folder.
- If you open a no-workspace, no-folder window, no repositories should appear (#33288). If you open a single file from a git repository, it should appear in the SCM viewlet.
- Make sure git repositories can coexist with other SCM provider repositories in the same window.

**Comment by weinand** [comment]
@mjbvz since I've accidentally removed Joao's list of platforms to test, I wonder what platform you did test?

**Comment by mjbvz** [comment]
I tested on mac
