### ISSUE TITLE
Duplicated 'Telemetry configuration' section

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3326]
![image](https://cloud.githubusercontent.com/assets/6461412/13253842/82ed2eac-da3e-11e5-8082-0f3d9003781e.png)

Should the sections have different titles, or would you prefer that they are merged? If you can't define them at a single place we can also add code that does the merging. (assign to me then)

**Comment by aeschli** [comment]
We were wondering if this should really be 2 settings, or just one.

@chrisdias Chris, with Sofian being out, please make a call if this needs a fix for February.

**Comment by chrisdias** [comment]
I believe there are two unique settings - enableTelemetry and enableCrashReporter, they are distinct and have different end points.  Having them together in the same section of the settings file would be ideal, but not a requirement for Feb, assuming it can be fixed at a later time.

**Comment by SofianHn** [comment]
@aeschli I thought the default behavior was to merge, I would prefer this. If you plan to do that for GA then please take over, otherwise I can fix this by introducing a different section.

**Comment by SofianHn** [comment]
@aeschli I still think the best behavior here is to merge. I will assign this to you, please let me know if you disagree.

**Comment by aeschli** [comment]
I fixed this for the June release
