### ISSUE TITLE
How to stop OUTPUT panel from popping up every time I open a new project?

### ISSUE THREAD

**Issue by corysimmons** [Microsoft/vscode#33262]
![image](https://user-images.githubusercontent.com/224636/29777989-e63ec632-8bdb-11e7-9c4e-a9796a9ea33f.png)

Super annoying...

**Comment by Tyriar** [comment]
It looks like it's the eslint extension doing this. Maybe there's an option to control it?

**Comment by corysimmons** [comment]
It pops up for all kinds of weird reasons. Is there an option to just permanently disable it auto-popping up?

I'd still like manual access to it, I just hate that it auto-pops up.

**Comment by dbaeumer** [comment]
I can only speak for ESLint:

It only opens up once per new workspace / project you open to inform that ESLint will not run. Before we never poped it up or poped it up on every workspace open which was even more unhappy (no awareness  versus to much awareness).

You can disable eslint by default `"eslint.enable": false` in the user settings. Then you need to enable eslint in the workspace you want to.

No further action planned to ESLint. If you see it with other Output channel things might be different.

Please ping if you are asking for a general setting to never bring the Output Panel to front independent of the channel.

**Comment by corysimmons** [comment]
@dbaeumer Yeah any solution to keep that from popping up. I think you guys are right, maybe it is just ESLint, but regardless, it's frustrating to have to close it on every ESLint'd project I work on (almost every project I work on).

**Comment by sandy081** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/105270
