### ISSUE TITLE
Test error to extension mapping

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33266]
Test for: #32766
Complexity: 1

- [x] macOS - @weinand

Write an extension that throws uncaught errors, e.g from inside an event listener etc, and check that the error is printed on the dev-tool console *including* the extension id throwing. Be creative and throw error from other places

**Comment by weinand** [comment]
Don't try this in commands or activation code since there errors are always "caught".
After using a `setTimeout` I got this feature to show up:

![2017-08-29_17-16-20](https://user-images.githubusercontent.com/1898161/29828890-46127376-8cde-11e7-84c4-2b97d197275e.png)
