### ISSUE TITLE
Test: Windows terminal session renaming via native module

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33276]
#31818

- [x] Windows @bpasero
- [x] Windows @roblourens

Complexity 4

*This is mostly a copy of https://github.com/Microsoft/vscode/issues/31776 from last iteration as the mechanism for doing it completely changed*

**Use [ProcessExplorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to track process trees.**

- Verify that the title changes as the process changes and that the title makes sense. eg: `cmd -> cmd, powershell -> powershell, npm -> node, git log -> git, etc`.
- Verify that the title only changes to the first child process (if one exists) of the shell unless the child is one of `[bash, cmd, powershell]` where we'd check that child's children etc. eg: `Initial shell = cmd`. Git log will spawn a child process called less `cmd -> git -> less`. The title will show git and not less since git is the first child of cmd. If the tree is  `cmd -> powershell -> bash -> cmd -> powershell` then the title would be powershell since all those processes are shells.
- Verify that the terminal title is not overridden after the user or an API sets it.
- It is known that creating an external process (eg: `start notepad`) will have the title stuck as notepad until that process is closed.

**Comment by Tyriar** [comment]
I realized not too long ago that this doesn't work when packaged. I wasn't able to get a fix in before code freeze so I'll fix this tomorrow. Don't attempt to test until https://github.com/Microsoft/vscode/issues/33308 is resolved 😃

**Comment by bpasero** [comment]
I once got into a state where the title would no longer change to "powershell" when I started it but I cannot reproduce anymore.
