### ISSUE TITLE
Preserve format of paths in workspace file when writing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33270]
There is a couple of cases where today we change the paths in a way that might not be desired:
* we convert path separators to the OS path
* we convert relative/absolute paths automatically

We should try to preserve as much of the workspace file format as possible. For example, when a folder is added or removed, we should try to only write the change to the folder in question and not all.

**Comment by pr-yemibedu** [comment]
Hello,
With each folder being an object, it is possible to have a default case and an overriding case to put the choice in the users hand. If there is a default "relative" style and the user can mark a particular path to preserve its absolute representation, then that could be a helpful alternative. Maybe with a setting value of "pinned".
That would allow the best of both and possibly feel more natural. I am bias towards simplicity and conventions but highly accept the ability to choose when it is applicable. Thank you. Good day.

**Comment by bpasero** [comment]
Handled for "Save Workspace As" via https://github.com/Microsoft/vscode/commit/7bbf770f0468cf4f5e1065aeb41d5effe4340a04
