### ISSUE TITLE
Test: New icons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33272]
Complexity: 2

- [ ] macOS @chrisdias 
- [x] Windows @seanmcbreen 
- [x] linux @joaomoreno 

We have new icons for our product. Make sure the icon show up properly and are looking good in these areas (depending on OS):
* taskbar
* shortcuts
* file associations
* installer (Windows)
* watermark (when you close last editor)

**Comment by Stanzilla** [comment]
Windows 8.1 taskbar visibility is not that great:

https://user-images.githubusercontent.com/75278/29780665-de4f6720-8c16-11e7-8b67-c0b362d4ae18.png

**Comment by bpasero** [comment]
That is reported as https://github.com/Microsoft/vscode/issues/33337 already.

**Comment by bpasero** [comment]
@chrisdias todays insider includes the icon changes, I will merge this into https://github.com/Microsoft/vscode/issues/35304
