### ISSUE TITLE
Doesn't open Onedrive folders under W10 Preview Build 16273

### ISSUE THREAD

**Issue by lokijota** [Microsoft/vscode#33271]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.16273
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
armsnippet|art|0.7.0
arm|dan|0.1.2
python|don|0.7.0
xml|Dot|1.9.2
json-tools|eri|1.0.2
MagicPython|mag|1.0.12
prettify-json|moh|0.0.3
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
azurerm-vscode-tools|msa|0.3.6
java|red|0.8.0
python|tht|0.2.3

---

Steps to Reproduce:

1. Open VS Code
2. Navigate to a folder (in OneDrive) and open it
3. You get "Path does not exist" for all folders

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
#27285
