### ISSUE TITLE
Working files list does not re-order if file is reopened

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3327]
Related to #2791 

* Open 10 files so the working files list is full
* Open the first file again, notice that it is not sorted to the top of the working files list
* This produces inconsistencies between quick open (showing working files) and working files list

![screen shot 2016-02-23 at 15 13 39](https://cloud.githubusercontent.com/assets/1926584/13254183/902b808a-da40-11e5-9b1c-978a9f7dc42a.png)

**Comment by bpasero** [comment]
Works fine using the new working files picker (~).
