### ISSUE TITLE
Keep Opening Curly Brace on Same line as definition C++

### ISSUE THREAD

**Issue by nealhnguyen** [Microsoft/vscode#33279]
- VSCode Version: 1.15.1
- OS Version: Windows 7 x64

Steps to Reproduce:
1. Format Code For C++

Is there any support such that when I "format" my C++ code, the opening curly brace stays on the same line as the definition instead of being placed on a new line?

**Comment by rebornix** [comment]
The formatter is provided by the C++ extension you are using. Please file feature request against them and maybe they already support that.
