### ISSUE TITLE
Open Folder does not work.

### ISSUE THREAD

**Issue by snarlynarwhal** [Microsoft/vscode#33289]
**VSCode Version:** 1.15.1
**OS Version:** Windows 10 64-bit
**Steps to Reproduce:** 
* From main menu, select `File -> Open Folder` and select a folder
* Or... On Welcome page, select `Open Folder` and select a folder
* Or... Press `[Ctrl+K][Ctrl+O]` and select a folder

**Result:** Nothing happens. The Open Folder dialog closes, but that's all.
**Reproduces without extensions:** Yes

**Comment by rcjsuen** [comment]
See also #33148 and #33177.

**Comment by roblourens** [comment]
Thanks. So if you open the file explorer or use quick open (ctrl+p), it doesn't show the files in the opened folder?

**Comment by snarlynarwhal** [comment]
Correct, the explorer remains empty. If I use quick open, it opens that file and lists only that file in the Explorer: Open Editors window.

**Comment by roblourens** [comment]
So if you use quick open with ctrl+p, it lists the files in the folder that you tried to open, but they don't show up in the file explorer?

**Comment by snarlynarwhal** [comment]
Yup, that's the problem. Thanks for helping me get to the bottom of it. From a UX standpoint, it might make sense to open/show that view when you open a folder.. or always show it since you can just collapse it if you don't want to see it. Right now the UI stays the exact same so there's no indication that the folder got opened. As it appears I am not the only one who experienced this confusion, a UX update might help!

**Comment by sandy081** [comment]
@snarlynarwhal Yes, hiding the folders view is confusing even though users opted to hide it. Hence, we decided to not to provide an option to hide folders views - #32962

Also agreed that we need some UX love.
