### ISSUE TITLE
Test: JS/TS extract method refactoring

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33282]
Complexity: 3

- [x] any @seanmcbreen
- [x] any @dbaeumer  

# Overview
TS 2.5 brings an extract method refactoring option. This is a code action that users can trigger for the current expression of for selected code

# Testing
Focus testing on the integration and UI experience in VS Code (since the functionality of 'extract method' is out of our control anyway). 
Try browsing around some JS and TS code and triggering extract method. It should work for the current expression if you don't have a selection, and for the current selection if it can be extracted

**Note of filing issues**
I suspect most of the issues encountered with this test pass will be upstream TS issues. In those cases, please file the issue against TS directly to save time: https://github.com/Microsoft/TypeScript/issues/new
 
# Known issues
- Extract method does not trigger rename automatically. This is tracked for the next TS servicing release: https://github.com/Microsoft/TypeScript/issues/17852

**Comment by dbaeumer** [comment]
Filed:
https://github.com/Microsoft/TypeScript/issues/18137
