### ISSUE TITLE
can only paste once

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#33286]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-stylesheet-beautify|n23|0.0.1|;

---

Steps to Reproduce:

1.  right click on a file
2. click "copy"
3. click the folder
4.  click "paste"
5. click the folder
6. no "paste" available

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
