### ISSUE TITLE
Test: Inline Color Decorator & Color Picker performance fix

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#33295]
Test for https://github.com/Microsoft/vscode/issues/32295

Complexity: 2
- [x] anyOS  @alexandrudima 

* Color decorator rendering is moved to the core, we deprecated old extensions settings `[css/less/sass/json].colorDecorators.enable` and use language-aware `editor.colorDecorators`. Please verify that ppl can still use`[css/less/sass/json].colorDecorators.enable: false` to disable this feature and the new setting can do so as well.
* Color decorator will be changed only when users select one color in Color Picker, which happens when mouse up, instead of every mouse movement.
* Mouse down then move in Color Picker body should not make changes to the document. A simple extension can verify 
    ```
    vscode.workspace.onDidChangeTextDocument( () => {
        console.log('content change');
    });
    ```

**Comment by alexandrudima** [comment]
Nice! :heart:
