### ISSUE TITLE
Test: Extension Recommendation Improvements

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#33298]
Complexity 2

- [x] anyOs @joaomoreno  
- [x] anyOs @dbaeumer  

**Testing Telemetry for the Recommendation Pop up**
1. Pick any of the extensions from the `extensionImportantTips` https://github.com/Microsoft/vscode-distro/blob/master/quality/insider/product.json#L63
2. Uninstall it if you have it installed, reload VS Code
3. Open the file corresponding to the extension you picked, you will get the recommendation pop up
4. Choose `Show Recommendations` and test that an event by the name `extensionRecommendations:popup` is fired. The `customDimenstions.userReaction` should have the user reaction
5. Repeat steps 1 to 3. Close the pop up. Same event should get fired. The `customDimenstions.userReaction` should have the user reaction
6. Repeat steps 1 to 3. Escape the pop up. Same event should get fired. The `customDimenstions.userReaction` should have the user reaction

**Testing Telemetry for installing an extension**
1. Search for an extension and install it
2. Go to the recommended view and install one of the recommended extensions.
3. An event by the name `extensionGallery:install` should get logged for both. `customDimensions.source` should denote recommendations for the latter

**Testing Recommendations based on executables**
1. Install azure cli or any of the other exes in https://github.com/Microsoft/vscode-distro/blob/master/quality/insider/product.json#L111
2. Reload VS Code and go to the recommendations view
3. You should be able to see corresponding recommendations as per https://github.com/Microsoft/vscode-distro/blob/master/quality/insider/product.json#L111

**Testing expiry on file based recommendations**
1. In dev tools, find  `extensionsassistant/recommendations`in the local storage
2. Extensions there will be showing up in your recommendations view. The numbers associated with them are the the date time in the form of number of milliseconds elapsed since 1 January 1970 00:00:00 UTC.
3. Update the storage for any one of them such that the date time is more than 7 days old. (Subtract 1000 * 60 * 60 * 24 *8)
4. Reload VS Code. That particular extension should not show up anymore

**Comment by joaomoreno** [comment]
@ramya-rao-a What to do here?

**Comment by joaomoreno** [comment]
I don't see a `source` field but a `querySource`... I'm guessing this is it?

**Comment by ramya-rao-a** [comment]
@joaomoreno Yes `querySource`, my brain was stuck in last week when I had named it `source` :)
