### ISSUE TITLE
Wording of telemetry options

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3329]
![image](https://cloud.githubusercontent.com/assets/6461412/13254143/4af406a4-da40-11e5-86bc-5b3cfb0686de.png)

- VSCode should be 'VS Code' or 'Visual Studio Code'
- Should we also advice that extension should follow this setting? In that case we could name it 'Allow usage data and errors to be collected by Microsoft or by extension authors'

I know that we can't enforce that, but good behaving extensions should follow it.

**Comment by egamma** [comment]
>VSCode should be 'VS Code' or 'Visual Studio Code'

Since we also have an insiders flavor of the product I would not mention the product name in the description and just state:
`This option requires a restart to take effect`
