### ISSUE TITLE
Test: HTML tag auto close

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#33294]
Test for #2246

Complexity 2

- [x] any os @joaomoreno 
- [x] any os @rebornix 

In a HTML file

1. typing the `>` of `<sometag>` will add the closing tag `</sometag>`.
2. typing '/' of `</` will also close the tag.

- test that this works also for tags with attributes
- test that selfclosing tags (e.g.` img`, `br`) will not be closed
- test that the closing tag name matches the last unopened tag
- test that this can be turned off with setting `html.autoClosingTags`

**Comment by rebornix** [comment]
It's pretty good 👍
