### ISSUE TITLE
Test: Keeping the undo history when the file changes on disk

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33302]
Test plan item for #2908 (PR #29655)

Complexity: 3
- [x] any OS @aeschli 
- [x] any OS @isidorn 

---

Test that if you do some changes on a file and save the file, and then the file gets changed on disk via some other program, we (as before) automatically update to show the disk content, but (unlike before) the undo stack is maintained.

Some edge cases: 
 * a large (log-style) file with a program that logs to it every N seconds. Please check that we don't run OOM due to the undo stack.
 * a change on disk that is large (goes from a file to an empty file, goes from an empty file to a file with 20MB, etc.)

**Comment by aeschli** [comment]
Tested on Linux:
- open a file in VSCode, make several change, test undo and redo
- modify the file in an other editor, see that changes are applied to editor in VSCode, test that undo works, also redo
- test with git viewlet
