### ISSUE TITLE
Feature Request: Add Zen mode without going to full screen

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#33306]
Currently when you use zen mode in VS Code, the app goes into full screen. 

However I wish I can still use the same cut down minimised interface zen mode but without going to full screen.

Thank you.

**Comment by mjbvz** [comment]
Try setting `zenMode.fullScreen": false`

**Comment by nikitavoloboev** [comment]
Thank you, this works. Is it possible to make it so all VS Code projects I open will by default be opened in zen mode?

**Comment by mjbvz** [comment]
Try setting `zenMode.restore": true` should help when working on a single project. I think automatically opening projects in zen mode is tracked by #27273
