### ISSUE TITLE
macOS: Support virtual desktops

### ISSUE THREAD

**Issue by patrykcd** [microsoft/vscode#33303]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
csharp|ms-|1.12.1
vscode-icons|rob|7.12.0
code-spell-checker|str|1.3.8

---

Steps to Reproduce:

1. Maximize (to full screen) Unity3d and vs code on Mac OS.
2. Double click on the script in Unity3d.
3. vs code is moved to right virtual desktop, but focused on left.

explanation video: https://youtu.be/ZldW8fdPhbE

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@bpasero should this be closed. It returned back to inbox. I labeled it as a feature request.

**Comment by bpasero** [comment]
@dbaeumer I forgot to add the feature request label, so it can stay open.
