### ISSUE TITLE
Duplicate definition warnings upon opening markdown file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3330]
1. Open a markdown file
2. Notice duplicate definition warnings

Joh must have introduced this with the markdown preview, giving to Alex so he is aware and we can forward to Joh if this is not for endgame week.

![screen shot 2016-02-23 at 15 20 27](https://cloud.githubusercontent.com/assets/1926584/13254318/249a64a2-da41-11e5-9b9a-ccd791d0e840.png)

**Comment by egamma** [comment]
Jo added a html preview command which is separate from the markdown preview, so I don't think this was introduced by Jo.
