### ISSUE TITLE
Test: ExtensionHost debugging

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33305]
Test https://github.com/Microsoft/vscode-node-debug2/issues/4

Complexity: 2

- [x] Windows @weinand
- [x] Mac @bpasero 
- [x] Linux @joaomoreno 

EH debugging is now powered by node2 and the inspector protocol. Debug an extension, play around with it, and look for any oddities.

**Comment by joaomoreno** [comment]
Even space oddities?
