### ISSUE TITLE
Multi-root SCM constantly polls git

### ISSUE THREAD

**Issue by keegancsmith** [Microsoft/vscode#33309]
If vscode is in the foreground or background it constantly polls git for the status of each folder every few seconds. I can reproduce this on a workspace containing 2 folders, both of which have no untracked files, clean index, on master and nothing running to mutate anything in the repo. If I instead just open a folder (instead of a multi-root workspace) vscode does not poll git, even when in the foreground. Note: It does seem to poll git a few times in single folder mode, but stops after a bit of time.

I created this script on my `PATH` called `git` to monitor usage of git:

```sh
#!/bin/sh
echo "$PPID $PWD $@" >> /tmp/git.log
exec /usr/local/bin/git "$@"
```

I see entries like this regularly, the PPID is `code-insiders`:

```
95329 /Users/keegan/src/go status -z -u
95329 /Users/keegan/src/go symbolic-ref --short HEAD
95329 /Users/keegan/src/go rev-parse master
95329 /Users/keegan/src/go rev-parse --symbolic-full-name --abbrev-ref master@{u}
95329 /Users/keegan/src/go rev-list --left-right master...origin/master
95329 /Users/keegan/src/go for-each-ref --format %(refname) %(objectname)
95329 /Users/keegan/src/go remote --verbose
```

- VSCode Version: Code - Insiders 1.16.0-insider (4f32007a5e20f181c675fefa82ff6115c785bb23, 2017-08-28T13:47:37.580Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.0
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
python|don|0.7.0
tslint|eg2|0.17.0
Go|luk|0.6.63
MagicPython|mag|1.0.12
debugger-for-chrome|msj|3.2.0
vscode-multiclip|sle|0.1.2
sourcegraph|sou|1.0.9

---

Steps to Reproduce:

1. Open a workspace in the latest insiders build
2. Notice the "checking" badge appear regularly on SCM viewlet
3. Tab away
4. Monitor git usage via extra script, or via `sudo fs_usage -f filesys git` on MacOS.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Might have something to do with the file watcher.

**Comment by joaomoreno** [comment]
Each repository was getting file events from *all* repositories. So, a file change event in one would fire a refresh on another and so on and so forth.

**Comment by keegancsmith** [comment]
I mentioned this in the description, but I could reproduce this without mutating any files in any of the workspace folders.

**Comment by joaomoreno** [comment]
Yup, all you need is a `git status` to trigger the whole thing, which can happen occasionally.

**Comment by keegancsmith** [comment]
I really don't think anything was running. I was literally just monitoring `tail -f` on the git log. So not even my shell prompt could do it. It is possible something else could come along and do it (I'd be surprised). I can run `sudo fs_usage -f filesys` and check if there is anything other than code-insiders / git from code-insiders accessing the relevant folders.

Side-note: If you are concerned about fs watching false positives, https://facebook.github.io/watchman/ is a really great and battle tested solution for file watching.

**Comment by kzhui125** [comment]
@joaomoreno 
5 git repos in 6 folders.
No files were changed, but vscode constantly polls git, and the git badge keeps flashing.
I have to use one root now (stable vscode).

![1](https://user-images.githubusercontent.com/11925432/29851888-5d1de1f0-8d69-11e7-94f5-386f469f18ab.gif)
![2](https://user-images.githubusercontent.com/11925432/29851892-61102610-8d69-11e7-84f4-7968289cb488.gif)
![3](https://user-images.githubusercontent.com/11925432/29852055-6d075c26-8d6a-11e7-865b-2eb273560e9d.jpg)

**Comment by bpasero** [comment]
I am still seeing lots of Git activity in my multi root workspace. It looks like there is constant file events on the repositories:

![image](https://user-images.githubusercontent.com/900690/29927822-bd0ada42-8e67-11e7-943b-83d451a481bc.png)
