### ISSUE TITLE
Find in Files only searches in opened files in workspace

### ISSUE THREAD

**Issue by Trucoto** [Microsoft/vscode#33307]
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

1. Ctrl-Shift-F (Search in files). Type something I know it's in my source files.
2. VSCode does not find anything.
3. Open one source file
4. Repeat the search, it does find the term within the opened file.

Reproduces without extensions: Yes

This is happening on certain projects, on other it works fine. Settings are exactly the same on both working and non-working projects.

This is my settings.json:

```
{
    "files.associations": {
        "ostream": "cpp",
        "algorithm": "cpp",
        "deque": "cpp",
        "exception": "cpp",
        "functional": "cpp",
        "iosfwd": "cpp",
        "iterator": "cpp",
        "list": "cpp",
        "map": "cpp",
        "memory": "cpp",
        "new": "cpp",
        "numeric": "cpp",
        "queue": "cpp",
        "set": "cpp",
        "stack": "cpp",
        "stdexcept": "cpp",
        "utility": "cpp",
        "vector": "cpp",
        "xmemory": "cpp",
        "xstddef": "cpp",
        "xstring": "cpp",
        "xtree": "cpp",
        "xutility": "cpp",
        "array": "cpp",
        "atomic": "cpp",
        "*.tcc": "cpp",
        "cctype": "cpp",
        "chrono": "cpp",
        "clocale": "cpp",
        "cmath": "cpp",
        "cstdarg": "cpp",
        "cstddef": "cpp",
        "cstdint": "cpp",
        "cstdio": "cpp",
        "cstdlib": "cpp",
        "ctime": "cpp",
        "cwchar": "cpp",
        "cwctype": "cpp",
        "fstream": "cpp",
        "initializer_list": "cpp",
        "iostream": "cpp",
        "istream": "cpp",
        "limits": "cpp",
        "ratio": "cpp",
        "sstream": "cpp",
        "streambuf": "cpp",
        "system_error": "cpp",
        "thread": "cpp",
        "tuple": "cpp",
        "type_traits": "cpp",
        "typeinfo": "cpp",
        "xlocale": "cpp",
        "ios": "cpp",
        "string": "cpp",
        "xiosbase": "cpp",
        "xlocinfo": "cpp",
        "xlocnum": "cpp"
    },
    "files.autoGuessEncoding": false,
    "files.encoding": "cp437",
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.o": true,
        "**/*.d": true
	},
	"files.exclude": {
        "**/*.o": true,
        "**/*.d": true
	},
    "C_Cpp.intelliSenseEngine": "Default"
} 
```

Works on /home/leandro/Lore/ElfinThread/ElfinSales3/server; it does not work on /home/leandro/Desarrollo/hsl/working, so directory names are not likely the problem. Both are C++ projects.

**Comment by roblourens** [comment]
The issue is the encoding - cp437 isn't supported by our search tool, since it's not part of the whatwg standard. I have an issue to provide a better experience for this case: https://github.com/Microsoft/vscode/issues/29090#issuecomment-310134356

Do you think an error message or falling back on utf8 would be more helpful in this case? Unfortunately we won't be able to support search for that encoding.

**Comment by Trucoto** [comment]
Yes, of course. An error message would be fine, falling back to UTF8, better for me. I am not so interested on finding comments (where UTF8/cp437 could make the difference), but actual code, which could be found with either encoding.

**Comment by Trucoto** [comment]
Any workaround is possible?

**Comment by roblourens** [comment]
Workaround - it should work with `"search.useRipgrep": false`.

Why is your code in `cp437`? I've had a few of these issues and don't quite understand the scenario, and how common it is.

**Comment by Trucoto** [comment]
Basically, legacy code. Coming from DOS, crossplatform source files that compiles across different architectures. Today it would be a problem to convert all source code from certain projects to UTF8, because some of them interact textually with peripherals like POS printers or displays or card readers that use as a de facto encoding CP437. More recent codebases use UTF8, hence that's why some projects do find in files correctly.

**Comment by roblourens** [comment]
Thanks for the explanation. Will continue tracking in #29090.
