### ISSUE TITLE
Automatically enable KeyRepeat on MacOS

### ISSUE THREAD

**Issue by Widdershin** [Microsoft/vscode#33311]
I am crossposting this issue from https://github.com/VSCodeVim/Vim/issues/1983 at the request of @jpoon.

> I don't believe our extension will have the authority to change macos user defaults. Can you cross-post this issue to VSCode?

Following on from https://github.com/VSCodeVim/Vim/issues/1975.

The aim of this issue is to either enable key repeat by default on MacOS, or to more proactively notify MacOS users that they can set this option. This is an issue in the VSCode vim plugin as by default users cannot hold h/j/k/l to navigate.

As I said in https://github.com/VSCodeVim/Vim/issues/1975, even though this is well documented in the VSCode readme, not all users think to check the documentation, and instead assume this is a bug.

From the [README](https://github.com/VSCodeVim/Vim#mac-setup):

> If key repeating isn't working for you, execute this in your Terminal. 
>
> defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
> defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
>
> We also recommend going into System Preferences -> Keyboard and cranking up the Key Repeat and Delay Until Repeat settings to improve your speed.

There are a few questions here:

 * Does this impact all MacOS users?
 * Can we programatically set this option on MacOS?
 * Would there be any downside to doing so?
 * If not, can we more proactively notify impacted users that they can easily fix this issue.

If anyone can answer any of those questions, please comment in here.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19764

**Comment by Widdershin** [comment]
Hi, this issue wasn't that it didn't work after enabling the option, but instead that it should be enabled by default. After enabling this option the behavior worked fine for me, which implies that it isn't on by default, as is stated in #19764.

Can you please reopen this issue? Or have I misunderstood something?

**Comment by rebornix** [comment]
@Widdershin sorry I didn't put more info in above comment. They share the same root cause.

Sometimes setting ApplePressAndHoldEnabled off for VSCode doesn't work, I don't have any clue why is that. If that problem can be solved, I'd like to put into the Code's installation process and make it turned off by default, which is your feature request. Does it make sense?

**Comment by Widdershin** [comment]
That makes total sense, my confusion stemmed from thinking that we were turning something on rather than off, which is not actually the case.

Thanks for explaining 👍
