### ISSUE TITLE
"Output" and "Debug Console" don't render UTF-8 symbols

### ISSUE THREAD

**Issue by Svetomech** [Microsoft/vscode#33310]
- VSCode Version: 1.15.1 (x64)
- OS Version: Windows 10, 64-bit, ru-RU
- .NET Core Version: 2.0 (x64)

Steps to Reproduce:

1. Launch VSCode, open `dotnet new console` .NET Core project
2. F5
3. (see images below)

![image](https://user-images.githubusercontent.com/7114815/29795320-64d18aac-8c54-11e7-8f93-867ac8dc18b4.png)
![image](https://user-images.githubusercontent.com/7114815/29795361-9640c440-8c54-11e7-8fc3-ceae8aa09414.png)

Reproduces without extensions: Not applicable ([C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) required)

**Comment by Svetomech** [comment]
Is there any additional info I need to provide in order to resolve the issue? Are there any workarounds?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/571 and some other issues already open which you can find and upvote in your collection of issues
