### ISSUE TITLE
Git Credential Manager for Windows Popups

### ISSUE THREAD

**Issue by osnirmaster** [Microsoft/vscode#33313]
How can I get rid of this popup that shows every 15-45 seconds asking for my bitbucket credentials? Giving the credentials to this popup does not stop it from coming back.

![sem titulo](https://user-images.githubusercontent.com/15311415/29802214-515214ce-8c4a-11e7-96c5-98901032e604.png)

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-html-css|ecm|0.1.8
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-npm|fkn|3.3.0
code-runner|for|0.7.1
rest-client|hum|0.15.2
search-node-modules|jas|1.1.1
node-module-intellisense|lei|1.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-exec-node|mir|0.5.0
mssql|ms-|1.1.0
cpptools|ms-|0.12.3
debugger-for-chrome|msj|3.2.0
vscode-icons|rob|7.12.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.9.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by osnirmaster** [comment]
How can I get rid of this popup that shows every 15-45 seconds asking for my github credentials? Giving the credentials to this popup does not stop it from coming back.

**Comment by joaomoreno** [comment]
You can disable the auto fetching behaviour: `git.autofetch: false`

**Comment by eromoe** [comment]
I don't think it is a good behavious,  

1. first, you should tell user this popup is pop by vscode (I cost some time to find out this)
2. you should show the git remote -v at popup top, then user can know which account to login
3. Now, no error message for wrong Credential , even more, it would popup again and again after close, 
are you kidding me ??  Keep popup is a really bad and annoying behavious .

Please fix it!
