### ISSUE TITLE
Feature request: Show the title of the integrated terminal

### ISSUE THREAD

**Issue by engineforce** [Microsoft/vscode#33315]
At the moment the drop-down in the terminal window only shows the type of the terminal, which become confusing after having many of them:

![image](https://user-images.githubusercontent.com/3614365/29802621-dac4fdd8-8cb9-11e7-873c-c752b560c705.png)

Both cmd and powershell have ways to set their title, can you please display the titles in the drop-down?

E.g., cmd:

    title "new title"

E.g., powershell

    $host.ui.RawUI.WindowTitle = "Changed Title"

**Comment by Tyriar** [comment]
You can do this via the command palette

![image](https://user-images.githubusercontent.com/2193314/29837920-76f30378-8cae-11e7-8e1b-009b70144247.png)

For powershell ISE-like support you can check the powershell extension https://github.com/PowerShell/vscode-powershell
