### ISSUE TITLE
Debug: Call stack view should use more ellipsis

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33326]
Testing #33305

IMO the behaviour, under tight space constraints, should be:

- First, the line numbers go away
- Then, the file name starts compressing, with ellipsis
- Finally, the same happens to the actual stack frame label

![peek 2017-08-29 09-42](https://user-images.githubusercontent.com/22350/29809983-71583e70-8c9e-11e7-8753-afdcd34cc326.gif)

**Comment by isidorn** [comment]
@joaomoreno thanks a lot for help. I love this change

**Comment by sandy081** [comment]
@isidorn I do not see ellipsis for stack frame label

![image](https://user-images.githubusercontent.com/10746682/30972023-c2988a5a-a469-11e7-849b-595498b49a09.png)

**Comment by isidorn** [comment]
@sandy081 good catch. Will tackle that in october

**Comment by isidorn** [comment]
@joaomoreno dear wizard, my span always wraps in 2 lines no matter what I do. I tried the following:

```css
box-sizing: border-box;
white-space: nowrap;
overflow: hidden;
```

Might you have some advice?

![screen shot 2017-10-03 at 17 11 33](https://user-images.githubusercontent.com/1926584/31132788-fb587588-a85d-11e7-9313-fb3e35d5df35.png)

**Comment by joaomoreno** [comment]
Not sure I follow. 😕

**Comment by isidorn** [comment]
Due to the 
`min-width: fit-content` my span overflows to the second line even though it shuold only remain in one line. However I have to use this rule due to the flex layout and the priorty on which elements get hidden.

Closing as will not fix
