### ISSUE TITLE
"Select workspace interpreter" takes no effect when under Ubuntu16.04 

### ISSUE THREAD

**Issue by appleyuchi** [Microsoft/vscode#33322]
- VSCode Version:newest
- OS Version:ubuntu16.04

Steps to Reproduce:

1.type code from terminal
2.ctrl+shift+p and choose “select workspace Interpreter”
3、choose virtual environment of python
4、restart vs code
5、run the code as follows：

import sys
print(sys.prefix)
print(sys.executable)

---------without this line-------------------
vs code will output：
[Running] python "/home/appleyuchi/PycharmProjects/python/csdn_blogs_code/labs/hello2.py"
/usr
/usr/bin/python

[Done] exited with code=0 in 0.132 seconds

All above shows that the option “select workspace Interpreter”doesn‘t take effect，the
python has been used doesn't point to virtualenv。
All above is operated under Ubuntu 16.04，Not under windows
please help，thank you！

**Comment by jrieken** [comment]
Please file this issue against the python extension you are using. Thanks

**Comment by appleyuchi** [comment]
why do you close my issue?I use many python extensions ,I don't which extension caused this.
