### ISSUE TITLE
CSS: bad documentation for `css.trace.server`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33320]
Testing #33291

![image](https://user-images.githubusercontent.com/22350/29807744-8c3c3902-8c95-11e7-9252-f46fa14dfa0f.png)

https://github.com/Microsoft/vscode/blob/master/extensions/css/package.nls.json#L20

**Comment by aeschli** [comment]
But still interesting information, right?

**Comment by joaomoreno** [comment]
Never hurts to know the truth.
