### ISSUE TITLE
Store workspace folder paths in the same format across OS (forward slash)

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#33328]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T07:05:40.998Z)
- OS Version: Windows_NT x64 10.0.15063

---

This is a follow-up of #33188. When adding or removing files from a workspace and saving, the following:

```json
{
	"folders": [
		{
			"path": "Arcade/Breakout"
		}
	]
}
```

turns into:

```json
{
	"folders": [
		{
			"path": "Arcade\\Breakout"
		}
	]
}
```

on Windows. The reverse is true for Linux - it turns backward slashes into forward slashes. 

It actually looks like backslash paths still _work_ on Linux, and vice-versa. However, this could still be annoying if the `code-workspace` file is checked into a repo and you're working with people using different operating systems. It would make the diff way bigger than it has to be when modifying the workspace.

How about always using forward slashes?

**Comment by bpasero** [comment]
Let's fold into https://github.com/Microsoft/vscode/issues/33270

**Comment by Gama11** [comment]
Not sure I follow that argument. You can also manually change them to absolute paths. So how did defaulting to relative paths help? ;)

**Comment by bpasero** [comment]
@Gama11 if the user changed the path property in a way that does not match our rules, then I think we should keep the path untouched and follow the rules. It is actually quite simple:
* preserve slash vs backslash
* preserve absolute vs relative paths

**Comment by bpasero** [comment]
@Gama11 oh I see what you mean, yeah our default could be to just use forward slashes.

**Comment by bpasero** [comment]
Pushed changes to use forward slash if we detect that other paths in the file use forward slash as well.
