### ISSUE TITLE
Always offer installation of the mono debug extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3332]
Testing #2831 

![image](https://cloud.githubusercontent.com/assets/22350/13253960/3f846940-da3f-11e5-97ab-c9dd0624b3d7.png)

**Comment by isidorn** [comment]
Yes / no / later as propes in #2748

**Comment by joaomoreno** [comment]
I suggest to remove the `No` action, since users can easily block themselves into never seeing this message again.

**Comment by isidorn** [comment]
Added it to the extension tips of CS projects

**Comment by joaomoreno** [comment]
The reasoning behind @isidorn's change is: the user might block themselves into never seeing this message again but the extension will show up as a tip.
