### ISSUE TITLE
Initialize Git Repository option is gone

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#33325]
Version 1.16.0-insider
Commit d0d00e882437092f521d2d7893cc56ee296d278f

- open on a new folder
- open the SCM viewlet
- The 'Initialize Git Repository' button is gone. All that's there is to install more providers.

**Comment by joaomoreno** [comment]
The action is available in the global command palette. Do you confirm?

**Comment by aeschli** [comment]
Yes, it's there.
