### ISSUE TITLE
New icon too similar to sublime

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33329]
The current icon on mac uses same colors as the sublime and has a very similar shape.
IMHO this is wrong because our icon would make our users think of Sublime.

fyi @egamma @bpasero 

![screen shot 2017-08-29 at 10 31 29](https://user-images.githubusercontent.com/1926584/29811950-69eb9f36-8ca5-11e7-9773-9dbb048a0482.png)

**Comment by bpasero** [comment]
Sublime's new logo: 
![image](https://user-images.githubusercontent.com/900690/29812976-c0df4eb6-8ca8-11e7-8970-b1b9dbd9acd8.png)

**Comment by isidorn** [comment]
New logo looks equally similar. Also users are used to the old sublime logo and at least my brain works by first recognizing colors and only later shapes, that's why I easily confuse these two now.

**Comment by chrisdias** [comment]
Valid concern, but I don't see any "fix" for this.

**Comment by isidorn** [comment]
@chrisdias fix is to use different colors or a different icon imho

**Comment by stevencl** [comment]
With regards to the shape, we tested these icons quite extensively (with well over 100 people) and there was no indication that the shape of our new icon would be confused with the shape of the Sublime icon. Nobody suggested that they would confuse Sublime and VS Code, even those participants who use Sublime.

**Comment by bpasero** [comment]
@stevencl this is not about the shape but the orange foreground color for the logo and the dark background color being almost the same colors as Sublime.

**Comment by stevencl** [comment]
@isidorn mentioned the shape being similar so I just wanted to point out that during our studies we did not get that feedback. I understand that the colours are similar but I do not have any feedback on that.

**Comment by dominicfallows** [comment]
Perhaps related to some thoughts here  [#issuecomment-325998918](https://github.com/Microsoft/vscode/issues/6607#issuecomment-325998918) ?

**Comment by fab1o** [comment]
MAKE VSCode **BLUE** AGAIN
<img width="157" alt="blue" src="https://user-images.githubusercontent.com/6663243/30812717-88f8a34e-a1d9-11e7-8fe5-968574870c12.png">

**Comment by chrisdias** [comment]
We are using green for Insiders, orange for Stable, please see: https://github.com/Microsoft/vscode/issues/6607#issuecomment-334600845

**Comment by kellpossible** [comment]
@stevencl do many of those users you tested with regularly use both text editors or have them both installed on their computer? The icons really are very similar imho. Folded ribbon, with sharp angles, almost exactly the same colour....

**Comment by brunocassol** [comment]
![image](https://user-images.githubusercontent.com/203541/31428494-e6182a98-ae38-11e7-9b3a-63567ff54d86.png)

Please consider reverting the icon to blue. It's very confusing on Linux too. Both tools I love suddenly decided to have similar icons.

Where can I find the old blue icon? I'll try overwriting Code's icon in my linux dev machine.

**Comment by fritzlolpro** [comment]
One more blue icon?! Aru ya kiddin'?! Orange was really nice. Sublime text icon is different from vs code. But if vs code and visual studio are opened at the same time, now they are EXACTLY SAME ICONS!
