### ISSUE TITLE
EH Debugging: bogus column numbers

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33338]
testing #33305 on Windows:

- debug TypeScript hello world extension
- set breakpoint in the 'sayHello' command (e.g. line 21)
- F5

Observe: 
when hitting the breakpoint the CALLSTACK views shows column numbers that are way off:

![2017-08-29_10-53-13](https://user-images.githubusercontent.com/1898161/29812995-d11790a4-8ca8-11e7-84bc-37b3ee85f751.png)

**Comment by isidorn** [comment]
I have compared this our behavior in VS Code stable and it seems we were suffering from the same flow.
node1 debugger was also getting wrong column locations -> possilby connected to source map minifaction

**Comment by weinand** [comment]
I've verified, this is a minification problem.
