### ISSUE TITLE
SCM: hide views for repositories without changes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33334]
I am not a big fan of how crowded the SCM view is now looking like by default, even if there are no changes in any of the other repositories:

![image](https://user-images.githubusercontent.com/900690/29812400-b73ddf64-8ca6-11e7-8e64-925f94f3af35.png)

The additional UI below the actual changes makes me always think there are more changes I need to take care of.

Can we not hide a view when there are no changes? Or collapse it by default?

**Comment by joaomoreno** [comment]
This will make things very jumpy, as changes come and go... Definitely going to be a bad experience.

I suggest to simply collapse the repositories you don't use often. We can even add the change count to the header of each split view.

**Comment by sqs** [comment]
Would you be interested in a PR that implemented a UI like this? I just hacked this together tonight.

The Open Repositories section works like the Open Editors section; it grows (to a point) based on the number of open repositories. Selecting a repository shows that repository's (and only that repository's) SourceControlView in the rest of the viewlet. Focus is in the Open Repositories list initially.

It would be fairly easy to make it possible to show multiple repositories' SourceControlViews if you multi-selected them. That would of course be duplicating some functionality of a viewlet's subviews (e.g., you could make it so right-clicking on the Source Control header would let you check/uncheck each repo, as in the extensions viewlet), but it seems quite convenient to make this always visible.

![image](https://user-images.githubusercontent.com/1976/29813975-99e7a454-8c60-11e7-8de8-3502a4f6fbd1.png)

**Comment by joaomoreno** [comment]
It's very interesting indeed. Let's move that here: #33363
