### ISSUE TITLE
High CPU usage by TypingsInstaller

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#33339]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
pgsql|dou|0.0.8
EditorConfig|Edi|0.9.4
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
code-spell-checker|str|1.3.7

(1 theme extensions excluded)

---

Opening certain projects causes a process to spawn that apparently downloads TS support files. These processes regularly cause extremely high CPU usage over long periods of time. I don't think this is intentional.

The log has a lot of:
```
Response has been sent.
Closing file watchers for project '/dev/null/inferredProject3*'
Closing file watchers for project '/dev/null/inferredProject3*' - done.
Installing typings ["emitter"]
Entry for package 'emitter' does not exist in local types registry - skipping...
All typings are known to be missing or invalid - no need to go any further
```

I'm also seeing this, which looks like an error:
```
Installing typings ["@fairmanager/core-secur","emitter"]
Package '@fairmanager/core-secur' is scoped and currently is not supported
...
Installing typings ["@fairmanager/core-securi","emitter"]
Package '@fairmanager/core-securi' is scoped and currently is not supported
...
Installing typings ["@fairmanager/core-security","emitter"]
Package '@fairmanager/core-security' is scoped and currently is not supported
```
The package in question is named `core-security2`.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18263
