### ISSUE TITLE
Icon: does not work well on Windows 7

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33337]
It looks like on Windows 10 the background of the taskbar is always black, so the log works better there. However, see Windows 7:

![image](https://user-images.githubusercontent.com/900690/29812668-a7a9c29c-8ca7-11e7-8347-a966e9c30c9a.png)

Even worse, the taskbar color is determined from the wallpaper, e.g.:

![image](https://user-images.githubusercontent.com/900690/29812706-c6e4df0c-8ca7-11e7-835d-0a3f2007f058.png)

Or can be set directly (yes, where the gap is, the logo is):

![image](https://user-images.githubusercontent.com/900690/29812767-007e1710-8ca8-11e7-93a3-0b2b543682f0.png)

**Comment by Neme12** [comment]
Honestly, this could happen with any app that your background color will match the branding. This doesn't seem like an issue to me. You could always have a dark taskbar to let everything stand out.

**Comment by bpasero** [comment]
In my screenshot above, ALL other icons in the taskbar seem to work just fine across all taskbar backgrounds, only our new icon fails. So I would think we can do better.

**Comment by DickvdBrink** [comment]
In Windows 10 you can change the taskbar color, so you would have the same problem there.

Home > Personalization > Colors
Change your accent color
**enable** the "Start, taskbar and action center" checkbox under "Show accent color on the following surfaces"

If I make it blue my Edge color is hard to read, Green makes my Spotify icon a bit less clear so imo you can't really do the "right"  thing for everyone when you have an icon with a single color

**Comment by chrisdias** [comment]
https://github.com/Microsoft/vscode/issues/6607#issuecomment-334600845
