### ISSUE TITLE
Windows: new insider icon in small resolution is indistinguishable from stable version

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33330]
As we learned, in small resolution, the new logo looses its border to the right and as such you cannot distinguish the application from stable.

One suggestion is to go back to the green color for insiders.

**Comment by dbaeumer** [comment]
Verified that we have a green insider icon

<img width="107" alt="capture" src="https://user-images.githubusercontent.com/1931590/31017630-6dafae04-a529-11e7-8e75-7295893e5e3a.png">
