### ISSUE TITLE
modify editor.fontFamily="新宋体"  Space is 4 ,but now it's 8

### ISSUE THREAD

**Issue by syxcools** [Microsoft/vscode#33336]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.20.0
vscode-lua|gcc|0.1.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@syxcools can you share your settings and provide more details about "Space is 4 ,but now it's 8".
