### ISSUE TITLE
Explorer: view header comes and goes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33345]
Steps to Reproduce:

1. drop a folder into the window to open it
2. the view header in the explorer comes and goes (this is with opened editors view disabled)

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29813386-34a7194a-8caa-11e7-9704-77c90bde84a1.gif)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Still happening with:
* gitlens installed
* open editors hidden (via settings)
* git stash being collapsed in bottom of explorer

**Comment by sandy081** [comment]
We have a tricky scenario here `git stash` view is controlled by context and is made visible after a while. 

Assume that git stash view is visible and workbench is refreshed
- Before extensions are ready, we compute from cache and see there are 2 visible views.
- After extensions are ready, we see only visible view (git stash view is not visible by context).
- After a while git lens extension set the context to make git stash view visible.

Hence we see a jump here. Context control views are not in our control, so we cannot avoid the jump.

One proposal I have is, if there are custom views registered in the explorer, then do not show the header in the title even if custom views are hidden. What do you think?

**Comment by bpasero** [comment]
> One proposal I have is, if there are custom views registered in the explorer, then do not show the header in the title even if custom views are hidden. What do you think?

Does this mean to always show the (more heavy) splitview header for the explorer even when no other view is visible?

**Comment by sandy081** [comment]
Yes, only when explorer has custom views registered.

**Comment by sandy081** [comment]
After discussing with @bpasero we would leave with this flickering behaviour due to the reason mentioned in [comment](https://github.com/Microsoft/vscode/issues/33345#issuecomment-326276121)
