### ISSUE TITLE
[theming] set foreground of 'Open Changes', 'Replace' and 'Replace All' icons

### ISSUE THREAD

**Issue by jx22** [microsoft/vscode#33346]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
asciidecorator|hel|0.2.0
vscode-icon-theme|jtl|1.5.0
cpptools|ms-|0.12.3
wordcount|ms-|0.1.0
color-highlight|nau|2.3.0
spellchecker|swy|1.2.13

Steps to Reproduce:
1. Open a file in the editor.
2. Observe that the Open Changes, Replace and Replace All icons all contain some blue foreground portions that, as far as I can tell, cannot be modified. 

It would be nice if users could specify the foreground color of these icons, rather than just using the standard-issue little bit of blue foreground alongside the white foreground in the icons. A single color instead of two colors would be perfectly fine to modify the foreground of these icons, just like the Open Preview to the Side and Split Editor icons, in order to further enhance users' color themes.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Yes deafult icons are currently not customizable. @aeschli do we already have an issue tracking this?

**Comment by misolori** [comment]
I think we can allow for icons to inherit the foreground colors of their parent elements, but setting individual color tokens for each icon is not something that we're interested in doing.
