### ISSUE TITLE
Git: Allow closing git repositories

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33341]

**Comment by jrieken** [comment]
I this useful without persistence?

**Comment by joaomoreno** [comment]
Yeah persistence is an interesting part of it... I keep going back to it but I don't yet have a good story for it. Maybe we make it workspace based? I'll leave that for next iteration.

**Comment by bpasero** [comment]
I can remove a repository, but it comes back right after. See this video:

![panel-red](https://user-images.githubusercontent.com/900690/29925535-def61c9a-8e60-11e7-85bf-1c0a70b12439.gif)

**Comment by joaomoreno** [comment]
Moving the persistence story to #33596

**Comment by joaomoreno** [comment]
Actually reverting this. I'll remove the `Close` command from git altogether. #33363 should either make it obsolete, or much easier to deal with. 👍

**Comment by bpasero** [comment]
Command is gone.
