### ISSUE TITLE
Dragging the color slider does not work until a click is registered in the large canvas

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33344]
Testing #33295

![kapture 2017-08-22 at 11 23 40](https://user-images.githubusercontent.com/5047891/29813289-f9164ac2-8ca9-11e7-8f6e-78eae594ef80.gif)

**Comment by alexandrudima** [comment]
With further testing, this might be a generic problem with shades of gray ?

I would also not expect the large canvas to change shades while I'm dragging inside of it. Notice how it turns from green to yellow and then changes to red:
![kapture 2017-08-29 at 11 13 05](https://user-images.githubusercontent.com/5047891/29813710-2dfe27fe-8cab-11e7-98c8-c79b51fa640c.gif)

**Comment by rebornix** [comment]
Achromatic grays (rgb values are the same) have no hue (the hue code is indicated with a dash) so changing the hue will not change anything. We can probably disable hue strip in this case.

**Comment by rebornix** [comment]
The reason that changing the Hue value for achromatic grays, whose /rgb values are the same/saturation is 0/, doesn't change the background of the large canvas is the same as color changing while dragging inside the canvas: the loss of Hue value.

We internally convert HSLA to RBGA and only stored the RGBA value. However, if the saturation of HSVA is 0, no matter what the Hue value is, the result RGBA will be the same, e.g. `(Hue: 100, Saturation: 0, Luminosity).toRGBA() === (Hue: 25, Saturation: 0, Luminosity).toRGBA()`.
