### ISSUE TITLE
Smooth scrolling isn't so smooth when jumping long distances

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33347]
re #33299

* open a very large file, e.g `checker.ts` from the TypeScript repo
* be on the first line
* open quick outline and scroll down to the last entry in its list and select it (don't select other items in the list)
* the smooth scrolling visually stales a few times

**Comment by alexandrudima** [comment]
I will tweak the animation function in a large distance scroll case.

See explanations in https://github.com/Microsoft/vscode/issues/33414#issuecomment-326046718

**Comment by alexandrudima** [comment]
This has been mitigated by adding two stop points to the animation if the scroll distance is large.
