### ISSUE TITLE
Debug dropdown misplaced

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#33357]
Version 1.16.0-insider (1.16.0-insider)
d0d00e882437092f521d2d7893cc56ee296d278f
Elementary OS Freya (Ubuntu 14.4)

- open a new instance of VSCode
- open the launch config drop down in the debug view: Correctly placed
- use the 'File > Open Folder' menu to open a new folder
- open the launch config drop down in the debug view: Dropdown is placed to high
- close the drop down, click again, now placed at the right place

![image](https://user-images.githubusercontent.com/6461412/29814078-651ebea0-8cac-11e7-995e-75cfe74ec922.png)

**Comment by aeschli** [comment]
Also happens with the dropdown in the terminal.
The bug has been around for quite some time, I just forgot to file it right away.

**Comment by isidorn** [comment]
99% this is an electron issue. 
The best would be to reproduce with a barebone electron startet and file it against electron. There is nothing I can do here since this are all native elements
