### ISSUE TITLE
Selecting an item from references view is weired

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33351]
re #33299 

* have code lenses in every file, e.g git lens
* open reference search on something
* double-click on an entry of a different file
* the reveal often yields in bad results (see screen shot)

![aug-29-2017 11-12-32](https://user-images.githubusercontent.com/1794099/29813647-fbe15a2a-8caa-11e7-96ae-634f64965933.gif)

**Comment by alexandrudima** [comment]
Fixed via e070afceabc88e57190697c9a79dc3ab3a98d3d5

**Comment by jrieken** [comment]
@alexandrudima  It is still a little nervous. I guess we first reveal the viewport smoothly and then comes in the peek view (which we don't animate ;-))
