### ISSUE TITLE
Flicker when revealing definition 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33356]
re #33299

* cmd+alt+click on a symbol with multiple definitions
* the outer and inner editor jump up and down

![aug-29-2017 11-19-34](https://user-images.githubusercontent.com/1794099/29814004-222c15e8-8cac-11e7-8d78-7539ed75affb.gif)

**Comment by alexandrudima** [comment]
I think this is also fixed after e070afceabc88e57190697c9a79dc3ab3a98d3d5 . There is still some jumpiness, but that happens even with smooth scrolling off, due to the code lenses being lazily computed.
