### ISSUE TITLE
Debug breakpoint not showing as resolved nor hit in multi root workspace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33355]
Steps to Reproduce (macOS):

1. generate an extension and open it as folder and debug a little bit (add breakpoints)
2. generate another extension and drop this folder into the explorer to create a multi root workspace
3. add a breakpoint into the second extension (it shows up as unresolved for me)
4. start the extension and make sure the breakpoint code is executed
5. the breakpoint now turns into a resolved breakpoint but only the second invocation makes it stop there

This seems multi-root workspace related?

**Comment by isidorn** [comment]
Wheter breakpints get resolved or not is entierly up to the debug adapter. Also if I debug two regular node apps in MR setup it seems to work fine for me.

Also what seems to be weird from your steps is that you say you get an unresolved breakpoint before even starting any debugging. This seems highly unlikely to me, did I get the steps right?

**Comment by bpasero** [comment]
Hm, I cannot reproduce when I try again fresh. I see however an issue with extension host debugging a JS extension: https://github.com/Microsoft/vscode/issues/33373

**Comment by isidorn** [comment]
@bpasero yes that one @weinand also found and we believe the issue lies in the adapter

**Comment by bpasero** [comment]
Maybe @roblourens could also try to reproduce with my steps and if that fails, we close this for good.

**Comment by weinand** [comment]
I tried to reproduce the issue with two TypeScript extensions "hello1" and "hello2" in a multifolder workspace on Windows. But with this setup everything seems to work fine.

But using a JavaScript extension and a TypeScript extension in a multifolder workspace, breakpoints weren't hit most of the time.

I strongly believe that this is a multifolder issue. 
I think this is just another instance of #33375 and/or #33354.

**Comment by roblourens** [comment]
Sorry for not responding but I agree that this was #33375 and #33354, LMK if there's something else that wasn't covered already.
