### ISSUE TITLE
I want to develop a form for submitting information about the current page。Is there any solution？

### ISSUE THREAD

**Issue by xyxuyao** [Microsoft/vscode#33352]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Please provide more details

**Comment by xyxuyao** [comment]
I want to extend a vscode plug-in。
A plug-in like this：
![issue](https://user-images.githubusercontent.com/13941855/29852428-980d3574-8d6c-11e7-9aa2-03138837e6a9.png)

**Comment by jrieken** [comment]
Thanks. Duplicate of #1833
