### ISSUE TITLE
Color decorators do not react to settings changed

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33353]
Testing #33295

* after changing the color decorators settings, there is a need to resize an editor for the settings change to take effect. If it's only about the old deprecated settings, then please feel free to close.

![kapture 2017-08-29 at 11 17 55](https://user-images.githubusercontent.com/5047891/29813885-bc779b50-8cab-11e7-97aa-35a70d7d6f84.gif)

**Comment by alexandrudima** [comment]
Yeah, looks like it reacts correctly for the proper `editor.colorDecorators` setting. I think that's good enough.

**Comment by rebornix** [comment]
FYI, for the deprecated `css.colorDecorators.enable`, we didn't listen to the change (which requires a listener for all content change in the workspace but not just editor).
