### ISSUE TITLE
Debug: multiple "Loaded Scripts" sections?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33350]
I am not sure how I got into this state, but I am seeing multiple of "Loaded Scripts" sections in the menu of the debug viewlet:

![image](https://user-images.githubusercontent.com/900690/29813603-d4b8ea62-8caa-11e7-86a9-2970bb5e9bdc.png)

**Comment by weinand** [comment]
There are actually four views registered under the same ID and the "when" clause makes sure that only one is active:
```json
			"debug": [
				{
					"id": "extension.node-debug.loadedScriptsExplorer",
					"name": "%loaded.scripts.view.name%",
					"when": "inDebugMode && debugType == 'node'"
				},
				{
					"id": "extension.node-debug.loadedScriptsExplorer",
					"name": "%loaded.scripts.view.name%",
					"when": "inDebugMode && debugType == 'node2'"
				},
				{
					"id": "extension.node-debug.loadedScriptsExplorer",
					"name": "%loaded.scripts.view.name%",
					"when": "inDebugMode && debugType == 'extensionHost'"
				},
				{
					"id": "extension.node-debug.loadedScriptsExplorer",
					"name": "%loaded.scripts.view.name%",
					"when": "inDebugMode && debugType == 'chrome'"
				}
			]
```
The reason for registering 4 views is the missing support for the OR operator in "when" clauses.

@sandy081 since all views have the same ID, shouldn't you show only one for all?

**Comment by sandy081** [comment]
Looks like a bug to allow multiple views with same id. Probably you have to use unique ids. 

I am planning not to show disabled views (views not visible because of context) from the context menu as this is not helping users and is confusing.

**Comment by weinand** [comment]
> I am planning not to show disabled views (views not visible because of context) from the context menu as this is not helping users and is confusing.

Yes, that would fix this. We should do this.
