### ISSUE TITLE
Clarify in docs what should happen if more than one provider is registered for the same type

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33364]
Refs: #33248

Currently from api comments it is not clear what is expected to happen if multiple providers are registered for the same type. It simply says this is allowed. I suggest to mention that all configurations will get merged

![screen shot 2017-08-29 at 11 46 28](https://user-images.githubusercontent.com/1926584/29815136-e5adea16-8caf-11e7-8b28-b4f428eea3b6.png)

**Comment by isidorn** [comment]
Only now found that this is actually mentioned for provideDebugConfigurations method.
Sorry for the false alarm

**Comment by weinand** [comment]
Since the behaviour depends on the semantics of the individual hooks, it is mentioned in the two method comments, not the interface comment.
