### ISSUE TITLE
Extension Host Restart doesn't close messages from previously crashed extension host

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#33368]
Testing #33300 

- I had an extension host crash after an error

![image](https://user-images.githubusercontent.com/172399/29815745-03285b60-8cb2-11e7-8ed6-9fbe51182b10.png)

- I executed Restart Extension Host. 

I ended up in this state

![image](https://user-images.githubusercontent.com/172399/29815906-928fc112-8cb2-11e7-9962-9e487727a390.png)

Suggest to close the messages, since with the message box visible it is not clear to me when the extension host restart is done.

**Comment by alexandrudima** [comment]
... I could call `IMessageService.hideAll()` ... although there is no proof that the errors are correlated. But I see lots of calls to that from other places that have no clue what they're dismissing...
