### ISSUE TITLE
New Icons has bad contrast on windows

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33360]
Two cases

1. While the installer runs a greenish progress-bar is rendering behind the icons and the orange on green doesn't work well

<img width="166" alt="screen shot 2017-08-29 at 11 33 57" src="https://user-images.githubusercontent.com/1794099/29814647-5e1d029a-8cae-11e7-8a17-9aa927e02884.png">

2. In my start menu the background color is a strong blue and that also doesn't work well

<img width="185" alt="screen shot 2017-08-29 at 11 35 37" src="https://user-images.githubusercontent.com/1794099/29814664-6bfeca2e-8cae-11e7-821d-5dff8e1748ae.png">

**Comment by bpasero** [comment]
Related to https://github.com/Microsoft/vscode/issues/33362

**Comment by chrisdias** [comment]
The solid icons should have better contrast, please see https://github.com/Microsoft/vscode/issues/6607#issuecomment-334600845
