### ISSUE TITLE
Windows: logo does not have a specific background

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33362]
We should follow up if the logo on Windows startmenu should also have a specific background set (like the VS one). Currently it seems to use the default blue color.

![logo](https://user-images.githubusercontent.com/900690/29814890-2743c8fc-8caf-11e7-8eac-9681ee9cdcb8.png)

**Comment by qpegg** [comment]
I have wanted this. Thanks!

**Comment by isidorn** [comment]
When installing VSCode on windows I get the white background during the installation process which actually looks good. Which makes me believe that the person designing the icon had only white background in mind

![screen shot 2017-08-29 at 16 57 48](https://user-images.githubusercontent.com/1926584/29827848-5ef880b8-8cdb-11e7-815c-af1e6842d938.png)

**Comment by ghiscoding** [comment]
@isidorn just a thought but the white background might pop out too much when using Windows 10 dark theme. On a light theme it makes perfect sense though. I'm on a dark theme and the only icon I have with a white background is Opera.

**Comment by gbale** [comment]
+1 and this should help:
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn449733.aspx

**Comment by dominicfallows** [comment]
Perhaps related to some thoughts here  [#6607 #issuecomment-325998918](https://github.com/Microsoft/vscode/issues/6607#issuecomment-325998918) ?
