### ISSUE TITLE
Html format

### ISSUE THREAD

**Issue by Charon3coins** [Microsoft/vscode#33370]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
code-runner|for|0.7.1
vscode-auto-open-markdown-preview|hnw|0.0.4
vetur|oct|0.9.5
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1.the "format" command doesn't work with  ` <select>`  element    in  HTML files
2.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Check out the `html.format.unformatted` setting. `select` is in the list of tags not to be formatted.
