### ISSUE TITLE
no intellisense

### ISSUE THREAD

**Issue by Jack85** [Microsoft/vscode#33372]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
stylus|Ala|0.0.4
stylus|buz|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm-source|dku|1.0.0
vscode-npm-script|eg2|0.2.0
vscode-nupkg|eri|0.0.8
vscode-npm|fkn|3.3.0
flow-for-vscode|flo|0.7.1
vscode-firefox-debug|hbe|0.15.3
vue-snippets|hol|0.1.2
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.4
sublime-babel-vscode|jos|0.2.6
net-core-project-manager|ksu|0.3.6
csharpfixformat|Leo|0.0.32
tgit-cmds|mbi|1.1.1
vscode-less|mrm|0.6.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.0
vetur|oct|0.9.5
csharp2ts|raf|0.0.17
vscode-flow|rto|276.3.0
aspnet-helper|sch|0.6.3
stylelint|shi|0.28.0
language-stylus|sys|1.7.3

---

Steps to Reproduce:

1. dotnet build
2. no csharp intelisense

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Do you use an extension that promised C# IntelliSense?

**Comment by Jack85** [comment]
yes c# ver 1.12.1

**Comment by jrieken** [comment]
Ok, please file this issue against https://github.com/OmniSharp/omnisharp-vscode. Thanks
