### ISSUE TITLE
Console panel display unidentifiable Chinese code

### ISSUE THREAD

**Issue by leeneo** [Microsoft/vscode#33377]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
live-html-previewer|hdg|0.2.0
beautify|Hoo|1.1.1
vs-color-picker|lih|0.6.0
easy-less|mrc|1.4.5
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.http://xingzhihen.com/images/feedback-img/2017-08-29_195110.png
2.http://xingzhihen.com/images/feedback-img/2017-08-29_195123.png

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
@leeneo is this powershell?

**Comment by Tyriar** [comment]
Actually this is the output and debug console panels, not terminal.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/4664 and https://github.com/Microsoft/vscode/issues/571
