### ISSUE TITLE
EH Debugging: breakpoints not hit in JavaScript

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33375]
testing #33305 on Windows:

- create **JavaScript** hello world extension
- set breakpoints in lines 3, 11, 16, 20, 25
- press "F5" and wait until EH windows appears and is ready
- run "Hello" action

Observe: 
sometimes no breakpoint is hit, or only breakpoint on line 20 is hit.
I was never able to break on any other breakpoint.

**Comment by roblourens** [comment]
Duplicate of #33373
