### ISSUE TITLE
Unsaved file does not detect underlying file changes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33374]
Refs: #33302

1. Have auto save off, make changes to a file.
2. Open the same file in some other editor and make changes to it and save
3. Go back to vscode and save your original changes. Notice that the saved changes from step 2 get overwritten. I would expect I get some conflict dialog

**Comment by bpasero** [comment]
@isidorn I cannot reproduce and I think it is unrelated to #33302. does it reproduce all the time?

**Comment by isidorn** [comment]
@bpasero for some reason I can no longer reproduce this.
Yes it is unrelated to the undo stack, I just found this while testing that

Will reopen if I see it again

**Comment by bpasero** [comment]
@isidorn the condition that brings this up is relatively simple: the modification time of the file is checked before saving, and if that one is newer it means another editor has changed it.
