### ISSUE TITLE
Retain the selection after tree refresh

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33371]
Steps to Reproduce:

1. install docker extension
2. click with the mouse into the contributed explorer

=> focus is shortly removed out of the view
=> focus should stay so that keyboard interaction is possible

![flicker_chrome58](https://user-images.githubusercontent.com/900690/29816438-4ff0bdc8-8cb4-11e7-8310-dc09a9663701.gif)

**Comment by sandy081** [comment]
It is not true in all custom views. Looks like this is having a command that is causing this.

**Comment by bpasero** [comment]
Ok then it should maybe move into the docker repository.

**Comment by chrisdias** [comment]
i'm refreshing the tree every second :(

**Comment by sandy081** [comment]
I see may be I should retain the selection after refresh. I should have a fallback if the selected item is gone after refresh

**Comment by eamodio** [comment]
Yeah, it would be great if it was retained -- expand/collapsed state too.

While it would great for the view to do this itself, at least having a new API where the extension could attempt to maintain it would also work (though obviously more work on the part of the extension). But an API for it could be valuable in other situations where you might want to cause selection in the tree. Of course that would also have to deal with expansion too for nested things.

**Comment by eamodio** [comment]
Noooo - Backlog 😢 Is there another way around this? Right now an extension can't even maintain its selection so there is no way to get a better experience.

**Comment by sandy081** [comment]
@eamodio I do not want to assign to a milestone and give false hopes. Actually I would collect the next set of features for tree views and discuss for our plan and assign the milestone.

**Comment by weinand** [comment]
I'm bumping the severity of this since it makes the tree almost unusable.

**Comment by weinand** [comment]
This is a bug not a feature.

**Comment by sandy081** [comment]
Fixed by cb926d58e4c12223f2e4ccb4751787c8326bc9f6

**Comment by weinand** [comment]
While verifying the fix with my extension, I've noticed that the selection is only retained if the label of the tree node does not change. If the label changes (e.g. because one part of it reflects a status), the selection is still lost.

I've created issue https://github.com/Microsoft/vscode/issues/40018 for this.
