### ISSUE TITLE
Debug: breakpoint for JS extension not hit until second invocation

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33373]
Steps to Reproduce:

1. generate a JS extension (JS!)
2. add breakpoint where the hello world info message is triggered

=> only after invoking the hello world command a second time is the breakpoint hit for me (macOS, todays insider build)

**Comment by roblourens** [comment]
Sounds like it is not setting BPs optimistically for unloaded scripts, when there is no sourcemap. Thought this had been fixed.
