### ISSUE TITLE
Terminal doesn't show / open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33379]
Testing: #33274 

I was not able to consistently reproduce this but sometimes the terminal / prompt didn't show up when opening the integrated terminal.

<img width="1389" alt="capture" src="https://user-images.githubusercontent.com/1931590/29820279-4e83bf48-8cc4-11e7-990c-1ac51c209c86.png">

**Comment by Tyriar** [comment]
That's a strange state to be in, for conhost to exist but not powershell.exe. I've never seen this and can't repro. If you find any more details on a repro let me know.
