### ISSUE TITLE
scripts\test.bat can't be executed in integrated terminal. Progress dots aren't rendered

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33384]
Testing: #33274 

- vscode workspace
- compile
- execute scripts\test.bat in integrated terminal

Observe: no dots are printed to show progress

- Do the same in HyperJS. Observe: dots are printed.

**Comment by Tyriar** [comment]
@dbaeumer works for me using:

```js
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

Do you have the PowerShell extension installed? Could you try repro on latest as some fixes went in last night.

**Comment by dbaeumer** [comment]
@Tyriar couldn't reproduce in latest insider.

Closing.
