### ISSUE TITLE
Initialize size of split views in SCM should be equal

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33383]
#33267

1. Have a mr workspace with two workspaces each having git support
2. Notice the inital layout of views in the SCM viewlet is not equal. The second workspace just gets around 20% of space
3. Doing some changes in the second workspace will leave the split view very small. Due to that I believe they should be the same size to start with. This way it is easier for user to not discover that we support git in a MR environment

![screen shot 2017-08-29 at 14 22 47](https://user-images.githubusercontent.com/1926584/29820669-8e00e5dc-8cc5-11e7-8f51-8fc2d72cb8a1.png)

**Comment by joaomoreno** [comment]
I'm pretty sure this isn't true. The initial layout, without any persistence, will always be perfectly split.

There must be something else, investigating.

**Comment by joaomoreno** [comment]
Yep steps:

- Have two repositories open, from two open folders
- Collapse the second one
- Remove the second folder from the workspace
- Add it again

**Comment by sandy081** [comment]
@joaomoreno When you add it back what is the initial size? Guessing there is no initial size and default size was taken

**Comment by isidorn** [comment]
I still see this in the latest.
Whenver I add a new folder to a workspace it's git view is the minimal size, not equal. I would not expact that -> reopening

![git](https://user-images.githubusercontent.com/1926584/29914684-b798a18a-8e39-11e7-9c7b-7823ecbe4257.gif)

**Comment by isidorn** [comment]
Sorry but I have to reopen this, it is still not behaving like it should.
Once a split view to git is added the size should be split between them, however the current way random views get minimized (even though they had a good size before a new view is added).

Tried out with latest insiders which contains your fix.

**Comment by chrmarti** [comment]
Starting from none and then adding Git repos to subfolders of a single workspace folder still gets out of balance at 3:
![image](https://user-images.githubusercontent.com/9205389/29982826-1a16412c-8f08-11e7-8982-d5fe75870777.png)

And then more (never changing the size manually):
![image](https://user-images.githubusercontent.com/9205389/29982859-40c18c64-8f08-11e7-8c87-16151a19a030.png)

Reopening for consideration. Not critical for the release from what I see.

**Comment by joaomoreno** [comment]
That's ok.

**Comment by isidorn** [comment]
1. code-insiders --user-data-dir SOME_NEW_PATH
2. Open some folder in code, like vscode, open the git view, close vscode
3. Start code-insders again as in step 1., add a second folder to your workspace
4. Notice that the second folder is minimized in the git view

I would expect them to be the same size in 4.

IMHO the issue comes from the fact that when closing vscode in step 2 you remember that the first folder has the maximum size of the pane and that leads to the fact that in 4 it pushed out the second folder.

**Comment by joaomoreno** [comment]
Fixed in `master`. Initial sizes are now completely different. If you multi select in the provider list, the entire space will be split among all views.

**Comment by isidorn** [comment]
We no longer use split views for git -> verified

**Comment by sandy081** [comment]
@isidorn I think we use split views for git especially in a Multi root workspace when you select multiple repositories

**Comment by isidorn** [comment]
@sandy081 thanks for letting me know. Though now whenever I select an additonal repo the space is always evenly split between them -> verified
