### ISSUE TITLE
Call `registerDebugConfigurationProvider` when adding a new config?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33380]
re #33248

I wonder if we should call `registerDebugConfigurationProvider` of all providers when the "Add Configuration" button in the lower right of `launch.json` is clicked. That would help me with existing launch.json-files.

**Comment by isidorn** [comment]
Currently for "Add Configuration" we are only showing a list of snippets.
I guess you are arguing that `provideDebugConfiguration` should also be called in that case which I think makes sense however the provided debug configuration currently does not have a label like a snippet and there are some other discrepencies.

**Comment by isidorn** [comment]
Due to the DebugConfiguratinoProvider not providing snippets at the moment closing this as no action planned.
