### ISSUE TITLE
Terminal has scroll bar after second launch allowing to scroll away inside buffers

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33382]
Testing: #33274 

Windows, PowerShell

- open terminal
- start nano on a file

Observer: the terminal has no scroll bar

- close nano
- start nano again

Observe: the terminal has a scroll bar and user can scroll

<img width="1083" alt="capture" src="https://user-images.githubusercontent.com/1931590/29820561-323e9cd0-8cc5-11e7-88e1-d2c2717f8e24.png">

**Comment by Tyriar** [comment]
@dbaeumer how are you installing nano?

![image](https://user-images.githubusercontent.com/2193314/29882817-18ebca66-8d63-11e7-93e6-21816a78948a.png)

It doesn't seem obvious on https://www.nano-editor.org/download.php

**Comment by dbaeumer** [comment]
I used https://github.com/bmatzelle/gow/wiki

**Comment by Tyriar** [comment]
It seems gow nano is very easy to break in a regular cmd.exe window.

![image](https://user-images.githubusercontent.com/2193314/34497422-60081272-efb2-11e7-8381-1ab5e1ad4310.png)
