### ISSUE TITLE
Git: Cannot read property 'resourceUri' of undefined

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33389]
Refs: #33267

1. Have a MR workspace with multiple folders having git
2. Try to stage iles in the third folder (in my case newly initiated repository with 10 files)
3. Seldomly I get `Git: Cannot read property 'resourceUri' of undefined`

I tried stopping on an exception but it does not stop so sorry for not providing more data. I believe you can easily repro it

**Comment by joaomoreno** [comment]
I never saw this... please try to reproduce.
