### ISSUE TITLE
Consider using only one commit input field instead of multiple

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33387]
refs: #33267

1. Have a MR workspace with multiple folders each having git
2. Notice that for each of these we duplicate the commit input field.
3. Due to this duplication we are loosing valuable screen space and it looks ugly on top of that

I propose that we only have one input field which would live on the top, seperated from the rest of the panes. This way the viewlet would be cleaner and nicer imho

**Comment by joaomoreno** [comment]
We have considered. This first month is a way to get the changes out. Upcoming: #33363

**Comment by isidorn** [comment]
I am not arguing here wheter to use a master / slave model or the current one. I am arguing that in both models we should use only one commit box
