### ISSUE TITLE
Improve relative paths in launch.json migration

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3338]
I've hit this while testing #2940:

![image](https://cloud.githubusercontent.com/assets/22350/13255006/4bd56ec4-da44-11e5-8ecf-410858ea17af.png)

I didn't know how to fix, since the file exists in the repository. After a while I opened `launch.json` and found the warning:

![image](https://cloud.githubusercontent.com/assets/22350/13254991/396743b6-da44-11e5-9e20-4bafda1f0a69.png)

- This should be a red error, not a green warning, since debug won't work.
- The original error should have informed me about the possible problem, since I wasn't aware of the change of `${workspaceRoot}`

**Comment by isidorn** [comment]
@aeschli as mentioned I would need a way to specify to the JSON schema that this is the error
@weinand I am getting the error message from the adapter. I could massage the error and add a sentence about the ${worspaceRoot} or this could be done directly in the debug adapter. What do you think?

**Comment by weinand** [comment]
@isidorn yes, I can do something in the adapter similar to this: "cannot launch program '{path}'; enabling source maps might help"

**Comment by egamma** [comment]
We must be more explicit here, a warning or an error decoration in the launch.json is not instrusive which is nice but also not obvious, the user has to hover over them etc. 

We should just show an error message:  Relative path names are depracted use...`. I know that this is how we started and then we tried to make it more subtle. This issue illustrates that trying to be more subtle is not helpful for users.

**Comment by isidorn** [comment]
-1 for the error message upon open of `launch.json`, users were not complaining then because they just ignored it and we were still automatically converting so everything worked for them and nobody complained. We are no longer automatically converting so now the situation is different.
I suggest we do what Joao originally suggested, in the adapter side create a more helpful error message. And I will try to make those warnings into errors

**Comment by egamma** [comment]
What is the reason for no longer converting or help the user to convert a relative path? We detect a relative path and we know we no longer support, so why not do what we did in the past?

**Comment by egamma** [comment]
>-1 for the error message upon open of  launch.json , 
I was not suggesting to do this upon open of the launch.json, but to show the error upon launching, that is when the user presses F5

**Comment by weinand** [comment]
@egamma two reasons:

- we wanted to use the same model as 'tasks': no magic! Paths used in the launch.json are not modified in any way (like tasks.json).

- previously we had a hardcoded list of well known path attributes that we would automagically convert into absolute paths. Since attributes are now contributable, we do not know which attributes need this treatment. The debug adapter knows nothing about a workspace, so it cannot convert relative paths into absolute ones because it does not know the workspace root.

**Comment by isidorn** [comment]
@egamma we would show this nicer error message upon pressing F5 so I think we are in alignment here

**Comment by weinand** [comment]
@egamma yes, I will add this hint on my side.

**Comment by egamma** [comment]
sold

**Comment by chrisdias** [comment]
I just spent a bunch of time trying to figure out why my app from vscode-samples wouldn't run.  The updated error message in https://github.com/Microsoft/vscode-node-debug/commit/ce36f927da0f9417d5c93cb8c239bf042ba2a92b will certainly help.  

Can we include a "More Information" link in that message and point to the release notes, where I assume this will be covered in greater detail. I am guessing that many, many people who have an existing launch.json will be broken with this change.

Also, why did we remove all of the comments from the launch.json?

**Comment by isidorn** [comment]
We removed all the comments from the launch.json 5 sprints ago because we felt they were not bringing additional value since all of that can be seen by either hovering or reading our documentation. No user complained so I think it was a good change.

**Comment by weinand** [comment]
@chrisdias we've removed comments from the default configs in launch.json because they are contributed in the extension's package.json: comments would invalidate the json syntax which would result in problems with all tools that cannot deal with comments in json.

**Comment by weinand** [comment]
@chrisdias currently it is not possible to pass a "More Information" link from a debug adapter to the frontend that actually works as a link. So just seeing the link in its raw form would only clutter the error message. I've created #3448 to track this new feature.

The current error message looks like this:

![2016-02-25 10-34-56](https://cloud.githubusercontent.com/assets/1898161/13315529/7be64774-dbab-11e5-8ac4-e1854e5ffe68.png)

**Comment by chrisdias** [comment]
@isidorn @weinand thanks for the info on the comments, i always use bits from https://github.com/microsoft/vscode-samples so I never regenerate the `launch.json` :)

**Comment by weinand** [comment]
@chrisdias aha, I see (and love those fancy looking launch.jsons ;-)

![2016-02-25 23-23-11](https://cloud.githubusercontent.com/assets/1898161/13336571/e823aa74-dc16-11e5-83a3-11afc0dcd523.png)

Another reason why comments in json files a problematic...
