### ISSUE TITLE
Show the workspace configuration file when opening VS Code from workspace file

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33388]
Testing #33278

- Have a workspace configuration file on disk
- Double click on it to open
- VS Code opens the workspace which is good

It will be also good to show the file when the workspace is open. Also true when user drags and drop the workspace configuration file.

**Comment by bpasero** [comment]
I am not sure I would agree, everytime you open a workspace like that you would see the workspace file very prominently. I think in most cases a user just wants to restore the state the workspace had before and not care about the contents.

Compare this to opening a folder today: would you want each time you open a folder to see an editor that shows you the metadata associated with that folder (e.g. settings)?

**Comment by sandy081** [comment]
I thought about the folder argument and agree with yours too.

Actually now I can open the file in VS Code only from VS Code but not from outside easily.

**Comment by bpasero** [comment]
Yeah you cannot drop the file into a window or pass it as argument from the command line to see it raw.

**Comment by bpasero** [comment]
Closing "as designed", I think our current behaviour is good.
