### ISSUE TITLE
VS Code debugger doesn't exit after program run

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#3339]
When debugging the following simple project (only a `gulpfile.js`), the debugger doesn't exit after the last line of code has been executed:

[Gulp4ParallelTest.zip](https://github.com/Microsoft/vscode/files/142778/Gulp4ParallelTest.zip)

----
```json
{	"version": "0.2.0"
,	"configurations":
	[	{	"name": "Gulp"
		,	"type": "node"
		,	"request": "launch"
		,	"program": "${workspaceRoot}/node_modules/gulp/bin/gulp.js"
		,	"stopOnEntry": false
		,	"args": []
		,	"cwd": "${workspaceRoot}"
		,	"runtimeExecutable": null
		,	"runtimeArgs":
			[	"--nolazy"
			]
		,	"env":
			{	"NODE_ENV": "development"
			}
		,	"externalConsole": false
		,	"sourceMaps": false
		,	"outDir": null
		}
	]
}
```

**Comment by weinand** [comment]
@SetTrend the debugger only exits if node exits. Node programs have the tendency not to exit under debugging. You will find the same behaviour with node-inspector so this is not a VS Code specific problem.

**Comment by SetTrend** [comment]
Thank's for enlightening me. Would you suggest this is more or less a Node bug? Then I would tend to create an issue there.

I feel it's quite confusing not to safely know whether a program has finished or not. Don't you, too?

**Comment by weinand** [comment]
@SetTrend I'm not sure whether this is a node bug. It might be difficult for the node runtime to decide whether there are any events expected and the runtime needs to continue running or not. Yes, please file an issue with node. I'm interested in their response.
