### ISSUE TITLE
Some git actions ask me for the repo, some assume automatically

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33397]
Refs: #33267

1. MR workspace with multiple git repositories
2. command palette > git pull I am presented a choice from which repo to pull from -> makes sense
3. Have changes in each repo, command palette > git stage  I am **not** presented a choice but git automagically picks a repository for which to stage

I think we should be consistent here and always ask if an action is being exectued from the command palette

**Comment by joaomoreno** [comment]
The global git stage (unstage, revert) command always picked up the current open file as the file to stage. We can't back out from that, and it does make sense.

I wasn't brave enough to do the same assumption to all other commands, so I decided to present a picker for those. I say we run a milestone with the current solution and wait for the outcry.

**Comment by joaomoreno** [comment]
It doesn't seem to be that big of a problem.
