### ISSUE TITLE
Cannot open a workspace when there is a empty folder entry

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33391]
Testing #33278

- Have the following folders in a workspace configuration file
```
"folders": [
		{
			"path": "gotypes"
		},
		{},
		{
			"path": "outyet"
		},
		{
			"path": "stringutil"
		}
	],
```
- Open workspace on the above file

No workspace is opened. Instead, file is opened

**Comment by bpasero** [comment]
Also fixed via https://github.com/Microsoft/vscode/commit/b2cd2e0b16f91638ce3ac6e14c777e362e616711
