### ISSUE TITLE
new VS Code icon doesn't look right in Windows Open dialog

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33398]
ref #33272:

When double clicking on workspace file on Windows I get this dialog:

![2017-08-29_12-58-22](https://user-images.githubusercontent.com/1898161/29822432-b84cb874-8ccb-11e7-889e-46745c6e5a07.png)

The icon doesn't look right in this context.

**Comment by bpasero** [comment]
Probably fixable via https://github.com/Microsoft/vscode/issues/33362

**Comment by weinand** [comment]
duplicate of #33433
