### ISSUE TITLE
Closing style tag highlighted incorrectly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33399]
Testing: #33292 

See screen shot: The `<` of the closing tag is not rendered correctly

<img width="451" alt="capture" src="https://user-images.githubusercontent.com/1931590/29822655-7aaf79f6-8ccc-11e7-9694-5b252bc6af2f.png">

**Comment by aeschli** [comment]
Which theme do you use?
This is how it looks with the Default+ theme: 
![image](https://user-images.githubusercontent.com/6461412/29823902-552ca43e-8cd0-11e7-905a-57c78997aca5.png)

**Comment by dbaeumer** [comment]
Slime: https://marketplace.visualstudio.com/items?itemName=smlombardi.slime

**Comment by aeschli** [comment]
Filed https://github.com/textmate/html.tmbundle/issues/74 against the HTML grammar as it does some tricks there.
