### ISSUE TITLE
Do not show invalid or not existing folders 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33390]
Testing #33278

- Open a multi root workspace with relative URIs
```
"folders": [
		{
			"path": "gotypes"
		},
		{
			"path": "hello"
		},
		{
			"path": "outyet"
		},
		{
			"path": "stringutil"
		}
	]
```
- Change the first URI to not existing location
```
"path": "/gotypes"
```
-  Open the first folder in the explorer

An error is shown 

![image](https://user-images.githubusercontent.com/10746682/29821624-e4f3188a-8cc8-11e7-8c65-5d094abf20c8.png)

**Comment by bpasero** [comment]
@sandy081 isn't this already covered in https://github.com/Microsoft/vscode/issues/31011 or https://github.com/Microsoft/vscode/issues/31001 ?

**Comment by sandy081** [comment]
@bpasero Yes. 
Forget about those.

Duplicates #31011
