### ISSUE TITLE
[visualforce] Add validation of HTML, CSS, Javascript to Visualforce pages

### ISSUE THREAD

**Issue by bmodeprogrammer** [Microsoft/vscode#33392]
I notice that we don't have JavaScript intelisense on Visualforce pages.
Will be good to have all html features like css, javascript helpers and HTML snippets on visualforce pages without the needing to change the language mode to HTML.

Thank you

**Comment by aeschli** [comment]
Sorry, I'm not familiar with the 'visualforce' pages. Is the file format is identical to HTML, or does it extend the HTML syntax?

Also note that you can change the default file associations in the user settings.

**Comment by bmodeprogrammer** [comment]
It's almost identical, we can use pure HTML, css and JavaScript inside, and the Visualforce own components.

Example of pure Visualforce:
```
<apex:page standardController="Account">
    <apex:form>
        <apex:pageBlock title="Edit Account for {!$User.FirstName}">
            <apex:pageMessages/>
            <apex:pageBlockButtons>
                <apex:commandButton value="Save" action="{!save}"/>
            </apex:pageBlockButtons>
            <apex:pageBlockSection>
                <apex:inputField value="{!account.name}"/>
            </apex:pageBlockSection>
        </apex:pageBlock>
    </apex:form>
</apex:page>
```
Visualforce it's like a Framework made By Salesforce.

**Comment by aeschli** [comment]
This looks like XML.. Assigning the HTML mode to that would not be correct.

The best would be if an extension picks this up and offers specific support for Visualforce.
