### ISSUE TITLE
Permanently assign file type to new extensions

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#334]
there are few extensions which are new like gtpl for go template or tmpl, there is no way currently to permanently assign the syntax, we have to do so each time we open the file

**Comment by jpierson** [comment]
Having this feature may also be a reasonable way to handle cases where some would like JSX syntax to work for files with a plain .JS file extension instead of .JSX. See #81 and #140 for more details.

**Comment by thewhitetulip** [comment]
Yes, this is a common feature in notepad++, really effective when you have a new language and want to add the extension

**Comment by bpasero** [comment]
The solution might end up to be integrated full editorconfig support in VS Code.

**Comment by matthewp** [comment]
I think the simple solution is best, just remember when a user selects a language for a particular file type.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3612 for March
