### ISSUE TITLE
Code should validate relative path in workspace file and behave more gracefully

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33404]
Testing: #33278 

- create a workspace file with only relative paths
- copy the file using OS means (file explorer) where the folder don't make any sense
- open the file

Observe:

- you see the folder structure also not existing on disk
- clicking on a folder shows an error message:

<img width="556" alt="capture" src="https://user-images.githubusercontent.com/1931590/29823761-e3d27aa2-8ccf-11e7-9640-f791c0595015.png">

I would have expected that the folders are rendered gray / disabled and that clicking on them shows me a better error message

**Comment by dbaeumer** [comment]
I would also expect that Remove Folder is available in the context menu

<img width="279" alt="capture" src="https://user-images.githubusercontent.com/1931590/29823903-55b96a40-8cd0-11e7-8d54-bdcef4581e02.png">

**Comment by bpasero** [comment]
This basically is https://github.com/Microsoft/vscode/issues/29738

**Comment by isidorn** [comment]
Dup of #29738
