### ISSUE TITLE
Explorer Tree View section doesn't disappear if EH dies

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33406]
testing #33300 on macOS:

- debug some code and open loaded scripts explorer
- kill EH from outside and restart EH

Observe: 
Loaded Scripts explorer tree disappears but the viewer header stays:

![2017-08-29_15-52-27](https://user-images.githubusercontent.com/1898161/29824525-15c7003a-8cd2-11e7-8748-7f8eb9c259e9.png)

**Comment by sandy081** [comment]
@weinand As discussed, this is expected. Because view is still registered and given the current context view is visible. Data of the view was gone as the extension host died.

**Comment by weinand** [comment]
@alexandrudima what do you think is the correct behaviour in this case?

**Comment by alexandrudima** [comment]
I don't have a strong opinion either way. For example, grammar contributions survive, even if the extension host is dead. But grammar contributions don't need a running extension host...

I think various paths can be taken:
1. Render a placeholder. When the extension host is starting up, it can read "Loading...". When the extension host is crashed, it can read "Not available at this time..." or "Error..." etc.
2. Don't render anything (also not the header)

I agree the path it takes today (where only the header is rendered, and the content is empty) is a bit ... unfriendly.
