### ISSUE TITLE
New Terminal and Kill Terminal do not work as expected with Tmux setup 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33400]
Testing #33274

- Set up tmux as explained in https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

With this set up, New terminal and Kill terminal commands are not working.
After clicking New terminal action, label of the terminal gets lost.

**Comment by Tyriar** [comment]
Maybe I'm doing something wrong but new-session doesn't work for me in Terminal.app or vscode:

<img width="292" alt="screen shot 2017-08-30 at 8 29 44 am" src="https://user-images.githubusercontent.com/2193314/29880756-746db292-8d5d-11e7-956b-3c54653a345c.png">

/cc @joaomoreno

**Comment by joaomoreno** [comment]
That's strange...

```
~ → tmux -V
tmux 2.5
```

Same version?

**Comment by Tyriar** [comment]
I was on 2.4

**Comment by Tyriar** [comment]
I can reproduce, I think what's happening is the terminal is launching and dying immediately as the session is already open? But this particular edge case isn't covered.

@joaomoreno can you repro this? Do you think it was always happening?

**Comment by joaomoreno** [comment]
That was always happening on my setup; it's not a problem.

The only problem I see is what @sandy081 refers to in the end: that the terminal label becomes empty.

**Comment by Tyriar** [comment]
The label is pulled from the process via this function:

https://github.com/Tyriar/node-pty/blob/12caa78c871caa388b013ab9d2e327f2b0a3a76e/src/unix/pty.cc#L507

Which incidentally was pulled in from tmux.

Going to close this out as I don't think this is particularly actionable and can maybe be fixed by tweaking the script?
