### ISSUE TITLE
Git split view not reacting to removal of files in no folder workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33402]
Refs: #33267

1. Have a no folder workspace and open a file belonging to some git repo
2. Notice that repo is nicely shown in the git viewlet
3. Close that file from the no folder workspace and open git viewlet
4. I would expect the git viewlet is empty, instead it shows the git repository I am no longer interested in

**Comment by joaomoreno** [comment]
I'm too afraid to remove git repositories automatically. The only situation this will currently happen in during a folder removal from a workspace.

I want to keep that process manual: #33341
