### ISSUE TITLE
Extension Recommendation: close event not fired

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33409]
Testing: #33298 

- Section Testing Telemetry for the Recommendation Pop up
- item 5: close the pop up

I didn't receive any event.  Verified by setting a break point in TelemetryService#publicLog.

**Comment by dbaeumer** [comment]
Esc does trigger a 'cancel' event.

**Comment by ramya-rao-a** [comment]
Duplicate of #33335
