### ISSUE TITLE
Zen Mode is hard to use on modern wide screen monitors

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#33408]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T07:05:40.998Z)
- OS Version: Windows_NT x64 10.0.15063

Basically, I can't use the Zen Mode on my wide screen 32-inch monitor, since all the code is on the very left side of the screen, while I (and I assume any other sane person working on computer) am usually positioned at the center of the screen, not on the far left.

It would be great if Zen Mode could support some kind of "centered" view, wen the text/code is centered in the middle, not on the very left.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/15684
