### ISSUE TITLE
Pressing enter converts spaces to tabs on current line

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode#33407]
- VSCode Version: 1.15.1
- OS Version: Linux

Steps to Reproduce:

1. ![a](https://user-images.githubusercontent.com/80071/29824776-b09cc194-8cd2-11e7-97ec-aaac5a004c03.png)
2. Press enter
3. ![b](https://user-images.githubusercontent.com/80071/29824779-b29579f0-8cd2-11e7-98dd-c22ee679fde5.png)

That it converts spaces to tabs on the new line (4) is a an old issue, but now it also converts the spaces to a tab on line 3! This is a regression as I don't remember this happening in ≤ 1.14.

Note that this even happens with `editor.autoIndent` set to `false`!

**Comment by rmunn** [comment]
Do you have the EditorConfig extension installed? If so, what happens if you disable EditorConfig? I've seen this happen to me when editing a file in an unfamiliar project, and it turned out to be caused by the `.editorconfig` file at the root of the project, which was specifying tabs for the file type I was editing.

If it is caused by EditorConfig, perhaps this bug should be reported on the [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig-vscode).

**Comment by rmunn** [comment]
I also note, given your screenshots, that this would also be solved if #33974 was implemented, as the editor would then do the right thing with tabs (tabs for indentation, spaces for alignment).

**Comment by jhasse** [comment]
> Do you have the EditorConfig extension installed?

No, also happens with all extentions disabled.

I just noticed that it only happens in C++ Language Mode.

> I also note, given your screenshots, that this would also be solved if #33974 was implemented, as the editor would then do the right thing with tabs (tabs for indentation, spaces for alignment).

Yes, tabs for indentation, spaces for alignment has always been hard with VS Code. I got used to that though, but with this issue it **modifies** a line, which I then have to fix manually.

**Comment by jez9999** [comment]
It seems to happen with TypeScript too.  How hard is it for VS Code to just leave indentation alone?

**Comment by alexandrudima** [comment]
@jhasse The first thing is to make sure the editor ended up configured properly w.r.t. what you would prefer: spaces or tabs. This is indicated in the status bar. `Spaces:4` means that pressing a tab will insert 4 spaces, `Tab Size: 4` means that pressing a tab inserts a tab character and the tab character will be rendered with the width of 4 spaces...

This can be controlled via three flags:
* `editor.tabSize`
* `editor.insertSpaces`
* `editor.detectIndentation`

Additionally, there are certain VS Code extensions, such as editor config which will tweak these settings if you use something like `.editorconfig`.

![image](https://user-images.githubusercontent.com/5047891/31931360-43ff6166-b8a3-11e7-82b4-bcb74954f73d.png)


---

Now on the topic of `editor.autoIndent`, assuming the editor is configured to your liking. After 004d0da57a05783797ca2860821d613095b346a8 (pushed for #36090) , i.e. available on the Insiders Release Channel:

#### `editor.autoIndent: false`, editor configured with Spaces:4
![kapture 2017-10-24 at 10 12 04](https://user-images.githubusercontent.com/5047891/31931537-cd341698-b8a3-11e7-9860-be5e0d39b64e.gif)

#### `editor.autoIndent: true`, editor configured with Spaces:4
![kapture 2017-10-24 at 10 13 54](https://user-images.githubusercontent.com/5047891/31931617-0e05920a-b8a4-11e7-8449-0644c8ed4656.gif)

---

I can no longer reproduce this issue on the Insiders Channel, so I think it is fixed. 

@jez9999 Please open a separate issue and double check if it reproduces on the Insiders Channel.

**Comment by jez9999** [comment]
@alexandrudima You don't appear to be trying to repro the error.  You're using space indentation.  We're using tab indentation, and having spaces be converted to tabs.

**Comment by alexandrudima** [comment]
@jez9999 Can you please read the first part of my comment  https://github.com/Microsoft/vscode/issues/33407#issuecomment-338910929 ?

So you are having a file that is all indented with spaces and configure the editor to use tabs for indentation... And then you would expect the editor to not respect the configuration you've set and insert spaces ?

In the following gif, I've got a file that is all indented with spaces and have configured the editor to indent with tabs (see the `Tab Size: 4` in the status par). 

It is expected that, when I press <kbd>Tab</kbd> or <kbd>Enter</kbd> tab characters are inserted and not spaces:

![kapture 2017-10-24 at 11 31 40](https://user-images.githubusercontent.com/5047891/31935361-ebbd0fe2-b8ae-11e7-9132-a2e61cd80c75.gif)

The editor editing operations will respect whatever this file gets configured with. The configuration is shown in the status bar. I don't understand what exactly is the problem you are pointing out. Can you please give precise steps with what you are doing, what you would expect to happen vs what happens.

**Comment by jez9999** [comment]
@alexandrudima What software are you using to do screen captures of VS Code?

**Comment by jhasse** [comment]
> So you are having a file that is all indented with spaces [...]

No, see my first comment.

**Comment by alexandrudima** [comment]
@jhasse So, you have the inverse. The same argument holds.

You have a file that is all indented with tabs and have configured the editor to insert spaces. You can see the editor is configured to insert spaces in the status bar `Spaces: 4`:

When pressing <kbd>Enter</kbd> or <kbd>Tab</kbd>, the editor will insert spaces, just as instructed. It doesn't care what the file contains, it will respect whatever you have configured it to do.

![kapture 2017-10-24 at 12 26 41](https://user-images.githubusercontent.com/5047891/31938040-9b720148-b8b6-11e7-8a00-77ede42141c0.gif)

I'm sorry, but please also see the first part of my comment https://github.com/Microsoft/vscode/issues/33407#issuecomment-338910929

There are two things mixed up in this issue:
1. Somehow, the editor is misconfigured. You would like it to insert spaces, but it inserts tabs. Or you would like it to insert tabs, but it inserts spaces. Just use `editor.tabSize`, `editor.insertSpaces`, `editor.detectIndentation`, uninstall or install editorconfig, or whatever, **you can configure VS Code to indent exactly as you wish, you just need to spend 2 minutes to configure it**.
2. There was an issue when pressing Enter in that scenario, where an extra indent was added; I can no longer reproduce that issue on the latest Insiders Build Release.

Pretty please, figure out problem 1 on your own. It is a configuration issue that is easily tweakable if you change the settings to match whatever you want. Please let me know if you believe problem 2 still exists.

**Comment by jez9999** [comment]
@alexandrudima Could you answer my question?

**Comment by jhasse** [comment]
> [...] and have configured the editor to insert spaces.

No, tabs. Sorry should have mentioned that.

I've just tried Insiders and this is indeed fixed when `editor.autoIndent` is set to `false`. Thanks :)

**Comment by alexandrudima** [comment]
@jez9999 on mac I use Kap. on windows I use LiceCap

**Comment by jez9999** [comment]
@alexandrudima OK I captured the issue.  It's configured to tabs size 4, and when I press enter the alignment spaces are converted to tabs as you can see.
![vs code spaces to tabs](https://user-images.githubusercontent.com/793830/31946723-788db49c-b8ca-11e7-92c0-71bb3d71b0e0.gif)

**Comment by alexandrudima** [comment]
@jez9999 Thank you for the self-explanatory gif. I can reproduce when using `editor.autoIndent: true`, but not when using `editor.autoIndent: false`.

#### `editor.autoIndent: false`
![kapture 2017-10-24 at 18 02 38](https://user-images.githubusercontent.com/5047891/31954315-90edf806-b8e5-11e7-8ee6-c56955f66ef7.gif)

#### `editor.autoIndent: true`
![kapture 2017-10-24 at 18 03 47](https://user-images.githubusercontent.com/5047891/31954382-b7b035bc-b8e5-11e7-931d-691f52cf7b74.gif)

**Comment by jez9999** [comment]
@alexandrudima Maybe it has been fixed *very* recently then?  I have `editor.autoIndent: false` and it still happens.

**Comment by alexandrudima** [comment]
@jez9999 

Please read again my initial comment https://github.com/Microsoft/vscode/issues/33407#issuecomment-338910929 , this time the second part.

![image](https://user-images.githubusercontent.com/5047891/31955824-d9ad5cf4-b8e9-11e7-9302-78ac1bca283c.png)

In other words, the part about `editor.autoIndent: false` is working as expected on the Insiders Channel and will make its way to the 1.18 release.

**Comment by jez9999** [comment]
@alexandrudima How does that address my point about the indentation being changed on the new line?  Even in your example image, it is being changed.

**Comment by alexandrudima** [comment]
@jez9999 Download VS Code Insiders from here https://code.visualstudio.com/insiders

Then set `editor.autoIndent: false` and run your steps. The current line will not be touched.

Then set `editor.autoIndent: true` and run your steps. The current line will be touched. This is the reason why I reopened the issue.

**Comment by ChrisTucker2000** [comment]
I have this issue too, in VS Code 1.21.0. What seems to be missing is a "smart tabs" kind of mode. Tabs should be used for indentation, and spaces should be used for alignment.

**Comment by ergcode** [comment]
![_2018_04_01_23_56_29_318](https://user-images.githubusercontent.com/23062770/38177352-a342a0ec-3608-11e8-9767-e7c2ec19f2a9.gif)

**Comment by tumut** [comment]
@alexandrudima `editor.autoIndent: false` only solves the issue partially. The problem that hasn't been addressed is the following:

If I press `Enter` in this case,

![image](https://user-images.githubusercontent.com/3442220/41305782-fd3d9c7a-6e41-11e8-997d-b82a4e5f74fc.png)

I expect this:

![image](https://user-images.githubusercontent.com/3442220/41305815-19f38212-6e42-11e8-9528-3915d95cc127.png)

But what actually happens is this:

![image](https://user-images.githubusercontent.com/3442220/41305795-06642102-6e42-11e8-9d70-a429327537ce.png)

Notice how 4 spaces from the alignment were converted into a tab literal.

**Comment by j-zeppenfeld** [comment]
Since there seems to be no interest nor understanding from the VS Code team for supporting tabs for indentation and spaces for alignment (as seen by the responses or lack thereof to this and related issues), I ended up writing an extension to achieve this:

[Tab-Indent Space-Align](https://marketplace.visualstudio.com/items?itemName=j-zeppenfeld.tab-indent-space-align)

I've used it a fair bit before publishing it and it has worked great for me, but I am sure that there are some corner cases that I overlooked. Feedback is very welcome!

**Comment by BrettMoan** [comment]
@alexandrudima

Are there any plans for vscode to fully replicate the "existing" whitespace characters when adding a newline and editor.autoIndent: false ?

The gifs on your October 24th 2017 comment show plainly the issue we are referring to on the auto-indent: false. Namely that line 7 has 2 levels of indentation + 12 spaces of alignment. However when you press enter the next line is created with 5 levels of indentation. 

I don't know if it is related but a similar issue will appear when you use the "out dent" command. Instead of the expected behavior (one level of indentation removed) all the alignment characters get converted to the indentation characters and then one level of indentation is removed.

**Comment by rebornix** [comment]
> Are there any plans for vscode to fully replicate the "existing" whitespace characters when adding a newline and editor.autoIndent: false ?

We don't have plan for this in the near term. This issue was reopened as 

> Then set editor.autoIndent: true and run your steps. The current line will be touched. This is the reason why I reopened the issue.

but it's how `editor.autoIndent` is designed, it will use indentation rules to adjust the indentation of current and next line when users type or press enter. If it doesn't work as you expect, you can change it to `"editor.autoIndent": "advanced"`.

**Comment by j-zeppenfeld** [comment]
@rebornix There most certainly is a bug here: VSCode counts those spaces as indentation, but they are alignment.

Ideally when pressing enter both the indentation and leading alignment would be copied to the new line. However, converting the alignment to indentation is plainly wrong!

**Comment by j-zeppenfeld** [comment]
@rebornix Please reopen this issue and keep it open until it has been resolved.

**Comment by rmunn** [comment]
If this bug has the `under-discussion` tag, why was it closed? Surely something that's under discussion should stay open until the discussion has reached a conclusion? It makes no sense to me why @rebornix would tag this as "under discussion" and then close the bug. Please reopen.
