### ISSUE TITLE
Find references with code lens enabled makes the peek view's editor jump

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33417]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T06:58:13.897Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#33299 

Might not be related to smooth scrolling (I don't normally have code lens on). Maybe code lens should always be disabled in the peek view?

![find-refs](https://user-images.githubusercontent.com/2193314/29831310-87f2388e-8c99-11e7-88ae-d1cf16a808b1.gif)

**Comment by alexandrudima** [comment]
Fixed via e070afceabc88e57190697c9a79dc3ab3a98d3d5 and 8ce745843c581cff6d69ea68b2d9730ce76633f4
