### ISSUE TITLE
Ability to search in open files only

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#33411]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T07:05:40.998Z)
- OS Version: Windows_NT x64 10.0.15063

It would be quite helpful to (optionally) limit the search to the open files only, even when a project/folder is open.

For example, I am working on some feature, adding TODOs here and there, and all files that I edited are naturally open. I'd like to search for all TODOs, but not in the entire project (there are thousands of TODOs in the big project), I'd like to limit the searches only to the currently opened files.

Currently, the UI in the Search tab provides a couple of buttons in "files to ignore" field ("Use Ignore Files" and "Use exclude settings").

I'd like to see a button in the "files to include" field, with similar styles as the two buttons above and named "Use Opened Files" or something like that.

Naturally, both ways should be possible, searching the entire project and searching only in the open files.

**Comment by roblourens** [comment]
👍 Tracking this request in #20530
