### ISSUE TITLE
Smooth scrolling animates scroll even when jumping to another file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33415]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T06:58:13.897Z)
- OS Version: Linux x64 4.10.0-32-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#33299 

1. Open this line: https://github.com/Microsoft/vscode/blob/30b47ba11c3a206773953909bbf2291670c8cbd6/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L311
2. Ctrl+click setTimeout
3. Ctrl+end to move the cursor to the bottom of lib.d.ts
4. Ctrl+tab to switch back to terminalInstance.ts
5. Ctrl+click setTimeout

Observe that the expensive scroll on lib.d.ts still animates even though the user has already lost context on the lib.d.ts file.

**Comment by alexandrudima** [comment]
I think this got fixed by one of the other changes I did here...
