### ISSUE TITLE
Documentation for the JSON scheme of  extension authoring configuration

### ISSUE THREAD

**Issue by wayou** [Microsoft/vscode#33418]
I wonder if there's an official documentation for the JSON scheme, witch is used in the [contributes.configuration](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration) within the package.json of an extension.

like the following usage:
```json
"myExtension.foo": {
                    "type": "array",
                    "description": "desc goes here...",
                    "items": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "text": {
                                        "type": "string",
                                        "description": "desc"
                                    },
                                    "color": {
                                        "type": "string",
                                        "description": "desc"
                                    }
                                }
                            }
                        ]
                    }
                },
```
This shows how to config the `foo` property, witch is type array, to accept both `number` and string as items.
I can't find any guides on this, but I know this works.

And if I want a property, witch is not array, to accept more than one data type, what would I do?

**Comment by sandy081** [comment]
@aeschli Could you suggest?

**Comment by aeschli** [comment]
@sandy081 What do you mean? We already offer suggestions for the JSON schema.

I will add a sentence here: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration
Basically, each configuration setting need to define a default value and can add validation for the value using [JSON schemas](http://json-schema.org/).

**Comment by sandy081** [comment]
Moved to vscode-docs repo - https://github.com/Microsoft/vscode-docs/issues/1287
