### ISSUE TITLE
app.use(function *() {}) can not be saved successfully

### ISSUE THREAD

**Issue by lisanlai** [Microsoft/vscode#33410]
For example, i want to write the below simple code:
`app.use(function *() {
    this.body = 'hello world';
});
`

But after saving file, the code became to:
`app.use(function*() {
    this.body = 'hello world';
});
`
In fact, there is a space between the word 'function' and '*'.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
python|don|0.7.0
code-runner|for|0.7.1
terminal|for|0.0.10
shell-format|fox|1.0.0
rest-client|hum|0.15.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.63
prettify-json|moh|0.0.3
PowerShell|ms-|1.4.1
java|red|0.8.0
partial-diff|ryu|0.3.1
bash-beautify|sha|0.1.1
json2yaml|tux|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Our default formatting is

```js
app.use(function* () { this.body = 'hello world'; }); 
```

Note that the `*` has been shifted next to the `function` keyword. We are tracking more formatting options for the `*` here: 
https://github.com/Microsoft/TypeScript/issues/9001

I suspect that an extension like `vscode-JS-CSS-HTML-formatter` could be deleting the space all together. Can you please try disabling and see if you end up with the above formatting

**Comment by lisanlai** [comment]
You guessed!
Caused by JS-CSS-HTML Formatter
