### ISSUE TITLE
Mime Extension Install: Reload Window Re-installs Extension

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33423]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
---

Steps to Reproduce:

1. Open VS Code via a web link to install an extension
2. You are prompted to install
3. Extension is installed
4. Reload the window to activate
5. You will be prompted to install the same extension again
6. Assuming you opened VS Code for the first time this way every window reload will prompt for install until you close and restart VS Code

Expected - once installed you are not prompted to install again.

**Comment by joaomoreno** [comment]
#33030
