### ISSUE TITLE
`parse_block_html` for Markdown in VS Code?

### ISSUE THREAD

**Issue by janpio** [Microsoft/vscode#33425]
Is there something similar to `kramdown`s `parse_block_html: true` [1] in Visual Studio Code?

Right now something like this:
```
<div class="message">
Caution: This might at times cause problems with `foo` commands ...
</div>
```
is not parsed as markdown both in the editor and preview.

[1] https://kramdown.gettalong.org/parser/kramdown.html#option-parse-block-html

**Comment by mjbvz** [comment]
VSCode's built-in markdown extension uses markdown-it. To my knowledge markdown-it does not have an equivalent setting to kramdown's, but an extension may be able to contribute a markdown-it plugin that adds this: https://code.visualstudio.com/docs/extensionAPI/api-markdown#_adding-support-for-new-syntax-with-markdownit-plugins

Closing as extension candidate
