### ISSUE TITLE
Mime Extension Install: Prompts event when already installed

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33421]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
---

Steps to Reproduce:

1. Click on a web link to install an already installed extension
2. You will be prompted to install the extension again

Expected - we check if the extension is already installed and display the extension details page vs the 'install extension' notification.

**Comment by joaomoreno** [comment]
This should be already fixed in stable since 900762c
