### ISSUE TITLE
Unable to launch VS Code from terminal in Windows 10

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode#33420]
I'm trying to follow the js guide from [here](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial), where it says:
> Tip: You can open files or folders directly from the command line. The period '.' refers to the current folder, therefore VS Code will start and open the Hello folder. 

This produces this error however: 
![uten navn](https://user-images.githubusercontent.com/9251274/29831829-a12580ca-8ce6-11e7-95e4-2dd8114ca348.png)

- VSCode Version:1.15.1
- OS Version: Windows 10 15063

Steps to Reproduce:
```
cd
mkdir hello
code .
```

Reproduces without extensions: Yes

Any ideas how I can troubleshoot this?

**Comment by joaomoreno** [comment]
What are the contents of your `%PATH%` variable?

**Comment by erihanse** [comment]
It's the 64-bit version, installed from here: https://code.visualstudio.com/updates/v1_15#_windows-64-bit. Filename: VSCodeSetup-x64-1.15.1.exe

Path:
> C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\eriha\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\;C:\Program Files\Git\cmd;C:\Go\bin;SYSTEM\go\bin;\Users\eriha\go\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\eriha\Anaconda3;C:\Users\eriha\Anaconda3\Scripts;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Vertica Systems\VSQL64;C:\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft VS Code;C:\Users\eriha\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\R\R-3.4.1\bin;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3;C:\Program Files\nodejs\;C:\Users\eriha\AppData\Local\Microsoft\WindowsApps;C:\Users\eriha\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\texlive\2016\bin\win32;C:\Program Files\Inkscape;C:\Program Files\Microsoft VS Code\bin;C:\Users\eriha\AppData\Roaming\npm

**Comment by joaomoreno** [comment]
Can you remove `C:\Program Files (x86)\Microsoft VS Code` from your path and just leave `C:\Program Files\Microsoft VS Code\bin`?

**Comment by erihanse** [comment]
That seem to do the trick. Thanks!
