### ISSUE TITLE
Improve the behaviour when opening an invalid workspace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33437]
Testing #33278

**Steps to Reproduce:**

1. For the code-workspace:

```json
{
	"folders": [
		{
			"path": "folder2"
		},
	],
	"settings": { }
}
```

(note the extra `,` in `folders`)

2. Try opening the workspace in VSCode

**Expected**
We display some sort of error about having an invalid workspace and open the `code-workspace` as a json file. 

**Actual**
No error is displayed. We open the  code-workspace` as a json file. No error is displayed in the file either:

![screen shot 2017-08-29 at 11 28 37 am](https://user-images.githubusercontent.com/12821956/29837650-9783e644-8cad-11e7-8f23-93a51f393958.png)

**Comment by bpasero** [comment]
I have extracted https://github.com/Microsoft/vscode/issues/33502 to change our parsing of workspaces to allow for simple errors like these. 

I still think if the workspace file really cannot be parsed, we should:
* open the workspace empty
* open the workspace file
* inform the user that the workspace file is invalid
