### ISSUE TITLE
No: "This setting must be a user setting" errors shown for code-workspace settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33439]
Testing #33278

For the `code-workspace`:

```json
{
	"folders": [
		{
			"path": "folder2"
		}
	],
	"settings": {
		"git.path": "hello"		
	}
}
```

`git.path` should be marked as only being supported in the user settings, similar to what we show if you try to set in on a folder:

![screen shot 2017-08-29 at 11 44 03 am](https://user-images.githubusercontent.com/12821956/29838200-6077c5b0-8caf-11e7-8d16-8807255f2d2a.png)

Currently no error is shown:

![screen shot 2017-08-29 at 11 43 32 am](https://user-images.githubusercontent.com/12821956/29838215-6a310da0-8caf-11e7-875c-685234637399.png)

**Comment by sandy081** [comment]
There is no classification of User/Workspace settings. We have `Window` and `Resource` settings. `Window` settings can be applied to complete workbench/window and can be configured in User / Workspace settings where are `Resource` settings can be applied only for resources and can be configured in User / Workspace / Folder settings.

Any setting can be customised from User / Workspace. This is the design decision and there are some advantages and disadvantages to it. From bright side, it will allow user to customise different gits for different workspaces.

**Comment by mjbvz** [comment]
Sorry, I think I posted the wrong screenshot of the expected error. Here's what I mean:

<img width="311" alt="screen shot 2017-08-30 at 12 16 18 am" src="https://user-images.githubusercontent.com/12821956/29859786-961bd6fc-8d18-11e7-9f1c-d5e82af6740f.png">

Settings for executables like `git.path` are only supported as user settings because they set the `isExecutable` flag in their settings contributions. In my testing, we don't show the green squiggles when you try to put one of these `isExecutable` settings into the `code-workspace` settings

**Comment by sandy081** [comment]
Ah I see.. right we have settings (exceptions) which are paths to executables and can only be user settings.

**Comment by ramya-rao-a** [comment]
Verified the fix for Workspace Settings in multi root mode.

But, in folder settings, in multi root mode, both messages are shown. The `This setting cannot be applied now...` doesn't apply

![settings](https://user-images.githubusercontent.com/16890566/32343442-afbede44-bfc0-11e7-8898-172bf5e1bf30.gif)

**Comment by sandy081** [comment]
It makes sense as both messages are applicable.
