### ISSUE TITLE
Icon: Context menu and Jump list missing edge

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33436]
Windows
Testing #33272 

The context menus don;t have the edge on the icon:

![image](https://user-images.githubusercontent.com/1051190/29837307-9d220dd4-8cac-11e7-919b-967b351f52f1.png)

The same it true for the jump lists:
![image](https://user-images.githubusercontent.com/1051190/29837349-bdd4a42e-8cac-11e7-93d7-646f24d1ff89.png)

Even when small I htink it looks OK.
![image](https://user-images.githubusercontent.com/1051190/29837322-a805a59e-8cac-11e7-9699-6842c36dc6cb.png)

**Comment by chrisdias** [comment]
"by design", at this size we use the icon w/out the box.
