### ISSUE TITLE
Insiders icon missing edge in installer.

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33435]
Windows
Testing #33272 

The icon in the top of the installer is different that Code itself:
![image](https://user-images.githubusercontent.com/1051190/29837167-4be02e4c-8cac-11e7-96fb-c6b66132fb71.png)

![image](https://user-images.githubusercontent.com/1051190/29837179-53d3b42a-8cac-11e7-91b6-5c61d0a68e92.png)

Really just in this case a consistency issue.

**Comment by chrisdias** [comment]
"by design" at this size we dont use the box.
