### ISSUE TITLE
Icon in Add/Remove programs

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33433]
Testing #33272 

Add remove programs is a little ugly:
![image](https://user-images.githubusercontent.com/1051190/29836636-a5d3229e-8caa-11e7-84ed-c105665014b6.png)

It's probably by design - but you can define a background color e.g. white it looks like.

Sean

**Comment by chrisdias** [comment]
"by design"

**Comment by weinand** [comment]
no, "by lack of design"

**Comment by bpasero** [comment]
@chrisdias @weinand this is not "by design", we should pick the same background color as VS does. We are simply getting the blue default from windows it seems. Duplicate of https://github.com/Microsoft/vscode/issues/33362

**Comment by weinand** [comment]
A good designed icon would not use so many transparent areas that makes it dependent on background colours that are out of our control.

If I would configure my Windows to use an orange background colour, the VS Code icon would vanish completely...
