### ISSUE TITLE
ConfigurationTarget constants in extension host do not match values in core

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33430]
Those in the extension host start at 1, those in the core start at 0.

**Comment by sandy081** [comment]
@chrmarti Not sure why it is a bug and important. Would like to know if there is an issue with API?

Also, I do not think it is mandatory to have the internal and api properties to be in sync. It is a problem if the transformation is not happening 

I preferred to start from `1` in API as using `0` could lead to conflicts with `undefined` or `null`.

**Comment by chrmarti** [comment]
@sandy081 My bad, I saw Global write to Workspace (or WorkspaceFolder). Duplicate of #33440.
