### ISSUE TITLE
Icon in small taskbar

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33434]
Windows
Testing #33272 

@chrisdias pointed this out with a small taskbar the insiders and stable will look the same.
![image](https://user-images.githubusercontent.com/1051190/29836827-3a401590-8cab-11e7-822a-6a2dc2b5c7ab.png)

I beleive @chrisdias has asked the UX team and the suggestion was that this was a non-issue users should pin ad have them not besirde each other.  Which does not sound ideal.

@chrisdias any update there?

**Comment by chrisdias** [comment]
original issue is "by design", as at this size we dont use the box.

@skl131313 yes, stable will be updated shortly.
