### ISSUE TITLE
Go to symbol in workspace seems to not be working:

### ISSUE THREAD

**Issue by rkpatel33** [Microsoft/vscode#33432]
Search symbol in project does not see to work on an exported module function. If I do symbol search in file, it works fine.

In some cases, it only finds some of symbols, in others, it finds none.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.3
html-css-class-completion|Zig|1.9.0
project-manager|ale|0.20.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-dash|dee|1.7.0
githistory|don|0.2.3
python|don|0.7.0
macros|ged|1.2.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.2.0
vscode-fileutils|sle|2.6.2

---

Steps to Reproduce:

1. Copy pasting actual symbol name into the search area per screenshot below.
2. Also try a search for a very common `settings` import.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/3799489/29835198-19c575f8-8ca6-11e7-803a-29e62249c938.png)

![image](https://user-images.githubusercontent.com/3799489/29835230-354a2382-8ca6-11e7-9bb8-a5cd47060fda.png)

**Comment by rkpatel33** [comment]
I also notice that, with the Sublime shortcuts extension, I get two different GUI views even though the following shortcuts are linked to the same command in the shortcuts:

![image](https://user-images.githubusercontent.com/3799489/29835705-a8a612b8-8ca7-11e7-9da7-58492bcf422f.png)

![image](https://user-images.githubusercontent.com/3799489/29835718-af393c9a-8ca7-11e7-9c4e-65ba547c0c25.png)

![image](https://user-images.githubusercontent.com/3799489/29835725-b4ade5e0-8ca7-11e7-87ef-7f24e60f62ec.png)

**Comment by mjbvz** [comment]
Does your workspace have one or more `jsconfig` or `tsconfig` files?

For the sublime extension shortcut problem, can you please file that issue against that extension: https://github.com/Microsoft/vscode-sublime-keybindings/issues/new

**Comment by rkpatel33** [comment]
I have neither a `jsconfig` or `tsconfig` file in my workspace.

**Comment by mjbvz** [comment]
Try creating a [jsconfig](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your workspace with the contents:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VSCode to treat all JS files in the workspace as part of a single project
