### ISSUE TITLE
Confusing Hover/warning in settings (multi root)

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33438]
Windows
Testing #33277 

1. make a new folder `mkdir workit`
2. Add a folder setting to hide status bar (status bar hides as expected)
3. save as a work-space `work1`
4. Settings editor has a warning - but the status bar is still hidden
5. reload window has no additional impact

![image](https://user-images.githubusercontent.com/1051190/29837644-9027629a-8cad-11e7-8529-018d985369ed.png)

Expected - no warning as the setting did work.  Or at least better warning text to explain that it is being overridden by the Workspace setting.

**Comment by sandy081** [comment]
@seanmcbreen As explained in the test plan item, we migrate workbench settings from folder settings to workspace settings for smoother transition from folder workspace to multi root workspace. 

In your case, setting `"workbench.statusbar.visible": false` is migrated to Workspace settings. Hence the status bar is not shown and the transition is smooth.

File you see in the above screen shot is `Folder settings`. There is a bug that the label shows as `Workspace Settings` - #33485. I think that might have confused you.
