### ISSUE TITLE
Debug console always comes up when attaching to target

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3344]
Testing #3238

When attaching to a process, we surely get no debug output at all from it. Yet, the debug console still always pops up. It's very distracting.

Especially when using the `restart: true` option:

![bug](https://cloud.githubusercontent.com/assets/22350/13257368/c4ba3356-da4e-11e5-81a1-4f982e65ec48.gif)

ping @weinand

**Comment by weinand** [comment]
@isidorn a session **restart** should not open the debug console

**Comment by joaomoreno** [comment]
Console still comes up on debug start, but no more on restart.

**Comment by weinand** [comment]
@isidorn we could consider to not reveal the debug console on 'attach' (but then your code would have to know the semantics of 'attach'...)
