### ISSUE TITLE
Light bulb is not displayed during selection

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33441]
Windows 
Testing #33282 

Did not consistently see light bulb (needed to use `ctrl + .`) which is not that discover-able.

Ideas
- add a right click context menu
- find a way for the light bulb to be more visible

**Comment by mjbvz** [comment]
I believe this was addressed by @jrieken's change 785c76451f76673df67bd7b6c59586145e5a1b18 for issue #33241 

@seanmcbreen Can you quickly test today's insiders build and let me know if you agree

**Comment by jrieken** [comment]
Yeah, I have fixed that today. When a selection encloses an error/warning I will check for code actions on that marker, otherwise for the whole selection
