### ISSUE TITLE
"Go to File..." shows files in search.exclude

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#33444]
"Go to File..." is essentially a search operation and should be be managed by `search.exclude`, or optionally an additional config, e.g. `goto.exclude`. Typical use-case is having Explorer reflect true contents of project (e.g. not hiding generated files), while other operations are for navigating files one will edit.

- VSCode Version: @latest
- OS Version: OS X

Steps to Reproduce:

1. Include `node_modules` in `search.exclude`, but not in `files.exclude` in settings
1. cmd + p
2. See excluded files appearing in results

![](http://i.imgur.com/VXf6lR1.png)

**Comment by roblourens** [comment]
It is supposed to respect `search.exclude` but there seems to be a problem with having `**/node_modules": false` in `files.exclude`...
