### ISSUE TITLE
Extracted method not formatted

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33443]
Windows
Testing #33282 

Extracted method was not formatted upon extraction.  This is true for both global and inline scopes.

**Comment by mjbvz** [comment]
Upstream issue: https://github.com/Microsoft/TypeScript/issues/18091

**Comment by mjbvz** [comment]
Ok, I've been investigating a workaround on our side too but have not been able to come up with a satisfactory one that does not introduce other weird edge cases.

Closing this as upstream. The workaround for anyone hitting this is to upgrade their workspace typescript versions
