### ISSUE TITLE
Jump to extracted method

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33442]
Windows
Testing #33282 

On extraction to global scope expected to jump to extracted method (in global scope) but did not.  So it was hard to know what happened.  The gutter indicator did help.

**Comment by mjbvz** [comment]
I think that jumping to the extracted method could also be confusing, perhaps even more so. Usually in the extract method workflow, you want to continue working in the current function after the extraction, not inside the method

Let me know if you have any other thoughts on how we could make it more clear to users that the method has been successfully extracted
