### ISSUE TITLE
Java syntax highlighter

### ISSUE THREAD

**Issue by amaneureka** [Microsoft/vscode#33445]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open new document and select java language
2. Code ```String test = new abc() + "ap";``` Any string block after new keyboard causes syntax highlighter to break

Reproduces without extensions: Yes

Note: I would like to take up this issue and contribute to the project, shall I?

**Comment by mjbvz** [comment]
Our java syntax highlighting comes from [language/java](https://github.com/atom/language-java). This may need to be fixed upstream

**Comment by aeschli** [comment]
That's what I see in 1.16 insiders, that uses the latest grammar from https://github.com/atom/language-java

![image](https://user-images.githubusercontent.com/6461412/29866593-211e685e-8d79-11e7-8ad3-f994d289ad3c.png)

IMO this looks fine. If you disagree, please reopen.

**Comment by amaneureka** [comment]
This in 1.15 release
![image](https://user-images.githubusercontent.com/10295295/29908075-095f83dc-8e3d-11e7-9e35-2ec5acb2878a.png)

It looks like issue has been already fix in the 1.16 insider.
