### ISSUE TITLE
Proxy error on macOS Sierra

### ISSUE THREAD

**Issue by yurinativo** [Microsoft/vscode#33446]
Visual Studio Code show proxy error all the time.
I opened the Developer Tools to track the error (Help\Toggle Developer Tools)
All this tries I did with many different kind of proxy settings.

I have tried this different proxy address formats:
1.  No proxy configuration
2. "http.proxy": "http://ProxyIP:port"
3. "http.proxy": "https://ProxyIP:port"
4. "http.proxy": "http://user:password@ProxyIP:port"
5. "http.proxy": "https://user:password@ProxyIP:port"
6. "http.proxy": "http://domain\\user:password@ProxyIP:port"
7. "http.proxy": "https://domain\user:password@ProxyIP:port"
8. "http.proxy": "http://user@domain:password@ProxyIP:port"
9. "http.proxy": "https://user@domain:password@ProxyIP:port"

I tried with and without proxyAuthorization: "http.proxyAuthorization": "Basic" 
I tried with and without proxyStrictSSL: "http.proxyStrictSSL": false

All browsers are working: Safari, Chrome and Firefox
All terminal commands are working with http_proxy and https_proxy environment variables: curl, pod, gem, git, svn, etc...

- VSCode Version: Versão 1.15.1 (1.15.1)
- OS Version: macOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1 - When click "Code\Check for updates..." Show the error: 
Houve um problema de comunicação com o servidor de proxy da web seguro (HTTPS). Verifique seus ajustes de proxy. Para obter ajuda com este problema, entre em contato com o administrador do seu sistema. 

2 - When click "View\Extensions" IT LIST A LOT OF EXTENSIONS, but don't download the Icons showing this errors:
GET https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdia…for-chrome/3.2.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TUNNEL_CONNECTION_FAILED
GET https://davidanson.gallerycdn.vsassets.io/extensions/davidanson/vscode-markdownlint/0.10.0/1500614993551/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TUNNEL_CONNECTION_FAILED
GET https://davidanson.gallery.vsassets.io/_apis/public/gallery/publisher/David…kdownlint/0.10.0/assetbyname/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TUNNEL_CONNECTION_FAILED

3 - If I select the "markdownlint 0.10.0" and click "Install", I got the error:
An unknown error occurred. Please consult the log for more details.

Reproduces without extensions: Yes

Using the proxy-tests, I tried many different kind of proxy formats with 2 different responses 

1 -
- http://ProxyIP:port or https://ProxyIP:port
- http://user:password@ProxyIP:port or https://user:password@ProxyIP:port
- http://user@domain:password@ProxyIP:port or https://user@domain:password@ProxyIP:port
| Test | Status | Hash or Error |
|---|---|---|
| HTTP XHR | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTPS XHR | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTP Node | 0 | Timeout |
| HTTPS Node | 0 | Timeout |
| HTTP Node (not strict) | 0 | Timeout |
| HTTPS Node (not strict) | 0 | Timeout |
| HTTP Node Agent | 302 | 19ab467486888159ef06a5fabb89cf69825dda72 |
| HTTPS Node Agent | 301 | d5434ab83b609d9fe25244d1f2282b0b74a4f2b8 |
| HTTP Node Agent (not strict) | 302 | 19ab467486888159ef06a5fabb89cf69825dda72 |
| HTTPS Node Agent (not strict) | 301 | d5434ab83b609d9fe25244d1f2282b0b74a4f2b8 |
| HTTP Electron | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTPS Electron | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |

2 -
- No proxy settings
- http://domain\\user:password@ProxyIP:port or https://domain\\user:password@ProxyIP:port
| Test | Status | Hash or Error |
|---|---|---|
| HTTP XHR | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTPS XHR | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTP Node | 0 | Timeout |
| HTTPS Node | 0 | Timeout |
| HTTP Node (not strict) | 0 | Timeout |
| HTTPS Node (not strict) | 0 | Timeout |
| HTTP Node Agent | 0 | Timeout |
| HTTPS Node Agent | 0 | Timeout |
| HTTP Node Agent (not strict) | 0 | Timeout |
| HTTPS Node Agent (not strict) | 0 | Timeout |
| HTTP Electron | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |
| HTTPS Electron | 200 | 059911552e14ec17a6fa5cdd0bbf34c4c329b483 |

![image](https://user-images.githubusercontent.com/5964246/29840448-6f166a3a-8cd8-11e7-9e70-955a00baf045.png)
![image](https://user-images.githubusercontent.com/5964246/29840455-7527da08-8cd8-11e7-876a-993581bc284b.png)
![captura de tela 2017-08-29 as 16 39 47](https://user-images.githubusercontent.com/5964246/29840823-acbd4790-8cd9-11e7-948f-3c2a9084b43c.png)
![captura de tela 2017-08-29 as 16 39 54](https://user-images.githubusercontent.com/5964246/29840822-acbc970a-8cd9-11e7-8226-07b9c7aaa9d3.png)
![captura de tela 2017-08-29 as 16 48 21](https://user-images.githubusercontent.com/5964246/29840977-2ef5228c-8cda-11e7-833b-a256cdf6e17e.png)

**Comment by joaomoreno** [comment]
Check our networking docs: https://code.visualstudio.com/docs/setup/network . You'll see that `http.proxy` and similar settings are now deprecated.

It's interesting how it does show many extensions but fails to download any of them. So, some communication is indeed working.

Does it work if you close Code and start it with `code --ignore-certificate-errors`?

**Comment by yurinativo** [comment]
Hi, thanks for your response.
I suspected that the problem should be the proxy because the error description, like the proxy was not set. I could not find any detail about the error.

Trying this setting, not happens:
![captura de tela 2017-08-30 as 07 55 56](https://user-images.githubusercontent.com/5964246/29869275-b7dfa5f8-8d58-11e7-83a3-d185dc58b2fd.png)

I'm sure the problem is with my company proxy, probably some address are blocked.
vscode-update.azurewebsites.net - Blocked
vscode.blob.core.windows.net
marketplace.visualstudio.com - Access but no Images
rink.hockeyapp.net  - Blocked

You can close this issue, sorry about the inconvenience.

**Comment by joaomoreno** [comment]
This one is missing from the list: `*.gallerycdn.vsassets.io`. I've added it to our docs.

You have to convince your system admin to open up those domains in order to get it to work.
