### ISSUE TITLE
git.ignoreLegacyWarning written to workspace settings instead of user settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33440]
Testing #33278

**Steps to Reproduce:**
On a machine with an old version of git:

1. Open a `code-workspace`
2. Observe git 2.0 upgrade warning
3. Click `Dont show again`

**Expected**
`"git.ignoreLegacyWarning": true` is written to user settings

**Actual**
`"git.ignoreLegacyWarning": true` is written to the workspace settings:

```json
{
	"folders": [
		{
			"path": "folder2"
		}
	],
	"settings": {
		"git.ignoreLegacyWarning": true
	}
}
```

**Comment by joaomoreno** [comment]
Good catch.

**Comment by joaomoreno** [comment]
@sandy081 I seem to be doing the right thing here:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/main.ts#L94

**Comment by sandy081** [comment]
Good catch.

Yeah its a bug from side. Classic bug: Having a check on an Enum starting with `0`.
