### ISSUE TITLE
Select all (cmd-a) shortcut doesn't work on Save As dialog (the file name field)

### ISSUE THREAD

**Issue by Bathlamos** [Microsoft/vscode#33448]
- VSCode Version: 1.15.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open VS Code
2. Create a new file somewhere
3. Hit cmd-s to save
4. Pick a different folder than the default one, just so that the "Save as" field gets deselected
5. Click the "Save as" field, and try to hit ctrl-a to select all the text

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
