### ISSUE TITLE
No timeout error when timing out due to restart: true

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3345]
Testing #3238

While successfully debugging using `restart: true` and nodemon, I created a syntax error and waited. The debugger eventually stopped attempting to connect after 10 seconds. There was no UI error indicating what happened. The console did have errors though.

![image](https://cloud.githubusercontent.com/assets/22350/13257530/79e4a090-da4f-11e5-8bcf-d1b333fffcc6.png)

Note that the error does appear on an initial failed attach attempt:

![image](https://cloud.githubusercontent.com/assets/22350/13257583/c440f184-da4f-11e5-8b5e-d4cc4ee997bd.png)

**Comment by weinand** [comment]
@isidorn I've debugged this and it seems that errors returned from 'attach' are only shown in the UI if it is the first 'attach' and not a restarted 'attach'. I tried to find a filter in your code that prevents these error from being shown, but I wasn't successful. Do you have an idea why these errors are not showing up.
