### ISSUE TITLE
Markdown with foot notes does not appears on default markdown previewer

### ISSUE THREAD

**Issue by ezequias** [Microsoft/vscode#33450]
- VSCode Version: 1.15.1
- OS Version: Win 10

Steps to Reproduce:

1.Create a markdown text with foot notes like:
The quick brown fox[^1] jumped over the lazy dog [^2].

[^1]: Foxes are red;

[^2]: Dogs are usually not red

2. Activate the the VS Code "Preview to the side";

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Footnotes are not part of the [common mark spec](http://commonmark.org) that out builtin markdown preview targets.

However we do allow extensions to add support for new syntax to the markdown preview and I've published an extension that adds this: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes
