### ISSUE TITLE
DebugConfigProvider suggestions not available in "Select Environment"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33458]
Testing #33248

- Set up a debug config provider, like in https://github.com/Microsoft/vscode/issues/33367, with

```json
"debuggers": [
    {
        "type": "isidor",
        "label": "hello isidor",
        "languages": [
            "java"
        ]
    }
]
```

and 
```ts
vscode.debug.registerDebugConfigurationProvider('isidor', {
        provideDebugConfigurations: (folder: vscode.WorkspaceFolder | undefined, token) => {
            return [{
                type: 'isidor',
                request: 'launch',
                name: 'hi',
                hello: 'tasty',
                path: folder.uri.fsPath
            }];
        }
    });
```

- Open a folder with no launch.json
- Configure the launch.json
- See "Select environment" prompt

![image](https://user-images.githubusercontent.com/323878/29844507-61e35a80-8cc4-11e7-99eb-7b146d7cfb65.png)

- "isidor" is not an option. Why not? I assume it's only showing adapters that set `initialConfigurations` but it seems like it should allow me to get them from `provideDebugConfigurations` here too.

**Comment by weinand** [comment]
I've verified that a debug type is shown in the environment menu, if there is a registered `DebugConfigurationProvider`. However, this `DebugConfigurationProvider` does not need to implement the `provideDebugConfigurations`.

This information is actually passed from the extension to VS Code: the IDebugConfigurationProvider has only a `provideDebugConfigurations` method if there is one in the extension.

**Comment by isidorn** [comment]
@weinand thank you, I have created https://github.com/Microsoft/vscode/issues/33663 to track this
