### ISSUE TITLE
Doesn't open updated file correctly

### ISSUE THREAD

**Issue by wschin** [Microsoft/vscode#33457]
There is a file called "foo.txt." I updated via "git pull," but VS Code still gave me an old version until manually closing the file opened by default.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
mdmath|goe|2.0.3
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
rewrap|stk|1.5.0
vim|vsc|0.9.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31600
