### ISSUE TITLE
Unlocalized message with misconfigured debug adapter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33452]
![image](https://user-images.githubusercontent.com/323878/29844056-de76c08e-8cc2-11e7-91d9-50cc2a63686b.png)

Have a debug adapter with no runtime, like in https://github.com/Microsoft/vscode/issues/33367 but remove the resolveDebugConfiguration. Launch a config, and see this message.

Also, after I see this message, I can't start debugging in that folder again. Clicking the Play button has no effect. I have to reload the window. I think it shouldn't be a fatal error.

**Comment by isidorn** [comment]
I have fixed it being a fatal error.
However the message I will not fix, since the adapter does not have any details at the point that error is thrown so it would take some refactoring to get the proper name of the adapter which I am unwilling to do
