### ISSUE TITLE
Drag/Drop of folder named "tmp" does nothing

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33466]
Testing #33275 

![image](https://user-images.githubusercontent.com/1487073/29848026-341f1e7c-8cd3-11e7-8c6d-f3cdaf4cdaec.png)

I have a folder called `tmp` and all it has in it is a `json` file:

![image](https://user-images.githubusercontent.com/1487073/29848047-48d72238-8cd3-11e7-972a-a5468ccef517.png)

When I drag/drop it to the explorer, nothing happens:

![tmpfolderdnd](https://user-images.githubusercontent.com/1487073/29848064-5ca2517a-8cd3-11e7-8b5b-521c558a7656.gif)

**Comment by chrisdias** [comment]
D/D of a folder without any content "fails" as well, but the `tmp` folder i have on disk has one file.  

If i d/d the `tmp` folder to the editor space (NOT the Explorer), I get a prompt to save an existing workspace (I say No) and then the editor is restarted with `tmp` folder opened.

**Comment by chrisdias** [comment]
One more update... I can do `File | Add Folder to Workspace` and include the `tmp` folder or any empty folder.

**Comment by ghiscoding** [comment]
@chrisdias I saw in the insiders 1.16 doc that the drag and drop now only works when dragging in the editor area (not the solution explorer like you are trying). See the docs here for [open a folder via drag and drop](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_16.md#open-a-folder-via-drag-and-drop)

**Comment by chrisdias** [comment]
@ghiscoding I can drag folders into the Explorer to _add_ to the existing workspace. What I can't do is drag this particular folder or empty folders.  Other folders can be dragged into the Explorer just fine.  

@bpasero ?

**Comment by bpasero** [comment]
This looks like an upstream issue with Electron/Chrome. I have seen the DND from external working funky under certain patterns (e.g. empty files).
