### ISSUE TITLE
Customize Emmet class attribute

### ISSUE THREAD

**Issue by mmakarios** [Microsoft/vscode#33461]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0

I'm trying to customize the JSX emmet filter in VSCode to use the attribute `styleName` from https://github.com/gajus/babel-plugin-react-css-modules. It uses `styleName` instead of `className` to reference styles.

First, I tried creating an Emmet snippet `[st]: "styleName"` and typing `div[st]` followed by Tab to see if worked. It didn't, the result was `<div st=""></div>`.

I think the easiest solution would be to change the file `jsx.js` in https://github.com/emmetio/emmet/blob/master/lib/filter/jsx.js. `className` would become `styleName`. Not the best solution since I would lose the `className` attribute instead of having an alternative.

Is it possible to change this file? Is this the best solution at the moment?
Thanks!

**Comment by ramya-rao-a** [comment]
@mmakarios  For now you can do this by using the `[]` syntax for attributes. Example:  `ul[styleName="hello"]`

@sergeche Can replacing the `className` with `styleName` be a transformation we can add on to the expand options?

**Comment by sergeche** [comment]
The only reason to have such transform is to write abbreviation `ul.foo` and have `<ul styleName="foo">` instead of `<ul className="foo">`, which is not something that should be in JSX transformer. A better solution is attribute aliases so users can define something like `s: styleName` and write `ul[s=foo]` instead of `ul[styleName=foo]`

**Comment by ramya-rao-a** [comment]
@sergeche How do we create such aliases

**Comment by sergeche** [comment]
I think it should be an option for `@emmetio/html-transform`: a simple key-value pair. Just `tree.walk()` over expanded abbreviation tree and replace attribute names

**Comment by ramya-rao-a** [comment]
@mmakarios As @sergeche suggested the proposed solution would be to make changes in the `@emmetio/html-transform` module.
I would suggest to create this feature request in the repo for `@emmetio/html-transform` instead as any solution to this feature request should be emmet specific and not editor specific
