### ISSUE TITLE
Drag/Drop of folder shows "Move" action

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33462]
testing https://github.com/Microsoft/vscode/issues/33275

Drag/drop of a folder onto the editor shows a "Move" action, which makes me think my folder is going to be moved instead of simply opened.

![image](https://user-images.githubusercontent.com/1487073/29847579-3817c58a-8cd1-11e7-996a-bec68dfdfe5e.png)

**Comment by chrisdias** [comment]
And it shows "Copy" when dragging to the Explorer.  Again, it makes me believe some sort of action will be taken on my folder when in reality nothing will happen to the folder.

![image](https://user-images.githubusercontent.com/1487073/29848156-c6e22f24-8cd3-11e7-94a3-dc7f642641d6.png)

**Comment by bpasero** [comment]
I changed the drop effect to be "Copy" to be consistent. That applies to dropping over the editor area as well as dropping over the tabs. This does not apply when dragging a tab actually because there we support both moving and copying operations (depending on the Alt key pressed or not).
