### ISSUE TITLE
Git: Support commit message intellisense

### ISSUE THREAD

**Issue by soanvig** [microsoft/vscode#33465]
GitHub uses excellent system of closing issues, by providing the commit with appropriate text: "Closes #xx", "Close #xx" etc.

It would be quite useful for VS Code to also integrate with the issues system, and suggest the issues just like the GitHub's textarea does during commenting or whatever.

Feature:
Enable integration with GitHub issue system if `origin` is GH server. Retrieve all issues, and suggest them after entering "#" into commit message.

**Comment by charlex** [comment]
I support this idea. Are there extensions on the marketplace that allow intellisense in the commit message box in general?

**Comment by lszomoru** [comment]
The [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) provides completion suggestions for issues that can be triggered in the commit input field using the `#` character. Please install the extension and take a look. In case some functionality is still missing please feel free to reopen this issue. Thanks!
