### ISSUE TITLE
Make Popups less annoying

### ISSUE THREAD

**Issue by detachmode** [Microsoft/vscode#33468]
<img width="903" alt="bildschirmfoto 2017-08-30 um 01 33 44" src="https://user-images.githubusercontent.com/19249828/29848817-4a2f8b8e-8d23-11e7-80c1-656a5d558d37.png">

Why is it so big and I have to click close so it disapears? Often this popups are used in cases where a small info text in the button bar would fit better.

**Comment by mjbvz** [comment]
Thanks. I believe this falls under #22388
