### ISSUE TITLE
--add of multiple folders should add to existing instance, not open new instance

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33469]
testing #33275 

![image](https://user-images.githubusercontent.com/1487073/29848912-5e7184f8-8cd8-11e7-99f6-8bbee9d2674d.png)

Consider the following three command lines:

a) `code-insiders -a <folder>` will add the folder to an existing instance
b) `code-insiders -a <folder1> <folder2>` will open a new instance of code with the two folders
c) `code-insiders <folder1> <folder2>` will open a new instance of code with the two folders

The behaviors for `b` and `c` are the same.  My expectation is that `b` would add to an instance while `c` would open a new instance.  Since they currently behave the same, I suggesting making `b` add to an instance.

**Comment by bpasero** [comment]
Great catch 👍

**Comment by isidorn** [comment]
Works fine if I have a workspace with single root open, however does not work if I have a MR workspace with folders A and B and I try to add C and D. The command simply gets ignored

**Comment by isidorn** [comment]
My unsaved workspace was somehow in a bad state. Once closing vscode and reopining I can no longer repro -> closing
