### ISSUE TITLE
SCC badge flicker is like having an eyelid twitch that won't go away

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33464]
Testing #33275 

![image](https://user-images.githubusercontent.com/1487073/29847878-a7afba8c-8cd2-11e7-9bc2-0992d4a52600.png)

Open 4 or 5 folders all under their own SCC.

Notice that the badge that shows me the number of changed files is constantly flickering between the stop watch and the number of changed files

![sccflickerhurtsmyeyes](https://user-images.githubusercontent.com/1487073/29847881-ad0bea6e-8cd2-11e7-8d09-f4e5d3afe864.gif)

**Comment by isidorn** [comment]
@joaomoreno I now never get the progress indiciator in the scm viewlet. This is fine for me as the user as I believe this is just noise, but not sure if that was your intention with this fix

**Comment by joaomoreno** [comment]
I've changed the threshold for when the progress indicator appears. It will only appear on _longer_ operations.

**Comment by isidorn** [comment]
Makes perfect sense, thanks
