### ISSUE TITLE
send text to terminal appears twice

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33467]
I'm seeing the text I send to the terminal 2x, once before the prompt and once at the prompt:

![image](https://user-images.githubusercontent.com/1487073/29848674-2dd6582e-8cd7-11e7-96fa-4d98f4d8ed44.png)

This is the code in the Docker extension as an example:

``` typescript
    const terminal: vscode.Terminal = vscode.window.createTerminal('Docker');
    terminal.sendText(`docker build -f ${uri.file} -t ${value} ${uri.path}`);
    terminal.show();
```

**Comment by Tyriar** [comment]
This is as designed, it's just how the shells work on mac/linux as they're launching
