### ISSUE TITLE
XML syntax highlighting, word-wrap not working for large xml file

### ISSUE THREAD

**Issue by nexional** [Microsoft/vscode#33460]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T07:05:40.998Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|0.6.0
npm-intellisense|chr|1.3.0
python|don|0.7.0
xml|Dot|1.9.2
vscode-npm-script|eg2|0.2.0
PowerShell|ms-|1.4.1
sort-lines|Tyr|1.3.0

---

Steps to Reproduce:

VS code fails to do syntax highlighting on huge files (~100mb). In my case I tried to open log4j based log file. VS code didn't do syntax highlighting. Also it failed to toggle word-wrap on that file.

Reproduces without extensions: Yes/No - YES

**Comment by alexandrudima** [comment]
At this time, this is as designed. Certain features are turned off for files over 30MB or over 300K lines in order to reduce memory usage and be able to open those files.

Please see https://code.visualstudio.com/updates/v1_15#_large-file-support

> Any file that is over 30MB or over 300K lines will now be considered a large file and will be handled specially in some circumstances. By disabling certain features for large files, for example tokenization, line guides, and wrapping or folding, we were able to optimize memory usage, in some cases, by as much as 50%. Additionally, large files will never travel to our web worker, which computes diff information, link detection, or word based completions. This helps in reducing the memory pressure on the operating system.

**Comment by nexional** [comment]
Ok, thanks!

**Comment by intbots** [comment]
@alexandrudima Is there a way to control the 300MB and the 300K values from settings?

**Comment by alexandrudima** [comment]
@intbots not at this time, the constants are not configurable.
