### ISSUE TITLE
Integrated terminal emacs sometimes becoming visually corrupted

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33463]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T06:52:41.503Z)
- OS Version: Darwin x64 16.7.0

---

**Steps to Reproduce**

1. Open bash integrated terminal. Open emacs
2. Start typing out a sentence that has spaces in it in a new document

**Bug**
![aug-29-2017 15-51-45](https://user-images.githubusercontent.com/12821956/29847788-47f6afd8-8cd2-11e7-9796-411807596e22.gif)

After typing a few characters, the cursor jumps to the far side of the screen. This happens no matter what the viewport size is. Long strings without spaces do not seem to trigger this and I cannot reproduce it on the system terminal

It seems to have started with the most recent insiders build

**Comment by Tyriar** [comment]
Nice find, for some reason emacs adds a `\t` and then a backspace after every xth space which is what causes this. The terminal refactor involved making the buffer own tabs and the alt buffer's tabs aren't being initialized correctly :smiley:
