### ISSUE TITLE
The Tizen version does not support the debug mode!

### ISSUE THREAD

**Issue by rajeshchettupalli** [Microsoft/vscode#33478]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
debugger-for-chrome|msj|3.2.0
vscode-janus-debug|otr|0.0.10
tizentv|tiz|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this agains the tizen extension, thanks
