### ISSUE TITLE
vscode cpu high bootstrap searchService

### ISSUE THREAD

**Issue by kwangok** [Microsoft/vscode#33471]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
weex|jay|0.4.0
AWK|lug|0.0.2
ftp-sync|luk|0.3.3
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
vetur|oct|0.9.5
laravel-5-snippets|sac|2.0.1
python|tht|0.2.3
vscode-lua|tri|0.8.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Will track this in other issues like #33019

**Comment by peabnuts123** [comment]
But that other issue is closed … ? I am having this issue. Vscode searchService using an entire core all of the time.

**Comment by roblourens** [comment]
This issue and probably that one is probably due to https://github.com/Microsoft/vscode/issues/34434. Are you opening a large folder? Is it any different using the Insiders build?
