### ISSUE TITLE
TSLint is not linting

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/vscode#33470]
- VSCode Version: 1.15.1
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. Check out the code <a href="https://stackoverflow.com/questions/45949692/tslint-json-is-not-working-in-vs-code">on SO</a>

I have a completely valid `tslint.json` and `tsconfig.json`. When I run my lint script, `"lint": "tslint ./src/**/*.ts --exclude \"./**/node_modules/**/*.ts\""`, I do get output from my Terminal. But VS Code doesn't highlight or underline any issues. It does not work with or without the extension. I've force-quit several times. I've restarted my computer. I grabbed someone else's tsconfig and tslint from a public repo, with no luck. I even cloned a reputable repo and still get no linting. (<a href="https://github.com/apollographql/apollo-server">apollographql/apollo-server</a>). So, not really knowing what to do, here I am, hopeful to get some help. Thanks!

Reproduces without extensions: Yes

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#248
