### ISSUE TITLE
Visual code will become more and more time when used the shell like npm start

### ISSUE THREAD

**Issue by kingemma** [Microsoft/vscode#33474]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:06.988Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-2-snippets|ara|0.1.0
scanner-js-twain-wia-javascript-browser-scan|asp|2.0.2
vscode-html-css|ecm|0.1.8
tortoise-svn|fan|0.1.1
NodeAssertionSnippets|jay|0.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.1.0
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
debugger-for-chrome|msj|3.2.0
vscode-material-ui-snippets|Swo|1.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide more details -> like reporucable steps. Can you calso reprodcuce without extensions?

**Comment by kingemma** [comment]
If the new version vs code with nodejs spends more cpu in task, will not release the cpu resource when re-start that I need restart computer to release the cpu resource ?
The older vs code work well .
------new vs code ------ --
 Version:1.15.0 
 Shell:1.6.6 
 Node:7.4.0
Thank you.

**Comment by isidorn** [comment]
@bpasero forwarding to you to ask your famous questionare

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`
