### ISSUE TITLE
Backspace to previous line, delete one more character, then type a character: suggestions list in wrong place

### ISSUE THREAD

**Issue by rmunn** [Microsoft/vscode#33475]
- VSCode Version: 1.15.1
- OS Version: Linux Mint 18 (based on Ubuntu 16.04)

Steps to Reproduce:

1. Set the `editor.acceptSuggestionOnEnter` option to `off`.
1. Open an existing file so that the suggestions list has several words to populate it.
1. While the suggestions list is up for a word, press Enter to start a new line *without* accepting the suggestion.
1. Hit Backspace twice, to delete the newline and the last character of the previous word.
1. Type one more character, which triggers the suggestions list.

Result: the suggestions list is shifted horizontally quite far right of where it should be. See screenshots below.

Before pressing Enter:

![Before pressing Enter](https://user-images.githubusercontent.com/90762/29854239-db62bdd8-8d6e-11e7-8dde-9ce13db9fc1a.png)

After pressing Enter, then Backspace twice, then typing the letter `e`:

![After backspace twice plus another letter](https://user-images.githubusercontent.com/90762/29854264-01948f90-8d6f-11e7-96dd-39f5e04f757b.png)

Note that I had trouble reproducing this when in a new file, but I could consistently reproduce it in a file that had quite a lot of text in it. Also, timing seems to be involved: if I waited a while between backspacing and typing the new character, the suggestions list appeared in the right place. Only when the two backspaces were quickly followed by typing `e` did the suggestions list show up in the wrong place horizontally — but when I typed those keystrokes at my normal typing speed (fairly quickly), the suggestions list consistently went too far to the right.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@rmunn I'm thinking you're also using something like:
```
	"editor.wordWrap": "wordWrapColumn",
	"editor.wordWrapColumn": 40,
	"editor.rulers": [ 40 ]
```

Do you perhaps use other settings that correlate with the reproducibility of the issue. i.e. does this happen without word wrap for example ? Or only at the end of a wrapped line ?

Unfortunately, I tried, and tried, and tried, but could not get the widget to be misplaced.

@ramya-rao-a Do you have any ideas ?

**Comment by rmunn** [comment]
I haven't had any success in reproducing this, so I agree that this should be closed. I'll reopen a new issue if I manage to reproduce this behavior again.
