### ISSUE TITLE
[folding] Add code folding for markdown based on heading level

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3347]
``` markdown
# Some heading

Collapsing `#` should collapse all lower level headings; `##`, `###`, etc.

## Another heading

Collapsing `##` should collapse all lower level headings; `###`, `####`, etc.

### Another heading

And so on...
```

**Comment by bpasero** [comment]
:+1:

**Comment by windsource** [comment]
+1

**Comment by darkf** [comment]
Why is this essential feature still not a thing?

**Comment by Tyriar** [comment]
@darkf because it relies on #3422 which is non-trivial and it needs to be prioritized against other work.

**Comment by sixeyes** [comment]
+1

**Comment by gravidor** [comment]
+1

**Comment by yusiwen** [comment]
+1
or adding a heading list view(TOC view) on the right side, it's really convenient for editing a large markdown file.

**Comment by iswade** [comment]
Please refer to the org-mode tab feature to implement, it's powerful.

**Comment by sejnub** [comment]
+1

**Comment by aeschli** [comment]
duplicate of #3422

**Comment by neilsustc** [comment]
I noticed that this is already implemented in the latest insider build, thanks a lot.
One more request, would you please preserve the last blank line of a folded region?
I mean

```
- # Heading 1

  Some text

- # Heading 1

  Another text
```

becomes

```
+ # Heading 1

+ # Heading 1
```

instead of

```
+ # Heading 1
+ # Heading 1
```

One reason is that currently

```
- # Heading 1           - # Heading 1

  ...                     ...

- ## Subheading 1  -->  + ## Subheading 1
                        - # Heading 2
  ...

- # Heading 2
```

**Comment by hikinthru** [comment]
Can anyone update the status on this?

**Comment by Tyriar** [comment]
@hikinthru it's coming to the next stable release.
