### ISSUE TITLE
Opening documents from OneDrive synced folder fails

### ISSUE THREAD

**Issue by peterloete** [Microsoft/vscode#33484]
- VSCode Version: Code - Insiders 1.16.0-insider (d0d00e882437092f521d2d7893cc56ee296d278f, 2017-08-29T07:05:40.998Z)
- OS Version: Windows_NT x64 10.0.16275
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1. Open file that is in a OD synced folder (file open or drag 'n' drop)
2. Error message 'Unable to open file 'xxxx.ext' with buttons to create file or to cancel the operation
3. Fails on 32-bit versions as well

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#27285
