### ISSUE TITLE
Undo from external file change: preserve viewstate?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33487]
Steps to Reproduce:

1. do some changes in a file
2. undo from the git viewlet

=> the editor jumps to line/col 1

It would be cool to preserve the view state in this case.

**Comment by alexandrudima** [comment]
@bpasero

I cannot reproduce on Insiders, and the new code that updates a buffer while also maintaining the undo stack should not cause AFAIK any cursor reveal / scroll, as the edits go straight to the model.

![kapture 2017-08-30 at 9 45 21](https://user-images.githubusercontent.com/5047891/29860974-058e17da-8d68-11e7-8a1a-bd77fb75e094.gif)

**Comment by bpasero** [comment]
@alexandrudima actually there is more involved:
* have a larger file and scroll to middle
* remove some lines
* undo from the GIT viewlet
* undo in the editor via undo command
* redo

=> I am now scrolled all the way to the top

**Comment by alexandrudima** [comment]
Aha, I see. Unfortunately, these edits are applied directly through the buffer (outside of an editor) at the level of the `IModelService`. I cannot easily get myself ahold of an editor at this layer, unless we also change some things in the workbench, that the change on disk on a file is correlated with a possible editor currently displaying the file. We would then need to move some of the code of `IModelService.updateModel` to the place which has access to the editor, to the buffer, and to the new TextSource (file on disk). We could then get the current editor selection and save that in the undo stack.

**Comment by aiswaryadeepak** [comment]
have a similar issue (I think). 

1. viscose jumps to line 1
2. undo stops working https://github.com/Microsoft/vscode/issues/24709

I am using git from the cli though (bash on macOS) ie. am not using git from vscode
