### ISSUE TITLE
Error message pulls focus out of problems view

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#33482]
Background: I had a tslint error reported in a file that I deleted. The error still showed up in the problems view.

1. Focus on an entry in the problems view in a file that still exists. This can be done by clicking into the problems view or using the keyboard
2. Use arrow keys to move between problems
3. Notice that as you move between them, an editor previews the area with the problem but the focus remains in the problem view
4. Use the arrow keys to move to a problem for a file that does not exist.

Expected: If an error message appears, it will return focus to the problems view
Actual: An error message appears (Unable to open 'filename', file not found), but then focus moves to the editor in the location of the last valid problem.

**Comment by sandy081** [comment]
Looks like it is already fixed

![kapture 2018-09-18 at 16 42 50](https://user-images.githubusercontent.com/10746682/45695546-f1568080-bb61-11e8-94e1-45a943a7627d.gif)
