### ISSUE TITLE
Node.js - Methods list in module

### ISSUE THREAD

**Issue by Lax-Keerthi** [Microsoft/vscode#33489]
**This is a feature request**. Not a bug.  With Node.js environment, when I open any module file, Or .js file, I would like to see all member functions in the file in a list box.  Similar to classic Visual Studio UI.

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline

![screen shot 2017-08-30 at 3 49 51 pm](https://user-images.githubusercontent.com/12821956/29898493-e4f03e26-8d9a-11e7-9068-9902b7715dcb.png)


The Go to Symbol action will also display this: https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-symbol

**Comment by Lax-Keerthi** [comment]
Thank you. This extension ^^ works as expected.
