### ISSUE TITLE
[Feature request] Extend the default search functionality

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#33483]
Currently for me, the search is one of the most functionality which can / should be extended.
For example, please look how the search look in another editors, like:

PHPStorm (ideal)
![phpstorm](http://i.imgur.com/29yg2yt.png)

SublimeText
![sublimetext](http://i.imgur.com/ZGTEFaY.png)

I mean the preview file / search result should be bigger than display only 1 line (without context of rest code)

**Comment by roblourens** [comment]
Thanks for the request. I do have specific issues for the suggestions here, like #18791 for context lines. 

See https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asearch+label%3Afeature-request :)
