### ISSUE TITLE
[folding] Cannot code fold empty functions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3349]
![image](https://cloud.githubusercontent.com/assets/2193314/13258746/4bf18806-da09-11e5-9882-18b4dea62383.png)

**Comment by joaomoreno** [comment]
As designed?

**Comment by aeschli** [comment]
Yes, as designed, but maybe the design can be improved :-)

**Comment by aeschli** [comment]
To implement that, we would need to have language agnostic knowledge and understand that `}` is closing block but not opening one.
Without knowing that we would also create a folding block from line 3 to line 5.
![image](https://cloud.githubusercontent.com/assets/2193314/13258746/4bf18806-da09-11e5-9882-18b4dea62383.png)

**Comment by aeschli** [comment]
Closing as designed.
