### ISSUE TITLE
How to finish a snippet halfway through

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#33491]
- VSCode Version: 1.15.1
- OS Version: Windows 7 Ultimate x64

Hello. I found a bug.
When I type ```!```, to expand the html template emmet displays the result on the cursor between the body tags. After pressing the enter key, ```device-width``` is selected, the cursor is placed after it, and the cursor is placed after the html tag. To remove the cursor after the html tag and selected ```device-width```, I need to press the esc key twice. For example, if I type the div tag, then it works. The cursor is placed between the tags.

**GIF**

![expand](https://user-images.githubusercontent.com/29632606/29809141-5a00683e-8cde-11e7-810d-72cd8db771b6.gif)

**Comment by Mlocik97-issues** [comment]
this same bug I reported 2x.....

**Comment by ramya-rao-a** [comment]
@jrieken This occurs for any snippet with placeholder. Need to press ESC twice to escape snippet mode
```
"Sample": {
		"prefix": "list",
		"body": [
			"<ul class=${1:hello}>${0}</ul>"
		]
	}
}
```

**Comment by jrieken** [comment]
Unsure what you guys mean? Do you expect the selection to collapse when leaving snippet mode? You enter snippet mode, hit escape and snippet mode stops, e.g. the placeholder for the final tabstop disappears. However, the current selection is maintained (which I think is fair because you might want to continue with it). To collapse a selection you hit Esc, as always. 

![aug-31-2017 09-44-51](https://user-images.githubusercontent.com/1794099/29912236-4705c432-8e31-11e7-87e3-1b1049d292b1.gif)

**Comment by opencreative** [comment]
I want to understand why the cursor is placed after the ```device-width```. The cursor should be placed between the body tags.

**Comment by jrieken** [comment]
Understood. We have two commands `leaveSnippet` and `acceptSnippet`. The former is bound to <kbd>Esc</kbd> by default and the latter isn't bound but does what you want, it stops snippet mode and goes to the final tab stop. 

I'd suggest that you rebind the keys, e.g. to Escape or to something like Shift+Escape

**Comment by opencreative** [comment]
What is the setting for the key binding?

**Comment by jrieken** [comment]
* F1 > Open Keyboard Shortcuts
* Search for 'acceptSnippet'
* Press the `+`-icon on the left

**Comment by opencreative** [comment]
Got it. Thank you.

**Comment by opencreative** [comment]
I'll try to bind the keyboard shortcut.

**Comment by opencreative** [comment]
I assigned a keyboard shortcut. <kbd>Shift</kbd>+<kbd>A</kbd>
I hope this will be a good solution.

![accept](https://user-images.githubusercontent.com/29632606/29917383-2d422a64-8e85-11e7-9315-f68a05c23804.gif)

After pressing the keys <kbd>Shift</kbd>+<kbd>A</kbd>, the cursor is placed after the html tag.  Is this how it should be? On the screenshot the cursor is placed between the body tags.

![cursor](https://user-images.githubusercontent.com/29632606/29917718-1e91840a-8e86-11e7-94e4-ff6369099e65.jpg)

**Comment by jrieken** [comment]
@ramya-rao-a Will know, from the preview it isn't clear where emmet put the *final* tabstop. You can try with a "normal" snippet, like such https://github.com/Microsoft/vscode/issues/33491#issuecomment-326161018

**Comment by opencreative** [comment]
After pressing the keys <kbd>Shift</kbd>+<kbd>A</kbd>, snippet below works correctly.

```
"Sample": {
    "prefix": "list",
    "body": [
        "<ul class=${1:hello}>${0}</ul>"
    ]
}
```
![list](https://user-images.githubusercontent.com/29632606/29918623-66537f3e-8e89-11e7-9664-e5489e6c4cd9.gif)

**Comment by jrieken** [comment]
Great, I'll leave the emmet details up to @ramya-rao-a and I am closing this as question. Thanks

**Comment by ramya-rao-a** [comment]
@jrieken Emmet doesn't put a final tab stop. Since it results in a snippet without a final tab stop, VS Code appends a final tab stop at the end.

@opencreative To get to the cursor location as shown in the suggestion docs, press tab. pressing tab takes you around placeholders and tab stops

**Comment by jrieken** [comment]
> Since it results in a snippet without a final tab stop, VS Code appends a final tab stop at the end.

Yeah, that is how snippets are defined (not by me btw). Emmet could consider adding a final tabstop in the 'right' place

**Comment by opencreative** [comment]
@ramya-rao-a, thank you.

**Comment by ramya-rao-a** [comment]
> Emmet could consider adding a final tabstop in the 'right' place

I'll give that a try

**Comment by ramya-rao-a** [comment]
Logged upstream issue with Emmet for this: https://github.com/emmetio/expand-abbreviation/issues/11

**Comment by ramya-rao-a** [comment]
Emmet snippets will now have a final tab stop and will not rely on the default final tab stop that gets added to the end of the snippet.

Note to verifier:
- To test the final tab stop, add a keybinding to the `acceptSnippet` command and use it right after expanding any emmet abbreviation
- Test the `!` emmet abbreviation. The final tab stop should be inside the `body` tag instead of being after the closing `html` tag
- Try any of the other emmet abbreviations and compare with stable. In stable, the final tab stop will always be at the end of the snippet.

**Comment by opencreative** [comment]
@ramya-rao-a, it works!

**Comment by ramya-rao-a** [comment]
@opencreative Thanks for verifying, Happy Coding!

**Comment by opencreative** [comment]
@ramya-rao-a, thank you!
