### ISSUE TITLE
No information of Source Control type for Initialising repository

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#33499]
In SCM view when there is no repository, it is not clear in which SCM repository is initialised.

![image](https://user-images.githubusercontent.com/10746682/29866122-b5077c56-8d77-11e7-87ac-effd6828d23c.png)

**Comment by joaomoreno** [comment]
I don't understand... what do you mean? If you click on the `Initialize Repository` action, you will get to say where you want to initialize a repository.

**Comment by sandy081** [comment]
@joaomoreno Updated the issue to be more clear. How do I know that initialise repository action is from git. What if there is other scm with initialise action?

Note we show `git` label when there is repository

![image](https://user-images.githubusercontent.com/10746682/29869569-bfebe93e-8d83-11e7-9658-7a5d7fab783d.png)
