### ISSUE TITLE
EH debugging: can not connect out of source

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33490]
1. Run vscode out of source
2. Try to debug a hello world vscode extension

Get the following error
`Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:27451).`

This scenario is important for me since I always run VSCode out of source for fixing EH issues.

Here's my `launch.json
fyi @weinand 

```json
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["/users/isidor/development/vscode", "--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/src/**/*.js" ],
            "preLaunchTask": "npm"
        }
    ]
}

```

**Comment by weinand** [comment]
We are now using our patched build of Electron 1.7.3 whereas `scripts/code.sh`still uses the unpatched Electron 1.7.3 (which doesn't support the "--inspect" protocol).

EH debugging on macOS with what is currently in master:

1. download the `electron` and `ffmpeg` zips from https://github.com/Microsoft/vscode-electron-prebuilt/releases/tag/v1.7.3
2. copy them to the output of  
```echo 'console.log(`${require("os").tmpdir()}/gulp-electron-cache/atom/electron`);' | node```
3. delete the `.build` folder in the the vscode workspace’s root folder
4. `./scripts/code.sh --debug`
5. attach to extension host (edited)

**Comment by QwertyZW** [comment]
@weinand  link in step 1 seems dead

**Comment by weinand** [comment]
The link points to a private repo. This is a temporary solution until Electron has fixed some bugs and we can go back to an official (unpatched) version of Electron.
