### ISSUE TITLE
Git screws up when workspace is open in the wrong lettercase

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33498]
![image](https://user-images.githubusercontent.com/1926584/29865892-0c374cd2-8d77-11e7-9b6f-d1e5c2416985.png)

**Comment by joaomoreno** [comment]
Repro: In macOS or Windows, open `code folder_name` using the wrong folder name casing

**Comment by isidorn** [comment]
I still get two split panes
Notice that the second one has a shorter title for some reason

![screen shot 2017-08-31 at 14 26 32](https://user-images.githubusercontent.com/1926584/29923062-69a7e19c-8e58-11e7-9c63-8d56da0e4bac.png)

**Comment by joaomoreno** [comment]
Oh wow.

**Comment by joaomoreno** [comment]
It was fixed for like 2 commits... another fix broke it!
