### ISSUE TITLE
Extract function converts tabs into spaces

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33492]
Testing: #33282 

```ts
function foo() {
	console.log('Hello World');
}
```
- observe: console.log is indented using tabs
- select `console.log('Hello World');`
- run extract function
- you get
```ts
function foo() {
    newFunction();
}
function newFunction() {
    console.log('Hello World');
}
```
Observe: spaces are used as indentation.

**Comment by dbaeumer** [comment]
@mjbvz unclear if this is us or TS

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18328
