### ISSUE TITLE
VS Code icon is too transparent

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33503]
ref #33272:

On "Elementary OS (linux), the VS Code icon shows up in the dock with "sublime fragility":

![2017-08-30_12-09-19](https://user-images.githubusercontent.com/1898161/29867622-68bc4cbe-8d7c-11e7-9439-cd4e1de911b8.png)

**Comment by dominicfallows** [comment]
Perhaps related to some thoughts here  [#6607 #issuecomment-325998918](https://github.com/Microsoft/vscode/issues/6607?#issuecomment-325998918) ?

**Comment by bpasero** [comment]
Now using the macOS icon on Linux too.

**Comment by weinand** [comment]
I'm not seeing a different icon in the 9c27b11bde339d58a8da0e3f6d5f88f7a4fcafa7 build:
![2017-09-01_11-55-48](https://user-images.githubusercontent.com/1898161/29965078-81f32144-8f0c-11e7-8291-0108e6674480.png)

**Comment by bpasero** [comment]
I did a bad commit, next insider to verify.

**Comment by weinand** [comment]
Nice!
![2017-09-01_14-57-36](https://user-images.githubusercontent.com/1898161/29970729-fc0f347c-8f25-11e7-9769-80b98d00a611.png)
