### ISSUE TITLE
[angular 2] typescript variables highlight in html

### ISSUE THREAD

**Issue by Maddyshien** [Microsoft/vscode#33505]
I want colorize the typescript properties in html like data binding property binding should be colorized
in vs code ?any extension or custom way to do that?

**Comment by aeschli** [comment]
@Maddyshien Can you paste a code example?

**Comment by Maddyshien** [comment]
@Aeschli thanks for your responding.
I want colorize the typescript variables inside the html.
Example
Suppose in html i want print  typescript employees[ ] array means 
<p *ngFor="#employee employees">
{{employee}}<p> i would do like in this case i want to different colos for employee refrence and employees array.

I tried many ways of customizing vs code and extensions.but still i cant found that.

**Comment by Maddyshien** [comment]
@aeschli thanks for responding 
I want typescript variables should be colorized inside html
In Angular 2
-------------------------
in typescript component.ts one array employees is threre
    employees[] :string=[];

I want to interpolation of that array employees
---------------------------------
in component.html

<p *ngFor="#employee  employees">{{employee}}</p>
------------------------------------------------------------
   in this case i want to colorize the employees array and its reference #employee
   in html
i tried many  vs code extension and possibilities of customizing also the vs code but still i cant found that.
i had tried below link for customizing vs code and struggling with that
https://github.com/microsoft/typescript/issues/6508
can you help me out from this?

**Comment by Maddyshien** [comment]
@aeschli thanks for responding 
i want colorize the typescript variables inside html
for eaxmple:
in typescript component.ts one array employees is there
employees[] :string=[];

I want to interpolation of that array employees

in component.html
  // <p *ngFor="#employee  employees">{{employee}}</p> //

------------------------------------------------------------
 in this case i want to colorize the employees array and its reference 
 #employee in html i tried many vs code extension and possibilities of 
 customizing also the vs code but still i cant found that. i had tried below link 
 for customizing vs code and struggling with that
 https://github.com/microsoft/typescript/issues/6508 
 can you help me out from this?

**Comment by aeschli** [comment]
That would have to be provided by an extension as this is an extension to HTML.
We don't want to add angular 2 specific rules to the HTML extension.

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try this extension: https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
