### ISSUE TITLE
Switch Ctrl+Alt+Up/Down with Ctrl+Alt+Up/Down

### ISSUE THREAD

**Issue by W4RH4WK** [microsoft/vscode#33508]
The current default keyboard shortcuts are: `Ctrl + Alt + Up / Down` creates another cursor one line above / below the current line, while `Shift + Alt + Up / Down` duplicates the current line.

I propose to swap these keybindings because they conceptually switched.

Often the `Ctrl` key is associated with duplicating or copying something. This already happens in VSCode when you drag a selection while holding `Ctrl`, the selection is copied rather than moved.

On the other hand, one can also argue that `Shift` is often associated with selecting things, and adding a new cursor is kinda similar. In VSCode, if I click and drag while holding down `Shift + Alt`, I get a (rectangular) selection with multiple cursors.

From this point of view it would be logical to have `Shift + Alt` spawn new cursors and `Ctrl + Alt` duplicate the current line.

**Comment by alexandrudima** [comment]
Changing our default keybindings is quite a tough change, as many of our users install updates automatically, and from one update to the next, their possibly beloved keybindings will no longer function.

**Comment by W4RH4WK** [comment]
I'd advice against introducing the change only for new installations. Adding this kind of *hidden state* is almost never a good idea. A better way may be to add this to a list of changes for the next major version (given such a list exists).

**Comment by W4RH4WK** [comment]
I spend some more time with the key-bindings for the cursor keys and came up with this. I am not saying this should be added, I just want to let you know and think about this setup.

|           Shortcut            |            Command             |
| ----------------------------- | ------------------------------ |
| `Ctrl + ↑ / ↓`                | *Scroll Line up / down         |
| `Ctrl + ← / →`                | *Move cursor word left / right |
| `Alt + ↑ / ↓`                 | *Move lines up / down          |
| `Alt + ← / →`                 | Increase / decrease indent     |
| `Ctrl + Alt + ↑ / ↓`          | Copy line                      |
| `Ctrl + Alt + ← / →`          | *Move Editor to group          |
| `Alt + Shift + ↑ / ↓ / ← / →` | Column select                  |
| `Ctrl + Shift + ↑ / ↓`        | *Selection up / down           |
| `Ctrl + Shift + ← / →`        | *Select word left / right      |
| `Ctrl + Alt + Shift + ↑ / ↓`  | Add cursor above / below       |
| `Ctrl + Alt + Shift + ← / →`  | Grow / shrink selection        |

\* ... already default

The ideas behind these bindings are:

- Use `Alt` to move lines around (even left and right)
- Use `Alt + Shift` for column selection
- Use `Ctrl + Shift` for word selection
- Use the combination of `Ctrl` and `Alt` for more advanced commands

Something I am yet not so sure about is having `Ctrl + Alt + Shift + ← / →` grow and shrink the selection. Being able to also select words while doing a cursor selection seems more intuitive. With this current setup you'd have to let go of `Alt` and hold `Ctrl`.

**Comment by sngreen** [comment]
What an effing nightmare! Why not have it the same as Windows as Linux -> shift+alt+down down selections, shift+alt+up up selection? Why does it need to be different!?

**Comment by sngreen** [comment]
Is it even possible to copy the keyboard binding file from one OS to the other? - why should not it be?
