### ISSUE TITLE
[folding] Folded block comments should show */

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3350]
In order to be consistent with folding braced functions.

![image](https://cloud.githubusercontent.com/assets/2193314/13258783/6e965e9a-da09-11e5-80a3-c3fb4de97d85.png)

**Comment by aeschli** [comment]
Setting as an enhancement as IMO what we have now is consistent in that what's folded are all indented lines. The folding strategy is not language aware, e.g. doesn't know that it's folding a comment. It just happens that Javadoc comment styles indent every line after the first with a space.

**Comment by aeschli** [comment]
Closing as out of scope for now. It's a topic again once we have #3422
