### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by johnashu** [Microsoft/vscode#33504]
- VSCode Version: 1.15.1
- OS Version: windows 10

Steps to Reproduce:

1. install python linting : https://github.com/DonJayamanne/pythonVSCode
2.

Reproduces without extensions: No

THe following extension:
https://github.com/DonJayamanne/pythonVSCode

returns the Errors:

Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.onExit @ extensionHost.ts:378
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
extensionHost.ts:386 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ extensionHost.ts:386
(anonymous) @ extensionHost.ts:196
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by alexandrudima** [comment]
Moved to https://github.com/DonJayamanne/pythonVSCode/issues/1187

@DonJayamanne If you can help in figuring out what causes the extension host process to crash, I'd be happy to try to alleviate that on our side. I've installed the extension and it seems to be working OK for me.
