### ISSUE TITLE
Allow to fix tabs (like pinning in Chrome)

### ISSUE THREAD

**Issue by lucas-viewup** [Microsoft/vscode#33509]
A interesting thing I see in browsers, specially Google Chrome, is the feature to fix tabs. It would be possible to implement it in Visual Studio Code? Sometimes I close by mistake the open tabs of editor. Thanks!

**Comment by ramya-rao-a** [comment]
@bpasero How is this different from #12622?

**Comment by mjbvz** [comment]
Closing as duplicate of #12622
