### ISSUE TITLE
Not getting terminate event from node when reload EH

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33507]
1. Start EH debugging
2. Reload the window you are debugging
3. Notice the debug adapter is not sending a `terminted` event which I would expect

Everything is still working fine but this could help me clean some code on the vscode side

Also in this milestone we changed how the EH exits, here's a code pointer
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostMain.ts#L27

**Comment by roblourens** [comment]
This is what I see in logs, immediately after pressing "reload"

```
From client: disconnect({"restart":true})
Terminated: Got disconnect request
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"event","event":"terminated"}
To client: {"seq":0,"type":"response","request_seq":8,"command":"disconnect","success":true}
```

So it looks like it is sending a terminated event? How are you debugging it?

**Comment by isidorn** [comment]
@roblourens seems to work fine now for me. False alarm, sorry. I will look more in debt week to simplify the process on the vscode side

fyi @weinand
