### ISSUE TITLE
Elementary OS: opening a folder doesn't update window title

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33506]
- make sure that VS Code reopens the project on start
- launch VS Code 

Observe the windows title: it should show the project folder name

- use "Open Folder" to open a different project

Observe: the windows title does not reflect the new name

**Comment by bpasero** [comment]
I can reproduce. However the title appears as soon as I maximize or minimize the window so I suspect an upstream issue with Electron.

**Comment by mtsh1000** [comment]
this is fixed in Electron 2.0.4

**Comment by bpasero** [comment]
@mtsh1000 could you verify this with the same distro?

@weinand any chance you can try?

**Comment by weinand** [comment]
This seems to work in VS Code Insiders:

![2018-08-06_14-32-56](https://user-images.githubusercontent.com/1898161/43716766-9ed63e70-9985-11e8-847e-ae9a57db34df.png)
