### ISSUE TITLE
creating an empty dockerfile immediately shows an error 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33512]
testing #33053:

- launch VS Code on a new project
- create a new dockerfile

Observe:
![2017-08-30_13-01-57](https://user-images.githubusercontent.com/1898161/29871546-722b777e-8d8c-11e7-8311-4a0bb005d1c0.png)

This is not a nice user experience.

**Comment by rcjsuen** [comment]
Hi, @weinand. Thank you for testing the vscode-docker extension. An identical issue was reported in [Microsoft/vscode-docker#114](https://github.com/Microsoft/vscode-docker/issues/114). Can we continue the discussion there?

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-docker#118
