### ISSUE TITLE
Add an `isInsiders` flag

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33518]
I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-code) for switching between Code and Code Insiders while keeping the same project and file open.

It exposes 2 commands: `Open in Code` and a `Open in Code Insiders`.

But it doesn't make sense to trigger `Open in Code` from Code and `Open in Code Insiders` from Code Insiders.

I'd like to properly hide those commands from the command palette, but in order for doing that I need a new `isInsiders` flag, so that I can write the following:

```js
"commandPalette": [
  {
    "command": "openInCode.open",
    "when": "isInsiders"
  },
  {
    "command": "openInCode.openInsiders",
    "when": "!isInsiders"
  }
]
```

**Comment by jrieken** [comment]
You can do that yourself with `env.appName` and the setContext command, see #10471

**Comment by fabiospampinato** [comment]
That's awesome, thanks for the tip.
