### ISSUE TITLE
Funky wording for code action

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33511]
re  #33282

* have code like this `const six = 1 + 2 + 3;`
* be on one of the numbers
* the code actions reads "extract function into global scope" which is misleading because I am not on a function, I'd prefer "extract *as* function..."

<img width="541" alt="screen shot 2017-08-30 at 14 22 04" src="https://user-images.githubusercontent.com/1794099/29872163-aaca6c28-8d8e-11e7-9a94-9294bdfd5774.png">

**Comment by mjbvz** [comment]
Agreed. I've opened https://github.com/Microsoft/TypeScript/issues/18176 to discuss this with TypeScript

Closing as upstream
