### ISSUE TITLE
Incorrect brackets match in markdown text

### ISSUE THREAD

**Issue by flily** [Microsoft/vscode#33513]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
shell-format|fox|1.0.0
MagicPython|mag|1.0.12
cpptools|ms-|0.12.3
python|tht|0.2.3
shellcheck|tim|0.1.0

---
I was writing a markdown file, and found the right bracket matching incorrect  to the bracket in a code string. The text i wrote is shown as followed.

```
By searching code with `pcregrep` (with regex `\bmain\s*\(`)
```

The last right bracket did not match the first one, but the one in regex.

I have try some similar case in C code but it works well. I think there may be something special that forget to make effect on markdown file.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
In the language agnostic bracket matching algorithm, strings, regular expressions and comments are ignored. 

We recognize these syntactical constructs if the scope name contains: `string`, `regex` or `comment`. Currently, these are not configurable. It is implemented [here](https://github.com/Microsoft/vscode-textmate/blob/d5cdb341100dd5ee5d7188d9ba900faa23f68374/src/grammar.ts#L275).

In this case, the markdown grammar does not identify the region between `` ` ``s as either of these and the bracket matching algorithm proceeds to attempt to match brackets inside that region.

<img width="805" alt="screen shot 2017-08-30 at 15 19 07" src="https://user-images.githubusercontent.com/5047891/29874394-eb74f4a2-8d96-11e7-8359-b1645c9e47aa.png">

@mjbvz I leave it up to you if you'd want to sneak in any scope name in the `.md` grammar that contains the text `string` in it for the inline markup case. e.g. `markup.inline.raw.markdown` => `markup.inline.raw.string.markdown`, etc.

**Comment by mjbvz** [comment]
Thanks @alexandrudima! This sounds like a good suggestion. I'll look into this for September
