### ISSUE TITLE
API for detecting Insiders version

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33516]
I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix) for installing .vsix files with a right click, under the hood it calls `code --install-extension`, therefor it doesn't work if triggered from Code Insiders, where it should instead call `code-insiders --install-extension`.

In order for this to work properly I need an API for detecting if the extension is running inside Code or Code Insiders.

**Comment by jrieken** [comment]
You should use [`env.appName`](https://github.com/Microsoft/vscode/blob/a8a81c6832d6d6a344153fa8e52af0eb9b0ba620/src/vs/vscode.d.ts#L3971) for this. That's the only hint we  have (externally/interally) because insiders is just another distribution.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion.
