### ISSUE TITLE
code helper 

### ISSUE THREAD

**Issue by woshichenxi2003** [Microsoft/vscode#33515]
- VSCode Version: <code>Code - Insiders 1.16.0-insider (1c6f2f9a8012565adcc50616c3aa90cb444e8797, 2017-08-23T05:10:58.701Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)</code>
- Memory (System): <code>8.00GB (0.24GB free)</code>
- Memory (Process): <code>203.07MB working set (0.00MB peak, 165.68MB private, 113.01MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|87|
|main|app.isReady => window.loadUrl()|316|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|489|
|renderer|require(workbench.main.js)|584|
|renderer|-> of which require() node_modules|115|
|renderer|create extension host => extensions onReady()|473|
|renderer|restore viewlet|0|
|renderer|restore editor view state|501|
|renderer|overall workbench load|665|
|main + renderer|start => extensions ready|1983|
|main + renderer|start => workbench ready|2153|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`e838_main.cpuprofile.txt`
-`e838_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
> ⚠️ Make sure to attach these files from your home-directory: ⚠️
> -e838_main.cpuprofile.txt
> -e838_renderer.cpuprofile.txt

How about this?
