### ISSUE TITLE
Long line with ligatures takes a long time to paint decorations

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33525]
![screen shot 2017-08-30 at 17 26 16](https://user-images.githubusercontent.com/1926584/29880557-5923ecc2-8da8-11e7-9799-eb61e139efea.png)

Have ligitures turned on
```json
"editor.fontLigatures": true,
```

`
saddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appenddata to appendde
`

**Comment by alexandrudima** [comment]
This does not reproduce with our default font family, I think it is specific to using Fira Code, which @isidorn was using.

**Comment by alexandrudima** [comment]
The slowness is caused by the rendering of the selection highlight:

![image](https://user-images.githubusercontent.com/5047891/45672772-4d50e300-bb29-11e8-9a67-c0a728382218.png)

Because of ligatures, we don't split the large token into multiple ones and then reading the offsets takes a very long time for Chromium. I will look into introducing artificial break points around spaces, since we cannot split in the middle of words (given we could break ligatures).

**Comment by alexandrudima** [comment]
With the change to split large tokens, this is 10x faster, but still feels a bit sluggish. I think that is good enough.

**Comment by isidorn** [comment]
Feels snapier -> verified
