### ISSUE TITLE
Cache (and other similar folders) are placed within %APPDATA% rather than %LOCALAPPDATA%

### ISSUE THREAD

**Issue by dcsprior** [Microsoft/vscode#33527]
On Windows, within %APPDATA%\Code\ are the following folders
- Cache
- CachedData
- GPUCache
- Local Storage

These can be relatively large (by the standards of a Windows roaming profile) - to the extent that on a corporate machine where the size of Roaming Profile is limited by Group Policy, I'm forced to delete them in order to be able to logoff any sync profile.

Their names suggest that they instead belong within %LOCALAPPDATA%

- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.1

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#3884
