### ISSUE TITLE
Automatic semicolon append at end of line in JavaScript/TypeScript

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33522]
A feature request, probably involving the tsserver.

When I enter a new line of code, maybe through IntelliSense, it would be great if a semicolon could automatically be appended to the current line.

Not sure what good preconditions are, maybe when inserting a function call through IntelliSense with return type `void` the tsserver could append a semicolon to the closing parenthesis of the call.

**Comment by mjbvz** [comment]
This sounds like a better fit for TSlint, possibly with autofix enabled too. Would the [semicolon rule](https://palantir.github.io/tslint/rules/semicolon/) work for this?

**Comment by chrmarti** [comment]
Autofix on save might be too invasive. I was thinking of automatic appending the semicolon only on the current line while you type. So it is not going to happen after you type and hit Ctrl+S (which seems unnatural with autosave enabled), but right when your focus is still on that line of text.

**Comment by mjbvz** [comment]
Do any other editors/tools do this? My feeling is that automatically adding semicolons would be more invasive / potentially annoying than autofix on save but its hard to say without a prototype to try out

**Comment by chrmarti** [comment]
Eclipse does it for Java (although its not enabled by default IIRC).

**Comment by yume-chan** [comment]
I prefer the way that Visual Studio does for C# files:

1. When the line is nearly valid (have matching quotes and braces).
2. No matter where your cursor is, even in the middle of the line.
3. Press `Shift` + `Enter`
4. VS will append the semicolon (if needed), and move your cursor to the next line.

**Comment by TeachMeAnything** [comment]
![2017-11-03_01-13-27](https://user-images.githubusercontent.com/28842311/32356274-580787e0-c034-11e7-968d-e1d7df5613cc.gif)
Is this implemented yet because I'm experiencing some weird semicolon issues when copy pasting.

**Comment by mjbvz** [comment]
@TeachMeAnything No. Do you have any extensions installed that could be causing this?

**Comment by TeachMeAnything** [comment]
Not really. I just tried it without extension and then activated one after another (with refreshing ofc). Now they are all enabled again and I no longer have this issue. If it helps someone experiencing the same the extensions I used were:  jsdoc, auto rename tag, eslint, insert date string, path intellisense, prettier, sublime keymap and some others. Unfortunately, I can't reproduce the behaviour.

**Comment by maqic** [comment]
![kapture 2017-11-07 at 14 55 08](https://user-images.githubusercontent.com/1974254/32480871-717b9d36-c356-11e7-9c1b-c29bd933766e.gif)
@mjbvz @TeachMeAnything I met the same problem

osx: 10.12.6
vscode: 1.17.2 (1.17.2) b813d12980308015bcd2b3a2f6efa5c810c33ba5

**Comment by nathanbrizzee** [comment]
Please provide a way to turn off automatic semicolons.  It breaks the linter for vuejs files when it forces a semicolon at the end of every JavaScript line.  The linter does not want semicolons in vue files anywhere.

**Comment by maqic** [comment]
https://github.com/prettier/prettier-vscode/issues/257#issuecomment-342468948

**Comment by mjbvz** [comment]
Closing as this is more suited to an extension such as TS lint
