### ISSUE TITLE
findFiles API should not get default excludes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33528]
It seems that all API calls inhert the configured exclude settings which isn't what all extensions want.
Start reading here: https://github.com/Microsoft/vscode/issues/31882#issuecomment-326009834

**Comment by jrieken** [comment]
fyi @joaomoreno

**Comment by bpasero** [comment]
I also think we should be careful about changing the defaults for performance reasons. @roblourens are we using ripgrep for the findFiles call or our old slow find mechanism?

**Comment by roblourens** [comment]
The old one, it takes the same path as quickopen.

**Comment by eamodio** [comment]
I just hit this case where `findFiles` is getting the default excludes (blocking me for searching for a file in the `.git` folder). I honestly don't mind that the default changed, but the fact that you can't override the default excludes by passing `null` or `''` or something feels like a much bigger issue, imo.

**Comment by jrieken** [comment]
>  but the fact that you can't override the default excludes by passing null or '' or something feels like a much bigger issue, imo.

That.

**Comment by jrieken** [comment]
Moving this to December so that we can try this a little but my plan is to not-inherit default excludes when they are set to `null` via the API

**Comment by jrieken** [comment]
Refined API is allowing `null` for the exclude pattern ` exclude?: GlobPattern | null`.

```ts
export function findFiles(include: GlobPattern, exclude?: GlobPattern | null, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>;
```
