### ISSUE TITLE
Debounce on file read

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33529]
If a file is getting updated every 500ms and we need 1000ms to read that file we end up in a spot where we have too many file reads since they do not get canceled.
Optimally we would cancel an outdated file read if we need to read that file again.

Example program / large file can be found here https://github.com/Microsoft/vscode/issues/33378

fyi @alexandrudima

**Comment by alexandrudima** [comment]
I've just checked the window also freezes on stable, so it is not a regression caused by preserving the undo stack in this case.
