### ISSUE TITLE
Compare Active File with... is too limited

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33526]
The 'Compare Active File with'-feature is a little limited as it only allows to compare with previous files. That will drive you up the wall if you are looking for something else and actually never pained attention to this limitation

**Comment by bpasero** [comment]
Yeah, I was waiting for someone to find out about it.

**Comment by cleidigh** [comment]
@bpasero 
Since I was just in this code with my last PR if you want to put this in the help-wanted category (and have a couple of bullet point goals), I'd be happy to work on it in September.

**Comment by bpasero** [comment]
@cleidigh sure why not. I think the main issue here is that the file picker does not have API to be opened and having an item picked for further use. Using the history is a workaround for that.

**Comment by cleidigh** [comment]
@bpasero 
Will review and question after I finish the notification navigation.

**Comment by cleidigh** [comment]
@jrieken 
@bpasero 
I started investigating work on this and don't want to go off the rails.
Is it correct that having history+progressive search of all workSpace files ie default IQuickOpenService.show() would be sufficient?
If so:
- Modify show() to have a pick promise return option
- Adding a Mode.PICK and a openOnSelected = true default option, with false returning a pick
- Second option: modify pick()
- Third option: new function essentially across between show and pick

I have most of the first option prototyped, working on returning a string/IOpenPickEntry .

Thoughts?

**Comment by bpasero** [comment]
@cleidigh yeah, it would probably be a good start to let [`IQuickOpenService.show()`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/quickOpen/common/quickOpen.ts#L141) return the selected item and then using that method from the compare action. One thing to keep in mind is that the user can change the quick open items by typing one of the prefixes (e.g. `@` for symbol outline), which means the method might not always return a file after all.

**Comment by cleidigh** [comment]
@bpasero 
Thanks.  Yes I see that the show has a lot of different execution paths.  I know this is a critical component
so I want to make sure I don't miss anything up. 

Trying to determine the best location to set and pass back the pick/promise.  I can do it
easily in elementSelected but I think it's more appropriate in onOk callback in the controller.
Haven't gotten that to work yet.  Everything else is more straightforward and working.

 Will probably have a couple questions to make sure I do it in a good manner after the weekend.

**Comment by cleidigh** [comment]
@bpasero 

Addressed with PR #35272
