### ISSUE TITLE
Workspace Settings missing 'Edit' action in multi-root mode

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33535]
- VSCode Version: Code - Insiders 1.16.0-insider (34cc9f2209be766d5be30a6ecdbb41f5e81fd56b, 2017-08-30T05:11:42.435Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Testing #33292

Steps to Reproduce:

1. Add setting to workspace settings in multi-root mode
2. Observe: The editable settings do not have the 'edit' action in the gutter that the user and folder settings have.

**Comment by sandy081** [comment]
Yeah it is because of the format Workspace settings file has in MR workspace.
