### ISSUE TITLE
Unable to set up development environment

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#33531]
- VSCode Version: git HEAD
- OS Version: Windows 10 x64

Steps to Reproduce:

I followed https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source. When running `scripts\npm.bat install`, I get the following error:
```shell
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.

> code-oss-dev@1.16.0 preinstall D:\vscode
> node build/npm/preinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\vscode\build\npm\preinstall.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
code-oss-dev@1.16.0 D:\vscode
`-- d@1.0.0  extraneous

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.16.0 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
```

**Comment by mjbvz** [comment]
Did you just clone the git repo? Does the file `D:\vscode\build\npm\preinstall.js` exist?

**Comment by oliversalzburg** [comment]
I'm sorry, I must have overlooked your response.

Yes, it's a straight clone of the repo and the file does exist. However, the issue must have resolved itself somehow, because I can no longer reproduce it now. I even cloned a fresh copy and tried again. Works fine.
