### ISSUE TITLE
not work when modify editor.fontSize to default

### ISSUE THREAD

**Issue by cuiyongjian** [Microsoft/vscode#33537]
- VSCode Version: 1.15.1
- OS Version: Mac OS sierra  10.12.3

Steps to Reproduce:
1.  open the preference setting with cmd+,
2.  change the editor.fontSize to 14 (default is 12), you can see the editor fontsize has change
3.  Then i change the editor.fontSize to the original 12,  but you can see it keep  14
4.   Only when i close the setting page ,  and reopen it , the font-size will take effect

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I have just tried it out and cannot reproduce.

**Comment by sandy081** [comment]
I cannot reproduce neither in stable nor insiders.

@cuiyongjian Can you please try in insiders https://code.visualstudio.com/insiders and check

**Comment by alexandrudima** [comment]
Perhaps there is a missing save, or we only save on close ... ?

**Comment by cuiyongjian** [comment]
@alexandrudima @sandy081 

Tody I have tryed the insider version,   It seems to have fixed the problem.  Thank you! 
---------

And now I paste the picture of my symptoms with stable version 1.15:


1. below is the pic when i set nothing (it is really 12px):
![image](https://user-images.githubusercontent.com/3937196/29995042-dfa3e7e6-9011-11e7-83a5-d34f8feb4ed3.png)


2. this is the pic when i set font-size to 14:
![image](https://user-images.githubusercontent.com/3937196/29995027-9bba0da8-9011-11e7-8715-ba8a73981d14.png)
you can see it changed to 14px

3. below is the pic when i reset to 12
![image](https://user-images.githubusercontent.com/3937196/29995034-c23f6112-9011-11e7-9fa3-dee7c3ba99eb.png)

it keep 14px.   


--------

**Comment by ant31** [comment]
Have you check that you don't have `fontSize` configured in both 'workspace setting' and 'user setting'

**Comment by cuiyongjian** [comment]
Today, i retry it with stable version 1.15.1.   It is worked.   it is really Strange 奇怪的.
