### ISSUE TITLE
Single inferred JS/TS project when workspace not saved yet

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33538]
- VSCode Version: Code - Insiders 1.16.0-insider (34cc9f2209be766d5be30a6ecdbb41f5e81fd56b, 2017-08-30T05:11:42.435Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Testing #33281

Steps to Reproduce:

1. Open two folders, do not save workspace
2. The second folders sees declarations from the first
3. This goes away once the workspace is saved (which reloads the window)

![image](https://user-images.githubusercontent.com/9205389/29884508-987bfb34-8d68-11e7-9a88-128c93a88872.png)

**Comment by mjbvz** [comment]
Reproduced by:

1. Start with a unsaved workspace with a single folder.
2. Add a second folder to the workspace so that a reload is not triggered

**Comment by mjbvz** [comment]
Seems to have been fixed by the workspace API changes we made
