### ISSUE TITLE
Latest insiders crashing while typing in WSL bash terminal

### ISSUE THREAD

**Issue by jcjolley** [Microsoft/vscode#33539]
- VSCode Version: Code - Insiders 1.16.0-insider (34cc9f2209be766d5be30a6ecdbb41f5e81fd56b, 2017-08-30T05:23:44.557Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
bracket-pair-colorizer|Coe|0.10.8
vscode-markdownlint|Dav|0.10.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
EditorConfig|Edi|0.9.4
tslint|eg2|0.17.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
docthis|joe|0.4.8
Angular2|joh|2.4.3
vscode-codemetrics|kis|1.9.3
typescript-hero|rbb|1.4.0
autoimport|ste|1.2.2
language-stylus|sys|1.7.3
vim|vsc|0.9.0

---

Steps to Reproduce:
1. Be typing in the VS Code terminal connected to WSL bash
2. Get the crash at the bottom

This is an intermittent bug, and I haven't figured out exactly the trigger yet.

Reproduces without extensions: IDK

![image](https://user-images.githubusercontent.com/2086176/29884882-0eb5d7c6-8d72-11e7-9b20-0e74fbc1d562.png)

**Comment by Tyriar** [comment]
I just now discovered and fixed this issue https://github.com/Microsoft/vscode/issues/33541 😄 

Sorry about the hassle.

**Comment by jcjolley** [comment]
@Tyriar No worries!  Thanks for the quick fix! :D
