### ISSUE TITLE
Task output disappearing from integrated-terminal

### ISSUE THREAD

**Issue by seanybaggins** [Microsoft/vscode#33544]
- VSCode Version: 2.0.0
- OS Version: Linux

Steps to Reproduce:

1. Create a helloWorld.c file in its own directory.  Code is as follows.

```
# include <stdio.h>

int main(){
    printf("\n hello world \n");
    return 0;
}
```

2. In the same directory as the helloWorld.c create the task.json file by going to the top ribbon and selecting Tasks -> Configure Tasks and pasting the code below.

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        { 
            "taskName": "Compile hello world",
            "type": "shell",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared"
            },
            "command": "gcc",
            "args": [
                "helloWorld.c"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        },
        {
            "taskName": "Run compiled file",
            "command": "./a.out",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "panel": "new",
                "reveal": "always",
                "focus": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}
```

3. Save the tasks.json file and press Ctrl+Shift+B.
4. Select Compile hello world
5. press Ctrl+Shift+B
6. Select Run compiled file
7. Observe that _hello world_ is briefly displayed in the integrated terminal and then disappears

Extensions:
C/C++
Code Runner
Python
vscode-icons

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
I can't reproduce this. Here is what I see under Linux (Fedora & Gnome)

![cast](https://user-images.githubusercontent.com/1931590/29915933-9288a5da-8e3d-11e7-9be6-53f51d5e93a7.gif)

Any additional information you can provide on how to reproduce this. Anything special about the shell you are using.

**Comment by seanybaggins** [comment]
Hi dbaeumer,
     I do not believe there is anything special with the shell (I'm kinda new to Linux). I just recently did a dual boot with Linux mint 17.1 cinnamon and Windows 10. Perhaps this is a problem specific to the distribution of Linux. Is there any specific command I could run in the terminal to provide you with more information?

@dbaeumer

**Comment by is73** [comment]
I have the same problem as @seanybaggins, Archlinux, vscode version 1.5.1

In 1.16.0-1504156726_amd64.tar.gz it works and terminal waits for pressing a key.

**Comment by dbaeumer** [comment]
I tested this with the latest inside as well. @seanybaggins could you try this on the latest insider. Or wait for the new stable coming out soon.

**Comment by seanybaggins** [comment]
... interesting. It appears this is not an issue in vs code insiders. My plan is to test this functionality again in vs code when the update comes out. Thanks for your help @dbaeumer.

**Comment by nukiebaba** [comment]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3
rust|rus|0.2.2

---

I'm running into this issue and solved it by putting in a delay.

Steps to Reproduce:

1. 
{
    "version": "2.0.0",

    "tasks": [
        {
            "taskName": "compile",
            "type": "shell",
            "command": "time ${workspaceRoot}/build.sh",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

2. Make a build.sh file that sleeps for some time, test at 0.10s and 0.25s.
#!/bin/bash
sleep 0.13

3. If the total time is less than .13s - .15s, the "Task - compile" terminal is destroyed immediately. When the bash script is compiling c code with clang, immediately destroyed when total time under .18s - .20s.


Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@nukiebaba thanks. Now it rings a bell. This is a dup of a issue that is in the terminal and got fixed for the next release.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/32276
