### ISSUE TITLE
Selecting setting + suggestions can corrupt value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33548]
![aug-30-2017 14-08-30](https://user-images.githubusercontent.com/323878/29895114-c59693b2-8d8c-11e7-9d4a-6b584b4de566.gif)

- Open settings
- Add `files.eol`
- Select the value, with the cursor left to the right of the selection, trigger suggestions, accept the suggestion
  - The result is missing characters
- If the cursor goes to the left side of the selection, it replaces the value as expected.

Also reproes in 1.15.2

**Comment by jrieken** [comment]
actually a duplicate of  #31199
