### ISSUE TITLE
[Extension API] vscode.workspace.textDocuments does not return all documents at the beginning

### ISSUE THREAD

**Issue by mkloubert** [Microsoft/vscode#33546]
I am using `vscode.workspace.textDocuments` to detect all opened and visible text documents.

At the beginning, when I start debugging my extension, I have 3 open text documents, lets say `test_1.php`, `test_2.php`, `test_3.php`.

Now when I access `vscode.workspace.textDocuments`, I only get the active one (in that example `test_1.php`).

When I click on another one (`test_2.php`) and access `vscode.workspace.textDocuments` again, I get the new active document and the previous one (`test_1.php` and `test_2.php`).

When I click on the last, remaining one (`test_3.php`) and access `vscode.workspace.textDocuments` again, I get the list of all documents.

But it seems to depend on the situation, which document has been active at the beginning or has been activated after I have clicked on it.

Is this a bug or a feature?

If a feature: Is there another way to access an up-to-date list of all opened documents?

**Comment by jrieken** [comment]
In what version does this happen?

**Comment by mkloubert** [comment]
@jrieken 

Oh, sorry: **1.15**

**Comment by jrieken** [comment]
> At the beginning, when I start debugging my extension, I have 3 open text documents, lets say test_1.php, test_2.php, test_3.php.

What do you mean by that? Right after start? Are those tabs or actual editors, e.g. three editor columns filled or one column with 3 tabs?

**Comment by mkloubert** [comment]
@jrieken 

Right after start. 3 tabs inside 1 column.

**Comment by jrieken** [comment]
Ok, so right after start the tabs are just restored, not the documents. Only the visible documents exists in memory, the other tabs are just UX gestures that will trigger document loading.
