### ISSUE TITLE
Caps for emphasis doesn't look right in folder settings (and small font size)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33542]
![image](https://user-images.githubusercontent.com/2193314/29889270-71b5563e-8d78-11e7-89bd-f9818bcbf242.png)

Why not just "Folder Settings - xterm.js" or "xterm.js - Folder Settings"? The small font on "Folder Settings" may also be smaller than any other text in the UI.

**Comment by sandy081** [comment]
This was the initial design to show User Settings and Workspace Settings in CAPS. I followed the same for Folders. I am not sure if there was any heurisitc around it. No strong opinions.

Small font for `Folder Settings` label is to differentiate from the Folder name. IMO this looks good.

**Comment by sandy081** [comment]
Closing this as there is no action will be taken.
