### ISSUE TITLE
Git Message Help Text not displaying when Exceeding 50 Characters

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#33549]
- VSCode Version: 1.15.1
- OS Version: Win 7, Win 10

Steps to Reproduce:

1. Type git message longer than 50 characters
2. Observe tooltip/warning is not displayed as it was previously.

Reproduces without extensions: indeterminate, running this in my command line did nothing

**Comment by joaomoreno** [comment]
#21144
