### ISSUE TITLE
Ruller position is +1 from my expectation

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#3354]
#3233

Multiple rulers work great and look great.  

However, when I configure a set of rulers e.g. [20,40,90,140] I expected the ruler to land on that column not the one after that.  This could be by design but I found it a little confusing as I wanted to know that once I reached the ruler I had hit column 20 vs 21.

![screen shot 2016-02-23 at 8 57 03 am](https://cloud.githubusercontent.com/assets/1051190/13259251/73afbcb2-da0b-11e5-87a1-164905a6139e.png)

**Comment by Tyriar** [comment]
Seems to behave the same as Atom's default wrap-editor as well as the community-based [multi-wrap-editor](https://github.com/lexicalunit/multi-wrap-guide).

**Comment by alexandrudima** [comment]
@seanmcbreen 

I think a ruler at 20 should help me keep my lines <=20 characters, therefore its positioning after the specified column.
