### ISSUE TITLE
VSCode crashes when editing heavy files

### ISSUE THREAD

**Issue by TheGrimSilence** [Microsoft/vscode#33543]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Tried to look into a minified javascript file (which is 200k+ lines unminified)
3. Tried to tidy the code manually via 'Search/Replace' (extensions stopped working before)
2. Scrolling and editing both lead to crash within seconds

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@TheGrimSilence Can you please share the file that causes the crash or a file that is very similar to the one you have (even generated if needed) that also reproduces the crash ?

**Comment by TheGrimSilence** [comment]
https://d3e54v103j8qbb.cloudfront.net/gen/js/webflow-designer.min.11db48d80c.js

The file is too large to paste or link. It's 7.93GB and trying to tidy it only causes further errors with VSCode.

**Comment by TheGrimSilence** [comment]
I've finally been able to tidy the code which is 366,006 lines total. However, it's been 30 minutes but VSCode still hasn't added syntax highlighting.

![webflow-designer js visual studio code 9_3_2017 6_43_53 pm](https://user-images.githubusercontent.com/11479772/30007243-3bd510d2-90bf-11e7-985b-19236b453159.png)

**Comment by alexandrudima** [comment]
@TheGrimSilence Syntax highlighting is disabled for files over 300k lines in order to save memory. I think you might have installed some extension that causes extreme slowness for large files. Does the slowness reproduce when disabling all extensions ?
