### ISSUE TITLE
Unable to use "Ctrl + Shift + 1" keyboard shortcut

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#33545]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|4.4.3
tslint|eg2|0.17.0
debugger-for-chrome|msj|3.2.0
vscode-icons|rob|7.12.0

(1 theme extensions excluded)

---

A while back, I set my "Sort Lines Ascending" keyboard shortcut as "Ctrl + Shift + 1". I noticed now that it's no longer working. I thought maybe my shortcuts got reset, so I went to set it again, but I saw my shortcut exists. I tried resetting by trying to enter the keystrokes again, but it's not recognizing the "1".

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@martellaj I see you are reporting two issues

1. Keyboard short cut "Ctrl+Shift+1" for "Sort Lines Ascending" is not working. Try assigning a different key binding and see if that works. If you want to reset it to "Ctrl+Shift+1" and you cannot do it from the Keyboard Shortcuts editor, you can fallback to open the JSON file (link is available in the editor) and update it.

2. "1" is not recognised in Keybindings Editor. It is working for me. See the attached video 

![kapture 2017-08-31 at 9 44 31](https://user-images.githubusercontent.com/10746682/29912194-1caa552c-8e31-11e7-9829-0cd2ad98014d.gif)

Not sure key "1" is special in Windows. @alexandrudima Any idea?

**Comment by alexandrudima** [comment]
@martellaj If you open the define keybinding widget, does VS Code receive the keydown event for `ctrl+shift+1` ?
