### ISSUE TITLE
Auto-reload of files sucks

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#33559]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. spend an hour editing a file and save it
2. accidentally clobber that file on disk by copying over it 
3. Notice that VS code cleverly automatically reloads the bad file losing all your work.
4. Even File->Revert command does nothing.

Reproduces without extensions: Yes

So it would be great if at least you could make it configurable whether to automatically reload files that were changed on disk or NOT.  (like VS does).  Thanks.  Twice now I've lost hours of work due to this "feature".

**Comment by bpasero** [comment]
With our upcoming release you are able to undo a change that occurred from outside VS Code by simply invoking the Undo command. That helps to go back into the state you had before.

Related: https://github.com/Microsoft/vscode/issues/30702, https://github.com/Microsoft/vscode/issues/20876, https://github.com/Microsoft/vscode/issues/14298

**Comment by lovettchris** [comment]
Perfect, thanks!!

**Comment by lovettchris** [comment]
I just got the update with this fix in it -- now that is what I call customer love :-)   Excellent work!
