### ISSUE TITLE
Does 'path intellisense' for 'node_modules' require a third party plugin?

### ISSUE THREAD

**Issue by loveholly** [Microsoft/vscode#33556]
- VSCode Version: `1.15.1`
- OS Version: `macOS Sierra 10.12.6`

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
What is "path Intellisense"?

**Comment by loveholly** [comment]
![image](https://user-images.githubusercontent.com/5133856/29902351-3b9091a0-8e30-11e7-9690-598bd834742f.png)
This functionality only works on my end supported by a plugin called `npm intellisense`. So my question is `Does vscode itself support this feature ?`
@rcjsuen

**Comment by rcjsuen** [comment]
By default VS Code seems to parse my `package.json` file and offers some suggested module names based on that.

**Comment by loveholly** [comment]
In my opinion, `vscode` should support this functionality by itself rather than a plugin. But now it doesn't work on my end, even though I disabled all the plugins. I'm not sure whether this is a bug or not.

**Comment by mjbvz** [comment]
This should already be included but you currently have to manually trigger the suggestions using `ctrl` + `space`

See #23962 for more info about this
