### ISSUE TITLE
Can't get members info of a instance property created by another constructor

### ISSUE THREAD

**Issue by loveholly** [Microsoft/vscode#33557]
- VSCode Version: `1.15.1`
- OS Version: `macOS Sierra 10.12.6`

Steps to Reproduce:
This is the code snippet:
![image](https://user-images.githubusercontent.com/5133856/29902293-c2ae1d66-8e2f-11e7-894c-c138e1e7f22a.png)

As you can see above, I can't read any property or function of `this.starter` which is created by `koa` constructor.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
Your `starter` field is of type `any` because you didn't declare its type.

TypeScript only infers type for declare and assign.

```` TypeScript
class App {
    public starter = new Koa(); // ok
    public anything;

    constructor() {
        const app = new Koa(); // ok
        this.anything = new AnyThing(); // not work
    }
}
````

**Comment by mjbvz** [comment]
You need to annotate the type for TypeScript: `public starter: Koa`

Otherwise it defaults to `any`

**Comment by loveholly** [comment]
thx
