### ISSUE TITLE
[folding] unfold when typing on first line

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33553]
This might be known or tracked somewhere else, but I don't see it called out explicitly anywhere...

- Fold a region of code
- Put the cursor at the end of the folded line
- Press enter and type
  - The typed stuff is visible 
- Once I stop typing for a second, the typed stuff disappears and is under the fold

It seems like pressing enter at the end of a folded line should either unfold, or add a newline after the folded section.

![aug-30-2017 16-21-41](https://user-images.githubusercontent.com/323878/29899292-59ce8744-8d9f-11e7-8392-e2156ce91020.gif)

**Comment by aeschli** [comment]
Pressing enter at the end of a folded line will unfold the region: 
Fixed by https://github.com/Microsoft/vscode/commit/85d5031b60651e02b26d97fe92e0fca1287244db
