### ISSUE TITLE
Error in 64bit studio Code unable to find Python.

### ISSUE THREAD

**Issue by GScully** [Microsoft/vscode#33551]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typings-installer|ben|0.2.0
npm-intellisense|chr|1.3.0
python|don|0.7.0
vscode-npm-script|eg2|0.2.0
vscode-npm|fkn|3.3.0
tfx-toolkit|har|0.1.0
vscode-tfs|iva|0.6.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1

---

Steps to Reproduce:

1. Open project in x64 VSCode that uses Python, run npm install2.
2. error -> gyp ERR! stack Error: Can't find Python executable "C:\Users\---\AppData\Local\Programs\Python\Python36-32", you can set the PYTHO
N env variable.
Python is in the path and exist. though it's 32 bit.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
What is `npm install2`? Is that from the project you are working on?
