### ISSUE TITLE
Search - Files to include/exclude path includes brackets

### ISSUE THREAD

**Issue by dariusj18** [Microsoft/vscode#33550]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
vagrant|bbe|0.5.0
vscode-svgviewer|css|1.4.2
githistory|don|0.2.3
gitlens|eam|4.4.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
coldfusion|ili|0.0.11
vscode-JS-CSS-HTML-formatter|lon|0.2.3
VS-code-drupal|mar|0.0.12
VS-code-vagrantfile|mar|0.0.5
vscode-autoprefixer|mrm|2.1.2
mssql|ms-|1.1.0
java|red|0.8.0
vscode-icons|rob|7.12.0
vscode-autohotkey|sle|0.2.1
php-ci|sma|0.2.2
vcl|tho|0.1.2
tmlanguage|Tog|0.7.1
vscode-input-sequence|tom|0.2.0
cfml-comment-tags|trs|0.2.2
lorem-ipsum|Tyr|1.0.0

---

Steps to Reproduce:

1. I have paths like "[foldername]"
2. Add "./public/[foldername]" to Files to include
3. No results
4. Add "./public/\[foldername\]" to Files to include
5. No results
6. Add "./public/?foldername?" to Files to include
7. No results (this used to work)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Covered in #16834 - still need a way to escape glob characters in those fields.
