### ISSUE TITLE
Breakpoints for uncaught exceptions do not get triggered for extension development

### ISSUE THREAD

**Issue by msafi** [microsoft/vscode#33566]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
find-word-at-cursor|mks|1.8.0
code-spell-checker|str|1.3.8
---

I'm assuming that when "Uncaught Exceptions" is checked under "Breakpoints" in the debug view, it will cause a breakpoint to get automatically set and execution will stop when an uncaught exception is encountered so that the developer can debug the issue.

That's not the behavior I'm observing. Instead, I see this in the Extension Development Host:

![image](https://user-images.githubusercontent.com/4027731/29905445-ada4f690-8dc3-11e7-9ba5-a964621ae739.png)

...and no breakpoint is set in the VS Code window where the source code is opened.

Steps to Reproduce:

1. Use `yo code` to generate an extension.
1. Open the extension in VS Code
1. Add bad code some where or throw an error
1. Run the extension with F5
1. Call the extension with `extension.sayHello`
1. No breakpoint gets triggered even though "Uncaught Exceptions" is checked (by default)

**Comment by isidorn** [comment]
@msafi please try reproducing this with vscode insiders since we have changed our debug backend for extension debugging.
https://code.visualstudio.com/insiders

If you still see the issue then @roblourens can investigate more.

**Comment by msafi** [comment]
@isidorn @roblourens I tried it in Code Insiders. Same problem.

See [this video](https://giphy.com/gifs/xT9IgEYGxwy00WBbP2/fullscreen)

**Comment by roblourens** [comment]
But the exception is caught, by vscode's code. It must be, for the error dialog to be shown. If you set "All Exceptions", you will break there.

**Comment by msafi** [comment]
@roblourens If I set "All Exceptions", I get a bunch of irrelevant breakpoints for internal VS Code that gets caught and handled. It's too much noise. Not really usable.

I feel the current design harms the extension authoring experience. For example, if you don't show the dialog or some how allow the error to propagate up so that the debugger will consider it uncaught, that will make things better.

Can't you rethrow the error after showing the dialog so that the debugger will consider it uncaught or maybe change the behavior of VS Code so that when it's an Extension Development Host and the error is generated by the extension being hosted, it doesn't catch the error?

**Comment by roblourens** [comment]
You bring up some good points, I think we can make this better. I think the best way to do that is to provide a way to not break on exceptions in code that isn't part of the user's extension, by our own definition, with the "skipfiles" feature.

@weinand "Toggle skipping file" isn't enabled for extensionHost debug, can we change that? https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L113

Debugging with "All exceptions" enable is annoying, I break on exceptions from other vscode EH code, our builtin extensions (especially TS), and other random extensions I've installed. We could introduce another special skipfiles namespace like `<eval>` and `<node_internals>`, that would cover all the EH code that isn't part of the currently debugged extension. Or a couple new ones, `<extensionhost_internals>`, `<other_extensions>`. And let users skip exceptions in those files.

**Comment by njpanderson** [comment]
Got here after searching with the exact same problem as @roblourens - Totally agree with what he's said above and it would be fantastic to be able to focus entirely on my own code even with "All exceptions" and/or "Promise rejects" checked while debugging. There's currently far too much noise with other extensions, node internals etc. being caught by the debugger.
