### ISSUE TITLE
ubuntu 16.04 debug python, press  f10 no result

### ISSUE THREAD

**Issue by lemonwx** [Microsoft/vscode#33563]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:31.163Z)
- OS Version: Linux ia32 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.3

---

Steps to Reproduce:

1. select a .py file
2. press f5 double
3. press f10 
  no result,
   
   

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the python extension https://github.com/DonJayamanne/pythonVSCode
