### ISSUE TITLE
running npm install in terminal crashing 

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33561]
Insiders on Windows is crashing fast when running `npm install` from terminal.

![image](https://user-images.githubusercontent.com/1487073/29904706-f53468f6-8dbe-11e7-959a-83118d7c0a57.png)

``` console
clone https://github.com/microsoft/vscode-website
cd vscode-website
code-insiders .
ctrl+`
npm install
```
result:

![image](https://user-images.githubusercontent.com/1487073/29904696-e6901b06-8dbe-11e7-97ab-abe91971fab0.png)

**Comment by Tyriar** [comment]
I believe I fixed this yesterday, please retry on today's build https://github.com/Microsoft/vscode/issues/33541
