### ISSUE TITLE
Color picker: when user start changing color the picker should not easily close

### ISSUE THREAD

**Issue by ghiscoding** [microsoft/vscode#33568]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  Hover over a CSS color and the color picker shows up, then move away and the picker goes away which is fine. 
2. Again do an hover over a CSS color again and this time start changing the color and if you have the misfortune of falling outside of the picker area, you lose the original color and your file is now dirty. The only way back is to do an undo (ctrl+z). It happened to me so many times that I slipped outside and lost my original color, the picker is just so small (the size is not the real culprit though) and it's so easy to fall outside.

Reproduces without extensions: Yes

Proposition:
I would rather argue that if the user starts changing the color, then it's most probably he wants to stay in the picker until he decides that the color is acceptable (or not by clicking back on the original color). If you try Chrome for example, the picker stays open until you click away. I think this could be a better approach, and/or add a "x" on the top corner... but please only implement this behavior **after** the user starts changing the color.
![2017-08-31_00-02-11](https://user-images.githubusercontent.com/643976/29905969-af19c4e4-8ddf-11e7-8efc-15ce288c1251.gif)

Compare this to Chrome developer tool, it never closes unless we click outside the picker

![I9P35TiGs1](https://user-images.githubusercontent.com/643976/137795843-cb338658-d97a-43e4-a782-b8eec5af1a4e.gif)

**Comment by iainhallam** [comment]
This has become a bit annoying for me as well; if I start changing the colour, I'd like the picker to stay around until I'm done.

**Comment by eschwartz** [comment]
As soon as I move my cursor a single pixel, the color picker closes

![2022-04-01 10 19 19](https://user-images.githubusercontent.com/1153371/161293052-09d11378-998b-4a25-9609-eb9e2b54498a.gif)


Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0

**Comment by lewallen** [comment]
> As soon as I move my cursor a single pixel, the color picker closes

I have exactly this problem the first time I click a given color box, and then it stops happening if I immediately click the color box again.

I used to think I was just being more careful the second time, but on further inspection I think this is part of the bug.

**Comment by ghiscoding** [comment]
Considering that I opened the issue 5 years ago, it doesn't look to be very high on their TODO list, which is sad considering that it's still very annoying 😓 

![image](https://user-images.githubusercontent.com/643976/189766038-f7a071cc-f28b-44d3-86c9-668957023e14.png)

**Comment by AlessandroFerrante** [comment]
Not even working for me for a week, I tried to update vscode, but nothing changes, I was wondering if you found an extension to wait for the bug resolution

**Comment by kubilayyalcinyt** [comment]
ı hate vscode

**Comment by elYanuki** [comment]
Please work on this, its should be as simple as adding some padding and changing the colose condition right?. This is just so anoying.

**Comment by aiday-mar** [comment]
Hi earlier this year we have made it that when a hover is focused, it should no longer close when hovering out of it. This applied to the color picker, and you can use this feature to keep it open. Additionally if you want to make the color picker and the other hovers disappear less quickly, you can configure the hiding delay with the setting `editor.hover.hidingDelay`. The default is 300ms but it can be increased if you wish so.
