### ISSUE TITLE
[Suggestion] Let zen mode show all opened files in the top tab

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#33562]
- VSCode Version: 1.16.0-Insiders
- OS Version: Win10

If I want to switch to another opened file in zen mode, now I have to :
1. Quit zen mode
2. Switch to another file
3. Enter zen mode again

And actually there is lots of space in the top bar of zen mode.

So it may be more convinient if there are all opened files in the top tab of zen mode.

**Comment by isidorn** [comment]
Please use the followign setting
```
"zenMode.hideTabs": false,
```
