### ISSUE TITLE
instal as Administrator,but use app as common user

### ISSUE THREAD

**Issue by astazyx1991** [Microsoft/vscode#33567]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none

i can not save my setting.

**Comment by joaomoreno** [comment]
Please install the app as your user or run the zip archive.
