### ISSUE TITLE
in Source code management,Usually,when you click the lists on the left,it will appear the relevant documents on the right, but the problem is,it won't.sometimes

### ISSUE THREAD

**Issue by chengquan223** [Microsoft/vscode#33564]
in Source code management,Usually,when you click the lists on the left,it will appear the relevant documents on the right, but the problem is,it won't.sometimes

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
path-intellisense|chr|1.4.2
cssrem|cip|0.0.3
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.14
vscode-auto-open-markdown-preview|hnw|0.0.4
canvas-snippets|hol|0.3.2
beautify|Hoo|1.1.1
docthis|joe|0.4.8
vscode-colorize|kam|0.6.3
vscode-gutter-preview|kis|0.10.0
csharp|ms-|1.12.1
vetur|oct|0.9.5
material-icon-theme|PKi|2.2.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Same underlying issue as #30323
