### ISSUE TITLE
After rename the folder, It can't work!

### ISSUE THREAD

**Issue by ancon** [Microsoft/vscode#33571]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
cpptools|ms-|0.12.3
sublime-keybindings|ms-|2.9.1
php-docblocker|nei|1.2.0
vscode-docker|Pet|0.0.16

(3 theme extensions excluded)

---

Steps to Reproduce:

1.vscode/
2.vscodes/
it can't work。

![2017-08-31_145410 vscode](https://user-images.githubusercontent.com/6762451/29910451-9be46ba4-8e5c-11e7-91d8-eb2d0991088e.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand what you renamed, and I don't understand the error message, can you translate it please?
