### ISSUE TITLE
图尔问题

### ISSUE THREAD

**Issue by mzcgithub** [Microsoft/vscode#33576]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.19.0|
|vscode-color|anseki|0.4.5|
|typings-installer|benjaminromano|0.2.0|
|GBKtoUTF8|bukas|0.0.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-markdownlint|DavidAnson|0.10.0|
|vscode-eslint|dbaeumer|1.2.11|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|EditorConfig|EditorConfig|0.6.2|
|vscode-npm-script|eg2|0.2.0|
|auto-close-tag|formulahendry|0.4.3|
|auto-rename-tag|formulahendry|0.0.14|
|vue-snippets|hollowtree|0.1.2|
|path-autocomplete|ionutvmi|1.6.1|
|docthis|joelday|0.4.7|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|prettify-json|mohsen1|0.0.3|
|js-atom-grammar|ms-vscode|0.1.13|
|debugger-for-chrome|msjsdiag|3.1.7|
|color-highlight|naumovs|2.3.0|
|vetur|octref|0.9.3|
|vue-beautify|peakchen90|2.0.4|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.12.0|
|new-moon-vscode|taniarascia|1.2.1|
|bootstrap-3-snippets|wcwhitehead|0.1.0|
|JavaScriptSnippets|xabikos|1.4.1|
|vscode-preview-server|yuichinukiyama|0.7.0|;

---

Steps to Reproduce:

1.
2.

**Comment by yume-chan** [comment]
What's your problem?
