### ISSUE TITLE
Emmet 2.0: Show custom snippet along with default snippet if match

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#33579]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:27:43.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
project-manager|ale|0.20.0
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.3
EditorConfig|Edi|0.9.4
prettier-vscode|esb|0.23.1
beautify|Hoo|1.1.1
vscode-stylefmt|mrm|2.5.0
atom-keybindings|ms-|3.0.1
vetur|oct|0.9.5
stylelint|shi|0.28.0
vscode-todo-highlight|way|0.5.9
vscode-jumpy|wma|0.3.1

---

Steps to Reproduce:

This is a weird one. I have defined the following custom snippet for Emmet:

`"mrgstart": "@include margin-start(${1:value});",`

When I type `mrg`, the snippet is not shown. It appears only when I type `mrgs`.

If I rename the snippet to `abcstart`, then it is properly shown when I type `abc`.

😵

Reproduces without extensions: Yes

**Comment by vvs** [comment]
Found multiple other cases when custom emmet snippets are now shown when their names partially entered.

It looks like it has something to do with the amount of the suggestions for the currently entered text. If the amount of suggestions is not big, then the custom snippet is shown among the suggestions. If the amount is big, the custom snippet is not shown until more text is entered and the amount of suggestions is reduced.

That way, entering `ps` won't show `pstart`, too many suggestions. But entering `px` will show `pxtart`, since there are not many suggestions.

My expectation is that my custom Emmet snippets should always be in the suggestion list, esp. when I entered a proper prefix of the entire snippet name.

**Comment by ramya-rao-a** [comment]
> It looks like it has something to do with the amount of the suggestions for the currently entered text

No. We show only the best match for the abbreviation/snippet that has been typed for Emmet

So in your case `mrg` fuzzy matches best with `mr` (See https://github.com/emmetio/snippets/blob/master/css.json#L137) than with `mrgstart`, and so you get `margin-right` which is the value for the snippet `mr`. This fuzzy matching occurs inside the emmet module called [css-snippets-resolver](https://github.com/emmetio/css-snippets-resolver)

Similarly `ps` matches best with `pos` than `pstart`.

To learn more about fuzzy matching in Emmet for css, see https://github.com/emmetio/css-snippets-resolver/blob/master/index.js#L154

> custom Emmet snippets should always be in the suggestion list, esp. when I entered a proper prefix of the entire snippet name.

That sounds reasonable. I can look into it

**Comment by ramya-rao-a** [comment]
this will be fixed in tonight's Insiders (Sept 1)
