### ISSUE TITLE
git dirty/clean sign is not updated correctly

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#33570]
- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. In terminal, make a directory called "`test`", and make it a git repo by "`git init`".
2. Open this directory in VSCode, by command "`code .`"
3. Create a file "test.txt", and type something.
4. In terminal, git add and git commit.
5. The git symbol at the down-left corner is "master", not "master*". It is correct.
6. Now, type another line into "test.txt". The green strip at the line number indicates it is a new insertion.
<img width="82" alt="screen shot 2017-08-30 at 22 51 26" src="https://user-images.githubusercontent.com/18319900/29908369-d6c6df22-8dd5-11e7-8b11-c047437a50d3.png">

7. Now, the git symbol at the down-left corner is "master", not "master*".
<img width="98" alt="screen shot 2017-08-30 at 22 52 07" src="https://user-images.githubusercontent.com/18319900/29908377-e24dd65c-8dd5-11e7-8893-eb858a32be49.png">

8. Git add.

9. Now, the git symbol at the down-left corner is still "master", not "master*".

Besides, I hope there is a "force update" option.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@Leedehai Is this still an issue for you?

**Comment by Leedehai** [comment]
I trained myself not to rely on the git dirty/clean sign, so.. I don't know:)

**Comment by joaomoreno** [comment]
Going to close it then.
