### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cmdreay** [Microsoft/vscode#33575]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.2.0-42-generic
- Extensions: none
(1 theme extensions excluded)
---
when  ctrl + f with a $ , why show as \$

Reproduces without extensions: Yes/No

**Comment by cmdreay** [comment]
$ ==> ''\'$

**Comment by cmdreay** [comment]
\\$

**Comment by yume-chan** [comment]
Do you have the `Use Regular Expression` option on?

`$` is a keyword in regexp, so Code will escape it automatically for you.

Besides, you can edit your post.

**Comment by alexandrudima** [comment]
I'm sorry I don't understand what's the issue here.

**Comment by cmdreay** [comment]
sorry, i mean the find field show as \\$ but this does not  affect the search anyway
