### ISSUE TITLE
Row/Chars Limit in output code

### ISSUE THREAD

**Issue by godzail** [Microsoft/vscode#33574]
- VSCode Version: Code - Insiders 1.16.0-insider (34cc9f2209be766d5be30a6ecdbb41f5e81fd56b, 2017-08-30T05:23:44.557Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.8
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
python|don|0.7.0
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.7.1
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.6.1
search-node-modules|jas|1.1.1
node-module-intellisense|lei|1.4.0
MagicPython|mag|1.0.12
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.2.0
indent-rainbow|ode|0.6.1
vscode-code-outline|pat|0.0.8
material-icon-theme|PKi|2.2.0
open-in-browser|tec|1.1.0
python|tht|0.2.3
nodejs-extension-pack|wad|0.1.9
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.4.1
---

Steps to Reproduce:

1.  Add a new python file that print text in output code:
```
for i in range(1, 4000):
  print(i, "random chars text pdpofspodispdsps di sdpofsdpois dpifpsdi psdoipiofsdp")

print("You reach the end!")

```
2. Run code and check the output code folder
3. In output code only the first 2653 rows are shown ("You reach the end!" not ) exiting with code=null.
4. Reducing then number of rows (2500) everything is ok (("You reach the end!" is visible) exiting with code=0.
5. If I run the code in terminal everything is ok.
6. Maybe is there a buffer limit?

![image](https://user-images.githubusercontent.com/9415177/29914333-6ff9893a-8e38-11e7-86e6-7bc77ddd7230.png)

Reproduces without extensions: No

**Comment by isidorn** [comment]
Yes there is a buffer limit due to performance reasons, you can find it here 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/common/output.ts#L43

More deatils can be found here https://github.com/Microsoft/vscode/issues/22804

Closing as desgined
