### ISSUE TITLE
The hotkey "ctrl+f"(search) have no any action, but reboot vscode can back to normal.

### ISSUE THREAD

**Issue by gzx-miller** [Microsoft/vscode#33583]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
python|don|0.7.0
gitlens|eam|4.4.3
cpptools|ms-|0.12.3
bash-debug|rog|0.1.0
code-settings-sync|Sha|2.8.3
vscode-multiclip|sle|0.1.2
debug|web|0.21.2
webnativeDebugger|web|1.0.0
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@gzx-miller can you still reproduce this with latest version?
