### ISSUE TITLE
Tabs setting in .editorconfig not used for new file - have to reopen file before it work

### ISSUE THREAD

**Issue by mostergaard** [Microsoft/vscode#33582]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
gitlens|eam|4.4.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.2.0
material-icon-theme|PKi|2.2.0
vscode-icons|rob|7.12.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Have an .editorconfig somewhere in the file system where the "indent_style = tab" setting is.
2. Right-click in the explorer-pane to create a new .js file
3. When you click "tab" spaces are inserted and not tabs as expected from the .editorconfig
4. Close the file and open gain. NOW it works correctly.

Reproduces without extensions: No. Even after reloading the file the indent_style setting of .editorconfig file is NOT used. Maybe the support for .editorconfig comes from one of the extensions?

**Comment by jrieken** [comment]
VS Code does *not* support editorconfig *without* installing the corresponding extension.
