### ISSUE TITLE
azure-account extension is missing licenses

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33587]
I was running the [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) today and it found several issues:

- do not add devDependencies to the npm-shrinkwrap.json. I've already removed them.

- the OSS tool reported these errors:
ERROR: aws-sign2@0.6.0: Missing Copyright statement in license text!
ERROR: azure-arm-resource@2.0.0-preview: Missing Copyright statement in license text!
ERROR: bcrypt-pbkdf@1.0.1: No license detail found at repositoryURL: null
ERROR: caseless@0.12.0: Missing Copyright statement in license text!
ERROR: copy-paste@1.3.0: Missing Copyright statement in license text!
ERROR: forever-agent@0.6.1: Missing Copyright statement in license text!
ERROR: json-schema@0.2.3: No license detail found at repositoryURL: https://github.com/kriszyp/json-schema
ERROR: jsonify@0.0.0: No license detail found at repositoryURL: https://github.com/substack/jsonify
ERROR: ms-rest-azure@2.2.3: Missing Copyright statement in license text!
ERROR: ms-rest@2.2.1: Missing Copyright statement in license text!
ERROR: oauth-sign@0.8.2: Missing Copyright statement in license text!
ERROR: tunnel-agent@0.6.0: Missing Copyright statement in license text!
ERROR: tweetnacl@0.14.5: Missing Copyright statement in license text!
ERROR: windows-process-tree@0.1.3: No license detail found at repositoryURL: null
ERROR: xmldom@0.1.27: Missing Copyright statement in license text!
ERROR: xpath.js@1.0.7: Missing Copyright statement in license text!

As an example we've already added an Apache license for the "request" npm module.

**Comment by chrmarti** [comment]
We have removed the extension.
