### ISSUE TITLE
SCM doesn't remove itself after removing workspace folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33581]
* Have a workspace with 2 folders, 1 under git, 1 not
* Add a third folder which is under git
* Remove that folder again
* The SCM viewlet still shows that folder

**Comment by joaomoreno** [comment]
It's tricky... I won't close the repository if you have a file from it still open, since I automatically open repositories when you open files from them.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
