### ISSUE TITLE
Link to API docs from intellisense

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3358]
It would be very convenient to have links to API documentation (MDN?) directly within intellisense for HTML, CSS and JS.

![image](https://cloud.githubusercontent.com/assets/2193314/13259640/2210a32e-da0d-11e5-997c-bb76a42c0096.png)

(Currently HTML descriptions is pulled from the spec)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-html-languageservice#12
