### ISSUE TITLE
Feature request: auto_id_class

### ISSUE THREAD

**Issue by nicooprat** [Microsoft/vscode#33592]
![68747470733a2f2f6769746875622e636f6d2f627261646c6579666c6f6f642f6175746f2d69642d636c6173732f626c6f622f6d61737465722f73637265656e2d7265636f7264696e672d64656d6f2e6769663f7261773d74727565](https://user-images.githubusercontent.com/645641/29925253-ff01d9c6-8e5f-11e7-83f5-af10a151de8a.gif)

Sublime Text has a nice option, not very well known I guess: `auto_id_class: true`. It allows, when focus is in a HTML tag, to type `#` to write `id=""`, and `.` to write `class=""`. Simple but very useful. I found an [extension for Atom](https://atom.io/packages/auto-id-class), but nothing for VScode. 

Did anyone find something similar?

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
You could define a snippet for that.

**Comment by nicooprat** [comment]
1. Would it be possible to restrict this snippet to having focus in a tag? Eg. not in regular text.
2. Wouldn't it interfere with Emmet?  (like `#` would write `<div id="|"></div>`)
3. What's more, in Atom or ST, there's no need to hit tab to trigger this behavior ; I guess there's no way to do so with snippets in VScode?

**Comment by aeschli** [comment]
No, snippets can't be restricted and both emmet proposals and your snippet would show up at the same time.
But if there is no other snippet with the name '#', you can autoselelect it with `tab` if you have `"editor.tabCompletion": true` enabled.
 
To have that without pressing tab then an extension is needed.
