### ISSUE TITLE
Removing a workspace when there are JSON errors does not give any feedback

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33599]
Steps to Reproduce:

1. have errors in the workspace file
2. remove folder from explorer

=> no feedback to the user

![panel-red](https://user-images.githubusercontent.com/900690/29929240-419c3208-8e6b-11e7-82d3-7026ba6875e3.gif)

**Comment by isidorn** [comment]
In the latest insider I get a nice error.
Closing. @bpasero please reopen if you still see this

`Unable to write into workspace configuration file. Please open the file to correct errors/warnings in it and try again.`
