### ISSUE TITLE
Diff editor breaks when running `vscode.diff` twice in a row

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33593]
This broke it: https://github.com/Microsoft/vscode/commit/062d65d175fb2183950cd1b02652799ae776c7c3

**Comment by joaomoreno** [comment]
cc @alexandrudima @bpasero

**Comment by joaomoreno** [comment]
Fixed by: 2b51e6bfe2596a912b0e7bf095918fcb86c4653a

**Comment by joaomoreno** [comment]
Repro steps:

Run this in an extension:

```
commands.executeCommand<void>('vscode.diff', left, right, title, opts);
commands.executeCommand<void>('vscode.diff', left, right, title, opts);
```

**Comment by bpasero** [comment]
I see why this is happening but I do not feel good about changing this so late (not a regression either). Will revisit this in September.
