### ISSUE TITLE
Intellisense read more button should not appear when everything is already displayed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3359]
![image](https://cloud.githubusercontent.com/assets/2193314/13259684/552e75a6-da0d-11e5-94a6-01a8fe29a6ed.png)

**Comment by joaomoreno** [comment]
Won't fix.

**Comment by Tyriar** [comment]
Any particular reason?

**Comment by joaomoreno** [comment]
Hm... Figuring out whether the text fits in there is not trivial nor do I feel it improves the experience by much. But feel free to give it a try! ;)
