### ISSUE TITLE
Color picker grows when using sliders and jumps up and down

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33595]
See attached video, the hover grows until a certain size whenever I change the color from the slider:

![panel-red](https://user-images.githubusercontent.com/900690/29927186-db2d7a90-8e65-11e7-897f-14d7f83056d7.gif)

**Comment by chrisdias** [comment]
Also, it removes the quotes, making the value an error in settings.

**Comment by rebornix** [comment]
Sorry for coming back to this issue too late, I used to the issue both of you described but I no longer see this in latest. Can you help confirm that?

**Comment by chrisdias** [comment]
I don't see either issue any more.
