### ISSUE TITLE
Installer Icon on Windows

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#33603]
Testing #33272 
Windows

On my home PC I noticed that the icon on the right was very blocky.  I have a 4K monitor.

![image](https://user-images.githubusercontent.com/1051190/29932331-d665061e-8e28-11e7-94f4-a2150082644d.png)

**Comment by bpasero** [comment]
We are limited in what kind of image resource we can provide to InnoSetup.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
Yup, hdpi issue.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
