### ISSUE TITLE
Tab is no working 

### ISSUE THREAD

**Issue by aboodh95** [Microsoft/vscode#33605]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.16
xml|Dot|1.9.2
tslint|eg2|0.17.0
prettier-vscode|esb|0.23.1
json2ts|Gre|0.0.6
beautify|Hoo|1.1.1
vscode-react-typescript|inf|1.0.7
dynamics-crm-js|JLa|1.2.4
Angular2|joh|2.4.3
ts-extension-pack|loi|0.0.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.2.0
tsimporter|pmn|1.2.14
typescript-hero|rbb|1.4.0
move-ts|str|1.5.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

In typescript editor the tap button will not work as tab inside the code and it will change the focus to the buttons in the ribbon

**Comment by mjbvz** [comment]
If you disable extensions, does this still happen? You can disable extensions by starting code with the  `--disable-extensions` command line flag or by running the `Extensions: Disable all installed extensions` command in vscode

**Comment by aboodh95** [comment]
Hi

i did as what you asked and it's the same 

the issue will start to happen if you click Ctrl + O (Open File) and then you _**cancel it**_ The tab button will stop working as tab inside the editor and it will change the focus (In case you select a file no problem will happen)
 
this will happen in all editor (i tried Json, XML, TypeScript, JavaScript)

**Comment by mjbvz** [comment]
I can't reproduce this on a windows machine. A few other questions to help investigate:

- Do you have any custom keybindings?
- What keyboard layout / language are you using?
- Can you share your user settings?

Thanks

**Comment by aboodh95** [comment]
Hi

I'm sorry but my knowledge is not that much so what do you mean by keybindings
 keyboard layout / language: English

{
    "workbench.colorTheme": "Solarized Dark",
    "files.autoSave": "afterDelay",
    "editor.mouseWheelZoom": true,
    "editor.tabCompletion": true
}

**Comment by aboodh95** [comment]
Hi 

the issue is related to "editor.tabCompletion": true
if i remove this option the problem will not happen

**Comment by aboodh95** [comment]
Hi

I'm sorry about the wrong information 

I'm use to click Ctrl + M + O in visual studio to collapse the method but this will open Open File dialog in Visual studio code 

In case i close this dialog (Not the Ctrl + O) the issue will happen

**Comment by aboodh95** [comment]
Hi

you can prevent this issue by removing the "editor.tabCompletion": true setting

**Comment by jrieken** [comment]
> you can prevent this issue by removing the "editor.tabCompletion": true setting

Are you saying the tab-key works when having this setting off/false?

> In typescript editor the tap button will not work as tab inside the code and it will change the focus to the buttons in the ribbon

What does "in the ribbon" means? Outside the editor? Do you see this at the bottom of the editor? 

<img width="234" alt="screen shot 2017-09-28 at 15 23 26" src="https://user-images.githubusercontent.com/1794099/30968868-052f7184-a461-11e7-9740-a134b81b2511.png">
