### ISSUE TITLE
Wrong keyboard shortcuts

### ISSUE THREAD

**Issue by opencreative** [Microsoft/vscode#33608]
- VSCode Version: 1.15.1
- OS Version: Windows 7 Ultimate x64

@jrieken, sorry, I assigned the wrong keyboard shortcuts. Issue #33491. <kbd>Shift</kbd>+<kbd>A</kbd> this is input in uppercase. Or the keyboard shortcuts <kbd>Shift</kbd>+<kbd>A</kbd> will only work for the event ```acceptSnippet```?

**Comment by jrieken** [comment]
You can use `when`-clauses to define when your keyboard shortcuts are active, e.g `when = inSnippetMode`. See https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization for more information.

**Comment by opencreative** [comment]
Thank you.
