### ISSUE TITLE
Automatically trigger a powershell script when open a new terminal 

### ISSUE THREAD

**Issue by hanct** [Microsoft/vscode#33600]
Everytime when I open a new terminal in vscode (v1.13.1), I have to manually trigger a script which is written to set up some environment path for the session. Is it possible to configure vscode such that whenever a terminal is newly opened, it will auto trigger a script which is located at say "C:\myScript.ps"?

**Comment by Tyriar** [comment]
I think the PowerShell extension might have this functionality https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

**Comment by hanct** [comment]
Hi,
Triggering a powershell script is just an example. Sometime, when i open a new terminal, i also wish it will automatically trigger/run a script (be it powershell script, window batch script) or even a program! Hence i wish to have a solution that is not specific to powershell.

**Comment by Tyriar** [comment]
I imagine there's some way to configure this this using a PS profile in command line arguments or something which can be set using the `terminal.integrated.shellArgs.windows` settings key.
