### ISSUE TITLE
Prompting for user permission, but console is run

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#33604]
verifying #21635
1.16-insiders
Ubuntu 14.04 & Windows 64
- create a Node app `app.js`
- create a launch config that uses the integratedTerminal as console:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "console": "integratedTerminal"
        }
    ]
}
```
- in the workspace settings, have `"terminal.integrated.shell.linux": "/bin/zsh"`
- launch the programm
- dialog pops up 'Do you allow shell: "/bin/zsh" (defined as a workspace setting) to be launched in the terminal?'
- observe that the shell is started and the programm is launched without waiting for the user to allow or disallow.

**Comment by Tyriar** [comment]
This was as designed, the workspace shell will be requested and the action will be performed using the default until the user accepts the workspace shell.
