### ISSUE TITLE
Fallback not working on invalid shell

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#33606]
Verifying #21635 

1.16-insiders
Windows 64
- create a Node app `app.js`
- create a launch config that uses the integratedTerminal as console:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "console": "integratedTerminal"
        }
    ]
}
```
- in the user settings, have `"terminal.integrated.shell.windows": "powershell.exe`
- launch the programm. Programm starts, output in integrated powershell terminal
- in the user settings, change to `"terminal.integrated.shell.windows": "powershell.exe1`
- launch the programm. Programm doesn't want to start. Error 'Cannot connect to runtime with 'legacy' protocol...
https://github.com/Microsoft/vscode/issues/21635#issuecomment-325320392 ays it would fallback to cmd.exe

**Comment by weinand** [comment]
Only the command line quoting falls back to "cmd.exe", not the shell.
