### ISSUE TITLE
Allow multiple of the left panels to be displayed at once

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3360]
I tend to avoid the search and git panes simply due to the fact that it hides my folder explorer and working files. This is loosely related to [no tabs](https://github.com/Microsoft/vscode/issues/224) as my current working files disappear when I go to these panels.

It would be very useful in particular to see my git working tree status alongside working files and folder explorer.

**Comment by bpasero** [comment]
Closing. We should keep VS Code lightweight and simple. No plans to support this currently.
