### ISSUE TITLE
Comments in .js files

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33619]
- VSCode Version: 1.15.1
- OS Version: win7x64

------

/* - one star in the beginning - params look commented (green color)
/** - two stars in the beginning - params and everything after them look like they are part of the code

```
/**

@param {Node} anchor
@param {string} position
@param {Node} elem

*/
```

GIF:
![js - comments](https://user-images.githubusercontent.com/24613274/29946510-4c9bfa38-8eae-11e7-8565-04f980cdb88d.gif)

**Comment by David-Else** [comment]
That's correct behaviour as it becomes a JSDoc comment with the /**.

It would be nice if you could then add more *********** to the top as it does restrict the formatting.

What would be really great would to be able to edit the config to make the automatic JSDoc fill with @description and @returns etc...
