### ISSUE TITLE
git.enabled false doesn't disable git

### ISSUE THREAD

**Issue by payonel** [Microsoft/vscode#33615]
`git` integration does not respect `git.enabled = false` as it used to. I recently updated vscode insiders when this stopped working (working to disable)

- VSCode Version: 
```
Version 1.16.0-insider
Commit 8b942faafb2d1bee6fd6a346853548d528c7eb5a
Date 2017-08-31T05:16:45.400Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- OS Version:
`ubuntu 16.04`

Steps to Reproduce:

1. open folder that has git with modified files
2. set `"git.enabled" = false` in both user and workspace 

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Dude, great catch, thanks!
