### ISSUE TITLE
Second Window Editor Limitations

### ISSUE THREAD

**Issue by Dargmuesli** [Microsoft/vscode#33617]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: (All disabled)

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
python|don|0.7.0
vscode-apache|mrm|1.1.1
PowerShell|ms-|1.4.1
vscode-docker|Pet|0.0.16
php-formatter|Sop|0.2.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open VS Code and view a file
2. Open a new VS Code Window and open another file

Problem:

In the first instance the editor works correctly.
In the second instance the editor does not show indent guides, whitespaces (/does not load settings) and shortcuts like `ALT + Z` do not work.

I guess I'm not the only one with this problem, but I'm unsure how to name it exactly. Hence, I cannot find another issue about this.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Do you have workspace settings in the first window?

**Comment by Dargmuesli** [comment]
No, I disabled them all. The problem also occurs when I open another folder in the same window.

**Comment by roblourens** [comment]
> does not load settings

So it's not respecting your user settings? Do you see the right settings in the settings editor (`ctrl+,`)?

**Comment by Dargmuesli** [comment]
Yes, that's correct. The settings are set, but not respected. I guess I'll soon try to do a complete reinstall on my computer as it works on my laptop. I'll give you a report.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Dargmuesli** [comment]
A reinstall fixed this issue. Could've started when I switched to 64bit.
