### ISSUE TITLE
PHP tags inside function incorrectly scoped

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#33616]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:18:42.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.20.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.6.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. In a php block like this:
````php
    <?php function auto_copyright($year = 'auto'){ ?>
       <?php if(intval($year) == 'auto'){ $year = date('Y'); } ?>
       <?php if(intval($year) == date('Y')){ echo intval($year); } ?>
       <?php if(intval($year) < date('Y')){ echo intval($year) . ' - ' . date('Y'); } ?>
       <?php if(intval($year) > date('Y')){ echo date('Y'); } ?>
    <?php } ?>
````
The `?`s inside of the brackets are not colored nor scoped like the others.  They are white and `text.html.php meta.embedded.line.php source.php ` while the others are orange and `punctuation.section.embedded.begin.php`.

<img width="1033" alt="screen shot 2017-08-31 at 4 16 25 pm" src="https://user-images.githubusercontent.com/835148/29943588-04a95572-8e68-11e7-8f8f-a651a20d20c4.png">

**Comment by roblourens** [comment]
It should work, but why do you have the php tags on every line of php?

**Comment by smlombardi** [comment]
I got that code snippet from a web site.  Looking at it now, I see how they can be removed.

But originally I just copied and pasted it.
