### ISSUE TITLE
"when" clause with context keys not working anymore for custom views

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#33618]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:27:43.804Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Create a custom view extension with a value of `"scmProvider == git"` for the `contributes.views.explorer.when` key in package.json.
2. Observe that the extension doesn't get activated even though the current scm provider is git.

Note that this is working in 1.15.1 and older versions.

**Comment by joaomoreno** [comment]
The notion of a single `scmProvider` value is now gone from the entire workbench context... since it is now possible to have multiple scm providers active.

**Comment by letmaik** [comment]
https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare

Basically I want to activate the custom view when there is at least one git repo in the workspace. Previously I used `scmProvider == git && config.git.enabled && gitState != norepo` as condition.

**Comment by joaomoreno** [comment]
Got it. There is now a specific git context key around: `gitOpenRepositoryCount` which is set to the number of git repositories. Can you try using that?

For stable that will be available from 1.16.0 onwards.

**Comment by letmaik** [comment]
That works, great. If only it would be possible to have OR conditions in "when" clauses to support both old and new behaviours.

**Comment by joaomoreno** [comment]
It's definitely not possible right now, unfortunately... I'll close this for now.

**Comment by letmaik** [comment]
Note that my concern about supporting both old and new versions is not relevant as I found out: https://github.com/Microsoft/vscode/issues/33959
