### ISSUE TITLE
Opening WorkSpace opens wp file instead after upgrade

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#33614]
Insiders 8-31 
Windows 7

After upgrading from Insiders 8-8 to 8-31 a working WorkSpace now opens the file not the workSpace.
This  occurs using open recent or Open WorkSpace from the file menu.

The workSpace layout/open files were also lost after the upgrade.

**Comment by bpasero** [comment]
@cleidigh can you share the workspace file?

**Comment by bpasero** [comment]
Issue is with filtering out folders in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/workspaces/electron-main/workspacesMainService.ts#L126

**Comment by KingDGrizzle** [comment]
Still didn't work, instead it now added the full path to `folders`
```json
{
	"id": "1504211943767",
	"folders": [
		"file:///c:/Users/Vlad/Desktop/Development/GAwesomeBot-Wiki"
	],
	"settings": {}
}
```

**Comment by bpasero** [comment]
@KingDGrizzle my fix is not yet in insiders!

**Comment by bpasero** [comment]
See also: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_16.md#new-workspace-file-format

**Comment by KingDGrizzle** [comment]
Is it not? I just had an update, and thought it was this. Sorry 😢

**Comment by cleidigh** [comment]
@bpasero 
@jrieken 
Just pulled master aa42e6ef81 built OSS and tried workSpace - works as advertised !
Great.
