### ISSUE TITLE
Ugly Color in all themes

### ISSUE THREAD

**Issue by sstaub** [Microsoft/vscode#33611]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|0.1.3
include-autocomplete|ajs|0.0.4
file-templates|brp|1.2.0
CppSnippets|har|0.0.12
auto-comment-blocks|kev|0.3.2
cpptools|ms-|0.12.3
vscode-code-outline|pat|0.0.8
platformio-ide|pla|0.6.0
vscode-icons|rob|7.12.0
vscode-todo-highlight|way|0.5.9
debug|web|0.21.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. see screenshot, the light green color (#98C379) is present in every theme
![colortheme ugly color](https://user-images.githubusercontent.com/6450325/29937478-04ebcb1e-8e86-11e7-8ef0-be0a2ff80f52.png)

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
I can't reproduce that. Please make sure extensions are disabled. Also, please add a code snippet.
To see why the color appears, put the cursor in the colored area and run the command `Developer: Inspect TM Scope`. When I try this I don't see any special scope for that line, its all `comment.block.c`
![image](https://user-images.githubusercontent.com/6461412/29964192-921e0c3a-8f09-11e7-87cb-5dafef7e687a.png)

**Comment by sstaub** [comment]
Thank you for that advice, it was the "Better Commands" Extension which causes the problem.
