### ISSUE TITLE
Breakpoints don't get triggered for extension integration tests

### ISSUE THREAD

**Issue by msafi** [Microsoft/vscode#33612]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:18:42.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Generate an extension with `yo code`
1. Add a breakpoint in extension code
1. Use `vscode.commands.executeCommand('extension.sayHello')` to trigger extension in one of the tests
1. Run integration tests

Breakpoint doesn't get triggered.

See this video https://giphy.com/gifs/3o7aDdJsTo4z8wVhnO/fullscreen

**Comment by weinand** [comment]
The breakpoint in the extension.ts gets hit fine, if I have a breakpoint in the extension.test.ts too. See this screencast:
![33612](https://user-images.githubusercontent.com/1898161/29962325-2b0e4c90-8f03-11e7-99c5-ef2b9a5e4674.gif)

If I remove the breakpoint in extension.test.ts, I **do not hit** the one in extension.ts.

**Comment by roblourens** [comment]
This works for me every time. @weinand can you add the log (from `"trace": true`)? And you have `outFiles` in your launch config right?

**Comment by roblourens** [comment]
I couldn't repro, can anyone else try again and attach a log?

**Comment by roblourens** [comment]
Actually now the test just says `Error: command 'extension.sayHello' not found` when I run the test, I'm not sure what I need to do to get it to activate the extension.

**Comment by DanTup** [comment]
I'm seeing something weird here today. I hit breakpoints in my test code, but not in the extension code. I can't be certain this ever worked for me as I didn't really have tests executing commands until recently.

Launch config looks like this:

```
{
	"name": "Launch Tests (General)",
	"type": "extensionHost",
	"request": "launch",
	"runtimeExecutable": "${execPath}",
	"args": [
		"${workspaceRoot}/test/test_projects/hello_world",
		"--extensionDevelopmentPath=${workspaceRoot}",
		"--extensionTestsPath=${workspaceRoot}/out/test/general"
	],
	"stopOnEntry": false,
	"sourceMaps": true,
	"outFiles": [
		"${workspaceRoot}/out/test/**/*.js"
	],
	"preLaunchTask": "npm: watch"
},
```

**Comment by roblourens** [comment]
This works fine for me now. Still an issue?

**Comment by roblourens** [comment]
Try changing outFiles to `"outFiles": [ "${workspaceRoot}/out/**/*.js" ]`
