### ISSUE TITLE
Open file with Ctrl+P seems to run the query on every keystroke without cancelation

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/vscode#33613]
- VSCode Version: 1.16.0-insider
- OS Version: Windows 10

**Steps to Reproduce:**

1. Open a project with ~150k files
2. Use Ctrl+P and type the name of a file

**Expected:**   
Search comes back within a second or two

**Actual:**   
Search takes about 10 seconds

However,      
2b. Paste the name of a file instead of typing it in

**Actual:**   
Search completes within a second or two.

Is VSCode performing the search on every keystroke and not canceling those that are obsolete?

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@trevorsg We create an index on the first search and cache that so subsequent searches are faster. Does that explain the behavior you see?

**Comment by trevorsg** [comment]
@chrmarti No. My repro is for files that I have never opened/queried before. I can attach a gif recording if you like.

**Comment by chrmarti** [comment]
@trevorsg The index is for the entire folder you have opened in VSCode. A GIF might help to better understand this, thanks.

**Comment by trevorsg** [comment]
![vscodectrlp](https://user-images.githubusercontent.com/397836/29940835-7ace192c-8e5e-11e7-8ea3-2cdc146f25a4.gif)

**Comment by chrmarti** [comment]
@trevorsg Try entering it letter by letter for a second time (without reloading the window in-between). It should be much faster. The reason pasting the name is faster is because it is the second time QuickOpen is used.

**Comment by trevorsg** [comment]
@chrmarti Nope. Watch the gif - you will see I enter "richeditor.ts" four times. First and third are typing it letter-by-letter, and it's slow. Second and fourth is Ctrl + V, and it's fast.

**Comment by chrmarti** [comment]
Could you check if there is anything in the console (Help > Toggle Developer Tools)?

**Comment by roblourens** [comment]
Or check whether it's spawning lots of 'find' processes in the task manager?

I tried on an extremely large folder and it still worked as expected. Do you know whether this worked before and stopped at some point?

**Comment by chrmarti** [comment]
There won't be any find processes because this is on Windows from what I see.

**Comment by trevorsg** [comment]
I'll be happy to help, but I'm oof until Tuesday. Maybe @dwilsonmsft can fill in. As far as I know it has always been this way. I only recently discovered they pasting the file name is fast.

**Comment by trevorsg** [comment]
I didn't see anything in the console. I created a perf profile and emailed it to you - not sure if that will help.

**Comment by chrmarti** [comment]
@trevorsg Thanks for sending the perf profile along. It shows the renderer process being idle most of the time. We'd need a way to get a perf profile from the search process.

**Comment by roblourens** [comment]
@chrmarti We now have a command line option to start the extensionhost in debug mode. https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_16.md#profile-your-extension Would it make sense to have one for the searchService too? These issues don't come up too often, but it seems like a useful tool.

**Comment by chrmarti** [comment]
@roblourens If that's simple enough to introduce, sure!

**Comment by chrmarti** [comment]
It turns out that once the search process is sorting the files to find the best matches, it just holds on to the thread and cancellation messages coming through IPC are only processed after that has finished.

I have a fix prototyped that will let the sorting yield to node's event loop from time to time so that can process IPC messages.

Moving out as this is not a recent regression.
