### ISSUE TITLE
Git sections from other folders, in single-root mode, don't go away

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33626]
- Open one folder
- Open a single file from another folder, which has a git repo
- See that there are now two sections in the git viewlet
- Close the file
- The other section is still there

One case where this is annoying is that I have my User folder under Git, so every time I open settings, it opens the `User` git section. It's easy to collapse the extra ones though. If they don't go away automatically when the file is closed, I should be able to right-click -> hide them

**Comment by joaomoreno** [comment]
We no longer use sections, unless the user explicitly wants them, so this problem is minimised. Let me know if it's still bothersome.

**Comment by roblourens** [comment]
I'm pretty tired of picking my repo every time I want to push or pull or do anything, but I can deal
![image](https://user-images.githubusercontent.com/323878/30711174-c5e396da-9ebc-11e7-8abf-bc40e15b8e18.png)

**Comment by joaomoreno** [comment]
@roblourens I'm thinking of adding the `...` overflow menu to the right of each repo in the list, so you'd have the actions there too.

**Comment by roblourens** [comment]
That wouldn't hurt, but I like the command palette :)

**Comment by dbaeumer** [comment]
Reopening it since I still see the git provider not disappearing.

![cast](https://user-images.githubusercontent.com/1931590/31017929-82b9b154-a52a-11e7-83de-8e176fbd0031.gif)

I have ESLint open, then open a file from Node which is under git and then close the file. Note that the Node provider stays.

**Comment by joaomoreno** [comment]
That's OK. I've added a context menu action to `Close Repository` in situations like this. I'm not a big fan of automatically pulling out rugs under the user's feet.

**Comment by dbaeumer** [comment]
@joaomoreno  But you are adding rugs under the user's feet :-)

**Comment by joaomoreno** [comment]
Don't want them to feel the hard wood floor!
