### ISSUE TITLE
pylint

### ISSUE THREAD

**Issue by Inhee-LEE** [Microsoft/vscode#33624]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.7.0
vscode-html-css|ecm|0.1.8
view-in-default-application|see|3.3.0
lorem-ipsum|Tyr|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@Inhee-LEE What is this issue about? Perhaps you meant to open an issue in the [DonJayamanne/pythonVSCode repository](https://github.com/DonJayamanne/pythonVSCode)?

**Comment by Inhee-LEE** [comment]
Sorry i made a mistake.
I did'nt try to open any issue.
I am a newbie about VS code.


2017. 9. 1. 오전 9:17에 "Remy Suen" <notifications@github.com>님이 작성:

@Inhee-LEE <https://github.com/inhee-lee> What is this issue about? Perhaps
you meant to open an issue in the DonJayamanne/pythonVSCode repository
<https://github.com/DonJayamanne/pythonVSCode>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/33624#issuecomment-326453507>,
or mute the thread

**Comment by jrieken** [comment]
Ok, closing
