### ISSUE TITLE
Not all Emmet shortcuts work

### ISSUE THREAD

**Issue by bcsjk11** [Microsoft/vscode#33629]
- VSCode Version: 1.15.1
- OS Version: macOS Sierra (12.6)

Steps to Reproduce:

1. Create a new HTML document
2. use `!` and the `TAB` key and I get the expected template
3. use the following syntax: `p[title="Hello world"]` and follow by the tab key and it does not work.

The `p[title="Hello world"]` snippet is directly from the emmet cheat sheet.

In previous versions of vscode (1.14 I believe) this `script[src="script.js"]` snippet worked fine and created `<script src="script.js"></script>`

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
So are you saying that `!` works as expected, but `p[title="Hello world"]` and `script[src="script.js"]` don't ?

They works as expected as shown below
 
![emmet](https://user-images.githubusercontent.com/16890566/29955982-a838b20c-8e98-11e7-9689-2d356283a624.gif)

If you are specifically looking to expand emmet abbreviations and snippets using the tab key, then set `emmet.triggerExpansionOnTab` to `true`

**Comment by ramya-rao-a** [comment]
Or are you referring to the issue that the suggestion box doesn't show up at the end of `]`?

**Comment by bcsjk11** [comment]
Now it works - sorry I placed my cursor at the end of the code snippet before hitting tab. This is what I did in the past.

**Comment by ramya-rao-a** [comment]
@bcsjk11 Yes, you can get the old behavior back by setting `emmet.triggerExpansionOnTab` to `true`.

More changes on Emmet in the last release can be found on the [Emmet 2.0 blog](code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

**Comment by bcsjk11** [comment]
Ah that all makes sense now - thanks for pointing that out.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
