### ISSUE TITLE
Git failed to find repository: permission denied 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33628]
- VSCode Version: Code - Insiders 1.16.0-insider (8b942faafb2d1bee6fd6a346853548d528c7eb5a, 2017-08-31T07:27:43.804Z)
- OS Version: Windows_NT x64 10.0.15063

---

**Steps to Reproduce:**
Under a standard account, open the `c:\Windows` folder in Code

**bug**
See a large number of "failed to find repository" errors

![image](https://user-images.githubusercontent.com/12821956/29951686-0ef506e6-8e79-11e7-8c0c-71bbc9c722c4.png)

```
extensionHost.ts:383 [Extension Host] Failed to find repository: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

![image](https://user-images.githubusercontent.com/12821956/29951711-5ab3130c-8e79-11e7-8a58-540b5419b70a.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This no longer happens in today's build.
