### ISSUE TITLE
Feature request: support for file path 

### ISSUE THREAD

**Issue by jeremychone** [Microsoft/vscode#33625]
Right now, when doing a `new file` or `new folder` we cannot add a full path. 

I think it would be a very neat to allow a full path (probably just supporting the "/" would be enough) when creating a new file. 
For example:

![image](https://user-images.githubusercontent.com/74671/29950482-f09c1c78-8e70-11e7-943d-f9668d170f50.png)
the  `src/` folder would be created if it does not exist and used as the path of the file. (This was one of my favorite Sublime plugins) 

Also, creating a folder seems to have another command to have new new file, which might not be needed. For example, the following "new item" could create a folder (as it ends with "/")
![image](https://user-images.githubusercontent.com/74671/29950637-fa1ee540-8e71-11e7-90d0-34873b46ef82.png)

Merging the "new file" and "new folder" with this feature will really make creating new file structure much more efficient. This will only save some few seconds per operation, but will bring much satisfaction. 

(This was one of my top Sublime Text plugins, and would fit perfectly in the current default VSCode new file UI)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by jeremychone** [comment]
@bpasero Sorry, I did try to search multiple time, but did not manage to find the one about this specific feature. Glad to hear it has been already recorded.
