### ISSUE TITLE
Some abbreviations not work in scss file

### ISSUE THREAD

**Issue by 2eron** [Microsoft/vscode#33633]
1. vscode Version: 1.15.1
2. OS: OS X El Capitan

For example:
When I input the emmet abbreviation 'mr' in a scss file, I expected the emmet result prompts, and after I entered TAB, the result is 'margin', not 'margin-right'.

<img width="629" alt="2017-09-01 11 36 04" src="https://user-images.githubusercontent.com/3272874/29954670-39e2ba40-8f0c-11e7-928d-d1ba8e03257f.png">

**Comment by ramya-rao-a** [comment]
`mr` -> `margin-right` does show up in the suggestion list, but it gets sorted among the css suggestions.

Something has changed in the sorting algorithm for 1.16 and I see a different order in the latest Insiders

<img width="366" alt="screen shot 2017-08-31 at 10 21 11 pm" src="https://user-images.githubusercontent.com/16890566/29956272-badc379c-8e9a-11e7-8146-303bb5375a59.png">


Regardless, to ensure emmet suggestions show up at the top no matter what you can set the below in the latest Insiders. 

```
"emmet.showSuggestionsAsSnippets": true,
"editor.snippetSuggestions": "top"
```
You can get the Insiders from https://code.visualstudio.com/insiders or wait for the next release of VS Code 1.16

Hope this helps.
