### ISSUE TITLE
Tab moves focus message not consistently displayed

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#3363]
#3246

This message [red in status bar] was not always displayed e.g. when I closed all editor windows it would go away - the tab would still shift focus but this was not what I expected.

**Comment by seanmcbreen** [comment]
no file in focus
<img width="996" alt="screen shot 2016-02-23 at 9 26 47 am" src="https://cloud.githubusercontent.com/assets/1051190/13260287/ac43072e-da0f-11e5-9a76-bcd01e3e077f.png">


file in focus
<img width="998" alt="screen shot 2016-02-23 at 9 26 58 am" src="https://cloud.githubusercontent.com/assets/1051190/13260290/b112db44-da0f-11e5-83e9-d4eb43855d63.png">

**Comment by joaomoreno** [comment]
I believe `Tab moves focus` is only relevant when an editor is in fact open, since it makes <kbd>Tab</kbd> move focus away from the editor itself. @alexandrudima is this correct?

**Comment by alexandrudima** [comment]
The editor is trapping <kbd>Tab</kbd> by default. This means that when inside an editor, by default, pressing the <kbd>Tab</kbd> key will not move focus and will insert a tab character or spaces for indentation. This is OK, as <kbd>Tab</kbd> is used a lot while coding.

However, we must have a way to escape the <kbd>Tab</kbd> trap and move focus to the next element in the focus ring. To do so, you can press <kbd>Ctrl</kbd>+<kbd>M</kbd> which now toggles this specific editor that it no longer traps <kbd>Tab</kbd>. Think of it similar to "insert/overwrite" mode (which we don't yet support, but which would have a similar status bar behaviour).
