### ISSUE TITLE
Formater Option for formatting a document

### ISSUE THREAD

**Issue by lbngoc** [Microsoft/vscode#33635]
I think it will better if we have an option (like ST when press Ctrl+Shift+P) to choice what type of document we want to format. 
I working much with PHP, and some times I need format a document with ext .php by HTML Formatter first, then reformat again with PHP Formatter.

**Comment by roblourens** [comment]
What if you change the file type to HTML first, by clicking on `PHP` in the status bar, to format it as HTML?

**Comment by lbngoc** [comment]
@roblourens 
Yep, I use this way to format my php file, but it take 2 steps to make document be formatted.
I think better if we have an option "Format document as PHP" in "Show All Commands" popup (like sublime text)

**Comment by roblourens** [comment]
This will have to be supported by an extension
