### ISSUE TITLE
After remove folder from sidebar, then open the folder again, I am unable to see the folder in the sidebar

### ISSUE THREAD

**Issue by sunweifang1992** [Microsoft/vscode#33636]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-svgviewer|css|1.4.2
angular2-snippets|dan|1.0.16
tslint|eg2|0.17.0
live-html-previewer|hdg|0.2.0
beautify|Hoo|1.1.1
svg|joc|0.0.9
Angular2|joh|2.4.3
vs-color-picker|lih|0.6.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.2.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
Duplicates #32962
