### ISSUE TITLE
Useless snippets in the snippets list

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33632]
- VSCode Version: 1.15.1
- OS Version: win7x64

It's great when IntelliSense gives you only necessary snippets. And after the "elem." you will (_or should_) get properties and methods, that belong to "elem".

But here is a case I've met like thousand times:

![image](https://user-images.githubusercontent.com/24613274/29953988-04a0246e-8edd-11e7-96c7-568fa2540e7c.png)

Although method `"createElement"` belongs to `document` and only, once you will write that in your code - it will appear in **any** snippets list, according to matching letters.

It shows the icon of "global identifier":

![image](https://user-images.githubusercontent.com/24613274/29954152-65550eea-8ede-11e7-83dd-934ea2c29631.png)

But how is that a global identifier, just because you wrote it somewhere in the code?
I think this should be fixed.

**Comment by mjbvz** [comment]
Try adding:

```json
  "javascript.nameSuggestions": true,
```

to your [user settings](https://code.visualstudio.com/docs/getstarted/settings)

We include all unique names javascript suggestion list by default. This is useful when our language tooling can't fully understand a JavaScript pattern but sometimes results in unwanted suggestions like this

**Comment by user3323** [comment]
@mjbvz, thanks!
