### ISSUE TITLE
Custom menu item

### ISSUE THREAD

**Issue by cwtuan** [Microsoft/vscode#33630]
Is possible to make extension have custom menu item in the file explorer？

Here's I want to do in extension:
When user right click a folder on explorer, show an custom menu item, then user click a item "import template". pop out a dialog which shows a list of template(html, js) then user select a template to import the template code into that folder.

**Comment by rcjsuen** [comment]
Maybe [this link](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus) will help.

**Comment by jrieken** [comment]
Thanks @rcjsuen.
