### ISSUE TITLE
Feature request: tag scrolling

### ISSUE THREAD

**Issue by shaileshkm** [Microsoft/vscode#33643]
- VSCode Version: 1.15.1
- OS Version: Windows 8

I don't find minimap much useful when I need to scroll up and down in my file. Unless there is a large block of switch or comments, I cannot make out where to jump unless I'm aware of the position of the code I'm searching.

Here's feature request for alternative way for fast scrolling.
- By default, auto-tag all method/functions and classes in a file.
- In place of minimap, show all the tags. Except for a large file, ensure the tag list fits in one screen. Scrolling for tag list would likely defeat the purpose. Those who are disciplined enough will keep the file short enough.
- As an enhancement, allow  custom tags.
- Allow hotkeys/quick access buttons for toggle jump between last two locations.

Thanks,
-Shailesh

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
Maybe `workbench.action.gotoSymbol` can help you here?

Use <kbd>Ctrl+Shift+O</kbd> or insert an `@` after a <kbd>Ctrl+P</kbd> and then type in the name of the function/method you are interested in in your editor. You can then jump to that function/method without using the mouse or scrolling with the keyboard.

Click [here](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol) for more information.

**Comment by shaileshkm** [comment]
The ':' to group by category is a nice trick. Thanks for the link.
