### ISSUE TITLE
typescript stop five times 

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/vscode#33642]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.9.0-deepin9-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.4.2
react-native-react-redux|EQu|1.1.0
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.3
android-dev-ext|ade|0.4.1
Gradle|caz|1.1.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
python|don|0.7.0
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
vscode-yarn|gam|1.2.0
docthis|joe|0.4.8
debugger-for-chrome|msj|3.2.0
color-highlight|nau|2.3.0
open-html-in-browser|pea|0.0.2
vscode-react-native|vsm|0.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dmnrmr** [comment]
I have the same issue.

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
vscode-babel-coloring|dza|0.0.4
tslint|eg2|0.17.0
vscode-icons|rob|7.12.0
cucumber|ste|0.9.6
language-stylus|sys|1.7.3

**Comment by mjbvz** [comment]
A few questions:

- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the crash
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by dmnrmr** [comment]
Actually today I worked without a single error, so I am not really sure what happened there.

**Comment by dandersen2** [comment]
I have the same issue, which seems to happen on it's own time when VSC is idle or just running in the background. Most of the time when I switch back to VSC I have this warning waiting for me: 
"The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

It occurs when extensions are enabled or disabled. This has been happening for months, so I don't know in which release it appeared. It appears to only happen in one of my projects(repos) and not the other, and not if I just open a single HTML file for example, but both projects are quite large with hundreds of .js files each so I'm not sure how to pin down what the cause could be.

I turned on the typescript logging and the OUTPUT panel says 'TSServer exited' about once every minute indefinitely for as long as the program is open (see image below). Here's an example of one of the logger errors from the log file: 
    "logger.error('Compression format of ' + encoding + ' not supported');\n "
If the entire log file would be helpful I can email it to you but it does contain some of our source code and filepaths.

![image](https://user-images.githubusercontent.com/14811496/30181920-f8d18546-93e2-11e7-810f-d0a0e3ab23f1.png)

I do not have any custom typescript.tsdk values in my user settings. Please advise...

Thanks!

**Comment by mjbvz** [comment]
@daanschipper Ok, can you please open a new issue and either share the tail of the log file or email me log so that I can investigate ( matb AT microsoft DOT com) Thanks
