### ISSUE TITLE
The project folder cannot appear

### ISSUE THREAD

**Issue by KeepPassionAlways** [Microsoft/vscode#33647]
- VSCode Version: 1.15.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1.command + O
2. Select Folder

Some folders can be opened, some not。

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@KeepPassionAlways can you share a screencast of what hapened?

**Comment by KeepPassionAlways** [comment]
Such as:

![](https://keeppassionalways.github.io/images/demo.gif)

**Comment by bpasero** [comment]
@KeepPassionAlways is that folder on OneDrive maybe?

**Comment by bpasero** [comment]
@KeepPassionAlways what is the full absolute path of the folder you try to open?

**Comment by KeepPassionAlways** [comment]
@bpasero  /Applications/MAMP/htdocs/ejs.m7.suzhouPubResourceCenterEnd

**Comment by bpasero** [comment]
@KeepPassionAlways does it make a difference if you close all code instances and start from the command line: `code /Applications/MAMP/htdocs/ejs.m7.suzhouPubResourceCenterEnd`

**Comment by KeepPassionAlways** [comment]
After running：

![](https://keeppassionalways.github.io/images/demo2.png)

**Comment by bpasero** [comment]
@KeepPassionAlways can you right click on the "Explorer: OpenEdit..." and restore the "Files Explorer" view?
