### ISSUE TITLE
Provide jsdoc highlighting

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3364]
Supporting jsdoc highlighting would make them easier to read, this comment documentation style is pretty widespread.

```js
/**
 * Sorts an array.
 * @param {Array} arr The array to sort.
 * @returns An array.
 */
function sort(array) {
  ...
}
```

`@param`, `@returns` at the least would be easy to highlight (Atom supports this). `{Array}` and `arr` could potentially also be highlighted.

Related https://github.com/Microsoft/vscode/issues/514

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#97
