### ISSUE TITLE
How to select the non-first item of the candidate selector by using the shortcut key?

### ISSUE THREAD

**Issue by kmvan** [Microsoft/vscode#33645]
For example, I want to select the second item, is it only way that using arrow-down key to select and enter?
![tim 20170901150254](https://user-images.githubusercontent.com/3839554/29958788-0d102fa0-8f27-11e7-8072-248712912a50.png)
Thank you.

**Comment by alexandrudima** [comment]
@kmvan I'm not entirely sure what you mean.

* Would you like to get a different sorting such that snippets are not sorted to the top? I think @jrieken knows about a setting you could change for that.
* Would you like to use something else than <kbd>arrow down</kbd> to change selection in the suggestion list? You could do that by looking for the keybinding for arrow down and *editing* it to be a different key. The same can be done with the keybinding for accepting a selected suggestion. It can be changed from <kbd>Enter</kbd> to something else.
* Would you like to have a single keybinding that **both** selects the next suggestion and inserts it? This sounds like a macro. We have an outstanding feature request that you can upvote in #871

**Comment by jrieken** [comment]
> Would you like to get a different sorting such that snippets are not sorted to the top? I think @jrieken knows about a setting you could change for that.

This isn't a snippet but a keyword, no special sorting for that.

@kmvan Are wishing for a 'Select and insert n-th item'-command?

**Comment by kmvan** [comment]
Oh, I got it. Thank you everyone.
![tim 20170901165741](https://user-images.githubusercontent.com/3839554/29962765-e698bc42-8f36-11e7-9031-aa6a88434b5c.png)
