### ISSUE TITLE
Prompt user whether he wants to close window

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#33649]
Feature request.
I usually start my dev server via embedded terminal. In case of two screens i often missclick to the "close window" button. Is it possible to prompt me whether i want to close window if there is an working process in embedded terminal?

**Comment by BruceGitHub** [comment]
The part of code interested is 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L51 

What could you use or ask for confirmation?

**Comment by BruceGitHub** [comment]
OK.
do not need more support then?
