### ISSUE TITLE
Typescript use of React SFC (stateless functional component) usage generates spurious error highlighting

### ISSUE THREAD

**Issue by uglycoyote** [Microsoft/vscode#33644]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5

---

Steps to Reproduce:

1.  create a new directory with a file called main.tsx with the following contents

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';

interface WelcomeProps {
  name: string,
 }
 
 const Welcome: React.SFC<WelcomeProps> = (props) => {
  return <p>Hello, {props.name}</p>;
 }

 class Test extends React.Component<any, any> {
  constructor(props: any) {
      super(props);
  }

  render() { 
      return <div>
              <Welcome name="Mike"/>
          </div>;
  }
}
```

2.  may need to npm install the react typings to reproduce the problem

```npm init```
```npm install --save react react-dom @types/react @types/react-dom```

3. running ```tsc --jsx react main.tsx``` gives no compilation errors.   (I'm running tsc version 2.4.2)

4. in VS Code, there's a red squiggly under <Welcome>:

![image](https://user-images.githubusercontent.com/2461007/29958657-a2d0a15c-8ea8-11e7-8c4e-5d1ddfb36d6d.png)

It's not clear to me why the JSX element should need to have any "construct or call signatures", but this pattern seems to compile with tsc fine and run fine in the browser.

for reference, I also get the same error highlighting in Sublime Text, so perhaps it's an issue with the underlying Language Services server?  I could not find a separate repo for that server, so it was not clear if I should log the issue under vscode versus the Typescript repo, so please feel free to send me elsewhere if this issue does not seem like it belongs here.

**Comment by mjbvz** [comment]
A few questions:

1. What version of TypeScript is active in the workspace. This is shown in the status bar next to the language mode:

    
![screen shot 2017-09-01 at 10 50 48 am](https://user-images.githubusercontent.com/12821956/29981670-70c404a0-8f03-11e7-966e-dab3d908cca0.png)

2. If you run `go to definition` on something like `React.Component`, which file does it open up?

**Comment by uglycoyote** [comment]
Thanks, your question lead me to a resolution of this problem.   In the corner it said it was running Typescript 2.0.0.  I assumed that it would run whichever version of typescript my project declared in the package.json file.  Clicking on that in the corner brought me to the page which explained that the ```typescript.tsdk``` user setting can be used to point to a specific typescript installation.   After switching this setting and restarting VSCode, it said 2.4.2 in the corner and I no longer had the spurious "no construct or call signatures" error over the use of the SFC.

Incidentally, switching to 2.4.2 also made auto-completion on React Props working so I will close the other issue that I opened, #33641
