### ISSUE TITLE
PowerShell: DSC's Node keyword isn't highlighted

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3365]
In PowerShell Desired State Configuration (DSC), the `node` keyword is used to create "node blocks" inside a DSC `configuration` document. Unfortunately, this keyword isn't highlighted properly.

<img width="276" alt="screen shot 2016-02-23 at 11 30 51 am" src="https://cloud.githubusercontent.com/assets/466713/13262243/128ee370-da21-11e5-816a-329e47b35084.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by joaomoreno** [comment]
Merging into #3342

**Comment by pcgeek86** [comment]
@joaomoreno  whoops ... I totally forgot that I'd already mentioned the node keyword in that one. Total oversight. Sorry.
