### ISSUE TITLE
Search: ignore root folder that does not exist

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33657]
Related to https://github.com/Microsoft/vscode/issues/29738, once you have any root folder that does not exist, you can no longer do a search at all. I think we should fail more gracefully and still run the search for the other folders:

![image](https://user-images.githubusercontent.com/900690/29963844-83b5972c-8f08-11e7-865a-92af0ecb647c.png)

**Comment by roblourens** [comment]
Now it will only complain if none of the search paths exist.
