### ISSUE TITLE
SCM panel is stuck

### ISSUE THREAD

**Issue by asnowfix** [Microsoft/vscode#33654]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-database|baj|1.2.0
vagrant|bbe|0.5.0
vscode-standard-format|che|0.0.12
vscode-standardjs|che|1.1.8
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|4.4.3
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
mysql-scratchpad|jbl|0.1.1
plantuml|jeb|2.1.3
markdown-table-formatter|jos|0.2.3
vscode-github|Kni|0.18.1
VS-code-vagrantfile|mar|0.0.5
vscode-remark|mrm|1.1.0
debugger-for-chrome|msj|3.2.0
mysql-inline-decorator|odu|0.0.4
vscode-docker|Pet|0.0.16
java|red|0.9.0
vscode-sql-beautify|sen|0.0.4
markdown-pdf|yza|0.1.7
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Open multiple VSCode windows on different projects
2. Make changes in one of them (whether these changes are from within VSCode or using another editor does not matter)
3. SCM panel does not reflect changes. Refresh button does nothing <<< This is not 100% reproducible & sometimes it happens right after a full VSCode restart

Reproduces without extensions: No... **but** at this issue is not 100% reproducible, I am unsure about the problem solved is due to restarting or disabling extensions.

**Comment by joaomoreno** [comment]
Can you reproduce on another machine?

Does the file explorer update if you add new files to a visible folder?

**Comment by asnowfix** [comment]
I only have a single windows machine. I will test file addition from another source than vscode next time I face the problem.

**Comment by asnowfix** [comment]
I forgot to mention one thing I did to trouble-shoot. Once, restarting VSCode did not fix the issue. Going in the Windows task manager showed that there were multiple background VSCode processes, even after the UI was closed. Killing those background processes & restarting VSCode fixed my problem.

**Comment by joaomoreno** [comment]
Alright, good to know. Let me know if this happens often.

**Comment by asnowfix** [comment]
I reproduced it today. Killing the background task that was taking 15%-20% of CPU produced the following in the UI window: **Extension host terminated unexpectedly. Please reload the window to recover.**

![image](https://user-images.githubusercontent.com/212094/30164691-a75ff97c-93dd-11e7-8648-59991845a3e0.png)

So my issue is very likely due to one of the extensions. Now I/wee need to understand which one...
