### ISSUE TITLE
Opening an old .code-workspace file provides no help to the user

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33653]
1. I am a user who used vscode insiders for MR workspace as soon as it came out, so I got the .code-workspace file in the old format
2. After a month I am coming back to VSCode -> I use the "open workspace" action to load my workspace from 1.
3. The file is outputed as simple text and no help is shown

At the very least we could detect if a user just opened a .code-workspace file and if we can not parse it we could provide a nice info message so the user is not puzzled as to why his old .code-workspace is not working any more

**Comment by bpasero** [comment]
@isidorn can you attach the file here, we do a migration

**Comment by isidorn** [comment]
Paths point to existing directories
```
{
	"id": "1501686422165",
	"folders": [
		"file:///Users/isidor/Development/vscode",
		"file:///Users/isidor/Development/w"
	]
}
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33614
