### ISSUE TITLE
When using smooth scrolling, the diff editor does not jump to the first change

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#33659]
* have `"editor.smoothScrolling": true`
* close all editors
* click on a change
* the scroll is somewhere between the top of the file and the first change

![kapture 2017-09-01 at 11 31 09](https://user-images.githubusercontent.com/5047891/29964041-149b856c-8f09-11e7-87d0-e75a8426e6bb.gif)

**Comment by alexandrudima** [comment]
I cannot reproduce on master after pulling, so I think some other (perhaps git related) fixes also fixed this case.

**Comment by roblourens** [comment]
I can still repro this in the latest Insiders

**Comment by alexandrudima** [comment]
Let's investigate in September. It only happens when `editor.smoothScrolling` is on (it is off by default).

**Comment by eamodio** [comment]
I can still reproduce this - although it isn't 100% reproducible
