### ISSUE TITLE
recommended workspace extensions is not working

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#33656]
```
╭─phra at kali in /home/phra/git/bloqwallet (feat/bloqholder-registry ✚1)
╰─λ code -v                                                                                                                                                      0 < 11:09:46
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
```

Steps to Reproduce:

1. follow the tutorial [here](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) to create the `.vscode/extensions.json` file.
2. querying for `@recommended:workspace` results in a empty list.

![screenshot from 2017-09-01 11-12-59](https://user-images.githubusercontent.com/984628/29963419-11c5cf20-8f07-11e7-809a-5588818b5bf1.png)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@phra Do you also get an empty list when you run the command `Extensions: Show Workspace Recommended Extensions` ?

Do you have all those extensions already installed?

**Comment by phra** [comment]
@ramya-rao-a yes and yes, but it's the same on another pc without the extensions already installed.

**Comment by ramya-rao-a** [comment]
There is a spelling mistake :)

You are using `recommandations` in the json file instead of `recommendations`
