### ISSUE TITLE
Visual Studio Insiders opens the code-workspace files instead of the actual workspace defined by the file

### ISSUE THREAD

**Issue by KingDGrizzle** [Microsoft/vscode#33651]
Visual Studio doesn't actually open the `code-workspace` files as a workspace, but rather as a raw file.

- VSCode Version: 1.16.0-insider (commit 8b942faafb2d1bee6fd6a346853548d528c7eb5a)
- OS Version: Windows 10 x64 Creator Update

Steps to Reproduce:

1. Launch VS Code
2. Open Files > Open workspace

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33614
