### ISSUE TITLE
Diff editor no longer reveals change when file is open in an normal editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#33655]
It reveals the editor's cursor position.

The scm resource command needs to be decoupled with the editor title's one.

**Comment by liwangqian** [comment]
The Alt+W key does not work.

**Comment by joaomoreno** [comment]
@liwangqian Please file a separate issue if you see one.

**Comment by roblourens** [comment]
I don't understand the issue?

**Comment by chrmarti** [comment]
Verified by:
- have a file with changes open in a regular editor
- scroll that editor and place the cursor such that the changes are not visible
- open the diff editor from the SCM viewlet on that file
-> verify the diff editor scrolls to the first change in the file 👍
