### ISSUE TITLE
Total breakdown of syntax highlighting with ES6 factory functions

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode#33664]
- VSCode Version: 1.15.1
- OS Version: Fedora 26

Steps to Reproduce:

1. copy the code pasted below into vscode with Javascript as the language
2. observe the syntax highlighting fail

Please see the attached screen dump
![broken](https://user-images.githubusercontent.com/12832280/29964659-b1160702-8f02-11e7-939b-a5fb0de86590.png)

Reproduces without extensions: Yes

```js
    // Factory functions

    const createZombie = ({
        status = 1,
        width = 10,
        height = 10,
        xPosition,
        yPosition,
        color = "green"
    }) => ({
        status,
        width,
        height,
        xPosition,
        yPosition,
        color
    });

    const createHero = ({
        status = 1,
        width = 25,
        height = 50,
        xPosition,
        yPosition,
        color = "red"
    }) => ({
        status,
        width,
        height,
        xPosition,
        yPosition,
        color
    });
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#510

**Comment by mutik** [comment]
Not only arrow expressions, regex variables/constants are having problems as well. Examples below.
- VSCode: 1.17.0-insider
- OS: Win 10 Pro

```javascript
const regOpts = /^\[([\w:]+?)\]:#(.+)|^!\[(\w+?)\]\((.+)\)/u;
const regHead = /^(#{1,6})\s?(.+)/u;
const regQuot = /^(>{1,3})\s?(.*)/u;
const regLine = /^[-*_]{4,}(\{.+\})?/u;
const regUList = /^(\s*)[*\-+]\s(.+)/u;
```

**Comment by mjbvz** [comment]
@mutik I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/513 to track that  upstream
