### ISSUE TITLE
On open focus window which the user explicitly wants

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33660]
1. Have an untitled workspace, close vscode
2. `vscode-insiders .` in some folder
3. Notice that the unititle workspace also gets opened, which is fine however we should focus the window which the user explicitly opened

**Comment by roblourens** [comment]
Is this an issue? Slight variation:

- Have an empty workspace with an unsaved file
- `code-insiders .` from some folder
- The empty workspace is opened and focused. If I understand the fix, the user-specified workspace should be focused.

**Comment by bpasero** [comment]
@roblourens I cannot reproduce, when after I do "code-insiders ." I see a new window opening and the other one is not moved to front. Can you show a video?

**Comment by roblourens** [comment]
The untitled window opens and the vscode workspace is right behind it.

![sep-27-2017 22-13-39](https://user-images.githubusercontent.com/323878/30950386-60cdaab4-a3d1-11e7-8531-45033537ff12.gif)

I don't know if it matters that I'm starting code from the package like that. Also I have `    "window.restoreWindows": "all"`

**Comment by bpasero** [comment]
@roblourens oh I see, I can reproduce now.

**Comment by bpasero** [comment]
@roblourens I created https://github.com/Microsoft/vscode/issues/35295 but not for this milestone, can you verify Isis original steps please?
