### ISSUE TITLE
Makefile override does not work

### ISSUE THREAD

**Issue by jensskott** [Microsoft/vscode#33667]
- VSCode Version: 1.15.1
- OS Version: Fedora 26

Steps to Reproduce:

1. add to usersettings 
```json
    "[makefile]": {
        "editor.tabSize": 4,
        "editor.insertSpaces": false
    },
```
2. Tab in a makefile and see that the invis characters are space and not tabs
Reproduces without extensions: Yes

**Comment by rebornix** [comment]
@jensskott I didn't reproduce this issue with the same setting in an empty workspace. Can you check if you have workspace setting that overrides it?
