### ISSUE TITLE
点击  从侧边栏删除之后，文件夹就不能在从编译器运行了

### ISSUE THREAD

**Issue by pandaiiz** [Microsoft/vscode#33666]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
jquery-snippets|Hri|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
