### ISSUE TITLE
File marked as changed but there is no diff

### ISSUE THREAD

**Issue by rkotov93** [Microsoft/vscode#33668]
**Environment:**
- VSCode Version:  1.15.1
- OS Version: macOS Sierra 10.12.6

**Steps to Reproduce:**
1. Open a file
2. Remove any character and type it again
3. Tab will indicate that file is changed
4. Use undo to make tab indicate, that file was not changed

Looks like VSCode checks operations history instead of real diff

**Reproduces without extensions:** Yes

**Comment by joaomoreno** [comment]
Code is possibly fixing your end-of-line markers. Can you check if you have mixed end-of-line markers on that specific file? Can you reproduce on another file?

**Comment by rkotov93** [comment]
Hey @joaomoreno,

Here is what I did:

![](https://user-images.githubusercontent.com/640137/29969934-cfc815d0-8f22-11e7-8c05-7692de4f4a60.png)

I removed single quote on 13th line and typed it back:

![](https://image.prntscr.com/image/zUKWcHHvS9qFUDbj3vkM7w.png)

`git status` is empty even if I save the file.

**Comment by joaomoreno** [comment]
Oh. This has nothing to do with git.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
