### ISSUE TITLE
Some keyboard shortcuts are written in two ways

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#33677]
- VSCode Version: 1.15.1 -c[41abd21afdf7424c89319ee7cb0445cc6f376959]
- OS Version: Windows 8.1 64-bit OEM (Home) SK

Steps to Reproduce:

https://s26.postimg.org/o6w2ttlex/screenshot_50.png
![screenshot_50](https://user-images.githubusercontent.com/31345346/29970789-3e0aa06e-8f26-11e7-8194-01e79b1f699f.png)
Reproduces without extensions: Yes

**Comment by PurpleGranite** [comment]
This should be tagged as Accessibility due to the impact differential placement, shading, and description by screen readers has on sight-impaired developers.

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.

**Comment by Mlocik97-issues** [comment]
I think, shortcuts can have different colors that description of items in menu. Maybe as in native shortcuts can be lighter.
