### ISSUE TITLE
SCM menu is getting out of control

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33678]
IMHO you overdid it on the actions, there are simply too many now to make this a pleasent experience.
Consider removing some, if you need suggestions which I would be happy to help

![screen shot 2017-09-01 at 15 02 40](https://user-images.githubusercontent.com/1926584/29970896-b4f3fb30-8f26-11e7-9b3f-0d3f29b20546.png)

**Comment by isidorn** [comment]
Alternative is to make a commit submenu

**Comment by joaomoreno** [comment]
I don't agree. A lot of people go there to find actions. I can't do submenus, it's all coming from the git extension.
