### ISSUE TITLE
Comment script fails, unexpected exception

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#33676]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.20.0
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.2.3
gitlens|eam|4.4.3
vscode-great-icons|emm|2.1.15
json-tools|eri|1.0.2
vscode-git-tags|how|1.1.0
coldfusion|ili|0.0.11
vscode-cflint|Kam|0.2.0
autotrim|Nat|1.0.6
vscode-docker|Pet|0.0.16
startanyshell|rem|0.3.1
cfml-comment-tags|trs|0.2.2
shell-launcher|Tyr|0.1.3
sort-lines|Tyr|1.3.0
terminal-tabs|Tyr|0.1.1
gitflow|vec|1.1.1
vscode-todo-highlight|way|0.5.9
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Open scripted file.
2. press CTRL + /

Reproduces without extensions: No

It seems to be a feature of ( coldfusion|ili|0.0.11 ), but that code has not been updated in a long time. Happened after last update of VS Code. (as far as we both noticed).

**Comment by rcjsuen** [comment]
@sosensible When you say "scripted file", what are you referring to? JavaScript? TypeScript? CoffeeScript? Something else?

You mention that you suspect this may be related to the `coldfusion` extension. So you cannot reproduce the problem if you start VS Code with `code --disable-extensions`, correct?

**Comment by jrieken** [comment]
@sosensible More details please
