### ISSUE TITLE
We should only convert settings into the workspace settings section if certain preconditions are meet.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33670]
I create a workspace with n folder today and I ended up with the following workspace file.
```ts
{
	"folders": [
		{
			"path": "jsonrpc"
		},
		{
			"path": "types"
		},
		{
			"path": "protocol"
		},
		{
			"path": "server"
		},
		{
			"path": "client"
		},
		{
			"path": "client.tests"
		}
	],
	"settings": {
		"typescript.tsdk": "./node_modules/typescript/lib",
		"typescript.tsserver.trace": "off",
		"typescript.format.insertSpaceAfterCommaDelimiter": true,
		"typescript.format.insertSpaceAfterSemicolonInForStatements": true,
		"typescript.format.insertSpaceBeforeAndAfterBinaryOperators": true,
		"typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": true,
		"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
		"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
		"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
		"typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
		"typescript.format.placeOpenBraceOnNewLineForFunctions": false,
		"typescript.format.placeOpenBraceOnNewLineForControlBlocks": false,
		"javascript.validate.enable": false,
		"eslint.enable": false,
		"tslint.enable": false
	}
}
```

This shows to problems: Typescript didn't mark formatter settings as resource settings. I opened an separate bug for this.

ESlint did the adoption, but I didn't release a new version yet. To avoid polluting the workspace setting section we should be more careful of converting the settings and do the following:

- either let extension flag that they did the adoption by a special flag in the package.json file. If so we convert their settings. If not we leave the settings untouched.
- only convert a setting if it is explicitly marked as window in the package.json. We could still keep the default.

IMO we should address this for September 

//cc @egamma we discussed this 'I did the adoption' flag yesterday.

**Comment by sandy081** [comment]
@dbaeumer How did you create this workspace?

**Comment by dbaeumer** [comment]
@sandy081: vscode-languageserver-node repository. Opened jsonrpc folder and then added all other top level folders to it. Then saved as workspace.

**Comment by dbaeumer** [comment]
@sandy081 in addition I am not sure if you can simply take the setting and move it over. Take the `"typescript.tsdk": "./node_modules/typescript/lib"` setting as an example. Since before window === resource in terms of scope the setting was specified relative to the workspace (e.g. folder). Moving this not into the workspace setting without proper user interaction doesn't make to much sense since the relative path might not make much sense. Should it be relative to the first folder? relative to the location of the *.code-workspace file?

**Comment by sandy081** [comment]
For now, I will migrate only vscode internal settings. All of these are adopted and properly defined to  be a resource/window setting. 

I would not migrate settings coming from extensions until they are adopted to MR. In the above case `typescript.tsdk` should be defined as a resource setting. It is the responsibility of the extension owner to adopt and classify them properly. We would also need a flag or some way of knowing if an extension is adopted and ready for MR workspaces.
