### ISSUE TITLE
Screen reader detected -> help user to turn tab to move focus

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33679]
Currently we automatically detect that a screen reader is detected, however we could at that moment also automatically swithc tab to move focus. 
If you think that is too aggressive we could at least do a message via message service
"We have detected you are using a screen reader, would you like to use tab to move focus"

**Comment by alexandrudima** [comment]
@isidorn 

IMHO I don't think that makes sense. 

Folks using a screen reader still want to edit source code and potentially want to insert the tab character in editors. I am not convinced that switching the defaults for them would help.
