### ISSUE TITLE
Markdown position not stable while preview is open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33675]
Windows (could not repro on mac)
1. Clone our smoke test repo, open `readme.md` and open preview to side
2. On the line where you have `Instalation` just add some characters to the end. Notice how the editor which you are currently editing always jumps around. I find this very frustrating as it distracts me while working on markdown

**Comment by StingyJack** [comment]
I think there are two settings that are conflicting. 

I set the second one to false and its better for me (with mermaid charts that drastically alter the preview output as you type, this was really bad).


```
// Scrolls the markdown preview to reveal the currently selected line from the editor.
  "markdown.preview.scrollPreviewWithEditorSelection": true,

  // Mark the current editor selection in the markdown preview.
  "markdown.preview.markEditorSelection": true,

  // When the markdown preview is scrolled, update the view of the editor.
  "markdown.preview.scrollEditorWithPreview": true,
```

**Comment by mjbvz** [comment]
Should be fixed by new scroll sync logic
