### ISSUE TITLE
"Visual Basic" language should be labelled "Visual Basic .NET"

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3368]
Since it's derived from [this](https://github.com/textmate/asp.vb.net.tmbundle) is should be labelled "Visual Basic .NET". Visual Basic ended at v6.0.

**Comment by aeschli** [comment]
That just makes the label longer..
@chrisdias Chris, what do you think?

**Comment by Tyriar** [comment]
It's not correct though as I believe the language was forked for .Net and it adopted that name.

**Comment by chrisdias** [comment]
If anything I would rename it `VB`. We also use this for VB Script, so having the name be more generic gives us flexibility. When OmniSharp supports VB fully in VS Code then we can get specific on the name.
