### ISSUE TITLE
Incorrect line indent while debugging in editor

### ISSUE THREAD

**Issue by ITSecMedia** [Microsoft/vscode#33686]
Couldn't find a thread where this has been reported, but one might already exist ?
When I do step debugging in delve with VSCode the indentation changes.

- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. GoLang debugging with delve

![2017-09-01_17-07-49](https://user-images.githubusercontent.com/3316334/29975886-64e267f0-8f38-11e7-9cbe-df506beb8fdf.gif)

**Comment by isidorn** [comment]
Can you please try reproducing this with the latest vscode insiders?
https://code.visualstudio.com/insiders/

Thank you
