### ISSUE TITLE
make staged changes editable

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#33681]
Is there a reason why staged changes are read-only? Vim fugitive allows editing the index.
It's a bit cumbersome to unstage, edit, stage (especially if that requires ranges).

- VSCode Version: Version 1.15.1 (1.15.1)
- OS Version: macOS 10.13 Beta

**Comment by joaomoreno** [comment]
As suggested in #15785, this can be implemented by an extension. Feel free to give it a try.
