### ISSUE TITLE
[Feature Request] "label marks" in code section.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#33689]
![screenshot_56](https://user-images.githubusercontent.com/31345346/29978275-be87c5d6-8f40-11e7-8414-41fb2a2f0ded.png)

When I have some code, I want sometimes mark some code (section), but use something what will not see in code. 

Can you add these labels?
I saw something like it in Visual Studio,...

 it shouldn't increase real code (file), only it marked section of code in editor.

maybe it could be created by right click on [+]...

(sry, for my English)

**Comment by jrieken** [comment]
You mean something like this: https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

**Comment by Mlocik97-issues** [comment]
@jrieken yes,...
