### ISSUE TITLE
Unable to parse content from 'vscode://schemas/workspaceConfig'

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33698]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

---

Steps to Reproduce:

1. Open a .code-workspace file in the editor
2. A warning is shown on the first character: `'Unable to parse content from 'vscode://schemas/workspaceConfig': Parse error at offset 0.' at: '1,1' source: ''`

**Comment by sandy081** [comment]
@chrmarti I do not see any such warnings.. Is it possible to share the file. Also see the source of this warning from Problems view.

**Comment by chrmarti** [comment]
@sandy081 It's a regular workspace file:

![image](https://user-images.githubusercontent.com/9205389/30167398-1ea77944-939b-11e7-9040-a0f02fdb475d.png)

**Comment by sandy081** [comment]
Ah I see.. Its when you open this file from a VS Code window opened with Single folder.

**Comment by burito** [comment]
I'm pretty sure this bug isn't fixed... I'm getting 

    Unable to parse content from 'vscode://schemas/launch': Parse error at offset 0.

**Comment by sandy081** [comment]
This is a different schema. Please file a new issue with steps to reproduce.
