### ISSUE TITLE
Workspace and build task

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#33693]
- VSCode Version: cc2cedf6adc622094b9c61d82b66486aee0a563f
- OS Version: windows 10 x64

When using workspace, you can't initiate multiple build tasks, it always uses the first folder tasks.json. Entering any file from any other folder does not change this behavior

Steps to Reproduce:

1. Create a workspace
2. Try to initiate a build task othan than the first folder in the workspace

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Adding multi folder support is planned for September.

**Comment by dbaeumer** [comment]
Support for multi root workspaces got added for next stable release. It is in the insider already.
