### ISSUE TITLE
Does not open a local file from Windows Explorer

### ISSUE THREAD

**Issue by gabrielius** [Microsoft/vscode#33696]
**Setup:**
- OS Version: Windows 10, x64
- VS Code version:
![image](https://user-images.githubusercontent.com/7396135/29982406-4007d7ea-8f5a-11e7-96ed-7d6b00990926.png)

**Steps to Reproduce:**
1. Double click a file in Windows Explorer (if VSCode is default program for that extension)
OR
1. Right click on a file > Open With > Visual Studio Code

**Reproduces without extensions:** Yes

**Notes:**
I noticed that **Computer\HKEY_CLASSES_ROOT\vscode\shell\open\command** has this default value: 
`"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --open-url "%1"`

So I tried removing `--open-url` and it works for the first time, because VSCode automatically updates the registry and adds `--open-url` again thus unfixing my fix :(

**Comment by bpasero** [comment]
Complete uninstall and reinstall will fix this.
