### ISSUE TITLE
SCM viewlet does not remove deleted Git repo when deleting its folder

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33695]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

Steps to Reproduce:

1. Start with an empty folder in a workspace
2. `mkdir subfolder; cd subfolder; git init; cd ..`
3. -> SCM viewlet shows Git repo
4. `rm -r subfolder`
5. -> SCM viewlet continues to show Git repo although it no longer exists

**Comment by joaomoreno** [comment]
Fixed in `master`.
