### ISSUE TITLE
SCM viewlet picks up Git repo in user data dir

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33690]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

Steps to Reproduce:

1. Have user data dir under Git control
2. Show SCM viewlet
3. Open user settings
4. -> SCM viewlet shows the user data dir's Git repo (with layout issues)

![image](https://user-images.githubusercontent.com/9205389/29981477-a715867e-8f02-11e7-88a9-258bb8f2b633.png)

**Comment by joaomoreno** [comment]
Is this not expected?

**Comment by chrmarti** [comment]
Ah...maybe :D
