### ISSUE TITLE
Feature request: Add/Edit orgin

### ISSUE THREAD

**Issue by josewhitetower** [Microsoft/vscode#33708]
- VSCode Version: 1.15.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open a Folder/Project
2. Control Version (Ctrl + Shift + G )
3. (...) More

On that menu there should be a way to Add/Edit the origin of the repository. Till now you can initialize a repository locally. It would be practical to add an option to add/edit the origin of that repository and not making it necessary to do it via the command line. Something to excecute the comand: `git remote add origin [address]`

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#21189
