### ISSUE TITLE
VS Code's Emmet will not wrap individual lines with <li> tag

### ISSUE THREAD

**Issue by mamamusings** [Microsoft/vscode#33703]
When using Emmet's "wrap with abbreviation" on a multi-line block of text, ul>li* (or ol>li*) creates a single list item rather than one list item per line. 

---

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
replace-smart-characters|DrM|0.0.2
lorem-ipsum|Tyr|1.0.0
git-easy|bib|1.9.1
htmltagwrap|bra|0.0.3
jshint|dba|0.10.15
vscode-hasher|dee|1.0.1
ftp-simple|hum|0.5.5
HTMLHint|mka|0.3.3
stylelint|shi|0.28.0
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. In .html file, select a series of lines separated by carriage returns
```
   list 1
   list 2
   list 3
```
2. Press F1 to bring up command palette
3. Enter "Emmet: Wrap With Abbreviation"
4. Enter the abbreviation `ul>li* ` (as documented at https://docs.emmet.io/actions/wrap-with-abbreviation/#wrapping-individual-lines)

Result:  
```html
    <ul>
        <li>
            list 1
            list 2
            list 3
        </li>
    </ul>
```

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@mamamusings Use the command `Emmet: Wrap Individual Lines with Abbreviation` instead.

With our move to [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) and support for multi cursor, this feature has been moved to a separate command.

I missed updating this information in the blog last month, sorry about that.

**Comment by mamamusings** [comment]
Thanks!
