### ISSUE TITLE
Debug server won't start

### ISSUE THREAD

**Issue by littlepwn** [Microsoft/vscode#33706]
- VSCode Version: 1.15.1
- OS Version: Windows 10 64x bit

I don't know what is causing the problem but whenever I try debugging my python project

There was an error in starting the debug server. Error = {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3000}

appears in the debug console, and obviously it won't let me debug my code. Anyone know how to fix this?

**Comment by isidorn** [comment]
Please file this against the python extension here https://github.com/DonJayamanne/pythonVSCode
