### ISSUE TITLE
Can't expand HTML snippets/Emmet in JSX javascript file

### ISSUE THREAD

**Issue by davi-mbatista** [Microsoft/vscode#33702]
- VSCode Version: Version 1.15.1 
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. write 'div' or any other HTML tag name on a js file and press tab to expand

**Comment by Mlocik97-issues** [comment]
Dupl #33700

**Comment by ramya-rao-a** [comment]
Thanks @Mlocik97-issues 

Closing this issue as duplicate
