### ISSUE TITLE
Can't expand HTML snippets/Emmet in JSX javascript file

### ISSUE THREAD

**Issue by davi-mbatista** [Microsoft/vscode#33700]
- VSCode Version: Version 1.16.0-insider
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. write 'div' or any other HTML tag name on a js file and press tab to expand

**Comment by ramya-rao-a** [comment]
For enabling emmet in js files you need to set
```
"emmet.includeLanguages": {
    "javascript:: "html"
}
```

For expanding emmet using tab you need to set `emmet.triggerExpansionOnTab` to `true`.

Have you done both of the above?

**Comment by ramya-rao-a** [comment]
Also please read the [Release Notes](https://code.visualstudio.com/updates/v1_15#_emmet-20) or the [blog on Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)

**Comment by davi-mbatista** [comment]
@ramya-rao-a I've added the extra config that you provided and now it works. But it wasn't the case before the latest update. Anyways, thanks.
