### ISSUE TITLE
Show Accessibility Help Alt+F1 hotkey is an invalid on Ubuntu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3371]
#3246

<kbd>alt</kbd>+<kbd>F1</kbd> focuses the launcher and allows keyboard navigation on Ubuntu. Show Accessibility Help can be accessed via command palette in a text view though.

**Comment by joaomoreno** [comment]
@Tyriar could you figure out an alternative keybinding for Ubuntu?

**Comment by Tyriar** [comment]
@joaomoreno It appears that this dialog's only purpose is to show help (which shouldn't belong in a hidden hotkey) and to turn on screen reader support. Screen readers aren't working on Linux due to an upstream issue, correct?

**Comment by joaomoreno** [comment]
Not really sure. They might not work simply because we never tackled that problem. Ping @bpasero

**Comment by bpasero** [comment]
No screen reader support in Chrome for Linux.

**Comment by Tyriar** [comment]
Closing since it's not supported anyway.
