### ISSUE TITLE
c# quickSuggestions/intellisense closes quickly when auto triggered by dot '.'

### ISSUE THREAD

**Issue by uday0408** [Microsoft/vscode#33710]
- VSCode Version:  1.15.1
- OS Version: macOS Sierra 10.12.6
- Omnisharp version: 1.12.1

Steps to Reproduce:

1. Trigger quickSuggestions/intellisense in c# code with dot '.' char.
2.

When triggering editor quickSuggestions with dot '.' char it opens and closes in a second. But when quickSuggestions are manually triggered by key binding, they stay open until closed. Once in a while, the auto triggered quickSuggestions do stay open until closed. I'm not sure what is responsible for this behavior.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Sorry, I cannot reproduce. Please provide a code sample that illustrates the problem 

![sep-04-2017 09-45-39](https://user-images.githubusercontent.com/1794099/30016547-dfaad9b2-9155-11e7-88fd-dbe91b1747d5.gif)
