### ISSUE TITLE
Feature request: Make extensions standalone and downloadable so that can install it offline.

### ISSUE THREAD

**Issue by x-strong** [Microsoft/vscode#33719]
Feature request: Make extension standalone and downloadable so that can install it offline, or make extension no need to installed, just unzip and place it into the extensions folder and restart the vs code then the new extension works.

- VSCode Version: all versions.
- OS Version: all versions.

Steps to Reproduce:
- no step.

**Comment by fabiospampinato** [comment]
This is already supported, just download an extension from the marketplace:
<img width="169" alt="download_ext" src="https://user-images.githubusercontent.com/1812093/29994908-c8fb52a8-8fdb-11e7-9c75-050766cebad1.png">
And then run the `Extentension: Install from VSIX...` command in VS Code.

If you want to make the `.vsix` file out of an unpublished extension, perhaps one you are currently working on, just package it using `vsce package`.

If you plan to install many extension this way I recommend [this extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix) that adds the ability to install them with a right click.

**Comment by x-strong** [comment]
@fabiospampinato Very good and thank you very much!
