### ISSUE TITLE
Feature request: Disable found text indicators on right-hand side of VS-Code

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode#33713]
- VSCode Version: 1.16 Insiders build
- OS Version: macOS 10.12.6 Sierra

Steps to Reproduce:

1. This is a feature request.
2. When using "Zen Mode", the presence of the found text indicators is a great distraction, shown highlighted in the attached image.
3. A facility to disable them (if it doesn't exist already, and I have searched high and low!) would be most welcome.

Reproduces without extensions: Yes
![screen shot 2017-09-02 at 00 18 03](https://user-images.githubusercontent.com/260612/29990673-db90e566-8f74-11e7-9fc5-36b76021949e.png)

**Comment by rcjsuen** [comment]
You don't find it distracting when you're not in Zen Mode?

So you want variables to only be highlighted in the editor but not in the margin on the right hand side of the editor?

**Comment by carlca** [comment]
The point is that as I scroll up and down the code, depending on which variable my cursor happens to pass over, the selection of points on the right-hand side of the screen changes rapidly - the effect is not quite stroboscopic, but it is very distracting to have that going on in one's peripheral vision. I'd rather that the right-hand column is invisible, while I am in "Zen Mode".

**Comment by carlca** [comment]
Or at least, have the option of configuring it as invisible.

**Comment by fabiospampinato** [comment]
I think there isn't any setting for hiding it completely.

But you can at least remove the border, which I find pretty distracting, by putting this in your configuration: 
```json
  "workbench.colorCustomizations": {
    "editorOverviewRuler.border": "#00000000"
  }
```

If that's not enough install [this](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension and with a bit of css you can hide it completely.

**Comment by carlca** [comment]
Thanks for the reply Fabio, but the `"editorOverviewRuler.border": "#00000000”` line didn’t make any difference, and I installed the extension, but it it no clear how to actually use it!

Cheers,
Carl

**Comment by fabiospampinato** [comment]
@carlca perhaps you have to restart VSC in order to see the different, that setting removes the tiny 1px border at the left of that bar.

Regarding the extension you have to put something like this in your settings, pointing to the CSS file you want to load:
```json
  "vscode_custom_css.imports": [
    "file:///path/to/custom.css",
  ]
```

In that file you should write the following:
```css
canvas.decorationsOverviewRuler {
    display: none !important;
}
```

Then run the `Enabled Custom CSS and JS` command from the command palette and reload VSC.

**Comment by alexandrudima** [comment]
@carlca

```
"editor.overviewRulerBorder": false,
"editor.hideCursorInOverviewRuler": true,
"workbench.colorCustomizations": {
	"editorOverviewRuler.findMatchForeground": "#ff000000",
	"editorOverviewRuler.rangeHighlightForeground": "#ff000000",
	"editorOverviewRuler.wordHighlightForeground": "#ff000000",
	"editorOverviewRuler.selectionHighlightForeground": "#ff000000"
}
```
