### ISSUE TITLE
Column/Block Paste should be pasted as a block

### ISSUE THREAD

**Issue by nexional** [Microsoft/vscode#33716]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
read-only-indicator|ale|0.6.0
shell-snippets|cds|0.1.2
npm-intellisense|chr|1.3.0
python|don|0.7.0
xml|Dot|1.9.2
reg|ion|0.0.1
ecdc|mit|0.10.3
PowerShell|ms-|1.4.1
vba|spe|1.0.17
shell-launcher|Tyr|0.1.3
sort-lines|Tyr|1.3.0

---
Steps to Reproduce:

1. Select any block using Shift+Alt+(MouseDrag)
2. Copy it using Ctrl+C
3. Try to paste it anywhere else in the code
4. It's pasted like a regular lines & not as a block

Reproduces without extensions: Yes/No

Is it possible to include this feature.

**Comment by zittix** [comment]
+1

**Comment by psifertex** [comment]
Possible dupe of #5940?
