### ISSUE TITLE
why is there a square in the command line?

### ISSUE THREAD

**Issue by cuiyongjian** [Microsoft/vscode#33727]
- VSCode Version: 1.15
- OS Version:  macOS serria  10.12.3

![image](https://user-images.githubusercontent.com/3937196/29995720-a9d35b54-9022-11e7-90f8-69f11fadecfa.png)

Why there is a square icon in the vscode build-in commond line?

**Comment by gamunu** [comment]
@cuiyongjian It seems like you are using `zsh` and missing `powerline fonts`. Try [installing powerline fonts](https://powerline.readthedocs.io/en/latest/installation/osx.html).
If fonts are already installed try setting the `terminal.integrated.fontFamily`.
e.g. `"terminal.integrated.fontFamily": "Source Code Pro for Powerline"`

**Comment by cuiyongjian** [comment]
@gamunu   yeal, it work, thank you very much.
