### ISSUE TITLE
The 'go to definition' function doesn't work when I use javascript, the vscode version is 1.15.1

### ISSUE THREAD

**Issue by shenshanyoumu** [Microsoft/vscode#33722]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
Works fine for me, @shenshanyoumu.
```JavaScript
var variable = "";
variable.toString();
```
I placed my cursor on the second line's `variable` and then used 'Go to Definition' from the context menu and it jumped to the first line.

Please provide some steps to reproduce the bug.

**Comment by mjbvz** [comment]
Yes, please provide some example code so we can investigate this

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
