### ISSUE TITLE
Emmet Abbreviatio not working with number endings

### ISSUE THREAD

**Issue by RBFraphael** [Microsoft/vscode#33726]
Since the last two or three updates, my VS Code is not automatically showing suggestions for snippets ending with numbers. I use VS Code for web development (HTML, CSS, JS, and PHP), and the issue only occurs on PHP files. In HTML files all are ok.

Example: to create a Bootstrap col-xs-12, we just need to type ".col-xs-12" and press Tab in HTML, but in PHP is not working (but, with snippets that not ends with numbers - tested with fictional ".col-xs" and ".col-xs-12e" - works fine).

PS: no extensions are installed

- VSCode Version: 1.15.1
- OS Version: Windows 10 x64 15063.540

Steps to Reproduce:

1. Insert some code snippet ending with numbers (like .col-xs-12 for creating a bootstrap formatted div)
2. Autocompletion not shows automatically (needs to press Ctrl + Space to show dropdown)

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Completions are triggered based on word definitions or trigger characters defined by completion providers.
`-` is not part of the word definition in php.
And so `col-xs-12` doesn't get treated as a word.

Fixing this with adding numbers to trigger characters for emmet completion provider
