### ISSUE TITLE
File suggestions for Node require() function

### ISSUE THREAD

**Issue by crazyredd** [Microsoft/vscode#33729]
It is quite annoying to keep working out the exact file path of a .js or .json file every time I want to include something, especially if I have to traverse backwards. Would it be possible to use the directory of the current document and the relative file being typed in to list file results that I would want to include?

**Comment by mjbvz** [comment]
We should provide this already. Can you try triggering suggestions using `ctrl+space` while typing out the path. If this does not work, please share small snippet showing where the `require` call is

**Comment by crazyredd** [comment]
Whoops, my mistake. Works for me. Sorry about this issue
