### ISSUE TITLE
Custom snippet doesn't work

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#33723]
`javascript.json`

```
{
    "res.json": {
        "prefix": "rj",
        "body": [
            "res.${1:status(${2:code}).}json({${3:key}: ${4:value}});",
            "$2"
        ],
        "description": "res.json"
    }
}
```

Then in `file.js` I type `rj` and nothing happens. The IDE doesn't suggest a snippet. Why? How to fix?

Version:

![visual studio code 2017-09-02 18 46 51](https://user-images.githubusercontent.com/3880497/29994945-27feeb74-900f-11e7-8fb8-99bc63dd8c4d.png)

**Comment by Cologler** [comment]
try replace 

`"res.${1:status(${2:code}).}json({${3:key}: ${4:value}});",` 

to 

`"res.${1:status}(${2:code}).json({${3:key}: ${4:value}});",`

**Comment by jrieken** [comment]
Does the snippet show up in the F1 > Insert Snippet menu? Also, have an empty file and hit  Cmd+Space and check that the snippet shows up

**Comment by wzup** [comment]
@jrieken 
1. No, the snippet doesn't show up on `F1` > `Insert Snippet`.
2. Snippet doesn't show up as well.

What does that mean? Wrong snippet syntax?

**Comment by jrieken** [comment]
It depends on the extension you have installed. The 'Babel' thing sound suspicious, it might steal the `.js`-suffix and use it for another language. Open a JS file and check on the lower right what the language name reads? It should be "JavaScript", not "JavaScript (Babel)". Also, try to disable the extensions that added this and try to reproduce

**Comment by wzup** [comment]
Here is the same thing https://github.com/Microsoft/vscode/issues/19954

**Comment by wzup** [comment]
I found culprit. This is [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) by [Josh Peng](https://marketplace.visualstudio.com/search?term=publisher%3A%22Josh%20Peng%22&target=VSCode&category=All%20categories&sortBy=Relevance)

I had two Babel plugins installed:
1. [Sublime Babel](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) by [Josh Peng](https://marketplace.visualstudio.com/search?term=publisher%3A%22Josh%20Peng%22&target=VSCode&category=All%20categories&sortBy=Relevance)
2. [Babel ES6/ES7](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring) by [dzannotti](https://marketplace.visualstudio.com/search?term=publisher%3A%22dzannotti%22&target=VSCode&category=All%20categories&sortBy=Relevance)

I disable the first and snippets started working. Though on the lower right the language name is still `Javascript (Babel)`.

![js babel - 2017-09-12 23 52 24](https://user-images.githubusercontent.com/3880497/30336538-10593d56-9818-11e7-8114-678af318805e.png)
