### ISSUE TITLE
List all open files in the ... more tab menu

### ISSUE THREAD

**Issue by josh-nz** [Microsoft/vscode#33724]
To the right of the opened tabs in VS Code is the "more" ellipsis, ( ... ). Clicking this provides an option to "Show Opened Editors", which lists all open files in a Ctrl-P style drop menu. This works, but it requires an extra mouse click (on "Show Opened Editors") before you can select the file you wish to switch to.

Keyboard users will of course know the correct short cut to directly show the Ctrl-P style drop list, but is there a reason as to why mouse users are required to perform an extra step? Could VS Code instead just list the opened editors directly in the "more" menu like other editors?

Compare the attached screenshots showing VS Code vs Visual Studio. In Visual Studio, the opened files are directly listed and can immediately be selected.

I would like an option for VS Code to behave like Visual Studio does.

My apologies is this has been asked or discussed before. I tried searching, but without knowing the extra terminology that VS Code uses, any search becomes a generic "list all files" sort of query, which doesn't help.

- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. See above, and screenshots for reference

Reproduces without extensions: Yes

VS Code:
![vscode](https://user-images.githubusercontent.com/414204/29995001-8dd45d26-9032-11e7-828c-c329af32f18c.png)

Visual Studio:
![vs](https://user-images.githubusercontent.com/414204/29995002-951abf62-9032-11e7-8132-d9615eb5959f.png)

**Comment by PixelT** [comment]
+1

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
