### ISSUE TITLE
TextDocument.isClosed = true even when document is not closed

### ISSUE THREAD

**Issue by danielkupco** [Microsoft/vscode#33728]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Open some 2 documents within the same editor
2. Switch from one to another document

Explanation:

Both _**onDidChangeActiveTextEditor**_ and _**onDidCloseTextDocument**_ events are fired. On the latter one, document's property _**isClosed**_ is set to _**true**_, even if it is not closed (it just lost focus).

I need the information if some file is actually closed, not just if focus switched from it to some another file.

**Comment by jrieken** [comment]
Exposing the tab-model is what you want: #15178

**Comment by danielkupco** [comment]
Actually, I do not think so. I do not need to see what are the open editors.

I need the information whether some document is closed. There is **_TextDocument.isClosed_** property but it seems it is always **true**, whether it is switched from or it is actually closed. If I just move to another document, **_onDidCloseTextDocument_** event is fired for the previous document, which is fine. But why it has **_.isClosed_** property set to **true** when it is not closed?

I would rather just read **_.isClosed_** property and check if it is **true** (but only then) to know that document has been closed instead of iterating through all open editors and check if it exists among them every time document focus has been changed.

**Comment by jrieken** [comment]
'isClosed' doesn't refer to UI state but means that the file is unloaded and not there anymore. This happens when you switch tabs. In reality there is just 1 editor for all tabs (per editor group/column) and when you switch tabs we close the open the new document, set it to the one editor, and close the old document.
