### ISSUE TITLE
Cmd popups when I open vscode

### ISSUE THREAD

**Issue by AustinKerr42** [Microsoft/vscode#33738]
![applicationframehost_2017-09-02_23-58-06](https://user-images.githubusercontent.com/22462157/30000707-70882744-903b-11e7-8934-c5755e273331.png)
![applicationframehost_2017-09-03_00-01-14](https://user-images.githubusercontent.com/22462157/30000706-70859cf4-903b-11e7-89d5-de8617d38a0c.png)
![applicationframehost_2017-09-03_00-01-28](https://user-images.githubusercontent.com/22462157/30000705-708435da-903b-11e7-839e-09be1a52602e.png)

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
php-debug|fel|1.11.1

---
When I open vscode a bunch of terminals relating to the -login popup and then disappear very quickly. Not sure why this started happening or how to fix it.

Steps to Reproduce:

1. Open vscode...
2. This only just started happening. Haven't had issues in the past.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
likely a dupe

**Comment by joaomoreno** [comment]
@AustinKerr42 What are your user settings?

**Comment by AustinKerr42** [comment]
It seemed to be an issue with my git settings. I had the "git.path" set to my bash executable and when I commented that out it stopped happening. Solved.
