### ISSUE TITLE
Can't start vscode from the debug configurations

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#33732]
I'm on debian artful
commit 465c3ed79335a971cbce040f003d205a4c141e15

I get this error when I try to debug vscode from the `Launch VS Code` configuration or the `Debug VS Code Main and Renderer` configuration

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Got a response from the target app, but no target pages found).
```

**Comment by QwertyZW** [comment]
Just a note that I had this working fine before I  did git pull ffonly on master and scripts/npm.sh install --arch=x64

**Comment by isidorn** [comment]
This works fine for me on my mac. Please note that we have updated the electron we use and you might need to do a workaround in order to make this work
https://github.com/Microsoft/vscode/issues/33490#issuecomment-325929670
@QwertyZW Can you please see if that workaround helps?

Assigning to @roblourens as he might have more details as the Launch VS Code configuration is using the `chrome` debugger under the hood.

**Comment by roblourens** [comment]
The workaround shouldn't be necessary, you might have something using the port, like a zombie instance of Code-OSS. You can see if something else responds on `http://localhost:9222/json`, or kill any leftover instances of Code-OSS, or set `port` to something else in the "Launch VS Code" config.

**Comment by QwertyZW** [comment]
@roblourens  I'd usually do `pkill -f vscode` and sometimes just `pkill -f code` when I get desperate.

`netstat -nap | grep -E "LISTEN\s` yields no results
```
khishman@khishman-desktop:~/dev/vscode$ netstat -nap | grep -E "LISTEN\s"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
tcp6       0      0 ::1:25                  :::*                    LISTEN      - 
```
But I'm noticing this error being thrown in the debug console
```
null: Object {errorCode: "load", moduleId: "vs/code/electron-main/main", neededBy: Array(1), detail: Error: ENOENT: no such file or directory, open '/h…}
detail: Error: ENOENT: no such file or directory, open '/home/khishman/dev/vscode/out/vs/code/electron-main/main.js'
code: "ENOENT"
errno: -2
message: "ENOENT: no such file or directory, open '/home/khishman/dev/vscode/out/vs/code/electron-main/main.js'"
path: "/home/khishman/dev/vscode/out/vs/code/electron-main/main.js"
stack: "Error: ENOENT: no such file or directory, open '/home/khishman/dev/vscode/out/vs/code/electron-main/main.js'"
syscall: "open"
__proto__: Object {name: "Error", message: "", constructor: , …}
errorCode: "load"
moduleId: "vs/code/electron-main/main"
neededBy: Array(1) ["===anonymous1==="]
__proto__: Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}
```

`npm run watch` yields 
```
hishman@khishman-desktop:~/dev/vscode$ npm run watch

> code-oss-dev@1.17.0 watch /home/khishman/dev/vscode
> gulp watch --max_old_space_size=4096

[16:11:15] Node flags detected: --max_old_space_size=4096
[16:11:15] Respawned to PID: 16264
Could not load our cross platform file watcher: Error: The module '/home/khishman/dev/vscode/build/lib/watch/node_modules/nsfw/build/Release/nsfw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
Falling back to our platform specific watcher...
```

and so I'd  try

`./scripts/npm.sh rebuild`

with which I finally arrive at

```
Downloading ripgrep failed: Error: Missing ./_node_modules...

npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/home/khishman/.nvm/versions/node/v7.4.0/bin/node" "/home/khishman/.nvm/versions/node/v7.4.0/bin/npm" "rebuild"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vscode-ripgrep@0.0.25 postinstall: `node ./dist/postinstall.js`
npm ERR! Exit status 1
```

I'm a bit at a loss here

**Comment by roblourens** [comment]
Just try a `git clean -xfd` and start over with `./scripts/npm.sh install` and `npm run watch`. You might have npm installed across an electron update, which often requires you to clean everything out.

**Comment by QwertyZW** [comment]
that worked, I didn't know about `git clean -xdf` I manually `rm -rf`ed everything but `.git` and followed by a `git checkout` followed by the setup commands

thanks @roblourens !

**Comment by roblourens** [comment]
Great!
