### ISSUE TITLE
Launching Vscode from git bash makes it impossible to clear the terminal window

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#33730]
- VSCode Version: 1.15.1 x64
- OS Version: Windows 10

Steps to Reproduce:

Launch vscode from git bash.
`$ code .`

Open the terminal run some commands to fill the windows.

Then try to clear the windows. `CTRL + L` or `clear`.

ps: If I launch vscode from the system  everything works fine.

I have git bash in the terminal window inside vscode

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Can you provide a screenshot of what happens after you run `clear`?

**Comment by sfabriece** [comment]
There you go.
![git-bash-clear](https://user-images.githubusercontent.com/3108592/30512331-684bbade-9aed-11e7-863e-fb627ba53dbb.gif)

**Comment by ioanungurean** [comment]
Hello, any updates on this? I have the same problem.

**Comment by Tyriar** [comment]
@rprichard any idea why clear would not be clearing the terminal?

**Comment by hansnow** [comment]
Same issue. Only launch vscode via `code <some-folder>` in git bash will trigger this bug. same command in cmd works fine.

**Comment by abdulghani** [comment]
same exact issue here 😩 if i launch vscode from git-bash it won't clear the terminal 😭😭

**Comment by nateous** [comment]
would love to stay inside vscode integrated terminal for work but not having clear is really annoying... is this slated to get worked?

**Comment by Tyriar** [comment]
@nateous try ctrl/cmd+k (windows/mac) or trigger the "Terminal: Clear" command through the command palette (F1).

**Comment by farrukhmomin** [comment]
@Tyriar thanks, ctrl+k works.

**Comment by Tyriar** [comment]
Tracking this in https://github.com/Microsoft/vscode/issues/45693

In the meantime ctrl+k (WIndows), cmd+k (macOS) will still clear the terminal properly, you can also run the command through the command palette. If the keybinding is not working for you see the FAQ on https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions about fixing the issue.

**Comment by PauloGasparSv** [comment]
I have this issue everyday... it's actually the one and only issue i have with vscode.
When i first open a folder with vscode, the git bash terminal does not clear itself when i use the "clear" command. Using ctrl+k (i'm using windows 10) does not fix the issue since it clears the terminal but once i start typing, the previous state of the terminal overlaps whatever i was trying to type.

**Comment by mehulmpt** [comment]
I'm facing the same bug which @PauloGasparSv told
