### ISSUE TITLE
Integrated Terminal is dead. No possible to input any commands. (x64 Architecture)

### ISSUE THREAD

**Issue by akalcik** [Microsoft/vscode#33733]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.20.0
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.2.3
gitlens|eam|4.4.3
LogFileHighlighter|emi|1.1.1
code-runner|for|0.7.1
vscode-jekyll-snippets|gin|0.8.1
live-html-previewer|hdg|0.2.0
rest-client|hum|0.15.2
jwt|ina|1.3.0
csharpextensions|jch|1.3.0
vscode-github|Kni|0.18.1
ecdc|mit|0.10.3
mssql|ms-|1.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
vs-keybindings|ms-|0.1.7
language-liquid|nei|0.0.2
vscode-docker|Pet|0.0.16
htmlescape-vscode-extension|ray|0.0.4
java|red|0.9.0
code-settings-sync|Sha|2.8.3
git-autoconfig|shy|0.0.1
vscode-autohotkey|sle|0.2.1
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Uninstall x32 version 
2. Install x64 version
3. Open the integrated terminal

Integrated Terminal is dead. There isn't possible to input any commands. I tried multiple terminals: command-line, bash, PowerShell, always the same.

Reproduces without extensions: No

**Comment by Tyriar** [comment]
@akalcik what's in your settings.json file?

**Comment by akalcik** [comment]
@Tyriar Good point. As I comment out (all) ```terminal.integrated.shell.windows```  entries, integrated terminal is running. But probably it is a bug or some settings has been changed. This is my _settings.json file.


```
// Place your settings in this file to overwrite the default settings
{    
    // "terminal.integrated.shell.windows": "\\windows\\sysnative\\cmd.exe",
    // "terminal.integrated.shellArgs.windows": [
    //     "/k",
    //     "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    // ],
    // "terminal.integrated.shell.windows": "\\Windows\\sysnative\\bash.exe",
    "terminal.integrated.shell.windows": "\\windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.sideBar.location": "left",
    "window.openFilesInNewWindow": "default",
    "window.zoomLevel": 0,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 5000,
    "sync.gist": "", //value removed because of secret
    "sync.lastUpload": "2017-08-03T20:08:05.875Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "2017-08-30T16:18:04.756Z",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "mssql.connections": [
        {
            "server": "(localdb)\\MSSQLLocalDB",
            "database": "",
            "authenticationType": "Integrated",
            "password": ""
        }
    ],
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "git-autoconfig.configList": [
        {
            "user.email": "",  //value removed because of secret
            "user.name": ""  //value removed because of secret
        }
    ],
    "workbench.colorTheme": "Default Light+",
    "sync.askGistName": false
}
```

**Comment by Tyriar** [comment]
Changing sysnative to System32 should fix the issues

**Comment by akalcik** [comment]
@Tyriar Yes, I can commit it resolves my issue.
