### ISSUE TITLE
VStudioCode seems to create gigabytes of write load

### ISSUE THREAD

**Issue by Nelvin** [Microsoft/vscode#33734]
Is there a way to stop VSCode trashing harddirves/ssds? As soon as I activate any VSC window and create some input events like moving the mouse over the window etc., it's going to write about 50-500kb/sec to my drive and I have absolutely no clue why/what it's writing but it sums up to gigabytes of write load in a very few hours of regular usage of VSC.

I use the process explorer tool from sysinternals to display the amount of data written.

- VSCode Version: 1.15.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.Open VSC and load a project or even just create a new empty file
2.that's it

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
What kind of files are being written? Can you show a screen capture of the sys internal tools?

**Comment by Nelvin** [comment]
Unfortunately I don't know what get's written, I only see the I/O Write Bytes column in proc explorer going up. Did a bit of a test and as soon as f.i. I move the mouse over VSCodes window it seems to write about 1-2mb/sec - doesn't matter if the window is the focused one. It also goes up to 1-2mb/sec when slowly scrolling through a file - it's only a few 100kb/sec with just an idle blinking cursor.

Maybe I misinterpret proc explorers IO write column and it not only measures disk writes?

I'm just curious as just a few months ago Spotify had a very bad behaviour and trashed my SSD with TBs of writes while most of the time sitting idle in my taskbar (my PC is on 24/7) and Chrome did some quite heavy trashing too - so even when a single app might not be a serious issue if you have multiple summing up to hundreds of GB a day it may become an issue at some point.
It's not that VSCode is that bad, I just noticed it had more than a GB of writes after coding a bit and wondered why and if there might be a way to reduce it (I'm a longtime game developer and had to work within 64kb limits - so whenever I see something in the range of GBs I'm really curious where/why that much resources are used :)).
I've attached a screenshot of proc explorer after a few hours of coding with a pretty simple project and only a few .lua files opened IO writes were 4GB.
![vscode_writes](https://user-images.githubusercontent.com/3474781/30168538-fcdf7538-93e9-11e7-919e-d0ce6dd18785.png)

**Comment by jrieken** [comment]
> Maybe I misinterpret proc explorers IO write column and it not only measures disk writes?

Must be something like. VS Code uses different processes and only the main process interacts with the mouse and keyboard. However, that process isn't visible and needs to tell the active window (renderer) that the mouse has moved. It does so by sending an IPC message to that process. My guess is that you measure those messages. 

Please try the scenario you have there with Chrome. Make sure have a few tabs from different websites open and move your mouse around. It should use the same IPC messages. 

Checking with https://superuser.com/questions/993966/what-does-i-o-reads-or-writes-and-i-o-read-bytes-or-write-bytes-mean it seems that I/O Read/Write Bytes does include network bytes. Remains the question if network bytes includes bytes send over named pipes (the IPC mechanism we use)

**Comment by Nelvin** [comment]
You're probably right - Chrome does show the same behaviour when moving the mouse and I already piped it's temp dir to nirvana (it created GB of writes over night without any user interaction before - of course might have changed by now).

Thanks a lot for your extremely fast reply, rather seldom these days - really appreciated and best regards from almost Switzerland (Weil am Rhein) :)
