### ISSUE TITLE
Exclude VM scripts via skipFiles

### ISSUE THREAD

**Issue by sabrehagen** [Microsoft/vscode#33735]
Hi,

I'd like to make a feature request to exclude 'VM Scripts' that are dynamically created with `eval()` from the VS Code debugger as suggested by @roblourens [here](https://stackoverflow.com/questions/46013729/vscode-debugger-exclude-node-vm-files?noredirect=1#comment78993320_46013729).

To make progress immediately, if a knowledgeable contributor can identify the code in the source, us open source users can start the grunt work of implementation.

[Some reading](https://stackoverflow.com/questions/17367560/chrome-development-tool-vm-file-from-javascript), [relevant discussion](https://stackoverflow.com/questions/29897750/is-it-possible-to-blackbox-all-vm-scripts-in-chrome-debugger).

Thank you.

**Comment by isidorn** [comment]
@sabrehagen thanks for willing to do a PR.
This feature seems to be coming from the node debug adapter extension. Thus forwarding to @weinand and @roblourens as they would be pest to provide code pointers as to where to start a potential PR

**Comment by weinand** [comment]
The "legacy" debugger places "VMnnn" scripts under the "<node_internals>" node (for which we already have skipFiles support). My suggestion: use the same approach for "inspector" debugger and problem is solved (and both debuggers become consistent).

**Comment by weinand** [comment]
see https://github.com/Microsoft/vscode/issues/33018

**Comment by weinand** [comment]
@roblourens as part of our November issue grooming could you please consolidate the three items into one?

**Comment by roblourens** [comment]
Will track this with https://github.com/Microsoft/vscode/issues/31537
