### ISSUE TITLE
F8 problems view doesn't wrap well

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33737]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.3
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
python|don|0.7.0
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
rust|rus|0.2.2
ayu|tea|0.6.0

(2 theme extensions excluded)

---

<img width="620" alt="screen shot 2017-09-02 at 8 40 49 pm" src="https://user-images.githubusercontent.com/2193314/30000391-2266f8ae-901f-11e7-9fb2-eedce591761a.png">

Looks like it's underneath the minimap:

<img width="665" alt="screen shot 2017-09-02 at 8 42 32 pm" src="https://user-images.githubusercontent.com/2193314/30000394-4704a134-901f-11e7-9761-557899dffdbb.png">

**Comment by jrieken** [comment]
Sorry, but the designed (not desired) behaviour. Often messages are ASCII-art'ish and rely being wrapped. For instance something like this

```
Bad Foo: This is a sample
                               ^^^^^^^
                               Bad 'sample', use a better one
```

So, I don't know a better to handle this. We can zoom out or add a scroll bar

**Comment by Tyriar** [comment]
My first instinct was shift+mouse wheel so I think a scrollbar when needed would be good.
