### ISSUE TITLE
Can no longer open image files from the git viewlet

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#33739]
- Add a .png file to a git repo (or rename an existing one so it shows up in the Git viewlet)
- See the untracked PNG in the git viewlet
- Click on it

See `Git: cannot open file:///Users/roblou/code/vscode/resources/linux/code2.png. Detail: File seems to be binary and cannot be opened as text`

Previously, it would open the image.

**Comment by joaomoreno** [comment]
#3935

**Comment by bpasero** [comment]
This is a regression when the file is untracked and thus new should open like a normal file.

**Comment by roblourens** [comment]
Thanks. I thought it had worked recently.

**Comment by joaomoreno** [comment]
Dupe of #33850
