### ISSUE TITLE
Option to find conflicting (duplicate) keyboard shortcuts

### ISSUE THREAD

**Issue by brezanac** [Microsoft/vscode#33745]
Many VSCode extensions come with their own set of keyboard shortcuts which usually do not conflict with those shipped as default with VSCode.

However, with multiple extensions installed it often happens that two or more of them register the same keyboard shortcut and since there is currently no system in place to prevent that (at least not to my knowledge) the only way to find out that there is a conflict is by actually using a shortcut and realizing it doesn't do what it's supposed to do.

I think that this feature is essential for a tool that relies so heavily on using shortcuts.

**EDIT**: Just to be clear, I am aware of the _"Show conflicts"_ option in the right-click context menu but it basically just does a search for a specific keyboard shortcut (the one that has been right-clicked on).

What I am talking about is a feature that would, for example, color all duplicate entries in _Keyboard shortcuts_ dialog red or at least warn if an extension is trying to register a shortcut that has already been declared.

**Comment by sandy081** [comment]
@ezra100 your scenario is different from what is reported here. Your scenario is when user is adding while the one here is when the extension is registering.

There is some work in progress (https://github.com/Microsoft/vscode/pull/40405) for your scenario

**Comment by brezanac** [comment]
@sandy081 I was actually targeting any case where an already existing binding is registered multiple times, regardless of how the new binding is added.

**Comment by DRSDavidSoft** [comment]
I wonder if this is going to be implemented -- this seems to be an _essential_ feature when having multiple extensions installed.

**Comment by sandy081** [comment]
We provide following ways to find a similar keybinding

- As mentioned in the description, there is a context menu action on keybinding entry to find similar keybindings
- While you are assigning a keybinding, a link with similar keybindings is shown and clicking on them will shown similar keybindings.

Hope this is already helpful for what is asked here. I would close this unless you need more.

**Comment by brezanac** [comment]
@sandy081 Is there currently a mechanism that also prevents newly installed extensions from registering already registered keybinds?

**Comment by DRSDavidSoft** [comment]
@sandy081 That is indeed helpful, but might I suggest adding two more functionalities:
- sorting keybindings table by bindings
- displaying all conflicting bindings that are _already_ set from different extensions and/or previous user configuration

**Comment by sandy081** [comment]
> Is there currently a mechanism that also prevents newly installed extensions from registering already registered keybindings?

No

> sorting keybindings table by bindings

There is an action in the Search input that sorts by precedence.

> displaying all conflicting bindings that are already set from different extensions and/or previous user configuration

What is the purpose of it?

**Comment by DRSDavidSoft** [comment]
@sandy081 I might be mistaken but I believe multiple extensions can register the same keybinding for different actions

**Comment by sandy081** [comment]
@DRSDavidSoft Yes thats possible. So you want to have an action that displays all commands with similar keybindings? If so, would like to know how the results will be used?

**Comment by DRSDavidSoft** [comment]
@sandy081 Yes, and it should be displayed right in the keybindings table. Maybe when searching for `@duplicates`tag?

Additionally, IMO the user should get a warning in the keybindings table if duplicates _are_ indeed registered in VS Code.

**Comment by DRSDavidSoft** [comment]
@sandy081 Here's a mockup I made:

### Show a message

"Warning: `##` duplicated keybindings found. [Show duplicates...](#)"

![vs-code-dupes1](https://user-images.githubusercontent.com/4673812/55020693-fb77a100-5014-11e9-8aed-da9a56e7b6f0.png)

### Search

Using `@duplicated` tag:

_NOTE:_ Clicking on "Show duplicated..." will type the `@duplicated` tags in the search box

![vs-code-dupes2](https://user-images.githubusercontent.com/4673812/55021459-64134d80-5016-11e9-8eb4-716b164136f1.png)

**Comment by sandy081** [comment]
You can have a query for that but don't like showing it by default as I am sure this will be true always. If interested, please feel free to submit a PR implementing the query.

**Comment by DRSDavidSoft** [comment]
@sandy081 I'll be happy to, if my typescript is qualified. What files do I need to edit?

**Comment by sandy081** [comment]
You can follow how `Show User Keybindings` command is implemented 

https://github.com/Microsoft/vscode/blob/76e18d0915b18b1aa5971272293fb923b5c2040e/src/vs/workbench/contrib/preferences/electron-browser/preferences.contribution.ts#L568

**Comment by KaungZawHtet** [comment]
that @duplicate tag is what i need now. How can i get in mine ? I can't do it in my vs code (version 1.33)
