### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by PacmanLazy** [Microsoft/vscode#33744]
I have to use PyCharm instead of your wonderful editor cause of bad support of python 3.6 in an intellisense.

**Comment by mrmlnc** [comment]
Cool. I'm happy for PyCharm. But this issue not related to editor. By default VS Code does not provide intellisense for Python – you must use [extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python)

**Comment by chrmarti** [comment]
Various issues are tracking this for the extension: https://github.com/DonJayamanne/pythonVSCode/search?q=3.6&type=Issues&utf8=%E2%9C%93
