### ISSUE TITLE
Improving retention of colors when copying text

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33747]
As I understand it, when copying some text VSC also copies its style along with it, in order to provide a better experience when pasting that text in a rich editor like Gmail's.

I believe this feature should be improved. Currently not all colors are copied along when highlighting some text using a .tmLanguage file, and none are copied when highlighting it dynamically using the API.

## tmLanguage

This is what a sample file highlighted using @sandy081's [todotasks](https://marketplace.visualstudio.com/items?itemName=sandy081.todotasks) extension looks like, respectively inside VSC and inside Gmail's editor after pasting:

<img width="358" alt="screen shot 2017-09-03 at 15 35 32" src="https://user-images.githubusercontent.com/1812093/30003694-c882cf72-90c1-11e7-8ff0-ffedbb47e65d.png">

<img width="448" alt="screen shot 2017-09-03 at 15 35 42" src="https://user-images.githubusercontent.com/1812093/30003696-cf1b9396-90c1-11e7-8e50-bdc2a123f975.png">

## Dynamically

And this is what the same file looks when using my [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) extension:

<img width="359" alt="screen shot 2017-09-03 at 15 36 13" src="https://user-images.githubusercontent.com/1812093/30003738-72bafac8-90c2-11e7-825d-a280992b9dc0.png">

<img width="449" alt="screen shot 2017-09-03 at 15 36 44" src="https://user-images.githubusercontent.com/1812093/30003739-75c8fd6e-90c2-11e7-83a2-43047feb22d2.png">

**Comment by rebornix** [comment]
Thanks! Technically, it requires putting the decorations to clipboard.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
