### ISSUE TITLE
Can't open project while using command to launch VSCode on Ubuntu

### ISSUE THREAD

**Issue by MSDimos** [Microsoft/vscode#33748]
My developing environment is Ubuntu, and my VSCode version is 1.15.1.
I use command `code /home/XXX/workspace/myProject` to load my own project. But it's doesn't work. Even I try to load my project in VSCode, it doesn't work either.

**Comment by MSDimos** [comment]
I don't know why. I rename my project folder, and it works. If I rename it to original name. It doesn't work again. Oh, my project folder name is 'vue'. I rename it to 'vuedev'. And then I entered 'code ./vuedev' at the terminal. It works. I renamed it back and entered 'code ./vue', it doesn't work. I don't know why

**Comment by isidorn** [comment]
For questions please go to StackOverflow I am sure you will get an answer in a short period of time.
fyi @Tyriar you might have the answer immediatly

**Comment by Tyriar** [comment]
@MSDimos did you have any VS Code windows open at the time? If so, can you try close them all and try again?
