### ISSUE TITLE
Intellisense selecting option despite semi-colon finishing statement

### ISSUE THREAD

**Issue by chinnick967** [Microsoft/vscode#33741]
- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. type "margin: auto;"
2. hit "enter"
3. intellisense picks the selection instead of dropping down a line despite finishing the statement with a semi-colon

Reproduces without extensions: Yes

Gif of issue: 

https://gyazo.com/f8d95639d5c703cbb2af4485ae22a088

**Comment by rcjsuen** [comment]
I too think there needs to be a way to skip all the tab stops and take what's suggested and move on. At the moment, you can't <kbd>Shift+Tab</kbd> to go to the end, you have to <kbd>Tab</kbd> through all the tab stops to get to the end.

**Comment by jrieken** [comment]
Not sure what you mean? Are you saying the semi-colon should select and insert the suggestion `auto`?
