### ISSUE TITLE
Thread dead when I modify the style

### ISSUE THREAD

**Issue by MarvelTiter** [Microsoft/vscode#33740]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-sql-beautify|sen|0.0.4

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@MarvelTiter What do you mean by "thread dead"? Does VS Code hard crash? What do you mean by "modify the style"? How can this problem be reproduced? Do you have any steps to reproducing this problem?

**Comment by MarvelTiter** [comment]
I will try my best to describe the problem like this:
       I am writing a html page
       And I want to change the Css. I can’t add any char. When I input a “.” Vs Code program crash, but only the work area menu can be clicked. That’s mean I can’t add anything in the style tag
       But it work well yesterday. Emmmmm
       That‘ all. I had restart my pc and reinstall Vs Code


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Remy Suen<mailto:notifications@github.com>
发送时间: 2017年9月3日 16:54
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: Marvel_T<mailto:outlinmt@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Microsoft/vscode] Thread dead when I modify the style (#33740)


@MarvelTiter<https://github.com/marveltiter> What do you mean by "thread dead"? Does VS Code hard crash? What do you mean by "modify the style"? How can this problem be reproduced? Do you have any steps to reproducing this problem?

―

**Comment by jrieken** [comment]
Please provide a code sample and/or a screen shot. Also the output of the dev tools console is important, F1 > Toggle Developer Tools > Console. Thanks
