### ISSUE TITLE
Multiple cursors aren't working when closing a curly brace

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#33753]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.3
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
python|don|0.7.0
tslint|eg2|0.17.0
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
rust|rus|0.2.2
ayu|tea|0.6.0

(2 theme extensions excluded)

---

Not sure if it's related to auto-indent, the ts ext or general multi-cursor.

<img width="219" alt="screen shot 2017-09-03 at 10 03 20 am" src="https://user-images.githubusercontent.com/2193314/30005065-28bb05f4-908f-11e7-838c-e26b0501ddbe.png">

<img width="214" alt="screen shot 2017-09-03 at 10 03 27 am" src="https://user-images.githubusercontent.com/2193314/30005066-2ae8f19c-908f-11e7-8d01-c87ba0313c68.png">

The TypeScript code:

```ts
export class A {
  public foo(): void {
    
  public bar(): void {
    
}
```

**Comment by rebornix** [comment]
@Tyriar good catch!
