### ISSUE TITLE
I want to use html snippets in double quotation of attribute

### ISSUE THREAD

**Issue by tamatebako** [Microsoft/vscode#33751]
- VSCode Version: 1.15.1
- OS Version: win10 x64

I can hardly speak English, I'm sorry.
I will ask a question using google translation.

I want to use html snippets in double quotation of attribute.
I wrote in html.json as follows.

~~~~
{
  "test": {
    "prefix": "t",
    "body": [
      "test"
    ],
    "description": "test"
  }
}
~~~~

For example
~~~~
<div class=""></div>
~~~~

I will input it like this.
~~~~
<div class="t"></div>
~~~~

Then, I want to display suggest.
~~~~
<div class="test"></div>
~~~~
![](https://i.gyazo.com/4e3ebf96fea34a7326e6ffa4f42cf969.gif)
![](https://i.gyazo.com/7a9349a677ceda34ff45143232602239.gif)

In another example, I wrote in html.json as follows.
~~~~
{
  "btn-primary": {
    "prefix": "bp",
    "body": [
      "btn-primary"
    ],
    "description": "btn-primary"
  }
}
~~~~

When it is like the following.
~~~~
<a class="btn"></a>
~~~~

I will input it like this.
~~~~
<a class="btn bp"></a>
~~~~

Then, I want to display suggest.
~~~~
<a class="btn btn-primary"></a>
~~~~

![](https://i.gyazo.com/6aba43df4b75cfef1632ad446e94be25.gif)
![](https://i.gyazo.com/ac8cc51b0c2912871ddc0d133ff2b5c0.gif)

Is there any better way to do this?
Thank you.

**Comment by jrieken** [comment]
Yes, there are two setting to controls. For once, enable tab completion via `"editor.tabCompletion": true` or enable 24x7 IntelliSense for strings, like so
```json
"editor.quickSuggestions": {
        "comments": false,
        "other": true,
        "strings": true
    }
```

**Comment by tamatebako** [comment]
Thank you very much for your help.
