### ISSUE TITLE
Emmet 2.0 doesn't work nice with empty custom components

### ISSUE THREAD

**Issue by muhajirframe** [Microsoft/vscode#33750]
I work with vuejs, and I use components alot. Everything was fine with previous version.

- VSCode Version: 1.15.1
- OS Version: Linux

Steps to Reproduce:

1. Write `link-list`, and press tab. 
2. Nothing happens

In previous version

1. write `link-list`, and press tab.
2. Got <link-list></link-list>

This is a huge boost for me to just write `something` and get `<something></something>`. But since emmet 2.0, I can no longer do this. Except for built in html element

**Comment by ramya-rao-a** [comment]
@muhajirframe Please try the latest Insiders from https://code.visualstudio.com/insiders

Custom components with `:` and `-` will expand just like you described above.

Custom components without `:` or `-` will not trigger emmet in suggestions.
But you can force it by setting `emmet.triggerExpansionOnTab` to `true` and then using tab
