### ISSUE TITLE
Middle click on Windows taskbar entry does not open a new window

### ISSUE THREAD

**Issue by c3er** [Microsoft/vscode#33759]
If I perform a middle click (pressing down the mouse scroll wheel), the last opened VS Code window gets focus. I expect instead that a new window is opened - same behavior as right click on taskbar entry --> "New Window". This is standard behavior of windows applications and allmost all applications behave this way.

---

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.8.2
python|don|0.7.0
xml|Dot|1.9.2
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
java|red|0.9.0
vscode-icons|rob|7.12.0

**Comment by rcjsuen** [comment]
See #13905.

**Comment by c3er** [comment]
Thanks
