### ISSUE TITLE
Clicking on a file in Explorer view selects wrong file when revealIfOpen: true

### ISSUE THREAD

**Issue by c3er** [Microsoft/vscode#33758]
If I click on a file to to open it in an editor, the selection jumps to another file. Then both files are opened and the wrongly selected file has the focus. This does not happen always but often. I reproduced it without extensions by renaming the ".vscode" user directory. Without extensions still happens but it seems not to happen as often as with all extensions activated.

Steps to Reproduce:

1. A not too small project is needed - it has to be possible to scroll the files in the Explorer view.
2. I could only reproduce it if two editors are opened side by side and enough files are opened already that the file tabs at each side do not fit in the row.
3. (Double) click different files in the Explorer view. Sometimes you can see that the selection jumps unexptectedly and the wrong file (that got the selection unexpectedly) is opened - thats the bug.

---

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
pascal|ale|0.8.2
python|don|0.7.0
xml|Dot|1.9.2
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
java|red|0.9.0
vscode-icons|rob|7.12.0

**Comment by bpasero** [comment]
@c3er would be good if you could try to attach a screen recording when this happens.

**Comment by c3er** [comment]
It happens multiple times in this record.

![screencast 33758](https://user-images.githubusercontent.com/24460532/30038045-300d3876-91c1-11e7-8e48-2ce37e946752.gif)

**Comment by bpasero** [comment]
@c3er can you share your VS Code settings?

**Comment by c3er** [comment]
Here are my user settings. The project where I work currently has no workspace settings besides of a "launch.json" and a directory named ".ropeproject" with content.

```json
{
    "csharp.suppressDotnetInstallWarning": true,
    "editor.fontSize": 12.5,
    "editor.minimap.enabled": false,
    "editor.renderIndentGuides": false,
    "editor.rulers": [80],
    "files.associations": {
        "*.mm": "xml",
        "*.zeit": "xml",
        "*.ipynb": "json"
    },
    "html.format.wrapLineLength": 0,
    "python.linting.enabled": false,
    "telemetry.enableTelemetry": false,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontSize": 12.5,
    "terminal.integrated.lineHeight": 1.0,
    "workbench.editor.revealIfOpen": true,
    "window.zoomLevel": 0,
    "editor.wordWrap": "off",
    "workbench.colorTheme": "Default Light+",
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "extensions.ignoreRecommendations": true
}
```

**Comment by bpasero** [comment]
Yes, looks like the `"workbench.editor.revealIfOpen"` setting is causing this.

**Comment by bpasero** [comment]
@c3er so if you disable the setting, this behaviour will not show. I think while not very nice, it behaves correctly: you select a file that is already opened in another editor group and we just reveal that file, but we do not activate it. The explorer will always focus and select the file that is active in the editor, and as such jumps back to indicate that.

**Comment by c3er** [comment]
@bpasero My trouble with the described behavior is that I like to select the files with double click on the explorer view. The file should be selected and the keyboard focus should be in the editor that displays the file. The problem is that the Explorer view tends to scroll (back) while the selection jumps and when I perform a double click, any file but not the intended one is selected (and does not have a keybord focus since I performed only a single click on the wrong file).

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
