### ISSUE TITLE
Unable to install extension via CLI

### ISSUE THREAD

**Issue by atipugin** [Microsoft/vscode#33754]
Unable to install any extension using cli anymore. It stucks with following output:

```shell
$ code --install-extension Tyriar.sort-lines
Found 'Tyriar.sort-lines' in the marketplace.
Installing...
(node:659) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:659) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- VSCode Version: 1.15.1
- OS Version: macOS 10.12.6
- Node.js Version: 8.4.0

Steps to Reproduce:

1. Uninstall plugin
2. Try to install it via `code --install-extension`. (i.e. `code --install-extension Tyriar.sort-lines`)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#32381
