### ISSUE TITLE
emmet doesnt work - tab inserts tab

### ISSUE THREAD

**Issue by flurbius** [Microsoft/vscode#33764]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.9.44-1-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
android-dev-ext|ade|0.4.1
Gradle|caz|1.1.2
gitlens|eam|4.4.3
java|red|0.9.0

---

Steps to Reproduce:

1. enter the code "ul>li.item$*7" without the quotes
2. hit TAB
3. expected some html - but got 4 spaces

Reproduces without extensions: Yes/No
Yes 
Happened first time in the interactive playground I was reading the tips and tricks.  I tried again , choosing the command from the menu instead of using TAB and it worked, I tried again with the TAB key and it didnt.  I opened a new file and tried it there, it didnt work.  I tried again with the menu and it didnt work.  Have not been able to get it to work again - it worked once from the menu.

**Comment by LukeMcGurdy** [comment]
It's working as intended. Tab no longer expands Emmet abbreviations. 

In your above example, you should see a dynamically generated preview of the HTML as you type. Whereas before you pressed Tab, now you press Enter. It's the same for CSS (though you may have to select from a list of suggestions TBH, I personally don't like the change (it seems like it slows things down and I can't figure out how to create shorthand like p10-20) but I've only spent a few minutes investigating the updates and maybe over time it will make sense.

The below link explains more (including how to revert to using Tab).

https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0

**Comment by ramya-rao-a** [comment]
@flurbius, what @LukeMcGurdy is saying is right. Also, we missed updating the interactive playground last time. It is updated in the current Insiders and in the coming update later this week/early next week.

@LukeMcGurdy, `p10` should give `padding: 10px` in the suggestion list by default. Which shorthand are you trying to use?

**Comment by LukeMcGurdy** [comment]
@ramya-rao-a, an example would be `p10-20` + tab which I would expect to expand to `padding: 10px 20px'`.

**Comment by ramya-rao-a** [comment]
@LukeMcGurdy I have logged #33898 for that issue.

It does do the expected expansion if you 
- run the `Emmet: Expand Abbreviation ` cmd directly
- or bind any keyboard shortcut to the cmd and use that
- or set `emmet.triggerExpansionOnTab` to `true` and use tab

Use any of the above 3 workarounds until #33898 gets fixed.
And feel free to report any other abbreviations that does not work as before.

**Comment by LukeMcGurdy** [comment]
Thanks, @ramya-rao-a. I've mentioned more here - https://github.com/Microsoft/vscode/issues/33898.

**Comment by flurbius** [comment]
OK thanks for clearing that up - Im new to vscode(congrats on a useful bit of software) and so Im not expecting it to work any particular way, until I saw the example.  And seeing as I am using up to the minute code, and building straight from Github, its inevitable that sometimes the docs might not be in sync with the code.

**Comment by ramya-rao-a** [comment]
No problem @flurbius, Welcome to VS Code and Happy Coding!
