### ISSUE TITLE
Snippets: final tab stop doesn't get added if there are no placeholders in the snippet

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#33761]
Take the below 2 examples of html snippets. The first one has a placeholder, the second doesn't.
The Snippet parser adds a final tab stop for the first snippet, but not for the second.

```
{
	"Sample": {
		"prefix": "list1",
		"body": [
			"<ul class=${1:hello}></ul>"
		]
	},
	"Sample2": {
		"prefix": "list2",
		"body": [
			"<ul class=${1}></ul>"
		]
	}
}
```

This is due to : https://github.com/Microsoft/vscode/blob/c0018cf640c82ab12ec60c9052da8ea66e748549/src/vs/editor/contrib/snippet/browser/snippetParser.ts#L487

This provides inconsistencies when authoring snippets.
Emmet especially assumes the editor will add the final tab stop and so doesn't do it itself.

cc @jrieken

**Comment by user3323** [comment]
@ramya-rao-a, here is one more little thing:

![image](https://user-images.githubusercontent.com/24613274/30009610-65ca2774-9132-11e7-8666-b883132fba3a.png)

box-shadow snippet:
space should be out of the 1st placeholder `inset`

**Comment by user3323** [comment]
@ramya-rao-a 

box-shadow snippet:

![image](https://user-images.githubusercontent.com/24613274/30010047-98af9d38-9135-11e7-95df-b10559e8a135.png)

I think it should not just "color", but `#${5:000}`
like it's done with color snippet or bgc snippet, etc.

`"bxsh": "box-shadow:${1:inset }${2:hoff} ${3:voff} ${4:blur} #${5:000}|none"`

**Comment by ramya-rao-a** [comment]
@user3323 That's coming from https://github.com/emmetio/snippets. Please submit a issue or better yet, a PR in that repo.

**Comment by jrieken** [comment]
this one #33147
