### ISSUE TITLE
Request textDocument/documentHighlight failed.

### ISSUE THREAD

**Issue by iiwf** [Microsoft/vscode#33769]
In the Script tag of the Html document, the following error occurs when I double-click a multiline comment,How can I fix it?
>[Error - 上午10:15:20] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603 

- VSCode Version: 1.15.1
- OS Version: Windows 10 , 14393.1593 

Steps to Reproduce:

1.  In HTML's script tag, write multiline comments
2.  Double click multiple comments

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
duplicate of #30774
