### ISSUE TITLE
Cannot save to a OneDrive directory.

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#33765]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16278
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|0.0.2
vs-code-css-comments|ash|1.0.3
vscode-icontheme-nomo-dark|be5|1.3.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
javadebugger|don|0.1.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.1
javac-linter|fau|1.2.6
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
code-runner|for|0.7.1
csharpextensions|jch|1.3.0
format-indent|Kas|1.3.0
format-php|Kas|1.1.2
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
vscode-docker|Pet|0.0.16
material-icon-theme|PKi|2.2.0
vscode-icons|rob|7.12.0
html-css-class-completion|Zig|1.9.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Use WIndows Insider to update on the slow ring builds which have the new OneDrive place holder feature. 
2. Try to save a new file you just created from within VSCode.
You get the error shown in the screenshot, I've never ever had a problem before until recently, like weeks.

![vscode error](https://user-images.githubusercontent.com/16159685/30006844-10cacac4-90d0-11e7-9573-2e70eb13ad1a.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
#27285
