### ISSUE TITLE
Cross arrow in search panel is different to that used elsewhere

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3376]
Search panel hover
![image](https://cloud.githubusercontent.com/assets/2193314/13268801/576c24e0-da39-11e5-8c13-c638d987516b.png)

Working files hover
![image](https://cloud.githubusercontent.com/assets/2193314/13268817/6b25932c-da39-11e5-8798-6efaaf0ac2bb.png)

Top-right of open file title bar
![image](https://cloud.githubusercontent.com/assets/2193314/13268822/6eb1f42c-da39-11e5-9bab-030313e2dc10.png)

**Comment by joaomoreno** [comment]
Absolutely, I find it ugly as hell.

**Comment by joaomoreno** [comment]
ping @isidorn

**Comment by joaomoreno** [comment]
Awesome

**Comment by isidorn** [comment]
Cool, I will also use this one in debug world
