### ISSUE TITLE
53806 files in working folder, may not be able to open code

### ISSUE THREAD

**Issue by zxdong262** [Microsoft/vscode#33767]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
autotrim|Nat|1.0.6
code-settings-sync|Sha|2.8.3
quokka-vscode|Wal|1.0.56
html-css-class-completion|Zig|1.9.0
project-manager|ale|0.20.0
color-info|bie|0.5.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
vsc-travis-ci-status|fel|1.1.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
useful-react-snippets|igo|1.0.9
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-css-peek|pra|1.3.1
view-in-browser|qin|0.0.5
vscode-icons|rob|7.12.0
language-stylus|sys|1.7.3
html2jade|wma|0.2.0
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.I have a i7 cpu, 16G memeory(Ubuntu 16.04.2), open a folder with 53806 files, it will froze for a while and ask me to reopen or close.
2. after delete some files, reopen it, it will be fine.(some times just reopen it will work too, but not always)
3.after successfully open it, add more files to folder one time, it may froze again.

Reproduces without extensions: No

**Comment by bpasero** [comment]
Does it reproduce with `"files.useExperimentalFileWatcher": true` ?
