### ISSUE TITLE
Provide option to disable drag and drop in File Explorer

### ISSUE THREAD

**Issue by KevDog** [Microsoft/vscode#33768]
- VSCode Version:
- OS Version:

After accidentally dragging and dropping a folder in the explorer and not only not knowing where the folder was originally, but the name of the folder moved, I would like to be able to turn off drag and drop in the file explorer. 

Or, perhaps to phrase this in terms of the problem rather than a proposed solution, I would like there to be some friction when moving files and folder through drag and drop in the Explorer.

An informal survey of my circle of dev friends shows 100% of us have done this at some point in time. 

Thanks for all the work that has gone into this fantastic editor.

Cheers,

Kevin

**Comment by bpasero** [comment]
`"explorer.enableDragAndDrop": false`

**Comment by KevDog** [comment]
Hah! I looked and didn't see it. Thanks!
