### ISSUE TITLE
不同的文件后缀，snippets 不能共用

### ISSUE THREAD

**Issue by ufowiner** [Microsoft/vscode#33771]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
jquery-snippets|Hri|1.0.0
laravel-blade|KTa|0.0.1
laravel-blade|one|1.8.1
laravel5-snippets|one|1.3.4
laravel-helpers|raf|0.2.2
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

write  one.blade.php  want to use  bootstrap-3-snippets or Emmet ，can't working

**Comment by jrieken** [comment]
This is not enough information and does not allow for us to reproduce this.

**Comment by ufowiner** [comment]
### like some.blade.php  , can't use this bootstrap snippets , this ext can  config add  *.blade.php language?
![2017-09-13](https://user-images.githubusercontent.com/10275943/30365437-578b775c-989a-11e7-9003-196382ee18fb.png) @jrieken
