### ISSUE TITLE
Top of debug panel should be responsive

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3377]
When the debug panel gets narrow the title and button disappear, becoming unusable with the mouse.

Regular view:

![image](https://cloud.githubusercontent.com/assets/2193314/13268966/39a06614-da3a-11e5-8b56-b0791ea72dc9.png)

Currently narrow view:

![image](https://cloud.githubusercontent.com/assets/2193314/13268959/2b624f9a-da3a-11e5-9f2a-aeb5ba782a34.png)

It should become something like this when the panel is sufficiently narrow so the button/title doesn't go missing.

![image](https://cloud.githubusercontent.com/assets/2193314/13269042/a3aa8dbe-da3a-11e5-85d4-d61d63271f10.png)

**Comment by isidorn** [comment]
Agree, dup of #1029
Will look into it next milestone probably
