### ISSUE TITLE
Add support for disabling formatter for a code block

### ISSUE THREAD

**Issue by varunkumar** [Microsoft/vscode#33772]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 6.1.7601

This is a feature request. I wanted a way to disable formatter for a block of code based on some sort of annotations. This will be handy for cases that are not yet supported by VSCode formatter. For example, support for dynamic imports were added in [v1.14](https://code.visualstudio.com/updates/v1_14#_languages). Before that `import()` statements were not getting formatted properly.

**Comment by jrieken** [comment]
>  code based on some sort of annotations

Like what? Can provide a sample? Is this for one specific language? And is this just a workaround for shortcomings of the formatter?

**Comment by varunkumar** [comment]
Here is a sample format that could be used. This is not just a workaround for shortcomings. This can be useful for cases where developers want to format a section of code differently.
```JavaScript
const generateData = () => {
  const items = [];
  for (let i = 0; i < 100; i++) {
     /* formatter: off */
    const item = {
      id            : i,
      name      : `item${i}`,
      category : 'some category'
    }
    /* formatter: on */
    items.push(item);
  }
}
```

**Comment by varunkumar** [comment]
JS Beautify has its own set of directives -- https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only

**Comment by jrieken** [comment]
This seems JS/TS specific

**Comment by mjbvz** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/18261 to track for our built-in JavaScript and TypeScript formatter

Closing as upstream
