### ISSUE TITLE
Same file opened twice

### ISSUE THREAD

**Issue by eleson2** [Microsoft/vscode#33779]
- VSCode Version: 1.15.1
(Also using Arduino and C/C++  )
- OS Version: Windows 10 + shared disk on Cubestation cs407.
Steps to Reproduce: ??

Reproduces without extensions: Yes/No Can't tell. 

Sometimes files opens both as they were named, like filename.h, and sometimes they **also** open as FILENAME.H in the tab. Having same file opened twice causes all types of issues. 
Most probably , this shows up sometimes/always when using "find in files" or "replace in files"
( I can't promise I've noticed all times it has happened. )

This on a project stored on a shared disk on the Cubestation.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
