### ISSUE TITLE
Duplicate clean up pattern

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33775]
It looks to me that the patterns defined [here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/common/telemetryService.ts#L56) are overlapping:

* `/file:\/\/\/.*?\/resources\/app\//gi`
* `/file:\/\/\/.*/gi`

The second seems to always match on the same things that the first matches on.

It is also not clear to me what the first pattern is trying to achieve and why it is being so specific about `resources/app`

**Comment by ramya-rao-a** [comment]
The first one strips off everything till "resources/app" and retains the rest which we need to determine the call stack.

The second one gets applied after the first one is applied and strips off the entire `file:///....`

**Comment by bpasero** [comment]
Ah ok got it, thanks!
