### ISSUE TITLE
TaskDetectorMatcher.match is missing a return type

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33778]
Looking at this interface [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L40):

```typescript
interface TaskDetectorMatcher {
	init();
	match(tasks: string[], line: string);
}
```

No return types are declared for these methods. And once you add them you will notice that none of the implementors seem to return something, however there is a check [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L312) that seems to expect a result.

**Comment by dbaeumer** [comment]
Fixed.
