### ISSUE TITLE
Any good idea for makeing a extension's profile?

### ISSUE THREAD

**Issue by amos402** [Microsoft/vscode#33770]
- VSCode Version: 1.15.1
- OS Version: Window10  1703

It's hard to find out a problem with `Developer Tools` inside, it always direct to the vscode sources.

**Comment by jrieken** [comment]
Glad you are asking. With latest insiders (and the upcoming 1.16 release) this is finally possible. I have added a howto here: https://github.com/Microsoft/vscode-docs/blob/a06b64bb959dbe275356d42dbc0e374e58b9a420/release-notes/v1_16.md#profile-your-extension

Let me know if it works for you. Thanks and Happy Profiling!
