### ISSUE TITLE
Feature request : add the possibility of renaming a terminal.

### ISSUE THREAD

**Issue by mbrmj** [Microsoft/vscode#33784]
This is not a bug, but a feature request.
while I am working I tend to have multiple terminals running gulp or docker logs on the same time.
I often lose track of which is which. because If I am using gulp on multiple terminal instance in the select option the only information I have is that those terminal are running gulp.

so having an option to rename a terminal would be really helpful.

**Comment by fabiospampinato** [comment]
There's already such option, just run the `Terminal: Rename` command.

If you've many terminals opened at once I recommend you my [Terminals](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) extension for spawning them automatically with the proper commands and names.

**Comment by mbrmj** [comment]
thank you @fabiospampinato  for your response . this issue  is a duplicate of  #10023

**Comment by mbrmj** [comment]
thank you @fabiospampinato for your response.
This issue is a duplicate of #10023
