### ISSUE TITLE
viewing shortcut issue on alternative tabs

### ISSUE THREAD

**Issue by onurbasak** [Microsoft/vscode#33789]
![screenshot from 2017-09-04 14-39-30](https://user-images.githubusercontent.com/18640632/30025075-80bd874a-917f-11e7-98c0-84bdc2e96324.png)
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.open a alternative tab
2.you can see some shortcut's align is left

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33677
