### ISSUE TITLE
Lag after missclicking on a big file

### ISSUE THREAD

**Issue by sixclones** [Microsoft/vscode#33781]
- VSCode Version : 1.15.1
- OS Version : GNOME Shell 3.24.2

Steps to Reproduce:

1. Make a global research on the project (Ctrl + Maj + F)
2. Missclick on/select a really big file like `index.js.map` with thousands of line (3.2Mo)
3. Try to work on other files but VSC got serious lagging problems. Like typing some code that come in screen with a second of delay.

The only solution I found is to quit and then launch again VSC. But it's a little bit boring because I run webpack with VSC's terminal, so I have to launch it again.
Not a huge issue in fact.

Reproduces without extensions: Yes
I tried to reproduce it without extensions but this bug doesn't always appear when I made the steps, extensions disable or not.

Hope I've could help you to improve VSC :)

**Comment by alexandrudima** [comment]
@sixclones Can you perhaps share with me a file that reproduces the slowness / freeze for you ?
