### ISSUE TITLE
Terminal: ctrl + A in find widget should select all text in find widget not terminal

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33799]
1. Open terminal, open find widget
2. Ctrl / Cmd + A = all text in terminal gets selected
3. I would expect only the text in the find widget gets selected, same as in the find widget in the editor

**Comment by ihalip** [comment]
Should be fixed by [this commit](https://github.com/Microsoft/vscode/commit/48bfb73ae22c4d300db694160dff1b7b357a2da2).

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/33935, thanks @ihalip 😄
