### ISSUE TITLE
Stale inline diff information

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33790]
See screenshot, unsure how I got there. With todays, insiders `aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad`

<img width="1232" alt="screen shot 2017-09-04 at 14 26 11" src="https://user-images.githubusercontent.com/1794099/30026418-1ce842ac-917d-11e7-8a46-906f5c72225e.png">

**Comment by joaomoreno** [comment]
Try to repo :(

**Comment by joaomoreno** [comment]
Very likely #34209

**Comment by jrieken** [comment]
Still seeing this btw. You decide what to do next

<img width="1120" alt="screen shot 2017-10-03 at 16 57 51" src="https://user-images.githubusercontent.com/1794099/31132062-191373ea-a85c-11e7-999b-b54b2bf553eb.png">

**Comment by joaomoreno** [comment]
That is indeed interesting. If you press the Refresh button, nothing really happens huh? There must be something different about your system. :/

**Comment by joaomoreno** [comment]
@jrieken Have you seen this lately?

**Comment by jrieken** [comment]
<img width="871" alt="screen shot 2018-04-24 at 18 50 19" src="https://user-images.githubusercontent.com/1794099/39201813-75a8cf2c-47f0-11e8-9da1-ffd722d1d7c3.png">

**Comment by joaomoreno** [comment]
Sorry to move this to a more recent one: #43092.

This sucks because I never see this issue. Need to spend some time reviewing the code.
