### ISSUE TITLE
Save conflict: left hand diff editor does not update on changes to file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33792]
Steps to Reproduce:

1. have a dirty file
2. change it outside VS Code
3. try to save
4. open the save conflict diff editor
5. continue to make changes outside VS Code

=> left hand side of diff editor does not update from these changes

We should update the left hand side automatically when changes are being done.

**Comment by roblourens** [comment]
I should see the diff editor auto reloading the file when it's changed externally? I do not see it updating with those changes.

**Comment by bpasero** [comment]
@roblourens I am glad we have verification 👍
