### ISSUE TITLE
String formatting isn't applied on `TaskSystem.activeSame.{no}background` message

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode#33797]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
python|don|0.7.0
pgsql|dou|0.0.8
vscode-html-css|ecm|0.1.8
vscode-nuget-package-manager|jmr|1.1.4
vscode-rust|kal|0.4.2
Kotlin|mat|1.3.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
shader|sle|0.2.3
vscode-lldb|vad|0.6.0
vim|vsc|0.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Cmd+Shift+b (to trigger the `build` task)
2. Cmd+Shift+b while the previously-started task is still running

![screen shot 2017-09-04 at 7 50 11 am](https://user-images.githubusercontent.com/4861023/30027387-610a9b24-9146-11e7-9e75-4426e791b1b9.png)

Reproduces without extensions: Yes

---

https://github.com/Microsoft/vscode/blob/bef497ff82391f4f29ea52f532d896a6903f6ff6/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1254-L1256

**Comment by dbaeumer** [comment]
Got already fixed for the next release.

**Comment by Phrohdoh** [comment]
Good to hear. Thanks for addressing this so quickly and sorry for the duplicate issue.
