### ISSUE TITLE
remove support for `debuggers.initialConfigurations` command contribution

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33794]
With the introduction of the `provideDebugConfigurations` method on type `DebugConfigurationProvider`, it is no longer necessary to contribute a command for the `debuggers.initialConfigurations` contribution point. Therefore we are deprecating the ability to specify a command ID in this milestone and plan to drop it in October (but we will continue the support for contributing a JSON object literal).

**Comment by rkeithhill** [comment]
Just to be clear, `debuggers.initialConfigurations` will continue to be supported in package.json right?  If we have this section in package.json, then it appears the `DebugConfigurationProvider.provideDebugConfigurations` method never gets called.  Is that correct?

**Comment by isidorn** [comment]
`debuggers.initialConfigurations` as an json object will continue to be supported in package.json

**Comment by weinand** [comment]
Since `debuggers.initialConfigurations` is still supported, please don't implement `DebugConfigurationProvider.provideDebugConfigurations` (instead of returning an empty array).
All `DebugConfigurationProvider` methods are optional and you do not have to implement any of them.

**Comment by rkeithhill** [comment]
Got it.  Fixed in pending [PR](https://github.com/PowerShell/vscode-powershell/pull/1062).  

BTW in the resolveDebugConfigurations, there is a particular config (attach) that will not work when running in PS Core (vs Windows PowerShell).  When I detect that, can I just return out of this method?  That seems to work.  Or is it better to return undefined?  Here's the [impl](https://github.com/PowerShell/vscode-powershell/pull/1065/files).

**Comment by isidorn** [comment]
Yeah in that case just return undefined for the config and vscode will hande things correctly

**Comment by weinand** [comment]
You can even show an error message in this case (see example from node-debug: https://github.com/Microsoft/vscode-node-debug/blob/fffc26014b7bf06a3ba061ff46adc69cff58158a/src/node/extension/configurationProvider.ts#L41)

**Comment by isidorn** [comment]
fyi @pieandcakes

**Comment by pieandcakes** [comment]
@isidorn This will be part of Stable 1.18 ? or does it already exist in 1.17?

@wardengnaw

**Comment by isidorn** [comment]
@pieandcakes we will remove the support for this in 1.18. DebugConfigurationProviders already exist in 1.17.

You can try it all out in insiders
