### ISSUE TITLE
Horrible indentation bug

### ISSUE THREAD

**Issue by saharso** [Microsoft/vscode#33798]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

When i am trying to duplicate an html block, I used to just select the rows, press ctrl+c and then ctrl+v and the block is successfully duplicated

But after the recent update things go horribly wrong when all the indentation gets screwed up as you can see in the attached image: the duplication is indented in relations to it's sibling, not to it's parents, which is totally incorrect in any known language or markup.

Indentation is to the sibling element instead of the parent element not just in duplictions but also in normal writing of code.

Please fix this bug as soon as possible.

By the way, editing css recently also becames challanging as auto complete suggests css properties no one ever really uses, this also started from one of the recent updates.
Steps to Reproduce:

![bug](https://user-images.githubusercontent.com/19216444/30027605-52ff5f1c-918a-11e7-92b3-bbe1e6f6cf39.jpg)

1.
2.

**Comment by jsepia** [comment]
I was able to get around this by adding 

    "editor.autoIndent": false

to my settings.

**Comment by saharso** [comment]
Thanks @jsepia , this improves things significantly. However, indentation is still not as smooth as it used to be. I keep noticing indentation "Jumps", when new elements or closing tags indent themselves to wrong locations, which forces me to manually indent them correctly.

**Comment by saharso** [comment]
To elaborate, please look at the attached image.

Notice that I opened <div class="grid"> tag, hit "enter" twice and then closed the tag. 

The closing tag pushed itself to the left without my intervention, and did not stayed align to the opening tag. I now must manually indent it correctly.

This was not the case before the update.

![bug](https://user-images.githubusercontent.com/19216444/30156737-1f5cd13a-93c9-11e7-9bde-ec209efa0bc5.jpg)

**Comment by rebornix** [comment]
Thanks all for your feedback, let's track this issue in https://github.com/Microsoft/vscode/issues/32320 , which talks about similar bug (indentation adjustment when pasting, moving, entering) in HTML/PHP like language. All your input will be considered when we tackle this issue. 

For you now if the indentation adjustment makes pasting worser, you can turn this off by setting `editor.autoIndent` to `false`. Thanks again for your help!
