### ISSUE TITLE
Code Collapse/Expand issue using +. Elements must end on same col

### ISSUE THREAD

**Issue by JoeEarly** [Microsoft/vscode#33793]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:40:17.463Z) (Also present in 1.15.1)
- OS Version: Windows_NT x64 10.0.15063

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.1
vscode-great-icons|emm|2.1.15
beautify|Hoo|1.1.1
team|ms-|1.122.0
---
Steps to Reproduce:

1. Open a file (using HTML/CSS/JS locally)
2. Ensure code block is in expanded state and opening and closing div tags are in different col number. See red x below at the opening tag and another at closing tag. 
![image](https://user-images.githubusercontent.com/5208459/30026708-0268621a-9176-11e7-9f87-3332f9dd93a7.png)
3. When clicking on the "+" to collapse, the code block is collapsed, but the the div ends up inside the collapsed code block. 
![image](https://user-images.githubusercontent.com/5208459/30026988-0291230c-9177-11e7-88ec-5959e63b93ad.png)

4. Now, ensure the closing div is on the same col as below: 
![image](https://user-images.githubusercontent.com/5208459/30026806-74030844-9176-11e7-8bf5-e5e2d1255ebf.png)
5. click on the "+" to collapse, the code block is collapsed, the div is now outside the collapsed code block as below:
![image](https://user-images.githubusercontent.com/5208459/30026851-96fb9d52-9176-11e7-9e72-a0454d43de27.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
What you observe is as expected. Folding is based on indentation only. 
The request for language aware folding is #3422
