### ISSUE TITLE
IntelliSense won't work for C#

### ISSUE THREAD

**Issue by Ah-Meow** [Microsoft/vscode#338]
Even if "editor.quickSuggestions" and "editor.suggestOnTriggerCharacters" are set to true.
Meanwhile, IntelliSense works for JavaScript etc.

**Comment by Someguy123** [comment]
You need to create:

1. a `yourproject.csproj` file for MSBuild or XBuild (OSX)
example:

         <Project DefaultTargets = "Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

        
        <ItemGroup>
            <CSFile Include = "main.cs"/>
        </ItemGroup>
        <Target Name = "Build">
        
        <CSC  Sources = "@(CSFile)"
            DebugType="full"
            Optimize="no"
            OutputAssembly="main.exe" >

            
            <Output TaskParameter="OutputAssembly"
                ItemName = "EXEFile" />
        </CSC>
        </Target>
        </Project>

2. A `project.json` containing dependencies and other info. Example:

        {
            "dependencies": {    
            },
            "commands": {
                "ConsoleApp": "ConsoleApp"
            },
            "frameworks": {
                "dnx451": { },
                "dnxcore50": {
                    "dependencies": {
                        "System.Console": "4.0.0-beta-*"
                    }
                }
            }
        }

Once you've created those, restart VS Code and load your project. You should see OmniSharp ( a little flame in the bottom right corner) start. Your intelli-sense should now be working just like in JS or PHP.

Not sure why you have to jump through so many hoops to make this work, but sadly this is how it is.

**Comment by jrieken** [comment]
@Someguy123 Thanks for helping out. @Ah-Meow let me know if that didn't work for you

**Comment by Ah-Meow** [comment]
@Someguy123 Thanks that works.

**Comment by PeteX** [comment]
In case other people are having trouble and find this report: I had problems because I only had the coreclr runtime installed.  Although most things work with coreclr now, Omnisharp seems to search for Mono specifically.  If it's not there, it tries to run it anyway.  This doesn't work but fails silently, meaning that Code starts but with c# completion unavailable.
