### ISSUE TITLE
Replace 'adapterExecutableCommand' with real debug API

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#33801]
Documentation from extensionAPI:

`adapterExecutableCommand` the command ID where the debug adapters executable path and arguments are dynamically calculated. The command returns a structure with this format:
  ```json
  command: "<executable>",
  args: [ "<argument1>", "<argument2>", ... ]
  ```
  The attribute `command` must be a either an absolute path to an executable or a name of executable looked up via the PATH environment variable. The special value `node` will be mapped to VS Code's built-in node runtime without being looked up on the PATH.

**Comment by isidorn** [comment]
I also came across this in our code just now.
We should try to remove it
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L82

Assigning it to November so we consider doing this then.

**Comment by weinand** [comment]
I've added a new optional method `debugAdapterExecutable` to the `debugConfigurationProvider`.
@isidorn please review my change on the https://github.com/Microsoft/vscode/tree/aweinand/debugAdapterExecutable branch.

**Comment by isidorn** [comment]
@weinand great work. I added some comments in the PR directly.
