### ISSUE TITLE
Receive didChangeTextDocument events with zero contentChanges

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33809]
I noticed during debugging today that I receive a lot of didChangeTextDocument event with `contentChanges` being an array of length === 0.

Is this intentionally?

**Comment by jrieken** [comment]
> Is this intentionally?

Yes, from the docs:

> An event that is emitted when a [text document](#TextDocument) is changed. This usually happens
> when the [contents](#TextDocument.getText) changes but also when other things like the
> [dirty](TextDocument#isDirty)-state changes.
