### ISSUE TITLE
Terminal: find widget gives flaky results

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33800]
1. Terminal, open find widget, find something -> works fine
2. Try to find some other term -> sometimes fails
3. If there are multiple instances of a result, sometimes moving between them fails

I can repro this flaky behavior both on my OS X with zsh shell and Win10 with powershell.
If nobody reported this so far please let me know and I will try to find better repro steps.

**Comment by Tyriar** [comment]
This is the first report, more details steps please :smiley:

**Comment by isidorn** [comment]
Ok here are steps which always repro on my os x zsh shell
1. vscode repo, terminal, do a `ls`
2. cmd + f, search for something, get results, search for something else no results

I can also repro on my win10 powershell but not so consistently

![terminal](https://user-images.githubusercontent.com/1926584/30102605-79f9b4f2-92f0-11e7-9a2e-d3aea85f7682.gif)

**Comment by cleidigh** [comment]
@isidorn 
@Tyriar 
I can also see this frequently on Windows 7/CMD.EXE
Usually the second search term fails, however this is not one hundred percent consistent.
Once the problem occurs, it appears to be "permanent" until you kill the terminal instance and start a new one.

I think I may have seen this while working on simpleFind but was possibly fooled by Dragon issues.

@isidorn  - what screen capture to use that is good for github ? and works on Windows.

**Comment by isidorn** [comment]
@cleidigh the creen capture I use is liceCap and I use it on my mac. Not sure if there is one for Windows though

**Comment by Tyriar** [comment]
@isidorn I'm not sure I understand, are you saying that the search for "blogs" should clear the selection?

Also the terminal find does not search the line that the selection is on, this is a known limitation and captured in another issue.

**Comment by cleidigh** [comment]
@Tyriar 
cc @isidorn 
I just redid my tests taking into account the above.  I noted the current selection with subsequent finds
and what I see matches your description of the other issue/limitation @Tyriar .
If I do a search making sure to look for something on another line things appear to be okay.  my guess is this is the same issue not a different one.

**Comment by cleidigh** [comment]
@isidorn 
LiceCap is available for Windows and seems to work well Thanks!

**Comment by isidorn** [comment]
@Tyriar yes I am saying that the search for "blogs" should clear the selection and then select "blogs". 
After trying a bit more I seem to be always hitting the issue you mentioned - I do not get the search results on the current line. This seems like a big limitation and makes the find widget very unrealiable in terminal imho

**Comment by Tyriar** [comment]
@isidorn there are many issues with the implementation, this was something @rebornix and I threw together over 1-2 days that wasn't planned for that iteration. Many of the improvements are listed here https://github.com/Microsoft/vscode/issues/28768

**Comment by isidorn** [comment]
Reopening as I have provided enough details and that is not the issue ehre.
It might be a duplicate but leaving that up to @Tyriar to decide

**Comment by Tyriar** [comment]
Let's close this off in favor of https://github.com/Microsoft/vscode/issues/28768, I think it captures everything 😃
