### ISSUE TITLE
doesn't linking file

### ISSUE THREAD

**Issue by dhfl372** [Microsoft/vscode#33808]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.my file doesn't open when target file double click or select vs code in menu(it open if right mouse click)

**Comment by joaomoreno** [comment]
#33216
