### ISSUE TITLE
Make the quick open prefixes configurable

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3380]
on testing #2791:

I tried hard to use the dash ('–') for Working file QP but then realised that the trigger character is in fact a tilde ('~'). We should either use a font that has a better tilde character, or use a better character (who knows how to enter a tilde on a German keyboard?).

![2016-02-23 23-46-40](https://cloud.githubusercontent.com/assets/1898161/13269519/692fbd32-da88-11e5-9d92-7e3c0d8a1ee1.png)

Since we are running out of usable characters, IMO we will have to find a better mechanism for QP.

**Comment by bpasero** [comment]
I would think that people assign a keybinding for working files picker and not always type the character.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
