### ISSUE TITLE
Stop supporting onDebug:type activation event

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33803]
Stop support for [`onDebug:type`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L844)

Currently the C++ extension seems to be the only extension getting activated by `onDebug:type` event. Since we added this event we have introduced alternative ways for extensions to be activated so there is possibly a better way to achieve what the C++ extension needs here.

@pieandcakes could you please clarify how you use`onDebug:type` in your extension. So we could potentially adivse to use a different solution

fyi @weinand 

related #33258

**Comment by isidorn** [comment]
@pieandcakes ping regarding this issue

**Comment by roblourens** [comment]
@ramya-rao-a and I noticed that the current state is actually not that great for the Go extension. It contributes a debugger _and_ a language server, so activating is a heavy operation that ideally would only happen when Go files are detected. But now it happens when a debug session of any type is started.

Most debug extensions probably just contribute debuggers, so vscode-go may be an oddball. Any thoughts on how to mitigate that?

**Comment by testforstephen** [comment]
@isidorn @weinand @aeschli
Got similar perf issue for java debugger. When user is debugging non-java project, also activate java language server and debugger extension. 
See the issue https://github.com/Microsoft/vscode-java-debug/issues/142

**Comment by weinand** [comment]
@aeschli fyi

**Comment by isidorn** [comment]
I understand the issue. Thanks for letting us know @roblourens @testforstephen 
I do not see this as a critical issue, so I suggest to try to fix this in November. Options:
* introduce new activation event "onDebugSession:type" which would fire everytime a session of that type is about to start. Basically would behave like the old event

Suggestions are also welcome. Once we come to the conclusion I can open a new issue for November to track this.

**Comment by weinand** [comment]
I've created https://github.com/Microsoft/vscode/issues/37918 to track this.

**Comment by weinand** [comment]
@isidorn activating on a specific type only would miss the case of collecting all registered DebugConfigurationProviders for the "initialLaunchConfigs" functionality.
