### ISSUE TITLE
ALT-E doesn't open Edit Menu

### ISSUE THREAD

**Issue by aec4444** [Microsoft/vscode#33806]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jslint|ajh|1.2.1
jshintrc-generator|ben|1.0.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
Angular1|joh|0.2.0
mssql|ms-|1.1.0
PowerShell|ms-|1.4.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.2.1
debugger-for-ios-web|msj|0.1.2
html-css-class-completion|Zig|1.9.0

---

Steps to Reproduce:

1.  Go to the code editor, and hit ALT-E
2.  See that while you are holding ALT the E is underlined, but hitting E doesn't do anything
3.  "window.enableMenuBarMnemonics": true,  is set

Reproduces without extensions: YES

**Comment by aec4444** [comment]
in previous builds, like most windows apps, I could hold ALT-E and get the edit menu to show.  All menus are not showing while holding the ALT key and hitting the hotKey.

**Comment by isidorn** [comment]
Works for me.
Please try reproducing by installing the latest vscode inisder version https://code.visualstudio.com/insiders

Also check your keyboard shortcuts and try disalbling all extensions since some extension might overwrite that keybdinging.
