### ISSUE TITLE
JS node deprecation error blocking extensions installation from command line

### ISSUE THREAD

**Issue by cjfq** [Microsoft/vscode#33812]
- VSCode Version: 1.15.1 x64
- OS Version: Windows 10

Steps to Reproduce:

1.  When executing the "code --install-extension <any extension>" command, does not allow to install any extension.
      
2. C:\Program Files\Microsoft VS Code\bin\code.cmd --install-extension ms-vsts.team
Found 'ms-vsts.team' in the marketplace.
Installing...
(node:13048) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:13048) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Reproduces without extensions: Yes/No

**Comment by decoomanj** [comment]
Same for lukehoban.Go and other plugins. When using vs-code in a Docker-container, it also hangs.

**Comment by joaomoreno** [comment]
#32381
