### ISSUE TITLE
Folders and files not available in Explorer

### ISSUE THREAD

**Issue by prezzz** [Microsoft/vscode#33816]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Try to load any folder into editor, either by dragging it to the window or by using Open Folder option

2. No folders and no files are displayed in the sidebar. No Open Editors panel is open even after a file is opened.

3. It only happens for folders that had been worked before. After RENAMING a given folder, I can load it successfully into editor.

**Comment by mortenmoulder** [comment]
I can confirm this is happening to me as well. It's really annoying.

**Comment by abepark01** [comment]
I am experiencing this issue as well

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11



---

Steps to Reproduce:

1. code --disable-extensions [project folder]
2. explorer window is empty.


Reproduces without extensions: Yes

**Comment by sandy081** [comment]
This was fixed in #32962
