### ISSUE TITLE
Cannot Git push - no ssh-askpass

### ISSUE THREAD

**Issue by jublo** [Microsoft/vscode#33814]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
format-indent|Kas|1.3.0
Bookmarks|ale|0.16.0
vscode-color|ans|0.4.5
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
smarty|imp|0.2.0
vscode-icon-theme|jtl|1.5.0
vscode-less|mrm|0.6.3
csharp|ms-|1.12.1
new-cmd|odo|0.2.0
CSSLint|ray|0.0.3

(3 theme extensions excluded)

---

I see this error when pushing a Git repo:

```
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Steps to Reproduce:

1. Open a Git repo folder.
2. Call the Git push feature.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you push from the command line?

**Comment by joaomoreno** [comment]
#32097

**Comment by jublo** [comment]
Yes I can push fine from Terminal!
