### ISSUE TITLE
After installing VS Code from a debian package, I could not find a double clickable application

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3381]
On testing #2701:

The installer was only referring to a code-alpha command that I have to run from the command line:

![2016-02-24 00-20-50](https://cloud.githubusercontent.com/assets/1898161/13270168/889d82f4-da8c-11e5-93e7-e16161cbab09.png)

**Comment by Tyriar** [comment]
You should be able to find "Visual Studio Code Alpha" (or similar) on the launcher after hitting the Windows/Super key and searching for the application. I'll double check this works tomorrow.

**Comment by Tyriar** [comment]
This actually is an issue. Code is no longer showing in the launcher because it's pointing at the launcher script not the `Code` binary. This broke when the build became quality dependent.

**Comment by Tyriar** [comment]
After reinstalling I see it shows up fine in the launcher:

![image](https://cloud.githubusercontent.com/assets/2193314/13301829/bde5a4f4-dafb-11e5-967b-72fa1c41ce4b.png)

On the specific issue reported, this is expected for Ubuntu programs; the software center advises the associated `bin/` command and installs a `.desktop` file in `/usr/share/applications` which makes it show up in the launcher as shown in the screenshot.
