### ISSUE TITLE
jsconfig.json is overwritten at startup

### ISSUE THREAD

**Issue by tobiasWenger** [Microsoft/vscode#33825]
VS Code: 1.15.1
OS: Windows 10

I always get the message that I should configure my jsconfig.json file to exclude large folders. Unfortunately this file is overwritten on each VS Code startup and I'm therefore not able to exclude any additional folder. How can I change my jsconfig file?

**Comment by mjbvz** [comment]
We should never overwrite your jsconfig file. Do you know how is it being overwritten? Does this issue reproduce if you disable extensions by starting code with the `--disable-extensions` command line flag?

**Comment by tobiasWenger** [comment]
You are right. One of my extensions creates the jsconfig.json file. Thanks for pointing me in the right direction.
