### ISSUE TITLE
Extended host terminated unexpectedly. Please reload the window to restore

### ISSUE THREAD

**Issue by wangxingyuaaa** [Microsoft/vscode#33827]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@wangxingyuaaa That message can show for various reasons and it's not enough for us to reproduce this with the console log readings, the extensions you are using, and what you did? Please provide more information. Thanks
