### ISSUE TITLE
Go to Definition files to open in read only mode

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#33823]
There is a [feature request](https://github.com/Microsoft/vscode-go/issues/1190) to the Go extension to open files from the standard library in a read only mode when user navigates to them using the Go to Definition feature for example.

This would need us to update the api for the definition provider to return the extra info of whether the file at given location should be opened in read only mode or not.
Then the code that does the actual navigation need to be updated to open a read only mode of the file.

On the other hand, extensions can themselves create a new command that does this using the [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id458textdocumentcontentproviderspan). But the downside is that the real `Go to Definition` cmd still exists and will invariably get used by the user.

@Microsoft/vscode Thoughts?

**Comment by jrieken** [comment]
> There is a feature request to the Go extension to open files from the standard library in a read only mode when user navigates to them using the Go to Definition feature for example.

Why? If you don't want to accidentally change a file you can use OS-level support and mark it as readonly. We will handle that somewhat gracefully. 


> On the other hand, extensions can themselves create a new command that does this using the TextDocumentContentProvider. But the downside is that the real Go to Definition cmd still exists and will invariably get used by the user.

There is no need for a command. Just register a content provider for a certain scheme and make your definition provider return URIs like this `go:/some/lib/file/to.go`. When reveal/showing a definition/reference we will consult the (content) provider and its value as readonly

**Comment by ramya-rao-a** [comment]
Thanks @jrieken
