### ISSUE TITLE
VS Code is pointing an error in a no longer existing file.

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [Microsoft/vscode#33826]
![bug](https://user-images.githubusercontent.com/19404359/30050216-e3f12aa8-921d-11e7-828d-b8d601b92ede.png)
![bug](https://user-images.githubusercontent.com/19404359/30049569-78c07290-921b-11e7-9b8d-7c385c0b0541.png)
- VSCode Version: 1.15.1
- OS Version: Windows 8.1 Enterprise

1. I had changed the file name, or its folder's name before fixing bug.
2. I had fixed the bug.
3. The bug is continuing to exists, but in the no longer existing file, clicking on the error, and the popup panel shows that: ,,Unable to open 'Authorization.security.php'; File not found (...)."

So I think this is a VS Code bug.

**Comment by roblourens** [comment]
Are you using a PHP extension?
