### ISSUE TITLE
JS - feature request - detect object Event as the first argument in func

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33824]
- VSCode Version: 1.16.0 ins
- OS Version: win7x64

Feature request about specific snippets for "current" elem or object, that we write.

For example, object Event. That comes as the first argument in function-handler.
The snippets, like `stopPropagation`, is bound to the specific name "event":

![image](https://user-images.githubusercontent.com/24613274/30047312-2640a334-9219-11e7-972d-801107d914e7.png)

and it cannot detect the "e", as the default Event object, that comes as the first argument:

![image](https://user-images.githubusercontent.com/24613274/30047269-df966fae-9218-11e7-956a-1044f52cd754.png)

The argument can be "e", "ev", "evt", etc. That's not about adding new names to the detection list, but, if possible, to learn VS Code to detect that first combination of letters in the parenthesis, make VS Code understand, that it's the Event object, so it could make `"event" == "e"` but itself.
It's not critical, but it would make the VS Code a little bit smarter.

**Comment by yume-chan** [comment]
I think determine objects' type by their names is a bad idea.

But it's strange, TypeScript server can infer the type of `e` as `MouseEvent` in TypeScript files, but in JavaScript files they are of type `any` (When TypeScript server knows the type of `onclick`).

Maybe there are any reason to not do this in JavaScript? or just a bug?

**Comment by mjbvz** [comment]
Yes, I don't think we want to go around infering types from names. However is is not clear why this example does not work if `two` has the correct type. I've opened https://github.com/Microsoft/TypeScript/issues/18260 to track this.

As a workaround, try adding a JSDoc comment to give the type:

```js
const img = document.createElement('img')

img.onclick = function(/** @type {MouseEvent} */ e) {
    ...
}
```


Closing as upstream
