### ISSUE TITLE
[loc][Query][VSCode] Please clarify meaning 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode#33832]
Hi, we have a question from a translator. Could you help please?

Source:
Controls what changes are discarded by the `Discard all changes` command. `all` discards all changes. `tracked` discards only tracked files. `prompt` shows a prompt dialog every time the action is run.

---

File Name:
extensions/git/package.nls.json

Query:

The translation of some of the UI options could not be verified. Left in English with a suggestion in brackets in accordance with the instructions.

Ex. ( de-de 
Legt fest, welche Änderungen vom Befehl "Alle Änderungen verwerfen" verworfen werden. "alle" verwirft alle Änderungen. "tracked" (verfolgt) verwirft nur verfolgte Dateien. "prompt" (Eingabeaufforderung) zeigt immer eine Eingabeaufforderung an, wenn die Aktion ausgeführt wird. )

-

**Comment by joaomoreno** [comment]
The three keywords `all`, `tracked` and `prompt` should **not** be localized.
