### ISSUE TITLE
[loc][Query][VSCode] Please clarify meaning 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode#33830]
Hi, we have a question from a translator. Could you help please?

Source:
Controls sorting order of files and folders in the explorer. In addition to the default sorting, you can set the order to 'mixed' (files and folders sorted combined), 'type' (by file type), 'modified' (by last modified date) or 'filesFirst' (sort files before folders).

File Name:
src/vs/workbench/parts/files/browser/files.contribution.ts

Query:
Please advise whether the options "mixed", "type", "modified" and "filesFirst" are localizable. Left in English for the time being since concatenated words suchas "filesFirst" are usually not localizable.Please confirm
--

**Comment by bpasero** [comment]
@PDostalek yes, the values surrounded by quotes are not to be translated 👍
