### ISSUE TITLE
Debug npm scripts - missing start log

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#33831]
- VSCode Version: 1.15.1
- OS Version: mac

Steps to Reproduce:

**1. debug npm scripts**
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run-script",
        "debug"
      ],
      // "console": "integratedTerminal",
      "port": 9229
    }
  ]
}
```

---

**2. when use `"console": "integratedTerminal"`**

![image](https://user-images.githubusercontent.com/227713/30054072-7216f95e-925d-11e7-95af-663f9a0febcf.png)

- the `npm scripts` - `egg-bin debug` is not what need to debug.
- it will start cluster with debug execArgv

---

**3. when use `internalConsole`**

- **the start log is missing**
- it seems vscode only log to  `DEBUG CONSOLE` after attach sucess

![image](https://user-images.githubusercontent.com/227713/30054009-3dfeb1c0-925d-11e7-87e2-91fcb3f3871b.png)

---

**4. BTW:** is there any `env` that I can get the attach port at npm scripts? just like WebStorm's `$NODE_DEBUG_OPTION`, so I can detect it at my bin.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
@atian25 can you share a repository on github for which we can reproduce this issue so we can further investigate?

@roblourens it seems like some log statements are missing, I am not sure if the issue is on the `node2` side that it does not send the events, or on the vscode side that the events are coming too early and we are not reacting on them.

**Comment by atian25** [comment]
@isidorn  sure,  https://github.com/atian25/vscode-log

**Comment by roblourens** [comment]
The vscode-log project is starting a child process in debug mode, but the parent process is not in debug mode. Then vscode (or chrome devtools) attaches to the child and only gets its log messages. Does that explain it? The screenshot doesn't match vscode-log so I'm not sure if I'm getting it right.

**Comment by atian25** [comment]
@roblourens the `vscode-log` is a simple showcase for snapshot.

another simple showcase is:

```json
{
  "scripts": {
     "debug": "echo some_log ; node --inspect -e 'setInterval(() => console.log(process.version), 3000)'"
  }
}
```

the `echo` output will missing, so it is not a responsibilities of `Debug Console` or could be improve?

**Comment by roblourens** [comment]
The Debug Console will only show output that comes through node's debug channel, not all stdout.

**Comment by atian25** [comment]
got, seems I need to doc our users to use `integratedTerminal`.

thanks.

**Comment by roblourens** [comment]
I would recommend that as a workaround. Also relevant: https://github.com/Microsoft/vscode/issues/19750
