### ISSUE TITLE
(team) Unable to initialize the TF executable. Please verify the installation of Java and ensure it is in the PATH. (Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap)

### ISSUE THREAD

**Issue by leparduk** [Microsoft/vscode#33844]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16278
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.122.0
gitflow|vec|1.1.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please provide enough details for us to understand and repro the issue.

**Comment by leparduk** [comment]
Installed TFVC Extension. Tried to do Team: sign in. Java is installed and in the path. Path is configured for local TEE.

**Comment by roblourens** [comment]
Ok, please open an issue on their repo: https://github.com/Microsoft/vsts-vscode
