### ISSUE TITLE
Preserve word wrap state in target file when saving untitled file

### ISSUE THREAD

**Issue by basilevh** [microsoft/vscode#33840]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.10.0-27-generic

Without any extensions or custom user/workspace settings, word wrap always turns off when saving a file or renaming the current file from the explorer sidebar.

---

Steps to Reproduce:

1. Press Ctrl+N and type a long line.
2. Press Alt+Z to enable word wrap.
3. Save the file and note that word wrap has been disabled.
4. Re-enable word wrap and rename the current file. Word wrap should disable again.

Expected behaviour: I think the word wrap setting should stay the same when editing a file, no matter whether its name or location changes.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
When saving an untitled file, the URI of the file changes. Currently, toggled word wrap is captured per URI.

**Comment by bpasero** [comment]
@alexandrudima currently not, we just dispose the untitled editor model and create a new model [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileService.ts#L602). 

We do [`setValue`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileService.ts#L622) on the target and also carry over the encoding, we could carry over more state if you have a way for me to retrieve it and then set it (similar to the editor view state maybe?).

**Comment by alexandrudima** [comment]
@bpasero The state is kept in `ICodeEditorService` via `setTransientModelProperty` and `getTransientModelProperty`. IMHO this should move to ... the configuration service ...

**Comment by bpasero** [comment]
@alexandrudima yes, we talked about this with @sandy081.

**Comment by bpasero** [comment]
@sandy081 is there a way now to ask for transient configuration for a text model and apply it to a new model?

**Comment by sandy081** [comment]
There is in memory configuration which is available until window reload.

**Comment by bpasero** [comment]
**Update:** we are not using the in-memory config service for the editor yet.

**Comment by bpasero** [comment]
When saving a untitled or normal file under a different name, the text file service will now copy all transient properties to the new model. Currently this seems to only cover word-wrap.

**Comment by bpasero** [comment]
**Verification:** open an untitled or normal file and enable word wrap from "View" menu. Save the file as a different file name and verify the word wrapping is preserved.
