### ISSUE TITLE
cannot replace to ${1} when using regex to replace

### ISSUE THREAD

**Issue by ktangels** [Microsoft/vscode#33842]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.replace string 'a' with search pattern (a) to ${1}, the expected result is 'a', but indeed is '${1}'
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Is this a feature we've supported before, or a new feature request?

**Comment by transtone** [comment]
use `$1`, not `${1}`
