### ISSUE TITLE
High CPU usage when viewing workbench.main.js source in Developer Tools

### ISSUE THREAD

**Issue by duanehutchins** [Microsoft/vscode#33845]
- VSCode Version: 1.16.0-insider x64 (and 1.15.1 x86)
- OS Version: Windows 8.1 64bit

Steps to Reproduce:

1. Open Developer Tools, Sources tab
2. Navigate to and select **workbench.main.js** in `file://Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench`
3. Observe high CPU usage which locks Developer Tools for a few minutes or longer.
4. Closing Developer Tools will stop high CPU usage, which will resume if Developer Tools is opened again.

Reproduces without extensions: Yes

Even without pretty-printing the minified file, the workbench.main.js source file takes a very long time to load with high CPU usage. While it's loading, the Developer Tools is completely frozen.  Sometimes I end up on this file's source while debugging extensions, but this is not extension-dependant.

The load takes a few minutes, but after load completes, CPU usage returns to normal, and the file source can then be closed.  If the file source is not closed, reopening Developer Tools will again cause high CPU usage.  You can't use Developer Tools after this happens unless you wait a long time for the file to load or to try to quickly close the file source before the CPU locks up.

**Comment by roblourens** [comment]
This sounds like a Chrome devtools issue, not a VS Code issue. Besides loading the extremely large minified file, it is also downloading sourcemaps and sources in the background. So it's expected to use a lot of CPU. It would be nice if devtools would stay responsive while this is happening, and let me close the file, but that's on the Chrome team.
