### ISSUE TITLE
Git checkout should also show remote branches

### ISSUE THREAD

**Issue by jycouet** [Microsoft/vscode#3385]
When I press F1 and type Git Chechout [SPACE], I see that I can checkout each tag version of my project, but I don't have any branch appearing in the list!

When I git checkout manually by branch with a command tool, it's working well.
Then, when I go back to vscode, I can work well with by branch.

I would be nice to have the branchs in the list

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/13280331/a3bda810-dadd-11e5-953a-9e0d944dd938.png)

I can't reproduce.

What do you get when running `git branch -a` from the command line?

**Comment by jycouet** [comment]
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/5312607/13285567/b3f67766-dafb-11e5-9f99-e4309a27c55f.png)

**Comment by joaomoreno** [comment]
Right, you only have the `chartjs-2.0` and `master` branches. Those surely appear in the list?

We don't show the remote branches in the dropdown. We could do that.

**Comment by jycouet** [comment]
Since you see tags I would expect to see branches too :+1: 
In the dropdown, I only see tag, no branch.

**Comment by joaomoreno** [comment]
We do show local branches though, just not remote ones. If you create more branches locally (`git branch foo`), don't they show up there?

**Comment by jycouet** [comment]
Yes, you are right, when I create a local branch I can switch between my branches... Good!
What I found wired is to see remote tags but not remote branches. In my mind, we see both or none... but not like this.

What I would like to avoid is to use the command line to checkout a remote branch.

Anyway, VSCode is a great tool!

**Comment by joaomoreno** [comment]
Makes sense.

**Comment by vastbinderj** [comment]
This is exact issue plagued me today.  I couldn't see the remote branches.  I also wonder what flags are sent when `git fetch` is run which I think is an analog to `refresh` in vscode?

Also I'd expect the tool to mirror the functionality of the git command line, for example `git checkout` appears to actually be `git checkout -b` which creates a local branch.  I don't like that.  

It should mirror the git command usage and if I run `git checkout <branch_name>` and that branch does not exist locally, it should then checkout the remote branch.  If there is no remote branch of <branch_name>, it should error out with the appropriate pathspec error.  

I would instead expect to use `git branch <branch_name>` and then need to checkout that branch.  

I very much like a vim fugitive feature which wraps the `git` command and allows me to issue any git command if there is not a convenient mapping for what I want to do.  Perhaps vscode git integration could introduce a similar capability?

**Comment by kelchm** [comment]
This tripped me up today.  It's really confusing for `git checkout` to actually be doing `git checkout -b` when what I'm actually trying to accomplish is checkout a remote branch.

**Comment by joaomoreno** [comment]
@bpasero, please verify.

**Comment by bpasero** [comment]
Have been using it for a while and works nicely 👍

**Comment by pcgeek86** [comment]
@joaomoreno @bpasero Working great for me.
