### ISSUE TITLE
Feature request: git.clone command parameter

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#33857]
I would love to use the `git.clone` command. My UseCase is to fork a github project first (via API) and then clone the fork. For the user this could be just a simple task and he should not mess around with the URLs.

Right now the `git.clone` command does not allow to give an existing URL to clone but always asks for a url to input.

**Comment by joaomoreno** [comment]
Wanna submit a PR? This seems like a pretty simple one.

**Comment by KnisterPeter** [comment]
Sure, thanks :+1:
