### ISSUE TITLE
ability to change command and icon in explorer contribution

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#33860]
Once a command is defined in the explorer, there is no way to change the icon (as far as I can tell).

``` json
      {
        "command": "dockerExplorer.refreshExplorer",
        "title": "Refresh",
        "category": "Docker",
        "icon": {
          "light": "images/light/refresh.svg",
          "dark": "images/dark/refresh.svg"
        }
      }
```

I may want to change the set of commands or the commands themselves based on a config, state only known to me, or state in the tree itself.  

`when` clause support may be sufficient?

**Comment by jrieken** [comment]
Yes, you have to use the `when`-clause in the `menu`-contribution, *not* the command. There is also a way to set when-clauses from extensions see https://github.com/Microsoft/vscode/issues/10471#issuecomment-239764839
