### ISSUE TITLE
Fix Shift-Alt-Select to work more like Alt-Select in other programs and Literally every other select function in every program.

### ISSUE THREAD

**Issue by TarAlacrin** [microsoft/vscode#33862]
Right now Shift-Alt-Select is almost a useful feature. The only issue is that you have to click at the start of your selection then input the Unnecessarily long hotkey of Shift-Alt to then click once somewhere else that you want to edit.

The way this feature was implemented feels like a hack because you don't have control over selections or mouse drags or something, But can you please go in and re do this feature. Its the only thing holding VS code back from being a good program that I can recommend and use every day.

Right now the tradeoff is should you go with the program that is slick and sleek at the expense of losing an essential quality of life feature that I've had since I first learned java on Notepad++ a decade ago and that basically every single other code editor has. The answer is obviously that I don't use VS code. Which is a bummer.

Steps to Reproduce:

1. Shift-Alt-Select. The feature is 90% implemented.

**Comment by alexandrudima** [comment]
This has been improved in 1.32. See https://code.visualstudio.com/updates/v1_32#_improved-column-selection

Let's track the rest of the gaps in #5402
