### ISSUE TITLE
Not able to debug/launch Go programs

### ISSUE THREAD

**Issue by karamana** [Microsoft/vscode#33867]
go: GOPATH entry is relative; must be absolute path: "undefined".
For more details see: 'go help gopath'
exit status 2
Process exiting with code: 1

GOPATH is set in the environment correctly. This has worked for the past 2 months so something has changed today (Spet/5/2017) with an extension possibly. 

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
markdown-toc|Ala|1.5.6
Bookmarks|ale|0.16.0
go-builder-help|ans|2.1.2
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.4.3
tslint|eg2|0.17.0
code-runner|for|0.7.1
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
Go|luk|0.6.64
start-git-bash|McC|1.2.1
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.2.1
vscode-docker|Pet|0.0.16
vscode-icons|rob|7.12.0
gitblame|wad|2.1.0
JavaScriptSnippets|xab|1.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1194
