### ISSUE TITLE
I had set "emmet.syntaxProfiles": {"blade": "html"},but I can't use Emmet In blade file,

### ISSUE THREAD

**Issue by zhengchengwu** [Microsoft/vscode#33876]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
laravel-blade|one|1.8.1
open-html-in-browser|pea|0.0.2
vscode-icons|rob|7.12.0
laravel-5-snippets|sac|2.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Use the setting `emmet.includeLanguages` instead and read [Emmet configuration](https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration)
