### ISSUE TITLE
Opening VS Code from command line (and then doing a bunch of work in cmd) and then ctrl+c kills VS Code

### ISSUE THREAD

**Issue by ianhan** [Microsoft/vscode#33872]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.16266
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3
SystemVerilog|msh|0.0.15
VerilogHDL|msh|0.0.13

---

Steps to Reproduce:

1. Launch VS code via file association (e.g. just run foo.cpp from a cmd)
2. Control returns to cmd, cd around your drive, etc.
3. Eventually hit ctrl+c (while still in cmd). Code closes.
4. Realize this is terrible and fix it.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
#20769
