### ISSUE TITLE
Doesn't open file with double click

### ISSUE THREAD

**Issue by SergeyLAI** [Microsoft/vscode#33871]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2

---

Steps to Reproduce:

1. During install set as default editor for all supported format when installer asks.
2. Try to open file with .xml extension with double left mouse button clicking (other extensions are also could be broken but I didn't test them all)
3) Then Windows 10 "How do you want to open this file" dialog appears and after you choose VS code nothing happens.
4) If VS Code was started beforehand everything is ok. Also everytime is possible to open file from right-click menu.
 
Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Maybe you have to restart for windows to take the defaults into effect? Have you done that?

Does the vscode logo show up in the file icon in windows explorer?

**Comment by SergeyLAI** [comment]
This issue can be reproduced even after restart (reboot) for windows.

**Comment by joaomoreno** [comment]
Does it work if you right click and `Open With Code`?

**Comment by SergeyLAI** [comment]
Yes, it works

**Comment by joaomoreno** [comment]
So:
- `Open with` always works
- Double click when Code is running always works
- Double click when Code is not running never works

Did I get this right?

**Comment by SergeyLAI** [comment]
Yes, that's right but seems that last point depends from extension. For example I have not had problem with simple txt files but with other extensions this problem appears sometimes.
Last extension where this issue was reproduced was "xml" but it is not the only one because there is at least one more (unfortunately I forgot which one)

**Comment by joaomoreno** [comment]
But it's consistent within each extension? Always works for some, never works for others?

**Comment by SergeyLAI** [comment]
Yes, that's right

**Comment by SergeyLAI** [comment]
http://take.ms/5rF3H

**Comment by SergeyLAI** [comment]
Solved
