### ISSUE TITLE
the VSCode gave me this warning when running

### ISSUE THREAD

**Issue by HZzzzy** [Microsoft/vscode#33877]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.4.5|
|vscode-weapp-api|coderfee|0.1.8|
|vscode-wxml|coderfee|0.1.9|
|vscode-eslint|dbaeumer|1.2.11|
|auto-close-tag|formulahendry|0.4.3|
|beautify|HookyQR|1.1.1|
|vue|jcbuisson|0.1.5|
|vetur|octref|0.9.5|
|vscode-wechat|qinjia|0.0.6|
|vscode-icons|robertohuertasm|7.12.0|
|linux-themes|SolarLiner|0.5.0|;

---

when this happens I can`t use the git plugin
![dyyt6ju k9u f6mdpjb10](https://user-images.githubusercontent.com/18050675/30098953-a663c2b4-9316-11e7-9017-86d7a83b475d.png)

**Comment by roblourens** [comment]
Does it say that the extensionhost stopped? When does this happen? How often? Does it happen if you start with `--disable-extensions`?

**Comment by HZzzzy** [comment]
extensionhost stopped,and it happens everytime when I excuting my program with VSCode, but it didn`t have this problem in old version

**Comment by HZzzzy** [comment]
my workmates don`t have this problem, I have no idea if there`re some problems with my Git or VSCode`s setting
![z 4op g6menl o5j](https://user-images.githubusercontent.com/18050675/30144825-383dc032-93c0-11e7-9e3f-200bd2fc1a84.png)

**Comment by roblourens** [comment]
>  it happens everytime when I excuting my program with VSCode

What do you mean exactly, what do you do that causes this to happen? Does this happen when you start with `--disable-extensions`?

**Comment by HZzzzy** [comment]
I tried with 'disable all installed extensions for this workspace', and it seams to work well

**Comment by roblourens** [comment]
It sounds like some extension is going crazy and using too much memory. If you reenable your extensions one by one, then maybe you can figure out which one it is.
