### ISSUE TITLE
different path of the same file

### ISSUE THREAD

**Issue by fishfishson** [Microsoft/vscode#33870]
- VSCode Version: 
1.15.1
- OS Version:
win10

i have some code mistakes in the cpp file, run it and vscode tells me there some mistakes.
in the **explorer** the file path is c:\code\test1.cpp
 but int **problems** the file path is c:\code\c:\code\test1.cpp
![img_9355](https://user-images.githubusercontent.com/28746110/30094265-9df77bf2-92fd-11e7-804a-e6ad0c2e1851.JPG)
![img_9356](https://user-images.githubusercontent.com/28746110/30094266-9dff52e6-92fd-11e7-80c2-3bd0f136efba.JPG)

the true path is the first one
so when i click the error in the problem and vscode tells me it cant find the file.
how to fix it?

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Is the error coming from a task with a problem matcher? If so, you may need to fix your problem matcher config.

Or is it coming from an extension? If so, you should file an issue on that extension.

**Comment by fishfishson** [comment]
so where to check the problem matcher config?  in the setting.js or task.js? sorry i dont konw what's the meaning of extension.

**Comment by roblourens** [comment]
In a `.vscode/tasks.json` file, if you're using one.

And I mean, if you have installed a C++ extension that might be providing these problems. You can see your installed extensions in the extensions viewlet.
