### ISSUE TITLE
Cannot expand prototype

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3387]
Testing #2941

`prototype` has a twisty so IMHO there should be some content under it

![expand-prototype](https://cloud.githubusercontent.com/assets/5047891/13279885/f19bb5f2-dada-11e5-939f-adf5e320c513.gif)

```javascript
function Safe(_key) {
    var _locked = true;
    var _value = null;
    
    this.unlock = function(key) {
        if (_key === key) {
            _locked = false;
        }
        return;
    };
    
    this.lock = function() {
        _locked = true;
    };
    
    Object.defineProperty(this, 'value', {
        get: function() {
            if (_locked) {
                console.log('thief detected!');
                process.exit(0);
            }
            return _value;
        },
        
        set: function(value) {
            if (_locked) {
                console.log('thief detected!');
                process.exit(0);
            }
            _value = value;
        }
    });
}

var safe = new Safe('mySecretPassword');

safe.unlock('mySecretPassword');
safe.value = 3;
console.log(safe.value);
safe.lock();


```

**Comment by isidorn** [comment]
The prototype has a twistie because it has reference > 0 as returned by the adapter. On the vscode side we expand it lazily which means we only request children once the user clicks expand.

So this might be a feature request that variables with no children should not have reference > 0
Moving to @weinand

**Comment by alexandrudima** [comment]
Not sure I'd label this one as a feature request :), my end user impression is that there is a bug in the hover, in the tree, or in the debugger.

**Comment by weinand** [comment]
@alexandrudima for structured objects, we do not know whether it has properties without fetching them (the v8debugger protocol does not provide a mechanism for retrieving the number of properties independently from fetching them all). Fetching all properties all the time just to learn whether a twistie is required or not can be very expensive if the object is large (e.g. an array).

This strategy is consistent with the VS Code navigator: it shows a twistie for folders even if the folder is empty.

**Comment by alexandrudima** [comment]
You're correct, we do the same in the explorer, which I also find weird :). I guess I don't deal with empty folders often. Check this one out:

No twisties next to unexpandable folders (folders without subfolders)

![image](https://cloud.githubusercontent.com/assets/5047891/13282339/d2d996f8-dae8-11e5-9cde-01e653b3af9b.png)
