### ISSUE TITLE
<pre> breaks Markdown Coloring

### ISSUE THREAD

**Issue by JBurny** [Microsoft/vscode#33886]
It appears that when using a combination of `<pre>` and `<code>` it breaks any sort of markdown related coloration that comes even after both tags are closed. For example, headers will now display as the same color as the text that falls under them. (Screenshot at bottom)

Using these tags is necessary for mark down to recognize other tags (such as <mark>) within the code block. Using ` ``` `or the indentation technique results in those tags becoming plain text instead. It appears the main problem is with the `<pre>` tag, rather than `<code>`.

- VSCode Version: 1.15.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Create Headers.
2. Create Text Below Headers.
3. Create Code Block using `<pre><code>`, and input text.
4. Close Code Block using `</code></pre>`.
5. Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/28165449/30109058-def290fe-92d2-11e7-9917-983ffecc691b.png)

**Comment by mjbvz** [comment]
Simple repo:

```md
# h

<pre>
a</pre>

# h
```

![screen shot 2017-09-06 at 1 51 02 pm](https://user-images.githubusercontent.com/12821956/30133961-70f15c9c-930a-11e7-8d46-348d0cab1594.png)
