### ISSUE TITLE
unable to uninstall vscode 32bit on windows 7

### ISSUE THREAD

**Issue by agusmba** [Microsoft/vscode#33883]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601 (Windows 7 Enterprise)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|4.4.3
material-icon-theme|PKi|2.2.0
qub-xml|qub|1.2.1

Steps to Reproduce:

1. Install (or reinstall) vscode 32bit 1.15.1
2. Try to uninstall vscode

Instead of uninstalling I receive an error about a corrupted unins000.dat
I have tried re-installing 1.15.1 and it apparently installs correctly, but I get the same error when trying to uninstall. Therefore I cannot test the 64bit install version.

Reproduces without extensions: Yes (no need to run vscode)

Thanks!

**Comment by joaomoreno** [comment]
Attempt to uninstall. When failing, manually remove the `C:\Program Files\Microsoft VS Code` folder and then reinstall everything over again.

**Comment by agusmba** [comment]
Ok, will do.
It failed again at uninstall.
I removed `C:\Program Files (x86)\Microsoft VS Code`
I re-installed the 32bit version 1.16.0 (more recent than the 1.15.2 that gave me problems)
Normal uninstall worked now.
I installed the 64bit version 1.16.0.
All seems to be working fine now.
Thanks @joaomoreno !
