### ISSUE TITLE
Not possible to disable error highlighting in VS Code

### ISSUE THREAD

**Issue by joergrech** [Microsoft/vscode#33887]
I couldn't get an answer on [SO](https://stackoverflow.com/questions/46061857/how-to-disable-error-highlighting-in-vs-code) so I ask / report my problem here:
 
- VSCode Version: 1.15.1
- OS Version: MacOS 10.12.6

I can't disable the error highlighting in java files. There seems to be no setting to disable the highlighting of errors/warning. I need to disable error highlighting in Java files in VS Code. VS Code tries to check a Groovy file while thinking it is a Java file (which is intended).

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@joergrech Why is the Java mode active on your groovy file? Does it use the `.java` file suffix?

**Comment by joergrech** [comment]
I switched groovy files to java files for code formatter such as uncrustify or clang. Without it the context menu to "format documents" are hidden.

```
"files.associations": { // for uncrustify
    "*.groovy": "java"
},
```

Therefore, the java error highlighting is activated but not needed for my use cases.

**Comment by aeschli** [comment]
If the uncrustify or clang formatters are also useful for groovy files, I'd suggest that you file a feature request against these extensions so they enable the formatter also for groovy files.
Aternativly, file a request against the Java extension to enable/disable validation.
