### ISSUE TITLE
macOS: show more native tab related actions when tabs are enabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33884]
When native tabs are enabled on macOS (`"window.nativeTabs": true`) we should add more actions to the Windows menu that are tab related:

![image](https://user-images.githubusercontent.com/900690/30107948-abb94a42-9300-11e7-8b46-5d097f064592.png)

**Comment by bpasero** [comment]
**Verification:** 
* enable macOS tabs via `"window.nativeTabs": true`
* group some windows together as tabs (drag and drop them on the title area to do this or click the "+" button on the right hand side)
* use the native tab related actions and verify functionality makes sense

**Comment by RoarkeRandall** [comment]
Are "Show Previous Tab" and "Show Next Tab" available from the shortcuts menu? I only see settings for workbench tabs
