### ISSUE TITLE
always lose intellisense after serveral minutes' coding

### ISSUE THREAD

**Issue by ivyhaswell** [Microsoft/vscode#33882]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
docthis|joe|0.4.8
vscode-csscomb|mrm|5.1.0
sass-indented|rob|1.4.1
gitblame|wad|2.1.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. open workspace
2. start webpack compile and node debugger
3. coding for serveral minutes
4. tada~ no intellisense 

Reproduces without extensions: Yes
Still the same result with no extension working. Maybe it's caused by too many files? My workspace contains over 2000 files (exclude `/public`  `/node_modules` and so on...).

**Comment by mjbvz** [comment]
Hey, sorry this fell off my radar.

Are you still running into this with VS Code 1.18?

**Comment by ivyhaswell** [comment]
Problem occured less than before, but still on

**Comment by mjbvz** [comment]
Please try collecting the TypeScript server logs to see if that has any leads:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Run the `Typescript: Open TS Server log` command in vs code and look in the `tsserver.log` file in the opened directory

Look near the end of the logs for errors or long running requests. If you are able to share the logs, I can also look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Closing as we cannot investigate this without more information. Please let me know if you are able to collect the TS server logs
