### ISSUE TITLE
selectionHighlight still slow and blocking for long non-wrapped lines

### ISSUE THREAD

**Issue by myfonj** [Microsoft/vscode#33885]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
---

## Steps to Reproduce:

1. Save `https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg` and open in VSC.
2. Ensure settings `"editor.selectionHighlight": true` <ins datetime="2017-09-12T14:18:59+02">and `"editor.fontLigatures": true`</ins>
3. Select entire document.
4. Invoke `>Join Lines`.
5. If lines are wrapped, invoke `>Toggle word wrap` .
6. Select `0` (zero, or any other digit).

## Actual behavior:

Editor **completely frozen** (i.e. does not react for any kind of input) **for circa 15 seconds**.
After highlights appear editor works normally again.

## Expected behavior: 

No freeze.
Would not mind missing or delayed highlights.

## Notes:

Quite OK with wrapped lines.
Older (closed) issues relevant to this "long lines" topic: #31425 #6885 #13515 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@myfonj I am thinking we are running into #33525 which is similar, when we don't end up doing our monospace optimizations and end up relying on Chromium to give us the positions of the highlights.

I am thinking this issue reproduces when:
* not using a monospace font
* (or) enabling ligatures

Can you please confirm that is the case ?

**Comment by myfonj** [comment]
Ah, ligatures! Yes, confirming: setting `"editor.fontLigatures": false` prevents described lag from happening.

**Comment by alexandrudima** [comment]
Thank you. Let's continue tracking in #33525
