### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by Duchynko** [Microsoft/vscode#33889]
Hello. 
I just installed the VS Code and I'm getting this popup error. 
I didn't install any extensions yet, didn't connect my github and didn't change any settings.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open VS Code
2.

**LOGS>** 

```
Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t.onExit @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
```

---

Reproduces without extensions: Yes

**Comment by Duchynko** [comment]
After update to 1.16. I'm getting some new errors in my logs. 

`Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ extensionService.ts:162
(anonymous) @ extensionService.ts:135
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
t._onExtHostProcessExit @ extensionHost.ts:423
(anonymous) @ extensionHost.ts:200
emitTwo @ events.js:106
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
00:27:16.407 messageService.ts:125 Extension host terminated unexpectedly.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e._onExtensionHostCrashed @ extensionService.ts:169
(anonymous) @ extensionService.ts:135
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
t._onExtHostProcessExit @ extensionHost.ts:423
(anonymous) @ extensionHost.ts:200
emitTwo @ events.js:106
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215`

`

  | e.doShow | @ | messageService.ts:125
-- | -- | -- | --
  | e.show | @ | messageService.ts:104
  | e._onExtensionHostCrashed | @ | extensionService.ts:169
  | (anonymous) | @ | extensionService.ts:135
  | e.invoke | @ | callbackList.ts:63
  | e.fire | @ | event.ts:123
  | t._onExtHostProcessExit | @ | extensionHost.ts:423
  | (anonymous) | @ | extensionHost.ts:200
  | emitTwo | @ | events.js:106
  | emit | @ | events.js:194
  | __dirname.ChildProcess._handle.onexit | @ | internal/child_process.js:215`

`/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28
00:27:16.405 `

**Comment by alexandrudima** [comment]
Well, the error code `3221225477 ` is `0xC0000005` or Access Violation, roughly the equivalent of segmentation fault. That basically doesn't tell us the root cause.

@ramya-rao-a @bpasero it would help if we can add a command line flag where a dump can be collected from an extension host process when it crashes. 

Last time I talked to @bpasero about it, we have no way to get a dump of the extension host process. What would we need to do to add such a flag?

**Comment by bpasero** [comment]
We do not run the crash reporter for the extension host on Windows, so currently there is no way to get a dump for a process. However, it would be nice to be able to enable the crash reporter for the extension host specifically through a command line flag.

**Comment by bpasero** [comment]
@Duchynko 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Duchynko** [comment]
@bpasero This one works without problems I guess 👍 Looks I will keep using this one. Thank you guys.

**Comment by bpasero** [comment]
@Duchynko does it reproduce using the stable build when from the command line you do "code --user-data-dir=<some folder>"?

**Comment by Duchynko** [comment]
@bpasero Fuuny but after I installed the insider version, the stable version is working without problems as well. Even after uninstalling the insider version. And after using "code --user-data-dir=" into command line, I didn't get any changes/errors reproduced.

**Comment by luetin** [comment]
I get the same popup error all the time. 

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

In the console it says:
module.js:472
    throw err;
    ^

Error: Cannot find module 'c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

**Comment by JkVon** [comment]
Me too,the same popup error.
Code:3221225477

Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ /D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28
/D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly.

**Comment by alexandrudima** [comment]
@JkVon This crash is indeed caused by installing an extension that **edits** the VS Code installation. You need to uninstall VS Code from the Program and Features Windows dialog and reinstall it again to get a non-corrupted installation.
