### ISSUE TITLE
无法格式化代码，各种快捷键 命令 都不起作用

### ISSUE THREAD

**Issue by xiaguLMJ** [Microsoft/vscode#33894]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Can you include more details about how you tried to format the code? What type of file? Are you trying to use an extension to format it?
