### ISSUE TITLE
`Reapply all breakpoints` seems like a bug exposed to the user

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3389]
Testing #2832 

`Reapply all breakpoints` -- I haven't seen such an action in other debuggers. IMHO it is the debugger's job to apply my breakpoints, and exposing an action to reapply all breakpoints seems like a workaround for a bug inside the debugger.

**Comment by isidorn** [comment]
I agree with your reasoning however sometimes it the debugger adapter does not know when is a good time to reapply breakpoints. @weinand can provide more details.

Also the react people really want this feature, so we will for sure not remove it.
We can make it more hidden by removing it from the viewlet and keeping it as a global workbench action
@weinand opinions?

**Comment by weinand** [comment]
We could get rid of this in the UI if we would call it on every stopped event. This would slow down stepping.

**Comment by alexandrudima** [comment]
If you compare breakpoints to watch expressions, I find it nice that there is no refresh button on the watch expressions (the debugger knows when it's a good time to re-evaluate them).

Maybe the debugger could keep a list of function breakpoints it could not apply and every chance it gets it tries to reapply the function breakpoints until they were applied successfully. Or perhaps report it to the UI on every pause that this function breakpoint is not active, is active, etc.
