### ISSUE TITLE
Suggestion Lightbulb Icon Incorrectly positioned

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#33895]
- VSCode Version: Code - Insiders 1.17.0-insider (be71eecef0bff8ad4a84ce06cd54b9185bc8c306, 2017-09-06T05:15:43.568Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
erb|Cra|0.0.1
html-leaf|Fra|0.1.3
json-to-ts|Mar|1.5.3
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
angular2-snippets|dan|1.0.16
githistory|don|0.2.3
tslint|eg2|0.17.0
vscode-ember|emb|0.1.0
prettier-vscode|esb|0.23.1
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.1.1
Angular2|joh|2.7.0
csharp|ms-|1.12.1
typescript-javascript-grammar|ms-|0.0.23
debugger-for-chrome|msj|3.2.1
EmberES6Snippets|pha|2.1.2
typescript-hero|rbb|1.4.0
vscode-icons|rob|7.12.0
git-merger|sha|0.3.6

(2 theme extensions excluded)

---

The lightbulb icon for suggested fixes is positioned incorrectly. It is not in the left margin - it is right against the test. And in some cases it is positioned on the wrong line.

![screenshot at 2017-09-06 09-47-56](https://user-images.githubusercontent.com/13488/30115406-9d59a946-92e8-11e7-9b5e-b026b28cebc8.png)

**Comment by roblourens** [comment]
Do you have line numbers visible? Can you show a little more context in the screenshot? Thanks

**Comment by jtsom** [comment]
Yes I do.

![screenshot at 2017-09-06 14-13-37](https://user-images.githubusercontent.com/13488/30127541-a6080e46-930d-11e7-9c8d-e26a9d173de9.png)

**Comment by mjbvz** [comment]
Looks like this only happens in master. Possible from #33682

**Comment by jrieken** [comment]
That is the new design/position of the lightbulb. Showing it in the gutter left of the line number was troublesome because it prevents you from setting/configuring breakpoints. This is why we settled on showing the leading whitespace area of a line (often code is indented) or above/below the line (no indent). See #25174, https://github.com/Microsoft/vscode/issues/25174#issuecomment-326259960 for more background. Closing this as dupe

**Comment by jtsom** [comment]
Uh. then this is an HORRIBLE design choice.

Do you not see the lightbulb overwriting the code text?

Do you not see the lightbulb not even on the CORRECT line?

In my second screenshot, I clicked on the red underlined code on line 9 but the lightbulb is showing on line 8 - nowhere near where it is indicating the problem is
