### ISSUE TITLE
DNF doesn't pick up the latest package version

### ISSUE THREAD

**Issue by tvieira** [Microsoft/vscode#33897]
- VSCode Version: code-1.14.2-1500507068.el7.x86_64
- OS Version: Fedora 26 - 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
1. Install the package code-1.14.2-1500507068.el7.x86_64
2. Follow steps on https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions to add the vscode repository.
3. Install vscode: 
```
$ sudo dnf install code
```
The message shown is:
```
Last metadata expiration check: 0:00:27 ago on Wed 06 Sep 2017 10:09:01 AM EDT.
Package code-1.14.2-1500507068.el7.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```

The package code-1.15.1-1502904099.el7.x86_64 is in the repository but the DNF command doesn't recognize as the latest package. To overcome this issue I had to install the package directly like:
```
sudo dnf install https://packages.microsoft.com/yumrepos/vscode/code-1.15.1-1502904099.el7.x86_64.rpm
```

**Comment by David-Else** [comment]
I can't update to 1.16! Please see attached screenshot, I assume it is the same bug.

![code-fedora-dnf-broken](https://user-images.githubusercontent.com/12832280/30211479-1c45e1c8-9499-11e7-8891-3429ce558d9e.png)

**Comment by David-Else** [comment]
STILL BROKEN. Is Fedora still supported? Any feedback?
![still-broken](https://user-images.githubusercontent.com/12832280/32698774-c5e73ee8-c7a2-11e7-87bd-147265504d27.png)

**Comment by Tyriar** [comment]
1.19.0 has been pushed to the repo, let me know if it didn't work and I'll reach out to the repo team.
