### ISSUE TITLE
Create File overwrites existing files without warning

### ISSUE THREAD

**Issue by Obbi89** [Microsoft/vscode#33899]
- VSCode Version: Code - Insiders 1.17.0-insider (be71eecef0bff8ad4a84ce06cd54b9185bc8c306, 2017-09-06T05:15:43.568Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
xml|Dot|1.9.2
vscode-docker|Pet|0.0.16
django-html|bib|1.2.0
django-snippets|bib|1.1.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jupyter|don|1.1.3
python|don|0.7.0
python-extension-pack|don|1.0.0
MagicPython|mag|1.0.12
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
vscode-icons|rob|7.12.0
perltidy|sfo|1.2.1
vim|vsc|0.10.0
gitblame|wad|2.1.0
jinja|who|0.0.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. create a file externally for example use the integrated terminal and do "wget https://wowsocool.domain.tld/supersecretpath/veryimportant.file.ext"
2. see that the file browser does not recognize the new file that was created.
3. click on create file and enter the filename of the existing file
4. ????
5. Profit! Your file has been truncated.

Reproduces without extensions: No

This is weird. It seems that one of the extensions is preventing the folder to be re-scanned and updated.
But even though it is a bug that the file gets truncated if it already exists. Even if it would correctly update it would still be racy and that is bad. I guess this bug is rather low prio but it should be relative easy to fix tbh.

**Comment by roblourens** [comment]
> see that the file browser does not recognize the new file that was created.

This should work. Does it never see the new file? Even if you use vim or `echo 'foo' > file.txt`?

**Comment by Obbi89** [comment]
This set of extensions I have seems to cause this.
Maybe it causes the open-files / file handle limit to be reached for watching folders or w/e

But even though. A file should never be overwritten by a create-file dialogue.

**Comment by Tyriar** [comment]
> Maybe it causes the open-files / file handle limit to be reached for watching folders or w/e

Have you boosted the file watch limit? https://code.visualstudio.com/docs/setup/linux#_error-enospc

**Comment by Obbi89** [comment]
Well I could, but why should I and it still is unrelated to the issue. It should be impossible to overwrite an existing file. And moving this into a different layer and blocking the function from being called is not the right solution tbh.

It will stay racy and it's bad design.

**Comment by Tyriar** [comment]
@bpasero do we do a file check before creating a few or do we rely on the file watcher giving us an accurate tree?

**Comment by bpasero** [comment]
`createFile` is just creating the file which is not good, we should check if the file exists and maybe provide an option to override the file if it exists.
