### ISSUE TITLE
No validation on load, only after type

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#33896]
* on master
* have the typescript file below, see errors
* reload the window
* typescript comes up, but doesn't validate the files
* make a change and validation happens

![sep-06-2017 15-54-52](https://user-images.githubusercontent.com/1794099/30115899-5a8cc8bc-931c-11e7-85ea-3edb149c6c40.gif)

```ts
ssss



console.log(<IMe>{
    foo: true,
    bar: tullllllllllllllllllllllllllllllle
})
a1
a

class MarkdownString {

    static escaped(value: string): MarkdownString {
        const six = 1 + 2 + 3;
        let result = new MarkdownString();
        result.value = value;
        return result;
    }

    value: string;
}


interface IMe {
    foo: boolean;
    bar: tre;
}

dd


type MarkedString = string | { lang, value } | MarkdownString


/**
 * This [click for more](command:deleteLeft)
 * List of tags, comma separated, that shouldn't be reformatted\. 'null' defaults to all tags listed at https://www\.w3\.org/TR/html5/dom\.html\#phrasing\-content\.
 */
function fff(): IMe {
    return {
        foo: true,
        bar: true
    }
}

function $fff(m: IMe): IMe {
    return {
        foo: true,
        bar: true
    }
}



$fff({ foo: false, bar: true });


const six = 1 + 2 + 3;

{
    const six = 1 + 2 + 3;
}


array.forEach(element => {

});



```

**Comment by mjbvz** [comment]
I just rebuilt from master and can't repo this on mac.

1. Is the file part of the workspace?
1. Does your workspace have a `jsconfig` or `tsconfig`?
1. Do any of the other hovers work, such as for `console.log`?

**Comment by jrieken** [comment]
This is from `script/code.sh` and my test workspace. It doesn't reproduce anymore. Maybe some other condition triggered this?
