### ISSUE TITLE
Very weird color in default Solarized Dark theme ever since some startup

### ISSUE THREAD

**Issue by circlecrystal** [Microsoft/vscode#33890]
- VSCode Version: Version 1.16.0-insider (1.16.0-insider)
- OS Version: 10.12.6 (16G29)

Steps to Reproduce: 

1. Start the app "vscode" or "vscode-insiders"

Reproduces without extensions: Yes

![vscode-solarized-dark](https://user-images.githubusercontent.com/5665980/30112757-04f31f90-9345-11e7-9c3c-034f6f9e6fdd.png)

![screenshot](https://user-images.githubusercontent.com/5665980/30112764-0aaff0c0-9345-11e7-88c9-b66f3c96bb5c.png)

The color of the default theme is very weird ever since some startup. Before that startup of the app, it looks like the above. Now it becomes very greenish in the below.

I experienced the exactly same problem in another app "Hyper" (a terminal app) as well. Since both Hyper and Vscode are using electron, I`m wondering if this is an issue of electron?

Meanwhile, all the other colorschemes are fine.

Please help me to fix this weird color problem. Many thanks!

**Comment by circlecrystal** [comment]
I tried to replicate the issue by switching back&forth my Mac OS X system color profiles.

The issue is fixed now.

**Comment by roblourens** [comment]
Strange, sounds like a MacOS issue. Thanks for following up.
