### ISSUE TITLE
Feature Request : Toolbar Styles ( Especially for Linux)

### ISSUE THREAD

**Issue by muhajirframe** [Microsoft/vscode#33891]
- VSCode Version: 1.15.1
- OS Version: Elementary OS Loki 0.4.1

Here's how current vscode toolbar looks on my desktop.
![vscode](https://user-images.githubusercontent.com/12745166/30113724-dc14486a-933f-11e7-9750-fcd3bbdbfaaf.png)

I am sure we can make it more stylish and bind with theme color, like shown here : 
![image](https://imgur.com/eQt9Z1u.png)
I took this image from https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme . It is probably running on Windows machine.

But I am sure, we can also make the toolbar stylish in linux,
This is [Gravit Designer](https://designer.io) app (also based on electron) running on my linux machine. *Note the toolbar.
![gravit](https://user-images.githubusercontent.com/12745166/30113927-73359618-9340-11e7-8fa3-08352f79fc83.png)

So, I think it's very possible to implement that on linux machine too.

**Comment by roblourens** [comment]
Electron supports this on Mac but I think not on other platforms yet.

**Comment by muhajirframe** [comment]
The gravit designer app (image above) seems already implemented that. I took the screenshot on my own linux machine

**Comment by harisvsulaiman** [comment]
@muhajirframe I believe gravit made electronjs chromeless and developed a custom chrome for their app.
Check the electronjs docs

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31926
