### ISSUE TITLE
Emmet not working properly

### ISSUE THREAD

**Issue by psingl** [Microsoft/vscode#33893]
- VSCode Version: 1.15.1
- OS Version: Windows 7 32-bit

I have installed no extension yet on my new install of VSCode. I am not able to use emmet properly.
Eg.
1. Open any empty html file
2. Type `app-navbar`
3. Press Tab.

In version 1.10 and some other later versions, when we do the same the `app-navbar` expanded to `<app-navbar></app-navbar>`. But in this version 1.15.1 I am not able to expand that abbreviation.

**Comment by crock** [comment]
I've noticed Emmet is no longer working at all for me. The keyboard shortcut is still set to tab, but it's not triggering expansions in HTML or PHP files.

This configuration used to work fine, so I'm not sure why it's not working now.
```
 "emmet.syntaxProfiles": {
        "blade": "html",
        "vue": "vue"
    },
    "emmet.includeLanguages": { 
        "laravel-blade": "html",
        "php": "html"
   },
```

**Comment by ramya-rao-a** [comment]
@psingl @crock 

There have been major changes to Emmet in the July release of 1.15
Please go through the [Emmet 2.0 blog](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
Or the [Emmet documentation for VS Code](https://code.visualstudio.com/docs/editor/emmet)

For tab to expand Emmet abbreviations, set `emmet.triggerExpansionOnTab` to `true`
