### ISSUE TITLE
Installer is signed, extracted exe is not

### ISSUE THREAD

**Issue by Hedkandi** [Microsoft/vscode#33892]
- VSCode Version: 1.15.1
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Apply applocker policies which denies anything not signed and allows signed exe-files
2. Run VSCode install
3. Get this message in AppLocker log:
"%OSDRIVE%\USERS\USERNAME\APPDATA\LOCAL\TEMP\IS-A02HI.TMP\VSCODESETUP-X64-1.15.1.TMP was prevented from running."

Turns out that the exe-file you download is signed but the one which is extracted and run, is not.

**Comment by joaomoreno** [comment]
I believe the one which is unsigned is the uninstaller. #2416
