### ISSUE TITLE
After delete folder from navigation bar, can't add deleted folder back

### ISSUE THREAD

**Issue by 123names** [Microsoft/vscode#33908]
- VSCode Version: 1.15.1
- OS Version: windows 10 home version 1703 OS build 15063.540

Steps to Reproduce:

1.ctrl+o open a folder
2.remove folder from sidebar
3. ctrl+o reopen the same folder

Reproduces without extensions: Yes/No
yes

**Comment by roblourens** [comment]
What do you mean by "remove folder from sidebar"?

Can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

**Comment by iMahesh** [comment]
Mr @roblourens ,
@123names meant by this (look in the attached image)  
![image](https://user-images.githubusercontent.com/19846657/30151035-b76d5eac-9362-11e7-914d-f5a08db3ceaa.png)


@123names  to resolve this issue, you can right-click on `EXPLORER: OPEN EDITORS` and Click on `Folders` to enable the folders again (Explained in detail - see the image down below). 
![image](https://user-images.githubusercontent.com/19846657/30151180-538be10a-9363-11e7-9d0d-e297f8a30355.png)

**Comment by roblourens** [comment]
Yes thanks, and in 1.16, we've removed the ability to hide the Folders view since it's confusing. Let me know if that's not your problem @123names

**Comment by 123names** [comment]
ok, thanks
