### ISSUE TITLE
'Extension not found' when trying to install 1.16 extension in 1.15

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#33905]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

Steps to Reproduce:

1. Publish an extension depending on VSCode 1.16
2. Installing from the extensions viewlet into 1.16-insiders works fine
3. Installing from the extensions viewlet into 1.15 fails with an error 'Extension not found'

The expected behavior is to either filter extension depending on a newer version from the extensions viewlet or display an appropriate info message when trying to install such an extension.

**Comment by sandy081** [comment]
Following error is shown when a compatible version of the extension is not found to install.

![image](https://user-images.githubusercontent.com/10746682/33181058-261b4f32-d06f-11e7-92f4-24985918227e.png)

**Comment by ramya-rao-a** [comment]
How do we verify this :) ? To verify this in 1.19 Insiders we will have to publish an extension depending on 1.20 that doesnt exist :)

**Comment by mjbvz** [comment]
I tried to verify this by creating a local vsix that requires `^1.20`. This seems to install fine, it just is never actually activated and always shows `reload`:

<img width="439" alt="screen shot 2017-12-06 at 6 22 09 pm" src="https://user-images.githubusercontent.com/12821956/33695476-6e677070-dab2-11e7-8b74-8a92cd10a221.png">

**Comment by sandy081** [comment]
@ramya-rao-a I did the same for verifying this. I have some dummy extensions in market place for testing such use cases. 

To verify:

- Publish an extension that depends on VS Code >1.19
- Try to install it and verify you get a message as mentioned in [comment](https://github.com/Microsoft/vscode/issues/33905#issuecomment-346653022)

@mjbvz Good catch. We never checked the VS code version on VSIX extensions, hence they are getting installed successfully. But, while running we treat all extensions as same and do not run those whose VS Code dependency does not match. Filing a new issue for VSIX one.

Thanks.

**Comment by joaomoreno** [comment]
Verified:

![image](https://user-images.githubusercontent.com/22350/33891643-db30fb10-df56-11e7-8a58-61ce14421707.png)

@sandy081 Just tiny grammar nitpicking:

> Unable to install 'joaomoreno.banana'; there is no available version compatible with VS Code 1.19.0-insider.

**Comment by sandy081** [comment]
Thanks @joaomoreno. Updated it in masters.
