### ISSUE TITLE
Add `files.autoGuessEncoding` to specified-lang settings

### ISSUE THREAD

**Issue by fzzr-** [Microsoft/vscode#33903]
Feature request.

I think we need to make possible to use `files.autoGuessEncoding` option in the language-specific preferences.

![screen shot 2017-09-06 at 19 20 59](https://user-images.githubusercontent.com/888526/30122852-9508c920-9338-11e7-8f36-7e886379d02c.png)

**Comment by fzzr-** [comment]
@bpasero: Why issue was closed? Any commit/Pr or it was rejected? No, I don't see anything. Sorry if it's my misunderstanding.

**Comment by bpasero** [comment]
@fzzr- yeah fixed, try it out from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
**Verification:** verify you can configure auto guess encoding per file type. The auto guessing can be tested best with a file that is not using UTF-8 as encoding.
