### ISSUE TITLE
Feature Request: Powershell Documentation

### ISSUE THREAD

**Issue by cajunitalian** [Microsoft/vscode#33907]
Feature Request:

Ability to add documentation similar to how functions allow auto help file generation above function.

EX: A template we can edit and apply similar to a coded function (<#) that auto populates details at beginning of script like Author, Version, Run Details, etc.

**Comment by roblourens** [comment]
I don't quite follow the request, is this specific to Powershell? Would it be a better fit for the powershell extension?
