### ISSUE TITLE
Show confirmation for git operations like pull/push

### ISSUE THREAD

**Issue by xameeramir** [Microsoft/vscode#33909]
- VSCode Version: All
- OS Version: All

Steps to Reproduce:

1. Do git operation like pull/push
2. User gets confused if the git operation completed or not
3. The output is too verbose

Reproduces without extensions: Yes

**Comment by asphub** [comment]
It is mustly required feature...

Pls show a message after all `git` operations **_(atleast when a `git pull` operation gets completed)_**
