### ISSUE TITLE
Folding icons don't match the font size

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3390]
![image](https://cloud.githubusercontent.com/assets/6461412/13281382/d17eaba4-dae3-11e5-84a7-4d6aeb44f077.png)
![image](https://cloud.githubusercontent.com/assets/6461412/13281410/fbde0cdc-dae3-11e5-9ac1-10f1d1e65941.png)

**Comment by joaomoreno** [comment]
Good catch

**Comment by aeschli** [comment]
Same for breakpoints.
Looks like Visual Studio also doesn't grow the breakpoint and folding icons with the font size.
Users can always use the Zoom feature, which zooms everything.

**Comment by aeschli** [comment]
I removed the code that grows the folding icon gutter by font size to avoid the clipping that can bee seen in the second screenshot. We can add that again if we decide to grow the icons along with the font size

**Comment by bgashler1** [comment]
I can fix this but converting the icon sizing to ems, but it could possibly affect the pixel-perfect lines of the icon; I wouldn't be able to test it before the freeze (because my Retina screen lies to me about how other screens will alias it.  I would need my desktop).  Let's hold off until March on this one just to be safe and not compromise the icon.

**Comment by aeschli** [comment]
Makes sense. As the breakpoints also don't grow/shrink I think we are consistent.

**Comment by kumarharsh** [comment]
This is fixed now I guess.

![image](https://user-images.githubusercontent.com/760112/41161605-10af19e4-6b51-11e8-86d1-66894193a32d.png)

**Comment by misolori** [comment]
@kumarharsh this actually happens when you change `editor.fontSize`, which is different from `window.zoomLevel`

**Comment by kumarharsh** [comment]
Yup, I can see that
![image](https://user-images.githubusercontent.com/760112/45411151-1e51f180-b691-11e8-8ab3-8f01f14e4f65.png)

I was under the impression Ctrl+Zoom changed to font size 🤦‍♂️
