### ISSUE TITLE
error with typescript

### ISSUE THREAD

**Issue by gshields** [Microsoft/vscode#33913]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
jslint|ajh|1.2.1
vscode-eslint|dba|1.2.11
python|don|0.7.0
json-tools|eri|1.0.2
diff-tool|jin|0.0.1
Go|luk|0.6.65
cpptools|ms-|0.12.3
typescript-javascript-grammar|ms-|0.0.23
vshaxe|nad|1.9.1
code-spell-checker|str|1.3.9

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What is the error?
