### ISSUE TITLE
[scss] no suggestion when there is an selector line below

### ISSUE THREAD

**Issue by dimondevs** [Microsoft/vscode#33911]
- VSCode Version: Insiders
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. ![2017-09-06 22-27-18](https://user-images.githubusercontent.com/7513945/30134023-6db103ee-935e-11e7-8bf1-26a6621bb887.gif)

Good day. After fixed [https://github.com/Microsoft/vscode/issues/32703](#32703) noticed here such another bug.

**Comment by ramya-rao-a** [comment]
I can't seem to repro it. Can you share a small code sample where I can try to repro this?

![cssemmet](https://user-images.githubusercontent.com/16890566/30137229-3a742fac-9317-11e7-8eb8-c0261119955e.gif)

**Comment by dimondevs** [comment]
You initially have a margin everywhere. Try to delete all properties. and start typing before the selector &: not ()

**Comment by dimondevs** [comment]
And I'm not talking about emmet, but about the whole list of suggestions

**Comment by ramya-rao-a** [comment]
Ah! got it. Can repro now.

**Comment by aeschli** [comment]
Oh, yes, October! :-) Thanks @ramya-rao-a !
