### ISSUE TITLE
[Is it a bug?]A IntelliSense problem about es6 react componet class.

### ISSUE THREAD

**Issue by sharkrice** [Microsoft/vscode#33918]
Is it a bug?Maybe can be improved.

- VSCode Version: 1.15.1
- OS Version: win10

Steps to Reproduce:

1. create a es6 class extend react component
2. try to type "component" and then the IntelliSense suggestions will pop.It will show react compoent lifecycle functions like "componentDidMount"
3. If you create a "constructor", and then you try to type "component", the IntelliSense suggestions didn't show any react compoent lifecycle functions.

![](https://i.imgur.com/l8gkdRJ.gif)
[https://i.imgur.com/l8gkdRJ.gif](url)

I alreay disabled all extensions.
Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/17977 TypeScript powers our JavaScript and TypeScript language support
