### ISSUE TITLE
arrow key is replaced by number wrongly

### ISSUE THREAD

**Issue by liuchanchen** [Microsoft/vscode#33912]
- VSCode Version:1.15.1
- OS Version:
Ubuntu 16.04.1 LTS 

Steps to Reproduce:

1.using shortcut key to delete a line(ctr+shift+k)
2.typing the arrow key will be replaced by number(eg: 'up' changing to '8','down' changing to '2', 'left' changing to '4', 'right' changing to '6')

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@liuchanchen I am not 100% sure I understand what you mean. Do you mean you are pressing the arrow keys and you get numbers inserted? This almost looks like one would be pressing the arrow keys on a numpad with NumLock on... or something along those lines.

Are you perhaps using a remote desktoping software?

Here is a quick troubleshooting guide for linux keybindings: https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

Does any of those steps apply to you ?

**Comment by liuchanchen** [comment]
Actually,  I used hyper-v to run ubuntu and win 10 as host

**Comment by alexandrudima** [comment]
@liuchanchen Would then the very first bullet point in the troubleshooting guide help?

![image](https://user-images.githubusercontent.com/5047891/30737640-a4b5d1a0-9f87-11e7-9080-ba7677447208.png)
