### ISSUE TITLE
Feature Request: Add features of grouping multiple tasks in tasks.json and running them in sequence or parallel

### ISSUE THREAD

**Issue by wheelo** [Microsoft/vscode#33917]
Consider the **Task** in vscode works in the sharp of some kind of shell, _e.g._ sh, node, npm, gulp, I just wonder the possibility of grouping tasks and executing them in sequence and in parrallel (with the configurations in **tasks.json**). 
Say, when we run the gulp task, we can also run the jslint and mocha at the same time. Similar features can be found in framework [**AVA**](https://github.com/avajs/ava)..

**Comment by dbaeumer** [comment]
This is already possible. See the following tasks.json as an example:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"taskName": "compile",
			"dependsOn": [
				"compile:client",
				"compile:server"
			],
			"problemMatcher": []
		},
		{
			"label": "compile:client",
			"type": "npm",
			"script": "compile:client",
			"group": "build",
			"presentation": {
				"panel": "dedicated",
				"reveal": "never"
			},
			"problemMatcher": [
				"$tsc"
			]
		},
		{
			"label": "compile:server",
			"type": "npm",
			"script": "compile:server",
			"group": "build",
			"presentation": {
				"panel": "dedicated",
				"reveal": "never"
			},
			"problemMatcher": [
				"$tsc"
			]
		},
		{
			"taskName": "watch",
			"dependsOn": [
				"watch:client",
				"watch:server"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": []
		},
		{
			"label": "watch:client",
			"type": "npm",
			"script": "watch:client",
			"isBackground": true,
			"group": "build",
			"presentation": {
				"panel": "dedicated",
				"reveal": "never"
			},
			"problemMatcher": [
				"$tsc-watch"
			]
		},
		{
			"label": "watch:server",
			"type": "npm",
			"script": "watch:server",
			"isBackground": true,
			"group": "build",
			"presentation": {
				"panel": "dedicated",
				"reveal": "never"
			},
			"problemMatcher": [
				"$tsc-watch"
			]
		}
	]
}
```

If you want to run them in sequence you currently need to sequence the single tasks. I have a feature request to support something like && and || as in package.json

**Comment by pinguo-pengxiaolong** [comment]
Great job! @dbaeumer. I must try it right now

**Comment by pinguo-pengxiaolong** [comment]
@dbaeumer Which PR is about this? 
> If you want to run them in sequence you currently need to sequence the single tasks. I have a feature request to support something like && and || as in package.json

**Comment by lerit** [comment]
i also want multiple tasks run in parallel
