### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by bowencool** [Microsoft/vscode#33914]
当终端没有焦点时，按下终端快捷键应该是获取焦点，而不是折叠

**Comment by llity** [comment]
哈哈

**Comment by dongrizhixue** [comment]
上次我提了一个issues，结果他们竟然看懂了，不过翻译起来有点差

**Comment by NewFuture** [comment]
<kbd>ctrl</kbd> + <kbd>\`</kbd> + <kbd>\`</kbd>

**Comment by roblourens** [comment]
> When the terminal has no focus, pressing the terminal shortcut key should be the focus, not the fold

Sorry, I don't understand the suggestion

**Comment by yume-chan** [comment]
@roblourens Translation:

> # Suggestions for improvement
> When the integrated terminal doesn't have focus (but shown, I think), press shortcut for "Toggle Integrated Terminal" should focus it but not hide it.

----

I found a solution: Add the following keybinding:

```` json
{
    "key": "ctrl+`",
    "command": "workbench.action.terminal.focus",
    "when": "!terminalFocus"
}
````

**Comment by roblourens** [comment]
Fixing this with a keybinding is the correct solution. Thanks @yume-chan
