### ISSUE TITLE
Code helper takes up more than 100% of CPU 

### ISSUE THREAD

**Issue by modarend** [Microsoft/vscode#33920]
![jietu20170907-103418](https://user-images.githubusercontent.com/25577631/30143390-20697792-93b8-11e7-9482-eec29dac4f45.png)
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: mac 10.12.6
- Extensions: the listing length exceeds browsers' URL characters limit
---
![image](https://user-images.githubusercontent.com/25577631/30143412-359ff320-93b8-11e7-8e74-4cab410a0858.png)
![image](https://user-images.githubusercontent.com/25577631/30143454-6dd0a8e8-93b8-11e7-8721-47c5d3e980ce.png)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you run this to help us figure out which process it is? `ps -eo pcpu,user,pid,command | grep Code`

And can you start with `--disable-extensions` to see whether an extension is causing this?
