### ISSUE TITLE
Closing tag isn't highlighting in some cases 

### ISSUE THREAD

**Issue by sakhisheikh** [Microsoft/vscode#33925]
VSCode Version: Code 1.15.1 (41abd21, 2017-08-16T17:15:57.756Z)
OS Version: Windows 10 Pro 1703 OS build 15063.540
Extensions: none

html-file-link: https://github.com/sakhisheikh/fb-mockup/blob/master/index.html

![git1](https://user-images.githubusercontent.com/18448824/30150855-7bc0ab5c-93c6-11e7-892c-2c8ba2383360.PNG)

![git2](https://user-images.githubusercontent.com/18448824/30152007-2271608c-93cb-11e7-9eec-386249376ddf.PNG)

**Comment by iMahesh** [comment]
@sakhisheikh You have an unopened `</iframe>` tag at line `479`  remove that closing iframe tag and try it. it's just a typo in your code. I guess I have solved your issue.
![image](https://user-images.githubusercontent.com/19846657/30151994-82cad3ec-9366-11e7-8688-b0a0fadc339c.png)

**Comment by sakhisheikh** [comment]
@iMahesh greatly surprised how did you quickly scrutinize the issue .  It was quite arduous for me. 
Following.

**Comment by farhanm612** [comment]
@sakhisheikh "greatly surprised how did you quickly scrutinize the issue . It was quite arduous for me." pata hai GRE ki tiyari chal rahi hai donday
