### ISSUE TITLE
wrap line not work

### ISSUE THREAD

**Issue by yanite** [Microsoft/vscode#33924]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. push Alt+z wrap line no work
2.

**Comment by iMahesh** [comment]
@yanite I don't see the binding for `Alt+[` in keybindings.json.
Seems like it's been replaced with `ctrl+shift+[` 
The only assignments related to `[` are in the picture below. 
![image](https://user-images.githubusercontent.com/19846657/30150375-fef1db66-935f-11e7-8505-67906f899be0.png)

I guess you can reassign the key-mapping to `alt+[` if you got used to it.

**Comment by alexandrudima** [comment]
@yanite Line wrapping is disabled in the following circumstances:
* when inside a diff editor
* when opening a very large file
* when having a screen reader attached (visible in the status bar with "Screen Reader Detected" which replaces the current line,col information)

Which one of these cases are you running into? Or is there another case ?
