### ISSUE TITLE
Search & Replace: diff editor becomes weird after replacing all

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33927]
Steps to Reproduce:

1. search for something
2. enter a replace text
3. open a diff editor for a change
4. click on replace all in the viewlet

=> the diff editor's right hand side becomes empty
=> click on another editor and then back, now both sides are empty

Should we just close the diff editor after replace all?

**Comment by sandy081** [comment]
I think the right solution is to show left and right side with same content. This is what we do when we undo or stage a change.

**Comment by sandy081** [comment]
It's got fixed already. Diff editor is closed after replace all.
