### ISSUE TITLE
ColorPicker Inaccessible

### ISSUE THREAD

**Issue by fzed51** [Microsoft/vscode#33928]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
Bookmarks|ale|0.16.0
vscode-twig-pack|baj|1.0.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
python|don|0.7.0
xml|Dot|1.9.2
EditorConfig|Edi|0.10.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
beautify|Hoo|1.1.1
composer|ika|0.5.0
Go|luk|0.6.65
vscode-apache|mrm|1.1.1
PowerShell|ms-|1.4.2
debugger-for-chrome|msj|3.2.1
php-docblocker|nei|1.2.0
vscode-icons|rob|7.12.0
twig|wha|1.0.2

---

Steps to Reproduce:

When I come over a color at the end of a long line, the ColorPicker appears at the beginning of the line. I can not access it, because as soon as I leave the color the colrpicker disappears.

![image](https://user-images.githubusercontent.com/1201984/30152618-ef44196e-93b3-11e7-81f7-69d7b45b81e0.png)

Reproduces without extensions: Yes/No

**Comment by Miyan0** [comment]
Same issue with macOs Sierra (10.12.6)

**Comment by rebornix** [comment]
Thank you for reporting, dup of https://github.com/Microsoft/vscode/issues/32443
