### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Afatkharrofiqi** [Microsoft/vscode#33923]
Pls add this features, 
1. list all methods, so we can find method quickly by clicking on the list, like netbeans 👍

**Comment by yume-chan** [comment]
Is `Go to Symbols in file` (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>) your want?

**Comment by Afatkharrofiqi** [comment]
Oh yes thank you, like what i want 👍
