### ISSUE TITLE
Double character $$ on php suggestions

### ISSUE THREAD

**Issue by arismanwebs** [Microsoft/vscode#33937]
Since 1.15 version i have a problem with autocomplete suggestions in PHP. When i press enter key to use any suggestion in a PHP var, VScode put two dolar character.

![but](https://user-images.githubusercontent.com/24960688/30159969-bffbb2ea-93ca-11e7-8ca2-8afeeef509f6.jpg)

**Comment by roblourens** [comment]
Can you try starting Code with `--disable-extensions`, to check whether this is due to an extension?

And can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders
