### ISSUE TITLE
Improve git implementation

### ISSUE THREAD

**Issue by hpohlmeyer** [Microsoft/vscode#33936]
The current git integration in VSCode has a couple flaws (most notably #9475) and could be improved.

I think Atom does a really good job with its git integration and would suggest something similar.
The main benefits (in my opinion):

__Not side-by-side__  
If you select lines individually, you know exactly which lines will be staged, because line x does not exist twice.

__Buttons not hidden__  
If you want to stage a selection, you have to go through the drop-down in VSCode, which is one more step and takes a lot longer, even if this is a very common interaction.

__Selection of single lines__  
As noted in #9475, this is currently not possible. A click next to a line should select exactly the selected line and not expand to any other line.

__Hunks__  
Nice to quickly scan the code and commit code blocks.

Here is a screenshot of Atoms git integration:
![screen shot 2017-09-07 at 12 06 37](https://user-images.githubusercontent.com/6564077/30158936-36caf10a-93c7-11e7-9766-8203e9fc9de6.png)

**Comment by danawoodman** [comment]
Re "Not side-by-side": I think this is personal preference. I like side-by-side. That said, Having both could be nice but is more maintenance.

**Comment by joaomoreno** [comment]
We now have the gutter decorations which improve this flow and target the hunks. Inline diff is also supported in the diff editor. Line staging is tracked in #9475. Buttons are tracked in #26067.
