### ISSUE TITLE
formatOnType: true breaks newline indentation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3393]
* have `formatOnType: true`
* pressing enter on the end of the line does not indent the next line properly, it is not indented at all
* I can repro for both TS and JS

Simple snippet to repro. Pressing enter on end of first line I would expect to get indentation
```
function f() {
};
```

Works for our insider build so it seems like it is a regression -> important

fyi @alexandrudima @dbaeumer

**Comment by joaomoreno** [comment]
Duplicate of #2907...
