### ISSUE TITLE
Picking a process ID for attaching with the GDB debugger is not possible anymore

### ISSUE THREAD

**Issue by Lichtbogen** [Microsoft/vscode#33938]
- VSCode Version: 1.15.1
- OS Version: Windows 7 Enterprise 6.1 (Build 7601: Service Pack 1)

I use the following launch.json configuration:

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Attach",
      "type": "cppdbg",
      "request": "attach",
      "program": "C:/02_tools/00_executables/BT_RTSIM.exe",
      "args": [],
      "stopAtEntry": false,
      "processId": "${command.pickProcess}",
      "cwd": "${workspaceRoot}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "c:/MinGW/bin/gdb.exe",
      "setupCommands": [
          {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
          }
      ]
    }
  ]
}

With version 1.12.2 it works as expected and I can select the process for connecting with the Debugger.:
![2c9e2bf](https://user-images.githubusercontent.com/26296473/30162141-d8a7215e-93d3-11e7-822c-2b027a202261.PNG)

Since version 1.15.0 I get the following error message: 

![process_picker](https://user-images.githubusercontent.com/26296473/30162237-4d480208-93d4-11e7-9d25-69e6e0f261da.png)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please file this against the VSCode c++ extension https://github.com/Microsoft/vscode-cpptools
