### ISSUE TITLE
Sencha Ext JS activation failed

### ISSUE THREAD

**Issue by JCarlos12** [Microsoft/vscode#33930]
- VSCode Version: 1.15.1
- OS Version: Windows 7
I'm trying to activate my Sencha Ext JS extension.

![image](https://user-images.githubusercontent.com/11145777/30153432-32101a2e-93e9-11e7-851a-67db35c75aae.png)

First I tried "Activate License" and it prompted me to enter my email address but I never received an email.

So I tried "Start Trial" But it gave me an error. So I checked its logs and it gave me this

> 2017-09-07T08:26:15.249Z - info: attempting to activate license initializing=false, email=jc-cabotaje@ti.com, name=Visual Studio Code Extension, version=1, fullVersion=1.0.1, productVersion=1, short=Visual Studio Code Extension, code=vsc, id=1ceef72d-216c-42f3-9ab0-316563ceb8e9, $ref=$["license"]["$config"]["data"], domain=null, , _eventsCount=0, _maxListeners=0, initialized=true, initializing=false, $config=undefined, domain=null, , _eventsCount=0, _maxListeners=0, _licenses=[], app.name=Sencha Visual Studio Code Extension, app.shortName=VSCode, app.version=1.0.1, app.build.date=2016-08-18, _parent=null, appName=Sencha Visual Studio Code Extension, appShortName=VSCode, appVer=1.0.1, appMajorVer=1, licensePath=C:\Users\x0247950\.sencha\VSCode\1\license.json, initialized=true, email=jc-cabotaje@ti.com
2017-09-07T08:26:16.029Z - info:  Error: getaddrinfo ENOTFOUND api.sencha.com api.sencha.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
2017-09-07T08:26:16.030Z - info: An error occurred while attempting to activate a license Error: getaddrinfo ENOTFOUND api.sencha.com api.sencha.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Please I really have no idea why
I can successfully install extensions btw

**Comment by roblourens** [comment]
Sounds like there is a problem with that extension - please file an issue on their repo.
