### ISSUE TITLE
从侧边栏中删除的文件夹无法再次打开

### ISSUE THREAD

**Issue by ca3tie1** [Microsoft/vscode#33932]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Please try updating to 1.16, we removed the ability to hide the Folders view. (You can also restore it by right clicking on the "Explorer" title)
