### ISSUE TITLE
terminal line broken

### ISSUE THREAD

**Issue by swkwon** [Microsoft/vscode#33934]
- VSCode Version: 1.15.1
- OS Version: Microsoft Windows [Version 10.0.15063] language: ko

Steps to Reproduce:

1. If I input command "dir" on terminal (cmd.exe or powershell.exe)
2. Output line is broken.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Please provide a screenshot of vscode and what you expect (launch cmd.exe window and run same command).

**Comment by swkwon** [comment]
I did windows update and it solved. I am sorry. I have no screenshot.

**Comment by Tyriar** [comment]
Good to hear 😃, there were some problems with a past Windows version so I'll assume it was that.
