### ISSUE TITLE
Extra indentation of def when prefixed with "private"

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#33939]
- VSCode Version: 1.15.0
- OS Version: Manjaro KDE Gellivara

Steps to Reproduce:

1. Open a ruby file.
2. Ensure `autoIndent` is enabled.
3. Write some function with indentation (by example, inside a class), then try to write end keyword

Reproduces without extensions: Yes

![Imgur](https://i.imgur.com/wY66iNe.gif)

![Imgur](https://i.imgur.com/bVYcuZo.gif)

This happen by default in vscode, but other extensions like vscode-ruby and vscode-crystal-lang also have this issue:

- https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/18
- https://github.com/rubyide/vscode-ruby/issues/203

**Comment by alexandrudima** [comment]
The root cause for this lies within the indentation rules defined for ruby at

https://github.com/Microsoft/vscode/blob/128a4e3640c5375f7b0bc1cfd37f626481b1386f/extensions/ruby/language-configuration.json#L25

I am not really sure how these should be changed to address the problem.

**Comment by faustinoaq** [comment]
Hi @rebornix @alexandrudima I did some indentation rules by myself:

I created it for [Crystal](https://crystal-lang.org) but is almost the same for Elixir, Ruby, Julia and other similar languages. In fact, currently [I'm using Ruby indentation rules for Crystal](https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/18#issuecomment-327778124)

```
indentationRules: {
    // /^[^#]*(
    //       ((
    //         ((if|elsif|lib|fun|module|struct|class|def|macro|do|rescue)\s)|
    //         (end\.)
    //       ).*)|
    //       ((begin|else|ensure|do|rescue)\b)
    //     )
    // $/
    increaseIndentPattern: /^[^#]*(((((if|elsif|lib|fun|module|struct|class|def|macro|do|rescue)\s)|(end\.)).*)|((begin|else|ensure|do|rescue)\b))$/,
    // /^\s*(
    //        ((rescue|ensure|else)\b)|
    //        (elsif\s.*)|
    //        (end(\..*|\b))
    //      )
    // $/
    decreaseIndentPattern: /^\s*(((rescue|ensure|else)\b)|(elsif\s.*)|(end(\..*|\b)))$/
}
```

It's working a quite well now, but `case` statement has a new problem with `end` keyword.

![ezgif-3-d16738dbc4](https://user-images.githubusercontent.com/3067335/30511858-88e29038-9aa7-11e7-8694-cae9df693b30.gif)

**Comment by faustinoaq** [comment]
Oh, good news @juicemia did a fix for vscode-ruby here :point_right: https://github.com/rubyide/vscode-ruby/pull/206

it was easier than I thought :sweat_smile:

**Comment by alexandrudima** [comment]
Thank you @faustinoaq
