### ISSUE TITLE
Pseudo localization doesn't seem to work in extension development

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3394]
Testing #3156

I've added the `"--locale=pseudo"` argument to the `args` of the debug launch task.

![image](https://cloud.githubusercontent.com/assets/22350/13282700/8ee5b83a-daea-11e5-83ab-f1fb5bb9d276.png)

**Comment by dbaeumer** [comment]
Need to investigate. But could be an issue with command line args. There is nothing I do special with --locale.

**Comment by dbaeumer** [comment]
Currently the locale parameter is only respected once per VSCode main process. The reason for this that the main process already controls parts of the UI (e.g. menu bar, some dialogs, ...). Honoring the locale in a browser process would result in a mixed user interface (like in the screen shot). So in the current build none of the strings are run through pseudo in this setup meaning that the menu bar, the open dialog shows normal strings.

**Comment by dbaeumer** [comment]
@joaomoreno pls close as verified if you accept the reason.
