### ISSUE TITLE
 Description to be localized in package.json doesn't fall back to English if text not in package.nls.*.json

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode#33949]
I have a description with %[description]% format in package.json and I have all the texts in package.nls.json.  so for English everything works but for other language, if the text not in package.nls.*.json, the description shows the key %[description]%, not the English one. Is that by design?

**Comment by dbaeumer** [comment]
Yes, this is by design to avoid lookups during runtime.

We fill in the default values (e.g. English, but it follows the language lookup rules) when we import the strings into our system from the translation database.
