### ISSUE TITLE
Wrong result in Node debug console

### ISSUE THREAD

**Issue by GregorBiswanger** [Microsoft/vscode#33940]
- VSCode Version: 1.15.1
- Local Node v.8.1.1 
- OS Version: Windows 10

Steps to Reproduce:

1. The following Code:
var numberA = 10 / "zero";
console.log(numberA); 
2. Execute Node.js Debug - In debug console is the output: **undefined**
    But the correct answer is: **NaN**.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This is coming from the node debug extension, forwaring to @roblourens

**Comment by roblourens** [comment]
This looks like an issue that I fixed recently. Please try in the Insiders build (or in the 1.16 release which is about to go out)
