### ISSUE TITLE
SCSS: "content" is not scoped correctly

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#33945]
- VSCode Version: Code - Insiders 1.16.0-insider (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-05T20:47:12.741Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.20.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.29.0
ayu|tea|0.6.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. when using the css "content" property, it is not scoped for theming as `support.type.property-name.css` like all the other property names.  It is incorrectly labeled as `entity.name.tag.css`.

<img width="323" alt="screen shot 2017-09-07 at 10 53 37 am" src="https://user-images.githubusercontent.com/835148/30169725-3d67abe0-93bb-11e7-817c-3644052b6a20.png">

**Comment by aeschli** [comment]
@smlombardi Please always paste your sample code as well. 

Reproduced with
```
&::after {
    content: 'FPO';
    font-family: system-ui;
}
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#233
