### ISSUE TITLE
Feature Request: Add Live Preview feature for Web development

### ISSUE THREAD

**Issue by jihadnaji** [Microsoft/vscode#33946]

**Comment by kevinrambaud** [comment]
Well, there are already a bunch of extensions doing what you are looking for such as https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer if you want more I guess you can search directly there https://marketplace.visualstudio.com/search?term=live%20preview&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by jihadnaji** [comment]
Well, i didn't know that because I'm new to VS Code, that's great thanks for letting me know of these extensions.
null
