### ISSUE TITLE
Julia right click "Run Code" returns an error

### ISSUE THREAD

**Issue by dondotson** [Microsoft/vscode#33957]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
syntax-julia|be5|0.0.4
code-runner|for|0.7.1
language-julia|jul|0.7.0
linter-gfortran|krv|0.5.2

---

Steps to Reproduce:

1. Place cursor next to Julia code to run.
2. Right click mouse and select "Run Code" option
3. Get error message "'julia' is not recognized as an internal or external command, operable program or batch file."

Reproduces without extensions: Yes/No  Yes
[sphere_vol.txt](https://github.com/Microsoft/vscode/files/1285917/sphere_vol.txt)
![capture](https://user-images.githubusercontent.com/31744787/30182069-203e1c46-93db-11e7-822b-5f2586623268.PNG)

**Comment by roblourens** [comment]
It looks like this is an issue with one of your extensions. Can you file an issue against the extension responsible for the "Run Code" option? Thanks.
