### ISSUE TITLE
"workbench.colorCustomizations"  -->  "tab.activeBorder" fixes the first entered value

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33956]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

Here we got an update and ...

![image](https://user-images.githubusercontent.com/24613274/30180229-d7d45c08-9417-11e7-85e8-a8bbf39fdfd8.png)

so I decided to test it and entered "#f00" in the value, so the border-bottom became red... and now this value bound to `"tab.activeBorder"`  by default :)

![tab activeborder](https://user-images.githubusercontent.com/24613274/30180162-a28885f6-9417-11e7-975e-ce88bbe74d44.gif)

even reload of VS Code - doesn't help

PS: or is that made by-design?

**Comment by roblourens** [comment]
`""` or `"#"` is an invalid entry, so I think the behavior is undefined.

**Comment by aeschli** [comment]
Yes, we show red for invalid values. There are also squigglies and and problem marker.
