### ISSUE TITLE
Language Server are not run in debug mode when debugging

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#33951]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.0
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
prettier-vscode|esb|0.23.1
debugger-for-chrome|msj|3.2.1
vetur|oct|0.9.5
vim|vsc|0.10.0

(1 theme extensions excluded)

---

1. Clone https://github.com/vuejs/vetur
2. Run `yarn` at `/`, `/server`, `/client`
3. Run `yarn watch` at `/server`
4. Debug using the compound debug target, `all`. Does not activate extension correctly. Error says 

    ![image](https://user-images.githubusercontent.com/4033249/30177543-0559bf68-93bb-11e7-8d28-54d3bcb038e9.png). Vue Language Server is not started at all.

5. Debug using the `client` target only. Launches VSCode and Vue Language Server correctly. However, the option being used is `run` instead of `debug` for `ServerOptions`: https://github.com/Microsoft/vscode-languageserver-node/blob/b0b7ebd59f935338f3023f747ca8e75e91f15018/client/src/main.ts#L69

    ![image](https://user-images.githubusercontent.com/4033249/30177682-6e7a11aa-93bb-11e7-86c7-325cf44fcce9.png)
    In last version, `debugServerModule` would be run when debugging. Now it's running `serverModule` when debugging.

@weinand @dbaeumer

**Comment by weinand** [comment]
Make sure that language server is launched into debug mode via the `--inspect` flag instead of `--debug`. VS Code's builtin node no longer support "legacy" mode.

**Comment by weinand** [comment]
@dbaeumer we should add a note about this to the new "[Upgraded Electron](https://code.visualstudio.com/updates/v1_16#_upgraded-electron-only-supports-inspector-protocol)" section in the release notes since this affects the language server client library.

**Comment by octref** [comment]
OK. Was scamming through release notes and also doing a Cmd+F for `--debug` but didn't find anything so I opened the issue.

**Comment by octref** [comment]
@weinand Nope, `--inspect` didn't help. The thing is `run` is being used instead of `debug` when init'ing the server.

https://github.com/vuejs/vetur/blob/master/client/src/htmlMain.ts#L19-L20

**Comment by octref** [comment]
Here you see, it's picking up the `run` config instead of the `debug` config, when I'm running it in debug mode.

For Vetur
- `run` config runs `client/node_modules/vue-language-server/dist/vueServerMain.js`
- `debug` config runs `server/dist/vueServerMain.js`

![err](https://user-images.githubusercontent.com/4033249/30190415-d5a30d54-93ee-11e7-83c8-05edd38c8ed1.gif)

**Comment by AHaberl** [comment]
I have the exact same issue as @octref

**Comment by dbaeumer** [comment]
This got addressed with the latest version of the LSP npm modules. Upgrade to version 3.4.x and debugging will work again.

**Comment by octref** [comment]
Thanks! client / server works fine now, but compound doesn't work still. I'll open another issue for it.

**Comment by octref** [comment]
@dbaeumer When debugging, no matter which extension you are debugging, it seems all LS are run in debug mode. Is that as designed?

In Vetur when developing, we build to `/server` and point to `/server/dist/vueServerMain.js`. In normal usage, the LS is at `/client/node_modules`.
Now it seems whichever extension I'm debugging, if I open a Vue file, Vetur would crash since it's trying to access `/server` which doesn't exist in the distribution.

**Comment by dbaeumer** [comment]
This depends on the setup of the LSP client. If you specify debug options in our server options and the extension host is running in debug mode then the server is started using the server debug options. I all leave them in yes then all are started in debug mode. If they don't use the same port I don't see why that would hurt.

**Comment by octref** [comment]
@dbaeumer For Vetur, when `run` we use the published https://www.npmjs.com/package/vue-language-server, when `debug` we point to a local dev version of the server.

We don't bundle the local dev version with distribution. So Vetur would crash if normal users access Vue files while debugging other non-Vetur extensions.

I would expect the LS / LS Client to be started in debug mode only if the user is debugging exactly that LS extension.

**Comment by dbaeumer** [comment]
@octref but this is nothing the LSP knows. Even the extension host doesn't know this. I rechecked and there is no information about which extension is the launch source on the command line for the extension host.
