### ISSUE TITLE
CodeLensContribution causes scrolling jump when rift view is centered in editor.

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#33952]
- VSCode Version: code-oss-dev 1.17.0 (9a06ffca7835df3677e7219dd983382baeaa0ea7, Date unknown)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
vscode-eslint|dba|1.2.11
python|don|0.7.0
gitlens|eam|4.4.3
tslint|eg2|0.17.0
git-tree-compare|let|1.1.0
Go|luk|0.6.65
node-debug2|ms-|1.14.5
debugger-for-chrome|msj|3.2.1
sourcegraph|sou|1.0.9
vim|vsc|0.10.0
---

Reproduces without extensions: No

Steps to Reproduce:

1. Have an extension installed that registers a CodeLensProvider (e.g. gitlens)
2. Open VS Code to a file (e.g. codelensController.ts) and scroll (make sure you have scrolled a non-zero amount) to a symbol in the middle of the file.
4. Right click on a symbol and "find references".
5. Adjust your window size and scroll position so the references peek view is in the middle of the screen and takes up most of the vertical height.
6. Close and reopen vscode (or refresh it if running `./scripts/code.sh`) 
7. Immediately right click on the same symbol and find references. (i.e. before code lens has resolved).

After the references returns, you will see the scroll position jump because CodeLensContribution tries to restore the center range:

https://github.com/Microsoft/vscode/blob/9a06ffca7835df3677e7219dd983382baeaa0ea7/src/vs/editor/contrib/codelens/browser/codelensController.ts#L256-L258

The problem is that the references rift view is actually in the center of the viewport, so the "center" line that CodeLensProvider saves to restore is actually the line after the rift view. Centering that line causes the rift view to scroll up off the screen (unexpected).

![screen recording 2017-09-07 at 11 17 am](https://user-images.githubusercontent.com/754768/30178566-3f03e268-93be-11e7-8d73-b41047f7568e.gif)

The following diff is helpful for debugging
```diff
diff --git a/src/vs/editor/contrib/codelens/browser/codelensController.ts b/src/vs/editor/contrib/codelens/browser/codelensController.ts
index ac409e2a56..2c06adac0b 100644
--- a/src/vs/editor/contrib/codelens/browser/codelensController.ts
+++ b/src/vs/editor/contrib/codelens/browser/codelensController.ts
@@ -254,7 +254,10 @@ export class CodeLensContribution implements editorCommon.IEditorContribution {
 			});
 		});
 		if (shouldRestoreCenteredRange) {
+			console.warn('revealRangeInCenter', centeredRange);
 			this._editor.revealRangeInCenter(centeredRange, editorCommon.ScrollType.Immediate);
+		} else {
+			console.log('not revealing range');
 		}
 	}
 

```

The ideal solution would be to adjust the scroll position by exactly the amount of content that was added by the code lenses.

**Comment by alexandrudima** [comment]
I think you are suggesting we keep the first line in the viewport constant rather than the centered line in the viewport, as in the case of the reference search the centered line in the viewport is the one after the reference search...

**Comment by nicksnyder** [comment]
Correct.

**Comment by roblourens** [comment]
Or, maintain the line with the cursor, suggested in https://github.com/Microsoft/vscode/issues/38257

**Comment by nicksnyder** [comment]
Maintaining cursor position also sounds like a reasonable solution.

**Comment by alexandrudima** [comment]
Done via 7a3204ce57da60afba584629a801c897608329e1, which keeps the first line of the viewport stable and not the centered one
