### ISSUE TITLE
Suggest widget: Deleting characters sometimes does not highlight matches

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3395]
Related to #3237

* Open any ts file
* type 'aa' get suggest widget (first picture), type another 'a' and then delete it (second picture)
* notice that 'a' are not highlighted in the second picture

<img width="256" alt="screen shot 2016-02-24 at 11 35 12" src="https://cloud.githubusercontent.com/assets/1926584/13282736/b37d78a4-daea-11e5-90e8-e721ac28a01c.png">
<img width="338" alt="screen shot 2016-02-24 at 11 35 57" src="https://cloud.githubusercontent.com/assets/1926584/13282750/cb169176-daea-11e5-9de0-46ecce5ae164.png">

**Comment by joaomoreno** [comment]
Suggest to move this to March, I want to clean up the suggest model.

**Comment by isidorn** [comment]
:+1:
