### ISSUE TITLE
Problem debugging extensions after upgrading to 1.16.0

### ISSUE THREAD

**Issue by emackey** [Microsoft/vscode#33958]
- VSCode Version: 1.16.0 (just released)
- OS Version: Windows 7

Steps to Reproduce:

1. Create a new extension with `yo code` accepting all the defaults (name it anything you like).
2. Press F5 to launch your new extension into the debugger.
3. After 10 seconds, the debugger fails to connect.  A message appears at the top of the parent VSCode instance:

> Error: Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {

I tried upgrading NodeJS to v8.4.0, but no luck.  `package.json` and `.vscode/launch.json` just have the standard output from `yo code` in them.

**Comment by emackey** [comment]
Debugging of extensions was working for me up until I upgraded to the September release of VSCode (1.16.0), at which point it broke for all extensions.  There's some chance it could be my corporate network, but, it was clearly tied to the release as I had been happily debugging earlier in the day.  It's a show-stopper for me now.

**Comment by weinand** [comment]
@emackey I cannot reproduce your problem. What I did:
- installed latest VS Code (stable, 64 bit)
- installed latest yeoman and "code" generator: `npm install -g yo generator-code`
- create typescript version of "hello" extension: `yo code`
- opened with VS Code:
  ```
      cd hello
      code .
  ``` 
- set breakpoints in line 12 and 21 in extension.ts
- F5
- in extension host I pressed "F1" and then "hello" 

First breakpoint was hit.

I suggest that you try again after restarting Windows 7

**Comment by emackey** [comment]
Thanks for trying.  Guess it's my machine or my network.  I'll try re-installing from scratch.

I did manage to get the full text of that error message from the console, reproduced below in case others are searching for something similar.

```
Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10968/f7b7432a-6d44-46fb-a1b4-72b0112bb59c",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "f7b7432a-6d44-46fb-a1b4-72b0112bb59c",
  "title": "f�u(",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:10968/f7b7432a-6d44-46fb-a1b4-72b0112bb59c"
} ]

).
```

**Comment by emackey** [comment]
Re-installing from scratch fixed it!  Also, turns out I had been auto-upgraded to the 32-bit version of 1.16.0, but when I re-installed I took the 64-bit version of 1.16.0, not sure if that made any difference.  Anyway it's working fine now.

**Comment by weinand** [comment]
@emackey glad to hear that you could fix this issue. Thanks!

**Comment by pajoma** [comment]
Reinstalling the 64-bit version solved this (really annoying) issue for me as well.
