### ISSUE TITLE
Clarify documentation on "engines" field in package.json

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#33959]
The [docs](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) say for `engines`:
> An object containing at least the vscode key matching the versions of VS Code that the extension is compatible with. Cannot be *. For example: ^0.10.5 indicates compatibility with a minimum VS Code version of 0.10.5.

It's not clear to me what happens when you publish an update with an engines constraint that targets the next Code version (currently Insiders). That is, will this update be invisible for regular non-insider users and only the insider users will see it? The other scenario would be that non-insider users would see an update that they can't install.

Also, is it possible to release updates on two different streams, e.g. let's say 1.2.3 is the current non-insiders release to which I can publish updates like 1.2.4 while at the same time releasing a 1.3.0 version targeting insiders, again with updates for it, like 1.3.1.

I assume it all just works out but documenting that somewhere would help.

**Comment by letmaik** [comment]
.... just found it: https://code.visualstudio.com/docs/extensions/publish-extension#_visual-studio-code-compatibility

So maybe add a link to that page from the `engines` docs.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1165
