### ISSUE TITLE
Can't install `code-oss` in PATH

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#33969]
I was trying to set-up Code in order to submit a PR for #33106, for which I need to have the `code-oss` command installed, but after running the command for installing it I get a message saying "This command is not available".

Maybe it's unrelated, but if I run `code --help` from `Code - OSS`'s terminal I get a "Cannot read property 'indexOf' of undefined", it works when executed in a regular terminal.

Did I miss something?

Steps to Reproduce:

1. git clone https://github.com/microsoft/vscode
2. cd vscode
3. ./scripts/npm.sh install
4. npm run watch
5. ./scripts/code.sh
6. Execute the `Install code-oss` command

- VSCode Version: code-oss-dev 1.17.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 17.0.0
- Extensions: none

**Comment by joaomoreno** [comment]
The equivalent of the `code-oss` command can be found in `scripts/code-cli.sh`. Can you try creating a symlink from somewhere in your `PATH` to that file? That should just work. :+1:

**Comment by fabiospampinato** [comment]
Executing `code-cli.sh` directly works.

I've tried symlinking it to `/usr/local/bin/code-oss`, but then the script itself sets the `ROOT` variable to `/usr/local` instead of the path where my vscode clone is.

For the time being I've defined a `code-oss` alias for executing `code-cli.sh` directly, but it doesn't look like an optimal solution.

**Comment by fabiospampinato** [comment]
Btw it looks like I cannot execute the `Install code-oss in PATH` command because the `bin/code` path, which I guess gets created when packaging the app, is non existent. Perhaps we should symlink `scripts/code-cli.(bat|sh)` instead in this case.

**Comment by joaomoreno** [comment]
I don't think that will be very useful, especially since devs can have many copies of VS Code in their system. `Install code-oss in PATH` is really a command dedicated for the shippable product only, not dev.

We should probably remove those actions from dev.

The `code-oss` alias is a great solution, btw, is there something that doesn't work with it?

**Comment by fabiospampinato** [comment]
> The code-oss alias is a great solution, btw, is there something that doesn't work with it?

No I don't think so.
