### ISSUE TITLE
Intellisense broken for index.js ommited ES6 imports

### ISSUE THREAD

**Issue by alexmdodge** [Microsoft/vscode#33964]
- VSCode Version: Version 1.15.1
- OS Version: Mac OSX Sierra 10.12.4

Steps to Reproduce:

1. Create a basic project structure as follows,

```
Sample
├── components
│   ├── index.js
│   └── module.js
├── jsconfig.json
└── test.js
```

Included `jsconfig.json` is,
```json
{
  "compilerOptions": {
      "module": "es6"
  }
}
```
2. Export some object from `module.js` as default,

```js
const Module = {
   PROP: 'prop'
}
export default Module;
```
3. In component `index.js`, export `Module`,

```js
export {default as Module} from './module.js';
```
4. In `test.js` attempt to import `Module`, and intellisense only works if index included in path.

```js
import { Module } from './components';

// No intellisense here
Module.PROP
```

5. Screen shots
<img width="680" alt="intellisense" src="https://user-images.githubusercontent.com/13264599/30185579-6b3c8904-93f8-11e7-8a67-a01f0ff48d33.png">
<img width="713" alt="no-intellisense" src="https://user-images.githubusercontent.com/13264599/30185580-6b3d52f8-93f8-11e7-8d9a-d2e240205dcb.png">

I'm assuming this may be related to the fact that intellisense could also interpret `./component` to be a file without an extension, ex. `./component.js`

### Context
We're building a large application with many subdirectories of components. Gives way to better organizing and cleaning up import syntax within files.

Reproduces without extensions: **Yes**

**Comment by mjbvz** [comment]
I don't think that es6 modules support automatically picking the `index.js` when you point to a directory. Try setting:

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs"
    }
}
```

This fixed the example for me. Let me know if this does not work

**Comment by alexmdodge** [comment]
@mjbvz That in combination with setting the `baseUrl` property did the trick (we have non-relative imports as well)! Thank you very much, could not seem to find that combination of properties described in the docs.

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "baseUrl": "./"
    }
}
```
