### ISSUE TITLE
"editor.lineHeight" description unclear

### ISSUE THREAD

**Issue by smtnsk** [Microsoft/vscode#33968]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
---
Steps to Reproduce:

1. Change "editor.lineHeight" to any value >= 0.5
2. Save settings

Reproduces without extensions: Yes

"editor.lineHeight": 0
![lineheight0](https://user-images.githubusercontent.com/12730887/30187239-7990ab64-9431-11e7-9501-83beb0c33a4d.PNG)

"editor.lineHeight": 1
![lineheight1](https://user-images.githubusercontent.com/12730887/30187246-7f684d9e-9431-11e7-87c5-cd474a290e1d.PNG)

"editor.lineHeight": 1.5
![lineheight15](https://user-images.githubusercontent.com/12730887/30187249-84a4e4ca-9431-11e7-97d7-41241fd29cc3.PNG)

**Comment by roblourens** [comment]
This looks correct. The documentation for that setting says `Use 0 to compute the lineHeight from the fontSize.`

What else do you expect for a very small line height?

**Comment by smtnsk** [comment]
I was expecting the setting to work similarly to other editors, where my
preferred setting is usually 1.2. What values should I be using in Code if
I want to make the line height smaller than default?

**Comment by roblourens** [comment]
They must have a different definition of it. I think maybe it's on the same scale as font size. But you should just increase it until you find a comfortable value.

**Comment by yume-chan** [comment]
Seems `markdown.preview.lineHeight` and `terminal.integrated.lineHeight` both use relative values, only `editor.lineHeight` is absolute. It's a little bit inconsistent.

**Comment by smtnsk** [comment]
Okay, I got it now. I had to set it to 15 to get the result I was after. It might be a good idea to mention in the documentation what values the setting is expecting.

![lineheight15](https://user-images.githubusercontent.com/12730887/30208714-724194b0-949d-11e7-8a39-5ce8d5a9bca1.PNG)

**Comment by roblourens** [comment]
I see, the terminal value is like a multiplier. Maybe the `editor.lineHeight` description should have another sentence about how the value is used.

**Comment by luangong** [comment]
I suggest you make `editor.lineHeight` a multiplier to keep consistency with `terminal.integrated.lineHeight` and `markdown.preview.lineHeight`. Thanks 😄

**Comment by alexandrudima** [comment]
@luangong unfortunately it is too late to do that, as we probably have by now very many users that have customized it using the current behaviour.

Since more than 5 years, the `editor.lineHeight` is the value, in CSS pixels of the amount of space used for lines vertically.

I am sorry it is not a multiplier as you were expecting.

We can improve the documentation, but this is one of those things that is too late to change.

**Comment by luangong** [comment]
Is it possible to add another setting called `editor.lineHeightUnit` and default it to `px`? The value of `editor.lineHeightUnit` can be `px`, `em`, `cm`, etc.

**Comment by alexandrudima** [comment]
@luangong yes, anything is possible. If that would reduce confusion or increase it, is hard to tell.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
