### ISSUE TITLE
No Visible Indicator of New Version of VS Code with Hidden Activity Bar.

### ISSUE THREAD

**Issue by skl131313** [Microsoft/vscode#33960]
With the recent change that removes the popup window when a new update is indicated, if you have the activity bar hidden then there's no way to know there's a new update.

```JSON
"workbench.activityBar.visible": false
```

Also not sure if there is a command to update VS Code through the command palette. There is `Extensions: Check for Updates` but I don't think that includes VS Code.

**Comment by isidorn** [comment]
You will get an explicit message after a couple of days of not updating.
Closing as designed 
fyi @joaomoreno

**Comment by skl131313** [comment]
Couldn't an icon or something be added to the status bar instead? A little gear in the bottom left corner that does the same thing as the gear in the bottom left activity bar?

The activity bar is kind of a waste of space for me. That explicit message just seems more like a way to inform someone who isn't aware of the icon in the activity bar. I want to be able to know that there's an update the day of the update, not a couple days later just because I don't want the clutter of the activity bar.
