### ISSUE TITLE
Terminal doesn't remove additional lines run from the editor when viewing history.

### ISSUE THREAD

**Issue by BoardWithLife** [Microsoft/vscode#33962]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
terminal|for|0.0.10
PowerShell|ms-|1.4.2
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1 .Create Multiple lines of code in the editor. (Just declare 3 variables on separate lines).
2. Select the three lines and run with F8
3. When focused on the Integrated terminal and using the up arrow to review history, the two additional lines do not disappear from the terminal window. 
Here is a video of the behavior:
[VSCode.zip](https://github.com/Microsoft/vscode/files/1286050/VSCode.zip)

Reproduces without extensions: No

**Comment by iMahesh** [comment]
@BoardWithLife unable repro even with the extensions. 
Could you please try to reproduce it with VSCode-insider?
![image](https://user-images.githubusercontent.com/19846657/30185385-07c5797a-93d6-11e7-9792-10aa2b85f127.png)

**Comment by Tyriar** [comment]
Since you said it doesn't reproduce without extensions, please create this against the powershell extension repo https://github.com/PowerShell/vscode-powershell
