### ISSUE TITLE
Option to disable thread exit logging in launch.json

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#33965]
Desired Behavior:

I'd like the ability to disable thread exit messages in the Debug Console. Options already exist for other types of messages such as module loads (under logging.moduleLoad), so this would simply be another one added to the list.

![vscode thread exit messages](https://user-images.githubusercontent.com/484784/30185717-47708c06-93e8-11e7-9b27-205b1aa4484e.png)

- VSCode Version: Code - Insiders 1.17.0-insider (ac167c41bababe6c47180012723fa2bc52610ff4, 2017-09-07T05:24:04.020Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
Lua|key|0.0.9
cpptools|ms-|0.12.3
code-settings-sync|Sha|2.8.3

---

Steps to Reproduce:

1. Launch a C++ program under the debugger
2. Notice "The thread #### has exited with code 0 (0x0)" messages in the Debug Console

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#1017
