### ISSUE TITLE
Extension @sort:rating is out of order

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#33967]
When searching for an extension, and sorting by rating, the sort displays out of order. As you can see there are ones with a rating followed by ones without a rating followed by more with a rating.

Also, they are out of order, where there are some `4.5`'s before `5`'s (however this part of the order could be based on the total number of ratings as well).

![extension-sorting](https://user-images.githubusercontent.com/1571806/30186265-69b802c4-93ea-11e7-97ca-b1753aada134.png)

**Comment by ramya-rao-a** [comment]
@sandy081 @joaomoreno The marketplace lists extensions in the exact same order when sorted by rating. Where can we log an issue for the marketplace?

**Comment by joaomoreno** [comment]
@ramya-rao-a Usually you can ping @modigrv and he can comment on the issue. :+1:

**Comment by modigrv** [comment]
A related issue is here https://github.com/Microsoft/vscode/issues/27229. 
VS Code has moved to Weighted rating similar to Marketplace website. The rating is not a plain average rating sort. It considers the number of ratings and also the average across all VSCode extensions to weigh in and decide on final rating.

**Comment by TheColorRed** [comment]
@modigrv If it considers the number of ratings as well shouldn't the ones without ratings be at the bottom? Whereas in the image they are in the middle.

**Comment by modigrv** [comment]
If an extension does not have any ratings, it is not considered as 0 rating, its rating is assumed to be product average (average rating across all VSCode extensions). 
So, some extensions having bad ratings, the overall weighted rating of them drops below average and hence those are listed even below the no ratings extensions.

**Comment by ramya-rao-a** [comment]
Closing this issue as per the explaination in https://github.com/Microsoft/vscode/issues/33967#issuecomment-332404184
