### ISSUE TITLE
magnifier vscode can not work well like in vs ，in vscode can not Follow the text insertion point and not Follow keyboard focus

### ISSUE THREAD

**Issue by fanhonghai** [Microsoft/vscode#33976]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/

**Comment by roblourens** [comment]
Does the magnifier follow the cursor in other text editors?

**Comment by alexandrudima** [comment]
Duplicate of #7394
