### ISSUE TITLE
Document typescript.tsdk_version setting and/or improve typescript.tsdk version detection for development versions of TS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#33977]
The undocumented `typescript.tsdk_version` is currently to set the version of development builds of TS since we cannot determine this automatically. We should improve how TypeScript version is determined and/or create a real documented setting for this

// cc @mhegazy

**Comment by mjbvz** [comment]
Added local to handle TS local build but opted not to document the `tsdk_version` as this setting may be confusing.

To verify this: 

1. Clone and build TypeScript locally: https://github.com/Microsoft/TypeScript
1. Point `typescirpt.tsdk` into the `built/local` folder inside of your TS repo. For example

```
    "typescript.tsdk": "/Users/matb/projects/TypeScript/built/local"
```

1. Make sure this version of TS is active in the workspace.
1. Confirm that the TS version is correctly picked up from the top level Typescript `package.json`

**Comment by roblourens** [comment]
Should it switch to the tsdk version automatically, instead of "use vs code's version"?

**Comment by mjbvz** [comment]
No, the flow for selecting TS versions is unchanged. However we now should correctly pick up the version for a TS local build (it should be 2.6 currently)
