### ISSUE TITLE
Pressing ESC in Bash prompt sometimes prints <M-C-F3>

### ISSUE THREAD

**Issue by Entroper** [Microsoft/vscode#33973]
I'm not sure if this is a VS Code or BashOnWindows issue.  I haven't seen it in a regular console window, only the integrated shell in VS Code.

Sometimes, but not most of the time, when I press ESC, the console prints <M-C-F3>.  I normally encounter this in vim when trying to escape insert mode.

https://imgur.com/O1PsWtK

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
EditorConfig|Edi|0.10.1
tslint|eg2|0.17.0
flow-for-vscode|flo|0.7.1
csharp|ms-|1.12.1
vscode-docker|Pet|0.0.16

Steps to Reproduce:

1. `git commit` with vim as your editor
2. Type a commit message, press ESC
3. Sometimes <M-C-F3> gets printed instead of exiting INSERT mode

**Comment by Tyriar** [comment]
Likely an issue in https://github.com/rprichard/winpty
