### ISSUE TITLE
Syntax highlighting with PHP broken in latest update

### ISSUE THREAD

**Issue by daviddeejjames** [Microsoft/vscode#33979]
- VSCode Version: 1.16.0
- OS Version:  Windows 10 Pro (10.0.15063 Build 15063)

Steps to Reproduce:

1. Launch VSCode with latest update and without extensions, use Monokai Color Theme
2. Start a new PHP file with some HTML between PHP tags

Reproduces without extensions: Yes

PHP syntax highlighting is broken for me on latest update (1.16.0). It looks like it thinks the PHP tags are missing or broken i.e the HTML in between should not become purple and the next PHP tag should also not be purple. I have disabled extensions. Reverting back to the previous build works. Screenshot:
![image](https://user-images.githubusercontent.com/5327212/30192210-81df44a8-9489-11e7-9a15-3ad0b0bcf1b4.png)

**Comment by roblourens** [comment]
Looks like this is the same case as the grammar issue, https://github.com/atom/language-php/issues/246. Triggered when the HTML portion is inside a PHP block.

**Comment by roblourens** [comment]
Also https://github.com/Microsoft/vscode/issues/32639

**Comment by daviddeejjames** [comment]
@roblourens ahhh I see, thanks for that, I shall keep an eye on the atom issue.
