### ISSUE TITLE
Feature request - to save input text in keybindings

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#33978]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

Not critical. But it would be better if text input field could save the text, that user has been typed.

_after switching to another tab:_
![keybindings - text input - 2](https://user-images.githubusercontent.com/24613274/30191870-8691b720-944c-11e7-8b34-642545b3166a.gif)

_after moving the "keybindings.json" tab to another group:_
![keybindings - text input](https://user-images.githubusercontent.com/24613274/30191632-c905dce6-944a-11e7-9fa3-5da69374749f.gif)

**Comment by sandy081** [comment]
Duplicates #23543
