### ISSUE TITLE
Nls: align `config` and `loadMessageBundle` calls

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3397]
Testing #3156

When using `vscode-nls`, I have to call `nls.config()` in one file and `loadMessageBundle` in all the others. Couldn't we align this such that I don't need to track whether I have called `nls.config()` in one of my files at all?

Eg: just calling `nls.config()` in all files would fix it for me.

**Comment by dbaeumer** [comment]
I am pretty sure that this is already possible. But need to check.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-nls#6
