### ISSUE TITLE
When resolving a merge conflict, adding resolved file to staged changes triggers warning

### ISSUE THREAD

**Issue by mattiLeBlanc** [Microsoft/vscode#33983]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ColdFusion|Ske|0.0.1
vscode-caniuse|aka|0.5.3
stylus|buz|0.1.0
tslint|eg2|0.17.0
coldfusion|ili|0.0.11
indent-rainbow|ode|0.6.1
vscode-icons|rob|7.12.0
gitblame|wad|2.1.0
html2jade|wma|0.2.0
markdown-authoring|yan|0.1.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Merge a branch that creates a merge conflict.
2. Resolve the conflicted file
3. Click on + sign to added resolved file to Staged Changes. VS Code will now notify you that you are trying to add a file with a merge conflict to Staged Changes. I just resolved the merge conflict so it shouldn't give me this warning.

All in all, I think the git integration is awesome. Keep it up!

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Original feature: #30055. You'll find a lot of interesting perspectives over there, of how hard it is to detect these cases.

But I guess we should actually grep for `<<<<<<` and similar markers and only prompt the warning in those cases.

**Comment by mattiLeBlanc** [comment]
Hi,

If I can use regex to scan through the file and look for the `<<<<<<<<`. Or should I use grep?
Not sure on what level the VS Code source is operating. Would I write it in JS or in something else?

**Comment by joaomoreno** [comment]
Sure, you can use regexp. Something like `/^(<<<<<<|>>>>>>|======)/m` should work.

**Comment by mattiLeBlanc** [comment]
okay, I will give it a try.

**Comment by naro** [comment]
I would prefer a more complex match to avoid false positives if you are solving merge conflict in a text file. I'm using ======== as a separator under version number in my changelog, for example. 

This regexp could work
/^<<<<<<<[\s\S]+^=======[\s\S]+^>>>>>>>/m
See also:
https://regex101.com/r/YyzRGL/1

If it looks too complex, the following would work as well :)
/^(<<<<<<|>>>>>>)/m

**Comment by roblourens** [comment]
This is much better but I think it could still be less sensitive, and would look better if it matched the merge-conflict extension's marker detection. It seems to be checking for just one of the merge marker types (>>>, ===, <<<), where merge-conflict is checking for all 3 of them.

e.g. If I just have `========asdf` on a line in the file, the warning is triggered.

**Comment by joaomoreno** [comment]
That's fine, IMO. If you don't use merge-conflict and resolve it manually, you might forget one of the markers.

**Comment by fenke** [comment]
Why is this closed, the problem persists

**Comment by RReverser** [comment]
I assume this is fixed in some upcoming version? Still happening to me (and, apparently, not just me).

**Comment by roblourens** [comment]
This is fixed in Insiders and the upcoming 1.18 release
