### ISSUE TITLE
wana vscode can close file group

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#33980]
- VSCode Version: 1.16
- OS Version:macos 10.13

![image](https://user-images.githubusercontent.com/9606668/30192892-c88ab24a-940f-11e7-894d-12fe248975a0.png)
![image](https://user-images.githubusercontent.com/9606668/30192896-d2a8bc18-940f-11e7-9718-608393d0fa6e.png)

**Comment by roblourens** [comment]
Can you give some more details about what you're asking for?

**Comment by NateLing** [comment]
@roblourens 
when you use some tool to complete like less,scss,js,ts, you will get completed files.
a.less -> [a.less,a.css,a.css.map], b.js -> [b.js,b.min.js,b.map]
i want vscode can close those file like the picture 1

**Comment by roblourens** [comment]
I see. I think this would fall under #6328
