### ISSUE TITLE
Let user to set the mouse keys as keybindings (feature request)

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#33985]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

How about to let user to set mouse keys as keybindings?

For example, people who have the mouse-wheel like this:

![image](https://user-images.githubusercontent.com/24613274/30194175-3c6122f4-945a-11e7-9f2b-2aa53cf06ab7.png)

would have +2 often used commands in VS Code, bound to these "Shift to the Left" of the wheel, and "Shift to the Right".

And the owners of the mouse like that:

![image](https://user-images.githubusercontent.com/24613274/30194328-2dc80aa4-945b-11e7-9715-70e2dfb1a333.png)

would have +4 (or even 5) more chances to bind all necessary commands to the keys.

**Comment by gjsjohnmurray** [comment]
Related to #3130

**Comment by alexdima** [comment]
Let's track in  #3130
