### ISSUE TITLE
有时候无法使用简体中文，强制繁体或者无法输入汉字。

### ISSUE THREAD

**Issue by hu-qi** [Microsoft/vscode#33987]
- VSCode Version:1.15.1
- OS Version: win10  64家庭中文版

有时候无法输入简体中文或者直接被切换成繁体，切换到其他应用输入法仍是繁体，再切换回来就只能输出英文。
Sometimes can't input is simplified Chinese or switch to traditional, switch to the other application input method is still traditional, switch back can only output in English.
Is my operating system problem？

**Comment by roblourens** [comment]
Problem with your IME?

**Comment by yume-chan** [comment]
Which IME do you use?

**Comment by hu-qi** [comment]
Sogou Pinyin  and  Microsoft Pinyin.

**Comment by alexandrudima** [comment]
@hu-qi 

Do you have issues when typing in an editor or when typing anywhere in VS Code?

e.g. if you switch back to vs code and type in the search viewlet input box, or in the find widget input box, do you also see this problem?
