### ISSUE TITLE
when I write js function comment, vs code not response

### ISSUE THREAD

**Issue by ruanjiayou** [Microsoft/vscode#33984]
- VSCode Version: Code 1.15.1 **[Unsupported]** (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.4
HTMLHint|mka|0.3.3
easy-less|mrc|1.4.5
vscode-csscomb|mrm|5.1.0
color-highlight|nau|2.3.0
vscode-icons|rob|7.12.0
background|sha|1.1.15
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.I write @param {char} [ch - 取整部位
2.I want [ch=s] ,vs code not response

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still happen if you disable all of your extensions?
