### ISSUE TITLE
Linter pep8 and pylint is not installed errors

### ISSUE THREAD

**Issue by cryst10** [Microsoft/vscode#33988]
- VSCode Version:  1.16.0
- OS Version: MacOS Sierra
- Python version: 3.6
- pip: 3
- virtualenv: 3
- extension: https://github.com/DonJayamanne/pythonVSCode/wiki

I am working in a virtualenv, I have my settings.json file like the below:

```
{
  "python.pythonPath": "python",
  "python.linting.pylintEnabled": true,
  "python.linting.pylintPath": "pylint",
  "python.linting.pep8Enabled": true
}
```
I have installed both pylint and pep8 in my virtualenv but keep getting those noisy error alerts in vscode `Linter pep8 is not installed` or `Linter pylint is not installed`, I am using this extension https://github.com/DonJayamanne/pythonVSCode/wiki.

**Comment by roblourens** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1197
