### ISSUE TITLE
Editor history lost when closing inactive group

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#33997]
Steps to Reproduce:

1. have 2 files open side by side
2. be in the first file to the left and navigate around (at least 10 lines apart) to produce some editor history
3. navigate back
4. close inactive editor on the right hand side
5. try to navigate forward

=> history is lost after the point where the inactive editor is closed because we wrongly treat that as a editor navigation event

**Comment by roblourens** [comment]
How do you close the inactive editor? I can't repro this in 1.16.

**Comment by bpasero** [comment]
@roblourens you can close it by just clicking the close button of the tab without making the editor active!

**Comment by roblourens** [comment]
That's what I'm doing. But I also can't repro it in 1.17, eh...
