### ISSUE TITLE
on mac osx i can‘t update

### ISSUE THREAD

**Issue by CoderBOBO** [Microsoft/vscode#3399]

**Comment by joaomoreno** [comment]
Do you see any errors? Which version of Code do you have? Which version of OS X do you have? What is the behaviour you see?

**Comment by CoderBOBO** [comment]
no response.     os x10.11.3

**Comment by joaomoreno** [comment]
What do you mean by *no response*? Maybe provide a screenshot? Some videos? Gifs? Any more information would be great.

Also, and again, what version of Code do you have?

**Comment by greimers** [comment]
I have the same problem but as the OP didn't give any detail, let me describe it:

- VS shows the notification that there is an update available
- I click "update" and get asked for admin credentials
- VS quits itself and does not open again
- When I manually open it, no update was installed
- There is no error message or any feedback

My console logs are full with hundreds of this entry:
`21/03/16 14:34:13,422 com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
21/03/16 14:34:15,452 com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt[1455]) Service exited with abnormal code: 1`

I'm having this issue for months with every version of VS. I always manually download VS from the website.
I am on and English El Capitan, MacBook Pro 2012.

**Comment by joaomoreno** [comment]
This is strange as you seem to `get asked for admin credentials`. You installed Code in a location that your user has no permissions to modify?

Can you try installing it in a location your user controls, e.g. `~/Applications`, and see whether the update works then?

**Comment by zhangmx** [comment]
I have the same problem. my console.app 's log:

> 6/20/162262 3:47:59.541 PM lsd[305]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
> 6/20/162262 3:48:03.143 PM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.432032[15619]) Service exited with abnormal code: 1
>

**Comment by joaomoreno** [comment]
Closing as: please install VS Code in a directory that your user has modifying rights.
