### ISSUE TITLE
文件->打开文件夹，反应非常非常迟钝，直接拖动文件夹到vs code倒是很快

### ISSUE THREAD

**Issue by ElegantGod** [Microsoft/vscode#33995]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.0
cpptools|ms-|0.12.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you include some more details about what the problem is and how I can reproduce it?
