### ISSUE TITLE
default intellisense engine not working

### ISSUE THREAD

**Issue by liuchanchen** [Microsoft/vscode#33991]
- VSCode Version:
1.15.1
- OS Version:
ubuntu 16.04 LTS
Steps to Reproduce:
1.install c/c++ extension
2.set C_Cpp.intelliSenseEngine as defult
3.restart vs code
4.find autocomplete doesn't work 

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you file this on the C++ extension repo, since it seems to be an issue with the extension?
