### ISSUE TITLE
Ability to name folders in workspace tree.

### ISSUE THREAD

**Issue by kwilliams1987** [Microsoft/vscode#33996]
- VSCode Version: Code - Insiders 1.17.0-insider (c354fca44896da2c9cad82b9bd9126f6658cfae8, 2017-09-08T05:24:34.310Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svn|eli|0.1.0
tortoise-svn|fan|0.1.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
composer|ika|0.5.0
smarty|imp|0.2.0
vscode-apache|mrm|1.1.1
wow-bundle|Sep|1.2.4
---

Steps to Reproduce:

1. Add a folder to workspace EG: C:\web\server\webroot
2. Add a second folder to workspace EG: C:\web\client\webroot

Without checking the content these two are now identical "wwwroot" folders in the navigator.

Please add something like this to workspace settings:

    {
    	"folders": [
    		{
    			"name": "Server",
    			"path": "C:\web\server\webroot"
    		},
    		{
    			"name": "Client"
    			"path": "C:\web\client\webroot"
    		}
    	]
    }

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This has been discussed in https://github.com/Microsoft/vscode/issues/396, I think it's covered by that issue.
