### ISSUE TITLE
PHP code highlighting broken in 1.16

### ISSUE THREAD

**Issue by mstpwnz** [Microsoft/vscode#33993]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.15
ftp-sync|luk|0.3.3
nativescript|Tel|0.7.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open any PHP file (using any theme)
2. Write something like this
`<?php if(a==b) { ?>`
`<p>some html with <?='php'?></p>`
`<?php } ?>`
3. HTML highlights and PHP tags highlights are wrong inside these brackets.

Reproduces without extensions: Yes
![example](https://user-images.githubusercontent.com/3955719/30199074-aeffee7a-9479-11e7-8d15-65b1b5f75fbb.png)

**Comment by roblourens** [comment]
This is a result of https://github.com/atom/language-php/issues/246
