### ISSUE TITLE
Keytar makes travis build fail if they run extension host tests

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#33998]
The problem is that on Travis a machine usually doesn't have `libsecret-1` installed. We should at least document this in the release notes that users know what to do.
```
{ errorCode: 'load',
  moduleId: 'keytar',
  neededBy: [ 'vs/platform/credentials/node/credentialsService' ],
  detail: 
   Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (/home/travis/build/Microsoft/vscode-languageserver-node/client/lib/.vscode-test/VSCode-linux-x64/resources/app/out/vs/loader.js:4:10954)
       at Object.<anonymous> (/home/travis/build/Microsoft/vscode-languageserver-node/client/lib/.vscode-test/VSCode-linux-x64/resources/app/node_modules/keytar/lib/keytar.js:1:169)
       at Object.<anonymous> (/home/travis/build/Microsoft/vscode-languageserver-node/client/lib/.vscode-test/VSCode-linux-x64/resources/app/node_modules/keytar/lib/keytar.js:55:3) }
```

The fix is to add this to the travis build
```
addons:
  apt:
    packages:
      - libsecret-1-dev
```

**Comment by chrmarti** [comment]
@dbaeumer Would `libsecret-1-0` be sufficient? (It should if you are not building keytar.)

**Comment by dbaeumer** [comment]
I guess. But after discussing it with @jrieken it looks like we should remove this all together since VS Code shouldn't load keytar.

**Comment by jrieken** [comment]
Yeah, @chrmarti  this the `CredentialsService` that we still load and which in return loads the key tar module. I don't think this a problem for computers that are used by humans but this is likely a problem for travis-like setups

**Comment by chrmarti** [comment]
The .rpm and .deb packages have the dependency listed. I'll change it to load keytar on demand. Once we know where to go with the credentials API, we can either keep or remove all associated code.

**Comment by DanTup** [comment]
For people running the tests on Travis whose builds recently broke with the above error (eg. https://travis-ci.org/Dart-Code/Dart-Code/jobs/273234511) should we be making the changes in the original post here, or are you making changes that will "unbreak" this? (I don't totally understand what you're planning from the comments above, or what keytar is!).

**Comment by chrmarti** [comment]
@DanTup The quickest fix is adding `libsecret-1-0` as a dependency to your travis config (let me know if that works). Alternatively you could wait for the next insiders build (most likely Monday) which will have my workaround in code.

**Comment by DanTup** [comment]
@chrmarti Sorry for the delay; the Mac builds had been paused on Travis for a while because they were having issues. The change worked fine, build is green now. I'll revert the change in a couple of days and ensure it still works. Thanks!

**Comment by DanTup** [comment]
@chrmarti I reverted my fix for this today expecting it'd work now, but it still fails with the same error.

I'm not totally familiar with how the tests work (I presume they're downloading the latest version at runtime, since the original issue occurred without me updating anything); would you expect it to work now?

**Comment by chrmarti** [comment]
@DanTup Can you confirm your build runs against the latest insiders build? It might use the latest stable release which hasn't changed yet.

**Comment by DanTup** [comment]
@chrmarti Very likely - I'm not sure what controls which build it uses ([config is here?](https://github.com/Dart-Code/Dart-Code/blob/master/.travis.yml)). I think I may have assumed that because it broke on its own (without any code changes) it was effectively using nightly/insider builds, though I guess more likely it was a stable update.

I can try removing the dependency again after the next stable release and probably that'll work.

**Comment by chrmarti** [comment]
@DanTup Not sure what decides which version of VSCode is used. Note that the library might become required again at a later point depending on how we move forward.

**Comment by DanTup** [comment]
@chrmarti Ok, maybe I'll just leave it as-is for now then; it's not really causing any harm and it works! :-)

**Comment by dmvianna** [comment]
I'm on a Windows 10 machine, and after adding an extension I cannot execute vscode anymore. I don't remember which extension it was.
```bash
$ code --list-extensions
donjayamanne.python
hnw.vscode-auto-open-markdown-preview
magicstack.MagicPython
ms-mssql.mssql
ms-vscode.Theme-MarkdownKit
robertohuertasm.vscode-icons
yzane.markdown-pdf
yzhang.dictionary-completion
yzhang.markdown-all-in-one
```
And the error message
```bash
$ code --verbose

{ errorCode: 'load',
  moduleId: 'keytar',
  neededBy: [ 'vs/platform/credentials/node/credentialsService' ],
  detail:
   Error: The module '\\?\C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\keytar\build\Release\keytar.node'
   was compiled against a different Node.js version using
   NODE_MODULE_VERSION 54. This version of Node.js requires
   NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
   the module (for instance, using `npm rebuild` or`npm install`).
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\loader.js:4:10954)
       at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\keytar\lib\keytar.js:1:169)
       at Object.<anonymous> (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\keytar\lib\keytar.js:55:3) }
```
Needless to say, this is a corporate machine. I have not compiled anything in it, nor can I. Suggestions welcome. `code --disable-extensions` did not help.

**Comment by chrmarti** [comment]
@dmvianna That's a different issue. It looks like your install is broken, could you try reinstalling VSCode? Please open a new issue if the problem persists.

**Comment by dbaeumer** [comment]
Verified in code.
