### ISSUE TITLE
Unexpected look-up offset on macOS

### ISSUE THREAD

**Issue by LitoMore** [Microsoft/vscode#33990]
- VSCode Version: 1.16.0 (1.16.0)
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Make sure turn on `Look up & data detectors` option in `System Preferences -> Trackpad`

<img width="668" alt="look-up" src="https://user-images.githubusercontent.com/8186898/30195668-7b48c20a-948d-11e7-9505-e023eeaf0d8a.png">

2. Look up in the release view or other markdown preview

![look-up-screenshot](https://user-images.githubusercontent.com/8186898/30195727-f0de7a64-948d-11e7-9c7d-4c2fb6562607.gif)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I believe this is https://github.com/electron/electron/issues/4539

**Comment by bpasero** [comment]
Looks like this is actually fixed with the new webview implementation :raised_hands:

**Comment by LitoMore** [comment]
@bpasero Nice! Look forward to it!

**Comment by bpasero** [comment]
To play around with those builds:

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
