### ISSUE TITLE
Python workspace interpreter doesn't select virtualenv interpreter

### ISSUE THREAD

**Issue by cryst10** [Microsoft/vscode#33992]
- VSCode Version: 1.16.0
- OS Version: MacOS Sierra
- Python version: 3.6
- pip: 3
- virtualenv: 3
extension: https://github.com/DonJayamanne/pythonVSCode/wiki

The Python workspace interpreter doesn't select the virtualenv interpreter, it can't even locate it. Also there isn't a possibility of doing it manually, as it wouldn't save. I'm stuck with system wide interpreter so I cannot locate local virtualenv dependencies.

**Comment by roblourens** [comment]
Is this an issue with the Python extension? Can you open the issue in that repo if so?

**Comment by cryst10** [comment]
@roblourens can you forward this issue to that extension like you did with [Microsoft/vscode#33988](https://github.com/Microsoft/vscode/issues/33988) ?

**Comment by roblourens** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1198
