### ISSUE TITLE
Make bot assign issues to owners with a 1 minute timeout

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#33999]
Currently some of our team member (@dbauemer and @jrieken  for example) first create an issue and only then assign it to somebody.
The bot does not seem to cope well with this strategy. Before they could assign it to somebody bot usualy jumps in, adds a debug label and pings me for no reason at all.

Pleae make the bot assign issues with some timeout

**Comment by alexandrudima** [comment]
I would also sincerely appreciate this. Sometimes I hit create issue before assigning it and the bot jumps in like super quickly and steals my thunder ... mostly assigning the issue to the wrong person.

**Comment by chrmarti** [comment]
This is a little harder to implement than to just listen on the create event. Maybe with a shorter delay we could just "setTimeout" and then re-read the issue (which we currently get with the event). Making the delay shorter will make the time window where we "loose" events when restarting the bot smaller.
