### ISSUE TITLE
Javascript - regular expressions are not colored - Javascript mode instantiated twice

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#34]
New **javascript** file, use the following code snippet:

`var booleanRegex = /^true|false$/i;`
`var stringRegex = /^(['"]).*\1$/;`

Notice the regex value **does not get colored**.
Regex coloring works for Typescript.

**Comment by joaomoreno** [comment]
@aeschli isn't this fixed?

**Comment by isidorn** [comment]
Yes this is fixed, I verfied
