### ISSUE TITLE
Browse the Gallery command windows always disappear when clicked somewhere else

### ISSUE THREAD

**Issue by sharechiwai** [Microsoft/vscode#340]
I tried to get "Browse the Gallery command line/Windows " on by pressing F1 / CTRL P, when I tried to 
navigate to web browser and follow the instruction from website
https://code.visualstudio.com/docs/editor/extension-gallery?pub=ms-vscode&ext=jscs
The command line/ windows disappear, it is quite annoying

Any suggestion how to solve this issue?

**Comment by joaomoreno** [comment]
Unless I'm misunderstanding something, this is just how the gallery is. It's a widget that you filter on. If you click somewhere else, it hides.
