### ISSUE TITLE
Open files with VS Code in Windows 10

### ISSUE THREAD

**Issue by karpulix** [Microsoft/vscode#34002]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
tslint|eg2|0.17.0
reg|ion|0.0.1
spellcheck|Jul|1.1.4
format-php|Kas|1.1.2
ftp-sync|luk|0.3.3
cpptools|ms-|0.12.3
debugger-for-chrome|msj|3.2.1
material-icon-theme|PKi|2.2.0
code-settings-sync|Sha|2.8.3
---

Steps to Reproduce:

1. Right click to any file
2. Select "Edit with VS Code
3. We get error message about Exception
I attach print screen of Exception: http://prntscr.com/gikc6t
![aaz1cda3qmctwbu9n9kitq](https://user-images.githubusercontent.com/16068884/30202841-093c7c5c-94aa-11e7-9d86-912404148692.png)
Sorry for my english. 

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Can you open VSCode in any other way? It seems like your installation must be corrupted. Can you try reinstalling?

**Comment by alexandrudima** [comment]
fyi @joaomoreno maybe you have an idea

**Comment by joaomoreno** [comment]
Please try to fully reinstall VS Code.

**Comment by karpulix** [comment]
**Once I used one hook for add VSCode to the context menu of Windows Explorer.**
Here it is (.reg file):
```
Windows Registry Editor Version 5.00 
; Open files 
[HKEY_CLASSES_ROOT\*\shell\Open with VS Code] 
@="Edit with VS Code" 
"Icon"="C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe,0" 
[HKEY_CLASSES_ROOT\*\shell\Open with VS Code\command] 
@="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\" \"%1\"" 
; This will make it appear when you right click ON a folder 
; The "Icon" line can be removed if you don't want the icon to appear 
[HKEY_CLASSES_ROOT\Directory\shell\vscode] 
@="Open Folder as VS Code Project" 
"Icon"="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\",0" 
[HKEY_CLASSES_ROOT\Directory\shell\vscode\command] 
@="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\" \"%1\"" 
; This will make it appear when you right click INSIDE a folder 
; The "Icon" line can be removed if you don't want the icon to appear 
[HKEY_CLASSES_ROOT\Directory\Background\shell\vscode] 
@="ќткрыть в Visual Studio Code :)" 
"Icon"="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\",0" 
[HKEY_CLASSES_ROOT\Directory\Background\shell\vscode\command] 
@="\"C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe\" \"%V\""
```
**To fix the problem, I deleted all the registry keys that were added by me.**
I did this (.reg file):
```
Windows Registry Editor Version 5.00 
[-HKEY_CLASSES_ROOT\*\shell\Open with VS Code] 
[-HKEY_CLASSES_ROOT\*\shell\Open with VS Code\command] 
[-HKEY_CLASSES_ROOT\Directory\shell\vscode] 
[-HKEY_CLASSES_ROOT\Directory\shell\vscode\command] 
[-HKEY_CLASSES_ROOT\Directory\Background\shell\vscode] 
[-HKEY_CLASSES_ROOT\Directory\Background\shell\vscode\command]
```
After I reboot PC and I reinstall VSCode. Now everything works. Thank u everybody!
