### ISSUE TITLE
Decoration types break when removing the first (original) folder from a multi-folder workspace

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#34004]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider) ac167c41bababe6c47180012723fa2bc52610ff4
- OS Version: macOS 10.12

Steps to Reproduce:

1. Create a simple extension with the code below:
```javascript
exports.activate = context => {

  const vscode = require('vscode');
  const red = window.createTextEditorDecorationType({
    isWholeLine: true,
    backgroundColor: 'red'
  });
  const green = window.createTextEditorDecorationType({
    isWholeLine: true,
    backgroundColor: 'green'
  });

  window.activeTextEditor.setDecorations(red, [new vscode.Range(0, 1, 0, 100)]);
  window.activeTextEditor.setDecorations(green, [new vscode.Range(1, 1, 1, 100)]);

  context.subscriptions.push({dispose: () => {
    window.activeTextEditor.setDecorations(red, []);
    window.activeTextEditor.setDecorations(green, []);
    red.dispose();
    green.dispose();
  }});
};
```
2. Open a folder, then add another folder to the workspace. Then remove the first (original) folder from the workspace. Decoration types will be broken. See the GIF below:

![vb](https://user-images.githubusercontent.com/979966/30203389-5304d35a-94c5-11e7-89c4-53e076560c77.gif)

The issue is only reproduced when removing the first folder in the workspace (in this case the extension is deactivated/activated back).

**Comment by bpasero** [comment]
This seems to be a consequence of the extension host restart. Moving to @alexandrudima

**Comment by alexandrudima** [comment]
Indeed, it appears the decorations are not correctly removed when the extension host is restarted.
