### ISSUE TITLE
program in launch.json not support environment variable

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#34009]
- VSCode Version: 1.16.0-Insiders
- OS Version: Win10

Steps to Reproduce:

1. I have a environment variable called `ts-node` (A path of a js file)
2. launch.json as below

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "TS Node",
            "program": "%ts-node%",
            "args": [
                "index.ts"
            ],
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

**Expect**
launch successful

**Actual**
> Error: Attribute 'program' is not absolute; consider adding '${workspaceRoot}/' as a prefix to make it absolute.

**Comment by isidorn** [comment]
Please use 
"program": "${env.ts-node}" if ts-node is the full name of your ENV variable

**Comment by k8w** [comment]
@isidorn Yes, `ts-node` is the full name.
But still get this error: 
> Error: Attribute 'program' is not absolute("${env.ts-node}"); consider adding '${workspaceRoot}/' as a prefix to make it absolute.

Is it because `${env.ts-node}` isn't starts with `${workspaceRoot}` ?

**Comment by isidorn** [comment]
My mistake, please use
`${env:ts-node}`
