### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by a596544022** [Microsoft/vscode#34008]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
open-html-in-browser|cod|0.1.21
vscode-html-css|ecm|0.1.8
vue-snippets|hol|0.1.4
path-autocomplete|ion|1.6.1
Go|luk|0.6.65
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
Please share more information with us. What did you do? Then what happened?

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our [guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) for filing issues. Thank you for your contributions.
