### ISSUE TITLE
Vscode become extremely slow with big files

### ISSUE THREAD

**Issue by BenoitValdes** [Microsoft/vscode#34000]
- VSCode Version: Code - Insiders 1.16.0-insider (aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad, 2017-09-01T15:25:57.896Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
clarissecomandport|Ben|0.5.0
indenticator|Sir|0.4.2
Bookmarks|ale|0.16.0
project-manager|ale|0.20.0
python|don|0.7.0
cpptools|ms-|0.12.3
datetime|rid|1.0.5
vscode-icons|rob|7.12.0
trailing-spaces|sha|0.2.11

---
I have a json file with almost 100 000 lines. If I want to edit it inside of VSCode everything becomes slow, the syntax color is not shown at all.
I could understand that if it was the same with sublime text but it's not. Sublime get all these lines easily and everything is as smooth as usual.

**Comment by alexandrudima** [comment]
@BenoitValdes Does this issue reproduce when you disable all extensions either manually or via `code --disable-extensions` ? 

The reason I am asking is that extensions also get to see these very large files and some extensions create hundred of thousands of decorations or some other similar things which can lead to slow-downs.

**Comment by BenoitValdes** [comment]
You are right, this is faster when I disable all the extensions.
After some investigation, it seems that it comes from the trailing-spaces plugin.
Moreover, this is still slower than sublime text. So maybe there is something that you could do on your side to speed-up the loading of these kinds of files.

Thank you for talking about the plugin, I didn't think about that.

**Comment by alexandrudima** [comment]
@BenoitValdes Yes, some extensions might not be prepared to deal with large files... 

I'm happy to take a look if there is something we can do to speed things up. Can you attach the file that causes slowness or perhaps a similar file (if you cannot for legal reasons) or perhaps a generator script that generates a similar file ?

**Comment by BenoitValdes** [comment]
@alexandrudima Thanks to taking a look of this.

I can't provide you the exact file but you can find attached to the comment a python script that can generate a similar file. Feel free to edit it to generate a larger file. By default, the script generates a file with approximately 120 000 lines.
[generate_big_json_file.py.zip](https://github.com/Microsoft/vscode/files/1324329/generate_big_json_file.py.zip)

**Comment by alexandrudima** [comment]
@BenoitValdes Thank you, I got myself the 120k lines json. But I cannot reproduce any perceivable slowness (without extensions and with our out of the box settings).

**Comment by BenoitValdes** [comment]
@alexandrudima This is weird because for me the syntax color takes ages to appear and, sometimes, it can take almost 1 second to load the file.

**Comment by alexandrudima** [comment]
Thanks for pointing out what you find slow.

I would not consider the time it takes for tokenization to reach the bottom of the file informative of our performance. Different editors have different strategies. We chose to display the file as soon as we can and then tokenize it in portions, in the background... always yielding and never tokenizing for more than 20ms. Tokenization times vary greatly by file shape, chosen grammar and chosen theme.

What I can look into is why it takes such a long time (300ms) for the creation of the buffer after the text has been read and for the creation of the view. There is also a lot of time spent in bracket matching (250ms) if I leave the cursor at position (1;1) ... the matching bracket is found at line 120k...

<img width="1520" alt="screen shot 2017-09-22 at 15 15 32" src="https://user-images.githubusercontent.com/5047891/30746207-42532bd0-9fa9-11e7-8f2f-fa1ca5b959f8.png">

**Comment by BenoitValdes** [comment]
Thanks for the explanation. You resolved my issue with your first reply. In my view, this issue is no longer one.
Everything comes from the file that uses nested dictionaries and could be a bit complex for the syntax highlighting system.

Thanks for your time, keep the good work ;)
