### ISSUE TITLE
Opening links / URLs in Safari happens in old, minimised window

### ISSUE THREAD

**Issue by agos** [Microsoft/vscode#34003]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0

---

## Steps to Reproduce:

1. Have a bunch of Safari windows, minimise the older ones
2. Set up Safari to open links in new tabs, not new windows
3. Open a link from Visual Studio Code. The menu item Help → Report Issues ~work~ has the issue, but many others do as well: open in Github is another notable example.

## Expected:

The url is opened as a new tab in the frontmost window

## Actual result:

The url is opened as a new tab in an old (perhaps the oldest?) window, even if it is minimised

I thought this might be a bug with Safari, but other apps (Tweetbot for example) don't have the same issue.

**Comment by roblourens** [comment]
Are you saying that `Report Issues` gets opened in the right place, but `Open in Github` doesn't? I know we basically use `window.open` for links from VS Code itself. The github link comes from an extension, I'm not sure if they have another method. If you just see the problem from extensions, can you open an issue on their repo?

**Comment by agos** [comment]
Sorry, I was not clear. Both `Report Issues` and `Open in Github` exhibit the unwanted behavior

**Comment by roblourens** [comment]
Ok. For me, it seems to always open in the newest window. I don't think we have control over this from Electron anyway, since we only call `window.open` and it's up to Electron/the OS from there, sorry.
