### ISSUE TITLE
1.16 can't start YML server while opening vscode

### ISSUE THREAD

**Issue by iharsuvorau** [Microsoft/vscode#34014]
- VSCode Version: 1.16
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. Launch `code .` in a directory with YML-files.

For the first launch I saw 'Can't start YML server':

```
[Error - 12:59:56 PM] Starting client failed
Error: spawn /Users/ihar/Library/Caches/com.microsoft.VSCode.ShipIt/update.JxPVEQs/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

For the second and third launches there were no any problems. Is it normal behaviour?

**Comment by mjbvz** [comment]
Does this reproduce if you disable all extensions? Just run `code --disable-extensions .` to check

**Comment by iharsuvorau** [comment]
@mjbvz no, as I wrote it doesn't reproduce even after the second run with the same command `code .`.

**Comment by mjbvz** [comment]
Ok, let us know if you hit this again
