### ISSUE TITLE
Emmet work like a mad

### ISSUE THREAD

**Issue by abhijitkumarbiswas** [Microsoft/vscode#34018]
- VSCode Version: 1.16.0
- OS Version: Windows 10

Steps to Reproduce:

1. In javascript file very where emmet works but emmet have to work only inside the quots, right?
2. I use configation: `"emmet.includeLanguages": {"javascript": "html"}`
3. I type `for` and vs code give me the for loop snippet
4. I hit `Tab` key it have to go to  edit the `array.length` on the screenshort but it execute the emmet.
5. See screenshort. Its make me very annoying and angry too.

![screenshot_1](https://user-images.githubusercontent.com/28084628/30208908-561713fe-94b7-11e7-8e2f-9197b53fc104.jpg)

Before I use sublime text it works good but now i want to use vscode but it make me so much annoying.

**How Can I execute emmet only inside qoutes in `.js` file**

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@abhijitkumarbiswas 

Can you share your settings? I can't repro it

![jsemmet](https://user-images.githubusercontent.com/16890566/30246745-75d715b2-95b7-11e7-8ccf-1dc386eab13a.gif)

**Comment by abhijitkumarbiswas** [comment]
![screenshot_1](https://user-images.githubusercontent.com/28084628/30258392-ddfe2cec-96da-11e7-8751-4d5b6522d684.jpg)

**Comment by ramya-rao-a** [comment]
I can repro it if I follow the below steps exactly

1. Use the `for` snippet (there are multiple cursor for each instance of `index` and `index` is completely selected)
2. Press ESC to escape the snippet mode
3. Use right arrow key (multiple cursors are at the end of each instance of `index` but the word `index` is no longer selected)
4. Press tab

Steps 2 and 3 can be swapped and I can repro

My question for you is
- Are my repro steps above the same as what you are doing? If not, then please share exact repro steps
- If your steps are same as mine, why do you press ESC before completing the snippet?

Here is how tab works in VS Code

Inside snippet mode, tabbing takes you to the next tabstop
Outside snippet mode, if there is a suggestion list, the first item is selected when you tab
Outside snippet mode, if there is no suggestion list, emmet is triggered when you tab if you have enabled `emmet.triggerExpansionOnTab`

**Comment by ramya-rao-a** [comment]
@abhijitkumarbiswas Since you havent gotten back to my questions above, I am assuming you understand the way snippets work and dont have any issues anymore.

If you still have questions, drop a comment here and I can help.

Closing this issue for now.
