### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by incetarik** [Microsoft/vscode#34012]
![screenshot_1](https://user-images.githubusercontent.com/14037316/30205678-37a66d7c-9492-11e7-830f-305883300663.png)
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: No

Since this happens because of any extension, could we track extension usages of RAM, CPU etc.? Or maybe VS Code team may add a new feature that logs/records unexpected usages of extensions.

**Comment by roblourens** [comment]
This is hard to do because all extensions run in one process. If you can figure out which extension is using too much memory (by disabling them), please file an issue on them.
