### ISSUE TITLE
Nested PHP/HTML Syntax Highlighting broken in latest release.

### ISSUE THREAD

**Issue by justlevine** [Microsoft/vscode#34017]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
---

As of the latest update, Syntax Highlight breaks any time I have a `?>` after a `{`.
Looks like VScode doesnt know to switch back to HTML highlighting.
This is with all plugins disabled.
PS: The issue is only with syntax highlighting. If I save the file, I don't get any "Problems".

Steps to Reproduce:

1. Create a new .php file.
2. Start typing some code.
3. Put a `?>` tag after a `{`
4. Watch the colors disappear!

![capture](https://user-images.githubusercontent.com/29322304/30209059-be47b1b8-949e-11e7-93f4-2e384e16fda1.PNG)

Reproduces without extensions: **Yes**/No

**Comment by roblourens** [comment]
Looks like another instance of https://github.com/atom/language-php/issues/246
