### ISSUE TITLE
Problems drag and droping files from vscode to external apps [Windows]

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#34015]
- VSCode Version: 1.16.0
- OS Version: Windows 10 64bit

It's possible to drag and drop files from VSCode's file explorer on external Windows apps but depending on the app it doesn't seem to work properly.

Here are some results:

 - droping an image from vscode explorer onto windows explorer: the file is correctly copied in the explorer's directory
 - droping an image from vscode explorer onto Affinity Photo: shows a "forbidden" sign
 - droping an image from vscode explorer onto Paint: shows a "+" but nothing happens when releasing the mouse
 - droping an image from vscode explorer onto a Skype window: shows a "+" but nothing happens
 - droping an image from vscode explorer onto the Skype window's text input: the path to the image is copied
 - droping an image onto a chrome window: shows a "+", but after releasing the mouse does nothing and the url is set to "about:blank"

It seems that vscode uses the object's path when doing drap & drop onto external apps. If the app recognizes it (eg. Windows Explorer), it will open the file. Unfortunately most apps doesn't recognize it.

My suggestion would be to improve vscode so that dragging files onto apps that support it work.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/164
