### ISSUE TITLE
debugger stopped at bootstrap.js

### ISSUE THREAD

**Issue by haolly** [Microsoft/vscode#34020]
- VSCode Version: 1.16.0
- OS Version: win10

Steps to Reproduce:

1. Follow instruction https://code.visualstudio.com/docs/extensions/yocode
2. F5

debugger stopped at bootstrap.js

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Uncheck the `All Exceptions` checkbox in the breakpoints pane in debug.
If that still does not work please provide more details. Like a video or picture would help

**Comment by haolly** [comment]
![fasdfaf](https://user-images.githubusercontent.com/2383231/30236328-d12b12ba-9549-11e7-80b2-e088d5330809.gif)
@isidorn This only happen when I press F5

**Comment by yuyat** [comment]
+1

**Comment by isidorn** [comment]
The stop on excpetion is coming from the node2 debug adapter, forwaring to @roblourens 
fyi @weinand

**Comment by roblourens** [comment]
Maybe it took too long to launch, and thought it needed to stop on entry.

Does it happen 100% of the time?

**Comment by metaleap** [comment]
Same issue here under Fedora after I updated a months-old vscode installation, nodejs, and then updating an existing extension project to all the new versions (node/ts/vscode etc).

Running with F5 jumps into bootstrap.js straight away even with **no breakpoints set** anywhere. Any breakpoints I set, never enter into and remain grayed-out.

(It's a bug in-so-far as just updating everything shouldn't break what worked smoothly just a few versions/months earlier.)

**Comment by bhughes339** [comment]
@roblourens This is happening for me as well, and it doesn't happen 100% of the time. I'd say probably 90% of the time when I debug (a vscode extension in my case) the bootstrap.js breakpoint fires. It seems this is the relevant code from module.js in node_internals:

```
// Set breakpoint on module start
if (filename === resolvedArgv) {
  delete process._debugWaitConnect;
  const Debug = vm.runInDebugContext('Debug');
  Debug.setBreakPoint(compiledWrapper, 0, 0);
}
```

**Comment by roblourens** [comment]
Yeah, we expect it to break there, then we set breakpoints and continue. But if it takes a really long time to start up, then we stop waiting for that break event.

Can you set `"trace": true` in your launch config? It will create a log file and write the path in the debug console. Then upload that log file here. Thanks!

**Comment by bhughes339** [comment]
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1308497/vscode-node-debug2.txt)

Looks like line 84 is when it breaks on bootstrap.js. I halted the debug after reaching the breakpoint.

**Comment by roblourens** [comment]
Thanks for the log! I think I found it although I couldn't repro... please try it in the Insiders build tomorrow.

**Comment by bhughes339** [comment]
Thanks @roblourens. I tried today's Insiders build (1.17.0-1505884649) and I'm still having the issue. Here's my tracelog:

[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1318146/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
One more update, try again with the next build :)

**Comment by bhughes339** [comment]
Looks like this issue is resolved in today's Insiders build, at least for me. Thanks again @roblourens!
