### ISSUE TITLE
The window has crashed, from last update 1.15 to 1.16 every time i got this issue and VScode goes down

### ISSUE THREAD

**Issue by ccolumna** [Microsoft/vscode#34029]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
code-gnu-global|aus|0.2.2
githistory|don|0.2.3
Angular2|joh|2.7.0
cpptools|ms-|0.12.3
debugger-for-chrome|msj|3.2.1
java|red|0.9.0
nativescript|Tel|0.7.2
nativescript-ng2-snippets|www|2.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you give some more details about what you're seeing?
