### ISSUE TITLE
JavaScript formatter doesn't respect html.format.wrapLineLength

### ISSUE THREAD

**Issue by ms1111** [Microsoft/vscode#34028]
I understand Code is using js-beautify for both HTML and JS/TS formatting.

By setting `"html.format.wrapLineLength": 96` I can get HTML tags to wrap at ~96 chars. This seems to be equivalent to `html-beautify --wrap-line-length 96` on the command line.

But for JavaScript files, the formatter doesn't wrap lines.

On the command-line if I run `js-beautify --wrap-line-length 96` I get the behaviour I expect - the lines wrap. In Code, the lines don't wrap.

Sample input:
```
function hasTooManyParams(blah, blam, oneTwoThreeFour, fiveSixSevenEight, nineTenElevenTwelve, thirteenFourteenFifteen, eighteenTwelve) {
    var a = 1; var b = 'shouldbeonextline';
    if (a) {
     misalignedOne();
       properlyAlignedTwo();
    }
}
```

Output of `js-beautify --wrap-line-length 96`:
```
function hasTooManyParams(blah, blam, oneTwoThreeFour, fiveSixSevenEight, nineTenElevenTwelve,
    thirteenFourteenFifteen, eighteenTwelve) {
    var a = 1;
    var b = 'shouldbeonextline';
    if (a) {
        misalignedOne();
        properlyAlignedTwo();
    }
}
```

Actual output from Code formatter:
```
// First line is not wrapped
function hasTooManyParams(blah, blam, oneTwoThreeFour, fiveSixSevenEight, nineTenElevenTwelve, thirteenFourteenFifteen, eighteenTwelve) {
    // Variable assignments aren't split onto separate lines
    var a = 1; var b = 'shouldbeonextline';
    if (a) {
        // alignment is fixed, as expected
        misalignedOne();
        properlyAlignedTwo();
    }
}
```
- VSCode Version: 1.16.0
- OS Version: Mac OS X 10.12.6

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
We don't use js-beautify for our built in formatting. Our built-in formatter also does not have a line length setting. For that, an extension such as eslint or js-beautfy
