### ISSUE TITLE
VSCOde

### ISSUE THREAD

**Issue by nazmul202101** [Microsoft/vscode#34025]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
laravel-5-snippets|ate|0.0.1
php-autocomplete|bsc|0.4.2
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
file-icons|fil|1.0.5
auto-close-tag|for|0.4.3
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
path-autocomplete|ion|1.6.1
codeexplorer|Jul|0.3.3
HTMLHint|mka|0.3.3
motss-html-snippets|mot|0.3.0
sublime-keybindings|ms-|2.9.1
color-highlight|nau|2.3.0
laravel-blade|one|1.8.2
vscode-css-peek|pra|1.3.1
view-in-browser|qin|0.0.5
LiveServer|rit|2.0.0
vscode-icons|rob|7.12.0
vscode-sql-beautify|sen|0.0.4
stylelint|shi|0.29.0
css-auto-prefix|spo|0.1.4
code-spell-checker|str|1.3.9
open-in-browser|tec|1.1.0
lorem-ipsum|Tyr|1.0.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
What's your problem?
