### ISSUE TITLE
MacOS: Cannot edit files that require root access to edit (EACCESS: permission denied)

### ISSUE THREAD

**Issue by raineluntta** [Microsoft/vscode#34021]
- VSCode Version: 1.16.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. $ code /etc/hosts
2. Make your changes
3. Try to save

Reproduces without extensions: Yes

How I would like it to behave:

1. $ code /etc/hosts
2. Make your changes
3. Try to save
4. Asks for authentication
5. Save successful

I have the same problem with NFS mounted directories etc. In Atom the app asks for my username and password to save, but VS Code just gives this error. Would it be possible to have the Atom's functionality in VS Code as well? Would be superb.

EDIT: Wanted to add that the reason I'd like to have this functionality is that I don't like (and its not recommended) to run VS Code as root. So the result is that any file that needs root access to edit is uneditable with VS Code.

**Comment by roblourens** [comment]
Yeah, we have a longstanding issue to improve this experience, https://github.com/Microsoft/vscode/issues/1614
