### ISSUE TITLE
[folding] markers of regions that intersect with the cursor should be visible, regardless of mouse hover

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3402]
Testing #2994

**Comment by aeschli** [comment]
@joaomoreno Can you add a screenshot?

**Comment by aeschli** [comment]
Ah, now I get it, so depending on the cursor position, you want the folding icons be always visible for the folding regions that cover that position?

**Comment by joaomoreno** [comment]
Yes exactly, sorry for the confusion.

**Comment by haisapan** [comment]
I want it too, if can add settings to make the folding icon always visible?

**Comment by aeschli** [comment]
We now have a setting to always show the folding markers.
`"editor.showFoldingControls": "always"`

No plans to add cursor aware folding markers
