### ISSUE TITLE
JSX syntax highlighting problem with default parameters.

### ISSUE THREAD

**Issue by nsnsoft** [Microsoft/vscode#34024]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|0.23.1
vscode-icons|rob|7.12.0

JSX syntax highlighting stops working when adding default value to destructured parameter.

**No syntax highlighting:**
![selection_033](https://user-images.githubusercontent.com/12295628/30211992-b32f2136-94c0-11e7-94e8-526a9dbb8304.png)

**Works fine:**
![selection_034](https://user-images.githubusercontent.com/12295628/30212028-d2205d12-94c0-11e7-975a-69d471990d05.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#512
