### ISSUE TITLE
Tab groups

### ISSUE THREAD

**Issue by Lev09** [Microsoft/vscode#34027]
Hello, 
In my practice I often open many tabs some for one task, some for other, and it's hard to work like this.
In MS Edge browser we have great feature, which allows us to save group of tabs and reopen when needed.
It would be great to have such a feature in VS Code.

**Comment by roblourens** [comment]
An extension could probably implement a version of this

**Comment by eamodio** [comment]
The [Restore Editors](https://marketplace.visualstudio.com/items?itemName=eamodio.restore-editors) extension can "kind of" do this (with insane hacks), but without real support for a "tabs" api this really can't be done in an extension today.

Re: https://github.com/Microsoft/vscode/issues/15178

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
