### ISSUE TITLE
Hang then crash by typing \\\\\\\\\\\\\\\\ in integrated terminal

### ISSUE THREAD

**Issue by jamesjryan** [Microsoft/vscode#34039]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.3
vscode-eslint|dba|1.3.0
tslint|eg2|1.0.1
cpptools|ms-|0.12.3
autoimport|ste|1.2.2
react-beautify|tai|0.3.0
vim|vsc|0.10.0
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Open integrated terminal
2. Type \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

All of vscode will immediately hang. You will not be able to use any of the UI.
After a while it will show a macOS dialog "The window is no longer responding" with options to Close/Keep Waiting/Reopen.

This will happen regardless of whether the current working directly is a git repository or not.

Using a mid 2015 MacBook Pro.

Using zsh terminal with oh-my-zsh framework. It is not possible to reproduce this issue in a regular terminal, either macOS Terminal.app or iTerm.

Reproduces without extensions: **Yes**/No

**Comment by Tyriar** [comment]
Pushed to master and release/1.16.

**Comment by jamesjryan** [comment]
Thanks for dealing with this so promptly @Tyriar 👍
