### ISSUE TITLE
WorkspaceStats performance considerations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34033]
Stumbled over this, a couple of ideas/questions..

* run with a delay on not immediately on startup, today this seems to be on the critical path
* we read `N` workspace folders, with each `M` files, and check `K` patterns against that...
* can this be an extension?

**Comment by jrieken** [comment]
related to #38080

**Comment by bpasero** [comment]
@chrmarti fyi I converted workspace stats to be a workbench contribution with the new support of instantiating these contributions in a certain lifecycle phase (via https://github.com/Microsoft/vscode/commit/fa592ef424a374edba7b58d49e8b7c69ff8114bc). With my change, the stats are only computed and recorded after 3s.

**Comment by chrmarti** [comment]
Great, thanks @bpasero! Is there anything left to do here?

**Comment by bpasero** [comment]
@chrmarti I would say, up to @jrieken as author to decide.

**Comment by jrieken** [comment]
> we read N workspace folders, with each M files, and check K patterns against that...

I think we still loop a lot
