### ISSUE TITLE
Clean up from _readIsISOKeyboard change

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34031]
We should see how the new electron version works with regards to the ISO keyboard remapping and if things are OK we can delete that code on our end.

For now I pushed a change that will always return false for the call to `_readIsISOKeyboard`

**Comment by bpasero** [comment]
@alexandrudima fyi this has been working quite nicely for me!

**Comment by alexandrudima** [comment]
@bpasero Nice! I can remove the workaround code
