### ISSUE TITLE
It seems like that the terminal search doesn't support chinese !

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#34032]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Press Ctrl+~, then input win, like below:
![qq 20170908222830](https://user-images.githubusercontent.com/8075421/30216314-2d900746-94e5-11e7-8ac2-cd7f58f4a9fa.png)
2. Then press Ctrl+F, search "函数", like below:
![qq 20170908223220](https://user-images.githubusercontent.com/8075421/30216459-a9e81356-94e5-11e7-9dbb-8cdefbf7abba.png)

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
Reproduced a similar problem with Japanese characters on 1.15.1.

**Comment by Tyriar** [comment]
Created upstream issue: https://github.com/xtermjs/xterm.js/issues/1167

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37440
