### ISSUE TITLE
emmet not work under certain conditions

### ISSUE THREAD

**Issue by clor09** [Microsoft/vscode#34036]
- VSCode Version: 1.16.0
- OS Version: archlinux

Steps to Reproduce:

1. create a new html file
2. in body tag input 'div.form-group' and let vscode show popup which show something like following
![test](https://user-images.githubusercontent.com/20962135/30219866-fc5f6832-94ef-11e7-8e62-4ec024e1d615.png)
select the second night.css one , press enter
3. press tab, the 'div.form-group' wont be expanded, not sure if this is just a code snippet which expected raw 'div.form-group' in 'night.css' or a bug

**Comment by ramya-rao-a** [comment]
@clor09 Before Step 3 do you seen any suggestions?

In the absence of suggestions if you want to expand Emmet abrbeviations on tab then you need to set `emmet.triggerExpansionOnTab` to `true`

**Comment by clor09** [comment]
@ramya-rao-a oh, i see, so should this be the default settings? or may be a little bit strange that if i input the code all by hand    tab works but with 'suggestions' it wont

**Comment by ramya-rao-a** [comment]
>  so should this be the default settings

We did have `emmet.triggerExpansionOnTab` set to `true` by default before VS Code 1.15
There were [issues with using tab for expanding emmet abbreviations](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_tab-no-longer-the-default-emmet-expansion-key)


> if i input the code all by hand tab works but with 'suggestions' it wont

Can you elaborate on this?
When suggestions are present, pressing tab selects the first item in the suggestion list. This is general VS Code behaviour.
When suggestions are absent and `emmet.triggerExpansionOnTab` is set to `true`, pressing tab triggers Emmet expansion
