### ISSUE TITLE
Ctrl + n works in Terminal but Ctrl + p doesn't

### ISSUE THREAD

**Issue by W4RH4WK** [Microsoft/vscode#34030]
In VSCode, if I open a terminal (using Bash) I can go through my history using the cursor up / down key. This can usually also be done with `Ctrl + n` (up) and `Ctrl + p` (down) in a regular terminal. In VSCode these shortcuts are already used for different actions and are therefore not passed to the terminal (`Ctrl +n` opens a new, empty file, while `Ctrl + p` brings up the file selection).

At least so I thought. Turns out that while `Ctrl + n` is configured to open a new file globally, the shortcut is actually passed to the terminal. This, however, does not happen for `Ctrl + p`. I do not see how the default configuration for these keys results in a different terminal behaviour.

- VSCode Version: 1.16
- OS Version: Ubuntu 16.04 LTS

**Comment by Tyriar** [comment]
You can configure what VS Code commands override terminal ones by changing the `terminal.integrated.commandsToSkipShell` setting. Removing `workbench.action.quickOpen` from the list should send ctrl+P to the shell.

**Comment by W4RH4WK** [comment]
Thank that was exactly what I was looking for.
