### ISSUE TITLE
"No Results" text unreadable in Quiet Light theme

### ISSUE THREAD

**Issue by jenjac24** [Microsoft/vscode#34035]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16251
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3
csharp|ms-|1.12.1

The font color of "No Results" in the Quiet Light theme is a light pink and is impossible to read.  Please change this color.

---

Steps to Reproduce:

1. File->Preferences->Color Theme -> Quiet Light
2. Ctrl+F to find something in a file
3. Search for something that doesn't exist so you get the "no results" text next to the search text box
Expected: The text is readable
Actual: The text is unreadable because the text is too light

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Please update the latest version, this issue is already fixed.
