### ISSUE TITLE
[Question] workspaceFolders behavior

### ISSUE THREAD

**Issue by LaurentTreguier** [Microsoft/vscode#34038]
The description of the current `vscode.workspace.workspaceFolders` API is:
> List of workspace folders or undefined when no folder is open. Note that the first entry corresponds to the value of rootPath.

Why is it set to `undefined` and not simply an empty array when no folder is open ? This is the way `vscode.workspace.textDocuments` work if I'm not mistaken. I think it would make more sense to have the same behavior for both, and it wouldn't require always checking if `vscode.workspace.workspaceFolders` is defined or not before using it, while still clearly indicating when no folder is open.

Maybe there is a reason for this that I am not aware of, but it bugs me that those two APIs seemingly behave differently while doing the same kind of work.

**Comment by jrieken** [comment]
No special reasons, maybe an oversight or aligning with how `rootPath` works. Needs thinking and I am not sure we can change this now without breaking others (or at least introduce compile error for those that use strict null check)...

**Comment by bpasero** [comment]
Currently we do not allow to open a workspace (`.code-workspace`) with 0 folders, but we eventually might want to. However in that case an extension is not able to distinguish between an empty workspace (= nothing opened) and a `.code-workspace` with 0 folders. 

In the workbench we want to move away from having to distinguish between these two modes and simply let each client handle 0, 1 or N folders without having to think about how the workbench got into that state.

Ideally the same would be true for extensions and we would just always have an array with 0, 1 or N folders. Not sure however if there is usecases where an extension needs to explicitly distinguish the empty workspace case from the 0-folders case.

**Comment by jrieken** [comment]
Yeah, good point

**Comment by jrieken** [comment]
Closing this because of https://github.com/Microsoft/vscode/issues/34038#issuecomment-328444786
