### ISSUE TITLE
Editor does not auto-scroll to keep the cursor visible

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#34045]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
python|don|0.7.0
Go|luk|0.6.65
cpptools|ms-|0.12.3
perforce|sle|2.1.1
---

I believe this is a recent regression:

Steps to Reproduce:
1. open any source file with matching brackets far away from each other so one of them is outside the visible lines
2. jump to the matching bracket (editor.action.jumpToBracket)
3. cursor moves to the matching bracket correctly, but it's not outside the visible lines (editor does not auto-scroll to keep cursor visible as expected)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/32597
