### ISSUE TITLE
HTML syntax highlighting problem in php file

### ISSUE THREAD

**Issue by hkcoyant** [Microsoft/vscode#34040]
- VSCode Version: 1.16.0
- OS Version: Ubuntu 17.04 64-bit Gnome 3

Steps to Reproduce:

1. Open file .php whit html and php code

html highlighted is broken if the html code is between php

![screenshot from 2017-09-08 14-21-08](https://user-images.githubusercontent.com/6413893/30223370-fd3a5e8c-94a0-11e7-909d-b0d33b0d3ae5.png)

**Comment by roblourens** [comment]
This is https://github.com/atom/language-php/issues/246
