### ISSUE TITLE
Allow extensions to override command title and/or icon in menu placement (in package.json)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#34048]
- VSCode Version: Code - Insiders 1.17.0-insider (c354fca44896da2c9cad82b9bd9126f6658cfae8, 2017-09-08T05:24:34.310Z)
- OS Version: Windows_NT x64 10.0.16281
---

It would be very helpful (and powerful) if there was the ability to *override* a command's `title` and/or `icon` when a command was placed. This would allow for more context sensitive titles/icons without having to resort to multiple commands. 

There are multiple places in GitLens where I wished I had this ability (because often the multiple commands just isn't worth the extra complexity) -- where I want a different title for the command palette, editor context, etc, etc.

This is somewhat similar to https://github.com/Microsoft/vscode/issues/32526 - @jrieken I think this could also address that one -- since you could just have the same command listed twice with a different title/icon based on the `when` clause

Here is my ideal example below:
```js
"commands": [
    {
        "command": "gitlens.stashSave",
        "title": "Stash All Changes",
        "category": "GitLens",
        "icon": {
            "dark": "images/dark/icon-stash.svg",
            "light": "images/light/icon-stash.svg"
        }
    }
],
"menus": {
    "commandPalette": [
        {
            "command": "gitlens.stashSave",
            "when": "gitlens:enabled",
            "icon": {
                "dark": "images/dark/icon-stash-all.svg",
                "light": "images/light/icon-stash-all.svg"
            }
        }
    ],
    "scm/resourceGroup/context": [
        {
            "command": "gitlens.stashSave",
            "when": "gitlens:enabled",
            "title": "Stash Changed Files"
        }
    ],
    "scm/resourceState/context": [
        {
            "command": "gitlens.stashSave",
            // listHasMultipleSelections of course doesn't exist today but it would be SO nice :)
            "when": "gitlens:enabled && !listHasMultipleSelections",
            "title": "Stash File"
        },
        {
            "command": "gitlens.stashSave",
            // listHasMultipleSelections of course doesn't exist today but it would be SO nice :)
            "when": "gitlens:enabled && listHasMultipleSelections", 
            "title": "Stash Files"
        }
    ]
}
```

I've also included in this example `listHasMultipleSelections` (or something like it -- no selection, single selection, multiple selections would be ideal) that would be very helpful to have again to be more context-sensitive.

Reproduces without extensions: Yes/No

**Comment by eamodio** [comment]
FYI, the example provided above is very simplistic, but this is a real world problem for me with GitLens and others. Changing the title/icon based on a condition would allow for drastically reduced complexity for extension authors and better usability for users through better contextual titles/icons.

To achieve this effect today, you need to create duplicate commands for all the possible usages where the title or icon should change. In GitLens I take that approach in some cases, but in others the extra complexity is just too high to pay the price of all the duplication.

**Comment by eamodio** [comment]
😢 I really wish this (or something similar) can be reconsidered. I really find dealing with commands with many different contexts very difficult to deal with and leads to so much duplication in the `package.json`

**Comment by eamodio** [comment]
@jrieken Any chance we can revisit this? I still would find it valuable to be able to at least change the title of a command in its placement.

**Comment by jrieken** [comment]
:-1: this is still against the design of the commands and how we utilise them. And you still didn't answer the question why it should be called "Save" in the global menu and "Delete" in the context menu.

**Comment by Tyriar** [comment]
I think I'm in the right place... I'd also like something like this so I could contribute several numbered commands to the context menu based on settings for https://github.com/Tyriar/vscode-windows-terminal/issues/5

For example:

```
"windowsTerminal.customMenuItem1.enabled": true,
"windowsTerminal.customMenuItem1.name": "PowerShell"
"windowsTerminal.customMenuItem2.enabled": true,
"windowsTerminal.customMenuItem2.name": "MSYS2"
```

With context contributions:

```json
"menus": {
  "explorer/context": [
    {
      "command": "vscode-windows-terminal.customMenuItem1",
      "when": "config.windowsTerminal.customMenuItem1.enabled",
      "title": "Open in Windows Terminal (${config.windowsTerminal.customMenuItem1.title})"
    }
    {
      "command": "vscode-windows-terminal.customMenuItem2",
      "when": "config.windowsTerminal.customMenuItem2.enabled",
      "title": "Open in Windows Terminal (${config.windowsTerminal.customMenuItem2.title})"
    }
  ]
}
```

Without something like this I think I need to either just stick with numbers to differentiate them in the context menu which are not user friendly, or enumerate every common possibility and uncommon titles just miss out.

**Comment by eamodio** [comment]
Allowing dynamic titles in this way (from context key values) would be awesome -- GitLens has the same issue when dealing with opening things (commits, files, branches, repos, etc) on a remote (GitHub, Bitbucket, etc). Right now I use `Open x on Remote`, but it would be awesome to be able to much more easily say `Open x on GitHub` when I know that the remote is GitHub.

**Comment by Tyriar** [comment]
@eamodio would GitLens be able to fill in GitHub, Bitbucket, etc. using something before activation?

**Comment by eamodio** [comment]
No, but we already are already evaluating whether or not to show the menu based on those context keys.

**Comment by zhfnjust** [comment]
we need this

```json

"commands": [
    {
        "command": "gitlens.stashSave",
        "title": "Stash All Changes",     //long name
        "category": "GitLens",
        "icon": {
            "dark": "images/dark/icon-stash.svg",
            "light": "images/light/icon-stash.svg"
        }
    }
],
"menus": {
    "commandPalette": [
        {
            "command": "gitlens.stashSave",
            "when": "gitlens:enabled",
            "icon": {
                "dark": "images/dark/icon-stash-all.svg",
                "light": "images/light/icon-stash-all.svg"
            }
        }
    ],
    "view/item/context": [
        {
            "command": "gitlens.stashSave",
            "when": "gitlens:enabled",
            "title": "Stash"    //it's a  button, short name
        }
    ],
}

```

**Comment by jrieken** [comment]
We have no plans for placement specific titles or icons. All information that is needed to present a command must be on the command itself. If it would be on the menu, that information is locked-in, needs to be potentially duplicated per placement, and is a show-stopper for customizable menus. 

This doesn't mean that there is no need for a _short name_  and _long name_ but it must be on the command, not the menu. With that menu implements decide what property to use, e.g already today the command palette menu uses the title and category property whereas other menus only use the title property.  

In fact, internally we added support for `shortTitle` which complements `title` (https://github.com/microsoft/vscode/commit/af0c01b1e3617a41f6da30bd1525d8d91dabfc85). I will close this issue and create a new issue to track making this usable by extensions.
