### ISSUE TITLE
Dead Slow file/folder deletion

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#34044]
File/Folder deletion is dead slow and it waits for a long time with ui get blocked.... by selecting folder or file and deleting using delete key or shift + del works perfectly fine but deleting right click option selecting delete is dead ...dead slow.... 

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|2.2.0
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
icon-fonts|idl|1.8.1
debugger-for-chrome|msj|3.2.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@prasanthnv so you say it is slow when using the mouse + menu but fast when using keyboard?

**Comment by prasanthnv** [comment]
@bpasero Yes....

**Comment by bpasero** [comment]
@prasanthnv are any actions from the context menu slow? are other menus slow as well?

**Comment by prasanthnv** [comment]
@bpasero nope.... only delete action is slow

**Comment by bpasero** [comment]
@prasanthnv maybe its a problem with moving the file to trash, can you check if the file ends up in trash when you use keyboard?
