### ISSUE TITLE
vscode-insiders replaced my user-settings with workspace settings

### ISSUE THREAD

**Issue by josiahbgrace** [Microsoft/vscode#34046]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider) (aed2c7cc5c6ab2a092e524a59f82d17fc9348fc0)
- OS Version: Sierra 10.12.6

Downloaded the latest vscode-insiders. I have two projects open, both with user setting and workspace settings (one is a notes folder, the other is a js project). 

Suddenly, the screen blipped and brought my mini-map back and reduced the font size. When I checked what happened, my user-settings globally had been replaced with my workspace settings 

```
{
  "workbench.colorCustomizations": {
    "statusBar.background": "#78dce8",
    "statusBar.noFolderBackground": "#78dce8",
    "statusBar.debuggingBackground": "#78dce8"
  },
  "vim.disableAnnoyingNeovimMessage": true,
  "workbench.iconTheme": "Monokai Pro (Filter Spectrum) Icons"
}
```

I wish I had been better about saving my user settings :( I don't think I can get them back, unfortunately.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Do you see the dropdown in the top right corner of the settings editor? Is it possible that you're just viewing the workspace settings?

![image](https://user-images.githubusercontent.com/323878/30232218-8ac408aa-94a3-11e7-85fe-3df3ae89d187.png)

**Comment by josiahbgrace** [comment]
Yeah, unfortunately I am viewing the user-settings. Verified in ~/Application Support/Code - Insiders/Users/settings.json as well

**Comment by roblourens** [comment]
Sorry that happened. Is it possible that an extension was involved? Which ones do you have installed?

**Comment by josiahbgrace** [comment]
```
Shan.code-settings-sync
Tyriar.theme-sapphire
WallabyJs.quokka-vscode
cduruk.thrift
christian-kohler.path-intellisense
donjayamanne.python
eamodio.gitlens
esbenp.prettier-vscode
flowtype.flow-for-vscode
leizongmin.node-module-intellisense
lukehoban.Go
monokai.theme-monokai-pro-vscode
mrmlnc.vscode-scss
ms-vscode.sublime-keybindings
msjsdiag.debugger-for-chrome
naumovs.theme-oceanicnext
vscodevim.vim
```
It's fairly sparse. Settings Sync seems potential, but I don't have it set to do any sort of auto-upload/download (and really don't use it).

**Comment by roblourens** [comment]
Yeah settings-sync seems possible but I know it's a popular one... Please let us know if it happens again!

**Comment by roblourens** [comment]
>I have two projects open

Do you have two projects in one (multiroot) window? Or in two windows?

**Comment by josiahbgrace** [comment]
I have two separate windows for this (not multiroot)

**Comment by sandy081** [comment]
Hmm sorry for what happened. I do not think we do any such replacements without a user action except while transitioning from single folder to a multi folder workspace in which we copy folder settings to workspace settings. 

I suspect this could be external. Is there any possibility that you performed any actions in VS Code before this happened?

**Comment by josiahbgrace** [comment]
Unfortunately, I haven't been able to replicate. I suspect it has to do with two open vscode windows, each with settings open. And the extension vscodevim, because I have it set up to change my status bar color in different vim modes (which modifies the setting.json file). I will keep track of this, and file if I can ever replicate (now that I version control my settings.json 😄 ), but for now I'll close it.
