### ISSUE TITLE
Intellisense should put more weight on local objects

### ISSUE THREAD

**Issue by mikepugh** [Microsoft/vscode#34049]
JavaScript intellisense has a lot of objects available via global scope and the various APIs available. While those options are good, I believe intellisense should give more weight to locally defined/imported objects & functions and display those at the top of the list.

- VSCode Version: 1.16.0
- OS Version: Windows 10 Enterprise 1511

Steps to Reproduce:

1. Create a basic app using something like create-react-app
2. Create a file `WorkerActions.js` that `export const WorkerActions = () => true;`
3. Within `App.js`, add `import {WorkerActions} from "./WorkerActions"`
4. Somewhere in the code, type `WA` and activate intellisense, notice that a bunch of WebAPI stuff pops up and `WorkerActions` is far down the list, beneath items like `WaveSharperNode` and `WebGLActiveInfo`

Example:
![image](https://user-images.githubusercontent.com/1666933/30230211-48afd81c-94b3-11e7-8f99-ae676b18e46d.png)

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Yes, TypeScript/JavaScript can do that by using the `sortIndex`

**Comment by mjbvz** [comment]
Confirmed that local completions and global completions currently both have the same weight. Opened https://github.com/Microsoft/TypeScript/issues/18398 to track this upstream
