### ISSUE TITLE
HTML highlight not recognized after open an PHP if statement using braces

### ISSUE THREAD

**Issue by h-stivalet** [Microsoft/vscode#34041]
- VSCode Version: 1.16
- OS Version: ubuntu 17.04

Steps to Reproduce:

1. Editing a combine HTML/PHP view
2. Adding a PHP IF statement or a FOR loop using braces
3. After opening the statement brace "{" and closing PHP "?>" in order to insert HTML, the PHP closing tag is not detected and all the following HTML acts like it continues in PHP mode, so HTML code is not highlighted and snippets stop working.

Reproduces without extensions: Yes

Extensions:
PHP Intelephense 0.7.2
HTML Snippets 0.1.0
![bug](https://user-images.githubusercontent.com/16110371/30223231-9367393c-948f-11e7-8b1a-2f3305f9e627.png)

**Comment by roblourens** [comment]
This is https://github.com/atom/language-php/issues/246
