### ISSUE TITLE
Substitute variables in launch configuration keys (and not only in values)

### ISSUE THREAD

**Issue by nbstar** [Microsoft/vscode#34059]
- VSCode Version: 1.15.1  
- OS Version: Win7  

Feature description：
It would be nice to use the environment variable $ {env: variable} in launch.json sourceFileMap, like using the built-in variable $ {workspaceRoot}.  

The present situation is that we can write $ {env: variable} in sourceFileMap, but it is not replaced by real path like $ {workspaceRoot}.  

So, when debugging with cpptools extension for c++ program，vscode pops up the following message box:
```
Error: Unable to open 'main.cpp': File not found (\usr1\pDTest\demo\main.cpp). Create File Cancel
```

The sourceFileMap is very simple:   
```
"sourceFileMap": {
    // "remote": "local"
    
    // This way works well
    // "/usr1/pDTest/demo" : "D:\\demo"
    
    // This way does not work
    "/usr1/{env:USERNAME}/demo" : "D:\\demo"
},
```
This feature is useful for collaborative development of multiple programmers. we can push launch.json on git repo, and do not need everyone to modify it.

**Comment by isidorn** [comment]
Yes, currently we are only resolving the values of objects in the configuration, not the keys (which is what you want).
We accept PRs that elegantly fix this, code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L194

**Comment by OkkeHendriks** [comment]
@nbstar  I was wondering if you have found a workaround for this?

**Comment by weinand** [comment]
@isidorn since VS Code's use of JSONs sometimes has values on the left hand side (as keys), we should consequently support variable substitution there too.

I assume this feature is low-hanging fruit?

**Comment by isidorn** [comment]
@weinand should not be too complex

**Comment by isidorn** [comment]
@dbaeumer note that we now also resolve keys not only values in configuraitons since this also affects tasks.

**Comment by aeschli** [comment]
Verified that variables are substitured in both values and keys.
