### ISSUE TITLE
[scss] Wrong autocomplete for build function in scss

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#34053]
I write in scss file:
```
.example {
color: darken
}
```
after write darken I hit `tab` key to select value from autosuggest list, and finally i get:
```
color: darken(: , : 0)
```
instead of:
```
color: darken($color , $amout);
```
This same situation I have in all build functions, like for example:
```
str-index(: "", : "s")
str-length(: "")
nth(: , : )
```

**Comment by roblourens** [comment]
Where does the suggestion come from? Is this an emmet feature? @ramya-rao-a

**Comment by ramya-rao-a** [comment]
That's coming from the css completions
