### ISSUE TITLE
Start up slow - 09/07/17

### ISSUE THREAD

**Issue by soitof** [Microsoft/vscode#34050]
- VSCode Version: <code>Code - Insiders 1.17.0-insider (aed2c7cc5c6ab2a092e524a59f82d17fc9348fc0, 2017-09-08T10:13:13.694Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)</code>
- Memory (System): <code>16.00GB (0.64GB free)</code>
- Memory (Process): <code>215.42MB working set (0.00MB peak, 176.83MB private, 142.97MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|66|
|main|app.isReady => window.loadUrl()|177|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|425|
|renderer|require(workbench.main.js)|434|
|renderer|create extension host => extensions onReady()|704|
|renderer|restore viewlet|268|
|renderer|restore editor view state|748|
|renderer|overall workbench load|995|
|main + renderer|start => extensions ready|1862|
|main + renderer|start => workbench ready|2134|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`35b4_main.cpuprofile.txt`
-`35b4_renderer.cpuprofile.txt`

[35b4_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1289078/35b4_main.cpuprofile.txt)
[35b4_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1289079/35b4_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
I couldn't find anything suspicious in this profile. If you have been alerted it might have been false alarm. If are interesting in our performance work, be assured it is an on-going theme and you can find all performance issues using the perf-label: https://github.com/Microsoft/vscode/issues?utf8=✓&q=%20is%3Aissue%20label%3Aperf%20

Thanks and Happy Coding
