### ISSUE TITLE
Encode platform requirement in configuration

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34057]
To support better settings search, we need to produce a json file of all settings in a particular vscode build. To do this I'm starting Code in a mode where it will retrieve all configuration details from the ConfigurationRegistry and write them out. But some settings are only registered on certain platforms or OS versions. e.g. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.contribution.ts#L365

I want to change this so that these settings are still known by the configuration registry, so we can retrieve them along with their platform requirements, but are still disabled/hidden when not on a supported platform. Otherwise, windows-only settings would be excluded if the file is produced on a Mac. 

I will try to come up with a PR proposal, but I'm open to suggestions @aeschli or @bpasero?

**Comment by bpasero** [comment]
I am fine if there is a way to define a platform filter when I register a setting 👍

**Comment by aeschli** [comment]
Something like a 'platform' file would make sense also for extensions to have.
@sandy081 FYI

**Comment by sandy081** [comment]
Makes sense to me. Think about exposing the property in the extension point too. You have to make sure that such properties are filtered by internal configuration service APIs
- https://github.com/microsoft/vscode/blob/master/src/vs/platform/configuration/node/configurationService.ts#L18
- https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/configuration.ts#L333

**Comment by roblourens** [comment]
Sure. It's easy to imagine how filtering by platform might look. But I'm not sure how much flexibility to provide for settings like this one: https://github.com/Microsoft/vscode/blob/69bc9d6ac927e70a9b2f48eeb0d91d308e43a941/src/vs/workbench/electron-browser/main.contribution.ts#L389 that require a certain OS version and Electron version. Does anyone know of any other settings that have requirements like this? Maybe the electron version check is obsolete.
