### ISSUE TITLE
Go to bracket stopped working after update to 1.16

### ISSUE THREAD

**Issue by azbatuk** [Microsoft/vscode#34056]
Go to Bracket "Ctrl + Shift + \ " stopped working after 1.16 update is installed. The cursor goes to the  matching bracket but the screen does not scroll to it.

- VSCode Version: 1.16
- OS Version: Windows 10

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Fixed in Insiders now. https://github.com/Microsoft/vscode/issues/32597
