### ISSUE TITLE
cannot attach remote node process

### ISSUE THREAD

**Issue by Xaqron** [Microsoft/vscode#34054]
- VSCode Version: 1.16.0
- OS Version: Ubuntu 16.04.3 LTS (xenial)

Steps to Reproduce:

1. Host a simple hello world node.js app on a remote machine (ip: `a.b.c.d`)
2. Start app with this command: `$ node --inspect=0.0.0.0:9229`
3. Configure vscode to attach remote process. Here is `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "remote debug",
            "address": "ws://a.b.c.d/bde3bbb8-410d-48ca-949e-a1e07980882f",
            "port": 9229,
            "localRoot": "/home/xaqron/remote-debug",
            "remoteRoot": "/home/xaqron/remote-debug",
            "sourceMaps": true,
            "protocol": "inspector",
            "restart": true
        }
    ]
}
```

vscode stuck trying to connect.

Reproduces without extensions: Yes

Note: Using Google chrome I'm able to attach the remote node process (chrome://inspect).

**Comment by roblourens** [comment]
'address' is actually the IP address of the remote machine, not the websocket address (so, probably `a.b.c.d`.)
