### ISSUE TITLE
java syntax highlight break on annotation interface

### ISSUE THREAD

**Issue by tnclong** [Microsoft/vscode#34058]
- VSCode Version:

1.16.0

- OS Version:

macOS 10.12.3

- Steps to Reproduce:

<img width="756" alt="screen shot 2017-09-09 at 8 55 40 am" src="https://user-images.githubusercontent.com/10040765/30235628-16088118-953d-11e7-92f7-37eea775569f.png">

- Reproduces without extensions

Yes

**Comment by aeschli** [comment]
This issue was moved to atom/language-java#109
