### ISSUE TITLE
Random error lines

### ISSUE THREAD

**Issue by TwistenTiger** [Microsoft/vscode#34067]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
javadebugger|don|0.1.3
python|don|0.7.0
java-debug|DSn|0.0.2
vscode-javac|geo|0.0.46
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
java|red|0.9.0
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Phrohdoh** [comment]
@TwistenTiger I suspect the VSCode team can't derive anything actionable from this ticket.

You haven't supplied steps to reproduce the issue, screenshots of what you are seeing, etc.

**Comment by TwistenTiger** [comment]
This is the error I was talking about random popping red line errors please help me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Phrohdoh** [comment]
Unfortunately there is no screenshot in your comment.
As far as I know you cannot attach files to GitHub via email.
