### ISSUE TITLE
"Developer: Inspect TM Scopes" command not working with "editor.tokenColorCustomizations" defined in User Settings

### ISSUE THREAD

**Issue by shepelevstas** [Microsoft/vscode#34065]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.2
django-html|bib|1.2.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.2
vscode-simpler-icons|dav|1.4.0
python|don|0.7.0
vscode-html-css|ecm|0.1.8
eppz-code|epp|1.2.41
vsc-material-theme|Equ|1.0.2
file-icons|fil|1.0.5
sublime-babel-vscode|jos|0.2.8
vscode-icon-theme|jtl|1.5.0
theme-dark-plus-contrast|k3a|0.1.101
vscode-colorize|kam|0.6.4
graphql-for-vscode|kum|1.6.0
vscode-simple-icons|Lau|1.6.0
vetur|oct|0.9.7
seti-icons|qin|0.1.3
prettier-now|rem|1.4.8
LiveServer|rit|2.0.0
vscode-icons|rob|7.12.0
ActiveFileInStatusBar|Ros|1.0.3
trailing-spaces|sha|0.2.11
vscode-fileutils|sle|2.6.2
vim|vsc|0.10.0
html-css-class-completion|Zig|1.9.0

(24 theme extensions excluded)

---

Steps to Reproduce:

1. put some "textMateRules" in "editor.tokenColorCustomizations" in USER SETTINGS
2. toggle "Developer: Inspect TM Scopes" on
You will see a small pop up window with "Loading..." in it, and that's it.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@aeschli The inspect TM scopes widget uses `themeService.getColorTheme()`. Perhaps that call should be adjusted or something ?

**Comment by aeschli** [comment]
`themeService.getColorTheme()` contains the rules including the custom rules.
![image](https://user-images.githubusercontent.com/6461412/30317452-772adbfc-97aa-11e7-8588-9ae75e754f6f.png)

It must have something to do with the rules or the grammar

@shepelevstas Please provide a reproducible example:
- your `"editor.tokenColorCustomizations"` setting
- the language id and the content of the editor you are using 'Inspect TM Scope' in.
