### ISSUE TITLE
[i18n] Curly quotes

### ISSUE THREAD

**Issue by glixlur** [Microsoft/vscode#34061]
- VSCode Version: 1.16.0
- OS Version: macOS Sierra

Currently, all localized strings in French locale uses straight quotes (`'`):

![image](https://user-images.githubusercontent.com/8125011/30237082-dffab162-94f7-11e7-8e33-8ec468fee895.png)

while in most macOS apps, the curly quote `’` is used correctly:

![image](https://user-images.githubusercontent.com/8125011/30237108-cf97052c-94f8-11e7-9673-c9ab6e899f1b.png)

Due to the widespread usage of quotation mark in the French language, this has been bugging me for a while.

**Comment by johnliu2016** [comment]
@lukaschal, it looks so https://github.com/Microsoft/vscode/blob/master/i18n/fra/src/vs/code/electron-main/menus.i18n.json

`"miSaveWorkspaceAs": "&&Enregistrer l’espace de travail sous...",
"miAddFolderToWorkspace": "&&Ajouter un dossier à l'espace de travail...",` 

Please review the wide usage of the quotation mark in French implement conssitency

**Comment by lukaschal** [comment]
Quote ( ' ) is commonly and widely used character in a french language.

**Comment by lukaschal** [comment]
So, what is a suggestion in this case ? Use curly quote ( ’ ) in a all VSCode french translations ?

**Comment by glixlur** [comment]
Only for apostrophes. It is already used in some phrases in the codebase.

In addition, [the space before `?`, `!`, `;` and `:` is written as a half-width space](https://crowdagger.github.io/textes/articles/heuristique.html) (0x202F).

I can handle this issue, but the current translations are machine generated and I cannot find the source file...

**Comment by lukaschal** [comment]
Current translations are present in a transifex.

https://www.transifex.com/microsoft-oss/

**Comment by Tyriar** [comment]
I'm assuming this is fixed based on @lukaschal's comment? Closing for housekeeping purposes - these sorts of issues should probably also just be handled in transifex in the future.
