### ISSUE TITLE
Right-click option (in VSCode) for "Open folder in VSCode"

### ISSUE THREAD

**Issue by shadycake** [Microsoft/vscode#34069]
In the sidebar, I would like to suggest the feature to be able to right click on a folder and click something along the lines of "Open folder in VSCode".
![image](https://user-images.githubusercontent.com/28223854/30239401-bdb90c5a-9553-11e7-8d6c-8f571e0fdc3a.png)
The right click menu in question is shown in the picture above, after having clicked that option VSCode will change to this:
![image](https://user-images.githubusercontent.com/28223854/30239436-541da17e-9554-11e7-9f7f-3c029a5f52f3.png)
I may suggest also having two options, one for open in a new window, and one for open in current window.

**Comment by roblourens** [comment]
There is a good extension for this, https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance
