### ISSUE TITLE
git partial staging not working

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#34060]
- VSCode Version: 1.16
- OS Version: Windows 10

Steps to Reproduce:

1. open a modified file in git working tree
2. select some changed lines
3. from the `...` menu (top right) select "Stage selected ranges"

It shows an error

> Git: Illegal value for `line`

And in the output console panel:

```
Using git 2.12.2.windows.2 from C:\Program Files\Git\cmd\git.exe
git rev-parse --show-toplevel
git fetch
git config --get commit.template
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
fatal: no upstream configured for branch 'master'

git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
fatal: no upstream configured for branch 'master'

git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git show HEAD:.../package.json
```

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Does it happen with **any** range you select?

**Comment by laggingreflex** [comment]
Seems to be working now, not sure what was going wrong. Closing for now, will reopen if I can repro again
