### ISSUE TITLE
Open Folder fails if no files in said folder

### ISSUE THREAD

**Issue by Vultraz** [Microsoft/vscode#34062]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.3
code-spell-checker|str|1.3.9

---

Steps to Reproduce:

1. File -> Open Folder. Select a folder with no files, only sub-folders.
2. Selected folder will not open and you end up at the Welcome screen.

Reproduces without extensions: Did not test, but should.

**Comment by bpasero** [comment]
I cannot reproduce, can you attach a recording of how this looks for you?
