### ISSUE TITLE
ibus-gtk works only with `GDK_SCALE=1`

### ISSUE THREAD

**Issue by aizuddineismail** [microsoft/vscode#34079]
Hello. The problem I'm facing now is when I installed ibus-gtk, I cannot type Chinese characters or any other foreign language characters in VS Code. The purpose of ibus-gtk is to allow the candidate panel to appear as I type. Here are two screenshots of the problem.

![problem2](https://user-images.githubusercontent.com/25891418/30241973-2aef5ca4-95c0-11e7-86c5-f7d493fae7dd.png)

![problem](https://user-images.githubusercontent.com/25891418/30241972-1e1d7ca4-95c0-11e7-89bc-707085e9fcc5.png)

As you can see from the first image, the candidate panel appears at the bottom of the screen. However, if I install ibus-gtk, I cannot type chinese characters in VS Code.

I don't know how to fill in the Steps to Reproduce. Sorry.

--The End--

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.1
vscode-icons|rob|7.12.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by krupenja** [comment]
Also reproducible with ibus-uniemoji (ibus input method for entering emoji and special characters). VSCode  1.29.1, Ubuntu 18.10.

**Comment by yoyoys** [comment]
slack has similar problem, I think it's GDK3's problem, `GDK_SCALE=1 /usr/bin/slack` solve problems, but this trick doesn't work on vscode.

**Comment by rongcuid** [comment]
Confirm that `GDK_SCALE=1` also works for `fcitx` problem, #58735. With this option candidate window is at correct location.

**Comment by yoyoys** [comment]
for easily usage, use `GDK_SCALE=1` to open a vscode window, then other window doesn't need add `GDK_SCALE`

otherwise, if there has any vscode window doesn't open with `GDK_SCALE=1` option, this will not effect.

**Comment by rebornix** [comment]
As shared above, it's an issue with upstream and to workaround this issue you need to run vscode from command line with prefix `GDK_SCALE=1`.
