### ISSUE TITLE
Upgrading to 64 bits version requires some extensions to be reinstalled

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#34075]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
danielo-node-snippets|dan|1.0.3
markdown-table-prettify|dar|1.1.1
vscode-eslint|dba|1.3.0
githistory|don|0.2.3
gitlens|eam|4.4.3
EditorConfig|Edi|0.10.1
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.4
JSDocTagComplete|Hoo|0.0.2
badges|idl|1.0.7
sublime-babel-vscode|jos|0.2.8
vscode-github|Kni|0.19.0
vue|liu|0.1.5
lit-it|moh|1.2.12
debugger-for-chrome|msj|3.2.1
vetur|oct|0.9.7
vuehelper|oys|0.1.0
vscode-docker|Pet|0.0.16
material-icon-theme|PKi|2.2.0
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.3
code-spell-checker|str|1.3.9
vscode-react-redux-snippets|tha|0.3.3
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Have 32 bits Windows version of VSCode installed
2. Upgrade it to the new 64 bits version

Reproduces without extensions: No

Hello,
I'm reporting this not expecting any fix, but to help other users with the same problem.
I had the 32 bit version of VSCode installed. I upgraded it to the 64 bits version expecting to loose all y configurations and extensions. To my surprise that was not the case, and all my extensions an configurations were kept 👍 
However, the first thing I noticed was the lack of syntax highlighting on VUE files. After toying a bit with Vetur extension I decided to uninstall - reload - install - reload. After that it started to work properly. The same thing happened with "Debugger for chrome": The extension was failing, so I uninstalled - reload- installed - reload and it started to work too.

I think it's worth mention this situation so people don't get mad about it.

Regards

**Comment by egamma** [comment]
pls investigate whether we can reproduce and need to document this as a limitation

@octref  pls see 
>However, the first thing I noticed was the lack of syntax highlighting on VUE files. After toying a bit with Vetur extension I decided to uninstall - reload - install - reload. After that it started to work properly. 

@roblourens 
>The same thing happened with "Debugger for chrome": The extension was failing, so I uninstalled - reload- installed - reload and it started to work too.

**Comment by roblourens** [comment]
> The extension was failing

@danielo515 Can you explain the problem a little more?

**Comment by roblourens** [comment]
I tried the upgrade, and all extensions still work fine for me.

**Comment by danielo515** [comment]
@roblourens it was complaining about some file missing, but i didn't recorded it. I expect other extensions to fail so i hope to provide better report. in any case, as I said I wanted to warn other users more than ex pect a fix

**Comment by roblourens** [comment]
> as I said I wanted to warn other users more than ex pect a fix

Well, I have no idea why that would happen, so I would like to get to the bottom of it and fix it :)

Would really appreciate if you can try it again and record any error messages you see. Are you sure it was a problem with the extension and not with your app or launch config?

**Comment by danielo515** [comment]
> Are you sure it was a problem with the extension and not with your app or launch config?
I'm pretty sure because the way I fixed it: uninstalling and installing the extension. Nothing else has changed. In the case of the chrome extension it was trying to access some internal extension file, don't remember which one

**Comment by octref** [comment]
@danielo515 You have this extension installed, which is in conflict with Vetur: https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue

Just uninstall it and you should be good to go.

**Comment by danielo515** [comment]
@octref Vetur is actually working. That extension is disabled. But you're right, I'll uninstall it.

Regards

**Comment by octref** [comment]
Thanks for letting me know. Closing to mark as resolved.

**Comment by danielo515** [comment]
@octref I'm fine if you close the issue, but I'm not sure if you catched the actual topic of the report.
Regards

**Comment by octref** [comment]
Oh I see. Maybe it's worth digging deeper @roblourens.
For Vetur I've had a few reports saying Language Server dependencies are not installed correctly when updating / installing. After a manual install of the dependency or reinstall things work properly.

IIRC all of such issues come from Win.

**Comment by roblourens** [comment]
I don't think there's anything we can do unless you're able to repro this and record the error messages. Please try it again if you get the chance and let us know what the error messages are.
