### ISSUE TITLE
Youtube Integration with VS Code

### ISSUE THREAD

**Issue by rushikesh90** [Microsoft/vscode#34072]
While learning lot of JavaScript libraries or frameworks, I use YouTube  coding tutorials. But opening YouTube in browser and working with tutorial in VS code is difficult. If VS code can have integrated youtube same as integrated terminal, it will be great help.

**Comment by roblourens** [comment]
An integrated browser has been a common request but I don't think it fits in to VS Code's general way of doing things. I suggest you arrange your Code and browser windows so you can see both 😁
