### ISSUE TITLE
Create undo stops also based on time between edits

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode#34073]
In Sublime, if I type `a b c` and then hit `Undo`, it deletes the `c`, but in VSCode it deletes the entire line. 

Is there a parameter to modify this behavior?

**Comment by alexandrudima** [comment]
Currently, undo stops are introduced when there is cursor movement. 

Undo stops are not introduced based on time between edits. Perhaps that is what you would like in this case? Combined with a way to customize the cut-off time ?

**Comment by nachocab** [comment]
@alexandrudima yeah, that would be ideal

**Comment by alexandrudima** [comment]
I have just pushed a change where undo stops are introduced when typing space, which resolves the initial reported issue regarding typing `a b c`. We can continue to track in this issue that an undo stop should be introduced also based on time between edits.

**Comment by alexdima** [comment]
Let's continue tracking in #49627 , which has more upvotes.
