### ISSUE TITLE
vscode can't remember maximized window state in Xfce

### ISSUE THREAD

**Issue by GoodGuyNick** [Microsoft/vscode#34074]
- VSCode Version: 1.16
- OS Version: Sparkylinux 4.6.1 Xfce, Xubuntu 16.04.3 or any other distribution with Xfce DE.

Steps to Reproduce:

1. Launch vscode in Xfce DE
2. Maximize window
3. Close vscode and launch again
4. vscode will not open in maximized window

Reproduces without extensions: Yes

I know 100% this issue exist from 1.12.1 version but don't know if it was in the earlier versions.

In the past atom was having the same issue but with more desktop environments.

**Comment by thierer** [comment]
Just for the record: Works (and I think has always worked) fine for me using Xfce on Arch Linux x86_64. Still on 1.15.1, but that shouldn't matter if you had that problem for some time now.

**Comment by GoodGuyNick** [comment]
I thing this issue related to the use of GTK+ 2. I can test on the other distributions if needed.

**Comment by GoodGuyNick** [comment]
Tested on Korora 25 Xfce. Same issue. So basically Ubuntu latest LTS, Debian Stable, Fedora affected.

**Comment by Tyriar** [comment]
@GoodGuyNick I think Electron is moving to GTK 3 in the next version so this could be fixed soon if that's the case.

**Comment by GoodGuyNick** [comment]
But other programs built with electron doesn't have this problem.

**Comment by Tyriar** [comment]
I suspect this is fixed now since there have been many changes in Electron.

**Comment by GoodGuyNick** [comment]
After update working now.
