### ISSUE TITLE
css写完之后没有自动补全这个符号；

### ISSUE THREAD

**Issue by bymomo** [Microsoft/vscode#34078]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
sublime-keybindings|ms-|2.9.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.css写完之后没有自动补全这个符号；
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand, please include enough details for me to repro the issue.
