### ISSUE TITLE
vscode doesn't notice typechange on files

### ISSUE THREAD

**Issue by bmacnaughton** [Microsoft/vscode#34077]
- VSCode Version: 1.15.1
- OS Version: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. Create symlink like `link -s libx--1.0.so.1 libx.so`
2. Commit the change
3. delete the symlink, replace it with a copy of the file (`rm libx.so && cp libx-1.0.so.1 libx.so`)

`git status` shows `typechange: libx.so`

while vscode shows no changes.

Reproduces without extensions: Yes (shows no changes while git status does)

**Comment by roblourens** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/5970
