### ISSUE TITLE
CSS syntax highlighting doesn't handle strings with line continuations correctly

### ISSUE THREAD

**Issue by kellyjp** [Microsoft/vscode#34076]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create a CSS file containing a string that has a line continuation (backslash newline).

Expected Output:

The syntax highlighting shows the continued line as being a continuation of the string.

Actual Output:

The syntax highlighting treats the string as having ended at the line continuation and formats the continued line as if it was not part of the string.  This can be verified using the `Developer: Inspect TM Scopes` command.

Reproduces without extensions: Yes

Here is a simple test case:

```
#testcase::before {
    content: 'long string\
    using line continuation';
}
```

Here is how Visual Studio Code syntax highlighting shows the test case:
![vscode](https://user-images.githubusercontent.com/7471464/30240372-9ad33af8-95b2-11e7-9921-2e4978d0925e.png)

For comparison here is how Atom (1.19.5) syntax highlighting correctly shows the test case:
![atom](https://user-images.githubusercontent.com/7471464/30240374-a6883f06-95b2-11e7-9a4d-7fc8f203ca55.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-css#123

**Comment by kellyjp** [comment]
I just upgraded to 1.17.1 and this now appears to be fixed.  Thank you for fixing this issue.
