### ISSUE TITLE
Impossible to disconnect from nodemon seassion

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3407]
Related to #3238

* Start a nodemon session outside of vscode
* Attach to nodemon form vscode
* Pressing the stop button does not disconnect the debug session, it just reconnects

**Comment by weinand** [comment]
With the fix pressing the Stop button terminates the debug session which disconnects from node (without terminating it) and prevents a restart from happening.
nodemon and node will continue to run.
