### ISSUE TITLE
create-react-app looks terrible in the code terminal

### ISSUE THREAD

**Issue by kofno** [Microsoft/vscode#34084]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.0
githistory|don|0.2.3
tslint|eg2|1.0.1
prettier-vscode|esb|0.23.1
vscode-npm|fkn|3.3.0
flow-for-vscode|flo|0.7.1
ocaml|hac|0.6.41
output-colorizer|IBM|0.1.2
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|2.34.4
Ionide-Paket|Ion|1.7.3
haml|kar|0.8.0
node-module-intellisense|lei|1.4.0
Ruby|reb|0.15.0
final-newline|sam|0.3.2
elm|sbr|0.15.0
gitblame|wad|2.2.0
vscode-open-in-github|ziy|1.2.7

---

Steps to Reproduce:

1. Start a new typescript app using create-react-app
```
npm install -g create-react-app

create-react-app my-app --scripts-version=react-scripts-ts
cd my-app/
```
2. Open a powershell terminal in code.
3. Run `yarn start`

Reproduces without extensions: Yes

![capture](https://user-images.githubusercontent.com/19907/30245328-c5bc51b4-95a3-11e7-8ba4-ab3f1547c008.jpg)

**Comment by Tyriar** [comment]
You likely have custom colors in cmd.exe's properties. The terminal will only work with the standard colors set unfortunately.
