### ISSUE TITLE
selection highlight has same color as search highlight

### ISSUE THREAD

**Issue by brunis** [Microsoft/vscode#34087]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
jshint|dba|0.10.15
vscode-eslint|dba|1.3.0
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
mssql|ms-|1.1.0
csharp|ms-|1.12.1
html-css-class-completion|Zig|1.10.0
---

Steps to Reproduce:
Light theme is bad, Dark theme has the same issue, with "found" string highlight.

1. search for a string in your code
2. double click the string or mark a part of it in code

Reproduces without extensions: Yes/No

**Comment by Ngranger** [comment]
I updated from 1.15 to 1.16 and the selection highlights along the vertical scroll bar changed to be the same as in the highlighted text in the file, which is very annoying as its harder to see the occurrences that match a find/replace search.

**Comment by Ngranger** [comment]
P.S. - I have no extensions installed.

**Comment by roblourens** [comment]
It is hard to see the selection 
![image](https://user-images.githubusercontent.com/323878/30252065-bf7d9ac4-9620-11e7-9b84-1679808ab780.png)

@Ngranger I'm not exactly sure which highlights you're takling about, can you include a screenshot? And which theme are you using?

**Comment by Ngranger** [comment]
![screenshot 2017-09-10 15 29 19](https://user-images.githubusercontent.com/28519061/30252738-84dac85c-963d-11e7-9ce4-55207f45493c.png)

They used to be #B58B3F and opaque, as for what theme I'm using its "Dark (Visual Studio)", exactly as in the quoted text.

**Comment by aeschli** [comment]
That's what I see in 1.18.
- select Dark+ theme
- Ctrl + f to open the find widget and search for a common word
![image](https://user-images.githubusercontent.com/6461412/33255458-f6e006b8-d34d-11e7-9268-7c45a3bbf31f.png)

Please reopen with detailed steps if you still see this

**Comment by brunis** [comment]
If i double click to select a text, then press ctrl+f to find text, it will clear my selection and actually make a new selection based on whatever i type in the search field. I dont think that is expected behaviour.

**Comment by aeschli** [comment]
@brunis That's an unrelated issue. Please file a new issue.
