### ISSUE TITLE
根据文件类型配置文件编码

### ISSUE THREAD

**Issue by yunxu1019** [Microsoft/vscode#34080]
# 建议增加根据文件类型配置默认编码的功能
##  当前的VSCode仅支持所有语言使用同一种设置
![image](https://user-images.githubusercontent.com/15274374/30243016-4668d398-95d4-11e7-8422-64fd3d449226.png)
### 1. 用相同的编码打开所有文件
![image](https://user-images.githubusercontent.com/15274374/30243082-0981ffe4-95d5-11e7-879f-148f8eec1622.png)
### 2. 用错误猜测的编码打开文件
![image](https://user-images.githubusercontent.com/15274374/30243112-65cf09ea-95d5-11e7-80d7-3478a2bf0c76.png)

### 建议增加对如下配置方式的支持
![image](https://user-images.githubusercontent.com/15274374/30243169-ab6d2404-95d6-11e7-8dfd-cf641260fea2.png)
# # # # # # # # # #

**Comment by roblourens** [comment]
I believe this is covered by https://github.com/Microsoft/vscode/issues/19890
