### ISSUE TITLE
Issue with MiniMap on Mac

### ISSUE THREAD

**Issue by MrJames2016** [Microsoft/vscode#34085]
![screen shot 2017-09-09 at 13 54 13](https://user-images.githubusercontent.com/23472761/30245801-21d2fb90-95dd-11e7-8376-2b5f00c8e448.png)

- VSCode Version: Latest
- OS Version: Mac Yosemite 10.10.5

Steps to Reproduce:

1.Flashing minimap on right hand side
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@MrJames2016 does this happen all the time for you or only after a specific set of steps (e.g. putting the computer to sleep and waking it up). Does this issue reproduce if you open Chrome and open the page at https://microsoft.github.io/monaco-editor/

There we use the same minimap implementation, exercising the same canvas APIs on Chromium. This would help us understand if this is a Chromium issue (which I suspect it is).

**Comment by MrJames2016** [comment]
Hi,

I use safari browser and it happens as soon as I start coding…

Regards

James

**Comment by alexandrudima** [comment]
@MrJames2016 Thanks for following up. In this case I believe this is an issue either with Chromium (that VS Code is built upon) or with your GPU or GPU driver...

Does this issue reproduce in VS Code when launching `code --disable-gpu` ?

May I kindly ask that you open an issue at https://bugs.chromium.org/p/chromium/issues/list and include the link to https://microsoft.github.io/monaco-editor/ and the steps you do. It would be most helpful if you can show that this issue reproduces inChrome, but not in other browsers such as Firefox.

If this issue reproduces in Firefox, Safari, and Chrome, then it might very well be an issue with your graphics card or graphics driver. The canvas we use to paint the minimap is possibly backed up by a GPU buffer and possibly that GPU buffer gets corrupted / written over by some other GPU paint instructions.

**Comment by MrJames2016** [comment]
Yes same problem in Chrome, also this is basically a brand new Mac…

Regards

James

**Comment by alexandrudima** [comment]
@MrJames2016 Please open an issue against https://bugs.chromium.org/p/chromium/issues/list . They are responsible for the code that manages GPU buffers, etc. and they can provide additional assistance, perhaps even come up with a fix which will then make its way to both Chrome and to VS Code.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
