### ISSUE TITLE
Let users highlight text in preview mode of markdown

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#34081]
- VSCode Version: 1.15.1 
- OS Version: 10.11.6

Steps to Reproduce:

1. Open preview of some markdown
2. Try highlight some text

It will then quit preview and go to .md file. Instead I would like to actually highlight some text and copy it or do something else with it. Right now I cannot do that.

**Comment by mjbvz** [comment]
Highlighting should work fine, except that double click switches back to the editor by default. Try setting

```json
"markdown.preview.doubleClickToSwitchToEditor": false
```

to disable this
