### ISSUE TITLE
Cannot run certain npm scripts as preLaunchTask

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#34086]
- VSCode Version: Code - Insiders 1.17.0-insider (c354fca44896da2c9cad82b9bd9126f6658cfae8, 2017-09-08T05:24:34.310Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

**Description:**
Setting a `preLaunchTask` to common built-in scripts like "build", or arbitrary scripts like "foo", works as expected. However, setting it to uncommon built-in scripts like "pretest" fails.

**Steps to reproduce:**
1. Launch the default "Mocha Tests" configuration with a `preLaunchTask` of `npm: pretest`.

**Expected:**
The task runner should execute `npm run pretest`.

**Actual:**
`Could not find the preLaunchTask 'npm: pretest'.`

---
**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "args": [
                "-u",
                "tdd",
                "--timeout",
                "999999",
                "--colors",
                "${workspaceRoot}/test"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "preLaunchTask": "npm: pretest"
        }
    ]
}
```
**package.json**
```
{
    "name": "example",
    "version": "0.0.1",
    "devDependencies": {
        "mocha": "^3.5.0",
        "typescript": "^2.5.2"
    },
    "scripts": {
        "build": "echo build",
        "pretest": "echo pretest",
        "test": "echo test"
    }
}
```

**Workaround:**
- Create a "shell" task that executes `npm run <script>` and set the `preLaunchTask` to that.

**Comment by egamma** [comment]
The npm task detection intentionally filters out `pre*` tasks, since they are run as part of another script and should not be run independently. The recommendation is if you want to run a task as a preLaunch task then it has to be a 'real' script and not a 'pre' or 'post' script.

**Comment by mattacosta** [comment]
I don't agree with that recommendation for these reasons:
- In the above example, Code provides a default test configuration, which is not run via npm.
- Even though I can see why those scripts are hidden from the "Run task..." menu, I don't see why they should be filtered from configuration files. Developers should decide what's a "real" script, not Code.
- From a UX standpoint, I don't generally approve of having undocumented special conditions on a feature. They tend to confuse/irritate new users, and end up being one more "gotcha" for existing users to remember in the future. In this case, a `npm: ___` task should operate the same as typing `npm run ___` into a command line.

At the end of the day, it's not a big deal though. Keep up the good work!
