### ISSUE TITLE
[html][emmet] Emmet Backspace Issue

### ISSUE THREAD

**Issue by herrkawalla** [Microsoft/vscode#34089]
- VSCode Version:1.16
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Open and save an html file
2. Write "select[name=foo]>option[value=bar$]*2"
3. TAB it to autocomplete with emmet
4. Undo with STRG+Z
5. Delete the last 2 characters "*2"
6. TAB again
7. Nothing happens
8. Delete the last "]" then replace it with a freshly typed "]"
9. TAB again and it works again

It would be great if emmet is still recognized after deleting the code after an undo. Sometimes you have to adjust the emmet snippets and the issue described above is slightly annoying. Thanks!

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Pressing tab accepts the first suggestion in the suggestion list if the suggestion list is present.
Suggestion list appears when you type or when you manually invoke it using `Ctrl+Space`
This is the general behavior of suggestions/auto-complete in VS Code
This is what is happening in your Step 3 and 9

In Step 6, when you press tab there is no suggestion list

Your options
- Hit `Ctrl+Space` to trigger suggestions -> you will see emmet in the suggestions -> press tab to accept the suggestion
- Or you can set `emmet.triggerExpansionOnTab` to `true`. This will trigger Emmet on tab when suggestion list is absent.
