### ISSUE TITLE
Formatting (indention) dont work for js in a html file

### ISSUE THREAD

**Issue by alfnielsen** [Microsoft/vscode#34095]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
format-indent|Kas|1.3.0
Angular-BeastCode|Mik|4.3.15
html-css-class-completion|Zig|1.10.0
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
code-runner|for|0.7.1
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.1
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
project-snippets|reb|0.5.0
language-stylus|sys|1.7.3
vscode-angular-support|vis|0.1.4
JavaScriptSnippets|xab|1.4.1
angular1-snippets-shark|yan|0.1.4

---

Steps to Reproduce:

1. Create an html file with <script></script>
2. Insert this: (some lines with tabs and some with spaces, and wrong indention)
function getTM(min){
	var t = Math.floor(min/60);
		var m = m - t*60;
	 return {t:t, om:min, m:m , m2:m.toFixed(2) }
  }
3. Right-click -> Format Document

Reproduces without extensions: Yes

**Comment by alfnielsen** [comment]
I dont know if there is any plans of making some mix format (html+js+css), 
so maybe this is not considered a bug!
But js work in html mode, so i believe the format method should as well (for js).

**Comment by aeschli** [comment]
I tried with this example
```html
<head><script>
    function getTM(min) {
 var t = Math.floor(min / 60);
      var m = m - t * 60;
return { t: t, om: min, m: m, m2: m.toFixed(2) }
    }

  </script>
</head>

```
and it resulted in correct format
![image](https://user-images.githubusercontent.com/6461412/30270262-35fc1286-96ec-11e7-8e8d-e05e1a91f2fc.png)

Please give more information...

**Comment by alfnielsen** [comment]
Yes it works when the script is in the header, but not if its in the body.

**Comment by aeschli** [comment]
No, must be something else.
```
<html>

<head>

</head>

<body><script>
    function getTM(min) {
 var t = Math.floor(min / 60);
      var m = m - t * 60;
return { t: t, om: min, m: m, m2: m.toFixed(2) }
    }

  </script>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/6461412/30316202-c6b15fce-97a6-11e7-8035-4e7781b062c4.png)

Please provide a sample where the problem shows.

**Comment by alfnielsen** [comment]
Okay I tried disabling all the plugin (listet above),
and then it worked!

So one of these plugin breaks it..
