### ISSUE TITLE
Allow to execute post commands when a task finishes

### ISSUE THREAD

**Issue by frameland** [Microsoft/vscode#34094]
I have created a custom language plugin for VS Code.
Also I created a task with a custom problem matcher:

> "type": "shell",  
     "command: "...",  
    "problemMatcher": {  
            "owner": "customlang",  
            "fileLocation": ["relative", "./"],  
            "severity": "error",
            "pattern": {
                "regexp": "^(.*)<(\\d+)>\\s:(.*):(.*)",
                "file": 1,
                "line": 2,
                "message": 4
            }
        }

This works fine and reports errors correctly in the Problems tab at the bottom.
However, I have to **manually click the error** to jump to it.

Is there a way to automatically jump to an error, once there is one?
(in this language, there are never multiple errors at once)

- VSCode Version: 1.16
- OS Version: OSX 10.11

**Comment by sandy081** [comment]
@frameland Do you mean, automatically focus the first problem in Problems view after generating the errors?

**Comment by frameland** [comment]
Exactly.
When I run the build task right now (compile), if there are errors,
I have to click the problems tab, then click the actual problem (which is always the first one).

I would expect vscode to do these 2 things automatically.

**Comment by sandy081** [comment]
@dbaeumer Probably a post build task action to open problems view?

**Comment by dbaeumer** [comment]
@sandy081 I think I have that feature request already :-). The implementation would be to trigger a command when a task is finished.

**Comment by sandy081** [comment]
Cool. Do you have the issue #.. will make it a dup

**Comment by dbaeumer** [comment]
I will take this issue and make it a dup when I find the other one.

**Comment by alexr00** [comment]
Duplicate of #7090
