### ISSUE TITLE
Feature Request: Hotkey Trigger For IntelliSense Suggestions

### ISSUE THREAD

**Issue by andrewrothman** [microsoft/vscode#34090]
The usefulness of IntelliSense could be dramatically improved by including a number-based hot-key quick select for the first 9 elements.

[Alfred for Mac](https://www.alfredapp.com/) includes this feature, and I find it very useful.

With this addition, one could immediately select any of the top selections in the IntelliSense pop-up with a key shortcut such as `Control-1` for the first, or `Control-2` for the second. The modifier would be configurable for the user, and a sane default would need to be chosen to be shipped in VS Code. If we're getting into configuration, the entire feature could also be turned on and off by a setting.

A screenshot of the proposed behavior is attached to this issue.

![Hotkey Trigger For IntelliSense Suggestions Proposal Screenshot](https://user-images.githubusercontent.com/742678/30246778-68b2f918-95b8-11e7-92e1-91aac2b9fa16.png)

**Comment by green-mike** [comment]
It would be very very useful if implement the feature :)
