### ISSUE TITLE
Refactor View tags as variables

### ISSUE THREAD

**Issue by amorenew** [Microsoft/vscode#34096]
- VSCode Version:1.16
- OS Version: Windows

Feature Request: In new update V1.16 there is a [refactor for method](https://code.visualstudio.com/updates/v1_16#_javascript-and-typescript-refactorings) I suggest to make refactor to extract a view variable like:

`var nameView = <Text>name</Text>`

**Comment by mjbvz** [comment]
I believe this is covered by https://github.com/Microsoft/TypeScript/issues/17098
