### ISSUE TITLE
[Suggestion] Verify content validity of machineid ?

### ISSUE THREAD

**Issue by robbix1206** [Microsoft/vscode#34098]
- VSCode Version: 1.16.0 (64bit)
- OS Version: Windows 10 (15063.540)

Steps to Reproduce:

1. Go to modules
2. Make a search
3. Get "Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '' is not a valid HTTP header field value." shell.ts:419

Seems to be a bug somewhere but related to vscode as I tried with atom and this one didn't bugged like that so I think this is not electron related.

Maybe related to a Windows update :/

Reproduces without extensions: Yes

https://puu.sh/xwfmn.png

PS: I tried to reinstall it but the error stay here

**Comment by robbix1206** [comment]
Stacktrace
```
    at o (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:913322)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:914309
    at new n.Class.derive._oncancel (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59607)
    at t.xhrRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:914224)
    at n.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:913041)
    at i (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:911776)
    at Object.v.__generator.r [as next] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:911111)
    at s (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:174350)
    at n.Class.derive._oncancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59348)
    at c (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:174484)
```

**Comment by roblourens** [comment]
Do you have any of the `http.*` settings set?

**Comment by robbix1206** [comment]
None of them I have the default configuration (I deleted my .vscode configuration directory to be sure)

**Comment by joaomoreno** [comment]
Can you open the `Developer Tools`, open the Network tab, then search for some extensions? There will be a `extensionquery` request. Click it, and show me a screenshot of its details.

**Comment by robbix1206** [comment]
Nothing in Network tab has it crash when preparing the request :/

**Comment by joaomoreno** [comment]
Still in the `Developer Tools`, press <kbd>Ctrl O</kbd>, type `electron-browser/requestService` and open that TS file. Go to line 75 and put a breakpoint there, it should be the first line of `setRequestHeaders`. Then, trigger an extension search. When it pauses, `options.headers` should show you your culprit header. Let me know which one it is.

**Comment by robbix1206** [comment]
```"{"type":"POST","url":"https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery","data":"{\"filters\":[{\"criteria\":[{\"filterType\":8,\"value\":\"Microsoft.VisualStudio.Code\"},{\"filterType\":12,\"value\":\"4096\"},{\"filterType\":10,\"value\":\"npm\"}],\"pageNumber\":1,\"pageSize\":50,\"sortBy\":0,\"sortOrder\":0}],\"assetTypes\":[\"Microsoft.VisualStudio.Services.Icons.Default\",\"Microsoft.VisualStudio.Services.Content.License\",\"Microsoft.VisualStudio.Services.Content.Details\",\"Microsoft.VisualStudio.Code.Manifest\",\"Microsoft.VisualStudio.Services.VSIXPackage\",\"Microsoft.VisualStudio.Services.Content.Changelog\"],\"flags\":914}","headers":{"X-Market-Client-Id":"VSCode 1.16.0","User-Agent":"VSCode 1.16.0","X-Market-User-Id":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","Content-Type":"application/json","Accept":"application/json;api-version=3.0-preview.1","Accept-Encoding":"gzip","Content-Length":514},"agent":null,"strictSSL":true}"```

**Comment by robbix1206** [comment]
https://github.com/Microsoft/vscode/blob/bef497ff82391f4f29ea52f532d896a6903f6ff6/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L293
this.environmentService.machineUUID is a the null string that you can see.
I will try to go further to understand exactly from where it comes.

**Comment by robbix1206** [comment]
.... 
%appdata%/Code/machineid content is a file with 36 null character as content...
I don't know if this is a corruption error from Windows or an error of Vscode on generation

**Comment by joaomoreno** [comment]
Excellent, many thanks for the research!

Pushing a fix for this. As a workaround, delete that file and try again. Is the file now a valid uuid?

**Comment by robbix1206** [comment]
Yes thank you 😄
