### ISSUE TITLE
Recent update crashes a lot in windows at random times.

### ISSUE THREAD

**Issue by Suzal3579** [Microsoft/vscode#34092]
Just today using VS Code for 5 hours and it has already crashed 16 times. I do not think of any particular action that caused  VS Code to crash, it happens randomly.

## Please Fix!

**Comment by roblourens** [comment]
Need any details that you can provide. What does it do when it crashes? Which OS are you using?
 Can you try running it with `--disable-extensions` to check whether an extension is involved?

**Comment by Suzal3579** [comment]
It crashed a lot yesterday. Had to downgrade. I'm on windows 10 by the way (_Also mentioned in the question_ :P :) ).

**Comment by roblourens** [comment]
Ok but I need more details to understand the issue.

- What exactly do you see when it crashes?
- Can you try running it with --disable-extensions to check whether an extension is involved?

**Comment by Suzal3579** [comment]
@roblourens I end up seeing this 👎  everytime my windows crashes.
![capture](https://user-images.githubusercontent.com/16387512/30433531-50535c0a-9982-11e7-8c61-b26772d9431d.PNG)

And yaa running it with `--disable-extensions` did no good.

**Comment by roblourens** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by Suzal3579** [comment]
@roblourens 

- [x]  it reproduces with extensions disabled (code --disable-extensions from the command line - NOT the integrated terminal of Code)
           - if it does not reproduce with extensions disabled, you can stop testing and report this!

- [x]   it was not happening in the previous stable release
- [ ]   it reproduces in insiders builds
- [x]   there is no suspicious output when running from the command line (code --verbose)
- [x]  there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [x]   it reproduces on Windows.
- [x]  it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json (backup first! see below for paths)
- [ ]   it reproduces when opening empty (code -n from the command line)
- [x]   it reproduces opening any folder
- [x]   it reproduces opening any file
- [ ]   it reproduces when only having a single window open
- [ ]   it reproduces by just using Code without external tools running on the same folder
- [ ]   it reproduces from a workspace that is not under Git version control
- [ ]   it reproduces independently if a file is opened or not after startup
 - [x]  it reproduces when running with GPU disabled (code --disable-gpu)
- [x]   it reproduces when being offline
 - [x]  it reproduces when disabling the file watching (set files.watcherExclude to "**/**": true)
- [x]   it reproduces after uninstalling and reinstalling
- [x]   it reproduces after deleting the application data directory (backup first! see below for paths)
- [x]   I have not played around with permissions or ran Code as administrator
 - [ ]  I am seeing a single CPU process spin high (please share the full command line arguments)
- [x]   I am seeing Code consuming lots of memory in a short time


Application Data Directory for VS Code:

__Windows 10__: C:\Users\<user>\AppData\Roaming\Code

Application Data Directory for VS Code Insiders:

__Windows 10__: C:\Users\<user>\AppData\Roaming\Code - Insiders

**Comment by bpasero** [comment]
@Suzal3579 are you using the integrated terminal for work?

**Comment by Suzal3579** [comment]
@bpasero yes, I do.

**Comment by dmsvlks** [comment]
It might have something to do with the terminal. I occasionally crash when I save changes and then webpack has to recompile.

**Comment by Suzal3579** [comment]
Yea, It might be the terminal. The crash only happened after the terminal actions. For me, it was `nodemon`.

**Comment by dmsvlks** [comment]
Hmm, I too use `nodemon`.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
