### ISSUE TITLE
Feature Request: Open terminal at the project location.

### ISSUE THREAD

**Issue by foo-baar** [Microsoft/vscode#34101]
Hello Team,

Today if I open an project from recent project menu of vscode, the integrated terminal opens at the root location.

As per flow I type `npm install` & it fails as I am not in the same directory where package.json is located.

If feel it should be in the same location as the project dir.

Kindly close & pardon me in case its already there or I am missing something.

Danke,
✌️

**Comment by roblourens** [comment]
>  the integrated terminal opens at the root location.

It should start in the folder you opened, is that what you mean? Or is it opening at the root of the drive?

**Comment by foo-baar** [comment]
Hello @roblourens Yeah exactly my suggestion\query it should start in the folder I opened, currently the terminal is opened at the root\home: `/User/username` location.

Thanks ✌️

**Comment by Tyriar** [comment]
@foo-baar what's in your settings.json file?

**Comment by foo-baar** [comment]
Hello @Tyriar : User settings are as below:

`{
    "window.zoomLevel": 0,
    "editor.fontSize": 15,
    "files.autoSave": "afterDelay",
    "editor.renderWhitespace": "boundary",
    "terminal.integrated.fontSize": 14,
    "update.channel":"default",
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Atom One Dark",
    "editor.wordWrap": "on",
    "workbench.welcome.enabled": false,
    "emmet.syntaxProfiles": {
         "typescript": "html"
    },
    "vsicons.projectDetection.autoReload": true
}`

OS: Mac Sierra v10.12.6
vscode version: Version 1.16.0 (1.16.0)

$SHELL: 
`TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
CLICOLOR=1
TMPDIR=/var/folders/6g/z5lsfxn17vn1zfwyzssn3k840000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9jMSqs8D78/Render
TERM_PROGRAM_VERSION=388.1.1
TERM_SESSION_ID=FCC47068-0625-46ED-8F67-EB409B1639AB
USER=vishal
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.bnYY3j3ddr/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/vishal
XPC_FLAGS=0x0
PS1=\[\033[36m\]\u\[\033[m\]🔥 \[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]$ 
XPC_SERVICE_NAME=0
HOME=/Users/vishal
SHLVL=2
LOGNAME=vishal
LC_CTYPE=UTF-8
_=/usr/bin/printenv`

Please let me know if you need any more info.

Thanks much 👍

**Comment by foo-baar** [comment]
Hey @Tyriar : Any instructions on this for me ?

**Comment by Tyriar** [comment]
It looks like you're using bash, this definitely works just fine. I suspect you are doing a `cd` or `pushd` in your `~/.bash_profile` or `~/.bashrc`.

**Comment by foo-baar** [comment]
Hey @Tyriar Yup :) had cd in the end of .bash_profile removed it & working fine now 👍 

Thanks much,
✌️

**Comment by Tyriar** [comment]
Good to hear 😃
