### ISSUE TITLE
Allow remapping the internal  terminal reversed search keys

### ISSUE THREAD

**Issue by krasi-georgiev** [Microsoft/vscode#34100]
Would it be feasible to allow re-mapping the bash reversed command search to other keys?

I use reversed command search all the time and I find it fastest to hit right CMD key +R , which I can do without lifting my hands from the keyboard.

In the built in terminal  this is triggered using left CTRL+R which can't be done without lifting your hand from the keyboard so on constant use is really awkward.

**Comment by krasi-georgiev** [comment]
in iTerm this is done by remapping the right CMD key to be used as CTRL and I have been using it for a long time without any conflicts.

**Comment by Tyriar** [comment]
You can't remap cmd to ctrl in VS Code, but you can remap keys generically using an `~/.inputrc` file.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/487

**Comment by krasi-georgiev** [comment]
Thanks will try

**Comment by krasi-georgiev** [comment]
@Tyriar 
read all info I could find but don't think I can use that to remap the forward search to be
right CMD+R
or
right ALT+R

**Comment by Tyriar** [comment]
@krasi-georgiev for cmd you will likely need to wait for the support to come through https://github.com/sourcelair/xterm.js/issues/487, I recommend subscribing to that issue
