### ISSUE TITLE
Missing Task Bar Icon

### ISSUE THREAD

**Issue by RaTcHeT302** [Microsoft/vscode#34106]
# Solution for the Broken Task Bar Icon (Workaround)
1. Open any file with Visual Studio Code.
2. Look at the Task Bar, locate Visual Studio Code and then Right Click on it.
3. Select "Visual Studio Code", located above the "Pin to Task Bar" item.
4. When a window with "Problem With Shortcut" in the name appears select "Yes".
5. Close Visual Studio Code, then open it again.

# Images
![immagine](https://user-images.githubusercontent.com/10897523/31571316-e30be008-b098-11e7-805a-0eb04c0901c7.png)
![immagine](https://i.imgur.com/BOnGcQ1.png)
____________________________________
# Old Comment
Visual Studio Code x64 1.16.0
Windows 10 1703 15063.540

Reproduces Without Extensions (No) (No Extensions Have Been Installed)
![missing icon](https://user-images.githubusercontent.com/10897523/30253570-a88d7bf2-9690-11e7-8739-5905e29d4bb1.png)

**Comment by gercules1979** [comment]
brecks all computer system Windows so not bed it these!

**Comment by RaTcHeT302** [comment]
what?

**Comment by roblourens** [comment]
Can you explain exactly what happened? Is the icon still missing if you reinstall or restart the computer?

**Comment by RaTcHeT302** [comment]
I don't really know, I was kinda hoping others would post here if they had the same problem in the future. I can't really reformat at the moment, restarting doesn't do anything, I don't understand why the icon for the insiders builds works fine.

Something probably broke on Windows itself but I opened up the issue anyway just in case.

**Comment by RaTcHeT302** [comment]
Also I got confused by the "Reproduces Without Extensions" text, I ment to set it to "Yes" as I have no extensions at all but I checked the command line anyway.

**Comment by ramya-rao-a** [comment]
@RaTcHeT302 Is the icon still broken? And just to make sure you are referring to the icon for the stable version of VS Code correct?

**Comment by crnd** [comment]
I've had the exact same problem for a while now. I think this started when I moved from 32bit to 64bit version of VS Code. The taskbar icon is still missing with version 1.17.0 running on Windows 10 Pro 1703.

**Comment by t5k6** [comment]
I had the same problem with insider version (1.18).
I solved it by duplicating "Code - Insider.exe" and renaming the copy ("Code - Insider.exe") to "Code.exe".
Now it also works with "Code - Insider.exe".
For reference, I have downloaded the portable zipped release.

**Comment by miocr** [comment]
Same as @crnd, I uninstall 32bit VSCode and install 64bit VScode about a month ago. Since then, there is a bad icon in the taskbar. VS Code updated twice since then and the problem remains.  
Now VSCode 1.17.0 / Win7Pro-64bit

**Comment by crnd** [comment]
Decided to try what @t5k6 did and eventually got it fixed. I started by making a copy of the Code.exe file, deleting the original and then renaming the copy to Code.exe. After this I opened VSCode, right clicked on the VSCode taskbar icon and selected "Visual Studio Code" from the context menu. Then I got a dialog saying that Windows cannot find the shortcut and asked if I wanted it to be deleted to which I answered yes. No idea what shortcut it meant because I could not see anything actually deleted, perhaps it was something internal. Then I closed VSCode and opened it again and now it seems to be working.

**Comment by miocr** [comment]
@crnd Thanks, this workaround works!  I try rename Code.exe ets. previously, but but I did not delete corucpted link over the right mouse click. Now the icon is ok.

**Comment by RaTcHeT302** [comment]
Solution for the Broken Task Bar Icon
1. Open any file with Visual Studio Code.
2. Look at the Task Bar, find Visual Studio Code then Right Click on it.
3. Select "Visual Studio Code", located above the "Pin to Task Bar" item.
4. When a window with "Problem With Shortcut" in the name appears select "Yes".
5. Close Visual Studio Code then open it again.

![immagine](https://user-images.githubusercontent.com/10897523/31571316-e30be008-b098-11e7-805a-0eb04c0901c7.png)
https://i.imgur.com/BOnGcQ1.png

**Comment by LunarTwilight** [comment]
VSCode (insiders) is now showing an electron icon? https://owo.sh/9b37b8.png

**Comment by joemaffei** [comment]
Not sure if it's been reported elsewhere (I couldn't find it), but the Insider icon is gone on Windows 10 - on my laptop and on my work computer. It's just showing the default Electron icon.

![image](https://user-images.githubusercontent.com/9068746/32031401-a7768a52-b9c6-11e7-8f1f-6adb28678ed2.png)

**Comment by bpasero** [comment]
Closing, it is unlikely that we can control this or can do anything about it.
