### ISSUE TITLE
И ещё немного шотландского - килт к примeру!

### ISSUE THREAD

**Issue by gercules1979** [Microsoft/vscode#34108]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.URL's brack all time!
2.All time opens BENG the plaice talking or wraits searcher distabilety!

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand, and google translate is not helping, can you explain some more?

**Comment by mrmlnc** [comment]
@gercules1979, это не описание твоей проблемы. Сейчас это похоже на стёб.

@roblourens, it looks like banter.
