### ISSUE TITLE
JSDocs @param object not working on IntelliSense

### ISSUE THREAD

**Issue by rhernandog** [Microsoft/vscode#34107]
The editor is not displaying the JSDocs `@param` correctly when an object is required as the parameter for a function. I've tried all the possibilities indicated in the [JSDocs reference](http://usejsdoc.org/tags-param.html) but IntelliSense always displays **_any_** instead of object. It works fine any other option (array, string, number, boolean, function).

- VSCode Version: 1.16
- OS Version: Windows 7 64

Steps to Reproduce:

1. Create a function/method
2. Create a JSDocs comment for the method
3. Add a `@param {Object}` to the JSDoc comment.
4. Hover on the definition and you'll see  **_any_** instead of object.
5. Call the function and you'll see **_any_** instead of object

Reproduces without extensions: Yes

#### Definition
![jsdocs-1](https://user-images.githubusercontent.com/4622323/30253571-6c12f2c4-965e-11e7-8989-058b85a1bebe.jpg)
#### Mouse Over
![jsdocs-2](https://user-images.githubusercontent.com/4622323/30253577-7caf5ffa-965e-11e7-81fe-e639864a081c.jpg)
#### Writing the function
![jsdocs-3](https://user-images.githubusercontent.com/4622323/30253580-8695342c-965e-11e7-9b07-8f2477bae973.jpg)

**Comment by roblourens** [comment]
It's showing a TypeScript-style type annotation, and there is no `Object` in TypeScript, so I suspect `any` is expected here.

**Comment by rhernandog** [comment]
Hi @roblourens and thanks for answering.

The thing is that I'm not working on TypeScript, this is Vanilla JS. I don't know if this should make a difference.

**Comment by mjbvz** [comment]
TypeScript powers our JavaScript and TypeScript language support.

I think that TS may alias `object` and `Object` to `any` in jsdoc comments. I've opened https://github.com/Microsoft/TypeScript/issues/18396 to track this 

Closing as upstream
