### ISSUE TITLE
HOW to adjust the TAB UI  SELECTION HIGHLIGHT

### ISSUE THREAD

**Issue by Piping** [Microsoft/vscode#34112]
- VSCode Version: 1.16
- OS Version: Mac OS

Hi, I am wondering if there a way to change the ui tab highlight behavior.

Currently the select tab is using dark color and inactive tab used bright color which is really confusing. I believe the UI highlight is also not consistent with file explorer.

![image](https://user-images.githubusercontent.com/12042284/30258232-760438d4-966c-11e7-8284-c9154df89e90.png)

Just By Looking at the picture, anyone would just think the Welcome is opened tab, but it is really not!!

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
You can customize these colors in settings. For example try 

```
"workbench.colorCustomizations": {
        "tab.activeBackground": "#00ff00",
        "tab.inactiveBackground": "#0000ff"
},
```
