### ISSUE TITLE
Improve Node.js intellisense for events

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#34114]
- VSCode Version: 1.16.0
- OS Version: macOs Sierra

Hello, maybe it's possible to improve Node.js IntelliSense by adding events for `process.on(...)` for e.g. if I type `process.on(` and I press `ctrl+space` I will get list with events like `uncaughtException | unhandledRejection | rejectionHandled | etc...`? Like it is right now for `typeof object === ''` I get list with types when I press `ctrl+space`. Also the same goes for `Net` module for e.g.

```
const server = net.createServer((socket) => {
  socket.end('goodbye\n');
}).on('error' <-- to get intellisense here
```

This will really help, because every time I need to open documentation to see what events I can use.

I can help and make PR, I just need to know if it's related with TypeScript or VS Code. Also the beginning where to start.

Thanks!

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/30261401-05f89c18-96ff-11e7-9e70-7aaffb11cb85.png)

`process.on` should already have event name suggestions.

Code uses typings from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) project to provide type information. So please make sure you have the latest version installed (`npm i -D @types/node@8.0.28` as `8.0.28` is the currently latest version)

The code about `process.on` is here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2bc1c232bad1888bff27366f10eafdea67a390fa/types/node/index.d.ts#L551-L561

If you want to add more events, you can start working here.

**Comment by bsvipas** [comment]
@yume-chan Yes, you're right, I was wrong, I don't know why, but earlier (after hour ago) I didn't get them, but right now I get it. I checked and every event right now have list of suggestions.

Thanks!
