### ISSUE TITLE
fails to start language servers, php.

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#34118]
As of this morning VSCode insiders starts with various errors like: php executable is not valid (it was, and it still is - version 7.0.7) and failing to start CSS and JSON language servers.

[Error - 09:37:35] Starting client failed
Error: spawn C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

OR

Cannot validate since c:\dev\php\php.exe is not a valid php executable. Use the setting 'php.validate.executablePath' to configure the PHP executable.

The stable build does not produce these errors with the same configuration.

- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:24:55.109Z)
- OS Version: Windows_NT ia32 10.0.16278
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-database|baj|1.2.0
vscode-intelephense-client|bme|0.7.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.9
jshint|dba|0.10.15
xml|Dot|1.9.2
gitlens|eam|4.4.3
php-debug|fel|1.11.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.2.1
php-docblocker|nei|1.2.0
vscode-icons|rob|7.12.0
Align|ste|0.2.0
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
We don't see this and it looks like the OS can't find the `C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe` exe anymore (which is the electron exe we use as a node environment). All I can recommend is to uninstall and reinstall insider to see if that makes a difference.
