### ISSUE TITLE
Committed new changes still shows in the editor

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/vscode#34115]
- VSCode Version: Version 1.16.0
- OS Version: Windows 10 Version 1703 (OS Build 16281.1000)

Steps to Reproduce:
I'm not really sure how to reproduce since I noticed it later. But the changes below are already committed but the green bar still shows.
![image](https://user-images.githubusercontent.com/19337229/30260538-88407d44-96fa-11e7-8a58-4ddf834325e5.png)

But it disappears after a restart. Still quite annoying, though, needing to restart just to make it go away.

**Comment by joaomoreno** [comment]
Is your workspace path special like a network share?

**Comment by iamdevlinph** [comment]
Just a local. And to add, I'm using WSL to commit changes.

**Comment by joaomoreno** [comment]
Got it. We are still a bit behind on WSL support unfortunately. #29812
