### ISSUE TITLE
Closing tag issue with latest version

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode#34111]
- VSCode Version: 1.16
- OS Version: Win 8.1

Steps to Reproduce:

Please see the video:   [**Youtube**](https://youtu.be/XkHxf6YrBhM)   

VS code version:

![Alt Text](https://i.imgur.com/Q7ORqWU.png)

**Comment by aeschli** [comment]
You say that in
```
<div>
  <span

  </span>
</div>
```
entering '>' should not autoclose as the tag is already closed.

What you see is the intended outcome, we assume that typing '>' means you just added a new tag that also needs to be closed.
You can press undo to remove the closing tag.

What was your reason to remove the '>' from the existing tag and type it again?

**Comment by Sampath-Lokuge** [comment]
@aeschli I was thinking that before injecting the new closing tag VS code should check whether is there any closing tag exist for that node. If it exists then no need to inject new closing tag again. Hope it is good enhancement instead of the current behavior no?

The reason for doing that was,  Angular components do not update the HTML file until we do some modification on that file. In other words, it shows below errors. But actually, I have added a particular module. After I have done minor change on the HTML page then an error will vanish.

![](https://i.imgur.com/kNgATKc.png)

**Comment by aeschli** [comment]
It's difficult to guess what the intention of the user is. Does he want to insert a new tag, or is he just just fixing an already closed tag. I'd leave it as is and follow the model we have with auto-closing brackets in other languages. Only if there is a closing bracket directly after the cursor, we don't add a new one.
As mentioned, a simple undo will revert the coding assistance.
