### ISSUE TITLE
[html] support for bootstrap

### ISSUE THREAD

**Issue by akshitgupta29** [Microsoft/vscode#34125]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.7.0
vscode-html-css|ecm|0.1.8
code-runner|for|0.7.1
HTMLHint|mka|0.3.3
view-in-browser|qin|0.0.5
Ruby|reb|0.15.0
vscode-icons|rob|7.12.0
view-in-default-application|see|3.3.0
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1. Can we have something that give us a breif explaination of the bootstrap classes, so that the developer at that moment can know what exactly is happening with that class?
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@akshitgupta29 Do you mean you would like some extra kind of documentation (like hover) when using a bootstrap CSS class name in HTML, or do you mean something else ?

**Comment by akshitgupta29** [comment]
@alexandrudima  By some extra kind of documentation, I meant something like attached in the image, so that a beginner like me, can have some extra information.
![visualcode](https://user-images.githubusercontent.com/12370891/30519365-42a2bb50-9bb2-11e7-991d-cf082fc82ea9.png)

**Comment by aeschli** [comment]
That would have to be offered by an extension. The built-in HTML extension should cover only the standard HTML constructs.

**Comment by akshitgupta29** [comment]
Okie! Thanks a lot! @aeschli

**Comment by akshitgupta29** [comment]
You can close this issue, and also since I am a newbie, can you recommend the extension for the same.

**Comment by aeschli** [comment]
Sorry, I don't use bootstrap myself. You have to check out https://marketplace.visualstudio.com/search?target=vscode&category=Languages&sortBy=Downloads.

**Comment by akshitgupta29** [comment]
Okie! Thanks a lot for your help! You may close this issue. @aeschli
