### ISSUE TITLE
Font color on php file different

### ISSUE THREAD

**Issue by pietro-nardelli** [Microsoft/vscode#34129]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

![cattura](https://user-images.githubusercontent.com/20285899/30268644-aef2bac4-96e6-11e7-951c-1fcd09be24f0.PNG)

Hi, as you can see in the picture there's a problem with the font color of php files. I cannot see anymore variables, and all seems that there's a tag mismatch but this is not true. This issue appears after the last patch I've downloaded of VS Code.

How can I solve it?

**Comment by roblourens** [comment]
Can you include the full contents of the file? The problem may start somewhere else before that snippet.

Is it correct in other files?

**Comment by pietro-nardelli** [comment]
It's strange because I just downloaded the new version of VS Code when I saw that problem. Anyway, of course, no problem!
`<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Study tool</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="Your tool for studying." />
	

	<style type="text/css">
		@import url("home-studente.css");
	</style>	
</head>
<body>
<?php
include 'functions/giorniDisponibili.php';
session_start();
if (!isset($_SESSION['accessoPermesso'])) {
    header('Location: login.php');
}

/***Procedura standard per inizializzare il file XML***/
$xmlString = ""; //Inizializziamo la variabile xmlString
foreach (file("xml-schema/studenti.xml") as $node) { //Per ogni riga del file xml...
	$xmlString .= trim($node); //Aggiungi alla stringa $xmlString la riga $node
}
$doc = new DOMDocument(); //Creiamo l'oggetto documento DOM e lo assegnamo a $doc
$doc->loadXML($xmlString); //$doc essendo un oggetto DOMDocument possiede il parser XML (metodo nella classe DOMDocument) che lo facciamo girare sulla stringa $xmlString
$root = $doc->documentElement; //la chiamata a DocumentElement restituisce la radice del documento DOM
$studenti = $root->childNodes; //$studenti contiene i nodi figli di root 
/***/

/*Scorri tutti gli studenti del file XML*/
for ($i=0; $i < $studenti->length; $i++) {
	/*Se l'email derivante dal login coincide con uno studente presente nel file XML, carica tutti i dati relativi*/
	if ($_SESSION['email'] == $studenti->item($i)->firstChild->nextSibling->nextSibling->textContent){
		$studente = $studenti->item($i); //questo sarà uno degli studenti e sarà dotato di altri figli.
		$nome = $studente->firstChild; 
		$nomeText = $nome->textContent;

		$cognome = $nome->nextSibling;
		$cognomeText = $cognome->textContent;

		$email = $cognome->nextSibling;
		$emailText = $email->textContent;

		//Questa parte è necessaria per aggiornare efficacemente il dom con $materieElement->insertBefore($newNode);
		$materieElement = $email->nextSibling; //Questo rappresenta l'elemento "materie"
		$materie = $materieElement->childNodes;  //Quest'altro invece la lista di materie
		/*Bisogna creare un array per ogni valore presente in materia, affinchè si possa successivamente
		 *elencare ed aggiornare le materie presenti nella lista. Se si creasse un array per i soli valori
		 *testuali sarebbe impossibile aggiornarli. Ogni valore $k deve appartenere ad una materia
		 *($k=>materia k-esima).
		 */
		$nomeMateriaText = array();
		for ($k=0; $k < $materie->length; $k++) {	
			$materia = $materie->item($k);

			$statusText[$k] = $materia->getAttribute('status');
			$nomeMateria[$k] = $materia->firstChild;
			$nomeMateriaText[$k] = $nomeMateria[$k]->textContent;

			//Solo per la materia planned possiamo inserire tutti i dati inerenti al piano di studi, altrimenti errore
			if ($statusText[$k] == 'planned') {
				$valoreDaStudiare[$k] = $nomeMateria[$k]->nextSibling;
				$valoreDaStudiareText[$k] = $valoreDaStudiare[$k]->textContent;

				$oggettoStudio[$k] = $valoreDaStudiare[$k]->nextSibling;
				$oggettoStudioText[$k] = $oggettoStudio[$k]->textContent;

				$dataScadenza[$k] = $oggettoStudio[$k]->nextSibling;
				$dataScadenzaText[$k] = $dataScadenza[$k]->textContent;

				$nGiorniRipasso[$k] = $dataScadenza[$k]->nextSibling;
				$nGiorniRipassoText[$k] = $nGiorniRipasso[$k]->textContent;			

				$valoreStudiatoOggi[$k] = $nGiorniRipasso[$k]->nextSibling;			
				$valoreStudiatoOggiText[$k] = $valoreStudiatoOggi[$k]->textContent;

				$dataStudiatoOggi[$k] = $valoreStudiatoOggi[$k]->nextSibling;
				$dataStudiatoOggiText[$k] = $dataStudiatoOggi[$k]->textContent;
				
				$valoreStudiato[$k] = $dataStudiatoOggi[$k]->nextSibling;
				$valoreStudiatoText[$k] = $valoreStudiato[$k]->textContent;
			}
		} 

		$riassunti = $email->nextSibling->nextSibling;
		$reputation = $riassunti->nextSibling;
		$reputationText = $reputation->textContent;

		$coins = $reputation->nextSibling;
		$coinsText = $coins->textContent;	
	}
}


?>
	<div id="lateralHomeStudente">
		<div id="logoHomeStudente">
			<a href="#">
				
				<img src="images/logoHome.png" style="width: 100%;"/>
			</a>
		</div>
		<div id="navigation">
			<a href="aggiungi-materia.php"><img src="images/iconAggiungiMateria.png">Nuova materia</a>
			<a href="#"><img src="images/iconArchivioMaterie.png">Archivio materie</a>
			<a href="#"><img src="images/iconRiassuntiCreati.png">Riassunti creati</a>
			<a href="#"><img src="images/iconRiassuntiVisualizzati.png">Riassunti visualizzati</a>
			<a href="#"><img src="images/iconRiassuntiPreferiti.png">Riassunti preferiti</a>
			<form action="<?php $_SERVER["PHP_SELF"] ?>" method="post" id="cercaRiassunti">		
				<input type="text" name="nome" placeholder=" Cerca riassunti" />
				<input type="image" src="images/iconCercaRiassunti.png" alt="Submit Form" />
			</form>
		</div>
		<div id="navigationUser">
			<div id="user">
				<img src="images/iconUtente.png"><?php echo $nomeText." ".$cognomeText; ?>
			</div>
			<div id="reputation">
				<img src="images/iconReputation.png" title="Reputation"><?php echo $reputationText; ?>
			</div>
			<div id="coins">
				<img src="images/iconCoins.png" title="Coins"><?php echo $coinsText; ?>
			</div>
		</div>
		
		<div id="navigation" style="top: 75px; height: 40px;">
			<a href="logout.php"><img src="images/iconLogout.png">Logout</a>
		</div>
	</div>
	<div id="main">
		<form action="<?php $_SERVER["PHP_SELF"] ?>" method="post" id="aggiungiMateria">
		<?php if (empty($_SESSION['status'])) {
			?>
			<div>
			Aggiungi una materia
			</div>
			<p>
			Puoi decidere se pianificare una materia sviluppando un <b>piano di studi</b> per arrivare all'esame preparato. 
			<br />
			Oppure puoi organizzarti autonomamente, ma in entrambi casi hai la possibilità di scrivere dei <b>riassunti</b>
			che ti permetteranno di memorizzare in maniera più efficace la materia.
			</p>
			<?php
			if (isset($_POST['submit'])) {	
				$errore = 0;
				if ($_POST['nomeMateria'] && !empty($_POST['status']) ) {
					for ($k=0; $k < $materie->length; $k++) {
						if ( strcasecmp($_POST['nomeMateria'], $nomeMateriaText[$k]) == 0 ) {	
							echo '<p style="color: red;">Materia già presente.</p>';
							$errore = 1;
						}
					}
					if ($errore == 0) {
						$_SESSION['nomeMateria']= $_POST['nomeMateria'];
						$_SESSION['status']= $_POST['status'];

						header("Location: aggiungi-materia.php");
					}
				}
				else {
					echo '<p style="color: red;">Compilare tutti i campi.</p>';
				}
			}
			?>

			<input type="text" name="nomeMateria" placeholder=" Nome della materia" />
			<input type="radio" name="status" value="planned" /> <label>Pianifica</label>
			<input type="radio" name="status" value="unplanned" /> <label>Non pianificarla</label><br />
			<input type="submit" name="submit" value="Continua" />
		<?php 
		}
		else if (!empty($_SESSION['status']) && empty($_SESSION['oggettoStudio'])) {
		?>
			<div>
			Aggiungi una materia
			</div>
			<p>
			Inserisci cosa si vuole monitorare. 
			<br />
			Ad esempio, se si deve studiare un libro di 300 pagine inserire "pagine" nel form sottostante.
			</p>
			<?php
			if (isset($_POST['submit'])) {	
				if ($_POST['oggettoStudio']) {
					$_SESSION['oggettoStudio']= $_POST['oggettoStudio'];
					
					header("Location: aggiungi-materia.php");
				}
				else {
					echo '<p style="color: red;">Compilare tutti i campi.</p>';
				}
			}
			if (isset($_POST['back'])) {
				unset($_SESSION['status']);

				header("Location: aggiungi-materia.php");
			}
			?>

			<input type="text" name="oggettoStudio" placeholder="Pagine? Capitoli? Paragrafi?"/> <br />	

			<input type="submit" name="back" value="Indietro" />	
			<input type="submit" name="submit" value="Continua" />
		<?php
		}
		else {
			?>
				<div>
				Aggiungi una materia
				</div>
				<p>
				Ancora un ultimo passaggio e abbiamo finito!
				</p>
				<?php
				if (isset($_POST['submit'])) {	
					if (isset($_POST['valoreDaStudiare'])) {
						if (is_numeric ($_POST['valoreDaStudiare']) && $_POST['valoreDaStudiare'] > 0 ) {
							$_SESSION['valoreDaStudiare']= $_POST['valoreDaStudiare'];
						}
						else {
							unset($_SESSION['valoreDaStudiare']);
							echo '<p style="color: red;">Valore da studiare deve essere un n° maggiore di 0.</p>';
						}
					}
					//https://stackoverflow.com/questions/10120643/php-datetime-createfromformat-functionality/10120725#10120725
					if ($_POST['dataScadenza']) {
						$dateTime = DateTime::createFromFormat('Y-m-d', $_POST['dataScadenza']);
						$errors = DateTime::getLastErrors();
						$now = new DateTime();

						
						if (empty($errors['warning_count'])) {
							$_SESSION['dataScadenza'] = $_POST['dataScadenza'];
						}
						else {
							unset($_SESSION['dataScadenza']);
							echo '<p style="color: red;">La data non è stata compilata correttamente.</p>';
						}
					}
					if (isset($_POST['nGiorniRipasso'])) {
						if (is_numeric ($_POST['nGiorniRipasso']) && $_POST['nGiorniRipasso'] >= 0) {
							$_SESSION['nGiorniRipasso'] = $_POST['nGiorniRipasso'];
						}
						else {
							unset($_SESSION['nGiorniRipasso']);
							echo '<p style="color: red;">Giorni di ripasso deve essere un n° positivo.</p>';
						}
					}
					if (isset($_POST['valoreStudiato'])) {
						if (is_numeric ($_POST['nGiorniRipasso']) && $_POST['valoreStudiato'] >= 0) {
							$_SESSION['valoreStudiato'] = $_POST['valoreStudiato'];
						}
						else {
							unset($_SESSION['valoreStudiato']);
							echo '<p style="color: red;">Valore studiato deve essere un n° maggiore di 0.</p>';
						}
					}
					else {
						$_SESSION['valoreStudiato'] = "0";
					}
					if (!isset($_POST['valoreDaStudiare']) || !($_POST['dataScadenza']) || !isset($_POST['nGiorniRipasso'])) {
						echo '<p style="color: red;">Compilare tutti i campi obbligatori.</p>';
					}
					else {
						$dataScadenza = $dateTime->format('Y-m-d');
						if (giorniDisponibili($dataScadenza, $_POST['nGiorniRipasso']) < 0) {
							echo '<p style="color: red;">Ops, non hai abbastanza giorni per studiare.</p>';
						}
						if ($_POST['valoreStudiato'] > $_POST['valoreDaStudiare'] ) {
							echo '<p style="color: red;">Il valore studiato non può essere maggiore del totale da studiare!</p>';
						}
					}
					if (isset($_SESSION['valoreDaStudiare']) &&
					isset($_SESSION['dataScadenza']) &&
					isset($_SESSION['nGiorniRipasso']) &&
					isset($_SESSION['valoreStudiato'])) {
						$newMateria = $doc->createElement("materia");
						$newNomeMateria = $doc->createElement("nomeMateria", $_SESSION['nomeMateria']);
										
						$newOggettoStudio = $doc->createElement("oggettoStudio", $_SESSION['oggettoStudio']);
						$newValoreDaStudiare = $doc->createElement("valoreDaStudiare", $_SESSION['valoreDaStudiare']);
						$newDataScadenza = $doc->createElement("dataScadenza", $_SESSION['dataScadenza']);
						$newNGiorniRipasso = $doc->createElement("nGiorniRipasso", $_SESSION['nGiorniRipasso']);
						$newValoreStudiato = $doc->createElement("valoreStudiato", $_SESSION['valoreStudiato']);
						$newValoreStudiatoOggi = $doc->createElement("valoreStudiatoOggi","0");
						$newDataStudiatoOggi = $doc->createElement("dataStudiatoOggi",date("Y-m-d"));
						
						/*Attacchiamo all'elemento principale tutti i suoi figli e i corrispettivi "nipoti"*/
						$newMateria->appendChild($newNomeMateria);
						$newMateria->appendChild($newValoreDaStudiare);
						$newMateria->appendChild($newOggettoStudio);
						$newMateria->appendChild($newDataScadenza);
						$newMateria->appendChild($newNGiorniRipasso);
						$newMateria->appendChild($newValoreStudiatoOggi);
						$newMateria->appendChild($newDataStudiatoOggi);
						$newMateria->appendChild($newValoreStudiato);
						
						$newMateria->setAttribute("status", $_SESSION['status']);
						
						
						/*Inseriamo il nodo che abbiamo creato, prima del primo elemento della lista di elementi dopo root*/
						$materieElement->insertBefore($newMateria);
						$path = dirname(__FILE__)."/xml-schema/studenti.xml"; //Troviamo un percorso assoluto al file xml di riferimento
						$doc->save($path); //Sovrascriviamolo
						/***/
						/*header("Location: home-studente.php");
						exit();*/
					}
				}



				if (isset($_POST['back'])) {
					unset($_SESSION['oggettoStudio']);
					header("Location: aggiungi-materia.php");
				}
				?>
	
				<input type="text" name="valoreDaStudiare" placeholder="Quante/i <?php echo $_SESSION['oggettoStudio'] ?> devi studiare?" /> <br />				
				<input type="text" name="dataScadenza" placeholder="Inserire la data dell'esame (yyyy-mm-dd)" /> <br />		
				<input type="text" name="nGiorniRipasso" placeholder="Quanti giorni si intende ripetere?" /> <br />	
				<input type="text" name="valoreStudiato" placeholder="Inserisci quante/i <?php echo $_SESSION['oggettoStudio'] ?> hai già fatto (optional) " /> <br />
				
				<input type="submit" name="back" value="Indietro" />
				<input type="submit" name="submit" value="Continua" />
		<?php
		}
		?>
		</form>	
	</div>

</body>
</html>`

Thank you a lot for the help.

**Comment by roblourens** [comment]
Which Theme are you using? It looks like you might be using the "Dark" theme. Try "Dark+", it does a better job of coloring the variable names.

**Comment by pietro-nardelli** [comment]
Now it's better, but the bug remains! 
![cattura](https://user-images.githubusercontent.com/20285899/30399622-8f6023b4-98d4-11e7-9db5-9111b486f479.PNG)
This is the snippet until the problem
```
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Study tool</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="Your tool for studying." />
	<!--<meta name="keywords" content="">-->

	<style type="text/css">
		@import url("home-studente.css");
	</style>	
</head>
<body>
<?php
include 'functions/giorniDisponibili.php';
session_start();
if (!isset($_SESSION['accessoPermesso'])) {
    header('Location: login.php');
}

/***Procedura standard per inizializzare il file XML***/
$xmlString = ""; //Inizializziamo la variabile xmlString
foreach (file("xml-schema/studenti.xml") as $node) { //Per ogni riga del file xml...
	$xmlString .= trim($node); //Aggiungi alla stringa $xmlString la riga $node
}
$doc = new DOMDocument(); //Creiamo l'oggetto documento DOM e lo assegnamo a $doc
$doc->loadXML($xmlString); //$doc essendo un oggetto DOMDocument possiede il parser XML (metodo nella classe DOMDocument) che lo facciamo girare sulla stringa $xmlString
$root = $doc->documentElement; //la chiamata a DocumentElement restituisce la radice del documento DOM
$studenti = $root->childNodes; //$studenti contiene i nodi figli di root 
/***/

/*Scorri tutti gli studenti del file XML*/
for ($i=0; $i < $studenti->length; $i++) {
	/*Se l'email derivante dal login coincide con uno studente presente nel file XML, carica tutti i dati relativi*/
	if ($_SESSION['email'] == $studenti->item($i)->firstChild->nextSibling->nextSibling->textContent){
		$studente = $studenti->item($i); //questo sarà uno degli studenti e sarà dotato di altri figli.
		$nome = $studente->firstChild; 
		$nomeText = $nome->textContent;

		$cognome = $nome->nextSibling;
		$cognomeText = $cognome->textContent;

		$email = $cognome->nextSibling;
		$emailText = $email->textContent;

		//Questa parte è necessaria per aggiornare efficacemente il dom con $materieElement->insertBefore($newNode);
		$materieElement = $email->nextSibling; //Questo rappresenta l'elemento "materie"
		$materie = $materieElement->childNodes;  //Quest'altro invece la lista di materie
		/*Bisogna creare un array per ogni valore presente in materia, affinchè si possa successivamente
		 *elencare ed aggiornare le materie presenti nella lista. Se si creasse un array per i soli valori
		 *testuali sarebbe impossibile aggiornarli. Ogni valore $k deve appartenere ad una materia
		 *($k=>materia k-esima).
		 */
		$nomeMateriaText = array();
		for ($k=0; $k < $materie->length; $k++) {	
			$materia = $materie->item($k);

			$statusText[$k] = $materia->getAttribute('status');
			$nomeMateria[$k] = $materia->firstChild;
			$nomeMateriaText[$k] = $nomeMateria[$k]->textContent;

			//Solo per la materia planned possiamo inserire tutti i dati inerenti al piano di studi, altrimenti errore
			if ($statusText[$k] == 'planned') {
				$valoreDaStudiare[$k] = $nomeMateria[$k]->nextSibling;
				$valoreDaStudiareText[$k] = $valoreDaStudiare[$k]->textContent;

				$oggettoStudio[$k] = $valoreDaStudiare[$k]->nextSibling;
				$oggettoStudioText[$k] = $oggettoStudio[$k]->textContent;

				$dataScadenza[$k] = $oggettoStudio[$k]->nextSibling;
				$dataScadenzaText[$k] = $dataScadenza[$k]->textContent;

				$nGiorniRipasso[$k] = $dataScadenza[$k]->nextSibling;
				$nGiorniRipassoText[$k] = $nGiorniRipasso[$k]->textContent;			

				$valoreStudiatoOggi[$k] = $nGiorniRipasso[$k]->nextSibling;			
				$valoreStudiatoOggiText[$k] = $valoreStudiatoOggi[$k]->textContent;

				$dataStudiatoOggi[$k] = $valoreStudiatoOggi[$k]->nextSibling;
				$dataStudiatoOggiText[$k] = $dataStudiatoOggi[$k]->textContent;
				
				$valoreStudiato[$k] = $dataStudiatoOggi[$k]->nextSibling;
				$valoreStudiatoText[$k] = $valoreStudiato[$k]->textContent;
			}
		} 

		$riassunti = $email->nextSibling->nextSibling;
		$reputation = $riassunti->nextSibling;
		$reputationText = $reputation->textContent;

		$coins = $reputation->nextSibling;
		$coinsText = $coins->textContent;	
	}
}


?>
	<div id="lateralHomeStudente">
		<div id="logoHomeStudente">
			<a href="#">
				<!-- il logo prende l'intera grandezza del div logo stabilito dai css -->
				<img src="images/logoHome.png" style="width: 100%;"/>
			</a>
		</div>
		<div id="navigation">
			<a href="aggiungi-materia.php"><img src="images/iconAggiungiMateria.png">Nuova materia</a>
			<a href="#"><img src="images/iconArchivioMaterie.png">Archivio materie</a>
			<a href="#"><img src="images/iconRiassuntiCreati.png">Riassunti creati</a>
			<a href="#"><img src="images/iconRiassuntiVisualizzati.png">Riassunti visualizzati</a>
			<a href="#"><img src="images/iconRiassuntiPreferiti.png">Riassunti preferiti</a>
			<form action="<?php $_SERVER["PHP_SELF"] ?>" method="post" id="cercaRiassunti">		
				<input type="text" name="nome" placeholder=" Cerca riassunti" />
				<input type="image" src="images/iconCercaRiassunti.png" alt="Submit Form" />
			</form>
		</div>
		<div id="navigationUser">
			<div id="user">
				<img src="images/iconUtente.png"><?php echo $nomeText." ".$cognomeText; ?>
			</div>
			<div id="reputation">
				<img src="images/iconReputation.png" title="Reputation"><?php echo $reputationText; ?>
			</div>
			<div id="coins">
				<img src="images/iconCoins.png" title="Coins"><?php echo $coinsText; ?>
			</div>
		</div>
		<!-- Il link del logout si comporta come i precedenti ma si trova in un punto differente quindi bisogna assegnargli
			uno stile interno particolare -->
		<div id="navigation" style="top: 75px; height: 40px;">
			<a href="logout.php"><img src="images/iconLogout.png">Logout</a>
		</div>
	</div>
	<div id="main">
		<form action="<?php $_SERVER["PHP_SELF"] ?>" method="post" id="aggiungiMateria">
		<?php if (empty($_SESSION['status'])) {
			?>
			<div>
			Aggiungi una materia
			</div>
			<p>
			Puoi decidere se pianificare una materia sviluppando un <b>piano di studi</b> per arrivare all'esame preparato. 
			<br />
			Oppure puoi organizzarti autonomamente, ma in entrambi casi hai la possibilità di scrivere dei <b>riassunti</b>
			che ti permetteranno di memorizzare in maniera più efficace la materia.
			</p>
```
Can you see the same problem if you put this code in your VS Code?

**Comment by roblourens** [comment]
I do, now you are getting https://github.com/Microsoft/vscode/issues/34204, which is due to ending a PHP block inside curly braces. Watch that issue for a fix.

**Comment by roblourens** [comment]
It will be fixed in tomorrow's insiders build: https://code.visualstudio.com/insiders
