### ISSUE TITLE
extension install shows non-applicable versions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3412]
Testing #3244, I published a version for a future version of VSCode.
- ext install shows the future version even if it won't be able to install it
- show outdated show the future version even it won't be able to update to it. When trying to do so it seems as if the update really happens.
  -> would be better to at least give a message that the update failed

The best solution would be if such future versions don't even show up. That way we could put future version in the store without distracting the user on the current version.

**Comment by joaomoreno** [comment]
We don't have such information in the gallery, unfortunately.

**Comment by joaomoreno** [comment]
@modigrv Do we have any progress on this item?

Specifically, when extensions are published to the marketplace, they indicate [a specific VS Code version range they are compatible with](https://github.com/Microsoft/vscode-parinfer/blob/master/package.json#L9). Is there any way vsce can send this information to the marketplace such that VS Code can then query on this (or at least get it through version properties?).

**Comment by modigrv** [comment]
Forwarded to Marketplace PM.

**Comment by hamenon** [comment]
@joaomoreno We do have this item in our backlog, and is currently scheduled for the upcoming sprint. The current thinking is to include it in the extension manifest explicitly and have the version support information presented in the details page and include the info as part of the API response to the client.

**Comment by joaomoreno** [comment]
This has been fixed since.
