### ISSUE TITLE
  crash   ten thousand times a day

### ISSUE THREAD

**Issue by hevily** [Microsoft/vscode#34128]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
project-manager|ale|0.21.1
htmltagwrap|bra|0.0.3
python|don|0.7.0
autofilename|Jer|0.1.3
code-beautifier|mic|1.7.2
easy-less|mrc|1.4.5
sublime-keybindings|ms-|2.9.1
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.12.0
code-settings-sync|Sha|2.8.3
python|tht|0.2.3
html-snippets|wge|0.1.5
change-case|wma|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by patrys** [comment]
Please try disabling some of the extensions and see if the application still crashes without the extensions.

If it does not, try to narrow down which extension of combination of extensions causes it to crash.

If it still crashes, provide steps to reproduce.

Above all, please remove the exclamation marks from the title, they are not helping.

**Comment by hevily** [comment]
![image](https://user-images.githubusercontent.com/644260/30269052-39ce1598-971a-11e7-8c4c-4d407f5b0546.png)

**Comment by hevily** [comment]
i  will try record video/gif

**Comment by alexandrudima** [comment]
@hevily this could be caused by an extension. Does it reproduce when disabling all extensions, as @patrys suggests ?

**Comment by hevily** [comment]
ok

**Comment by hevily** [comment]
Why vscode can not know which plug-in caused by the crash?

**Comment by hevily** [comment]
i think it's  
![image](https://user-images.githubusercontent.com/644260/30305059-6b091ff2-97a3-11e7-84c0-deb8f75f2d22.png)  
cause crash

**Comment by alexandrudima** [comment]
@hevily Do you have any specific steps you do ?

So, if you are running VS Code with only that extension enabled (and all the other extensions disabled), VS Code crashes immediately ? Or does it crash only when doing a specific set of steps ?

**Comment by hevily** [comment]
disable all extension  then crash  crash  crash  again

**Comment by alexandrudima** [comment]
@hevily

Does the 32 bit also immediately crashes for you -- https://az764295.vo.msecnd.net/stable/787b31c0474e6165390b5a5989c9619e3e16f953/VSCode-win32-ia32-1.16.0.zip ? --- This is our zip release of VSCode 32bit v 1.16.

If you close the 64 bit version of VSCode and open the 32 bit version, does the 32 bit version crash immediately too? Even without opening a folder? Even without opening a file?
