### ISSUE TITLE
TreeDataProvider: allow programmatically changing the selection

### ISSUE THREAD

**Issue by patrys** [Microsoft/vscode#34133]
The default explorer view highlights the current file when the active editor changes. It would be nice to be able to match this behavior with custom tree views.

Related: https://github.com/patrys/vscode-code-outline/issues/12

**Comment by sandy081** [comment]
@patrys I see the general need of programmatically changing the selection, but not sure if I understand your usecase you related to the explorer view. Can you please elaborate what kind of custom view you have and the requirement for programmatic selection?

**Comment by patrys** [comment]
My extension displays a tree outline of the source code in the currently active editor. Ideally moving your cursor would select the appropriate code part (class, method etc.) in the sidebar.

**Comment by eamodio** [comment]
I would also like to have this ability in GitLens too. Searching for a commit or to jump from a quick pick to the custom view

**Comment by patrys** [comment]
I think this might be a duplicate of #28338 that I did not initially find.

**Comment by sandy081** [comment]
Thanks for finding the duplicate :)
