### ISSUE TITLE
Multiple monitors: the VS Code window becomes invisible

### ISSUE THREAD

**Issue by wrager** [Microsoft/vscode#34135]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. In the display settings you should have two monitors in this order: 1, 2.
2. Set the 2nd monitor the main one.
3. "Restore" the window (make it not full-size) and place it on the 1st monitor.
4. Close VSCode.
5. Set the 1st monitor the main one.
6. Open VSCode.

In the taskbar there is an active element of VSCode, but clicking on it or Alt+Tab'ing does not make the VSCode visible. Clicking on the taskbar item prompts me with the animation that the window is to the left of the 1st monitor, beyond visibility.

The problem will not be reproduced if you perform the same actions with the 2nd monitor.

The problem will be fixed if you set back the 2nd monitor the main one and move the window to it. Of course, the problem will also be fixed if you clear the `%APPDATA%\Code` folder.

Reproduces without extensions: **Yes**

**Comment by Petertaylor9999** [comment]
I am currently experiencing the same issue. On a brand new Surface Book with Windows 10 creators update.

**Comment by sepehrr** [comment]
I have the same problem. I think after updating to new version I'm facing this problem.
If VS code window is in second monitor and you open a new project in another window, it opens somewhere unreachable and invisible. (if VS Code  window is in main monitor, everything is fine)
I'm facing this problem on Windows 10.

**Comment by wrager** [comment]
This is probably a bug in Windows - I just got a similar behavior of another application

**Comment by z4ns4tsu** [comment]
I'm also experiencing this.  Different repro steps:

1. Connect a secondary display
2. Move VS Code window to secondary 
3. Disconnect secondary

Expected: VS Code "snaps to" primary monitor

Actual: VS Code remains off-screen where secondary monitor used to be

Work around: The move option dialog on the instance will let me move it back onto the primary

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35148

**Comment by tjarvis-hatchworks** [comment]
This still happens with the latest VSCODE, so not fixed

**Comment by bpasero** [comment]
@tjarvis-hatchworks what version are you running?

**Comment by sepehrr** [comment]
Problem exists for me too

**Comment by tjarvis-hatchworks** [comment]
Hi,

I am using VS Code version 1.16.1 on WIndows 10. I also use Linux versions
but I am not using multiple monitors with Linux, so I cannot check if the
issue exists with Linux too.

Thanks,

Tim

**Comment by tjarvis-hatchworks** [comment]
I have updated to version 1.17.0 and still have the same issue.

Thanks,

Tim Jarvis

**Comment by bpasero** [comment]
@tjarvis-hatchworks how exactly do you reproduce?

**Comment by tjarvis-hatchworks** [comment]
I start up vscode then I drag it to the other monitor. If I quit Vscode at
that point, when I restart it, most of the IDE is visible on the secondary
monitor but the top is generally not on the screen. If I close the Vscode
window and restarts it again, Vscode appears on the secondary monitor, but
more of the IDE screen is not available. This will occure again and again
until it is finally completely off the monitor and not visible. At this
point, I have to disconnect the secondary monitor form my machine to get
Vscode to start back on the primary monitor.

Now, if I start Vscode on the primary monitor, drag it to the secondary
monitor, use it fro a while and then drag Vscode back to the primary
monitor, when I restart it, it will start on the primary monitor just fine.
So, that is what happens on my machine with vscode

Tim

**Comment by bpasero** [comment]
@tjarvis-hatchworks what are the resolutions of your primary and your secondary monitor and is the secondary monitor to the right or to the left? What OS is this on?

**Comment by sepehrr** [comment]
@bpasero My problem still exists. I use VS Code latest version(64bit), primary monitor is 3000x2000 and secondary 1080p. I put secondary monitor on top of main monitor (not left or right), And my OS is Windows 10

**Comment by tjarvis-hatchworks** [comment]
the resolution for each monitor is 1920 x 1080. The machine OS is WIndows
10 Professional


Tim

**Comment by bpasero** [comment]
Let's move the discussion into https://github.com/Microsoft/vscode/issues/35148

**Comment by tjarvis-hatchworks** [comment]
Very good, thanks

Tim Jarvis

**Comment by bpasero** [comment]
@sepehrr @tjarvis-hatchworks to clarify, the window is moving to a slightly different position but you are not hitting a situation where the entire window is "off" screen right? If so, that would point to a different issue: https://github.com/Microsoft/vscode/issues/36122
