### ISSUE TITLE
Issue from visual code

### ISSUE THREAD

**Issue by o0sh4d0w0o** [Microsoft/vscode#34134]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
debugger-for-chrome|msj|3.2.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@o0sh4d0w0o this issue is invalid. please provide clear steps and a clear explanation.

**Comment by o0sh4d0w0o** [comment]
There is no step, this message appear always without possibilities to close it except click on submit, fix it please.
