### ISSUE TITLE
TreeDataProvider: allow selecting a TreeItem without affecting its collapsibleState

### ISSUE THREAD

**Issue by patrys** [Microsoft/vscode#34130]
Currently clicking an item will both select it and change its expanded/collapsed state. This results in very weird UX as you need to click the items to interact with them.

I have [an extension](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) that provides a tree outline of the currently opened file and clicking a class name will currently select that class in the editor and at the same time expand/collapse its children in the tree view.

Related: https://github.com/patrys/vscode-code-outline/issues/24

**Comment by eamodio** [comment]
Somewhat related to https://github.com/Microsoft/vscode/issues/28632

**Comment by weinand** [comment]
I'm bumping the severity of this since it makes the tree very difficult to use for users.

**Comment by sandy081** [comment]
@weinand May I know the explanation behind its importance?

@patrys @eamodio May I know your expectation in this case. Is your request is to support command only for leaf items?

**Comment by weinand** [comment]
Today I learned that all VS Code trees behave like this.

So all VS Code trees collapse/expand when a node is selected.
For the standard VS Code trees (e.g file explorer) this is not a problem because the only purpose of selecting a non-leaf node is to expand or collapse it, so selecting a non-leaf node is not really needed because the node itself is never fed into an editor.

For custom trees the story is not so clear:
In a custom tree a non-leaf node might feed into an editor and expanding its children could be an expensive operation. So it is questionable whether both purposes should be coupled into one gesture.
If a user only wants to select the node in order to open it in an editor, this is not possible without expanding all children at the same time.

Since the current behaviour is consistent with the other VS Code trees, I think this is not a bug but a feature and we can remove the "important" flag.

**Comment by patrys** [comment]
@sandy081 My extension shows a code outline so containers can be classes while leaves are functions, I'd very much like to support commands at all tree levels in a way that does not affect the tree state.

**Comment by eamodio** [comment]
For me, it is less about the user clicking on an item, and more about having an api (way) to not only set focus to the tree, but select an item -- and ideally control whether or not it expands when selected via that api.

**Comment by weinand** [comment]
@eamodio this is a different issue. You are asking for new API which is already covered by #30288.

**Comment by eamodio** [comment]
@weinand very true -- I had originally wanted something like this (where the user controlled it -- I opened https://github.com/Microsoft/vscode/issues/28632), but while I still think it could be useful (for example in GitLens, there are nodes in the tree that both have children and could support a click command themselves) I am worried about the user experience of it. Unless the whole tree behaves the same way, I think it would be strange for a user, if sometimes clicking on a node would expand it and sometimes it might execute a command. Anyway my 2c :)

**Comment by patrys** [comment]
I think it would be less surprising if the tree behaved more like native platform trees: usually clicking the name selects/activates items while clicking the chevron or pressing the left/right arrow key collapses/expands the tree.

**Comment by sandy081** [comment]
@eamodio I agree with your point about consistency. As mentioned, all tree in VS Code are now consistent in how to expand, collapse and selected. In order to separate commands from expand/collapse, how about exposing primary commands on nodes. Eg:

![image](https://user-images.githubusercontent.com/10746682/33529851-9dae772c-d876-11e7-9cc3-3556e1282c92.png)

I would still allow command on selection which extension authors can decide to have or not to have on leaf nodes and parent nodes.

**Comment by patrys** [comment]
@sandy081 How do you imagine this helping with a [code outline type of extension](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)?

**Comment by sandy081** [comment]
@patrys Agreed, it wont help such extensions. Unfortunately I have to be consistent with current tree behaviour in VS Code.

**Comment by zigmondy** [comment]
Running into exactly same issue. Can you please prioritize the fix and allow extensions to override the behavior?

**Comment by DanTup** [comment]
This is somewhat blocking a feature for us too; I'm wondering if I can workaround it by forcing the tree to re-render and adding new items that are set to collapsed? (it would kinda suck though!)

**Comment by eamodio** [comment]
@DanTup Since I don't need the behavior for when the user clicks on an item, I've been waiting for https://github.com/Microsoft/vscode/issues/30288 so that I wouldn't have to play around with what you suggest -- force a re-render and change the collapsed state.

**Comment by DanTup** [comment]
@eamodio I was just playing with that in insiders (couldn't make it work though, it calls `getParent` until it gets to my root and I return `null` and then it crashes saying it can't resolve the tree item). I need that too (need to select outline nodes as the user moves around the editor), but it doesn't excuse this - the user clicking on the nodes causing collapses is super-wonky.

**Comment by TomasHubelbauer** [comment]
This is super annoying, I've upvoted both this and Microsoft/vscode#28632 (where the last comment is about awaiting feedback to justify it but three months in VSCodeBot closes down the conversation, oh, how I love VSCodeBot) but feel like I need to vouch for the importance of considering this with a comment, too! The UX on custom trees is extra trippy, certainly unpleasant and I wish it can be rectified.

**Comment by sandy081** [comment]
May I know every body asking for this requirement is for Outline views? Or is there some other type of custom view needed this? If so, can you please mention.

Thanks

**Comment by TomasHubelbauer** [comment]
If by Outline view you mean just the things like classes, methods etc. then I have another use case. My VS Code extension [MarkDown To-Do](https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-todo) would benefit from this, I would keep expanding MarkDown file items with their headers and the checkboxes corresponding to those headers underneath them.

**Comment by DanTup** [comment]
@sandy081 Ours is an outline view, however it's kinda specialised (doesn't map directly onto Code like a normal outline, and we'd probably also have a standard outline) if that's relevant (eg., if you built in a standard outline view, I don't think that's solve the problem for us).

**Comment by zigmondy** [comment]
Hopefully the capability to suppress collapse on click is built some day. VS code tree view extension feels so limited because of this issue :( !!!

**Comment by sandy081** [comment]
>> For me, it is less about the user clicking on an item, and more about having an api (way) to not only set focus to the tree, but select an item -- and ideally control whether or not it expands when selected via that api.

@eamodio I suppose your requirement mentioned here is supported now using the existing APIs

**Comment by sandy081** [comment]
Here are the two proposals I can think of as solution

1. Have a tree property like `expandOrCollapseOnTwisty` and let every node in the tree honours this.

2. If a tree node has a command, then Expand/Collapse it only when user clicks on twisty, otherwise do it when user clicks any where on the node.

**Comment by eamodio** [comment]
@sandy081 AFAIK there still isn't an api to select an item in the tree and have it expand or collapse though right?

**Comment by sandy081** [comment]
@eamodio There is reveal API to select, but not to expand or collapse. Is there an issue you opened where we can discuss about it?

I also liked #2 and implemented.

- If a node provides command, then node is expanded/collapsed only when user clicks on the twisty. Also, command will not be executed when user clicks on twisty.

**Comment by eamodio** [comment]
@sandy081 We talked about it back during the `reveal` api discussion, but I don't have a strong enough need for it at this point, so I'll leave it be ;)

**Comment by DanTup** [comment]
@eamodio I haven't tried it, but does changing `collapsibleState` and then fire an update for the node work? (it's not nice, sure, but if it works?)

**Comment by TomasHubelbauer** [comment]
This has not shipped as a part of the June milestone, right? Can the milestone be updated to the next one in case this is projected to land in it?

**Comment by sandy081** [comment]
@TomasHubelbauer This is fixed in June milestone and is available in the latest 1.25 (June) stable release.

May I know why do you think so?

**Comment by zigmondy** [comment]
I've also verified in latest version 1.25 and works beautifully!! Thanks for addressing it.
