### ISSUE TITLE
Terminal: lost ability to ctrl+click on links

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34132]
I am using TMUX on macOS and I was always able to click on a link in the output to open it in the editor. I think with the new canvas implementation I am no longer seeing links.

**Comment by Tyriar** [comment]
@bpasero any more info (workspace/path) or a screenshot of the link you're trying to click?

**Comment by bpasero** [comment]
@Tyriar output from "npm run watch":

![image](https://user-images.githubusercontent.com/900690/30284437-38dc64b8-971b-11e7-89ea-14986617c4fd.png)

**Comment by AlQuraian** [comment]
I'm facing the same issue. On Windows 10, latest VS Code. Tried cmd and powershell.
Whatever output has a local link, it's not clickable anymore.

**Comment by mkuratczyk** [comment]
I have the same on two macOS machines. URLs are clickable but paths are not - neither in the editor nor the terminal. URLs are underlined in the editor but not in the terminal but they are clickable in both places with CMD key. I've tried both stable and insiders builds.
<img width="389" alt="screen shot 2017-09-19 at 20 39 24" src="https://user-images.githubusercontent.com/9566114/30611935-e67301e4-9d7a-11e7-8861-df47fced8a1f.png">

**Comment by straiki** [comment]
Hey,
similar issue here.. link is clickable, but click handler seems to be just badly positioned..
Win10, latest code, powershell.
![image](https://user-images.githubusercontent.com/724967/30692752-368c61ea-9ecd-11e7-9075-a297b7c0f11f.png)

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/34967

**Comment by bpasero** [comment]
Nice!
