### ISSUE TITLE
Show image dimensions

### ISSUE THREAD

**Issue by janmarek** [Microsoft/vscode#3414]
It would be nice to see image dimensions when I open image in VSCode. Atom shows that information in status bar.

**Comment by bpasero** [comment]
In the native browser hower I am now showing the image dimensions. Thats a good start for this feature 👍

**Comment by bpasero** [comment]
Verification: we show image dimensions and file size (latter for all binary files) in the right corner of the status bar.

**Comment by janmarek** [comment]
Thank you guys
