### ISSUE TITLE
Code Terminal VIM Auto Inserts Text Value

### ISSUE THREAD

**Issue by lucentminds** [Microsoft/vscode#34145]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.9-300.fc26.x86_64
- Fedora 26 with KDE Plasma
- Extensions: none 

---
While commiting a project with git I noticed that when I started vim by itself or git started vim, there is text that gets pre-inserted into the document. This means I always have to enter `:q!` if I don't want to actually enter text myself. I recognize the inserted text as a password that I used the other day to log into a remote ssh session and an ftp session. I've restarted the machine more than once since I've notice this happening. This does NOT happen if I start a standard terminal session in konsole or tilix. Any help on finding where this information is being stored would be awesome.

Steps to Reproduce:

1. Open terminal session in vscode.
2. Start a vim instance in terminal by typing `vi` or `vim`
3. Text is somehow auto inserted into the empty vim document.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Weird, there was one other report of this https://github.com/Microsoft/vscode/issues/33173, not sure what it could be.

**Comment by mbcoguno** [comment]
It looks like trigger something to put last yank line when launch vim inside vscode's terminal. It can reproduce on my machine. neovim does not happen.

**Comment by ralberto** [comment]
Same here as reported by @lucentminds

**Comment by wyattjoh** [comment]
Been experiencing this issue for a while as well.

**Comment by lucentminds** [comment]
Just found out something. If I delete all of the registers in `~/.viminfo` or delete everything in the `~/.viminfo` file, the value is no longer pasted into the file, but an error shows up at the bottom of the screen: `E353: Nothing in register "`. So even though there is nothing in the register, it's still trying to paste the register contents.

**Comment by wyattjoh** [comment]
Encountering exact same as @lucentminds. I've additionally deleted my `~/.vimrc`, and `~/.vscode` with no change beyond the error that was mentioned.

**Comment by lucentminds** [comment]
Looks like this was fixed. In the last updates since I noticed this. This isn't happening anymore, and no errors when I delete all of my registers.

**Comment by jerry1100** [comment]
I've been experiencing this issue for a while now too. When opening vim inside the integrated terminal, the contents of register `"` gets pasted, as if `p` was automatically pressed.

Also, as @lucentminds pointed out, deleting `~/.viminfo` (which clears the registers) and opening vim results in the message `E353: Nothing in register "`.

VSCode Version: 1.18.0
OS: macOS Sierra 10.12.6

**Comment by bentheax** [comment]
I'm getting this behaviour as well, for as long as I can remember, but currently with the same versions as @jerry1100 .

I have multiple workarounds to share.

Firstly, if I run `tmux`, then I don't encounter any problems.

Secondly, I also noticed that I've set a `TERM=screen-256color` in my tmux config. So I tried to set `TERM=screen` or `TERM=screen-256color` without first running `tmux`, and that also resolved the issue for me.

It seems like, at least in the way that I'm experiencing this bug, that when the terminal is set to `xterm`, `vim` sends some escape codes that the embedded terminal reacts to in an unexpected way.

**Comment by bentheax** [comment]
The terminal emulator is meant to set this value to something that it understands and is compatible with, but maybe there's something in my/our environments that sets it to a value it shouldn't.

When I try a slightly-nicer workaround of setting `TERM` in the vscode configuration, I'm out of luck:

```
 "terminal.integrated.env.osx": {
    "TERM": "screen-256color",
    "VSCODETEST": "screen-256color"
  }
```

Only `VSCODETEST` is applied.

**Comment by jerry1100** [comment]
I decided to do some digging and used a nice [keylogger program](https://gist.github.com/tylerneylon/dd9d8e73345aa7a47af7) to capture the escape codes being sent from 1) the native terminal on OS X and 2) the integrated terminal on VSCode when opening vim.

os x:
```
ESC[2;2RESC[>1;95;0c:q
```

vscode (added line breaks for visibility):
```
ESC[2;2RESC[>0;276;0cESCP0+r436fESC\ESCP0+r6b75ESC\ESCP0+r6b64ESC\ESCP0+r6b72ESC\
ESCP0+r6b6cESC\ESCP0+r2332ESC\ESCP0+r2334ESC\ESCP0+r2569ESC\ESCP0+r2a37ESC\ESCP0+r6b31ESC\
ESCP0$rESC\ESCP0+r6b32ESC\ESCP0+r6b33ESC\ESCP0+r6b34ESC\ESCP0+r6b35ESC\ESCP0+r6b36ESC\
ESCP0+r6b37ESC\ESCP0+r6b38ESC\ESCP0+r6b39ESC\ESCP0+r6b3bESC\ESCP0+r4631ESC\ESCP0+r4632ESC\
ESCP0+r2531ESC\ESCP0+r2638ESC\ESCP0+r6b62ESC\ESCP0+r6b49ESC\ESCP0+r6b44ESC\ESCP0+r6b68ESC\
ESCP0+r4037ESC\ESCP0+r6b50ESC\ESCP0+r6b4eESC\ESCP0+r4b31ESC\ESCP0+r4b33ESC\ESCP0+r4b34ESC\
ESCP0+r4b35ESC\ESCP0+r6b42ESC\:q
```

Here are the raw log files:
[terminal_out.log](https://github.com/Microsoft/vscode/files/1752910/terminal_out.log)
[vscode_out.log](https://github.com/Microsoft/vscode/files/1752911/vscode_out.log)

I also tested VSCode's integrated terminal with `TERM` set to `screen` and `screen256-color`, as well as opening vim inside tmux, and in those cases, the long sequence of `ESCP0+r...ESC` were not there.

**Comment by jerry1100** [comment]
The behavior went away for me. Anyone else still experiencing this issue?

VSCode Version: 1.25.1
OS: macOS High Sierra 10.13.6
