### ISSUE TITLE
Search in Files: toggle for "Use Exclude Settings" does not work

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/vscode#34140]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
githistory|don|0.2.3
gitlens|eam|4.4.3
tslint|eg2|1.0.2
JSDocTagComplete|Hoo|0.0.2
docthis|joe|0.4.8
comment|kar|5.0.0
regex-railroad-diagrams|kog|0.2.4
vs-color-picker|lih|0.6.0
team|ms-|1.122.0
vscode-filter-json|ric|1.0.0
vscode-sort-json|ric|1.9.0
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
standard|shi|0.2.3
code-spell-checker|str|1.3.9
vscode-todo-highlight|way|0.5.11
JasmineSnippets|xab|1.0.0

---

irrespective of the status of the toggle, whatever extensions are currently inside the "files to exclude" field are excluded from the search
![image](https://user-images.githubusercontent.com/24651374/30272475-fa5f5aa4-96f4-11e7-82f2-666af4ed25a6.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
The toggle only affects *settings*, ie the `files.exclude` and `search.exclude` settings. Text in the viewlet will still be respected.

That was on purpose, I think it's useful to disable the settings excludes and provide a different set.
