### ISSUE TITLE
Syntax highlight issue

### ISSUE THREAD

**Issue by EduardJS** [Microsoft/vscode#34144]
I have the latest version of VSCode ( stable ), and I'm not sure if this is a theme issue or it's related to VSCode itself. ( I have One Dark Pro installed as theme ).

[Here is a screenshot](http://i.imgur.com/ZzzTx01.png). As you can see, the HTML code within the PHP tags is wronngly highlighted, though the tags are closed correctly.

Regards!

**Comment by roblourens** [comment]
This should be fixed in 1.16.1, try it out. If it isn't fixed, post the full code snippet here.
