### ISSUE TITLE
Error opening/debugging Powershell

### ISSUE THREAD

**Issue by d1964b** [Microsoft/vscode#34148]
[1505138349-1b3696d4-d5ef-4ba9-b68c-3b6d7eedb04e1505138345318.zip](https://github.com/Microsoft/vscode/files/1292816/1505138349-1b3696d4-d5ef-4ba9-b68c-3b6d7eedb04e1505138345318.zip)

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.2

---

Steps to Reproduce:

1. open file - select existing ps1
2. Set Break point - start debug

Reproduces without extensions: No

**Comment by aeschli** [comment]
This issue was moved to PowerShell/vscode-powershell#1192
