### ISSUE TITLE
extract method doesn't indent code correctly

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#34147]
As you can see, the brand new `Extract Method` functionality is not indenting the code correctly.

![screenshot from 2017-09-11 16-09-01](https://user-images.githubusercontent.com/984628/30278834-dc7c8c3e-970b-11e7-983e-a7ac2b84895b.png)
![screenshot from 2017-09-11 16-09-13](https://user-images.githubusercontent.com/984628/30278835-dc7ee1aa-970b-11e7-962f-6b080085c646.png)
![screenshot from 2017-09-11 16-09-17](https://user-images.githubusercontent.com/984628/30278836-dc816b6e-970b-11e7-9bb4-70382c65c738.png)

- VSCode Version: Version 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953)
- OS Version: Kali Linux (Rolling Release based on Debian Sid)

**Comment by mjbvz** [comment]
Thanks. We are tracking this upstream with https://github.com/Microsoft/TypeScript/issues/18328
