### ISSUE TITLE
Differentiate (partially) staged changes from unstaged changes

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#34149]
- VSCode Version: 1.16
- OS Version: Win 10

Steps to Reproduce:

1. Partially stage some changes (from the ... menu (top right) select "Stage selected ranges")
2. Open the 2 views of the same file from Source Control sidebar - first by clicking the file under "Staged Changes" which should open it with a "(Working tree)" suffix, and second by clicking the same file under "Changes" which should open it with a "(Index)" suffix. 

Both views show exact same contents. So you can't easily identify which lines were (partially) staged:

![2017-09-11_19-54-05](https://user-images.githubusercontent.com/2523987/30279617-5a6424bc-972b-11e7-914d-8062f0a4e93b.gif)

This is different from `git gui` which correctly shows the relevant views (stages/unstaged):

![2017-09-11_20-03-46](https://user-images.githubusercontent.com/2523987/30280042-620a5d52-972c-11e7-9109-fa04556271a7.gif)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Actually, that should not be happening. It does not reproduce for me. I believe you are facing a line ending issue. `git gui` might be ignoring line ending changes.

Can you try it on another file from another repository?

What are your line ending git settings?

**Comment by laggingreflex** [comment]
You're right about the newline thing. But my main issue is that it's still not easy to distinguish staged changes from unstaged changes. 

As I understand VS Code has two views: 

* Staged changes 
* Changes (which is ALL changes: staged + unstaged)

This is different from Git GUI which has:

* Unstaged changes
* Staged changes 

I guess I'm more used to the Git GUI's way of things. My workflow is such that I stage lines one by one, and so I need to know which lines are left unstaged to decide whether to stage them or not. Having a separate view with *just* the unstaged changes would be a great help in this case.

**Comment by joaomoreno** [comment]
We have exactly the same git gui has. If you fix the line ending issue, please check again. One view shows you the staged changes. The other, the unstaged ones only.

**Comment by laggingreflex** [comment]
Ah yes, you're right. I think it was the not-updating-the-view issue (#34232) that led me to thing this wasn't the case.
