### ISSUE TITLE
[css] insert semicolon on property suggestion

### ISSUE THREAD

**Issue by bymomo** [Microsoft/vscode#34141]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
sublime-keybindings|ms-|2.9.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.编写css文件的时候没有自动补全。
2.比如输入background，然后按快捷键，只是出现background: 并没有 ; 这个符号 
![image](https://user-images.githubusercontent.com/28828166/30272566-ac17a0d0-9727-11e7-8a90-96aaa315cb34.png)
3,这样子才是我需要的，看下面的图片。

4，sublime有自动补全;这个符号的功能

Reproduces without extensions: Yes/No

**Comment by bymomo** [comment]
![2](https://user-images.githubusercontent.com/28828166/30272752-9ace90c6-9728-11e7-9450-a2162e9a1a55.png)

**Comment by snikeguo** [comment]
@bymomo   你说中文，谁能看的懂。。。
Americans do not understand Chinese .....

**Comment by rcjsuen** [comment]
What @bymomo wants is for code completion to insert `background: ;` and not simply `background: `

In snippet lingo I believe it would be `background: ${1};`.

**Comment by rcjsuen** [comment]
See #32200.

**Comment by bymomo** [comment]
@rcjsuen 对啊  支持support

**Comment by bymomo** [comment]
1. When writing CSS files, there is no automatic completion.
2. For example, input background, and then press the shortcut key, but background: no;This symbol
The image
3. That's what I need. Look at the picture below.
4. Sublime has automatic completion;The function of this symbol

**Comment by bymomo** [comment]
wants is for code completion to insert background: ; and not simply background:

In snippet lingo I believe it would be background: ${1};

**Comment by octref** [comment]
Sublime doesn't do this.
![image](https://user-images.githubusercontent.com/4033249/39891086-8df466e6-5451-11e8-90dc-ea476eba5800.png)

Adding `;` towards the end is awkward since then after entering value you can't press <kbd>enter</kbd> to open a new line.
