### ISSUE TITLE
VSCode's colors are very dull

### ISSUE THREAD

**Issue by AlanRosenthal** [Microsoft/vscode#34146]
- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:16:01.987Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gitlens|eam|4.4.3
cpptools|ms-|0.12.3
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.3.9
highlight-trailing-white-spaces|yba|0.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

I restarted my computer and now vscode's colors are very dull.
now: 
![image](https://user-images.githubusercontent.com/1288897/30277646-73ac26cc-96d6-11e7-9e68-dd87a1006083.png)
before:
![image](https://user-images.githubusercontent.com/1288897/30277659-7adbb7e6-96d6-11e7-89ac-233a7f54a3d4.png)

**Comment by AlanRosenthal** [comment]
Same dullness for other themes

**Comment by aeschli** [comment]
Looks like that a different font has been picked. 
Our font settings for Linus are: "Droid Sans Mono", "Courier New", monospace, "Droid Sans Fallback". Looks like 'Courier New' is used now.
Can you check that 'Droid Sans Mono' is available?

Note that you can configure the font in the user settings.

**Comment by jhasse** [comment]
Should also be fixed by #34947.
