### ISSUE TITLE
Feature request: open file in a new window except if the file's folder is opened

### ISSUE THREAD

**Issue by mr7432631** [Microsoft/vscode#34143]
- VSCode Version: 1.16.0
- OS Version: Windows 10 (64-Bit)

Feature request: the setting, "window.openFilesInNewWindow": "off", should have an additional option where: opening a new file should open in a new window except if the file's folder is opened, in that case it should open in the file's folder window

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
