### ISSUE TITLE
TreeDataProvider should support a way to deal with many children (paging or streaming)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#34151]
Currently `TreeDataProvider.getChildren` supports returning a promise for async filling of a node, but in some cases (in GitLens for example) providing all children of a node could be very costly (in terms of both time and usability). It would be great if there was a built-in way to provide some form of paging/streaming of children (i.e. infinite scrolling). Or at least maybe some way where a `TreeItem` could be marked as "inline expanding" -- meaning when you click on that item it would be removed and replaced with its children? (Could maybe even have it as `TreeItemCollapsibleState.InlineExpand` or something?).

Personally I like the idea of being able to have an "inline expanding" node -- i.e. a *more* from both a usability and perf view point -- because while infinite scroll is nice in some cases, in a tree it doesn't seem ideal, as you end up having to keep scrolling past stuff you may or may not care about to get to a further down item in another "branch".

If there is already some mechanism to handle this I'm all 👂 as well 😄. As I'm struggling with this a bit in the new GitLens custom view, where I show the history of a branch and I don't want to show the entire history all at once (because of the time involved). I've implemented a custom paging solution for use in the quick picks, but so far I haven't found a solution I like (ux wise) in the custom views.

@sandy081

**Comment by patrys** [comment]
@eamodio Would it work if `getChildren` was replaced by `getChildrenCount()` and `getChildAtIndex(index: number)`? As all items have similar metrics this could be used to implement a sliding window renderer. Both could default to using `getChildren` internally so extensions with just a bunch of items would not have to deal with per-item retrieval.

**Comment by eamodio** [comment]
@patrys I don't think so for my case -- I'm trying to load in the Git history of a branch, and I can cap the history returned to a number (say 200 entries), but it doesn't tell me how many there are in total. So all I really know is that there are more.

So what I am doing right now is when I know there is more than 200 (that number is configurable), I add a node at the end saying `Show All Commits -- this may take a while`

![image](https://user-images.githubusercontent.com/641685/30335957-aec18154-97b1-11e7-848e-278770bc3028.png)

And when the user clicks on that, I refresh the whole parent node without the 200 cap. Not ideal, but it works. Rather what I would like to do is add a `Show Next x Commits` instead of the show all, and when the user clicks on that node, that node is removed and replaced with its children. That way I could have an incremental opt-in expansion for more.

Hope that makes sense.

**Comment by sandy081** [comment]
@eamodio Good approach in fetching items efficiently, hopefully it helps @patrys 

I do not think we support loading in pages/batches in any of our API. All providers fetch and provide all items.

**Comment by eamodio** [comment]
@sandy081 yeah, its workable (though painful for large repos), but I would really love to have something like outlined above -- so instead of needing to refresh the whole parent, I could just get the commits between a range and add them to the list. With something like that there doesn't need to be any sort of streaming -- just a way to mark a node as this special type (i.e. inline-expand) and then when clicked (or just refreshed) it could be replaced with its children
