### ISSUE TITLE
Launch config wraps args in quotes

### ISSUE THREAD

**Issue by guycnicholas** [Microsoft/vscode#34153]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.0
vscode-npm-script|eg2|0.2.1
sublime-babel-vscode|jos|0.2.8
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.1
vscode-icons|rob|7.12.0

Steps to Reproduce:

1. Launch with
```js
{
			// Name of configuration; appears in the launch configuration drop down menu.
			"name": "Run app-server tests",
			// Type of configuration. Possible values: "node", "mono".
			"type": "node",
			"request": "launch",

			// Workspace relative or absolute path to the program.
			"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
			// Automatically stop program after launch.
			"stopOnEntry": false,
			// Command line arguments passed to the program.
			"args": ["$(find ./test -name '*.js')"],
			// Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
			"cwd": "${workspaceRoot}",
			// Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
			"runtimeExecutable": "${workspaceRoot}/node.sh",
			// Environment variables passed to the program.
			"env": { "NODE_ENV": "development"}
}
```
2. Command line call ends up single quoting the args which causes the command to fail. Here is the output `node.sh --inspect=36920 --debug-brk node_modules/mocha/bin/_mocha '$(find ./test -name '*.js')' `

Reproduces without extensions: Yes/No

**Comment by guycnicholas** [comment]
I want to clarify (I have been working to get around the issue). The problem isn't that it is wrapping the args in quotes, it is that the args for me is actually a bash command to list all the files in a directory.  I need the command to execute and the results to written out as args.

**Comment by weinand** [comment]
Currently what you are trying to do is not supported.
You could try to use an argument that does not contain any spaces and will not be quoted by VS Code, e.g. a bash function.

**Comment by weinand** [comment]
We cannot support correct quoting for all possible combinations of shells and OSes.
I suggest to move the `$(find ./test -name '*.js')` into a shell script and refer to that from the launch configuration.
