### ISSUE TITLE
Newly created and saved file, when closed, doesn't appear in 'Open Recent...' list

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#34154]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.1.38
python|don|0.7.0
wordcounter|kir|1.2.0
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.2
blank-line-organizer|rin|0.1.2
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Double-click an empty area on the tab bar to create a new Untitled text file.
2. Type some text, hit Ctrl+S to save it, and give the new text file a name.
3. Click 'x' on the tab to close the newly created file.
4. Hit Ctrl + R to list recent files. Notice that the one you just saved isn't there.

Depending on how long you had the Untitled one open before saving it, you'll either see no entry at all for the file you just closed, or you'll see it with its 'Untitled' name, which of course can't be opened when you select it.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
That list is only for files that are opened externally. For editors within the instance you can use the editor history: Cmd/Ctrl+P

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
