### ISSUE TITLE
JavaScript snippets don't work in JavaScript React

### ISSUE THREAD

**Issue by janmarek** [Microsoft/vscode#3415]
When I type for example "fun" and press tab I expect to see

```js
function name(params) {
        
}
```

but I see

```html
<fun></fun>
```

instead.

**Comment by egamma** [comment]
This comes from emmet which we enabled for React.

```html
<fun></fun>
```
@aeschli Suggest to also register the javascript.json snippets for javascriptreact.

Suggest to get this in for Feb since we will say that we improve the .jsx support.

**Comment by janmarek** [comment]
Would it be possible for javascriptreact to inherit (user defined) javascript snippets?

**Comment by deathmood** [comment]
just downloaded 0.10.10-insiders --- and it expands to function definition. But there is another problem --- *.js files with jsx inside are opened as `JavaScript` and emmet does not work. But if I switch language to `JavaScript React` emmet works.

Is there any possibility to enable emmet in files with *.js extension?
