### ISSUE TITLE
Feature request: separate UI state for edit and debug mode

### ISSUE THREAD

**Issue by saravanaj** [Microsoft/vscode#34155]
Similar to how Visual Studio remembers the state of panels and windows separately for debugging and editing.

When I am editing I have the sidebar and bottom panel hidden. When I start debugging I have to manually activate the "Debug" sidebar and the "Debug Console". And I have to hide everything again once I stop debugging.

**Comment by isidorn** [comment]
Please use the following settings
```json
"debug.openExplorerOnEnd": true,
"debug.internalConsoleOptions": "openOnSessionStart"
```

**Comment by saravanaj** [comment]
@isidorn  I know about those options and that is not what I meant.

1. When I edit a file I do not have any sidebar or console open:
![edit-view](https://user-images.githubusercontent.com/1573565/30318884-f59e5132-97cb-11e7-9182-a2af55705bc9.png)

2.  When I debug the file and stop the debugger, I end up with this:
![debugger-stopped](https://user-images.githubusercontent.com/1573565/30319257-04986d0c-97cd-11e7-8f6c-991d131bc217.png)

I do not want to see the "Debug Console" when I am back in edit mode. Maintaining the UI state separately (similar to Visual Studio) for debug and edit mode would fix this.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27871
and some other open issues

VS Code is a minimalistic code editor and we try to minimise automatic UX changes.
