### ISSUE TITLE
Bug on save .groovy files

### ISSUE THREAD

**Issue by LuaXD** [Microsoft/vscode#34166]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
vscode-docker|Pet|0.0.16
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|4.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.3
vscode-npm-script|eg2|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
rest-client|hum|0.15.2
docthis|joe|0.4.8
Angular2|joh|2.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.1.0
mono-debug|ms-|0.15.7
PowerShell|ms-|1.4.2
debugger-for-chrome|msj|3.2.1
Ruby|reb|0.15.0
java|red|0.9.0
vscode-icons|rob|7.12.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.1
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Try to save (some) groovy files
2. Is not possible save, don't show error, or problems

Reproduces without extensions: Yes
[bug.mkv.zip](https://github.com/Microsoft/vscode/files/1293957/bug.mkv.zip)

**Comment by LuaXD** [comment]
This problem only happens to me on groovy files.

**Comment by alexandrudima** [comment]
@LuaXD Does this reproduce when disabling all extensions ? (either from the extensions viewlet + restart or by launching `code --disable-extensions` ) ?

AFAIK we have API for extensions to participate in saving in case you have turned on format on save. Perhaps one of your extensions participates in the saving of groovy files ? In any case, is there an error message shown? If you open developer tools (Help > Toggle Developer Tools) do you see any errors in the console ?

I have looked at the `.mkv` video you have attached, but unfortunately it is clipped in a funny way which prevents me from seeing all the steps that you are doing.
