### ISSUE TITLE
Can not bind Ctrl+Tab to workbench.action.quickOpenTerm

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#34168]
- VSCode Version: 1.16 Insider
- OS Version: macOS

Steps to Reproduce:

1. Tried to bind my favorite keyshort ctrl+tab to terminal tab switching
2. Ctrl+tab works when binding to workbench.action.terminal.focusNext
3. Ctrl+tab inserts tab when binding to workbench.action.quickOpenTerm, however you can see ctrl+tab when searching for Switch Active Terminal command in Command Palette.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
It's a little involved messing with ctrl+tab, here's how I make it work on Linux:

Add `workbench.action.quickOpenTerm` to the commandsToSkipShell setting.

Then add keybindings something like this:

```js
{
	"key": "ctrl+tab",
	"command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
},
{
	"key": "ctrl+tab",
	"command": "workbench.action.openNextRecentlyUsedEditorInGroup",
	"when": "!terminalFocus"
},
{
	"key": "ctrl+tab",
	"command": "workbench.action.quickOpenTerm",
	"when": "terminalFocus"
}
```
