### ISSUE TITLE
Polish task snippets

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3416]
Related to #3159 #3413

As discussed in triage, I reverted commits 8004d27, b7e9c82 and a7a0f82 which introduced snippet support for `tasks.json`. The reverts are: 9d64fe7, 9c5cefb and 856fb0b.

The experience needs to be improved, the user needs more guidance towards creating a final, working `tasks.json` file.

>Joao Moreno [15:08]:
hi Erich?
Erich Gamma [15:08]:
hi
Joao Moreno [15:08]:
sorry to bug you
Erich Gamma [15:08]:
no prob
i'm working anyways
Joao Moreno [15:09]:
i have a feeling Dirk left his task stuff halfway done: https://github.com/Microsoft/vscode/issues/3159
it's very hard now to generate a tasks file. I even went through our documentation and couldn't figure it out
meaning: I tried setting up a build task with the ts compiler, and still didn't make it. maybe this needs more thought?
Erich Gamma [15:11]:
This definitely came in hot. I have never used it end to end and only looked at the point feature, which made sense.
Joao Moreno [15:11]:
got it
Erich Gamma [15:11]:
Let me give it a try as well
Joao Moreno [15:12]:
please do. if you feel the same, I propose to undo it and polish it when dirk is back
Erich Gamma [15:12]:
agreed, I'll get back to you
Joao Moreno [15:12]:
thanks!
Erich Gamma [15:31]:
Tried and I got it to work, but there are issues and I suggest to rollback and revisit the experience.
I'll file an issue
unless there already is one
Joao Moreno [15:34]:
there isn't one for rolling back, no
just small ones for the isolated hickups in the experience
Erich Gamma [15:36]:
ok, then this is good enough and I suggest that you discuss this in the triage and suggest to roll back the change, since Dirk cannot address the hickups and you have my support for this.
Joao Moreno [15:36]:
thanks!

**Comment by dbaeumer** [comment]
Discussed with Joao the concerns he raised and demoed him and Erich the new implementation.

**Comment by dbaeumer** [comment]
Marking as verified since the story got obsolete.
