### ISSUE TITLE
New Integrated Terminal and multi-root

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#34163]
The only way I see to control which root a new terminal will open in is through opening a file under that root. That is not very convenient when I don't have such a file open and don't need to open one for other reasons.

Maybe the '+' could be changed to a drop-down button with a click on the button itself would have the same behavior as now and the drop-down would show the list of roots to choose from.

**Comment by Tyriar** [comment]
The idea behind this was that we wanted to avoid having a dropdown every single time, instead we assume that the user wants the terminal in the root folder of the active file, as they're currently work on it.

**Comment by chrmarti** [comment]
I agree with using the active file as a hint, but there should also be a way for me to choose a root explicitly.

**Comment by Tyriar** [comment]
The plan is to have 2 different behaviors depending on how you create the new terminal:

- ctrl+shift+`: Create based on the active file
- + icon on panel: Dropdown to select the folder
- + icon on terminal quick open: Dropdown to select the folder

**Comment by bpasero** [comment]
@Tyriar fyi there is now a command to bring up a workspace folder picker: `commandService.executeCommand(PICK_WORKSPACE_FOLDER_COMMAND).then(workspace => {})`

**Comment by Tyriar** [comment]
@bpasero does that mean VS Code now have an active folder concept?

**Comment by bpasero** [comment]
@Tyriar no, but we added one UI for everyone to use if the picker is needed. Some examples where we need it:
* when generating files out of a template from an extension to ask where to generate the files to (vscode-docker extension)
* when running the action to configure workspace recommendations on a certain folder to pick the folder where to add the recommendations to
* when running the command to "Open Folder Settings" to pick the folder to open

**Comment by Tyriar** [comment]
@bpasero sounds great, thanks 😃

**Comment by Tyriar** [comment]
Here is the new behavior in a multi-root context:

- ctrl+shift+` should create a terminal in the current file's root, same as before
- + button on panel should present a workspace selector
- Right-click context menu on terminal panel should present a workspace selector
- 'term ' quick open should present a workspace selector

**Comment by Tyriar** [comment]
I ended up changing my mind on the UX for ctrl+shift+`, all create terminal actions will now show the workspace selector if there are > 1 folders. Feels much better/less confusing in multi-root.
