### ISSUE TITLE
can't format code, option   shift   f, it's show 'Ï ', open command panel can't found format line

### ISSUE THREAD

**Issue by clay-f** [Microsoft/vscode#34179]
1.  using shortcut, shift+option+f, can't format code, show `Ï` 
2.  change `format selection` command +k command + f
     > The key combination is not a command.

3. open command panel can't found format item

vscode version: 1.16.0
os version: mac os 10.12.6

**Comment by alexandrudima** [comment]
@clay-f What keyboard layout do you have configured on your OS ?

**Comment by clay-f** [comment]
@alexandrudima U.S., both format code seem can't used

**Comment by clay-f** [comment]
@alexandrudima 
origin format
<img width="661" alt="screen shot 2017-09-12 at 20 32 52" src="https://user-images.githubusercontent.com/16079417/30326005-a1a251e4-978c-11e7-8c46-e3908edd1945.png">


<img width="831" alt="screen shot 2017-09-12 at 20 34 33" src="https://user-images.githubusercontent.com/16079417/30326145-27d125f6-978d-11e7-829e-32376f004394.png">
<img width="820" alt="screen shot 2017-09-12 at 20 35 00" src="https://user-images.githubusercontent.com/16079417/30326144-27cdcc94-978d-11e7-9c3b-db0b0b3f3d9d.png">

**Comment by alexandrudima** [comment]
@clay-f We do not ship out-of-the-box with a formatter for ruby.

Have you installed an extension that contributes ruby formatting? Unless there is some extension that is able to format ruby, invoking the format command will be a no-op. The format command will be shown in the context menu if there is an extension implementing formatting for the language. i.e. What does the context menu show ?

Perhaps we should show a warning message when the format command is invoked and we have no formatter... Thoughts @jrieken ?

**Comment by jpmckearin** [comment]
@alexandrudima @jrieken I think a warning message would certainly help eliminate some of these issues opened concerning the formatting shortcuts. I was having the same issue this morning with `less` files before stumbling upon this. It is not obvious that the behavior observed is due to a missing formatter.

**Comment by alexandrudima** [comment]
It boils down to the way the command is registered in our keybinding rules:

```
{ "key": "shift+alt+f",
   "command": "editor.action.formatDocument",
   "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly" 
},
```

So if there are no document formatting providers defined for the current file, `shift+alt+f` is not bound and bubbles up to produce what it would always produce under this keyboard layout, `Ï`

**Comment by coreylendo** [comment]
Hello need or help

C.L

**Comment by alexandrudima** [comment]
We now show a message in this case:

![image](https://user-images.githubusercontent.com/5047891/45344327-bf627e80-b5a3-11e8-814a-4ad92b610c7d.png)
