### ISSUE TITLE
Please bring the lightbulb on empty selections back

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#34172]
In version 1.16 the lightbulb is no longer appearing on empty selections. After looking through the git log I found commit 785c76451f76673df67bd7b6c59586145e5a1b18 "don't show lightbulb for empty selections, #33241" by @jrieken.
This change was obviously intended in order to stop annoying people with a lightbulb that provides refactorings only. It makes perfect sense to me that people don't want to see a lightbulb when there is nothing bad in the code. But the current change of behaviour is not an optimal solution in my opinion. I'd love to see the lightbulb appearing on empty selections. That way the user can see there are quickfixes for his code even before the linter started to mark the current identifier. 
In my specific case there is no fast linter that is capable of marking unknown identifiers in real time but the language service can say quickly when an identifier can't be resolved as long as source file ABC is not imported. So I made use of the empty selection lightbulb which appears while typing an unknown identifier name. The user got immediate feedback about the quick fix. With the changes in 1.16 the user has to check for quick fixes by hand which declines the user experience.

Since the lightbulb annoyed users in other situations I'd love to see an API where each code action comes with a code action kind like `refactoring` or `fix` and VSCode would show the lightbulb for fixes only while refactorings are offered somewhere else.

**Comment by mjbvz** [comment]
The old lightbulb behavior was already restored in insiders builds. Please try these out and let us know if you notice any problems

**Comment by Wosi** [comment]
Awesome! Works as expected. Thank you!
