### ISSUE TITLE
Support Logical functions in Azure Resource Manager Tools extension

### ISSUE THREAD

**Issue by russcam** [Microsoft/vscode#34177]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro 64 Bit, Build 15063.540

The [logical functions for Azure Resource Manager templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-logical) have been out for a little while now, but the latest Azure Resource Manager tools Version 0.3.6 (07/27/2017) does not support them:

![logical_functions](https://user-images.githubusercontent.com/208231/30302219-e4c42496-97a2-11e7-993d-9a177ce053d2.png)

Please add support for them to make authoring templates that little bit less fiddly!

**Comment by chrisdias** [comment]
the azure resource manager tools will be open source shortly and once that happens we can move this issue to that repo.

**Comment by russcam** [comment]
Thanks @chrisdias

**Comment by pwiens** [comment]
@chrisdias Any updates on when the extension will be opensourced?

**Comment by chrisdias** [comment]
@pwiens here it is: https://github.com/Microsoft/vscode-azurearmtools

**Comment by chrisdias** [comment]
copied to: https://github.com/Microsoft/vscode-azurearmtools/issues/10
