### ISSUE TITLE
Editor not rendering soft hyphen

### ISSUE THREAD

**Issue by WToorenburghEasyMarkit** [Microsoft/vscode#34176]
I ran into a case where a [soft hyphen](http://www.fileformat.info/info/unicode/char/00AD/index.htm) had snuck into a regex expression, yet the character was not visible in the editor. It doesn't seem to render in most places, including Stack Exchange; it has only shown up for me when pasted into a terminal window like `cmd.exe` or `terminal.app`. Full disclosure: I don't know if this is behaviour as intended or not. This could also be an Electron issue.

- VSCode Version: 1.16.0
- OS Version: Windows 10 Pro 15063.540

Steps to Reproduce:

1. Copy this regex expression using Ctrl+A: http://rubular.com/r/M58qyBfuxF (Link provided as it seems GitHub scrubs the soft hyphen before posting)
2. Paste it into Code, and verify that there is no hyphen visible.
3. Paste it into a terminal window and verify that there is a hyphen directly after the `$`

Reproduces without extensions: Yes
Also reproduces with both the default font and [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)

**Comment by WToorenburghEasyMarkit** [comment]
vscodebot is correct in that the integrated terminal also does not render this character, though that's not the core of the issue.

**Comment by alexandrudima** [comment]
@WToorenburghEasyMarkit This is indeed an upstream issue, all of our font rendering in the editor is done by Chromium. May I kindly ask that you open an issue at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by WToorenburghEasyMarkit** [comment]
@alexandrudima Thanks for the direction. [Here's the issue I filed](https://bugs.chromium.org/p/chromium/issues/detail?id=767950).

After looking a bit closer at some of the bugs submitted that refer to soft hyphens ([the search I used](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=soft+hyphen&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids)), it seems like the intended behaviour is for soft hyphens to not be rendered unless they are at the end of a line. Or, at least, it seems as though soft hyphens not being visible at all times is not unintended.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by WToorenburghEasyMarkit** [comment]
Understandable! Thanks for the communication. Here's hoping the Chromium issue I filed gets some further attention.
