### ISSUE TITLE
Expore improvements to minimap rendering performance

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34170]
Currently we use `putImageData` to redraw the entire minimap each frame, we should explore keeping the source of truth of the image in the canvas and printing diffs to minimize the amount of rendering.

**Comment by Tyriar** [comment]
Not sure if there will be time for this in September (it's on the iteration plan though).

**Comment by alexandrudima** [comment]
I have pushed an optimization where the `dirtyY` and `dirtyHeight` arguments of `putImageData` are exercised to reduce in many cases how much painting is done.

@Tyriar I leave it up to you to explore further optimizations.
