### ISSUE TITLE
The reload Typescript action also applies to JavaScript

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3417]
Now that the TS server powers both TypeScript and JavaScript the action to reload a project also applies to JavaScript:

![image](https://cloud.githubusercontent.com/assets/172399/13287918/b8ecab9c-db09-11e5-84e3-9afcab05368d.png)

I suggest to either rename the action to `Reload TypeScript/JavaScript Project' or we provide a separate action: 'JavaScript: Relead Project'

**Comment by egamma** [comment]
Opinions/preferenes @weinand and @joaomoreno?

**Comment by weinand** [comment]
@egamma users not interested in JavaScript might be confused by the combination. I suggest to introduce a separate action.

**Comment by egamma** [comment]
@weinand yes, a separate action is cleaner for users that only use TypeScript or JavaScript, but then there are users that use a hybrid TypeScript/JavaScript setup. This is supported and one of the goals of Salsa. In this case this can  mislead users that TS and JS are separate projects.

**Comment by weinand** [comment]
Which user group is larger?

**Comment by egamma** [comment]
>Which user group is larger?

JavaScript only is the largest group, so let's go with two separate actions.

**Comment by weinand** [comment]
What's about these two: 
- `Reload JavaScript Project'
- `Reload TypeScript/JavaScript Project'

instead of:
- `Reload JavaScript Project'
- `Reload TypeScript Project'

**Comment by egamma** [comment]
This would cover both scenarios. Only concern is when I type 'JavaScript' into the quick box then the filtering returns both commands and as a user I wonder what is the difference between those two.

**Comment by weinand** [comment]
@egamma good point. So then let's go with:

- `Reload JavaScript Project'
- `Reload TypeScript Project'

**Comment by egamma** [comment]
sold :smile:

**Comment by chrisdias** [comment]
Why don't we watch for changes to tsconfig or jsconfig and just reload it automatically?  When would you not want this to happen?

**Comment by joaomoreno** [comment]
@weinand @egamma I believe there is no way to provide separate actions with separate behaviours here. I only found [one place](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L45) where the project gets reloaded. So, I have to assume the language service is shared between JavaScript and TypeScript. My very limited knowledge of how this works might not be the most correct one, though, and @jrieken or @dbaeumer could confirm or deny this.

Anyway, I present you with 2 solutions:

- Have a single `Reload JavaScript & TypeScript Project` which reloads both worlds
- Have separate `Reload JavaScript` and `Reload TypeScript Project` actions, but each will reload both worlds as well. They will both do the same.

Give me your thoughts.

**Comment by weinand** [comment]
@joaomoreno We had exactly your second solution in mind: Have separate Reload JavaScript and Reload TypeScript Project actions, but each will reload both worlds as well. They will both do the same.

**Comment by joaomoreno** [comment]
Oh I didn't realize that. Thanks!
