### ISSUE TITLE
[Folding] Allow empty lines below folded markdown block

### ISSUE THREAD

**Issue by mortenjust** [Microsoft/vscode#34173]
1. Create a foldable section
2. Add a few newlines under it
3. Add content below
4. Fold the foldable section from 1.

Actual: The newlines from 2. will be hidden inside the folding
Expected: Newlines to not be hidden

![missingwhitespace](https://user-images.githubusercontent.com/1548468/30299557-1b0805f2-9705-11e7-9224-415f7506c1a1.gif)

**Comment by hmalaud** [comment]
Not specific to markdown though, but would be very much appreciated if we could add new line breaks after code folded without it to be folded with the previous content.

**Comment by aeschli** [comment]
This got fixed for 1.17
