### ISSUE TITLE
Keyboard layout compatibility

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#34174]
_From @pujiaxun on August 30, 2017 2:54_

- VSCode Version: 1.15.1 
- OS Version: macOS Sierra 10.12.6  

I am using an simplified Chinese input method. And this seems to change the keyboard layout, which makes a few keybindings failed.

For example:

When **ABC(English)** input method:

```json
[
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorTextFocus && !editorReadonly"
    },
  {
        "key": "cmd+/",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
  }
]
```

When **Simplified Chinese** input method:
```json
[
    {
        "key": "cmd+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorTextFocus && !editorReadonly"
    }
]
```

**The `cmd+/` disappeared!**

Finally I find this:

```json
    {
        "key": "cmd+[Slash]",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    }
```

I wonder whether I can toggle a switch to change the keybindings from `/` to `[Slash]`, from `,` to `[Comma]`, and so on?

Thank you!

_Copied from original issue: Microsoft/vscode-docs#1148_

**Comment by alexandrudima** [comment]
@pujiaxun Our default keybindings are currently shipped in the form of e.g. comment line is `cmd+/`. When using any keyboard layout, including ABC-English or Chinese Simplified, our keybinding system will try to find a physical key to map that default keybinding to.

e.g. on the German keyboard layout `/` is produced by `Shift+[Digit7]`. Therefore, on the German keyboard layout comment lines will be mapped by default to `cmd+shift+[Digit7]`.

I am not intimately familiar with the Chinese Simplified keyboard layout, but perhaps there is no straight-forward key combination that produces `/`. To verify that, you can open an editor and run `F1 > Developer: Inspect Key Mappings`. Those are the mappings we identify from the OS and use to bind default keybindings to physical keys.

Today, the only workaround is the one you are currently using, of rebinding the actions to what makes most sense on your keyboard layout. What would be best is if we would ship with keybindings optimized for each individual keyboard layout. That is something we can track in #1240
