### ISSUE TITLE
HTML indentation inside PHP files

### ISSUE THREAD

**Issue by andremacola** [Microsoft/vscode#34178]
- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:10:46.671Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
code-settings-sync|Sha|2.8.3
project-manager|ale|0.21.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.0
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-great-icons|emm|2.1.15
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.0
vs-deploy|mkl|9.32.3
sublime-keybindings|ms-|2.9.1
wordpress-snippet|tun|1.1.2

---

Steps to Reproduce:

1. Save any file to file.php
2. type div (or any html tag) (press tab and enter)

Reproduces without extensions: Yes

What happen:
![bug](https://user-images.githubusercontent.com/3408809/30302501-dcdfbc74-9737-11e7-886e-750d19d409b4.png)

Expected:
![expected](https://user-images.githubusercontent.com/3408809/30302500-dcdf2e30-9737-11e7-93a1-b04ff6d6bd1b.png)

---

Not so quick fix:

Change the current language file to **html**, reproduce number 2 and back to **php** language mode (sometimes needed for every open/new file)

**Comment by TheDutchCoder** [comment]
This is driving me absolutely insane.

Mixed PHP/HTML support is horrible right now and there must be a huge amount of people having to deal with this (i.e. every single WordPress dev for example).

Indentation is completely broken for PHP right now and it seriously makes me switch back to another editor because of it.

Can this please be addressed as a bug?

**Comment by roblourens** [comment]
I'll see if it works to copy the html indentation rules into the PHP extension.

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/39142#issuecomment-349080179
