### ISSUE TITLE
In debug mod, the keyboard shortcut "F11" can't full screen

### ISSUE THREAD

**Issue by JkVon** [Microsoft/vscode#34187]
In debug mod, the keyboard shortcut "F11" can't full screen.

- VSCode Version: 1.16.0
- OS Version: Win10 (10.0.15063 Build )

**Comment by isidorn** [comment]
Yeah, that is a know limiation.
As a workound please use a differnt shortcut for either `step in` or enter full screen since they ovewrite each other.
Prefences > Keyboard shortcuts
