### ISSUE TITLE
Please support CMake 

### ISSUE THREAD

**Issue by SkyRiderMike** [Microsoft/vscode#34180]
- VSCode Version: 1.16
- OS Version: windows 10 

I am using this wonderful app for C++ code on Windows Subsystem of Linux.

I have downloaded the CMake extension, however, it usually shows "The "cmake" command is not found in PATH. Install it or use `cmake.cmakePath` in the workspace settings to define the CMake executable binary."

But I have cmake installed on WSL already. Can you help me fix this problem ?

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
My best guess is that the specific cmake extension you have installed is not aware of WSL and searches for cmake in the Windows path. Perhaps you can reach out to the author of the extension and ask for this feature request there ?
