### ISSUE TITLE
Terminal link hover widget clipped 

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#34183]
- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:10:46.671Z)
- OS Version: Darwin x64 16.7.0

---

**Bug**
In the integrated terminal, the `Cmd + click to follow link` hover may be clipped if the link is near the top of the terminal

<img width="280" alt="screen shot 2017-09-11 at 6 16 00 pm" src="https://user-images.githubusercontent.com/212305/30303540-9fbc310c-971d-11e7-9794-e57fabed6d7a.png">

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/34967
