### ISSUE TITLE
Add functionality for autoclosing single quotes and double quotes

### ISSUE THREAD

**Issue by luchong12** [Microsoft/vscode#3418]
I have editor.autoClosingBrackets set to true but it seems it works stricly with brackets. I guess autoclosing single/double quotes is not implemented yet? If not, please do it. I think it is a common feature for every editor.

**Comment by alexandrudima** [comment]
@luchong12 What language is missing them?

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
