### ISSUE TITLE
不区分大小写

### ISSUE THREAD

**Issue by Mrjen** [Microsoft/vscode#34185]
- VSCode Version:1.16.0
- OS Version: win 10 

Steps to Reproduce:
1.驼峰命名的单词和不是驼峰命名的单词双击都会同时高亮

Reproduces without extensions: Yes/No

**Comment by hevily** [comment]
Not capitalized lowercase

VSCode Version: 1.16.0
OS Version: win 10
Steps to Reproduce:
1. Hump named words and not hump named double click will be highlighted at the same time

Reproduces without extensions: Yes / No

**Comment by hevily** [comment]
最好英语提问
Best English question

**Comment by warmsea** [comment]
Happened to see this. Help translate/explain.

Double click a word, all the same words will be highlighted, regardless of uppercase and lowercase.

For example, if I double click `serviceKey`, it shows:
![image](https://user-images.githubusercontent.com/2446182/30309103-efa2a658-97bb-11e7-8d13-83ee5983a3d4.png)

I guess @Mrjen expects only the camelCased `serviceKey` to be highlighted. While `ServiceKey` is highlighted too in this example.

**Comment by alexandrudima** [comment]
What language are you using ?

The selection highlighter which kicks in when a language does not have a semantic occurences highlighter respects the settings of the find widget. If the find widget toggle for case sensitive is off, the selection highlighter will highlight matches which are also not case sensitive.

Here, for example both case sensitive and match whole words are on:
![image](https://user-images.githubusercontent.com/5047891/30312928-d7006718-979b-11e7-8332-58b502f70327.png)

The selection highlighter will respect those.

**Comment by warmsea** [comment]
I'm using English. I confirm that double click respects the find widget settings.
But since @Mrjen complained, I think now it became a PM/UX question. Because seems it is not easy for a customer to find the connections here. I didn't find it either.

**Comment by alexandrudima** [comment]
The selection highlighter is a feature very useful for programming languages where there is no semantic highlighter.

If you wish to have semantic highlighting, please install a corresponding extension and disable selection highlighting via `"editor.selectionHighlight": false`.
