### ISSUE TITLE
Mouse Selection now has one line offset in Terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#34184]
- VSCode Version: 1.16 Insider
- OS Version: macOS

![terminal-offset](https://user-images.githubusercontent.com/876920/30304456-73562726-9722-11e7-85f4-717b53eb85dc.gif)

Select on the first line leads to virtual selection on the second line.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@rebornix do you have zoom level or terminal line height in settings?

**Comment by rebornix** [comment]
@Tyriar After plug/unplug to my monitor, I can't reproduce anymore. When I ran into that issue, I don't have any zoom, I only set terminal font size and reload the window doesn't work.

Close it right now, If I ran into it again, I'll reopen.

**Comment by Tyriar** [comment]
Oh I can reproduce, it's definitely a bug. Just curious under which settings you repro'd as there are a few different cases.

**Comment by will-l-h** [comment]
I have run into this issue as well as ctrl-clicking links in the terminal. window.zoomLevel -1, 0, and 1 are all far enough off to be an issue.

**Comment by martellaj** [comment]
Today's update fixed this particular issue for me, but led to another ([here](https://github.com/Microsoft/vscode/issues/34475)).

**Comment by will-l-h** [comment]
I'm on today's update and the issue described here is still present. On zoomLevel 0 it's still shifted a little bit down and on 1 or -1 it's more pronounced.

**Comment by darkvertex** [comment]
I've updated to the latest code-insiders as of today and I also experience this issue constantly in my Terminal view.

**Comment by martellaj** [comment]
Any update or extra information needed for this one? It's kind of a killer with respect to using the integrated terminal.

**Comment by martellaj** [comment]
Thanks, @Tyriar! Can confirm it looks good with today's build!

**Comment by darkvertex** [comment]
Fixed for me too :tada: :smile: with today's build! - Thanks @Tyriar!

**Comment by octref** [comment]
I can't repro the original issue so both insider and stable looks fine for me. @Tyriar how should I verify the fix?

**Comment by Tyriar** [comment]
@octref I would hold off on this until tomorrow as a related issue was closed off.

To verify: Ensure that the mouse cursor selection feels natural, especially as you go further right and further down.
