### ISSUE TITLE
Terminal is messy when I use Chinese path.

### ISSUE THREAD

**Issue by colorfulJin** [Microsoft/vscode#34186]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-html-css|ecmel|0.1.8|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|java|redhat|0.9.0|
|Seti-theme|TsumiNa|0.0.1|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
@colorfulJin What do you mean? Can you please attach a screenshot ?
