### ISSUE TITLE
Error Windows

### ISSUE THREAD

**Issue by DarioXavier** [Microsoft/vscode#34181]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
Angular1|joh|0.2.0
Angular2|joh|2.7.0
LiveServer|rit|2.1.1
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@DarioXavier Can you please provide steps and a more detailed explanation of your problem?
