### ISSUE TITLE
Window failure

### ISSUE THREAD

**Issue by annder** [Microsoft/vscode#34197]
- VSCode Version:1.16
- OS Version:Windows 10.0.14393

Reproduces without extensions: Yes/No Yes

It is in writing code that happens frequently:

![image](https://user-images.githubusercontent.com/12369444/30311245-f04c736c-97c6-11e7-99ae-42dfa1ec2b5a.png)

**Comment by huhao815** [comment]
I met too, how to solve?

**Comment by annder** [comment]
Do you open the terminal and enter a command like type observation?

I entry  tslang command like tsc -w.

**Comment by huhao815** [comment]
Yes, I also started the "tsc -w " in the terminal。
I'm ready to rollback the version to 1.15

**Comment by alexandrudima** [comment]
@annder I do not understand, what does the message say?

Also, what are the steps that leads to this error?

**Comment by annder** [comment]
step 1. open terminal in VScode
step 2.entry tsc -w command .(Typescript language instructions).

Soon there was a window failure。

**Comment by octref** [comment]
@Tyriar It says "Window malfunctioned. We are sorry about the inconvenience. Please restart to continue from where the program stopped working."

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
