### ISSUE TITLE
Snippets are pretty flaky: Don't load, don't reload, don't have autocomplete priority

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#34198]
- VSCode Version: Version 1.16.0 (1.16.0)
- OS Version: Sierra

I have a fairly simple snippet I'm testing:

```
    "Print to console": {
        "prefix": "log",
        "body": [
            "console.log( '$1', $1 );",
            "$2"
        ],
        "description": "Log output to console"
    },
```

## 1. On VSCode launch, snippets don't show up for ~30 seconds

![no-snippets-why](https://user-images.githubusercontent.com/79215/30311752-9f9c2c58-974b-11e7-9c17-c5036511feb0.gif)

**Steps to reproduce**

1. Create a snippet like the above
2. Open VSCode with a session with a Javascript file already open
3. Attempt to type the snippet

**Expected behavior**

The snippet loads and is usable

**Actual behavior**

The snippet doesn't load

## 2. Snippets randomly don't load at all (neither does any autocomplete)

![flakey-snippets](https://user-images.githubusercontent.com/79215/30311121-ac4b3bc2-9748-11e7-8f03-473867cb4f6f.gif)

Notice how I type `log` above the snippet line, and no snippets work. Even if autocompletion doesn't work here (not sure why?) snippets should load, since there's no overhead to loading the contents of a file.

**Steps to reproduce**

1. Insert the contents of a snippet
2. Move the cursor above or below and type text that should trigger another snippet

**Expected behavior**

The snippet loads and autocompletes

**Actual behavior**

Nothing happens

## 3. Snippets randomly move in priority, autocomplete nonsense

![flakey-snippets](https://user-images.githubusercontent.com/79215/30311121-ac4b3bc2-9748-11e7-8f03-473867cb4f6f.gif)

When the autocomplete dropdown for `log` finally shows up, the first entry is **not** a snippet. Instead it's a baffling `var log: Log`. Note I have no variable named `log` anywhere in this file nor my project.

**Steps to reproduce**

1. Insert the prefix of a snippet

**Expected behavior**

The snippet is suggested to autocomplete

**Actual behavior**

Nonexistent variables are suggested to autocomplete

## 4. Snippets don't have priority in autocomplete

I tried naming a snippet with the prefix `"c"`. I've done this in all other editors that support snippets. I have it set to expand to the snippet posted at the top of this ticket. However, when I type `c`, a dozen variables that don't exist in my project come up first, as well as things that are syntactically impossible here, like `catch`.

![complete-not-good](https://user-images.githubusercontent.com/79215/30311468-311bf2d2-974a-11e7-9105-8d167f0396dc.gif)

## 5. Snippets don't seem to live reload

I've used a few Vim snippet plugins, and they seem to reload instantly on saving the file. With VSCode, changing a snippet prefix in `javascript.json`, opening a `.js` file, and typing that prefix does nothing. On restart the snippet shows up.

-----

So far snippets in VSCode have been a mildly frustrating experience. Even Vim, which has notoriously bad autocomplete, doesn't seem to have these issues.

**Comment by jrieken** [comment]
> 1. On VSCode launch, snippets don't show up for ~30 seconds

Try without extensions, you are likely having a busy extension host and computing suggestions is blocked by that. 

> Notice how I type log above the snippet line, and no snippets work

The first occurrence of `log` isn't a snippet but the JavaScript-all-symbols-suggestion. Check with the icon, also you can use the `editor.snippetSuggestions`-setting to tweak sorting of snippet and other suggestions. This should also answer question 3 and 4

Unsure what number 5 is about, please try again with insiders because we have changed the snippet discover and loading logic. Also, please file separate issues for separate things
