### ISSUE TITLE
Fix terminal link tests

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34193]
Disabled in https://github.com/Microsoft/vscode/commit/128a4e3640c5375f7b0bc1cfd37f626481b1386f

**Comment by Tyriar** [comment]
@timbanaveen In order to fix a VS Code crash caused by a regex catastrophic backtracking case, I changed the unix link link regex (https://github.com/Microsoft/vscode/issues/34039). I had to disable some of the terminal link line/column Unix cases (added in https://github.com/Microsoft/vscode/pull/24832) as I don't totally understand what's happening. For some reason `unixLineAndColumnMatchIndex` doesn't seem to work for all the `lineAndColumnClause` anymore, specifically these ones:

```
	'((\\S*) on line ((\\d+)(, column (\\d+))?))', // (file path) on line 8, column 13
	'((\\S*):line ((\\d+)(, column (\\d+))?))', // (file path):line 8, column 13
```

See this change which gets 2/4 cases working: https://github.com/Microsoft/vscode/commit/b411fb2c2cace098d6eb95999a2b055962204819

Any insights would be great :smiley:

**Comment by timbanaveen** [comment]
@Tyriar, just saw this issue and fix. will have a detailed look in this on weekend, will update you on any findings.

**Comment by Tyriar** [comment]
@timbanaveen did you get a chance to look at this?

**Comment by timbanaveen** [comment]
@Tyriar got new machine, i have just started setup. Will update soon.

**Comment by timbanaveen** [comment]
@Tyriar I tried running test from terminal using `scripts\test.bat`, but it seems to be stuck, shows nothing on terminal. Is there any way to run specific test or something i am missing.
Thanks

**Comment by Tyriar** [comment]
Hmm... I'm sure there is a way as it uses mocha, I'm not sure what it is though as the tests always run so fast for me.

**Comment by timbanaveen** [comment]
@Tyriar I have updated the tests and ts file, now tests are working fine. Please review. Thanks
