### ISSUE TITLE
Git bash not working

### ISSUE THREAD

**Issue by veganexe** [Microsoft/vscode#34190]
Added this as per the docs

`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

But I get an empty/blank terminal with a cursor. One more thing is I see "bash" in the terminal drop-down option. Not "bash.exe" as I have seen in some screenshots. Idk, maybe that's of some importance

**Comment by shieldsjared** [comment]
Also having the same problem, after upgrading to 64-bit edition (although I didnt have bash configured before so I'm not sure if that had anything to do with it.)

**Comment by Tyriar** [comment]
I can't reproduce this. If it happened when you moved to 64-bit it's probably related to running the 32-bit shell instead of the 64-bit one; if you used sysnative i the path before switch it to system32.
