### ISSUE TITLE
Terminal file path clickability when colour changes midway through file path

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/vscode#34195]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.0
githistory|don|0.2.3
tslint|eg2|1.0.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.2

---

Steps to Reproduce:

1. Take the setup here: https://github.com/TypeStrong/ts-loader/tree/master/examples/fork-ts-checker
2. `npm install`
3. `npm start`
4. Observe lack of clickability on errors:

![screenshot 2017-09-12 06 12 25](https://user-images.githubusercontent.com/1010525/30310016-40e1325e-9786-11e7-858d-7f5579deae38.png)

The reason for this is the colour change that the [`fork-ts-checker-webpack-plugin`](https://github.com/Realytics/fork-ts-checker-webpack-plugin) produces between the path ("...fileWithError.ts") and the line number / column number ("(2:7)")

You can work around this by supplying a custom formatter to fork-ts-checker-webpack-plugin; see here: https://blog.johnnyreilly.com/2017/09/fork-ts-checker-webpack-plugin-code.html

However, I wonder if VS Code should be able to cope with these colour changes and preserve "clickability".  What do you think?

**Comment by johnnyreilly** [comment]
See related PR for fork-ts-checker-webpack-plugin that works around this issue: https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/48#issuecomment-328766562

**Comment by Tyriar** [comment]
This limitation is fixed in Insiders (https://github.com/sourcelair/xterm.js/issues/654), there are some lingering issues with links in Insiders though that should hopefully get fixed before it lands in stable.

**Comment by johnnyreilly** [comment]
Nice!
