### ISSUE TITLE
File types associated with VS Code are all given the same label in File Explorer

### ISSUE THREAD

**Issue by JoshTumath** [Microsoft/vscode#3419]
If I associate a file with VS Code (e.g. *.css, *.html, *.js, *.gitignore), each of these files are given the same file type label "Visual Studio Code". Therefore, when viewing a project directory in File Explorer, it is not possible to list files by type, because they all have the same label.

**Comment by tht13** [comment]
tools > Folder Options > View >  
Disable "Hide extentions for know file types" in the scroll section

**Comment by JoshTumath** [comment]
> Disable "Hide extentions for know file types" in the scroll section

That's already disabled. I'm referring to the label that appears in the "Type" column when viewing a folder in the Details view.

**Comment by joaomoreno** [comment]
Let's consider putting this information in the repo, so people can make PRs on it.

**Comment by joaomoreno** [comment]
To verify:

- Install a version after e1598eb (Insiders from July 22 should have it)
- Associate a file type with Code, from the Windows Explorer
- The type column in the Explorer should be specific to the file type.

![image](https://cloud.githubusercontent.com/assets/22350/17020836/31c8d87a-4f44-11e6-95ba-836a1259ea93.png)
