### ISSUE TITLE
SUGGESTION: Add Duplicate File to the Context Menu

### ISSUE THREAD

**Issue by awgeorge** [Microsoft/vscode#342]
I have often had to navigate to `Finder` in order to duplicate files while I have been working.

I would imagine that duplicating a file is a common way of developing.

Hope to see it in the future :)

**Comment by coreh** [comment]
With the file focused, you can press Command+C then Command+V. I know it's not as fast or the same as a dedicated menu item, but it's a nice workaroud.

**Comment by bpasero** [comment]
Yes, you can Copy + Paste via keybindings or the menu.

**Comment by awgeorge** [comment]
I guess this mentality is baked into your ethos.

`This is so trippy`: https://youtu.be/5DqJwmzG6Fk?t=7m24s

Please spare a thought for users from other platforms.
