### ISSUE TITLE
Linux: Cannot open containing folder of a file

### ISSUE THREAD

**Issue by ansidev** [Microsoft/vscode#34202]
- VSCode Version: 1.16.0
- Commit: 787b31c0474e6165390b5a5989c9619e3e16f953
- OS Version: Ubuntu 17.10 Awkward Artful x64
- Linux Kernel Version: 4.12.0-12-generic
- Nautilus Version: 3.25.92

Steps to Reproduce:

1. Right click on a file
2. Select Open containing folder
3. After that, windows will not response to user and you must force quit.
4. A popup will display when forcing quit with below error:

``` javascript
Uncaught Exception:
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
```

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Does this still happen?

**Comment by robbiespeed** [comment]
Fresh install of Fedora 26 vscode still responds, but clicking "Open Containing Folder" does nothing.

**Comment by ansidev** [comment]
Now, it's OK with version 1.18.1 on Ubuntu 17.10
