### ISSUE TITLE
Extension Development Host not activating development extension

### ISSUE THREAD

**Issue by amamut** [Microsoft/vscode#3420]
I created brand new extension project using ```yo code``` which has the default activation message in it. When I press ```F5``` it loads the extension development host but I do not get the activation message. I also put breakpoints on the ```activate``` method to see if it even gets in there and it doesn't. Is this a configuration error or something with the debugger?

**Comment by joaomoreno** [comment]
The default extension has the following in its `package.json`:

```
	"activationEvents": [
		"onCommand:extension.sayHello"
	],
```

This means it will only be activated when the `extension.sayHello` command is triggered.

If you run the `Hello World` command from the command pallette with <kbd>F1</kbd> (or <kbd>Cmd Shift P</kbd>) your extension will then be activated.

**Comment by analysisi** [comment]
ou should find the "Hello World" command in the Command Palette (press F1) ,
but when press f1 ,howerver  it cant show the command window , 
![6ad8 tm](https://cloud.githubusercontent.com/assets/12759554/13597286/acfb73c4-e552-11e5-8ae6-a98d587d0c18.png)

**Comment by joaomoreno** [comment]
ping @bpasero

**Comment by bpasero** [comment]
@analysisi maybe you stopped in your extension in the debugger?

**Comment by bpasero** [comment]
Also, something in the console of the extension host window?

**Comment by indiejames** [comment]
I just built a test extension with yo code and it worked twice and then stopped working. By chance I uninstalled the spell checker extension and then the test extension started working every time I tried it. It may be possible that some other extension is interfering with the startup of your extension.
