### ISSUE TITLE
Problem with syntax highlighting (HTML/PHP)

### ISSUE THREAD

**Issue by mattiamerlini** [Microsoft/vscode#34204]
Problem with syntax highlighting as reported below:

![image](http://imageshack.com/a/img924/7888/eAWgqU.png "Image")

- VSCode Version: 1.16.0 (1.16.0)
- OS Version: Mac OSX Sierra 10.12.5

Steps to Reproduce:

1. Write HTML code
2. Insert multiline pieces of PHP code
3. See that the syntax doesn't recognise the open/close php tag

**Comment by roblourens** [comment]
Another instance of https://github.com/atom/language-php/issues/246...

**Comment by roblourens** [comment]
This will be fixed in tomorrow's Insiders build

**Comment by roblourens** [comment]
Will be fixed in tomorrow's Insiders.

**Comment by maldetquest** [comment]
What about the regular build?

**Comment by roblourens** [comment]
It will be in 1.16.1, whenever we get that out.

**Comment by daviddeejjames** [comment]
Thank youuuu @roblourens, this was released today in 1.16.1 😄

**Comment by khanhvu14** [comment]
good job, thank you :)
