### ISSUE TITLE
Color Picker does not follow the cursor.

### ISSUE THREAD

**Issue by hua03** [Microsoft/vscode#34205]
- VSCode Version: 1.16.0
- OS Version: Window10

![](http://opd59bmxu.bkt.clouddn.com/2017-09-12-15-57-08.png)

Steps to Reproduce:

1. open your VS Code.
2. new a CSS file.
3. paste this to you file

```
.wrap {
  display: inline-block;
  width: 300px;
  height: 300px;
  margin: 20px;
  background: repeating-linear-gradient(45deg, red, red 10px, orange 10px,orange 20px);
}
```

4. Put your cursor over here `orange`

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Hm, the hover computed by the CSS hover provider returns a range that encompasses the entire line. i.e. the range for the descriptive text "Shorthand property for setting most background properties at the same place in the style sheet" is the entire line. The hover then tries to position itself in such a way that it covers this range.

While this might make sense for the regular hover message, perhaps this does not make sense when also displaying the color picker in the hover message...

**Comment by ajitid** [comment]
I still didn't had no problem even if color picker was shown at start of the line, but if you try to reach to the picker it hides itself

**Comment by iainhallam** [comment]
When this happens, it also means that simply by moving the mouse to the picker, you leave the colour, so it disappears! I think it either needs to move closer to the colour definition, or stay around a bit longer to allow a path to the picker that traverses the rest of the document without hiding the picker.

**Comment by usernamehw** [comment]
Still possible to access it tho, just have to move the mouse real quick and precise... \\[T]/

**Comment by usernamehw** [comment]
⬆ It was a joke, but whatever...
