### ISSUE TITLE
linux: terminal font is cut off

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#34208]
Elementary OS Freya (based on 14.04)
1.70.0-insiders

The terminal font has changed. It seems to be too big for the line height chosen.

![image](https://user-images.githubusercontent.com/6461412/30315735-3f83170a-97a5-11e7-8edc-5435674ad2f9.png)

**Comment by Tyriar** [comment]
@aeschli do you have a font set in your settings?

**Comment by aeschli** [comment]
@Tyriar No font settings. To verify I just ran code-insiders on a empty user-data-dir.
Not sure if that helps:
![image](https://user-images.githubusercontent.com/6461412/30369165-cd8990f0-9873-11e7-8cd3-95191488ea0b.png)

**Comment by jgillich** [comment]
Similar issue on Fedora 26:

![screenshot from 2017-09-16 13-49-56](https://user-images.githubusercontent.com/347965/30512053-4d9140d0-9ae6-11e7-835a-7a261e7c9ec5.png)

This only appears in the latest insiders build, not stable. Also no custom font set.

**Comment by Tyriar** [comment]
@jgillich if you can figure out what font it was before that would be great. Also what commit was the version you saw this one (in help > about)?

**Comment by jgillich** [comment]
@Tyriar The font appears to be Liberation Mono, commit b0c0634339c6f64a5c7f08b56fe732fb9154d3c4.

**Comment by Tyriar** [comment]
The likely fix here is to allow the drawable area within a terminal grid cell to include the line height of the cell and then increase the line height in settings.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
