### ISSUE TITLE
Code highlighting trouble in *.jsx

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#34215]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
vscode-docker|Pet|0.0.16
sass-lint|gle|0.0.4
sass-indented|rob|1.4.1
vscode-multiclip|sle|0.1.2

(22 theme extensions excluded)

---

Steps to Reproduce:

1. Open *.jsx file in editor
2. Enter the next complex ternary operator: 
`{ i >= 2 && i < 3 ? "first branch" : i > (j - 2) * 4 ? "second branch" : "third branch" }`

As a result, the code highlighter recognizes code between `<` and the last `>` as a tag (e.g. `<div>`).
Another interesting thing: if there is no any `(round brackets expression)` immediately after the last `>`, it's all fine.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/518 to track this upstream
