### ISSUE TITLE
Emmet escaping $ not working 

### ISSUE THREAD

**Issue by surajrao** [Microsoft/vscode#34216]
- VSCode Version: 1.16.0
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. edit `span{\\$5}` in HTML file and press tab
2. generates `<span>\</span>`

Should escape and print `<span>$5</span>` according to https://docs.emmet.io/customization/snippets/#escaping--and--characters

Note: also tried `span{\$5}` with same result.

Reproduces without extensions: Yes

Or is it handled differently in visual studio code in particular?

**Comment by ramya-rao-a** [comment]
@surajrao A single escape will work in tonight's Insiders.
You can get the Insiders from https://code.visualstudio.com/insiders
