### ISSUE TITLE
Build a real file system provider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34218]
This to make #29194 and the goal is to build a file system provider that connects to a FTP server. We want to support the following things

* stuff works with `scheme`, not `authority`
* show remote files in the explorer like normal files
* allow read, write, and delete files
* allow to list, create, delete folders

The outcome of this is a more mature and complete (internal and external) API  and a sample that illustrates how to use it. And last but not least this is to identify debt and false-assumptions about running on a (local) file system.

**Comment by therealkenc** [comment]
Linking [ghedit](https://github.com/spiffcode/ghedit) for posterity (partially so I can find it again in a search later). A git filesystem provider or ssh filesystem provider would be interesting once the infrastructure is in place. I have a partially complete CIFS client implementation (it can do basic CRUD) that could be turned into a native node module. Is it possible that #25199 might be entertained in the future? That would be one unconventional way to satisfy the Chromebook people (#1031) and WSL people (#13138).

**Comment by siegebell** [comment]
I've been playing around with this and it looks very promising -- thanks!

@jrieken At the moment, it takes several seconds to load the file system in the explorer :(. Maybe  you can change the API to allow batching multiple operations, or else have a `readtree` command that has a depth argument?

**Comment by siegebell** [comment]
[Here is @jrieken's ftp example](https://github.com/jrieken/ftp-sample).

**Comment by jrieken** [comment]
> Maybe you can change the API to allow batching multiple operations, or else have a readtree command that has a depth argument?

The challenge with readtree is that it easily leads to a tree-model of stats and that I want to avoid

**Comment by jrieken** [comment]
> @jrieken At the moment, it takes several seconds to load the file system in the explorer 

There was actually an issue that would always stat *way too much*...  We have fixed that in https://github.com//Microsoft/vscode/commit/22170c2bf665c30119c3aabd67326871c7c1e378 and things should be a lot faster, esp with large directories.

Wrt 'readtree' I'd like to point out that our readdir call is something like 'readddirplus' which doesn't only return filenames but also it's stat. That keeps the number of round trips low.

**Comment by jrieken** [comment]
I am closing this issue now as the whole remote thing has become bigger and this particular issue isn't actionable. We have the ftp sample in its own repo and in this repo we use the [`remote`](https://github.com/Microsoft/vscode/labels/remote)-label as well as `todo@remote` comments
