### ISSUE TITLE
format is not so comfortable

### ISSUE THREAD

**Issue by Skypow2012** [Microsoft/vscode#34211]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.格式化的时候，会在很奇怪的地方换行
2.

**Comment by alexandrudima** [comment]
@Skypow2012 In order for us to reproduce, can you please let us know:
* what language you are using? (C, JavaScript, etc.)
* what is the minimal sample file that you want to format
* what happens vs. what you would expect.
