### ISSUE TITLE
red error lines popping why

### ISSUE THREAD

**Issue by TwistenTiger** [Microsoft/vscode#34217]
#- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
javadebugger|don|0.1.3
python|don|0.7.0
java-debug|DSn|0.0.2
vscode-javac|geo|0.0.46
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.3
java|red|0.9.0
python|tht|0.2.3
`java-imports-snippets|tus|0.0.1
![capture](https://user-images.githubusercontent.com/31478484/30320576-a3a41744-97e5-11e7-938a-c8ec39b0c667.PNG)
![another one](https://user-images.githubusercontent.com/31478484/30320588-ab66f71c-97e5-11e7-973c-a0091b5da25e.PNG)

`

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
These red squiggles are likely being added by your Java extension. If you think it is incorrectly reporting these errors, please try filing an issue against that extension: https://github.com/redhat-developer/vscode-java
