### ISSUE TITLE
VS Code Intellisense seems to wrongly infer revealing module pattern 

### ISSUE THREAD

**Issue by lodybo** [Microsoft/vscode#34214]
- VSCode Version: 1.16.0
- OS Version: Windows 10

Steps to Reproduce:

1. Copy the code below into a file called `greeter.js`
2. Run `node greeter.js` in a terminal

```javascript
var Greeter = (function(country) {
  // Private
  this.country = country;

  function getCountry() {
    return country;
  }
  
  // Public
  var performGreeting = function (name) {
    var country = getCountry();
    
    return 'Hello ' + name + ', from ' + country;
  }
  
  return {
    greet: performGreeting
  }
});

var greeter = new Greeter("The Netherlands");
console.log(greeter.greet("Lody"));
console.log(greeter.country);
```
Using the revelealing module pattern in VS Code seems to trip up Intellisense into suggesting the wrong members. The code above was tested in multiple browsers and consoles and run with Node v6.3.0 which behaved as expected. They ran the `greet()` function and returned `undefined` for `greeter.country`:
```bash
λ node greeter.js
Hello Lody, from The Netherlands
undefined
```

But VS Code's Intellisense reports that `greeter` only contains `country`:
![image](https://user-images.githubusercontent.com/1598330/30318944-d12c85de-97ae-11e7-9e18-b82689b34769.png)

It also reports the expected interface of `greeter` for the class itself (`Greeter`):
![image](https://user-images.githubusercontent.com/1598330/30318992-eed8773c-97ae-11e7-8678-9e279455fa38.png)

What is expected is VS Code correctly inferring `greeter.greet` to be a function of `Greeter`, with a parameter `name`.

This was reproduced in a clean folder of VS Code, with no extensions (launched with `code --disable-extensions`), and no `jsconfig.json`.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18496
