### ISSUE TITLE
Failed to debug native node addon if attach node process

### ISSUE THREAD

**Issue by wip0** [Microsoft/vscode#34219]
- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:24:31.374Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
MochaSnippets|Ala|0.0.1
Handlebars|and|0.2.0
tslint|eg2|1.0.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-favorites|how|1.1.5
language-julia|jul|0.7.0
Align|ste|0.2.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. node --debug-brk index.js 
2. attach and run
3. Debug Console shows as below
![vscodebug](https://user-images.githubusercontent.com/20312631/30321159-452bb81c-97df-11e7-9264-250121965af1.png)

While VSCode 1.15.1 works on the same code and launch.json

![vscodeok](https://user-images.githubusercontent.com/20312631/30321280-b2f380b4-97df-11e7-8ed0-0e65f84730dd.png)
---
I tried with procmon to see what happen.
![procerror](https://user-images.githubusercontent.com/20312631/30321540-a228e8a4-97e0-11e7-88a5-66d1d7ee1c49.png)
node process which was spawned from vscode tried to load the native addon. And it failed because of lack of dlls.

But in VSCode 1.15.1, my process loaded native addon and everything went ok.
![procok](https://user-images.githubusercontent.com/20312631/30321790-8263788a-97e1-11e7-9daa-9c1e06467f9b.png)

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode-node-debug/commit/7c55e9e41862e5de2a27adb3f0cb581b3283aa99

It should be fixed in tomorrow's insiders. If that is not the case please let me know - thanks!

**Comment by wip0** [comment]
@isidorn Thanks. It works.

**Comment by isidorn** [comment]
@wip0 thanks for checking. Adding verified label
