### ISSUE TITLE
Sidebar file tree breaks on scrolling while entering a new file name

### ISSUE THREAD

**Issue by Loilo** [Microsoft/vscode#34220]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-simple-icons|Lau|1.6.0
vscode-paste-and-indent|Rub|0.0.8
vscode-apache|mrm|1.1.1
debugger-for-chrome|msj|3.2.1
vetur|oct|0.9.7
vscode-template-literal-editor|pli|0.8.4

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a project with many folders (you should be able to scroll in the sidebar file explorer). Maybe expand some folders and have some colorful file icons enabled, it will help recognizing the effect described below.
2. In the sidebar file explorer, right-click any of the upper folders and click "New File" or "New Folder".
3. Now start scrolling down until the input for the new file name disappears from the viewport.
4. Scroll up again: The input is gone.

   Instead, all kinds of crazy stuff will happen to the file tree. Keep scrolling up and down, try different scrolling speeds. You will notice files and folders randomly disappearing and re-appearing, or changing order — never in your sight, only in parts of the file tree you're just about to scroll to.

   It even happened to me that I clicked on a `.gitignore` file but an `.editorconfig` file was opened instead. I scrolled down and up again, and there actually *was* an `.editorconfig` which must have been disappeared before.

I was able to reproduce this bug with and without extensions and on two different machines, both running macOS Sierra.

---

Reproduces without extensions: Yes

**Comment by Loilo** [comment]
Additional note: I'm also able to reproduce this on Windows 10:

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063

**Comment by isidorn** [comment]
I can reproduce that the tree seems to think it has lower height than expected so there is some space at the bottom of the view. However no wrong files get opened on click.
I am nicely getting a dom [BLUR event](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L394) once the user scrolls down, so the new file input gets nicely disposed.
@joaomoreno was there already some issue similar to this one? The strange thing is that I do not see tree.layout being called from anywhere.

**Comment by isidorn** [comment]
Notice that the `monaco-tree-rows` has the correct height, while the last tree-row seems to be positioned not at the very bottom

![tree](https://user-images.githubusercontent.com/1926584/30381080-aadecb4c-989b-11e7-93c0-e4a558f6a5ea.gif)

**Comment by joaomoreno** [comment]
#22269
