### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by sanderbos1402** [Microsoft/vscode#34225]
When defining tasks it will work okay for the first folder.
Tasks will be stored in the tasks.json AND the workspace.
When working with tasks for the second folder tasks will be stored in tasks.json, but will not be added to the workspace. 
These task cannot be used because they will not be found.
You also cannot use them as a build task in your launch configuration because they will not be found.

- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
nativescript|Tel|0.7.2
docomment|k--|0.0.17
csharp|ms-|1.12.1
PowerShell|ms-|1.4.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.2.1
vsc-angular-cli|web|1.0.0

---

Steps to Reproduce:

1. Open a workspace
2. Add tasks for the first folder
3. Add tasks for the second folder

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/29454.
