### ISSUE TITLE
VSCode output windows opens automatically when typing

### ISSUE THREAD

**Issue by linocatucci** [Microsoft/vscode#34221]
- VSCode Version: 1.16.0
- OS Version: macOs 

Output Window of Visual Studio Code opens on its own while I'm typing or just clicking Angular code I'm working in the code base on and it's very disturbing, it takes to much screen space.

Steps to Reproduce:

1. typing code in a typescript file while the file is not complete yet.
2. the output window opens 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@linocatucci the output window doesn't open itself for me. Which output window shows itself? Is it trying to communicate some form of error ?

I once noticed it opening when I had the eslint extension installed and it opened itself to complain that it cannot find the node module or something...

**Comment by linocatucci** [comment]
hello Alexandru,
the output window always opens when I save a .ts file and the compiler starts. It will output the compile information.
I have read in the documentation that you can set a property in the task.json file but I can't find the task file.

_The behavior of the terminal can be controled using the presentation property of a task. It offers the following properties:

reveal: Controls whether the Integrated Terminal panel is brought to front. Valid values are:
always - The panel is always brought to front. This is the default.
never - The user must explicitly bring the terminal panel to the front using the View > Integrated Terminal command (Ctrl+`).
silent - The terminal panel is brought to front only if the output is not scanned for errors and warnings._

Cheers,
Lino

**Comment by isidorn** [comment]
@linocatucci hi, this is probalby caused by an extension. I recommend that you disable all extensions and still try to reproduce. Doing that you can find which extension is to blame and then you can open an issue on their side.
On the other hand if you are using tasks, you can configure your task to not open the output. On how to configure that please consult our Tasks documentation.
Thanks

**Comment by linocatucci** [comment]
Hi Isidorn, 

thanks for the suggeston, I will do that.
Cheers,
Lino

**Comment by linocatucci** [comment]
Hello Isidorn,

Looks like it was indeed one of those strange Angular plugins!
Thank you for your help!

**Comment by isidorn** [comment]
@linocatucci welcome
