### ISSUE TITLE
Command "Files: Save all" is not enabled in the current context

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#34226]
Steps to Reproduce:

1. Open VS Code
2. With no files modified, open the command palette and search "Save all"
3. Select the command "Files: Save All"

**Expected**: The command will run silently (in this case, doing nothing)
**Actual**: The command results in an info message shown saying "Command 'Files: Save all' is not enabled in the current context"

More context: I had just done a global find and replace which opens every file in a tab. I used the command to save them all. A few moments later I couldn't remember if I had saved them, so I executed the command again to be safe. I don't need VS Code to tell me that it didn't save them a second time, I just need to know that if they weren't saved before, they are now.

**Comment by bpasero** [comment]
Yeah, we have another issue to only show commands in the palette when it makes sense. That should take care of this one too.
