### ISSUE TITLE
Version 1.16 issues with GPU support, older versions worked just fine

### ISSUE THREAD

**Issue by pgossmann** [Microsoft/vscode#34227]
After installing VS 1.16 I get a "black screen" issue. 
It is described in the FAQ and when applying the workaround to "DISABLE THE GPU support" it works again.
However this is anoying and due to version 1.16

I reinstalled the older version 1.15 and the issue is gone.

- VSCode Version: 1.16 32 bit
- OS Version: Windows 10

I got a DELL Latitude E7470 with 2 external screens connected (if taht has anything to say)

Steps to Reproduce:

1. install new version 1.16 
2. open VS Code -> I get a black screen on startup
3. context menus in Windows Explorer no longer work

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by pgossmann** [comment]
Doesn't seem to happen with the Insiders Preview!
Thanks!
