### ISSUE TITLE
VSCODE - TFSVC - Make Associate Work Items create actual link between changeset and work items

### ISSUE THREAD

**Issue by moital** [Microsoft/vscode#34223]
**In VSCode with TFSVC as source control,**
**please make "Associate Work Items" operation create actual link between changeset and work items** 

**Env Details  :** 
- VSCode Version: 1.16.0
- OS Version: Windows 7 Enterprise 64 bit
- SCM : TFSVC (with Visual Studio Team Services Extension)

**Steps to Reproduce :**
1. Make some change in text file within workspace.
2. Goto View->SCM and select "Associate Work Items" from SCM menu.
3. Select a work item from the list. The ID and Title of the work item enter the Message / Comment field.
4. Press "Ctrl-Enter" to CheckIn. The Association is implemented as it currently seems in VSCODE just by having the ID and Title mentioned in the comment of the Checkin. Would expect to have VSCode create an actual link between the changeset and work item same as would be if the operation would be done in regular TFS Explorer in regular Visual Studio.

Thank u

Currently On VSCode Side :
![image](https://user-images.githubusercontent.com/31817354/30323411-cb3adb3c-97c5-11e7-8678-980a10716742.png)

Currently On TFS Side : 
![image](https://user-images.githubusercontent.com/31817354/30323379-ae2b27e0-97c5-11e7-9695-8db81650d53e.png)

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/vsts-vscode/issues/316
