### ISSUE TITLE
Stage all changes

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#34230]
- VSCode Version: 1.16
- OS Version: Win 10

In Source Control there are options to "Discard All Changes" and "Unstage All Changes"  but no "Stage All Changes" 

I want to stage all files except for 1. There's no easy way to do this.  "Stage All Changes" option would be really helpful in this case, because then I could just stage all then unstage that 1 file. 

It's possible in `git gui`

**Comment by joaomoreno** [comment]
Can you double check? The command is there. Both available in the command palette as well as an icon in the viewlet.

**Comment by laggingreflex** [comment]
Ah yes, it's there in both those places, I was trying to find it in this menu:

![image](https://user-images.githubusercontent.com/2523987/30336395-b455e460-9802-11e7-9823-c43b6181a15e.png)

**Comment by joaomoreno** [comment]
I've added the command there.
