### ISSUE TITLE
Live preview the selected quick open file in an unpinned editor

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#34237]
This is an idea for a feature.

# Use case

I am a developer in a codebase that has files with the same or similar names. When I go to quick open one of these files I often have to guess which file is the right one because the full path isn't enough context for me to quickly remember which is the right one. I end up opening multiple files until I guess correctly and find the one that I really want.

FWIW, there are almost 70 non-unique file names in vscode. Many of these are pairs of interface and implementation. This happens in private code bases as well.
```
find src/ -name *.ts | grep '\([^/]\+\)$' -o | sort | uniq -c | sort -r | head -n 20
```

# Proposal

1. User types a query into quick open (e.g. "actions.ts").
2. After a delay of no more input, the selected option (i.e. the file that would open if you hit enter) opens in an unpinned editor.
3. Cursoring up/down in the quick open list updates the unpinned editor with the selected file.
4. Hitting enter closed quick open and pins the editor.

Imagine a new unpinned editor behind quick open is live updating as I am cursoring up/down here:
![screen recording 2017-09-12 at 08 26 am](https://user-images.githubusercontent.com/754768/30334303-0a6f5954-9794-11e7-9021-cabf1cf11623.gif)

It isn't ideal that the quick open would obscure part of the file, but it would be better than nothing. 

Thoughts?

**Comment by rpavlovs** [comment]
+1, miss this since I moved from Sublime
