### ISSUE TITLE
Hightlight symlink files in the explorer pane

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#34238]
In the explorer, I think it would be useful if the symlink files have a different icon (or a different representation than the regular files). Many times I have to resort to the console to confirm which are symlinks.

**Comment by bunchjesse** [comment]
+1 for this
Also, it would be nice to have a different treatment for symlink'd folders.

**Comment by dmlemos** [comment]
Hi @isidorn. Would you mind pointing to the original issue? I am afraid I can't find a similar one.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/11539
