### ISSUE TITLE
ImportFileAction doesn't use URI

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34235]
re  #34218

Most file actions work on URI and to make them work with uris from other schemes little work is needed, however it seems that the import action and the drag&drop model work with *paths*:
https://github.com/Microsoft/vscode/blob/joh/ftp/src/vs/workbench/parts/files/browser/fileActions.ts#L852

**Comment by bpasero** [comment]
@jrieken I hope I did the right thing in https://github.com/Microsoft/vscode/commit/47cfc8bf7aa3778e358c15d0cfa483eb0e637522#diff-9404b1da682862c61dce10b84ff76e5cR850
