### ISSUE TITLE
Partial staging only works on the right hand side view?

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#34231]
- VSCode Version: 1.16
- OS Version: Win10

Steps to Reproduce:

1. Click on an unstaged file to open its working tree view
2. Select a few changed lines on the left hand side view
3. Menu on top-right -> stage selected range

It doesn't work.  It only works when you do this from the right hand side view. 

When trying to stage removed lines it's more intuitive to do it from the left side:

![image](https://user-images.githubusercontent.com/2523987/30329805-02d80864-97f1-11e7-9d19-f29e3e58569f.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This is as designed. You must select the text in the right hand side.

**Comment by laggingreflex** [comment]
With this approach you can't stage/unstage just 1 deleted line from a hunk of deleted lines.

Suppose I have 3 deletions, all consecutive (so a one "hunk" in Git GUI), and I want to stage the middle line.

In Git GUI I'd do this:

![image](https://user-images.githubusercontent.com/2523987/30419634-b38ed7e6-9954-11e7-9885-956172747f95.png)

But in VSCode on the right side there's only **absence** of code in which you can't select the middle bits, you can only select the entire deleted block as a whole:

![2017-09-14_13-59-17](https://user-images.githubusercontent.com/2523987/30419698-f7c93bae-9954-11e7-829d-3bd6ace8071c.gif)


Repro for this and another issue (#34360) https://github.com/laggingreflex/vscode-git-test

**Comment by joaomoreno** [comment]
Yes, we only support staging/upstaging the entire hunks we collect together. Created #34430 for that.
