### ISSUE TITLE
Extension host crashes out of memory

### ISSUE THREAD

**Issue by melloc01** [Microsoft/vscode#34234]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-jest|Ort|2.3.0
scss-scan|aar|0.1.67
scss-lint|ada|0.0.18
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.1
gitlens|eam|4.4.3
code-runner|for|0.7.1
vscode-javac|geo|0.0.46
docthis|joe|0.4.8
vscode-styled-components|jpo|0.0.8
node-module-intellisense|lei|1.4.0
code-beautifier|mic|1.7.2
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|2.9.1
sort-imports|pet|2.4.0
java|red|0.9.0
vscode-icons|rob|7.12.0
autoimport|ste|1.2.2
gitblame|wad|2.2.0

(14 theme extensions excluded)

---

Steps to Reproduce:

1. Open VS Code
2. Wait for it to crash

Reproduces without extensions: No

Console output:
```
[uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
e._onExtensionHostCrashed @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28 Extension host terminated unexpectedly.
e.doShow @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28 Extension Host
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:28 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/share/code/libnode.so]
 2: 0x7f726effbec7 [/usr/share/code/libnode.so]
 3: 0x7f726ed34bb7 [/usr/share/code/libnode.so]
 4: 0x7f726ed34b35 [/usr/share/code/libnode.so]
 5: v8::internal::Factory::NewTransitionArray(int) [/usr/share/code/libnode.so]
 6: 0x7f726e7fae1d [/usr/share/code/libnode.so]
 7: 0x7f726e918ea0 [/usr/share/code/libnode.so]
 8: 0x7f726e915e68 [/usr/share/code/libnode.so]
 9: 0x7f726e915cbb [/usr/share/code/libnode.so]
10: 0x7f726e92dad9 [/usr/share/code/libnode.so]
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/share/code/libnode.so]
12: 0x7f726e91b5de [/usr/share/code/libnode.so]
13: 0x7f726e91f62a [/usr/share/code/libnode.so]
14: 0x7f726eccfbe9 [/usr/share/code/libnode.so]
15: 0x7f726eccf9c3 [/usr/share/code/libnode.so]
16: 0x7f726ecd1ba7 [/usr/share/code/libnode.so]
17: 0x7f726eccec26 [/usr/share/code/libnode.so]
18: 0x7f726eb5424e [/usr/share/code/libnode.so]
19: 0x2516d4a0415d

<--- Last few GCs --->

[29336:0x2337be422000]   160430 ms: Mark-sweep 2057.1 (2207.6) -> 2057.1 (2187.1) MB, 3510.6 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3511 ms) last resort 
[29336:0x2337be422000]   164006 ms: Mark-sweep 2057.1 (2187.1) -> 2057.1 (2187.1) MB, 3575.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x153f97ab959 <JS Object>
    0: builtin exit frame: stringify(this=0x153f9790771 <a JSON with map 0x3f1fa4d06199>,0x82336802311 <undefined>,0x2d4924437931 <JS Function r (SharedFunctionInfo 0x4133d5c6739)>,0x1a2fc107f0b1 <JS Array[3]>)

    1: arguments adaptor frame: 2->3
    2: callOnRemote [/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:~28] [pc=0x2516d54d0433](this=0x11275e472039 <a e wi...

```

**Comment by melloc01** [comment]
I was uninstalling some plugins to find out which one was causing this and saw that after uninstalling [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) it stopped crashing.

**Comment by alexandrudima** [comment]
@aeschli Would you perhaps know some specifics about the Java extensions, is it possible it has a memory leak in the extension code ?

**Comment by aeschli** [comment]
@fbricon Fred FYI.
@melloc01 Do you have an example project where you see this?

**Comment by melloc01** [comment]
Thanks guys,

@aeschli would you suggest an open source project to test whether it crashes or not?

This one is private.

**Comment by melloc01** [comment]
Yesterday I uninstalled it and no crashes happened until I installed it back - pretty sure it is the extension.

**Comment by fbricon** [comment]
@melloc01 did it crash after opening a Java project or java files?

**Comment by melloc01** [comment]
Java project @fbricon

**Comment by fbricon** [comment]
@melloc01 a sample project reproducing the error would be mighty helpful.

@aeschli the vscode-java extension is fairly simple. I'm not a javascript or typescript expert but I don't see anything obvious. Any advice on how to track memory leaks in vscode extensions?

**Comment by melloc01** [comment]
@fbricon yeah, I know, I'm a Java rookie tho, I use this extension to help me patching any small issues.

I just tested in this project: https://github.com/gabrielf/maven-samples and it works fine.

Seems to be related to the project.

I managed to attach a strace on the process, not sure if it'll help but this was what I got:

```
strace -s 800 -p 27457
strace: Process 27457 attached
futex(0x7fa810df79d0, FUTEX_WAIT, 27458, NULL <unfinished ...>
+++ exited with 13 +++
```

Which is an `EACCES`.
hmm.. maybe my permissions are messed up on some place the plugin uses for caching?

**Comment by aeschli** [comment]
With the latest insider build it's now very easy to profile the extension host. Just open the dev tools, and check the console for the chrome debug URL that lets you open the chrome dev tools on the extension host node process.
I tried that with a simple project, but didn't see hangs or any big memory allocations.

**Comment by aeschli** [comment]
Closing. @melloc01 Please file an issue against the [Java extension](https://github.com/redhat-developer/vscode-java) with an example project.
