### ISSUE TITLE
Unstaging doesn't update the view

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#34232]
- VSCode Version: 1.16
- OS Version: Win 10

Steps to Reproduce:

1. Stage some changes
2. Open the staged changes view
3. Either unstage the file completely or unstage some lines partially 

The view doesn't update to reflect the status

Not sure what should happen when you completely unstage the file (should it close that view?) 

But when doing partial unstaging it should update it, which it does when you close and reopen the same view. 

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
#34209
