### ISSUE TITLE
Git out of sync on mounted drive

### ISSUE THREAD

**Issue by mlabrecque** [Microsoft/vscode#3423]
When I attempt to load a project located on a drive mounted via smb:// the git tab in VS Code reports that all files in the project as "changed". When I go to the command line, my Git status command shows the working directory as clean. I have attempted to refresh the git status and it shows the spinner for 10 seconds, but then no changes appear in the Git tab. It just shows 99+ files changed, when in reality, nothing has. 

Perhaps this is user error and I am missing something?

**Comment by mlabrecque** [comment]
Just a follow up comment on this issue, I have ran into similar problems caused by file permissions. I attempted to normalize the file modes, but it didn't seem to make a difference for the above issue.

Thanks!

**Comment by joaomoreno** [comment]
Do you still have this issue?

**Comment by mlabrecque** [comment]
I am now using a Vagrant environment instead of the system mentioned above, so I have not tested this since I have logged the ticket. Sorry!

Let me know if I can provide you with any additional details to diagnose this issue, or it can be closed if you are confident that it is no longer relevant :)

**Comment by joaomoreno** [comment]
No problem. I'll close it then. Thanks for the reply.

**Comment by waldoow** [comment]
Hi,
i do have the same issue today.
