### ISSUE TITLE
PowerShell snippet includes variables in tab stops

### ISSUE THREAD

**Issue by mrchops1024** [Microsoft/vscode#34236]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
code-runner|for|0.7.1
vscode-angular2-emmet|jak|2.0.3
csharpextensions|jch|1.3.0
Angular2|joh|2.7.0
docomment|k--|0.0.17
vscode-exec-node|mir|0.5.0
mssql|ms-|1.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.2
angular2-inline|nat|0.0.17
live-server-preview|neg|0.0.4
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.8.3
autoimport|ste|1.2.2
cordova-tools|vsm|1.2.12
quokka-vscode|Wal|1.0.62
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Add the following snippet to PowerShell snippets:

```
    "Test snippet": {
        "prefix": "_test",
        "body": [
            "$$test = '${1:value for test}'",
            "$0"
        ],
        "description": "Test snippet for tab stops"
    }
```
2. Open new PowerShell window
3. Add snippet by entering `_test` followed by `TAB`
4. The start position is on the `value for test` value.
5. Hit `TAB` and it will jump to the variable `$test`
6. Hit `TAB` again and it will go to the final cursor position.

Reproduces without extensions: Yes

---

I'm assuming it's because the $ is used to identify the tab stops, but in PowerShell I wouldn't want to tab over every variable in a snippet. I also had to add `$$` for the variable name or else it would be lost upon completion of the snippet. I haven't been able to figure out if there is a way to include $ in a PowerShell snippet without including it in the tab order.

**Comment by jrieken** [comment]
> I'm assuming it's because the $ is used to identify the tab stops,

Yes and no, it is unfortunate... The grammar and parser identifies things like $1, ${2:default} as tabstops/placeholders and things like $foo, ${foo:default} as variables. The problems is that our old parser had a bug and that it would interpret the variable-syntax as tabstop. This has left us with thousands of falsy snippets that we don't want to break...

@mrchops1024 Do you want to insert `$$test` or `$test` (single dollar)? Can you try to escape the dollar with backspace (and backspace with backspace) so, `\\$test = ${1:fooo}`?

We should also consider a flag that marks a snippet as proper, e.g. no funky handling of variable/tabstop confusion required...

**Comment by mrchops1024** [comment]
@jrieken Escaping the dollar sign AND the backslash seems to be the key. I tried escaping the dollar sign at first, but didn't think of escaping the backslash. I tried the double dollar-sign and it seemed to be working, except for the aforementioned tab stop issues. Using `\\$test` properly inserts `$test` and is ignored when tabbing.

Thanks!

**Comment by jrieken** [comment]
Great. Yeah, it messy and I am sorry for that. TextMate escapes things with a backslash, and JSON escaped backslashes with backslashes..
