### ISSUE TITLE
[BUG]Integrated Terminal font dramatically different

### ISSUE THREAD

**Issue by peterschussheim** [Microsoft/vscode#34242]
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

# Description
**EDITED 09/13**:  Updated this morning and terminal looks beautiful again! 🥇  What changed?
I noticed after updating **yesterday** that the integrated terminal's font appears quite different than it used to.  Were there commits merged that are related to this part of VSCODE?

Unfortunately, I don't have a screen shot handy of how it used to look, but i've included how it currently looks.

Thank you in advance.

# Screenshot

### Added 09/13 (appears to be fixed 👍 )
![code - insiders011](https://user-images.githubusercontent.com/3654683/30378476-512a707c-9861-11e7-8835-b6e02afccd82.jpg)

### Undesirable rendering of terminal font
![code - insiders010](https://user-images.githubusercontent.com/3654683/30341360-c607ce9c-97c3-11e7-807d-358d9bb55499.jpg)

**Comment by peterschussheim** [comment]
@Tyriar: updated with a screenshot showing integrated terminal after updated insiders build this morning.  You can close this issue if you want since it appears to be fixed but I would be interested in understanding why this happened.  :)

**Comment by Tyriar** [comment]
I'm glad it looks better, this was happening because text coordinates were being drawn as ceiled integers, not floating point numbers. Here's the fix https://github.com/sourcelair/xterm.js/pull/980
