### ISSUE TITLE
Integrated terminal prompt cut of on first boot.

### ISSUE THREAD

**Issue by MEXdave1997** [Microsoft/vscode#34243]
- VSCode Version: 1.17.0-insider
- OS Version: Windows 10 Build 15063.540

Steps to Reproduce:

1. Launch VSCode Insider 
2. Open Integrated Terminal in the prefered way. 

Reproduces without extensions: **Yes**/No

Comment: 
This isn't really a major issue, but it is kind of annyoing that the integrated terminal gets thrown off its positioning on first boot. Below is an image of the integrated terminal opened on first boot: 
![screenshot 56](https://user-images.githubusercontent.com/17634751/30341860-82ed71d2-97ac-11e7-9b83-df6387505754.png)

EDIT: This is also on VSCode Stable Version 1.16

**Comment by Tyriar** [comment]
@MEXdave1997 thanks for the report, I have some follow ups:

- Can you share your settings.json file?
- Does this happen whenever you create a terminal or just for the first one?
- Does the issue go away completely after resizing the panel?

**Comment by MEXdave1997** [comment]
Ill answer some of these questions here:

* The settings.json files for both versions can be found in [this gist](https://gist.github.com/MEXdave1997/ecaa0cefd35e660cb8825fef85ba3852).
* Yes, this happens pretty much every time I open the integrated terminal panel.
* No, in fact, the issue gets worse if I make the panel larger, and changes very minimally as I make the panel smaller.

**Comment by Tyriar** [comment]
I pushed a fix for this.

@roblourens a quick verification on your mac would be appreciated as I wasn't seeing it quite as bad as you were.

**Comment by MEXdave1997** [comment]
I will try the fix now, and will update if anything comes up. Thank you for this! 😄
