### ISSUE TITLE
PHP syntax highlighting has gone berserk

### ISSUE THREAD

**Issue by mpenna** [Microsoft/vscode#34244]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
vscode-twig-pack|baj|1.0.0
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
EditorConfig|Edi|0.10.1
harbour|eko|0.0.8
harbour-custom|eko|0.0.8
php-intellisense|fel|1.5.1
vue-snippets|hol|0.1.4
beautify|Hoo|1.1.1
phpcsfixer|mak|0.0.1
mssql|ms-|1.1.0
atom-keybindings|ms-|3.0.1
cpptools|ms-|0.12.3
csharp|ms-|1.12.1
vetur|oct|0.9.7
laravel-blade|one|1.9.0
vscode-subword-navigation|ow|1.1.5
vscode-docker|Pet|0.0.16
vscode-format|rya|0.0.6
php-formatter|Sop|0.2.4
sort-lines|Tyr|1.3.0
codedox|wig|1.2.5

(6 theme extensions excluded)

---

Not sure what's going on, but I've noticed that the PHP syntax highlighting has been off since the past couple of VSC updates. This happens either with or without extensions enabled and also happens when using VSC Insiders' version. 

Reproduces without extensions: Yes

![snag- 2017-09-12-15-48-45](https://user-images.githubusercontent.com/6953141/30342910-ecddab1e-97d1-11e7-8592-680bd8998130.png)

**Comment by yavisht** [comment]
+1 
<img width="288" alt="screen shot 2017-09-13 at 10 10 27 am" src="https://user-images.githubusercontent.com/6112201/30354075-bfd476b0-986d-11e7-85da-bb2b6b7e179f.png">

**Comment by danfisher85** [comment]
I got the same inside PHP files

![screen shot 2017-09-13 at 14 15 40](https://user-images.githubusercontent.com/7786257/30376852-10df5a00-988e-11e7-9a20-9a7781bef7da.png)

**Comment by aeschli** [comment]
@mpenna Please file the code snippet. @yavisht @danfisher85 Please file separate issues unless its exactly the same issue.

**Comment by roblourens** [comment]
These are probably all related to https://github.com/Microsoft/vscode/issues/34204, which happens when you have a php close tag inside PHP curly braces.

I'm not sure about @mpenna's example though, can you include the full text? Thanks.

**Comment by mpenna** [comment]
The actual code has a lot more substance but what is shown here is enough in order to give the result being depicted on the screen grab sent earlier. 

```
namespace App\Http\Controllers\Auth;

use Socialite;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Domain\Users\Events\UserNetworkCreated;
use Domain\Users\Repositories\UserRepository;
use Domain\Networks\Repositories\NetworkRepository;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Infrastructure\Services\ActivationManagerContract;
use Infrastructure\Services\InvitationManagerContract;

class LoginController extends Controller
{
    use AuthenticatesUsers {
        attemptLogin as attemptLoginAtAuthenticatesUsers;
    }

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * @var ActivationManagerContract
     */
    protected $activationManager;

    /**
     * @var InvitationManagerContract
     */
    protected $invitationManager;

    /**
     * @var UserRepository
     */
    protected $userRepository;

    /**
     * @var NetworkRepository
     */
    protected $networkRepository;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(
        ActivationManagerContract $activationManager,
        InvitationManagerContract $invitationManager,
        UserRepository $userRepository,
        NetworkRepository $networkRepository
    ) {
        $this->activationManager = $activationManager;
        $this->invitationManager = $invitationManager;
        $this->userRepository = $userRepository;
        $this->networkRepository = $networkRepository;

        $this->middleware('guest', ['except' => 'logout']);
    }
}

```

**Comment by roblourens** [comment]
I believe all these issues are fixed. Let me know if they repro in the latest.
