### ISSUE TITLE
Allow users to specify setting to start all projects in zen mode

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#34249]
I am not sure if this is currently possible, but if it is, it would be really amazing.

If not, I really wish it was added. Thank you.

**Comment by isidorn** [comment]
Please use 	`"zenMode.restore": false`
That way vscode will always restore zen mode on startup.
As for the setting to start every new project in zen mode, I would only consider adding that if more users ask for it. I personally am not a big fan of the idea
