### ISSUE TITLE
It became to be not styling with Markdown in fact.

### ISSUE THREAD

**Issue by Clouver** [Microsoft/vscode#34241]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:26:08.116Z)
- OS Version: Linux x64 3.10.0-514.26.2.el7.x86_64
- Extensions: none
---

Steps to Reproduce:

1. I did write a .md and it worked amazingly. (with the newest version 1.16)  
2. I installed some extensions for other languages such as C/C++ Python and JAVA. And vim in fact.  
3. Then I found that it works in other language mode , WITH ONLY A MARKDOWN FILE OPENED. 
4. I tried to remove all extensions, reinstall vscode, even downgrad to 1.14. But it did not help. Its configs seem to be saved.

  I haven't done any configuration by code or something. I guess it's broken by my rude actions to install so many extensions at one time. 

  I want to know how to delete ALL relating things about vscode then I can reinstall and get a brand new one.

Thanks at first. It's a great app. ：）

**Comment by mjbvz** [comment]
Can you please provide some screenshots of the issue. It is not clear to me what is going wrong

**Comment by Clouver** [comment]
I mean some of the highlight dispeared. Such as `&emsp;` and`  `at the line-ends.  

I'm sorry that it works normally when I changed a theme.  I found the theme button finally.   

Sorry again for my bad memery. :)
