### ISSUE TITLE
Gulp task `vscode-linux-x64-build-debian` creates dummy DEB installer

### ISSUE THREAD

**Issue by khionu** [Microsoft/vscode#34247]
"Dummy" meaning only includes the meta data for the Application Menu, Icon, File Association, etc. None of the actual executables for the program.

- VSCode Version: 3864be5
- OS Version: Debian 9.1.0 (Stretch)

Steps to Reproduce:

1. Install dependencies
2. Clone
3. `./scripts/npm.sh install --arch=x64`
4. `gulp vscode-linux-x64-build-deb`
5. Check `./.build/linux/deb/amd64/deb/<deb installer here>`'s file size (8kb)

**Comment by Tyriar** [comment]
At some point the dependency for that task was changed I think in order to lessen resources on the build agent. See 277dc8bdb99ac2ae820d5ee35d9fa2fedd65d0b1

**Comment by khionu** [comment]
Then [the GitHub Wiki page](https://github.com/Microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux) needs to be updated with the correct steps.

**Comment by Tyriar** [comment]
@khionu good call, fixed 😃

**Comment by khionu** [comment]
Sorry to point this out this much later, but [this section](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#packaging) also could be updated.
