### ISSUE TITLE
[Intellisense] JSON schema works for a few seconds then stops.

### ISSUE THREAD

**Issue by mannyyang** [Microsoft/vscode#34250]
- VSCode Version: 1.16.0
- OS Version: windows 7

Steps to Reproduce:

1. Create workspace JSON schema
2. Hit Ctrl+space to get intellisense
3. Json intellisense works for a couple seconds that gets over written.

Reproduces without extensions: Yes

Here's a sample of my json schema in the settings.json file inside of the .vscode folder.
![image](https://user-images.githubusercontent.com/3444220/30349191-efd27116-97c6-11e7-8015-1ae95a6d0874.png)

Here's a gif of my experience:
![schema-bug](https://user-images.githubusercontent.com/3444220/30349210-fcf0b916-97c6-11e7-8567-b7c9d1f393dc.gif)

As you can see, when I reload the window and hit ctrl+space, the intellisense works for a little bit then returns to its default state. Very weird, never had this happen before.

Any help would be appreciated!

Thanks,
Manuel Yang

**Comment by aeschli** [comment]
@mannyyang The proposals you see seem to be all textual proposal, so it doesn't seem like the schema got used at all. And yes, it strange that the proposals get resorted
Can you by chance paste the content of the settings?

**Comment by mannyyang** [comment]
Hey @aeschli, thanks for responding. From the gif above, it seems as though the schema does gets parsed and consumed in the first few seconds, then for some reason, is removed. The settings just has a json-schema property and is pretty big so I put it in a pastebin: https://pastebin.com/Pg2HUaPP.

This schema was working before so I'm clueless on how to debug this.

**Comment by aeschli** [comment]
I fixed the issue. There was a bug with resolving a top level $ref in schemas in workspace settings.
As a workaround, don't use $ref at top level, or copy the schema definition to the user settings, or in a file in the workspace. Or use the next insiders build.

**Comment by mannyyang** [comment]
Hey @aeschli,

Just wanted to say thanks for the updates and fix! Just wanted to provide an extra verification on this. Glad there's smart developers actively supporting this great software.

👍👍👍👍👍

**Comment by aeschli** [comment]
@mannyyang You are welcome, thanks for using VSCode and thanks for your help!
