### ISSUE TITLE
vscode.workspace.onDidChangeWorkspaceFolders fires before workspace configuration is loaded

### ISSUE THREAD

**Issue by beyang** [Microsoft/vscode#34254]
- VSCode Version: 1.17.0-insider (6039e061a8b8f82114500c34c679f991f9607e71)
- OS Version: Ubuntu 16.04.3

Steps to Reproduce:

1. Register a onDidChangeWorkspaceFolders handler like the following in a VS Code extension:
```
vscode.workspace.onDidChangeWorkspaceFolders(e => {
  for (const added of e.added) {
    const config = vscode.workspace.getConfiguration('tasks', e.added);
    console.log(config);
  }
});
```

2. Add a `.vscode/tasks.json` file to a project folder. For example:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"command": "virtualenv -p python ./env",
			"taskName": "Install virtualenv"
		}
	]
}
```

3. Add the project as a workspace folder to VS Code (assuming it is running the extension from step 1).
4. Expected: The task configuration for the just-added workspace folder is printed to the dev console. Actual: An empty object is printed.

It appears that at the time `onDidChangeWorkspaceFolders` is fired, the configuration for the corresponding workspace folder has not yet been loaded. The example given above refers specifically to the tasks configuration, but in general, this applies to any workspace-folder-level configuration. A workaround that seems to work is to use `setTimeout(() => { ... }, 0)` inside the handler. Empirically, the configuration for the newly added workspace folder(s) has been added by the time the inner function runs. It would be useful to run commands that depend on the workspace folder configuration in response to workspace folder addition / removal (e.g., automatically build a newly added workspace folder).

Proposal: make the `onDidChangeWorkspaceFolders` fire after the configuration for newly added workspaces has already been loaded. Or alternatively, add a new event that fires at this time.

**Comment by sandy081** [comment]
Hmm I thought it got fixed already here - https://github.com/Microsoft/vscode/issues/31597

Will see if it is broken.

**Comment by sandy081** [comment]
Looks like it got fixed only on main side. I was updating the configuration model and then triggering folder change and configuration change in sequence. But I think I have to change the order of the sequence to fire configuration change first and then folder change.

**Comment by aeschli** [comment]
I still see this problem. Here's my test program:
```
'use strict';
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(vscode.commands.registerCommand('extension.sayHello', () => {
    console.log("hello world");
    print();
  }));

  context.subscriptions.push(vscode.workspace.onDidChangeWorkspaceFolders(e => {
    console.log("onDidChangeWorkspaceFolders");
    print();
  }));
}

function print() {
  vscode.workspace.workspaceFolders.forEach(w => {
    const config = vscode.workspace.getConfiguration('tasks', w.uri).inspect('version');
    console.log(w.uri.toString() + ' ' + config.workspaceFolderValue);
  });
}
```
- add a workspace folder that has a tasks.json
- run the hello.world command to see that the version is read (`2.0.0` in my case)
- remove the workspace folder and add it again
- on the add event, the version printed as `undefined`
- run the hello.world command again. It is still `undefined`.

![image](https://user-images.githubusercontent.com/6461412/31016436-f59f148a-a524-11e7-812a-e5671b7ebff8.png)

**Comment by sandy081** [comment]
@aeschli Good catch. 
Events are coming in the expected order. But the ext host configuration is still holding to old workspace.

Since MR is only insiders, this is not important to fix now.
