### ISSUE TITLE
Need outline view like atom ide

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#34253]
https://ide.atom.io
atom ide add features

Improved language integration

Get smarter context-aware auto-completion, code navigation features such as an outline view, go to definition and find all references. As well as hover-to-reveal information, diagnostics (errors and warnings) and document formatting.

**Comment by crper** [comment]
Yes , this is great feature....expect...

**Comment by alexandrudima** [comment]
Possible dup of #5605

**Comment by jrieken** [comment]
Yes, duplicate of #5605
