### ISSUE TITLE
Understaing 'Info: Cannot find a program to debug'

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode#34257]
Debugger gives me info
`Info: Cannot find a program to debug`

What does this mean?

- VSCode Version: 1.17.-insider
- OS Version: Win10

**Comment by isidorn** [comment]
This is very likely fixed via https://github.com/Microsoft/vscode-node-debug/commit/7c55e9e41862e5de2a27adb3f0cb581b3283aa99 and should be fixed in the latest insiders. Can you please try if you still see it once you update insiders and if you still see please give us reproducable steps how to see this on our machines so we can investaigte further

Closing for now

**Comment by mboeser** [comment]
having the same issue after installing the update. Never have had this issue in previous VS Code.
VS Code Version: 1.17.1
OS Version: macOS 10.13
Node Version: 8.7.0

**Comment by akmil** [comment]
Having the same issue after installing the update. But only if open single file. 
When open folder wih that file witch need to debug then works fine
VS Code Version: 1.17.1
Node Version: 6.11.2

**Comment by mboeser** [comment]
@akmil Thanks for pointing this out. I can confirm the same on my end; debugs works when a folder is open but not for a single file.

**Comment by isidorn** [comment]
Please try reproducing with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by nixxquality** [comment]
Trying to run a single file without any folder open still says "Cannot find a program to debug."
If I open a folder (any folder) and try to run the same file, it does work though. (Whereas this is broken in stable)

VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T04:23:04.454Z)
Node Version: 8.5.0

**Comment by isidorn** [comment]
Thanks for providing more details.
I have pushed a fix which should be available in tomorrows insiders.
@weinand please code review once you are back from vacation https://github.com/Microsoft/vscode-node-debug/commit/bfc4139012899be9828c55c050a048161ae3c4bb

**Comment by gamevnlc** [comment]
I have same issue like this 

![image](https://user-images.githubusercontent.com/2215185/31644209-33e71b54-b31f-11e7-9383-d9e0ccb39359.png)

**Comment by nixxquality** [comment]
I can confirm that it works both with and without a folder opened now, thanks.

I'm not sure if this should be in a separate issue, but this does not work for TypeScript files (unlike what the documentation says [here](https://code.visualstudio.com/docs/languages/typescript#_typescript-files-and-projects)).
Is single file TypeScript debugging not supported at all?

**Comment by isidorn** [comment]
@nixxquality that is a seperate issue please file a new issue.

**Comment by weinand** [comment]
@isidorn I've restructured your fix a bit so that the non-folder case is now using the same code path as the folder case.
