### ISSUE TITLE
[loc query] Typo in source string

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#34266]
**Context**
src/vs/platform/theme/common/colorExtensionPoint:English (en):plaintext:invalid.id
**Resource**
vs_platform
**Text**
'configuration.colors.id' must be defined an can not be empty
**Query**
Should '**an** can not be empty' be '**and** can not be empty'
**Opened by**
https://www.transifex.com/microsoft-oss/vscode-editor/translate/#es/$/116961350?issue=yes

**Comment by dbaeumer** [comment]
This is either Ben or Martin.
