### ISSUE TITLE
searchservice cpu too high 

### ISSUE THREAD

**Issue by kwangok** [Microsoft/vscode#34268]
**# searchservice  cpu too high and memory too big !**

![p1](https://user-images.githubusercontent.com/5486533/30362329-1671c12e-988e-11e7-82d4-60b6f9d5049c.png)
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.4.0-93-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
weex|jay|0.4.0
AWK|lug|0.0.2
ftp-sync|luk|0.3.3
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
vetur|oct|0.9.7
laravel-5-snippets|sac|2.0.1
python|tht|0.2.3
vscode-lua|tri|0.8.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
There are also a lot of `find` processes in there, so I'm not sure if this is @chrmarti or @roblourens

**Comment by chrmarti** [comment]
Extensions trigger a `find` when they use `findFiles`, that's as designed.

@kwangok The memory footprint seems out of shape. How many files are in your workspace? We cache the list of files when we collect them the first time you use quick open.
