### ISSUE TITLE
community-based file-extension support

### ISSUE THREAD

**Issue by ArtGangsta** [Microsoft/vscode#34262]
I have some file extensions that are unique to my product.  I would like to publish them somewhere, similar to types in typescript, that my customers could automatically download if they open one of my files in VisualStudio code.

When I open a .ps1 file in Visual Studio, it tells me that there's an extension that supports that.

Is there something like that for Visual Studio code?

**Comment by seanmcbreen** [comment]
HI,

Today we have a mechanism for a curated list of extensions to file types that powers our recommendations.  However it's a short list and one that we have no way to accept and manage community contributions.

Let me add this as a feature request and see how much it gets up voted over time.

Sean

**Comment by egamma** [comment]
Closing. This has been covered by performing a search for extension in the market place that supports a particular file extension.
