### ISSUE TITLE
Can't search GBK when autoGuessEncoding=true

### ISSUE THREAD

**Issue by mjlovesz** [Microsoft/vscode#34271]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
code-gnu-global|aus|0.2.2
plsql|cas|0.0.3
xml|Dot|1.9.2
CppSnippets|har|0.0.12
prettify-json|moh|0.0.3
cpptools|ms-|0.12.4
vscode-sql-beautify|sen|0.0.4
change-case|wma|1.0.0

---

Steps to Reproduce:

1.set "files.autoGuessEncoding": true,
2.If my file is encode by GBK and not open 。Nothing was searched When I search Chinese characters。

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
autoGuessEncoding is not yet supported by search. https://github.com/Microsoft/vscode/issues/34315 and https://github.com/Microsoft/vscode/issues/25131
