### ISSUE TITLE
Multi-root workspace git changes indicator

### ISSUE THREAD

**Issue by felixdivo** [Microsoft/vscode#34278]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
latex-workshop|Jam|3.5.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
python|don|0.7.0
vscode-npm-script|eg2|0.2.1
vscode-auto-open-markdown-preview|hnw|0.0.4
HTMLHint|mka|0.3.3
cpptools|ms-|0.12.4
vscode-csstree|sme|0.2.0
easysass|spo|0.0.6
code-spell-checker|str|1.3.9
vscode-arduino|vsc|0.2.6
vscode-react-native|vsm|0.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Have a multi-root workspace with multiple git repositories in there
2. Change a file
3. Now you see in the activity bar on the left on the "Source Control" icon an indicator that one file was changed
4. Click on that "Source Control" icon
5. Now I see a collapsible list of all the repositories in the workspace
6. I have collapsed them to get a better overview
7. Now I can't see on what repository the changes were made. Not a single subtle indicator is there to guide me to the right one. Of course I usually should know what changes I just made but what if a was away for launch and come back to commit everything and start working somewhere else. In that case I would have to click through all the repositories just to find the one with the changes. 

Reproduces without extensions: Yes

---

Proposed solution:

1. Let the indicator on the "Source Control" icon be a summary of all the changes in all the repositories (like it is now)
2. Add such a summary (the blue ball with the white number on it) to the right of each collapsible list item header, while it is collapsed

**Comment by joaomoreno** [comment]
Thanks for the detailed issue, we suffer from the same over here in the team. We're exploring better solutions in #33363, maybe you'd like to subscribe to that issue. 👍

**Comment by felixdivo** [comment]
Ok okay. I sure will. Sorry, I didn't find that issue in the first place.
