### ISSUE TITLE
Source Safe Integration

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [Microsoft/vscode#34272]
Can we please have Visual Source Safe integration?
Many of us have not bought into Git, or other 3rd party off-site source code control systems.
We like things simple.
Our code, safely in our network, behind closed doors, away from competitors.
But, we do not want the bloat of Visual Studio Enterprise or the crippled nature of VS Community edition.
Plus although VSS is old, it still works and is a no-nonsense source code control system, plus we have been using it for over 20 years, and have millions of lines of code held inside it.
Please?

**Comment by joaomoreno** [comment]
This is why we have invested so much in an extensibility story, namely Source Control extensibility. If there is enough demand, there will be someone creating an extension for it. Maybe that someone is you? 😮 

https://code.visualstudio.com/docs/extensionAPI/api-scm
