### ISSUE TITLE
Github Diff will allow single line undo

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#34274]
- VSCode Version:
- OS Version:

Feature:
1. When user will preview the diff between newly saved file and previous copy they should be able to undo single line rather discard all the changes all together. May be beside each - or + button there could be a discard icon.

![diff of individual line](https://user-images.githubusercontent.com/14817471/30365246-f32c0f08-9888-11e7-98b0-8063aec2f9d2.png)

Reproduces without extensions: Yes/No

**Comment by eamodio** [comment]
@khaled-hossain-code While the UI to access this feature isn't ideal, the functionality I think exists today. You can use the `Revert Selected Ranges` command from either the command palette or from the `...` menu on the far left of the tab bar.

**Comment by khaled-hossain-code** [comment]
@eamodio other ide like webstorm has this feature in their UI. And as it works with the command palette and also popup a confirmation modal I think it would be great to have this feature in UI.By the way thanks for the `Revert Selected Ranges` command. I didn't know it exists. :+1:

**Comment by gulshan** [comment]
Related- #30519 #25887

**Comment by alexandrudima** [comment]
Let's track in #25887
