### ISSUE TITLE
change ms-vscode.omnisharp to ms-vscode.csharp

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3427]
(from testing #2701)

@DustinCampbell is going to rename the extension `ms-vscode.csharp`. 

* `extensionAssistant.ts`, line 57: `extensionChecker['ms-vscode.omnisharp'] = omnisharpChecker;`

it might make sense to change the method name too, from `omnisharpChecker` to `cSharpChecker`.

* `extensionTips.json`, line 2: `"ms-vscode.omnisharp": "{**/*.cs,**/project.json,**/global.json,**/*.csproj,**/*.sln}",`

**Comment by weinand** [comment]
@chrisdias what is my role in this? I assume that Dustin publishes the extension under the new name and updates the description and readme.md, right?

**Comment by chrisdias** [comment]
@weinand don't we need to change the identity in our sources?  

in extensionAssistant.ts and extensionTips.json we refer to `ms-vscode.omnisharp` and it needs to be changed to `ms-vscode.csharp`.  

Sorry if I have this wrong.  I assigned to you because I assigned the other OmniSharp message to you :)

**Comment by weinand** [comment]
@chrisdias from your first message I was assuming that Dustin fixes those as part of his extension rename. Sorry if I misunderstood. Please let us know (via this issue) that the final `ms-vscode.csharp` extension has been published and we will then change the two places you've mentioned.

**Comment by weinand** [comment]
@isidorn assigning to you, because you are already familiar with Joh's code.

**Comment by chrisdias** [comment]
@dustincampbell let me know asap when this is ready.

**Comment by isidorn** [comment]
So I changed all `ms-vscode.omnisharp` to `ms-vscode.csharp` inside our code.
I did not publish any extensions or nothing like that

**Comment by DustinCampbell** [comment]
OK. I changed it here as well: https://github.com/OmniSharp/omnisharp-vscode/commit/29a54a0818f6e1a4386802f74f2b8fa1a53b81fb.

I'm planning on publishing the current bits under the new name this morning

**Comment by chrisdias** [comment]
verified
