### ISSUE TITLE
[html] format work only partially due to html.format.unformatted setting

### ISSUE THREAD

**Issue by kasik96** [Microsoft/vscode#34285]
- VSCode Version: 1.16.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Paste this code to your VS Code https://gist.github.com/kasik96/cfbc30d536b0819488073f7f3909e538
2. Set to HTML
3. Formate code with right click (Format Document)

It do absolutely nothing and it looks terrible. But when i use any HTML formatter online it works like a charm, for example http://htmlformatter.com
Any idea why this problem occurs? Thanks.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
The reason why <a> tags are not formatted has to do with the following setting:
` "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var",`

I suggest to remove 'a' from there.

I changed the defaults to only exclude `code`, `pre` and `textarea` from beeing formatted

**Comment by aeschli** [comment]
fixed with https://github.com/Microsoft/vscode/commit/fb5cdf0948d0f60c10628bb2b6193d002ee9e341
