### ISSUE TITLE
Do expressions error

### ISSUE THREAD

**Issue by Akryum** [Microsoft/vscode#34287]
- VSCode Version: Code - Insiders 1.17.0-insider (06529dbcacb796d59e7fc2ca0ac5dbe7c29c099e, 2017-09-13T09:50:23.560Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.1
file-icons|fil|1.0.5
easy-icons|jam|0.3.1
vetur|oct|0.9.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Use the stage-0 babel preset (or the [transform-do-expressions](https://babeljs.io/docs/plugins/transform-do-expressions/) plugin).
2. Write some JSX with do expressions. For example:

```jsx
return <div>
{do {
  if (test) {
    <span>Hello</span>
  }
}}
</div>
```

Or in plain JS:

```javascript
const msg = do {
  if (test) {
    'HELLO'
  } else {
    'MEOW'
  }
}
```

Reproduces without extensions: **Yes**

---

Code using do expressions breaks intellisense and make the code underlined in red with a "Expected expression" message.

![image](https://user-images.githubusercontent.com/2798204/30377278-75b3c6ae-988f-11e7-8642-bc21d47e8d67.png)

**Comment by mjbvz** [comment]
We only support standard JS out of the box. For babel and proposal stage syntax, try: https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel
