### ISSUE TITLE
vscode-node-debug extension w/security vulnerability included in latest release

### ISSUE THREAD

**Issue by Raptormstr** [Microsoft/vscode#34283]
- VSCode Version: 1.16
- OS Version: N/A

Steps to Reproduce:

1. Download the ZIP version (https://go.microsoft.com/fwlink/?Linkid=850641)
2. Open the archive to the path \resources\app\extensions\ms-vscode.node-debug
3. Inspect the version number in package.json

This version of vscode-node-debug is 1.16.9 which includes the version of brace-extension (1.1.6) containing the ReDoS vulnerability (https://nodesecurity.io/advisories/338).  Version 1.1.7 of brace-expansion (https://github.com/juliangruber/brace-expansion/issues/33) corrected the issue and subsequently version 1.17.3 of vscode-node-debug.

**Comment by isidorn** [comment]
Adding verified since the newest stable uses brace-expansion version 1.1.8
