### ISSUE TITLE
File syntax auto-detect is broken

### ISSUE THREAD

**Issue by shobhitsharma** [Microsoft/vscode#34289]
- VSCode Version: 1.16.0
- OS Version: macOS Sierra v10.12.6

Since the last update, the highlighting seems to be broken. For example, the `.pug` file type; with auto-detect option it wont work anymore, but by manually selecting syntax solves it.

[example video](https://i.gyazo.com/e68f37db764e3bd9b0507713e809587f.mp4)

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
I can't reprocude. I open a pug file. It is detected as pug file and syntax highlighting seem to work too.

Please run without extensions and see if it still reproduces.
Does it depend on the file content?

**Comment by shobhitsharma** [comment]
I debugged it. I wasnt using any such extension which does it. But by configuring `.pug` to Pug manually fixed the issue for me. Maybe caused by some conflicts with settings.

Since its resolvable, I close this issue.

**Comment by lordfpx** [comment]
I have the same problem.

I noticed I have 2 entries in my language list: "PUG" and "Pug" (the 1st one is always selected and is not working, when the second one is working, but I need to manually select it.

Maybe the issue comes from those 2 entries ?

**Comment by shobhitsharma** [comment]
@lordfpx Exactly, it appears someone re-wrote the logic for file detection. Anyways, you can use this to your user-settings to fix it.

```
"files.associations": {
    "*.pug": "jade"
  },
```

**Comment by aeschli** [comment]
But that really sounds like an extension that adds a 'PUG' language.

**Comment by shobhitsharma** [comment]
@aeschli You are right about it. Because its not just the pug, but other syntax like `typescript` or `haskell` showed similar issues. I suspect its some `Auto-Preview` or `syntax-lint` plugin causing it on very rough guess.

**Comment by shobhitsharma** [comment]
@aeschli Possible to hook some case-sensitive matching to the core lib to prevent that in future?

**Comment by lordfpx** [comment]
It looks like that issue was closed a little too early isn't it ?

**Comment by leomeloxp** [comment]
I couldn't find exactly why, but I also had *PUG* and Pug available as syntax options for me. A quick grep on my extension folders brought my attention to [this](https://marketplace.visualstudio.com/items?itemName=searKing.preview-vscode) module, which when I disabled it, the broken *PUG* language entry disappeared.

Hope it helps 😃
