### ISSUE TITLE
--allowUnreachableCode in tsconfig.json breaks in editor

### ISSUE THREAD

**Issue by httpete** [Microsoft/vscode#3428]
I upgraded to 1.8.2. My VScode starting getting red underlines all over after I added the allowUnreachableCode option in the tsconfig. If I remove and restart, it works fine.

**Comment by joaomoreno** [comment]
I cannot reproduce this, can you provide an example where you see this happening? Or maybe some screenshots? What error message did the red underlines tell you?

**Comment by httpete** [comment]
![it_does](https://cloud.githubusercontent.com/assets/1200635/13324661/a58324ac-dbac-11e5-82f0-e8d5cce0e0a2.png)
![if_i_add](https://cloud.githubusercontent.com/assets/1200635/13324662/a5f8029a-dbac-11e5-9f34-2d17f46efcbe.png)

**Comment by joaomoreno** [comment]
Thanks. Can you give me the entire error? All I see is `cannot export without module fla...`.

**Comment by httpete** [comment]
It is as if the tsconfig.json isn't there. It is picking up none of my tsconfig optins.

**Comment by egamma** [comment]
Currently changes to tsconfig.json require to run the  'reload typescript' command. Unhappy, but we work on improving this.

**Comment by httpete** [comment]
I find the only dis is to remove the line from tsconfig and reboot vscode. Then the red goes away.

**Comment by dbaeumer** [comment]
I can't reproduce this. @httpete can you share your project ?


![capture](https://cloud.githubusercontent.com/assets/1931590/13396092/fef4f440-def2-11e5-82e2-f16c7ea76d88.png)

**Comment by httpete** [comment]
With the latest 0.10.10 VSC and TS 1.8.7 I don't see this anymore. Thanks!
