### ISSUE TITLE
Changing tab clears the "Search keybindings" field and lists all shortcuts

### ISSUE THREAD

**Issue by GrantSolar** [Microsoft/vscode#34281]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.1

---

1. Open the Keyboard Shortcuts tab
2. Enter text to search on
3. Change to a different tab
4. Return to Keyboard Shortcuts tab. Default listing of all keybindings is shown

**Comment by sandy081** [comment]
Duplicates #23543
