### ISSUE TITLE
Slow configuration model merging

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34282]
We have seen a slowdown in startup performance with 1.16. The profiler shows that are spending much more time in `array.forEach` which we could eventually track back to being called ~10000 times from object clone which is often called from the configuration model merging. 

Individual calls are usually sub millisecond but this is death by thousand paper cuts... Apply the attached patch and see output like below

[patch.txt](https://github.com/Microsoft/vscode/files/1298980/patch.txt)

<img width="1113" alt="screen shot 2017-09-13 at 11 44 04" src="https://user-images.githubusercontent.com/1794099/30370865-231d2be4-9879-11e7-95eb-43546e534bd2.png">

**Comment by jrieken** [comment]
FYI - I just pushed https://github.com/Microsoft/vscode/commit/8c8b46f8335ccc56ee110231b76ab5a60d213cc5 because `getConfigurationValue` is really hit by clone. Obviously it's always faster to cache a value but the difference is around 40ms (when showing a full explorer, ~50items)

[FileRenderer-renderElement-faster.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1438053/FileRenderer-renderElement-faster.cpuprofile.txt)
[FileRenderer-renderElement-slow.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1438054/FileRenderer-renderElement-slow.cpuprofile.txt)

**Comment by sandy081** [comment]
@jrieken Why not using [getValue](https://github.com/microsoft/vscode/blob/master/src/vs/platform/configuration/common/configuration.ts#L65) API which is more efficient for your case?

**Comment by jrieken** [comment]
It somehow simpler when something like [`IFilesConfiguration`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/files.ts#L64) already exists. It makes you use less strings and more typed objects...

**Comment by sandy081** [comment]
@jrieken I agree with your argument if you are depending on the entire section, for e.,g `explorer`. But, I see you are using only `explorer.decorations`. Is not it better if you listen to `explorer.decorations` changes and cache the value of `explorer.decorations` ?

**Comment by sandy081** [comment]
Object cloning is reduce enormously and is being used smartly. Here is the new picture of time taken for `clone`.

![image](https://user-images.githubusercontent.com/10746682/32618989-9fa4258c-c579-11e7-9ea9-f3492fbcfafe.png)
