### ISSUE TITLE
Terminal lines are being duplicated after resizing panel

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#34280]
1. Open terminal, run `ipython`, and input
```python
if True:
    print('bu')
    print('fan')
```
2. Resize terminal to smallest size
3. Resize to normal size
LOOK! IT BECOMES LONGER!  

![ff](https://user-images.githubusercontent.com/9464825/30370331-dc553a5e-98a9-11e7-8f7f-6c249085471e.gif)

**Comment by Tyriar** [comment]
@innerlee can you share what OS this is and what version of VS Code you're using?

**Comment by innerlee** [comment]
Ubuntu 17.04
Vscode 1.16.0

**Comment by levani** [comment]
I'm also having some promlem with the terminal after resize. Please see the screencast below:

![vscode-terminal-resize](https://user-images.githubusercontent.com/184472/32663144-546f95a6-c646-11e7-90d5-c68429fc863f.gif)

I'm on windows 10 x64, vscode 1.18.0

**Comment by Tyriar** [comment]
Linux issue is minor and out of scope, for the Windows problem see https://github.com/Microsoft/vscode/issues/30429

**Comment by innerlee** [comment]
![bug vscode](https://user-images.githubusercontent.com/9464825/34068287-31e1b1f6-e273-11e7-8e5e-17d57ae1acf4.gif)
