### ISSUE TITLE
tab content coverd by debug panel

### ISSUE THREAD

**Issue by lufengd3** [Microsoft/vscode#34297]
- VSCode Version: 1.16.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. drag the tab which coverd by debug panel in debug mod, still coverd by the panel

![image](https://user-images.githubusercontent.com/5675408/30380971-adbd266a-98cd-11e7-9aad-2fb44b605314.png)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2513
