### ISSUE TITLE
Extract Function Uses Wrong Indentation

### ISSUE THREAD

**Issue by ambroselittle** [Microsoft/vscode#34291]
- VSCode Version: 1.16.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

Config info that might apply:
Project is using the Prettier plugin, which has a default tab size of 2. 
I have set `"editor.tabSize": 2` in my workspace settings. I also tried setting it in user settings, but same results.

1. Create a new test.ts file with these contents:
```javascript
export class TestClass {
  private thing1 = true;
  private thing2 = false;

  public doSomething = () => {
    this.thing1 = !this.thing2;
    this.thing2 = !this.thing1;
  };
}
```
2. Highlight the two lines in doSomething and use the new (rad) extract function capability. (I was using the keyboard, FWIW.)

Actual:
```javascript
export class TestClass {
  private thing1 = true;
  private thing2 = false;

  public doSomething = () => {
      this.newFunction();
  };

    private newFunction() {
        this.thing1 = !this.thing2;
        this.thing2 = !this.thing1;
    }
}
```

Note the extra indent for both the newFunction and the call to new function.

Expected:
```javascript
export class TestClass {
  private thing1 = true;
  private thing2 = false;

  public doSomething = () => {
    this.newFunction();
  };

  private newFunction() {
    this.thing1 = !this.thing2;
    this.thing2 = !this.thing1;
  }
}
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/18328

Closing as upstream
