### ISSUE TITLE
Integrated terminal font rendering doesn't look good in Insiders 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#34294]
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0
- Display: Thunderbolt display (non retina)

left: Stable, right: Insiders

![2017-09-13_15-30-49](https://user-images.githubusercontent.com/1898161/30380079-df58a062-9898-11e7-8cd8-9413fbe17f55.png)

I'm using these font related settings:

```
	"editor.fontFamily": "FiraCode-Retina",
	"editor.fontSize": 13,
	"editor.fontLigatures": true,
```

**Comment by Tyriar** [comment]
A change related to letter spacing landed last night, it looks like you're on an older build.

As for how it's a little more blurry, that's covered in https://github.com/Microsoft/vscode/issues/34119

**Comment by Tyriar** [comment]
See https://github.com/sourcelair/xterm.js/pull/980 for letter spacing change
