### ISSUE TITLE
Revisit usages of Uri#file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34296]
For remote-resource support we need to be revisit our `Uri#file`-usage because not everything is a file anymore. Often code like this is encountered 

```ts
👎 URI.file(join(sourceUri.fsPath, yetAnotherPath)) 
``` 
which unfortunately steals everything else from the "source" uri, like scheme, fragment and query. The way such conversions should be is: 

```ts
👍 source.with({ path: join(source.path, yetAnotherPath) })
```

I have done an initial scan and places we should check are

* [x] vs/workbench/parts/execution/electron-browser/execution.contribution.ts#L194
* [x] vs/workbench/parts/files/browser/fileActions.ts#L309
* [x] vs/workbench/parts/files/browser/views/explorerView.ts#L454
* [x] vs/workbench/parts/files/common/editors/fileEditorTracker.ts#L209
* [x] vs/workbench/parts/output/common/outputLinkComputer.ts#L73
* [x] vs/workbench/parts/search/browser/searchActions.ts#L379
* [x] vs/workbench/parts/search/common/queryBuilder.ts#L198
* [x] vs/workbench/services/editor/browser/editorService.ts#L236
* [x] vs/workbench/services/telemetry/common/workspaceStats.ts#L230
* [x] vs/workbench/services/textfile/common/textFileService.ts#L454
* [x] vs/base/browser/dnd.ts#L71
* [x] vs/base/common/labels.ts#L37

**Comment by bpasero** [comment]
On top of that we should scan where raw file paths travel to other processes and not using URI. There can be cases where we still just send over paths and we never use URI at all but just go to node directly. These are probably harder to find but also less surface to check.

**Comment by bpasero** [comment]
* `vs/base/common/labels.ts#L37`: fair use, if a path is passed in as string, assume it is a file path
* `vs/base/browser/dnd.ts#L71`: fair use, external files dropped can only be local files
* `vs/workbench/services/textfile/common/textFileService.ts#L454`: fair use, the path comes from a native file dialog
* `vs/workbench/services/telemetry/common/workspaceStats.ts#L230`: fair use, files to open from outside are currently always files (e.g. from command line, native dialog)
* `vs/workbench/services/editor/browser/editorService.ts#L236` I would argue, also a fair use. this is when you create an untitled file with an associated file path. 
* `vs/workbench/parts/output/common/outputLinkComputer.ts#L73` fair use, the file patterns for detecting links are all for file on disk paths

Adding @roblourens for search.

@jrieken it seems to me we need a similar issue for use of `URI.fsPath` which is most likely much worse to deal with. If we now start to create non-file URIs that get passed around, `URI.fsPath` is bogus in most cases. To give one example, [hot-exit is hashing dirty editors](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupFileService.ts#L220) based on the `fsPath` property. So you could easily end up with collisions. The fix there is quite easy to use the `URI.toString()` instead, but we need to check each use.

**Comment by jrieken** [comment]
Good point. The `fsPath`-property should only be used when trying to read something from disk.

**Comment by isidorn** [comment]
I removed the leftover usages of uri.file via cb576b0a4c and d089cc7e2e
queryBuilder I did not touch, leaving that to @roblourens

**Comment by jrieken** [comment]
ping @roblourens

**Comment by roblourens** [comment]
One remaining in querybuild, ok because for now I will only support searching local resources with an absolute path in `files to include`
