### ISSUE TITLE
Running from source, missing dependency 'run-in-terminal'

### ISSUE THREAD

**Issue by DerTolleEmil** [Microsoft/vscode#343]
It seems like vscode is depending on npm module 'run-in-terminal' which does not get installed by running `scripts\npm install`. There is nothing mentioned in the package.json file in the root dir (it is, however, listed as a dependency in package.json in extensions\csharp-o). `gulp watch` shows one error in `extensions\csharp-o\src\features`, line 13 reads `import {runInTerminal} from 'run-in-terminal';`

Running `npm install run-in-terminal` manually fixes this.

Edit: Might somehow be connected with #321? I rarely use npm/gulp and I am far from an expert when it comes to dependencies etc.

**Comment by joaomoreno** [comment]
@jrieken 

I cannot reproduce this. Please try the following steps:

```
git clean -xfd .
.\scripts\npm install
```

This should populate `extensions\csharp-o\node_modules` including the `run-in-terminal` dependency. Please reopen if you don't see that behavior.
