### ISSUE TITLE
Colour Picker available in other file types.

### ISSUE THREAD

**Issue by devallish** [Microsoft/vscode#34308]
- VSCode Version: 1.17.0-insider
- OS Version: Windows 10

Could we have the new colour picker available for other file types. 
Vuejs template files .vue have <style> section and it would be useful to use the picker here. I am not sure if other libraries have this.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/374

**Comment by romines** [comment]
Is there a reason this was closed?
