### ISSUE TITLE
Improve JavaScript language service prompt

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3430]
Testing #3170 

I have the same issue with the JavaScript infrastructure message as with the OmniSharp extension prompt (#2748). It is easy to miss this prompt and I have to be in the mood to want to read the release notes.

Suggest a similar behavior in #2748:

Message: "Our JavaScript support has been enhanced, would you like to view the Release Notes?"

Options:

* **Yes**: Open release notes, set flag to never show prompt again
* **No**: Do not open release notes, set flag to never show prompt again
* **Later**: Do not open release notes, show message next time we open a workspace with JavaScript artifacts

If I press Cmd+Q or ESC we should not set the flag. It should only be set if I choose Yes or No.

**Comment by joaomoreno** [comment]
Unfortunately our API doesn't let us hide the `Close` button. So, `Close` will behave as you describe `Later` to behave. This seems fine for me. Here's how it looks:

![image](https://cloud.githubusercontent.com/assets/22350/13315876/a3719d5a-dbad-11e5-980d-4871bf561add.png)

**Comment by chrisdias** [comment]
ok

**Comment by chrisdias** [comment]
@joaomoreno It looks like we do allow for overriding the "Close" button??? 

When I am prompted to install the C# Extension I get Yes/No/Later:

![image](https://cloud.githubusercontent.com/assets/1487073/13381942/e106e810-de68-11e5-8830-17a0f1f08245.png)

But for JavaScript I have Yes/No/Close: 

![image](https://cloud.githubusercontent.com/assets/1487073/13381930/a32ec5e4-de68-11e5-8b8e-9b3924a942f6.png)

I would like to be consistent here and I think "Later" does a better job describing what will happen.

**Comment by joaomoreno** [comment]
Because one is through our internal message service, the other through our API, which I found to be more limiting, e.g., not allowing me to omit the Close.

Correct me if I'm wrong, @jrieken @bpasero

**Comment by bpasero** [comment]
I think you have the same control over actions both for internal and API use.

**Comment by joaomoreno** [comment]
Docs are:

```
/**
 * Show an information message to users. Optionally provide an array of items which will be presented as
 * clickable buttons.
 *
 * @param message The message to show.
 * @param items A set of items that will be rendered as actions in the message.
 * @return A thenable that resolves to the selected item or `undefined` when being dismissed.
 */
export function showInformationMessage(message: string, ...items: string[]): Thenable<string>;
```

I call it with

```
vscode.window.showInformationMessage(
	'Our JavaScript support has been enhanced, would you like to view the Release Notes?',
	'No',
	'Yes'
)
```

And I get the `Cancel` button.

**Comment by joaomoreno** [comment]
Yep: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostMessageService.ts#L60
