### ISSUE TITLE
Navigating away and back to diff editor resets the scrollbar position

### ISSUE THREAD

**Issue by rylancates** [Microsoft/vscode#34300]
- VSCode Version: 1.16
- OS Version: KDE Arch Kernel v4.12

Steps to Reproduce:
1. Open up a working tree view of a file you have made changes to in a git repository
2. Scroll to a place you'd like to reference continually in working tree file
3. Switch tabs to another open file
4. Switch back to the working tree tab from before, note that you are teleported to the first diff present in the file and away from the location you wish to reference

Reproduces without extensions: Yes

**Comment by rylancates** [comment]
Desired functionality would be to remember the scrollbar position and require user interaction to navigate forward and backward though diff positions etc.

**Comment by joaomoreno** [comment]
@bpasero Not sure if this is in your editor layer, or further down.
