### ISSUE TITLE
Blurred terminal fonts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34302]
I see that the terminal fonts turned a bit blurry after the canvas adoption:

![image](https://user-images.githubusercontent.com/22350/30384923-e18c8fe4-98a5-11e7-812c-4001a025f366.png)

This is using native resolution, no hdpi:

![image](https://user-images.githubusercontent.com/22350/30384927-e36fb52a-98a5-11e7-8036-0bc2bf19af78.png)

**Comment by joaomoreno** [comment]
It seems to be due to the lack of sub-pixel antialiasing:

![image](https://user-images.githubusercontent.com/22350/30385354-2f737424-98a7-11e7-9dbd-b74fc21248d5.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34119
