### ISSUE TITLE
Auto close JSX tags.

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#34307]
- VSCode Version: 1.16.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create JSX content, ie `<div></div>`
2. Closing `</div>` does not auto-insert when you close the opening tag

This is a feature request to make the awesome auto-closing-tag feature work with JSX, instead of just html.

**Comment by Igorbek** [comment]
I would add that it is desirable that it would work with components as well.

- Type `<C`
- auto-completion shows options where the user selects `Component` and press _tab_
- it is expanded to `<Component></Component>`

**Comment by bsvipas** [comment]
@Igorbek it doesn't work for me, auto close tags works in HTML, Handlebars, etc., but not in .js file with JSX syntax.

**Comment by Igorbek** [comment]
It doesn't for me either :) I extended the feature request. That is what I want.

**Comment by bsvipas** [comment]
@Igorbek Oh sorry, I misread your comment 😄

**Comment by Igorbek** [comment]
no worries, just upvote the feature if you're interested.

**Comment by priley86** [comment]
+1

**Comment by quarleswn** [comment]
How is it 2018 already and this has still not yet been implemented? Atom has had this forever.

**Comment by joshua-turner** [comment]
@quarleswn I would avoid that extension, it causes errors with eslint and produces intense CPU spikes. It's likely there's some infinite recursion happening somewhere in there.

It's detailed here: https://github.com/formulahendry/vscode-auto-close-tag/issues/70

**Comment by GregCMills** [comment]
Guys, note that while typing:
   '<div>'
will not autoclose the jsx tag, if your filetype is set to 'JavaScript React' typing:
   'div'
will output (after tab):
    '<div></div>' and place your cursor in the middle.

**Comment by GregCMills** [comment]
Note that the feature described here: https://github.com/Microsoft/vscode/issues/18427
does a lot of what you're looking for I think.

**Comment by PolGuixe** [comment]
Any working solution?

**Comment by gor918** [comment]
@PolGuixe As long as the language mode is "Javascript React", it should work
<img width="395" alt="123" src="https://user-images.githubusercontent.com/11815472/37863873-3490eea4-2f7f-11e8-82aa-ae2a362c2809.png">

**Comment by chuckmasucci** [comment]
It's not working as TypeScript React

**Comment by bastienGranger** [comment]
+1 it does not work for .tsx files. Auto-closing tags works on html native tags but not on custom and React Native tags

**Comment by orszaczky** [comment]
@gor918 Even with "Javascript React" it's not auto-closing the tags

**Comment by daphnegold** [comment]
+1

I am also having this problem with JavaScript React as the language mode.

**Comment by cmacdonnacha** [comment]
@daphnegold , thanks! I was pulling my hair out trying to figure out why `<div>` would not generate a closing tag. I then tried just `div `and it worked. I would suggest that even when using  `<div>` it should still auto close the tag.

**Comment by bammoo** [comment]
Do consider self-close tag pls!

**Comment by theapache64** [comment]
I've created a small snippet

```
{
	"Auto close tag": {
		"prefix": "tag",
		"body": [
			"<$1>",
			"</$1>"
		]
	}
}
```
Type `tag` and then type your `Component` name, you'll see the magic. (y)

**Comment by IllusionMH** [comment]
Yep, works for me in VS Code Insider after installing `typescript@next` as [described here](https://basarat.gitbooks.io/typescript/content/docs/getting-started.html#typescript-version)

However there is noticeable delay after typing `>` (in `<div>`) and when `</div>` appear, in comparison with simple HTML page or new project created with CRA.
And doesn't close `<div>` if entered in

```
<div>
    <div> <- doesn't close here
</div>
```

@mjbvz should I create separate issue for this delay issue if it depends on project size?

**Comment by mjbvz** [comment]
Yes this requires TS 3.0+ which is enabled on VS Code insiders. Please open new issues for any problems you see. 

@IllusionMH This issue is tracked by https://github.com/Microsoft/TypeScript/issues/25552

**Comment by andrewriveraj** [comment]
Solution is : CTRL + SHIFT + P then type and select "Change Language Mode". Enter javascriptreat

**Comment by SurrealShock** [comment]
Adding this to my user settings fixed it for me:
`"emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },`
