### ISSUE TITLE
Conditional exclude is not respected by text search

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#34306]
With this in `settings.json`
```json
"files.exclude": {
    "**/*.js": {
      "when": "$(basename).ts"
    }
  },
```
which excludes *.js nera *.ts from file tree in explorer, text SEARCH (via right pane) doesn't search in *.js files at all:
![image](https://user-images.githubusercontent.com/736697/30388539-73fa6fae-98c9-11e7-8727-2f0ffe406bfb.png)

if remove this setting:
![image](https://user-images.githubusercontent.com/736697/30388555-7edd4108-98c9-11e7-81fc-cd73462ed045.png)

**Comment by roblourens** [comment]
I believe this was fixed, let me know if it reproes in the latest.
