### ISSUE TITLE
Allow a project to be tracked with only one SCM provider.

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode#34313]
I just upgraded to VSCode 1.16.0, and now the SCM badge is showing 99+ even though all my changes have been committed.

I assume this is happening because I have the Hg SCM Provider (v1.1.7) installed, and as far as Hg is concerned, all the files in my project are untracked. Since my project is only using Git, however, I have no desire to track it with Hg, and I would like the badge to only show the count of files untracked/uncommitted in Git (not Hg).

I'm not sure if this is an issue with VSCode or the SCM provider. Please let me know if it's the latter, and I'll file a request with that project.

**Comment by devuxer** [comment]
For the moment, I was able to solve this by placing the following in my workspace settings:

```
{
    "hg.countBadge": "off"
}
```

**Comment by joaomoreno** [comment]
Yes, it seems the Mercurial extension needs to correctly adopt multirepo scm. Disabling it for now seems to be the only workaround.

**Comment by devuxer** [comment]
Thanks, @joaomoreno. Just filed an [issue](https://github.com/mrcrowl/vscode-hg/issues/26) for vscode-hg.
