### ISSUE TITLE
Program does not recognize php closing tag if there is an open bracket.

### ISSUE THREAD

**Issue by maldetquest** [Microsoft/vscode#34318]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ftp-sync|luk|0.3.3

---

Steps to Reproduce:

1.  Open and Save new PHP file
2.  Open php tag and open an if statement but do not close if statement bracket and then close the php tag `<?php if(test){ ?>`
3. VSCode will not recognize that the php tags are closed because of the open bracket. Before the most recent update, this was not an issue.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Indeed, this is https://github.com/Microsoft/vscode/issues/34204
