### ISSUE TITLE
Code completion (intellisense) in new Files

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#34317]
- VSCode Version: 1.16
- OS Version: Windows 10

Steps to Reproduce:

1. Install [Python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension from market place
2. Open a workspace
3. Create a new file (*do not save*)
4. Change language of file to Python
5. Start typing code, and there's no intellisense

FYI - I am fairly certain this used to work in an older version.
I've debugged this and the the ```provideCompletionItems``` method of the class implementing ```vscode.CompletionItemProvider``` is not being hit. 

Related https://github.com/DonJayamanne/pythonVSCode/issues/1194

**Comment by mjbvz** [comment]
Looks like the python extension either hasn't been activated or failed to activate? Do you see the same error  in the developer console as the user in the other user reported?

**Comment by DonJayamanne** [comment]
The extension has activated without any errors. I say this because I can switch to a file on disk in the same VS Code instance (i.e. switch between tabs) and it works as expected.

As for errors in the console window, this is all I can see:
```
Ctrl+Alt+ keybindings should not be used by default under Windows.
[Extension Host] vscode-icons is active!
```

**Comment by mjbvz** [comment]
Ok,  I took a quick look through the ext source. Looks like you only register for the scheme:

```js
const PYTHON: vscode.DocumentFilter = { language: 'python', scheme: 'file' };
```

If you do support unsaved filed, try omitting the `scheme` part of this

**Comment by DonJayamanne** [comment]
Great thanks.
