### ISSUE TITLE
VSCode won't update after restarting

### ISSUE THREAD

**Issue by David-EP** [Microsoft/vscode#34310]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
vscode-markdownlint|Dav|0.10.1
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
lorem-ipsum|Tyr|1.0.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
vagrant|bbe|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
jquerysnippets|don|0.0.1
gitlens|eam|5.0.0
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.23.1
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.0
vscode-firefox-debug|hbe|0.16.0
openchrome|hua|0.0.3
rest-client|hum|0.15.2
docthis|joe|0.4.8
quickstart|lol|0.1.0
vs-cron|mkl|1.5.1
vs-deploy|mkl|9.32.3
vs-remote-debugger|mkl|1.9.9
vs-rest-api|mkl|1.18.2
vs-script-commands|mkl|4.14.0
vs-swiss-army-knife|mkl|1.0.3
atom-keybindings|ms-|3.0.1
debugger-for-chrome|msj|3.2.1
createGUID|nwa|0.0.2
vscode-icons|rob|7.12.0
open-in-browser|tec|1.1.0
bootstrap4-vscode|the|2.4.0
vscode-todo-highlight|way|0.5.11

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by David-EP** [comment]
I disabled all extensions and problem persists. VSC closes, reopens and moments later I get the indicator telling me to restart to update. I downloaded new version, as you see above, so now I have both 1.15 and 1.16.  This can't be good, right? Should I delete 1.15? Won't this leave all kinds of fragments I should remove? Thank you!

**Comment by joaomoreno** [comment]
Yeah completely remove all versions and redownload the latest from our site.

There is currently an issue with macos updating: https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
