### ISSUE TITLE
Code.exe still running after uninstall, reinstall unsuccessfull.

### ISSUE THREAD

**Issue by Oscar-21** [Microsoft/vscode#34312]
I tried to update VS Code and it failed, then VS Code would not even start. I uninstalled VS Code and downloaded the installer.

This error occurs during install.
<img width="357" alt="untitled picture" src="https://user-images.githubusercontent.com/21151259/30391303-daf5980c-9886-11e7-89b9-a8a9a7210400.png">

Even though it was "successfully" uninstalled task manager shows this:
<img width="585" alt="uss" src="https://user-images.githubusercontent.com/21151259/30391438-5479b726-9887-11e7-8a74-9357d0ffd035.png">

**Comment by alexandrudima** [comment]
I have also noticed something similar once on my Windows machine. I think @dbaeumer noticed it too. The process Code.exe goes to consume very little memory (16K) and it then cannot be killed via Task Manager. The only way I could get myself out of that state was to restart Windows.

**Comment by joaomoreno** [comment]
@alexandrudima Isn't this the Electron issue you investigated?

**Comment by alexandrudima** [comment]
@joaomoreno That is where it happened, but that was due to Electron crashing every time. 

The screenshot shows the icon for Code.exe stable, so it could not have had the same root cause.

**Comment by joaomoreno** [comment]
Not sure what I can do here. @bpasero have you seen this?

**Comment by bpasero** [comment]
No, not so far.
