### ISSUE TITLE
Very often the program is turned off when working in angular 4

### ISSUE THREAD

**Issue by Razor164** [Microsoft/vscode#34311]
Very often the program is turned off when working in angular 4. The last update is not very like!

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.2
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.4
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
vscode-simple-icons|Lau|1.6.0
easy-less|mrc|1.4.5
vscode-docker|Pet|0.0.16
material-icon-theme|PKi|2.2.1
rxjs-snippets|pko|0.0.2
tsimporter|pmn|1.2.14
seti-icons|qin|0.1.3
sass-indented|rob|1.4.1
vscode-angular-support|vis|0.1.4
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
I don't understand what the issue is. Can you please provide some more information about the problem? Please include some steps to reproduce the issue and some screenshots of what is going wrong

**Comment by Razor164** [comment]
![image](https://user-images.githubusercontent.com/26738019/30436780-b2c56f48-9975-11e7-9a7f-696c0ef3e8d3.png)

**Comment by Razor164** [comment]
After the program is updated when the project is saved to angular, it appears. the pattern of appearance is not revealed. My colleagues faced such a problem.

**Comment by mjbvz** [comment]
Does this reproduce if you disable all extensions? You can do this by running the `disable all extensions command` in VSCode

Also can you please post the text of that error or temperately switch the editor language to english
