### ISSUE TITLE
Syntax highlight has stopped working when mixing php and html

### ISSUE THREAD

**Issue by CounterCoding** [Microsoft/vscode#34325]
- VSCode Version:  1.16.0
- OS Version: Windows 10 Home Single Language Version 1703

Steps to Reproduce:

1. Change the file extension to .php
2. Open the file.
[test.txt](https://github.com/Microsoft/vscode/files/1300902/test.txt)

![captura](https://user-images.githubusercontent.com/20713139/30400239-9ffa9f74-98ac-11e7-832d-10e7252d6b7f.PNG)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/34204, and will be fixed in tomorrow's insiders build.
