### ISSUE TITLE
Terminal font squished in retina display

### ISSUE THREAD

**Issue by knownasilya** [Microsoft/vscode#34320]
- VSCode Version: Code - Insiders 1.17.0-insider (06529dbcacb796d59e7fc2ca0ac5dbe7c29c099e, 2017-09-13T05:32:25.862Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
dart-code|Dan|2.4.0
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.1
vscode-docker|Pet|0.0.16
lorem-ipsum|Tyr|1.0.0
quokka-vscode|Wal|1.0.63
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
workbench|and|0.1.6
typings-installer|ben|0.2.0
npm-intellisense|chr|1.3.0
vsc-ember-frost|cie|0.0.2
vscode-eslint|dba|1.3.1
githistory|don|0.2.3
tslint|eg2|1.0.4
vscode-npm-script|eg2|0.2.1
vscode-ember|emb|0.1.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.2.1
stylelint|shi|0.29.0
ayu|tea|0.6.0
vim|vsc|0.10.0

---

Steps to Reproduce:

1. Open terminal in a non-retina monitor
2. Drag vscode to retina monitor
3. Click expand on the terminal panel
4. Terminal font is super tiny and impossible to read
5. Move back to non-retina monitor and collapse, it's back to normal

Also the fonts are fuzzy on both monitors, only in the terminal.

![terminal](https://user-images.githubusercontent.com/34726/30395779-5e344b74-9895-11e7-817d-f9ad266ebfef.gif)

**Comment by Tyriar** [comment]
May need to use the [`'display-metrics-changed'`](https://github.com/electron/electron/blob/master/docs/api/screen.md#event-display-metrics-changed) event from Electron to detect DPI changes when dragging the window, I was expecting window.onresize to fire but it doesn't.

**Comment by Tyriar** [comment]
Could also include the target d`evicePixelRatio` with the `CharAtlas` and verify that before drawing.

**Comment by Tyriar** [comment]
Created the upstream issue https://github.com/xtermjs/xterm.js/issues/1118

**Comment by Tyriar** [comment]
Created the upstream issue https://github.com/xtermjs/xterm.js/issues/1118

**Comment by realappie** [comment]
Very frustrating bug, resizing the terminal seems to fix it.
