### ISSUE TITLE
keep prev. search string

### ISSUE THREAD

**Issue by kostyamy** [Microsoft/vscode#34326]
I hope there is already existing case on such simple issue/feature

is it possible to add a drop down with list of previously completed search strings 
sometime search strings are quite lengthy and i hate simply to lose it and being forced to retype it.
as a workaround i have Notepad++ open on a side with all my searches and it just odd situation.
Pretty much any test editor out there has such feature as built-in option.

Thanks,

- VSCode Version: 1.16.0
- OS Version: Windows 10
- Shell 1.7.3
- Renderer 58.0.3029.110
- Node: 7.9.0
- Arch: x64
- Hardware: Surface Pro 3

Steps to Reproduce:
1. open any text file
2. click Ctrl+F, type in string to find, Close / ESC
3. keep editing the file
4. open another tab to edit
5. click Ctrl+F, last search is gone and string to find now populated with current word from the second tab.

Suggestion: in step 5 i would like to have a drop down so i can select from history of prev. completed searches.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You can use alt+up/down to get earlier search strings :)

**Comment by kostyamy** [comment]
Or as you have suggested i can simply do Alt+Up/Down :-)
Thank you!
