### ISSUE TITLE
Shouldn't be possible to open the same file with different case

### ISSUE THREAD

**Issue by Madd0g** [Microsoft/vscode#34322]
VSCode Version: 1.16.0
OS Version: OSX 10.11

Steps to Reproduce:

1. Turn off preview, not sure if this is needed ("workbench.editor.enablePreviewFromQuickOpen")
2. Create file Maddog.ts
3. Rename it to maddog.ts
4. VSCode still allows to open and change both, while only one exists and **updates** when you change either file.

This is also causing havoc with typescript, can't really put my finger on what happens, feels like VSCode thinks they're both one file but TypeScript thinks they're different.

Thanks

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
