### ISSUE TITLE
JSDoc @constructor shows up in IntelliSense

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3432]
related to #3186?

Testing #3170 and the `@ constructor` JSDoc comment text shows up in the IntelliSense prompt. 

``` javascript
/**
 * Represents a person
 * @constructor
 * @param {string} name The name of the person
 * @param {number} age The age of the person
 */
function Person(name, age) {
    this.name = name;
    this.age = age;
}
var p = new Person
```

![image](https://cloud.githubusercontent.com/assets/1487073/13303539/e652f9e2-db04-11e5-9ce8-beff0eda5216.png)

![image](https://cloud.githubusercontent.com/assets/1487073/13303493/a0b9951c-db04-11e5-8a87-305d4aba60a8.png)

**Comment by joaomoreno** [comment]
It is up to each language service to parse the comments and provide whatever they want to be rendered in the widget.

**Comment by egamma** [comment]
Moving to Salsa

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7243
