### ISSUE TITLE
I can't keep in Dock

### ISSUE THREAD

**Issue by SamShiyun** [Microsoft/vscode#34336]
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:10:59.101Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. I select option Keep in Dock
2.rebot MAC, it's show "?" in Dock

**Comment by SamShiyun** [comment]
it's show "Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information." error info when check for update. My application

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by SamShiyun** [comment]
Hi @bpasero ,  I am sorry that I don't understand what you mean . I get newest version , the  issue always exist. what detail info need I report?  Thanks!

**Comment by bpasero** [comment]
Still happening?
