### ISSUE TITLE
Seeking advice - is it ok to create a CompletionItem with a command that retriggers completion?

### ISSUE THREAD

**Issue by tintoy** [Microsoft/vscode#34335]
Hi.

In my language service, I have some completion items that re-trigger completion using an associated `Command` on the `CompletionItem` that is implemented by my extension.

https://github.com/tintoy/msbuild-project-tools-vscode/blob/a4288d06830b9563a87496ff5b3eee2e7fa6ab92/src/LanguageServer.Engine/CompletionProviders/ItemMetadataExpressionCompletion.cs#L288-L298

Completion can be 2-phase in this context; I provide a list of completions and, if one of a subset of those completions is selected, then I re-trigger completion to provide the second piece of required information.

The extension itself does 2 things:

1. Watches for certain 2-character combinations, and triggers completion if they are found (auto-closing pairs in the language configuration does not seem to reliably support a multi-character opening).  
    https://github.com/tintoy/msbuild-project-tools-vscode/blob/a4288d06830b9563a87496ff5b3eee2e7fa6ab92/src/extension/extension.ts#L327-L336
2. Implements a command to move the cursor and trigger completion.  
    https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/src/extension/internal-commands.ts#L24-L37

It seems OK to me, but it does feel as if I'm working around the way this was intended to be used; I'd just like to confirm that it is not considered being a bad citizen, extension-wise (e.g. bad for performance, etc). This functionality is only enabled when using a custom language defined by my extension, not any of the built-in ones, if that makes any difference.

**Comment by jrieken** [comment]
Yes and no. So, generally yes but you should use the command that does it. Unfortunately, [this bug](https://github.com/Microsoft/vscode/issues/34565) prevents you from do it right now... However, this is about *re*triggering completions and I believe you want to trigger completions after auto-completing/closing a certain sequence. For us that's OK, if that's also OK for your user everything is good ;-)

**Comment by tintoy** [comment]
Cheers :)
