### ISSUE TITLE
Column select doesn't to account for wrapped lines

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#34331]
- VSCode Version: Code - Insiders 1.17.0-insider (06529dbcacb796d59e7fc2ca0ac5dbe7c29c099e, 2017-09-13T09:50:23.560Z)
- OS Version: Windows_NT x64 10.0.16281
---

Steps to Reproduce:

1. Open a markdown file with lines long enough to wrap
2. Column select at the beginning of the lines
3. :bug: Cursors are added to the point where lines are wrapped

This is reproducible on 1.16 too.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Multi-cursor navigation is implemented on the wrapped (view) lines. AFAIK this is consistent with what other editors do.

**Comment by Fania** [comment]
I've mentioned this in #5402 a while ago. I don't think that has been resolved yet.
