### ISSUE TITLE
Files explorer : *Properties* command in the context menu

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#3433]
How about a _Properties_ item / command in the file explorer ? 
I often want to look at my files properties, mainly the size.
If this is not possible, maybe just add a tooltip to show some useful properties.

**Comment by Tyriar** [comment]
My thinking is that we'd probably want to stay away from this as users can open the file in the OS's file explorer or terminal which both support this.

**Comment by Nimzozo** [comment]
This is  understandable, I wanted to win 1 click :smile: . 
Maybe the tooltip idea is not bad though.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
