### ISSUE TITLE
Add some sort of warning when file has changed from outside

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#34333]
I'm aware you guys (@stringham) pulled off something very needed in [this PR](https://github.com/Microsoft/vscode/pull/29655). Thank you for that.

Still, unless the file change is something huge, I find myself coming back to the editor after working somewhere else and going to modify an additional piece of data in that file, without realizing that the file has changed, potentially messing the 'new' file and/or unknowingly overwriting it.

There should be some warning or prompt (like in other editors) to make it clear that the data has been updated from the outside.

Now, thanks to that PR I can either go back and save somewhere else or review the new changes from the outside... I have options. But **only if I know** that file has been reloaded. As it is now is very sneaky and error prone IMHO.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14298
https://github.com/Microsoft/vscode/issues/20876
