### ISSUE TITLE
There's a lot of unused space to the right of the terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34332]
Column sizing must be off

![image](https://user-images.githubusercontent.com/2193314/30402801-d3a4be54-9893-11e7-98ce-ab3053feee33.png)

**Comment by yume-chan** [comment]
It's still not fixed in 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z).

I'm on Windows 10, 100% DPI, had reverted all settings and disabled all extensions.

**Comment by Tyriar** [comment]
I think this is mostly fixed, but it's still not fitting ideal. @yume-chan a screenshot like above using selection would be good showing your case.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/30891740-632c177e-a367-11e7-9dfc-2c829b3039dc.png)

I'm building Code from source, so I should have the latest fixes, but there is still lots of space on the right side.

**Comment by yume-chan** [comment]
I can verify it's now fixed.
