### ISSUE TITLE
Extension Development Host : No 'Save File' prompt on closing a modified file. 

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode#34334]
- VSCode Version: Code - Insiders 1.17.0-insider (2c385b98066eebb8e39dfd98b1fcb8cc254196b6, 2017-09-11T05:24:31.374Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|5.0.0
azure-account|ms-|0.1.2
debugger-for-chrome|msj|3.2.1

---

Steps to Reproduce:

1. Using Hello World, start debug mode. An Extension Development Host instance opens, with the VSCode home screen. 
2. Click on New File. Write something there, say, 'Lorem Ipsum'. 
3. Close the file (Ctrl+W). 

Expected : 
A system dialog prompt asking me if I want to save a file, warning me of unsaved changes. 
Result : 
File closes with no warning. 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
This is "as designed": we use the extension development host as target for automated tests (e.g. extension tests) which cannot handle modal dialogs. As such, please do not use this host for any productive development.
