### ISSUE TITLE
Tab give incorrect indentation on Go file.

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode#34347]
- VSCode Version: 1.16.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Write go code
```golang
package main

func main() {
    bus := event.NewBus()

    var events []event.Event

    bus.Subscribe(event.HandlerFunc(func(evt event.Event) {
        events = append(events, evt)
    }))

}
```
2. Press "tab" key will give incorrect indentation only on the line 11.
Result will be like:
```golang
package main

func main() {
    bus := event.NewBus()

    var events []event.Event

    bus.Subscribe(event.HandlerFunc(func(evt event.Event) {
        events = append(events, evt)
    }))
        |
}
```
While expecting:
```golang
package main

func main() {
    bus := event.NewBus()

    var events []event.Event

    bus.Subscribe(event.HandlerFunc(func(evt event.Event) {
        events = append(events, evt)
    }))
    |
}
```

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@uudashr What indentation setting is the editor configured with? Do you have any extensions installed that might want to take over the `tab` key ?

![image](https://user-images.githubusercontent.com/5047891/30417220-43047cd0-992f-11e7-8f86-b317778c6880.png)

![image](https://user-images.githubusercontent.com/5047891/30417230-4c472f90-992f-11e7-9845-4e84320e6984.png)

Does this reproduce when using `"editor.autoIndent": false` ?
