### ISSUE TITLE
Add feature to disable tabs in Panel

### ISSUE THREAD

**Issue by lomholdt** [Microsoft/vscode#34349]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
vscode-eslint|dba|1.3.1
php-intellisense|fel|1.5.1
phpcs|ika|0.7.0
php-docblocker|nei|1.2.0
vetur|oct|0.9.7
vscode-icons|rob|7.12.0
gitblame|wad|2.2.0

(1 theme extensions excluded)

---
The Panel is nice. But the "Tabs" PROBLEMS, OUTPUT etc. are huge. It would be awesome to be able to remove/hide it or at least decrease the font size. 

![skaermbillede 2017-09-12 kl 10 43 30](https://user-images.githubusercontent.com/1733744/30416685-75b9c4ac-992d-11e7-8804-c40ec7e9ad0e.png)

Steps to Reproduce:

1. Open the Panel (That's the one with the PROBLEMS/OUTPUT/DEBUG CONSOLE/TERMINAL)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This is a fair feature request. If more users ask for this we would be willing to accept PR
