### ISSUE TITLE
Have to reload vscode in order to pick up jsconfig.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3434]
Testing #3170 

I still need to reload the environment when i add a jsconfig.json file, even with Salsa.  

add `greeter.js`:

``` javascript
export function greetMe() {
   return 'hello';
}
```

add `app.js`:

``` javascript
var g = require('./greeter');
g.
```

result no intellisense on greeter.

![image](https://cloud.githubusercontent.com/assets/1487073/13304395/332b3014-db09-11e5-8707-e2e57f94f21e.png)

add a `jsconfig.json`:

``` javascript
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

* go back to `app.js`, try to bring up intellisense on `g` again, same result -> no intellisense.
* reload window
* open `app.js`, now we have intellisense:

![image](https://cloud.githubusercontent.com/assets/1487073/13304409/49c871ba-db09-11e5-88f4-e613a1b5343a.png)

**Comment by chrisdias** [comment]
related to #3417?

**Comment by joaomoreno** [comment]
Probably.

**Comment by chrisdias** [comment]
@joaomoreno @dbaeumer why not Feb2016? If we did, we don't need the "Reload TypeScript" and "Reload JavaScript" commands in #3417.

**Comment by joaomoreno** [comment]
Because there is no one confident enough of making this change and there is the `Reload` workaround. Marking it for March.

**Comment by dbaeumer** [comment]
I do :-).

Fixed. To be clear: we still need the reload project since there are cases where the tsserver can only recover from changes if you reload the project.

**Comment by dbaeumer** [comment]
@chrisdias pls verify.

**Comment by chrisdias** [comment]
looks good
