### ISSUE TITLE
Code higlighter is broken after update to 1.16.0

### ISSUE THREAD

**Issue by kutanari** [Microsoft/vscode#34343]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
numbered-bookmarks|ale|0.10.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
bracketselection|guo|1.0.3
vue-snippets|hol|0.1.4
ftp-simple|hum|0.5.6
phpcs|ika|0.7.0
Hg|jak|0.0.4
format-indent|Kas|1.3.0
laravel-blade|KTa|0.0.1
vue|liu|0.1.5
ecdc|mit|0.10.3
prettify-json|moh|0.0.3
sublime-keybindings|ms-|2.9.1
php-docblocker|nei|1.2.0
vetur|oct|0.9.7
laravel-blade|one|1.9.0
seti-icons|qin|0.1.3
sass-indented|rob|1.4.1
text-marker|ryu|0.10.0
bracket-jumper|sas|1.1.8
vue|sea|0.4.2
stylelint|shi|0.29.0
wordpress-snippet|tun|1.1.2
highlight-matching-tag|vin|0.4.4
better-align|wwm|1.1.6

(4 theme extensions excluded)

---

Steps to Reproduce:

1. When open file .php contain PHP code and HTML (standard wordpress theme file)
2. the code higligher is so messy, I use default theme by VS code.

Reproduces without extensions: Yes
![capture](https://user-images.githubusercontent.com/924723/30410811-7b84bf5e-9937-11e7-9c25-61a74eed8f7e.JPG)

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/34204 and it will be fixed in tomorrow's Insiders build if you want to try that out.
