### ISSUE TITLE
Access to language server in extension

### ISSUE THREAD

**Issue by atishay** [Microsoft/vscode#34344]
I want to write an extension for JS files. Is it possible to access the output of the language server like knowing if the given word is a variable.

**Comment by mjbvz** [comment]
We do not expose this currently. Existing plugins get around this by using their own version of TypeScript to parse files: https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts#L9

If you are writing an extension that augments JavaScript intellisense , consider creating a TypeScript server plugin instead: https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin This is the preferred approach to add new editor functionality to javascript files

Let me know if you have any questions about these options
