### ISSUE TITLE
vscode development - how to import a new npm module into vscode

### ISSUE THREAD

**Issue by cwtuan** [Microsoft/vscode#34346]
I'm developing a new feature to vscode itself. I want to use a  npm module(axios) in the source.

In the root of project,
```
npm install --save axios
```

Any in any typescript file of vscode, 
```
import * as axios from 'axios';
```
There's error: `[ts] Cannot find module 'axios'.`

But when I import other npm which is already in original vscode [package.json](https://github.com/Microsoft/vscode/blob/master/package.json#L47) such as `winreg`. Then,  the statement`import * as winreg from 'winreg';` doesn't show any error.

Question: How do I import a new npm module into vscode?

**Comment by mjbvz** [comment]
This seems like a bug when using `"moduleResolution": "classic"` as we do in VSCode. I've opened https://github.com/Microsoft/TypeScript/issues/18492 to track this. I'm tried putting together a workaround but was not able to come up with one. Someone on the TS team may have a better idea on what to do here

Closing as upstream

**Comment by mjbvz** [comment]
Hey @cwtuan, as a workaround try adding:

```
        "paths": {
            "axios": [
                "node_modules/axios/index.d.ts"
            ]
        }
```

to the `src/tsconfig.json`. I believe the alternative is to copy the `axios/index.d.ts` into `src/typings`

**Comment by cwtuan** [comment]
@mjbvz Does the workaround work for you?  I have tried to add path paths in `tsconfig.json` and  copy the axios/index.d.ts into src/typings. But nothing work for me.
