### ISSUE TITLE
feature req: multiple cursors till end offile

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#34345]
If we want to have multiple cursors then we have to use alt+ctrl+bottom or up key. It becomes tedius on a huge file. Could there be a shortcut to create multiple cursors till end of file?

**Comment by svenax** [comment]
One way of doing that is to create a normal selection to end-of file (ctrl+shift+down), then use Add cursors to line ends and move the cursors to where they should be.

**Comment by alexandrudima** [comment]
To the verifier, there are now two commands `editor.action.addCursorsToBottom` and `editor.action.addCursorsToTop` that implement the desired behaviour.
