### ISSUE TITLE
  error TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by cyl520134** [Microsoft/vscode#34340]
Executing task: tsc  -p "g:\WEB PRO\serve\tsconfig.json" <

error TS5042: Option 'project' cannot be mixed with source files on a command line.

**Comment by andrew-veresov** [comment]
Same here. Typescript version is 2.5.2

**Comment by alexandrudima** [comment]
@cyl520134 Are you using our task system or typing the command in the terminal ?

**Comment by andrew-veresov** [comment]
hi @cyl520134! 
I'm using task system. 
Finally I solved the ussue by moving to the shell task:
`{
            "taskName": "build-ts",
            "type": "shell",
            "command": "tsc -p tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
           },
            "dependsOn": [
                "copy-json"
            ]
}`

**Comment by dbaeumer** [comment]
@andrew-veresov since tsc is a batch file (cmd) it needs to be executed as a shell task. Process tasks can only execute `exe` under Windows.

I will close the issue. @cyl520134 please ping if you still see the problem even when using a shell task.
