### ISSUE TITLE
Time is wasted when extension contribute configurations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34353]
When we read package.json-files of our extensions we also register new configurations. The profile shows that this triggers event to which various part of our core react. That doesn't make sense because a built-in, core component like the welcome screen should be influenced by a setting from extension foo. This needs

* [ ] a fine-grained configuration change event that allows consumer to check what settings have changed
* [ ] adoption in the listeners

<img width="904" alt="screen shot 2017-09-14 at 09 25 41" src="https://user-images.githubusercontent.com/1794099/30417265-640dba36-992f-11e7-8213-12af5ff52bd8.png">

**Comment by jrieken** [comment]
@sandy081 Starting with you to check/ensure we have an event that contains enough information.

**Comment by jrieken** [comment]
@sandy081 Just to put this into perspective: This is ~10% of the time the renderer takes to finish, so the biggest single most performance issue we have

**Comment by sandy081** [comment]
@jrieken Understood. I will try to see if I can fix it this milestone.

**Comment by sandy081** [comment]
Introducing a fine grained configuration event and adopting everywhere is not trivial. So, to get some performance improvement, I introduced a new event `onDidRegisterExtensionsConfigurations` in configuration service that is triggered when extension configurations are registered. The actual event `onDidUpdateConfiguration` is not triggered during this. This will let everybody in core not to react to configurations registrations from extensions except extension host. 

Will implement fine grained configuration event and adoption as a separate feature - https://github.com/Microsoft/vscode/issues/35229

**Comment by sandy081** [comment]
Reverted the fix because we are unsure if the core has dependencies on configurations from extensions. For eg., one can use a setting as context key and context key service can read that setting.

Will do a proper fix next milestone.
