### ISSUE TITLE
git repository source code while save means blinking continuously ( Other that git repository is working fine )

### ISSUE THREAD

**Issue by gsivaprabu** [Microsoft/vscode#34350]
- VSCode Version: 1.16.0
- OS Version: Windows8 -64 bit

FYI:-

![image](https://user-images.githubusercontent.com/2444608/30416781-0befd0c0-994b-11e7-9b3f-c436659d53e4.png)

Steps to Reproduce:

1. git repository source code while save means blinking continuously 
2. Other that git repository is working fine

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Does it reproduce no matter in which folder you have opened Code?

Does it eventually stabilize?

**Comment by gsivaprabu** [comment]
FYI:-

APM (Application Folder) folder from  the repository (Angularjs-Path)

![image](https://user-images.githubusercontent.com/2444608/30489566-2d688624-9a55-11e7-88d9-3c70650967e1.png)

**My vscode View below:-**

![image](https://user-images.githubusercontent.com/2444608/30489436-d590ae72-9a54-11e7-960b-33f542fec214.png)

**Comment by gsivaprabu** [comment]
Other then git repository folder means not blinked

**Comment by joaomoreno** [comment]
This is a problem with one of your extensions.

Please try disabling them one by one until you find the culprit.

Once you do, please file an issue for that specific extension.
