### ISSUE TITLE
strings pasted to lync2010 are always formatted even if "editor.formatOnPaste": false

### ISSUE THREAD

**Issue by ThirevenLi** [Microsoft/vscode#34359]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
python|don|0.7.0
gitlens|eam|5.0.0
output-colorizer|IBM|0.1.2
markdown-table-formatter|jos|0.2.3
typelens|kis|1.4.1
cpptools|ms-|0.12.4
sublime-keybindings|ms-|2.9.1
material-icon-theme|PKi|2.2.1
trailing-spaces|sha|0.2.11
vim|vsc|0.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
When copying source code that is in length below 64kb, VS Code places two formats in the clipboard:
* a plain text format
* an HTML format (that contains syntax highlighting)

When pasting in other software, the software you paste into typically chooses whatever they believe suits their needs best. For example, when pasting in MS Word, the HTML format will be pasted, and an option appears to paste without formatting.

We currently have no way to turn this off, one possible workaround involving VS Code is to open a new untitled file (ctrl+n) and paste there first, then copy it again and paste it in Lync. That should remove the syntax highlighting...

**Comment by ramya-rao-a** [comment]
Closing this issue as there is nothing that can be done from VS Code's perspective here at the moment
