### ISSUE TITLE
Add feature to disable top bar

### ISSUE THREAD

**Issue by lomholdt** [Microsoft/vscode#34351]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.16
vscode-eslint|dba|1.3.1
php-intellisense|fel|1.5.1
phpcs|ika|0.7.0
php-docblocker|nei|1.2.0
vetur|oct|0.9.7
vscode-icons|rob|7.12.0
gitblame|wad|2.2.0

(1 theme extensions excluded)

---

Disabling tabs gives me nothing, since it still has one huge "Tab" at the top. Disabling tabs with `"workbench.editor.showTabs": false` only disables the tabs feature, it doesn't actually hide the top bar that's taking all the space. Even zen mode has the tabs.

![skaermbillede 2017-09-14 kl 09 17 48](https://user-images.githubusercontent.com/1733744/30416744-a4396800-992d-11e7-9d50-bc92dcabaa5c.png)

Steps to Reproduce:

1. Disable tabs `"workbench.editor.showTabs": false` and watch the top bar appear

Reproduces without extensions: Yes/No

**Comment by ronjouch** [comment]
@bpasero @alexandrudima @chrmarti until such a feature is officially considered/implemented, is there a feature in electron/vscode similar to Firefox's [`userChrome.css`](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) that would let willing users to manually target and tweak/disable UI elements?

In Firefox, I (and many other Firefox users enjoying the feature, there's even a [subreddit](https://www.reddit.com/r/FirefoxCSS/) for it!) routinely use this feature to `#whatever-ui-component {display: none !important}` the UX parts I don't use. Of course, that means I might kill the only entry point for an editor/extension UI component, and I'm okay with that. Is there something similar in Code?

**Comment by ronjouch** [comment]
@bpasero can you point to the bug this one is a duplicate of? I searched for it and couldn't find it.

**Comment by bpasero** [comment]
@ronjouch you can use the label [`workbench-tabs`](https://github.com/Microsoft/vscode/labels/workbench-tabs) to narrow down the search results and find it.

**Comment by ronjouch** [comment]
Found it, thank you. To other subscribers of this bug, you should look at https://github.com/Microsoft/vscode/issues/33607.
