### ISSUE TITLE
Emmet input:text completion moves cursor to type attribute instead of name

### ISSUE THREAD

**Issue by DiscreteChi** [Microsoft/vscode#34352]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshintrc-generator|ben|1.0.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.1
python|don|0.7.0
vscode-html-css|ecm|0.1.8
file-icons|fil|1.0.5
beautify|Hoo|1.1.1
vscode-cdnjs|Jak|0.14.3
cpptools|ms-|0.12.4
debugger-for-chrome|msj|3.3.0
advanced-new-file|pat|0.5.0
hipsum|thi|1.0.7
lorem-ipsum|Tyr|1.0.0
vim|vsc|0.10.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Create html file
2. Type "input:text" and press tab

Cursor is moved to type attribute that is already correctly filled in as text. Would be more appropriate for it to be moved to the name attribute. Seems to work correctly with other input completion such as input:date or input:color.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Thanks for logging this @DiscreteChi 
I have submitted a PR upstream to fix this.
https://github.com/emmetio/snippets/pull/4
