### ISSUE TITLE
Git extension fails when no git is installed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34358]
* be on windows
* don't have git installed
* this line of code throws and doesn't catch: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/main.ts#L30
* you see an error on the console

**Comment by joaomoreno** [comment]
The error is caught [here](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/main.ts#L67), at which point the error is printed to the console, as expected. Does something bad happen in the UI?

**Comment by jrieken** [comment]
Yeah, I do see an error message on the console and it is about a path on my computer... I have it on windows, I can show it you when you are around

**Comment by joaomoreno** [comment]
Let's catch the case where Git wasn't found and just throw a `Git not found` error.
