### ISSUE TITLE
Notification style breaks if filename contains markdown symbols (i.e. __)

### ISSUE THREAD

**Issue by KazeZlat** [Microsoft/vscode#34367]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Name an image with some name__contains__double__underscores
2. Try to open that image

You will see smth like this:
![An error](https://i.imgur.com/8aQI4hZ.png?1)

Probably need to escape filename
Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What the...

**Comment by bpasero** [comment]
Probably introduced via https://github.com/Microsoft/vscode/commit/7194723e62c1829890a6c6e663ad103b4be46bfb

@mjbvz

**Comment by mjbvz** [comment]
We don't support markdown in messages but do support formatted text. And for file actions specifically, we do explicitly enable `formattedText`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L199

Looks like that may be the root cause here?

**Comment by mjbvz** [comment]
Whoops, that's the wrong code. It's actually this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageList.ts#L340

**Comment by bpasero** [comment]
Yeah, we seem to support formatted text in the message list. Maybe we should not format the text when an error enters the message list widget. Anyway, this does not seem like a big deal, but PR welcome.

**Comment by mangopearapples** [comment]
Hi. I cannot reproduce. Has this issue been resolved?

Tested on `1.16.1` and `1.17.0`
