### ISSUE TITLE
zenMode doesn't display correctlly when taskbar is on the top of screen

### ISSUE THREAD

**Issue by tdkihrr** [Microsoft/vscode#34363]
- VSCode Version: 1.16
- OS Version: windows 10 1703 15063.608

Steps to Reproduce:

1. when taskbar is on the top of screen
2. user zenMode

It doesn't display correctly.

![Image of Yaktocat](http://images.cnblogs.com/cnblogs_com/tdkihrr/1079099/o_%e6%9c%aa1%e5%90%8d%e5%9b%be%e7%89%87.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this issue against chrome.
I would think that when chrome goes into full screen you see the same issue.
If not then you should file this against electron
