### ISSUE TITLE
HTML close Tag  - submit with tab-key

### ISSUE THREAD

**Issue by willi84** [Microsoft/vscode#34365]
cool HTML Autocomplete Feature. Just one suggestion:
If I get the suggestions of intellisense, it would be cool to submit the suggested tab with the tab-key.

- VSCode Version: 1.16.0
- OS Version: Window 7 Professional

Steps to Reproduce:

1. Open HTML file
2. type <div
3 try to use the tab key to complete the div-tag with a closed one.
(its a feature which works in sublime)

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
We now close the tak as soon as `>` is typed. I hope that good enough. Otherwise, please speak up.
