### ISSUE TITLE
Ctrl + D (delete whitespace) doesn't work properly

### ISSUE THREAD

**Issue by zexerlang** [Microsoft/vscode#34373]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux Mint 18 Cinnamon x64 
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. In the editor enter the following text: "a bcdefgh xx"

2. Position your cursor just after "a" which means there should be 1 space between the cursor and the letter "b". Like so (the pipe symbol represents the cursor): "a| bcdefgh xx"

3. Now press CTRL+D to delete the whitespace between the cursor and letter "b"

4. Expected behavior: A single space following the cursor is deleted. The resulting string should look like this: "abcdefgh xx"

5. Actual behavior: It deletes the space, and then the entire word following the space. The resulting string looks like this: "a xx"
Definitely not what one wants or expects.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@zexerlang What command have you bound to `ctrl+d`. By default `ctrl+d` does not delete. You can find it out in the keybindings UI by searching for `ctrl+d`.
