### ISSUE TITLE
// @ts-check doesn't know Web Bluetooth and Generic Sensors

### ISSUE THREAD

**Issue by kenchris** [Microsoft/vscode#34376]
I get errors for navigator.bluetooth Accelerometer, Magnetometer etc.

If you can tell me where this can be added and how to, we can supply PRs

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TSJS-lib-generator#294

**Comment by mjbvz** [comment]
As a workaround, try installing these the typings for web bluetooth manually: `npm install --save-dev @types/web-bluetooth`
