### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by ShayanKebriti** [Microsoft/vscode#34370]
hello guys. i have a huge problem.
i saw another problems but i didn't give my question!
" i can install vscode ! "
i can't fix : 
'  ./scripts/npm.sh: line 25: npm: command not found  '

thanks

**Comment by alexandrudima** [comment]
@ShayanKebriti Do you want to create a development setup for vscode ? This is explained in detail here : https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

Or do you want to install VS Code? You can get a built version from our website https://code.visualstudio.com/
