### ISSUE TITLE
Error on creating launch.json file in extension that contributed debuggers

### ISSUE THREAD

**Issue by killerall** [Microsoft/vscode#34375]
Hi,
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 
advpl-vscode|Kil|0.7.2

Steps to Reproduce:

1. Open a folder that does not have a launch.json;
2. Tip F5 to call the Debug;
3. select the Advpl Debug

Error:

'error while processing request 'launch' (exception: Object reference not set to an instance of an object.)'

Reproduces without extensions: No
Extensions site :https://marketplace.visualstudio.com/items?itemName=KillerAll.advpl-vscode
In version 1.15 it worked normally

**Comment by isidorn** [comment]
Please file this against the advpl debug extesion.
Thanks

**Comment by killerall** [comment]
I'm sorry @isidorn if I did not make myself understood, I develop the extension.
The issue is that the example code vscode (vscode-mock-debug) of the problem in version 1.16.

If you use the mock extension version, which works on 1.16, (the master of this version only works on the future 1.17)
git checkout b86ef9e3735caca4f0a4dea3bc19a4ea6930f1cb

You will have the same problem.

Apart from the change to support the DebugConfigurationProvider, it broke the creation of launch.

Thanks

**Comment by isidorn** [comment]
@killerall thanks for clarification, however I think this is expected. For more details about what we are changing and deprecating you can read our release notes https://code.visualstudio.com/updates/v1_16#_debug-contributions-in-packagejson

I believe that mock debug working with only insiders is fine since we want to have it as an example for all future debug adapters.

fyi @weinand

**Comment by weinand** [comment]
Yes, the latest repository version of mock-debug requires VS Code 1.17.0 which is stated in the package.json. However, the mock-debug on the Marketplace works fine with VS Code 1.16.
This constraint will go away when we release VS Code 1.17 stable.
If you need the example for VS Code 1.16 please branch off commit https://github.com/Microsoft/vscode-mock-debug/commit/dfef538ad3930f86eef9b350b7567428dcb14b2b

**Comment by killerall** [comment]
@weinand  thanks for answer,but
I just installed mock-debug on the marketplace, and when trying to create the launch, and got error:

![image](https://user-images.githubusercontent.com/4764609/30451400-e7057bce-9969-11e7-99c3-4a70278ac1eb.png)

Thanks a lot.

**Comment by weinand** [comment]
@killerall I cannot reproduce your problem. In a fresh install of VS Code 1.6 on Windows I've installed mock-debug from the marketplace, and opened an empty folder.
After switching to the debug viewlet and pressing the gear icon and selecting the "Mock" environment I got this launch.json:

![2017-09-14_22-30-17](https://user-images.githubusercontent.com/1898161/30454354-4e806296-999c-11e7-8d6f-b88ab645ab16.png)

Please make sure that you have no other extensions than mock-debug installed.

**Comment by killerall** [comment]
@weinand, thank you very much for the attention. I made an install in a new VM, only with mock.

If you can,try do the same test, but don't switch to debug viewlet and press F5.
The error will occur.
If I follow the procedure that you did not really mock the problem, and my extension as well.

**Comment by weinand** [comment]
Sorry, I cannot not reproduce.
Here is what I did:

![2017-09-14_23-08-48](https://user-images.githubusercontent.com/1898161/30455879-dd8d0098-99a1-11e7-828f-a4e9a50e61db.gif)

**Comment by killerall** [comment]
I did the same, but the result was:

![_moca_34375](https://user-images.githubusercontent.com/4764609/30456634-d970e136-997a-11e7-981e-0bebf7651b5f.gif)


- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.20.0

**Comment by j-deodato** [comment]
Hi! 
@weinand , I´ve got the same problem reported by @killerall . 
I´ve instaled a new version of VsCode and the Advpl extension, and reproduced this bug.
