### ISSUE TITLE
Long delay when bringing up the build tasks menu or launching a task, when used with an extremely large folder

### ISSUE THREAD

**Issue by GSThornton** [Microsoft/vscode#34387]
- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:58:39.362Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.4
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
perforce|sle|2.1.1

---

Whilst working on VSCode support for Unreal Engine, I have noticed a significant stall when attempting to open the "run build task" dropdown, or when launching a build tasks and waiting for the task to actually start. This appears to be unrelated to the contents, or even the existence, of the tasks.json, or anything else in the .vscode directory. The issue reproduces even when I delete the entire .vscode directory.

I suspect this isn't something specific to the Unreal Engine folder, rather just when the folder is very big, containing a significant volume of data. For reference, my current Unreal Engine workspace is 853GB big, and contains 1.3 million files and around 104k folders. I have configured my workspace settings file to exclude huge amounts of this data, but it makes no difference.

Steps to Reproduce:

1. Download the UE4 source distrubution from GitHub
2. Open VSCode, pointing at the root folder 
3. Use Ctrl-Shift-B to open the build tasks drop down
4. Observe significant delay with "Fetching build tasks..." displayed in the status bar

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
We try to autodetect task. You can disable this for every task system we support. The setting is:

`gulp.autoDetect`, `jake.autoDetect`, `grunt.autoDetect` and `npm.autoDetect`. 

Set the one you use to false.

**Comment by GSThornton** [comment]
Thank you. Setting "typescript.tsc.autoDetect" to "off" fixed the problem.
