### ISSUE TITLE
打开VS Code  提示‘扩展宿主意外停止’

### ISSUE THREAD

**Issue by Vove7** [Microsoft/vscode#34383]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.just open it，64 bit too。
2.
error info：

/F:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 扩展宿主意外终止。
e.doShow @ /F:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

**Comment by alexandrudima** [comment]
@Vove7 does this issue reproduce for you when disabling extensions. i.e. launching `code --disable-extensions` or when disabling them manually from the extensions viewlet ?

**Comment by i672715631** [comment]
Same as you, it's seem like git extensions problem.

**Comment by i672715631** [comment]
设置-git-"git.path": "D:/Program Files/Git/cmd/git.exe",

**Comment by Vove7** [comment]
好的 楼上 我去试试😄

**Comment by i672715631** [comment]
不过我出现的目录不一样……

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Vove7** [comment]
@i672715631 设置了git.path好了😄谢谢

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
@alexandrudima Thanks, seems to be the same as the others... I can't seem to repro it on any machine I try... though there are definitely people around which repro it easily.

**Comment by alexandrudima** [comment]
@joaomoreno pinged you for the hint:

> 设置-git-"git.path": "D:/Program Files/Git/cmd/git.exe",

i.e. might be reproducible if Windows is not installed under `C:`
