### ISSUE TITLE
Navigate back after cross-file goto-definition takes me to a new location

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#34389]
- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:58:39.362Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open the vscode repo.
2. Go to `ipc.electron-main.ts`
3. Click on `WebContents` in `Electron.WebContents` (line 12).
4. Go -> Go to definition (takes you to the definition of `class WebContents` in `electron.d.ts`).
5. Go -> Back

Expected: Get taken back to `ipc.electron-main.ts`.
Actual: Get taken to a random location in the middle of `electron.d.ts`.

**Comment by bpasero** [comment]
@andy-ms quite possible I broke something with my refactoring to merge editor history locations. However I am not able to reproduce:

![panel-red](https://user-images.githubusercontent.com/900690/30473826-f2c4c3aa-9a01-11e7-9c39-10f034e31eb9.gif)

Can you let me know if those are your steps and if you have any settings configured?

**Comment by andy-ms** [comment]
I can still reproduce this with the default settings (contents of `settings.json` commented out) and with the latest update.
It looks like some navigation history persists even after I close and re-open vscode; every time I reopen `ipc.electron-main.ts` my cursor is already at `WebContents`. Is there a way I could send the history to you so you could reproduce the error?

**Comment by bpasero** [comment]
@andy-ms to get a truly fresh state you an always run `code-insiders --user-data-dir=<somefolder>`

Can you share a screencast of the behaviour you are seeing?

**Comment by andy-ms** [comment]
@bpasero Could you recommend a way of taking a screencast?

**Comment by bpasero** [comment]
@andy-ms maybe screen share in a skype meeting and record the meeting? I only know of macOS solutions, sorry.

**Comment by andy-ms** [comment]
![cast](https://user-images.githubusercontent.com/19274678/30490666-84e94dae-99ef-11e7-8ced-104a98035f7a.gif)
This screencast is from a session with `--user-data-dir`; I couldn't reproduce it immediately but could after stepping around in `electron.d.ts` for a while.

**Comment by bpasero** [comment]
@andy-ms thanks, I can reproduce. a regression I introduced. Should land in Monday's insider.
