### ISSUE TITLE
// @ts-check complains about screen.orientation and suggest msOrientation

### ISSUE THREAD

**Issue by kenchris** [Microsoft/vscode#34381]
```[js] Property 'orientation' does not exist on type 'Screen'. Did you mean 'msOrientation'?```

Though screen.orientation is what Chrome uses

```  mat4.rotateZ(this.rotationMatrix, this.rotationMatrix, toRad(window.screen.orientation.angle || 0));```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TSJS-lib-generator#295
