### ISSUE TITLE
[Folding] Actions on folded section only effects first line

### ISSUE THREAD

**Issue by bofabcd** [Microsoft/vscode#34388]
- VSCode Version: 1.16.0
- OS Version: Centos 7

Steps to Reproduce:

1.  Fold a section of code
2.  Select folded section
3.  Press delete, or alt+(up or down), or copy and paste

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
How did you select the folded region?

You have to select up to the next line if you want to work on the whole folded range.
Otherwise, it's really just the one line
![image](https://user-images.githubusercontent.com/6461412/30746716-ff0ec666-9faa-11e7-8cf4-7a9fac8dbe93.png)
