### ISSUE TITLE
On redhat Linux key map is incorrect (backspace -> [EQUAL], left ctrl -> ctrl-enter, etc)

### ISSUE THREAD

**Issue by potbunker** [Microsoft/vscode#34391]
- VSCode Version:
- OS Version:

Version 1.16.0
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-06T16:19:37.192Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo

Steps to Reproduce:

1. Backspace and many other keys do not work
2. On keyboard shortcut, add a new shortcut to empty map
3. In the key press screen, backspace results in [EQUAL], left ctrl results in ctrl-enter, etc

Tested wit xev, and both key codes are correctly sent.
Works in embedded terminal, only broken in editor.

Reproduces without extensions: Yes

**Comment by rmunn** [comment]
What keyboard do you have installed (e.g., US QWERTY, Dvorak, UK, French, German...), and how did you select that keyboard (GNOME GUI settings app, KDE GUI settings app, manually editing a config file (which one?), something else...)? Those seem like details the VS Code dev team will need in order to reproduce the problem.

**Comment by potbunker** [comment]
I am in a corporate setting, and launching it throug X forwarding over an exceed on demand channel.
Even the keyboard is custom built.
On a Windows 7. Where can I find these information?
US  QWERTY, and it is mapped via X, I suppose.

It is weird that integrated terminal sees the keys correctly, but only the editor does not.

**Comment by alexandrudima** [comment]
@potbunker There is a known issue with remoting. Please see https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/30737358-9694dd92-9f86-11e7-89d0-55f394dfb222.png)
