### ISSUE TITLE
Transform tips to links or buttons?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#34397]
When no editor is open there's an area in the middle of the screen with some commands and hotkeys:

![no-editor](https://user-images.githubusercontent.com/9638156/30444998-6260f6cc-998d-11e7-89c8-4166c3532363.png)

I expected them to trigger actions on click but that didn't happen. Was it done to promote hotkeys (intentionally) or not?

It just so happens "Welcome page" has both (links and buttons) that invoke commands written on them.

**Comment by bpasero** [comment]
I saw a duplicate of this one.

**Comment by usernamehw** [comment]
Of this one https://github.com/Microsoft/vscode/issues/16601
