### ISSUE TITLE
Working Tree view does not update when staging selected ranges.

### ISSUE THREAD

**Issue by thomsavage** [Microsoft/vscode#34392]
- VSCode Version: 1.16.0
- OS Version: Windows 10

Steps to Reproduce:

1. Modify a file.
2. Open the Working Tree view of the file to see the diff.
3. Highlight changes.
4. Select the "Stage Selected Ranges".

The selected ranges are added to the Git Index, but the Working Tree view is not updated to remove the staged changes (it used to do this).

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#34209
