### ISSUE TITLE
I want to be able to just close things consistently without worrying about what type of thing it is

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#3439]
There's this extremely annoying distinction between editor, working files and other views (e.g. settings). With a single, common shortcut key, if I have a thing open, I want to be able to close it and it's gone. If it was in working files, it's gone from there too. It doesn't matter what I had open, I want it gone. Screwing around trying to learn the different ways to close things and having to maintain a mental note of whether I'm closing an editor or a working file is irritating to the point that it's keeping me away from VS Code. The fact is, if I close a working file, getting it back with CTRL+P is so easy and frictionless that I don't even care that I closed it. If I could just have a shortcut key to "just close whatever the hell is currently open and, if applicable, remove it from working files too", that would be fantastic.

For what it's worth, I don't really care about the whole debate around tabs-or-not. Working files is fine for me in this regard. Saving the previous workspace state of a working file, even if it gets closed, is a pretty good idea though.

**Comment by Tyriar** [comment]
You can add these keybindings to get that sort of behavior to close the current working file (<kbd>ctrl</kbd>+<kbd>w</kbd>) and close all working files (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>w</kbd>).

```json
{ "key": "ctrl+shift+w",        "command": "workbench.files.action.closeAllFiles" },
{ "key": "ctrl+w",              "command": "workbench.files.action.closeFile" },
```

**Comment by axefrog** [comment]
@Tyriar yep but I can't do what I was talking about; with one key, close the thing that is currently open, no matter what it is, and also remove it from working files, if applicable. i.e. what every other text editor does by default.

**Comment by Tyriar** [comment]
I notice the default keyboard shortcuts doesn't want to close using `workbench.files.action.closeFile`, this may be as issue of changing that action to actually close everything as I was expecting it to do. What else are you unable to close using these keybindings?

**Comment by axefrog** [comment]
@Tyriar basically any kind of settings page; those can only be closed with the "close editor" command.

**Comment by bpasero** [comment]
Pushed a change that makes "Close File" close any active editor. After march we will revisit the confusing subtle difference between "Close Editor" and "Close File".

**Comment by axefrog** [comment]
Nice turnaround, thanks!
