### ISSUE TITLE
DateTime is no more localized (in extension)

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#34398]
- VSCode Version: 1.16 /1.17 insider
- OS Version: Windows 10

In my extension (local-history), I use date.toLocaleString()
Previous return : 17/07/2016 à 10:12:25  (not sure it was in last version, perhaps a previous one...)
Currently return : 2016-7-17 10:12:25

In the console (Help / Toggle Developer Tools), I can still see  "17/07/2016 à 10:12:25"

**Comment by jrieken** [comment]
Hard to say, the value of `toLocaleString` depends on your timezone and locale: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString. I don't think that we have changed that or can event influence that. 

@dbaeumer Does your nls-module depends on some process-defaults or on the API?

**Comment by dbaeumer** [comment]
@jrieken I depend on electron API that I call to find out the locale to use. I somehow remember that I saw that before. Might be an electron problem ?

**Comment by zabel-xyz** [comment]
I try to reinstall the previous version, it worked:

1.15.1:
![vscode15](https://user-images.githubusercontent.com/16486407/30514491-cb437064-9b15-11e7-8387-d962c3fa0fa7.png)

Now, something changed :
1.16.1:
![vscode16](https://user-images.githubusercontent.com/16486407/30514495-d50bf6fc-9b15-11e7-9703-db6ecab0fb36.png)

**Comment by jrieken** [comment]
@zabel-xyz What extension is that?

**Comment by zabel-xyz** [comment]
Like I say, I use date.toLocaleString() in my extension (local-history)
https://github.com/zabel-xyz/local-history/blob/master/src/historyTree.provider.ts#L74
https://github.com/zabel-xyz/local-history/blob/master/src/historyContent.provider.ts#L127

**Comment by zabel-xyz** [comment]
For now, I added a settings in my extension :
"local-history.dateLocale":  locale to use when displaying date
