### ISSUE TITLE
Coloring issue in .Less file

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#34394]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Copying from:
https://github.com/Microsoft/TypeScript-TmLanguage/issues/492#issuecomment-329407436

> I've only noticed this happening today, so I'm not sure if the latest VSCode update has introduced this bug (I'm running 1.14.0).
> 
> ![Image](http://i.imgur.com/Z2nE8VC.png)

> @sheetalkamat I'm able to reproduce this anywhere the cursor property is defined.
> 
> 1. Create a file with the .less extension or change the language to LESS.
> 2. Use the following CSS:
> 
> ```css
> div {
>   cursor: pointer;
>   color: tomato;
> }
> ```
> 
> This is the result I'm seeing (I'm now using 1.16.0):
> 
> ![https://i.imgur.com/4Mhs9SH.png](https://i.imgur.com/4Mhs9SH.png)
> 
> This does not apply to files marked as using the CSS language, only LESS.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
This issue was moved to atom/language-less#79
