### ISSUE TITLE
Is there anyway to hide the twitter feedback icon?

### ISSUE THREAD

**Issue by t0lkman** [Microsoft/vscode#3440]
This smiley face is distracting me for some reason :)

**Comment by joaomoreno** [comment]
I'm afraid there isn't. Sorry!

**Comment by egamma** [comment]
@waderyan fyi

**Comment by waderyan** [comment]
They've seen this feedback in VS as well...

**Comment by bentx** [comment]
@waderyan true, although the icon in VS was changed later to be something less distracting than a smiley face, could this be improved ? A way to hide it or at least to change the icon would be nice.

**Comment by waderyan** [comment]
Yeah they had some interesting data on why they made that change. I'll get with the team and understand what they did. 

Any suggestions for a new, less distracting icon?

**Comment by bentx** [comment]
Nice, could be anything that doesn't catch the eye really, speech bubble etc.

**Comment by waderyan** [comment]
Created an issue to look into options.

**Comment by blueredcat** [comment]
More than one year later and I still cannot remove this very cynical marketing feature.

**Comment by marteleto** [comment]
https://github.com/Microsoft/vscode/issues/7893#issuecomment-271556921
^ this worked.
