### ISSUE TITLE
Option to always keep panel hidden and never popup automatically

### ISSUE THREAD

**Issue by idchlife** [Microsoft/vscode#34402]
- VSCode Version: 1.16.0
- OS Version: 10.12.5

Steps to Reproduce:

1. Install vscode-java extension
2. Create simple project with gradle, start writing a file

Reproduces without extensions: No

I think this is an issue with many plugins that have several issues. One could say hey - just fix the plugins, write issue there, but I think it's ok for some plugin to show errors in output. I think there can be a feature, option in settings which would disallow forceful pop up of this panel, instead showing small alert icon for developer to see later or whenever he/she wants.
Thanks!

**Comment by isidorn** [comment]
We accept PRs that fix this
