### ISSUE TITLE
Pasted text is truncated at the first null char

### ISSUE THREAD

**Issue by jeffman** [Microsoft/vscode#34400]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
xml|Dot|1.9.2
json-tools|eri|1.0.2
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
prettify-selected-json|vth|1.0.3
---
When pasting text that contains null characters, the pasted text will be truncated at the first null character. Notably, copying text from within vscode and pasting it in-place will change the text that was selected if it contains nulls.

Steps to Reproduce:
1. Copy text to your clipboard containing null characters
2. Paste into a vscode window

Expected behaviour: the entire string copied to the clipboard is pasted.

Actual behaviour: the pasted string is truncated before the first null character.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is a Chromium issue. VSCode is built on top of Electron, which is built on top of Chromium.

Also (in this comment box) I cannot paste text which contains null characters.

May I kindly ask that you open an issue at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
