### ISSUE TITLE
[macOS] editor.autoClosingBrackets not working with "U.S. International - PC"

### ISSUE THREAD

**Issue by sgruetter** [microsoft/vscode#34407]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.1
pgsql|dou|0.0.8
toggle-excluded-files|eam|1.6.0
prettier-vscode|esb|0.23.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Switch the keyboard layout to "U.S. International - PC" on the Mac. System Preferences > Keyboard > Input Sources > Add they layout and enable it (e.g. via US Flag in the task bar, next to the clock).
2. In Visual Studio Code, make sure the setting "editor.autoClosingBrackets" is set to true.
3. Try to use auto completion with single or double quotes => it's not working, only 1 character appears.
4. Switch the keyboard layout to "U.S.". Add again a double or single quote => VS Code auto-completes the input with a second character.

See also video: https://imgur.com/a/Wpm7w
Note: 
- The different color of the single quote for U.S. International. That's to create special chars, e.g. é or ë for double quotes. To just write the double or single quote character, hit space afterwards. 
- Braces always work.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This also was working and appears to be broken by our electron upgrade.

**Comment by alexandrudima** [comment]
My mistake. This never worked, as for US intl we prevent the auto closing characters especially for the case of creating accented characters.

**Comment by nicgirault** [comment]
A related problem is that when I select a word and add quotes, it removes the word whereas I would expect the word to be wrapped with quotes

**Comment by sgruetter** [comment]
@nicgirault I agree, this seems to be a related bug as wrapping-selection-with-quotes works with standard US layout.

**Comment by rogeriopradoj** [comment]
It's the same bug as https://github.com/Microsoft/vscode/issues/26820, isn't?

That one is tagged with "needs more info". Do you really need more information about the issue from us users?

**Comment by lucasfeliciano** [comment]
What is the status on this PR?
This affects all users who use keyboards(languages) which uses accents

**Comment by sgruetter** [comment]
@lucasfeliciano The issue still exists in the current version (1.24.1). My workaround is to switch layouts with Control+Space. US for programming, US International for everything else.

This works, and is not really a problem once gotten used to it. A fix would of course still be nice.

**Comment by oji** [comment]
+1

**Comment by Aranor28** [comment]
+1

**Comment by eduardonunesp** [comment]
+1

**Comment by dandeveloper** [comment]
It's the same bug as [#26820](https://github.com/Microsoft/vscode/issues/26820) and it was fixed, but the problem has changed and the comments ware blocked in the referred issue.

**Comment by rhyek** [comment]
Something I'm used to doing in Windows and Ubuntu when using US International with Dead Keys is this sequence that works perfect:

quote key, space, (2 quotes will be inserted and cursor is positioned between them), write string, quote key, space, (no new quote is added; cursor is positioned after second original quote). **result: 'test'|** (| is position of cursor)

On OSX, using ABC input source (no dead keys) the behavior is exactly the same (without the spaces). With U.S. International - PC (dead keys) the behavior is this:

quote key, space, (2 quotes will be inserted and cursor is positioned between them), write string, quote key, space, (this time a new quote **is** added; cursor is positioned after this new quote and before the original second quote). **result: 'text'|'**

Hopefully this is clear.

**Comment by rhyek** [comment]
This is especially annoying since, as someone else mentioned, you can set ABC and US International as input source options, but for some reason the default will always be ABC for every new window. It would need to be the other way around for it to be a good workaround.

**Comment by rhyek** [comment]
There's actually an `editor.autoClosingQuotes` setting that I set to `never` and this works fine for me while using *U.S. International - PC*. This is a good workaround.

**Comment by rhyek** [comment]
Actually, my solution sucks, because when you write the first quote the rest of your code is now a string until you close it. This really needs to be looked at!

**Comment by andremacola** [comment]
another issue maybe related to autoClosingBrackets is #73828

**Comment by fabb** [comment]
Another horrible thing connected to the quote dead key: when I press the quote key + the. The left arrow, an invisible unicode control character is inserted. It took me hours to debug because I inserted such a character in a className string wich caused the class not matching and the css style not being applied.

**Comment by andremacola** [comment]
this affect quotes in multicolumn selection too.

**Comment by andremacola** [comment]
Apparently issue #73828 is fixed on:

Version: 1.38.0-insider
Commit: ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8

Will test more in the next days.

**Comment by alexandrudima** [comment]
Indeed, this got fixed via 37981d8fd5d4ba1619f69dc8a0f4670543d39650

**Comment by alexandrudima** [comment]
The easiest way to verify is to use the US Intl Keyboard layout on mac and press double quote / single quote + <space> to insert it...

**Comment by alexandrudima** [comment]
@ccarstens This has been fixed and the fix has been shipped with VS Code 1.38. Please open a new issue with precise steps if this doesn't work for you as expected.
