### ISSUE TITLE
VS Code will not start when installing from Marketplace from Chrome

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34405]
MacOS
stable 1.16.0

Force Quit Stable
In Chrome, browse to the marketplace
Click on "Install" on any extension

Result: The stable icon just bounces, never starts

If I use Safari, Code will start correctly.

In this gif you can see the code icon bounce but it never starts (sorry its clipped):

![installbug2](https://user-images.githubusercontent.com/1487073/30456317-f3af1536-9957-11e7-9d04-e8f8e2ccc2c3.gif)

**Comment by joaomoreno** [comment]
I know it sounds like a joke but... did you try restarting your machine?

**Comment by chrisdias** [comment]
heh heh heh... I restarted and it works.
