### ISSUE TITLE
Uninstall of a dependent extension silently fails

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34406]
MacOS
Insiders or Stable

Install an extension pack
Try to uninstall one of the dependent extensions

Result: You are asked if you want to uninstall the extension, you say OK, but the extension is not uninstalled.

In this gif, the Azure Account extension is a dependency of the App Service extension.  When I try to uninstall I'm prompted, but nothing happens.

![uninstalldep](https://user-images.githubusercontent.com/1487073/30457085-f6960c16-995a-11e7-81cc-d9879ecc7378.gif)

I would expect a prompt that says "This extension cannot be uninstalled because other extensions are dependent upon it. Please uninstall the other extensions first." 

Even better, there is some way to see the list of extensions that are dependent upon the extension, like we have a "Dependencies" tab for an extension, perhaps we have a "Dependents" tab.

**Comment by sandy081** [comment]
Hmm.. strange. I remember error message was shown. Will look into it.
