### ISSUE TITLE
Linux install code_1.16.1-xxx.deb is not working

### ISSUE THREAD

**Issue by aanthraxx** [Microsoft/vscode#34415]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.3
vscode-twig-pack|baj|1.0.0
phpserver|bra|2.0.0
gitignore|cod|0.5.0
githistory|don|0.2.3
gitlens|eam|5.0.0
vscode-great-icons|emm|2.1.16
php-debug|fel|1.11.1
file-icons|fil|1.0.5
sublime-babel-vscode|jos|0.2.8
materialize-snippets|len|1.1.2
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|2.9.1
php-docblocker|nei|1.2.0
LiveServer|rit|2.1.1
bootstrap4-vscode|the|2.4.0
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Download the package from https://code.visualstudio.com/docs/?dv=linux64_deb
2. Try to install it via terminal
3. it will give you a message "bash: syntax error near unexpected token `('"

Sorry in advance about this post I just don't know where to report this. It is not code related problem but please do check.

**Comment by weinand** [comment]
After downloading the deb archive I could install with `sudo apt install ./code_1.16.1-1505406497_amd64.deb` without problems.

**Comment by Tyriar** [comment]
Publishing was delayed, should all be fine now.

**Comment by aanthraxx** [comment]
Thanks
