### ISSUE TITLE
Please add your own FTP module!

### ISSUE THREAD

**Issue by lvar** [Microsoft/vscode#34418]
I already try every ftp plugin on the market....amd many times I'm endin with blank files or losing content because this plugins are not working properly... PLEASE!! add your own ftp module!

**Comment by jrieken** [comment]
boom: https://github.com/Microsoft/vscode/pull/34229. This is part of a larger effort and I cannot promise that we ship this in September but this will happen and it will be good. This is how it looks on my dev setup

<img width="872" alt="screen shot 2017-09-14 at 18 37 21" src="https://user-images.githubusercontent.com/1794099/30472802-3576d052-99fe-11e7-9a0d-99c3eb9be8dd.png">
