### ISSUE TITLE
the output&dubug console output chinese with messy code

### ISSUE THREAD

**Issue by rocketRobin** [Microsoft/vscode#34417]
- VSCode Version:1.16.1
- OS Version:windows 7 sp1

Steps to Reproduce:

1. make some dotnet core project
2. start dubug
3. you will see
![image](https://user-images.githubusercontent.com/9987850/30464496-64d5b01a-9a04-11e7-9348-e3f5f337be87.png)

or  if you output string has chinese ,that will be the same 
![image](https://user-images.githubusercontent.com/9987850/30464520-916397aa-9a04-11e7-9097-88b25c605aed.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of #35235
