### ISSUE TITLE
Cannot use "goto Definition"

### ISSUE THREAD

**Issue by deftcat** [Microsoft/vscode#34416]
- VSCode Version: 1.16.0
- OS Version:10.12.6

Steps to Reproduce:

1. In React code. include the pkg, but I cannot use command to 'goto definition'. previous version works well.
2. In React code. self define style(eg. styles.selfDefStyle), I cannot use 'goto definition' to kind of jump to the definition code.
ps. previous version works well.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
To help us investigate, please provide some example code that demonstrates this problem or a small sample project

**Comment by deftcat** [comment]
Thank for your reply.

Here 

`import React from 'react';`
`import { StyleSheet, Text } from 'react-native';`
`import _ from 'lodash';`
`export default class Example extends React.Component {`
`  render() {`
`    return (`
`      <Text style={styles.myStyle}>{_.get(this.state, 'name', 'Hello')}</Text>`
`    );`
`  }}`

`const styles = StyleSheet.create({`
`  myStyle: {`
`    margin: 100, color: 'red',fontSize: 50,`
`  }`
`})`

I just update to VSCode Version: 1.16.1, and surprisedly the pkg of 'goto Definition' work.
But **styles.myStyle**  , myStyle cannot show 'goto definition'.

**Comment by deftcat** [comment]
Thank for your reply. 

Here 

`import React from 'react';`
`import { StyleSheet, Text } from 'react-native';`
`import _ from 'lodash';`
`export default class Example extends React.Component {`
`  render() {`
`    return (`
`      <Text style={styles.myStyle}>{_.get(this.state, 'name', 'Hello')}</Text>`
`    );`
`  }}`

`const styles = StyleSheet.create({`
`  myStyle: {`
`    margin: 100, color: 'red',fontSize: 50,`
`  }`
`})`

I just update to VSCode Version: 1.16.1, and surprisedly the pkg of 'goto Definition' work.
But **styles.myStyle**  , myStyle cannot show 'goto definition'.

**Comment by mjbvz** [comment]
Thanks. I tried the example but see `go to definition` working as expected on `myStyle` in `style={styles.myStyle}` 

Do you have any extensions installed? Does this problem happen if you disable all extensions? To disable all extensions, run the `Extensions: Disable all installed extensions` command in vscode and restart the window

**Comment by deftcat** [comment]
Thanks for this commend.
Here is the extension I've installed : `React Native Tools`, `React-Native/React/Redux snippets for es6/es7` , `TODO Highlight` and `vscode-icons`.
I've try ` Extensions: Disable all installed extensions` ,but no work for me. 
Here is the screenshot. 
<img width="910" alt="gotodefinition" src="https://user-images.githubusercontent.com/17827939/30469438-e4a83998-9a22-11e7-8569-8ff5e45a8c4c.png">

`Go to definition ` is really powerful 💯  for me. really hope it works as expected.

**Comment by mjbvz** [comment]
When you run `go to definition` on `StyleSheet` in the `import` and in `StyleShee.create`, what does it show?

You may also want to try adding `// @ts-check` to the top of the file. This enable type checking for JavaScript files and can catch problems with packages not being imported properly: https://code.visualstudio.com/docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files

**Comment by deftcat** [comment]
Hello @mjbvz ,
Thank for your help. Today I am on the react project.
and the `goto definition` suddenly work!
