### ISSUE TITLE
problemMatcher $tsc-watch ignores error second time around

### ISSUE THREAD

**Issue by cloudkite** [Microsoft/vscode#34412]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 15.6.0
- typescript version: 2.5.2

Given the following tasks.json which finds all typescript errors in project

```
// tasks.json
{
  "version": "2.0.0",
  "tasks": [
    {
      "taskName": "tsc-watch",
      "type": "shell",
      "command": "./node_modules/.bin/tsc",
      "args": ["--noEmit", "-w", "-p", "."],
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": false,
        "panel": "shared"
      },
      "group":{
        "kind": "build",
        "isDefault": true
      },
      "isBackground": true,
      "problemMatcher": "$tsc-watch"
    }
  ]
}
```

an index.ts file:
```
// index.ts
import related from './related';

console.log(related(1))
```

an related.ts file:
```
// related.ts
export default function related(thing: number) {
  return thing
}
```

Steps to reproduce.
1. Open related.ts without index.ts open.
2. Change `thing: number` to `thing: string` = vscode correctly shows 1 error
3. Undo change = vscode correctly shows 0 errors
4. Redo change in Step 2 = vscode incorrectly still shows 0 errors

**Comment by dbaeumer** [comment]
@cloudkite very good catch.

I fixed this for the next insider build.

**Comment by cloudkite** [comment]
@dbaeumer Awesome thanks for that! looking forward to the next build 👍
