### ISSUE TITLE
Microsoft C++ Runtime Library: "Assertion failed" when open VS code

### ISSUE THREAD

**Issue by ghostarc** [Microsoft/vscode#34428]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by DininduWanniarachchi** [comment]
+1

**Comment by DininduWanniarachchi** [comment]
![error](https://user-images.githubusercontent.com/12568779/32786254-6bd6d4da-c979-11e7-8641-4d960db4bbd7.PNG)
