### ISSUE TITLE
PHP indentation usually breaks when pasting over a method

### ISSUE THREAD

**Issue by neerolyte** [microsoft/vscode#34424]
- VSCode Version: 1.16.1
- OS Version: 10.12.6

Steps to Reproduce:

1. Write some PHP code
2. Select a method (class function) in full with some whitespace before it so that pasting it twice will result in the right thing being duplicated
3. Copy (command+c)
4. Paste (command+v) twice
5. Observe strange indentation:

![weird-indentation](https://user-images.githubusercontent.com/1070702/30467739-4b6e9896-9a2a-11e7-968e-a4452e16c5db.gif)

Reproduces without extensions: Yes

**Comment by neerolyte** [comment]
Happens in Insiders 1.17.0 too.

**Comment by MikeVelazcoMtz** [comment]
This happens to me also, but with my indentation is with spaces and on every paste adds one space to each line.

**Comment by neerolyte** [comment]
From #6392

> I found that hitting CTRL-Z (undo) after CTRL-V (paste) fixes the indentation. Faster to fix, but what extra step is taking place that the CTRL-Z has to undo it? The auto-indent?

**Comment by neerolyte** [comment]
Putting:

```json
    "[php]": {
        "editor.autoIndent": false
    }
```

in config also stops VSCode breaking indentation in PHP files (by turning off the feature).

**Comment by MikeVelazcoMtz** [comment]
I checked and found what I suppose it is a related issue:

When pasting from a file with phpdocumentor comments to another a method it adds one space to every line:

![error_vscode](https://user-images.githubusercontent.com/5341310/30711028-08bbf032-9ecd-11e7-8119-c391fcf40eb9.gif)

**Comment by peluprvi** [comment]
This happens with js files too, only in some cases.

Examples with problem:
```js
(function(){

  var error = function(){
    return true;
  };

})();
```
```js
(function(){

  'use strict';

  var error = function(){
    return true;
  };
  
})();
```


Examples without problem:
```js
(function(){
  'use strict';

  var error = function(){
    return false;
  };

})();
```

```js
(function(){
  
  'use strict';

  var error = false;

})();
```

```js
(function(){
  var error = function(){
    return false;
  };

})();
```

**Comment by peluprvi** [comment]
Related to: https://github.com/Microsoft/vscode/issues/33011 and https://github.com/Microsoft/vscode/issues/36294

**Comment by robrecord** [comment]
This isn't just PHP, but every language. This is a core feature. How is it languishing?

**Comment by robrecord** [comment]
Any detail as to why this bug was closed, @connor4312 ?

**Comment by connor4312** [comment]
The issue here was fixed in the linked commit (https://github.com/microsoft/vscode/commit/867bcaee0df6a87ab2f81ef04f24d1e4fe3f6135), which is available on the Insiders build and will be in the next release 🙂
