### ISSUE TITLE
Go to matching bracket doesn't scroll

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode#34429]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Simply create javascript file or any other language mode.
2. Create matching bracket "{ }"
3. Give a lot of new line in between so the bracket separated until the editor scrolls.
4. Now try to use shortcut "Go to matching bracket"
5. The cursor jump, but the editor doesn't scroll.

Reproduces without extensions: Yes

**Comment by rcjsuen** [comment]
See #32597.

**Comment by alexandrudima** [comment]
A fix is available on the insiders channel and will come out to stable with the next release.
