### ISSUE TITLE
Avoid sync fs calls in workbench: extensionTipsService

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34423]
In the renderer we want to stay away from sync fs API calls to node.js because each call will stop the VM from doing anything. We should try to use the async fs APIs. 

The code in question is: https://github.com/Microsoft/vscode/blob/6c4274d7e53913cc905dcd20e59f6d7a9c4b7697/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L343

**Comment by ramya-rao-a** [comment]
@bpasero What about https://github.com/Microsoft/vscode/blob/ed2b9d0ed1caf9d06e6cfc0dde9a77324709c632/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L598-L606 ?

**Comment by bpasero** [comment]
@ramya-rao-a yes, I reported those at the same time I reported this one via https://github.com/Microsoft/vscode/issues/34425

**Comment by ramya-rao-a** [comment]
@bpasero 

There about 20 files that I need to run the checks on (this will definitely grow). Assuming there are about 20 paths in the PATH env variable, that is about 400 file checks to make in the worst case scenario

If I do all of this async, thats about 400 async calls made at the same time. This can have an adverse affect as well correct? Or it doesnt matter at all?

**Comment by bpasero** [comment]
@ramya-rao-a anything is better than doing it sync, especially if you are stat'ing 400 files which probably means that the user cannot do anything for a couple of 100ms.

We have [`IFileService.resolveFiles()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L184) that allows to batch resolve. 

my 2 cents: having to stat 400 files for a feature seems wrong to me, especially if this blocks a piece of UI from working properly. At the very minimum this should run in the background, maybe buffered and not block any UI from showing up.
