### ISSUE TITLE
[html] don't show closing tag proposal with "html.autoClosingTags": "false" 

### ISSUE THREAD

**Issue by thohe973** [Microsoft/vscode#34435]
- VSCode Version: 1.16.1
- OS Version: W10 Home

In previous versions you could write `<div>`, press enter and get a newline. Pressing enter in 1.16.1 now closes the tag.
Please bring back the old behaviour when autoClosingTags is set to false.

Steps to Reproduce:

1. Set html.autoClosingTags to false
2. Write `<div>`
3. Press enter
4. Enter should give a newline, not close the tag

**Comment by aeschli** [comment]
It's actually the `>` that closes the tag. It's a new feature in 1.16 and we want, for now, keep it enabled by default. Please set `"html.autoClosingTags": "false"` in your user settings.

**Comment by thohe973** [comment]
Yeah, but setting `"html.autoClosingTags": "false"` in the user settings doesnt revert back to the old behaviour.

When its off, you now get a intellisense suggestion of `</tag>` when you write `<tag>`.
So if I want a newline after my tag I now haft to press Esc to close the suggestion and then press enter.
In previous versions you didnt get a suggestion and could press enter directly.
I think when autoClosingTags is false you shouldnt get a suggestion of `</tag>`  just like in the older versions of vscode.

**Comment by str** [comment]
autoClosingTags should be on by default. It should respect if the user sets it's preferences to false, but should be true by default.

**Comment by amid11** [comment]
I can **confirm** this, even though I set `"html.autoClosingTags": false` in user settings, when I type `<div>` and hit **Enter** it returns a closed tag like `<div></div>`. but this time as an autocomplete option (I guess).
![peek 2017-10-02 20-58](https://user-images.githubusercontent.com/21957927/31090615-11c01550-a7b5-11e7-86a6-2c70fd9fe074.gif)

**Comment by hpg-mheck** [comment]
Yeah, I think whoever implemented this testing the in-line case, but not the multi-line case.  To be exceedingly clear:

**STEPS TO REPRODUCE:**

1. Set:

   "html.autoClosingTags": false

2. In an HTML editor tab, create the following text on exactly one line, verbatim, with no leading and no trailing spaces:

<span>stuff</span><span>things</span>

3. Position the cursor on that line, in the first column.

4. Press only these keys in exactly this order:
'<', 'b', 'u', 't', 't', 'o', 'n', '>', [RETURN]
for a total of exactly precisely nine (9) keystrokes with a tolerance of zero (0).

**EXPECTED EXACT RESULT:**
<button>
   <span>stuff</span><span>things</span>

_(assuming 3-space auto-indentation)_

**OBSERVED FAILURE:**
<button></button><span>stuff</span><span>things</span>

**Comment by hpg-mheck** [comment]
IMHO, options to disable features should NEVER be tested by people who like those features.  They always miss something.

**Comment by aeschli** [comment]
Fixed by no longer triggering code completion on `>`. The proposal is still there but is only seen when actively pressing `ctrl + space` after `>`
