### ISSUE TITLE
Breakpoint stopped event will cause all threads 'PAUSED ON BREAKPOINT'

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#34437]
- VSCode Version: 1.17.0-insider
![image](https://user-images.githubusercontent.com/14052197/30472455-07f1f96e-9a2f-11e7-97fd-5a1dcecb28a1.png)

When developing java debugger, it supports breakpoint hit event only suspends a single thread and keeps other threads running. So for breakpoint hit event, our java debugger will send a stopped DA event with allThreadsStopped flag as false. See `{"event":"stopped","body":{"threadId":1,"reason":"breakpoint","allThreadsStopped":false,"type":"stopped"},"seq":11,"type":"event"}`. But vscode shows all threads are `PAUSED ON BREAKPOINT`.
![image](https://user-images.githubusercontent.com/14052197/30472579-afd311cc-9a2f-11e7-8eb5-7424cd30c572.png)

I remember vscode works before, and it will only display `PAUSED ON BREAKPOINT` on the related thread. It seems a regression bug.

**Comment by isidorn** [comment]
@testforstephen I have pushed a fix for this, you can pick it up from a latest build here https://vscode-builds.azurewebsites.net/builds/insider
Let us know if it works for you
