### ISSUE TITLE
test.sh does not run extensions/git unit tests

### ISSUE THREAD

**Issue by keegancsmith** [Microsoft/vscode#34438]
I tried running the unit tests locally and it seems to not run them. I have to manually do `./node_modules/mocha/bin/mocha` from the git directory. I see some special casing for specific extensions in `scripts/test-integration.sh`. Just pointing this out, since this implies they are not run on CI.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
