### ISSUE TITLE
Enhancements to snippetSuggestions? Custom priorities?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#34433]
Hi,

it looks like the setting `editor.snippetSuggestions` is a little bit limited in the moment. It would be nice, if the priority of a snippet could be configured in a smarter way. Currently I have set it to `top` and have the following behaviour. 

Say I have a custom snippet called `imp`.

1) Now I have an empty file and type `i`.

- Nice to have: I'd like to see my custom snippet `imp` first.
- Current behaviour: I see the built in snippets (?) `if` and `ifelse` first.

2) Now I have a `import {} from 'foo'` and my cursor is inside `{}`. I expect `'foo'` to export a constant called `installer` and type `i`.

- Nice to have: I'd like to see my `installer` as an auto complete suggestion.
- Current behaviour: I see the built in snippets (?) `if` and `ifelse` and my custom `imp` snippet first, even though they are invalid here.

---

My current workaround: I prefix snippets with some char like `!` to avoid collisions :)

**Comment by jrieken** [comment]
> Current behaviour: I see the built in snippets (?) if and ifelse first.

We have fixed that in insiders, custom snippets should be ranked higher than extension snippets. What version are you using?

>  I see the built in snippets (?) if and ifelse and my custom imp snippet first, even though they are invalid here.

Yes. Snippets cannot control in what scopes that are applicable, see #22661

**Comment by donaldpipowitch** [comment]
> What version are you using?

Current stable.

> Yes. Snippets cannot control in what scopes that are applicable, see #22661

Sweet. Will follow this issue.

---

I guess I'll close this issue and create a new one, if I have a more specific request. Thanks. 👍
