### ISSUE TITLE
Giant window UI font size

### ISSUE THREAD

**Issue by darginyegor** [Microsoft/vscode#34443]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
json-tools|eri|1.0.2
ftp-simple|hum|0.5.6
Angular2|joh|2.7.0
ftp-sync|luk|0.3.3

(1 theme extensions excluded)

Font size in app menu bar and dropdown menus after updating to the last version became giant.
---

Steps to Reproduce:

1. Launch VS Code.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@darginyegor Can you perhaps add a screenshot ?

**Comment by darginyegor** [comment]
@alexandrudima
![2017-09-18 17-07-28](https://user-images.githubusercontent.com/22341230/30539441-31164900-9c94-11e7-850f-33a20f7a9757.png)

1920x1080...

**Comment by bpasero** [comment]
No plans of action here.
