### ISSUE TITLE
Cannot create multi-key bindings on linux with swapped CTRL and CAPS

### ISSUE THREAD

**Issue by imonmyown** [Microsoft/vscode#34447]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crystal-lang|fau|0.3.3
vscode-emacs-friendly|lfs|0.8.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Swap CTRL and CAPS LOCK keys either using `gnome-tweak-tool` or `xmodmap` as described e.g.
 [here](https://askubuntu.com/questions/363346/how-to-permanently-switch-caps-lock-and-esc).
2. Make sure the rebound keys work as expected in other applications.
2. Find a command you want to map to.
3. Try to map the command to e.g. Ctrl+x Ctrl+m

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@imonmyown There is a known issue on Linux. At https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/30737458-0a9e739c-9f87-11e7-960b-654a8853b681.png)

**Comment by imonmyown** [comment]
It worked! Thanks a lot @alexandrudima
