### ISSUE TITLE
terminal sizing issues

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#34444]
Elementary OS Freya (14.04)
Version 1.17.0-insider
Commit b0c0634339c6f64a5c7f08b56fe732fb9154d3c4
Date 2017-09-15T05:16:08.120Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

When initially start VSCode with the terminal view visible, it has sizing issues:
- Note the prompt goes over two lines
- Note the gray area on the right

![image](https://user-images.githubusercontent.com/6461412/30477928-38dd7140-9a0f-11e7-919c-07f49dc2203e.png)

- pressing enter fixes the rendering of the prompt
- the gray area on the right stays, also when resizing VSCode

**Comment by eamodio** [comment]
I am seeing the same on Windows 10

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34601
