### ISSUE TITLE
Sidebar shows the wrong catalogue

### ISSUE THREAD

**Issue by ChrisShen93** [Microsoft/vscode#34440]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

I was at branch dev and just enter some commonds like
```shell
git stash save "xxx"
git checkout dev-1
git checkout -b dev-2
```
All I have done was using git commonds like above, eventually I checkout the branch dev and then found the sidebar shows the wrong catalogue, some files and folders was missing.

It was fixed when I restart vscode, all missing files and folders appear again.

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
I'm glad everything worked out after a restart. If you can reproduce the issue let us know more details, a screenshot would also be helpful.

**Comment by ChrisShen93** [comment]
![vscode](https://user-images.githubusercontent.com/11674518/31759007-7893ccb4-b475-11e7-817f-be28f2a65b0c.png)
![finder](https://user-images.githubusercontent.com/11674518/31759008-7daa3800-b475-11e7-9f81-ab50973a97b7.png)

This appear again after I've used git stash save, git stash pop

**Comment by bpasero** [comment]
@ChrisShen93 when you refresh the explorer are the files showing up properly?
