### ISSUE TITLE
Allow navigation in Word Wrapped line

### ISSUE THREAD

**Issue by konmavrakis** [Microsoft/vscode#34448]
As you can see in the following image, in Sublime Text you can navigate the contents of **one line** when the Word Wrap option is enabled. When you have Word Wrap enabled in VS Code it won't navigate inside the wrapped line but instead it will change line.

![zobzpczsbl](https://user-images.githubusercontent.com/5990379/30478255-08a2f3b0-9a19-11e7-83af-d9c7afea7a94.gif)

- VSCode Version: 1.16.1
- OS Version: macOS 10.12.1

**Comment by konmavrakis** [comment]
**Update**: This works properly on my Macbook Air. This issue is on my iMac for some reason. Both Macs run on latest macOS and both editors on the latest update.

**Comment by konmavrakis** [comment]
I've found the issue. It looks like the issue happens when [Vim by vscodevim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) is enabled. 

Vim settings in ``settings.json``

```json
{
  "vim.easymotion": false,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.disableAnnoyingNeovimMessage": true,
}
```

**Comment by alexandrudima** [comment]
@konmavrakis It would be best to reach out to the extension author on their issue list.
