### ISSUE TITLE
Python UnicodeEncodeError in output window

### ISSUE THREAD

**Issue by sun1991** [Microsoft/vscode#3444]
`arabic_bytes=b'\xd9\x83\xd9\x84\xd8\xa7 \xd8\xa8\xd8\xaf\xd8\xa7\xd9\x8a\xd8\xa9 \xd9\x88\xd8\xa8\xd8\xaf\xd8\xa7\xd9\x8a\xd8\xa9'`
`print('%s' % arabic_bytes.decode('utf-8'))`

The output in output window is: 
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)`

Is output window support ASCII only? Or where can I change it?

**Comment by sun1991** [comment]
version 0.10.8 on win7 64bit

**Comment by dbaeumer** [comment]
Dups #3550
