### ISSUE TITLE
Open editors in the active editor group if now viewcolumn is specified

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34459]
Steps to Reproduce:

1. open a diff editor (from git) in the second or third view column
2. trigger the editor title action "Open File"
3. :bug: the file opens in the first view column

I think the Git extension [is doing the right thing](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L368) for this command by setting the view column to be the one of the active editor, which in this case is the diff editor. However, it looks like the view column is always `undefined` for diff editors at least. 

Tracing this down the stack, it looks like [`MainThreadDocumentsAndEditors#_onDelta`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadDocumentsAndEditors.ts#L274) is called with the left hand side of the diff editor as well as the right hand side (both instance of `CodeEditor`). As such, the method [`_findEditorPosition`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadDocumentsAndEditors.ts#L357) will not function properly because it [compares](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadEditor.ts#L318) the `CodeEditor` to the `DiffEditorWidget` which is opened.

**Comment by jrieken** [comment]
> However, it looks like the view column is always undefined for diff editors at least.

Yes, that how it is defined because otherwise both editors will have the same view column which is a little bogus. The `viewColumn` is just a weak hint, also because it will be undefined for other editors, embedded, output etc. Unsure what to do here, unsure if two editors should have the same view column...

**Comment by bpasero** [comment]
Interestingly this would be not much of an issue if the `viewColumn` by default would not be set to `ViewColumn.ONE` from the extension host. If `undefined`, the workbench is always picking the column that is currently active. But I guess that would be a breaking change, at least from the docs:

![image](https://user-images.githubusercontent.com/900690/30485182-f1658d16-9a2c-11e7-8898-5c54189d4a83.png)

**Comment by jrieken** [comment]
Yeah, I think we can always tweak that. And more than you want that: https://github.com/Microsoft/vscode/pull/27409 I am just not yet sure about the implementations...

**Comment by bpasero** [comment]
@jrieken yeah it looks like https://github.com/Microsoft/vscode/issues/27408 is the git diff issue.

**Comment by bpasero** [comment]
I pushed a change to open an editor in the currently active editor group if no group is provided. I think this plays much better with the new grid system. As for other impact the grid should have on extensions API I have opened https://github.com/Microsoft/vscode/issues/51001
