### ISSUE TITLE
Jump to line from terminal (vim-like)

### ISSUE THREAD

**Issue by DeadNumbers** [Microsoft/vscode#34453]
Hello! It would be nice if you added the jump to the line as Vim-like `$ code file.c +1337`

**Comment by rcjsuen** [comment]
@DeadNumbers This feature should already work.

```
$ code -g file.c:1337
```
See [here](https://code.visualstudio.com/docs/editor/command-line) for more details or use `code -h` to check the CLI's help output.

**Comment by DeadNumbers** [comment]
@rcjsuen Thanks
