### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by PacmanLazy** [Microsoft/vscode#34452]
Is it normal?!!
![vscode](https://user-images.githubusercontent.com/11561042/30479076-43653032-9a1c-11e7-9eab-9cdaf92aa68c.png)

**Comment by znk** [comment]
Sadly, it is. vscode is RAM-heavy, having a "browser-like" under the hood. It also depends on the size of files you are working on. From my experience, extensions tend to have little impact.

**Comment by znk** [comment]
You may use these command lines to investigate and collect more factual details.

Performance |  
-- | --
-p, --performance | Start with the Developer: Startup Performance command enabled.
--disable-gpu | Disable GPU hardware acceleration.
--verbose | Print verbose output (implies --wait).
--prof-startup | Run CPU profiler during startup.

**Comment by alexandrudima** [comment]
@PacmanLazy what were you doing that caused this?

Are you on the stable channel or the insiders channel ?

Which process is this ? (You can use process explorer and hover over the process to capture the command line arguments of the process such that we can identify which one it is)

**Comment by PacmanLazy** [comment]
@alexandrudima I use stable build of vscode. Only one php-file with pretty simple script was loaded. Also I used xdebug, I noticed that accidently, when some process took more than 1GB of RAM. It was some unsual behavior. Some time later it returned to normal state. Usually it takes 60-90Mb. It is hard to check again, cause it happended first time

**Comment by alexandrudima** [comment]
@PacmanLazy 

VSCode should definitely not be consuming 1GB of RAM for showing/editing a php file.

Please keep an eye on this and if you notice it again, do let us know, maybe some pattern will become clear out of which we can get some steps.

**Comment by PacmanLazy** [comment]
![image](https://user-images.githubusercontent.com/11561042/30772292-88f7493c-a061-11e7-856e-01cf7cbd1b8d.png)
It happened again

**Comment by alexandrudima** [comment]
@PacmanLazy Were you debugging, were you simply editing? Can you please find some steps to help us reproduce?

**Comment by PacmanLazy** [comment]
I was editing php code and debugging it. That was all, nothing difficult..

2017-09-25 12:16 GMT+03:00 Alexandru Dima <notifications@github.com>:

**Comment by znk** [comment]
@PacmanLazy You have to provide metrics and details (steps to follow, environments...)

**Comment by roblourens** [comment]
I don't think there is enough actionable info here, but see the doc for troubleshooting these issues if it is still happening: https://github.com/Microsoft/vscode/wiki/Performance-Issues
