### ISSUE TITLE
Shortcut ctrl+del doesn't delete trailing space

### ISSUE THREAD

**Issue by grokky1** [Microsoft/vscode#34456]
- VSCode Version: 1.16.0
- OS Version: Win10 x64

1. I want to edit "foo bar baz" to "foo baz"
2. In most editors, and in Visual Studio too, I would position cursor before "bar", and press ctrl+del, which would delete "bar" as well as the space after it.
3. But in VSCode it deletes "bar" only, and leaves the space, which I must then delete as well.

Very frustrating as it's not the same as in VS or the 99% of IDEs and editors out there. Even here in GitHub it works that way, try it for yourself.

**Comment by alexandrudima** [comment]
Please see https://github.com/Microsoft/vscode/issues/832#issuecomment-197827616

To get VS-style Ctrl+Delete, edit your `keybindings.json` and add:

```
{ "key":"ctrl+delete",       "command":"deleteWordStartRight",       "when":"editorTextFocus" }
```

This will overwrite the default:

```
{ "key":"ctrl+delete",       "command":"deleteWordRight",            "when":"editorTextFocus" }
```

**Comment by grokky1** [comment]
👍
