### ISSUE TITLE
Shortcuts ctrl+left and ctrl+right don't move cursor to expected positions

### ISSUE THREAD

**Issue by grokky1** [Microsoft/vscode#34457]
- VSCode Version: 1.16.0
- OS Version: Win10 x64

1. I want to move cursor between words using ctrl+left and ctrl+right
2. In most editors, and in Visual Studio too, cursor would move to the left or right and position itself before the previous/next word's first character.
3. But in VSCode it does not work that way - it moves to first/last character of the same word.

Very frustrating as it's not the same as in VS or the 99% of IDEs and editors out there. Even here in GitHub it works that way, try it for yourself.

**Comment by alexandrudima** [comment]
To control this behaviour and get VS-style Ctrl+Right, please edit your `keybindings.json` and add:

```
{ "key":"ctrl+right",       "command":"cursorWordStartRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordStartRightSelect", "when":"editorTextFocus" }
```

This will overwrite the defaults:

```
{ "key":"ctrl+right",       "command":"cursorWordEndRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordEndRightSelect", "when":"editorTextFocus" }
```

You can also use a keymap extension like the Visual Studio keymap extension.

**Comment by grokky1** [comment]
@alexandrudima Awesome that works... thanks! 😄

For anyone else reading this, the same can be done for <kbd>ctrl+left</kbd> and <kbd>ctrl+shift+left</kbd>!
