### ISSUE TITLE
"Save All" keyboard shortcut on Linux

### ISSUE THREAD

**Issue by blendsdk** [microsoft/vscode#34455]
Please add the "Save All" keyboard shortcut on linux

![screen shot 2017-09-15 at 13 40 21](https://user-images.githubusercontent.com/5524595/30480757-b3a939de-9a1b-11e7-9a16-4380ee6e4a92.png)

**Comment by alexandrudima** [comment]
The action doesn't ship with a default keybinding for linux.

@blendsdk you can define a keybinding for save all via the keybindings UI at ctrl+k ctrl+s

**Comment by jhasse** [comment]
<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd> would a good fit IMO.

**Comment by blendsdk** [comment]
> On 19 Sep 2017, at 09:15, Jan Niklas Hasse <notifications@github.com> wrote:
> 
> Ctrl+Alt+S would a good fit IMO.
> 
> —
> 

I also think CTRL+ALT+S is a good option.

**Comment by jhasse** [comment]
I think the 20 upvotes for such a minor thing won't happen. But the fix is also trivial: #89071 
Can someone have a quick look? :)
