### ISSUE TITLE
error xhr failed when installing extentions in visual studio code 2017

### ISSUE THREAD

**Issue by alank90** [Microsoft/vscode#34460]
- VSCode Version:2017
- OS Version:Windows 10

Steps to Reproduce:

1.  Install an extension in VS code 
2.

Reproduces without extensions: Yes/No

0         down vote          favorite | Just installed VS Code 2017 and when I try to install any extensions I  get popup Error XHR Failed. Tried googling but cant find any clues.  Anybody run across this?
-- | --

**Comment by dsneddon** [comment]
This is a duplicate of issue 34385.

**Comment by alank90** [comment]
I'm sorry but the issue you point to says it cleared up on its own. Not much help to me seeing my problem persists.
