### ISSUE TITLE
 Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#34465]
Issue Id: <b>b91a0348-529d-3290-6f29-42d1ad14f63b</b><br /><br />*Versions* <br />- 1.16.0<br />*Stack* <br />TypeError: Cannot read property 'layout' of undefined<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L374:12 (layout)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L374:12 (layout))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L319:67 (layoutBody)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L319:67 (layoutBody))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/base/browser/ui/inputbox/inputBox.ts#L480:27 (fire)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/browser/ui/inputbox/inputBox.ts#L480:27 (fire))<br />[/vs/base/browser/ui/inputbox/inputBox.ts#L435:7 (layout)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/browser/ui/inputbox/inputBox.ts#L435:7 (layout))<br />[/vs/base/browser/ui/inputbox/inputBox.ts#L419:7 (updateMirror)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/browser/ui/inputbox/inputBox.ts#L419:7 (updateMirror))<br />[/vs/base/browser/ui/inputbox/inputBox.ts#L234:8 (onValueChange)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/browser/ui/inputbox/inputBox.ts#L234:8 (onValueChange))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L462:24 (this)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L462:24 (this))<br />[/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L330:7 (updateInputBox)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L330:7 (updateInputBox))<br />

**Comment by joaomoreno** [comment]
Code has changed considerably in this area.
