### ISSUE TITLE
Stale launch configuration read by extension

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#34461]
- VSCode Version: 1.16.1
- OS Version: Any

In our extension we have an action which generates launch.json file. We just use fs.writeFile and place the proper content there.
Up until vscode 1.16 if you press F5 after launch.json has been generated, it will pick it up and execute whatever is specified there.
Starting from version 1.16 VsCode "does not see" launch.json the first time you press F5 and only succeeds the next time.

Steps to Reproduce:
1. Clone the extension https://github.com/dennisfrostlander/vscode-launch-bug
2. npm install
3. Open the project and run extension with F5.
4. In the extension host, open an empty folder.
5. Run the command "Hello world". It will generate valid launch.json. Inspect the file to make sure it's there.
6. In the extension host, press F5. VSCode will show debugger selection list although the launch.json exists.
7. Press cancel and F5 again, this time VSCode will attempt to start a debugger.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please try with latest vscode insiders, I think i have fixed this issue 
https://code.visualstudio.com/insiders

**Comment by dennisfrostlander** [comment]
Thanks, it's fixed indeed.

**Comment by dennisfrostlander** [comment]
Any chance you guys are planning another 1.16 update? Or should we expect this fix only next month?

**Comment by isidorn** [comment]
@dennisfrostlander next monhts. In the meantime you can use vscode insiders

**Comment by dennisfrostlander** [comment]
@isidorn Did you guys by any chance made more changes to how debug configurations are read from launch.json?
In today's build of insiders, when the extension generates the launch.json file, vscode does not see it _at first_. When I invoke another action in the extension, then the configurations can be seen again.

On the screenshot below you can see that extension host (on the right) has a valid launch.json, however, when the code reads the launch configuration (on the left), the value of _configurations_ is undefined. 

I can try to prepare a full repro if needed.

![image](https://user-images.githubusercontent.com/16953692/30645199-3951525e-9e15-11e7-9cd1-b395446b8fec.png)

**Comment by isidorn** [comment]
@dennisfrostlander I can not reproduce this on my mac with latest insiders. Creating a repository on github for which you can always see this would be helpful.

@sandy081 might have changed how we are reading configurations.
I do not believe this is debug specific.

**Comment by sandy081** [comment]
There are not any changes done in Configuration. As @isidorn asked having a repo that has this issue would be helpful.

**Comment by dennisfrostlander** [comment]
@sandy081 Ok, I've got another repro. Not exactly the same as on the previous screenshot, but it shows that reading launch.json after it was created does not always work.

Steps to Reproduce:
1. Clone the extension https://github.com/dennisfrostlander/vscode-launch-bug
2. npm install
3. Open the project and run extension with F5.
4. In the extension host, open an empty folder.
5. Run the command "Hello world". It will generate valid launch.json. 
After generating the file, the extension reads it and shows the message:
`typeof configurations, expected: object, actual: object`
So far so good.
6. Delete launch.json file.
7. Run the command "Hello world" again.
This time the message is:
`typeof configurations, expected: object, actual: undefined`

The code which does all of this is pretty simple:
```javascript
        fs.writeFileSync(launchFile, contents, {encoding: 'utf-8'});

        vscode.workspace.openTextDocument(launchFile)
            .then(d => vscode.window.showTextDocument(d))
            .then(() => {
                let configurations = vscode.workspace.getConfiguration("launch").get("configurations");
                vscode.window.showInformationMessage('typeof configurations, expected: object, actual: ' + (typeof configurations));
            });
```

**Comment by isidorn** [comment]
@dennisfrostlander thanks for nice steps.
Yes I can reproduce this. My hunch is that configuraiton service is reading some stale state, since the issue is that `getConfiguraiont("launch")` returns `undefined`

Reopening and assigning to @sandy081

**Comment by sandy081** [comment]
This is a timing issue because User is creating/writing into the file directly. We listen to the file events (with some interval) and update the configuration which has to travel back to extension host. Above code is getting hit in this time interval where the config on the extension host is not yet updated. Passing the execution at the place where you get the configuration also does not help because you are pausing the complete extension host and the model on the extension host is not yet updated. Right way to do this is

```typescript
let contents = {
			"version": "0.2.0",
			"configurations": [
				{
					"name": "Launch Extension",
					"type": "extensionHost",
					"request": "launch",
					"runtimeExecutable": "node"

				}
			]
		};
		await vscode.workspace.getConfiguration().update('launch', contents);
		vscode.workspace.openTextDocument(path.join(vscode.workspace.workspaceFolders[0].uri.fsPath, '.vscode', 'launch.json'))
			.then(d => vscode.window.showTextDocument(d))
			.then(() => {
				let configurations = vscode.workspace.getConfiguration("launch").get("configurations");
				vscode.window.showInformationMessage('typeof configurations, expected: object, actual: ' + (typeof configurations));
			});
```
