### ISSUE TITLE
 Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#34469]
Issue Id: <b>2c2f786e-5f02-6be5-208a-1bae0cc432c0</b><br /><br />*Versions* <br />- 1.17.0-insider (9/13/2017 5:36:40 AM)<br />-  128a4e3640c5375f7b0bc1cfd37f626481b1386f<br />-  2c385b98066eebb8e39dfd98b1fcb8cc254196b6<br />*Stack* <br />Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.<br />    at CharAtlasGenerator.generate (\node_modules\xterm\lib\renderer\CharAtlas.js:115:44) <no sourcemaps><br />    at Object.acquireCharAtlas (\node_modules\xterm\lib\renderer\CharAtlas.js:34:27) <no sourcemaps><br />    at BackgroundRenderLayer.BaseRenderLayer._refreshCharAtlas (\node_modules\xterm\lib\renderer\BaseRenderLayer.js:28:34) <no sourcemaps><br />    at BackgroundRenderLayer.BaseRenderLayer.onThemeChanged (\node_modules\xterm\lib\renderer\BaseRenderLayer.js:23:14) <no sourcemaps><br />    at \node_modules\xterm\lib\renderer\Renderer.js:58:15 <no sourcemaps><br />    at Array.forEach (native)<br />    at Renderer.setTheme (\node_modules\xterm\lib\renderer\Renderer.js:57:28) <no sourcemaps><br />    at Terminal._setTheme (\node_modules\xterm\lib\Terminal.js:388:36) <no sourcemaps><br />    at \node_modules\xterm\lib\Terminal.js:379:23 <no sourcemaps><br />

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34493
