### ISSUE TITLE
 disposed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#34463]
Issue Id: <b>63425441-7fe5-0468-91fa-08da20793ccd</b><br /><br />*Versions* <br />- 1.16.0<br />-  1452d0a8f75cc7be3f8ab735af3a198a0f11aff6<br />*Stack* <br />Error: disposed<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L98:29](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/parts/ipc/node/ipc.cp.ts#L98:29)<br />[/vs/base/parts/ipc/node/ipc.cp.ts#L92:38 (request)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/parts/ipc/node/ipc.cp.ts#L92:38 (request))<br />[/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 (call)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/platform/telemetry/common/telemetryIpc.ts#L37:22 (call))<br />[/vs/platform/telemetry/common/telemetryService.ts#L115:18 (log)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/platform/telemetry/common/telemetryService.ts#L115:18 (log))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/platform/telemetry/common/telemetryService.ts#L102:32 (then)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/platform/telemetry/common/telemetryService.ts#L102:32 (then))<br />[/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L169:34 (publicLog)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L169:34 (publicLog))<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1041:0 (_run)](https://github.com/microsoft/vscode/blob/787b31c0474e6165390b5a5989c9619e3e16f953/src/vs/base/common/winjs.base.raw.js#L1041:0 (_run))<br />

**Comment by isidorn** [comment]
This is fine, closing. Maybe the adapter could report more data with this error
