### ISSUE TITLE
Window crash after exec two internal powershell terminals

### ISSUE THREAD

**Issue by mikicegal14** [Microsoft/vscode#34472]
- VSCode Version: 1.16.1
- OS Version: Windows 10 Pro Insider Preview 1703 (16281.1000

Steps to Reproduce:

1.Open one terminal and exec gulp (gulp watch)
2.Open other terminal and exec sass 
3.Vscode crash
(Maybe not crash inmediatly)

Reproduces without extensions: **Yes**/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
