### ISSUE TITLE
Auto-bullet

### ISSUE THREAD

**Issue by macdonaldster** [Microsoft/vscode#34474]
Feature request: when I am writing a bulleted list (e.g. in Markdown or plain text) and hit enter I would like the editor to continue the line prefix.

Example:

* bullet 1
* bullet 2
[hit enter]
* [new line has bullet/spaces mimicking lines above]

Another key feature is if you hit enter on an otherwise unused bullet it will get out of list mode. I think you could do this as an extension, as well, but I haven't found one that does this.

**Comment by yaomtc** [comment]
I would add to this that it should auto-insert for numbered lists, as well. I don't mind if it's an option disabled by default.

**Comment by alexandrudima** [comment]
@mjbvz This could perhaps be implemented via `onEnterRules`

**Comment by mjbvz** [comment]
Duplicate of #14010
