### ISSUE TITLE
VSCode not responding when I change 4k files at once in the workspace.

### ISSUE THREAD

**Issue by Telokis** [Microsoft/vscode#34478]
- VSCode Version: 1.16.1
- OS Version: Windows 7 64bits

Steps to Reproduce:
1. Have VSCode open with a workspace loaded
2. Run a script (from outside VSCode) that writes 4000 files very quickly
3. The window hangs out and finally asks me to "reopen" it.

Reproduces without extensions: No.

Here are my extensions :

```christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
dzannotti.vscode-babel-coloring
eg2.vscode-npm-script
EQuimper.react-native-react-redux
fknop.vscode-npm
joelday.docthis
msjsdiag.debugger-for-chrome
robertohuertasm.vscode-icons
Shan.code-settings-sync
shinnn.stylelint
slevesque.vscode-hexdump
steoates.autoimport
timothymclane.react-redux-es6-snippets
xabikos.ReactSnippets```

**Comment by mjbvz** [comment]
What types of files are you changing? Does this still reproduce if you disable all extensions?
