### ISSUE TITLE
[decorators] After decoration can break font ligatures

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#34473]
- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:58:39.362Z)
- OS Version: Windows_NT x64 10.0.16288
---

Originally from https://github.com/eamodio/vscode-gitlens/issues/141

![image](https://user-images.githubusercontent.com/7287076/30472072-00e58ae6-99f3-11e7-9da7-14af536c35ca.gif)

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
This has been fixed in the meantime via 2217a39b3ee4c1ebf0516a5f52d5561a6825778c
