### ISSUE TITLE
Ability (api or command) to paste into the terminal

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#34479]
I've been thinking about some possible new features in GitLens now that there is a repository visualization. Like more advanced commands, rebasing, etc. And while some of them could be just fine to run on their own, others might require more terminal interaction or something like that.

So I was thinking if there was a way to paste commands into the terminal (NOT run them), it could help some of those scenarios, and/or help people learn the command line commands of certain operations easier -- which could be valuable outside git or anything like that.

**Comment by Tyriar** [comment]
@eamodio I assume you've seen the terminal API? https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameterminalaspan-classcodeitem-id1032terminalspan

`term.sendText('foo', false)` will send the text to the terminal, as if it was typed and not follow it with a new line (ie. not run it).

**Comment by eamodio** [comment]
@Tyriar awesome! I'll check it out -- thank you!
