### ISSUE TITLE
TypeScript Extract Function is Removing All Blank Lines

### ISSUE THREAD

**Issue by infinisuite** [Microsoft/vscode#34485]
- VSCode Version: Version 1.16.1 (1.16.1)
- OS Version: OSX: 10.12.6 (16G29)

Steps to Reproduce:

1. Highlight any TypeScript code
2. Extract to function

All blank lines have been removed.

**Comment by infinisuite** [comment]
Also, all 'else' and 'else if' statements are put on a new line. For example:

```
if (true) {
} else if (x) {
}
```
becomes this after being extracted:

```
if (true) {
} 
else if (x) {
}
```

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/18091

Should be fixed once we pick up the next version of TypeScript
