### ISSUE TITLE
Warn: command 'workbench.action.showNextWindowTab' not found

### ISSUE THREAD

**Issue by NigelKibodeaux** [Microsoft/vscode#34489]
- VSCode Version: 1.16.0 
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Set `"window.nativeTabs": true` in your user settings and restart vscode
2. Update keybindings.json file to include a shortcut for `workbench.action.showNextWindowTab`
3. Attempt to use the shortcut (see screenshot for keybindings.json file and warning banner)

Reproduces without extensions: Yes

![screen shot 2017-09-15 at 10 45 04 am](https://user-images.githubusercontent.com/408692/30498387-05469656-9a03-11e7-8d52-3690762f388a.png)

**Comment by bpasero** [comment]
@NigelKibodeaux you will need to use our insider build to get this. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
