### ISSUE TITLE
[html] support script type=module

### ISSUE THREAD

**Issue by ValentineStone** [Microsoft/vscode#34488]
- VSCode Version: 1.16.1
- OS Version: Windows 10 ( Creators Update )

Steps to Reproduce:

1. Create new file & save it as .html
2. Open file in VSCode and add some content like so:
```
<script type="module">
'line1';
'line2';
"any multiline content: functions 'n stuff...";
</script>
```
3. Right click on the editor and select `Format Document` from the context menu
4. You should get some like this:
```
<script type="module">
  'line1'; 'line2'; "any multiline content: functions 'n stuff...";
</script>
```
5. As you can see, auto-formatter puts everything on one line :/

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I see the same behavior...

**Comment by aeschli** [comment]
Maybe someone else can verify as well...

**Comment by roblourens** [comment]
Some extension. But I can't figure out which one...
