### ISSUE TITLE
workspaceContains starts a search over full workspace, including .git/, node_modules/

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34487]
Since https://github.com/Microsoft/vscode/commit/10c0610a6dafc5d7932126678f660e77c895e65c

This could be very expensive. We should include the exclude settings, or hardcode an exclusion to a few folders.

**Comment by roblourens** [comment]
Also, we could batch workspaceContains searches into a single search. For example the C# extension will spawn 6 ripgrep processes.

**Comment by jrieken** [comment]
> We should include the exclude settings, or hardcode an exclusion to a few folders.

So, how do you then active on `.git/HEAD`?

**Comment by roblourens** [comment]
Maybe add some smartness to search .git/ or node_modules/ if it's explicitly mentioned in the `workspaceContains:` search glob?

**Comment by alexandrudima** [comment]
I will not push any change that changes the semantics. But I agree, if an extension has multiple glob patterns, we can invoke `DiskSearch.search` at most once per extension.

**Comment by roblourens** [comment]
Thanks, that should help. Opening #34711 to track other strategies

**Comment by roblourens** [comment]
Now I see it spawning some rg processes with no glob args at all. I think there might be a bug. Debugging...

**Comment by alexandrudima** [comment]
@roblourens Nice catch! Yes, it can happen if an extension uses strict file names.
