### ISSUE TITLE
TypeScript extract function/method

### ISSUE THREAD

**Issue by gozno42** [Microsoft/vscode#34482]
new refactoring options (extract method & function) are not available unless you use VSCode's TypeScript version.  when i use my workspace's version of TypeScript (2.3.3) the refactoring options are missing.

- VSCode Version: 1.16.1 x64
- OS Version: Windows 7

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Yes, that version of TypeScript does not support these operations. You need to use Typescript 2.5+ in your workspace to enable extract method

**Comment by yashv** [comment]
I'm using TS v2.5+ and the latest VS Code version but still don't see the options. Is there any other requirement to see the 'Extract Methods' ? 
(also, my ts config has compilerOptions": {   "target": "es5", ...})
