### ISSUE TITLE
[json] Markdown in hovers (descriptions from schema)

### ISSUE THREAD

**Issue by vojtechhabarta** [Microsoft/vscode#34498]
I have generated JSON schema which has lots of long markdown descriptions. Currently VS Code displays descriptions from schema as plain text. It would great if schema could somehow indicate that descriptions use markdown and VS Code would render it properly.

**Comment by aeschli** [comment]
We would need a new property for that, other than 'description'. It would be VSCode specific, something like 'makedDescription'. 
Although it's not explicitly stated in the [JSON spec on `description`](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.2), but I believe the idea is that `title` and `descriptions` are plain text in order to be used by a variety of tools.

**Comment by vojtechhabarta** [comment]
New property (`markedDescription`) would be great.
I generate the schema so it doesn't matter if the property is `description` or something else.
Thanks for considering this feature.

**Comment by vojtechhabarta** [comment]
Thanks 👍

**Comment by aeschli** [comment]
To verify:
Create foo.schema.json and foo.json next to each other. In foo.json, hover over 'bar' and verify that it's markdown.
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "bar": {
            "markdownDescription": "**Hello** _world_"
        }
    }
}
```
foo.json
```
{
	"$schema": "./foo.schema.json",
	"bar":  ""       
}  
```

**Comment by vojtechhabarta** [comment]
It works for me in insider build, I tried it with my schema.
It also worked when I modified your example schema:
``` json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "bar": {
            "markdownDescription": "**Hello** _world_"
        },
        "baz": {
            "enum": [
                "Foo"
            ],
            "markdownEnumDescriptions": [
                "It can only be **Foo**"
            ]
        }
    }
}
```
Thanks.
