### ISSUE TITLE
cannot read property 'resourceJSON' of null

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34490]
MacOS
Version 1.17.0-insider (1.17.0-insider) 
b0c0634339c6f64a5c7f08b56fe732fb9154d3c4

scaffold a new extension
run the extension
in the [Extension Development Host] press Cmd+P to bring up the command palette

Result: error: cannot read property 'resourceJSON' of null

Console from Extension Development Host:

``` console
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 Cannot read property 'resourceJSON' of null: TypeError: Cannot read property 'resourceJSON' of null
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:191627
    at t.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1087764)
    at e.deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:191577)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2490886
    at Array.map (native)
    at t.loadHistory (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2490702)
    at t.ensureHistoryLoaded (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2490029)
    at t.handleEditorEventInHistory (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2485825)
    at t.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2485639)
    at t.e.onEditorsChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2481621)
```

`F1` works fine, I can bring up the command palette.

**Comment by alexandrudima** [comment]
I could find references of `resourceJSON` in some serialized file inputs interfaces...

**Comment by bpasero** [comment]
Not possible from the [source code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L710), but I added paranoia code even though I cannot explain this.

**Comment by kumarharsh** [comment]
+1 happening to me too. I was working on my extension (say, C:\Extension), and to test it out, I opened my usual work directory (D:\Work) in the EDH. I later closed the EDH, and in the main vscode-insider window, I switched to the same work directory (D:\Work), and I kept getting this error. And now, even after restarting vscode and even updating it to a new version, I just keep getting this error, in effect, I can't use vscode-insider now :/

The error:
![image](https://user-images.githubusercontent.com/760112/30632377-8069901c-9e05-11e7-9298-d105b29c8514.png)

The "Ctrl+P" palette is empty:
![image](https://user-images.githubusercontent.com/760112/30632385-85ea3690-9e05-11e7-9765-5ea92dce68ee.png)

**Comment by bpasero** [comment]
@kumarharsh you are still seeing this in todays insider build?

**Comment by kumarharsh** [comment]
Yes. I posted my reply only after verifying that it didn't work after updating. Never saw this bug coming, and thought it'd be trivial to fix by just reloading window. Boy, was I wrong 😢  !

Using the stable channel for now.

**Comment by bpasero** [comment]
@kumarharsh can you show me a screenshot of your about dialog? also, can you send me the crash from the developer console (Help > Developer Console)

**Comment by kumarharsh** [comment]
![image](https://user-images.githubusercontent.com/760112/30633769-7f232556-9e0a-11e7-8873-221243a77e8b.png)

Opening the developer tools is hanging my vscode everytime, so can't see the whole trace... This is all I can get...
![image](https://user-images.githubusercontent.com/760112/30633879-efc12b32-9e0a-11e7-9004-d1dabfc797c0.png)

**Comment by bpasero** [comment]
@kumarharsh thanks, I am working on a fix and will ping you to give it a try.

**Comment by kumarharsh** [comment]
@bpasero did your changes get rolled up into a release? My editor always says "No updates available" when I check for updates. The version is the same as in the screenshot above.

**Comment by bpasero** [comment]
@kumarharsh we are currently not able to provide updates because our signing service does not run, please be patient for our next stable release.

**Comment by kumarharsh** [comment]
I'm patient :-) I asked because I was concerned whether the update service was also not broken.

> next stable release.
So, the insider builds are stopped until october?
