### ISSUE TITLE
Current function name as a launch variable

### ISSUE THREAD

**Issue by p0lar-bear** [Microsoft/vscode#34496]
Out of all the variables I see in the launch configuration, I'm surprised there isn't one that puts in either the name of the function/method that the cursor is at, or the contents of the editor's selected text. Use case being, I use launch.json in my PHP-based project to run PHPUnit in debug mode. I can currently launch specific test files, but I can't narrow it down to a single test function. I'm aware of the PHPUnit extension, and that's great for running specific tests, but I'd rather not mess with my environment variables to do debugging and rely on other team members to be able to do it as well.

This may be a niche case, but maybe this could be useful for other cases?

**Comment by weinand** [comment]
This functionality can be easily implemented as an extension.

**Comment by isidorn** [comment]
@weinand thanks for pointing that out. Due to that closing this, we try not to keep extension candidates open
