### ISSUE TITLE
Terminal starts with the wrong font

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34494]
Only reproes with `"editor.fontFamily": "Fira Code"`

- Open a new VS Code window
- Open the terminal, see that it's a different font
- Launch a new terminal, see that the font is correct

Switching back and forth, 1 is incorrect, 2 is correct:

![sep-15-2017 12-13-54](https://user-images.githubusercontent.com/323878/30499483-88bd9e60-9a0f-11e7-8fab-d0f69fa76bef.gif)

**Comment by josiahbgrace** [comment]
Exact same issue on my end. Except the font isn't fixed for new terminals

**Comment by Tyriar** [comment]
I can't seem to repro on:

- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:44:11.087Z)
- OS Version: Darwin x64 14.5.0

**Comment by roblourens** [comment]
That's a day old, I have

b0c0634339c6f64a5c7f08b56fe732fb9154d3c4

2017-09-15T05:07:10.475Z

It started in that build
