### ISSUE TITLE
JavaScript - Salsa Preview doesn't work at all

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#3449]
Hi,

I tried a code mentioned at [Updates](http://code.visualstudio.com/Updates) web and IntelliSense doesn't work. Do I need to enable some extension, or do something else?

I tried this:
```js
function Person(name) {
    this.name = name;
}

Person.prototype.greet = function (params) {
};

var per = new Person('foo');
per.
```

...and got "No suggestions." after `per.`.

I just need to know whether it should work or not, because it didn't work so I started to write an extension which handles that ;)

Thanks!

-----
Ubuntu 14.04 LTS
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:00:07.223Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by joaomoreno** [comment]
I don't understand which version of Code you have. When you go to the `About` dialog, what version is there?

**Comment by obrejla** [comment]
Recenty I updated my previous post, it's there...

Ubuntu 14.04 LTS
Version 0.10.8
Commit db71ac6
Date 2016-02-05T10:00:07.223Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by joaomoreno** [comment]
Salsa will only arrive with `0.10.10`, coming soon. This use case is not supported before Salsa.

**Comment by obrejla** [comment]
Oki, that explains everythig...except...why is it in `0.10.8 (January 2016)` update section?? :-)

**Comment by joaomoreno** [comment]
I have to agree that it is not very obvious (ping @waderyan @gregvanl) but if you scroll down there is a section called **Enabling Salsa**.

**Comment by obrejla** [comment]
Thanks!
