### ISSUE TITLE
Using Search adds an extra space at the top of the editor

### ISSUE THREAD

**Issue by eliashdezr** [Microsoft/vscode#34495]
- VSCode Version: 1.16.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open any file and stay at the top
2. Press 'CTRL + F' (search)

Reproduces without extensions: Yes

![vscode_search_extra_space](https://user-images.githubusercontent.com/6153607/30499748-5eeb6fba-9a21-11e7-8c09-cac6d2a8f147.gif)

With `code --disable-extensions`
![vscode_search_extra_space_2](https://user-images.githubusercontent.com/6153607/30499779-7929ea14-9a21-11e7-9182-61a6cac59f57.gif)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28390
