### ISSUE TITLE
Editing a simple C# program always shows errors (despite compiling fine)

### ISSUE THREAD

**Issue by Someguy123** [Microsoft/vscode#345]
Example:

![Image of Code](https://i.imgur.com/meqxJMl.png)

    The type or namespace 'Convert' does not exist in the namespace 'System' (are you missing an assembly reference?)

and:

    'Console' does not contain a definition for 'Clear'

My `project.json` is as follows:

		{
			"dependencies": {
		
			},
			"commands": {
				"ConsoleApp": "ConsoleApp"
			},
			"frameworks": {
				"dnx451": { },
				"dnxcore50": {
					"dependencies": {
						"System.Console": "4.0.0-beta-*"
					}
				}
			}
		}

VS Code Version: `0.10.1` running on `OS X (Yosemite) 10.10.5`

**Comment by jrieken** [comment]
@Someguy123 Can you hit F8 on the compile error and tell me what projects they are reported for? Your project.json refers to coreclr and desktop clr and I am unsure the symbols you are asking for ship with core clr

**Comment by Someguy123** [comment]
@jrieken I'm using mono to compile my program.

Here's the results of F8: 
https://imgur.com/a/FA9ai

**Comment by jrieken** [comment]
The problem is that some symbols aren't part of `dnxcore50` - the error message lists only that project, not `dnx451` You need more dependencies in the `frameworks.dnxcore50.dependencies`-section

**Comment by Someguy123** [comment]
@jrieken What dependencies though? The only components being used are System.Console and System.Convert (of which I cannot find a package for on nuGet). The closest thing I found for System.Convert is this: https://www.nuget.org/packages/runtime.osx.10.10.System.Runtime.Extensions/4.0.11-beta-23516 - After adding the package, Intellisense still can't see Convert as a valid symbol, and I don't understand why Console.Clear() isn't in the System.Console package.
