### ISSUE TITLE
Trailing Spaces always Trimmed In Markdown

### ISSUE THREAD

**Issue by fierval** [Microsoft/vscode#34504]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-azure-storage-utility|Com|0.0.2
angular2-snippets|dan|1.0.16
empty-indent|Dmi|0.2.0
jupyter|don|1.1.3
python|don|0.7.0
vscode-coffeescript-preview|dre|0.1.4
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.7
mdmath|goe|2.0.5
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-angular2-emmet|jak|2.0.3
markdown-toc|jof|1.4.0
Angular2|joh|2.7.0
mdhelper|jos|0.0.11
righteous|kar|1.0.2
markdown-shortcuts|mdi|0.8.1
vscode-jade-snippets|mrm|1.0.1
vscode-puglint|mrm|2.3.0
PowerShell|ms-|1.4.3
azurerm-vscode-tools|msa|0.3.7
debugger-for-chrome|msj|3.3.0
editorconfiggenerator|nep|0.2.1
language-vscode-javascript-angular2|nwa|0.0.11
vscode-docker|Pet|0.0.16
coffeescript-snippets|ron|0.1.3
preview-vscode|sea|1.3.1
autoimport|ste|1.2.2
code-spell-checker|str|1.3.9
vscode-markdown-paste-image|tel|0.5.0
jadeview|viv|1.0.0
expresssnippet|vla|0.1.0
html2jade|wma|0.2.0
JavaScriptSnippets|xab|1.4.1
vsc-docker|Zim|0.16.0

---

Steps to Reproduce:

Preferences:
// Place your settings in this file to overwrite the default settings
{
    "puglint.enable": true,
    "typescript.check.tscVersion": false,
    "editor.formatOnSave": false,
    "editor.trimAutoWhitespace": false,
    "files.trimTrailingWhitespace": false,
    "workbench.iconTheme": "vs-seti",
    "workbench.colorTheme": "Visual Studio Light",
    // Whether to lint Python files when no workspace is opened.
    "python.linting.enabledWithoutWorkspace": true,
    "editor.wordWrap": "on",
    "python.linting.enabled": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe",
    "cSpell.enabledLanguageIds": [
        "latex",
        "markdown",
        "plaintext",
        "text"
    ],
    "git.enableSmartCommit": true,
    "[markdown]": {
        "files.trimTrailingWhitespace": false
    }
}

1. Type something in an .md (Markdown) file, add 2 or more trailing spaces
2. Type another line 
3. Save the file. Ctrl - S

Trailing spaces are removed from line 1. In Markdown trailing spaces are semantically significant.

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
@fierval Since this does not appear to reproduce for you when running without extensions, this is most likely caused by one of the extensions you have installed. At this time, we don't have an easy way to figure out something like this (since any extension is allowed to interact with the file on save). So, you would need to disable some extensions, see if the problem reproduces, etc. until the extension that causes the trimming is identified.

I know EditorConfig might do some of this stuff on save, so you might want to start with that...
