### ISSUE TITLE
double-clicking on a word in peek view closes peek view

### ISSUE THREAD

**Issue by skybrian** [Microsoft/vscode#34502]
Normally, double-clicking on a word selects the word. In "peek view" the behavior is different; it closes the window. Since double-clicking is a common editing operation, this makes it harder to edit code within peek view; you have to remember never to double-click a word.

Steps to Reproduce:
1. Right-click on a Go symbol and select "Find All References"
2. In the code in the peek view window, double-click on any word.

Expected: the word should be highlighted and the quick view should remain open, allowing you to edit the word.
Actual: the quick view window closes, losing context.

Reproduces without extensions: No
(Requires Go plugin for "Show References"; I'd guess other languages would work, though?)

Workaround: in preferences, set "editor.stablePeek" to true. However, this does too much, because clicking outside the peek view doesn't close it.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
Go|luk|0.6.65
---

**Comment by jrieken** [comment]
We have a setting to turn that off: `"editor.stablePeek": true`. That will do what you want. Thanks and Happy Coding
