### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nodejs98** [Microsoft/vscode#34509]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-angular2-files|ale|1.3.10
ng-template|Ang|0.1.7
typings-installer|ben|0.2.0
bracket-pair-colorizer|Coe|0.10.9
angular2-snippets|dan|1.0.16
tslint|eg2|1.0.7
angular2-switcher|inf|0.1.4
Angular2|joh|2.7.0
angular2-inline|nat|0.0.17
typescript-hero|rbb|1.4.2
autoimport|ste|1.2.2
Angular2|UVB|0.4.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by gombosg** [comment]
I'm pretty sure this is typescript hero. Got the same errors - they disappeared after uninstalling that extension.
