### ISSUE TITLE
How can i ensure path valid via ctrl + .

### ISSUE THREAD

**Issue by cipchk** [Microsoft/vscode#34507]
- VSCode Version: 1.16.1
- OS Version: Win10(64)
- Node: 7.9.0
- Npm: 5.3.0

Steps to Reproduce:

Gif:

![asdf](https://user-images.githubusercontent.com/2987467/30508878-07ca6f7a-9ad4-11e7-86c3-8db7c0b591d5.gif)

Shouled:

```typescript
import { Injectable } from "@angular/core";

@Injectable()
export class NzTreeOptions {}
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
A few questions:

1. Do you have a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)?
2. How did you install angular? Is it installed in the root of your workspace?

**Comment by cipchk** [comment]
restart vscode is working.
