### ISSUE TITLE
opening files - issue - feature request

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#34501]
I think sometimes, if you don't change a file, and click on the other one which is in a different folder is pretty annoying. The file you have opened (looked for 3 minutes) just suddenly disappears.

1, It would be very handy, if the "Open editors" might not be sync with the opened files in the editor.
(so you haven't hundreds of files opened), but my file won't be disappeared.

2, The second thing is, it would be nice, if the "open editors" would be structured. (so if you opened more than one file from the same folder than it shows a tree list with the directory name - only the last directory - so not a whole structure) and show one file per folder, if you haven't changed the file,
but if you  have clicked again from the open editors, open the other file also.

It would be tricky, but very handy and nice feature.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
