### ISSUE TITLE
[STOPPING]

### ISSUE THREAD

**Issue by oeduardoal** [Microsoft/vscode#34505]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04 Gnome

Steps to Reproduce:
1. Upgrade to the latest version
2.Spend a few minutes programming

After I upgraded it overnight to the latest version available, after a few minutes of code, it hangs, and my Ubuntu asks for it to be forced shutdown.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@oeduardoal Can you perhaps give us more steps? What do you do specifically when you spend a few minutes programming?

i.e. Do you launch tasks, do you launch commands in the integrated terminal, do you do debugging, do you do git, do you just type in a file, etc. ?

**Comment by Tyriar** [comment]
Likely caused by https://github.com/Microsoft/vscode/issues/34301
