### ISSUE TITLE
Enhancement to manage extensions - bookmark, tag, metadata

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode#34513]
It would be useful to show bookmarks that I'm interested in (or that I'm not interested in).

Since there are so many extensions available and new ones being developed each day.    It would be nice to have a way to tag the extensions in the gallery.   The tag could be 'bookmark', 'review', 'dontuse', etc.

After some cursory review, It seems like this can be done using the galleryExtensionId.   We can store a list of the Ids and associated tags and metadata (comments, etc.) in a json file locally.

Whenever we query the extensions, we can merge the results into the UI of the Gallery or search results.

As a start, I suspect the storing of the metadata can be done with an extension itself -- would it have access to the galleryExtension id?   It probably makes more sense to integrate this into the UI of the workspace.   

I"m posting it here, because I'm interested in feedback and thoughts on this.

**Comment by bkbonner** [comment]
I went through the extension stuff, and it looks like w/o breaking into the core VSCode project, the galleryExtension API isn't exposed for extensions.   I might be missing something though.   I was hoping to use something from:  https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts

**Comment by sandy081** [comment]
Related #33035
