### ISSUE TITLE
Not Using http_proxy and https_proxy environment variables.

### ISSUE THREAD

**Issue by rishabhiitbhu** [Microsoft/vscode#34514]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Set `http_proxy` as `http://username:password@proxy_address:port/`and `https_proxy` as `https://username:password@proxy_address:80/` as environment variable. Start vscode. 
2. VSCode promts proxy authentication required for `proxy_address:port`. If you enter same username and password which you used while setting environment variable, it will accept it and you can install any plugin etc.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
If Code asks you for the credentials, then it is working. What's the problem here?

Here are more details about Networking in VS Code: https://code.visualstudio.com/docs/setup/network

**Comment by rishabhiitbhu** [comment]
@joaomoreno I would like to walk you through the issue.

VSCode is not using `http_proxy` and `https_proxy` env variables. I have set `http_proxy` variable as `https://username:password@proxy_address:80` why is it not using `username` and `password` instead asking explicity everytime I open the window.

I hope you get my point, if you have a doubt let me know.

**Comment by joaomoreno** [comment]
Does it remember the credentials if you run `code --proxy-server= https://username:password@proxy_address:80`?
