### ISSUE TITLE
[Linux] KDE's menubar button does not work

### ISSUE THREAD

**Issue by andreyorst** [Microsoft/vscode#34510]
- VSCode Version: 1.16.1
- OS Version: Archlinux
- Desktop Environment: KDE Plasma 5.10.5

Steps to Reproduce:

1. In Plasma settings go Widget Style -> Fine tuning -> Menubar: Titlebar button :
![image](https://user-images.githubusercontent.com/19470159/30510512-6f1c997e-9ace-11e7-8f3b-814c7ced4bd8.png)
2. Add this `Application menu` to window decoration: Widget Style -> Window decorations -> Buttons:
![image](https://user-images.githubusercontent.com/19470159/30510536-dcc0f9d4-9ace-11e7-9664-860ee4354fee.png)
3. Open any KDE app, and see that menu is gone and new button appeared:
![image](https://user-images.githubusercontent.com/19470159/30510560-2c68b67a-9acf-11e7-9f21-4e209ed928ba.png)
4. Open Visual Studio Code app, and check the menus:
![image](https://user-images.githubusercontent.com/19470159/30510568-5f50f200-9acf-11e7-8131-c258148a4b89.png)

Reproduces without extensions: Yes

### Expected behavior: 
menubar should disappear, and button should work.
### Actual behaior:
Menu is still there and button do nothing.

As electron supports KDE's global menus (or at least supported to draw them in previous versions) i'd expect them to work. But since fix of the electrons high CPU usage bug, menus are not working at all in VS Code.

**Comment by somniumAeternam** [comment]
What is the status of this issue? I would like to use the global menu with Visual Studio Code. It is working with Atom Editor and the new Electron release.

**Comment by andreyorst** [comment]
@somniumAeternam strange, just installed atom (I'm on Arch Linux) and global menu didn't worked for me. What versions of atom and electrom did you use? Were you using a git build?
Checked electron itself. Same story with electron version 1.6.15
https://github.com/electron/electron/issues/10532

**Comment by somniumAeternam** [comment]
I use Atom Editor 1.22.1 x64  on openSUSE Tumbleweed with latest updates. It is also working with electron 1.7.9.

**Comment by andreyorst** [comment]
So the global menus work for some people. Not for me, but i think that maybe something missing in my particular system. Maybe some plasma packages are missing. I don't know.
![image](https://user-images.githubusercontent.com/19470159/35563110-b7f7b986-05c6-11e8-8835-a6ff32754e66.png)

**Comment by andreyorst** [comment]
With the lastest plasma update global menu started to work in electron and all electron based applications.

**Comment by worldofpeace** [comment]
@andreyorst I can verify that installing `libdbusmenu-glib` on archlinux does solve this.

**Comment by andreyorst** [comment]
@worldofpeace awesome!

**Comment by kolya-ay** [comment]
Can confirm that installing `libdbusmenu-glib4` package on my Debian testing solves the issue for me. KDE Plamsa 5.10.5

**Comment by Tyriar** [comment]
Great that there's a workaround, it looks like an upstream issue
