### ISSUE TITLE
Feature Request: Navigation through Highlighted References

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/vscode#34519]
In Visual Studio there are 2 keyboard shortcuts that allow you to navigate through highlighted references of the current open document.  I think it would be very useful to have these in VS Code.

For languages like c# and typescript VS Code already has the symbol information to perform the highlight, I think now it's just a matter of being able to map a key to navigate next/previous.

In Visual Studio:
Edit.NextHighlightedReference
Edit.PreviousHighlightedReference

**Comment by jrieken** [comment]
> navigate through highlighted references 

@Sharpiro You the symbol highlight, right?

<img width="672" alt="screen shot 2017-09-18 at 10 49 07" src="https://user-images.githubusercontent.com/1794099/30534569-0e5ff08a-9c5f-11e7-89c6-a2e8c413be7e.png">

**Comment by sam-s4s** [comment]
@jrieken Yes, it highlights, but it doesn't allow you to navigate to the next/previous instance of that highlighted word. There is a Shift+F12 feature that shows references, but it is a slow and clunky method of navigating a piece of code...

Such a handy feature of VS2015/2017... Ctrl+Shift+Up/Down.

**Comment by jrieken** [comment]
Understood, thanks.
