### ISSUE TITLE
Hello World doc has wrong key sequence

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode#34518]
- VSCode Version:  1.16
- OS Version:  Linus

Steps to Reproduce:

1.  visit https://code.visualstudio.com/docs/extensions/example-hello-world
2.  search for:  you need to restart the Extension Development instance of VS Code

It says to use Ctrl+R to restart the instance.   I suspect this got changed over time, because the keybinding on linux is Ctrl+Shift+F5  (Restart)

Reproduces without extensions: Yes

**Comment by gregvanl** [comment]
Hi @bkbonner, the keyboard shortcut is correct. The confusion is with which instance you press Ctrl+R. You use Ctrl+R to restart the running Extension Development Host instance (the debuggee). You use Restart Ctrl+Shift+R if you want to restart the initial VS Code instance (the debugger). 
I'll update the documentation to be a clearer.
