### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by joshpeng** [Microsoft/vscode#34526]
[fda4_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1308712/fda4_main.cpuprofile.txt)
[fda4_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1308713/fda4_renderer.cpuprofile.txt)

- VSCode Version: <code>Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2673)</code>
- Memory (System): <code>8.99GB (3.86GB free)</code>
- Memory (Process): <code>151.09MB working set (158.19MB peak, 127.49MB private, 42.97MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|31|
|main|app.isReady => window.loadUrl()|251|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1088|
|renderer|require(workbench.main.js)|605|
|renderer|create extension host => extensions onReady()|606|
|renderer|restore viewlet|0|
|renderer|restore editor view state|103|
|renderer|overall workbench load|349|
|main + renderer|start => extensions ready|2688|
|main + renderer|start => workbench ready|2339|

---

**Comment by jrieken** [comment]
I couldn't find anything suspicious in this profile. If you have been alerted it might have been false alarm. If are interesting in our performance work, be assured it is an on-going theme and you can find all performance issues using the perf-label: https://github.com/Microsoft/vscode/issues?utf8=✓&q=%20is%3Aissue%20label%3Aperf%20

Thanks and Happy Coding
