### ISSUE TITLE
Feature request: option to include untracked files with Git: Stash command

### ISSUE THREAD

**Issue by zvinless** [Microsoft/vscode#34527]
- VSCode Version: 1.16.1
- OS Version: MacOS 10.12.6

This is a feature request.

I typically use "git stash -u" when stashing from the command line, but I don't think the git extension's current stash implementation supports stashing untracked files.  This would be really convenient either as a setting (could probably support various flags this way) or as a separate command.

**Comment by joaomoreno** [comment]
PR? :+1:

**Comment by raouldc** [comment]
I could give this a try, if no one is already working on it

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/34674

Thanks @raouldc!
