### ISSUE TITLE
Integrated terminal off-by-one rendering errors.

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#34524]
- VSCode Version: 1.17.0 128a4e3640c5375f7b0bc1cfd37f626481b1386f
- OS Version: macOS 10.13 Beta (17A362a)

Steps to Reproduce:

1. Paste the following command into the integrated terminal:
`python -c 'print ("\x1b[31m0123456789\x1b[0m")*9`
This prints the string [RED]0123456789[RESET] nine times, followed by a newline.

2. Resize the VSCode window so that the window half clips one of the red characters, and run it again.

Issues:

The terminal output does not wrap the partially-clipped character; it is possible to resize the window so that the final character essentially disappears.

Additionally, double-clicking a line of text to select it causes the line below to become highlighted instead.

Ideally, previously rendered text would wrap dynamically as the window was resized but this is not the case.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Reflowing lines is tracked in https://github.com/Microsoft/vscode/issues/23688

The double clicking bug should be fixed now, it may take a while to land in Insiders though.
