### ISSUE TITLE
块注释不能切换

### ISSUE THREAD

**Issue by onlyliujiangtao** [Microsoft/vscode#34521]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
vscode-eslint|dba|1.3.1
vscode-html-css|ecm|0.1.8
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.4
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
code-beautifier|mic|1.7.2
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
color-highlight|nau|2.3.0
vetur|oct|0.9.7
view-in-browser|qin|0.0.5
vue-vscode-snippets|sdr|1.0.2
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.块注释不能切换
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@onlyliujiangtao  Can you perhaps give a minimum example where toggle block comment fails for you ?
