### ISSUE TITLE
Cursor uses text cursor when mousing over the window title on macOS

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34522]
- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:44:11.087Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-svgviewer|css|1.4.2
tslint|eg2|1.0.7
git-project-manager|fel|1.4.0
seti-icons|qin|0.1.3

(1 theme extensions excluded)

---

This part:

<img width="326" alt="screen shot 2017-09-16 at 10 44 55 am" src="https://user-images.githubusercontent.com/2193314/30514559-1afd4476-9acc-11e7-8971-0a1628dfffdb.png">

**Comment by bpasero** [comment]
@Tyriar there is no explicit cursor style set on the title anywhere though, what are you seeing?

**Comment by Tyriar** [comment]
@bpasero this seems to be fixed now. I was seeing the caret/text cursor when mousing over the title bar. Will ping you again with a gif showing the problem if I see it again (as gifs can capture the mouse).
