### ISSUE TITLE
Add setting to delete without sending to trash

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#34534]
I'm on linux and want to have a file be immediately removed when I delete it from vscode. I don't want it moved to the trash directory but rather to be removed as if `rm` were being used. Please make it configurable as an option. None of the other apps I use move things to trash, so it creates an extra set of files for me to manage later. I manage my own recurring backups so I'm not worried about accidentally deleting something.

**Comment by mangopearapples** [comment]
I don't use  vscode enough on linux to know for sure, but on windows, shift-delete permanently deletes the file. Perhaps this works on the linux version too

**Comment by rightaway** [comment]
That works, thanks. But I'd like to suggest a configuration option that allows you to use just the Delete key to have the file go directly to trash (after the confirmation dialog), in order to remain consistent with all other applications I use on linux.

**Comment by Lusito** [comment]
Yes, please add this. I'm on windows and I have trash disabled.
I can't use the menu delete option, as it fails ("Failed to move '....' to the trash") and having to use shift+delete is quite annoying when every other application respects my windows trash setting.

**Comment by Lusito** [comment]
Just for reference, the other issue is #37900
