### ISSUE TITLE
Please rid of the () "" {} autocomplete nonesence

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#34537]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

Hit " or ( or { and a second matching " ) }  appears. and often, if not used from the start, like adding a terminating " on a string... a superfluous " appears or sometimes it double quote some text because I hit " where there was something there already. Sometimes delete the extra quote and the other one is deleted too! Frankly this is annoying, I find myself typing " and deleting the extra and retyping the quote I wanted because it's now gone!!!, And how about compile errors due to added or removed matching quotes?. How is constantly fighting the compile errors due to poorly placed matching ) " } worth my time! It's not saving any time, It's not like I can't double tap " myself or shift tap {} in 1 millisecond... something we've all done for years now. This Auto Typing the matching pair is just silly and goes against every programming fiber in my body!! I don't need a ghost adding characters to my code behind my back

---

Steps to Reproduce:

1. Use the product all day and curse every time you type " or ( or { and it anoyed you or broke your code behind your back that's the steps to reproduce

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
You can turn it off via `editor.autoClosingBrackets`. Just set it to false and the feature will be off.

**Comment by icuurd12b42** [comment]
Thank you!!! Thank you!
Thank you Thank you Thank you Thank you Thank you!!!

**Comment by JCKodel** [comment]
Disabling editor.autoClosingBrackets also disabling "{" auto closing (the only thing usefull). The "all-or-nothing" is not nice =(

Also, would be a lot better if we had the ReSharper option "Insert braces after [Enter]", so the matched "}" would appear only if we type "{" followed by an [Enter].
