### ISSUE TITLE
Feature Request - Async validation for ShowInputBox

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode#34532]
Scenario:

The [Azure App Service Extension](https://github.com/Microsoft/vscode-azureappservice) uses ShowInputBox to prompt user for the name of the new web app to be created. Then it checks the name availability by trying to resolve the DNS name of the web app. This operation can take up to a few seconds depending on network speed.

Currently the ShowInputBox doesn't seem to support async validation function, which means we can only validate after ShowInputBox function is done and re-prompt if the DNS value turns out not available.

The optimum experience: ShowInputBox supports async validation, when the validation function is running, the input box shows a progress indicator and won't allow the value be accepted (pressing Enter won't close the box), ESC should still cancel the input regardless.

**Comment by jrieken** [comment]
Understood. Technically it is already async but we wanted to enforce prompt and speedy validation because the user experience depends on this...

**Comment by chrisdias** [comment]
@jrieken is this something you expect to support, and if so in Sept or later?  thx.

**Comment by jrieken** [comment]
We can support it, tho very unlikely in September
