### ISSUE TITLE
Lag while scrolling

### ISSUE THREAD

**Issue by Ashikpaul** [Microsoft/vscode#34530]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open a file that contains many lines of code
2. Try to scroll.

->When I use two fingers gesture to scroll it lags. It is very annoying.

Feature request: 
It would be great if there is an option to view four panels like the below image.  

![screenshot 2](https://user-images.githubusercontent.com/17526871/30517950-dc49c670-9b8c-11e7-899a-af0f7673d42b.png)

**Comment by wizarrc** [comment]
@Ashikpaul I know there is an issue here that has been reported before. It has something to do with the Electron/Chromium dependencies causing the issue with a high precision trackpad. A workaround was to restore then maximize the vscode window and it stops lagging. Hope that helps.

**Comment by alexandrudima** [comment]
That would be #13612

**Comment by wizarrc** [comment]
@alexandrudima thanks, searching is impossible on this repo now with 5000+ open issues 😀

**Comment by wizarrc** [comment]
> Feature request:
It would be great if there is an option to view four panels like the below image.

@Ashikpaul try to file bug reports separately from feature requests. As you can see, the issue was closed pretty much without realizing you had a completely separate feature request embedded in your issue.

**Comment by alexandrudima** [comment]
Oh, sorry about that. I can extract that to a separate issue

**Comment by alexandrudima** [comment]
I've extracted the feature request to #34772

**Comment by Ashikpaul** [comment]
@wizarrc Sorry. I didn't know.
