### ISSUE TITLE
Request for project saving feature

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#34538]
- VSCode Version: 1.16.1
- OS Version: KDE Neon 5.10

Thanks, VsCode team for the awesome 1.16.1 Update... but I think there is more room for improvement,
If there is an option to save the workspace will be useful... I use 2 integrated terminals for my work. I  have to start it manually each time it gets back to work. if there is an option to save these all as a project it would be easier and fun to work. I feel language support more than JS is not up to the mark. but thanks to plugins which definitely fills the gap, But an integrated solution is more appreciated

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
