### ISSUE TITLE
无法为 JavaScript 语言功能安装 typings 文件。请确认 NPM 已经安装或者在你的用户设置中配置“typescript.npm”

### ISSUE THREAD

**Issue by Edge00** [Microsoft/vscode#34536]
<img width="1176" alt="wx20170917-163816 2x" src="https://user-images.githubusercontent.com/23715779/30519347-c17a6be4-9bc6-11e7-9bda-9bd51ac0887f.png">
<img width="378" alt="wx20170917-163833 2x" src="https://user-images.githubusercontent.com/23715779/30519348-c484a8d6-9bc6-11e7-850e-5dd2f8e1b34c.png">

**Comment by mjbvz** [comment]
Please set `"typescript.npm"` to point to your TypeScript install location: https://code.visualstudio.com/docs/languages/javascript#_fixing-npm-not-installed-warning-for-automatic-type-acquisition
