### ISSUE TITLE
Markdown preview is hard to read in the latest

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3453]
Previewing the 'latest.md' in the latest VS Code looks like this:

![2016-02-25 14-20-04](https://cloud.githubusercontent.com/assets/1898161/13320699/191a55e8-dbcb-11e5-83d4-e500a8730cd0.png)

and here the same file in VS Code 0.10.9:

![2016-02-25 14-19-27](https://cloud.githubusercontent.com/assets/1898161/13320724/335e1c64-dbcb-11e5-8be2-b7f9c8d47a98.png)

**Comment by weinand** [comment]
@bgashler1 after switching the theme the problem disappeared.

**Comment by weinand** [comment]
@bgashler1 after reloading the window the problem comes back.

CC @isidorn

**Comment by weinand** [comment]
duplicate of #3488

**Comment by joaomoreno** [comment]
:fireworks:
