### ISSUE TITLE
emmet abbreviation

### ISSUE THREAD

**Issue by funnycom** [Microsoft/vscode#34535]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|2.1.1
html5-boilerplate|sid|1.0.1

---

If I write the "background:none" and hit Enter then VSCode rewrite to "background-attachment:none".
It's very terrible. 
Can I modify the Emmet Abbreviation list? 

Steps to Reproduce:

1. write "background:none"
2. rewrite automatically to "background-attachment:none"

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@funnycom This issue is tracked in #34162, for which I will have a fix out soon in the next Insiders. Please

**Comment by ramya-rao-a** [comment]
Just pushed a fix in.
The fix will be available in tonight's Insiders build which you can get from https://code.visualstudio.com/insiders

Can you give it a try and let me know if it works for you?

**Comment by funnycom** [comment]
Thanks. The issue has been resolved.
