### ISSUE TITLE
Delete-all-left command does not continue to delete previous lines

### ISSUE THREAD

**Issue by zhiayang** [Microsoft/vscode#34531]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0 (macOS 10.12.6)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.2
TabOut|alb|0.1.4
better-whitespace|chm|1.0.1
cpptools|ms-|0.12.4
sublime-keybindings|ms-|2.9.1
subtle-brackets|raf|2.0.2
scope-info|sie|0.2.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file with multiple lines
2. Place the cursor in any line that's not the first line
3. Use the "Delete All Left" command/keybinding to delete all characters to the left
4. Repeat the keybinding or command -- nothing happens.

Reproduces without extensions: Yes

The standard OS X behaviour is to delete the current line entirely, and move the cursor up one line -- such that continuously pressing the delete-all-left will continue deleting lines.

If this is intended behaviour, then it might be desirable to have a separate command, or a preference toggle, that enables the behaviour I'm describing.

**Comment by kevinschaich** [comment]
Agree there should be a way to continue to prev. line. Atom and Sublime both function this way.

**Comment by eddysapata** [comment]
Please do this, want this feature

**Comment by AlexRex** [comment]
Any news on how to achieve this?

**Comment by eddysapata** [comment]
@AlexRex  @kevinschaich  Yes .
By using macros.
 In setting ,Use this
```
 "macros": {
        "sapataDelete": [
            "deleteAllLeft",
            "deleteWordLeft"
        ]
	}
```
And in key binding.

```
	{
		"key": "ctrl+shift+backspace",
		"command": "macros.sapataDelete",
		"when": "editorTextFocus && !editorReadonly"
	}
```

P.S -> https://marketplace.visualstudio.com/items?itemName=geddski.macros
You will need this in order to use macros..!! :) :)

**Comment by rebornix** [comment]
This issue was already fixed and no longer reproduceable in latest.
