### ISSUE TITLE
Node launch 'program' parsed incorrectly

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#34541]
I'm trying to launch Mocha tests in debug mode with TypeScript and ts-node, this should work (and used to work I believe):

```
{
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot}/node_modules/.bin/_mocha",
    ...
}
```

but I'm getting:

```
Cannot launch program 'c:\Temp\vscode-ts-node-debugging\node_modules\.bin_mocha'; setting the 'outDir or outFiles' attribute might help.
```

Note that there is a backslash missing in that message (`\.bin_mocha` should be `\.bin\_mocha`) so that leads me to think that the `program` value is parsed incorrectly. If I change my `launch.json` to contain:

```
"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha"
```

all works fine (but it's more correct and most tutorials use `node_modules/.bin/_mocha`).

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063

**Comment by isidorn** [comment]
@borekb can you reproduce this with vscode insiders?
https://code.visualstudio.com/insiders

Can you reproduce if you add 
```
"protocol": "inspector"
```
to you launch.json configuration?
How about if you do 
```
"protocol": "legacy"
```

I tried reproducing your issue but could not. Could you share a repository on GitHub for which you can always reproduce this issue?

**Comment by borekb** [comment]
Same problem in insiders:

![image](https://user-images.githubusercontent.com/101152/30538357-dd8f9690-9c6d-11e7-93dc-4ff81cf7498c.png)

Good repository to try to reproduce it is https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging/. I can reproduce at `ca02121`, all is OK in `master` (`dbf4d8b`).

**Comment by isidorn** [comment]
I can reproduce this only on Windows.
@weinand forwarding to you after our discussion

**Comment by weinand** [comment]
@borekb I cannot reproduce with the given repository in VS Code 1.17 (Insiders) on Windows.
What node.js version are you using?

**Comment by borekb** [comment]
Just tried on the most recent insiders and the issues is still there:

- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none

Make sure you try on [this specific commit](https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging/tree/ca021213cf7393ee56351d581f89b92c4c1f057c), `ca021213cf7393ee56351d581f89b92c4c1f057c`.

My Node is 8.4.0.

**Comment by weinand** [comment]
@borekb ok, then this is a problem of the "inspector" protocol of the node debugger.

**Comment by weinand** [comment]
@borekb the path `${workspaceRoot}/node_modules/.bin/_mocha` points to a shell script, not to anything that node.js can use. The `program` attribute expects a path to a JavaScript file (or any other source that can be translated to JavaScript). 

If you want to run the mocha JavaScript, then you'll have to use this path:
```json
"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha"
```  
(this is actually what you get when loading MASTER from the repository).

Or you can run the "mocha" executable by using the `runtimeExecutable`:
```json
"program": "${workspaceRoot}/node_modules/.bin/_mocha"
```

The fact that the error message shows `\.bin_mocha` instead of `\.bin\_mocha` is a bug in the error notification (and there is already a bug for it; @isidorn might know which)

**Comment by borekb** [comment]
@weinand Thanks, that explains it nicely.
