### ISSUE TITLE
It is NOT an error to open a folder that isn't in a git repo

### ISSUE THREAD

**Issue by Paul-Dempsey** [Microsoft/vscode#34549]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.1
xml|Dot|1.9.2
gauntlet|Mic|2.2.0
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
code-spell-checker|str|1.4.0

---

Steps to Reproduce:

1. Open a folder that is not in a git repo

Observe a big red error message from the git extension. 

<img width="428" alt="badgitalert" src="https://user-images.githubusercontent.com/25112074/30524437-85a746be-9ba8-11e7-9603-c0c0760dd12b.PNG">

Sorry, but opening a non-git folder is nothing to panic about and alert the user with an attention-getting alert that needs to be dismissed. This is normal functioning for an editor.  When I click on the git widget, then it's time to tell me about it.

Reproduces without extensions: No
(Obviously a git extension issue)

**Comment by joaomoreno** [comment]
That's strange... Does this reproduce when running `code --disable-extensions`?

**Comment by Paul-Dempsey** [comment]
See the last two lines of my post: no,

**Comment by joaomoreno** [comment]
Great! So this is an issue with one of the extensions you have installed. It's not the core git extension, since that one is enabled when running with `code --disable-extensions`.

I suggest you disable them one by one until you find the culprit. When you do, please file them an issue.

**Comment by Paul-Dempsey** [comment]
Ah! This is the Gauntlet extension for authoring files in Open Publishing Services.
