### ISSUE TITLE
refactor menu isn't working

### ISSUE THREAD

**Issue by m3l7** [Microsoft/vscode#34540]
- VSCode Version: 1.16.0
- OS Version: arch linux
- typescript version: built in (2.5.2)

I'm trying to show the refactor menu but it's not working.

I selected a method in a class (both in an angular4 and node.js+typescript project), no light bulbs appear and ctrl+. isn't doing anything.

I tried also to disable all extensions

**Comment by mjbvz** [comment]
1. What version of TypeScript are you using? This is shown in the status bar next to the `TypeScript` language identifier. Extract method is only supported on TS 2.5+
2. Can you please share some code that demonstrates the problem so we can investigate this

**Comment by m3l7** [comment]
using typescript 2.5.2

I cannot share my repos, but right now I'm trying with this simple script:

    export class Test {
        constructor() {}
    
        public testMethod() {
    
        }
    }

this is my tsconfig.json: 

    {
        "compilerOptions": {
            "target": "es6",
            "module": "commonjs",
            "sourceMap": true,
            "typeRoots": ["./typings/modules", "./typings/globals"],
            "experimentalDecorators": true,
            "emitDecoratorMetadata": true
        },
        "include":[
            "src/**/*"
        ]
    }

I tried to select testMethod, no light bulbs, nothing happens with ctrl+.

**Comment by mjbvz** [comment]
`testMethod` itself is not a valid extraction. Extract method takes some lines of code and converts them into a method/function.

Can you try selecting some lines inside of `testMethod` to see if that works
