### ISSUE TITLE
Feature request: There's no default formatting for CSS files when pressing shift+alt+f

### ISSUE THREAD

**Issue by vkWeb** [Microsoft/vscode#34545]
- VSCode Version: 1.16.0
- OS Version: Windows 10 Pro

Steps to Reproduce: 
Just press the default formatting shortcut **shift+alt+f** in a CSS file. You'll notice that the shortcut won't work for it.

Reproduces without extensions: Yes

Though we can get formatting by using beautify extension but I think every code editor must have CSS formatting in-built. It was quite disappointing. I hope it'll be resolved in coming updates.

**Comment by yume-chan** [comment]
Duplicate of #19166
