### ISSUE TITLE
Command D case sensitive option

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#34548]
_From @xmattstrongx on September 16, 2017 14:50_

`Command D - Add Next Occurrence`

I have found this shortcut to be a nice substitute for a refactor command that you may find in other IDEs. Unfortunately there does not seem to be an option to do this in a case sensitive manner. 

![image](https://user-images.githubusercontent.com/10662489/30513174-34b122aa-9ac4-11e7-8c38-8ea0cd06e3b5.png)

It would be nice if this option could either be configurable to be case sensitive or perhaps to have another shortcut that could function the same as Command D but in a case sensitive manner.

_Copied from original issue: Microsoft/vscode-go#1217_

**Comment by yume-chan** [comment]
In fact when you hit <kbd>Ctrl</kbd> + <kbd>D</kbd>, there is a little toolbar appears at the top-right of the editor, to let you toggle search options.

Shortcuts are <kbd>Alt</kbd> + <kbd>C</kbd> for case sensitive, <kbd>Alt</kbd> + <kbd>W</kbd> for match whole word (although it doesn't work for me), and <kbd>Alt</kbd> + <kbd>R</kbd> for using regular expressions (is it meaningful to use regular expressions to find occurrences?).

The shortcuts only work when the search panel is not shown, or it will apply to the search panel.

**Comment by alexandrudima** [comment]
I believe this is resolved with PR #36682 . When starting with a collapsed selection, Command+D will now search with `wholeWords: true and caseSensitive: true`.
