### ISSUE TITLE
VSCode Auto Save untitled files and open those files when opens again like Notepad++

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#3454]
Is there any way that i write some text in some files and dont save those files and close the editor when i open the editor again it should auto open those files like notepad++ does.

**Comment by joaomoreno** [comment]
This is currently not implemented.

**Comment by axefrog** [comment]
This is also the default behaviour in Sublime and Atom.

**Comment by shanalikhan** [comment]
i still use notepad++ for such feature. It would be great if this feature is implemented. to even write plain text in VSCode

**Comment by fyears** [comment]
This issue seems to be a duplication of #906.

I am another user looking for this features here. I also find someone posted feature suggestion on [uservoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756146-auto-save-temporary-files).

**Comment by joaomoreno** [comment]
Thanks. Closing as duplicate of #906

**Comment by lovebdsobuj** [comment]
This feature `"Unsaved files should be preserved on quit"` still not yet implement in **VSCode** version 1.4 !
It's really needed feature.
