### ISSUE TITLE
stdout/stderr not working in debug console

### ISSUE THREAD

**Issue by tonila** [Microsoft/vscode#34558]
launch.json
```
  {
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "test",
        "program": "${workspaceRoot}/test.js",
        "console": "internalConsole"
      }
    ]
  }
```
code 
```
"use strict";
// we are using npm debug module, that uses stdout/stderr to write logs
//process.env.DEBUG = 'server'
//const debug = require('debug')('server');
//debug('debug')
process.stdout.write('stdout\n')
process.stderr.write('error\n')
```
debug console does not print stdout/stderr
If I change "internalConsole" to "integratedTerminal" or run app from terminal, stdout/stderr works fine

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.11.0-041100-generic
- Extensions: Extensions are disabled

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19750
fyi @roblourens
