### ISSUE TITLE
Ctrl+K S no longer works (with this extensions list)

### ISSUE THREAD

**Issue by Azmos** [Microsoft/vscode#34553]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.2
dart-code|Dan|2.4.1
vscode-eslint|dba|1.3.1
html-symbols|Die|0.0.2
githistory|don|0.2.3
python|don|0.7.0
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.7
prettier-vscode|esb|0.23.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
rest-client|hum|0.15.2
icon-fonts|idl|1.8.1
svg-icons|idl|0.5.0
vscode-cdnjs|Jak|0.14.3
autofilename|Jer|0.1.3
MeteorSnippets|jml|0.1.3
svg|joc|0.0.9
docthis|joe|0.4.8
Angular2|joh|2.7.0
TypeScriptImport|kev|1.17.0
terraform|mau|0.0.17
dotenv|mik|1.0.0
vscode-jade-snippets|mrm|1.0.1
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.6.2
vscode-docker|Pet|0.0.17
material-icon-theme|PKi|2.2.1
ejs-language-support|Qas|0.0.1
project-snippets|reb|0.5.0
Ruby|reb|0.15.0
vscode-icons|rob|7.12.0
gi|rub|0.2.11
vscode-paste-and-indent|Rub|0.0.8
Align|ste|0.2.0
language-stylus|sys|1.7.3
sort-lines|Tyr|1.3.0
vscode-meteor|vuh|0.1.1
quokka-vscode|Wal|1.0.63
wallaby-vscode|Wal|1.0.59
JavaScriptSnippets|xab|1.4.1
html-css-class-completion|Zig|1.10.0

(15 theme extensions excluded)

---

Steps to Reproduce:

1. Press Ctrl+K S;
2. Command gets accepted but not executed.

Reproduces without extensions: **No**, if I disable extensions it works as expected.

**Comment by alexandrudima** [comment]
@Azmos keybindings are straight forward to tweak.

You can open the keybindings UI (from Preferences > Keyboard Shortcuts).

Then, you can search for "ctrl+k s" or "ctrl+k ctrl+s" and find out which keybinding rules are operating on those keybindings. Then, you can remove them (via right click).

**Comment by Azmos** [comment]
@alexandrudima whops my bad, I checked the keyboard shortcuts when I was still in `--disable-extensions` mode ¯\\\_(ツ)\_/¯

What replaced it was `quokka.stopCurrent`.
