### ISSUE TITLE
Explorer Viewlet: Allow to set to hidden by default

### ISSUE THREAD

**Issue by spywhere** [microsoft/vscode#34557]
- VSCode Version: 1.16.1 (1.16.1) 27492b6bf3acb0775d82d2f87b25a93490673c6d
- OS Version: macOS Sierra 10.12.6 (16G29)

By default, VSCode allow users to hide/show custom explorer views, however its behaviour is to always show all explorer views on a newly opened project. Since not all extension developer make an option to hide these custom views, doing the hiding stuffs is quite tedious when work with a lot of projects. By allowing users to set their default showing preferences, this help reduce time to do unnecessary stuffs a lot.

**Comment by alexr00** [comment]
We have this now https://code.visualstudio.com/updates/v1_48#_tree-view-initial-visibility

**Comment by spywhere** [comment]
@alexr00 that doesn't solve the issue from VSCode, rather it depends on extension developers to provide the option instead (which is the point of this issue).

- There is an option to disable the tree view manually.  
But it work per workspace, not globally.
- Developer have an option to set a context for toggle visibility.  
But not all developer would follows so.

**Comment by alexr00** [comment]
I think that would be solved by https://github.com/microsoft/vscode/issues/103654, which is about saving a default view + sidebar layout to be used across projects.
