### ISSUE TITLE
Git commit message keymap for newline

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#34556]
I often have >1 line commit messages. Or try to, when I remember that vscode is one of the only programs that uses _SHIFT_ + ENTER for a newline rather than _CTRL_ + ENTER. And that is ok, but an extremely useful addition would be to have a keymap point so that this could be changed. It would be much appreciated!

To be clear. I am referring to:
![image](https://user-images.githubusercontent.com/5379325/30526964-f6d5b300-9bd7-11e7-870d-3ba1863602ec.png)

**Comment by joaomoreno** [comment]
Actually VS Code uses the simplest thing: just <kbd>Enter</kbd>. Did you try that?

**Comment by erichiller** [comment]
Right you are sir. I will go sit in the corner now....

But that must have changed at some point. I am nearly certain I remember `<Enter>` committing the message.

A keyhook might still be nice. But if any more than a low-level of work is required, I'd close this.

**Comment by joaomoreno** [comment]
Eheh no worries. I'll close it for now, you're actually the first guy to bring this up. If someone else comes along I'll think of you! 🥇
