### ISSUE TITLE
Bad HTML Formatting when using <button></button>

### ISSUE THREAD

**Issue by nazarkryp** [Microsoft/vscode#34569]
Angular 4 project
Not alignning </button> close tag and elements or text that is inside of button when calling format document command
![image](https://user-images.githubusercontent.com/23178377/30535236-41f2c494-9c6a-11e7-9a87-b9275bbef1e0.png)

**Comment by aeschli** [comment]
Please check the `html.format.unformatted` setting and remove `button` from there if you want it formatted.
