### ISSUE TITLE
Python debugger crashes instantly

### ISSUE THREAD

**Issue by derekriemer** [Microsoft/vscode#34562]
- VSCode Version: Code - Insiders 1.17.0-insider (b0c0634339c6f64a5c7f08b56fe732fb9154d3c4, 2017-09-15T05:24:23.107Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.4
code-spell-checker|str|1.4.0

---

Steps to Reproduce:

1. open a folder.
2. create a python file, with these contents.
    ```
    x = int(input("Enter your x"))
    y = int(input("Enter your y"))
    z = x + y
    if z < 5:
        print("Addition to less than 5")
    else:
        print("More than 5.")
    print(z)
    ```
3. open debug launch. Use autocomplete to complete the external debugger launch.
4. press f5 in the python file. 
Expected: External terminal with printouts and such.
Actual: Terminal comes up very briefly, then boom, disappears. additionally, my default python file assosiation was at one point vs code, and a python file was launching in vs code as soon as I pressed f5 (Assumed to be used to spawn the debugger). I set python 3 as my default python handler, but still, not sure what's going on.

Reproduces without extensions: Yes/No Not applicable.

**Comment by derekriemer** [comment]
If I could get the thing to stay open I could get the traceback I think must be happening.

**Comment by derekriemer** [comment]
wo, that's some cool bot magic.

**Comment by isidorn** [comment]
Please file this against the vscode python extension
https://github.com/DonJayamanne/pythonVSCode

Thank you

**Comment by derekriemer** [comment]
sweet, thanks.
