### ISSUE TITLE
Terminal is broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34563]
I simply can't use the terminal today. :cry: 

![peek 2017-09-18 09-41](https://user-images.githubusercontent.com/22350/30532758-46a13bec-9c56-11e7-9608-11bd8b37d827.gif)

![screenshot_20170918_094137](https://user-images.githubusercontent.com/22350/30532632-9da5cb20-9c55-11e7-917e-8a8211ef2dab.png)

**Comment by liuliangsir** [comment]
I run into the issue just now.

**Comment by farfromrefug** [comment]
Same here, no terminal

**Comment by ddotlic** [comment]
Same here, a bit more context: on a fully up-to-date macOS.

**Comment by Uranbold** [comment]
![bug](https://user-images.githubusercontent.com/1425854/30537908-95bf0204-9ca6-11e7-9d6a-adb8750e0852.jpg)

Don't know why but also this... Is this similar?

**Comment by edenprojectde** [comment]
Any correlation to this maybe? Console closes after this error :?
![grafik](https://user-images.githubusercontent.com/6115966/30543029-d0a02eea-9c81-11e7-8894-a5c17c9b8170.png)

**Comment by tomavic** [comment]
Yes I encounter this problem since I downloaded the August version. CLI keep crashing

**Comment by ddotlic** [comment]
I'm reasonably sure we're talking _Insider_ build here, not a regular one, reason being that console has been completely rewritten at the rendering layer and this kind of issues are somewhat to be expected.

**Comment by will-l-h** [comment]
Yes, it's Insiders (you can see that in the title bar in the screenshots). Not sure how important it is to have the Insiders label but I made the mistake of filtering my search to that label and came up empty.
