### ISSUE TITLE
Search input field barely visible

### ISSUE THREAD

**Issue by baglio** [Microsoft/vscode#34564]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open a new document
2. Press <kbd>cmd</kbd> + <kbd>f</kbd>

Reproduces without extensions: Yes

When searching in file the input field is too small, and the input text can't be seen.

![input search](https://i.imgur.com/jLKwrbe.jpg)

**Comment by yume-chan** [comment]
Looks similar to #33349.

**Comment by roblourens** [comment]
Yes, thanks
