### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Maxim-Lysak** [Microsoft/vscode#34560]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
sass-indented|rob|1.4.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yume-chan** [comment]
What's your problem?

What did you do and what did you see?
