### ISSUE TITLE
Close red wave underline error hint

### ISSUE THREAD

**Issue by AsasinCree** [Microsoft/vscode#34568]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open one file in a specific format.
2. If there's any grammer error, it'll highlighted by a red wave underline.

But I doesn't need this hint sometime. I want to close it in all files but can't find this setting.

**Comment by alexandrudima** [comment]
@AsasinCree What language are you using (i.e. JavaScript, TypeScript, css, etc) ?
