### ISSUE TITLE
Setting 'editor.action.triggerSuggest' as post completion command does show proposals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#34565]
Inspired by #31948:

The idea is that on a completion of a css property, code assist is activated again, to show the proposals for the property values.

- add 'editor.action.triggerSuggest' as post completion command
- invoke the completion proposal
- observe no completion window is opened

The triggerSuggest command is called, proposals are requested from the providers, but the operation is canceled before any suggestions are shown.
(cancel seems to come from SuggestController._onDidSelectItem)

**Comment by jrieken** [comment]
Yeah, it seems that after accepting/inserting a completion we always finish/cancel suggestion not being aware that in the meantime a new session has started...

**Comment by aeschli** [comment]
Verified by a code example
