### ISSUE TITLE
Autodetect tasks not working when tasks are on a subfolder and using "cwd" option

### ISSUE THREAD

**Issue by elvishp2006** [microsoft/vscode#34575]
- VSCode Version: 1.16.1
- OS Version: Windows 10

Autodetect tasks not working when tasks are on a subfolder and using "cwd" option to set the tasks folder, same problem for package.json and Gulpfile.js

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
We are currently only auto detecting task in the root folder and in workspace folder roots. We are not traversing down the whole folder tree.

**Comment by elvishp2006** [comment]
I understand, but as there is the option "cwd", I think coherently look at the directory informed in "cwd".

**Comment by dbaeumer** [comment]
Hmm, which option `cwd` are you referring to? The autodetection for at least grunt, gulp and jake doesn't offer such an option.

**Comment by elvishp2006** [comment]
* ${cwd} the task runner's current working directory on startup: https://code.visualstudio.com/docs/editor/tasks

**Comment by dbaeumer** [comment]
This is the working directory of an executed task. You can only use it to configure a task, not to tell the tak system where to look for tasks. Where did you use `${cwd}`

**Comment by elvishp2006** [comment]
This is an example of my tasks.json, I am using the "cwd" option, outside of the tasks array, what I wanted to do was just inform this "cwd" option and vscode understand that my tasks are in this folder and then autodetect these tasks, without the need to inform the tasks array.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "gulp",
            "type": "shell",
            "command": "gulp",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "taskName": "gulp dev",
            "type": "shell",
            "command": "gulp dev"
        }
    ],
    "options": {
        "cwd": "${workspaceRoot}/ghost"
    }
}
```

**Comment by dbaeumer** [comment]
Actually this as a different semantic. The options defined globally are merged into every task defined in the tasks property. They are inherited.

**Comment by dallas** [comment]
So, tasks in subfolders are not auto-detected, I get that, but is there a way to still configure tasks in subfolders to work in the VS Code task runner system?

**Comment by dbaeumer** [comment]
@dallas yes. You can always create a task in the tasks.json file that runs gulp for example in a sub folder. Something like (not tested :-))

```json
        {
            "label": "gulp sub",
            "type": "shell",
            "options": {
                "cwd": "${workspaceFolder}/subFolder"
            }
            "command": "gulp build"
        }
```

**Comment by dallas** [comment]
Ahh, okay. Thanks for the quick answer and useful example, @dbaeumer! 😄

**Comment by ltfschoen** [comment]
i just tried doing this where i have multiple applications in subfolders and i want to build a specific one by running `cargo contract build` https://github.com/paritytech/cargo-contract since the build command needs to be run in the folder with the Cargo.toml file, **but it doesn't work**.
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build Contract",
            "type": "shell",
            "problemMatcher": [
                "$rustc"
            ],
            "args": ["contract", "build"],
            "options": {
                "cwd": "${workspaceRoot}/mydapp",
                "shell": {
                    "executable": "/bin/bash",
                    "args": ["-c", "-i"]
                }
            },
            "command": "cargo",
            "group": "build",
            "presentation": {
                "reveal": "always",
            },
        }
        
    ]
}
```

but since it's running `cargo`, i can add a `Cargo.toml` file in the project root folder too such as:
```
[workspace]

exclude = []

members = [
	"dapps/mydapp",
]
```

and add all the projects that are in the subdirectories as members of it, and then i can build them all from the project root
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build Contract",
            "type": "shell",
            "problemMatcher": [
                "$rustc"
            ],
            "args": ["contract", "build"],
            "options": {
                "cwd": "${workspaceRoot}/dapps/mydapp",
                "shell": {
                    "executable": "/bin/bash",
                    "args": ["-c", "-i"]
                }
            },
            "command": "cargo",
            "group": "build",
            "presentation": {
                "reveal": "always",
            },
        }
    ]
}
```
e.g. https://github.com/ltfschoen/RustTest/blob/master/.vscode/tasks.json

then after they're all built (which generates a binary in the subdirectory's {subdirectory}/target/debug folder, i run the specific application i want with debugging by using a launch.json configuration file like this one https://github.com/ltfschoen/RustTest/blob/master/.vscode/launch.json
