### ISSUE TITLE
Markdown Preview don't work

### ISSUE THREAD

**Issue by allruiz** [Microsoft/vscode#34579]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
vscode-simple-icons|Lau|1.6.1
vscode-docker|Pet|0.0.17
application-insights|Vis|0.4.1
cform|aws|0.0.10
azuretoolsforvscode|bra|1.2.9
vscode-eslint|dba|1.3.1
python|don|0.7.0
tslint|eg2|1.0.7
azure-functions-tools|joh|0.3.1
mssql|ms-|1.1.0
azurecli|ms-|0.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-azureextensionpack|ms-|0.0.6
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
vscode-icons|rob|7.13.0
json2yaml|tux|0.2.0
usql-vscode-ext|usq|0.2.4
azure-iot-toolkit|vsc|0.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Change Lang to Markdown
2. Open Preview
3. Nothing happen

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still reproduce if you disable all extensions? Start code with the `--disable-extensions` command line flag to check this
