### ISSUE TITLE
http img url in markdown preview fail

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#34570]
- VSCode Version:1.16.1 (1.16.1)
- OS Version:10.13 Beta

Steps to Reproduce:

1.when i write markdown i add a img url .it's  url is `http`；
2.then  i preview it but it fail; i don't kown why。

![jietu20170918-172708 2x](https://user-images.githubusercontent.com/3990411/30536056-07035f8c-9c2a-11e7-9f4c-fbb8fd91716f.jpg)

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I believe we only render `https` and `file` origins in the markdown preview by default for security reasons. @mjbvz would know how to enable/disable this.

**Comment by mjbvz** [comment]
Yes, we block http resources by default. There should be a popup in the preview saying that some content has been blocked. Click on this popup to change the markdown security settings. Here's more info about those settings: https://code.visualstudio.com/Docs/languages/markdown#_markdown-preview-security

Please let me know if that doesn't fix things

**Comment by zhiqiang21** [comment]
yes ,when i do `Markdown: Change preview security settings `。image url  is http can preview very well。

when i preview a plugin information 。 i find  the http image url  also load fail。 How can I solve this problem?

![](http://7xs2tr.com1.z0.glb.clouddn.com/zhiqiang21/fqeqg.jpg?imageMogr2/auto-orient/thumbnail/!80p/blur/1x0/quality/75|watermark/2/text/aHR0cHM6Ly9naXRodWIuY29tL3poaXFpYW5nMjE=/font/5b6u6L2v6ZuF6buR/fontsize/400/fill/I0ZBMEMwQw==/dissolve/100/gravity/SouthEast/dx/10/dy/10|imageslim)

**Comment by mjbvz** [comment]
Yes, we always block http images in the marketplace. There is no way to change that. You need to use https resources. Relative links to images on stored in a github issue will also work since these resolve to https

**Comment by zhiqiang21** [comment]
Thank you very much for your answer。
