### ISSUE TITLE
switch branch will automatically save the file as CRLF

### ISSUE THREAD

**Issue by gumppur** [Microsoft/vscode#34573]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
better-toml|bun|0.2.0
gitignore|cod|0.5.0
python|don|0.7.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-rust|kal|0.4.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.12.4
rust|rus|0.2.2
vim|vsc|0.10.1
debug|web|0.21.2
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.9.0

---

Steps to Reproduce:

1.Open a git working directory.
2.Set the default eol to LF.
3.Converts the current file eol to LF.
4.Click the branch name in the lower left corner to switch the branch.
5.Then you will find all the files fol have become CRLF, but I just want LF.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I think this should be a setting that you configure to git. i.e. use `git configure ....`

**Comment by gumppur** [comment]
You are right, my git autocrlf is set to false, and after I set it to true, I can not see that eol is modified in git status. But now switching the branch will still automatically convert eol. I still do not understand why this is so.

**Comment by joaomoreno** [comment]
Try setting `autocrlf` to `false` and `safecrlf` to `true`.
