### ISSUE TITLE
Specific focus mode for popup?

### ISSUE THREAD

**Issue by coodoo** [Microsoft/vscode#34589]
I was trying to assign a specific shortcut key (instead of `esc`) to dismiss popup/tooltip box (as seen pointed by the red arrow in the screenshot).

Wondering if there's a specific focus mode I could use to target it? Something like `"when": "editorFocus"` but for popups instead?

<img width="636" alt="screen shot 2017-09-19 at 4 14 15 am" src="https://user-images.githubusercontent.com/325936/30562525-5465bf00-9cf1-11e7-99a9-705ec3e0fb7e.png">

**Comment by ramya-rao-a** [comment]
That looks like the hover info.
Escape should by default dismiss the popup. It doesnt for you?

**Comment by coodoo** [comment]
Yes `escape` worked fine by default, it's just that I mapped it to switch between active editor and integrated terminal, so now every time I want to dismiss the popup, it also switches the focus from editor to terminal.

What I wanted to do is setting up a new shortcut key to only dismiss the popup when it's displayed, but after that stay put in current editor.

Here's what I tried but to no avail, hence asking if there's specific focus mode I could use to replace `<SOME_MODE>`.
```
{
      "key": "escape escape", "command": "workbench.action.focusActiveEditorGroup", "when": "<SOME_MODE>"
    },
```

**Comment by ramya-rao-a** [comment]
Try `!editorTextFocus` when mapping escape to switch between the active editor and the terminal. That way you will be switching when the text inside isn't focused

When inside the editor, esc would execute the default behavior.

For more on the clauses you can use, see https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

Does that help?

**Comment by coodoo** [comment]
hey thanks! `!editorTextFocus` worked like a charm!

Here's the full configuration for switching between editor/terminal using escape, and also remain the  capability to cancel popups.

```
{
    "key": "escape", "command": "workbench.action.terminal.focus", "when": "!editorTextFocus"
},
{
    "key": "escape", "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"
},
```

**Comment by ramya-rao-a** [comment]
great, Happy Coding!
