### ISSUE TITLE
VSCode Ignores Double-Click to Minimize Setting on Yosemite

### ISSUE THREAD

**Issue by jthomp** [Microsoft/vscode#34582]
- VSCode Version: 1.16.1
- OS Version: Mac OS X Yosemite 10.10.5

Steps to Reproduce:

1. Open VSCode.
2. Open System Preferences.app.
3. Click Dock.
4. Check 'Double-click a window's title bar to minimize'.
5. Double-click the title bar in the VSCode window. The window will expand to fill the screen when it should minimize to the Dock.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
I might be missing something here...

You set  'Double-click a window's title bar to minimize'
So when you double click, the app minimizes... which is what you set

Why would the window expand to fill screen?

**Comment by jthomp** [comment]
I clarified step 5. On my machine, when I double-click the title bar the window expands to fill the screen when it should minimize the Dock.

**Comment by ramya-rao-a** [comment]
I tried the same on my Mac, works as expected.

Do other applications work as expected? i.e minimize on double-clicking the title bar?

**Comment by jthomp** [comment]
Yep. I've also tried disabling extensions. Strangely, this doesn't happen on my other Mac running High Sierra.

**Comment by bpasero** [comment]
@jthomp we read the settings to do the right thing but this might require a restart of VS Code after changing the setting. Does it help?

**Comment by jthomp** [comment]
@bpasero Restarting does not seem to have any effect.

**Comment by bpasero** [comment]
Might be an issue with your macOS version, it works just fine for me on macOS 10.12.x.

You can always enable the native title bar to get the behaviour: `"window.titleBarStyle": "native"`

**Comment by jthomp** [comment]
That's what I was thinking, too. This doesn't happen on my other machine.

Ah, I hadn't realized I that. Changing `window.titleBarStyle` to `native` fixes the issue for me.
