### ISSUE TITLE
Feature Request: Compare and Merge files line by line (not vsc)

### ISSUE THREAD

**Issue by tiger2380** [Microsoft/vscode#34585]
Hey.
I will be great if I can compare two files and merge the files line by line.

For example: I compare two files, it shows the diff, I right click on a line that is diff and it will give me an option to move/merge the line left or right.

**Comment by hrvoj3e** [comment]
@tiger2380 Did you find a way to do this? Some external tool called from VSCode maybe?

**Comment by FloppyNotFound** [comment]
@hrvoj3e you can use any tool you like as git merge tool, independently from VS Code, by setting another diff/merge tool as default. See http://meldmerge.org/help/resolving-conflicts.html as an example.

But the drawback is, you can't resolve conflicts directly in VS Code in that way (yet).

**Comment by hrvoj3e** [comment]
@FloppyNotFound I found Meld also. It looks good.
I am using Beyond Compare on Windows but I often compare files **outside of Git** and having controls to copy content from "left to right" or "right to left" does help a lot - I miss this feature in VS Code.

**Comment by alexandrudima** [comment]
Let's track in #25887
