### ISSUE TITLE
C++ intelliSense with different file system types (Windows 10)

### ISSUE THREAD

**Issue by jordangarside** [Microsoft/vscode#34586]
- VSCode Version: Code - Insiders 1.17.0-insider (128a4e3640c5375f7b0bc1cfd37f626481b1386f, 2017-09-12T05:24:19.607Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.4

IntelliSense doesn't seem to be working with SSHFS filesystem type in Windows 10 (no import errors detected and no squiggly lines). I know this is a fringe case, but I'm wondering if there is an easy fix.

IntelliSense works fine for this example in the local filesystem as well as on an exfat formatted flash drive.

---

Steps to Reproduce:

1. Install winsshfs and mount a remote file system
2. Open the a project locally from that mounted file system

<img width="270" alt="nlogn_properties" src="https://user-images.githubusercontent.com/6321824/30560600-715fce7c-9c86-11e7-9f4e-7f84be4a01e0.png">
<img width="761" alt="helloworld_vscode" src="https://user-images.githubusercontent.com/6321824/30560601-7163b1ea-9c86-11e7-9996-ffeeb6b7298e.png">

Reproduces without extensions: No (Need the C++ extension for intellisense)

**Comment by ramya-rao-a** [comment]
@jordangarside Have you tried logging this issue in the repo for the C++ extension?

**Comment by jordangarside** [comment]
Oops, didn't realize it was a separate repo. I will post there today, thanks!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
