### ISSUE TITLE
Allow closure of git folders in multi-root workspace

### ISSUE THREAD

**Issue by coenicho** [Microsoft/vscode#34581]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601

I updated to new VSCode release and love the multi-root workspace feature. The issue/feature I would like to raise is that it would be nice to be able to close git repos instead of just minimizing them in the source control view.

**Comment by joaomoreno** [comment]
The latest Insider release already has a different UX which allows for this: #33363
