### ISSUE TITLE
IntelliSense for .vscode/extensions.json

### ISSUE THREAD

**Issue by donaldpipowitch** [microsoft/vscode#34584]
- VSCode Version: 1.17.0-insiders
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Add the following `.vscode/extensions.json`.

```json
{
  "recommendations": [
    // VS Code plugin for prettier/prettier
    // see https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
    "esbenp.prettier-vscode"
  ]
}
```

2. Hover over a recommendation.

It would be nice to see some information about the extension on hover (similar to `dependencies` in the `package.json`). Currently I like to add the description and a link to the market place for more information, but this is cumbersome to do manually :)

**Comment by ramya-rao-a** [comment]
What information would be useful here?
Extension name and the description?

@sandy081 @joaomoreno This would be a nice feature, thoughts?

**Comment by donaldpipowitch** [comment]
Description and maybe a way to go to the marketplace easily.

**Comment by sandy081** [comment]
A click handler that would open the extension in Extensions editor?

**Comment by donaldpipowitch** [comment]
Sounds good.
