### ISSUE TITLE
JCAMP-DX text file not displayed

### ISSUE THREAD

**Issue by lampo808** [Microsoft/vscode#34580]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|0.16.0
jupyter|don|1.1.3
python|don|0.7.0
matlab|Gim|0.6.0
gc-excelviewer|Gra|1.1.15
latex-workshop|Jam|3.5.2
copy-markdown-as-html|jer|1.0.0
md-navigate|jri|0.0.1
vscode-todo-parser|min|1.9.1
vscode-markdown-to-clipboard|mle|0.0.1
wordcount|ms-|0.1.0
startanyshell|rem|0.3.1
code-settings-sync|Sha|2.8.3
markdown-preview-enhanced|shd|0.2.8
Align|ste|0.2.0
code-spell-checker|str|1.3.9
vscode-markdown-paste-image|tel|0.4.9
markdown-all-in-one|yzh|0.9.0

---

Steps to Reproduce:

1. (try to) Open the text file in the attached [zip](https://github.com/Microsoft/vscode/files/1311217/130001.zip)
2. Blame the editor for not being able to recognize a small text file as such

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
The file is identified as binary. @bpasero would know why:

![image](https://user-images.githubusercontent.com/5047891/30649671-2a5b78fe-9e21-11e7-8a17-048296790f5b.png)

**Comment by bpasero** [comment]
@lampo808 probably because it contains 0-bytes. We only support files with 0-bytes when the it has a UTF-16 BOM in the beginning.

**Comment by lampo808** [comment]
@alexandrudima @bpasero thanks guys! I will convert the encoding with another editor for now.
