### ISSUE TITLE
Assertion failed - node-pty/winpty

### ISSUE THREAD

**Issue by liam-potter** [Microsoft/vscode#34587]
Receiving the following error upon VSCode Insiders startup:

![Error Screenshot](https://i.imgur.com/no0AE7C.png)

The terminal then closes and shows the following error in VSCode Insiders:
> The terminal process terminated with exit code: 3221226505

- VSCode Version: 1.17.0-insider
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Close VSCode while bash terminal is open (nothing running)
2. Open VSCode Insiders manually, or through `code-insiders .`, or through `code-insiders --disable-extensions`
3. Error appears

Reproduces without extensions: Yes

**Comment by MEXdave1997** [comment]
Have this same error. I wonder what exactly within that file specified is causing it. 🤔

**Comment by andresg747** [comment]
Hi. 
Having the exact same error as well. Have no idea why though.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35117
