### ISSUE TITLE
vscode (1.16.1) getting crashed 

### ISSUE THREAD

**Issue by Jo-ravar** [Microsoft/vscode#34588]
- VSCode Version: 1.16.1
- OS Version: Windows 10 1607

![vsbug](https://user-images.githubusercontent.com/20628218/30561685-6d1b1d0a-9cd9-11e7-92d8-52aa008c99bc.PNG)

### Issue:

- While running `mongoDB` and `node.js` server in  the  windows command shell in vs terminal .
vscode is getting crashed frequently.

**Comment by Jo-ravar** [comment]
I am frequently getting this issue  . Can you look into it .

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
