### ISSUE TITLE
typescript crash

### ISSUE THREAD

**Issue by gshields** [Microsoft/vscode#34599]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
jslint|ajh|1.2.1
vscode-eslint|dba|1.3.1
python|don|0.7.0
json-tools|eri|1.0.2
diff-tool|jin|0.0.1
Go|luk|0.6.65
cpptools|ms-|0.12.4
typescript-javascript-grammar|ms-|0.0.24
code-spell-checker|str|1.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide some information about the issue
