### ISSUE TITLE
Search returns incorrect results for files that have only \r newlines

### ISSUE THREAD

**Issue by mtillman** [Microsoft/vscode#34596]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
gauntletTest|Mic|2.3.1

---

Steps to Reproduce:

1. Clone intunedocs-pr
2. In VSCode, open the repo folder, shift-control-F, and search on "ms.assetid:". 
3. Search returns 653 results in 572 files. There should be only one in each file. I ran the same search in NotePad ++ and got 571 hits in 571 files (exactly what I would expect).
4. Scroll down to one of the files in VSCode that contain 2 hits and click on of the ms.assetid's, see capture below: 
 ![screenshot](https://user-images.githubusercontent.com/1141590/30566937-edb52746-9c82-11e7-802c-16d3efd8c99c.png)
 The highlighted text in the opened file is not the search text. If you click the other hit, it doesn't highlight the text correctly either. Note that there's just one instance of the the search text in the file. 

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Is the folder on a network share? Is the encoding not UTF-8? Anything else unusual that you can think of? I'll try the repo but it's likely to be an environment thing, not an issue with the particular files.

I see Microsoft/intunedocs, is that the repo you mean? intunedocs-pr?

**Comment by roblourens** [comment]
Nevermind, I can repro it.

**Comment by roblourens** [comment]
The problem is with some line endings that are only `\r`. Not `\r\n` or `\n` as is typical. How did they end up that way? That's an unusual case and I'm not sure whether it's really a bug on the search tool.
