### ISSUE TITLE
Which version of JSON schema is VSCODE supporting?

### ISSUE THREAD

**Issue by kanitw** [Microsoft/vscode#34590]
The documentation (https://code.visualstudio.com/docs/languages/json) does not say specific version.  I know that VSCode supports draft-04 for sure as I am using it, but I wonder if it supports draft-06 too.  

Note that I originally asked this on [stackoverflow](https://stackoverflow.com/questions/46205308) but was suggested to ask here. In any case, it is probably worth updating the documentation anyway.  

Thanks!

**Comment by aeschli** [comment]
VSCode supports draft-04. I'll add it to the documentation.
