### ISSUE TITLE
Window not really maximize on startup (Debian 8 XFCE)

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#3459]
When I close VSC window in maximized state and restart VSC, the window not preserve maximized. But when I click right mouse on the title bar, the menu show as it in maximized state. To really maximize the windows, I must unmaximize it and maximize it again 
(Sorry for my bad English)

**Comment by Tyriar** [comment]
Closing as there have been no reports since.

**Comment by Stormherz** [comment]
@Tyriar seems like I'm having the same issue here.
Debian 8.6, XFCE 4.1
Window  is not preserving maximized state, though it's trying - once last maximized window is closed and I'm starting vscode once again - window is maximized only vertically, but not horizontally, which is quite unexpected =)

**Comment by Stormherz** [comment]
Let me know if any additional info/use case is required for reproducing the issue

**Comment by Tyriar** [comment]
@Stormherz it's likely an issue with Electron, I'll add the help wanted label as I probably won't have time to look into this any time soon.

**Comment by Tyriar** [comment]
Close this off as there's nothing we can do and it only applies to a subset of Linux distros. If you're still seeing the problem please create an issue in https://github.com/electron/electron
