### ISSUE TITLE
Visual Studio Code deleting content of git submodules inside a git project

### ISSUE THREAD

**Issue by jpierru** [Microsoft/vscode#346]
I have a git project that contains several git submodules of other projects and I have seen that the Git integration in Visual Studio Code takes a lot of times to "scan" my git project to in the end delete the content of my submodules leaving my git checkout corrupted.

**Comment by jpierson** [comment]
Strange and concerning as I'm looking at making more use of submodules in the near future.

**Comment by joaomoreno** [comment]
@jpierru can you provide your OS, Code and git versions?

**Comment by jpierru** [comment]
@joaomoreno OS is OSX 10.10.5 and git version is 2.3.2 (Apple Git-55). Visual Studio code version is 0.10.1.

**Comment by rogierschouten** [comment]
May be related to #901 ?

**Comment by joaomoreno** [comment]
Don't think it is related, this user is not merging/rebasing.

**Comment by jpierru** [comment]
I have updated to visual studio code 0.10.3, I'll see if the issue still persists. @joaomoreno that is correct I am not merging and rebasing at this time.

**Comment by jpierru** [comment]
Well, I guess this does not only apply to submodules, it looks like that if I wait long enough, all the files in my project are staged for deletion....
Is there a log from Visual Studio Code that I can look at to see what it is trying to do?

**Comment by jpierru** [comment]
Interesting, if i click the "Unstage All" button, the git checkout is now "fixed" and the git status looks like it is correct. I am not sure why on its first pass at computing the git status Visual Studio Code is staging every files for deletion.

**Comment by jpierru** [comment]
The submodules still show as modified, the reason is that their contents are still staged for deletion. If i unstage the changes in each of the submodules the git status is then finally clean.

**Comment by jpierru** [comment]
It does look like when you are loading a project (the first time?) into visual studio code it stages every files for deletion in the project and its submodules.

**Comment by jpierru** [comment]
Even after you clean up the mess, the submodule contents eventually are again staged for deletion.

**Comment by joaomoreno** [comment]
Is your project OS? Could I clone it and give it a try?

**Comment by jpierru** [comment]
Unfortunately it is not, I'll see if I can recreate it with a simple project.

**Comment by joaomoreno** [comment]
That would be :+1:

**Comment by joaomoreno** [comment]
Please reopen if there are more details.
