### ISSUE TITLE
Please update the icon for Mac pls pls 🙏 🙏 🙏 🙏

### ISSUE THREAD

**Issue by PTcampbell** [Microsoft/vscode#34600]
It really does not fit in with the Mac vibe. The filled in white space between the loop really kills me. Visual Studio at least has a subtle gradient and its negative space cut out (transparent). Like honestly it should not take you that long. I will do it. Please. For the love of.

**Comment by chrisdias** [comment]
please see: https://github.com/Microsoft/vscode/issues/6607#issuecomment-334600845
