### ISSUE TITLE
How to call format command in extension?

### ISSUE THREAD

**Issue by eshengsky** [Microsoft/vscode#34608]
I'm developing a custom extension for vscode, I wonder how to call vscode inner format command?
I found nothing in api, I just want this:
```js
const editor = window.activeTextEditor;
// without this api now
editor.format();
```

**Comment by yume-chan** [comment]
If you want to format the active document, you can use

```` TypeScript
vscode.commands.executeCommand("editor.action.formatDocument")
````

If you want to format any specified document, seems there is no way to do that.

**Comment by eshengsky** [comment]
@yume-chan got it, thanks!
