### ISSUE TITLE
Lightbulb is only visible when you can see the first column

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34603]
This means you cannot see that code actions are available when authoring relatively long lines on a narrow monitor.

<img width="634" alt="screen shot 2017-09-19 at 8 00 55 am" src="https://user-images.githubusercontent.com/2193314/30568566-d5d08f42-9d10-11e7-9490-ec2759ba2200.png">

**Comment by jrieken** [comment]
Tricky... The current idea of the lightbulb is to utilise the often occurring leading whitespace of a line. That doesn't work with horizontal scrolling. We have ideas to also show the lightbulb in the hover which might mitigate this.

**Comment by stevencl** [comment]
Yes, just commented on the original issue here: https://github.com/Microsoft/vscode/issues/25174#issuecomment-331472857.

Perhaps we should close this issue and keep the discussion going in the original?

**Comment by jrieken** [comment]
Yeah, agreed. Closing as dupe of #25174
