### ISSUE TITLE
Code Box, Tabs Color and Behaviour

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#34609]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

The Monakai Themes have Reversed the Color of Selected and Background tab. The active tab is the same color as non selected items... Like compared to the list on the left, or selected text... While the Non Active Tabs have the color of active items. This ruins the initutivity of the layout!!!

Tab Behaviour, I would like the tabs to align like Chrome does, that app's got it right. so I can close opening codes boxes rabidly by clicking the X on the tab without constantly moving my mouse to align it with the X on the Next Tab

And Double Click on the file list Group/Folder should expand it. Not the single click. that is the Windows Standard. You cant have your expectations shift on you from app to app, that was the whole point of standard behaviours

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by SailorMax** [comment]
Same problem in almost all other dark themes, except "Red", "Solarized Dark" and "Tomorrow Light Blue" themes.
In files list active file has light background, but in tabs list - dark. Plus difference between active tab and tab bar colors is very small. When monitor has no high contrast and open only 2 tabs, hard to understand which is active.
