### ISSUE TITLE
View state is not retained when adding a folder

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#34619]
- Open VS Code with a folder
- Go to SCM view
- Add another folder to workspace

Expected: I should stay in SCM view
Observed: Switches to Explorer view

@bpasero FYI

**Comment by bpasero** [comment]
@sandy081 I would argue this works as expected? The action is to add more folders for a reason, so why not show them in the explorer?

**Comment by sandy081** [comment]
Ah I see. That's a valid point. Closing it as designed.
