### ISSUE TITLE
(Important) Syntax color problem after new update

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#34611]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:54:47.289Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
text-transform|flo|0.1.0
vscode-icons|rob|7.13.0
wordpress-snippet|tun|1.1.2
sort-lines|Tyr|1.3.0
---

Hi, after new update, I have syntax color problem!! Please check this because this color (purple) is not suitable for the eye and it is annoying. I haven't this problem on before versions.

# **Error:**

![ashampoo_snap_2017 09 19_08h51m00s_001_](https://user-images.githubusercontent.com/5067331/30575829-9b1a5592-9d18-11e7-875b-f8da38ebad06.png)

# **Correct:**
![ashampoo_snap_2017 09 19_08h52m05s_002_](https://user-images.githubusercontent.com/5067331/30575835-b3102ce4-9d18-11e7-9f6d-d6af6e8de67c.png)

**Comment by roblourens** [comment]
This is fixed in 1.16.1, update and try it again.
