### ISSUE TITLE
Smooth scrolling for Explorer and other scrollable elements

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode#34616]
As mentioned in https://github.com/Microsoft/vscode/pull/25286#issuecomment-324099312 `"editor.smoothScrolling": true` currently only affects the editor, not other scrollable elements like the File Explorer.

**Comment by intijk** [comment]
I would also love to have a strength parameter to tune the feeling of smooth movement if possible, the current animation movement in editor area seems too fast for me.
