### ISSUE TITLE
Toggle empty block comment doesn't work well in Python 

### ISSUE THREAD

**Issue by tomer-gavish** [Microsoft/vscode#34618]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.4

---

Steps to Reproduce:

1. Press the key binding Shift+Alt+A (Toggle block comment) when editing a python file.
2. Press again. The comment will not be removed, but a weird leftovers will be left.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@tomer-gavish Can you share an example? Screenshots and actual code will help

**Comment by tomer-gavish** [comment]
Yes.
Now I notice that it isn't reproduced if any text is selected, but only when the keyboard shortcut is pressed when no text is selected.

Try to insert the following line in a python script, with the cursor in the following position:
![image](https://user-images.githubusercontent.com/30431562/30780763-5cfd102c-a11b-11e7-9fcd-535380760fcf.png)

Press Alt+Shift+A (Without marking anything), and then again - and you'll get the following state:
![image](https://user-images.githubusercontent.com/30431562/30780783-c1dc0638-a11b-11e7-8825-39148fc4be88.png)

It seems that, when no selecting nothing, enabling and disabling block comments doesn't work. It's worth mentioning that this works in other editors, and this feature is pretty useful if you want to start a block comment with no text inside.

**Comment by ramya-rao-a** [comment]
I see something similar in javascript as well
When inside an empty block comment, toggling it just keeps adding more empty block comments

So this must be a generic problem.

**Comment by alexandrudima** [comment]
Caused by 5c58b8cb2d59e1151c87cf2fbe46f69b41a3620f
