### ISSUE TITLE
Add a new feature to easily copy a line to the next line

### ISSUE THREAD

**Issue by jineshmathew** [Microsoft/vscode#34614]
- VSCode Version: Version 1.14.2 (1.14.2)
- OS Version: 10.12.6 (16G29) Mac OS Sierra

Steps to Reproduce:

> 1. type a code in one line
> 2. now we have select the lines using mouse or trackpad and using the normal copy and paste method, replace it by a **shortcut key**
> 
 Thanks in Advance

Reproduces without extensions: Yes/No

**Comment by jhasse** [comment]
The following should work: <kbd>Cmd</kbd>+<kbd>C</kbd>, <kbd>Cmd</kbd>+<kbd>V</kbd>

**Comment by jhasse** [comment]
Should it though? You can even hold down <kbd>Cmd</kbd> and press <kbd>C</kbd>, <kbd>V</kbd>. I don't think there's much to gain by a dedicated shortcut (one less keypress and only for the first copy since you can repeat <kbd>V</kbd> after that).

**Comment by jineshmathew** [comment]
It is just a feature request. They can easily reject it if they want to but if you do something for the users using it will only help them to build a good product.

**Comment by thierer** [comment]
Don't `Copy Line Down` and `Copy Line Up` do what you're asking for? I don't know the keyboard shortcuts for Mac but you should be able to find out using the Command Palette:

![image](https://user-images.githubusercontent.com/240625/30592322-96ad5a3a-9d46-11e7-9e21-e952c12924ac.png)

**Comment by jineshmathew** [comment]
Thanks @thierer
