### ISSUE TITLE
Document continuous test tasks setup with PowerShell Pester

### ISSUE THREAD

**Issue by csharmath** [Microsoft/vscode#34610]
Hi !

This is one about documentation on how to setup VSCode with PowerShell and Pester running tests continuously with tasks

Steps to Reproduce:

1. Develop awesome PowerShell scripts / modules / DSC
2. Have awesome tests
3. Wanting to have those tests run on file changes
4. searching for docs on vscode https://code.visualstudio.com/Search?q=pester
5. can't find documentation
6. resorting to google and solves the problem, but would be nice to see some PowerShell love as well as it's barely even mentioned on vscode site @jpsnover

**Comment by ramya-rao-a** [comment]
cc @gregvanl @chrisdias @seanmcbreen

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1175

**Comment by csharmath** [comment]
thanks guys
