### ISSUE TITLE
Investigate use of ELECTRON_NO_ATTACH_CONSOLE for forked Electron processes in Windows

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3461]
We always thought that there was no way to `console.log` from an Electron process which is not launched from a command prompt. Doing so would throw since there was no stdout stream available. Ping @bpasero @dbaeumer @alexandrudima.

This would make it a hard task to setup the new `code` launcher in Windows too, related to #1704. Ping @Tyriar 

While investigating for #1704, I found out about `ELECTRON_NO_ATTACH_CONSOLE` from atom/electron#3692.

Using this flag would enable us to remove [this ugly code](https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L91). Needs investigation.

**Comment by bpasero** [comment]
Yeah I noticed this new environment variable.

**Comment by joaomoreno** [comment]
No-op.
