### ISSUE TITLE
From the git integration pannel, I cannot preview image files listed in the changes or staged section.

### ISSUE THREAD

**Issue by tluanga34** [Microsoft/vscode#34628]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.4

Steps to Reproduce:

1. Add some image files, then go to git integration pannel
2. Click on the images recently added in the changes section, then it will show error Git: cannot open <filepath>

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#3935
