### ISSUE TITLE
Toggle Panel doesn't work perfectly

### ISSUE THREAD

**Issue by tomer-gavish-crl** [Microsoft/vscode#34620]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.4

---
The "Toggle Panel" default key map (Ctrl + J) doesn't work if the terminal is the selected feature in the panel. It would open the panel, but when pressing it again while the terminal is open - it would enter a special character to the terminal instead of closing it.

Steps to Reproduce:

1. Make sure the lower panel is shown.
2. Press the TERMINAL tab.
3. Press Ctrl + J.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
So this should work automatically as the toggle panel command is in the `terminal.integrated.commandsToSkipShell` setting. I'm guessing you have overridden the setting and not included `workbench.action.togglePanel`. If not please share your settings.json file.
