### ISSUE TITLE
Support inline and side by side view for Diff files

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#34623]
Viewing a Diff file (`.diff`, `.patch`, or `.rej`) in VS Code shows syntax highlighting for the diff. It would be great if the contents of a Diff file could be presented in the same way that it presents actual differences between files under Git version control, which would allow for side by side and inline views.

Examples:

Here is a `.diff` file open in the editor:

<img width="782" alt="screen shot 2017-09-19 at 12 05 23" src="https://user-images.githubusercontent.com/208434/30584605-f0f680ac-9d32-11e7-8016-6d8c690f774b.png">

Here is the live file differences shown in VS Code:

<img width="1248" alt="screen shot 2017-09-19 at 12 04 42" src="https://user-images.githubusercontent.com/208434/30584638-0604f992-9d33-11e7-87a0-3aa6d5fdb977.png">

And here's its inline view:

<img width="1178" alt="screen shot 2017-09-19 at 12 05 00" src="https://user-images.githubusercontent.com/208434/30584644-0e190524-9d33-11e7-91f6-04d0cf300a97.png">

It would be great if the latter two views were available when viewing a Diff file.

- VSCode Version: 1.16.1
- OS Version: macOS 10.12.3

**Comment by alexandrudima** [comment]
This feature request is a great candidate for an extension.
- the extension would activate on `.diff` files
- it would contribute an action in the top right corner of editors showing `.diff` files
- when pressed, it would parse the currently opened `.diff` file
- it would invoke the `vscode.diff` command and pass two URIs that use a custom scheme like e.g. `diff-file://doc1` and `diff-file://doc2`
- based on the previously parsed `.diff` file, it would provide the text for the `diff-file` documents.
