### ISSUE TITLE
Git Extension: "Open Changes" shows incorrect difference for renamed, staged files 

### ISSUE THREAD

**Issue by thierer** [Microsoft/vscode#34629]
I admit that it's a niche scenario, but I think that what "Open Changes" shows for not-yet-staged changes to files that **have been detected as renamed in the index** is incorrect, at least inconsistent with how changes to files in the index are shown that have not been renamed.

Steps to Reproduce:

1. Create an empty directory and initialize a git repository in it.

1. In that directory create two files `file1.txt`and `file2.txt` with identical content:

```
abc defg hijkl mnop qrst uvwxyz
defg hijkl mnop qrst uvwxyz abc
hijkl mnop qrst uvwxyz abc defg
mnop qrst uvwxyz abc defg hijkl
qrst uvwxy zabc defg hijkl mnop
uvwxyz abc defg hijkl mnop qrst
```

This exact content is somewhat important, as I've confirmed that it triggers git's "rename detection" (checked with git v2.14.1).

2. Stage and commit both files.
3. Duplicate the first line in both files.
4. Rename `file2.txt` to `file2-renamed.txt`.
5. "`Stage All Changes`":

![image](https://user-images.githubusercontent.com/240625/30590638-c438d292-9d3f-11e7-9384-607f52359ba8.png)

6. Now `Open Changes` does the right thing for both files, that is, it shows the changes between HEAD and the staged version:

`file1.txt`:

![image](https://user-images.githubusercontent.com/240625/30590983-402450e2-9d41-11e7-8708-380a4b413317.png)

`file2-renamed.txt`:

![image](https://user-images.githubusercontent.com/240625/30590958-241aa07c-9d41-11e7-8448-84c473039da3.png)

7. Duplicate the first line in both files once more, **but don't stage these changes**.

8. Now `Open Changes` still shows the right thing for `file1.txt` (in this case the changes between the staged version and the file in the working tree):

![image](https://user-images.githubusercontent.com/240625/30591125-e241344e-9d41-11e7-8304-3b43e2d6acae.png)

As the content of both files is identical both in the index and the working tree, I would have expected the exact same result for `file2-renamed.txt`, but now the left side **is just empty instead of showing the staged version**:

![image](https://user-images.githubusercontent.com/240625/30591172-0580730c-9d42-11e7-82db-2fa1eeb147db.png)

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.12.13-1-ARCH

**Comment by joaomoreno** [comment]
Hehe great catch! Would you like to [attempt](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/contentProvider.ts#L69) to [fix](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L83) it?

**Comment by petercr** [comment]
So is this issue still open and up for _**grabs?**_ If so I would like to try to help 👍

**Comment by joaomoreno** [comment]
@petercr Just look above your comment, there's a PR for it already: https://github.com/Microsoft/vscode/pull/34690
