### ISSUE TITLE
Allow to drop files onto the "Open Editors" view 

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#34625]
I really like the fact that I can drag files between windows, but it seems odd that they need to be dropped into the editor pane. Dropping into the open editors view would seem much more logical, but it doesn't work. I can see the cursor change from a small + to an arrow as I move around the open editors view, so it looks like it is trying to do the drop...

**Comment by isidorn** [comment]
PR welcome, code pointer https://github.com/Microsoft/vscode/blob/joh/ftp/src/vs/workbench/parts/files/browser/views/openEditorsViewer.ts#L428

If more users ask for this I can also look into it

**Comment by fussinatto** [comment]
@isidorn Link is dead. Did you mean
https://github.com/Microsoft/vscode/blob/65b9a0de2d5e9625bb39233765a434af4357a2c6/src/vs/workbench/parts/files/browser/views/openEditorsViewer.ts#L428

**Comment by isidorn** [comment]
Yes, here's the fixed link
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsViewer.ts#L428

**Comment by lohxx** [comment]
I'm interested in contributing with this issue

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/535fc34ba442fc22bc02008c83fe4ee1ab38f23b
