### ISSUE TITLE
Investigate to support 0-folder workspaces

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34622]
We should see if we could support workspaces with 0 folders.

/cc @sandy081

**Comment by bpasero** [comment]
Our code is quite fit for this, I only found the following that still need multi root adoption (via @dbaeumer work) that currently hardcode `workspace.folders[0]` usage:
* `processRunnerDetector.ts`
* `processTaskSystem.ts`
* `task.contribution.ts`

Once that is in we should remove the following checks for `folders` having entries:
* `workspaceMainService#113`
* `Configuration#393`

And then we can enable the "Remove Folder" action when only one root is there:
* `fileActions.contribution.ts#95`

**Comment by sandy081** [comment]
I think we should also update the schema of workspace configuration file to allow no entries for folders

**Comment by dbaeumer** [comment]
The places where I use folders[0] is when I am sure that I am in a folder workspace.

**Comment by bpasero** [comment]
**Verification:** remove all folders from a workspace configuration file and verify you see no undesired behaviour. The explorer should show up as empty.
