### ISSUE TITLE
Recently opened files refuse to disappear from suggestions

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#34630]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.1
python|don|0.7.0
pgsql|dou|0.0.8
EditorConfig|Edi|0.10.1
vsc-material-theme|Equ|1.0.2
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
code-spell-checker|str|1.4.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file (Ctrl+P).
2. See a file you don't want, like crap from `dist` or `coverage`
3. Put the `dist` or `coverage` folder into `files.exclude`.
4. The file is still suggested for opening.
5. Clear recently opened documents.
6. The file is still suggested for opening.

And it's always the top suggestion as well. Extremely annoying.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6904
