### ISSUE TITLE
Find all references not working from diff view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#34631]
Title says it all. Open some typesript file in a diff view, try find all references. I never get any results. I nicely get results if I invoke find all references on a regular file view

fyi @joaomoreno

**Comment by mjbvz** [comment]
This issue is similar to #34034

**Comment by joaomoreno** [comment]
@isidorn Which side of the diff view?

**Comment by isidorn** [comment]
@joaomoreno left side, right side works properly

**Comment by joaomoreno** [comment]
Uffff, long standing issue man. Closing for the same reasons as #34034
