### ISSUE TITLE
app won't update on macOS

### ISSUE THREAD

**Issue by timbedard** [Microsoft/vscode#34635]
I have tried with both regular VS Code and Insiders.

- VSCode Version: Code - Insiders 1.17.0-insider (b0c0634339c6f64a5c7f08b56fe732fb9154d3c4, 2017-09-15T05:10:59.353Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
python|don|0.7.0
---

Steps to Reproduce:

1. Install VS Code on macOS Sierra (10.12.6).
2. When update notification appears in bottom left, right click and select Restart to Update.
3. Wait for application to close, do its work and restart.

The update notification appears again, regardless of how many times it is told to update.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
