### ISSUE TITLE
Files not showing up in workspace explorer

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#34638]
- VSCode Version: 1.16.1
- OS Version: MacOS Sierra

Steps to Reproduce:

Here's a quick screencast: https://www.screencast.com/t/fVnc2I4u9uL
Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
