### ISSUE TITLE
Freezing v1.16.1 x64 on Win10 Pro but CPU use is under 5%

### ISSUE THREAD

**Issue by JanPSchneider** [Microsoft/vscode#34636]
- VSCode Version: 1.16.1
- OS Version: Win 10 Pro 1703, latest official build

Steps to Reproduce:

1. Use the programm (no special use requiered, only 1 to 4 small Javascript files open.
2. After some minutes it starts freezing for some seconds, then works again, until it freezes again. It seems,that it freezes more often the longer it is used.    #freezing

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Can you try running `code --disable-extensions` and see if you still experience the issue?
This is to ensure none of you installed extensions are causing the problem

**Comment by JanPSchneider** [comment]
I closed the Microsoft Win 10 Mail App (https://www.microsoft.com/de-de/store/p/mail-und-kalender/9wzdncrfhvqm?wa=wsignin1.0) and since then Visual Studio Code is running smooth again -
 maybe this "solved" the problem.

**Comment by ramya-rao-a** [comment]
@bpasero Any reason why the 2 might be connected?

**Comment by bpasero** [comment]
No :-/

**Comment by JanPSchneider** [comment]
I disabled the extensions and it seems to be running better. But sometimes I only see the background (the dark grey) for some seconds, until it shows the code again.

**Comment by bpasero** [comment]
Ok, if you can pin point it to a specific extension, please let us know.
