### ISSUE TITLE
[Multi-Repo] Deleting Git Repo on Disk Does Not Remove Repo From List

### ISSUE THREAD

**Issue by jd-carroll** [Microsoft/vscode#34645]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
(Other extensions excluded)

Steps to Reproduce:

1. Open a folder with multiple git repositories as subdirectories
2. Manually delete one of the folders from the file system (outside of VS Code)
3. BUG: Repo does not disappear from the list on the version control tab

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Great catch!
