### ISSUE TITLE
Update vs code Fedora

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#34640]
I have fedora 26, Vs code

    Version 1.16.0
    Commit 787b31c0474e6165390b5a5989c9619e3e16f953
    Date 2017-09-06T16:19:37.192Z
    Shell 1.7.3
    Renderer 58.0.3029.110
    Node 7.9.0
    Architecture x64

And it keeps showing 

[![enter image description here][1]][1]

In the main menu too. I tried updating it like [this][2]

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    
    Then update the package cache and install the package using dnf (Fedora 22 and above):
    
    dnf check-update
    sudo dnf install code

Do I have the latest version? Is it a bug in vs code that keeps notifying for updates? Or do I have to update it in some other way?

  [1]: https://i.stack.imgur.com/gonhG.png
  [2]: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

**Comment by loretogutierrezjr** [comment]
There is a latest version of VS Code it's <a href="https://code.visualstudio.com/updates/v1_16">1.16.1</a>

**Comment by elieobeid7** [comment]
Thank you, updates are not being pushed to repo? Do I have to download it from the browser?

**Comment by loretogutierrezjr** [comment]
I think it's still in progress.. maybe you can try to update after sometimes until it official.:)
Linux version still not there in documentation.

**Comment by elieobeid7** [comment]
Ok thank you

**Comment by batisteo** [comment]
Still no 1.16.1 in sight https://packages.microsoft.com/yumrepos/vscode/
Is it a manual process or automatized?

**Comment by batisteo** [comment]
It’s now present! Thank to the people who contributed to that! 🎉

**Comment by Tyriar** [comment]
Sorry about the issues, we had signing problems and some key team members were out of the office.

**Comment by bsienn** [comment]
I am also stuck with older version.
The latest is ATM Version 1.17.1

But on my system it's Version 1.17.0
and the update notification stays there.

OS: Fedora 26.
Note: I did add the repo and updated using instruction on download page.

**Comment by Tyriar** [comment]
@bsienn we're having issues with our infrastructure, rest assured we're working on it 👍
