### ISSUE TITLE
Allow drop of file or URL from browser into editor to paste it

### ISSUE THREAD

**Issue by ssteinerx** [Microsoft/vscode#34647]
- VSCode Version: Code - Insiders 1.17.0-insider (38853832f83c75a76412d3586dfb8bdeb97a8777, 2017-09-14T07:44:11.087Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
python|don|0.7.0
MagicPython|mag|1.0.12
vscode-antlr4|mik|1.1.10

---

Steps to Reproduce:

1. Drag a URL from navigation bar in browser to document in VSCode
2. See that VSCode shows green "+" indicating it's ready to accept drop
3. Let go and watch the dropped URL fall to the floor, never to be seen again

---

Desired Behaviour:
Insert the URL into the document at the drop point.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Its not just the url, any selected text for that matter behaves the same

**Comment by ssteinerx** [comment]
@ramya-rao-a Apparently I don't use that "much" 'cause I never even noticed.  I have had issues with dropping URLs in other apps and just figured "oh, that again..."  Should I update the title?  URL drop has never worked, not sure if the whole drop-any-text-on-floor behaviour is new.

**Comment by ramya-rao-a** [comment]
I dont see why a URL drop would be different from a text drop. Both involve selecting text and moving it to a different application

I'll let @alexandrudima and @bpasero decide

**Comment by ssteinerx** [comment]
I'm pretty sure the drop item in OS X is an object that the target has to handle properly or it falls on the floor when you drop it.

**Comment by stef-levesque** [comment]
@ssteinerx in the meanwhile, you can use https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-link

`link: Open link in editor (read-only)`

**Comment by ssteinerx** [comment]
@stef-levesque  -- thanks but I'm not sure what that has to do with drag & drop.   I'm not having problems opening links, this is about dropping a dragged URL from a browser's address bar directly into an open VSCode document.

**Comment by stef-levesque** [comment]
my bad :)

**Comment by bpasero** [comment]
@ssteinerx to be clear you want that URL to be pasted into the editor as text?

**Comment by ssteinerx** [comment]
@bpasero Yes, just paste the URL as text.  VSCode can already handle opening it with cmd-click so there's no special handling required other than getting the URL text out of the dropped object.

**Comment by robsonsobral** [comment]
I think the title should be "Allow drop of text into editor to paste it".

**Comment by stef-levesque** [comment]
Just to confirm, can we leave the default behavior for drop in a `previewHtml` ? 
The Editor part of [3dviewer extension](/stef-levesque/vscode-3dviewer) rely on that to properly work.

Incidentally, drag-and-drop doesn't seems to work on 1.18 Windows, but works fine on the Insiders build.
