### ISSUE TITLE
Import statement snippet inconsistent between .ts and .tsx files

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#34646]
1. Create a .ts file
2. Type `import`
3. Press tab to activate the "import statement" snippet

Expected and actual: completes to `import {  } from "module";`

1. Create a .tsx file (TypeScript + JSX)
2. Type `import`
3. Press tab to activate the "import statement" snippet

Actual: completes to `import name = require('');`

Expected: completes to `import {  } from "module";`

Is there any reason why the snippet is inconsistent between .ts and .tsx files?

**Comment by mjbvz** [comment]
Yes this is unintentional. I've marked this as help wanted in case anyone want to take a look. Here are the relevant snippet files: https://github.com/Microsoft/vscode/tree/master/extensions/typescript/snippets

**Comment by OliverJAsh** [comment]
@mjbvz Thanks! See https://github.com/Microsoft/vscode/pull/34653

I was also thinking it would be useful to add this to .js and .jsx extensions. What do you think?

**Comment by mjbvz** [comment]
Thanks for the PR! The change should be in the next insiders build

Yes I think adding the same for js/jsx also make sense. Did you want to submit another PR that copies these snippets over to js/jsx?
