### ISSUE TITLE
Feature request: Argument placeholders after function autocompletion?

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#34641]
First of all, Thank You for this awesome code editor!

In Sublime when I press tab and a function is autocompleted, it provides argument placeholders. I miss that feature so much in VSCode and I'm sure everybody who migrated from Sublime will wish that feature. 
![sublime snip](https://i.imgur.com/1CkZM8r.jpg)

There is this setting in the dart extension, but I want it globally, for all the languages I use.
![dart extension settings](https://i.imgur.com/CGlx5PS.jpg)

**Comment by ramya-rao-a** [comment]
Different languages hav different syntax, so providing the same solution to all will not work.
cc @jrieken to confirm

If you find this missing in the language of your choice, then log the feature request in the repos of the respective extensions that provide language features.

As far as i know, typescript/javascript allows this by setting `typescript.useCodeSnippetsOnMethodSuggest` and the Go extension allows this via `go.useCodeSnippetsOnFunctionSuggest`

**Comment by jrieken** [comment]
Yes, every language has to decide. We do support the building blocks, completions and completion as snippet, the rest is up to the extensions

**Comment by DevotionGeo** [comment]
Thank You @ramya-rao-a and @jrieken for the responses! :)

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
