### ISSUE TITLE
Javascript "Rename symbol" does not rename destructured variables

### ISSUE THREAD

**Issue by dchristensen** [Microsoft/vscode#34650]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:
Given the following code: 

```Javascript
let obj = { x: 'x', y: 'y', z: 'z' };
const { x, y, z } = obj;
console.log(x, y, z);  // "x" "y" "z"
```

If I execute the "Rename Symbol" command while the cursor is on the `x` property of `obj` and rename the property, the destructured variable is not renamed and the code is left in a invalid state.

```Javascript
let obj = { newNameX: 'x', y: 'y', z: 'z' };
const { x, y, z } = obj;
console.log(x, y, z); // undefined "y" "z"
```
I would expect the `x` variable to be renamed to `newNameX` and the usage of `x` in the `console.log` to also be renamed.

This problem also exists for Typescript code.
This appears to have been reported and fixed once before (#6227).

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. I believe this is already tracked by https://github.com/Microsoft/TypeScript/issues/15787 

Closing as upstream
