### ISSUE TITLE
Editor freezes while typing on 52,000+ lines file

### ISSUE THREAD

**Issue by clarking** [Microsoft/vscode#34655]
Hi, i have a very large perl script that contains a hash of 52,000+ lines and when i start typing on that file the editor starts to freeze for a moment, then allows me to type one or two strokes before getting stuck again, it's pretty frustrating trying to edit that file on vscode.

Please help me with this issue and keep up the awesome work!

- VSCode Version: 1.16.0
- OS Version:  Xubuntu Linux 4.10.0-33-generic #37~16.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.Open a 50,000+ lines file 
2.Start typing

Reproduces without extensions: Not tested

**Comment by alexandrudima** [comment]
@clarking  Please launch `code --disable-extensions` and check if the sluginess reproduces.

**Comment by clarking** [comment]
if i use the `--disable-extensions` argument the error is gone, it seems that is an issue with the vscode-perl extension, thank you and keep up the good work.

**Comment by alexandrudima** [comment]
:+1: The best would be to reach out to the extension author.
