### ISSUE TITLE
Unreadable search input box (too tight)

### ISSUE THREAD

**Issue by motocarota** [Microsoft/vscode#34657]
Hello!

It looks like that when I open the search bar (command+F) it is initialized with not enough horizontal space, so the input field it is barely visible, and nothing I type inside it is readable unless I manually give more room to it.

![image](https://user-images.githubusercontent.com/3191993/30612181-0efa9d94-9d84-11e7-9131-85db3711aa45.png)

Even opening the search box with some selected text gives the same behavior

![image](https://user-images.githubusercontent.com/3191993/30612221-245bc924-9d84-11e7-9d79-06af7de791a5.png)

If you manually resize the input box the new size is kept until restart.
If you need additional info I'm at your service

- VSCode Version: 1.16.1
- OS Version: Mac Os Sierra 10.12.6

Steps to Reproduce:

1. open any file
2. open the search box (command + F)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
We are tracking this in #33349
