### ISSUE TITLE
Warning about merge conflicts when all conflicts are resolved?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34651]
- Have a file with merge conflicts
- Resolve all conflicts
- Click `+` to stage the file
- Get merge conflicts warning:

![image](https://user-images.githubusercontent.com/323878/30608173-5d25b8a8-9d2c-11e7-8f0f-981a163eca61.png)

This makes me think that I missed a conflict, but all are resolved. Is it a bug or is it supposed to be a general confirmation message? I think this is new but I don't resolve conflicts that often.

**Comment by joaomoreno** [comment]
#33983
