### ISSUE TITLE
YAML Syntax Highlighting Breaks on Large Files

### ISSUE THREAD

**Issue by cbluth** [Microsoft/vscode#34658]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.18
hugofy|akm|0.1.0
better-toml|bun|0.2.0
python|don|0.7.0
json-tools|eri|1.0.2
Go|luk|0.6.65
terraform|mau|0.0.17
cpptools|ms-|0.12.4
gitlink|qez|0.3.2
Ruby|reb|0.15.0
vscode-icons|rob|7.13.0
markdown-all-in-one|yzh|0.9.0

---

Steps to Reproduce:

1. generate large yaml file (`kubectl get all --all-namespaces > large-yaml.yaml`)
2. highlighting breaks (note line numbers for relative size, also node sidebar):
![image](https://user-images.githubusercontent.com/6709636/30614102-ea2e4314-9d4f-11e7-9f6c-7e55644c8d70.png)

**Comment by aeschli** [comment]
There's a maximum number of lines we colorize. That's for performance reasons.
To check if that applies here, open the dev tools (Help > Toggle Developer Tools) and check the console tag.
