### ISSUE TITLE
German Umlaute saved in wrong format

### ISSUE THREAD

**Issue by krehberger** [Microsoft/vscode#34662]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. Create Powershell Script with the following Statement and save it as "TestUmlaute.ps1"
    `$test = "Möwe" -replace "ö", "oe"
     write-host $test`
     Starting the script in VSCode doesn't replace the character "ö" with "oe" in the string "Möwe".
2. Open the file "TestUmlaute.ps1" in Powershell ISE. All Umlaute are displayed with wrong characters:
    `$test = "MÃ¶we" -replace "Ã¶", "oe"
      write-host $test`
     

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
> Starting the script in VSCode doesn't replace the character..

@krizzdewizz What do you mean by starting the script?

**Comment by krehberger** [comment]
Starting means e.g., run the script with F5 in Debugging mode (with or without breakpoints).

**Comment by ramya-rao-a** [comment]
Then this should be an issue for the Powershell extension isnt it?
