### ISSUE TITLE
DebugConfigurationProvider: provide snippets for launch.json

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#34668]
- VSCode Version: 1.16.1
- OS Version: mac

Steps to Reproduce:

https://github.com/Microsoft/vscode/issues/12735#issuecomment-329381584

@weinand I'm writing a extension to provide debug  configurations.

as mentioned at docs `"initialConfigurations": "extension.eggjs.provideInitialConfigurations"`

my question is how to link a command to `configurationSnippets`?

had try `"configurationSnippets": ["${command.extension.eggjs.provideConfigurationSnippets}"]` and `"configurationSnippets": ["extension.eggjs.provideConfigurationSnippets"]` without luck.

the command is not trigger.

**Comment by isidorn** [comment]
We are moving away from this model.
The new way of doing things is using a ConfigurationProvider. More about this can be found [here](https://github.com/Microsoft/vscode/blob/joh/ftp/src/vs/vscode.d.ts#L5658)

Your feature request could be solved by extending the ConfigurationProvider to also provide snippets, thus renaming the issue

**Comment by weinand** [comment]
Since the new introduce DebugConfigurationProvider addresses this need, we can close this request.

**Comment by weinand** [comment]
Reopening since the `DebugConfigurationProvider` does not (yet) support to provide snippets.

**Comment by atian25** [comment]
@weinand additional 2 request:

1. `DebugConfigurationProvider` should support `compounds`
2. allow hidden or sort order at debug configuration drop list.

![image](https://user-images.githubusercontent.com/227713/32151329-173d54f8-bcea-11e7-9e84-ee2975af8e04.png)

We only want to show user: `Egg Debug` and `Egg Debug with brk`(which is compounds)

so feature request is either provide a hidden property for `"Egg Master", "Egg Agent", "Egg Worker"`, or `compounds` should show at top. 

```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "debug" ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "auto",
      "port": 9999
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Master",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "debug", "--", "--inspect-brk" ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "inspector",
      "port": 9229
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Agent",
      "restart": true,
      "protocol": "inspector",
      "port": 5800
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Worker",
      "restart": true,
      "protocol": "inspector",
      "port": 9999
    }
  ],
  "compounds": [
    {
      "name": "Egg Debug with brk",
      "configurations": [ "Egg Master", "Egg Agent", "Egg Worker" ]
    }
  ]
}
```

**Comment by weinand** [comment]
@atian25 please don't add new feature requests onto existing but unrelated issues. They will be ignored. Create new issues.

**Comment by isidorn** [comment]
I believe this can be done using the [`CompletionItemProvider`](https://github.com/Microsoft/vscode/blob/isidorn/explorerCommands/src/vs/vscode.d.ts#L2921) API.
Simply register a CompletionItemProvider only for `launch.json` file using this [API](https://github.com/Microsoft/vscode/blob/isidorn/explorerCommands/src/vs/vscode.d.ts#L5532). And your `CompletionItemProvider` can returtn `CompletionItems` which inserts a `SnippetString` as an `insertText`.
