### ISSUE TITLE
Not able to specify a -- (double hyphen) as args in launch.json, while debugging with lldb

### ISSUE THREAD

**Issue by thecoder138** [Microsoft/vscode#34661]
My c++ source code binary takes -- as a means of differentiating certain args.
e.g. ./binary  arg1  --  sub_arg1
when I specify in launch.json:
"args": ["arg1  -- sub_arg1"]
launch.json completely ignores standalone "--".

How do I trick launch.json into thinking that -- is an actual argument to the binary. 

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the C++ debug extension here https://github.com/Microsoft/vscode-cpptools
