### ISSUE TITLE
Ionic project: Error Debug adapter process has terminated unexpectedly, when "Run on Android device"

### ISSUE THREAD

**Issue by imarem** [Microsoft/vscode#3466]
HI,
When i try to "Run on Android device" with the pluguin Cordova " on a Ionic project, allways aperars same error.

"Error Debug adapter process has terminated unexpectedly"

Anyone know what 's going on? or where I can see more logs or some kind of information? is not enough to solve the problem....

Thanks!!!

**Comment by MSLaguana** [comment]
This was a bug in https://github.com/Microsoft/vscode-cordova which should be fixed in the latest update of the extension.

**Comment by joaomoreno** [comment]
Awesome.

**Comment by imarem** [comment]
Hi MSLaguana,

I downloaded the plugin yesterday, and i think that is the latest update.

This is my system information:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v4.2.1

I don't know what else to look, you need any more information? Please do not close the issue.

**Comment by MSLaguana** [comment]
Version 1.0.2 of the cordova-tools extension had an issue, and only a couple of hours before I posted my response we uploaded 1.0.3 which had the fix. If you re-install the extension it should work. If not, please open an issue at https://github.com/Microsoft/vscode-cordova and we'll follow up there.

**Comment by imarem** [comment]
Yeaah!  XD

With a version 1.0.3 of the cordova-tools extension run perfectly!!

Thanks a lot for your supoort!! you save my day!!
