### ISSUE TITLE
Color Picker not working with JSON files at 1.16.1

### ISSUE THREAD

**Issue by tfauvell** [Microsoft/vscode#34663]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create new "test.json" file
2. Paste the following...
{
    "text-color": "#000000"
}
3. No color box shows up. Color picker works fine for HTML and CSS file formats.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
To have that work, you need a schema associated with the json file.
The schema has to say `format: color` on property that represents a color.

**Comment by tfauvell** [comment]
Thanks @aeschli, something still isn't right. I created a custom schema, and properly mapped my custom schema in my workspace to my test_colopicker.json (test workspace attached [VSCode_ColorTest.zip](https://github.com/Microsoft/vscode/files/1326275/VSCode_ColorTest.zip)). I could only get HEX and short HEX colors to show a color decorator. RGB, RGBA, HSL, HSLA, and HTML colors which are working in HTML; don't show a color decorator. Are these color formats not supported yet?
![image](https://user-images.githubusercontent.com/18420319/30769945-1c8daef4-9ff2-11e7-9512-23cbadf98b47.png)

**Comment by aeschli** [comment]
In JSON we currently only support hex color formats. It's what we settled on in the VSCode config files. From a JSON schema perspective, the 'color' format is not standardized, it is a VSCode specific extension, and I wanted to keep it simple.
If this is essential for you, you could think to support through a VSCode extension that adds a colorProvider to your type of files.
