### ISSUE TITLE
Fix the behavious of Git Credential Manager for Windows Popups

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#34667]
There is already an issue about this 
https://github.com/Microsoft/vscode/issues/33313
Why closed?

I don't think it is a good behavious,   

1. first, you should tell user this popup is pop by vscode (I cost some time to find out this)
2. you should show the `git remote -v` at popup top, then user can know which account to login (it is necessary when user has many account. )
3. Now, no error message for wrong Credential , even more, it would popup again and again after close, 
are you kidding me?Click close button means user don't want to use vscode to manage git in this project   , keeping popup is a really bad and annoying behavious .

Please fix it!

**Comment by joaomoreno** [comment]
This popup is not by VSCode. Code launches git, which launches whatever credential manager you have installed, which shows you the popup.

You'll get exactly the same behaviour if you go into a command line and type `git fetch`.

We might simply disable autofetch, since this seems to annoy many people.

**Comment by eromoe** [comment]
I thought it is vscode excute some code to call https://github.com/Microsoft/Git-Credential-Manager-for-Windows  to open a popup. Is that right? 

In command line , after several times click close button,  it would shows something like below
```
Logon failed, use ctrl+c to cancel basic credential prompt.
Logon failed, use ctrl+c to cancel basic credential prompt.
error: unable to read askpass response from 'D:/Git/mingw64/libexec/git-core/git-gui--askpass'
```

So does vscode can't get such return information and give user a tip ?
Maybe use a  winform or something else to wrap the external popup , then you can display error message and also let user know it is vscode who open this popup.  
Then you can add a button on this winform,  use to send `ctrl+c` to to cancel basic credential prompt.
