### ISSUE TITLE
can not type any char open  under tmux

### ISSUE THREAD

**Issue by foxundermoon** [Microsoft/vscode#34675]
mac os `10.12.4`
code  `1.16.1`

enter `tmux` mode
then `code .` open the editor
just can type  `tab` char  ,type other char is no response when in new   document or  in file name input for  creat file/folder  and after  `Command + P`  in the  command input also can not type any char

**Comment by bpasero** [comment]
https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
