### ISSUE TITLE
How could I copy with Line numbers?

### ISSUE THREAD

**Issue by diigu** [Microsoft/vscode#34672]
I Googled this but found nothing useful.
Sublime has this plugin: CopyWithLineNumbersReloaded.
How could I copy codes with line numbers in VS Code?
Or is there any plugin like this in VS Code??'

(Picture is in Sublime for example.)

![qq 20170920115402](https://user-images.githubusercontent.com/5822468/30626201-dd97446a-9dfa-11e7-8393-ced7e641ee7a.png)

**Comment by mliq** [comment]
@diigu Related but not the same, this copies the file path and line number: https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line

Might be a good starting point for someone looking to create your desired functionality.

**Comment by diigu** [comment]
@mliq Thanks, I tried this plugin, but it can only copy one/first line. If there is no such extension, I'll try to create one in the future.

**Comment by diigu** [comment]
@mliq I have almost done this function, but last step: how could I put target string into clipboard? I found "import copypaste = require('copy-paste');", but how to use it ? I didn't find any guide to this.

**Comment by diigu** [comment]
@mliq  Hi, I have finished this function and I had uploaded it to extension market.
Welcome to use this.
extension name: copywithline

Copy with line numbers

[https://marketplace.visualstudio.com/items?itemName=diigu.copywithline](https://marketplace.visualstudio.com/items?itemName=diigu.copywithline)
