### ISSUE TITLE
Horizontal scroll should work on window instead of text...

### ISSUE THREAD

**Issue by Pritraj** [Microsoft/vscode#34677]
Ref #32128

Here are GIF you asked for..

**Comment by Pritraj** [comment]
![window_scroll](https://user-images.githubusercontent.com/18588781/30628999-216035c0-9df7-11e7-90ab-9587e571d39f.gif)
![textscroll](https://user-images.githubusercontent.com/18588781/30628998-215d0ff8-9df7-11e7-8144-897425477ffe.gif)

**Comment by alexandrudima** [comment]
@Pritraj how do you "scroll" ?

 Do you perhaps use your laptop's built-in trackpad for horizontal scrolling ?

**Comment by Pritraj** [comment]
Yes I am scrolling with my laptops touchpad.

**Comment by alexandrudima** [comment]
Thank you for following up. Duplicate of #17476

**Comment by BladeMF** [comment]
Reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=784329&can=2&q=touchpad%20scroll&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
