### ISSUE TITLE
Pasting text into Replace-in-File Search field removes editor selection

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#34679]
This prevents you from proceeding with doing a search/replace in the selection.

---

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
php-formatter|Sop|0.2.4
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
javadebugger|don|0.1.3
python|don|0.7.0
phpunit|ema|2.1.1
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
code-runner|for|0.7.1
vscode-javac|geo|0.0.46
phpcs|ika|0.7.0
Go|luk|0.6.65
prettify-json|moh|0.0.3
mssql|ms-|1.1.0
cpptools|ms-|0.12.4
Ruby|reb|0.15.0
rewrap|stk|1.5.0
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

---

Steps to Reproduce:

1. Select text.
2. Edit > Replace.
3. Shift-Tab to focus the Search field.
4. Select All text in the Search field.
5. Paste a substring that exists in the selected text.
6. Your text selection is gone.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/17563, let's track it there.
