### ISSUE TITLE
Consider changing "files.autoSave": "afterDelay" to "on"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#3467]
I've made this mistake myself and just saw another user do it as well.
When you copy the default "files.autoSave": "off" to user or workspace settings, the logical change is to set "files.autoSave": "on" if you don't read the fine print about setting it to "afterDelay".
I think this also makes sense with the other option "onSave".
We would have: "off", "on" and "onSave".
The default settings file comment will still call out tuning the "autoSaveDelay".

**Comment by joaomoreno** [comment]
I also get this wrong every time I'm there.

`onSave` doesn't make much sense, though. One would *auto save on save*?

Besides `onFocusChange` (which I would personally have called `onFocusLost` or `onBlur`), the only other two options that make sense are `on` and `off`.

**Comment by bpasero** [comment]
I like the way it is and we already pushed this to people. We could add "on" to be an alias for "afterDelay" though.

**Comment by joaomoreno** [comment]
:+1:

**Comment by bpasero** [comment]
Closing. We should add a file menu option to enable this. Will be done as part of allowing programmatic changes to the settings.
