### ISSUE TITLE
Search: collapse but keep roots expanded

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34685]
One pattern I am seeing myself doing a lot is invoking the "Collapse" action on the search viewlet and now that I have multi root results, I see no results until I expand a root:

![image](https://user-images.githubusercontent.com/900690/30634559-ce368a68-9def-11e7-91c5-1b3e75112aa8.png)

Could we maybe collapse all but leave the roots expanded? Or, upon first collapse call we do that and upon the second we collapse also the roots?

**Comment by roblourens** [comment]
> Or, upon first collapse call we do that and upon the second we collapse also the roots?

hmmm...

**Comment by bpasero** [comment]
This still annoys me a lot, especially if the results are only coming from one folder:

![image](https://user-images.githubusercontent.com/900690/31989250-0fd58ff8-b972-11e7-863f-31d3408d85aa.png)

**Comment by roblourens** [comment]
Agreed, and there should be an external PR incoming for this. If not I'll fix it...

**Comment by bpasero** [comment]
@roblourens this behaves very nice now, thanks!
