### ISSUE TITLE
File Icon Theme not applied correctly

### ISSUE THREAD

**Issue by lbrndnr** [Microsoft/vscode#34686]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
python|don|0.7.0
vscode-great-icons|emm|2.1.16
vscode-ghc-mod|hoo|1.2.0
language-haskell|jus|2.3.2
cpptools|ms-|0.12.4

(1 theme extensions excluded)

---

The issue doesn't seem to be reproducible for anybody else. I have tried reinstalling the icon themes as well as vscode itself, without success. The problem is that some icons (in my case the Haskell file icon) is not displayed correctly. Instead, some other haskell icon is being used (that I don't know). See [this issue](https://github.com/PKief/vscode-material-icon-theme/issues/134#event-1256854834) to verify that this is not a bug in the theme itself.

Steps to Reproduce:

1. Install VSCode Material Icon Theme
2. Open a folder containing a haskell file using VSCode
3. The wrong haskell icon is displayed in place of the one provided by the installed theme.

It seems like the image cache is corrupted in some way. While this is not a serious bug, it seems weird nevertheless. Note that only the VSCode Material Icon Theme is not working as expected, any other theme works normally.

Reproduces without extensions: No, as the issue is directly linked to theme extensions.

**Comment by aeschli** [comment]
Can you open the dev tools (Help > Toogle Developper Tools), and inspect the icon that is wrong?

When I do this, that's what I see:
![image](https://user-images.githubusercontent.com/6461412/30973685-ff608d80-a46d-11e7-9ee5-3f7b2bb435b4.png)

So to me all looks fine. The icon seems to be the one that comes from the extension.

**Comment by PKief** [comment]
The left icon is shown on my computer and the right icon is from your screenshot:
![haskell_icons](https://user-images.githubusercontent.com/12248527/30975019-6f2cf9f2-a471-11e7-85a7-078970e586ab.png)

Could it be that your computers render the font family that is used in the SVG differently? If yes it is definitely an issue with the icon and not with VS Code.

PS: I'm working on a windows 10 machine.

**Comment by lbrndnr** [comment]
@PKief @aeschli Ok I guess this is an issue of the theme then. For me it's showing the same, wrong icon.

**Comment by aeschli** [comment]
Didn't even know that you can do all that inside a SVG :-) Don't know who is at fault here, the SVG or Chromium, which renders it.
I guess it's best to just draw these 2 lines with `path`, and not use a font.

Closing the issue unless you have an idea what could be done on our side.
