### ISSUE TITLE
How to show icon button in editor menu bar?

### ISSUE THREAD

**Issue by eshengsky** [Microsoft/vscode#34688]
According to this link: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands, I add `icon` filed in my extension's package.json as following:
```json
"contributes": {
    "commands": [
      {
        "command": "extension.lvmamaFix",
        "title": "修复当前文件",
        "category": "lvmama fix",
        "icon": {
          "light": "./images/001.png",
          "dark": "./images/002.png"
        }
      },
      {
        "command": "extension.lvmamaFixAll",
        "title": "修复指定目录下所有文件",
        "category": "lvmama fix"
      }
    ]
}
```
But there's no icon button displayed in editor menu bar.
Any help? thanks!

**Comment by ramya-rao-a** [comment]
See https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus for contributing to the editor title menu bar

You cannot add icons to the commands you contribute
You can add icons to the menu items in the editor title menu bar

```
"contributes": {
    "menus": {
        "editor/title": [{
            "when": "resourceLangId == markdown",
            "command": "markdown.showPreview",
            "alt": "markdown.showPreviewToSide",
            "group": "navigation"
        }]
    }
}
```
