### ISSUE TITLE
Set git.autofetch to disabled, by default

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34684]
Git autofetch makes auth popups come up on many users' machines. These popups come out of nowhere and don't indicate that their existence is due to Code spawning `git fetch`. AFAIK it is not possible to detect whether a `git fetch` will cause a popup to appear, since it depends on the user's configuration.

Many users have already expressed their will to have autofetch disabled by default simply because such a default enabled setting is _too magic_.

Furthermore, I keep getting ~10 issues per iteration in which I have to, yet again, explain the nature of the mysterious popup to surprised users.

I intend to disable autofetch by default due to this. The consequence is, of course, that the incoming changes won't be automatically updated any more by default, unless you enable the setting.

We can also introduce a one-time popup which prompts the user if he wants to enable autofetch in case a successful sync has happened, which is a good sign that proper credentials are configured.

@Microsoft/vscode, thoughts?

**Comment by jrieken** [comment]
Could we show an affordance in that status bar (instead of the auto-fetch-updated status indication of incoming/outgoing changes) that motivates you to enable auto-fetch and explains the details/implications of auto-fetch?

**Comment by joaomoreno** [comment]
That was my intention with the suggestion of showing the prompt at sync. I don't think we can afford to occupy more space in the status bar as it is.

**Comment by innerlee** [comment]
Can you add a link to the doc at the popup window showing how to properly configure credentials for some common senarios, like github?

**Comment by joaomoreno** [comment]
@innerlee We don't own the popup window.

**Comment by octref** [comment]
I don't know how everyone else is using the status bar, but I hide it completely since I don't like the color in Dark+ and most of the status bar items are useless to me.
One time popup sounds better to me.

**Comment by eamodio** [comment]
I wish there was another way around this because when there are no issues (with creds) auto-fetch is great. But I personally have had to turn it off because of some creds issues with 1 of my repos.  (See this thread from hell: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/429). From what I can gather from the behavior on my machine, the main issue is auto-fetch when there is network issues. I don't know if this is something that vscode could try to detect before issuing a `git fetch` command (of course it couldn't be 100% but maybe it helps a lot more cases?).

**Comment by chrmarti** [comment]
There is a Git config option that might help work around the issue and may lead to a fix: https://github.com/Microsoft/vscode/issues/26743#issuecomment-332574332

**Comment by joaomoreno** [comment]
Personally, I only use SSH keys for authentication, which solves the whole problem instantly.
