### ISSUE TITLE
Same file opened twice from network drive

### ISSUE THREAD

**Issue by MrZebra** [Microsoft/vscode#34687]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Open a network drive as the project root
2. Press Ctrl+P and select a file, which opens it in a tab
3. Use the side bar explorer panel to open the same file

This opens two copies of the same file, instead of just one.
Note also that right-clicking on the file's tab and choosing "Reveal in side bar" does not work for the file opened in step 1, but does work for the file opened in step 2.

This happens when the project root is a SAMBA share on a Linux machine, mapped as a network drive on Windows.  It does not appear to be due to case sensitivity problems.

This issue causes work to be lost, as changes made in one edit window overwrite changes made in the other edit window when saving.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This is most likely because of opening the same file with different casing, which basically is: https://github.com/Microsoft/vscode/issues/12448
