### ISSUE TITLE
when I click to open a folder inside the Explorer, children of that folder appeared below other folder, not the parent folder

### ISSUE THREAD

**Issue by huangxiaolu** [Microsoft/vscode#34691]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.2.0
vue|liu|0.1.5
cpptools|ms-|0.12.4
vuejs-extension-pack|mub|0.1.9
vetur|oct|0.9.7
vuehelper|oys|0.1.0
PostCSS|ric|1.0.1
JavaScriptSnippets|xab|1.4.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I don't know how to reproduce the bug. 

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Can you share some screenshots of each step?

**Comment by hytromo** [comment]
I had the same issue today.

The contents of the `backend` folder showed up under the root (project's) folder:

Backend closed: https://i.imgur.com/boFQE2S.png
Backend open: https://i.imgur.com/aJEdNBd.png

I switch a lot between different branches so folders that exist only on specific branches get deleted and show up again. This could have something to do with the bug but I don't know how to reproduce the problem step-by-step.

**Comment by joaomoreno** [comment]
#22269
