### ISSUE TITLE
Cannot modify `editor.insertSpaces` setting anymore

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3469]
Have a file test.txt:
```
function a() {
	var a = {
		x: 3
	};
}
```

Use the following settings in the user settings and make sure there are no workspace settings:
```
{
    "editor.renderWhitespace": true
    , "files.autoSave": "afterDelay"
    , "editor.tabSize": 4
    , "editor.insertSpaces": false
    , "files.trimTrailingWhitespace": false 
}
```

Open the file and the user settings side-by-side:
![image](https://cloud.githubusercontent.com/assets/5047891/13333173/fbf40c4e-dc05-11e5-85d2-1633e97e4e55.png)

Go in test.txt and press a Tab. It is ok, it inserts a tab character:
![image](https://cloud.githubusercontent.com/assets/5047891/13333197/15caf4ac-dc06-11e5-9073-4b298e65fbff.png)

Go to the settings and change `"editor.insertSpaces": true`.

Go back to the file and press another Tab. Observe, it still inserts tabs.

This used to work.

**The editor status contribution should change editor options only if there was a manual user interaction with the tab status for the file**

**Comment by isidorn** [comment]
Very cool catch!
