### ISSUE TITLE
Winston Logger has stopped logging in Debug console ( NodeJS )

### ISSUE THREAD

**Issue by prem911** [Microsoft/vscode#34702]
- VSCode Version: 1.16.1
- OS Version: Win 10 64bit

Steps to Reproduce:

1. For a NodeJS app which uses Winston logger, start it in debug mode
2. None of the winston log messages appear in the Debug console.
3. This used to work till the June drop.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please provide a repository which uses this logger you mention.
What node version do you have? Can you share your launch.configuraitons

thanks

**Comment by prem911** [comment]
@isidorn Here is the information required.
My NodeJS version is 8.1.4
Repo is https://github.com/prem911/winstonSample
launch.json is part of the source code.

npm start will show the winston log statement.
When we debug the program, we dont see the log statement.

**Comment by prem911** [comment]
Some more info : I tried with bunyan and pino, the other popular loggers for NodeJS.
These are also not working.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/19750

This logger writes directly to stdout. You can set `"console": "integratedTerminal"`, or use the Insiders build and set the new option `"outputCapture": "std"`.
