### ISSUE TITLE
Reinstalling an extension that is on the 'delete' list silently fails and is very confusing.

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3470]
- uninstalled vscode-eslint, this results in adding it to the about to delete on next restart
- reinstall vscode-eslint

There is no feedback that this didn't have any effect. 
I suggest that we check whether an extension that is about to be installed is on the 'delete' list. If it is then we inform the user with the suggestion to restart Code.

**Comment by joaomoreno** [comment]
This only makes sense if it indeed failed to delete the extension. When the extension successfully gets removed, this won't repro.

I agree with the suggestion!
