### ISSUE TITLE
TFS Associate work item is not working. I can select the work item but the text is not copying on source control message textbox

### ISSUE THREAD

**Issue by marcobaccaro** [Microsoft/vscode#34708]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
csharpfixformat|Leo|0.0.34
vscode-docker|Pet|0.0.18
path-intellisense|chr|1.4.2
githistory|don|0.2.3
gitlens|eam|5.1.0
tslint|eg2|1.0.8
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
code-runner|for|0.7.1
csharpextensions|jch|1.3.0
Angular2|joh|2.7.0
vscode-csharp-snippets|jor|0.2.0
vscode-icon-theme|jtl|1.5.0
mssql|ms-|1.1.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vs-keybindings|ms-|0.1.7
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.0
sass-indented|rob|1.4.2
code-spell-checker|str|1.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by PietheinHeemskerk** [comment]
I have the same issue. It started out a few weeks ago (I suppose after an upgrade of VS Code). I also use VS Code 1.16.1

**Comment by ramya-rao-a** [comment]
Can you please elaborate with repro steps?

**Comment by marcobaccaro** [comment]
Sure!



Marco Baccaro


________________________________

**Comment by giang-nh** [comment]
same issue!

**Comment by PietheinHeemskerk** [comment]
I updated my original comment with steps to reproduce.

**Comment by ramya-rao-a** [comment]
Looks like an issue with the TFS extension itself.
Can you please log the issue in the repo for the TFS extension?
If they feel there is something missing in the VS Code APIs, the we can re-open this issue here.

**Comment by pollusb** [comment]
I have the same problem. Can you tell me where to find this issue on "repo for the TFS extension"? Txs

**Comment by ramya-rao-a** [comment]
Find the extension in the marketplace
https://marketplace.visualstudio.com/items?itemName=ms-vsts.team

There is a Repository link there. 
https://github.com/Microsoft/vsts-vscode
