### ISSUE TITLE
FTP polish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#34704]
- [ ] verify file matching did not get broken on case insensitive file systems
- [x] Try to lazily add the FTP folder once ready, since currently the whole explorer is loading on startup
- [x] Fix broken copy ftp folder action -> https://github.com/Microsoft/vscode/issues/41547
- ~~Think about UI to add a new ftp root~~ -> that's extension buisness

from @bpasero 

- [ ] [fileActions](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L1374) seems to miss proper handling of the resource, e.g. not all resources are saveable
- [x] [textModelResolverService](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts#L39) should this also use the `supportsResource` check?
- [x] [textFileService](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileService.ts#L414) is probably OK because non-saveable resources will not return as dirty

**Comment by jrieken** [comment]
> editorService will always evaluate to true even if supportResource returns false

@bpasero Unsure, I’d say `&&` binds stronger than `||` but I might be missing something

> textModelResolverService should this also use the supportsResource check?

I kind of does, just the inverse by checking if the scheme is supported from the other side and defaults to the checking with the file service

**Comment by bpasero** [comment]
> Unsure, I’d say && binds stronger than || but I might be missing something

True, my mental compiler does not seem to follow the spec...

**Comment by jrieken** [comment]
> fileActions seems to miss proper handling of the resource, e.g. not all resources are saveable

Shouldn't this be decided by the service? I will throw a `ENOPRO` error when being called with an unknown scheme and things like the save action should simply handle such errors. I believe that makes things easier as it must handle save failure anyways

**Comment by bpasero** [comment]
@jrieken yeah that could work. the normal save action seems to just do nothing silently when the resource is not supported (I tried File > Save of a staged resource with git scheme). However, doing "Save As..." results in this:

![image](https://user-images.githubusercontent.com/900690/30737946-c3953bf0-9f88-11e7-9ff5-92db977179f8.png)

**Comment by jrieken** [comment]
Yeah, so the service works as expected and with my latest commit it stop printing the `toString`-implementation of `URI` but actually invokes it.

Maybe we are missing well defines error code and a standard file error? I did start to define some for the provider apis: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L39 and believe a super set of those should be well known to everyone dealing with the file service

**Comment by bpasero** [comment]
Yeah I am already using similar things for the file service from [`FileOperationResult`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L555). They are more high level than the basic node.js fs ones and I deal with those in most places where I call the file service.

**Comment by jrieken** [comment]
Closing as we have shelled out most items into separate issues or fixed tem
