### ISSUE TITLE
Problems resolving Marketplace CDN URL

### ISSUE THREAD

**Issue by hhubik** [Microsoft/vscode#34709]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
tslint|eg2|1.0.7
Angular2|joh|2.7.0
debugger-for-chrome|msj|3.3.0
JavaScriptSnippets|xab|1.4.1
---

Steps to Reproduce:

1.  ??

Reproduces without extensions: ??

I launch VS Code as a background process in GIT Bash running on my Windows system. From time to time (about once or twice a day),  the error message below appears in the Bash window from which I launched VS Code:
```
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NAME_NOT_RESOLVED,
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NAME_NOT_RESOLVED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NAME_NOT_RESOLVED
[main 4:27:40 AM] [uncaught exception in main]: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
[main 4:27:40 AM] Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:78173)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by bpasero** [comment]
Hard to say what this could be.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by hhubik** [comment]
@joaomoreno - I am not behind a proxy.

**Comment by joaomoreno** [comment]
Are you in a corporate network?

**Comment by hhubik** [comment]
@joaomoreno I am not.  It's a small home office network with two or three computers connecting to the Internet via an ADSL line.

**Comment by joaomoreno** [comment]
Is your DNS server special?

Can you ping all these domains? https://code.visualstudio.com/docs/setup/network#_common-hostnames

**Comment by hhubik** [comment]
@joaomoreno - I am not aware of anything special about my DNS server.  The machine where I run VS Code is connected to the Internet through a router that is connected to my ISP.

I tried to ping the domains. Here is the result:
```
vscode-update.azurewebsites.net		Request timed out
vscode.blob.core.windows.net		Request timed out
marketplace.visualstudio.com		Request timed out
www.gallerycdn.vsassets.io		OK
rink.hockeyapp.net			Request timed out
```

**Comment by joaomoreno** [comment]
Can you resolve their names into IP addresses using `nslookup`?

**Comment by hhubik** [comment]
@joaomoreno  Yes, I can resolve the above four domain names that "timed out" into IP addresses using `nslookup`.

**Comment by joaomoreno** [comment]
Can you show me their IP addresses?

**Comment by hhubik** [comment]
@joaomoreno  here is the output of `nslookup` for each of the five domains above:
```
Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    waws-prod-bay-049.cloudapp.net
Address:  40.83.182.206
Aliases:  vscode-update.azurewebsites.net
          waws-prod-bay-049.vip.azurewebsites.windows.net

Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    blob.am5prdstr07a.store.core.windows.net
Address:  13.95.96.184
Aliases:  vscode.blob.core.windows.net

Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    marketplace.visualstudio.com
Address:  13.85.19.92

Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    www.gallerycdn.vsassets.io.netgear.com
Addresses:  198.105.244.74
          198.105.254.74

Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    stadiumvpc-265910089.us-east-1.elb.amazonaws.com
Addresses:  54.83.87.53
          52.204.92.23
          34.228.205.158
          52.7.206.234
Aliases:  rink.hockeyapp.net

```

**Comment by joaomoreno** [comment]
Very interesting. The problem seems to be in

```
Name:    www.gallerycdn.vsassets.io.netgear.com
Addresses:  198.105.244.74
          198.105.254.74
```

The domain is `www.gallerycdn.vsassets.io` and your DNS request seems to be for `www.gallerycdn.vsassets.io.netgear.com`. Can you try that again?

**Comment by hhubik** [comment]
@joaomoreno  That is interesting.  I missed the netgear.com part.   It is really there though.
```
$ nslookup www.gallerycdn.vsassets.io
Non-authoritative answer:
Server:  Gateway1
Address:  192.168.1.1

Name:    www.gallerycdn.vsassets.io.netgear.com
Addresses:  198.105.244.74
          198.105.254.74

```
The "server" Gateway1 is a Netgear  VPN Firewall.  Could that be somehow misconfigured?  This domain also ending with `.io` seems to be OK though:
```
$ nslookup angular.io
Non-authoritative answer:
Server:  FVS318Gv2
Address:  192.168.1.1

Name:    angular.io
Addresses:  151.101.1.195
          151.101.65.195

```

**Comment by joaomoreno** [comment]
It does explain why you can query but not download.

cc @modigrv have you seen this at all? The `www.gallerycdn.vsassets.io` domain is being redirected for a few of our customers.

**Comment by joaomoreno** [comment]
#34385
