### ISSUE TITLE
editor.fold command will fold the enclosing block but editor.foldRecursively will not

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#34706]
- VSCode Version: Code - Insiders 1.17.0-insider (b0c0634339c6f64a5c7f08b56fe732fb9154d3c4, 2017-09-15T05:24:23.107Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vsc-material-theme|Equ|1.0.2
Lua|key|0.0.9
cpptools|ms-|0.12.4

(2 theme extensions excluded)

---

When my cursor is on a line of code that is not the first line of a foldable block (i.e. it's somewhere in the middle of the block) some folding commands will work while other will not. Specifically, editor.fold will cause the enclosing block to fold, while editor.foldRecursively does nothing at all.

Steps to Reproduce:

1. Place your cursor on a line that is within a foldable block, but not on the first line of the foldable block
2. Trigger the editor.fold command
3. Notice the block folds
4. Re-expand the block and return your cursor to the same position within the block
5. trigger the editor.foldRecursively command
6. Notice nothing happens

Example of step 1
![fold bug 1](https://user-images.githubusercontent.com/484784/30654830-c1ee9976-9df4-11e7-8843-bec4463ff6cd.png)

Expected behavior of step 5
![fold bug 2](https://user-images.githubusercontent.com/484784/30654831-c1f6cda8-9df4-11e7-965c-64918c60d5d7.png)

**Comment by aeschli** [comment]
This got fixed for 1.18
