### ISSUE TITLE
Alt+click to follow link does nothing on Ubuntu

### ISSUE THREAD

**Issue by kleinfreund** [Microsoft/vscode#34710]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
prettier-vscode|esb|0.23.1
sublime-keybindings|ms-|2.9.1
color-highlight|nau|2.3.0
vscode-subword-navigation|ow|1.1.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Put a URL into a document (new, empty document suffices)
2. Hover over it and hit <kbd>Alt</kbd>+<kbd>Click</kbd> as suggested by the tooltip to follow the link

**Expected:** URL is launched in the default browser in a new tab

**Actual:** Nothing happens (as in absolutely no feedback/reaction happens)

Note: I can open URLs from an external terminal by clicking it.

Reproduces without extensions: **Yes**

*(Bot gets tripped up by the report template, eh? :p)*

**Comment by ajitid** [comment]
I have this same issue, did Alt-clicked worked before VS Code 1.16.1?

**Comment by kleinfreund** [comment]
@ajitid Unfortunately, I cannot comment on that as I started using VSCode on the current version.

**Comment by ajitid** [comment]
Try this `dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier '"<Super>"'`

**Comment by kleinfreund** [comment]
@ajitid I don’t know the purpose of that command. What is it doing?

**Comment by ajitid** [comment]
Found this on stackoverflow, Alt + Click is bound to drag window, so you map this Alt + click to Super + click with this command. https://askubuntu.com/questions/521423/how-can-i-disable-altclick-window-dragging

**Comment by kleinfreund** [comment]
This would be merely a workaround. The overall issue still persists.

Also, VSCode is still able to use the <kbd>Alt</kbd> modifier for this purpose, without affecting or triggering Ubuntus window dragging.

**Comment by ajitid** [comment]
I agree. Let's wait from someone from VS Code team to respond.

**Comment by Tyriar** [comment]
Alt+click moves windows on Linux as an OS level. To get multi-cursor with the mouse working, you can either:

- Disable alt+click at the OS level, or
- Add this setting: `"editor.multiCursorModifier": "ctrlCmd"`, note that this will move the go to definition/follow link action to alt+click.

**Comment by kleinfreund** [comment]
@Tyriar I see. This setting has an intentional side-effect of moving the shortcuts. 

This issue is not really resolved right now, because the tooltip shown by VS Code suggests an interaction that is not available with the given shortcut.

So the intentional side-effect of mentioned setting has another side-effect: It renders a subset of users unable to perform the interaction instead of avoiding the conflict.

**Comment by Tyriar** [comment]
@kleinfreund which tooltip are you referring to?

**Comment by kleinfreund** [comment]
@Tyriar see original question

**Comment by Tyriar** [comment]
@kleinfreund if you're talking about the tooltip saying press alt+click then we're probably not going to fix this. I don't even know where to begin detecting whether alt+click is bound to *anything* at the OS level, let alone detecting this across all the distributions in a reasonable way.

**Comment by kleinfreund** [comment]
I understand.

The only reasonable way of working arounds this I can think of right now would be using <kbd>Shift</kbd> as the fallback instead of <kbd>Alt</kbd>.

**Comment by Tyriar** [comment]
@kleinfreund this is the real fix for this issue https://github.com/Microsoft/vscode/issues/3130, allowing real customization of mouse bindings

**Comment by anchepiece** [comment]
@kleinfreund I've also contributed a fix for the tooltip text here https://github.com/Microsoft/vscode/pull/36764 

Just to confirm, does Ctrl + Alt + click work?
