### ISSUE TITLE
Poor resize performance for editor with many code lenses 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#34716]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z) and 1.17.0-insider f7962f0682a76516df51de4856f8ccc5d8ad578a
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Make sure code lenses are enabled:

```json
"editor.codeLens": true,
"typescript.referencesCodeLens.enabled": true,
```

2. Open a file that will have many code lenses, such as this `d.ts` file
[tsserverlibrary.txt](https://github.com/Microsoft/vscode/files/1319319/tsserverlibrary.txt)

3. Try resizing the editor

**Bug**

![sep-20-2017 14-36-16](https://user-images.githubusercontent.com/12821956/30668898-290292f4-9e11-11e7-8a55-6c8ed7e5be13.gif)

I don't see any additional calls being made to TS to compute the code lenses.

**Comment by alexandrudima** [comment]
Nice find!

**Comment by alexandrudima** [comment]
I've optimized as much as feasible in the case of painting these 3000+ code lenses (content widgets).

Most of the time now is taken by the find widget (#34744) and the workbench editor title area (#34745)
