### ISSUE TITLE
Python debugger args

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#34717]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Python

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
---

Steps to Reproduce:
1. Edit launch.json
2. Add "args": [ "one long string of args"]

I'm getting tired of converting command line args to a JSON array syntax with each arg separately quoted and backslashes converted to forward slashes and so on.  Can you make it so I can just paste in a command line somewhere and have it "just work" or auto-convert that to the correct JSON syntax ?

**Comment by isidorn** [comment]
This is currently designed behavior. launch.json is lanugage agnostic and has no notion of different attributes in the configuration file so it would be hard to automate this
Closing as designed
