### ISSUE TITLE
Allow to reveal a symlinked file from the editor in the explorer

### ISSUE THREAD

**Issue by scamden** [Microsoft/vscode#34713]
- VSCode Version: 1.16.0
- OS Version: Mac 10.12.6

Steps to Reproduce:

1. cd to the director of an npm package
2. run npm link
3. cd to a second package
4. run npm link <first package name>
5. import something from package 1 in ts within vscode
6. use go to definition to open the file from package 1
7. run workbench.files.action.showActiveFileInExplorer

expected: file opens inside package2's node_modules folder in the sidebar
actual: nothing happens

Reproduces without extensions: Yes

**Comment by Jeyanthinath** [comment]
@bpasero I would like to take this on,  would you give me some leads
