### ISSUE TITLE
Display unique directory label for quickopen files

### ISSUE THREAD

**Issue by beyang** [Microsoft/vscode#34718]
In multi-root workspaces, the quickopen shows the relative directory path, including the workspace folder basename, as the label for file results in order to disambiguate files from different workspace folders:

![selection_016](https://user-images.githubusercontent.com/1646931/30669152-0c5b8c0e-9e12-11e7-959b-53eac94724fa.png)

In cases such as the one shown above, 2 or more workspace folders may share the same basename ("mux" in this case). Such cases arise commonly when you've checked out a fork of another repository or you've checked out a different revision into a separate working tree.

In these cases, including the directory up to the workspace folder basename is no longer sufficient to disambiguate the results (as shown above). Using the absolute path would satisfy uniqueness, but the absolute path is often too long and hard to visually distinguish, especially if the first few path components are the same. Ideally, the directory label should include just enough parent components to disambiguate a file among all workspace folders. For instance:

![selection_017](https://user-images.githubusercontent.com/1646931/30669303-b009cbea-9e12-11e7-8431-a437a60a499a.png)

In cases where the workspace folder basename is unique, the old behavior should remain (displaying basename plus the relative path from the workspace folder root).

If there's agreement this would be useful, I can open a PR from https://github.com/beyang/vscode, which implements this change.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/29871

**Comment by beyang** [comment]
#29871 addresses my issue to satisfaction, thanks!
