### ISSUE TITLE
Light bulb for code actions displays only when text is selected

### ISSUE THREAD

**Issue by joshtynjala** [Microsoft/vscode#34724]
- VSCode Version: 1.16
- OS Version: macOS

Steps to Reproduce:

1. Place cursor within range where a "hint" diagnostic exists.

Light bulb should appear in left margin, but it no longer does. Instead, you need to select at least one character in the range. This worked correctly by simply placing the cursor in the range without selection in previous versions of VSCode.

This makes code actions more difficult to discover. Users need to guess where they might exist. Please return to previous behavior.

Reproduces without extensions: Yes/No

**Comment by joshtynjala** [comment]
This issue still exists in version 1.17.1. In fact, the behavior has gotten worse than described! In order to show a lightbulb for a hint diagnostic, a user is now required to select the entire range of the diagnostic in the editor.

Is there still work to be done?

**Comment by joshtynjala** [comment]
For reference, I'm working on a language extension that supports replacing a member variable on a class with getter/setter functions that have the same name. I don't want the user to be required to select the entire member variable definition to discover that they can generate a getter and setter. They should be able to click anywhere within the definition to place the cursor, similar to how a code actions work for an error or warning. For an error or warning, no selection is required. Simply clicking to place the cursor is enough.

**Comment by joshtynjala** [comment]
Anyone? It's been over a week since I followed up.

**Comment by alexandrudima** [comment]
ping @jrieken

**Comment by jrieken** [comment]
> Light bulb should appear in left margin, but it no longer does. Instead, you need to select at least one character in the range.

Not, true. Please provide more information

<img width="386" alt="screen shot 2017-10-23 at 17 12 43" src="https://user-images.githubusercontent.com/1794099/31897023-7b61fc88-b815-11e7-8a18-adac498628e4.png">

**Comment by joshtynjala** [comment]
@jrieken You seem to have missed that **DiagnosticSeverity.Hint** is required. From your screenshot, the red squiggly suggests to me that you tested with DiagnosticSeverity.Error instead. As I said in my followup, code actions for other severities (like errors and warnings) are working correctly, but DiagnosticSeverity.Hint suddenly changed to have a different behavior.

Here's an animated GIF that shows the issue:

![diagnostic-severity-hint](https://user-images.githubusercontent.com/141885/31897483-60cc7c76-b7cb-11e7-804c-d9e910351445.gif)

There is a diagnostic with DiagnosticSeverity.Hint from the beginning of the text on that line to the end. You can see that I place the cursor twice, but the light bulb does not appear until I select the entire range.

**Comment by jrieken** [comment]
> but the light bulb does not appear until I select the entire range.

It depends on the provider. The light bulb logic asks the provider *whenever* markers or selections change for code actions. If there are any, a light bulb is shown. The snippet below registers a provider that always returns code actions, no matter what, and the light bulb will always show. So, I don't think that this is a problem of how/if we invoke the provider, but a problem of the provider. That brings us to the usual question of what extension/language this is

<img width="155" alt="screen shot 2017-10-23 at 17 59 45" src="https://user-images.githubusercontent.com/1794099/31899563-2520c924-b81c-11e7-8721-475a2d66ee25.png">


```ts
vscode.languages.registerCodeActionsProvider('abc', {
    provideCodeActions() {
        return [{ title: 'Hello Lightbulb', command: 'someid' }];
    }
})
```

**Comment by joshtynjala** [comment]
This is the extension that I'm building for the ActionScript language:

https://github.com/BowlerHatLLC/vscode-nextgenas/

The language server is written in Java, and it uses the LSP4J library from Eclipse (version 0.3.0):

https://github.com/eclipse/lsp4j

The code actions are provided here:

https://github.com/BowlerHatLLC/vscode-nextgenas/blob/24cf23cf8b22c948d165a2bde1fd3900ab1a372f/language-server/src/main/java/com/nextgenactionscript/vscode/ActionScriptTextDocumentService.java#L755

As far as I can tell, I'm not treating DiagnosticSeverity.Hint and DiagnosticSeverity.Error any differently when providing code actions.

**Comment by jrieken** [comment]
> As far as I can tell, I'm not treating DiagnosticSeverity.Hint and DiagnosticSeverity.Error any differently when providing code actions.

There is no guarantee that you are being called with any diagnostics. In fact, most often the array of diagnostics will be empty

**Comment by joshtynjala** [comment]
If I'm understanding you correctly, the result from the code actions provider is not necessarily limited only to the diagnostics that are in the array. In other words, I can have it return additional code actions that have nothing to do with the diagnostics that are passed in. Is that correct?

**Comment by joshtynjala** [comment]
@jrieken Oops! I forgot to @ you in my last response.

**Comment by jrieken** [comment]
> Is that correct?

Yes, the api asks for code action that are applicable for the given *range*. If in that range diagnostics exists we also provide them but it must not be like that

**Comment by joshtynjala** [comment]
@jrieken Okay, thank you! I understand better now. I think I originally thought that a diagnostic was always required to create a code action, and I know now that I misunderstood.

By the way, I dug through the VSCode source code yesterday to try to figure out the reason that DiagnosticSeverity.Hint was behaving differently than other severities for me. It turns out that the severity didn't matter, and the difference was that these diagnostics didn't include a message. Once I gave them a message, my code actions provider could see them without selection. Of course, adding a message also caused them to be listed in the problems panel, which I don't want. However, I now understand that I don't even need to use a diagnostic for code actions, so I know how to fix that.

Thanks again!

**Comment by jrieken** [comment]
> Of course, adding a message also caused them to be listed in the problems panel, which I don't want.

Arguably a bug as severity hint should be only for code actions and not for users. I'll follow up on that
