### ISSUE TITLE
search or files exclude isn't working anymore

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#34723]
- VSCode Version: 1.17.0-insider
- OS Version: W10 15063.608

one of the exclude settings aren't working anymore. vscode is sitting here scanning my entire production image upload directory causing the remote mount to choke to hell lol. these settings WERE working for a long time. but maybe two weeks or so now its been bad.

settings i have been using. i called them the "fknn staaaap" settings punching sshfs in the face.

```
	"search.exclude": {
		"**/.git": true,
		"**/www/media": true,
		"**/www/media/*": true,
		"**/www/media-live": true,
		"**/www/media-live/*": true,
		"**/vendor": true
	},
	"files.exclude": {
		"**/.git": true,
		"**/www/media": true,
		"**/www/media/*": true,
		"**/www/media-live": true,
		"**/www/media-live/*": true
	},
	"files.watcherExclude": {
		"**/.git": true,
		"**/www/media": true,
		"**/www/media/*": true,
		"**/www/media-live": true,
		"**/www/media-live/*": true,
		"**/vendor": true,
		"**/": true
	},
```
screenshot of my filesystem log where code is scanning everything.

![image](https://user-images.githubusercontent.com/881944/30671263-8fca981e-9e2b-11e7-9716-8704b4eb71c2.png)

scrolls for evrrrrrrrr, tens of thousands of uploads in there rofl.

it will eventually lag vscode out so hard trying to do this over the remote mount that i cant save anything and even opening a new terminal will give up for some reason, which i would have expected to be unrelated.

i know its code because it starts flooding the log the moment i launch it and stops the moment i quit. additionally, eventually, code will start spamming me with ERROR banners at the top of the window for these files also in that log, because it has choked my mount, once it eventually times out trying to read them i guess.

**Comment by roblourens** [comment]
Can you start with `--disable-extensions` and see if it still reproes? If not this would probably be #34434.

**Comment by hassanbazzi** [comment]
--disable-extensions does fix it. Figuring out which extension is causing this now.

**Comment by hassanbazzi** [comment]
I think this is the plugin causing it: https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

I did get some inconsistent behavior though.

**Comment by bobmagicii** [comment]
for me it appears to be https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

**Comment by hassanbazzi** [comment]
Something is weird. When I enabled / disabled various combinations of plugins it happens. I think there's maybe some kind of race condition in the new codebase of Code itself.

**Comment by bobmagicii** [comment]
not sure. for me it doesn't start the moment i open the folder. sometimes it stays nice and calm for a while and then while im in the middle of working is when it goes nuts.

**Comment by hassanbazzi** [comment]
Yea same! Sometimes random "excluded" folders start showing up as well.

**Comment by roblourens** [comment]
Hm, I still suspect #34434, and the extensions you mention would also indicate that due to them activating on `workspaceContains` patterns. But 

> sometimes it stays nice and calm for a while and then while im in the middle of working is when it goes nuts

doesn't fit that theory - in that case it should only happen when you launch vscode.

Can you try the latest Insiders build and let me know if you see a bunch of `rg.exe` processes running when this happens? If not, try to figure out which process is using CPU.
