### ISSUE TITLE
When I use the Find(ctrl+f) function, I found my two editors roll together.

### ISSUE THREAD

**Issue by donnol** [Microsoft/vscode#34729]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.10.1
githistory|don|0.2.3
gitlens|eam|5.1.0
graphviz-preview|EFa|0.0.3
git-project-manager|fel|1.4.0
code-runner|for|0.7.1
beautify|Hoo|1.1.1
path-autocomplete|ion|1.6.1
Go|luk|0.6.65
vscode-fileheader|mik|0.0.2
prettify-json|moh|0.0.3
vscode-code-outline|pat|0.0.10
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.13.0
code-settings-sync|Sha|2.8.3
vscode-nginx|sha|0.3.1
dot|Ste|0.0.1
vim|vsc|0.10.1
gitblame|wad|2.2.0
vscode-todo-highlight|way|0.5.11

(2 theme extensions excluded)

---

Steps to Reproduce:

1. open two editors.
2. ctrl + f , find something, then roll, you will find the other editor roll too.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
what do you mean by "roll" ?

**Comment by donnol** [comment]
@ramya-rao-a Scroll page，thanks.

**Comment by ramya-rao-a** [comment]
Do you see this when the 2 editors are opened side by side in 2 different editor groups or the same editor group?

Is the file opened in the 2 editors, the same file or different file?

When you say scroll, do you mean you scrolled manually or the scroll that happens automatically to take the cursor to the first result of the find operation?

Are you able to see this issue when you run `code --disable-extensions` from the command line?
