### ISSUE TITLE
exception not displayed in console

### ISSUE THREAD

**Issue by geogeim** [Microsoft/vscode#34721]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.3.0

---
```
require('async_hooks').createHook({
  init: () => {
    process._rawDebug("you won't see mee");
    a.b = c; // crash
  }
}).enable();

Promise.resolve().then(()=>{
  console.log("me neither");
});
```
I'm writing code using async_hooks magic and it seems that process._rawDebug does not appear in the console anymore. Worst, if a crash happens in a hook then you won't have any indication that it happened. I spent 4 hours debugging this :(

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
`process._rawDebug` goes directly to stderr and skips the debug protocol. I don't recommend using that in general. But you can also check out the insiders build and set `"outputCapture": "std"`.

https://github.com/Microsoft/vscode/issues/19750

**Comment by geogeim** [comment]
It's not only that, the debugger does not catch the exceptions happening in hooks, the debugging session just exits without any indication that something has gone wrong.

**Comment by roblourens** [comment]
Do you have the button checked to break on all exceptions? Does it work differently with chrome devtools?

**Comment by geogeim** [comment]
Tried the sample code with chrome devtools and I get the same behavior. Node.js bug?

**Comment by roblourens** [comment]
Thanks for trying that. Sounds like it could be a node bug, you can open an issue on https://github.com/nodejs/node
