### ISSUE TITLE
code searchService always takes a whole CPU core

### ISSUE THREAD

**Issue by samsong8610** [Microsoft/vscode#34727]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.18
code-gnu-global|aus|0.2.2
file-templates|brp|1.2.0
FreeMarker|dco|0.0.9
python|don|0.7.0
CppSnippets|har|0.0.12
restructuredtext|lex|37.0.0
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
vetur|oct|0.9.7
java|red|0.10.0
html-preview-vscode|tht|0.1.1
vim|vsc|0.10.1
jinja|who|0.0.8

---

A background process `/usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=searchService` always takes a whole CPU core.

Steps to Reproduce:

1. open a node project created by vue-cli
2. one `Code` process takes a whole CPU core and creates six subprocesses running `find -L . -type f`
3. after closing the Code, these subprocesses take all my four CPU cores for about one minute before exit

Reproduces without extensions: No

**Comment by roblourens** [comment]
This is #34434
