### ISSUE TITLE
Terminal link hover is squished

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#34720]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Print a link in the integrated terminal
2. Hover over the link text

**Bug**
Even with the terminal spanning the entire width of the window, the link hover content is squished:

![screen shot 2017-09-20 at 3 16 33 pm](https://user-images.githubusercontent.com/12821956/30670327-b616921c-9e16-11e7-8110-ba987fa6ca7b.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Should be fixed now

**Comment by octref** [comment]
Don't know how to repro this, maybe @mjbvz should verify.

**Comment by dbaeumer** [comment]
Verified on Windows:

<img width="238" alt="capture" src="https://user-images.githubusercontent.com/1931590/31019815-46be86f0-a531-11e7-8721-1979624f78d0.png">
