### ISSUE TITLE
it reported this problem, i don't know why.

### ISSUE THREAD

**Issue by WickedDogg** [Microsoft/vscode#34728]
[176c_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1319744/176c_main.cpuprofile.txt)
[176c_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1319745/176c_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.17.0-insider (b0c0634339c6f64a5c7f08b56fe732fb9154d3c4, 2017-09-15T05:10:59.353Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)</code>
- Memory (System): <code>8.00GB (1.29GB free)</code>
- Memory (Process): <code>251.63MB working set (0.00MB peak, 207.00MB private, 134.36MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|73|
|main|app.isReady => window.loadUrl()|216|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|477|
|renderer|require(workbench.main.js)|526|
|renderer|-> of which require() node_modules|78|
|renderer|create extension host => extensions onReady()|958|
|renderer|restore viewlet|0|
|renderer|restore editor view state|818|
|renderer|overall workbench load|1226|
|main + renderer|start => extensions ready|2316|
|main + renderer|start => workbench ready|2569|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`176c_main.cpuprofile.txt`
-`176c_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
I couldn't find anything suspicious in this profile. If you have been alerted it might have been false alarm. If are interesting in our performance work, be assured it is an on-going theme and you can find all performance issues using the perf-label: https://github.com/Microsoft/vscode/issues?utf8=✓&q=%20is%3Aissue%20label%3Aperf%20

Thanks and Happy Coding
