### ISSUE TITLE
Recents not showing in task bar on windows 10

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#3473]
This is all I see when right clicking on the task bar icon.
![untitled](https://cloud.githubusercontent.com/assets/1727302/13333908/31b2e5d0-dc01-11e5-993a-ea99da05dd9d.png)

**Comment by bpasero** [comment]
@pflannery which version of Code is this?

**Comment by pflannery** [comment]
@bpasero 0.10.8

**Comment by bpasero** [comment]
Likely an issue with Electron...

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/241
