### ISSUE TITLE
without the Internet , I can't open the VSCODE. I don't know why.

### ISSUE THREAD

**Issue by Jun860** [Microsoft/vscode#34731]
without the Internet , I can't open the VSCODE. I don't know why.

**Comment by ramya-rao-a** [comment]
What happens when you try to open it?
Any errors?

**Comment by Jun860** [comment]
@ramya-rao-a i used win10 x64, there is no problem when i connect to network, but break the net network ，i open the VSCODE , but without any reaction. No progress producted.

**Comment by ramya-rao-a** [comment]
Does VS Code open and the window is blank? Or absolutely nothing happens when you double click on the icon? Have you tried running it from the command line?
