### ISSUE TITLE
Cancel debug configuration choose dialog ends with an error pop up

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode#34735]
- VSCode Version: 1.16.1
- OS Version: Win10 64Bit

Steps to Reproduce:

1. Open an empty folder, create a simple file abc.txt with content test.
2. Open abc.txt and F5
3.  Debug configuration dialog will pop up
4. Press ESC to cancel

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/17075863/30685156-82ffa03c-9ee6-11e7-9be9-2a55f21d4e85.png)

![image](https://user-images.githubusercontent.com/17075863/30685162-876a8344-9ee6-11e7-8e2d-f9b479f23285.png)

**Comment by isidorn** [comment]
This is fixed in the latest vscode insiders.
Let me know if you can reproduce with latest insiders and I will reopen
https://code.visualstudio.com/insiders
