### ISSUE TITLE
Tasks - Multiroot folder - no all detected tasks presented in quick pick

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#34732]
In this setup:

![image](https://user-images.githubusercontent.com/172399/30683265-03ed9706-9ead-11e7-9f02-987999a39370.png)

after running empty4 - task1, the auto detected task empty2 - task1 is no longer presented

![image](https://user-images.githubusercontent.com/172399/30683248-f0e36dca-9eac-11e7-90fd-82dca09d792e.png)

**Comment by roblourens** [comment]
I can't run any autodetected tasks now.

- Open a workspace with no tasks.json file, that has a package.json with some scripts
- Try to run the task
- Get `Cannot read property 'toString' of undefined`

**Comment by dbaeumer** [comment]
@roblourens any more steps ?

**Comment by dbaeumer** [comment]
I can't reproduce this:

<img width="486" alt="capture" src="https://user-images.githubusercontent.com/1931590/31008275-cd5f5960-a503-11e7-9bbf-ae62dcb6fa7f.png">

**Comment by dbaeumer** [comment]
Found steps that make it fail with the above message.
