### ISSUE TITLE
Installing Python extension: error end of central directory record signature not found

### ISSUE THREAD

**Issue by IB4N3Z** [Microsoft/vscode#34730]
I'm upated VS Code 1.16.1 clean install & try to install extension Python error apear "end of central directory record signature not found" https://marketplace.visualstudio.com/items?itemName=donjayamanne.python, & i'm not using proxy too

**Comment by joaomoreno** [comment]
Does it reproduce with any other extensions?

I believe you are behind a proxy, are you sure you're not?

**Comment by IB4N3Z** [comment]
ass long install another extension not problem at all, but only for python extension, & proxy that you mean is on control panel as internet option, at tav Connections inside LAN Setting ?! no i don't have a proxy connection
![2017-09-23_17h23_11](https://user-images.githubusercontent.com/31641364/30772417-5ca95b9a-a084-11e7-9488-d078cf2bc564.png)

**Comment by aphe** [comment]
confirm on the mac version to.

Python 0.7.0 extension (from the initial Welcome page)
![Python 0.7.0](https://i.imgur.com/P2YMcUy.png)
another extension
![another extension](https://i.imgur.com/cs0r7RH.png)

**Comment by maestrofx** [comment]
@joaomoreno , 
Mine too. Confirmed for my linux machine, got the same error `Error end of central directory record signature not found`
is it the problem for the only python extension or any other issue related to this? Because the other extension is success to install.

Thx

**Comment by joaomoreno** [comment]
Hey guys what do you get when running `nslookup www.gallerycdn.vsassets.io`?

**Comment by gifff** [comment]
I was having the same problem, but then I tried to use another internet connection.
Firstly, I was still unable to install it directly in the VS Code. But I tried to install the extension using cmd and somehow it worked.

Failed:
![screenshot 32](https://user-images.githubusercontent.com/4391866/30951566-ec129824-a44d-11e7-967f-fc98d6348acd.png)

Worked:
![screenshot 34](https://user-images.githubusercontent.com/4391866/30951569-ef230a6c-a44d-11e7-98d5-fb5cfb448d5c.png)

**Comment by joaomoreno** [comment]
@gifff Great finding!

@jrieken There appears to be a difference between XHR and node requests in terms of the contents of the request which comes back. `end of central directory record signature not found` means that the unzipping library could not unzip the file because it was corrupt.

**Comment by aphe** [comment]
Yes, it is a connection issue.

try first i got this error message
```bash
Found 'donjayamanne.python' in the marketplace.
Installing...
Error: end of central directory record signature not found
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:183:14
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:618:5
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
```

change the connection and successfully install

**Comment by joaomoreno** [comment]
@aphe What do you mean by "change the connection"? Like connect to another wifi? And does the change also fix the in-product installation?

**Comment by aphe** [comment]
i am using my vpn.
yes it works on terminal but not in-product installation.

<img width="960" alt="screen shot 2017-09-28 at 10 04 21 pm" src="https://user-images.githubusercontent.com/8718403/30974151-206a23bc-a499-11e7-8463-e90364253cf3.png">

**Comment by joaomoreno** [comment]
#34709 seems to be the same.

**Comment by aslamhadi** [comment]
how is this going? I'm experiencing the same, strangely only for python extension. I've installed Go, Scala, and Wakatime extension perfectly.

**Comment by ridanlukita** [comment]
Thanks man ! It worked @aslamhadi

**Comment by takin** [comment]
thanks @aslamhadi it works perfectly for me.

@aphe BTW, can you tell me how to make the terminal path look like this -> https://user-images.githubusercontent.com/8718403/30974151-206a23bc-a499-11e7-8463-e90364253cf3.png

**Comment by hantumobil** [comment]
It works for me @aslamhadi, Thanks!.

**Comment by luftywiranda13** [comment]
but we won't have the ability of auto updating if we install the extension from VSIX, right?

**Comment by jamil912** [comment]
Install with GUI Failed, With Command Line Failed too.

C:\Users\Akagami>code --install-extension donjayamanne.python
Found 'donjayamanne.python' in the marketplace.
Installing...
ApplicationInsights:Sender [ { Error: connect ECONNREFUSED 127.0.0.1:443
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443 } ]
Error: end of central directory record signature not found
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index
.js:183:14
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index
.js:618:5
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\fd-slicer\i
ndex.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)

**Comment by jamil912** [comment]
@aslamhadi Thank You very strongly much :smile: 

That's Work for me 
![vscode_python_issues](https://user-images.githubusercontent.com/19743722/31329675-6b389102-ad05-11e7-91c0-2d212bd9e382.png)

**Comment by joaomoreno** [comment]
If you suffer from this, read @aslamhadi's suggestion as a workaround.

**Comment by miccferr** [comment]
Any updates on this issue?  I'm experiencing the same as:

-  @aphe if trying to install via GUI
- @jamil912 if trying to install via command line

The suggested workaround is not working either, as the extension is no longer hosted on the provided URL..

I'm on a mac with OSX 10.11.5  and VsCode Version 1.16.1 (1.16.1)

Thanks in advance!

**Comment by aphe** [comment]
Hi @miccferr, you can download vsix file [here](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-extension-pack) at the Resources section on the right.
