### ISSUE TITLE
Tasks: Multi root - Configure Build Task does nothing

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#34733]
1) Starting with no tasks.json in this setup

![image](https://user-images.githubusercontent.com/172399/30683341-600b5f64-9ead-11e7-9a4b-977d57c9feb7.png)

2) Execute Tasks>Run Build Task, shows
![image](https://user-images.githubusercontent.com/172399/30683367-7d3c6c0e-9ead-11e7-95a9-ab52abf35d4c.png)

3) Selecting 'Configure Build Task' in the message box 
Shows the template picker
![image](https://user-images.githubusercontent.com/172399/30683419-b08e8c90-9ead-11e7-812d-7897d2e365c9.png)

I would have expected the same behaviour as when I execute Tasks>Configure Default Build Task, where I can pick from the set of detected tasks.
![image](https://user-images.githubusercontent.com/172399/30683500-f60f1cc6-9ead-11e7-93a1-e596d8b2ce42.png)

**Comment by dbaeumer** [comment]
I am currently `rewriting` the UI around it to make it more consistent when in folder or workspace mode

**Comment by dbaeumer** [comment]
Fixed.
