### ISSUE TITLE
Explorer should load root folders (workspace folders) sequentially

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34738]
Today the explorer is empty until *all* root folders are resolved. In case of a remote file system, that can be a long time. Instead it should show the roots as given and the loading indication individually for them. Also, failure of one should "break" the explorer

**Comment by forivall** [comment]
This also fixes an issue where workspace folders don't load properly in the UI.
![screen shot 2017-10-11 at 3 15 18 pm](https://user-images.githubusercontent.com/760204/31469599-135d1e56-ae97-11e7-9046-a89f281fdb33.png)

Cherry-picked into https://github.com/forivall/vscode/tree/missing-tree-many-roots

**Comment by isidorn** [comment]
Yes, I have also commented that here https://github.com/Microsoft/vscode/issues/35320
