### ISSUE TITLE
Emmet should use embeddedLanguage to determine if in css

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#34736]
**Problem**
For css within js/ts strings, emmet css expansions are currently not enabled:

```js
styled.button`
    color: red;
    m10|
`
```

The js document in this case is using the `html` emmet syntax profile. However the string contents are marked as `css` in VS Code  and it looks like emmet does not honor this language setting. Only html emmet expansions are enabled inside of the template string

**Proposal**
When using the `html` syntax profile, emmet should look at the language mode of the current context to determine if we are in a style sheet. Currently this is determined by looking for a `<style>` tag, which will not exist for cases like the above

**Comment by ramya-rao-a** [comment]
@mjbvz Does this also happen when you use the `Emmet: Expand Abbreviation` command directly?

**Comment by mjbvz** [comment]
Yes, it looks like that command does work properly. Tab expansion and the suggestion list do not however.

Here's the code I've been testing with: 

```js
import * as React from 'react'
import styled from 'styled-components'

const Button = styled.button`
    border-radius: 3px;
    m10
`;
```

![Uploading Screen Shot 2017-09-21 at 10.32.16 AM.png…]()


For testing purposes however, it will currently be easier to:

1. Set:

```json
    "emmet.includeLanguages": {
        "markdown": "html"
    },
    "emmet.excludeLanguages": []
```

2. In a markdown file:

~~~md
```css
.a {
    m10
}
```
~~~

3. Try triggering expansing inside the css block.

This is the same basic issue as the jsx case, but does not require that any extensions be installed

**Comment by ramya-rao-a** [comment]
The `Emmet: Expand Abbreviation` command comes from the core and so has access to the language under the cursor and so is able to use the right syntax.

The completion provider on the other hand is from the extension and extensions dont have the scope information for position under the cursor.

You have any ideas on how an extension can get the scope info?

**Comment by mjbvz** [comment]
Yes this gets back to the whole discussion around exposing scope to extensions.

One idea is to leverage the new `CompletionContext` object and add a property with the current language to that object. I believe we should already know the current language when we compute the completion context in the editor

**Comment by ramya-rao-a** [comment]
Closing this as "wont fix" for now.

Workaround is to use the `Emmet: Expand Abbreviation` directly or to set `emmet.triggerExpansionOnTab` to `true and use tab instead.

Getting the completion provider to understand the language under the cursor is way too much work at the moment.
We do have an issue that tracks use of emmet from the css extension. That should solve most cases.

**Comment by gilesbutler** [comment]
> Workaround is to use the Emmet: Expand Abbreviation directly or to set emmet.triggerExpansionOnTab to `true and use tab instead.

Hey @ramya-rao-a, that workaround doesn't work for styled-components here. In my user settings I have...
```
  "emmet.triggerExpansionOnTab": true,
  "emmet.showSuggestionsAsSnippets": false,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
```

and in a jsx file...
```
const CreatedDate = styled.p`
  p10
`;
```

`p10` should expand to `padding: 10px` but I don't get anything from using tab or `Emmet: Expand Abbreviation` from the command palette.

This has only stopped working since the recent update and is much needed feature. We're back to writing a tonne more css now without emmet support.

**Comment by ramya-rao-a** [comment]
@gilesbutler 

> This has only stopped working since the recent update

I don't believe css expansions in a jsx file inside the `styled` components ever worked. Are you sure that this worked before. If so, can you recall the last time you used it?

**Comment by gilesbutler** [comment]
Hey @ramya-rao-a, 

100% this was working up until about a week or so ago, sorry I can't pin point the exact date but pretty sure it was after the recent update. 

And didn't you tweet about this exact thing [https://twitter.com/ramyanexus/status/895756078306050048]https://twitter.com/ramyanexus/status/895756078306050048) 🤔

**Comment by ramya-rao-a** [comment]
When you map any language to css using the `emmet.includeLanguages` setting you will be able to expand css abbreviations in that file. That's what the tweet is talking about.

The feature I mentioned which I believe never worked was expanding css abbreviations inside `styled` components in a js file where the `javascript` was mapped to either `javascriptreact` or `html` in the `emmet.includeLanguages` setting

**Comment by gilesbutler** [comment]
Hey @ramya-rao-a thanks for clarifying.

Expanding css abbreviations inside `styled` components was definitely working for me up until recently so I don't know what changed.

I've actually found out since that emmet isn't working in normal css files either now. If I type `p` then `padding` will come up in the quick suggestions but typing `p10` then hitting `tab` doesn't trigger emmet to expand to `padding: 10px` like it used to. I think my settings are correct as well...
```
  "editor.snippetSuggestions": "top",
  "emmet.showExpandedAbbreviation": "always",
  "emmet.triggerExpansionOnTab": true,
  "emmet.showSuggestionsAsSnippets": true,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
```

**Comment by ramya-rao-a** [comment]
@gilesbutler Your settings are fine. `p10` and all other css abbreviations work just fine. Can you run `code --disable-extensions` and try again?

**Comment by gilesbutler** [comment]
@ramya-rao-a that worked with the extensions disabled thanks.

Anyway of tracking down which extension is the culprit?

**Comment by gilesbutler** [comment]
All good! Found it! I disabled [PostCSS Syntax](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS) and it's working again in CSS files now.

Thanks for your help @ramya-rao-a
