### ISSUE TITLE
Non standard Delimiter Used in title/Caption bar

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#34742]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

Can we please stick to the standard minus "-" to delimit the files in the caption bar? this "—" 8212? Is definitely not the standard delimiter and Clashes Both Visually and with tools that rely on "-" looking up windows by title to separate application name from opened files. Eg, Find Window By Name where Name.Split("-").Last().Trim() === "Visual Studio Code"

You really want tool makers to special case your product?

You are definitely playing with my OCD here

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Now only using this special character on macOS, but not Windows or Linux.

**Comment by mjbvz** [comment]
@bpasero I believe ee68167 caused all platforms to use the regular minus sign. I've checked in d772ad8ae2fab210c17d166641b52294180d2602 to change mac to use the emdash again

**Comment by bpasero** [comment]
@mjbvz thanks, good catch. Was hard to spot the difference :)
