### ISSUE TITLE
Broken code highliting in vue files

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Microsoft/vscode#34741]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.2.0
vue|liu|0.1.5
vuejs-extension-pack|mub|0.1.9
vetur|oct|0.9.8
vue|sea|0.4.0
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1. Code sample: http://joxi.ru/ZrJ4yvEi1eLKZ2?d=1
2. Highlighting is broken after ' symbol in comment

Reproduces without extensions: Yes
Without extensions where is no highlighting on .vue files.

**Comment by ramya-rao-a** [comment]
This issue was moved to vuejs/vetur#442
