### ISSUE TITLE
bug submit

### ISSUE THREAD

**Issue by hqApril** [Microsoft/vscode#34749]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
angular1-code-snippets|ale|0.0.3
vscode-database|baj|1.2.0
phpserver|bra|2.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
auto-rename-tag|for|0.0.14
code-runner|for|0.7.1
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
HTMLHint|mka|0.4.0
vscode-filesize|mkx|1.0.0
debugger-for-chrome|msj|3.3.0
vscode-icons|rob|7.13.0
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.if i use tab in a new line, cursor will move to end of  next line instead of next tab
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please run `code --disable-extensions` from the command line and see if you still see the issue. This is to eliminate the case that one of the extensions that you have is causing the problem.

If you still see the issue, please share more details like
- what type of files do you see the issue in? All types?
- Can you share a gif/video of the same?
- Have you bound tab as a keyboard shortcut for any command?
