### ISSUE TITLE
Feature Request : Syntax highlighting for the CYPHER query language

### ISSUE THREAD

**Issue by jasperblues** [Microsoft/vscode#34748]

**Comment by ramya-rao-a** [comment]
Have you tried the extension https://marketplace.visualstudio.com/items?itemName=jakeboone02.cypher-query-language?

**Comment by egamma** [comment]
This is a great candidate for an extension and should not be provided by the VS Code core.

**Comment by jasperblues** [comment]
> Have you tried the extension https://marketplace.visualstudio.com/items?itemName=jakeboone02.cypher-query-language?

Wow, cool 👍
