### ISSUE TITLE
Code does not work when using new session switch (-n)

### ISSUE THREAD

**Issue by antonydeepak** [Microsoft/vscode#3474]
Hello - I noticed couple of times that code does not open the current folder when I use `code -n .` . It creates a new code session(window) but does open the current folder. However, `code -r .` works.

Coincidentally, whenever this happens I also see the error stream spitting information in my console. Attaching my current log files for reference.
[operation_log.txt](https://github.com/Microsoft/vscode/files/147279/operation_log.txt)

**Comment by bpasero** [comment]
@antonydeepak which code version? and is this windows?

**Comment by Tyriar** [comment]
I've noticed this as well on Ubuntu. It could be related to https://github.com/Microsoft/vscode/issues/3127,  I haven't tested it since that went in.

**Comment by antonydeepak** [comment]
@bpasero Yes, this is on Windows.

**Comment by bpasero** [comment]
We had inconsistent behavior with the "-n" option depending wether Code was running or not. If code was running, "-n" would open a new instance with the folder and if not, would open empty. My fix tries to align both and now when Code is not running you can run it with "-n" and still pass a path to open.

To verify:
* you can start code -n and it opens empty when not running and opens a new window empty when running
* you can start code -n with a path and it opens the path in a new window both if running or not
* you can still use -r option to force reuse the last active window
