### ISSUE TITLE
Cannot debug with external console

### ISSUE THREAD

**Issue by Azarien** [Microsoft/vscode#34740]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
Lua|key|0.0.9
cpptools|ms-|0.12.4
shader|sle|0.2.4

---

Steps to Reproduce:

I'm trying to debug C++ (msvc) program with external console window but it always uses internal debug console. I set "externalConsole": true in launch.json but it still doesn't open external console and the output appears in debug console.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the C++ vscode extension here 
https://github.com/Microsoft/vscode-cpptools
