### ISSUE TITLE
Find widget's checkEditorWidth does synchronous layout on editor resize

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#34744]
fyi @rebornix 

Discovered while looking into #34716

* have a diff editor (side by side)
* resize via sash:
![kapture 2017-09-21 at 12 08 09](https://user-images.githubusercontent.com/5047891/30690770-8f64855c-9ec5-11e7-91d6-a323d2df7791.gif)

Observe a lot of time being spent in `checkEditorWidth`:

![image](https://user-images.githubusercontent.com/5047891/30690733-778fcdce-9ec5-11e7-8839-30613324bd0c.png)

**Comment by alexandrudima** [comment]
@rebornix There's a PR from @mjbvz that improves this -- #38651

**Comment by rebornix** [comment]
Mitigate issue by not checking width/dom-info when users never resize the find widget (the usual case, most ppl don't resize at all). Then the DOM related operations are gone

![image](https://user-images.githubusercontent.com/876920/33278560-c3c64dac-d350-11e7-85e8-033fdd058e12.png)

It looks good now for this particular problem. We can continue improving this by listening to `ResizeObserver` as Atom does but it requires `experimentalWebFeatures` in Electron rendering process and it only helps inside VSCode.
