### ISSUE TITLE
CachedData dir won't clean up

### ISSUE THREAD

**Issue by plievone** [Microsoft/vscode#34751]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 15.6.0
- Extensions: enabled or disabled, no difference

---

VSCode Insider's `CachedData` dir won't clean up on my MacOS (it takes 2 GB, some files are from February this year). It should be kept only for 1 week, according to [nodeCachedDataManager.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/nodeCachedDataManager.ts#L21-L23). 

Launching from command line with --verbose doesn't report anything. Is there a way to see the telemetry, or how to debug that file during the startup?

**Comment by jrieken** [comment]
I see the same. I will look into this. Thanks for reporting this.

**Comment by aeschli** [comment]
Verified on all 3 platforms
