### ISSUE TITLE
[folding] Folding should not try to do any revealing if using mouse

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3475]
![folding-jumping](https://cloud.githubusercontent.com/assets/5047891/13334626/3e14e2fe-dc0d-11e5-851d-86ec373dcf25.gif)

Perhaps when not using mouse, it could reveal the beginning of the fold region...

**Comment by aeschli** [comment]
fixed with commit e68a6bd3e

**Comment by alexandrudima** [comment]
Nice!
