### ISSUE TITLE
Expanding A nested tag with emmet does not work in a JavaScript File

### ISSUE THREAD

**Issue by tomy8910** [Microsoft/vscode#34750]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider)
- OS Version: macOS Sierra Version 10.12.6

If you try to nest a tag, it will not expand
```javascript
<div>
   div /* clicking tab here will not expand the tag */
</div>
```
If the tag is not nested, it will expand.
```javascript
<div>
</div>
<div>
</div>
```

However, it only occurs when I'm running vscode-insiders with extensions. The problem does not occur when I have disabled my extensions. How do I pinpoint which extension is causing the problem? 

| Extension | Author |
| ------------- | ------------- |
| 2gua | rainbow-brackets |
| DavidAnson | vscode-markdownlint |
| EQuimper | react-native-react-redux |
| Equinusocio | vsc-material-theme |
| HookyQR | beautify |
| HookyQR | minify |
| James-Yu | latex-workshop |
| Kasik96 | swift |
| PKief | material-icon-theme |
| PeterJausovec | vscode-docker |
| Shan | code-settings-sync |
| Tyriar | lorem-ipsum |
| WakaTime | vscode-wakatime |
| WallabyJs | quokka-vscode |
| Zignd | html-css-class-completion |
| abusaidm | html-snippets |
| alefragnani | project-manager |
| anseki | vscode-color |
| austin | code-gnu-global |
| bibhasdn | django-snippets |
| bierner | color-info |
| bigonesystems | django |
| christian-kohler | npm-intellisense |
| christian-kohler | path-intellisense |
| chrmarti | regex |
| coderfee | open-html-in-browser |
| codezombiech | gitignore |
| cssho | vscode-svgviewer |
| dbaeumer | vscode-eslint |
| deerawan | vscode-faker |
| donjayamanne | githistory |
| donjayamanne | jquerysnippets |
| donjayamanne | python |
| dzannotti | vscode-babel-coloring |
| eamodio | gitlens |
| ecmel | vscode-html-css |
| eg2 | tslint |
| eg2 | vscode-npm-script |
| esbenp | prettier-vscode |
| felixfbecker | php-debug |
| felixfbecker | php-intellisense |
| formulahendry | auto-close-tag |
| formulahendry | auto-complete-tag |
| formulahendry | auto-rename-tag |
| formulahendry | code-runner |
| formulahendry | terminal |
| freebroccolo | reasonml |
| hollowtree | vue-snippets |
| jasonnutter | search-node-modules |
| joelday | docthis |
| johnpapa | Angular2 |
| joshpeng | sublime-babel-vscode |
| jpoissonnier | vscode-styled-components |
| karyfoundation | comment |
| kevinkyang | auto-comment-blocks |
| lukehoban | Go |
| magicstack | MagicPython |
| mohsen1 | prettify-json |
| mrmlnc | vscode-attrs-sorter |
| mrmlnc | vscode-jade-snippets |
| mrmlnc | vscode-pugbeautify |
| mrmlnc | vscode-puglint |
| mrmlnc | vscode-scss |
| ms-mssql | mssql |
| ms-vscode | cpptools |
| ms-vscode | csharp |
| ms-vscode | sublime-keybindings |
| msjsdiag | debugger-for-chrome |
| naumovs | color-highlight |
| octref | vetur |
| pflannery | vscode-versionlens |
| pranaygp | vscode-css-peek |
| rebornix | Ruby |
| robinbentley | sass-indented |
| shakram02 | bash-beautify |
| sidthesloth | html5-boilerplate |
| sysoev | language-stylus |
| taichi | react-beautify |
| thebarkman | vscode-djaneiro |
| tht13 | python |
| vsmobile | vscode-react-native |
| waderyan | gitblame |
| wix | vscode-import-cost |
| xabikos | JavaScriptSnippets |
| xabikos | ReactSnippets |
| zhuangtongfa | Material-theme |
| ziyasal | vscode-open-in-github |

**Comment by mjbvz** [comment]
I suspect it's one of the auto-tag extensions you have installed. Try disabling those to see if that fixes this issue

**Comment by tomy8910** [comment]
I got too desperate so I disabled them one by one whole testing which extension causes the problem. It was the sublime Babel extension by Josh Peng that caused the problem.

**Comment by ramya-rao-a** [comment]
@tomy8910 Do you mean this one: https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode ?

**Comment by tomy8910** [comment]
Yes!

**Comment by ramya-rao-a** [comment]
@tomy8910 Add the below in your settings and Emmet should work as expected inside the nested tag when using the babel extension
```
"emmet.includeLanguages": {
      "jsx-sublime-babel-tags": "javascriptreact"
  }
```
