### ISSUE TITLE
Integrated terminal wrongly highlight filename

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/vscode#34753]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled

Steps to Reproduce:

1. Launch a Javascript project (mine is a react one) from integrated console
2. Add some unused variables in some files
3. Filenames in console eslint warnings are highlighted and can't be read
4. Switching themes would make no difference

Screenshot in VS Code: 

<img width="498" alt="capture d ecran 2017-09-21 a 16 03 08" src="https://user-images.githubusercontent.com/674667/30697335-4c5e2e6c-9ee7-11e7-816a-008383b40d50.png">

Screenshot in iTerm: 

<img width="500" alt="capture d ecran 2017-09-21 a 16 03 15" src="https://user-images.githubusercontent.com/674667/30697354-61884e76-9ee7-11e7-90ce-792717ad9002.png">

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This should be fixed on master now.
