### ISSUE TITLE
How can I set  autoreload False  when a file was changed externally？

### ISSUE THREAD

**Issue by inthink** [Microsoft/vscode#34758]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.2
bracket-pair-colorizer|Coe|0.10.9
xml|Dot|1.9.2
EditorConfig|Edi|0.10.1
code-runner|for|0.7.1
java-properties|ith|0.0.2
vscode-docker|Pet|0.0.18
java|red|0.10.0
vscode-icons|rob|7.13.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.8.3
velocity|sod|0.1.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.  When a  file changed ,I wish that notice me instead of  autoreload. Because  sometimes I need the old  files to compare.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
When you change the file manually or when the file is changed by an external process?
Can you explain your scenario?

**Comment by inthink** [comment]
@ramya-rao-a Both scenarios  you mentioned  can  reappear.

**Comment by ramya-rao-a** [comment]
Can you explain your particular scenario with steps?

**Comment by inthink** [comment]
@ramya-rao-a 
1. open a  file in two editors : vscode /  sublime text 3  at meantime ;
2. minisize vscode  and  modify the file in sublime ;
3. recover vscode  will see the file content  already autoreload   without notice or confirm.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14298
https://github.com/Microsoft/vscode/issues/20876
