### ISSUE TITLE
Test: Improved --wait behaviour

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34764]
Refs: https://github.com/Microsoft/vscode/issues/24327

- [x] Win - @auchenberg 
- [x] Mac - @sandy081 
- [x] Linux - @aeschli  

Complexity: 2

Running code with `--wait` parameter from the command line makes the command line process wait until the window that opens is closed. During this milestone we are now tracking the file to open as argument and also terminate the calling process when all the files are closed. This allows to reuse an existing Code instance for this purpose.

* verify you can use `--wait` with 0, 1 or many files and the calling process terminates when the files close
* verify the command line will terminate also when the target window closes or when the target window gets another folder opened

**Comment by auchenberg** [comment]
Looks good on Windows 10 RS2.
