### ISSUE TITLE
Link scrolling in editor split-view

### ISSUE THREAD

**Issue by brussee** [Microsoft/vscode#34762]
Feature request:

Allow scrollbars of editors in split-view to be linked such that, for example, if you scroll the left editor, the right editor scrolls with it at the same time. This makes comparing two files more easy.

**Comment by alexandrudima** [comment]
@brussee why not right click compare in the explorer to compare two files ?

**Comment by brussee** [comment]
@alexandrudima Thanks, I was not aware of this hidden gem! The scroll-link as described in my original post works perfectly already in compare mode.

This _almost_ covers my use case: the compare only allows editing of the rightmost file and I need to be able to edit both (or swap them).

**Comment by alexandrudima** [comment]
@brussee You can upvote in #4180. I would also like to be able to edit the left-hand-side of the diff. The widget supports it, but there appears there are some difficulties with the dirty file indicator.

**Comment by brussee** [comment]
Upvoted. Looking at the code I take it that `originalEditable` is an unused internal option and not a user setting.

**Alternative solution:**
How about taking the existing scroll-feature from the compare-mode and enabling that to be used in split-view? A simple "scroll-lock" checkbox that, when enabled, would scroll all viewports simultaneously.

**Comment by brussee** [comment]
@alexandrudima Thanks, upvoted. Looking at the code I take it that `originalEditable` is an unused internal option and not a user setting.

**Alternative solution:**
How about taking the existing scroll-feature from the compare-mode and enabling that to be used in split-view? A simple "scroll-lock" checkbox that, when enabled, would scroll all viewports simultaneously.

**Comment by alexandrudima** [comment]
@brussee that is a lot more difficult than painting a dirty indicator :)

Difficulties:
* scroll lock works well in the diff editor because the diff editor adds those hashed regions to fill in "deleted" or "inserted" lines.
* scroll lock would not work well at all if the files have even a few inserted/deleted lines.
* it looks to me you really want the diff editor for your use case of "comparing" two files.

**Comment by brussee** [comment]
@alexandrudima Agreed. Thanks for the quick responses!
