### ISSUE TITLE
Ubuntu 16.04 no icon in the active programs bar

### ISSUE THREAD

**Issue by GGAlanSmithee** [Microsoft/vscode#34767]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-npm|fkn|3.3.0
vscode-codemetrics|kis|1.9.3
autoconf|mae|0.0.1
cpptools|ms-|0.12.4
debugger-for-chrome|msj|3.3.0
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Open vscode multiple times
2. sometimes the task bar icon appears and then quickly dissapears

Reproduces without extensions: Not sure, happens seemingly at random

Also, the icon does not appear in the "program toggle bar" (alt + tab) making it impossible to re-open a minimized project.

![vscode no icon](https://user-images.githubusercontent.com/11805103/30705867-f68e1294-9ef6-11e7-91df-d3cfe3250d47.png)

In the image you can see that vscode is open but there is no icon in the left-hand bar. Alt+tab shows no icon either. 

This have happened multiple times both at home and at work, and only with vscode, no other application.

Sorry if there are other issues covering this. I tried to search, but there are so many issues, so might have missed it.

**Comment by Tyriar** [comment]
This is probably an issue with Ubuntu as all we do is provide a .desktop file for the OS to use.

**Comment by GGAlanSmithee** [comment]
@Tyriar That might be, but I've used Ubuntu for many years and only had this problem with this app, both at home and at work... Kind of an unlikely coincidence..

**Comment by Tyriar** [comment]
Seems more unlikely to have anything to do with VS Code though as VS Code is open, it's just not being reflected from within Unity's dash. We do not communicate with Unity at all, we just have a desktop entry which registers the application with some metadata.

**Comment by GGAlanSmithee** [comment]
@Tyriar I understand what you are saying, and it makes sense. I just thought it to be a somewhat unlikely coincidence that it happens repeatedly on several computers with just one application, and no other. But you are the one with the technical insight in this conversation, so let's leave it at this. Thanks for your reply and explanation! :+1:
