### ISSUE TITLE
underscore is indistinguishable in links 

### ISSUE THREAD

**Issue by joejebara** [Microsoft/vscode#3476]
when a link, src or url... contains an underscore character ( _ ) , you can't distinguish it from a misplaced space character because of the default underline below the links.

**Comment by bgashler1** [comment]
Appears to be impractical to solve using `text-decoration: underline` in Chromium until it fully adopts the full CSS 3 spec on `text-underline-position`.

What I'll do is use a `border-bottom: 1px solid` instead.  Tested locally, and it looks good to me:
![untitled-2](https://cloud.githubusercontent.com/assets/11839736/14162578/f02c591e-f6a1-11e5-928d-78f1cf266a15.png)

**Comment by alexandrudima** [comment]
Fixed via #38948
