### ISSUE TITLE
ExplorerView#getActiveFile only uses file-uris

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34768]
Trying to understand why remote files aren't reveal in the explorer brings me to this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L363. Unclear why and why we don't try to lookup a uri in the explorer model?

**Comment by bpasero** [comment]
Yes I think this check is bogus now that other resources are shown in the explorer. The intent is to show and reveal the active file of the editor in the explorer. I think the explorer view model would be fit enough to deal with any schemes now.

**Comment by jrieken** [comment]
@isidorn Can we tackle this for September? I would make the demo nicer

**Comment by isidorn** [comment]
@jrieken yes, I can look into this today

**Comment by isidorn** [comment]
@bpasero looking at the code @jrieken pointed out it is enough to just remove `filter: 'file'`.
The only way to match the resource agains the `explorerModel` is to compare `uri`, thus I would first need to get a uri which defeats the purpose, since that is all we want.

**Comment by bpasero** [comment]
@isidorn I do not understand the problem, sorry.

**Comment by isidorn** [comment]
@bpasero sorry for not being clear. There is no problem, I just propse a fix which I just pushed 6dc90eace42ae18437850354970af6fa4c4f5db5

Apart from this I question the use of a [`filter`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L841) Shuold we try to remove this?

**Comment by bpasero** [comment]
@isidorn ah sorry, I read your last comment wrong. yes I think we need to revisit every use of this filter thing and make sure to get rid of it if possible.

**Comment by isidorn** [comment]
Ok I can look into the filter. My commit should fix this issue though -> closing

**Comment by jrieken** [comment]
Thanks Isi
