### ISSUE TITLE
Test: macOS touchbar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34760]
Refs: https://github.com/Microsoft/vscode/issues/14653

- [x] macOS  - @alexandrudima 
- [x] macOS  - @auchenberg 

Complexity: 3

We enabled support to show commands (with either icon or label) in the macOS touch bar. The commands are context aware and registered per window (switching windows will update the touch bar).

**Built-in**
* verify out of the box you get touch bar entries that you can use
* verify the debug touch bar behaves properly depending on your debug state (running, not running, stopped) and all commands work

**Extensions**
Extensions can add new commands via the menu API by registering to the `touchBar` location:

```json
"contributes": {
	"menus": {
		"touchBar": [
			{
				"command": "markdown.showPreview",
				"when": "editorLangId == markdown",
				"group": "navigation"
			}
		]
	}
}
```

Verify you can register commands to the touch bar and then `when` condition is respected. The touch bar will always take the context of the active editor to resolve the commands. The resource of the active editor will be passed to the command you register as context. 

**Note:** your command can either have a label or icon. If you chose an icon, make sure to use PNG, as SVG is currently not supported.

**Comment by alexandrudima** [comment]
This is super cool! Is there a way for our main-side code to easily participate in there?

Ideas:
* when focus is in the find widget, the touchbar should have prev/next icons for prev/next matches
* when focus is in a diff editor, the touchbar should have prev/next icons for prev/next change

**Comment by bpasero** [comment]
@alexandrudima yeah we do not show the label when an icon is present, in your case I suspect an issue with how Electron decides to update the touch bar entries when a change occurs on that level (e.g. I added a label and then added an icon and briefly I saw both showing up but after a full restart only the icon was showing up).

It is very simple to contribute more entries based on a specific context, e.g. see the code for the [debug buttons here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L204). Basically all you need is a command and a context. 

Space is indeed a bit limited down there and I am trying to optimize for a good experience when the debug toolbar is fully visible. It seems that when there are too many items in the touch bar, the last items will simply be removed from the bar. Maybe file new issues for your suggestions so that we can keep them in mind.

**Comment by alexandrudima** [comment]
Created #35137 and #35138

**Comment by varunkumar** [comment]
It would be great to get a first class API to play with TouchBar. Perhaps, a subset of whatever Electron offers. I feel its very restrictive to have access to TouchBar via `contribution points` only. I wrote an extension which uses `completionProvider` and want my suggestions to show up on TouchBar. Having an API would be helpful.

**Comment by auchenberg** [comment]
Touchbar works overall.

Created https://github.com/Microsoft/vscode/issues/35242 and https://github.com/Microsoft/vscode/issues/35244
