### ISSUE TITLE
Multiple Git repo status not updating after closing file opened from directory with different Git repo than project

### ISSUE THREAD

**Issue by andrewatwood** [Microsoft/vscode#34766]
- VSCode Version: 1.16.1
- OS Version: OSX 10.13

Steps to Reproduce:

1. Open a folder with an initialized Git repo
2. Open an individual file in the same window from a different folder and different repo.
3. Under the source control tab you will see both repos being tracked and accessible.
4. Close the file from a different repo.
5. Both repos will remain until the window is reloaded.

<img width="823" alt="single-file single-repo" src="https://user-images.githubusercontent.com/8690529/30705800-1a9a7d5c-9ebc-11e7-81da-8bdd6e20e663.png">
<img width="952" alt="double-file double-repo" src="https://user-images.githubusercontent.com/8690529/30705808-215097d0-9ebc-11e7-920c-d967c3ef23da.png">
<img width="874" alt="single-file double-repo" src="https://user-images.githubusercontent.com/8690529/30705810-23626f80-9ebc-11e7-8390-8d12e961b0bc.png">

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This is as designed. We're careful when removing repositories from the SCM viewlet as you might have closed the file but not yet be ready to close the repository.
