### ISSUE TITLE
Add square layout

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#34772]
Extracted from #34530

From @Ashikpaul 

---

It would be great if there is an option to view four panels like the below image.  

![screenshot 2](https://user-images.githubusercontent.com/17526871/30517950-dc49c670-9b8c-11e7-899a-af0f7673d42b.png)

**Comment by wizarrc** [comment]
@Ashikpaul would these be all separate files, you can do that now column wise only I believe. I would be more interested if you could have freeze panels of the same file, similar to how MS Excel works, except be able to snap them to another monitor if need be
