### ISSUE TITLE
Optional chaining suport in Javascript

### ISSUE THREAD

**Issue by zalishchuk** [Microsoft/vscode#34776]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
sharecode|Rol|0.4.1
vscode-caniuse|aka|0.5.3
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
prettier-vscode|esb|0.23.1
auto-rename-tag|for|0.0.14
docthis|joe|0.4.8
vscode-styled-components|jpo|0.0.8
vscode-puglint|mrm|2.3.0
atom-keybindings|ms-|3.0.2
color-highlight|nau|2.3.0
vetur|oct|0.9.7
vscode-icons|rob|7.13.0
vscode-nginx|sha|0.3.1
language-stylus|sys|1.7.3
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.4.1

(3 theme extensions excluded)

---

Steps to Reproduce:

Support [optional chaining](https://github.com/tc39/proposal-optional-chaining) syntax in `javascript`/`javascriptreact` languages.

Seems like VS Code parses `?` as a ternary operator and expects `:` symbol further.

Screenshots:
[Broken syntax](https://user-images.githubusercontent.com/2690794/30707451-31af05c4-9f04-11e7-9b4f-12e6ff3ad2f8.png)
[Works as it should](https://i.imgur.com/9DgHStJ.png)

Code: 
```js
const a = {
  b: {
    c: {
      d: {
        e: 1,
        g: [1, 2, 3],
      },
    },
    f: null,
  },
};

const brokenSyntaxHighlighting = () => {
  const array = a?.b?.c?.d?.g;

  /**
   * No TypeEror, but syntax highlighting is broken
   */
  const test = a?.b?.f?.f;

  for (let i = 0; i < array.length; i++) {
    console.log(array[i]);
  }
};

brokenSyntaxHighlighting();
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
JavaScript  and TypeScript language support for this syntax is tracked by: https://github.com/Microsoft/TypeScript/issues/16

I've also opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/522 to track just the syntax highlighting part of the feature request

Closing as upstream
