### ISSUE TITLE
No errors but highlighting Error

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#34777]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|2.2.1
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
auto-rename-tag|for|0.0.14
icon-fonts|idl|1.8.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.3.0

(3 theme extensions excluded)

---

Vscode showing an error warning in my code. but it works absolutely fine but  can't get rid of this
![spectacle ve5411](https://user-images.githubusercontent.com/10536234/30708170-7664bd0a-9f1b-11e7-8f86-d3e2945a3fde.png)

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Do you see the error with all extensions disabled? Try running `code -- disable-extensions` from the terminal

**Comment by prasanthnv** [comment]
No, it does not show any errors while all extensions are disabled. but the intelisense is gone  :(

**Comment by ramya-rao-a** [comment]
The error reporting is coming from one of the extensions that you have installed. 
Please log the issue in the repo for the corresponding extension
