### ISSUE TITLE
Intellisense with non static imports/require

### ISSUE THREAD

**Issue by thetutlage** [Microsoft/vscode#34778]
**Disclaimer**

1. I am not sure if this is the right repo to place this issue, so please guide me if not.
2. I searched stackoverflow and existing issues and found nothing for it.

I was trying to find a way to make `dynamic imports` or `non-static imports` to provide intellisense. For example

I have a file called `user.js` with following contents

```js
module.exports = function () {
  return {
    username: 'virk'
  }
}
```

And another file called `index.js` with following contents

```js
var userModule = './user'

const user = require(userModule)()
console.log(user)
```

When typing `user.` I get no intellisense, since the engine behind autocomplete may not have access to the `userModule` value and hence it fails.

## Hey that's not the right way?
Maybe you are right, but going there can be so many use cases where the require statements receives a dynamic value, which is part currently running application.

Also going forward, ES6 will have a [Loader](https://whatwg.github.io/loader/) API, where you can register modules or even can define a custom loader for a given application and I do think that intellisense will fail in that case too.

## No offense
The above points may have nothing to do with intellisense at all, since the design behind the entire system works on static analysis.

But the reason I created the issue, since I know that a `TSServer` runs inside a separate process to provide Typescript intellisense, which means there can be other ways too to use a loader which is part of a certain application.

Thanks 😄

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18656

**Comment by mjbvz** [comment]
Thanks for the report! I've moved this issue over to TypeScript, which powers both the JavaScript and TypeScript language support in VSCode
