### ISSUE TITLE
Test: transition into multi-root workspace without window reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34774]
Refs: https://github.com/Microsoft/vscode/issues/32945

- [x] Win @gregvanl
- [x] Mac @weinand 
- [x] Linux @isidorn 

Complexity: 4

We no longer require a window reload when entering a workspace. 

**Verify** for the following actions:
* Empty window: Add folders...
* Empty window: Save workspace as...
* 1-folder window: Add folders...
* 1-folder window: Save workspace as...
* Workspace window: Save workspace as...

**That**:
* our UI updates accordingly (e.g. explorer, window title)
* our migration of UI state (local storage) and hot-exit backups works properly
  * no data-loss: your dirty files are kept and restored when you now do a restart and new dirty files that you create after the transition are also restored properly
  * your UI state is kept and restored when you now restart the instance
* any window-workspace settings are migrated over to the workspace file (only when transitioning from a 1-folder window)
* extensions work properly still (we do restart the extension host!)

**Comment by isidorn** [comment]
Works well :+1:
