### ISSUE TITLE
Accessibility: With NVDA, the second to last line of this text breaks.

### ISSUE THREAD

**Issue by derekriemer** [Microsoft/vscode#34779]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.12.4
incremental-search|sie|0.2.1
code-spell-checker|str|1.4.0

---

Steps to Reproduce:

0. turn on NVDA. 
1. Paste this into code, in a empty document. This code was taken from an NVDA pull request I'm working on.
    ```
    #IAccProcServer.py:
    #A part of NonVisual Desktop Access (NVDA)
    #Copyright (C) 2017 NV Access Limited, Derek Riemer
    #This file is covered by the GNU General Public License.
    #See the file COPYING for more details.
    
    """Implementation of IAccProcServer, so that customization of a wx control can be done very fast."""
    
    from logHandler import log
    from  comtypes.automation import VT_EMPTY
    from  comtypes import GUID, COMObject
    from comInterfaces.Accessibility import IAccPropServer
    
    #These are the GUIDS for IAccessible properties we can override.
    #Use these to look up the GUID needed when implementing a server.
    #These are taken from oleacc.h (oleacc.idl has them too).
    #Number of digits Format: "{8-4-4-4-12}"
    PROPID_ACC_NAME = GUID("{608d3df8-8128-4aa7-a428-f55e49267291}")
    PROPID_ACC_VALUE             = GUID("{123fe443-211a-4615-9527-c45a7e93717a}")
    PROPID_ACC_DESCRIPTION = GUID("{4d48dfe4-bd3f-491f-a648-492d6f20c588}")
    PROPID_ACC_ROLE = GUID("{CB905FF2-7BD1-4C05-B3C8-E6C241364D70}")
    ```
2. go to the     `PROPID_ACC_DESCRIPTION = GUID("{4d48dfe4-bd3f-491f-a648-492d6f20c588}")` line.
3. Now, go to the end of the line, and press backspace.

Expected: The last character is announced as it is deleted. 
Actual: Nothing speaks, but the character is deleted.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@derekriemer Thank you! Nice catch!

**Comment by derekriemer** [comment]
wo, that was fast!
