### ISSUE TITLE
Version in vscode.d.ts docstring is confusing

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#3477]
The version in the doc string header of [vscode.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L7) is confusing as even on the 0.10.8 release it still claims to be version 0.10.1. 

It makes it difficult to tell what version of the api you are based off as for some reason the yo code generator did not setup my vscode.d.ts correctly leading to some of the [newer options](https://code.visualstudio.com/docs/extensionAPI/vscode-api#431) not existing in the file. 

I had to manually run npm install to get the correct version (which worked) but the version number at the top was still confusing. 

I realise this is probably two issues, and can split it if you wish.

**Comment by joaomoreno** [comment]
Assigning to February for discussion today.
