### ISSUE TITLE
[RFE] Shortcut for selecting all lines with multi-cursor

### ISSUE THREAD

**Issue by VojtechVitek** [microsoft/vscode#34782]
Would be nice to have a shortcut to select all file lines at once using [Multiple Selections](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor) feature.

It'd be very convenient especially on files with 1k+ lines.

**Comment by VojtechVitek** [comment]
Seems like this can be achieved via https://github.com/Microsoft/vscode/pull/5715 (regexp search + ALT+Enter). Can we please add this to documentation?

**Comment by hediet** [comment]
Workaround:
* Position the cursor at the beginning of the document
* Scroll to the end
* Hold Alt+Shift and click on the first column at the end of the document

This positions a cursor on each line in-between.

---

This can be easily implemented by an extension. If there is enough demand we can still make it a core command.
