### ISSUE TITLE
Mac OS - cannot download VSCode

### ISSUE THREAD

**Issue by rafal-olszewski** [Microsoft/vscode#34788]
- VSCode Version: current latest
- OS Version: Darwin rafmb.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Steps to Reproduce:

1. go to vscode download page
2. click download
3. nothing happens

**Comment by Henderake** [comment]
Same for me

**Comment by adetoks91** [comment]
I am also getting the same issue

**Comment by HaydenRead** [comment]
Same here on Windows 10, and Windows 7

**Comment by FernandoGomez** [comment]
Just tried again and it worked.

**Comment by ramya-rao-a** [comment]
The downloads are now working. Sorry for the trouble everyone.
