### ISSUE TITLE
Firing TreeDataProvider.onDidChangeTreeData(item) doesn't fully update the item

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#34789]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.16294
---

It seems that firing the `TreeDataProvider.onDidChangeTreeData(item)` event only causes the item's children to get refreshed (`item.getChildren` is called) and not the item itself (`item.getTreeItem` is not called).

This causes an issue if an extension is trying to update the label or icon of the item itself. For example, in GitLens I try to update an item which has a count in its label, but the only way to get that updated is to trigger an update of the item's parent (which causes a LOT more items to get updated and recalc'd).

//cc @sandy081 

Reproduces without extensions: No

**Comment by sandy081** [comment]
@eamodio True. I see the need. Updating the complete item makes sense to me.

**Comment by whiskeyjay** [comment]
Having the same issue here with the App Service extension - in order to update a single app setting node, I have to call refresh on the parent node which causes unnecessary trip to Azure.

**Comment by eamodio** [comment]
@weinand Any chance you'd consider this an important one too? 🤞 This one causes quite a bit of pain and needless refreshes.

**Comment by sandy081** [comment]
@eamodio I will look into this as part of the issue grooming effort.

**Comment by weinand** [comment]
@eamodio yes, I'm suffering from this too but I did not add the label "important" because it does not affect the end-user experience. It is just a performance problem.

**Comment by eamodio** [comment]
Thank you both!

**Comment by eamodio** [comment]
@sandy081 I'm doing a happy dance! Thank you! 😄

**Comment by sandy081** [comment]
Before: Refreshing a node is not updating the label

![before](https://user-images.githubusercontent.com/10746682/33528873-b640648e-d868-11e7-8cb4-1a554fd84f45.gif)

After: Refreshing a node updates its label

![after](https://user-images.githubusercontent.com/10746682/33528895-f74d0e96-d868-11e7-96ec-cb263e6e57b9.gif)
