### ISSUE TITLE
Opening a folder from the CLI or native explorer should add it to my current workspace

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#34784]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Have an existing window open with a few folders added in your workspace
2. `cd` to some other directory
3. run `code-insiders .` 

By default, a new window will be opened. Using `code-insiders . -r` will cause the existing window to be reloaded completely - replacing the existing workspace. Personally, I would much prefer the folder to be added to my current workspace, so that it doesn't disrupt my workflow. Do you have plans to at least add this as a configuration option?

**Comment by felixfbecker** [comment]
Agreed! I used to navigate and add folders from the terminal into native tabs, now with the new multi-folder workspace I always have to go through the file picker, which is very cumbersome and not very keyboard oriented. This would be awesome

**Comment by bpasero** [comment]
You can use the `--add` argument to add a folder to the last active instance.

**Comment by ggilmore** [comment]
@bpasero Could you please re-open this issue? I would at least the option to configure VSCode to behave like this by default, and not have to pass the `--add` flag every time I want to add another folder.
