### ISSUE TITLE
cannot install latest version on fedora

### ISSUE THREAD

**Issue by lukatendai** [Microsoft/vscode#34785]
Last metadata expiration check: 0:07:23 ago on Thu 21 Sep 2017 05:32:19 PM EDT.
Dependencies resolved.
====================================================================================
 Package       Arch            Version                          Repository     Size
====================================================================================
Upgrading:
 code          x86_64          1.16.1-1505406659.el7            code           39 M

Transaction Summary
====================================================================================
Upgrade  1 Package

Total download size: 39 M
Is this ok [y/N]: y
Downloading Packages:
code-1.16.1-1505406659.el7.x86_64.rpm                                                                                                         3.9 MB/s |  39 MB     00:10    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                         3.9 MB/s |  39 MB     00:10     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                      1/1 
  Upgrading        : code-1.16.1-1505406659.el7.x86_64                                                                                                                    1/2 
Error unpacking rpm package code-1.16.1-1505406659.el7.x86_64
Error unpacking rpm package code-1.16.1-1505406659.el7.x86_64
error: unpacking of archive failed on file /usr/share/code/icudtl.dat;59c431ab: cpio: read
code-1.16.1-1505406659.el7.x86_64 was supposed to be installed but is not!
  Verifying        : code-1.16.1-1505406659.el7.x86_64                                                                                                                    1/2 
code-1.16.0-1504715044.el7.x86_64 was supposed to be removed but is not!
  Verifying        : code-1.16.0-1504715044.el7.x86_64                                                                                                                    2/2 

Failed:
  code.x86_64 1.16.1-1505406659.el7                                                                                                                                           

Error: Transaction failed

the size of the package is 20MB less than 1.16.0

**Comment by dverstap** [comment]
I have the exact same error when upgrading on CentOS 7.

In addition, when first removing the package and then installing from scratch, I get a similar error:

```
[root@HOSTNAME_REMOVED ~]# uname -a
Linux HOSTNAME_REMOVED 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@HOSTNAME_REMOVED ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@HOSTNAME_REMOVED ~]# yum -y install code
Loaded plugins: fastestmirror, langpacks, priorities, versionlock
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package code.x86_64 0:1.16.1-1505406659.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package Arch      Version                     Repository                  Size
================================================================================
Installing:
 code    x86_64    1.16.1-1505406659.el7       microsoft-vscode-x86_64     39 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 39 M
Installed size: 186 M
Downloading packages:
code-1.16.1-1505406659.el7.x86_64.rpm                      |  39 MB   00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : code-1.16.1-1505406659.el7.x86_64                            1/1 
Error unpacking rpm package code-1.16.1-1505406659.el7.x86_64
error: unpacking of archive failed on file /usr/share/code/icudtl.dat;59c558f3: cpio: read
  Verifying  : code-1.16.1-1505406659.el7.x86_64                            1/1 

Failed:
  code.x86_64 0:1.16.1-1505406659.el7                                           

Complete!
```

Same thing on a freshly installed host.

**Comment by Tyriar** [comment]
The package is now published, we had some issues with signing and staff being out.
