### ISSUE TITLE
"Updating C/C++ dependencies" fail

### ISSUE THREAD

**Issue by rabbitq0082** [Microsoft/vscode#34797]
When start VSCode, ouput show error as below:
-----------------------
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
failed (error code '407')
-----------------------

I have configured "http.proxy", and VSCode is able to search/install plugins, it should not be the internet connection problem.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
Bookmarks|ale|0.16.0
project-manager|ale|0.20.0
code-gnu-global|aus|0.2.2
plsql|cas|0.0.3
vscode-markdownlint|Dav|0.10.0
algorithm-mnemonics-vscode|dav|1.0.2
python|don|0.7.0
xml|Dot|1.9.2
vscode-pandoc|Dou|0.0.8
LogFileHighlighter|emi|1.1.1
terminal|for|0.0.10
copy-markdown-as-html|jer|1.0.0
VBScript|lug|0.0.2
MagicPython|mag|1.0.12
markdown-converter|man|0.0.9
vscode-fileheader|mik|0.0.2
vscode-todo-parser|min|1.9.1
cpp-symbols|mir|0.0.1
cpptools|ms-|0.12.3
vscode-code-outline|pat|0.0.8
java|red|0.9.0
vscode-icons|rob|7.12.0
vscode-format|rya|0.0.6
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.2.7
vba|spe|1.0.17
python|tht|0.2.3
highlight-matching-tag|vin|0.4.4
local-history|xyz|1.3.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.8.3

(6 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Unfortunately this is an issue with the C++ extension, please forward the issue to them.
