### ISSUE TITLE
For some extension involving language server, the uninstllation have to restart if the language the server is running

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#34794]
- VSCode Version: Version 1.16.1
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Install extension either of the following : [C#](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp), [C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), [Java](https://marketplace.visualstudio.com/items?itemName=redhat.java)
2. Open the related files (.cs, .cpp, or .java) to make the language server running
3. Try to uninstall the related extension
4. The extension cannot be uninstalled on the extension view. Have to restart in this case. 

Reproduces without extensions:  No

**Comment by sandy081** [comment]
@yaohaizh I saw the error while uninstalling is coming from the extension. May I know how is it related to VS Code? What has to be the expected behaviour if the extension throws an error while uninstalling?

**Comment by yaohaizh** [comment]
For this issue, it happens for different extension as listed above, but not a specific extension.  This should related to the uninstall behavior of VSCode extension, which cannot be fixed on the extension side. 

On the other hand, I'm not sure if this is by design behavior or should be fixed with additional VSCode API. For example, VSCode can provide API for uninstall extension such as onUninstallExtension(...). Thus, on each extensions, then can gracefully shutdown the server before remove extension.   For now, I cannot find such kind API for extension authoring.

Or prompt to the user to reload VSCode if some files cannot be deleted when uninstall extension.

**Comment by sandy081** [comment]
We do not shutdown the extension on Uninstall. It happens only when you close / refresh the window after. In other words, extensions are active and can run in the current section even when an extension is uninstalled. So providing such an API does not makes sense.

**Comment by yaohaizh** [comment]
On this issue, when uninstall the extension on the extension view, though the extension is still running on the current session, it is removed. But the UI is still confusing here. 

I already uninstalled the C++ extension here, but this can not be told from the below snapshot. I have to restart VSCode. 
![untitled](https://user-images.githubusercontent.com/17268517/30863901-ca8d2ce0-a304-11e7-9aed-8c698485c297.png)

**Comment by sandy081** [comment]
>>On this issue, when uninstall the extension on the extension view, though the extension is still running on the current session, it is removed

What do you mean by it is removed? It is removed from where?

>> I already uninstalled the C++ extension here, but this can not be told from the below snapshot. 
We do show reload action when you uninstall an extension. If this is not true it is a bug and please file a separate issue for that. See the following video showing how it works in case of uninstall

![kapture 2017-09-27 at 9 16 54](https://user-images.githubusercontent.com/10746682/30900613-f52bd27a-a364-11e7-9de2-16ddce0408de.gif)

Also, we show some UI gestures if an extension is installed and not active

![image](https://user-images.githubusercontent.com/10746682/30900555-be37206c-a364-11e7-92d2-d3ac31fc8b8f.png)

Finally, I am not sure how the above comment is related to this issue.

**Comment by yaohaizh** [comment]
For C++: 

![uninstall](https://user-images.githubusercontent.com/17268517/30901035-dd361070-a398-11e7-95df-952e0bf9ad16.gif)

**Comment by sandy081** [comment]
@yaohaizh Can you please file a new issue for this. I do not want the main issue here to be side tracked.

**Comment by yaohaizh** [comment]
@sandy081  This is the issue I want to file. The same issue happens for C#/Java.

**Comment by sandy081** [comment]
Ok. Can you please update the issue then. Also provide if there are any errors in the console of VS Code. Also open Dev tools for Shared process (from command pallette) and see if there are any errors there.
