### ISSUE TITLE
Destructuring object parameter and setting a properties default value to an array literal confuses the syntax highlighter when there's a line break

### ISSUE THREAD

**Issue by marco-ramirez** [Microsoft/vscode#34790]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra version 10.12.6

Steps to Reproduce:

1. Open a new file
2. Set the language to JavaScript
3. Enter the following code:
```js
const a = ({
    b = []
}) => b;
```
4. Notice syntax highlighting breaks after the array literal

The problem doesn't occur if you omit the line breaks.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I believe this has been fixed in the [latest code insiders builds](https://code.visualstudio.com/insiders). Please try these out and let me know if you still see this issue

**Comment by marco-ramirez** [comment]
The issue is resolved in the insiders build. Thanks!
