### ISSUE TITLE
CTRL+P incorrectly maps to Open File on Windows

### ISSUE THREAD

**Issue by riverar** [Microsoft/vscode#34798]
- VSCode Version: 1.14.1
- OS Version: 1703

Steps to Reproduce:

1. Press CTRL+P
2. Note print dialog does not appear

Expected:

* Print dialog appears (if extension present) or nothing at all if capability isn't present

Reproduces without extensions: Yes

---

Use of `CTRL+P` for printing actions roots to the beginning of Microsoft Windows and Microsoft Office UX time. Re-purposing this shortcut runs against decades of user muscle memory for no obvious gain in usability. Users will either never remember the hotkey or be slowly retrained, impacting their use of all other apps -- legacy desktop and modern --  on Windows that implement this hotkey properly today.

Do the right thing here.

**Comment by kieferrm** [comment]
There is a printing extension now in the market place.
