### ISSUE TITLE
NWJS Debugging Support

### ISSUE THREAD

**Issue by voxking** [Microsoft/vscode#3479]
I want to know if you guys are willing to support nwjs debugging like WebStorm does because i find your editor much better because of the best typescript support and the git integration.

Thanks.

**Comment by weinand** [comment]
@voxking did you try the [Chrome debugger extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) for VS Code? If the Chrome DevTools work for NWJS then the Chrome debugger extension should as well.

**Comment by voxking** [comment]
ok i will try it.

**Comment by karikera** [comment]
I made it! :D
https://marketplace.visualstudio.com/items?itemName=ruakr.vsc-nwjs
