### ISSUE TITLE
Wrong indentation of block comments.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#348]
![indent-of-block-comment](https://cloud.githubusercontent.com/assets/1937871/11301257/fe7534bc-8fd8-11e5-80ba-85b32be4e3c6.gif)

A space before the first `*` in each line is lost.
This behavior is inconvenience a bit.

**Comment by alexandrudima** [comment]
Indeed, this is due to the indentation logic "normalizing" indents, but being unaware of doc comments that should be left "un-normalized"

**Comment by mysticatea** [comment]
Thank you very much!
I'm looking forward to the next version.
