### ISSUE TITLE
Small case _l_ rendered as upper case _L_ in markdown editor

### ISSUE THREAD

**Issue by SimplyInk** [Microsoft/vscode#34801]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
python|don|0.7.0
xml|Dot|1.9.2
VBScript|lug|0.0.2
mssql|ms-|1.1.0
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. edit a markdown file (*.md)
2. `_l_` rendered as `_L_` (italics)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Can you please provide a screenshot and explain the issue in more detail. Here's what I see:

<img width="344" alt="screen shot 2017-09-21 at 9 13 06 pm" src="https://user-images.githubusercontent.com/12821956/30729084-b4459c0c-9f11-11e7-95c7-7b4e9cb71672.png">

**Comment by SimplyInk** [comment]
Hi,

Finally realised that the itallic small cap 'L' looked like a capital 'L':

![image](https://user-images.githubusercontent.com/12554237/30952780-c796f450-a45b-11e7-98ef-1b631644f03e.png)

"editor.fontFamily": "Consolas"
