### ISSUE TITLE
VScode always crashs and force user reopen window When I open more five terminals

### ISSUE THREAD

**Issue by lunmatu101** [Microsoft/vscode#34800]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
laravel-5-snippets|ate|0.0.1
random-string-password-generator|bib|1.0.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
jquerysnippets|don|0.0.1
tslint|eg2|1.0.8
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.23.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
flow-for-vscode|flo|0.7.1
auto-close-tag|for|0.5.0
beautify|Hoo|1.1.1
rest-client|hum|0.15.2
docthis|joe|0.4.8
laravel-blade|KTa|0.0.1
node-module-intellisense|lei|1.4.0
vs-color-picker|lih|0.6.0
debugger-for-chrome|msj|3.3.0
node-modules-resolve|nau|1.0.2
laravel-blade|one|1.9.0
laravel5-snippets|one|1.3.4
tsimporter|pmn|1.2.14
remote-vscode|raf|1.1.0
java|red|0.10.0
vscode-icons|rob|7.13.0
laravel-5-snippets|sac|2.0.1
ionic2|Tha|2.4.0
cordova-tools|vsm|1.2.12
vscode-react-native|vsm|0.4.2
JavaScriptSnippets|xab|1.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
