### ISSUE TITLE
Hiding contributed split panes broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#34809]
1. Start debugging, debug viewlet
2. Try to hide Loaded Scripts view via context menu
3. The context menu action will not go away :bug:
4. Once the pane finally gets hidden hiding other panes and bringing them back will show the Loaded Scripts view even though it should remain hidden in the whole process :bug:

**Comment by joaomoreno** [comment]
@isidorn Is this a regression? Nothing changed in the underlying code, since @sandy081 first created it.

**Comment by isidorn** [comment]
I can reproduce with the current stable. So it is not a regression and not introduced by your split view refactor

**Comment by sandy081** [comment]
I will look into it.

**Comment by joaomoreno** [comment]
@sandy081 I'd say don't do anything here, and let's merge my changes. Can you give me the list of issues you found?

**Comment by weinand** [comment]
The loadedScripts view is now registered for four different IDs (instead of one ID).
