### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xianglongzhang** [Microsoft/vscode#34805]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please provide details about the issue you are facing.
