### ISSUE TITLE
Debug: VSCode API tests always stops in bootstrap.js

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34807]
- VSCode Version: 1.17-insiders
- OS Version: macOS

Steps to Reproduce:

1. start the VSCode API tests debug config
2. you end up in bootstrap.js stopped

![image](https://user-images.githubusercontent.com/900690/30731545-496307c8-9f6e-11e7-90b6-1b990dcded0d.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/34020, should be fixed in the next insiders
