### ISSUE TITLE
perf profile

### ISSUE THREAD

**Issue by dhagej** [Microsoft/vscode#34806]
[0c77_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1323589/0c77_main.cpuprofile.txt)
[0c77_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1323590/0c77_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)</code>
- OS Version: <code>Windows_NT x64 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)</code>
- Memory (System): <code>7.70GB (1.76GB free)</code>
- Memory (Process): <code>225.63MB working set (225.63MB peak, 205.48MB private, 44.12MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|125|
|main|app.isReady => window.loadUrl()|432|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|919|
|renderer|require(workbench.main.js)|3254|
|renderer|create extension host => extensions onReady()|2593|
|renderer|restore viewlet|1481|
|renderer|restore editor view state|2381|
|renderer|overall workbench load|4046|
|main + renderer|start => extensions ready|7465|
|main + renderer|start => workbench ready|8832|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`0c77_main.cpuprofile.txt`
-`0c77_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Nothing suspicious here... Code loading seems quite slow but that should get faster after a while as cached data is produced on demand.
