### ISSUE TITLE
Language definitions are not correct

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#34804]
- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

```javascript
function download() {
	const a = document.createElement('a');
	a.href = ''; // href: support.variable
	a.target = ''; // target: support.variable
	a.download = ''; // download: variable.other (THIS IS BAD!)
}
```

```javascript
window.navigator.userAgent.toLowerCase(); // navigator: variable.other (THIS IS BAD!)
window.location.href = '' // Here everything is good, all are support.variable
```

Even GitHub doesn't have proper language definitions and it doesn't colorize these properties 😄 

To see it I used `Developer: Inspect TM Scopes`.

This is a little bit annoying, because it's hard sometimes to read code when code coloring is different, because of bad language definitions theme authors can't fix it.

**Comment by tomas-cimermonas** [comment]
I've faced same issue with properties. Looking for solution.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#523
