### ISSUE TITLE
Git diff indicators near line numbers & on the scroll-bar doesn't work in submodules.

### ISSUE THREAD

**Issue by caudatecoder** [Microsoft/vscode#34808]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open a git project with submodule.
2. Edit a file in the submodule.

Reproduces without extensions: Yes

---
As far as I remember, everything was fine before 1.16.1 update

**Comment by joaomoreno** [comment]
#7829

**Comment by caudatecoder** [comment]
@joaomoreno 
It's definitely different issue.
The issue you referred to is about viewing changes via diff-tool.

I'm talking about diff-indicators when you directly see the file. This feature was working in previous versions.

**Comment by joaomoreno** [comment]
@caudatecoder If it worked before, it was accidental. We simply never did any feature work to support submodules yet.
