### ISSUE TITLE
When there is only one build task, please just run it. Don't make me pick it from a one item list.

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#34802]
- VSCode Version: 1.16.0
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Create a tasks.json file with a single build task.
2. Press Ctrl+Shift+B and you will be prompted to select the single build task from an item list with one item in it. 

That is just dumb.  If there is a single build item, PLEASE JUST RUN THE BUILD TASK when I press Ctrl+Shift+B.  The current behavior just slows me down.

Reproduces without extensions: Yes

**Comment by Jeyanthinath** [comment]
@rkeithhill If you have only one task , you can use code runner extension to configure it , then it will be a one click run and an addtional UI button will be also supported.

**Comment by dbaeumer** [comment]
@rkeithhill you can control this behavior since other users wanted to be asked because with tasks auto detection things can change under the cover. Simple add this to the task in the tasks.json file:

```json
			"group": {
				"kind": "build",
				"isDefault": true
			}
```

**Comment by dbaeumer** [comment]
Side note: the default task support requires task version "2.0.0"
