### ISSUE TITLE
When I try to open multiple editors with Ctrl+P each one replaces the previous one

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#34814]
- VSCode Version: 1.16.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open any source file with Ctrl+P
2. Open another file with Ctrol+P. 

Effect: The second file opens in the same tab. Instead of having the 2 files open only the last one remains.

**Comment by jhasse** [comment]
I think this is intentional because of ` "workbench.editor.enablePreview": true`.

**Comment by ramya-rao-a** [comment]
@jhasse  is right.

See https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by gozzoo** [comment]
Thanks for the hint, now it makes sense. I'm still confused though. The documentations says:

> When you start editing the file or use double-click to open the file from the Explorer, a new Tab is dedicated to that file.

What's the equivalent of double-click when you open a file with 'quick open'. It seems I don't have the option to open the file permanently with quick open unlike when I open it from explorer.

**Comment by ramya-rao-a** [comment]
I dont think there is an equivalent option in quick open for that.
cc @bpasero to confirm

You can disable the preview mode in general by setting `workbench.editor.enablePreview` to `false`

**Comment by bpasero** [comment]
There is also for quick open specifically: `"workbench.editor.enablePreviewFromQuickOpen": false`
