### ISSUE TITLE
win10下打开文本文件 中文乱码

### ISSUE THREAD

**Issue by liyangfd** [Microsoft/vscode#34817]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1、win10 企业版
2、桌面右键  新建文本文件
3、输入  我是中国人 并保存
4、用VSCode打开 发现乱码

**Comment by shizengzhou** [comment]
文本文件保存时是GBK的编码，VSCode打开文件默认是utf-8编码，所以乱码了。你换编码试一下。

**Comment by ramya-rao-a** [comment]
Like @shizengzhou suggested, try chnaging the encoding on the file in VS Code
See https://code.visualstudio.com/updates/v0_3_0#_file-encoding
