### ISSUE TITLE
connect ECONNREFUSED ../Code/1.15.1-shared.sock

### ISSUE THREAD

**Issue by codenoid** [Microsoft/vscode#34815]
hi, i got this message when opening (click) on extension menu, and extenstion list not working

`connect ECONNREFUSED /Users/ruby/Library/Application Support/Code/1.15.1-shared.sock`

OSX sierra
vs code 1.15.1

**Comment by sandy081** [comment]
Looks like there is some instance of Code hanging on to the above socket. Can you try quitting those dangling Code instances and try again?

**Comment by codenoid** [comment]
@sandy081 , i dont know why, but i think the problem has been fixed after restart the vscode
