### ISSUE TITLE
Working Tree window empty when opening first time

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#34816]
- VSCode Version: 1.16.1
- OS Version: Windows 7

Steps to Reproduce:

This applies to projects under git source control

0. Commit all changes.
1. Change some file
2. Go to 'Source Control' from 'Activity bar'. In 'Changes' section the edited file should be listd.
3. Double click the file name.

Effect: new tab opens but the content is empty.

If I do the same thing after a while the compare view opens without problem.

**Comment by joaomoreno** [comment]
Can you share a screenshot?

**Comment by gozzoo** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/296970/30820708-6984ef02-a22b-11e7-8882-bd3acf258c02.png)

**Comment by joaomoreno** [comment]
If you open the Developer Tools (<kbd>F1</kbd>, `Developer Tools`) do you see any errors there?

**Comment by gozzoo** [comment]
No.

![image](https://user-images.githubusercontent.com/296970/30858095-cf1c68c2-a2c6-11e7-8fe7-16b42d043110.png)

**Comment by joaomoreno** [comment]
@alexandrudima @bpasero Anything you guys know that might be helpful here?

**Comment by bpasero** [comment]
Maybe run with "break on error"? I wonder if we hit an exception but do not show it.

**Comment by alexandrudima** [comment]
@joaomoreno This looks as if the diff editor gets null models or the models get disposed after being attached.

@gozzoo Do you have any problem when right clicking on a file in the explorer and selecting "Compare" and then right clicking on another file an selecting "Compare with ....". This will also bring up the diff editor, but with comparing two files on disk. Does this work consistently?

**Comment by gozzoo** [comment]
It happens when I try to open the compare view the first time. If I close it and try again latter it works.

I noticed on the empty screen, that right of the scrollbar there is a vertical bar with color bands (visible on the screenshot), which represent the changes. I noticed that when I manage to open the same compare view again the color pattern on the right is not the same as the one on the empty screen.

alexandrudima - I tried to compare 2 files, everything was fine.

**Comment by gozzoo** [comment]
I just noticed that this happens more often on slow hardware. I have a very old laptop (~10yo) and it happens amost always when I first try to open compare view. On my desktop, which is also old, but much faster than the latpop it happened only once.

Could this be some kind of race condition?

**Comment by joaomoreno** [comment]
@gozzoo Is this still an issue for you?

**Comment by gozzoo** [comment]
The problem has disappeared since the last release, thaks.
