### ISSUE TITLE
showWorkspaceFolderPick not enforced as proposed api

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34819]
The implementation of [`showWorkspaceFolderPick`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L353) must use the `proposedApiFunction`-wrapper.

Alternatively, we make it final API this milestone

**Comment by bpasero** [comment]
I guess we need to decide this next week, for now I added the function wrapper.
