### ISSUE TITLE
Cannot dismiss top bar notifications. 

### ISSUE THREAD

**Issue by guy-kdm** [Microsoft/vscode#34818]
When getting a notification like "Failed to save... content on disk is newer..." They linger indefinetly and cannot be dismissed aside from choosing compare. I think there should be a general method to dismiss notifications.

**Comment by jhasse** [comment]
For me pressing <kbd>esc</kbd> works (Linux).

**Comment by ramya-rao-a** [comment]
The ESC key dismisses all notifications.

cc @bpasero if  we should have a separate Cancel/Close button

**Comment by ramya-rao-a** [comment]
@bpasero What were you not able to repro?

The message `Failed to save... content on disk is newer...` ?
