### ISSUE TITLE
Go To Bracket doesn't scroll to the cursor

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#34824]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64

When using Go To Bracket and the matching bracket is out of view, the editor should scroll to it (it does as soon as I start typing).

**Comment by alexandrudima** [comment]
Duplicate #18540
