### ISSUE TITLE
Hovering on View in horizontal menu bar obstructs the viewing of next menu item

### ISSUE THREAD

**Issue by ramvalleru** [Microsoft/vscode#34822]
- VSCode Version: 1.6.1
- OS Version: Microsoft Windows 10 Pro (Build) 10.0.1506

![vscode_view](https://user-images.githubusercontent.com/17983707/30738295-ed177e74-9f89-11e7-9bd2-c876fd4c6d36.png)
3

Steps to Reproduce:

1. Try to hover over the "View" menu on the top horizontal menu bar.
2. Instead of the sub items from the menu appearing on the bottom of the menu item, appears on to the side of the item.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
I believe this happens when there is not enough space to show the complete menu below

**Comment by ramvalleru** [comment]
Yeah. So isn't this a design glitch which needs to be fixed.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17457
