### ISSUE TITLE
not able to set up the code

### ISSUE THREAD

**Issue by Sujay-shetty** [Microsoft/vscode#3482]
Hi,

I'm trying to set up vscode locally but getting the following error.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "extensions/vscode-ap
i-tests/" "install" "extensions/vscode-api-tests/"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! vscode-api-tests@0.0.1 postinstall: `node ./node_modules/vscode/bin/ins
tall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-api-tests@0.0.1 postinstall script 'node ./node_mo
dules/vscode/bin/install'.
npm ERR! This is most likely a problem with the vscode-api-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/vscode/bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls vscode-api-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vs-code\vscode-master\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Code@0.10.10 postinstall: `npm --prefix extensions/vscode-api-tests/ in
stall extensions/vscode-api-tests/ && npm --prefix extensions/json/ install exte
nsions/json/ && npm --prefix extensions/typescript/ install extensions/typescrip
t/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Code@0.10.10 postinstall script 'npm --prefix extensions/
vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extension
s/json/ install extensions/json/ && npm --prefix extensions/typescript/ install
extensions/typescript/'.
npm ERR! This is most likely a problem with the Code package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm --prefix extensions/vscode-api-tests/ install extensions/vscode
-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --p
refix extensions/typescript/ install extensions/typescript/
npm ERR! You can get their info via:
npm ERR!     npm owner ls Code
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vs-code\vscode-master\npm-debug.log

Python 2.7 environment path as well as visual studio 2013 path has been set.

When I execute ./scripts/npm.bat install command it installs some of the components but while testing it is throwing the above error.

Please help me to resolve this issue.

Thanks,

**Comment by joaomoreno** [comment]
@bpasero any idea?

**Comment by bpasero** [comment]
@Sujay-shetty can you attach the npm debug log?

**Comment by Sujay-shetty** [comment]
Hi @bpasero, 
Please find the npm logs below.

304 info Code@0.10.10 Failed to exec postinstall script
305 verbose stack Error: Code@0.10.10 postinstall: `npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/`
305 verbose stack Exit status 1
305 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
305 verbose stack     at emitTwo (events.js:87:13)
305 verbose stack     at EventEmitter.emit (events.js:172:7)
305 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
305 verbose stack     at emitTwo (events.js:87:13)
305 verbose stack     at ChildProcess.emit (events.js:172:7)
305 verbose stack     at maybeClose (internal/child_process.js:818:16)
305 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
306 verbose pkgid Code@0.10.10
307 verbose cwd E:\vs-code\vscode-master
308 error Windows_NT 6.1.7601
309 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
310 error node v4.2.2
311 error npm  v2.14.7
312 error code ELIFECYCLE
313 error Code@0.10.10 postinstall: `npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/`
313 error Exit status 1
314 error Failed at the Code@0.10.10 postinstall script 'npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/'.
314 error This is most likely a problem with the Code package,
314 error not with npm itself.
314 error Tell the author that this fails on your system:
314 error     npm --prefix extensions/vscode-api-tests/ install extensions/vscode-api-tests/ && npm --prefix extensions/json/ install extensions/json/ && npm --prefix extensions/typescript/ install extensions/typescript/
314 error You can get their info via:
314 error     npm owner ls Code
314 error There is likely additional logging output above.
315 verbose exit [ 1, true ]

**Comment by bpasero** [comment]
@joaomoreno I can reproduce on Win 10 with npm 3, but not with npm 2. I think npm 3 might be more picky about failing postinstall tasks.

It fails here for me: 

npm ERR! vscode-json-server@0.0.1 compile: `tsc -p .`
npm ERR! Exit status 2

**Comment by aeschli** [comment]
We delivered a fix to our build scripts. The NPM postinstall hooks no longer trigger the compilation of the JSON extension. This is now done in our regular build script (gulp watch).
I tested it with npm 3.
