### ISSUE TITLE
Can we have a Open in the right pop up menu on the files view

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#34820]
- VSCode Version:
- OS Version:

I have icons, sound files, batch files and other files that I would like to "open/run" or "edit" natively with the right click menu on the file view so I can quickly run the file or edit the file with it's native editor.

For example I can Open a Batch File in explorer or I can Edit. I can play a sound or edit it with audacity... Explorer's right click menu gives me both options. Same with a Sound File and so many others. the system allows this so might as well use it!

Related, the Reveal in Explorer should be in it's Own group which would also have the "open" Native and, if the "edit" options is present, the "edit" Native

Sorry for the bold large font
Menu Change Suggestion:
Open to the side
Open in Terminal
-
Open In Explorer
Open/Run Natively
Edit Natively (This menu may or may not be available, hidden/grayed if "edit" command is not registered for the file type)
-
Copy
Copy Path
-
Rename
Delete

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
So you are talking about the "Open With" feature that is available on native file explorers?

**Comment by icuurd12b42** [comment]
![image](https://user-images.githubusercontent.com/6321426/30760219-4e775078-9fa7-11e7-903c-f22f081ebb71.png)
If the attachment holds, the black arrows are the things I was talking about, these are tied to the "open" "edit" "print" verbs available.  For the file type.  
Executed with a shell "edit" filename type command... shell "open" filename, shell "print" filename

The blue arrows would be icing on the cake if added

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
