### ISSUE TITLE
Can't find npm module!

### ISSUE THREAD

**Issue by bobKasbi** [Microsoft/vscode#34827]
VSCode Insider can't find node modules even they exists in the project root.
Happens after upgrade.

- VSCode Version: Version 1.17.0-insider (1.17.0-insider)
- OS Version: Mac Sierra

Steps to Reproduce:

1. Import module in a ts file: 
`import { Component } from '@angular/core';`
2. Error: 
`[ts] Cannot find module '@angular/core'.`

I noticed that it affects all the angular modules e.g. `@angular/http`, `@angular/material`, `@angular/router` and `@angular/forms`

**Comment by andy-ms** [comment]
Looks like a duplicate of #34681

**Comment by bobKasbi** [comment]
Yes, it is. Thanks!
