### ISSUE TITLE
Smarter workspaceContains handling?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34823]
Would it be possible to avoid a full workspace scan from every `workspaceContains` that an extension declares by stopping a search once the first result is found? I know that this should work from the classic file traversal implementation but I am not sure about `RipGrep`. Maybe there is a command to use `RipGrep` in such a way that it would just return 0 or 1 when a result is found?

Alternatively we could also do a heuristic: we could first do a quick check of the root level files of the workspace folders and only run the more expensive file search if no files match. I would argue that in most cases the file of interest would actually be in the root folder (e.g. `tsconfig.json`).

**Comment by alexandrudima** [comment]
At the time this was implemented, that was the contract of the `DiskSearch`.

I don't know if that changed in the meantime.

https://github.com/Microsoft/vscode/blob/de99997ab5715de51a1a9903acf46e487e73f7fa/src/vs/workbench/node/extensionHostMain.ts#L224

```ts
		const query: ISearchQuery = {
			folderQueries: this._workspace.folders.map(folder => ({ folder: folder.uri })),
			type: QueryType.File,
			maxResults: 1,
			includePattern: includes
		};
```

**Comment by bpasero** [comment]
Ah ok, didn't know about `maxResults`, @roblourens can maybe clarify if this is supported in `RipGrep` too.

**Comment by roblourens** [comment]
It is implemented for text search with ripgrep, but looks to be not implemented for filesearch with `rg` or `find`. @chrmarti

**Comment by chrmarti** [comment]
@roblourens `--quiet` will tell us if there is a matching file (in ripgrep 0.6.0, we'd need to upgrade from 0.5.2) but not what the match is (which we need for `maxResults: 1`, but not necessarily for `workspaceContains`). I don't see any other options we can use, `--max-count` doesn't do anything with `--files`.

**Comment by roblourens** [comment]
We can kill the process as soon as we get the right number of results, this is what text search does.

**Comment by chrmarti** [comment]
We could optimize this case with an additional flag `exists: true` and for that pass `--quiet`. That will avoid all output to stdout and terminate immediately on the first hit. This will need an upgrade of ripgrep we ship though.

**Comment by chrmarti** [comment]
One way to verify with extension code is by using `workspace.findFiles` with a low `maxResults` against a large workspace and make sure it is much faster than without `maxResults`.
