### ISSUE TITLE
No results when using "find all references"

### ISSUE THREAD

**Issue by SandW** [Microsoft/vscode#34838]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.12.4
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1. mouse right click, find all references
2. always no results when editing c/c++ projects

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
Find all References for c/c++ comes from the extensions you use. Please log an issue in the repo for the c++ extension
