### ISSUE TITLE
Encoding status doesn't update

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34837]
* have a remote file with some encoding
* use the picker to select an different encoding
* note that editor updates, funky characters get re-interpreted
* note that the status bar never updates...

![sep-22-2017 15-23-23](https://user-images.githubusercontent.com/1794099/30746445-20ab6d98-9faa-11e7-91a7-64c880036695.gif)

**Comment by bpasero** [comment]
@jrieken another case of `toResource` using the file/untitled filter (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorStatus.ts#L699). Moving to @isidorn

**Comment by isidorn** [comment]
Fixed via 15b1f59905
