### ISSUE TITLE
Integrated terminal selection is off

### ISSUE THREAD

**Issue by Haroenv** [Microsoft/vscode#34842]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider) f7962f0682a76516df51de4856f8ccc5d8ad578a
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. try to select text on the integrated terminal
2. the cursor is a line and a few characters off

![2017-09-22 16_06_24](https://user-images.githubusercontent.com/6270048/30748245-fe64e952-9faf-11e7-812b-716e1fe582e4.gif)

Reproduces without extensions: Yes

**Comment by yume-chan** [comment]
Duplicate of #34184

**Comment by Haroenv** [comment]
Yep, closing as a duplicate, thanks
