### ISSUE TITLE
[theming] Use different colors for rendering warning and info markers

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#34849]
Both the lsp and vscode api support different severity levels for linter style markers:

- error
- warning
- info

However it seems that the editor theming doesn't actually make a distinction between warning and info (both of them look identical and render as a green squigly underline).

![warning-and-information](https://user-images.githubusercontent.com/1002156/30756085-e7fe68a0-9f7d-11e7-8665-f3a0ef03050c.png)

A more traditional way of rendering is to use Red for errors, Yellow for warnings and either Green or Blue for info.

I looked at trying to change these looks via the theming support, but as far as I could figure out, the 'equal treatment' of warnings and infos goes down to the theming engine as well. Looking here:

https://code.visualstudio.com/docs/getstarted/theme-color-reference

I find that there are properties like `editorError.foreground` and `editorWarning.foreground`, but there is no `edtitorInfo.foreground` and the info squiglies simply follow the warning color if it is changed.

**Comment by dbaeumer** [comment]
See also https://github.com/Microsoft/vscode/issues/9209 which contains discussion to use yellow for warnings out of the box.

**Comment by aeschli** [comment]
I separated the warning and info colors and added new color ids
- `editorInfo.foreground`
- `editorInfo.border`
- `editorMarkerNavigationInfo.background`

I haven't changed the color yet (warning and info are still green). I'll wait for color recommendations from the UX team, see #9209.

**Comment by kdvolder** [comment]
Wow! Fixed so fast! Will this fix show up in the 'vscode insiders' soon? I'd like to give it a try if I can.
