### ISSUE TITLE
Git not found as "installed" 

### ISSUE THREAD

**Issue by Haroenv** [Microsoft/vscode#34848]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider) f7962f0682a76516df51de4856f8ccc5d8ad578a
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. open a git folder
2. nothing else

<img width="333" alt="screen shot 2017-09-22 at 17 43 06" src="https://user-images.githubusercontent.com/6270048/30752773-9ef80bc6-9fbd-11e7-864e-b43dda1c3cb1.png">

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Where is your git installed? Does git work from the command line?

**Comment by Haroenv** [comment]
yep, git works perfectly on the command line, even on the integrated terminal. It stopped working in VSCode last week.

**Comment by Haroenv** [comment]
This wasn't an issue before, but I could fix it by setting: 

```json
{
  "git.path": "/usr/local/bin/git"
}
```

in my settings

**Comment by joaomoreno** [comment]
Interesting. If you open the dev tools in Code, does `process.env.PATH` include that `/usr/local/bin` path?

**Comment by Haroenv** [comment]
`/usr/local/bin` is in the PATH on my system and in the devtools, yep

**Comment by joaomoreno** [comment]
This is odd... in the Terminal what does `which git` return?

**Comment by Haroenv** [comment]
```sh
$ which git
/usr/local/bin/git
```

It's just the git that came with Xcode or with homebrew IIRC

**Comment by joaomoreno** [comment]
And what does `git --version` return?

**Comment by Haroenv** [comment]
```
$ git --version
git version 2.11.1
hub version 2.2.9
```

**Comment by joaomoreno** [comment]
Hm... and I'm guessing there's nothing in the Devtools right?

**Comment by joaomoreno** [comment]
We can chat here, if you're online for while longer: https://tlk.io/vscode34848
