### ISSUE TITLE
Option to open cmd or powershell both.

### ISSUE THREAD

**Issue by DadyByte** [Microsoft/vscode#34845]
- VSCode Version:1.16.1
- OS Version: Windows 7

Steps to Reproduce:

1. Press Ctrl + ` to open integrated terminal
2. Click + button to open new terminal

There should a option to select cmd or powershell based on option.

**Comment by Tyriar** [comment]
You should be able to run cmd/powershell in either terminal to run an inner shell as a workaround.

There is this extension as well which provides the functionality you're after https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
