### ISSUE TITLE
Revisit getWorkspace-API

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34843]
We have added the `getWorkspace`-api with some special behaviour in case it's called with the path of a workspace. Not every expected that it behaves like and we should (1) have a flag to make it behave different, e.g. return the workspace folder if called with one and (2) consider changing/breaking the defaults

**Comment by jrieken** [comment]
@sandy081 Is your tool ready to check on usages of this?

**Comment by jrieken** [comment]
cc @bpasero, @dbaeumer

**Comment by bpasero** [comment]
+1 for changing the default behaviour and adding that option for the current behaviour.

**Comment by sandy081** [comment]
@jrieken Not yet. Will be ready by tomorrow.

**Comment by dbaeumer** [comment]
+1 for changing this.

@aeschli and I once had a discussion how to provide this in the LSP (which we didn't at the end) and one idea was that getWorkspaceFolder returns the folder if called with one and that we have a second method getParentWorkspaceFolders which returns an array of all parent folders. The idea was that if I am interested in nesting I am very likely interested in all parents or the top most parent. That would avoid having a flag and looping.

**Comment by jrieken** [comment]
I went through the list of extensions using this and how they use it. I was able to find the sources of two but all the others use `getWorkspaceFolder` with a document-url. That means they won't be affected by the planned change. 

This is what I am planning to do (when being called with a workspace folder)

1. Return workspace folder if `uri` points to a workspace folder and if `resolveParent` is `falsy`
2. Return `undefined` or parent workspace folder if `uri` points to a workspace folder and if `resolveParent` is `true` (to today behaviour)


```
export function getWorkspaceFolder(uri: Uri, resolveParent?:boolean): WorkspaceFolder | undefined;
```

**Comment by bpasero** [comment]
Makes sense, though the name `resolveParent` implies to me that there is some actual work behind it, maybe a better name could be found.

**Comment by jrieken** [comment]
Yeah, nuked the parent-stuff all together

**Comment by sandy081** [comment]
@jrieken Check this out to download extensions from marketplace 

https://github.com/Microsoft/vscode-tools#downloading-extensions-from-marketplace
