### ISSUE TITLE
[folding] Expand action should restore cursor position inside folded region iff cursor didn't change since fold action

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3484]
Confusing, but let me elaborate. Before #3400, I could run `Fold` `Fold` `Fold` actions in a deeply nested folding region and then `Expand` `Expand` `Expand` and my cursor would return back to the original position.

Although #3400 is the good fix, it did remove that functionality unfortunately.

Maybe there is a way for the actions to cooperate between themselves and have the expand action restore the cursor position iff it hasn't changed since the fold action.

**Comment by aeschli** [comment]
Fixed by #3814
