### ISSUE TITLE
Implement local file system provider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34840]
Just because we can, because it will help with running the extension host somewhere, and to align the code we should strive for a [`IFileSystemProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L178) that works against the local disk (basically what we have today in another implementation of the fileService). Also, it will show if the provider story is strong enough, what pieces are still missing. @bpasero How much confidence do you have the [fileService tests](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/test/node/fileService.test.ts)?

**Comment by bpasero** [comment]
@jrieken [quit a bit](https://coveralls.io/builds/13386546/source?filename=src%2Fvs%2Fworkbench%2Fservices%2Ffiles%2Fnode%2FfileService.ts), though it looks like the coverage went down after we added more stuff. Maybe time to add some more tests for the gaps we have.

**Comment by bpasero** [comment]
First cut: https://github.com/Microsoft/vscode-extension-samples/tree/master/nodefs-provider-sample

**Comment by bpasero** [comment]
This will actually now happen on master.

**Comment by suntobright** [comment]
Just wondering if this is a extra feature or a replacement of the original local file operation implementation? If it’s a replacement, does it mean the search viewlet support file system provider natruely other than the local one?

**Comment by bpasero** [comment]
This is a replacement of our file service to play nice with `IFileSystemProvider`. It is unrelated to search.
