### ISSUE TITLE
Unable to load schema for setting files

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#34844]
VSCode out of source
Open settings file, notice warning and that there is no json schema support
Notice the same if you open a launch.json
fyi @aeschli 

![screen shot 2017-09-22 at 15 39 12](https://user-images.githubusercontent.com/1926584/30748603-102a6b84-9fb1-11e7-9086-d2c7764a2916.png)

**Comment by sandy081** [comment]
@isidorn I cannot reproduce it in out of sources / insiders.

Let me know if there are any specific steps I should follow.

**Comment by isidorn** [comment]
This works now, somebody fixed it in the meantime
