### ISSUE TITLE
After Signing PowerShell script in VSCode, file remains “unsaved/changed”

### ISSUE THREAD

**Issue by CPUTek1** [Microsoft/vscode#34852]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
beautify|Hoo|1.1.1
mssql|ms-|1.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-icons|rob|7.13.0
html-css-class-completion|Zig|1.10.0

---

Currently I have this defined in my VSCode $profile:

`Register-EditorCommand -Name SignCurrentScript -DisplayName 'Sign Current Script' -ScriptBlock {     $cert = (Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert)[0]     $currentFile = $psEditor.GetEditorContext().CurrentFile.Path     Set-AuthenticodeSignature -Certificate $cert -FilePath $currentFile } `

When I run it to digitally sign my script, it signs it and saves it. However the vscode editor still thinks the file is marked as Changed/ Un-Saved.

**Comment by ramya-rao-a** [comment]
> Currently I have this defined in my VSCode $profile:

What do you mean by VSCode $profile?

**Comment by CPUTek1** [comment]
My Microsoft.VSCode_profile.ps1


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ramya-rao-a** [comment]
I am guessing that gets used by the Powershell extension?
