### ISSUE TITLE
Assertion Failed! error message when VSCode is open

### ISSUE THREAD

**Issue by fab1o** [Microsoft/vscode#34858]
- VSCode Version: 1.17.0-insider (updated on 9-22-2017 at 5:40 PM EST)
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open VSCode (Run: code --disable-extensions)
2. Open the Integrated Terminal (Click on View / Integrated Terminal or use the shortcut)
3. Exit VSCode (File / Exit)
4. Open VSCode again

Reproducible 100% of the time.

<img width="903" alt="vscode - step 1" src="https://user-images.githubusercontent.com/6663243/30765238-b33db050-9fbc-11e7-94cc-5fc6ab36b998.png">

<img width="904" alt="vscode - step 2" src="https://user-images.githubusercontent.com/6663243/30765583-60b75d84-9fbe-11e7-8220-426b31d0c2ea.png">

Microsoft Visual C++ Runtime Library | Assertion Failed! | ASSERT_CONDITION

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This should be fixed in another issue
