### ISSUE TITLE
php syntax highlighting has wrong heredoc termination rules

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/vscode#34851]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.1.0
python|don|0.7.0
reasonml|fre|1.0.0
cpptools|ms-|0.12.4
csharp|ms-|1.12.1

---

Steps to Reproduce:

Write a PHP file with the following contents:

$foo = <<<'EOF'
$bar and this and that
EOF.$bar.<<<'EOF'
and some more
EOF;

![image](https://user-images.githubusercontent.com/3316258/30756751-cc826b00-9f80-11e7-904f-d4481085cae2.png)

**WHAT I EXPECT**

The middle line `EOF.$bar.<<<'EOF'` should all be colored red because it all just a verbatim string, part of the heredoc. It does *not* terminate the first heredoc then start a new heredoc as you might think.

The relevant PHP spec for [heredoc](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) explains "It is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;)". The middle line doesn't meet this restriction and hence isn't a terminator.

And PHP parsers do indeed obey the spec in this respect: http://phpfiddle.org/lite/code/g2xf-edyv

So the syntax-highlighter should too!

Reproduces without extensions: Yes

**Comment by mattacosta** [comment]
Just checked. This has already been fixed (probably by f31c369).

**Comment by roblourens** [comment]
Indeed. Thanks!

**Comment by str** [comment]
This has nothing to do with folding a function with heredoc inside, not folding the function, right?

**Comment by roblourens** [comment]
Since folding is indentation-based, an issue like that is kind of expected unfortunately.

**Comment by str** [comment]
@roblourens I thought that changed in 1.17

https://code.visualstudio.com/updates/v1_17#_folding-regions

**Comment by roblourens** [comment]
Yeah we now also support folding regions by specific markers, but there's no change for folding a function body.
