### ISSUE TITLE
[seti] Incorrect icon colors in explorer when using Light themes

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#34850]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
cpptools|ms-|0.13.0
cmake-tools|vec|0.10.2
---

Steps to Reproduce:

1. Open a folder with a .bat, .xls, or .doc (which have distinguishable colors for their icons)
    * they can be empty files, you just need to get the extension in the filename
2. Switch the theme from Dark+ to Light+
3. Notice that the icons are the wrong colors in the Light+ theme.  (could be a BGR <-> RGB swizzle problem)
    * Windows & Word should be blue. Excel should be green.

Reproduces without extensions: Yes

![dark](https://user-images.githubusercontent.com/12818240/30756839-1c17e5b4-9f81-11e7-918d-d64d129ffcd5.png)
![light](https://user-images.githubusercontent.com/12818240/30756843-1d98d628-9f81-11e7-8fe0-286e7fc76dc4.png)

**Comment by aeschli** [comment]
The seti theme has otpimized the colors for dark themes. For the light theme we just invert the colors to ensure the contrast. Changing to darken it instead.
