### ISSUE TITLE
json autocomplete does not escape \ in strings?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3485]
Go to `settings.json`
Auto-complete editor.wordSeparators

![image](https://cloud.githubusercontent.com/assets/5047891/13350006/c74a89f0-dc7d-11e5-83d7-5eb40aa855bc.png)

**Comment by aeschli** [comment]
I delivered a workaround. The real fix is to disallow snippet syntax in settings default value and add snippet syntax escaping to the jsonSuggest code

**Comment by aeschli** [comment]
Fixed with changes from #3494
