### ISSUE TITLE
.deb package missing multiple dependencies

### ISSUE THREAD

**Issue by jasonzio** [Microsoft/vscode#34854]
- VSCode Version: 1.16
- OS Version: Ubuntu 1604

Steps to Reproduce:

1. Add Code repo to apt according to directions on https://code.visualstudio.com/docs/setup/linux
1. Run `sudo apt-get update; sudo apt-get install code`
1. Run `code`

The `code` program would not run; the error indicated missing libraries. The following packages had to be installed explicitly in order to get code to run:
- libgtk2.0-0
- libxss1
- libasound2

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13089
