### ISSUE TITLE
Incorrect html formatting for this in .vue files

### ISSUE THREAD

**Issue by amritk** [Microsoft/vscode#34859]
- VSCode Version: 1.61.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. set the "editor.formatOnSave": true
2. Save this code as a .vue file with the vetur extension enabled
```
<template>
    <v-icon v-for="n in 5" :key="n">
        {{ n <= details.rating ? 'star' : 'star_border' }}
    </v-icon>
</template>
```

it will format to 
```
<v-icon v-for="n in 5" :key="n">
    {{ n
    <=d etails.rating ? 'star' : 'star_border' }}
</v-icon>
```
which breaks it. I originally created this issue in the vetur repo but they told me the issue is with vscode.
https://github.com/vuejs/vetur/issues/452

Reproduces without extensions: No, needs vetur enabled for .vue support

**Comment by ramya-rao-a** [comment]
Same happens in html file as well and with all extensions disabled

My guess is that the `<=` gets treated as start of new tag?

**Comment by amritk** [comment]
@ramya-rao-a most likely

**Comment by octref** [comment]
I misread it. It's actually a bug with js-beautify.
