### ISSUE TITLE
Add a setting to prevent extra newline between brackets

### ISSUE THREAD

**Issue by jkyeung** [microsoft/vscode#34861]
Pressing Enter while the cursor is between empty brackets results in an extra newline before the closing bracket. For example, using `|` to represent the cursor, if we press Enter here

    foo = [|]

we get

    foo = [
        |
    ]

I'd love a setting which allows me to get this instead:

    foo = [
        |]

In case it's not clear, I'm thinking about all kinds of brackets, not just square brackets. Like, whichever ones `editor.autoClosingBrackets` handles.

**Comment by gelraen** [comment]
Could you please reconsider? This auto-newline bullshit is easily in my top 10 of most infuriating text editor misfeatures.

**Comment by ygqygq2** [comment]
`setttings.json` add `"editor.language.brackets": [],` can do what you say.

**Comment by jkyeung** [comment]
> `setttings.json` add `"editor.language.brackets": [],` can do what you say.

@ygqygq2 - No, it can't. You have misunderstood my issue.

@imax9000 @foreverstupid @tinynow @JuliusPunhal - Thank you for upvoting this issue. It's always nice to know that I'm not the only one! Especially for coming back after three years and still expressing support.

As far as I'm aware, there is still no setting within VS Code that handles this. However, for those of you who program in Python (which includes me), the [Python Indent extension](https://github.com/kbrose/vsc-python-indent/issues/66) *does* have a setting for this! (I just discovered this enhancement today, though it's actually been around for over two years now.) Which I guess means there's still no relief for other programming languages without a corresponding extension; but at least it offers a little hope, and perhaps even a roadmap for those who are motivated enough to take on writing their own extension.

**Comment by zimtsui** [comment]
This option is very useful for LISP user. Why is this issue closed😳

**Comment by zimtsui** [comment]
Ok I found a setting

```json
{
    "editor.autoIndent": "keep"
}
```

It's preset by the language extension whether it should add an extra new line. But VS Code can ignore that.
