### ISSUE TITLE
Terminal canvas renderer

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34868]
https://github.com/Microsoft/vscode/issues/34169

- [x] Windows - @alexandrudima 
- [x] Linux - @roblourens 
- [x] macOS - @seanmcbreen 

Complexity: 4

All rendering done by the terminal has moved from a completely DOM-based model to using canvas instead. Here are some things to focus on and look out for:

- Unicode characters, emojis, etc. behave correctly
-,Tweaking the terminal settings, font size/family and line height in particular
- Blurry text, lack of sub-pixel anti-aliasing
- The rows/columns not being the correct size for the panel
- Rows being cut off on the top
- Mouse coordinates when using selection, links and xterm mouse events are accurate
- Changing the window zoom level works as expected

**Comment by alexandrudima** [comment]
Nice job!
