### ISSUE TITLE
Clicking on file in git viewlet sometimes stops working

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34862]
Seen this a few times recently - using vscode and the git viewlet normally, then clicking on a file in the git viewlet no longer opens it.

Here, clicking on ndcg.test.ts doesn't do anything.

![sep-22-2017 16-05-16](https://user-images.githubusercontent.com/323878/30767258-01073e8a-9fb0-11e7-87ec-cff894497b93.gif)

It's always one particular file. No errors in the developer tools. Tell me where to debug next time if you've never seen it.

**Comment by joaomoreno** [comment]
If you reload, `ndcg.test.ts` does open? Was there anything in the devtools?

**Comment by roblourens** [comment]
Nothing in devtools. If I reload the window it starts working again.
