### ISSUE TITLE
Emmet still has incorrect expansion for some CSS abbrevations.

### ISSUE THREAD

**Issue by Niichie** [Microsoft/vscode#34866]
- VSCode Version: 1.17 Insiders, 1.16 Stable
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Launch VSC, open a CSS document.
2. Type bgc, which should expand to "background-color" but instead suggests "background-clip" first on the list.

Oddly enough using something like bgc# will still give you the correct emmet expansion.

It seems odd to suggest things like "widows" over more commonly used terms like "width" as well.

![2017-09-22_22-09-53](https://user-images.githubusercontent.com/16381287/30769202-d20672e4-9fe2-11e7-803e-0c687f729059.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Emmet suggestions get sorted alphabetically among other css suggestions.
In your case `background-clip` and `widows` are css completions not emmet.

To ensure emmet suggestion is the one that shows up as the first item in the list, you can set `emmet.showSuggestionsAsSnippets` to `true` and `editor.snippetSuggestions` to `top`. 

If you don't want snippets to show up at top for other languages then use the below
```
"emmet.showSuggestionsAsSnippets":  "true",
 "[css]":{
        "editor.snippetSuggestions": "top"
    }
```
