### ISSUE TITLE
i updated the vscode, the syntax is always shows error i am not able to format code correctly and even though the syntax is correct in any programming language the error is shown always the lint is not working

### ISSUE THREAD

**Issue by yuvaraj119** [Microsoft/vscode#34867]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

the HTML syntax highlight error:

`import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
    render() {
        return ( <
            div className = "App" >
            <
            div className = "App-header" >
            <
            img src = { logo }
            className = "App-logo"
            alt = "logo" / >
            <
            h2 > Welcome to React < /h2> <
            h3 > Hello World < /h3> < /
            div > <
            p className = "App-intro" >
            To get started, edit < code > src / App.js < /code> and save to reload. < /
            p > <
            /div>
        );
    }
}

export default App;`

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
react-toolbox-snippets|ale|0.12.0
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
ionic3-vs-ionView-snippets|dan|1.0.1
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
flow-for-vscode|flo|0.7.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
code-runner|for|0.7.1
ionic2-vscode|jgw|1.0.0
Angular2|joh|2.7.0
format-indent|Kas|1.3.0
ionic-extension-pack|loi|0.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
cpptools|ms-|0.12.4
jscs|ms-|0.1.9
debugger-for-chrome|msj|3.3.0
rxjs-snippets|pko|0.0.2
java|red|0.10.0
vscode-icons|rob|7.13.0
autoimport|ste|1.2.2
nativescript|Tel|0.7.2
ionic2|Tha|2.4.0
python|tht|0.2.3
Angular2|UVB|0.4.1
cordova-tools|vsm|1.2.12
vscode-react-native|vsm|0.4.2
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

Steps to Reproduce : 
1. Write a react native code
2. add html code in reactnative
3. See that the syntax doesn't recognise the open/close of html tag and reactnative

---

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
I just copy pasted your code and this is what I see:

<img width="698" alt="screen shot 2017-09-23 at 12 18 46 pm" src="https://user-images.githubusercontent.com/16890566/30776358-830df50a-a059-11e7-8bfd-0895c309a6e3.png">

Do you see the same?

If yes then the errors are valid. You cannot have `<` in one line and the tag name in the next.
Thats not valid html

**Comment by yuvaraj119** [comment]
yes the above shared screen shot which you shared i got the same error now i installed the 1.15 version of vscode its working correctly.

**Comment by ramya-rao-a** [comment]
I see the same error even in VS Code 1.15

**Comment by yuvaraj119** [comment]
I found the issue, it was due to one of the plugin due to which its not getting formatted properly,
@ramya-rao-a Thanks for your support. Its working in 1.16.1 too.
