### ISSUE TITLE
Multi-Cursor Modifier is not working with the Ctrl-key (but with Alt-Key)

### ISSUE THREAD

**Issue by bitdreamers** [Microsoft/vscode#34869]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
tabsanity|jed|0.0.9
vetur|oct|0.9.10
laravel-blade|one|1.9.0
advanced-new-file|pat|0.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Press Ctrl + left mouse button -> not working
2. Press Alt + left mouse button -> working

---

In the menu bar -> "Selection" it says "Switch to Ctrl+Click for..."

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@bitdreamers The multicursor modifier is out of the box set to `alt`.

It can be changed to be `ctrl` by configuring `"editor.multiCursorModifier": "ctrlCmd"` in user settings.

The menu `Selection > Switch to Ctrl+click for multi-cursor` means the current modifier is Alt and if you click on the menu item it will switch to use `ctrl`.

**Comment by bitdreamers** [comment]
@alexandrudima Thank you for the explanation. It makes perfect sense now.
