### ISSUE TITLE
Git: alert user that he needs to accept the xcode license, in order to use git

### ISSUE THREAD

**Issue by arggh** [Microsoft/vscode#34870]
Running on MacOS, I found a tiny glitch with the Source Control feature of VS Code.

Last night I updated Xcode, which also brings Git to MacOS. This morning I made a few changes to my project and went to the Source Control -tab in VS Code to review and commit, but there was no indication of any changes made whatsoever. Also, there wasn't any indication that something was wrong or required my attention.

I was rested well enough to immediately understand I probably have to accept the new Xcode license agreement before Git becomes usable again, but I wish VS Code would at least give me an indication that something is wrong and needs action to be taken.

### Expected

VS Code to let me know that `git` is not working for whatever reason

### What actually happened

I was wondering why my changes aren't shown in Source Control -tab (did I really already commit?!)

**Comment by joaomoreno** [comment]
Open a Terminal and run `git`.
