### ISSUE TITLE
search keybinding text resets

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#34873]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. search a keybinding in keyboard shortcut tab, like typing `delete` in text area.
2.go to another tab like task.json
3. go back to keyboard shortcuts tab, text area is empty. the `delete` keyword is not there.

vscode suppose to store the `delete` keyword and also the search result

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
Duplicate of #23543
