### ISSUE TITLE
Delete a word based on space separator

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#34874]
- VSCode Version: 1.16
- OS Version: Ubuntu 16

Steps to Reproduce:

1. place the cursor middle of a word. I can delete left half of the word or right half of the word but can not delete the complete word at once. like if I would like to delete a line i can do that from anywhere the cursor is on the line. but for word i would like to delete a word from anywhere the cursor is on the word.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@khaled-hossain-code The only workaround now is to select the word `ctrl+d` and delete it.

**Comment by usernamehw** [comment]
Is it solvable with [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros)?
`settings.json`
```json
"macros": {
    "deleteWholeWord": [
        "editor.action.addSelectionToNextFindMatch",
        "deleteRight"
    ]
}
```
`keybindings.json`
```json
{
    "key": "ctrl+shift+delete",
    "command": "macros.deleteWholeWord",
    "when": "editorTextFocus && !editorReadonly"
}
```

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
