### ISSUE TITLE
Emmet snippets don't appear in the middle of CSS-rules block (.css files)

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#34877]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

Emmet snippets disappear from the snippets list if you trying to type the CSS rule in the middle of the block.
It happens only in `.css` file.
In `.html ` file, in tag `<style> ... </style>` - everything is ok.

![emmet abbrs - middle](https://user-images.githubusercontent.com/24613274/30772746-db8868bc-a06a-11e7-80b2-dce347734e56.gif)

**Comment by user3323** [comment]
one more thing:

**op0.5**  -> should be `opacity: 0.5`

but Emmet doesn't want to put the snippet in the list

**Comment by ramya-rao-a** [comment]
Thanks for reporting @user3323!

The fixes for both the issues will be out in Monday's Insiders build

**Comment by user3323** [comment]
@ramya-rao-a 

> The fixes for both the issues will be out in Monday's Insiders build

today is Thursday already and there were no new builds...

**Comment by ramya-rao-a** [comment]
@user3323 

We are having some issues with getting signed bits out for the Insiders and so there hasnt been an Insiders update in a few days.

If you dont mind the unsigned bits then you can get it from:
https://az764295.vo.msecnd.net/insider/3831ef5e2ca82e7040cca4af44d76d064f9430a5/VSCode-darwin-insider-unsigned.zip

**Comment by ramya-rao-a** [comment]
@user3323 If you are on Windows, then new builds for Insiders are now out.
You should be able to update by restarting vs code

**Comment by user3323** [comment]
@ramya-rao-a, thanks for informing!

BTW, can you take a look at https://github.com/Microsoft/vscode/issues/35420 ?.. Cause bot didn't assign you to it.
