### ISSUE TITLE
can't run java on linux deepin 

### ISSUE THREAD

**Issue by Janindu077** [Microsoft/vscode#34883]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.9.0-deepin9-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
java-debug|DSn|0.0.2
lorem-ipsum|Tyr|1.0.0
html-snippets|abu|0.1.0
java-run|cao|1.1.4
plsql|cas|0.0.3
vscode-sql-connect|dvd|0.2.1
vscode-html-css|ecm|0.1.8
javac-linter|fau|1.2.6
vsc-lorem-cn|gal|1.0.2
js-atom-grammar|ms-|0.1.13
java|red|0.10.0
vscode-sql-beautify|sen|0.0.4
JavaScriptSnippets|xab|1.4.1
plsql-language|xyz|1.0.4

(8 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please provide details on the issue along with repro steps
