### ISSUE TITLE
Quick file finder ignores search.exclude setting

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#34880]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-docker|Pet|0.0.18
python|don|0.7.0
restructuredtext|lex|37.0.0
hg|mrc|1.1.7
language-gettext|mro|0.0.2
sass-indented|rob|1.4.2

---

Steps to Reproduce:

1. Edit `./.vscode/settings.json`.
2. Add `"search.exclude": {"./src": true, "./auto/addons": true}`.
3. Open quick file finder (Ctrl+P in my case).
4. Search for a file that could be matched under `/src`.
5. It matches! 
   ![captura de pantalla de 2017-09-23 17-42-15](https://user-images.githubusercontent.com/973709/30774660-ad2828c4-a086-11e7-8f0f-a9490a60e252.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You don't need `./` in those globs. `"src": true` will work.
