### ISSUE TITLE
Install button is not working

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#34881]
Clicking the install button in the web page for the marketplace has no effect.

- Chrome on macOS, Sierra

![2017-09-23_11-57-43](https://user-images.githubusercontent.com/1202528/30774805-931d6b72-a056-11e7-9101-6f655a9d44e0.gif)

**Comment by ramya-rao-a** [comment]
Just tried with chrome on Mac OS El Capitan and it works as expected.

Is the problem only with that one extension or all?
Can you repro using other browsers as well?
Can you try via incognito mode?

**Comment by ramya-rao-a** [comment]
Looks like @chrisdias saw something similar in #34405
