### ISSUE TITLE
terminal, exit code: 3221225786 when sending SIGINT

### ISSUE THREAD

**Issue by undefinederror** [Microsoft/vscode#34886]
- VSCode Version: 1.16.1 64bit
- OS Version: Windows 10 
![image](https://user-images.githubusercontent.com/8209966/30776084-5c6b4e42-a0a0-11e7-91da-73a4a4496b84.png)
![image](https://user-images.githubusercontent.com/8209966/30776090-815941aa-a0a0-11e7-846f-06542f9a00de.png)

Steps to Reproduce:

1. open a terminal
2. send SIGINT signal (CTRL + c)

Terminal crashes, "The terminal process terminated with exit code: 3221225786"

Reproduces without extensions: Yes

As a temporary workaround, is there any way to bind SIGINT to a different key combination?

Thank you

**Comment by TheColorRed** [comment]
I am having this issue too, I am not sure if it matters, but I am using `Git Bash` as my integrated terminal.

**Comment by undefinederror** [comment]
I confirm. If I remove the "terminal.integrated.shell.windows" override I don't get the same issue.
This only happens on 1 of the two machines I regularly use for development.
On the other one git bash works great.

I there any error log I can send? Where would I find it?

Thank you

**Comment by eps1lon** [comment]
>3221225786: The application terminated as a result of a CTRL+C 
> -- <cite>[Common program exit codes and error levels](http://www.febooti.com/products/automation-workshop/online-help/events/run-dos-cmd-command/exit-codes/) </cite>

I guess the sigint is not sent to the terminal but to the process that handles the terminal i.e. the terminal is being interrupted and not the process in the terminal if that makes any sense.

**Comment by PabTorre** [comment]
maybe there's a workaround using terminal.integrated.commandsToSkipShell?

**Comment by TheColorRed** [comment]
After the update, this issues seems to have been fixed on my computer.

**Comment by eps1lon** [comment]
Still experimenting this on 1.18.0.

**Comment by undefinederror** [comment]
I have now updated to VSCode 1.18.1 and git 2.15.0 and the issue is now gone.
I seem to recall from memory, that I had git 2.7 when the issue occurred.
I should have included the git version right in my opening post, my bad, I did not understand that it might have been related.

@eps1lon have you tried updating git?

**Comment by eps1lon** [comment]
I updated `2.6.4.windows.1` to latest stable `2.15.0.windows.1` which seems to have fixed the problem. Thanks @undefinederror

**Comment by TheColorRed** [comment]
I take back my previous comment. It isn't working anymore.  I will try to update git and see if that works like you guys are saying

**Comment by undefinederror** [comment]
@eps1lon glad it worked :)

**Comment by Tyriar** [comment]
Sound like you worked it out, fyi ctrl+c issues on Windows are all being tracked in https://github.com/Tyriar/node-pty/issues/7
