### ISSUE TITLE
Atom like hypertext ctrl+click typing

### ISSUE THREAD

**Issue by ErikDreyer** [Microsoft/vscode#34887]
Please add a feature found in atom, where you can ctrl+click on multiple places and then start typing, and then you will be able to type on all the clicked lines at the same time. This is the only thing stopping me from doing a full transition from Atom to VS Code

**Comment by alexandrudima** [comment]
@ErikDreyer This is possible out of the box with `alt+click`. If you would like to use `ctrl+click`, it is possible to switch to it from the `Selection > Switch to using ctrl+click for multi-cursor` or via settings `"editor.multiCursorModifier": "ctrlCmd"`
