### ISSUE TITLE
Git Bash terminal emulator `clear` doesn't work correctly

### ISSUE THREAD

**Issue by karpimpski** [Microsoft/vscode#34888]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

When using the Git Bash emulator, using the `clear` command doesn't clear the screen. The cursor moves back to the top of the terminal and I am able to type commands, but the previous text isn't cleared until I type over it.

Steps to Reproduce:
1. Use Git Bash emulator
2. Try to clear screen

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/33730
