### ISSUE TITLE
Because the color for my script are not showing on Visual Studio Code.

### ISSUE THREAD

**Issue by xSxnio** [Microsoft/vscode#34884]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.10.1
swap-word|dav|0.1.2
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
sublime-keybindings|ms-|2.9.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by xSxnio** [comment]
Because the color for my script are not showing on Visual Studio Code.

**Comment by ramya-rao-a** [comment]
Please provide screenshots and more details on the issue along with sample code

**Comment by xSxnio** [comment]
​
 Capture.PNG
<https://drive.google.com/file/d/0B_4ztm7IkzfLZUVmcjNEU25vNXM/view?usp=drive_web>
​See no color I need the color to see the mistake and if it's a JavaScript
or not. I'm am a youtuber with 110 subsciber I need it I do scripting and
gaming and How To's

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ramya-rao-a** [comment]
@xSxnio In your example the file doesnt have an extension and so VS Code will not know which language the file is.

On the bottom right, click on the "plain text" status bar item and choose the language from the resulting    options

@bpasero AutoDetect should work in such cases right?

**Comment by xSxnio** [comment]
Okay.

**Comment by bpasero** [comment]
@ramya-rao-a you mean in an untitled file? No, we never auto detect in that case, do you mean by checking for the contents?

**Comment by ramya-rao-a** [comment]
@bpasero Yes, in untitled file.

Looking at the code now, I see that auto detect works on the file name or the first line
And in this case since it is an untitled file, file name will not give anything.
And the first line isn't of much use here.

@xSxnio Closing this issue as you can get the language features by associating a language mode or by saving the file with the right extension
