### ISSUE TITLE
Garbled output on centos 7

### ISSUE THREAD

**Issue by d3x0r** [Microsoft/vscode#34882]
![garbled-vscode](https://user-images.githubusercontent.com/1909610/30774918-ee636742-a03e-11e7-83ec-983ac70b56eb.png)

Any clue how to fix this?

**Comment by ramya-rao-a** [comment]
That looks like the Welcome page.
Is the issue only with the Welcome page or all text documents?

Did this happen recently?

**Comment by d3x0r** [comment]
Found installing MS fonts worked to fix it....
http://help.accusoft.com/PCC/v8.1/HTML/How%20to%20Install%20Microsoft%20Fonts%20on%20Linux.html

**Comment by d3x0r** [comment]
And yes, it was just the welcome page... 
Chrome also had the same issue with its title bar and address bar; again, fixed with the first part of installing MS fonts.

**Comment by ramya-rao-a** [comment]
cc @chrmarti

**Comment by chrmarti** [comment]
@Tyriar Is this a known limitation?

**Comment by Tyriar** [comment]
Not known, didn't happen when I tried using vscode on CentOS. Looks to be a Chromium issue.

@d3x0r it was not just the welcome page though? The menu and tabs are broken as well?
