### ISSUE TITLE
Code is busy in doing something while open folder, the CPU and memory is going high, plugin do not work.

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#34896]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.1.0
code-runner|for|0.7.1
CppSnippets|har|0.0.12
cpp-pack|jew|0.0.2
Lua|key|0.0.9
ftp-sync|luk|0.3.3
cppcheck|mat|0.2.1
markdown-shortcuts|mdi|0.8.1
vscode-devskim|MS-|0.2.0
cpptools|ms-|0.12.4
PowerShell|ms-|1.4.3
team|ms-|1.122.0
node-tdd|pra|0.2.3
vscode-coverage-gutters|rya|1.1.3
text-marker|ryu|0.10.1
Align|ste|0.2.0
cmake-tools|vec|0.10.2
vscode-pclint|liw|0.1.0
c-cpp-snippets|wlh|0.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open a folder
2. open a js file
![image](https://user-images.githubusercontent.com/19996314/30778854-7136b38a-a112-11e7-948a-4ccaa3f8c6c3.png)

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
Can you reproduce this issue with extensions disabled? Try running `code --disable-extensions`

**Comment by p0d3r** [comment]
code helper on osx also now using more than 70% of cpu after new release. it even stuck and needed to restart the mac by holding power button...

**Comment by ramya-rao-a** [comment]
@p0d3r Can you repro it after running `code --disable-extensions`?

**Comment by liwangqian** [comment]
@ramya-rao-a 
I had try disable extensions, it cannot be reproduced, I mentioned in the issue description.

**Comment by liwangqian** [comment]
@ramya-rao-a 
This on my computer with extensions installed listed above，can be reproduced when I try to debug my extension after rerun the debugger.

Cannot you reproduce on you computer ?

**Comment by ramya-rao-a** [comment]
if you don't see the issue with extensions disabled, then this means one of the extension you have is causing the high CPU usage

Do you see the issue when working on certain files or all files?
