### ISSUE TITLE
Add julia language syntax highlighting to markdown editor code block

### ISSUE THREAD

**Issue by colinfang** [Microsoft/vscode#34891]
Can take the `tmLanguage` from https://github.com/JuliaEditorSupport/Julia.tmbundle/blob/696f630736669251a3cb56cb27741b5b07a4c093/Syntaxes/Julia.tmLanguage

Does markdown editor allow extensions to contribute to code block syntax highlighting for a specific language just like what markdown preview doess?

**Comment by mjbvz** [comment]
Extensions can contribute markdown fenced code block language support. Here's an example extension that does this: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example 

Let me know if you have any trouble getting this to work
