### ISSUE TITLE
Uninstall of 32-bit version didn't work.

### ISSUE THREAD

**Issue by JCBurnside** [Microsoft/vscode#34894]
- VSCode Version: N/A
- OS Version: win10

Steps to Reproduce:
Unsure

Reproduces without extensions: N/A

I am trying to upgrade to the 64-bit version but apparently some bits of the 32-bit version are left somewhere and I don't know where.

**Comment by ramya-rao-a** [comment]
What do you see the suggests that some bits of the 32-bit version are still lingering?

**Comment by JCBurnside** [comment]
When I run the install file for the 64-bit version it says I have to uninstall the 32-bit version.

**Comment by joaomoreno** [comment]
Can you try installing and uninstalling 32 bit again? Then try installing 64.

**Comment by JCBurnside** [comment]
In order to uninstall again I had to reinstall the latest 32-bit.  Otherwise it wouldn't show up on the windows installed programs list.  However this time it worked.  I don't know why 1.15 didn't uninstall correctly but it is fixed.
