### ISSUE TITLE
document.getWordRangeAtPosition works differently in a JSON file from a JS file

### ISSUE THREAD

**Issue by msafi** [Microsoft/vscode#34895]
I have this JSON file:

```json
{
  "dependencies": {
    "something": "^1.0.5"
  },
  "foo|": 1
}
```

And this JS file:

```js
const obj = {
  "dependencies": {
    "something": "^1.0.5"
  },
  "foo|": 1
}
```

The `|` above indicates cursor position.

As you can see, the cursor is in the same location relative to the JavaScript object. Now if I invoke `document.getWordRangeAtPosition(selection.end);`...

On the JSON file I get the following Range:

```js
[
  { "line": 4, "character": 2 },
  { "line": 4, "character": 7 }
]
```

...but on the JS file, I get the following Range:

```js
[
  { "line": 4, "character": 3 },
  { "line": 4, "character": 6 }
]
```

Why are the ranges different on a JSON and JS file?

**Comment by mjbvz** [comment]
@aeschli Looks like json's `wordPattern` is set to include quotes. I think the difference with JS is by-design then?

**Comment by aeschli** [comment]
Yes, it's intentionally. The language-specific word regexp is used e.g by intellisense or rename to evaluate the replace range. In JSON, you always want to replace the full key or property.  

Note that `getWordRangeAtPosition` takes a regexp as an optional argument, so you can tune that for your use case.
