### ISSUE TITLE
spawn EACCES is probably the most unhelpful error message 2nd only to error 5 reporting error 5

### ISSUE THREAD

**Issue by RyanNerd** [Microsoft/vscode#34899]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.11.0-041100-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
lua-debug|act|0.1.2
vscode-intelephense-client|bme|0.7.2
vsc-ember-frost|cie|0.0.2
php-debug|fel|1.11.1
vsc-ember-cli|fel|0.3.3
Lua|key|0.0.9
cpptools|ms-|0.12.4
csharp|ms-|1.12.1
EmberES6Snippets|pha|2.1.2

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Create a main.lua hello world program.
2. In the debugger attempt to lauch
Get the world's 2nd most obscure error message: `spawn EACCES `

Reproduces without extensions: No
Different error message: Configured debug type 'lua' is not supported.

**Comment by isidorn** [comment]
Please file this against the lua vscode extension, thank you
