### ISSUE TITLE
Unable to target CoreCLR from Visual Studio Code

### ISSUE THREAD

**Issue by TheBlueSky** [Microsoft/vscode#3489]
Hellp everyone,

I created a totally empty project and specified only CoreCLR as targetted framework; i.e., in `project.json` I have:

    "frameworks": {
        "dnxcore50": {}
    }

On my PC, the dnvm confirugration is the following:

    Active Version           Runtime Architecture OperatingSystem Alias
    ------ -------           ------- ------------ --------------- -----
           1.0.0-rc1-update1 clr     x64          win
           1.0.0-rc1-update1 clr     x86          win
      *    1.0.0-rc1-update1 coreclr x64          win             default
           1.0.0-rc1-update1 coreclr x86          win

Still, when I run the application I receive:

    System.InvalidOperationException: The current runtime target framework is not compatible with 'SomeProject'.
    Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
     Version:      1.0.0-rc1-16231
     Type:         Clr
     Architecture: x86
     OS Name:      Windows
     OS Version:   10.0
     Runtime Id:   win10-x86

    Please make sure the runtime matches a framework specified in project.json

Visual Studio Code is still "thinking" that it should run x86 CLR DNX and not the x64 CoreCLR one.

I'm not sure if this is a Visual Studio Code issue, or ASP.Net Core tooling issue; and appreciate any hint and help.

**Comment by TranscendOfSypherus** [comment]
I too am seeing this issue, if I launch a command window from the command pallet and invoke dnx web then kestrel launches fine against coreclr.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#88
