### ISSUE TITLE
Documentation view

### ISSUE THREAD

**Issue by qtbit** [Microsoft/vscode#34892]
Simply, I'd like to see documentation of a method and its parameters.

Webstorm has Documentation tooltip (Ctrl+Q). With the cursor on a method and pressing ctrl+q, it shows you all needed info about the method. VS Code currently shows just the autocomplete without documentation in "TypeScript definition" format which is hard to read.

![image](https://user-images.githubusercontent.com/25822015/30777778-fa8b06ae-a0c2-11e7-9d90-772e9ee667e2.png)

![image](https://user-images.githubusercontent.com/25822015/30777812-ff012906-a0c3-11e7-9dee-960476c19d41.png)

**Comment by mjbvz** [comment]
Can you please share the text source of this example?

For some of the individual issues:

1. We do not show the return type's documentation when you are completing a method. We only show the return type and the `@return` documentation. This is by-design. 
1. https://github.com/Microsoft/TypeScript/issues/15597 tracks the typedef being incorrectly replaced with with its definition in Intellisense 
1. The part about the signature not being colorized is tracked by #34188

**Comment by qtbit** [comment]
Sorry, I was out.
Here you are: [Book.txt](https://github.com/Microsoft/vscode/files/1374559/Book.txt)
 
Notice, it does not show you the method params documentation while you are writing the method name.
