### ISSUE TITLE
TypeScript syntax highlighting wrong after decorator

### ISSUE THREAD

**Issue by Ristaaf** [Microsoft/vscode#349]
When adding a decorator to a variable declaration i TypeScript, both public/private and the name of the variable is plain white, while if removing the decorator both are colored correctly.

**Comment by aeschli** [comment]
Reproduced with
   @MyAnnotation(1) private var foo = 'a';

Please add your example as well...

This needs to be filed against https://github.com/Microsoft/TypeScript.
