### ISSUE TITLE
connected variables can not be modified properly with snippet function

### ISSUE THREAD

**Issue by mkitby** [Microsoft/vscode#34904]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
arm|dan|0.1.2
python|don|0.7.0
cpptools|ms-|0.12.4
snippet-creator|nik|0.0.4
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Add the following snippet to c.json

```
"Header Include-Guard": {
    "prefix": "once",
    "body": [
        "#ifndef __${1:NAME}_H__\r",
        "#define __${1:NAME}_H__\r",
        "\r",
        "$0\r",
        "\r",
        "#endif /* __${1:NAME}_H__ */"
    ]
}
```

2. Create an c language file, and insert the snippet, then the cursor would be end of three NAME strings.  Press the Backspace key once, the first __NAME_H__will be changed to __, and the other two strings will be kept unchanged.

by the way, the issue is gone if I disable the vim extension.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
> Create an c language file, and insert the snippet, then the cursor would be end of three NAME strings. Delete the NAME string and enter new name.

And then?

**Comment by mkitby** [comment]
@jrieken, I already added more information.

**Comment by jrieken** [comment]
Yeah, our bot doesn't recognise modification to the summary // cc @chrmarti

**Comment by jrieken** [comment]
Please refine your steps as this doesn't reproduce for me

![oct-05-2017 13-01-30](https://user-images.githubusercontent.com/1794099/31224220-5572b874-a9cd-11e7-9df8-108fb64fe30e.gif)

**Comment by mkitby** [comment]
@jrieken 

As I said, the issue is gone if I disable the vim extension. So did you install vim extension?
![vscode_bug](https://user-images.githubusercontent.com/15389150/31266038-7f3d5cd6-aaa4-11e7-9752-c5f5d7ac573b.gif)

**Comment by jrieken** [comment]
> As I said, the issue is gone if I disable the vim extension. 

Sorry, I missed that. However, it also makes this an issue for VIM because the vim extension incepts *every* type event and it is its responsibility to send it back to the editor.

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#2157
