### ISSUE TITLE
Add support for intersecting decorators

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#34905]
Let's say I'm applying 2 decorators to the following string: `foo bar foo`, the first one changes the color of the whole string to green, the second makes `bar` red. With the current implementation the whole string will be green.

I think a better system would take into account the order in which decorators are applied. For instance if I apply the `red` decorator after the `green` one, it should take precedence and make `bar` red, while still keeping the rest green.

This kind of logic can already be implemented in an extension, but it seems low-level and general enough to deserve to be implemented in VSC itself.

What do you think?

**Comment by alexandrudima** [comment]
@fabiospampinato I agree. Our current recommendation is to ask everybody to use transparent colors.
