### ISSUE TITLE
Terminal window content, wordwrapped content is not suitable for "problemsMatcher" integration 

### ISSUE THREAD

**Issue by bisaga** [Microsoft/vscode#34908]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.2.0
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
debugger-for-chrome|msj|3.3.0

---
I have a problem with the multiline problemsMatcher and word wrapped results in the terminal console. 

When I integrate jasmine error reports to vscode "problems" tab and my vscode window is small, the reported error lines are cut at the visual width of the terminal window. Because multiline pattern matching works line by line, those wrapped lines doesn't contains whole information and  are not consistent any more with my pattern matching regex expressions. 

Is there any way to disable word wrapping in the terminal window or do you have any other workaround maybe ? 

I tested with two different terminals (Git Bash and win. PowerShell), because both have the same behavior I think the wrapping is at the vscode side ?   
  
Steps to Reproduce:

I describe whole integration between jasmine and vscode in [this blog article](http://bisaga.com/blog/programming/testing-typescript-node-app-with-jasmine/) 

1. create project with jasmine tests, run jasmine in the terminal successfully, then 
2. create task with the content: 
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "command": "run",
    "args": [],
    "tasks": [
        {
            "taskName": "test",
            "command": "node_modules/.bin/jasmine",
            "type": "shell",
            "isBackground": true,
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated"
            },
            "problemMatcher": {
                "owner": "javascript",
                "fileLocation": ["absolute"],
                "severity": "error",
                "pattern": [
                    {
                        "regexp": "Message.*"
                    },
                    {
                        "regexp": "[^ ](.*)",
                        "message": 1
                    },
                    {
                        "regexp": "Stack.*"
                    },
                    {
                        "regexp": "at +.*\\((.*\\\\*.ts):(\\d+):(\\d+)\\)",
                        "file": 1,
                        "line": 2,
                        "column": 3
                    }
                ]
            }
        }            
            
    ]
}
3. run the task with maximized size of the terminal window , pattern matcher does recognize errors and create problem in the problems tab
An error line (where the last regex pattern looks for file, line and column) looks like: 

`
        at UserContext.it (c:\Bisaga\Workspaces\learning\mytest\spec\myapi-spec.ts:16:32) 
`

4. run the task with very narrow size of the terminal window, pattern matcher does not recognize errors any more because the error line reported from the jasmine is now in 3 lines ...
An error line from jasmine is now in the 3 lines instead of the one : 

```
        at UserContext.it (c:\Bisaga\Worksp
aces\learning\mytest\spec\myapi-spec.ts:16:
32)
```

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/32042
