### ISSUE TITLE
VSCode does not identify fonts with special characters in it

### ISSUE THREAD

**Issue by aswinmohanme** [Microsoft/vscode#34907]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.0
vsc-material-theme|Equ|1.0.2
beautify|Hoo|1.1.1
vim|vsc|0.10.1
vscode-react-native|vsm|0.4.2

---

Steps to Reproduce:

1. Install Anka Coder Condensed Font 
2. Try to set the Font to 'Anka/Coder Condensed Font'  - https://fontlibrary.org/en/font/anka-coder-condensed
3. The font does not change

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@aswinmohanme Sometimes Chromium caches font information and we need to be restarted after installing a font.

Also, this is very sensitive to exact name matching. If the font name has spaces, you can use extra `'`s. i.e.

```
"editor.fontFamily": "'Arial Narrow'",
```

**Comment by aswinmohanme** [comment]
Adding a ' inside " seemed to fix the issue. Thanks
