### ISSUE TITLE
Save the splitted screens widths

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#3490]
It would be better if the widths of the splitted screens of the editor could be saved and restored.

It is always set to 50% when unsplitted / resplitted. I think a saved value would be more practical.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
