### ISSUE TITLE
Count in source control in side bar is wrong

### ISSUE THREAD

**Issue by hytromo** [Microsoft/vscode#34902]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: none
---

Steps to Reproduce: I don't know

Hitting the refresh button doesn't update the erroneous counter.

Screenshots: https://i.imgur.com/mjeQUR3.png https://i.imgur.com/UIeyAXf.png
It seems that the counter is always 1 higher than the real number
Restarting VSCode fixes the problem

**Comment by joaomoreno** [comment]
Interesting. What does `git status -u` return in the command line?
