### ISSUE TITLE
Emmet don't clear '<' when type <tag then press tab <<tag></tag>

### ISSUE THREAD

**Issue by gladx** [Microsoft/vscode#34906]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
code-settings-sync|Sha|2.8.3
quokka-vscode|Wal|1.0.66
html-snippets|abu|0.1.0
vscode-twig-pack|baj|1.0.0
vscode-intelephense-client|bme|0.7.2
phplt|cao|1.1.0
path-intellisense|chr|1.4.2
goto-documentation|cxf|0.0.1
vscode-html-css|ecm|0.1.8
prettier-vscode|esb|0.23.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.0
yii2-snippets|ima|0.0.9
Angular2|joh|2.7.0
php-cs-fixer|jun|0.1.43
php-symbols|lin|2.1.0
js-atom-grammar|ms-|0.1.13
php-docblocker|nei|1.2.0
advanced-new-file|pat|0.5.0
highlight-matching-tag|vin|0.4.4
twig|wha|1.0.2
JavaScriptSnippets|xab|1.4.1
vscode-pomodoro|yah|1.0.3

---

Steps to Reproduce:

1.when write any html tag for example start with <div
2. and  press tab to complete tag 
3- create `<<div></div>` :-( expected `<div> </div>` 

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
I can't repro...

![htmlemmet](https://user-images.githubusercontent.com/16890566/30793950-32cd2ecc-a17a-11e7-9ec3-d3501badb22a.gif)

Can you try again with extensions disabled to ensure none of the extensions are interfering? Run `code --disable-extensions`

**Comment by gladx** [comment]
![html](https://user-images.githubusercontent.com/9036557/30799788-e62b8fc0-a1ea-11e7-9f71-1334f231c9fb.gif)
run `code --disable-extensions ` in html document
![php](https://user-images.githubusercontent.com/9036557/30799912-3e2ba606-a1eb-11e7-8605-7c40ac231ff5.gif)
and in php document 

[Code.mkv.zip](https://github.com/Microsoft/vscode/files/1328819/Code.mkv.zip)
a screen cast show problem code.mkv

**Comment by yume-chan** [comment]
I can reproduce this in both 1.16.1 and 1.17-insiders.

Press <kbd><</kbd> <kbd>a</kbd> <kbd>Backspace</kbd> <kbd>a</kbd> <kbd>Enter</kbd> in a HTML file.

**Comment by ramya-rao-a** [comment]
Thanks @gladx and @yume-chan I can repro now.

Pushed a fix to not show emmet in completions when what is typed is an open tag

Note to verifiers
- Type `<html` or `<` any html tag
- Delete last char and type it again to trigger emmet completions or press ESC and manually trigger suggestions by `Ctrl+Space`
- No emmet suggestions should appear
