### ISSUE TITLE
How to remove automatically added ";" from "Extract function"

### ISSUE THREAD

**Issue by davedmarketing** [Microsoft/vscode#34911]
- VSCode Version: (1.16.1)
- OS Version: OSX 10.11.6

Steps to Reproduce: 

When I use "Extract function" it automatically adds ";". I don't use ";" when writing javascript except for inline "line breaks" or in front of self-executing functions so this causes a discrepancy.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18780
