### ISSUE TITLE
Module resolution displays incorrectly in a certain case

### ISSUE THREAD

**Issue by EagleLizard** [Microsoft/vscode#34916]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. When using the `import` syntax in JS and TypeScript, VSCode doesn't display the types filename correctly.

Given the file hierarchy:
<img width="208" alt="screen shot 2017-09-24 at 6 08 10 pm" src="https://user-images.githubusercontent.com/4955582/30788090-85aed14e-a153-11e7-806b-80c034495462.png">

The file `main.ts` contains the code:
```typescript


import Rect from './shape/Rect';
import Fill from './fill/Fill';

main();

function main(){
  let startRect = new Rect(20, 20);
  let matrix = startRect.render(true);
  Fill.getPoints(matrix);
}

```

The compiled javascript file also displays the error:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Rect_1 = require("./shape/Rect");
const Fill_1 = require("./fill/Fill");
main();
function main() {
  let startRect = new Rect_1.default(20, 20);
  let matrix = startRect.render(true);
  Fill.getPoints(matrix);
}
```

**Inside of VSCode** the file renders `'./fill/Fill'` as `'./filFill'`.

The filepath still resolves correctly and the missing `l/` characters are still deletable (nothing happens on-delete, they act as invisible characters

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Where is the text being incorrectly rendered? Can you please provide a screenshot of the issue

**Comment by EagleLizard** [comment]
@mjbvz see screenshot attached below, with the problem lines highlighted in green boxes. 

Both the source Typescript and compiled JS are pictured (opened with `--disable-extensions` flag). The compiled JS is now in the `./out` directory, however the problem is reproducible without specifying `outDir` in `tsconfig.json`.

<img width="1358" alt="screen shot 2017-09-25 at 1 41 31 pm" src="https://user-images.githubusercontent.com/4955582/30827662-201253ce-a1f8-11e7-91de-650ea245211b.png">

Note that the bug appears to be purely visual, if I copy and paste the entire string into another program's text input the string renders correctly as `"./fill/Fill"`.

**Comment by mjbvz** [comment]
Weird. Are you using a custom font? Can you temporarily try removing all of your user settings to see if any of those may be causing this.

**Comment by EagleLizard** [comment]
@mjbvz I am using a custom font. Disabling all of my settings fixed the issue:
<img width="1414" alt="screen shot 2017-09-25 at 5 18 57 pm" src="https://user-images.githubusercontent.com/4955582/30835622-4559329c-a216-11e7-93e2-8683fa290996.png">

It seems to be a problem with the `profont` font in MacOS (src: http://tobiasjung.name/profont/):
<img width="1411" alt="screen shot 2017-09-25 at 5 18 43 pm" src="https://user-images.githubusercontent.com/4955582/30835640-6fdd7dc0-a216-11e7-9080-e0db35c29167.png">

I was able to find an alternative to `profont` that works called `profontx` (src: http://faisal.com/software/profontx/)
<img width="1408" alt="screen shot 2017-09-25 at 5 19 22 pm" src="https://user-images.githubusercontent.com/4955582/30835677-9f87aa1e-a216-11e7-9857-c7a387e63878.png">


The source website for `profontx` says something about the original `profont` having "ligatures which make the font less useful in Cocoa apps under Mac OS X". Perhaps that is causing the issue?

`profontx` looks close enough to the original that it works for me. I still see this as a bug, the behavior was odd and the path to discovery on how to fix it wasn't clear (or standard across other fonts).

**Comment by mjbvz** [comment]
Yes is seems some of the ligatures are causing problems, specifically one for `l/`

@alexandrudima Can you please take a look? I could repo this on MacOS by installing `ProFont Distribution 2.2` from  http://tobiasjung.name/profont/ Minimal repo string: `l/`

**Comment by alexandrudima** [comment]
Sure, ligatures can do that. It is difficult for me to speculate if this is a bug with the font or a bug with Chromium's font rendering. The best perhaps is to open an issue against Chromium at https://bugs.chromium.org/p/chromium/issues/list , and ask them for guidance. (VSCode is built with Electron which uses Chromium and we use Chromium for font rendering in the editor).

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
