### ISSUE TITLE
Insiders: Stop debugging doesn't stop the node process

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#34917]
Mac
Insiders 1.17.0 f7962f0682a76516df51de4856f8ccc5d8ad578a

scaffold a new express app

``` console
express myexpapp
cd myexpapp && npm install
code-insiders .
```

Generate `launch.json` by clicking on the gear in the debug viewlet, looks like this:

``` json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/bin/www"
        }
    ]
}
```

`F5` to start/debug the app
browse to `localhost:3000`
stop the debugger
`F5` again

result: port 3000 is in use

the node process is still running:

``` console
chris            75258   0.0  0.5  3686816  78276   ??  S     8:43PM   0:01.00 /usr/local/bin/node --debug-brk=45606 --nolazy bin/www
```

So, you can only debug once.

**Comment by chrisdias** [comment]
``` console
node --version
v6.11.2
```

I added `"protocol": "inspector"` to `launch.json` and it works properly.  Since node is 6.* I would expect the opposite behavior?  Regardless, the "out of the box" experience seems broken.

**Comment by auchenberg** [comment]
@roblourens This works in Version 1.16.1 (1.16.1), so we have changed something recently.

**Comment by weinand** [comment]
Accidentally a Windows line ending crept into the macOS/linux script that is used to terminate the node.js process. This made the script fail.
