### ISSUE TITLE
Allow editing shortcuts that include mouse buttons

### ISSUE THREAD

**Issue by lucasv1179** [Microsoft/vscode#3491]
There's a particularly annoying limitation in Ubuntu where the "alt+LMB" combination is already reserved by the system which impedes the placing of multiple cursors in the program with said shortcut. Might you consider changing the shortcut or allowing users to change it themselves?

**Comment by Tyriar** [comment]
Allowing customization of mouse actions is part of https://github.com/Microsoft/vscode/issues/3130

As for <kbd>alt</kbd>+click, that's captured in https://github.com/Microsoft/vscode/issues/3091
