### ISSUE TITLE
Broken fuzzy search algorithm in picker

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#34914]
The fuzzy search algorithm can be improved to solve all problems listed in #27317, but IMHO it's completely broken and it should be rewritten from scratch. Let me show you some of the errors I've found:

### Doesn't work with leading spaces

This is the expected behavior:

![ok_todop](https://user-images.githubusercontent.com/1812093/30786853-bf457bbe-a17c-11e7-8ec2-aa033d618db4.gif)

This is what happens if the strings have some leading spaces (useful for extensions like [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus) for showing a tree-like structure):

![broken_todop](https://user-images.githubusercontent.com/1812093/30786852-bf3df376-a17c-11e7-873e-8ecfc9c97465.gif)

### Not really "fuzzy"

As I understand it, the term "fuzzy" in "fuzzy search" basically means that the characters provided in the search query can have 0 or more other arbitrary characters between them in the matching string. The current algorithm looks like regular search instead:

![broken_fuzzy](https://user-images.githubusercontent.com/1812093/30786850-bf2daa20-a17c-11e7-8b45-0ce237e75cbe.gif)

### Overly strict about string position

For some reasons there are strings that match against some queries, but don't mach against less specific versions of those queries. I mean, a more specific query should provide the same or less results, not more, right?

![broken_start](https://user-images.githubusercontent.com/1812093/30786851-bf370bba-a17c-11e7-9b5d-3154847c59b4.gif)

**Comment by bpasero** [comment]
@fabiospampinato some of this can be explained by the fact that fuzzy search is NOT enabled for the normal picker (see #34088). Currently we have it only enabled for the file search because it still needs to be tweaked. I need to check for the leading whitespace issue but it may be related to the same cause.

**Comment by bpasero** [comment]
@fabiospampinato trying to reproduce the issue with leading white space but I cannot:

![panel-red](https://user-images.githubusercontent.com/900690/31046974-973c8a56-a602-11e7-83ac-162347388a1e.gif)

Is there any way I could try it on the code that you used for your animation to reproduce the same?

**Comment by fabiospampinato** [comment]
@bpasero Try prefixing those strings with exactly 8 spaces. For whatever reason the bug doesn't manifest itself with just 4 spaces in my system.

If it doesn't work, install [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus), run `Projects: Edit Configuration` and paste this:
```json
{
  "groups": [
    {
      "name": "open",
      "groups": [
        {
          "name": "vscode",
          "projects": [
            {
              "name": "vscode-projects-plus-todo-plus",
              "path": "/"
            },
            {
              "name": "vscode-todo-plus",
              "path": "/"
            }
          ]
        }
      ]
    }
  ]
}
```
Then run `Project: Open`  and try it again.

It would be weird if it still doesn't work.

**Comment by bpasero** [comment]
@fabiospampinato thanks, I can reproduce now.

**Comment by fabiospampinato** [comment]
@bpasero Here there's another bug, in the following gif I hit `down` 2 times and then `up` 2 times and nothing gets selected instead of selecting the last item:

![2017-11-09 16_54_49](https://user-images.githubusercontent.com/1812093/32614983-c45e6eec-c56e-11e7-90f1-6c90ec0068da.gif)

When will this bugs be resolved?

**Comment by bpasero** [comment]
@joaomoreno I think that one is fixed already in our latest insider build, can you check

**Comment by fabiospampinato** [comment]
@bpasero It's fixed. Thank you.
