### ISSUE TITLE
Emmet Tab Expansion not working

### ISSUE THREAD

**Issue by selrond** [Microsoft/vscode#34929]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.0
vsc-material-theme|Equ|1.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.2.0
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.23.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
sublime-babel-vscode|jos|0.2.9
vscode-styled-components|jpo|0.0.8
sublime-keybindings|ms-|2.9.1
color-highlight|nau|2.3.0
vscode-versionlens|pfl|0.19.1
vscode-import-cost|wix|2.5.0

(1 theme extensions excluded)

---

Coming from #32243 Tab Expansion (Expand Abbreviation) still not working for me.
My Emmet-related settings:

```json
{
	"emmet.includeLanguages": {
		"javascript": "javascriptreact",
		"jsx-sublime-babel-tags": "javascriptreact"
	},
	"emmet.triggerExpansionOnTab": true
}
```

It _does_ work, however, when invoking `Emmet: Expand Abbreviation` as well as when using the shortcut. 

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Do you have any custom keybindings that might be using the tab key?

**Comment by selrond** [comment]
@ramya-rao-a I've checked my `keybindings.json` and found a [removal rule](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule)

```json
{
	"key": "tab",
	"command": "-editor.emmet.action.expandAbbreviation",
	"when":
		"config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus"
}
```

IDK how it got there though 😁
Deleted that, it now works as expected! Thanks.

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
