### ISSUE TITLE
Cannot exit VS Code

### ISSUE THREAD

**Issue by goooxu** [Microsoft/vscode#34924]
- VSCode Version: Both 1.16.1 and 1.17.0-insider (64bit)
- NodeJS Version: v8.4.0
- NPM Version: 5.3.0
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Open Terminal
2. Run code . ( currently folder is a VSCode extension project )
3. Start debugging then stop
3. Try to quit VSCode with following approaches but without any effect
   1. File menu -> Exit button
   2. Close button on top right
   3. Close window menu by right click docker icon
   4. Alt+F4
4. Also try to close folder but without any effect

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@goooxu you try to quit the application that shows the debug tool bar, not the window that opens that hosts your extension right?

**Comment by goooxu** [comment]
@bpasero Yes, actually I already exited the debugging, so there is only one VSCode window.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by goooxu** [comment]
@bpasero I followed your approach and got the below messages,

The `code --verbose` only outputs the 2 lines echo time I clicked the close button
```
[main 1:58:59 PM] Lifecycle#window-before-close 1
[main 1:58:59 PM] Lifecycle#unload() 1
```
And the Console in Developer Tools didn't output anything.

But I found another rule, if I made the below change in package.json file of extension project,
```
- "compile": "tsc -watch -p ./",
+ "compile": "tsc - p ./",
```
The issue doesn't repro anymore.

**Comment by bpasero** [comment]
@goooxu can you come up with some exact steps that reliably reproduce this issue for you? It seems to me that it involves starting to debug and then stop and then trying to quit? Maybe you could give me a list to reproduce.

**Comment by goooxu** [comment]
@bpasero the simplest reproduce steps are as below:

1. use `yo code` to create an default vscode extension project
2. `cd` to folder and `code .`
3. press F5 to start debugging
4. close the extension development host vscode, then debugging is stopped
5. try to close the first vscode, then the issue reproduced.

**Comment by bpasero** [comment]
Cannot really reproduce, tried this:

![panel-red](https://user-images.githubusercontent.com/900690/30871720-0df8df14-a2e8-11e7-9b1f-3e8cb5651a67.gif)

You doing anything differently?
