### ISSUE TITLE
Cant install extensions. Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Diyago** [Microsoft/vscode#3492]
I cant any install extension, VS Code keep saying me that _he unable to get local issuer certificate_.

VS Code've been downloaded from [here ](https://go.microsoft.com/fwlink/?LinkID=623231) and installed from that zip file (simply unzipped, not to Program files folder due to admin restriction policy). 

Version 0.10.8, Windows 7, 32 bit

**Comment by joaomoreno** [comment]
You seem to be behind a proxy. There are a couple of settings that may be useful to you:

```
    //-------- HTTP configuration --------

    // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
    "http.proxy": "",

    // Whether the proxy server certificate should be verified against the list of supplied CAs.
    "http.proxyStrictSSL": true,
```
