### ISSUE TITLE
[suggestion] How about support Browser-Server, without electron?

### ISSUE THREAD

**Issue by hxsf** [Microsoft/vscode#34923]
Hi.

some reason of this:
- the ENVs of DEV and PROD are different. (like using a macOS to make a Linux program.)
- want code any where.(install vscode at server, use browser to connect to it and code)
- more than one developer can attach a same vscode instance to review code or do pair programming, or attach different instance to do something alone.

**Comment by isidorn** [comment]
We probably already have requests like this in our repository, please search olders issues for more details.
However I can answer shortly, currently our whole vscode architecture is built on top of electron and we do not plan to change that.
However the monaco editor is not dependendt on the server https://github.com/Microsoft/monaco-editor
