### ISSUE TITLE
Quotation marks around absolute path contains spaces in tasks.json

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#34922]
- VSCode Version: 1.16.1
- OS Version: Windows 10, Version 1703, OS Build 15063.608

Steps to Reproduce:

1. Create project with tasks.json, and input absolute path contains spaces with quotes as args

In Windows 10, double quotes around absolute path contains spaces do not work, but apostrophe works

However, it is just the opposite in Windows 7/8.

Reproduces without extensions: Yes

[tasks.json](https://github.com/Microsoft/vscode/files/1328186/tasks.zip)

Reference: 

https://github.com/Microsoft/devkit-sdk/issues/585

**Comment by dbaeumer** [comment]
The problem is that in Windows 10 we use PowerShell as the default shell but under Windows 7/8 cmd.exe,

However if you switch to task version 2.0.0 you can nicely control the shell to use to run the commands making it the same on Windows 10 and 7/8/

Something like:

```
	"tasks": [
		{
			"type": "shell",
			"taskName": "...
			"command": "..."
			"options": {
				"shell": {
					"executable": "...\\cmd.exe",
					"args": [
						"/d", "/c"
					]
				}
			}
		}

```

**Comment by Sneezry** [comment]
Thanks for the information!
