### ISSUE TITLE
VSCode C/C++ Extension(ms-vscode.cpptools) can be cached?

### ISSUE THREAD

**Issue by diigu** [Microsoft/vscode#34925]
As my usage, I usually open 2 or more Linux Kernel Source projects in vscode, it's very huge.
When I open vscode, ms-vscode.cpptools will auto start preparation of C/C++ IntelliSense, such as symbol search ing, goto defination and so on.
But as I say, the project of kernel source code is very huge and ms-vscode.cpptools will take a lot of time to finish. Every time I open vscode, this preparation job will run again and take a lot of time.
I'm thinking that ms-vscode.cpptools should add cache support for a project.

**Comment by ramya-rao-a** [comment]
@diigu Please log this issue in the repo for the ms-vscode.cpptools extension
