### ISSUE TITLE
Need a flag to know if an extension is adopted to MR workspace or not

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#34937]
We would need this flag to know if we could copy those settings contributed by an extension while transitioning from a Folder window to Workspace window.

More details here - https://github.com/Microsoft/vscode/issues/33670

**Comment by bpasero** [comment]
@sandy081 isn't that just a matter of checking for each setting if the setting is contributed on the `window` vs `resource` scope? Why is the flag needed?

**Comment by sandy081** [comment]
Its because of the issue #33670. We make an assumption that by default all settings are `window` scoped. This includes also settings which are not adopted / classified yet. So, when we transition from single folder to a workspace, we copy all these window settings. This might be not intended in case of non adopted extensions if they have a resource scoped setting which is not classified, e.g., `typescript.sdk`. So for now, I am migrating only vscode internal settings. 

We can either remove this restriction once we make MR stable or we can derive some check on an extension to know if it is MR aware or not

**Comment by bpasero** [comment]
@sandy081 I think if an extension adopts the resource scope the extension should also declare the setting properly. So if we then wrongly copy over the setting because of that, the extension should fix it.

But yeah, I am fine waiting until we make this stable before migrating extension settings.

**Comment by sandy081** [comment]
@bpasero I completely agree with adopted extensions to mark the settings correctly. But the issue is more about non-adopted ones. IMO it is not good to migrate settings for these.

Also 👍 for waiting until stable.

**Comment by bpasero** [comment]
@sandy081 as far as I know we solve this by adding a new category for extensions, @seanmcbreen drives this.

**Comment by sandy081** [comment]
Today's insiders do not have fix for migrating in built extensions configurations. For built-in extensions, please wait for next insiders.

**Comment by sandy081** [comment]
To verify:

Create a sample extension that defines resource and window scoped settings. You can use https://github.com/Microsoft/vscode-extension-samples/tree/master/configuration-sample

- Open a Folder in VS Code that has following in Workspace settings
 - Core window setting (say window.zoomLevel)
 - Core resource setting (say editor.fontSize)
 - In built extension window setting (say git.enabled)
 - In built extension resource setting (say typescript.quickSuggestionsForPaths)
 - Above extension's window setting 
 - Above extension's resource setting 

- Add a folder now.

Make sure all Window settings are migrated to workspace leaving out resource settings.
