### ISSUE TITLE
Selecting Tag Suggestions Results In Double Opening Chevrons (eg <<html></html>)

### ISSUE THREAD

**Issue by DannyMexen** [Microsoft/vscode#34932]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: none
---

Steps to Reproduce:

1. Type '<'
2. Select any of the suggested tags

**Comment by yume-chan** [comment]
Duplicate of #34906

**Comment by ramya-rao-a** [comment]
Thanks @yume-chan 

Closing as duplicate
