### ISSUE TITLE
September Endgame

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34939]
## Endgame Schedule
- *September 25*, Code freeze for the endgame
- *October 1*, Endgame done

#### Monday, September 25
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items are created (with "complexity" but not necessarily with full description) by 11pm ZRH time (2pm PT)
- [x] All test items contain comprehensive test descriptions by 10pm PT
- Testers who cannot participate in testing check-off from list below:
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @auchenberg
  - [x] @bpasero
  - [ ] @chrisdias
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [ ] @rebornix
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @seanmcbreen
  - [ ] @tyriar
  - [x] @weinand

#### Tuesday, September 26
- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A"September+2017") assigned
- [x] [All closed feature-requests either have a verification-needed or on-testplan tag](https://github.com/Microsoft/vscode/issues?q=label%3Afeature-request+-label%3Aon-testplan+-label%3Averification-needed+-label%3Aduplicate+milestone%3A%22September+2017%22+is%3Aclosed)
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

#### Wednesday, September 27
- [x] Remind team members to assign issues that they intend to fix to the September milestone
- [x] Testing
- [x] [Fixing](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2017%22+label%3Abug) (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22September+2017%22)

#### Thursday, September 28
- [x] [Fixing last issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2017%22+label%3Abug)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22September+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
  - do not forget to update the `distro` attribute in the package.json with the commit ID of the distro repo.
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**

#### Friday, September 29
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [ ] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node-debugadapter-node **@weinand**
  - [x] node-debug **@weinand**
  - [ ] node-debug2 **@roblourens**
- [x] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) @dbaeumer
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @isidorn 
  - [x] OS X - @jrieken
  - [x] Linux - @bpasero 
- [ ] All release notes updated - release notes are collected in a file named *`v1_17.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @octref
  - [x] @rebornix
  - [ ] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @mjbvz
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [ ] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-filewatcher-windows **@bpasero**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [ ] vscode-textmate **@alexandrudima**
  - [ ] vscode-loader **@alexandrudima**
  - [ ] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [ ] vscode-css-languageservice **@aeschli**
  - [ ] vscode-json-languageservice **@aeschli**
  - [ ] vscode-html-languageservice **@aeschli**
  - [ ] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [ ] vscode-jshint **@kieferrm**
  - [ ] vscode-recipes **@auchenberg**
  - [ ] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [ ] Trigger new insider build and publish it manually **@owner**

##### Friday/Monday
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@redmond**

##### Monday - Wednesday
- [x] Polish release notes **@redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@owner**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [ ] Documentation updated
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [ ] @octref
  - [ ] @rebornix
  - [ ] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @mjbvz

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Thursday/Friday
- [x] Merge translations **@zurich**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request @chrmarti
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@owner**
    - [x] zip **@owner**
  - [x] OS X - **@owner**
  - [x] Linux
    - [x] deb package 64-bit **@owner**
    - [x] deb package 32-bit **@owner**
    - [x] rpm package 64-bit **@owner**
    - [x] rpm package 32-bit **@owner**
    - [x] archives **@owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@owner**
- [ ] Publish deb and rpms to repositories manually @chrmarti
- [x] Add version with symbols to HockeyApp @Tyriar 
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen**

**Comment by FredrikFolkesson** [comment]
Should this issue not be closed? @jrieken

**Comment by jrieken** [comment]
Yeah
