### ISSUE TITLE
Full screen / Zen mode window flickering

### ISSUE THREAD

**Issue by mikaelkundert** [microsoft/vscode#34934]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic (Ubuntu Gnome 16.04)
- Using touchpad mouse in X1 Carbon laptop
- Extensions: (disabled)

Extension|Author (truncated)|Version
---|---|---
crane|Hvy|0.3.8
php-namespace-resolver|Meh|0.7.6
vscode-docker|Pet|0.0.18
vscode-intelephense-client|bme|0.7.2
vscode-eslint|dba|1.3.2
vscode-instant-markdown|dba|1.3.0
drupal-8-snippets|dss|0.0.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
rest-client|hum|0.15.2
drupal-7-snippets|jun|0.0.7
Go|luk|0.6.65
VS-code-drupal|mar|0.0.12
drupal7-hooks-snippets|pau|0.0.2

While in Full screen mode or Zen mode, the window disappear/flickers for couple milliseconds (making other background windows visible) 3-6 times per minute. Especially when scrolling or moving the mouse.

---

Steps to Reproduce:

1. Launch the IDE without extensions
2. Open some files
3. Go to Full screen mode or Zen mode
4. Scroll and browse files from sidebar
5. Scroll opened files

Unxpected result: The code's window disappears for very short time (1-10ms) when having mouse activity.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Does it reproduce via `code --disable-gpu` from the command line?

**Comment by mikaelkundert** [comment]
My current version seems not to have this problem anymore.
```
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by mikaelkundert** [comment]
Sorry, I have to say that the problem still occurs. However, I was not able so far to detect this problem when using with `--disable-gpu`.

**Comment by mikaelkundert** [comment]
Do I have to re-report this to get this issue opened? I totally missed the question and couldn't react in time. @bpasero

**Comment by gamezinfantes** [comment]
It still happens I have the same problem in full screen on windows 10. --disable-gpu solves the problem.

**Comment by jazieltan** [comment]
#41513

**Comment by jazieltan** [comment]
#41513
