### ISSUE TITLE
[PHP] Static Class Highlighting

### ISSUE THREAD

**Issue by Helfull** [Microsoft/vscode#34931]
- VSCode Version: 1.17.0-insider
- OS Version: Windows 10 Pro (1703)

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/720645/30796697-7bbf66d2-a1d3-11e7-8475-3fa3fccfd8b8.png)

The `StaticClass` call should have the same Highlighting as the `use` Class name, but the scopes are totally different
![image](https://user-images.githubusercontent.com/720645/30796716-9bdefd10-a1d3-11e7-8c83-6acde42f6e0a.png)
![image](https://user-images.githubusercontent.com/720645/30796722-a0b7deec-a1d3-11e7-982f-5ed5a0c742af.png)
Also the scopes for the namespace separators are wrong
![image](https://user-images.githubusercontent.com/720645/30796753-b66b44cc-a1d3-11e7-87cd-4cd2a1694bea.png)
![image](https://user-images.githubusercontent.com/720645/30796759-bd0de30c-a1d3-11e7-8350-16e3abe423c0.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Maybe related to https://github.com/Microsoft/vscode-textmate/issues/50. Works in Atom

**Comment by roblourens** [comment]
This was fixed by one of the grammar updates

**Comment by mjbvz** [comment]
@roblourens For the code:

```
<?php

use NonStaticClass\Something;
\StaticClass:foobar();
```

The only difference I see from the original bug report is that `StaticClass` now has `constant.other.php`:

![screen shot 2017-10-31 at 5 39 31 pm](https://user-images.githubusercontent.com/12821956/32255069-7f5cfea2-be62-11e7-8bdb-6dc684e76ebf.png)

**Comment by roblourens** [comment]
Two colons :)

![image](https://user-images.githubusercontent.com/323878/32255127-0c7c9dd8-be63-11e7-9f13-80cff77e2b8c.png)

Fun fact, in PHP this operator is called the `Paamayim Nekudotayim`

**Comment by mjbvz** [comment]
Thanks! Verified that works
