### ISSUE TITLE
Icon on Taskbar can't be shown correctly

### ISSUE THREAD

**Issue by Blazero** [Microsoft/vscode#34930]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.3.0
python|don|0.7.0
cpptools|ms-|0.12.4
java|red|0.10.0
vscode-icons|rob|7.13.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@Blazero Can you please be specific about what icon and where ? Screenshots would be very much helpful.

**Comment by Blazero** [comment]
Of course. As I said, the icon on Taskbar.

[cid:image002.png@01D336EE.1ED55490]

The one in red circle is VSCode, it was not shown correctly.

Thank you for your time.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bpasero** [comment]
@Blazero looks like the screenshot is not coming through?

**Comment by Blazero** [comment]
I’ll send you a new picture. In case you can’t see it, I also add it as an attachment.

[cid:image003.jpg@01D33795.00331980]

This problem happened after I uninstall 32-bit VSCode and install the 64-bit one.
And the VSCode has been auto-updated for some times after installed, this problem still exists.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chrisdias** [comment]
@Blazero I still don't see the image. Please reply in github, not through email.

**Comment by Blazero** [comment]
I've re-installed VSCode and it's solved. Thanks.
