### ISSUE TITLE
Programs starting with underscore makes its path to be merged with previous directry

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#34949]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
danielo-node-snippets|dan|1.0.3
markdown-table-prettify|dar|1.1.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.2.0
EditorConfig|Edi|0.10.1
vscode-npm-script|eg2|0.2.1
auto-close-tag|for|0.5.0
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
JSDocTagComplete|Hoo|0.0.2
badges|idl|1.0.7
sublime-babel-vscode|jos|0.2.9
vscode-github|Kni|0.19.0
vue|liu|0.1.5
lit-it|moh|1.2.12
debugger-for-chrome|msj|3.3.0
vetur|oct|0.9.10
vuehelper|oys|0.1.0
vscode-docker|Pet|0.0.18
material-icon-theme|PKi|2.2.1
vscode-icons|rob|7.13.0
code-settings-sync|Sha|2.8.3
code-spell-checker|str|1.4.0
vscode-react-redux-snippets|tha|0.3.3
quokka-vscode|Wal|1.0.66
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Try to debug a program that has underscore as first parameter. Something like this
```js
{
            "name": "Run mocha",
            "request": "launch",
            "type": "node",
            "program": "${workspaceRoot}\\node_modules\\.bin\\_mocha",
            // Automatically stop program after launch.
            "stopOnEntry": false,
            // Command line arguments passed to the program.
            "args": [
                "-b",
                "--recursive",
                "build/test/"
            ],
            "cwd": "${workspaceRoot}",
            // Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
            "runtimeExecutable": null,
            // Environment variables passed to the program.
            "env": {
                "NODE_ENV": "test"
            }
        }
```
2. See how the pat becomes `node_modules/.bin_mocha` instead of `node_modules/.bin/_mocha`

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34541
