### ISSUE TITLE
font setting

### ISSUE THREAD

**Issue by YanYuanFE** [Microsoft/vscode#34945]
- VSCode Version:1.16
- OS Version:Ubuntu16.04

Steps to Reproduce:

1.font of my code is different

Reproduces without extensions: Yes/No
![_040](https://user-images.githubusercontent.com/17774285/30802788-3b2092d0-a21a-11e7-817d-e2adfc1a907f.png)

**Comment by alexandrudima** [comment]
@YanYuanFE I'm sorry I don't know exactly what you mean? Did you update Ubuntu or did something like deleting fonts. You can change the font family via `editor.fontFamily`

**Comment by YanYuanFE** [comment]
I attempt to change the  font family via _editor.fontFamily_ to Source Code Pro, but it's bad, as,follow, I also uninstall vscode and reinstall，but not success。I sure install a font of Source Code Pro。
![_041](https://user-images.githubusercontent.com/17774285/30839712-38b23396-a2a6-11e7-8cef-5274811af53b.png)

**Comment by alexandrudima** [comment]
@YanYuanFE  Can you please try using `'`s for spaces in font names. Chromium (which we are built on top of) is very picky w.r.t. casing and spaces. i.e. would the following work:

`"editor.fontFamily": "'Arial Narrow'"`
