### ISSUE TITLE
Remove TimerService debt

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#34944]
The current timer service depends on outsiders assigning values to its public files, like `restoreViewletDuration`. These things should be replaced with `startupTimers` as it encapsulates/hides information properly and as it makes it easier to add new timer ticks. 

This is a [sample](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L322) using startup timers, this is how the timer service [uses](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/timer/node/timerService.ts#L97) the ticks

**Comment by bpasero** [comment]
Looks like this is done via https://github.com/Microsoft/vscode/commit/32d43295f0a1b7b3f4bdc2fbee724362e7e9a17a#diff-18f5e7dee362518450ae232b2f4830d4
