### ISSUE TITLE
Test: console shows origin when used from extensions

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#34946]
Refs: https://github.com/Microsoft/vscode/issues/34936

- [ ] Windows 
- [ ] Linux
- [ ] macOS

Complexity: 2

When using `console.log`, `console.warn` or `console.error` from an extension, the log information is serialised from the extension host to the renderer and then played back in the renderers DevTools console as well as debug console. This means that the origin of the console use from the extension is lost. We now preserve the origin and allow access to it.

Use `console.log`, `console.warn` or `console.error` from your extension with strings, objects, primitives etc. Verify:
* you can expand the message in the extension host dev tools to see the full stack of where the message was sent
* you see the location of the message in the right hand side of the debug console and can click on it
* the data that you log is not shown up in a bad way or is lost

**Comment by isidorn** [comment]
Merged with https://github.com/Microsoft/vscode/issues/34756
