### ISSUE TITLE
VSC freezes when opening .js or .ts files

### ISSUE THREAD

**Issue by FedPete** [Microsoft/vscode#34948]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
vscode-auto-open-markdown-preview|hnw|0.0.4
debugger-for-chrome|msj|3.3.0
seti-icons|qin|0.1.3

> The extensions above are disabled

---

Steps to Reproduce:

1. Start VSC editor (using last opened project folder)
2. Select a `.js` file
3. Editor window freezes
4. After waiting some time, you get the option REOPEN, KEEP WAITING, CLOSE
5. KEEP WAITING, jumps to previos step 4
6. REOPEN, you end up at step 1.
7. Same thing for `.ts` files.
8. No problem for `.json`, `.svg` files.

Reproduces without extensions: Yes

Other things I did:
A couple of days ago I installed Nodejs 8.5.0  
I uninstalled VSC and re-installed the latest version  
Still same problems  
I uninstalled Nodejs 8.5.0 and reinstalle Nodejs LTS 6.11.3
Still same problems

**Comment by FedPete** [comment]
Additional notes:

* No problems with small `.js` files
* `.js`, `.ts` files giving problems are 85KB in size, about 2130 line of code. The `.js` version is the trans pilled version of the `.ts` file.

**Comment by mjbvz** [comment]
This sounds like it may be https://github.com/Microsoft/TypeScript-TmLanguage/issues/515 or similar. 

@FedPete Can you try out the next [VSCode insiders](https://code.visualstudio.com/insiders/) builds to see if that fixes the issue. The current insiders build does not have the fix in it.

**Comment by FedPete** [comment]
I can confirm it's all about the [Microsoft/TypeScript-TmLanguage#515](https://github.com/Microsoft/TypeScript-TmLanguage/issues/515). I created a `.txt` file with the code snippet, no problems. When I change it to file extension `.js` it freezes.
I wait for a new build of the  SVCode insiders version and give you feedback. Thank you, for the quick response.

**Comment by FedPete** [comment]
@mjbvz - I can confirm that the problem is solved with version 1.17.0-insider, date 2017-09-30T05:06:21.234Z shell 1.7.7 Renderer 58.0.3029.110
