### ISSUE TITLE
My terminal has something wrong:

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#34954]
- VSCode Version: Code 1.16.1 **[Unsupported]** (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
Go|luk|0.6.65
background|sha|1.1.15
intelligence-change-case|zhe|1.1.0

---

Steps to Reproduce:

1. Open the terminal panel.
2. Now it looks like:
![image](https://user-images.githubusercontent.com/12682063/30808288-0f7f9340-a230-11e7-981c-2db1f10f8657.png)
And the input character would insert into wrong position:
![image](https://user-images.githubusercontent.com/12682063/30808315-350c1570-a230-11e7-8472-43128a2d6323.png)
I tried `cmd` too:
![image](https://user-images.githubusercontent.com/12682063/30808342-52dee1b8-a230-11e7-8b3a-9747d11cb458.png)

With the develop tool, I found the error dom structure:
![image](https://user-images.githubusercontent.com/12682063/30808417-9c8ee4ac-a230-11e7-9669-e80da7ea6f2a.png)

I has just re-install my win10 system image, and installed the vscode x64 version, before I used x32. so there are two install folder:
![image](https://user-images.githubusercontent.com/12682063/30808518-fc8e886c-a230-11e7-88d7-013dc5c23f89.png)
![image](https://user-images.githubusercontent.com/12682063/30808513-f57a605a-a230-11e7-8477-c1e6688164a0.png)
Maybe I need to remove the old x32 folder?

Reproduces without extensions: Yes/No

**Comment by zhengxiaoyao0716** [comment]
I tried to remove all the old installed, and re-install the x64version, but the problem still exist.
What's more, I tried the other package which installed without execute installer, instead unpacked from the `.zip` compress file directly:
![image](https://user-images.githubusercontent.com/12682063/30840070-d4d660e8-a2a7-11e7-8de6-eda15c18ed52.png)
This version has works well ever, but now it appeared the same wrong too.

**Comment by Tyriar** [comment]
Does it just occur with the first line? Does pressing enter get everything back in sync?

**Comment by zhengxiaoyao0716** [comment]
@Tyriar I'm sorry but, every thing has resume normal now.
![image](https://user-images.githubusercontent.com/12682063/30998633-bd40f5e4-a502-11e7-904e-b381471c4ed9.png)
I don't  known what  happened, and don't remember when it recover, everything  seems not change but it really resumed normal...

**Comment by Tyriar** [comment]
I don't think anything changed in this area so the issue might pop up again. I'll close this off in the meantime, just ping the issue if you see it again and I'll reopen 😃
