### ISSUE TITLE
Suggestion: Allow disabling autoClosingBrackets within strings

### ISSUE THREAD

**Issue by exts** [Microsoft/vscode#34956]
- VSCode Version: Latest
- OS Version: Windows 10 & Linux Mint

Idea:

Currently if you have `autoClosingBrackets` enabled auto closing tags inside strings still auto complete so if I'm typing inside a single or double quote string it'll still attempt to auto close quotations withing the string same with braces, it would be nice to be able to disable auto closing brackets for strings all together or even disable single/double quotes within strings.

That or improve auto-closing quotations within strings because it malforms the strings all together every time I use them.

**Comment by alexandrudima** [comment]
@exts What language are you using, as this depends from language to language ? And can you please provide a simple example.

e.g. I think for TypeScript this works ok:
![kapture 2017-09-25 at 14 53 44](https://user-images.githubusercontent.com/5047891/30809224-5d9cfbc8-a201-11e7-809b-6748b63fc717.gif)

**Comment by exts** [comment]
I'm using Crystal Language.

**Comment by exts** [comment]
Just downloaded 1.16.1 and it seems like it's fixed, so I'm going to close this for now.
