### ISSUE TITLE
[ts] editor.actionQuickFix: adding missing import incorrectly adds default import to an existing import

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#34951]
- VSCode Version: 1.16.1
- OS Version: Windows 10 Home version 1703

Steps to Reproduce:

1. Open an empty folder to vscode (e.g. `c:\temp\import-quickfix-bug\`)
2. Generate a .tsconfig file by running `tsc --init` in the folder
3. Create `to-import.ts` file with the following content: 
```typescript
export default class A {}
export class B {}
```
4. Create `index.ts` file with the following content:
```typescript
import { B } from "./to-import";

// 1. Move cursor to position Ln 9 Col 14 (between 'A' and '(' on line 9)
// 2. Press Ctrl+. (editor.action.quickFix)
// 3. Select "Add A to existing import declaration from ./to-import." from the list.

let test01 = new B();

let test02 = new A();
```

5. Follow the steps described in the `index.ts` file.
6. Notice how the import is incorrectly added after B inside the curly brackets:
```typescript
import { B, A } from "./to-import";
```
This produces an error: `.../to-import"' has no exported member 'A'.' at: '1,13'source: 'ts'`
Instead, the import should look like this:
```typescript
import A, { B } from "./to-import";
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18752
