### ISSUE TITLE
Mac OS X :: 0.10.9 :: No Intellisense for PowerShell variables

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3496]
It seems that variables are not showing up in Intellisense, although the editor itself is highlighting the other variable references (*first screenshot*). Hence, I can't tab-complete to save myself time and effort. 

Am I the only one seeing this @daviwil? I know the PowerShell engine / Editor Services isn't available on Mac OS X, but I figured it could "fake it" like with Bash variables (*second screenshot*)

<img width="272" alt="screen shot 2016-02-26 at 7 54 29 am" src="https://cloud.githubusercontent.com/assets/466713/13355576/542b4b0e-dc5e-11e5-8f76-7807232ef4e4.png">

<img width="300" alt="screen shot 2016-02-26 at 7 56 08 am" src="https://cloud.githubusercontent.com/assets/466713/13355608/7dd0cd8a-dc5e-11e5-91a5-b26d469ab9cf.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by daviwil** [comment]
Question for the VS Code guys: under what circumstances does the Sublime-style auto completion become enabled?  Does that feature get turned off if my extension registers a completion provider for the .ps1 file type?

**Comment by joaomoreno** [comment]
@daviwil If the extension register a completion provider, then only that is used. This seems to be a Powershell specific issue, can you move it there?

**Comment by daviwil** [comment]
Yep, thanks!  New issue is here: https://github.com/PowerShell/vscode-powershell/issues/106
