### ISSUE TITLE
Default Git SCM 

### ISSUE THREAD

**Issue by Aldo-Hutch** [Microsoft/vscode#34969]
- VSCode Version: 1.16.1
- OS Version: OSX Sierra 10.12.6

Have recently updated VS code, to find that the inbuilt git SCM has disappeared. 
Different SCM extensions display as normal, but once removed does not display the default.
Command Pallet does not allow running "Switch SCM", "Disable SCM", "Disable Preview SCM"

Steps to Reproduce:

1. Open VSCode on a single project
2. Go to SCM tab
2. Observe that the default Git provider is a non-option

<img width="624" alt="screen shot 2017-09-25 at 15 23 14" src="https://user-images.githubusercontent.com/21175505/30814245-87c27a94-a207-11e7-95c3-04caa5e1f037.png">

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@Aldo-Hutch What does `git --version` return?

**Comment by Aldo-Hutch** [comment]
I found the issue.
Running `git --versions` revealed that XCode required its terms and conditions to be agreed to. 
Working now.

**Comment by joaomoreno** [comment]
Excellent.
