### ISSUE TITLE
Strange behaviour for cursor movement in find widget

### ISSUE THREAD

**Issue by csalv5** [Microsoft/vscode#34976]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

I like to use alt+j/alt+l for cursor movement, so i've defined the following keybinding:
```
,{
    "key": "alt+l", // or "alt+j"
    "command": "cursorRight",
    "when": "editorFocus && findInputFocussed && findWidgetVisible"
}
```

but
1. when i open find widget
2. and type alt+l

Two strange behaviours occur:
-> cursor disappear
-> even though widget is focussed, cursor (invisible) movements are done in the editor.

I've chosed the same "when" clause of alt+up / alt+down used in find history commands.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
`cursorRight` is targeting active editor so even though the when clause has `findInputFocussed `, it won't work.
