### ISSUE TITLE
How to Find text in Debugger console in visual studio code ? 

### ISSUE THREAD

**Issue by radharajendran** [Microsoft/vscode#34973]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
EditorConfig|Edi|0.10.1
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.0
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.3.0
vscode-icons|rob|7.14.0
gitblame|wad|2.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/4338
