### ISSUE TITLE
smartselect.grow/shrink doesn't work in multiple cursor mode

### ISSUE THREAD

**Issue by csalv5** [Microsoft/vscode#34975]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
![grow_shrink-issue](https://user-images.githubusercontent.com/6254054/30816425-39d949e8-a216-11e7-91ba-7415446ae4fa.gif)

Expected: grow/shrink should be applied to all instances of the cursor.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
duplicate of #4795
