### ISSUE TITLE
Loaded ScriptsLoaded Scripts

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34979]
Seen with both node and chrome debugging

![image](https://user-images.githubusercontent.com/323878/30823186-383c23c0-a1e0-11e7-9a19-e2d544ae10b6.png)

**Comment by weinand** [comment]
node-debug2 sends two event for every loaded script:
```
To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"timers.js","path":"timers.js","sourceReference":1007,"origin":"read-only core module"}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"<node_internals>/timers.js"}}
```

The obsolete event "scriptLoaded" has the correct path starting with "<node_internals>/" and the new event "loadedSource" with a "path" that misses the "<node_internals>/".

I will remove the compatibility code in the loadedScripts explorer today.

**Comment by roblourens** [comment]
I do need to fix that but I was more pointing out that the viewlet title is duplicated. Same for other viewlets: 
![image](https://user-images.githubusercontent.com/323878/30925967-7a5df1fa-a368-11e7-8b0f-cd578db95fe8.png)

**Comment by weinand** [comment]
Sorry, I didn't notice that in your screenshot.

And I cannot reproduce this in the latest.

**Comment by roblourens** [comment]
It actually seems ok in e059563fb6b8905de79ac4c75be537bb6dc74f5f now...

Tracking your other comment in https://github.com/Microsoft/vscode-chrome-debug-core/issues/240
