### ISSUE TITLE
recall list for search

### ISSUE THREAD

**Issue by l11vdo** [Microsoft/vscode#34977]
The most annoying thing using vscode is having to continually retype the same search strings.
Could a recall buffer / typeahead feature be added to the input box in the SEARCH tool??

**Comment by roblourens** [comment]
You can access search history with alt+up/down. But there are some other open feature requests to change this to just the arrow keys, or add a dropdown list.

**Comment by l11vdo** [comment]
i've tried Alt + up arrow / down arrow and this has no effect.
Please can you be specific about how to retrieve previous search strings
Lyndon

**Comment by l11vdo** [comment]
sorry - its working now ive created a list
thanks
