### ISSUE TITLE
Restore terminals including the current directory upon restart

### ISSUE THREAD

**Issue by SoumenDass** [Microsoft/vscode#34971]
Steps to Reproduce:

Operating System: Linux Mint.

1. Open terminal in VSCode
2. cd to some directory (different from the default/home directory)
3. Restart vscode
4. Terminal is restored but the current directory is not same as the one prior to restart

#Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
