### ISSUE TITLE
No MacOS Insiders update for several days

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#34978]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider)
 f7962f0682a76516df51de4856f8ccc5d8ad578a
- OS Version: MacOS

Checking for updates produces No Updates Available. Last update installed was above version, dated 2017-09-20T05:07:02.538Z

**Comment by jtsom** [comment]
Addition - Windows (x64) also shows no updates.

**Comment by sandy081** [comment]
Yeah, we are facing some signing issues. Hence the updates are not there. If interested, I would point to the unsigned bits which you have to manually download and install. 

cc @joaomoreno

**Comment by stef-levesque** [comment]
@sandy081 @joaomoreno  where can we download those unsigned builds ?

**Comment by sandy081** [comment]
Please let me know the platform you need the installable, I can share you the link.

**Comment by nanaasumadu** [comment]
@sandy081,

Hi Sandy,

If you can please share the link for MacOS and Windows x64, that will be great.

Thanks in advanced.

**Comment by sandy081** [comment]
Here are the links to

* MacOS: https://az764295.vo.msecnd.net/insider/67a8479bdcb95b3e21959342663b828d97f2098f/VSCode-darwin-insider-unsigned.zip

* Windows 64: https://az764295.vo.msecnd.net/insider/e059563fb6b8905de79ac4c75be537bb6dc74f5f/VSCodeSetup-x64-1.17.0-insider.exe

**Comment by nanaasumadu** [comment]
@sandy081 

Thank you so much.  Much appreciated.

**Comment by stef-levesque** [comment]
With those unsigned builds, I guess it's best to set `"update.channel": "none",`

**Comment by seanmcbreen** [comment]
Unfortunately these builds (as they are not signed) will take you off our update process.

Once we clear up the issues we have I'll update this issue and you should reinstall VS Code Insiders with a signed version - that way you will continue to receive updates.

Thanks for bearing with us.  We are working hard on a fix.
Sean

I'll reopen for now so I don't forget to reply :)

**Comment by pr-yemibedu** [comment]
Hello,
 May you share the portable zip version for these as well. I install 32bit and run 64 bit portable as needed. Thank you. Good day.

**Comment by jtsom** [comment]
Any update on this? What's the actual thing preventing the updated being signed so they can be released?

**Comment by kieferrm** [comment]
Mac builds are back to normal.
