### ISSUE TITLE
1px gap in between scroll bar and minimap

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#34974]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:15:33.090Z)
- OS Version: Linux x64 4.10.0-33-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
lorem-ipsum|Tyr|1.0.0
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.9
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.1.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3

(1 theme extensions excluded)

---

![image](https://user-images.githubusercontent.com/2193314/30819025-4157aef6-a1d2-11e7-96dd-6471bb6e8534.png)

**Comment by alexandrudima** [comment]
@Tyriar Do you use `workbench.zoom` ?

**Comment by Tyriar** [comment]
It's kind of difficult for me to reproduce again, it does seem to be related to zoom level though. Feel free to close as I'm having trouble with a repro.

**Comment by alexandrudima** [comment]
It might be similar to #32404 ... we position everything at good coordinates, such that logically the minimap is wide enough that it "touches" the scrollbar, but floating points get rounded by Chromium due to zoom level.
