### ISSUE TITLE
Add 'Collapse All' to Explorer panel

### ISSUE THREAD

**Issue by smbkr** [microsoft/vscode#34972]
Now that the Explorer panel allows for extensions to add their own items, it can get quite cluttered, showing for example, open files, project files, code outline, git log, bookmarks, Docker containers, etc, etc.

It would be helpful to have a Collapse All button at the top of this list (or wherever is deemed appropriate), along with Collapse Other buttons on each section, to quickly de-clutter this view.

**Comment by cristim** [comment]
You have my +1, but I'd +100 this if I could!

In order to reduce this clutter, all the extension items should be collapsed by default, and only expanded to a reasonable size if they have some content to show. In my case they're most empty and taking space from my file tree.

Their size should be stored in the settings, and able to be overridden for the current workspace.

**Comment by sandy081** [comment]
@cristim Please try the latest insiders here - https://code.visualstudio.com/insiders. There was a bug (regression) that is by default opening custom views in a new workspace https://github.com/Microsoft/vscode/issues/36134. This got fixed in insiders. Please try out.

**Comment by cristim** [comment]
Thanks @sandy081, good to know it was already addressed.

I'm going to wait for the next release, the insiders won't be in sync with my normal vscode and I would rather wait than port all my settings to it.

**Comment by zpydee** [comment]
@sandy081 when is next release solving this issue planned?

**Comment by smbkr** [comment]
@zpydee 09-10/10 https://github.com/Microsoft/vscode/issues/37117

**Comment by drayfar** [comment]
It would be great to be able to Collapse All at any point in the file tree to collapse folders. Helpful when I'm cleaning up between tasks. Use this feature all the time in VS'17.

**Comment by sandy081** [comment]
Currently we have performance issues with Collapse all action on a tree and we are working on a new tree implementation which is more performant. I will add this support after this.

**Comment by pavel-agarkov** [comment]
on a small screen it is possible to work only with one expanded panel at a time.
so I would love to have an option to change **`expand panel`** action to be also a **`collapse all other panels`**.
many accordion controls out there have a similar option.
now I have first to collapse current panel before to expand the next one.
if panels could remember their height it would be wonderful as well.
thank you.

**Comment by Mellbourn** [comment]
Up until recently, the keyboard shortcut `cmd-left` would collapse the explorer view. This binding has disappeared. Was that intentional?

**Comment by sandy081** [comment]
There are quite a lot of improvements added after this issue was created. Improved views management, introduced view custom containers and views can control their initial visibility.

Please revalidate this request with latest release and create a new issue for new improvements.
