### ISSUE TITLE
Test: Region folding markers

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#34989]
Tests #12146

Complexity 3

- [x]  @auchenberg 
- [x] @sandy081 

Folding now supports region markers. Markers are defined by the language in the language configuration. The following languages currently have markers defined:

- TypeScript/JavaScript:  `//#region` and `//#endregion`  and `//region` and `//endregion`
- C#: `#region` and `#endregion`
- C/C++: `#pragma region` and `#pragma endregion`
- F#: `//#region` and `//#endregion`
- Powershell: `#region` and `#endregion`
- VB: `#Region` and `#End Region`

Region markers are case sensitive.

- test that the region folding works
- test edge cases: Missing start or end patterns, nested regions
- test the snippets for the folding markers

**Comment by sandy081** [comment]
Good job @aeschli.

**Comment by pcasalinho** [comment]
Powershell regions do not work!
```powershell
#region
Write-host '1 unicorn Dead!'
Write-host '2 unicorns Dead!'
Write-host '3 unicorns Dead!'
#endregion

#yadayada
 Write-host '1 unicorn Dead!'
 Write-host '2 unicorns Dead!'
 Write-host '3 unicorns Dead!'
#yadayada
```
It folds because of identation, not because of keywords (region, endregion)

**Comment by aeschli** [comment]
@pcasalinho Make sure you have the latest insiders. I tried with 1.17.0-insider (2017-10-04T17:31:53.393Z) with your example and folding #region/#endregion works.
