### ISSUE TITLE
Cannot open / launch / debug multiple subprojects in same workspace

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#34985]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
debugger-for-chrome|msj|3.3.0
vscode-docker|Pet|0.0.18
perforce|sle|2.2.1
tslint-tmp-multiroot-compat|sqs|0.17.0
autoimport|ste|1.2.2

Trying to launch with attached debugger via Code.
Not sure if it is even possible/feasible to so do from a single window - didn't bother trying.  Attempting to open two vscode windows for side by side debugging of two submodules/executables of a larger project.
launch and debug parameters for both are stored in the workspace's launch.cfg

Opening a new vscode window, then trying to reopen the same workspace results in the original workspace being pushed to front, leaving the new vscode in the 'no-open-workspace' state

---

Steps to Reproduce:

1.Open workspace
2.Open new window
3. open the same workspace (via recent or direct to file)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please use our multi folder support. Debugging is supported for that case
More about multi folder vscode you can find out by googling around

**Comment by vrachels** [comment]
Investigating further, I do see the multi-executable debugging process.  I don't think this is related to the multi-workspace view, though.  This technically does what I need, but could behave much better.   Ie: output for all processes are routed to the same debug console window, rather than operating like the output or terminal windows, with the ability to swap between channels.

Alternately, I would like to have multiple windows of the same workspace (folder view or workspace file) open at the same time.   Current workaround is to load once in vscode and once in insiders.  Various other tabbed-window applications (browsers, text editors, IDEs) provide this functionality.  Perhaps even with an 'ask to use existing window' dialog

workbench.editor.revealIfOpen seems vaguely relevant, but is set to false.

**Comment by vrachels** [comment]
fwiw- after working with it today, debugging multiple processes in the same window just has too many issues to actually be usable.

**Comment by isidorn** [comment]
@vrachels thanks for providing feeback. If you could distill those "too many issues" into seperate nice reproducable issues and file them on GitHub that would be great. Since that would help us improve that experience. Thanks
