### ISSUE TITLE
Format Context Menu and Keyboard Shortcuts not working/appearing

### ISSUE THREAD

**Issue by tnewtona** [Microsoft/vscode#34986]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.2.1
beautify|Hoo|1.1.1
composer-support-client|Hyp|0.11.3
Angular2|joh|2.7.0
Go|luk|0.6.65
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.0
vscode-docker|Pet|0.0.16

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@tnewtona Not sure what is the issue here. There is no enough information. Closing it as invalid.

Please reopen it with more details of what is not working with some screenshots. Also, check if this is due to some extensions by disabling them.
