### ISSUE TITLE
Smoke test on macOS hits socket file path limit issue

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#34988]
I swear we seem to hit every single exoteric issue with this smoke test.

The smoke test creates brand new user-data-dir folders in TEMP. In macOS, TEMP is usually a huge path. The communication sockets live inside user-data-dir. UNIX sockets have a [file path length limit](https://serverfault.com/questions/641347/check-if-a-path-exceeds-maximum-for-unix-domain-socket). So the sockets are simply cut. This surfaces as incredibly random and unconnected issues within the smoke test.

![image](https://user-images.githubusercontent.com/22350/30829079-11d8ff2c-a240-11e7-85c7-68d0958a05e1.png)

This took me **way** too long to find out.

**Comment by joaomoreno** [comment]
[It seems we're not alone.](https://bugs.chromium.org/p/chromium/issues/detail?id=469065)

**Comment by joaomoreno** [comment]
cc @sandy081 @isidorn

**Comment by chrmarti** [comment]
Marking verified after review.
