### ISSUE TITLE
Git Precommit check is not showing error when the added file is saved [ vscode contribution issue ]

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#34980]
While contributing to vscode, I added some changes on the code and I while doing a commit the precommit check is errored out and I edited and saved the file , then precommit is working , it should not .

- VSCode Version:
1.16.1

- OS Version:
Ubuntu 16

Steps to Reproduce:
1. Clone vscode repo
2. Try adding some code which makes tslint error and do a commit on the file  , the pre-commit check will show error 
3. Save the file and do commit (without adding the file), the commit will work , It should not because ( the changes won't be added but the pre-commit script is allowing that )

Reproduces without extensions: Nothing to do with extensions

**Comment by chrmarti** [comment]
@joaomoreno Shouldn't this be assigned to you? It currently shows up in the inbox.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by jeyanthimuthuram** [comment]
@joaomoreno if it is a bug and there are no duplicates ticket assigned , I can try fixing this :+1:

**Comment by joaomoreno** [comment]
@jeyanthimuthuram Sure, be my guest!
