### ISSUE TITLE
Allow customizable aliases for each terminal instance

### ISSUE THREAD

**Issue by nicholasengleman** [Microsoft/vscode#34983]
If I 3 terminal instances running, currently they are titled, "1: Bash", "2: Bash, "3:Bash".

It would be nice if we could each instance a customizable alias/title to help us remember what task each instance is doing.

**Comment by Tyriar** [comment]
Terminals launched by extensions can set this name for you. There is also a rename command that allows you to rename each session manually:

<img width="734" alt="screen shot 2017-09-28 at 9 59 03 am" src="https://user-images.githubusercontent.com/2193314/30970661-ae3a362a-a433-11e7-81f8-ee26ac2cd665.png">
