### ISSUE TITLE
'Revert File' in working files context menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3498]
* have some items in the working files
* context menu, notice 'revert file' actions. Why is this action here?
* clicking on the action produces no visible effect

![screen shot 2016-02-26 at 16 07 42](https://cloud.githubusercontent.com/assets/1926584/13355948/35baa8c8-dca3-11e5-8c36-18fef8e60f3b.png)

**Comment by joaomoreno** [comment]
Why would I know?

**Comment by bpasero** [comment]
We should enable this action (and maybe Save) only when the file is dirty.

**Comment by bpasero** [comment]
Actions are now only enabled when the file is dirty, otherwise not. They also only show up when auto save is disabled.
