### ISSUE TITLE
No syntax highlighting for dynamic .ts docs from debugger

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#34987]
When I get a .ts document from the debugger, it is no longer highlighted. Shouldn't this be done from the file extension? I think this worked before.

![image](https://user-images.githubusercontent.com/323878/30827528-4526f57e-a1ef-11e7-98c3-e5068ff9d87c.png)

**Comment by isidorn** [comment]
Nothing changed on the debug side.
Though we have done quite some refactorings with the uri.
@mjbvz on what documents do you do .ts syntax highlighting? Do you look at the extension or?
@roblourens repro steps would be great. Can you debug and check what is the exect uri of that document, you could place some breakpoints in [`DebugSource`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugSource.ts#L21) to check how this document gets created and then check back with @mjbvz if that uri should be handled by him

**Comment by mjbvz** [comment]
@isidorn We register the ts grammar based on language:

```
    "grammars": [
      {
        "language": "typescript",
        "scopeName": "source.ts",
        "path": "./syntaxes/TypeScript.tmLanguage.json"
      }
],
    "languages": [
      {
        "id": "typescript",
        "aliases": [
          "TypeScript",
          "ts",
          "typescript"
        ],
        "extensions": [
          ".ts"
        ],
        "configuration": "./language-configuration.json"
      }
```

@roblourens What is the language mode of the document in this case?

**Comment by roblourens** [comment]
It is plain text but I thought TS should be picked up based on the extension. The full path is correct. I'll debug in DebugSource

**Comment by roblourens** [comment]
The uri is `"debug:/Users/roblou/code/vscode-chrome-debug-core/node_modules/vscode-debugadapter/src/logger.ts?session%3Ddc36384e-3877-4b86-8634-86108c214336%26ref%3D1144"`, I guess the special debug uri is interfering with extension checking for the language mode?

**Comment by isidorn** [comment]
I have pushed a potential fix to only use the path for mimeTypeGuessing, not the full query of the uri.
If the fix does not work then:

* how is the file detected in the status bar as the language?
* You can put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugContentProvider.ts#L92) and check what mode that file is set to.
Do you get colorization if you manualy set the language to typescript for that file?

**Comment by roblourens** [comment]
Looks good now!
