### ISSUE TITLE
Setting to use .gitignore in QuickSearch

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#34991]
Follow-up from #24074.

**Comment by pxwee5** [comment]
Good work implementing it. Looks like it's time to switch. 

One thing to note though, quickopen with ripgrep is the only function slower in VSCode compared to Atom. Not sure if it's because I have too many apps opened but if you could make it faster or as fast as Atom's it will be great!

**Comment by chrmarti** [comment]
@pxwee5 Could you try the current insiders build or the upcoming 1.18? If it is still slow, please open a issue for us to investigate the details.
