### ISSUE TITLE
Terminal jitter on resize

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#34995]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Open integrated terminal and run `ls`
2. Resize vscode window
3. Notice terminal contents jittering

![sep-25-2017 14-23-48](https://user-images.githubusercontent.com/12821956/30831708-4fbbe608-a1fd-11e7-9fac-6543d8efb776.gif)

**Comment by Tyriar** [comment]
@mjbvz can you try repro this? I believe it's fixed.

**Comment by mjbvz** [comment]
Thanks. Yep, this is fixed in the latest insiders
