### ISSUE TITLE
Should collapse xml elements

### ISSUE THREAD

**Issue by kutyel** [Microsoft/vscode#350]
Right now it is not possible to collapse the xml elements in the editor.

![code_xml](https://cloud.githubusercontent.com/assets/5127501/11301612/ca8c46f8-8f98-11e5-80d3-685bae4abb78.png)

**Comment by matt-diehl** [comment]
This is on the roadmap (code folding) - 

https://github.com/Microsoft/vscode/wiki/Roadmap

**Comment by glen-84** [comment]
Duplicate of #105?

**Comment by alexandrudima** [comment]
Indeed, let's track this in #105
