### ISSUE TITLE
Extension needs to be notified when it gets uninstalled

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#35006]
When an extension is uninstalled, it needs to be notified of the uninstall event and do some cleanup before it is removed.

Here's the scenario. We have extension B which register some Java component in extension A. So when B is uninstalled, we would like to unregister B from A. Otherwise, A would attempt to load B's Java component in the next run, when B is already removed.

In our case, A is the Java Language Support from RedHat. B is the new Java debugger from Microsoft. Both ship Java artifacts which contain the real logic. So it's very important for the registration/unregistration to happen correctly.

**Comment by sandy081** [comment]
@akaroml Not sure why do you need to Uninstall listener here. Actually when an extension depends on another extension, you can add it as a dependency in `extensionDependencies` section of `package.json`. Dependent extension should not bother about the depending extensions existence or not. It should be other way round. We also make sure if an extension is uninstalled, we do not uninstall it if there is an extension depending on it. 

It looks to me that in your case B depends on A and A wants to do some clean up when B is uninstalled. This is showing some cyclic dependencies.

@aeschli FYI

**Comment by Luiz-N** [comment]
I have a different use case but the same request for an uninstall life-cycle hook/event. I have an extension that needs to clean up some dirs/files it creates on the OS when uninstalling but not simply while deactivating.

**Comment by sandy081** [comment]
Makes sense

**Comment by sandy081** [comment]
Related #14444

**Comment by sandy081** [comment]
Now you can provide node script (javascript) to run when the extension gets uninstalled(removed) from the system, using the property `vscode:uninstall` under the `scripts` property in `package.json`.

Example

```json
"scripts": {
    "vscode:prepublish": "tsc -p ./",
    "vscode:uninstall": "node ./out/src/extensionUninstall"
},
```

Using this hook, you can clean up the stuff that your extension has created.

**Comment by GabrielBB** [comment]
@sandy081 "Using this hook, you can clean up the stuff that your extension has created." I can't clean up vs code user settings on that hook. In my case, i add some settings.

**Comment by sandy081** [comment]
@GabrielBB Yes, this hook does not provide you access to vscode api. Please create a new feature request for that.
