### ISSUE TITLE
markdown snippets unavailable

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#35007]
- VSCode Version: 1.16.1
- OS Version: Win7 / Win10

Steps to Reproduce:

1. at markdown file
2. input snippet prefix , such as 'blod'
3. have not suggestion menu

when i create a extension, call registerCompletionItemProvider('markdown', { provideCompletionItems: () => {...}}, the callback will not response

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Are you sure you file is markdown? What does the language indicator at the lower left say?

**Comment by builden** [comment]
yes, i'm sure use the markdown file. when i change registerCompletionItemProvider first param to 'json', and switch to json file, i can get the callback

**Comment by jrieken** [comment]
Not sure I understand. My question was what the lower right says? It will tell you what language you are using. The fact that you get called for `json` means that your file is interpreted as json...

<img width="327" alt="screen shot 2017-09-29 at 11 38 23" src="https://user-images.githubusercontent.com/1794099/31010321-be8daa52-a50a-11e7-955f-45d89dc48ccc.png">

**Comment by builden** [comment]
![image](https://user-images.githubusercontent.com/9499016/31043437-30f593fa-a5ee-11e7-8a31-4e2261929b07.png)
I found the reason, vscode make the markdown file set quicksuggestions to false default
thank you also for your answer

**Comment by jrieken** [comment]
Ok. Thanks closing as question in that case
