### ISSUE TITLE
Provide a way to prevent popups when typing.

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#35008]
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: macOS Sierra 10.12.6 (16G29)

There is currently no way to prevent popups from appearing as one types. I find this very frustrating. Sometimes I just want to type and be able to see the code in the document. But there are always a minimal of popups that are going to appear as you type. I would expect they would disappear as I type, but the don't, they follow the cursor. Clicking somewhere will dispel them or hitting ESC. But this breaks the pace of typing code. You should provide some kind of setting to prevent all popups for when users want/need to type without the distractions of popups. 

My current user settings are as follows:

```
{
    "editor.fontSize": 12,
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "css.validate": false,
    "editor.fontFamily": "SF Mono, monospace",
    "editor.quickSuggestions": {
      "other": false,
      "comments": false,
      "strings": false,
      "editor.wordBasedSuggestions": false
    },
    "editor.quickSuggestionsDelay": 1000000,
    "editor.minimap.enabled": false,
    "editor.fontLigatures": true,
    "editor.wordBasedSuggestions": false,
    "editor.hover": false,
    "explorer.openEditors.visible": 0,
    "explorer.autoReveal": false,
    "emmet.syntaxProfiles": {
         "typescript": "html"
    },
    "emmet.includeLanguages": {"javascript":"javascriptreact"},
    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0
  }
```
Here's an image of what I'm talking about:

![vscode-popups](https://user-images.githubusercontent.com/249218/30843691-b9d84792-a23f-11e7-86c1-caa0b9156028.png)

The popup "Component(props: any)..." is exactly over the area I need to type in. I do not need to see this popup about the call signature every time I try to add a member to the class.

**Comment by yume-chan** [comment]
For this popup: `"editor.parameterHints": false`

Looks like you want to completely disable the language server, only leaving the code highlight (or maybe formatter)?

**Comment by alexandrudima** [comment]
@rbiggs  We have 3 auto-popping "pop-ups":
* suggestions
* hover
* parameter hints

There is just the last one that you need to turn off to never see auto popups again.
