### ISSUE TITLE
Configuration editing extension prints weird warnings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35017]
From here: https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts#L49

![image](https://user-images.githubusercontent.com/900690/30850875-33190008-a2a7-11e7-8192-3132b4f4ef79.png)

**Comment by jrieken** [comment]
This is a bad jsdoc/markdown link to a symbol that cannot be found. Those come in via 955e4b8c063b90fbcdaf265298541aaebdcd2d9f

**Comment by bpasero** [comment]
@jrieken at least maybe include this info in the warning, otherwise quite hard to relate the warning to the `extension-editing` extension. 

I could not figure out how to reference `#SourceControl.inputBox` properly.

**Comment by joaomoreno** [comment]
@jrieken @bpasero I don't understand what's going on here, but I just simply removed the link...

**Comment by jrieken** [comment]
haha. fair enough... there is an extension that implements a link provider for markdown-links in vscode.d.ts. when those links cannot be found it prints a warning
