### ISSUE TITLE
Folder to find, use the regular search no results

### ISSUE THREAD

**Issue by ChaimHong** [Microsoft/vscode#35012]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
json-tools|eri|1.0.2
Go|luk|0.6.65
csharp|ms-|1.12.1

When using the folder search, find the results. My search is a regular statement, open a single file the same use of this regular statement is no problem.
My regular "^\s*$\n", the purpose is to remove the blank line

**Comment by roblourens** [comment]
`^\s*$\n` won't work because multiline search isn't supported. But I just fixed it so `^\s*$` will work, without the newline.

**Comment by sandy081** [comment]
@roblourens Above regex is showing invalid results. Also the results view looks broken

![image](https://user-images.githubusercontent.com/10746682/30971084-4f481860-a467-11e7-8573-900f16896548.png)

**Comment by roblourens** [comment]
rg is returning some incorrect results. The results view is correct though since it's supposed to be matching empty lines.

**Comment by roblourens** [comment]
Fixed upstream, need 0.7.0+ https://github.com/BurntSushi/ripgrep/issues/599
