### ISSUE TITLE
[ctrl+c] ->[ctrl+v] -> Disordered form

### ISSUE THREAD

**Issue by bestime** [Microsoft/vscode#35011]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.0
vue-snippets|hol|0.1.5

---

Steps to Reproduce:

1.ctrl + c
2.ctrl + v
3.the text-index is wrong !!!

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@bestime Can you please give a concrete example, with the language you are working on ?

e.g. This works for me as expected in HTML:

![kapture 2017-09-26 at 16 07 14](https://user-images.githubusercontent.com/5047891/30864770-eed0e22a-a2d4-11e7-9bde-d33166736bdd.gif)

**Comment by bestime** [comment]
![Uploading abc.gif…]()

**Comment by bestime** [comment]
![abc](https://user-images.githubusercontent.com/30017385/30894397-25a6d0d8-a376-11e7-9598-8407543cc4ec.gif)

**Comment by bestime** [comment]
@alexandrudima 
![abc](https://user-images.githubusercontent.com/30017385/30894676-b0c0e2b6-a377-11e7-8685-88d465b723b9.gif)

**Comment by alexandrudima** [comment]
@bestime I cannot reproduce on a default installation of VSCode with the default VSCode settings.

Can you perhaps try disabling your extensions? I believe `auto-close-tag` sounds like an extension that would want to do things in HTML.
