### ISSUE TITLE
Paste HTML indent

### ISSUE THREAD

**Issue by wangcode** [Microsoft/vscode#35019]
- VSCode Version:1.16.1
- OS Version:Windows_NT x64 10.0.15063

Steps to Reproduce:

1.Copy any html from anywhere.
2.Paste into VSCode 
![](https://i.loli.net/2017/09/26/59ca14f76616e.gif)

**Comment by alexandrudima** [comment]
@wangcode

I could not reproduce with our default options. Can you reproduce when disabling all extensions? If yes, what are your settings ?

![kapture 2017-09-26 at 16 07 14](https://user-images.githubusercontent.com/5047891/30864733-cc218e32-a2d4-11e7-9afa-91aaedebee86.gif)

**Comment by wangcode** [comment]
@alexandrudima 
it's no problem when i disabling all extensions,
and then i enable all extensions, it's also no problem.
thank you for help me.
good day!
