### ISSUE TITLE
no whitespace shown after typing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3501]
- make whitespaces visible
- add some whitespaces at the end of a line that has the folding icons: Whitespaces are correctly rendered
- enter a letter: whitespaces go away
![image](https://cloud.githubusercontent.com/assets/6461412/13356358/1b4c51a6-dca5-11e5-855c-181a9354c9bd.png)

**Comment by alexandrudima** [comment]
Well, typing d no longer makes it trailing whitespace.
