### ISSUE TITLE
Tasks: clicking on configure action in quick open should open exact tasks.json location

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#35024]
Refs: #34953

1. Have a long `tasks.json` file
2. List all tasks in quick open, notice that each task has a configure action next to it, click on some configure button
3. Notice that the `tasks.json` gets opened on a previously edited location, not at the location where the task that I explicitly cliked on is

If we improved this in tasks land it would also allign better with how we open launch.json currently.

**Comment by dbaeumer** [comment]
Agree, but it requires me to reparse the file using Martins' json parser since our configuration service doesn't have that info. How do you do that in debug land.

**Comment by isidorn** [comment]
@dbaeumer ugh now I found some not so nice code that I am doing - counting the number of new lines https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L580

Using Martin's json parser might be nicer

**Comment by alexr00** [comment]
We already do this now.
