### ISSUE TITLE
[rust] Pressing backtick replaces selection instead of wrapping it

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#35029]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-docker|Pet|0.0.18
python|don|0.7.0
restructuredtext|lex|37.0.0
hg|mrc|1.1.7
language-gettext|mro|0.0.2
qub-xml-vscode|qub|1.2.8
sass-indented|rob|1.4.2

---

Steps to Reproduce:

1. Write `hello`
2. Select `hello`
3. Press `"` ➡️ it becomes `"hello"` ✔️ 
4. Press `` ` `` (backtick) ➡️ it becomes ``"`"`` 🚫  ➡️ it should become ``"`hello`"``

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@Yajo What programming language are you using ? (this is a language configuration and varies from language to language)

**Comment by Yajo** [comment]
I was on RST. Indeed Markdown seems to handle it right.

**Comment by alexandrudima** [comment]
@aeschli `` ` `` is not defined as a surrounding char in Rust. I don't know if it should be.

**Comment by aeschli** [comment]
@Yajo I'm a Rust novice, so please correct me. But from what I read, backticks are not used in Rust?

**Comment by aeschli** [comment]
Closing. I'm happy to reopen if backtick strings are part of Rust.

**Comment by Yajo** [comment]
By RST I meant ReStructuredText, sorry.

**Comment by aeschli** [comment]
ReStructuredText is from an external extension. You have to file an issue against the author:
https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues

**Comment by lextm** [comment]
More investigation shows inconsistency in VSCode behavior, and it does vary on languages,

**Test cases**

1. Select some text in a specific language file.
2. Input `"` or `` ` ``.

**Result**
* Batch: Autocompletion for `"`, but not for `` ` ``.
* YAML: Autocompletion for `"`, but not for `` ` ``.
* Markdown: Autocompletion for `` ` ``, but not for `"`.
* Restructured Text: Autocompletion for neither.

So let's put restructured text aside, how does VSCode decide what to do for Batch, YAML, and Markdown? I quickly glanced over the Markdown extension source code, but could not find a place that handles `` ` `` input. I guess it is another part of VSCode that controls the autocompletion.  Am I right?

**Comment by aeschli** [comment]
@lextm Each language defines it's auto pair characters. This is typically done in the language-configuration file, as done here for [yaml](https://github.com/Microsoft/vscode/blob/f3e9dce61281a37cb23b185832e13e3b3431940a/extensions/yaml/language-configuration.json#L10) and depends on the [language spec](https://symfony.com/doc/current/components/yaml/yaml_format.html#strings).
