### ISSUE TITLE
Don't lock the files while open in Visual Code

### ISSUE THREAD

**Issue by BatsheveF** [Microsoft/vscode#35020]
- VSCode Version: 1.16.1
- OS Version: 

Steps to Reproduce:

Please enable external editing (don't lock the files while open in Visual Code).
Thanks
I realy enjoy the Visual Code

Reproduces without extensions: No

**Comment by sandy081** [comment]
@BatsheveF What is not working when you try to edit a file outside?

**Comment by BatsheveF** [comment]
I try to run pub build (build of dart) with output to folder open in VisualCode,
then I get an error:
"Failed to delete entry because it was in use by another process",
I expect to override the files and get a message asking to "reload modified files"
(as I get in visual studio when doing the same action).

**Comment by bpasero** [comment]
Still happens?

**Comment by BatsheveF** [comment]
yes.
I'm Running a build in PowerShel and getting:

Thursday, November 16, 2017 07:44:46 AM
pub build
Failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
>>> DART pub build completed <<<
Thursday, November 16, 2017 07:44:57 AM

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BatsheveF** [comment]
Still happening.
I opened the vs code with --disable-extensions, and opened the files, then I ran the pub build.
and I'm getting the same message:

"Failed to delete entry because it was in use by another process."

**Comment by bpasero** [comment]
@BatsheveF can you use a tool like "handles.exe" (https://docs.microsoft.com/en-us/sysinternals/downloads/handle) to see which process locks the file?

**Comment by BatsheveF** [comment]
Done.
Preent Screen:

![handles](https://user-images.githubusercontent.com/25722483/32878124-5cdc3c9c-caad-11e7-94da-29eea14afc50.PNG)

**Comment by bpasero** [comment]
@BatsheveF you seem to have pointed it to a folder, is that also the thing you notice that the folder is locked, or is it the file?

Can you find out the command line of the CodeHelper.exe and Code.exe processes? You can do this with:

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by BatsheveF** [comment]
The folder is locked (and all the files inside it).
Here's the info:

![processexplorer](https://user-images.githubusercontent.com/25722483/32879755-e74b59ac-cab3-11e7-8475-98f6cd09737d.PNG)

Process | Command Line
------------ | -------------
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" --disable-extensions
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,19,23,41,61,74 --disable-gl-extensions="GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent" --gpu-vendor-id=0x8086 --gpu-device-id=0x0412 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=10.18.15.4248 --gpu-driver-date=6-29-2015 --service-request-channel-token=F65EC22E26110FBB651A12B80F003330 --mojo-platform-channel-handle=1524 /prefetch:2
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=5BE06553F6BCB24CF77DFB2390F3A51F --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Program Files\Microsoft VS Code\resources\app" --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=5BE06553F6BCB24CF77DFB2390F3A51F --renderer-client-id=4 --mojo-platform-channel-handle=2208 /prefetch:1
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" --reporter-url=https://rink.hockeyapp.net/api/2/apps/0ac07349c6e34e978fdfb42074932f22/crashes/upload --application-name=VSCode "--crashes-directory=C:\Users\C42\AppData\Local\Temp\VSCode Crashes" --v=1
CodeHelper.exe | "c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\files\node\watcher\win32\CodeHelper.exe" d:\Development\MOCH.PersonalSite\wwwroot\MOCH.PersonalSite.Web2\DartApps\App02
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap" --type=extensionHost
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html\node_modules\vscode-languageclient\lib\utils\electronForkStart" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html\server\out\htmlServerMain.js" --node-ipc --clientProcessId=3232
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap" --type=searchService
Code.exe | "C:\Program Files\Microsoft VS Code\Code.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=392A7AE3C63F0756134F6BDB088C6FAC --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --app-path="C:\Program Files\Microsoft VS Code\resources\app" --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=392A7AE3C63F0756134F6BDB088C6FAC --renderer-client-id=6 --mojo-platform-channel-handle=2380 /prefetch:1

**Comment by bpasero** [comment]
@BatsheveF I see. Is that the folder you are actually opening with VS Code?

**Comment by bpasero** [comment]
It looks like the file watcher on Windows is locking the folder, I have heard this before. Does it reproduce if you configure `"files.useExperimentalFileWatcher": true` and restart?
