### ISSUE TITLE
Master view isn't pretty

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35023]
re #34963

The SCM overview view is visually cramped and busy, labels repeat and don't align nicely. 

<img width="355" alt="screen shot 2017-09-26 at 11 09 22" src="https://user-images.githubusercontent.com/1794099/30852181-300a9e04-a2ab-11e7-8a8c-c8a6540b04ac.png">

**Comment by joaomoreno** [comment]
Any suggestions? :+1:

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
