### ISSUE TITLE
Empty workspace is a little too empty

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35021]
* open a new, empty, window
* trigger "save workspace as"
* 🐛 explorer should show an affordance to add folders

<img width="472" alt="screen shot 2017-09-26 at 11 02 51" src="https://user-images.githubusercontent.com/1794099/30851984-9de6e794-a2aa-11e7-9c51-591af95f1d83.png">

**Comment by isidorn** [comment]
Verifier:
* check that the add folder button appears when the workspace is empty
* check that the open folder button appears as before in a no folder setup
* check that transition between these and normal workspace and folder case work proprerly
