### ISSUE TITLE
Transition from task 0.1.0 to 2.0.0 produces errors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35022]
Refs: #34953

OS X

1. Follow the exect steps from Task testplan
2. Once you finish the 0.1.0 version, for version 2.0.0 continue in the same workspace, but just delete the `tasks.json` file
3. Continue with the 2.0.0 test and once you select the problem matcher $tsc notice an error in the message service
4. Running my task does not work and I am getting errors

Note that once I reload vscode everything works nicely.
I believe tasks framework should handle the case of tasks.json deletion and it should handle the transisiton to 2.0.0 more gracefully

![screen shot 2017-09-26 at 11 00 50](https://user-images.githubusercontent.com/1926584/30852053-cfb45c34-a2aa-11e7-898a-bfc8a4264377.png)

**Comment by dbaeumer** [comment]
No critical for September.

**Comment by kieferrm** [comment]
See #35175 for an example in which this really hurts.

**Comment by dbaeumer** [comment]
Moving to September due to #35175
