### ISSUE TITLE
git  delect err or

### ISSUE THREAD

**Issue by King-Ran** [Microsoft/vscode#35027]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
yaml|ada|0.0.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
angular2-snippets|dan|1.0.16
vscode-eslint|dba|1.3.2
vscode-generate-getter-setter|DSK|0.4.2
tslint|eg2|1.0.9
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
vscode-add-angular-native-files|jos|0.0.9
Angular-BeastCode|Mik|4.4.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.0
material-icon-theme|PKi|2.2.1
code-settings-sync|Sha|2.8.3
autoimport|ste|1.2.2
nativescript|Tel|0.7.2

---

Steps to Reproduce:

1.　i add node_modules.zip
2.    i delete in my computer  folder
3.    err ,my git show my node_modules.zip need add, but i don`t have node_modules.zip 
       i can`t delete node_modules.zip in my git  

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This is hard to understand, do you mind sharing a screenshot?
