### ISSUE TITLE
Cannot resize SCM bucket

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35028]
re #34963

Watch the movie and relax

![sep-26-2017 11-21-07](https://user-images.githubusercontent.com/1794099/30852701-f310605e-a2ac-11e7-9795-224a151691c3.gif)

**Comment by joaomoreno** [comment]
Do you feel the same when using the explorer open editors view?

**Comment by jrieken** [comment]
?

**Comment by joaomoreno** [comment]
You should be able to resize it, when there are more than 5 repositories.
