### ISSUE TITLE
Bad master/child metaphor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35026]
re #34963

The new SCM master/child UI uses UX controls/metaphors that we use in other places to fence off pieces, e.g "Open Editor" vs "Folders", "Callstack" vs "Watched Variables", "Installed" vs "Recommended Extension" etc. 

None of those usage have a master/child relationship and I think its in-consistnet, unexpected, and confusing see see the SCM viewlet re-purpose those controls in a master/child mannar

<img width="638" alt="screen shot 2017-09-26 at 11 15 10" src="https://user-images.githubusercontent.com/1794099/30852502-41252cbc-a2ac-11e7-86d9-29f00130fef4.png">

<img width="355" alt="screen shot 2017-09-26 at 11 09 22" src="https://user-images.githubusercontent.com/1794099/30852508-444e99b4-a2ac-11e7-83b2-2e5e5f3159f5.png">

**Comment by joaomoreno** [comment]
Not sure about the amount of confusion... I would leave this running for a few iterations before changing it just because these widgets are used in different ways in other places.

The master/child metaphor isn't badly implemented, it's actually correct. But maybe you intend to say that when two list widgets are on top of another, a master/child metaphor should not be expected...?

**Comment by stevencl** [comment]
I'm running a UX study today and tomorrow on multi root UX. and will get some feedback about this experience.

**Comment by joaomoreno** [comment]
@jrieken Suggests using a combo box, similar to how debug does it, which I like. Though, I will effectively be using the same widgets as Debug and providing a different abstraction with their composition, which is what this issue is against.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
