### ISSUE TITLE
SCM: status bar should indicate the repository it shows information about

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35037]
Testing: #34963 

I think we should indicate the repository that we are showing status for from the status bar to the left of the branch. Clicking this repository could just open the SCM viewlet where the user can click on another one. If the user picks multiple, we could still just take the first. The important thing here is to make it clear which repository a branch belongs to.

![image](https://user-images.githubusercontent.com/900690/30853488-3cc7ed50-a2af-11e7-8a01-015e907c2833.png)

**Comment by joaomoreno** [comment]
It is indicated via tooltip. I didn't want to waste more space in the status bar. Is it really common that you get confused about which repo that status is from?

**Comment by bpasero** [comment]
Maybe we can have it behind a setting. But I agree on the space down there to be valuable. We can also wait for more user feedback.

**Comment by ckrger** [comment]
> We can also wait for more user feedback.
I find it confusing that the repository for which the status is displayed is fixed i.e. I would expect it to change whenever I switch to (or focus, in case of a split editor) a different file. Other editors do it like
this. If it was implemented like this no indication would be needed. It would be clear that the information is about the repository containing the file currently edited.

**Comment by alessandrodimarco** [comment]
In a workspace with many repos it gets confusing. Especially when having many micro-services where each service has a similar structure.
