### ISSUE TITLE
Tasks: do not show task selection picker if there is only one choice

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35033]
Refs: #34953

1. Have exactly one task running
2. tasks > terminate task or restart running task
3. Notice the user is presented with a quick pick as a choice to pick which task to terminate even though there is only one choice. I think the UI and the exeprience would be cleaner if we do not ask the user if there is only one choice

**Comment by dbaeumer** [comment]
This is on purpose. Since restart and terminate are 'invasive' actions I ask the user about the task. It is basically a confirmation. 

Any objection to close ?

**Comment by isidorn** [comment]
@dbaeumer feel free to close. That is just my feedback, though I understand some users would prefer the confirmation.

**Comment by dbaeumer** [comment]
Closing then.
