### ISSUE TITLE
SCM: repository status could get some alignment

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35039]
Testing: https://github.com/Microsoft/vscode/issues/35034

I think visually it would be nice if the repository status would be aligned at least on the left hand side. We always seem to have the branch icon followed by the branch name and I think the branch icon should always show aligned across all repositories:

![image](https://user-images.githubusercontent.com/900690/30853590-82c881ac-a2af-11e7-81da-605e85c19e3e.png)

**Comment by bpasero** [comment]
Actually this is more complicated and needs more thinking:

![image](https://user-images.githubusercontent.com/900690/30853807-1bf7f34e-a2b0-11e7-8d9c-c97e06d66c53.png)

It seems to me we have some structure per row:
* the repository name
* the repository provider name
* the number of changes
* the branch
* dirty indicators (*, +)
* the sync action
* incoming / outgoing changes

Some way of aligning these would be nice, otherwise the view becomes very heavy.

**Comment by joaomoreno** [comment]
This is also nothing we can really control, given that providers can contribute whatever they want. We might want to drop the status items though, and just allow to have inline, square, actions.

**Comment by bpasero** [comment]
> We might want to drop the status items though

What does that mean?

**Comment by joaomoreno** [comment]
Those status items were never meant to be shown there, but in the status bar. I just repurpose them to that location. But maybe it's best if we call it a whole different location and have semantic actions in that location.

**Comment by bpasero** [comment]
Don't get me wrong, I like all the info I am seeing there. But visually I wonder if we can align things better that belong together.

**Comment by joaomoreno** [comment]
Closing this for now.
