### ISSUE TITLE
SCM: initialize git repo is weird

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35031]
Testing: https://github.com/Microsoft/vscode/issues/34963

I am not sure I get this action:

![image](https://user-images.githubusercontent.com/900690/30853005-c190ce32-a2ad-11e7-8b71-fa8ac6c78557.png)

I am being asked where to initialize the repository, but what if that path is outside of the opened workspace? Even worse, when I have no workspace open, I am still being asked, but then shouldn't we open that folder of the repo?

Imho this action should always init the git repo in one of the workspace folders and be disabled if no folder is opened. If multiple folders are opened, the user should be asked. 

Also, this action is hidden as soon as any repository is shown but I might still want to "git init" in one of my workspace folders.

**Comment by joaomoreno** [comment]
> Imho this action should always init the git repo in one of the workspace folders and be disabled if no folder is opened. If multiple folders are opened, the user should be asked.

👍 

> Also, this action is hidden as soon as any repository is shown but I might still want to "git init" in one of my workspace folders.

There's always the global command. The action is there just to catch your eye.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by joaomoreno** [comment]
Git init now asks for a folder name to initialise in.

Also, you can still initialise after that action item is gone, since there is the global command.

**Comment by bpasero** [comment]
@joaomoreno I think https://github.com/Microsoft/vscode/issues/35031#issuecomment-332440188 summarises my expected behaviour and I think you acknowledged that too.

**Comment by joaomoreno** [comment]
Have you tried the action lately?

**Comment by bpasero** [comment]
@joaomoreno yes:

**Empty Workspace**
The action is enabled and when I click it I am asked to pick a folder. Once I picked a folder, the viewlet shows changes from that folder. Once I reload the window, the SCM viewlet does not remember that.

**Fix:** Do not enable this action in empty workspace. It makes no sense unless you would also ask the user to actually open that folder in VS Code. 

**Folder Workspace**
I already opened a folder so why am I being asked to pick a folder? And when I pick a folder that is not opened I end up with the same issue as for the "Empty Workspace" case.

**Fix:** pick the opened folder to initialise and do not ask. 

**Multi Root Workspace**
I am asked again even though I already opened folders. 

**Fix:** Show a picker of workspace folders that are part of my multi root workspace to select from. If the workspace is empty (= 0 root folders) the action should not be enabled at all.

**Comment by joaomoreno** [comment]
On it. For the first, since we don't have contributable action enablement, I'll just have to hide it. Do you know of a context key I can listen to?

**Comment by bpasero** [comment]
@joaomoreno as far as I know we currently have no context key that reflects the state of the workspace, but it would probably make sense to have it.

**Comment by joaomoreno** [comment]
@bpasero What's the best place to put that?

**Comment by bpasero** [comment]
@joaomoreno maybe in the workspace service itself.

@sandy081 what do you think? could be a layering problem though...

**Comment by sandy081** [comment]
I think, having a context for workspace makes sense. 
We cannot have it Workspace service but can be done in workbench?

**Comment by joaomoreno** [comment]
@sandy081 Let's do it together tomorrow.

**Comment by joaomoreno** [comment]
@bpasero Thanks!

**Comment by joaomoreno** [comment]
> I already opened a folder so why am I being asked to pick a folder?

I'm leaving this picker. I've seen way too many users initializing their repo in their home folder just because they click that command. The dialog is there as a confirmation step.

Everything is fixed.
