### ISSUE TITLE
Explorer viewlet contributions render title twice

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35035]
<img width="308" alt="capture" src="https://user-images.githubusercontent.com/1931590/30853325-c0755116-a2ae-11e7-9c2a-073cbfdec98d.png">

@sandy081 assigning to you since all of them render the title twice.

**Comment by sandy081** [comment]
I already have the issue. But you are first to win :)

**Comment by joaomoreno** [comment]
Sorry about this @sandy081 

I even had that issue for myself: #35100
