### ISSUE TITLE
Unable to write into tasks.json creates a very confusing experience

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35030]
Refs: #34953

1. Have some workspace with tasks, for example one mentioned in the linked testplan item
2. Have some small error in your tasks.json, like an extra comma on the end of the `"tasks"` array
3. Run some task, when asked if he should scan output say "Never scan"
4. I always get the attached error
5. This is very confusing due to the fact that clicking on the "Open Settings" the workspace `settings.json` gets opened, not the `tasks.json`. Also the error makes the user believe something is wrong in his `settings.json` which is wrong

![screen shot 2017-09-26 at 11 21 56](https://user-images.githubusercontent.com/1926584/30852780-3971cb96-a2ad-11e7-9edd-b754e25689ce.png)

**Comment by dbaeumer** [comment]
Actually the message comes from the configuration editing service.

Moving to @sandy081 to correct the message in the case that I passed a workspace folder to the service. 

In general I thing the configuration editing service shouldn't pop up any message. It should reject the promise and the caller should handle that (which I currently don't do in task land).

@sandy081 please move back if there is something I can adopt (e.g. showing my own message).

**Comment by sandy081** [comment]
Yeah. Error message should talk about tasks file.

**Comment by sandy081** [comment]
Error message now talks about the correct file and actions.

![image](https://user-images.githubusercontent.com/10746682/30912789-313447ec-a38e-11e7-815e-3ca095ab7f0a.png)
