### ISSUE TITLE
SCM view should be customizable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35034]
Testing: https://github.com/Microsoft/vscode/issues/34963

The same as the explorer: it should be possible to always show/hide the "SCM Repositories" view, even if there is just one repo. And if there is multiple I should be able to hide it. We could always allow to change the active SCM repo from the "..." menu too.

**Comment by joaomoreno** [comment]
Except that the metaphor is different than the explorer. I can't hide the master view. I'll merge this with #35026
