### ISSUE TITLE
keytar ships 6MB

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35046]
keytar should get the same treatment (deleting debugging symbols) as the other native node modules we ship.

**Comment by chrmarti** [comment]
@alexandrudima How do I do that?

**Comment by alexandrudima** [comment]
Like the other 13 native node modules in: https://github.com/Microsoft/vscode/blob/97cf7e7aaf7221d792318fa6114d15584355235f/build/gulpfile.vscode.js#L290

**Comment by chrmarti** [comment]
@alexandrudima Are our tests run against the cleaned up modules? It doesn't look like that's the case.

**Comment by alexandrudima** [comment]
Nice !
