### ISSUE TITLE
Outfile attribite not generated when TS file is open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35042]
Testing #34993

I followed the steps in #34993 but no outFiles property was created even if a TS file is open. 

I always get:

<img width="977" alt="capture" src="https://user-images.githubusercontent.com/1931590/30853913-6c531422-a2b0-11e7-8798-9045aacdac3e.png">

Note, that I have a package.json without a main entry.

I would also argue that the outFiles property is taken from the tsconfig.json file options outDir or outFile.

**Comment by chrmarti** [comment]
Did you click Run (F5) or the Configure (Gear) button?

**Comment by octref** [comment]
This works for me on macOS.

**Comment by dbaeumer** [comment]
I think I pressed the green arrow button in the debug viewlet.

**Comment by weinand** [comment]
Please note: the `launch.json` is only created for the 'Configure' command (gear button), not for 'Debug' (F5 or green play button). 

When pressing F5 (and there is no launch.json), we create a launch config in memory, so you cannot really verify what is generated.

When pressing F5 for an open TS file in the editor, we cannot yet create a launch config that includes a "preLaunchTask" for generating the JS from source.
In this case the following (now improved) error message is shown:

![2017-09-27_16-08-55](https://user-images.githubusercontent.com/1898161/30918424-d186e33e-a39e-11e7-86e4-465073d74322.png)

Feature request https://github.com/Microsoft/vscode/issues/35160 covers this aspect.

The launch.json that is created for a TS file in the editor is covered by https://github.com/Microsoft/vscode/issues/35055.

**Comment by weinand** [comment]
@roblourens I've tried to improve the usefulness of the "Cannot launch program 'foo'; setting the 'outFiles' attribute might help." error message by detecting that `outFiles` or `outDir` has been actually configured but node-debug still cannot find the generated JavaScript.

Pls see https://github.com/Microsoft/vscode-node-debug/blob/d526bf450ff96f714653bfdb01b794ee306d3274/src/node/nodeDebug.ts#L950-L954

**Comment by roblourens** [comment]
I made the same change

**Comment by dbaeumer** [comment]
I am reopening this since I now get an error message complaining about no js file generated although a prelaunch task successfully created one. Here is what I see:

![cast](https://user-images.githubusercontent.com/1931590/31016315-771bdeea-a524-11e7-8fce-9c4ce3c6c99c.gif)

**Comment by weinand** [comment]
@dbaeumer How does your tsconfig.json look like?

**Comment by dbaeumer** [comment]
```json
{
	"compilerOptions": {
		"outDir": "./lib"
	}
}
```

**Comment by weinand** [comment]
@dbaeumer With your tsconfig.json it is expected that launching fails because a "sourceMap" attribute is missing.

Without a "sourceMap" attribute, the generated JavaScript does not have a backlink to the TS source.

The following tsconfig.ts should work:
```
{
    "compilerOptions": {
        "outDir": "./lib",
        "sourceMap": true
    }
}
```
