### ISSUE TITLE
Ignoring task configuration message pesters the user all the time

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35045]
Refs: #34953

1. Currently we show the "Ignoring task configuraiton" message every time a user runs a task
2. There is absolutely no way for the user to say never show this again

It seems like you are also showing this message whenever a user edits a tasks.json which feels wrong.
Why not use the message service instead, with a never show again action?

**Comment by dbaeumer** [comment]
This should only be printed once or when you change a tasks.json file. 

I got bad feedback about using the message service. This is why all `errors from parsing tasks.json` files go into the output window. I will make sure that the message is only shown once and that I don't bring the output panel to front

@isidorn would be nice to have a badge on the output panel that indicated `unread` messages.

**Comment by isidorn** [comment]
@dbaeumer regarding the badge there is already an issue for this https://github.com/Microsoft/vscode/issues/34703

**Comment by dbaeumer** [comment]
@isidorn thanks

**Comment by dbaeumer** [comment]
I now show a detailed message in the output window and a message box which has a Don't show again button. The output window doesn't come to front.
