### ISSUE TITLE
opening a file using code --wait does not wait to quit 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35049]
Testing #34764

- Open VS Code with a folder.
- Now from terminal, open a file from a different folder and has `.vscode` folder in it using `--wait`

Expected the command waits but it terminates immediately

**Comment by bpasero** [comment]
Pushed a change to now prefer to open the file that was passed to `--wait` instead of opening the parent folder when it contains a `.vscode` folder.
