### ISSUE TITLE
Tasks output covers terminal running the task

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35043]
Refs: #34953

1. Follow the steps for multi root workspace in the testplan
2. Once you run the npm compile task notice that the Output panel is opened with the message how tasks 0.1.0 are not supported in multi root folder
3. I am puzzled as to where my output is and if my task actually got ran
4. What actually happened is that my task was ran in the terminal, however the output deprecation message comes on top. Since this is less important than my actuall task output I would expect the task output on top

**Comment by dbaeumer** [comment]
Agree. Partly dups the other bug you opened about pestering :-)

**Comment by dbaeumer** [comment]
I now show a detailed message in the output window and a message box which has a Don't show again button. The output window doesn't come to front.
