### ISSUE TITLE
SCM: repository actions grow out of tree item bounds on click

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35040]
Testing: #35034

The animation on click causes the icon to leave the bounds of the tree. I actually think the animation really does not work well within a tree item where there is not a lot of space:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/30853702-d73ca948-a2af-11e7-9058-724703e3115f.gif)

**Comment by joaomoreno** [comment]
This has **always** been like that in the ActionBar. I will not fix that.
