### ISSUE TITLE
More aggressive  auto-added SCM provider removal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35041]
re #34963

* have workspace with SCM
* open a file from another SCM managed folder/workspace
* you see another provider being added to the SCM viewlet which is good
* now close the file from step 2
* 🐛 the SCM provider is still there, enough I didn't make a change, the repo isn't dirty, the file is gone... I think in such cases (last files of a foreign repo disappears) we should also remove the provider again. Today it makes the "reading a file"-workflow more heavy weight

**Comment by joaomoreno** [comment]
Instead, I have added a context menu action to close a repository:

![image](https://user-images.githubusercontent.com/22350/30958418-6102b7f6-a43d-11e7-82f0-7923abe545df.png)

**Comment by octref** [comment]
Verified the current solution, but I also think removing SCM provider that doesn't have any associated open workspace / file would make more sense.
