### ISSUE TITLE
SCM: bogus question for where to create branch

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35044]
Testing: #35034

Clicking on branch action from a repository and selecting "Create new branch" asks again for which repository to use. It should remember the choice I made initially and not ask again.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/30854047-cde81070-a2b0-11e7-8775-692d0eac15ac.gif)

**Comment by joaomoreno** [comment]
Great catch!
