### ISSUE TITLE
Improve bad defaultUri argument to `showOpenDialog`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35059]
Testing #34821

![image](https://user-images.githubusercontent.com/22350/30855030-c7c23196-a2b3-11e7-96ee-fb5e53c5027f.png)

Maybe the error message should indicate which `bad path` it refers to. Or maybe just ignore it, if it's bad and continue as if no URI was passed.

**Comment by jrieken** [comment]
Yeah, for now you can only open `file`-uris

**Comment by jrieken** [comment]
I have improved the error message, unsure about ignoring...
