### ISSUE TITLE
Generated launch.json doesn't reflect my workspace content

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35055]
Testing #34993 

A workspace with

- main.ts file
- tsconfig.json with outDir: "./lib"
- no package.json
- compile TS file
- open .\lib\main.js
- generate launch.json. You get:

```ts
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}",
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			]
		}
	]
}
```

Observe: neither `program` not `outFiles` match any of my configuration.

**Comment by dbaeumer** [comment]
Actually retesting it I get:

```ts
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}"
		}
	]
}
```

Still not what I expected to get.

**Comment by octref** [comment]
The first generated config is when a TS file is open in one of the tabs. The second one is when no TS file is open.

On macOS I get the same result. `program: "${file}"` seems reasonable to me, but `outFiles` should be read from `tsconfig.json`'s outDir or outFiles I think.

**Comment by weinand** [comment]
I'm now setting the `program` attribute to the file open in the editor (if this is JS or TS).
The `outFiles` glob pattern is optionally derived from the `compilerOptions.outDir` attribute from a top-level `tsconfig.json` file.

**Comment by dbaeumer** [comment]
Verified. I no get:

```ts
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/lib\\main.js",
			"preLaunchTask": "tsc: build - tsconfig.json",
			"outFiles": [
				"${workspaceFolder}/lib/**/*.js"
			]
		}
	]
}
```
