### ISSUE TITLE
SCM: repositories are not sorted by order of the workspace config file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35065]
Testing: https://github.com/Microsoft/vscode/issues/34963

It seems that the order I define in workspace file is not reflected in the sorting order of the repository view:

![image](https://user-images.githubusercontent.com/900690/30855887-c9d9c8e2-a2b6-11e7-8ac9-82ef20ea672d.png)

I changed the order while the SCM view was opened. `test-ts` and `test-js` are not in the order as defined.

**Comment by joaomoreno** [comment]
The repositories won't be resorted if you resort the list, but they should appear in the order of their respective folders, at startup. Multiple repositories can even come from a single folder. A repository can even come from any other place.

I'll close this as I don't think this will be an issue in real world usage.
