### ISSUE TITLE
Confusing syntax in API docs

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35061]
Testing #34821

https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1541

It uses this syntax:

```ts
{
	['Images']: ['*.png', '*.jpg']
	['TypeScript']: ['*.ts', '*.tsx']
}
```

When this would be simpler:

```ts
{
	'Images': ['*.png', '*.jpg']
	'TypeScript': ['*.ts', '*.tsx']
}
```

**Comment by jrieken** [comment]
Even simpler

```ts
{
	Images: ['*.png', '*.jpg']
	TypeScript: ['*.ts', '*.tsx']
}
```

**Comment by jrieken** [comment]
Going with the slightly more verbose keys-as-string variant because it makes it more clear that the it's a string and used for display purposes

```ts
{
	'Images': ['*.png', '*.jpg']
	'TypeScript': ['*.ts', '*.tsx']
}
```
