### ISSUE TITLE
'How to contribute' out of date?

### ISSUE THREAD

**Issue by Dimpl** [Microsoft/vscode#35068]
I have forked the project and am following the 'how to contribute'  guide to try and compile on Windows. On running `npm run watch`, I receive the error `'gulp' is not recognised...`. A little research suggests that this is a node package, which has to be installed globally before use in a project (https://semaphoreci.com/community/tutorials/getting-started-with-gulp-js, 'Gulp installation').

Have I missed something, or should the guide be updated in order to include this step?

**Comment by sandy081** [comment]
Did you follow the step to do install before compiling? 

`./scripts/npm install`

**Comment by Dimpl** [comment]
Yes

**Comment by sandy081** [comment]
I do not have gulp installed globally. `gulp watch` works for me after running `./scripts/npm.sh install`
