### ISSUE TITLE
task list still shows a root name with bracket

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35064]
Refs: #34953

1. Multi folder repository
2. Quick open > task 
3. Notice the task list presented here shows the folder names in brackets
4. Notice that the folder names are not shown in brackets for any other task UI, it seems like you forgot it for the Task quick open entry

![screen shot 2017-09-26 at 12 26 40](https://user-images.githubusercontent.com/1926584/30855742-43655e5c-a2b6-11e7-906a-d95012c11eb3.png)

**Comment by roblourens** [comment]
I don't think any other multiroot UI shows the root folder name in brackets, I prefer it without.

**Comment by dbaeumer** [comment]
The rule is to show them without in picker where the folder name can be rendered grayish.
