### ISSUE TITLE
TypeScript should allow to disable watch and build task detection seperately

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35067]
Testing #34992

- have a workspace with a tsconfig.json file
- Tasks > Run Task

You get a build and watch task which is great. However I would like to disable the build task auto detection since I would always prefer watch over build.

**Comment by mjbvz** [comment]
If we add this setting, I think we'd want to support defaulting to either build or watch. Something like:

```
typescript.autoDetectType: "build" | "watch" | "both"
```

**Comment by dbaeumer** [comment]
+1. off should be a valid value as well.

**Comment by mjbvz** [comment]
@dbaeumer I opted not to add an `"off"` setting since we already have `"typescript.tsc.autoDetect": "on"` and `"typescript.tsc.autoDetect": "off"` to control this. Let me know if you think we should combine these two instead of having separate settings

**Comment by mjbvz** [comment]
Actually, having two settings was not great. Instead I've created additional enum values for `"typescript.tsc.autoDetect"` instead and used these to control task detection

**Comment by dbaeumer** [comment]
@mjbvz this is what I somehow expected. That is why I ask to have `off` in the list.
