### ISSUE TITLE
Default name for showSaveDialog when using filters is wrong

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35063]
Testing #34821 on macOS

I call the API so:

```ts
window.showSaveDialog({ filters: { 'TypeScript': ['*.ts'] }});
```

![image](https://user-images.githubusercontent.com/22350/30855564-ba46e12c-a2b5-11e7-9593-85f83a47a060.png)

**Comment by jrieken** [comment]
Again, just forward stuff to our service/electron....

**Comment by jrieken** [comment]
Hm, this is just bad documentation. If you use `'ts'` instead of `'*.ts'` everything works as expected. I'll update the docs
