### ISSUE TITLE
Folding a region does not work when using snippets 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35069]
Testing #34989

See the video

![kapture 2017-09-26 at 12 18 01](https://user-images.githubusercontent.com/10746682/30855977-29d2bab0-a2b7-11e7-851e-d9c30729d7b4.gif)

**Comment by aeschli** [comment]
@sandy081 Don't put extra comments '//' ....

**Comment by sandy081** [comment]
When I do not put comments, I do not get the snippets for regions

**Comment by aeschli** [comment]
They are there, probably sorted to the end, depending on your "editor.snippetSuggestions": "inline"
![image](https://user-images.githubusercontent.com/6461412/30914134-d2537388-a392-11e7-93d5-7fe45e6886ae.png)

**Comment by sandy081** [comment]
Ah right. But won't be nice not to put extra comments when inside comments?

**Comment by aeschli** [comment]
That would mean to not use snippets. Snippets are not context sensitive, they show up everywhere.
To know if a position is in a comment needs a scanner/parser, so the proposals would have to come from the TypeScript server.

IMO snippets work fine here once you know they exists. The best way to use this is to just start typing '#'. 
![image](https://user-images.githubusercontent.com/6461412/30914728-ee308af8-a394-11e7-918c-0844c6704c10.png)
