### ISSUE TITLE
Can't open single file anymore if contained in folder workspace

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35060]
- have a folder workspace
- open a terminal
- navigate to the folder workspace location
- go into a sub directory
- code .\xxx.yy

Observe: the folder workspace opens not the single file.

**Comment by bpasero** [comment]
@chrmarti this seems to be coming from your smartness around `vs/code/node/windowsFinder.ts`

**Comment by chrmarti** [comment]
Indeed, this is by design. When there is already a window open on a folder that contains the file you want to open, that window is used to open it. You can still use `code -n somefile.txt` to let the file open in a new window.
