### ISSUE TITLE
Tasks: consider using folder name for terminal drop down

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35066]
Refs: #34953

1. Multi folder workspace
2. Run some task, notice that the title showed in the terminal drop down only has the task name
3. I suggest to aslo include the folder name in brackets (since we can not style here) after the task name

This is what we are currently doing in launch.json dropdown so it would be both for consistency and clarity.

**Comment by dbaeumer** [comment]
Good catch. Like the suggestion:

<img width="202" alt="capture" src="https://user-images.githubusercontent.com/1931590/30865347-9ba22e9a-a2d6-11e7-8139-872e3132a630.png">
