### ISSUE TITLE
// Coment on last line produces error 'Invalid regular expression'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3507]
- .js file
- comment out the last line //
- notice an error: 'Invalid regular expression'

**Comment by mjbvz** [comment]
I'm unable to repo this issue in VSCode 1.7. 

![screen shot 2016-11-18 at 2 39 15 pm](https://cloud.githubusercontent.com/assets/12821956/20449181/b4efba3c-ad9c-11e6-80cd-e1117ebd611d.png)

Please give a more recent VSCode release a try and let me know if you still see this issue. Thanks.
