### ISSUE TITLE
[css] accept selectors in ::slotted()

### ISSUE THREAD

**Issue by abdonrd** [Microsoft/vscode#35076]
- VSCode Version: v1.16.1
- OS Version: macOS Sierra v10.12.6

- Reproduces without extensions: Yes

Steps to Reproduce:

1. For example, write the next valid code in a CSS language mode:

```css
::slotted(div:hover) {
  color: red;
}
```

2. See the alerts.
![screen shot 2017-09-26 at 12 14 51](https://user-images.githubusercontent.com/1007051/30856255-16462c4c-a2b8-11e7-9a73-e5e05c71ebe0.png)

Reference: https://github.com/w3c/webcomponents/issues/655

**Comment by aeschli** [comment]
Please understand that we might wait until it is supported by the majority of browsers

**Comment by abdonrd** [comment]
Curiously, the tree-abiding pseudos (`::before`, `::after`, `::marker`, and `::placeholder`) are supported. They go after `::slotted()`.

<img width="837" alt="screen shot 2017-10-12 at 20 48 48" src="https://user-images.githubusercontent.com/1007051/31513561-00d6a290-af8f-11e7-93ac-c706d294ee1e.png">
