### ISSUE TITLE
Terminal Output incorrectly rendered for IEx help

### ISSUE THREAD

**Issue by RyanHirsch** [Microsoft/vscode#35070]
When using Elixir's Interactive Shell the help headings for functions is incorrectly formatted. It should be a yellow bar with black letters to indicate the name of the function, instead it is a shortened, non-contiguous bar with no text.

- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
EditorConfig|Edi|0.10.1
material-icon-theme|PKi|2.2.1
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
better-toml|bun|0.3.1
vscode-eslint|dba|1.3.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|5.2.0
rest-client|hum|0.15.2
terraform|mau|0.0.18
vscode-elixir|mjm|1.0.0
prettify-json|moh|0.0.3
cpptools|ms-|0.12.4
elm|sbr|0.15.0
vscode-nginx|sha|0.4.1
vim|vsc|0.10.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open terminal
2. Launch `iex`
3. Run `h String.split/1`

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35151
