### ISSUE TITLE
Allow to specify file path preferences for Copy path of Active File command

### ISSUE THREAD

**Issue by dKab** [Microsoft/vscode#35084]
This is a feature request. It would be nice if user could specify the following things in preferences for paths that are copied to clipboard when you use "Copy path of Active File" command:

- *separators type*: Windows style i.e. backwards slashes or Unix style - i.e. normal slashes. 
- *base*: currently paths begin from file system root (e.g. C:\Users\...). It would be nice to specify that when you are copying paths to clipboard you want it to start from project folder root or from a folder where git repository is based.

Use case:
=====

I'm on Windows. I use VCS, namely git, from integrated terminal. When I want to perform git commands on opened files (like for example `git blame` ) I have to get hold of file path. But git expects file paths to start from project root, not from File system root. It also only understands normal slashes. So now every time I want to do simple git blame or git log on a certain file I have to do a lot of work:

1. Copy file path
2. Insert it somewhere in the opened editor
3. Open "Replace" command
4. Replace all occurances of "\\" to "/"
5. Select part of the path that starts from project root folder and copy it to cpipboard
6. Return focus to terminal and insert my file path

I have to do quite a lot of this during my day, and honestly it isn't much fun.

**Comment by CoryXie** [comment]
This is the 1st extension I would like to find and use when started to use VS Code.

**Comment by dKab** [comment]
Ok, I'll create an extension for this.

**Comment by dKab** [comment]
@CoryXie if you are still interested here's the extension for this: https://marketplace.visualstudio.com/items?itemName=dkaba.better-file-path

**Comment by CoryXie** [comment]
@dKab Thanks for the work! Just tried, it works to copy the path in Linux path separator. 

1) Better to have it integrate into the explorer context menu, and provide key binding to do it short.
2) Better to include the parent folder name as the 1st dir in the path, for example, I was looking at a file in Linux kernel source tree which its under "Linux" git tree, it is copied as 'arch/powerpc/platforms/cell/spufs/context.c', better to have it copied as "Linux/arch/powerpc/platforms/cell/spufs/context.c", anyway, if a configuration options is available is better.

I am trying to fork your code base and bake it.
