### ISSUE TITLE
Saving an untitled file is not showing the prompt

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35083]
- Create a new Untitled file
- Save the file. ( I used `cmd+s`)

No dialog appears

**Comment by bpasero** [comment]
@isidorn maybe a case of checking for `IFileService.canHandleResource` but not for `untitled` scheme?

**Comment by isidorn** [comment]
@bpasero please code review. I checked all usages of `canHandeResource` in `fileActions` and added a check. If I have an `untitileEditorService` I use it to see if the resource is untitiled, otherwise I look at `schema`.

**Comment by bpasero** [comment]
@isidorn I think you can just always do `resource.scheme === 'untitled'` that should be sufficient.

**Comment by isidorn** [comment]
@bpasero thanks, I pushed
