### ISSUE TITLE
Exclude folders for php linting

### ISSUE THREAD

**Issue by binarious** [Microsoft/vscode#35089]
- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Add the following to the `settings.json`:
```json
"files.exclude": {
    "**/app/cache": true
}
```
2. Have a folder opened with a php file in `app/cache` which contains invalid syntax.

The errors still shows up in the errors pane.

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
It is expected. Language servers do not know about these exclude settings. Since the file is opened, it gets linted and thereby warnings/errors are shown.

**Comment by binarious** [comment]
So there is no way in ignoring these folders?

> Since the file is opened

The file is not opened. I do get php errors for files which are in my cache folders and which aren't opened in vscode.
