### ISSUE TITLE
The YUM vs-code repository is not signed.

### ISSUE THREAD

**Issue by esclear** [Microsoft/vscode#35086]
Trying to update code from the official yum-repository (https://packages.microsoft.com/yumrepos/vscode) yields the following warning message:
```
Warning: File 'repomd.xml' from repository 'Visual Studio Code' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.
```

As the warning states, signatures are important for integrity and trust.
So while I am aware that the packages and the manifest are transmitted via an encrypted channel, the warning may discourage users from updating or installing vs code.

**Comment by esclear** [comment]
So the fix would be to place the release-signing-key that the packets should be signed with (`0xEB3E94ADBE1229CF`) in the repository as `repomd.xml.key` in the `repodata` subfolder and the signature of the `repomd.xml` file as `repomd.xml.asc`.

**Comment by joaomoreno** [comment]
I didn't even know we had such an official package.

**Comment by esclear** [comment]
Well, uh, [surprise](https://code.visualstudio.com/docs/setup/linux#_opensuse-and-sle-based-distributions) :smile:

**Comment by Tyriar** [comment]
It looks like this might be an issue with the service we hook into that manages the repository. Thanks for the report, I'll ping them.

**Comment by Tyriar** [comment]
The team told me they took steps to fix the issue, I'm following up on what the root cause was.
