### ISSUE TITLE
Smoke Test: Squiggles in bin/www

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3508]
Following the steps in the smoke test, I open bin/www and I get the following errors:

Not sure why require is unknown in bin/www but tolerated in app.js

![image](https://cloud.githubusercontent.com/assets/5047891/13358626/89445446-dcb0-11e5-969b-861b4582b775.png)

**Comment by joaomoreno** [comment]
Related to Salsa

**Comment by egamma** [comment]
When I rename the file to `www.js` then the errors go away. So this might not be a Salsa issue, but an issue in how we associate the language/mode with the file `www`. I suspect the file is treated as a TypeScript file.

Assigning to Dirk he has debugged such a problem previously.

**Comment by dbaeumer** [comment]
@egamma what does the status indicator say about the language type. The problem I had was exactly the opposite. The shebang forces VSCode to treat all files as JS regardless of the extension. So even TS files where treated as JS if they have a shebang. So I am pretty sure the shebang forces VSCode to treat the file as JS but may be Salsa fails with it due to a missing extensions.

**Comment by dbaeumer** [comment]
I checked the samples and inside VSCode the bin/www file is treated as JavaScript. When the extension transfers the file to the tsserver VSCode has no means to tell the tsserver the type of the file. So I really guess that this is a tsserver issue falling back to TS type if a file has no extension.

![capture](https://cloud.githubusercontent.com/assets/1931590/13391174/1f9b5b0a-ded3-11e5-9768-2a502936ed28.png)

**Comment by egamma** [comment]
@dbaeumer 
![image](https://cloud.githubusercontent.com/assets/172399/13391153/05400274-ded3-11e5-9f69-d83d7490d666.png)

**Comment by dbaeumer** [comment]
@egamma see my latest comment. I am pretty sure that the tsserver treats files without an extensions as TS. I am experimenting with a jsonfig.json file to tell the tsserver this is a JS project.

**Comment by egamma** [comment]
Filed issue against TypeScript and documented the limitation in the release notes.

**Comment by zigomir** [comment]
Looking at typescript issue shows that 2.0 fixes this issue. This probably means that when TS2.0 lands in vscode we can expect this to be fixed, right?

**Comment by dbaeumer** [comment]
Yes, that is correct. I already adopted the new API to support this.

**Comment by lekhnath** [comment]
If you cant wait until TS2.x lands in VSCode.

//.vscode/settings.json
{
  "typescript.tsdk": "../node_modules/typescript/lib"
}
