### ISSUE TITLE
Allow *.lnk shortcut as workspace folder when created from a folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35085]
re #34775

* have a workspace with a few folders
* for one of those folders add symlinks
* add those symbols to the workspace file (manually)
* 🐛 they show gray, they shouldn't show at all as they are dupes

<img width="1446" alt="screen shot 2017-09-26 at 13 04 12" src="https://user-images.githubusercontent.com/1794099/30857290-7aaef38c-a2bb-11e7-9e24-8455d2ebfef9.png">

**Comment by bpasero** [comment]
@jrieken the only time I see this if I would create a shortcut of a folder via right click > create shortcut. I believe those are not resolvable by node.js. All other cases work for me via `mklink` (see https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/).

**Comment by jrieken** [comment]
>  folder via right click > create shortcut. 

Yes, like that and I would guess that most user create links like that on windows

**Comment by bpasero** [comment]
node.js reports this as a file and it seems to be a file and not an actual symbolic link.
