### ISSUE TITLE
WebView find widget: match case, match whole world, regular expression

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35082]
Refs: #33296

We shuold also support match case, match whole word, regulard expression in the web view find widget. Just like in the editor.
Mostly for consistency so these two experiences are not so much different

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
