### ISSUE TITLE
to undo one step back you have to do it at least 5-6 times

### ISSUE THREAD

**Issue by webshocker** [Microsoft/vscode#35090]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.9
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.10.1
beautify|Hoo|1.1.1
ionic2|Tha|2.4.0
jsx|Twe|0.0.1
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
alignment|ann|0.3.0
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.16
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.23.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ionic1-snippets|jus|1.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
font-awesome-codes-html|med|0.0.7
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.0
vscode-icons|rob|7.14.0
html5-boilerplate|sid|1.0.1
vscode-fileutils|sle|2.6.2
ramdajs-snippets|use|1.0.3
highlight-matching-tag|vin|0.4.4
expand-selection-to-scope|vit|0.2.0
cordova-tools|vsm|1.2.12
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1. just Do something and undo it
2. happens while working on HTML/CSS/JS files

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@webshocker Can you please try reproducing without extensions? You can do it by disabling all extensions and try.
