### ISSUE TITLE
Search: allow to search workspace relative paths

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35097]
I would expect in this case to get a file result, I wonder if this is because of our RipGrep change for file search:

![image](https://user-images.githubusercontent.com/900690/30860471-80385bb6-a2c7-11e7-95fc-41d14c592742.png)

I do have `vscode-docs` as one of the folders inside my workspace.

**Comment by roblourens** [comment]
Not a regression, right? I think I filed a feature request for this somewhere.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/32444
