### ISSUE TITLE
WebView find widget: cursor sometimes stop blinking

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#35094]
Refs: #33296
OS X

1. Extensions description -> find widget
2. Enter some search terms, navigate find history with alt + up / down
3. Notice that after some time the cursor inside the find widget stops blinking

Note that I was not able to reproduce this in the editor find widget.

**Comment by rebornix** [comment]
Looks like an upstream (webview in electron) issue where the input box is focused by `input.focus()` but the cursor doesn't blink, even though typing still works.

**Comment by isidorn** [comment]
@rebornix should we file this against electron than?

**Comment by bpasero** [comment]
@isidorn still happens?

**Comment by isidorn** [comment]
Can not reproduce and is not important. Closing
