### ISSUE TITLE
Incorrect rendering of Thai in the integrated terminal on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35096]
Testing #34868

* create a file `a.txt` with the following content and save it as UTF8 with BOM:
```
Thai is a Tai-Kadai language spoken by about 65 million 
people mainly in Thailand (ประเทศไทย), and also in the 
Midway Islands, Singapore, the UAE and the USA
```
* configure:
```
	"editor.fontFamily": "SimSun-ExtB",
	"terminal.integrated.fontFamily": "SimSun-ExtB"
```
* open the integrated terminal on Windows (defaults PowerShell)
* run ` chcp 65001`
* run `cat a.txt`

Observe:

* editor:
![image](https://user-images.githubusercontent.com/5047891/30859906-ba41d3b6-a2c5-11e7-8f98-a4885e4bf48f.png)

* native PowerShell (configured with `SimSun-ExtB` and after `chcp 65001`)
![image](https://user-images.githubusercontent.com/5047891/30859939-da70640e-a2c5-11e7-81e2-e9ac17c84193.png)

* ConEmu (uses cmd.exe, configured with `SimSun-ExtB` and after `chcp 65001`, with `type a.txt`):
![image](https://user-images.githubusercontent.com/5047891/30859982-feacc68c-a2c5-11e7-83b6-d132471d73b9.png)

* Integrated terminal in 1.13:
![image](https://user-images.githubusercontent.com/5047891/30860008-17e70fb8-a2c6-11e7-8b94-2bb9c79b5216.png)

* **new integrated terminal**:
![image](https://user-images.githubusercontent.com/5047891/30860072-2e350bd0-a2c6-11e7-948e-681e11396c5e.png)

Observe the problem around this glyph:
![image](https://user-images.githubusercontent.com/5047891/30860114-4f3e4256-a2c6-11e7-928e-78c7afc5493c.png)

I believe the same problem exists with Arabic, but it appears the old integrated terminal also suffered from problems with rendering Arabic (i.e. RTL).

**Comment by Tyriar** [comment]
This was fixed a while ago:

<img width="103" alt="screen shot 2017-12-28 at 7 06 48 am" src="https://user-images.githubusercontent.com/2193314/34414348-b51948bc-eb9d-11e7-9ec5-90a38e504743.png">
