### ISSUE TITLE
Regions are not folding correctly in off-side languages

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35091]
Testing #34989

Look at the video. There are total 4 regions with an addition end region line
- First region is folding correctly
- All others are not

![kapture 2017-09-26 at 14 02 14](https://user-images.githubusercontent.com/10746682/30859395-d46f3f32-a2c3-11e7-9b60-e2b9c67c1885.gif)

**Comment by aeschli** [comment]
Thanks @sandy081. Always post the sample as well... Saves me some typing :-)

Problem is that f# is using the off-side rule where empty lines are treated special
Reproduced with
```
//#region 
//#endregion

here is a region

//#region 

//#region 

//#region 

//#endregion


//#endregion


//#endregion

//#endregion
``

**Comment by sandy081** [comment]
Thanks for posting the sample. Will save my time for verification :)
