### ISSUE TITLE
Snippet tabstops disappear after changing tabs

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#35099]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

After expanding your snippet, if there would tabstops (with placeholders or without), they will disappear after you will move to another tab and return back.

GIF:
![tabstops disappear after changing tabs](https://user-images.githubusercontent.com/24613274/30860539-1bfe4d64-a2d0-11e7-9484-fbf2b44deedf.gif)

**Comment by alexandrudima** [comment]
@jrieken We could save with the view state the snippet state (via `IEditorContribution.saveViewState()` )

**Comment by jrieken** [comment]
duplicate of #27513
