### ISSUE TITLE
Smoke Test: Don't get cross file intellisense in JS

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3509]
* in the smoke test repo, add a new file bar.js:
```
exports.foo = 3;
```
* in app.js add the following:
```
var bar = require('./bar');
bar.
```

> No completions on bar

**Comment by alexandrudima** [comment]
![image](https://cloud.githubusercontent.com/assets/5047891/13358791/528d443e-dcb1-11e5-92d8-e10f45871fcf.png)

**Comment by egamma** [comment]
I cannot reproduce this with the following jsconfig.json

```json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

**Comment by joaomoreno** [comment]
Documentation

**Comment by egamma** [comment]
Upstream fix merged into our code.
