### ISSUE TITLE
Terminal consumes a lot of memory

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35104]
Testing #34868

[emoji-test.txt](https://github.com/Microsoft/vscode/files/1333136/emoji-test.txt)

* save this file as UTF8 with bom (I think it is already)
* configure `"terminal.integrated.scrollback": 5000`
* run `chcp 65001`
* run `cat emoji-test.txt`
* Take a memory snapshot before running `cat`
* Take a memory snapshot after running `cat`
* Observe:
listing a 345KB file ends up allocating a 32MB Buffer / CircularList:

![image](https://user-images.githubusercontent.com/5047891/30860892-2773a47a-a2c9-11e7-8797-73314430ae01.png)

**Comment by Tyriar** [comment]
This is being tracked in https://github.com/sourcelair/xterm.js/issues/791

**Comment by Tyriar** [comment]
We've made some improvements but some big ones are being worked on in xtermjs/xterm.js#791, tracking this upstream.
