### ISSUE TITLE
fs.existsSync fails with vscode debug tools, but works with node

### ISSUE THREAD

**Issue by dauledk** [Microsoft/vscode#35105]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Angular-BeastCode|Mik|4.4.2
code-settings-sync|Sha|2.8.3
wallaby-vscode|Wal|1.0.62
yaml|ada|0.0.9
vscode-color|ans|0.4.5
python|don|0.7.0
docthis|joe|0.4.8
Angular2|joh|2.7.0
typings-autoinstaller|jvi|1.2.0
heroku-command|pko|0.0.8
vscode-icons|rob|7.14.0
vim|vsc|0.10.1
vscode-import-cost|wix|2.5.0

---
fs.existsSync fails with vscode debug tools, but works with node:
Steps to Reproduce:

1. Create the following js file test.js: 

    `const fs = require('fs');
    let path = 'path does not exists'; 
    console.log(fs.existsSync(path)); `
2. Run the file with node test2.js, confirm it works
3. Now run the file with the following launch.json config file:

`{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/test2.js"
        }`

**Gives the following error:** 
`Error: ENOENT: no such file or directory, stat 'random/address'
    at Object.fs.existsSync (fs.js:330:13)
    at Object.<anonymous> (/Users/alexbjorlig/Documents/SolidFlow/streamRD/test2.js:4:4)
    at Module._compile (module.js:621:14)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3`

Reproduces without extensions: Yes

I tried to debug with chrome dev tools and node --inspect --debug-brk test2.js, here it works as expected.

**Comment by roblourens** [comment]
Are you breaking on a caught exception? If not and this still reproes, please set `"trace": true` and attach the log.
