### ISSUE TITLE
Registering a FS provider with a root with an non-contributed scheme blows up explorer

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35106]
Testing #35009

1. Register a new FS provider with a root set to a URI with an unknown scheme eg `foobar:root`

Explorer doesn't render anything.

**Comment by jrieken** [comment]
@isidorn the explorer should blow up less bad

**Comment by jrieken** [comment]
generally we need to revisit the `root` story, e.g register a provider not for a scheme but for a root to begin with

**Comment by isidorn** [comment]
With this fix the explorer can still display the rest of the roots and clicking on some invalid roots shows an error
@jrieken please code review, now I am simply trying to handle the error case more gracefully in two locations

**Comment by isidorn** [comment]
After discussing with @jrieken decided to revert commit and tackle this in October with https://github.com/Microsoft/vscode/issues/34738
