### ISSUE TITLE
Smoke test: launch.json is populated with windows paths

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3511]
I think it should be ${workspaceRoot}/bin/www as that would be cross OS compatible?
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}\\bin\\www",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"address": "localhost",
			"restart": false,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
}
```

**Comment by isidorn** [comment]
We always convert to a good platform before sending to the adapter, so this launch.json we still work on mac.
Though when it is generated on the mac we nicely put "program": "${workspaceRoot}/bin/www",

I think all is good here

**Comment by alexandrudima** [comment]
I understand there's no functional bug, but check out other json files where we represent paths, such as `package.json`, `settings.json`, etc.

For consistency I believe we should generate `.json` files with `/`.

**Comment by isidorn** [comment]
Being consistent makes sense

**Comment by weinand** [comment]
Yes, please use forward slashes.

**Comment by alexandrudima** [comment]
Nice!
