### ISSUE TITLE
Scrollbar slider should have a min height

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35116]
Testing #34868

[emoji-test.txt](https://github.com/Microsoft/vscode/files/1333136/emoji-test.txt)

* save this file as UTF8 with bom (I think it is already)
* configure `"terminal.integrated.scrollback": 5000`
* run `chcp 65001`
* run `cat emoji-test.txt`
* Obseve: the scrollbar slider becomes very small and it is difficult to grab it with the mouse
* It would be nice if the mouse cursor would not be an `I` or if it would give hover feedback:

![slider](https://user-images.githubusercontent.com/5047891/30861829-46c29fc2-a2cc-11e7-93d7-41c7309522bb.gif)

**Comment by YannickMeeus** [comment]
I'd like to pick this up, if possible.
