### ISSUE TITLE
Scrolling via mousewheel in the terminal scrolls by a lot on Windows (~12 lines)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35111]
Testing #34868

Scrolling using the mouse wheel appears to scroll a constant number of lines, regardless of the terminal height, which can become very confusing:

[emoji-test.txt](https://github.com/Microsoft/vscode/files/1333136/emoji-test.txt)

* save this file as UTF8 with bom (I think it is already)
* configure `"terminal.integrated.scrollback": 5000`
* run `chcp 65001`
* run `cat emoji-test.txt`

This is using all the defaults:
* the editor scrolls by ~5 lines
* native PowerShell scrolls by ~3 lines
* our integrated terminal scrolls by ~12 lines

For example, in this case, scrolling via mouse wheel once has jumped over "Venezuela", which is very confusing:
![terminal-scroll](https://user-images.githubusercontent.com/5047891/30861570-66a1a258-a2cb-11e7-8e65-48856c555ed8.gif)

**Comment by Tyriar** [comment]
Might be related to https://github.com/Microsoft/vscode/issues/35191

**Comment by alexandrudima** [comment]
I was scrolling with an external mouse, not with the Surface Trackpad.

**Comment by jfftck** [comment]
I am also seeing this issue and when the terminal is only 8 lines tall it skips large sections. This causes me to not know where I am in the output.

Could smooth scrolling be added as a setting to give a temporary fix for this issue? At least I would be able to see the lines as they scroll by.

**Comment by Tyriar** [comment]
I believe this is fixed in the latest version of [Insiders](https://code.visualstudio.com/insiders/), it now correctly scrolls depending on the mouse's configuration by the pixel/line/page amount.
