### ISSUE TITLE
Selection in the terminal does not reflect mouse position

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35114]
Testing #34868

[emoji-test.txt](https://github.com/Microsoft/vscode/files/1333136/emoji-test.txt)

* save this file as UTF8 with bom (I think it is already)
* configure `"terminal.integrated.scrollback": 5000`
* run `chcp 65001`
* run `cat emoji-test.txt`
* scroll to `British Virgin Islands`
* try to select with the mouse:

![mouse-position](https://user-images.githubusercontent.com/5047891/30861679-d22fae7a-a2cb-11e7-8e79-d5068e25ad1b.gif)

**Comment by Tyriar** [comment]
@alexandrudima you were testing the latest unsigned Insiders correct? I thought I fixed this issue a few days ago.

**Comment by alexandrudima** [comment]
Yes @Tyriar . Did you attempt to reproduce with the steps I have provided ?

**Comment by dbaeumer** [comment]
Reopening. There is still something funny. Following the steps provided by @alexandrudima I can't select from right to left trying to start with the `s` of `British Virgin Islands`. 

And there is more if I select `British Virgin Islands` from left to right and the copy it and past it it is missing `ds` at the end.

**Comment by Tyriar** [comment]
@dbaeumer I can't repro not being able to select starting at the s, but I can see the copy paste issue. Working on it now.

**Comment by Tyriar** [comment]
Fun fact: Terminal.app has some similar bugs, this selection will only copy the flag and the reflow is off for emojis with several code points like this.

<img width="564" alt="screen shot 2017-09-29 at 2 54 03 pm" src="https://user-images.githubusercontent.com/2193314/31031254-2745f782-a526-11e7-8549-a08d18cba374.png">

**Comment by Tyriar** [comment]
Pushing this to October, I have a fix for it but it's quite large. Since it only affects characters after an emoji on a line it shouldn't be hit too often.

**Comment by Tyriar** [comment]
https://github.com/sourcelair/xterm.js/pull/1017

**Comment by roblourens** [comment]
Should the flags be shown in the terminal? They are shown in the editor. The other emoji symbols further up in the file are visible.

**Comment by roblourens** [comment]
Mouse selection works, but I filed #37440

**Comment by Tyriar** [comment]
@roblourens many emojis won't show up the same, this is as designed due to the how the terminal splits some emojis into separate characters/cells
