### ISSUE TITLE
[Feature Request] Send text to current terminal to run

### ISSUE THREAD

**Issue by Retorz** [Microsoft/vscode#35113]
Dear Team,

Integration with Terminal is a killing feature for VSC, and interaction between text editing and terminal would be better.
When working with VSC, I always keep both text editing window and terminal active. For example: connect to remote hive in the terminal meanwhile write some hql script in text window. Or some thing like writing python script meanwhile connect to ipython in terminal. I have to keep coping from text and pasting into terminal all the time

I think send selected text directly to current terminal maybe a better way to achieve REPL and inteactive programing.

**Comment by Tyriar** [comment]
Commands are already available for this 😃 

<img width="730" alt="screen shot 2017-09-28 at 9 29 42 am" src="https://user-images.githubusercontent.com/2193314/30969174-98295d56-a42f-11e7-982f-f62301763689.png">

Run selected text will run the current line if there is no selection. You can attach custom keybindings to them if you use them frequently.
