### ISSUE TITLE
reload after extension installation makes ssh connection in terminal disconnect

### ISSUE THREAD

**Issue by Retorz** [Microsoft/vscode#35118]
After extension installation, I have to reload to make it working, but my remote connection(ssh, ipython, beeline) in terminal disconnected the same time.

**Comment by Tyriar** [comment]
When VS Code closes, all terminal processes are terminated as well. If this was not the case then processes would be leaked. Here are your options:

- Use tmux to retain the terminal session
- Set the `terminal.integrated.confirmOnExit` setting to true which will warn you on exit if you have any terminal sessions active

Related: https://github.com/Microsoft/vscode/issues/20013
