### ISSUE TITLE
Screen reader detected window in top left corner

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35129]
OS X, voice over

I can not repro this again sorry! But the steps were something like this
1. Start vscode, voice over nicely detected
2. Close the vscode
3. Turn off voice over, start vscode again, notice the dialog in the top left corner

![screen shot 2017-09-26 at 16 13 52](https://user-images.githubusercontent.com/1926584/30865129-0b091cfe-a2d6-11e7-8de4-bdfd8a5f52d8.png)

**Comment by alexandrudima** [comment]
@isidorn I was able to reproduce by starting and closing voice over. I fixed it via 6ba46ec7d979b0b52170ace3b18c48aea88e9dd5

Please let me know if you see this again (after 6ba46ec7d979b0b52170ace3b18c48aea88e9dd5)
