### ISSUE TITLE
Smoke test: Cannot navigate to error produced by task

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#3512]
In the smoke test repo, run the build (Ctrl-Shift-B)

You get 9 more errors in \routes\index.js (<-- NOTE THE LEADING \)

I cannot click on them as the file does not exist

![image](https://cloud.githubusercontent.com/assets/5047891/13359094/b236bfae-dcb2-11e5-8dfd-6da725a5aa4a.png)

**Comment by joaomoreno** [comment]
Document in README

**Comment by dbaeumer** [comment]
Documented in readme for Februar release
