### ISSUE TITLE
Emmet activates on * and take 150ms to do that

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35120]
Two things aren't clear to me

* why does emmet activate on *?
* why does it load for 150ms?

<img width="847" alt="screen shot 2017-09-26 at 15 15 14" src="https://user-images.githubusercontent.com/1794099/30862232-9c38307e-a2cd-11e7-9710-ceeb3559bc6c.png">

**Comment by ramya-rao-a** [comment]
There is a setting that lets users map a language of their choice to one of the emmet supported languages to get emmet completions.

Therefore, I dont have fixed set of languages to use the "activate on language" feature.

That's the reason for activating on star.

As for why it takes over 100ms to load... am not sure. Will have to look into it

**Comment by jrieken** [comment]
> There is a setting that lets users map a language of their choice to one of the emmet supported languages to get emmet completions.

But you still need an editor for being used, right? You could use some the commands that do that to active

**Comment by ramya-rao-a** [comment]
@jrieken Yes I need the editor. 

> You could use some of the commands that do that to active

I don't follow... As in the user has to run some emmet command which can activate the extension and only then use the completion feature?

**Comment by ramya-rao-a** [comment]
Updated to activate on "type" instead.

**Comment by ramya-rao-a** [comment]
@jrieken The code loading time doesnt appear to be big enough to matter anymore. Closing this issue

**Comment by ramya-rao-a** [comment]
@jrieken Due to https://github.com/Microsoft/vscode/pull/36876#issue-268289895, I had to remove the `onCommand:type` as the activation event for Emmet and we are back to square 1 using *

Is it possible to have an activation event corresponding to the trigger of completion? If yes, then I can use that instead of *

**Comment by jrieken** [comment]
Yes, `onCommand:editor.action.triggerSuggest`

**Comment by ramya-rao-a** [comment]
@jrieken That works only when manually triggering completions. The quick suggestions dont use this command

**Comment by ramya-rao-a** [comment]
@jrieken There is one main module that I load for emmet. With https://github.com/Microsoft/vscode/commit/81cca6cc606eeca3443998025bff3893fcfe3ad5, I've made it so that it gets lazy loaded. With this codeLoadingTime taken by emmet during startup is under 50 ms.
