### ISSUE TITLE
Emmet suggests tags when trying to add attributes when there is no closing tag

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35128]
- VSCode Version: 1.16.1 c[ 27492b6bf3acb0775d82d2f87b25a93490673c6d ]
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. said `<img sr`

Result:

`<img <source>`

What should it do?

suggestion `<img src="">` (also tooltip).

![screenshot_68](https://user-images.githubusercontent.com/31345346/30864514-1a144f4a-a2d4-11e7-9dbd-32cddf66abb9.png)
![screenshot_70](https://user-images.githubusercontent.com/31345346/30864512-19f8748c-a2d4-11e7-9766-8821a024359d.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@ramya-rao-a Any chance you can filter 'src' at this location? The location is inside a tag and shouldn't be proposed.

**Comment by ramya-rao-a** [comment]
If the `img` tag were closed then this doesnt happen. The parser I am using identifies the cursor position to be inside the open tag and emmet will not suggest anything.

But here, the opening tag for `img` is not closed. And so the parser doesnt identify it as a node..

**Comment by obedm503** [comment]
also facing this issue. it's gets pretty annoying after a while. also happens when typing inside an attribute's value and isn't limited to `img` tags

**Comment by ramya-rao-a** [comment]
I have pushed a fix for this.
Please give the Insiders build for Dec 4th 2017 a try.

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Test both the `Emmet: Expand Abbreviation` command and the emmet completions
- Apart from the case here (Open tag not closed yet), try from all other possible locations in an html file. Inside open tag, in between open and close tag, after attributes etc.

**Comment by octref** [comment]
@ramya-rao-a Does not seem to handle it at outermost position:

![image](https://user-images.githubusercontent.com/4033249/33686951-59778c9e-da8b-11e7-90d8-246cefec989d.png)

**Comment by ramya-rao-a** [comment]
Good catch @octref 
Fixed with https://github.com/Microsoft/vscode/commit/a1b377e423018836b7e8a1d1733b8044136ed59c
