### ISSUE TITLE
jsdoc-param completions should keep order

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35124]
* have the code snippet below
* invoke completions for the param name
* the proposals should be sorted in order in which they are defined

```ts
/**
 * 
 * @param 
 */
function fofofo(zzz: number, bü: boolean, a: string) {

}
```

<img width="626" alt="screen shot 2017-09-26 at 15 48 38" src="https://user-images.githubusercontent.com/1794099/30863854-60e60f50-a2d2-11e7-9f22-342130cce6cf.png">

**Comment by joelday** [comment]
@jrieken, @mjbvz This is OT, unsure where to bring this up. I'm considering EoL'ing vscode-docthis in favor of contributing to improving the native support. Thoughts?

**Comment by jrieken** [comment]
It's always sad to see an extension go but I think it's fair. TypeScript is evolving quickly and it'll be better if you have free cycles for new, cool stuff.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/20183 to track this request upstream

**Comment by bmsdave** [comment]
@jrieken do you use extensions in this case?
I can not reproduce this case (https://youtu.be/2oV3Jy7WDc4)
