### ISSUE TITLE
FSProvider: dependency on uri.path

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35134]
Testing #35009

The current API doesn't allow to have resources without a path since it tries to read it in some places:

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L37

**Comment by jrieken** [comment]
Yes, today we derive the *name* of a resource by using `basename` of path component of the URI. We should maybe not do that or spec that the URIs must be pretty

**Comment by jrieken** [comment]
Seems to be like that, see https://github.com/Microsoft/vscode/issues/35135. I don't think we can change anything here...
