### ISSUE TITLE
FSProvider: dependency on hierarchical paths?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35135]
Testing #35009

Maybe the Explorer has a requirement on hierarchical resources having hierarchical URIs...

**Comment by jrieken** [comment]
No clue, @isidorn @bpasero What defined the structure of the explorer model? The hierarchical stat model, or uri-path-math, or both?

**Comment by isidorn** [comment]
Getting children in the explorer is done by resolving the file [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L99)
Also getting the parent we usualy do `stat.parent` and try not to do any path smartness.
AFAIK we have no dependency on hierarchical paths, though there are probably some assumptions regarding the hierarchy hidden somewhere.

**Comment by bpasero** [comment]
@jrieken didn't you say at one point that we expect extension authors to return URIs that follow a disk scheme, e.g. there is hierarchy reflected in the URI. In other words, we would not expect URIs such as: `scheme://myserver.something/?resolve=something`

**Comment by jrieken** [comment]
> @jrieken didn't you say at one point that we expect extension authors to return URIs that follow a disk scheme, e.g. there is hierarchy reflected in the URI. In other words, we would not expect URIs such as: scheme://myserver.something/?resolve=something

Well, yes and "hello, here comes reality" maybe no. One problem was that we were not able to get @joaomoreno stats to show in the explorer and we were clueless why... So one guess was that the explorer depends on hierarchal paths. It's not clear if all providers can full-fill the requirement of such paths but it is valuable to know that we will have a hard time without them

**Comment by joaomoreno** [comment]
In my example, my URIs didn't represent the hierarchy the actual underlying model had.

**Comment by jrieken** [comment]
Closing as question, the answer seems to be "Yes, we depend on hierarchical uris..."
