### ISSUE TITLE
Not clear how editor.accessibilitySuport is tied to the ScreenReader dialog

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35130]
Currently this relationship is not quite clear. Due to this when the user in your screen reader dialog says "No" and later in life wants to get this behaior back it is hard for him - since he is not aware of the relationship between editor.accessibilitySupport and the dialog (and there is no other way to bring the dialog back).

**Comment by alexandrudima** [comment]
@isidorn If you answer with No and later in life come back to VSCode with a Screen Reader, you will hear instructions to turn it back to "Yes". Just listen for the editor aria label and follow the steps in there.
