### ISSUE TITLE
failed to execute 'setrequestheader' on 'xmlhttprequest'

### ISSUE THREAD

**Issue by ranouf** [Microsoft/vscode#35136]
Hi,

In installed the last version of Visual Studio Code (x64 1.16.1) and I have this error.
![image](https://user-images.githubusercontent.com/1764519/30868045-8d2c8390-a2ab-11e7-9ca2-dcb37b165e62.png)

I try to install Extensions.

Can you help to fix this problem?

Thank you

**Comment by joaomoreno** [comment]
#34098

Fixed in `master`, will come with the next release. 👍
