### ISSUE TITLE
Render find next/prev in the touchbar when focus is in the find widget

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#35137]

**Comment by bpasero** [comment]
@rebornix @alexandrudima the touch bar structure follows the same rules as our context menus: navigation group is first and then we order by prefix (e.g. 9_debug is currently last). 

The editor navigation commands are registered from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L411) and the debug tool bar from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L199).  

One thing to mention is that adding enough items to the touch bar that they cannot display will cause the last group of buttons to disappear. This is currently the debug tool bar. We could also think about flipping the order. 

Another thing to mention is that users can configure the default commands that appear in the touch bar for each application. By default, it shows this stripe to the right which unfortunately takes away some space:

![image](https://user-images.githubusercontent.com/900690/30869907-ab49f934-a2e2-11e7-9311-1150a9eed99b.png)

The related setting is:

![image](https://user-images.githubusercontent.com/900690/30869916-b29afbf2-a2e2-11e7-803b-ab2735cb3308.png)
