### ISSUE TITLE
Editing workspace file from within workspace doesn't really work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#35131]
- VSCode Version: 1.17 a5210bcbda97166904ce4c08ee296cb98fccfcd9
- OS Version: macOS

While testing #29871:

- open a multi root workspace
- open the workspace file as file (in order to add folder names)

Observe:
- the contents is greyed but it is possible to edit a little bit, e.g. I could add `,"name":"other"` but whitespace (newlines, spaces) wouldn't work.
- the edited file is saved, but the changes are not picked up by VS Code.
- after a "Reload window" the new folder names showed up correctly

**Comment by bpasero** [comment]
@sandy081 this is a missing event we need to add to react to changes

**Comment by sandy081** [comment]
@bpasero I am re-using the existing event `onDidChangeWorkspaceFolders` for this.  Event sends `IWorkspaceFoldersChangeEvent` that has `added`,  `removed` and `changed` workspace folders.

- Added contains newly added folders
- Remove contains removed ones
- Changed contains current changed folders (name)

**Comment by bpasero** [comment]
@sandy081 sounds ok to me, just maybe quickly verify that all listeners of `onDidChangeWorkspaceFolders` are properly handling this event. E.g not sure everyone is looking at the event specifically.
