### ISSUE TITLE
Empty hover on tab titles

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35132]
Testing #34696

Ubuntu

![image](https://user-images.githubusercontent.com/10746682/30866304-26772082-a2d9-11e7-88ee-e444d8862727.png)

**Comment by isidorn** [comment]
@sandy081 make sure this is not a VM issue and veify that the hover otherwise works

**Comment by sandy081** [comment]
Ignore it.

I no longer see this issue.
Not sure what was wrong.

**Comment by isidorn** [comment]
The VM hover breaks down from time to time. A known vm issue I hit all the time
