### ISSUE TITLE
Extensions viewlet gets cleared on workspace folder add

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35133]
1. Open extensions viewlet -> notice installed extensions shown and recommendations
2. Explorer -> add new workspace folder
3. Back to extensions viewlet -> it is completely emtpy

Once I search for something and cancel the search the extensions viewlet gets healthy

**Comment by sandy081** [comment]
Duplicate of #35189

**Comment by isidorn** [comment]
@sandy081 my issue is older 😭

**Comment by sandy081** [comment]
Yeah...I noticed it after attaching the fix to the newer one. :(
