### ISSUE TITLE
Console.logs from command handler not linked to origin

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35140]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:11:30.780Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

Testing #34756

Steps to Reproduce:

1. Logging from activate() works as expected
2. Logging from a command handler shows extensionHostProcess.js as the origin

![image](https://user-images.githubusercontent.com/9205389/30870917-014bc036-a29a-11e7-8bfd-57c22855cb80.png)

**Comment by octref** [comment]
Same for macOS.

**Comment by bpasero** [comment]
@chrmarti @octref I cannot reproduce, are you sure you both test on latest? Can you try if it reproduces in todays build and then upload your sources somewhere?

**Comment by octref** [comment]
@bpasero 

a5210bcbda97166904ce4c08ee296cb98fccfcd9 is the one I'm using.

![image](https://user-images.githubusercontent.com/4033249/30897407-ef68c26c-a30a-11e7-9836-91df1940d647.png)

The highlighted console.log is the only change I made after `yo code` using JS template.

**Comment by octref** [comment]
Same for 67a8479bdcb95b3e21959342663b828d97f2098f released 20 min ago.

**Comment by bpasero** [comment]
Ok only happens in JS extension, the issue is this top frame that I fail to parse:

![image](https://user-images.githubusercontent.com/900690/30898240-a0f5b39c-a35a-11e7-849a-d16b9972605e.png)

**Comment by octref** [comment]
Actually still happens on Windows for this version:

- VSCode Version: Code - Insiders 1.17.0-insider (f7dc950831c601a247e08f374df8d018fbb97b5a, 2017-09-28T17:50:54.394Z)

![image](https://user-images.githubusercontent.com/4033249/30996356-412a371e-a475-11e7-9847-f8ec0a67f54b.png)

**Comment by bpasero** [comment]
@octref thanks for finding this!
