### ISSUE TITLE
Listing for Encoding Confusing

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35146]
Testing #34769 

The file encosing list helps me understand the options we include but the values in the list do not match the encoding strings...

![image](https://user-images.githubusercontent.com/1051190/30873982-dc307fbc-a2a3-11e7-9450-48af059671b0.png)

A list like the file list would be better I think where the values in brackets are the actual setting values

![image](https://user-images.githubusercontent.com/1051190/30873995-ea003be6-a2a3-11e7-83a0-30c653da4221.png)

**Comment by bpasero** [comment]
Now doing this:

![image](https://user-images.githubusercontent.com/900690/30898007-78dbb592-a359-11e7-88fa-433bf62d3011.png)
