### ISSUE TITLE
IntelliSense for File Encoding

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35144]
Testing #34769 

When creating the encoding setting I expected to see a more complete set of options in IntelliSense...

![image](https://user-images.githubusercontent.com/1051190/30873838-61c1f1e8-a2a3-11e7-8688-123a03e8fc5a.png)

Matching

![image](https://user-images.githubusercontent.com/1051190/30873850-6dda16ea-a2a3-11e7-9111-f54a9cf02d30.png)

**Comment by bpasero** [comment]
@seanmcbreen that is not how our intellisense works, it will only suggest things that match your prefix and you already typed "utf8". Am I missing something?

**Comment by seanmcbreen** [comment]
No - you are right, that was silly I know that - blush :(
