### ISSUE TITLE
Open recently closed tab/file

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#35149]
Same as in a web browser, is it awesome to reopen tabs in visual studio code.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/30895636-cfae3a06-a34b-11e7-8447-393f2f0f2477.png)

**Comment by ShalokShalom** [comment]
thx

**Comment by ShalokShalom** [comment]
I mean more like in browser, so like the people are used to it.
