### ISSUE TITLE
Dev tools do not link to origin

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35142]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:11:30.780Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

Testing #34756

Steps to Reproduce:

1. Log messages from extension
2. Origin shown in dev tools is always console.ts:112
3. The test item seems to say that the link should be to the actual origin?

![image](https://user-images.githubusercontent.com/9205389/30871674-7f15d4d2-a29c-11e7-9dc3-143ff81304e4.png)

**Comment by bpasero** [comment]
No, we cannot trick dev tools into showing something else there, that is why we show it in the expanded state with a full stack.
