### ISSUE TITLE
Console log origin not shown on Linux

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35145]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:15:18.286Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
credstore|ms-|0.0.1
github-issues-prs|ms-|0.5.0

Testing #34756

---

![image](https://user-images.githubusercontent.com/9205389/30874003-f246f272-a2a3-11e7-8313-663a7f18dce3.png)

**Comment by chrmarti** [comment]
Same with extensions:
![image](https://user-images.githubusercontent.com/9205389/30874388-042bba80-a2a5-11e7-882c-9b3edb9bf7b7.png)

Node on the PATH is v7.10.1.

**Comment by octref** [comment]
macOS seems fine.

**Comment by isidorn** [comment]
Sorry about that
Dup of #35213 with explanation
