### ISSUE TITLE
[html] do not suggest to close an already closed tag

### ISSUE THREAD

**Issue by hagailuger** [Microsoft/vscode#35143]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---
When working on html file - the editor suggets I would close an already closed tag.
Tried uninstalling and other things but it didn't work
![lswe0](https://user-images.githubusercontent.com/8089740/30873248-3385a82c-a2f5-11e7-8425-974fbe7b75aa.png).
Happened to me on other versions too.

Steps to Reproduce:
(note I'm not sure it happens to everyone)
1. create a tag. let the editor automatically create the closed tag. or close it yourself
2. start creating a tag between those two.

**Comment by Ardethian** [comment]
Same here - [https://i.imgur.com/M7IM1x6.gif](https://i.imgur.com/M7IM1x6.gif)

**Comment by aeschli** [comment]
That's the intended behaviour. I see that this doesn't make sense for <html> but for other tags (e.g. div), you might want to close is so you can open it later again.

**Comment by hagailuger** [comment]
I understand. But for this  rare scenario we sacrifice the day-to-day
scenario?
Plus, I think other IDEs don't do that.

**Comment by aeschli** [comment]
Code completion is just a coding aid. The user can pick what is needed and the user will know the order in which he/she edits.
