### ISSUE TITLE
VS Code unusable on Mac with large projects

### ISSUE THREAD

**Issue by MynockSpit** [Microsoft/vscode#35150]
- VSCode Version: Version 1.16.1 (1.16.1)
- OS Version: macOS Sierra 10.12.4 (16E195)

Opening a large project in VS Code on Mac causes other in-no-way-related programs to crash, break, or behave otherwise unexpectedly. Examples include Safari and Chrome failing to load anything, Terminal failing to even show a basic prompt, and even VS Code's Git extension failing to initialize. VS Code continues to work, until you try to save, at which point it fails to do so. Makes it unworkable for large projects.

Steps to Reproduce:

1. Create project with large number of files. My project currently has 20k+ files (that does not include npm modules BUT it does include build artifacts).
2. Observe (in Activity Monitor for example) a high thread count. It currently floats around 660 threads for me. If using Activity Monitor, observe the number of open files by CodeHelper (gets up to around 9k before crashing the log.)
3. Observe other programs failing. This includes basically every program -- browsers failing to load despite having internet, other IDEs, Terminal, Chrome extensions, even VS Code's Git extension fails.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
> Opening a large project in VS Code on Mac 

What does that mean? Do you open a large folder but no files? Do you open thousands of files? Do you  have an extension jumping onto those files or better can you reproduce when extensions are disabled (code --disableExtensions)?

**Comment by MynockSpit** [comment]
To clarify, opening a folder with thousands of files in it or its subdirectories, such that it shows up in the sidebar. You don't have to open any of those files in the editor, just load in the folder. (I think) VS Code ignores the files in common module folders (like npm) so the thousands of files can't be module files.

I've tested with and without extensions with no noticeable difference.


Realized that I didn't explain that CodeHelper is the process that is using a lot of threads.

![screen shot 2017-09-26 at 9 52 23 am](https://user-images.githubusercontent.com/5713867/30932766-50bb6656-a37d-11e7-81b4-9e76a9192bbd.png)

**Comment by bpasero** [comment]
@MynockSpit can you find out the full command line of that process?

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

**Comment by jrieken** [comment]
Also try to CPU profile this. Hit' F1 > Toggle Developer Tools'. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file, and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by MynockSpit** [comment]
Process output (from ```ps ax```): 
```
  PID   TT  STAT      TIME COMMAND
34808   ??  R      0:17.14 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
```

Here's the profile. Note that I start the profile BEFORE opening the project, and open it several seconds in.
[CPU-20170928T120032.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1342008/CPU-20170928T120032.cpuprofile.zip)

Thanks!

**Comment by bpasero** [comment]
@MynockSpit does it reproduce if you configure `"files.useExperimentalFileWatcher": true` in settings?

**Comment by jrieken** [comment]
@MynockSpit The attached profile is a zero-byte file...

**Comment by MynockSpit** [comment]
@bpasero Woah! No! That seems to solve it!

@jrieken Sorry, I didn't check. Looks like this issue also messes with the profiler -- it took ~10 attempts to get a profile that wasn't zero bytes.

Here's one that has data (although @bpasero suggestion seems to fix the problem).

[CPU-20170930T075746.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1346486/CPU-20170930T075746.cpuprofile.zip)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3998
