### ISSUE TITLE
Explorer does not navigate to current file on first open

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#35152]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:15:18.286Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Open vscode in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.
2. Open `abs/index.d.ts` and `zip.js/index.d.ts` as tabs.
3. Close the explorer (View -> Toggle side bar)
4. Observe that when you re-open the explorer (View -> Explorer), you're navigated to whatever file you're currently editing.
5. Now close the explorer and exit vscode.
6. Now open the explorer again. You're not navigated to the current file.

This worked in vscode `1.16.1`.

**Comment by isidorn** [comment]
Doing git bisect the following commit caused this https://github.com/Microsoft/vscode/commit/f5202f12170a3f95189dd647117d5ac2cd83052a

@joaomoreno please code review. The commit fixes this issue (that my viewlet is called `setVisible` before it is fully constructed.

**Comment by joaomoreno** [comment]
I don't understand how your commit fixes it. Or even why you are using `await ... .then(...)`. 😕

**Comment by isidorn** [comment]
@joaomoreno thanks for the feedback. I have refactored the code to do the same thing but now should be more readable. Let me know what you think

**Comment by joaomoreno** [comment]
Ah! You are returning `this.updateViews()`. Excellent.
