### ISSUE TITLE
Copy path of active file should not show in command palette for virtual documents

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#35156]
**Steps to Reproduce:**

1. Open release notes in the editor
2. Look for `Copy path of active file` in the command palette

**Bug**
This command does not apply for virtual text documents like the release notes and should not be shown in this case.

**Comment by isidorn** [comment]
[Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L191)
We would need a context key that is active if the open file is not a virtual docuement. Not sure if we have this, @bpasero would know better

**Comment by ihalip** [comment]
I'm going to look at this one.

**Comment by fernandreu** [comment]
Do you still need help for this? I was doing some tests about it, mostly to get familiar with the code in the process. I could not see an appropriate context key for that, so I added one at editor/common/editorContextKeys.ts, and updated the corresponding file actions and commands to make user of it. However, the only way I found to set the value of that context key was on the `MainThreadDocumentsAndEditors._onDelta` method (if `delta.newActiveEditor === null`, I assumed you have either a virtual document or no document at all). It seems to work, but I am guessing there might be better ways of implementing this.

If this could be helpful, I can prepare a pull request.
