### ISSUE TITLE
Find results in markdown preview has different highlight color than normal editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35159]
Testing #33296

On the left is the editor with a markdown file, on the right is the markdown preview.
The find results have very different highlights.

![image](https://user-images.githubusercontent.com/16890566/30876861-bc0a6686-a2ac-11e7-8e4a-942aef857ec4.png)

**Comment by mjbvz** [comment]
Duplicate of #31689. We currently have no way to control these colors.
