### ISSUE TITLE
Cannot save an empty Untitled File

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35154]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:15:18.286Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
credstore|ms-|0.0.1
github-issues-prs|ms-|0.5.0

---

Steps to Reproduce:

1. Ctrl + N
2. Ctrl + S
3. Expect Save dialog, but nothing happens. I think that used to work.

Also on Mac.

**Comment by chrmarti** [comment]
Also after changing the initially empty file.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/35083
