### ISSUE TITLE
Resizing terminal messes up cursor position

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#35155]
#34868

Ubuntu only. 
![sep-26-2017 11-05-41](https://user-images.githubusercontent.com/323878/30876207-c148edc2-a2aa-11e7-865b-7d1bbcada1d0.gif)

**Comment by roblourens** [comment]
Also:

![sep-26-2017 11-07-48](https://user-images.githubusercontent.com/323878/30876277-f3a6aade-a2aa-11e7-92a3-10889157745f.gif)

Also is fixed on the next keypress. So I don't think these are high priority issues.

And don't worry about all the blinking, it's from parallels.

**Comment by Tyriar** [comment]
Reflow would have changed this a bit, plus it generally happens on other terminals
