### ISSUE TITLE
accessibility: allow me to jump quickly to various debugger treeviews

### ISSUE THREAD

**Issue by derekriemer** [Microsoft/vscode#35153]
As a keyboard only user, I'd like to quickly be able to jump to the variables, or watch area of the debugger.

1. I press f5 to start debugging. A breakpoint is hit, I am placed on the line. If I want to investigate the variables, breakpoints, or call stack, I have to control+shift+d, then tab several times. Then, I press f11 to step in, or f5 to continue, ...
2. Now, my cursor is thrown into the editor, and I have to repeat those multiple tabs to get back to the variables/call stack/watching.

I propose a keyboard shortcut to quickly ump to the variables area, and/or making it possible to move between the debugger areas with less keystrokes if possible (By putting buttons into toolbars I can arrow along).

**Comment by isidorn** [comment]
@derekriemer Thanks for the feedback. I propose introducing some new actions in the command pallete like
* Debug: focus variables
* Debug: focus watch expressions
* Debug: focus callstack
* Debug: focus breakpoints

These actions would have no keybinding by default, but a user could assign any keybinding to those actions.
Does this make sense? I am open for suggestions.

**Comment by derekriemer** [comment]
Yes, that would be great. Also, is there a "focus last focused editor" action? sometimes, if I am in variables I want to focus the last editor, but I forget what group it's in, so ctrl+num is a guess.

**Comment by isidorn** [comment]
@derekriemer yes there is "Focus Active Editor Group"

**Comment by isidorn** [comment]
@joaomoreno is there currently some way for me to get an instance of a registered viewlet view?
You can see from this feature reuqest that I would need to get my views in an action in order to focus them.

Currenly the only thing I found is this which seems very internal
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L550

**Comment by derekriemer** [comment]
oh, wow, that's useful

**Comment by joaomoreno** [comment]
@isidorn Yeah that's the problem with the registry... But yes, you should either call `this.getViews()` and look for the one in there or `this.getView(id)`, both from the `DebugViewlet`.

**Comment by isidorn** [comment]
@joaomoreno got it. Would you mind if I change the focus of the composite to take the optional ID of the view when focusing? This way I could make everything flow through nicely
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/composite.ts#L49

**Comment by EbXpJ6bp** [comment]
@isidorn can you delete comment of the localize point?
In transifex, this key has not the "Debug". This comment may be confusing.

![c182c10f4da7078060247f8f6254f0dc](https://user-images.githubusercontent.com/8474118/31486479-9377940a-af72-11e7-8fb8-cb850f5a3ef2.png)

**Comment by isidorn** [comment]
@EbXpJ6bp done via 5f2bd928eb

**Comment by EbXpJ6bp** [comment]
@ichiriac I'm sorry I didn't make it clear enough...
Focus Variables, Focus CallStack, Focus Breakpoints are also same situation.
