### ISSUE TITLE
Intellisense not working with TS and dynamic exports

### ISSUE THREAD

**Issue by ludohenin** [Microsoft/vscode#3515]
Intellisense doesn't work when doing:

file1.ts

``` es6
export = {
  x: 1
}
```

file2.ts

``` es6
import {/* No suggestions */} from './file1';
```

**Comment by mjbvz** [comment]
Looking at the current TypeScript docs, it looks like `export = ` must be used with `import x = require('module')`https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#export--and-import--require )

Closing as-designed
