### ISSUE TITLE
Terminal selection position still feels off from the mouse position, when zoomed

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35157]
Testing #34868

I see #35114 but this doesn't involve any special characters.

This is zoomed just one level. When I'm right on the text, it selects the correct line. If I shift down just a little, it selects the next line when it feels like it should select the same line.
![sep-26-2017 11-17-01](https://user-images.githubusercontent.com/323878/30876712-4612d558-a2ac-11e7-9de9-022b5114dca0.gif)

It feels perfect when not zoomed.

**Comment by roblourens** [comment]
Still better than Outlook on Mac

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35114
