### ISSUE TITLE
Once debug test failed due to an exception, the "debug test" and "run test" links are gone.

### ISSUE THREAD

**Issue by leechen** [Microsoft/vscode#35167]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
python|don|0.7.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.0
gitblame|wad|2.2.0
---
Once debug test failed due to an exception, the "debug test" and "run test" links are gone. Have to restart VS Code to be able to debug again.

Steps to Reproduce:

1. Write a unit test which fail or throw an exception.
2. Click debug test link and let it run to finish.
3. Try debug the test again, but there is no links to "debug test" or "run test"

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
What language are you debugging?
What do you mean by debug test link? 
Can you also reproduce this without extensions?
Can you share a gif that shows the issue

**Comment by leechen** [comment]
C#. .net core 1.1. C# plugin installed.

**Comment by isidorn** [comment]
Please file this against the C# extension
