### ISSUE TITLE
Typescript - Generates imports with double quotes, immediately suggests using single quotes

### ISSUE THREAD

**Issue by TroelsL** [Microsoft/vscode#35166]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.9
vscode-docker|Pet|0.0.18
angular-cli|pko|1.0.1

---

Steps to Reproduce:

1. Create a typescript file and class where you reference a missing using.
2. Use the refactoring tools to generate the import statement.

The generated code is:
   `import { HarmonyService } from "./harmony-service";`
But VSCode immediately suggests fix: " should be '.

It should probably just have generated 
    `import { HarmonyService } from './harmony-service';`

**Comment by mjbvz** [comment]
Thie suggested fix comes for tslint, not VSCode itself.

If you are using TS2.5+ this quote style should be inferred from the other imports in the file. If there are no other imports, we always default to using double quotes. Please let me know if you don't see the correct quote style being inferred
