### ISSUE TITLE
Latest insider build?

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode#35168]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
prettier-vscode|esb|0.23.1
vscode-console-wrapper|fab|0.4.0
debugger-for-chrome|msj|3.3.0
vscode-icons|rob|7.14.0

Is there a link somewhere that will show the latest insider build that has been pushed out?

I'm not sure if a new build just hasn't been pushed out in the last 6 days or if the updater is broken in my install.  It would appear that I'm using a build that was pushed on on 9/20, and when I check for updates it states there are no updates available.

Without being able to determine the latest actual released build it's hard to know if there is a problem or not.  If that information is _not_ currently available somewhere it might be a good idea to post it somewhere.

**Comment by pocesar** [comment]
from time to time, the CI breaks, happens with Typescript nightly as well (many days without releases). it will eventually work again

**Comment by dlong500** [comment]
I get that things break from time to time, but is there a way to see what the latest released insiders build actually is?  Without that information how are we to know if our local build is broken or if there just hasn't been a new release pushed out?

**Comment by mattacosta** [comment]
I've been looking at new issues tagged with "insiders" and checking their SHA tag. Looks like mac and linux users are on a5210bc published today, so yeah, the Windows build is stuck.

**Comment by dlong500** [comment]
Still a bit perplexed about this.  @mattacosta I thought the same thing, but issue #35195 shows someone on Windows with the https://github.com/Microsoft/vscode/commit/a5210bcbda97166904ce4c08ee296cb98fccfcd9 build from 9/26.

I tried reinstalling manually and still end up with the same 9/20 build, so I have no idea how the poster of that other issue got a later build unless they somehow have *inside* access to insiders builds 😛

**Comment by mattacosta** [comment]
Just tried that myself. Deleting these folders had no effect either:
- `AppData\Roaming\Code`
- `AppData\Roaming\Code - Insiders`
- `%TEMP%\*`

Guess we'll just have to wait it out.

**Comment by tmknight** [comment]
The Windows x64 version to downloaded from the Insiders page is also from 20-Sep.  Linux is from today (27-Sep).

**Comment by sandy081** [comment]
Yeah, we are facing some signing issues. Hence the updates are not there. If interested, I would point to the unsigned bits which you have to manually download and install.

Here are the links to latest insiders bits 

MacOS: https://az764295.vo.msecnd.net/insider/67a8479bdcb95b3e21959342663b828d97f2098f/VSCode-darwin-insider-unsigned.zip

Windows 64: https://az764295.vo.msecnd.net/insider/e059563fb6b8905de79ac4c75be537bb6dc74f5f/VSCodeSetup-x64-1.17.0-insider.exe

**Comment by tmknight** [comment]
Ha, installed unsigned, then auto-check for update, put it right back to 20-Sept...oh, well, I'm certain you'll sort out the certs...

**Comment by dlong500** [comment]
@sandy081 I understand that you recognize the problem, however I'm not sure why this issue is closed given that the problem still exists (now going on 9 days).

**Comment by dlong500** [comment]
Looks like it's fixed!  I just got an update notification and installed build 7ac1f1e05baad03d4dd8f8515f1e598180b2c97e from today (9/30).  Thanks!

**Comment by ddotlic** [comment]
@dlong500 @sandy081  It might be "fixed" for Windows, but it's still not fixed for macOS.

At lest for me - on High Sierra - the latest is still reported as Sep 20th one.

Looking at the release schedule where

> insider must be at least 24h in the wild before ...

I don't think this'll go well seeing how some people still can't get the latest version.

And I'll second again @dlong500 request: where can we see which version _should_ be the latest one?

Guys, _we're helping you debug this_, that's why we're using insider channel. Help us help you.

**Comment by ddotlic** [comment]
> I've been looking at new issues tagged with "insiders" and checking their SHA tag. Looks like mac and linux users are on a5210bc published today, so yeah, the Windows build is stuck.

I'm on a mac, upgraded to High Sierra on 29th, before and after - still - am stuck on 20th of Sep version. I _think_ Linux users are using unsigned version and as such are on latest, but I assure you **some** (all?) macOS users are **not** up to date.

**Comment by Sweetman** [comment]
On mac as well and still stuck on f7962f0

**Comment by ddotlic** [comment]
Guys, it seems they've fixed the issue for mac users as well, I've just updated to the today's build (Oct 3rd). 🍾 🎉
