### ISSUE TITLE
Cannot read property 'type' of undefined, when not selecting anything from "Start Debugging" menu

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#35163]
- VSCode Version: 1.16.1
- OS Version: Windows 7 Build 7601

Steps to Reproduce:

1. Press <kbd>F5</kbd> **OR** go Debug ⇒ Start Debugging
2. Dismiss the menu that appears: press <kbd>Esc</kbd> **OR** click outside the menu

Reproduces without extensions: Yes

Exception:
![image](https://user-images.githubusercontent.com/451903/30877719-7051b1f4-a2f2-11e7-8337-8e7f09742763.png)

<pre>

**Comment by isidorn** [comment]
This is already fixed in latest vscode insiders
You can download and try it out here https://code.visualstudio.com/Insiders/
