### ISSUE TITLE
wrappingIndent not consistently working

### ISSUE THREAD

**Issue by slaughtr** [Microsoft/vscode#35162]
- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6 (Sierra)

Steps to Reproduce:

1. Open a large file or create one
2. Use these settings: 

 ```
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.fontSize": 14,
    "editor.wordWrap": "on",
    "editor.acceptSuggestionOnEnter": "off",
    "workbench.activityBar.visible": true,
    "terminal.external.osxExec": "iterm.app",
    "window.zoomLevel": 1,
    "workbench.sideBar.location": "left",
    "workbench.statusBar.visible": true,
    "extensions.ignoreRecommendations": false,
    "editor.dragAndDrop": false,
    "editor.links": false,
    "bracketPairColorizer.forceUniqueOpeningColor": true,
    "bracketPairColorizer.forceIterationColorCycle": true,
    "bracketPairColorizer.consecutivePairColors": [
        ...
    ],
    "editor.fontFamily": "Input",
    "editor.fontWeight": "100",
    "editor.wrappingIndent": "indent",
    "editor.wordWrapColumn": 100
```

Reproduces without extensions: Yes

Here's an image that illustrates the inconsistencies (sorry I had to block some things out):
[Screenshot](https://i.imgur.com/txkGPe6.jpg)

As you can see, all the things at the bottom of the editor are wrapping and indenting correctly, but many lines above are wrapping and not indenting at all. Sometimes they wrap, sometimes they don't. It's even more inconsistent (and impossible to work with) if I have the file explorer open (can provide another screenshot if needed, but honestly, it's impossible to tell what's going on as indentation is so all over the place).

This happens whether I have editor.wrappingIndent set to indent or same, and without extensions loaded. It's very frustrating and can make some files a huge PITA to edit (it seems that after about 5 indentations things get weird, and almost everything I'm working with is in the 8-20 indentation range).

Edit: after playing around, it seems the wrappingIndent definitely breaks at 10 indents every time, but the presence of anything over 9 indents seems to cause the weird inconsistencies with other lines/indent amounts. This, again, becomes painfully hard to deal with if the file explorer is open.

**Comment by alexandrudima** [comment]
@slaughtr The wrapped line gets "unindented" if indentation would cover more than 50% of the line's width. That is a decent heuristic when things get very *packed* i.e. like resizing the editor to have a very small width, but, I agree, it doesn't make sense when the editor has a decent enough large width.

**Comment by alexandrudima** [comment]
before:

![kapture 2017-09-27 at 11 16 48](https://user-images.githubusercontent.com/5047891/30905537-62fb1de6-a375-11e7-84f6-ecb831ef94d7.gif)

after (still happens, but only when the indent would be so large that no characters would fit):

![kapture 2017-09-27 at 11 19 59](https://user-images.githubusercontent.com/5047891/30905690-d69c3e9c-a375-11e7-868c-4d13aeb0739e.gif)
