### ISSUE TITLE
Colorful dots and lines   

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#35169]
What can this be?

![screenshot_20170926_212807](https://user-images.githubusercontent.com/6344099/30880036-9b29ff12-a301-11e7-943c-db7b16f6537a.png)

It happens in 16.1, 17.1 and 17.2 on Linux with both Intel GPU driver and KMS (generic)

**Comment by alexandrudima** [comment]
@ShalokShalom You could try `code --disable-gpu`

**Comment by ShalokShalom** [comment]
Still the same issue.

**Comment by alexandrudima** [comment]
@ShalokShalom is there any more information you could provide?
* are you running Linux in a VM?
* are you connecting to the machine via some form of remote desktoping software or are you sitting physically at the machine?
* what flavour of Linux are you using?
* Do you experience this smearing in all parts of our UI?
* Do you experience this smearing if you install Chromium and go to a website?

**Comment by ShalokShalom** [comment]
Installed KaOS
Chrome/Opera is fine
And all in the UI of VSCode, yes.

**Comment by bpasero** [comment]
Looks like an chrome/electron rendering issue to me. Do you see the same when running Chrome browser?

**Comment by ShalokShalom** [comment]
No, as said.

**Comment by ShalokShalom** [comment]
This is this the case for 17.1

I already renamed the whole .vscode folder, so I get a new one without any extensions. 
Still the same. I also deleted all the settings. All the same. 

So, this is an electron issue? How can I fix it?

**Comment by ShalokShalom** [comment]
It does not happen in the release notes page, so I guess its an Electron issue, since that one is probably not rendered with it, yeah?

**Comment by ShalokShalom** [comment]
Can I do anything about it?

**Comment by ugurozturk** [comment]
@ShalokShalom if it is electron problem then the alternatives also must have the same problem. Did you try another electron app ? Perhaps atom. Checking the result might help to develop vscode

**Comment by ShalokShalom** [comment]
Yeah, it also happens in Atom.

**Comment by ShalokShalom** [comment]
Well, this is even merged already: atom/atom#15737
