### ISSUE TITLE
Add API for interacting with TouchBar in Mac

### ISSUE THREAD

**Issue by varunkumar** [microsoft/vscode#35164]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
quokka-vscode|Wal|1.0.66
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-eslint|dba|1.3.2
vscode-instant-markdown|dba|1.3.0
gitlens|eam|5.2.0
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.16
vscode-styled-components|jpo|0.0.8
vscode-ai|ms-|0.1.1
debugger-for-chrome|msj|3.3.0
vetur|oct|0.9.10
proto|pet|0.0.2
vscode-versionlens|pfl|0.19.1
polymer-ide|pol|0.6.0
testcafe-test-runner|rom|1.2.0
google-input-tools|var|0.0.3
vscode-import-cost|wix|2.5.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

---

This is a feature request. I would like to have a first class API to play with TouchBar. Perhaps, a subset of whatever Electron offers. I feel its very restrictive to have access to TouchBar via `contribution points` only. I wrote an extension which uses `completionProvider` and I want my suggestions to show up on TouchBar. This is not possible currently with the support added in https://github.com/Microsoft/vscode/issues/14653

**Comment by felipenmoura** [comment]
I find it very important.
I really like VSCode and it has become the first editor to offer support for the touchbar, what is awesome.
It's still a long way to the top, though!

I just wrote a plugin that adds features to the touchbar while you are coding.
I would like to add some comments on it:

- The Extensions APIs are very verbose and have some extra, unnecessary complexity.
- The Extensions APIs are "half documented". I barely could do what I wanted based only on the documentation. I always had to "guess" some commands or find a comment in stackoverflow.
- The support for the touchbar is still very limited. I know there are already some issues related to this, but I will mention it anyways:
  - Some times the icons appear "cropped" showing only half the button. Restarting the VSCode fixes it.
  - Cannot change buttons colors
  - Cannot change buttons sizes (neither images/icons sizes)
  - Too many buttons are "breaking" the touchbar layout and making the last ones disappear (they should be "scrollable").
  - There should be a menu to customize the buttons.

In case any of you want to take a look and point me in a better direction or perhaps, even add some feature, the repo is at: https://github.com/NascHQ/nasc-vscode-mac-touchbar
And the plugin itself is at https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar

Keep the good work :)

**Comment by sergeysova** [comment]
Some progress?

**Comment by Tsourdox** [comment]
+1
