### ISSUE TITLE
Cannot run tsc build task

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#35175]
Testing #34992.

- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:11:30.780Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
vscode-docker|Pet|0.0.18
quokka-vscode|Wal|1.0.66
regex|chr|0.1.0
crazy|kie|0.0.1
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.2.0
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
vsc-travis-ci-status|fel|1.1.0
svgpreview|kis|0.2.0
Go|luk|0.6.65
mssql|ms-|1.2.0
github-issues-prs|ms-|0.5.0
debugger-for-chrome|msj|3.3.0
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.15.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.2.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. `yo code`
2.  open the created folder in vs code
3. delete the `.vscode/tasks.json` file
4. `Tasks: Run Task` from the command palette 
5. Choose `tsc: watch - tsconfig.json`
-> Error: The process task system can only execute custom tasks.

**Comment by mjbvz** [comment]
@dbaeumer I see this with npm tasks too. The bug seems to be that `yo code` creates a `tasks.json` 0.1.0 file. This version effects the task runner even after the tasks file is deleted and prevents contributed tasks from being run. Can you please take a look at this?

**Comment by roblourens** [comment]
When you switch from 0.1 to 2, you need to reload -https://github.com/Microsoft/vscode/issues/35022

Tripped me up too, I think the error message is very confusing.

**Comment by kieferrm** [comment]
I can confirm, reloading the window solves the issue. Duplicate of #35022.

**Comment by dbaeumer** [comment]
Closing as dup of #35022. Will investigate #35022 for September.
