### ISSUE TITLE
Watch task spinner never goes away

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35174]
Testing #34953

- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:15:18.286Z)
- OS Version: Linux x64 4.4.0-83-generic

- Follow instructions in #34953 for the first gulp watch task, and also the later tsc watch task, using the `$tsc-watch` matcher
- When I start the watch task, the spinner appears and never goes away as long as the task is running. It should only be visible while the task is building.

Output for the second one is

```
> Executing task in folder tasks-tsc: npm run watch <


> tasks-tsc@1.0.0 watch /home/parallels/code/tasks-tsc
> tsc -w -p .

test.ts(1,9): error TS2551: Property 'logg' does not exist on type 'Console'. Did you mean 'log'?
2:07:16 PM - Compilation complete. Watching for file changes.
```

**Comment by dbaeumer** [comment]
The task must be marked as "isBackground". Otherwise the system doesn't know that the task is a background task. 

We should try to auto detect this which is covered by https://github.com/Microsoft/vscode/issues/29586.

Marking as dup.
