### ISSUE TITLE
Add file to .gitignore unexpectedly asks for which repo

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35176]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34963

The file is just in one repo not the other, I'd expect that to be picked, not to be asked:
![image](https://user-images.githubusercontent.com/9205389/30885191-2ea9bf6a-a2c7-11e7-9db3-259896a1a056.png)

**Comment by joaomoreno** [comment]
Great catch!
