### ISSUE TITLE
how to set php.validate.executablePath if I want to use php on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by erdemece** [Microsoft/vscode#35170]
I am trying WSL and vscode. I would like to use php that I installed on wsl  with vs code. I used [this ](https://github.com/Microsoft/BashOnWindows/issues/1946#issuecomment-295583000)solution to add php into windows path but I am not sure how set php.validate.executablePath in this scenario. is this possible? can anyone help please?

Thanks.

**Comment by roblourens** [comment]
If it doesn't work with that fix to add bash php to your path, then I don't think it will work. But that workaround is basically what I think you'll have to do - tell bash to invoke php with some parameters. I don't really know what those parameters are though, I'm not fluent in batch script.

**Comment by mjbvz** [comment]
Closing as possibly resolved / no recent followup
