### ISSUE TITLE
Similar icons for Synchronize and Refresh actions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35178]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34963

The Refresh and the Synchronize icon look very similar and are located close to each other:

![image](https://user-images.githubusercontent.com/9205389/30885440-299ccb2e-a2c8-11e7-96f8-3014aeaf86a3.png)

Because Synchronize also pushes, clicking that when intending to do the other can have unintended consequences.

I think the two icons should either be further apart in the UI, have more visual differences or both should become read-only actions.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
