### ISSUE TITLE
JS Syntax highlight snafu

### ISSUE THREAD

**Issue by meeech** [Microsoft/vscode#35172]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
solidity|Jua|0.0.29
vscode-jest|Ort|2.3.0
vscode-docker|Pet|0.0.18
code-clip-ring|Sir|0.0.4
Bookmarks|ale|0.16.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
json-tools|eri|1.0.2
prettier-vscode|esb|0.23.1
debugger-for-chrome|msj|3.3.0

---

Steps to Reproduce:

1. put the following code in a JS file
```
export let foo = (type, { ids = [], 
  page = 0}) => {
  console.log(type, ids, page);
}
```

2. See how the syntax highlighting is broken. Specifically seems to be the lf after the ids = [], that triggers the issue

Reproduces without extensions: Yes

Bad:
![image](https://user-images.githubusercontent.com/4623/30883907-b2e6b6b6-a2db-11e7-9456-4962e95a3283.png)

Good: 
![image](https://user-images.githubusercontent.com/4623/30883920-c058f03e-a2db-11e7-9179-aa9eab070cef.png)

**Comment by mjbvz** [comment]
I believe this is fixed in the latest insiders builds:

![screen shot 2017-09-26 at 2 04 59 pm](https://user-images.githubusercontent.com/12821956/30884246-be15f6c2-a2c3-11e7-8709-8f443a2e7e2f.png)
