### ISSUE TITLE
Commit Staged (Amend) asks for new commit message

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35182]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34963

Steps to Reproduce:

1. Stage some change
2. Commit Staged (Amend)
3. 🐛 I'm asked for a new commit message without the existing one as the default. I usually want to keep the existing one.

**Comment by mvmjacobs** [comment]
I would like to help with this. It will be my first time contributing to this project, so I may have some questions. Is there any suggestions where to begin?

**Comment by pradeepmurugesan** [comment]
@joaomoreno yeah may be we can add an option to keep the older message. 
```
git command line option is --no-edit
```

**Comment by ADTC** [comment]
I'm assuming this is not in version **1.18.1**.

Can I expect this in **1.18.2**? Because I'm looking for this to amend the commit properly (both the diff and the message). I keep having to go back to the command line and issue `git commit --amend` because VSCode's _Commit Staged (Amend)_ option shows a blank message.

**Comment by joaomoreno** [comment]
No, this will be in 1.19.

**Comment by nzjony** [comment]
I upgrade to 1.19, and this works, however we use gerrit which has a Change-Id in the commit message, and the newline is removed when added to the commit message box. Which means when I upload the change to gerrit, it becomes a new patchset. 
Can this please not remove the newlines.

**Comment by joaomoreno** [comment]
I see... I created this to track that issue: https://github.com/Microsoft/vscode/issues/40295
