### ISSUE TITLE
Add ability to copy formatted code to clipboard

### ISSUE THREAD

**Issue by thomas-taylor** [Microsoft/vscode#3518]
I'd like to request adding the ability to copy selected code to the clipboard with syntax highlighting? This is useful for pasting formatted code into another application (e.g., Word document, e-mail).
Regular Visual Studio does this by default (it puts both text and RTF formats on the clipboard).
RTF works well for me, but maybe HTML would be okay too, as long as it is 'pastable' (dependency-free).

**Comment by sushruth** [comment]
:+1:

**Comment by pcgeek86** [comment]
We definitely need this.

**Comment by harikrishkk** [comment]
Thumbs up!.. Would be awesome if the code can be copy pasted along with the syntax highlighting into word or ppt!.. Such a good IDE, especially with typescript + angular 2 combo , this wud be like gold for me!...Please provide syntax highlighting..

**Comment by ram7489** [comment]
Would love this feature! We regularly share code, and it would be much easier to read/understand if there's color coding and indentation.

**Comment by nicsu** [comment]
👍

**Comment by Tyriar** [comment]
You should be able to write an extension to do this, you would need to include a syntax highlighter in the extension though. I'm not sure we would want to integrate something like this into the core editor (concerned about feature bloat).

**Comment by andybrodie** [comment]
I would really like this feature.  I was quite surprised that this wasn't already supported when I tried it (I'm a Visual Studio user!).  If an extension had to do its own syntax highlighting I think that wouldn't be a great user experience, as I find how VSCode highlights absolutely fine and wouldn't want to have to manage a separate highlighter configuration.

Are you concerned about feature bloat from an end-user perspective or from the codebase itself?  I wouldn't comment on the latter, but from an end-user perspective, I enjoy the fact that it's seamless on VS.  i.e. VS copied the colour information and if I tried to paste in to an app that didn't support colour (e.g. notepad) then it just disappeared and the app behaved as if I was pasting plain text.  In apps like PowerPoint (where I regularly copy and paste code snippets!) I have the source formatting and plain text options available.

**Comment by wangbourne** [comment]
+1

**Comment by Xarkam** [comment]
:+1:

**Comment by SirwanAfifi** [comment]
:+1:

**Comment by crazyquark** [comment]
👍

**Comment by sushruth** [comment]
Is there anything that is blocking this, or is it not a desired feature ?

**Comment by ryan413** [comment]
Dear GitHub Gods,

Please add this feature.

Sincerely,
Ryan

**Comment by steveluc** [comment]
Would love to see this happen.  Great for communicating about code.

**Comment by atian25** [comment]
there is a plugin for atom: https://atom.io/packages/copy-as-rtf

and [Code highlighting for Keynote presentations](https://gist.github.com/jimbojsb/1630790)

maybe someone can write a plugin to wrap these

**Comment by atian25** [comment]
HI, I just publish one plugin for this:  

https://marketplace.visualstudio.com/items?itemName=atian25.copy-syntax

**Comment by ram7489** [comment]
Hey, thanks, Atian! We'll check it out!

**Comment by johncruise** [comment]
Hello @atian25, 

Thanks for the extension but it copies the text and put "literal" RTF signatures/tags (whatever people call them) around it.  So when I paste the code, I get something like this:

```
{\rtf1\ansi\uc0\deff0{\fonttbl{\f0\fmodern\fprq1\fcharset0 Monaco;}}{\colortbl;\red136\green136\blue136;\red186\green33\blue33;\red0\green68\blue221;\red102\green102\blue102;\red64\green128\blue128;\red160\green160\blue0;\red25\green23\blue124;\red0\green128\blue0;\red187\green102\blue136;\red187\green102\blue34;\red136\green0\blue0;\red170\green34\blue255;\red153\green153\blue153;\red0\green160\blue0;\red160\green0\blue0;\red255\green0\blue0;\red128\green0\blue128;\red176\green0\blue64;\red0\green0\blue255;\red187\green187\blue187;\red188\green122\blue0;\red0\green0\blue128;\red125\green144\blue41;\red210\green65\blue58;}\f0 \fs50{\chbrdr\chcfpat16 @}unittest.skipIf(mock is None, {\cf2 "`mock` module not installed!"})\par
```
... when I am expecting a color coded text similar to below:

```python
@unittest.skipIf(mock is None, ...)
```

If it helps, I'm pasting it into an blank Outlook email window.  For those who want an interim solution, look at Notepad++'s NppExport plugin (Copy HTML to clipboard)

![croppercapture 2](https://cloud.githubusercontent.com/assets/135095/19371266/94bdf492-9166-11e6-87a7-fc25332e31dc.Gif)

**Comment by atian25** [comment]
hey, @johncruise the extension is use `pygments` behind, and  it offer [HtmlFormatter](http://pygments.org/docs/formatters/#HtmlFormatter)

so, for now, you can:

- set `copy-syntax.defaults.format` to `html`
- maybe `copy-syntax.formatters.html.full` to `true`
- then copy and you will get html output

but, I don't know whether `copy-paste` module can copy it to clipboard with correct format (see https://github.com/atian25/vscode-copy-syntax/issues/1)

I don't have window and outlook now, could you please have a try and feed back? 

btw, you can report an issue/suggest at https://github.com/atian25/vscode-copy-syntax/issues

**Comment by atian25** [comment]
@Tyriar does vscode have any api for extension to set clipboard?

**Comment by Tyriar** [comment]
@atian25 there is no copy and paste in the API, I think the advice is to pull in a node module which does it for you.

**Comment by nashwaan** [comment]
@Tyriar This capability should be part of native VS Code experience, not as a plugin.
If anyone doesn't like the colors, he can simply select the pasted code and apply a single color to them.

How many  👍 do you need before getting convinced to implement it as part of VS code?
 ; )

**Comment by lazywinadmin** [comment]
+1  Definitely need this !!

**Comment by rebornix** [comment]
We hear your voice and I'm working on it :)

**Comment by harikrishkk** [comment]
Awesome! awesome! awesome! requesting you to make it something like the
"Copy as HTML" in one of the simple editors like Notepad++ , where,
whatever be the Theme, the copied one will also copied like the
theme!..cant wait to see the same working on VS code. I see a "Copy syntax
as" in the plugins for VS Code, but seems nothing close to the one I saw in
Notepad++ or Webstorm.

**Comment by rebornix** [comment]
@harikrishkk I enjoyed the moment that what you describe is what I did. We converted the content with theme into HTML with inline CSS then it can be as compatible as possible.

**Comment by Meligy** [comment]
Can Insiders build try the early stages of this with some flag or so?

Cheers,

**Comment by rebornix** [comment]
You should be able to see this Copy with Syntax Highlighting feature from Friday's Insider update. Please let me know if you guys find any problem with it :)

I would close this issue once tomorrow's Insider is out, thank you all for your patience and feedback.

**Comment by AroraMunish** [comment]
Getting the error  Command Failed: Python -v
![untitled](https://cloud.githubusercontent.com/assets/13214220/23059233/7f72ce3e-f51e-11e6-9e1f-d478da5e0861.png)

**Comment by andybrodie** [comment]
Thanks for the update on this and for your hard work on this feature.

Certainly looks like the fundamentals are working, font and colour information is coming across.

I tried with some Go code, pasting in to PowerPoint 2016, but it didn't paste the background correctly, as the text box it created wasn't configured with the right dimensions.  TBH I wasn't expecting the background to come across at all.

![image](https://cloud.githubusercontent.com/assets/8665087/23061741/f01904a6-f4fa-11e6-990e-802b76f745a6.png)

I also compared with VS2015 on some C# code.  VS2015 didn't attempt to take across a background and pasted white text from VS2015 as black text in to PowerPoint, taking in to account the background colour change from dark to light.  Would it be possible to mimic VS2015's behaviour with this feature as this works perfectly for what I want to achieve.

**Comment by Meligy** [comment]
I love it as it now!

I tried it in Gmail opened in Chrome, and in Word, both on Mac. The result is super impressive!

I love that it picked the background. I guess for copying to Word if you want a white background temporarily switch to a theme that matches what you want.

It picked everything, except for lint error underlines, which is exactly what I'd expect and want it to do.

Thanks heaps!

**Comment by thomas-taylor** [comment]
Looks great! Many thanks for adding this feature!

I was surprised when first testing that it includes the background (dark theme in my case).  Sometimes I don't want this, such as pasting in a report (e.g., Word document), but it is easy enough to switch themes when I want the light background.  So, the implementation is perfect for me.

**Comment by harikrishkk** [comment]
Can someone tell me the steps to try this out? I updated the visual studio
code to latest version, set the editor.copyFormat to true in settings, but
trying to copy paste still throws "command.copySyntax" not found error.

**Comment by schallm** [comment]
This works very nice.  It basically seems to mirror the VS2013 copy/paste
feature where it copies the background and does a full width paste of the
background.  If memory serves, VS2012 would copy background, but only under
the text, so when pasting you would have jagged ends of the line.  VS2015
by default copies with a nice theme (not sure if you can change it), but
must not use the current theme.  I used a dark background, but when
copying/pasting it is a white background.

Many comments are coming that we could easily change the theme if we want
to have a different look when pasting.  Would it be possible to have a
setting like editor.copyTheme in settings.json that would do that for us?

Thanks again for the great feature...

**Comment by rebornix** [comment]
@AroraMunish does that happen when you just press ctrl/cmd+c? It looks like an extension problem to me.

**Comment by rebornix** [comment]
@andybrodie I'll give Powerpoint a try on Windows, the output HTML is just simple `<div>`s so I'll see if I make anything wrong with the layout.

Speaking of VS2015, are you saying that you are using Dark theme in VS2015 and when you copy it to Powerpoint, the pasted content has white background and black font color? Does other colorization still work? A screenshot can help me understand  :)

**Comment by rebornix** [comment]
@harikrishkk Just simply Ctrl/Cmd+C without any configuration.

@thomas-taylor @schallm or anyone uses Dark theme, I'm a Dark theme guy as well. At the very beginning, I didn't put the background color from the theme into the output content, but later on I found for most cases the output is ugly or unreadable. I suppose you can imagine that as for Dark theme, the font color are always light. Light font above white background is terrible most of the time. The dark theme you are using makes sure that the background color and foreground color has good contrast so I choose to ship bkg color to the clipboard.

I can see reasons that why customizing the pasted content style is useful as sometimes you can't easily modify the styles in the target application. Look forward to more users feedback on this once we ship it to stable.

**Comment by schallm** [comment]
Here is a screenshot of VS2015 (dark theme) with code selected, copied to
clipboard, pasted to Outlook...  I don't know if they use a different theme
when copying, but it works great.  I get syntax highlighted code that looks
great, but without the dark background...

[image: Inline image 1]

**Comment by schallm** [comment]
Here is a screenshot of VS2015 (dark theme) with code selected, copied to clipboard, pasted to Outlook...  I don't know if they use a different theme when copying, but it works great.  I get syntax highlighted code that looks great, but without the dark background...

![screenshot](https://cloud.githubusercontent.com/assets/331167/23079704/9dd20f76-f513-11e6-80b5-a6b9b2399d09.png)

**Comment by thomas-taylor** [comment]
@harikrishkk - You say you have latest, but just to be sure you know, today this is only in the insider build: https://code.visualstudio.com/insiders

@rebornix - I think the way it matches the theme exactly (including background) is perfect.  Regular VS 2015 appears to switch the entire theme (for example text that is white in VS 2015 dark theme is pasted as black text in Word/Outlook).  This works fine too (for my needs), but I like your implementation in VS Code better.  That said, I also like the suggestion from @schallm to have a setting to choose the theme that you want to use for this cut/paste feature.

**Comment by harikrishkk** [comment]
Superb! I just installed the one with the insiders link! .what i previously
downloaded was the normal one from the vs code site... And i tried copy
pasting a sample to word doc! sweet!... A simple crtl+ c, and paste it!....
@thomas taylor, thanks a lot!...
[image: Inline image 1]

**Comment by AroraMunish** [comment]
When I try to copy using right click | Copy Syntax, I get the error "Command failed: python -V".  Do I need to pre-install anything?

**Comment by harikrishkk** [comment]
@munish, https://code.visualstudio.com/insiders try downloading the
installer from here and see if its working..i had the same issue when i was
just trying to take the latest of the VS code from the usual site. After
installing this build ( a green one ), it did work for me

**Comment by AroraMunish** [comment]
Thanks Harikrishnan .. it worked..

**Comment by MateenKadwaikar** [comment]
Not working with Powerpoint. I have to copy it in Word first then I have copy from word and paste in Powerpoint

**Comment by rebornix** [comment]
@MateenKadwaikar is there anyway in Powerpoint that can trigger a force copy with formatting? In Outlook on macOS, I have to do that always as the default paste is just pasting plain text.

**Comment by Meligy** [comment]
@MateenKadwaikar , +1 to @rebornix. PowerPoint has a default text based paste. From Edit menu though you can choose "Paste Special...", which will give HTML and RTF options. I have found the VS Code HTML copy to work with both.

**Comment by harikrishkk** [comment]
Is anyone facing issues while copy pasting? I get the code but indentations
is all wrong and has to put tab or space every single time. A couple of
updates before, it wasnt the case i guess.

**Comment by dalyIsaac** [comment]
+1 It doesn't work with OneNote 2016 either

**Comment by rebornix** [comment]
@dalyIsaac do you mind sharing what platform and version you are using and a gif can help me understand what's going on, thanks!

**Comment by atian25** [comment]
Guess:
- maybe vscode is copy as HTML format
- keynote only support RTF format
- word/mail support both

![untitled](https://cloud.githubusercontent.com/assets/227713/24935794/c5c57a6e-1f56-11e7-9198-d78049af1adb.gif)

**Comment by tedyun** [comment]
@rebornix Is this feature configurable? I couldn't find a setting for disabling this feature.. Unlike other people in this thread I personally prefer copying the plain text and nothing else. I also think copying plain text should be the DEFAULT behavior, like all other similar, non-IDE text editors (e.g. Atom, Sublime Text, Notepad++).

I appreciate all the effort went into enabling this feature. I hope you guys can add a boolean option in Settings file to enable/disable it.

**Comment by lukeaus** [comment]
@tedyun If you want to copy plain text: select text the Edit --> Copy
If you want to copy with syntax: select text then open command pallate and select "Copy with Syntax Highlighting"

**Comment by tedyun** [comment]
@lukeaus It doesn't work that way in my machine. Both (Edit -> Copy) and (Ctrl+C) copy the text WITH syntax highlighting. Version 1.12.2

**Comment by tedyun** [comment]
@rebornix I'd really appreciate if you can take a second look at this issue.

**Comment by rebornix** [comment]
@tedyun we put both plain text and html in clipboard and it's the target application who decides which format to paste.

**Comment by Aptend** [comment]
@rebornix when copying codes into OneNote2016, indentation(using spaces) will get lost.
![indentation](https://cloud.githubusercontent.com/assets/17057861/26542034/ef239e28-448a-11e7-9c47-6b1c0d959c6d.gif)

It seems that OneNote will ignore `'white-space: pre;'`. Get `&nbsp;` solution back, maybe?

**Comment by xgqfrms-gildata** [comment]
I'd like to using `sublime text 3`  **format paste**!

> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>

How to realize it in VScode ?

**Comment by eckdanny** [comment]
@rebornix @Meligy on Outlook for Mac (v15.35) I can get formatted text into an email if I spam the crap out of paste cmd (below)

![spam-outlook-with-cnp](https://user-images.githubusercontent.com/3521444/27981864-250a0ea4-6359-11e7-8f2f-81ba2d3bf5fd.gif)

I can detect visually a FOUC-like render of the formatted paste under normal conditions too (one can see in the screen cast too). Surely there must be a way to _disable_ the sanitizing that Outlook is doing in Outlook prefs, rt? (If anyone knows, plz share)

Definitely not a problem with VSCode... i just _really_ want to be able to paste syntax-highlighted snippets in company email 😞

**Comment by pcgeek86** [comment]
@eckdanny You don't need to spam the paste key combo. Just paste once, and then notice the little icon that appears after your paste. Click the icon and change it to "*keep source formatting*."

**Comment by darthwalsh** [comment]
@Aptend you can paste into Word, copy, and paste into OneNote. If you remove the dark text background color the text colors are too light to see, but you can change VS Code to a light theme before copying ;)

I also found a few OneNote requests in UserVoice that everybody should upvote:
- https://onenote.uservoice.com/forums/327186-onenote-for-windows-windows-phone/filters/my_feedback
- https://onenote.uservoice.com/forums/327186-onenote-for-windows-windows-phone/suggestions/6189896-respect-whitespace-tags-in-pasted-html-text-e

**Comment by SirwanAfifi** [comment]
It doesn't work with OneNote 2016!
