### ISSUE TITLE
Node debugger does not expand obj/array correctly in debug console

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#35180]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:11:30.780Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
prettier-vscode|esb|0.23.1
vetur|oct|0.9.10
vim|vsc|0.10.1

(1 theme extensions excluded)

---

While testing #34756.

![image](https://user-images.githubusercontent.com/4033249/30886017-60232a42-a2ca-11e7-997d-96e43e64f746.png)

`launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
          "name": "test",
          "type": "node",
          "request": "launch",
          "program": "${workspaceRoot}/test.js",
          "protocol": "inspector"
        }
    ]
}
```

`test.js`
```js
console.log([1, 2, 3, 4, 5])
console.log('t1', { foo: 5 })
console.warn('t2', { foo: 5 })
console.error('t3', { foo: 5, bar: 10 })

const t = {};
for (let i = 0; i < 100; i++) {
  t['attr' + i] = i;
}

console.log(t);
```

When using `extensionHost` and putting the code inside `activate`, they all expand correctly.

![image](https://user-images.githubusercontent.com/4033249/30886163-f6bdd0f6-a2ca-11e7-813f-7f8ae76be47e.png)

**Comment by isidorn** [comment]
@octref there was an issue that upon expansion of objects in repl we would throw exception and I have pushed a fix for that.
However not being able to expand while the session is terminated is expected, you can only do that while you are in a stopped state and the frontend is able to get children from teh backend debug adapter
