### ISSUE TITLE
Commit Staged (Amend) asks to stage changes and then fails

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35185]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34963

Steps to Reproduce:

1. Have some unstaged changes, none staged
2. Commit Staged (Amend)
3. Dialog asks if I want to stage the changes
4. Click Yes
5. 🐛 Message telling me that there are no changes to commit

**Comment by dKab** [comment]
Hi. I would like to try and fix this. May I?

**Comment by prog-rajkamal** [comment]
this is a duplicate of #35182

**Comment by joaomoreno** [comment]
For repro: make sure you have `"git.enableSmartCommit": false`.
