### ISSUE TITLE
Issues with default build task flow with multiroot

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35187]
Testing #34953

If I don't have a task marked as the default build task, I can configure one as in #34953 and run it, and it works fine.

But if I open two folders in a multiroot workspace that each have a default build task configured, then press ctrl+shift+b, then it just shows all the tasks with the option to select one. I would expect it to let me choose between my different default build tasks.

And another problem that I only see on my debug workspace on Mac -
- I start watch task A through the menu from cmd+shift+b
- I start watch task B also through cmd+shift+b
- A notification appears saying "The task B [...] is already active and in background mode". But it isn't active, only task A is active.

Also, I should be able to configure multiple build tasks, but when I run "Configure default build task", it shows a message that there is already a task marked as the default build task.

**Comment by dbaeumer** [comment]
Investigating for September the problem

> A notification appears saying "The task B [...] is already active and in background mode". But it isn't active, only task A is active.

To mark a task as a default build task for the workspace would require task support for workspaces which (to be in line with Debug) we decided not to do for now. You can't define launch configs nor tasks for a workspace. Only for folders. 

@egamma we might need to rethink that decision.

**Comment by roblourens** [comment]
What I'd like to have is a build task per folder, then when I press cmd+shift+b, I see all the available build tasks. My workspace has 3 folders and each needs to be built.

**Comment by dbaeumer** [comment]
@roblourens that works but currently you can't start them all at once. You need to start them one by one. What I clould add is an "All" entry with starts them all. I was thinking about an "All" entry for terminate and relaunch as well.

**Comment by dbaeumer** [comment]
Fixed the initial reported problem minus the Confogure default Build Task improvement mentioned. Tracked in https://github.com/Microsoft/vscode/issues/35312
