### ISSUE TITLE
defaultUri's file extension is not preserved in showSaveDialog

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#35195]
- VSCode Version: Code - Insiders 1.17.0-insider (a5210bcbda97166904ce4c08ee296cb98fccfcd9, 2017-09-26T05:24:48.911Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Testing #34821.

When saving like this:

```ts
vscode.window.showSaveDialog({
            defaultUri: vscode.Uri.file(`c:\\Users\\octref\\Desktop\\hello.ts`)
})
```

The dialog does not show the file extension.

![image](https://user-images.githubusercontent.com/4033249/30890069-6b0ae58e-a2df-11e7-9d9e-52372d9ae0f7.png)

And BTW, the save dialog does not actually save the current file. Is that as intended?

**Comment by octref** [comment]
Same for `showOpenDialog`.

**Comment by jrieken** [comment]
> And BTW, the save dialog does not actually save the current file. Is that as intended?

Sure, i lets you chose a file path to save to, you don't give it content to be saved. It's a filename picker for saving a file, which btw isn't anything special

**Comment by jrieken** [comment]
@bpasero Can you share your experience about file filter and the dialogs? I see quite some [code here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/electron-browser/textFileService.ts#L150) and I would expect that to be in the service if there are issues with the underlying electron/windows implementation

**Comment by bpasero** [comment]
@jrieken yeah the filter API is challenging, only on Windows we fill in the extensions for known languages. We never used a save dialog anywhere else than for saving files so feel free to extract that to some other place for reuse.

**Comment by jrieken** [comment]
> We never used a save dialog anywhere else than for saving files so feel free to extract that to some other place for reuse.

Sorry, no intentions of owning that service

**Comment by bpasero** [comment]
@jrieken I can look into that, would you expect that when an extension does not provide the "`filter`" option from the API, we fill in whatever we do in our default save dialog?

**Comment by jrieken** [comment]
>  does not provide the "filter" option from the API, we fill in whatever we do in our default save dialog here on windows?

I'd except that to be the '*' filter then, so show all files which it according to https://github.com/Microsoft/vscode/issues/35195#issue-260809334 doesn't. On Mac it works fine for me

**Comment by bpasero** [comment]
@octref this is configurable from Windows Explorer, just make sure you have this unchecked:

![image](https://user-images.githubusercontent.com/900690/30916865-bb2a967a-a39a-11e7-9ab5-699785194ef0.png)
