### ISSUE TITLE
Snippet used when creating extensions.json puts cursor in the wrong place

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35190]
Testing #29242

In multi-root set up, the command `Extensions: Configure Recommended Extensions (Workspace)` creates the extensions.json file as below

![image](https://user-images.githubusercontent.com/16890566/30889220-b82c0830-a2d9-11e7-978f-370796a06dd7.png)

The cursor should be inside the `[]`.
Instead the cursor is just before `[]`

**Comment by sandy081** [comment]
@aeschli Here is my schema for extensions/recommendations

```json
{
	id: ExtensionsConfigurationSchemaId,
	type: 'object',
	title: localize('app.extensions.json.title', "Extensions"),
	properties: {
		recommendations: {
			type: 'array',
			description: localize('app.extensions.json.recommendations', "List of extensions recommendations. The identifier of an extension is always '${publisher}.${name}'. For example: 'vscode.csharp'."),
			items: {
				type: 'string',
				pattern: EXTENSION_IDENTIFIER_PATTERN,
				errorMessage: localize('app.extension.identifier.errorMessage', "Expected format '${publisher}.${name}'. Example: 'vscode.csharp'.")
			},
		},
	}
}
```

`recommendations` is of type array. When a user types `recommendations` I think you are automatically writing empty array. I think the bug here is that, cursor is not placed inside array.

**Comment by aeschli** [comment]
When completing 'recommendations' with code assist, you get
![image](https://user-images.githubusercontent.com/6461412/30975404-7ce95d6e-a472-11e7-83f1-060bc4e9d54d.png)

The `Extensions: Configure Recommended Extensions (Workspace)` seems to either create a new file or open the existing file and add `recommendations`. In both cases the cursor is at the end. I guess @ramya-rao-a suggestion is to place.
How do you insert `recommendations`? You would have to add it as snippet. Probably like that: https://github.com/Microsoft/vscode/blob/5b76a1d27f75814a4494aad6d909a01436c61f0a/src/vs/workbench/api/electron-browser/mainThreadEditor.ts#L358, but Joh would know.

**Comment by sandy081** [comment]
Ah ok. This is while creation. Could be that I placing the cursor there. Thanks @aeschli for insight.
