### ISSUE TITLE
How do i configure a task to call a powershell script

### ISSUE THREAD

**Issue by kcheick** [Microsoft/vscode#3519]
I am trying to set up a build task in visual studio code to call an existing build script written in powershell. Here is how i set up my build task
``` F#
{
    "version": "0.1.0",
    "command": "powershell",
    "isShellCommand": true,
    "args": [   
        "-File ${cwd}/source/deployment/build.ps1",
        "-NoProfile",
        "-ExecutionPolicy Unrestricted"
    ],
    "taskSelector": "-task ",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "showOutput": "always",
            "isBuildCommand": true
        }
    ]
}

```
but here the output when i run the task

> . : File C:\Users\chkeita\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170. At line:1 char:3 + . 'C:\Users\chkeita\Documents\WindowsPowerShell\Microsoft.PowerShell_ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : SecurityError: (:) [], PSSecurityException + FullyQualifiedErrorId : UnauthorizedAccess -File : The term '-File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + -File f:\Dev\spf3/source/deployment/build.ps1 -NoProfile -executionpo ... + ~~~~~ + CategoryInfo : ObjectNotFound: (-File:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException

I have tried reordering the arguments and merging them in one string without any success
What am i missing? Is there a better way to do this in vscode

**Comment by egamma** [comment]
// @daviwil

**Comment by daviwil** [comment]
Check out this tweet by @StefanStranger which gives an example of setting up a task to launch a PowerShell script: https://twitter.com/sstranger/status/700409449337397248

![screenshot of task](https://pbs.twimg.com/media/Cbhal_MXIAEXAr9.jpg:large)

**Comment by kcheick** [comment]
Thanks @daviwil it helped me figured out what was wrong with my script 

here is the working version of my script for those who are interested: I had to split he ExecutionPolicy parameter in two and move it in the front of the list of arguments 
```json
{
    "version": "0.1.0",
    "command": "powershell",
    "args": [   
        "-ExecutionPolicy",
        "Unrestricted",
        "-NoProfile",
        "-File",
        "${cwd}/source/deployment/build.ps1"       
    ],
    "taskSelector": "-task ",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "showOutput": "always",
            "isBuildCommand": true
        }
    ]
}
```
