### ISSUE TITLE
SCM: very hectic activity updates when opening folder with many repositories

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35205]
Steps to Reproduce:

1. open a folder with many git repos inside
2. the activity bar is dancing a lot

![flicker_chrome58](https://user-images.githubusercontent.com/900690/30900644-09ea6406-a365-11e7-900e-3b7528fadf66.gif)

**Comment by joaomoreno** [comment]
What would you expect instead?

**Comment by bpasero** [comment]
Maybe this call should be buffered, either on your end or the activity bar.

**Comment by joaomoreno** [comment]
But when would it actually show? Currently it is buffered, it just has a short debounce number. Increasing that will get me another issue that the activity bar always takes X amount of time to react.

**Comment by bpasero** [comment]
@joaomoreno yeah I meant to throttle it, not buffer. so it should succeed to update every 1s for example.

**Comment by joaomoreno** [comment]
So... imagine you have 10 changes. You commit. The SCM Viewlet will show that there are no changes. And the activity would only update its status 1 second after?

**Comment by bpasero** [comment]
@joaomoreno probably what set me off was the quick flicker between a number and progress, I think any other transition (number) or from showing the badge to not showing can still be instant.

**Comment by joaomoreno** [comment]
Maybe we can simply remove the progress indicator then. 👍

**Comment by bpasero** [comment]
@joaomoreno yeah for the multi repository scenario it could be that the progress is constantly showing due to activity in one of the repos.
