### ISSUE TITLE
SCM: some git.exe hang in git-remote-https

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35208]
Steps to Reproduce:

1. open a folder with many git repositories inside
2. I got asked if I want to permit VS Code access to my keychain and said "yes"

Notice how many git processes seem to hang in git-remote-https, not returning. I am also not seeing a login popup from VS Code either:

![image](https://user-images.githubusercontent.com/900690/30900796-91694eec-a365-11e7-9526-473ef1110221.png)

My git config:

```ini
[credential]
	helper = osxkeychain
```

**Comment by joaomoreno** [comment]
@bpasero Can you show me the full command line of those top processes? 6580 and 6591?

**Comment by bpasero** [comment]
@joaomoreno `/usr/local/git/libexec/git-core/git-remote-https origin https://chromium.googlesource.com/chromium/src`

Another one is: `/usr/local/git/libexec/git-core/git-remote-https origin https://github.com/Microsoft/TypeScript`

They also seem to come and go, they probably retrigger because of auto-fetch?

**Comment by joaomoreno** [comment]
Leaving close as duplicate of #34684
