### ISSUE TITLE
Cannot reference a regex subgroup in "Find in Files"

### ISSUE THREAD

**Issue by armandas** [Microsoft/vscode#35202]
- VSCode Version: 1.16.1
- OS Version: Windows 10 Home 64-bit

Steps to Reproduce:

1. Create a random folder with a single text file inside it.
2. Open the created folder using vscode.
3. Open the text file, write `hello,hello,world` and save it.
4. With the file open, click the search icon and paste the following regex into the search field: `([a-z]+),\1`. Make sure the regex option is selected.
5. Perform the search and observe that a single result has been returned.
6. Close the file and perform the search again. Observe that no results have been found.
7. (Optional) set `search.useRipgrep` option to false and observe that the search now works as expected.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected - search is powered by the ripgrep tool, which doesn't support some advanced regex features like backreferences.

**Comment by armandas** [comment]
@roblourens Thank you for the explanation. After your reply, I found #27802 which describes exactly the same issue.

I think the problem stems from inconsistency. Back references work in some cases (open files) but not others. This is confusing at best and misleading at worst. For a moment, I was lead to believe that there were no results, other than those found in my open file.

I don't know why ripGrep was chosen as a default search tool, but I think it would make more sense to give users the full features and allow them to choose the performance option, if they are happy to sacrifice some functionality. The added benefit is that the users can be made fully aware of the trade-offs in the documentation.

**Comment by roblourens** [comment]
Yeah, I understand that it's confusing. I think I should use #27802 to detect and disable searches with backreferences entirely to cut down on the inconsistency. Technically you can disable ripgrep with `"search.useRipgrep": false` but don't expect that to be an option forever.

**Comment by armandas** [comment]
When you say that `search.useRipgrep` option may not be there forever, are you saying it will become the only search option, even though it has limited regex support?

While I think disabling back references would be better than the current situation, I would hate losing that feature. Would it be possible to only disable back references when `search.useRipgrep` is set to true?

What is your opinion on making ripGrep optional?

**Comment by roblourens** [comment]
The old search code is definitely going to go away at some point, but we may allow extensions to power search at some point. In that case, someone could build an extension with a different search implementation that supports other regex features.
