### ISSUE TITLE
OSX can't update as non-admin user

### ISSUE THREAD

**Issue by steelheaddigital** [Microsoft/vscode#3520]
When an update is available, Code tells me to restart to apply the update.  When I restart, Code is not updated and the "restart to update" message is displayed again. I suspect this may be due to the fact that I'm using a non-administrator account.  I haven't done anything to confirm that though.

**Comment by joaomoreno** [comment]
@steelheaddigital Sorry for the long silence. Is this still a problem nowadays with the latest versions?

**Comment by steelheaddigital** [comment]
No problem, thanks for taking a look.  Yes, it's still an issue with the last upgrade I just did from 1.2.1 to 1.3.0.

**Comment by joaomoreno** [comment]
Do you by any chance use another application with automatic updates, like Atom? Does it work for you there?

**Comment by steelheaddigital** [comment]
Yes, other auto updates seem to work.  I'm not using Atom, but Sublime Text auto update works. The difference seems to be that other apps display the popup asking for admin credentials to install the update. Code doesn't do that, so I'm guessing it probably can't write to the Applications directory since I'm using a non-admin account.

**Comment by joaomoreno** [comment]
Oh. What if you move Code to a folder your user controls?

**Comment by steelheaddigital** [comment]
I can try that. I don't have my Mac with me right now, but I'll give it a shot later. That would at least let us know if it is indeed a permissions thing. Still, it would be nice to have it ask for Admin credentials when updating like other apps so that it can stay in the Applications directory.

**Comment by DavidRigglemanININ** [comment]
I'm having the exact same problem and have for a while. I run as a non administrator account on my Mac and have VS Code in the Applications folder. I second the notion about asking for Admin credentials.

**Comment by joaomoreno** [comment]
We should get this from Electron. electron/electron#6345 ?

**Comment by joaomoreno** [comment]
Or Squirrel: Squirrel/Squirrel.Mac#157

**Comment by spicydonuts** [comment]
I was having the same issue but happened to install macOS Sierra (10.12) last night and after doing so the update worked fine (still in `/Applications`).

**Comment by nathantschultz** [comment]
I'm seeing this same behavior but I am signed in with an admin account.

**Comment by scgm11** [comment]
still fails, example:  Im stuck with 1.7.0  says update, restart now but nothing happens i have to manyally download and install

**Comment by antonstefanov** [comment]
+1, issue persists, Version 1.7.1, macOS Sierra 10.12.1, extensions update without issues, admin account, visual studio code located in user\applications. After clicking restart to update Visual Studio Code closes and doesn't restart or update

**Comment by johnfn** [comment]
I began running into this bug as soon as I upgraded to macOS Sierra from OS X Yosemite.

**Comment by rwatts3** [comment]
Same Issue for me

**Comment by joaomoreno** [comment]
A possible fix, as @farfromrefug found out in #7426, is to run:

```
xattr -dr com.apple.quarantine "/Applications/Visual Studio Code - Insiders.app"
```

Does this help anyone?

**Comment by mmc41** [comment]
The xattr trick did not help. I also have had the same problem for many, many releases of code and for different mac os x versions incl. Sierra. It is the single most annoying problem with visual code. Really need fixing.

**Comment by cesarvarela** [comment]
Happens to me now with VScode, and happened with Atom in the past.

The xattr thing didn't work for me though.

**Comment by jguerin** [comment]
This continues to happen to me. I'm on MacOS 10.12.2, running as non-admin. I was stuck on VS Code 1.7.2 until I manually updated it to 1.8.1.

**Comment by ivosabev** [comment]
Same issue on macOS Sierra 10.12.2

I get this error every 2 seconds in `system.log`

```
Dec 28 14:23:45 Ivolution com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Dec 28 14:23:47 Ivolution com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[7291]): Service could not initialize: 16C67: xpcproxy + 11765 [1475][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0xd
```

**Comment by brettKgm** [comment]
same issue on macOS Sierra 10.12.2

insiders asks to update every day -- need to manually download and copy into Applications each day to update.

`Jan 17 11:09:05 xxxxxxx com.apple.xpc.launchd[1] (com.microsoft.VSCodeInsiders.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Jan 17 11:09:07 xxxxxxx com.apple.xpc.launchd[1] (com.microsoft.VSCodeInsiders.ShipIt[14413]): Service could not initialize: 16C67: xpcproxy + 11765 [1475][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0xd
`

**Comment by rwatts3** [comment]
Manually install the lateset version of insiders.  After that it should
auto update going forward.  I'm not sure which issue fixed this problems
but it has been working ever since the last couple updates

**Comment by brettKgm** [comment]
@rwatts3 confirmed that this does not work. Tried pressing update button today -- same result as before.

**Comment by maxruby** [comment]
I am experiencing the same issue as @brettKgm with version 1.8.0 on OSX 10.12.2.

**Comment by joaomoreno** [comment]
Definitely #7426

**Comment by armenr** [comment]
This issue is persistent on my Mac as well. 

VSCode 1.9.1
OSX 10.12.3

**Comment by joaomoreno** [comment]
Guys, read [my comment](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150) on #7426

**Comment by lsoarestd** [comment]
same with me

**Comment by tapsaid** [comment]
I managed to get ride of this.
I noticed that I used to run code as admin.
So I normally started vs code and updated. After that, everything went well for me.

Here is my context:
OSX El Capitan
Version 10.11.6

Old VS Code version: 10.11
VS Code version after successful update : 10.12

Hope this will help someone.
