### ISSUE TITLE
SCM: lots of git processes hanging around after quitting

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35206]
Steps to Reproduce:

1. open a folder with many git repositories as children
2. see your CPU go flying

![screen shot 2017-09-27 at 09 21 10](https://user-images.githubusercontent.com/900690/30900702-4ad0bf6a-a365-11e7-9843-52bbf40e8743.png)

These processes were hanging around even after I quit VS Code. I had to reboot my machine to get out of very high CPU/memory consumption.

**Comment by joaomoreno** [comment]
How much is many?

**Comment by bpasero** [comment]
@joaomoreno not sure, I have to mark this as important because my machine become very slow having a constant 100% load and even after closing VS Code, a lot of git processes where actually still running.

**Comment by joaomoreno** [comment]
@bpasero Can you try to get into this state again and find the full command line of the processes?

**Comment by joaomoreno** [comment]
I believe https://github.com/Microsoft/vscode/commit/3b76085a6c8d9fbefaa6306588f6d7a7a67d0a46 could make this situation better. There was a case in which many fetches could be running simultaneously. That commits fixes that and makes sure only one runs at a time.

**Comment by bpasero** [comment]
@joaomoreno still seeing long running fetches even after I quit VS Code:

![image](https://user-images.githubusercontent.com/900690/30965272-1d854f58-a455-11e7-9265-e83f00ff44d9.png)

**Comment by bpasero** [comment]
They eventually seem to quit, e.g. after 2 minutes now only the chromium one is still active.

**Comment by joaomoreno** [comment]
Excellent, so I think this is fine for now. The behaviour hasn't changed from previous builds. I think changing the default of auto fetch to off will polish this out. Merging into #34684
