### ISSUE TITLE
Incorrect "explicitly instantiated more than once" warnings in C++

### ISSUE THREAD

**Issue by gcp** [Microsoft/vscode#35200]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Load https://github.com/gcp/Stockfish/src
2. Open pawns.cpp, navigate to bottom

```C++
template<Color Us>
Score Entry::do_king_safety(const Position& pos, Square ksq) {
...
}

// Explicit template instantiation
template Score Entry::do_king_safety<WHITE>(const Position& pos, Square ksq);
template Score Entry::do_king_safety<BLACK>(const Position& pos, Square ksq);
```

VSCode's C++ IntelliSense red underlines these, claiming a duplicate explicit instantiation. But as you can see, that's not correct.

**Comment by sandy081** [comment]
Please file the issue against c++ extension. You can find the link to report issue when you open the extension.
