### ISSUE TITLE
VS Code freezes on editing jsdoc

### ISSUE THREAD

**Issue by sAleksovski** [Microsoft/vscode#35209]
- VSCode Version: 1.16.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Edit jsdoc that has something=[]
2. Put opening [ before `something`
3. VSCode freezes

Example: 
```
* @param {object[]} something=[] Some description
```

Changing to
```
* @param {object[]} [something=[] Some description
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/515

Should be fixed in the next VScode insiders build
