### ISSUE TITLE
when open devtools layers, vscode crashed

### ISSUE THREAD

**Issue by topul** [Microsoft/vscode#35203]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
EditorConfig|Edi|0.10.1
auto-close-tag|for|0.5.0
code-runner|for|0.7.1
vetur|oct|0.9.10
language-stylus|sys|1.7.3
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. toggle developer tools
2. more tools -> layers

Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/8213229/30899661-5ed11d38-a393-11e7-84b5-778249f2750b.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/29063
