### ISSUE TITLE
Git running operations although VS Code has no focus

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35216]
See attached screen shot

I execute git pull in a terminal and VS Code's git integration is running in the background although it doesn't have focus making this git operation executed in the terminal fail.

![cast](https://user-images.githubusercontent.com/1931590/30907199-598fccde-a37a-11e7-9742-4eb9b8d254d3.gif)

**Comment by joaomoreno** [comment]
What's your version commit id?

**Comment by dbaeumer** [comment]
Either 67a8479bdcb95b3e21959342663b828d97f2098f or e059563fb6b8905de79ac4c75be537bb6dc74f5f

But very likely the first.

**Comment by joaomoreno** [comment]
Very interesting! I thought a `git show` wouldn't mess around with the index! But it turns out that it does... gonna have to disable that one too. Too bad!
