### ISSUE TITLE
Terminal size is very often cropped

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35218]
Doesn't seem to relate to my tmux setup, it also happens when I disable that.

![image](https://user-images.githubusercontent.com/22350/30908372-a4dfdfa0-a37d-11e7-8560-3235f2ffa641.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34332, will see if I can have a look for Sept.
