### ISSUE TITLE
workspace file conflict: compare content

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35211]
Testing #34775

- open a folder
- save the workspace to a new file
- open the workspace file in another editor, add
```
	"settings": {
		"workbench.colorTheme": "Monokai"
	}
```
- in VSCode, note that the theme color changes
- in VSCode, add a new workspace folder
- Error dialog comes up and says that the file has been modified in the background.

-> there should not be any conflicts here as the file seems to be tracked
-> non-conflicting changes should be resolvable without a merge editor

**Comment by bpasero** [comment]
@sandy081 an issue with the configuration editing service? it probably holds on to an old buffer?

**Comment by sandy081** [comment]
I do not see this is going through configuration editing service. Workspace configuration file was edited twice

1. Directly in a different editor to update configuration
2. Adding a folder - that uses workspace editing service.

This issue happens does not happens when the workspace is saved already. Looks like it occurs during the transitioning phase. 

@bpasero Any idea, we are having stale data of the file during transitioning?

**Comment by bpasero** [comment]
@aeschli not reproducible for me, so I wonder if there was more to it. Did you have the file open? Maybe a case of a missing file event. Let us know if you can reliably reproduce or it only happened once.

**Comment by aeschli** [comment]
No I didn't have the file open. 
I have it 90% reproducible. Please come by and we can debug it together.

**Comment by bpasero** [comment]
@sandy081 here are the steps to reproduce:
* open a saved workspace (make sure the workspace file is not opened in any editor)
* change a setting in that workspace file from an external editor (theme is best to verify the change is picked up)
* add or remove a workspace folder
* change the theme setting again from an external editor
* add or remove a workspace folder

=> you get the save conflict error

This reminds me of an issue we talked about earlier. Somehow I think the [`JSONEditingService`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/node/jsonEditingService.ts#L25) is using an old model for the writing (does it maybe not dispose its reference after writing)?

**Comment by sandy081** [comment]
Yes, I am not disposing the reference. Initially this came from configuration editing service. Fixed it in configuration editing service but forget in json editing service.

Fixed it.

**Comment by bpasero** [comment]
@sandy081 awesome!
