### ISSUE TITLE
Add/remove workspace folder with dirty workspace file gives no feedback

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35219]
Steps to Reproduce:

1. have a dirty workspace config file
2. add or remove workspace folders

=> nothing happens
=> no message shown either

**Comment by sandy081** [comment]
Error message is shown when running the command `Add Folder to Workspace` from Command Pallette. When doing it from explorer, not error is shown.

**Comment by sandy081** [comment]
I will improve the error message and actions in it.

**Comment by sandy081** [comment]
IWorkspaceEditingSerive takes care of showing proper message for error. So no need to change at places calling this API.
