### ISSUE TITLE
Cannot run oss tool because of markdown's npm-shrinkwrap.json

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#35215]
The oss tool does not work anymore, as it stumbles upon the new npm-shrinkwrap.json format, where at a field called `"version"`, which used to be a version number, the tool now finds an npm URI.

This breaking change was introduced via https://github.com/Microsoft/vscode/commit/a87c72f2dffe56dccc1c522b523449f67858583a

If you would like to use such a format in your npm-shrinkwrap.json, then please also update the oss tool to work with this new format.

**Comment by jrieken** [comment]
This is important because we need OSS tool this week (thursday) in order to have a release candidate.

**Comment by mjbvz** [comment]
Caused by using npm 5 by mistake, which we don't support yet
