### ISSUE TITLE
Fine grained configuration change events

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35229]
Currently configuration service fires a change event and do not provide what part of configuration has changed. It will be effective and performant for the consumers to know what part of configuration has changed and react to it.

* [ ] a fine-grained configuration change event that allows consumer to check what settings have changed
* [ ] adoption in the listeners

**Comment by eamodio** [comment]
@sandy081 will this new support be available to extensions or just internally?

**Comment by sandy081** [comment]
Also to extensions - Drafting API in progress - https://github.com/Microsoft/vscode/issues/36475

**Comment by sandy081** [comment]
This is implemented internally.
