### ISSUE TITLE
Screen Reader Detected isn't very valuable

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35228]
#32166 

We have talked about this, the fact that a screen reader is detected hasn't much value

**Comment by alexandrudima** [comment]
I have improved the wording:

| before | after |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/30918363-a0806e5e-a39e-11e7-8041-850c98786798.png) | ![image](https://user-images.githubusercontent.com/5047891/30918310-75be1cca-a39e-11e7-9b78-1a2f69f4894d.png)
