### ISSUE TITLE
Hover: Don't wrap in the middle of words

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35223]
From #35147:

![foo](https://user-images.githubusercontent.com/1051190/30874366-f0ff1916-a2a4-11e7-93c2-6177e5caed17.gif)

Ideally, line wrapping should happen at word boundaries.

**Comment by joaomoreno** [comment]
Unfortunately this is a double edged sword. More often than not, there are huge words in that widget. Like `thisMethodIsSoLargeBecauseICantFindAShorterWayToWriteIt`. And because of that, we wrap on characters: any other alternative would look much worse than the current one, most of the time.

**Comment by mattacosta** [comment]
Hmm, would it be possible to let a language server pass along a flag in the `Diagnostic` object that tells VSCode to wrap the message at word boundaries?

For example, my parser returns a diagnostic object that may contain message arguments (i.e. text replacements). This means that the language server could let VSCode know if `mySuperLongMethodOrVariableName` was inserted into a diagnostic message or if the message did not contain any replacements and should be wrapped at word boundaries.
