### ISSUE TITLE
Add please support for  "suggestions" for javascript lang based on all opened files in workspace.

### ISSUE THREAD

**Issue by arktas79513** [Microsoft/vscode#3522]
Example:  we have 2 files, first is newly created offerService.js which contains gridMetadata() method exposed outside:
```
(function() {
    "use strict";

    angular
        .module("px.offers")
        .service("offerCategoriesService", offerCategoriesService);

    offerCategoriesService.$inject = ["Restangular"];

    function offerCategoriesService(Restangular) {
        var offerCategories = Restangular.all("offercategories");
        var service = {
            gridMetadata: gridMetadata
        };
        return service;

        function gridMetadata() {
            return offerCategories.options();
        }
    }
})(angular);
```
If i create new file somethingController.js  i would like to have _gridMetadata _in my suggestions list when i start typing _gri...._
Right now it's not available in VS code.

**Comment by egamma** [comment]
Did you create a jsconfig.json in your folder? https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson

**Comment by arktas79513** [comment]
![1](https://cloud.githubusercontent.com/assets/5990013/13374535/3cf07f94-dd90-11e5-9565-362a7d719792.png) Thanks for quick response! Yes, i did

**Comment by egamma** [comment]
Thanks for the simple test case, but this works for me in the latest 0.10.10 that we will push to stable today.

![image](https://cloud.githubusercontent.com/assets/172399/13565963/85893ec0-e453-11e5-839f-19825a8aba6a.png)
