### ISSUE TITLE
Full stack traces are annoying

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35222]
The devtools-console is showing the *full* stack trace of callers (calling console.log/warn/etc) and that's quite annoying as that is usually too much information. The top most stack element should be enough to identify the caller. 

<img width="858" alt="screen shot 2017-09-27 at 12 37 14" src="https://user-images.githubusercontent.com/1794099/30909281-d171a60e-a380-11e7-9b36-0bac5e87111f.png">

**Comment by bpasero** [comment]
@jrieken that is fine by me but I thought it would also be interesting which code triggered a specific `console.log` message.

**Comment by jrieken** [comment]
For me this is just some ambient information and when need to know more I use breakpoints
