### ISSUE TITLE
Search using regex only searches open documents

### ISSUE THREAD

**Issue by SippieCup** [Microsoft/vscode#35232]
- VSCode Version: Version 1.17.0-insider (Commit 67a8479bdcb95b3e21959342663b828d97f2098f)
- OS Version: Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux

Steps to Reproduce:

1. Open a folder and ensure all editors are closed.
2. Open search, enable regex search and search for "\n" - You should get 0 results.
3. Open a few files in editors and search again, populated results will consist of only the open documents.

Note: sometimes it populates with just a single file, cannot consistently reproduce this.
 
Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected - search doesn't normally support multiline search. But if the file is open, then search is done by the editor, which does support multiline search.

**Comment by SippieCup** [comment]
Good to know, I thought this was expected behavior but was confused when it did provide a result for the  `tsconfig.json` file in the directory and thought something might have changed/was broken.

![screenshot](https://user-images.githubusercontent.com/679311/30926907-b1402dac-a384-11e7-955d-fa87be2872d1.png)

Is this intended functionality? or is the single result due to tsconfig.json being open in a hidden editor?

**Comment by roblourens** [comment]
That's interesting, I actually don't know why it would do that. It may be a bug in the search tool we use, but not a critical one.

**Comment by SippieCup** [comment]
Yeah, definitely not a critical bug, that being said managed to reproduce consistently on MacOS.

1. Open a folder that has both a .ts file and a tsconfig.json file
2. Open the .ts file
3. Close .ts file
4. Search for "\n" with regex.

**Comment by roblourens** [comment]
Ah, I can reproduce it now too. Apparently the tsconfig is open in the background, didn't realize it did that.
