### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by jcitarello** [Microsoft/vscode#35233]
- VSCode Version: 1.6
- OS Version: Ubuntu 16,04

Steps to Reproduce:

1.  Open VS Code
2. Attempt to load and install any extenstions.

Reproduces without extensions: Yes

I am unable to see any extensions when opening the Extensions dialog and seeing "Error XHR failed" message when typing in any search.  Please advise, thanks.

**Comment by banyudu** [comment]
Same issue
VSCode version 1.16.1
OS Version: Ubuntu 17.04

**Comment by banyudu** [comment]
Possible duplicate of https://github.com/Microsoft/vscode/issues/34385

Besides, in my case, the system proxy causes this error.

**Comment by sandy081** [comment]
Duplicate of #34385
