### ISSUE TITLE
Update ripgrep to 0.6.0+

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35237]
#35236 depends on `--quiet` working with `--files`. We'll also need the fix for `--files` performance that is not in any release yet only in master.

**Comment by BurntSushi** [comment]
I'm hoping to do a patch release of ripgrep soonish. I might not get to it until the weekend however.

**Comment by chrmarti** [comment]
@BurntSushi That would be great, thanks!

**Comment by chrmarti** [comment]
Thanks @roblourens !
