### ISSUE TITLE
Intellisense not working for Ember when using import statement

### ISSUE THREAD

**Issue by ibachar** [Microsoft/vscode#3523]
Hi,

I've a project using Ember and experience problems with Intellisense not being available.
I've a .jsconfig at the root level of my projects and have used the tsd manager
to download the .d.ts for ember. Whenever an `import Ember from 'ember';`
statement is present in any javascript file, Intellisense is not available. Removing the import statement causes vscode to properly display auto complete for the Ember namespace but obviously the project doesn't compile then... Am I doing something wrong here?

Thanks.

**Comment by egamma** [comment]
This is a limitation in the existing JS infrastructure. We are switching to a new infrastructure and you can try the preview https://code.visualstudio.com/Updates#_javascript-salsa-preview and we believe that this issue is now addressed, but would appreciate if you could confirm this in your setup.

// @chrisdias

**Comment by ibachar** [comment]
I've enabled Salsa but now I don't have Intellisense at all (with or without the import statement).

**Comment by davelane** [comment]
+1 from me :)

**Comment by egamma** [comment]
I guess that the ember.d.ts does not use the ES6 default export.  Please see this comment for the new compilerOption allowSyntheticDefaultImport https://github.com/Microsoft/vscode/issues/5336#issuecomment-211052292

**Comment by egamma** [comment]
`allowSyntheticDefaultImport` is now the default https://github.com/Microsoft/TypeScript/issues/10895.
