### ISSUE TITLE
Not very helpful link origin when logging out of an extension

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35230]
See screen shot:

The link points to extensionHostProcess and clicking on it takes me to minified code. I was expecting to see a link to my extension code. 

<img width="703" alt="capture" src="https://user-images.githubusercontent.com/1931590/30917414-3e1b2300-a39c-11e7-9fe7-cc077dec1698.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35140
