### ISSUE TITLE
terminal.integrated.fontLigatures is missing from the most recent insiders builds

### ISSUE THREAD

**Issue by flipphillips** [Microsoft/vscode#35239]
- VSCode Version: Version 1.17.0-insider (1.17.0-insider)
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open User Settings
2. Notice that `"terminal.integrated.fontLigatures": true,` now has the squiggle of 'this is not an option' under it. 
3. Confirm looking in master preferences

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This was intentional to support to big performance improvement in latest. You can read more about it here https://github.com/sourcelair/xterm.js/pull/938

Issue to support it again: https://github.com/sourcelair/xterm.js/issues/958

**Comment by flipphillips** [comment]
OK- makes sense / understandable. I'm all for optimizing render'n.
