### ISSUE TITLE
Launch Multiple Windows on Different Desktops

### ISSUE THREAD

**Issue by anish557** [microsoft/vscode#35240]
When launching VS code from a new virtual desktop on Windows, you are forced to the virtual desktop that has an active instance of VS code. 

I expect that it would render a new window for VS code in the new virtual desktop to let me have different projects open at the same time.

**Comment by CaptainN** [comment]
It seems to work the way this issue requests now - but I'd actually like it to work the way it used to (as I have described in #58978) - is there a way to change it back with a setting?
