### ISSUE TITLE
Markdown references links don't handle escapes

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#35245]
From https://github.com/Microsoft/vscode/issues/33714#event-1267713457

In a markdown file:

```
text [more info][aut\]osave] text

[aut\]osave]: /docs/editor/codebasics.md#saveauto-save
```

Does not detect `aut\]osave` as a link

**Comment by hibyguy** [comment]
Did you mean **auto\]save**?

**Comment by hibyguy** [comment]
**auto\]save** @mjbvz

**Comment by Olovan** [comment]
Added a merge request with some tweaks to the regex that is used to detect links. With the fix it should now correctly detect links with "\]" in their names.
