### ISSUE TITLE
Git actions are gone!!!

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35248]
- VSCode Version: Built from master as of 9/27/2017 11am PST
- OS Version: Windows

Steps to Reproduce:

1. The context menu for Git has only one entry "Install additional SCM providers"
2. Next to "CHANGES", the "Clean" and "Stage" buttons are gone
3. The button to view the diff on the editor group title is gone
4. All Git related commands from command palet is gone.

cc @joaomoreno

**Comment by joaomoreno** [comment]
Git bisect tells me this is the culprit: https://github.com/Microsoft/vscode/commit/838d4a33d6b6b056e059593f857fb7d0c67343f6

cc @sandy081

**Comment by sandy081** [comment]
Reverted the fix #34353.
