### ISSUE TITLE
Wrong Intellisense editing css, scss, less

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#3524]
typing ```text-decoration: ``` gives intellisense for colors, not for text-decoration. typing non will not show 'none' in Intellisense. The problem occurs in any css, less and scss file in any place, with any selector. Problem also occurs without extensions. I am running Windows 7 32bit with all updates possible.
![2016-02-27 1](https://cloud.githubusercontent.com/assets/13982006/13372969/cf463f72-dd5a-11e5-849d-e9b84e19b0a2.png)
![2016-02-27](https://cloud.githubusercontent.com/assets/13982006/13372970/cf46c17c-dd5a-11e5-8dbe-c25de28318b2.png)

**Comment by dstorey** [comment]
Colours are valid values for text-decoration, as it is a shorthand which includes text-decoration-color https://www.w3.org/TR/css-text-decor-3/#text-decoration-property
