### ISSUE TITLE
Markdnwn automatic numbers only autofills "1."

### ISSUE THREAD

**Issue by pimatrix314** [Microsoft/vscode#35241]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.16
vsc-material-theme|Equ|1.0.3
ayu|tea|0.8.0
markdown-all-in-one|yzh|0.10.2

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open a .md file
2. Type the number "1." with a space and some text after it
3. Press enter and watch it type "1." instead of continuing to 2

Reproduces without extensions: Yep!

**Comment by mjbvz** [comment]
This behavior comes from your markdown extension. Please file the issue against them: https://github.com/neilsustc/vscode-markdown/issues
