### ISSUE TITLE
Touchbar: Prev and next buttons doesn't switch to the expected editors

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#35242]
When using the Prev and next buttons  in the touchbar, the actions doesn't seem to follow any particular order, but seems to jump around. I assume this is because of some internal ordering of open editors, but this doesn't match what I'd expect: If I press next I'd go to the next right editor tab, and back is the next left one.

![touchbar_prev_next](https://user-images.githubusercontent.com/173559/30928640-f8344afe-a370-11e7-9826-6d1635ac0e13.gif)

**Comment by bpasero** [comment]
@auchenberg the buttons map to the same thing as Go > Previous and Go > Forward, they navigate in editor history (also within editor).
