### ISSUE TITLE
Open Changes Button Blinks

### ISSUE THREAD

**Issue by petealbertson** [Microsoft/vscode#35243]
The "Open Changes" button is blinking non-stop and it's driving me insane. The button also cannot be used in this state.

- VSCode Version: Version 1.16.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Open a project in VSCode.
2. See the "Open Changes" button (upper right corner) blink.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you record a screencast of this? Thanks!
