### ISSUE TITLE
Windows: Dropdowns have orange border in all themes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35246]
I first noticed this in the Dark theme. The orange border felt out of place.
Changed themes and I see the same. Light, Dark, Red, Blue ...

![image](https://user-images.githubusercontent.com/16890566/30929829-87899f4e-a374-11e7-87d8-b2bde5905bea.png)

**Comment by ramya-rao-a** [comment]
I am guessing this must be electron related....

**Comment by cleidigh** [comment]
@ramya-rao-a 

I think what you are referring to is one of several select element styles
that cannot be regularly styled (limitation of the select element native rendering).
The select border at the top of the drop-down can be styled by CSS, but
the select border of the expanded dropdown cannot be changed, it is controlled
by the OS browser.  

This is the type of thing I was trying to address with related issue #25965   and PR WIP #27298 .

Other things addressed:
- selected item focus color
- hover color
- Match Windows, Linux DD style on OS X

@bpasero  Any possibility to move forward with my PR for the October release ?
It would be great to make these UI improvements ;-)

If so I will have to update and finish the high contrast modes.

**Comment by bpasero** [comment]
On Windows and Linux we are now using custom select box (via https://github.com/Microsoft/vscode/pull/37533)
