### ISSUE TITLE
Show release notes info message after every update

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3525]
@bgse says:

>@egamma This might be a psychology thing. I guess when the update notification comes up, users can get a bit excited about new toys, and the obvious thing to do is to hit that update button asap.

>Maybe it would be a good idea to display the release notes notification again once the user starts the updated VSCode for the first time.

>E.g. "Visual Studio Code was recently updated. Do you want to read release notes now", offering options like "Release Notes", "Not now", "Do not ask again".

cc @pcgeek86 @egamma

**Comment by chrisdias** [comment]
perhaps we open browser after upgrade, same way we do for first time download.

**Comment by pcgeek86** [comment]
@chrisdias Please no. I hate it when applications open pages in web browsers. The experience needs to be more integrated. /cc @joaomoreno

**Comment by joaomoreno** [comment]
I think the message service will do just fine.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/13709038/27db44c8-e7b2-11e5-88ba-e9e77edc7fb5.png)
