### ISSUE TITLE
Saving an unchanged file still writes it to disk

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35256]
- VSCode Version: Code - Insiders 1.17.0-insider (e059563fb6b8905de79ac4c75be537bb6dc74f5f, 2017-09-27T09:56:06.042Z)
- OS Version: Windows_NT x64 10.0.17004

---

Steps to Reproduce:

1. Create an extension to creates a watcher on ts files:

```ts
const watcher = vscode.workspace.createFileSystemWatcher(
    new RelativePattern(
        vscode.workspace.workspaceFolders[0],
        '*.ts'))

watcher.onDidChange(x => console.log('change ' + x));
```

2. Open a workspace with this extension and browse to a ts file. Hit save a bunch of times

**expected**
The file has not changed and should not be written to disk here. No change even should be fired

**Actual**
On every save, we seem to rewrite the file to disk. This also triggers the on changed event each time

**Comment by bpasero** [comment]
No this works as designed, we update the modified time of the file when you save even if there is no change. People want this for live reload scenarios.
