### ISSUE TITLE
RelativePattern difference in behavior for single star glob patterns

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35257]
Testing #34831

- VSCode Version: Code - Insiders 1.17.0-insider (e059563fb6b8905de79ac4c75be537bb6dc74f5f, 2017-09-27T09:56:06.042Z)
- OS Version: Windows_NT x64 10.0.17004

---

Steps to Reproduce:

Try creating watchers for all ts files in the root folder (and not in sub folders) using `RelativePattern`:

```ts
const relativeWatcher = vscode.workspace.createFileSystemWatcher(
    new RelativePattern(
        vscode.workspace.workspaceFolders[0],
        '*.ts'))
relativeWatcher.onDidChange(x => console.log('relative change ' + x));

const globWatcher = vscode.workspace.createFileSystemWatcher(
    vscode.workspace.rootPath + '\\*.ts');
globWatcher.onDidChange(x => console.log('change ' + x));
```

**Expected**
Since a single star glob pattern is used, I initially thought these watchers should only fire when a top level ts file is changed. Changing a ts file is subfolder of the workspace should not trigger either.

**Actual**
The watcher using relative pattern is always fired, even when the ts file is in a subfolder.  The globWatcher is correctly only fired for ts files in the root

From the documentation of RelativeWatcher, I think this behavior is expected since the glob is only applied to the file. 

To get the glob `*` behavior, I also tried patterns such as:

```ts
 new RelativePattern(
        vscode.workspace.workspaceFolders[0],
        './*.ts')
```

and 

```ts
new RelativePattern(
        vscode.workspace.workspaceFolders[0],
        '\\*.ts')
```

Using these, the relative watcher is never fired.

**Comment by bpasero** [comment]
@mjbvz good catch, I changed the implementation so that the relative path (relative to the provided base) will be used for matching.
