### ISSUE TITLE
[feature-request] Clicking file tab should maximize file pane.

### ISSUE THREAD

**Issue by str** [Microsoft/vscode#35252]
- VSCode Version: 1.16.1
- OS Version: Ubuntu/GNU-Linux 17.04

Steps to Reproduce:

1. Open a file, should open the file in a file tab.
2. Double click in the file tab does nothing.
3. Explore pane and bottom pane should be minified to show only the file tab.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by str** [comment]
I don't think closing it is a good idea. I think it's better to tag it as 'backlog' or something similar. Closing the issue, puts it in the bucket of 'done or won't do at all', 

How will you then separate the 'to do' from the 'done' in 12 months?
