### ISSUE TITLE
RelativePattern not limiting watching to workspace subdirectory

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35255]
#34831

- VSCode Version: Code - Insiders 1.17.0-insider (e059563fb6b8905de79ac4c75be537bb6dc74f5f, 2017-09-27T09:56:06.042Z)
- OS Version: Windows_NT x64 10.0.17004

---

Steps to Reproduce:

1. 
```ts
    const watcher = vscode.workspace.createFileSystemWatcher(
        new RelativePattern(
            path.join(vscode.workspace.rootPath, 'sub'),
            '*.ts'))

    watcher.onDidChange(x => console.log('change ' + x));
````

2. Open a workspace and try editing and saving ts files in the root folder and then saving ts files under `sub`

**Expected**
Change only fires for ts files under `sub`

**Bug**
Change is fired for files under the root as well files under `sub`.

**Comment by bpasero** [comment]
@mjbvz thanks for actually testing this, the bug was bad enough that the relative pattern was actually not working at all...

**Comment by dbaeumer** [comment]
Verifiying...
