### ISSUE TITLE
PHP user defined snippets only work inside `<?php...?>`

### ISSUE THREAD

**Issue by standingdreams** [Microsoft/vscode#35250]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
expand-region|let|0.1.1
sublime-keybindings|ms-|2.9.1
vscode-versionlens|pfl|0.19.1
expand-selection-to-scope|vit|0.2.0

---

## Steps to Reproduce:
If you create a snippet in `php.json` to be used in a PHP file, VS Code will only display the snippet in quickSuggestions if you are inside of `<?php...?>`. I have a few snippets that should be used in a PHP file but not inside of `<?php...?>`.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Outside of the PHP tags, the file is actually considered as HTML, so you can add those to your HTML snippets.

**Comment by standingdreams** [comment]
I tried it previously and it wasn't working. NOW that you mention it....boom...it suddently (read: magically) wants to work.

Thank you @roblourens
