### ISSUE TITLE
[folding] Click in bottom part of editor expands last region regardless of where focus is

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#35259]
Testing https://github.com/Microsoft/vscode/issues/34989

Click in bottom part of editor expands last region regardless of where focus is.

**Actual**
![region expand](https://user-images.githubusercontent.com/173559/30938929-a7672630-a390-11e7-9b47-ca89708414b0.gif)

**Expected:**
Region only to get expanded once I click on the "expand icon" or when the next line is a folded region

**Comment by aeschli** [comment]
@alexandrudima Is there a way for me to find out if a position is below the last line?

**Comment by alexandrudima** [comment]
By definition, editor positions are within the text boundary, so when clicking below the last line of text, the editor position will be the last valid position in the file. Not sure what you'd want to find out?
