### ISSUE TITLE
C++ / clang code hints not working on windows 10

### ISSUE THREAD

**Issue by mike213** [Microsoft/vscode#35253]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
GBKtoUTF8|buk|0.0.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.3.0
vscode-author-generator|edw|0.0.4
react-native-react-redux|EQu|1.4.0
vscode-semistandard|fle|1.1.2
code-runner|for|0.7.1
CppSnippets|har|0.0.12
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
vue|jcb|0.1.5
Angular2|joh|2.7.0
clangcomplete|kub|0.0.6
cpptools|ms-|0.13.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.0
vetur|oct|0.9.10
tsimporter|pmn|1.2.14
java|red|0.10.0
vscode-icons|rob|7.14.0
java-snippets|tus|0.0.1
python-extended-snippets|tus|0.0.1
clang-format|xav|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.after installing clang completion tool,open a CPP file
2. At the beginning  put the cursor on some keywords and it works. However, several minutes later, when you put the cursor on some keywords again, it will become "initializing",but no any hints.
3. Even though restart, it does not work.
4. It worked properly on Windows 7, but it is in malfunction when I upgraded to windows 10.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
Please file the issue against corresponding c++ extension.
