### ISSUE TITLE
Problem matcher issues don't go away when problems are fixed, even when re-compiling and re-matching problems.

### ISSUE THREAD

**Issue by HazardDev** [Microsoft/vscode#35251]
- VSCode Version: 1.16.1
- OS Version:  macOS Sierra 10.12.6

Steps to Reproduce:

1. Use this task file to build any C source file that has errors
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"taskName": "Build",
			"type": "shell",
			"command": "gcc --std=c99 main.c -o main",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"promptOnClose": false,
			"isBackground": true,
			"presentation": {
				"echo": true,
				"reveal": "never",
				"focus": false,
				"panel": "dedicated"
			},
			"problemMatcher": ["$gcc"]
		}
	]
}
```

2. Fix the error, but have the error warnings not disappear, even on re-compile

Reproduces without extensions: Can't run this test, depends on C/C++ extensions.

I hope I'm not wasting anyone's time. However, I can't really tell if this is an issue with VSCode itself having issues re-checking problem output or if it's the C/C++ extension. The only way I've found to re-check these issues is to reload the window.

**Comment by sandy081** [comment]
Please file the issue against C++ extension.
