### ISSUE TITLE
HTML editor, highlight closing tag, instead of all tags.

### ISSUE THREAD

**Issue by str** [Microsoft/vscode#35261]
- VSCode Version: 1.16.1
- OS Version: Ubuntu/GNU-Linux 17.04

Steps to Reproduce:

1. Open an HTML file
2. put the cursor in an opening `<div>` tag
3. All `<div>` and  `</div>` tags are highlighted, and should not. Only the corresponding closing tag should be highlighted.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This works from me:
![image](https://user-images.githubusercontent.com/6461412/30969647-542943a8-a463-11e7-9fe9-1bad08487339.png)

Please make sure the editor mode is 'HTML' (not PHP). Also check again that no extension is active.
If you still see it, please add a code sample and reopen.

**Comment by str** [comment]
@aeschli You are right. This happens only for the "HTML (twig)" editor. How can I report this to the team that manages that plugin?

**Comment by str** [comment]
@aeschli  found it at https://marketplace.visualstudio.com/items?itemName=whatwedo.twig#qna

Thank you.
