### ISSUE TITLE
Marketplace returns 500 for long extension search text

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35262]
Testing #34122

Steps to Reproduce:

1. Paste the following single line string in the extension search box:

```
Alice was beginning to get very tired of sitting by her sister on thebank, and of having nothing to do: once or twice she had peeped into thebook her sister was reading, but it had no pictures or conversations init, ‘and what is the use of a book,’ thought Alice ‘without pictures orconversations?’So she was considering in her own mind (as well as she could, for thehot day made her feel very sleepy and stupid), whether the pleasureof making a daisy-chain would be worth the trouble of getting up andpicking the daisies, when suddenly a White Rabbit with pink eyes ranclose by her.
```

**Bug**
Marketplace returns a 500:

```
{"$id":"1","innerException":null,"message":"TF400898: An Internal Error Occurred. Activity Id: 369ab7d1-92d2-4d0d-8c18-9e37d1606065.","typeName":"System.Data.SqlClient.SqlException, System.Data","typeKey":"SqlException","errorCode":0,"eventId":0}
```

**Comment by sandy081** [comment]
Looks like the market place has lesser limit now. It fails with following text whose length is `196`

```
Alice was beginning to get very tired of sitting by her sister on thebank, and of having nothing to do: once or twice she had peeped into thebook her sister was reading, but it had no pictures or
```

**Comment by sandy081** [comment]
Market place has different limitations at different levels. From Market place team

>In Marketplace Web the current restriction is based on number of characters.  But in SQL query length it is based on number of words.
We have a backlog Item to refine this search restriction.
Till then, I would suggest to retain 200 characters limit in VScode (same as marketplace web site limit).

Since we are giving a query directly, we are hitting words limitation. As they suggested I will be sticking to 200 characters.
