### ISSUE TITLE
Syntax color of declared identifiers changes if type is present

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#35268]
In a const block, if a declaration is explicitly typed, the name is white, but if not, then it's light blue:

![screen shot 2017-09-27 at 3 04 38 pm](https://user-images.githubusercontent.com/63830/30940251-4979307c-a395-11e7-9cc9-d1fe1ef08c5b.png)

This can look strange:

![screen shot 2017-09-27 at 3 09 01 pm](https://user-images.githubusercontent.com/63830/30940400-d5234388-a395-11e7-8c54-40471033c6f0.png)

![screen shot 2017-09-27 at 3 13 12 pm](https://user-images.githubusercontent.com/63830/30940597-6e35802c-a396-11e7-8884-a478702c69bf.png)

Note that the syntax highlighting for variables is consistent in this case:

![screen shot 2017-09-27 at 3 16 10 pm](https://user-images.githubusercontent.com/63830/30940722-ebb64b26-a396-11e7-9c27-72ab11d03050.png)
![screen shot 2017-09-27 at 3 16 23 pm](https://user-images.githubusercontent.com/63830/30940723-ebbe7242-a396-11e7-8385-2a9c3b6e36e1.png)

@ramya-rao-a: Should all syntax highlighting issues be created with atom instead of here?

---

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
php-formatter|Sop|0.2.4
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
javadebugger|don|0.1.4
python|don|0.7.0
phpunit|ema|2.1.1
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
code-runner|for|0.7.1
vscode-javac|geo|0.0.46
phpcs|ika|0.7.0
Go|luk|0.6.65
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
cpptools|ms-|0.13.0
Ruby|reb|0.15.0
rewrap|stk|1.5.0
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Is it related to Go language?

**Comment by willfaught** [comment]
@sandy081 Just realized this wasn’t vscode-go. I used the help menu item to create the issue and forgot it would be an issue for vscode. I’ll move this to vscode-go.

**Comment by ramya-rao-a** [comment]
> Should all syntax highlighting issues be created with atom instead of here? 

We could do that. The only extra information they would need is the underlying scope and if it repros in Atom.

You can find the underlying scope by running the command `Developer: Inspect TM Scopes`. Then click on the text that you feel has the wrong color, you should see the scope name.

When you do create such issues in the atom/language-go repo, cc me there. So that I can provide any extra information that they might need.

**Comment by willfaught** [comment]
I might still file these issues in vscode-go if I don't have more time to investigate it at the time same that I'm reporting the problem.

**Comment by ramya-rao-a** [comment]
@willfaught That's alright too
