### ISSUE TITLE
Pressing enter replaces spaces with tabs in C++ files

### ISSUE THREAD

**Issue by peredin** [Microsoft/vscode#35260]
- VSCode Version: 1.16.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open or create a new C++ file and insert the following code:

[ht] means a literal tab-character. A . (dot) means "visible space".

```cpp
namespace MyProgram {
[ht]class Debug_generator : public Generator,
[ht]........................public Visitor,
```
2. Place the cursor directly after `Visitor,` and press Enter. The file contents is changed to:

```cpp
namespace MyProgram {
[ht]class Debug_generator : public Generator,
[ht][ht][ht][ht][ht][ht][ht]public Visitor,
```
I want to indent with tabs but align with spaces, VScode shouldn't replace anything unless I've explicitly requested VScode to do so.

I have disabled everything related to formatting that I've been able to find in the settings.json file.

If I set the filetype to `Plain Text` the line is left unchanged but the new line still gets tabs inserted automatically. I do not want VScode to do this either.

Reproduces without extensions: Yes

**Comment by peredin** [comment]
Same result when tested on 1.17.0-insider.

**Comment by peredin** [comment]
I did some testing after completely removing `indentationRules` from `vscode/extensions/cpp/language-configuration.json` and it appears to have solved the replacement-issue.

**Comment by alexandrudima** [comment]
We currently have no way to customize this.

**Comment by alexandrudima** [comment]
This is working as expected when using `editor.autoIndent = false`.

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
