### ISSUE TITLE
Content does not reflow on resize

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35264]
Testing #34868 

When the terminal has text flowing over many lines it does not reflow the text to full window size (or a reduced window size).

![image](https://user-images.githubusercontent.com/1051190/30939523-8854881c-a392-11e7-8e1e-c3657ee61bdd.png)

The native terminal does do this and this does work on Windows for our integrated terminal.

Sean

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
