### ISSUE TITLE
Emoji don't work in native Windows shells (WSL is fine)

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#35266]
- VSCode Version: Code - Insiders 1.17.0-insider (e059563fb6b8905de79ac4c75be537bb6dc74f5f, 2017-09-27T09:56:06.042Z)
- OS Version: Windows_NT x64 10.0.17004

---

Steps to Reproduce:

1. Bring up the emoji keyboard in windows
2. Select vscode terminal and try clicking on an emoji to insert it

**Bug**
Corrupted Unicode characters are inserted

![a](https://user-images.githubusercontent.com/12821956/30940048-8aed0688-a394-11e7-9f38-68accd57ecf4.gif)

**Comment by Tyriar** [comment]
Upstream: https://github.com/sourcelair/xterm.js/issues/469

**Comment by KillyMXI** [comment]
Looks like it's not even possible to paste emoji from clipboard.
And it also breaks everything if you paste combined characters...

**Comment by Tyriar** [comment]
@KillyMXI pasting emoji should work, it works differently to in the editor though. The representation of the emoji depends on the shell (eg. bash) which may have patchy support for combined emojis.

**Comment by KillyMXI** [comment]
Checked it once again.
OK, pasting is shell dependent. I think I was focused on GHCi at that moment. It works in PowerShell, although doesn't accommodate additional space for emojis (doubled character width for them would be nice in monospaced environment with majority of fonts). No combined *emojis* - OK, that must be tricky enough stuff for now.

But I meant any combined characters. Here I paste two characters - one is a single Unicode symbol and the other one is made of "e" symbol and combining acute accent mark:
https://i.imgur.com/INKihY6.gif
Cursor position is not synced with display after that.
(Should I open a separate issue for that?)

**Comment by warpdesign** [comment]
It's not a windows only issue. Same problem with macOS: #38064.

**Comment by mzkev** [comment]
I cant bring up the emoji keyboard in vscode on windows. Has this been fixed yet?

**Comment by gertcuykens** [comment]
Doesn't seem to be fixed

![image](https://user-images.githubusercontent.com/863731/49251047-cc637100-f420-11e8-8b06-72c313aade9b.png)

![image](https://user-images.githubusercontent.com/863731/49251103-eb620300-f420-11e8-91f7-fe054eb11c36.png)

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

https://github.com/matchai/spacefish/issues/118

**Comment by lucasjohnston** [comment]
Still not fixed - I'm having to abandon using emojis in my commit messages now on my mac 😢

**Comment by warpdesign** [comment]
It still doesn't work in macOS either:
 - using the Emoji panel from macOS to insert an Emoji does nothing at all
 - pasting an Emoji kinda works but there are problems: is several Emoji are pasted, using backspace after, too many characters are removed and you can even remove part of the prompt

**Comment by lgarron** [comment]
I've also had trouble inserting emoji on macOS. I assumed I was doing something wrong or had a transient issue, but I still see the same issues that @warpdesign describes. :-(

**Comment by Ciantic** [comment]
I'm used to having Haskell prompt with a pickle (for obvious reasons) in front:
```
:set prompt "🥒 >>> "
```

It works with VSCode when it's running bash e.g. inside docker container development. But it ceases to working when I use it inside Powershell in Windows.

Just giving me:

```
≡ƒÑÆ >>>
```

I think this is some Powershell/Windows problem.

**Comment by stam** [comment]
Still not fixed? This bug requires me to switch to Iterm and leave my vscode focus in order to commit...

**Comment by Dc9894** [comment]
I don't think it's just related to the shell you are using I'm using powershell core as the default integrated terminal and though I can get some emojis typed in there, the characters before and after look weird if shown at all

**Comment by ListsOfArrays** [comment]
Path names with emojis in them also result in issues. I have a preview edition of PowerShell installed that supports that, but VS Code both inserts a junk character and results in the terminal being off by two characters when typing & displaying inputs:
![image](https://user-images.githubusercontent.com/10949346/82764968-e943ef00-9de0-11ea-99a4-7132f159adca.png)
vs the vanilla PowerShell terminal:
![image](https://user-images.githubusercontent.com/10949346/82764981-037dcd00-9de1-11ea-8d54-5551b45f5c38.png)

**Comment by nijikokun** [comment]
I'm receiving a similar issue using Git Bash on Windows:

![image](https://user-images.githubusercontent.com/198276/84229222-e3673280-aa9d-11ea-9070-cf3951ad3739.png)

**Comment by ColinTimBarndt** [comment]
When using the Terminal, I encounter the exact same problem with the junk characters, as @ListsOfArrays mentioned, but when using the debugger (Rust), all emojis work correctly, probably because it's not using the PowerShell. There has to be an error in the communication between PS and VSC.

**Comment by slinkardbrandon** [comment]
Today I got really sad when I couldn't commit with an emoji, guys this is breaking people's hearts.

**Comment by windcheck** [comment]
Using Windows Terminal powershell runs without problems. When I go to VS code integrated powershell it's broken. See screenshot.

![stack1](https://user-images.githubusercontent.com/30125276/95688424-6c26e400-0be0-11eb-9d71-2f51ac6e4a3a.jpg)

**Comment by ynechaev** [comment]
This issue has nothing to do with PowerShell or VSCode, it's actually related to *xtermjs* issue https://github.com/xtermjs/xterm.js/issues/469 and it was mentioned above.

**Comment by Tyriar** [comment]
Note that this issue is about emoji _IMEs_ which are the popup you can use to input emojis. Simple support for them is patchy because WT and conpty seem to do something a little different to what they're trying to emoji, that's tracked in https://github.com/xtermjs/xterm.js/issues/2693

**Comment by regalstreak** [comment]
Any workaround for this? @Tyriar Been facing this for years

**Comment by andy3520** [comment]
😟 Still cannot add awesome emoji to git commit by using ctrl+cmd+space. I have to use source control in the vscode or insert the emoji some then copy + paste it to the terminal

**Comment by jv-k** [comment]
This is a good workaround until the 🐞 is fixed:

https://marketplace.visualstudio.com/items?itemName=bierner.emojisense

Works in the terminal as well. In MacOS you can use `cmd + i` to bring up the emoji panel and easily insert.

**Comment by Tyriar** [comment]
Our support right now seems about as good as Windows terminal, the emoji selector doesn't work but you can write emojis to the terminal:

![image](https://user-images.githubusercontent.com/2193314/125966645-c7af66c5-2720-4600-8c02-92262d7c1737.png)

WT:

![image](https://user-images.githubusercontent.com/2193314/125966710-234bc4f5-8eef-486e-9921-278a4c842543.png)

**Comment by Tyriar** [comment]
Message sent to pwsh:

![image](https://user-images.githubusercontent.com/2193314/125967289-c7238c9d-6067-4a4b-8cb0-0bbc61cd250c.png)

Message received from pwsh 7.0.1:

![image](https://user-images.githubusercontent.com/2193314/125967326-40a0c6ff-a8c0-42c2-9657-d52311263fd5.png)

**Comment by Tyriar** [comment]
Related: https://github.com/PowerShell/PowerShell/issues/15256

**Comment by Tyriar** [comment]
Ok this is definitely an upstream issue: https://github.com/microsoft/terminal/issues/190

FWIW emoji support works fine in wsl which proves we're doing the right thing (plus mac/linux works fine):

![image](https://user-images.githubusercontent.com/2193314/125968015-d76e1c51-558d-4886-90d4-214afa5d3feb.png)

I'll keep this open as it's a pretty big issue but it's just tracking the upstream issue.

**Comment by ullaskunder3** [comment]
@Tyriar sir is there any fix?
2021 still the same problem in vs code default bash terminal  
If I add emoji from Win emoji picker it just show `<?>`
![image](https://user-images.githubusercontent.com/66258652/139595780-ee094ee4-592e-4f38-ac4c-e481469a3f0e.png)

**Comment by erhanertem** [comment]
> @Tyriar sir is there any fix? 2021 still the same problem in vs code default bash terminal If I add emoji from Win emoji picker it just show `<?>` ![image](https://user-images.githubusercontent.com/66258652/139595780-ee094ee4-592e-4f38-ac4c-e481469a3f0e.png)

Use powershell therminal in vscode....It works fine. Bash still problematic.
