### ISSUE TITLE
Mac press and hold accent character insertion does not update suggestions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35269]
- VSCode Version: Code - Insiders 1.17.0-insider (e059563fb6b8905de79ac4c75be537bb6dc74f5f, 2017-09-27T09:42:20.756Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

Using a mac

1. Ensure word based completions are enabled
1. Create a blank text file with the contents:

    ```
    abc
    äbc

    ```

2. On the last line, press and hold the a key until the alternative character selector is shown.
3. Select ä from here

**Bug**
The suggestion list is not updated after the `a` is replaced with `ä`. It is updated if you trigger the suggestion list again:

![sep-27-2017 15-33-17](https://user-images.githubusercontent.com/12821956/30941226-4065adae-a399-11e7-8827-c30013d8a827.gif)

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@jrieken there is no cursor position change in this case

**Comment by jrieken** [comment]
>  there is no cursor position change in this case

Yeah, that's what I am looking for....
