### ISSUE TITLE
Emmet suggests typed text as is for css 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#35267]
Happens only in Insiders when the css property value is added right after the `:`
Doesnt occur if there is space after the `:`

![image](https://user-images.githubusercontent.com/16890566/30940418-e556cbee-a395-11e7-837f-b9a440cb7910.png)
![image](https://user-images.githubusercontent.com/16890566/30940575-5ad1d5b2-a396-11e7-85de-b1d53c6af6c5.png)

Previously in Stable 1.16.1, we would have gotten 

![image](https://user-images.githubusercontent.com/16890566/30940606-7859b7e4-a396-11e7-9161-e43e2ffb7bd5.png)

**Comment by ramya-rao-a** [comment]
In 1.17 we introduced a min score that fuzzy matching in emmet needs to get to offer a suggestion.

So for `background:u` , `background-attachment: unset` was suggested before. This match had a low score, lesser than the min score

So in 1.17, `background-attachment: unset` doesnt make the cut, so emmet falls back to suggesting what  was typed.

**Comment by aeschli** [comment]
Verified in Version 1.17.0-insider
Commit 3831ef5e2ca82e7040cca4af44d76d064f9430a5
Date 2017-09-28T08:43:06.798Z

The 'n' proposal is no longer present.
