### ISSUE TITLE
Cannot read terminal content - nano

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35265]
Testing #34868 

When I load up Nano I can;t see the control chars at the bottom and also their are some strange artifacts at the top of the terminal.

![image](https://user-images.githubusercontent.com/1051190/30939935-181ff106-a394-11e7-80ed-bfa93a9e1621.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35151
