### ISSUE TITLE
"Extension host terminated unexpectedly." error wont go away.

### ISSUE THREAD

**Issue by august-norkko** [Microsoft/vscode#35271]
I am not getting rid of this error for the life of me. Uninstalling extensions, reinstalling and trying 
different versions wont remove it.

Extensions I had previously:
Code Runner,
git, 
Language Support for Java(TM) by Red Hat,
Javascript Standard Style,
vscode-icons

https://imgur.com/a/BICY4

- VSCode Version: 1.16.1
- OS Version: Win 10 Home 10.0.15063 Build 15063

Steps to Reproduce:

1. Run Visual Studio Code.
2. Receive error.

Reproduces without extensions: Yes

**Comment by august-norkko** [comment]
Running with code.exe --disable-extensions does not fix it. Reinstalled node as well, no change.

**Comment by august-norkko** [comment]
@alexandrudima All the time, even when I open a new empty window.

**Comment by august-norkko** [comment]
@alexandrudima I tried the 64-bit version and still getting the error.

**Comment by alexandrudima** [comment]
Thanks for trying. Let's try to see if the data dir is corrupt:

From the place you have unzipped, in a command prompt, can you please try:
`code --user-data-dir="`

**Comment by august-norkko** [comment]
@alexandrudima Application starts normally from command prompt with that line but still receiving the error.

**Comment by alexandrudima** [comment]
I'm sorry, I'm starting to run out of ideas (without any error message except the segmentation fault). How about we check if one of our built-in extensions causes the segmentation fault. Could you please try:

In the folder you have extracted, go to the folder `resources/app` and rename the folder `extensions` to `extensions1` and create a new empty folder `extensions`, close all instances of VSCode (also check via Task Manager for any leaky processes) and run again with `code --user-data-dir=''`.

**Comment by august-norkko** [comment]
I am happy to tell you that after renaming extensions to extensions1 and creating an empty folder the error stopped, having the appication run by `code --user-data-dir=''`.

**Comment by alexandrudima** [comment]
Ok, this makes me think the error is triggered by one of our extensions that activates on startup.

So it would be one of:
* vscode.emmet
* vscode.git
* vscode.merge-conflict

Can you please move folders one-by-one back from `extensions1` to `extensions` to see which one of these built-in early activation extensions are to be blamed ?

**Comment by august-norkko** [comment]
Will do, do you want me to run vscode with `code --user-data-dir=''` everytime?

**Comment by alexandrudima** [comment]
If `code` doesn't crash, the `--user-data-dir=''` is not necessary anymore

**Comment by alexandrudima** [comment]
I will be offline for a while. if it turns out to be `vscode.git`, we have a setting `git.enabled` that you can set to false in your proper VSCode installation. I don't think we have *disable*-like settings for the other extensions.

**Comment by august-norkko** [comment]
Yeah. It was `vscode.git` that was the problem. Will do as you suggested, thanks for the help.

**Comment by joaomoreno** [comment]
Interesting... @august-norkko Do you have git installed in your system?

Related: #32739

**Comment by august-norkko** [comment]
@joaomoreno Yes, version 2.14.1.windows.1.
