### ISSUE TITLE
Keyboard navigation across word-boundaries doesn't feel right

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#3527]
Right now, the cursor in vscode jumps from the ending of one word to the ending of the next even when there are spaces and other characters between them.

Demo (with a pipe as my current cursor `|`, and repeated presses <kbd>Ctrl+Right</kbd>)

```
"|command": "actions.find"
"command|": "actions.find"
"command": "actions|.find"
```

Expected (sublimetext)

```
"|command": "actions.find"
"command|": "actions.find"
"command":| "actions.find"
"command": "actions|.find"
```

I think another related issue is that there is no setting in vscode (that I could find) of specifying the word separators (regex) such as in Sublime - or there should be a sub-word navigation option.

This was discussed here earlier: https://github.com/Microsoft/vscode/issues/3249

**Comment by alexandrudima** [comment]
@kumarharsh Thank you for the feedback. In the upcoming 10.10, the word navigation has been refurbished and these will be the new stops for <kbd>Ctrl+Right</kbd> for your example:

```
|"command": "actions.find"
"|command": "actions.find"
"command|": "actions.find"
"command":| "actions.find"
"command": "|actions.find"
"command": "actions|.find"
"command": "actions.|find"
"command": "actions.find|"
"command": "actions.find"|
```

There will also be a new setting `editor.wordSeparators` where you can customize what a word is.

**Comment by gordey4doronin** [comment]
What about camel case?

|"commandCamelCase": "actions.find"
"|commandCamelCase": "actions.find"
"command|CamelCase": "actions.find"
"commandCamel|Case": "actions.find"
"commandCamelCase|": "actions.find"

**Comment by kumarharsh** [comment]
@gordey4doronin that is *subword* navigation, which is being discussed in another issue.

**Comment by gordey4doronin** [comment]
@kumarharsh Yes, I saw the issue #541

However.. I'm curious why we call it _subword_?

If we have something like this `command-with-few-words`, then it works fine.
It sees there are 4 word separated with `-` symbol which is taken from `"editor.wordSeparators": "~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"`.

And when we have `commandWithFewWords`, why it became _subwords_ rather than _words_?
My expectation is `vscode` needs to understand that camel-case is also some kind of a word separator.

@alexandrudima What do you think?

**Comment by alexandrudima** [comment]
You are correct, they are very similar in nature.

But technically, one is called word navigation (as it involves separator characters between groups of characters that become a word, so `command-with-few-words` is a group of characters containing 4 words if `-` is defined as a separator) and one is called subword navigation (as it involves examining the contents of a word `commandWithFewWords` is a group of characters containing 1 word and 4 subwords).

They usually have different implementations and the latter involves some interesting questions about localization `myÜberCoolWord`, therefore making it non-trivial to implement correctly.

**Comment by kumarharsh** [comment]
@alexandrudima Oh... I was going to take a shot at it this weekend, but hadn't thought the case for localization at all. :disappointed:
