### ISSUE TITLE
Custom aliases for quick open shortcuts (view, task, debug, etc)

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35278]
I use the quick open shortcuts pretty often, and I want them to be accessible but don't want to come up with new shortcuts for all of them. In the terminal I usually assign one or two letter shortcuts to commands that I use often, so it would be awesome if I could customize the command palette in the same way.

For example, I might want to type `db` to get a list of debug configs instead of `debug`, or `t` for tasks.

```
"workbench.quickOpen.aliases": {
  "db": "debug ",
  "t": "task ",
  // or maybe symbols
  "!": "view ",
  // or for the command palette beyond the existing shortcuts
  "x": ">extensions:"
}
```

**Comment by bpasero** [comment]
@roblourens can't you do this from an extension?

**Comment by roblourens** [comment]
I don't think so? I don't think an extension can register a quick open handler like that?

Maybe you could make something work with a custom quick pick, then calling "Run Task" if they type the right alias, but it's not really the same.

**Comment by bpasero** [comment]
@roblourens I see, yeah extensions cannot hook into the quick open stuff like that, only via picker, which is not the same.

**Comment by bpasero** [comment]
Looks like this is https://github.com/Microsoft/vscode/issues/3380
