### ISSUE TITLE
No switch SCM GIT provider menu

### ISSUE THREAD

**Issue by matteoLorenzini** [Microsoft/vscode#35270]
- VSCode Version:1.16.1
- OS Version:Ununtu 16.04 LTS
-GIT Version: 2.7.4

Steps to Reproduce:

1. I'm going to clone a GIT repo in my local GIT folder
2. When I'm in VSCode doesn't switch automatically to SCM Git provider interface and, if I'm going to try to switch from the menu there's no GIT option.
3. I still have the default view insted of GIT (with GIT icon on the sidebar)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Show me a screenshot of what you mean by _the default view insted of GIT_.

Also, what exactly do you mean by _I'm going to clone a GIT repo in my local GIT folder_? Where do you clone it to? Is Code open in some folder?

**Comment by matteoLorenzini** [comment]
Basically I have this 

![selezione_001](https://user-images.githubusercontent.com/6868238/30957817-94fecc4a-a43b-11e7-84b1-05862b3e72f1.png)

instead of this

![versioncontrol_overview](https://user-images.githubusercontent.com/6868238/30957531-d4404efc-a43a-11e7-957c-93e8a9b28c81.png)

**Clone GIT repo:** 

-  Creation of an empty folder i.e /home/matteo/GitRepo

-  From /home/matteo/GitRepo  git clone https://github.com/acdh-oeaw/parthenos_mapping.git (using the GUI provided by VSCode...but I have the  same mistake even by terminal)

**Comment by joaomoreno** [comment]
Which folder do you have open in Code, in this example?

- `/home/matteo/GitRepo`
- `/home/matteo/GitRepo/parthenos_mapping`

?

**Comment by matteoLorenzini** [comment]
sure...here the screencast
[video.mkv.zip](https://github.com/Microsoft/vscode/files/1340534/video.mkv.zip)

**Comment by joaomoreno** [comment]
Everything seems to be working... You just cloned your repository. You have no changes... What is the problem?
