### ISSUE TITLE
SCM Viewlet hides "Source Control Providers" panel with only one folder in workspace

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#35279]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Have only one git repo / folder in your workspace 
2. Open the SCM Viewlet, notice that the Source Control Provider's panel isn't visible
3. Add another folder to the workspace
4. Notice that they Source Control Provider's panel is now visible, and lists two providers

Is this intended behavior? I find it confusing to have the panel be hidden like that when I am working with a single repository - I expect the UI to be consistent.

**Comment by ggilmore** [comment]
I created a PR for this here: https://github.com/Microsoft/vscode/issues/35279. If this intended behavior, feel free to close it.

**Comment by joaomoreno** [comment]
It is intended behaviour, we're trying to save space and keep the UI minimal. Thanks for the PR tho.
