### ISSUE TITLE
Source origin is not shown for "loaded script"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#35277]
- Debug a node app with node2
- Open `fs.js` from the sidebar, or from the loaded sources picker
- It doesn't show the origin, `read-only core module`

If I open a node_internals script from the callstack, it does show the origin.

The loaded source event looks like `{"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"fs.js","path":"<node_internals>/fs.js","sourceReference":1022,"origin":"read-only core module"}}}`

**Comment by isidorn** [comment]
I think this is the current limitation of our extension API, namely the node extension can not pass the `description` from the extension API [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/loadedScripts.ts#L354) when opening an editor as I am doing internally [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugSource.ts#L61)
Forwarding to @weinand

**Comment by weinand** [comment]
@isidorn yes, I'm not (yet) passing the origin via the document uri. 
But I could certainly do this with an additional query parameter.
