### ISSUE TITLE
running build task switches focus to terminal task output no matter what

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#35273]
- VSCode Version: 
`Version 1.16.1 (1.16.1)`
- OS Version:
`macOS 10.12.6`

Steps to Reproduce:

1.  Use a tasks.json like this
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "problemMatcher": ["$tsc"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
      }
    }
  ]
}
```
2. Switch to 'Problems' pane
3. Build on a project with an error
4. You are now in 'Terminal' pane and have to manually switch back to 'Problems' pane if you want problemMatcher issue navigation

Tried with and without presentation and with various combinations of presentation options above.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@breathe that is controllable via the `"reveal"` property. Simple set it to `"never"`
