### ISSUE TITLE
Cannot local right path files under 'symbol link' that created by 'mklink /j'

### ISSUE THREAD

**Issue by eeropp** [Microsoft/vscode#35283]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|don|0.7.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
vscode-icons|rob|7.14.0

---

Steps to Reproduce:
If we have a code project folder d:\TestProject
1. mklink /j e:\TestProject d:\TestProject, so we can have a symbol link folder in e:\TestProject
2. open e:\TestProject with VSCode
3. open any file under the project in VSCode, we can see the path is d:\TestProject\..., not e:\TestProject\...

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I know we have a duplicate for being able to disable resolving symlinks on startup. Sorry, cannot find it right now :-/
