### ISSUE TITLE
[loc][query] Typo in source string: Aquiring ->Acquiring 

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#35284]
String text: Aquiring user code failed
Context
extensions/azure-account/out/azure-account:English (en):plaintext:azure-account.userCodeFailed
Resource
azure-account

String text: Aquiring token with device code
Context
extensions/azure-account/out/azure-account:English (en):plaintext:azure-account.tokenFailed
Resource
azure-account

See: https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#es/$/117123262?issue=yes

**Comment by danyeh** [comment]
This one still repro.
String text: Aquiring token with device code
Context
extensions/azure-account/out/azure-account:English (en):plaintext:azure-account.tokenFailed
Resource
azure-account

See: https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#es/$/117123262?issue=yes

**Comment by chrmarti** [comment]
We still need to publish the extension it seems. I'm planning to do so next week. (Adjusting target milestone to reflect that.)
