### ISSUE TITLE
使用空格进行缩进时，从Code复制到OneNote（桌面版）的内容没有缩进了

### ISSUE THREAD

**Issue by teclxl** [Microsoft/vscode#35288]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
java|red|0.10.0

---
**原始显示**
![image](https://user-images.githubusercontent.com/11850956/30947919-24798e48-a43f-11e7-84e2-3262115f6370.png)

**复制到OneNote，颜色显示能保留，但行前空格都没有了。将空格替换成制表符后复制到OneNote，颜色显示能保留，位置正常。**
![image](https://user-images.githubusercontent.com/11850956/30948011-a4157388-a43f-11e7-843b-c2a312cdbf43.png)

不带格式复制到时（例如复制到eclipse），空格是正常的。

**Comment by sandy081** [comment]
Sorry closing it. Please file the issue in English.
