### ISSUE TITLE
Horizontal scrolling in explorer file list

### ISSUE THREAD

**Issue by jack-chung** [Microsoft/vscode#35282]
With long file names or files in many levels deep, it is not easy to see the files unless I resize the pane.

**Comment by joshuawilson77** [comment]
I whole-heartedly agree with this Issue. In fact, this may be the only thing I would add to Code.

**Comment by blackbetty** [comment]
Agreed, this is standard behavior in most editors/IDEs/general tools I've used. Seems like a bug from my perspective.
