### ISSUE TITLE
Click `create new file` icon, layout  break littles

### ISSUE THREAD

**Issue by suhaotian** [Microsoft/vscode#35281]
- VSCode Version: 1.16.1
- OS Version: windows 7

Steps to Reproduce:

1. Click `Create new file` icon for two twice;
2. Two input boxes appears:

![image](https://user-images.githubusercontent.com/6512574/30946608-a3023a4c-a437-11e7-8c79-c90e25cc7e85.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Only for a short period of time, do you get that state constantly?
Can you also reproduce with latest vscode insiders 
https://code.visualstudio.com/Insiders/

**Comment by suhaotian** [comment]
Latest vscode insiders is ok! close it.
