### ISSUE TITLE
[loc][query] Please clarify where does "Editing evolved" show

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#35287]
String text: Editing evolved
Context
src/vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page:English (en):plaintext:welcomePage.editingEvolved
Resource
vs_workbench_parts_welcome

Query: Is it a slogan in isolated area? Where does it appear in software? Accept levrik's suggestion to revert German translation to English may be a good idea.
levrik wrote: I already stumbled over this translation very often and thought about a better one since the current one actually just means "Advanced editing" what does not really match the meaning of the English one. I would suggest to not translate this slogan/tagline. Don't think it really needs a translation at all.
Is that means "The thing, editing, evolved better" ?

Reference: https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/111041640?issue=yes

**Comment by chrmarti** [comment]
It is shown as the subtitle on the Welcome page (Help > Welcome - if not already shown):
![image](https://user-images.githubusercontent.com/9205389/30973005-eb338f9e-a420-11e7-850e-a3008815de18.png)
