### ISSUE TITLE
No intellisense in C#

### ISSUE THREAD

**Issue by leocrespo** [Microsoft/vscode#3529]
Intellisense just doesn't work. 

![screen capture on 2016-02-28 at 13-09-47](https://cloud.githubusercontent.com/assets/2193314/13377654/233e1bd4-dd99-11e5-8c39-1d8b1321f1ff.gif)

How can this possibly be a tool to create C# code without any intellisense?

**Comment by chrisdias** [comment]
@leocrespo IntelliSense for C# is driven off of the project type, you need to have an MSBuild project that can be loaded OR an ASP.NET Core 1.0 project in order for it to work. Check out http://code.visualstudio.com/docs/runtimes/ASPnet5 for more information. 

Also, please submit issues in the https://github.com/omnisharp/omnisharp-vscode repository, which is the C# extension for VS code.

**Comment by leocrespo** [comment]
Thank you for your reply Chris, however there isn't any option for me to create a project (is "New Project" menu item missing?), and I want to work on a Class Library. The page you pointed out, http://code.visualstudio.com/docs/runtimes/ASPnet5, has nothing on this.

I appreciate your reply. I am however disappointed with this tool. How basic is Intellisense? Isn't it obvious that whatever instructions are needed to get Intellisense on VSCODE for bloody C# need to be really freaking obvious if they're not on by default?

**Comment by chrisdias** [comment]
I agree, our C# story needs improvement. We're early in this journey and our E2E experience will get better. I should have also referred you to the C# doc that gives you a little more background on what we do and do not support today: http://code.visualstudio.com/docs/languages/csharp.  

VS Code doesn't have the notion of a New Project dialog as is in the traditional Visual Studio IDE. Code is more aligned with editors such as Sublime or Notepad++ where you scaffold projects outside of the tool. ASP.NET has a yeoman generator to create applications (see [docs.asp.net for an additional walkthrough](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-app-using-vscode/#create-the-web-app)).

Going forward [.NET Core 1.0](https://docs.asp.net/en/latest/conceptual-overview/dotnetcore.html) will have a scaffolding tool for creating traditional console/class library/etc. applications.  Debugging support is also on its way.  

Again, sorry for the rough edges, your feedback is certainly valid and we'll continue to work on the e2e experience.  

CC @DustinCampbell @AnthonyDGreen

**Comment by leocrespo** [comment]
That page http://code.visualstudio.com/docs/languages/csharp says 
"IntelliSense just works hit ⌃Space at any time to get context specific suggestions."

However this isn't true. InstelliSense does not work. To prove the point, just open any .cs file with VS Code and see if works. I don't know what a yeoman is, all I wanted was a C# editor for OSX and one of the very basic requirements was Intellisense. Notice I said "C# editor", not ASP.NET editor. 

It's 2016 and we've become used to good software by now. While I understand that you're trying to help, the fact that this is being marketed as a C# editor, even though it doesn't have the features listed on the site, is very misleading.
