### ISSUE TITLE
CPU usage getting very high after updating to latest version. Git process from VS is taking almost 80 instance of CPU usage.

### ISSUE THREAD

**Issue by yjagdale** [Microsoft/vscode#35292]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.0

![image](https://user-images.githubusercontent.com/17045535/30949688-76bb914c-a435-11e7-89c2-36e82d787493.png)

Reproduces without extensions: Yes/No 
![image](https://user-images.githubusercontent.com/17045535/30949673-672efac0-a435-11e7-9b7d-bf2edd97c8fd.png)

**Comment by joaomoreno** [comment]
@yjagdale If you double click on that process... what's the full command line of it?

**Comment by guhuajun** [comment]
Same here. I am using vscode 1.16.1.

![default](https://user-images.githubusercontent.com/14121694/30997362-ead42fc0-a4f9-11e7-8c65-68f39a9f6ec8.png)

**Comment by joaomoreno** [comment]
What happens if you run one of those commands in a Command Prompt? Let's say:

```
git show :api/models.py
```

Does the command return immediately?

What's your git version?

**Comment by agabhane** [comment]
Same is happening with me.

![image](https://user-images.githubusercontent.com/8133509/31015484-fa180eb8-a53d-11e7-826e-9a4facd48247.png)

VS Code: 1.16.1
Git: 2.14.2

**Comment by agabhane** [comment]
Also it it creating too many processes of vs code

![image](https://user-images.githubusercontent.com/8133509/31016051-c5317c90-a540-11e7-9b5f-0bf8ea9df340.png)

As soon as you open VS code, Code.exe and git.exe instances are getting created.

**Comment by guhuajun** [comment]
@joaomoreno It takes 3.x seconds to complete.

![default](https://user-images.githubusercontent.com/14121694/31040854-dcb9b3cc-a5be-11e7-900a-2012125dfca4.png)

**Comment by guhuajun** [comment]
https://github.com/git-for-windows/git/issues/1129

Trying to upgrade git and my driver to latest version.

**Comment by joaomoreno** [comment]
This seems to be git issues. Make sure you have the latest.
