### ISSUE TITLE
Emmet: descending order is not supported when using repeater in abbreviations

### ISSUE THREAD

**Issue by 300d** [Microsoft/vscode#35296]
The similar commands of "ul>li.item$@-*5" can't be interpreted correctly by emmet.
![issues](https://user-images.githubusercontent.com/29995008/30951802-68894732-a457-11e7-8270-606b4cf26266.png)
.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.9
vscode-great-icons|emm|2.1.16
Angular2|joh|2.7.0
Angular-BeastCode|Mik|4.4.2
atom-keybindings|ms-|3.0.2
cpptools|ms-|0.13.0
debugger-for-chrome|msj|3.3.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Upstream issue: https://github.com/emmetio/html-transform/issues/2

**Comment by ramya-rao-a** [comment]
https://github.com/emmetio/html-transform/issues/2 has been fixed by @gushuro 
The changes have been absorbed to the emmet extension via https://github.com/Microsoft/vscode/commit/41e7dbc0df0d5be8dee67b2d1a0f66152a15b170
