### ISSUE TITLE
Set Zoom reset by keyboard to Ctrl+0

### ISSUE THREAD

**Issue by pkirchner** [Microsoft/vscode#35298]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 17.0.0
- Extensions: none
---

Steps to Reproduce:

1. Zoom in (e.g. CMD+)
2. Try to reset with a MacBook or small keyboard

You are not able to use the Key Combination CMD+NumPad0 because that key does not exist on many Mac-Keyboards.

**Comment by alexandrudima** [comment]
`cmd+0` is taken out-of-the-box by Focus into Side Bar. The zoom can be reset from the View menu or you can bind `cmd+0` by opening `cmd+k cmd+s`, searching for "reset zoom" and clicking on the edit button.

@bpasero Perhaps at one point we should align `cmd+0` to reset zoom, like in browsers.

**Comment by bpasero** [comment]
Not planned to change this. keybindings can be configured.
