### ISSUE TITLE
Select All keyboard shortcut fails in save dialog 

### ISSUE THREAD

**Issue by erikmedk** [Microsoft/vscode#35299]
- VSCode Version: 1.16.0 (1.16.0) 27492b6bf3acb0775d82d2f87b25a93490673c6d
- OS Version: macOS 10.12.6 (16G29)

Steps to Reproduce:

1. Create new file with ⌘N
2. Save file with ⌘S
3. In the save dialog, the ⌘A keyboard shortcut does not select all text in neither the "Save as:" nor "Tags:" fields.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
We fixed this for 1.17.
