### ISSUE TITLE
Angular Language Service Keeps Crashing

### ISSUE THREAD

**Issue by perceptron007** [Microsoft/vscode#35293]
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:35] Connection to server is erroring. Shutting down server.
[Error - 10:37:37] Server initialization failed.
Error: Connection got disposed.
	at Object.dispose (/home/spock/.vscode/extensions/Angular.ng-template-0.1.7/node_modules/vscode-jsonrpc/lib/main.js:675:25)
	at Object.dispose (/home/spock/.vscode/extensions/Angular.ng-template-0.1.7/node_modules/vscode-languageclient/lib/main.js:69:35)
	at connection.shutdown.then (/home/spock/.vscode/extensions/Angular.ng-template-0.1.7/node_modules/vscode-languageclient/lib/main.js:924:28)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)

This error Keeps appearing and after sometime all the extension stops working.

**Comment by sandy081** [comment]
Please file an issue against respective extension
