### ISSUE TITLE
Auto guess encoding "big5" is not equal to "Big5"

### ISSUE THREAD

**Issue by RayWings** [Microsoft/vscode#35290]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows 10 x64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ftp-simple|hum|0.5.7
debugger-for-chrome|msj|3.3.0
---
Some of my file is encoding by Big5 (Traditional Chinese)
Visual Code autoGuessEncoding may random open them by encoding "big5" or "Big5" .
But "big5" is not equal to "Big5".
And big5 may cause some chinese word error.

Currently known word : "都" "起" "者"

**Comment by bpasero** [comment]
@RayWings can you attach such a file?

**Comment by RayWings** [comment]
Visual Code Auto detect
![image](https://user-images.githubusercontent.com/20767845/31106360-c38018ea-a81d-11e7-89e2-4877dea6e2c8.png)
I change the encoding
![image](https://user-images.githubusercontent.com/20767845/31106386-ea9bf7f0-a81d-11e7-9aaf-791b909bd03e.png)
Error
![image](https://user-images.githubusercontent.com/20767845/31106377-d371ee72-a81d-11e7-814a-1353d35d3971.png)
Notepad++ and Explorer cannot read this word
![image](https://user-images.githubusercontent.com/20767845/31106433-326a5dba-a81e-11e7-86a4-96f8eabf5916.png)

**Comment by RayWings** [comment]
That word is at line:123
[unihome_paper.txt](https://github.com/Microsoft/vscode/files/1350912/unihome_paper.txt)

**Comment by bpasero** [comment]
@RayWings how did you get from `Big5` to `big5` in the last screenshot?

**Comment by RayWings** [comment]
In the last screenshot ,
I reopen that HTML file , and Code auto detect to `big5`

**Comment by bpasero** [comment]
Thanks
