### ISSUE TITLE
Cann't open big file

### ISSUE THREAD

**Issue by signhuwei** [Microsoft/vscode#35305]
I have a 20k lines JS file
When i open it,VSCode dumped

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-npm|fkn|3.3.0
live-html-previewer|hdg|0.3.0
vetur|oct|0.9.10
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@signhuwei  Can you please share the file that causes VS Code to crash? If that is not possible, can you perhaps share a file similar or perhaps a script that generates a file with similar properties that causes VS Code to crash ?
