### ISSUE TITLE
New icon in stable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35304]
**Verify (macOS, Linux, Windows):**
* the new icon is in and its the orange VSCode logo with full border shape
* Test the icon shows up in
** Windows
*** [ ] Task Bar
*** [ ] Window
*** [ ]  File associations
*** [ ] Letterpress background (when no editor is opened)
*** [ ] Welcome (icon for the tab)
*** [ ] Installer
*** [ ] Tile in the Start Menu ("pin to start")
** Linux
*** [ ] Dock
*** [ ]  Window
*** [ ] Letterpress background (when no editor is opened)
*** [ ] Welcome (icon for the tab)
** macOS
*** [ ] Dock
*** [ ]  File associations
*** [ ] Letterpress background (when no editor is opened)
*** [ ] Welcome (icon for the tab)

Note: sometimes the OS decides to cash the old icon. In that case, try to uninstall and reinstall. On Windows there is a trick to flush the icon cache: from an admin powershell session, run (ls `“$env:ProgramData\Microsoft\Windows\Start Menu\Programs\[Shortcut].lnk”).lastwritetime = get-date` where Shortcut is the VScode name.

**Comment by jrieken** [comment]
@bpasero Is this already on todays insiders? I don't see a new icon, is there a special trick needed?

**Comment by bpasero** [comment]
@jrieken yes all in, but I see that each OS has its own issues with caching the icon somewhere. On what OS are you checking?

**Comment by jrieken** [comment]
mac

**Comment by bpasero** [comment]
@jrieken yeah good catch, I have [code](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L398) that refreshes the icon cache on macOS but this code will only run once when we updated to our orange icon a while ago. I pushed a change so that we update the icon cache once again, so for tomorrow we should see the new green icon for insider automatically showing up.

Btw, I think we should verify this on stable once we have some stable builds tomorrow.

**Comment by jrieken** [comment]
Unsure why but I do see a mix of icons...

<img width="1014" alt="screen shot 2017-09-29 at 14 34 19" src="https://user-images.githubusercontent.com/1794099/31016028-594f7b20-a523-11e7-953e-f0e8456e02ff.png">

**Comment by bpasero** [comment]
@jrieken weird, maybe my cache invalidation trick does not help for the finder. However seeing the right icon in the dock and about dialog is good.

**Comment by jrieken** [comment]
I see the right icon when downloading the stable candidate

**Comment by bpasero** [comment]
Marking macOS as verified, also for me.

**Comment by bpasero** [comment]
Windows looks OK except for the file associations icon (https://github.com/Microsoft/vscode/issues/35380 @chrisdias)

**Comment by colemickens** [comment]
I'm still very confused about this. Is the icon supposed to have the tilted rectangular background on Linux, or not? The first post in this thread seems to indicate it shouldn't, yet the build I just pulled today still does... This was also the same conclusion I came to after the last thread that was widely publicized that also seemed to indicate the Linux icon shouldn't have the weird rectangle backdrop.

This is from: `code_x64_1.17.0.1505281268.tar.gz`:

```
$ pacman -Ql visual-studio-code-insiders | grep pixmaps

/usr/share/icons/visual-studio-code-insiders.png
```

And this is the icon file itself: 
![visual-studio-code-insiders](https://user-images.githubusercontent.com/327028/31087915-ba32d356-a753-11e7-83eb-18ad1e1d2046.png)

**Comment by colemickens** [comment]
Sorry, this issue looks related to Stable. I can open a new issue in a bit if someone doesn't correct my understanding. Thanks!

**Comment by bpasero** [comment]
Stable: Orange, Insiders: Green. What you see is correct.

**Comment by jrieken** [comment]
fyi - with todays (signed) builds I am back to the old icon...

**Comment by GeorgeSapkin** [comment]
Why did you switch the previous icon to _this_? What does it solve? It seems like a massive step backwards and reminds me of something from the Office Clip-art era.

**Comment by TankedThomas** [comment]
Can the icons at least be uniform across operating systems? Not liking the Mac icon. I'd much prefer the transparency of the Windows one.

**Comment by lochstar** [comment]
It looks a little too much like Sublime Text for comfort...

<img width="126" alt="screen shot 2017-10-09 at 08 26 12" src="https://user-images.githubusercontent.com/4231286/31321096-b2242c32-accb-11e7-9944-5766cc480a61.png">

**Comment by areddicks1014** [comment]
The blue with the white border was much more visually distinctive and the new one just looks too busy. I understand the green for insider builds, but why change the color for the stable builds? Not to mention all the merch that has the old icon that's out in the world. This feels like a "change for the sake of change" as opposed to a constructive improvement.

**Comment by VolleMelk** [comment]
Come on! What are we, ST3?!
