### ISSUE TITLE
[handlebars] Bad link ctrl+click underline in handlebars file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3530]
When a link it in `{{}}`, only the underscore is being underlined, nothing is preferable.

![highlight](https://cloud.githubusercontent.com/assets/2193314/13377306/4a8da0f6-dd8a-11e5-9445-19651cac0ce8.png)

**Comment by joaomoreno** [comment]
@bpasero gave it to you for link detection. fwd if wrong

**Comment by alexandrudima** [comment]
handlebars inherits link detection from html and tries to make everything inside href be a link. We might as well remove link detection completely from handlebars

**Comment by Tyriar** [comment]
It's still useful for handlebars as it is just a HTML document with data annotations. It shouldn't ever highlight the opening `"` though, and it should assume it's not a regular URL if it starts with `{` and not highlight.

**Comment by alexandrudima** [comment]
Handlebars is now an extension owned by @aeschli
