### ISSUE TITLE
[less] wrong colorization for some at-rules

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#35300]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:

The grammar wrongly identify some at-rules as variables, causing wrong colorization for them.

![image](https://user-images.githubusercontent.com/1330321/30954232-0002395c-a462-11e7-9e92-85f6ee90f46b.png)

Specifically,  `@charset`, `@keyframes`, `@page` `@namespace` and `@supports` are not supported. (I have checked all at-rules on https://css-tricks.com/the-at-rules-of-css/, `@document` is not supported by the language service at all)

It's worse if I use the Monokai theme, because it doesn't support less variables so they are just white. (for real variables, maybe I need to open another issue)

![image](https://user-images.githubusercontent.com/1330321/30954381-7efa7274-a462-11e7-84b0-84c4939a9714.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
I created https://github.com/atom/language-less/issues/80
