### ISSUE TITLE
Intellisense peek and navigation not working for global variables

### ISSUE THREAD

**Issue by shashi-raja** [Microsoft/vscode#35318]
I am writing api tests using javascript+mocha in visual studio code. I have created a file **testData.js** which contains

` exports.name = 'test';`
Now I have defined a **global variable** in setup.js and required that setup.js in **mocha.opts** file, which basically requires everything in setup.js and you can then access them without directly requiring them in your code.

`global.testData = require(./testData.js);`
Now in my **test.js**  file I am using

`name = testData.name;`
I am not able to traverse/peak to testData.js upon ctrl+click on testData.**name**. I am able to do so in webstorm.
But if I include below code in test.js then intellisense works fine but it defeats my purpose of using global variable-
```
const testData = require(./testData.js);
name = testData.name;
```
 How can I configure visual studio code to give intellisense in this scenario?

- VSCode Version:1.16.1
- OS Version:macOS Sierra version 10.12.6

**Comment by mjbvz** [comment]
Can you please move this question to stackoverflow so that it can help other users as well?

**Comment by shashi-raja** [comment]
I think it is more of an issue than a question. Visual stdio code should detect this global variable relationship like webstorm and should allow to traverse to that particular file.
