### ISSUE TITLE
Untitled file is not part of recent list after saving

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#35316]
- Create a new file
- Add some text
- Close it
- Prompt is shown asking to save
- Save it
- Open Quick pick
Expected to show above save file in the recent list.

**Comment by bpasero** [comment]
@sandy081 technically the file was never opened, you closed it and saved it, so not sure we should have it in the recently opened section.

**Comment by sandy081** [comment]
I understand that, but I saved the file which I just created/edited. It is not aligned with our current behaviour where we show a file in recent list when we open and close it.

**Comment by bpasero** [comment]
@sandy081 ah I see where you are coming from, fair enough.
