### ISSUE TITLE
Debug dotnet core 2.0 app 

### ISSUE THREAD

**Issue by twb0223** [Microsoft/vscode#35313]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
python|don|0.7.0
tslint|eg2|1.0.9
csharp|ms-|1.12.1
vetur|oct|0.9.10
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

���� .NET Core �� Microsoft (R) ��������汾 15.3.409.57025
��Ȩ����(C) Microsoft Corporation����������Ȩ����

  Code -> e:\Code\Myapi\bin\Debug\netcoreapp2.0\Code.dll

�ѳɹ����ɡ�
    0 ������
    0 ������

����ʱ�� 00:00:02.10

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/35235
