### ISSUE TITLE
Touch Not Working on scrollbar

### ISSUE THREAD

**Issue by TheWozMSN** [Microsoft/vscode#35314]
I am not able to use touch to Click the gear or use the scroll bars in both Code and Code - Insiders

- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.16296
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-PSStackoverflow|Dou|0.0.2
json-tools|eri|1.0.2
PowerShell|ms-|1.4.3
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I fixed the gear touch support for 1.17.

**Comment by alexandrudima** [comment]
@TheWozMSN On the editor, it is possible to touch and pan.

Do you mean you would you like to be able to interact with the scrollbar slider ?

**Comment by TheWozMSN** [comment]
Yes! The scroll bar doesn’t respond to touch!  A mouse or touchpad is needed but there are times it would help.  I have a Yoga that lets me work in tablet mode and this would really help me

Doug

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexandrudima** [comment]
There exists a workaround, to simply touch and pan any scrollable area. (i.e. not via touching the scrollbar slider, but via touching the entire scrollable area).

**Comment by TheWozMSN** [comment]
I just tried.  I have the Docker Extension in the view.  I went to the bottom section to look at the command and configuration information.  I can’t use touch.  The trackpad to select the scroller works.  But nothing moves touching.

Doug
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
