### ISSUE TITLE
Break JavaScript syntax color

### ISSUE THREAD

**Issue by Luchanso** [Microsoft/vscode#35310]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Select sytax JS
2. Typewrite correct code:
```js
A.B = async(C, D, {
    E = 'F',
} = {}) => {
    // Comment
    if (!Func.J(C))
        throw new Error('Field C ...');
    if (!D || !OWNERS.includes(D))
        throw new Error('Field D ...');
};
``` 
3. Syntax coloring not work :(
![image](https://user-images.githubusercontent.com/2098777/30962574-07fdb97e-a453-11e7-9ed6-3ac7cdf0d5f5.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. Should already be fixed in insiders builds:

<img width="457" alt="screen shot 2017-09-28 at 10 47 55 am" src="https://user-images.githubusercontent.com/12821956/30981982-e74b5316-a43a-11e7-9e9e-dc7bb247a09b.png">
