### ISSUE TITLE
No funciona path de validacion PHP

### ISSUE THREAD

**Issue by QHADI** [Microsoft/vscode#35315]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
html-class-suggestions|And|1.0.7
ACF-Snippet|ant|1.8.1
git-easy|bib|1.9.1
bower|don|0.0.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.0
auto-rename-tag|for|0.0.14
live-html-previewer|hdg|0.3.0
phpcs|ika|0.7.0
autofilename|Jer|0.1.3
vscode-github|Kni|0.20.2
vs-color-picker|lih|0.7.0
PowerShell|ms-|1.4.3
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1
seti-icons|qin|0.1.3
vscode-icons|rob|7.14.0
wordpress-snippet|tun|1.1.2
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  En preferencias ajustes configuro el path de donde esta PHP
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "files.associations": {},
    "workbench.iconTheme": "vscode-icons",
    "php.validate.executablePath": "D:\\SERVIDOR\\bin\\php\\php7.0.10\\php.exe",
    "team.showWelcomeMessage": false,
![sin titulo-1](https://user-images.githubusercontent.com/31287998/30967608-223465a4-a45d-11e7-8bed-63299aa76236.jpg)
   
}
 
Pero me da error

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
You set `php.validate.executablePath`, but that error message is coming from the PHP Intellisense extension, which uses the `php.executablePath` setting. If you want to use that extension, you need to set that setting (or add PHP to your path).
