### ISSUE TITLE
Hover: links in documentation are not doing anything

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35319]
There can be links from JSDoc in the hover but clicking them does nothing. Should we jump to the documentation maybe and provide a way to go back?

![image](https://user-images.githubusercontent.com/900690/30972271-607febd2-a46a-11e7-9eec-f91a78eb8b01.png)

**Comment by mjbvz** [comment]
The vscode docs uses custom `DocumentLinkProvider` to support those links so we'll have to see if we can do something for those. However also don't support normal url such as `http://example.com`

**Comment by mjbvz** [comment]
Fixed normal urls with  d3bbec5.  Opened #35940 to track relative link support
