### ISSUE TITLE
Modernize Snippets

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35322]
The TypeScript extension ships some old-school snippets, like a for-loop snippet using var and not a for-of-loop snippet. We should revisit those

**Comment by prog-rajkamal** [comment]
@jrieken 

The snippets are defined in javascript.

Now, `let` is compatible with IE11 and all evergreen browsers (http://caniuse.com/#feat=let) 
However, I am sure if var-version be removed from snippets.

@mjbvz would you mind If I tackle this one? FWIW ,this would be my first contribution.

**Comment by prog-rajkamal** [comment]
This was way easier than I had originally expected. So I just made a quick PR. #35444 :)


As they affect extension, you can test them by copy pasting updated files in javascript extension.

At my local machine, I replaced the snippets file present at: 

C:\Program Files\Microsoft VS Code\resources\app\extensions\javascript\snippets

**Comment by jrieken** [comment]
> The TypeScript extension ships some old-school snippets,

Actually, nothing has been done for TypeScript. Also the changes for JavaScript/JavaScriptReact have some questionable names in the for-of-loops, e.g

```ts
for(let iterator of object) {}
```

It's not an iterator, it's an element the iterator returns. It should be `element` and `iterable`. Also it could be `const` instead of `let`

**Comment by prog-rajkamal** [comment]
Okay, this is embarrassing. Well I somehow missed snippets file in typescript directory (no idea how i thappened).

So, I added it in javascript snippets which _did_ work for  typescript.
 
--------------------------

Right now, I am checking in vscode 1.17.2 .

"For of" and "For in" are implemented  with both let and const variants (though they share the same shortcut [`fof` and `fin`])


Typescript `for loop` , however, still uses `var`. 

I suggest I make the change `var` to `let` and you review the PR. 

@jrieken your thoughts?

**Comment by prog-rajkamal** [comment]
@jrieken 

Regarding the PR #35444, I suggest 

  - `For of` snippet: remove it as it is not needed.
  - `For (let)` : change the snippet to `For const`  [for both typescript and javascript snippets]

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.18.0-insider (86e057cd25756811781237b5d84b8228f99e59ab, 2017-11-03T12:04:44.269Z)

TypeScript and TypeScript React are still using `var` in some of the for loops:
```ts
for (var key in object) {
	if (object.hasOwnProperty(key)) {
		var element = object[key];
		
	}
}

for (let index = 0; index < array.length; index++) {
	var element = array[index];
	
}
```

JavaScript and JavaScript React are using `let` in `for in` and `const` in `for of`. I'd use the same in both for consistency (I'm in favor of `const`).

Nit: JavaScript and JavaScript React have parentheses around the `forEach` parameter, others don't. I'd remove them.

**Comment by mjbvz** [comment]
Const makes sense for-in. You need to use `let` in regular for loops though

**Comment by rnyberg** [comment]
@prog-rajkamal Hey, `let` does work in IE11, but some other changes that were made are not compatible, for example ES6 arrow functions (`settimeout` snippet for example) make older browsers throw hissy fits. This is a big regression for many devs that are stuck with older browsers, imho.

At minimum, the old snippets should be available with some setting, or they can be available in the popup alongside the never variants (just lower in priority).
