### ISSUE TITLE
Broken intellisense for C++

### ISSUE THREAD

**Issue by nabeelomer** [Microsoft/vscode#35327]
- VSCode Version: 1.17.0-insider
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open VScode
2. Open a C++ source file
3. Try to get Intellisense suggestions

A prompt says "C++ language server has crashed 5 times won't be restarted" or similar and then no intellisense even after restarting code, only the tag parser results come up.

(Not sure if I should have filed this with https://github.com/Microsoft/vscode-cpptools, but since their last commit was 10 days ago, I think the problem is with VSCode and not the extension)

Reproduces without extensions: Yes

**Comment by adithyasai** [comment]
@nabeelomer I think there is a similar issue.
https://github.com/Microsoft/vscode-cpptools/issues/430

Please check this once

**Comment by nabeelomer** [comment]
@adithyasai I don't think that applies to me, my intellisense was working fine till the last insiders update.

**Comment by jrieken** [comment]
Please file this issue against the extension
