### ISSUE TITLE
There is a way to crypt extension?

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#35326]
Hi all, i wonder if there is a way to build and crypt extension or lock his content from being extracted. I know that renaming a `.vsix` file to `.zip` can be easily extracted.

**Comment by joaomoreno** [comment]
There is no support for this. We need to extract the contents otherwise we can't run the extension.

**Comment by equinusocio** [comment]
And what about crypting extension files? Something like python crypt or git crypt.

**Comment by joaomoreno** [comment]
You can easily do that as a publisher: just encrypt whatever files you want.

**Comment by equinusocio** [comment]
Yes if i encrypt files how vsc can read it?

**Comment by joaomoreno** [comment]
Well how would we be able to read the files?
