### ISSUE TITLE
Playground updates

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35328]
Some things we should factor into the playground...

- Refactoring - extract method
- JavaScript Type Checking //@ts-check
- Color picker mention in the CSS section

Lets use this to tract additional ideas.

cc/ @chrmarti

**Comment by bcgodfrey91** [comment]
It would be my first open source contribution, but do you mind if I pick this up, @seanmcbreen?

**Comment by JacksonKearl** [comment]
This issue should be closed right?

**Comment by chrmarti** [comment]
Indeed, closing.
