### ISSUE TITLE
Typescript colorization issue

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35335]
1.17, not 1.16

Looks fine if I delete the `++`
```ts
if (a++ < b) {
}

export class A extends B {
}
```

![image](https://user-images.githubusercontent.com/323878/30982398-21dbeefe-a43c-11e7-82bf-2e831520a808.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#526
