### ISSUE TITLE
Warning: C:\Documents and Settings is a symlink, which is not allowed.

### ISSUE THREAD

**Issue by reklawevarg** [Microsoft/vscode#35330]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.7.0
ruby-rubocop|mis|0.4.0
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
Ruby|reb|0.15.0

(7 theme extensions excluded)

---

Steps to Reproduce:

1.  Open any document, make a small change, and save
2.  Code complains that "Warning: C:\Documents and Settings is a symlink, which is not allowed."

This has only occurred on VSC 1.16.1, not in prior versions.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by reklawevarg** [comment]
mime.ts:59 Overwriting extension <<.rhtml>> to now point to mime
<<text/x-erb>>
(anonymous) @ mime.ts:59
extensionService.ts:407
[C:\Users\WINDOWSUSERNAMEGOESHERE\.vscode\extensions\rebornix.ruby-0.15.0]:
The "if else"-snippet very likely confuses snippet-variables and
snippet-placeholders. See
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax
for more details.
e._logMessageInConsole @ extensionService.ts:407
extensionHost.ts:384 [Extension Host] rejected promise not handled within 1
second
t._logExtensionHostMessage @ extensionHost.ts:384
shell.ts:419 An unknown error occurred. Please consult the log for more
details.
e.onUnexpectedError @ shell.ts:419
extensionHost.ts:384 [Extension Host] C:\Ruby23-x64\bin\rubocop.bat
messageService.ts:125 Warning: C:\Documents and Settings is a symlink,
which is not allowed.

e.doShow @ messageService.ts:125
extensionHost.ts:384 [Extension Host] Warning: C:\Documents and Settings is
a symlink, which is not allowed.

2fileService.ts:783 [node.js Watcher] [CHANGED]
c:\Users\WINDOWSUSERNAMEGOESHERE\src\ruby\report\term_search.rb
fileService.ts:797 [node.js Watcher] >> normalized [CHANGED]
c:\Users\WINDOWSUSERNAMEGOESHERE\src\ruby\report\term_search.rb
extensionHost.ts:384 [Extension Host] C:\Ruby23-x64\bin\rubocop.bat
messageService.ts:125 Warning: C:\Documents and Settings is a symlink,
which is not allowed.

e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e._showMessage @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] Warning: C:\Documents and Settings is
a symlink, which is not allowed.

**Comment by bpasero** [comment]
@reklawevarg still happening?

**Comment by reklawevarg** [comment]
No, thankfully --- traced it back to a fresh install of Rubocop (and still
happens every time I update it).  Am able to disable that cop from the
config files.
