### ISSUE TITLE
Could not find the preLaunchTask 'npm'

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35333]
- VSCode Version: Code - Insiders 1.17.0-insider (3831ef5e2ca82e7040cca4af44d76d064f9430a5, 2017-09-28T08:38:19.665Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
autofilename|Jer|0.1.3
vscode-simple-icons|Lau|1.6.1
vscode-docker|Pet|0.0.18
vscode-caniuse|aka|0.5.3
duplicate|alq|0.0.2
regex|chr|0.1.0
ssh|chr|0.0.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
ghlink|dt|0.0.6
gitlens|eam|5.3.0
tslint|eg2|1.0.9
vscode-scss|mrm|0.6.2
azure-account|ms-|0.1.3
azurecli|ms-|0.2.0
csharp|ms-|1.12.1
github-issues-prs|ms-|0.5.0
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
vetur|oct|0.9.10
vscode-versionlens|pfl|0.19.1
diff|raf|0.0.1
vscode-open-in-github|sys|1.6.0
vim|vsc|0.10.1
vscode-import-cost|wix|2.5.0

---

This is with a workspace with 4 root folders, it still works when opening a single folder. The launch switcher has the Launch Extension config of the first root folder selected.

![image](https://user-images.githubusercontent.com/9205389/30981187-65e0e6f8-a438-11e7-90de-f01640b5fd87.png)

**Comment by weinand** [comment]
@chrmarti and the "npm" task is defined in the "task.json" of the same root folder as the underlying launch.json?

**Comment by chrmarti** [comment]
Yes. It works when I open a single folder instead of a multi-folder workspace.

**Comment by isidorn** [comment]
@chrmarti please put your repository on github so I can simply clone it and try it out. Thanks
Also to repeat @weinand question, are you in your scenario referencing the task which lives in the same folder as your launch.json?

**Comment by dbaeumer** [comment]
The reason for this is as follows: the npm task is version 0.1.0 which is not supported in a multi folder setup. When you try to run a task from Task > Run Task you should get a message for this. In addition there is a message in the output window (@isidorn which I didn't bring to front anymore since you complained about it :-)).

So what we need to do is that the debugger shows a message and I let you know that the task can't be run since it is in a tasks.json version 0.1.0.

Opt to not do this for September.

**Comment by isidorn** [comment]
Agree, assigning to October

**Comment by isidorn** [comment]
Unassigning myself until @dbaeumer produces an appropraite message in the task land. Once that is done if the message is not showing to the user assign this back to me to make sure debug is propagating the error nicely

**Comment by dbaeumer** [comment]
Done. The promise will resolve to an error if the folder is ignored

**Comment by isidorn** [comment]
The meesage should nicely pop up [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L768)
Closing.

@chrmarti please reopen if you do not see a nice error message.

**Comment by shouze** [comment]
@dbaeumer ok having this issue https://github.com/Microsoft/vscode/issues/27737#issuecomment-339361651 with a freshly generated typescript extension from yeoman. tasks.json version is `2.0.0`.

**Comment by shouze** [comment]
Ha... and if I try to run the task with `Task > Run Task` its works... this issue occurs only when I click to the start icon in the debugger panel in fact 🙀

**Comment by weinand** [comment]
This error shows up when using a 0.1.0 task in a multi root setup:

![2017-11-03_17-00-53](https://user-images.githubusercontent.com/1898161/32383572-a4d70ada-c0b8-11e7-9ff7-97c3a8f79a77.png)
