### ISSUE TITLE
Support lookaround for find/replace even if slow

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode#35336]
One of the most common use cases I have for using regex when performing a find/replace is to be able to search for words that are not preceded or followed by another word. For example, I'd like to find any word that ends with "Model" unless it ends with "ViewModel".

If I'm understanding the documentation correctly, this is currently not possible.

What would it take to support this? I could really use this even if searches of this type were slower.

**Comment by rebornix** [comment]
sorry we don't support that as described in https://github.com/Microsoft/vscode/issues/36687#issuecomment-338442577

**Comment by devuxer** [comment]
You seem to have interpreted my issue as a bug report. **This is not a bug report--it's a feature request.**

I get that you are using ripgrep, which doesn't support lookaround. What I'm asking you to consider is adding logic that bypasses ripgrep when the regex expression requires lookaround.

I would be willing to sacrifice search speed when performing lookaround searches.
