### ISSUE TITLE
Visual Studio Code NSTouchBar crash on start

### ISSUE THREAD

**Issue by MattLuker** [Microsoft/vscode#35334]
After upgrading My Macbook Pro to Sierra I can no longer run visual studio code. I've reinstalled Insider 1.17 and seeing same problem. It seems to point to the version of Electron being used? 
My Mac does NOT have the touchbar. 

- VSCode Version: 1.17.0-insider
- OS Version: Sierra 10.12.1

Steps to Reproduce:

1. Open Visual Studio Code Insiders after updating mac to Sierra 10.12

Reproduces without extensions: Yes

------------- Send to Apple Problem Details Snippet -------------------

Process:               Electron [8368]
Path:                  /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCodeInsiders
Version:               1.17.0-insider (1.17.0-insider)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [8368]
User ID:               501

Date/Time:             2017-09-28 12:41:20.835 -0500
OS Version:            Mac OS X 10.12.1 (16B2657)
...

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Application Specific Information:
Crashing on exception: -[NSTouchBar setEscapeKeyReplacementItemIdentifier:]: unrecognized selector sent to instance 
...

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fffbbac648b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffd03c5cad objc_exception_throw + 48
2   CoreFoundation                      0x00007fffbbb47c94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x00007fffbba38b55 ___forwarding___ + 1061
4   CoreFoundation                      0x00007fffbba386a8 _CF_forwarding_prep_0 + 120
5   Electron Framework                  0x0000000112f608cc 
...

**Comment by bpasero** [comment]
@MattLuker I am happy you found this, it only seems to happen on macOS 10.12.1. Would you be available for a little test on a new build I am running just now?

**Comment by bpasero** [comment]
@MattLuker if you could verify with the following build: https://az764295.vo.msecnd.net/insider/5d79ec8e56843b6b540a997fd1263a2ceb13d0d2/VSCode-darwin-insider-unsigned.zip

**Comment by MattLuker** [comment]
@bpasero Hey Benjamin, that build is working great for me.
