### ISSUE TITLE
vscode comes with the code to fold / shrink line / change the corresponding label, do not know how to disappear, how can I call out?

### ISSUE THREAD

**Issue by ziyuanzhang** [Microsoft/vscode#35348]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: none
---

Steps to Reproduce:
2.vscode comes with the code to fold / shrink line / change the corresponding label, do not know how to disappear, how can I call out?

**Comment by aeschli** [comment]
Sorry, I don't understand what you mean. Please add a screenshot.

**Comment by aeschli** [comment]
So you are saying the default installation works?

**Comment by aeschli** [comment]
Closing the issue, clarifications are needed.

**Comment by ziyuanzhang** [comment]
thanks, The problem is solved, it is caused by the screen reader optimization. The The Disable screen reader optimization just fine，
