### ISSUE TITLE
Inverted text not readable

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35344]
- VSCode Version: Code - Insiders 1.17.0-insider (3831ef5e2ca82e7040cca4af44d76d064f9430a5, 2017-09-28T08:38:19.665Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

---

Steps to Reproduce:

1. `less somefile.txt`
2. The last line should show color-inverted text:
![image](https://user-images.githubusercontent.com/9205389/30994518-3b3a2e9c-a469-11e7-9936-50a762113d38.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35151
