### ISSUE TITLE
"Loaded Scripts" sections remain during next debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#35345]
Start and stop debugging a few times. The old scripts remain in the Loaded Scripts tree.

![image](https://user-images.githubusercontent.com/323878/30994592-9d5fa818-a469-11e7-9f26-be7f8a74fb02.png)

**Comment by weinand** [comment]
In the LoadedScriptsExplorer I no longer receive the `onDidTerminateDebugSession` event which I use to remove the session data from the tree. See here:
https://github.com/Microsoft/vscode-node-debug/blob/13f65864fdee46a9ed7d3bf2a21320e79b3f6c3a/src/node/extension/loadedScripts.ts#L78

This seems to be a recent regression. Insiders build e059563fb6b8905de79ac4c75be537bb6dc74f5f it is still working fine,
but it is broken in build 3831ef5e2ca82e7040cca4af44d76d064f9430a5.

**Comment by isidorn** [comment]
Nice catch and thanks for the analysis @weinand 
This got introduced by me refectoring process state in https://github.com/Microsoft/vscode/commit/4ebe4343a164f0a1973cddaa844c145699d80c92

**Comment by weinand** [comment]
@isidorn please make sure that this gets cherry picked into the 1.17 branch!

**Comment by isidorn** [comment]
@weinand thanks! I have pushed this to the release branch as well (somehow I though I pushed this to master before it was open but I was wrong)
