### ISSUE TITLE
Editor have a small "jump" after creating new terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#35341]
- VSCode Version: Code - Insiders 1.17.0-insider (f7dc950831c601a247e08f374df8d018fbb97b5a, 2017-09-28T17:52:44.396Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.1
vscode-eslint|dba|1.3.2
gitlens|eam|5.3.0
tslint|eg2|1.0.9
prettier-vscode|esb|0.23.1
csharp|ms-|1.12.1
vetur|oct|0.9.10
vim|vsc|0.10.1

(1 theme extensions excluded)

![term](https://user-images.githubusercontent.com/4033249/30992643-b38ad77a-a45f-11e7-99e3-030d6e7cc732.gif)

**Comment by Tyriar** [comment]
Hmm, I can't repro. I even installed nord just in case that had something to do with it. Any settings that could have impacted this?

**Comment by octref** [comment]
Pinned that down to `"workbench.statusBar.visible": false`

**Comment by octref** [comment]
This has been fixed in latest.
