### ISSUE TITLE
diff view tab: cursor always resets to top of file

### ISSUE THREAD

**Issue by iestynb** [Microsoft/vscode#35342]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.0
team|ms-|1.122.0

---

Steps to Reproduce:

1. create a diff-view tab (e.g by double-clicking on a file in the SCM sidebar)
2. scroll down in the diff-view, place the cursor somewhere in the middle of the file
3. switch to another tab and then back again
4. notice that the diff-view has scrolled back to the top of the file...

Diff-view editing is my primary workflow, so this bug makes VS code almost unusable for me :o(

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
On tab switching, the cursor jumps to the first diff result.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
