### ISSUE TITLE
Improving sample build task template to "solve" the "No build tasks found" message

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/vscode#35352]
- VSCode Version: 1.6.1
- OS Version: Win10 170927

## Issue:

VSCode doesn't recognize build tasks created from VSCode's built-in templates, displaying the "No build task found" toast. This can be quickly remedied by improving the task templates. See below.

This is a continuation of #7877.

## Steps to Reproduce:

1. Working on Jekyll website project with no built-in VSCode build support
1. Hit CTRL + SHIFT + B to start build
1. See "No Build Task Found" info toast
1. Hit "Configure Build Task" button on toast bar
1. Offered 4 task runner options, choose "Others" to run external build command
1. HIt CTRL + SHIFT + B to test newly generated build task

Expected: Newly generated build task should run
Actual: "No build task found" toast is displayed again

Reproduces without extensions: Yes

## Proposed Fix: 
Update task templates to include group options that indicate the task is the default build task

```javascript
            "group": {
                "kind": "build",
                "isDefault": true
            }
```

Fix PR incoming.

**Comment by dbaeumer** [comment]
We should not mark the echo task as the build task. We should rather list all tasks if no build task is found and inform the user about this.

**Comment by dbaeumer** [comment]
I fixed it by introducing a flow that allows to configure the default build task in this scenario. To verify start with

tasks.json
```ts
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo Hello"
		}
	]
}
```
- Task > Run Build Task
- Select ... Configure Default Build Task
- select echo

Ensure that the echo task is marked as the default build task.
