### ISSUE TITLE
Tasks in my workspace file show up as error

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35357]
I am not sure how I got into this state, but my workspace file contains a task entry which now shows up as warning:

![image](https://user-images.githubusercontent.com/900690/31002746-b53079c6-a4ec-11e7-8774-c4f72fdb22e8.png)

Either we should not show a warning or we should have no way of adding task config to workspace file.

**Comment by dbaeumer** [comment]
This very likely happened when I was using @sandy081 API incorrectly. I now do:

```ts
	private writeConfiguration(workspaceFolder: IWorkspaceFolder, value: IConfigurationValue): TPromise<void, any> {
		if (this.contextService.getWorkbenchState() === WorkbenchState.FOLDER) {
			return this.configurationEditingService.writeConfiguration(ConfigurationTarget.WORKSPACE, value);
		} else if (this.contextService.getWorkbenchState() === WorkbenchState.WORKSPACE) {
			return this.configurationEditingService.writeConfiguration(ConfigurationTarget.FOLDER, value, { scopes: { resource: workspaceFolder.uri } });
		} else {
			return undefined;
		}
	}
```

@sandy081 if you think that this is correct and shouldn't write into the workspace settings anymore then please clone. Otherwise please advice what the correct code would be.

**Comment by sandy081** [comment]
@dbaeumer Yes above usage is correct. You can also simplify it with single call

```typescript
this.configurationEditingService.writeConfiguration(ConfigurationTarget.FOLDER, value, { scopes: { resource: workspaceFolder.uri } })
```
 This will write configuration in to given workspace folder in both Single folder and MR workspace.

I would also like to know if we support tasks at a workspace level in a MR workspace? I keep this open for me to do following
- Update the schema to have tasks entry
- If somebody writes tasks into this file, I have to write it correctly.

**Comment by dbaeumer** [comment]
@sandy081 currently there are not plans to support tasks at the workspace level (e.g. having them in a settings file).

**Comment by sandy081** [comment]
@dbaeumer @weinand Currently, Configuration API supports reading and writing workspace `tasks` and `launch` configurations in a Multi-root workspace. Not sure, if you support them. If not, let me know I will also do the same.

But, I think we would need support for that in general.

**Comment by dbaeumer** [comment]
@sandy081 still no plans to support task configuration in a workspace file.

**Comment by sandy081** [comment]
Ok, I will take back their support in configuration  land
