### ISSUE TITLE
VS_CODE environment variable disappered.

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#35354]
- VSCode Version: 1.16.1-main
- OS Version: Ubuntu 17.04, Linux 4.10.0-35-generic

Steps to Reproduce:

1. run `env` or try to use variable `$VS_CODE` in the VS Code terminal.
2. You will notice `VS_CODE` env variable no longer exists (it used to be `VS_CODE=1` in the previous versions.)

I used to use this environment variable to detect if the VS Code built-in terminal is running because of some compatibility issues between different terminal programs. After I updated to 1.16, I noticed there is no VS_CODE anymore.

It that intentionally removed? If then, what environment variable is 'guaranteed' to be set in the built-in terminal?

**Comment by Tyriar** [comment]
Not sure what VS_CODE was used for but there is $TERM_PROGRAM which is available just for this use case. It's also set in many other terminals as well:

<img width="278" alt="screen shot 2017-09-29 at 5 26 44 am" src="https://user-images.githubusercontent.com/2193314/31009863-dcd485b4-a4d6-11e7-8d37-2ddf32c0d3e8.png">

<img width="207" alt="screen shot 2017-09-29 at 5 27 30 am" src="https://user-images.githubusercontent.com/2193314/31009873-e931b188-a4d6-11e7-98d5-69b95faab6aa.png">
