### ISSUE TITLE
Not all symbols in commets are detected correctly.

### ISSUE THREAD

**Issue by lijyigithub** [Microsoft/vscode#35351]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
python|don|0.7.0
Go|luk|0.6.65
cpptools|ms-|0.13.0
vim|vsc|0.10.1
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. I installed C/C++ plugin by Microsoft.Then I edit semphr.h for FreeRTOS
2.If the line number is large enough, eg 1061, symbols in commet may not be detected correctly.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
Please file issue against cpptools extension
