### ISSUE TITLE
Java extension recommendation, but I have all installed

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35364]
I'm getting the following recommendation, but I already have both
- Language Support for Java(TM) by Red Hat
- Java Debug Extension for Visual Studio Code
installed.

I think what it means is the 'Java Extension Pack'.
-> Change the dialog to `The 'Java Extension Pack' is recommended for this file type`

![image](https://user-images.githubusercontent.com/6461412/31009884-3d4e7a12-a509-11e7-872d-1b32de14f4d3.png)

**Comment by ramya-rao-a** [comment]
@seanmcbreen Can you update the name for the recommendation you added recently?

**Comment by ramya-rao-a** [comment]
For 1.17, we will show

![image](https://user-images.githubusercontent.com/16890566/31035176-e59d68ce-a51b-11e7-82b0-c3b76dd2ecad.png)

For 1.18, we will add some smarts to the distro to differentiate between extensions and extension packs

**Comment by fbricon** [comment]
I find it pretty annoying that it recommends the Java extension pack when the minimum required (and already installed in my case) is the redhat.java one

**Comment by seanmcbreen** [comment]
Hi @fbricon 

A little context - and a more generic point first - we are increasingly moving to packs for recommendation to offer a solid E2E experience for VS Code users.  Of course individuals can still elect to have partial adoptions e.g. language, analyse, utility tool or debugger.  But landing with a solid pack is something we aspire to.  We are also revising how we handle recommendations to make them more impact-full across the board - balancing being intrusive/getting in the way with helping a new user.

That said I think in this specific case the pack authors need to do a better job explaining why this makes sense and I’ll reach out and get that improved.  I'm sure there are also other things we should include as well.

Hopefully that clarifies, LMK if you have additional input.

Sean
VS Code Team Member
