### ISSUE TITLE
Empty Explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35360]
I don't have repro steps but since a few days I sometimes see the explorer bucket staying empty. I have the feeling that this happens with workspaces I haven't opened since while and I also believe this is related to the fact that there the git-bucket (which is populated with a delay). This might be from the remote-changes we did?

<img width="876" alt="screen shot 2017-09-29 at 09 50 01" src="https://user-images.githubusercontent.com/1794099/31006254-42718dac-a4fc-11e7-9a6f-6641f9a00d0a.png">

**Comment by jrieken** [comment]
Hm, also the 'open editors' bucket is empty which it shouldn't...

**Comment by jrieken** [comment]
```
{"workbench.explorer.openEditorsView":{"collapsed":true,"isHidden":false,"order":0},"workbench.explorer.fileView":{"size":754,"collapsed":false,"isHidden":false,"order":1},"gitlens.stashExplorer":{"size":110,"collapsed":true,"isHidden":true,"order":2}}
```

![screen shot 2017-09-29 at 10 19 00](https://user-images.githubusercontent.com/1794099/31007110-a36e2040-a4ff-11e7-8459-b3d5d014c378.png)

**Comment by joaomoreno** [comment]
Great catch!

**Comment by jrieken** [comment]
I have tried all my other old and not so old project and didn't see this anymore. Marking as verified
