### ISSUE TITLE
Control + left/right arrow doesn't stop at every word boundary

### ISSUE THREAD

**Issue by thomaslevesque** [Microsoft/vscode#35366]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
auto-close-tag|for|0.4.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. Type a sentence, e.g. "the quick brown fox jumped over the lazy dog"
2. Place the cursor at the end of "quick"
3. Hit <kbd>Ctrl</kbd>+<kbd>&rarr;</kbd>

Expected behavior: should move the cursor at the beginning of "brown"
Actual behavior: moves the cursor to the end of "brown"

This is inconsistent with the behavior of the vast majority of text editors.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
To control this behaviour and get VS-style Ctrl+Right, please edit your `keybindings.json` and add:

```
{ "key":"ctrl+right",       "command":"cursorWordStartRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordStartRightSelect", "when":"editorTextFocus" }
```

This will overwrite the defaults:

```
{ "key":"ctrl+right",       "command":"cursorWordEndRight",       "when":"editorTextFocus" }
{ "key":"ctrl+shift+right", "command":"cursorWordEndRightSelect", "when":"editorTextFocus" }
```

You can also use a keymap extension like the Visual Studio keymap extension.

**Comment by thomaslevesque** [comment]
Thanks @alexandrudima!
