### ISSUE TITLE
Improve the drag and drop feedback in split views

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35368]
1.17-insiders
- open the marketplace view
- drag the header of the 'Installed' section, and try to make the section smaller
-> a very long bar shows up
-> moving it down doesn't see to work at all
-> moving it up gives a strange drop indication like when moving a file inside a folder
-> moving up swaps the two sections. I didn't expect that from the visual indication.

![drag-header](https://user-images.githubusercontent.com/6461412/31012572-90929128-a512-11e7-835e-0b06e8b588dd.gif)

**Comment by joaomoreno** [comment]
The long hover seems like a Linux bug.

All the other details are applied to pretty much all our drag and drop interactions (activity bar, open editors, tabs), so we're not really gonna touch that any time soon.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
