### ISSUE TITLE
[handlebars] Inconsistent Handlebars highlighting within HTML comments

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3536]
Handlebars expressions are only not being highlighted as comments when they do not have an indent or immediately follow the opening `<!--`.

``` hbs
<!--{{a}}
 {{a}}
{{a}}
 {{a}}
-->
```

![image](https://cloud.githubusercontent.com/assets/2193314/13378099/3394fde0-ddad-11e5-9535-c5237ba54d19.png)

The comment scope is not present on them: `class="token punctuation expression unescaped handlebars"`

**Comment by mjbvz** [comment]
I believe this was fixed at some point: 

<img width="129" alt="screen shot 2017-02-15 at 4 25 11 pm" src="https://cloud.githubusercontent.com/assets/12821956/23001733/59aa95a8-f39b-11e6-9e41-25c0a9ecb928.png">
