### ISSUE TITLE
Replace ${workspaceRootFolderName} with ${workspaceFolderBasename}

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35369]
Now that we have workspaceFolder we should replace ${workspaceRootFolderName} with ${workspaceFolderBasename}

@isidorn objections.

**Comment by isidorn** [comment]
No objections. I think it makes sense and aligns well with what we already did for ${workspaceFolder}

**Comment by ghiscoding** [comment]
@dbaeumer Not really a big deal but I noticed that there's a typo in your camelCase in both the title and the comment, `...Basename` should be `....BaseName`

**Comment by dbaeumer** [comment]
in bash and node it is called basename. This is why I decided to name it the same. Will look if we have variables using basename as well and which style they use

**Comment by dbaeumer** [comment]
We do have fileBasename. So I will call it workspaceFolderBasename
