### ISSUE TITLE
If I try to move VScode into one monitor to the other monitor it crashed.

### ISSUE THREAD

**Issue by Kavinda8535** [Microsoft/vscode#35362]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 
Server.js
![screenshot_1](https://user-images.githubusercontent.com/22386540/31006338-f2538212-a519-11e7-838a-89e2d79a21d4.jpg)

Package.json
![screenshot_2](https://user-images.githubusercontent.com/22386540/31006339-f253aa94-a519-11e7-95ce-66633f77eac4.jpg)

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
debugger-for-chrome|msj|3.3.1
react-beautify|tai|0.3.0
ReactSnippetsStandard|Tim|1.1.0
jsx|Twe|0.0.1
vscode-react-native|vsm|0.4.2
ReactSnippets|xab|1.4.0

I am currently working on a react and redux project.
While I run the node server.js in a one terminal and webpack in a another terminal.my localhost was running. I try to move the VScode window to one monitor to the other monitor. Every time Vscode window crashed. Had to reopen windows again. Why ?
I will attached my server.js and package.json file to identify my installed packages and my server also.
Localhost port 3000 its ran.
---

Steps to Reproduce:

1.while running the VSCode try to see some console logs in Firefox browser / chrome browser.
2.Move VScode window to one monitor to the other monitor. Suddenly it will get crash.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
