### ISSUE TITLE
Per-editor/tab background color

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#35379]
It would be awesome to have the ability to change the background color of an editor/tab on a per-editor/tab basis, programmatically. The use case I'm thinking about is ToDo files, but there might be others. 

For instance this is what a todo file might look like in VSC:

<img width="726" alt="screen shot 2017-09-29 at 15 35 41" src="https://user-images.githubusercontent.com/1812093/31018423-55ed50ca-a52c-11e7-9df3-d199e016c6c2.png">

<img width="726" alt="code-tabs" src="https://user-images.githubusercontent.com/1812093/31019036-a8b8ab72-a52e-11e7-90de-65f3bdd2ffaa.png">

This is what it looks like in Sublime:

<img width="726" alt="screen shot 2017-09-29 at 15 35 51 1" src="https://user-images.githubusercontent.com/1812093/31018432-5e2291a6-a52c-11e7-92ff-b56c62cc6a22.png">

<img width="726" alt="sublime-tabs" src="https://user-images.githubusercontent.com/1812093/31019041-ac6fc57a-a52e-11e7-933e-c4927efe23fe.png">

Having those editors/tabs in a different color makes them stand out. 

Also, some decorators used by the VSC [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) in the screenshot are necessarily dynamic, and because of #32813 the colors used in them are provided via the settings. This means that if a user changes its theme he/she will also need to change those settings for those decorators to not look out of place. With the ability to set a custom background colors those decorators will look right no matter the theme.

**Comment by hujianxin** [comment]
I really really need this feature.

Like this pic: ![](https://camo.githubusercontent.com/8ee527438f591aa56ab1f75c104b0a94d43e99dc/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f303036744b6654636c7931666b71643071657365396a33316b7730796b6166342e6a7067)

**Comment by michael-38** [comment]
I agree. The current UI looks like the tab that I'm on is not selected (and vice versa). The selected tab colour should be lighter (grey) and other tabs should be darker (black).

**Comment by jpike88** [comment]
I think it would be useful in a multi-root environment, for tabs to inherit the colours of their relevant project settings. It gets confusing juggling grey tabs in a client/server environment.

**Comment by deadcoder0904** [comment]
Would definitely love colored tabs

**Comment by oreporan** [comment]
There is an extension that does exactly this - 
[ColorTabs](https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext)
You can choose what you want to color, the tab, the title bar etc. based on a regex

**Comment by fabiospampinato** [comment]
@oreporan I don't think that extension can achieve something similar to what VSCode provides. Besides I'm asking for an API for this, which I would in turn use in my extensions.

**Comment by oreporan** [comment]
Oh my bad - overlooked the "programatically" part in your original post

**Comment by hediet** [comment]
I would love to have this feature too!
Currently I have a medium sized backend and many frontend applications within the same workspace (repository).
It starts to get confusing whenever I touch files across all sub-projects. Colored tabs would greatly help here - they build up a mental model and help to orientate a lot.

**Comment by Jared-Dev** [comment]
> I think it would be useful in a multi-root environment, for tabs to inherit the colours of their relevant project settings. It gets confusing juggling grey tabs in a client/server environment.

It would be incredible if when working in a multi-root project you could define custom themes for each root folder. Ideally, these settings could live within a `.vscode` folder of each root folder as well as within the `*.code-workspace` file!
