### ISSUE TITLE
new Map/Set suggests not show

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#35372]
- VSCode Version: 1.16.1
- OS Version: Arch linux

Steps to Reproduce:

1. write new Map() or new Set()
2. ctrl + space

Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/11390039/31015831-b5651cce-a52a-11e7-9611-355960894750.png)
![image](https://user-images.githubusercontent.com/11390039/31015838-ba9e6ee8-a52a-11e7-9ae3-336d8d725018.png)

**Comment by mjbvz** [comment]
1. What language? JavaScript or TypeScript?
2. Do you have a `tsconfig` or `jsconfig` file in your workspace?
3. If you hover over `Map` or `Set`, what does it show?

**Comment by edDimensi** [comment]
1. js
2. nope
3. nothing

**Comment by mjbvz** [comment]
And you have disable all extensions?

Can you please: 

1. Set  "typescript.tsserver.trace": "verbose",
2. Run `go to definition on `Map`
3. Open the output panel and share the TypeScript section's output

**Comment by edDimensi** [comment]
@mjbvz i do this. Nothing happing.

**Comment by edDimensi** [comment]
On my home pc, i not have that problem.

**Comment by mjbvz** [comment]
What does your `jsconfig.json` contain?
