### ISSUE TITLE
Terminal content expanding when resizing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35376]
Version 1.17.0-insider
Commit caa5656df9e8fa9c556c7eddeb6b4d532814054b
Date 2017-09-29T05:16:09.696Z

- give the editor section a small with, and close the window
- start with a empty window
- add an empty folder with 'Add workspace folder'
- open the terminal. It will open with small width, don't resize yet, but type `ls`
- resize the terminal to get more width
- context stays small

![image](https://user-images.githubusercontent.com/6461412/31018372-2228f0c8-a52c-11e7-9315-e191611ae54c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
