### ISSUE TITLE
Workspace with special name cannot be modified

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35370]
* open a single folder
* 'F1 > Save As Workspace' use the `Üntïtlęd.code-workspace` as name
* open the workspace configuration file
* 'F1 > Add Folder to Workspace' and pick something
* the file updates
* 🐛 the explorer doesn't because no change event is send (the api also doesn't receive a file)

**Comment by bpasero** [comment]
+ @isidorn for explorer and @sandy081 for events

**Comment by isidorn** [comment]
The events are missing, that's the issue here.

**Comment by bpasero** [comment]
Another case of where the decomposed form on macOS file systems was tricking us. We need to normalise also in cases of `fs.watch` and `chokidar.watch`.
