### ISSUE TITLE
Allow multiple patterns in exclude "when" clauses

### ISSUE THREAD

**Issue by dmitrykurmanov** [Microsoft/vscode#35375]
Hello, team! Thanks for the greatest editor I've ever used!

- VSCode Version: 1.16.1
- OS Version: windows 10, x64

Steps to Reproduce:

1. setup files.exclude setting: 
```
     "files.exclude": {
         "**/*.js": { "when": "$(basename).ts" },
         "**/**.js": { "when": "$(basename).tsx" }
     }
```
this is hack from the doc: https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files

2. try to find something in folder and see the error:  `error parsing glob path/**/**.js: invalid use of **; must be one path component`

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is a typo in the docs, you need to use `"**/*.js"` in both cases. I'll fix the docs.

**Comment by dmitrykurmanov** [comment]
@roblourens, but now we have `duplicate object key ` and  the text below : 

> ... The search glob pattern is used as a key. The settings above use **two different glob patterns** to provide **two unique keys** but ...

**Comment by roblourens** [comment]
I did not read that closely enough. That's an ... interesting workaround.

**Comment by roblourens** [comment]
Need to either handle this case (`**.js`) for ripgrep or change the syntax to support multiple patterns with a 'when' clause, e.g.

```
"**/*.js": { "when": ["$(basename).ts", "$(basename).tsx"] }
```

or allow a pattern on the right side, like `"$(basename).ts*"`

but we can't just keep adding *s. If I want 3 patterns, am I supposed to use `**/***.js`?

**Comment by roblourens** [comment]
Actually a dupe of https://github.com/Microsoft/vscode/issues/1214
