### ISSUE TITLE
git.publish ask for remote if only one is setup

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#35373]
- VSCode Version: 1.16.1
- OS Version: Linux

Steps to Reproduce:

1. Create project with git setup and just one remote.
2. Execute `git.publish`
3. QuickPick is shown with the one configured remote

I would suggest to skip the quickpick if there is just one remote. It would simplify the UX of `git.pubish`.

**Comment by joaomoreno** [comment]
Would you like to [attempt a PR](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L1232)?

**Comment by KnisterPeter** [comment]
Sure :relaxed:
