### ISSUE TITLE
Spanish translation gives different meaning to some options.

### ISSUE THREAD

**Issue by F1r3f0x** [Microsoft/vscode#35378]
- VSCode Version: 1.16.1
- OS Version: Windows 10 x64 1703

 vscode/i18n/esn/src/vs/code/electron-main/menus.i18n.json 

**"Alternar Bloquear Comentario"** means "Toogle lock comment". It should be "Alternar Bloque de comentario."

**"Alternar comentario de Linea"** means "Toggle comment off the Line". A better translation would be "Alternar comentario en linea". ("Toggle comment in Line")

**"Alternar Fragmento de codigo del usuario"**.  Has Snippets in singular, should be plural.

They look like little errors, but they really confuse users about those functions.

Reproduces without extensions: Yes

**Comment by danyeh** [comment]
@F1r3f0x , it will be great if you can help to correct directly in [Transifex](https://www.transifex.com/microsoft-oss). See https://aka.ms/vscodeloc on the how to access Transifex. Thank you!

**Comment by danyeh** [comment]
We will follow up in community localization process in Transifex. Close here.
Thank you for the feedback! Feedback is captured and will be fixed in January update release.
