### ISSUE TITLE
Order of "Cut, Copy, Paste" in editor context menu is wrong

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#3538]
![copycutpaste](https://cloud.githubusercontent.com/assets/6125444/13379703/4e9b500a-de2d-11e5-8365-87f86fe41145.png)

On Windows 8.1, v 0.10.8

Is there a reason for this order? I've only ever seen it ordered as Cut, Copy, Paste, at least on Windows. The main Edit menu, on the other hand, does have them in the right order.

**Comment by alexandrudima** [comment]
Nice catch!
