### ISSUE TITLE
Not seeing option to extract as a func/method when highlighting variables

### ISSUE THREAD

**Issue by greyepoxy** [Microsoft/vscode#35388]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Typescript: 2.5.2

---

Steps to Reproduce:

1. I have this code
```ts

export function validateJson(jsonToValidatePath: string, jsonSchemaPath: string): void {
  const jsonAbsolutePath = pathResolve(jsonToValidatePath);
  const json = readJson(jsonAbsolutePath);
  const jsonSchemaAbsolutePath = pathResolve(jsonSchemaPath);
  const schema = readJson(jsonSchemaAbsolutePath);

  validate(json, schema);
}

const pathResolve = (path:string): string => {
    return path;
};

const readJson = (path:string): any => {
    return {};
}

const validate = (json: any, schema: any) => {
    return true;
} 
```

2. Highlight 
```ts
  const jsonAbsolutePath = pathResolve(jsonToValidatePath);
  const json = readJson(jsonAbsolutePath);
```

3. Expect to see the lightbulb with an extract func/method option, instead see nothing
I would expect an extract function to produce the following
```ts
function newFunction(jsonToValidatePath: string) {
    const jsonAbsolutePath = pathResolve(jsonToValidatePath);
    return readJson(jsonAbsolutePath);
}
```

I only see extract function as an option when I highlight (which works as I would expect)
```ts
  validate(json, schema);
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks! I've opened https://github.com/Microsoft/TypeScript/issues/18855 to track this against TypeScript
