### ISSUE TITLE
Flash of non-Syntax highlighting the first time I open a file

### ISSUE THREAD

**Issue by codedread** [Microsoft/vscode#35389]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Open a new project / folder
2. Click on a source file

There is an annoying flash of non-syntax highlighted code before syntax highlighting comes up.

**Comment by alexandrudima** [comment]
We currently choose to paint the text as soon as possible and then tokenize the text in chunks. i.e. we do not block the rendering of the file until all the file is tokenized.
