### ISSUE TITLE
VS Code crashing frequently.

### ISSUE THREAD

**Issue by ayush987goyal** [Microsoft/vscode#35386]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
python|don|0.7.0
vscode-generate-getter-setter|DSK|0.4.2
tslint|eg2|1.0.9
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
Angular-BeastCode|Mik|4.4.2
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.3.1
tsimporter|pmn|1.2.14
vscode-icons|rob|7.14.0
sass-indented|rob|1.4.2
code-settings-sync|Sha|2.8.3
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@ayush987goyal Are there any steps to reproduce this crash. Also does it happens when extensions are disabled?
