### ISSUE TITLE
Insiders build not updating on Windows and Mac (works on Linux)

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/vscode#35390]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:10:59.524Z)
- OS Version: Darwin x64 14.5.0

- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce
===

1. Download the Insiders build for Mac and Windows from https://code.visualstudio.com/Insiders/
2. Launch and notice that it's not been updated since September 20.
3. Click the gear on the bottom left of the window (the usual place) and select "Check for updates"

### Actual

There are no updates available for Mac and Windows.

Here are the screenshots for the build information. Both Mac and Windows Insiders seem to have been last built on 2017-09-20

![screen shot 2017-09-29 at 9 56 03 am](https://user-images.githubusercontent.com/54414/31026753-6ee68798-a4fc-11e7-95b2-975df59b26d2.png)

![screen shot 2017-09-29 at 9 55 34 am](https://user-images.githubusercontent.com/54414/31026742-62802a7c-a4fc-11e7-97bd-6ea7f89f2383.png)

### Expected

There should be a new update to match the Linux version (which at this time of filing, is the 2017-09-29 version). **Note that we are using Ubuntu so we have only tested against the .deb file that is generated. The rpm files were not tested**.

- VSCode Version: Code - Insiders 1.17.0-insider (caa5656df9e8fa9c556c7eddeb6b4d532814054b, **2017-09-29T05:16:09.696Z**)
- OS Version: Linux x64 4.4.0-96-generic

![screen shot 2017-09-29 at 9 56 30 am](https://user-images.githubusercontent.com/54414/31026778-819ce012-a4fc-11e7-9b7f-b4fae64e4b54.png)

Reproduces without extensions
===

Yes (even removing the ~/.code-insiders folder didn't solve this)

Deleting and reinstalling Insiders doesn't help either.

----

We could get around by building from source but it's more convenient for us to be able to test our extensions against the latest insider builds.

**Comment by dlong500** [comment]
see #35168 

Not sure when they are going to fix it though.

**Comment by dlong500** [comment]
It just started working again for me on Windows with the 7ac1f1e05baad03d4dd8f8515f1e598180b2c97e build.

**Comment by ddotlic** [comment]
@dlong500 What's perplexing is them closing the issue where you simply asked for information about where to get the info about which version _is_ the latest (without giving us even a hint or at least "no, we won't tell you" 😞), so that we know whether we have latest bits or not.

Not sure what the point of insider build is if we have to wait for the non-insider to test the code.

I'm completely puzzled by the way this has been (not) communicated.

**Comment by vazexqi** [comment]
The issue is fixed for Mac and Windows. I am able to get both to update today to the latest commits. I'm marking this issue as closed.
