### ISSUE TITLE
Feature Request: Zen mode with tabs and auto-hide panel

### ISSUE THREAD

**Issue by markfaine** [Microsoft/vscode#35399]
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.16
Angular2|joh|2.7.0
LiveServer|rit|2.1.1
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Active Zen Mode
2. Tabs for open documents are still available allowing easy file switching for already open files
3. Moving the cursor to the side slides opens the panel while the mouse is in the region allowing for files to be selected.  - No need to ever leave zen mode unless you wish to.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
2. Use `"zenMode.hideTabs": false`
3. This is not aligned with our general design principles. Currently you can open the panel with `cmd + J`. You can search our issues database for other panel discussion we are having
