### ISSUE TITLE
Renaming or copy/paste files can cause save to fail

### ISSUE THREAD

**Issue by varnk** [Microsoft/vscode#35394]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
plantuml|jeb|2.3.0
guid|kos|0.0.1
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
team|ms-|1.122.0
java|red|0.10.0
code-spell-checker|str|1.4.0
python-extended-snippets|tus|0.0.1

---
This is an intermittent problem.  I don't know the exact steps to reproduce, but here is the closest I could figure out.

Steps to Reproduce:

1.  Rename one or more files using Code Explorer
2.  Try to save the file after the rename.  
3.  Save fails in Code Editor.  The system asks to Cancel, Retry, Discard, Save, or SaveAs.  None of these options work.  The only way to recover is to Cancel and then restart Code.

Reproduces without extensions: Yes/No    - Not sure

**Comment by isidorn** [comment]
@varnk can you also reproduce this with latest vscode insiders?
https://code.visualstudio.com/Insiders/
fyi @bpasero
