### ISSUE TITLE
x64 bug in extension regex processing causes runaway memory use

### ISSUE THREAD

**Issue by coe-jeubanks** [Microsoft/vscode#35391]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
jet|dio|0.0.1
xml|Dot|1.9.2
backspace-plusplus|jri|0.0.16
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
SQR|Cit|0.2.5

(1 theme extensions excluded)

---

Extension processing using x64 version of VS Code improperly handles single quote regex match of "('(?:\\\\'|.)*?')" with a string containing a pound sign character (e.g. 'string#'). Symptom is runaway memory use until the workstation becomes unresponsive.

Steps to Reproduce:

1. Install SQR 0.2.5 extension
2. Open a file containing a single line:   print 'Emp# '     (+1,1)

Reproduces without extensions: No

**Comment by sandy081** [comment]
Please file bug against the corresponding SQR extension

**Comment by coe-jeubanks** [comment]
The bug is not caused by the extension. The bug is caused by faulty regex processing in VS Code. The regex processing works perfectly well in the x86 version of VS Code.

**Comment by aeschli** [comment]
@coe-jeubanks Where did you find this regex?

**Comment by aeschli** [comment]
Ok, got it: https://github.com/CityOfEscondido/Visual-Studio-Code-SQR/blob/6754ec99c75ae70aaa88d454675f4365eb9401de/syntaxes/sqr.json#L68

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-textmate#56
