### ISSUE TITLE
reactNamespace makes tsconfig.json invalid for VSCode

### ISSUE THREAD

**Issue by Bobris** [Microsoft/vscode#3539]
Version of VSCode: 0.10.8
In workspace I have 2 files `tsconfig.json` and `app.tsx` and `npm install bobril` (it does not matter what module it is, it only should not be React) 
I have this in `tsconfig.json`:

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "jsx": "react",
        "reactNamespace": "b"
    },
    "compileOnSave": false,
    "files": [
        "app.tsx"
    ]
}
```

Next I have this in `app.tsx`:
```
import * as b from "bobril";

b.init(()=> <div><h1>Header</h1><p>Lorem upsum</p></div>);
```

tsc.exe 1.8.2 successfully compiles it.
But Vscode shows error in `app.tsx` on import "Cannot compile modules unless the '--module' ..." this error goes away if I remove `"reactNamespace": "b"` from `tsconfig.json` and it shows correct error on `<div>` that React is undefined.
Only workaround I found is to remove that custom namespace and add line `const React = b;` to `app.tsx`.

**Comment by egamma** [comment]
VSCode 0.10.8 ships with TS 1.7.5. Can you try with enable TS 1.8.2 in Code using the tsdk setting (see https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) or you can try the Feburary update available on the insiders channel on early next week.

**Comment by Bobris** [comment]
You are right. And I though I tried this also before.
