### ISSUE TITLE
VSCode suggesting html classnames everywhere in .vue files

### ISSUE THREAD

**Issue by victorgarciaesgi** [Microsoft/vscode#35392]
- VSCode Version: 1.16.1 
- OS Version: macOs High Sierra 10.13

[Screenshot](https://image.noelshack.com/fichiers/2017/39/5/1506705882-screenshot-at-sep-29-19-24-08.png)

When Intellisense want to suggest something in the Typescript part, it suggest html class names. Same happen within scss structure. 

Atom handle the problem very well and it is really a frustrating bug

**Comment by mjbvz** [comment]
This is likely coming from one of the extensions you have installed. You can launch code with the `--disable-extensions` command line flag to check this. 

Try to narrow down which extension is causing this and report the issue against them

**Comment by victorgarciaesgi** [comment]
Yeah thanks! I found the extension responsible: Html CSS Support
[Link to extension](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)

Hope they will fix this because .vue files are interpreted as Html files
