### ISSUE TITLE
Error from the plugin host: write EPIPE

### ISSUE THREAD

**Issue by Yemolai** [Microsoft/vscode#354]
Since I've upgraded my Code, for a few minutes it works ok, like ever, but suddenly a plugin freezes the entire application and when I kill it (a node.exe process that's using a lot of memory and 50% of processor, what means here that it's using an entire processor, because it's dual core) Code shows me these messages:

>Error from the plugin host: write EPIPE
>Plugin host terminated unexpectedly. Please restart VSCode to recover.
>Error from the plugin host: channel closed

And I have no more code suggestions.

I'm editing PHP files, writing in PHP/HTML. Using windows 7 x32 with Code version 0.10.1 from 2015-11-17, with Shell version 0.34.1 and Node version 4.1.1

Oh, and Code started to ask me for the PHP executable path:
> Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

I activated it before and with the sudden crashes, I though maybe was my php executable, deactivated it but the crashes still happen.

**Comment by bpasero** [comment]
This is #160
