### ISSUE TITLE
View sub-menu blocking other menu items

### ISSUE THREAD

**Issue by richarddunnebsc** [Microsoft/vscode#35400]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.  Open Visual Studio Code
2.  Click on menu items File, Edit, Selection.  Each items sub-menu opens below menu items, all other 
     menu items are directly accessible.
4.  Click on menu item View, menu items Go, Debug, Tasks and Help are all blocked/hidden by the View 
     sub-menu.  Go, Debug, Tasks and Help are not directly accessible until the View sub-menu is closed 
     by clicking View.  
![viewsubmenu](https://user-images.githubusercontent.com/32400931/31034248-27d71f5c-a55b-11e7-9591-8877658afed0.png)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by richarddunnebsc** [comment]
I did look for one but didn't see it.  Thanks.
