### ISSUE TITLE
Make Git Synchronize useful for a wider audience

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35402]
I don't use Synchronize because it can:
- Merge, when I usually want to rebase.
- Push after merging, when I usually want to check the merge went smooth.

The current confirmation dialog really only helps me avoid triggering the action by accident.

It would be more useful if its behavior changed based on the current status (doing a `git fetch` first):
- When there only incoming changes: pull without confirmation dialog.
- When there are only outgoing changes: push with confirmation dialog "There are no incoming changes, do you want to push your outgoing changes?"
- When there are incoming and outgoing changes: pull and merge or rebase with confirmation dialog "There are incoming changes, do you want to merge or rebase your outgoing changes?" (showing Merge and Rebase buttons to choose from)
- When there are neither incoming nor outgoing changes: do nothing, no dialog/message.

This will break the original workflow of push&pull into two steps in the case where there are incoming and outgoing changes, it remains one step in all other cases.

Only the two cases where there is potential harm (merge/rebase needed and push) a confirmation dialog is shown, informing the user what is about to happen.

**Comment by joaomoreno** [comment]
> Merge, when I usually want to rebase.

In the team, we all have `pull.rebase = true` in our git settings, at least in the vscode repo.

> Push after merging, when I usually want to check the merge went smooth.

Well, that's a pull, not a sync.

---

This is not about changing Sync, it's about adding more confirmation dialogs around it.

Feel free to submit a PR, but I'd like to always have a way to get to the current state: no dialogs whatsoever. That can be achieved with `Never Ask Again` buttons.
