### ISSUE TITLE
Visual Code can't create index.lock while discarding many files

### ISSUE THREAD

**Issue by SnapJag** [Microsoft/vscode#35408]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
mssql|ms-|1.2.0
PowerShell|ms-|1.4.3
team|ms-|1.122.0
html-preview-vscode|tht|0.1.1

---

Problem.
An error message "fatal error cannot create .git/index.lock file".
Making bulk changes to my files doesn't yield the error.
However, performing undo of edits will produce error in Visual Code.
Discard of 1 file works fine.
Discard of 2 files works fine.
Discard of 60 files does not work fine. It produces the following error...

Sample of one of the files, among the 60 discards...

```
git checkout -q -- k:\repos\projectloc\Installer\Packager\Settings\file.txt
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git checkout -q -- k:\repos\projectloc\Installer\Packager\Settings\DB_Pkgr_Settings.xml
git show HEAD:Installer/Packager\Settings/PackagersFile.bat
fatal: Unable to create 'k:/repos/projectloc/.git/index.lock': File exists.
```

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

- If this operation is performed using GitExtensions, with Visual Code open, the same error is produced.
- If this operation is performed using GitExtensions, with Visual Code closed, the same error is NOT produced.

Steps to Reproduce:

1. Open a GIT repository
2. Create a bunch of file edits
3. Undo a majority of them
4. In the OUTPUT window the "cannot create */.git/index.lock file"....

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Very likely fixed by the same commit which fixed #35216 last week.
