### ISSUE TITLE
Stage with merge conflicts warning still appears after all conflicts resolved

### ISSUE THREAD

**Issue by ecraig12345** [Microsoft/vscode#35404]
- VSCode Version: 1.16.1
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Do a git merge/rebase operation that causes merge conflicts
2. Using the Source Control pane, open each file with conflicts, resolve the conflicts, and save
3. Try to stage the file--even though all the conflicts are resolved (and all conflict markers removed), I still get the message "Are you sure you want to stage _______ with merge conflicts?"

This is annoying since I have to take extra time/clicks to confirm the dialog before moving on to the next file.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#33983
