### ISSUE TITLE
snippets: still completion use tab when deleting a property

### ISSUE THREAD

**Issue by cipchk** [Microsoft/vscode#35409]
- Version 1.16.1
- Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
- Date 2017-09-14T16:38:23.027Z
- Shell 1.7.3
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

a gif:

![error](https://user-images.githubusercontent.com/2987467/31043100-b91e833c-a5e8-11e7-9171-295e1a033437.gif)

the snippet code: 

```json
"general button": {
    "prefix": "nz-button",
    "body": "<button nz-button (click)=\"${2}\" [nzType]=\"'${3|primary,dashed,danger,default|}'\"${4: [nzSize]=\"'${5|small,large|}'\"}>$1</button>\r\n$0",
    "description": "按钮（只含type&size）",
    "scope": ""
}
```

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
#31619
