### ISSUE TITLE
Provide additional workspace API (read / write)

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#35407]
Today I can call [vscode.openFolder](https://github.com/Microsoft/vscode/blob/56cfb2754a37f532e17a40c01fc3490b9d63c38f/src/vs/workbench/api/node/extHostApiCommands.ts#L184) to open a folder programmatically:
```
vscode.commands.executeCommand("vscode.openFolder", vscode.Uri.file(path), false);
```

However, I would like to be able to do the same thing with the new multi-root workspace and just _add_ a folder to the workspace. Something like [this](https://github.com/Microsoft/vscode/blob/424e1ebc28edbee570ffcee769410f00bd287500/src/vs/workbench/browser/actions/workspaceActions.ts#L95), but where I can pass in a Uri

For more context on our scenario, see @chrisdias's comments on this issue: https://github.com/Microsoft/vscode/issues/13807

NOTE: We realize such a command might restart the extension host, but we don't care if that happens.

**Comment by bpasero** [comment]
fyi @jrieken @sandy081 I guess eventually it would make sense to expose some kind of workspace editing API to extensions.

**Comment by jrieken** [comment]
I like, tho the weird thing we need to communicate is that calling such API might restart the extension itself

**Comment by EricJizbaMSFT** [comment]
The 'openFolder' api has the same behavior and just includes this in the description: 

> Open a folder in the current window or new window depending on the newWindow argument. Note that opening in the same window will shutdown the current extension host process and start a new one on the given folder unless the newWindow parameter is set to true.

**Comment by bpasero** [comment]
This landed as `workspace.addWorkspaceFolder` and `workspace.removeWorkspaceFolder`.

**Comment by bpasero** [comment]
I reverted this change due to https://github.com/Microsoft/vscode/issues/37301

**Comment by stef-levesque** [comment]
I hope that `workspace.addWorkspaceFolder` will come back. I'm working on an extension that would allow to open .zip files as workspace folders, along with using proposed api `FileSystemProvider`.

Creating a workspace file and opening it is not really an option here.

**Comment by alefragnani** [comment]
@bpasero, what about `vscode.workspace.path`/`vscode.workspace.uri` too? I mean, we have the `uri` for each folder in a workspace, but not for the workspace itself.

I would love to have this, so I could update my *Project Manager* extension and add `workspaces` as favorite projects, just like regular folders.

Thanks

**Comment by bpasero** [comment]
@alefragnani I extracted that particular request to https://github.com/Microsoft/vscode/issues/37421

@stef-levesque we are still in discussion how to best do the API, it might need another iteration.

**Comment by bpasero** [comment]
Some ideas discussed in https://github.com/Microsoft/vscode/issues/35407

**Comment by stef-levesque** [comment]
The splice'ish solution works for me, it easily cover most cases (add, delete, insert)

Except moving order? Not a show-stopper though.

**Comment by bpasero** [comment]
@stef-levesque reordering would be possible via add & remove as well

**Comment by stef-levesque** [comment]
Is closing a workspace going to close all related TextDocument ?

**Comment by bpasero** [comment]
@stef-levesque no, closing a workspace is currently not closing any documents.

**Comment by EricJizbaMSFT** [comment]
@bpasero any update on this? I see the api was removed because of https://github.com/Microsoft/vscode/issues/37301, but we don't need all of the functionality listed in that. We just want a single command to add a folder to a workspace. If 'remove' and 'insert' are blocking 'add', can we save those for later?

**Comment by bpasero** [comment]
@EricJizbaMSFT no update so far other than this is "on deck" so it will happen eventually. Please talk to @egamma or @kieferrm to put some pressure on this if this must happen at a specific time.

**Comment by bpasero** [comment]
@EricJizbaMSFT can you share more details on your scenario of adding a workspace folder from an extension?

**Comment by chrisdias** [comment]
azure function extension is a good example, it lets you create a new Azure Function "project", which is really just a folder.  

So, imagine I have a folder open, my web app called "stickerApp".  It could be the only folder open, or it could be a part of a workspace.  

![image](https://user-images.githubusercontent.com/1487073/34889153-dbfdf622-f781-11e7-8f78-4392c4c83bb7.png)

With the Azure Functions extension I choose to "Create a new Azure Function Project" from the command palette or the explorer commands. 

![image](https://user-images.githubusercontent.com/1487073/34889176-f2aeb154-f781-11e7-96fa-050f75fbd804.png)


This command first prompts me for the folder location in which to scaffold the project:

![image](https://user-images.githubusercontent.com/1487073/34889200-01583900-f782-11e7-8ac4-08d08f2985ca.png)

I choose Browse... and get the folder picker:

![image](https://user-images.githubusercontent.com/1487073/34889240-24ef7b4e-f782-11e7-8ec2-5ca9c0d7f3af.png)

And I pick some new folder called `stickerFunctions`

The `func` cli then scaffolds out the new sticker function in the `stickerFunctions` folder.

At this point I probably want to start working on this function. Ideally it would be added to the explorer as a second top level root node:

![image](https://user-images.githubusercontent.com/1487073/34889314-66398360-f782-11e7-8a84-04edf438d68e.png)
