### ISSUE TITLE
Allow to open all hidden files via "code ."

### ISSUE THREAD

**Issue by cjrams** [Microsoft/vscode#35401]
- VSCode Version:  1.16.1 (1.16.1)
- OS Version: Mac OSX Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Enable command line 
2. Enter in a directory with hidden files and or folders (Starting with dot)
3. Type "code ."
4. Code is open with the hidden files and folder but not the current dir as expected

Reproduces without extensions: Not sure

**Comment by bpasero** [comment]
@cjrams can you be more specific of what happens? maybe attach a vide or screenshots?

**Comment by cjrams** [comment]
I was expecting to open the current folder, but just open hidden files, ie, file starting with a dot. 
There is a implicit filter in the file that is specifies in the command line, there is a way to force to open the current folder instead?

**Comment by bpasero** [comment]
I see, that is not possible the way you do it. "." always references the current folder.

**Comment by bpasero** [comment]
Closing "as designed".
