### ISSUE TITLE
markdown preview does not support font ligatures

### ISSUE THREAD

**Issue by brentian** [Microsoft/vscode#35410]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
path-intellisense|chr|1.4.2
python|don|0.7.0
tslint|eg2|1.0.9
json-tools|eri|1.0.2
mdmath|goe|2.0.6
prettify-json|moh|0.0.3
cpptools|ms-|0.13.0
vscode-icons|rob|7.14.0
code-spell-checker|str|1.4.0
html-preview-vscode|tht|0.1.1
python-extended-snippets|tus|0.0.1
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.10.3
------
editor already supports this.

**Comment by mjbvz** [comment]
The markdown preview is just a webview. It supports ligatures if the font used in the webview supports them. 

Try setting `"markdown.preview.fontFamily"` to change the font. You can also use custom css in the webview with `"markdown.styles"`
