### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by tobiashoeft** [Microsoft/vscode#35411]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.10.0
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
ng-template|Ang|0.1.7
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
docthis-customize-tags|dwe|0.4.5
gitlens|eam|5.3.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
vsc-material-theme|Equ|1.0.3
prettier-vscode|esb|0.23.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.1
code-runner|for|0.7.2
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
typelens|kis|1.5.0
vscode-codemetrics|kis|1.9.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
angular-cli|pko|1.0.1
vscode-icons|rob|7.14.0
prettier-eslint-vscode|Rob|0.7.1
code-settings-sync|Sha|2.8.3
autoimport|ste|1.2.2
code-lens-roundup|wad|1.0.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.10.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.open package.json
2.show dependency

**Comment by sandy081** [comment]
@tobiashoeft Are there any steps to reproduce this issue? Also did you try reproducing it by disabling all extensions?
