### ISSUE TITLE
Register code as an editor in Debian with update-alternatives

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3541]
See https://github.com/Microsoft/vscode-docs/issues/194

https://www.debian-administration.org/article/91/Using_the_Debian_alternatives_system

This will be a matter of adding some lines to `postinst` and `prerm`in the Debian package to register and deregister using `update-alternatives`.

**Comment by borgdylan** [comment]
Would it be possible to add the contents of prerm/postrm scripts in the zip files for Linux? People not using packages might also want to do such registration manually.

**Comment by Tyriar** [comment]
@borgdylan once the deb file is available you can always just download that and extract it, it contains the contents of the zip as well as the launcher, desktop and (un)installation scripts.

**Comment by borgdylan** [comment]
I happen to install manually, are these file available separately here on github as well?

**Comment by Tyriar** [comment]
@borgdylan an official build of the deb package won't be available until the March release. Is there any reason you would opt for manual once this is available over an official apt package?

**Comment by borgdylan** [comment]
I opted for that since I used to customize the install myself to support my own programming language.

**Comment by Tyriar** [comment]
Well I recommend the deb package when it's out, it just handles everything for you; a nice launch wrapper, launcher integration, registering apt repository for updating through OS software updater (https://github.com/Microsoft/vscode/issues/2973). Plus clean removal with `dpkg`/`apt-get`.

**Comment by Tyriar** [comment]
Verified:
![image](https://cloud.githubusercontent.com/assets/2193314/13998250/69612940-f0f3-11e5-88d2-2e0ac6469a77.png)
