### ISSUE TITLE
php support needs some attention 

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#35416]
If php is supported as a core feature rather that plugins it would be fantastic. Vscode is good at each and every other places congrats for that. no one can beat vsCode when comes to typescript and javascript. But when php it gets boring. Plugins helps alot but it doesn't fill the gap. 
thanks,

**Comment by willsilvano** [comment]
I agree with @prasanthnv ... 
the autocompletion of php plugins is actually a bit slow...

**Comment by roblourens** [comment]
We have some basic built in PHP support, but we expect dedicated extensions, like the PHP Intellisense extension to provide advanced support.
