### ISSUE TITLE
VS keybindings extension overrides word navigation with column selection on OSX

### ISSUE THREAD

**Issue by adison** [Microsoft/vscode#35412]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vsc-rustfmt|Con|0.1.0
swift|Kas|0.0.3
githistory|don|0.2.3
python|don|0.7.0
unicode-normalizer|esp|0.0.1
vscode-auto-open-markdown-preview|hnw|0.0.4
Lua|key|0.0.9
Go|luk|0.6.65
MagicPython|mag|1.0.12
prettify-json|moh|0.0.3
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.3.1
Ruby|reb|0.15.0
RustyCode|sav|0.19.1
guides|spy|0.8.4
code-spell-checker|str|1.4.0
vscode-react-native|vsm|0.4.2
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1. use alt + arrow key(left/right) to jump word by word
2. use shift to select anything(word or letter) and try alt + arrow(right/left) again, it can only move letter by letter.

Reproduces without extensions: Yes

Without this feature, it's hard to delete multiple words efficiently.

**Comment by alexandrudima** [comment]
@adison I cannot reproduce, word navigation works as expected for me.

Please check:
* extensions can redefine keybindings. Are the `alt+arrow` keys still bound to word navigation? (you can disable extensions or search for `"alt+leftarrow"` in the keybindings UI at `cmd+k cmd+s`)
* Have you customized `editor.wordSeparators`

**Comment by adison** [comment]
I have disabled all extensions before make this clip, what I mentioned is below, while using alt+shift+left/right, it move letter by letter.
[http://www.giphy.com/gifs/xT9IgxgK5tQmbIFLzO](http://www.giphy.com/gifs/xT9IgxgK5tQmbIFLzO)

No idea if I made changes to editor.wordSeparators, I think no though, and it is ```  "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",```

**Comment by alexandrudima** [comment]
@adison Can you please check your keybindings for `shift+alt+right`:
* open the keybindings UI: `cmd+k cmd+s`
* search for `shift+alt+right`

Check that it is bound only to this command:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/5047891/31068330-ccd532c0-a757-11e7-9655-12f1c9dc8307.png">

**Comment by adison** [comment]
There are two items..
What should I do? and it seems a default binding, isn't it?
![2017-10-02 15 58 01](https://user-images.githubusercontent.com/2823871/31068454-9ff5368c-a78a-11e7-8169-b7e5585d0525.png)

**Comment by adison** [comment]
@alexandrudima Hi, I just map the **cursorColumnSelectRight to control+shift+right**, and so on cursorColumnSelectLeft, it works fine now.
And I would suggest put this setting to default setting, I have no idea what is cursorColumnSelectLeft yet, but I do need select and move by word by alt+shift+left/right, just as other application, kind of sublime text and many others.

I will leave this for you to close or what you want, like leave as note for those have same problem.
Thanks for your help.

**Comment by alexandrudima** [comment]
@adison based on your screenshot, it appears an extension defines `alt+shift+left/right` to be column selection instead of word selection.

Specifically, I believe the `vs-keybindings` would do that.

In your initial report, you have the following incorrect statement:
> Reproduces without extensions: Yes

**Comment by rebornix** [comment]
This issue was moved to rebornix/vscode-vs-keybindings#25
