### ISSUE TITLE
Wrong scss completion - unwanted colon (?)

### ISSUE THREAD

**Issue by SharakPL** [Microsoft/vscode#35418]
I've just started using VSCode and scss so apologize if I'm mistaken, but this behaviour seems wrong to me

- VSCode Version: 1.16.1
- OS Version: Windows 10 x64

Steps to Reproduce:
In .scss file
![scss](https://user-images.githubusercontent.com/5007456/31044981-63843b64-a5da-11e7-9199-0570251d72d1.gif)
![scss1](https://user-images.githubusercontent.com/5007456/31045128-f674ec32-a5dc-11e7-9332-2b380ad5c58f.gif)
![scss2](https://user-images.githubusercontent.com/5007456/31045129-f67e1b22-a5dc-11e7-84b5-35a11abd87e6.gif)

Suggestions are correct, but selecting them always adds unwanted `:<space>` that breakes the code

Reproduces without extensions: Yes, all extensions disabled

**Comment by SharakPL** [comment]
Here's expected behaviour taken from Sublime Text 3 with sass plugins

![scssnorm](https://user-images.githubusercontent.com/5007456/31045325-8ed80e42-a5e1-11e7-901d-9bace2b50496.gif)

**Comment by rebornix** [comment]
@SharakPL are you using any extension which might change the behavior of the auto-complete? I tried with latest Code but can not reproduce. Thanks!

**Comment by SharakPL** [comment]
It was fixed in 1.18 :p

**Comment by SharakPL** [comment]
@rebornix it was fixed in 1.18, if I remember correctly
