### ISSUE TITLE
PHP Syntax Coloring

### ISSUE THREAD

**Issue by Hoto-Cocoa** [Microsoft/vscode#35415]
- VSCode Version: 1.16.1
- OS Version: Windows 10 Pro (Build 15063.608)

Steps to Reproduce:

1. Clone `https://gitlab.com/librewiki/Liberty-MW-Skin.git`.
2. Open `LibertyTemplete.php`.

![image](https://user-images.githubusercontent.com/21969938/31043576-9000dce6-a5f9-11e7-9127-728ad9bbf2e6.png)
![image](https://user-images.githubusercontent.com/21969938/31043588-c3f946dc-a5f9-11e7-87f0-172bae6d32fb.png)
![image](https://user-images.githubusercontent.com/21969938/31043593-da90a6ec-a5f9-11e7-867d-e798dead54d2.png)

This did not occur in previous versions. and works well in atom.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I just updated the PHP grammar which, I think, fixes this issue with end tags (`?>`) inside of PHP curly braces once and for all.

It will be out in the next Insider's build.

**Comment by Hoto-Cocoa** [comment]
classes colored with white, how about it?

**Comment by roblourens** [comment]
I see the problem, it will be fixed in the next Insiders build out some time next week.

**Comment by Hoto-Cocoa** [comment]
ok. thanks!
