### ISSUE TITLE
Rename symbol problem with TypeScript

### ISSUE THREAD

**Issue by martin19** [Microsoft/vscode#35417]
There are problems renaming of symbols in base/derived objects.

In the example below:
* Renaming foo in "basevar" does not rename foo in "derivedvar".
* Renaming foo in "base" does not rename foo in "derivedvar"
* Renaming foo in "derivedvar" does not rename foo in "base" and "basevar". (webstorm offers an option to rename base symbols here)

```typescript
const basevar : base = {
    foo:42    
};

const derivedvar : derived = {
    foo:42
}

interface base {
    foo:number;
}

interface derived extends base {
    foo:number;
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#18866
