### ISSUE TITLE
Emmet doesn't want to beautify code

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#35420]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

If we have `div>p`:
![image](https://user-images.githubusercontent.com/24613274/31046070-d741e838-a5fa-11e7-815d-d9ff5cdf57f9.png)

if will expand into:
![image](https://user-images.githubusercontent.com/24613274/31046079-fab4dbd6-a5fa-11e7-8615-442382c8a1a4.png)

But if we do have something like `form>select`:
![image](https://user-images.githubusercontent.com/24613274/31046098-41c63ef2-a5fb-11e7-8ffe-1042033f49a3.png)

it would be a little mess with no work of beautifier and indents: 
![image](https://user-images.githubusercontent.com/24613274/31046100-514bab14-a5fb-11e7-87fe-5319fe28cdb7.png)

It starts to beautify the code only if there 3+ options (inputs, etc.) in the form:
![image](https://user-images.githubusercontent.com/24613274/31046115-9b9419b8-a5fb-11e7-8c68-a734ef2502f2.png)

I think it should do also for 1 and 2.

**Comment by ramya-rao-a** [comment]
Try setting "inline_break" to 1 or 2 as per your requirement
```
"emmet.syntaxProfiles": {
    "html":{
        "inline_break": 1
    }
}
```

Documentation: https://docs.emmet.io/customization/syntax-profiles/#create-your-own-profile

**Comment by ramya-rao-a** [comment]
@sergeche `form` is a block element and `select` is an inline element

I understand why `select*2` would result in the select tags appearing without a line break
But when `select` is a child of `form` in the abbreviation `form>select` shouldn't `select` appear in the new line regardless of the `inlineBreak` profile setting?

**Comment by sergeche** [comment]
No, since select is inline element, it’s output is controlled by inlineElements option, which is 3 by default, e.g. there must be 3 inline elements inside block to enable formatting. As an option, you can make `select` a block-level element

**Comment by ramya-rao-a** [comment]
@user3323 For now use the `inline_break` setting.

I'll wait and see if there is more feedback on this. If so, then will consider treating `select` as a block element.
