### ISSUE TITLE
Don't try to "open" executables when clicked in the explorer

### ISSUE THREAD

**Issue by skunkiferous** [Microsoft/vscode#35426]
- VSCode Version: 1.16.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Compile your code to some *.exe file, which shows up in the explorer
2. Left-click on it.
3. VS-Code tries to open the file, and complains it's "binary", although opening executable files makes no sense.

VS-Code might not know about all possible binary formats, but it really should at least recognize the OS's own executable files. Alternatively, it could just "run" the files; at least that would make some sense.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
