### ISSUE TITLE
Settings - color picker absorbs quote-marks

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#35422]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

Color picker in the settings, after you choose a color, absorbs the quote-marks around it.

GIF:
![settings - color picket - qmarks](https://user-images.githubusercontent.com/24613274/31046288-b6bed32e-a5fe-11e7-8334-1d7d279cd80e.gif)

**Comment by aeschli** [comment]
@user3323 Can you give the exact version of VSCode where you see this?
Also, please file a separate issue for the second issue. Please attach the content of a settings file where this can be reproduced.

**Comment by user3323** [comment]
@aeschli, well, now I got update to:

![image](https://user-images.githubusercontent.com/24613274/31147498-c45e97a8-a892-11e7-9420-2c62098b803a.png)

and the issue with "absorbing quote-marks" is gone.. seems like you already fixed it?

**Comment by aeschli** [comment]
Yes, there was a fix for that, but I wanted to make sure that you don't see it in the current version.
Closing then.
