### ISSUE TITLE
Debug C program on fopen() 

### ISSUE THREAD

**Issue by ChanJuiHuang** [Microsoft/vscode#35424]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-atom-javascript-snippet|glu|0.2.1
vue-snippets|hol|0.1.5
atom-keybindings|ms-|3.0.2
cpptools|ms-|0.13.0
code-spell-checker|str|1.4.0
debug|web|0.21.2
---
I use Native Debug to debug C program, but it always show this error message for me on the top screen. I just test how to use vscode to debug. My C code can compile and execute correctly.

ERROR MESSAGE: Unable to open 'iofopen.c': File not found (/build/glibc-6V9RKT/glibc-2.19/libio/iofopen.c).

Thank you very much^^

This is my code.

```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  if (argc != 2)
  {
    fprintf(stderr, "Usage: ./recover image\n");
    return 1;
  }

  char *infile = argv[1];
  char outfile[10];
  FILE *inptr = fopen(infile, "r"); // It always break on this line, and cannot run to next line
  FILE *outptr = NULL;

  int fileNum = 0;
  int isOutFileExist = 0;
  unsigned char imgBuffer[512];

  while (fread(imgBuffer, sizeof(unsigned char), 512, inptr))
  {
    if (imgBuffer[0] == 0xff &&
        imgBuffer[1] == 0xd8 &&
        imgBuffer[2] == 0xff &&
        (imgBuffer[3] & 0xf0) == 0xe0)
    {
      if (isOutFileExist)
      {
        fclose(outptr);
      }
      isOutFileExist = 1;
      sprintf(outfile, "%03i.jpg", fileNum++);
      outptr = fopen(outfile, "w");
    }

    if (isOutFileExist)
    {
      fwrite(imgBuffer, sizeof(unsigned char), 512, outptr);
    }
  }

  fclose(outptr);
  fclose(inptr);
}
```

**Comment by isidorn** [comment]
Please file this against the c extension you are using.
Thank you
