### ISSUE TITLE
Code Hints/Intellisense should be disabled when writing comments, especially multiline ones.

### ISSUE THREAD

**Issue by VulcanRav** [Microsoft/vscode#35423]
- VSCode Version: 1.16.1
- OS Version: Windows 7 Home Premium

Steps to Reproduce:

1. Start a multiline comment
2. Press a dot.

Reproduces without extensions: Yes

When I write the documentation for my files it's very annoying that each time I type a dot (.) I get suggested the various methods and attributes I can access.

**Comment by mjbvz** [comment]
What language are you working in? Do you have `editor.wordBasedSuggestions` enabled?

**Comment by VulcanRav** [comment]
yes I do, and I want it to be True.

My point is that the editor should understand itself to make it false when I'm writing a comment rather than code.

**Comment by jrieken** [comment]
> My point is that the editor should understand itself to make it false when I'm writing a comment rather than code.

You should know the setting supports more than `true` or `false` but also this: `"editor.quickSuggestions": {"comments": false }`
