### ISSUE TITLE
Add option to open preview in new editor from icon

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#3542]
Most of the time when you're working in markdown (and probably SVG if the preview gets added to that view) you probably want to be able to see the source and the rendered result side by side. Currently you have to do a two step process of opening a new editor then pressing the preview toolbar button. There is also a (not so discoverable keyboard shortcut…which I couldn't get to work until I realised I had to let go of command-k first before pressing v)

Would be nice if you could do something like right click the preview icon and select open in new editor from a drop down or some such..

**Comment by bpasero** [comment]
There is a command to do this in F1 and you can change its keybinding.
