### ISSUE TITLE
Multiple select in the explorer list (feature request)

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#35421]
- VSCode Version: 1.17.0-ins
- OS Version: win7x64

If the user has many of unnecessary files, like a.js, b.js, c.js, etc:

![image](https://user-images.githubusercontent.com/24613274/31046258-4c07ffb0-a5fe-11e7-904b-a7790f3cc823.png)

It would be great to make a multiple selection by holding **Shift** , and delete them, or do whatever you want.

Don't you think?

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
