### ISSUE TITLE
[loc] Adding language - Hindi to transifex VS Code project

### ISSUE THREAD

**Issue by mohitsoam** [Microsoft/vscode#35427]
I'd be willing to take part in this initiative.
Translation language interested: **Hindi**
Transifex username: **mohitsoam**

**Comment by danyeh** [comment]
Adding guidance here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
We need 3 votes by put Transifex account here.

**Comment by asphub** [comment]
https://www.transifex.com/user/profile/asphub/

**Comment by asahasrabuddhe** [comment]
Hi,

Let's make this work. My account is: asahasrabuddhe

Regards,
Ajitem

**Comment by danyeh** [comment]
Thank you for showing interest to contribute! Hindi (hi) has been enabled in Transifex.
