### ISSUE TITLE
LF/CRLF silent change on Git Diff View. Statusbar shows wrong info. No warning.

### ISSUE THREAD

**Issue by superherointj** [Microsoft/vscode#35428]
Note: LF/CRLF on statusbar doesn't change on switching window in Git Diff View 

- VSCode Version: 1.16.1
- OS Version: linux

Steps to Reproduce:

Have a file saved in repository as CRLF. Open VSCode in Linux, open Git tab, pick the file. Git will show it as having changed but when switching active tab (inner window) on Git Diff View, LF/CRLF status is not updated. And there isn't any warning on the change between LF/CRLF.

It shows the file having changed but having no visible change. There should have some warning as the content is the same and change being the difference between LF->CRLF, this is problematic.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#5118
