### ISSUE TITLE
Custom debugger adapter met serious error somtimes

### ISSUE THREAD

**Issue by minggo** [Microsoft/vscode#3543]
I am writing a debugger adapter, and sometimes i met a strange exception error like this:

<img width="941" alt="screen shot 2016-02-29 at 10 29 51 am" src="https://cloud.githubusercontent.com/assets/488203/13384348/b9ba2abc-decf-11e5-8ec5-a767d3392817.png">

I don't know what's the error and how to trigger it. This error exists even i restarted VSCode. I have to restart my computer to fix the error.

My environment:
* VSCode: 0.19.0
* MAC OS X: 10.11.2

**Comment by minggo** [comment]
I found node app is not terminated when VSCode is quit. So the port is occupied by the node and cause the error.  

Why not terminated corresponding node when terminating VSCode?

**Comment by weinand** [comment]
@minggo the address in use '4711' indicates that **your** debug adapter is not killed. This can happen if your adapter is in a weird state and for some reason VS Code is not able to kill it successfully. You do not have to restart your computer. On OS X just run the 'Activity Monitor' and search for 'node'. If you are not  in a debugging session, there should be no 'node' processes running. If there are any, you can kill them.
(alternatively you can use `killall node` from the command line).

**Comment by minggo** [comment]
@weinand Yep, i killed the node process to resolve it.
Thanks.
