### ISSUE TITLE
TypeScript: aggregate errors for file from all projects

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#35432]
I have a project with three folders, two of which are TS projects and the third of which is shared between them:

- shared
- service-worker (with `tsconfig.json`)
- browser (with `tsconfig.json`)

Both "browser" and "service-worker" depend on "shared".

However, when I open a file in "shared", I only see errors related to one of the `tsconfig.json`s—usually this will be the `tsconfig.json ` used for the file I navigated from previously.

It would be great if VSCode could aggregate all errors for the current file for all matching TS projects.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20185
