### ISSUE TITLE
Support edit time browsing of source-maps of node_modules/ dependencies when source maps are available?

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#35439]
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: macOS 10.12.6

Some npm modules ship with sourcemaps (.map files or inline sourcemaps) and compiled js.  When source maps are present vscode is quite successful at presenting the sourcemapped codebase when debugging.

There are still gaps in the experience though when I want to set a breakpoint somewhere in one of my compiled node_modules/ packages.   I have to navigate to the compiled code, set a breakpoint somewhere in the compiled output, start the debugger, and then I'll end up in the original source through sourcemap translation with a  nice debugger experience ...  It would be amazing if vscode offered a mechanism that allowed directly navigating the sourcemaps of npm modules when available (in some kind of non-editable mode since changes to such a source-mapping presentation would of necessity not behave as expected without integration with the module's build process).  This way I could set breakpoints in a representation of the original source rather than it's compiled output.

This feature would also provide better readability ergonomics for browsing the code of my project's npm dependencies.  There's a large speed and convenience difference between peaking at the code on my disk in my editor vs (1) figuring out the version of the project on my disk and then (2) navigating to that version of that project's codebase wherever it happens to live (in practice this experience usually means opening the project on github and having a much worse code navigation experience than exists in vscode).

**Comment by auchenberg** [comment]
Could debuggers contribute source mapped (inlined) resources in the "loaded scripts" pane? This could give a similar experience to browser DevTools.

**Comment by weinand** [comment]
Not now, but this is planned.

**Comment by roblourens** [comment]
I think this is different because in this scenario, the debug adapter isn't running. I think the loaded scripts pane should only show resources loaded in the debuggee.

The new remote resource API might be a good fit. I'm not sure what this experience would look like though, showing sources that are inlined in sourcemaps, but not other sources?

**Comment by auchenberg** [comment]
I think a first step could be the make source mapped resources show up in "Loaded scripts" while debugging running + a mechanism to map the resource to a local resource via select-file-dialog -> sourceMapOverride config?

**Comment by roblourens** [comment]
I think that showing the sources in the Loaded Scripts pane would be a good thing to do. But the original request - browsing inlined sourcemaps of node_modules at edit time - is out of scope.

If showing sources in Loaded Scripts is covered somewhere else, let's close this one.

**Comment by weinand** [comment]
I will add support for showing source files in the LoadedScripts view.
Let's continue to use this issue for this.

**Comment by gjsjohnmurray** [comment]
@weinand do I remember correctly that Loaded Scripts view now has a mechanism for getting to associated sources?
