### ISSUE TITLE
CTRL+BACKSPACE in Git message editor intercepted by active file text editor

### ISSUE THREAD

**Issue by pmunin** [Microsoft/vscode#35431]
When i have a file editor tab opened and I try to write a commit message for git repo, and use shortcuts that include CTRL (ctrl+backspace, ctrl+delete) - active file text editor intercepts those keyboard events and handles it modifying the file instead of modifying the message.

- VSCode Version: 1.6.1
- OS Version: Windows 10/7 Pro x64

Steps to Reproduce:

1. open a repo folder in vscode
2. Edit a file from that repo vscode text editor. hit CTRL+S to make git recognize changes. (keep editor's tab opened)
3. Switch to Source control panel in side bar. You should see the file that you modified in the list of changes to commit
4. In message editor start type "Word1 word2", then press CTRL+Backspace (to remove last word in the message)

**Expected result:**

message editor removes a word before cursor ("word2")

**Actual result:**

Active file text editor removes word before the last know position of a cursor in it

Reproduces without extensions: No

**Comment by alexandrudima** [comment]
@pmunin Which extensions do you have installed? Did you install a specific key mapping extension? What are the commands bound (and their `when` clause) when you open the keybindings UI via `ctrl+k ctrl+s` and search for `"ctrl+backspace"` ?

**Comment by pmunin** [comment]
Thanks for the hint - it helped me to figure out the problem - it's "Visual Studio Keymap" extension (from Microsoft) that adds shortcut "Ctrl+Backspace" to its command:"deleteWordStartLeft", when:(undefined). Once I removed that shortcut - it started working fine! Thank you!

**Comment by arkaic** [comment]
Also happening on OSX when I use `option+backspace`. I currently use the Emacs Friendly Keymap extension.

**Comment by rebornix** [comment]
We have restriction for `ctrl+backspace` already in the VS keymap https://github.com/rebornix/vscode-vs-keybindings/blob/master/package.json#L100  thanks!
