### ISSUE TITLE
ES2016 short version of binding context of function is not supported 

### ISSUE THREAD

**Issue by Jackmann** [Microsoft/vscode#35434]
- VSCode Version: 1.16.1
- OS Version: MacOS 10.12.6

Steps to Reproduce:
![sample](https://user-images.githubusercontent.com/13643681/31048187-ef80330c-a620-11e7-978d-b09108e0c995.png)

1. Write function similar to mine on the screen
2. Colons will be highlighted red

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Tracked upstream by: https://github.com/Microsoft/TypeScript/issues/3508

**Comment by fourteenmeister** [comment]
It's not quite clear why the typescript are here?

![image](https://user-images.githubusercontent.com/3837141/31706261-ed359526-b41a-11e7-8355-a23d8247af52.png)

- VS Code Version: 1.17.2
- OS Version: Windows 10

**Comment by mjbvz** [comment]
We use TypeScript behind the scenes to power both our JavaScript and TypeScript language support
