### ISSUE TITLE
Weird font issue

### ISSUE THREAD

**Issue by PassTheMayo** [Microsoft/vscode#35430]
One day, I hopped on Visual Studio Code and this happened:

![image](https://user-images.githubusercontent.com/16949253/31047363-cf59ea84-a5ce-11e7-8ad0-c16cedb524da.png)

I haven't touched any settings that have to do with the font family.

Side note: I reinstalled and same issue.

**Side note 2: I reinstalled and removed `~/Library/Application Support/Code` and it fixed the font issue.**

- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

I don't know how this occured.

Reproduces without extensions: Yes

**Comment by PKief** [comment]
What happens if you set the font family in your user settings to the default one:

`"editor.fontFamily": "Consolas, 'Courier New', monospace"`

Then it should be without serifs.

**Comment by PassTheMayo** [comment]
@PKief I have already reinstalled Visual Studio Code which seemed to fix the issue. Thanks though.

**Comment by alexandrudima** [comment]
@PassTheMayo By deleting `~/Library/Application Support/Code` you have removed your user `settings.json` where you probably had configured a certain font family. Perhaps there was a typo in the `editor.fontFamily` you had configured. Please let me know if you remember what settings you had in there that led to this font situation...
