### ISSUE TITLE
Is there any way to run extension commands through command line

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#35437]
Is there any way to run the extension commands through command.

Some thing like this
`code --run-extension shan.code-settings-sync --command-name DownloadSettings`

https://github.com/shanalikhan/code-settings-sync/issues/403

**Comment by jrieken** [comment]
But it has been asked before, not just for extensions but for any command such that would look more like this: `code --command myCommand`

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by jdshkolnik** [comment]
@joaomoreno This was open a month and a half. I think this would be very useful. I didn’t realize it’d be closed without votes.
