### ISSUE TITLE
Mismatched Icon

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#35436]
I'm sure this is just a caching thing and not much can be done but sharing none-the less.

![image](https://user-images.githubusercontent.com/1051190/31048435-c0b84c7a-a5d1-11e7-8405-7a477a46a13f.png)

**Comment by apap04** [comment]
![image](https://user-images.githubusercontent.com/17275723/31052037-ed8a384c-a646-11e7-8797-7275d2b711ea.png)

**Comment by chrisdias** [comment]
can you try unpinning then pinning again?

**Comment by seanmcbreen** [comment]
Did no change i.e. still two different ones following pin/unpin.

**Comment by chrisdias** [comment]
its a cache thing, not exactly sure how to fix...

**Comment by chrisdias** [comment]
try restarting...
