### ISSUE TITLE
VS Code Hangs while switching back and forth with other windows

### ISSUE THREAD

**Issue by ahmedabadawi** [Microsoft/vscode#35448]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
vscode-eslint|dba|1.3.2
Angular2|joh|2.7.0
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Have an editor open
2. Switch to another window, like a browser
3. Switch back to VS Code, it goes blank for a while and then gets back to normal
Note: The issue is not consistently reproducible

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
