### ISSUE TITLE
JS/TS Syntax highlighting issue with key/value defaults

### ISSUE THREAD

**Issue by misaxi** [Microsoft/vscode#35445]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
sort-lines|Tyr|1.3.0
python|don|0.7.0
Go|luk|0.6.65
debugger-for-chrome|msj|3.3.1
Ruby|reb|0.15.0
annotator|ryu|0.10.1
vscode-hexdump|sle|1.4.0
vscode-react-native|vsm|0.4.2
join-lines|wma|0.2.2

---

Steps to Reproduce:

```js
const fun = ({
    a = 1,
    b = 2,
    c = 3
}) => console.log(a, b, c)
```

The majority of the code snippet above is in the same color block...

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Should already be fixed in VS Code 1.17
