### ISSUE TITLE
Easier way to add items to "files to include" box

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#35442]
From https://github.com/Microsoft/vscode/issues/17164#issuecomment-333295055

We could have a 'browse' button to add external folders to the 'files to include' search box.

Example from Sublime:

![image](https://user-images.githubusercontent.com/323878/31050768-3244a0f4-a60a-11e7-9078-b220d80deb7f.png)

**Comment by surjithctly** [comment]
Thank you 👍

**Comment by ivanvoznyakovsky** [comment]
It would also be very handy when in explorer pressing Cmd + Shift + F would add focused folder path to "files to include".

**Comment by izzygld** [comment]
yes please.

**Comment by kwegezed** [comment]
This would be a very nice feature to me. I use the find in file(s) frequently in my workflow and a browse button would be a great relief.

+1

**Comment by roblourens** [comment]
I think that this would go along with https://github.com/microsoft/vscode/issues/20530
