### ISSUE TITLE
 Issue debugging a .NET core application

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#35446]
- VSCode Version: 1.17
- OS Version: Fedora 26

Steps to Reproduce:

1. Set up dotnet and the C# plugin from [OnmiSharp](https://github.com/OmniSharp/omnisharp-vscode/)
2. Set up a debugging session

I then get this error, which is annoying because I downloaded the plugin directly from OmniSharp, which it looks like the extension tab then replaces it with Microsofts proprietary version of it, which is pretty shady...

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

**Comment by isidorn** [comment]
This is  caused by the C# extension please file it in this repository https://github.com/OmniSharp/omnisharp-vscode
