### ISSUE TITLE
FileSystemProvide API should declare enums starting with 1

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35449]
The type in question is:

```ts
	export enum FileType {
		File = 0,
		Dir = 1,
		Symlink = 2
	}
```

Having 0 as a value only causes problems with default interpretation and the absence of properties. I only use 0 if this is equal to the property no being there.

**Comment by jrieken** [comment]
Yeah, makes sense

**Comment by siegebell** [comment]
It also needs documentation :) -- I wasn't sure whether it was describing bit flags or discrete options until vscode gave me errors for describing a file as a `Symlink` but not allowing `readdir`.

**Comment by jrieken** [comment]
Started on this... @siegebell Do you have a preference? I have some changes in `joh/fs-next` that allow for a bit mask but maybe discrete options are better, e.g

```ts
export enum FileType {
  File = 1,
  Dir = 2,
  Symlink = 64
}
export interface FileStat {
  mtime: number;
  size: number;
  type: FileType;
}
```

or 

```ts
  File = 1,
  Dir = 2,
}
export interface FileStat {
  mtime: number;
  size: number;
  type: FileType;
  isSymlink: boolean;
}
```
