### ISSUE TITLE
Reopen windows bug

### ISSUE THREAD

**Issue by bornastimac** [Microsoft/vscode#35455]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.Use multiple screens of VScode
2.Drag windows around (hit edge of screen to make it maximize or half-screen)
3.Sometimes I get error which states that vscode needs to reopen my window (other opened instances are okay)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bornastimac** [comment]
Sure, let me give it a try

**Comment by bpasero** [comment]
And?

**Comment by bornastimac** [comment]
The same thing happens... I realized it is because I'm using multiple
integrated terminals. Im running node.js server and node.js scripts that
all use networking. When I was reporting the bug, it seemed to me that it
was caused by resizing the window (ie. hitting the edge of the screen), but
now I have it happen more often when I run multiple node.js scripts in
multiple integrated terminals. The terminals are set up to use MINGW64.
If you think I can provide more info, please contact me.
Borna Štimac

**Comment by bpasero** [comment]
@bornastimac so it does not reproduce when you are not using the integrated terminal?

@Tyriar fyi

**Comment by bornastimac** [comment]
Yes I believe it does not. Last few crashes with the build you provided
happened as I pressed Return key to run a node script

**Comment by Tyriar** [comment]
Please update to 1.17, that should fix the issue. Duplicate https://github.com/Microsoft/vscode/issues/34301
