### ISSUE TITLE
VSCode Command Palette issue

### ISSUE THREAD

**Issue by rohitj559** [Microsoft/vscode#35457]
On the Command Palette i type the literal - 'code'. I need to get the below -
![image](https://user-images.githubusercontent.com/13977044/31055647-af75ba48-a6e3-11e7-8ae4-80878daf8d8c.png)

But i get the below -
![image](https://user-images.githubusercontent.com/13977044/31055640-976e1c74-a6e3-11e7-94ea-baac81120499.png)

Please help. What should i do to get the former Palette options?

**Comment by thetrompf** [comment]
The command pallette is contextual, my guess is that aren't in a .NET project? or you simply already have downloaded the debugger for .NET core?

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
