### ISSUE TITLE
[question] how to develop vscode extensions locally with inter dependencies

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#35458]
I'm attempting to develop extensions which have a common dependency.
I use `npm link` to satisfy the dependency locally.

The problem is that I can't package the extension because `vsce` will fail due to `npm` saying there are extraneous modules.  This is due to both modules requiring `vscode`.

The annoying work around is to uninstall the `vscode` from the common module before I package/publish.  But this is an annoying workflow.

Is there a way to make this work properly?

**Comment by joaomoreno** [comment]
Can you show me the log from vsce?

**Comment by dakaraphi** [comment]
@joaomoreno 
`Error: Command failed: npm list --production --parseable --depth=99999
npm ERR! extraneous: vscode@1.1.5 /Users/chadmeadows/development/vscode-extensions/dakaraphi/vscode-extension-space-jumper/node_modules/vscode-extension-common/node_modules/vscode`

`vscode-extension-space-jumper` is the extension I'm attempting to package.
`vscode-extension-common` is the module I've included via npm link

**Comment by joaomoreno** [comment]
Is vscode listed in the `dependencies` object of `vscode-extension-common`?

**Comment by dakaraphi** [comment]
yes

**Comment by joaomoreno** [comment]
As a regular dependency? And the version matches what's on disk? Because that's what `npm` is complaining about.

**Comment by dakaraphi** [comment]
hmm, ok.  So I actually had it listed as `devDependency`.  
So `vsce` does not complain if I move it to `dependency`; however, doesn't my package then unnecessarily include the vscode libraries?

**Comment by joaomoreno** [comment]
Hm `devDependency` should actually work... Interesting.. that might be the issue here.

**Comment by joaomoreno** [comment]
Moved to https://github.com/Microsoft/vscode-vsce/issues/207
