### ISSUE TITLE
Workspace-level key bindings?

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#35450]
I think support should be introduced for a keybindings.json in the project's `.vscode` folder which would override globally-defined key bindings.  This would allow me to remap certain key bindings for a given project and make sure I don't lose them by checking them into source control.

**Comment by sandy081** [comment]
@jez9999 What is the actual purpose of Workspace level keybindings? Do you need them for checking into source control? Or you want to have different keybindings per workspace?

**Comment by jez9999** [comment]
@sandy081 Both really, but mainly for checking into source control.  I don't want to lose the key bindings if I use a different machine.

**Comment by sandy081** [comment]
There is an extension sync that stores it for you - https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-

**Comment by jez9999** [comment]
1) what about per-workspace key bindings?
2) that link is broken.

This should be re-opened.

**Comment by sandy081** [comment]
@jez9999 May I know the usecase behind per-workspace key bindings and how that helps?
