### ISSUE TITLE
Can we choose another method for barce matching?

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#35467]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Brace matching is great but my problem is the way the brace are highlighted with the 2 squares that almost touch when the 2 braces are next to each other, giving me this faux caret illusion....

![image](https://user-images.githubusercontent.com/6321426/31059908-1a6217d2-a6d7-11e7-8eb0-d82bcd01e510.png)

If I take a quick look at the screen while the caret has blinked off, my mind assume this area between the 2 squares is my carret. And that makes for quite a few issues, especially combined with the mouse clicking to place the caret... which places the caret in front of the clicked character instead of whatever side of the character is closes to the mouse. I will report on that separate issue

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
You can customize them to your liking via user settings. e.g.:
```
	"workbench.colorCustomizations": {
		"editorBracketMatch.border": "#00000000",
		"editorBracketMatch.background": "#ff000088"
	},
```

<img width="544" alt="image" src="https://user-images.githubusercontent.com/5047891/31066990-d01e225e-a750-11e7-9f92-eeefb151984b.png">

**Comment by icuurd12b42** [comment]
Thanks! That one was hard to find, it's empty in the defualt

  // Overrides colors from the currently selected color theme.
  "workbench.colorCustomizations": {},

**Comment by icuurd12b42** [comment]
Is there a color value for the character itself?
editorBracketMatch.color

**Comment by alexandrudima** [comment]
No, not at this time.
