### ISSUE TITLE
Have Cmd+R(Mac) and Ctrl+R(Win) reload window by default

### ISSUE THREAD

**Issue by jtlapp** [Microsoft/vscode#35469]
- VSCode Version: 1.16.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Write code that depends on typings or a module that isn't installed yet or isn't yet correct.
2. Install the correct typings or module, and then find yourself struggling to get the Problems panes to update for all the open files (eventually finding multi-step solutions).

Reproduces without extensions: Yes

I originally asked for help with this on SO: [Refreshing errors in VSC after installing typings](https://stackoverflow.com/questions/46461014/refreshing-errors-in-vsc-after-installing-typings)

I eventually found a solution: Map Command+R (on a Mac) or Control+R (on Windows) to `workbench.action.reloadWindow`. Now all I have to do to refresh the errors is to hit the same key combo I would in any browser to refresh the page.

Amazingly, it seems that Command+R and Control+R are not already mapped on Mac and Windows.

SUGGESTION: Add this to the default mappings, in order to make users' lives easier. It'll at least make my life easier by keeping VSC from later mapping this to something else I might also need.

Of course, it's also possible that I went on a wild goose chase and there is another, better way to make life easier. If so, please advise me. Thanks!

**Comment by jtlapp** [comment]
This keyboard mapping also gives users the added benefit of being able to quickly guarantee that they are looking at the latest files, in case they aren't confident that VSC is updating for background edits. It's the same magic feeling that refresh gives us in a browser (ignoring caching).

**Comment by usernamehw** [comment]
1. Keybindings are subjective
2. <kbd>Ctrl</kbd>+<kbd>R</kbd> is already mapped (Open Recent), so that would require 2 default keyboard remappings
3. It's not a browser

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
