### ISSUE TITLE
FileSystemProvider API: should write offer flags to control the behaviour when the file doesn't exist

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#35460]
Usually write API offers such flags.

**Comment by jrieken** [comment]
Yeah, maybe... Currently we handle that in VS Code with a leading stat-call

**Comment by jrieken** [comment]
done in e7e88126adb157ded7936bf385272675484571c2

**Comment by dbaeumer** [comment]
Verified in `vscode.d.ts`
