### ISSUE TITLE
Can we have a better mouse to caret positioning?

### ISSUE THREAD

**Issue by icuurd12b42** [microsoft/vscode#35468]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

I know this convention is half one way, half the other...

For as long as text editors have existed there has been 2 conventions on mouse to caret positioning

One, which is what Code used now, is the annoying clicking anyway on a character places the caret in front of the character (Notepad)

The other, better imho, is if you click on a character, which ever side of the character, the left or the right, the mouse is, that is where the caret will be placed. (Notepad ++, this one seem to place the caret to the front clicking on the left 2/3rd of the character and to the back clicking the right 1/3rd). Which reduces the selection error quite drastically. 

Is there a way to set that up in the settings?

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by hyvyys** [comment]
Any, um, updates on this?? From what I've noticed, current behavior is that clicking left 2/3 of the character positions caret before. Could we make this 1/2? This trips me up and slows me down quite a bit sometimes when my hand is tired.

```
Yeah, I know. True programmers don't use the mouse.
```
