### ISSUE TITLE
Use block comment for every line if line comments are not supported by language

### ISSUE THREAD

**Issue by myskov** [Microsoft/vscode#35464]
There are some languages which don't support line comments: xml, html, ml, maybe more. In case of such languages VSCode uses block comments, when user invokes **editor.action.addCommentLine** or **editor.action.commentLine**.

When I select some code and toggle line comment, I expect this:

![linecomment](https://user-images.githubusercontent.com/2060295/31059140-2bc69cec-a708-11e7-8c96-cb3e738474ec.png)

But, in fact, I got this:

![blockcomment](https://user-images.githubusercontent.com/2060295/31059139-2a863338-a708-11e7-8f99-bc9215678c59.png)

I think it would be better to implement following behaviour: _if line comment is not specified by extension and user invokes line comment command - use block comment for every line_

**Comment by rebornix** [comment]
Thanks for the issue, it's pretty inspiring. We see Line Comment as something you add to any position in the line and the content from that position till the end will be commented out. HTML/XML only have block comments, so we do block comments around selection.

First of all it's a good extension candidate, with which you can run a command to toggle block comments on each line inside the selection. A good feature request as well.

**Comment by Gruntfuggly** [comment]
I wrote an extension to toggle block and line comments dependent on the selection. I've updated it to do block comments on each line as per this issue, as it seemed relevant. Hopefully it does what you need.
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.bettercomment

**Comment by cairinmichie** [comment]
Would it not be easier to have a setting to disable block comments altogether?

**Comment by batisteo** [comment]
Would it be possible in the language-configuration that `lineComment` could accept a CharacterPair as well?

**Comment by egamma** [comment]
Thanks to @Gruntfuggly this is now covered by an extension. Closing the issue.
