### ISSUE TITLE
Request "Vertical Structure Guidlines" Feature

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#35470]
Requesting a feature that VS2017 has. Everywhere seems to call it "Vertical Structure Guidelines." Screenshot shows exactly what this is.

![verticalstructureguidelines](https://user-images.githubusercontent.com/16159685/31060240-056c9a76-a6de-11e7-92d5-f32199f6a223.png)

**Comment by siegebell** [comment]
How is this different than setting `"editor.renderIndentGuides": true`?

**Comment by DanJ210** [comment]
I guess so. It seems that I cannot see them unless I highlight the lines. Is there any way to change their color or visibility?

![editorindentguides](https://user-images.githubusercontent.com/16159685/31402740-e1b8268e-adc4-11e7-99b6-4dd2e86e37bc.png)
