### ISSUE TITLE
Feature Request : support for emmet preference "profile.allowCompactBoolean"

### ISSUE THREAD

**Issue by bbarroux** [Microsoft/vscode#35477]
The support for the preference "profile.allowCompactBoolean" would be super nice : 

Standard behaviour : 
`div[contentEditable.]` expends to `<div contentEditable="contentEditable"></div>`

with `"profile.allowCompactBoolean": true` :
it would expends to `<div contentEditable></div>`
much nicer!

reference : [https://docs.emmet.io/customization/preferences/](https://docs.emmet.io/customization/preferences/)

**Comment by ramya-rao-a** [comment]
In Emmet 2.0 Sergey has moved the profile related setting to "syntaxProfile"

Try setting the below
```
"emmet.syntaxProfles": {
  "html": {
    "compact_bool": true
  }
}
```

**Comment by bbarroux** [comment]
Thanks a lot, works great. 
For future reference, works in .vue files template section as well if you have in your settings : 
`"emmet.includeLanguages": {
        "vue-html":"html",
        "vue": "html"
 }`
