### ISSUE TITLE
100% CPU Utilisation

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#35472]
- VSCode Version: Code - Insiders 1.17.0-insider (caa5656df9e8fa9c556c7eddeb6b4d532814054b, 2017-09-29T05:16:09.696Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
fish|Ted|0.0.4
html-snippets|abu|0.1.0
file-templates|brp|1.2.0
python|don|0.7.0
flow-for-vscode|flo|0.7.1
auto-rename-tag|for|0.0.14
graphql-for-vscode|kum|1.6.2
fish-ide|lun|0.3.0
code-beautifier|mic|1.7.2
vscode-less|mrm|0.6.3
---

Steps to Reproduce:

1. Launch code with existing project.
2. Use normally for a few minutes.
3. CPU usage for code thread gets pegged at 100%

![code cpu issue](https://user-images.githubusercontent.com/2549985/31063837-b9924d0a-a771-11e7-86e0-628253700edd.png)

Reproduces without extensions: No

**Comment by bsvipas** [comment]
Hi, this happens if you project contains a lot of files, normally you need to exclude `node_modules`, `bower_components`, `tmp` and so on. I think you get the idea, you need to exclude temporary/build dirs, etc.

Try to use `"files.useExperimentalFileWatcher": true` and add exclude to `files.watcherExclude` and `search.exclude`.

**Comment by Panoplos** [comment]
OK, but this issue seems to have only popped up since updating some of the packages in my project. In other words, even with the same number of files, I was not seeing this phenomenon before. Is there a way to pinpoint which extension is the offending one, because `htop` is not showing that any of the actual extensions are the culprit. Additionally, when I disable extensions, the issue does not occur, as pointed out in the report.

**Comment by Panoplos** [comment]
Additionally, I have tried to disable the `flow-for-vscode` and `graphql-for-vscode` extensions, but the phenomenon still occurs.

**Comment by bsvipas** [comment]
@Panoplos try to Toggle Develop Tools and see console output. If nothing here best solution I think is to try to disable one by one extensions to see which one it is. And if you said this is extension fault, do not use my settings.

If you're installed `flow` and you're using it with VS Code extension it's really memory/CPU consumer, especially for big projects. It also scans your `node_modules` so sometimes you can feel 100% CPU while it's scanning.

**Comment by Panoplos** [comment]
Again, I didn't have this issue before updating some packages in my project. If I revert the packages to previous versions, the problem is gone, but this is not a solution.

`fish-ide` is a bit of a misnomer, IMO.

**Comment by BillDenton** [comment]
This sounds like the same problem as https://github.com/Microsoft/vscode/issues/35475.

**Comment by jrieken** [comment]
>  If I revert the packages to previous versions, the problem is gone, but this is not a solution.

What packages? Can you pin point this to a certain extension? From https://github.com/Microsoft/vscode/issues/35472#issue-261980092 it looks like the extension host, the process in which all extensions run, goes crazy. I'll be good to know what extension is causing this

**Comment by BillDenton** [comment]
I've disabled all my extensions and am slowly bringing them back in as I need them. So far I have only brought in [MS C/C++ for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). I'll try to update once I have re-enabled more extensions.

**Comment by jrieken** [comment]
Ok, good progress. You can also try to profile the extension host. That should quickly reveal what extension is going mad: Do the following:

* Start VS Code from the command line the with --inspect-extensions=<port>-flag, for example code --inspect-extensions=9333.
* In VS Code, from the Command Palette (F1), select Developer: Toggle Developer Tools, hit Enter.
* Select the Console tab and find a message that starts with "Debugger listening on port 9333" and that ends with a chrome-devtools-link.
* Open that link in Chrome for dedicated DevTools for the extension host.
* Use the CPU profiler, record CPU activity for a few seconds (~10), and attach the profile here

Thanks

**Comment by Panoplos** [comment]
Here is the cpuprofile file from when this happens.
![screenshot_20171003_130802](https://user-images.githubusercontent.com/2549985/31109599-f66e3296-a83b-11e7-93d2-cb5fdcddc2f2.png)

I do not see anything about a specific extension. :^(

**Comment by jrieken** [comment]
Yeah, looks like some excessive regular expression execution happens... Maybe point the extension author to this issue.

**Comment by BillDenton** [comment]
I'm not using the <code>auto-rename-tag</code> extension. By disabling all the extension and only re-enabling each one as I need it, I have made the editor usable again. For me, it appears to be a problem with  <code>vscode-spell-checker</code> (see https://github.com/Jason-Rev/vscode-spell-checker/issues/77). I've not investigated further as I've got work to do.

**Comment by BillDenton** [comment]
I've tried profiling and attached the results to https://github.com/Jason-Rev/vscode-spell-checker/issues/77. I can't see anything obvious.

**Comment by BillDenton** [comment]
For me the problem is now fixed by update to [vscode-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). From that the problem appears to be in VS Code. From https://github.com/Jason-Rev/vscode-spell-checker/issues/77#issuecomment-333944351: 
"The problem is related to the code that searches for the configuration files. The extension calls a VSCode function to find the files. Apparently, this function is VERY expensive."

**Comment by jrieken** [comment]
Thanks. I will followup on Jason-Rev/vscode-spell-checker#77 (comment):
