### ISSUE TITLE
yum update error

### ISSUE THREAD

**Issue by yokall** [Microsoft/vscode#35479]
I have been trying to update Code 1.16.0 from the yum repo for a few days now.  Everytime it tries it says "No Presto metadata available for code", starts the download which is very slow sometimes even though all other network activity is fine and then errors with "https://packages.microsoft.com/yumrepos/vscode/code-1.16.1-1505406659.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=code clean metadata".

I have tried cleaning the repo as suggested but the result is always the same.  I can just uninstall and grab the rpm itself but I do like the ability to just update from yum, it has been very slick until now.

I am on Centos 7 64 bit.

If you need any firther info just ask.

Thanks

Colin

**Comment by Tyriar** [comment]
Strange, I will pass it on to the team that hosts the repo.

**Comment by szarkos** [comment]
According to https://access.redhat.com/solutions/3141231 the presto message is ignorable.  The presto metadata is related to support for delta RPMs, which is optional.

Are you behind a proxy?  Besides running 'yum clean all' and the like, another suggestion is to add "http_caching=packages" to yum.conf and see if that helps at all.

**Comment by yokall** [comment]
Yes I'm behind a proxy.  yum is working fine for other packages.

I tried the "http_caching" suggestion but it failed the same way.
