### ISSUE TITLE
Refresh local branch?

### ISSUE THREAD

**Issue by jk-jx** [Microsoft/vscode#35471]
Can someone help me with this issue? 
VS Code: v1.16.1
I have an issue about the local branch. I have using VS Code for months. In this few month I have open a few branch on my local and I have push the commit to my server. But I have found out that the list havent been updated. But my branch had been delete on my server. So does anyone know how to refresh the list so that my VS Code branch list are same with my remote branch list.

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/16408300/what-are-the-differences-between-local-branch-local-tracking-branch-remote-bra
