### ISSUE TITLE
Link clicking doesn't work in Terminal, in mouse mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35484]
When I hit <kbd>Ctrl MouseClick</kbd> the view just appears to scroll up a bit. Weird.

![peek 2017-10-02 11-25](https://user-images.githubusercontent.com/22350/31071497-7eea691a-a764-11e7-9398-aabf769055f1.gif)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/1020
