### ISSUE TITLE
setFunctionBreakpoints request is coming in after launch request

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#3548]
I seem to be getting setFunctionBreakpoints requests after the launch request whereas setBreakpoints requests come in before the launch request.  Should I be using the configurationDone request or something here?  BTW the extension is configured to send the initialized event in the processing of the initialize request but before the initialize response is sent. Could that be causing this?

**Comment by rkeithhill** [comment]
I think I have a workaround here where we stash the launch parameter info and defer launching of the requested script until we receive the configurationDone request message.  Is this how the protocol is supposed to work?

**Comment by weinand** [comment]
@rkeithhill yes, the `configurationDone` request is called after all configurations are done (that means after setFunctionBreakpoints). 

@isidorn is there are guarantee that `launchRequest` is always called after the `configurationDone`?

**Comment by isidorn** [comment]
@weinand no there is no guarantee. 
`launchRequest` is guaranteed to be called after I get a response from an `initializeRequest`.
`configurationDone` is guaranteed to be called at the end of all the configuration which is started when an `initialized` event is received. Since VSCode does not control when it receives the `initialized` event from the adapter, VSCode can not guarantee that launch is always called after configuration done.

**Comment by rkeithhill** [comment]
@isidorn Do I have this about right - excuse my incorrect use of sync calls below but this message order is what I see in our extension's log file and it reflects "when" we send the `initialized` event:

![vscodedebugprotocolseq](https://cloud.githubusercontent.com/assets/5177512/13442034/9d54600c-dfb7-11e5-8225-20a8264c8717.png)

NOTE: in the log file I examined the debug scenario had no line breakpoints configured.  If I look at a log file that does have a line breakpoint configured, the `setBreakpoints` request/response is in the same spot as `setFunctionBreakpoints` is in the diagram and the `setFunctionBreakpoints` request/response has shifted down to the same spot as `setExceptionBreakpoints`.

So right now, we see `configurationDone` arrive after the `launch` request msg and we've shifted code to configurationDone that **requires** that we received the `launch` request already as it contains launch parameters.  

My worry is that when the issue with the `setExceptionBreakpoints` request message is fixed i.e. we will no longer get that message because we don't support that feature and the order of `launch` and `configurationDone` request messages could change due to the async processing nature of dbg protocol messages.  Is that correct?  If so, I can guard against this but I didn't want to "complicate" the code if the scenario of `launch` received after `configurationDone` is not possible give that we send the `initialized` before we send the `initialize` response.  Thanks.

cc @daviwil

**Comment by weinand** [comment]
@rkeithhill thanks for the diagram. I have not yet analysed it in detail but here is just a piece of information that might be helpful:

If you return `supportsConfigurationDoneRequest = true` in the `InitializeRequest`, VS Code will call `configurationDoneRequest` right after the (now optional) `setExceptionBreakpointRequest`. So if you are not interested in implementing the `setExceptionBreakpointRequest`, just ignore it but implement the `configurationDoneRequest` instead. So `configurationDoneRequest` is basically the official replacement for the `setExceptionBreakpointRequest` if you do not have to set any exception breakpoints at all but just need a reliable request after all configuration has been done. There should be no timing difference between `setExceptionBreakpointRequest` and `configurationDoneRequest`.

**Comment by rkeithhill** [comment]
I've updated our code to handle receiving the `configurationDone` and `launch` requests in non-deterministic order.  That said, I agree with this:

> We might want to consider to call  launchRequest  (or  attachRequest ) only after receiving the response from the  configurationDoneRequest  

but I worry it could break existing debug extensions.

**Comment by jinmingjian** [comment]
> We might want to consider to call launchRequest (or attachRequest) only after receiving the response from the configurationDoneRequest (or the setExceptionBreakpointRequest for old clients). This would ensure that no configuration requests occur after the launchRequest.

this mandatory is unwanted sometimes. For example, my debugger adapter will delegate to its background real debugger. So it needs launchRequest done before configurationDoneRequest. OK, now this order is also not supported. 

However, @isidorn 's current two-thread invocation solution leaves the flexibility to the clients. We can use Promises, callbacks or anything else to order the sequence of which you like. But if the order is forced in the logic, some clients really becomes unhappy.

So, I suggest that this case be more *designed* rather than flawed.
