### ISSUE TITLE
Some hotkeys are displayed incorrectly in the main menu

### ISSUE THREAD

**Issue by impworks** [Microsoft/vscode#35481]
- VSCode Version: 1.16.1
- OS Version: Windows 10 v1703

Steps to Reproduce:

1. Open the editor
2. Open main menu

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/604496/31069263-6360f42a-a764-11e7-8081-5d919bd6f1c9.png)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by impworks** [comment]
Sorry. I did use the search - the `hotkey` query does not show anything.
