### ISSUE TITLE
Git: Hide untracked files

### ISSUE THREAD

**Issue by eladcandroid** [microsoft/vscode#35480]
- VSCode Version: 1.16.1
- OS Version: Windows 10

I'm talking about hide untracked files from here, or put them in other group..
![whatsapp image 2017-10-02 at 10 47 10 am](https://user-images.githubusercontent.com/13297000/31068540-1fcfde4a-a761-11e7-859b-7b049810d7cf.jpeg)

The same situation in some IDE (You know the name..)
![whatsapp image 2017-10-02 at 10 47 55 am](https://user-images.githubusercontent.com/13297000/31068612-73caab06-a761-11e7-998f-247e3eabaf09.jpeg)

**Comment by Diom** [comment]
I agree that this would be a nice improvement. It makes sense that currently tracked files at least would sort to the top with untracked below. That would be enough for me at least.

**Comment by Dari-K** [comment]
This was annoying me a bit as well, you can remove the path sorting pretty easily until (or if) this get gets fixed:
```diff --git a/src/vs/workbench/api/node/extHostSCM.ts b/src/vs/workbench/api/node/extHostSCM.ts
index 7ffe2da782..8313c66377 100644
--- a/src/vs/workbench/api/node/extHostSCM.ts
+++ b/src/vs/workbench/api/node/extHostSCM.ts
@@ -91,11 +91,7 @@ function compareResourceStatesDecorations(a: vscode.SourceControlResourceDecorat
 }

 function compareResourceStates(a: vscode.SourceControlResourceState, b: vscode.SourceControlResourceState): number {
-       let result = comparePaths(a.resourceUri.fsPath, b.resourceUri.fsPath);
-
-       if (result !== 0) {
-               return result;
-       }
+       let result = 0;

        if (a.decorations && b.decorations) {
                result = compareResourceStatesDecorations(a.decorations, b.decorations);```

**Comment by jkmacc-LANL** [comment]
👍

**Comment by laoshaw** [comment]
for git I set up .gitignore and the U (untracked) sign in vscode disappears.

**Comment by Diom** [comment]
@Dari-K Would you submit a Pull Request with that change? I can implement that on my home computer but my workplace is not so open.

**Comment by shauntck** [comment]
this would definitely be helpful fix!

**Comment by Diom** [comment]
@laoshaw you obviously do not generate any code then 😄 
.gitignore can only get me so far. We produce cql files as part of the build too, and often MD files are part of the output of automation scripts.

**Comment by MaddyDahiya** [comment]
"git.decorations.enabled": false - Removed "Untracked" status against any file.

**Comment by lukka** [comment]
@MaddyDahiya that did not help. It just removes the graphics decoration around the status icon, i.e.:
![image](https://user-images.githubusercontent.com/681992/45657638-1682ba80-baa0-11e8-9010-43051958d78e.png) vs 
![image](https://user-images.githubusercontent.com/681992/45657663-29958a80-baa0-11e8-974f-d500dbf5b788.png)

**Comment by joaomoreno** [comment]
If we omit the untracked files, what would you expect would happen if the user presses `Stage All Changes`? Should the _invisible_ untracked files be staged?

**Comment by Dari-K** [comment]
@joaomoreno I don't think the untracked files necessarily need to be hidden, would be nice if they were in separate sections like in the picture the issue creator posted. Tracked vs untracked with tracked on top.

**Comment by cogentParadigm** [comment]
I agree. I would like to see them in a separate section, as you would see them if you ran `git status` from the terminal.

I would also like to see untracked files collapsed to the level of granularity that is untracked. If an entire directory is untracked, it would be great if I only saw the directory in the same way git displays it from the terminal.

**Comment by boochamoocha** [comment]
Want to create repo and add just one file from legacy codebase and expect vscode chow me just 1 file in changes list after `git init; git add somefile`. 
But vscode shows me 5k files in changes list. It is very inconveniently.

**Comment by alexandrebastien** [comment]
Hi I agree with @boochamoocha. I have set a virtualenv with 4k files and they are all listed in changes, even if I put my env folder in .gitignore . This is very annoying. How would you guys works with virtualenv, git and vscode ? I'm very new to all of this.

**Comment by barezina-intellipharm** [comment]
This feature would be great - at the moment vscode's ability to surgically stage files becomes mostly unusable in legacy projects if the project dynamically creates files when being run - it essentially forces devs to use the git command line in these instances.

**Comment by alexandrebastien** [comment]
Maybe just something to show files in a collapsible tree would be a quick fix.

**Comment by lehoanganh298** [comment]
> git has its own [setting](https://git-scm.com/docs/git-config#git-config-statusshowUntrackedFiles) to control behavior with respect to untracked files. When it is set to no in ~/.gitconfig or .git/config, vscode should respect it. That means no file which is untracked should show up in the changed list, and commit all should not commit such files.

I did what you said but it doesn't work, git status not show untracked files but vscode still show and count a bunch of untracked files.

**Comment by aperomsik** [comment]
Sorry @lehoanganh298 -- I did not mean to imply that it _does_ work that way, only to suggest that it _should be fixed_ to work that way.

**Comment by kousu** [comment]
I just tried whast @aperomsik suggested, adding

```
*.o
*.pyc
```

to my project .gitignore and VSCode seems to respect it.

**Comment by aperomsik** [comment]
@kousu if that works for you, great, but it's not what I suggested. The point of the settings I mentioned is to remove the need to mess with .gitignore.

**Comment by Mochnant** [comment]
I'd like to see them in a separate group and also not incrementing the git decorator changes count.

**Comment by cdeline** [comment]
As an anonymous user and complete newbie to vscode, I can provide the following feedback.  I was really un-nerved when I opened vscode for the first time, and found over 200 'changes' to my repo, which were really just un-tracked files.  The only two options at the top of the 'git' tab are to 'Discard all changes' (i.e. DELETE all of my local files, which is a huge issue pissing a lot of people off - do a search for 'vscode deleted all my files' to get a sense for it) and 'stage all changes'.  Well, I don't want to do either.  I want vscode to IGNORE all these untracked local files.  Why isn't that the default option???  or an option at all?  Even just a way to update .gitignore through vsc would be ok.  Thank you!

**Comment by forivall** [comment]
If there are many untracked changes under a folder, i'd like to see that automatically collapsed under one entry. For example, in the CLI, it looks like this, 
![Screen Shot 2019-03-15 at 2 23 54 PM](https://user-images.githubusercontent.com/760204/54462746-0b96a300-472e-11e9-8757-d7891536cc36.png)
But in vscode, it shows an entry for every file.
![Screen Shot 2019-03-15 at 2 25 20 PM](https://user-images.githubusercontent.com/760204/54462836-4d274e00-472e-11e9-8e29-c0432f56d176.png)

**Comment by johnrix** [comment]
This one issue essentially prevents me from using the Source Control tab of VSCode. I work with a Joomla site and do not check in any of the Joomla core files into my GIT repo. VSCode consistently tells me I have over 5000 changed files. Not helpful.

Consequently, I use SourceTree instead. I'd love to have one less tool to rely on though.

**Comment by sillvva** [comment]
Agree with johnrix. My project shows 184 changes, but only about 2% of those are modified.

**Comment by parmentelat** [comment]
same here; +1 for having an option to ignore untracked files - and ideally for it to be the default

**Comment by eladcandroid** [comment]
@joaomoreno Can you please push it up, with @Dari-K suggestion?

**Comment by cipri-tom** [comment]
@eladcandroid maybe the team is reluctant to hide untracked, because then how would you add a new file to the repo? So would it be a good idea to adapt a bit the name to 'hide/separate untracked files'? Because the separation is also a solution, though they are not hidden.

**Comment by parmentelat** [comment]
IMHO, having the files grouped into collapsible sections, last of them being 'untracked' - that I for one would have collapsed like 99.99% of the time - would already be huge improvement towards unclobbering the display

I don't care having to add new files by other means like the command line, sourcetree, or whatever other tool  
It's not as if the vscode extension was supporting 100% of the daily needs anyway; don't get me wrong, it is really cool to have it do what it currently does as a basic toolset - esp. for teaching btw  !

**Comment by yfdyh000** [comment]
I think grouped and folding is a good choice, but it should be hidden ("+ more") if more than 50 or 100 files, and provide a button to expand (not recommended) or pop up a window (possibly increased development costs) to filter, select and manipulate files.

**Comment by ztlpn** [comment]
+1 It would be very helpful for us recovering CLI users if VSCode would just mimic the way ordinary git commands work, i.e. `git status` shows staged, unstaged and untracked files separately. Possible improvements: support an analog of `git status -uno` (don't show untracked files); support `git add -u` (stage changes to the tracked files only).

**Comment by aniongithub** [comment]
Same here, :+1: for the collapsible sections idea. It's already used for a variety of other groupings in Visual Studio!

**Comment by rajkundu** [comment]
+1.This would be very helpful to all.

**Comment by madkinsz** [comment]
+1 !

**Comment by ArrrNeo** [comment]
+1

**Comment by nonarkitten** [comment]
Not sure if it was mentioned -- Visual Studio Code **DOES** honour the .gitignore file, so feel free to add untracked files there to clean up the source control view. Of filter out a whole folder, and put all untracked files there.

**Comment by bonfire62** [comment]
@nonarkitten not sure about others, but I need the functionality outside of the gitignore, as the gitignore for my repo is tracked and I can't modify it.

**Comment by nonarkitten** [comment]
@bonfire62  Create a folder. Put everything untracked in there. Add a new .gitignore in there and have it ignore everything. Git will automatically never include empty folders.

**Comment by aperomsik** [comment]
@nonarkitten The whole reason I set status.showuntrackedfiles to no in .gitconfig was to avoid the need to mess with gitignore.

**Comment by bonfire62** [comment]
@nonarkitten That wouldn't work in my case, because a lot of the content I need to hide as untracked is generated at compile time

**Comment by jjnurminen** [comment]
I'm +1 on this. Command line `git status` shows unstaged files first, so I can see changes easily. VSCode on the other hand combines unstaged and untracked files in a single list, which is too long to be useful.

I don't know about others, but at least in my project directory, untracked files come and go. Adding every single one of them to .gitignore is not a workable solution.

**Comment by johnrix** [comment]
For me, the .gitignore approach is helpful as far as being able to ignore entire folders that are not tracked and it brings the change list down to a somewhat more manageable size, but its not a complete solution for many of the reasons expressed above.

**Comment by joaomoreno** [comment]
Everybody, give it up for @Jakobeha. His PR just landed in master.

A new setting `Git: Untracked Changes` allows you to separate or hide away untracked changes. Give it a spin next monday on Insiders!

**Comment by johnrix** [comment]
Looks like options there to suit most needs from what I can see. Nice work @Jakobeha!

**Comment by eladcandroid** [comment]
@Jakobeha @joaomoreno 
Just saw that on VSCode 1.40! Thank you so much! You rock! 🎸😎

**Comment by jbaileyashe** [comment]
Fantastic! Inspired me to install Insiders!

**Comment by onoffpt** [comment]
Simply fantastic. Thanks.

**Comment by johnrix** [comment]
Been using the git integration a good bit of late, thanks to this update. :-)
