### ISSUE TITLE
Renaming a symbol in a file shared by two projects only affects the files in one

### ISSUE THREAD

**Issue by nahuel** [Microsoft/vscode#35488]
If you open two typescript projects sharing a common file with a symlink, and then do a "Rename Symbol" in the shared file, ONLY the files in the project were you did the operation  will be affected by the rename, rendering the other project files inconsistent. Steps to reproduce:

1- Create `/tmp/a` and `/tmp/b` projects and `/tmp/c` shared directory

```
cd /tmp ; mkdir a b c
cd a ; npm init ; tsc --init
ln -s ../c c
cd ..
cd b ; npm init ; tsc --init
ln -s ../c c
```

2- Create files:

```ts
/* /tmp/c/fc.ts */
export const C = 8

/* /tmp/a/a.ts */
import {C} from "./c/fc"
console.log(C)

/* /tmp/b/b.ts */
import {C} from "./c/fc"
console.log(C)
```

3- Now open both folders `a` and `b` in VS Code, then open `a/c/fc.ts` and do a "Rename symbol" on `C`. Only the files at the `a` folder will be affected. In the `b` project `fc.ts` will remain unchanged until you save it in the `a` project, then it will show the changes but it will not notice is a symbol change, so the `b` files will not be updated with the new symbol.

- VSCode Version: 1.16.1 27492b6bf3acb0775d82d2f87b25a93490673c6d
- OS Version: Ubuntu 17.04

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20021
