### ISSUE TITLE
ExtensionContext.globalState strangeness

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#35487]
I'm seeing a very strange issue with a couple of GitLens users (I have one user with the issue right now and we have tried to debug it). What looks like is happening is that the `globalState` that I set in GitLens is somehow being either cleared or set to a previous value on every restart of vscode.

For example, I use `context.globalState.get<string>('gitlensVersion')` to detect upgrades which I log to the output channel. In this user's case,  when it gets logged out it seems to have a value of `5.1.1-beta`, but when we look in the local storage -- that global gitlens key has a value of `5.3.0`, and if we restart vscode, we see exactly the same thing, it gets read/logged as `5.1.1-beta`, but we see it as `5.3.0` in local storage. We've pulled down the gitlens repo and tried to catch this in the debugger, but when in the debugger we never see the wrong value -- it always gets correctly read as `5.3.0`. I will also say if other keys get written to the same `globalState` -- we can see them properly in the local storage, but once we restart vscode they all disappear.

FYI, this user did have the marketplace version of GitLens installed on top of a previous beta vsix, but we removed all the versions and re-installed GitLens from scratch and still the behavior persists.

This users was on Linux, but I've had another case of almost the same behavior on macOS (https://github.com/eamodio/vscode-gitlens/issues/130)

**Comment by joaomoreno** [comment]
cc @isidorn @bpasero @jrieken @sandy081 

Not sure who owns this; just unassign yourselves if I got it wrong.

**Comment by jrieken** [comment]
The API is more or less just using the [`storageService`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadStorage.ts#L28) which makes we thing it's at a lower level

**Comment by jrieken** [comment]
> unless we do some migration?

That actually rings a bell... @bpasero Isn't there something with multi root and this? And iff so does this happen before starting the extension host or while it's already up?

**Comment by eamodio** [comment]
FYI, in case it helps -- this user @bcanzanella (a friend and co-worker of mine) can still reproduce this issue if you'd like any further details etc.

**Comment by jrieken** [comment]
@bcanzanella are you using a multi-root setup?

**Comment by bcanzanella** [comment]
@jrieken nope, no multi root. single folder/project.

**Comment by bpasero** [comment]
@eamodio to clarify you are not accessing workspace storage right only global storage? Asking because we only do some stuff with workspace storage.

With the explanation it is not clear what could go wrong, if you can find steps in a standalone extension (simple hello world extension) that would be great 👍

**Comment by eamodio** [comment]
I do use both (for different settings), but I've only heard/seen these issues with the global ones.

Yeah, its totally baffling -- it really looks like somehow on shutdown (or pre-extension) startup the global key gets reset to some original state. But if the key gets written/read during a session it works just fine. We even tried just nuking the local storage key completely (using the devtools) but it didn't change anything.

**Comment by bpasero** [comment]
@eamodio at the time your extension calls into the storage service can you verify that the change ends up in local storage?

**Comment by eamodio** [comment]
After the call to set the value, yes -- the correct change is written and is read correctly. Although I can only tell this from the logs, because this behavior is not reproducible while debugging GitLens.

**Comment by bpasero** [comment]
@eamodio could it be that the machines where this happen do not gracefully shutdown? local storage gets only synced back by Chrome to disk on shutdown, not while writing. We have [extra code](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/update/electron-main/updateService.ts#L277) to trigger the flush when an update is applied because we always lost our local storage otherwise.

**Comment by eamodio** [comment]
Graceful shutdown of vscode? If so, I don't think so. When we watch it happen (which it still is 100% reproducible on @bcanzanella's machine), we start up vscode and GitLens will log out the wrong local storage value, save the new version (which is verifiable in the devtools) and could also save other settings into that global key (also verified in the devtools). Then close vscode via the `Exit` menu choice, and restart it and see the exact same thing play out again (like groundhog day).

Although if we attempt to repro this via the debugger it never is wrong. I'm not sure how (or even if it is possible) to attach to the extension host before it loads.

**Comment by bcanzanella** [comment]
I upgraded to GitLens 5.4.0 from the marketplace, and I still have the issue. The strange thing is from this bit of the log:

```
GitLens(v5.4.0) active: undefined
Git found: 2.14.2 @ /usr/bin/git
Git version: 2.14.2
GitLens upgraded from v5.1.1-beta to v5.4.0
ShowMessage(info, 'GitLens has been updated to v5.4.0', suppressUpdateNotice, Don't Show Again)
CodeLens config changed; resetting CodeLens provider
Git cache changed; resetting CodeLens provider
Triggering a reset of the git CodeLens provider
Git cache changed; resetting current line annotations
```

VS Code thinks I went from v5.1.1-beta to v5.4.0, but in reality I went from v5.3.0 to v5.4.0 (I had previously installed v5.1.1-beta from a VSIX file). ~/.vscode/extensions/ only has `eamodio.gitlens-5.4.0` in there.
