### ISSUE TITLE
IntelliSense fails for absolute import paths

### ISSUE THREAD

**Issue by grokky1** [Microsoft/vscode#35489]
- VSCode Version: 1.16.0
- OS Version: Win10 x64

Steps to Reproduce:

1. import module: `let Customer = require.main.require("./src/Models/Customer");`
2. use it: `let customer = new Customer();`

This syntax imports modules from the app's root, which avoids the problem of crazy paths like `"../../../../foo/bar/baz/Customer"`. But there is no intellisense for anything in the `Customer` module.

I've tried importing it directly as above, and also via a directory `index.js` file. Neither approach works.

I found this [related issue](https://github.com/Microsoft/vscode/issues/19342) which said I should have a `jsonconfig.json` with `"module": "es6"` and `"target": "ES6"`, but that doesn't help.

**Comment by mjbvz** [comment]
What does your project look like? Can you share minimal sample project?

Also, please try enabling [`tscheck`](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) in your code. This can help track down why a module is not being resolved properly

**Comment by grokky1** [comment]
@mjbvz Very simple repro:

**Contents of file `./exporter/exporter.js`**
````javascript
module.exports.foo = "foo";
````

**Contents of file `./importer/importer.js`**
````javascript
const exporter = require.main.require("./exporter/exporter.js");

module.exports.run = function () {
  console.log(exporter.foo);
};
````

**Contents of file `./app.js`**
````javascript
const importer = require.main.require("./importer/importer.js");

importer.run();
````

Then run app using `node app`. Although this prints "foo" as expected, I don't get intellisense.

However when I change `require.main.require("./exporter/exporter.js");` to `require("../exporter/exporter.js");` then I do get intellisense.

Like I said above, the `require.main.require()` call does not seem to work with intellisense. And this is the widely used alternative to crazy paths like `../../../../foo/bar/baz.js`.

(When I used `tscheck` as you recommended, it told me that it couldn't find "require" and "module". Strange...)

**Comment by mjbvz** [comment]
Thanks. Yes it looks like we don't support `require.main.require` style imports. 

Opened https://github.com/Microsoft/TypeScript/issues/19117 to track this upstream
