### ISSUE TITLE
Failed to save 'httpd-vhosts.conf': A system error occurred (EACCES: permission denied, open '/private/etc/apache2/extra/httpd-vhosts.conf')

### ISSUE THREAD

**Issue by ptbobolakis** [Microsoft/vscode#35482]
- VSCode Version: Version 1.14.2 (1.14.2)
- OS Version: 10.12.5 (macOS)

Steps to Reproduce:

1. Enter `sudo code /etc/apache2/extra/httpd-vhosts.conf` in Terminal
2. Add a virtual host
3. Try to save it

Reproduces without extensions: Yes

Just like in Atom, I'd like to be able to enter my admin password to elevate my role to be able to write to the file.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
