### ISSUE TITLE
$tsc problemmatcher fails with long output lines in terminal window

### ISSUE THREAD

**Issue by eramitmittal** [Microsoft/vscode#35483]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
jenkins-status|ale|0.4.0
githistory|don|0.2.3
vscode-generate-getter-setter|DSK|0.4.2
gitlens|eam|5.4.0
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.16
status-bar-tasks|Gua|0.2.1
vscode-firefox-debug|hbe|0.16.0
debugger-for-phantomjs|ira|0.1.1
docthis|joe|0.4.8
typelens|kis|1.5.0
debugger-for-chrome|msj|3.3.1
vscode-docker|Pet|0.0.18
java|red|0.10.0
html-less-class-completion|wan|0.0.6

---

Steps to Reproduce:

1. Create a dummy task in gruntFile.js to print a long string in the format for some valid typescript error
2. Configure this dummy grunt task as your build task with problem-matcher $tsc
3. 'Build' your project (thus causing the dummy grunt task to run and use integrated terminal window)
4. Notice that for long line outputs, integrated terminal splits it into multiple lines (even when actual output is single line)
5. The $tsc problem matcher treats each line as independent and hence fails to properly report the error in problems tab

Reproduces without extensions: Yes/No Yes

![image](https://user-images.githubusercontent.com/6870404/31071040-37a0e14e-a780-11e7-8186-1433f5192f8b.png)
![image](https://user-images.githubusercontent.com/6870404/31071059-4595604a-a780-11e7-8039-1bdf9d4f0550.png)

**Comment by dbaeumer** [comment]
Dups 32042
