### ISSUE TITLE
clean up icon path confusion

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35491]
With https://github.com/Microsoft/vscode/commit/269ae60a4b7f0afb4d779433d88d9c1ef2190bc6 the concept of an `iconPath` has been added. This competes with `iconClass` and having both doesn't make much sense. While I understand the reasoning for us having it `iconPath` is only honoured in a single place and every other user will fail to make it work. At least the `MenuItemActionItem` should know what to do, ideally no competing concepts exist.

**Comment by bpasero** [comment]
Yes a bit ugly. One issue is that an extension today can contribute an icon as a path for an command and we expand that a) into an `iconClass` and b) into an `iconPath`. I think we could possible go away from `iconClass` and keep `iconPath`, though then we have to somehow keep the semantic of different icons per theme and switch accordingly. The beauty of CSS is that you do not have to care about our 3 base themes.

Alternatively, it would be relatively easy to support `iconPath` in `MenuItemActionItem` alone by just setting the `background-image` if we do not have a CSS class defined otherwise.

**Comment by jrieken** [comment]
>  One issue is that an extension today can contribute an icon as a path for an command and we expand that a) into an iconClass and b) into an iconPath.

Well, the original design was *only* has `iconClass` which abstracts away the fact that extensions can provide one or two icons for the dark and light theme. And "yes" this also makes theme switching nice. Now, the bad `iconPath` has appeared which breaks the "information-hiding" and it also prefers the dark-variant of an icon. So, I don't think the `iconPath` can be supported in `MenuItemActionItem` with ease. What's needed is to carry along the *full* icon information and delay the CSS creation

**Comment by jrieken** [comment]
Ping... now that this get wider adoption this mess should really disappear.

**Comment by bpasero** [comment]
@jrieken how about removing `iconClass` altogether and having the concept of a `iconPath: string | { dark: string, light: string }` in `ICommandAction`?

It seems to me, the only place where `iconClass` is actually being used is in [`MenuItemAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L183). Why not move the [code that creates dynamic CSS](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/electron-browser/menusExtensionPoint.ts#L296) rules into there?

**Comment by bpasero** [comment]
Hm, maybe not a good idea as there are `MenuItemActions` for the touch bar that use `iconPath` but do not require any CSS class. We could try to move this into `MenuItemActionItem` though which is the thing that is actually used for our toolbars and actionbars.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/commit/525eb58e6117646962f04ef1ae2d531affdd59b8 exercises the idea of getting rid of `iconClass`. It is still at the wrong layer though (`MenuItemAction`).

**Comment by jrieken** [comment]
Yeah, something along those lines. The `ICommandAction` is still just a model type and I think it's good to contain the information in there. Not sure if we should set the class-property in the `MenuItemAction`... For once it might leak css styles and then it's just glue code to fit into the existing actions story (which we should finally get rid of). The better place would be `MenuItemActionItem` is about rendering (UI) of a menu item. Tho I am unsure if there are other places in which we render MenuItemAction
