### ISSUE TITLE
SCM: list of repositories randomly looses entries after reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35497]
Steps to Reproduce (I use multi root setup):

1. reload window
2. click on a change

=> some repositories hide

![panel-red](https://user-images.githubusercontent.com/900690/31091466-62df82b8-a7ab-11e7-879c-d5475a7cb29f.gif)

**Comment by joaomoreno** [comment]
Great catch!

**Comment by joaomoreno** [comment]
Commit cherry-picked to `release/1.17`
