### ISSUE TITLE
End of line issue VS -10 git command line  

### ISSUE THREAD

**Issue by Vivekdude** [Microsoft/vscode#35493]
Hi Team , 
I am facing eol issue with my commit ,
I am using visual studio 10 and git command line . 
i have set git config --global core.safecrlf true ,
that supposed to fix this issue , but still having a lot of problem , 
Is there any way to fix this . 
it regularly creating problem while making pull request , 
it casting me a lot of issue , could get some help to fix this . thanks in advance

**Comment by joaomoreno** [comment]
This is the VS Code project. You might want to file an issue with Visual Studio.
