### ISSUE TITLE
debt - replace ExplorerViewerActionContributor with menu-registration

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35490]
There is a lot of [code to register](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/search.contribution.ts#L169) the "find in folder" action. Since a while we have `MenuId`s and menu registrations based on that. Find a sample in every caller of `MenuRegistry.appendMenuItem` like [this one](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/codeEditor/electron-browser/toggleWordWrap.ts#L253). The context key you are looking for is `explorerResourceIsFolder` to know if you are on a folder and `resource` to get the active resource

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/24900

**Comment by bpasero** [comment]
This is done via #24900
