### ISSUE TITLE
Mac OS X :: 0.10.9 :: Regular Expression Replace / Substitution

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3549]
I'm trying to perform a very basic regex substitution in VS Code 0.10.9 on Mac OS X. However, it only substitutes `$0` with the string literal `$0`. How can I substitute captures in the regex replacement string?

<img width="424" alt="screen shot 2016-02-28 at 9 52 05 pm" src="https://cloud.githubusercontent.com/assets/466713/13386082/9d559498-de65-11e5-9953-7b510895c4d5.png">

I can't find any documentation about this.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by joaomoreno** [comment]
It does support `$1` `$2`, etc., for group matches. It doesn't seem to support `$0` for the entirety of the match.

**Comment by alexandrudima** [comment]
I didn't know this either, but apparently that is achievable with `$&`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

(disclaimer: we call JavaScript's string.replace).

I will look into adding support for `$0` too, by transforming it to `$&` behind the scenes.

**Comment by alexandrudima** [comment]
To verify: any platform can be used, this is not platform specific

**Comment by pcgeek86** [comment]
@alexandrudima Nice, thank you!!

**Comment by pcgeek86** [comment]
@alexandrudima Also very helpful to understand that you're using JS regex implementation. I didn't know that before, but now I know where to look for more information. :smile:
