### ISSUE TITLE
Trashcan button kills entire terminal process tree including non-console apps

### ISSUE THREAD

**Issue by the-ress** [Microsoft/vscode#35492]
- VSCode Version: Code - Insiders 1.17.0-insider (7ac1f1e05baad03d4dd8f8515f1e598180b2c97e, 2017-09-30T05:06:21.234Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open a non-console app from vscode terminal (e.g. notepad)
2. Kill the terminal using the trashcan button

Expected: Only the terminal process and any other processes attached to the console should be killed.
Actual: Entire process tree is killed, even non-console applications.

**Comment by Tyriar** [comment]
Yeah I introduced this earlier when trying to fix the process leak problem. Windows terminal support is my big focus in October so it should get resolved there :smiley:

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/26807

**Comment by the-ress** [comment]
Thanks! This has been keeping me at 1.14. (The fix will ship with 1.18, right?)

**Comment by Tyriar** [comment]
1.14 o.0 you're missing *a lot* of good stuff.

Yes the fix is coming in 1.18 in early November.
