### ISSUE TITLE
Linux: WatcherService consumes 100% cpu on large folder

### ISSUE THREAD

**Issue by halyavin** [Microsoft/vscode#355]
As soon as I open Visual Studio Code, the watcherService process (a process with flag --type=watcherService) started from the renderer process starts to consume 100% cpu and 60Mb to 1.6 Gb of memory. If I kill the process, it relaunches immediately. No other process consumes cpu in the idle state.
Version: 0.10.1
OS: Ubuntu 14.04

**Comment by bpasero** [comment]
@halyavin could it be that you open a large folder with many files?

**Comment by halyavin** [comment]
Yes, this is a large folder with many files. But why it consumes 100% of cpu indefinitely? Eclipse doesn't have such problem on this project.

**Comment by bpasero** [comment]
@halyavin our watcher implementation on Linux is not very good, it has to scan each folder for changes which can be time consuming. You can use the files.exclude setting to add folders you dont need to see in the explorer and it will also exclude them from watching.

**Comment by halyavin** [comment]
May be switch off global project watching (restrict it to currently edited files) and make user press refresh? There is a great chance an efficient Linux watching will never be implemented.

**Comment by bpasero** [comment]
I would accept help here if someone has an idea for efficient Linux file watching.

**Comment by wycats** [comment]
I'm experiencing a similar issue on OSX with `ElectronHelper`.

**Comment by halyavin** [comment]
I just found out, by looking at the process tree on my machine, that IntelliJ IDEA has a similar process for Linux file watching and they made in open source (Apache license):
https://github.com/JetBrains/intellij-community/tree/master/native/fsNotifier/linux . You can just reuse it for VS Code.

**Comment by chadhietala** [comment]
Seeing the same thing on OSX with `ElectronHelper`.

**Comment by bpasero** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/3998
