### ISSUE TITLE
VSCode Insiders adds import statements above file header comment

### ISSUE THREAD

**Issue by Frikki** [Microsoft/vscode#35503]
- VSCode Version: 1.17.0-insider
- OS Version: Linux

Steps to Reproduce:

1. Create a new .ts file: `a.ts`.
2. Add this code to `a.ts`:
    ```typescript
    export function a() {}
    ```
3. Save `a.ts`.
4. Create a new .ts file: `b.ts`.
5. Add a file header comment, e.g.:
    ```typescript
    /**
     * File: b.ts
     */
    ```
6. Below the file header comment, add:
    ```typescript
    const b = a()
    ```
7. Move cursor between `a` and `(`.
8. Press `CTRL+.`.
9. Choose _Import from "a"._

Reproduces without extensions: Yes

IMHO, the import statements should be place _below_ the file header comment.

**Comment by mjbvz** [comment]
Thanks! I've opened https://github.com/Microsoft/TypeScript/issues/19042 to track this upstream
