### ISSUE TITLE
[folding] Endregion case-sensitive depending on case Region is specified in

### ISSUE THREAD

**Issue by mikefrobbins** [Microsoft/vscode#35506]
- VSCode Version: Code - Insiders 1.17.0-insider (7ac1f1e05baad03d4dd8f8515f1e598180b2c97e, 2017-09-30T05:06:21.234Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3

The endregion keyword must be specified in lower case when region is specified in lower case. Endregion is not case sensitive when region is specified in proper, mixed, or upper case. For more details see: http://mikefrobbins.com/2017/10/02/regions-are-now-available-in-vscode-as-of-insiders-build-version-1-17-0/

---

Steps to Reproduce:

1. Specify region in lower case.
2. Specify endregion in anything other than lower case.

**Comment by aeschli** [comment]
@daviwil https://blogs.technet.microsoft.com/heyscriptingguy/2016/01/09/weekend-scripter-unexpected-case-sensitivity-in-powershell/ says regions are case sensitive.
What's the correct behaviour?

**Comment by mikefrobbins** [comment]
That's funny, I just realized that I wrote the blog article that's referenced in the previous comment by @aeschli

**Comment by aeschli** [comment]
I verified that in the Powershell ISE #region and #endregion must be all in lowercase, so I assume that's how is designed.
Closing, but I'm happy to change it to whatever the spec says.

**Comment by mikefrobbins** [comment]
@aeschli based on your comment for closing this issue, it has not been resolved and is not working as designed.
In VSCode insiders build version 1.17.0, regions work when specified in a case other than lower case which based on your comment is not how it's designed. You should only be able to use lower case.

**Comment by aeschli** [comment]
Note that indentation based folding is also active. That's what you are seeing
If not, please add a sample.

**Comment by mikefrobbins** [comment]
`#Region
    <#
    Region can be upper, proper, or mixed case with no problem. This should not
    work, but it does.
    #>
#endregion`

**Comment by aeschli** [comment]
@mikefrobbins That's because the line below #Region has a larger indent. The normal folding by indentation rules apply.
What's new with the added folding marker support is that these work regardless of indent,  e.g:
![image](https://user-images.githubusercontent.com/6461412/31272648-ff4812cc-aa8b-11e7-993d-07db79dda1ab.png)
