### ISSUE TITLE
Discard changes should throw the files in the bin

### ISSUE THREAD

**Issue by Slackercode** [Microsoft/vscode#35501]
![adad](https://user-images.githubusercontent.com/24302433/31096091-94b49964-a7aa-11e7-8abe-2b193fce1ce0.png)
-The files should not be permanently deleted, instead they should be moved to the trash bin.
-`Discard changes` should be renamed to `Delete file`.

**Comment by joaomoreno** [comment]
This action comes from git. Git simply deletes the file. The action will show you a popup explaining that specific files will be forever deleted. Closing as designed.
