### ISSUE TITLE
Dialog menu breaking

### ISSUE THREAD

**Issue by JSBmanD** [Microsoft/vscode#35500]
3 buttons hides in dialog window after hiding vscode.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-debug|Uni|1.2.1
csharp|ms-|1.12.1
team|ms-|1.122.0
---
Steps to Reproduce:

1. Open file.
2. Roll up vscode window for a while.
3. Expand window.

Reproduces without extensions: Yes
Normal behaviour:
![screenshot_20171002_223750](https://user-images.githubusercontent.com/5402335/31095805-bd2d76e6-a7c2-11e7-8c20-6943446bf6af.png)
Bug:
![screenshot_20171002_223831](https://user-images.githubusercontent.com/5402335/31095821-c9abc01c-a7c2-11e7-8e04-208a49d88f59.png)

**Comment by alexandrudima** [comment]
@JSBmanD The context menu is ... context sensitive. When showing the context menu, the actions that show up depend on the language of the buffer and if the editor is read only.

What languages are you right clicking in ?

**Comment by JSBmanD** [comment]
C#. This happens on the same element(and all the elements afterwards) as I clicked before hiding vscode window.

**Comment by alexandrudima** [comment]
This might happen if the C# extension decides to dispose its provider registrations.

**Comment by alexandrudima** [comment]
Moved to https://github.com/OmniSharp/omnisharp-vscode/issues/1774
