### ISSUE TITLE
showErrorMessage(message, ...items) not displayed

### ISSUE THREAD

**Issue by vladdu** [Microsoft/vscode#35504]
When using the showErrorMessage(message, ...items) API, no message is shown. I couldn't find anything about this at all.

- VSCode Version: Code - Insiders 1.18.0-insider (f31c369c3bd686d494cb0f01a4ed051b5e9956d0, 2017-10-02T05:16:04.623Z)
- OS Version: Linux x64 4.10.0-35-generic

Steps to Reproduce:

1. From an extension do for example `showErrorMessage('message', 'item').then(s=>{})`. No message box is shown.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
I'm surprised you are on 1.18.0-insiders. Did I miss us publishing that @Tyriar?

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/31109700-d77b187a-a801-11e7-8985-88a896828f25.png)

I cannot reproduce with the code `showErrorMessage('message', 'item').then(s=>{})`. Is there any output?

**Comment by vladdu** [comment]
just downloaded another update, it works now. Thanks!
