### ISSUE TITLE
Proposal: default webp image format support

### ISSUE THREAD

**Issue by mazyvan** [Microsoft/vscode#35502]
- VSCode Version: 1.16.1
- OS Version: Windows 10

**Comment by mazyvan** [comment]
https://developers.google.com/speed/webp/

**Comment by chrmarti** [comment]
Could you be more specific on what the feature should do? Could it be implemented by an extension?

**Comment by mazyvan** [comment]
![image](https://user-images.githubusercontent.com/10915753/31134904-126ac21a-a829-11e7-8c2d-11617f53e89b.png)

The editor by default don't recognize the webp image format. And I couldn't find any extension

**Comment by chrmarti** [comment]
Seems we would need to add it to the list in resourceViewer.ts and the built-in icon themes.
