### ISSUE TITLE
Indentation: make it clear that the change is temporary

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3551]
I think the action should make it clear that its temporary (only for current editor) and show me in the list what the default actually is or at least offer a way to undo my change and go back to default settings

from @bpasero

**Comment by isidorn** [comment]
@bpasero I tuned this a bit based on your feedback, check it out and let me know what you think

**Comment by bpasero** [comment]
@isidorn much better, but I suggest to also emphasize the default, similar how encoding does it:

![image](https://cloud.githubusercontent.com/assets/900690/13395155/47568e98-deed-11e5-9fef-2ed187963d6e.png)

**Comment by bpasero** [comment]
Maybe it should read "Configured tab size" or something like that.

**Comment by isidorn** [comment]
Ok, I tuned the wording and I now show the default value. 
Please note that I decided to initially select the tab size value for the current editor, but I put the 'default' description for the tab size that is specified in the configuration file. Let me know how you feel about it

**Comment by isidorn** [comment]
btw I went with 'Configured Tab Size', not sure if 'Configured Tab Size in Workspace' is better to make it more clear that it is coming from the settings file. Though it might be come from user.json and then it might be confusing
