### ISSUE TITLE
Tooltip display glitch

### ISSUE THREAD

**Issue by sarbash** [Microsoft/vscode#35518]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
overtype|ada|0.2.0
Go|luk|0.6.65
vscode-icons|rob|7.14.0
vscode-proto3|zxh|0.1.2

---

Steps to Reproduce:

1. Move the cursor to the element to see a multiline tooltip
2. Then move the cursor to the element with a single-line tooltip
3. Now, the text of the tooltip is invisible and is below first line of the tooltip

Reproduces without extensions: Yes

![default](https://user-images.githubusercontent.com/1932297/31119024-4101b6a6-a838-11e7-94fc-82884220813a.png)

![default](https://user-images.githubusercontent.com/1932297/31119051-5af8d986-a838-11e7-9868-11da459d8d62.png)

**Comment by joaomoreno** [comment]
@bpasero Seems like an upstream issue. Do we have a duplicate?

**Comment by bpasero** [comment]
Maybe https://github.com/Microsoft/vscode/issues/23946 ?

**Comment by joaomoreno** [comment]
Definitely.
