### ISSUE TITLE
Text selection in Command Palette not working correclty

### ISSUE THREAD

**Issue by jannik-mohemian** [Microsoft/vscode#35517]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.8
csharp|ms-|1.12.1
sublime-keybindings|ms-|2.9.1
jenkinsfile-support|sec|0.1.0
vscode-fileutils|sle|2.6.2

(1 theme extension excluded)

---

**Steps to Reproduce:**

1. Open the command palette `⌘⇧P`
2. Type text and select it to the end of the line **OR** execute a command that will result in selected text in the command palette e.g. `File: Move`
3. Hit the `→` (right arrow) key

**Behavior:** Nothing happens.

**Expected Behavior:** The selected text should be unselected and the cursor should move to the end of the line.

**Important:**
* This bug only occurs when the selection spans to the end of the line. 
* This bug does **NOT** occur for hitting the  `←` (left arrow) key

Reproduces without extensions: `Yes`

**Comment by bpasero** [comment]
I think I fixed that. @jannik-mohemian 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jannik-mohemian** [comment]
You're completely right! Issue can be closed. Thanks for the quick response. 🎉
