### ISSUE TITLE
Keybinding for auto-import feature

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#35515]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra

Reproduces without extensions: Yes

---------
It would be nice if we could add a keybinding to the auto-import feature. Now I have to put my cursor on the red line and press the lightbulb on the left side. Would be nice to be able to do this without having to manually press it but use a keybinding to invoke the import action.

![screen shot 2017-10-03 at 11 13 00](https://user-images.githubusercontent.com/1913805/31117899-dcc0dea8-a82b-11e7-8f14-cd2523593fbb.png)

**Comment by jrieken** [comment]
You can use `Cmd+.` and with more recent version we do pre-select the first item in that list.

**Comment by jrieken** [comment]
We are also working on making the code action infrastructure better, esp when a code action fixes something or when it's just a refactoring. This issue sure is duplicated by another issue...

**Comment by SamVerschueren** [comment]
> You can use `Cmd+.` and with more recent version we do pre-select the first item in that list.

Oh my god, why didn't I knew this before 😱. This is a lifesaver. And now I notice that when hovering over the lightbulb, the tooltip shows `Cmd+.`.

Feel free to close this issue!

**Comment by jrieken** [comment]
Ok. Happy that I could help
