### ISSUE TITLE
Color picker replaces wrong range when in template mode

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#35519]
1.17-insiders

- open the settings file and add 
```
"workbench.colorCustomizations": {

}
```
- inside the block, use code completion, pick a color
- without changing the cursor location enter a color value, e.g. '#FF0000'
- move the mouse over the color value and pick a new color with the picker
- the result is
```
"welcomePage.buttonHoverBackground": ""#cf6161""
```

**Comment by aeschli** [comment]
I'd suggest to also push this to the 1.17 branch

**Comment by aeschli** [comment]
Pushed to 1.17 branch as well

**Comment by chrmarti** [comment]
@aeschli Can this be closed?

**Comment by aeschli** [comment]
Yes, fixed.
