### ISSUE TITLE
RemoteFileService.resolveFiles can return results out of order

### ISSUE THREAD

**Issue by keegancsmith** [Microsoft/vscode#35512]
This can lead to bad bugs in the explorer viewlet where roots become un-expandable. The easiest way to reproduce is add more than 10 folders to the workspace.

https://github.com/microsoft/vscode/blob/8414d5c03e059ec6d0f725c74a94315403284f3c/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L174-L187

This can happen in two cases:
1. There are more than 10 files to resolve.
2. There is a mix of schemes.

For (1) it is because the implementation uses groupBy, which in turn uses sort. node's sort is not stable. However, for small values it is which is why this probably hasn't been noticed before. For (2) its because at the end of the function we just flatten the groups, without respect to the initial input order. This likely hasn't been noticed since most people just have `file` schemes as the roots.

cc @jrieken

**Comment by jrieken** [comment]
Nice find.

**Comment by keegancsmith** [comment]
@jrieken this still doesn't solve the 2nd point I mentioned in the description. If people actually use the remote service (rather than just `file` resources) the results will be out of order. However, I'm not sure if that would effect any current uses in the codebase, but could effect future uses.

**Comment by jrieken** [comment]
Did you look at both changes? I fixed `groupBy` but the remote file service doesn't actually use it anymore but uses a softer grouping which is "use groups if called with groups otherwise don't"

**Comment by keegancsmith** [comment]
oh sorry! I only saw the stable sort commit. Yes the algorithm in the other commit looks good to me. :+1:
