### ISSUE TITLE
Justify assign-util in presence of object spread and mixin

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35526]
We have (and had before) `objects#mixin` and have since while object spread supported by TypeScript. That makes we wonder why we have `objects#assign` which for once duplicates what TypeScript now offers and (I believe) also duplicates what `mixin` offers. We should first try to nuke our `assign` and then also review `mixin`

**Comment by joaomoreno** [comment]
@jrieken Totally agree. I can remove `assign`, but I won't touch `mixin` as I didn't create nor used it.

**Comment by joaomoreno** [comment]
@jrieken Actually I won't touch this. `objects#assign` is a statement while the object spread is an expression.

```es6
const o = {};
objects.assign(o, { hello: 'world' });
// o.hello is defined
```

You can't do this with object spreading afaik, without removing the `const`, which sometimes is far from ideal (eg when objects are owned in other places than the modification).

**Comment by jrieken** [comment]
I was thinking of this [`const o = { ... { hello: 'world' }}`](http://www.typescriptlang.org/play/#src=%0D%0Aconst%20o1%20%3D%20%7B%7D%3B%0D%0Aobjects.assign(o%2C%20%7B%20hello%3A%20'world'%20%7D)%3B%0D%0A%0D%0Aconst%20o2%20%3D%20%7B...%20%7B%20hello%3A%20'world'%20%7D%7D). Also, I don't understand why `assign` was added in the first place give that mixin is doing the same thing

**Comment by joaomoreno** [comment]
Yeah, but assign has side effects on its first argument. You can't do that with object spread. I'm all about using object spread, but I'm not going to go around the code and rewrite `assign` methods to use the spread operator, while making sure all the side effects are considered. Why would you want to risk breaking code?

Mixin is recursive (and seems to have an overwrite option), while assign isn't.

Let me know what you want to do.

**Comment by jrieken** [comment]
Closing as I understand the difference between `assign` and `mixin`... I hope "our" is standard compliant such that we can eventually switch to `Object.assign`
