### ISSUE TITLE
Does `product.json` slow down startup?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35523]
1. build vs code locally via `npm run gulp vscode-darwin`
2. start/restart (not reload) it a few times and keep note of the `"[renderer] window.loadUrl() => begin to require(workbench.main.js)"`. On my machine this is around ~390ms
3. copy the `product.json` file from Insiders to your build
4. release step 2, and note that the times for `"[renderer] window.loadUrl() => begin to require(workbench.main.js)"` got worst, on my machine ~450ms

~~"Wer misst, misst Mist" but I believe this is the `extensionsGallery` entry because (a) I imagine it being used on the main side (maybe too early) and (b) because removing that (and keeping everything) changes the times again.~~

**Comment by jrieken** [comment]
@joaomoreno Do you have insights when/how `extensionsGallery` is being used or what from product.json is being used very early (before code loading, so most likely on the main side)

**Comment by joaomoreno** [comment]
We do use it to check for updates... but AFAIK it all happens in the shared process. @sandy081 can provide more insight.

**Comment by jrieken** [comment]
false. measured a few more times and no more difference between the times...

**Comment by sandy081** [comment]
Just to update, we do use product.json for extension recommendations on the main side. I think we can delay collecting tips and recommendations until workbench is ready. IMO they are not mandatory to be read during workbench start up.

@ramya-rao-a FYI

**Comment by ramya-rao-a** [comment]
> false. measured a few more times and no more difference between the times...

@jrieken no more difference between keeping extensionGallery and removing it?
