### ISSUE TITLE
Review your deepClone usages

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35525]
For reasons unknown to the history books there is `clone` and `deepClone` in [objects.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/objects.ts#L10). Both are a deep clone but both are slightly different. Since there more (53 vs 32) usages of `clone` I am asking you to review/update your references to use `clone` instead of `deepClone`. We should delete the latter at the end of this.

**Comment by isidorn** [comment]
Thanks. Done.

**Comment by dbaeumer** [comment]
Personally I think that we should review the usages of clone to decided whether they need a deepClone. Users that decided to call deepClone already made the decision that they want a deepClone. 

Or is the idea to rename clone to deepClone at the end of this ?

**Comment by jrieken** [comment]
> Or is the idea to rename clone to deepClone at the end of this ?

Yes

> Personally I think that we should review the usages of clone to decided whether they need a deepClone.

Well, I wanted to start with deepClone because its just you and Isi using it

**Comment by jrieken** [comment]
Thanks
