### ISSUE TITLE
Focus terminal actions are spamming the command pallete

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#35520]
There are too many focus terminal actions in the command palette. This way then an accessibility user is searching for focus actions he can not find the appropraite one due to all the clutter imho

Could we somehow reduce this number, by having a focus active one, focus previous, next?

![screen shot 2017-10-03 at 12 37 59](https://user-images.githubusercontent.com/1926584/31121254-be818c4c-a837-11e7-9d19-096ab3663116.png)

**Comment by Tyriar** [comment]
This was a community pull request to allow focusing numbered terminals via custom keybindings, just like what's possible with the editor tabs:

```js
{ "key": "alt+1",                 "command": "workbench.action.openEditorAtIndex1" },
{ "key": "alt+2",                 "command": "workbench.action.openEditorAtIndex2" },
{ "key": "alt+3",                 "command": "workbench.action.openEditorAtIndex3" },
{ "key": "alt+4",                 "command": "workbench.action.openEditorAtIndex4" },
{ "key": "alt+5",                 "command": "workbench.action.openEditorAtIndex5" },
{ "key": "alt+6",                 "command": "workbench.action.openEditorAtIndex6" },
{ "key": "alt+7",                 "command": "workbench.action.openEditorAtIndex7" },
{ "key": "alt+8",                 "command": "workbench.action.openEditorAtIndex8" },
{ "key": "alt+9",                 "command": "workbench.action.openEditorAtIndex9" },
```

Is just hiding it in the command palette the way to go? Do you know how to hide them from the command palette but keep then available to keybindings.json?

**Comment by isidorn** [comment]
@Tyriar yeah just hide it from the command palette. As for how to do that I know there is a trick, but not sure what it is. 
Just chekced how `openEditorAtIndex` is doing it and I believe the trick is the `when: undefined` clause as done here
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorCommands.ts#L237

**Comment by Tyriar** [comment]
Looking into this more, it's looks like we want these to be *commands*, not *actions*.
