### ISSUE TITLE
Confusing explanation for `activeEditorMedium` in `window.title` setting

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/vscode#35534]
- VSCode Version: 1.16.1
- OS Version: Windows 10

The explanation for `activeEditorMedium` says
`e.g. myFolder/myFile.txt`, which made me believe that it would be the
same as `${folderName}/${activeEditorShort}`.  Instead, I saw full
paths.  After tracking it down in the code I saw the use of `contextService`:

    private get mediumTitle(): string {
        return labels.getPathLabel(this.resource, this.contextService, this.environmentService);
    }

That clarified that it's really a path that is relative to some context,
and I confirmed it by openning a file from an opened directory.

It would be better if the explanation was something like:

    path relative to root, e.g. myFolder/myFile.txt

**Comment by bpasero** [comment]
I updated the description for the following variables:

```
${activeEditorShort}: e.g. the file name (myFile.txt)
${activeEditorMedium}: e.g. the path of the file relative to the workspace folder (myFolder/myFile.txt)
${activeEditorLong}: e.g. the full path of the file (/Users/Development/myProject/myFolder/myFile.txt)
${folderName}: name of the workspace folder the file is contained in (e.g. myFolder)
${folderPath}: file path of the workspace folder the file is contained in (e.g. /Users/Development/myFolder)
${rootName}: name of the workspace (e.g. myFolder or myWorkspace)
${rootPath}: file path of the workspace (e.g. /Users/Development/myWorkspace)
```
