### ISSUE TITLE
Add explorer open editors tail tip setting

### ISSUE THREAD

**Issue by nicosommi** [Microsoft/vscode#35536]
Feature request:

I would love to see the latest tokens of the path on my opened files if it doesn't fit the view

Take a look at this annotated image
![](https://cl.ly/1a3E3a451b2O/[4efb009c674b201ca0ff5d38e5c98770]_Image%202017-10-03%20at%201.48.28%20PM.png)

Maybe using a setting like explorer.openEditors.pathTails

**Comment by Jeyanthinath** [comment]
I will look into this @isidorn

**Comment by isidorn** [comment]
@Jeyanthinath no, we do not want this feature implemented yet. If more users ask for this and somebody proposes a good solution only then we can discuss if we really want it. Thanks

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
