### ISSUE TITLE
installed extensions pane only sized for two extensions

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode#35537]
- VSCode Version: Code - Insiders 1.17.0-insider (5316a2d916b504cc627eb68e119e6b99ea7ad5e5, 2017-10-03T15:39:46.348Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
prettier-vscode|esb|0.24.0
vscode-console-wrapper|fab|0.4.0
debugger-for-chrome|msj|3.3.1
vscode-icons|rob|7.14.0

The "installed extensions" pane is only sized to show two extensions (no matter how many extensions are installed).  It can be manually resized, but upon closing vscode and reopening it will be back to a height that only displays two extensions again.  Not sure what commit changed this, but I believe it was something recent.  I would think it should default to be sized to show all installed extensions, or at least be split half and half with the "recommended extensions" pane.

Steps to Reproduce:

1. Make sure vscode is completely closed
2. Open vscode, navigate to the extensions pane, and notice there are only two installed extensions visible
4. Manually resize the pane to show all installed extensions, and then close vscode
5. Re-open vscode, navigate to the extensions pane, and notice there are only two installed extensions visible again

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/430481/31139677-46cfc71e-a840-11e7-8ba7-c843b32cb00e.png)

**Comment by sandy081** [comment]
@joaomoreno I could reproduce this. 

- Open extensions viewlet
- Update the sashes
- Close the window
- Open new window

- See extensions viewlet sashes are not restored

Any idea ?

**Comment by joaomoreno** [comment]
Sounds like the storage scope is wrong. Did you check that?

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L611

**Comment by sandy081** [comment]
Storage scope is `Workspace` if Workbench State is not empty otherwise `Global`. It looks correct to me.

**Comment by joaomoreno** [comment]
Reproduces with:

1. Set view size
2. Hide sidebar
3. Reload
4. Show sidebar

Sizes are not restored.
