### ISSUE TITLE
[themes] Some Editor Color Tokens Do Not Work

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#35538]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-npm-script|eg2|0.2.1
mssql|ms-|1.2.0
debugger-for-chrome|msj|3.3.1
code-settings-sync|Sha|2.8.3
guides|spy|0.8.4

(1 theme extensions excluded - Contrast Theme)

**The following theme properties do not appear to work:**
1.  `editorSuggestWidget.highlightForeground`
2. `editorMarkerNavigationError.background`
3. `editorMarkerNavigationWarning.background`

---

Steps to Reproduce:

1. [Download and install/enable Contrast Theme](https://marketplace.visualstudio.com/items?itemName=johndugan.contrast-theme) from the vscode marketplace.
2. Open a file where the previously mentioned theme tokens should render the colors defined in the `Contrast.json` theme file.
3. Scratch head in confusion.

**Comment by aeschli** [comment]
Thanks for the findings, I fixed `editorSuggestWidget.highlightForeground`.

The other two are used when you press 'F8' (Goto next error or warning).

![image](https://user-images.githubusercontent.com/6461412/31166366-ce2bf652-a8ee-11e7-95b1-21ad2fffd427.png)
![image](https://user-images.githubusercontent.com/6461412/31166497-3f4fb72e-a8ef-11e7-9a59-67e409845864.png)

**Comment by johndugan** [comment]
Thanks!

RE editor marker navigation: I was confused because `editorMarkerNavigation.background` defines a background color, while `editorMarkerNavigationError.background` and `editorMarkerNavigationWarning.background` define border colors.

Perhaps rename them to `editorMarkerNavigationError.border` and `editorMarkerNavigationWarning.border`.

**Comment by aeschli** [comment]
I agree that 'background' is a misnomer, 'border' would have been better.
