### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by cichy** [Microsoft/vscode#35542]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open terminal
2. Highlight text doesn't work

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please fill out the OS version, VS Code version and provide more details. How are you trying to highlight exactly?

**Comment by cichy** [comment]
It's working in version 1.17.0

**Comment by Tyriar** [comment]
Great 😃
