### ISSUE TITLE
Issue regarding touchpad

### ISSUE THREAD

**Issue by banziFD** [Microsoft/vscode#35545]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.13.0

---

Steps to Reproduce:

1.minimize vscode window.
2.click taskbar to reload vscode.
3.use touchpad to scroll edit area, it will get stuck.
ps: If click restore, scrolling get smooth again.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Could be a duplicate of https://github.com/Microsoft/vscode/issues/35191

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35191
