### ISSUE TITLE
VSCode freezes when opening   7.4MB file.

### ISSUE THREAD

**Issue by nmsmith22389** [Microsoft/vscode#35548]
There is something specifically in this file that is causing the freeze as it doesn't seem to happen with similar sized files or without extensions. I'm guessing that it's the Lua linting.

_File listed below._

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: macOS 10.13 (17A365)
- Kernel Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
output-colorizer|IBM|0.1.2
vscode-paste-and-indent|Rub|0.0.8
wow-bundle|Sep|1.2.4
fish|Ted|0.0.4
project-manager|ale|0.21.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
vscode-dash|dee|1.7.0
KillTasksButton|dtr|0.0.4
tslint|eg2|1.0.9
php-intellisense|fel|1.5.1
macros|ged|1.2.0
docthis|joe|0.4.8
comment|kar|5.0.0
Lua|key|0.0.9
expand-region|let|0.1.1
vscode-todo-parser|min|1.9.1
vscode-csscomb|mrm|5.1.0
vscode-postcss-sorting|mrm|2.3.0
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
incrementor|nms|0.1.0
notes|nms|0.0.1
vetur|oct|0.9.10
laravel-blade|one|1.9.0
typescript-hero|rbb|1.5.0
vscode-sort-json|ric|1.9.2
vscode-icons|rob|7.14.0
partial-diff|ryu|0.3.3
scss-snippets|nms|0.0.1
scope-info|sie|0.2.0
vscode-fileutils|sle|2.6.2
guides|spy|0.8.4
Align|ste|0.2.0
vscode-lua|tri|0.8.1
colonize|vms|2.2.2
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open VSCode
2. Open [this file](https://gist.github.com/nmsmith22389/f1e4fe93f860626524578aacb04822c3).

Reproduces without extensions: No

**Comment by chrmarti** [comment]
Does it occur when you disable the Lua linting extension and keeping all other extensions enabled?

**Comment by nmsmith22389** [comment]
It's kind of confusing at this point. Here's what I mean...

Run|Config|Result
-|-|-
A|All Extensions On|Freeze
B|No Extensions On|Stable
C|Only Lua Off|Stable
C|Only Lua Off|Freeze
D|All Extensions On|Stable

At first I thought disabling the Lua extension fixed it but then it froze once with it off still. Also, it wasn't working at all with all of the extensions on but then it just did. I will keep trying with all extensions off and see if it ever freezes.

**Comment by chrmarti** [comment]
Does it occur just by opening the file or do you always, e.g., type something before it does?
