### ISSUE TITLE
Code - Insiders 1.17.0-insider throws error when Powershell extension is enabled and run as admin

### ISSUE THREAD

**Issue by kcwms** [Microsoft/vscode#35540]
![when_starting_as_admin_and_opening_workspace_with_powershell_plugin_enabled](https://user-images.githubusercontent.com/29052675/31142037-1da6f914-a847-11e7-8752-a6f468772d1f.PNG)
- VSCode Version: Code - Insiders 1.17.0-insider (f7962f0682a76516df51de4856f8ccc5d8ad578a, 2017-09-20T05:24:33.599Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-guid|hea|1.1.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
mssql|ms-|1.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
shell-launcher|Tyr|0.1.3

---

Steps to Reproduce:

1. have the Powshell plugin enabled (**when not enabled there are no issues**)
2. open VSCode-Insiders as administrator
3. open a project with a *.ps1 file

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@kcwms could you try reproduce on the latest version of insiders? Yours seems to be about 5 days old and there was some movement around this code then.

/cc @daviwil

**Comment by kcwms** [comment]
just updated latest to 1.17.0-insiders and that seems to have solved the problem.
Gracias!!

**Comment by Tyriar** [comment]
Great 😄
