### ISSUE TITLE
Shrinkwrap devDependencies

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#35543]
Just a heads up, while working on #30134 I noticed that vscode does not shrinkwrap its `devDependencies`. While in npm 5 it is the default, in npm 4 it requires the extra flag `npm shrinkwrap --dev`.
This means a faulty minor/patch version somewhere in the devDependency tree (e.g. a gulp dependency etc) could cause a build failure.

As an example, master is currently broken because of a breaking change in an `@types` package: https://travis-ci.org/Microsoft/vscode/jobs/282871823#L2579

**Comment by joaomoreno** [comment]
We do know this. It's a purposeful state of affairs since we always want the latest dev tools around. The risk is, of course, what you just mentioned, but we're willing to take it.

Do you still see the compile error? I don't see it on master now.
