### ISSUE TITLE
Git: sometimes diff stays empty when clicked

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35559]
I often end up seeing no diff when I click on a change, hard to say how to reproduce though, once I close the editor and reopen it shows up properly. Proof:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/31165259-b074dd9e-a8ea-11e7-9d1d-433ad6eba705.gif)

There is no output in the console when this happens.

**Comment by joaomoreno** [comment]
Please, please, please, try to narrow it down to reproducible steps.

**Comment by joaomoreno** [comment]
It's not that the diff stays empty. The contents on both sides appear equal for some reason...

**Comment by bpasero** [comment]
@joaomoreno just had it again and I can verify that clicking the entry in the SCM list does not trigger any command, nor does it trigger opening the editor. I can easily open the editor from the editor history. So it seems this is not at all related to any editor diff stuff, but purely the git extension not issuing the command.

Again let me know where to set a breakpoint to find out more.

**Comment by joaomoreno** [comment]
So you're saying it's the same as https://github.com/Microsoft/vscode/issues/33594?

> clicking the entry in the SCM list does not trigger any command

But in the GIF, when you click the row something does happen: the diff input opens but with equal contents on both sides.

**Comment by bpasero** [comment]
@joaomoreno yeah good point, so this is actually a different issue :-/. At home I had it not hitting `editorPart.openEditor()` when I clicked. But yeah, my gif seems to be yet another issue which is not the same.

**Comment by bpasero** [comment]
@joaomoreno btw there is 0 activity when I click the entry and all other entries work so I do not think what I saw is #33594

**Comment by borekb** [comment]
I've seen this too, and also cannot provide better steps to reproduce :( But it's new in 1.17, never seen this before and it happened about 3 times during the past few days.

**Comment by chrmarti** [comment]
Any hints on how to verify this?

**Comment by joaomoreno** [comment]
@bpasero Can you please verify this? You know exactly the steps. 👍
