### ISSUE TITLE
Shortcuts don't respect keyboard layout

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#35554]
_From @ericelliott on December 7, 2016 9:59_

I'm using the Dvorak keyboard layout.

The following shortcuts appear to be configured in the Default Keyboard Shortcuts, but don't work:

```
{ "key": "shift+cmd+=",           "command": "workbench.action.zoomIn" },
{ "key": "cmd+=",                 "command": "workbench.action.zoomIn" },
{ "key": "shift+cmd+-",           "command": "workbench.action.zoomOut" },
{ "key": "cmd+-",                 "command": "workbench.action.zoomOut" },
```

Instead, it appears to indent the current line in. When I use the physical + and - keys, it does work.

This doesn't work whether I use the physical key or the mapped key:

```
{ "key": "alt+cmd+/",             "command": "editor.action.commentLine",
                                     "when": "editorTextFocus" },
```

Note: when editing key bindings, I get little info hints that tell me to use the mapped keys (the ones that don't work) instead of the physical keys. Those info hints describe behavior that I want, but doesn't exist.

_Copied from original issue: Microsoft/vscode-sublime-keybindings#31_

**Comment by auchenberg** [comment]
_From @waderyan on December 9, 2016 22:27_

@alexandrudima could I get your help here...

**Comment by alexandrudima** [comment]
Our keyboard infrastructure has been implementing to work by dispatching scan codes in ~ March 2017.
