### ISSUE TITLE
When I Open Just One File in Initialized Git Folder - Source Control Shows Number of Changed Files

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#35555]
- VSCode Version: 1.16.1
- OS Version: Windows 10 1703 15063.632

When I Open Just One File in Initialized Git Folder - Source Control Shows Number of Changed Files. And project folder is not shows in explorer.

It's a Bug?

Steps to Reproduce:

1. Open folder with Initialized Git Repository in VSCode and make some changes in files
2. Then close VSCode
3. Open only one file from this folder in VSCode (with [right mouse button](https://i.imgur.com/3tZNbTa.png))

Gif Demonstration:

![vscode-issue](https://user-images.githubusercontent.com/20873402/31157496-51c5b8b0-a870-11e7-85de-76d28d34bf4f.gif)

Expected Behavior:

When I open just one file in Initialized Git Folder I need to see only this file. No any information from all project (as on gif).

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
We try to help you and start monitoring git repositories which contain files you edit. We believe this is a good thing.

Would you like a setting to disable this behaviour?

**Comment by Zx-EvM** [comment]
@joaomoreno 

> Would you like a setting to disable this behaviour?

Yes. If possible it will be great to have.

**Comment by joaomoreno** [comment]
Do you want to attempt a PR?

I was thinking something like a `git.autoRepositoryDetection` setting, with a boolean value.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/36183
