### ISSUE TITLE
any plan to use native background editor engine?

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#35557]
hi,all:
i found a useful background editor engine [xieditor](https://github.com/google/xi-editor). maybe, we can use xieditor for background render,Syntax highlighting. and so on...  this is an example [xi-electron](https://github.com/callodacity/xi-electron)
it based rust language ,that means it very fast and safety.

**Comment by isidorn** [comment]
@NateLing thanks for letting us know, however we are currently using the [monaco editor](https://github.com/Microsoft/monaco-editor) and do not plan to switch.
