### ISSUE TITLE
VS Code Insiders Windows installer extremely laggy

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#35558]
Couldn't find an existing issue for this, so here goes. The VS Code Insiders Windows installer is extremely laggy on my PM. Takes minutes to show the window and while the installation process itself is reasonably fast, the cleanup/restarting apps phase is similarly slow (minutes).

Is there a log I can provide? What diagnostic methods are at my disposal to identify the bottleneck for you?

**Comment by joaomoreno** [comment]
We're actually using [Inno Setup](https://github.com/jrsoftware/issrc), so those guys could possibly help you out more than us. Keep an eye on #33184 #534 #13308 for alternatives.

**Comment by TomasHubelbauer** [comment]
@joaomoreno There is more to this issue, sometimes (like with this recent update), clicking on *Restart to update* will close VS Code Insiders without anything happening (the installer is not started or fails to start - waited for about 15 minutes to be extra sure) and only the second time *Restart to update* is clicked, it actually starts the installer. This may still be an Inno issue, but I'm providing this information in order to give a completely picture of the experience on Windows.
