### ISSUE TITLE
Use strict version-identifier for @types/xyz-modules

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35561]
This is a source of breakage. For instance, we needed to push https://github.com/Microsoft/vscode/commit/81fc22ec957de26d2bf6aada3f16f04e0164741c to the `release/1.17`-branch because some d.ts files had changed so that we cannot compile anymore. For the a similar reason we are not able to compile from our `release/1.15` branch anymore. This is scary and while the underlying issue is `d-ts`-modules not caring about semver-semantics we should be acknowledging that and be strict when adding `@types/foo` dependencies.

**Comment by jrieken** [comment]
I did assign folks based on searching for `@types/` in all `package.json` files

**Comment by aeschli** [comment]
I updated html/json/css and the various task extensions (for @dbaeumer)

**Comment by joaomoreno** [comment]
Another idea is this: #35543 Thoughts?

**Comment by joaomoreno** [comment]
Locked `git` deps.

**Comment by ramya-rao-a** [comment]
emmet updated
