### ISSUE TITLE
[html] Allow to ignoring base href

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vscode#35568]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0

I'd like to disable the integration for `<base href="/some-path/">`.
Right now the editor 'thinks' it should 'link' paths and prepend it with the base href, but this is only applicable when the application is deployed, since then it's running on a sub-directory.

How to reproduce:

1. Create two files: `index.html` and `script.js` in the same directory
0. Add `<base href="/some_path/">` to the index.html
0. Add `<script src="script.js"></script>` to the index.html
0. Try to `cmd + click` or `ctrl + click` on the script.js

**Expected**
Navigate to `./script.js`

**Actual**
Navigation blocked: 
```
Unable to open 'script.js': File not found (/Users/....../some-path/script.js).
```

**Comment by aeschli** [comment]
Tricky problem, as it's a general problem that the file structure while development and deployment can differ, especially with scripts.
