### ISSUE TITLE
VS Code window crashes

### ISSUE THREAD

**Issue by cambraidwood** [Microsoft/vscode#35562]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

After the application has been open for a while (days) ... I get a popup message saying the window has crashed. Has only ever done this after latest release.

**Comment by chrmarti** [comment]
Did you do anything specific when this happened? E.g., browsing large files?

Did this happen multiple times?

**Comment by cambraidwood** [comment]
Its after I interact with the app after a period of inactivity, may after lunch, but I mainly notice it in the morning the first time I click on it, or try to move the window from one screen to another.

I put the laptop to sleep overnight and wake it back up in the morning.

It has a project open, the files are no different from any normal html / angular file.

Its happened about 6 or 7 times since applying the last update a few weeks ago.

rgds,
Cam.

**Comment by chrmarti** [comment]
Are you using the terminal? (Could be #34301)

**Comment by cambraidwood** [comment]
Yes , I have the terminal window open with three terminals running




Sounds like it could be the thing, at least it's been noted




Thanks for your assistance




Get Outlook for Android







On Wed, Oct 4, 2017 at 9:33 PM +0100, "Christof Marti" <notifications@github.com> wrote:












Are you using the terminal? (Could be #34301)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34301
