### ISSUE TITLE
completely split wondows

### ISSUE THREAD

**Issue by guftall** [Microsoft/vscode#35569]
- VSCode Version: 1.16.1
- OS Version: ubuntu 16.04

its so good if i can pick my windows and place them in other place, not just around fullscreen program.

for example drag debugConsole and drop it on my second screen. just like eclipse

**Comment by isidorn** [comment]
There are already issues opened that request something like this. Please search in our repo for panel position and windows and you will be sure to find some interesting ones to upvote. Thanks
