### ISSUE TITLE
Visual Studio Code starts up unexpectedly when phone is plugged in via USB

### ISSUE THREAD

**Issue by fschutt** [Microsoft/vscode#35563]
Visual Studio Code launches unexpectedly whenever a phone is plugged in via USB. I don't know what the one has to do with the other, but it is reproducible: When I unplug the phone and replug it in, VSC opens. I've tried multiple USB ports, multiple phones. Not sure if this happens with IOS devices, I only have Android.

- VSCode Version: 1.16.1 (commit #27492b6bf3acb0775d82d2f87b25a93490673c6d)
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Install vscode
2. Plug your phone in via USB

Result: A new VSC window pops up. This also happens if the phone is plugged in while the computer starts up, meaning every time I log in, VSC pops up.

I am completely at a loss as to why this happens or why plugging a phone in and VSC opening are correlated. Maybe some mount script uses the keyword "code", but I am not sure.

**Comment by chrmarti** [comment]
Does this help? https://superuser.com/questions/556674/how-can-i-change-the-default-action-taken-on-removable-media-in-ubuntu

**Comment by fschutt** [comment]
Thanks, this helped. I'm sorry for asking. It still opens, even if I set all options to "ask me everytime". I'm sorry that I didn't think of this earlier. If I uninstall VSCode, the regular file explorer opens - as if VSCode would take precedence over the regular file viewer. I also don't know why specifically VSCode (it was not marked in the settings at all). However, this is, not a bug regarding VSCode. Thank you for your answer.
