### ISSUE TITLE
Error trying to run a 'program' with the extension

### ISSUE THREAD

**Issue by Elejdor** [Microsoft/vscode#3556]
When I run the extension from Visual Code and I try to start a 'program' I get:
Error: DebugAdapter bin folder not found on path c:/.../vscode-mock-debug-master/out/mockDebug.js

It doesn't generate the output file. I checked HelloWorld extension and it compiled correctly. I also tried installing Mock-Debug as pre-built extension and it works too.

Regards

**Comment by weinand** [comment]
@Elejdor Are you building your own debug adapter based on mock-debug? Did you build your debug adapter?

**Comment by weinand** [comment]
No info after 7 days -> closing.

**Comment by ChuanjenWang** [comment]
I got the same situation when I execute C# console application, any recommend?
