### ISSUE TITLE
代码格式化问题

### ISSUE THREAD

**Issue by verySunshine** [Microsoft/vscode#35565]
1、格式化深层次节点的HTML代码时，没有缩进或者未对齐。
2、格式化混合型代码格式不漂亮

**Comment by yoyo837** [comment]
Please use the world language - English communication, the community can be better involved.
请使用英语方便社区中世界各地的人员参与到一起。谢谢！

**Comment by chrmarti** [comment]
Which language is this? Could you attach an example demonstrating the problem?
