### ISSUE TITLE
Are touchBar commands really, always editor aware?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#35564]
Stumbled over [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L138) 

```
// If we run an action from the touchbar, we fill in the currently active resource
			// as payload because the touch bar items are context aware depending on the editor
			if (request.from === 'touchbar') {
				const activeEditor = this.editorService.getActiveEditor();
				if (activeEditor) {
					const resource = toResource(activeEditor.input, { supportSideBySide: true });
					if (resource) {
						args.push(resource);
					}
				}
			} else {
				args.push({ from: request.from }); // TODO@telemetry this is a bit weird to send this to every action?
			}
```

It seems your commands wanna be [editor commands](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommonExtensions.ts#L99)

**Comment by bpasero** [comment]
I tried to simulate what we are doing for the [`EditorTitle`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/titleControl.ts#L337) actions where we add the current resource to the arguments when running the command.

**Comment by jrieken** [comment]
Yeah, the `EditorTitle` action really sit inside the editor, like context menu actions for the explorer or editor. The touchbar seems more like a global command palette IMO, similar to F1.

I am not yet decided if passing some 'context' around was a good decision or not. It makes command-authors think their command is only and always called like that. The main reason we have it is that certain API are missing, e.g you cannot figure out what's selected in the explorer nor cannot know the resource of the extensions preview 'editor'. That's what makes me more conservative on this

**Comment by bpasero** [comment]
I was just looking at examples of what to put into the touch bar and I was using the "Open Preview" command from the markdown extension as an example because it seemed like a good candidate. One could argue that possible all editor title actions are good candidates for the touch bar (e.g. next / previous diff when the diff editor is open). 

Is there something to do here to improve this, e.g. it is not clear how to benefit from `EditorCommands`, is the idea to wrap an existing command around that one to run with the currently active editor?

**Comment by jrieken** [comment]
Not really sure what to do... The "Open Preview" or worst the "Go back to source" are the command that started this... We kind of have it now but it's not a very solution... I'd suggest to use the `EditorCommand` for things that we implement in the 'core'. It also takes care of other things, like finding the correct editor when focus is in an embedded editor etc. For extension we don't have a option I guess...

**Comment by bpasero** [comment]
Not planning to work on this near term, closing.
