### ISSUE TITLE
editor.formatOnSave not applying Eslint rules anymore

### ISSUE THREAD

**Issue by nsierram** [Microsoft/vscode#35567]
- VSCode Version: 1.16.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Install extensions: esbenp.prettier-vscode, dbaeumer.vscode-eslint

2. Set following vscode configuration, .eslintrc and node dependencies

```
// vscode settings
// Place your settings in this file to overwrite default and user settings.
{
  "editor.formatOnSave": true,
  "mocha.enabled": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.parser": "flow",
  "javascript.format.enable": false
}
```
```
// .eslintrc
{
  "extends": ["prettier"],
  "parser": "babel-eslint",
  "env": {
    "es6": true
  },
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error",
  }
}
```
```
// package.json
    ....
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.1",
    "babel-preset-env": "^1.6.0",
    "eslint": "^4.8.0",
    "eslint-config-prettier": "^2.6.0",
    "eslint-plugin-prettier": "^2.3.1",
    "prettier": "^1.7.4", ...
```

2. Create a new document with the following code for example and save:
```
const greet = { msg: 'Hello, how are you ?', type: 'hello' };
const { msg, type } = greet;
```

3. You will see that the editor formatting does not apply the eslint rules, although it recognises the error generated afterwards.

4. * if the following vscode setting properties are set, it works. But I don't want to disable the editor.formatOnSave property.
```
"editor.formatOnSave": true,
"eslint.autoFixOnSave": false,
```

Reproduces without extensions: Not possible

**Comment by mjbvz** [comment]
Please file this issue against the eslint extension: https://github.com/Microsoft/vscode-eslint/issues/new
