### ISSUE TITLE
When copying from csvode to some other editor (MS Word, Evernote and so on) the formatting is kept

### ISSUE THREAD

**Issue by anedisi** [Microsoft/vscode#35573]
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: OSX 10.13

Steps to Reproduce:

1. Copy some part of the code, to MS Word
2. The Formating (font-size, color, background) everything is kept.

Reproduces without extensions: Yes

As somebody coming from sublime its anoying, if i want to copy some part of the code, usualy translation strings to some editor, ms word, evernote or something else i want only the string without the formating.

I know the reason why this is im actually copying HTML and MS word and evernote try to keep the formating when you paste HTML but its still anoying.

In word you can choose to paste it without the formating but in other software you cannot.
I dont know is there a solution for this type of problem because for the technology used by vscode.

**Comment by fab1o** [comment]
There're many solutions for this. Yes, VSCode could provide an option, but the best solution in my opinion is to copy the code to Notepad or something like that, and then copy it again from there.

What makes VSCode smarter and better than Sublime is that it gives you the option, and option is good for more ppl.

**Comment by anedisi** [comment]
sorry but that does not make sense. maybe i was not completely acurate. it
not only copies the code it copyes the font color and background color from
the theme thah i used. of what use is that exactly when im copyin it
anywhere else. if i want to copy the code i have no use of background color
of Monokai theme. i just want the code.

and i do hope you understand how anoying of a workload it is to copy it
first to some other regular editor and then to the target software.

**Comment by svenax** [comment]
Both MS Word, Evernote, and many other programs provide a way to paste text without style information. In Word it is called "Paste Special", in Evernote "Paste and Match Style"

**Comment by alexandrudima** [comment]
As @svenax mentions, it is typically the job of the software accepting the paste to pick the best format from the clipboard and have commands to allow the user to pick which format the user desires.

We currently set both the plain text and html formats in the clipboard. We only set the plain text format when copying out of a `.txt` file.

**Comment by anedisi** [comment]
a quick question, what is the intendent purpose of setting it as HTML. its a code editor not a browser, if you can control it i would rather that it behaves like a code editor.

and "paste special" is really not a great solution. you do know word and other text editors default to pasting html because they think you are pasting it from a web browser and they want to keep the formating from a web page. and also paste special has no default keyboard shortcuts, evernote and ms word have different shortcuts. 

the thing that you suggest are workarounds, so my question is why is it setting html in the clipboard at all ? is it how the electron works or something else.

sublime clipboard -> https://imgur.com/a/hoQr7

vscode slipboard -> https://imgur.com/a/cXcSp

**Comment by svenax** [comment]
Different users have different needs. When I paste into a program that handles formatted text, I usually want to include the formatting, so I think it is good that VS Code includes HTML data in the clipboard.

**Comment by sinkuu** [comment]
>  alexandrudima commented on Oct 5 
> .. it is typically the job of the software accepting the paste to pick the best format from the clipboard and have commands to allow the user to pick which format the user desires.

The job might be difficult in `contenteditable` editors. I contacted the support of a web-based service as their wysiwyg Markdown editor is broken when pasted from VSCode. They ended asking me to use another editor :(

**Comment by agibsen** [comment]
On normal "Copy", you should just get the plain text content (with linebreaks and indentation) _not_ style formatting like fonts and colors.
For copying _with_ style formatting, you should use the Command Palette option "Copy With Syntax Highlighting".
Also coming from Sublime Text the current VSCode behaviour of including style formatting is very annoying.

**Comment by rebornix** [comment]
We can now disable this feature by setting `editor.copyWithSyntaxHighlighting` to `false` and "Copy With Syntax Highlighting" will always work as expected.
