### ISSUE TITLE
"The TypeScript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report."

### ISSUE THREAD

**Issue by dandersen2** [Microsoft/vscode#35575]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-timer|Max|1.0.0
vscode-eslint|dba|1.3.2
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.16
vs-code-xml-format|fab|0.1.5
vscode-npm|fkn|3.3.0
easy-icons|jam|0.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1

(21 theme extensions excluded)

---

Steps to Reproduce:

1. Open my project, make any change, save file
2. After 5 minutes the error will popup 

Reproduces without extensions: Yes

I have followed the instructions here and will email the typescript log separately: https://github.com/Microsoft/vscode/issues/17335

**Comment by mjbvz** [comment]
Thanks! I looked through the log but it seems pretty short and has no obvious errors. Can you make sure it is the one from the crashed instance. To do this:

1. Restart VSCode
1. Open a TS or JS file
1. Open the output panel and go to the TypeScript section
1. At the very top of this output there should be lines the look like:

    ![screen shot 2017-10-11 at 5 16 55 pm](https://user-images.githubusercontent.com/12821956/31473238-07a7052a-aea8-11e7-8a7e-53a84c6efb79.png)

1. This is the log file you want
1. Now reproduce the issue and share the log file that was printed above
