### ISSUE TITLE
Letter spacing decoration: cursor offset is wrong

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#35574]
Hello,

This feature was working really great, but recently I retry to use the letter-spacing and the cursor is now offset without changing my code.
I seems the letter-spacing is applied to the text decoration for example 'aaabc', so if I set letter-spacing to -4px for 'aaa' the text is correctly reduced, but if the cursor position is before b, then cursor position doesn't changed and the cursor is now after b.

Do I need to change something to my code or is it a vscode bug ?

Thank you in advance for your help.

A previous issue comment was added, but the issue wasn't reopened since april:
https://github.com/Microsoft/vscode/issues/1925

Any info about the problem ?

**Comment by Alphapage** [comment]
Hello @alexandrudima ,
Any news about this issue? Is it a vscode problem or an electron one ?
You were able to solve it previously, so I hope you will be able to solve it soon.

**Comment by alexandrudima** [comment]
@Alphapage 

I cannot reproduce this. Here I have used `"editor.letterSpacing": -2` and the cursor appears to be placed correctly:

![kapture 2017-12-06 at 11 39 50](https://user-images.githubusercontent.com/5047891/33657648-32c4bab0-da7a-11e7-96c7-14ab95007b38.gif)

**Comment by Alphapage** [comment]
Here is my code:
```
 // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('Hello World!');

        var regEx = /(?:aaaa)(.*\n{0})/g;
		var text = vscode.window.activeTextEditor.document.getText();
		var spacing : vscode.DecorationOptions[] = [];
		var match;
		while (match = regEx.exec(text)) {
			var startPosSpacing = vscode.window.activeTextEditor.document.positionAt(match.index);
			var endPosSpacing =vscode.window.activeTextEditor.document.positionAt(match.index+2);
			var decorationSpacing = { range: new vscode.Range(startPosSpacing, endPosSpacing),hoverMessage:null};
			spacing.push(decorationSpacing);
        }
        this.decorationSpacing = vscode.window.createTextEditorDecorationType({
            letterSpacing: '-2px'
        });	
		vscode.window.activeTextEditor.setDecorations(this.decorationSpacing, spacing);
    });
```

Just add `aaaaa` in the document. I'm using vscode 64bits on windows.
Maybe I'm doing something wrong.

**Comment by Alphapage** [comment]
@alexandrudima : any news about this problem ? Is it a `Windows` problem only or is it a bug because of my code ?

**Comment by alexandrudima** [comment]
Full repro steps:
* `package.json`:
```json
{
    "publisher": "alex",
    "name": "35574",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	var regEx = /(?:aaaa)(.*\n{0})/g;
	var text = vscode.window.activeTextEditor.document.getText();
	var spacing = [];
	var match;
	while (match = regEx.exec(text)) {
		var startPosSpacing = vscode.window.activeTextEditor.document.positionAt(match.index);
		var endPosSpacing = vscode.window.activeTextEditor.document.positionAt(match.index + 2);
		var decorationSpacing = { range: new vscode.Range(startPosSpacing, endPosSpacing), hoverMessage: null };
		spacing.push(decorationSpacing);
	}
	this.decorationSpacing = vscode.window.createTextEditorDecorationType({
		letterSpacing: '-2px'
	});
	console.log(`setting to: `, spacing);
	vscode.window.activeTextEditor.setDecorations(this.decorationSpacing, spacing);
}

```

* `demo.txt`:
```
aaaaaaaaaaaaa
```

Repro:
![kapture 2018-02-02 at 17 13 51](https://user-images.githubusercontent.com/5047891/35742987-7b3a3fa0-083c-11e8-9231-a0415f555e8c.gif)

**Comment by Alphapage** [comment]
I tested on the april update and the letter spacing is working as expected now. 👍 
Thank you very much from "maybe" the only guy who is using this feature!
