### ISSUE TITLE
Rename (refactor) parameter object doesn't rename the shape declaration

### ISSUE THREAD

**Issue by bill-mybiz** [Microsoft/vscode#3557]
I have the following code:
```
 getExistingThing({
        id, 
        spaceId
    }: {
        id: string, 
        spaceId: string
    }): IThingInfo {
   // Use the params object here with destructuring...
}
```

When I tried to refactor `id` to `thingId`, it renamed it correctly in the parameter object variable and the symbols in the function body, but it did not rename it in the "shape" of the parameter object (I don't know what else to call it).

Expected:
```
    getExistingThing({
        thingId,
        spaceId
    }: {
        thingId: string, <<< should change here
        spaceId: string
    }): IThingInfo {
```

Got: 
```
    getExistingThing({
        thingId, 
        spaceId
    }: {
        id: string, <<< doesn't change though
        spaceId: string
    }): IThingInfo {
```

I would also love it if someone could tell me what the various parts of this kind of function declaration is called. I use it for named arguments which I love, but I just don't know what the various pieces are called. I just know it's awesomeness.

(VS Code version 0.10.8)

**Comment by bill-mybiz** [comment]
Also it fails in the reverse as well. If I perform the refactor on the shape declaration, it does not change the corresponding symbols in the parameter object, nor in the function body.

**Comment by bill-mybiz** [comment]
Ah, This apparently is a TypeScript problem and not a VS code problem, which is why I couldn't find it:

https://github.com/Microsoft/TypeScript/issues/6312

**Comment by rob3c** [comment]
Yep, this is certainly annoying. I think it's root cause is related to issue #6459 that I created,  #6312 that my issue was close enough to label as 'duplicate', as well as other issues it's connected to.
