### ISSUE TITLE
Open Editors: bad icon flash when hovering with icons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35584]
Maybe a regression from @joaomoreno split view work?

![panel-red](https://user-images.githubusercontent.com/900690/31186833-1a9b2f1c-a930-11e7-95b3-1eb6c5b52dc3.gif)

**Comment by bpasero** [comment]
I can reproduce in stable candidate, I think we should fix this.

**Comment by joaomoreno** [comment]
On it.
