### ISSUE TITLE
Error when I open integrated terminal on macOS

### ISSUE THREAD

**Issue by kevinb22** [Microsoft/vscode#35587]
- VSCode Version: 1.16.1
- OS Version: 10.12.6 (Sierra)

Error: The terminal process command `/bin/false -l` failed to launch (exit code: 1)

Steps to Reproduce:

1. Open integrated terminal
2. Verify that error pops up at top of the screen.

Workaround:
Seems that /bin/false wasn't a file on my computer. There was /usr/bin/false, but using that path in settings still gave the same error.
 
In the end I overwrote the default settings for the integrated terminal to be "terminal.integrated.shell.osx": "bash" and then it launched as normal.

Reproduces without extensions: Yes

Related Issues?:
https://github.com/Microsoft/vscode/issues/14528
https://github.com/Microsoft/vscode/issues/14768

**Comment by Tyriar** [comment]
This happens in some enterprise environments when they change `$SHELL` to `/bin/false` to try to prevent usage. You can try adding this to your settings:

```js
"terminal.integrated.shell.osx": "/bin/bash"
```

If that doesn't work I suggest contacting your sysadmin.
