### ISSUE TITLE
Non-documented required ordering of breakpoints in setBreakpoints response

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#3558]
Our extension for PowerShell doesn't always return the breakpoints in the response in the same order they were sent in the request e.g.:
```
    READ MESSAGE:
    
    {
      "type": "request",
      "seq": 19,
      "command": "setBreakpoints",
      "arguments": {
        "source": {
          "name": null,
          "path": "C:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.4.1\\examples\\DebugTest.ps1",
          "sourceReference": null
        },
        "lines": [
          9,
          22
        ],
        "breakpoints": [
          {
            "line": 9,
            "condition": "$i % 10 -eq 0"
          },
          {
            "line": 22
          }
        ]
      }
    }
```
Response:
```
    WRITE MESSAGE:
    
    {
      "type": "response",
      "request_seq": "19",
      "command": "setBreakpoints",
      "success": true,
      "body": {
        "breakpoints": [
          {
            "verified": true,
            "message": null,
            "source": "C:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.4.1\\examples\\DebugTest.ps1",
            "line": 22,
            "column": null
          },
          {
            "verified": true,
            "message": null,
            "source": "C:\\Users\\Keith\\.vscode-alpha\\extensions\\ms-vscode.PowerShell-0.4.1\\examples\\DebugTest.ps1",
            "line": 9,
            "column": null
          }
        ]
      }
    }
```
What I notice in the VSCode UI is that after I add or remove a breakpoint during a debug session, VSCode gets confused about which line my "conditional" breakpoint is on.  Check this out:
![vscodebreakpointbug](https://cloud.githubusercontent.com/assets/5177512/13402498/d063e32c-decd-11e5-861a-2c3a1e1105a0.gif)

Is there an implicit, undocumented (AFAICT) contract that says the requested breakpoints must be returned in the same order.  So far, that's the only thing I can see wrong.  

**Update**: had time to change my code to ensure the breakpoints are returned in the same order as received and this issue goes away.  Seems like that should be documented in the debug protocol - or maybe I'm looking at the wrong file - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L495

**Comment by weinand** [comment]
@rkeithhill yes, the breakpoints returned from the response must be returned in the same order as the breakpoints passed to the request. Otherwise there would be no way to know what response corresponds to what input.

The comment for `SetBreakpointsResponse` says:
"The array elements correspond to the elements of the 'breakpoints' (or the deprecated 'lines') array."

I will make clearer that 'correspond' means: in the same order.

**Comment by rkeithhill** [comment]
Thanks for the clarification.

**Comment by weinand** [comment]
I've changed the comment to this:

```
	/** Response to "setBreakpoints" request.
		Returned is information about each breakpoint created by this request.
		This includes the actual code location and whether the breakpoint could be verified.
		The breakpoints returned are in the same order as the elements of the 'breakpoints'
		(or the deprecated 'lines') in the SetBreakpointsArguments.
	*/
```

**Comment by rkeithhill** [comment]
:+1:
