### ISSUE TITLE
Make "Workspace" and "Folder" settings more discoverable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35580]
We should bring back entries to the File menu for accessing workspace and folder settings.

**Comment by bpasero** [comment]
I am having second thoughts about adding more entries to the File menu and the global action in the activity bar. Imho if we can make the settings editor show the various setting locations in a more prominent way, this might not be an issue anymore:

![image](https://user-images.githubusercontent.com/900690/31531324-b3ec38fc-afe6-11e7-8180-1046720de0a6.png)

**Comment by sandy081** [comment]
Empty
![image](https://user-images.githubusercontent.com/10746682/32942887-a6d8f8fc-cb8a-11e7-9a57-1393afbdd9ac.png)

Folder
![image](https://user-images.githubusercontent.com/10746682/32942910-b5c6521a-cb8a-11e7-8de8-d1cdb289d0cb.png)

Workspace
![image](https://user-images.githubusercontent.com/10746682/32942854-8f41320e-cb8a-11e7-9a26-f018cd68998f.png)

**Comment by bpasero** [comment]
@sandy081 very nice!
