### ISSUE TITLE
Workpace folder: add a command to the context menu to edit folder settings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#35583]
We could surface an action in the context menu of a root folder to open the settings editor for that folder.

/cc @isidorn @sandy081

**Comment by isidorn** [comment]
@sandy081 Do we already have a command that opens the folder settings? If yes I can just stick it in the context menu, if not is there some service which I can call so this file gets opened?

This issue does not have enough tags!

**Comment by sandy081** [comment]
Yes, you can use the command `_workbench.action.openFolderSettings`. This command needs WorkspaceFolder as the argument.

**Comment by bpasero** [comment]
Maybe it could be close to these here:

![image](https://user-images.githubusercontent.com/900690/31229430-ee260a04-a9e0-11e7-817d-524f68512038.png)

**Comment by isidorn** [comment]
![screen shot 2017-10-05 at 15 52 26](https://user-images.githubusercontent.com/1926584/31230757-470d3fd0-a9e5-11e7-9499-b91312dac402.png)
