### ISSUE TITLE
Editor Automatically Highlights Commented Code With jQuery

### ISSUE THREAD

**Issue by infinisuite** [Microsoft/vscode#35597]
- VSCode Version:  1.16.1 (1.16.1)
- OS Version:  OSX 10.12.6 (16G29)

Steps to Reproduce:
1. Paste this code into an open TypeScript file in the editor. 
2. Move the mouse over any commented code that contains a parenthesis. The entire block will automatically highlight. When additional code is present all code above the comment within the inner block is also highlighted. Moving the mouse off of the comments returns the editor to normal. This happens constantly when using resolved jQuery promises and is very distracting. It appears to have something to do with the presence of the  'fail' block.

```
export function test() {

    $.Deferred().resolve()
        console.log('test')
        // let data: any[] = []
        // _boDetail.forEach(() => {   // <------------- MOUSEOVER HERE
        //     data.push({
        //     })
        // })
        .fail(() => {
        })
}
```

Reproduces without extensions: Yes

**Comment by infinisuite** [comment]
Using jQuery  v1.12.3.

**Comment by infinisuite** [comment]
I was able to reproduce this without extensions.

**Comment by infinisuite** [comment]
Here's a better example:

```
$.Deferred().resolve()
    .then(() => {
        console.log('test1')
        return $.Deferred().resolve()
    })

    // *********************************************************
    // MOUSEOVER ANYTHING IN THIS COMMENT
    // *********************************************************
    .then(() => {
        console.log('test2')
        return $.Deferred().resolve()
    })
```

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/19984 to track this upstream
