### ISSUE TITLE
Feature Request: Add API to refresh various debugger panes

### ISSUE THREAD

**Issue by Tenebrous** [Microsoft/vscode#35598]
I'm writing a debug adapter, and there are some events that can happen outside of the normal process that result in vscode not reflecting the correct state.

**Variables**
Sometimes when setting a variable, other variables change in response.  For example, in the image below the HL register is made up of H and L.  Changing HL also changes H & L.  Changing H or L individually also changes HL.

![image](https://user-images.githubusercontent.com/593662/31198523-84845ec8-a94c-11e7-8e71-e3780e4744e9.png)

**Call Stack**
I've implemented a 'Set Next Statement' via vscode.debug.activeDebugSession.customRequest.  However, there's no way to tell vscode to refresh the call stack to reflect the updated state.

**Comment by isidorn** [comment]
If I understood you correctly you are setting a variable in the variables view and the parent / child is not updated. This should be handled automatically by vscode, if it is not then it is a bug (there actually might be already one in our issues).
Our api should not have such specific commands as "refreshVariablesView" imho.

**Comment by Tenebrous** [comment]
@isidorn I agree there should not be a "refreshVariablesView" command. However, there still needs to be a way to tell vscode that the debug state has changed outside of it's control.

Alternatives would be: vscode.debug.variables.refresh(); which would work well if other things had a .refresh().  Alternatively, a generalised vscode.debug.stateChanged();

**Comment by isidorn** [comment]
@Tenebrous not sure I agree, for that we have the debugProtocol.
fyi @weinand 

As for the variables not refershing after setVariable request this is due to this code [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L163) which only refreshes the changed element, not the whole tree

**Comment by Tenebrous** [comment]
@isidorn The debugProtocol doesn't support this either - do you think that would be the preferred method? I implemented a custom debug event over the protocol, but the code on the vscode extension side doesn't have any API in vscode to call to do the refresh.

**Comment by Tenebrous** [comment]
Actually I have discovered I *can* force a refresh by sending the debug protocol event 'continued' followed immediately by 'stopped'.

**Comment by isidorn** [comment]
Closing because we are not planning to implement this within the next 12 months.
