### ISSUE TITLE
Feature Request: Configuration to force documentation popup below current line.

### ISSUE THREAD

**Issue by chriseppstein** [Microsoft/vscode#35596]
Following up from a twitter conversation with @auchenberg yesterday:
https://twitter.com/auchenberg/status/915370598871662592

- VSCode Version: 1.16.1
- OS Version: Mac OSX 10.12.6 (16G29)

Steps to Reproduce:

1. write code (in vim mode if that matters)
2. press `(`.
3. Get popup above current line.
![stylemapping ts template-api 2017-10-04 12-46-08](https://user-images.githubusercontent.com/1839/31196314-2bf5697c-a902-11e7-964d-51fafb211c3c.png)
4. Be sad that you can't see the code you just typed and now need to use as an argument to the current function call.

I'd like to be able to force this popup to be underneath my current line of code (especially when triggered by typing -- it's not that important when displayed via a mouse interaction).

Other possible config options or solutions might be to have the pop up displayed in a fixed location when triggered by typing (E.g. the upper right corner of the editor window) because sometimes I need to refer to the code below as well :)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/33752
