### ISSUE TITLE
C# folding error

### ISSUE THREAD

**Issue by laimonas** [Microsoft/vscode#3559]
Windows 10
![untitled](https://cloud.githubusercontent.com/assets/870178/13402637/d6963e92-df19-11e5-9817-56724b20ebb1.png)

**Comment by joaomoreno** [comment]
Codelens rendering cheese

**Comment by alexandrudima** [comment]
@aeschli It is not clear to me what I should do -- should I try to hide all content widgets inside hidden areas?

**Comment by aeschli** [comment]
@alexandrudima Looking at the other use cases of the ContentWidget (hover, parameter hints, lightbulb, rename, suggest), it seems to me that a content widget attached to a hidden position should never be shown.

Alternately we could add an API to ask for hidden lines. The code lense could skip the computation and visualization of hidden elements. We would also need a hidden lines event listener.

**Comment by chrisdias** [comment]
@alexandrudima this looks bad, do we need to fix for Feb 2016 release?

**Comment by chrisdias** [comment]
also note that when i fold and unfold all the code lenses are not being restored to the correct location, resulting in overlap with comments (in the case below, in the picture) and phantom blank lines.

![image](https://cloud.githubusercontent.com/assets/1487073/13429203/60dbd396-dfbf-11e5-8423-181af2eb92d5.png)
