### ISSUE TITLE
Error updating on Windows

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#3560]
I am getting an error trying to update to the new 0.10.10 release on Windows.

I received the notification, clicked on "update and restart" and it showed this error:

![errorupdatevscode](https://cloud.githubusercontent.com/assets/199648/13404671/1877ddec-df1b-11e5-8ab1-46d7ecdd470f.png)

Pressing "start again" shows the same error, cancel roll backs the install.

**Comment by warpdesign** [comment]
With process explorer I was able to find which app locks the file:

It is a git process that. The thing is I have not git running right now, although I ran some git commands earlier.

**Comment by joaomoreno** [comment]
Sorry for that, glad you caught the culprit!

**Comment by warpdesign** [comment]
@joaomoreno I think you were too fast in closing this issue.

Today I had the same error on another computer.

Since I knew I could have the same problem, here is what I did:

 1. Visual Code for Insiders wasn't running so I checked if there was a sh/git process: there was none
 2. I started Visual Code for Insiders which loaded an empty workspace: again, there was no sh/git process
 3. I then opened a directory containing a git project and checked again: now there was a git process, which had been started from the directory I just opened
 4. I received the update, and clicked on "restart and update"
 5. I got the same error

It seems the git process is started by Visual Code, but isn't properly stopped when Visual Code is quitted and the update process is started.

**Comment by warpdesign** [comment]
More information..

Here is the exact command line that was started:

`"C:\Program Files (x86)\Git\bin\sh.exe" "c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\parts\git\electron-main\askpass.sh" "Password for 'https://warpdesign@bitbucket.org': "` (from Process Explorer)

**Comment by joaomoreno** [comment]
Agreed!

**Comment by shadowii** [comment]
I had the same issue. I did a clean OS restart before attempting the update as well, but that didn't help. I eventually had to uninstall Code first, and then manually clear out the old folder before the install would work.

**Comment by ashclarke** [comment]
I've had this issue on the last two updates. I, too, had to end a couple of idle git.exe processes.

**Comment by joaomoreno** [comment]
This has been mitigated since. I'll reopen if reports that it continues open come.

**Comment by fractos** [comment]
Just had this occur with latest update, same file (askpass.sh)

**Comment by fractos** [comment]
Just happened again with an update today.

**Comment by johntiger1** [comment]
had it happen today

**Comment by johntiger1** [comment]
What I did was terminate all `Code.exe` processes and then I was able to delete the Program folder and do a clean install
