### ISSUE TITLE
Cntrl click on an object reference in a TS file, takes ~17 seconds to open the file

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vscode#35603]
- VSCode Version:  1.16.1 64 bit (although this was happening on 32 bit)
- OS Version:

 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows

Steps to Reproduce:
1.  When I click on a reference to an object, it takes almost 20 seconds for the file to open up
 For example:  
 I have this contructor:
```
constructor(private seasonsService: SeasonsService) {
  }
```
When I cntl click on SeasonsService, it will take 17 seconds to open up seasons.service.ts file.

This happens on more than one project.    It used to work fine and not sure what would be causing this.

It may be worth noting here that Intelliense in C# stopped working too but TypeScript typed objects still get intellisense.  I logged an issue with the C# extension but that seems much different than the issue I stated here.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Possible related to https://github.com/Microsoft/TypeScript/issues/16329

1. Do you have a `tsconfig.json` and are both files part of this project? You can check this by running `TypeScript: go to configuration` in vscode for each file. This command should open up the `tsconfig`

2. Also can you please try updating to VSCode 1.17 and installing the latest TypeScript 2.6 dev build in your workspace by running` npm install typescript@next` and following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if fixes the issue

**Comment by jrmcdona** [comment]
The answer to #1 was yes to both.  

In the end it seemed to resolve itself.  Will keep an eye on it for bad behavior/  

Thanks
