### ISSUE TITLE
auto build is not working on ubuntu

### ISSUE THREAD

**Issue by anfasci** [Microsoft/vscode#35609]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-89-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-spell-checker|str|1.4.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Which language is this? Would expect it to automatically build when starting the debugger?

Could you post your `launch.json` and `tasks.json` here?
