### ISSUE TITLE
Marketplace misses Insider protocol links to install extensions

### ISSUE THREAD

**Issue by colemickens** [Microsoft/vscode#35604]
- VSCode Version: Code - Insiders 1.17.0-insider (f6ef4bef42fa2948426c99fefa340235e67a0c5e, 2017-10-04T17:40:56.306Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
vscode-markdownlint|Dav|0.10.1
json-tools|eri|1.0.2
git-project-manager|fel|1.4.0
beautify|Hoo|1.1.1
ftp-sync|luk|0.3.3
Go|luk|0.6.66
prettify-json|moh|0.0.3
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-docker|Pet|0.0.18
rust|rus|0.3.0
vscode-helm|tec|0.3.0
json2yaml|tux|0.2.0
debug|web|0.21.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Go to VS Code Marketplace. For example: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
2. Click the install button
3. Realize there's nothing registered for `proto:` urls.
4. Wonder why the old `ext install ...` command help text box is completely gone.
5. Check Windows settings and indeed see that nothing is registered for `vscode`.

![demo 1](https://user-images.githubusercontent.com/327028/31207897-e70b2336-a935-11e7-8293-449dccfdf6fb.png)

**Comment by joaomoreno** [comment]
There used to be an experience for installing extensions for Insiders...

**Comment by joaomoreno** [comment]
@colemickens Can you at least confirm you have the `vscode-insiders` protocol in the registry?

```
[HKEY_CLASSES_ROOT\vscode-insiders]
"URL Protocol"=""
@="URL:vscode-insiders"

[HKEY_CLASSES_ROOT\vscode-insiders\shell]

[HKEY_CLASSES_ROOT\vscode-insiders\shell\open]

[HKEY_CLASSES_ROOT\vscode-insiders\shell\open\command]
@="\"C:\\Program Files (x86)\\Microsoft VS Code Insiders\\Code - Insiders.exe\" --open-url \"%1\""
```

**Comment by joaomoreno** [comment]
Work is done on our side. Update comes next month.
