### ISSUE TITLE
Possible UI bug with iMac 2012 on MacOS High Sierra?

### ISSUE THREAD

**Issue by BruceHem** [Microsoft/vscode#35605]
I'm getting these weird UI bug... I don't know if it's my iMac or VsCode or some other factors?

Anyone running into this problem?

![screen shot 2017-10-05 at 8 50 29 am](https://user-images.githubusercontent.com/15667259/31207796-9967b232-a9aa-11e7-8875-dc1784562e1e.png)

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/35527 but we have not yet figured out what this is nor being able to reproduce.
