### ISSUE TITLE
Feature Request:push shift+enter  to go to the next line like PyCharm

### ISSUE THREAD

**Issue by songzhi** [Microsoft/vscode#35607]
In PyCharm,if you press shift+enter ,then you just go to the next line without minding the last chars in the former line.
This will be convnient if you type a pair of  brackets,and you've typed something.You want to go to the next line.By now,you should do a move forward and press enter .while shift+enter is just more direct.
I don't know if VSCode already has the feature.if it has,please tell me how to turn it on.

**Comment by shizengzhou** [comment]
You can try to press ctrl+enter

**Comment by songzhi** [comment]
Thank you very much!
It's a stupid question...
LOL
