### ISSUE TITLE
Add help/usage flags for CLI code command

### ISSUE THREAD

**Issue by ctrlrsf** [Microsoft/vscode#3561]
vscode supports a few CLI arguments but there's no --help, -h, or even a /? flag that prints help/usage information to look them up from command line.

List of additional CLI arguments supported according to docs:
https://code.visualstudio.com/Docs/editor/codebasics#_additional-command-line-arguments

On OSX calling `code --help`, `code -h`, or even `code /?` just opens the editor and doesn't print any helpful information.

**Comment by bpasero** [comment]
@Tyriar fyi

**Comment by Tyriar** [comment]
`--help` is being added in Feb release https://github.com/Microsoft/vscode/pull/2650

I wasn't actually aware of the doc page you linked, I've created a new issue to add the remaining aommand line args for the March release https://github.com/Microsoft/vscode/issues/3565. Thanks!
