### ISSUE TITLE
macOS High Sierra Code Helper intensive CPU usage

### ISSUE THREAD

**Issue by elias-garcia** [Microsoft/vscode#35614]
- VSCode Version: 1.16.1
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. Open the VSCode.
2. Open a project.

Activity Monitor screenshot:
<img width="796" alt="captura de pantalla 2017-10-05 a las 10 02 58" src="https://user-images.githubusercontent.com/6737805/31216623-90b6e6b2-a9b4-11e7-939c-074e7bdc969f.png">

Opened files by the process:
<img width="1920" alt="captura de pantalla 2017-10-05 a las 9 39 31" src="https://user-images.githubusercontent.com/6737805/31216604-7ef4a48c-a9b4-11e7-9c64-d60234970a8d.png">

`ps -p` and `ps aux` commands outputs:
<img width="961" alt="captura de pantalla 2017-10-05 a las 10 02 27" src="https://user-images.githubusercontent.com/6737805/31216610-821768a2-a9b4-11e7-961d-dd72cdf72f83.png">

**Comment by chrmarti** [comment]
@elias-garcia How many times have you seen this? Does it always occur? Could you list the extensions you have installed here (`code --list-extensions`)? There are several fixes in the upcoming 1.7 release, please try that when it is out and let us know if that improves things.

**Comment by elias-garcia** [comment]
@chrmarti Yes, every day to me since I update to macOS High Sierra. Ok, I'll wait and give it the 1.7 version a try and get back to this issue if this problem persists, thanks!

By the way, here is the output of the `code --list-extensions` command:

***
Angular.ng-template
CoenraadS.bracket-pair-colorizer
EditorConfig.EditorConfig
PKief.material-icon-theme
akamud.vscode-theme-onedark
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
eg2.tslint
formulahendry.auto-rename-tag
joelday.docthis
johnpapa.angular-essentials
johnpapa.Angular2
minhthai.vscode-todo-parser
msjsdiag.debugger-for-chrome
natewallace.angular2-inline
ritwickdey.live-sass
ritwickdey.LiveServer
wayou.vscode-todo-highlight
***

**Comment by datysho** [comment]
The same problem.

code --list-extensions
```
CoenraadS.bracket-pair-colorizer
EditorConfig.EditorConfig
Gruntfuggly.activitusbar
HookyQR.beautify
Mikael.Angular-BeastCode
PKief.material-icon-theme
RoscoP.ActiveFileInStatusBar
WallabyJs.quokka-vscode
aaron-bond.better-comments
akamud.vscode-theme-onedark
alefragnani.Bookmarks
alefragnani.project-manager
alexiv.vscode-angular2-files
christian-kohler.path-intellisense
donjayamanne.githistory
donjayamanne.python
eamodio.gitlens
ecmel.vscode-html-css
eg2.tslint
expixel.vscode-eval
formulahendry.auto-rename-tag
huizhou.githd
iceliu.highlight-icemode
infinity1207.angular2-switcher
ionutvmi.path-autocomplete
jakethashi.vscode-angular2-emmet
k--kato.intellij-idea-keybindings
letrieu.expand-region
natewallace.angular2-inline
ow.vscode-subword-navigation
patrys.vscode-code-outline
qezhu.gitlink
rbbit.typescript-hero
robertohuertasm.vscode-icons
rokoroku.vscode-theme-darcula
ryu1kn.partial-diff
sleistner.vscode-fileutils
smlombardi.darcula-extended
steoates.autoimport
trinm1709.dracula-theme-from-intellij
vangware.dark-plus-material
vscodevim.vim
wmaurer.change-case
zhuangtongfa.Material-theme
```

**Comment by chrmarti** [comment]
@datysho Is this High Sierra too?

1.17 is out, could you both give that a try?

**Comment by elias-garcia** [comment]
I've just updated it. Will give it a try this days and post any news here!

**Comment by datysho** [comment]
@chrmarti yes, I have tried with macOS High Sierra, and both versions of vscode 1.16 and 1.17.

**Comment by lainekendall** [comment]
This is also happening to me. I have macOS Yosemite 10.10.3 and have tried 1.15, 1.16, 1.17 and all have frozen. Code Helper is at 100%+ CPU usage.

**Comment by roblourens** [comment]
@lainekendall Can you use `ps aux` to determine which Code Helper process is using high CPU? And check whether it reproes when launching with `--disable-extensions`?

**Comment by elias-garcia** [comment]
Hi! This issue is gone for me with the 1.17 version.

**Comment by chrmarti** [comment]
@elias-garcia Thanks! Is this the case for everyone else too?

**Comment by datysho** [comment]
@chrmarti I found the problem. I have a huge project (1,236,721,303 bytes (1.44 GB on disk) for 74,934 items). So it seems like vscode are frozen every time when I open a file from unindexed folders. Every time when I restart the editor and do it again, freezes are coming.

**Comment by chrmarti** [comment]
@datysho Could you open a new issue for that using Help > Report Issues and /cc me? That sounds like different problem.

**Comment by datysho** [comment]
@chrmarti I think this is the same problem because my problem is complemented by high CPU usage of Code Helper process.

**Comment by jrotenstein** [comment]
I never experienced this problem before, but now it is happening since upgrading to 1.17.

**Comment by elias-garcia** [comment]
Hi, the issue is back in the latest VSCode version (1.17.2)

<img width="799" alt="captura de pantalla 2017-10-18 a las 12 54 19" src="https://user-images.githubusercontent.com/6737805/31715330-af8d776e-b403-11e7-9716-2f8926eabefd.png">

Before the CPU usage dramatically increaseses, the VScode stops working normally (my tab key wasn't working, I can only use spaces for example).

**Comment by elias-garcia** [comment]
I've uninstalled and reinstalled the VSCode and it's happening all the time with the new version. Suddenly, the IDE help stop workings and the CPU usagre increases to <100%.

When it happens I've seen that at least these features stops working:

- Autocompletion when editing the user config.
- Indentation.
- Autoformat on save.

**Comment by roblourens** [comment]
Is it still the searchService process, as shown by `ps` originally? Is it possible that it's a different service? If it's affecting those language features, then it seems more likely to be related to the language server extension.

**Comment by elias-garcia** [comment]
These are the outputs for the `Code Helper` process:

<img width="997" alt="captura de pantalla 2017-10-19 a las 10 03 54" src="https://user-images.githubusercontent.com/6737805/31760451-ffc397de-b4b4-11e7-9246-435d98290ddc.png">

And these are the outputs for the `Code` process:

<img width="990" alt="captura de pantalla 2017-10-19 a las 10 01 01" src="https://user-images.githubusercontent.com/6737805/31760470-10d6b470-b4b5-11e7-8008-38ca98b027ea.png">

**Comment by chrmarti** [comment]
If you see Code Helper with `--type=searchService` taking a lot of CPU in 1.17, could you try the current insiders? That comes with a few additional fixes and it would be great to know if these cover the issues you see. (Download insiders builds: https://code.visualstudio.com/insiders/)

**Comment by roblourens** [comment]
Seems that it is the extensionhost process in that first case @elias-garcia so that would be a different issue. Looks like the procs in the other screenshots are not using lots of CPU.

**Comment by elias-garcia** [comment]
I've just downloaded the insiders preview. I'll give it a try this days and get back here to post the results @chrmarti . Yes @roblourens , it seems to be something related to the extensions. Should I open a new issue or what? Anyway, I'll give the current insiders a try and post here the results.

**Comment by roblourens** [comment]
Yeah you can open a different issue for the extensionHost. If you can figure out which extension it is, you can open an issue on their repo.

**Comment by anthonyholmes** [comment]
This worked for me:

- Close all opened tabs
- In command palette "Clear Editor History"
- Close all windows
- Restart VS Code

**Comment by cideM** [comment]
Is this closed because it's a duplicate? Because @anthonyholmes answer doesn't solve anything. The high CPU usage eventually just recurs.

**Comment by roblourens** [comment]
@cideM There are a lot of things that can cause that kind of issue - you should open a new issue and check out https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide as much info as possible.

**Comment by jrotenstein** [comment]
I traced my performance issue to the Git Auto-fetch function, which was taking a long time fetching numerous remote repositories.

Fixed by adding this to my settings:

     "git.autofetch": false
