### ISSUE TITLE
Cannot open two instance from folder it worked till now. i am now sure what is problem

### ISSUE THREAD

**Issue by top1st** [Microsoft/vscode#35618]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|0.1.1
vscode-npm-script|eg2|0.2.1
cpptools|ms-|0.13.0
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
I don't quite understand, could you attach a screenshot? Are you trying to open two windows with the same folder?
