### ISSUE TITLE
Conflict resolution options do not show up for files with conflicts starting from line 1

### ISSUE THREAD

**Issue by sushruth** [Microsoft/vscode#35628]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-svn|eli|0.1.0
vscode-insertdatestring|jsy|2.1.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a conflicted file where conflict starts in the first line

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Could you post an example / screenshot?
