### ISSUE TITLE
Missing tooltip for Source Control

### ISSUE THREAD

**Issue by PeterVersteege** [Microsoft/vscode#35623]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-c-al|zod|0.0.11

---

Steps to Reproduce:

1. Look at left Activity Bar
2. Go to third icon, tooltip is missing

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Strange... I can see it here. Does it always reproduce for you?

![image](https://user-images.githubusercontent.com/22350/31271453-dc9fab80-aa87-11e7-9082-ef8b51ac1e19.png)

**Comment by PeterVersteege** [comment]
Hi Joao,

I only installed Visual Studio Code 2 days ago, for your information I am using version 1.16.1
Today I tried again, and it doesnot show this tooltip, all the other tooltips are shown correctly.

Best regards,

Peter Versteege
Developer / Consultant | Global Accounts

[cid:image005.jpg@01D298EC.66A8FBA0]<http://www.k3retail.com/>

M   +31 (0)6 52 03 80 56
T    +31 (0)15 251 65 55
find us<http://k3retail.com/>  |  k3retail.com<http://k3retail.com/>  |  linkedin<https://www.linkedin.com/company/k3-retail-nederland>  |  twitter<https://twitter.com/k3retailNL>  |  facebook<https://www.facebook.com/k3retailNL>  |  youtube<https://www.youtube.com/channel/UCBKOw2Gz0itifu4Y49_1KyQ>

The Netherland ICT Terms and Conditions are applicable on all our offers and agreements. These conditions can be found here<http://www.k3retail.com/nl/nederland-ict-voorwaarden/>. The Terms and Conditions used by our contractual party are hereby excluded.
K3 Retail is a trading name for K3 Business Solutions with number 27244554. K3 Business Solutions B.V. is part of the K3 group of companies which is owned by K3 Business Technology Group PLC registered in England and Wales, Company number 02641001, at Baltimore House, 50 Kansas Avenue, Manchester M50 2GL. Confidentiality: This email is confidential and intended for the use of the individuals to whom it is addressed. If you are not the intended recipient, or you have received this email in error, then any use or forwarding of this email is not allowed. If you have received this email in error please notify the sender and then delete it. Content: Any views or opinions presented are solely those of the author and do not necessarily represent those of K3 Retail Solutions Limited. Security: Internet email is not a secure communication and you accept this lack of security when emailing K3 Retail Solutions Limited. We have taken steps to ensure this email is virus free but you should ensure it is actually virus free in accordance with good computing practice.


Van: João Moreno [mailto:notifications@github.com]
Verzonden: vrijdag 6 oktober 2017 11:18
Aan: Microsoft/vscode <vscode@noreply.github.com>
CC: Peter Versteege <peter.versteege@k3retail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Microsoft/vscode] Missing tooltip for Source Control (#35623)


Strange... I can see it here. Does it always reproduce for you?

[image]<https://user-images.githubusercontent.com/22350/31271453-dc9fab80-aa87-11e7-9082-ef8b51ac1e19.png>

**Comment by joaomoreno** [comment]
Can you record a screencast showing all the tooltips minus the SCM one?
