### ISSUE TITLE
VS Code Auto Fetch Improvements

### ISSUE THREAD

**Issue by d3x0r** [Microsoft/vscode#35625]
https://github.com/Microsoft/vscode/issues/20294  SSH connections with VS Code put my IP address on a blacklist (too many failed logins) 
https://github.com/Microsoft/vscode/issues/8469 Autofetch should be disable by default

It is destructive when the git repo is an ssh link, and vscode doesn't prompt for credentials, so it just causes blacklisting from too many invalid ssh logins.
I was working remotely on a system, and suddenly in the middle of editing things the connection dies.  (it is a remote asking for a fetch from my server, which blacklisted the remote I was working on).

It(vscode) should at least check to see the repository origin url is ssh or not.
Yes, setting (git.autofetch configuration flag set to false) this now stops the issue which happened 3 times, fortunately 2 of the times I wasn't in the middle of typing.

**Comment by joaomoreno** [comment]
#34684
