### ISSUE TITLE
[typescript] dom definitions not up to date

### ISSUE THREAD

**Issue by yukulele** [Microsoft/vscode#35620]
- VSCode Version: 1.16.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

* Create this code in typescript file
```typescript
const elm = document.createElement('main')
```
* `elm` is typed as `HTMLElement` instead of `HTMLMainElement`

`lib.dom.d.ts` is not up to date

how to update it without wait for vscode update ?

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19040
