### ISSUE TITLE
Bring back the Orange Insider Icon...

### ISSUE THREAD

**Issue by johnwildes** [Microsoft/vscode#35629]
I thought the Orange / Sketched look icon was really neat for an "Insider" build of VS Code....I think you should replace the green icon with the orange one again.  

I see that green is back for 1.17.0.  I'm not going to stop running the insider build because of an Icon, but thought the other one looked better.

- VSCode Version: Code - Insiders 1.17.0-insider (f6ef4bef42fa2948426c99fefa340235e67a0c5e, 2017-10-04T18:44:49.174Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.3.0
vscode-markdownlint|Dav|0.10.1
xml|Dot|1.9.2
php-debug|fel|1.11.1
phpcs|ika|0.7.0
azure-functions-tools|joh|0.3.1
windowsiot|ms-|0.0.20
mssql|ms-|1.2.0
vscode-ai|ms-|0.1.1
azurecli|ms-|0.3.0
cpptools|ms-|0.13.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-azureextensionpack|ms-|0.0.6
wordcount|ms-|0.1.0
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
usql-vscode-ext|usq|0.2.4
application-insights|Vis|0.4.1
azure-iot-toolkit|vsc|0.2.3
vscode-arduino|vsc|0.2.7

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrisdias** [comment]
Please see: https://github.com/Microsoft/vscode/issues/6607#issuecomment-334600845
