### ISSUE TITLE
split terminal view , to have both angular logs and nodejs 

### ISSUE THREAD

**Issue by jhonyourangel** [Microsoft/vscode#35627]
i would love to be able to split also the terminal. i develop angula.io and nodejs server side, will be nice to see both of them 

- VSCode Version: latest
- OS Version: high siera

Steps to Reproduce:

1.none
2.none

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7504
