### ISSUE TITLE
Typescript is failing to start and error keeps showing at top of VS Code IDE

### ISSUE THREAD

**Issue by jzapantis** [Microsoft/vscode#35624]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Could you post the message or a screenshot here?

**Comment by jzapantis** [comment]
Hi thank you for the response, I just built a new application with Angular CLI and merged changes, and it worked. Easier than troubleshooting configurations! Sorry for not responding sooner, thank you for your time and consideration.
