### ISSUE TITLE
File Change Detection Should be less sensitive; match to saved file

### ISSUE THREAD

**Issue by jdhines** [Microsoft/vscode#35622]
VS Code thinks the file has changed when anything has been typed, regardless of whether the change has been reversed. So it thinks it needs to be saved (and pops up the "Do you want to save changes" message), even if the file is technically the same as the last-saved version. In contrast, the [Atom](https://atom.io/) editor (which I'm trying to migrate to VS Code from) actively diffs file so that no matter what you've typed, if you undo back to the state of the last save, it detects that no material changes were made, and you can just close the file without any further interruption.

- VSCode Version: 1.16.1
- OS Version: OS X El Capitan (10.11.6)

**Steps to Reproduce:**
1. In any file, type a character.
2. Delete the character you just typed, returning the file to its previous state.
3. In the explorer and the file's tab, the changed dot is still present, and trying to close the file gives the "Do you want to save changes" box, even though the file hasn't really changed.

**Reproduces without extensions:** Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
