### ISSUE TITLE
peekViewResult Tokens Bug

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#35631]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-npm-script|eg2|0.2.1
mssql|ms-|1.2.0
debugger-for-chrome|msj|3.3.1
code-settings-sync|Sha|2.8.3
guides|spy|0.8.4

(1 theme extensions excluded)

The following theme tokens do not work:
- `peekViewResult.fileForeground`
- `peekViewResult.lineForeground`

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/31272101-095392a2-aa8a-11e7-9cec-d8098677725b.png)
