### ISSUE TITLE
Preference to disable Recently Opened Files

### ISSUE THREAD

**Issue by quicksnap** [Microsoft/vscode#35637]
- VSCode Version: 1.16.1
- OS Version: OSX

I personally have no need for recent files to be promoted to the top of the Goto File results: 

![6xjw-kiw](https://user-images.githubusercontent.com/1199742/31247619-03a204a2-a9c6-11e7-98f2-2bf8385ad616.png)

These results actually slow me down, since I a used to Sublime Text fuzzy match behavior. If the "Recently Opened" results were not there, I would be able to jump to files in a predictable way.

Any preference option I'm missing?

**Comment by iainhenderson** [comment]
Please add an option to disable this, or at least an option to limit 'recent files' to the current project directory.

Several times I've gone to modify common configuration files in my project (like package.json, gulpfile.js) and have wound up modifying the files of the last project I was working on.
