### ISSUE TITLE
Slow go to declaration fo typescript when tsconfig has "paths" 

### ISSUE THREAD

**Issue by amikitevich** [Microsoft/vscode#35630]
- VSCode Version: 1.16
- OS Version: macOs high sierra 10.13

Steps to Reproduce:

add path to tsconfig.json

```json
"paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ],
      "@app/shared/*": [
        "app/shared/*"
      ],
      "@app/core/*": [
        "app/core/*"
      ]
    }
```

Go to declaration very slow. It can take 5-10 second.

Without "paths" in tsconfig go to declaration works incredible fast.

typescript: 2.5.2

Reproduces without extensions: Yes

**Comment by sapjax** [comment]
me too

**Comment by mjbvz** [comment]
Possible related to https://github.com/Microsoft/TypeScript/issues/16329

Can you try installing the latest TypeScript 2.6 dev build in your workspace by running` npm install typescript@next` and following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if fixes the issue

**Comment by sapjax** [comment]
@mjbvz  
I update typescript version to `next`,  and `go to definition`  is became fast now.
Thanks!

**Comment by amikitevich** [comment]
@mjbvz 
I updated vscode, installed typescript dev and it seems to work quicker than before, but without path alias go to declaration still works much faster.

 Much appreciate for your help.

**Comment by mjbvz** [comment]
Thanks for confirming. Closing this as upstream. We plan on picking up TypeScript 2.6 this month #36100. Until then, please try using the nightly TypeScript 2.6 build in your workspace
