### ISSUE TITLE
Improve git partial staging discoverability

### ISSUE THREAD

**Issue by factormystic** [Microsoft/vscode#3563]
In `Git GUI`, you can right click a tracked & changed file and stage just the selected lines, or just the current hunk. It's the UI version of `git add -p` This is extremely useful when splitting up lots of code changes in to several commits. It would be nice to have this partial stage functionality in this app.

**Comment by joaomoreno** [comment]
Well, whad'ya know!

[bug](https://cloud.githubusercontent.com/assets/22350/13421700/40e39210-df90-11e5-80c5-9e72b15296ec.gif)

**Comment by factormystic** [comment]
Okay, I see that there is extremely basic functionality that I missed initially, thank you. However, this highlights additional limitations:

1. obscure, unlabelled menu instead of available via context menu (like git gui) or command palette
1. no "hunk" staging
1. no partial unstage by line/hunk

**Comment by joaomoreno** [comment]
Fair enough

**Comment by tdhsmith** [comment]
Would it be possible to enable a shortcut command for this? For those of us that use the feature frequently, the mouse-menu movement gets pretty tedious. :weary:

**Comment by joaomoreno** [comment]
Absolutely. @isidorn wanna create a global workbench action for this?

**Comment by isidorn** [comment]
I wanted to even put it in the  context menu of the diff view
Yeah I will make this awesome feature more discoverable 🐩

**Comment by factormystic** [comment]
@joaomoreno did this functionality move? I can't replicate your screencap in 1.3.1

**Comment by joaomoreno** [comment]
cc @bpasero, the actions are a bit hidden now

**Comment by bpasero** [comment]
They moved back to the "..." dropdown when tabs are enabled.

**Comment by factormystic** [comment]
Which "..." dropdown? All I see have on the "..." on the tab is "Move left" "Move right" and "Clear all". The "..." dropdown on the git tab has git commands, but nothing related to staging lines in a diff.

**Comment by tdhsmith** [comment]
@factormystic: I just found it: you right-click the _tab header_ of the diff tab and the dropdown includes "Stage Selected Lines". But I confim it's definitely not in the "..." dropdown (which is where they used to be).

If anything the recent update was a regression on the discoverability here. I didn't even know the tabs had their own context menus (or that the diff one would be unique from others) until I became frustrated with the disappearing stage command...

**Comment by chrisdias** [comment]
With the tab work we had to do work on the editor actions location and discoverability. One of the challenges we faced was where to put the editor specific actions in light of having many tabs open, which reduces the amount of space in which to put the actions.  

You can find the discussion here: https://github.com/Microsoft/vscode/issues/7666 and you can try out the current behavior using the [Insiders build](https://code.visualstudio.com/insiders). We would love to get feedback.

All of this this doesn't address this specific issue, but it does start to address the discoverability issues with the editor actions.

**Comment by preslavrachev** [comment]
@joaomoreno thanks for the GIF explanation! The current VSCode still makes committing selected code lines and hunks just as obscure. I wouldn't have gone for the three-dot-menu intuitively had I not known it were there.

**Comment by isidorn** [comment]
This is now a global workbench command -> closing

**Comment by factormystic** [comment]
What are those global workbench commands?

**Comment by isidorn** [comment]
@factormystic that's the list of commands you get after typing `F1`, or `ctrl + p >`

**Comment by factormystic** [comment]
Yes, and what are the partial staging commands, specifically? All I'm seeing that's relevant to this thread is "Stage Selected Ranges" and "Unstage Selected Ranges". Anything else?

Also, it's unclear what types of file views these commands apply to. I tried to use "Unstage Selected Ranges" for a line via the "Source Control: Git" panel, for a file under the "Staged Changes" section, but it had no effect in either the left hand or right hand panels of the diff. Nor did it have any effect in the original  editable file view.

Also, it is not clear if these new palette commands can be attached to a right click menu.

Also, there's still no automatic hunk computation as with `git add -p` and in `git gui`.

**Comment by jpeddicord** [comment]
I appreciate the intent here, but I feel like with each change this is getting less and less discoverable. I can also confirm that while staging a range appears to work, unstaging does not.

**Comment by laggingreflex** [comment]
This would be much more discoverable if it were on the right click context menu. Like it is in the git GUI:

![image](https://cloud.githubusercontent.com/assets/2523987/25481829/a2f75b7a-2b6c-11e7-9732-bf8a255cc08a.png)

**Comment by joaomoreno** [comment]
@laggingreflex Totally agree: #25541

**Comment by factormystic** [comment]
Related: https://github.com/Microsoft/vscode/issues/26642 & https://github.com/Microsoft/vscode/issues/26571

**Comment by factormystic** [comment]
Related: https://github.com/Microsoft/vscode/issues/10782

**Comment by poke** [comment]
With further improvements to partial staging, I would also like the diff view to get some improvements.

Currently, when you look at the changes, you start with a diff between the HEAD version and the working directory. Then, when you stage some changes, that view is not updated, so you still see the changes you just staged as actual changes.

When doing partial staging, the diff view should update to be a diff between the index and the working directory. This would also match what you are going to see once you close the current diff view and reopen it again from the pending changes list. Obviously, the view should also update on every new stage action and not require you to close and reopen it again.

**Comment by shamrin** [comment]
Nobody has mentioned [GitHub Desktop partial commits UI][1] so far. I find it very convenient.

![68747470733a2f2f6769746875622d696d616765732e73332e616d617a6f6e6177732e636f6d2f626c6f672f323031342f626c6f672f6d61632d73656c6563742d62792d6368616e67652e676966](https://user-images.githubusercontent.com/510678/28024785-56f23ff2-659a-11e7-9ab2-e18c0500c34a.gif)

Notice that you can easily select individual lines or the whole hunk with a single click. Or a range of lines by dragging.

(GitHub Desktop also doesn't present staging area concept to the user. I used staging area a lot when I was committing from command line. But now I simply use GitHub Desktop partial commits and - if necessary - undo-commit button. But this is probably too large of a change to suggest here.)

[1]: https://github.com/blog/1816-partial-commits-in-github-for-mac

**Comment by marcohamersma** [comment]
My favourite implementation from [gitup](http://gitup.co/):
![commit2](https://user-images.githubusercontent.com/577144/29663779-c6d81d62-88c4-11e7-845e-21323236d41b.gif)

**Comment by auchenberg** [comment]
https://github.com/Microsoft/vscode/issues/26067

**Comment by SgtPooki** [comment]
I always do git add -p, git reset -p, and git checkout -p as well. I really love vs code's merging functionality (use incoming, use current, etc...) and think that adding links similar to that for staging in the workspace view would be extremely useful.  I used to use the CLI for everything but I have been keeping my workflow within Vs code a lot more lately and would love to be able to do everything within vs code. @auchenberg  that looks pretty good. will continue comments there.

**Comment by jimarcher** [comment]
I'm using version 1.18.0 on a Mac running High Sierra and I just can't make this work, even after spending over an hour trying to figure it out. Right click on the tab does not offer this option, nor do any of the three dot menus.  I see it in the command palette (cmd-shift-p) but it does not work.

If I select a line with the mouse, enter the palette and select "Git: Stage Selected Ranges" there is no indication whatsoever that it did anything. I confirmed it with the command line git tools.

Is this how it's supposed to work or am I doing something wrong?
