### ISSUE TITLE
File Explorer hijacks keyboard focus somehow

### ISSUE THREAD

**Issue by kurtnovack** [Microsoft/vscode#35632]
This has been an issue for me for months now on the insider edition as well as the stable version. I can't narrow down when or why it happens. (I decided to make an issue and see if others have noticed this or can narrow down how to reproduce it. If that's against guidelines this can be removed)

I'll be focused on an actual file and typing in new code will work, but the enter key, arrow keys, and delete will do actions within the file explorer instead of my code. I try hitting escape, spam clicking in the open file to try forcing a focus state change but that doesn't work. The only fix I could find is to open other files then go back to what I was working on. 

- VSCode Version: Code - Insiders 1.17.0-insider (81fc22ec957de26d2bf6aada3f16f04e0164741c, 2017-10-03T22:47:28.178Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
vsc-material-theme|Equ|1.0.4
beautify|Hoo|1.1.1
Angular-BeastCode|Mik|5.0.4
material-icon-theme|PKi|2.2.2
html-css-class-completion|Zig|1.10.0
markdown-preview-github-styles|bie|0.0.4
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
vscode-great-icons|emm|2.1.16
Angular1|joh|0.2.0
Angular2|joh|2.7.0
haml|kar|0.9.0
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.2
Ruby|reb|0.15.0
sass-indented|rob|1.4.2
stylelint|shi|0.29.1
slim|sia|0.1.2
guides|spy|0.8.4
gitblame|wad|2.2.0
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Sadly I can't figure it out why it happens

**Comment by bpasero** [comment]
@kurtnovack did you change your keybindings in any way? Maybe attach the keybindings.json file? And yeah, best if you could find any steps to reproduce.

**Comment by kurtnovack** [comment]
It's empty, so it's just the defaults + the atom keybindings extension. I'll try it without that extension and see if that's somehow messing up.

**Comment by kurtnovack** [comment]
It ended up happening again, so it's definitely not the atom keymaps extension.

here are the console errors:
![screen shot 2017-11-13 at 10 53 11 am](https://user-images.githubusercontent.com/4550817/32734803-0992cf72-c861-11e7-9120-35f0177971cc.png)

I deleted the guides extension and will update if it happens again without that

**Comment by bpasero** [comment]
Does not seem like the error could be related.

**Comment by isidorn** [comment]
@kurtnovack yes the error is not related.
Unfortunately without reproducable steps we can not do anything.
Though I find it very strange if you can reproduce this without any extensions and with no custom keybindings.
