### ISSUE TITLE
[cpp] Put class open brace on new line as you type

### ISSUE THREAD

**Issue by 7654098** [Microsoft/vscode#35640]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
csharpfixformat|Leo|0.0.36
html-css-class-completion|Zig|1.10.0
terminal|for|0.0.10
path-autocomplete|ion|1.6.1
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
mssql|ms-|1.2.0
csharp|ms-|1.12.1
team|ms-|1.122.0
vscode-format|rya|0.0.6

---

I've already spend hours finding how to put open brace to the new line when you type. 

I type this:
`class Foo{`

...and press Enter. I get the closing brace automatically:
```
class Foo{

}
```
But I want this (like VS 2017 did):
```
class Foo
{

}
```

I can do that with format command (Shift + Alt + F), but can I have it automatically?

I've tried different extensions (my lines from in User Settings).

ryannaddy.vscode-format: "format.newLine": { "brace": true }
Leopotam.csharpfixformat: "csharpfixformat.style.braces.onSameLine": false
"editor.formatOnType": true
Omnisharp: { "FormattingOptions": { "NewLinesForBracesIn...": true, } }
All without any success, none of these setting did this formatting on typing.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
You can also try '"editor.formatOnSave"'.

Sounds like a candidate to be added by an extension.

**Comment by 7654098** [comment]
editor.formatOnSave do the right formatting after Cmd + S.

But it would be perfect if braces will put on place of the fly (like VS2017 did)
