### ISSUE TITLE
Exiting code doesn't ask to terminate running task 

### ISSUE THREAD

**Issue by bisaga** [Microsoft/vscode#35643]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.4.1
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
debugger-for-chrome|msj|3.3.1

---

Steps to Reproduce:

1. Create script to run server in package.json
  "scripts": {
    "server": "tsc --watch | nodemon --inspect --watch dist"
  },
2. Create task (using the 2.0.0. compatibility version) and run "server" command which will run corresponding script with node and tsc processes.  
{
    "version": "2.0.0",
    "type": "process",
    "tasks": [
        {
            "type": "npm",
            "script": "server",
            "problemMatcher": [],
            "isBackground": true,
            "promptOnClose": true,
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new"
            }
        }

3. Take "File/Exit" , the code editor close without asking to terminate running task, all node instances remain running and must be killed from the task manager.  

Workaround :
==========
If you create task with the 0.1.0 standard compatibility, everything works as expected. The command is successfully ran and on the exit, editor ask I you wish to terminate running task. If you choose Yes, all node instances and tsc in the "watch" state are successfully terminated. 
{
    "version": "0.1.0",
    "isShellCommand": false,
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "run server",
            "showOutput": "always",
            "command": "npm",
            "args": [
                "run", 
                "server"
            ]
        },

Reproduces without extensions: Yes
Reproduces in 32bit and 64bit version on windows 10

**Comment by dbaeumer** [comment]
This is caused by an unlucky event order which is now hitting since the task service got more lazy. Since the task service now registers after the terminal service I don't execute the code path. I either need better control over these listeners order or the terminal service needs to expose a life cycle event.

**Comment by dbaeumer** [comment]
The terminal does have support to confirm on Exit. You can until we have the right solution in place use `"terminal.integrated.confirmOnExit": true`

**Comment by bisaga** [comment]
I can confirm, the proposed solution works! At the exit the program now again ask if you want to terminate 2 active terminal sessions ... 

Yes, thanks, that is it !

**Comment by dbaeumer** [comment]
See #36845

**Comment by liudonghua123** [comment]
@dbaeumer I tried to set `"terminal.integrated.confirmOnExit": true` in my user's settings. But it did not work as expected.

**Comment by dbaeumer** [comment]
This works for me:

<img width="308" alt="capture" src="https://user-images.githubusercontent.com/1931590/45676265-a15fc580-bb31-11e8-9633-464edc564e31.png">


Any additional steps how to reproduce what you are seeing

**Comment by alexr00** [comment]
I tried out `"terminal.integrated.confirmOnExit"` and it worked as expected. The issue mentioned where an extra process sticks around was fixed, so please let me know if you're seeing that still. Having a separate confirm on exit setting for tasks, or having a per task way to configure that is covered by #36845.
