### ISSUE TITLE
Native tabs not working

### ISSUE THREAD

**Issue by alessandrodimarco** [Microsoft/vscode#35648]
<img width="1224" alt="screen shot 2017-10-05 at 4 39 23 pm" src="https://user-images.githubusercontent.com/8059120/31251623-93f9de0a-a9ec-11e7-9363-4e72fd641b2b.png">
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0 (macOS High Sierra 10.13)
- Extensions: none

---

Unable to view native tabs after recent update. I did a clean install of `vscode` but still not working.

Steps to Reproduce:

1. Set setting `"window.nativeTabs": true`
2. Set `System Preferences` > `Dock` > `Prefer tabs when opening documents: Always`

**Comment by alessandrodimarco** [comment]
Just noticed this. `Note: Native tabs on macOS High Sierra (10.13) are currently only partially supported. We are working on a fix, stay tuned!`

**Comment by bogdansoare** [comment]
same issue here

**Comment by aytacozkan** [comment]
anyone know, when will fix this issue exactly, on october update:?
