### ISSUE TITLE
Create an option to position the intellisense parameter info top or bottom.

### ISSUE THREAD

**Issue by rhyek** [Microsoft/vscode#35647]
This is the same issue as #33752. I do not understand why that issue was closed. It had recent comments in the conversation and no additional information was requested:

Currently the parameter info tooltip is always placed above the cursor. This is often quite annoying since it completely blocks code in the above lines and you sometimes need to look at your context to know what values to give the parameters.

Example:
![image](https://user-images.githubusercontent.com/702922/30005026-e9034dec-9096-11e7-80c0-1a23814ca15c.png)

Note: Once you select a method, the intellisense tooltip is hidden. There is no reason to place the parameter tooltip at the top.

**Comment by joaomoreno** [comment]
#33752
