### ISSUE TITLE
Suggestion: git branch list sorted by most recent commit

### ISSUE THREAD

**Issue by factormystic** [Microsoft/vscode#3564]
Currently it appears that the git branch list is sorted alphabetically. It would be nice if I could get it to sort by most recent commit in the branch, ie, date descending, so that active branches are nearer to the top of the list & stale branches are nearer to the bottom of the list.

**Comment by bbenoist** [comment]
:-1: As I would be personally confused when searching throughout a large branch list.

**Comment by factormystic** [comment]
A large branch list is precisely the scenario where recency is useful. You probably didn't commit to ALL those branches, right? Probably only a couple? Well, now they'd be at the top.

**Comment by bbenoist** [comment]
:information_source: **Tip**
TIL you can sort git branches by most recent commit date with:

    git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)'

> A large branch list is precisely the scenario where recency is useful.

Having a large amout of local branches is not a scenario. It is a common consequence of multiple and different use-cases.

My own use-case is that I not only have to make commits but I also need to review and merge branches into other ones. Sometimes, I have dozens of local branches whose work is in progress and subject to last multiple weeks of frequent updates. **Local** branches I need to checkout are nearly never the most recent and it even tends to be the opposite. Thus, ordering them by recency would be less convenient for me than alphabetically.

> You probably didn't commit to ALL those branches, right? Probably only a couple? Well, now they'd be at the top.

Why would you need local branches if you do not need to commit on them?

I mean, apart from `master` and `develop`, the only branches I keep locally are work in progress.

Once one of my local branch gets reintegrated into our team's repository, I just `git branch -D` it.

**Comment by factormystic** [comment]
> Tip

Yeah, I have something similar as an alias in my gitconfig

> etc

All your comments boil down to "I don't personally find this useful" which is totally okay, but also not really a good reason to prohibit this feature.

I'm perfectly content to have branch sorting as a configuration option that defaults to today's behavior. But it is the kind of thing power users could take advantage of if it was possible.

**Comment by suan** [comment]
👍 As a developer on a large, monolithic repo (heck, we maybe have about 20 devs but it's already alotta branches), there's a ton of local+remote branches and I rely a lot on this as well - makes sense to me to at least make it a configured option.

See also https://github.com/Microsoft/vscode/issues/18231 as evidence for further demand

**Comment by joaomoreno** [comment]
Branches are now sorted by `committerdate`.
