### ISSUE TITLE
`There are no changes to stash` when all files are staged

### ISSUE THREAD

**Issue by vladeck** [Microsoft/vscode#35645]
- VSCode Version: 1.17.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Have files that are edited or new in working copy
2. Select `Stage All Changes`
3. Select `Stash`
4. Info `There are no changes to stash` is shown

**Comment by joaomoreno** [comment]
Would you like to look into a fix PR?

**Comment by dKab** [comment]
I'll take it if there would be no objections.

**Comment by vladeck** [comment]
None from me. I've just started reading the contribution docs and browsing through the code (for future endeavors) so someone that already has experience is better fit for this.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/35710
