### ISSUE TITLE
Unicode symbols inside integrated terminal

### ISSUE THREAD

**Issue by zaharcan** [Microsoft/vscode#35649]
Integrated terminal fails to display  \u2387 symbol if used as part of command prompt (PS1)
In 1.16 it was working.

- VSCode Version: 1.17.0
- OS Version: Xubuntu 16.04.3

Steps to Reproduce:

1. modify your PS1 to display \u2387 symbol 
2. open integrated terminal to see that only first part of this symbol is displayed, the second part is just a black space
3. if I try `prinft "\u2387"` from integrated terminal - it works

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@zaharcan can you provide a screenshot? This is what I see:

![image](https://user-images.githubusercontent.com/2193314/31252044-c78edac6-a9d4-11e7-8dfd-0aedccbce073.png)

**Comment by zaharcan** [comment]
![vscode](https://user-images.githubusercontent.com/25492410/31252235-8d45682a-a9ee-11e7-9cfb-d40e50f1a275.png)

**Comment by Tyriar** [comment]
Found the issue, the character is drawn but the background isn't:

<img width="247" alt="screen shot 2017-10-05 at 2 19 23 pm" src="https://user-images.githubusercontent.com/2193314/31253082-4571d2c4-a9d8-11e7-91e1-4f6855a4bcba.png">

**Comment by vcsjones** [comment]
Thanks for getting this figured out already... ran in to this with powerline for bash.

**Comment by Tyriar** [comment]
Pushed to release/1.17 & master

**Comment by pradyunsg** [comment]
@Tyriar When would this be released?

**Comment by Tyriar** [comment]
Probably early next week, not 100% sure though.

**Comment by pradyunsg** [comment]
Yayie!

I've patched my downloaded VS Code to have the newer xterm until then! Thanks _a lot_ for some awesome work on the terminal! ^>^
