### ISSUE TITLE
Default Fedora font has rendering issues

### ISSUE THREAD

**Issue by lalocespedes** [Microsoft/vscode#35644]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.0-2-amd64
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Terminal window doesn't look well
![codeterminal](https://user-images.githubusercontent.com/1903917/31250339-238a5c6e-a9e0-11e7-93f9-5d9aeb882637.png)

Reproduces without extensions: Yes/No

**Comment by acupofspirt** [comment]
Here is how my integrated terminal looks like
![image](https://user-images.githubusercontent.com/1342726/31250620-081aab34-aa24-11e7-881b-ffb3285157e1.png)

**Comment by Tyriar** [comment]
@lalocespedes what distro are you using? I've seen Fedora acts a little odd with font rendering both in the editor and the terminal.

@acupofspirt see https://github.com/Microsoft/vscode/issues/35681

**Comment by fpipita** [comment]
I'm experiencing the same issue on Fedora 26 / Gnome 3.24.2 / VSCode version 1.17.0. The only affected component is the terminal so far, other fonts look good.

The issue is not present in VSCode 1.16.1.

**Comment by lalocespedes** [comment]
@Tyriar  i am using debian 9 / xfce4 / VSCode version 1.17.0

**Comment by Tyriar** [comment]
For Fedora right now the workaround is to use a different font:

```js
"terminal.integrated.fontFamily": "'DejaVu Sans Mono'"
```

**Comment by fpipita** [comment]
@Tyriar it works like a charm. Thanks a lot :)

**Comment by lalocespedes** [comment]
@Tyriar Thks now looks very well.

**Comment by Tyriar** [comment]
Pushed to master and release/1.17

**Comment by vushe** [comment]
Not sure I've got issue right, but looks like custom fonts such as [Fira Mono](https://mozilla.github.io/Fira/) are not working after last update. Before update everything worked fine. Wouldn't say it is too important, but would be nice to get it back.

Linux Mint 18.2 x64.

![image](https://user-images.githubusercontent.com/15868217/31427551-5cc80668-ae70-11e7-9fcc-eb9054539b09.png)

**Comment by DNLHC** [comment]
Same issue here with Fira Code font
Ubuntu 17.04 x64

**Comment by danez** [comment]
yes also here FiraCode looks weird now. 
macOS 10.13

**Comment by bsvipas** [comment]
@Tyriar same here as @vushe after 1.17.1 update it looks weird now with SF Mono on macOS.

**Comment by Tyriar** [comment]
This is the issue tracking the blurry text in 1.17.1 https://github.com/Microsoft/vscode/issues/35991
