### ISSUE TITLE
The new terminal cuts off emoji characters 

### ISSUE THREAD

**Issue by ericulevik** [Microsoft/vscode#35656]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2

---

Steps to Reproduce:

1. change terminal to cmd.exe
2. open terminal
3. run node
4. console.log('😺')

Result:
cat face cut off vertically (space not wide enough to display whole emoji)

Desired result:
cat face fully displayed (as worked in VS Code prior to 6 Oct 2017)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
This will be fixed in https://github.com/Microsoft/vscode/issues/35188
