### ISSUE TITLE
extensions connect ENOENT error MacOS since 1.14

### ISSUE THREAD

**Issue by tgill880** [Microsoft/vscode#35652]
Selecting the Extensions icon in the left tool bar results in the following error message:

`connect ENOENT /var/folders/my/t5b899fn0_s4tx5_tndwnvh00000gp/C/Code-1.16.1-shared.sock`

Of course, no extensions are then listed.

This error occurs with 1.16.1, 1.15.1 and 1.14.2, but **not** with 1.13. The message is the same, except for the different version # in the .sock file.

The `.sock` file does not exist, hence the `ENOENT` error. There are many other files in that directory.

Since it looks like a networking error, I should note my Mac has 2 VPN services installed. 
* Tunnel Bear
* F5 SSL VPN Plugin (a VPN service for my university, which I need)

Neither are loaded when the error occurs.

- VSCode Version: 1.14+
- OS Version: MacOS 10.12.6

Reproduces without extensions: See above

**Comment by joaomoreno** [comment]
What other `Code-1.16.1*` files can you find in that directory?

**Comment by tgill880** [comment]
None. Same for all versions 1.13 - 1.16. However, 1.13 does not have the error, and the extensions are listed as expected.

**Comment by joaomoreno** [comment]
If you start Code with `code --verbose`, are there any errors in the terminal?

**Comment by tgill880** [comment]
Sorry for the delay.

code --verbose
   version 1.13.1 - no errors; extensions work correctly
   version 1.16.1 - error when click extensions icon as below (but not consistent)
   version 1.17.1 - no errors; extensions work correctly

So I only get an error message when I click on the extension icon, not on code launch.

code -- verbose > out.txt (version 1.16.1)
actions: launch from command line; click on extensions icon; quit from app
macOS 10.12.6

********************************** out.txt
[main 9:39:07 AM] Starting VS Code in verbose mode
[main 9:39:07 AM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 9:39:07 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false }
[main 9:39:07 AM] Unable to read folders in /Users/gillespy/Library/Application Support/Code/Workspaces (Error: ENOENT: no such file or directory, scandir '/Users/gillespy/Library/Application Support/Code/Workspaces').
[main 9:39:08 AM] IPC#vscode-machineId
[main 9:39:08 AM] IPC#vscode-workbenchLoaded
[main 9:39:34 AM] Lifecycle#quit()
[main 9:39:34 AM] Lifecycle#before-quit
[main 9:39:34 AM] Lifecycle#window-before-close 1
[main 9:39:34 AM] Lifecycle#unload() 1
[main 9:39:34 AM] Lifecycle#window-before-close 1
[main 9:39:34 AM] Lifecycle#window-close 1
[main 9:39:34 AM] Lifecycle#window-all-closed
[main 9:39:34 AM] Lifecycle#before-quit
[main 9:39:34 AM] App#will-quit: disposing resources

**Comment by joaomoreno** [comment]
Does 1.17.1 work correctly always?

**Comment by tgill880** [comment]
Yes.

**Comment by joaomoreno** [comment]
Then it is fixed. Thanks!
