### ISSUE TITLE
[folding] Collapse/expand all regions

### ISSUE THREAD

**Issue by dsolodow** [Microsoft/vscode#35657]
Now that 1.17 adds region support for languages, there are a few extra bits around regions that would be really handy:

- Command Palette option 'Collapse all regions'
- Command Palette option 'Expand all regions'
- Preference for regions expanded/collapsed by default on file open (default to expand)

**Comment by dsolodow** [comment]
Looks like the existing "Fold All" and "Unfold All" cover the "collapse all regions" and "expand all regions", so perhaps an alias (if that's a thing) or just documentation would cover those two.

**Comment by aeschli** [comment]
@dsolodow Fold All & Unfold All change all folding ranges: Both indendentation based and marker based.
Are you saying that's good enough, or should there be a command that only folds marker based ranges?

**Comment by dsolodow** [comment]
Hmm. 
I was originally thinking about things on the region tags, and didn't know about indentation based folding. 
I'm thinking ideal would be to have a preference for "include marker based folding" with it defaulting to yes.

**Comment by dsolodow** [comment]
So after experimenting and considering, I think it would make sense to have a separate one for marker based that shows on the command palette as 'Expand/Collapse Regions'.
Collapsing everything was a bit of a pain when you have functions inside regions. :)

I did see an interesting related idea here: http://tommymaynard.com/add-the-ises-ctrl-m-to-visual-studio-code-2017/

**Comment by GitTom** [comment]
I concur that it would be great to have 'expand/collapse all regions' commands, and a setting I could change such that files get opened with regions collapsed.

The regions in my file are much smaller in number and greater in significance - the user has taken the effort to mark the region themself - so they warrant the option of seperate treatment.

**Comment by aeschli** [comment]
Added two new commands: `Fold all regions Ctrl+K Ctrl+8` and `Unfold all regions Ctrl+K Ctrl+8`.
