### ISSUE TITLE
Automatic Selection of First Option in Quick-Fix menu doesn't work for Windows or Linux

### ISSUE THREAD

**Issue by KyleMcNutt** [Microsoft/vscode#35654]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
angular-productivity-pack|dev|1.6.1
githistory|don|0.2.3
gitlens|eam|5.4.1
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.9
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
angular2-switcher|inf|0.1.4
vscode-angular2-emmet|jak|2.0.3
angular-essentials|joh|0.2.0
Angular1|joh|0.2.0
Angular2|joh|2.7.0
Angular-BeastCode|Mik|5.0.4
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1
angular2-inline|nat|0.0.17
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|2.2.2
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1. Open a TypeScript Class and reference a class that isn't imported into your current class
2. Press Ctrl+. to open the Quick-Fix menu and notice that first element isn't selected

Reproduces without extensions: Yes

(pinging @bpasero since it looks like he implemented this in #33881)

**Comment by bpasero** [comment]
Yes, it turns out this is only supported on macOS unfortunately, I was not aware:

From: https://github.com/electron/electron/blob/master/docs/api/menu.md#menupopupbrowserwindow-options

**Comment by bpasero** [comment]
I filed https://github.com/electron/electron/issues/10699

**Comment by KyleMcNutt** [comment]
Ahhh, okay that makes sense. Thanks for the update! Glad we've got an open issue to add that to Windows/Linux.

**Comment by bpasero** [comment]
This works fine if you configure: `"window.titleBarStyle": "custom"`, which will be the default on Windows in our next release (possibly not Linux).

**Comment by bpasero** [comment]
Closing, the default has changed.
