### ISSUE TITLE
Collapsing a block doesn't collapse content with lower indenting

### ISSUE THREAD

**Issue by SanderRonde** [Microsoft/vscode#35653]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
auto-rename-tag|for|0.0.14
latex-workshop|Jam|3.5.5
expand-region|let|0.1.1
HTMLHint|mka|0.4.0
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.3.1
code-settings-sync|Sha|2.8.3
code-spell-checker|str|1.4.6
python|tht|0.2.3
vscode-todo-highlight|way|0.5.11
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1. Create a block of code where a line has no indenting (or just lower than the block itself)
2. Try to collapse it
3. Observe it collapsing everything but that line

Reproduces without extensions: Yes

![example](https://user-images.githubusercontent.com/5385012/31254669-f9798482-aa29-11e7-8cd8-da87f3f21f32.gif)

This behavior makes sense when dealing with lines that simply have less indenting, as there's no difference in how the code would function and the author can just increase the indenting if necessary. But when the lines contain for example (javascript) template strings where indenting is very important, increasing indenting is not possible (or you'll have to change the code to string[] joining).
This can be quite a pain when dealing with large sections of template strings that aren't collapsed (such as in the image below).

A possible solution except for of course collapsing everything inside a collapsed block, would be to make it possible to collapse a multi-line template string by itself.

![large example](https://user-images.githubusercontent.com/5385012/31254886-c4ac41b2-aa2a-11e7-948b-8f84807dc54c.gif)

**Comment by George35mk** [comment]
you must indent the code 118 and 119 line to work

**Comment by SanderRonde** [comment]
I know but seeing as the lines are inside of the collapsed block and the block shows it being collapsed, it would make sense if they're collapsed as well. Additionally indenting those lines could possibly break the code. For example in the following code, indenting the code would put a tab in front of the message the user sees, and the amount of tabs in front of the line the user sees would increase even more when this function would be indented even more.

```javascript
function showMessage() {
    const message = `
hi user,
some message`;
    messageBox.innerText = message;
}
```

**Comment by aeschli** [comment]
The current folding strategy is based on indentation only.
What you are looking for is language aware folding: #3422
