### ISSUE TITLE
Typescript definition files ignored outside of node_modules/@types

### ISSUE THREAD

**Issue by matt-erhart** [Microsoft/vscode#35658]
- VSCode Version: 1.17
- OS Version: Windows 10

Steps to Reproduce:

1. Move a folder from node_modules/@types to anywhere else
2. Try editing tsconfig fields include, files, skipLibCheck, paths, and typeRoots to match new location
3. Only see intellisense when folder is in ./node_modeles/@types

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Does reloading the window help? It sounds like the changes might not have been picked up.

**Comment by vidarc** [comment]
Seems related to my issue

Before 1.17.0 I had my setup like this:
main folder
    project1
    project2
    project3

and VSCode was able to find the @types folder inside each of the individual projects. once I upgraded it wasn't able to find @types/jasmine anymore. installing @types/jasmine inside of the main folder fixed it

**Comment by matt-erhart** [comment]
@chrmarti I didn't reload the window because vscode automatically detected when I moved the dir back into node_modules/@types. Will give it a go. 

Can someone explain the interaction between vscode and tsconfig as far as .d.ts files are concerned, and better yet, point us to a repo that's working?

**Comment by mjbvz** [comment]
@matt-erhart Are you still running into this problem?

`d.ts` files are part of the `tsconfig.json` project. VSCode should handle them the same way as tsc does, but it may have gotten out of sync in this instance.

**Comment by matt-erhart** [comment]
@mjbvz what's a minimal tsconfig and folder structure I could use to test this out?

**Comment by mjbvz** [comment]
@matt-erhart You should just be able to put the `.d.ts` files next to your `.ts` files. Can you share your `tsconfig.json` and a basic description of your project structure
