### ISSUE TITLE
Request to add "Close All Files Above / Below" in Working Files list

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3566]
Many modern editors that have tabs have options like "Close all to the right / left" or "Close all but this..." so you can close multiple files at once. The same can be added to the working files list. Right-click on a file and we should see options like "Close all files above", "Close all files below", and "Close all files but this one". I often organize files in tabs (or in the Working files list in the case of VS Code) according to function within the app I am working on. For instance, I may have a user view, user controller and user model open followed by login view, login controller and login model files. If I no longer need to refer to the login files, I could simply right-click the user model and select "Close all files below" rather than closing each login related file individually. I do this frequently throughout the day regardless of the project I am working on and I am sure this feature would be beneficial to others as well as it is an easy way to quickly clean up the working files list if you have many open.

**Comment by bpasero** [comment]
"Close Others" has been added for February.

**Comment by jayrosen1576** [comment]
ok great. the option to have a close above / below is important too since we tend to group files in the working files list and there are many instances where we want to just close the last or first few files that were opened.

**Comment by bpasero** [comment]
For our tabs work we will have "Close Others to the Left" and "Close Others to the Right". I do not think we need above/below as separate actions to that.
