### ISSUE TITLE
VS code window not refresh on background

### ISSUE THREAD

**Issue by juanpale** [Microsoft/vscode#35665]
- VSCode Version: 1.17
- OS Version: OS X 10.12.6

Steps to Reproduce:
1. Edit a file, so you will get a badge in git icon, wich indicate the change.
2. Use your prefer terminal, not the integrated terminal in vscode.
3. Commit the changes or checkout to a new branch.
4. Unless you click the vscode window, you will still have the badge or will see the previous branch name.

**Comment by joaomoreno** [comment]
This is purposeful: #11918
