### ISSUE TITLE
chinese font is break in new canvas terminal

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#35669]
- VSCode Version: 1.17
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. open terminal in vscode
2. type `ls -al`
3. chinese font is break

![untitled3](https://user-images.githubusercontent.com/2631733/31260914-dbed35c0-aa16-11e7-9f7f-01a4385143cc.gif)

**Comment by sgryjp** [comment]
Japanese font too. Scrolling up/down or hitting `Ctrl+K` (`workbench.action.terminal.clear`) leaves right half of Japanese (wide ones such as “漢”) character graphic left uncleared.

**Comment by itn3000** [comment]
It was occured in my machine(win8.1-x64) with Japanese font

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
