### ISSUE TITLE
Integrated terminal scrambled on resize

### ISSUE THREAD

**Issue by AaronReboot** [Microsoft/vscode#35664]
- VSCode Version: 1.17.0
- OS Version: High Sierra

Steps to Reproduce:

1. Open VSCode
2. Open Integrated Terminal
3. Switch focus to another app
4. Let computer go to sleep
5. Wake computer
6. Switch back to VSCode
7. Vertically increase the size of the integrated terminal pane with mouse

Reproduces without extensions: Yes

Example:
![image](https://user-images.githubusercontent.com/14034112/31260470-275e07e6-aa1c-11e7-9c10-401a30145a69.png)

**Comment by Tyriar** [comment]
@AaronReboot did you switch to a different DPI monitor in between using the terminal and this happening? Looks similar to https://github.com/Microsoft/vscode/issues/34320
