### ISSUE TITLE
Text in Tweet Feedback will be broke by Hashtag (#)

### ISSUE THREAD

**Issue by joesze** [Microsoft/vscode#35668]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3
java|red|0.11.0
terminal-tabs|Tyr|0.1.1

---

Steps to Reproduce:

1. Click the smiley icon to tweet feedback.
2. Text after hashtag (#) will not be brought to the browser.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Now using `encodeURIComponent` for the actual tweet content when opening the URL.
