### ISSUE TITLE
Inconsistent link activation in integrated terminal output

### ISSUE THREAD

**Issue by narkowicz** [Microsoft/vscode#35662]
- VSCode Version: Code - Insiders 1.17.0-insider (81fc22ec957de26d2bf6aada3f16f04e0164741c, 2017-10-03T22:47:28.178Z)
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Open a new integrated terminal
2. Run `echo https://www.visualstudio.com`
3. Expect both printed link texts to be command (or ctrl) + clickable, but neither underline on hover or are clickable
4. Repeat `echo https://www.visualstudio.com`
5. The second set of links (in command and result) underline on hover and are clickable as expected, first link text remains inactive
6. Fill terminal window with repeated output until scrolling is enabled. After manually scrolling up to first line of terminal contents, the first link is now clickable

Seeing same issue for local file path links.

Behaviour is very regular but not _always_ consistent for me. With a new integrated terminal session the first links are always un-clickable but are occasionally enabled after the second link is printed. On other occasions either one or both of the second links are also un-clickable.

Issue emerged in program output printed to integrated terminal on stable version 1.17 where none of the printed local file paths were clickable - in this case, manually scrolling the integrated terminal window activated the links.

edit: Added details of stable version exhibiting same behaviour

**Comment by Tyriar** [comment]
Pushed to release/1.17

**Comment by ramya-rao-a** [comment]
@Tyriar I could repro in Windows with 1.17.0 and have verified the fix works with 1.17.1
However I cannot repro in Mac with 1.17.0

**Comment by narkowicz** [comment]
@ramya-rao-a I've updated to 1.17.1 on macOS Sierra 10.12.6 and still seeing issue as originally reported.

**Comment by Tyriar** [comment]
@narkowicz I can not reproduce on 1.17.1 macOS, do you have errors in the console? (Help > Toggle Developer Tools)

**Comment by narkowicz** [comment]
@Tyriar no errors in console. Have disabled all extensions. Version details below.

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0

Only seeing the error as described above on first command in a 'fresh' / brand new terminal. In 1.17.1 the url is clickable when entered into the prompt, but after hitting return neither the url in (what was) the prompt or the printed result are clickable. All subsequent urls entered in same manner are clickable.

However, still seeing original issue of printed paths in program output initially not being clickable until scroll event (in my case seeing this in output of a build script run via npm). This seems to be the case regardless of when the command is run (does not require a fresh terminal to reproduce).

Was hopeful that the issue as described might fix the underlying problem affecting program output... I could create a new issue with an attempt to reproduce problem with program output if that's a better test case?

**Comment by narkowicz** [comment]
Update to last: showing verbose output in console reveals the following when opening a fresh terminal:

```
(2) Terminal.ts:2111 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
Terminal.ts:2111 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
Terminal.ts:2111 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
```

Not seeing any further messages in console after entering content or producing program output. No info, warning or error statements being printed.
