### ISSUE TITLE
Tasks menu disappears from menu bar

### ISSUE THREAD

**Issue by Xaqron** [Microsoft/vscode#35667]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.18
html-css-class-completion|Zig|1.10.0
html-snippets|abu|0.1.0
vscode-standardjs|che|1.2.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.4.1
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
code-runner|for|0.7.2
asciidecorator|hel|0.2.0
docthis|joe|0.4.8
sftp|lix|0.8.3
debugger-for-chrome|msj|3.3.1
vscode-code-outline|pat|0.0.11
vscode-versionlens|pfl|0.19.1
LiveServer|rit|2.2.0
vscode-icons|rob|7.14.0
bash-debug|rog|0.1.0
code-spell-checker|str|1.4.6

---

Steps to Reproduce:

1. Not a specific path to reproduce but mainly after running test task

In previous versions debug menu sometime disappeared
![tasks menu](https://user-images.githubusercontent.com/29380705/31260699-7bb0f1ec-aa5c-11e7-8c71-552719c9471d.png)
.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I've seen this sort of thing happen occasionally, particularly with the Help menu for me.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8901
