### ISSUE TITLE
CPU spikes just from typing

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#35661]
- VSCode Version: 1.17.0
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Open a file.
2. Type. 😢

Reproduces without extensions: Yes

CPU spikes to 100% whenever I type.

**Comment by ffxsam** [comment]
Verified that this occurs on macOS Sierra as well.

**Comment by alexandrudima** [comment]
@ffxsam Which VSCode process (command line arguments) goes up to 100% CPU ? I typically use something link `htop` in a separate terminal, and then try to find the `pid` that causes 100% CPU consumption. Then, I can grab the command line arguments. 

Is the CPU consumption going down immediately as you stop typing ?

Is there a CPU spike when typing in plain text files or only in certain file types?

**Comment by ffxsam** [comment]
Here's the full process (on macOS):

    /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart.js /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/5h/1l7pvm3d30qg92qtfgfscrh40000gn/T/vscode-tscancellation-cfd3993bbfbd3e1bb6ff.sock*

Yes, CPU consumption drops when typing. Actually, sometimes on macOS it works fine even when typing. On Ubuntu, my laptop's fan goes nuts & CPU spikes whenever I type. I'll try to gather more info there today.

Not sure if file type matters or not. I can gather more detailed info on my Ubuntu laptop, it's tough to gauge on the Mac since it's 50x more powerful than my laptop and handles whatever I throw at it. 😁

**Comment by ffxsam** [comment]
Process on Ubuntu:

    /usr/share/code/code /usr/share/code/resources/app/extensions/typescript/out/utils/electronForkStart.js /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-tscancellation-04e2683ef59cf347ce2a.sock*

It seems to have gotten _slightly_ better for no apparent reason. Not sure if it's related, but Code Outline is sometimes blank.. doesn't seem to consistently populate with symbols.

**Comment by alexandrudima** [comment]
That would be the `tsserver` process, the language service for TypeScript and JavaScript.

I'm not sure what exactly could be going on, my guess is that they are installing a file watcher and you have possibly enabled auto-save, and you are working on a folder with a lot of files.

**Comment by smac89** [comment]
Not just the CPU spiking, Huge memory spike too. I am running version 1.17.0, this is what I get from just opening the editor:

![code](https://user-images.githubusercontent.com/8305511/31288923-898a65f2-aa8c-11e7-946f-87a2bd1d1c9a.png)

The top two processes are from opening the editor, I haven't even typed anything yet!

Os: Ubuntu 16.04

**Comment by ffxsam** [comment]
Nope, definitely no auto-save, and not a lot of files.. nothing out of the ordinary. And 1.16 worked perfectly.

**Comment by mjbvz** [comment]
@ffxsam Can you please check to see if this reproduces for other file types? Specifically, please try restarting vscode with no open editors and then trying to open a few different types of files to see if one in particular triggers this

**Comment by ffxsam** [comment]
I'm actually having trouble replicating this now. I would normally think it was a fluke on my machine, but it happened on both macOS and Ubuntu.

I'll keep trying to replicate it. If I can't, I'll close this issue.

**Comment by mjbvz** [comment]
Closing this out. @ffxsam please let me know if the issue returns
