### ISSUE TITLE
Pinning vscode to the taksbar changes it's colour from orange to blue 1.17

### ISSUE THREAD

**Issue by BluSpanner** [Microsoft/vscode#35663]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
githistory|don|0.2.3
python|don|0.7.0
ctags|hcy|0.2.6
mssql|ms-|1.2.0
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1. Load vscode
2. Pin vscode to task bar

Reproduces without extensions: Yes/No

**Comment by navossoc** [comment]
No issues here on Windows 10.

To be honest, I hate this color change, every time I am looking for a blue icon.
IMHO, this is the worst idea ever...

**Comment by peterdanis** [comment]
On Windows 7 (and probably on other versions too) follow these steps:
- go to `%userprofile%\AppData\Local`
- delete `IconCache.db` file
- in Task manager kill `explorer.exe` process
- in Task manager start a new `explorer.exe` process (through `File > New task (Run)`)

**Comment by zonzujiro** [comment]
Windows 10, same problem.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33685
