### ISSUE TITLE
option terminal.integrated.enableBold break in 1.17

### ISSUE THREAD

**Issue by Treri** [Microsoft/vscode#35666]
- VSCode Version: 1.17
- OS Version: OSX 10.12.6

Steps to Reproduce:
1. open settings

I found this option was removed in the commit https://github.com/Microsoft/vscode/commit/02c75d263d8703e992f58476cdb62caf12213634
Could any one can explain why this option is removed? I think someone include me will need it.

**Comment by Tyriar** [comment]
This was removed after big changes to the terminal upstream.

**Comment by Treri** [comment]
Look forward to this option come back again quickly👍

**Comment by Treri** [comment]
Could vscode provide an option to still use DOM renderer instead of canvas? So that I can still use `terminal.integrated.enableBold` option?

To my condition, the current DOM renderer performance is good enough, and I just want to still use `terminal.integrated.enableBold` to disable the bold font in shell.

I always upgrade my vscode to latest version as soon as the new version vscode released, but I think the terminal's bold font is so ugly and I feel Uncomfortable with it.

I will appreciate it if vscode can bring `terminal.integrated.enableBold` back again

@Tyriar

**Comment by Tyriar** [comment]
@Treri I added it back, thanks for letting me know how important it is to you.

It would be great if you could test it in Monday's insiders build 😃 
 https://code.visualstudio.com/insiders/

**Comment by Tyriar** [comment]
@Treri also, a screenshot of your terminal with bold enabled plus the name of your font would be useful if you want to share.

**Comment by Treri** [comment]
You are so sweet! Thanks very very much!

I tested this option in latest insiders version. It works again.

below is the screenshot with this option enabled or disabled.
The font I used is **Source Code Pro**

when `terminal.integrated.enableBold` is true, the font is a little too bold, and some letter crushed to others, but when false, they are good to see

![image](https://user-images.githubusercontent.com/2631733/31575472-7e10fa5c-b0ad-11e7-9744-bf49759884d9.png)
![image](https://user-images.githubusercontent.com/2631733/31575499-22ba06de-b0ae-11e7-8a19-b9c23846f39d.png)

![image](https://user-images.githubusercontent.com/2631733/31575474-8c53a380-b0ad-11e7-9308-cbb14ab8310a.png)
![image](https://user-images.githubusercontent.com/2631733/31575506-35c5abf2-b0ae-11e7-9837-32aef0c9adc0.png)

**Comment by Treri** [comment]
Just a problem and a suggestion

**problem**: in integrated terminal in mac, <kbd>ctrl+cmd+space</kbd> the emoji can't input to terminal

**suggestion**: in Terminal.app and iTerm2, there is an option to show bold font in bright color, can vscode also have the option? Then we can disable the bold font and to use bright color to indicate the text is bold

![image](https://user-images.githubusercontent.com/2631733/31575782-d005d700-b0b3-11e7-86e1-e668255a89bb.png)
![image](https://user-images.githubusercontent.com/2631733/31575786-e06ccc20-b0b3-11e7-9b36-2ab19d2543e5.png)

**Comment by Tyriar** [comment]
Emoji IME is tracked in https://github.com/sourcelair/xterm.js/issues/469

On the options, I'd rather not go down this path right now. A lot of settings have been added around this stuff recently in the underlying lib and would rather let that bake for a while before adding even more.
