### ISSUE TITLE
1.17.0 Integrated Terminal Chinese Problem

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#35660]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|1.5.1
crane|Hvy|0.3.8
php-docblocker|nei|1.3.0

---

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/20104656/31259364-b28f5980-aa78-11e7-8aa3-f7443b37742f.png)

2.
![image](https://user-images.githubusercontent.com/20104656/31259366-b79101e0-aa78-11e7-92f3-2d50ea545c84.png)

3.
![image](https://user-images.githubusercontent.com/20104656/31259369-bd9ba1da-aa78-11e7-8951-62e3fa6ddb48.png)

Reproduces without extensions: Yes/No

**Comment by Yurunsoft** [comment]
![gif](https://user-images.githubusercontent.com/20104656/31259500-b053f45e-aa79-11e7-86fc-6aa29c929055.gif)

**Comment by mysticatea** [comment]
This happens in Japanese as well. It seems a problem of dirty checking.

![terminal-problem](https://user-images.githubusercontent.com/1937871/31261348-a1997b40-aa8e-11e7-8658-c3f8d8171942.gif)

**Comment by Tyriar** [comment]
Pushed to release/1.17 & master

**Comment by mysticatea** [comment]
Thank you!

**Comment by Dwscdv3** [comment]
@Tyriar It seems the patch isn't part of 1.17 release. Is there a setting to switch back to the old rendering engine?

**Comment by xu-gang** [comment]
1.17.1 version is ok.

**Comment by wuhuatianbao007** [comment]
good

**Comment by Yurunsoft** [comment]
it's good!
666!

**Comment by mjrao** [comment]
it's good!
