### ISSUE TITLE
New Icon Accessibility

### ISSUE THREAD

**Issue by maths22** [Microsoft/vscode#35672]
- VSCode Version: 1.17
- OS Version: N/A

Steps to Reproduce:

1. Look at the new stable icon
2. Look at the new insiders icon
3. Be color blind, and have no idea which is which

(AKA, the new choice of logo colors is very bad for color blind users who have both stable and insider builds installed, because the logo does not allow for the products to be distinguished)

Reproduces without extensions: Yes

**Comment by Thaina** [comment]
I think any pair of color would have the same problem for other colorblind people who have different type of colorblindness

I agree with you that it should improve but maybe with with more difference icon or shape, not color. For monochrome people too

**Comment by nbering** [comment]
![dock 2017-10-06 12-04-23](https://user-images.githubusercontent.com/4421371/31287575-bb5dadde-aa8f-11e7-928e-c5b0171ca291.png)
This is just one example through a simulation with the Sim Daltonism app on the Mac. One of the other red-green confusion types was actually even closer to each other in shade.
Differentiation by increasing the contract in colour intensity would probably have been more effective.

**Comment by maths22** [comment]
@chrisdias I just wanted to say thank your for taking this into account as part of reverting back to the blue color and even including a screenshot of what this would look like for color blind individuals in your blog post: https://code.visualstudio.com/blogs/2017/10/24/theicon#_youre-my-boy-blue

**Comment by bpasero** [comment]
Closing, there are currently no plans to change the icon.

**Comment by nbering** [comment]
You probably don't need the "as-designed" tag. This is probably resolved now... as recognized in the blog post that announced the change.

Here's an updated red-green confusion simulation with the new icon.
![simulated color blindness](https://s3-ca-central-1.amazonaws.com/nbering-monosnap/Dock_2017-11-11_10-37-29.png). It seems to me that the contrast, while not fantastic, is much easier to differentiate than with the previous colours.
