### ISSUE TITLE
Simplify --goto's usage

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3567]
Currently `--goto` uses the following form:

```sh
code file.ext:10:2 --goto # opens "file.ext" at 10th line, 2nd column
code file.ext:10:2 -g     # opens "file.ext" at 10th line, 2nd column

code file.ext:10:2        # opens the file "file.ext:10:2"
```

This is a little difficult to explain this in the usage and is a little different to how CLI args are handled on unix-like systems. I propose this instead:

```sh
code file.ext -g 10:2     # opens "file.ext" at 10th line, 2nd column
code file.ext --goto=10:2 # opens "file.ext" at 10th line, 2nd column
```

This follows the `-g <value>`, `--goto=<value>` standard and also allows `-g/--goto` to be documented in isolation of the path arg.

This also brings it in line with how the `--locale` arg seems to work currently.

**Comment by Tyriar** [comment]
@bpasero thoughts?

**Comment by bpasero** [comment]
I like the suggestion but it would seriously break all clients that expect the current behaviour including Unity plugins that are written so that you can easily open a file from Unity in VS Code. I would not want to make this change easily as this format has been out since almost a year without complaint.

**Comment by bpasero** [comment]
-1 for breaking existing clients.

**Comment by Tyriar** [comment]
@bpasero Would introducing the new way, deprecating the old way and notifying known consumers not be a better route? Otherwise this is technical debt as there is an arg that has inconsistent usage others like `--locale`.

**Comment by bpasero** [comment]
I am not so worried bout this as long as a user can find how to use this feature with "--help".

**Comment by bpasero** [comment]
And we would also loose a feature we have now: you can open multiple files with their line/col information.
