### ISSUE TITLE
Comment hotkeys throws the cursor before the comment

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/vscode#35673]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
vscode-docker|Pet|0.0.18
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|1.0.9
vscode-javac|geo|0.0.46
ruby-linter|hoo|1.0.0
vue|jcb|0.1.5
vscode-rust|kal|0.4.2
graphql-for-vscode|kum|1.6.2
Go|luk|0.6.66
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
Ruby|reb|0.15.0
java|red|0.11.0

---

Steps to Reproduce:

1. `cmd` + `/` keys
2. That's it. The cursor goes before the `//`. I've checked Ruby, JavaScript, Go, and C#. I think that's enough but I could check others

Reproduces without extensions: Yes

**Comment by iamclaytonray** [comment]
<img width="116" alt="screen shot 2017-10-05 at 11 43 18 pm" src="https://user-images.githubusercontent.com/16495816/31262214-89618304-aa27-11e7-8f7b-047349d5e0e9.png">

**Comment by creanme** [comment]
VSCode Version: Code 1.17.0
 OS:win10 15063
I have a similar problem:

![1](https://user-images.githubusercontent.com/11664505/31266867-67e83462-aaa8-11e7-8113-376d439c9ea8.png)
