### ISSUE TITLE
Emmet settings IntelliSense for new preferences 

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#35676]
In 1.17 in Emmet [were added new preferences](https://code.visualstudio.com/updates/v1_17#_emmet-preferences):

* bem.elementSeparator
* bem.modifierSeparator
* filter.commentBefore
* filter.commentTrigger
* filter.commentAfter

But they are absent from autocomplete:

![missingsuggest](https://user-images.githubusercontent.com/9638156/31263026-0d660a72-aa68-11e7-96b2-e302e0c437c7.png)

**Comment by ramya-rao-a** [comment]
Thanks for catching this @usernamehw!
I've pushed in a fix and the new preferences will start showing up in the suggestions in tomorrow's Insiders build

**Comment by EbXpJ6bp** [comment]
@ramya-rao-a 
Maybe this https://github.com/Microsoft/vscode/commit/fd77f04352aa75d4e4121f109d7c755784a5bb2a#diff-f00d71401c4d6214e9a4eaaf5c7e8a19R45 line has typo. 

"emmetPreferencesFilterCommentBefore": "A definition of comment that should be placed **before after** element when comment filter is applied.",  -> 
"emmetPreferencesFilterCommentBefore": "A definition of comment that should be placed **before** element when comment filter is applied.",

**Comment by ramya-rao-a** [comment]
Thanks @EbXpJ6bp 
Typos have been fixed.
