### ISSUE TITLE
ANSI Color "dark gray" is rendered incorrectly in the integrated terminal

### ISSUE THREAD

**Issue by xpl** [Microsoft/vscode#35677]
VSCode Version: 1.17.0
OS Version: MacOS Sierra 10.12.6
Extensions: Extensions are disabled

Steps to Reproduce:

1. Type `echo -e "Default \033[90mDark gray"` in the integrated terminal.
2. Rendered text is incorrectly rendered as **bold** (which shouldn't happen until a ["bright"](https://misc.flogisoft.com/bash/tip_colors_and_formatting) ANSI flag is set):

<img width="349" alt="screen shot 2017-10-06 at 07 44 03" src="https://user-images.githubusercontent.com/1707/31263320-28bde144-aa6a-11e7-854c-ac4a430f17d9.png">

What is expected (as it's rendered in the Mac's default Terminal.app):

<img width="302" alt="screen shot 2017-10-06 at 07 44 52" src="https://user-images.githubusercontent.com/1707/31263342-45fff5ee-aa6a-11e7-9e4a-4fac1881d86c.png">

**Comment by xpl** [comment]
More pics. How it looks in the (updated) VSCode's integrated terminal:

<img width="592" alt="screen shot 2017-10-06 at 07 48 03" src="https://user-images.githubusercontent.com/1707/31263442-d9c2518c-aa6a-11e7-9c62-a99e24d15edb.png">

How it should look (from Terminal.app):

<img width="596" alt="screen shot 2017-10-06 at 07 48 31" src="https://user-images.githubusercontent.com/1707/31263448-e96eaffe-aa6a-11e7-959a-83e0abe9fddd.png">

**Comment by xpl** [comment]
BTW, you can also try the [ansicolor](https://github.com/xpl/ansicolor) library (developed by me), which does the ANSI → CSS translation in JavaScript! Check it out.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/1047
