### ISSUE TITLE
VSCode Remote Client and Headless Server [feature request]

### ISSUE THREAD

**Issue by zhanglix** [Microsoft/vscode#35671]
- VSCode Version: latest
- OS Version: any

Steps to Reproduce:
Is it possible to have a VSCode Headless Server on a remote server, and a VSCode client on Laptop/iPad/Browser.  Then you can edit the files with the  client,  build and test on the remote server with all plugins running on the remote server. 

For example:

You have a big project that will take lots of time to build and tests on your laptop, but much faster on on powerful Linux Server which do not have a screen.  For now you can only install VSCode on the Server and using ssh -x to login onto the remote server. This is solution is not satisfactory for the amount of data to transfer between X11 client and Server is too large. The developing experience is dreadful. 

If there is a VSCode client and a Headless VSCode Server,  the amount of data required to transfer between client and sever will be much less. I think the editor will be much more responsive, and the speed of development will faster.

Reproduces without extensions: Yes

**Comment by Leedehai** [comment]
Much needed feature.

**Comment by ohjames** [comment]
I'd use it to write a vim plugin to get vscode's typescript functionality.

**Comment by tdamsma** [comment]
Such a feature would be awesome. With VS Live Share it seems like most of the work is done. I would love to be able to work with just a simple client and all finicky dev dependencies including editor setup packaged nicely in a set of containers

**Comment by ikriz** [comment]
Isn't having a linux server automatically imply its accessible via SSH?
In that case i'd like to just open an SSH folder (possible using SFTP) as a VSCode Workspace

**Comment by Rohansi** [comment]
Now that VS Live Share is in public preview it's the perfect opportunity to implement this. Many people are already using their servers as their dev environment and just work in their terminal. I don't know of any alternatives to that workflow that have a GUI but VS Code could easily fill that gap.

**Comment by bhack** [comment]
Please consider also the Docker and Kubernetes cases https://github.com/Azure/vscode-kubernetes-tools/issues/403

**Comment by Rohansi** [comment]
It seems like it, even though that issue was initially proposing the file system provider API.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by Rohansi** [comment]
@Tyriar Good to hear! How well does all of that integrate with Live Share?

**Comment by Tyriar** [comment]
@Rohansi not sure, I haven't tried it yet
