### ISSUE TITLE
cmd terminal Simplified Chinese display error

### ISSUE THREAD

**Issue by meowao** [Microsoft/vscode#35678]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.14393
![vscode](https://user-images.githubusercontent.com/13918627/31263968-6266cc48-aa98-11e7-8da6-9eb2936c4949.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
