### ISSUE TITLE
Switching icon color?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#35674]
It's a little thing but I think stable should be green and insider should be orange. I think color shade in yellow to red feel like a warning. While green and blue feel more stable

**Comment by chrisdias** [comment]
We will make Stable blue and keep Insiders green.  You can read all about it in the blog post: https://code.visualstudio.com/blogs/2017/10/24/theicon

Resolving this issue against a single issue tracking all the icon issues: https://github.com/Microsoft/vscode/issues/35683
