### ISSUE TITLE
Top notifications is truncated 

### ISSUE THREAD

**Issue by sergous** [Microsoft/vscode#35686]
Screenshot:

https://cl.ly/0x1G311y1b1Y

Expecting:
Show full message on mouse over.

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
autofilename|Jer|0.1.3
vscode-jest|Ort|2.4.1
terminal-tabs|Tyr|0.1.1
vscode-exports-autocomplete|cap|0.5.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|5.4.1
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
path-autocomplete|ion|1.6.1
quicktask|lky|3.0.0
vscode-extension-auto-import|mop|1.3.3
debugger-for-chrome|msj|3.3.1
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.15.0
js-jsx-snippets|sky|0.0.5
react-redux-es6-snippets|tim|2.1.0
vscode-react-native|vsm|0.4.2
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0
local-history|xyz|1.5.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by sergous** [comment]
Dear bpasero,
I just use link inside VS Code, which brings me directly here, not to any search form.
If you rely on this scenario, just redirect your request this to person responsible for the report button, not me - I just bringing good to VS Code.
If it's reported then just link it here, in this case I can follow it's for sure.
Regards,
Sergey
