### ISSUE TITLE
Vscode New logo

### ISSUE THREAD

**Issue by herper** [Microsoft/vscode#35683]
- VSCode Version:1.17.0
- OS Version:windows 10 X64 15063.632

Steps to Reproduce:
new logo put into the start menu is ugly！

**Comment by herper** [comment]
The background is opaque！
![01](https://user-images.githubusercontent.com/9085064/31266517-b5b505e6-aaa6-11e7-9346-874175abbc23.jpg)

**Comment by tailgo** [comment]
It's very ugly!!!

**Comment by akoufatzis** [comment]
The old one was perfect. The good thing is, that if you have it pinned on the macOS Dock and you update it, the icon does not change immediately to the ugly new one.

**Comment by upliveevent** [comment]
The old icon look better.

**Comment by karthikeyan5** [comment]
yeah!! ugly Logo and Shitty colour....

**Comment by David-Else** [comment]
The old logo was better, no idea why anyone wanted to change it. Seems like change just for the sake of change.

**Comment by enjikaka** [comment]
I hate the new logo. The old one was glorious!

**Comment by Fpckalk** [comment]
I'll get used to it! Thanks for all the updates VS Code team/contributors

**Comment by 0xdeafcafe** [comment]
Yeah, the new logo is horrific. Please, can it be reverted to the old logo by the next release?

**Comment by billinghamj** [comment]
Looks like an Office application 🤢

**Comment by billinghamj** [comment]
Could always fork the project to get rid of it though? I kinda doubt Microsoft will listen to anyone here...

**Comment by robinbentley** [comment]
The colour change is fine but really preferred the old logo 😞

**Comment by herper** [comment]
@billinghamj Yeah，background of icon colour is too deep,choose other colour will be perfect！Or，become transparent and look better！
![02](https://user-images.githubusercontent.com/9085064/31272514-cd8d4716-aabd-11e7-9f68-323d4e5c8262.jpg)

**Comment by herper** [comment]
@0xdeafcafe I don't think so!

**Comment by isergey** [comment]
Bring back the old blue icon!

**Comment by HRK44** [comment]
See https://github.com/Microsoft/vscode/issues/6607 for more information about the new icon...

**Comment by daniel0101** [comment]
Please bring back the old logo

**Comment by Mlocik97-issues** [comment]
I want back blue logo, or green is also good, but this "poop color logo" is horrible and so ugly.

![screenshot_74](https://user-images.githubusercontent.com/31345346/31275982-e06c84c4-aa99-11e7-8f93-66c93bf3fabc.png)

![screenshot_75](https://user-images.githubusercontent.com/31345346/31276001-f54beefc-aa99-11e7-88ab-0a1003b7bbf7.png)

And on desktop it isn't updated. (only if uninstall and install it's updated, but if I update old version, it's not)

**Comment by Stone-Zeng** [comment]
The files' icon is still blue:

![default](https://user-images.githubusercontent.com/18233088/31276782-205ade4c-aad0-11e7-999d-29f655b5e87f.PNG)

**Comment by jeasonstudio** [comment]
I want back the blue one.
btw, the color `green` means something bad in chinese, and I think it's not a good choice.

**Comment by chadbr** [comment]
![image](https://user-images.githubusercontent.com/3179452/31280415-e7affe78-aa71-11e7-96d8-5013eb00ba9e.png)

cmz and insiders is the same??

**Comment by GuyHarwood** [comment]
the old one was great.  why change it?

**Comment by rfgamaral** [comment]
Old one - although not the best icon ever - was 1000x times better than the current one. Change for the sake of change about a thing that nobody ever complained about.

**Comment by LeoLozes** [comment]
The new icon shape is not great, but the worse was the color. 
I changed the taskbar shortcut icon after a few hours. 
I did try to get used to the orange (I'm not resisting to change usually), but sorry, nope. 

I'm using this one now (can't upload the .ico in github but you can convert it to ico [really easily](http://convertico.com):
![icon](https://user-images.githubusercontent.com/11133817/31283969-77272212-aab7-11e7-9190-f7544f7316ff.png)

**Comment by verlok** [comment]
Thanks @leolozes. I’ll do this too.

**Comment by verlok** [comment]
Yes, the old icon was a little too big on a Mac, but it was still acceptable. This new icon is very very ugly. Please change it asap.

**Comment by jens1o** [comment]
Well, tbh, due to the use of Insiders, I'm used to it now. It's not that worse. :)

**Comment by Mlocik97-issues** [comment]
#35736

**Comment by herper** [comment]
@LeoLozes Icon is very good，but live tile is still the original. I hope icon's background color to  follow the theme color change,and would be better.

**Comment by NoxRacing** [comment]
I not found the new logo that bad on linux, but I still prefer the old one. Before doing a change when nobody tell to change a small thing like this when is perfectly great, correct the bugs and implement new feature without changing something that nobody actually care about

**Comment by tyson-kubota** [comment]
The lack of visual distinctness with Sublime is not great. As noted on https://github.com/Microsoft/vscode/issues/6607#issuecomment-334792687.

My current Dock:
<img width="53" alt="screen shot 2017-10-06 at 11 04 17 am" src="https://user-images.githubusercontent.com/317573/31292315-cebd6c00-aa87-11e7-897b-7c8addad53d8.png">

**Comment by offbeatful** [comment]
Can we have new 1.17 release with old color (blue) icon?
New one is just awful.

**Comment by wmakley** [comment]
Man orange is such an ugly color. I liked the old icon just fine (on OS X). Seriously, now my devtools dock area looks awful:

![screen shot 2017-10-06 at 3 10 34 pm](https://user-images.githubusercontent.com/514189/31294350-901a4466-aaa8-11e7-9455-c8b7ccbd2d5a.png)

**Comment by bithooked** [comment]
The prior icon was so distinctive and recognizable, while still extremely clean.  The icon made me _want_ to click on it.  This one, which showed up on my desktop today, is just so muddy that it all-but disappears on my ribbon.

**Comment by miladghiravani** [comment]
New logo is very ugly!!!

I love previous logo: (blue have powerful)
![image_88](https://user-images.githubusercontent.com/5067331/31306057-c88fa910-ab54-11e7-86b2-f74511293b5c.png)

please change new logo! This affects productivity.

**Comment by tahnik** [comment]
I almost thought my new icon pack made the VSCode icon crappy. If you guys keep this I swear I will switch to....I will switch to...ummm...

Please don't do this to us. VSCode is the best text editor right now and that icon is just horrible.

**Comment by salmansamie** [comment]
Personally, I love the new logo. It's distinct and elegant.

**Comment by ruzhovt** [comment]
New icon is a terribly bad one :(

**Comment by volllly** [comment]
please go back to the old icon.

**Comment by llife0915** [comment]
the color should be blue

**Comment by viosey** [comment]
It's totally not cool! Weird color & design.

**Comment by faraazahmad** [comment]
Please bring back the blue logo

**Comment by iamchathu** [comment]
Bring back the old one.

**Comment by msaiyaff** [comment]
**Please bring back the old logo.**
Even the files look uglier and I don't tend to open them.
![image](https://user-images.githubusercontent.com/17147255/31311623-c6b2adb2-abcd-11e7-8efe-571eb3f0ca7f.png)

**Comment by 1l0** [comment]
Use reaction instead of broken radio.

**Comment by Rhodenspire** [comment]
I'm glad that they're trying new things with the icon, but the dark orange color doesn't give the feeling that this is a modern tool for programming, and the choice to snip off the leftmost edge is unnecessary and destructive to the iconic loop visual studio logo. It'd be just fine if It were back to being some variation of blue and had it's left-most side back.

**Comment by kaiyuanl** [comment]
New logo looks bad.

**Comment by Ituury** [comment]
I think also that the icon color looks bad. But the icon shape looks great. In #35674 the user had an interesting suggestion. I would like to see the green color instead of the orange, so that the insider version is orange and the stable is green. Like he said  "I think color shade in yellow to red feel like a warning. ". And I agree completely.

**Comment by jrysig** [comment]
It is difficult to distinguish VSCode icon on Linux Mint task bar. A few dark orange pixels on dark background:
![taskbar](https://user-images.githubusercontent.com/7038517/31315538-03447b46-ac1b-11e7-828e-f29b4364fbea.png)

**Comment by makepizza** [comment]
Hm... 
![screen shot 2017-10-08 at 21 11 58](https://user-images.githubusercontent.com/25575840/31316269-8e5b5036-ac6d-11e7-9312-60d0288ca385.png)

**Comment by GuyHarwood** [comment]
Workaround for macOS....

1.  Download a [previous version](!https://code.visualstudio.com/updates/v1_16) 
2.  Right Click -> Get Info
3.  Select and Copy Icon in top left
4.  Right click VsCode in Applications folder -> Get Info
5.  Select and Paste Icon in top left

**Comment by tehbeard** [comment]
This new logo looks like a cheap knock off of the Sublime Text logo...

Come on guys, this is a great product, you're better than this.

**Comment by ruzhovt** [comment]
I can't work because of it! Please change it back asap or I'll newer finish my project :(

**Comment by ntkhoi** [comment]
Personally, I like the new logo

**Comment by iyedb** [comment]
Yes please bring back the new logo. vscode has become my only and primary editor but new logo is just awful (color and design wise) but especially that faded orange color. It will be interesting to see how MS reacts to this feedback. I will seriously consider switching to another editor it the icon problem is not fixed.

**Comment by zubivan** [comment]
Maybe, (VSCode is so extensible, right?) we can get an option to configure the icon with user settings?

P.S. I'm not a big fan of this change to orange, what was it driven by?

**Comment by iyedb** [comment]
Can it be configured with an extension :D

**Comment by ifeltsweet** [comment]
I feel sorry for the designer who spent time and effort on developing this new icon. We've all been there when we thought we were actually doing something great but when shared with others received negative feedback. Cheer up!

I'm on the same side with most people here, the color of the icon is very unattractive. The composition is even worse. In the age and time when streamlined, flat, simple graphics are all the craze this one feels like something from the era of 2000's.

Previous icon was actually very good. Maybe it needed some slight polish but nothing more.

It's funny how we are obsessed with little things, so seemingly unimportant. But it does in fact cost productivity for some of us.

**Comment by isergey** [comment]
I'm so sorry sorry, but color of new icon like piece of shit :(

**Comment by coxandrew** [comment]
Not a fan of the new one, but the old one was pretty bad too. You can change the icon pretty easily on a Mac, but you have to do it every time it updates. This is the one I'm using:

![](https://cdn.dribbble.com/users/18955/screenshots/3328384/artboard.jpg)

**Comment by Dalstroem** [comment]
I don't think the new icons are bad or ugly. But I don't understand why the stable is "Orange" and the insider is "Green"!

Normally orange is associated with warning or danger, where green is stable, ready og done.

**Comment by Veyhunk** [comment]
Blue maybe better![image](https://user-images.githubusercontent.com/21153513/31341256-90c34084-acce-11e7-85ff-8bdf130f149c.png)

**Comment by Cirno9** [comment]
when I'm coding, calm and cool blue is better. when I'm doing sports, maybe I'll choose warm orange.
so please bring the old logo back!

**Comment by mvenuksai** [comment]
Blue logo back please!!!

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

I do not like the "opening" on the back.

I think it looks better this way, in my opinion (done in Paint - sorry :laughing: )

![vsnew3](https://user-images.githubusercontent.com/19866231/31351762-ac438c36-ad02-11e7-92d9-467e3aed9b55.png)

**Comment by Bubbit** [comment]
I think the new logo is nicely aligned with my notes on MacOSX 👍 
![screen shot 2017-10-10 at 07 55 38](https://user-images.githubusercontent.com/7201983/31388659-fd108746-adce-11e7-96f6-141f2002a4fd.png)

**Comment by 0xdeafcafe** [comment]
I'm a fan of @Tekbr's post above. The half-vs icon is just weird, and orange as the logo colour when the app border is blue is just weird.

**Comment by billinghamj** [comment]
The Mac & Linux ones should be the same too though - the weird rotated semi-3D effect is not good.

**Comment by bithooked** [comment]
@Bubbit - Good catch.  It aligns with one of the few skeuomorphic icons that Apple has been too lazy to redesign to match modern flat icons that have been the modern norm for several years.  I think you've illustrated the problem perfectly.

**Comment by Knagis** [comment]
Why not just include multiple icons in the .exe - at least on Windows it is easy enough to change which icon is used for the shortcut - just click "Properties" -> "Change icon"?

But personally I have no problem with the orange one - I probably like it better than the blue one because there are already so many blue icons...

**Comment by coolicer** [comment]
So ugly, I can't accept it.

**Comment by makepizza** [comment]
Folks, new logo is not ugly. It's a good logo fo sure but... Main thing here that logo is out of a whole design concept. For me personally old one was the best in terms of VSCode's concept.

P.S.: But i don't care much to be honest because VSCode's logo != my code (and yours).

**Comment by djensen47** [comment]
The logo looks like an [ichthys ](https://en.wikipedia.org/wiki/Ichthys) or "Jesus fish" outlined by the letter J.

**Comment by pujianto** [comment]
![screenshot from 2017-10-11 11-25-54](https://user-images.githubusercontent.com/543111/31422306-f923f322-ae76-11e7-8d3c-59a20c7a1f46.png)
looks good on Ubuntu

**Comment by sudopluto** [comment]
looks more like microsoft office than a text editor

**Comment by haseebeqx** [comment]
looks very ugly in ubuntu. worst logo for such a great tool. old one was perfect

**Comment by verlok** [comment]
I’ve read everything you wrote and I wanted to recap: 

-  we don’t like the way the icon is rotated on Mac, because the rotated  icons belong to the past 
- we don’t like the new color of the icon because it’s different from the bottom bar of VS code
- we designed some really good alternative icons here, you should really take a look at them

Thank you for your time, we’re really hoping this item will change in the next release

**Comment by benji7425** [comment]
I really dislike this new colour too :( Please give the option to use the old blue one! My taskbar used to look nice and now it has an ugly orange icon on it

**Comment by isergey** [comment]
Please, sign the petision https://www.change.org/p/developers-bring-back-the-old-visual-studio-code-logo

**Comment by BigWillie** [comment]
I switched back to VS code a few weeks ago... on the basis of this logo, I think I might go back to Vim....

**Comment by qiaoyixuan** [comment]
very ugly!very angry! 😡

**Comment by jtafurth** [comment]
Hate every inch of it!!

**Comment by TommiHelander** [comment]
Please don't tilt the mac logo! By addition to the new logo being too complicated and abstract by itself, this tilting makes it even worse.

**Comment by martinsuchan** [comment]
**The new orange color just feels wrong.** Visual Studio always used purple or blue color. VS2017 has purple, VSCode should use the light blue, just like before.  
I have no problem with the shape even thought the original Infinity symbol was a bit better.

**Comment by felipemullen** [comment]
+1 on going back to the old logo. 
Either the purple one shown by @LeoLozes or the blue one that was being used before this release. I can see why it happened from microsoft's standpoint, since it aligns with the style used by visual studio.. but..

**The new logo is very unattractive and ugly**

Part of the reason many people were open to trying out VSCode is because it is not like Visual Studio in the first place, so from a marketing point of view you may want to reconsider the decision to confuse people further

**Comment by jbrodriguez** [comment]
So, an icon look detracts from a product's technical merits ... why? why ??? once you click, you can forget about it ... I certainly don't like the new icon, but right now, vscode is the best electron-based editor available.

**Comment by RaTcHeT302** [comment]
can we go back to the blue one please

**Comment by vammex** [comment]
i pay $5 to everyone who can find the VSCode logo on this screen
![color](https://user-images.githubusercontent.com/19187347/31583174-45d4b81c-b19e-11e7-86ee-2a61be3645c9.PNG)

**Comment by faraazahmad** [comment]
To be honest, the logo isn't so bad, especially with the 3D-ish effect on Mac and Linux. What's putting people off is the weird orange colour and the fact that it is similar to that of sublime. Consider changing it to blue maybe.

**Comment by vammex** [comment]
i don't understand - there are 9 signs on  [](https://www.change.org/p/developers-bring-back-the-old-visual-studio-code-logo) right now while there are almost 100 posts here. where is everybody?

**Comment by RaTcHeT302** [comment]
why would the vs code developers care about some random petition?

**Comment by verlok** [comment]
I agree with @ratchet302 and that’s why I didn’t sign the petition :)

**Comment by vammex** [comment]
i don't understand why one interferes with another ?
continue to upvote and sign the petition, it doesn't work for you together?
if you don't care vs code developers' reaction why you are in this thread?

**Comment by sudopluto** [comment]
@vammex, this is an open source project, this issue in itself is a form of petition. no need for silly change.org petitions when you can make pull requests and open issues :)

**Comment by isergey** [comment]
@sudopluto The petition needed to solve common problems. This is a blatant case beyond a issue tracker :)

**Comment by LeoLozes** [comment]
@isergey if you are using VS Code, chances are that you're a developer. If you are half serious, you know it's an open source project, and there's a GitHub link in the home page. You then search the issue and find it. Way easier than finding some random petition in Change.org that nobody cares about.  

And we're talking about an editor icon for God sakes, not a worlwide issue. I didn't want to comment to keep the thread clean, but couldn't resist, sorry. 

I think the +200 thumbs-up are enough for the developers to know there's consensus among the community about the redesign.

**Comment by isergey** [comment]
@LeoLozes the changing icon was a shock for me. I could not work half a day because of this.

**Comment by edwinj85** [comment]
I concur - the new icon is hideous.

**Comment by rubberduck203** [comment]
The orange is off putting. So is cutting off half the logo. The green that's being used on the insiders build is actually really nice looking, still a cool (as opposed to warm) color, and would stand out nicely in the task bar. There aren't many green icons around. 

Seriously though. Close the loop. It looks ridiculous. 

> Developers like you live with the Visual Studio icons every day: clicking on them multiple times, staring at them side by side on the taskbar, and seeing them attached to project files. So when we update them, it’s a big deal. After all, icons matter. For pictures that are at most just under a centimeter wide on a normal display (or under half an inch, for those of you who aren’t British like me), icons are huge. They pack a lot of meaning into a small space. They offer clues as to what kind of experience you’ll have with the application the icon represents. Some icons even establish an emotional connection: they make you feel something about something.

https://blogs.msdn.microsoft.com/visualstudio/2017/03/08/iterations-on-infinity/

There seems to be a huge disconnect between the purpose and the results here.

**Comment by crowna** [comment]
Orange is great! It stands out maybe a little Arabic in style, but that's not a bad thing.
Blue is so Fire Fox Developer, Outlook, Skype and MS Edge...

**Comment by Matheus-de-Souza** [comment]
I was reading the commentaries on the post [iterations on infinity](https://blogs.msdn.microsoft.com/visualstudio/2017/03/08/iterations-on-infinity/) and I found this response from the design director, John Lea.

> The reason we could only use a single flat color was due to the branding guidelines. Now branding guidelines in general are useful and very much required to ensure a sense of consistency across products. A world without branding guidelines would be would be a bit of a mess, and in such a world Microsoft products would not feel like ‘Microsoft products’.

I'm losing hope that Microsoft will change this terrible icon..  😞

**Comment by dondon2475848** [comment]
I like Blue icon!
Orange icon is very ugly><

**Comment by verlok** [comment]
Hey, Microsoft team, are you gonna do something for this after all these comments?

**Comment by vammex** [comment]
i have only one hope that they'll not come with some philosophical ideas why orange is better than blue and other stuff

**Comment by sporto** [comment]
I don't think the orange is bad, that doesn't seem like the issue to me. Blue was nicer though. Everything else about the logo is terrible, the shape, the lack of balance, too much contrast. Doesn't look professional at all.

**Comment by Ankit-Prajapati** [comment]
I want the Blue Logo Back. This New Logo is so Dull.

**Comment by AdamNC** [comment]
The new logo is absolutely horrible.

Considering boycotting VS Code for the stupidity of this choice alone...

**Comment by coxandrew** [comment]
I think people calling for the logo to be reverted to the old blue logo are missing the boat. The old logo was not better. 

The update is better than the previous logo (at least on Mac) because it at least adheres better to the Mac icon guidelines (gradients, drop shadows, size). It really isn't _terrible_, but it still needs a few iterations.

Even within the MS brand guidelines, I think there's room for improvement based on some of the earlier suggestions.

This is specific to the Mac logo:

1. Tilting it at that angle makes it look outdated like the old skeuomorphic icons (Mail, Calendar).
2. The dark, rectangular background helps with contrast, but makes it appear brown and dingy (rather than a vibrant orange).

Consider:

1. Not tilting the logo
2. Using a white (rounded?) rectangular backdrop for contrast with a drop shadow
3. Using green for stable and orange for insider (as @polettoweb noted, green is associated with safe, yellow/orange with caution)

Also, my sympathies for the logo designer who has to put up with feedback from a bunch of programmers.

**Comment by artin-phares** [comment]
Do not care about tilting, rounding, backgrounds, shadows...  
Just need it in blue.

**Comment by djensen47** [comment]
Aside from the tilted angle, the logo *might* be more tolerable on MacOS because it has dimension and depth. However, on Windows (ironically), it looks subpar. If the team is not able to fix the overall idea of the design, at least _clean up_ the current versions of the icon.

**Comment by coxandrew** [comment]
I agree @djensen47 - the dimension and depth and _contrast_ definitely makes it better on macOS. I don't think it's actually too far away from being a "good" icon on Mac.

**Comment by djensen47** [comment]
However, I still don't like that the "infinity" symbol is missing a section. It implies that VS Code is inferior, substandard, or incomplete compared to VisualStudio. (Some of us might actually think the opposite).

**Comment by mermaid** [comment]
I've made a shell script for macOS that will change it back if anyone is interested in it
https://github.com/mermaid/vscode-beautifier

Hopefully they'll work on it more and get a better looking icon, but until then I'll just keep changing it back

**Comment by vammex** [comment]
@coxandrew have you earned a $5 bonus already by doing this?
[https://github.com/Microsoft/vscode/issues/35683#issuecomment-336695720]

**Comment by dannygoncalves** [comment]
I don't like it old one was perfect, no idea why the image change

**Comment by rafialikhan** [comment]
Orange is not cool, bring back the blue...and whats with the tilt on mac?

![screen shot 2017-10-20 at 1 19 06 am](https://user-images.githubusercontent.com/179993/31791422-1d222684-b536-11e7-816d-905714699635.png)

**Comment by verlok** [comment]
Let’s be frank: the old icon wasn’t that good either. But the new one is worse. Please remove the tilt on Mac, and if possible bring back the blue.

**Comment by brunocassol** [comment]
![vscode_meme](https://user-images.githubusercontent.com/203541/31820342-4449f2fa-b577-11e7-9707-810108002b3e.png)

**Comment by vikas-0** [comment]
#35783 consider closing this issue

**Comment by orenmizr** [comment]
i wonder how many comments before there will be some kind of **recognition** about this from **microsoft**

workaround on fixing your open source code editor
1. uninstall vscode
2. reinstall atom, atom-ide-ui, atom-typescript
3. unstar this repo

**Comment by verlok** [comment]
@orenmizr Done!

**Comment by vikas-0** [comment]
@orenmizr or use papyrus icon theme 
![image](https://user-images.githubusercontent.com/15345994/31849653-26e4f31c-b663-11e7-987b-0713c42d660a.png)

**Comment by faustinoaq** [comment]
![vscode new icon meme](https://i.imgur.com/6AB8BNV.jpg "vscode new icon suggestion")

**Comment by fabioroldan** [comment]
Please, Mr. Microsoft, please return our logo. The orange does not have enough contrast and is confused with the color of my windows. And the lateral line shrinks the logo, discard it.

**Comment by AlfaDelta** [comment]
Very ugly on Mac and Windows :-(  I surprised me that someone allowed this.

**Comment by Robinnnnn** [comment]
I'm gonna go back to using Sublime. Ping me once the old logo is back!

**Comment by AlfaDelta** [comment]
Please sign:
https://www.change.org/p/developers-bring-back-the-old-visual-studio-code-logo

**Comment by AlfaDelta** [comment]
VSC @Linkedin.... https://www.linkedin.com/groups/6974311/profile

**Comment by chrisdias** [comment]
Thanks everyone for all the feedback, and again we apologize for not responding sooner.  

In a nutshell, we've decided to change the Stable orange to blue, and keep green for Insiders. You can read all about it in the blog post: https://code.visualstudio.com/blogs/2017/10/24/theicon

Resolving this issue against a single issue tracking all the icon issues: https://github.com/Microsoft/vscode/issues/35683

**Comment by Robinnnnn** [comment]
WE DID IT!!! _reinstalls_

**Comment by felipemullen** [comment]
proud of Microsoft for listening to the community these days. Tell the design team we still love them

**Comment by alexanderby** [comment]
![ms-eats-vs-code-fish](https://user-images.githubusercontent.com/9638588/31967531-d65a2924-b916-11e7-84a6-545e31a7e63f.png)

**Comment by MrSunshyne** [comment]
Ok great. but it's still orange... even after I downloaded it again.

**Comment by chrisdias** [comment]
@MrSunshyne it will be blue in the next stable release, available in early november.

**Comment by vammex** [comment]
so good to know MS comes back! thank!

**Comment by intellixdev** [comment]
so ugly! nice to know we gonna go back to the BLUE color. I feel sick with this orange

**Comment by faintsignal** [comment]
[Blue is Back!](https://youtu.be/YVkUvmDQ3HY?t=32s)

Thanks to everyone for giving the feedback and responding to it.  
I think we all learned a valuable design lesson here, which is: if you can replace Trump's hair with your logo and no one notices, it's time to rethink it.

**Comment by fritzlolpro** [comment]
Give me back my orange!

**Comment by verlok** [comment]
LOL. I was getting used to orange too :)

**Comment by OrionStark** [comment]
Oh boy, one color changes everything :)

**Comment by sjetha-pason** [comment]
Can we get an option or an extension that brings back the Orange? I really liked it. Blue is such a boring colour.

**Comment by vammex** [comment]
@ @sjetha-pason come on may be enough trolling this issue?

**Comment by msaiyaff** [comment]
I think they weren't closing this issue so that they can relieve their work stress reading the comments made here? 🤔

**Comment by Xoom3r** [comment]
Rather indecisive, some people liked the orange and got used to it but on the other hand M$ actually did change it.. hmm...

**Comment by bithooked** [comment]
In my experience, colors are culturally aligned in many things, but especially in UIs.  In the some cultures, brighter colors in UIs are considered gaudy, and in the other cultures they are preferred.  Reds and oranges, in particular, are discouraged in UIs in the some cultures, because they invoke a warning response, while in other cultures, reds and orange are more popular.  So, I don't think it's surprising to hear some people express that they preferred orange.  That's part of the difficulty of building international UXs.

**Comment by tmutton** [comment]
+1 for the blue logo

**Comment by Simran-B** [comment]
Not that I liked the orange logo, but it did work better in Windows' "open with" dialog:

![image](https://user-images.githubusercontent.com/7819991/33509711-457def92-d704-11e7-8117-3d60fcede1b7.png)
