### ISSUE TITLE
Default Fedora font has rendering issues

### ISSUE THREAD

**Issue by Holdlen2DH** [Microsoft/vscode#35687]
- VSCode Version: 1.17
- OS Version: Fedora 26

![screenshot from 2017-10-06 15-46-45](https://user-images.githubusercontent.com/3234356/31268207-df0969ca-aa40-11e7-8a28-456a8732fe43.png)

**Comment by svrakata** [comment]
* Distributor ID:	Ubuntu
* Description:	Linux Lite 3.4
* Release:	16.04

![terminalvscode](https://user-images.githubusercontent.com/17287274/31272505-e0b458b8-aa93-11e7-9aa4-660c74617006.png)

**Comment by Tyriar** [comment]
@Holdlen2DH Fedora has issues with its default font, if you change the font the problem should be gone, try adding this to your settings:

```js
"terminal.integrated.fontFamily": "'DejaVu Sans Mono'"
```

@svrakata see https://github.com/Microsoft/vscode/issues/35681

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35644

**Comment by Holdlen2DH** [comment]
@Tyriar  Thanks very much! It  works.
