### ISSUE TITLE
Add Case sensitivity to editor.action.addSelectionToNextFindMatch

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3568]
We use this feature a lot in our daily development activities however since it is case-insensitive, it tends to select items that are unintended. A perfect example is defining an instance of a class and wishing to rename the instance references but not the class itself:

var user = new User(); <-- cmd+d would select 'user' & 'User' when only the instance variable is intended
user.firstName = 'Joe';
user.lastName = 'Smith';

**Comment by alexandrudima** [comment]
@jayrosen1576 The find widget toggles also control the behaviour of `cmd+d`. The toggles can be used even when the find widget is hidden:

Here are the mac keybindings:
- case sensitive: `cmd+alt+c`
- whole words: `cmd+alt+w`

![ctrl-d-case-sensitive](https://cloud.githubusercontent.com/assets/5047891/13422984/b002674a-df98-11e5-9f71-b55c96ce8e75.gif)

**Comment by jayrosen1576** [comment]
While this does seem to work it is a bit clunky and not well known as an option. I would assume cmd+d would function case-insensitive as most other text editors do with maybe cmd+alt+d as a case-sensitive selection.
