### ISSUE TITLE
File copy in UNC folders doesn't work anymore

### ISSUE THREAD

**Issue by mkszepp** [Microsoft/vscode#35680]
- VSCode Version: 1.17.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder
2. select file
3. copy file
Error: `A system error occurred (UNKNOWN: unknown error, mkdir '\\servername\servername\myprojects\myproject')`

Correct path in my example is: `\\servername\myprojects\myproject`

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
We should always use `resource.path` when we use `uri.with` calls.
This was first introduced by https://github.com/Microsoft/vscode/commit/a7e2b9827f0a32a344629237faa78cf063e406d7

@jrieken can you please code review

**Comment by jrieken** [comment]
👍 Yeah, that is a good change

**Comment by isidorn** [comment]
I built latest insiders and verified this works.
Easy verification steps open a local file on windows as it is a unc path via
`\\localhost\c$\my_dir`

**Comment by isidorn** [comment]
I pushed the fix on top of release/1.17
@jrieken can you please verify once we have stable builds out tomorrow?

**Comment by jrieken** [comment]
Yeah, will do

**Comment by xtbe** [comment]
Doesn't appear anymore for me

![image](https://user-images.githubusercontent.com/909796/31379924-11917cf8-adb0-11e7-8ee6-916de97ccbed.png)
