### ISSUE TITLE
XMLs code folding problem

### ISSUE THREAD

**Issue by NikosK72** [Microsoft/vscode#35684]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open an XML with multiple nested elements, e.g.:
```
<body>
<section>
<sectionBody>
blahblahblahblah
</sectionBody>
</section>
</body>
```

2. Fold the parent element of a series of nested elements, e.g. the <body>. This results to:
```
<body>...
blahblahblahblah
</sectionBody>
</section>
</body>
```

Reproduces without extensions: Yes

**Comment by NikosK72** [comment]
[results-N059-2017-02-0000-00-en.zip](https://github.com/Microsoft/vscode/files/1361888/results-N059-2017-02-0000-00-en.zip)

**Comment by aeschli** [comment]
The current folding strategy is based on indentation only. 
What you are looking for is language aware folding: #3422

**Comment by NikosK72** [comment]
It sucks big time, because the resulting identation after formating an XML in VS Code is not good either. Almost any other editor does it right.

**Comment by aeschli** [comment]
Let's improve the formatter then as well. Please file a issue against the formatter extension!

**Comment by NikosK72** [comment]
Right! Thank you!
