### ISSUE TITLE
Font rendering in new terminal does not use standard spacing

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#35695]
- VSCode Version: 1.17.0
- OS Version: Windows 7 Pro

**Before:**
![image](https://user-images.githubusercontent.com/96476/31272082-9c59c4e4-aa81-11e7-863e-d7e26b7b6e07.png)

**After:**
![image](https://user-images.githubusercontent.com/96476/31272116-b2f69d80-aa81-11e7-82bf-51b352c9637c.png)

Doesn't seem to have proper spacing between each letter.

Is this a known issue?

**Comment by ITSecMedia** [comment]
It would be nice if you could add "terminal.integrated.fontWeight" too, 
because it's needed if you are using the "Operator Mono SSm" font.

But the current bug in letter spacing is even worse.

**Comment by franky47** [comment]
The refactoring in 1.17 to make the integrated terminal faster using canvas rendering definitely broke something, see #36086

**Comment by sjdweb** [comment]
This is awful for me too, I don't have a before screenshot but look how bad this is:

![image](https://user-images.githubusercontent.com/783982/31485358-70f2e084-af2b-11e7-86ba-6cde5cdd56eb.png)

**Comment by sjdweb** [comment]
Found #35991 which already has fix so hopefully released soon.

**Comment by ITSecMedia** [comment]
Yep it's still not right, better than the too much condensed letter-spacing before but still not the correct font kerning.

**Comment by Tyriar** [comment]
Yes standard spacing is a separate issue to #35991.

We have a `terminal.integrated.letterSpacing` setting coming which will allow spacing out by whole pixel amounts, I don't think actual standard spacing will come any time soon though as that will likely lose a lot of the recent performance gains. I'd like to support it eventually so people can use proportional fonts if they desire as well https://github.com/Microsoft/vscode/issues/35681

**Comment by Tyriar** [comment]
The situation has improved a lot since this was originally created, it's still not standard spacing but it's closer. I'm going to close this off in favor of proportional font support in https://github.com/Microsoft/vscode/issues/35681. We will probably eventually have a setting that can be set to enable proportional font support at the cost of performance but it will be disabled by default.
