### ISSUE TITLE
[html] Request textDocument/rangeFormatting failed when pasting inside script tags

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [Microsoft/vscode#35698]
- VSCode Version: 1.17.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create html file with  **<script type="text/html"></script>** element
2. Paste any text inside the script tags
3. (The problem) - Output window in being opened (Html Language server) with following error:
`[Error - 11:49:13] Request textDocument/rangeFormatting failed.
  Message: Request textDocument/rangeFormatting failed with message: Cannot read property 'getId' of undefined
  Code: -32603 `

Reproduces without extensions: Yes

**Comment by johnvs** [comment]
I have the same problem, same error message. 
* VSCode Version: 1.17.0
* OS Version: OS X 10.11.6

**Comment by Melmoth-the-Wanderer** [comment]
Changed `Reproduces without extensions:` from `No` to `Yes`. Sorry about that mistake.

**Comment by nicfitzgerald** [comment]
I have the same problem, but within any <script> tag, exact same error message, though.
* VSCode Version: 1.18.0
* OS Version: Windows 10 (Fall Creators Update)

**Comment by bhavin137** [comment]
Facing the same issue. I hope that commit fixes it for the next release..
