### ISSUE TITLE
Parent method suggestions in subclasses

### ISSUE THREAD

**Issue by bochen2014** [Microsoft/vscode#35696]
- VSCode Version: 1.17.0
- OS Version: windows7

Steps to Reproduce:

![parent method suggestions in subclass](https://code.visualstudio.com/images/1_14_js-super-suggestions.png)

however,  if you define a `constructor(){}` , all the suggestions are gone
![image](https://user-images.githubusercontent.com/8207081/31272236-fb7be0a2-aad5-11e7-8974-02baf291980b.png)

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/17977 

Closing as upstream
