### ISSUE TITLE
Miss import path quick suggestions with side effect import

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/vscode#35691]
- VSCode Version: 1.17.0
- OS Version: macOS 10.13

Steps to Reproduce:
![2017-10-06 16_03_41](https://user-images.githubusercontent.com/15059605/31268920-080c8782-aa44-11e7-85b6-2ad6d6b8c3a9.gif)

**Comment by notgiorgi** [comment]
Intelisense doesn't work for me at all.

even if I do

```js
const a = { foo: 'bar' }
a. // no suggestions appear after I type dot
```

**Comment by drKnoxy** [comment]
I had to update my jsconfig baseUrl from '.' to './'

**Comment by mjbvz** [comment]
@notgiorgi That is unrelated to this issue. Please file a new issue for your problem

**Comment by mjbvz** [comment]
Manually triggering intellisense using ctrl+space should still work in this case. I'll look into automatically showing intellisense for October

**Comment by roblourens** [comment]
I still don't see the path suggestions automatically appear for `import './'` or `import from './'`

**Comment by foisonocean** [comment]
@roblourens @mjbvz 
It still doesn't work in VS Code v1.18.1

**Comment by foisonocean** [comment]
I still don't see the path suggestions automatically appear for import './' or import from './'
Can you reopen this issue?
@mjbvz @roblourens
