### ISSUE TITLE
wiki: npm global install requires sudo on *nix

### ISSUE THREAD

**Issue by 0xmohit** [Microsoft/vscode#357]
The instructions for installing dependencies should make use of `sudo` for `npm` install as global packages on Linux and Mac.

``` diff
diff --git a/How-to-Contribute.md b/How-to-Contribute.md
index ab42f72..42d4228 100644
--- a/How-to-Contribute.md
+++ b/How-to-Contribute.md
@@ -32,7 +32,7 @@ After you have these tools installed, run the following commands to check out Co
 **OS X**
 
        git clone https://github.com/microsoft/vscode
-       cd vscode && npm install -g mocha gulp
+       cd vscode && sudo npm install -g mocha gulp
        ./scripts/npm.sh install
 
 **Windows**
@@ -45,7 +45,7 @@ After you have these tools installed, run the following commands to check out Co
 **Linux**
 
        git clone https://github.com/microsoft/vscode
-       cd vscode && npm install -g mocha gulp
+       cd vscode && sudo npm install -g mocha gulp
        ./scripts/npm.sh install --arch=x64
        # for 32bit Linux
        #./scripts/npm.sh install --arch=ia32
@@ -120,4 +120,4 @@ We're also interested in your feedback for the future of Code. You can submit a
 
 ## Discussion Etiquette
 
-In order to keep the conversation clear and transparent, please limit discussion to English and keep things on topic with the issue. Be considerate to others and try to be courteous and professional at all times.
\ No newline at end of file
+In order to keep the conversation clear and transparent, please limit discussion to English and keep things on topic with the issue. Be considerate to others and try to be courteous and professional at all times.
```

**Comment by jrieken** [comment]
That's a setup problem. Please refer to this guide: http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

**Comment by coreh** [comment]
We could add a link to that info on the instructions, though.

**Comment by jrieken** [comment]
Feel free to make a PR

**Comment by coreh** [comment]
Couldn't figure out how to make a PR against the Wiki. I edited it directly, I hope that's fine?

**Comment by mackenza** [comment]
I use nvm on Linux and `sudo` is not required. It's not a certainty that `sudo` is required and I feel like someone who needs `sudo` for a global npm install already knows that.

**Comment by FabianLauer** [comment]
@mackenza Agreed. I'm always suspicious of wikis, tutorials, etc that put `sudo` in sample code. Copying and pasting commands into the console without double checking might turn a good day into a bad one.

**Comment by Tyriar** [comment]
I think this can be closed, the wiki was modified to add this line:

> **Note:** For more information on how to install NPM modules globally on UNIX systems without resorting to sudo, refer to [this guide](http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/) .
