### ISSUE TITLE
[website] favicon is not updated, and one section is "without load".

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35708]
![screenshot_77](https://user-images.githubusercontent.com/31345346/31276205-e7a8c378-aa9a-11e7-95d5-94554f7aecf1.png)

![screenshot_81](https://user-images.githubusercontent.com/31345346/31276315-86f95a46-aa9b-11e7-976e-910466403914.png)

**Comment by Mlocik97-issues** [comment]
Icon is solved now.

**Comment by octref** [comment]
What's your browser and OS?

**Comment by Mlocik97-issues** [comment]
OS: Windows 8.1 & Linux Ubuntu 16.04.2 Gnome 3
Browser: Chrome 61.0.3163.100 & Firefox 56.0
