### ISSUE TITLE
Feature request: Block files from appearing on quick open

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#35701]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
read-only-indicator|ale|0.6.0
alignment|ann|0.3.0
Doxygen|bbe|1.0.0
python|don|0.7.0
matlab|Gim|0.7.1
triggertaskonsave|Gru|0.1.3
vscode-dimmer|hoo|2.1.0
mediawiki|jak|2.1.0
vscode-clang|mit|0.2.2
select-part-of-word|mle|1.0.1
cpptools|ms-|0.13.1
PowerShell|ms-|1.4.3
indent-rainbow|ode|0.6.1
vscode-clearcase|Ope|1.10.0
vscode-icons|rob|7.14.0
indenticator|Sir|0.4.2
vscode-hexdump|sle|1.4.0
code-spell-checker|str|1.4.6
comment-snippets|Tob|0.2.0
selectline-statusbar|tom|0.0.2
change-case|wma|1.0.0
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

0. Two folders containing different copies of the same source code, e.g. for working on different branches.
1. Open a file in one workspace.
2. Switch workspaces.
3. Open the same filename in the new workspace.
4. Often the file from the first workspace appears at the top of the list, so it very easy to open the file from the other workspace.

Is there anyway to prevent as I have often edited the wrong file? I would like to exclude files from other workspaces. This could be done a wildcard or only allowing files inside the current root folder. However, restricting to the current root folder would prevent quick opening of files outside the workspace, which also I often do.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
As a workaround, you could add a `**/*` exclusion in the `search.exclude` setting of the one folder you don't want to see results from.

**Comment by jpike88** [comment]
This is related to https://github.com/Microsoft/vscode/issues/19762

**Comment by LegoChicken** [comment]
@chrmarti Hi, could you clarify how to add the appropriate exclusion to search.exclude and how this would prevent files appearing in quick open. Thanks.

**Comment by BillDenton** [comment]
@chrmarti Hi, could you clarify how to add the appropriate exclusion to search.exclude and how this would prevent files appearing in quick open. Thanks.

**Comment by chrmarti** [comment]
Hi @BillDenton, in the settings editor:
- Switch to the settings of the folder you want to exclude.
- Add the `**/*` pattern.

That will let QuickOpen skip all files from that folder. Note that the setting is stored in the folder's `.vscode/settings.json`.
