### ISSUE TITLE
Import hints not working for Javascript files

### ISSUE THREAD

**Issue by methyl** [Microsoft/vscode#35702]
- VSCode Version: 1.17.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Open a JS project with empty `jsconfig.json`
2. Create a `test.js` with following content:
```
export default class Test {}
```
3. Create a `test2.js` with following content:
```
class Test2 extends Test {}
```

Actual behavior:
- No lightbulb with hint to `import Test from './test` appear.

Correct behavior
- Lightbulb with hint to `import Test from './test` appear, just like for `.ts` files.

It works fine once I change extensions from `.js` to `.ts`.

**Comment by mjbvz** [comment]
To use quick fixes in javascript files, you need to enable the checkJS feature: https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files

Try adding `"checkJs": true` to your `jsconfig.json`:

```
{
    "compilerOptions": {
        "checkJs": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
