### ISSUE TITLE
Suggestion: Allow customizing the css of the workbench

### ISSUE THREAD

**Issue by emil19** [Microsoft/vscode#3570]
In Atom it's possible to edit the css of the editor by going to "File > Open Your Stylesheet" and overriding the css of the editor. Since vscode is also based on HTML I imagine it wouldn't be too difficult to implement this feature in vscode as well. It would be very convenient to be able to customize the UI with css and possibly in other ways too.

I can see this feature being useful both in extensions and for the user to easily customize his or her experience. The thing I would like to do with it is move the debug widget to the side, because I find that it is placed in a very inconvenient location by default.

**Comment by joaomoreno** [comment]
Not supported and not in the near future plan.

cc @chrisdias @egamma
