### ISSUE TITLE
Insiders deb repo package broken (Web download works)

### ISSUE THREAD

**Issue by Obbi89** [Microsoft/vscode#35703]
- VSCode Version: code-insiders (1.18.0-1507267008) [amd64]
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. apt install code-insiders
(dpkg: error processing archive /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg' to '/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg.dpkg-new': unexpected end of file or stream)

Works for the download from the webpage: https://code.visualstudio.com/insiders/

sha1sum: 64f7cdb98ba110a642099112c270cba246a9e16d apt-download code-insiders
sha1sum: 9e80c77e805ab1a2a57367270de5c58b2cc02387 code-insiders_1.18.0-1507267008_amd64.deb

The files have same size but differ. A huge chunk in the broken file is filled with zeros :+1:

Reproduces without extensions: N/A

**Comment by molokovskikh** [comment]
Ii join to issue.
I have just same bug!

**Comment by hknust** [comment]
Experiencing the same issue but the Web download (code-insiders_1.18.0-1507267008_amd64.deb) has the same issue as the repo.

**Comment by chrmarti** [comment]
Maybe related: #35638

**Comment by sergey-suloev** [comment]
same issue
Ubuntu 16.04

**Comment by andrei-pavel** [comment]
Same issue with a new install. Seems like `ripgrep` is missing from `node_modules`, should be easy fix?
```
The following NEW packages will be installed:
  code-insiders
Unpacking code-insiders (1.18.0-1507267008) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg' to '/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by manjeettahkur** [comment]
same issue 

`(Reading database ... 200230 files and directories currently installed.)
Preparing to unpack .../code-insiders_1.18.0-1507267008_amd64.deb ...
Unpacking code-insiders (1.18.0-1507267008) over (1.17.0-1506717283) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg' to '/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg.dpkg-new': unexpected end of file or stream`

**Comment by edwinksl** [comment]
Looks like this problem has been fixed; I just managed to upgrade.

**Comment by molokovskikh** [comment]
I confirm. Fixed!

**Comment by chrmarti** [comment]
Sounds like a one-off that got fixed with todays build. Closing.

**Comment by manjeettahkur** [comment]
Still issue 
OS: - `Ubuntu 14.05 LTS`

> Preparing to unpack .../code-insiders_1.18.0-1507267008_amd64.deb ...
> Unpacking code-insiders (1.18.0-1507267008) over (1.17.0-1506717283) ...
> dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
> dpkg-deb: error: subprocess <decompress> returned error exit status 2
> dpkg: error processing archive /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb (--unpack):
>  cannot copy extracted data for './usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg' to '/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg.dpkg-new': unexpected end of file or stream
> Processing triggers for desktop-file-utils (0.22-1ubuntu1.1) ...
> Processing triggers for mime-support (3.54ubuntu1.1) ...
> Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
> Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Errors were encountered while processing:
>  /var/cache/apt/archives/code-insiders_1.18.0-1507267008_amd64.deb
> 
>

**Comment by Tyriar** [comment]
@manjeettahkur you're unpacking the bad version, try running `sudo apt update` first.

**Comment by manjeettahkur** [comment]
@Tyriar Thank you so much for guide me
