### ISSUE TITLE
Integrated terminal font issue

### ISSUE THREAD

**Issue by nilsenmiotto** [Microsoft/vscode#35706]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.2
githistory|don|0.2.3
vscode-great-icons|emm|2.1.16
json-tools|eri|1.0.2
php-debug|fel|1.11.1
code-runner|for|0.7.2
ruby|gro|0.0.6
CppSnippets|har|0.0.12
vscode-clang|mit|0.2.2
vs-deploy|mkl|9.33.0
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
prettier-vscode-with-tabs|pas|1.1.0
Ruby|reb|0.15.0
ayu|tea|0.8.0
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1. Open the integrated terminal
2. try read something...

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please provide a screenshot and call out the issue, there are many things that could go wrong.

**Comment by doggy8088** [comment]
In my terminal (v1.17.0) on Windows, when I type "cls" to clear window.  It will leave something dirty in the screen.

Before type `cls`:
![image](https://user-images.githubusercontent.com/88981/31287927-8f80feee-aaf5-11e7-9ee8-442a8dafadd7.png)

After `cls` entered:
![image](https://user-images.githubusercontent.com/88981/31287941-9e903508-aaf5-11e7-98a3-0fe12bc36cfb.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660

**Comment by nilsenmiotto** [comment]
![terminal](https://user-images.githubusercontent.com/20935245/31289652-d368a130-aa9f-11e7-879e-5cd06c85a287.png)

**Comment by Tyriar** [comment]
@nilsenmiotto see https://github.com/Microsoft/vscode/issues/35681, you should use a monospace font
