### ISSUE TITLE
Making comments using Ctrl + /  places the cursor in the wrong position

### ISSUE THREAD

**Issue by ByFox** [Microsoft/vscode#35704]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.13.1

(1 theme extensions excluded)

---
Hi, using visual studio code really well!
Since the latest update, whenever I make a comment using Ctrl + / key, it places the cursor in front of 
//, not the back of // which makes me unable to write right after making those comments.
Hope this bug is fixed really soon!

Reproduces without extensions: Yes/No

**Comment by iamclaytonray** [comment]
Figured I'd add, this is a replica issue: #35673
