### ISSUE TITLE
Git partial staging issue: illegal value for `line`

### ISSUE THREAD

**Issue by jbrodriguez** [Microsoft/vscode#35705]
![screen shot 2017-10-06 at 06 06 03](https://user-images.githubusercontent.com/1305422/31275443-cfd0ec1e-aa5c-11e7-9533-ff90033eaa00.png)

- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Select a range to stage
2. Click on menu option stage selected ranges

Reproduces without extensions: Yes

**Comment by jbrodriguez** [comment]
I have to say, this works on the inline view.

**Comment by joaomoreno** [comment]
#32681

**Comment by oshalygin** [comment]
Anyone have a resolution for this?? It was closed based on the other ticket and the other ticket was closed based on this one?  @joaomoreno maybe we should reopen?

**Comment by oshalygin** [comment]
This only breaks in side by side view

**Comment by joaomoreno** [comment]
@oshalygin #32681 is still open.
