### ISSUE TITLE
hot reloading  when using vuetify project is very very slow.....it takes 20 seconds minimum to hot reload

### ISSUE THREAD

**Issue by Jay0007** [Microsoft/vscode#35714]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-html-css|ecm|0.1.8
json-tools|eri|1.0.2
vue-snippets|hol|0.1.5
node-module-intellisense|lei|1.4.0
vue|liu|0.1.5
atom-keybindings|ms-|3.0.2
vetur|oct|0.9.10
vue-vscode-snippets|sdr|1.0.2
code-spell-checker|str|1.4.6
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Jay0007** [comment]
pls tell me what should i do?

**Comment by chrmarti** [comment]
Which command do you run? "Reload Window"?

**Comment by chrmarti** [comment]
Does it reproduce with the latest release 1.17.0?

**Comment by Jay0007** [comment]
I USE ->NPM RUN DEV

**Comment by chrmarti** [comment]
This seems to be specific to vuetify, not VSCode?
