### ISSUE TITLE
hanging parsing, slowing down

### ISSUE THREAD

**Issue by lukaswajdzik** [Microsoft/vscode#35712]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
gitlens|eam|5.4.1
CppSnippets|har|0.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1. Open c++ project (>10 000 files)
2. Working very slow, indexing cannot finish

Previously I had no such a problem (previous versions). It was parsing quickly and working fast

**Comment by chrmarti** [comment]
Could you check if there is a `rg` process running and what arguments that has?

Could you also post your `files.exclude` and `search.exclude` settings here?

**Comment by lukaswajdzik** [comment]
thanks for quick reply!
I don't see any rg process running (_ps -aux | grep rg_)
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/cmake-build-debug": true
    }
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  }

**Comment by lukaswajdzik** [comment]
It helps! Thank you.

So the issue is with c++ extension.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#1118
