### ISSUE TITLE
【Terminal】Break japanese

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/vscode#35713]
- VSCode Version:latest
- OS Version:ubuntu16.4
![image](https://user-images.githubusercontent.com/17868838/31276851-fe7aa1d2-aad8-11e7-9aeb-ba40bb59bc65.png)
![image](https://user-images.githubusercontent.com/17868838/31276847-f6d397e0-aad8-11e7-8a1b-32520679b347.png)

Steps to Reproduce:

1.japanese input
2.click clear

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
