### ISSUE TITLE
[0.10.10-insiders] Code folding for #region/#endregion

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#3571]
It seems that `#region`/`#endregion` syntax in both PowerShell and C# isn't foldable in the 0.10.10-insiders release:

![image](https://cloud.githubusercontent.com/assets/79405/13413795/3954aa5e-df02-11e5-8018-d1b24f9d0a8e.png)

It seems that `#if`/`#endif` work fine though. What should our syntax definition files need to make these regions fold correctly?

**Comment by Tyriar** [comment]
This is blocked by https://github.com/Microsoft/vscode/issues/3422

**Comment by daviwil** [comment]
I apologize, I didn't read the release notes carefully enough.  This is mentioned there already.  I'll close this issue since it's already being tracked by #3422. Thanks!
