### ISSUE TITLE
Updates notified before they are available

### ISSUE THREAD

**Issue by alanbirtles** [Microsoft/vscode#35718]
On Centos 7 visual studio code always notifies about an update before it is actually available to install. The Centos repositories at https://packages.microsoft.com/yumrepos/vscode/ seem to take a day or so to be updated but the UI bugs you about an update being available as soon as the update is released. It'd be nice to delay the notification until the update is actually installable

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21651
