### ISSUE TITLE
Integrated terminal doesn't work properly with Chinese characters

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#35717]
- VSCode Version: 1.17.0
- OS Version: Windows 10 1703 (15063.632)

Steps to Reproduce:

1. Open a new window on a folder with Chinese name (as `新建文件夹`)
2. Use ``ctrl+` `` to open the terminal, and enter `dir` to get some output in Chinese, then use `cls` to clean the screen. Some characters will remain in the terminal.
3. When you drag the terminal to resizeit, those characters will disappear.

Reproduces without extensions: Yes

![vscode](https://user-images.githubusercontent.com/18233088/31277198-5fcfa196-aad2-11e7-91be-1fed6f6c3a7d.gif)

**Comment by Stone-Zeng** [comment]
Seems the same issue as #35713 .

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
