### ISSUE TITLE
Unwanted white-space deletion

### ISSUE THREAD

**Issue by talamaska** [Microsoft/vscode#35716]
I'm having issues with the auto formatting of VS code.
When I try to manually align my assignments after saving them all formatting is lost and the code is back to initial default state. Example 
```ts
export namespace ActionTypes {
  export const GET_CLIENTS = '[Clients] Get';
  export const GET_CLIENTS_SUCCESS = '[Clients] Get success';
  export const GET_CLIENTS_FAIL = '[Clients] Get fail';
  export const ADD_CLIENT = '[Clients] Add';
  export const ADD_CLIENT_SUCCESS = '[Clients] Add success';
  export const ADD_CLIENT_FAIL = '[Clients] Add fail';
  export const EDIT_CLIENT = '[Clients] Edit';
  export const EDIT_CLIENT_SUCCESS = '[Clients] Edit success';
  export const EDIT_CLIENT_FAIL = '[Clients] Edit fail';
  export const DELETE_CLIENT = '[Clients] Delete';
  export const DELETE_CLIENT_SUCCESS = '[Clients] Delete success';
  export const DELETE_CLIENT_FAILS = '[Clients] Delete fail';
}
```
after editing manually it looks like this : 

```ts
export namespace ActionTypes {
  export const GET_CLIENTS           = '[Clients] Get';
  export const GET_CLIENTS_SUCCESS   = '[Clients] Get success';
  export const GET_CLIENTS_FAIL      = '[Clients] Get fail';
  export const ADD_CLIENT            = '[Clients] Add';
  export const ADD_CLIENT_SUCCESS    = '[Clients] Add success';
  export const ADD_CLIENT_FAIL       = '[Clients] Add fail';
  export const EDIT_CLIENT           = '[Clients] Edit';
  export const EDIT_CLIENT_SUCCESS   = '[Clients] Edit success';
  export const EDIT_CLIENT_FAIL      = '[Clients] Edit fail';
  export const DELETE_CLIENT         = '[Clients] Delete';
  export const DELETE_CLIENT_SUCCESS = '[Clients] Delete success';
  export const DELETE_CLIENT_FAILS   = '[Clients] Delete fail';
}
```
after saving the code is back to it's initial state.
If there is some setting I don't now which it is, but it is really annoying. I would like to opt out of deleting white-space in the middle of lines. It seems to me that the white space cleaners doesn't only delete white space in the end of the lines.

- VSCode Version: 1.17
- OS Version: Windows 10

Steps to Reproduce:

1. Add spaces with tabs to align assignments
2. save

Reproduces without extensions: Yes

**Comment by talamaska** [comment]
Maybe some clarification, I don't think it mater how I added the spaces - with space or with tab.
I just want to make sure that if this is not a bug, than I would like to have a setting for opting-out

**Comment by mjbvz** [comment]
Yes this is currently the expected behavior. Support for maintaining spaces in formatted code is tracked by: https://github.com/Microsoft/TypeScript/issues/14601

As a workaround, you can disable the built-in formatter by setting:

```json
"typescript.format.enable": false,
```

And then installing another formatter from the marketplace which may support this style.

Closing as upstream
