### ISSUE TITLE
[BUG] Activity Bar refresh bug over loading extension marketplace list

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35719]
- VSCode Version: 1.17.0 c[ be377c0faf7574a59f84940f593a6849f12e4de7 ]
- OS Version: Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3

Steps to Reproduce:

---

[Lang = "CZ/SK"]
Ak budete veľmi rýchlo skrývať a zobrazovať ikony v activity bar, tak bežne sa v panelu zobrazuje práve ten ktorý bol naposledy odkrytý alebo ten ktorý je nad skrytým, to je ok, ale ak takýmto spôsobom otvoríte extension marketplace list, a zároveň počas načitávania extensions bude naďaľej rýchlo skrývať a zobrazovať ikony v Activiry Bar, tak občas sa stane že sa naďalej graficky bude ukazovať ikona v activity bar, niekedy funguje na ňu kliknúť, niekedy nie, ovšem v zoznamu "show/hide" nieje pri danej ikone/položke fajka. Alebo naopak je, ale ikona / položka sa nezobrazuje, niekedy ovšem keď kliknete na prázdne miesto v activity bar, otvoríte aj skrytú položku. Problém je s reprodukovaním, pretože sa to udeje náhodne a len občas / zriedkavo. Ak sa to stane, tak celý panel a aktivity bar je zabugovaný až kým nevypnete a znova nezapnete vscode.

---

[EN - translated by google translator]

If you hide and display icons in the activity bar very quickly, so the one that was last exposed or the one that is hidden is usually in the panel, but if you open the extension marketplace list, you will also be able to open the extension extensions to quickly hide and display icons in the Activiry Bar, sometimes it happens that the icon in the activity bar will continue to be shown graphically, sometimes it's clickable on it, sometimes not, but in the "show / hide" list it is not the icon / brier item. Or vice versa, but the icon / item is not displayed, but sometimes when you click on a blank space in the activity bar, you also open the hidden item. The problem is with reproduction because it happens at random and only occasionally / rarely. If this happens, the entire panel and activity bar is bugged, you must close and again open vscode to fix it.

---

Reproduces without extensions: Yes

![screenshot_84](https://user-images.githubusercontent.com/31345346/31278489-67d78822-aaa5-11e7-8b4e-169357ce8117.png)

---
[lang = "CZ/SK"]
P.s. Ak niekto vie prekladať z češtiny alebo slovenčiny do angličtiny, prosím o pomoc, totiž neco málo po anglicky viem, a neprijde mi že preklad je správny. (aj keď si to dám preložiť spätne, tak to preloží chujovinu).

[EN - translated by google translator]
P.s. If someone can translate from Czech or Slovak into English, please help, I know little about English and I do not think the translation is correct. (even though I'm going to translate it back, so it translates the stupid

**Comment by isidorn** [comment]
Please provide nice reproducable steps and explain nicely and concisely what is the problem. With the current info we can not do much. Can you reproduce with vscode insiders https://code.visualstudio.com/Insiders/
fyi @bpasero

**Comment by Mlocik97-issues** [comment]
I will try said it by my bad English.

Reproduce:
Right click on activity bar and fast show/hide items.
When it will open extension marketplace list by "showing and hidding items" (no you don't want left 
click on extension item / icon). You continue fast show/hide items over loading extensions list.

Result:
Sometimes it will still showed icon when you hide it, but it's not clickable, or sometimes it will still hiden, but you can click on "plain area" in activity bar and it will open something in panel.
Also one time I had 2 same icons in activity bar. It's not easy to reproduce, it happend only sometimes.

**Comment by Mlocik97-issues** [comment]
I will try reproduce it, and record on video.

**Comment by Mlocik97-issues** [comment]
Result:

![screenshot_96](https://user-images.githubusercontent.com/31345346/31299487-f4981ec2-aaee-11e7-8440-d92eaca68385.png)

Right click on panel will do nothing (you can't anymore show/hidden icons), but in real are extensions hidded and debugger showed, only graphically it's rendered otherwise.

**Comment by isidorn** [comment]
@bpasero you might have some good questions here, assigning to you also

**Comment by Mlocik97-issues** [comment]
![screenshot_100](https://user-images.githubusercontent.com/31345346/31330176-8a824026-acdd-11e7-97b7-ed9cc039c936.png)

**Comment by bpasero** [comment]
@Mlocik97-issues can you provide step by step instructions for how to reproduce. Or can you make a video and show the issue?

**Comment by Mlocik97-issues** [comment]
@bpasero Right click on Activity bar, hide show hide show hide show items, but not Extensions... If Other items at least once were hidden, Extension Marketplace list will be opened. If you now will very fast hide / show some items during loading extension list in panel, some items will be graphically hidded (even if you showed them.) or vice versa...


-----

Now I found out something else, simmiliary strange behavior (not bug), if You hide some items, and after use keyboard shortcut it will open item in panel, and also icon on activity bar, if you click on it, it will disappear.

**Comment by bpasero** [comment]
@Mlocik97-issues can you make a screencast of the full flow and attach it here?

**Comment by Mlocik97-issues** [comment]
IN:

- VSCode Version: 1.17.1 c[ 1e9d36539b0ae51ac09b9d4673ebea4e447e5353 ]
- OS Version: Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3

I can't again reproduce "first problem".... (I think it's maybe fixed)

Second problem:

https://youtu.be/wgP2pR3oJhU

**Comment by bpasero** [comment]
@Mlocik97-issues that is weird, are you triggering any action that the "Debug" view suddenly shows up again? Do you have any extensions installed?

**Comment by Mlocik97-issues** [comment]
No, I haven't installed extensions.
