### ISSUE TITLE
Sudden blank screen

### ISSUE THREAD

**Issue by trumbitta** [Microsoft/vscode#35723]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.9
EditorConfig|Edi|0.10.1
material-icon-theme|PKi|2.2.2
project-manager|ale|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
tslint|eg2|1.0.9
file-icons|fil|1.0.5
angular-essentials|joh|0.2.0
Angular2|joh|2.7.0
atom-keybindings|ms-|3.0.2
debugger-for-chrome|msj|3.3.1
angular2-inline|nat|0.0.17
vscode-fileutils|sle|2.7.0
vscode-apielements|vnc|0.6.7
JasmineSnippets|xab|1.0.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Use vscode
2. Fiddle with the file tree, just moving the mouse pointer around, maybe dragging horizontally sometimes

<img width="1552" alt="screen shot 2017-10-06 at 15 55 34" src="https://user-images.githubusercontent.com/462705/31281248-281caf6e-aaaf-11e7-84f4-88bc2ebaaf8e.png">

Reproduces without extensions: Yes

**Comment by trumbitta** [comment]
It happens also trying to open a file via `cmd + p`

**Comment by chrmarti** [comment]
Note: On High Sierra.

**Comment by trumbitta** [comment]
It's happening also with 1.16.1. But it started doing it after I upgraded to 1.17 earlier today.

**Comment by trumbitta** [comment]
Tried to reboot the mac out of desperation. That triggered the autoupdate back to 1.17. And it seems stable so far. The bug is not happening.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35527
