### ISSUE TITLE
Unable to use ctrl-p in the integrated terminal in GNU/Linux

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode#35722]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rust|rus|0.3.1
vim|vsc|0.10.1
---

Steps to Reproduce:

1. Launch and give focus to the integrated terminal
2. Hit ctrl-p

---

Expected behavior:

Previously executed command should be in the buffer ready to execute.

Note: This works as expected on macOS (presumably because cmd-p is used there for Go To File)

---

Actual behavior:

Go To File in command prompt opens

---

Reproduces without extensions: Yes

---

Would it be sane to not trigger Go To File if the terminal has focus?

I realize this is an edge-case and special casing things like this isn't desirable.

I don't want to suggest yet-another-setting because that becomes a nightmare to maintain and troubleshoot.

**Comment by Phrohdoh** [comment]
Bonus information that may or may not be helpful. This is the version of bash that I am running:

```
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Ubuntu 16.04

**Comment by Tyriar** [comment]
ctrl+p is a special keybindings which is whitelisted in the integrated terminal so it skips the shell and goes to the vscode keybinding system. You can get around this by redefining `terminal.integrated.commandsToSkipShell` in your setting and remove `"workbench.action.quickOpen"` from the list.

**Comment by Phrohdoh** [comment]
Ah I see! Thank you for your speedy and informative response @Tyriar.
