### ISSUE TITLE
intellisense for javascript not working for Canvas element

### ISSUE THREAD

**Issue by ramvalleru** [Microsoft/vscode#35727]
- VSCode Version: 1.17
- OS Version: Windows 10

Is there a problem with VScode intellisense to work on HTML 5 'canvas' element. Intellisense doesn't provide auto completion support.

**Comment by mjbvz** [comment]
Can you provide some example code. I see this working in a basic example:


<img width="608" alt="screen shot 2017-10-08 at 8 03 07 am" src="https://user-images.githubusercontent.com/12821956/31317492-2ddec602-abff-11e7-8a5f-633aad3bfb32.png">

**Comment by ramvalleru** [comment]
If I use document.createElement, then recommendation for getContext is being displayed. But when i use getElementById as shown from the below image, getContext is being recommended. 

![canvas](https://user-images.githubusercontent.com/17983707/31317990-fbdd5b72-ac4a-11e7-9d8f-f4d83ac1c7b8.png)

Both createElement and getElementById returns Element type. But I don't understand why VScode only recommends getContext for Element returned using createElement. But when I use getElementById, it works find but no recommendation.

**Comment by mjbvz** [comment]
Yes this is by design. When you create an element we can know its type. When you retrieve it by id, it could be any type so we only show generic suggestions.

Try adding an explicit type cast if you are sure the returned element is a canvas:

```js
var canvas = /** @type {HTMLCanvasElement} */ (document.getElementById('test'))
```
