### ISSUE TITLE
Terminals launched via extensions are sometimes blank

### ISSUE THREAD

**Issue by derekmiranda** [Microsoft/vscode#35728]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-paste-and-indent|Rub|0.0.8
vscode-color|ans|0.4.5
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-filesize|mkx|1.0.0
vscode-open|san|0.1.0
todotasks|san|0.5.0
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Once VS Code open, open Integrated Terminal. Shows up blank but still interactive.

<img src="https://i.imgur.com/y4nEeGN.png"></img>

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@derekmiranda what version of macOS are you on?

**Comment by derekmiranda** [comment]
Sierra 10.12.6

**Comment by fabiospampinato** [comment]
@Tyriar It happens to me as well, steps to reproduce:

- Open a terminal
- Spawn another one via [Terminals](https://github.com/fabiospampinato/vscode-terminals)
- Go to the newly created terminal
- It's blank

If the terminal gets resized, or the whole window gets resized it shows up.

**Comment by derekmiranda** [comment]
@fabiospampinato Hmm it doesn't show up for me at all even after resizing...

**Comment by fabiospampinato** [comment]
@derekmiranda Maybe they are unrelated bugs then, I'm not sure 🤔

**Comment by derekmiranda** [comment]
Update: The problem still persists on the computer previously mentioned but on my personal Macbook, which is also on Sierra 10.12.6, the terminal works fine. Not sure what might be causing this, is it possibly hardware-related?

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/34554

**Comment by egamma** [comment]
@Tyriar I've ran into the same issue when working on the npm-script-runner extension. I've added a repro extension to #34554.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34554
