### ISSUE TITLE
[Error] XHR failed:

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35720]
- VSCode Version: 1.17.0 c[ be377c0faf7574a59f84940f593a6849f12e4de7 ]
- OS Version: Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3

Steps to Reproduce:

1. I was trying reproduce #35719 
2. I hidded icon, but very fast I dragged it in moment, when I will in drag it will refresh activity bar, and icon was placed to "void" = generate error .... also extension marketplace list will still be not loaded.

Reproduces without extensions: Yes

![screenshot_87](https://user-images.githubusercontent.com/31345346/31279749-75418b66-aaaa-11e7-8dfa-b84c55926d69.png)

![screenshot_88](https://user-images.githubusercontent.com/31345346/31280980-6a52d044-aaae-11e7-8865-ff8d71410c3b.png)

**Comment by joaomoreno** [comment]
#34385
