### ISSUE TITLE
Opening folder in second window of VSCode opens in first window of VSCode in error

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#3572]
1. Open VSCode and open a folder for project A
2. Go to File -> New Window
3. In the new window Open the same folder for project A. This will cause nothing to happen as it is still open in the first VSCode window
4. In the new window, open a folder for project B.

Expected: it to open in the new VSCode window
Actual: opens in the first VSCode window, replacing project A as the open folder.

**Comment by bpasero** [comment]
@pieandcakes win10?

**Comment by pieandcakes** [comment]
Sorry, this is for Ubuntu 14.04. I haven't tried it on windows to see if its the same issue or not.

**Comment by bpasero** [comment]
@pieandcakes my speculation is that the first window gets active but is not ordered to the front, and actions are targeting the first window even though not in front.

**Comment by bpasero** [comment]
I cannot reproduce, see attached gif of what I see when following the steps.

![untitled](https://cloud.githubusercontent.com/assets/900690/14040299/50102d50-f266-11e5-979f-736a6f63c75c.gif)

**Comment by bpasero** [comment]
The only issue I do see is that the background window is not coming to the foreground.
