### ISSUE TITLE
Bugs in terminal showing Chinese character 

### ISSUE THREAD

**Issue by banziFD** [Microsoft/vscode#35726]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.13.1

---

Steps to Reproduce:

1.Any Chinese character will leads terminal to show "fragment"
2.

Reproduces without extensions: Yes/No

**Comment by Mlocik97-issues** [comment]
dupl #35717

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
