### ISSUE TITLE
Support import intellisense in <script> tags in .html files

### ISSUE THREAD

**Issue by Rich-Harris** [Microsoft/vscode#35732]
The new autocomplete suggestions for `import` in 1.17 are great — would it be possible to support them inside `<script>` tags in .html files?

**Comment by aeschli** [comment]
@mattbierner Where are the path completions implemented?

**Comment by snuggs** [comment]
+1 @Rich-Harris Great feature request! 👍

**Comment by aeschli** [comment]
duplicate of #29315

**Comment by Rich-Harris** [comment]
Thanks for taking a look @aeschli. Is this definitely a duplicate of #29315 though? That issue concerns type information, not autocompletion (though I realise that you may get both for free once VSCode understands what `import` in the context of `<script>` means).

**Comment by aeschli** [comment]
It comes all together. We need to configure the service for JavaScript inside HTML so it can access the imported files.
