### ISSUE TITLE
Old Icon, when you are not updating, but use new install (by installator from web)

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35736]
- VSCode Version: 1.17.0 c[ be377c0faf7574a59f84940f593a6849f12e4de7 ]
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. If you will install VSCode by installator from website, and in installator you chcecked "create desktop icon", it will create old icon on desktop (blue).

**Comment by Mlocik97-issues** [comment]
#35736
#35683

**Comment by Tyriar** [comment]
I believe this issue should resolve itself after a restart
