### ISSUE TITLE
Linting issue with Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by batatop** [Microsoft/vscode#35737]
- VSCode Version: 1.17.0
- OS Version: Windows 10 Education

I'm using Bash on Ubuntu on Windows. I tried to setup an environment for Python development. Everything works except the linting support. Even if I download the reqired files, it gives an error of "pylint is not instaled". . I think that the problem is caused because of the pylint's path. However, I  couldn't solve the problem. I would appreciate any help. Thank you...

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Please file this issue against the python ext repo https://github.com/DonJayamanne/pythonVSCode
