### ISSUE TITLE
Terminal weird behavior after 1.17 update

### ISSUE THREAD

**Issue by GhaithZamrik** [Microsoft/vscode#35738]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. am not sure, while running gulp with auto-refresh at some point the text in the terminal went blurry, then when I tried to adjust the size of it I got this.
2. I had to kill the current process shut down the terminal and open it again, and it went back to normal. 
nothing serious, thought to report this.
<img width="1120" alt="screen shot 2017-10-06 at 5 49 14 pm" src="https://user-images.githubusercontent.com/24314871/31286541-c52a64d6-aabe-11e7-92c3-e0a446563e3f.png">

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
@GhaithZamrik do you have a hi DPI and a low DPI monitor and you moved the window between them?

**Comment by Tyriar** [comment]
Could be https://github.com/Microsoft/vscode/issues/34320
