### ISSUE TITLE
Removed files persisted in cache and displayed in search/quick open file results

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#35745]
- VSCode Version: 1.17.0
- OS Version: Windows 10

Steps to Reproduce:
1. create file `test1` with content `test`
2. create file `test2` with content `test`
3. search `test` and see both files in results
4. delete file `test2`
5. search `test` and see both files in results again

Also there is can be same issue with quck open files list, but i cant reproduce it again

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Text search will show matches if the deleted files is still open in an editor. When you close the editor, the match will no longer show up.
