### ISSUE TITLE
node.js : f12 - "GO TO DEF" Does not go to node_modules definition in required module

### ISSUE THREAD

**Issue by TylerSustare** [Microsoft/vscode#35758]
- VSCode Version: 1.17.0
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Require local module.
2. Require the package.
`const internalSuperTool = require('../../../thing');`
3. `f12` or go to definition on method of `internalSuperTool.makeAllThingsGreat`
4. "No definition found for 'makeAllThingsGreat'"

Reproduces without extensions: Yes

**Comment by TylerSustare** [comment]
-- UPDATE -- 
This appears to be a problem when trying to perform a **go to definition** on a variable passed into a function as well.

**Comment by TylerSustare** [comment]
@mjbvz What additional information would be helpful?

**Comment by mjbvz** [comment]
Sorry, looks like my comment wasn't posted when I added that badge. 

Can you please share a small example project that demonstrates this problem. Also try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your workspace. This will tell VS Code to treat all js files in the workspace as part of the same project

Finally, try [enabling `ts-check`](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) in your file. This can help track down issues where our intellisense can't find a module

**Comment by TylerSustare** [comment]
I will try these today and report back. Thanks!

**Comment by TylerSustare** [comment]
@mjbvz adding the `jsconfig.json` file at my root with the config below solved my issue. 
Switching back to VS Code from WebStorm!

```{
{
    "compilerOptions": {
        "target": "ES6"
    },
    "include": [
        "*"
    ]
}
