### ISSUE TITLE
[Feature request or question] jQuery & AngularJS suggestions in JS.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35755]
Can VSCode suggest a jQuery & AngularJS Code? like as:

`$(document).re` to -> `$(document).ready(|)` ... | = cursor move.
or
`$sc` to -> `$scope.|` ... | = cursor move.

Or if yes, how (how enable it)?

**Comment by KyleMcNutt** [comment]
@Mlocik97-issues 

You can add this by installing the type definitions for each of these libraries and then referencing them in a jsconfig.json. You can see this StackOverflow: https://stackoverflow.com/questions/38930984/how-to-set-intellisense-for-angular-js-and-javascript-in-visual-studio-code-with for details on this.

**Comment by mjbvz** [comment]
Yes, if you are using globals like `$` for jquery, please try installing the typings for that library. 

[Automatic type acquisition](https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition) should kick in if you use require or import statements
