### ISSUE TITLE
Unable to close files with ctrl-w in normal mode with vscodevim

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode#35753]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rust|rus|0.3.1
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Open a file
2. ctrl-w

*Note*: I was in normal mode while testing this. If I were in insert mode this obviously would have a different result.

Reproduces without extensions: No (caused by vscodevim)

**Comment by rebornix** [comment]
Please file issues against VSCodeVim.
