### ISSUE TITLE
Chinese characters in the vscode terminal has garbled

### ISSUE THREAD

**Issue by APieceOfCake** [Microsoft/vscode#35754]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. When there is Chinese characters in the page and scrolls a line
![222](https://user-images.githubusercontent.com/26304195/31290211-32eff35c-aafe-11e7-81d3-9a7015b61ce5.JPG)

![default](https://user-images.githubusercontent.com/26304195/31290124-edd59dee-aafd-11e7-927d-7f2f38b61a76.JPG)

**Comment by meowao** [comment]
Duplicate #35660
