### ISSUE TITLE
Nodejs debug wont run if machine is offline.

### ISSUE THREAD

**Issue by Lukas238** [Microsoft/vscode#35750]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
FreeMarker|dco|0.0.9
python|don|0.7.0
EditorConfig|Edi|0.10.1
php-debug|fel|1.11.1
auto-rename-tag|for|0.0.14
code-runner|for|0.7.2
macros|ged|1.2.0
Language-TodoTXT|ger|0.0.1
beautify|Hoo|1.1.1
vscode-browser-sync|jas|1.2.0
docthis|joe|0.4.8
vscode-insertdatestring|jsy|2.1.0
ecdc|mit|0.10.3
prettify-json|moh|0.0.3
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1
partial-diff|ryu|0.3.3
stylelint|shi|0.29.1
sort-lines|Tyr|1.3.0
markdown-pdf|yza|0.1.7
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1. Open VSCode and write a node .js program.
2. Run the debuger with Node.js.
This is my current settings for **launch.json** file.
```
{
        "version": "0.2.0",
        "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 5858
        },
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${file}"
            }
        ]
    }
```
3. The debug console windows will open and output the message ```Debugging with inspector protocol because Node.js v8.6.0 was detected.```, but nothing else will run.

Reproduces without extensions: Yes

## Developers Tools Console Log
```
extensionHost.ts:384 [Extension Host] Message Debugging with inspector protocol because Node.js {0} was detected. didn't get externalized correctly.
---
ipc.cp.ts:195 IPC "Debug Telemetry" crashed with exit code 1
---
messageService.ts:125 Unable to launch debug adapter from 'c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.node-debug2/out/src/nodeDebug.js'.
```

**Comment by Lukas238** [comment]
All is working fine on version 1.17.

Not sure what was the problem in my ve 1.16 version.

Thanks!!

**Comment by roblourens** [comment]
Cool, thanks!
