### ISSUE TITLE
Weird Go To Implementation Command Palette behavior

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#35759]
- VSCode Version: 1.17.0-insider 2017-10-3 commit 5316a2
- OS Version: Windows 10

Steps to Reproduce:
1. Open/create a C# project with the following text (2 classes that implement an interface)
```C#
interface IA {}

class A : IA {}
class B : IA{} 
```
2. Place the caret on the definition of `IA`
3. Press F1 to open the command palette
4. Type "go to implementation" to bring up the go to implementation command

5a: click on the "go to implementation" entry in the drop down: a code peek view appears allowing you to choose between viewing A and B
5b: press enter to go to implementation: VSCode navigates directly to A without showing the code peek

If you look closely, you can see the code peek flicker into the screen. It looks like the "enter" is improperly getting passed into to code peek menu after it's shown, hence only clicking the command name shows you the menu.

**Comment by rchande** [comment]
Note that directly invoking Go To Implementation using the keyboard shortcut also shows the peek menu 
![image](https://user-images.githubusercontent.com/3751401/31292665-2a080362-aa89-11e7-9637-07b07301a3d5.png)

**Comment by jrieken** [comment]
This is key-up vs key-down

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6146
