### ISSUE TITLE
Lightbulb follows the cursor around, when there really isn't a problem.

### ISSUE THREAD

**Issue by daveharmswebdev** [Microsoft/vscode#35757]
I'm simply typing and the lightbulb appears. It's not needed at the moment, no suggestions are required or wanted. I liked it better when the light bulb only appeared when I clicked on a red squiggly line.

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
react-native-react-redux|EQu|1.4.1
EditorConfig|Edi|0.10.1
mithril-emmet|Fal|0.6.1
beautify|Hoo|1.1.1
Angular-BeastCode|Mik|5.0.5
jsx|Twe|0.0.1
elm-format|aba|0.1.0
html-snippets|abu|0.1.0
htmltagwrap|bra|0.0.3
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
tslint|eg2|1.0.9
vscode-angular2-emmet|jak|2.0.3
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
Angular2|joh|2.7.0
csharp|ms-|1.12.1
js-atom-grammar|ms-|0.1.13
chai-snippets|nwh|0.1.0
vscode-icons|rob|7.14.0
elm|sbr|0.15.1
aspnet-helper|sch|0.6.3
es6-mocha-snippets|spo|0.0.4
autoimport|ste|1.2.2
vscode-react-native|vsm|0.4.2

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
@daveharmswebdev Which language are you seeing this with?
