### ISSUE TITLE
Double Width Character aren't 

### ISSUE THREAD

**Issue by pradyunsg** [Microsoft/vscode#35756]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Use a monospace font with double width characters in the terminal
2. Witness artifacts. (more below)

Reproduces without extensions: Yes

---

I have a monospace font with double width characters. In the integrated terminal, these characters are trimmed and/or the spacing between them is garbled. 

<img width="150" alt="screen shot 2017-10-06 at 11 20 09 pm" src="https://user-images.githubusercontent.com/3275593/31291239-f0f6707c-aaec-11e7-9ad8-91653b9de534.png">

This happens with updated VSCode, not with the previous version.

Font: Iosevka Nerd Font

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35649
