### ISSUE TITLE
Always use CRLF when copying on Windows

### ISSUE THREAD

**Issue by KevinGrealish** [Microsoft/vscode#35766]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
python|don|0.7.0
tslint|eg2|1.0.9
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. in code copy several lines of text.
2. paste that text into notepad.exe or a command prompt (cmd).
BUG: Line breaks are gone and all text pastes as a single line.
EXPECT: Line breaks to be preserved. 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
We currently place in the clipboard text with the file's line terminators. If the file uses LF (`\n`), we place lines delimited by LF in the clipboard
