### ISSUE TITLE
VSCode window not given focus when invoking with -r from command line

### ISSUE THREAD

**Issue by windexlight** [Microsoft/vscode#35765]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.0
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
rewrap|stk|1.5.1
vscode-terminal-here|Tyr|0.0.5

---

Steps to Reproduce:

1. Open VSCode 
2. With code command accessible in path, open either a PowerShell or Command window, and run:
3. code -r test.txt
4. Expected behavior is that the existing VSCode window will be activated / given focus.
5. Instead, the VSCode icon on the taskbar flashes orange, but the window is not activated, requiring an extra click to activate it.

This is annoying when trying to use VSCode as an editor for writing git or svn commit messages (i.e. when used as GIT_EDITOR or SVN_EDITOR).

As a workaround for now, I am able to use this code-focus.cmd file to activate the window before invoking VSCode:

`@echo off`
`echo (new ActiveXObject("WScript.Shell")).AppActivate("Visual Studio Code"); > %temp%\focus.js`
`cscript //nologo %temp%\focus.js`
`del %temp%\focus.js`
`code %*`

I can then invoke this file instead of VSCode in my GIT_EDITOR and SVN_EDITOR environment variables.

I've just started using VSCode for this purpose, so don't know if this behavior is new (due to either the Windows 10 Creator's Update or the September 2017 update to VSCode) or has always been this way.

May be related to: electron/electron#2867

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@the-ress maybe you have an idea as the author of the `windows-foreground-love` module we are using from you. We still call [`allowSetForegroundWindow`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L84) with the PID of the main process as before but the task bar on windows is back to blinking for some reason.  

Steps:
* start code normally
* from the command line start code with "`-r`" flag to reuse the last instance
=> window blinks in task bar but is not put to front

**Comment by the-ress** [comment]
I'll look into it later today.

**Comment by Tevic** [comment]
Also met this problem from 1.16,i tested 1.15 and below it works fine,but 1.16 and 1.17 doesn't.

**Comment by the-ress** [comment]
I can reproduce the problem on insiders. (It works fine on 1.14.2.)

`windows-foreground-love` and `windows-mutex` modules are missing in my insiders installation so `allowSetForegroundWindow` cannot be called. They somehow got removed from `npm-shrinkwrap.json` in 05fc36e1701d68d2fb50c107aa200428f38a883e

**Comment by bpasero** [comment]
@the-ress wow great catch!

**Comment by joaomoreno** [comment]
CC @roblourens

**Comment by windexlight** [comment]
Thanks all, for the prompt action and fix.

**Comment by stefangabos** [comment]
Yeah! Finally working - this was broken for the past two or three official releases. Thank you!
