### ISSUE TITLE
Debugger stopped working after updating the insider build

### ISSUE THREAD

**Issue by rajivkanaujia** [Microsoft/vscode#35762]
- VSCode Version: Code - Insiders 1.18.0-insider (af6ca44db81f5186d3104226c8e76e026789ce20, 2017-10-06T07:50:45.639Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-docker|Pet|0.0.18
node-debug2|ms-|1.17.2
java|red|0.11.0
code-spell-checker|str|1.4.6
vscode-react-native|vsm|0.4.2
local-history|xyz|1.5.2

---

Steps to Reproduce:
1. See steps in https://github.com/Microsoft/vscode-chrome-debug/issues/495 

Error received- Debug adapter process has terminated unexpectedly
There is no output via "server"
![image](https://user-images.githubusercontent.com/9750485/31303745-5445982c-aae0-11e7-8f29-ab6374c2417e.png)

**Comment by roblourens** [comment]
Could you set `"trace": true` in the launch config, and see whether it prints a path to a log file in the debug console? And upload it here?

**Comment by rajivkanaujia** [comment]
Hi @roblourens - Please note that the "Stable" build does not have this issue. Below is output I get 
```
Debugging with legacy protocol because Node.js version could not be determined.
26794: launchRequest: program '/Users/<project-name-folder>/node_modules/.bin/sls' seems to be the generated file
/usr/local/bin/node --debug-brk=31333 --nolazy node_modules/.bin/sls invoke local -f hello --data {} 
26794: _attach: address: 127.0.0.1 port: 31333
(node:26796) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
26794: _terminated: target exited
26794: _terminated: target closed
26794: shutdown: kill debugee and sub-processes
26794: disconnectRequest: send response
```

**Comment by roblourens** [comment]
Can I see your launch config? Is `node` not on your path?

We do need to change it to fall back to 'inspector' protocol in this case...

**Comment by rajivkanaujia** [comment]
Node is in path.  If VSCode-darwin-stable works, then it should not be a path issue.  In addition, nvm/node works on Terminal/iTerm.

Here is the launch config
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "trace": true,
        "name": "hello",
        "program": "${workspaceRoot}/node_modules/.bin/sls",
        "args": [
          "invoke",
          "local",
          "-f",
          "hello",
          "--data",
          "{}" ]
        }
    ]
  }  
```

**Comment by roblourens** [comment]
Thanks. 

> Node is in path. If VSCode-darwin-stable works, then it should not be a path issue.

True, but the debug adapter hasn't been changed lately. Is stable updated to 1.17?

**Comment by rajivkanaujia** [comment]
Stable is running 1.17.

**Comment by roblourens** [comment]
Very strange. For now, adding `"protocol": "inspector"` should work as a workaround.

**Comment by rajivkanaujia** [comment]
Actually, `"protocol": "inspector",` does not work either. Already tried that approach.

**Comment by roblourens** [comment]
What's the error/trace output from that?

**Comment by rajivkanaujia** [comment]
No errors, besides one that was mentioned when I logged the bug.
--> Error received- Debug adapter process has terminated unexpectedly
IMO, changes between 1.17 stable and 1.18 insider must have caused some regression.

**Comment by roblourens** [comment]
So two issues:

- With "legacy", it seems to think it can't find node on the path
  - We need to default to inspector here and maybe figure out why it's having an issue determining the node version
- With "inspector" the debug adapter crashes immediately.

@isidorn Since the adapters haven't been updated in Insiders (well, node2 was updated today but not as of this issue), can you think of anything that changed on the vscode side?

@rajivkanaujia WIth "inspector" when you run with `"trace": true`, does it write a path to a log in the debug console? Can you upload it here?

**Comment by isidorn** [comment]
@roblourens  we have dropped lots of deprecated commands (startSessionCommand for example. Full list can be seen here https://github.com/Microsoft/vscode/issues?q=is%3Aissue+assignee%3Aisidorn+milestone%3A%22October+2017%22+is%3Aclosed+label%3Adebt

If it is not clear what might be the issue and if you can repro this problem let me know and I can bisect commits to find the cause.

**Comment by rajivkanaujia** [comment]
@roblourens - the debugger dies before even it can put something out. There was a new update on insider. After installing it, the debugger still crashes. The only information it puts out is `Debugging with inspector protocol because Node.js v8.6.0 was detected.`

**Comment by rajivkanaujia** [comment]
@isidorn - to reproduce, follow instructions mentioned when I logged the bug. See https://github.com/Microsoft/vscode-chrome-debug/issues/495

**Comment by roblourens** [comment]
I can't repro this with the `serverless` config from that other issue. 

Is there any output in the Extensions output channel?

![image](https://user-images.githubusercontent.com/323878/31466604-a853a350-ae8c-11e7-8ec7-15bc2e9e21e8.png)

**Comment by roblourens** [comment]
It should be there in the dropdown. If not, it may just be that it hasn't been needed yet.
