### ISSUE TITLE
Fast path for quick open by filename

### ISSUE THREAD

**Issue by TimCondon** [Microsoft/vscode#35761]
I'm on Linux working with very large code trees over a network filesystem (~250,000 files, 200 GB). 

In this environment, the quick open command takes several minutes when first searching for a new file - presumably because it's looking across this entire, very large file system. Given the full feature set of quick-open, the slow performance makes sense - but I really need to solve the simpler subproblem of typing an exact filename (or even exact path) of a source file and getting it to open within say 5 sec (it currently takes 5 min). 

The subset of files I care about is small, and doesn't change often. I only need this to work for a limited set of extensions (ie, .cpp, .h. .py) and a limited subset of the filesystem where we store source files. It seems like this should be easy enough to handle with a small cache of source files scraped out of a larger tree...

Do I have any options for this with VS Code's current implementation?  I've already pruned some folders with file.excludes, but it doesn't seem to make a noticeable impact on performance. Since the editor is responsive after I've issued a query once, is there a way to write a script to prepopulate a cache with the files I care about?

I'm also willing to write my own extension, but I can't find a way take additional user input (ie a target filename) from the command palette - all the examples simply execute based on the name of the command. If this feature is easy to add, I'd happily do the legwork to build my own cached search over a limited database of relevant files.

Any help would be much appreciated!!

**Comment by hugoj-goncalves** [comment]
When I need something like this and I know exactly where it is I just use the integrated terminal to open the file. (*code ...*)

**Comment by FHTheron** [comment]
Existing extensions that navigate the filesystem (not fuzzy finding in the workspace):
https://marketplace.visualstudio.com/items?itemName=jakelucas.code-file-nav
https://marketplace.visualstudio.com/items?itemName=leizongmin.quick-open

The fuzzy search in each directory makes it fast enough to navigate around, but a version of this which limits scope to the workspace could be perfect. Perhaps zsh-style shorthand that matches into directories. For example, "s/c/m" matching "src/core/main.c".

**Comment by chrmarti** [comment]
You could use the `search.exclude` setting to make QuickOpen index only the interesting parts of your folder.

**Comment by chrmarti** [comment]
@TimCondon Also: Which OS and what version of VSCode is this?

**Comment by TimCondon** [comment]
@FHTheron Thanks for pointing those out! I've looked at both and while they offer some solution for the "exact path" problem, I really want something that can quickly match exact filename across some subset of directories.

@Chrmarti I'm on RHEL v.7.2, and VSCode v.1.16.1.  Does search.exclude do substantially more than file.exclude (which, as noted above, I've tried and don't see much of an impact?). It may be worth noting that exhaustive file searching often seems faster than using the quick open command...though this could be because I run exhaustive search in the background, while quickopen goes away if I click anywhere else.

**Comment by chrmarti** [comment]
`search.exclude` only adds to `files.exclude`. What do you mean by exhaustive file searching? Does 1.17 perform any better? That uses ripgrep for listing all files.

**Comment by TimCondon** [comment]
@chrmarti By "Exhaustive Searching" I mean opening the search view in the VSCode sidebar and typing the name of my class. I just did a quick test searching for a class name I've never opened, and the sidebar search returns 100 results (including the file itself) in under a second, while running QuickOpen from the workbench with the same string takes over a minute to return any results at all...

I'll definitely give 1.17 a try and see if it improve performance. Thanks for the info!

**Comment by chrmarti** [comment]
In 1.17 QuickOpen is powered by the same engine (ripgrep) as the text search. Let me know how that goes. 👍

**Comment by TimCondon** [comment]
@chrmarti - Wow, the 1.17 update completely delivered! QuickOpen is now fluid and completely responsive! Please thank the team for this update!

--Tim

**Comment by chrmarti** [comment]
Thanks @TimCondon !
