### ISSUE TITLE
Won't open all previously opened windows when re-run the app.

### ISSUE THREAD

**Issue by terrybleger** [Microsoft/vscode#35769]
Sublime and other text editors are able to remember all previously opened windows when the app has exit and re-run again, only VS Code is doesn't. And It's almost 2018 bruh.

- VSCode Version: 1.17.0
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open two or more folders in two or more separate windows.
2. Exit VS Code.
3. Open VS Code once again will only open up a single window instead of all previously opened windows.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
`"window.restoreWindows": "all"`
