### ISSUE TITLE
Sort Lines Ascending command should use encoding ordering

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#35767]
It's using a case-insensitive ordering, where all the "A"s are grouped together, then all the "B"s, and so on. As a programmer, this is such an odd choice. Uppercase letters are always ordered before lowercase letters, like with ASCII/UTF-8.

#### Steps to reproduce:

1. Enter this text:

```
a
B
```

2. Select both lines. Invoke the "Sort Lines Ascending" command.
3. Nothing changes.

Compare with `echo "a\nB" | sort`:

```
$ echo "a\nB" | sort
B
a
```

---

This pertains to the Sort Lines Descending command too, obviously.

I should add that the files in the file browser should be listed this way too, but aren't; they're listed in the case-insensitive way, which subverts the purpose of naming special files with uppercase letters, like Makefile and Dockerfile. If they're not listed first, then there's no point in using uppercase letters to name them.

---

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
php-formatter|Sop|0.2.4
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
javadebugger|don|0.1.5
python|don|0.7.0
phpunit|ema|2.1.1
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
code-runner|for|0.7.2
vscode-javac|geo|0.0.46
phpcs|ika|0.7.0
Go|luk|0.6.66
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
cpptools|ms-|0.13.1
Ruby|reb|0.15.0
rewrap|stk|1.5.1
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
