### ISSUE TITLE
Add built in UI based merge conflict tool

### ISSUE THREAD

**Issue by qwert789** [Microsoft/vscode#35760]
Great feature for code and a lot of people would be built in UI based GIT merge conflict tool, which would allow easily to select relevant changes and preview the final result, here some examples:

Git Kraken example:
![merge-tool-1-copy-1](https://user-images.githubusercontent.com/1618071/31293098-a492b4b0-aade-11e7-829e-c081f4722458.png)

Visual Studio example:
![vs](https://user-images.githubusercontent.com/1618071/31293135-cbf0ac42-aade-11e7-9cb9-b2cc971cf8b4.png)

**Comment by joaomoreno** [comment]
#5770
