### ISSUE TITLE
nested placeholder of snippet is not placeholder in "Choice" or keep placeholder if outer is deleted

### ISSUE THREAD

**Issue by taketori** [Microsoft/vscode#35779]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.66
vs-script-commands|mkl|4.14.0

---
- What I am struggling with:
setting a snippet which includes optional variables.
- What I expected:
  - ("Choice" placeholder) Vscode select placeholders text if they exist in picked item.
  - (nested placeholder) Inner placeholder whose outer placeholder was deleted is not focused on.

Steps to Reproduce ("Choice" placeholder):

1. Add a snippet like below to my go.json
```
	"variable declaration =": {
		"prefix": "var=",
		"body": "var ${1:name1, name2...} ${2|${3:type} = ${0:0...},= ${0:0...},${3:type}|}",
		"description": "variable declaration with expression.\neither \"type\" or $0 is optional."
	},
```
2. Input "var=", press "Tab" key twice (focus on 2nd placeholder) and pick anything.
3. Vscode inputs like `${0:0...}`, not `0...`, and cursor is right after text which vscode inputted or next placeholder if it exists.

Steps to Reproduce (nested placeholder):

1. Add snippet like below to go.json
```
"body": "var ${1:name1, name2...}${2: ${3:[type]}} = $0",
```
2. Input "var=", press "Tab" key twice to focus on 2nd placeholder.
3. Press "Delete" key to delete the placeholder.
4. To focus on $0 placeholder, pressing "Tab" key 2 times, not once, is needed.

**Comment by jrieken** [comment]
> Vscode inputs like ${0:0...}, not 0..., and cursor is right after text which vscode inputted or next placeholder if it exists.

There is no support for choice elements being another snippet. The ["spec"](http://manual.textmate.org/snippets.html#multiple-choices) isn't very clear but looking at how TextMate behaves we aren't too far off. Tho it seems TM isn't taking the contents as is but the printable values. Is that what you expect?

**Comment by taketori** [comment]
if you meant that "printable" is not like `${3:type} = ${0:0...}`, but `type = 0...`, Yes, I want elements in "choice" become another snippet.
In other words, I expect the [grammer](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) of vscode snippet is like below:
```
any         ::= tabstop | placeholder | choice | variable | text
tabstop     ::= '$' int | '${' int '}'
placeholder ::= '${' int ':' any '}'
choice      ::= '${' int '|' any (',' any)* '|}'    <- preferably
    or
choice      ::= '${' int '|' tabstop | placeholder | variable | text (',' tabstop | placeholder | variable | text)* '|}'
~~snip~~
```
