### ISSUE TITLE
terminal renderring problem

### ISSUE THREAD

**Issue by CHL2** [Microsoft/vscode#35773]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
xml|Dot|1.9.2
tslint|eg2|1.0.9
beautify|Hoo|1.1.1
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.3.1
java|red|0.11.0
vscode-icons|rob|7.14.0
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. 
2.
![image](https://user-images.githubusercontent.com/18417342/31304191-5f34ff56-ab4f-11e7-8302-52b64b7fac8e.png)

Reproduces without extensions: Yes/No

**Comment by tonny-zhang** [comment]
https://github.com/Microsoft/vscode/issues/35774 

I have the same problem

**Comment by windyflying** [comment]
I have the same problem, too.
![qq 20171007114443](https://user-images.githubusercontent.com/13942593/31304507-2210d2ac-ab55-11e7-83cc-a2496a608fae.png)

**Comment by WaveFunctionP** [comment]
Same problem here:

https://cdn.discordapp.com/attachments/219866789067096065/366069604734337025/unknown.png

**Comment by andreiucm** [comment]
![terminal problem](https://user-images.githubusercontent.com/19815046/31307884-257b5564-ab75-11e7-9d83-ad6b374ea3a9.png)

I have problem too (1. too much space between characters. 2: the lines are not dropped -> so if you write to big command line you can't see it)
Latest VSCode
Linux 16.04

**Comment by he4d** [comment]
Same for me..
![img](https://user-images.githubusercontent.com/591188/31316106-bc8c1ae0-ac26-11e7-8b89-23097585db83.png)

Fedora 26 (using Xserver)
VSCode 1.17.0

**Comment by JaxomofRuatha** [comment]
![fishterminal2](https://user-images.githubusercontent.com/18075641/31325155-9d67fd42-ac7f-11e7-9039-e2cda8a9ac02.png)

![fishterminal1](https://user-images.githubusercontent.com/18075641/31325160-a7295b6e-ac7f-11e7-8c66-a5d3092bc4b5.JPG)

Same issue happening for me, using Fish. It happens for all fonts that I've tried using (including other monospaced fonts) besides Consolas and Monospace. If I use any Oh My Fish themes, the entire render seems to overlap and not display correctly, the cursor doesn't show up, and any output half-displays under the initial command input.

Windows 10 using Windows Subsystem
VSCode 1.17.0
Fish 2.6.0

**Comment by stargriv** [comment]
I have the same issue on RHEL 7.3 + VSCode 1.17.0 + integrated terminal + zsh + Input Mono Condensed Light:
![image](https://user-images.githubusercontent.com/3427633/31330601-63b43e3e-acdf-11e7-8e88-606916ad1c80.png)

**Comment by Tyriar** [comment]
CJK right side of char remaining issue: https://github.com/Microsoft/vscode/issues/35660
Proportional font support: https://github.com/Microsoft/vscode/issues/35681 (use a monospace font in the meantime: `"terminal.integrated.fontFamily": "monospace"`
Fedora issue with fonts being chopped off: https://github.com/Microsoft/vscode/issues/35644
