### ISSUE TITLE
The console shows the ghost when I use Chinese

### ISSUE THREAD

**Issue by tonny-zhang** [Microsoft/vscode#35774]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-npm-script|eg2|0.2.1
search-node-modules|jas|1.2.0
Go|luk|0.6.66
mssql|ms-|1.2.0
csharp|ms-|1.12.1
vscode-icons|rob|7.14.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. The console show the ghost when I use Chinese, Here is the screenshot

![_20171007112759](https://user-images.githubusercontent.com/1396702/31304395-d186a674-ab52-11e7-834a-d89dbb97c288.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
