### ISSUE TITLE
Double Click Select Is confused with "-----"

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#35775]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.1

Doubleclick select is confused with "--------"

![image](https://user-images.githubusercontent.com/6321426/31304607-035649d0-aaf3-11e7-8b98-a9df3fb3ae74.png)

t("hello")
t("____________")
t("------------")
---

Steps to Reproduce:

1.Paste the 3 lines above
2.Doubleclick the text inside the quote

Reproduces without extensions: Yes/No

**Comment by kleinfreund** [comment]
What is the expected behavior?

**Comment by icuurd12b42** [comment]
>What is the expected behavior?
It should select the ------- excluding the "" like it does for t("______") and t("Hello")

Since it's a string the selection should end at the encounter of the string delimiter " or ' whatever is used. it looks like it's not taking that into account

some other examples with the same problem
t('=======')
t("=======")
t("+++++++")
t("~~~~~~~")
t("```````")
t("@@@@@@@")
t("#######")

**Comment by icuurd12b42** [comment]
![image](https://user-images.githubusercontent.com/6321426/31311545-82b5fd86-ab7c-11e7-9a6e-ef53c89772bc.png)

**Comment by icuurd12b42** [comment]
Above is an simulation where I would want to change the === to == by double clicking the === and type == to replace the selection. but since it grabbed the " as well, if unnoticed will result in 
if(Name==George")

**Comment by alexandrudima** [comment]
Word selection works by classifying characters in 3 buckets:
* word characters
* word separators (controlled via `editor.wordSeparators`)
* whitespace

It is implemented language independent and therefore does not take into account that `"`, `(` or `)` have syntactical meaning. The default value for `editor.wordSeparators` is `` "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?" ``, so all these characters get classified as word separators.

When double clicking, the character type is determined and selection is expanded to encompass all neighbouring characters sharing the same type.

For a more "logical" selection expansion I can recommend using `Expand Select` and `Shrink Select` which try to find strings, brackets, etc.

**Comment by icuurd12b42** [comment]
>I can recommend using Expand Select and Shrink Select which try to find strings, brackets, etc.
Sorry these don't work to fix the selection in both the
if(Name==="George")
and the
t("-----------")
examples

I know this is an edge case scenario, but it's those that get you all the time.... it breaks my programming "symphony" ;)

Really not sure how this can be addressed, I'm sure the guy trying to fix this will loose is mind ;)
Suggestion:
If the character double clicked is a word separator it should stop the selection at the first word separator character that is not the same as the on clicked

![image](https://user-images.githubusercontent.com/6321426/31350214-55ce96e2-acf4-11e7-8b17-08f20404ef59.png)

This implies you have 2 methods of selection in your code, the current one and the one that stated off when you clicked on a word sep in the first place

**Comment by kleinfreund** [comment]
> If the character double clicked is a word separator it should stop the selection at the first word separator character that is not the same as the on clicked

I like this idea in theory. I don’t know about any complexity/performance implications, though.
