### ISSUE TITLE
Favorite/Bookmark Project to pin it on top when start program

### ISSUE THREAD

**Issue by pansitwattana** [Microsoft/vscode#35777]
Feature Request
1. Pin my fav. project
2. Open Recent -> Sort my fav project first
3. When program start, show my fav project

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
