### ISSUE TITLE
Toggle comment  sets the cursor before the comment

### ISSUE THREAD

**Issue by rhernandog** [Microsoft/vscode#35776]
- VSCode Version: 1.17.0
- OS Version: Windows 7 64 bit

Steps to Reproduce:

1. Create a line comment using the **Toggle Line Comment** keyboard shortcut, on an empty line, with no code in it. The cursor is set to the left of the comment: `$//`. In the previous version the cursor was set after the comment: `// $`. (I used the dollar sign to point where the cursor is after creating the comment).

Reproduces without extensions: Yes

**Comment by apratheek** [comment]
I'm facing the same issue as well

- VSCode Version: 1.17.0
- OS Version: Ubuntu 16.04
- Language: TypeScript 2.5.3

**Comment by abarnhard** [comment]
Same issue:
VSCode: Version 1.17.0 (1.17.0)
OS: macOS HighSierra 10.13
Lang: Python

**Comment by keithro** [comment]
Me too.
VSCode: Version 1.17.0
OS: macOS Sierra 10.12.6
Language: JavaScript

**Comment by alexandrudima** [comment]
Duplicate of #35673
