### ISSUE TITLE
Add Ctrl+Right behavior option

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3577]
Ctrl+Right behaves like sublime, it goes to the end of the current word.  

VS (and other Windows editors such as notepad, word) goes to the beginning of the next word.

To satisfy both camps we should add an editor option to control this behavior.

**Comment by Pajn** [comment]
It would be great with an option for Ctrl+Left too for the behavior mentioned in #943

**Comment by alexandrudima** [comment]
To control this behaviour and get VS-style Ctrl+Right, please edit your `keybindings.json` and add:
```
{ "key": "ctrl+right",       "command": "cursorWordStartRight",       "when": "editorTextFocus" }
```

This will overwrite the default:
```
{ "key": "ctrl+right",       "command": "cursorWordEndRight",       "when": "editorTextFocus" }
```

**Comment by alexandrudima** [comment]
Please also see #832 for getting VS-style Ctrl+Delete.
