### ISSUE TITLE
After scoll / flush terminal's screen, the content still display.

### ISSUE THREAD

**Issue by ershiwo** [Microsoft/vscode#35784]
- VSCode Version: 1.17 stable
- OS Version: Windows 10 version 1703 build 15063.632

Steps to Reproduce:

1. Open a terminal in Chinese Windows environment, input a command such as `ls`;
2. Scoll the screen, text should be flush, but they are still on screen.
![2017-10-07_174318.png](https://ooo.0o0.ooo/2017/10/07/59d8a2770c430.png)
3. Use `clear` to clean screen, this problem will be more esay to observe.
![2017-10-07_170729.png](https://i.loli.net/2017/10/07/59d8a2770130c.png)

A gif to show it: https://i.loli.net/2017/10/07/59d8a277631b3.gif

Reproduces without extensions: Yes

**Comment by wang7x** [comment]
I have the same problem on Linux (Ubuntu 17.04)

**Comment by wevsty** [comment]
On Ubuntu 16.04.03 I also encountered the same problem.

**Comment by ershiwo** [comment]
#35773 
#35774

**Comment by wevsty** [comment]
Duplicate #35660 

It seems to have been fixed.

**Comment by ershiwo** [comment]
I see. They haven’t published a new version. Thank you.

发件人: wevsty [mailto:notifications@github.com]
发送时间: 2017年10月7日 20:41
收件人: Microsoft/vscode <vscode@noreply.github.com>
抄送: 板砖加身 <ershiwo@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [Microsoft/vscode] After scoll / flush terminal's screen, the content still display. (#35784)


Duplicate #35660<https://github.com/Microsoft/vscode/issues/35660>

It seems to have been fixed.

**Comment by andreiucm** [comment]
I have the problem too in ubuntu 16.04
https://github.com/Microsoft/vscode/issues/35773#issuecomment-334932232

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
