### ISSUE TITLE
net debugger warning

### ISSUE THREAD

**Issue by HawkenKing** [Microsoft/vscode#35781]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open VScode on El Capitan
2. get warning

Hi, I'm not sure how to get rid of this warning. I am using Unity and VScode, in their vanilla states.

This is something that appears in VScode after installing.

Any advice on how to stop this warning from appearing would be appreciated. 
![screen shot 2017-10-07 at 4 15 24 pm](https://user-images.githubusercontent.com/5999766/31305719-7a4f650c-ab7b-11e7-9524-836465841c9d.png)

**Comment by chrmarti** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1784
