### ISSUE TITLE
cannot use touch to slide the tab bar (like with two fingure gesture on mouse touch pad) or move individual tabs with touch

### ISSUE THREAD

**Issue by flyinggorilla** [Microsoft/vscode#35786]
Working on Surface Pro (5)

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
Go|luk|0.6.65
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.0
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@flyinggorilla Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by flyinggorilla** [comment]
I am now on Win 10 1709 fall creators update (GA) and tried the insider version

does NOT work in 1.16.1 release
DOES work in insider version 1.18.0-insider

so great news! tab bar can be slided with touch now.
-bernd
