### ISSUE TITLE
source file not found

### ISSUE THREAD

**Issue by nihuai** [Microsoft/vscode#35780]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.10.0-28-generic
- Extensions: 

---
Steps to Reproduce:
c++
Start debugger,Contains Chinese string path garbled，Unable to find source file
FilePath：/home/nihuai/桌面/你好/a.cpp
DebugOutput：Source file not found(file:///home/nihuai/346241214351235242/344275240345245275/a.cpp)。

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#1113
