### ISSUE TITLE
razor page syntax highlighting bug with apostrophe after variable

### ISSUE THREAD

**Issue by Alleno** [Microsoft/vscode#35793]
cshtml page syntax highlighting fails if you have an inline variable immediately followed by an apostrophe. Here it is `<h1>@ViewBag.username's Profile</h1>`

The page works correctly, and the syntax highlighting used to work in Core version 1.X, but for some reason upon upgrade to 2.0 the syntax highlighting changed. 

![image](https://user-images.githubusercontent.com/9685726/31308458-23c74dd4-ab45-11e7-93dc-82ce9bc45db5.png)

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.10.0
jshint|dba|0.10.15
python|don|0.7.0
auto-close-tag|for|0.5.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
view-in-browser|qin|0.0.5
LiveServer|rit|2.2.0
html5-boilerplate|sid|1.0.1
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. Insert a inline variable
2. Add apostrophe right after variable (no space)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to demyte/language-cshtml#16
