### ISSUE TITLE
Terminal font doesn't fit to the line after update 1.17

### ISSUE THREAD

**Issue by ahmadkhalidjs** [Microsoft/vscode#35794]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.4-200.fc26.x86_64

integrated-terminal font doesn't fit to the line after update 1.17

![22228309_1736678776632498_4608159730353965000_n](https://user-images.githubusercontent.com/18547251/31308785-596ac782-ab85-11e7-809e-bc3a238e8e76.jpg)

**Comment by martiuslim** [comment]
I'm also facing this issue after updating to v1.17.0 last night.

OS: Linux fedora 4.12.14-200.fc25.x86_64

**Comment by andreiucm** [comment]
I have not exactly this issue but similar
https://github.com/Microsoft/vscode/issues/35773#issuecomment-334932232

**Comment by dc-dos** [comment]
Same issue, Fedora 26. I've seen the expect trouble thing before but the line clipping seems to be new and comes from Sept 2017 release...

**Comment by Yawzheek** [comment]
I too have encountered this issue at 1.17, also using Fedora 26 (LXDE):
OS: 4.13.4-200.fc26.x86_64
It presents itself exactly the same as the photo user ahmadkhalidjs provided.

**Comment by jfpoilpret** [comment]
Exact same issue here on Fedora 26 with XFCE.
VSCode 1.17 makes integrated terminal just unusable.
Patch needed urgently otherwise, only solution would be to revert to 1.16.1.

**Comment by tonila** [comment]
Same here in debian buster. reinstalled 1.16.1 for now.

**Comment by zorankiki** [comment]
try something like "terminal.integrated.fontFamily": "Mono" in user settings. it worked but personally just don't like that font.

**Comment by jfpoilpret** [comment]
@zorankiki thanks, that works around this issue with integrated terminal on Fedor26/XFCE. Makes it usable again, Personally, I find this font usable.

**Comment by vstoykov** [comment]
I normally don't like the default font and for that reason I always install 'Ubuntu Mono' font (even on Fedora) and use it in my editor and terminal. With it I don't have that problem.

**Comment by ahmadkhalidjs** [comment]
@zorankiki that worked for me, and the font is even better than the default font on terminal. thanks.

**Comment by mprahl** [comment]
Same problem here on Fedora 26.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35644

Workaround is to change the terminal font:

```js
"terminal.integrated.fontFamily": "'DejaVu Sans Mono'"
```
