### ISSUE TITLE
cant add parenthesis when cursor precedes an existing parenthesis

### ISSUE THREAD

**Issue by sarora2073** [Microsoft/vscode#35799]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.3
vscode-eslint|dba|1.3.2
gitlens|eam|5.4.1
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
debugger-for-chrome|msj|3.3.1
vscode-icons|rob|7.14.0

---

Steps to Reproduce:

1. Open editor on a new file and enter any text with opening and closing parenthesis 
e.g. enter this code which is missing a 3rd closing parenthesis
console.log(_.isEmpty(JSON.parse(myObject));
2. Put cursor on any of the last 2 closing parenthesis
3. Enter a closing parenthesis (i.e. attempt to add another parenthesis when one is already in front of the cursor). 
4. Issue: The new parenthensis is not entered (perhaps due to some code completion feature? Either way, it's obviously not useful in this common scenario)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This can be turned off via `editor.autoClosingBrackets`. The feature consists of multiple parts:
* one is that when `(` is typed, the result is `(|)`
* the other part that is hit here, is that when `)` is typed and `)` follows the cursor, `)` will be *overtyped*.

The feature is implemented language agnostic and looks only locally at the next character. It does not count brackets to determine if the code is "bracket unbalanced"

**Comment by sarora2073** [comment]
Thanks for the info. I've disabled it for my purposes since it can create room for accidental bugs in the code, by not recognizing intended closing brackets when entered. 

If the second scenario you described were either improved (by not being just local) or else remove the second scenario handling entirely, then the auto-close feature might be more usable. Just a thought.

**Comment by allmaxgit** [comment]
I want add parenthesis when cursor precedes an existing parenthesis.
And I want use autoClosingBrackets.
