### ISSUE TITLE
what is this？

### ISSUE THREAD

**Issue by yimiZSK** [Microsoft/vscode#35790]
It was a pretty bad update？what is rg.exe?
![1507369600 1](https://user-images.githubusercontent.com/24860389/31308141-e2d0416e-aba3-11e7-9c45-7ab55180ae3c.png)

**Comment by Mlocik97-issues** [comment]
eg.exe is not VSCode service.

**Comment by mrmlnc** [comment]
The `rg.exe` process is `ripgrep` that uses in VS Code as Search engine.

**Comment by yimiZSK** [comment]
@mrmlnc how do I  make it to use less CPU?

**Comment by mrmlnc** [comment]
I think you help @chrmarti or @roblourens  :)

**Comment by roblourens** [comment]
Can you get the command line arguments of the process from the 'details' tab?

Do they show up right away when launching vscode, or after some usage? Are you opening a large folder?

**Comment by yimiZSK** [comment]
Yes，they show up when i open a normal folder 。But after some usage ，they're gone @roblourens

**Comment by roblourens** [comment]
Some extensions will start these, it's expected. Do they stay around for a long time? We are looking at ways to make it faster: https://github.com/Microsoft/vscode/issues/34434

**Comment by yimiZSK** [comment]
Thanks

**Comment by yimiZSK** [comment]
Thanks @roblourens
