### ISSUE TITLE
Integrated terminal noise on Linux in ver 1.17.0

### ISSUE THREAD

**Issue by narimiran** [Microsoft/vscode#35795]
- VSCode Version: Version 1.17.0
- OS Version: Linux Mint Cinnamon 18.2

Steps to Reproduce:

1. Use VS Code for some time
2. Put the computer to sleep (suspend)
3. When you return, you'll see this:

![screenshot](https://i.imgur.com/Mjt7QCX.jpg)

Not sure if this is the correct or the only way to reproduce it, but I witnessed it two times already with ver1.17 after suspending.

To 'fix' the problem (to make terminal visible again), the VS Code window needs to be resized.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/30292

**Comment by Tyriar** [comment]
This is a Chromium issue with no known workarounds.
