### ISSUE TITLE
Terminal does not render awesome patched icon fonts correctly

### ISSUE THREAD

**Issue by cvuorinen** [Microsoft/vscode#35791]
- VSCode Version: 1.17.0
- OS Version: Linux

Steps to Reproduce:

1. Use an [awesome-terminal-fonts](https://github.com/gabrielelana/awesome-terminal-fonts) patched font in terminal with a powerline that uses awesome icons (such as [powerlevel9k](https://github.com/bhilburn/powerlevel9k))
2. Open terminal

Reproduces without extensions: Yes

Before updating to 1.17:

![screenshot from 2017-05-05 19-03-48b](https://user-images.githubusercontent.com/1764167/31308179-a3ddd616-ab7a-11e7-80c4-76868924059a.png)

With 1.17.0:

![screenshot from 2017-10-07 16-01-05](https://user-images.githubusercontent.com/1764167/31308183-ac99c9fe-ab7a-11e7-890c-0a9ffbad7b26.png)

**Comment by cvuorinen** [comment]
Also, seems to be some other weird rendering issues as well. Here is a screenshot after running npm install:

![screenshot from 2017-10-07 17-41-03](https://user-images.githubusercontent.com/1764167/31308912-f48e4878-ab86-11e7-9255-2ecf5ab6c10e.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35649

@cvuorinen I haven't actually seen that last screenshot you posted. If you have repro steps could you create a new issue?
