### ISSUE TITLE
[folding] Allow to fold a specific level

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3580]
It should be possible to fold all sections in the current file that have a specific indentation level.
 - it should be possible to right click on a code folding icon and select _(Un)Fold all on this level_
 - it should be possible to trigger this action from command palette or shortcut to fold all on the level of the section the cursor currently is in.

**Comment by aeschli** [comment]
Thanks for the request, I had 'Fold Level' already planned. Not all of what you request, but IMO the most useful:
- `Ctrl + J, Ctrl + 1`: Folds all regions of level 1, except if a cursor is placed in it
- `Ctrl + J, Ctrl + 2`: Folds all regions of level 2, except if a cursor is placed in it
...
- `Ctrl + J, Ctrl + 5`: Folds all regions of level 5, except if a cursor is placed in it

The other features you mention (unfold to level, context menu, fold to level at cursor) are currently not planned. Please file separate issues if you think they are important.
