### ISSUE TITLE
Adding a new file should open the Explorer file list 

### ISSUE THREAD

**Issue by victor-rocha** [Microsoft/vscode#35803]
- VSCode Version: 1.17.0
- OS Version: OSX 10.13 (High Sierra) 

Steps to Reproduce:

1. Close the collapse on the left side toolbar (Explorer file list) 
2. Click on the "new file" icon. 

Reproduces without extensions: Yes

I think the collapse should open so you can type and see the file name you are about to create. 
What do you guys thing? Thats more of an UX issue! =)

**Comment by isidorn** [comment]
Dup of #35923
