### ISSUE TITLE
closing tag on certain elements not initialize new line

### ISSUE THREAD

**Issue by tuonglai3602** [Microsoft/vscode#35802]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. create an empty html doc
2. type <style> and click enter to auto closing tag
3. new line is not populated

p.s: new lines populated with other tags in `<body>` such as: `<h1>` [enter], etc.

Looks like only happens on Mac (tested on a Windows machine which is working)

**Comment by aeschli** [comment]
@rebornix given that the text before the cursor still belongs to html, I'd say the HTML indent rules appliy

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/46426 and thanks all for your feedback!
