### ISSUE TITLE
`resourceLangId` doesn't work after a language mode change

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#35805]
I'm using [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) for managing todo files. It adds the following to its `package.json`:

```json
    "menus": {
      "commandPalette": [
        {
          "command": "todo.toggleBox",
          "when": "resourceLangId == todo"
        }
      ]
    }
```

The `todo.toggleBox` command is displayed in the command palette if the active file's name is contained inside `contributes.languages.extensions`, but if I create a file named `foo`, run `Change Language Mode`, and set the language to `Todo` (provided by Todo+), the `todo.toggleBox` command is not displayed.

I guess the context variable `resourceLangId` doesn't get updated and/or extensions aren't updated accordingly to the change.

**Comment by chrmarti** [comment]
Does `editorLangId` work? (See https://github.com/Microsoft/vscode/issues/26873#issuecomment-302626728)

**Comment by fabiospampinato** [comment]
That does work, I guess I'm supposed to use it instead of `resourceLangId`.
