### ISSUE TITLE
Folding sidebar sections causes sidebar overflow

### ISSUE THREAD

**Issue by heronsilva** [Microsoft/vscode#35801]
- VSCode Version: 1.17.0
- OS Version: Debian 9.1
- Screen resolution: 1366x768

Steps to Reproduce:

1. Fold some sidebar sections (starting from the bottom - Drake's voice)
2. Unfold all and the bottom ones should overflow out of the sidebar

Reproduces without extensions: No

Example:
![vscode-sidebar-issue](https://user-images.githubusercontent.com/9641348/31310109-89c2f99e-ab68-11e7-9b5a-527d1fdc764f.gif)

**Comment by sandy081** [comment]
@joaomoreno Any insights?

**Comment by joaomoreno** [comment]
@sandy081 All those views have a pretty big minimum size when expanded. If you sum up all those minimum sizes, it will be larger than the layout size of the split view. Nothing we can do to fix that.

The bug is valid though, I'll take it.

**Comment by joaomoreno** [comment]
Good catch!

![drake](https://media.giphy.com/media/5xaOcLDE64VMF4LqqrK/giphy.gif)
