### ISSUE TITLE
Format Document Not Working

### ISSUE THREAD

**Issue by DannyMexen** [Microsoft/vscode#35816]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: none
---

Steps to Reproduce:

1. Open a file eg html or php

2. Press `Ctrl + Shift + I`

**Comment by roblourens** [comment]
Is that the right shortcut? What if you run "Format document" from the command palette?

Does it work if you launch code with `--disable-extensions`?

**Comment by DannyMexen** [comment]
Yes it is. I am not running any extensions and I was going to try that but after reloading, formatting HTML files worked. As for PHP, research indicated that I need an extension that relies on a system wide installation of PHP CodeSniffer. I tried installing via Pear as the extension page in VSCode suggested but to no avail. Thanks for your response but for now, I will try another editor. I'll sit down properly and set up some day. Thanks again.

**Comment by DannyMexen** [comment]
Running from Command Palette yielded no results.

**Comment by roblourens** [comment]
We don't support formatting PHP out of the box right now. I'm not sure which extension you were looking at, but I use the PHP Intellisense extension which supports formatting without any other setup besides installing PHP.
