### ISSUE TITLE
terminal garbled

### ISSUE THREAD

**Issue by illinux** [Microsoft/vscode#35814]
VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
bracket-pair-colorizer|Coe|0.10.9
vscode-markdownlint|Dav|0.10.1
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
python|don|0.7.0
vscode-great-icons|emm|2.1.16
php-debug|fel|1.11.1
code-python-isort|fre|0.0.3
easy-icons|jam|0.3.1
format-php|Kas|1.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
start-git-bash|McC|1.2.1
vscode-filesize|mkx|1.0.0
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.14.0
code-settings-sync|Sha|2.8.3
guides|spy|0.8.4
python|tht|0.2.3
vim|vsc|0.10.1
bootstrap-3-snippets|wcw|0.1.0

(11 theme extensions excluded)

---

Steps to Reproduce:
![snipaste_2017-10-08_12-52-49](https://user-images.githubusercontent.com/30189427/31314023-eac813f4-ac27-11e7-9186-02b71421fd7e.png)

1.
2.

Reproduces without extensions: Yes/No

**Comment by tonyforgan** [comment]
Somewhat similar issues for me too. 
![image](https://user-images.githubusercontent.com/6308371/31322701-2ccf6c58-ace0-11e7-9308-aba90514b87b.png)

I did spot a random log message in the terminal on the first run of 1.17.0 which was along the lines of _something doesn't match, be prepared for trouble_, but I haven't been able to have it report again.

VS Code 1.17.0 on Fedora 25.

**Comment by illinux** [comment]
Is theme problem. But "终端显示中文是有问题的",and background color is garbled.

**Comment by illinux** [comment]
![snipaste_2017-10-09_10-10-51](https://user-images.githubusercontent.com/30189427/31323525-912af532-acdb-11e7-9565-1f8bae461a67.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
