### ISSUE TITLE
support `workbench.action.terminal.runSelectedLine` for run current line and go to the next line

### ISSUE THREAD

**Issue by dongzhuoer** [Microsoft/vscode#35818]
Currently, when you don't select anything, `workbench.action.terminal.runSelectedText` will run the line where your cursor locate. This is awesome.

But when you are write a script, you often want to run code line by line. It would be very convenient if there is a function like "run current line and go to the next line".

**Comment by Tyriar** [comment]
This is a good candidate for a simple extension, we would want to avoid putting something so specific into the core editor to prevent feature bloat.
