### ISSUE TITLE
Working files picker not discoverable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3581]
Working files picker is hardly discoverable, we should market this feature better

1. It is completely disconnected from the working files view, which might make sense since all the functionality is there already. But maybe only to add it there so the users learn that working files can be accessed via quick open also. Not sure if context menu action is a good choice - just a food for thought
2. It should be in the view menu, after command palette, or in the goto menu after goto file

**Comment by bpasero** [comment]
I think we are good here given our work. The working files picker is not that important anymore.
