### ISSUE TITLE
The new logo is so ugly

### ISSUE THREAD

**Issue by whitefirer** [Microsoft/vscode#35819]
The new logo is so ugly, could you use the old logo?

**Comment by Kenya-West** [comment]
#35783

**Comment by Mlocik97-issues** [comment]
Dupl #35683

**Comment by mjbvz** [comment]
Duplicate of #35783

**Comment by miladghiravani** [comment]
Hi, Thanks a lot for change icon. But new icon need some stroke line.
![image](https://user-images.githubusercontent.com/5067331/32614410-6e7f7d54-c582-11e7-86c2-831a570f8217.png)

Like this:
![image](https://user-images.githubusercontent.com/5067331/32614855-67a34d84-c583-11e7-86f9-071e13515775.png)
