### ISSUE TITLE
MarkdownString rendering differently in Hover and SignatureHelp

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode#35813]
- VSCode Version: 1.17.0
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Initiate Hover with `contents` as a `MarkdownString` containing a backtick-enclosed string
2. Initiate SignatureHelp with `ParameterInformation.documentation` or `SignatureInformation.documentation` as a `MarkdownString`  containing a backtick-enclosed string

Reproduces without extensions: Yes

Hover
![image](https://user-images.githubusercontent.com/22951521/31313041-31cc759e-aba4-11e7-9a75-54e9388cc70e.png)

SignatureHelp
![image](https://user-images.githubusercontent.com/22951521/31313051-68571a4c-aba4-11e7-9ded-d6c2350fe586.png)

In the above images, the left-most character strings on lines 2-5 are surrounded by backticks (`) in both cases, but rendered differently in each context.

**Comment by ramya-rao-a** [comment]
They still look a little different

![hover](https://user-images.githubusercontent.com/16890566/32344160-1ed86adc-bfc3-11e7-99fa-9305b0fa1545.gif)

**Comment by mjbvz** [comment]
Yes, still had different fonts. Fixed by c4028a7
