### ISSUE TITLE
User settings view changes on tab change

### ISSUE THREAD

**Issue by Dimpl** [Microsoft/vscode#35815]
- VSCode Version: 1.17.0
- OS Version: Windows 10 Version 1703

Steps to Reproduce:

1. Open 'User Settings', close the 'commonly used' section and open another settings group.
2. Change tab away from, then back to, 'User Settings'

Expected behaviour: There is no change to the settings view.
Actual behaviour: The settings tab resets to the initial view (the 'commonly used' section is open and all others are shut).

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Duplicates #28394
