### ISSUE TITLE
Go to definition on hover link click (feature request)

### ISSUE THREAD

**Issue by CoryXie** [Microsoft/vscode#35827]
It would be good if there is a link on the Hover pop up that can lead to the code location, short cut to the Go to Definition menu item. This is then similar to the Source Insight Code Preview window where a (double) click on the preview leads to that position in the main editor. Helpful for code navigation.

**Comment by jens1o** [comment]
It is implemented, but you will need to press down the <kbd>Ctrl</kbd>-Key and then click on the symbol name.

**Comment by CoryXie** [comment]
Yes, but still prefer to have it on the hover pop up, since it always would pop up when mouse over for some time, then a click is simpler than requiring another key press and then click...

**Comment by jens1o** [comment]
Well, personally, I'm doing just fine with the current approach, and I'm doing this automatically. I often click on the hover messages to select something, and I wouldn't like false-positives there.

**Comment by CoryXie** [comment]
Sometimes a symbol name may have been defined in many places (because they are different implementations), however the default "Ctrl+Press" may blindly lead to a definition that is not the implementation the user may want to check, but the the popup would contain a list of all definitions, so it is good to let the user just choose where he/she wants to look at.

**Comment by jrieken** [comment]
Closing this as extension-candidate. Checkout [complex/api commands](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) and the [hover provider api](https://code.visualstudio.com/docs/extensionAPI/vscode-api#HoverProvider) that allow you to implement this. Happy Coding
