### ISSUE TITLE
full screen bugs on ubuntu and maybe other distros

### ISSUE THREAD

**Issue by singhravi1** [Microsoft/vscode#35825]
when full screen, if i click anywhere where ubuntu menu any other layout would be, it goes out of full screen mode and i have to alt+tab again to vscode to get it right again.
i think many other guys who like to work in full screen mode have experienced this.

**Comment by halidaltuner** [comment]
+1

**Comment by bpasero** [comment]
@singhravi1 @halidaltuner still happening? And if so, could you try to reproduce with these newer builds: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz ?
