### ISSUE TITLE
Custom font size for Search and SCM

### ISSUE THREAD

**Issue by sivakov512** [Microsoft/vscode#35821]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.13_1
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-eslint|dba|1.3.2
python|don|0.7.0
vetur|oct|0.9.10
vim|vsc|0.10.1
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---
Can I change font size in Search and SCM?
It looks small by default :(
![image](https://user-images.githubusercontent.com/10251687/31315476-cc5458e4-ac5c-11e7-9d1c-0de95f7832fe.png)

**Comment by chrmarti** [comment]
You can set a `"window.zoomLevel"` in user settings.

**Comment by cryptomaniac512** [comment]
this will increase the fonts and size of the elements everywhere in the editor, not only in this panel.

**Comment by oyeanuj** [comment]
I want to second this. In addition, being able to customize the line height would be super helpful. 

FWIW, Here is how the search can be customized in Atom, for comparison:

<img width="907" alt="screen shot 2017-10-18 at 8 22 56 pm" src="https://user-images.githubusercontent.com/9633371/31752893-41abb488-b442-11e7-9e08-ad15a10c7019.png">
