### ISSUE TITLE
New Shell File: Set permission and template

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode#35824]
Hi, All,

When I create a shell file, say, `test.sh` is it possible to make VSCode to:

1. Set exec permission (`chmod +x test.sh`).
2. Add shebang `#!/bin/sh -eu` to the beginning of the file.

I know I can copy the file but I'd rather avoid doing that

---

```sh
$ code -v
1.17.0
be377c0faf7574a59f84940f593a6849f12e4de7
```

**Comment by aeschli** [comment]
Sounds like you want a 'new' file creation wizards ('New shell file), which we don't have (as a principle).
