### ISSUE TITLE
Code highlighting only works if it's formated?

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#35826]
- VSCode Version: 1.17.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Open a minimized JSON file with .json extension
2. VSCODE correctly identifies it's json but there's no syntax highlight
3. `Format code` and all of a sudden code lights up with its color

Before format:
![image](https://user-images.githubusercontent.com/8936090/31316528-80f92078-ac2f-11e7-9389-ecd8ee8b4bf8.png)

After format:
![image](https://user-images.githubusercontent.com/8936090/31316530-8d021cee-ac2f-11e7-9839-71d949a61790.png)

**Comment by aeschli** [comment]
There's a line length limit. Lines longer than the limit are not colorized for performance reasons.

**Comment by nmaxcom** [comment]
Can I change that? "Force" it to paint it anyway? What's the length limit? Because in that file the lines were not really that long.

**Comment by aeschli** [comment]
The limit is 20000 characters. It's not configurable.

On your screenshot it looks like all is on one line.

**Comment by nmaxcom** [comment]
Now that you mention it, I think you are right. Thanks for the info!
