### ISSUE TITLE
左侧文件导航有时会显示文件夹错位，而实际文件夹正常

### ISSUE THREAD

**Issue by leehave** [Microsoft/vscode#35829]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
JSDocTagComplete|Hoo|0.0.2
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
format-indent|Kas|1.3.0
jsx|Twe|0.0.1
html-css-class-completion|Zig|1.10.0
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
vscode-twig-pack|baj|1.0.0
vscode-styled-jsx|bla|0.1.1
vscode-standard-format|che|0.0.12
open-html-in-browser|cod|0.1.21
vscode-svgviewer|css|1.4.3
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
terminal|for|0.0.10
typings-autoinstaller|jvi|1.2.0
php-symbols|lin|2.1.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
js-patterns-snippets|nik|0.0.5
vetur|oct|0.9.10
view-in-browser|qin|0.0.5
vscode-icons|rob|7.14.0
sass-indented|rob|1.4.2
launchterminal|tes|0.4.0
vscode-typings|typ|0.0.5
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Mlocik97-issues** [comment]
I don't know what you mean, maybe it's similiar as  #35719

**Comment by chrmarti** [comment]
@leehave Could you attach a screenshot?
