### ISSUE TITLE
[folding] Code Folding in larger files slows down editor

### ISSUE THREAD

**Issue by kuechlerm** [Microsoft/vscode#3582]
In 0.10.10-insider folding more than about 3000 lines of xml slows down the editor.
Specifically moving the cursor takes seconds.

Should be reproducible with

`<root>
    <element>1</element>
  
</root>`

Addition: If the cursor is not located in the block that gets folded, there is no lag.

**Comment by aeschli** [comment]
@kuechlerm Is that what you tried?
- have a large XML document
- set the cursor inside
- fold the top node

**Comment by kuechlerm** [comment]
@aeschli Yes, but so be more specific:

- have a XML doc with a large node (more then 3000 elements) and a small node (place for cursor movement)
- place cursor inside large node
- use shortcut or mouse to fold node 

Result:
- no cursor movement for a while (~2 seconds)
- overall slower cursor movement in the rest of the file from here on

Placing the cursor outside the node and then closing the large node with a mouse click sometimes seemed to have less or no lag, but I cannot reproduce that with certainty. 

Unfolding restores normal cursor speed.

**Comment by aeschli** [comment]
The problem with folding a full document to one line is that we collapse all decorators to that one line. Decorators are used for error markers, git markers, but also for tracking the folding regions.

We have ideas on how to reduce the number of decorators used for folding to improve the performance of this scenario. Bur not for March.

**Comment by aeschli** [comment]
I created #3725.
