### ISSUE TITLE
Question: Can the region folding start marker and end marker be the same?

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#35823]
In the examples in [doc](https://code.visualstudio.com/updates/v1_17#_folding-regions), the start marker and end marker for region folding are all different. Is this a requirement? Say, if I want support folding regions using `#==*=#`, e.g.,

```julia
#========================#
Hshsjshshsjsjsjsjhsyxyxtsnzb
Jsjshzhzhbsbsbsbsbsjjss
#========================#
```

Is it supported by design? Thanks!

**Comment by aeschli** [comment]
Sorry, the markers must be different.
