### ISSUE TITLE
CJK text not properly rendered in built-in terminal

### ISSUE THREAD

**Issue by xrfang** [Microsoft/vscode#35820]
- VSCode Version: 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7)
- OS Version: Kubuntu 17.04 x86_64

Steps to Reproduce: 

1. type any command that will get Chinese text output in the built-in terminal
2. scroll the text in terminal. Text will not get cleared properly

Reproduces without extensions: I estimate this has nothing to do with plugins.

![screenshot_20171008_160321](https://user-images.githubusercontent.com/399946/31315088-0cc8a37c-ac43-11e7-9cb8-ecfb5dad8f71.png)

**Comment by xrfang** [comment]
I just confirmed that this problem does not exist in previous 1.16.

**Comment by Stone-Zeng** [comment]
Duplicate #35660
