### ISSUE TITLE
[folding] "editor.showFoldingCongrols":"always" not respected

### ISSUE THREAD

**Issue by kcwms** [Microsoft/vscode#35839]
- VSCode Version: Code - Insiders 1.17.0-insider (f6ef4bef42fa2948426c99fefa340235e67a0c5e, 2017-10-04T17:40:56.306Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-guid|hea|1.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
mssql|ms-|1.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
partial-diff|ryu|0.3.3
shell-launcher|Tyr|0.1.3

---
When Mouse Is Not Hovered
![image](https://user-images.githubusercontent.com/29052675/31319007-65b32580-ac29-11e7-964b-c1e8188d1de0.png)

When Mouse Is Hovered
![image](https://user-images.githubusercontent.com/29052675/31319014-8dc14d9a-ac29-11e7-9b53-858867d31b35.png)

---

Steps to Reproduce:

1. Edit User or Worksapace Settings and add "editor.showFoldingControls":"always"
2. Save your changes and look at a file with folding regions

Reproduces without extensions: Yes

**Comment by rhernandog** [comment]
Same issue.
- VSCode Version: 1.17.0
- OS Version: Windows 7 64 bit

One thing I can add is that when I open a file all the minus signs are visible, but as soon as I focus on the file (click anywhere in the code) they fade out, regardless of the settings.

**Comment by maxtar** [comment]
I have the same problem.

**Comment by technoiswatchingyou** [comment]
Same problem for me

VSCode 1.17.2
MacOS 10.13.1

**Comment by DeathLoveCrymo** [comment]
I am also having this problem.
1.17.2 on Windows 10

**Comment by solidxsnake** [comment]
Same problem here.

**Comment by victorwpbastos** [comment]
Same here.

- VSCode 1.18.0
- WIndows 10

**Comment by solidxsnake** [comment]
This bug still seems to exist. Folding controls only show all the time when their corresponding section is collapsed. When the section is expanded, the "-" box disappears when the mouse is not over the gutter. See gif.

- VSCode Version: Code - Insiders 1.19.0-insider (d6fbdcf19716910b26ea81efc95724f2fabe5aa6, 2017-11-10T05:17:03.030Z)
- OS Version: Windows_NT x64 6.1.7601

![folding_bug](https://user-images.githubusercontent.com/8855615/32667124-c79e741e-c607-11e7-8066-4b6373941098.gif)

**Comment by rhernandog** [comment]
Yep, still happening.
- Windows 7 64
- VSCode 1.18.0

**Comment by maxtar** [comment]
The same

**Comment by aeschli** [comment]
Oh, sorry, you are right, this is still broken in 1.18. Fix on the way.

**Comment by maxtar** [comment]
Hi, version 1.18.1 still doesn't work. :(

**Comment by aeschli** [comment]
Yes, I know. Its fixed in November (1.19).
