### ISSUE TITLE
typescript generic inference issue

### ISSUE THREAD

**Issue by fourcels** [Microsoft/vscode#35832]
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

```ts
function identity<T>(arg: T): T{
  return arg
}

identity(1)
```

![e06c5964-7ead-4a30-9561-52f193eb4bf4](https://user-images.githubusercontent.com/1042568/31317346-a7df4f30-ac04-11e7-8d15-e48b5346c40a.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This is correct due to TypeScript's literal types. `T` is of literal type `1` in this example
