### ISSUE TITLE
C++ Parsing Never Stops

### ISSUE THREAD

**Issue by ahmedbilal** [Microsoft/vscode#35831]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.9.52-1-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
python|don|0.7.0
Go|luk|0.6.66
cpptools|ms-|0.13.1
preview-vscode|sea|1.3.4
markdown-all-in-one|yzh|0.10.3

(9 theme extensions excluded)

---

Steps to Reproduce:

1. Install Microsoft C/C++ extension.
2. It never stop parsing in Visual Code 1.17

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#1114
