### ISSUE TITLE
Incorrect highlighting when using backslashes for line continuation in TypeScript

### ISSUE THREAD

**Issue by fantacytyx** [Microsoft/vscode#3583]
version 0.10.10-insider

![60ec0fb2ddde6d38feaff57a68db6528](https://cloud.githubusercontent.com/assets/8966236/13427589/0288360a-dff0-11e5-8d35-7483103fa87b.jpg)

[bug demo.zip](https://github.com/Microsoft/vscode/files/152779/bug.demo.zip)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#104
