### ISSUE TITLE
vscode.commands.executeCommand('editor.action.cursorUndo') Doesn't work

### ISSUE THREAD

**Issue by patmeeker** [Microsoft/vscode#35840]
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.3

I'm trying to create an extension.

`vscode.commands.executeCommand('editor.action.cursorUndo');`
Doesn't do anything.

Other commands work here, but not this one.

**Comment by alexandrudima** [comment]
`editor.action.cursorUndo` will move the cursor to its previous state. The cursor undo stack is reset after each edit.

**Comment by patmeeker** [comment]
What is the command to undo the last edit?

**Comment by alexandrudima** [comment]
`undo`.

**Comment by patmeeker** [comment]
editor.action.undo ? Doesn't seem to work either.

**Comment by alexandrudima** [comment]
`vscode.commands.executeCommand('undo')`

The easiest way to find built-in commands is by opening the keybindings UI (cmd+k cmd+s) and clicking on `keybindings.json`. In the `"command"` fields or at the bottom of the file you can find all identifiers for all the commands registered to a running VS Code instance. In this case:

```
{ "key": "cmd+z",                 "command": "undo",
                                  "when": "editorTextFocus && !editorReadonly" },

```

**Comment by patmeeker** [comment]
Thanks!
