### ISSUE TITLE
Bring back the old logo (or make the new one the same color as the old one)

### ISSUE THREAD

**Issue by iyedb** [Microsoft/vscode#35843]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Mlocik97-issues** [comment]
........................


-.-


DUPLICATE WITH "MILIONS" ISSUES.

**Comment by ahmedtota47** [comment]
i think that the new one is not so bad

**Comment by iyedb** [comment]
Glad to see I am not the only one complaining about the new logo. Closing.
