### ISSUE TITLE
Can't (add) drag and drop folder into already open workspace

### ISSUE THREAD

**Issue by karuppasamy** [Microsoft/vscode#35849]
- VSCode Version: Version 1.17.0
- OS Version: macOs Sierra 10.12.6

Steps to Reproduce: Find attached gifs.

1. Create two folders (ex: (Project1 and Project2) with some files
2. Open Project1 folder in VSCode
3. Drag and Drop Project2 folder into Project1 workspace (NOT working)
4. Drag and Drop any file from Project2 folder into Project1 workspace (working)

![vscode_drag_and_drop_folder_not_working](https://user-images.githubusercontent.com/264525/31322302-2a9fb800-ac8d-11e7-9b7d-12e5e8eb8d6c.gif)

Reproduces without extensions: Yes

**VSCode insiders** is working but not as expected. 

![vscode_insiders_drag_and_drop_folder_not_working](https://user-images.githubusercontent.com/264525/31322281-bfd4b642-ac8c-11e7-8d78-e25c56836b95.gif)

**Comment by isidorn** [comment]
@karuppasamy thanks for reporting this. currently we only care about insiders behavior for this. From what I see the issue is that you want to drop a folder into a specific location in the explorer and we always treat that as an add workspace. I can also repro this

Did you specifcily design this to behave like this @bpasero 
I think the folder should be only added as a workspace if it is dropped top level. I can look into fixing this if you agree with this behavior.

**Comment by karuppasamy** [comment]
Thanks for response @isidorn. You are correct. I was trying to add (drag and drop) the new folder into the `src` but It always added into the Top Level only.

"... should be only added as a workspace if it is dropped to..." - Just for a clarification, is this a functionality for the feature request [#396](https://github.com/Microsoft/vscode/issues/396)? If so, may be you could consider this UI  [Add support for opening multiple project...](https://github.com/Microsoft/vscode/issues/396#issuecomment-315694083) for opening multiple projects in a separate workspace. 

So, every workspace will have a name as project name. Otherwise it'll show as **"UNTITLED (WORKSPACE)"** as in VSCode Insiders.

**Comment by bpasero** [comment]
@karuppasamy when you drop a folder into the explorer we will add it to the workspace. are you suggesting something else?

**Comment by isidorn** [comment]
I think that droping the folder on the top level tree node adds it to the explorer, otherwise it adds it as a child to the specific node.

**Comment by karuppasamy** [comment]
@bpasero, As @isidorn said, it'd be nice to have a behavior to add the folder in the selected (drag and drop on a folder) node instead of always add it in top level node in the workspace. 

In attached gifs, I was expecting the folder that should be added under `src` which I dragged over on it. 

-------
One more question that I asked in my previous comment is that the title of the Workspace in VSCode Insiders is **UNTITLED (WORKSPACE)** but, the current version (1.17) having the name of the project as a title. 

If we keep adding folders in an existing workspace like as the current behavior of the Insiders, what would be the title for the Workspace?

**Comment by bpasero** [comment]
@karuppasamy you can save a workspace to assign a name via File > Save Workspace As.

**Comment by tangorboyz** [comment]
can drag and drop  copy or folder to current workspace? I would really like that feature.

**Comment by karuppasamy** [comment]
Closing this ticket since the expected functionality has done as part of the feature implementation #396
