### ISSUE TITLE
Named workspaces + `window.title`

### ISSUE THREAD

**Issue by shobhitg** [Microsoft/vscode#35845]
Hi,

It would be awesome if we have the ability to name our workspaces. And subsequently be able to use them in `window.title` setting.

Like this:

```
{
  "settings": {
    "workspace.Name": "ui-ng"
    "window.title": "${workspaceName}${separator}${activeEditorMedium}${separator}${dirty}"
  }
}
```

And the same workspace names should be used to open recent workspaces in vscode.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33340
