### ISSUE TITLE
quickOpenNavigate* run selected option

### ISSUE THREAD

**Issue by cryptomaniac512** [Microsoft/vscode#35851]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.13_1
- Extensions: Extensions are disabled
---
It looks like quickOpenNavigate* and quickOpenSelect* works similar

Steps to Reproduce:

1. Set this
```
{
   "command": "workbench.action.quickOpenNavigateNext",
   "key": "ctrl+n",
   "when": "inQuickOpen"
},
{
   "command": "workbench.action.quickOpenNavigatePrevious",
   "key": "ctrl+p",
   "when": "inQuickOpen"
},
```

2. Run quick open and previous next with ctrl+p
3. Release pressed keys
4. Option will run

I think option must be running after pressed Enter.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This works as designed for fast keyboard navigation in quick open.

**Comment by cryptomaniac512** [comment]
But it's not convenient. It would be nice if this behavior was customizable.
What should I do if I opened the command palette and then changed my mind?

**Comment by cryptomaniac512** [comment]
What is the difference between quickOpenNavigate* and quickOpenSelect*?

> This works as designed for fast keyboard navigation in quick open.

it hurts if I want to call a command, and then I change the solution.
