### ISSUE TITLE
Explorer on focus opens the file under the cursor as a preview editor

### ISSUE THREAD

**Issue by itiut** [Microsoft/vscode#35858]
- VSCode Version: 1.17.0 be377c0faf7574a59f84940f593a6849f12e4de7
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Close all editors.
2. Show explorer (<kbd>shift+cmd+e</kbd>) and move the cursor to a file.
3. Hide sidebar (<kbd>cmd+b</kbd>).
4. Show explorer again (<kbd>shift+cmd+e</kbd>). Then, the file under the cursor is opened on a preview editor.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I acknowledge this issue and the explorer has always behaved like this.
The problem here is that the explorer get focus due to the newFile action and whenever explorer gets focus it always opens the focused element here

I think this is a limiation we can live with.
fyi @bpasero

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
