### ISSUE TITLE
bug ! 在最新1.17.0版本中 终端 输入中文 删除会留下半边字

### ISSUE THREAD

**Issue by davy-gan** [Microsoft/vscode#35855]
![d63ab5f6-5442-477e-9845-49f674b03afd](https://user-images.githubusercontent.com/21240946/31323648-651abd26-ac70-11e7-8348-26844083b09e.png)

![155933309f2b1f579b385cb58abba58b](https://user-images.githubusercontent.com/21240946/31323647-61a51eac-ac70-11e7-942a-5196e5e74802.jpg)
![033ce878-e7e4-429d-980e-595461e91b8a](https://user-images.githubusercontent.com/21240946/31323646-60d27042-ac70-11e7-824c-6f0a0a98c5fb.png)

如图 删除不掉 中文

**Comment by yoyo837** [comment]
![8fc7c98d-c8a6-4ffc-a961-f62e81fcf87c](https://user-images.githubusercontent.com/6134547/31324271-aaa076f6-ace3-11e7-99f4-28590e5f9424.png)
![ff5c0233-3c2e-4e6f-80d3-b89447e3ba4e](https://user-images.githubusercontent.com/6134547/31324272-aaa667dc-ace3-11e7-9e38-601aad083b3d.png)

**Comment by superlbr** [comment]
+1, 使用扩展屏的时候，还可能出现缩放比例失调的现象

**Comment by wuhuatianbao007** [comment]
我的也有这个问题
![vscode012312314350320](https://user-images.githubusercontent.com/21991861/31324445-36f0fcd2-ac78-11e7-9d14-ddf01f969cf9.png)

**Comment by banyudu** [comment]
duplicate https://github.com/Microsoft/vscode/issues/35660

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
