### ISSUE TITLE
Recongize .xhtml files

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/vscode#3585]
Visual Studio Code does not provide any IntelliSense, not even syntax highlighting, for .xhtml files. If IntelliSense for .html file cannot be used because of the possible conflict between the compact xhtml syntax and html syntax, I think .xhtml file should at least be treated as an XML file, which has syntax highlighting and bracket/quotes matching.

**Comment by Tyriar** [comment]
This will be in the March release https://github.com/Microsoft/vscode/issues/3521
