### ISSUE TITLE
There is a problem with the terminal display

### ISSUE THREAD

**Issue by W1821** [Microsoft/vscode#35852]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
Angular-BeastCode|Mik|5.0.6
debugger-for-chrome|msj|3.3.1

---

Steps to Reproduce:

1.
![default](https://user-images.githubusercontent.com/32122849/31323101-f4c295a2-acd4-11e7-82b8-8572f80bada4.png)

2.

Reproduces without extensions: Yes/No

**Comment by Treri** [comment]
Duplicate #35660 and had been fixed in [September Recovery 2017](https://github.com/Microsoft/vscode/milestone/55)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
