### ISSUE TITLE
vscode terminal display problem

### ISSUE THREAD

**Issue by HeartUnchange** [Microsoft/vscode#35857]
![image](https://user-images.githubusercontent.com/8402502/31323720-5864a826-acde-11e7-88bd-6a37643e7ff2.png)

- VSCode Version:
![image](https://user-images.githubusercontent.com/8402502/31323627-0b8c00cc-acdd-11e7-975b-bb0f6d2d7e20.png)

- OS Version:
![image](https://user-images.githubusercontent.com/8402502/31323623-fd65d54a-acdc-11e7-9268-02f91802f3c5.png)

Steps to Reproduce:

1. open Terminal (集成终端, ctrl+`), 
2. input some Chinese characters, like 你好
3. type Enter to make the scroll bar visible

Reproduces without extensions:  didn't check.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
