### ISSUE TITLE
Paste broken

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#35853]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Copy text
2. In editor paste CMD+V

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Are you using `tmux` or something similar when starting VSCode?

**Comment by rajinder-yadav** [comment]
This is working again in v1.17.0, closing, thanks!
btw, Had nothing to do with tmux in the previous version, as I tried opening from a normal terminal.
