### ISSUE TITLE
Integrated Terminal render error in chinese

### ISSUE THREAD

**Issue by xiaoyueguang** [Microsoft/vscode#35850]
- VSCode Version: 1.17.0
- OS Version: macOS 10.13

Steps to Reproduce:

1. when use integrated terminal. rendering error in chinese
![IMG](http://ovhfrawes.bkt.clouddn.com/QQ20171009-084837.png)

Reproduces without extensions: Yes

**Comment by doommm** [comment]
got the same issue in OS win10(1703)

**Comment by Treri** [comment]
Duplicate #35660 and had been fixed in [September Recovery 2017](https://github.com/Microsoft/vscode/milestone/55)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
