### ISSUE TITLE
Terminal: Output rendered as black/shadowed font color

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#35862]
- VSCode Version: Code - Insiders 1.18.0-insider (af6ca44db81f5186d3104226c8e76e026789ce20, 2017-10-06T05:26:16.770Z)
VSC Stable 1.17.0

Believed to start approximately 1.5wks ago in insiders.

- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
git-easy|bib|1.9.1
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.9
vscode-eslint|dba|1.3.2
git-extension-pack|don|0.1.3
githistory|don|0.2.3
gitlens|eam|5.4.1
tslint|eg2|1.0.9
git-project-manager|fel|1.4.0
file-icons|fil|1.0.5
vscode-npm|fkn|3.3.0
code-runner|for|0.7.2
macros|ged|1.2.0
hello|hyp|0.1.1
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.36
start-git-bash|McC|1.2.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
git-add-remote|sam|0.0.2
code-settings-sync|Sha|2.8.3
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0
vscode-open-in-github|ziy|1.2.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start Code
- Start a single terminal
- Exit Code
- Restart Code
- 90% of time the terminal output will render as black (slightly visible, not blank)

- Opening new terminals does not clear the issue
- If you killed the terminal and then restart the problem will frequently go away
Update Note
- Change of color theme sometimes fixes the issue

Reproduces without extensions: Yes

* Zoom to see characters in terminal
![terminal black rendering](https://user-images.githubusercontent.com/25272315/31324502-3c5f0a52-ac81-11e7-9d13-5f7eeb59f98e.png)

**Comment by Tyriar** [comment]
Weird I haven't seen this at all. You indicate the issue is not particularly consistent, but are you able to get reasonably consistent repro steps?

Do you have custom colors set in your cmd.exe properties?

**Comment by cleidigh** [comment]
@Tyriar 
it is weird.
It is actually close to a hundred percent reproducible if I close Code with at least one active terminal.
Upon restart font is black.  I can restart code over and over and this will persist. Once I restart code
with no terminal things get back to normal.  I thought it might be something to do with themes since I'm working on select box improvements and changing themes a lot.  I have no terminal color set.
One new observation I don't think it ever happens with light themes.  So it may indeed be related to themes.  It is almost as if the terminal erroneously gets into a light theme independent of the rest of the UI.  

if you can think of any experiments I'll happily do them.

**Comment by cleidigh** [comment]
@Tyriar 
I have not seen this since the last couple of insiders releases.
I think we can go and close.

**Comment by Tyriar** [comment]
@cleidigh great, thanks for the update 😃
