### ISSUE TITLE
Ignore white space in diff

### ISSUE THREAD

**Issue by satkamar** [Microsoft/vscode#35868]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
There is the setting `diffEditor.ignoreTrimWhitespace`, which is set to true by default.

**Comment by Thaina** [comment]
@alexandrudima I think this issue mean ignoring whitespace between the line. Such as changing from 2 spaces to 1 space. Or changing from tab to space in front of assignment operator and so on

And I want it too
