### ISSUE TITLE
garbled characters in integrated terminal with WSL on windows

### ISSUE THREAD

**Issue by Jianbo-Yang** [Microsoft/vscode#35869]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
python|don|0.7.0
code-runner|for|0.7.2
Go|luk|0.6.66
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-docker|Pet|0.0.18
java|red|0.11.0
vscode-icons|rob|7.15.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Jianbo-Yang** [comment]
![image](https://user-images.githubusercontent.com/12404591/31326106-e012515c-acf6-11e7-8aa6-23ea87870d99.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
