### ISSUE TITLE
[Feature request] Allowing to disable an extension in an extension pack

### ISSUE THREAD

**Issue by royling** [Microsoft/vscode#35863]
Now, it's not allowed to disable an extension if it's included/dep in a pack, but there are cases that I want an alternative one instead of the one in the pack, eg. color/icon themes. Is it reasonable to support it?

- VSCode Version: Latest
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@royling I do not think so. Since they are dependencies, not having them in the runtime might break the depending extension.
