### ISSUE TITLE
升级到1.17.0后，终端乱码了

### ISSUE THREAD

**Issue by wuhuatianbao007** [Microsoft/vscode#35861]
- VSCode Version:   1.17.0
- OS Version:   10.12.5

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/21991861/31324261-9b83979c-ac76-11e7-9089-9937e1ceba46.png)

1.   terminal display garbled
![vscode012312314350320](https://user-images.githubusercontent.com/21991861/31324367-59a3026c-ac77-11e7-806c-c82a68f03ff2.png)

Reproduces without extensions: Yes

**Comment by wuhuatianbao007** [comment]
输入中文，然后删掉就会这样子

**Comment by yoyo837** [comment]
duplicate #35855

**Comment by celestialphineas** [comment]
It seems that this has been solved: https://github.com/Microsoft/vscode/commit/c7d4aed6a45c1498520b58463601cb82925cceb0 
We now only need to wait for the next release.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
