### ISSUE TITLE
Coffeescript 2 and JSX syntax

### ISSUE THREAD

**Issue by damaera** [Microsoft/vscode#35860]
- VSCode Version: 0.17
- OS Version: Debian

JSX is now supported in coffescript2: http://coffeescript.org/#jsx
It would be awesome to have the syntax supported in `.coffee`

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/atom/language-coffee-script/issues/135

**Comment by aap82** [comment]
Here's the syntax file I use.  I just inserted the relative portions of the CJSX tmbundle into the current coffeescript one.  I know nothing about TM grammar, but this file when using jsx syntax for me.

https://gist.github.com/aap82/e4d6d68e5caa891092c58e4f09994f60

I

**Comment by mjbvz** [comment]
Closing as upstream. We'll pull in the fix if is ever made upstream but have no plans to work on this right now. If you want this supported, please submit a pr for atom/language-coffee-script#135
