### ISSUE TITLE
Terminal Chinese garbled

### ISSUE THREAD

**Issue by sbfkcel** [Microsoft/vscode#35865]
![snipaste20171009_123426](https://user-images.githubusercontent.com/5469785/31325323-5b777baa-acee-11e7-8ae2-fc74735c4aad.png)

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typescript-react-snippets|abo|0.2.0
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
alignment|ann|0.3.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
vscode-weapp-api|cod|0.1.8
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
jquerysnippets|don|0.0.1
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
react-native-react-redux|EQu|1.4.1
terminal|for|0.0.10
beautify|Hoo|1.1.1
docthis|joe|0.4.8
Angular2|joh|2.7.0
azure-functions-tools|joh|0.3.1
markdown-table-formatter|jos|0.2.3
vscode-codemetrics|kis|1.9.6
vscode-jade-snippets|mrm|1.0.1
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
vscode-for-node-js-development-pack|nod|1.1.0
vscode-code-outline|pat|0.0.11
vscode-docker|Pet|0.0.18

material-icon-theme|PKi|2.2.2
sass-indented|rob|1.4.2
code-settings-sync|Sha|2.8.3
language-stylus|sys|1.7.3
react-redux-es6-snippets|tim|2.1.0
jsx|Twe|0.0.1
MarkdownToHtml|WaT|1.0.1
vscode-import-cost|wix|2.5.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by holynewbie** [comment]
In my oponion, it's not garble but residual. when you resize the integrated terminal, all the characters disappear. I think it's because this version of vsc use **canvas** to render terminal.

**Comment by sbfkcel** [comment]
@holynewbie Yes, I think so.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
