### ISSUE TITLE
when I run a py file, there are a lot of extra characters in the console.

### ISSUE THREAD

**Issue by Huang-Jinxian** [Microsoft/vscode#35873]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.4.1
tslint|eg2|1.0.9
code-runner|for|0.7.2
sublime-babel-vscode|jos|0.2.9
java|red|0.11.0
vscode-java-debug|vsc|0.1.0
vim|vsc|0.10.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1. run py file to parse html 
2. print html content
3. a lot of extra characters in the console, they are words already exist, and appear twice or more times, and the worst thing is that each character in them only have half of it, and only Chinese characters have this situation.
![image](https://user-images.githubusercontent.com/22197930/31328678-f81e5d78-ac9b-11e7-93f3-4ce3227ee441.png)

Reproduces without extensions: Yes/No

**Comment by Huang-Jinxian** [comment]
![image](https://user-images.githubusercontent.com/22197930/31328662-e553903c-ac9b-11e7-9f25-6af26bfc7c52.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
