### ISSUE TITLE
Import path quick suggestions - add disable option

### ISSUE THREAD

**Issue by mudrz** [Microsoft/vscode#35877]
- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

**Could not find a setting to disable the newly enabled 'import path quick suggestions'**

Reproduces without extensions: Yes

I am having a terrible experience with it
- It is painfully slow on a medium sized project and unusable on a big project - there is 2-4 seconds delay before folder/files suggestions are shown
- Doesn't work properly with aliases added in `jsconfig.json` https://code.visualstudio.com/docs/languages/jsconfig
- the extension https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense already does everything I could ask from path Intellisense and yet - I cannot use it, because there is no setting to disable the native path Intellisense

In general it would be really nice to be able to opt-out of new functionality until it is battle-tested and settled instead of disrupting existing workflows after updates.
Disabling VS Code auto-updates is not an ideal solution
(not trying to be salty, simply sounds like a nice to have feature)

**Comment by mjbvz** [comment]
Yeah we can add a setting to disable this but I'm surprised you weren't seeing these issues before. Path intellisense for JS and TS has been in VSCode since 1.9, all 1.17 did was enable triggering suggestions automatically when you start writing a path.

Also can you please file separate issues for the perf and jsconfig bugs you are seeing?

**Comment by mudrz** [comment]
Sure, created 2 new issues

https://github.com/Microsoft/vscode/issues/35970

https://github.com/Microsoft/vscode/issues/35971

Not sure why I wasn't seeing the issue before, it's possible that the `path-intellisense` extension was somehow overriding the default behaviour

**Comment by mjbvz** [comment]
Added a `typescript.quickSuggestionsForPaths` setting to disable this. It is enabled by default

Should be in next week's insiders builds
