### ISSUE TITLE
Occupy too many system resources

### ISSUE THREAD

**Issue by jaylinwang** [Microsoft/vscode#35879]
- VSCode Version: 1.17.0 (1.17.0)
- OS Version: 10.12.6 (16G29)

When open javascript project.  a process named **Code Helper** occupy too many CPU and Memory

**Comment by chrmarti** [comment]
What are the command arguments of the Code Helper?

**Comment by jaylinwang** [comment]
same as [#11963](https://github.com/Microsoft/vscode/issues/11963). but my vscode version is 1.17.0

**Comment by chrmarti** [comment]
Could you check what the command line arguments are and post these here? I don't see which part of #11963 you are referring to.
