### ISSUE TITLE
Newest version occupy too much CPU

### ISSUE THREAD

**Issue by linxiangjun** [Microsoft/vscode#35872]
- VSCode Version:1.17.0
- OS Version:Windows 10

Steps to Reproduce:

1.Open VSCode software
2.Two unknown .exe files called 'rg.exe' which occupy too mush CPU(more than 50%),When you close VSCode,It's will be release.This is only find in newest version,old version don't find this question.Please reply as soon as possible,Thanks.

**Comment by kybom** [comment]
The same to you.
My os is Ubuntu 16.04.
VScode starts slowly, and occupies too much CPU.

**Comment by chrmarti** [comment]
Duplicate of #35659
