### ISSUE TITLE
bug：更新版本之后，终端的问题（terminal bug）

### ISSUE THREAD

**Issue by f839903061** [Microsoft/vscode#35874]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-mail|ccc|1.1.2
vscode-markdownlint|Dav|0.10.1
githistory|don|0.2.3
git-project-manager|fel|1.4.0
Go|luk|0.6.66
prettify-json|moh|0.0.3
sublime-keybindings|ms-|2.9.1

---

Steps to Reproduce:

1.我替换了terminal为git bash 
2.当我使用git log 的时候，我的某些commit message 里面包含(contains)中文chinese-simplified 
3.这个是我录的gif picture [https://imgur.com/a/YNTmd](https://imgur.com/a/YNTmd)

Reproduces without extensions: Yes/No

**Comment by kotot** [comment]
the same to you

**Comment by dolphinfine** [comment]
同样的问题

**Comment by copie** [comment]
the same to you

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
