### ISSUE TITLE
在终端里 git log 会有残影

### ISSUE THREAD

**Issue by donhwa** [Microsoft/vscode#35876]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
vscode-auto-open-markdown-preview|hnw|0.0.4
search-node-modules|jas|1.2.0
Angular2|joh|2.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.12.1
vetur|oct|0.9.10
typescript-hero|rbb|1.5.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.open teminal
2.git log
3.中文残影（在空白行中显示下一行里每个字的右半部分）

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
