### ISSUE TITLE
Good First Bugs

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3587]
React does something cool to bring contributors up to speed in their repo. They use [good first bugs](https://github.com/facebook/react/labels/good%20first%20bug) as a stepping stone for getting into the code. We could look into doing something similar.

**Comment by Tyriar** [comment]
:+1:

**Comment by bgse** [comment]
Maybe go even further?

Personally, I'd love to have some kind of indication if the issue/feature-request will be handled internally by Microsoft people (in the near future) or if it is something that is encouraged to be handled by public contributors.

Especially for things that might not exactly be a "good first bug", one might want some indication if the time they invest is likely to be in vain as there is already someone working on it internally and that solution will take precedence.

**Comment by Tyriar** [comment]
@bgse that's what the help wanted label is supposed to be for, I don't see it getting used much though. Due to the way issues are assigned based on ownership and not who's working on it currently, I can see the issue you're bringing up.

**Comment by waderyan** [comment]
We could use Assignee to show that the issue has been picked up by someone on the team. If it isn't assigned it hasn't been picked up. Would that be clear enough? 

help-wanted could be changed to something more clear. Here are a few proposals. 
- "help wanted from community"
- "community help here"
- "good for community help"

For issues that are good for someone to start with we could label them one of the following:
- "good first bug"
- "good for first time contributor"
- "start here"
- "community start here"

We want to add something to the [How to Contribute wiki](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) and possibly to the [README](https://github.com/Microsoft/vscode/blob/master/README.md) to help folks know how to get started.

**Comment by egamma** [comment]
@waderyan 
>We could use Assignee to show that the issue has been picked up by someone on the team. If it isn't assigned it hasn't been picked up. Would that be clear enough? 

I see you have never been the inbox tracker :smile:

Pls see https://github.com/Microsoft/vscode/wiki/Issue-Tracking. We can always change how we do things, but we should preserve thins what work OK. The two-step inbox triage has worked OK, so we should preserve this one way or the other.

@bgse 
>Personally, I'd love to have some kind of indication if the issue/feature-request will be handled internally by Microsoft people (in the near future) or if it is something that is encouraged to be handled by public contributors.

We plan one milestone ahead and we have the roadmap, so you can use the milestone label as good indicator for this. If in doubt then asking a question in the issue seems appropriate to me.

**Comment by waderyan** [comment]
Ha yeah maybe I could take on that role one week to feel the pain :smile:

@egamma feedback on changing "help-wanted" label change?

**Comment by egamma** [comment]
@waderyan I prefer shorter labels and to document how we use the labels in the CONTRIBUTING.md. So `help-wanted` works still better for me but we should document and agree on how we use it.

A new label for `beginner bugs` makes sense to me.

**Comment by waderyan** [comment]
Makes sense.

**Comment by waderyan** [comment]
Suggestion from standup was to use `beginner task` to be more generic.

**Comment by waderyan** [comment]
Ok. @chrisdias and I decided to go with `effort easy`. It is concise, avoids bad connotation we feel with "beginner", and explains the difficulty of the issue clearly. 

We can easily iterate on this, so please suggest a new name if you have improvements. I will update the wikis.
