### ISSUE TITLE
feedback - different number of available characters " :-) vs :-( "

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35882]
- VSCode Version: 1.17.0 c[ be377c0faf7574a59f84940f593a6849f12e4de7 ]
- OS Version: Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3

Steps to Reproduce:

![screenshot_101](https://user-images.githubusercontent.com/31345346/31330972-c347d288-ace0-11e7-8456-42ff850d837b.png)
![screenshot_103](https://user-images.githubusercontent.com/31345346/31330971-c3468ffe-ace0-11e7-93d4-58d82841eef9.png)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This is as designed.
Will not fix
More details https://github.com/Microsoft/vscode/commit/3e7a20469e2898addd319fdc2fc5f350724fab24
