### ISSUE TITLE
Inconsistent file icons using '.h'

### ISSUE THREAD

**Issue by litarussell** [Microsoft/vscode#35888]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
tslint|eg2|1.0.9
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
Go|luk|0.6.66
cpptools|ms-|0.13.1

---

Steps to Reproduce:

1.what's happening?
![img](http://wx2.sinaimg.cn/mw690/c9c97f9ely1fkc554lrtfj208i08oq30.jpg)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Which file icon theme is this?

.h files always show as '.h' for me using Seti UI, I think that's expected.
