### ISSUE TITLE
Extensions: Do not prompt to reload when the user just pressed the 'reload' button

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#35884]
See the screenshot below. I've just pressed 'reload' in the Extensions Viewlet and I'm getting prompted whether I want to reload? Is there  a reason why we guard the 'reload', can anything be lost? If there isn't anything then I suggest to not show the prompt.

![image](https://user-images.githubusercontent.com/172399/31331180-ac2bc75c-ace1-11e7-9e0f-23c1723d905a.png)

**Comment by sandy081** [comment]
No, I think this does not makes sense. We also do not prompt when user executes the command `Reload Window`. 

I will remove the additional dialog.
