### ISSUE TITLE
[Scss/Less] @supports linting as nested rule

### ISSUE THREAD

**Issue by bojan-stojanovic** [Microsoft/vscode#35887]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-opennewinstance|chr|0.0.4
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
vscode-placeholder-images|Jak|0.1.0
easy-less|mrc|1.4.5
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.2
stylelint|shi|0.29.1
highlight-matching-tag|vin|0.4.4
---

Steps to Reproduce:

1. Make .scss or .less file
2. Make some rules for some class or id
3. Add @supports rule inside class or id
4. Default VSC's built in style linter will mark this rule as invalid
![less](https://user-images.githubusercontent.com/32634808/31331698-b0f6bbd2-ace3-11e7-9369-0ef97bcf19ea.jpg)
![scss](https://user-images.githubusercontent.com/32634808/31331697-b0f63af4-ace3-11e7-8027-4f6ffc98d696.jpg)

How should it work:
Default VSC's style linter should not mark this rule as invalid, it should work as stylelint plugin which doesn't mark this rule as invalid.

Reproduces without extensions: Yes

**Comment by simgooder** [comment]
Any word on this? It's driving me crazy!

**Comment by aeschli** [comment]
Pushed a fix for 1.19.
