### ISSUE TITLE
Teminal Console log seems some thing wrong on Chinese OS env!

### ISSUE THREAD

**Issue by iqianxing** [Microsoft/vscode#35889]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.2.0
githistory|don|0.2.3
xml|Dot|1.9.2
javac-linter|fau|1.2.6
beautify|Hoo|1.1.1
vue|liu|0.1.5
vetur|oct|0.9.10
java|red|0.11.0
react-beautify|tai|0.3.0

---

Steps to Reproduce:

1.The message on my code's teminal console log message seems something wrong
2.
![image](https://user-images.githubusercontent.com/2938263/31332951-eb21344a-ad1a-11e7-9aeb-7e690d45691d.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
