### ISSUE TITLE
Wrong place for lightbulb

### ISSUE THREAD

**Issue by bam** [Microsoft/vscode#35880]
- VSCode Version: 1.17.0
- OS Version: Windows 7 Pro 64

Steps to Reproduce:

1. Open file with linting error that could be fixed with fix options
2. Put cursor on struggled line, and find the lightbulb

![image](https://user-images.githubusercontent.com/2446302/31330470-4a2c2a50-ace7-11e7-9a47-870625d223cd.png)

**Comment by jrieken** [comment]
duplicate of #25174
