### ISSUE TITLE
electron demo运行成功后，过几秒自动崩掉

### ISSUE THREAD

**Issue by li986390329** [Microsoft/vscode#35894]
- VSCode Version: 1.17（之前1.16版本也一直不行）
- OS Version: windows7

Steps to Reproduce:

1.下载electron demo 到vscode中运行
2.protocol已经改为legacy
3.程序刚开始是运行成功的，但是过了几秒之后就提示：无法通过 "legacy" 协议连接到运行时；请尝试使用 "inspector" 协议。程序自动终止。

希望得到解答，代码就是https://github.com/electron/electron-quick-start，最简单的demo,不过事实证明其他的也是同样现象。

**Comment by isidorn** [comment]
Please file this issue in english. We do not speack chineese. Thank you

**Comment by li986390329** [comment]
oh,sorry,I just want to say this issue :

- VSCode Version:1.17(The 1.16 version  of the existence of this problem)
- OS Version: windows7

Steps to Reproduce:
1.Download electron demo to run in vscode.
2.The protocol has been changed to legacy.
3.The program was just running successfully, but after a few seconds it was prompted:Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol.The program automatically terminates.

Hope to get the answer, the code is https://github.com/electron/electron-quick-start, the simplest demo, but the fact that the other is the same phenomenon.
Thank you very much.

**Comment by isidorn** [comment]
Please put "protocol": "inspector" in your "launch.json".
If thta does not work please try reproducign with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by roblourens** [comment]
Can you post the launch config that gave this problem?

**Comment by li986390329** [comment]
launch config is :

"version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron Main",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "program": "${workspaceFolder}/main.js",
            "protocol": "legacy"
        }
protocol:inspector,Protocol changed to inspector  it does not work at all. I am confused.Thank you .

**Comment by auchenberg** [comment]
@li986390329 Try to remove `"protocol": "legacy" from your `launch.json`

**Comment by li986390329** [comment]
When i removed "protocol": "legacy"，it use inspector , it was prompted：can not connect to a running process and will time out after 10,000 milliseconds

**Comment by roblourens** [comment]
> it was prompted：can not connect to a running process and will time out after 10,000 milliseconds

Sorry I don't understand what you mean.
