### ISSUE TITLE
Go to definition doesn't work with ES modules using .mjs extension

### ISSUE THREAD

**Issue by mfidemraizer** [Microsoft/vscode#35892]
- VSCode Version: 1.17
- OS Version: Any

Newer NodeJS versions including latest have broad native support to ES2015 and ES2017 and they already support ES modules. NodeJS team decided to support ES modules instead of CJS on files using the `.mjs` file extension.

Visual Studio Code currently won't be able to direct to symbol's definition using *Go to definition* when JavaScript code files are using `.mjs` extension.

Steps to Reproduce:

1. Rename a Node package source files to use the *.mjs file extension
2. Press F12 or click on *Go to definiton* in editor's context menu.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19119
