### ISSUE TITLE
Automatically installed extensions from 'Welcome' page

### ISSUE THREAD

**Issue by pretodor** [Microsoft/vscode#35895]
When clicking on one of the suggested extensions under 'Customize' > 'Tools and languages' on the 'Welcome' page the extension will get installed without asking the user for confirmation.

- VSCode Version: 1.17.0
- OS Version: Linux Mint 18 Cinnamon (64-bit)

Steps to Reproduce:

1. Open Visual Studio Code
2. Click on one of the suggested extensions under 'Customize' > 'Tools and languages' on the 'Welcome' page
3. A prompt will appear on the top of the window saying 'The window will reload after installing additional support for <extension_name>'
4. The extension will get installed

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
This is by design so there are less steps to go through to get things up and running for the new user.
