### ISSUE TITLE
(keybindings.json & Keyboard Shortcuts)  Can't type Polish characters in (with extensions) editor 

### ISSUE THREAD

**Issue by CisSasGot** [Microsoft/vscode#35899]
- VSCode Version: 1.18.0 - insider
- OS Version: Win10

Reproduces without extensions: [Yes] / No

Steps to Reproduce:
**I have the big problem because Can't type Polish characters in editor.**

I have added exceptions to the settings, but some characters still do not work (keybindings.json)
```json
[
    { "key": "alt+a", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+a", "command": "", "when": "editorTextFocus" },

    { "key": "alt+c", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+c", "command": "", "when": "editorTextFocus" },

    { "key": "alt+e", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+e", "command": "", "when": "editorTextFocus" },

    { "key": "alt+l", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+l", "command": "", "when": "editorTextFocus" },

    { "key": "alt+n", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+n", "command": "", "when": "editorTextFocus" },

    { "key": "alt+o", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+o", "command": "", "when": "editorTextFocus" },

    { "key": "alt+s", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+s", "command": "", "when": "editorTextFocus" },

    { "key": "alt+x", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+x", "command": "", "when": "editorTextFocus" },

    { "key": "alt+z", "command": "", "when": "editorTextFocus" },
    { "key": "alt+shift+z", "command": "", "when": "editorTextFocus" }
]
```

### All special characters for the Polish language are:

Ą / ą | Ć / ć | Ę / ę | Ł / ł | Ń / ń | Ó / ó | Ś / ś | Ź / ź | Ż (Ƶ ) / ż (ƶ)
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
[`AltR`]+[`shift`]+[`a`] | [`AltR`]+[`shift`]+[`c`] | [`AltR`]+[`shift`]+[`e`] | [`AltR`]+[`shift`]+[`l`] | [`AltR`]+[`shift`]+[`n`] | [`AltR`]+[`shift`]+[`o`] | [`AltR`]+[`shift`]+[`s`] | [`AltR`]+[`shift`]+[`x`] | [`AltR`]+[`shift`]+[`z`] 
[`AltR`]+[`a`] | [`AltR`]+[`c`] | [`AltR`]+[`e`] | [`AltR`]+[`l`] | [`AltR`]+[`n`] | [`AltR`]+[`o`] | [`AltR`]+[`s`] | [`AltR`]+[`x`] | [`AltR`]+[`z`] 
  |    |    |    |    |    |    |    |  
`&#260;` / `&#261;` | `&#262;` / `&#263;` | `&#280;` / `&#281;` | `&#321;` / `&#321;` | `&#323;` / `&#324;` | `&#211;` / `&#243;` | `&#346;` / `&#347;` | `&#377;` / `&#378;` | `&#379;` (`&#437;`)/ `&#380;` (`&#438;`)
  |    |    |    |    |    |    |    |  
`U+0104` / `U+0105` | `U+0106` / `U+0107` | `U+0118` / `U+0119` | `U+0141` / `U+0142` | `U+0143` / `U+0144` | `U+00D3` / `U+00F3` | `U+015A` / `U+015B` | `U+0179` / `U+017A` | `U+017B` (`U+01B5`)/ `U+017C` (`U+01B6`)

Is it possible to programmatically force a character after a character's hotkey usage with either by UNICODE or an Html Entity?

# How to overcome this problem?

**Comment by CisSasGot** [comment]
#### For example, I need to use the .... extension, but it blocks the use of the .... character
- **Code Runner** -> block the [**ń**] character
- **TypeScript Extension Pack: json2ts** -> block the [**ź**] character
- **SCSS Refactoring** -> block the [**ę**] character

#### This (in principle) does not need, but informs that:
- **TypeScript Extension Pack: Hero r** -> block the [**ó**] character
- **JSON to TS** -> block the [**ś**] character

## Can I do it, somehow this is to go around, to use extensions and can use the Polish characters?

**Comment by SylwesterZarebski** [comment]
Question to developers: Is <kbd>Ctrl+Alt</kbd> different from <kbd>AltGr</kbd>?
If no, it is serious bug, these should be never ever mixed together, because it have very different meaning.

I found similar (but closed?!) issue: #21746.

**Comment by alexandrudima** [comment]
@SylwesterZarebski We cannot differentiate <kbd>Ctrl+Alt</kbd> from <kbd>AltGr</kbd>.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState
![image](https://user-images.githubusercontent.com/5047891/35682883-83c6ad0a-0762-11e8-8692-78a50ae3410e.png)

https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute
![image](https://user-images.githubusercontent.com/5047891/35682946-baa6a94c-0762-11e8-96f2-528564dfb353.png)

AFAIK, we do our best to not ship with <kbd>ctrl</kbd>+<kbd>alt</kbd>+ keybindings

**Comment by alexandrudima** [comment]
@CisSasGot on a default VS Code installation (no extensions), I was able to type all of the special Polish characters that you list above. I believe you have installed an extension that binds `ctrl+alt+` keybindings. Using the UI (ctrl+k ctrl+s) you can search for these keybindings and remove them. You can also contact the extension author that defines these keybindings and ask them to remove them.

**Comment by SylwesterZarebski** [comment]
Note: this is shortcoming of browsers (also Blink engine which is base for Electron), but native program should have no problem detecting <kbd>AltGr</kbd> from <kbd>Ctrl</kbd>+<kbd>Alt</kbd> on any nowadays system.
