### ISSUE TITLE
Create groups to organize installed extensions

### ISSUE THREAD

**Issue by s-haensch** [microsoft/vscode#35891]
I would like to be able to create groups/subfolders for my installed extensions. Most importantly to seperate color themes from other utility extensions.

**Comment by iricigor** [comment]
+1 
If custom groups would be an issue, then at least, separate themes from other things. Or, for example. it can be grouped by extension categories.

**Comment by ashrafhadden** [comment]
@iricigor Similar to issue #55697

**Comment by ZenLiuCN** [comment]
I may wanna extensions split into groups and could be `enable` `disable` as groups..

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/20599
