### ISSUE TITLE
Release as NPM package

### ISSUE THREAD

**Issue by mihailik** [Microsoft/vscode#35896]
Currently VSCode can be downloaded as installer executable (MSI, deb, rpm, pkg...) or a zipped archive. Having that ZIP deployment is great for non-admin installs and portable USB stick model.

![vscode download page](https://user-images.githubusercontent.com/4041967/31337883-1db58d1e-acf5-11e7-923f-a458cd86bb09.png)

<h3>Add to that installation via NPM:</h3>

```BAT
C:> npm install @vscode/vscode
. . . 
C:> npm start
```

That would be useful for scenarios:
* Install the latest released (nightly) VSCode via unattended script
* Install specific version of VSCode in a guaranteed predictable manner
* CI and testing -- specific or latest version as a pre-requisite for test suite
* Predictable and quick way of getting a fresh VSCode for addon development needs
* Massive testing against a number of VSCode versions
* Very easy upgrade in all the above scenarios, across all the supported platforms: `npm install ...'

The heavy work of preparing ZIP packages for corresponding platforms (OSX, Windows, Linux) is already done as part of VSCode release. NPM deployment would re-package those bits into NPM package.

This is a non-conventional way of deploying apps, of course. But it may turn out a great deployment channel, simplify life to certain user categories, and ultimately widen the reach of the product.

**Comment by joaomoreno** [comment]
This won't happen.

But we do provide some REST routes, upon which you can do many things:

- `https://vscode-update.azurewebsites.net/api/update/win32/insider/latest` returns a JSON object with info about the latest build for `win32` `insider`
- `https://vscode-update.azurewebsites.net/latest/win32/insider` redirects to the download of the latest build for `win32` `insider`

Possible platforms:

- `win32-archive`
- `darwin`
- `linux-x64`
- `linux-x64-deb`
- `linux-x64-rpm`

Possible qualities:
- `insider`
- `stable`

**Comment by mihailik** [comment]
@joaomoreno thanks for the link!

I can see there is a way to fetch latest stable too:

https://vscode-update.azurewebsites.net/api/update/win32/stable/latest

Also I can infer another pattern for older versions:

https://vscode-update.azurewebsites.net/1.6.1/win32/

So pretty much all the heavy ground work is done — I guess if Microsoft doesn't provide a NPM route, I can just package it myself and let people use like that.

**Comment by mihailik** [comment]
Progressing on this: creating <a href="https://www.npmjs.com/package/@inst/vscode">@inst/vscode</a> packages to implement this idea.

* <a href="https://www.npmjs.com/package/@inst/vscode"><span>@</span>inst/vscode</a>
    * <a href="https://www.npmjs.com/package/@inst/vscode-bin-darwin"><span>@</span>inst/vscode-bin-darwin</a>
    * <span>@</span>inst/vscode-bin-win32
    * <span>@</span>inst/vscode-bin-linux *and so on*

The main package will install the appropriate platform-specific binary, and run the corresponding Electron from pre-crafted `code.js` in its root directory.

I'm figuring out minor npm details, but it looks promising so far. Glad I've snatched the <span>@</span>inst namespace, if it works for VSCode, it can be replicated for other Open Source apps.

**Comment by mihailik** [comment]
Repository with progress on this feature: https://github.com/mihailik/inst-vscode

**Comment by mihailik** [comment]
@jaomoreno these azurewebsites.net links return metadata and downloads for EXE builds (in case of win32).

Is there a similar link for ZIP builds please?

**Comment by mihailik** [comment]
Great news! Got it working on OSX, small glitches on Win32

The trouble with getting this through is `.npmignore` and `.gitignore` -- otherwise things work nicely.

**Comment by mihailik** [comment]
Fixed — now working for both `win32` and `darwin`.
