### ISSUE TITLE
Command line Chinese garbled

### ISSUE THREAD

**Issue by lvxv** [Microsoft/vscode#35890]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ejs-language-support|Qas|0.0.1
jsx|Twe|0.0.1
vscode-wakatime|Wak|1.1.16
vscode-eslint|dba|1.3.2
python|don|0.7.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
Lua|key|0.0.9
cpptools|ms-|0.13.1
Ruby|reb|0.15.0
vscode-icons|rob|7.15.0
vscode-lua|tri|0.8.1
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
