### ISSUE TITLE
VS Code - strange git behavior

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35897]
- VSCode Version: 1.17.0 c[ be377c0faf7574a59f84940f593a6849f12e4de7 ]
- OS Version: Windows 8.1 64-bit & Linux Ubuntu 16.04.2 Gnome 3

Steps to Reproduce:

https://youtu.be/JCQgfc6OEXM

I think, initializate repository should be disabled, if folder isn't opened.
Or if it's intention, why after close and again open VS Code it isn't inicializated?

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
We should probably not allow this, much less suggest it.

**Comment by joaomoreno** [comment]
Sorry, I thought you had a different issue: #35902

**Comment by Mlocik97-issues** [comment]
#35905

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
