### ISSUE TITLE
Polish Indentation story

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3590]
Changes to how the editor handles indentation:

- [ ] Provide the editor with the auto detected indentation #3259 
- [ ] Given the previous item, we can remove the editor input to indentation type map cache

Changes to the indentation status bar contribution:

- [ ] *Change Tab Size for Current File* action should be called: *Change Indentation Size*
- [ ] We should hide the action when the model has tabs, simply because it doesnt seem to be a use case that a user would like to change the tab indentation size for a single file. Its usually a setting.
- [ ] Move the action to the third position of the actions list, instead of the first
- [ ] Change *Configured Tab Size* to *Current Indentation Size*

**Comment by isidorn** [comment]
Fixed by the half the team

**Comment by joaomoreno** [comment]
Yay team work

![teamwork](http://i.giphy.com/bCd3nrE4UiJqg.gif)
