### ISSUE TITLE
[Feature Request] - VSCode ask to open folder if inicializate repo "out"...

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#35905]
#35902 

In the case of initiating repo out of the workspace, I think it would be advisable to suggest opening a folder in the VS Code, in the case of "multiroot" it would be without the "closure" of the previous workspace..... and keep it inicializated.

This could help with manipulating the "out" repos from VSCode...

**Comment by Mlocik97-issues** [comment]
as "out" I think external repositories and/or repositories what I inicializate from VS Code (like in video in #35897 - C:\Users\ ) locall.

**Comment by PaulTFreedman** [comment]
I'd be interested in working on this fix but I'm not quite clear on the problem, what do you mean by "out" repos?

**Comment by Mlocik97-issues** [comment]
If I haven't opened folder in VSCode and I click on inicializate repo, it ask to folder to inicializate, in "git in vscode" it open to panel, but in "explore in vscode" in panel no. 

![screenshot_110](https://user-images.githubusercontent.com/31345346/31567203-a01d544a-b06e-11e7-8529-0f00afd1844d.png)
![screenshot_111](https://user-images.githubusercontent.com/31345346/31567204-a0440d24-b06e-11e7-8aea-16e6a398a310.png)

(in the same moment), I think, if something is opened in "git in vscode" it's good to ask to "open in explorer in vscode".

**Comment by PaulTFreedman** [comment]
Ok, thanks for the clarification. If I understand you correctly you would like to see some kind of prompt appear at the point when you initialize the git repo asking whether the user would like to open the folder where the git repo was initialized.

I'd be happy to look into this but would welcome any tips from people familiar with the codebase, particularly if anyone knows about any similar prompts that already exists. Thanks!

**Comment by PaulTFreedman** [comment]
I've had some time to look at this today. I've found the CommandCenter.init() function which is called when we click the button to initialize a new repository, and I have found the WindowsService.openNewWindow() function which I believe can be used to open a new instance of VS Code.

However I can't see the best way to utilise the service in the init() function as there doesn't seem to be an instance of WindowsService available at that point. Anyone know how this should be done? Perhaps inject IWindowsService into the constructor? But WindowsService itself has quite a busy constructor which I would then also have to populate.

**Comment by Ankk98** [comment]
Anyone working on this issue?
I would like to try working on this issue, but I am a beginner if that's OK?

**Comment by sa-adebayo** [comment]
@Ankk98 are you currently working on this? There isn't any assignee yet.

**Comment by sucicf1** [comment]
Hello,
I made a pull request with solution to this bug. I tested it locally and it works, but before commit I used the -no-verify because it failed some test. Can somebody help me with that, why the test fail?

**Comment by bpasero** [comment]
@joaomoreno verification needed?

**Comment by alexr00** [comment]
@mjbvz, Where is the "Open folder on items in the VS Code git activity are in" supposed to be?

**Comment by joaomoreno** [comment]
**Verification steps:**

When initializing a git repo in an external folder, there should be a prompt to add that folder to the current workspace.

https://github.com/Microsoft/vscode/pull/58380

@alexr00 Not sure what you mean.
