### ISSUE TITLE
Cannot permanently turn off "Commits" and "Compare Commits" panels

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#35908]
- VSCode Version:Version 1.18.0-insider (1.18.0-insider)
- OS Version MacOS High Sierra

Steps to Reproduce:

1. Open a new window - by dragging a folder to the dock icon, or via the `open` terminal command
2. Commits and Compare Commits panels are open. Close with a Right Click, but they will open if a new window is opened again.

**Comment by isidorn** [comment]
@jtsom I can not reproduce. Whenever I open a new window the explorer always gets opened.
Can you please attach a video or a gif showing this problem?
@bpasero might this be some wait state the VSCode is left in?

**Comment by jtsom** [comment]
Ok, sorry for the noise.. after doing more investigation, these panels are coming from the Git History extension.

Thanks!
