### ISSUE TITLE
vscode terminal rendering wrongly !

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#35900]
- VSCode Version: simplified chinese edition 1.17.0 x64
- OS Version: simplified chinese win10 pro x64

Steps to Reproduce:

1. Enter "powershell"
2. Then "cls"
like below:
![test](https://user-images.githubusercontent.com/8075421/31338404-9fb14254-ad31-11e7-9fcd-f24b6a51b2e3.gif)

Reproduces without extensions: Yes/No

**Comment by Dwscdv3** [comment]
#35660 duplicated

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
