### ISSUE TITLE
User variables not used in command window path

### ISSUE THREAD

**Issue by neilw73** [Microsoft/vscode#35909]
Version 1.16.1
Date 2017-09-14T16:38:09.760Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

When I open a command window (F1/Open New Command Window), the path on this command window only picks up PATH created in the System variables (as seen in control panel/system properties), it ignores the PATH also created in user variables.

When you open a command window normally you get both user and system PATH as your path, in VS you do not.

What this means is things like node.js, npm and other applications that add themselves to the user path fail to work properly. 

I for example, installed node.js, opened a command window and node.js failed to run.

**Comment by joaomoreno** [comment]
What is your OS?
