### ISSUE TITLE
wrong order of next/prev buttons at touchbar

### ISSUE THREAD

**Issue by Eugene-Musika** [Microsoft/vscode#35906]
![image](https://user-images.githubusercontent.com/19905407/31339409-70f0d072-ad0b-11e7-8701-67187a265dcd.png)

- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:
1. Open VS Code

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Weird I am not seeing that in my High Sierra setup, with a touch bar simulator though. Is anyone else seeing this?

@Eugene-Musika does it reproduce in our insiders release? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Eugene-Musika** [comment]
Nothing changed
![image](https://user-images.githubusercontent.com/19905407/31406587-a454ddfa-ae0a-11e7-9f9d-bf63f3ecf4b5.png)

![image](https://user-images.githubusercontent.com/19905407/31406572-95cb837e-ae0a-11e7-8695-6c7f136e11f8.png)

**Comment by bpasero** [comment]
@Eugene-Musika weird, would you be able to follow https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source to do some code changes to find out further?

**Comment by Eugene-Musika** [comment]
@bpasero I would try on this weekend

**Comment by dmrz** [comment]
@Eugene-Musika Have you tried to build the latest version from source? I have the same issue with the wrong order of arrow buttons.

**Comment by bpasero** [comment]
Any update?

**Comment by dmrz** [comment]
Version 1.19, issue is still unresolved.

**Comment by Eugene-Musika** [comment]
Did you try steps, witch I mentioned in related issue #61150?

VSCode Version: 1.28.2
OS Version: macOS Mojave 10.14
Steps to Reproduce:

1. Open VS Code
2. Configure display language in locale.json to "ru"
3. Install Russian language pack
4. Few times open/close VS Code via CMD+Q

I have the latest available stable version of VS Code and problem is still here.

**Comment by bpasero** [comment]
Actually this will be fixed with https://github.com/microsoft/vscode/issues/85453
