### ISSUE TITLE
JS syntax highlighter bugs

### ISSUE THREAD

**Issue by pladaria** [Microsoft/vscode#35917]
- VSCode Version: 1.16.1
- OS Version: Ubuntu Xenial

Steps to Reproduce:
Create a .js file with this contents:
```javascript
const bug = ({
    a,
    b = []
}) => {
    console.log(`:${a}`, a);
    // now everything is red
    console.log('hello');
};
```
Syntax highlighting is now broken
![bug](https://i.imgur.com/Ft7Pjga.png)

This snippet also breaks highlighting, but differently
```javascript
const bug = ({
    a,
    b = []
}) => {
    console.log(a);
    // now everything is blue
    console.log('hello');
};
```
![bug2](https://i.imgur.com/skF6HNA.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This should be fixed in VS Code 1.17:

<img width="339" alt="screen shot 2017-10-09 at 8 34 54 am" src="https://user-images.githubusercontent.com/12821956/31346069-bf495c88-accc-11e7-9d3b-a1e644b3622c.png">
