### ISSUE TITLE
New logo isn't showing correctly on taskbar

### ISSUE THREAD

**Issue by sherbinyk** [Microsoft/vscode#35911]
This is the current logo 
![image](https://user-images.githubusercontent.com/936441/31341328-80615434-ad09-11e7-8cc7-34c0df7ec0ca.png)

It suppose to show this logo
![image](https://user-images.githubusercontent.com/936441/31341439-c229c93c-ad09-11e7-8bc9-5dc3ed9f5b30.png)

**Comment by Mlocik97-issues** [comment]
dupl #35663

**Comment by torn4dom4n** [comment]
This is icon from VSCode-win32-x64.zip
![image](https://user-images.githubusercontent.com/27698189/31342012-91c65cac-ad35-11e7-90b3-5afe14a6d945.png)

**Comment by sherbinyk** [comment]
@torn4dom4n is there a way to change it?

**Comment by torn4dom4n** [comment]
I think it is a **bug**. If I pin from Start or Taskbar:

![image](https://user-images.githubusercontent.com/27698189/31342947-6de269cc-ad38-11e7-8bf4-09a6b092a0eb.png)

**Comment by victorgarciaesgi** [comment]
I found the new icon very ugly

**Comment by sherbinyk** [comment]
@torn4dom4n it didn't work out with me. 😭

**Comment by sherbinyk** [comment]
@torn4dom4n btw, I have the same problem with Visual Studio Pro 2017. I even tried to solve it with the support, online, but that couldn't even help. My last resort was to re-install a clean windows version, guess what? Nothing changed. 🦀

**Comment by Mlocik97-issues** [comment]
#35746

**Comment by torn4dom4n** [comment]
@sherbinyk Did you try using VSCode-win32-*.zip? I can sure correct icon on the desktop when you create a shortcut. This is the link: https://code.visualstudio.com/docs/?dv=winzip. I am using  Visual Studio Pro 2015 so I can not help your problem with Visual Studio Pro 2017.

**Comment by torn4dom4n** [comment]
@sherbinyk You can try to [download Visual Studio Pro 2017](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio) again or try to create [an offline installation](https://docs.microsoft.com/vi-vn/visualstudio/install/create-an-offline-installation-of-visual-studio). This maybe helps you. I use Visual Studio Pro 2015 offline installation but can't download offline Visual Studio Pro 2017.

**Comment by sherbinyk** [comment]
@torn4dom4n so buggy! I have downloaded the zip folder. When I pin and unpin VScode it shows the right logo for a moment. Although, the shortcut as you mentioned shows the right logo as well. Regarding VS Code Pro 2017. I have downloaded it so many times but the same issue remains. But, I never did an offline installation yet tho.

**Comment by sherbinyk** [comment]
@torn4dom4n 
VS Code and VS Pro 2017 side by side.
![image](https://user-images.githubusercontent.com/936441/31347227-ecb50b96-ad1b-11e7-8f53-73af6a10aa0f.png)

After trying to pin VS Code
![image](https://user-images.githubusercontent.com/936441/31347245-003b26fa-ad1c-11e7-9cb4-2c5bbd5edd34.png)

**Comment by torn4dom4n** [comment]
Sorry, I can't help you with Visual Studio Pro 2017. This is Code Properties:

![image](https://user-images.githubusercontent.com/27698189/31350198-7c186bb4-ad50-11e7-8bed-4a8d74c8f330.png)

Only Code.exe isn't showing correct.

**Comment by camwheeler** [comment]
@sherbinyk 
I'm not positive this is actually a bug. If you inspect the icon files embedded in the exe you can see that the smallest version of this image is missing the little hook underneath, which makes sense as things start getting cramped at that small resolution.
I know if I toggle my taskbar buttons between small and normal it switches which image it uses -- because it uses one of the smaller resolution images for small taskbar buttons. You can check if this is the case by either toggling the "Use small taskbar buttons" setting, or by messing with the display scaling (or a combination of both.)

**Comment by sherbinyk** [comment]
@camwheeler you're definitely correct. It only occurs when I use the small taskbar buttons.

**Comment by chrisdias** [comment]
@camwheeler is correct - in the small taskbar we use an icon without the bounding box on the right/bottom.
