### ISSUE TITLE
Terminal Window doesn't always display properly

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode#35915]
macOS 10.12.6
VSCode Insiders 1.18.0
iTerm2
ZSH

My problem is that the integrated terminal doesn't always fire up at all. I have the line "terminal.external.osxExec": "iTerm.app", in my settings. When it does decide to work, it works really well, displaying the ZSH fonts really nicely, but it only works maybe 50% of the time.

For example, here I have just pressed Ctrl ` to try to activate the terminal - nothing...

![screen shot 2017-10-09 at 15 47 41](https://user-images.githubusercontent.com/260612/31343868-d9fc5cba-ad08-11e7-8529-24cbdba25c4a.png)

**Comment by KonaBlend** [comment]
Carlca, I had the exact same issue, and minimap not rendering issue. Both were solved for my system probably because I have an older OS version and/or graphics card with relatively low RAM. I am on OS El Capitan 10.11.6 with NVIDIA GeForce 8800 GT 512 MB.

Here's what solved my issue:

1. close vscode app
2. from command-line:

`open '/Applications/Visual Studio Code.app' --args --disable-gpu
`

**Comment by carlca** [comment]
It’s early days so far, and I’ve only tried it a few times, but, by golly, it seems to work!! Thank you so much!

Cheers,
Carl

**Comment by donmckenna** [comment]
@KonaBlend's solution worked for me as well.
However, is there a way to persist this command when opening from a dock / desktop icon?
A similar issue was stated here: https://github.com/Microsoft/vscode/issues/15211#issuecomment-330570631
Aliasing did not work for me. El Capitan 10.11.15, NVIDIA GeForce GT 120 512 MB
Thank you!

**Comment by KonaBlend** [comment]
don,

in the meantime the following is what I do for Finder/Dock launches; but it needs to be done every upgrade.

1. edit: `Visual Studio Code - Insiders.app/Contents/Info.plist`

```diff
diff --git a/Info.plist b/Info.plist
index 9e1a5a1..9496af8 100644
--- a/Info.plist
+++ b/Info.plist
@@ -7,7 +7,7 @@
     <key>CFBundleDisplayName</key>
     <string>Code - Insiders</string>
     <key>CFBundleExecutable</key>
-    <string>Electron</string>
+    <string>Electron.disable_gpu</string>
     <key>CFBundleIconFile</key>
     <string>Code - Insiders.icns</string>
     <key>CFBundleIdentifier</key>
```

2. create new script: `Visual Studio Code - Insiders.app/Contents/MacOS/Electron.disable_gpu`
(note: important, we drop extension to determine executable name so `Electron` must be basename and extension can be anything you want but has to match `Info.plist` entry)

```zsh
#!/bin/zsh
  
## executable is script without extension; exec with custom args
exec $0:r --disable-gpu
```

3. set executable permissions on script

```bash
chmod 755 'Visual Studio Code - Insiders.app/Contents/MacOS/Electron.disable_gpu'
```

4. launch and examine Electron command-line

```
pgrep -fl MacOS/Electron
```
