### ISSUE TITLE
Per window Zoom In/Out

### ISSUE THREAD

**Issue by socmag** [Microsoft/vscode#35913]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.4-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.2
vscode-docker|Pet|0.0.18
clojure|avl|0.9.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|1.0.9
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
csharp2ts|raf|0.0.19
vscode-scheme|sjh|0.3.1
visualclojure|sti|0.0.2
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1. Open two instances (Windows) of VSCode
2. In each instance, browse to some different code
3. In *one* instance use the Ctrl-+ or Ctrl-- (View:Zoom In or View:Zoom Out)
4. Notice that the Zoom level changes not only in the open window, but also in all the other VSCode instances

This is very annoying when you are using multiple monitors that have different resolutions, or are at different distances from the user.  One VSCode ends up with huge text, or one too small.

It would be very nice if I could control the Zoom level on a per VSCode instance.

Thanks!

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This is a tradeoff between storing this as setting or not. You can configure per-workspace zoom levels for each window. Closing "as designed".
