### ISSUE TITLE
array.includes error message

### ISSUE THREAD

**Issue by ChaltinPagan** [Microsoft/vscode#35918]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 3.18.0-14875-g438cb8ab27c6
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2

---

Steps to Reproduce:

var a = [1, 2, 3];
a.includes(2); // true 
a.includes(4); // false

console.log( a.includes(2))
console.log( a.includes(4))

Error message: a.includes is not a function

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This is an issue with your code, not with VSCode. You are running on a JavaScript engine that does not implement `Array.prototype.includes`. Please try a different engine or using a polyfill for this method
