### ISSUE TITLE
The terminal doesn't render properly

### ISSUE THREAD

**Issue by Sheshtawy** [Microsoft/vscode#35912]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
MochaSnippets|Ala|0.0.1
postgresql|JPT|0.0.2
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
vscode-javascript-snippet-pack|aka|0.1.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
color-info|bie|0.5.0
django|big|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
python-snippets|cst|0.0.5
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
jupyter|don|1.1.3
python|don|0.7.0
python-extension-pack|don|1.0.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
Python-autopep8|him|1.0.2
vscode-angular2-emmet|jak|2.0.3
search-node-modules|jas|1.2.0
docthis|joe|0.4.8
node-module-intellisense|lei|1.4.0
Go|luk|0.6.66
MagicPython|mag|1.0.12
vscode-todo-parser|min|1.9.1
github-issues-prs|ms-|0.6.0
chai-snippets|nwh|0.1.0
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.15.0
code-spell-checker|str|1.4.7
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
nodejs-extension-pack|wad|0.1.9
jinja|who|0.0.8
JavaScriptSnippets|xab|1.5.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Open the terminal section you'll find the line high is less than the font hight so the letters are cut out. 
![](https://i.imgur.com/vUzWOUf.png)

**Comment by carlca** [comment]
macOS 10.12.6
VSCode Insiders 1.18.0
iTerm2
ZSH

My problem is that the integrated terminal doesn't always fire up at all. I have the line `"terminal.external.osxExec": "iTerm.app",` in my settings. When it does decide to work, it works really well, displaying the ZSH fonts really nicely, but it only works maybe 50% of the time.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35644

@carlca `"terminal.external.osxExec": "iTerm.app"` is for launching the external terminal, not the integrated terminal? Could you create a separate issue with screenshots and more details? This issue is specific to Linux.
