### ISSUE TITLE
Powerline fonts Messed Up in integrated terminal!

### ISSUE THREAD

**Issue by imcodingideas** [Microsoft/vscode#35916]
- VSCode Version: 1.17.0 (1.17.0)
- OS Version: macOS 10.13

Yesterday; I updated VS Code then my integrated terminal messed up.

<img width="974" alt="screen shot 2017-10-09 at 7 45 50 am" src="https://user-images.githubusercontent.com/5374985/31343900-f2fb08b2-acc5-11e7-94c4-aebde573702d.png">

As you can see i'm using the powerline fonts; and there seems to be a lot of extra 'padding' there between everything which wasn't there before.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35649
