### ISSUE TITLE
Provide a command to restart VS Code

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3592]
I would have naturally expected there to be a "restart" command for Visual Studio Code, out of the box. Any chance of adding this in?

<img width="241" alt="screen shot 2016-03-01 at 9 34 43 am" src="https://cloud.githubusercontent.com/assets/466713/13433868/ffe65d78-df90-11e5-908c-9ceeb102fb08.png">

The current command name is "reload window," which is probably technically precise, but on the other hand, isn't really user-friendly. Could we add an alias for "restart Visual Studio Code" (or similar) for the "reload window" function?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Tyriar** [comment]
I'd find this really useful :+1:

**Comment by bbenoist** [comment]
@pcgeek86 Isn't `Reload Window` already doing what you expect?

**Comment by pcgeek86** [comment]
@bbenoist I don't know. Does `Reload Window` do the same thing as "restart" Visual Studio Code, after an update has been applied? If so, the inconsistency is causing some confusion. :)

**Comment by Tyriar** [comment]
@bbenoist that probably works for my use case (reloading themes, extensions, etc.), thanks.

**Comment by pcgeek86** [comment]
@Tyriar @bbenoist Seems like maybe we need an alias for that command. The notification for VS Code updates asks if you want to "restart" VS Code, so naturally I looked for a "restart" command. Can an alias be added, to close this out?

**Comment by Tyriar** [comment]
That's my experience too, restart and reload wording is not consistent so I didn't even bother looking for reload. If you want to make a new issue to that effect or rename this one that would be good.

**Comment by pcgeek86** [comment]
@Tyriar Done! :smile:

**Comment by camiller2** [comment]
+1

**Comment by bpasero** [comment]
I think we should not call it "Restart" because you would expect all windows you have opened to go down and restart. There currently is no restart command that would do the full thing.

**Comment by Tyriar** [comment]
@bpasero if that's the case then extensions should say "Reload" for consistency.

![image](https://cloud.githubusercontent.com/assets/2193314/14374940/c07085d6-fd10-11e5-86ef-77e163031552.png)

That's the main thing that was causing the confusion personally.

**Comment by bpasero** [comment]
I would actually argue to treat the fact that "Restart Now" does a window reload as a bug because if you have a second window open, you need to do the same action there too to benefit from the extension.

**Comment by pcgeek86** [comment]
@bpasero It just needs to be consistent. However, if there's a separate "*restart [program]*" command, then that should probably be listed in the Command Palette, as suggested by the original report.

**Comment by ArianeLu** [comment]
Some time may need manual reload, like modify .eslintrc

**Comment by bpasero** [comment]
Closing, I think this is fine as it is now. Newer electron versions provide a real restart command btw, that does the real thing. But I am not seeing a use case for that yet.

**Comment by Tyriar** [comment]
@bpasero reload keybindings is the biggest one for me.

**Comment by tcoopman** [comment]
I have an other use case for restart, on linux when I change my dpi settings (for example after switching monitors), I need to restart visual studio code to notice these changes.
Reloading does not work for this

In chrome there is `about://restart` which does the trick, something similar in visual studio code would be great.

**Comment by Tyriar** [comment]
@tcoopman with hot exit you can now relaunch really easily to do a full restart, just hit ctrl+q and relaunch.

**Comment by karlpothast** [comment]
On windows just create a .bat (batch file), create a shortcut to it on your desktop and a then put a keyboard short cut on it.  I used ctrl-shift-r.

This below will kill Visual Studio Code gracefully and then start up again cleanly.
-----------------------
@echo off    

taskkill /IM Code.exe
start /d "<Visual Studio Code Directory>" Code.exe
