### ISSUE TITLE
Compare Files

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#35929]
- VSCode Version: 1.18.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

When comparing file and switch to another tab and return to comparison tab, the scroll back to the beginning. This is very annoying. 

Is there any setting to stop this?

![scrollcompare](https://user-images.githubusercontent.com/19866231/31357192-1a593bbc-ad17-11e7-8a40-4a9a6b82136e.gif)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@bpasero Thanks for the reply, but I tried to find it, but I did not succeed. (I think it might be because of the language. 🤔 😊 😆 😁 😊  )
Can you tell me what the case is?

**Comment by bpasero** [comment]
@Tekbr I would appreciate if you could find it via the search as it is also time consuming for me as a developer. Anyway, the issue is https://github.com/Microsoft/vscode/issues/28956

**Comment by Tekbr** [comment]
@bpasero Thank you.
I was by the easiest and obvious. 😊   But thank you very much. 😄
