### ISSUE TITLE
Cursor automatically shifts to the end of the line

### ISSUE THREAD

**Issue by QadMohKuwait** [Microsoft/vscode#35922]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.start editing any file
2.

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Could you post the list of extensions you have installed? (`code --list-extensions`)
Does it reproduce when you disable all extensions? (`code --disable-extensions`)

**Comment by QadMohKuwait** [comment]
I removed the extensions (Git) and it resolved
