### ISSUE TITLE
Add new file button should expand a collapsed file explorer sash

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#35923]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Collapse file explorer
2. Hit add new file button

**Expected behavior**
File explorer section is expanded again and we enter into the standard new file flow

**Bug**
Explorer is not expanded and we get into a weird state where the new file input box is shown is the explorer but not active. This even allows for multiple input boxes to be created

![oct-09-2017 11-45-44](https://user-images.githubusercontent.com/12821956/31353491-a244259e-ace7-11e7-9526-5da1ac8866dc.gif)

**Comment by isidorn** [comment]
@sandy081 @joaomoreno I think this should be solved on the split view level in order to be a consistent experience across multiple views. Either:
* When a title split view actions is clicked and view should get expanded
* Do not show actions if the view is collapsed

I can aslo handle this specially in the explorer, but then I wil also have to do it for breakpoints, watch...

**Comment by sandy081** [comment]
@isidorn 

>>When a title split view actions is clicked the view should get expanded
Doing two things on a single action is not a good UX also might not be expected by users

>>Do not show actions if the view is collapsed
This can be thought of. But what if there is an action that can be invoked on a collapsed view?

**Comment by isidorn** [comment]
I am not aware of an action that can be invoked on a collapsed view.
If so then it feel like it should not belong to that title view.

As for the first thing, not sure I agree that it would be bad ux to do two things in a single action ( imho we do this all over the workbench)

**Comment by joaomoreno** [comment]
> When a title split view actions is clicked the view should get expanded

This is pretty rough imho. It would be behind an option of the Panel, at best.

> Do not show actions if the view is collapsed

If this works for you, just do that. 👍

**Comment by isidorn** [comment]
Did it with css, please review.

Also not a big fan that you are calling your split view pane `panels`. This creates some confusion with the bottom panel, but that's just life
