### ISSUE TITLE
Missing Menu Item "Check or Search for Updates" 

### ISSUE THREAD

**Issue by chessweb01** [Microsoft/vscode#35926]
I'm using VS Code 1.16.0 on Windows 7 and just noticed that the item "Check / Search for Updates" is missing in the Help menu.

**Comment by roblourens** [comment]
Can you share a screenshot?

**Comment by chessweb01** [comment]
sure
![vscode](https://user-images.githubusercontent.com/1660364/31355829-13d95086-ad3c-11e7-9eb5-6f2a88bb45a7.PNG)

**Comment by roblourens** [comment]
Did you install a private/unsigned build at some point? Can you just try reinstalling?

**Comment by chessweb01** [comment]
Well, I just installed 1.17 from the zip archive. Same result: no "Check / Search for Updates" item in Help menu.

**Comment by roblourens** [comment]
It will only show up for builds installed with the installer, not when running a .exe from a zip. Is that the case here?

**Comment by chessweb01** [comment]
That's it. Is there any particular reason that one cannot look for updates when running the zip version?

**Comment by roblourens** [comment]
On Windows it can only self-update itself when installed - I'm not sure of the technical reasons behind that. But I typically use that version when I want to run a specific build, not for normal daily use.
