### ISSUE TITLE
Snippet Enums should have key value pairs

### ISSUE THREAD

**Issue by shobhitg** [Microsoft/vscode#35924]
Hi,

I am referring to this snippet enum facility:
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice

Let me describe with my own example.
Lets say we would like to choose between 3 neat options: `None`, `Search`, `Test`. But what we want displayed in enum dropdown is actually somewhat different and not so neat stuff.

```
{
  None: '',
  Search: 'ggrep(option-1, log-bundle, searchTests)',
  Test: 'some really long and cryptic text snippet string'
}
```

The current enum snippets do not support that.

Neatness or ugliness aside, currently there is no way I could have a `None` or `EmptyText` kind of option.

My suggestion isn't perfect, but something really needs to be improved in enum snippet facilities.

**Comment by jrieken** [comment]
I am not seeing choice in your sample. Please extend your sample

**Comment by shobhitg** [comment]
@jrieken The choice options in my sample are `None`, `Search`, `Test`.

What I am suggesting is that vscode should treat those choice options more like a key:value parameters. That way we can achieve the following:
# Create an option for Empty string (i.e. None)
# Insert more complex strings on choosing any choice.

**Comment by jrieken** [comment]
Understood. It's tricky because we implement what's given by Textmate and we strive for being compatible. For richer experiences you can always use a completion item provider. That allows for a richer experience.

**Comment by shobhitg** [comment]
@jrieken Can you please give more pointers on what is `a completion item provider`?

**Comment by jrieken** [comment]
Yeah, take a look at this sample: https://github.com/Microsoft/vscode-extension-samples/tree/master/completions-sample

**Comment by jrieken** [comment]
Closing this as out-of-scope because we want to stay close to the original textmate-syntax. For more complex use-cases extensions should be used. Thanks and Happy Coding
