### ISSUE TITLE
Cursor remains in the beginning after pressing comments shortcut

### ISSUE THREAD

**Issue by shreyas-a** [Microsoft/vscode#35928]
- VSCode Version: 1.17.0
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Press `⌘ + /`
2. Notice that cursor is stuck at the beginning of the line, it should be at the end of the line.

**Comment by ajmichaels** [comment]
I also have been experiencing this issue since the new release.

**Comment by ryan-lynch** [comment]
A minor but quite irritating bug!

**Comment by trevren11** [comment]
Also on Windows

**Comment by alexandrudima** [comment]
Duplicate of #35673
