### ISSUE TITLE
Empty extension - ghost logging

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3593]
This is strange to me. I created an [extension](https://github.com/waderyan/vscode-babelrc) for adding json validation to babelrc files. I removed everything that was unnecessary including any .js file. 

When I debug my extension, the default console.log seems to run. 

![image](https://cloud.githubusercontent.com/assets/2449568/13434112/03e1941c-dfd5-11e5-8663-ae685302ca77.png)

See the log "Spell and Grammar checker active...". This is the same log from [spell and grammar check extension](https://github.com/Microsoft/vscode-spell-check/blob/master/extension.ts). 

I don't know if this is causing problems... but its strange behavior to me. Why is this happening?

**Comment by weinand** [comment]
@waderyan what is strange here? You are launching another instance of the extension host. It runs the same extensions that you have installed (e.g. the 'Spell and Grammar checker) plus your extension under development. So this looks quite normal to me.

CC @bpasero do you agree?

**Comment by bpasero** [comment]
Yes, console.log goes to the repl from the extension!

**Comment by waderyan** [comment]
@weinand I don't understand how I installed the Spell and Grammar checker extension. Shouldn't I only see the console.log from the extension I am currently debugging? Why do I see another installed extension?

**Comment by bpasero** [comment]
Actually we do not distinguish console.log from your extension or any other extension which is somewhat odd. Maybe we should not load any extension BUT the one you are debugging?

**Comment by weinand** [comment]
@waderyan you are really debugging the extension host and not only your extension. And the extension host has access to all extensions plus your additional extension.

**Comment by Hxs1990** [comment]
Just add extensions config in the product.json (under `buildout/resources/app/`).
`"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	},
	"extensionTips": {
		"ms-vscode.csharp": "{**/*.cs,**/project.json,**/global.json,**/*.csproj,**/*.sln,**/appsettings.json}",
		"ms-vscode.mono-debug": "{**/*.cs,**/*.csproj,**/*.sln}",
		"msjsdiag.debugger-for-chrome": "{**/*.ts,**/*.tsx**/*.js,**/*.jsx,**/*.es6,**/.babelrc}",
		"lukehoban.Go": "**/*.go",
		"ms-vscode.PowerShell": "{**/*.ps,**/*.ps1,**/*.ps.config,**/*.ps1.config}",
		"austin.code-gnu-global": "{**/*.c,**/*.cpp,**/*.h}",
		"Ionide.Ionide-fsharp": "{**/*.fsx,**/*.fsi,**/*.fs,**/*.ml,**/*.mli}",
		"dbaeumer.vscode-eslint": "{**/*.js,**/*.jsx,**/*.es6,**/.eslintrc.*,**/.eslintrc,**/.babelrc,**/jsconfig.json}",
		"dbaeumer.jshint": "{**/*.js,**/*.jsx,**/*.es6,**/.babelrc,**/jsconfig.json,**/.jshintrc,**/.jshintignore}",
		"eg2.tslint": "{**/*.ts,**/*.tsx,**/tslint.json,**/tsconfig.json}",
		"felixfbecker.php-debug": "{**/*.php,**/php.ini}",
		"ikappas.phpcs": "{**/*.php,**/php.ini}",
		"tht13.python": "{**/*.py}",
		"donjayamanne.python": "{**/*.py}",
		"magicstack.MagicPython": "{**/*.py}",
		"saviorisdead.RustyCode": "{**/*.rs,**/*.rslib}",
		"mitaki28.vscode-clang": "{**/*.cpp,**/*.cc,**/*.h}",
		"ms-vscode.cpptools": "{**/*.c,**/*.cpp,**/*.cc,**/.cxx,**/*.hh,**/*.hpp,**/*.hxx,**/*.h}",
		"ms-vscode.Theme-MarkdownKit": "{**/*.md}",
		"DavidAnson.vscode-markdownlint": "{**/*.md}",
		"PeterJausovec.vscode-docker": "{**/dockerfile,**/Dockerfile,**/docker-compose.yml,**/docker-compose.*.yml}",
		"EditorConfig.EditorConfig": "{**/.editorconfig}",
		"HookyQR.beautify": "{**/.jsbeautifyrc,**/*.js,**/*.jsx,**/*.es6,**/.eslintrc.*,**/.babelrc,**/jsconfig.json}",
		"donjayamanne.githistory": "{**/.gitignore, **/.git}",
		"felipecaputo.git-project-manager": "{**/.gitignore, **/.git}",
		"waderyan.gitblame": "{**/.gitignore, **/.git}",
		"codezombiech.gitignore": "{**/.gitignore, **/.git}",
		"rebornix.Ruby": "{**/*.rb,**/*.erb,**/*.reek,**/.fasterer.yml,**/ruby-lint.yml,**/.rubocop.yml}",
		"lonefy.vscode-JS-CSS-HTML-formatter": "{**/.jsbeautifyrc,**/*.js,**/*.jsx,**/*.es6,**/.eslintrc.*,**/.babelrc,**/jsconfig.json}",
		"DotJoshJohnson.xml": "{**/*.xml}",
		"shinnn.stylelint": "{**/.stylelintrc,**/stylelint.config.js}",
		"eg2.vscode-npm-script": "{**/package.json}",
		"fknop.vscode-npm": "{**/package.json}",
		"donjayamanne.bower": "{**/.bowerrc}",
		"ms-mssql.mssql": "{**/*.sql}",
		"ms-vscode.jscs": "{**/.jscsrc}",
		"waderyan.babelrc": "{**/.babelrc}",
		"ms-vscode.sublime-keybindings": "{**/.sublime-project, **/.sublime-workspace}",
		"k--kato.intellij-idea-keybindings": "{**/.idea}",
		"dzannotti.vscode-babel-coloring": "{**/.babelrc}",
		"christian-kohler.npm-intellisense": "{**/package.json}"
	},
	"extensionImportantTips": {
		"ms-vscode.csharp": {
			"name": "C#",
			"pattern": "{**/*.cs,**/project.json,**/global.json,**/*.csproj,**/*.sln}"
		},
		"lukehoban.Go": {
			"name": "Go",
			"pattern": "**/*.go"
		},
		"donjayamanne.python": {
			"name": "Python",
			"pattern": "{**/*.py}"
		},
		"redhat.java": {
			"name": "Language Support for Java(TM) by Red Hat",
			"pattern": "{**/*.java}"
		},
		"ms-vscode.PowerShell": {
			"name": "PowerShell",
			"pattern": "{**/*.ps,**/*.ps1}"
		},
		"ms-vscode.cpptools": {
			"name": "C/C++",
			"pattern": "{**/*.c,**/*.cpp,**/*.cc,**/.cxx,**/*.hh,**/*.hpp,**/*.hxx,**/*.h}"
		},
		"PeterJausovec.vscode-docker": {
			"name": "Docker",
			"pattern": "{**/dockerfile,**/Dockerfile,**/docker-compose.yml,**/docker-compose.*.yml}"
		},
		"ms-mssql.mssql": {
			"name": "SQL",
			"pattern": "{**/*.sql}"
		}
	},
	"keymapExtensionTips": [
		"vscodevim.vim",
		"ms-vscode.sublime-keybindings",
		"ms-vscode.atom-keybindings",
		"ms-vscode.vs-keybindings",
		"k--kato.intellij-idea-keybindings",
		"hiro-sun.vscode-emacs",
		"alphabotsec.vscode-eclipse-keybindings",
		"alefragnani.delphi-keybindings"
	],
	"extensionKeywords": {
		"md": [
			"Markdown"
		],
		"js": [
			"JavaScript"
		],
		"jsx": [
			"JavaScript"
		],
		"es6": [
			"JavaScript"
		],
		"html": [
			"Html"
		],
		"ts": [
			"TypeScript"
		],
		"tsx": [
			"TypeScript"
		],
		"css": [
			"CSS"
		],
		"scss": [
			"SASS"
		],
		"txt": [
			"Text"
		],
		"php": [
			"PHP"
		],
		"php3": [
			"PHP"
		],
		"php4": [
			"PHP"
		],
		"ph3": [
			"PHP"
		],
		"ph4": [
			"PHP"
		],
		"xml": [
			"XML"
		],
		"py": [
			"Python"
		],
		"pyc": [
			"Python"
		],
		"pyd": [
			"Python"
		],
		"pyo": [
			"Python"
		],
		"pyw": [
			"Python"
		],
		"pyz": [
			"Python"
		],
		"java": [
			"Java"
		],
		"class": [
			"Java"
		],
		"jar": [
			"Java"
		],
		"c": [
			"c",
			"objective c",
			"objective-c"
		],
		"m": [
			"objective c",
			"objective-c"
		],
		"mm": [
			"objective c",
			"objective-c"
		],
		"cpp": [
			"cpp",
			"c plus plus",
			"c",
			"c++"
		],
		"cc": [
			"cpp",
			"c plus plus",
			"c",
			"c++"
		],
		"cxx": [
			"cpp",
			"c plus plus",
			"c++"
		],
		"hh": [
			"cpp",
			"c plus plus",
			"c++"
		],
		"hpp": [
			"cpp",
			"c++"
		],
		"h": [
			"cpp",
			"c plus plus",
			"c++",
			"c",
			"objective c",
			"objective-c"
		],
		"sql": [
			"sql"
		],
		"sh": [
			"bash"
		],
		"bash": [
			"bash"
		],
		"zsh": [
			"bash",
			"zshell"
		],
		"cs": [
			"c#",
			"csharp"
		],
		"csproj": [
			"c#",
			"csharp"
		],
		"sln": [
			"c#",
			"csharp"
		],
		"go": [
			"go"
		],
		"sty": [
			"latex"
		],
		"tex": [
			"latex"
		],
		"ps": [
			"powershell"
		],
		"ps1": [
			"powershell"
		],
		"rs": [
			"rust"
		],
		"rslib": [
			"rust"
		],
		"hs": [
			"haskell"
		],
		"lhs": [
			"haskell"
		],
		"scm": [
			"scheme"
		],
		"ss": [
			"scheme"
		],
		"clj": [
			"clojure"
		],
		"cljs": [
			"clojure"
		],
		"cljc": [
			"clojure"
		],
		"edn": [
			"clojure"
		],
		"erl": [
			"erlang"
		],
		"hrl": [
			"erlang"
		],
		"scala": [
			"scala"
		],
		"sc": [
			"scala"
		],
		"pl": [
			"perl"
		],
		"pm": [
			"perl"
		],
		"t": [
			"perl"
		],
		"pod": [
			"perl"
		],
		"groovy": [
			"groovy"
		],
		"swift": [
			"swift"
		],
		"rb": [
			"ruby"
		],
		"rbw": [
			"ruby"
		],
		"jl": [
			"julia"
		],
		"f": [
			"fortran"
		],
		"for": [
			"fortran"
		],
		"f90": [
			"fortran"
		],
		"f95": [
			"fortran"
		],
		"coffee": [
			"CoffeeScript"
		],
		"litcoffee": [
			"CoffeeScript"
		],
		"yaml": [
			"yaml"
		],
		"yml": [
			"yaml"
		],
		"dart": [
			"dart"
		],
		"json": [
			"json"
		]
	},`
