### ISSUE TITLE
Unit Testing Multiroot workspace for Extension Authors

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#35936]
Currently the test script passes the following arguments to the executable:
```javascript
    var args = [
        testsWorkspace,
        '--extensionDevelopmentPath=' + extensionsFolder,
        '--extensionTestsPath=' + testsFolder
    ];
```

How do I configure the tests such that it opens up a multi-root workspace for the unit tests?

**Comment by egamma** [comment]
@DonJayamanne great to see that you are investigating into multi root folder support. We want to support the migration as good as we can. From the dev team @chrmarti from the Redmond team is also available to support the migration of your extension.

**Comment by bpasero** [comment]
@DonJayamanne I think you could just pass the path to a pre-crafted workspace file to the test to let your tests run in a workspace environment. You can also change this file programmatically via node FS APIs, however you will need to account for the file event travelling through to the workbench.

**Comment by DonJayamanne** [comment]
Thanks, got it working.
