### ISSUE TITLE
Editor hangs splitting views by dragging

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#35939]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
EditorConfig|Edi|0.10.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.9
cpptools|ms-|0.13.1
autoimport|ste|1.2.2
vim|vsc|0.10.1
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. open 2 file so you have 2 tabbed views
2. drag one of the tabs to the side to split views

Result editor hangs

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@rajinder-yadav can you share a screencast?

**Comment by rajinder-yadav** [comment]
This is working again in v1.17.0, closing!
