### ISSUE TITLE
"Clear Recently Opened" should also clear editor quick pick history

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#35935]
- VSCode Version: 1.17.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file to get it into quick open's "recently opened" suggestions
2. Close the file
3. Press CTRL+P; start typing the filename and it should show up with the label "recently opened"
4. Bring up the command bar and select "clear recently opened"
5. The file is gone from the file menu's recently opened files, but not from the quick open bar

![vscode-clear-recently-opened](https://user-images.githubusercontent.com/298883/31361184-695a1014-ad95-11e7-946a-3045e5cdbccc.gif)

I understand that the command bar's recently opened suggestions are a separate feature to the recent files list in the file menu, but I'd say that:

1. They may be separate in terms of implementation, but they are probably the same from the user's perspective. Clearing one should probably clear the other.
2. Even if they stay separate, the nomenclature should be changed - the hint text displayed to the right of the file in quick open is "recently opened"; providing a "clear recently opened" command creates confusion, given that the latter has no effect on the former.

**Comment by jemhuntr** [comment]
Would love this feature! This always bites me when I rename a folder and all the `Ctrl+P` results fire a `File Not Found` error.

**Comment by bpasero** [comment]
It is easily possible to clear the editor history of `Cmp+P`, just use this:

![image](https://user-images.githubusercontent.com/900690/38403533-6d1a0190-3964-11e8-9a6d-deccb634c7f0.png)

**Comment by bpasero** [comment]
Picking "Clear Recently Opened" will now also remove "recently used" from the picker.

**Comment by isidorn** [comment]
@bpasero I verified that the Clear Editor History and remove from history properly remove editors from the quick pick history.
However clicking on Clear Recently Opened in the menu does not modify the quick open editor history. Should I reopen?

**Comment by bpasero** [comment]
@isidorn good catch

**Comment by schoening** [comment]
Looks like "Clear Editor History" first becomes active on a reload? Perhaps something worth changing, that or force reload the editor. Unless I am wrong and it's only my version that does not show the changes instantly :)
