### ISSUE TITLE
Examples for Editor Theme Customization Properties

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#35932]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-npm-script|eg2|0.2.1
mssql|ms-|1.2.0
debugger-for-chrome|msj|3.3.1
code-settings-sync|Sha|2.8.3
guides|spy|0.8.4

(1 theme extensions excluded)

Hi There,

I've been writing (and releasing) a color theme. I've customized almost all colors, but was hoping you could provide a visual example for two properties whose impact I cannot figure out:

1. `editor.findRangeHighlightBackground`
2. `editorOverviewRuler.rangeHighlightForeground`

I've read the [docs](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors) and tested a few different hex values, but their impact is still unclear.

Thanks much!

Sidebar - more screenshots would be great to have on that docs page. The naming conventions are not always obvious/clear - even with the descriptions. Perhaps tooltips...

**Comment by aeschli** [comment]
`editor.findRangeHighlightBackground`: select a range, open the find dialog, click on 'find in selection' 
![image](https://user-images.githubusercontent.com/6461412/31374222-61170de6-ad9d-11e7-86c8-ea66261437a3.png)
`editorOverviewRuler.rangeHighlightForeground`: open 'document symbols (Ctrl + Shift +O), select an entry
![image](https://user-images.githubusercontent.com/6461412/31374542-b9bf85f8-ad9e-11e7-9ab8-2df253c863a4.png)
