### ISSUE TITLE
Visual Studio Code pins CPU when invalid CSS entered

### ISSUE THREAD

**Issue by jonathanapp** [Microsoft/vscode#35948]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18

---

Steps to Reproduce:

I believe this happened twice today (I used Code for about 12 hours.)
Entire OS grinds to a halt. Mouse cursor still moves, nothing receives clicks. Fan begins to ramp up like an aircraft taking off. Had just entered wavy-green-underlined code in a div element. Forced to do hard restart of machine.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
Given the above steps this is difficult to analyze.  The next time it happens can you please try to find out which process is causing this.

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

Once you have the information please update this issue with it. Thanks!

**Comment by egamma** [comment]
@jonathanapp can you share the CSS file and describe what the invalid CSS was?

**Comment by jonathanapp** [comment]
When it freezes, the UI and entire OS become unresponsive (even the clock stops ticking).
I'm going to try to reproduce with a simple example...

**Comment by jonathanapp** [comment]
This might be of use:
[Code Helper_2017-10-09-205304.crash.txt](https://github.com/Microsoft/vscode/files/1451676/Code.Helper_2017-10-09-205304.crash.txt)

**Comment by egamma** [comment]
@jonathanapp thanks for the additional info. So did it happen to you with 1.18 again?

Adding @bpasero for his insights.

**Comment by jonathanapp** [comment]
After experiencing this (almost) every day and doing more research, I'm now confident this is a issue introduced in macOS High Sierra issue that can be triggered by _any_ UI doing decent amount of rendering. I was seeing it often with Code simply because Code was my top-level app.

For those who are curious: there are system reports named "WindowServer_YYYY_MM_DD_[...].userspace_watchdog_timeout.spin" for every instance the OS grinds to a halt and becomes unresponsive. Others have experienced similar issues. I've tracked down a 3rd party display kext (DisplayLink) and removed it; I believe this (or another) extension is now incompatible with High Sierra.

Sorry for any confusion, this is the most vexing issue I've experienced in a couple years at least!

**Comment by bpasero** [comment]
Top stack from Electron seems to be this:

```
gl::GLFence::Create() (in Electron Framework) (gl_fence.cc:61)
gpu::ImageTransportSurfaceOverlayMac::SwapBuffersInternal(gfx::Rect const&) (in Electron Framework) (image_transport_surface_overlay_mac.mm:221)
gpu::ImageTransportSurfaceOverlayMac::GetFormat() (in Electron Framework) (image_transport_surface_overlay_mac.mm:307)
gpu::gles2::GLES2DecoderImpl::HandlePostSubBufferCHROMIUM(unsigned int, void const volatile*) (in Electron Framework) (gles2_cmd_decoder.cc:11832)
gpu::error::Error gpu::gles2::GLES2DecoderImpl::DoCommandsImpl<false>(unsigned int, void const volatile*, int, int*) (in Electron Framework) (gles2_cmd_decoder.cc:5278)
```
