### ISSUE TITLE
Terminal: Chinese words print error.

### ISSUE THREAD

**Issue by yvesyao** [Microsoft/vscode#35949]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Type some chinese words in terminal.
2. Press enter or just scroll.
![terminal](https://user-images.githubusercontent.com/7723729/31367458-202bb544-ad3d-11e7-8c61-f76b753a7df0.gif)

![image](https://user-images.githubusercontent.com/7723729/31367384-ad519b4c-ad3c-11e7-88a6-7874c9c460a1.png)

Reproduces without extensions: Yes

**Comment by zjjott** [comment]
+1

**Comment by Deguang** [comment]
same issue
![image](https://user-images.githubusercontent.com/11596327/31371902-05167d54-ad59-11e7-9f19-e00c3089bfeb.png)

**Comment by yvesyao** [comment]
Same issue as mentioned in: #35946 #35947

**Comment by elppac** [comment]
+1

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
