### ISSUE TITLE
terminal goes wrong

### ISSUE THREAD

**Issue by tongxian** [Microsoft/vscode#35946]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
better-comments|aar|0.1.3
include-autocomplete|ajs|0.0.4
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
insertnumbers|Asu|0.9.1
All-Autocomplete|Ati|0.0.10
GBKtoUTF8|buk|0.0.2
vscode-astyle|chi|0.7.1
gitignore|cod|0.5.0
arm|dan|0.1.2
githistory|don|0.2.3
gitlens|eam|5.5.0
windows-explorer-context-menu|ele|1.0.2
vsc-material-theme|Equ|1.0.4
code-runner|for|0.7.2
matlab|Gim|0.7.1
mdmath|goe|2.0.7
CppSnippets|har|0.0.12
latex-workshop|Jam|3.5.5
hex-fmt|ker|1.0.0
auto-comment-blocks|kev|1.0.1
cmake-tools-helper|mad|0.1.1
gitignore|mic|1.0.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
sublime-keybindings|ms-|2.9.1
incrementor|nms|0.1.0
vscode-icons|rob|7.15.0
partial-diff|ryu|0.3.3
todotasks|san|0.5.0
code-settings-sync|Sha|2.8.3
markdown-preview-enhanced|shd|0.2.9
vscode-autohotkey|sle|0.2.1
vscode-hexdump|sle|1.4.0
guides|spy|0.8.4
cmake|twx|0.0.17
cmake-tools|vec|0.10.2
gitflow|vec|1.1.1
highlight-matching-tag|vin|0.4.4
gitblame|wad|2.2.0
vscode-jumpy|wma|0.3.1
vscode-open-in-github|ziy|1.2.8

(2 theme extensions excluded)

---

Steps to Reproduce:

Something is wrong with chinese encoding in terminal after updating the vs code .
![image](https://user-images.githubusercontent.com/20140785/31367202-41491206-ada8-11e7-8188-112ff7e2e2b9.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
