### ISSUE TITLE
terminal‘s bug

### ISSUE THREAD

**Issue by shinrabansyou** [Microsoft/vscode#35947]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-clock|Com|0.0.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.5.0
tslint|eg2|1.0.9
vsc-figlet|fer|0.0.8
html-tag-wrapper|hwe|0.2.3
git-tree-compare|let|1.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-filesize|mkx|1.0.0
vscode-autoprefixer|mrm|2.1.2
sublime-keybindings|ms-|2.9.1
java|red|0.11.0
background|sha|1.1.15
open-in-browser|tec|1.1.0
vscode-preview-server|yui|0.7.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by shinrabansyou** [comment]
![_9ipfvo0 u ixg 6vhhzg_r](https://user-images.githubusercontent.com/24823615/31367378-952fff82-ada9-11e7-8024-c298b5aa1aaa.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
