### ISSUE TITLE
VSCode new icon Windows 10 not shown correctly

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode#35942]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-eslint|dba|1.3.2
beautify|Hoo|1.1.1
vscode-colorize|kam|0.6.7
theme-monokai-pro-vscode|mon|1.1.2
material-icon-theme|PKi|2.2.2

(7 theme extensions excluded)

---

Steps to Reproduce:

1. Right Click on VSCode related files.
---

I'm using Windows 10, I really like the new icons, but I'm having troubles with the icon when I right click the icon on the taskbar for example:

![image](https://user-images.githubusercontent.com/29575744/31362437-7963af16-ad26-11e7-9aec-bb03ef296b27.png)

But with the insiders version it doesn't happen.
![image](https://user-images.githubusercontent.com/29575744/31362407-5078e4d6-ad26-11e7-9f35-ac2816ead8fb.png)

Another example is when I right click to a file, to be opened in VSCode:
![image](https://user-images.githubusercontent.com/29575744/31363628-a65d0812-ad2d-11e7-9bca-9d1c98ce1ae8.png)
The Stable version icon is not shown correctly.

But when it comes to file icons (when they're opened by the editor by default), the stable version looks better:
![image](https://user-images.githubusercontent.com/29575744/31363693-208dbbae-ad2e-11e7-88ae-12ff07c12d54.png)
![image](https://user-images.githubusercontent.com/29575744/31364875-b625fdaa-ad35-11e7-873b-53d24e40574b.png)
 But then, this happens again...
![image](https://user-images.githubusercontent.com/29575744/31364958-3c82a2d6-ad36-11e7-9208-6e21fc338cbc.png)
The Insiders icon looks better.
![image](https://user-images.githubusercontent.com/29575744/31364982-710b68b2-ad36-11e7-94f4-566f6574c7eb.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/33685
