### ISSUE TITLE
there are a bug in Chinese OS. when you use inner terminal in vs under ubuntu-os you'll find that there are many unexpected char. for example, after I execute "git status && git reset --hard HEAD^ && git pull ", some  incomplete Chinese-char left at  framebuffer and displaying in terminal

### ISSUE THREAD

**Issue by singh-zhao** [Microsoft/vscode#35944]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|don|0.7.0
code-python-isort|fre|0.0.3
auto-comment-blocks|kev|1.0.1
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
reloaded-cpp|rel|0.1.6
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
