### ISSUE TITLE
Changing the value"editor.fontWeight": "normal" to anything below 400 doesn't make a difference. 

### ISSUE THREAD

**Issue by makepizza** [Microsoft/vscode#35941]
- VSCode Version: 1.17.0 (same was with previous version)
- MacOS Version: 10.13.1 (same was with previous version 10.12.6)

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
This is the expected behaviour. pls see https://www.w3schools.com/cssref/pr_font_weight.asp 
The value ranges from 100-900. 400 is the same as normal, and 700 is the same as bold
