### ISSUE TITLE
Editor indentation incorrect around tabbed function parameters

### ISSUE THREAD

**Issue by aahaselgrove** [Microsoft/vscode#35952]
Indentation does not seem to work correctly for multi-line function signatures. It is based off the indentation on the previous line, rather than the appropriate scope (which in this case, is the indentation level of the first line of the function).

Outcome after typing the following, and pressing enter between the braces. '|' represents the cursor position.

Expected:
```
void test(int first, int second,
        int third) {
    |
}

void test2(int first, int second,
           int third) {
    |
}
```

Actual:
```
void test(int first, int second,
        int third) {
        |
    }

void test2(int first, int second,
           int third) {
               |
           }
```

**Comment by Dimpl** [comment]
This might be related to https://github.com/Microsoft/vscode/issues/35709

**Comment by sean-mcmanus** [comment]
This repros without the cpptools extension installed, but it looks like our extension may be responsible for handling the C++ indentation rules. We're tracking this issue with https://github.com/Microsoft/vscode-cpptools/issues/883 .

**Comment by rebornix** [comment]
This issue shares the same root cause as #30859 , let's track it there.
