### ISSUE TITLE
`fuzzy.exclude` - a setting to exclude results from the fuzzy file picker

### ISSUE THREAD

**Issue by ubershmekel** [Microsoft/vscode#35950]
`search.exclude` excludes from `Find in Files`.
`files.exclude` excludes from the `workspace explorer` AND from the `fuzzy file picker`.

My scenario is I have a folder with generated code (JS) and I sometimes want to be able to open it from the explorer but I never want to open it from the fuzzy file picker (⌘-P). I just lost a lot of time for editing generated code that I accidentally opened through the fuzzy file picker.

So I'm suggesting a different setting to separate control from what's excluded in the explorer vs fuzzy file picker - `picker.exclude` or `fuzzy.exclude`. There might be some consideration required with regards to how alternate pickers handle this setting.

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|1.1.15
vscode-docker|Pet|0.0.18
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.4.1
LogFileHighlighter|emi|1.2.0
flow-for-vscode|flo|0.7.2
vue-snippets|hol|0.1.5
terraform|mau|0.0.18
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
vetur|oct|0.9.10
java|red|0.11.0
vscode-sort-json|ric|1.9.2
bash-debug|rog|0.1.0
vscode-hexdump|sle|1.4.0
gitblame|wad|2.2.0

**Comment by bpasero** [comment]
I am not a big fan of introducing yet another setting that users have to learn.

@ubershmekel `search.exclude` does exclude from the picker as well.

**Comment by ubershmekel** [comment]
I think my problem might be something else. If I ever open a generated `js` file it will forever be in the fuzzy file matcher (command-p). I see the file goes away after modifying the `search.exclude` settings, but otherwise it's there forever if it was ever opened. Is that intended?

**Comment by bpasero** [comment]
@ubershmekel there is a command to remove an entry from this list:

![image](https://user-images.githubusercontent.com/900690/33112791-445861e4-cf55-11e7-8c05-00b337e96931.png)
