### ISSUE TITLE
Lot of problems in last versions

### ISSUE THREAD

**Issue by b-mi** [Microsoft/vscode#35957]
- vscode destroy code after rename properties
- vscode is unable to identify file changes, need to restart vscode after change
- false syntax errors - need restart vscode after  change
- vscode is catastrophic and unusable now
- I did not install any new extensions
- you identify these problem and start to test your VSCode before publishing

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-angular2-files|ale|1.3.10
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.9
vscode-npm-script|eg2|0.2.1
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
Angular2|joh|2.7.0
Angular-BeastCode|Mik|5.0.6
debugger-for-chrome|msj|3.3.1
git-add-remote|sam|0.0.2
gitblame|wad|2.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Please read: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions Thanks!

**Comment by b-mi** [comment]
joamoreno - you have 5000+ opened issues. I don't have so much time to create another 5000+ + 1 issue - and create another useless issue. But you should not fire issue so quickly.
