### ISSUE TITLE
No vendor-prefixed with Emmet 2

### ISSUE THREAD

**Issue by equiman** [Microsoft/vscode#35951]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
xml|Dot|1.9.2
code-settings-sync|Sha|2.8.3
sonarlint-vscode|Son|1.1.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
markdown-preview-github-styles|bie|0.0.4
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
jquerysnippets|don|0.0.1
tslint|eg2|1.0.9
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
HTMLHint|mka|0.4.0
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
indent-rainbow|ode|0.7.2
tsimporter|pmn|1.2.14
java|red|0.11.0
vscode-open|san|0.1.0
stylelint|shi|0.29.1
code-spell-checker|str|1.4.7
code-spell-checker-spanish|str|1.0.1
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Create new CSS file
2. Try to add -bdrd with vendor-prefixed as mention in emmet documentation adding a hyphen before. But not show any suggestion or auto-complation list. 

Expected result:
```css
-webkit-border-radius: ;
-moz-border-radius: ;
border-radius: ;
```

Emmet Documentation:
https://docs.emmet.io/css-abbreviations/vendor-prefixes/

I'm not see in his documentation if there is a way or option to enable this behaviour:
https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
@equiman You are right, expanding the abbreviations so that all vendor prefixes are included is not supported in Emmet 2.0

Have you used the `Emmet: Reflect CSS Value` command? https://docs.emmet.io/actions/reflect-css-value/

We could just overload that command to add missing vendor prefixes or have a new command to do the same.

**Comment by equiman** [comment]
I'm not using it, but I think is better add it to a new command.

**Comment by ramya-rao-a** [comment]
Note to verifier:

The vendor prefixes should be attached as documented in https://docs.emmet.io/css-abbreviations/vendor-prefixes/ when using the `Emmet: Expand Abbreviation` command.
