### ISSUE TITLE
[loc]Request to add Tamil ta-IN language to VS Code

### ISSUE THREAD

**Issue by prakashslm** [Microsoft/vscode#35953]
I like to submit a new request for the new language on all vscode-* transifex projects.
I am willing to translate to Tamil (India).

**Comment by Jeyanthinath** [comment]
I vote( transifex username: jeyanthinath )

**Comment by prasphy** [comment]
+1

**Comment by Jeyanthinath** [comment]
@prasphy Please do update your transifex username ,to get yourself as approved vote

**Comment by danyeh** [comment]
@prakashslm , please vote with your Transifex account link in issue  #https://github.com/Microsoft/vscode/issues/31974.
Please also review Adding language criteria is here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.
I am closing this one.

**Comment by solomonsunder** [comment]
@Jeyanthinath Can you vote in issue #31974? Request for Tamil is already open over there.
