### ISSUE TITLE
[mac] Duplicated character is typed when changing same key sequence during shifting Eng -> Korean 

### ISSUE THREAD

**Issue by charlie-chang** [Microsoft/vscode#35959]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
vscode-npm-source|dku|1.0.0
githistory|don|0.2.3
python|don|0.7.0
vscode-npm-script|eg2|0.2.1
vscode-auto-open-markdown-preview|hnw|0.0.4
Sbt|itr|0.1.7
Scala|itr|0.1.7
ScalaSnippets|itr|0.1.7
search-node-modules|jas|1.2.0
Go|luk|0.6.66
csharp|ms-|1.12.1
erlang|pgo|0.1.1
java|red|0.11.0
RustyCode|sav|0.19.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
erlang-otp|yuc|0.2.4
markdown-pdf|yza|0.1.7

(3 theme extensions excluded)

---

Steps to Reproduce:

1. in English keyboard type 'd', then change into Korean and type 'df' which is (아) 
2. expected is 'd아'  but you can see 'dㅇ아'

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@charlie-chang Can you please give more detailed steps regarding how to reproduce. 

When I try to reproduce and use "Korean - 2-Set Korean" on OSX I get `ㅇㄹ ` produced when typing <kbd>d</kbd>  <kbd>f</kbd>.

Here is an example of a page with very precise steps for reproducing such kind of issues: https://github.com/Microsoft/vscode/wiki/IME-Test

**Comment by charlie-chang** [comment]
Currently I have updated vscode to 1.18.0 and I think the duplicated typing problem is solved.
