### ISSUE TITLE
Create rpm package

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3595]
Related #1056

**Comment by 1dot75cm** [comment]
very nice :+1:

**Comment by rebornix** [comment]
@Tyriar does it mean we still have no support for RHEL 6?

**Comment by Tyriar** [comment]
@rebornix yes < RHEL7 isn't supported, due to issues with GLIBC and GLIBCXX. It might be possible to build it on a RHEL6 box, I was having a bit of difficulty though.

**Comment by rebornix** [comment]
@Tyriar got it. I'll have a try to see whether it can be solved as there are companies/users of my ruby debugger plugin asking if we can have RHEL6 support.

**Comment by Tyriar** [comment]
@rebornix if you have any luck, post it on https://github.com/Microsoft/vscode/issues/1056 or [https://github.com/Microsoft/vscode/issues/3603](https://github.com/Microsoft/vscode/issues/3603). Also read these issues if you're going to give it a shot as it contains a few of my notes.
