### ISSUE TITLE
Font modified to PingFang SC, the console font becomes ugly!

### ISSUE THREAD

**Issue by phm622848** [Microsoft/vscode#35968]
[-]([url](url)) VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
vsc-material-theme|Equ|1.0.4
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
path-autocomplete|ion|1.6.1
ayu|tea|0.8.0

(5 theme extensions excluded)

---

Steps to Reproduce:
<img width="1387" alt="45" src="https://user-images.githubusercontent.com/18509054/31374552-15474388-ad64-11e7-938b-58a8b9fa0da5.png">

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681

Please use a monospace font in the meantime.
