### ISSUE TITLE
copy paste doesn't work in the folder explorer

### ISSUE THREAD

**Issue by genfa** [Microsoft/vscode#35962]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|0.6.0
statusbar-commands|anw|0.1.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
status-bar-tasks|Gua|0.2.1
crane|Hvy|0.3.8
mssql|ms-|1.2.0
omnipascal|Wos|0.15.0

---

Steps to Reproduce:

1. open a folder
2. ctrl-c on a fille in the file explorer
3. ctrl-v of this file in the file explorer
4. an error message appeared with 'a system error occured (unknown: unknown error, mkdir '\\server\folder\...')

![snip_20171010084752](https://user-images.githubusercontent.com/4083412/31372827-e62702d0-ad97-11e7-9325-e8c5b90de089.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of #35743

**Comment by genfa** [comment]
Didn't find this, thanks closing the issue
