### ISSUE TITLE
Import hints not working when using export default after class definition

### ISSUE THREAD

**Issue by methyl** [Microsoft/vscode#35966]
- VSCode Version: 1.17.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Open a JS project with `jsconfig.json` having checkJs: true in compilerOptions
2. Create a `test.js` with following content:
```js
class Test {}
export default Test
```
3. Create a `test2.js` with following content:
```js
class Test2 extends Test {}
```

Actual behavior:
- No lightbulb with hint to `import Test from './test` appear.

Correct behavior
- Lightbulb with hint to `import Test from './test` appear, just like when `test.js` have `export default` inlined:
```
export default class Test {}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19115
