### ISSUE TITLE
Scroll wheel click doesn't close working files

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#3596]
Upon clicking open files using the scroll wheel, instead of closing, a scroll symbol appears. 

This is the expected behaviour in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/1297882/13435641/900f3f56-dfdb-11e5-80bc-a83fc1a2d7f8.gif)
 
This is the resulting behaviour in VSCode:
![working_files](https://cloud.githubusercontent.com/assets/1297882/13435699/d718cc96-dfdb-11e5-888c-9322a309da81.gif)

This works in VSCode on OS X.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3574
