### ISSUE TITLE
Terminals run hidden when reload window or close Visual Code.

### ISSUE THREAD

**Issue by NhanNguyenPropolife** [Microsoft/vscode#35963]
- VSCode Version: 1.17.0
- OS Version: OSX 10.9.5

Steps to Reproduce:

1. Run task(s)
2. Reload the window/close window.
3. All terminal disappears. But the tasks still running

Reproduces without extensions: Yes

When reload windows, I think we should keep all running terminals or ask to close them.
When close Visual Code, we should ask users if they want to close all them or not.

Sorry for my bad English.

**Comment by Tyriar** [comment]
@NhanNguyenPropolife what is the task you're using that causes this?

**Comment by NhanNguyenPropolife** [comment]
When I runs these tasks - Start Redis-server, MongoDB server, NGINX, Gunt
![image](https://user-images.githubusercontent.com/32286970/31417560-74cb6e00-ae5a-11e7-997a-deeed41460de.png)
Then I reload the window to disable/enable an extension:
![image](https://user-images.githubusercontent.com/32286970/31417614-e12c4fc4-ae5a-11e7-9f14-7fff7163a8df.png)
After reloading, all tasks in the terminal panel disappears. But the processes still running.
![image](https://user-images.githubusercontent.com/32286970/31417646-2364cc54-ae5b-11e7-9454-19fe91b9b717.png)

**Comment by Tyriar** [comment]
Closing this in favor of:

- Hot exit for terminal; keep terminals around between window reloads https://github.com/Microsoft/vscode/issues/20013
- Have confirmOnExit only prompt when the terminals have sub-tasks https://github.com/Microsoft/vscode/issues/23808
