### ISSUE TITLE
Terminal canvas  rendering Chinese anomalies

### ISSUE THREAD

**Issue by ChasHong** [Microsoft/vscode#35964]
- VSCode Version: 1.17.0
- OS Version: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. open Terminal
2. touch 测试.txt
3. ls
4. ctrl + l  Terminal clear
![peek 2017-10-10 15-03](https://user-images.githubusercontent.com/25047036/31373413-8e72ab40-adcc-11e7-9bdb-09a5d29288c4.gif)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
