### ISSUE TITLE
有没有快速切换文件后缀的快捷键，就算右下角的文件后缀。比如js后缀快速切换成html后缀

### ISSUE THREAD

**Issue by leeseean** [Microsoft/vscode#35967]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.有没有快速切换文件后缀的快捷键，就算右下角的文件后缀。比如js后缀快速切换成html后缀
2.有没有快速切换文件后缀的快捷键，就算右下角的文件后缀。比如js后缀快速切换成html后缀

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
Translatation: There is no quick to change the file suffix shortcut keys, even if the lower right corner of the file suffix. Such as js suffix quickly switch to html

There is a key binding for the `Change Language Mode` command: CTRL+K M
