### ISSUE TITLE
终端中文显示

### ISSUE THREAD

**Issue by chihysoa** [Microsoft/vscode#35969]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
vscode-standard-format|che|0.0.12
velocity|sod|0.1.0
vscode-import-cost|wix|2.5.0

---

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/12008127/31374634-5833fe2a-ad64-11e7-804a-22082adb3666.png)

Reproduces without extensions: Yes/No

**Comment by lijing666** [comment]
I found this issue too after I updated to VSCODE latest version

**Comment by dddddavy** [comment]
me too, after the latest update.

**Comment by egamma** [comment]
Translation of title: Terminal Chinese display

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
