### ISSUE TITLE
Update Inno Setup to the latest version

### ISSUE THREAD

**Issue by XhmikosR** [Microsoft/vscode#35977]
- VSCode Version: 1.17.0
- OS Version: Windows

The latest Inno Setup version is 5.5.9, with many improvements compared to the old version you currently use. See http://www.jrsoftware.org/files/is5-whatsnew.htm

**Comment by joaomoreno** [comment]
We won't go this way. We want to improve the Windows update experience. That will probably involve dropping Inno.
