### ISSUE TITLE
Import path quick suggestions - performance issue

### ISSUE THREAD

**Issue by mudrz** [Microsoft/vscode#35971]
- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

Reproduces without extensions: Yes

Path Intellisense is very slow on a medium sized project and unusable on a big project - there is 2-4 seconds delay before folder/files suggestions are shown

**Comment by mjbvz** [comment]
Possible related to https://github.com/Microsoft/TypeScript/issues/16329

Can you try installing the latest TypeScript 2.6 dev build in your workspace by running` npm install typescript@next` and following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if fixes the issue

**Comment by mudrz** [comment]
@mjbvz 
I just installed TS 2.6 and the performance issue is indeed fixed
(aliases are still not correctly resolved though https://github.com/Microsoft/TypeScript/issues/19113)

**Comment by mjbvz** [comment]
Thanks for the following up @mudrz. We'll keep looking into the alias path suggestions issue.  Closing this issue as upstream.
