### ISSUE TITLE
Import path quick suggestions - jsconfig aliases not recognised

### ISSUE THREAD

**Issue by mudrz** [Microsoft/vscode#35970]
- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

Reproduces without extensions: Yes

Doesn't work properly with aliases added in `jsconfig.json` https://code.visualstudio.com/docs/languages/jsconfig

Sample `jsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "ClientApp/*": ["./ClientApp/*"]
    }
  }
}
```
Expected behaviour
```js
import Something from 'ClientApp/...'
```
will pull path intellisense for folder `ClientApp`

Existing extension [path-intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) for example can also be configured with aliases in `settings.json`
```json
"path-intellisense.mappings": {
    "ClientApp": "${workspaceRoot}/MvcProject/ClientApp",
  }
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19113
