### ISSUE TITLE
The new icon sacks (on my blue desktop) - revert to the old one

### ISSUE THREAD

**Issue by ChariatisAD** [Microsoft/vscode#35973]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-firefox-debug|hbe|0.16.1
debugger-for-chrome|msj|3.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/35783
