### ISSUE TITLE
php mysql querys in <<<A A; highlighting not working

### ISSUE THREAD

**Issue by peon501** [microsoft/vscode#35979]
php mysql querys in <<<A A; highlighting not working

- VSCode Version:newest
- OS Version: win8.1

Steps to Reproduce:

$query=<<<A
SELECT lala FROM blablabla
A;

**Comment by roblourens** [comment]
Are you expecting mysql highlighting? We don't support that here. If there's a problem with the PHP syntax highlighting, can you post a screenshot?

**Comment by str** [comment]
I think @peon501 means something like this:

![selection_001](https://user-images.githubusercontent.com/123817/31475082-fea1c316-aebb-11e7-9fea-731d4e9faeb2.png)

**Comment by peon501** [comment]
Yes I want something like in @str image

**Comment by peon501** [comment]
Ok so I have to use SQL insted of anything else 👍  ty for this :).

**Comment by str** [comment]
@peon501 I don't know if the issue should be closed. The highlighting in the 2 defined strings are very different.

**Comment by roblourens** [comment]
This is actually a theme issue, not a grammar issue.
