### ISSUE TITLE
启动后有两个rg.exe进程占用cpu

### ISSUE THREAD

**Issue by whcxiaobai** [Microsoft/vscode#35976]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-html-css|ecm|0.1.8
vscode-great-icons|emm|2.1.16
open-in-browser|tec|1.1.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
 
![111](https://user-images.githubusercontent.com/20062144/31378627-82d62dd6-adde-11e7-99ea-8b28f0c736e4.png)

2.

Reproduces without extensions: Yes/No

**Comment by sunking3** [comment]
the  same problem。vs：Windows x64，Chinease version；os：win10 x64.
and if open with no-extension,the process "windows modules insaller worker" will occupy  high cpu

**Comment by chrmarti** [comment]
@whcxiaobai Are you using `cnpm`? If so, could you try removing `node_modules` and then installing with `cnpm install --by=npm`?
