### ISSUE TITLE
a bug in Chinese version

### ISSUE THREAD

**Issue by jjjjj19980806** [Microsoft/vscode#35975]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 
在終端機中 要是有出現中文 而且空間不夠 需要滾動的時候滾下去就會出現殘影 很難閱讀 不過英文的就不會 https://imgur.com/a/Sv3YU

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.13.1
VerilogHDL|msh|0.0.13

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
