### ISSUE TITLE
[folding] breaks when a particular sequence of text is entered

### ISSUE THREAD

**Issue by SenHengDesamis** [Microsoft/vscode#35981]
- VSCode Version: 1.17.0
- OS Version: macOS 10.12.6 (Sierra)

Steps to Reproduce:

I've reduced the code to the bare minimum where the bug occurs.

1. inserting the text `// region` between a const declaration and an array transformer
```
function thisFoldsToEndOfPage() {
  const variable = []
    // regionの型に変更   <-- this line
    .reduce((a, b) => a,[]);
}

function thisFoldsProperly() {
  const foo = 'bar'
}
```
Folding breaks
![2017-10-10 19 32 05](https://user-images.githubusercontent.com/27673439/31382163-b93db4e4-adf1-11e7-8847-441b69ebcb5e.png)

2. After removing Japanese text
```
function thisFoldsToEndOfPage() {
  const variable = []
    // regio
    .reduce((arr, event) => arr,[]);
}

function thisFoldsProperly() {
  const foo = 'bar'
}
```

Now it folds properly
![2017-10-10 19 34 22](https://user-images.githubusercontent.com/27673439/31382275-0ee618be-adf2-11e7-8365-841e6c372f32.png)

3. Other things I've tried
- switching with other reducers (sort/filter/concat/etc) doesn't solve the problem
- another mixed string `// asdfアイウエオ`, this doesn't cause any problem
- all Japanese text `// アイウエオ`, this doesn't cause any problem
- all English text `// asdf`, this doesn't cause any problem
- `// regioe` this doesn't cause any problem
- `// regionasdfasdf` this breaks.
- `// region` this breaks. `region` seems to be the problem.

Reproduces without extensions: Yes

**Comment by SenHengDesamis** [comment]
updated with more conditions

**Comment by aeschli** [comment]
Thanks @SenHengDesamis, good find!
