### ISSUE TITLE
Displaying broken characters in console

### ISSUE THREAD

**Issue by tim37021** [Microsoft/vscode#35982]
- VSCode Version: 1.17.0
- OS Version: Win10 x64

Steps to Reproduce:

1. msbuild
or
2. Type any character that ends in '\': for eaxmple '許' '功' '蓋'

![image](https://user-images.githubusercontent.com/5507113/31384132-2eb073f8-adf0-11e7-868e-82875f77de56.png)

(Code Page 950)

**Comment by tim37021** [comment]
If I change the codepage to CP437, VC++ will output english message and everything works fine

**Comment by tim37021** [comment]
duplicated https://github.com/Microsoft/vscode/issues/35969

**Comment by egamma** [comment]
Closing as a duplicate of #35969
