### ISSUE TITLE
Support for multiple filters in emmet abbreviation

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#35984]
- VSCode Version: Code - Insiders 1.18.0-insider (dcd1aa35dfa590b4a528e1ab55e957002f430f17, 2017-10-10T05:26:33.683Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
docthis|joe|0.4.8
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
sublime-keybindings|ms-|2.9.1
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

Realisation in sublime

![a](https://user-images.githubusercontent.com/15665678/31390629-1891989e-addd-11e7-81f1-e94f1ccecc19.gif)

It's very good working

---

Steps to Reproduce:

![a](https://user-images.githubusercontent.com/15665678/31390795-7ef8f8d4-addd-11e7-914e-071c3944e25f.gif)

1.It's not working
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
We don't support multiple filters at the moment in abbreviations.

If you want to use the bem and comment filters all the time, then one way to do this at the moment is to update your syntax Profiles with bem and comment as default filters

```
"emmet.syntaxProfiles": {
        "html": {
            "filters": "bem,c"
        }
    }
```

**Comment by linedotwww** [comment]
if I insert a space after code .block>.-item|bem but then I returned last position after keypress TAB it's not working

**Comment by ramya-rao-a** [comment]
When you do that the suggestions are gone. Either hit `Ctrl+Space` to manually trigger suggestions again or set `emmet.triggerExpansionOnTab` to `true`

**Comment by linedotwww** [comment]
thank you very much)))

**Comment by ramya-rao-a** [comment]
Since there is a workaround for this (See https://github.com/ramya-rao-a), we wont be taking this feature request as a priority at the moment.
PRs are welcome though, and I can guide anyone who is interested as to where the fix should go.
