### ISSUE TITLE
Output double byte text in terminal, display bug

### ISSUE THREAD

**Issue by asins** [Microsoft/vscode#35985]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
vscode-docker|Pet|0.0.18
vscode-css-formatter|aes|0.0.2
dotjs|all|0.0.6
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vue|liu|0.1.5
vetur|oct|0.9.11
sass-indented|rob|1.4.2
nunjucks|ron|0.2.3
stylelint|shi|0.29.1
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Enter terminal input window
2. Enter Chinese characters in the terminal

![image](https://user-images.githubusercontent.com/898354/31390748-42c5a842-ae07-11e7-86da-3a599a51de0d.png)

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660
