### ISSUE TITLE
[Feature request] Add terminal into Zen mode

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#35980]
I suppose, it'll be a good thing e.g. in case of working with node.js application

**Comment by Mlocik97-issues** [comment]
It's already implemented, I think.

**Comment by Wosi** [comment]
You have at least two choices in the command palette: 
`View: Toggle Integrated Terminal`
or
`Terminal: Focus Terminal`

**Comment by antony-chopin** [comment]
@Wosi ok, seems like it fits, sorry for picking up the dust!

**Comment by Mlocik97-issues** [comment]
![screenshot_104](https://user-images.githubusercontent.com/31345346/31388895-ccc65812-adcf-11e7-8e8d-90ef815be2e4.png)


And this is what? In zen Mode.
