### ISSUE TITLE
[folding] Provide a parameterized code folding command to be called from an extension

### ISSUE THREAD

**Issue by twlamb** [Microsoft/vscode#3598]
Is there a way with the new code folding for an extension to toggle a fold? I want to have my extension by default fold a comment that is at the top of all files.

**Comment by aeschli** [comment]
You can programmatically set the cursor and invoke the folding command.
But by doing that you would assume that the folding regions are always computed the same way. We are planning to make this extensible and customizable.

To avoid you having to set the cursor, we could also add a command that takes the line number as argument.

**Comment by twlamb** [comment]
From the info in #32655 - I can accomplish what I will need so I am closing this issue.
