### ISSUE TITLE
Touch Bar Icon Scaling

### ISSUE THREAD

**Issue by idleberg** [Microsoft/vscode#35997]
- VSCode Version: 1.17.0
- OS Version: macOS 10.13 (17A405)

Steps to Reproduce:

After the release of 1.17, I tried adding Touch Bar icons to one of my extensions. Since I don't have a Touch Bar in my MacBook, I tested my changes using Xcode 9.0's built-in software Touch Bar and the third-party [Touch Bar Simulator](https://github.com/sindresorhus/touch-bar-simulator). From my existing SVG icons, I created PNG images.

**24x24 pixels:**

![touch-bar-scale-1](https://user-images.githubusercontent.com/1504938/31403200-bc52e2e2-adf8-11e7-95b5-dd745cd22d30.png)

**48x48 pixels:**

![touch-bar-scale-2](https://user-images.githubusercontent.com/1504938/31403247-df1a6d36-adf8-11e7-82af-3a46b9e8c302.png)

As you can see (in fullscreen), both icons have the same problem: they're not scaled properly and parts of the images are cropped. I did some reseach in Apple's [Human Interfaces Guidelines](https://developer.apple.com/macos/human-interface-guidelines/touch-bar/touch-bar-icons-and-images/) and also tried a couple of other things:

- 36x36
- 44x44
- 60x60
- each of the above with `@2x` suffix in file-name
- 60x60 icons with the actual image being 36x36 or 44x44

None of that had any effect on the icons in the Touch Bar, they always looked like in one of the screenshots above. Documentation on the topic is scarce. Maybe this is a bug. I don't know for sure.

I'll gladly supply more info on this, if needed.

**Comment by bpasero** [comment]
@idleberg the icons we are using are 100x100px (canvas) with a resolution of 144ppi. The icon itself is ~32x32px, so there is lots of transparent space around the icon to accommodate for the scaling issues.

**Comment by idleberg** [comment]
One more remark: if I'm not mistaken, one can only use the same icons in `editor/title` and `touchBar`. Icons with padding (as you descibed) work fine in `touchBar`, but at the same time they are too small, thus unreadable. in the `editor/title` menu.

> We currently require the commands icon to be of PNG file type. SVG is not supported.
> [Source](https://code.visualstudio.com/updates/v1_17#_touch-bar-support)

The word “currently” leaves hope that this will be overworked in the future. If that's the case, please consider a solution that works for both, the `editor/title` and `touchBar` menus.  As I see it, the best solution would be to work with SVG icons and solve the padding in the Touch Bar programatically. Alternatively, let the user provide separate icons for the menus.
