### ISSUE TITLE
Provide API allowing extensions to provide enhanced command palettes

### ISSUE THREAD

**Issue by dakaraphi** [microsoft/vscode#35993]
I would like to build an extensions to provide many enhancements to a command palette interface.

The capabilities I would like to provide to VSCode can be viewed at [Commander, a next-gen command palette for Eclipse](https://github.com/dakaraphi/eclipse-plugin-commander)

**Some initial thoughts on required API capabilities:**

- Capture keyboard input events from input field and handle in extension
- Change list content on handling of input events
- Add columns to list content
- Handle some level of rendering of content
    - Provide indication of markers to be applied on a row
    - Provide character indices or information for highlighting matched characters

**Comment by egamma** [comment]
@dakaraphi it is unlikely that we would expose API for all the feature requests you mentioned above. So this would not be done as an extensions but in a Pull Request against VS Code. Since this would be a larger Pull Request that requires ongoing discussion.

**Comment by mjbvz** [comment]
#49340 tracks a discussion of an improved input API. Please follow up there
