### ISSUE TITLE
Bad AA on characters immediately following emojis

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35994]
1.17.1 candidate build, found verifying #35656

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: A few

---

![image](https://user-images.githubusercontent.com/9205389/31400335-13288dc4-ada4-11e7-9ece-58c300f21d4c.png)

**Comment by Tyriar** [comment]
The overlapping thing is as designed as it's how emoji's are sized within the shell. I do notice there is some bad AA on the char on top of the emoji though, that can be fixed.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/1060

**Comment by Tyriar** [comment]
Would be fixed by https://github.com/xtermjs/xterm.js/issues/1059
