### ISSUE TITLE
.deb package from APT repository has corrupt xz compression

### ISSUE THREAD

**Issue by schachmat** [Microsoft/vscode#35992]
Our mirroring is broken since 2017-10-06. You can reproduce from the terminal like this:

$ wget http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.18.0-1507267008_amd64.deb
…
2017-10-10 14:25:57 (43.8 MB/s) - ‘code-insiders_1.18.0-1507267008_amd64.deb’ saved [43198092/43198092]
$ ar vx code-insiders_1.18.0-1507267008_amd64.deb
x - debian-binary
x - control.tar.gz
x - data.tar.xz
$ file data.tar.xz
data.tar.xz: XZ compressed data
$ xz -d -c <data.tar.xz >/dev/null
xz: (stdin): Compressed data is corrupt
$ xz --version
xz (XZ Utils) 5.1.0alpha
liblzma 5.1.0alpha

**Comment by schachmat** [comment]
Same result for more recent xz version 5.2.2

**Comment by Tyriar** [comment]
I've passed this on to the team responsible for the repo.

**Comment by chrmarti** [comment]
@Tyriar It looks like we updated the uploaded file, but that hasn't been propagated to the public repo. I'll try deleting the uploaded file in the hope that the deletion will propagate.

**Comment by chrmarti** [comment]
Only saw you comment now. Holding back on deleting the file for now.

**Comment by chrmarti** [comment]
It is possible that this is just taking more time to synchronize. We will wait some more.

**Comment by chrmarti** [comment]
@schachmat I have removed the file now.

**Comment by schachmat** [comment]
I can confirm. Thanks for fixing.
