### ISSUE TITLE
Disable touch bar or allow to configure it

### ISSUE THREAD

**Issue by anvaka** [Microsoft/vscode#35990]
- VSCode Version:  1.17.0 (1.17.0)
- OS Version: MacOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Write javascript code
2. Accidentally touch touch bar with "debug" button. 

I run into this very regularly, I'm not interested in debugging with VS code, yet because touch bar is very sensitive, I often accidentally press that button. Is there a way to disable touch bar? Or at least remove the debug button?

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@anvaka you can do this with macOS preferences, just follow https://apple.stackexchange.com/questions/283565/customise-touch-bar-for-a-specific-application
