### ISSUE TITLE
Differences in Terminal and Editor font rendering on Windows

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#35991]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Some

1.17.1 candidate build

Using the steps from #35188 with Fira Code on my Windows 10 VM:
![image](https://user-images.githubusercontent.com/9205389/31399338-d381f4ba-ada0-11e7-8423-cfc44c79da9d.png)

The terminal's rendering seems to have less weight?

**Comment by wsmd** [comment]
I'm having similar issue with Version 1.17.1 (1.17.1) on macOS Sierra 10.12.6

The terminal font looks a little bit blurry and squeezed compared to the editor font:

```
"terminal.integrated.fontFamily": "Menlo",
"terminal.integrated.lineHeight": 1.4,
```

**Terminal**

![image](https://user-images.githubusercontent.com/2100222/31407013-6791edd8-add1-11e7-8105-7d7bdf6254e6.png)

**Editor**

![image](https://user-images.githubusercontent.com/2100222/31407039-77333120-add1-11e7-9bc6-0795283ca6c3.png)

**Comment by skriss** [comment]
I'm also seeing this issue on the same configuration as @wsmd

**Comment by abrakidabra** [comment]
I'm having the same issue. Only in the latest version though. This wasn't a problem for me in v1.17.

macOS 10.12.6
VS Code v1.17.1

![screen shot 2017-10-11 at 13 19 38](https://user-images.githubusercontent.com/20607891/31419341-1b66a168-ae87-11e7-8565-d75acec7cd14.png)

![screen shot 2017-10-11 at 13 19 00](https://user-images.githubusercontent.com/20607891/31419338-1665ce64-ae87-11e7-8cf9-0bc4f20c21c2.png)

**Comment by Tyriar** [comment]
Can repro on a low DPI monitor (well VM).

**Comment by ivan-ha** [comment]
facing the same after update to 1.17.1 on macOS

**Comment by Tyriar** [comment]
Verified the fix works in the latest unreleased insiders

**Comment by ItsNoHax** [comment]
Thanks for the quick fix!

**Comment by sjdweb** [comment]
+1 for quick fix. Any way to downgrade for time being?

**Comment by wizardion** [comment]
+1 Thanks for the quick fix!

**Comment by deejayxd07** [comment]
+1 for the quick fix!

**Comment by simonhaenisch** [comment]
The font renders fine again, but I still got this issue on macOS Sierra where the character under the cursor gets pushed up in the first line of the terminal:

![screencast](https://user-images.githubusercontent.com/3410759/31699821-9de79468-b421-11e7-9daf-d53cd1a34715.gif)

It only happens when I'm in the first line, i. e., after opening the terminal or running `clear`. Anyone else with this? Could not find an open issue for it.

**Comment by Pajn** [comment]
It does not occur for me, I'm using pure prompt as well.

**Comment by simonhaenisch** [comment]
Happens with other prompts as well... how far the character gets pushed up depends on the line the cursor is in:

![image](https://user-images.githubusercontent.com/3410759/31711224-fa04093e-b453-11e7-9c55-48336d398fd5.png)

![image](https://user-images.githubusercontent.com/3410759/31711289-1b17b9c2-b454-11e7-8244-62c3cc72e19c.png)

![image](https://user-images.githubusercontent.com/3410759/31711311-2deda872-b454-11e7-87f3-e2dd8060cb9b.png)

![image](https://user-images.githubusercontent.com/3410759/31711314-33ac5560-b454-11e7-920d-af50440c23ca.png)

![image](https://user-images.githubusercontent.com/3410759/31711367-5b353264-b454-11e7-8fed-17346f72d09d.png)

From line six on the currently selected character is invisible (which is probably why I thought it was only in the first line).

This didn't happen before updating to `1.17.1`. Here is my current info:

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Reproduces without extensions: Yes

**Comment by lucasfernandes4472** [comment]
+1 for the quick fix!

**Comment by Tyriar** [comment]
@simonhaenisch I cannot repro on Sierra. Can you create a new issue and include your settings.json file?

**Comment by ovasquez** [comment]
@Tyriar which was the font used by error in the Terminal? I actually liked it a lot and would like to set it again.

**Comment by Tyriar** [comment]
@ovasquez not sure what other people are using but I use Hack http://sourcefoundry.org/hack/

**Comment by gonssal** [comment]
![vscode-terminal](https://user-images.githubusercontent.com/1172272/32842706-0d6f4e22-ca1e-11e7-953c-8f95375bc4e4.png)

(K)Ubuntu 17.10. Unusable.

**Comment by chrmarti** [comment]
@gonssal Could you open a new issue for this? Thanks.
