### ISSUE TITLE
Layout displacement while opening search

### ISSUE THREAD

**Issue by ThatsEli** [Microsoft/vscode#35999]
After reproducing you can see there is a displacement from the top of the window to the first row. When closing the search popup, the displacement is fixed.

- VSCode Version: 1.17.0
- OS Version: Windows 10 Version 1703 - (Build 15063.608)

Steps to Reproduce:

1.Scroll down until you can't see row one anymore
2.Open search with CTRL+F.
3.Scroll back up.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected. The space is there so that the find widget doesn't cover up the first line in the editor.
