### ISSUE TITLE
Emmet not working in vanilla VSCode install (0.10.x)

### ISSUE THREAD

**Issue by silverbucket** [Microsoft/vscode#3599]
Not sure what's going on here, I removed and re-installed VSCode just to be sure. Emmet does not seem to be working:

1. Open HTML file with the contents:
```html
<html>
<body>
</body>
</html>
```
*(editor shows HTML in bottom right info-bar)*

2. Between the body tags, I enter:
`div>ul>li*5`

3. Hit enter and nothing happens, just go to new line. In fact, no auto HTML formatting is happening, making editing HTML quite cumbersome.

I saw a previous issue about this (#958), where extensions were discussed. I've never installed an extension and don't even know how to view whether I have extensions installed or not, which is another reason I deleted, re-downloaded, and installed Visual Studio Code from scratch just to be sure.

**Comment by silverbucket** [comment]
And just in case someone would ask, my user preferences are minimal:

```javascript
// Place your settings in this file to overwrite the default settings
{
	// Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
	"editor.tabSize": 2,

	// Controls if the editor will insert spaces for tabs. Accepted values:  "auto", true, false. If set to "auto", the value will be guessed when a file is opened.
	"editor.insertSpaces": true
}
```

**Comment by egamma** [comment]
@silverbucket what version of VS Code are you using (see the About Box), are you on the insider or the stable channel?

**Comment by silverbucket** [comment]
@egamma the version is `0.10.9` I believe I'm on the stable channel, as it's a fresh install from the main site.

Just to test it out, I tried downloading VSCode on my Windows machine. I get the exact same behavior as described above. Version is `0.10.8`

**Comment by egamma** [comment]
@silverbucket just did a fresh install of `0.10.9` and emmet is expanded. 

But now I read your description again:

>Hit enter and nothing happens

The emmet expansion key is TAB and not ENTER.

Also if TAB doesn't work can you execute the 'Emmet: Expand Abbreviation' from the command palette.

**Comment by silverbucket** [comment]
Thanks @egamma - I had a fealing it was something simple like that! Just checked and it's working for me!

**Comment by amitthk** [comment]
Doesn't work for me either way.  Neither the Tab, not clicking the Emmet:Expand Abbreviation from commands menu.

*Visual Studio Code:*
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

*Extensions Installed:-*
C#, TSLint, Angular 2 Typescript Snippets

**Comment by kumanan12** [comment]
I was teaching HTML5 to high school kids using visual studio code.  Emmet wasn't working in their machines(PC and MAC). Also checked for updates.  Dont know whats the issue. Please advise.
