### ISSUE TITLE
App lockup/freezes when switching to it

### ISSUE THREAD

**Issue by SnowShock35** [Microsoft/vscode#35998]
Hi,

I've just installed Visual Studio Code on my brand new laptop. I've spent today working on a website only to find that when switching between the browser and code, code will stop responding. I'll be unable to type or attempt any actions within the program. The program will then take a few seconds (longest so far was about 20 seconds) to respond again. This is becoming exceptionally difficult to deal with and I've never had this problem before on my desktop. While I'm aware they're two completely different devices this behaviour is odd none the less. 

I would appreciate any advice or help in solving this issue that you could provide.

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open code and one other program (In my case the browser)
2. Have the other program as the currently active window then switch to code.
3. After doing this you'll perhaps experience the app not responding or working at all.

It can also happen during other aspects of the app. This is just the one I've noticed most

Reproduces without extensions: Yes/~~No~~

**Comment by SnowShock35** [comment]
My laptop specs are as follows:

Clevo N850HK1 GTX-1050 Ti i7-7700HQ
Includes 1920 x 1080 15.6" IPS Screen
SINGLE COLOUR BACKLIT UK KEYBOARD
8GB Corsair VENGEANCE 2400MHz SODIMM DDR4 (2 x 8GB)
Samsung MZ-V6E250BW 960 EVO 250GB
GIGABIT LAN & WIRELESS INTEL® AC-8260 M.2 (867Mbps, 802.11AC
Microsoft Windows 10 Home OEM DVD 64bit

Worth noting that all I've done since getting the laptop is:

- Disable hibernation
- Enable Linux subsystem for Windows
- Install programs (Visual Studio Code, Prepros, Node.js, MongoDB,  Spotify, Discord Canary, ShareX, Microsoft Office 2016 + OneDrive for Business, Adobe Photoshop CC, Adobe Illustrator CC, Adobe Experience Design (Beta), Samsung Magician, GeForce Experience, Google Chrome, Git, 7-Zip)
- Tweaked settings like task bar setup, start menu appearance, uninstall unwanted windows 10 junk (candy crush saga, etc.)

**Comment by egamma** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by egamma** [comment]
Some more questions, does this happen when you edit a particular file? Can you characterize what the file looks like, what language, what size. Is there anything special about it.

**Comment by egamma** [comment]
It would be really helpful for us when you provide us with a CPU profile when this happens. Here is how:

Hit F1 > Toggle Developer Tools. In the overflow menu (see below) select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds when this happens, stop it, save it to a file and attach the file here. 

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by SnowShock35** [comment]
The issue seems to have stopped now. I'm not sure why since there was no fixes relevant to that issue in the release notes and I've not changed anything. :/ Should I still provide the information or just close the issue?

**Comment by SnowShock35** [comment]
It's possible the issue isn't occurring 100% of the time and at "random" intervals. Can't be certain.

**Comment by egamma** [comment]
Thanks for coming back. Did you uninstall an extension in the meantime? If you cannot reproduce the issue, then I suggest to close this one and reopen it.

**Comment by SnowShock35** [comment]
I changed nothing. The only thing I had done was update to a hot fix released later that day when the bug was initially reported. So for now I'll close the issue. Should I have any further issues I'll be sure to either reopen the issue or create a new one.
