### ISSUE TITLE
[Git] weird indicator for renamed file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36]
(I am on Mac OS X, Git 2.4.0)

- have a checked in README.md with some contents
- take the contents of the file and move it to a new file CONTRIBUTING.md
- change the text in README.md to something else
- stage all

![image](https://cloud.githubusercontent.com/assets/900690/11213365/e6561f9e-8d3b-11e5-9bbc-453bfe70d904.png)

**Comment by jimschubert** [comment]
On OS X El Capitan, I just ran through this scenario with:

* git 2.4.9 (Apple Git-60)
* Code 0.9.2 3fd93bd0833cc6ad311134e254f8ec2b048994a3
* hub 2.2.1

and staging looks as I'd expect:

<img width="828" alt="contributing_md_-_vscode-36" src="https://cloud.githubusercontent.com/assets/109659/11259418/7cc13ba0-8e2f-11e5-8bac-65c5ae76214b.png">

**Comment by hashhar** [comment]
I tried this and seems that the issue is gone. It might have been an isolated event.
