### ISSUE TITLE
Keyboard shortcut Find In Files should not move focus to the editor

### ISSUE THREAD

**Issue by natesilva** [Microsoft/vscode#36006]
- VSCode Version: 1.17.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open a project.
2. Open some file in that project.
3. Press the keyboard shortcut for “Find In Files” (Shift-Cmd-F or Shift-Ctrl-F)
4. Search for something.
5. Press the keyboard shortcut again. And again.
    * Notice that the cursor (focus) toggles between the find panel and the editing area each time you press the keyboard shortcut

Reproduces without extensions: Yes

Let’s say you’re busy. You press Shift-Cmd-F, type `🦄`, and hit Enter to find some unicorn-related functions. You get a call from your boss who explains that we need to fix some rainbow functions. You come back to the computer, press Shift-Cmd-F, type `🌈`, and hit Enter.

**Expected result:** You should see functions related to rainbows.

**Actual result:** Any text that was selected in your editor has been erased and replaced by a rainbow and a newline.

→ Shift-Cmd-F / Shift-Ctrl-F should not be modal. Pressing this keyboard shortcut should always focus on the Find In Files panel, or leave focus there if it is already on that panel.

**Comment by teki** [comment]
Workaround, add to your keybindings.json:
```
    {
        "key": "shift+cmd+f",
        "command": "workbench.action.findInFiles",
        "when": "searchInputBoxFocus && searchViewletVisible"
    }
```

**Comment by natesilva** [comment]
Fantastic. This workaround solves the issue.

This fix needs to be incorporated into the product… unless they intended the current behavior, which I can’t imagine they did.

**Comment by ggaughan** [comment]
I used `ctrl+shift+f` for linux

**Comment by roblourens** [comment]
This is actually the intended behavior, to match the other viewlet shortcuts that toggle focus between the viewlet and editor. The keybinding suggestion is the correct workaround if you don't like that behavior.
