### ISSUE TITLE
I hate this new logo

### ISSUE THREAD

**Issue by leeseean** [Microsoft/vscode#36009]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.I hate this new logo
2.I hate this new logo

Reproduces without extensions: Yes/No

**Comment by jindaxia** [comment]
agree

**Comment by SethPoulsen** [comment]
This is a duplicate of [#35683](https://github.com/Microsoft/vscode/issues/35683) and [#35783](https://github.com/Microsoft/vscode/issues/35783). Don't worry, you're not alone ;). Follow the links to see the hundreds of other complaints about it...

**Comment by BIGWarriorSoftware** [comment]
If you hate this, you can change it in the application properties.

**Comment by coladou** [comment]
Urgly LOGO!
