### ISSUE TITLE
Where is the source code for visual studio?

### ISSUE THREAD

**Issue by megamindbrian** [Microsoft/vscode#36008]
I have been dealing with an error popup every day for the last year.  Please configure IIS *AFTER* the project has loaded:

![image](https://user-images.githubusercontent.com/25057134/31417726-4cc7323c-ade6-11e7-870c-d2be0c87a537.png)

At some point I have to stop asking "why isn't this fixed?" and do it myself.

**Comment by KamranMackey** [comment]
This repository doesn't deal with issues related to the Visual Studio IDE. For that you'll need to report this issue to the proper channels. And, the Visual Studio IDE is proprietary. Only VS Code is open source software.

**Comment by megamindbrian** [comment]
Bummer, Thank you!!

**Comment by mjbvz** [comment]
Please try submitting this issue to VS itself: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017

**Comment by megamindbrian** [comment]
OMG, I think that worked.  I couldn't get it to screenshot the dialog but I
submitted a reproduce recording.  If they fix this issue I've had every day
for the last year I have to send you pizza/beer/whatever money.
