### ISSUE TITLE
JSDoc comments don't infer argument types

### ISSUE THREAD

**Issue by simonhaenisch** [Microsoft/vscode#36004]
- VSCode Version: 1.17.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

I type the following function in Typescript:

```ts
function foo(bar: String, options: Object = {}) {
  return bar.repeat(2);
}
```

Then I trigger a JSDoc comment and it adds the following:

```ts
/**
 * 
 * @param bar 
 * @param options 
 */
function foo(bar: String, options: Object = {}) {
  return bar.repeat(2);
}
```

Why does it not infer the types of the parameters and their optionality? i. e. I want this doc block:

```ts
/**
 * 
 * @param {string} bar 
 * @param {Object} [options] 
 */
```

It would also be nice if the return type would be inferred, but I found Microsoft/TypeScript#14248 which addresses this.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This is as-designed. In TypeScript, the types themselves are the source of typings truth, not the types in jsdoc comments. You should generally not use types in JSDoc comments for TypeScript files, and the compiler will ignore these anyways

**Comment by joelday** [comment]
@mjbvz My only concern about not including types is the scenario where declarations are published in the module for consumption by plain JS projects.

**Comment by mjbvz** [comment]
@joelday If you want you can still include typings annotations in your jsdocs with TypeScript, we just won't use them for type checking your code

**Comment by simonhaenisch** [comment]
Would be nice to have it infer if an argument is optional though, right?
