### ISSUE TITLE
Memory Leak 1.17 Renderer Linux

### ISSUE THREAD

**Issue by resolutecake** [Microsoft/vscode#36005]
Impact: VSCode has to be terminated after 24 hours

- VSCode Version: Version 1.17.0
- OS Version:
echo $(lsb_release --id --release --short --codename)
Ubuntu 17.04 zesty

It worked prior to upgrade, when the icon was not orange

GNOME Wayland multi-display MacBook Pro 2015

Steps to Reproduce:

1. Launch code and leave running
2. Leaks 20 MiB VSIZE per 84 minutes
3. After day or so the computer starts swapping heavily leaing to 10 - 20 s outages for mouse/keyboard

It's the renderer process that launches searchServcie and such, 31153 in the below
```
ps -C code -o pid,ppid,user,group,vsz,lstart,etime,args | cat
  PID  PPID USER     GROUP       VSZ                  STARTED     ELAPSED COMMAND
31081 31079 foxyboy  foxyboy+ 1630588 Tue Oct 10 12:28:19 2017   03:51:12 /usr/share/code/code
31084 31081 foxyboy  foxyboy+ 342240 Tue Oct 10 12:28:19 2017    03:51:12 /usr/share/code/code --type=zygote --no-sandbox
31130 31081 foxyboy  foxyboy+ 479384 Tue Oct 10 12:28:19 2017    03:51:12 /usr/share/code/code --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,7,23,61,74 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x8086 --gpu-device-id=0x162b --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=3C4EAB4C40E66EC695E21789884120E6
31153 31084 foxyboy  foxyboy+ 1259800 Tue Oct 10 12:28:20 2017   03:51:11 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=39562A52A38B80E4655E84DB25A39F21 --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#fce5cd --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --service-request-channel-token=39562A52A38B80E4655E84DB25A39F21 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101
31156 31084 foxyboy  foxyboy+ 1093476 Tue Oct 10 12:28:20 2017   03:51:11 /usr/share/code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=1E682FD3755F6B4ADFC2F9907B774003 --lang=en-US --app-path=/usr/share/code/resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --service-request-channel-token=1E682FD3755F6B4ADFC2F9907B774003 --renderer-client-id=6 --shared-files=v8_natives_data:100,v8_snapshot_data:101
31228 31153 foxyboy  foxyboy+ 961332 Tue Oct 10 12:28:22 2017    03:51:09 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=extensionHost
31229 31153 foxyboy  foxyboy+ 954176 Tue Oct 10 12:28:22 2017    03:51:09 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService
31231 31153 foxyboy  foxyboy+ 927516 Tue Oct 10 12:28:22 2017    03:51:09 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=searchService
```

**Comment by resolutecake** [comment]
Some activity makes it leak faster. My other fattest process is 8 GiB vsize, but code went over to Terabyte unit in top, ie more than 10 GiB. Ill post what size it is next time it gets rowdy

**Comment by egamma** [comment]
Can you give some background on your project setup, language used, size/number of files.

>Some activity makes it leak faster. 

Can you narrow down what activity makes it leak faster.

**Comment by resolutecake** [comment]
This happens when a remote directory is opened over ssh, ie. the directory opened is the sshfs share mount point
- CPU constantly 10%
- Resident memory consumption 50% (8 GiB) - this makes everything on the computer really slow
- Virtual memory consumption 0.001 TiB per 12 s, ie. 5.12 GiB per minute
- This can lock up the Chromium browser cache, ie. a different application, preventing browsing: "waiting for cache…"

Local file system directories do not have this problem
It does not happen right away, but when it does, it’s game over

**Comment by resolutecake** [comment]
I have a script that deploys files using series of ssh connections

This is unrelated, using a different user account on the local host, goping from the remote computer but between the two same hosts. It writes some files in the near user’s home directory

This should not affect code at all, but it does. Perhaps code has some file watchers on ~ and goes berzerk on certain writes. How do I determine what  code is doing that consumes 5 GiB of memory per minute?

**Comment by resolutecake** [comment]
Perhaps @bpasero could reopen and examine this issue?

**Comment by bpasero** [comment]
@resolutecake can you please follow the advice in https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by demestav** [comment]
I experience similar behavior as @resolutecake describes, after upgrading to 1.17.2 from 1.16. I am also using ssh mounts. Looking at `htop` as suggested in https://github.com/Microsoft/vscode/wiki/Performance-Issues, it seems that the processes with `--type=searchService` keeps increasing until the system is overwhelmed completely.

**Comment by bpasero** [comment]
@roblourens fyi on https://github.com/Microsoft/vscode/issues/36005#issuecomment-339662818

**Comment by resolutecake** [comment]
Upgraded to Ubuntu 17.10 Wayland, still happens

currently blew through 107 GiB
waiting to see how it ends… 141 GiB…

I cannot trigger it every time I do the deploy-over-ssh, but it clearly is triggered by that activity.
So, when I run the same thing immediately again,it doesn’t happen

I think we are at the end of what silly users can figure out. Does msft has anything?

[CPU-20171029T163333.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1425600/CPU-20171029T163333.cpuprofile.txt)

**Comment by resolutecake** [comment]
lsof tells us it is not changing files open during 20 minutes
0.182 TiB…

**Comment by resolutecake** [comment]
page faults, page allocation stalls, memory pressure relief 0.196 TiB

**Comment by resolutecake** [comment]
The project is just text files, ie. YAML/Jinja, so Code only does a little syntax coloring

**Comment by roblourens** [comment]
@demestav Please open a new issue - you're seeing lots of activity in the searchService where @resolutecake is seeing it in the renderer process, so it may be a different issue.

Also please try the Insiders build, and try starting with `--disable-extensions`.
