### ISSUE TITLE
Add filename, line & column information in EvaluateArguments with 'hover' context

### ISSUE THREAD

**Issue by Tenebrous** [Microsoft/vscode#36000]
I'm implementing a z80 debugger, for example:
```
162A 5E       ld e, (hl)
162B 19       add hl, de
```

Hovering over `(hl)` in the first line should have more information than hovering over the `hl` in the second line - however, obviously the brackets are treated as a word boundary and don't get include in the EvaluateRequest.

Given the line & col information I could extract additional information. For (hl), for example, I could show the contents of the memory address pointed to by the HL register.

**Comment by isidorn** [comment]
This is just the current hover limiation of our debug hover. Closing as dupilcate of https://github.com/Microsoft/vscode/issues/24520
