### ISSUE TITLE
The "\r" of writting shell script 

### ISSUE THREAD

**Issue by Despertor** [Microsoft/vscode#36012]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.2.9200

when I run shell script in centos ,the shell told me that this script has "\r".I think this tool is not good than editplus... Then editplus will not write "\r" in script.

**Comment by egamma** [comment]
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment]
Given the terse description I can only speculate. 
Notice that you can control the line terminator used in a file in the bottom right corned in the status bar. By clicking on it you can switch to other line terminators.
