### ISSUE TITLE
Not able to attach debugger to already running nodejs web app on port 3001

### ISSUE THREAD

**Issue by SharmaHarsh7** [Microsoft/vscode#36016]
Hi,

I am not able to attach debugger to the already running NodeJS web app.

Following are my VSCode launching configurations:

 ```
 "configurations": [
    {
        "type": "node",
        "request": "attach",
        "name": "Attach",        
        "port": 3001
    },
```

I am getting following error message:

> Cannot connect to runtime process (reason: This socket has been ended by the other party).

Now, when I add `protocol : inspector` in the above configuration, it shows me the following error message:

> Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms  

I am currently using v8.6.0 version of NodeJS

**Comment by isidorn** [comment]
Well the message appears correct to me. When you launch your node app from the command line you should pass in the `--inspect` flag. Also in your launch.json you are using port 3001 and in the title port 3000, make sure you are using the correct port.

Not sure if we support attaching to node that is not running in inspect mode. @roblourens can comment more

**Comment by SharmaHarsh7** [comment]
Hi,

Thanks for your response.

I have corrected the port number in the title (Issue is not related to the port number) 

I am trying to run the NodeJS+Typescript+Express starter template provided by Microsoft:

- https://github.com/Microsoft/TypeScript-Node-Starter

And want to attach it to the debugger after running it from the command prompt.

I am not running the app with node command, instead I am using `npm start` to run it.

I hope above link will help you to better understand my issue, if you can replicate it.

I am currently using v8+ version of nodejs.

Thanks,
Harsh

**Comment by roblourens** [comment]
`npm start` doesn't start with the inspect flag. I see a `serve-debug` task which does, it looks like `npm run debug` might do what you want.

**Comment by SharmaHarsh7** [comment]
Thanks, I am able to attach to the debugger after changing the port from 3001 to 9229 and by using the command `npm run debug`

I have one more doubt, why there are so many request logs with following detail:

> [Node] GET /json/version 404 1.145 ms - 151
> [Node] GET /json 404 0.837 ms - 143
> [Node] GET /json 404 1.050 ms - 143
> [Node] GET /json/version 404 1.479 ms - 151
> [Node] GET /json 404 1.640 ms - 143
> [Node] GET /json/version 404 1.630 ms - 151
> [Node] GET /json/version 404 1.112 ms - 151
> [Node] GET /json 404 1.726 ms - 143

**Comment by roblourens** [comment]
Awesome, glad that worked.

Are all of those just from a single start of the debugger? Hm, not sure.

**Comment by SharmaHarsh7** [comment]
Yes... but happy it worked
