### ISSUE TITLE
residual word in terminal

### ISSUE THREAD

**Issue by DennisXie** [Microsoft/vscode#36011]
- VSCode Version: 1.17.0
- OS Version: windows7 sp1

Steps to Reproduce:

1. git commit -m "添加一些新的配置"
2. other command, such as ls

![issue pic](https://user-images.githubusercontent.com/10068887/31419290-96e8d2f8-ae6d-11e7-891b-fdf5d7b8c8ee.png)

Reproduces without extensions: yes

**Comment by Yurunsoft** [comment]
1.17.1已经修复了，你更新下
