### ISSUE TITLE
VS Code always appears of my screens

### ISSUE THREAD

**Issue by Allann** [Microsoft/vscode#36015]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.10
beautify|Hoo|1.1.1
csharp|ms-|1.12.1
js-atom-grammar|ms-|0.1.14
PowerShell|ms-|1.4.3
team|ms-|1.122.0
---

Steps to Reproduce:

_This is an issue when using multiple screens and with two different environments on the same machine (laptop)._

1. Load Code having one multi screen orientation (e.g. at home I use my laptop with a screen connected above my laptop screen)
2. Move Code to "other" screen and Close.
3. Change screen orientations (at work I have 2 additional screens to the left of the laptop screen)
4. Open Code.

Code now appears to the left of my left most screen.  I have to use Alt+Space then M and the arrow keys to move the screen right so that it appears on my left most screen.  i.e.  I'm assuming the top left coordinate that is saved is a -ve value, hence why I can't see the screen.

I hope that makes sense.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@Allann I tried a bunch of combinations and was not possible to reproduce so far. However one catch is that I only have 1 external monitor and my laptop monitor to play with. Can you try to reproduce with such a setup? My test case is always to start with one arrangement (e.g. secondary monitor on top of first) and then moving VS Code there, closing it and changing the monitor arrangement and restart. So far in all cases I tested VS Code appeared back on the primary monitor.

Alternatively if that is not possible for you, we could also try to add some debug code to print the window dimensions on startup to the console.

**Comment by bpasero** [comment]
Please continue in https://github.com/Microsoft/vscode/issues/35148
