### ISSUE TITLE
Autocompletion box "Loading..." indefinitely, even when receiving data

### ISSUE THREAD

**Issue by bojan-misic** [Microsoft/vscode#3601]
I'm using **VS Code 0.10.9** on **OS X 10.11.3** with [Code-D](https://github.com/Pure-D/code-d) for writing code in **D**. 

I have all the dependencies that **Code-D** requests, and I can see that the plugin is properly initiated, but I can't get the **autocompletion** (intellisense) box to show. I have a .gif to describe  the problem:

![vscode](https://cloud.githubusercontent.com/assets/5645089/13436536/04f77988-dfe0-11e5-932b-7b131df71753.gif)

When I open Developer's Tools, I can see that the symbols are resolved properly, there is a list of objects I should be able to see in the autocompletion box, but it just hangs with "Loading..." message. Sometimes it hangs indefinitely, sometimes I get it to show literally after 1 minute. I also have to press _CTRL+Space_ after **"."**, it's not triggered automatically.

I have to pinpoint that this issue is known for this plugin, but only on OSX. Couple of people reported it, but there's nothing obvious wrong with the plugin. Just asking for clues if this is indeed a plugin problem, or somewhere below in VS Code and OSX.

Any help appreciated.

**Comment by isidorn** [comment]
I believe this is an issue with the plugin. Let's wait for response on this issue before we make any further action here
https://github.com/Pure-D/code-d/issues/29

ping @joaomoreno

**Comment by joaomoreno** [comment]
It would be great to have been provided better repro steps. I had to install and/or `dfmt`, `dmd`, `dub`, `dscanner`, `workspace-d` on my system. I then had to figure out how to get a functional [D workspace](https://gist.github.com/joaomoreno/4d8e74ba550b1b0e6c3c) set up...

I am now able to repro. Will come back with more information.

**Comment by joaomoreno** [comment]
@isidorn this is neither `needs more info` nor `upstream`.

**Comment by joaomoreno** [comment]
Closing on our side, full explanation in Pure-D/code-d#29.

**Comment by serhiisol** [comment]
Have similar problem with Typescript or javascript in general. If I'll work with VSCode more than 1hr, intellisense just stops working showing me "loading..." and nothing else, reboot of VSCode helps only.

**Comment by slender9168** [comment]
did you manage to solve the issue ?

Thanks

**Comment by alexdmejias** [comment]
as a quick fix, the issue seems to get resolved if you run the 'reload the window' command

**Comment by Alonski** [comment]
Reloading the window fixed this once then back to loading forever 😞

**Comment by RoestVrijStaal** [comment]
@Alonski No, it doesn't

**Comment by slender9168** [comment]
@RoestVrijStaal  this worked for me, hope it helps:
https://github.com/Microsoft/vscode/issues/26594
