### ISSUE TITLE
Provide a way to tell if a TextEditor is part of a diff "tab" and which side it is

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#36019]
Currently there doesn't seem to be any way for an extension to know if a `TextEditor` is part of a diff tab (other than a hack which assumes that a `viewColumn` of `undefined` is a diff), nor any way to know which side an editor represents.

I would love this ability for GitLens because if I could tell if an editor is part of a diff and which side it is, I could provide a much more seamless experience for navigating forward and backward diffs. This is related to this comment https://github.com/Microsoft/vscode/issues/16707#issuecomment-305016864

Reproduces without extensions: No

**Comment by egamma** [comment]
// CC @joaomoreno 
As a workaround... The scheme of a document differs in the diff editor:
editor.document.uri.scheme === "file" when it is the editable side
editor.document.uri.scheme === "git" when it is the read only side.
However, the use of the "scheme" git is an implementation detail.

**Comment by eamodio** [comment]
Unfortunately that won't really work for my usage -- because you could be comparing `file` to `file`, or I could be comparing my own scheme `gitlens-git` (for file revisions) to a `file` or another `gitlens-git`.

**Comment by StingyJack** [comment]
@eamodio - does what you mean eventually result in some visual indication of which of these windows are the local or remote?

![image](https://user-images.githubusercontent.com/15381181/32188536-7ecf5dd4-bd7e-11e7-90c6-9d16187f2680.png)

**Comment by eamodio** [comment]
Not sure this is needed to know that -- the Git extension could change the title of the diff tab to be anything it would like.

**Comment by eamodio** [comment]
Any chance this can be bumped up? I hit this limitation very often in trying to provide GitLens features.
