### ISSUE TITLE
Attempting to use window.onDidChangeWindowState causes proposed api error

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#36010]
- VSCode Version: Code - Insiders 1.18.0-insider (dcd1aa35dfa590b4a528e1ab55e957002f430f17, 2017-10-10T05:26:33.683Z)
- OS Version: Windows_NT x64 10.0.16299
---

I'm trying to take advantage of the new `window.onDidChangeWindowState`, which as far as I can tell is no longer a proposed api, but every time I start debugging with it referenced in code I get the following error prompt

> Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api eamodio.gitlens.

According to the [docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.onDidChangeWindowState) this should be available for use.

//cc @jrieken 

Reproduces without extensions: No

**Comment by eamodio** [comment]
It looks like this is the culprit https://github.com/Microsoft/vscode/blob/a627a95c4d78684e3285107c428b9cd2a151761d/src/vs/workbench/api/node/extHost.api.impl.ts#L349-L351

**Comment by joaomoreno** [comment]
Oh no!!!

**Comment by jrieken** [comment]
We used to have a big, bold warning on startup... But, yeah I agree we could check if some labeled as proposed isn't defined `vscode.d.ts`

**Comment by joaomoreno** [comment]
I'll leave this assigned to October. If there is another recovery release, we'll make sure to put it in it. cc @egamma

**Comment by eamodio** [comment]
@joaomoreno thanks! You just answered my next question :)

**Comment by joaomoreno** [comment]
@eamodio There will be another recovery release, so this will go in!

**Comment by jrieken** [comment]
verified via code review
