### ISSUE TITLE
title doesn't change when switching open files via tabs

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#36018]
- VSCode Version:  VSCode 1.18.0-Insider
- OS Version: Win7 64bit

Steps to Reproduce:

1.Open VSCode, and open a few files.
2.switch open files via tab, the title doesn't change to the right file path.
3.if I change the size of the VSCode window, or minimize then maximum, the title is refreshed to the currently open file path. 

my settings:
{
    "workbench.activityBar.visible": false,
    "files.autoGuessEncoding": true,
    "editor.minimap.enabled": false,
    "workbench.colorTheme": "Visual Studio Light",

    "editor.rulers": [
        120
    ],
    "editor.renderLineHighlight": "all",
    "editor.renderWhitespace": "all",
    "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}",

    "workbench.colorCustomizations": {
        "tab.border": "#00F",
        "tab.activeBackground": "#F99BC5",
        "tab.inactiveBackground": "#E7E7EF"
    }
}

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
