### ISSUE TITLE
Please, return default font for Terminal.

### ISSUE THREAD

**Issue by makepizza** [Microsoft/vscode#36014]
- VSCode Version: 1.17.1
- MacOS Version: 10.13.1

![screen shot 2017-10-11 at 1 19 57 pm](https://user-images.githubusercontent.com/25575840/31420789-fe66d11e-ae86-11e7-9efd-c915250f646c.png)

**Comment by Tyriar** [comment]
Could you elaborate a little? What's the issue exactly?

Also is this macOS?

**Comment by makepizza** [comment]
@Tyriar Sorry, yes MacOS (topic edited). Font of integrated terminal became different from editor's font. When i try to use "terminal.integrated.fontFamily": "Menlo" it has no effect at all. Font in editor: Menlo.

**Comment by ivan-ha** [comment]
same discussion here #35991

**Comment by Tyriar** [comment]
Thanks, closing as duplicate of https://github.com/Microsoft/vscode/issues/35991
