### ISSUE TITLE
Ctrl+Tab to switch code tabs gets confused and sometimes I lose a code window

### ISSUE THREAD

**Issue by icuurd12b42** [Microsoft/vscode#36021]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

So I've been using Code for a few weeks and I use ctrl+tab to switch code tabs quite a lot and I'm faced often with confusing moments where ctrl+tab is not selecting the right code; like the code I want is supposed to be 1 or 2 ctrl tabs over but it's way out of order... The adverse effect of a bad switch (wrong file) is me editing the wrong file if they are similar and did not notice the wrong switch

The other weird thing is having the code window I just switched from disappearing from the opened tabs completely.

I don't know how to reproduce this... as it happens I am just surprised I cant find my other code tab anymore and I have not seen any pattern aside maybe it happens more often when I load another file from the tree view.... just use ctrl+tab for a few days as your main means of code tab navigation...

Oh, I have auto save ON in case you are wondering why I'm not seeing any save message upon a close

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.2.17
code-runner|for|0.7.2
vscode-autohotkey|sle|0.2.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@icuurd12b42 the order of Ctrl+Tab is always in MRU (most recently used) so it can well be that the tab you are getting to is not in spatial order, but in recently used order. As an alternative you could pick editors via the Switch Editor commands:

![screen shot 2017-10-11 at 10 09 23](https://user-images.githubusercontent.com/900690/31428777-46591416-ae6c-11e7-8194-eeaf5b7a6636.png)
