### ISSUE TITLE
Vscode 1.17.0 appears chinese font disorder problem in integrated terminal 

### ISSUE THREAD

**Issue by fychinesepjj** [Microsoft/vscode#36026]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
python|don|0.7.0
vscode-html-css|ecm|0.1.8
json-tools|eri|1.0.2
auto-rename-tag|for|0.0.14
sass-lint|gle|0.0.4
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.5
code-beautifier|mic|1.7.2
csharp|ms-|1.12.1
dust|nem|0.0.1
vscode-icons|rob|7.15.0
gitblame|wad|2.2.0

---

Steps to Reproduce:

1.  Vscode' new version(1.17.0) appears chinese font disorder problem in integrated terminal 

![img](https://user-images.githubusercontent.com/5492785/31425662-caecc42c-ae92-11e7-8a9f-8ba03aed7444.png)

after auto upgraded.

Reproduces without extensions: Yes/No

**Comment by meowao** [comment]
已经修复了 更新就好了

**Comment by fychinesepjj** [comment]
I have upgraded to 1.17.1.
problem have fixed.
thanks !!!
