### ISSUE TITLE
Window rendering is garbaged on the right side 

### ISSUE THREAD

**Issue by cbezenco** [Microsoft/vscode#36028]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
json-tools|eri|1.0.2
beautify|Hoo|1.1.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-docker|Pet|0.0.18
html-css-class-completion|Zig|1.10.0

---

Steps to Reproduce:

1. launch VS Code... it immediately appear. I tried to switch to one screen. The garbage is still here.
![capture](https://user-images.githubusercontent.com/12773102/31426563-240a7f7e-ae64-11e7-92b2-1e78c75c5c34.JPG)

2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
What is shown on the right is the so called 'minimap' it shows a birds eye view of the file. You can disable the minimap by setting "editor.minimap.enabled" to false.
