### ISSUE TITLE
Windows - Terminal font change between 1.17 and 1.17.1

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#36025]
The new one is smaller and I find it harder to read.

1.17
![image](https://user-images.githubusercontent.com/172399/31425228-9a334a06-ae5e-11e7-9c88-bd382567eeca.png)

1.17.1
![image](https://user-images.githubusercontent.com/172399/31425241-ae84ef50-ae5e-11e7-96ec-dd740dd0bbfa.png)

**Comment by adgllorente** [comment]
Same as @enricomingardo.

**Comment by fpipita** [comment]
Same issue as @egamma on Fedora 26 / GNOME 3.24.2.

**Comment by ShogunPanda** [comment]
Me too, OSX with and without retina

**Comment by osdavison** [comment]
I have the same issue on Windows 7

**Comment by sdemura** [comment]
Manually setting `"terminal.integrated.fontFamily": "Menlo"` doesn't seem to do anything either.

VS Code 1.17.1
OS X 11.12.6

**Comment by gustavosotnas** [comment]
Same problem here, using VS Code 1.17.1 in a Windows 10, build 1703. Even using other command line shells (like `bash`) and manually setting `fontFamily` and `fontSize`, the result is the same: a "condensed" font.

![Terminal font issue](https://user-images.githubusercontent.com/9777954/31443020-987c4784-ae6e-11e7-8bea-eec1f7f678df.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35991
