### ISSUE TITLE
ExtensionDevelopment: breakpoints sometimes do not get hit

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#36036]
1. Set a breakpoint in your extension
2. Start debugging it, try to hit the breakpoint -> does not get hit
3. Set the breakpoint again while you are debugging -> it gets hit

Please note that I can not reproduce this for the simplest extension sample but only saw this for @egamma npm runner extension on his win machine https://github.com/Microsoft/vscode-npm-scripts

I though #36035 might be related however I still have the old code which should treat the wrong event properly so there might be some other root cause to this,

**Comment by egamma** [comment]
Adding the `important` label since it is a regression in insiders from 1.17.1.

**Comment by roblourens** [comment]
I can't repro it, just by setting a breakpoint in `activate` in vscode-npm-scripts on windows. Really nothing has changed in the debug adapter since 1.17.

Can you take a trace for me with `"trace": true`? It writes the log file path to the debug console.

**Comment by roblourens** [comment]
Does this still repro? I haven't been able to repro it. Please collect a trace if it does.
