### ISSUE TITLE
Visual artifacts in terminal

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#36037]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.4-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-docker|Pet|0.0.18
python|don|0.7.0
restructuredtext|lex|38.0.0
hg|mrc|1.1.7
language-gettext|mro|0.0.2
qub-xml-vscode|qub|1.2.8
sass-indented|rob|1.4.2

---

Steps to Reproduce:

1. Open integrated terminal. You can see the artifacts (little yellow dots) right away: 
![captura de pantalla de 2017-10-11 10-34-29](https://user-images.githubusercontent.com/973709/31429975-cafc0612-ae6f-11e7-9f1f-21e3488055fc.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Upgrading to 1.17.1 should fix this (provided you're on Fedora)
