### ISSUE TITLE
vscode intermittently doesn't find typescript type definition files (*.d.ts) in project

### ISSUE THREAD

**Issue by ajaysagar** [Microsoft/vscode#36039]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|1.0.10
debugger-for-chrome|msj|3.3.1

(2 theme extensions excluded)

---

This issue happens intermittently, I have *.d.ts files in my project, the typescript compiler can see them and the project builds successfully. However, vscode intermittently does not find the types and shows red squiggly lines under types in some/all files. Around 50% of the time, the types are resolved correctly and I can click into the types to go to their declarations. This seems like a bug to me, since it is intermittent.

**Comment by mjbvz** [comment]
Sorry for the delayed response.

Can you please try out [VS Code insiders](https://code.visualstudio.com/insiders/). This includes a new version of TypeScript that fixed a number of issues similar to this.

If you still see this problem when using VS Code insiders, can you reliably reproduce this problem? If so, can you please share some example code or a small example project that causes it to occur?
