### ISSUE TITLE
Smoke test Red Hat Distros

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3603]
Smoke vscode test on the following distributions

- [x] ~~RHEL6~~ (https://github.com/Microsoft/vscode/issues/1056): Does not work without compiling from source (of which there are other problems).
- [x] RHEL7: Works
- [x] CentOS 7: Works
- [x] Fedora 23: Works

**Comment by Tyriar** [comment]
Installed RHEL6 and ran in to some issues.

- Hit the issue described here https://github.com/Microsoft/vscode/issues/1056 and did a little research, it looks like building on a RHEL machine will fix this.
- Installed prereqs:

 ```
 curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
 yum install nodejs
 npm install -g mocha gulp
 yum install gcc-c++
 yum install libX11-devel.x86_64
 ```

Currently hitting an issue when installing npm deps

**Comment by Tyriar** [comment]
Same issue with RHEL seems to occur on Atom https://github.com/atom/atom/issues/2177. I think RHEL7 should work [since it comes with gcc 4.8](https://access.redhat.com/solutions/19458) (C++11).

**Comment by rebornix** [comment]
Install GCC 4.8 in RHEL6 per http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos . But still get problems with `oniguruma@6.0.1` installation.

**Comment by ykne** [comment]
Are there any updates for making this work on RHEL6.x?

**Comment by Tyriar** [comment]
@ykne no updates, we support RHEL7+ https://code.visualstudio.com/docs/supporting/requirements

Snap package support may change this, I'm not sure https://github.com/Microsoft/vscode/issues/5458
