### ISSUE TITLE
Autocomplete for Unity events not working

### ISSUE THREAD

**Issue by torquemadaaa** [Microsoft/vscode#36032]
- VSCode Version: 1.17.1
- OS Version: WIndows 10, build 15063.540

Extensions:
1. C/C++
2. C#
3. vsicons

Steps to Reproduce:

1. Open Unity project in VS Code
2. Try to type "On..."

Reproduces without extensions: No

VS Code provides autocomplete for references in the Unity project, except Unity-specific events:
![image](https://user-images.githubusercontent.com/25992594/31427882-83a56c5c-ae71-11e7-9c2e-4ba677e5c5ac.png)
But in VisualStudio:
![image](https://user-images.githubusercontent.com/25992594/31428092-3f710a54-ae72-11e7-9303-6cc227161e3e.png)
Project is the same, no changes in source code.
Visual Studio has "Tools for Unity" installed.

**Comment by egamma** [comment]
This is an issue in the C# extension, pls report the issue in this repository https://github.com/OmniSharp/omnisharp-vscode
