### ISSUE TITLE
Click F5 has no response on vscode when there is no launch.json file in current workspace

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#36045]
In the latest vscode-insider (2017-10-11), if no launch.json file exists in current workspace, click `F5` and it seems nothing happens. Is there any possible to pop up the `Add Configuration` dropdown menu to guide user?

**Comment by isidorn** [comment]
Thanks for finding this issue. I have pushed a fix and you can pick it up in tomorrows insiders

**Comment by testforstephen** [comment]
It works at latest insider. thanks.

**Comment by isidorn** [comment]
Thanks for trying out, I wil ladd verified label
