### ISSUE TITLE
missing 1.17.1 package on https://packages.microsoft.com/repos/vscode/

### ISSUE THREAD

**Issue by ulrichSchreiner** [Microsoft/vscode#36048]
hi,

i use `https://packages.microsoft.com/repos/vscode/` to install vscode in my container, so i can specify an exact version to be installed in the container.

the 1.17.0 version can be installed, but the 1.17.1 version is not available. at the momemt of writing this issue the contents of https://packages.microsoft.com/repos/vscode/pool/main/c/code/ show that 1.17.1 is missing.

**Comment by chrmarti** [comment]
Published .deb and .rpm now.

**Comment by sattellite** [comment]
Update repodata for .rpm please

https://packages.microsoft.com/yumrepos/vscode/
