### ISSUE TITLE
使用创建新文件功能Bug

### ISSUE THREAD

**Issue by itzx** [Microsoft/vscode#36049]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
vscode-markdownlint|Dav|0.10.1
vscode-great-icons|emm|2.1.16
beautify|Hoo|1.1.1
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1
view-in-browser|qin|0.0.5

---

Steps to Reproduce:

1.资源管理器，项目文件夹收起的状态下，单击右侧新建文件图标，无反映，多次单击。
2.再次展开项目文件夹，发现里面增加了好多新增默认空名文件。

Reproduces without extensions: Yes/No

**Comment by kzhui125** [comment]
looks like https://github.com/Microsoft/vscode/issues/35923

**Comment by egamma** [comment]
@kzhui125 thanks for jumping in. Closing this is issue as a duplicate.
