### ISSUE TITLE
New macOS icon is too small

### ISSUE THREAD

**Issue by muttoni** [Microsoft/vscode#36041]
- VSCode Version: 1.17
- OS Version: macOS / version irrelevant

Love the new icon, but it's not proportional to other app icons. Would it be possible to resize it or make full use of available icon space to enlarge it so it doesn't look out of place? See image below.

<img width="109" alt="icon" src="https://user-images.githubusercontent.com/27052451/31431138-227fd6ae-ae73-11e7-83df-3a4afabd9a48.png">

**Comment by cornedor** [comment]
I thinks this is because you have a dark background, if you look at this screenshot you can see that it is the full size.
<img width="135" alt="screen shot 2017-10-11 at 15 46 30" src="https://user-images.githubusercontent.com/570297/31444059-63a3773a-ae9b-11e7-960c-6d9923fd123f.png">

**Comment by muttoni** [comment]
@cornedor , good point. I'll leave it to the designers to evaluate if it's worth fixing... maybe there's a way to make it dark-compatible by adding a light border. Interesting that no other icon in my application bar has this issue (including ST3 which uses an almost identical color scheme)

**Comment by chrisdias** [comment]
Will track this issue here: https://github.com/Microsoft/vscode/issues/36692
