### ISSUE TITLE
Open release notes in a new window instead of tabs

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#36040]
- VSCode Version: 1.17.1
- OS Version: 10.12.6

**Steps to Reproduce:**
1. Upgrade VSCode
2. A tab for release notes opens in every window

**Reproduces without extensions:** Yes

**Proposal**
Open a new window for release notes instead of opening a tab in every window.

**Comment by joaomoreno** [comment]
#25800

**Comment by dmlemos** [comment]
Missed that one 👍
