### ISSUE TITLE
Only the first two installed extensions are shown in 'Extensions' Tab when 'Recommended' section is expanded

### ISSUE THREAD

**Issue by thierer** [Microsoft/vscode#36042]
Just upgraded to 1.17.1 (from 1.16.1, so I don't know if this issue was already present in 1.17.0) and found that only the first two installed extensions are shown in the 'Installed' section of the 'Extensions' tab when first entering the tab and the 'Recommended' section is expanded. (The total number of installed extensions that is displayed on the right side of the section header is correct). 

Collapsing and expanding the 'Installed' section does not help. All installed extensions are only shown after collapsing 'Recommended':

![vscode-extensions](https://user-images.githubusercontent.com/240625/31431642-8cda2918-ae74-11e7-8b7e-13bf5e8cfa92.gif)

Is this on purpose? If so, I find it annoying because I'm usually more interested in my installed extensions (to disable/enable them, check the help, ...) than in recommendations... 

A an aside, I find the big blank vertical space that stays after both sections are expanded unnecessary, but I just checked and that was already there in 1.16.1.

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.13.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-eslint|dba|1.3.2
python|don|0.7.0
json-tools|eri|1.0.2
Go|luk|0.6.66
cpptools|ms-|0.13.1

**Comment by egamma** [comment]
All the installed extensions are shown and there is scroll bar shown in the installed extensions section. So all you need to do is to either scroll or resize the installed extensions section.

**Comment by thierer** [comment]
Ok, I wasn't aware that it was possible to change the size of the sections, thanks!

Still, something has changed between 1.16.1 and 1.17.1: I just checked that while in 1.16.1 the size of the 'Installed' section was remembered between restarts, that doesn't work for me on 1.17.1: If I resize it, it's back to 2 entries after a restart.

**Comment by egamma** [comment]
@thierer the implementation of the sections has changed. can you please file a separate issue on the sizing problem.
