### ISSUE TITLE
Add environment variable to know the integrated terminal number?

### ISSUE THREAD

**Issue by FezVrasta** [Microsoft/vscode#36057]
I would like to use tmux to prevent my terminals from closing when I close VSCode and be able to restore them when I open the same project.

The only problem is that, while with the project I can use the `pwd` result to get an unique ID, there's no way to know which terminal number I'm viewing (I'm talking about the multiple terminals support, where each terminal has its own number from 1 to infinite).

Would it be possible to expose an environment variable such as `VSCODE_TERMINAL_NUMBER` just to allow me to manage multiple terminals of the same project?

For further reference read 
https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by Tyriar** [comment]
Would rather not add something like this as the number changes when terminals are destroyed so it may be inaccurate. Couldn't you query tmux to see if the tmux session is already in use or something like that?

**Comment by FezVrasta** [comment]
Thanks for the suggestion, it may work.
