### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by HuRainMan** [Microsoft/vscode#36054]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typings-installer|ben|0.2.0
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
vscode-npm|fkn|3.3.0
text-transform|flo|0.1.0
vscode-auto-open-markdown-preview|hnw|0.0.4
expand-region|let|0.1.1
code-beautifier|mic|1.7.2
easeserver|mil|0.1.3
easy-less|mrc|1.4.5
material-icon-theme|PKi|2.2.2
view-in-browser|qin|0.0.5
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. At first i'cant open the browser, errors occured ! ==> whate the hell ? this is a sad story !!!! 
2.I'think vs code just soso... ! to many things that need to do; hurry up 

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
>At first i'cant open the browser, errors occured 

Thank you for the feedback. Can you please elaborate what the problem here is, may be you can illustrate it with a screen shot and describe the errors.

**Comment by egamma** [comment]
Please reopen the issue when you can provide more detailed information on how to reproduce the problems.

**Comment by HuRainMan** [comment]
error had been resolved

2017-10-11 22:01 GMT+08:00 Erich Gamma <notifications@github.com>:
