### ISSUE TITLE
Please update octicons from 3.1.0 to 6.0.1

### ISSUE THREAD

**Issue by rwnkl** [Microsoft/vscode#36053]

**Comment by jrieken** [comment]
Unfortunately not so easy because some octicons have been removed and hence updating might likely break some extensions that rely on them

**Comment by Gruntfuggly** [comment]
Is there a plan going forwards with this? I just tried to use an octicon and it came up blank. I couldn't work out why until I checked the versions being used, which led me here.

From the change log, it looks like some of the removed icons are just renamed. Would it be possible to add a simple 'redirect' to return the new icon if the old name is used? Similarly, if an icon has genuinely been removed, could a placeholder be returned? In fact, it would probably be nicer to return *something* if a bad icon is named, rather than leaving a blank space.

**Comment by jrieken** [comment]
> would it be possible to add a simple 'redirect' to return the new icon if the old name is used?

Hm... Do you have a pointer/release notes that describe these changes?

**Comment by Gruntfuggly** [comment]
I was just looking through here:
https://github.com/primer/octicons/blob/master/CHANGELOG.md

**Comment by Gruntfuggly** [comment]
Great - thanks!

**Comment by jrieken** [comment]
So, this would be the compat table and the good news is that no extension seems to use those three removed icons. The bad news is that octicons are now shipped as npm module which we cannot consume at the level at which we define the `OcticonLabel`

```
const _compatMapping = {
	// https://github.com/primer/octicons/blob/master/CHANGELOG.md#320-november-6-2015
	'screen-normal': '',
	'screen-full': '',
	// https://github.com/primer/octicons/blob/master/CHANGELOG.md#340-january-22-2016
	'color-mode': '',
	// https://github.com/primer/octicons/blob/master/CHANGELOG.md#600
	'ellipses': 'ellipsis',
	//https://github.com/primer/octicons/blob/master/CHANGELOG.md#601
	'kebab-veritcal': 'kebab-vertical',
	// https://github.com/primer/octicons/blob/master/CHANGELOG.md#octicons_node-700
	'file-text': 'file',
	'mail-reply': 'reply'
};
```

**Comment by bpasero** [comment]
@jrieken we already have all the octicon resources checked in to our sources, so why is the fact that Octicons now ship as an NPM module an issue for us moving forward? Can we not just do the same?

![image](https://user-images.githubusercontent.com/900690/40980375-87546aac-68d8-11e8-99ce-df1dd0e8f8ae.png)

**Comment by bpasero** [comment]
Maybe @misolori has an idea on how to do that. I wonder if we can convert the set back to a font so that it is easy for us to consume it as we did before.

**Comment by misolori** [comment]
@chryw and I talked about how to convert the new svgs back into an icon font. We'd need to setup a project (probably in node) that would have the right modules to convert svgs into icons. @chryw [already has a similar project](https://github.com/chryw/vsfi) but we'd need to:
- Format the octicons file names to include their unicode
- Format the less/sass templates to match the old styles format
- Audit the changes from the old version of Octicons (renames/deletions/additions)
- Map all of the changes
- Also create local ttf file for users to install

This would take some time to setup, but nonetheless it is **very** hacky. Github has already [moved towards using svgs](https://blog.github.com/2016-02-22-delivering-octicons-with-svg/) so this would be a patch that we'd need to maintain.

One last thing to consider is _if_ in the future we decide to create our own icon set (related to #8017) then this would be deprecated. I'd be in favor of putting our efforts into creating our own icon set that can be consumed by everyone.
