### ISSUE TITLE
Rectangular area in html-document does not receive any mouse events

### ISSUE THREAD

**Issue by rwnkl** [Microsoft/vscode#36051]
When you display a html document (using complex command vscode.previewHtml), a rectangular area in the document does not receive any mouse events.
This rectangle is located in the upper right corner and is located under the 1st menu item of the Editor menu (Coords: position: absolute; width: 220px; height: 28px; top: 1px; right: 28px;)
This bug did not occur in version 1.16

- VSCode Version: 1.17
- OS Version: Windows 10 Prof 64 Bit

Steps to Reproduce:

1. Create an extension with complex command vscode.previewHtml
2. Show the attached html-code
3. Move mouse cursor
Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This seems to be caused by the find widget in the webview. Will take a look at hiding it properly
