### ISSUE TITLE
Terminal: lines are not well rendered

### ISSUE THREAD

**Issue by paeolo** [Microsoft/vscode#36059]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.14-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.13.1

---

Just updated to 1.17.0 and I have a new issue with the terminal. The lines are not well rendered (see the screenshot). I am using fedora 26 with gnome 3/X11 and my computer have a 1920x1080px screen resolution.

Steps to Reproduce:

1. Launch Code and open the terminal
2. The lines of the terminal are not rendered properly.

![capture d ecran de 2017-10-11 13-34-07](https://user-images.githubusercontent.com/32302162/31438594-f53a1496-ae88-11e7-8567-18f40212049f.png)

Reproduces without extensions: Yes

**Comment by TheDutchCoder** [comment]
Same here, there's something wrong with the font rendering, it's incredibly narrow, so I assume these issues are all related:

![image](https://user-images.githubusercontent.com/1668207/31441503-5b62634a-ae61-11e7-9796-2e59378aec4b.png)

**Comment by Noitidart** [comment]
Same on Windows 10 system for me:

## Here is how it looks now:

![how it looks now](https://user-images.githubusercontent.com/6372489/31444950-1710b354-ae52-11e7-8981-e7d7d84e64fc.jpg)

## This is how it used to look, expected look is this:

![how it used to look](https://i.imgur.com/zzSTc2c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35991
