### ISSUE TITLE
Terminal hangs many times when Ctrl+C is pressed.

### ISSUE THREAD

**Issue by ankur-birdeye** [Microsoft/vscode#36056]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
react-redux-react-router-snippets|dis|0.3.5
gitlens|eam|5.6.0
tslint|eg2|1.0.10
prettier-vscode|esb|0.24.0
path-autocomplete|ion|1.6.1
vscode-styled-components|jpo|0.0.8
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|3.3.1
code-settings-sync|Sha|2.8.3
stylelint|shi|0.29.1
vscode-react-native|vsm|0.4.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/9347
