### ISSUE TITLE
Go To Defination not working with React component

### ISSUE THREAD

**Issue by ue** [Microsoft/vscode#36055]
When i get new version it was crush.

- VSCode Version: 1.18.0-insider (also without insider version)
- OS Version: win 10

Steps to Reproduce:

1. Open a react component and go to defination (crtl+clik or f12) a variable or something. it`s not working

Notice!: It worked on a simple project, but didn't work on a large project which I'm currently working on.

Reproduces without extensions: Yes/No
Yes

**Comment by mjbvz** [comment]
Does your project have a `jsconfig` or `tsconfig` file? Can you please share some example code?

You may also want to try enabling type checking for the file where this is not working: https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files This can help track down issue like this

**Comment by ue** [comment]
No it not has any ` jsconfig ` or ` tsconfig ` . I can`t share my code base. But I`ll try to quick example for that.

**Comment by mjbvz** [comment]
Thanks. Please try [creating a jsconfig](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) as well. This file tells VS Code to treat all javascript files in your workspace as part of the same project

**Comment by ue** [comment]
You right maybe but its work very well before latest version. When I get latest version this feature broken. I guess thats not interest with config.

**Comment by ue** [comment]
This problem already fixed in Version 1.18.0 - insider. Thnx a lot for your time. So you can close this issue.  @mjbvz
