### ISSUE TITLE
Task Master does not recognize tasks

### ISSUE THREAD

**Issue by FanTesy** [Microsoft/vscode#36050]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
task-master|ian|0.1.39

---

Steps to Reproduce:
I use VS Code with a extend, the extend name is Task Master. In the last two versions, I've found that this extension does not identify tasks. Here is the
![tim 20171011181306](https://user-images.githubusercontent.com/20451745/31434808-0bf99086-aeb0-11e7-8f06-9fc17fc2fcf4.png)
 screenshot
1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@FanTesy please file the issue against the owner of the TaskMaster extension.
