### ISSUE TITLE
1.7 / 1.7.1 CoffeScript/Knockout Syntax Colour changed

### ISSUE THREAD

**Issue by NeilBagley** [Microsoft/vscode#36058]
Steps to Reproduce:

1. Using Dark+ theme, Type the following in a coffescript file "self.test = ko.observable(null)"
2. Notice the "ko" is now blue when previously it was white.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This has to do with the update of the Coffee script grammar which is originating from https://github.com/atom/language-coffee-script.

The Dark+ uses blue for variables declaration and reference, and the new behaviour looks like the correct behaviour.
BTW, you can customize the token colors in the settings:
```
    "editor.tokenColorCustomizations": {
        "variables": "#FF0000"
    }
```
