### ISSUE TITLE
Holding Command+S keeps saving the file

### ISSUE THREAD

**Issue by cornedor** [Microsoft/vscode#36062]
- VSCode Version: 1.17.1
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open a file in vscode and use a file watcher to watch it for changes
2. Press and hold Command+S
3. The watchers keeps triggering

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This is how our keybindings work, I do not think we want to change that. Closing "as designed".
