### ISSUE TITLE
Error: extensions host terminate accidentally（扩展宿主意外终止）

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode#36064]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.16.0
html-class-suggestions|And|1.0.7
htmltagwrap|bra|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
gitlens|eam|5.6.0
vscode-html-css|ecm|0.1.8
react-native-react-redux|EQu|1.4.1
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.6.1
vscode-random|jre|1.3.1
vue|liu|0.1.5
vetur|oct|0.9.11
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
stylelint|shi|0.29.1
open-in-browser|tec|1.1.0
vscode-react-native|vsm|0.4.2
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. start the vscode it reports errors an once

Reproduces without extensions: No

![image](https://user-images.githubusercontent.com/11827786/31440703-5f5d3c9c-aec3-11e7-93fb-0d8fa0d9351b.png)

**Comment by Jancat** [comment]
I disable the extensions that report error in the console log and then vscode show erros as the same.

![image](https://user-images.githubusercontent.com/11827786/31440929-23eadc22-aec4-11e7-9b4c-d9248c1c565c.png)

**Comment by mjbvz** [comment]
@Jancat Please try disabling all extensions. Another one may be causing crashing the extension host silently

**Comment by Jancat** [comment]
@mjbvz Why does the error happened in extensions crashing? Should I try out the problematic one  among my extensions?

**Comment by mjbvz** [comment]
Yes, please disable all extensions and then try re-enabling the ones that may be causing this issue to track down which one is responsible

**Comment by Jancat** [comment]
Ok, that's all I can do
