### ISSUE TITLE
Introduce setting to hide hover tooltips on file lists, tabs etc.

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#36061]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
gherkin-indent|Ara|2.0.0
vscode-bad-code-highlighter|bha|0.1.6
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-turtle|fei|1.0.30
vscode-sort|hen|0.2.5
beautify|Hoo|1.1.1
format-indent|Kas|1.3.0
string-manipulation|mar|0.2.0
vscode-apache|mrm|1.1.1
vscode-duplicate|mrm|1.2.0
oracle-plsql|myc|1.0.3
java|red|0.11.0
selectline-statusbar|tom|0.0.2
gitblame|wad|2.2.0
twig|wha|1.0.2

There is a full pfile path tooltip on the editor tab, which can be a little annoying and not usefull, since I have full path in the title. `editor.hover: false` has no effect.

---

Steps to Reproduce:

1. open few files
2. hover over tab
3. tooltip with full file path appears

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
editor.hover is for the editor as the name suggest.
This is as desgined behavior, thus closing.

**Comment by PunchyRascal** [comment]
Well by submitting this issue I didn't try to contradict whether or not the behaviour is as designed, I am saying there could be a setting to turn this off. As for the editor.hover - for me the whole thing is an editor, so I don't know how to tell what is and isn't editor.

**Comment by sunew** [comment]
would be super with a setting to turn this off. Its too much information and just plain distracting - you know where your workspace is located.

**Comment by sefaYavuz** [comment]
This is real annoying indeed, this makes it hard to see the files benath the tooltip and the constant showing hiding of the tooltip is not helping either.
