### ISSUE TITLE
Error while installing vscode via ubuntu software center. Also attached error log.

### ISSUE THREAD

**Issue by araviaravi** [Microsoft/vscode#36074]
- VSCode Version: code_1.17.1-1507645403_amd64.deb
- OS Version: Ubuntu 16.04.3 64bits

Steps to Reproduce:

1. Download .deb for your vscode website 
2. add it to gdebi package installer
3. Check Lintian output tab

Reproduces without extensions: Yes/No Not applicable

I am using Ubuntu 16.04. I am getting this output of error. I have managed to install via GDebi package manager. But not sure how stable it is now. The below is the error output of Lintian.

[Lintian.txt](https://github.com/Microsoft/vscode/files/1376149/Lintian.txt)

I hope this could help you to make it install via ubuntu software center. Thanks for making opensource software and keep doing the great job.

**Comment by araviaravi** [comment]
Also include terminal installation procedure for linux os. This will help us troubleshoot installation error and solve the installation failure.

**Comment by Joel-hanson** [comment]
same trouble here. @araviaravi you method worked
like for .deb
`sudo dpkg -i <file>.deb`
`sudo apt-get install -f # Install dependencies` 

or for installing manually with the following script:

`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
`sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg`
`sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'`


`sudo apt-get update`
`sudo apt-get install code # or code-insiders`

**Comment by Tyriar** [comment]
Dupliate https://github.com/Microsoft/vscode/issues/20380
