### ISSUE TITLE
TextDocument#save resolves with false

### ISSUE THREAD

**Issue by jedmao** [Microsoft/vscode#3607]
According to [the TextDocument documentation](http://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument), the `save()` method returns a promise that should resolve to `true` when the file has been saved. Unfortunately, I have a promise that is resolving to `false`, which I presume means the file was not saved, but there is no indication as to why. Also, if there was an error, why didn't the `onRejected` callback get called with the error instance instead of the `onFulfilled` callback with a simple `false` value?

**Comment by bpasero** [comment]
@jedmao please provide a snippet for how to reproduce this.

**Comment by jedmao** [comment]
I'll do you one better. I have [a failing PR](https://github.com/editorconfig/editorconfig-vscode/pull/31) and [failing Travis-CI build](https://travis-ci.org/editorconfig/editorconfig-vscode/builds/114705101) that demonstrates the issue in [these lines](https://github.com/editorconfig/editorconfig-vscode/blob/e42908690e1908a21fd2e879d72d8ea397e5939c/test/index.test.ts#L67-L125):

```ts
const doc = await workspace.openTextDocument(filename);
assert.strictEqual(await doc.save(), true, 'saves file');
```

**Comment by bpasero** [comment]
@jedmao it also returns false if the file was not dirty, I have updated the docs.
