### ISSUE TITLE
Cursor styling normal selecting, vim mode selection 

### ISSUE THREAD

**Issue by palango** [Microsoft/vscode#36070]
- VSCode Version: 1.17.1
- OS Version: macOS 10.12.6

Not sure where to report this, but I guess styling is more a VSCode issue than the vim extensions bug.

Steps to Reproduce:

1. Make a selection (Shift + right arrow). Looks good as in screenshot 1
2. Enable vim mode, select a word example wise with `ve`. The selection end is at the cursor. The styling looks strange (screenshot 2)

Reproduces without extensions: No (needs VsVim)

![screen shot 2017-10-11 at 16 09 34](https://user-images.githubusercontent.com/90851/31445823-3d9a9646-ae9f-11e7-9ce0-c00a9ef7a92e.png)
![screen shot 2017-10-11 at 16 10 00](https://user-images.githubusercontent.com/90851/31445824-3db73238-ae9f-11e7-96fc-4f44c883b8b8.png)

**Comment by alexandrudima** [comment]
It's not clear what that thing is. Most likely it is an editor decoration that is set by the vim extension.

**Comment by rebornix** [comment]
IMO it's set by the Vim extension, please start from there.

**Comment by Chillee** [comment]
@palango To be clear, this is a VSCodeVim issue related to limitations with the VSCode api. Check here: https://github.com/VSCodeVim/Vim/issues/1590 and https://github.com/VSCodeVim/Vim/issues/1755 for history.

**Comment by Chillee** [comment]
@palango Also, I just realized that we were being very dumb with our stylings, so we've actually fixed this issue!

https://github.com/VSCodeVim/Vim/pull/2161
