### ISSUE TITLE
多行注释/** */不能自动添加*号

### ISSUE THREAD

**Issue by ToBegin** [Microsoft/vscode#36078]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
tslint|eg2|1.0.11
vsc-material-theme|Equ|1.0.4
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
atom-keybindings|ms-|3.0.2
vetur|oct|0.9.11
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0
shader|sle|0.2.4
JavaScriptSnippets|xab|1.5.0
markdown-pdf|yza|0.1.7
html-css-class-completion|Zig|1.10.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ZombieProtectionAgency** [comment]
>Multi-line comment / ** * / can not automatically add * # 36078

You will probably need to supply some more information. At least what language you are using and how what you are trying to do that is causing an issue.

**Comment by egamma** [comment]
@ZombieProtectionAgency thanks for jumping in.

**Comment by ToBegin** [comment]
疏忽了，语言是JavaScript，在vue文件中的Script的标签中使用，在纯js文件没有问题

**Comment by egamma** [comment]
Translated: Negligence, the language is JavaScript, vue file in the script used in the label, there is no problem in the pure js file

**Comment by octref** [comment]
This issue was moved to vuejs/vetur#467
