### ISSUE TITLE
Provide squiggles in .code-workspace file if the path is invalid

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#36079]
More details https://github.com/Microsoft/vscode/issues/35075

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35092 is related and I think we need to decide what to do here. Showing squigglies is one thing, but should we actually not surface entries to the workspace service that are files in the first place? This would for example not cause extensions to try to read entries as folders that are actually files.

The downside is that the only way of knowing for sure would be to stat each entry of the workspace before loading the workbench :-/

**Comment by isidorn** [comment]
To be honest I do not think this experince is that important.
Our main flow is that the user does not manually touch the `.code-workspace`, due to that getting in this situation is not trivial it is a corner case.

For this corner case I would just decoarte it in the explorer (as mentioned in the other issue) and also send it over to extensions. We could also have a check to see if it is a file before sending it over to extensions which would not be before loading the workbench.
