### ISSUE TITLE
Integrated terminal font looks distorted on Mac 

### ISSUE THREAD

**Issue by joelalejandro** [Microsoft/vscode#36076]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
emoji|Per|0.0.3
vscode-eslint|dba|1.3.2
gitlens|eam|5.6.0
vscode-codemetrics|kis|1.9.6
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
pdf|tom|0.2.0

---

Steps to Reproduce:

1. Open Code.
2. Open the integrated terminal.

![image](https://user-images.githubusercontent.com/118913/31452182-9216a310-ae84-11e7-9330-12b1b3ca1f2f.png)

![image](https://user-images.githubusercontent.com/118913/31452215-a70d14b6-ae84-11e7-924d-2e308656f49f.png)

Reproduces without extensions: Yes

**Comment by calrsom** [comment]
This is a definite regression in usability.  I noticed it right away.  I hope this gets fixed quickly!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35991
