### ISSUE TITLE
Cannot navigate top-level menu with keyboard

### ISSUE THREAD

**Issue by jschroedl** [Microsoft/vscode#36077]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
gitlens|eam|5.6.0
vscode-auto-open-markdown-preview|hnw|0.0.4
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
java|red|0.11.0
vscode-icons|rob|7.15.0
vscode-header-source|ryz|1.1.0
vscode-spotify|shy|2.2.1
perforce|sle|2.2.1

---

Steps to Reproduce:

1. Run Code on Windows, press Alt+F to show the File menu
2. Press the right arrow key. The Edit menu should now open but it does not.

Reproduces without extensions: Yes/No

**Comment by jschroedl** [comment]
This is not markdown-related. I had a .md file opened when I added this. I see no way to remove a tag.

**Comment by egamma** [comment]
This is a limitation of Electron, closing as an upstream issue.
