### ISSUE TITLE
Terminal font looks terrible

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#36086]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|2.2.2
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-todo-plus|fab|1.5.2
auto-rename-tag|for|0.0.14
icon-fonts|idl|1.8.2
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.3.1
vscode-todo-highlight|way|0.5.11

(3 theme extensions excluded)

---

Terminal font's look terrible in new update. its so hard to read

Reproduces without extensions: Yes/No

**Comment by prasanthnv** [comment]
![spectacle zt7638](https://user-images.githubusercontent.com/10536234/31457608-dee1a4c8-aeda-11e7-81d1-2b55c3a9ea99.png)

**Comment by prasanthnv** [comment]
Its okay in some eyes but its better for mine in the previous version

**Comment by Deilan** [comment]
Screenshot with an illustration of a difference between 1.17.1 and previous versions. Using git bash on windows 8.1 x64:
![image](https://user-images.githubusercontent.com/4777512/31459481-fc7ebde0-aecb-11e7-99c3-2a49b45f2b58.png)
My eyes are broken. :(

**Comment by ChaseOnTheWeb** [comment]
I'm seeing the same issue on a Mac. The characters look fuzzier and narrower (though their width is actually the same).

![Screenshot: top is Terminal, bottom is VSCode, same font and size](https://user-images.githubusercontent.com/783851/31459483-511cc2d8-ae91-11e7-935e-eea7d325b245.png)


See also #36076

**Comment by franky47** [comment]
Same issue here, VSCode 1.17.1, macOS 10.12.6, Retina screen:
<img width="766" alt="capture d ecran 2017-10-11 a 22 16 01" src="https://user-images.githubusercontent.com/1174092/31465169-6ab02518-aed3-11e7-8b26-8f314c2d188e.png">
1.16 left, 1.17 right

**Comment by simonhaenisch** [comment]
I also get this bug now when I type something and move the cursor back:

![image](https://user-images.githubusercontent.com/3410759/31467216-b7bbe6dc-af35-11e7-9670-51c7923e68ef.png)

![image](https://user-images.githubusercontent.com/3410759/31467206-a7f717d0-af35-11e7-9716-ee1c775e93c2.png)

Only happens directly after opening the terminal though.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35991

**Comment by franky47** [comment]
Not exactly a duplicate, the same problem exists on macOS too.

**Comment by robhaswell** [comment]
Menlo on OSX, size 10:

![screen shot 2017-10-12 at 11 05 03](https://user-images.githubusercontent.com/415486/31490831-3940e16a-af3d-11e7-9590-c5334560b732.png)

This used to be readable (identical to the editor), now it is not.

**Comment by Tyriar** [comment]
FYI #35991 was happening on all platforms, it was much less noticeable on macOS though as many more users have high DPI screens.

**Comment by prufrock123** [comment]
Hey @Tyriar , 

So this is fixed in the insider's build?  And will be fixed in a future patch? Just wanted to confirm as I see all the tickets closed out, despite the problem still existing.

Thanks for all you folks do! Love VSC.

**Comment by Tyriar** [comment]
@prufrock123 this one was fixed in 1.17.2, hope everything is fine now 😃

**Comment by prasanthnv** [comment]
not good as 1.17.0

**Comment by Tyriar** [comment]
@prasanthnv it should be very similar to 1.17.0, the main difference is that the characters no longer have their last pixel chopped off and can now overlap slightly (which are both good things)
