### ISSUE TITLE
launch.json "program" need '/'

### ISSUE THREAD

**Issue by charlesxsh** [Microsoft/vscode#3608]
When automatically generate a launch.json, "program": "${workspaceRoot}index.js"
It should be "program": "${workspaceRoot}/index.js"

**Comment by isidorn** [comment]
On what version of vscode are you seeing this? This should be fixed in the march release which will be out next week.

Can you share the `package.json` of your workspace?

**Comment by charlesxsh** [comment]
{
  "name": "= == =",
  "version": "1.0.0",
  "description": "= =",
  "main": "index.js",
  "scripts": {
    "test": "node index.js"
  },
  "author": "Shihao Xia",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.0",
    "express": "^4.13.4",
    "mongoose": "^4.4.4"
  }
}

**Comment by isidorn** [comment]
And on what version of vscode do you see this, I can not reproduce with the latest vscode.
I think this is already fixed in the march release - you could try it out in the march insiders release

**Comment by isidorn** [comment]
This should be fixed in the march realese
