### ISSUE TITLE
After update to 1.17.1 not work clang-command-adapter

### ISSUE THREAD

**Issue by vvzvlad** [Microsoft/vscode#36084]
- Operating System and version: Mac OS 10.13

- VS Code version: 1.17.1

- C/C++ extension version: 0.13.1

- clang command adapter extension version: 0.2.2

- step-by-step instructions to reproduce the issue:

open .c file, enter error code(   printf") ), wait... not work, no error messages. 

My settings files:
[settings.zip](https://github.com/Microsoft/vscode/files/1376646/settings.zip)

I reinstalled all extensions and restarted the program and the computer. The work did not resume.

**Comment by isidorn** [comment]
Please file this against the clang extension. Thank you

**Comment by vvzvlad** [comment]
To my regret, it seems that the problem is not in extension. I removed the mitaki28.vscode-clang extension and installed jbenden.c-cpp-flylint, which does the same, but includes not only clang but also cppcheck. The second extension does not work either.
It seems to me that something has happened to the interface for code validation extensions.
