### ISSUE TITLE
Changes visualizer in source control no longer works.

### ISSUE THREAD

**Issue by jzatarain** [Microsoft/vscode#36085]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
bower|don|0.0.3
jquerysnippets|don|0.0.1
eppz-code|epp|1.2.41
code-runner|for|0.7.2
beautify|Hoo|1.1.1
docthis|joe|0.5.0
Angular1|joh|0.2.0
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0
html-css-class-completion|Zig|1.10.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. I have a project in a network folder
2. Source control tab, open changes for any file to visualize it
3. No response for a while, then you get : "Git: Failed to show text document file:Route_of_my_file, should show in editor #undefined"

Reproduces without extensions: Yes/No
If I disable extensions, I can view my changes, but when adding a route to my .gitignore file, the file doesn't get removed from the changes list.

**Comment by joaomoreno** [comment]
Can you record a screencast?

**Comment by dradickDT** [comment]
I believe I encountered the same issue after my update to 1.17.1 as well. VSCode would not open diffs or merge conflicts from the SCM sidebar. It would give an error about not having an editor defined. 

I ran the command to add `code` back to the PATH, which some how got lost. I set up code as the global editor, difftool, and mergetool for git. And rebooted Code several times. The error persisted.

When I tried reproducing the issue this morning to post a screencast to this thread, everything worked fine. I even undid my git config settings and couldn't get an error. My best guess is that there was disconnect between Code and the branch that remained checked out before and after the update. And somehow changing/creating new branches helped resolve things? Again, best guess...

**Comment by kasske** [comment]
VSCode Version: Code 1.17.2 

Its not working for me either. Cant do inline actions to accept current or incoming... Used to love that feature of better-merge.
Now i cant make it to work. There is no inline actions

**Comment by joaomoreno** [comment]
@dradickDT @jzatarain If you guys manage to reproduce it let me know.

@kasske Might you have a separate issue perhaps?

**Comment by kasske** [comment]
@joaomoreno  I don't know exactly, but i can't find a solution on how to get it to work

![image](https://user-images.githubusercontent.com/19287983/31778189-54910158-b4f0-11e7-94e9-7d17a4fef518.png)
 That above is the issue and i want to have the feature below:
![image](https://user-images.githubusercontent.com/19287983/31778266-82f08a96-b4f0-11e7-81ee-2dabc49437a9.png)

**Comment by jzatarain** [comment]
The changes visualizer now works, but the issue about adding a pattern to the gitignore file no longer removes the matched files from the changes lists, still happens.
So instead of using "stage all changes", I have to stage things per file. @joaomoreno

**Comment by joaomoreno** [comment]
> the issue about adding a pattern to the gitignore file no longer removes the matched files from the changes lists, still happens.

That is how git works. You must remove the file from the repository. Glad it works now.
