### ISSUE TITLE
Idea about bookmark in VS Code

### ISSUE THREAD

**Issue by titaneric** [Microsoft/vscode#36082]
HI, VS Code.
I'm a lover with VS Code for just one year, just a little suggestion here...

Cause the programmers may review/trace codes, and programmers (at least including me) may forget where they trace/review. A bookmark is a big help for programmers at this time.

Specific advice here:  The programmer can mark the line number in the code after right-clicking on the lino and selecting the "Add bookmark". VS Code saves the bookmarks in the ".vscode" directory before the VS Code is totally closed and left. In the next time when the same directory being opened, the VS Code loads the data from ".vscode" folder and marks where the bookmarks are, and the programmers can start their work from there.

It's seem that the suggestion is over. Hope that the advice can be implemented and help other programmers who have the same problem like me.

Best regards,
TitanEric

**Comment by egamma** [comment]
@titaneric there is a popular extension available for this and we currently have no plans to implement this in the core.
