### ISSUE TITLE
Hanging & Key Repetition while typing

### ISSUE THREAD

**Issue by kylegrantlucas** [Microsoft/vscode#36088]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.8
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.2
vscode-docker|Pet|0.0.18
code-settings-sync|Sha|2.8.3
dot|Ste|0.0.1
fish|Ted|0.0.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
python|don|0.7.0
gitlens|eam|5.6.0
tslint|eg2|1.0.11
git-project-manager|fel|1.4.0
ruby|gro|0.0.6
cypher-query-language|jak|1.0.2
Go|luk|0.6.66
MagicPython|mag|1.0.12
dotenv|mik|1.0.0
sublime-keybindings|ms-|2.9.1
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vscode-icons|rob|7.15.0
trailing-spaces|sha|0.2.11
shellcheck|tim|0.1.0
vim|vsc|0.10.1
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

(6 theme extensions excluded)

---

Steps to Reproduce:

1. Open Go project
2. Start typing, once achieving any "rhythm" while typing random characters will start to repeat on every few seconds.

Reproduces without extensions: No

**Comment by egamma** [comment]
I cannot reproduce this given the above steps. Are you using a special keyboard? Can you please attach a screen recording that illustrates the problem?

**Comment by egamma** [comment]
Please reopen and with more information
