### ISSUE TITLE
Cursor lost after selecting completion item using mouse

### ISSUE THREAD

**Issue by EduardoMx0122** [Microsoft/vscode#36087]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
ionic-preview|ion|0.0.15
material-icon-theme|PKi|2.2.2
cordova-tools|vsm|1.2.12

(1 theme extensions excluded)

---

Steps to Reproduce:

1.type something, intellisense appear
2.on select any intellisense option, the cursor its gone

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Regression from 1.16

**Comment by ramya-rao-a** [comment]
@jrieken The cursor is lost when a completion item is selected using mouse

**Comment by ramya-rao-a** [comment]
@joaomoreno I was able to trace down the commit that caused this to https://github.com/Microsoft/vscode/commit/3ac4826939631336f4989fa7421aad7d6258de8a
