### ISSUE TITLE
Adding "base" to files.exclude breaks VS Code

### ISSUE THREAD

**Issue by natedawg1013** [Microsoft/vscode#36081]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-astyle|chi|0.7.1
python|don|0.7.0
toggle-excluded-files|eam|1.6.0
base-converter|hoo|0.0.1
auto-comment-blocks|kev|1.0.1
vscode-devskim|MS-|0.2.0
cpptools|ms-|0.13.1
sublime-keybindings|ms-|2.9.1
material-icon-theme|PKi|2.2.2
reloaded-cpp|rel|0.1.6
vscode-coverage-gutters|rya|1.1.3
perforce|sle|2.2.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open any folder in VS Code
2. Create a .vscode directory
3. Create a file "settings.json" within this .vscode directory
4. Add the following to the file:
`{
    "files.exclude": {
        "base": true
    }
}`
5. Save and close VS Code
6. Reopen VS code to the original folder (folder which contains .vscode directory)
7. VS Code window will be blank except for top menu bar, keyboard shortcuts will give errors.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@natedawg1013 great catch 👍
