### ISSUE TITLE
JS: editor.autoIndent seems to be broken

### ISSUE THREAD

**Issue by basilikum** [Microsoft/vscode#36090]
The option `editor.autoIndent` seems to do exactly the opposite to what it is supposed to do. If it is set to true, then autoIndent is disabled, if it is set to false, then autoIndent is enabled.

I posted this question on Stackoverflow: https://stackoverflow.com/questions/46692283/prevent-vs-code-from-changing-indentation-on-enter

Steps to Reproduce:

1. Set `editor.autoIndent` to false
2. Follow instructions on Stackoverflow question
3. Set `editor.autoIndet` to true
4. Follow instructions on Stackoverflow once again
5. Observe that the first time it causes an automatic indentation and the second time it doesn't

I am using Version 1.17.1 on macOS Sierra 10.12.6

Reproduces without extensions: Yes (all extensions were disabled)

**Comment by TheDutchCoder** [comment]
`autoIndent` doesn't do anything for me and indentation is completely broken since last version.

All kinds of weird offsets happening all over the place. Not even sure if there's a pattern to it.

**Comment by egamma** [comment]
The example on SO shows that this is a problem in JS.

**Comment by alexandrudima** [comment]
I have fixed that setting `autoIndent: false` should not go and tweak indentation of the line on which Enter is pressed.

**Comment by basilikum** [comment]
Great! Thank you! :D

**Comment by Nodws** [comment]
Still not working in Ubuntu

**Comment by alexandrudima** [comment]
@Nodws Please open a separate issue with precise steps.
