### ISSUE TITLE
Highlight the corresponding breakpoint when stopping on a breakpoint in the debugger

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#36094]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
python|don|0.7.0
Go|luk|0.6.66
cpptools|ms-|0.13.1
perforce|sle|2.2.1
---

Currently when stopping on a breakpoint it's hard to tell which one is it in the list of breakpoints (there's no visual clue). I'm primarily interested in the C++ debugger, but this could be relevant to all debugger engines.

**Comment by tlemo** [comment]
Out-of-scope? Was the tag added by mistake?

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
