### ISSUE TITLE
No warning when saving changes if underlying file changed while editing

### ISSUE THREAD

**Issue by JimKCode** [Microsoft/vscode#36096]
- VSCode Version: 1.17.1
- OS Version: Win10 version 1703

Steps to Reproduce:

1. Open XML file in VS Code
2. Make edit but do not save
3. Edit same file with another editor and save.
4. Back in VS Code, save your edit.

I've read that VS Code should prompt "Failed to save ... The content on disk is newer. Click on Compare" but it doesn't.  Instead, the edits in VS Code overwrite whatever was done by the other editor.
Note that VS Code did not silently update any lines in my dirty file between steps 3 & 4.  That's why saving in VS Code lost the edit done in the other editor.
The most disturbing part of this is that I can overwrite someone else's change and never know it.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by JimKCode** [comment]
If you're referring to  #31063, it doesn't look the same.  I DID NOT get any warning about a potential conflict.  It silently overwrote the changed file.  That's DATA LOSS.  Why isn't that fixed already?
