### ISSUE TITLE
New theme colors for modified files in tree view?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#36091]
- VSCode Version: Code - Insiders 1.18.0-insider (3ffa14e5ed86b3489f86d9f8d966ae3076f94a61, 2017-10-11T05:11:32.053Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.11
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.29.1
Align|ste|0.2.0
ayu|tea|0.8.0
change-case|wma|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Add a file to project folder (`_functions.scss`).
2. Modify an existing file (`design_system.scss`)

The new file and its enclosing folder are gray, and the modified file and all its enclosing folders are blue.  This never happened before.

<img width="287" alt="screen shot 2017-10-11 at 2 44 31 pm" src="https://user-images.githubusercontent.com/835148/31460040-08bd9fce-ae93-11e7-813b-33c18d1d7c8d.png">

where are these colors set, so I can make them work better with my workbench theme?

**Comment by smlombardi** [comment]
Found it via a hunch.  Not in documentation... was this added recently?

   `"git.color.untracked"` and `"git.color.modified"`

**Comment by equinusocio** [comment]
@smlombardi yes.
