### ISSUE TITLE
Terminal dropdown doesn't appear on first click after window reload

### ISSUE THREAD

**Issue by osdavison** [Microsoft/vscode#36095]
- VSCode Version: 1.17.1
- OS Version: Windows 7

The first time that I click on the terminal selector dropdown after reloading the vscode window, the list of terminals does not appear (It is just black)

![image](https://user-images.githubusercontent.com/16767154/31467427-ed3a05f2-aea7-11e7-98e2-6685d562db94.png)

Steps to Reproduce:

1. Open a new VSCode window
2. Open the integrated terminal
3. Reload the window `ctrl+shift+p`, then Reload Window
4. Click on terminal selector dropdown

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/25700
