### ISSUE TITLE
File Tree Explorer: Missing "Move File" on right click menu!

### ISSUE THREAD

**Issue by WadeShuler** [Microsoft/vscode#36104]
# Missing "Move File"

There should be a "Move File" menu item when you right click on a file in the Explorer file tree.

## Steps to Reproduce:

1. Right click on a file in the left Explorer tree. You can rename and delete it, but there is no ability to move it. This seems like a pretty common feature and found in other editors.

## Reproduces without extensions:

It wouldn't make sense for an extension to magically remove this menu item...

---

### Specs

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
swift|Kas|0.0.3
vscode-docker|Pet|0.0.18
html-css-class-completion|Zig|1.10.0
project-manager|ale|0.21.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
laravel-goto-view|cod|1.1.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
openshift-vscode-extension|dud|0.0.2
gitlens|eam|5.6.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
docker-explorer|for|0.1.5
phpcs|ika|0.7.0
csharpextensions|jch|1.3.0
Go|luk|0.6.66
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
vscode-mongodb|ms-|0.0.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
php-docblocker|nei|1.3.2
vetur|oct|0.9.11
laravel-blade|one|1.9.0
laravel5-snippets|one|1.3.4
sass-indented|rob|1.4.2
laravel-artisan|rya|0.0.8
vscode-nginx|sha|0.4.1
vscode-import-cost|wix|2.5.0

(1 theme extensions excluded)

**Comment by egamma** [comment]
@WadeShuler you can move files using drag&drop.

**Comment by WadeShuler** [comment]
That isn’t my point and isn’t always feasible on a large project and when your nested down many directories.

Every other IDE I have used has a “move” file option or the rename includes a path, which lets you move it by changing the path too. Sometimes it’s easier (especially using a trackpad) to just type the path. Or maybe you need to copy and paste the path in...

**Comment by WadeShuler** [comment]
Really? Basic file handling isn’t a core function? Are you kidding me? It
is absolutely nuts to suggest people use a 3rd party extension to add “move
file” support! Might as well remove the “rename” feature, as it isn’t a
core function, since it’s similar to “move file”.

Don’t be like Atom and ignore basic necessities of a file editor/IDE! That
is why Atom users jumped to Code in the first place!

I have been programming for 15 years. I think I have a pretty good idea of
what a text editor or IDE should come out of the box with!
