### ISSUE TITLE
~765M memory footprint without extensions...

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#36105]
- VSCode Version: 1.18.0-insider
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Open VSC (`vsc --disable-extensions`) with an existing project. (One I tested on has about 423 local files and 19K in node_modules.)
2. Open System Monitor and gasp in horror.

![memory hog](https://user-images.githubusercontent.com/2549985/31475583-994d6d36-af3c-11e7-81db-643216111c32.png)

Reproduces without extensions: Yes

I know, I know...this is web technology, but...I've developed full-fledged operating systems with complex UIs (Symbian) that used a fraction this amount RAM! A little perspective: Ubuntu Linux with Plasma (Desktop) uses about 1G.

This is, after all, an IDE. Is there any plan to tame this beast?

**Comment by badre429** [comment]
vscode is realy lightweight in install size but when it comes to ram it end up consuming more than Visual Studio the full IDE

**Comment by ZombieProtectionAgency** [comment]
I haven't noticed VSCode using too much ram. For reference this is my system currently:
![image](https://user-images.githubusercontent.com/9204874/31614114-2cc99986-b253-11e7-8ad8-a3e1594aed95.png)

**Comment by bpasero** [comment]
Still happening?

**Comment by Panoplos** [comment]
Yes (latest insiders version)

![still memory hog](https://user-images.githubusercontent.com/2549985/32873586-2bdb6712-cad0-11e7-9ef9-74dbb5d94a26.png)

**Comment by bpasero** [comment]
@Panoplos can you find out which command line is the highest memory process in that list?

**Comment by Panoplos** [comment]
According to this:

![highest memory](https://user-images.githubusercontent.com/2549985/32888594-1da2eb12-cb0b-11e7-9407-f1b2a07d2569.png)

Process is:
panoplos    7093  0.9  3.6 1553300 589148 ?      Sl   13:01   4:18 /usr/share/code-insiders/code-insiders /usr/share/code-insiders/resources/app/extensions/typescript/out/utils/electronForkStart.js /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-tscancellat...

**Comment by Panoplos** [comment]
As I am not even using TS, is there a way to disable it?

**Comment by bpasero** [comment]
@mjbvz welcome

**Comment by mjbvz** [comment]
@Panoplos  TypeScript powers both our JS and TS language support.

If you are still seeing this issue, try setting up some [jsconfig](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) includes/excludes patterns to make sure only the JS files you want are being loaded. Here's a standard jsconfig the excludes all js files in `node_modules`

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by mjbvz** [comment]
Closing as we cannot investigate this further without additional info
