### ISSUE TITLE
Allow user defined default launch.json for specific language

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#36108]
Hi,

Is there anyway to create a user defined default launch.json for specific language?

For example:
I want to add `Pytest` or some custom config to python debug configurition,   but I have to manually add that config to each project's launch.json  . Usually we want a global launch.json sync to all project.

feature would be:
1.  user define default launch.json for specific language
2.  a setting parameter :  overwrite current project's launch.json  to newest , when user defined launch.json changed (or current vscode is focused)

At first, I post on  https://github.com/DonJayamanne/pythonVSCode/issues/1292 , because they say it is by vscode , so I repost here .

**Comment by auchenberg** [comment]
@eromoe Can you elaborate on the specific use-case? I'm not sure I fully understand. You want to install/provide a `launch.json` for user's workspace when they install the `pythonVSCode` extension or open a new workspace?

**Comment by eromoe** [comment]
### 1. `pythonVSCode` would provide  launch.json for each python project

`pythonVSCode`  would automatically  create a predifined  launch.json use for debug:
![image](https://user-images.githubusercontent.com/3938751/31476487-2d661b84-af39-11e7-883b-8216d33736fa.png)

content is like 
```

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },      
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
.....
}
```

### 2. I want to add a debug config named `PyTest`  , which can use in every existed project,  or new create project .  

### 3. But now,  launch.json is create by `pythonVSCode`  with its default `launch.json` . Except the project I modified myself,  neither new project  nor other old projects  would have  `PyTest` .


### 4. So a global user defined launch.json ,  automatically sync with each project would be good.

**Comment by isidorn** [comment]
We currently support having a global launch.json that a user can specify in his configuration file. More about this https://github.com/Microsoft/vscode/issues/18401
Apart from that any debugger can customize the launch.json any way he wants, more about that can be found in https://code.visualstudio.com/updates/v1_16#_debug-api-updates

**Comment by eromoe** [comment]
>  I have clarified that if a launch.json is present in the workspace the global launch confiugration is ignored.
I  think this global is useless in most situation. 

At least, 
1. If I add custom python and js gloabl config ,  I wouldn't like to see the js config show on python project.
2. Please provide a parameter,  to make global config auto merge into  workspace's config or not.


I have describe the details, I think this feature is not only a global config. Sync/merge config is the big point.

Please consider to reopen this.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
