### ISSUE TITLE
Terminal line alignment cause characters cropped

### ISSUE THREAD

**Issue by samsong8610** [Microsoft/vscode#36106]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-docker|Pet|0.0.18
code-gnu-global|aus|0.2.2
file-templates|brp|1.2.0
FreeMarker|dco|0.0.9
python|don|0.7.0
CppSnippets|har|0.0.12
restructuredtext|lex|38.0.0
Go|luk|0.6.66
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
vetur|oct|0.9.11
java|red|0.11.0
html-preview-vscode|tht|0.1.1
vim|vsc|0.10.1
jinja|who|0.0.8

---

Steps to Reproduce:

1. open terminal
2. the prompt line display like [the screenshot](http://wx4.sinaimg.cn/mw690/5700655cly1fkf8pqc8j7j20c902gt8l.jpg)

Reproduces without extensions: Yes

**Comment by AMoghrabi** [comment]
I'm having the same issues on Fedora 26.

**Comment by JustinTJones** [comment]
+1

VS Code:
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

uname -a:
Linux [hostname removed for privacy] 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux

**Comment by Tyriar** [comment]
This should be fixed in 1.17.1 https://github.com/Microsoft/vscode/issues/35644

There is another release coming soon to fix another regression that added https://github.com/Microsoft/vscode/issues/35991
