### ISSUE TITLE
The icon for new updates is shown, even though the last update was downloaded

### ISSUE THREAD

**Issue by bigkrp** [Microsoft/vscode#36114]
![2017-10-12 08-37-31](https://user-images.githubusercontent.com/11586744/31481170-a9dd75b8-af2a-11e7-8401-679e997dc952.png)

- VSCode Version: `1.17.0`
- OS Version:
```
Fedora 26,
Linux version 4.13.5-200.fc26.x86_64 (mockbuild@bkernel01.phx2.fedoraproject.org) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC)) #1 SMP Thu Oct 5 16:53:13 UTC 2017

```

Steps to Reproduce:

1. Update last version via RPM Fusion 
2. Launch VS Code

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
1.17.1 has been released.

@Tyriar this might be related to the delay in publishing rpms and debs?

**Comment by Tyriar** [comment]
Yeah we had a bunch of issues pushing out the rpm for 1.17.1
