### ISSUE TITLE
Rename the product to "Visual Code", dropping "Studio" from name

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#3611]
Vscode is a totally different product from the Visual Studio behemoth. So IMHO, dropping **Studio** and renaming the product **Visual Code** will match the characteristic of this product better. This is not an IDE and thus not a Studio. And Visual Code suits to be name of a tool to visualize code. "Visual" will also goes with other development products from Microsoft like "Visual C++" or "Visual Basic". The twitter handle is already just @code. After the renaming, often used shorthand vscode can denote **V**i**s**ual **Code** instead of **V**isual **S**tudio **Code**. Even the product name in https://github.com/Microsoft/vscode/blob/master/product.json do not have the word "Studio". So, everything will fit together.

**Comment by chrisdias** [comment]
@gulshan thanks for the feedback.  

The intent of using the "Visual Studio" name for Code is that "Visual Studio" is a family of products  consisting of Visual Studio, Visual Studio Team Services, and Visual Studio Code (you can see this on the https://www.visualstudio.com/ home page). As you note in your feedback, one of the challenges we have with this model today is that most people think of "Visual Studio" as the traditional VS Windows desktop product and not a family of products. In fact, there isn't a clear way to distinguish between those two.  

The "Visual Studio" brand has tremendous recognition and appeal among developers (despite some negative connotations) and we do want Code to be associated with it. As a result of all this, given that "Visual Studio" is the family name and "Code" is the product, then "Visual Studio Code" is the correct name using this model. 

For the "Code" name, it is clear that one of the bigger challenges we have is around search (you can find a number of issues here that bring this up). It's hard to search for "Code", you have to use "VS Code" or "VSCode" as the term. We're working hard to improve our search rankings and we're building up https://code.visualstudio.com as the definitive place for all things Code, further strengthening the search terms. It will take time but we are only in the very early stages of this product!

I hope this helps to explain the naming.  

Chris
