### ISSUE TITLE
Issue while navigating from one line to the other

### ISSUE THREAD

**Issue by morfsys** [Microsoft/vscode#36112]
So, this has been very frustrating when I decided to switch from Atom to VS Code.
Everytime I want to move my cursor down or up using navigation keys, I am not able to do so.
The little tooltip that appears next to my current cursor position wont allow me to navigate down or up. It simply navigates the message inside the tooltip.
For this particular reason, I have to use mouse everytime I wish to move up or down. This has been very frustrating and so I switched back to Atom for the moment.

**Comment by egamma** [comment]
@morfsys this is bad, but it is not fully clear when this problem shows up. Can you please add a screenshot that illustrates the problem?

**Comment by morfsys** [comment]
Sure thing. HYG
![vs-code-issue](https://user-images.githubusercontent.com/25836296/31499692-22ee77b0-af83-11e7-83a3-a863c5b41ea0.png)

**Comment by egamma** [comment]
I think this is a user preference, since you are entering a parameter the pop shows you the potential parameters for this function. You can press escape to dismiss it.

You can set  "editor.parameterHints": to false and the pop-up will not appear,
