### ISSUE TITLE
Incorrect comment in vscode.d.ts related to `registerDebugConfigurationProvider` 

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#36118]
- VSCode Version: 1.17.1
- OS Version: mac

Steps to Reproduce:

1. write a extension
2. call `vscode.workspace.registerDebugConfigurationProvider`

![image](https://user-images.githubusercontent.com/227713/31484105-9158840a-aef4-11e7-9eac-75dfcf55060a.png)

BTW, https://code.visualstudio.com/docs/extensions/example-debuggers need updated also.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
@atian25 In your package.json do you set the engine version to 1.17 and did you run postInstall?

**Comment by atian25** [comment]
```js
  "engines": {
    "vscode": "^1.17.0"
  },
```

and just run postinstall:

```bash
➜  vscode-eggjs git:(master) npm run postinstall

> eggjs@0.0.6 postinstall /Users/tz/Workspaces/github/vscode-eggjs
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.17.0
Found minimal version that qualifies engine range: 1.17.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```

**Comment by egamma** [comment]
You are using the wrong name space. It is `vscode.debug.registerConfigurationProvider`.

**Comment by atian25** [comment]
oh, sorry.

so it seems to be a doc bug at `vscode.d.ts`

![image](https://user-images.githubusercontent.com/227713/31489637-ebf843de-af06-11e7-918c-8adfd81219e4.png)

**Comment by atian25** [comment]
and also https://code.visualstudio.com/docs/extensions/example-debuggers need update.

**Comment by egamma** [comment]
@atian25 this explains things, thanks. Reopening.

**Comment by weinand** [comment]
For updating the documentation (https://code.visualstudio.com/docs/extensions/example-debuggers) I've created https://github.com/Microsoft/vscode-docs/issues/1216.

**Comment by atian25** [comment]
hi, @weinand 

had register, but the `provideDebugConfigurations` don't trigger, did I miss some config?
should I need to provide `contributes.debugger` ? how?

```js
  context.subscriptions.push(vscode.debug.registerDebugConfigurationProvider('node', {
    provideDebugConfigurations(folder: WorkspaceFolder, token?: CancellationToken): DebugConfiguration[] {
      return [
        {
          name: 'Egg Debug',
          type: 'node',
          request: 'launch',
          port: '9999',
        }
      ];
    }
  }));
```

**Comment by weinand** [comment]
@atian25 make sure that your debugger extension activates correctly by contributing this in package.json:
```ts
	"activationEvents": [
		"onDebug",

                // ... and all commands that need to activate this extension 
        ]
```

Please note that `provideDebugConfigurations` is only called for projects that do not have a launch.json. And you need to press debug's gear icon.

**Comment by atian25** [comment]
`provideDebugConfigurations` don't support `add Configuration`? 

Only had to config  `configurationSnippets`?

**Comment by atian25** [comment]
as https://github.com/Microsoft/vscode/issues/34668 `DebugConfigurationProvider` should support `configurationSnippets` now

**Comment by weinand** [comment]
I was wrong in closing #34668. Please see my comment there.
