### ISSUE TITLE
PsScriptAnalyzer Falsely Recognizes Global Variable As Assigned But Not Used

### ISSUE THREAD

**Issue by avelis26** [Microsoft/vscode#36111]
- VSCode Version: 1.17.0
- OS Edition: Windows 10 Pro
- OS Version: 1703
- OS Build: 15063.674

Steps to Reproduce:

1. Open VS Code and create a PowerShell file (PowerShell extension installed obviously).
2. Paste the following example code:
```powershell
function Write-ErrorDetails {
	$global:eventType = 'Error'
	Write-Error -Message 'An error happened.' -ErrorId $statusCode
}
try {
	Write-Output 'hello world'
	$statusCode = 0
	throw 'eventType variable is totally going to get used now!'
}
catch {
	$statusCode = 1
	Write-ErrorDetails
}
finally {
	Write-EventLog -LogName 'Applicatoin' -Source 'MyScript' -EntryType $global:eventType
}
```
3. Note that `$global:eventType` is underlined as a 'PSUseDeclaredVarsMoreThanAssignments' error.

**Comment by egamma** [comment]
Please file the issue against the powershell extension https://github.com/PowerShell/vscode-powershell

**Comment by avelis26** [comment]
Thank you and reported.
