### ISSUE TITLE
Symbol need many time to load

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#36117]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.1
sublime-keybindings|ms-|2.9.1

---

Steps to Reproduce:

1. It needs almost 10 sec to loading when I use "Go to symbol in File..." at the first time in a file. (My working folder almost 20G)
![loading](https://user-images.githubusercontent.com/18381153/31482524-4ddcaf1e-af5b-11e7-853c-1acf9a9472d9.png)

2. Seach file using Ctrl+P is faster then before, but sometimes it still needs to loading for a long time (Rebuild Index ?)

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
@Jackie-Yang this issue is C++ related, please file the issue against this repository https://github.com/Microsoft/vscode-cpptools
