### ISSUE TITLE
[Folding] Could vscode support #region and #endregion in PHP ?

### ISSUE THREAD

**Issue by DarkNami** [Microsoft/vscode#36115]
Could vscode support #region and #endregion in PHP ?
( # is also a PHP comment, so we can use C# folding mark )

[PHP supports 'C', 'C++' and Unix shell-style (Perl style) comments](http://php.net/manual/en/language.basic-syntax.comments.php)

Thank you.

Follow: #12146

**Comment by roblourens** [comment]
Technically yes, but I don't know that I would want to implement a brand new folding construct for PHP in vscode. Does any other editor respect that in PHP?

**Comment by DarkNami** [comment]
PhpStorm has folding comment //region and //endregion 
[Visual Studio style folding](https://www.jetbrains.com/help/phpstorm/2016.1/code-folding.html?origin=old_help#using_folding_comments)

Personaly, I use #region and #endregion in my PHP code. 
(I also writing C# code, so I use VS style folding comment)

I saw the new 'Folding regions' feature in v1.17.1 release log, I think maybe vscode can support this feature in PHP. 

If this feature request is unnecessary, you can close this issue. :)
