### ISSUE TITLE
fuzzy searching problem

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#36119]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.1
sublime-keybindings|ms-|2.9.1

---

Steps to Reproduce:

If I want to fuzzy search "File.cpp" under "ABC" folder (using Ctrl + P)， input "ABC File.cpp",
The search results might be:
"Axx\xxBxx\xxC\xxxxx\File.cpp"

The search results are inaccurate， most importantly，  I didn't get the results I needed.
The searching performance of sublime text is still better than vscode.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
It's hard to know what you mean in that case if there are other fuzzy matches, but if you use `abc/file.cpp`, then it should only show the result under a folder 'abc'.

**Comment by roblourens** [comment]
Assigning @bpasero if you want to tweak it or follow up

**Comment by Jackie-Yang** [comment]
@roblourens 
for example:
Target path: xxx/xxx/abc/xxx/xxx/file.cpp
Input: abc file.cpp
result: axxx/bxxx/cxxx
VScode:
![1-1](https://user-images.githubusercontent.com/18381153/31526113-68f2fd52-aff7-11e7-950a-5c8b66c3ced8.png)

Sublime:
![2-2](https://user-images.githubusercontent.com/18381153/31526115-6c478356-aff7-11e7-85bd-475a7741875a.png)

**Comment by bpasero** [comment]
@Jackie-Yang did a little bit of tweaks here for our 1.18 insider build, can you grab it and see if your examples work any better? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
@Jackie-Yang also in your screenshot where you compare VS Code with Sublime I see different folders for the top results, are those not showing up for VS Code after all? I mean the ones within `projects/ui/tcl/...`

**Comment by Jackie-Yang** [comment]
@bpasero Yes, so I said I didn't get the results I needed.
The results of VScode did not include "tcl" folder.

**Comment by bpasero** [comment]
@Jackie-Yang not at all or just showing up later? Is this workspace open source so that I could have a look?

**Comment by Jackie-Yang** [comment]
Sorry~This code is not open source
But I try it again, and it show correctly, maybe the index build error?
And I want to know is it the index rebuilt sometimes? Sometimes the result show quickly, and sometimes it need to load.
Can vscode  show index progress like sublime?

**Comment by Jackie-Yang** [comment]
@bpasero But this problem still exist, it still show wrong result when I search some file.
My workspace is to big, so I try to input the whole path of the file, and it need to load for a long time, so I think vscode did not index all the file at that time.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/9d40f0c647bf1de0aaa813e6519b85a24e98da14
