### ISSUE TITLE
Feature Request: Collapse Activity Bar on focus change

### ISSUE THREAD

**Issue by scifientist** [Microsoft/vscode#36110]
VSCode Version: 1.17.1
I've looked through the default settings for the feature, but didn't find it. Also asked on stackoverflow, someone suggested to set it to a hotkey/suggest it on here.

**Comment by isidorn** [comment]
Please clarify what feature you want.
And make sure it is not a duplicate by searching through our database. Thanks

**Comment by scifientist** [comment]
A default setting to collapse the activity bar on focus change. Its current default behavior is to stay opened, and needs to be manually collapsed back into a strip with just the activity bar icons. I looked through the database and didn't find any pertinent info, but I'm pretty new to coding so a lot of the features terminology is unfamiliar to me. Please let me know if it's still unclear, thanks.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/3742
