### ISSUE TITLE
OmniSharp is taking more time to load and sometime it is showing server load timeout. I have set the TimeOut of 900! 

### ISSUE THREAD

**Issue by technicalganesh** [Microsoft/vscode#36116]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
csharpfixformat|Leo|0.0.36
vscode-docker|Pet|0.0.18
html-css-class-completion|Zig|1.10.0
vscode-database|baj|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
gitlens|eam|5.6.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
eppz-code|epp|1.2.41
vscode-guid|hea|1.2.0
path-autocomplete|ion|1.6.1
csharpextensions|jch|1.3.0
mssql|ms-|1.2.0
csharp|ms-|1.12.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
Please report the issue against the C# extension: https://github.com/OmniSharp/omnisharp-vscode
