### ISSUE TITLE
Not updated repodata for latest release 1.17.1

### ISSUE THREAD

**Issue by brozs** [Microsoft/vscode#36129]
Hello VSCode,

Thank you for your latest release, but please do not forget to update repodata for the yum repositories when you do a release. The latest modification was made:

repomd.xml                                         06-Oct-2017 22:24                2986

Which is around the time when 1.17.0 was released. This means that noone using yum/dnf will see the 1.17.1 update.

**Comment by chrmarti** [comment]
Contacted our Linux repo folks.

**Comment by s-martin** [comment]
YUM repositories always took a couple of days, until new versions were available. Not sure why.

**Comment by brozs** [comment]
The RPM is in the yum repository, perhaps somebody just forgets to run createrepo --update </path/to/repo>? Or are you using a CDN and not pushing repodata content?

**Comment by chrmarti** [comment]
I got word that we might run into [this issue](https://bugs.launchpad.net/ubuntu/+source/libxml2/+bug/1375637) and might have to rebuild the repo as mentioned in the issue's comments.

**Comment by Tyriar** [comment]
I think we can close this off for now as there is nothing more to be actioned. 1.17.1/2 should be on the repo
