### ISSUE TITLE
collapse search items in sidebar

### ISSUE THREAD

**Issue by MizuBishi** [Microsoft/vscode#36121]
Is there a way to collapse the search results in the sidebar (like in the explorer of the editor)? I work with several microservices and I have to search all the time and it is pretty confusing. I would love to use it furthermore but It depends on the good search possibilites. Please help :)

**Comment by roblourens** [comment]
The search viewlet has the same "collapse all" button as the explorer. Is that what you mean?

![image](https://user-images.githubusercontent.com/323878/31509339-ffd3b4f4-af35-11e7-824e-4ef05d60bf2f.png)

**Comment by MizuBishi** [comment]
Hi Rob 

Sorry was my mistake. Im so glad for it, thanks!

Best, Michelle
