### ISSUE TITLE
Cursor animations expand, smooth, phase are stuck after 10 reps

### ISSUE THREAD

**Issue by MilanLes** [Microsoft/vscode#36128]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
p5js-snippets|aci|0.0.6
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
---

Steps to Reproduce:

1. Go to User Settings
2. save of these setting for cursor 
- "editor.cursorBlinking": "expand"
- "editor.cursorBlinking": "smooth"
- "editor.cursorBlinking": "phase"
3. after 10 expansions, cursor is frozen at full expanded size

Issue is reproducible with every type of cursor (line, block, underline and thin variations)

Workaround: force redrawing of cursor (write any character, move cursor, scroll page so cursor is not visible and then scroll back...)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is to prevent high CPU usage while vs code is idle. See https://github.com/Microsoft/vscode/issues/22900#issuecomment-291667931
