### ISSUE TITLE
Allow file name to language associations via settings

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#3612]
i have yaml in .controller, .asset etc files
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
```
when i open the file it does not detect it is yaml and sets it to plain text mode?
i can choose yaml from the language mode selector (to get nice coloring) but then i get an error on that first yaml 1.1 line

Expected a JSON object, array or literal
![untitled](https://cloud.githubusercontent.com/assets/962340/13452325/c4833196-e014-11e5-952a-cbdbe6b6cb97.png)

1. should it auto detect? or is there a way to associate files with languages? (no, see link below)
2. how to fix error?

thanks

https://code.visualstudio.com/docs/languages/overview
Q: Can I map additional file extensions to a language?
A: Currently this is not supported but it's on the way.

**Comment by aeschli** [comment]
@rakkarage I can't reproduce the error you get on the first line. Do you have any extensions installed that might have an impact on Yaml?

**Comment by rakkarage** [comment]
ya nevermind the error i cannot reproduce it either but i think it came because i changed the file type a couple times before i ended up on yaml. because each time i open the project i have to reselect yaml type for each file thanks

**Comment by bpasero** [comment]
@egamma pushed a change to have an action in the mode picker that hints a user to the fact that this is configurable now, feedback welcome:

![image](https://cloud.githubusercontent.com/assets/900690/13608354/bfc3b6fe-e554-11e5-8d82-3bb0d27a218c.png)

**Comment by egamma** [comment]
@bpasero the quick box looks good.

The top most quick box entries are difficult to discover since the currently defined association is revealed.  How about not revealing the current mode when the user has changed the association. In this way the top most entries are always visible?

What is a bit disturbing are the info messages that appear when you have a workspace settings, but this is not the common case
![image](https://cloud.githubusercontent.com/assets/172399/13685367/6a1ccf34-e710-11e5-9163-febcaa288029.png)

I suggest to make `Configure in Settings...` more verbose, e.g., `Open Settings to configure default for ".html"

**Comment by bpasero** [comment]
@egamma good ideas, here is the new look depending on what you do:

**Untitled file**
![image](https://cloud.githubusercontent.com/assets/900690/13696449/b930a9be-e766-11e5-9408-cfbb2b468f8c.png)

**File with extension**
![image](https://cloud.githubusercontent.com/assets/900690/13696451/bced0b88-e766-11e5-8174-8100411b7698.png)

**File without extension**
![image](https://cloud.githubusercontent.com/assets/900690/13696457/c404e60c-e766-11e5-8692-5044b4520b4e.png)

Should we stop showing the info message at all?

**Comment by aeschli** [comment]
My wording suggestions:
Configure in Settings... ->  Configure file associations... 
Configure defaults for '.md' -> Configure file association for '.md'

**Comment by egamma** [comment]
>Should we stop showing the info message for workspace settings at all?

I'd keep it, it is useful since it tells me the setting.

:+1: on @aeschli 's wording suggestions

**Comment by bpasero** [comment]
Ok pushed. Thanks!
