### ISSUE TITLE
Search by filename (or results that also include filenames which match the search criteria)

### ISSUE THREAD

**Issue by DanAtkinson** [Microsoft/vscode#36125]
- VSCode Version: 1.17.1
- OS Version: Windows 10 v1511

**Steps to Reproduce:**

1. Open an folder/workspace in VSCode which contains files with similar filenames/extensions (such as locale variants). Inside each folder is a file called `Errors.txt`. Locale examples include de-DE, en-EN, en-GB.
2. Perform a search for `Errors.txt`

![image](https://user-images.githubusercontent.com/23440/31493329-a91f469e-af46-11e7-8c35-bd3564817a85.png)

**What should I expect to happen:**

Given the example filenames in step 1, I would expect several results called `Errors.txt` to be returned. However, unless those files contain the text 'Errors.txt', they are not included in the results.

**Anything else?**

I would like the search results to include the filename when searching. I know that Ctrl+P/Command+P does something similar-ish but if the results are output in a list, it makes it easier to go through them if you have to make lots of changes to files with the same/similar names which I sometimes do.

As an example, I may have the following folder structure:

    Locales
    ├───de-DE
    │       Errors.txt
    │       Info.txt
    │
    ├───en-EN
    │       Errors.txt
    │       Info.txt
    │
    ├───en-GB
    │       Errors.txt
    │       Info.txt
    │
    ├───fr-CA
    │       Errors.txt
    │       Info.txt
    │
    └───fr-FR
            Errors.txt
            Info.txt

If I wanted to get *just* the Errors.txt files, the best that I could do is to perform a search for strings that are unique to those files and hope that I don't get lots of other files (I actually do). In my real-world environment, each locale folder has 10-15 files, so the folder explorer isn't very quick to navigate when you have something in the order of 40 language variants and 10+ files in each as it's lots of collapsing/expanding.

In the meantime, I've had to put the filename in at the top of each file in order for them to be returned, which is somewhat cumbersome.

![image](https://user-images.githubusercontent.com/23440/31493500-60faa8bc-af47-11e7-9e8e-60b9515d8322.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
The search viewlet is specifically for searching for text, but you can set it to only search for certain file name/path patterns with the "files to include" menu, under the `...` button. Does that help?

![image](https://user-images.githubusercontent.com/323878/31509441-584323cc-af36-11e7-9cce-27445f7826c0.png)

**Comment by DanAtkinson** [comment]
Thanks for the feedback. Although I was surprised that the "files to include" functionality doesn't offer regex, I can achieve more or less the same result with wildcards instead. This is particularly handy if I only want to edit, say only the English versions of the same files to make spelling corrections.

![image](https://user-images.githubusercontent.com/23440/31550375-0e982af8-b029-11e7-9e6c-2dcfd6e798ea.png)

Much appreciated!

**Comment by roblourens** [comment]
Exactly - it supports basic glob syntax. Glad that helps.
