### ISSUE TITLE
Keys not working in VS code

### ISSUE THREAD

**Issue by Abdullah-Sohail** [Microsoft/vscode#36124]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.keys other than arrow keys not working
2.updated with latest version
3.still not working

**Comment by egamma** [comment]
@Abdullah-Sohail what kind of keyboard do you have? 
Please help us to track down the issue by following this guide https://github.com/Microsoft/vscode/wiki/Keybindings.

**Comment by egamma** [comment]
Closing, please reopen the issue when you can provide more information.
