### ISSUE TITLE
[Website] Own launch configuration page

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/vscode#36127]
This is the original: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

**Comment by isidorn** [comment]
Can you elaborate what is the issue here with exact reproducable steps. Thank you

**Comment by ShalokShalom** [comment]
Do you see an own page for the launch configuration?

**Comment by isidorn** [comment]
Please file this in this repository https://code.visualstudio.com/docs

**Comment by ShalokShalom** [comment]
Thanks
