### ISSUE TITLE
Formatting shortcut (cmd-k cmd-f) no longer working on mac

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#36126]
- VSCode Version: Version 1.17.1 (1.17.1)
- OS Version:  OS X 10.13 (17A405)

Steps to Reproduce:

1. Select text to format
2. Press Command-K Command-F
3. You get the message in the status bar that "the key combination (command-K command-F) isn't a command.
However, when you go to see the shortcuts we see:
{
  "command": "editor.action.formatSelection",
  "key": "cmd+k cmd+f",
  "when": "editorHasDocumentSelectionFormattingProvider && editorHasSelection && editorTextFocus && !editorReadonly"
}

so command-k command-f is certainly defined.

**Comment by egamma** [comment]
@jyavenard in what kind of file does this happen? I cannot reproduce it in a TypeScript file.

The when clause is `editorHasDocumentSelectionFormattingProvider` and not all language services provide a selection formatter.

**Comment by jyavenard** [comment]
C++ file

**Comment by egamma** [comment]
Looks like the C++ extension doesn't provide a formatter that can support the selection only. I suggest that you file a feature request against the C++ extension https://github.com/Microsoft/vscode-cpptools, nothing we can do about this on the VS Code side.

**Comment by jyavenard** [comment]
You're kidding right?

Formatting a selection worked just fine until I updated VS Code this morning....

You've dropped the usefulness of VS Code by half with whatever change you decided to make.
And the CPP provides all tools to format the code.
"C_Cpp.clang_format_path"

Please re-open, your conclusion is obviously wrong

**Comment by bobbrow** [comment]
We support this in the C++ extension. I suspect that the extension is currently unresponsive. There is a known issue on mac/linux causing the extension to stop receiving messages from VS Code. Try using the "Reload Window" command to reset the extension and formatting should work again.

Sorry for the inconvenience!

**Comment by jyavenard** [comment]
@bobbrow It didn't work after my first reload.. It did work again the 2nd time.. So indeed, it appears to be an intermittent issue...
