### ISSUE TITLE
Add intellisense support for local npm dependencies

### ISSUE THREAD

**Issue by megakoresh** [Microsoft/vscode#36123]
- VSCode Version: 1.17.1
- OS Version: Windows 10 Pro x64

VSCode does not seem to follow local dependencies. Pressing F12 on them gives "no definition found" and autocomplete does not work. It would be nice have them work same way as relative path requires. 

Steps to Reproduce:

1. Add `"localdep": "file:local"` to your package.json dependencies
2. Add a folder called `local` to the project root and create a simple package.json in it:
``` 
{
  "name": "localdep",
  "version": "0.0.0",
  "description": "My local dependency"
}
```
3. Create a file `dependency.js` in `local` with the following content
```
const path = require('path');
exports = class MyLocalClass {
  constructor(){}
  
  getMyDir(){
    return __dirname;
  }
}
```
4. Add a file `index.js` in `local` with the following content
```
exports.MyLocalClass = require('./dependency.js');
```
5. In your root file add the following
```
const { MyLocalClass } = require('localdep');

console.log(MyLocalClass.getMyDir()); //should print the directory of dependency.js 
```
If you put cursor over the `getMyDir()` method call, and press F12, it will not find anywhere to go to for definition and neither will it prompt `getMyDir` when typing as opposed to modules required through relative paths `require('./local/dependency.js')`. It would be nice if VSCode followed local dependencies.

Reproduces without extensions: **Yes**

**Comment by megakoresh** [comment]
After looking as the source code and noticing how module intellisense is provided, I tried the following:
```
npm install -g linklocal
cd [project dir]
linklocal -r
```
After re-opening the files, local dependencies were read from the symlinks in node_modules and were indexed - f12 and intellisense work just as expected!

If bundling this `linklocal` package as default extension is too much hassle, I guess the issue can be closed. It would be nice to have this somewhere in the docs or as an extension though.

**Comment by mjbvz** [comment]
Did you run `npm install` after creating the local dependency? This will create a symlink in `node_modules` to the local file

**Comment by megakoresh** [comment]
That's what `linklocal` does, just faster. So you can assume I did just that, after which the autocomplete started working as expected. What I was asking is - could this be done by VSCode, because those are local dependencies after all. If that is outside the scope, please feel free to close the issue.

**Comment by mjbvz** [comment]
Yes, the current behavior is consistent with what we do for normal package dependencies. For those, you do need to install them locally for intellisense to work properly. Adding logic to handle local dependencies differently is beyond our scope right now
