### ISSUE TITLE
Question/Feature Request: Color decorators and picker in JSON files?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#36138]
- VSCode Version: Code - Insiders 1.18.0-insider (c098b394b07afbb58975ab609117a0e115c5a3fa, 2017-10-12T05:11:23.795Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.11
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.30.0
Align|ste|0.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Is there a way to enable color decorators (the color "chips") along with the color picker for JSON files that include Hex colors, such as theme files?

**Comment by aeschli** [comment]
Note, if you edit color themes, make sure the file name ends with `-color-theme.json`. You will get the schema support, including color decorations.

To have color decorators in your own JSON files:
Annotate your JSON schema with `"format": "color"`. In the latest 1.18-insiders use `"format": "color-hex"`
Here's an example: https://github.com/Microsoft/vscode/blob/f61f960249f40ca4d9aaca11697340300e9eb0ed/src/vs/workbench/services/themes/common/colorThemeSchema.ts#L124

**Comment by smlombardi** [comment]
@aeschli  Thanks,  I had to rename my theme json to match the pattern.
