### ISSUE TITLE
[Feature Request]. Cursors API

### ISSUE THREAD

**Issue by vvatikiotis** [Microsoft/vscode#36136]
- VSCode Version: 1.17.1
- OS Version:  macOS Sierra (10.12.6)

Hello,

except from the `cursorMove` complex command I don't seem to find a Cursors API. Is there one? One where I could create, style, move (and move events) programmatically multiple cursors.

Also, is there an cursor event? Something like `onCursorMove` which can report the Position of a cursor within a TextEditor?

Coding a remote pair programming extension here, so unless I can show and track multiple cursors within an editor it's not very useful.

Thanks

**Comment by alexandrudima** [comment]
You can use [`TextEditor.selections`](https://github.com/Microsoft/vscode/blob/5ba128e16721d6a2bff75b72a29f24dd1c02382f/src/vs/vscode.d.ts#L1027) to read an editor's selection and you can use [`window.onDidChangeTextEditorSelection`](https://github.com/Microsoft/vscode/blob/5ba128e16721d6a2bff75b72a29f24dd1c02382f/src/vs/vscode.d.ts#L4504) to listen to selection changes.

**Comment by vvatikiotis** [comment]
I think I didn't state my use case clearly. What I need is a way to create a new cursor programmatically, using a vscode API. Something like `const aCursor = new Cursor(style: TextEditorCursorStyle, editor: TextEditor)`. I also need an API to move this cursor inside its editor and an event which will fire whenever a cursor moves reporting it's previous and current Position.

My use case is a remote pair programming extension for vscode. As with all real time, remote collaboration tools (e.g. Google Drive, Office 365 etc), when a shared document opens each participant can see what the other participants are doing within this document. From what I've seen, these tools visualise this with cursors, with each participant seeing a coloured cursor controlled by someone who at the same time is editing the shared document.

Please let me know if you'd need more info on this.

**Comment by alexandrudima** [comment]
You could perhaps use `window.createTextEditorDecorationType` together with `TextEditor.setDecorations` to create a text editor decoration that resembles a cursor. You could use such decorations for "remote" cursors.

**Comment by vvatikiotis** [comment]
Thx, I'll report my findings.
