### ISSUE TITLE
Markdown styles: Can't use style sheet that contains "#" in the local path

### ISSUE THREAD

**Issue by kurehajime** [Microsoft/vscode#3613]
Can't use style sheet that contains "#" in the local path.

OK

```
{
    "markdown.styles": ["file://C:/CSharp/user.css"]
}
```

NG (net::ERR_FILE_NOT_FOUND)

```
{
    "markdown.styles": ["file://C:/C#/user.css"]
}
```

OK

```
{
    "markdown.styles": ["file://C:/C%23/user.css"]
}
```

Is this by design or a bug?

---

Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:10:11.194Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
WIndows 7

**Comment by bpasero** [comment]
Might be a bug when we inject the stylesheet into the markdown preview.

**Comment by bpasero** [comment]
@kurehajime does it work with "C:\C#\user.css"

**Comment by kurehajime** [comment]
>@kurehajime does it work with "C:\C#\user.css"

It was the same.

---

OK

```
{
	"markdown.styles": ["C:/CSharp/user.css"]
}
```

NG (net::ERR_FILE_NOT_FOUND)

```
{
	"markdown.styles": ["C:/C#/user.css"]
}
```

OK

```
{
	"markdown.styles": ["C:/C%23/user.css"]
}
```

**Comment by bpasero** [comment]
@kieferrm fyi this might be fixed now?
