### ISSUE TITLE
Bug: Not found files

### ISSUE THREAD

**Issue by vladknp** [Microsoft/vscode#36131]
Bug Error install VS Code. Not found files:
- http://take.ms/wgfdT
- http://take.ms/rEWUw
- http://take.ms/BJfzF
- http://take.ms/apmYe
- http://take.ms/svyH1
- http://take.ms/D1aQU

- VSCode Version: 1.17.1
- OS Version: Windows7 Corporate

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by vladknp** [comment]
Error install VS Code.

**Comment by egamma** [comment]
The links in the description point to screenshots that illustrate the install problem.

**Comment by joaomoreno** [comment]
Can you try to fully uninstall, redownload and reinstall Code? Does the issue still happen?

**Comment by vladknp** [comment]
@joaomoreno 
Uninstall Code, remove old files and  again install Code did not help.

**Comment by joaomoreno** [comment]
@roblourens Why is `vscode-chrome-debug-core` still alive after Code quit?

**Comment by roblourens** [comment]
It says "the system cannot find the path specified", it looks like those files are missing during install? I don't know why that would be? I don't think the debug adapter is using them, if that's what you mean.

**Comment by vladknp** [comment]
@roblourens, @joaomoreno 
Doesn't matter version Node and npm in system?

**Comment by joaomoreno** [comment]
Is your Windows user name in cyrillic?

**Comment by vladknp** [comment]
No, Latin. 
It used to be installed and updated without problems.

**Comment by joaomoreno** [comment]
> Uninstall Code, remove old files and again install Code did not help.

When you say _again install Code_... does it fail on that very first installation after a complete removal?

**Comment by joaomoreno** [comment]
Oh I see what this is...

You're hitting a long path issue, which our setup framework suffers from. Please try to put the installation on a shorter path location. That will succeed.

---

There is something wrong in those paths since `node_modules\vscode-debug-chrome-core` appears twice in the path. I can investigate.

**Comment by roblourens** [comment]
That segment showing up twice is my issue. `vscode-chrome-debug-core` contains another npm module for test which has `vscode-chrome-debug-core` as a dependency, and it's pulling the localization files in twice.

**Comment by joaomoreno** [comment]
That's good. @vladknp Can you try out our [insider release](https://code.visualstudio.com/insiders), which should have @roblourens' fix?

**Comment by vladknp** [comment]
@joaomoreno, @robertohuertasm,
Thank you! I am clear all and install to c:\Microsoft VS Code. It is all good.
