### ISSUE TITLE
StartDebugSession in vscode API

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#36132]
Currently there is only `[startDebugging](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5943)` in our vscode api. There is no notion of startDebugSession, even though I see that the extension host debug service is implementing it [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDebugService.ts#L101)

Is there a plan to expose this in the API or should we remove this code?

**Comment by weinand** [comment]
This is an obsolete leftover from my first cut of the debug API where I had a `startDebugSession` function. This has become obsolete after the introduction of the `DebugConfigurationProvider`.
@isidorn please remove.
