### ISSUE TITLE
Git "modified" badge not using "badge.background" token

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#36133]
- VSCode Version: Code - Insiders 1.18.0-insider (c098b394b07afbb58975ab609117a0e115c5a3fa, 2017-10-12T05:11:23.795Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
tslint|eg2|1.0.11
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.7.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.29.1
Align|ste|0.2.0
ayu|tea|0.8.0
change-case|wma|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Modified file in file tree in a Git-managed project now has a small "M" badge
2. This is using the default blue badge color, not the color defined in the workbench as `badge.background`
3. Either it should, or please provide a new workbench key to hook into workbench theme.

<img width="332" alt="screen shot 2017-10-12 at 9 20 33 am" src="https://user-images.githubusercontent.com/835148/31498529-22d9133c-af30-11e7-92b5-6860dbcbc3fa.png">

**Comment by jrieken** [comment]
It's kind of work in progress. Above screen shot is from an old version that uses the icons, git uses. In a more recent version we render a badge in colors defined via `git.color.modified` and `git.color.untracked`
