### ISSUE TITLE
Suggestion: use webpack's entry to provide intellisense

### ISSUE THREAD

**Issue by nico-onmap** [Microsoft/vscode#36135]
Right now I am working on two webpack ES6 projects (that are in two different browsers).

project2 has project1 as node dependency and it's linked using `npm link project1`.

The problem is that project1 has this in package.json:

```json
{
main: 'dist/build.js'
}
```

Here is the entry inside `webpack.config.js

```js
{
entry: 'src/main-es6.js'
}
```

So if, in project2, I have this code:

```js
import { foo } from 'project1';

let bar = new foo();
```

VSCode will use `project1/dist/build.js` for Intellisense. And since this is the built file, it won't be able to provide autocomplete for modules/functions from project 1: I cannot use `clickto definition`.

Changing main to point to `src/main-es6` would allow VSCode to provide correct Intellisense but then I cannot build project2 anymore.

I think it would fix the problem if vscode could use the webpack's `entry` for intellisense entry point instead of using the package.json's `main` file.

**Comment by mjbvz** [comment]
Possibly #16320

Can you try setting up a `jsconfig.json` and configuring the `paths` for your module: https://github.com/Microsoft/vscode/issues/16320#issuecomment-320544078

**Comment by nico-onmap** [comment]
@mjbvz Which path? The paths appear to be fine to me. The problem is the way Intellisense resolves modules (by using the main property inside the package.json file).

**Comment by nico-onmap** [comment]
I didn't know you could put paths to a file and not only pathpart in `jsconfig.json`. I was able to fix my problem using this configuration;

```json
{
    "compilerOptions": {
        "target": "es2016",
        "module": "es6",
        "baseUrl": ".",
        "paths": {
            "athenajs": [
                "./node_modules/athenajs/js/athena-module"
            ]
        }
    }
}
```

This way the `package.json` main property is used as expected at runtime, and VSCode uses the alias I put in `jsconfig.json` instead.

Problem solved! :)
