### ISSUE TITLE
Bug report: Missing error context after passing webworker

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/vscode#36130]
I found this bug while debugging monaco in chrome.

As you can see, after JSON.stringify(msg), the Error instance is not transformed into a string, thus, the error message is lost.
![image](https://user-images.githubusercontent.com/5390719/31497967-492ea8cc-af93-11e7-8b05-1b7ad4b8f857.png)

https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/worker/simpleWorker.ts#L176

**Comment by Jack-Works** [comment]
use ```if(msg.err) (<any>msg.err).detail = msg.err.detail.message``` or something like this

**Comment by alexandrudima** [comment]
Moved to https://github.com/Microsoft/monaco-editor/issues/646
