### ISSUE TITLE
Unable to "Start Debugging - F5" with PowerShell script file

### ISSUE THREAD

**Issue by jkavanagh58** [Microsoft/vscode#36139]
- VSCode Version: Code - Insiders 1.18.0-insider (c098b394b07afbb58975ab609117a0e115c5a3fa, 2017-10-12T05:24:34.433Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
referenceshelper|gay|0.2.0
PowerShell|ms-|1.4.3
team|ms-|1.122.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Create New file add simple $psversiontable and Press F5
2. After delay Error banner indicates "Timed out waiting for the PowerShell extension to start."

Reproduces without extensions: No - Debug starts after disabling extensions

**Comment by isidorn** [comment]
Please file this against the powershell extension here https://github.com/PowerShell/vscode-powershell

Thanks
