### ISSUE TITLE
crashes a lot with too many (>=20) files opened in working files

### ISSUE THREAD

**Issue by AndyYSWoo** [Microsoft/vscode#3614]
running on OS X Yosemite 10.10.5

**Comment by isidorn** [comment]
What version of vscode are you running?
Have you actually set `"explorer.workingFiles.maxVisible": 20` in settings? Or you just mean when you open more than 20 files? Do you see this for all workspaces, or only for one? Is it possible to share that workspace?

**Comment by AndyYSWoo** [comment]
I am using version 0.10.9. Setting maxVisible doesn't seem to help. I am reading the spring framework
 source code the AOP part. The files I open are as follows: ExposeInvocationInterceptor.java, MethodBeforeAdviceInterceptor.java, AspectJAfterAdvice.java, AspectJAfterThrowingAdvice.java, AspectJAroundAdvice.java, ConfigBeanDefinitionParser.java, AopNamespaceUtils.java, AopConfigUtils.java, ParserContext.java, ReaderContext.java, AspectJAwareAdvisorAutoProxyCreator.java, AbstractAdvisorAutoProxyCreator.java, AbstractAutoProxyCreator.java, ProxyProcessorSupport.java, ProxyFactory.java, DefaultAopProxyFactory.java, ObjenesisCglibAopProxy.java, CglibAopProxy.java, AdvisedSupport.java, ProxyConfig.java. It's freaking me out cause every time vscode crashes I have to find and reopen those files in the working files window again.

**Comment by bpasero** [comment]
@AndyYSWoo does it also crash when you disable all extensions (start with --disableExtensions)?

**Comment by bpasero** [comment]
@AndyYSWoo ping, can you answer to the following questions please:
* any extensions installed?
* are you opening a workspace folder or just individual files
* is it possible to share the workspace with us

**Comment by AndyYSWoo** [comment]
ah, sorry for the delay

1. no i haven't installed any extension
2. a workspace folder
3. the workspace is https://github.com/spring-projects/spring-framework,
files i open are as described before

2016-03-08 1:01 GMT+08:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
@AndyYSWoo thanks, I am not able to reproduce a crash here nor do I see an increase in CPU/memory usage. Could you watch CPU/memory in activity monitor when you work on the workspace to see if a certain action causes a big spike suddenly? I suspect the crashes to be caused by out of memory.

**Comment by AndyYSWoo** [comment]
i think most crashes happen when i minimize the window and work on the
keynote or read some website for a not short while. Recently i haven't work
on this project, but i'll try to reproduce the crash and save my working
environment for you.

2016-03-08 18:37 GMT+08:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
@AndyYSWoo thanks. maybe if possible you could also share your global and/or workspace settings.

**Comment by bpasero** [comment]
I also assume you are not running a task in the background with Code right?

**Comment by AndyYSWoo** [comment]
I think all my settings are default.no i only use it to read the source
code.
just now it crashes again.
here's the screenshot
2016-03-08 18:55 GMT+08:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
Unfortunately at the time the crash shows in the UI, the process that consumes much memory (the window with your workspace) is already killed and would not show up in the activity monitor. 

When you use Code normally on that workspace can you check if the memory goes up steadily? The critical memory size is 800-1000 MB I would say.

**Comment by bpasero** [comment]
@AndyYSWoo curious, does it happen when you are not adding any file to working files?

**Comment by AndyYSWoo** [comment]
yes... most cases are when i am not even looking at the vscode window then
after a while it happens. The normal memory use is around 100~130 MB and I
haven't noticed any abnormal increase.

2016-03-09 23:57 GMT+08:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
@AndyYSWoo another theory I have is that maybe it happens always in the same file when the editor colors the file. These coloring rules are defined with regular expressions and certain input might cause bad things to happen. Next time it happens it would be interesting if you could remember the file you wanted to open. 

Another guess I had is git: We periodically do something in the background. It is unlikely this would cause the crash, but to outrule this, can you see if setting `git.enabled: false` still causes crashing?

**Comment by AndyYSWoo** [comment]
ok I'll try.

2016-03-10 23:27 GMT+08:00 Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
@AndyYSWoo we just released a new insiders build, maybe you could try with that: http://code.visualstudio.com/insiders

It shows up as green logo in the taskbar as opposed to the blue one.

**Comment by AndyYSWoo** [comment]
Alright, I'll see if this version solve this problem.

2016年3月17日星期四，Benjamin Pasero <notifications@github.com> 写道：

**Comment by bpasero** [comment]
Any success?
