### ISSUE TITLE
Do not execute multiple shell commands from task

### ISSUE THREAD

**Issue by JerryMS** [Microsoft/vscode#36146]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.3.1
cpptools|ms-|0.13.1
perforce|sle|2.2.1

Multiple shell commands not executed from task:
output in terminal: 

At line:1 char:35
cmd.exe /c build.bat CLEAN & build.bat NAND
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
    CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : AmpersandNotAllowed
---

Steps to Reproduce:

1. define shell task with "command": "cmd.exe /c build.bat CLEAN \\"&\\" build.bat NAND"
2. execute task

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
What is your default shell for the integrated terminal ?

**Comment by JerryMS** [comment]
The default is PowerShell

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.

**Comment by dbaeumer** [comment]
Wrong issue

**Comment by alexr00** [comment]
It is possible to do this, you just need to make sure the escaping makes it all the way to the terminal:

    "command": "cmd.exe /c cd ..\\ \\\"&\\\" dir",
