### ISSUE TITLE
Toggle Line Comment places cursor incorrectly

### ISSUE THREAD

**Issue by AiryShift** [Microsoft/vscode#36147]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open a blank file
2. Change language to a language with line comments that are formed with characters at the beginning of a line (e.g. C or Python but not HTML)
3. Press the keyboard shortcut that invokes `editor.action.commentLine`

For example, if the language mode was Python this would make the first line:

`#<space>` where `<space>` is a literal space character. However the cursor is placed _before_ the `#`.

Similarly, using C the language mode:

`//<space>`. The cursor is placed before the first `/`.

This behaviour does not occur with an earlier version (tested 1.16.0 on commit aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad)

Reproduces without extensions: Yes

**Comment by egamma** [comment]
You are still on 1.17 this has been fixed in 1.17.1, please reopen if this is not the case.
