### ISSUE TITLE
Terminal "clear" bug

### ISSUE THREAD

**Issue by pkunitsky** [Microsoft/vscode#36144]
- VSCode Version: 1.17.1
- OS Version: Windows 10

Fix terminal "clear" bug.
Terminal aint cleared, but caret moves to top.

**Comment by maxibanki** [comment]
How do you try to clear the Terminal? I don't see any button which should be the ability to do this.
The trash icon is to kill the terminal, the `x` to close the terminal and the arrow up to maximize it.

**Comment by omril1** [comment]
Could you provide more information about it? Are you using a command? If so, on which terminal is that?

**Comment by coreh** [comment]
> How do you try to clear the Terminal? I don't see any button which should have the ability to do this.
> The trash icon is to kill the terminal, the x icon to close the terminal and the arrow up to maximize it.

@maxibanki Cmd+K (Or Ctrl+K on Windows)

**Comment by maxibanki** [comment]
Can you reproduce it?
In my environment:
- VSCode Version: Code - Insiders 1.17.0-insider (7ac1f1e05baad03d4dd8f8515f1e598180b2c97e, 2017-09-30T05:06:21.234Z)
- OS Version: Windows_NT x64 6.1.7601

It works without any problems.

**Comment by pkunitsky** [comment]
I'm using embedded git bash terminal and command "clear" to work with node.js. I faced that problem after the latest update (1.17.1).

**Comment by mklement0** [comment]
There are several related issues:

* Apparently, using shell-native `cls` / `Clear-Host` only clears the _current screen_ (one screen's worth of output), while preserving the rest of the scrollback buffer.

* By contrast, `workbench.action.terminal.clear`  clears bot the current screen _and_ the scrollback buffer. There is currently no UI element to invoke this command (though the suggestion has been made - see #30077), so a keyboard shortcut is required.

* `Ctrl+K` _should_ work on Windows, but apparently doesn't as of 1.18 (even though the UI suggests it should; observed on W7x64); workaround: place the default definition at the end of your `keybindings.json` file.

```json
  {
    "key": "ctrl+k",
    "command": "workbench.action.terminal.clear",
    "when": "terminalFocus"
  }
```

**Comment by cnavarro16** [comment]
Can confirm that adding the default definition for workbench.action.terminal.clear at the end of the keybindings.json file did the trick.
