### ISSUE TITLE
Intellisense not working properly while building an object "step by step" instead of the shorthand notation {property:"value"}

### ISSUE THREAD

**Issue by darknessm0404** [Microsoft/vscode#36143]
- VSCode Version: 1.17.0
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Make a javascript file with that content: 

```
var a = {};
a.test = 1234;

var b = {
    test: 1234
};
```

2. type `b.` to trigger intellisense, it will show "test" as a property and know it's a number
3. type `a.` to trigger intellisense, it will only list all available keywords in the javascript file, without understanding that a has a property named "test"

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is tracked by https://github.com/Microsoft/TypeScript/issues/10868 upstream

Closing as upstream
