### ISSUE TITLE
QuickOpen / Go To File keyboard shortcut behavior changed with 1.17

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#36156]
I just upgraded to 1.17 (an then 1.17.1 shortly after) on Windows 7. The first odd thing I noticed is my CTRL+P shortcut for quickly opening a file doesn't work anymore.

Instead at the bottom in the status bar I see:

`(Ctrl + P) was pressed. Waiting for a second key or chord...`

Okay, that's strange. I didn't change anything. I just restarted VSCode after the upgrades and now it's doing this.

Next I looked in the "Go" menu and see:

![screenshot 192](https://user-images.githubusercontent.com/87356/31511070-c8ab203a-af43-11e7-88ec-5e8098f92f41.jpg)

Okay so that is normal. Next looking in shortcuts:

![screenshot 193](https://user-images.githubusercontent.com/87356/31511078-cbd5f528-af43-11e7-8bf6-1c31257c1d0a.jpg)

Okay so is QuickOpen the same thing as Go To File in the menu? Because CTRL+P is definitely not doing that anymore even though the setting appears correct. CTRL+E does work though as QuickOpen. I don't remember ever setting CTRL+E to be QuickOpen. I'm not sure if that was always there as a default option or not.

I upgraded to 1.17 on my MacBook and this bug did not present itself. Everything seemed normal there.

**Comment by isidorn** [comment]
Just search in your keybinding for Ctrl + P
There is probably some extension which is stealing your keybinding.
Try disabling all your extensions and you will not be able to reproduce. You can also try with vscode inisders https://code.visualstudio.com/insiders/

**Comment by Jakobud** [comment]
The only thing I see in my `keybindings.json` for `ctrl+p` is `workbench.action.quickOpen` and `-workbench.action.quickOpen`. I see the same thing for `ctrl+e`. 

I went ahead and just removed the `ctrl+e` entries and everything appeared to go back to normal. Not sure what happened exactly but I guess you can close this unless you want me to investigate more.
