### ISSUE TITLE
The Visual Studio Code icon... Really become really ugly.....

### ISSUE THREAD

**Issue by gclove** [Microsoft/vscode#36152]
![](https://i.imgur.com/RoRMxHm.png)

Perhaps orange represents the future of quantum computing ?

---

But, indeed, this drab color, brown yellow, is out of tune with other colorful icons.

At the very least, you should provide custom configuration that allows me to replace icons.

Such as an anime beauty? 😂  Ha ha ha!

---

By the way, Icon graphics are ugly, too !

I think at least *blue* and *brown*, or *purple*！

**Comment by maxibanki** [comment]
Same as in #35783 please close your issue

**Comment by Leedehai** [comment]
The icon for VSCode 1.16 (the original one) is [here](https://github.com/Leedehai/nostalgia-vscode).

**Comment by dankellett** [comment]
Disagree
