### ISSUE TITLE
High CPU consumption even with extensions disabled

### ISSUE THREAD

**Issue by diminutivesloop** [Microsoft/vscode#36159]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
find-related|eam|0.5.0
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
Angular2|joh|2.7.0
vscode-duplicate|mrm|1.2.0
debugger-for-chrome|msj|3.3.1
vscode-code-outline|pat|0.0.11
testcafe-test-runner|rom|1.4.0
annotator|ryu|0.10.1
vscode-open|san|0.1.0
vim|vsc|0.10.1
gitblame|wad|2.2.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

VSCode CPU usage will occasionally spike and continue doing so even after a re-launch. Usually I must restart my computer to fix the issue.

![vscode startup cpu usage](https://user-images.githubusercontent.com/667716/31512295-6358ead6-af58-11e7-9402-d75d09116870.PNG)

Reproduces without extensions: Yes

**Comment by egamma** [comment]
@diminutivesloop we need more information to track down this performance issue, please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for the information we are looking for.
