### ISSUE TITLE
TSQL Reserved word Coloring

### ISSUE THREAD

**Issue by Calidus** [Microsoft/vscode#36151]
- VSCode Version:  1.17.0
- OS Version: Win10 Pro 

Steps to Reproduce:

1. Create/Open a .sql file in Visual Studio Code
2. Write a SELECT statement that contains a 'CASE ','WHEN','ELSE','THEN','END'
3. 'CASE ','WHEN','ELSE','THEN','END' don't have reserved word coloring applied to them

Happens with all themes that are bundled with the install.
Reproduces without extensions: Yes

**Comment by aeschli** [comment]
duplicate of https://github.com/textmate/sql.tmbundle/issues/21
