### ISSUE TITLE
Blue Screen when opening VS Code and VS 2017 at the same time

### ISSUE THREAD

**Issue by fedeantuna** [Microsoft/vscode#36163]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
none|-|-

When I open Visual Studio 2017 Enterprise and Visual Studio Code at the same time and in that order, the system crashes (the entire system, Windows crashes with SYSTEM_SERVICE_EXCEPTION). Apparently it doesn't the other way around (if I open first VS Code and the VS 2017). It happened in two computers until now. I hope you can fix this, it started to happen recently. I use both all the time and this is really bad.

---

Steps to Reproduce:

1. Open Visual Studio 2017 Enterprise (latest versión to 10/12 - October 12th - )
2. Open Visual Studio Code
3. Wait one or two minutes

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by fedeantuna** [comment]
I had not extensions and a clean fresh Windows 10 Professional (I reinstalled everything after the first time it happened). And in previous versions I had 0 trouble doing that, could it be some upgraded or new feature?

**Comment by bpasero** [comment]
Still happens?

**Comment by fedeantuna** [comment]
I'm sorry, I forgot to tell here, I updated everything as soon as an update was available (Windows, Visual Studio and Visual Studio Code) and now is not happening anymore.
