### ISSUE TITLE
MacOS git ssh credential problems

### ISSUE THREAD

**Issue by pos42** [Microsoft/vscode#36168]
I was locked out by my firewall as it has rate limiting on SYN packets. Then I as a bunch of other people discovered the flag  “git.autofetch" in VScode that was set to true. Setting it to false and the problem was gone.

This however makes me wonder if there is a VScode bug….

I have SSH keys and can in the terminal on my MAC log in to the git host over SSH with just the public key. I have no password dialogs whatsoever. Setting git.autofetch to false it works and talk to the remote git repo with no password dialogs. When git.autofetch is true it also works if I remove rate limiting of SYN packets in the firewall between my client MAC and the Linux git repo host.

The problem is that VsCode open up a huge amount of SSH sessions. Why should it? The public key login works flawlessly…

“git config credential.helper” shows “osxkeychain”

What am I missing here? Or is this another potential bug?

VSCode Version: 1.17.1
OS Version: MacOS High Sierra 10.13

Tnx in advance

/Peo

**Comment by pos42** [comment]
When disabling the rate limiting or sitting at home behind the firewall it looks like this with git.autofetch set to true. Why does it open som many sessions in just a few seconds? Also it can be a lot more than this..... 

From the log of the git ssh host

Oct 12 23:34:37 daedalus sshd[16401]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56315 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:37 daedalus sshd[16401]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:37 daedalus sshd[16407]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56315:11: disconnected by user
Oct 12 23:34:37 daedalus sshd[16407]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56315
Oct 12 23:34:37 daedalus sshd[16401]: pam_unix(sshd:session): session closed for user sjoh Oct 12 23:34:37 daedalus sshd[16403]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56316 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:37 daedalus sshd[16405]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56317 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:37 daedalus sshd[16405]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:37 daedalus sshd[16403]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:37 daedalus sshd[16421]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56317:11: disconnected by user
Oct 12 23:34:37 daedalus sshd[16421]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56317
Oct 12 23:34:37 daedalus sshd[16405]: pam_unix(sshd:session): session closed for user sjoh
Oct 12 23:34:37 daedalus sshd[16422]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56316:11: disconnected by user
Oct 12 23:34:37 daedalus sshd[16422]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56316
Oct 12 23:34:37 daedalus sshd[16403]: pam_unix(sshd:session): session closed for user sjoh
Oct 12 23:34:37 daedalus sshd[16418]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56318 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:37 daedalus sshd[16418]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:38 daedalus sshd[16446]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56318:11: disconnected by user
Oct 12 23:34:38 daedalus sshd[16446]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56318
Oct 12 23:34:38 daedalus sshd[16418]: pam_unix(sshd:session): session closed for user sjoh
Oct 12 23:34:38 daedalus sshd[16445]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56319 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:38 daedalus sshd[16445]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:38 daedalus sshd[16459]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56319:11: disconnected by user
Oct 12 23:34:38 daedalus sshd[16459]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56319
Oct 12 23:34:38 daedalus sshd[16445]: pam_unix(sshd:session): session closed for user sjoh
Oct 12 23:34:42 daedalus sshd[16471]: Accepted publickey for sjoh from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56320 ssh2: RSA SHA256:3yJ3gp0wyBfPsefl1efGs12kwiDZw8fCviuKI/N8hHk
Oct 12 23:34:42 daedalus sshd[16471]: pam_unix(sshd:session): session opened for user sjoh by (uid=0)
Oct 12 23:34:43 daedalus sshd[16473]: Received disconnect from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56320:11: disconnected by user
Oct 12 23:34:43 daedalus sshd[16473]: Disconnected from 2001:470:dc5d:1:7c5d:c717:2b9:bd97 port 56320
Oct 12 23:34:43 daedalus sshd[16471]: pam_unix(sshd:session): session closed for user sjoh

**Comment by joaomoreno** [comment]
We will disable auto fetch: #34684
