### ISSUE TITLE
[html] Add option to configure formatter

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#3616]
It would be great if the auto-formatters could be configured. I am happy with most settings but some settings keep me from using it (in my case: "long" lines in HTML are automatically converted to multiple lines even though they should be kept intact).

**Comment by aeschli** [comment]
As all formatters are different and configured separately, we'd need a issue per formatter.
Ok if I use this issue for html?

**Comment by lafe** [comment]
No problem. As I looked through the code, I suspected as much.

**Comment by Mine02C4** [comment]
+1
In HTML, newline character has a meaning. There is a case where at the time of formatting trouble changing the line break position.

**Comment by aeschli** [comment]
Implemented for the March release. You can now configure all options offered by the foematter (beautify-html)
