### ISSUE TITLE
Format newly created file without saving it.

### ISSUE THREAD

**Issue by kkorus** [Microsoft/vscode#36165]
Why I can't format newly created file without saving it? I just want to create new "Untitled-1" file, change "Language Mode" and have option to format code.

**Comment by maxibanki** [comment]
Hi,

on my enviorment it is working. Ctrl+N => Create a new file, paste code, Ctrl+Shift+F => Format the document.

**Comment by kkorus** [comment]
I have noticed. It works for JavaScript, but can't from C# code.

**Comment by jrieken** [comment]
This is extension business, not a limitation of the editor or its API. Closing as extension candidate...
