### ISSUE TITLE
code blocks not collapsible in markdown files

### ISSUE THREAD

**Issue by pangrr** [Microsoft/vscode#36169]
- VSCode Version: 1.17.1
- OS Version: Windows 7

Steps to Reproduce:

1. Write a `.md` file in vscode with code blocks.
2. Code blocks are not collapsible.

Reproduces without extensions: Yes

I practice [literate-programming](https://github.com/pangrr/literate-programming) and write markdown `.md` files with code sewed inside documents. 
It would be great to make code blocks in markdown files collapsible so that I can focus on document.

**Comment by mjbvz** [comment]
Requires #3422
