### ISSUE TITLE
Broken message parsing from linter extensions [vscode 1.17.1]

### ISSUE THREAD

**Issue by vvzvlad** [Microsoft/vscode#36179]
Operating System and version: Mac OS 10.13
VS Code version: 1.17.1
ms-vscode.cpptools: 0.13.1
mitaki28.vscode-clang: 0.2.2
jbenden.c-cpp-flylint: 0.2.7

The problem is that I do not see errors from two extensions-linter. I write the wrong code, and the linter from ms-vscode.cpptools highlights it, and both other extensions (of course, I include them separately from each other) are silent, as if everything is in order.

I can see the messages from jbenden.c-cpp-flylint on the "Output" tab by selecting the "C / C ++ Flylint" drop-down menu, but I do not see them on the "Problems" tab.
![image](https://user-images.githubusercontent.com/3315944/31524041-c0d8aafe-afbf-11e7-87c2-966d22cf37d6.png)
![image](https://user-images.githubusercontent.com/3315944/31524047-c5a3ae26-afbf-11e7-8ffb-424c0b1b7ec7.png)

I think the code responsible for parsing the message from clang has broken.
Can you suggest further steps to test this theory?

[settings.zip](https://github.com/Microsoft/vscode/files/1381031/settings.zip)

**Comment by sandy081** [comment]
@vvzvlad Could be an issue in the extensions, Please file an issue against corresponding extensions
