### ISSUE TITLE
VS Code Terminal Kerning Way Off after latest update - 1.17.1

### ISSUE THREAD

**Issue by alohaninja** [Microsoft/vscode#36172]
Can you please fix the kerning in the terminal - it's so far off! It's driving me nuts. The font in the editor should be the same as the font in the terminal. It's killing me...

![terminal vscode2](https://user-images.githubusercontent.com/26234626/31521549-823c7fbe-af6f-11e7-8e49-e90fb901c70b.png)

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|5.6.3
tslint|eg2|1.0.11
beautify|Hoo|1.1.1
docthis|joe|0.5.0
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
PowerShell|ms-|1.4.3
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0
vscode-hexdump|sle|1.4.0
vscode-jumpy|wma|0.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No
![image](https://user-images.githubusercontent.com/26234626/31521404-09f80fc8-af6f-11e7-9867-03b985feff77.png)

**Comment by VsTB** [comment]
INGMASTER© SERVER 
IMS™ Home free network
Hosting ITT internet provider
GIALGIAY MOHK INGUSHETIA MALGOBEK
INGMASTER©
Development of web sites VGroup
Classify the system administrator
77.87.103.230 IMS™


vstb@gialgiay.ru
+79287273737

**Comment by alohaninja** [comment]
Looks like the editor has a setting `"editor.letterSpacing"` but that doesn't exist for integrated terminal...

`"terminal.integrated.letterSpacing"` should be added or fix the spacing between the letters to match the editor.

**Comment by alohaninja** [comment]
this does seem to be rendering correctly using [VS Code insiders](https://code.visualstudio.com/insiders/)...thanks for the quick fix!

**Comment by Tyriar** [comment]
Sorry about the hassle, this one was tracked in https://github.com/Microsoft/vscode/issues/35991
