### ISSUE TITLE
'Open in Terminal' option greyed out (for node.js launch), Windows 10, Uncertain Cause

### ISSUE THREAD

**Issue by metabench** [Microsoft/vscode#36178]
This started just after the latest update, but I had also replaced my code folder.

Having the option greyed out shows that somewhere it is detected it can't be opened in the terminal. It may be worth making it detect that problem and try to fix it. The node.js addon(s) are installed by default.

**Comment by metabench** [comment]
My problem was solved. I had opened the code directory from a network share path, rather than a local one.

At some stage, cmd (or something similar) gets called, this takes place within the option of using a powershell internal terminal too. Support for UNC paths looks like it would solve the issue, but I don't know how difficult that would be to add/integrate.

**Comment by Tyriar** [comment]
@metabench to clarify, was your issue around debugging not supporting UNC in some capacity?
