### ISSUE TITLE
Keep scroll position when going between normal <> changes editor

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#36176]
- VSCode Version: Code - Insiders 1.18.0-insider (c098b394b07afbb58975ab609117a0e115c5a3fa, 2017-10-12T05:11:23.795Z)
- OS Version: Darwin x64 16.7.0
- Extensions: A few

Steps to Reproduce:

1. Open file with changes
2. Scroll down to second change
3. Click 'Open Changes' in editor toolbar
4. -> Change editor opens at a different scroll position
5. Scroll down to second change
6. Click 'Open File' in editor toolbar
7. -> File editor opens at a different scroll position

It would be great if the editors opened at the same scroll position as the previous one.

**Comment by joaomoreno** [comment]
@bpasero This was working fine just last week. I just launched Code, the insiders version from last Thursday and it was working correctly. As soon as I got today's update, I could reproduce @chrmarti 's issue. Are you aware of any changes?

**Comment by joaomoreno** [comment]
Selection works. Scroll position not yet.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
