### ISSUE TITLE
FileSystemProvider: root folders automatically added to workspace

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#36177]
- VSCode Version: Insiders (c098b394b07afbb58975ab609117a0e115c5a3fa)
- OS Version: OS X 10.12.6

1. Run an extension that registers a filesystem provider with e.g. root "foo://bar" (using the proposed API).
2. Open a workspace that does not mount the root path directly, e.g. `"uri": "foo://bar/delta"`.
3. Observe that vscode will often automatically add "foo://bar/" to the workspace.

**Comment by jrieken** [comment]
Yeah, that's the current design. Whatever the provider gives us a `root` will be added as workspace folder. It was done because it's pragmatic but also somewhat the right think to do IMO. I have plans to register a provider not just for a scheme, but for a root. So the property would move out of the provider, allow you to reuse a single provider for multiple roots and also making it more clear what register does...

@siegebell Thoughts?

**Comment by siegebell** [comment]
@jrieken I'd like to have a clear distinction between provided file systems and workspace folders. Automatically adding the root implies that every provided file system should be a (project) folder. (Or that every subproject should have a provided file system... but that's just silly -- it doesn't make sense for an extension to determine each subproject to provide.)

In my case, a root will contain many (many!) subprojects, and I want to select just a small subset to display in the explorer. Also having the root just gets in the way. And it is very disorienting when a folder is automatically added to a workspace, especially when I explicitly removed it before.

> It was done because it's pragmatic but also somewhat the right think to do IMO.

I bet there's no nice way to get widows/mac/linux file-select widgets/dialogs to work with provided file systems :(. But ideally, there would be a UI to browse the remote file tree and select which folders to add to the workspace.

I personally like editing the JSON directly, so I think this would be a cool use case for path completion in JSON (hooking into the registered file system providers).

But if you're going for better discoverability, would it be enough to provide an explorer command where one can manually select to add a root? And another command that adds the currently-selected folder in the explorer as a workspace folder. (And finally, the root can be removed.)

> I have plans to register a provider not just for a scheme, but for a root.

I don't follow. You mean multiple providers would be registered for the same scheme, but providing different roots? And when you say "scheme" here, do you mean "scheme"+"authority"?

**Comment by siegebell** [comment]
On path completion of Uris in workspace files, the closest existing feature request I found was #5202.

**Comment by jrieken** [comment]
> I don't follow. You mean multiple providers would be registered for the same scheme, but providing different roots? And when you say "scheme" here, do you mean "scheme"+"authority"?

Yes. Think of ftp, it's unlikely that you own the whole space of ftp but it's likely that you own a slice which is usually called something like `ftp://your.server/some/path/to/your/user/files`. So, a ftp-uri, like `ftp://another.server/another.path` might not openable like that. It might require to setup, some auth etc. So now the questions is if that should happen while such uris are resolved or if an upfront, extension specific, config step is required.

**Comment by siegebell** [comment]
I can see the root being specific to the scheme and authority (e.g. username, hostname, port). And this is how I think it currently behaves? But what use case do you have in mind for having multiple providers handle different paths for the same scheme+authority?

For resolving/authenticating, here's what I currently do:
1. The user adds extension-specific settings declaring a list of connection profiles: hostname, username, a document root, and how the remote server should be set up (either a command to run or how to install it).
2. On extension activation, a provider is registered for each connection profile, but connections are not made.
3. When a provider handles a request to resolve a resource, it will first check if an open connection exists or is in the process of being made.
4. If not, it initiates and awaits the connection. (The user may be prompted for a password, 2-factor, etc., and an editor-server might be installed.)
5. Finally, the resource is resolved.

Here's an example profile:
```
{
  // This is what the hostname will look like to the user:
  "hostname": "remote",
  // The root Uri maps to this remote folder:
  "documentRoot": "/home/me/",
  // If specified, this will be the actual address/hostname
  "address": "my.server",
  "privateKey": "/Users/me/.ssh/id_rsa",
  // The server will be able to run build commands, notify us of file changes, etc.
  "deployServer": {
    "node": "/usr/bin/node",
    "installationPath": "/home/me/.remote-edit-server/",
    "extractZipCommand": "unzip -qo ${zip} -d ${dest}"
}
```

Let's say my extension claims to handle scheme "foo". It will register a filesystem with root "foo://remote/". An example Uri is "foo://remote/my/file", which will resolve to "/home/me/my/file" on host "my.server". A user would then create a workspace with multiple projects, without necessarily having multiple providers, like this:
```
"folders": [
  { "uri": "foo://remote/projectA" },
  { "uri": "foo://remote/projectB" },
  { "path": "a/local/projectC" }
]
```

**Comment by bolinfest** [comment]
I also seem to be hitting some sort of race condition where I get an `ENOENT` for my document root before I see any `stat()` or `readdir()` calls into my `FileSystemProvider`. (This is on Insiders 2018-01-05.) Any ideas where this check is being done?

**Comment by jrieken** [comment]
> Any ideas where this check is being done?

Depends... Usually, when things aren't ready yet (and that's the biggest source of timing issues I know) you get "no provider" (NOPRO) errors... The ENOENT error might thrown [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L164) which would mean that `provider#stat` didn't return anything we could deal with...

**Comment by jrieken** [comment]
So, as a first baby step I have made `FileSystemProvider#root` optional. So, if missing the provider is there but nothing will be added to the workspace.

**Comment by jrieken** [comment]
... and as second step we have proposed api to allow extensions to add a folder as workspace folder. With that we have all pieces in place and should be able to remove `FileSystemProvider#root` and let extension authors decide.

**Comment by amp343** [comment]
@bolinfest in your test, are you modifying the first workspace folder definition after the extension host is already started? Doing that caused behavior I wasn't expecting (including `ENOENT`) at first before I realized that action restarts the extension host/reactivates the extension. https://github.com/Microsoft/vscode/issues/44711#issuecomment-370863579

**Comment by jrieken** [comment]
I have pushed a change that removes `FileSystemProvider#root` which means registering a file system provider has no effects on the current workspace anymore. To restore the old behaviour and/or to add a (remote) folder to a workspace use the `vscode.workspace.updateWorkspaceFolders`-API.
