### ISSUE TITLE
`ext install <name>` doesn't work like it used to

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#36185]
You used to be able to use `ext install <name>` to install an extension. Now it instead just opens the extension pane and searches for the text supplied for `<name>`. That alone isn't a big deal, but you can't search the extensions pane for the name of an extension. 

For example, if I type `ext install gitlens`, it opens extension pane and searches for `gitlens` which returns no results -- even though the actual name of GitLens is `gitlens` as you can see here:

https://github.com/eamodio/vscode-gitlens/blob/4360c86197728430759ef1d7851ca0edfbd52110/package.json#L1-L15

As an aside, the only reason I ended up having the `displayName` being what it is, was because of poor searching. When it was just called *GitLens*, you couldn't find it when searching for `git` or `lens` or any other keywords. With any luck that would also be wonderful to have fixed -- because I'd love to set its `displayName` back to just *GitLens* and not have to *SEO* pack it.

Originally reported here: https://github.com/eamodio/vscode-gitlens/issues/160

**Comment by joaomoreno** [comment]
`ext install <name>` should never have worked in the first place, because there can be many versions out there with the same name. I could publish `joaomoreno.gitlens`.

> For example, if I type ext install gitlens, it opens extension pane and searches for gitlens which returns no results -- even though the actual name of GitLens is gitlens as you can see here:

This is the real issue.

@modigrv Why does searching for `gitlens` not return any results?

**Comment by eamodio** [comment]
@joaomoreno While I agree, that has always been the text command to install GitLens and while it has been replaced with the *Install* button on Windows & macOS, on Linux it still says `ext install gitlens`:

![image](https://user-images.githubusercontent.com/641685/31616381-94e8733c-b25a-11e7-92cc-e6ac71d5927d.png)

**Comment by joaomoreno** [comment]
And it has always been wrong, unfortunately. I have no idea why it was never changed.

@modigrv Can we also address this? We would profit much more from using a fully qualified name such as `ext install eamodio.gitlens`.

---

Also, even the Marketplace returns no results for `gitlens`:

https://marketplace.visualstudio.com/search?term=gitlens&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by sandy081** [comment]
Duplicates #26389

**Comment by joaomoreno** [comment]
@eamodio For now, add a `gitlens` tag to your extension, to start getting results when searching for `gitlens`. I'll try to push for a real fix meanwhile.
