### ISSUE TITLE
控制台中文bug

### ISSUE THREAD

**Issue by Yjq14114** [Microsoft/vscode#36184]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
FreeMarker|dco|0.0.9
xml|Dot|1.9.2
vscode-npm-script|eg2|0.2.1
json-tools|eri|1.0.2
beautify|Hoo|1.1.1
csharp|ms-|1.12.1
vetur|oct|0.9.11
java|red|0.11.0
vim|vsc|0.10.1

![image](https://user-images.githubusercontent.com/15209776/31526744-61bbc7ae-affb-11e7-9f81-a91c851684b8.png)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by JerryYu2014** [comment]
VS Code 1.17.1 has been repaired

**Comment by egamma** [comment]
Thanks @JerryYu2014 for helping with translation, closing.
