### ISSUE TITLE
Clicking links in terminal should focus the terminal when it's not focused

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36187]
https://twitter.com/colshacol/status/918542506870083584

**Comment by colshacol** [comment]
@Tyriar, thanks for making this issue! I was joking on Twitter and planned to come make it myself.

_Bug details:_

Version: **1.18.0-insider (1.18.0-insider)**

Description: **When** focus is _not_ in the integrated terminal **and then** a click is made in the integrated terminal **and** the click lands on a `ctrl+click`able link, _focus to the integrated terminal is not applied._

**Comment by Tyriar** [comment]
@colshacol haha, sarcasm doesn't translate so well to text sometimes 😄

**Comment by colshacol** [comment]
Why is the issue closed?

**Comment by Tyriar** [comment]
@colshacol the issue is fixed, it will be in v1.18.0
