### ISSUE TITLE
Program stopped after 3seconds launcher

### ISSUE THREAD

**Issue by jeffitoro** [Microsoft/vscode#36180]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.5
html-css-class-completion|Zig|1.10.2
html-snippets|abu|0.1.0
markdown-latex-renderer|agu|0.0.2
latex-preview|ajs|0.5.1
vscode-twig-pack|baj|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vue-snippets-js-html-pug-razor|heb|0.0.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.5
webpack|jer|2.0.2
latexcompile|mat|0.7.1
vetur|oct|0.9.11
laravel-blade|one|1.9.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.4
code-spell-checker|str|1.4.10
bootstrap4-vscode|the|2.4.0
latex-support|tor|1.0.1
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
@jeffitoro can you reproduce this when you disable all extensions by starting code as follows  ``code --disable-extensions`

**Comment by egamma** [comment]
@jeffitoro you have the https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion installed and it had some scalability issue. This has been addressed in 1.11 of the extension. Can you still reproduce the issue when you use this version of the extension?

**Comment by egamma** [comment]
Please reopen the issue if this problem has not been addressed by the extension improvement.
