### ISSUE TITLE
Problem with display of built-in terminal. (case of dual display)

### ISSUE THREAD

**Issue by sugiii8** [Microsoft/vscode#36181]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

---

Steps to Reproduce:

1. Dual Display(1: external display, 2: macbook pro retina display)
2. Open VSCode on [1]
3. Move VSCode to [2] 
4. Check built-in terminal
<img width="417" alt="vscode-terminal" src="https://user-images.githubusercontent.com/1410177/31526164-1282794e-b000-11e7-9940-0534d38224d4.png">

Reproduces without extensions: Yes/No

**Comment by sugiii8** [comment]
Additional:
If [1] and [2] reversed, this is reproducible.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
