### ISSUE TITLE
Only highlight the similar matches when double click.

### ISSUE THREAD

**Issue by TrangDinhVan** [Microsoft/vscode#36189]
Highlighting the similar matches is so useful, however I find it so distracting when working with HTML files.
Please make it behavior as Sublime Text, just trigger highlighting matches when DOUBLE CLICK.
Thanks!

**Comment by alexandrudima** [comment]
This can be turned off via `"editor.occurrencesHighlight": false`. If you would like to turn this off only for HTML, you can use language specific settings:
```
"[html]": {
    "editor.occurrencesHighlight": false
}
```
