### ISSUE TITLE
Support `args` in contributed keybindings

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#36196]
If you insert the following Codeblock to keybindings.json everything works fine:
```
            {
                "key": "ctrl+oem_2",
                "command": "editor.action.insertSnippet",
                "args": { "name": "scriptbrackets" }
            }
```
But if you try to insert this block to "keybindings-section" in a package.json of an extension it always calls the snippet selector dropdown (at the top of the window) and is NOT calling the snippet refered by the snippet name.

```
  "contributes": {
        "languages": [{
            "id": "f-script",
            "aliases": ["F-Script", "f-script"],
            "extensions": [".ff",".fs",".fss",".fx",".lb",".lbd",".lbf",".lbe",".lbi",".lbx",".config"],
            "configuration": "./language-configuration.json"
        }],
        "keybindings" : [
            {
                "key": "ctrl+oem_2",
                "command": "editor.action.insertSnippet",
                "args": { "name": "scriptbrackets" }
            }
        ]
	}

```

- VSCode Version: 1.17.0
- OS Version: WIN 10 PRO

Steps to Reproduce:
1. define a snippet
2. create a keybinding in keybinding.json
3. execute the keybinding in a file
4. try to move the keybinding to package.json.

Hope you can enable this feature also on language-extensions.

Raydir

**Comment by jrieken** [comment]
I know @bpasero added supported for `args` in keybindings customisation, tho unsure if it is @bpasero or @alexandrudima

**Comment by bpasero** [comment]
We just did not wire this in to the [`keybindingsRegistry`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/common/keybindingsRegistry.ts#L60) and [`keybindingsService`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L439). 

I see no reason why we could not or would not support this but I let @alexandrudima comment on that.

Maybe also an area for a first contributor PR.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31372
