### ISSUE TITLE
vscode的图标好难看，丑，一眼看去不知道是啥软件来的

### ISSUE THREAD

**Issue by zcnet4** [Microsoft/vscode#36191]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
GBKtoUTF8|buk|0.0.2
python|don|0.7.0
Lua|key|0.0.9
cpptools|ms-|0.13.1
vs-keybindings|ms-|0.1.7
debug|web|0.21.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
We do not speak chineese. Please file the issue in english with reproducable steps and we will reopen

**Comment by weihanglo** [comment]
He said the logo of VS Code is awful and not recognizable. 😅

**Comment by isidorn** [comment]
Duplicate of some issue. @weihanglo thanks for translating
