### ISSUE TITLE
Can't attach to node in Docker

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#36192]
git clone https://github.com/glimpse/stickerapp
cd stickerapp
git fetch
git checkout chrisdias/connect2017
npm install && code-insiders .

`tasks.json`:
``` json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "docker-compose",
            "command": "docker-compose",
            "args": [
                "-f",
                "docker-compose.debug.yml",
                "up"
            ],
            "identifier": "docker-compose"
        }
    ]
}
```

`launch.json` configuration:
``` json
        {
            "type": "node",
            "request": "attach",
            "name": "Docker",
            "address": "localhost",
            "port": 9229,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/usr/src/app",
            "preLaunchTask": "docker-compose"
        }
```

press `F5`

result: docker-compose is run, but the debugger never attaches

add the `detached` flag to docker-compose in `tasks.json`:

            "args": [
                "-f",
                "docker-compose.debug.yml",
                "up",
                "-d"
            ],

`F5`

Result: "Cannot connect to runtime process...."

If you run `docker-compose -f docker-compose.debug.yml -d` from the terminal and then attach the debugger (without the `preLauncTask`) then I can attach the debugger.

**Comment by isidorn** [comment]
Following your exact steps I get the picture attached. Take note that I do not have any of the docker stuff installed on my machine. 
Do you get the same if you set `protocol: legacy` or `protocol: inspector` to your launch.json

As for debugger not attaching that is probably coming from node2 thus assigning also to @roblourens 
As for the first case that the debugger never attaches that would be an issue on the vscode side does it look something like this https://github.com/Microsoft/vscode/issues/35340

![screen shot 2017-10-13 at 11 30 33](https://user-images.githubusercontent.com/1926584/31539790-04cfbbea-b00a-11e7-8b5f-08495420372d.png)

**Comment by roblourens** [comment]
I don't see that file, is it `docker-compose.dev.yml`?

In that file all the `--inspect` args have different ports than 9229 specified, so do you need to set a different port in the launch config?

**Comment by chrisdias** [comment]
I cleaned up the `chrisdias/connect2017` branch.  There is a `tasks.json` and a simplified `launch.json` in there now and you do need docker installed on the machine.

When I press `F5` I get this:

![image](https://user-images.githubusercontent.com/1487073/31558222-e4cdbc60-b000-11e7-8867-1161da796d25.png)

Now, if you press `F5` again, the debugger will attach because (I think) the container is running already.  So, it's the first time.

A second problem I'm seeing here, but related.  If I have a mistake in my `tasks.json` such that the command does not run, I cannot fix it and then run `F5` again.  I see a blue progress bar in the debug viewlet but when I try to terminate a running task, it tells me there isn't one.

**Comment by roblourens** [comment]
I see the same thing. Can you try with a newer version of Node? It works if I add `"protocol": "inspector"` which implies that it's an issue with protocol detection. The same thing happened with an old Electron version. This is weird because I've never seen it with Node proper and can't repro with 6.11.4 locally.

What I see here, and saw with old Electron, is that after we try to detect the protocol, it won't let anything attach anymore. I can't even attach with chrome devtools after it gets into the broken state.

**Comment by chrisdias** [comment]
ok, i see it work now with `"protocol": "inspector"`.  I've got node 8.5 on my mac so I can't seem to go much higher :).  Also, I don't see the problem where I can't attach anymore.

**Comment by roblourens** [comment]
I'll leave it open since it should work without specifying the protocol. I don't know why it's working differently between running node locally and in Docker.

**Comment by chrisdias** [comment]
if i update the docker image to node 8, i cannot debug anymore.

All i did was change the `Dockerfile` to have this `FROM` statement:

FROM node:8-alpine

Press `F5` and get this message:

![image](https://user-images.githubusercontent.com/1487073/32394583-d5966198-c09a-11e7-8002-16d715c70481.png)

**Comment by chrisdias** [comment]
need to use this in the docker-compose file...

``` yml
    command: node --inspect=0.0.0.0:9229 server/index.js
```
