### ISSUE TITLE
Unable to load schema from 'http://json.schemastore.org/package' behind Proxy

### ISSUE THREAD

**Issue by JoySurfer** [Microsoft/vscode#36197]
- VSCode Version: 1.17.1
- OS Version: Win7 x64

Steps to Reproduce:

1. package.json produces warning in every project:
message: 'Problems loading reference 'http://json.schemastore.org/package': Unable to load schema from 'http://json.schemastore.org/package': <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2017 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>

2. Proxy is set and used fine by other parts of VS Code. But no loading from json.schemastore.org,

**Comment by aeschli** [comment]
The JSON extension relies on the `http.proxy`, `http.proxyStrictSSL` and `http.proxyAuthorization` settings.
If these are all correctly set, but you still see the issue, please describe your environment in #12588.
