### ISSUE TITLE
New files get view state of previously open file

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3619]
- have a JS file, do some collapsing and set cursors
- set a breakpoint in 'textFileEditor.saveTextEditorViewState'
- in the file explorer click on the new file action and create a new file
- the breakpoint is hit when the file view state for the JS file is stored (good!)
- the breakpoint is hit again, when the view state of the new file is set, but again with the state of the JS file (not good), The view state contains cursor positions and folding regions which do not apply to the new file.

**Comment by bpasero** [comment]
Good catch!
