### ISSUE TITLE
VSCode settings through GPO/Registry

### ISSUE THREAD

**Issue by ivansieder** [Microsoft/vscode#3620]
In VisualStudio Code I'm able to overwrite `"telemetry.enableCrashReporter": false`, but this has to be done manually for each new user. Is there any way to set this through a GPO or Registry setting, so I don't have to run to each user and disable it?

**Comment by SofianHn** [comment]
can you describe more your scenario? The easiest way would be dropping a configured user setting file for each new user on provisioning the machine.

**Comment by ivansieder** [comment]
In our company we would like to deploy for about 20 users VS Code, but we don't want to go to each PC and set for example the telemetry, or to hide js and js.map files, when there is a .ts file etc. ofc it's relatively short in terms of time, but it accumulates from time to time, new apps come, so there we got to run again etc. So therefor it would be handy to have the possibility to set propertys through Group policy or registry

**Comment by SofianHn** [comment]
@ivansieder why would not you start by creating a user setting file and then automatically copying that in to the user home directory. This should get you most of what you want. We don't have currently any plans to add the ability to read settings from the registry.

**Comment by ivansieder** [comment]
@SofianHn the reason is, that we want the users change it also on their own and that's impossible if we overwrite the file each time they open it.

**Comment by SofianHn** [comment]
@egamma, maybe [this](https://github.com/Microsoft/vscode/issues/3620#issuecomment-197183559) is a scenario that we want consider in the future.

**Comment by egamma** [comment]
//+ @chrisdias
