### ISSUE TITLE
add new file bug in directory tree

### ISSUE THREAD

**Issue by hsir** [Microsoft/vscode#36209]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 17.0.0

There's a bug in directory tree while adding a new file.

Steps to Reproduce:

1. open a project in VSCode.
2. collapse the directory tree panel.
3. click "new file" icon button.
4. expand the directory tree panel.
5. click any file.
6. there will be a weird input box on a random file.

Possible reason:  the input box dose not trigger any blur events, so it never get removed.

Images:

![1](https://user-images.githubusercontent.com/5260937/31537483-f8cd2720-afc7-11e7-9203-949be59ce939.png)

![2](https://user-images.githubusercontent.com/5260937/31537493-fd13a3fe-afc7-11e7-96f5-172374ba0ed2.png)

![3](https://user-images.githubusercontent.com/5260937/31537497-fffb652a-afc7-11e7-8329-539068bb566b.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Fixed in latest. Dup of https://github.com/Microsoft/vscode/issues/35923
