### ISSUE TITLE
Underscores are invisible in integrated shell under Fedora 26

### ISSUE THREAD

**Issue by zhangzujian** [Microsoft/vscode#36200]
- VSCode Version: 1.17.1
- OS Version: Fedora 26

Steps to Reproduce:

1. Set  "terminal.integrated.fontSize": 14 (14 seems to be the default value)
2. 
![14](https://user-images.githubusercontent.com/13048299/31535140-8799406e-afbf-11e7-90f5-c3ab546f3376.png)

3. Set  "terminal.integrated.fontSize" = 16 and the underlines are visible again.
4. 
![16](https://user-images.githubusercontent.com/13048299/31535179-b110f388-afbf-11e7-8709-4603d7ac98fa.png)

Reproduces without extensions: Yes

**Comment by zhangzujian** [comment]
I tried 12, 13, 14, 15, 16, and it happened only when font size = 14.

**Comment by xadhoom** [comment]
Same on Fedora 25 and yes, happens only with font size 14

**Comment by sebd71** [comment]
Same on Ubuntu 16.04.3 LTS and only with font size 14

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
