### ISSUE TITLE
Chinese display in Terminal

### ISSUE THREAD

**Issue by gosongs** [Microsoft/vscode#36202]
- VSCode Version: 1.17.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/27057518/31535574-3674712a-afc1-11e7-8ef6-1cacf060bdec.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35660, upgrading should fix this if you haven't yet 😄
