### ISSUE TITLE
crash / become unresponsive if terminal.integrated.fontSize is set to 1

### ISSUE THREAD

**Issue by Flatta** [Microsoft/vscode#36215]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
polymer-ide|pol|0.6.0
java|red|0.11.0
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

1. open settings.json and set terminal.integrated.fontSize to 1
2. open integrated terminal (if not opened)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Already fixed, coming in v1.18
