### ISSUE TITLE
SCM: staging multiple files is not very fast

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36213]
It looks like we stage one by one and not all in one go?

![flicker_chrome58](https://user-images.githubusercontent.com/900690/31539864-434e36da-b00a-11e7-99dc-f9634c1b1186.gif)

**Comment by joaomoreno** [comment]
@bpasero I couldn't really repro this on my machine, but I did find a bug which could cause something like that. Pushed a fix, let me know if it fixes it for you.

**Comment by bpasero** [comment]
Yeah seems better.
