### ISSUE TITLE
Can not insert code block after <script>

### ISSUE THREAD

**Issue by songxing10000** [Microsoft/vscode#36211]
- VSCode Version:1.17.1
- OS Version:10.12.6
This can be inserted into the code block
![image](https://user-images.githubusercontent.com/10040131/31539021-f0efebfa-afcc-11e7-9dc5-ddf53df8b25f.png)
![image](https://user-images.githubusercontent.com/10040131/31539132-4af8e872-afcd-11e7-956f-3df140c9f029.png)

This will not work
![image](https://user-images.githubusercontent.com/10040131/31539071-0e1bc26c-afcd-11e7-9814-2881ec71defe.png)

I understand the insertion of the code block, can insert code in any location, there is a solution

**Comment by aeschli** [comment]
Inside the code block only *JavaScipt* templates will show up.
-> `Use Preferences > User Snippets > JavaScript`

**Comment by songxing10000** [comment]
it works, when you use vscode write weex ,you should also eidt the files `vue.json`、`vue-html.json`、`css.json`、`javascript.json `、`html.json`
