### ISSUE TITLE
Gulp watch fails to trigger recompilation while TypeScript compiles

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#36214]
This started happening since the adoption of NSFW. I never really paid much attention to it, but it bothers me every week. I'm pretty sure this worked well before NSFW.

Imagine the initial compilation takes 1 minute. If during that minute there are file events, there won't be any compilation of those files after the minute. It seems that file events during busy times are ignored.

**Comment by bpasero** [comment]
Back to our old watcher. NSFW has [known bugs](https://github.com/Axosoft/nsfw/issues).
