### ISSUE TITLE
VSCode won't let another window display when maximised

### ISSUE THREAD

**Issue by ewantowie** [Microsoft/vscode#36218]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 3.10.0-514.6.1.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
vscode-eclipse-keybindings|alp|0.9.6
Doxygen|bbe|1.0.0
cpptools|ms-|0.13.1
funclist|qrt|7.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open VSCode and maximise.
2. Wait a few seconds (seems not to occur immediately)
3. Try to open, or bring another window to the front.

Reproduces without extensions: Yes

When VSCode is open and maximised it will not allow any other window to display in front. If the window is not maximised the GUI behaves as expected. Oddly, for the first couple of seconds after being maximised, it will allow other windows to display then it will revert to the incorrect behaviour.

Feel free to ask any further questions :)

**Comment by ewantowie** [comment]
Discovered that this issue actually occurs both when the window is maximised or not, but only if an alternative window is selected from the taskbar. When the window isn't maximised, can click another window and it will correctly bring it to the front. Even more odd!

**Comment by cannonfodda** [comment]
Having the same issue with different version. Running remotely via ssh -X on Centos 7.1 dev box. 

Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:57:21.071Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by bpasero** [comment]
@ewantowie @cannonfodda can you try to reproduce with our new build for Linux: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/code-exploration-1.22.0-1522303929_amd64.tar.gz

**Comment by cannonfodda** [comment]
Hi @bpasero, thanks for following up.

Just gave it a try and I get a runtime link error so can't check.

code-exploration: undefined symbol: gtk_widget_get_scale_factor

This is on CentOS Linux release 7.1.1503 (Core) with GTK-3.8.8. 
From a quick search it looks like this was introduced in >GTK-3.10. Unfortunately I can't install an update.

**Comment by bpasero** [comment]
@cannonfodda wow that's bad, thanks for letting us know

**Comment by Tyriar** [comment]
@cannonfodda I was able to run Electron 2 on CentOS 7.1 on a clean install after running `yum update`. Part of the output:

```
  Installing : gtk3-3.22.10-5.el7_4.x86_64                         751/2008
```

Please follow up on https://github.com/Microsoft/vscode/issues/47158 if you want to continue the discussion.
