### ISSUE TITLE
hope the js comment style more Intelligent

### ISSUE THREAD

**Issue by warmilk** [Microsoft/vscode#36210]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
vscode-npm|fkn|3.3.0
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
vue|jcb|0.1.5
autofilename|Jer|0.1.3
node-module-intellisense|lei|1.4.0
vue|liu|0.1.5
HTMLHint|mka|0.3.3
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
vetur|oct|0.9.7
vuehelper|oys|0.1.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.4
html-css-class-completion|Zig|1.10.2

---

Reproduces without extensions: No

Steps to Reproduce:

all the .js file comment with below format , some key works are highlight  not expected
```js
/**
 *
 *
 *
 */
```
look like this
![myIssue](https://user-images.githubusercontent.com/14016918/31537719-bc3dd930-b035-11e7-8213-ac3c3625bb50.jpg)

**Comment by mjbvz** [comment]
This is by-design and up to the theme. All of our built-in themes colorized jsdoc comments. Individual themes can change this behavior or you can try manually overriding the colors by setting `editor.tokenColorCustomizations`:

```js
  "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "storage.type.class.jsdoc",
                "settings": {
                    "foreground": "#f0f"
                }
            }
        ]
    }
```

See [this comment](https://github.com/Microsoft/vscode/pull/29393#issuecomment-323190406) for more info on `editor.tokenColorCustomizations`
