### ISSUE TITLE
Do not autoscroll Output window if cursor is not at the end

### ISSUE THREAD

**Issue by astepanov83** [Microsoft/vscode#36217]
This feature is present in regular VS and is very useful. When you notice some message in the output and click on it, output doesn't scroll automatically. Looks like there is no config option for this.

Steps to Reproduce:

1. Build some big project.
2. During the build, click on some text in the Output window. If the build process is not over when new text appears in the output, the window is autoscrolled to the bottom.

Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by isidorn** [comment]
There is a scroll lock feature in the output. Please try using it.

![screen shot 2017-10-13 at 15 43 10](https://user-images.githubusercontent.com/1926584/31549073-4baffade-b02d-11e7-9759-71f7377ef096.png)

**Comment by astepanov83** [comment]
Didn't notice this feature, thanks. Unfortunately, still doesn't work as I would like. It would be awesome if this is added in future releases.

**Comment by isidorn** [comment]
If you lock the screen and it still auto scrolls then this is a clear bug and I would need exact reproducable steps how you got into this state.
@dbaeumer are you sometimes telling the output to reveal the last line explicitly as that might be the only reason for the scroll lock to not function

**Comment by astepanov83** [comment]
Sorry, what I meant is not Always On/Off autoscrolling as it's implemented right now (no bug is here). I meant a smart autoscroll feature: by default it always autoscrolls, but when you click on some text in the output window, it stops scrolling. When you press Ctrl+End, it resumes autoscrolling. This is how it behaves in VS. Of course this behavior can be emulated by pressing "Lock" icon when necessary to stop autoscrolling, but the icon is small and I got used to clicking right inside the output window, like in VS.
