### ISSUE TITLE
toggle comment gives an ERROR - Unexpected exeption while executing command

### ISSUE THREAD

**Issue by sspnet** [Microsoft/vscode#36226]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
coldfusion|ili|0.0.11
Angular2|joh|2.7.0
vscode-github|Kni|0.22.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
Please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

- what language did you edit when this happens?
- can you provide steps for how to reproduce it?
- can you reproduce this when all the extensions are disabled.

**Comment by sspnet** [comment]
This issue happend on a index.cfm page.

I Discovvered just now that when I use the Keyboard shortcut CTRL+SHIFT+/
it works but if I use the CTR+/ I get the error.

Also when I use the menu option Edit - Toggle Line Comment I get the same
error

[image: Inline afbeelding 1]

Hope this helps!


Met vriendelijke groet,
Simple Soft Products

Jeroen Goorts
T 036 537 71 63



2017-10-13 15:02 GMT+02:00 Erich Gamma <notifications@github.com>:

**Comment by egamma** [comment]
>[image: Inline afbeelding 1]

The image got lost, can you please re-attach.

When this happens can you please open the developer tools Help>Toggle Developer Tools and see what exception is shown in the console tab?

Can you reproduce this when you have the extensions disabled (start `code --disable-extensions`.

**Comment by sspnet** [comment]
Hi Erich,

This is shown in the developers tools console after I disabled all the
extentions and image attached:

t.charCodeAt is not a function: TypeError: t.charCodeAt is not a function
    at Function.e._haystackHasNeedleAtOffset (file:///C:/Program
Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:567048)
    at Function.e._analyzeLines (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:570407)
    at Function.e._gatherPreflightData (file:///C:/Program Files/Microsoft
VS Code/resources/app/out/vs/workbench/workbench.main.js:28:570881)
    at e.getEditOperations (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:573506)
    at Function.e._getEditOperationsFromCommand (file:///C:/Program
Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:884467)
    at Function.e._getEditOperations (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:883523)
    at Function.e._innerExecuteCommands (file:///C:/Program Files/Microsoft
VS Code/resources/app/out/vs/workbench/workbench.main.js:28:881932)
    at Function.e.executeCommands (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:881674)
    at t._executeEditOperation (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:877826)
    at t._externalExecuteCommands (file:///C:/Program Files/Microsoft VS
Code/resources/app/out/vs/workbench/workbench.main.js:28:881360)
e.onUnexpectedError @ shell.ts:454
(anonymous) @ shell.ts:414
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e._getEditOperationsFromCommand @ cursor.ts:797
e._getEditOperations @ cursor.ts:712
e._innerExecuteCommands @ cursor.ts:599
e.executeCommands @ cursor.ts:583
t._executeEditOperation @ cursor.ts:343
t._externalExecuteCommands @ cursor.ts:548
t.trigger @ cursor.ts:489
t.executeCommands @ commonCodeEditor.ts:786
t.run @ comment.ts:39
t.runEditorCommand @ editorCommonExtensions.ts:193
(anonymous) @ editorCommonExtensions.ts:144
t.invokeFunction @ instantiationService.ts:58
t.invokeWithinContext @ commonCodeEditor.ts:185
t.runCommand @ editorCommonExtensions.ts:137
handler @ editorCommonExtensions.ts:67
t.invokeFunction @ instantiationService.ts:58
t._tryExecuteCommand @ commandService.ts:51
(anonymous) @ commandService.ts:39
then @ winjs.base.raw.js:1566
t.executeCommand @ commandService.ts:39
e._dispatch @ abstractKeybindingService.ts:161
(anonymous) @ keybindingService.ts:313
messageService.ts:125 Unexpected exception while executing command.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.onUnexpectedError @ shell.ts:458
(anonymous) @ shell.ts:414
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e._getEditOperationsFromCommand @ cursor.ts:797
e._getEditOperations @ cursor.ts:712
e._innerExecuteCommands @ cursor.ts:599
e.executeCommands @ cursor.ts:583
t._executeEditOperation @ cursor.ts:343
t._externalExecuteCommands @ cursor.ts:548
t.trigger @ cursor.ts:489
t.executeCommands @ commonCodeEditor.ts:786
t.run @ comment.ts:39
t.runEditorCommand @ editorCommonExtensions.ts:193
(anonymous) @ editorCommonExtensions.ts:144
t.invokeFunction @ instantiationService.ts:58
t.invokeWithinContext @ commonCodeEditor.ts:185
t.runCommand @ editorCommonExtensions.ts:137
handler @ editorCommonExtensions.ts:67
t.invokeFunction @ instantiationService.ts:58
t._tryExecuteCommand @ commandService.ts:51
(anonymous) @ commandService.ts:39
then @ winjs.base.raw.js:1566
t.executeCommand @ commandService.ts:39
e._dispatch @ abstractKeybindingService.ts:161
(anonymous) @ keybindingService.ts:313

Met vriendelijke groet,
Simple Soft Products

Jeroen Goorts
T 036 537 71 63



2017-10-13 18:11 GMT+02:00 Erich Gamma <notifications@github.com>:

**Comment by sspnet** [comment]
When I restarted the VS application the error was gone but it also did not
do anything anymore when useing the CTRL+/ or Edit - Toogle command tool.

After activating the "CFML (ColdFusion) Language Support" extension the
error is back.

Met vriendelijke groet,
Simple Soft Products

Jeroen Goorts
T 036 537 71 63



2017-10-16 12:38 GMT+02:00 Jeroen Goorts <jeroen@sspnet.nl>:

**Comment by alexandrudima** [comment]
The root cause lies with the extension which defines the line comment token to be an array instead of a string in https://github.com/ilich/vscode-coldfusion/blob/master/cfscript.configuration.json#L3

A PR already exists against the extension at https://github.com/ilich/vscode-coldfusion/pull/30/files

I will look into a fix on our side that we should not accept a string array instead of a string for a line comment token.

**Comment by alexandrudima** [comment]
From now on a warning will be presented in the developer tools and the line comment rule will be ignored: `` language configuration: expected `comments.lineComment` to be a string. ``
