### ISSUE TITLE
Command Names

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3622]
This isn't a big deal - I'm curious why some commands are named `workbench.action.files.*` and others are `workbench.files.action.*`

![image](https://cloud.githubusercontent.com/assets/2449568/13458499/d2230188-e06d-11e5-9350-8bd7f3a223e7.png)

**Comment by isidorn** [comment]
This is because we are not always consistent and is an error on our part.
The reason why we can not easily change these ids is because it would require a transition of user keyboard shortcuts. Feel free to invest in this if you are passionate about it :)

**Comment by waderyan** [comment]
Haha ok sounds good.
