### ISSUE TITLE
would be nice if we would have red line to see elements endings in HTML

### ISSUE THREAD

**Issue by peon501** [Microsoft/vscode#36224]
- VSCode Version: newest
- OS Version: 8.1

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1125765/31544255-8f3b4624-b022-11e7-90b3-e4be25b764f1.png)

would be nice if on div click you would have line in some kind of color
![image](https://user-images.githubusercontent.com/1125765/31544309-d5e3f77e-b022-11e7-9285-a44b1cfb10ed.png)

**Comment by peon501** [comment]
Found, plugin. 
At last something, doing some kind of job.
[](https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
