### ISSUE TITLE
.vscode/c_cpp_properties.json is overwritten on editor "reload"

### ISSUE THREAD

**Issue by kghose** [Microsoft/vscode#36220]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
uncrustify|Lau|2.7.0
haskero|Van|1.3.1
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.4.0
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.13.1
cmake-tools|vec|0.10.2
clang-format|xav|1.6.0

---

Steps to Reproduce:

1. Fill out "includePath" entry in .vscode/c_cpp_properties.json. Save the file
2. After enabling/disabling an extension "reload" the editor
3. The file has been reset

**Comment by egamma** [comment]
Please report the issue against the cpp-extensions repository https://github.com/Microsoft/vscode-cpptools.

**Comment by lzjqsdd** [comment]
same too
