### ISSUE TITLE
Installing c++ plugin crashes Firefox

### ISSUE THREAD

**Issue by galgalesh** [Microsoft/vscode#36225]
- VSCode Version: 
```
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
```
- OS Version: Ubuntu 17.10

This is the weirdest bug ever.

Steps to Reproduce:

1. Install VS code snap on Ubuntu 17.10
2. Open VS code, go to the extensions page, search for c++ and install the Microsoft C/C++ extension.

What happens:

FF crashes...

Reproduces without extensions: No

Bug in FF in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1723406

It might be useful because it contains a bunch of stack traces etc. It is however currently hidden because it contains privacy-sensitive information.

**Comment by galgalesh** [comment]
@egamma Any pointers as to what info I need to provide?

**Comment by egamma** [comment]
Sorry, forget to save my comment.

Does this only happen when installing the C++ extension. Have you tried installing other extensions like the C# extension.
