### ISSUE TITLE
Very high memory usage during search (Ctrl + p)

### ISSUE THREAD

**Issue by mistralol** [Microsoft/vscode#36227]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
rpm-spec|Lau|0.2.1
code-gnu-global|aus|0.2.2
Doxygen|bbe|1.0.0
githistory|don|0.2.3
gitlens|eam|5.6.4
vscode-power-mode|hoo|2.0.0
c-cpp-flylint|jbe|0.2.7
autoconf|mae|0.0.1
cppcheck|mat|0.2.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
code-spell-checker|str|1.4.10
todo-show|suy|0.2.1
gitblame|wad|2.2.0
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Press Ctrl + p
2. Enter some string to search for a file.
3. VSCode runs machine out of memory. Loinux kernel oom kills process eventually.

Approx number of files from project root is 176754. This used to work without a problem on the same code based prior to an of the october releases.

Output from dmesg.

[1220388.516211] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[snip other unreleated tasks]
[1220388.516442] [10760]  1000 10760   414003     6103     275      30      579             0 code
[1220388.516443] [10764]  1000 10764    85484       33     128       4      731             0 code
[1220388.516444] [10795]  1000 10795   114207     9624     195       5       55             0 code
[1220388.516445] [10808]  1000 10808   314038    31021     377     145      993           300 code
[1220388.516447] [10812]  1000 10812   288228     6919     228      50      606           300 code
[1220388.516448] [10887]  1000 10887   263928    15839     254      98       94           300 code
[1220388.516449] [10888]  1000 10888   458464   212397    1584    1346      372           300 code
**[1220388.516450] [10889]  1000 10889 57083008  3883879  112075    1438    22829           300 code**
[1220388.516451] [10967]  1000 10967   232410     4600     162      30        0           300 code
[1220388.516452] [10968]  1000 10968   267636    15026     260     113       16           300 code
[1220388.516453] [10975]  1000 10975   282179    29051     100       4       39           300 Microsoft.VSCod
[1220388.516454] [11065]  1000 11065   239902    58277     148       3      194           300 Microsoft.VSCod
[1220388.516455] [13480]  1000 13480   141523     1330     130       3       33             0 unity-panel-ser
[1220388.516457] Out of memory: Kill process 10889 (code) score 715 or sacrifice child
**[1220388.516471] Killed process 10889 (code) total-vm:228332032kB, anon-rss:15535516kB, file-rss:0kB, shmem-rss:0kB**
[1220389.222695] oom_reaper: reaped process 10889 (code), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

This is a capture of /proc/<pidof code>/status while the bug is occuring
Name:	code
Umask:	0022
State:	S (sleeping)
Tgid:	5223
Ngid:	0
Pid:	5223
PPid:	5150
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	64
Groups:	4 24 27 30 46 121 131 136 1000 
NStgid:	5223
NSpid:	5223
NSpgid:	2646
NSsid:	2646
VmPeak:	163432444 kB
VmSize:	163432444 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	11212700 kB
VmRSS:	11212700 kB
RssAnon:	11176556 kB
RssFile:	   36144 kB
RssShmem:	       0 kB
VmData:	162580552 kB
VmStk:	     132 kB
VmExe:	   78692 kB
VmLib:	   64600 kB
VmPTE:	  320728 kB
VmPMD:	    4332 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	11
SigQ:	3/127949
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001002
SigCgt:	0000000180010200
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	1411966
nonvoluntary_ctxt_switches:	246281

**Comment by chrmarti** [comment]
@mistralol Could you check if the problem also occurs in the insiders build (https://code.visualstudio.com/insiders/)? What `files.exclude` and `search.exclude` settings are you using?

**Comment by mistralol** [comment]
I can confirm it happens on todays insiders build version I tried was in code-insiders_1.18.0-1507883485_amd64.deb

The other information you requested. From the recent VSCode install.

  // Configure glob patterns for excluding files and folders. For example, the files explorer decides which files and folders to show or hide based on this setting.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },

  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },


I also tried the following. for the excludes patterns but the same issue occurs.

    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "*.so" : true,
        ".la" : true,
        "*.o" : true,
        "*.a" : true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "*.so" : true,
        ".la" : true,
        "*.o" : true,
        "*.a" : true
    }

**Comment by chrmarti** [comment]
What is the output of the following when run from the workspace folder:
```
time (/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg --files --hidden --follow --no-ignore -- . | wc -l)
```

**Comment by mistralol** [comment]
So I ran this command for around 1.5 hours. It was never able to complete. Howerver it did't ever use excessive amount of memory. It was around an rss size of 815MB.

**Comment by chrmarti** [comment]
@mistralol Could you check what the output of `rg` is:
```
/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg --files --hidden --follow --no-ignore -- .
```
That will likely flood your terminal with pathnames it traverses. It would be interesting to know if it keeps making progress, goes into some sort of cycle (like through symlinks or mount points) or maybe just becomes very slow.

Also please run the original command without following symlinks to check if that changes anything:
```
time (/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg --files --hidden --no-ignore -- . | wc -l)
```

**Comment by mistralol** [comment]
Looks like its not making any progress. To try to compare the "time" taken for this search I used "find -type f  | xargs grep ." Which comes out at around 10 minute runtime.

From what I can tell there is some code in there that doesn't seem to be dealing well with certain file permissions. Note: part of the build system on this tree is performed as root since we are producing a bootable iso for linux.

So I don't think it is making progress. I also get constant spamming of 

Permission denied (os error 13)
Permission denied (os error 13)
Permission denied (os error 13)
Permission denied (os error 13)
Permission denied (os error 13)
Permission denied (os error 13)

From what I can tell with strace the process is just looping on calls to getdents64 indefinatly. This are also not permitted eg

strace output is

[pid  9756] <... getdents64 resumed> 0x7fea5a213020, 2048) = -1 EACCES (Permission denied)
[pid  9763] <... getdents64 resumed> 0x7fea57e13020, 2048) = -1 EACCES (Permission denied)
[pid  9758] getdents64(5,  <unfinished ...>
[pid  9757] <... getdents64 resumed> 0x7fea59c12020, 2048) = -1 EACCES (Permission denied)
[pid  9759] getdents64(10,  <unfinished ...>
[pid  9761] <... getdents64 resumed> 0x7fea58213020, 2048) = -1 EACCES (Permission denied)
[pid  9762] getdents64(8,  <unfinished ...>
[pid  9758] <... getdents64 resumed> 0x7fea59613020, 2048) = -1 EACCES (Permission denied)
[pid  9760] getdents64(6,  <unfinished ...>
[pid  9759] <... getdents64 resumed> 0x7fea58c13020, 2048) = -1 EACCES (Permission denied)
[pid  9762] <... getdents64 resumed> 0x7fea58012020, 2048) = -1 EACCES (Permission denied)

**Comment by chrmarti** [comment]
Could you add the folders with restricted permissions to the `"files.exclude"` setting?

**Comment by mistralol** [comment]
It does seem to stop it from exceeding memory usage. Which will serve as a workaround for now

**Comment by chrmarti** [comment]
I'm trying to reproduce what you are seeing without luck. Do you have more details on what is going on? Does the insiders build show the same behavior? (https://code.visualstudio.com/insiders/)

**Comment by mistralol** [comment]
I am trying with code-insiders code-insiders_1.18.0-1509431158_amd64.deb (todays build)

While running: "time /usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg --files --hidden --no-ignore -- ."

Before the file permissions errors are present in the directory strucutre.

real	0m0.732s
user	0m0.116s
sys	0m0.260s

After the file permission errors are present.

It simple never completes and I just get "Permission denied (os error 13)" printed over and over.

What I do know about this case is that this is using a network mounted filesystem and is behaving a little differently to a normal filesystem. Where the opendir gets success (common optimization as a saves a round trip). But the readdir fails which is why you are probably having issues trying to reproduce it. When I try this another way with a normal filesystem it doesn't happen. The opendir fails it produces the same error message but will not enter the infinate loop.

I suspect the loop is in fileSearch.ts +503 But I am not really javascript person / type script (I c/c++ instead). So I have no idea how to put a debugger on it to confirm exactly what is going on. One of the things that also indicates this is that as soon as file excludes are turned on it the problem doesn't happen.

private doWalk(folderQuery: IFolderSearch, relativeParentPath: string, files: string[], onResult: (result: IRawFileMatch) => void, done: (error: Error) => void):

**Comment by chrmarti** [comment]
Thanks for the analysis. What network filesystem are you using?

**Comment by mistralol** [comment]
Its sshfs :)
