### ISSUE TITLE
Error font in Vietnamese

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#36229]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Open a terminal.
2. Input "Chào buổi sáng Chủ Nhật".
3. See characters: "ổ", "ủ", "ậ".

![image](https://user-images.githubusercontent.com/27698189/31547984-8368dbbe-b053-11e7-9ba2-4c799ec88e9f.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@torn4dom4n isn't it just the "ổ" that's wrong? The "ủ" and "ậ" look fine to me?

**Comment by torn4dom4n** [comment]
@Tyriar You can zoom in the picture to see. It isn't good.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
