### ISSUE TITLE
rpm build 1.17.1 not visible to yum/dnf

### ISSUE THREAD

**Issue by tomkv** [Microsoft/vscode#36228]
The new release in yum repository is not visible to yum/dnf. The repodata does not contain info about this release.

- VSCode Version: 1.17.1
- OS Version: Fedora 26

Steps to Reproduce:

1. `dnf update --refresh`
2. the last version available is 1.17.0

Reproduces without extensions: N/A

**Comment by Tyriar** [comment]
1.17.1/2 are published to the yum repo
