### ISSUE TITLE
Match whole word does not work for not latin characters (at least for cyrillic)

### ISSUE THREAD

**Issue by KvanTTT** [Microsoft/vscode#3623]
I created the next document:

```
я
компилятор
обфускация

i
compiler
cli
```

And if I am trying to find all whole words "я", vscode highlights all three first words. But if I am trying to find "i", vs code highlights only fourth word.

**Comment by nixel2007** [comment]
@alexandrudima link to code -
https://github.com/Microsoft/vscode/blob/fb5b68d199918fbe58e57d4faa3909580430fa4e/src/vs/base/common/strings.ts#L184

The problem is in `\b` - it doesn't support non-en symbols

**Comment by ebugusey** [comment]
The problem is that js doesn't have full support for unicode. Even with `/u` in ES6 it just doesn't work. You should use _oniguruma_ for regular expressions, like Atom does.

**Comment by nixel2007** [comment]
@ebugusey atom does not use oniguruma everywhere or it doesn't help in all cases. I've made a unicode support for Atom-autocomplete using the XRegExp library.

**Comment by martinsuchan** [comment]
Just discovered this bug - still happening in VS Code 1.9. It's especially problematic when searching for specific word in localized comments or searching for all usages of variable with short name:    
![match_whole_word](https://cloud.githubusercontent.com/assets/3041397/22648481/3465342c-ec77-11e6-89b9-8048a9eaf07b.png)

**Comment by alexandrudima** [comment]
fyi @roblourens

**Comment by bambr1975** [comment]
![default](https://cloud.githubusercontent.com/assets/9781644/26447753/92e3a594-4152-11e7-92c3-08a613cfc1f1.png)
don't working

**Comment by alexandrudima** [comment]
Search in files uses a different implementation. Hence the ping to @roblourens

**Comment by roblourens** [comment]
Opened a new issue for it, #27280
