### ISSUE TITLE
Collapsing code opens git diff

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#36237]
- VSCode Version: Code - Insiders 1.18.0-insider (d1047a65ed5db2ffc26c01ebc6f4ed91a0b5eb26, 2017-10-13T05:22:12.703Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Collapse Code
2. VSCode shows me the git diff

![gif](https://user-images.githubusercontent.com/19274678/31555404-c52513f0-aff5-11e7-9407-062f3239e821.gif)

**Comment by jdatskuid** [comment]
Temporary work-around: use <kbd>⌘</kbd> + <kbd>⎇</kbd> + <kbd>[</kbd> to fold, <kbd>⌘</kbd> + <kbd>⎇</kbd> + <kbd>]</kbd> to unfold (if you aren't already)

After a quick exploration of the settings file, I could not find a setting that disables this feature.

**Comment by joaomoreno** [comment]
#36237

**Comment by mcarpenterjr** [comment]
When can we expect this fix to roll out?

**Comment by jdatskuid** [comment]
According to https://github.com/Microsoft/vscode/issues/36470#issuecomment-337973333, it's already been released in latest Insiders build.
