### ISSUE TITLE
Allow to detect encoding from contents in the file

### ISSUE THREAD

**Issue by fzzr-** [microsoft/vscode#36230]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

The `files.autoGuessEncoding=true` not looks to `xml`'s processing instructions (header with encoding).

For document with header `<?xml version="1.0" encoding="windows-1251"?>` encoding must be `windows-1251/cp1251` for example.

Because processing instructions and `encoding` attribute is optional we should use standard existing solution to determine encoding as fallback if `encoding` attribute doesn't exists.

Steps to Reproduce:
[test.xsd.zip](https://github.com/Microsoft/vscode/files/1382715/test.xsd.zip)

0. add `"[xml]": { "files.autoGuessEncoding": true },` into the settings json. (maybe same for `xsd`)
1. open attached xml `test.xsd`
2. encoding will `maccirillic` instead `cp1251`

Reproduces without extensions: Yes

- - -

_I think this issue can be reproduced for other markups/ langs such as:_
- xml-family: xml, xsd, html-family, svg, php, mxml,..
- eml (look to `charset=..`)
- yaml maybe
- what have I forgotten

**Comment by LinAGKar** [comment]
Also, [PEP-263](https://www.python.org/dev/peps/pep-0263/) for Python, [coding comment](https://ruby-doc.org/core-2.1.4/Encoding.html#class-Encoding-label-Script+encoding) for Ruby, and [meta [Content-Type] charset](https://www.w3.org/International/questions/qa-html-encoding-declarations) for [X]HTML.

**Comment by IgnakhinSS** [comment]
Is there any information on the timing of this task? More than a year has passed.

**Comment by alrekr** [comment]
Has this feature been dropped? Maybe VS Code should bypass jschardet in case VSC detects an encoding specification in languages supplying their own encoding definition.

**Comment by luigli** [comment]
Hi. I'm interested about auto guess encoding feature.
I've uploaded a simple xml file (please, remove .txt extension) with some spanish text.
The only non-ascii character is an &oacute; in the 3rd line.
It is declared and encoded as utf-8, but VSCode 1.43.2 on Windows 10 guesses it as "tis620" encoding.
Thanks.
[2200.xml.txt](https://github.com/microsoft/vscode/files/4390563/2200.xml.txt)

**Comment by luigli** [comment]
Should you consider adding an option like "[xml]": { "files.relyOnDeclaration": true }, please?
It could be useful for some files that optionally declare their encoding, like html, xml and the like.
