### ISSUE TITLE
vscode insiders: uninstall powershell shows err

### ISSUE THREAD

**Issue by kcwms** [Microsoft/vscode#36239]
- VSCode Version: Code - Insiders 1.18.0-insider (f1ee80be081b0d47f4423b9dc5f41a65c36146da, 2017-10-13T08:55:13.465Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-guid|hea|1.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
mssql|ms-|1.2.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
partial-diff|ryu|0.3.3
shell-launcher|Tyr|0.1.3

---

Steps to Reproduce:

1. uninstall Powershell plugin
2. ERROR 
```Error: EBUSY: resource busy or locked, unlink 'C:\Users\{0}\.vscode-insiders\extensions\ms-vscode.powershell-1.4.3\logs\1507911856-ce396016-e286-4b2b-b4a7-66a2b619b8e41507911850184\EditorServices.log',,,Error: EPERM: operation not permitted, unlink 'C:\Users\{0}\.vscode-insiders\extensions\ms-vscode.powershell-1.4.3\modules\PowerShellEditorServices\bin\Desktop\Microsoft.PowerShell.EditorServices.dll',Error: EPERM: operation not permitted, unlink 'C:\Users\{0}\.vscode-```
3. restart and the extension is gone

**Comment by egamma** [comment]
Please file the issue against the powershell extension https://github.com/PowerShell/vscode-powershell so that they can investigate whether it is an issue with the extension or with VS Code.
