### ISSUE TITLE
Cannot install VS Code extension (Ubuntu 16.04)

### ISSUE THREAD

**Issue by hu2342** [Microsoft/vscode#36241]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 3.13.0-88-generic
- Extensions: none
-Proxy? Yes
-Proxy setting work OK for browsers and "apt"
---

Steps to Reproduce:

1.Open VS Code
2.CTRL+P to open quick access bar
3. type "ext install csharp"
4. Get error "XHR Failed"

**Comment by Tyriar** [comment]
@hu2342 does this only happen with the csharp extension, or all extensions?

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/34385
