### ISSUE TITLE
Broken built-in code formatting

### ISSUE THREAD

**Issue by beworker** [Microsoft/vscode#36248]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.18
gitignore|cod|0.5.0
auto-close-tag|for|0.5.1
vue|liu|0.1.5
java|red|0.11.0

When formatting JS code using built-in formatter, the code gets formatted like this

```javascript
    const {
        companyValues,
        agentValues,
        channelValue
    } = prepareValues({
            data
        })
```

instead of being formatted like this (see two last lines)

```javascript
    const {
        companyValues,
        agentValues,
        channelValue
    } = prepareValues({
        data
    })
```

---

Steps to Reproduce:

1. Create new JS-file and add code snippet above
2. Format the code (alt + shift + F)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/19167 to track this upstream

Closing as upstream
