### ISSUE TITLE
Error should have action to edit the launch.json file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3624]
![image](https://cloud.githubusercontent.com/assets/22350/13458813/e1d1e16a-e06f-11e5-9ba0-e1a5f646157a.png)

It's even hard to figure out that this is debug related and/or that the attributes mentioned occur in `launch.json`.

This will hit **every extension developer** when they update, so marking it as important. IMO it should be fixed for the Feb stable release.

**Comment by weinand** [comment]
@isidorn can we have both, the 'More Information' action and the "Edit launch.json' button?

**Comment by isidorn** [comment]
@joaomoreno removing the important since this is not a part of february release, I just pushed this change yesterday. I will fix it either way but it is not a stable candidate

**Comment by joaomoreno** [comment]
@isidorn Please reconsider. This affects **all extension developers**.

**Comment by joaomoreno** [comment]
@isidorn says *what I mean is that the screenshot does not reflect what will be released on February, that change came after in the `master` branch*
