### ISSUE TITLE
Linux insider update indicator unclear.

### ISSUE THREAD

**Issue by mcarpenterjr** [Microsoft/vscode#36245]
Installed the deb package for the insiders build, built in system update manager alerts every day when a new version is available, that's cool works as expected. Typically one the system update manager runs and finishes, If I have an active instance of VS COde Insiders running, I will close the instance and restart, this clears the internal vscode update notification and loads the updated version of vs code. Didn't work today.

**Comment by mcarpenterjr** [comment]
How does one find out the currently available version of insiders?

**Comment by mcarpenterjr** [comment]
After upgrading to this morning's release the update notification functions as expected.

Open insiders, see an upgrade notification.
Open System Package manager, see indisders has an update.
Run Update from the package manager.
Restart insiders, no update notification.

I am going to close the issue because it seems to be fixed. However, I still would like to know how to find the current release's version.

**Comment by Tyriar** [comment]
Occasionally our update server which alerts of new versions and the apt repo will get out of sync for the Insiders build. If you're running Insiders and apt says it's up to date after an `apt update` I would just ignore the update notification.
