### ISSUE TITLE
Allow to set git badges foreground

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#36246]
Hi, what color key is used for the git badge foreground in the explorer tree?

<img width="317" alt="screen shot 2017-10-13 at 19 44 54" src="https://user-images.githubusercontent.com/10454741/31559016-6afbd3d2-b04f-11e7-9e35-e0c8034a7622.png">

**Comment by jrieken** [comment]
That's not yet possible to configure...

**Comment by equinusocio** [comment]
@jrieken Thank you

**Comment by jrieken** [comment]
<img width="323" alt="screen shot 2017-10-26 at 17 34 51" src="https://user-images.githubusercontent.com/1794099/32062169-fe8713c2-ba73-11e7-9a52-32dbb6e54be3.png">

We have changed the design to use the same color as for the label. Closing this

**Comment by equinusocio** [comment]
Nice!
