### ISSUE TITLE
Gear context menu reopens itself after choosing an action on mac

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#36244]
- VSCode Version: Code - Insiders 1.18.0-insider (f1ee80be081b0d47f4423b9dc5f41a65c36146da, 2017-10-13T08:20:36.732Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Steps to Reproduce:

1. Click on the gear in the side bar
2. Click on any item in the context menu using the mouse

**Bug**
After selecting the item, the context menu opens itself again

![oct-13-2017 10-21-58](https://user-images.githubusercontent.com/12821956/31558136-8ef61c38-b000-11e7-9dff-16844a13eb37.gif)

Does not reproduce when using the keyboard for selecting the context menu item

**Comment by bpasero** [comment]
@mjbvz how did you manage to click "Restart to Update" without the update process actually initiating? Can you reproduce with the other commands from the menu?

**Comment by mjbvz** [comment]
Yes it reproduces with the other commands as well.

The update does get initiated after the first click but the second one seems to pause it. If I cancel out of the second context menu, the update starts right away

**Comment by bpasero** [comment]
@mjbvz what are you doing differently from me? ![panel-red](https://user-images.githubusercontent.com/900690/31646201-bbf0bd62-b300-11e7-86b8-79b27f83e04b.gif)

Does it reproduce in stable too?

**Comment by mjbvz** [comment]
Yes, I also see it in stable. I'm using a mac trackpad with tap to click on the gear. It may have something to do with the duration of the tap / click since I can't always repo this when using a normal click

Let me know if there's any additional info that would be helpful

**Comment by joaomoreno** [comment]
Oh wow... I was about to file this issue.

I got hit with this: https://github.com/Microsoft/vscode/issues/36255

**Comment by bpasero** [comment]
@joaomoreno yeah most likely happens on any os, there was a mouse-down and a click handler both triggering the menu.
