### ISSUE TITLE
using vscode as my git editor no longer works

### ISSUE THREAD

**Issue by ddivecs** [Microsoft/vscode#36247]
- VSCode Version: 1.17.1
- OS Version: Windows 7 64 bit 

Steps to Reproduce:

1. Set Vscode as your editor in .gitconfig
`editor=\"C:\\Program Files\\Microsoft VS Code\\Code.exe\" --wait`
2. `git commit` a file from inside a terminal in vscode

A new tab successfully opens, and i can edit and save it. Closing this tab does not actually make the commit, and my terminal hangs.

Previously a new vscode window would spawn (which also wasn't great, because boot time for a new vscode window is slow with the number of addons i have).
Closing this window would successfully save my commit message and `git commit` would continue.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@ddivecs you need to use our command which is within `C:\Program Files\Microsoft VS Code\bin` and not the EXE directly. Best to install Code via installer and pick the open to add Code to the path.

**Comment by ddivecs** [comment]
@bpasero I tried this. I now have Code installed correctly and have it added to my path. git now immediately presents a message saying `Aborting commit due to empty commit message.`

**Comment by bpasero** [comment]
@ddivecs can you run "code --wait <some file>" from the command line and verify that the command prompt waits until you close the tab that opens?

**Comment by ddivecs** [comment]
@bpasero my path was wrong, I must have manually configured it at some point. Everything works now.
