### ISSUE TITLE
`Rename Symbol` on variable sourcing a return destructured object leads to compiler error

### ISSUE THREAD

**Issue by greyepoxy** [Microsoft/vscode#36252]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Typescript: 2.5.3
---
**Steps to Reproduce:**
1. I have the following typescript code
```ts
interface Result {
    a: number;
}

export function doThing(): Result {
    const a = 5 + 10;

    return {
        a
    };
}
```
2. Highlight `a` at its declaration
3. Hit F2 and rename the symbol to `b`

**Expected:**
1. A symbol rename to not lead to a compiler error
1. Something like the following:
```ts
export function doThing(): Result {
    const b = 5 + 10;

    return {
        a: b
    };
}
```

**Actual:**
```ts
export function doThing(): Result {
    const b = 5 + 10;

    return {
        b // <-- this has the error below
    };
}
```
severity: 'Error'
message: 'Type '{ b: number; }' is not assignable to type 'Result'.
  Object literal may only specify known properties, and 'b' does not exist in type 'Result'.'

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19173
