### ISSUE TITLE
How 'score' was computed when registering a language feature like FormatProvider?

### ISSUE THREAD

**Issue by luyiming** [Microsoft/vscode#36254]
Currently in [VSCode api reference page](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages):
> Registration is done using a document selector which is either a language id, like javascript or a more complex filter like { language: 'typescript', scheme: 'file' }. Matching a document against such a selector will result in a **score** that is used to determine if and how a provider shall be used. When **scores** are equal the provider that came last wins.

I'm wondering how this `score` is actually being computed?

I register a formatter using `registerDocumentFormattingEditProvider`, and there is currently another extension providing the same formatter for the language. I put some `console.log()` in my formatter code and it shows the code is running, but actually the document is formatted by the other extension. This is confusing. I have tried to add a command which registers the formatter again to make sure it comes last but it didn't work. Is it because my extension has a lower `score` than the other?

**Comment by egamma** [comment]
@luyiming please see the following blog post. It should cover the issue you raise https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_multiple-formatters

**Comment by jrieken** [comment]
How the score is computed is documented here: https://github.com/Microsoft/vscode/blob/95d24c19d909b306be4e22212197b66c79ea1241/src/vs/vscode.d.ts#L5311
