### ISSUE TITLE
"Path must be string. Received null" error when attempting to start debugger

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#3625]
Using VSCode 0.10.10-insider on Windows 7

I can no longer debug my JavaScript in this build. It just throws this error
 
![capture](https://cloud.githubusercontent.com/assets/563860/13458737/2bef9a1e-e0c3-11e5-82fa-0e1dae4e271c.PNG)

Falling back to the 0.10.8 release on the "stable" channel, I can debug this project again. I could also debug this project with the previous insiders build.

To reproduce:

1. Clone my repo https://github.com/jumpinjackie/jsdoc-typescript-plugin
2. `npm install`
3. `npm run-script tsc`
4. Open this clone dir in VSCode 0.10.10-insider
5. Start debugging with the provided launch.json

As an aside, it would be nice for such errors to present an option to show the stack trace as well, because I have no clue where to even look to determine the cause of this problem.

**Comment by weinand** [comment]
@jumpinjackie sorry for this regression. The workaround is to set `outDir` to the path where the source maps exist, e.g. for the project from above `${workspaceRoot}/plugins`.

You can find the stacktrace for the error in the dev tools console of VS Code.

**Comment by saravmajestic** [comment]
I am getting the same error when trying to install "Cordova tools".
Steps:
- Installed VSCode Version 0.10.9 (0.10.9)
- installed cordova extension from extensions gallery
- selected Cordova from debug configuration
- clicked 'Run Android on emulator'
Got the error as above.

I tried to set `sourceMaps` as false and `"outDir": "${workspaceRoot}"` , but still getting same error.

I dont know which sourcemaps I have to specify as mentioned in the workaround.

**Comment by weinand** [comment]
@saravmajestic this problem cannot occur in VSCode 0.10.9 because the problematic code got introduced in version 0.10.10. Please include a screenshot of the exact error you are seeing.

**Comment by saravmajestic** [comment]
<img width="1440" alt="screen shot 2016-03-06 at 5 46 28 pm" src="https://cloud.githubusercontent.com/assets/1147025/13554046/88eb3df6-e3c3-11e5-8a56-55f1487ba433.png">

@weinand attached the screenshot. I will report the same in Cordova tools as well. Thanks a lot!

**Comment by weinand** [comment]
@saravmajestic thanks! Yes, the error message shows that this is not a VS Code problem but a problem in the Cordova extension.

**Comment by egamma** [comment]
@saravmajestic this is the repository of the Cordova extension https://github.com/Microsoft/vscode-cordova
