### ISSUE TITLE
Arrow up/down for navigating source code is prevented by hint dialog

### ISSUE THREAD

**Issue by dbkaplun** [Microsoft/vscode#36256]
1. Start a new JavaScript file
2. Enter `require(`
3. Observe that arrow up/down cycles through hints rather than navigating between lines in source code

See also #14840

**Comment by egamma** [comment]
This is the expected behaviour, when working with paramter hints. If you do not like to work with parameter hints you can disable them using the `"editor.parameterHints": false` setting.

**Comment by dbkaplun** [comment]
If this is the expected behavior then it's a bug. If there isn't a way to navigate above/below a line when the hint dialog is open then there should be one.

**Comment by egamma** [comment]
I disagree that this is a bug. When the parameter hints are visible, then the up/down arrow cycling through the hints is the designed behavior. You can dismiss the parameter hints message box using the ESC key and there is a setting to control whether the parameter hints should show.

**Comment by dbkaplun** [comment]
The problem is that the parameter hints are pretty useful, so I don't want to disable them. Is it possible to disable the keyboard for the hint dialog only?

**Comment by hex13** [comment]
for me dialog alone is very obtrusive when reading code, especially when hints are completely useless:
![image](https://user-images.githubusercontent.com/3883359/32405860-c4db5ba0-c16d-11e7-908f-6e43e96aca37.png)

I know how `console.log` works so I don't need any hints with that. I'm more interested in **reading code around** but hint window obscures my previous code. 

I can disable hinting completely, but this way I disable also other suggestions (so it's needless tradeoff. Sometimes hints can be useful).

Hints are not bad idea, but this is matter how you present these hints to the user and when (and when not? Unless user is beginner in JS, hinting `console.log` is pretty useless)
