### ISSUE TITLE
Rename Symbol when object destructuring leads to compiler error

### ISSUE THREAD

**Issue by greyepoxy** [Microsoft/vscode#36253]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Typescript: 2.5.3
---

Might be another case of https://github.com/Microsoft/vscode/issues/36252 but a little different so opened a separate issue.

**Steps to Reproduce:**
1. I have this code
```ts
interface Result {
    a: number;
}

export function doThing(): Result {
    const a = 5 + 10;

    return {
        a
    };
}

export function DoTheThing(): void {
    const { a } = doThing();
}
```
2. Highlight `a` were object destructuring is occurring (in the `DoTheThing` function).
3. F2 - rename symbol to `b`

**Expected:**
1. No compiler errors
1. Something like the following
```ts
interface Result {
    b: number;
}

export function doThing(): Result {
    const a = 5 + 10;

    return {
        b: a
    };
}

export function DoTheThing(): void {
    const { b } = doThing();
}
```

**Actual:**
```ts
interface Result {
    b: number;
}

export function doThing(): Result {
    const a = 5 + 10;

    return {
        b // <-- this has the error below
    };
}

export function DoTheThing(): void {
    const { b } = doThing();
}
```
severity: 'Error'
message: 'Cannot find name 'b'.'

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19176
