### ISSUE TITLE
Multiple git repositories in single project

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#36250]
It's possible to support multiple git repositories in one project?
Currently my project structure looks like this:

```
- framework (git) 
  -- theme-1 (git)
  -- theme-2 (git)
```

The Source Control tab by default show changes etc. from root catalog - in this example for framework - it's possible to switch default git source to - for example - theme-1 ?

**Comment by seanmcbreen** [comment]
We just added some support for multiple SCM Repositories.  
https://code.visualstudio.com/updates/v1_16#_source-control 

However you need to use the Insiders build:
https://code.visualstudio.com/insiders/

As it's part of our border effort to add support for multi root folders.
https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces

Give it a go and let us know what you think!

Net, net I think we have what you are after so will close for now - but fell free to re-open if not.

**Comment by PixelT** [comment]
I check it in Insiders build, but still can change? git source in my project - they always take .git from root folder...
