### ISSUE TITLE
Bug for JSDoc type checking for `object` type

### ISSUE THREAD

**Issue by Mr-Binary** [Microsoft/vscode#36269]
- VSCode Version: 1.17.1
- OS Version: OS X 10.13

Steps to Reproduce:

1. add a `// @ts-check` at the first line of a new `js` file
1. add a function with the following code:
```javascript
/**
 * return the value of name property
 * 
 * @param {object} obj 
 * @returns {string}
 */
function getName(obj) {
  return obj.name;
}
```
3. Try invoking the function with wrong signature, `getName(1)` or `getName('abc')`, no errors.
4. Seems only work for `string`, `number` or `|` check.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This is by-design, see https://github.com/Microsoft/TypeScript/issues/18396

For cases like this, try specifying what the object interface explicitly:

```js
/**
 * return the value of name property
 * 
 * @param {{name: string}} obj 
 * @returns {string}
 */
function getName(obj) {
  return obj.name;
}
```
