### ISSUE TITLE
Powershell: Debugger timed out, VSCode Insider Version : 1.18.0 32 bit

### ISSUE THREAD

**Issue by plykkegaard** [Microsoft/vscode#36268]
Run debugger (F5) on poweshell does not work since latest download of insider, I get a timeout 
On official build 1.17.7 VSCode 64bit it's fine
Earlier insider builds also did not have the above problem with debugging script
I am only using VSCode for powershell development atm

Thanks /Peter

- VSCode Insider Version : 1.18.0 32 bit
- OS Version: Windows 10 Enterprise 64 bit

Steps to Reproduce:

1. 
Extensions installed:
- Powershell 1.4.3
- XML Tools 1.92
- XSLT snippets 0.1.0

Powershell script opened in editor

Eg (part of script to shut down BizTalk Services)
```
$iis =  Get-WmiObject Win32_Service -Filter "Name = 'W3SVC'"
if ($iis.State -eq 'Running')
{
    Write-Host "Stopping IIS Services /noforce..." 
    & {iisreset /stop /noforce}
}
```
launch.json
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch (current file)",
            "script": "${file}",
             "args": ["-Handle 'Start'"],
            "cwd": "${file}"
        }
    ]
}
```
2. Hit F5 and run debugger on current powershell script

Reproduces without extensions: Can't remove the powershell extension

**Comment by isidorn** [comment]
VSCode has deprecated some API that Powershell is using. Powershell needs to update to this. @plykkegaard can you please file this issue in the powershell repository
ping @daviwil @rkeithhill are you lacking cycles to use the new vscode debug api?

**Comment by plykkegaard** [comment]
Thanks

**Comment by rkeithhill** [comment]
I can take a look at this tonight.

**Comment by rkeithhill** [comment]
@isidorn @weinand OK so the `debugger.startSessionCommand` is deprecated.  There is a new DebugConfigurationProvider that can provide initial configuration and fill in missing details at runtime.  There is a new onDebug activation event.  But what I don't get is what notifies the PowerShell extension to actually start the debug session?  Or is that done automatically by VSCode now?  PS used to call `vscode.startDebug` in the command that handled the startSessionCommand.

BTW has someone notified the OmniSharp (C# debugger) project about this breaking change?  I was looking at their repo for guidance and didn't see any changes related to this.

**Comment by isidorn** [comment]
@rkeithhill thanks for looking into this.
An example how this is done can be seen in the node debug repository https://github.com/Microsoft/vscode-node-debug
Here's the [NodeConfigurationProvider](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L18)

And yes, if I understand your question correctly, VSCode will automatically start the debug session once you provide the configuration. There is no need for you to explicitly call startDebug. Try it out and let me know how it goes :)

**Comment by rkeithhill** [comment]
I think I have it working now.  One question though, VSCode never seems to call our `resolveDebugConfiguration` method.  Is that because we still have our debugger initial configurations defined in the package.json file?

**Comment by isidorn** [comment]
@rkeithhill no, those two are not related. 
Make sure your extension gets activated on the event "onDebug".
Not on "onDebug:powershell" since that is deprecated
