### ISSUE TITLE
eslint no-multiple-empty-lines 

### ISSUE THREAD

**Issue by DestinyHunter** [Microsoft/vscode#36263]
- VSCode Version: 1.17.1
- OS Version: win10

Steps to Reproduce:

1. .eslintrc.js  'rules':{"no-multiple-empty-lines": { max: 2, maxEOF: 1 },
2.  infopop  .eslintrc.js: Configuration for rule "no-multiple-empty-lines" is invalid: Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '{ max: 2, maxEOF: 1 }')

**Comment by scholtzm** [comment]
Your settings are indeed invalid. It should be:

`"no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 1 }]`

Docs: https://eslint.org/docs/rules/no-multiple-empty-lines

**Comment by DestinyHunter** [comment]
Thank you. I only see the blue options above.

**Comment by egamma** [comment]
Closing, if you think this is an issue with the vscode-eslint extension then report the issue in the repository of this extension https://github.com/Microsoft/vscode-eslint
