### ISSUE TITLE
Debug fails to recognise the task has failed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#3626]
- Clone https://github.com/Pure-D/code-d and checkout commit 09ce158566e94bd28cfba9a9fd1365717fa863fd.
- Open that workspace in Code.
- Open `launch.json` and change the `outDir` values to use `${workspaceRoot}`
- Hit F5

You get this error:

![image](https://cloud.githubusercontent.com/assets/22350/13458948/a82dc270-e070-11e5-8aeb-05a4079aefba.png)

Open the task log and you'll see this:

![image](https://cloud.githubusercontent.com/assets/22350/13458956/b72a2746-e070-11e5-8029-bc9a4c3fd8c7.png)

Meaning that the `npm` task failed to execute.

When I run that task in the terminal, I can confirm that it returns a non-zero value. So why isn't Debug picking that up and informing me that the problem occurred in the task itself?

![image](https://cloud.githubusercontent.com/assets/22350/13458970/ce0f880c-e070-11e5-954b-ab53c78c25f9.png)

**Comment by isidorn** [comment]
Nice catch and cool repro steps - thanks!

**Comment by isidorn** [comment]
After talking to @dbaeumer there is a limitation in the task framework for this.

We need API to provide functionality of running a watch task that would return a TaskSummary both in the success and error case. 
Once @dbaeumer adds API I can use it to address this issue, until then -> backlog.

**Comment by isidorn** [comment]
From 2016 -> closing as will not fix, outdated
fyi @alexr00 since there might be a duplicate, or this might have gotten fixed in the meantime
