### ISSUE TITLE
command 'emmet.expandAbbreviation' not found on pressing Tab

### ISSUE THREAD

**Issue by vinzlee97** [Microsoft/vscode#36267]
- VSCode Version: 1.17.1 x64 (1e9d365, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: (all disabled)

Name | Dev | Version
--- | --- | --- 
C/C++ | Microsoft | 0.13.1
C# | Microsoft | 1.12.1
Debugger for Chrome | Microsoft | 3.3.1
Go | lukehoban | 0.6.66
mssql | Microsoft | 1.2.0
Python | Don Jayamanne | 0.7.0
Search Docsets | Silverlake Software LLC | 0.5.2

- Settings:
```
{
    "window.zoomLevel": 0,
    "workbench.sideBar.location": "left",
    "editor.renderWhitespace": "none",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "workbench.startupEditor": "welcomePage",
    "editor.wordBasedSuggestions": false,
    "window.openFoldersInNewWindow": "on",
    "emmet.triggerExpansionOnTab": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"
}
```
Steps to Reproduce:

1. Create a JS file, no need to save it
2. Reload Window or reopen VS Code
3. Press Tab key in the new JS file

Expected result: Indentation on pressing Tab, instead of Emmet expansion
What I've got: Warn message which says: "command 'emmet.expandAbbreviations' not found" and indenting doesn't work

![record_2017_10_14_10_25_26_311](https://user-images.githubusercontent.com/28251913/31574519-c56ba9da-b0fb-11e7-8b94-88eacc593320.gif)

Reproduces without extensions: Yes/No

**Comment by linxiaoru** [comment]
Same here.

**Comment by ramya-rao-a** [comment]
I believe this happens only if the first key pressed is "tab" in a file that is not html/css/scss/less
Can you confirm?

**Comment by vinzlee97** [comment]
Yes, the bug comes in the file types other than html/css/scss/less, and the first key pressed is Tab.

**Comment by ramya-rao-a** [comment]
I have pushed in a fix which will be out in tonight's Insiders build.

Thanks for reporting the issue!

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Set `emmet.triggerExpansionOnTab` to `true`
- Open any non html/css/scss/less file
- The first key to be pressed should be tab

**Comment by vinzlee97** [comment]
Verified in Version 1.18.0-insider
Commit `82dcf98`
Date 2017-10-20T04:24:25.632Z

The indentation in non html/css/scss/less file works.
Thanks for the quick fix.
