### ISSUE TITLE
jsdoc generics via @template not supported

### ISSUE THREAD

**Issue by cancerberoSgx** [Microsoft/vscode#36260]
I've configured jsdoc for js typechecking and autocomplete as explained in https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition  and works ok, but I'm noticing that jsdoc/closure-compiler generics via @template annotation is not supported. 

I'm not using typescript - I'm using JavaScript (jsconfig.json)

For example, the editor will show the error "[js] type Class is not generic" in the following snippet:

Compiling this with jsdoc doesn't throw an error because we are making the class generic with @template annotation: 

```
/**
 * @class
 */
class View {
	/**
	 * @param {View} view_definition
	 * @return {Class<View>}
	 */
	static extend(view_definition) {
		return null;
	}
}

/**
 * @class
 * @template T
 */
class Class {

}
```

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:26:20.018Z)
- OS Version: Linux x64 4.9.51-1-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
JSDocTagComplete|Hoo|0.0.2
flow-for-vscode|flo|0.7.2
code-spell-checker|str|1.4.10

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19215
