### ISSUE TITLE
Add a copy on select option for the terminal

### ISSUE THREAD

**Issue by ngryman** [Microsoft/vscode#36271]
Hi guys,

It's pretty much in the title, would you consider adding a **copy on select** option? If so I could open a PR.

Thanks!

**Comment by Tyriar** [comment]
@ngryman are there other terminals that do this? Wouldn't the fact that it's attached to an editor make it much easier to mess up your clipboard accidentally?

**Comment by ngryman** [comment]
> are there other terminals that do this?

Yes, iTerm on OSX would be the most acknowledged.

> Wouldn't the fact that it's attached to an editor make it much easier to mess up your clipboard accidentally?

Good point, but I don't think so for 2 reasons:
1. It would be an opt-in, so if the user enables it, he is perfectly aware of the feature.
2. It's *copy on select*, so it still involves a user action, that same user perfectly aware of the feature.

Those 2 reasons make a *power* user perfectly conscious of what is happening here.

The motivation for this feature is that when you actually select some text in your terminal, it's 99% of time to copy it and 1% because you have vision problems 🤓. Being able to copy on select simply removes an optional action for power users.

I would also suppose that VSCode users often copy/paste things from the integrated terminal to google errors or search a reference from an error stack in the code. So it makes perfect sense to offer them a way to simplify their life :)

**Comment by Tyriar** [comment]
Created upstream issue: https://github.com/sourcelair/xterm.js/issues/1092, open to PRs

**Comment by Tyriar** [comment]
The upstream issue has been done and I just pulled in the change to vscode `master`, so this issue is unblocked and ready to be worked on.

**Comment by Tyriar** [comment]
Added in https://github.com/Microsoft/vscode/pull/38287
