### ISSUE TITLE
In my vscode extension, I create a new terminal but it has not output in frist time.

### ISSUE THREAD

**Issue by plylrnsdy** [Microsoft/vscode#36279]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
project-manager|ale|0.21.1
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
vscode-faker|dee|1.1.0
githistory|don|0.2.3
tslint|eg2|1.0.11
code-runner|for|0.7.3
seito-openfile|Fr4|1.4.0
mdmath|goe|2.0.7
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
latex-workshop|Jam|3.5.5
docthis|joe|0.5.0
markdown-table-formatter|jos|0.2.3
vscode-codemetrics|kis|1.9.6
vscode-regexp-preivew|le0|0.0.3
vscode-todo-parser|min|1.9.1
vscode-filesize|mkx|1.0.0
cpptools|ms-|0.13.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
vetur|oct|0.9.11
vscode-code-outline|pat|0.0.11
run-as|ply|0.3.10
vscode-icons|rob|7.15.0
ActiveFileInStatusBar|Ros|1.0.3
autoimport|ste|1.2.2
code-spell-checker|str|1.4.10
quokka-vscode|Wal|1.0.70
change-case|wma|1.0.0
---

Steps to Reproduce:

1. open default terminal
2. close vscode
3. open vsscode
4. use my extension 'run-as', right click a file (*.bat or something else), click the menu item 'Run as ..', we can see the terminal 'Run As...' is open but **no output**
5. kill terminal 'Run As...'
6. kill terminal 'powershell', we can see another terminal 'Run As...'
7. kill terminal 'Run As...' again
8. use my extension 'run-as', right click a file (*.bat or something else), click the menu item 'Run as ..', we can see the terminal 'Run As...' is open and finally has output
9. kill terminal 'Run As...'
10. use shortcut Ctrl+` to open **a new default terminal, we can see it named 'Run As...'**

But in this situation, it is no problem
1. close default terminal
2. close vscode
3. open vsscode
4. use my extension 'run-as', right click a file (*.bat or something else), click the menu item 'Run as ..', we can see the terminal 'Run As...' is open and has output

**My extension is work correctly in vscode 1.16.**

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34554
