### ISSUE TITLE
A new action on quick open to browse files

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#36275]
Problem to solve:
* if I put something in `"files.exclude"`, the the excluded files are not revealed in quick open. This is unfortunate somethimes. For example I often put `.gitignore` in the list and it is a pain to type `code .gitignore` in the terminal to edit the file.

Suggestion:
* add a new command `.` in the quick open to navigate from the current project root. the behavior is like this,
  * when typing `.`, the dropdown list shows the root name. 
  * In the mult-root case, it shows a list of roots to select.
  * when typing `./`, list all files and folders in the dropdown list. and filter them when typing more, the list content should just like the list shown in `zsh` after pressing a tab. Note that this list should be complete and ignore the `files.exclude` or `.gitignore` settings. This should also support standard wildcards. When the match is unique, it is good to autocomplete as in the address bar in chrome.
  * In the multi-root case, it indicate the selected root in some way. For example, use a badge at the right side of quick open bar.
  * In addition, we can support `../` for open files outside the root folder.
  * Don't know whether the following is useful, but maybe we can support absolute path using `/` as action name.

**Comment by davidkwan95** [comment]
Is anyone doing this right now? I would like to try this. Can I get any help?

**Comment by innerlee** [comment]
I do not think core devs will do this in near future. It has no assignee and do not in backlog. So spiritually I fully support you implementing it :P 
Maybe I will try it myself, well, four months later...

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by innerlee** [comment]
This smells like a `wont fix`. If that's the case, attach a proper `wont fix`-like label would be great. Otherwise, the closing action is confusing, I thought this do not fit into

> close obsolete/fixed issues

in https://github.com/Microsoft/vscode/issues/38209.
