### ISSUE TITLE
Unreal Engine Please install [clang](https://clang.llvm.org/) or check configuration `clang.executable`

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Microsoft/vscode#36270]
Hi, Unreal Engine has recently officially supported VSCode. I've switched the code editor from Unreal Engine & whenever I open VSCode I saw the above error. I have installed everything. Downloaded the latest clang manually & set path to bin stuff but still doesn't work

How to fix this error?
![visual studio code](https://user-images.githubusercontent.com/8083613/31574865-30aa8280-b0f6-11e7-92b9-d44599dfa90a.PNG)

I'm case of this video. Everything seems fine https://www.youtube.com/watch?v=Bu4JMUjCH00

**Comment by egamma** [comment]
The message comes from one of the C/C++ extensions you have installed, please file the issue against the extension that is causing this message.
