### ISSUE TITLE
Show Fix Bubble issue

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#36273]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|2.2.2
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-todo-plus|fab|1.5.2
auto-rename-tag|for|0.0.14
icon-fonts|idl|1.8.2
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.3.1
vscode-todo-highlight|way|0.5.11

(3 theme extensions excluded)

---
Show Fix Bubble is not showing in the right place. Its always show in one line above. It's okay till the last update. It doesn't make any sense. Hope it would be fixed in the next release. 
![screenshot_20171014_170358](https://user-images.githubusercontent.com/10536234/31575327-af770024-b101-11e7-8e65-56796cc9b58c.png)

**Comment by egamma** [comment]
This is as designed.

**Comment by prasanthnv** [comment]
But it looks odd
