### ISSUE TITLE
would be nice to have "Copy Relative Path of Active File"

### ISSUE THREAD

**Issue by hugo775128583** [Microsoft/vscode#36277]
Now we have "Copy Path of Active File" and it's real convinient. But it would be better if we can copy Relative path of current file in some cases.

**Comment by dKab** [comment]
There are extensions for this.
https://marketplace.visualstudio.com/items?itemName=enochc.copy-relative-path

**Comment by sandy081** [comment]
@hugo775128583 Does the above extension works for you?

**Comment by hugo775128583** [comment]
helpful! Thank @dKab .
