### ISSUE TITLE
vs code always popup a error tag which said i didn't install clang or not configure,how could i fix it?thank you.

### ISSUE THREAD

**Issue by jiajjj** [Microsoft/vscode#36281]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
This looks like an issue with the vscode-clang extension, please file the issue in the repository of this extension.
