### ISSUE TITLE
desktop icon bug

### ISSUE THREAD

**Issue by bfss** [Microsoft/vscode#36282]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0

---

Steps to Reproduce:

After I  updated my VS code to the latest version, my VS code's desktop icon was also that old one.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
>After I updated my VS code to the latest version, my VS code's desktop icon was also that old one.

You mean the desktop icon shown in the task bar was not updated to the new orange icon? Did it help to restart the VS Code?

**Comment by bfss** [comment]
No, just the desktop icon also the blue one, the task bar icon is the new one. I restart my VS code and my computer, nothing changed.

**Comment by joaomoreno** [comment]
This is a cache issue in Windows. 

https://www.google.ch/search?q=windows+refresh+icon+cache&oq=windows+refresh+icon+cache&aqs=chrome.0.0l6.4071j0j7&sourceid=chrome&ie=UTF-8
