### ISSUE TITLE
ES6+ with React Native preview - not possible with either Salsa or TypeScript

### ISSUE THREAD

**Issue by kristianmandrup** [Microsoft/vscode#3628]
Trying to create a React component as a class. Currently my file is called `GiftedMessengerExample.js` and detected as `Javascript (Salsa)`

Following guidelines here: https://babeljs.io/blog/2015/06/07/react-on-es6-plus

Converting method into a property declaration with arrow function. However, when I do this, the IDE complains that this is only supported with TypeScript `.ts` files.
However, if I change the extension to `.ts` it complains about my JSX and type declarations for React imports such as `Text` and `StyleSheet` etc.

Please fix this :)

```js
class GiftedMessengerExample extends Component {
  
  handleSend = (message = {}, rowID = null) => {
    this._gm.setMessageStatus('ErrorButton', rowID); 
  }
```

**Comment by davezuko** [comment]
Not a TS user, but should it be `.tsx` if you're using JSX? Aside from that, is this related to https://github.com/Microsoft/TypeScript/issues/6997 at all?

**Comment by kristianmandrup** [comment]
Wasn't aware of `.tsx` but I tried it and didn't work either. Looks like a fix (or docs) is in the works from what I can gather from the other issues related to this... 
Thanks!

**Comment by egamma** [comment]
Same behaviour when using the latest Code Insider build with TS 1.8.2. 

Moving to TypeScript.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7343
