### ISSUE TITLE
bug Ctrl+D    查找下个匹配   然后按删除键 只删除第一个匹配

### ISSUE THREAD

**Issue by skygst102** [Microsoft/vscode#36299]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|0.21.1
color-info|bie|0.5.0
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
vscode-html-css|ecm|0.1.8
prettier-vscode|esb|0.24.0
mithril-emmet|Fal|0.6.1
php-debug|fel|1.11.1
auto-close-tag|for|0.5.1
code-runner|for|0.7.3
minify|Hoo|0.3.0
autofilename|Jer|0.1.3
docthis|joe|0.5.0
typings-autoinstaller|jvi|1.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.2.0
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1
nodejs-docs|Muk|0.2.2
vscode-css-peek|pra|1.3.1
code-settings-sync|Sha|2.8.3
html5-boilerplate|sid|1.0.1
easy-snippet-maker|tar|0.0.6
vim|vsc|0.10.1
intelligence-change-case|zhe|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by skygst102** [comment]
Ctrl+D    查找下个匹配   然后按删除键 只删除第一个匹配

**Comment by skygst102** [comment]
Ctrl+D looks for the next match, then press delete to delete only the first match

**Comment by egamma** [comment]
@skygst102 thanks for the translation, but the steps to reproduce the problem are still unclear given this translation.
