### ISSUE TITLE
Hovering over the sidebar displays black bars on the editor

### ISSUE THREAD

**Issue by saravanaj** [Microsoft/vscode#36295]
- VSCode Version: 1.17.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Hover over the explorer sidebar
2. A black bar is displayed over the editor

This is very noticeable when using a light colour scheme. 
Here's a small gifv showing the issue: https://i.imgur.com/CytXSNV.gifv

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Looks like a rendering bug, can you reproduce it? If so, does it also happens when you restart VSCode?

**Comment by saravanaj** [comment]
@maxibanki Yes, I can consistently reproduce this even after restarting VS Code.

**Comment by bpasero** [comment]
Does this still happen in 1.26?

**Comment by saravanaj** [comment]
No. Can't reproduce it with 1.26.
