### ISSUE TITLE
launch.json for new java debug extension

### ISSUE THREAD

**Issue by hajiskyy** [Microsoft/vscode#36298]
Hi! humans. I'm having trouble figuring out this launch.json stuff. I'm supposed to enter the fully qualified name of the mainClass but i have no idea what that is. I've tried a bunch of things but i can't figure it out.

i keep getting this error:
Failed to resolve classpath: Main class 'com.java.first' doesn't exist in the workspace.

PLEASE HELP!!

here's the launch.json settings

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "mainClass": "com.java.first", //here's where i'm having an issue. i don't know anything about this.
            "args": ""
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 0
        }
    ]
}

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.11.1
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.3.1
java|red|0.11.0
vscode-icons|rob|7.15.0
vscode-java-debug|vsc|0.1.0
vscode-java-pack|vsc|0.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the java extension you are using. Thank you
