### ISSUE TITLE
Help: how to disable the changes popup?

### ISSUE THREAD

**Issue by yanxyz** [Microsoft/vscode#36292]
- VSCode Version: Code - Insiders 1.18.0-insider (989c40066d124cde846cf5ded8364251246e100e, 2017-10-13T22:58:21.399Z)
- OS Version: Windows_NT x64 10.0.15063
---

Well, I don't know the exact name of this feature

![image](https://user-images.githubusercontent.com/737120/31581355-54fb78c8-b19c-11e7-9e78-4c5a20daeda2.png)

It is boring for me, it is too close to the code folding button, when I click the folding button even when I cut some lines, the popup is automatically opened. 

So how to disable it?

**Comment by joaomoreno** [comment]
#36237
