### ISSUE TITLE
Code Mark, marking code line to specific color (likes notes)

### ISSUE THREAD

**Issue by lamekemal** [Microsoft/vscode#36296]
# **The marking will highlight the codes so that it can be readily identifiable for non-immediate correction.**

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
