### ISSUE TITLE
Sections-size of "Extensions" panel not preserved over restarts

### ISSUE THREAD

**Issue by thierer** [Microsoft/vscode#36297]
([I was told](https://github.com/Microsoft/vscode/issues/36042#issuecomment-336378298) that the implementation of these sections changed, so it probably doesn't only affect the ones in the "extensions" panel, but this is where I noticed it and where I find it easy to reproduce).

Steps to Reproduce:

1. Start vscode and switch to the "Extensions" panel.
2. Notice the size of the "Installed" section (for me it's always two entries after a fresh start):

![image](https://user-images.githubusercontent.com/240625/31583037-361666e2-b193-11e7-9e70-af446375c3d3.png)

3. Resize the "Installed" section so it shows e.g. 3 entries:

![image](https://user-images.githubusercontent.com/240625/31583041-5f389b30-b193-11e7-89b9-9a4e254b58ec.png)

4. Exit and restart and switch to the "Extensions" panel.
5. Result: The size of the "Installed" section is back where it was before resizing:

![image](https://user-images.githubusercontent.com/240625/31583061-c2b7f9e4-b193-11e7-9d16-7bd937160e62.png)

I checked that the section size was saved between restarts at least with 1.16.1 (and probably earlier versions, as I never noticed this behavior before). Can't comment on 1.17.0, I never had that version installed.

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.13.5-1-ARCH

**Comment by sandy081** [comment]
@thierer 

> Exit and restart and switch to the "Extensions" panel.

- What view do you see after restart?
- Are you on the same workspace after restart?

**Comment by thierer** [comment]
> What view do you see after restart?

I'm not sure if that's what you mean, but after a restart the active view is the "explorer" view.

> Are you on the same workspace after restart?

I think by "workspace" you mean which folder is open? When I made the example screenshot I had no folder open at all; but that doesn't matter, if I have a folder opened (which is restored after the restart) the effect is the same.

**Comment by sandy081** [comment]
@thierer Thanks for the information.  Can you please try with our insiders version and see if the issue persists. You can get the insiders from here - https://code.visualstudio.com/insiders

**Comment by thierer** [comment]
I've tried with `code-insider-1.18.0-1508995529_amd64.tar.gz` and it seems to be fixed in that build. Thanks!

(The section site still seems to be reset to 2 entries after installing an additional extension, but that might have been the case with older versions as well.)

**Comment by sandy081** [comment]
Thanks for confirming.
