### ISSUE TITLE
Clicking on lowerleft gear pauses terminal command output

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#36290]
- VSCode Version: Code - Insiders 1.18.0-insider (f1ee80be081b0d47f4423b9dc5f41a65c36146da, 2017-10-13T08:20:36.732Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.5
material-icon-theme|PKi|2.2.2
vscode-eslint|dba|1.3.2
gitlens|eam|5.6.4
tslint|eg2|1.0.11
prettier-vscode|esb|0.24.0
csharp|ms-|1.12.1
vetur|oct|0.9.11
vim|vsc|0.10.1

(1 theme extensions excluded)

---

![pause](https://user-images.githubusercontent.com/4033249/31579572-e734da90-b0ed-11e7-9196-40df76793994.gif)

Don't know if this is as-designed. @Tyriar 

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I'd guess it's related to Electron, can't repro in Chrome v59 on Codepen

**Comment by bpasero** [comment]
Note that showing any context menu will stop the JavaScript engine in the renderer because we open the menu sync.

**Comment by octref** [comment]
@bpasero Thanks for the explanation!
