### ISSUE TITLE
Automatic jump to first error

### ISSUE THREAD

**Issue by aardappel** [Microsoft/vscode#36308]
- VSCode Version: 1.16.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have a tasks.json with reveal set to silent or never.
2. Ctrl+Shift+B on file that has an error (matched by error matcher).
3. My program doesn't launch as expected, I sit there wondering for a few seconds why, until I see there is 1 error in the status bar.
4. I have to press F8 to go to where the error is.

I'd like a setting (in tasks.json or elsewhere) that automates steps 3 & 4, such that if a task matches an error, I am instantly brought to it, saving me seconds each time it happens.

Reproduces without extensions: N/A

**Comment by dbaeumer** [comment]
Dups #37379.

**Comment by aardappel** [comment]
#37379 requests "show error list", which would be helpful, but need one more click to get to the first error. As per the title, this issue requests "jump to first error", which is different.
