### ISSUE TITLE
Strange highlighting of brackets in insiders build

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#3630]
I face these strange highlightings for brackets in the latest insiders build:
![vscode_insiders_feb_brackets](https://cloud.githubusercontent.com/assets/3448684/13460152/03e6732a-e079-11e5-91b1-1967371b1fec.png)

I can't figure out whether the highlighter API has changed so that I need to adjust my OmniPascal plugin or if this is a bug in the latest build. Is @aeschli the right man to ping for this issue?

**Comment by aeschli** [comment]
There hasn't been any changes on the themes and colors lately.
Looks like two independent issues.
For OmniPascal, it seems that the first bracket gets the `token keyword objectpascal' scope, the second one 'token objectpascal'.
I suggest moving this issue to OmniPascal

**Comment by aeschli** [comment]
Closing the issue as this looks like a problem of the OmniPascal grammar
