### ISSUE TITLE
how do you Stop live preview from showing other folders index.html

### ISSUE THREAD

**Issue by misharikw** [Microsoft/vscode#36302]
![capture](https://user-images.githubusercontent.com/30925653/31585679-bb6db8f0-b1ce-11e7-984b-c3262a766f76.JPG)
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.21.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|5.6.4
vscode-html-css|ecm|0.1.8
EditorConfig|Edi|0.11.0
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
code-runner|for|0.7.3
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.1.1
rest-client|hum|0.15.3
crane|Hvy|0.3.8
docthis|joe|0.5.0
Angular2|joh|2.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.66
MagicPython|mag|1.0.12
Angular-BeastCode|Mik|5.0.7
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
csharp|ms-|1.12.1
node-debug2|ms-|1.18.2
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
vscode-docker|Pet|0.0.19
Ruby|reb|0.15.0
java|red|0.11.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.4
code-settings-sync|Sha|2.8.3
stylelint|shi|0.30.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.2
quokka-vscode|Wal|1.0.70
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by misharikw** [comment]
![1](https://user-images.githubusercontent.com/30925653/31585708-183e03c8-b1cf-11e7-95b1-ada151c434ab.JPG)
![2](https://user-images.githubusercontent.com/30925653/31585709-19ad160e-b1cf-11e7-9136-5391948661b9.JPG)
for example here when i place my cursor on one of third  " TD" and when i place my cursor on fourth TD

**Comment by egamma** [comment]
This feature is provided by the live-html-previewer extension, pls file the issue against the repository of this extension https://github.com/HarshdeepGupta/live-html-preview
