### ISSUE TITLE
lorem snippet only worked once

### ISSUE THREAD

**Issue by misharikw** [Microsoft/vscode#36300]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
python|don|0.7.0
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
php-intellisense|fel|1.5.1
auto-close-tag|for|0.5.1
beautify|Hoo|1.1.1
rest-client|hum|0.15.3
crane|Hvy|0.3.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
azure-account|ms-|0.1.3
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
vscode-docker|Pet|0.0.19
Ruby|reb|0.15.0
LiveServer|rit|2.2.1
sass-indented|rob|1.4.4
python|tht|0.2.3
html-css-class-completion|Zig|1.11.0

---

Steps to Reproduce:

1. type lorem tab tab to show the full lorem paragraph
![capture](https://user-images.githubusercontent.com/30925653/31584594-eefb7546-b1b9-11e7-9217-2d57133176a6.JPG)
 then it it stops working if u type it again
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
I could reproduce it. 
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063

I think it isn't working the second time, because the intellisense for the already existing words in the document finds the already existing world `Lorem`. Once you remove the first word from the last lorem ipsum (`Lorem`) then it works well.

**Comment by misharikw** [comment]
yah i have tried what you said and its working again when you remove the first "lorem" word from the first one, is there a fix ? where u can use multi  lorem snippets without removing each time the  "lorem" word from each passage?

**Comment by maxibanki** [comment]
There should be definitely a way that you can use multiple lorem ipsums in one document. When you try to make a second lorem ipsum there is in the intellisense dropdown the entry for the emmet snippet missing.

**Comment by ramya-rao-a** [comment]
As a workaround for now you can do the below

- press ESC to escape the textual suggestion (the suggestion with the "abc" icon)
- Then press Ctrl+Space to trigger suggestions again. The right emmet suggestion will show up

I'll look into providing an actual fix.

**Comment by ramya-rao-a** [comment]
The fix will be out in Monday's Insiders build
