### ISSUE TITLE
No format document option on macOS

### ISSUE THREAD

**Issue by KyleStay** [Microsoft/vscode#36303]
**VSCode Version:** Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
**OS Version:** Darwin x64 17.0.0 / macOS 10.13 (17A405)
**Extensions:**

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
xml|Dot|1.9.2
EditorConfig|Edi|0.11.0
vscode-docker|Pet|0.0.19
html-css-class-completion|Zig|1.11.0
html-snippets|abu|0.1.0
githistory|don|0.2.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
Angular2|joh|2.7.0
Go|luk|0.6.66
azure-account|ms-|0.1.3
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.3.1
Ruby|reb|0.15.0
vscode-icons|rob|7.15.0
code-spell-checker|str|1.4.10

### Steps to Reproduce:

1. Open VS Code on macOS
2. Press `shift` + `option` + `f` on keyboard
3. Notice "Ï" symbol inserted instead of executing `format document` action
4. Search the Help menu for "format"
5. Notice there are no results for `format document`
6. Press `command` + `shift` + `p` on keyboard
7. Type "format" in command palette
8. Notice there is no `format document` option

Reproduces without extensions: Yes

**Comment by KyleStay** [comment]
Looks like this may have been an issue for a while: https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode#comment50800815_29973358

**Comment by egamma** [comment]
The format document command is only available when a language supports formatting. What language are editing when this happens? Can you reproduce this when editing a JavaScript file?

**Comment by KyleStay** [comment]
Thank you! The shortcut and command palette work in javascript.

I was trying to edit a shell script and a Vagrant file (Ruby). Neither worked so it appeared to be broken.

It would be great if users were given a notification that formatting isn't available when they enter the same shortcut that worked on a different file.

Thank you again for your help!

**Comment by egamma** [comment]
>It would be great if users were given a notification that formatting isn't available when they enter the same shortcut that worked on a different file.

good point we will look into this.

**Comment by jrieken** [comment]
It know shows a message telling you what's going on
