### ISSUE TITLE
新版本不能输入英文

### ISSUE THREAD

**Issue by kidddfu** [Microsoft/vscode#36304]
我完全不清楚状况，Mac系统的，自动更新了之后编辑器就不能输入英文了，包括空格。中文可以输入，tab可以输入。请熟悉vscode的同学帮帮我！

**Comment by Spown** [comment]
你为什么认为世界上每个人都会说中文？

**Comment by NateLing** [comment]
translate:
i dont know what happed? when i updated vscode i cant use english,symble and white space.but chinese and tab key. any help?

**Comment by egamma** [comment]
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by kidddfu** [comment]
Apologised to describe the bug in Chinese...it's my fault .
Now I'm here to give more details :
I opened my Macbook to code as usual on October 15th. And I found the icon of vscode turn to A new Yellow icon but previous Blue icon. So I realized vscode may be updated automatically some time I don't know.
But miserably, I can not use it now. The specific detils is like @NateLing translated:
     I can't input English keys, symbles and WhiteSpace by keyboard but Chinese words and Tab key. 
Addition: 
               After several minutes, maybe eight ,maybe tens, it can work again without reason. 
That is the bug all. Now I setup an previous edition to code with vscode. My MacOS edition is 10.26. I don' know what happened.

**Comment by egamma** [comment]
@kidddfu thank you for updating the bug description. We haven't heard about such an issue from others, we will watch out. 

>Now I setup an previous edition to code with vscode. 

Reinstalling the latest edition again will not work for you?
