### ISSUE TITLE
autoClosingPairs with spaces get ignored

### ISSUE THREAD

**Issue by rpalo** [microsoft/vscode#36306]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
emoji|Per|0.0.3
html-snippets|abu|0.1.0
vscode-icontheme-nomo-dark|be5|1.3.3
markdown-preview-github-styles|bie|0.0.4
django|big|1.0.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
fancy-bash|Rya|0.0.1
auto-close-tag|for|0.5.1
ginfuru-vscode-jekyll-syntax|gin|0.0.5
vscode-jekyll-snippets|gin|0.8.6
vscode-auto-open-markdown-preview|hnw|0.0.4
wordcount|ms-|0.1.0
language-liquid|nei|0.0.2
vetur|oct|0.9.11
Ruby|reb|0.15.0
vscode-icons|rob|7.15.0
preview-vscode|sea|1.3.4
vim|vsc|0.10.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1.  Create shellscript extension with language-configuration.json:
```json
{
    "comments": {
        "lineComment": "#"
    },
    "brackets": [
        ["{", "}"],
        ["(", ")"],
        ["do", "done"]
    ],
    "autoClosingPairs": [
        { "open": "[[ ", "close": " ]]" },
        { "open": "{", "close": "}" },
        { "open": "[", "close": "]" },
        { "open": "[[", "close": "]]" },
        { "open": "[ ", "close": " ]" },
        { "open": "(", "close": ")" },
        { "open": "( ", "close": " )" },
        { "open": "((", "close": "))" },
        { "open": "(( ", "close": " ))" }
    ],
    "surrroundingPairs": [
        ["'", "'"],
        ["\"", "\""],
        ["`", "`"]
    ]
}
```
And package.json: 
```json
{
    "name": "fancy-bash",
    "description": "Extra Bash support",
    "version": "0.0.1",
    "publisher": "Ryan Palo",
    "engines": {
        "vscode": "^1.17.1"
    },
    "categories": [
        "Languages",
        "Snippets"
    ],
    "contributes": {
        "languages": [
            {
                "id": "shellscript",
                "aliases": [
                    "Bash"
                ],
                "extensions": [
                    ".sh"
                ],
                "firstLine": "^#!.*bash$",
                "configuration": "./language-configuration.json"
            }
        ],
        "snippets": [
            {
                "language": "bash",
                "path": "./snippets/bash.json"
            }
        ]
    }
}
```
2.  Copy extension to ~/.vscode/extensions
3.  Reload window.
4. Create new .sh file.
5. Try typing `[[ ` (with space), expecting a balanced ` ]]` to autoclose.
6. No space.
7. Add phony `{ "open": "+", "close": "+" } pair to extension to make sure extension is getting loaded.
8. Close and open VSCode.
9. Type `+` and a second `+` comes up as expected.
10. Type `[[ ` (with space), and only `]]` (no extra space) pops up.  Unexpected.
![issue](https://user-images.githubusercontent.com/14909201/31587612-ab4bc24e-b199-11e7-815b-fa9970bf37d0.gif)

Reproduces without extensions: Not possible

**Comment by alexandrudima** [comment]
It is currently not supported that auto closing pairs are composed of more than 1 character. As the user types, one character at a time is evaluated and checked if it is an auto closing pair.

**Comment by rpalo** [comment]
Gotcha.  Any ideas for a work around?  I'm just trying to figure out a way to get surrounding spaces inside my bash conditionals without typing <space> <space> <left arrow>.  It's *exhausting* :wink:

**Comment by alexandrudima** [comment]
Let's track in #583
