### ISSUE TITLE
Please provide way to close *all* messages 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode#36305]
- VSCode Version: 1.17.1
- OS Version: macOS

Steps to Reproduce:

1. Open large solution such as Microsoft/RTVS on github
2. You will get a lot of messages, it takes lots of clicks to close all of them

![image](https://user-images.githubusercontent.com/12820357/31586386-03d7e074-b185-11e7-8dfe-bd806c99c46d.png)

**Comment by nmur** [comment]
You can press Esc to close them all.

**Comment by egamma** [comment]
Closing, as @nmur explains you can dismiss the message boxes using ESC. We have improved support for notifications on our backlog.
