### ISSUE TITLE
Default Settings tab: scroll and opened section lost after activating another tab

### ISSUE THREAD

**Issue by samzzz** [Microsoft/vscode#36311]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---
The Default Settings scroll (and opened section) lost after activating another tab.
Thanks in advance and regards,
Steps to Reproduce:
1. Open some files
2. Open the Default Settings (Ctrl+Comma), scroll down and open a section.
3. Activate another tab.
4. Activate the Default Settings tab and you can notice that the scroll is lost (you are at the top) and the opened section is closed (the first one is opened).

**Comment by isidorn** [comment]
For me the editor scroll position gets nicely preserved, however the expansion of the sections gets lost. Forwarding to @sandy081

**Comment by sandy081** [comment]
Default settings editor was never supporting retaining the view state.

**Comment by sandy081** [comment]
Duplicates #35815
