### ISSUE TITLE
code-insiders: select a file, git-status-color Invalid

### ISSUE THREAD

**Issue by jeasonstudio** [Microsoft/vscode#36317]
- VSCode Version: 1.18.0-insider (1.18.0-insider)
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. not select the file and it will be green
![image](https://user-images.githubusercontent.com/17971291/31594609-96f66ce2-b1fb-11e7-8083-b05f64220214.png)
2. select the file, it becomes white
![image](https://user-images.githubusercontent.com/17971291/31594619-aaa87438-b1fb-11e7-9bf9-9706a2877b06.png)

**Comment by jrieken** [comment]
That was done on purpose because selection highlights and custom colours have a high change of looking bad together. @jeasonstudio What is your suggestion? Do you want to keep the color, or do want to be able to define the selected/focused etc colors for SCM status?

**Comment by jeasonstudio** [comment]
The changeable `fileNameColor` made me confused when I toggle the focus of my files.
I think it better to keep that `status color`. 
Just my personal opinion~ @jrieken

**Comment by jrieken** [comment]
I have now changed it to inherit the default color only when an item is selected *and* focused. As soon as focus goes into the editor the SCM color wins again. Hope. that's better

![oct-16-2017 12-45-14](https://user-images.githubusercontent.com/1794099/31608243-ea7aab48-b26f-11e7-8d82-e985091a9dd1.gif)
