### ISSUE TITLE
Suggestion: Add option for Beautify / Format on Save

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3631]
My last suggestion for this was closed but I think the request was misunderstood. I understand that there is a format on type option which I already have enabled. What I was requesting in #3588 was to have the formatter/beautifier invoked on the entire document when it is saved regardless of any edits that may or may not have been done. Basically this would invoke "editor.action.format" when the document is saved and save the formatted result. I use this feature extensively in other editors and it allows all devs to keep code inline regardless of who or when the file was last revised.

**Comment by isidorn** [comment]
Dup of #3588 which I reopened
