### ISSUE TITLE
IntelliSense based on TypeScript Declaration Files is unavailable while open editor.

### ISSUE THREAD

**Issue by Lxxyx** [Microsoft/vscode#36314]
- VSCode Version: 1.17.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1.

Create a new project.

![image](https://user-images.githubusercontent.com/13161470/31592351-45b563f0-b1ed-11e7-8808-f6fd13a44f09.png)

In test.js:

```js
/**
 * @type {People}
 */
var a = {}

a
```

in myTypes.d.ts

```ts
declare interface People {
  name: string
  age: number
}
```
2.

Result:

![image](https://user-images.githubusercontent.com/13161470/31592399-8d7b3868-b1ed-11e7-8be3-2df18cdcfd22.png)

3.

BUG: when I open my editor. **I must open and edit `myTypes.d.ts`**, then intelliSense service is activate.

![image](https://user-images.githubusercontent.com/13161470/31592429-c65db516-b1ed-11e7-93f2-c97747ec6f2e.png)

If not open `myTypes.d.ts`, intelliSense service is unavailable.

### Extra Question

The Typescript Declaration Files must named as myTypes.d.ts?

Thank you.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project:

```js
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells vscode to treat all js and d.ts files as part of the same project, even if they are not open
