### ISSUE TITLE
VS Code does not pass correct tsconfig to TSServer

### ISSUE THREAD

**Issue by jmathew** [Microsoft/vscode#36318]
# Overview 
I have a typescript project that compiles correctly with `tsc`. However, there are intellisense errors showing. In particular, I have a module declared in one file basically to ignore imports of any style files. I am using fusebox which allows style sheets to be included. 

# Versions

- VSCode Version:
Version 1.17.1 (1.17.1)

- OS Version:
macos seirra 10.12.6 (16G29)

# Repro
Steps to Reproduce:

1. Create an app.d.ts inside a folder named 'src' with the following
```
declare module '*.scss';
```
2. In the same directory create 'app.ts' with the following:
```
import styles from './SomeStylesFile.scss';
```
3. Add 'SomeStylesFile.scss' to the same directory.
4. Create tsconfig.json with the following setup in the directory above 'src':
```
{
	"compilerOptions": {
		"module": "commonjs",
		"moduleResolution": "node",
                "noImplicitAny": true,
                "sourceMap": true,
		"jsx":"react"
	},
	"compileOnSave": false,
	"include": [
		"./src/**/*"
	],
	"exclude":[
		"node_modules"
	]
}
```
5. Run `tsc`. Notice everything compiles with no complaints.
6. Open visual studio code to the same file. 

## Observed
Notice there is an error 'Cannot find module './SomeStylesFile.scss'.

## Expected
No errors same as the tsc command.

# Research
I turned on verbose typescript logs for the typescript server with: 
```
    "typescript.tsserver.log": "verbose",
    "typescript.tsserver.trace": "verbose"
```
in my user settings.

This reveals the log. I've added some interesting bits from it. I can provide the whole thing as well. 
```
[Trace  - 23:49:36] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 6
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve",
        "checkJs": false
    }
}
[Trace  - 23:49:36] Sending request: getSupportedCodeFixes (3). Response expected: yes. Current queue length: 4
[Trace  - 23:49:38] Event received: telemetry (0).
Data: {
    "telemetryEventName": "projectInfo",
    "payload": {
        "projectId": "63832e8e25127ecdb786d75d59a22120",
        "fileStats": {
            "js": 0,
            "jsx": 0,
            "ts": 0,
            "tsx": 102,
            "dts": 9
        },
        "compilerOptions": {
            "module": "commonjs",
            "moduleResolution": "node",
            "noImplicitAny": true,
            "sourceMap": true,
            "jsx": "react"
        },
        "typeAcquisition": {
            "enable": false,
            "include": false,
            "exclude": false
        },
        "extends": false,
        "files": false,
        "include": true,
        "exclude": true,
        "compileOnSave": false,
        "configFileName": "tsconfig.json",
        "projectType": "configured",
        "languageServiceEnabled": true,
        "version": "2.5.3"
    }
}
[Trace  - 23:49:38] Event received: configFileDiag (0).
Data: {
    "triggerFile": "/Users/user/work/FuseBoxTest/wwwroot/src/Clock.tsx",
    "configFile": "/Users/user/work/FuseBoxTest/wwwroot/tsconfig.json",
    "diagnostics": []
}
```

It would seem to me that my project is being considered an inferred project according to this:
https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)

Though I'm not sure why because the tsconfig is clearly being picked up.

# Extensions?
Reproduces without extensions: I believe this requires the typescript compiler extension to work.

**Comment by mjbvz** [comment]
I think the implicit project request is unrelated to the issue. We always send that to TypeScript in order to make sure any loose files that we may encounter are configured properly.

A few questions:

1. If you run `TypeScript: go to project configuration` in  `app.ts` file or in `app.d.ts` , does it go to the correct `tsconfig`
2. What version of tsc are you using to compile? `$ tsc --version`
3. What version of TypeScript is active in the workspace? This is shown in the status bar next to the `TypeScript` language mode

**Comment by jmathew** [comment]
1. `> TypeScript: go to project configuration` in the command palette takes me to the correct tsconfig.json when in `app.ts`, but in `app.d.ts` it says its not part of a project. When it attempts to create one automatically it puts it one level higher. Which in my project is the actual root containing the server implementation.  This is also the directory that contains the `.vscode` folder. 

I still see the same error after adding my tsconfig.json to this folder and modifying the paths slightly to reflect its new position. 

When I go to the dts after the file is added and re-run the `go to config...` it still says there's no tsconfig.json and when I click 'create' it opens the existing tsconfig.json.

I have tried restarting VSCode. No dice.

2. `Version 2.5.3`
3. Typescript 2.5.3

**Comment by mjbvz** [comment]
Thanks @jmathew! I've opened https://github.com/Microsoft/TypeScript/issues/19225 to track this issue upstream against TypeScript
