### ISSUE TITLE
Make "Tab" whitespace character available for searching

### ISSUE THREAD

**Issue by tino2kp** [Microsoft/vscode#36321]
- VSCode Version: 1.17.1
- OS Version: Win 10 x64
Hi, I would like this feature implemented in VS Code. To search space whitespace character is possible, for text editing/manipulating, tab search would be a nice feature just as sublime already supports.
What do you guys think?

![tabsearch](https://user-images.githubusercontent.com/32155919/31596988-8680765e-b20b-11e7-9f89-d7c1ae6e57aa.JPG)

Reproduces without extensions: No

**Comment by purocean** [comment]
use regular expression  *\t*
![image](https://user-images.githubusercontent.com/7115690/31597794-f78e7938-b27c-11e7-8bbf-7a699ad7a1ee.png)

**Comment by egamma** [comment]
@purocean thanks for jumping in. 

Closing the feature request since it is already supported..

**Comment by tino2kp** [comment]
thank you
