### ISSUE TITLE
`vscode.workspace.findFiles` speed

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#36324]
- VSCode Version: 1.17.1
- OS Version: Mac

Steps to Reproduce:

only has one workspace.(1.17.1)

```js
    console.time('vscode');
    const files = await vscode.workspace.findFiles('test/**/*.test.js', 'test/**/fixtures/**');
    console.timeEnd('vscode');

    console.time('globby');
    const result = await globby(['test/**/*.test.js', '!test/**/fixtures/**'], { cwd: vscode.workspace.rootPath });
    console.timeEnd('globby');
```

output:

```bash
vscode: 3986.304756999016ms
globby: 13.889526963233948ms
```

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
In the description above `globby` refers to https://www.npmjs.com/package/globby which is based on glob.

@atian25 you do not use the same glob patterns for the vscode vs. globby test runs. The globby test run is using '!test/**/fixtures/**' (leading @!) and the vscode test run is using 'test/**/fixtures/**'.

**Comment by atian25** [comment]
`export function findFiles(include: GlobPattern, exclude?: GlobPattern, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>;`

the second param of vscode is docs as `exclude`, so I think don't need to pass `!` to it, correct me if I was wrong.

**Comment by roblourens** [comment]
The globs look correct. Does it produce the same number of results? With a difference like that, I would think that we are including more files for some reason.

**Comment by atian25** [comment]
@roblourens I think I found how to reproduce this issue.

```bash
$ git clone https://github.com/atian25/egg-showcase
$ cd egg-showcase
$ npx npminstall
```

test case:
```js
    console.time('vscode1');
    await vscode.workspace.findFiles('test/**/*.test.js', 'test/**/fixtures/**');
    console.timeEnd('vscode1');

    console.time('vscode2');
    await vscode.workspace.findFiles('test/**/*.test.js', '{**/node_modules/**,test/**/fixtures/**}');
    console.timeEnd('vscode2');

    console.time('globby');
    await globby(['test/**/*.test.js', '!test/**/fixtures/**'], { cwd: vscode.workspace.rootPath });
    console.timeEnd('globby');
```

only one result:
```bash
# use `cnpm/npminstall`
vscode1: 5215.872524023056ms
vscode2: 22.511777997016907ms
globby: 4.167885005474091ms

# use origin npm
vscode1: 77.74119102954865ms
vscode2: 55.32521003484726ms
globby: 3.1935110092163086ms
```
```

since we're using [`npminstall`](https://github.com/cnpm/npminstall) / [`pnpm`](https://github.com/pnpm/pnpm) to install node dependencies which will make soft link at `node_modules`.

**Comment by roblourens** [comment]
Ah, yeah there is a known issue with pnpm/cnpm. Tracking this at https://github.com/Microsoft/vscode/issues/35659. Thanks for the investigation help.

**Comment by chrmarti** [comment]
@atian25 Could you rerun your tests with 1.18.0-insiders? There have been a few changes affecting findFiles there and we want to make sure #35659 really covers the entire issue you are seeing.

**Comment by atian25** [comment]
sure, `Version 1.18.0-insider (1.18.0-insider)`, seems fixed this, thanks.

```bash
# use `cnpm/npminstall`
vscode1: 53.27696300111711ms
vscode2: 33.83170799911022ms
globby1: 24.2972289994359ms
globby2: 2.1356440000236034ms

# use origin npm
vscode1: 56.670049000531435ms
vscode2: 63.19821000099182ms
globby1: 32.93946599960327ms
globby2: 15.8237469997257ms
```

**Comment by roblourens** [comment]
Thanks. I think that for a fast search, globby will be faster than ripgrep because we have to send IPC messages across multiple processes, and spawn a new rg process. But I verified in a large workspace with lots of results, that ripgrep is much faster than globby in that case.

**Comment by atian25** [comment]
@chrisbenti @roblourens

had this merge to 1.18 ?

```bash
# Version 1.18.0 (1.18.0)
vscode1: 7445.466ms
vscode1: 7445.017657999881ms
extension.ts:25
vscode2: 20.98140799999237ms
extension.ts:29
vscode2: 21.488ms
globby1: 7.864932000171393ms
extension.ts:33
globby1: 8.260ms
globby2: 4.326971000060439ms
extension.ts:37
globby2: 4.986ms
```

**Comment by roblourens** [comment]
Is that with cnpm?

**Comment by atian25** [comment]
yes

发自我的 iPhone

**Comment by roblourens** [comment]
Nothing has happened with the symlink issue yet but you can work around it by setting `"search.useSymlinks": false`.

**Comment by atian25** [comment]
@roblourens but last time I test with 1.18.0-insider is work fine?
