### ISSUE TITLE
 Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#36328]
Issue Id: <b>c80c979f-f134-ad1e-94eb-a573ee5a3754</b><br /><br />*Versions* <br />- 1.17.0<br />-  1e9d36539b0ae51ac09b9d4673ebea4e447e5353<br />-  81fc22ec957de26d2bf6aada3f16f04e0164741c<br />-  20dfcb6467a2f1aee0f122001a4e69cb3a134dd9<br />*Stack* <br />TypeError: Cannot read property '1' of null<br />    at MouseZoneManager._findZoneEventAt (/node_modules/xterm/lib/input/MouseZoneManager.js:104:34) <no sourcemaps><br />    at MouseZoneManager._onHover (/node_modules/xterm/lib/input/MouseZoneManager.js:66:25) <no sourcemaps><br />    at MouseZoneManager._onMouseMove (/node_modules/xterm/lib/input/MouseZoneManager.js:60:18) <no sourcemaps><br />    at HTMLDivElement.MouseZoneManager.MouseZoneManager._terminal._mouseMoveListener (/node_modules/xterm/lib/input/MouseZoneManager.js:13:63) <no sourcemaps><br />

**Comment by Tyriar** [comment]
PR out: https://github.com/sourcelair/xterm.js/pull/1078
