### ISSUE TITLE
Vscode Sometimes broken

### ISSUE THREAD

**Issue by MrZhang123** [Microsoft/vscode#36320]
Sometimes when I use ^ ` open terminal ,  the vscode broken

- VSCode Version: 1.17.1
- OS Version: macOS High Sierra 10.13
- Extensions:

| Extension    |  Version  | 
| --------   | -----  | 
| EditorConfig for Visual Studio Code | 0.11.0 |
| Nomo Dark Icon Theme | 1.3.3 |
|One Dark Pro | 2.10.16 |
| Path Intellisense | 1.4.2 |
| Prettier formatter for Visual Studio Code | 0.24.0  |
| React Native Tools | 0.4.2 |
| React-Native/React/Redux snippets for es6/es7 | 1.4.1 |
| sass | 1.4.4 |
| Version Lens | 0.19.1 |
| Vetur | 0.9.11 |
| vscode-icons | 7.15.0 |
| vscode-styled-components | 0.0.8 |

### results
![2017-10-16 12 19 37](https://user-images.githubusercontent.com/13158765/31595628-affe2b02-b26f-11e7-9c91-512769bdbf16.png)

**Comment by mjbvz** [comment]
Possibly a dup of #35527

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35527
