### ISSUE TITLE
触摸板双指滚动卡顿

### ISSUE THREAD

**Issue by hsgogo** [Microsoft/vscode#36323]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.打开vscode，或者最小化vscode再打开
2.双指滑动触摸板，有卡顿

fixed issues
1.resize一下窗口，再双指滑动触摸板，卡顿消失

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
assigning to @octref for translation help.

@octref is this is an issue with a high precision touch pad then it is a duplicate of #13612

**Comment by octref** [comment]
@egamma Good guess!

Marking as duplicate of #13612.
