### ISSUE TITLE
 Cannot read property '1' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#36332]
Issue Id: <b>1abbc009-fb5e-70d0-6d21-5762e7e7587d</b><br /><br />*Versions* <br />- 1.17.0<br />-  1e9d36539b0ae51ac09b9d4673ebea4e447e5353<br />-  27492b6bf3acb0775d82d2f87b25a93490673c6d<br />*Stack* <br />TypeError: Cannot read property '1' of null<br />[/vs/base/common/comparers.ts#L43:24](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/comparers.ts#L43:24)<br />[/vs/base/common/comparers.ts#L34:8 (noIntlCompareFileNames)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/comparers.ts#L34:8 (noIntlCompareFileNames))<br />[/vs/base/common/comparers.ts#L128:10 (compareFileNames)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/comparers.ts#L128:10 (compareFileNames))<br />[/vs/workbench/api/node/extHostSCM.ts#L94:14 (comparePaths)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/workbench/api/node/extHostSCM.ts#L94:14 (comparePaths))<br />	at Array.sort (native)<br />[/vs/workbench/api/node/extHostSCM.ts#L211:45 (sort)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/workbench/api/node/extHostSCM.ts#L211:45 (sort))<br />	at /out/vs/workbench/node/extensionHostProcess.js:28:401017 <no sourcemaps><br />	at Set.forEach (native)<br />[/vs/workbench/api/node/extHostSCM.ts#L393:29 (forEach)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/workbench/api/node/extHostSCM.ts#L393:29 (forEach))<br />[/vs/base/common/decorators.ts#L67:40 (apply)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/decorators.ts#L67:40 (apply))<br />

**Comment by joaomoreno** [comment]
There seems to be problems in the current `noIntlCompareFileNames` function.

I'm sure I'm passing strings to `comparePaths`, otherwise there would be an exception before this one. So it must mean that the regexp fails to match.

@bpasero any thoughts?

**Comment by bpasero** [comment]
@joaomoreno oh yeah, wasn't aware that exec returns null if not matching!
