### ISSUE TITLE
 Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#36333]
Issue Id: <b>beeb52ec-1d01-7612-4b8a-810b19e9781e</b><br /><br />*Versions* <br />- 1.17.0<br />-  f6ef4bef42fa2948426c99fefa340235e67a0c5e<br />-  81fc22ec957de26d2bf6aada3f16f04e0164741c<br />-  caa5656df9e8fa9c556c7eddeb6b4d532814054b<br />-  20dfcb6467a2f1aee0f122001a4e69cb3a134dd9<br />-  7ac1f1e05baad03d4dd8f8515f1e598180b2c97e<br />-  f31c369c3bd686d494cb0f01a4ed051b5e9956d0<br />*Stack* <br />TypeError: Cannot read property '0' of undefined<br />    at TextRenderLayer._clearChar (/node_modules/xterm/lib/renderer/TextRenderLayer.js:152:41) <no sourcemaps><br />    at TextRenderLayer.onGridChanged (/node_modules/xterm/lib/renderer/TextRenderLayer.js:88:30) <no sourcemaps><br />    at /node_modules/xterm/lib/renderer/Renderer.js:146:60 <no sourcemaps><br />    at Array.forEach (native)<br />    at Renderer._refreshLoop (/node_modules/xterm/lib/renderer/Renderer.js:146:28) <no sourcemaps><br />

**Comment by Tyriar** [comment]
Fixed already
