### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'getIndentLevel' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#36336]
Issue Id: <b>7f31e4e5-3ae9-f29e-a9b8-bc1e4e83ea88</b><br /><br />*Versions* <br />- 1.17.0<br />-  5316a2d916b504cc627eb68e119e6b99ea7ad5e5<br />-  f6ef4bef42fa2948426c99fefa340235e67a0c5e<br />-  81fc22ec957de26d2bf6aada3f16f04e0164741c<br />*Stack* <br />TypeError: Cannot read property 'getIndentLevel' of null<br />[/vs/editor/contrib/quickFix/browser/lightBulbWidget.ts#L139:23 (getIndentLevel)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/editor/contrib/quickFix/browser/lightBulbWidget.ts#L139:23 (getIndentLevel))<br />[/vs/editor/contrib/quickFix/browser/lightBulbWidget.ts#L111:9 (_show)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/editor/contrib/quickFix/browser/lightBulbWidget.ts#L111:9 (_show))<br />[/vs/base/common/winjs.base.raw.js#L1524:0 (onComplete)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1524:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L1180:0 (call)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1180:0 (call))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1813:0 (complete)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1813:0 (complete))<br />[/vs/base/common/winjs.base.raw.js#L1838:0 (argDone)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1838:0 (argDone))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />

**Comment by jrieken** [comment]
Still seeing this...

**Comment by jrieken** [comment]
Code has changed in the meantime. Wait for this to occur again in a different way...
