### ISSUE TITLE
Allow add "Open Editors" panels in every sideBar tabs

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#36337]
It will be great to display opened files not only in Explorer, but in every panels.
Simpler to understand with some images of the idea : 

Explorer (as is now) :
![image](https://user-images.githubusercontent.com/5599375/31601460-3ae23670-b25a-11e7-969a-fa1cd6c9ff7e.png)

In search panel : 
![image](https://user-images.githubusercontent.com/5599375/31601687-faa625ac-b25a-11e7-877c-88995752a3db.png)

in git panel : 
![image](https://user-images.githubusercontent.com/5599375/31601716-14dc223c-b25b-11e7-8bfb-c41527dc2463.png)

in debug panel : 
![image](https://user-images.githubusercontent.com/5599375/31601740-2eb06c72-b25b-11e7-9e70-739b4ac245dc.png)

Many in my work team use VScode without file tabs displayed, and only switch files with shortcuts and "open editors" panel.
This is very annoying yet working on global search without seeing actual opened files. 

Regards,

**Comment by isidorn** [comment]
@DavidBabel the whole vscode team also does not use tabs and we all got used to just having the history of files opened accessible via `ctrl + tab`. After some time you will get used to that flow and will not need the visual representation of this at all (OpenEditors). However keeping this issue open as a feature request - though there is 0% change we implement it :)

**Comment by DavidBabel** [comment]
> the whole vscode team also does not use tabs
It explain many things on the design ;)

Thanks for you answer. Keep it as feature request, maybe someday a contributor will PR this.
Search in the whole project without seeing explorer or/and opened file is not very usefull, but it's a personnal opinion

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
