### ISSUE TITLE
Feature request: improve terminal history

### ISSUE THREAD

**Issue by csicky** [Microsoft/vscode#36339]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
EditorConfig|Edi|0.11.0
auto-close-tag|for|0.5.1
vue-snippets|hol|0.1.5
vetur|oct|0.9.11
vscode-react-native|vsm|0.4.2
ReactSnippets|xab|1.4.0

---
I would like to have a cleaner history in the integrated terminal, if possible. I work on different projects, some start with `npm run dev`, others with `npm start`, other times I have to kill node process with a terminal command, or do a `npm install`, just simple daily things. What I don't like is that I have to press key up on keyboard many times until I find the command I need from history. I have like five entries in history and I would have to press max five times, but instead it happens to be much more. The history is chronological right now. If I use for a week one of the commands daily, it means I have to press that many times until I find the previous command from last week.
I don't know if it's a PowerShell setting or VS Code.

Steps to Reproduce:

1. Press key up in terminal.

Reproduces without extensions: probably

**Comment by csicky** [comment]
Found this via Google: `Set-PSReadLineOption –HistoryNoDuplicates:$True`
After I run it the history is how I would like it. Unfortunately it stays like this only in the current instance. Basically I just would like the above command to stay on for all VS Code integrated terminals all the time,  if it is an improvement for more users.

**Comment by Tyriar** [comment]
Currently this is all handled by your shell and I don't think we will attempt to change this. Your options are:

- Try out reverse history search ctrl+r, this may meet your needs
- Investigate whether your shell of choice has options such as `-HistoryNoDuplicates` or sharing history across sessions
- Look into macro software to automate typing in the common commands
- Look into extensions that automate this
