### ISSUE TITLE
Add the option to search only in modified git files

### ISSUE THREAD

**Issue by wcastand** [Microsoft/vscode#36345]
- VSCode Version: Version 1.18.0-insider (1.18.0-insider)
- OS Version: macOS Sierra 10.12.6

I search in the issues and didn't find this feature request. add an option to search only in the modified files not committed to git yet.
I don't know if that's enough informations, don't hesitate to ask if you don't understand something.

If that's something that people want. I don't mind working on this.

**Comment by roblourens** [comment]
This is included in https://github.com/Microsoft/vscode/issues/20530. Main question for me would be UI and how widely valuable it is. I wouldn't take a PR for it yet.
