### ISSUE TITLE
Character "g" in bold is clipped in the terminal

### ISSUE THREAD

**Issue by Flavien** [Microsoft/vscode#36341]
- VSCode Version: 1.17.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Run anything from the terminal which outputs bold text
2. The character "g" in bold is clipped at the bottom. See attached screenshot.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/296540/31604433-331e3fc8-b25b-11e7-8dc6-16e222f43278.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
