### ISSUE TITLE
Emmet's format.noIndentTags setting doesn't seem to work

### ISSUE THREAD

**Issue by exectails** [Microsoft/vscode#36347]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.7.2
contextualduplicate|laf|0.2.0
csharp|ms-|1.12.1
seti-icons|qin|0.1.3
easysass|spo|0.0.6

---

Steps to Reproduce:

1. Try to modify "format.noIndentTags"
2. Notice that it doesn't do anything

Reproduces without extensions: Yes

I'm trying to clear "format.noIndentTags", so the content of HTML's html tag gets indented, but changing it in the user settings doesn't seem to do anything. Changing it in a preferences.json in the Emmet extension folder didn't work either. I tried setting it to an empty string, null, and an empty array, but to no avail. Further, adding new values to it, like "head", doesn't do anything either, so I guess it's either completely broken, or I'm doing something wrong.

My user settings:
```json
{
    "emmet.preferences": {
        "format.noIndentTags": []
    }
}
```

(I copied the above code from another issue on here about a similar problem.)

**Comment by ramya-rao-a** [comment]
The fix for this will be in Monday's Insiders build
