### ISSUE TITLE
Add support for use case-sensitive sorting in File Explorer

### ISSUE THREAD

**Issue by LitoMore** [Microsoft/vscode#36346]
It's a feature request.

- VSCode Version: Version 1.17.1 (1.17.1)
- OS Version: macOS 10.13.1 Beta (17B35a)

### Current sorting behavior

```
- CODE_OF_CONDUCT.md
- composer.json
- CONTRIBUTING.md
```

### Wannted sorting behavior

```
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- composer.json
```

It can be an option of File Explorer, like:

```
"explorer.caseSensitiveSorting": true
```

**Comment by isidorn** [comment]
There is already `explorer.sortOrder` which accepts a lot of options. This would be a new option. We accepts PRs that fix this.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L595

**Comment by pradeepmurugesan** [comment]
Also requires a change in the sort function ? When I browsed through the code I could find

https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/comparers.ts#L59

is responsible for comparing the filenames and converts everything to lowecase by default. 

I believe should also change the method signature here to accept whether its a case-sensitive or case-insensitive comparison. The value of the flag may be case-insensitive by default. 

something like 

```
noIntlCompareFileNames(one: string, other: string, caseSensitive:boolean = false): number
```

Kindly correct me if I am wrong.

**Comment by isidorn** [comment]
@pradeepmurugesan feel free to submit a pr where we can discuss this further.
@bpasero fyi
