### ISSUE TITLE
Git: VSCode's branch not in sync

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#36343]
- VSCode Version: 1.18.0 insiders
- OS Version: Windows 10 x64

Steps to Reproduce:

1. open a terminal and type `git checkout <branch>`
2. VSCode still shows the old branch at the bottom left of the window

What should happen?
VSCode should show the current branch

Reproduces without extensions: Yes

![vscodegit](https://user-images.githubusercontent.com/199648/31605881-d1a86234-b267-11e7-9c1a-90cdd28c95f6.gif)

**Comment by warpdesign** [comment]
Note that if I restart VSCode it correctly shows the new branch.

**Comment by joaomoreno** [comment]
If you wait long enough (10 seconds) does it work?

If you create a file in the Windows Explorer, inside your workspace folder, does it appear in Code's explorer automatically?

**Comment by warpdesign** [comment]
It seems the problem is related to newly-created branch: when using `git checkout -b new_branch` VSCode doesn't update current branch to `new_branch`, even if I wait a full minute.

Switch back to `master` and again to the `new_branch` doesn't work either.

If I create a file in the Windows Explorer it appears immediately in Code'es explorer.

**Comment by joaomoreno** [comment]
> It seems the problem is related to newly-created branches

So if you simply switch between existing branches, it works?

**Comment by warpdesign** [comment]
Yes.

**Comment by joaomoreno** [comment]
I can't seem to reproduce. Does it reproduce in other repositories you have?
