### ISSUE TITLE
search in file drops down file view

### ISSUE THREAD

**Issue by zzjin** [Microsoft/vscode#36355]
- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T05:11:43.411Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.21.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
code-runner|for|0.7.3
phpcs|ika|0.7.0
haml|kar|0.9.0
vscode-filesize|mkx|1.0.0
sublime-keybindings|ms-|2.9.1
Ruby|reb|0.15.0
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

open one file. press `cmd+f` to search in file.
file shown down as blow:
![image](https://user-images.githubusercontent.com/679757/31612346-03e37726-b2b2-11e7-8995-6f50a5f9e6d0.png)
![image](https://user-images.githubusercontent.com/679757/31612373-141e2276-b2b2-11e7-97a6-d2bd260edca3.png)

Reproduces without extensions: Yes

**Comment by egamma** [comment]
The sliding down happens when the find match is on the first line and this is by design.
