### ISSUE TITLE
Text in switch cases should be formatted with an added indent

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#36357]
- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T04:23:04.454Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

**Steps to reproduce:**

1. Use `alt+up` or `alt+down` to move a statement or comment in a switch-case.

Reproduces without extensions: Yes

---
**switch-indent.ts**
```ts
function test(a: any) {
  switch (a) {
    default:
      // Moving either line will cause both to lose an indent.
      console.log('hello world');
      return;
  }
}
```

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/31864, let's track it there.
