### ISSUE TITLE
Broken dropdown for terminals

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#36353]
- VSCode Version: 1.17.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open vscode open a few terminals
2. press the dropdown

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/11232402/31611923-aac7a9a8-b286-11e7-95cb-8ce826986832.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/25700
