### ISSUE TITLE
Feature request: editor.wordHighlightBorder

### ISSUE THREAD

**Issue by will-stone** [Microsoft/vscode#36354]
It would be really nice if we could add borders to matches (like Atom): 

![image](https://user-images.githubusercontent.com/654103/31612175-cc675082-b276-11e7-919a-8a9b9ce6bda6.png)

**Comment by egamma** [comment]
// CC @alexandrudima @aeschli

**Comment by will-stone** [comment]
I can see this was implemented today as dotted/dashed. Can we set the style to solid? Or is that coming? Just wondering why you guys went with dashed style?

**Comment by aeschli** [comment]
The borders are currently hardcoded. Different styles were chosen to distinguish the selections in case you pick the same border color.

**Comment by will-stone** [comment]
Ah, yes. Any chance of the style being an option? Then we can make that decision in out themes. It's just that I find solid lines less jarring than dashed lines (and others may feel the complete opposite).

**Comment by aeschli** [comment]
Please file a feature request, or rename this request, as `editor.wordHighlightBorder` and `editor.wordHighlightStrongBorder` are avaiable since the February build.

**Comment by will-stone** [comment]
Will do, thanks 👍
