### ISSUE TITLE
what's this? pop-up windows

### ISSUE THREAD

**Issue by illinux** [Microsoft/vscode#36351]
![snipaste_2017-10-16_19-53-56](https://user-images.githubusercontent.com/30189427/31610952-a684d37c-b2ac-11e7-833b-2c952b390787.png)

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.16.0
bracket-pair-colorizer|Coe|0.10.9
vscode-markdownlint|Dav|0.10.1
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
python|don|0.7.0
vscode-great-icons|emm|2.1.16
php-debug|fel|1.11.1
code-python-isort|fre|0.0.3
output-colorizer|IBM|0.1.2
easy-icons|jam|0.3.1
format-php|Kas|1.1.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
start-git-bash|McC|1.2.1
vscode-filesize|mkx|1.0.0
vscode-docker|Pet|0.0.18
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
guides|spy|0.9.0
python|tht|0.2.3
vim|vsc|0.10.1
bootstrap-3-snippets|wcw|0.1.0

(11 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
When does this window appear? What did you do before this window appears, does it always appear? I cannot reproduce it given the screenshot only. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
