### ISSUE TITLE
Add workspace identifier and file hash to telementry data

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#36350]
To better classify workspace it would be helpful to have the following additional telemetry data:

- a unique workspace identifier (not containing any PII). Could be the hash for the folder. @bpasero you mentioned we do have such an identifier internally already
- a hash of the file path opened to not count file more than once to classify a workspace.

@seanmcbreen @kieferrm any objections to add this?

**Comment by dbaeumer** [comment]
Noticed that we already sent a anonymize path. Will dig into whether this is what I need

**Comment by bpasero** [comment]
@dbaeumer here is what the workspace ID is today:
* empty workspace: a unique identifier that is stable as long as the workspace is reopened (goes away when closing the workspace)
* folder workspace: the hash of the folder path
* workspace: the hash of the location of the workspace file

Note that this ID can change when transitioning from folder workspace into workspace without a window reload.

**Comment by bpasero** [comment]
I added the hash for workspace.

**Comment by dbaeumer** [comment]
@bpasero thanks a lot!

**Comment by dbaeumer** [comment]
Thanks for @bpasero this is done for October.
