### ISSUE TITLE
Git actions should prompt a dialog if required.

### ISSUE THREAD

**Issue by devvpm** [Microsoft/vscode#36352]
When you git pull from the menu and if the repository requires password it should ask for the password in a dialogue box instead of showing it as an error.

Same with passphrases for rsa key.  It should open a dialogue if it requires to enter the passphrase.

**Comment by joaomoreno** [comment]
@devvpm Can you show me a screenshot of the error?

Code will ask for your credentials if git asks for them. If git doesn't ask for them, Code won't ask for them.

Code will never ask for your private key's passphrase though. Only for HTTPS user/pass credentials.

What happens if you run `git pull` from the command line? Does it ask you for anything?

**Comment by devvpm** [comment]
When I do `git pull` from the terminal, It asks for the password, it works fine. However, when it is done from Menu, It does not ask for the password instead shows this error. 
![git issue](https://user-images.githubusercontent.com/1164077/31750549-6b07e146-b4b3-11e7-90d5-8e38128012bf.png)

**Comment by joaomoreno** [comment]
I don't know what that means. You should reach out to your system administrator.

**Comment by devvpm** [comment]
When I do git pull from the terminal, it asks for git password with that message. My git url protocol is ssh. 
When I do git pull from the menu instead of prompting for the password it shows this error. However, [Pycharm](https://www.jetbrains.com/pycharm/) asks for the password in a dialogue when I do git pull.

**Comment by joaomoreno** [comment]
Can you check, using a process manager, which process actually asks you for credentials, when you run from the command line? You should see a tree of processes. The furthest deep in that tree is the process asking you for credentials. Is the prompt in a UI dialog, or in the command line? Do you have any special type of SSH key authentication?

**Comment by devvpm** [comment]
That message is actually from the HOST, That is shown even in the terminal when I do pull and password is asked in the terminal. In Pycharm, when I do git pull from UI, it asks a UI dialogue.  I will check which process actually asks for credential and share here.

**Comment by joaomoreno** [comment]
Thanks. Can you also show me a screenshot of Pycharm's popup?

**Comment by devvpm** [comment]
Here is the Pycharm popup.
![ssh](https://user-images.githubusercontent.com/1164077/31770446-87b5ebc4-b50a-11e7-98f7-a1d08cf59116.png)

**Comment by joaomoreno** [comment]
Maybe... is it possible if you can show me the process tree of Pycharm when that happens?

**Comment by devvpm** [comment]
Trying to see the process tree in Window7, Can I share the `tasklist `output?
