### ISSUE TITLE
Clicking the fold controls in the gutter opens changes magnification.

### ISSUE THREAD

**Issue by mcarpenterjr** [Microsoft/vscode#36365]
- VSCode Version: Version 1.18.0-insider

Steps to Reproduce:

1. Make some changes to any file that has some Source Control. Specifically foldable changes.
2. Click the fold controls in the gutter.

Reproduces without extensions: Yes

![changes_gutter](https://user-images.githubusercontent.com/11430497/31620165-8d0ed1ba-b264-11e7-9bf7-63ce5ef97d48.gif)

I Would hope that's not the expected behavior. It is wicked annoying.

**Comment by joaomoreno** [comment]
#36237
