### ISSUE TITLE
VSCode refuses to perform commit when "git includeIf" is used

### ISSUE THREAD

**Issue by bad-ed** [Microsoft/vscode#36368]
VSCode refuses to commit to git repository if global git config file does not contain [user] section, but contains "includeIf" sections, which include other config files which have credentials, like this:
global `.gitconfig` file:

```
[includeIf "gitdir:E:/work"]
  path = .gitconfig-work
```

`.gitconfig-work`:

```
[user]
  name = User
  email = user@email.com
```

Git outputs in console:

```
git commit --quiet --allow-empty-message --file -
*** Please tell me who you are.
```

However if I perform commit from command line, everything is ok.

- VSCode Version: 1.17.1
- OS Version: Windows 7

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/11656761/git-please-tell-me-who-you-are-error

**Comment by bad-ed** [comment]
Bug is not about "please tell me who you are". Bug is about using _conditional_ config includes. Git, when used from command line, works properly and actually performs commit without issuing this error. But when I perform commit from VSCode, it can't find out user/email from included config.
