### ISSUE TITLE
File explorer: After closing active file, file explorer moves to previous one

### ISSUE THREAD

**Issue by klinki** [Microsoft/vscode#36369]
- VSCode Version: 1.16.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open any file in your project
2. Open some very nested file in `node_modules`   (this one can be any directory, my point is this issue is most annoying for some very nested file).
3. Close the file

After closing the file, file explorer scrolls to last active file. Which is very annoying, when you need to open several files from some node module.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Configurable via `"explorer.autoReveal": false`

**Comment by klinki** [comment]
it works, thanks!
