### ISSUE TITLE
vscode could not perform as well on mac as on windows 7.

### ISSUE THREAD

**Issue by thkfly** [Microsoft/vscode#36362]
1. I tried 1.17 edition at first. However, I just could not type code on the editor.
2. Then I went back to 1.16 ed. It could type. However, after installing the plugins, I found it could not offer code hints and on some clicks it reports some error as follows :
"Cannot read property 'value' of null"

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.10.1
vscode-pandoc|Dou|0.0.8
python-docs|Muk|0.8.0
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
vscode-python-docstring|aza|0.0.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
markdown-preview-github-styles|bie|0.1.0
flask-snippets|cst|0.0.4
python-snippets|cst|0.0.5
algorithm-mnemonics-vscode|dav|1.0.2
jupyter|don|1.1.3
python|don|0.7.0
python-extension-pack|don|1.0.0
code-runner|for|0.7.2
code-python-isort|fre|0.0.3
mdmath|goe|2.0.7
CppSnippets|har|0.0.12
Python-autopep8|him|1.0.2
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-flake8|jay|0.0.4
clangcomplete|kub|0.0.6
cmake-tools-helper|mad|0.1.1
MagicPython|mag|1.0.12
cppcheck|mat|0.2.1
markdown-shortcuts|mdi|0.8.1
vscode-clang|mit|0.2.2
vscode-ai|ms-|0.1.2
cpptools|ms-|0.13.1
wordcount|ms-|0.1.0
reloaded-cpp|rel|0.1.6
preview-vscode|sea|1.3.4
markdown-preview-enhanced|shd|0.2.9
vscode-table-formatter|shu|1.2.1
spellchecker|swy|1.2.13
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
cmake-tools|vec|0.10.2
vscode-arduino|vsc|0.2.9
jinja|who|0.0.8
clang-format|xav|1.6.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.10.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1. install the vscode as default set
2. install python plugins

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this only happen after you install the python extension? How about if you disable all extensions?

**Comment by thkfly** [comment]
on version 1.17, I reinstalled it many time, but just could not type in the editor except  TAB and BACKSPACE key.

on version 1.16, all the functions around the python plugins do not work. I suspect that there must be some defects in vscode

**Comment by thkfly** [comment]
<img width="578" alt="2017-10-17 9 33 47" src="https://user-images.githubusercontent.com/3348908/31642637-90cbe228-b2b1-11e7-9be9-12e260e5c8a5.png">

**Comment by thkfly** [comment]
<img width="585" alt="2017-10-17 9 36 43" src="https://user-images.githubusercontent.com/3348908/31642681-c54f8356-b2b1-11e7-85a1-d96b04e4e35c.png">
It seems that the buttons do not work

**Comment by mjbvz** [comment]
From those errors, it seems like you have some misbehaving extensions. Can you try disabling all extensions by running the `Extensions: Disable all installed extensions` command in VS Code and then restarting the editor. After disabling all extensions, does this still happen

**Comment by thkfly** [comment]
<img width="762" alt="2017-10-17 4 40 38" src="https://user-images.githubusercontent.com/3348908/31654904-fd7f3b8c-b2ec-11e7-9248-cad02de072d7.png">
I find that the 'code runner' plugin is disabled, and there is no button , no errors. (ed 1.16)

However, whenever I turn on any plugins, they seem do not work

By the way, ed 1.17 could not type on the editor in any case so that I give up this edition

**Comment by mjbvz** [comment]
Sorry, I don't understand the problem. So when you have any plugin enabled, code stops working?

**Comment by thkfly** [comment]
It could type in 1.17.2 and all the plugins could be load correctly.

By the way, when all plugin enabled in 1.16, code could type while plugins do not work
