### ISSUE TITLE
[Feature Request] Report deleted text in `onDidChangeTextDocument` when user deletes text

### ISSUE THREAD

**Issue by vvatikiotis** [microsoft/vscode#36361]
- VSCode Version: 1.17.1 
- OS Version: macOS Sierra 10.12.6

Hello,

Is there a way to retrieve deleted text during normal user delete operations? In the `onDidChangeTextDocument` event listener, when text is inserted it can be found under the `evt.contentChanges[0].text` property. When the operation is a deletion this property is the empty string, which imo is correct since, the way I understand it, the design approach seems to be that `contentChanges`  contains a `start` and `end` Position and the new `text`. However, that leaves me with no way of getting the deleted text.

PS: I tried to work around this via the undo mechanism, but I cannot find any API about it.

Thanks

**Comment by HoboKristian** [comment]
Any update on this issue? I am having the same problem.
