### ISSUE TITLE
来自小小的建议

### ISSUE THREAD

**Issue by luluyiluchangtong** [Microsoft/vscode#36378]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. You can't right-click on it, paste it on the desktop, or whatever it is
2. You can't copy the entire contents of the code segment, and you can only copy the contents of the code snippet when you expand it

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Can you please provide an example of these

**Comment by mjbvz** [comment]
Closing as this is not actionable without more information about the problem
