### ISSUE TITLE
New monokai selection color is too subtle

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#36376]
@aeschli I see that the monokai select color was changed in https://github.com/Microsoft/vscode/commit/f319787f7dfac28138499569bdf216616e82416a. I find it really hard to see, especially for small selections.

Old

![image](https://user-images.githubusercontent.com/323878/31637002-a117d54a-b281-11e7-8c30-b275f502a4f0.png)

New

![image](https://user-images.githubusercontent.com/323878/31636987-8de6594c-b281-11e7-916f-bb9291152524.png)

I'm not sure it addresses the original issue anyway. 

![image](https://user-images.githubusercontent.com/323878/31637114-076141b0-b282-11e7-98fd-805b52bf05c9.png)

The left side is selected, but I can't tell the difference. Maybe this isn't the right case.

**Comment by aeschli** [comment]
@roblourens Your screenshot is with the Monokai Dimmed themed, which is not related to the changes in https://github.com/Microsoft/vscode/commit/f319787f7dfac28138499569bdf216616e82416a

**Comment by aeschli** [comment]
I made similar improvements to the Monokai theme:
![image](https://user-images.githubusercontent.com/6461412/32889201-38f0f04e-caca-11e7-96ed-03e176907bb8.png)
![image](https://user-images.githubusercontent.com/6461412/32889225-4fc9d790-caca-11e7-88fd-5b9d310c0fcc.png)

**Comment by roblourens** [comment]
No, it's normal Monokai
