### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by eboujlal** [Microsoft/vscode#36377]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
react-native-react-redux|EQu|1.4.1
react-native-react-redux-snippets-for-es6-es7-version-standard|EQu|1.0.3
vsc-material-theme|Equ|1.0.5
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.2
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
python|don|0.7.0
prettier-vscode|esb|0.24.0
file-icons|fil|1.0.5
flow-for-vscode|flo|0.7.2
auto-close-tag|for|0.5.1
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.14
docthis|joe|0.5.0
MagicPython|mag|1.0.12
vscode-extension-auto-import|mop|1.3.3
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.3.1
color-highlight|nau|2.3.0
react-native-snippet|san|0.6.0
autoimport|ste|1.2.2
python|tht|0.2.3
vscode-react-native|vsm|0.4.2
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What is the error?
