### ISSUE TITLE
Running `git pull origin master --rebase` on vscode console always fails first time

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#36375]
- VSCode Version: Version 1.17.0 (1.17.0)
- OS Version: Mac OS Sierra 10.12.5 (16F73)

Steps to Reproduce:

```
➜  analytics git:(nojvek-sst) git pull origin master --rebase
remote: Counting objects: 204, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 204 (delta 136), reused 146 (delta 136), pack-reused 50
Receiving objects: 100% (204/204), 58.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (148/148), completed with 87 local objects.
From github.com:mixpanel/analytics
 * branch                  master     -> FETCH_HEAD
   533c3a3255..29c9380710  master     -> origin/master
First, rewinding head to replay your work on top of it...
fatal: Unable to create '/Users/nojvek/mp/analytics/.git/index.lock': File exists.
```

**Comment by nojvek** [comment]
I suspect, this is due to vscode doing some sort of file watching and it tries to run a fetch operation while a pull rebase operation is going on. I just think vscode needs to be smarter and not interfere with a manual git command operation

**Comment by joaomoreno** [comment]
We do have a *lot* of smartness around this. Unfortunately, if you run a command from the integrated terminal this can still happen. How long does that command usually take for you?

Does it reproduce if run it in the Terminal app (not inside Code)?

**Comment by nojvek** [comment]
Will give that a shot and report back.

Does this happen because vscode watches files inside the.git folder?

**Comment by joaomoreno** [comment]
Yes.

**Comment by nojvek** [comment]
@joaomoreno the issue happens when doing git pull -rebase inside vscode but doesn't happen when doing it from external terminal e.g the built in macosx terminal app.

Not sure how to re-open the issue.

**Comment by joaomoreno** [comment]
It's fine. As I said, the work is done on our side. The next release of git will work together with our fix and make this problem go away.

**Comment by nojvek** [comment]
You guys are awesome. Look forward to the next release.
