### ISSUE TITLE
The first letter used by SCM Decoration in Explorer is not always the best in some locales.

### ISSUE THREAD

**Issue by Joelism** [Microsoft/vscode#36373]
- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T04:23:04.454Z)
- OS Version: Windows_NT x64 10.0.17017

---
Eg. In zh-CN and zh-TW
For edited files, it shows '已', meaning 'already' in Chinese.
Maybe leave it in English.

Reproduces without extensions: Yes

**Comment by jeasonstudio** [comment]
I'm facing the same problem, so I change the language mode to en-US.

**Comment by Joelism** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/41f0ff15d7327da30fdae73aa04ca570ce34fa0a, it seems.
Close issue
