### ISSUE TITLE
Rename Symbol in C# Code does not rename

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#36371]
- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T05:22:08.224Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.9
erb|Cra|0.0.1
html-leaf|Fra|0.1.3
json-to-ts|Mar|1.5.3
Angular-BeastCode|Mik|5.0.7
material-icon-theme|PKi|2.2.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.2.3
tslint|eg2|1.0.11
vscode-ember|emb|0.1.0
prettier-vscode|esb|0.24.0
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.2.0
Angular2|joh|2.7.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
EmberES6Snippets|pha|2.1.2
typescript-hero|rbb|1.5.0
vscode-icons|rob|7.15.0
git-merger|sha|0.3.6
autoimport|ste|1.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Click on a symbol (class name)
2. Hit F2 (Or right click and choose rename)
3. Should rename the symbol and any references to it, but it does not, nothing changes.

**Comment by mjbvz** [comment]
Please try opening this against the c# extension: https://github.com/OmniSharp/omnisharp-vscode/issues/new
