### ISSUE TITLE
Saving new file: the save-dialog doesn't use last working directory

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#36379]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
contextualduplicate|laf|0.2.0
MDTools|sea|1.0.1

---

Steps to Reproduce:

1. Make new file.
2. Attempt to save.
3. Save-dialog always uses home directory (e.g: `/home/user/`). It doesn't use current working directory (for the file next to it), or last working directory (if there are no files opened next to it).

Reproduces without extensions: Yes

Would you please check?

Thank you,

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/22697
