### ISSUE TITLE
Warning takes precedence over error in squiggles

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#36374]
This piece of code gets warning from TSLint and an error from TypeScript. I would expect red squiggle to be shown but the warning one wins:

![image](https://user-images.githubusercontent.com/101152/31631601-7982f760-b2ba-11e7-879a-750525b3e664.png)

Only when I fix the weaker warning, I see the error:

![image](https://user-images.githubusercontent.com/101152/31631682-b6f7be00-b2ba-11e7-9e4d-b1155a1df8f1.png)

BTW, the Problems panel is sorted correctly from the start:

![image](https://user-images.githubusercontent.com/101152/31631616-86504d08-b2ba-11e7-8a02-77802ad6d2ed.png)

- VSCode Version: 1.17.1
- OS Version: Win10

**Comment by rcjsuen** [comment]
I noticed this in my language server as well running VS Code 1.17 on Windows 10.

**Comment by alexandrudima** [comment]
This is a regression from making the colors for the warnings and errors externalized.

For reference: https://microsoft.github.io/monaco-editor/
<img width="350" alt="image" src="https://user-images.githubusercontent.com/5047891/31826532-9d1d2b0c-b5b5-11e7-8b4d-d900df61975b.png">

**Comment by fbricon** [comment]
This is a problem affecting vscode-java too.
