### ISSUE TITLE
Indent command keyboard shortcut

### ISSUE THREAD

**Issue by zevero** [Microsoft/vscode#3637]
alt+up shifts a line up
alt+down shifts it down

I have set

    { "key": "alt+right",           "command": "tab",
                                       "when": "editorTextFocus" },
    { "key": "alt+left",            "command": "outdent",
                                       "when": "editorTextFocus" },`

And it works as expected for selected text.
But if no text is selected only the tab command alt+right fails.
It is just making a tab.

Could we have an indent command?

**Comment by Tyriar** [comment]
@zevero use `"editor.action.indentLines"` and `"editor.action.outdentLines"` for this

**Comment by zevero** [comment]
Great!!!
I should have looked better at the documentation at
https://code.visualstudio.com/Docs/customization/keybindings

Hey, why not give a reference link in keybinding.json ?
Or in the default table (examples are already given) but a link might be
very helpful.


2016-03-02 18:44 GMT+01:00 Daniel Imms <notifications@github.com>:
