### ISSUE TITLE
vscode insiders cmd+mouse left click cannot work, and vscode works 

### ISSUE THREAD

**Issue by KISSMonX** [Microsoft/vscode#36381]
- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T05:11:43.411Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.29
vscode-docker|Pet|0.0.19
solidity-extended|bea|3.0.2
path-intellisense|chr|1.4.2
githistory|don|0.2.3
python|don|0.7.0
pgsql|dou|0.0.8
code-runner|for|0.7.3
docker-linter|hen|0.4.0
rest-client|hum|0.15.3
Go|luk|0.6.66
azure-account|ms-|0.1.3
vscode-icons|rob|7.15.0
vscode-uppercase|rui|1.0.1
markdown-preview-enhanced|shd|0.2.9
gitblame|wad|2.2.0
vscode-todo-highlight|way|0.5.11
markdown-pdf|yza|0.1.7

(1 theme extensions excluded)

---

**Comment by KISSMonX** [comment]
cmd+mouse left click  --->> go to definition

**Comment by mjbvz** [comment]
What language are you working in? Does it still happen if you disable extensions?

**Comment by KISSMonX** [comment]
@mjbvz  Thank You. 
settings.json  Comment out this line can work properly. 
`// "editor.multiCursorModifier": "ctrlCmd",`
