### ISSUE TITLE
can't display chinese

### ISSUE THREAD

**Issue by wangjie182** [Microsoft/vscode#36389]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide some information about the bug, such as steps to reproduce and screenshots of the problem

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
