### ISSUE TITLE
there is code ghosting  in the terminal

### ISSUE THREAD

**Issue by tingtien** [Microsoft/vscode#36382]
- VSCode Version: 1.17.0
- OS Version: 10.11.6

Steps to Reproduce:

1.  when output logs in the terminal, there is code ghosting.
![image](https://raw.githubusercontent.com/tingtien/node-web/master/templates/images/1.jpg)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This is fixed in the latest, please update VS Code 😃
