### ISSUE TITLE
Intellisense Sometimes Stop Working.

### ISSUE THREAD

**Issue by tusharpatil-tlg** [Microsoft/vscode#36383]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
polymer-snippets|chi|1.0.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
xml|Dot|1.9.2
gitlens|eam|5.6.4
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
beautify|Hoo|1.1.1
angular2-switcher|inf|0.1.4
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.4
Angular2|joh|2.7.0
language-polymer|jon|1.0.3
Polymer2Snippets|jus|0.0.5
mssql|ms-|1.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.3.1
angular2-inline|nat|0.0.17
polymer-ide|pol|0.6.0
vscode-icons|rob|7.15.0
code-spell-checker|str|1.4.10
html-css-class-completion|Zig|1.11.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What language? Does this still happen if you disable extensions?

**Comment by Hypernut** [comment]
I can confirm this for powershell. Hard to reproduce this though. Sometimes intellisense just does not work and then works again.

**Comment by sojimaxi** [comment]
@mjbvz Honestly I love Visual Studio Code, but the Intellisense issue is really a pain. For almost 2 weeks, I have been restarting Code more than **20 times a day**. 

Trust me it's really frustrating. Very simple insignificant code  like `import JsClass from "./utils"` where the class does not exist in that file easily break Intellisense and you are on your own until you restart Code.

 I disable all extensions and its all the same. Actually right now I just removed the 64bit version to install 32bit and see if there would be a difference.

I keep asking my self why should my code break Intellisense. I don't see it happening elsewhere. I switched to Code based on the small memory footprint and enjoyable workflow. Every other feature works great but Intellisense really needs a lot of work and we all appreciate the great effort the contributors have been putting into this project.

**Comment by jonathanhupp** [comment]
I am also experiencing this issue. Primarily when using the path intellisense, when I get to a directory that takes awhile to load (if it ever loads) it blocks any other intellisense from working.

**Comment by mjbvz** [comment]
@jonathanhupp  I believe you could have been hitting https://github.com/Microsoft/TypeScript/issues/16329 Can you please try using the current VS Code insiders builds and let me know if you see any improvement

@sojimaxi It sounds like intellisense just completely breaks for you sometimes, is that correct? Can you also please try out the insiders builds but also set `	"typescript.tsserver.trace": "verbose"` in your user settings. Then, if intellisense stops working, please open the output panel and look in the `typescript` section. There may be some error messages that can help us track down what is going wrong
