### ISSUE TITLE
how to remove vscode from --user-data-dir?

### ISSUE THREAD

**Issue by Jaironlanda** [Microsoft/vscode#36388]
- VSCode Version: 1.17.1
- OS Version: Ubuntu 16.04 LTS

Hi,
i'm new in Linux and i need help. 
How to remove vscode from `--user-data-dir`
i follow from this link 
https://askubuntu.com/questions/803343/how-to-run-visual-studio-code-as-root

**Comment by mjbvz** [comment]
Please try posting questions like this to stackoverflow first

Also it is unclear to me you you mean by removing vscode from `--user-data-dir`. Please include an example or additional information in you stackoverflow question
