### ISSUE TITLE
Can not input English letters, white space, punctuation but Chinese and Tab in new(Maybe?) edition

### ISSUE THREAD

**Issue by kidddfu** [Microsoft/vscode#36387]
Apologised to describe the bug in Chinese...That's my fault .
Now I'm here to give more details :

I opened my Macbook to code as usual on October 15th. And I found the icon of vscode turn to A new Yellow icon but previous Blue icon. So I realized vscode may be updated automatically some time I don't know.

But miserably, I can not use it now. The specific details is like :

I can't input English letters, punctuation and WhiteSpace by keyboard but Chinese words and Tab key.
After several minutes--maybe eight ,maybe tens, it can work again suddenly without reason, and the words I input in "crash state" all re-displayed in vscode operation panel.
That is the bug all. Now I setup an previous edition to code with vscode. My MacOS edition is 10.26. I don' know what happened.

Thanks for criticism, and I will use English to ask a question afterwards.

**Comment by bryfroze** [comment]
Same problem, can't input anything except use simplified input method, since version 1.17.1

**Comment by bryfroze** [comment]
Same problem, can't input anything except use simplified input method, since version 1.17.1 !!!
I reinstalled vscode and let setting reset, no extendsion, no keybind setting, still dont work.
Search viewlet is working fine.

**Comment by alexandrudima** [comment]
I still cannot reproduce. 

@rebornix @octref : is there anything basic I'm missing here ? Can you reproduce ?

**Comment by octref** [comment]
@alexandrudima This is a very popular IME in China: http://pinyin.sogou.com/mac/ I guess they are using it.

@kidddfu @bryfroze Are you using 搜狗？If so what's the version of it?
Also, Are you on Windows, Mac or Linux?

**Comment by octref** [comment]
I cannot repro with 搜狗 on Mac or Win.

**Comment by bryfroze** [comment]
@octref @alexandrudima 
IME: 搜狗, but im not using it to input English
![](http://otw24a63u.bkt.clouddn.com/1508813156.png?imageMogr2/thumbnail/!70p)
MacOS High Sierra 10.13

**Comment by bryfroze** [comment]
@octref @alexandrudima @kidddfu 
I think i found problem, its maybe some(don't know exactly) extension's compatibility, not vscode, i delete the .vscode directory in my Mac and everything is fine now.

**Comment by alexandrudima** [comment]
:+1: @bryfroze do you still remember what extensions you've had installed? @kidddfu does the issue reproduce when disabling all extensions ?

**Comment by bryfroze** [comment]
@alexandrudima I try to find the reason, but i can't reproduce when i installed all extensions back. I restored my extensions and setting with sync-setting, but this problem has not reappeared. so it became a mystery 😅

**Comment by alexandrudima** [comment]
Let's keep an eye on this and if you have any reproducible steps, I'd be happy to try them.
