### ISSUE TITLE
Tab Align Problem

### ISSUE THREAD

**Issue by archi1016** [Microsoft/vscode#36385]
![untitled 1](https://user-images.githubusercontent.com/10942241/31647655-14e4b10e-b33c-11e7-9741-5a688b4536b4.png)
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.16
material-icon-theme|PKi|2.2.2

(6 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
We don't support this formatting style out of the box. Support for aligned formatting in javascript and typescript is tracked by https://github.com/Microsoft/TypeScript/issues/11865

Try installing a formatter from the marketplace to get the desired formatting
