### ISSUE TITLE
i'am not good at English,so i used Chinese to describe this big issue

### ISSUE THREAD

**Issue by hcf1994** [Microsoft/vscode#36391]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2
vscode-eslint|dba|1.3.2
csharp|ms-|1.12.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1.ie浏览器、VisualStudio的窗口 与VSCode的窗口在切换时会使窗口内容卡住（主要是通过鼠标点击另一个窗口的“底层”部分切换）

2.对于大段gbk编码的文字转码会卡死

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Does this only happen when you are running VS Code alongside those other applications?

**Comment by hcf1994** [comment]
是的 特别是微软自己的产品 Chrome浏览器没有上述问题

**Comment by hcf1994** [comment]
刚刚发现 office系列（Word Excel）可能也有同样的问题

**Comment by mjbvz** [comment]
Since other program besides vscode cause this, it sounds like it may be an issue with your operating system

Closing as external
