### ISSUE TITLE
Debugger client error, Error: This socket is closed.

### ISSUE THREAD

**Issue by spagidipati** [Microsoft/vscode#3639]
working with Ruby extension and somehow debugging is not working in Windows 7 64x , all debugging navigation is disabled except stop button.

**Comment by isidorn** [comment]
Are you sure that ruby debugging is supported on Windows 7?
I suppose you are working with this extension https://github.com/rebornix/vscode-ruby
I would first file an issue there, because it sounds like there is an issue with the ruby extension, not vscode iteself

**Comment by isidorn** [comment]
Closing for now, will reopen if more data is provided
