### ISSUE TITLE
[html] read over php tags

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#36396]
Add a mode where the html language server reads over `<?php  ... ?>` and `<?= ?>` tags.

**Comment by bmewburn** [comment]
Thanks for your help with this. I'll just summarise so I have this straight in my mind. I hadn't realised there was a simple api call to forward requests, that makes things easier. 

A php client should listen to php language id requests only and forward on requests to the html language client/server using `commands.executeCommand` and a custom language id `phtml`. A php client could further filter requests to the html server by first testing for a falsey response from the php server. Requests handled by the html server would read over and ignore php tags when processing a response. This circumvents the need to declare language ranges or alter the original document.

**Comment by bmewburn** [comment]
Giving this more thought, there may be occasions where php is embedded in css and js, in this case I assume that changes to the html scanner would not be enough. Perhaps it's inevitable that the php extension modifies the document and handles the php ranges itself?

**Comment by bmewburn** [comment]
@aeschli I ended up escaping the php and forwarding to html server so feel free to close unless you think there's still value here. I followed your example [here](https://github.com/Microsoft/vscode/blob/7ba55c5860b152d999dda59393ca3ebeb1b5c85f/extensions/html/client/src/htmlMain.ts#L95) One thing I'm trying to solve is that if language modes are switched off php and then back again the forwarding to html no longer works. Did you come across anything similar?

**Comment by aeschli** [comment]
@bmewburn Cool. Yes, escaping the PHP tags is also great and will help you with html inside PHP.
I don't know why switching language modes back an forth could result in the forwarding to no longer work. If you are not in PHP mode you obviously will no longer get the code complete requests, but once you switch back you should get the requests. 
Otherwise, please file a bug with a small code example...
