### ISSUE TITLE
Interaction of json editor with tasks

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode#36398]
I've noticed interesting side effect of choosing name `taskName` instead of plain `name`:

The Json editor built in VS Code treats `"name"` node specially and allows quick navigation inside file via `Ctrl+Shift+O`.

For example in `launch.json`:
![image](https://user-images.githubusercontent.com/7413219/31655788-4fa4ca48-b32a-11e7-9c2a-ee6419dc2ede.png)

If I try to find task with same name in `tasks.json` I get an empty list.

I'm not sure if it is possible to change schema at this stage, but it would be nice usability improvement.
Maybe it is possible to patch up Json editor a bit and consider this 'feature' in future.

**Comment by ytimenkov** [comment]
Related to #28235

**Comment by alexr00** [comment]
Still a problem in v2 of tasks with "label".
