### ISSUE TITLE
Cannot read property uri of indefined when opening a new terminal tab

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#36392]
- VSCode Version: 1.18.0 insiders
- OS Version: MacOSX + Windows 10

Steps to Reproduce:

1. Open VSCode without opening any folder or workspace
2. Open the terminal panel
3. Click on + to open a new tab

You get the error `Cannot read property 'uri' of undefined.`

The error happens in [terminalActions.ts](https://github.com/Microsoft/vscode/blob/3495b0b185acbe8188e821ccb3ae807274703a9c/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts) `line 236`. I wanted to fix the problem but I am not sure what to do: where should I get the cwd in case there's no workspace?

The error happens both when running without a workspace or if VScode has opened a workspace but the user closes the dialog without selecting a workspace.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@warpdesign thanks for the pointer to the file, that's all the info I need to fix it 👍
