### ISSUE TITLE
Cursor Issue on bash terminal scroll

### ISSUE THREAD

**Issue by viren-singh** [Microsoft/vscode#36397]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 
<img width="387" alt="issue" src="https://user-images.githubusercontent.com/31695669/31654443-b3e50b44-b343-11e7-95e2-7792e2506799.png">

---

Steps to Reproduce:

1.For Bash Terminal on Scroll bar cursor is not highlight as pointer. 

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/1067

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/39832
