### ISSUE TITLE
Extension process makes Macbook Air fan goes crazy!

### ISSUE THREAD

**Issue by Totoajax** [Microsoft/vscode#364]
Since the new update (0.10.1) my Macbook Airs fan sounds like a jet engine!!! If this isn't a bug, please make an option to disable some of the new things to make it quiet again. I REALY REALY loves Visual Code, so please fix this!

**Comment by Totoajax** [comment]
I tracked it down, and found that it's the plugin handler or something. I could close it from activation control. I forgot what it was called. But now it works perfectly (But I guess the plugins won't work)

**Comment by Totoajax** [comment]
It's called electron helper and takes 99% of CPU usage

**Comment by bpasero** [comment]
@Totoajax what extensions do you have installed?

**Comment by Totoajax** [comment]
@bpasero Go and bookmarks. I'm gonna try remove them And see if it works

**Comment by lukehoban** [comment]
@Totoajax Did removing these extensions fix the issue?  If so, did you get a chance to identify which extension was causing the issue?

**Comment by Totoajax** [comment]
@lukehoban I've now worked with vs code for a long time after removing the extensions. And it works perfect! The extension that made the fan go crazy was Go. I installed bookmarks after the first sounds came. BUT I haven't tried to run only with bookmark, so I can't say there's not a problem with bookmarks

**Comment by lukehoban** [comment]
Okay - since this was caused by the Go extension I'll move it over to that repo to investigate further.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode-go#58

**Comment by bpasero** [comment]
@lukehoban hey how do you move issues on GitHub ;)?

**Comment by lukehoban** [comment]
I've used https://github-issue-mover.appspot.com/ which has worked well for me so far for one-off moves.
