### ISSUE TITLE
About extension error.

### ISSUE THREAD

**Issue by returnGirl** [Microsoft/vscode#36401]
- VSCode Version:  1.17.0 (1.17.0)
- OS Version: macos 10.12.6 

Steps to Reproduce:

1.open extension
2.choose any installed extension
3. uninstall
4. "sure to uninstall" choose no.
5. 
![image](https://user-images.githubusercontent.com/14890909/31656690-0537ab5c-b2f2-11e7-8468-ce33c486bbf8.png)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Can you please try collecting the full information about this error using  the developer console. To do this: In VSCode run the `Toggle developer tools` command to open the developer console, then look in the console for any error messages. Please share the full stack of these errors

**Comment by mjbvz** [comment]
Closing as not actionable without additional information
