### ISSUE TITLE
Please add option to turn off capitalization of pane names

### ISSUE THREAD

**Issue by andrzejc** [microsoft/vscode#36403]
VS Code renders all pane titles in capital case (majuscule to be exact: "OPEN EDITORS" vs "Open Editors"). This makes them less readable - it's especially visible in folder explorer sidebar pane, when the folder name is using CamelCase. The lowercase letters are there in the alphabet for a reason, which is that the presence of asceners and descenders is a visual aid in faster recognizing letter shapes (faster reading). See the following quote from Wikipedia: Long spans of Latin-alphabet text in all upper-case are harder to read because of the absence of the ascenders and descenders found in lower-case letters, which can aid recognition (https://en.wikipedia.org/wiki/Letter_case#Capitalisation). This is consistent with common knowledge, so the choice of CAPITALCASE rendering is even more astonishing.

**Comment by misolori** [comment]
I could see us adding a user settings option for this. @bpasero, thoughts? Below are a couple screenshots:

![image](https://user-images.githubusercontent.com/35271042/40332071-87579178-5d07-11e8-929e-fc45888ca6b0.png)
![image](https://user-images.githubusercontent.com/35271042/40332095-9e8f236a-5d07-11e8-8ab8-01d81837d09f.png)
![image](https://user-images.githubusercontent.com/35271042/40332103-a6481eb8-5d07-11e8-8277-377305ff19a6.png)

**Comment by lig** [comment]
@misolori this would look even more awesome if it would be displayed using Ubuntu Light or Droid Sans;)

**Comment by misolori** [comment]
Since there are no plans to make this happen, closing this as `out of scope` but will watch this thread for increased interest from the community. Thanks!

**Comment by andrzejc** [comment]
how can I make it not out-of-scope? it's a real issue.

**Comment by misolori** [comment]
@andrzejc my mistake, this shouldn't be closed or out of scope (I misunderstood how we handle these issues). Re-opening.

**Comment by lig** [comment]
This is the only thing which really frustrates me in VS Code :(

**Comment by misolori** [comment]
Given that there hasn’t been much activity here and that we have no plans to introduce this feature anytime soon, I’ll be closing this as out of scope. If we ever decide to revisit this we will reopen the issue. Thanks for the feedback.

**Comment by gjsjohnmurray** [comment]
The new `workbench.experimental.modernUI` experimental setting changes this.
