### ISSUE TITLE
Feature request: Typescript completion in Angular/Vue html templates

### ISSUE THREAD

**Issue by victorgarciaesgi** [Microsoft/vscode#36405]
It would be very useful to have typescript completion inside the frameworks templates.
For exemple: 

Here typescript should be suggesting me the properties I provided with "ITodos".
It's a single file component so Typescript should know which Class to look into for data

![image](https://user-images.githubusercontent.com/15092120/31658719-17b6bd46-b332-11e7-9303-2ec651c12c52.png)

Also it should work with Web components! Typescript could suggest the component Props inside the Html.

Thanks

Victor Garcia

**Comment by mjbvz** [comment]
For vue, please try the [vetur extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur). I'm not sure if it fully supports your scenario yet. This may be tracked by https://github.com/vuejs/vetur/issues/145

For angular, please see the [angular language service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template)
