### ISSUE TITLE
can't preview markdown file

### ISSUE THREAD

**Issue by Wingless-Archangel** [Microsoft/vscode#36400]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
vscode-docker|Pet|0.0.19
python|don|0.7.0
vscode-html-css|ecm|0.1.8
php-intellisense|fel|1.5.1
code-runner|for|0.7.3
docker-explorer|for|0.1.5
shell-format|fox|1.1.1
MagicPython|mag|1.0.12
Kotlin|mat|1.3.0
azure-account|ms-|0.1.3
java|red|0.11.0
bash-beautify|sha|0.1.1
cucumber|ste|0.9.6
vim|vsc|0.10.1
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1. open md file
2. click Preview to the Side

Reproduces without extensions: No

**Comment by mjbvz** [comment]
So when you disable all of your extensions, the preview starts working again? Can you then try selectively enabling some of the extensions again to see which one causes breaks the preview

**Comment by Wingless-Archangel** [comment]
I found that this one causing the issue.
https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by mjbvz** [comment]
Thank you for the followup. Please try filing an issue against whatever extension you believe is causing this issue
