### ISSUE TITLE
vsCode 对于 MySQL 的语法支持

### ISSUE THREAD

**Issue by ISuuuu** [Microsoft/vscode#36409]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.0
csharp|ms-|1.12.1

---
mysql 创建一个触发器，语法显示不对
CREATE TRIGGER update_sex BEFORE INSERT ON personinfo_2 FOR EACH ROW
SET New.SexName =  (CASE New.SexCD 
                WHEN '1'     THEN '男' 
                WHEN '2'     THEN '女'                               
         END )

**Comment by zjjott** [comment]
Can you  speak English in a international project

**Comment by ISuuuu** [comment]
Create a trigger , It runs correctly in Mysql 。But Virtual tudio Code  shows grammatical errors. 

Forgive my poor English.

**Comment by mjbvz** [comment]
Please file issues with sql against your sql extension: https://github.com/Microsoft/vscode-mssql/issues/new

In the new issue, please include some example code and possibly a screenshot of the issue
