### ISSUE TITLE
Blurred text on integrated terminal

### ISSUE THREAD

**Issue by angelmadames** [Microsoft/vscode#36419]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.10.0-37-generic
- Distribution: Ubuntu 17.04 (Zesty)
- Extensions: none
---

Steps to Reproduce:

1. Install VSCode from .deb package
2. Open Integrated terminal.

Images:
v1.16 (not-blurred):
![not-blurred](https://user-images.githubusercontent.com/9947992/31667481-94c75896-b31d-11e7-99f8-1766b57af733.png)

v1.17(blurred):
![blurred](https://user-images.githubusercontent.com/9947992/31667486-97572d02-b31d-11e7-8946-abe9a6584bd9.png)

Details:

On versions 1.16.x and 1.17.0 the integrated terminal works perfectly fine (except for some resize functionalities). After the 1.17.1 update, I noticed the blurred output. Everything else seems to work as expected. I tried reinstalling but the issue persisted. I tried downgrading to 1.16, and the difference persisted. Also, I used two new VMs, 16.04 and 17.04 respectively. In the 16.04 version, the output is not blurred but it is on 17.04. Thus, this issue only affects 17.04.

**Comment by Hurtak** [comment]
I have blurred text on Ubuntu after update from 1.17.0 to 1.17.1

**Comment by CoolName1993** [comment]
I'm having the same issue on Windows 10.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35991
