### ISSUE TITLE
Cannot save files without extension

### ISSUE THREAD

**Issue by YoDaMa** [Microsoft/vscode#36416]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.10.1
vscode-instant-markdown|dba|1.3.0
python|don|0.7.0
minify|Hoo|0.3.0
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.3.1
python|tht|0.2.3
vim|vsc|0.10.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Launch VSCode and write a few lines in an unnamed file.
2. Go to save and save it as Makefile without any extension
3. An error will be shown saying this filename is not valid.

Reproduces without extensions: **Yes**

**Comment by mjbvz** [comment]
@YoDaMa Can you please check if an extension is causing this issue. To so this, disable all of your extensions by running the `Extensions: Disable all installed extensions` command in vscode and then restart the editor.

**Comment by bpasero** [comment]
@YoDaMa there is an entry in the "Save as type" dropdown "No Extension" that you need to pick for this to work.
