### ISSUE TITLE
Occasional gibberish inserted into C++ code after Format Document

### ISSUE THREAD

**Issue by bojunehsu** [Microsoft/vscode#36418]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.4.1
include-autocomplete|ajs|0.0.4
githistory|don|0.2.3
python|don|0.7.0
scala-lsp|dra|0.2.2
code-runner|for|0.7.3
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
team|ms-|1.122.0
material-icon-theme|PKi|2.2.2
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Edit C++ code.  Verify that it compiles.  See completionTrieTest.cpp
2. Select Format Document (Alt+Shift+F).
3. Note that the gibberish is sprinkled across the code.  See completionTrieTest.gibberish.cpp.  With some files, when I close and reopen the file, Format Document works again.  With the attached file, it consistently fails in my VSCode session.  But if I relaunch VSCode, it succeeds again.  Unfortunately, I do not have a deterministic repro.  So I hope the gibberish file helps narrow down the issue.  This issue occurs about once every 30 times.

[completionTrieTest.zip](https://github.com/Microsoft/vscode/files/1391033/completionTrieTest.zip)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
