### ISSUE TITLE
I can't input any char in vscode after use Command+Q,except backspace and ctrl

### ISSUE THREAD

**Issue by zjjott** [Microsoft/vscode#36411]
It happend very suddenly,I use vscode this afternoon,and I don't remember  I have any strange operation 
Now I can't input any char in vscode,but I can use keyboard to select or copy text,and I can use backspace or delete to delete char
Any input place can't input any char,include command panel and search panel

- VSCode Version:1.17.2

- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. I can reproduce it:open some file and use `command+Q` to quit it,and now,files which is just open can't edit,and after that,other file open is still can't edit too.
2. It can continuous reproduce,if you close or `command+Q` with these file can't edit,and reopen or restart your computer.To resolve it ,close all file in workspace,and open some file which never open

Reproduces without extensions: Yes, I start code without extensions,and this issue is still reproduce

I upgrade to 1.17.2,it still can reproduce

**Comment by zjjott** [comment]
@chrmarti hello,I can reproduce in 1.17.2,it should be a bug in this release version too

**Comment by alexandrudima** [comment]
@zjjott Are you certain you have disabled all extensions? VSCode must be restarted after disabling all the extensions in the extensions viewlet.

Can you share your `keybindings.json` ? Does typing work in other areas of our UI ? like e.g. in the search viewlet ?
