### ISSUE TITLE
code -n does not force a new instance

### ISSUE THREAD

**Issue by oliversturm** [Microsoft/vscode#36417]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.8.0-59-generic

---

Steps to Reproduce:

1. Run `code -n .` in one folder
2. Run `code -n .` in another folder
3. In either of the two windows, use the Ctrl+Q keyboard shortcut or the File/Exit menu item.

Expected result: one instance closes, the other stays
Actual result: both windows close

I apologize if this should be perceived as a duplicate of [this issue](https://github.com/Microsoft/vscode/issues/48). I read most of the discussion over there and I agree that the default behavior (of reusing the same instance) is irritating. Meanwhile, `code --help` clearly states that `-n` is supposed to *force a new instance of Code* and it obviously does not do that (or alternatively, the File/Exit command ends all running instances? - that would be weird, too.)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
