### ISSUE TITLE
highlighting php in javascript <script> tag bug

### ISSUE THREAD

**Issue by peon501** [Microsoft/vscode#36423]
php coloring in <script></script> tags incorrect

- VSCode Version:newest
- OS Version:win 8.1

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1125765/31668718-a4af532e-b35b-11e7-8e0a-07efa3266004.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you post the code as text and tell me which theme? It looks correct to me in Monokai.

**Comment by peon501** [comment]
Monokai Dimmed

<script>
<?php
	if($test){
		foreach($test as $value){
			echo $value;
		}
	}
?>
	<?php
	if($test){
		foreach($test as $value){
			echo $value;
		}
	}
?>
</script>

**Comment by roblourens** [comment]
Filed https://github.com/atom/language-php/issues/289 for this upstream

**Comment by roblourens** [comment]
Fixed with grammar update.
