### ISSUE TITLE
Git diff peek is not removed when switching to another file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#36424]
@egamma 

1) open the git peek view
2) leave it open and switch to another file
-> the git peek is not dismissed. See below

![image](https://user-images.githubusercontent.com/172399/31615108-db520d1e-b288-11e7-9c0e-91d92fcd5863.png)

**Comment by tonghuashuo** [comment]
- it won't go away if I click on blank area
- some times folding code blocks will pop it up. and refocus cursor.
- can't find any configuration items on turning this feature off.
