### ISSUE TITLE
Autocomplete for string-indexed members even from dot-notation

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#36429]
Sometimes the keys of a map-object are not valid typescript identifiers, yet they are strongly typed members still.  Invoking autocomplete within `['']` does suggest them and, as you know, the string indexer is fully type-checked in such a situation.

Supposing I have members `hello`, `return` and `delete` on an object, can they be suggested in the dot-notation autocomplete as well and then just automatically converted to indexer form since?

```
myObj.            // should offer all members, `hello`, `return` and `delete`
myObj['return']   // choosing `return` replaced the dot-notation with indexed notation and completes the accessor
```

**Comment by mjbvz** [comment]
You should be able invoke autocomplete inside of `['']` using <kbd>ctrl</kbd><kbd>space</kbd>

<img width="276" alt="screen shot 2017-10-19 at 8 14 04 pm" src="https://user-images.githubusercontent.com/12821956/31803701-11a8366c-b50a-11e7-822a-feceefe07dea.png">

We just don't show quick suggestions automatically in this case because you are inside of a string. Does this address the issue?

**Comment by JasonKleban** [comment]
@mjbvz - thanks for the look and the suggestion, but it doesn’t satisfy my interest.  Part of autocomplete’s value is in exploring unfamiliar apis and even needing to know that there are indexed members is a burden - it’s a little more awkward and we have to check both lists.

In my case, I’m generating Rest client code off swagger definitions, organized by route template and http method.  Rather than munging those strings into identifiers and worrying about collisions among them and having the consumer deal with the munged repesentations of the routes, I’m leaving the templates intact:

```
service[‘order/{orderid}’][‘delete’](35552)
```

I really like this except I give up a bit in discoverability.

**Comment by mjbvz** [comment]
I don't think I understand the issue. In your `service`, can you please explain the expected behavior compared to the actual behavior today?

**Comment by JasonKleban** [comment]
A user is not used to typing `['` for member access.

They might explore the api by typing `service.` and get nothing or perhaps some `hasOwnProperty` and `toString` kind of suggestions.  Or depending on the generation, then might get suggestions for identifier-compatible names for completing expressions like `service.orders.get()` and yet not see the others because they are not compatible with the dot-notation.  This is confusing - fixing it would improve the discoverability of such an api.  I can't think of any negative consequences for providing string-indexed suggestions too.

**Comment by mjbvz** [comment]
Ok, so my understanding is:

**Repo**

1. For the code:

```js
const foo = {
    'string': 'abc',
    'spacey string': 'abc'
};

foo.
```

2. Trigger completions after `foo.`

**Expected**
Shows completions for both `string` and `spacey string`. Selecting `spacey string` should complete to:

```js
foo['spacey string']
```

**Current**
Only a completion for `string` is shown:

![screen shot 2017-10-20 at 11 27 01 am](https://user-images.githubusercontent.com/12821956/31836293-a10f18fa-b589-11e7-9dea-ecb14e23cd9e.png)


Is that correct?

**Comment by JasonKleban** [comment]
Yes.  Thanks.

**Comment by mjbvz** [comment]
Fixed on the VSCode side but requires a build of typescript with Microsoft/TypeScript#20547 . Should be in 2.7 final. Once the TS PR is merged you can also pick it up by installing `typescript@next` into your workspace
