### ISSUE TITLE
Autocomplete dropdown width limit makes differentiating long member names impossible

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#36428]
Even in the latest VSCode, the autocomplete dropdown is too narrow to display full member names.  I know this case is pretty specific and looks a little weird, but it is a legitimate case (wrapping and naming rest operations by route template rather than some identifierization of the name):

![image](https://user-images.githubusercontent.com/17498172/31674982-5e9fd86a-b331-11e7-941e-a3fe1258af48.png)

Can it auto-grow or show tooltips or some other thing in the dropdown for long member names?

Thanks!

**Comment by ramya-rao-a** [comment]
Hitting `Ctrl+Space` when the drop down is present shows the docs associated with the suggestions.
Can you try that and see if the full symbol name appears there?

**Comment by hdorgeval** [comment]
Same problem with using strings as type:

![screen shot 2017-11-15 at 00 25 58](https://user-images.githubusercontent.com/9698924/32810522-97351106-c99b-11e7-8704-e7007ef0f9ff.png)
![screen shot 2017-11-15 at 00 27 57](https://user-images.githubusercontent.com/9698924/32810571-e0dcd1a4-c99b-11e7-827d-0f9e531b79a1.png)

**Comment by ramya-rao-a** [comment]
This is being tracked in #29757
