### ISSUE TITLE
Coffeescript syntax highlighting broken after 1.17.0 

### ISSUE THREAD

**Issue by bob-v-t** [Microsoft/vscode#36422]
- VSCode Version: 1.17.0 and Insiders 1.18.0-insider (1.18.0-insider)
- OS Version: macOS 10.12.6 
- Reproduces without extensions: Yes (I used a fresh install of the insiders build to replicate the problem)

Description:

![image](https://user-images.githubusercontent.com/6329322/31668396-631a4580-b352-11e7-9259-f61d0595cdf4.png)

As shown in the image above, the CoffeeScript syntax highlighting broke after the 1.17.0 release; the `FROM table` part and everything after should be interpreted as a string literal.
I know it is ugly code, and funny enough, it also breaks Github syntax highlighting. However, it used to display just fine in 1.16.X and before.

Since there were some syntax highlighting improvements I fear that this might have been broken by accident.

If you copy-paste the code into http://decaffeinate-project.org/repl/ it should display just fine.

Snippet:

``` coffeescript
# Some bogus function definitions to help emphasize the problem
someObject =
    customFunction: (returnVal) -> returnVal
    doQuery: ({sql}) -> console.log sql

# This thing really breaks
timestampReduction = 10
lasttime = "20170902"
someObject.doQuery
    name: "myQueryName"
    sql: """
        SELECT
            #{if someSetting is true then "uid" else (customFunction 'Uid') + " as uid"}
        FROM table
        WHERE TIMESTAMP(lasttime) <= TIMESTAMP('#{lastStamp}')-#{timestampReduction}
    """
```

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/atom/language-coffee-script/issues/158 to track this upstream

Closing as upstream

**Comment by mjbvz** [comment]
Looks fixed upstream. Pulled in update grammar.

<img width="803" alt="screen shot 2017-10-17 at 1 01 05 pm" src="https://user-images.githubusercontent.com/12821956/31686537-45363414-b33b-11e7-81f0-43416e29c2b3.png">


Fix should be fixes in the next insiders build

**Comment by bob-v-t** [comment]
Thanks for the quick action, Matt!
