### ISSUE TITLE
tabCompletion computes too much in `onDidChangeCursorSelection` listener 

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#36427]
* if a selection is multiline, it probably should leave the event listener early. e.g. select all in a 100MB file.
* to set the `hasSnippets` context key, it is needed to only find the first matching snippet (i.e. that there exists a matching snippet) and not to find all the snippets matching the prefix; all the snippets can be computed/filtered at a later stage, when they are really needed.
* `getSnippetsSync` is very slow even after snippets are loaded from disk. The selection is `a` and the language is TypeScript. I don't have any user snippets defined for TypeScript.
* When the setting `editor.tabCompletion` is false (which it is in this case), the cursor selection change listener should not do any computations. like the other listeners: [1](https://github.com/Microsoft/vscode/blob/d5880b1a5948b3bffd40f932dfb63ec8a4be58f9/src/vs/editor/contrib/bracketMatching/common/bracketMatching.ts#L90), [2](https://github.com/Microsoft/vscode/blob/d5880b1a5948b3bffd40f932dfb63ec8a4be58f9/src/vs/editor/contrib/folding/browser/folding.ts#L248) etc.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/5047891/31674944-871cde1e-b363-11e7-9375-726d6d282167.png">

**Comment by alexandrudima** [comment]
Late edit: added the 4th bullet point, that is there should be an early exit in the listener if the feature is turned off via settings.

**Comment by jrieken** [comment]
This is now  ~1ms

**Comment by alexandrudima** [comment]
Nice !
