### ISSUE TITLE
Auto Fixes will sometimes apply the change to a new file instead of the current one.

### ISSUE THREAD

**Issue by Devcon4** [Microsoft/vscode#36425]
Sometimes, but not every time, when I try to use the Import Auto Fix It will open a new tab of the current file and apply the change there. This new tab does not include current unsaved changes, causing you to discard one of the open file changes or use the merge tool to combine them. My use case is when I add a constructor parameter to a Typescript class in an Angular2 project. I am using `eg2.tslint` And `esbenp.prettier-vscode` extensions although trying with extensions disabled also has the problem.
Once this happens your in a bad state. The first tab still doesn't have your auto import, so it still shows the light bulb, and if you import again your changes happen in the opened tab that already has them. Multiple imports will sometimes clobber each other, inserting mid word.

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled

Steps to Reproduce:
This is issue is fairly flaky. The main way it will happen for me is when I add a parameter to a Typescript class and then try to import the type using the Auto Fix light bulb.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
If this happens again, can you please try looking at the full paths of both the original file and the duplicate one. Behavior like this is sometimes caused by casing differences.

To copy the full path, just right click on the file's tab in the tab bar and select the `copy path` menu option

**Comment by Devcon4** [comment]
original: activityTypeDetails\activityTypeDetails.component.ts
opened: ActivityTypeDetails\ActivityTypeDetails.component.ts

Tried it again and it is a casing issue. I renamed this folder/files to be lowercase just the other day. This is also the only file I can consistently get the issue.

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/19329 to track this issue upstream
