### ISSUE TITLE
Getting uri like path for current opened file in the editor

### ISSUE THREAD

**Issue by acrolink** [Microsoft/vscode#36426]
In Windows and using `vscode.window.activeTextEditor.document.uri` I get:

`file://C%3A/Users/User/.vscode/my_scripts/nicify.js`

instead of:

`C:/Users/User/.vscode/my_scripts/nicify.js`

How to fix that?

**Comment by mjbvz** [comment]
Try using `fsPath` on the uri object:  `vscode.window.activeTextEditor.document.uri.fsPath`

**Comment by acrolink** [comment]
`fsPath` works and gives the desired result. May I ask, where is this documented? I mean the `document` and `document.uri` objects and properties?

**Comment by mjbvz** [comment]
These are all documented in the `vscode.d.ts` file. Try running `go to definition` or `go to type definition` on any of the vscode APIs to jump to this file

**Comment by acrolink** [comment]
> Try running go to definition or go to type definition on any of the vscode APIs to jump to this file.

Getting `no definition found for activeTextEditor` etc..

**Comment by mjbvz** [comment]
Can you share some example code? Also, did you run the `postinstall` script to download the vscode typings files: 

```json
    "postinstall": "node ./node_modules/vscode/bin/install"
```

This should have already been done automatically if you used `yo code` to create the extension

**Comment by acrolink** [comment]
I ran the command `npm install --save microsoft/vscode-extension-vscode` inside the extension root folder. Installed fine. But when running `node ./node_modules/vscode/bin/install` I get:

`Error installing vscode.d.ts: Missing VSCode engine declaration in package.json.`

**Comment by mjbvz** [comment]
Yes you also need something like this in your extension's `package.json`:

```json
  "engines": {
    "vscode": "*"
  },
```

Again, `yo code` will handle all of this setup for you

**Comment by acrolink** [comment]
I have just started to code using the `yo code` helper. Side question, is there a way to make VS Code reload the extension automatically after saving/editing the `extension.js` file without the need to restart VS Code or reload the window?

**Comment by mjbvz** [comment]
Not currently. You can create a keybinding for reloading the window though to make this easier though:

```json
{
    "key": "cmd+r",
    "command": "workbench.action.reloadWindow"
}
```

**Comment by acrolink** [comment]
I guess this applies to typescript only. If written in JS, the execution is live or still thee is a need to reload window?

**Comment by acrolink** [comment]
Just to update you on the edit script and execute updated issue. Editing and running scrips updated without window.reload is possible by creating custom scripts within https://github.com/mkloubert/vs-script-commands
