### ISSUE TITLE
Opening additional vscode window has empty workspace

### ISSUE THREAD

**Issue by aviadb** [Microsoft/vscode#36421]
When opening another instance of vscode to have two instances working in parallel each on separate monitor, the new opened window comes up with an empty workspace.
Adding folders to the workspace of the new opened window discard the workspace of the previously window of vscode.

- VSCode Version: 1.18
- OS Version: Win 10

Steps to Reproduce:

1.File->New window
2.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@aviadb 
- Are you adding same folder again in the new window?
- Which command / action are you using to add the folder?

**Comment by aviadb** [comment]
Yes. I want the same workspace on both screens( both opened vscode ).
I am using right mouse click -> Add Folder To Workspace

**Comment by sandy081** [comment]
@aviadb Not sure if I get the issue. Can you please update the description with the steps to reproduce and what are you expecting and what you see.
