### ISSUE TITLE
'Quick Open' doesn't show any node_modules folders -- regression in 1.17.1

### ISSUE THREAD

**Issue by matt-adam** [Microsoft/vscode#36438]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.6.5
json-tools|eri|1.0.2
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
debugger-for-chrome|msj|3.3.1

---

Repro project: [vscode-test.zip](https://github.com/Microsoft/vscode/files/1392020/vscode-test.zip)

Steps to Reproduce:

1. Unzip the attached file, open the resulting vscode-test folder in VS Code.
2. Launch quick-open (Cmd+P)
3. Type in 'find'

I expect quick-open to find the 'Code/node_modules/find_this.js' file, but it doesn't.  This worked in VSCode 1.16, and no longer works in 1.17.1

Some background:  Our project has '/node_modules' for external dependencies, plus a '/Code/node_modules' which contains importable internal code.  Yes I know this is not an ideal structure :)

We have configured .vscode/settings to exclude /node_modules, but include /Code/node_modules for searching and quick-open, as in the attached project.  This worked in 1.16 but no longer works.

I am happy to provide more information, or debug this myself if you point me in the right direction.

Thank you for making VSCode, it's a great product and I enjoy using it!

Reproduces without extensions: Yes

**Comment by matt-adam** [comment]
Ah, one more thing to note -- everything works as expected in the file tree and for searching.  The Quick Open behaviour is harder to understand, it seems to be a mixture of search.exclude and files.exclude, and changing each of them impacts the Quick Open list in unpredictable ways.

**Comment by chrmarti** [comment]
Will check what text search does differently here. From the settings:
```json
{
    "search.exclude": {
        "node_modules": true,
        "Code/node_modules": false,
        "**/node_modules": false
    },

    "files.exclude": {
        "node_modules": true,
        "Code/node_modules": false,
        "**/node_modules": false
    }
}
```

**Comment by chrmarti** [comment]
@roblourens It seems `-g !node_modules` is like `-g !**/node_modules`. Should I just add a `/` when the pattern does not start with `*`? (Same issue occurs with `*.js`.)

**Comment by roblourens** [comment]
Oh yeah, I think you should. Search now resolves those patterns to absolute paths, so it will have the right behavior. But before I was doing that, I was doing a search out of the workspace folder as cwd, and I'm pretty sure I did exactly that, prepend `/` when needed to get the expected behavior.

**Comment by matt-adam** [comment]
Spectacular -- you guys are heroes. Thank you very much!
