### ISSUE TITLE
vscode.workspace.openTextDocument does not open a document

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#36435]
- VSCode Version: 1.17.1
- OS Version: OS X 10.12.6

Steps to Reproduce:

1. Create a new typescript extension using `yo code`
2. Add the following line to the extension.ts file after line 21:
vscode.workspace.openTextDocument();
3. Launch extension debugger with F5.
4. Invoke the 'Hello World' command from the command palette.
Expect:  A new editor pan opens.
Actual: No editor pane opens

Reproduces without extensions: Yes

This fails whether or not I pass options to the `openTextDocument` function.

**Comment by mjbvz** [comment]
This just creates the text document. To show it in UI you then have to call `showTextDocument`:

```ts
vscode.workspace.openTextDocument().then(doc => vscode.window.showTextDocument(doc))
```
