### ISSUE TITLE
Menu item is disabled after git clone

### ISSUE THREAD

**Issue by Xaqron** [Microsoft/vscode#36431]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.19
code-settings-sync|Sha|2.8.3
html-css-class-completion|Zig|1.11.0
html-snippets|abu|0.1.0
vscode-standardjs|che|1.2.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.6.5
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.2.1
code-runner|for|0.7.3
asciidecorator|hel|0.2.0
docthis|joe|0.5.0
sftp|lix|0.8.4
azure-account|ms-|0.1.3
debugger-for-chrome|msj|3.3.1
vscode-code-outline|pat|0.0.11
vscode-versionlens|pfl|0.19.1
LiveServer|rit|2.2.1
vscode-icons|rob|7.15.0
bash-debug|rog|0.1.0
code-spell-checker|str|1.4.10

---

Steps to Reproduce:

1. git clone somerepo
2. let's vscode open the cloned repo

Reproduces without extensions: Yes/No

`File` > `Close Folder` menu is disabled after cloning a repo. Issue resolves after restarting
![screenshot from 2017-10-17 19-49-48](https://user-images.githubusercontent.com/29380705/31676418-6955e6c6-b374-11e7-91a0-33bb6cffa832.png)
 vscode.

**Comment by bpasero** [comment]
@Xaqron can you describe some more exact steps? I cannot reproduce. We update the menu based on the contents of the window that is active.

**Comment by Xaqron** [comment]
@bpasero I have just tried with disabled extensions and same happened. It seems git clone doesn't fire the event that window content is changed. Attached is a short video of how it happens with disabled extensions.
[vscode.mp4.zip](https://github.com/Microsoft/vscode/files/1398749/vscode.mp4.zip)

**Comment by bpasero** [comment]
Looks like on Linux the dynamic updating of enablement for menu items is not working. I pushed a change to always have this action enabled if running on Linux.
