### ISSUE TITLE
Welcome page should be excluded from quick open

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36437]
![image](https://user-images.githubusercontent.com/2193314/31680190-6c52a45a-b328-11e7-81c0-a4d85deedca5.png)

**Comment by chrmarti** [comment]
Which folder(s) do you have open at that time? I don't see that file being picked up.

**Comment by Tyriar** [comment]
@chrmarti this was just https://github.com/Microsoft/vscode-smoketest-express.git, I was in the middle of the smoke test on the quick open step

**Comment by chrmarti** [comment]
Found on Linux while the Welcome page is open.

**Comment by chrmarti** [comment]
Can't reproduce anymore. Can you?
