### ISSUE TITLE
excuse me, can you tell me how to set two or more backgroundImages in my IDE's

### ISSUE THREAD

**Issue by HuRainMan** [Microsoft/vscode#36434]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide more information about this issue. What is the expected behavior? Can you provide a screenshot?

**Comment by atian25** [comment]
sound something like this:  https://marketplace.visualstudio.com/items?itemName=shalldie.background

but this will change vscode to warning, maybe support as config?

**Comment by mjbvz** [comment]
Yes, what that extension does is not officially supported and may break things. The ability to set background images for the editor is tracked by #17219

**Comment by mjbvz** [comment]
Closing as duplicate of #17219
