### ISSUE TITLE
Zen Mode doesn't adapt to Taskbar Setting (autohidden/always show)

### ISSUE THREAD

**Issue by Tetheta** [Microsoft/vscode#36430]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
latex-preview|ajs|0.5.1
project-manager|ale|0.21.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
python|don|0.7.0
scala-lsp|dra|0.2.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|5.6.5
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
vscode-npm|fkn|3.3.0
latex-workshop|Jam|3.5.5
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
indent-rainbow|ode|0.7.2
vscode-jest|Ort|2.4.2
vscode-docker|Pet|0.0.19
vscode-versionlens|pfl|0.19.1
material-icon-theme|PKi|2.2.2
java|red|0.11.0
partial-diff|ryu|0.3.3
jsx|Twe|0.0.1
vscode-java-debug|vsc|0.1.0
vscode-java-pack|vsc|0.1.0
vim|vsc|0.10.1
JavaScriptSnippets|xab|1.5.0
ahalatex|xud|1.0.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Switch taskbar setting from auto-hide to always show
2. Enter Zen Mode in VSCode.
3. Note that sometimes, Zen Mode will stretch underneath the taskbar as if it's being auto hidden. This is especially frustrating when trying to use the integrated console as then I can't see what I'm typing.

Reproduces without extensions: Yes

I have enough issues with the taskbar autohide/always show already I imagine it's not on your end, just the program I have the most trouble with and was hoping you might have insight. 
Should also note I have three different monitors and it only happens on my main one. 
However on the others it replaces the taskbar entirely despite me having always show checked.

**Comment by isidorn** [comment]
This is a chrome full screen bug. File it against chrome please.
The same would happen if you put chrome into full screen

**Comment by stoberov** [comment]
This just happened to me as well.

The (Windows) solution was to open Task Manager (Ctrl + Shift + Esc) > find Windows Explorer > right click & Restart.
