### ISSUE TITLE
What is the default operation when pressing `backspace`?

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#36433]
origin: [vscode-markdown#41](https://github.com/neilsustc/vscode-markdown/issues/41).

In short, we find that `vscode.commands.execute('deleteLeft')` is not equal to the default backspace behavior.

---

- VSCode Version: 1.17.0
- OS Version: Windows/macOs

Steps to Reproduce:

1. Prepare a simple extension (only signs a keybinding on <kbd>backspace</kbd>, see details below)
2. Install [Unikey](http://www.unikey.org/)
3. Open a file using vscode
4. Try to type "Thuwr" and see the result "Thu" (Telex).

Expected result: "Thuwr" --> "Thử"

Reproduces without extensions: No

---

### A Simple Extension

Use `yo code` to create a vscode js extension. Change `package.json`

```json
"contributes": {
    "keybindings":[
        {
            "command": "extension.onBackspaceKey",
            "key": "backspace",
            "when": "editorTextFocus && !editorHasSelection && !suggestWidgetVisible"
        }
    ]
}
```

And `extension.js`

```js
function activate(context) {
    var disposable = vscode.commands.registerCommand('extension.onBackspaceKey', function () {
        vscode.commands.executeCommand('deleteLeft');
    });

    context.subscriptions.push(disposable);
}
exports.activate = activate;
```

### A Tip

After install unikey, click on the tray icon to turn on the Vietnamese keyboard

![image](https://user-images.githubusercontent.com/7588612/31677307-ec0ed474-b39c-11e7-932b-568ab72ea4d5.png)

@MagicPro1994

**Comment by MagicPro1994** [comment]
@neilsustc Vietnamese Keyboard on Windows doesn't support VNI or Telex typing mode (Two most common typing modes for native writer).
