### ISSUE TITLE
Show commands in `Command Palette` based on context (like `when` in KeyBindings)

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#3643]
When you define a `keybinding` in `package.json`, you are able to define `when` the keybinging works. So, for instance, if you define a keybinding like below, it will only work if you are the editor has focus, but not if the focus in TreeView or Find panels, for instance:

``` json
   "when": "editorTextFocus"
```

The same flexibility could be added when you create the command itself (`contributes.commands`), so it should not appear in the `Command Palette`, unless the `when` clause is satisfied.

This could make easier to define commands for the _Workspace/Project_  or _Active Document_.

Thanks in advance

**Comment by bpasero** [comment]
I think we added this a while ago.
