### ISSUE TITLE
Ability to disable jsDoc/tsDoc colors

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#36432]
It would be nice if I could disable the coloring of jsDoc items, and have them render as the default comment color. For me, it makes it harder to read the code vs the comments.

When coloring is disabled the usage of bold italic and regular fonts could help.

Reproduces without extensions: Yes

Maybe there is a setting for this, but I couldn't find it.

**Comment by mjbvz** [comment]
This is something that an extension can change. The easiest way would probably be to inject a custom grammar into the `comment.block.documentation.ts` scope that matches any character.

Closing this as extension candidate.
