### ISSUE TITLE
Updates to workspace settings not available immediately in multi-root workspaces

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#36448]
- VSCode Version: Version 1.18.0-insider **(1.18.0-insider)** 2017-10-17T05:07:33.862Z
- OS Version: OSX Sierra

Steps to Reproduce:

1. Open a multi-root workspace  
2. Ensure settings in both workspace and workspace folders are empty.  
3. Ensure global (user settings) value for ```editor.autoIndent``` is ```true``` (this is the default)  
2. Execute the following code (e.g. code in an extension)  

```typescript
let settings = workspace.getConfiguration('editor');
await settings.update('autoIndent', false, ConfigurationTarget.Workspace);
settings = workspace.getConfiguration('editor');
console.log(settings.autoIndent);
/// Though workspace has been updated the value is still `true`

// Trick, place a delay and the values get loaded
await new Promise(resolve => setInterval(resolve, 2000));
settings = workspace.getConfiguration('editor');
console.log(settings.autoIndent);
/// Now the value is read as `false`
```

Problem: 
- The updates to the configuration settings are not available immediately. 

Expected behaviour:
- Upon awaiting update method, I'd expect to see the updated results when using the method ```workspace.getConfiguration```

**Comment by dlech** [comment]
I noticed the same problem when using a folder-specific configuration, i.e.

    settings = workspace.getConfiguration('editor', resourceUri);

I was manually editing the `.vscode/settings.json` for a workspace folder rather than programatically changing the settings. Additionally, waiting any amount of time still returns a stale value.

**Comment by sandy081** [comment]
@DonJayamanne Good catch. Fixed it.

@dlech Can you please file a new issue for what you are seeing? Steps to reproduce like in this issue's description would be very helpful.

Thanks.

**Comment by dlech** [comment]
I was hoping that the different symptoms had the same root cause. I will open an new issue if the problem persists after this fix.

**Comment by dlech** [comment]
Confirmed that what I was seeing is fixed in 

```
Version 1.18.0-insider
Commit 8deed535e26bc8ceebf83a9aa631580ebd610918
Date 2017-10-30T06:22:40.015Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
