### ISSUE TITLE
Minimap should pick up new colors when changing themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36443]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-35-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
terminal-tabs|Tyr|0.1.1

(1 theme extensions excluded)

---

Repro steps:

1. Open a file
2. Change theme to one with a different background color

![image](https://user-images.githubusercontent.com/2193314/31681618-a59e9328-b32c-11e7-844f-cadd6796ccd9.png)

Closing and reopening files does not fix the issue, I needed a window reload to get the minimap to use the new theme background.

**Comment by alexandrudima** [comment]
@Tyriar AFAIK this code is not platform specific. I have tried to reproduce on OSX and it works as expected. 

![kapture 2017-10-23 at 17 48 13](https://user-images.githubusercontent.com/5047891/31898823-5c470e38-b81a-11e7-9b87-1a98dc5c5e84.gif)

I can also try on linux, but in the meantime, is this something you observe for any theme change or only for specific themes? Are you using `workbench.colorCustomizations` ?

**Comment by alexandrudima** [comment]
**Update**: This also works as expected for me on Linux. I have tried Fedora Linux. Please let me know what further steps you have that can help me reproduce.

**Comment by Tyriar** [comment]
Turns out this happens when I switch between multiple themes packaged in the same extension I can see this (Ubuntu 17.04):

![out](https://user-images.githubusercontent.com/2193314/32136975-88926004-bbcc-11e7-845e-cb19a6b73c54.gif)

Theme: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

**Comment by alexandrudima** [comment]
The following built-in themes are all coming from the same extension, `theme-defaults`:
* light
* light+
* dark
* dark+

This appears to be a problem specific to the Sapphire themes. Would you like me to debug your Sapphire themes ?

**Comment by alexandrudima** [comment]
I can reproduce specifically when switching between Sapphire themes. I have tracked the root cause to

`TextMateService.compareTokenRules` i.e. b5783867f397e7fbba0ce83320b337297797e5ab
