### ISSUE TITLE
Git should better handle error when changing branches with local changes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36441]
Steps:

- Handle local changes not commited
- Try change the branch using the bottom-left status bar branch switcher

![image](https://user-images.githubusercontent.com/2193314/31681460-26564138-b32c-11e7-9357-aaaf421967b6.png)

This is the error in the log:

```
error: The following untracked working tree files would be overwritten by checkout:
	.vscode/launch.json
Please move or remove them before you switch branches.
Aborting
```

It would be good if we either improved the error message to refer to the log for the list, or just list the files ourselves.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
