### ISSUE TITLE
How to open PowerShell Terminal ?

### ISSUE THREAD

**Issue by jsappme** [Microsoft/vscode#36456]
- VSCode Version: Code - Insiders 1.18.0-insider (3495b0b185acbe8188e821ccb3ae807274703a9c, 2017-10-17T04:23:54.942Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.9.11
heroku-command|pko|0.0.8

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by atian25** [comment]
`settings` -> `terminal.integrated.shell.windows`

**Comment by mjbvz** [comment]
Please try looking through the docs for this: https://code.visualstudio.com/docs/editor/integrated-terminal#_windows

**Comment by jsappme** [comment]
there is no way to choose the shell type before opening a new terminal. I had this option before with the insider version but it does not prompt the option anymmore. any idea why?

**Comment by mjbvz** [comment]
@Tyriar will know that

**Comment by Tyriar** [comment]
The first time you launch the terminal on Windows it will ask you your preferred shell, once you make your selection it's saved in your settings.json file. You can also bring up that prompt again by opening the command palette and running the "Terminal: Select Default Shell" command.

If you want to choose on every terminal you open I recommend this extension https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
