### ISSUE TITLE
Link in hover popup isn't working as expected

### ISSUE THREAD

**Issue by AlexeyRaga** [Microsoft/vscode#36452]
- VSCode Version: 1.17.1
- OS Version: Mac OS X Sierra

Since one of the recent updates, VSCode started opening HTML links as tabs with the HTML source instead of opening them in a browser. This beaks some of the use cases. One of them is when a hover popup suggests a link to documentation. See the screenshot demonstrating the bug below.

Steps to Reproduce:

1. Have a custom language provider that adds a link to the hover popup in a form of:
`[Documentation](file://path/to/file.html)`
2. Click on that link
3. VSCode opens the file source in a tab.
4. Expected: link is either opened in a browser or opened in a new tab in "preview" mode.
![links-bug](https://user-images.githubusercontent.com/1394391/31935537-d5a20536-b8fa-11e7-84df-7c4810b6a308.gif)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Actually, after thinking this over more, I believe this behavior is correct for `file:` links. `file:` urls can be used for example to open another file in the project. Special casing `.html` file links to open in a browser does not seem expected. @jrieken, any thoughts on this?

@AlexeyRaga Can you also provide some information about how the hover content is being generated in the first place? Do you have control over this content?

**Comment by AlexeyRaga** [comment]
@mjbvz I see how this breaking change behavior can be justified. I am trying to figure out if there is a workaround for the feature that used to work before this change.

The content is generated by just appending markdown I posted in an issue above. 
You can see the code here: https://github.com/haskell/haskell-ide-engine/blob/master/hie-haddock/Haskell/Ide/HaddockPlugin.hs#L110

We do have control over the content, however, we would like to keep it "frontend-agnostic" (for the lack of a better term): there are other LSP-compliant frontend (Emacs, Atom, etc.) that benefit from this language server.

Saying that, if there is some specific markup we can use to make VSCode open a link in browser, we maybe could parse/substitute it on the VSCode plugin side?
Is there a hook that we can use to adjust the content of the hover?
And what would be the correct markup to make it open file in a browser?

Another acceptable behavior would be to still open the link in VSCode, but in a preview mode (I am not sure if VSCode can do that or not) so the user would be able to read the documentation.

Any thoughts/suggestions?

**Comment by jrieken** [comment]
> @mjbvz I see how this breaking change behavior can be justified.

Not really sure that this was a breaking change. We have always opened `file`-uri in the editor. In what version did you see this working?

> Saying that, if there is some specific markup we can use to make VSCode open a link in browser, we maybe could parse/substitute it on the VSCode plugin side?

Yeah, use can a `http` link

**Comment by AlexeyRaga** [comment]
@jrieken I don't remember the version I used before upgrading. But it definitely worked (I mean links would open in a browser), I use this feature daily.

I don't know any way to have an `http` link to a file on a local file system. Is it even possible?

**Comment by jrieken** [comment]
Well, `http` requires a server so if the resources aren't available online you have to run your own server... Not really recommended. 

An alternative, would to have a custom command that opens a browser for a local file on disk and generate a command link. Use the `MarkdownLink` for that and have a link like so `[Doc](command:myExtension.myCommand?url-encoded-argument)`. Make sure to mark the link as trusted, it will execute the command when clicked

**Comment by AlexeyRaga** [comment]
I can try that, thanks. 
I don't think that I can generate this VSCode-specific link on the LSP server (since it is used not only by VSCode), but if I can hook in LSP-response and transform the link before it is displayed in a popup, that could be a workaround.
Is there anything in the API I can look at for such a hook?

**Comment by jrieken** [comment]
> Is there anything in the API I can look at for such a hook?

I believe that there is support for middleware in the LSP client lib but @dbaeumer will know for sure

**Comment by dbaeumer** [comment]
@AlexeyRaga yes there is: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L398

**Comment by jrieken** [comment]
closing this as question
