### ISSUE TITLE
the terminal always crashes when stop a process by Ctrl+C

### ISSUE THREAD

**Issue by aisakeniudun** [Microsoft/vscode#36454]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
speech|bie|0.0.1
scala|dal|0.0.4
vscode-markdownlint|Dav|0.10.1
vscode-instant-markdown|dba|1.3.0
glslx-vscode|eva|0.0.11
easy-less|mrc|1.4.5
java|red|0.11.0
sass-indented|rob|1.4.4
preview-vscode|sea|1.3.4
shader|sle|1.0.0
shader-toy|ste|0.4.0
ActionScript3|yop|0.0.1

(4 theme extensions excluded)

---

Steps to Reproduce:

1. type `npm start` to start a server process
2. stop the server by `Ctrl+C`

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I'm tracking all ctrl+c on Windows issues in https://github.com/Tyriar/node-pty/issues/7
