### ISSUE TITLE
总是不能使用中文输入法

### ISSUE THREAD

**Issue by Yuloongm** [Microsoft/vscode#36455]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.16
tortoise-svn|fan|0.1.1
php-debug|fel|1.11.1
beautify|Hoo|1.1.1
easy-less|mrc|1.4.5
vetur|oct|0.9.11
ayu|tea|0.8.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by FishOrBear** [comment]
I can not always use Chinese input method  (google translate)

**Comment by yoyo837** [comment]
I do not have this problem, I use Windows built-in Chinese input, which way do you use Chinese input method? @Yuloongm

**Comment by mjbvz** [comment]
@Yuloongm Please provide more information about the issue, such as some steps to reproduce the problem and a description of what is not working correctly

**Comment by mjbvz** [comment]
Closing as not actionable without additional information
