### ISSUE TITLE
trouble with `Debug Console messages show source location` at 1.17

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#36457]
- VSCode Version: 1.17.1
- OS Version: mac

Steps to Reproduce:

1. start a debug session
2. switch to `DEBUG CONSOLE`
3. select log lines, copy
4. unexpected `source location` copy

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Can you also reproduce this with latest insiders https://code.visualstudio.com/insiders/
I can not reproduce the issue you are mentioning, can you paste a sample javascript program for which you can always reproduce this?

**Comment by atian25** [comment]
![untitled](https://user-images.githubusercontent.com/227713/31711112-b9b97e1e-b3bc-11e7-8049-55e80edf8bea.gif)

@isidorn had post a gif. just simple `console.log`

**Comment by isidorn** [comment]
Well that is expected. In you gif notice that index.js gets selected.
For example chrome dev tools also behaves like this.
I understand this is not optimal behavior however there is nothing we can do here sicne this is native html selection + copy.
Closing as designed.
Try using copy all command, it should not copy the source thing
