### ISSUE TITLE
使用的过程中界面就乱了

### ISSUE THREAD

**Issue by shaipe** [Microsoft/vscode#36459]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
vscode-npm-script|eg2|0.2.1
open-in-browser|tec|1.1.0

使用时经常会出现界面就乱了,什么也看不到了

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by yoyo837** [comment]
Hope to provide with more information, such as screenshots. In addition, please use English as much as possible so that more people in the community can participate.
