### ISSUE TITLE
Normal Emmet expansion not working in 1.17.2

### ISSUE THREAD

**Issue by craigs100** [Microsoft/vscode#36450]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1
iis-express|war|1.0.0

Despite Edit|Emmet Expand Abbreviation showing as Tab it cannot be used from the keyboard.
After typing an Emmet abbreviation set I have to type "Ctrl+e x" to expand it.
This is a UI/X failure.

**Comment by craigs100** [comment]
I should mention, the Linux version works just fine and even gives a flyout indicating you're typing an Emmet abbreviation.

**Comment by ramya-rao-a** [comment]
@craigs100 There hasnt been any Emmet related changes between the 1.17.0 and 1.17.2 releases

- Was everything working as expected before upgrading to 1.17.2?
- Did you add/change any emmet related settings?
- In what kind of files do you see this issue? Html, css, jsx?

**Comment by craigs100** [comment]
Normally use VS so just trying out Code.  Turns out Emmet expansion IS working on html files but NOT on cshtml files. Same goes for Linux version. I know even the full VS doesn't handle Razor formatting well so not surprised Code doesn't work with Emmet on Razor files. Pity.

**Comment by ramya-rao-a** [comment]
If you have just started trying out Code, then first of all Welcome!

Give this a read to understand how you can leverage Emmet in VS Code: https://code.visualstudio.com/docs/editor/emmet

You should be able to get Emmet expansion in cshtml files as well. See https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types

Closing this issue for now.

**Comment by craigs100** [comment]
Got it working thanks by adding "razor":"html". Your docs need a link to https://code.visualstudio.com/docs/languages/identifiers

**Comment by ramya-rao-a** [comment]
Thanks for the tip!
I've updated the docs and the changes will be deployed by the end of the day.
