### ISSUE TITLE
打开文件夹的在外部程序调用默认编辑器时文件夹消失

### ISSUE THREAD

**Issue by emCupid** [Microsoft/vscode#36461]
- VSCode Version: Code - Insiders 1.18.0-insider (3495b0b185acbe8188e821ccb3ae807274703a9c, 2017-10-17T04:23:54.942Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2
vscode-great-icons|emm|2.1.16
json-tools|eri|1.0.2
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
sftp|lix|0.8.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
color-highlight|nau|2.3.0
sort-lines|Tyr|1.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Translated as:

> Open folder disappears when external program calls the default editor 

@emCupid Can you please provide more information about the problem. Steps to reproduce the issue and some screenshots would help us understand what is going wrong

**Comment by emCupid** [comment]
http://ww1.sinaimg.cn/large/6fd368d6ly1fkmelae153j20du0aw3yt.jpg
Exit vscode and open a file with vscode
http://ww1.sinaimg.cn/large/6fd368d6ly1fkmelabvctj207x024a9w.jpg
http://ww1.sinaimg.cn/large/6fd368d6ly1fkmelae12ij2073074dfv.jpg

**Comment by mjbvz** [comment]
Thanks you. 

I believe this is by-design. When you use the open in vs code context menu we only open that file, not the entire enclosing folder. This allows you to work with a loose set of files in the editor

Please let me know if I misunderstood the issue

**Comment by emCupid** [comment]
我的意思是：通过上下文菜单打开单个文件不影响原来已经打开的文件夹，这样vs code就可以做为默认文本编辑器又可以做为某个语言的项目编辑器，不然打开单个文件清空已打开的文件夹每次做项目时又得重新打开项目文件夹很麻烦，关键是如果同时有几个项目分别在不同的文件夹下，那就有点累了。

**Comment by mjbvz** [comment]
Files should always open in the current instance unless you set `"window.openFilesInNewWindow": "on"` set. We should also restore the editors when you restart vscode.

For working with files across multiple folders checkout mulitroot support in the insiders builds  https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces
