### ISSUE TITLE
@returns jsdoc info not surfaced in UI

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#36462]
```js
/**
 * @returns Stuff
 */
function foo() {}

foo()
```

The `@returns` description is not surfaced in the UI for completions or hovers

**Comment by LazyKnightX** [comment]
This will help javascript developer feel good while using vscode, vote +1.

**Comment by mjbvz** [comment]
Fixed upstream by typescript@next (TypeScript 2.7):

![screen shot 2017-11-29 at 6 09 36 pm](https://user-images.githubusercontent.com/12821956/33409497-8172ebb8-d530-11e7-8642-4613ccde9e2c.png)

Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use typescript@next
