### ISSUE TITLE
Changelists in VCS

### ISSUE THREAD

**Issue by fourteenmeister** [Microsoft/vscode#36472]
- VSCode Version: 1.17.2
- OS Version: Windows 10

I would like to be able to work with several changelists (like PhpStorm) in VCS.
Is there any plan to implement this feature?

![image](https://user-images.githubusercontent.com/3837141/31709309-34126a2e-b424-11e7-96fa-de8a7c40f8f3.png)

**Comment by joaomoreno** [comment]
What is _VCS_?

**Comment by Ash258** [comment]
@joaomoreno Version control system.

**Comment by joaomoreno** [comment]
Which VCS do you want this for? Git? TFS? Perforce?

**Comment by fourteenmeister** [comment]
I personally use git, but I think for other VCS it is also necessary

**Comment by joaomoreno** [comment]
So, in git terms, what is a changelist?

**Comment by fourteenmeister** [comment]
I'm not so strong in English to explain this. Therefore, I give a link to the documentation of PhpStorm https://www.jetbrains.com/help/phpstorm/changelist.html
