### ISSUE TITLE
Hover info panel background disappear

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode#36479]
![strage-hover](https://user-images.githubusercontent.com/166053/31715425-03279fa6-b42e-11e7-8212-72d444c02c86.gif)

- VSCode Version: Version 1.17.2 (1.17.2
- OS Version: MacOS X Sierra

Steps to Reproduce:

1. Just hover to something that can show a info panel (I'm using vscode-go)
2. This happen when the hovering to the error on the right side (after scroll)

**Comment by mjbvz** [comment]
What theme are you using? Do you have any custom color settings?

**Comment by uudashr** [comment]
Default theme.
My settings:
```json
// Place your settings in this file to overwrite the default settings
{
	"[javascript]": {
        "editor.tabSize": 2
    },
    "terminal.external.osxExec": "iTerm.app",
    "files.insertFinalNewline": true,
    "extensions.autoUpdate": false,
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "workbench.fontAliasing": "antialiased"
}
```

**Comment by alexandrudima** [comment]
Yes, I also see this sometimes.

**Comment by joaomoreno** [comment]
@alexandrudima Can you reproduce?

cc @bpasero @aeschli and all the theme guys... since I didn't touch anything here.

**Comment by alexandrudima** [comment]
@joaomoreno  I see this every now and then since at least 6 months. I could never reproduce reliably so I didn't create an issue for it.

Perhaps @uudashr can give us a bullet-proof repro ?

**Comment by joaomoreno** [comment]
@alexandrudima What theme are you using?

**Comment by alexandrudima** [comment]
@joaomoreno AFAICT It is a layout-related problem, unrelated to themes, font settings or anything else.

reproducible example:
* vscode stable
* `package.json`
```
{
	"publisher": "alex",
	"name": "hover",
	"version": "0.0.0",
	"activationEvents": ["*"],
	"engines": { "vscode": "^1.0.0" },
	"main": "index.js"
}
```
* `index.js`:
```
console.log(`i am alive`);
var vscode = require('vscode');

exports.activate = function() {
	var diags = vscode.languages.createDiagnosticCollection('test');
	var pos1 = new vscode.Position(11, 150);
	var pos2 = new vscode.Position(11, 1000);
	var range = new vscode.Range(pos1, pos2);
	diags.set(vscode.window.activeTextEditor.document.uri, [
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
		new vscode.Diagnostic(range, 'This is just a hover message that is a bit longer than your regular hover message.', vscode.DiagnosticSeverity.Warning),
	]);
} 
```
* have a file which on line 12 has ~400 chars. e.g.:
```
// http://bl.ocks.org/rengel-de/5603464










//  A timeline component for d3  A timeline component for d3  A timeline component for d3  A timeline component for d3  A timeline component for d3  A timeline component for d3  A timeline component for d3A timeline component for d3  A timeline component for d3A timeline component for d3  A timeline component for d3A timeline component for d3  A timeline component for d3
//  version v0.1
```

Now scroll horizontally. At one point (a certain horizontal scroll), the hover background will start to ... disappear:

![36479](https://user-images.githubusercontent.com/5047891/32110984-6d6ab22e-bb39-11e7-860f-a95d5408ae56.gif)

**Comment by joaomoreno** [comment]
Beautiful!

**Comment by cleidigh** [comment]
All
I just saw my issue #30433 closed.  I do not believe I have seen the issue recently, however, I just saw
what is possibly a similar issue with "ghosting" of the hover going into and returning from
running the Run VSC task.  Should I open a separate issue? 

![image](https://user-images.githubusercontent.com/25272315/32643510-eaa98e5c-c5a9-11e7-82f4-b6141d114b71.png)

**Comment by joaomoreno** [comment]
No, it's the same issue.

**Comment by joaomoreno** [comment]
@alexandrudima This code path is never reached:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L475

Thus, the hover widget stays `visibility: hidden`.

Mainly because:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L475

**Comment by alexandrudima** [comment]
@joaomoreno Every time you move your mouse, the widget will disappear and have a position of `null`, which will result in the `topLeft` to be `null`.

With the following diff in `contentWidgets.ts`:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/5047891/33265035-51ef96be-d370-11e7-9c86-2592b8149ecb.png">

I see that `topLeft` is always non-null when the widget is painted:

![kapture 2017-11-27 at 12 43 32](https://user-images.githubusercontent.com/5047891/33265100-9babe3fc-d370-11e7-8535-af18ad1d7d9b.gif)

**Comment by alexandrudima** [comment]
After some pair-debugging, we've deterined the root cause is https://github.com/Microsoft/vscode/commit/a8ad55ace9d241cdde9b1f34933c2f52b1fc4cad
