### ISSUE TITLE
changelog opened when click collapse function/class/etc.

### ISSUE THREAD

**Issue by sqlProvider** [Microsoft/vscode#36470]
- VSCode Version: Version 1.18.0-insider
- OS Version: MacOS Siera 10.12.6 (16G29)

Steps to Reproduce:

1. click collapse button [+]
2. open SCM changelog

Reproduces without extensions: Yes

**Comment by bluemner** [comment]
![capture_bug_vscode](https://user-images.githubusercontent.com/3493458/31728478-0b97862e-b3f2-11e7-8c0f-eeaa0b96ac93.PNG)

- same on window & Linux x64 versions. 
resolution is 1366 x 768

**Comment by sqlProvider** [comment]
is anyone interested?

**Comment by yume-chan** [comment]
Duplicate of #36237

**Comment by mjbvz** [comment]
Thanks @yume-chan! Yes this looks like a duplicate of #36237

Please try out today's VSCode insiders build which I believe contains the fix for this issue
