### ISSUE TITLE
Terminal should not prompt for workspace folder in single folder workspaces

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#36473]
- Insider 1.18
- opened a normal folder
- create a new terminal
- got prompted with the following picker

<img width="532" alt="capture" src="https://user-images.githubusercontent.com/1931590/31710847-80fce658-b3f6-11e7-95b7-8ad7d40dc002.png">

Since I have only one folder open no picker should show up.

**Comment by kieferrm** [comment]
The prompt is disturbing the workflow as it asks me a question to which there is only a single answer. Also, when I choose the folder the keyboard focus afterwards is not in the newly created terminal.
