### ISSUE TITLE
ResourceGlobMatcher is reacting to all configuration change events

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#36478]
ResourceGlobMatcher is listening to configuration changes and reacting to all. I do not see usage of configuration service in it. Not sure if the listener is needed or not.

**Comment by bpasero** [comment]
@sandy081 not sure I understand, the excludes are resolved from the [outside](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/resources.ts#L75) because once `files.exclude` is read and ones `files.exclude` and `search.exclude`.

**Comment by sandy081** [comment]
@bpasero Please check this [listener](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/common/resources.ts#L98).

[updateExcludes](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/common/resources.ts#L102) is being called for all configuration changes.
