### ISSUE TITLE
The uri strings are inconsistent from SetBreakpointsRequest#source.path

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#36471]
- VSCode Version: 1.18.0-insider
- OS Version: Windows 10

When user steps into the third party classes, java debugger would return jdt:// uris in the stack trace response. 
<pre>
[REQUEST]
{"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":28}
[Info  - 4:22:22 PM] Oct 18, 2017 3:32:54 PM 
[[RESPONSE]]
Content-Length: 629

{"success":true,"request_seq":28,"command":"stackTrace","body":{"stackFrames":[{"id":12,"source":{"name":"PrintStream.java","path":"jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class","sourceReference":0},"line":805,"column":0,"name":"PrintStream.println(String)"},{"id":13,"source":{"name":"Step.java","path":"C:\\Work\\CodeJava\\sources\\java-debug-ci\\testcase\\3.thread\\src\\main\\java\\Step.java","sourceReference":0},"line":6,"column":0,"name":"Step.main(String[])"}],"totalFrames":2},"seq":37,"type":"response"}
</pre>

uri from debugger: `jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class`

Then VSCode will find our self-defined JDT Content Provider to render the uri contents. And user can add/remove breakpoints at the jdt editor, and VSCode would persist these breakpoints after the debug session exited. But when the user relaunch the debug session, previous persisted breakpoint's uri from jdt content provider looks to be encoded by VSCode. See the init SetBreakpointsRequests data below.
<pre>
[REQUEST]
{"command":"setBreakpoints","arguments":{"source":{"path":"jdt://contents/rt.jar/java.io/PrintStream.class?%3D3.thread%2FC%3A%5C%2FProgram%20Files%5C%2FJava%5C%2Fjdk1.8.0_131%5C%2Fjre%5C%2Flib%5C%2Frt.jar%3Cjava.io%28PrintStream.class","name":"PrintStream.class"},"lines":[806],"breakpoints":[{"line":806}],"sourceModified":false},"type":"request","seq":5}
</pre>

uri from vscode: `jdt://contents/rt.jar/java.io/PrintStream.class?%3D3.thread%2FC%3A%5C%2FProgram%20Files%5C%2FJava%5C%2Fjdk1.8.0_131%5C%2Fjre%5C%2Flib%5C%2Frt.jar%3Cjava.io%28PrintStream.class`

Continue to run the program, and when the breakpoint at java.io.PrintStream.class#L806 was hit, and the debugger popped up the jdt content provider to render java.io.PrintStream.class. Then add a new breakpoint at PrintStream.class#L807, and observe the SetBreakpointsRequest DA data and found the source uri become the un-encoded version. 
<pre>
[REQUEST]
{"command":"setBreakpoints","arguments":{"source":{"name":"PrintStream.java","path":"jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class","sourceReference":0},"lines":[806,807],"breakpoints":[{"line":806},{"line":807}],"sourceModified":false},"type":"request","seq":21}
</pre>

uri from vscode: `jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class`

The source uris are not consistent between different SetBreakpointsRequest.  We expect the source uri should not be encoded or at least keep it consistent, because we need use the source uri as key to compute the delta of breakpoints in the same source file.

**Comment by isidorn** [comment]
Now we are decoding paths before sending them out to the adapter.
@testforstephen you can try it out in insiders in a coupld of days

@weinand fyi

**Comment by testforstephen** [comment]
@isidorn thanks for the quick response. I review your commit, it can keep the uri path consistent but not sure if `decodeURIComponent(path)` would break the original uri string because the original uri could also contain encoded string by itself.

e.g. `jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class`, 
and 
`jdt://contents/rt.jar/java.io/PrintStream.class?%3D3.thread%2FC%3A%5C%2FProgram%20Files%5C%2FJava%5C%2Fjdk1.8.0_131%5C%2Fjre%5C%2Flib%5C%2Frt.jar%3Cjava.io%28PrintStream.class`

decodeURIComponent will change them to 
`jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:\/Program Files\/Java\/jdk1.8.0_131\/jre\/lib\/rt.jar<java.io(PrintStream.class`

It has little difference with our original version.

**Comment by isidorn** [comment]
@testforstephen you are correct in this. However I am not sure if we can do anything better since vscode encoding uri is a bit our of our control ( it is done automatically by the workbench in this case).
Let's keep it like this in insiders for a couple of days. And we can also consult with @weinand once he is back from vacation.

**Comment by testforstephen** [comment]
@isidorn i found another reason why the uri is not consistent. 
See the source code for this line [L1121](https://github.com/Microsoft/vscode/commit/9c97b8002db556b0e8d2cf1b7df362356e8f585e#diff-4e8f1e1f9a43a95b525cbbe5abc3b2e8R1121) in your commit.
For the persisted breakpoints during the configuration stage, `const source = process.sources.get(modelUri.toString());` is null, so vscode use the `modelUri.toString()` as the uri path.

And if there is a breakpoint hit and debugger sent this uri in it's stack trace response, the subsequent SetBreakpointsRequest from vscode will use the original uri that the debugger provided, and at this time `const source = process.sources.get(modelUri.toString());` will return the cached original uri.

**Comment by isidorn** [comment]
@testforstephen yes that is correct and we are aware of this limmiation. While there is an active debug session we would send the exact source we got from the adapter. While there is none we only store the modelUri which we use as an identifier for sources.

**Comment by testforstephen** [comment]
@isidorn I tried today insider (2017-10-19) which include your commit, and found a serious problem about the decoded uri. Now the uri is always decoded by decodeURIComponent, and it would change the good uri string to an invalid uri format.

e.g. The original uri is `jdt://contents/rt.jar/java.io/PrintStream.class?=3.thread/C:%5C/Program%20Files%5C/Java%5C/jdk1.8.0_131%5C/jre%5C/lib%5C/rt.jar%3Cjava.io(PrintStream.class`, and it's a valid uri string that complied to uri syntax.

`decodeURIComponent` will change it to `jdt://contents/rt.jar/java.io/PrintStream.class?=5.breakpoint/C:\/Program Files\\/Java\/jdk1.8.0_131\/jre\\/lib\/rt.jar<java.io(PrintStream.class`. This new uri conflicts with the uri syntax because the characters (`\`, `<`) in query need to be encoded. See [URI syntax in wiki](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax).

In java, when i tried to parse the new decoded uri string by `java.net.URI`, it also throws `URISyntaxException`. 

Before we get a nice solution about this issue, i suggest to roll back to the old code. For the old code, i have submit a PR on java debugger to handle the inconsistent issue.

**Comment by isidorn** [comment]
@testforstephen i have reverted the "fix". Let me reopen the issue so we can decide what to do.

**Comment by testforstephen** [comment]
sure, thanks.

**Comment by testforstephen** [comment]
I tried the latest version, the source.path in SetBreakpointsRequest is consistent. I will close this issue as fixed.
