### ISSUE TITLE
Possible to install extensions offline?

### ISSUE THREAD

**Issue by phillipj** [Microsoft/vscode#3647]
Hi,

is it possible to install extensions while being offline? At times I don't have direct access to the internet, it would be really great if I could download the extensions beforehand, and install later while offline. I wouldn't mind copying files into specific directories by hand, as long as it gets the job done.

**Comment by joaomoreno** [comment]
Here's a template for the download URL of an extension: 

```
https://${ publisher }.gallery.vsassets.io/_apis/public/gallery/publisher/${ publisher }/extension/${ extension name }/${ version }/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```

For example:

```
https://gerane.gallery.vsassets.io/_apis/public/gallery/publisher/gerane/extension/Theme-azure/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```

You can sideload them by opening the file with Code itself.

**Comment by phillipj** [comment]
Awesome, thanks! :+1:

**Comment by sotnikov-link** [comment]
Use the [simple downloader][1], which is designed for this. You just need to input info about extension and click the button to download.


  [1]: https://sotnikov-link.github.io/get-vscode-extension-for-offline-install

**Comment by phillipj** [comment]
Great tip, thanks 👍
