### ISSUE TITLE
Issues with emmet and editor performance after update 1.17.2

### ISSUE THREAD

**Issue by chiragbhansali** [Microsoft/vscode#36487]
- VSCode Version: 1.17.2
- OS Version: Windows 10

All the problems mentioned below were not there before the update(except point 2)

Problems Faced:

1. Emmet is not working. Error being returned: 'command 'emmet.expandAbbreviation' not found'. 
2. 'Extension host terminated unexpectedly' error being constantly returned
3. Editor is much more slower than it was before the update(before the update, it was a breeze to use)
4. Hints not showing up at all
5. Tab key doesn't work because of point 1
6. Enter key takes a 3-4 seconds to work(not a problem elsewhere)

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
> All the problems mentioned below were not there before the update

@chiragbhansali by "update" are you referring to update from 1.17.0/1.17.1 to 1.17.2 or 1.7 in general?

There was no emmet related changes between 1.17.0 and 1.17.2

Can you see if https://github.com/Microsoft/vscode/issues/36267 covers what you are seeing related to the command not found problem?

Can you try the latest Insiders (you can get it from https://code.visualstudio.com/insiders) and see if you see the same issues?

**Comment by chiragbhansali** [comment]
@ramya-rao-a : Some extensions were causing the problem instead. I have removed them and everything is fine now. Thanks.

**Comment by Right2Drive** [comment]
@chiragbhansali What extensions were causing the issue?

**Comment by chiragbhansali** [comment]
@Right2Drive : 'HTML Snippets' and 'Intellisense for CSS Class Names' were causing issues.
