### ISSUE TITLE
[less] add collapse markers

### ISSUE THREAD

**Issue by mattytommo** [Microsoft/vscode#36483]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Enteprise 64bit

Steps to Reproduce:

1. Open a LESS file
2. Try and collapse regions

Reproduces without extensions: Yes

**Comment by yume-chan** [comment]
You should be able to collapse blocks in less files out of box.

![image](https://user-images.githubusercontent.com/1330321/31764825-f15f5792-b4f4-11e7-887c-5812e55ba63b.png)
![image](https://user-images.githubusercontent.com/1330321/31764849-fed2be78-b4f4-11e7-9066-6020d5b31949.png)
(By default, the collapse marks appears when you hover on the line numbers)

If you are requesting something other, can you share more information about that?

**Comment by mattytommo** [comment]
That's just for blocks themselves though, a region may have 100 of those blocks. In standard Visual Studio you have the ability to incorporate collapsible regions into your files (as you would a C# file), so you may have:

```
/*#region Element Styles*/

html {
}

body {
}

input[type=text] {
}

/*#endregion*/

/*#region Mixins*/

.disable-select {
}

/*#endregion*/

/*#region Generic Classes

.padded {
}

/*#endregion*/
```

It'd be great to have the same collapsible support that we now have in other file types.

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode/commit/20e326771a58f69ba0ffec2a36618b16df68453e
