### ISSUE TITLE
The custom-built PATH shows twice in terminal of vscode.

### ISSUE THREAD

**Issue by newbie1993** [Microsoft/vscode#36481]
# Basic Information # 
VSCode Version: 1.17.2
 OS Version: macOS 10.13

# Steps to Reproduce : #

1.  I'm working in go, so I configured the running environment of go on my mac.
2. I edit `.bash_profile`,  add the statement `export $PATH=$PATH:$(go env GOPATH)/bin`.(`$(go env GOPATH)` equals to `/Users/Mann/go`)
3. In terminal of vscode, it shows `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/Mann/go/bin:/Users/Mann/go/bin` when I excute the command `echo $PATH`.(`/Users/Mann/go/bin` shows twice)
4. But it shows only once on bash of mac.

# Screenshot #
## terminal of vscode: ##
![image](https://user-images.githubusercontent.com/10355814/31717672-7c700c42-b3d2-11e7-9ea5-09b02b3dc5b8.png)

## bash of mac: ##
![image](https://user-images.githubusercontent.com/10355814/31717706-a111c680-b3d2-11e7-9dfa-331844bbe5d4.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/33077
