### ISSUE TITLE
[Feature Request] Sort files in a specific folder by file extensions

### ISSUE THREAD

**Issue by 10manjunath** [Microsoft/vscode#36489]
I'm working on a fairly big project with many languages in it like C++, TCL, Sh, C# etc..

on the left hand side, if i expand a specific folder, all its subfolders/files are displayed below it. However, if i right click, i should be able to sort those files by file extensions or Group by file extensions

Makes it very helpful for developers to review code easier

**Comment by yume-chan** [comment]
There is a global setting: `"explorer.sortOrder": "type"`, to make the explorer sort by file types.

**Comment by 10manjunath** [comment]
This global setting worked. Thank you.
