### ISSUE TITLE
file been deleted after switching to another branch

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/vscode#36480]
- VSCode Version:newest
- OS Version:win7

Steps to Reproduce:

1.  use `webpack-dev-server` to run a web project
2.  switch from one branch to another, again and again
3.  sometimes there will be some files been modified or deleted shown on the `source control` panel

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Please check your setup. I'm sure this will reproduce even if you don't use Code. Simply use a command line to run `git checkout BRANCH` and you'll get the same behaviour.
