### ISSUE TITLE
Flow type imports not autocompleting path...

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#36488]
- VSCode Version: 1.18.0-insider
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Open js file.
2. Attempt flow type import. The path should autocomplete as it does with normal imports, but it is not working.

Fail
![type_file_completion](https://user-images.githubusercontent.com/2549985/31723490-f284afaa-b459-11e7-9cd4-dab0408a0654.gif)

Normal Case
![normal_completion](https://user-images.githubusercontent.com/2549985/31723590-43823170-b45a-11e7-8eb9-7a56d2e75664.gif)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
We don't support flow out of the box. Are you using the flow extension currently?

**Comment by Panoplos** [comment]
This is an import of a file that should not have to depend on the extension to manage simply because of an extra keyword in front, no?

**Comment by mjbvz** [comment]
@Panoplos Do you have a flow extension installed? What is the language mode of the document?

**Comment by Panoplos** [comment]
I have it installed, yes. (Phenomenon happens, with or without). JavaScript language mode.

**Comment by mjbvz** [comment]
In the error case, if you manually trigger intellisense using <kbd>ctrl</kbd><kbd>space</kbd>, do you see the correct suggestions?

**Comment by Panoplos** [comment]
No.

**Comment by mjbvz** [comment]
Do you have a `jsconfig.json` file? Can you share a small description of your project structure

**Comment by Panoplos** [comment]
This should be reproducible with a very minimal setup. Just attempt to import some flow types from one js file in a subdirectory in another tree.

**Comment by mjbvz** [comment]
I cannot reproduce this with a simple setup. Again, please share a small description of your project structure or, even better, post up a minimal repo project

**Comment by Panoplos** [comment]
https://github.com/Panoplos/flow-expand-directory-issue

You can test this by navigating to `src/app/index.js` and trying to complete the directory in line 5.

**Comment by mjbvz** [comment]
Thanks. Yes the root cause is that we do not support flow's `import type`. Please file an issue against the flow extension if you would like to see path intellisense implemented for flow's `import type` as well
