### ISSUE TITLE
Autocomplete emoji on git source control :)

### ISSUE THREAD

**Issue by mauscoelho** [Microsoft/vscode#36484]
It will be awesome if on git source control show an autocomplete for emojis when is typing a commit.

![screen shot 2017-10-18 at 10 27 57](https://user-images.githubusercontent.com/5712300/31718740-bc716d78-b3ef-11e7-8f55-1d02ed26a5c2.png)

Could be like `slack` autocomplete following this [commit-message-emoji](https://github.com/dannyfritz/commit-message-emoji):

<img width="320" alt="screen shot 2017-10-18 at 10 29 24" src="https://user-images.githubusercontent.com/5712300/31718775-d688d91c-b3ef-11e7-94dd-9ec8dc474276.png">

**Comment by yume-chan** [comment]
Related to #36366

Maybe we need plug-able completion provider for the source control message box😄.

**Comment by joaomoreno** [comment]
We support emojis at the OS keyboard level, we don't support `:this_style:` emojis. Closing out of scope, sorry!
