### ISSUE TITLE
Commenting collapsed lines automatically extends them

### ISSUE THREAD

**Issue by AndreiRosu** [Microsoft/vscode#36482]
- VSCode Version: 1.17.2
- OS Version: Win 7 Enterprise 64bit

Steps to Reproduce:

1. Collapse some part of code
2. Comment the collapsed code

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@AndreiRosu Please provide a code sample where this can be reproduced.

**Comment by AndreiRosu** [comment]
![codesample](https://user-images.githubusercontent.com/8149965/31786409-0e775278-b511-11e7-80ca-336c1e9c7dab.gif)
Please notice that I've used "CTRL +  /" to comment the code.

**Comment by aeschli** [comment]
Our folding is indentation based. By adding the comment, this is no longer a folding region as all lines have the same indent.
That would even be the case if we had a language-aware folding and e.g are aware of brackets.Brackets would be ignored when they are commented out.
