### ISSUE TITLE
When debugger stops on a function breakpoint - it is not obvious why the debugger stopped

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#3648]
When I set a function breakpoint and it stops on that "function", it is not obvious that the debugger stopped because of a function breakpoint e.g.:

![vscodefuncbreakpoint](https://cloud.githubusercontent.com/assets/5177512/13472433/1ba45c86-e072-11e5-8a17-977c13bd2e7b.png)

Notice that the "normal" breakpoint above gets a red glyph and a tooltip but where the debugger has stopped does not have any sort of breakpoint glyph or tooltip.

Now I would NOT want VSCode to try to find all the spots in my source where the "function" exists and put a static breakpoint glyph on those spots.  However, when the debugger is stopped on a function breakpoint, I think it would be useful to either A) provide a tooltip indicating the debugger stopped on function breakpoint "`<name of function>`" or B) a **temporary** red breakpoint glyph that goes away as soon as you step off that line (or continue).  Or you could provide both.

This is an example of what this might look like:
![vscodefuncbreakpoint2](https://cloud.githubusercontent.com/assets/5177512/13472911/34d5af00-e074-11e5-94f1-bd86d369240d.png)

**Comment by isidorn** [comment]
First thing to improve is that the adapter should give VSCode 'Function Breakpoint' as the reason for the stop event.The reason is shown next to the CALL STACK, currently it says 'Paused on Breakpoint.

Not a big fan of adding temporary breakopint decorations. So I suggest to start with changing the reason and then see if we get user feedback that it is unclear why vscode stopped. Opinions?

**Comment by rkeithhill** [comment]
I'll give that a try. Hmm, looks like our extension returns reason "paused on breakpoint" all the time.  What are other debuggers returning for `reason` when the user is just stepping through code and not hitting a breakpoint?

**Comment by isidorn** [comment]
'Step', that particular reason we do not show as it is the most common one
Node also returns 'Exception' as a reason.

Let me know after this change if it is still not obvious enough and I will reopen this issue

**Comment by rkeithhill** [comment]
@isidorn Thanks!
