### ISSUE TITLE
Feature request: Click on file path for ES6 imports to open the file

### ISSUE THREAD

**Issue by patik** [Microsoft/vscode#36495]
When I have this:

```js
import foo from 'path/to/file'
```

I'd like to be able to alt-click (or cmd-click) on `path/to/file` and have it open that file. This functionality already seems to exist for `require('path/to/file')`.

**Comment by siegebell** [comment]
I click the filename and press F12 (Go to Definition). Works most of the time.

**Comment by mjbvz** [comment]
yes this should already be supported

@patik Can you please share some info about your project structure? Do you have a `jsconfig.json`?

**Comment by patik** [comment]
It might be my project config (I didn't set it up). We don't have a `jsconfig.json`, but we are using webpack and configured the `base` so that it starts at a particular directory.

So instead of writing:

```
import foo from 'actual/path/to/the/file`
```

we just write:

```
import foo from 'to/the/file`
```

I assume this is why Code can't resolve the path. If so, and webpack configs aren't supported, you can close the issue.

**Comment by mjbvz** [comment]
Yes, that is why intellisense is not working currently. The good news is that you should be able to use a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) project definition to make VSCode understand your webpack importants. Try something like:

```
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": ".",
        "paths": {
            "to/the/file/*": ["actual/path/to/the/file/*"]
      }
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by patik** [comment]
Awesome, thanks!
