### ISSUE TITLE
Feature Request: Default settings.json file for new user profiles

### ISSUE THREAD

**Issue by mjgranstrom** [microsoft/vscode#36499]
Please provide a mechanism for specifying a default settings.json file for new user profiles.

Example:
I'd like to be able to set "update.channel": "none" by default for new users that log on to a shared system. Currently I have to script around this in order to have it set by default. I'd like to see a per-machine copy of the settings.json file somewhere under C:\Program Files\Microsoft VS Code\ that gets copied to %appdata%\Code\User\ at initial launch.

**Comment by sandy081** [comment]
Looks to me a request for overriding configuration defaults
