### ISSUE TITLE
ctrl+alt+arrow keys are not adding multiple cursors

### ISSUE THREAD

**Issue by kirusyaga** [Microsoft/vscode#36493]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-vscode|1.12.1

---

Steps to Reproduce:

1. Open VS Code
2. Open any file
3. Press Ctrl+Alt+Any Arrow Button
4. ?????
5. PROFIT!!!!!111

Reproduces without extensions: Yes

P.S. On Win7 this bug isn't seen. Only on Win8 and Win8.1.

**Comment by alexandrudima** [comment]
@kirusyaga Please check that you don't have any drivers or other software that "steals" those keybindings. I know there are some GPU drivers that steal those keys.

Search online for `ctrl+alt+arrow not working`.

**Comment by kirusyaga** [comment]
@alexandrudima It seems that the Intel Graphics driver is to blame for this.
