### ISSUE TITLE
Source control Git Window not refreshing or updating if git status changes through command line

### ISSUE THREAD

**Issue by kkankala** [Microsoft/vscode#36498]
- VSCode Version: 1.17.2
- OS Version: Win 10(10.1.14393)

Steps to Reproduce:

1. Have your Source control window open
2. Open Terminal in VSCode
3. Using GIT, commit and push through Terminal window.
4. the committed changes are not reflected in Source Control Window.

Expectation: Source Control refreshes and do not show any pending changes.
Actual: Things stay same.

workaround: click refresh and view the updated changes.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Does this reproduce always? Does it work if you <kbd>Alt Tab</kbd> to another window and then <kbd>Alt Tab</kbd> back to Code to give the window focus?

**Comment by kkankala** [comment]
yes, it works on window active of Code. But within code and use code terminal, then it wont.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the terminal?

**Comment by kkankala** [comment]
Im not able to reproduce this lately. I'll open another issue if I ran into it again. sorry for the trouble.
