### ISSUE TITLE
return, delete, spacebar buttons stop working 

### ISSUE THREAD

**Issue by retrogradeMT** [Microsoft/vscode#36506]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.16.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
auto-close-tag|for|0.5.1
vue-snippets|hol|0.1.5
docthis|joe|0.5.0
backspace-plusplus|jri|0.0.16
sublime-keybindings|ms-|2.9.1
vetur|oct|0.9.11
laravel5-snippets|one|1.3.4
blank-line-organizer|rin|0.1.2
highlight-matching-tag|vin|0.4.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I'm not entirely sure, but the buttons seem to stop working after a new file is created using the save as on an existing file. 
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
@retrogradeMT Can you please try disabling all of your extension to see if one of them could be causing this. To do this, start code with the `--disable-extensions` command like flag:

```bash
$ code --disable-extensions .
```
