### ISSUE TITLE
Running Visual Studio Code as guest

### ISSUE THREAD

**Issue by cometta** [Microsoft/vscode#36500]
I would like to request for feature to map Visual Studio Code running in guest Ubuntu OS to map all keyboard Keys to Host running MacOS. So that I can press Command + p in Ubuntu just like when in MacOS. I get confuse when switching between Host and Guest for ctrl+p and Command + p

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
