### ISSUE TITLE
Feature Request - Need a way to define how JS (or any language) code should be formatted

### ISSUE THREAD

**Issue by vpatel-gb** [Microsoft/vscode#36503]
- VSCode Version: Any
- OS Version: Any

Steps to Reproduce:

1. Press `Shift + Alt + F` to format the JS code, it always formats in a specific way defined somewhere. 

It would be good to have a way to define how code should be formatted (like in VS2015)

Reproduces without extensions: Yes

**Comment by kevinrambaud** [comment]
Is Prettier extension (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) not enough ?

**Comment by mjbvz** [comment]
Please see the [documentation](https://code.visualstudio.com/Docs/languages/javascript#_formatting) for the built-in formatter.

For more advanced formatting, try installing a formatting extension from the marketplace
