### ISSUE TITLE
Auto-indent issue after `if` statement with no braces

### ISSUE THREAD

**Issue by logidelic** [Microsoft/vscode#36505]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|1.2.22
mssql|ms-|1.2.0
cpptools|ms-|0.13.1

---

Steps to Reproduce:

1. Edit Javascript or C++ file and place cursor on a line after a braceless `if()`. For example:

![image](https://user-images.githubusercontent.com/18287271/31731281-841ea25c-b402-11e7-9258-959bcc023a6a.png)

2. Press enter. Result:

![image](https://user-images.githubusercontent.com/18287271/31731349-c1dae2fe-b402-11e7-9783-3cccb1a1109d.png)

In the above example, one would hope that the line `do_something_else();` would keep its current (correct) indentation, but instead it gets auto-indented extra.

Actually, this is just one particular example of the more general case: brace-less `if()` statements seem to be generally unsupported by vscode's auto-indent. Is that so?

**Comment by icuurd12b42** [comment]
That has to be error inducing. I had so many bugs with brace-less ifs and loops I personally always use braces now... IMHO brace-less conditionals and loops should go the way of the goto

**Comment by logidelic** [comment]
@icuurd12b42 is this universally accepted to be true? As a C++ (and Javascript) programmer of nearly 20 years, I've come across all sorts of adamant opinions of programming style, but none that have ever become agreed upon as universal truths. Certainly I've come across just as many good programmers that do brace-less ifs as not...

Anyway, is this also the official position of vscode? Are brace-less if's simply not supported because they are considered harmful? What about old code? Not supported?

**Comment by icuurd12b42** [comment]
Nah It's just my opinion. though I'm sure in your 20 years of programming this bit you hard at least once :)

**Comment by logidelic** [comment]
I'll admit, it's making me reconsider seriously.

However, even we say that it's error-prone, this doesn't help with the tons of code out there that use brace-less ifs. As soon as you touch one (even just adding a line after one of these statements, or even moving an existing line), vscode will do its superfluous indent...

**Comment by 0x1c97d5f** [comment]
i hope this is the right issue but here are more examples of braceless if being broken (tested in javascript and c++ with default vscode settings)

```javascript
// pretend CARET is the text cursor

// if you press enter, the new line isn't indented (it should be)
if (x) CARET

// if you paste something, the indentation is removed (it shouldn't be)
if (x)
    CARET

// if you press enter, the new line is indented (it shouldn't be)
if (x)
    return; CARET

// if you...
// - paste something, the line is indented (it shouldn't be)
// - press enter, the new line is indented (it shouldn't be)
if (x)
    return;
CARET
```

it actually behaves the same if you replace `if (x)` with `return;` (or any other statement) so maybe it isn't supported at all?

i noticed even notepad++ gets all of the examples right but it's not vscode

**Comment by rebornix** [comment]
We already removed the indentation rules for non-bracket block so right now the behavior is the same as before, we just inherit the indentation from above line when you press Enter.

@ghost to ensure typing/pasting around both bracket/non-bracket blocks correct, I'll suggest to use formatters which understand AST.

**Comment by logidelic** [comment]
@rebornix "we just inherit the indentation from above line when you press Enter".. That's exactly the problem being described, no?

I see that you resolved this as a duplicate. What's the open issue for this? Thanks much.
