### ISSUE TITLE
Mac: ENOSPC causes currently editing file content to be deleted

### ISSUE THREAD

**Issue by andrewrothman** [Microsoft/vscode#36507]
When I'm working in VS Code and my Mac is running on low storage, I've encountered numerous times VS Code complaining about "ENOSPC" and refusing to save a file, which makes sense to me and is expected behavior. Once I close VS Code, however, I find that it had completely deleted the content of the file I was working on. At this point, the only hope I have is to copy the editor content before exiting VS Code, paste it into vim, and save it before rebooting.

I should mention that I have Auto-save turned on.

Ideally, if a "ENOSPC" error occurs, VS Code should not write out empty file contents.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.19
python|don|0.7.0
azure-account|ms-|0.1.3
cpptools|ms-|0.13.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Live dangerously, and work on a file in VS Code with very low space on your OS X boot drive
2. Edit away until an "ENOSPC" error occurs
3. Close VS Code, ignoring its warning of unsaved changes
4. Open the file you were editing in another text editor, use `cat`, or open it in VS Code again once you have freed up some space. It won't matter. Your code is gone for good.

Reproduces without extensions: Uncertain

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34915
