### ISSUE TITLE
Render Issue - macOS 10.13

### ISSUE THREAD

**Issue by L4r0x** [Microsoft/vscode#36516]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z) - also 1.17/1.17.1
- OS Version: Darwin x64 17.2.0 (macOS 10.13.1 Beta (17B35a))
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.2
java|red|0.12.0
code-spell-checker|str|1.4.10
code-spell-checker-german|str|0.1.2

(2 theme extensions excluded)

---

### Description

Some parts of the window begin to flicker or disappear by hovering over them (see the image below). The application it self doesn't seem be stuck in this moment. Shortcuts and command are working properly. Also writing and saving is no problem, despite that I can't see what I'm writing at this moment. 

It happens often during longer sessions and also sometimes directly after startup. 

In some cases it can be easily by with switching to another application and back, but more often the window has to be reloaded in order to fix this issue. (At least for a short period.)

![vs-code_render-issue](https://user-images.githubusercontent.com/20145354/31742673-9cd5363e-b458-11e7-9f88-cf51951a9e81.png)

Currently I'm trying to figure out if it happens only while using specific extensions. Does someone else has similar issues?

### Steps to Reproduce:

I don't found a good way to reproduce this issue. 

As mentioned earlier, it happens often during longer sessions, but also sometimes directly after startup. 

Reproduces without extensions: No (not quite sure yet)

**Comment by glennray** [comment]
I have uninstalled all extensions and still have the same issue on macOS 10.13.  This did not occur prior to macOS 10.13.

**Comment by kolya182** [comment]
Having the same issue.
![screenshot 2017-10-19 12 23 29](https://user-images.githubusercontent.com/3277207/31790088-2207bb4a-b4c9-11e7-9a14-4ca6181e2f28.png)

**Comment by L4r0x** [comment]
I have disabled most of my extensions, but the issue still occurs. (Updated my post)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35527
