### ISSUE TITLE
Focus is inconsistent opacity in High Contrast theme

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#3651]
<img width="426" alt="screen shot 2016-03-02 at 2 22 51 pm" src="https://cloud.githubusercontent.com/assets/11839736/13477654/4d694258-e082-11e5-8f3d-e80abe812fa5.png">
<img width="426" alt="screen shot 2016-03-02 at 2 23 00 pm" src="https://cloud.githubusercontent.com/assets/11839736/13477658/4ed4e868-e082-11e5-95b7-6f13002af6b4.png">

**Comment by bpasero** [comment]
I am not seeing an issue here.
