### ISSUE TITLE
Windows application icon isn't theme friendly

### ISSUE THREAD

**Issue by johnwargo** [Microsoft/vscode#36510]
VS Code 1.17.0
Icon background doesn't update based on theme. See attached photo

![vs icon](https://user-images.githubusercontent.com/571463/31735303-7e70765c-b40f-11e7-9daf-34368b1dc3c2.png)

**Comment by mattacosta** [comment]
For reference: #33362

**Comment by bpasero** [comment]
Yeah, as designed. We did not want to use the default colors here to prevent this from happening:

![image](https://user-images.githubusercontent.com/900690/31822470-32dfd91c-b5a9-11e7-9e7c-6f918b105e55.png)

**Comment by johnwargo** [comment]
Hmmm, but you could set the background behind the icon and let the remainder of the tile match the theme.  That way it fits with the way Windows works (and most other icons comply with).  On my system, it's only those two VS icons plus Office that don't work with the theme I've selected.
