### ISSUE TITLE
Integrated Terminal: Character Under Cursor Gets Pushed Up

### ISSUE THREAD

**Issue by simonhaenisch** [Microsoft/vscode#36515]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
quokka-vscode|Wal|1.0.72
markdown-checkbox|bie|0.0.3
markdown-emoji|bie|0.0.6
markdown-preview-github-styles|bie|0.1.0
vscode-svgviewer|css|1.4.3
githistory|don|0.2.3
prettier-vscode|esb|0.24.0
git-project-manager|fel|1.4.0
auto-rename-tag|for|0.0.14
graphql-for-vscode|kum|1.6.2
csharp|ms-|1.12.1
sublime-keybindings|ms-|2.9.1
debugger-for-chrome|msj|3.4.0
word-counter|plu|0.0.1
json-template|sto|0.3.1
language-stylus|sys|1.7.3
twig|wha|1.0.2

Reproduces without extensions: Yes

---

User Settings:

```json
{
	"[markdown]": {
		"editor.quickSuggestions": false,
		"editor.rulers": [],
		"editor.wordWrap": "bounded",
		"editor.wordWrapColumn": 80,
		"editor.wrappingIndent": "none",
		"files.trimTrailingWhitespace": false
	},
	"files.associations": {
		".aliases": "shellscript",
		".functions": "shellscript",
		".tern-config": "json"
	},
	"editor.fontSize": 15,
	"editor.insertSpaces": false,
	"editor.minimap.enabled": true,
	"editor.multiCursorModifier": "ctrlCmd",
	"editor.renderControlCharacters": true,
	"editor.renderWhitespace": "boundary",
	"editor.rulers": [120, 80],
	"editor.tabSize": 2,
	"editor.wordWrap": "on",
	"explorer.autoReveal": false,
	"explorer.openEditors.visible": 0,
	"extensions.autoUpdate": true,
	"files.exclude": {
		"**/.DS_Store": true,
		"**/.git": true,
		"**/.gitkeep": true,
		"**/.hg": true,
		"**/.svn": true,
		"**/bin": true,
		"**/CVS": true,
		"**/node_modules": true
	},
	"files.insertFinalNewline": true,
	"files.trimTrailingWhitespace": true,
	"telemetry.enableCrashReporter": false,
	"telemetry.enableTelemetry": false,
	"window.newWindowDimensions": "maximized",
	"window.title": "${activeEditorMedium}${separator}${rootName}",
	"window.zoomLevel": 0,
	"workbench.colorTheme": "Monokai",
	"workbench.commandPalette.history": 0,
	"workbench.commandPalette.preserveInput": true,
	"workbench.editor.openPositioning": "last",
	"workbench.startupEditor": "newUntitledFile",
	"workbench.statusBar.visible": true,
	"prettier.printWidth": 120,
	"prettier.singleQuote": true,
	"prettier.trailingComma": "all",
	"prettier.useTabs": true,
	"markdown.preview.fontSize": 16,
	"debug.inlineValues": true,
	"window.restoreWindows": "all",
	"editor.minimap.showSlider": "always",
	"editor.minimap.renderCharacters": false,
	"editor.wrappingIndent": "indent",
	"editor.colorDecorators": false,
	"editor.formatOnSave": true,
	"javascript.implicitProjectConfig.checkJs": true,
	"npm.runSilent": true,
	"terminal.integrated.lineHeight": 1.2,
	"gitProjectManager.baseProjectsFolders": [
		"~/Projects",
		"~/Work"
	],
	"gitProjectManager.ignoredFolders": ["node_modules"],
	"gitProjectManager.searchInsideProjects": false,
	"auto-rename-tag.activationOnLanguage": ["html", "php", "xml", "jsx", "tsx"],
	"typescript.format.enable": false,
	"javascript.format.enable": false,
	"html.format.enable": false,
	"git.confirmSync": false,
	"window.nativeTabs": true,
	"workbench.editor.enablePreview": false,
	"editor.tabCompletion": true,
	"editor.formatOnPaste": true,
	"editor.wordBasedSuggestions": false
}
```

---

I got an issue on macOS Sierra in the integrated terminal, that the character under the cursor gets pushed up. It only happens since I updated from `1.17.0` to `1.17.1`, How far it gets pushed up depends on the line the cursor is in, and from line six on the currently selected character is invisible.

![screencast](https://user-images.githubusercontent.com/3410759/31699821-9de79468-b421-11e7-9daf-d53cd1a34715.gif)

![image](https://user-images.githubusercontent.com/3410759/31711224-fa04093e-b453-11e7-9c55-48336d398fd5.png)

![image](https://user-images.githubusercontent.com/3410759/31711289-1b17b9c2-b454-11e7-8244-62c3cc72e19c.png)

![image](https://user-images.githubusercontent.com/3410759/31711311-2deda872-b454-11e7-87f3-e2dd8060cb9b.png)

![image](https://user-images.githubusercontent.com/3410759/31711314-33ac5560-b454-11e7-920d-af50440c23ca.png)

![image](https://user-images.githubusercontent.com/3410759/31711367-5b353264-b454-11e7-8fed-17346f72d09d.png)

(originally reported in #35991)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36599
