### ISSUE TITLE
Clicking in margin to toggle collapsible section opens changes window

### ISSUE THREAD

**Issue by bemartin** [Microsoft/vscode#36514]
- VSCode Version: Code - Insiders 1.18.0-insider (1ff751a12b8a1646ac19375126e106a3df4df8cc, 2017-10-18T05:52:05.805Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.10.1
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
xml|Dot|1.9.2
gitlens|eam|5.6.5
tslint|eg2|1.0.11
vsc-material-theme|Equ|1.0.5
beautify|Hoo|1.1.1
docomment|k--|0.0.17
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
team|ms-|1.122.0
vscode-icons|rob|7.15.0
code-settings-sync|Sha|2.8.3
trailing-spaces|sha|0.2.11
ayu|tea|0.8.0

---

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/6611598/31739736-c61261de-b403-11e7-8a8d-d69b7fc5a6b1.png)

2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
#36237
