### ISSUE TITLE
Abnormal Errors

### ISSUE THREAD

**Issue by shemzz** [Microsoft/vscode#36518]
Errors persistently show even when they've been foxed. most times, I have to restart vs code before errors clear; after a while the same behavior occurs.

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.9
EditorConfig|Edi|0.11.0
Angular-BeastCode|Mik|5.0.8
material-icon-theme|PKi|2.2.2
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.11
vscode-angular2-emmet|jak|2.0.3
angular-essentials|joh|0.2.0
Angular2|joh|2.8.0
debugger-for-chrome|msj|3.4.0
angular2-inline|nat|0.0.17
typescript-hero|rbb|1.6.0
vscode-icons|rob|7.15.0
autoimport|ste|1.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What language are you working in? Does this still happen if you disable all of your extensions?

**Comment by shemzz** [comment]
I think it's an extension issue. trying to check which extension has compatibility issues
