### ISSUE TITLE
为什么我的项目跟git无关，我不知道git功能栏的文件是哪里来的。

### ISSUE THREAD

**Issue by IronnMan** [Microsoft/vscode#36519]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:12:42.401Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

- Problem
我在本地创建了一个本地项目文件，源代码管理功能栏却出现很多无关的文件。

**Comment by zigang93** [comment]
不明白你说什么 你是指这个？
![screen shot 2017-10-19 at 10 29 11 am](https://user-images.githubusercontent.com/11520821/31751540-86c4c458-b4b8-11e7-9ccc-5fcda5d2c1b6.png)

**Comment by IronnMan** [comment]
![wechatimg10](https://user-images.githubusercontent.com/22145534/31751719-95e7ef1c-b44c-11e7-955e-fef53331767f.jpeg)
这个红色的出现99+

**Comment by zigang93** [comment]
很明显 你曾经在 ～ git init 过.. 那是mac os 系统文件

这个位置：
![screen shot 2017-10-19 at 10 43 29 am](https://user-images.githubusercontent.com/11520821/31751857-635054b8-b4ba-11e7-9b94-4710957f3785.png)

**Comment by IronnMan** [comment]
对啊！怎么去掉？

**Comment by zigang93** [comment]
在terminal写：
cd ~
rm -rf .git

**Comment by IronnMan** [comment]
完美决解，非常感谢🙏

**Comment by zigang93** [comment]
welcome

**Comment by danyeh** [comment]
Thank you guys for solving the issue.
