### ISSUE TITLE
Format Document Resulting in Error

### ISSUE THREAD

**Issue by hariram1975** [Microsoft/vscode#36513]
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Click on Format Document (Alt+Sht+F)
2.

Reproduces without extensions: Yes/No

**Comment by hariram1975** [comment]
![image](https://user-images.githubusercontent.com/26047377/31739216-3ae98b7e-b41b-11e7-8acc-98331f538b5d.png)

After Click on Format Document, I don't have any editorconfig file as well in my react project.
![image](https://user-images.githubusercontent.com/26047377/31739260-57e852b4-b41b-11e7-983f-580f97ad4b55.png)

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions? To do this, run the `Extensions: Disable all extensions` command in vscode and then restart the editor

**Comment by hariram1975** [comment]
thanks disable HookyQR.beautify fixed the issue

**Comment by mjbvz** [comment]
Thanks for the followup. Closing as caused by extension
