### ISSUE TITLE
method reference when debug python

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#36523]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vsc-material-theme|Equ|1.0.5
Go|luk|0.6.66
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

1. Write a class with public property and method.
2. In another file: create an instance of that class; call one of its method.
3. Actually, it will succeed, and when we are coding, the python plugin provides auto-complete.
4. But in debug mode, we cannot find the reference to that method when we press F12, and only the properties of that class are available.
![python_debug](https://user-images.githubusercontent.com/10704251/31752823-9f2ec5f0-b4bf-11e7-9bdf-16cf133d1ae6.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the python debug extension here https://github.com/DonJayamanne/pythonVSCode
