### ISSUE TITLE
1.17.2 部分js 代码后面加 ;

### ISSUE THREAD

**Issue by pz25925** [Microsoft/vscode#36525]
- VSCode Version: 1.17.2
- OS Version:  windows 10 x64

Steps to Reproduce:

1. 更新 1.17.2 之后,  会自动在部分js 代码后面加 ;  和 eslint 的配置冲突

Reproduces without extensions: Yes/No

**Comment by pz25925** [comment]
看起来像是 vutur 插件造成的.  关闭此 issue

**Comment by mjbvz** [comment]
Closing as caused by Vetur plugin
