### ISSUE TITLE
debug in python class

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#36524]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vsc-material-theme|Equ|1.0.5
Go|luk|0.6.66
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

1. Write a python class with some private properties that start with two leading underscore.
2. When debugging in that python class, no tip or local list for those private properties.
3. Is it possible to add this feature for debugging in python class?
![class_debug](https://user-images.githubusercontent.com/10704251/31753142-7284be54-b4c1-11e7-8911-197a2e15648a.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the python extension here https://github.com/DonJayamanne/pythonVSCode
