### ISSUE TITLE
Bottom console headers look bad on "Insiders" build

### ISSUE THREAD

**Issue by mbarzeev** [Microsoft/vscode#36529]
- VSCode Version: Code - Insiders 1.18.0-insider (7424b934292d9a1fb6e4309ff9547660eab27a80, 2017-10-19T05:11:37.681Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.6.5
LogFileHighlighter|emi|1.2.0
auto-close-tag|for|0.5.1
vscode-todo-parser|min|1.9.1
elm|sbr|0.15.1

---

Steps to Reproduce:

1. Open the console by pressing "Ctrl+~"

See image:
![screen shot 2017-10-19 at 9 55 12](https://user-images.githubusercontent.com/2098439/31758016-4f0943a8-b4b4-11e7-925b-d6f366d101b7.png)

**Comment by iricigor** [comment]
Also text gets trimmed in weird way
![image](https://user-images.githubusercontent.com/15923171/31758413-a54b0a46-b4ad-11e7-8c20-83cc70dfe157.png)

**Comment by Treri** [comment]
same problem

**Comment by sqlProvider** [comment]
+1

**Comment by isidorn** [comment]
Thanks for reporting. There will be a new build in about 30 minutes.

**Comment by yume-chan** [comment]
@isidorn Thanks for your fixing, but things are still not very correct.

The cursor on the `TERMINAL` tab header has became text input mode, and the drop down menus and filter input on the right are too small.

**Comment by isidorn** [comment]
Yeah it is work in progess, thus it is on the insider channel :)
Will get nicer in a couple of days

**Comment by yume-chan** [comment]
@isidorn May we know what will change? Or is there an issue tracking that?

**Comment by isidorn** [comment]
@yume-chan will be fixed probably on friday / monday
