### ISSUE TITLE
Error messages no longer "link" to error in code

### ISSUE THREAD

**Issue by edombrower** [Microsoft/vscode#36521]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. create an error in some server side code.
2. run the code and let the debugger flag the error
3. try to click on the line of code where the error is identified... 
4. nothing happens :( (it used to which is why I keep trying it)

**Comment by isidorn** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34026
