### ISSUE TITLE
Could not install typings files for JavaScript language features. Please ensure that NPM is installed or configure 'typescript.npm' in your user settings

### ISSUE THREAD

**Issue by sharno** [Microsoft/vscode#36520]
- VSCode Version: 1.17.2
- OS Version: macOS 10.12.6

Steps to Reproduce:
1. Load a big JS project
2. open a file inside to edit

Checking the npm path, it's correct and even putting it manually gives the same error

checked the tsserver log, I found those errors:
```

Entry for package 'babel-loader' does not exist in local types registry - skipping...
Entry for package 'babel-polyfill' does not exist in local types registry - skipping...
Entry for package 'babel-preset-es2015' does not exist in local types registry - skipping...
Entry for package 'babel-preset-react' does not exist in local types registry - skipping...
Entry for package 'babel-preset-stage-0' does not exist in local types registry - skipping...
Entry for package 'babel-runtime' does not exist in local types registry - skipping...
Entry for package 'babel-eslint' does not exist in local types registry - skipping...
```

and the other file showed:
```
Info 38   [21:9:43.497] Received response: {"kind":"event::initializationFailed","message":"Command failed: \"/usr/local/bin/npm\" install --ignore-scripts types-registry"}
Info 39   [21:9:43.497] event: {"seq":0,"type":"event","event":"typesInstallerInitializationFailed","body":{"message":"Command failed: \"/usr/local/bin/npm\" install --ignore-scripts types-registry"}}
```
running these commands works from terminal but only after removing the quotations that are escaped

It's worth mentioning that I'm using Fish Shell but it's configured properly (I suppose)

Also this error appears only in this project

Reproduces without extensions: Yes

**Comment by sharno** [comment]
Checked the path in VSCode's developer console and I found that `/usr/local/bin` is present there. Don't know why the command `\"/usr/local/bin/npm\" install --ignore-scripts types-registry`

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19325
