### ISSUE TITLE
My vscode shortcuts often don't work  in  window system

### ISSUE THREAD

**Issue by heibaikn** [Microsoft/vscode#36527]
- VSCode Version:1.172
- window : 10

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Can you please provide more information about this problem. To help us, please include the steps to reproduce this issue, along with a short description of the expected behavior.

**Comment by mjbvz** [comment]
Closing as not actionable without more information
