### ISSUE TITLE
Terminal appearance broken

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#36535]
- VSCode Version: Code - Insiders 1.18.0-insider (7424b934292d9a1fb6e4309ff9547660eab27a80, 2017-10-19T04:24:18.386Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
githistory|don|0.2.3
gitlens|eam|5.6.5
csharp|ms-|1.12.1
vscode-icons|rob|7.15.0
debug|web|0.21.2
omnipascal|Wos|0.15.0

Reproduces without extensions: Yes
![terminalappearancebroken](https://user-images.githubusercontent.com/3448684/31761329-ccb3983c-b4b7-11e7-917d-54e912e545f0.PNG)

Look at the 
  - white areas
  - the way too small drop down field
  - and the incomplete text for Windows Powershell

**Comment by BenoitValdes** [comment]
Already fixed #36529 we have to wait for the next build.

**Comment by Wosi** [comment]
Ah, thanks. Didn't find that issue.
