### ISSUE TITLE
TypeScript intellisense not work for folder appeared in .gitignore

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#36533]
- VSCode Version: 1.18.0-insider
- OS Version: Win10
- TypeScript Version: 2.5.3

Steps to Reproduce:

1. `tsc --init`
1. *File lib/Test.ts*
```ts
export default class Test {
    
}
```
3. add `/lib` to `.gitignore`
4. *File index.ts*
```ts
let a: Test;  // Test cannot get auto import hint here
```

A demo project here:
[https://github.com/k8w/vscode-gitignore-problem-example](https://github.com/k8w/vscode-gitignore-problem-example)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This is unrelated to the gitignore. You need to import `Test` in `index.ts` for this to work. By having the `export` in `Test.ts`, that file will be treated as a module so it will not export globals
