### ISSUE TITLE
1. Touchscreen was not fully supported at pdf viewer mode. 

### ISSUE THREAD

**Issue by albertlixw** [Microsoft/vscode#36530]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.5
language-julia|jul|0.7.0
java|red|0.12.0
shader|sle|1.0.0

1. Touchscreen was not fully supported at pdf viewer mode. 
2. I can only operate with one folder at a time, other files need to be opened individually. This is fine with me but whenever I think about the friendly folder browsing UI on eclipse or Intellij, I miss it. 

Keep it up! :) 👍 

---

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
For 2, please see multiroot workspaces in our VSCode insiders builds: https://code.visualstudio.com/updates/v1_17#_preview-multi-root-workspaces

For the first issue, is the pdf viewer functionality coming from the latex-workshop extension?
