### ISSUE TITLE
Rendering issue in terminal

### ISSUE THREAD

**Issue by teterovic** [Microsoft/vscode#36534]
![image](https://user-images.githubusercontent.com/7413906/31760785-1ee4995a-b4b6-11e7-8344-03bb4b35c7e4.png)

- VSCode Version: Version 1.17.1 (1.17.1)
- OS Version: macOs high Sierra 10.13

Steps to Reproduce:

- Can't reproduce
- opening and closing terminal from view menu - it doesn't help
- Closing VS code and opening it again helps

**Maybe it's klingon :D**

**Comment by gdxn96** [comment]
Got the same issue 
![image](https://user-images.githubusercontent.com/12607360/31767918-f08d0632-b4c4-11e7-9c53-71658074a297.png)

**Comment by Tyriar** [comment]
@teterovic @gdxn96 do you have multiple monitors with varying DPI scales?

**Comment by gdxn96** [comment]
Multiple monitors, scaling on monitor one is 1920x1200 to look like 1440x900, the other has no scaling at 1920x1080

**Comment by teterovic** [comment]
I was using macos split screen. The screen was on an external monitor and
the macbook monitor was active but not used (could be that the screen
switched from macbook to external monitor and back but I didn't noticed it).

ps. Using VS Code for two days since the glitch happened and didn't had the
issue since then. Looks like a rare glitch

**Comment by chapmandu** [comment]
I have the same issue several times per day on macOS High Sierra, with vscode 1.17.2.. I am also using multiple monitors. 

<img width="1271" alt="screen shot 2017-10-24 at 9 37 26 am" src="https://user-images.githubusercontent.com/1092563/31916572-0bdb0988-b89f-11e7-82b5-e190a9320196.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
