### ISSUE TITLE
Why do VSCode couldn't show on my Unbuntu form terminal ?

### ISSUE THREAD

**Issue by MingningShao** [Microsoft/vscode#3653]
Installed vscode as the followed tutorial，
https://code.visualstudio.com/Docs/editor/setup
when i typed code . ,why there nothing happend ?

**Comment by Tyriar** [comment]
Did you replace `/path/to/vscode/Code` with the actual path? Did you get any error at all? If not, can you let me know where you installed it and what exact `ln` command you ran?

**Comment by MingningShao** [comment]
Yeah.
I extracted VSCode-linux-x64.zip to /root/VSCode-linux-x64,and  typed command(BTW,I am a root user.) : ln -s /root/VSCode-linux-x64/Code /usr/local/bin/code.
I also have a question，dose vscode can only run on Ubuntu with desktop ?

**Comment by Tyriar** [comment]
I would expect that to work if you downloaded the stable build from the code.visualstudio.com homepage (the insiders build works a little different). Do you get any output from the program at all, any errors, or just nothing?

You can also try just directly calling `/root/VSCode-linux-x64/Code`, as all /usr/local/bin/code is suppose to be is a symlink to it.

RE your question: Do you mean other Linux distros? It works generally on Debain-based distros, I'm currently going through support on Red Hat now in #3603.

**Comment by stylemistake** [comment]
@MingningShao Root directory has no read permissions for non-root users, means symlink won't work. I suggest to unpack it into `/opt` directory instead.

**Comment by MingningShao** [comment]
I tried, but it didn't work.
The reason why VSCode didn't work, may be i just used xshell.That's just a terminal emulator.
I installed ubuntu on my PC,and download VSCode,finally it worked.
Thanks a lot !@Tyriar @stylemistake

**Comment by Tyriar** [comment]
:+1:
