### ISSUE TITLE
Terminate existing debug session when starting build

### ISSUE THREAD

**Issue by bojunehsu** [Microsoft/vscode#36538]
Oftentimes, after identifying a bug from the Debug session (F5), I fix the code and hit Build (Ctrl+Shift+B).  But because the Debug session is still active, build does not complete by updating the executable.  Since there is no color coding in the Build output, I don't always catch that the build actually failed and I spend a while figuring out why the next Debug session still fails.

It will be great if starting a Build while a Debug session is active triggers a dialog that asks if we would like to terminate the debug sessions.  Having a remember this next time checkout will be even better.

It will be even better if we can prompt the user at the beginning of a Debug session to Build if the code is more up to date than the executable.  I understand that this is difficult with arbitrary build/debug tasks.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
