### ISSUE TITLE
Git status in File Explorer do not work anymore

### ISSUE THREAD

**Issue by BenoitValdes** [Microsoft/vscode#36536]
- VSCode Version: Code - Insiders 1.18.0-insider (7424b934292d9a1fb6e4309ff9547660eab27a80, 2017-10-19T05:11:37.681Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
clarissecomandport|Ben|0.5.0
indenticator|Sir|0.4.2
Bookmarks|ale|0.16.0
project-manager|ale|0.21.1
python|don|0.7.0
cpptools|ms-|0.13.1
live-server-preview|neg|0.0.4
datetime|rid|1.0.5
vscode-icons|rob|7.15.0

(1 theme extensions excluded)

---
Hi,

The Git status in File Explorer #178 feature doesn't work anymore.

Reproduces without extensions: Yes

**Comment by BenoitValdes** [comment]
Everything came back with the new update.
I let you close the issue if you think that's good now.

Thx

**Comment by jrieken** [comment]
Closing should work as advertised, tho it's still some work in progress
