### ISSUE TITLE
TypeScript Definition File Download Error

### ISSUE THREAD

**Issue by lyvius** [Microsoft/vscode#3654]
When I click on the light bulb appearing beside 'XX' keyword in my code, It has the option to download the type definition file XX.d.ts. But, when I click on it, it fails with the following message:

[Info] Unable to fetch d.ts file at https://raw.githubusercontent.com/borisyankov/DefinitelyTyped/master/XX/XX.d.ts: {1}

It appears that this part of the URL has been changed:
borisyankov -> DefinitelyTyped

**Comment by dbaeumer** [comment]
@lyvius which version of VSCode are you on. I suspect this is the old JS support.

**Comment by lyvius** [comment]
I think it is the latest Windows version. I have clicked on "Check for Updates" for many times, right before searching the forums and posting it here, and it says that I'm on the latest version.

**Comment by aeschli** [comment]
Closing as obsolete: We no longer have that quick fix
