### ISSUE TITLE
Add setting to exclude symlinks from search paths

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#36548]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open a project with this structure:
   
   ```
   ./src/one_file.js
   ./srclink -> symlink to ./src
   ```
2. Do a fuzzy search of "onefile".
3. 2 results will appear, one under each folder.

Before, the workaround explained at https://github.com/Microsoft/vscode/issues/36549 could be used, but since its regression, you only can choose among having several or none results, not just one.

The feature proposal here is to add a setting that allows you to exclude symlinked files from searches automatically.

Reproduces without extensions: Yes

**Comment by Yajo** [comment]
Thanks! ❤️

**Comment by bpasero** [comment]
Verified on macOS.
