### ISSUE TITLE
[groovy] provide formatter

### ISSUE THREAD

**Issue by StefH** [Microsoft/vscode#36546]
VSCode Version: 1.18.0-insider
OS Version: Windows 7

Steps to Reproduce:
1. Create a file named **file.groovy**
2. Right click the window --> there is no format file/code option present

**Comment by isidorn** [comment]
This should be handled by the groovy extensions. Please file it aginast that extension

**Comment by StefH** [comment]
@isidorn : Can you please provide the github project for this ? I'm unable to find it.

**Comment by isidorn** [comment]
Actually there seems to be some built in support. Reopeneing and assigning to @aeschli to classify what to do here

**Comment by aeschli** [comment]
We have no plans to provide a groovy formatter. Keeping the issue open for an interested party to take over.
If there's a groovy extension, best is to file the request there.
