### ISSUE TITLE
Auto completion of path for export statements

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#36547]
- VSCode Version: 1.17.2
- OS Version: macOS

Steps to Reproduce:

1. Create a file `test.ts` and put this as content:
   ```ts
   export function testMe(): void { }
   ```
2. Create another file `export-test.ts` and put this as content
   ```ts
   export {} from '' // <- here the auto completion doesn't offer anything!
   ```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/19365 to track this upstream
