### ISSUE TITLE
Prevent multiple setups from running simultaneously

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#36545]
Due to https://github.com/Microsoft/vscode/issues/36244 we are at risk of damaging user's Windows installations next update.

cc @bpasero

**Comment by isidorn** [comment]
Tried installing multiple times in parallel and I always correctly get this dialog

![screen shot 2017-11-03 at 11 48 42](https://user-images.githubusercontent.com/1926584/32370376-16237060-c08d-11e7-921d-563d07e8e51d.png)
