### ISSUE TITLE
vscode change file stat

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Microsoft/vscode#36543]
- VSCode Version:
   1.17.2
- OS Version:
   macos 10.13

Steps to Reproduce:

On macOS 10.13 i use __Samba__ connect __linux__, __vscode open project on linux server__, vscode create file or save file will change file stat.
form
![image](https://user-images.githubusercontent.com/7554917/31763738-cb69880c-b484-11e7-8ef8-4ba6e89380b4.png)
to
![image](https://user-images.githubusercontent.com/7554917/31763753-d9170a4c-b484-11e7-82f9-fb41e7489a15.png)

someting wrong on integrate terminal:
![image](https://user-images.githubusercontent.com/7554917/31763855-2a5e04be-b485-11e7-87de-45002b8a57a8.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/29195
