### ISSUE TITLE
Regression: excluding a symlinked path from search excludes its target

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#36549]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:21:18.489Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open a project with this structure:
   
   ```
   ./.vscode/settings.json
   ./src/one_file.js
   ./srclink -> symlink to ./src
   ```
2. Write this into `settings.json`: `{"search.exclude": {"srclink": true}}`
2. Do a fuzzy search of "onefile".
3. no results will appear. It seems that blacklisting the symlink blacklists its target too. This was not happening in previous releases.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I can't reproduce this. Can you try with the Insiders version? The symlink was just created with `ln -s`?

**Comment by Yajo** [comment]
Yes, just a normal symlink (Linux here).

With insiders version, I have to reload window after applying settings to trigger the bug.

**Comment by roblourens** [comment]
I still can't repro on linux or mac, and it doesn't make sense to me why that would happen. But, I just implemented #36548 and it will be available in the next Insiders. That should work around the issue for you right?

**Comment by Yajo** [comment]
Weird, I can reproduce in many workspaces. In any case, you're right, it should be enough for me. Thanks! 😄

**Comment by roblourens** [comment]
Great! If you wanted to investigate more, this would probably be an issue with our search tool, ripgrep https://github.com/BurntSushi/ripgrep. You could install it and try to repro it with ripgrep alone (using `--follow` and `-g '!...'` to set a glob pattern).
