### ISSUE TITLE
Terminal: text wraps over multiple lines (insiders regression)

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#36541]
- VSCode Version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:29:07.096Z)
- OS Version: Windows_NT x64 10.0.17017
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
gitlens|eam|5.6.5
tslint|eg2|1.0.11
vscode-great-icons|emm|2.1.16
prettier-vscode|esb|0.24.0
docthis|joe|0.5.0
debugger-for-chrome|msj|3.4.0
material-icon-theme|PKi|2.2.2
java|red|0.12.0
ActiveFileInStatusBar|Ros|1.0.3
vscode-hexdump|sle|1.4.0
quokka-vscode|Wal|1.0.72

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Open the integrated terminal

What happens?
Windows version incorrectly spans over three lines

![vscode_terminal_regression](https://user-images.githubusercontent.com/199648/31763126-a56a33e8-b4bd-11e7-89f4-3aa794f0966e.png)

This didn't happen a few days ago and started behaving like this when I updated today morning.

**Comment by Tyriar** [comment]
I saw this today and suspect it's related to https://github.com/Microsoft/vscode/issues/35798
