### ISSUE TITLE
Open dialog shown at 2x size on low DPI external monitor (in Fall Creators Update)

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#36551]
**File -> Open** on an external monitor, using vscode, Windows and a Surface book - all supplied by Microsoft - currently looks like:

![image](https://user-images.githubusercontent.com/172594/31768646-2ba0fafa-b4c8-11e7-89a0-1272f7c1b63d.png)

- VSCode Version: 1.17.2
- OS Version:  10.0.16299.0

Steps to Reproduce:

1. Plug Surface Book into external monitor (with laptop closed)
2. Start VScode
3. Open a file

**Comment by bpasero** [comment]
Nothing we can do about.
