### ISSUE TITLE
Installation error: "Error writing to registry key: ..." (version VSCodeSetup-x64-1.17.2.exe)

### ISSUE THREAD

**Issue by Brampage** [Microsoft/vscode#36558]
- VSCode Version: VSCodeSetup-x64-1.17.2.exe
- OS Version: Windows 10
- I have WSL (Windows Subsystem for Linux) installed

Steps to Reproduce:
1. I pressed "restart and install updates" menu item.
2. Default installation path.
3. I have all "Other:" options selected (it also shows me the error when I deselect all "Other:" options).
4. Everything seems to be fine until the very last part of the progressing bar, it shows me the following error:

```
Error writing to registry key: 
HKEY_CLASSES_ROOT\VSCode.ascx\shell\open\command

RegSetValueEx failed; code 5.

Click retry to do x ignore to do y etc.
```
When I keep clicking ignore (ignore to proceed anyway). I get a lot more errors on registry keys. Eventually I get the following error: 

```
Unable to execute file: 
C:\Program Files\Microsoft VS Code\Code.exe

CreateProcess failed; code 740.
The requested operation requires elevation.
```

**Comment by joaomoreno** [comment]
Can you completely uninstall and reinstall VS Code? Thanks.
