### ISSUE TITLE
Error on configure global encoding utf8

### ISSUE THREAD

**Issue by leandroluk** [Microsoft/vscode#36557]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.15063

---

I program in typescript and need my files to always be in UTF-8 encoding, but when I open a file, vscode sets a random encoding even though I have configured it in the global settings to always open UTF-8 files... please, help us.

**Comment by roblourens** [comment]
Is `"files.autoGuessEncoding"` set? Which encoding does it use?
