### ISSUE TITLE
javascript in .vue not formatting correctly after update

### ISSUE THREAD

**Issue by maple3142** [Microsoft/vscode#36554]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|0.0.2
markdown-checkbox|bie|0.0.3
npm-intellisense|chr|1.3.0
vscode-javascript-snippets|cod|1.0.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
python|don|0.7.0
xml|Dot|1.9.2
EditorConfig|Edi|0.11.0
vscode-npm-script|eg2|0.2.1
vscode-yarn|gam|1.3.0
webpack-snippets|gog|0.0.3
vue-snippets|hol|0.1.5
webpack|jer|2.0.2
csharpfixformat|Leo|0.0.38
cpptools|ms-|0.13.1
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
material-icon-theme|PKi|2.2.2
ejs-language-support|Qas|0.0.1
es6-mocha-snippets|spo|0.0.4
addDocComments|ste|0.0.8
bootstrap4-vscode|the|2.4.0
nativescript-xml-snippets|tsv|1.0.6
vscode-meteor|vuh|0.1.1

---

Steps to Reproduce:

1. Open a .vue file with `<template>` and `<script>`
2. Set indentation to tab and width=4
3. Run command `Format Document`

Reproduces without extensions: No (can't format .vue file without vetur extension)

After formating(2 space):
![](https://i.imgur.com/N5cI17Q.png)

edit: It also add semicolon to my file and change single quote string to double quote string

**Comment by atmar** [comment]
Same issue here, happening since today. Really annoying as I don't use semicolons and I can't format now. Tried a previous vscode version which worked, but after re-opening vscode I have the same issue again. Really strange

**Comment by waqasraz** [comment]
same here

**Comment by mjbvz** [comment]
We don’t provide support for vue out of the box. Can you please file this issue against the vetur extension. This may be https://github.com/vuejs/vetur/issues/476
