### ISSUE TITLE
`editor.formatOnSave` is unreliable

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#36553]
- VSCode Version: 1.17.2
- OS Version: macOS 10.13

Steps to Reproduce:

1. Enable `editor.formatOnSave`
2. Save a file

Reproduces without extensions: Yes/No

This issue is difficult to triage because it only seems to occur randomly, hence I am unable to verify if it still occurs without extensions.

Sometimes the file I'm editing will not be formatted on save. I have to manually run the "format document" command and then save.

I'm wondering if anyone else has seen this behaviour?

I will continue to watch the issue to see if there's any pattern to it.

For context, I am enabling format on save with this project configuration:

``` json
{
    "[javascript]": {
        "editor.formatOnSave": true
    },
    "[javascriptreact]": {
        "editor.formatOnSave": true
    },
    "[typescript]": {
        "editor.formatOnSave": true
    },
    "[typescriptreact]": {
        "editor.formatOnSave": true
    }
}
```

**Comment by mjbvz** [comment]
Are you still running into this issue? Does it happen for other languages as well or just JS and TS?
