### ISSUE TITLE
JavaScript indentation still annoying

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#36550]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.16

This looks like another case of #30933. Type in the following in to a JavaScript file:

```js
foo()
.then(bar =>
```

Then type: `<enter>` `{`

Observed result:

```js
foo()
.then(bar =>
	{
```

Expected result:

```js
foo()
.then(bar =>
{
```

i.e. the open brace should not be indented.

**Comment by rebornix** [comment]
This is another case of our shortage of handling multiple line expressions. Let's track it in https://github.com/Microsoft/vscode/issues/30859.
