### ISSUE TITLE
CONST default values error

### ISSUE THREAD

**Issue by ar53n** [Microsoft/vscode#36559]
- VSCode Version: 1.17.1
- OS Version: Win10

Steps to Reproduce:

1. Typed const values and set values.
2. Link on this variable not show default value

Reproduces without extensions: Yes/No

![vscode](https://user-images.githubusercontent.com/7085102/31773261-dd5a8f78-b4ea-11e7-93a2-ac8313545641.gif)

```javascript 
export const FILES_LOAD: string = '[File] Loading';
export const FILES_SUCCESS: string = '[File] Loading success';
export const FILES_ERROR: string = '[File] Error!';

export class FilesSuccess implements Action {
	readonly type = FILES_SUCCESS;

	constructor(public payload: IFile[]) {}
}

export type Actions = FilesLoad | FilesSuccess | FilesError;

export function reducer(state: State = initialState, action: folder.Actions): State {
	switch (action.type) {

		case folder.FILES_LOAD: {
			return {
				...state,
				loading: true,
			};
		}

		case folder.FILES_SUCCESS: {
			return {
				loaded: true,
				loading: false,
				files: action.payload
			};
		}

		default: {
			return state;
		}
	}
}
```

**Comment by isidorn** [comment]
Please attach a picture or an animated gif to further elaborate on this issue.
Also a small reproducable code sample would be great

**Comment by mjbvz** [comment]
I don't understand the example code. Can you please post a self-contained example and describe what  the expected behavior is
