### ISSUE TITLE
Commenting code in Unsaved files

### ISSUE THREAD

**Issue by mathitech** [Microsoft/vscode#36568]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vs-keybindings|ms-|0.1.7

Adding comments doesn't work if its a new file or the file is not saved.

---

Steps to Reproduce:

1. Open a blank document
2. Type some JSON code
3. Try to add line comment

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Did you change the document's language mode to `json`? Untitled documents start in plain text mode by default

**Comment by mathitech** [comment]
Yes, After changing the document language mode, it works fine. Thanks!
