### ISSUE TITLE
Peek view badges look different than other batches

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#36563]
Version 1.18.0-insider
Commit 4b01451cea60f32412098735709fddcac567b33d
Date 2017-10-19T08:25:22.140Z

![image](https://user-images.githubusercontent.com/6461412/31774663-a364a62c-b4e6-11e7-86ee-e166e111e39a.png)

**Comment by jrieken** [comment]
Yeah, it is a different badge. Tho you are on a very old version as the latest version uses less round badges but more boxy badges as we do in the SCM viewlet

**Comment by aeschli** [comment]
I'm on the latest.

![image](https://user-images.githubusercontent.com/6461412/31877345-6a4023c4-b7d6-11e7-8737-f35c5546721e.png)

**Comment by jrieken** [comment]
So, do you mean the eggs in the peek view? That aren't SCM decorations but the old count badges telling you how many references have been found in a file

**Comment by aeschli** [comment]
Yes, the badges  in the peek view.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/32290151-6ab6b506-bf39-11e7-9004-399d3893c296.png)

They still look a bit different to me though, the one in the search viewlet is much rounder compared to the one in the references widget. Also the size is different, which could have an impact.

**Comment by bpasero** [comment]
Reopening based on my last comment to get confirmation that this is OK. I see the widget is used but maybe some styling is different.
