### ISSUE TITLE
Is it possible to pop out the terminal window?

### ISSUE THREAD

**Issue by Nekochef** [Microsoft/vscode#36565]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.16299

It can't use my ultra wide screen efficiently, if it keeps lying on the bottom. Did I miss something? I think it would be best to manage windows/panels just like Visual Studio.

**Comment by bpasero** [comment]
Currently not but people asked for this already.
