### ISSUE TITLE
Making multiple selections of lines, then performing the action Sort lines ascending or Sort lines descending only works on the first selection

### ISSUE THREAD

**Issue by Markussss** [Microsoft/vscode#36562]
- VSCode Version: Version 1.17.0
- OS Version: Fedora 26, 4.13.5-200.fc26.x86_64

When trying to sort several highlighted blocks of text, using several cursors in one file, only one of the blocks are sorted.

Steps to Reproduce:

1. Create a file with several sections that can be sorted. Exaple:
```
section 1:
a
d
b
c

section 2:
d
c
a
b
```
2. Place cursor on the start of one of the sections, create a new cursor by holding down alt and clicking at the start of the other section.
3. Highlight all four rows of letters in each section by holding Shift, while using the arrow/home/end keys.
4. Press Ctrl+Shift+P and select «Sort Lines Ascending» or «Sort Lines Descending».
5. Result is that only one of the highlighted blocks are sorted. 

Reproduces without extensions: Yes

**Comment by Markussss** [comment]
I have only tested this with up to four different selected blocks. The result is the same every time, but what block is getting sorted depends on where I put the first cursor (the main cursor); the block highlighted by the main cursor is always getting sorted it seems.

**Comment by alexandrudima** [comment]
This would be a good opportunity for a PR. The `SortLinesAscendingAction` and `SortLinesDescendingAction` only operate on the primary selection.

**Comment by MFry** [comment]
Can I take a look at solving this?
