### ISSUE TITLE
Indentation indicator is wrong for travis.yml

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3656]
Our travis.yml uses spaces for indentantion and not tabs, but the status bar shows 4 Tabs:

![image](https://cloud.githubusercontent.com/assets/900690/13486890/5ddfc3e4-e115-11e5-9e9d-851b05772ce5.png)

@isidorn fyi

**Comment by isidorn** [comment]
This is expected with the current behavior of the indentation, we show how the editor is configured, not what is the predominant indentation. Hit an enter on any line and you will see that a tab will be inserted

This will be fixed as a part of https://github.com/Microsoft/vscode/issues/3590 
so I feel like closing this

**Comment by bpasero** [comment]
Fine, I will move the "Important" label.

My reasoning is that the editor status should always show the state of the file you are in. I also show the encoding as it is detected in the status bar even though the workspace setting might be different.

**Comment by isidorn** [comment]
Makes sense to me, we just did not design it like that for the previous release.
This will be fixed as part of #3259, #3590 
Closing

**Comment by joaomoreno** [comment]
FIX IT
