### ISSUE TITLE
Saving file after it has been deleted from disk saves empty file.

### ISSUE THREAD

**Issue by rsmith8614** [Microsoft/vscode#36573]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Change "workbench.editor.closOnFileDelete" to false
2. Create text file with one line in it.
3. Save file, but keep it open in VS Code
4. Delete file from disk (in Windows explorer)
5. File marked as "(deleted from disk)" added to end of file name in VS Code
6. Save file.
7. File is recreated on disk (you see it in Windows explorer)
8. File name in VS Code still says "(deleted from disk)" - Don't think it should anymore
9. If you close the file and re-open the file from disk, the contents are blank.  -Should be whatever was in the file when you saved it.

Also note that if you do a "Save As" for step 6, it doesn't actually create a file on the disk.

Logically, to me, if you save a file that is still open in VS Code after it has been deleted from the disk would create the file again with the contents that are being shown in VS Code.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
nice catch 👍
