### ISSUE TITLE
Test: panel title area

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#36571]
- [x] win @ramya-rao-a 
- [x] mac @mjbvz 
- [x] linux @Tyriar

Complexity: 3

Open the panel and verify in the title area:
* You can move / hide / show panels
* Once there is not enough space in the title area you see nice overflow behavior
* Badges are properly shown in panels
* Panel title view state is preserved across vscode sessions
* Be creative in trying to break it and feedback on how to further improve this UX is appricated

**Comment by ramya-rao-a** [comment]
@isidorn 

> Badges are properly shown in panels

What are badges in the panel context and where do they appear?

**Comment by isidorn** [comment]
@ramya-rao-a sorry about that, no panel has adopted this behavior yet so we currently do not have any badges.
