### ISSUE TITLE
`window.visibleEditors` & `window.onDidChangeVisibleTextEditors` return inconsistent results

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#36579]
- VSCode Version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:29:07.096Z)
- OS Version: Windows_NT x64 10.0.17017
---

Steps to Reproduce:

1. Create (use) a simple extension that subscribes to `window.onDidChangeVisibleTextEditors` or polls `window.visibleTextEditors`
2. Watch/log the editors returned

Normal editors come and go as expected when their visibility changes, but other panels have inconsistent behavior.

- `Problems` & `Terminal` panes never appear in the list regardless of visibility
- `Output` & `Debug Console` panes will appear in the list when they first become visible, but never seem to leave the list regardless of visibility

I'm unsure why the `Output` & `Debug Console` panes ever appear in the list -- I would much prefer they didn't as they aren't really editors. Also if they are to stay in that list it feels like there should be some consistency with the `Problems` & `Terminal` panes as well, and they should certainly IMO be removed from the list when they aren't visible

I feel like this behavior has changed in 1.17, but I can't be sure.

Reproduces without extensions: No

**Comment by eamodio** [comment]
FYI, this is not a `debug` issue (as the "helpful" bot) labeled it

//cc @jrieken

**Comment by jrieken** [comment]
> I feel like this behavior has changed in 1.17, but I can't be sure.

It has been like that since forever

> I'm unsure why the Output & Debug Console panes ever appear in the list -- I would much prefer they didn't as they aren't really editors.

They are implemented as text editor, that's way

**Comment by eamodio** [comment]
Shouldn't they at a minimum respect visibility? It is called `visibleTextEditors`

**Comment by jrieken** [comment]
Yeah, that's a bad name choice...

**Comment by eamodio** [comment]
And all other editors respect visibility to be in that list.

**Comment by eamodio** [comment]
@jrieken Can this be reopened then? Still seems like an issue to me

**Comment by jrieken** [comment]
> Output & Debug Console panes will appear in the list when they first become visible, but never seem to leave the list regardless of visibility

Yeah, they should leave the list eventually...

**Comment by jrieken** [comment]
With @sandy081 recent work on output channels this got already a lot better. It's now just the debug console that stays alive forever and @isidorn might know why that is

**Comment by isidorn** [comment]
I can look into disposing the debug console input once it is hidden
