### ISSUE TITLE
Any way to build premium extensions?

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#36577]
Hi, it could be awesome having a way to publish "premium" extensions with crypted files. @OctoD

**Comment by chrisdias** [comment]
hi - thanks fo the suggestion. we're cleaning up our backlog this milestone and this doesn't meet the criteria for keeping it open - not enough community support and it is unlikely to make our backlog in the next 6-12 months.  thanks for the suggestion though, keep them coming!
