### ISSUE TITLE
git SSH with Putty key can not work

### ISSUE THREAD

**Issue by yoyo837** [Microsoft/vscode#36572]
- VSCode Version: 1.17.2 64bit
- OS Version: Win 10 Fall Creator Updates

[Putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/)

Steps to Reproduce:

I have a remote repository that uses gitlab to deploy git. When using tortoisegit + putty key, it can do the SSH. If you do not use putty key, you can also do HTTP + username and password. When I use SSH clone a repo to local, then open it with VSCode, In the git console panel, it report :

socket: Socket operation on non-socket
ssh: connect to host `git.xxxxx.com`(my gitlab) port 22: Socket operation on non-socket
fatal: Could not read from remote repository.

(google translation)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Does it work from the Command Prompt?

**Comment by yoyo837** [comment]
My company's computer can work fine about this, this is my home computer. Very strange, today found that it can work fine always, I do not know why.
