### ISSUE TITLE
Feature Request: Variable List continues to display values after execution is over given runspace is still live

### ISSUE THREAD

**Issue by Eric2XU** [Microsoft/vscode#36589]
The only thing that keeps me from using VS Code for my daily PowerShell work is the fact it doesnt show variable data when the script isnt running. It seems an obvious oversight. If the runspace is preserved (which it is since I can do $var at the command line and get values) they why wouldnt you display all variables in between runs. Is there a way to hack that in?

**Comment by isidorn** [comment]
Please file this feature request against the powershell extension https://github.com/PowerShell/vscode-powershell
Though this is probably something we wold not support on the vscode side

**Comment by Eric2XU** [comment]
It's so funny you would say that given the fact they told me to file it here as they dont control that panel. Just please know many used to tools like ISE and PowerGUI have this functionality and won't switch until you wake up and realize you need to provide the PowerShell extension the ability to do this. I guess ill cross VS Code off my list for my next PS IDE.
