### ISSUE TITLE
macOS High Sierra - Can no longer drag and drop folder in to explorer panel

### ISSUE THREAD

**Issue by jgclifton** [Microsoft/vscode#36586]
- VSCode Version: 1.17.2
- OS Version: macOs High Sierra - 10.13

Steps to Reproduce:

1. Drag folder to file explorer pane in VS Code

I can't find a duplicate issue - hopefully this isn't just me. Hard to tell whether it has coincided with a VS Code update or the macOs update.

**Comment by bpasero** [comment]
@jgclifton you have to drop it onto the editor area to open
