### ISSUE TITLE
Dynamically modified exports

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/vscode#36587]
- VSCode Version: 1.17.0
- OS Version: Windows 10

I'm using mongoose, which requires a connection to be established first before defining models. I'm assigning the defined models to `module.exports` in an "init" function. I'm trying to get type checking on that module, but I've tried a few different solutions and none of them seem to work.

This is the piece of code I'm using:

```js
// @ts-check

const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  username: String
});

const connect = async () => {
  await mongoose.connect('mongodb://localhost/test');
  
  module.exports.User = mongoose.model('User', userSchema);
};

const model = {
  mongoose,
  connect
};

module.exports = model;
```

First, I tried jsdoc's `@property` tag on the `model` like so:
```js
/**
 * @property {mongoose.Model} User - User model
 */
const model = {
  mongoose,
  connect
};
```

But that didn't work. I also tried a dummy property and setting a type on it:
```js
const model = {
  mongoose,
  connect,
  /**
   * @type {mongoose.Model}
   */
  User: null
};
```

That didn't work either, and I'm getting a "Cannot find namespace 'mongoose'." error when hovering over `mongoose.Model`.

Is there a way to accomplish what I'm trying to do?

**Comment by mjbvz** [comment]
This seems to work if you use an import statement:

```
import mongoose  from 'mongoose'

const model = {
    mongoose,
    connect,
    /**
     * @type {mongoose.Model} User - User model
     */
    User: undefined
};
```

or if you extract the `Model`:

```js
const {Model} = require('mongoose')
```

I believe you are running into this issue: https://github.com/Microsoft/TypeScript/issues/11825

As a workaround, we are consider allowing jsdocs to include module imports for this case. See https://github.com/Microsoft/TypeScript/issues/14377 for more detail

Closing as upstream
