### ISSUE TITLE
The new vs code icon gave my computer cancer

### ISSUE THREAD

**Issue by takahser** [Microsoft/vscode#36581]
The new vs code logo is really not something I'd show my children. On Windows, it looks ugly, but on OS X it's horrible!!

It would be great to have the old one back, so I don't have to be ashamed of using vs code anymore. Thank you.

**Comment by chrisdias** [comment]
The title of this issue is not appropriate.

**Comment by mashiroplanc** [comment]
Try using [Resources Hacker](http://www.angusj.com/resourcehacker/) to change VSCode Icon on Window, I tried it on Sublime 
![image 008](https://user-images.githubusercontent.com/30903885/31791483-dd356ace-b542-11e7-972f-490f106a139c.png)
