### ISSUE TITLE
Support opening and editing extra large binary file

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#36594]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.20
vscode-eclipse-keybindings|alp|0.9.6
Gradle|caz|1.1.2
githistory|don|0.2.3
python|don|0.7.0
vscode-livescript-preview|ehe|1.0.2
azure-account|ms-|0.1.3
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.4.0
createGUID|nwa|0.0.2
livescript|pse|0.1.1
java|red|0.12.0
vscode-hexdump|sle|1.4.0
vscode-proto3|zxh|0.1.2
---

Steps to Reproduce:
I think it's not new bug...
I tried to open an extra large file (above 1GB). There is a hexdump plugin to be able to open binary files.

Why VsCode cannot use buffered reader technic to avoid such a complain that the file is too big?
A reputable editor should know about this.

I'm not sure whether the feature exist or not, but if there is a binary file, why it does not trigger binary file reader if it does exist. (if the binary file format has specific plugin open with that one, but if there is not, than open with a general one)

Many times it's easier to write a hex editor than just find a good one.

**Comment by bpasero** [comment]
Closing as candidate for extensions.
