### ISSUE TITLE
There is no "peekViewResult.foreground" in workbench theme settings. 

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#36598]
- VSCode Version: 1.17.2
- OS Version: macOS Sierra
- [Source Code of the Problem](https://github.com/karyfoundation/kf-theme-vscode/blob/master/themes/kary-dark.json)

Hi everyone. As always thanks a lot for great new features in VS Code.

We [came across a problem within our theme](https://github.com/karyfoundation/kary.themeX/issues/19) that as you can see in active peek view results are being rendered in black.

<img width="1044" alt="screen shot 2017-10-20 at 1 41 34 am" src="https://user-images.githubusercontent.com/2157285/31796922-838b090c-b538-11e7-839a-15b8dd50de3f.png">

I tried all the settings in which I could find and none of them effected this problem. What I found in this search was that, there is a setting for the background of the peek view as

```
"peekViewResult.background": ""
```

But there exists no 

```
"peekViewResult.foreground": ""
```

Can you please implement this setting too? I don't know what setting is effecting this color which makes it a bad thing because it means that it's both hard to find a way to change it and also it's depending on something else so you may want different colors for these two things.

Thanks a lot!

**Comment by moskal91** [comment]
@pmkary I checked how it is done in other theme and found that `"peekViewResult.fileForeground"` does exactly what you want.

**Comment by aeschli** [comment]
Thanks @moskal91, yes that's the solution.
