### ISSUE TITLE
Latest insiders panel titles have white background on all themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36591]
- VSCode Version: Code - Insiders 1.18.0-insider (7424b934292d9a1fb6e4309ff9547660eab27a80, 2017-10-19T05:21:45.915Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.0
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.11
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.1.2
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.10.1

(1 theme extensions excluded)

---

Theme in screenshot: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

![image](https://user-images.githubusercontent.com/2193314/31791224-c7e28d58-b4cc-11e7-8463-64fd4c7a3c16.png)

![image](https://user-images.githubusercontent.com/2193314/31791236-d439263e-b4cc-11e7-84a2-99d99b528425.png)

**Comment by Tyriar** [comment]
Nevermind, this was what the extra build was last night.

@isidorn FYI the released checkbox does not release Linux builds, this needs to be done manually currently.

**Comment by isidorn** [comment]
@Tyriar thanks for releasing them. Do we have this documented somewhere so anybody can release Linux builds when needed. Thanks
