### ISSUE TITLE
Edit multiple selected word is not working as expected

### ISSUE THREAD

**Issue by mashiroplanc** [Microsoft/vscode#36593]
- VSCode Version: 1.17.2
- OS Version: Window 10 Education, Build 15063.674

#### Describe: 
Pressing Ctrl+D then Delete to delete similar word but VSCode only deleted the first selected word and next string after it.

#### Actual behavior:
![1](https://user-images.githubusercontent.com/30903885/31791667-8be57424-b543-11e7-903f-b0d70e7d6381.gif)
#### Expected  behavior:
![2](https://user-images.githubusercontent.com/30903885/31791988-b6a3ebae-b544-11e7-8ffb-acebfaf2858d.gif)

**Comment by mjbvz** [comment]
Hmm, i just tried this in 1.17.2 and saw it working as expected. Does this only happen in python files for you? Does it still happen if you disable all of your extensions?

**Comment by mashiroplanc** [comment]
I tried this again in 1.17.2 after window update and it worked as expected, don't know where it went wrong. perhaps it was window fault.
