### ISSUE TITLE
Keybindings: Add when clause context for sidebar

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#36595]
Currently there is no way to tell if sidebar is visible. You can get the state only for 2/5 viewlets.

Explorer: `explorerViewletVisible`
Search: `searchViewletVisible`
Source Control: `x`
Debug: `x`
Extensions: `x`

Sidebar (any of the above is visible): `x`

**Comment by isidorn** [comment]
PR that fixes this is welcome.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L105

Basicaly the part service would need to add new context key and set it when sidebar gets shown / hidden.
I propose to call this context key `sidebarVisible`.

**Comment by usernamehw** [comment]
Does it actually work?
