### ISSUE TITLE
VSCode lost my work

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#36590]
I don't know what happened exactly, but I had changed some files, saved them, tested them - then did some browsing and when I switched back to VSCode, it lost all my work and reverted the files to a state that they were in *yesterday* (even though I had closed the editor and restarted a fresh instance today).

Now I'm thinking I have to switch editors because I don't trust VSCode anymore. This is the 2nd time I lost work using this editor. After the recent update, I also seem to hit Intellisense "Loading..." and then Intellisense stops working every time I import something new into a file.

I don't expect that I'm giving you any useful information here, but I don't know where else to tell you about this problem. Thanks.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
xml|Dot|1.9.2
EditorConfig|Edi|0.11.0
java|red|0.12.0
vscode-icons|rob|7.15.0
html-preview-vscode|tht|0.1.1
cordova-tools|vsm|1.2.12

---

Steps to Reproduce:

1. I did some work on a create-react-app project and tested it in the browser.
2. After some time, when I switched back to VSCode, my files had been reverted to an earlier state and all my work was lost.

Reproduces without extensions: Yes/No

**Comment by waynebloss** [comment]
Luckily, I'm fanatical about checking in my work as often as possible so I didn't lose much. However, this tool did make me question my sanity momentarily and that is never good.

I might roll back to the August 2017 update in the near future. Anyway, closing this because it's really not that useful to you.

**Comment by bpasero** [comment]
@waynebloss sorry to hear that, if you can find any reproducible steps I would be happy to look into it.
