### ISSUE TITLE
Default "Change Language Mode" shortcut doesn't work

### ISSUE THREAD

**Issue by KayLeung** [Microsoft/vscode#36602]
The shortcut of "Change Language Mode" (ctrl+k m) has the conflict with "ctrl+k". When you press "ctrl+k", it executes "workbench.action.git.input-commit" and show errors, you can't continue to type in "m"

- VSCode Version: 1.17.2
- OS Version:  Windows 10

Steps to Reproduce:

1. Open a file
2. Press "ctrl+k" then "m" ( the default "Change Language Mode" shortcut)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
You probably configured that behaviour in your keybindings file. Please check it.
