### ISSUE TITLE
The problem of encoding confusion when VSCode compiles and runs Java

### ISSUE THREAD

**Issue by xin-6** [Microsoft/vscode#36607]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
java-run|cao|1.1.4
---

Steps to Reproduce:

Here is the error message when I run Java, and it's normal to run in eclipseIDE

```
k:\leson_java\Java14_date.java:7: 错误: 编码GBK的不可映射字符
 * 璧勬枡鍙傝?冿細 http://www.runoob.com/java/java-date-time.html
        ^
k:\leson_java\Java14_date.java:8: 错误: 编码GBK的不可映射字符
 * SimpleDateFormat 鍏佽�镐綘�?夋嫨浠讳綍鐢ㄦ埛鑷�瀹氫箟鏃ユ湡鏃堕棿鏍煎紡鏉ヨ繍琛屻€?
                         ^
k:\leson_java\Java14_date.java:8: 错误: 编码GBK的不可映射字符
 * SimpleDateFormat 鍏佽�镐綘�?夋嫨浠讳綍鐢ㄦ埛鑷�瀹氫箟鏃ユ湡鏃堕棿鏍煎紡鏉ヨ繍琛屻€?
                                                     ^
k:\leson_java\Java14_date.java:13: 错误: 编码GBK的不可映射字符
        // 鍒濆�嬪�? Date 瀵硅薄
               ^
4 个错误
```

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This sounds like an issue with the java-run extension. Can you please file this issue against that extension: https://github.com/NeverCL/vscode-java-run/issues/new
