### ISSUE TITLE
Razor syntax highlighting issue

### ISSUE THREAD

**Issue by dee-see** [Microsoft/vscode#36604]
- VSCode Version: 1.17.2
- OS Version: Arch Linux, kernel 4.13.4-1

Steps to Reproduce:
Single quotes and accents in blocks mess up the colors

![accent](https://user-images.githubusercontent.com/7252342/31801034-61cb16a6-b513-11e7-97b2-8ceaa00b19de.png)

![singlequote](https://user-images.githubusercontent.com/7252342/31801038-63b1dbf8-b513-11e7-9b88-e18521aa82e4.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to demyte/language-cshtml#17
