### ISSUE TITLE
Allow folding in output channels

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/vscode#36609]
- VSCode Version: 1.17
- OS Version: all

Steps to Reproduce:

1. Write some foldable content to an output channel.
2. Folding doesn't work in the output channel.

Reproduces without extensions: Yes

For some reason folding is disabled in output channels -
 https://github.com/Microsoft/vscode/blob/e8f7ac78b782e157ef56c0d16de994bb54443646/src/vs/workbench/parts/output/browser/outputPanel.ts#L84

![screen shot 2017-10-20 at 1 12 32 pm](https://user-images.githubusercontent.com/979966/31803758-e5e1a786-b598-11e7-8082-94b47505fb2f.png)

**Comment by ssbarnea** [comment]
As Output Channel gaines support for highlighting using a language syntax, I wonder if by any chance this also opened the door for allowing collapse? Quite often we see JSON output in these  windows and that takes a huge amount of space if not collapsed by default, making debugging quite hard.
