### ISSUE TITLE
Installing Visual Studio Code on RP3 is failing

### ISSUE THREAD

**Issue by uwence** [Microsoft/vscode#36608]
I'm trying to get Microsoft Visual Studio Code on my Raspberry Pi3 running Raspbian 9 (stretch). I've used these instructions; http://dattabase.com/install-vs-code-raspberry-pi-3/, except that I am using the n node manager and running node v 7.10.1 and npm v4.6.1.

When is run "./scripts/npm.sh install --arch=armhf" it runs for a while, then I get the following errors;

> electron-mksnapshot@1.7.1 install /home/pi/projects/vscode/node_modules/electron-mksnapshot

> node ./download-mksnapshot.js

/home/pi/projects/vscode/node_modules/electron-mksnapshot/download-mksnapshot.js:16

if (error != null) throw error

^

Error: Failed to find Electron v1.7.0 for linux-armhf at https://github.com/electron/electron/releases/download/v1.7.0/mksnapshot-v1.7.0-linux-armhf.zip

at Request. (/home/pi/projects/vscode/node_modules/nugget/index.js:169:61)

at emitOne (events.js:115:13)

at Request.emit (events.js:210:7)

at Request.onRequestResp

**Comment by joaomoreno** [comment]
We don't support ARM yet.

**Comment by brianlinuxing** [comment]
I recently had the same problem.

The previous week I had successfully compiled VS Code on an RPI3, as have many others, eg. https://www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx

Therefore the real questions are:

1. What is the bug?
2. Where does it comes from?
3. What has changed to make it happen?
4. How can we fix it?
