### ISSUE TITLE
SCM viewlet always scrolls to the top and resets size when selecting repo

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#36605]
- VSCode Version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:14:18.042Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.0
vscode-wakatime|Wak|1.1.16
vscode-icontheme-nomo-dark|be5|1.3.3
tslint|eg2|1.0.11
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
java|red|0.12.0
sourcegraph|sou|1.0.9

(1 theme extensions excluded)

---
Steps to Reproduce:

1. Add >5 root folders to workspace
2. Select one that is lower down
3. Notice how list always scrolls up
4. Resize list
5. Select one any repo
6. Notice how the size is reset

![2017-10-19 6 27 24 pm](https://user-images.githubusercontent.com/10532611/31801235-8684509c-b4fb-11e7-8515-4b36e327ca5b.gif)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Good catch!
