### ISSUE TITLE
Autocompletion should not autocomplete parentheses on import clause

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#3660]
I have the settings 

``` json
"typescript.useCodeSnippetsOnMethodSuggest": true,
```

It current autocompletes on import clauses too. Which is not desired.

``` ts
import { setRoutes(app)} from './Routes/Index';
```

**Comment by tinganho** [comment]
I also find autocompletion of call expression to be strange when handling of overloads. It seems like it choose the wrong ones for me all the times. Maybe overloads should only be autocompleted with the least arguments?

**Comment by tinganho** [comment]
It would be also awesome if it could autocomplete the arguments. If it finds assignable variables in scope and there exists only one assignable variable it should autocomplete it as an argument in a call expression.

```ts
function f(a: string) {
}

let b: string;
f(b) // autocompleted with b as an argument.
```

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/2092
