### ISSUE TITLE
Lag in git left-side indicators update

### ISSUE THREAD

**Issue by Faultless** [Microsoft/vscode#36619]
- VSCode Version: Code - Insiders 1.18.0-insider (3495b0b185acbe8188e821ccb3ae807274703a9c, 2017-10-17T04:23:54.942Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.2
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.2.1
prettier-vscode|esb|0.24.0
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
vscode-npm|fkn|3.3.0
flow-for-vscode|flo|0.7.2
vscode-rust|kal|0.4.2
graphql-for-vscode|kum|1.6.2
azure-account|ms-|0.1.3
PowerShell|ms-|1.4.3
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
material-icon-theme|PKi|2.2.2
markdown-preview-enhanced|shd|0.2.9
wordpress-snippet|tun|1.1.2
vscode-import-cost|wix|2.5.0
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|0.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a git repository.
2. Multiline edit a file.
3. There is some inconsistency with the left side git changes indicator near the line number (doesn't always update right away).

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
That is for performance.
