### ISSUE TITLE
function or class or class member search slowly and cannot get what I want.

### ISSUE THREAD

**Issue by qidianbuji** [Microsoft/vscode#36613]
1. The problem is: when I try to search a class definition, I use the "ctrl+shift+f" global symbol search, and after I type in the name, the search result windows show me the  some thing like symbols. In other word, it use the symbols like search, not syntax. Off course, when I type in with the space name, failed search definitely.
2. another problem is, when open one file, I want to have one symbol info outline only about this file.
3. all what I want is can you provide a better version which just like the source insight tool? support syntax search for function, class or macro name on all the solution project, and provide symbol-match search all round solutions?
If so, I think, vscode will be the most popular develop platform, more than source insight, than linux-vim, than xcode, than eclipse...   Thank you very much.

**Comment by roblourens** [comment]
1. Can you explain some more? ctrl+shift+f searches for text. I don't understand what you're asking for.
2. Does ctrl+shift+o do what you're asking for?
3. Also don't understand what you're asking for here. Does ctrl+t (global symbol search) help?

**Comment by qidianbuji** [comment]
Thank you very very much, maybe I have missed something. all functions I need are ok now.
now, can you think about providing some window about these features? WE use visual studio too long, maybe dont

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by qidianbuji** [comment]
(sorry above from mobile phone editor)
Thank you very very much, maybe I have missed something. all what I need about search are ok now.
But here I have 2 problems need your help:
1. can you help provide some window view about these features? We use visual studio too long, and like such develop tool so much that maybe are not used to command-line search. (really the ctrl+shift+cmd is not a good experience)
2. How can I build and debug C++ project remotely on linux-board while vscode installed on win7? Because most time I develop on linux, but use Win7 xshell to connect to.
Thank you again~

**Comment by roblourens** [comment]
1. Sorry, I don't understand what you mean here by "command-line search", what are you referring to?
2. I'm not sure. You can use vscode on Linux if that helps :) or you could ask on the C++ extension repo.

**Comment by qidianbuji** [comment]
build and debug on remote Linux platform. and the debug window showed on windows which vscode installed on.
like visual studio 2015/2017... can creat Linux project and build and debug it remotely on Linux board.
do you understand what I mean?

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roblourens** [comment]
I understand that part but I don't know how to do it. It will involve the C++ extension so you may be able to find some documentation or help by searching over there https://github.com/Microsoft/vscode-cpptools
