### ISSUE TITLE
open c file can not find symbol

### ISSUE THREAD

**Issue by michaelllh** [Microsoft/vscode#36616]
- VSCode Version: 1.17.2
- OS Version:win7

Steps to Reproduce:

1.open a c source file
2.ctrl+T to find all symbol is none.(ctrl+shift+o find symbol in this file is also none)

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
We do not provide builtin intellisense for C. Please try installing an extension such as [this one](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
