### ISSUE TITLE
Insider 1.18: sidebar on right side displays icons with text overlay

### ISSUE THREAD

**Issue by iricigor** [Microsoft/vscode#36618]
- VSCode Version: Insiders 1.18
- OS Version: Windows 10

Steps to Reproduce:

1. Open user settings and add "workbench.sideBar.location": "right"
2. Check sidebar icons (see screenshot below), icons will have some text over them

Reproduces without extensions: Yes

Here are screenshot from extensions icon on different themes. Notice letters (most probably) "t e n" over it. It is similar with other icons
![image](https://user-images.githubusercontent.com/15923171/31808601-35e2e6ca-b574-11e7-8408-383845ca1a41.png) ![image](https://user-images.githubusercontent.com/15923171/31808678-86e13450-b574-11e7-931e-632cb288bae9.png) ![image](https://user-images.githubusercontent.com/15923171/31808716-aebd0422-b574-11e7-9b9d-d8cf328051c3.png)

**Comment by isidorn** [comment]
@iricigor great catch, thanks a lot
