### ISSUE TITLE
Global packages not detected

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#36615]
- VSCode Version: 1.17.1
- OS Version: Ubuntu 16.04
Reproduces without extensions: Yes

This issue is also posted on:
[https://stackoverflow.com/questions/46762461/how-to-use-global-node-packages-with-vs-code](https://stackoverflow.com/questions/46762461/how-to-use-global-node-packages-with-vs-code)

If Node.js packages are globally installed, they can be used by Node.js applications. But *vscode* will not accept these packages and indicate an error, as long as these packages are not installed locally in the project directory (inside the subdirectory *node_modules*). 

For example:

    import * as net from 'net';

... `'net'` is marked with a red underline as long as you do not install `npm install --save @types/node`. If you install that package globally via `npm -g install @types/node`, the package would be available, but *vscode* will not recognize it.

So my question, is this a bug or is there some way to configure *vscode* to recognize global installed Node.js packages?

**Comment by mjbvz** [comment]
Answered on SO: https://stackoverflow.com/a/46943302/306149
