### ISSUE TITLE
Find in Files is failure

### ISSUE THREAD

**Issue by goooxu** [Microsoft/vscode#36620]
- VSCode Version: 1.17.2 (x64)
- OS Version: Version 1709 (OS Build 16299.19)

Steps to Reproduce:

1. cd **D:\OneDrive - Microsoft\Code\OpenMindVSCode**
2. code .
3. Ctrl+Shift+F open Find in Files dialog
4. search anything will be failure (nothing found), except opened documents

Reproduces without extensions: Yes

Please note that **D:\OneDrive - Microsoft** is the folder which synced with my OneDrive for Business

**Comment by golf1052** [comment]
You're probably running into #35433. I noticed this morning that I wasn't getting Find in Files results either. It works fine with files not in OneDrive, doesn't work with OneDrive files. I just turned off Files On-Demand so we'll see if things work once everything syncs.

**Comment by sandy081** [comment]
Assigning to you @roblourens, assuming it could be related to search process

**Comment by roblourens** [comment]
Closing this in favor of #35433
