### ISSUE TITLE
Editor text is not sub-pixel anti-aliased on Arch Linux

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode#36629]
OS: Arch Linux
Visual Studio Code version: 1.7.2

![vscode](https://user-images.githubusercontent.com/2160692/31816914-c2e43280-b557-11e7-98d9-07e4325a5ced.png)

However the text in the “About” dialog is sub-pixel anti-aliased.

Not sure if other Linux systems have the same problem.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24957
