### ISSUE TITLE
Emmet doesn't respect tab completion settings

### ISSUE THREAD

**Issue by doque** [Microsoft/vscode#36628]
- VSCode Version: 1.17.2
- OS Version: mac OS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. Create file with syntax file Javascript React
2. Type `const foo = []`
3. Emmet will suggest to insert a snippet: 
![image](https://user-images.githubusercontent.com/1480751/31816134-63b62ee8-b58f-11e7-88cf-5de6bf7024a1.png)
4. Hitting return (as in, leave the array empty and insert a new line) will trigger the Emmet completion and remove `[]`, leaving only `const foo = `.

This shouldn't happen, according to my settings:

```js
{
  "editor.tabCompletion": true,
  "editor.snippetSuggestions": "bottom",
  "emmet.showSuggestionsAsSnippets": true,
  "emmet.triggerExpansionOnTab": true
}
```

Am I missing something here? My goal is to not have emmet do anything when I hit return, much less delete characters and replace them with nothing.

Reproduces without extensions: No.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @doque 
This is definitely a bug. I'll look into providing a fix soon.

**Comment by ramya-rao-a** [comment]
The fix for this will be out in Monday's Insiders build
