### ISSUE TITLE
Enhancement Request - Option to delay applying property changes when editing tabular models

### ISSUE THREAD

**Issue by phual** [Microsoft/vscode#36626]
- VSCode Version: SSDT 15.3.3 (VS 2017)
- OS Version: Windows 7 6.3.9600
- Tabular Model compatibility level 1103

Making changes to the design of tabular models is slow. Every time you make a change, you have to wait for that change to be applied before making the next change. The user experience could be dramatically improved by delaying the application of changes until multiple changes have been made. Here is a simple example:

Current experience:
1. Import table with a column of data type "Decimal Number".
2. Change the "Data Format" from the default of "General" to "Decimal Number".
3. Move to the next property - forced to wait for model to update.
4. Update "Decimal Places" setting to 5.
5. Move to the next property - forced to wait for model to update.
6. Set "Show Thousand Separator" to True.
7. Move to the next property - forced to wait for model to update.

Improved experience:
1. Import table with a column of data type "Decimal Number".
2. Change the "Data Format" from the default of "General" to "Decimal Number".
3. Update "Decimal Places" setting to 5.
4. Set "Show Thousand Separator" to True.
5. Choose "apply changes" or move to different entity - wait for model to update all three changes at the same time.

**Comment by isidorn** [comment]
Please file this against Visaul Studio.
This is a different product Visual Studio Code.

Sorry for the confusion
