### ISSUE TITLE
Minimap out of sync with scrollbar

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#36622]
Not sure if this belongs here but it is issue after all....

Minimap gets out of sync with scroll position. ( left image - u can crearly see, that scrollbar handle is far lower than minimap 'handle' ... )

Also error markers ( in green circle ) are in scope of scrollbar and not minimap ... i usually center minimap view to that red box, get confused for a while and then move to correct place

Can be minimap changed to look similar to Visual Studio (right image) - basically hide 'default' scrollbar and render custom scrollbar with minimap inside?

![minimap](https://user-images.githubusercontent.com/12444673/31811455-efe8c67e-b57f-11e7-8f1c-a5df46b89d8d.png)

**Comment by alexandrudima** [comment]
#### Visual Studio
In Visual Studio, the minimap and the scrollbar share the same geometry. For example, in an editor of 800px height, the minimap is always 800px high:
* if a file has 80 lines, each line gets 10px in the minimap
* if a file has 800 lines, each line gets 1px in the minimap.
* if a file has 80000 lines, each line gets ... 0.01px in the minimap. 
This has the consequence that, at one point, the Visual Studio minimap switches to sampling lines.

#### Visual Studio Code
In Visual Studio Code, the minimap and the scrollbar do not share the same geometry. In Visual Studio Code, each line gets a fixed amount of pixels reserved in the minimap, and the minimap height is made variable. For example, in an editor of 800px height, where each line gets 2px in the minimap (a low DPI display):
* if a file has 80 lines, the minimap height is 160px
* if a file has 800 lines, the minimap height is 1600px
* if a file has 80000 lines, the minimap height is 160000px
This has the consequence that, at one point, the minimap will also need to scroll.

You can think of the minimap in VSCode as a 10x zoomed-out version of your code. If in the regular editor, a line takes 20px in height, in the minimap a line takes 2px.

You can upvote that we implement the Visual Studio model in #21849
