### ISSUE TITLE
Folder setting changes don't send any workspace.onDidChangeConfiguration() notifications

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode#36625]
- VSCode Version: 1.18.0-insider 3495b0b185acbe8188e821ccb3ae807274703a9c
- OS Version: Windows 10

Steps to Reproduce:

1. I have this code in an extension.
```TypeScript
export function initialize() {
	console.log("initialized");
	configurationListener = workspace.onDidChangeConfiguration(() => {
		console.log("changed");
	});
}
```
2. When I change user settings or workspace settings, I get notified. However, when I change folder settings I don't get any notifications. The settings in my package.json are `"scope": "resource"` and I have been told that this should work.

![image](https://user-images.githubusercontent.com/15629116/31814689-5cae6256-b5c5-11e7-8806-a80043f7f4f1.png)

**Comment by sandy081** [comment]
To Verify:

- Open  a Multi root workspace with Folders A, B
- Configure `files.exclude` setting under Settings of Folder A to exclude some files under Folder A.
- Make sure Explorer is updated according to the changes to this setting in Settings of Folder A.
