### ISSUE TITLE
Auto-updating (v1.17.1 to v1.17.2) didn't install vscode in existing dir

### ISSUE THREAD

**Issue by sumbrez** [Microsoft/vscode#36633]
- VSCode Version: 1.17.1 (2017-10-10T14:24:50.851Z)
- OS Version: Windows 10 64bit

I installed vscode in D dir, and auto-updating before v1.17.1 worked correctly, but updating from v1.17.1 to v1.17.2 installed vscode in C dir (default dir).

Extensions:
Gimly81.matlab-0.7.1
robertohuertasm.vscode-icons-7.15.0
James-Yu.latex-workshop-3.5.5
se2dev.vscode-yacc-1.1.0
justusadam.language-haskell-2.4.0
Shan.code-settings-sync-2.8.3
luniclynx.lex-0.1.0
yzhang.markdown-all-in-one-0.11.0

**Comment by joaomoreno** [comment]
That's very odd... Can you try to reproduce?

1. Fully uninstall Code
2. Install [1.17.1](https://vscode-update.azurewebsites.net/1.17.1/win32-x64/stable) on `D:` again
3. Get an update

Does it reproduce?

**Comment by sumbrez** [comment]
It didn't reproduce. Now I think there's something wrong with my Windows.  A recent system update made many files' permission abnormal, although I uninstalled it at once, I doubt that this issue existed before the system update.
