### ISSUE TITLE
[folding] Expose folding regions through executeFoldingRangeProvider

### ISSUE THREAD

**Issue by patrys** [microsoft/vscode#36638]
I maintain a code structure visualizing plugin ([Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)) that would benefit from having access to the named regions introduced in one of the recent versions (see [related issue](https://github.com/patrys/vscode-code-outline/issues/50)).

**Comment by patrys** [comment]
Now that the folding API is stable, could we get an `executeFoldingRangeProvider` extended command?

**Comment by aeschli** [comment]
@patrys Sure. Please create an issue so that I don't forget it.

**Comment by aeschli** [comment]
@patrys Will look into it ASAP

**Comment by SimonSiefke** [comment]
This would also be useful for testing folding ranges with vscode-test.

**Comment by octref** [comment]
Ping @aeschli, would want this to do E2E test for language servers.

**Comment by ihdavids** [comment]
Determining which rows are currently folded or being able to test if a region is currently folded would be a huge benefit to some plugins.

**Comment by allisonchou** [comment]
@aeschli is there an ETA for this work? This would be very helpful for the Razor team.

**Comment by aeschli** [comment]
There's now a command `vscode.executeFoldingRangeProvider` returning the folding ranges from providers or from the default provider (indentation based). Ranges are sanitized (duplicates and overlapping ranges removed) and follows the settings `editor.folding`, `editor.foldingStrategy` and `editor.defaultFoldingRangeProvider`

**Comment by jrieken** [comment]
verified in source code
