### ISSUE TITLE
GitHub Desktop not recognized by Visual Studio Code

### ISSUE THREAD

**Issue by feutl** [Microsoft/vscode#3663]
Hi am using GitHub Desktop on my Windows Machines because it is the easiest way to interact with GitHub especially if you work with multiple tools changing files in a repo.

Now VS Code is not recognizing the installed GitHub Desktop and wants me to install git-scm again. This is already there otherwise GitHub Desktop wouldn't work with GUI or GIT Shell.
What am I doing wrong in this case ? I found that others have issues too, but they seem related to authentication, I am stuck at having VS Code recognizing the setup :)

The installation of GitHub Desktop was done using Chocolatery, if this changes something.

Somehow Related topics I already read through but didn't make any difference.
* https://github.com/Microsoft/vscode/issues/2947
* https://github.com/Microsoft/vscode/issues/1984
* https://stackoverflow.com/questions/32639393/authentication-failed-on-the-git-remote
* https://social.msdn.microsoft.com/Forums/vstudio/en-US/eb6853f3-b710-4be5-8b82-d55fa568e2b9/problem-with-git-on-vs-code?forum=vsarch

**Comment by felixfbecker** [comment]
Is git in your path? Eg can you run `git --version` from the command line?

**Comment by feutl** [comment]
This is my outcome
* cmd - git not recognized
* powershell - git not recognized
* git shell (which uses powershell in my case) - git version 2.7.1.windows.1

As it seems is the official github application not setting the variables for the rest of the system only for itself. is there a way code can still fix it for its own, it would just be great :)

**Comment by felixfbecker** [comment]
@feutl Change your PATH to include the git application. I think it is out of scope for VS Code to try to find the git installation if it is not in the PATH...

**Comment by joaomoreno** [comment]
We definitely would like to catch the case that all you have installed in the GitHub for Windows application as that seems to be a pretty common use case. But yes, adding it to your `PATH` for now is the workaround.

**Comment by feutl** [comment]
@felixfbecker 
I do not think so, to be honest, @joaomoreno is right it is a common use case and it is the official way and tool from github for github.
That's why I think this should also be handled by VSCode, sooner than later. There are people out there like me, who need git and github but only to get their work done, because it is a requirement and they want to use VScode, because its great :)

**Comment by feutl** [comment]
http://haacked.com/archive/2015/10/29/git-shell/
seems a good writeup how and what is going on. still for me not that easy to get vscode recognizing the existing portable git version coming with github desktop

**Comment by felixfbecker** [comment]
@feutl All you need to do is open Windows search and type _Environment Var_...  Under _System Variables_ select _PATH_, click _Edit_, and then _New_. You can either copy+paste the path were the git.exe is located or click _Search_ to get a folder picker. The GUI for this in Windows is really superb.

Often, there is also an installation option to add git to the PATH.

**Comment by Tyriar** [comment]
@joaomoreno did you have any specific plans on resolving this, like detecting the default GitHub for Windows path or something? Isn't it reasonable to assume git is on the `PATH`? If git is missing is the error we present good enough for most people to do it on their own?

**Comment by joaomoreno** [comment]
[We do search for it in a few places](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/electron-browser/electronGitService.ts#L94) aside from relying on the `PATH`, just need to complement it. Let's do it.
