### ISSUE TITLE
Poor compatibility with Power Line

### ISSUE THREAD

**Issue by bigkrp** [Microsoft/vscode#36637]
![2017-10-20 17-13-49](https://user-images.githubusercontent.com/11586744/31825199-160563e6-b5ba-11e7-8c78-00f4379ea409.png)

- VSCode Version:1.17.1
- OS Version: Fedora 26

Steps to Reproduce:

1. Run VS Code
2. Open terminal

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
It looks like you're not using the powerline font, check out https://github.com/Microsoft/vscode/issues/7116 for how to set that up
