### ISSUE TITLE
Closing curly brace cannot be written

### ISSUE THREAD

**Issue by deiberdev** [Microsoft/vscode#36635]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
ftp-sync|luk|0.3.3
atom-keybindings|ms-|3.0.2
material-icon-theme|PKi|2.2.2
vscode-icons|rob|7.15.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Delete some closing curly brace.
2. It cannot be written again using the keyboard (the event cannot be triggered).

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You can't retype the closing curly brace? Can you include a gif or screenshot so we're clear?

**Comment by deiberdev** [comment]
![screenshot](https://user-images.githubusercontent.com/27818529/31830825-a6811802-b57e-11e7-87e0-1b753b8a63ac.gif)

**Comment by roblourens** [comment]
That's odd, can you start Code with `--disable-extensions` and check whether it still reproes?

If so, can you check for errors in the console in Help > Toggle Developer Tools?

**Comment by mnunezdm** [comment]
i've being running with this issue for 2 months thought i was the only one

**Comment by roblourens** [comment]
I see both of you have atom-keybindings. @deiberdev do you also have a non-english keyboard layout?

**Comment by deiberdev** [comment]
Yes, I have a Latin American keyboard layout. I change it to English and now I can type the closing curly brace.

**Comment by alexandrudima** [comment]
I have moved this issue to https://github.com/Microsoft/vscode-atom-keybindings/issues/40

Until the extension is modified to no longer bind keybindings to `ctrl+alt+` combinations, the workaround is to search in your keybindings (ctrl+k ctrl+s) for "ctrl+alt+" keybindings, find the offending ones and delete them.
