### ISSUE TITLE
CPU full load for over 5 mins while replacing strings in multiple files

### ISSUE THREAD

**Issue by universonic** [Microsoft/vscode#36631]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-clock|Com|0.0.1
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-color|ans|0.4.5
gitignore|cod|0.5.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
vscode-html-css|ecm|0.1.8
code-runner|for|0.7.3
Angular2|joh|2.9.0
Go|luk|0.6.66
VS-code-vagrantfile|mar|0.0.7
graphql|mqu|0.1.2
mssql|ms-|1.2.0
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.4.0
Ruby|reb|0.15.0
java|red|0.12.0
vscode-icons|rob|7.15.0
sass-indented|rob|1.4.5
stylelint|shi|0.30.0
vscode-glide|vit|1.0.2
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Open a project which has more than 500 files
2. Replace all exact occurrences of a given string with another one in all files in the project folder.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Which process is taking the CPU load? Is this an open source project that I can try? Are the matches in very long lines?

**Comment by universonic** [comment]
Sorry, I didn't make myself very clear. My computer model is MacBook Pro 15-inch, 2016 late. I Just open a project with more than 500+ files, and make a string replacement, then click the _Close All Editors_ button on top right corner of the _Open Editors_ window. 
This operation will pop out a dialog to ask if I would like to save those changes. After click the save button, VSCode came to stuck, and used up all left CPU resources (memory that allocated to VSCode is also over 8GiB in the meantime). I guest there must be a buffer problem while doing such jobs.

**Comment by gorangrubic** [comment]
I have the same situation here -- all 8 cores are loaded to max. This is: 1.15.1, Win64 bit build.
Yasterday I've installed this new build (before I had 32bit version. Also installed some extensions afterwards so I'm convinced some extension gone wild.
Using Code more than year - and due the project I'm working on I watch the CPU usage non stop and this is the first time I see this behavior. 
![image](https://user-images.githubusercontent.com/20734509/31849384-9a61ecea-b641-11e7-92ca-324c38cfe514.png)

![image](https://user-images.githubusercontent.com/20734509/31849388-a6e205ea-b641-11e7-8b7d-807969bfae30.png)

![image](https://user-images.githubusercontent.com/20734509/31849391-bcc6c99a-b641-11e7-9971-461fdb14cc51.png)

* tried with open/close
* also when I clicked "reload" on a extension - it stopped for few seconds, so I'm sure it is some extension doing this.

**Comment by roblourens** [comment]
@gorangrubic Your repro steps don't match @universonic, please open another issue, and show the command line args for the processes that are taking lots of CPU. Also 1.15 is a couple versions old, please update (and you could also try the Insiders build to try the latest changes).

@universonic I see, can you check the command line arguments of the process taking CPU, using `ps aux`?

**Comment by universonic** [comment]
As you can see, there are so many processes on my system (I have disabled buildOnSave and lintOnSave):

```bash
[universonic@KAMIKAZE kubernetes-client]$ ps aux
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
universonic       2593  59.9  1.3 558450504 219460   ??  R    11:45AM   0:05.93 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6335  30.8  0.3 558447600  55268   ??  R    11:47AM   0:00.51 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       2671  24.7  1.3 558450440 211664   ??  R    11:45AM   0:05.84 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       1378  23.7  0.2 558438436  34132   ??  R    11:45AM   0:06.66 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_2 -o /var/folde
universonic       2696  21.5  1.4 558451080 226940   ??  R    11:45AM   0:06.06 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6352  20.9  0.2 558446128  29080   ??  R    11:47AM   0:00.15 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6344  18.0  0.2 558446960  40284   ??  R    11:47AM   0:00.35 (compile)
universonic       1304  17.8  0.2 558438372  35208   ??  R    11:45AM   0:06.76 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_2 -o /var/folde
universonic       6333  15.4  0.3 558446512  54084   ??  R    11:47AM   0:00.44 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       2579  14.4  1.3 558450504 210924   ??  R    11:45AM   0:06.24 (compile)
universonic       6123  14.4  0.1 558437540  12088   ??  R    11:47AM   0:02.51 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_4 -o /var/folde
universonic       2646  14.1  1.4 558450568 229612   ??  R    11:45AM   0:06.25 (compile)
universonic       5947  13.9  0.9 558448896 154220   ??  R    11:47AM   0:03.31 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6167  13.9  0.1 558437028  11864   ??  R    11:47AM   0:02.28 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_4 -o /var/folde
universonic       6343  13.5  0.3 558446448  41952   ??  R    11:47AM   0:00.29 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6020  13.4  0.9 558448896 154924   ??  R    11:47AM   0:02.86 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6008  13.1  0.9 558448576 146780   ??  R    11:47AM   0:03.00 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       5989  12.8  0.3 558438628  49364   ??  R    11:47AM   0:02.95 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_2 -o /var/folde
universonic       6346  12.8  0.2 558445616  35140   ??  R    11:47AM   0:00.23 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6081  12.5  0.1 558437284  11832   ??  R    11:47AM   0:02.54 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_4 -o /var/folde
universonic       6342  12.4  0.2 558446448  40488   ??  R    11:47AM   0:00.31 (compile)
universonic       6360  12.3  0.0 558436900   3488   ??  R    11:47AM   0:00.04 (cover)
universonic        800  11.4  2.0  6386788 328884   ??  R    11:40AM   0:37.59 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Content
universonic       2722  11.1  1.3 558450952 211532   ??  R    11:45AM   0:05.98 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6121  10.9  0.1 558437540  12072   ??  R    11:47AM   0:02.57 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_4 -o /var/folde
universonic       6128  10.9  0.1 558437284  12172   ??  R    11:47AM   0:02.61 (cover)
universonic       2363  10.9  1.3 558450824 225772   ??  R    11:45AM   0:06.17 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6347  10.8  0.2 558446448  37280   ??  R    11:47AM   0:00.25 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6126  10.8  0.1 558437284  11824   ??  R    11:47AM   0:02.36 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_4 -o /var/folde
universonic       6328  10.7  0.3 558446576  54648   ??  R    11:47AM   0:00.60 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       1375  10.6  0.2 558438372  33744   ??  R    11:45AM   0:06.36 /usr/local/go/pkg/tool/darwin_amd64/cover -mode set -var GoCover_2 -o /var/folde
universonic       6345  10.3  0.2 558446192  37888   ??  R    11:47AM   0:00.22 /usr/local/go/pkg/tool/darwin_amd64/compile -o /var/folders/zz/sm1y6p5d5qg8cq249
universonic       6341  10.1  0.2 558446448  38032   ??  R    11:47AM   0:00.33 (compile)
```

**Comment by roblourens** [comment]
This seems like it could be an issue with the vscode-go extension which I assume you're using. You could check whether it's set up to do something else on save, or file an issue on that repo.

**Comment by gorangrubic** [comment]
@roblourens sorry, I'm noob in issue reporting on GitHub (and issue reporting at all).  However, this seems for me as the same issue - as the behavior is the same - if I would be the one that has to debug this I would assume that @universonic  just had a coincidence doing string replacement when this happen. But, as said, still have no experience in this. 
Related to vscode-go: no, I don-t have it here. But, since my last comment it never repeated. And I just tried several string replacements (Replace All and single Replace) and nothing wrong about CPU.  If it does happen, where you want me to report it: on this thread or to create new issue?

**Comment by roblourens** [comment]
No worries. Glad it stopped happening, but if it does, please open a new issue.
