### ISSUE TITLE
The logo

### ISSUE THREAD

**Issue by gonoiu** [Microsoft/vscode#36639]
- VSCode Version: latest
- OS Version: win10

Steps to Reproduce:

1. The logo is really ugly
2. The logo is really ugly
 
The new logo is so ugly can't even click on it to open the editor. I'm going to use somethig else.

**Comment by chrisdias** [comment]
Don't give up on us yet, we're working on it!

Dupe of https://github.com/Microsoft/vscode/issues/35783

**Comment by richarddavenport** [comment]
@gonoiu hahahahahahaha
