### ISSUE TITLE
Integrated terminal doesn't recognize project folder location on removable media (WSL Bash)

### ISSUE THREAD

**Issue by uwe-h** [Microsoft/vscode#36643]
- VSCode Version: 1.17
- OS Version: Windows 10.0.16299.19 (Win10 1709) 

Steps to Reproduce:

1. Mount any removable device (say its drive letter is D) in WSL Bash so you can access it via "/mnt/d".
2. Make sure you use WSL Bash as integrated terminal.
3. Open a project folder on this removable device.
4. The integrated Bash terminal defaults to WSL Bash's user home directory, not to the project folder. This somehow makes sense because it was not possible to mount removable devices in former builds of WSL. However it's been implemented for a while now and since Fall Creators Update this feature is available to a wider public. As a consequence, it's not trivial to use Tasks oder Launch commands because they all operate in the wrong location. 
This fallback solution should be replaced with a check whether the folder is currently accessible in /mnt/ or not. Note that the removable drives stay mounted as long as there exists an open Bash window (globally, not restricted to VS Code terminals) or the user unmounts it.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@uwe-h this is probably a problem in WSL, the terminal launches a WSL instance by calling bash.exe and setting the cwd to the current project directory.

**Comment by uwe-h** [comment]
@Tyriar You are right. If you use cmd.exe to navigate to a location on D:\ and then start bash, you are also redirected to your user's directory. So it's not on VS Code.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/32717
