### ISSUE TITLE
[Feature Request] Preview in new window

### ISSUE THREAD

**Issue by Ash258** [Microsoft/vscode#36647]
I would like to open preview / or some other file in new window so i can move it to other monitor or make it smaller. 

1. I am facing lack of this feature mainly for markdown / latex files when on normal (not ultrawide) is quite uncomfortable. 
1.  Next nice example is comparing files. 
    - When i am developing some C i print output of program (valgrind output, etc...) to text file and compare it in editor. (better than scrolling in terminal)
    - So is nice to open compare on second monitor and just check changes.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/31848135-814618b4-b62b-11e7-889e-fd55dbfaeed9.png)
