### ISSUE TITLE
Integrated Terminal shell drop down not sized properly

### ISSUE THREAD

**Issue by Erchamion** [Microsoft/vscode#36645]
- VSCode Version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:29:07.096Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1.  Open integrated term window
2.  The terminal / shell drop down is not properly sized.

![image](https://user-images.githubusercontent.com/11239968/31830660-e9183406-b58e-11e7-9a53-ec02136e1365.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@isidorn I think you were working on this?

**Comment by isidorn** [comment]
Fixed in latest
