### ISSUE TITLE
Verifying PlatformIO Core installation... stuck here.

### ISSUE THREAD

**Issue by chall3ng3r** [Microsoft/vscode#36648]
It was working perfectly with couple of VSCode updates back. But VSCode force updated, and the extension now is stuck here.

Have tried reinstalling, disabling with no use.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
scad|efb|1.0.1
cpptools|ms-|0.14.0
platformio-ide|pla|0.7.3
debug|web|0.21.2

---

Steps to Reproduce:

1. Install latest VSCode and PlatformIO Extention
2. Start VSCode. The status bar message with be "Verifying PlatformIO Core installation"

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Tracked by https://github.com/platformio/platformio-vscode-ide/issues/45
