### ISSUE TITLE
Support indented here-docs (fix incorrect string highlighting)

### ISSUE THREAD

**Issue by skaurus** [Microsoft/vscode#36640]
I'm talking about this: http://perldoc.perl.org/perlop.html#Indented-Here-docs

Steps to Reproduce:

1. write perl code like that:
```perl
if ($cond) {
    my $string = <<~EOF;
        indented
        text
        will be
        indented
        just by 4 spaces
        and totally not 8
    EOF
    my $res = $self->method;
}
...
```
2. code after closing `EOF` will be colored as if it's still inside the string.

Currently it works only if opening here-doc marker does not have a tilde; AND closing marker is not indented (at all).

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
@mjbvz This is perl, not PHP :D

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#26
