### ISSUE TITLE
Visual Studio code fails to launch from time to time

### ISSUE THREAD

**Issue by vikrampraveen** [Microsoft/vscode#36646]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.17018
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
vscode-icons|rob|7.15.0

---

Steps to Reproduce:

1. Try to open a file from anywhere using console or shell
2. Try to open a new window.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide more details. How to reproduce this.
Can you aslo reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
