### ISSUE TITLE
Improvements to the default view in the Extensions Viewlet

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#36649]
The default view in the Extensions Viewlet shows 2 sections. 1 for Installed extensions, the other for recommended extensions. Below are the proposed improvements to reduce noise/information overload and provide the user with more useful information

1. **Goal**: Reduce noise in the "Installed" view
**Experiment**: Show "Enabled" extensions instead of "Installed" extensions.

Including disabled extensions in the default view can be considered noise for some people. On the other hand it is useful for those who are frequently enabling/disabling extensions.

**Data**: Looking at a 10 day period of data, we see
- About 3% of users who open the Extensions view run the "Enable Extension" action
- About 5% of users who open the Extensions view run the "Disable Extension" action
- About 55% of users who open the Extensions view search for extensions
- About 10% of users who open the Extensions view run the "Uninstall Extension" action

2.  **Goal**: Reduce clutter in the "Recommended" view
**Experiement**: Trim the # of recommended extensions. 
- Show all of the workspace recommendations. These are the ones deemed as important by someone in repo collaborators group, and so deserve their spot in the recommendations always.
- We have timestamp on file based recommendations. This timestamp denotes the last time file of type "x" was opened that resulted in recommendation "y". Use this to recommend the top 2.
             - If no workspace recommendations exist, then show top 5
- Randomly choose 2 from the exeutable based recommendations 

3. **Goal**: Convey the "why"/"how" behind the recommended extension.
**Experiment**:
- Show this on hover over the recommended extension
- Include it in the aria-label for the recommended extension
- Show this in the header of the extension editor that opens on clicking an extension in the view 

4. **Goal**: Enable more user attention on the Recommendations view 
**Experiment** : Collapse the "Installed" view by default or swap the order between the 2

**Comment by ramya-rao-a** [comment]
cc @Microsoft/vscode

**Comment by roblourens** [comment]
> Show "Enabled" extensions instead of "Installed" extensions.

Where do I see disabled extensions? Will an extension leave the list when I disable it?

**Comment by ramya-rao-a** [comment]
You can see the disabled extensions using the "Show Disabled Extensions" or "Show Installed Extensions" menu options. There are commands in the command pallet for the same.

**Comment by chrmarti** [comment]
It would make sense to have everything you "need" to work with extensions in the default view. That avoids the need for the user to discover the other views in the view menu which is difficult for new users.

To me the disabled extensions are part of what I need to work with extensions, so I would keep them in the default view. A colored 'Enable' button would make their state stand out better.

Also: Besides collapsing the Installed section I'd also move it to the bottom to make the Recommended section more prominent.

**Comment by ramya-rao-a** [comment]
I like the idea of swapping the order and showing the Recommended section first.

The initial thought behind collapsing the "Installed" section is to get the user's attention to the long list of recommendations. Pruning the recommended list + showing the Recommendations first and Installed later serves this purpose.

**Comment by chrmarti** [comment]
Or try both: collapse and move the Installed section to the bottom? The user likely expects there to be a list of installed extensions "somewhere" and will scan the UI for it when needed.

**Comment by ramya-rao-a** [comment]
Of the 4 experiments detailed in https://github.com/Microsoft/vscode/issues/36649#issue-267253728, the 2nd and 3rd will be shipped in the October milestone.
