### ISSUE TITLE
Integrated Terminal Doesnot prompt for Input.

### ISSUE THREAD

**Issue by shobanbobba** [Microsoft/vscode#36658]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Updated VS Code software to version 1.17.2
2. Terminal stopped prompting. 
![terminal_notprompting](https://user-images.githubusercontent.com/31071951/31841884-20dd9eae-b5b1-11e7-81cc-0f344773030e.PNG)

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by shobanbobba** [comment]
I tried with cmd.exe path and gitbash.exe path. It worked before upgrade.

**Comment by Tyriar** [comment]
@shobanbobba I need to see your settings.json file to further diagnose the issue

**Comment by shobanbobba** [comment]
Here it is. Thanks.

// Customizes what kind of terminal to launch.
"terminal.explorerKind": "integrated",

// Customizes which terminal to run on Windows.
"terminal.external.windowsExec": "C:\\Windows\\System32\\cmd.exe",

// Customizes which terminal application to run on OS X.
"terminal.external.osxExec": "Terminal.app",

// Customizes which terminal to run on Linux.
"terminal.external.linuxExec": "xterm",


// The path of the shell that the terminal uses on Linux.
"terminal.integrated.shell.linux": "sh",

// The command line arguments to use when on the Linux terminal.
"terminal.integrated.shellArgs.linux": [],

// The path of the shell that the terminal uses on OS X.
"terminal.integrated.shell.osx": "sh",

// The command line arguments to use when on the OS X terminal.
"terminal.integrated.shellArgs.osx": [
"-l"
],

// The path of the shell that the terminal uses on Windows. When using
shells shipped with Windows (cmd, PowerShell or Bash on Ubuntu).
"terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",

// The command line arguments to use when on the Windows terminal.
"terminal.integrated.shellArgs.windows": [],

// When set, this will prevent the context menu from appearing when right
clicking within the terminal, instead it will copy when there is a
selection and paste when there is no selection.
"terminal.integrated.rightClickCopyPaste": true,

// Controls the font family of the terminal, this defaults to
editor.fontFamily's value.
"terminal.integrated.fontFamily": "",

// Controls the font size in pixels of the terminal.
"terminal.integrated.fontSize": 14,

// Controls the line height of the terminal, this number is multipled by
the terminal font size to get the actual line-height in pixels.
"terminal.integrated.lineHeight": 1,

// Controls whether the terminal cursor blinks.
"terminal.integrated.cursorBlinking": false,

// Controls the style of terminal cursor.
"terminal.integrated.cursorStyle": "block",

// Controls the maximum amount of lines the terminal keeps in its buffer.
"terminal.integrated.scrollback": 1000,

// Controls whether locale variables are set at startup of the terminal,
this defaults to true on OS X, false on other platforms.
"terminal.integrated.setLocaleVariables": false,

// An explicit start path where the terminal will be launched, this is used
as the current working directory (cwd) for the shell process. This may be
particularly useful in workspace settings if the root directory is not a
convenient cwd.
"terminal.integrated.cwd": "",

// Whether to confirm on exit if there are active terminal sessions.
"terminal.integrated.confirmOnExit": false,

// A set of command IDs whose keybindings will not be sent to the shell and
instead always be handled by Code. This allows the use of keybindings that
would normally be consumed by the shell to act the same as when the
terminal is not focused, for example ctrl+p to launch Quick Open.
"terminal.integrated.commandsToSkipShell": [
"editor.action.toggleTabFocusMode",
"workbench.action.debug.continue",
"workbench.action.debug.pause",
"workbench.action.debug.restart",
"workbench.action.debug.run",
"workbench.action.debug.start",
"workbench.action.debug.stop",
"workbench.action.focusActiveEditorGroup",
"workbench.action.focusFirstEditorGroup",
"workbench.action.focusSecondEditorGroup",
"workbench.action.focusThirdEditorGroup",
"workbench.action.navigateDown",
"workbench.action.navigateLeft",
"workbench.action.navigateRight",
"workbench.action.navigateUp",
"workbench.action.openNextRecentlyUsedEditorInGroup",
"workbench.action.openPreviousRecentlyUsedEditorInGroup",
"workbench.action.quickOpen",
"workbench.action.quickOpenView",
"workbench.action.showCommands",
"workbench.action.terminal.clear",
"workbench.action.terminal.copySelection",
"workbench.action.terminal.deleteWordLeft",
"workbench.action.terminal.deleteWordRight",
"workbench.action.terminal.findWidget.history.showNext",
"workbench.action.terminal.findWidget.history.showPrevious",
"workbench.action.terminal.focus",
"workbench.action.terminal.focusAtIndex1",
"workbench.action.terminal.focusAtIndex2",
"workbench.action.terminal.focusAtIndex3",
"workbench.action.terminal.focusAtIndex4",
"workbench.action.terminal.focusAtIndex5",
"workbench.action.terminal.focusAtIndex6",
"workbench.action.terminal.focusAtIndex7",
"workbench.action.terminal.focusAtIndex8",
"workbench.action.terminal.focusAtIndex9",
"workbench.action.terminal.focusFindWidget",
"workbench.action.terminal.focusNext",
"workbench.action.terminal.focusPrevious",
"workbench.action.terminal.hideFindWidget",
"workbench.action.terminal.kill",
"workbench.action.terminal.new",
"workbench.action.terminal.paste",
"workbench.action.terminal.runActiveFile",
"workbench.action.terminal.runSelectedText",
"workbench.action.terminal.scrollDown",
"workbench.action.terminal.scrollDownPage",
"workbench.action.terminal.scrollToBottom",
"workbench.action.terminal.scrollToTop",
"workbench.action.terminal.scrollUp",
"workbench.action.terminal.scrollUpPage",
"workbench.action.terminal.selectAll",
"workbench.action.terminal.toggleTerminal",
"workbench.action.togglePanel"
],

// Object with environment variables that will be added to the VS Code
process to be used by the terminal on OS X
"terminal.integrated.env.osx": {},

// Object with environment variables that will be added to the VS Code
process to be used by the terminal on Linux
"terminal.integrated.env.linux": {},

// Object with environment variables that will be added to the VS Code
process to be used by the terminal on Windows
"terminal.integrated.env.windows": {},

Thanks,
Shoban.
(515) 494-0084

**Comment by Tyriar** [comment]
@shobanbobba that's the default settings (left side), what's in your user settings (right side)?

**Comment by shobanbobba** [comment]
User settings, this is what I have

{
"workbench.colorTheme": "Monokai Dimmed",
"autoimport.doubleQuotes": true,
"tslint.autoFixOnSave": false,
"genGetSet.pathStringDelimiter": "'",
"window.zoomLevel": -1
}



Thanks,
Shoban.
(515) 494-0084

**Comment by Tyriar** [comment]
Can you try set the shell using the command palette:

- ctrl+shift+p
- "default shell"
- enter
- Pick cmd
- Try launching a new terminal

**Comment by shobanbobba** [comment]
I tried, still the same. No permit.

**Comment by shobanbobba** [comment]
reinstalled VS Code. Its working now. Thanks for your support.

Thanks,
Shoban.
(515) 494-0084

**Comment by Tyriar** [comment]
Great to hear 😃
