### ISSUE TITLE
new icon blends on an orange background (transparent parts of icon cause it).

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#36657]
![screenshot_114](https://user-images.githubusercontent.com/31345346/31841864-b2229c54-b5eb-11e7-94aa-309f7f6b2f8a.png)

**Comment by Mlocik97-issues** [comment]
I think it's good to upholster icon arround.

**Comment by maxibanki** [comment]
Issue isn't relevant anymore because the icon color has changed to green for insider releases and blue for stable releases. More information you will find [here](https://code.visualstudio.com/blogs/2017/10/24/theicon).
