### ISSUE TITLE
modify javascript code while single stepping does not cause code to be recompiled

### ISSUE THREAD

**Issue by johngrabner** [Microsoft/vscode#36656]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. enter debug point
2. when code is hit, change some lines, save and continue single stepping
in visual studio, this would cause the part of code modified to be recompliled and single stepping would be using the new code. In VScode, must completely quit the application and start over.

**Comment by auchenberg** [comment]
We don't support live editing in VS Code for JavaScript directly, but you can use webpack, Nodemon and other 3rd party tools to enable automatic restart of your node process when Node is changed.

For client-side code we recommend Webpack, which works well with React. See https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f

**Comment by johngrabner** [comment]
Visual studio does not restart the whole app, but rather recompiled only the affected closure and code keeps states from other closure.

This made visual studio great since you could fix as you single step.

Too bad this is not available is this product



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------
