### ISSUE TITLE
[ts] 'import ... =' can only be used in a .ts file

### ISSUE THREAD

**Issue by leocavalcante** [Microsoft/vscode#36654]
- VSCode Version: 1.17.2
- OS Version: Microsoft Windows [version 6.1.7601]

Steps to Reproduce:

1. Install `flowtype.flow-for-vscode`
2. Add to `.vscode\settings.json`
```json
{
  "flow.useNPMPackagedFlow": true,
  "javascript.validate.enable": false,
  "typescript.validate.enable": false
}
```
3. Create a `.js` file with `// @flow` at top
4. Import some type: `import type Foo`

Reproduces without extensions: No
Yes, project have a `.flowconfig` at root folder.

**Comment by mjbvz** [comment]
We don't support flow out of the box. Try following the flow extension's [setup instructions](https://github.com/flowtype/flow-for-vscode#setup )  to disable our builtin js validator by setting `"javascript.validate.enable": false` so that the flow one is active instead

**Comment by leocavalcante** [comment]
> Try following the flow extension's setup instructions to disable our builtin js validator by setting "javascript.validate.enable": false so that the flow one is active instead

Did you saw step 2 on the 'Steps to Reproduce'?

**Comment by mjbvz** [comment]
Sorry, my bad. Here's the error message I see without `"javascript.validate.enable": false`:

![screen shot 2017-10-20 at 1 53 33 pm](https://user-images.githubusercontent.com/12821956/31841376-15eb00c6-b59e-11e7-902f-72a13fc42336.png)

You see the same error but with `[ts]` instead?

**Comment by leocavalcante** [comment]
My bad now, maybe something related to `sourcegraph.javascript-typescript`, removing it fixed it.
Thanks!
