### ISSUE TITLE
PHP Syntax Highlighter Fails to Highlight all Escape Sequences

### ISSUE THREAD

**Issue by KyleJohnstonNet** [Microsoft/vscode#36655]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-twig-pack|baj|1.0.0
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
php-symbols|lin|2.1.0
twig|wha|1.0.2
html-css-class-completion|Zig|1.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. In any text file, enable PHP syntax highlighting
2. Insert the following in the file and observe the highlighting.
```
<?php
  $foo = "A double quoted string doesn't highlight all valid escape sequences such as \v and \f. It does highlight some like \n, \r, \e, and \\ though.";
  $bar = 'A single quoted string dosen\'t recognize \r or \n, as it should.";
?>
```

See the full list of escape sequences PHP recognizes in double quoted strings at: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double

Reproduces without extensions: Yes (With no extensions enabled)

**Comment by roblourens** [comment]
The double quote escape highlighting looks fixed with the new grammar in the Insiders build. Can you try again there?

In the single quoted string, I don't think it should color `\r` or `\n` because those are not escape sequences in a single quoted string.

**Comment by KyleJohnstonNet** [comment]
I tried in the Insiders build and it does correctly highlight escape sequences. Thanks!
