### ISSUE TITLE
emmet attr_quotes not working on tsx file

### ISSUE THREAD

**Issue by leozhao0709** [Microsoft/vscode#36663]
- VSCode Version: 1.17.2
- OS Version: Mac OS 10.12.6
`"emmet.syntaxProfiles": {
        "html": {
            "self_closing_tag": true,
            "attr_quotes": "single"
        },
        "tsx": {
            "self_closing_tag": true,
            "attr_quotes": "single"
        }
    }`

I have these settings. The Html emmet works well, the attr_quote works with single quotes, but for my tsx file, the attr_quotes still show double quotes which should be single quotes.

**Comment by ramya-rao-a** [comment]
Try `jsx` instead of `tsx` in the settings.
`tsx` is not a valid mode in the world of emmet
