### ISSUE TITLE
Integrated console is not loading

### ISSUE THREAD

**Issue by teom10** [Microsoft/vscode#36661]
![image](https://user-images.githubusercontent.com/13441800/31843945-6ab9098c-b5bb-11e7-9e83-c75f490daa09.png)

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.3.2
bower|don|0.0.3
githistory|don|0.2.3
gitlens|eam|5.6.5
tslint|eg2|1.0.12
beautify|Hoo|1.1.1
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
vscode-csproj|luc|0.7.0
prettify-json|moh|0.0.3
csharp|ms-|1.12.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
material-icon-theme|PKi|2.2.2
guides|spy|0.9.0
jsx|Twe|0.0.1
html-css-class-completion|Zig|1.11.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please update to 1.17.2. Duplicate https://github.com/Microsoft/vscode/issues/34554

**Comment by teom10** [comment]
The problem keeps coming up, sometimes it loads and sometimes it does not. I need to close and open a console several times until it works

**Comment by Tyriar** [comment]
Probably actually a duplicate of https://github.com/Microsoft/vscode/issues/37044 then
