### ISSUE TITLE
Live script execution / evaluation under VS Code extension development

### ISSUE THREAD

**Issue by acrolink** [Microsoft/vscode#36668]
I have generated a template for a ` VS Code` extension using `yo code`. While editing the extension files inside `VS Code` I have noticed that I have to make `workbench.action.reloadWindow` before the new code modifications take effect. I think there should be an option to execute the code live without the need to reload the editor's window.

**Comment by weinand** [comment]
Please be more specific about what you tried to do (e.g. editing the package.json or editing source) and what did not work.

**Comment by acrolink** [comment]
@weinand 

I mean while developing the extension (changing source code / JS or TS files) I cannot test the modifications immediately, a windows reload is needed to load the updated extension,

**Comment by weinand** [comment]
This is not really a debug issue.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
