### ISSUE TITLE
Killing a debug session does not cancel Variable spinners 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3666]
Whenever there is a long running debug adapter request and a spinner appears in the UI, this spinner does not disappear when the session is terminated (in fact the full variables viewlet does not disappear in this case). Since starting a new debug session does not work in this situation, only a window reload helps.

**Comment by isidorn** [comment]
Variable spinners means the tree is in a broken state. 

So I believe this is a feature request against the tree 'Setting new tree input should get the tree out of a broken state'.
@joaomoreno or is there something better I could do to clear the bad state?

**Comment by joaomoreno** [comment]
Variable spinners means the `getChildren` either never returned or returned an error. Just pushed 21d1c62 and 78e4f0e which simply catches the error state and calls `onUnexpectedError` with it.

You probably are hitting the error state, and if that's true, `onUnexpectedError` is probably not the right behaviour, so I suggest you catch your errors early and handle them accordingly on your side.

**Comment by isidorn** [comment]
The RawDebugSession needs to remember all the promises it fired, and on disconnect just cancel them all.

**Comment by weinand** [comment]
@isidorn yes, that's probably necessary.
Today this issue is the biggest obstacle for a smooth debug adapter development experience.

**Comment by isidorn** [comment]
@weinand can you please give this a try now, it should behave nicer. I tried it out and works for me.
@joaomoreno can you quickly give this a review? I am just canceling all the promises, even the ones which finished - which works fine in practice. Just in the console I get a warning that my promises do not implement onCancel - not sure if it is mandatory that I implement this if I plan to cancel my promise

**Comment by weinand** [comment]
@isidorn works great!
