### ISSUE TITLE
Terminal dropdown lost its minimum width

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#36662]
@isidorn it looks really awkward now, we should be able to have overflow with the dropdown decreasing in size as necessary.

New:

<img width="349" alt="screen shot 2017-10-20 at 4 24 28 pm" src="https://user-images.githubusercontent.com/2193314/31845197-403ecb40-b5b3-11e7-802f-7658d3e0520c.png">

Old:

<img width="526" alt="screen shot 2017-10-20 at 4 24 59 pm" src="https://user-images.githubusercontent.com/2193314/31845198-422f5e74-b5b3-11e7-833c-6cfdc997d430.png">

**Comment by isidorn** [comment]
I increased the minimal with on Friday, please check it out in the latest insider.
Due to css flex logic it is harder to have this beahvior as before.

Please try out the latest behavior and if you think this is a considerable worse experience then before let me know and we can reopen this

**Comment by Tyriar** [comment]
@isidorn It still feels very cramped when compared to before. Maybe a little bit more to accommodate "powershell" as that is pretty common.

![image](https://user-images.githubusercontent.com/2193314/32132794-f4c2345a-bb7e-11e7-943d-ed16b752d746.png)

**Comment by isidorn** [comment]
Increased by 10px, here is how it looks now on my machine
In case you would like to more fine tune this, here's a code pointer 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/panel/media/panelpart.css#L92

<img width="201" alt="screen shot 2017-10-30 at 10 24 37" src="https://user-images.githubusercontent.com/1926584/32163434-955a4446-bd5c-11e7-948e-b8d0dcda315c.png">

**Comment by yuval-gilboa** [comment]
This is not enough since task names are usually much longer than that. The dropdown should automatically adjust its width to contain all items, or its minimum width should be set much higher. As it is implemented now, it's useless. See example below:

![image](https://user-images.githubusercontent.com/4710322/32989955-d04f937c-cd28-11e7-88a4-a0e959663aa2.png)
