### ISSUE TITLE
Search and replace in multiple files is not usable with long lines

### ISSUE THREAD

**Issue by divega** [Microsoft/vscode#36660]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. I use search and replace in a large markdown-based documentation project 
2. Search and replace UI allows me to pick specific instances of a term to be replaced
3. To the right of the search pane I see a diff view of before and after the replacement
4. Documents are authored with long lines, and many instance of the term to be replaced don't fit in the screen 
5. It is not possible to turn on word wrap in a diff view. Hence the text that I am replacing is not visible without extensive horizontal scrolling, and as a result VS Code is not usable for this scenario.

In comparison, the search and replace experience offered by Atom is much more usable for this scenario, e.g. the text to replace is always visible and in context.

**Comment by adamreisnz** [comment]
I concur that the find & replace in files screen, the way it's currently opening up on the left in the activity bar, which is quite narrow by default, is not the best UX choice. Atom opens a new large panel for this, so you have no issues with entering longer search & replace terms, and makes for much more efficient browsing of search results.

This is enough of an issue to make VSCode unworkable for me at present, as I am forced to resize the activity bar when I want to search, and then make it smaller again in normal conditions when going back to the file explorer.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/23931 covers this
