### ISSUE TITLE
AWS cli command "eb health --refresh" throws error in Integrated Terminal

### ISSUE THREAD

**Issue by prem911** [Microsoft/vscode#36669]
- VSCode Version:
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:46.104Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version:
Windows 10 Pro Version 1709 OS Build 16299.19
Steps to Reproduce:
My project is deployed on AWS as a beanstalk app. I run this command during deployments to see the health of the instances. It was working before we got the new terminal changes.

1. run eb health --refresh from integrated terminal
2. throws error `ERROR: IOError :: [Errno 0] Error`

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Doing to need some more to go on here, is the error printed in the terminal or in a message box? Could you check the devtools console for errors too? (Help > Toggle Developer Tools)

**Comment by prem911** [comment]
Its printed in the terminal.

No errors in dev console
![image](https://user-images.githubusercontent.com/7778147/32222703-5418f360-be60-11e7-82f5-9fd915e921c1.png)

**Comment by Tyriar** [comment]
VS Code is just printing what `eb`/powershell is telling it to print, I don't think anything changed in the area that could impact this since May https://github.com/Tyriar/node-pty/releases/tag/0.6.5. Are you sure your env is setup correctly?

**Comment by prem911** [comment]
Not sure how to tell whether my env is good or bad.
Have been using VSCode for more than a year and religiously update every month.
If you have a AWS elastic beanstalk application, then try the command once.
I was happily using this command till the last 2-3 months update to Code.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36630
