### ISSUE TITLE
Combination `Command + Shift + ?` doesn't work well in a full screen view on macOS.

### ISSUE THREAD

**Issue by paperant** [Microsoft/vscode#36675]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
code-runner|for|0.7.4
java|red|0.12.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Make VS Code in a full screen view on macOS.
2. Use key combination `Command + Shift + ?`.
3. Use the combination for the **second** time after the menu bar appeared and finally it works.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
`cmd+shift+?` brings up this search bar for me. I believe that's implemented by Electron.

<img width="442" alt="screen shot 2017-10-23 at 15 47 05" src="https://user-images.githubusercontent.com/5047891/31892519-84dc3fe6-b809-11e7-8615-aec3afe18ce7.png">

**Comment by paperant** [comment]
@alexandrudima
Actually this search bar is what I want but it fails to pop up when I use VS Code in a full screen view. I have to try the second chance to make it work.

**Comment by bpasero** [comment]
Still happening?
