### ISSUE TITLE
Do not support kotlin

### ISSUE THREAD

**Issue by cv0cv0** [Microsoft/vscode#36676]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Kotlin|mat|1.3.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Please provide us more information. If the language support is not working like expected, then it is a issue from the [kotlin VS Code extension](https://github.com/mathiasfrohlich/vscode-kotlin).

**Comment by cv0cv0** [comment]
@maxibanki @mjbvz Native does not support, installed only to support expansion. Hope to be able to provide support for the original.

**Comment by mjbvz** [comment]
Yes, we only provide builtin support for a small set of core languages. Please try using the extension for Kotlin and file any issues or feature requests for Kotlin against that extension
