### ISSUE TITLE
Why there is always a property "x"?

### ISSUE THREAD

**Issue by huang2002** [Microsoft/vscode#36678]
![image](https://user-images.githubusercontent.com/25705146/31851297-903f47cc-b695-11e7-83b6-7c02843ee7b7.png)

Whenever I define an object, there's an "x" property.

**Comment by Mlocik97-issues** [comment]
the letter X denotes any variable

**Comment by mjbvz** [comment]
Yes this is by design. It indicates that the object is open, you can add any additional property to it or lookup any additional property on it. This is not always true, but it is the case when dealing with object literals in javascript
