### ISSUE TITLE
Numeric keys not working after installing stable version

### ISSUE THREAD

**Issue by jay-web** [Microsoft/vscode#36671]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
open-html-in-browser|cod|0.1.21
python|don|0.7.0
tslint|eg2|1.0.12
react-native-react-redux|EQu|1.4.1
file-icons|fil|1.0.5
auto-close-tag|for|0.5.1
auto-rename-tag|for|0.0.14
terminal|for|0.0.10
Angular2|joh|2.9.0
intellij-idea-keybindings|k--|0.2.15
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|5.0.8
atom-keybindings|ms-|3.0.2
js-atom-grammar|ms-|0.1.14
node-debug2|ms-|1.18.3
color-highlight|nau|2.3.0
laravel-blade|one|1.9.0
laravel5-snippets|one|1.3.4
LiveServer|rit|2.2.1
html5-boilerplate|sid|1.0.1
react-beautify|tai|0.3.0
bootstrap4-vscode|the|2.4.0
python|tht|0.2.3
vscode-react-native|vsm|0.4.4
JavaScriptSnippets|xab|1.5.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this still happen if you disable all of your extensions?

**Comment by mjbvz** [comment]
Closing as not actionable without more information
