### ISSUE TITLE
problem with json file intelligence

### ISSUE THREAD

**Issue by maheswarar** [Microsoft/vscode#36670]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions:  msazurermtools.azurerm-vscode-tools

Extension|Author (truncated)|Version
---|---|---
node-debug2|ms-|1.18.3
azurerm-vscode-tools|msa|0.3.7
vscode-react-native|vsm|0.4.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maheswarar** [comment]
Hi every one 

i am facing problem with the json file intelligence . i am unable to get intelligence for" azure resource manager tools  " which is an extension . could you plzz any one help me...!!!

**Comment by chrmarti** [comment]
@cweining Are you working on the azurerm-vscode-tools extension? Where can we forward issues for it to?

**Comment by cweining** [comment]
Hello maheswarar,

I'm sorry you are having issues with the Azure RM extension for VS Code. I want to make sure I understand the problem so we can look into it. Do you mean that the intellisense pop-up menu does not appear when you are editing a JSON template? Can you attach a screen shot of what is happening for you? Also, are you running the Git Lens extension? We are currently investigating a situation where that extension seems to conflict with the Azure RM Tools extension. If you are running Git Lens, try disabling that extension and see if it fixes the problem.

Thanks,
Chuck Weininger

**Comment by chrmarti** [comment]
Closing as we haven't heard back for some time.
