### ISSUE TITLE
Theming border between explorer and extensions panes

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#36674]
I'm adding a visible separator line to more clearly show the border of explorer/code/terminal, which makes it easier for me to grab these handles and resize the panes:

```javascript
{
    "workbench.colorCustomizations": {
        "panel.border": "#1d262a",
        "sideBar.border": "#1d262a"
    }
}
```

It would also be great to be able to add such a border/separator between the explorer and extension panes.
I went to the [vscode theme color reference docs](https://code.visualstudio.com/docs/getstarted/theme-color-reference) but it seems this is not possible at this time.

![screen shot 2017-10-18 at 11 20 47](https://user-images.githubusercontent.com/994357/31711128-757bc32a-b3f7-11e7-8032-e1fe9e127f05.png)

**Comment by equinusocio** [comment]
I think that only the top border is enough

**Comment by bpasero** [comment]
@fredrikaverpil there is no specific border color for the split-views, but if you set contrastBorder you will see that borders show up there:

![image](https://user-images.githubusercontent.com/900690/32217966-c6c6c162-be29-11e7-85a5-eff82dd49a75.png)

**Comment by eamodio** [comment]
I would like this as well to control the top border: `sideBarSectionHeader.border` or `sideBarSectionHeader.topBorder`

See:
![image](https://user-images.githubusercontent.com/641685/40950873-8a62ea98-6842-11e8-8159-e1d3532bccb0.png)

**Comment by bpasero** [comment]
I added `sideBarSectionHeader.border` as new color.

**Comment by sbatten** [comment]
@bpasero NIT: if the section header is selected, the focus border completely hides the section header border. It's a little weird but not too big of a deal. Feel free to close and mark as verified if this is intended.

**Comment by bpasero** [comment]
@sbatten that is not a new issue, we had that before already. If you feel strong about it, I suggest to file a separate bug for it. My change was just to give a name to a color that was already there before.
