### ISSUE TITLE
Resource consumption

### ISSUE THREAD

**Issue by XXQ521** [Microsoft/vscode#36677]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-database|baj|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.9
jshint|dba|0.10.15
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.12
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
Angular2|joh|2.9.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
java|red|0.12.0
yo|sam|0.9.3
autoimport|ste|1.2.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please add information about the issue

**Comment by mjbvz** [comment]
Closing as not actionable without more information
