### ISSUE TITLE
Debugger will not hit typescript breakpoints on windows when the path contains spaces

### ISSUE THREAD

**Issue by johan-gorter** [Microsoft/vscode#3667]
We had some team members who could not debug mocha unit-tests and others who could. We tracked the problem down to the path which contained spaces (in our case c:\development next\frontend) . This is probably also the cause of issues #3144 and #3659.

This issue has appeared in the last month, before that, we did not have problems with spaces in the path. We suspect that something is wrong with reading the sourcemaps.

**Comment by bruce965** [comment]
A path with no spaces seems to work well (breakpoints hit).
![2016-03-07 21_51_40-index ts - gulpboilerplate - visual studio code](https://cloud.githubusercontent.com/assets/992536/13582908/0f73dd1a-e4af-11e5-8738-c3a164bdf4bb.png)

Same exact configuration, but on a path with spaces:
`Error: Debug adapter process has terminated unexpectedly`

Manually replacing `"sourceRoot":"c:\\gulp boilerplate/src-server/"` with `"sourceRoot":"/"` in source map and the debugger runs, but uses inline source map, therefore breakpoints don't get hit.
![2016-03-07 21_55_45-index ts - gulp boilerplate - visual studio code](https://cloud.githubusercontent.com/assets/992536/13582982/6a7c0dfe-e4af-11e5-9e7d-0c5a2cab7303.png)

```
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
```

**Comment by bruce965** [comment]
Still broken on Version 0.10.10 for me, will this fix be included with next release?

**Comment by weinand** [comment]
Please note that this fix will appear in the March release and is not in VS Code 0.10.10

**Comment by alexandrudima** [comment]
Verified by debugging a VS Code extension that uses sourcemaps and sits in a path with many spaces
