### ISSUE TITLE
task can not execute cmake properly

### ISSUE THREAD

**Issue by navono** [Microsoft/vscode#36679]
- VSCode Version: Code 1.17.2 (b813d12, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 16299.19
- Extensions:

| Extension | Author (truncated) | Version |
| ------| ------ | ------ |
| C/C++ | Microsoft | 0.14.0 |
| CMake | twxs | 0.0.17 |
| CMake Tools | vector-of-bool | 0.10.2 |
| QuickTask| Lky Tal | 3.0.2 |

Steps to Reproduce:

1.
computer environment:
- cygwin version: 2.881(32 bit)
- cmake-3.9.2-win64-x64

task.json:
```js
"version": "2.0.0",
  "tasks": [
    {
      "taskName": "CMake with g++",
      "type": "shell",
      "command": "cmake",
      "args": [
        "..",
        "-DCMAKE_CXX_COMPILER=g++",
        "-G \"Unix Makefiles\""
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
]
```
2.
when I execute the task, it shows the error:

CMake Error: Could not create named generator Unix

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.

...
---
But when I start a Poweshell, and execute the same command, everything works fine: 
PS D:\cpp-vscode\build> cmake .. -DCMAKE_CXX_COMPILER=g++ -G "Unix Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: C:/cygwin/bin/cc
-- Check for working C compiler: C:/cygwin/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/cygwin/bin/g++.exe
-- Check for working CXX compiler: C:/cygwin/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
cxx Flags:
-- Configuring done
-- Generating done
-- Build files have been written to: D:/cpp-vscode/build

---
Am I missing anything or the task execution environment is not same as Powershell?

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@navono the task execution environment is the same as the integrated terminal. Is this powershell for you. 

However I assume this is a space escaping issue. In general shell tasks shouldn't use args since it makes quoting escaping hard to control. You should even have a warning in the task output channel about this.

In your example I would say something like this should work:

```js
"version": "2.0.0",
  "tasks": [
    {
      "taskName": "CMake with g++",
      "type": "shell",
      "command": "cmake .. -DCMAKE_CXX_COMPILER=g++, -G 'Unix Makefiles'",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
]
```

Please note the single quotes around Unix Makefile. Alternatively you can escape a space in PowerShell with a back tick. Then it would read: `-G Unix``` Makefiles`

**Comment by navono** [comment]
@dbaeumer  Thank you for your reply. You're right. Put the command after cmake, it works.
Usually I just ignore the warning in the Output window and sometimes tasks works fine. e.g. cmd.exe.
