### ISSUE TITLE
vscode除了上部菜单栏，其余整个区域黑屏不显示任何东西。

### ISSUE THREAD

**Issue by kssoftwangwg** [Microsoft/vscode#36672]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|don|0.7.0
vscode-great-icons|emm|2.1.16
vscode-flake8|jay|0.0.4
vscode-clang|mit|0.2.2
mssql|ms-|1.2.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1

---

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/21151911/31849516-30118bae-b676-11e7-8c61-e7bc93d0d037.png)

Reproduces without extensions: Yes/No

**Comment by navono** [comment]
看下cpu高不高。我猜可能是扩展插件导致的。

**Comment by kssoftwangwg** [comment]
![image](https://user-images.githubusercontent.com/21151911/31852874-42dacff2-b6b2-11e7-810f-dfbde5052179.png)
从运行截图上看，CPU的占比不是特别高，内存消耗比较大。

**Comment by kssoftwangwg** [comment]
@navono ，谢谢支招：
![image](https://user-images.githubusercontent.com/21151911/31852890-71cee03c-b6b2-11e7-909b-d7bf27dd24e7.png)
从任务资源管理器的详细展示看，CPU的消耗并不高，内存效果占比高一些。不过这个vscode是卸载了原来的版本后重新安装的。

**Comment by kssoftwangwg** [comment]
@navono ，贼6...，是显卡的问题，我全局设置了使用英伟达显卡，看见vscode再打开时用了GPU引擎，后来我调整自动选择显卡，重新打开vscode就显示了...
![image](https://user-images.githubusercontent.com/21151911/31853013-45eee6d6-b6b4-11e7-9dc7-c1ffed2d1199.png)


![image](https://user-images.githubusercontent.com/21151911/31853017-5502a752-b6b4-11e7-9314-567440f6b3e1.png)

**Comment by navono** [comment]
解决就好。看起来好像vscode的渲染跟显卡设定有一定关系。

**Comment by octref** [comment]
/cc @Microsoft/vscode FYI since I saw a lot of Win / Nvidia / slow-freeze-crash issues.

Op sees blank screen with nothing rendered. He found the reason to be that he turned on Nvidia Graphics Card's GPU rendering for all apps. After removing that setting (and presumably VS Code falls back to integrated graphics card), VS Code works fine.

**Comment by bpasero** [comment]
See: https://github.com/Microsoft/vscode/issues/35527
