### ISSUE TITLE
bug: regex lookahead not working (search)

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#36687]
@rebornix 
- VSCode Version: Code - Insiders 1.15.0-insider (81e812c06540d1bd2636cf70ff7d0edd1bb0e866, 2017-07-21T13:15:10.775Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.1.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-mocha|Com|0.1.1
vscode-mocha-test-runner|cst|0.2.4
angular2-snippets|dan|1.0.16
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.10.1
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.11.1
tslint|eg2|0.17.0
vscode-npm-script|eg2|0.3.1
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.4.3
auto-rename-tag|for|0.0.14
vue-snippets|hol|0.1.5
search-node-modules|jas|1.2.0
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.4.0
vuejs-extension-pack|mub|0.2.1
vetur|oct|0.9.7
vuehelper|oys|0.1.0
language-stylus|sys|1.7.3
vscode-textlint|tai|0.5.0
babelrc|wad|1.0.0
gitblame|wad|2.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. ctrl+shift+f 搜索
2. 输入：http(?!s)

![image](https://user-images.githubusercontent.com/13050025/31854187-c5a13e34-b6c7-11e7-813f-f280136db719.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected, unfortunately our search tool doesn't support lookahead. From [the docs](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options), 

> While VS Code does support regular expression searches, backreferences, lookaround, and multiline matches are not supported. This is because VS Code depends on the search tool ripgrep, which, while extremely fast, doesn't support these advanced regex features.
