### ISSUE TITLE
Icons on open editor explorer get squashed for ignored files

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#36689]
- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T14:46:19.849Z)
- OS Version: Darwin x64 16.7.0

![cap](https://user-images.githubusercontent.com/4033249/31855640-e1f874ee-b663-11e7-8a8b-89dee0692355.gif)

**Comment by isidorn** [comment]
@jrieken did you do some wrong css magic with the label. Feel free to forward back to me

**Comment by jrieken** [comment]
I made it use flex-layout, so yeah maybe

**Comment by isidorn** [comment]
Maybe try adding to the icon
`flex-shrink: 0`
or 
`min-width: fit-content;`

**Comment by jrieken** [comment]
This is fixed with latest changes
