### ISSUE TITLE
Make top horizontal scrollbar larger

### ISSUE THREAD

**Issue by pevans360** [Microsoft/vscode#36684]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.4.0
Angular2|UVB|0.4.1

---

Steps to Reproduce:

1. Roll mouse pointer over the top horizontal scrollbar under the tabs
2. (a) Scrollbar is too narrow to be useful
    (b) It's really annoying when tabs on the left scroll out of view ... the most important file usually goes there.  So you want to get back to it, you can't see it and then have to deal with the annoying scroll bar.  
Liked the old VS way of handling this better.  

Reproduces without extensions: Yes/No

**Comment by up201505472** [comment]
What is exactly the desired outcome?

**Comment by pevans360** [comment]
Thanks for your response.  I think it's OK to close this issue.  

Was going to suggest making the scrollbar thicker (vertically) to make it easier to grab.  But discovered that the scroll wheel works to scroll through the tabs (which for me is easier to use and makes the scrollbar redundant).  The 'Open Editors' list is also a good alternative.

**Comment by up201505472** [comment]
still the scrollbar could become thicker

**Comment by pevans360** [comment]
Yes, for me thicker would be better.

**Comment by up201505472** [comment]
so you want it thicc ( ͡° ͜ʖ ͡°)
