### ISSUE TITLE
API: output.show() no longer supports ViewColumn 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3668]
But we still have it in our API.

**Comment by jrieken** [comment]
@isidorn You made changes there, right?

**Comment by isidorn** [comment]
@jrieken correct. After discussing with you we decided to leave the method call as deprecated for backwards compatibility https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2495

**Comment by jrieken** [comment]
@isidorn I know that, but I wonder what happened to the actual implementation of that method?

**Comment by isidorn** [comment]
@jrieken I see the implementation [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostOutputService.ts#L48)

**Comment by jrieken** [comment]
which looks decent. I will dig deeper

**Comment by isidorn** [comment]
ok, but I thought Ben is only complaining that the api is still there. I am not understanding what is the underlying issue here

**Comment by jrieken** [comment]
D'oh. Only reading the first half isn't good. Blame it on jet leg...

**Comment by jrieken** [comment]
Closing as _must keep for API compatibility_

**Comment by isidorn** [comment]
✈️

**Comment by bpasero** [comment]
@jrieken I suggest to still document the ViewColumn parameter is deprecated if possible.

**Comment by jrieken** [comment]
Agree - moving to @isidorn tho
