### ISSUE TITLE
Feature request: update on close

### ISSUE THREAD

**Issue by leonoverweel** [microsoft/vscode#36680]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Pro Version 1703 (build 15063.674)

Some Windows software, such as Paint.NET, has an option to "update on close" when a new update is available. The only way to make the update notification disappear in VSCode is to update now or dismiss the notification (and, in the latter case, probably forget to update by the time you finish working in the app).

It'd be great if VSCode could add an option to the update notification to install the update once the current VSCode session is closed.

**Comment by tiagosomda** [comment]
anyone working on this feature?

Current notification
![vs-code-update-notification](https://user-images.githubusercontent.com/1281399/47263362-f8e8ac80-d4b4-11e8-9c62-952d47231d56.jpg)

Suggested feature 
![vs-code-update-notification-new-feature](https://user-images.githubusercontent.com/1281399/47263367-10279a00-d4b5-11e8-98d0-72d3d9fa132e.jpg)

**Comment by joaomoreno** [comment]
Update on close is already the default.
