### ISSUE TITLE
[java] Syntax Highlighting broken by method header on more than one line

### ISSUE THREAD

**Issue by emilyeverett** [Microsoft/vscode#36688]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.5
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

Syntax highlighting is broken in the below code snippet:
``` Java
public static <M extends Map<Integer, String>> 
boolean TestGet(Supplier<M> c) {
 //TODO write unit test for get
 //Setup
 Map<Integer, String> map = c.get();
 return false;
}
```

Highlighting is fixed if full method header is on the same line:
```Java
public static <M extends Map<Integer,String>> boolean TestGet(Supplier<M> c){
//TODO write unit test for get
//Setup
Map<Integer, String> map = c.get();
return false;
}
```

Reproduces without extensions: Yes

**Comment by snjeza** [comment]
See redhat-developer/vscode-java#338

**Comment by aeschli** [comment]
I updated the Java grammar we use to the latest version from https://github.com/atom/language-java.
The issue looks fixed to me:
![image](https://user-images.githubusercontent.com/6461412/32001827-3b2097ec-b99b-11e7-87d1-7e22fcc696b3.png)

**Comment by snjeza** [comment]
@aeschli See https://github.com/Microsoft/vscode/pull/36786#issuecomment-339389126
