### ISSUE TITLE
Workspace doesn't restores itself on re-opening Code in Ubuntu 17.10 GNOME

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#36695]
Ubuntu 17.10 also provides older Unity interface, in which workspace gets restored on re-opening VS Code, but it doesn't happens in new GNOME UI unless a file modified isn't saved.

**Comment by ilyahoilik** [comment]
I can reproduce this as well

**Comment by bpasero** [comment]
I can reproduce but only when I launch VS Code from the task bar, not when running from the command line. All state (local storage) seems to be there, just not the window state (which folder was opened before). 

@Tyriar do you have any clue what could go on here?

**Comment by bpasero** [comment]
@Tyriar my first guess would be that clicking the icon in the dock puts the "`-n`" argument to the process and that is why we always open up empty.

**Comment by nunesvictor** [comment]
@bpasero I had the same problem.

Looking into the code.desktop file I notice this:

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.23

[Desktop Action new-window]
Name=New Window
Name[de]=Neues Fenster
Name[es]=Nueva ventana
Name[fr]=Nouvelle fenêtre
Name[it]=Nuova finestra
Name[ja]=新規ウインドウ
Name[ko]=새 창
Name[pt_BR]=Nova Janela
Name[ru]=Новое окно
Name[zh_CN]=新建窗口
Name[zh_TW]=開新視窗
Exec=/usr/share/code/code --new-window %F
Icon=code
```

The action 'new-window' is beeing triggered every time I click on the dock icon, when it supposed to behave like that only when the action is clicked. I figure if I remove the '--new-window' attribute from the Exec it will restore the workspace normally.

Maybe is a gnome dock issue or just an error on the desktop file syntax.

Hope I helped!

**Comment by Tyriar** [comment]
I'll check this out now

**Comment by Tyriar** [comment]
What appears to be happening is that "New Window" is now the default action for all applications in the new Gnome desktop manager. Since we had an additional action defined as "New Window", that is becoming the default due to the name.

**Comment by bpasero** [comment]
@Tyriar I am still seeing this, could this be a caching issue where I need to uninstall and reinstall?

**Comment by Tyriar** [comment]
@bpasero I was uninstalling and reinstalling the OSS build while testing the fix, there is a [desktop-file-install](https://github.com/Microsoft/vscode/blob/8025a1a6261ded894a8be5956e705cbc6588bfba/resources/linux/debian/postinst.template#L17) command which is meant to refresh it but it didn't seem to work reliably on Gnome.

**Comment by bpasero** [comment]
I can no longer reproduce, maybe the restart fixed it.

**Comment by jhpratt** [comment]
@Tyriar I'm unable to launch at all from the dock. I either have to open up the software center and click "launch" or do it from the command line. Could this be related?
