### ISSUE TITLE
File change highlight is too disturbing but can't turn off

### ISSUE THREAD

**Issue by tonghuashuo** [Microsoft/vscode#36697]
When I'm editing codes. The editor gives me highlights like below on changed lines.
<img width="671" alt="wx20171022-134320 2x" src="https://user-images.githubusercontent.com/6594276/31858681-6e498ce0-b730-11e7-98e2-a1b47ad27602.png">

It's good to have some hints on modified lines. But I think a little color bar around the line number should be enough. Highlighting the whole line is too strong for me. It's very disturbing if I made changes in different places. The editor looks like green / black zebra with so many highlighted lines (and it's always green with a plus icon regardless it's added / modified. and the plus icon overlays code folding icon visually, though the code folding feature still works)

- VSCode Version: 1.18.0-insider (found in latest upgrade. not sure it's today or yesterday)
- OS Version: macOS 10.13 High Sierra

Steps to Reproduce:
1. Open a file.
2. Make some change to the code. (then find it disturbing to see so many highlighted lines)
3. Can't find any switch on turning

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
An extension must add that, it's not the default behaviour. Can you disable all extensions and see if this solved the issue?
If not, please reopen.
