### ISSUE TITLE
MacOS merge windows not working

### ISSUE THREAD

**Issue by arielril** [Microsoft/vscode#36693]
The property of macOS to merge all windows is not working. It creates the local where it would be the merged windows but no window is there to switch.

- VSCode Version: 1.17.2
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Open more than one window of VSCode
2. Try to merge the windows that were opened.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35361
