### ISSUE TITLE
Explore a non-tilted icon on Mac

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#36692]
based on @donysukardi's comment here:  https://github.com/Microsoft/vscode/issues/6607#issuecomment-335664326

**Comment by franky47** [comment]
It seems logical, at a time where almost everyone moves to flatter & simpler-looking icons (Apple, Google, even Microsoft...), to stay in the same trend, rather than moving away from it by adding unnecessary complexity.

**Comment by Rylon** [comment]
I was actually quite pleased with the introduction of the tilted icon, as it feels like it better adheres to the Human Interface Guidelines for application icons on macOS:

https://developer.apple.com/macos/human-interface-guidelines/icons-and-images/app-icon/

Many (most?) of Apple's built-in applications still follow this convention of a slight tilt, even in the latest version.

**Comment by dlech** [comment]
Apparently Apple only follows their own HIG 1/2 of the time. I count 13 out of 26 Apple apps on my laptop have the tilt. I also count that only 4 out of 50 3rd party apps have the tilt (2 of which are Visual Studio, and a total of 6 if you count 2 that are tilted in the wrong direction).

Furthermore, the Mac icon for VSCode is also used on Linux. The GNOME Desktop also uses non-tilted icons. https://developer.gnome.org/hig/stable/icons-and-artwork.html.en

Likewise, elementary OS, which is a very Mac-like Linux distro, does the same. https://elementary.io/docs/human-interface-guidelines#iconography

**Comment by Rylon** [comment]
Haha true, they're not all tilted, but I think most of the utilities are (Mail, Notes, Reminders, TextEdit, Calendar, Contacts, Pages. You're right in that they don't seem to be following it consistently. I don't see a pattern of exactly what is tilted and what isn't 😆

**Comment by coreh** [comment]
Maybe the rectangle on the back could be tilted, but the VS Code logo could be straight?

**Comment by averzen** [comment]
I start used VS Code because I liked new tilted and orange icon!!! old icon was awful...

**Comment by TankedThomas** [comment]
I'm glad this is being looked into. Not sure why the Windows icons aren't just used for Mac. Looks fine to me.

**Comment by mklbtz** [comment]
First, I'd like to say that I really like the rectangle with the new blue color because visually mimics the actual window (dark gray window with blue accents, by default). I also appreciate that the VS Code team has made the effort to give us an icon that fits with the Mac platform. 👏 

However, one of the main issues I see is the dark rectangle tends to fade into other dark backgrounds, making it hard to pick out in a lineup.

![code logo](https://user-images.githubusercontent.com/1493623/32616643-d299c43a-c540-11e7-8dc0-6e6481d22a0a.png)

The Apple HIG — which are of course _just_ guidelines — mentions this effect specifically. Perhaps there's some way to incorporate this idea into the rectangle. 

> Consider adding a slight glow just inside the edges of your icon. If your app icon includes a dark reflective surface, such as glass or metal, add an inner glow to make the icon stand out and prevent it from appearing to dissolve into dark backgrounds.

Cheers and thanks for your hard work!

**Comment by heshuimu** [comment]
While every OS does start to make the icon and UI look "flatter", they did not abandon the "material" feel. You still see lightings and shadows, and that is how to make it look not like a 2D shape in a grid of 2D shapes on top a 2D wallpaper with zero depth. The current icon does just that, nothing much. 

The first icon VS Code ever had looks really out of place among all other softwares but now that we have this new icon that looks great on the Dashboard, I don't think I'll ever going back to background-less icons. Having an icon consistent with the OS human design have not been something I can even expect from a open source application. 

Plus, it does not looks small in Launchpad and Dock given that it already has a distinct color and shape.

**Comment by foresmac** [comment]
FWIW, I personally like the logo without the black tilted background as shown here: https://github.com/Microsoft/vscode/issues/6607#issuecomment-339807539

<img width="64" alt="screen shot 2017-11-09 at 1 44 52 pm" src="https://user-images.githubusercontent.com/3628189/32626171-328a71e2-c554-11e7-922b-71b97b63b1c6.png">

**Comment by user3587412** [comment]
I just wanted to say that I was pleased with this new icon for macOS as well. 

I thought this article did a great job in terms of classifying macOS icons into 4 types: http://macreplacementicons.com/articles/mac_app_icon_categories/

I do not agree with the sentiment that the rotation makes the icon look outdated; it fits the design language of macOS perfectly--the tilt is still a convention that Apple follows for their apps that "create things", which is exactly what we're doing with Visual Studio Code.

**Comment by jonathanherdt** [comment]
I have VSCode right next to Xcode and it looks like it belongs there, especially because of the tilt. I like it!
![screen shot 2017-11-10 at 10 23 21](https://user-images.githubusercontent.com/6302908/32651393-372a9378-c601-11e7-8373-f0e5335df2b1.png)

**Comment by adrientetar** [comment]
The tilt could totally be removed on Linux, there's no tilt convention there.

**Comment by lloeki** [comment]
[This analysis](http://martiancraft.com/blog/2014/07/inspecting-yosemite-icons/) of macOS (then OS X) icons is still worth a read. Heavily excerpted:

> ### The Shape Hierarchy
>
> #### The Circle
>
> The circle appears to be used for apps — light weight pieces of software; entertainment, or consumer focused products.
>
> #### The Square
>
> The square seems to be used for System-related utilities.
> 
> #### The Tilted Rectangle
>
> The tilted rectangle will be the most used shape out of these three. It’s used for Applications — tools to help you get work done

I'm entirely OK with the VSC tilted icon itself on a light dock. It just doesn't quite sit right with a dark dock: there ought to be some slight border for contrast or something, like the white icons on a white dock.

![screen shot 2017-11-13 at 09 38 57](https://user-images.githubusercontent.com/75445/32716491-889f1a24-c856-11e7-89aa-9ea7fa4b47f2.png)
![screen shot 2017-11-13 at 09 38 40](https://user-images.githubusercontent.com/75445/32716493-88ba3ac0-c856-11e7-91ee-1692b13a9b15.png)

Note: WRT the semantics of icon shape, the one that infuriates me the most is the SourceTree icon, which is a blue *circle*. In my mind it just doesn't make any sense, and every single time I can't find it! Now that I reread that article I can definitely see why.

**Comment by TankedThomas** [comment]
Wait, so no one liked the new icon and now that I say it's bad, people suddenly like it? Geez...

No, the tilted icon definitely looks terrible on Mac. It's too small, for starters, and the black just sort of disappears. The icon before was perfectly fine. It needs be to visible and blend in with the system more than anything else. The black doesn't really work. Even Terminal does a better job of blending in, with the silver border.

**Comment by lloeki** [comment]
> Wait, so no one liked the new icon

@TankedThomas My bad, I was ambiguous:

- I'm ok with VSCode being *a* tilted icon, not necessarily *that* titled icon.
- If it *has* to be a tilted icon, the icon is properly visible on a light dock, but it's definitely not good at all on a dark dock.

A particularity of tilted icons is that they represent *something*, with possibly an overlaying object at a different angle: a sheet, a page, a stamp, a calculator, sticky notes, [some window with code](http://www.macmaniacs.at/wp-content/uploads/2011/06/textmate-icon.png)... This one is a dark bland slab mount overlaid by an already busy logo at the same angle. What does that mean? There is no semantic purpose to that slab, it's *horror vacui* at that point. The mirrored alpha "fish" *wants* to be embedded into the mount but the overhanging, mirrored L combined with the slightly antagonistic shading just contradicts that, making the composition cognitively dissonant. So maybe the mirrored L itself is *horror vacui*, and the problem lies with being hell bent on building a [family identity from a visually uninteresting graphic element](https://code.visualstudio.com/blogs/2017/10/24/theicon) that **dominates** the composition.

> The icon before was perfectly fine

I disagree and find neither are OK, but for entirely different reasons.

**Comment by averzen** [comment]
@TankedThomas I liked new icon, it great. The previous icon was terrible. It was so ugly that I deleted VSCode from the system and came back to Sublime. And when I saw the new icon I tried Code again and now using it all time.

**Comment by pluma** [comment]
Can we maybe at least get the non-tilted version without background on Ubuntu? Here's how it would look with the default dark theme:

![logos of Google Play Music, Franz, Gnome Terminal, VS Code, Firefox Quantum and Nautilus in the Ubuntu side bar](https://user-images.githubusercontent.com/1280922/32951630-e07bfa76-cbaa-11e7-8810-499881ece435.png)

and in the activities panel:

![smaller version of the VS Code logo in the Activities switcher](https://user-images.githubusercontent.com/1280922/32951631-e094c75e-cbaa-11e7-9b75-e69997b6aa01.png)

**Comment by logicbus** [comment]
I have 22 icons in my dock.  Two are tilted: Visual Studio Code and (iOS Device) Simulator.  Everyone seems to have abandoned the tilt.  

I use VSC on Mac and Windows.  What if they just use the exact same icon on all OSes, just like almost every other app that is available on multiple OSes?

**Comment by cig0** [comment]
Like it's shown in @jonathanherdt screenshot, the problem isn't the tilt of the background shape but it's _orientation_.
Since VSCode is a developer tool, more associated to Xcode than to productivity tools like Calendar, Mail or notes, the background should be horizontally tilted, not vertically.

**Comment by lloeki** [comment]
> the background should be horizontally tilted, not vertically.

You mean landscape vs portrait? Because both are tilted the exact same way, standing on a grid rotated by 9°.

**Comment by cig0** [comment]
Hi @lloeki -- yes, exactly, landscape is what I meant. Thanks for the clarification :)

**Comment by piotrekkmt** [comment]
Agree that a big full scale icon would fit better between the rest of the giants in my Dock. There's an optical illusion that it's smaller even though it's not more different than the MacOS system icons. But if you're clicking the icon every single day you'd like it to be appealing and easy to find, would you not? 
Here's a great article about the perception of optically balanced icons 
https://medium.muz.li/optical-effects-9fca82b4cd9a

**Comment by jeffbax** [comment]
Could it be a user setting? I _much_ prefer the titled graphic... I think that the Windows-icon style (just the outline) looks terribly lost -- and at least for me I feel like most of my "document" applications are indeed titled:

<img width="68" alt="screen shot 2017-11-27 at 6 17 31 pm" src="https://user-images.githubusercontent.com/489946/33294619-73d2bd68-d39f-11e7-94ef-177d6d08b2a7.png">

Naturally, the highly non-native RubyMine bucks the trend...

I will probably change to the beta build just for the orange icon though... most docks are overwhelmingly blue as it is, so I'm sad to see blue become the standard.

**Comment by publicarray** [comment]
I'm fine with the tilt, but I do click sublime text's icon by accident ;) In my option the VS Code's icon background needs to be lighter to increase the contrast on a dark background.
![screen shot](https://user-images.githubusercontent.com/5497998/33524790-e8747ebc-d86e-11e7-8ede-f33095608dd0.png)

**Comment by averzen** [comment]
mat3224, on Mac you can change icon to whatever you want on any file, folder or app, just change it if you want it. I’m happy with current icon on dark theme.

**Comment by matt3224** [comment]
@averzen doesnt it get reset everytime you do an update?

**Comment by averzen** [comment]
@matt3224 if update replace whole app folder, it does, if only content it stay (if you assign icon to app_folder.app through info window.)

**Comment by christopherkang** [comment]
Did we come to a consensus on this? There will always be personal preference, but should we allow selection of tilted/straight icons or simply choose one to use universally?

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#updated-visual-studio-code-icon
