### ISSUE TITLE
can not  auto update

### ISSUE THREAD

**Issue by shijiebei2014** [Microsoft/vscode#36696]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.0.0

can not auto update!!!

**Comment by maxibanki** [comment]
Please provide us more information such as logs, behavior etc. Thanks :)

**Comment by PeterWAWood** [comment]
I also have this problem when running VSCode under a non-admin account on macOS. After clicking on Update Now, VSCode goes through the motions of updating itself, quits and reloads itself. Next time you run VSCode, it says that there is an update available and you can go through the process again ... and again.

At now time does VSCode open a dialog box to request Admin permission to update itself. (Which I guess is why the update silently fails.).

**Comment by joaomoreno** [comment]
@PeterWAWood https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150

Closing since there's no actual details here.
