### ISSUE TITLE
JavaScript Ternary Operator

### ISSUE THREAD

**Issue by Xzlash** [Microsoft/vscode#36691]
No support for Ternary operator in JavaScript, as the editor believes the `:` to be a ts type declaration.

![image](https://user-images.githubusercontent.com/31580218/31856255-7c686dc4-b68a-11e7-9a34-c7595b00040e.png)

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Hi,
if I understood your problem correctly, then it is no bug. I tried to execute your code from above `(m ? (): "")` in Google Chrome in which it was not working (eslint and jslint reported both also errors). So I think it is not valid JavaScript.
```javascript
var x = true ? 1 : 2; // works
var y = (m ? 1 : ""); // works
var z = (m ? (): ""); // 'types' can only be used in a .ts file.' + '=>' expected.
```
So I come to the conclusion that the `()` in the if statement isn't correct syntax.

**Comment by mjbvz** [comment]
Yes, `()` is not a valid expression in current JS
