### ISSUE TITLE
jsconfig.json validate module import seem to not find default 'index' file path

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode#36699]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0

---

My `jsconfig.json` :
```
{
  "compilerOptions": {
    "target": "ES6",
    "checkJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native"
  },
  
  "exclude": [
    "node_modules"
  ]
}
```
`foo.js`：
```
import { ApplicationStyles } from "app/themes"
```
The build-in js validator hint `[js] Cannot find module 'app/themes'.`

And I want to import `app/themes/index` default without the `index` suffix and validator error.

How can I config the `jsconfig.json` to achieve this?

**Comment by mjbvz** [comment]
You need to add `"module": "commonjs"` to your `compilerOptions`. This allows `index` files to be resolved when referencing the parent directory
