### ISSUE TITLE
pep8 package deprecated, use pycodestyle instead - "python.linting.pep8"

### ISSUE THREAD

**Issue by kurtlewis** [Microsoft/vscode#36706]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.4.0-96-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
java|red|0.10.0
---

Among the options for python code linting is pep8 - specifically under `python.linting.pep8`. This package [recently underwent a rename](https://github.com/PyCQA/pycodestyle/issues/466) to [pycodestyle](https://github.com/PyCQA/pycodestyle). This could create ambiguity for users, and as outlined in the pycodestyle transition plan, the `pep8` package will stop receiving updates, and could eventually be removed from pypi.

Steps to Reproduce:

1. None

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Due this is an extension specific issue, please create an issue in the [repository](https://github.com/DonJayamanne/pythonVSCode) of it.

**Comment by kurtlewis** [comment]
My apologies, I'll close this and open an issue there!
