### ISSUE TITLE
Windows and Mac Icon of VSC

### ISSUE THREAD

**Issue by AlfaDelta** [Microsoft/vscode#36701]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063

The new application icon of VSC is very ugly! On Windows but special on an Apple Macbook!
Please give me the previous very clear VSC icon back ;-)

**Comment by rcjsuen** [comment]
Duplicate of #35683.
