### ISSUE TITLE
Feature request: Ability to focus single folder in file explorer

### ISSUE THREAD

**Issue by edlahoz** [Microsoft/vscode#36709]
While working, would be pretty darn sweet if we could right click a folder and select an option like "Focused Folder/Directory" or something around those lines. 

What this would do is single out this selected directory in your file explorer while collapsing everything else. So you would only see what you are interested in your file explorer (while still having the option to see everything else). This is essentially a filter on the explorer.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28905
