### ISSUE TITLE
Icons are not correctly rendered in Open Editors pane

### ISSUE THREAD

**Issue by robertohuertasm** [Microsoft/vscode#36707]
![image](https://user-images.githubusercontent.com/696981/31865372-6b891c9e-b76e-11e7-97b5-c4e3fca57bac.png)

Steps to Reproduce:

1. Open a file
1. Modify it
1. Grab the left pane and shrink it until you get something similar to this.

![image](https://user-images.githubusercontent.com/696981/31865370-61b37e76-b76e-11e7-9e16-70d540defad3.png)

You can see below that depending on the file icon theme this can happen or not.

![left-pane](https://user-images.githubusercontent.com/696981/31865389-be399de2-b76e-11e7-873e-a6e7d01ab926.gif)

For more info you can see this issue [vscode-icons#1280](https://github.com/vscode-icons/vscode-icons/issues/1280).

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/36689#event-1304414773
