### ISSUE TITLE
Copy json from variable WATCH

### ISSUE THREAD

**Issue by dbauszus-glx** [Microsoft/vscode#36704]
It should be possible to copy variable values or json from a watched variable during debug. This is the one feature which makes me still need to use WebStorm where it is easily possible to copy JSON from the right click menu on a watched variable.

![image](https://user-images.githubusercontent.com/22201617/31862309-87d5ae70-b733-11e7-844a-3ab75c2de013.png)

Where as in Visual Studio Code there is merely the option to add / remove / edit a variable watch.

![image](https://user-images.githubusercontent.com/22201617/31862273-1c232e64-b733-11e7-8719-94bd35024e75.png)

Please log this as a feature request.

**Comment by isidorn** [comment]
There is already copy value action but only for simple exrpessions which have a value.
There is no "Copy JSON" thus leaving this feature request open

![screen shot 2017-10-23 at 11 07 53](https://user-images.githubusercontent.com/1926584/31881041-8a18968e-b7e2-11e7-8f65-8e769c98a798.png)

**Comment by dbauszus-glx** [comment]
There is a limit of 10000 characters on watchers. In the case of the JSON it would be neat of the limit could be configured. My objects are almost always longer than 10k characters.

**Comment by drdgvhbh** [comment]
I wanna give this a shot but is there a way to test the debugger in incremental mode? The debugger for the OSS vscode only works when I use the  `vscode-[platform]` command and run the exe.

**Comment by isidorn** [comment]
@drdgvhbh please keep in mind that this feature request does not have a help wanted label, which means that we are not 100% sure we want this.
Keep in mind that vscode debugger ux is language agnostic and adding a Copy JSON commands sounds too specific for JavaScript. I understand that JSON is used for more than just js but still it feels to js specific for me.

As for running the debugger in incremantal vscode you can see it here https://github.com/Microsoft/vscode/issues/20623#issuecomment-279969736

Sorry for missing documentation on this.
fyi @weinand we shuold probably add documention in 'How To Contribute' wiki on how to setup debugger for conitous development

**Comment by weinand** [comment]
What exactly is the definition of "Copy JSON" for arbitrary languages, e.g. C++?

The Debug Adapter Protocol (DAP) does not provide this functionality directly, so the (generic) implementation of this feature would have to live in the VS Code UI. It would use the existing primitive DAP requests to retrieve names and values of data structures and construct a JSON from them. I don't know how useful this JSON is for C++ developers...

I suggest to implement this feature as an extension.
@isidorn is it already possible to contribute an context action on watches and variables?

**Comment by isidorn** [comment]
@weinand I also had the same idea to be implemented by the extension but I thought the extensions can not access the keyborad.
Currently it is not possible to contribute for watches and variables but simply because we did not enable this due to the lack of use case

**Comment by weinand** [comment]
@isidorn why would an extension implementing "Copy JSON" need access to the keyboard?

**Comment by weinand** [comment]
copy to clipboard: see https://stackoverflow.com/questions/7778539/copy-to-clipboard-in-node-js

I've created feature request #36891

**Comment by dbauszus-glx** [comment]
Copy value would do to keep the function language agnostic. At the moment it is not possible to copy values from anything but string and strings are limited at 10000 characters in the watcher.

![image](https://user-images.githubusercontent.com/22201617/31996266-bc3ae100-b97f-11e7-8084-f931f7dc12c6.png)
