### ISSUE TITLE
Transfer Publishers in Marketplace

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3670]
Two questions that came up on [Twitter](https://twitter.com/ErichGamma/status/705309211736068096). 

1. Is it possible to transfer ownership? If not, can we get that added? 
2. How to add multiple users to a publisher account? 

I'm reaching out to the marketplace friends to find out the answer.

**Comment by waderyan** [comment]
Ping @hamenon

**Comment by hamenon** [comment]
We can technically transfer ownership of an extension, but just be aware that moving the extension under a different publisher will change the extension’s fully-qualified identifier. This could impact clients, like VS Code, that try to look up the extension by its old ID.

If the extension doesn’t have a lot of downloads, it might be easier to just remove from the old publisher and re-publish under the new publisher.

Following is an example shared by Erich Gamma where a change publisher was done by creating a new extension under the new publisher and deprecating the old one.

https://github.com/Microsoft/vscode-editorconfig/issues/23#issuecomment-184427296.

**Comment by hamenon** [comment]
Will get back to you soon on adding multiple users to the same publisher account.

**Comment by waderyan** [comment]
@gep13 see above.

**Comment by gep13** [comment]
@waderyan thanks! I have set up a subscription on this issue now, and will follow along with it.  Let me know if there is something you want me to test out.

**Comment by gep13** [comment]
The extension in question is this one:

https://marketplace.visualstudio.com/items?itemName=cake-build.cake-vscode

The publisher ID is what we want, i.e. cake-build, however, the publisher exists under @patriksvensson own account.  Ideally, we would want to move the publisher under an account that we (the Cake development team) all have access to.  Thanks!

**Comment by hamenon** [comment]
@gep13 you can edit a publisher now and add multiple users into the same publisher. On the publisher page click on the edit publisher options from the drop down. 

![image](https://cloud.githubusercontent.com/assets/13758921/13981737/ebd2dbd6-f10b-11e5-9447-1c985c7ea40a.png)
![image](https://cloud.githubusercontent.com/assets/13758921/13981839/83393966-f10c-11e5-9d5c-9619d20e6e71.png)

You can then add multiple users under different roles. The roles are:

•	Reader – can see the publisher in the publisher drop-down and view all of its extensions
•	Creator – can see the publisher and can upload new extensions (but cannot delete other extensions)
•	Contributor – everything a reader can do, plus the ability to upload new and delete existing extensions
•	Owner – everything a contribution can do, plus the ability to manage roles

Do let me know if this helps.

**Comment by gep13** [comment]
@hamenon this sounds like exactly what we need.  We will give this a try, and let you know how it goes!
