### ISSUE TITLE
Using Intellij Shortcuts.  Cmd + Y to delete line does not work

### ISSUE THREAD

**Issue by justanirudh** [Microsoft/vscode#36713]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.5.5
vscode-elixirc-mix-linter|PTD|0.0.3
latex-preview|ajs|0.5.1
intellij-idea-keybindings|k--|0.2.15
vscode-elixir|mjm|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please file this issue against the intellij keybindings extension: https://github.com/k--kato/vscode-intellij-idea-keybindings/issues
