### ISSUE TITLE
Scrollbar theming options

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#36714]
I can't seem to find how to change the indications in the scrollbar. In my specific case, I'd like to make the found items much more visible:

![image](https://user-images.githubusercontent.com/8936090/31867210-73baf99c-b78b-11e7-8f8a-7060181bd454.png)

Is it possible?

**Comment by aeschli** [comment]
Try 
```
    "workbench.colorCustomizations": {
        "editorOverviewRuler.findMatchForeground": "#ff0000"
    }
```

Check out the 'Overview ruler' section in https://code.visualstudio.com/docs/getstarted/theme-color-reference for all overview ruler colors.

**Comment by nmaxcom** [comment]
Thanks, that's precisely it. I'm not a native speaker, so I don't know if it's just me or "OverviewRuler" is a name not directly inferable from "scrollbar" (where the actual thing happens)?
