### ISSUE TITLE
When I press the Terminal + icon, support it will open a new terminal, but it open a shortcut for "switch the workspace project".

### ISSUE THREAD

**Issue by coderkk** [Microsoft/vscode#36719]
- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T15:35:45.848Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.0.5
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
mssql|ms-|1.2.0
vetur|oct|0.10.1
laravel-blade|one|1.9.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.3.4
laravel-artisan|rya|0.0.8
vscode-workspace-switcher|sad|1.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. click the '+' in integrate terminal
2. it open switch the workspace project" instance of  new terminal.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
This is a new feature, if you're in a multi-root workspace you will be able to select the workspace to launch the terminal in
