### ISSUE TITLE
Markdown preview doesn't syntax highlight tsx

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#36711]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.3.2
python|don|0.7.0
tslint|eg2|1.0.11
prettier-vscode|esb|0.24.0
csharp|ms-|1.12.1
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.4.0
Ruby|reb|0.15.0
java|red|0.12.0
stylelint|shi|0.30.0

---

Steps to Reproduce:

1. Create a `.md` file with a <code>```tsx</code> block:
![image](https://user-images.githubusercontent.com/3335181/31865648-18ff3bbc-b727-11e7-956e-90a15738bf48.png)

2. Open a preview view on that `.md` file:
![image](https://user-images.githubusercontent.com/3335181/31865655-2ae2945a-b727-11e7-9ab8-a7ba4a4c4ac1.png)

Note that it does correctly highlight <code>```ts</code> and <code>```typescript</code> blocks.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/isagalaev/highlight.js/issues/1155
