### ISSUE TITLE
Add support for "e.key" keybindings in extension's `contributes.keybindings`

### ISSUE THREAD

**Issue by aioutecism** [microsoft/vscode#3671]
I'm encountering this problem when dealing with different keyboard layout in extension.

Say I have these in my extension's `package.json`:

``` json
{
  "contributes": {
    "keybindings": [
      {
        "key": "\\",
        "command": "myExtension.backSlash"
      }
    ]
  }
}
```

I'm trying to map `\` here.
However, what VSCode actually does is map `VK_OEM_5` to `myExtension.backSlash`.
Therefore, I get `\ => myExtension.backSlash` on US keyboard (which is correct) but `# => myExtension.backSlash` on British keyboard (which is wrong), which is not correct.

I've done a workaround to deal with different keyboard layouts [here](https://github.com/aioutecism/amVim-for-VSCode/pull/45).
But users have to add a setting in configuration in order to tell the extension the layout they are using.
This is troublesome and extension shouldn't do all the handling of keyboard layout.

**Comment by aioutecism** [comment]
Also, the [dead key problem](https://github.com/aioutecism/amVim-for-VSCode/issues/23#issuecomment-191720007) will be solved too if "real key" binding is possible.

**Comment by erikbra** [comment]
https://github.com/aioutecism/amVim-for-VSCode/pull/46 (I didn't manage to test it - low skills developing Code plugins :))

**Comment by aioutecism** [comment]
Thank you @erikbra!
I leaved some comments #46.

**Comment by alexandrudima** [comment]
https://github.com/alexandrudima/vscode-vim shows how to better handle keyboard input in the case of a vim extension

**Comment by aioutecism** [comment]
Well, yes, listening to `type` event can solve the layout problem of vim extension.
But, if an extension want to add custom function when `cmd+\` is pressed, we still need to deal with different keyboard layout since `cmd+\` is not passed to `type`.
Having `type` event gives developers a workaround for some problem. But doesn't solve the problem that keybinding settings is not binding the "real" key.

**Comment by alexandrudima** [comment]
Unfortunately, all the commands of vscode itself have the same limitation. This is not a limitation we have added, [it was a design choice done by w3c when they drafted the `keydown` event specification](https://www.w3.org/TR/DOM-Level-3-Events/#determine-keydown-keyup-keyCode).

[We can revisit this one Chromium decides to implement KeyboardEvent.key in a correct way](http://caniuse.com/#search=KeyboardEvent.key), so it is ok with me to keep this open as a tracking issue.

**Comment by aioutecism** [comment]
Thanks! Looking forward to the fix.
