### ISSUE TITLE
Color previews don't show in .sass files.

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#36724]
When I write a color code (name, hexa, rgb, or rgba) a nice preview is showed, which on hover expands into a nice color picker. I love this handy feature, but unfortunately it doesn't work in .sass files the way it works in .scss or .css files.

![Color Previews](https://i.imgur.com/RQEkdHR.png)

**Comment by aeschli** [comment]
We don't have built-in SASS support, but SASS support come in through extensions. So to make this happen, this should be filed against one or several SASS extensions.
