### ISSUE TITLE
Close folder closes all open documents

### ISSUE THREAD

**Issue by tomkerkhove** [Microsoft/vscode#36726]
# Version

- VSCode Version: 1.17.2

Reproduces without extensions: Yes

# Description
When opening VS Code on a folder, you can create & store a file on a different location - This is perfect.
However; when choosing the "Close Folder" option, it closes all open documents as well, even if they are not part of that folder.

# Repro
Steps to Reproduce:

1. Open folder on c:\repro
2. Create new file
3. Save new file on c:\docs
4. Close folder on c:\repro

**Comment by bpasero** [comment]
Closing "as designed". We might revisit this at a later point in time.

**Comment by tomkerkhove** [comment]
May I ask why this is by design? It doesn't really make sense to me that you close other files outside of the open folder as well..
