### ISSUE TITLE
Provide convertion to lower javascript standard

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#36723]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04
![image](https://user-images.githubusercontent.com/8751130/31872758-143661da-b7f1-11e7-907b-f3a930a66241.png)

I notice that we could convert from prototype based class to es2015 class. The light bulb option shows up when we place the cursor at the function name. Can we have the other options to convert from es2015 class to the lower standard like es3?

**Comment by mjbvz** [comment]
Converting newer JS conventions to older es3 or es5 code is really much better suited for a transpiler like babel. 

Closing this as implementing it properly would be a non-trivial amount of work and I don't see it adding much value
