### ISSUE TITLE
insiders SCM bug

### ISSUE THREAD

**Issue by jeasonstudio** [Microsoft/vscode#36721]
- VSCode Version: 1.18.0-insider (1.18.0-insider)
- OS Version: macOS 10.13

Steps to Reproduce:

1. `Fix-Bugs` and `New-Feature` are both UnCommit file, something wrong with file `Fix-Bugs`'s color.

![image](https://user-images.githubusercontent.com/17971291/31871408-aa905046-b779-11e7-8484-ef9904d79cd4.png)

![image](https://user-images.githubusercontent.com/17971291/31871458-13b048e2-b77a-11e7-9e4b-1841b2d477e8.png)

Reproduces without extensions: Yes

**Comment by jeasonstudio** [comment]
![image](https://user-images.githubusercontent.com/17971291/31926186-a03cdb44-b852-11e7-81e2-fde8f425b81d.png)
`SourceTree` shows that I have `Uncommitted changes`, but vscode gives me the wrong result.
Btw, what's that scrolling at the bottom of `SOURCE CONTROL` ? @joaomoreno 

Git outputs:

```
git remote --verbose
git show :app/config/index.js
git fetch
git status -z -u
git symbolic-ref --short HEAD
git rev-parse MISPEECH-47
git rev-parse --symbolic-full-name --abbrev-ref MISPEECH-47@{u}
git rev-list --left-right MISPEECH-47...origin/MISPEECH-47
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git status -z -u
git symbolic-ref --short HEAD
git rev-parse MISPEECH-47
git rev-parse --symbolic-full-name --abbrev-ref MISPEECH-47@{u}
git rev-list --left-right MISPEECH-47...origin/MISPEECH-47
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git status -z -u
git symbolic-ref --short HEAD
git rev-parse MISPEECH-47
git rev-parse --symbolic-full-name --abbrev-ref MISPEECH-47@{u}
git rev-list --left-right MISPEECH-47...origin/MISPEECH-47
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git fetch
git status -z -u
git symbolic-ref --short HEAD
git rev-parse MISPEECH-47
git rev-parse --symbolic-full-name --abbrev-ref MISPEECH-47@{u}
git rev-list --left-right MISPEECH-47...origin/MISPEECH-47
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git status -z -u
git symbolic-ref --short HEAD
git rev-parse MISPEECH-47
git rev-parse --symbolic-full-name --abbrev-ref MISPEECH-47@{u}
git rev-list --left-right MISPEECH-47...origin/MISPEECH-47
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
```

**Comment by jrieken** [comment]
@jeasonstudio You were likely hit some "work-in-progress"-issues. Can you try again with latest insiders has many things have changed by now. Thanks
