### ISSUE TITLE
enlarge margin of "Discard All changes" and "Stage All changes"

### ISSUE THREAD

**Issue by suixudongi8** [Microsoft/vscode#36727]
- VSCode Version:1.17.2
- OS Version:Mac OS high sierra.

Steps to Reproduce:

1.for now, the margin of "Discard All changes" and "Stage All changes" in git extension are too close. It is very easy to have a wrong click. Shall we enlarge the margin?

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you show me a screenshot?
