### ISSUE TITLE
Change modified file badge in the explorer tab for consistency

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#36729]
- VSCode Version: Code - Insiders 1.18.0-insider (65c08338e4bece35fb53f5a1cdf56d30b7706157, 2017-10-20T15:35:45.848Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
xml|Dot|1.9.2
Go|luk|0.6.66
code-beautifier|mic|1.7.2
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Use in the explorer opened files list the modified svg badge from the source control tab instead of a new creation.

My suggestion:
![image](https://user-images.githubusercontent.com/17984549/31877227-f71d0fe2-b7d5-11e7-9c9d-5993f680637c.png)

For testing, add these css values to the modified element and remove the class `monaco-decorations-style-2`.
```css
background-image: url(/resources/app/extensions/git/resources/icons/dark/status-modified.svg);
background-repeat: no-repeat;
```

Current design:
![image](https://user-images.githubusercontent.com/17984549/31877299-3d6db05a-b7d6-11e7-8b72-cca5c80fabfa.png)

**Comment by jrieken** [comment]
Yes, we have done that yesterday and aligned both representations. Tho we did pick a lighter design based on user feedback. See https://github.com/Microsoft/vscode/issues/178#issuecomment-339077269 for more details.

**Comment by maxibanki** [comment]
Thanks, but what do you think about adding a right margin (2px) to the 'U' element, that it looks like that:
![image](https://user-images.githubusercontent.com/17984549/31991316-c526d5c4-b977-11e7-9aeb-caca9e30b9d6.png)
Instead of
![image](https://user-images.githubusercontent.com/17984549/31991322-c7591e88-b977-11e7-8a44-b4ae3c8d1971.png)
Because the 'M' icon is wider than the 'U' icon.

**Comment by jrieken** [comment]
Tricky... That is rendered as text with the option for more text...
