### ISSUE TITLE
[json] provide code assist for $schema

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3673]
On Mac OS X El Capitan, I tried to author a new JSON document, using the new ARM extension for Visual Studio Code. I'm not getting Intellisense suggestions for Azure Resource Manager resources.

I'm assuming that the `$schema` property is required, but I'm not getting any assistance for how to add the schema version, or which schema versions are valid. 

<img width="300" alt="screen shot 2016-03-03 at 8 15 37 am" src="https://cloud.githubusercontent.com/assets/466713/13498674/2bde6488-e118-11e5-953a-2c5d565c8028.png">

<img width="291" alt="screen shot 2016-03-03 at 8 24 42 am" src="https://cloud.githubusercontent.com/assets/466713/13499013/a767bdba-e119-11e5-8fa9-b18309614d74.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by aeschli** [comment]
yes, there needs to be a schema file association. Either using $schema, in the settings, or by an extension.
https://code.visualstudio.com/docs/languages/json#_json-schemas-settings for more information and examples.

You are saying that you are using the ARM extension. If there's a clear association of file name to schema, then they should declare that association in their extension. Is 'VirtualNetwork.json' a file name you picked or is it a default name? If it's a default name I'd move the issue to the ARM extension team.

We have no code assist for $schema. That's a good idea, but there's an open number of schemas around, so in the end you as the user will have know the schema URL to validate against,

**Comment by pcgeek86** [comment]
@aeschli Yeah, I would assign this over to that team. `VirtualNetwork.json` is a file name that I chose. How would the file name matter though? An ARM JSON template file can have any file name, as long as it ends with the `.json` file extension.

My recommendation here is that the ARM VSCode Extension team adds support for completing the `$schema` property.

**Comment by aeschli** [comment]
But we can not associate all JSON files with the ARM schema by default. There's plenty of other json files around which are not ARM configuration files.

I'll change this issue as a request to provide code assist for $schema then,

**Comment by pcgeek86** [comment]
@aeschli I understand that you can't assume ARM by default, given that JSON is generic. I don't know exactly what the right solution is, but having nothing certainly isn't one. :smile:
