### ISSUE TITLE
Top Extension Recommendation

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#36739]
#FeatureRequest Please add a editors choice or plugin recommendations. It will help developers to find the best Extension for their requirements.

**Comment by ramya-rao-a** [comment]
@prasanthnv We currently do have recommendations based on the types of files you have been working on.
Run the command `Extensions: Show Recommended Extensions` to see what has been recommended for you.

We will continue to improve this experience in the future.
Closing this issue for now.
