### ISSUE TITLE
Terminal text vertically clipped

### ISSUE THREAD

**Issue by andyli** [Microsoft/vscode#36734]
VSCode version:
```
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Using Ubuntu Xenial (16.04), installed fonts (using `apt-get`): `fonts-noto`, `fonts-dejavu`

Using `"editor.fontFamily": "'Noto Mono'"`, `"terminal.integrated.fontSize": 14`, notice how the bottom of the letter `g` is clipped:
![screenshot from 2017-10-23 16-37-47](https://user-images.githubusercontent.com/103977/31879855-49a6f3aa-b811-11e7-92d4-5bddc5b08d0e.png)

Using `"editor.fontFamily": "'DejaVu Sans Mono'"`, `"terminal.integrated.fontSize": 14`, running `echo ____`, notice how the underscore character `_` is completely invisible:
![screenshot from 2017-10-23 16-51-28](https://user-images.githubusercontent.com/103977/31880263-8b6e7e60-b812-11e7-9e59-356340722051.png)

The problem only happens in the terminal panel but not in the file editing area, despite they're using the same font with the same font size. Adjusting `"terminal.integrated.lineHeight"` has no effect on the clipping issue.

**Comment by robbiespeed** [comment]
Same issue on Fedora 25
```
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
```
Using "Source Code Pro" as the terminal font mitigates this issue though.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
