### ISSUE TITLE
DirtyDiffModel reacts incorrectly to new diff computations

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#36730]
AFAICT this is a regression introduce with 90fc26ca2cea6a0036c9d2d723d67e7536e00613 and the usage of `sortedDiff`.

Stage a file with the contents:
```
Line 1
Line 2
Line 3
Line 4
```

Modify the file to have the contents:
```
Line 1
Line 2
Line 2.5
Line 3
Line 4
```

Observe correct dirty-diff:
<img width="141" alt="image" src="https://user-images.githubusercontent.com/5047891/31877651-a04555d8-b7d7-11e7-80eb-aed160c040d9.png">

Press Enter after `Line 2.5`.

Observe the dirty-diff does not update:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/5047891/31877763-025b62b2-b7d8-11e7-960f-f769caf148bd.png">

 because `arrays.sortedDiff` is incorrect or perhaps invoked incorrectly:
```
old changes: [{"originalStartLineNumber":2,"originalEndLineNumber":0,"modifiedStartLineNumber":3,"modifiedEndLineNumber":3}]
new changes: [{"originalStartLineNumber":2,"originalEndLineNumber":0,"modifiedStartLineNumber":3,"modifiedEndLineNumber":4}]
result: diff is an empty array
```

**Comment by joaomoreno** [comment]
Great catch!
