### ISSUE TITLE
code command does not work correctly only in WSL filesystem

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#36737]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Version: 1709 Build: 16299.19

Steps to Reproduce:

1. Open WSL with `bash` or `ubuntu` command
2. Go to "~"
3. Then:
     - mkdir my-project
     - cd my-project
     - touch index.js
    - code .

After this steps, VSCode runs with all contents of Windows `Desktop/` directory. But if I will run `code  .` in any folder in Windows filesystem, for example in `/mnt/c/Users/User/Desktop/my-project` it opens VSCode correctly.

Reproduces without extensions: Yes

**Comment by jeasonstudio** [comment]
This is my issue, #29812
I think vscode should greatly improve the support for wsl.

**Comment by Zx-EvM** [comment]
Any ideas why it happens and how can we fix this?

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/32717

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13138

**Comment by Zx-EvM** [comment]
@Tyriar why duplicate? I talking about correctly running VSCode that installed in Windows with running `code` command in `WSL` environment.

But in https://github.com/Microsoft/vscode/issues/13138 issue we are talking about running VSCode installed in WSL.
