### ISSUE TITLE
vscode while be die when directory has rar file

### ISSUE THREAD

**Issue by luogui495186** [Microsoft/vscode#36736]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
phpcs|ika|0.7.0
format-php|Kas|1.1.2
net-core-project-manager|ksu|0.3.6
csharp|ms-|1.12.1
vscode-icons|rob|7.16.0
html5-boilerplate|sid|1.0.1
php-formatter|Sop|0.2.4
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you explain some more? What does vscode do when you open a folder with a rar file? Can you share the rar file?

**Comment by luogui495186** [comment]
https://github.com/luogui495186/jd-pid-front.git
this is my project 
1.vscode can not open the project directory 
2.if remove "sort-select.rar"  file  vscode  works very

**Comment by roblourens** [comment]
Can you try from the command line, with the `--verbose` flag?

**Comment by luogui495186** [comment]
when open my project the vscode exit.i can not do anything

**Comment by roblourens** [comment]
If you launch code from the command prompt, like

```
cd <your project>
code --verbose .
```

then it may print some extra debugging information to the console which will be useful.

**Comment by roblourens** [comment]
Please also try with `--disable-extensions`. It works for me in windows.

**Comment by luogui495186** [comment]
"code --verbose ."information 
[90m[main 09:33:46][0m Starting VS Code in verbose mode
[90m[main 09:33:47][0m from: d:\Program Files (x86)\Microsoft VS Code\resource
s\app
[90m[main 09:33:47][0m args: { _: [ 'E:\\jd-pid-front-github' ],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false }
[90m[main 09:33:47][0m Unable to read folders in C:\Users\sqluogui\AppData\Roa
ming\Code\Workspaces (Error: ENOENT: no such file or directory, scandir 'C:\User
s\sqluogui\AppData\Roaming\Code\Workspaces').
[90m[main 09:33:49][0m IPC#vscode-machineId
[2720:1024/093352.325:INFO:CONSOLE(29)] "[C:\Users\sqluogui\.vscode\extensions\x
abikos.javascriptsnippets-1.5.0]: 鈥渃ontributes.JavaScriptSnippets.language鈥濅
腑瀛樺湪鏈煡鐨勮瑷€銆傛彁渚涚殑鍊? vue", source: file:///D:/Program Files (x
86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (29)
[90m[main 09:33:52][0m IPC#vscode-workbenchLoaded
[2720:1024/093353.564:INFO:CONSOLE(28)] "%c[Extension Host] %cvscode-icons is ac
tive! %c(at activate (C:\Users\sqluogui\.vscode\extensions\robertohuertasm.vscod
e-icons-7.16.0\out\src\index.js:40:13))", source: file:///D:/Program Files (x86)
/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (28)
[91m[main 09:33:54][0m [VS Code]: render process crashed!
[90m[main 09:43:34][0m Lifecycle#window-all-closed
[90m[main 09:43:34][0m Lifecycle#before-quit
[90m[main 09:43:34][0m App#will-quit: disposing resources

**Comment by roblourens** [comment]
Thanks. Can you also try with `--disable-extensions`?

**Comment by luogui495186** [comment]
code --disable -extensions.
his no information but open new vscode window

**Comment by roblourens** [comment]
Did it open the window with the rar file? Did it crash? Can you try `code --disable-extensions --verbose .`?
