### ISSUE TITLE
Code Insiders constantly prompts authorization on MacOS

### ISSUE THREAD

**Issue by rogerkerse** [Microsoft/vscode#36741]
- VSCode Version: 1.18.0-insider
- OS Version: 10.13.1 Beta

Steps to Reproduce:

1. Open some project that I have downloaded with Sourcetree and leave it open with some file opened.
2. Sometimes when alt+tab-ing back into code insiders, it prompts popup asking to put in computer credentials to give access to bitbuckets credentials I think.

Even if I click 'Always allow', it still happens again and again and again...

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
You can disable auto fetch with `"git.autofetch": false`. It will be disabled by default soon.
