### ISSUE TITLE
Add folders with right click `Open with Code`

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#36747]
Currently Code either opens a new window or replaces the existing one (`"window.openFoldersInNewWindow": "off"`) when opening a folder with the `Open with Code` right click option on Win. Instead, I would like for Code to simply add a folder in my already existing window.

A new option maybe? `"window.openFoldersInNewWindow": "add"`

**Comment by bpasero** [comment]
Lets merge this into https://github.com/Microsoft/vscode/issues/34784
