### ISSUE TITLE
Error upgrading deb package from VS Code Insiders repository

### ISSUE THREAD

**Issue by edwinksl** [Microsoft/vscode#36742]
- VSCode version: Code - Insiders 1.18.0-insider (4b01451cea60f32412098735709fddcac567b33d, 2017-10-19T08:25:22.140Z)
- OS version: Ubuntu 17.04 (Linux x64 4.10.0-38-generic)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.7.1
latex-workshop|Jam|3.5.5
---

Steps to reproduce:

Running `sudo apt update && sudo apt upgrade` to upgrade the VS Code Insiders build gives the following messages:
```
Preparing to unpack .../code-insiders_1.18.0-1508736309_amd64.deb ...
Unpacking code-insiders (1.18.0-1508736309) over (1.18.0-1508401646) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/code-insiders_1.18.0-1508736309_amd64.deb (--unpack):
 cannot copy extracted data for './usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserverlibrary.js' to '/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserverlibrary.js.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/code-insiders_1.18.0-1508736309_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Reproduces without extensions: Yes

**Comment by edwinksl** [comment]
This looks like https://github.com/Microsoft/vscode/issues/35703 all over again.

**Comment by shirishkz** [comment]
yup, facing the same issue here

**Comment by AwakenedOne** [comment]
Same issue here.

**Comment by edwinksl** [comment]
I just tried to update again and it looks like the problem has been automagically fixed.
