### ISSUE TITLE
[erb] support for erb syntax highlighing

### ISSUE THREAD

**Issue by jian-leopoldo** [Microsoft/vscode#36749]
- VSCode Version: 1.17.2
- OS Version: Xubuntu 16.04

Problems i´ve found:

1.The problem is in the Ruby archives, on Rail´s views.  The close´s tag to show data  in HTML its feels like a string code . Something like this "%>" without quotes.
2.JavaScript Syntax color in Ruby on Rails archives  doesn´t work properly .

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Can you please share some example code for these issues so that we can investigate this?

**Comment by jian-leopoldo** [comment]
the first error is something like this(close´s tag share the same strings color): 
![vscod_issue](https://user-images.githubusercontent.com/25981646/31961178-bdf90cf8-b8d8-11e7-8bc5-0f9f284f2385.png)
in the second error the ruby syntax does not work in "javascript.js.erb", something like this:  .
![vscode_issue2](https://user-images.githubusercontent.com/25981646/31961510-b3fa1d68-b8d9-11e7-8b5c-9c5d2fa9bf07.png)

**Comment by aeschli** [comment]
The problem is that the `<%` syntax is not valid in html.

Did you check the [marketplace for erb](https://marketplace.visualstudio.com/search?term=erb&target=VSCode&category=All%20categories&sortBy=Relevance) extensions?

**Comment by jian-leopoldo** [comment]
I've tried a lot of extensions nothing work properly.

**Comment by aeschli** [comment]
Please file issues against the extension so they can get better.
