### ISSUE TITLE
Virtual names on folders

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#36746]
A lot of projects I work on have a subfolder named e.g _Sw_, _trunk_ or _DSP_ which makes it inconveniant to have multiple folders open at once.

```
[Proj1]
    [Doc]
    [Sw] <--
[Proj2]
    [Doc]
    [DSP] <--
    [Rel]
[Proj3]
    [Doc]
    [Pw]
    [trunk] <--
```

It's not very efficient to open projects at top level as this reveals too many hierarchical levels.

Would love some way of virtually renaming the opened folders.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by csholmq** [comment]
:(
