### ISSUE TITLE
issue in showing terminal when increasing the font size 

### ISSUE THREAD

**Issue by LordST95** [Microsoft/vscode#36743]
- VSCode Version: 1.17.2
- OS Version: kali
this is my setting:
{
    "window.zoomLevel": 2,
    "liveServer.settings.donotShowInfoMsg": true
}
and the image below shows the terminal
![image](https://user-images.githubusercontent.com/10278253/31886244-68744d0c-b800-11e7-801a-54114b9ec887.png)

**Comment by Tyriar** [comment]
Same root cause as https://github.com/Microsoft/vscode/issues/36322, try changing your font as a workaround
