### ISSUE TITLE
The name "Con" is not valid as a file or folder name

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#3674]
I was going to create a folder named `Console`, and I noticed that when I typed `Con` it gave an error saying I can't create a folder with the name `Con` (case insensitive). As you can see from the image, it isn't because there already is a folder named `Con`. I haven't come across this for other folder names yet though.

![vscode-file-error](https://cloud.githubusercontent.com/assets/1571806/13499524/62f576bc-e124-11e5-9771-93553a9e0531.png)

**Comment by bpasero** [comment]
"Con" is invalid, see https://msdn.microsoft.com/en-us/library/aa365247
