### ISSUE TITLE
Proxy Authentification Frame shows menu bar and is glitched because of it

### ISSUE THREAD

**Issue by qrybe** [Microsoft/vscode#36751]
![Demo Image](https://user-images.githubusercontent.com/18246089/31893458-dea28bb4-b80b-11e7-96dc-b3fc89efeaa7.png)
When you get asked for a password, the default electron menubar occurs on top which breaks the design of the frame. 

- VSCode Version: 1.17.2
- OS Version: Windows 10 

Steps to Reproduce:

1.  set a windows proxy with authentification in the settings
2.  wait until the question asking for login credentials occurs

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@bpasero This could be an Electron regression.

**Comment by roblourens** [comment]
@joaomoreno Where can I find a proxy that requires authentication?

**Comment by chrmarti** [comment]
Verified with a local squid proxy.
