### ISSUE TITLE
Debug adapter can't enable ExceptionBreakpointFilters by default

### ISSUE THREAD

**Issue by rick111111** [Microsoft/vscode#3675]
Because of some recent changes now debug adapter must provide default ExceptionBreakpointFilters, however there seems to be no way to enabled some or all of these filters by default. It's kind of unexpected for user that the "Unhandled Exceptions" filter is disabled by default.

Related:
https://github.com/Microsoft/vscode/issues/3015#issuecomment-185403965
https://github.com/Microsoft/vscode/commit/c676ceb7333eb43a1d9a95f9841901e7dbe929de

**Comment by isidorn** [comment]
You are right, currently it is not possible for an adapter to say that an exception breakpoint should be enabled by default.
Forwarding to @weinand to decide if we want to introduce this to the protocol, and if we decide to introduce it then I can add it on the vscode side

**Comment by weinand** [comment]
Makes sense. Will try to add this for March.

**Comment by weinand** [comment]
@daviwil @felixfbecker @lukehoban @rkeithhill @gregg-miskelly
you can now control whether an exception filter is enabled or disabled by returning an attribute `default` for the exceptionBreakpointsFilter capability.
