### ISSUE TITLE
Can't use copy & paste when launch vscode from tmux session

### ISSUE THREAD

**Issue by lifez** [Microsoft/vscode#36755]
- VSCode Version: 1.17.2
- OS Version: Osx 10.12.6

Steps to Reproduce:

1. open `tmux` session
2. open vscode from tmux session `code `
3. Can't use `cmd+c` and `cmd+v` in vscode

Reproduces without extensions: Yes

**Comment by a-eid** [comment]
I have a similar issue , 
it also does not load the correct font for some reason , I am using "Fira Code" , it just load a system font . 
I am also using vscodevim and it has missed up some of the key binding .

**Comment by Tyriar** [comment]
@a-eid sounds like a different problem, we can can discuss in a separate issue if you want.

**Comment by a-eid** [comment]
@Tyriar I have the same issue . 
However I am not sure if the font issue related to it or not.  
@lifez please confirm if your custom fonts are loading correctly  . Thabks

**Comment by Tyriar** [comment]
When you're in tmux with mouse mode on a regular mouse event will be sent to the terminal program to be handled (ie. tmux). There is an override to force "regular selection" by holding alt, this should show a selection color the same as when you are outside of tmux. This normally works fine and allow the use of cmd+c/v even in mouse mode but it broke recently due to https://github.com/sourcelair/xterm.js/issues/1090

**Comment by roblourens** [comment]
I think @lifez and @a-eid are describing a different issue than what you fixed. I have the copy/paste problems in **the editor** after launching vscode from a tmux session, and the font is missing.

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/32393028-3be1536e-c095-11e7-8787-a4b546260d44.png)

**Comment by Tyriar** [comment]
Yeah I linked to the wrong issue, removing from October.

**Comment by a-eid** [comment]
weirdly enough after applying my linux machine tmux config , it worked fine (font + copy pasting) ,
I will make a gist of the config and share it in a few min

**Comment by bpasero** [comment]
This will solve it: https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by Tyriar** [comment]
@bpasero I'm not so sure about that? This issue is about launching VS Code *from* tmux which then breaks copy and paste.

**Comment by bpasero** [comment]
@Tyriar I just did that from my tmux setup and copy/paste works.

**Comment by bpasero** [comment]
Here is my tmux.conf:

```ini
set -g mouse on
set -g status off

set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

set -g history-limit 10000

set-option -g default-command "reattach-to-user-namespace -l bash"
```
