### ISSUE TITLE
Remote debugging session breakpoints do not remove on "Delete" key press if not debugging

### ISSUE THREAD

**Issue by Muchaszewski** [Microsoft/vscode#36757]
- VSCode Version: 1.17.2 x64
- OS Version: Windows 10 

Steps to Reproduce:

1. Open remote debug session (file is streamed on debugger connection to the debugger); This should create a temporary file called Script Document.
2. Set up breakpoint while debugging
3. Close debugging session.
4. Select from Breakpoints list previously created a breakpoint.
5. Press "Delete" key
6. Following error appears: Unable to open 'Script Document': Unable to resolve the resource without a debug session.
6. a) Right click -> Remove breakpoint works as intended

Expected behavior: Delete button should remove breakpoint as well event if not in debugging.

Reproduces without extensions: Yes

Additional info:
I'm using the ClearScript debugging with V8 engine on JavaScript to debug.

**Comment by weinand** [comment]
The fix results in a confusing UI. I've create issue https://github.com/Microsoft/vscode/issues/37517 to address this.
