### ISSUE TITLE
Single quotes changing into double quotes on Saving .vue file

### ISSUE THREAD

**Issue by 01abhishekjain** [Microsoft/vscode#36750]
- VSCode Version: Version 1.17.1
- OS Version: High Sierra

Steps to Reproduce:

1. add single quotes somewhere in a .vue file
2. save the file

The single quotes get changed to double quotes automatically.
I have only observed this on .vue files. If I change the language mode to Javascript, then it seems to be fine.

![issue](https://user-images.githubusercontent.com/11534188/31892251-30a1bc2c-b826-11e7-811d-77a31ee129ec.gif)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Vue support is not integrated by default. So this is implemented by an extension you've installed and not a VS Code issue. Checkout which extensions you have installed and try to deactivate them and recheck it. (I think you are using [Vetur](https://github.com/vuejs/vetur) for the Vue support).

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html
`prettier.singleQuote: true`.

**Comment by 01abhishekjain** [comment]
Should've observed that myself. Thanks.
