### ISSUE TITLE
Crash VS Code in Debugger Chrome.

### ISSUE THREAD

**Issue by Siscon-Ng** [Microsoft/vscode#36766]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-simpler-icons|dav|1.5.2
angular-extension-pack|dog|0.8.1
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.12
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
vscode-firefox-debug|hbe|0.16.1
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.1.4
docthis|joe|0.5.0
Angular2|joh|2.9.0
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.3
Angular-BeastCode|Mik|5.0.9
mssql|ms-|1.2.0
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.4.0
debugger-for-edge|msj|0.4.1
tsimporter|pmn|1.2.14
LiveServer|rit|3.0.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the vscode chrome extension with exact reproducable steps and more details like an error message or such
