### ISSUE TITLE
Formatting does not work correctly in .vue files

### ISSUE THREAD

**Issue by KLaci** [Microsoft/vscode#36765]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
vue-snippets|hol|0.1.5
csharp|ms-|1.12.1
vetur|oct|0.10.1
language-stylus|sys|1.7.3

---

Steps to Reproduce:

1. Create a .vue file with some content in in
2. Try to format with Alt+Shift+F
3. HTML part of the file is not formatted at all

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Please open this issue against the vetur extension: https://github.com/vuejs/vetur/issues
