### ISSUE TITLE
Dropdown of the intellisense is not in the correct position

### ISSUE THREAD

**Issue by mxschmitt** [Microsoft/vscode#36778]
- VSCode Version: Code - Insiders 1.19.0-insider (3c470706ded48fc75c05f86bc4f9c7b0f4d6c708, 2017-11-27T05:14:17.223Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
Go|luk|0.6.66
code-beautifier|mic|1.7.2
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Reproduces without extensions: Yes, I checked it

Steps to Reproduce:

1. Create a file (in my case `test.go`)
2. Set the language to `Golang`
3. Set the cursor to the End of the file (after the `.`)
3. Press Ctrl + Shift + P and reload the window
4. Press Ctrl + Space to get the intellisense dropdown

The first time after the reload when I try to open the intellisense dropdown it is not on the correct position. When I try it a second time or more, everything is alright. It looks like that:

![image](https://user-images.githubusercontent.com/17984549/31911998-caa470aa-b842-11e7-8aaa-57cbd0c9a0e8.png)

The testfile to reproduce is:

```go
package main

import (
    "github.com/sqweek/dialog"
)

func main() {
    dialog.Message("%s", "Do you want to continue?").Title("Are you sure?").
}
```

I'm not so sure, I know that this is a specific issue to `Golang` intellisense, but the position placement is not done there, it is done in the VS Code core. Although it is the same without any extensions enabled.
Additional I checked if the same behaviour is in an older release persistent. In this VS Code release everything works without any problems with the same test case:

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
xml|Dot|1.9.2
vsc-material-theme|Equ|1.0.3
markdown-table-formatter|jos|0.2.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.66
vscode-icons|rob|7.16.0
addDocComments|ste|0.0.8

(4 theme extensions excluded)

**Comment by ramya-rao-a** [comment]
@mxschmitt I am not able to repro this. Do you still see this?

**Comment by ramya-rao-a** [comment]
Ah, never mind. I can repro now. I need to press Ctrl+Space right after reload. If I wait for a while, then it doesnt repro. Also if the search/extensions view let is open, then after reload, the cursor is in the side bar. By the time I get the cursor to the editor and try, it doesnt repro. I'll see whats happening

**Comment by mxschmitt** [comment]
@ramya-rao-a thanks!

**Comment by ramya-rao-a** [comment]
@mxschmitt The fix will be out in tomorrow's Insiders build
