### ISSUE TITLE
Drag and drop from zip-files

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#36776]
Dragging files in to the workspace works flawlessly, or at least untill you try and drag files from a zip-file. It would be wonderful to be able to download libraries and not have to extract them before importing.

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
