### ISSUE TITLE
i cant see editor or other section like folder or terminal ...

### ISSUE THREAD

**Issue by DihoKing** [Microsoft/vscode#36773]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.0
csharp|ms-|1.12.1
material-icon-theme|PKi|2.2.3
java|red|0.12.0

![capture](https://user-images.githubusercontent.com/11072891/31909233-4812c6ba-b846-11e7-9ca7-ae87d76c8e39.PNG)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Can you reproduce it?
Please check if you are able to open the developer tools (Menu => Help => Toggle Developer Tools) and see there under the console tab any errors.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
