### ISSUE TITLE
Extension Development: all commands are shown on the command palette in spite of using "contributes.menus.*"

### ISSUE THREAD

**Issue by dlech** [Microsoft/vscode#36770]
- VSCode Version: 1.17.2
- OS Version: All

Steps to Reproduce:

1. Clone `https://github.com/dlech/vscode-command-bug` in VSCode
2. `npm install`
3. Run the extension
4. Open the command palette and type `command-bug` to see commands contributed by this extension
5. Observe that there are two commands.

Only one of the two commands should be shown in the command palette. The second command is associated with a tree view item context menu and causes an error when launched from the command palette.

I have worked around the issue by adding 

                {
                    "command": "extension.clickMe",
                    "when": "false"
                }

to "contributes.menus.commandPalette", but this get tedious for a real extension with many commands for tree view items.

Also, with the workaround, contributions as listed in the extension marketplace are incorrect. All of the commands in the screenshot below should only say `view/item/context` and not `commandPalette`.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/963645/31907425-664b7ae8-b7f9-11e7-8d95-ce499c7cfe42.png">

Reproduces without extensions: Yes

**Comment by dlech** [comment]
To save some clicking, here is my `project.json`

```json
{
    "name": "command-bug",
    "displayName": "command-bug",
    "description": "For reproducing bug",
    "version": "0.0.1",
    "publisher": "dlech",
    "engines": {
        "vscode": "^1.17.0"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "onCommand:extension.sayHello",
        "onView:extension.view1"
    ],
    "main": "./out/src/extension",
    "contributes": {
        "commands": [
            {
                "command": "extension.sayHello",
                "title": "Hello World",
                "category": "command-bug"
            },
            {
                "command": "extension.clickMe",
                "title": "Click Me",
                "category": "command-bug"
            }
        ],
        "views": {
            "explorer": [
                {
                    "id": "extension.view1",
                    "name": "View One"
                }
            ]
        },
        "menus": {
            "commandPalette": [
                {
                    "command": "extension.sayHello"
                }
            ],
            "view/item/context": [
                {
                    "command": "extension.clickMe"
                }
            ]
        }
    },
    "scripts": {
        "vscode:prepublish": "tsc -p ./",
        "compile": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "node ./node_modules/vscode/bin/test"
    },
    "devDependencies": {
        "typescript": "^2.0.3",
        "vscode": "^1.0.0",
        "mocha": "^2.3.3",
        "@types/node": "^6.0.40",
        "@types/mocha": "^2.2.32"
    }
}
```

I would expect that since the "extension.clickMe" is listed only in "contributes.menus.views" and not "contributes.menus.commandPalette" that it should not show up in the command palette.

**Comment by eamodio** [comment]
@dlech Sadly I believe that is a holdover from before you could actually remove commands from the command palette -- I'm guessing for backward compatibility, every command is automatically visible in the palette and must explicitly be removed via the `when` clause, like you did.

**Comment by jrieken** [comment]
Yeah, it's partly legacy and partly by design. In former times you could only have entries in the command palette but it's also part of the design as commands can always be invoked from anywhere, e.g. a keybinding, by another extension, etc... 

The problem is that we cannot change the command-palette-by-default behaviour anymore without breaking existing extensions and the ugly when-trick is the only thing we currently have to offer

**Comment by dlech** [comment]
So we are OK with just having it broken forever? Surely there are some clever people that could figure out something to make it better without breaking compatibility with existing extensions.

For example, would it be acceptable to base the behavior on a version? Maybe some think like this:

If you have...

```
    "engines": {
        "vscode": "^1.19.0"
    },
````

...or greater, then drop the legacy behavior. Old extensions will continue to work without change, but new/updated extensions are not forced to do ugly workarounds.
