### ISSUE TITLE
Intellisense Javascript for simple classes

### ISSUE THREAD

**Issue by scharf** [Microsoft/vscode#3677]
Intellisense for javascript does not detect simple Javascript classes.

Given this (ES6/TypeScript) class:
```js
class Greeter {
    constructor(message) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}
var greeter = new Greeter("world");
greeter. // I get intellisense here
```

If I write the same class by hand in ES5 (the code generated by TypeScript):

```js
var Greeter = (function () {
    function Greeter(message) {
        this.greeting = message;
    }
    Greeter.prototype.greet = function () {
        return "Hello, " + this.greeting;
    };
    return Greeter;
}());

var greeter = new Greeter("world");
greeter. // no suggestion here
```

I get no intellisense. I think this pattern should be detected automatically...

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7370

**Comment by sandersn** [comment]
This works for me on master, and I believe there were some fixes recently around IIFE type checking. 

@scharf, can you test this by installing `typescript@next` in a test package and in Code's settings.json temporarily setting `"typescript.tsdk": ".../node_modules/typescript/bin"`, where `...` is the path of your test npm package? (You'll have to restart Code or Reload Window to get the changes.)
