### ISSUE TITLE
Git - inicializate repo if folder is opened

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#36772]
- VSCode Version: 1.17.2 c[ b813d12980308015bcd2b3a2f6efa5c810c33ba5 ]
- OS Version: Win8.1 & Linux 16.04.2 Gnome3

Steps to Reproduce:

1. After #35902 changes, I think if we already have opened folder, it could also suggest initialization of repo in the current opened folder.
Of course, it is still possible to initialize a repo in another folder.

2. Now If I already have opened folder in vscode, and I click "inicializate repo", it ask, and I must do a lot of clicks to direct it to opened folder.

**Comment by joaomoreno** [comment]
We won't suggest to initialise a git repo on an open folder. It's a too far fetched assumption.

You can <kbd>Ctrl Shift P</kbd>, `init`.

**Comment by Mlocik97-issues** [comment]
I think, Atom has solved it correctly
