### ISSUE TITLE
[Feature request] Copy Info from "About VSCode"

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#36774]
- VSCode Version: 1.17.2 c[ b813d12980308015bcd2b3a2f6efa5c810c33ba5 ]
- OS Version: Win8.1 & Linux 16.04.2 Gnome3

Like as in Atom, one button, and you can easy copy version, commt, date, and other info about vscode. It can help if someone is reporting issue.

**Comment by maxibanki** [comment]
Already integrated to directly create an issue with the relevant information:
![image](https://user-images.githubusercontent.com/17984549/31909926-101ad810-b83c-11e7-88e9-588bff440bcc.png)
