### ISSUE TITLE
vscode not re-reading files from disk even after closing unedited file buffers

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#36775]
- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: MacOS 10.12.6 (16G29)

Steps to Reproduce:

1. Open file in project (don't edit it)
2. Change file outside of vscode
3. File change not reflected in vscode
4. Close file in vscode
5. Re-Open File in vscode
6. File change still not reflected in vscode

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@breathe is that reproducible? it should at least show the content after reopening

**Comment by breathe** [comment]
Sorry — the issue went away on its own several releases ago — apologies for going silent here.
