### ISSUE TITLE
VSCode gives wrong push error message

### ISSUE THREAD

**Issue by Vikingat-RAGE** [Microsoft/vscode#36785]
- VSCode Version: 1.17.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set GitHub private email setting to true
2. Open repo through vscode
3. Push to repo

VSCode returns : Can't push refs to remove. Run "Pull" first to integrate your changes.

However the issue as visible from the git log is infact 
`[remote rejected] master -> master (push declined due to email privacy restrictions)`

**Comment by joaomoreno** [comment]
Changed the message to more tentative suggestion.
