### ISSUE TITLE
[jade] Syntax highlighting in attribute values not correct

### ISSUE THREAD

**Issue by Haaner87** [Microsoft/vscode#3678]
### VS Code version:
0.10.8

### Code:
```
block content
  div(style='width:30vw')
    h1= title
    p= location
    p This is a paragraph
    img(src= image)
```

### Description:
The `image`-variable isn't highlighted corrctly.In fact all attribute-value-variables inside a html element, not only for the `img`-Tag are not highlighted correctly. This happens with all Themes and also with disabled extensions.
`image` should be white instead of grey.

### Image:
![1](https://cloud.githubusercontent.com/assets/1260620/13502000/48b0e15c-e169-11e5-8ffd-9c2b86d3c883.PNG)

### For comparison the same Syntax highlighted in another Editor (Sublime):
![image](https://cloud.githubusercontent.com/assets/1260620/13502072/ac1e5116-e169-11e5-873e-ab7fce69797c.png)

**Comment by Tyriar** [comment]
It's being styled with the default styles:

```css
.monaco-editor.vs-dark .token.meta.tag {
    color: gray;
}
```

This is a good example of the need for https://github.com/Microsoft/vscode/issues/2564, closing in favor of that.
