### ISSUE TITLE
Truncated text in Error message pop-over bar blocks user from reading full error text

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/vscode#36780]
User Story:
- As a VSCode user, I would like to have the ability to read the full text of error messages generated by the IDE.

System Info:
- VSCode Version: 2.6.1-insiders.20171019
- OS Version: macOS 10.11.6 El Capitan

Steps to Reproduce:
1. Run F5/Debug on any TypeScript file _without_ any run profile configured
2. Error message pop-over contains truncated text and is impossible to read full error text
![vscode truncated error text 2017 10 23 at 14 39 22 png 2078x118](https://user-images.githubusercontent.com/3075047/31914990-b989b726-b801-11e7-8d98-cbca56da28e0.png)

Reproduces without extensions: Unable to confirm. `code` shortcut not found on system.
```bash
> $ code --disable-extensions                                                                                                                                                 
zsh: command not found: code
```

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/22388
fyi @stevencl
