### ISSUE TITLE
Terminal cannot print all output.

### ISSUE THREAD

**Issue by gwy15** [Microsoft/vscode#36787]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Education / 1709 / 16299.19

Steps to Reproduce:

1. write a C++ program like this, actually I think all programs with heavy output requirements can reproduce this.
```
#include <iostream>
int main() {
    for (int i=0; i<256; ++i) {
        std::cout << "hello, world " << i << std::endl;
    }
    return 0;
}
```
2. compile and run in VSC's terminal.
(in my case, three different shells (cmd, PowerShell and Git Bash) produce similar results)
```
PS root\to\file> g++ -o vsc.exe -O2 -Wall vsc.cpp
PS root\to\file> ./vsc.exe
hello, world 0
hello, world 1
hello, world 2
hello, world 3
hello, world 4
hello, world 5
hello, world 6
hello, world 7
hello, world 8
hello, world 9
hello, world 10
hello, world 11
hello, world 12
hello, world 13
hello, world 14
h
PS root\to\file>
```
Please notice that the output stream is not fully printed.

+ The compile step can be simplified as `g++ vsc.cpp` and still produce same result.
+ Where the terminal stops varies. Sometimes it works properly and print all output.
+ If I add an extra line after the print line like
    `someFileStream << "hello, world " << i << std::endl;`
the output file is perfectly generated, and the terminal output is still incomplete. So I assume the problem is about VSC's terminal.

Reproduces without extensions: Yes

---
## update

Still reproduce on Windows 10 (1709, 16299.371), VSCode Version 1.22.2

**Comment by Summon528** [comment]
I also have the problem. Terminal cannot print all output if using Cmd or Powershell. It does behave well if using WSL though.

**Comment by Summon528** [comment]
Further information, If you wrote that code in python, the terminal behave just fine.

**Comment by xlebec** [comment]
Further information: When I compile a similar program with Cygwin g++ it works just fine, but when I use cl to compile it it has the exact same problem as above.

**Comment by ganka51298** [comment]
+1
Same issue here
VSCode Version : 1.19.3
OS:  Windows 10/ 1709 /16299.19

**Comment by malciin** [comment]
Same issue

**Comment by malciin** [comment]
+1 Same issue

**Comment by glebec** [comment]
GitHub has reaction emoji (upper-right corner of each comment). Please refrain from posting "+1" comments and instead show your support using a reaction, as otherwise subscribers to the issue get emails full of unwanted "+1" notifications. Thanks for understanding! 😃

**Comment by ihalip** [comment]
I can't reproduce this on Windows 7.

**Comment by yulon** [comment]
Can use `std::ios_base::sync_with_stdio(false)`  to solve this problem. 😂

**Comment by 1793907272** [comment]
+1
Same issue here
VSCode Version : 1.22.2
OS: Windows 10/ 1709 /16299.19

**Comment by Summon528** [comment]
Is this fixed? I'm not able to reproduce on the newer version (Windows 10 Build 17666, VSCode 1.23.1).

**Comment by gwy15** [comment]
@Summon528 I've retried just now and can't reproduce as well on Windows 10 1803 (17134.48), VSC 1.23.0. I believe this bug is fixed.
I'm closing this issue for now.
