### ISSUE TITLE
terminal print noisy webpack building log

### ISSUE THREAD

**Issue by fourcels** [Microsoft/vscode#36788]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

![screen shot 2017-10-24 at 10 23 47](https://user-images.githubusercontent.com/1042568/31922082-9bfe5586-b838-11e7-9fc5-5e1304895f95.png)

Reproduces without extensions: Yes

**Comment by doommm** [comment]
i got the same issue in OS: win10 15063.674, VS Code 1.17.2.
but it works well in insider-1.18.0.

**Comment by Tyriar** [comment]
I think this is happening due to the width of the terminal, does it still occur when the window is fullscreen and the line is not full?
