### ISSUE TITLE
How to stop vscode to capture the windows command shell

### ISSUE THREAD

**Issue by adyanced** [Microsoft/vscode#36789]
Hi,
There are vscode and 'IAR Embedded Workbench IDE' both on my computer. I use the latter developping hardware. And there is a 'post-build' command in IAR which will execute after the IAR project is built. The command will invoke the windows command shell to run a javascript. But the action is catched by vscode, then vscode will open the js file but not run it. So, how to stop vscode?

Thx

**Comment by joaomoreno** [comment]
https://www.digitaltrends.com/computing/how-to-set-default-programs-and-file-types-in-windows-10/
