### ISSUE TITLE
Support twig

### ISSUE THREAD

**Issue by bgarrant** [Microsoft/vscode#36784]
Many of us are using a twig based CMS these days. The code is very close to HTML, with some additional template tags. While VSC is amazon for HTML, it has no support for Twig. We can add twig syntax handling with a plugin, but there is no plugin that will format the twig code. Even worse is the twig extensions appear to be abandoned. 

Is there any way or anyone that can help get proper twig support in VSC?

**Comment by Spown** [comment]
Yes, there is. You can fork the extension and write it yourself or let someone do it for you by placing a bounty on it. And don't get me wrong, I'm not trying to be an asshole. I use Nunjucks (which is basically TWIG) and would love to have a better support for it, but I also understand that VSC has nothing to do with it. VSC developers were nice enough to enable 3rd party lang support. You can't demand from them to write every lang extension as well. That's where their responsibility ends and open-/crowd- sourcing begins.

Please don't forget to close this issue.

**Comment by bgarrant** [comment]
The syntax and language part is easy.  The code formatting part is where the issue lies really.  There is no code beautifier for twig tags.  I reached out to a few devs that have beautifier plugins and no response.  Looks like I will need to keep using PHPStorm until one is created as that is beyond what I can do.  Thanks for your reply.

**Comment by Spown** [comment]
>The syntax and language part is easy.

easy to use usually means hard to implement.

```html
<div>foo{{'</d'}}{# i'm so smart #}{['iv>'}}
```
and voilà the html syntaxer goes crazy. it can't produce a vaible DOM anymore and effectively it can't pretty/uglyfy. Jinja syntax is not XHTML compliant thus when your template is a mix of 2 or even more syntaxi - everything becomes several magnitudes harder. Don't say it's easy if you have no idea.

**Comment by bgarrant** [comment]
I meant creating the plugin for twig language syntax was easy as it can be converted from the Sublime Text PHP Twig plugin.  Took less than 5 minutes with Yo.  Only issue is no Beautifier will correctly indent and format the twig code as you know.  That is the hard part for me.

**Comment by bgarrant** [comment]
I have a few tickets open with this plugin https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify.  It seems to be our best bet for the twig formatting.  I looked at it and was not able to get the code working myself.  I have just been formatting in PHPStorm as it works there.  Once we can get a good twig beautify extension we should be able to eliminate using PHPStorm altogether.

**Comment by bgarrant** [comment]
Atom Beautify works perfect with Twig so it almost seems that an update is needed for the VSC Extension. https://github.com/Glavin001/atom-beautify. I am not sure if it pulls from Pretty Diff or JS Beautify however.

**Comment by aeschli** [comment]
Marked as an extension candidate.
