### ISSUE TITLE
Regex problem in Version 1.17.1 and 1.17.2

### ISSUE THREAD

**Issue by artan86** [Microsoft/vscode#36799]
https://stackoverflow.com/questions/46902830/how-to-search-in-visual-studio-code-using-regex-to-match-only-uncommented-code?noredirect=1#comment80755792_46902830

- VSCode Version: 1.17.2
- OS Version: Windows 7 Professional SP1

Steps to Reproduce:

1. Create a file with any filename and put the following content in the file:
[testRegex.txt](https://github.com/Microsoft/vscode/files/1409948/testRegex.txt)

//sys.log(siteNameToPrepare);
	//sys.log(siteNameToPrepare);
        // sys.log("downloadFolder: "+downloadFolder);
	// lorem ipsum ...
	arbitrary codes here...
	var a = _POST;
	sys.log("groupManagementHandler.jhp _POST is not object");
sys.log("groupManagementHandler.jhp _POST is not object");

2. Try to search within files (Ctrl+Shift+F) and turn ON the REGEX feature.
3. Put the following pattern in the search field: 

> ^((?!//|/\*).)*sys\.log

 then press Enter.
4. The following error message will appear: [Error parsing regex near...](https://i.stack.imgur.com/CFH7h.png)

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
In this Version it was working without any problems:
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601

**Comment by artan86** [comment]
How can I revert to the older version?

**Comment by maxibanki** [comment]
You could download e.g. the 1.15 [here](https://code.visualstudio.com/updates/v1_15).
But that's definitely a bug in my opinion and should be fixed.

**Comment by roblourens** [comment]
This is expected, our search tool ripgrep doesn't support lookahead or lookbehind. This is mentioned in the docs here: https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
