### ISSUE TITLE
Tasks schema 2.0.0 says suppressTaskName is deprecated but we still need it.

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#36790]
- VSCode Version: 1.17.2
- OS Version: Windows 10 16299.19

Steps to Reproduce:

We need to specify the version of PowerShell to run on various OS across many tasks.  We put the command defs outside the individual task defs so they can be reused.  So far the only approach that works on Windows and Linux is the following.  And if I pull out the `suppressTaskName` field the task fails because the task name is put on the command line:
```json
{
    "version": "2.0.0",

    "windows": {
        "command": "${env:windir}/System32/WindowsPowerShell/v1.0/powershell.exe",
        "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
    },
    "linux": {
        "command": "/usr/bin/powershell",
        "args": [ "-NoProfile", "-Command" ]
    },
    "osx": {
        "command": "/usr/local/bin/powershell",
        "args": [ "-NoProfile", "-Command" ]
    },

    "tasks": [
        {
            "taskName": "Install",
            "suppressTaskName": true,
            "args": [ "Invoke-Build", "Restore" ],
            "problemMatcher": []
        }
        // 5 more tasks very similar to the above 
    ]
}
```
So how is it that `suppressTaskName` is being deprecated.  Or maybe this is a bug where a `"type": "process"` task should **never** pass the task name as a parameter? 

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
In task 2.0.0 the shell to use can be controlled via the following setting:

```
"options": {
    "shell": {
        "executable": "....",
        "args": "...."
    }
}
```

In general `suppressTaskName` is true by default when using task 2.0.0 since the command and arguments should be fully controlled via the task itself. If this is not the case then I do have a bug :-)

**Comment by dbaeumer** [comment]
The options property can be used inside windows, linux or osx.

**Comment by dbaeumer** [comment]
OK to close?

**Comment by dbaeumer** [comment]
Thinking about it more I should add a warning to the tasks.json if the version is 2.0.0 and a task doesn't define a command or a dependsOn

**Comment by rkeithhill** [comment]
Thanks.  That works but I have to say from the tasks docs, the solution wasn't obvious.  But OK to close.

**Comment by rkeithhill** [comment]
> In general suppressTaskName is true by default when using task 2.0.0

This wasn't the case for how we originally had tasks.json configured.  But maybe our config was just bad.

**Comment by dbaeumer** [comment]
@rkeithhill I agree that the doc could be better here. And for compatibility I still support the `suppressTaskName` in case users simply bump the version number. But with the support of having a command per task the property doesn't make too much sense anymore and users starting fresh with tasks should not use it. This is why it is deprecated.

**Comment by rkeithhill** [comment]
Ugh, this is getting a bit frustrating.  I'm able to get this to work on Linux:
```json
{
    "version": "2.0.0",

    "windows": {
        "options": {
            "shell": {
                "executable": "${env:windir}/System32/WindowsPowerShell/v1.0/powershell.exe",
                "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
            }
        }
    },
    "linux": {
        "options": {
            "shell": {
                "executable": "/usr/bin/powershell",
                "args": [ "-NoProfile", "-Command" ]
            }
        }
    },
    "osx": {
        "options": {
            "shell": {
                "executable": "/usr/local/bin/powershell",
                "args": [ "-NoProfile", "-Command" ]
            }
        }
    },
    "tasks": [
        {
            "taskName": "Install",
            "type": "shell",
            "command": "Invoke-Build Restore",
            "problemMatcher": []
        }
    ]
}
```
But that hangs on Windows with:

![image](https://user-images.githubusercontent.com/5177512/31976513-34644f08-b8f5-11e7-8af1-7d0305b59a66.png)

Sigh...  I have yet to figure out how to make these six tasks work across Linux and Windows without having to resort to `suppressTaskName` or perhaps repeating the three shell configurations in all six tasks which is a major fail on the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.

**Comment by dbaeumer** [comment]
There is a bug in the terminal that if the shell can't be found or exits otherwise it is not propagated back. This will be fixed in the next release. I would say the problem is with `"executable": "${env:windir}/System32/WindowsPowerShell/v1.0/powershell.exe"` not resolving to a shell the terminal can launch. 

To better track this down I would like to ask you to set powershell as the terminal shell to use and open a terminal and see if this works.

**Comment by dbaeumer** [comment]
OK. Investiagted a little and there seems to be a problem with variable substitution in the executable property on a shell config. If I use:

```
		{
			"type": "shell",
			"taskName": "dir",
			"options": {
				"shell": {
					"executable": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
					"args": ["-Command"]
				}
			},
			"command": "dir"
		},
```

**Comment by dbaeumer** [comment]
Created https://github.com/Microsoft/vscode/issues/36880

**Comment by rkeithhill** [comment]
Indeed. If I remove that variable and use `C:/Windows/...` the task works!

**Comment by nightroman** [comment]
@rkeithhill 
FWIW, The latest [New-VSCodeTask.ps1](https://www.powershellgallery.com/packages/New-VSCodeTask/1.1.4/DisplayScript) generates VSCode tasks from Invoke-Build scripts according to this discussion.
