### ISSUE TITLE
Insiders 1.18.0 shows with default icon of Electron

### ISSUE THREAD

**Issue by toantk911** [Microsoft/vscode#36798]
- VSCode Version: Code - Insiders 1.18.0-insider (aaec2980609a4bbe44d0cfe2d3f78c85cba1be83, 2017-10-24T04:19:43.883Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
gitlens|eam|5.7.1
vscode-icons|rob|7.16.0

---

Steps to Reproduce:

1. Open Visual Studio Code
2. Watch the icon on Taskbar

Reproduces without extensions: Yes/No

**Comment by Mlocik97-issues** [comment]
Duplicate

**Comment by Mlocik97-issues** [comment]
#36665

**Comment by jtsom** [comment]
May be a duplicate, but #36665 was closed, however latest insiders update still has Electron icon.
