### ISSUE TITLE
"disable auto-formatting" on specific code block

### ISSUE THREAD

**Issue by AmirSasson** [Microsoft/vscode#36797]
- VSCode Version: -1.17.1
-  OS Version: windows 10 (creators update)

i Need to  "disable auto-formatting" on specific code block.
Can be done by leaving a comment above a block/line of code that disable the autoformatting.
auto-format on save is a great feature for teams.
but sometime we need not to format a "string" that represent an HTML (with indentation) that we want to control the indentation (for readability or sometime for logical reasons)

Steps to Reproduce: (TemplateStringsArray example in typescript)

```  
private readonly template = createParser
`<div style="border: solid 1px #eee; height: 100px; width: 476px; padding: 2px;">
     <div style="float: left; width: 100px">
     </div>
 </div>`;
`
```

when saving it is save like this:
```
`  private readonly template = createParser
        `<div style="border: solid 1px #eee; height: 100px; width: 476px; padding: 2px;">
    <div style="float: left; width: 100px">
    </div>
</div>`;
`
```
which is less readable

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/18261

Other formatters in the extension marketplace may already provide this functionality
