### ISSUE TITLE
text on menu  item is abnormal,but other apps are ok !

### ISSUE THREAD

**Issue by availa** [Microsoft/vscode#36794]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.9-gentoo
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.4
Go|luk|0.6.66
cpptools|ms-|0.14.0
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. install code
2. open code,just view root menu is not dispaly property!

Reproduces without extensions: Yes

**Comment by Spown** [comment]
you forgot 3rd step "describe your issue so that a human being could understand what you are talking about".

**Comment by availa** [comment]
it looks like this :

http://imglf4.nosdn.127.net/img/OWhVb1F5ZzAwVWxUanpKekhxTGdpWE1EeWFFTldvcExvMlVtS2lvMGxGcz0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg


my usersettings  is simple:

{
    "window.restoreWindows": "none"
}

nothing about font and display.

so why it show such ugly ?

**Comment by Spown** [comment]
what OS do you use?

**Comment by Spown** [comment]
It's probably has something to do with your OS

**Comment by availa** [comment]
gentoo

**Comment by availa** [comment]
other apps is ok ,only code

**Comment by availa** [comment]
firefox is ok ,

like this :

http://imglf4.nosdn.127.net/img/OWhVb1F5ZzAwVWtnaStLQUZhRW9ac1Zjb3hOZGRaaW4veDQ5aG9QemFnV3RGU1kySjhyMUdRPT0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg

**Comment by availa** [comment]
i have found  the reason:

in fontconfig,i turn off  10-sub-pixel-rgb.conf ,
then  ok .

many thanks  @Spown
