### ISSUE TITLE
Omnisharp does not load for one of my projects: Cannot evaluate the item metadata "%(FullPath)"

### ISSUE THREAD

**Issue by martinellison** [Microsoft/vscode#36793]
Omnisharp does not load for one of my projects (another project is OK).

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.5-200.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
numbered-bookmarks|ale|0.10.0
vscode-astyle|chi|0.7.1
csharpextensions|jch|1.3.0
docomment|k--|0.0.17
Go|luk|0.6.66
csharp|ms-|1.12.1
change-case|wma|1.0.0

---

Steps to Reproduce:

1. load project in VSC
2. try to find (say) all occurrences of a variable

Reproduces without extensions: Omnisharp does not load at all if I disable extensions

Starting OmniSharp server at 2017-10-24 12:16:48
    Target: /path/to/project/Persist.sln

OmniSharp server started wth Mono
    Path: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/run
    PID: 8783

OmniSharp: -s /path/to/project/Persist.sln --hostPID 3738 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/path/to/project' on host 3738."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /path/to/project
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/MSBuild.dll
    MSBuildExtensionsPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild
    TargetFrameworkRootPath: /usr/lib/mono/xbuild-frameworks
    RoslynTargetsPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/Roslyn
    CscToolPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/Roslyn

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/path/to/project/Persist.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /path/to/project/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/path/to/project/Assembly-CSharp.csproj'.
/path/to/project/Assembly-CSharp.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /path/to/project/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \\server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/path/to/project/Assembly-CSharp-Editor.csproj'.
/path/to/project/Assembly-CSharp-Editor.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/path/to/project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by isidorn** [comment]
Please file this against the omnisharp extension here https://github.com/OmniSharp/omnisharp-vscode
