### ISSUE TITLE
Git: sometimes "Open File" and "Open Change" show up disabled in context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3679]
@joaomoreno I wonder if this is a regression from my change to make the context menu show up after process.nextTick()? Sometimes I see "Open File" and "Open Change" disabled when I right click on an outgoing change.

Maybe you could check out if the code is sensitive to the context menu not opening sync anymore?

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/13502375/03f4a0ec-e16b-11e5-8a09-a51cc7b31ee8.png)

**Comment by joaomoreno** [comment]
No, it's related to the adoption to TS 1.8.2, super() ctor call ordering.
