### ISSUE TITLE
Question about VSCode terminal

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#36805]
VSCode terminal use canvas to show command result.
it's so amazing! i wonder how it's done?

like this? 
 input command -> native terminal -> output command -> syntax to html -> draw html to canvas

**Comment by Tyriar** [comment]
You can check out this blog post I wrote about it for a high-level summary: https://code.visualstudio.com/blogs/2017/10/03/terminal-renderer

Here's the PR that goes into more technical details: https://github.com/sourcelair/xterm.js/pull/938

Essentially this is how it was before:

```
input -> pty -> output -> create html based on output
```

And now:

```
input -> pty -> output -> draw text to canvas based on output
```
