### ISSUE TITLE
Error: Ignoring launch.version as launch is true

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#36808]
Version 1.18.0-insider
Commit aaec2980609a4bbe44d0cfe2d3f78c85cba1be83
Date 2017-10-24T05:25:17.161Z

When adding a workbench folder, I get the following error dialog:
![image](https://user-images.githubusercontent.com/6461412/31937198-046aae6e-b8b4-11e7-9059-8f0edcf31a87.png)

What does it mean?

**Comment by maxibanki** [comment]
https://github.com/Microsoft/vscode/blob/fa4c5561c9485a3c4427ec3de5584b9334e3e3c4/src/vs/platform/configuration/common/configuration.ts#L137-L163
Only to help others here's the method. That they don't need to search it.

**Comment by isidorn** [comment]
@maxibanki thanks, forwarding to @sandy081 as this is coming from the configuration service

**Comment by sandy081** [comment]
@aeschli Does your settings has overridden `launch` property?

**Comment by aeschli** [comment]
@sandy081 I don't think s. These are the steps to reproduce:
- git clone https://github.com/redhat-developer/vscode-java.git
- git clone https://github.com/eclipse/eclipse.jdt.ls.git
- open vscode on 'vscode-java'
- add workspace folder 'eclipse.jdt.ls'

**Comment by aeschli** [comment]
I see this in my default settings:
![image](https://user-images.githubusercontent.com/6461412/31948049-15bb66dc-b8d6-11e7-9d5c-e0f6a41f834e.png)

**Comment by sandy081** [comment]
Thanks @aeschli for steps
