### ISSUE TITLE
打开文件夹看不到下级文件及文件夹

### ISSUE THREAD

**Issue by kou8910** [Microsoft/vscode#36801]
打开文件夹添加项目，打开窗口只能看到上级目录，文件夹中的文件以及文件夹都看不到，等了很久不没有反应，关闭窗口，主程序卡死。

**Comment by Maroon1** [comment]
看起来时你电脑的问题，删掉 VS Code 重新安装试试看，不行的话，删掉所有设置和插件再重装试试看

**Comment by dbaeumer** [comment]
Can you please provide the issue report in English so that we can investigate.

@octref can you help ?

**Comment by octref** [comment]
@dbaeumer "Adding folder to project" -> I guess he meant multi-root.
"Only able to see the top-most folder. Then can't see any folders / files under it. Waiting for a while and VS Code becomes unresponsive."

**Comment by octref** [comment]
@kou8910 请提供 VS Code 的版本以及操作系统信息。
看样子你打开了一个你没有操作权限的文件夹？

**Comment by bpasero** [comment]
English please.
