### ISSUE TITLE
Extensions should be able to contribute file templates via a new UI feature - New File Template ... 

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#3680]
Our extension has several file types that we would like to provide users with a "starting" set of boilerplate code.  I would envision a new menu entry in the navigator under `New File` called perhaps `New File Template...` that would pop up a UI that lists extensions that contribute file templates.  The user selects the extension they're interested in, and then they see the file templates for that extension.  For PowerShell we would like to provide the following file templates:
- Module manifest file (.psd1)
- PowerShell Gallery Publish PSake script (.ps1)
- Fileshare Publish PSake script (.ps1)
- PowerShell Build, Test and Publish tasks (tasks.json)

The user selects one, presses OK/Close and that file gets placed into their workspace.

**Comment by rkeithhill** [comment]
Another approach might be to integrate various scaffolding tools into the task runner somehow.  If my extension could insert tasks like `Tasks: Scaffold New PowerShell Module Project`, `Tasks: Scaffold New Module Manifest File` and `Tasks: Scaffold PowerShell Module Publish Script`.   

The one downside to this approach is discoverability unless ... there was a Task Explorer viewlet along with the Navigator, Search, Git and Debug.  FWIW I would use a Task Explorer viewlet way more than I ever use the Search viewlet.  Hmm, I really like this idea as I think the tasks feature is currently not very discoverable.

**Comment by egamma** [comment]
When it comes to scaffolding template for new file, pls checkout what the aspnet yo generator is doing and how they use sub generators https://github.com/OmniSharp/generator-aspnet.

**Comment by rkeithhill** [comment]
Thanks for the pointer.  Yeoman is the scaffolding tool I was thinking about.  

As far as using Yeoman with VSCode, would you expect VSCode users to drop out of VSCode to a shell to scaffold items?  Or would you expect VSCode users to invoke the scaffolding tool via a task?  

Of course, sometimes the scaffolding tool needs input from the user i.e. target filename.  Does the task runner currently support defining a task that can pop an input dialog to ask the user for a filename?  If not, I could see how that would be a useful feature to have.  :-)

**Comment by egamma** [comment]
>As far as using Yeoman with VSCode, would you expect VSCode users to drop out of VSCode to a shell to scaffold items? Or would you expect VSCode users to invoke the scaffolding tool via a task?

There is a nice yeoman extension: https://marketplace.visualstudio.com/items?itemName=samverschueren.yo. An integrated generator appears more natural to me than a invoking a task to scaffold a file. Can you check how the yo extension works with your scenario.

**Comment by rkeithhill** [comment]
We talked with the Yeoman folks and found out this:

> Apparently the user has to globally install a Yeoman generator via npm before it shows up in the list. This is definitely an adoption blocker for PowerShell folks.

I think we will roll our own solution that generates projects and files in the PowerShell extension.  Perhaps if the installation of our extension could ensure that every dependency were in place already, such that the PowerShell extension user did not  have to perform extra install steps, we would reconsider.
