### ISSUE TITLE
Any typed character is not visible in terminal although being executed when hit Enter Key

### ISSUE THREAD

**Issue by pmverma** [Microsoft/vscode#36812]
- VSCode Version: 1.17.2
- OS Version: Window 10,  Version 1703
- Git Terminal version: git version 2.14.1.windows.1

Steps to Reproduce:

1. Open bash terminal inside vscode, it must be MINGW64 terminal which come with git installation
2. Do a `git diff` which should produce large output
3. Continue to hit `space bar` and then `Ctrl+C` to stop 
4. Type any command, it should not be visible
5. Hitting enter will execute typed command

Reproduces without extensions: Not tested

**Comment by Tyriar** [comment]
I'm consolidating ctrl+c issues under https://github.com/Tyriar/node-pty/issues/7
