### ISSUE TITLE
Change default keybinding of cursorColumnSelectUp to ctrl+shift+up on Windows

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#36819]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063

Current default keybindings on Windows:

```json
{ "key": "ctrl+shift+alt+up",     "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
// ...
{ "key": "ctrl+shift+up",         "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
{ "key": "shift+up",              "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
```

`cursorUpSelect` has two key bindings, which seems unnecessary. On Linux the default key bindings are (IIRC):

```json
{ "key": "ctrl+shift+up",         "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
// ...
{ "key": "shift+up",              "command": "cursorUpSelect",
                                     "when": "editorTextFocus" },
```

Which makes a lot more sense IMHO. Also using this default on Windows would also align Windows/Linux key bindings and maybe even avoid complications like #4391.

(same for `*Down` of course)

**Comment by alexandrudima** [comment]
We will not change this. See https://github.com/Microsoft/vscode/pull/41471#issuecomment-376139155
