### ISSUE TITLE
Old VS Code Icon on Pin to taskbar

### ISSUE THREAD

**Issue by AlexBanks97** [Microsoft/vscode#36814]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Go to installation folder of VS Code
2. Right click executeable
3. Click pin to taskbar

**Comment by Mlocik97-issues** [comment]
Duplicate

**Comment by sandy081** [comment]
Duplicate of #35663
