### ISSUE TITLE
Support for homebrew

### ISSUE THREAD

**Issue by luebken** [Microsoft/vscode#3681]
Support for distribution via http://caskroom.io/ would be great. Homebrew / cask is the defacto standard for software delivery for Mac developers.

**Comment by szaydel** [comment]
It is available as a cask, which may be good enough to call this closed. The name of relevant cask is `visual-studio-code`. [visual-studio-code link](https://github.com/caskroom/homebrew-cask/blob/master/Casks/visual-studio-code.rb)
