### ISSUE TITLE
Poor Fuzzy search results in Go To File...

### ISSUE THREAD

**Issue by dombarnes** [Microsoft/vscode#36810]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.5
material-icon-theme|PKi|2.2.3
vscode-docker|Pet|0.0.20
application-insights|Vis|0.4.1
html-snippets|abu|0.1.0
android-dev-ext|ade|0.4.1
azuretoolsforvscode|bra|1.3.0
Gradle|caz|1.1.2
npm-intellisense|chr|1.3.0
bower|don|0.0.3
githistory|don|0.2.3
tslint|eg2|1.0.12
vscode-npm-script|eg2|0.3.1
vscode-npm|fkn|3.3.0
useful-react-snippets|igo|1.1.1
azure-functions-tools|joh|0.3.1
Go|luk|0.6.66
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
atom-keybindings|ms-|3.0.2
azure-account|ms-|0.1.3
azurecli|ms-|0.3.0
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
node-debug2|ms-|1.18.3
PowerShell|ms-|1.4.3
vscode-azureextensionpack|ms-|0.0.6
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
debugger-for-chrome|msj|3.4.0
Csharp-ASPNETCore|rah|1.0.5
usql-vscode-ext|usq|0.2.6
azure-iot-toolkit|vsc|0.3.0
vscode-react-native|vsm|0.4.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a project with many similar text files (MVC with lots of index.cshtml files)
2. Go To File and enter text from a word where the letters also exist in the namespace
In my example, I want the Tips index.cshtml but instead every file is selected because T, I and P are in my namespace
<img width="616" alt="screenshot 2017-10-24 10 46 46" src="https://user-images.githubusercontent.com/511773/31936230-e2c50dd2-b8a8-11e7-8f2a-0440b57b8e48.png">

I would expect results order preference to favour full string matches

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@dombarnes if you try out our insiders build it should be better, otherwise please report back.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
