### ISSUE TITLE
Error: It looks like Git is not installed on your system

### ISSUE THREAD

**Issue by mars000** [Microsoft/vscode#36815]
I recently installed VSC Insiders x64 and stable x64 on a new computer (Windows 10 PC)
I clicked on Clone Git Repository and received the following INFO: It looks like GIT not installed on your system

I openeded a previosuly working workspace with .git and it fails to show Gir repository in VSC.
I'm stumped ! please help.

- VSCode Version: 1.17.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bary12** [comment]
Did you [install git](https://git-for-windows.github.io/)?

**Comment by mars000** [comment]
I thought it was already part of the VSC build; is that not the case ?
I've installed it separately now

**Comment by joaomoreno** [comment]
It's not included in VS Code. You must install it.
