### ISSUE TITLE
Git pull permission denied (Public key) on Mac OS Sierra

### ISSUE THREAD

**Issue by stilllife00** [Microsoft/vscode#36818]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
quokka-vscode|Wal|1.0.72
vscode-eslint|dba|1.4.0
intellij-idea-keybindings|k--|0.2.15
---

Steps to Reproduce:

1. Click on the Git dots
2. Select Pull
3. Instead of asking for the password it shows: Git: Permission denied (publickey).

Of course the same happens the push command.
I have also put in settings "git.autofetch": false but did not help

Outside of VSCode pull and push work fine

Reproduces without extensions: Could not test. Opening the app from the terminal it correctly asks for the password for id_rsa (in the terminal)

**Comment by joaomoreno** [comment]
https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain

**Comment by stilllife00** [comment]
Well I have followed the Solution 1 (recommended) but no luck.
This is my `~/.ssh/config` file:

    Host *
      AddKeysToAgent yes
      UseKeychain yes
      IdentityFile ~/.ssh/id_rsa

Any suggestion ?
