### ISSUE TITLE
Node not found on path when vscode launched from task bar -> Recent Workspaces

### ISSUE THREAD

**Issue by DragomirStefan** [Microsoft/vscode#36824]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Launch VSCode by clicking on one of the 'Recent Workspaces' displayed when right-clicking on the VSCode shortcut pinned on the taskbar - see attachment 1.png
2. If the Workspace opened is a Node.js application, trying to run it will produce an error - see attachment 2.png
3. Close the error message
4. Trying to run (F5) the Node.js application will show another error - see attachment 3.png
5. Close the error message
6. Switch to the integrated terminal and type "node --version" - a message is being displayed saying that "node : The term 'node' is not recognized as the name of a cmdlet..." - see attachment 4.png
7. Open a command prompt outside of VSCode, type node --version, and observe that the correct version is displayed - see attachment 5.png

Please note that if the same Workspace is opened by first launching VSCode and then opening the folder, everything works as expected.
![1](https://user-images.githubusercontent.com/32800808/31946466-ec06ca1a-b89f-11e7-831d-ddd834fc08b9.png)
![2](https://user-images.githubusercontent.com/32800808/31946467-ec223ade-b89f-11e7-98d1-a342c084c698.png)
![3](https://user-images.githubusercontent.com/32800808/31946469-ec358b98-b89f-11e7-9732-4a60905bbebf.png)
![4](https://user-images.githubusercontent.com/32800808/31946470-ec4f8232-b89f-11e7-8160-020e463ee099.png)
![5](https://user-images.githubusercontent.com/32800808/31946471-ec636c98-b89f-11e7-9d08-0248299ea651.png)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Try to reproduce it without extension, for that run VS Code with the `--disable-extensions` parameter.

**Comment by DragomirStefan** [comment]
Cannot repro when extensions are disabled. I opened VSCode from command prompt using "code --disable-extensions", then opened a node.js folder. Using this sequence the problem does not occur, even when extensions are loaded.

Note that the problem I reported happens when opening via a Recent Workspace shortcut. I don't know how to open a Recent Workspace with the extensions disabled.

**Comment by joaomoreno** [comment]
How did you install Node JS?

**Comment by DragomirStefan** [comment]
I installed node by running the install available at nodejs.org. Yes, node.js is in %PATH%. Even when loading a folder in VSCode from a "Recent Workspaces" shortcut, when VSCode is not finding node, I can go to the command prompt, type 'node --version' and the command is recognized, the version of node gets printed out.

Can you repro the problem? Are there any logs you want me to provide?

**Comment by joaomoreno** [comment]
I can't repro the problem. There are no logs unfortunately.

If you open the `Developer Tools` in Code, in the Console what does `process.env.PATH` return?

**Comment by DragomirStefan** [comment]
It returns the correct %PATH% system variable.

I cannot repro the problem anymore. Don't know what happened, I did not update VSCode or any of the node packages I was using.

**Comment by joaomoreno** [comment]
Great to know.
