### ISSUE TITLE
formatOnSave is broken with Indent Using Tabs.

### ISSUE THREAD

**Issue by pvcresin** [Microsoft/vscode#36826]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:
1. Set `"editor.formatOnSave": true`in `settings.json`.
1. Set "Indent Using Tabs" to 4 on the GUI.
1. Create a file : `test.js`.
1. Edit like this (using tab-indent):
```js
function name(params) {
	console.log('hello')
}
```
5. After saving (and Formatting), the number of tabs will be quadrupled.
```js
function name(params) {
				console.log('hello')
}

```

**Comment by mjbvz** [comment]
Do you have any formatter extensions installed that could be causing this? Does it still reproduce if you disable all extensions?

**Comment by pvcresin** [comment]
I'm sorry. I was wrong.
It seems that the extension for the format which I used before was bad.
After completely disabling all extended functions, I fixed it.
