### ISSUE TITLE
renderLineHighlight should highlight logical line 

### ISSUE THREAD

**Issue by hickford** [microsoft/vscode#36839]
- VSCode Version:  1.17.2

- OS Version: Windows 7

When word wrap is on, renderLineHighlight should highlight the whole logical line, not just the physical line. (When word wrap is off, these are the same thing.) This makes it clear that the commands 'cut' and 'move line up' affect the logical line.

Steps to Reproduce:

1. Enable word wrap
2. Move cursor to a long line

Expected:

3. See whole logical line is highlighted

Actual:

3. Only physical line is highlighted

Screenshots (some themes set a background, others set a border)

![image](https://github.com/microsoft/vscode/assets/105314/53807941-eccb-45fb-aef9-7ffcb9c1b4a9)

![image](https://user-images.githubusercontent.com/105314/31957290-373675da-b8e6-11e7-8152-7097ed6439ce.png)

Relevant code: https://github.com/microsoft/vscode/blob/main/src/vs/editor/browser/viewParts/currentLineHighlight/currentLineHighlight.ts

**Comment by hickford** [comment]
Works as expected in Sublime Text

![image](https://user-images.githubusercontent.com/105314/31957625-4b4cdfa4-b8e7-11e7-9d5b-9df5e97f7865.png)

**Comment by alexandrudima** [comment]
Interestingly, not all editors do this. Here is, for example, Visual Studio:

![image](https://user-images.githubusercontent.com/5047891/32004792-e81e2264-b9a2-11e7-8451-c073bc573610.png)

**Comment by h-h-h-h** [comment]
Ideally, there would be two different ways of indicating the current memory and the current display line that are both shown at the same time.

**Comment by usernamehw** [comment]
Just made an extension [Highlight logical line](https://marketplace.visualstudio.com/items?itemName=usernamehw.highlight-logical-line#overview):

![example](https://user-images.githubusercontent.com/9638156/47610087-5a7cbe00-da55-11e8-9ea6-9efcef3729ce.gif)

 It has some sort of delay though... But looks almost fine using black color: `#00000050`.
Making native highlighting transparent makes it slightly better too:
`"editor.lineHighlightBackground": "#0000",`

**Comment by ZYinMD** [comment]
> Interestingly, not all editors do this. Here is, for example, Visual Studio:
> 
> ![image](https://user-images.githubusercontent.com/5047891/32004792-e81e2264-b9a2-11e7-8451-c073bc573610.png)

@alexandrudima That is indeed interesting for Visual Studio. What happens when you press Ctrl-C (⌘C) in Visual Studio when your cursor is at a wrapped line when no selection is made? Does it copy the logical line or the highlighted line? If the latter, then it's an inconsistent user experience.

**Comment by hickford** [comment]
Visual Studio's word wrap has many issues; I wouldn't hold it up as an example https://docs.microsoft.com/en-gb/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor#known-issues

**Comment by jamescostian** [comment]
Are there any plans to fix this in VS?

**Comment by kevcube** [comment]
Bumping 😬

**Comment by iamwwc** [comment]
Above Exstenion works for my. But I think vscode should support it natively 👍

**Comment by lucasvazq** [comment]
bump

**Comment by AlbertoFabbri93** [comment]
I think this should be the default behavior when word wrap is enabled.

**Comment by zhangbest5** [comment]
"Highlight Line", try it !
Highlights the current line in the editor. Find your location in your editor easily.
