### ISSUE TITLE
VS Code Insiders icon is now the Electron default icon

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#36838]
- VSCode Version: Code - Insiders 1.18.0-insider (aaec2980609a4bbe44d0cfe2d3f78c85cba1be83, 2017-10-24T04:19:43.883Z)
- OS Version: Windows_NT x64 10.0.15063

The standard VS Code Icon no longer shows in VS Code Insiders or when app is pinned to taskbar, instead the default Electron app icon shows. This happened a couple updates ago. I've noticed this on two different machines I run code on. 

Screenshot:

![code-insiders-icon-is-default-electron-app-icon](https://user-images.githubusercontent.com/190154/31957131-b6f118f0-b8bb-11e7-9414-718eaa140a52.PNG)

**Comment by frankhale** [comment]
Yikes! Was the removal of the orange icon intentional or is this a mistake? 

I did not realize how volatile this subject was... https://github.com/Microsoft/vscode/issues/35783

**Comment by frankhale** [comment]
Just installed VS Code stable and it has correct icon (eg. no Electron default icon).

**Comment by frankhale** [comment]
I tried downloading and reinstalling Insiders but icon is still the same default icon that shows in an Electron app.

Additionally I downloaded the zip of Insiders and the code executable also has the same default Electron icon.

**Comment by apap04** [comment]
yeah, they probably messed up the code.

**Comment by rcjsuen** [comment]
See #36665.

**Comment by frankhale** [comment]
Oh thanks @rcjsuen I'll close this one in favor of #36665

**Comment by frankhale** [comment]
I didn't realize that #36665 was closed. I'm going to reopen this one as the issue still exists.

**Comment by frankhale** [comment]
Duplicate of what? The issue I linked to is still closed. Is the issue actually fixed now?

**Comment by frankhale** [comment]
Thanks for closing and I appreciate that after updating the problem is sort of solved but there is still an issue with pinning VS Code to Windows 10 taskbar. See screenshot...

![problem-half-fixed](https://user-images.githubusercontent.com/190154/31986236-a883d738-b935-11e7-81b0-a2d219395d95.PNG)

**Comment by frankhale** [comment]
I wish I could reopen this issue, silly github you drunk!

**Comment by rcjsuen** [comment]
@frankhale I suggest you comment on #36665. There are more people subscribed to that issue and there may be others there that are encountering the same problem as you. It's best to collect all the information and comments in one issue instead of having discussions in multiple places.
