### ISSUE TITLE
Go To/ Peek Definition

### ISSUE THREAD

**Issue by zxzeigler** [Microsoft/vscode#36834]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
java|red|0.12.0
yo|sam|0.9.3
guides|spy|0.9.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. In a java project, the goto/ peek definition right-click actions state "No definition found in --my referenced java class--". 
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please try filing this issue agains the java extension: https://github.com/redhat-developer/vscode-java/issues/new 

Include a small code example or small sample project that demonstrates the issue
