### ISSUE TITLE
Git integration missing whitespace changes

### ISSUE THREAD

**Issue by rdlaner** [Microsoft/vscode#36833]
- VSCode Version: 1.18.0 (Insiders)
- OS Version: Windows 10

Steps to Reproduce:

Select a range of code and press 'tab' and save. Note that git doesn't detect this as a modification:
Before:
![image](https://user-images.githubusercontent.com/17415937/31954231-e5f6f830-b899-11e7-9f76-4c446e03cb54.png)

After:
![image](https://user-images.githubusercontent.com/17415937/31954294-1267c0fc-b89a-11e7-96a0-b4e85829333f.png)

Viewing the repo in the Git source control view also does not show this as a modification, whereas other git tools do.

Reproduces without extensions: No

**Comment by maxibanki** [comment]
In my test case it shows the modification when I indent something with tabs.
![image](https://user-images.githubusercontent.com/17984549/31983691-98ed2238-b95e-11e7-986b-7ac99e09b044.png)
- VSCode Version: Code - Insiders 1.18.0-insider (c1e079b6ccfad9ead105c44a84e862ffc5250222, 2017-10-25T04:18:36.616Z)
- OS Version: Windows_NT x64 6.1.7601

**Comment by rdlaner** [comment]
@maxibanki 
Sorry, I should have clarified: I can see the modification in the "diff" view, however, I do not see any indication in the gutter where the modification took place.

When you add the tabs, the modification shows up in the "diff" view, but do you see any notification in the gutter indicating that a modification has occurred? For example, if you add, modify or remove code, the gutter should give an indication where the modification took place. For me, this happens most of the time, but I noticed that it does not for white space modifications.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/10007
