### ISSUE TITLE
Feature Request: assign a colour to a project Window

### ISSUE THREAD

**Issue by mikegleasonjr** [Microsoft/vscode#36842]
Sometimes I have 2-3 projects opened, when I circulate through the windows with cmd+`, it is not obvious right away which project I just activated.

In the project-specific files, this could be great to assign a colour somewhere, maybe make the blue bottom status bar configurable.

**Comment by bpasero** [comment]
@mikegleasonjr you can do this via the `workbench.colorCustomizations` setting or by setting different themes per workspace.

**Comment by mikegleasonjr** [comment]
@bpasero Thanks! Sorry for the noise..
