### ISSUE TITLE
BUG: Feature autoclose tag<html> is shooting in any other languages

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#36846]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Updated

Reproduced in Typescript 2.5.3, but this behavior is shooting in any other language.

Steps to Reproduce:

1.  See Gif

![bugautoclosetag](https://user-images.githubusercontent.com/5774595/31964041-7c60bce2-b8e1-11e7-9b0a-6e7e49de8c11.gif)

Reproduces without extensions: No

**Comment by aeschli** [comment]
I think you have the [auto close extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) installed. Please uninstall or configure it to not complete in TypeScript

**Comment by cwberick** [comment]
Thanks. Problem resolved.
