### ISSUE TITLE
Terminal should support to confirm an instance delete / kill on exit

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#36845]
In the old task system the task service prompted the user if the workbench closed with running tasks. However when executing the task in the terminal this doesn't happen anymore since the terminal service receives the shutdown event first and then kills all terminal instances. When the task service is ask all tasks are already gone. To support that the task service gets more control over this I see two options:

- the terminal service fires an event that it shutsdown and the task service listens to that
- a terminal instance can be marked as confirmOnExit and if one exist the terminal service prompts the user (as it would if the setting is set)

I would prefer option two and I am willing to provide a PR. @Tyriar what is your take on that.

**Comment by Tyriar** [comment]
@dbaeumer there is already the confirmOnExit setting, it will confirm even when the shell isn't running anything currently though.

Can this be closed in favor of https://github.com/Microsoft/vscode/issues/23808?

**Comment by dbaeumer** [comment]
@Tyriar I was aware of that setting but it is global. I do have requests that people want to be warned for task A but not for task B. But may be we can postpone the request and I tell people to use the Terminal setting for now.

**Comment by dbaeumer** [comment]
#23808 would be a prerequisite for using the setting with tasks. Most of the time the terminal doesn't have an active process anymore so closing it would be fine.

**Comment by Tyriar** [comment]
@alexr00 is this still desired from the tasks side? Do you have an issue reference for this?

**Comment by alexr00** [comment]
I don't know of an issue for it. I'll re-open if I find something.
