### ISSUE TITLE
OutputChannel - remove show function

### ISSUE THREAD

**Issue by ShiftySituation** [Microsoft/vscode#36844]
Feature Request

- VSCode Version:  1.17.2
- OS Version: Windows10

Remove the show function from OutputChannel.  Reason, coders need less distractions so allowing extensions to control what I see is a huge distraction.  Plus it is annoying when typing commands in the terminal and all of a sudden the output window comes into view.

**Comment by dbaeumer** [comment]
In general I see why @ShiftySituation is aksing for this however removing the show function is not the right way to tackle this. Two things that I think can be improved:

- a badge indicating that a message is there but not read
- tracking down the cases where the output channel comes to front and is not necessary and fix those.

@isidorn assigning to you as the owner of the output channel.

**Comment by isidorn** [comment]
We are exploring adding the badges to the output channel. All the infrastrucutre is there for this.
Once we have adopted this in the output channel we can look into revisting where we call show.

As for the extension we can not prevent them from doing this, though I understand your concern.
fyi @jrieken

**Comment by jrieken** [comment]
No way we can remove that function from the API but "yes" we should have this overrule-able by the user.

**Comment by isidorn** [comment]
Let's wait and see if more people ask for it and I can add some configuration.

**Comment by lemoinem** [comment]
@isidorn Yes, people ask for it. Please refer to https://github.com/angular/vscode-ng-language-service/issues/128 for example.

**Comment by ShiftySituation** [comment]
@Jakeii Just out of curiosity, what is an example use-case that would clarify this api function as being beneficial?

**Comment by isidorn** [comment]
@lemoinem yeah that is a problem with the angular extension and should be fixed there and not using a workaround in vscode.

**Comment by paustint** [comment]
@isidorn , according to @chuckjaz from `vscode-ng-language-service`:
> My code does not call that method at all (https://github.com/angular/vscode-ng-language-service/blob/master/client/src/extension.ts). This is call happens in the client library I am using which is provided by the vscode team.

**Comment by isidorn** [comment]
@paustint thanks for more details, however what client library is he refering to?
Is he simply using our api and if yes what exact call does the automatic show of output?

**Comment by dbaeumer** [comment]
@isidorn it is the LSP client library

@chuckjaz if the output channel is reveal or not can be control in the client library via the `revealOutputChannelOn` setting.

**Comment by isidorn** [comment]
Seems like this is configurable in the client library, no action to do here on the vscode side (as far as I understand) -> closing
