### ISSUE TITLE
Unable to create 'launch.json' file inside the '.vscode' folder (TypeError: Cannot read property 'replace' of undefined).

### ISSUE THREAD

**Issue by Prateek0601** [Microsoft/vscode#36841]
- VSCode Version: 1.17.2
- OS Version:Windows 10 fall creators update 

Steps to Reproduce:

1.create any C++ program 
2.debugging it suing C++ GWW 

Reproduces without extensions: No

Hey github community i need help with this problem 
![help](https://user-images.githubusercontent.com/33068264/31958716-416e77ee-b910-11e7-816a-3957bff757bc.png)

**Comment by isidorn** [comment]
Please file this against the C++ extension here https://github.com/Microsoft/vscode-cpptools

@pieandcakes I have pinged you on some deprecations we are introducing on the vscode side. It would be awesome if c++ extension could pick those up (should not be a lot of work)
