### ISSUE TITLE
The keyboard sometimes has a chance of not typing, but it's ok to restart the editor

### ISSUE THREAD

**Issue by saybabi** [Microsoft/vscode#36859]
- VSCode Version: 1.17.2
- OS Version: windows 6.1.7601

Extensions

- Git History 0.2.3
- Git Lens 5.7.1
- Git Product Manager 1.4.0
- Git Tags 1.1.2
- HTML CSS Support 0.1.8
- HTML Snippets 0.1.0
- One Dark Pro 2.10.17
- PHP IntellSense 1.5.2
- PHP IntellSense  - Crane 0.3.8
- TODO Highlight 0.5.11
- TSLint 1.0.12
- vue 0.1.5
- Vue 2 Snippets 0.1.5

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@saybabi can you please provide any reproducible steps ? Does this reproduce when disabling all extensions ?
