### ISSUE TITLE
Constant prompting to install Helper Tool

### ISSUE THREAD

**Issue by Bak3y** [Microsoft/vscode#36856]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ansible|haa|0.2.5
ansible-autocomplete|tim|0.0.2
---

Steps to Reproduce:

1.  Install VSCode Version: Code 1.17.0 on OSX High Sierra
2. Open VSCode
3. Wait for prompt.

Reproduces without extensions: Yes

The app will prompt for credentials "An update is ready to install.  Visual Studio Code is trying to add a new helper tool."
<img width="474" alt="screen shot 2017-10-24 at 7 42 41 pm" src="https://user-images.githubusercontent.com/4029474/31974912-b0b7d108-b8f3-11e7-905e-f1f758abd734.png">

If you input your credentials it prompts to relaunch:  "Visual Studio Code will be updated after it restarts."  Clicking Update Now relaunches Visual Studio Code but the prompt comes back shortly thereafter.

I already attempted the steps at https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 to no avail.

**Comment by Bak3y** [comment]
I manually downloaded an updated to 1.17.2 and this problem appears to have gone away.

**Comment by joaomoreno** [comment]
Good to know.
