### ISSUE TITLE
vscode does not show sql script in correct syntax when editing with temp syntax (#)

### ISSUE THREAD

**Issue by betimer** [Microsoft/vscode#36853]
- VSCode Version: 1.17.2
- OS Version: Win10 x64

Steps to Reproduce:

open `myscript.sql` 

incorrect display for temp SP/table (with #)
```
exec @help = #aa_7458_page @master, 7, 'Help','/help'
exec #aa_7458_page @help, 0, 'Begin a Consult ','/beginconsultPDF'
```

![image](https://user-images.githubusercontent.com/8111748/31971907-af303bba-b969-11e7-88e6-d7a9366ba66a.png)

**Comment by mjbvz** [comment]
Appears to be an issue with our builtin grammar. [The mysql extension](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) seems to fix it:

![screen shot 2017-10-24 at 5 13 23 pm](https://user-images.githubusercontent.com/12821956/31974176-ccc56ee2-b8de-11e7-984e-8de2b96f5b33.png)

@aeschli Should we look into pulling our grammar from that extension's repo instead? The textmate one we currently use doesn't seem very active

**Comment by aeschli** [comment]
@mjbvz Goog idea. I switched to use the mysql grammar
