### ISSUE TITLE
Output editor should also be a simple editor

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#36851]
- VSCode Version: Code - Insiders 1.18.0-insider (aaec2980609a4bbe44d0cfe2d3f78c85cba1be83, 2017-10-24T04:19:43.883Z)
- OS Version: Windows_NT x64 10.0.17017
---

Steps to Reproduce:

1. Subscribe and log `window.onDidChangeActiveTextEditor` via an extension
2. Open a text editor
3. Click and hold on the output or debug console tab 
4. 🐛 observe that multiple events trigger with the last event setting the active editor back to the open text editor

This is not reproducible in the current stable version. You also don't need to click and hold for long to see it, it just makes it easier to see

//cc @jrieken 

Reproduces without extensions: No

**Comment by eamodio** [comment]
Again the "helpful" bot mislabeled this ;)

**Comment by jrieken** [comment]
> observe that multiple events trigger 

Which are what events?

**Comment by jrieken** [comment]
> This is not reproducible in the current stable version. 

@isidorn is that related to the container work you have been doing?

**Comment by isidorn** [comment]
@jrieken might be. I can look into this, thanks.

**Comment by eamodio** [comment]
To be clear, the events I was talking about were all the same `onDidChangeActiveTextEditor`, just with different values for the editor -- I believe the order was 3 events, first with `undefined`, then with output/debug pane, and finally back to the original editor

**Comment by jrieken** [comment]
I believe that's how it always was...

**Comment by eamodio** [comment]
In the stable version, it only fires 2 -- `undefined` and output/debug pane (since you are selecting the output/debug pane). It also would only fire those events on mouse up, but now those 3 above fire on mouse down -- and then on mouse up, you'll get another 1 at least, back to the output/debug pane (but I think you might also get `undefined` first)

**Comment by isidorn** [comment]
I have looked into this and can repro. The issue here is that the new composite bar steals focus on click. Thus the `MainThreadDocumentsAndEditors` reacts on the blur event from the output, tries to find the active editor by asking the workbench since no other editor has focus. And then wrongly sends that the active editor changed.

@bpasero I find it weird as to why was this previously working. How did you trick the previous panel title area to never steal focus?
Composite bar has some listeners for click and drag, but I still get the behavior that he steals focus on click if I remove all listeners.

**Comment by bpasero** [comment]
@isidorn probably just related to the fact that the panels now can be dragged. I did not prevent the focus stealing with any code as far as I remember. 

Though this does not happen for editor tabs (which are also draggable). I think there I am passing focus back on mouse down and that might prevent the focus lost from happening in the first place. Maybe play around with that.

**Comment by isidorn** [comment]
Just doing domBlur, does not do the trick. I think I need to explicitly call `focus()` on the composite.
Though all of this seems a bit ugly. In reality the composite did loose focus and now our vauge definition of the active editor kicks in.

**Comment by DanTup** [comment]
Somewhat related; I raised #45188.

I didn't expect debug console to be considered a "text editor". The docs for `activeTextEditor` make it seem like this is an actual document the user is editing, and is stick to the last one when they move focus away:

> "The active editor is the one that currently has focus or, when none has focus, the one that has changed input most recently

This is really useful for rendering something like an outline tree, but if we hide the tree when the `activeTextEditor` ceases to be our document, it vanishes when you click in the debug console.

**Comment by isidorn** [comment]
This behaves better now since the debug console is no longer an editor but a simple editor. Thus events for it are not sent to extensions

**Comment by DanTup** [comment]
Yep, saw this in release notes a while back and it looks fine now 👍

**Comment by eamodio** [comment]
@isidorn will/can the output pane also be a simple editor? The debug pane works as expected now, but the output pane behaves the same as before.

Can this be reopened?

**Comment by jrieken** [comment]
> the output pane behaves the same as before.

⚠️ this will break those that rely on this oddity, like wallaby et al

**Comment by DanTup** [comment]
Slightly related:

https://github.com/Microsoft/vscode/issues/58865

If an output pane can be an active editor, why doesn't `closeActiveEditor` close it?
