### ISSUE TITLE
Backspace must decrease indent (as Shift-Tab do) when the line is empty

### ISSUE THREAD

**Issue by dimdin** [Microsoft/vscode#3685]
e.g. for this code
```C 
    if (cond) {
        return ;
        |
```
where | is the cursor position. By pressing backspace the cursor must be aligned with "if".

**Comment by NinoFloris** [comment]
+1 very useful feature that I love from sublime

**Comment by outcoldman** [comment]
@dimdin implemented it with PR #5423
Please review unit test https://github.com/Microsoft/vscode/pull/5423/files#diff-03a74fc8e046bdf7481eefdc7cce74c8R2147 to check that I have not missed anything

**Comment by alexandrudima** [comment]
Thanks to @outcoldman this has now landed with PR #5423 . It will most likely come out with the May release in about a month.
