### ISSUE TITLE
I want to use 'cmd+shift+/' to switch the block comment, but I find the key is bound to the help menu and can't be unbound,  what should I do?

### ISSUE THREAD

**Issue by DaleHe** [Microsoft/vscode#36858]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
html-snippets|abu|0.1.0
vscode-caniuse|aka|0.5.3
project-manager|ale|0.22.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-npm-script|eg2|0.3.1
smarty|imp|0.2.0
vue|jcb|0.1.5
vetur|oct|0.10.1
vscode-icons|rob|7.16.0
svg-snippets|sid|1.0.1
open-in-browser|tec|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@DaleHe which keyboard layout are you using?

**Comment by alexandrudima** [comment]
This is a built-in feature of mac applications, showing up in Google Chrome, VS Code and Parallels from the applications I have tested:

![image](https://user-images.githubusercontent.com/5047891/31995215-ca88e244-b983-11e7-8cb8-b8acbe9779a4.png)

Please search online for how to disable this feature in your OS.

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by DaleHe** [comment]
@alexandrudima Yes, you are right! The key is bound by my mac. I changed my system's keyboard settings, and then, it works! Thank you so much!
