### ISSUE TITLE
i want css intellisense can use in other file type 

### ISSUE THREAD

**Issue by xiachaoxulu** [Microsoft/vscode#36869]
i want css intellisense can use in other file type 
maybe：

**Comment by xiachaoxulu** [comment]
css.intellisenseExtension [
  "html",
"postcss"
]

**Comment by aeschli** [comment]
There's already css completion in HTML.

Please explain more what you mean.

**Comment by xiachaoxulu** [comment]
yes, in html ,when i write words in style tag，i get the css intellisense。
but，i want to write css in .postcss , such as  index.postcss,or index.abcdefg. 
how can i get  css intellisense  in that filetype.
so,i suggest  ,vscode css language service  can give the interface for config what  file extension  can get  css intellisence.
maybe : 
 css.intellisenseExtension [
"abcd",
"postcss"
]

**Comment by aeschli** [comment]
You can just associate your postcss file extension to css.
But you likely want us to fully parse and understand cssnext. That's https://github.com/Microsoft/vscode-css-languageservice/issues/47
