### ISSUE TITLE
Insider integrated terminal cannot render underscore character properly

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#36862]
- VSCode Version: 1.18.0-insider commit:  aaec2980609a4bbe44d0cfe2d3f78c85cba1be83
- OS Version: Ubuntu 16.04

This is both happen in light and dark theme

Steps to Reproduce:

1. Launch VSCode and open integrated terminal
2. Type underscore character and try to switch the vscode theme 

![image](https://user-images.githubusercontent.com/8751130/31979000-fe7cf304-b976-11e7-9fbb-0f001d1c795d.png)
I already type the underscore character but it doesn't appear.

**Comment by tangorboyz** [comment]
Sorry, the regular vscode version 1.17.2 doing just fine. That's only happen on insider build

**Comment by maxibanki** [comment]
Tried to reproduce, but in my version everything is working fine. Already tried to reproduce it without extensions?
- VSCode Version: Code - Insiders 1.18.0-insider (c1e079b6ccfad9ead105c44a84e862ffc5250222, 2017-10-25T04:18:36.616Z)
- OS Version: Windows_NT x64 6.1.7601

**Comment by deterok** [comment]
I have the same problem.
![screenshot_20171025_144545](https://user-images.githubusercontent.com/1702003/31996994-1bae4b50-b993-11e7-961d-15367577c139.png)

- VSCode Version: 1.17.2
- OS Version: Linux fort_dey 4.13.8-1-ARCH #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017 x86_64 GNU/Linux

Installed addons:
![screenshot_20171025_145043](https://user-images.githubusercontent.com/1702003/31997213-cc6e6dc6-b993-11e7-89ae-d98bf8a8795c.png)

**Comment by deterok** [comment]
It seems to me that the problem is in the font.
I changed the fontFamily (`"editor.fontFamily": "'Noto Mono', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'"`) and the character displayed correctly.
![screenshot_20171025_145922](https://user-images.githubusercontent.com/1702003/31997542-0418b938-b995-11e7-9571-1f6b712c386d.png)

**Comment by tangorboyz** [comment]
I don't know, it's working again. I even didn't have to disable the extensions.

**Comment by tangorboyz** [comment]
You're right, it's the font.

**Comment by jhasse** [comment]
Still not fixed for me, even when using `"editor.fontFamily": "'Noto Mono', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'"` (with or without Noto Mono installed). I'm on Fedora 26 and using 1.17.2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901

**Comment by abhigyandwivedi** [comment]
@jhasse  changing my font family in user settings file to "editor.fontFamily": "monospace,'Noto Mono', 'Droid Sans Mono', 'Courier New', 'Droid Sans Fallback'" resolved this issue completely.
