### ISSUE TITLE
when will the icon be changed? 

### ISSUE THREAD

**Issue by MAPESO** [Microsoft/vscode#36864]
https://code.visualstudio.com/blogs/2017/10/24/theicon

On what date will we have the new icon?

**Comment by maxibanki** [comment]
In the [1.18.0 Insider release](https://code.visualstudio.com/insiders/) the icon has already been changed (the green one). The blue one will be used when the next stable release will be published.

**Comment by MAPESO** [comment]
@maxibanki Thanks 😄
