### ISSUE TITLE
[theming] Add theme-specific color customizations

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#36860]
Now there are only 2 settings to customize current theme:
`"workbench.colorCustomizations": {}`
`"editor.tokenColorCustomizations": {}`

The downside: if you have a habit to customize each one of your themes, then you have to manually maintain the list of all of your tweaks.

#### New Syntax:
```json
"workbench.colorCustomizations": {
    "[One Dark Pro]": {}
}
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {}
}
```
#### Color priority:

`2:` Setting with theme name (`"[One Dark Pro]": {}`)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
`1:` Setting without theme name (`workbench.colorCustomizations: {}`)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
`0:` Active theme (One Dark Pro)

#### Use cases:

* Using different themes for night and day
* Using several favorite themes (in no particular order)
* Trying out new theme, tweaking it, but in the end returning to the previous one

**Comment by aeschli** [comment]
Note that you can easily create a new theme out of your customized theme with the `Generate Color Theme from User Settings' command.

**Comment by usernamehw** [comment]
As far as I understand, that will leave you without theme updates:
* Added support for a new language
* Fixed a bug
* Used new styling properties

**Comment by sgon00** [comment]
+1

**Comment by bpasero** [comment]
This is pretty cool 👍

**Comment by usernamehw** [comment]
IKR? Should this be included in the release notes?

**Comment by aeschli** [comment]
I added an entry in the release notes and updated the docs.
Thanks again @usernamehw !
