### ISSUE TITLE
Drag VSCode to Another Screen, terminal(iterm2+zsh) display error

### ISSUE THREAD

**Issue by yvshuo** [Microsoft/vscode#36863]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
vscode-css-formatter|aes|0.0.2
vscode-eclipse-keybindings|alp|0.9.6
node-debug2|ms-|1.18.3
vetur|oct|0.10.1
velocity|sod|0.1.0
vscode-react-native|vsm|0.4.4

---

Steps to Reproduce:

1.open my VSCode at my macbook‘s local screen, the terminal(item2+zsh) works well
![image](https://user-images.githubusercontent.com/9249608/31979959-11c2d9e6-b90f-11e7-97d7-7f94f99dd5e3.png)

2.drag it to the macbook's another screen, it works wrong
![image](https://user-images.githubusercontent.com/9249608/31979987-31f534e8-b90f-11e7-8d68-b57ea0499e55.png)

3.drag it back to the local screen, the terminal works well again

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
