### ISSUE TITLE
Expect Shift+END to select to end of line

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#3686]
With cursor in the middle of a line, when I press Shift + End, I expect the selection to extend to the end of line.   Current behavior seems to just move the cursor to the end of line.

**Comment by Tyriar** [comment]
Cannot reproduce (Ubuntu 15.10).

**Comment by katopz** [comment]
Cannot reproduce (Windows7 x64) v0.10.8

**Comment by mquandalle** [comment]
It looks like there is no issue and this could be closed. @BurtHarris?

**Comment by Tyriar** [comment]
Yes, closing this due to its age and I use it all the time without any problems.

**Comment by BurtHarris** [comment]
Finally reproduced this, of course it was my silly mistake - I had changed my Numlock preference in the BIOS.
