### ISSUE TITLE
Can you pin the window on the top with a button ?

### ISSUE THREAD

**Issue by whitefirer** [Microsoft/vscode#36879]
Sometimes need this.

**Comment by bpasero** [comment]
@whitefirer can you explain what you mean?

**Comment by whitefirer** [comment]
@bpasero click a button to make the vscode's window keep on the top layer.And also cancle it by click the button again.Place it on the title bar.

**Comment by bpasero** [comment]
Thanks understood. 

This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
