### ISSUE TITLE
HTML结构复制后粘贴在其他位置后结构错乱

### ISSUE THREAD

**Issue by shen-zhao** [Microsoft/vscode#36870]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
vscode-markdownlint|Dav|0.10.1
EditorConfig|Edi|0.11.0
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-simpler-icons|dav|1.5.2
vscode-eslint|dba|1.4.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.2.1
vscode-great-icons|emm|2.1.17
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
jquery-snippets|Hri|1.0.0
docthis|joe|0.5.0
sublime-babel-vscode|jos|0.2.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
easy-less|mrc|1.4.5
debugger-for-chrome|msj|3.4.0
color-highlight|nau|2.3.0
sass-indented|rob|1.4.5
easysass|spo|0.0.6
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@shen-zhao  can you please provide the issue report in English. Otherwise we are not able to work on this. 

@octref can you help ?

**Comment by octref** [comment]
@dbaeumer "HTML becomes mal-formatted after pasted into other areas". Guess that's the onTypeFormat for HTML.

@shen-zhao Can you try to use English, thanks.

**Comment by aeschli** [comment]
@shen-zhao Please add a code sample with steps
