### ISSUE TITLE
Auto-update is launched twice if you two VSCode window open

### ISSUE THREAD

**Issue by g3r4n** [Microsoft/vscode#36874]
- VSCode Version: 1.1.7.1
- OS Version: Windows 7

Steps to Reproduce:

1. open 2 VSCode window.
2. Auto-update the VSCode
3. the 2 window will close
4. 2 installation windows will open.

**Comment by joaomoreno** [comment]
This is fixed in `master`.

**Comment by g3r4n** [comment]
Don't consider the down thumb, I hate my track pad ...
