### ISSUE TITLE
I want the old blue infinity logo!

### ISSUE THREAD

**Issue by liuhong12th** [Microsoft/vscode#36877]
The previous blue infinity logo is the best.
![vscode-logo](https://user-images.githubusercontent.com/10379994/31985754-c56b8dba-b998-11e7-9705-a7f984433049.png)

The current logo, orange fish logo, is the worst.
![windows-stable-orange](https://user-images.githubusercontent.com/10379994/31985792-d3e2e456-b998-11e7-94d7-4ec189768b41.png)

The incoming logo, blue fish logo, is a little better than the orange fish logo, but still bad.
![2017_10_24_blueicon](https://user-images.githubusercontent.com/10379994/31986061-a3fad734-b999-11e7-9d66-a68a091f2535.png)

The orange infinity logo is also looks wierd, but is much better than the previous two logo.
![vscode-logo2](https://user-images.githubusercontent.com/10379994/31986098-c0247c30-b999-11e7-9937-08bbe4dc4dd4.png)

So why you must change the logo?

**Comment by Zolomon** [comment]
I agree that the old blue infinity logo is much more aesthetically pleasing.

**Comment by parwat08** [comment]
Yes the blue infinity logo is the best...

**Comment by bpasero** [comment]
The reasons for our new icon are nicely summarised here: https://code.visualstudio.com/blogs/2017/10/24/theicon
