### ISSUE TITLE
integrated terminal   chinese font 

### ISSUE THREAD

**Issue by mangege** [Microsoft/vscode#36878]
- VSCode Version: 1.17.2
- OS Version: archlinux

Steps to Reproduce:

1. touch /tmp/你好 
2. ls /tmp/ 

filename = ''$'\344\275\240\345\245\275'

Reproduces without extensions: Yes

user config
```json
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.fontFamily": "'Noto Sans Mono', 'Noto Sans CJK SC'",
    "terminal.integrated.fontFamily": "'Noto Sans Mono', 'Noto Sans CJK SC'",
    "markdown.preview.fontFamily": "'Noto Sans Mono', 'Noto Sans CJK SC'"
}
```

**Comment by Tyriar** [comment]
Can you provide a screenshot of the issue?

**Comment by mangege** [comment]
screenshot url: https://imgur.com/yKCUqxH

**Comment by Tyriar** [comment]
Can you show me the output of `echo $LANG`?

**Comment by mangege** [comment]
```
[outman@hparch tmp]$ echo $LANG
en_US.UTF-8
[outman@hparch tmp]$ export LANG="zh_CN.UTF-8"
[outman@hparch tmp]$ cd /tmp
[outman@hparch tmp]$ mkdir a
[outman@hparch tmp]$ cd a/
[outman@hparch a]$ touch 你好
[outman@hparch a]$ ls
你好
```

change lang, fix .

**Comment by Tyriar** [comment]
@mangege interesting, normally this just works on Linux with `en_US.UTF-8` and the setLocaleVariables thing is only needed on macOS. Oh well, glad you worked it out :smiley:
