### ISSUE TITLE
Feature request: open new VS Code window by dragging file tab

### ISSUE THREAD

**Issue by zachsa** [Microsoft/vscode#36875]
At the moment you can drag file tabs to rearrange them, which is great. I would like to be able to drag a tab OFF the tab bar to create another VS Code window with just that file. I.e. I would like to view two files on two different monitors. 

I know that If I have VS Code with 4 different files open,  I can split the editor view into two or more columns and show files side by side. But i don't think this allows me to spread files across two monitors.

Currently I'm using VS Code V1.17.2

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by zachsa** [comment]
Thanks I did search - couldn't find what I was looking for. There are a lot of ways that one could search for this. What about a link to the open issue?

Thanks - Zach
