### ISSUE TITLE
Region collapsing/folding and Git Integration clash

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#36872]
- VSCode Version: 1.18.0-insider (Commit c1e079n6ccfa...)
- OS Version: Windows 7

Steps to Reproduce:
![off center click](https://user-images.githubusercontent.com/4070008/31984287-4af53aea-b961-11e7-833a-b8269acc71b0.gif)
1. Open a file that is under Git source control and which supports folding (I used JSON in my example)
2. Perform a change in that file near a point where region collapsing occurs
3. Click on the toggle that should collapse the region. If the mouse cursor is firmly in the center of the toggle button, the region collapses. If the mouse is off center and also touches the Git "change marker", the difference panel is shown. The issue is that the "hit zone" of the region toggle seems to be smaller than in previous builds and you have to aim more precisely.

Reproduces without extensions: Yes

**Comment by lafe** [comment]
The issue seems to be a little different than I initially thought: The issue is not limited to clicks that might overlap the Git marker but can also occur if you click "off center" on the toggle of a region that contains a change. I hope this video makes the issue more clear:
![second image](https://user-images.githubusercontent.com/4070008/31987393-fe5393e8-b96b-11e7-9f9f-bd2267246d16.gif)

**Comment by aeschli** [comment]
This got fixed in the meantime.
