### ISSUE TITLE
Ability to contribute context menu actions in Problems panel

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#36881]
An extension should be able to contribute actions to the context menu in problems panel.

**Comment by CoenraadS** [comment]
Will the current message be passed as an event arg? I just tried it out but didn't receive any args?

**Comment by sandy081** [comment]
@CoenraadS No. But I see it does not makes sense to have this without passing the current problem. Let me revisit it.

**Comment by sandy081** [comment]
Since this is needed mainly for quick fixes and supporting quick fixes in problems view is implemented here ##52627, closing this.
