### ISSUE TITLE
Allow to open SCM resource files with a single click

### ISSUE THREAD

**Issue by mradbourne** [Microsoft/vscode#36885]
I often use the source control menu to jump between files by right clicking on a file and choosing 'Open file'.

Would it be possible to add a settings property that makes primary click 'Open file' instead of 'Open changes'?

**Comment by joaomoreno** [comment]
@mradbourne Wanna attempt a PR? All changes should be contained in the `extensions/git` folder.

**Comment by cleidigh** [comment]
fyi @bpasero related #30530 cc: @joaomoreno

**Comment by bpasero** [comment]
Not sure...

**Comment by joaomoreno** [comment]
Actually I went with just having the action inline:

![image](https://user-images.githubusercontent.com/22350/34046637-04930ce2-e1ae-11e7-838f-c5ba3bac767a.png)
