### ISSUE TITLE
Zen mode: panel and sidebar do not restore after reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36888]
Steps to Reproduce:

1. enter zen mode
2. show the panel
3. reload window

=> first the editors restore and then the panel

**Comment by isidorn** [comment]
This should be fixed via https://github.com/Microsoft/vscode/commit/1a4f6b9f7dbf297904025925af55cc4bc4cf8631
Please let me know if you still see it

**Comment by bpasero** [comment]
@isidorn now the panel is not restoring at all anymore is that expected?

**Comment by isidorn** [comment]
@bpasero no, this is a regression that on reload zenMode hides all things again -> reopening and renaming

**Comment by isidorn** [comment]
Actually this is the behavior in stable already and nobody complained. So might actually not be that undesirable.
For now pushing to backlog and only if people complain will do something.

**Comment by isidorn** [comment]
Let's close this and reopen if somebody complains
