### ISSUE TITLE
The obvious and best solution for the icon color discussion

### ISSUE THREAD

**Issue by Parou** [Microsoft/vscode#36886]
We don't need orange, we don't need blue. Pink is the color to go!

![vscode_pink](https://user-images.githubusercontent.com/28531401/31992740-634b8dfa-b97b-11e7-86b7-86d454540a14.png)

**Comment by CronGM** [comment]
I don't know if this is the right place for this kind of feedback, but am I the only one who dislikes the "box" in the icon? I associate that directly with Office 365 and the Windows Store icons (which is something I don't expect a development tool to be directly associated with).

**Comment by bpasero** [comment]
Thanks for the suggestion! I think for now we will stick with blue and green. Please see https://code.visualstudio.com/blogs/2017/10/24/theicon
