### ISSUE TITLE
Update incremental build instructions in wiki

### ISSUE THREAD

**Issue by phillipj** [Microsoft/vscode#3688]
As https://github.com/Microsoft/vscode/pull/3649 got merged, the incremental build instructions in [wiki/How-to-Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#incremental-build) should be updated to:

```bash
npm run watch
```

as global install of `gulp` on the developer's machine is no longer required.

**Comment by phillipj** [comment]
Also noticed this in the prerequisites:

```bash
npm install -g mocha gulp
```

which could also be removed. 

In addition to the mentioned PR, what's in #3691 made me able to tests and dev version of VS Code running without gulp or mocha globally.

**Comment by joaomoreno** [comment]
Fixed.
