### ISSUE TITLE
Extension: CHANGELOG.md isn't picked up

### ISSUE THREAD

**Issue by drKnoxy** [Microsoft/vscode#36898]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
sort-lines|Tyr|1.3.0
vscode-custom-css|be5|2.5.0
vscode-icontheme-nomo-dark|be5|1.3.4
vscode-eslint|dba|1.4.0
eslint-disable-snippets|drK|1.1.3
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
code-runner|for|0.7.4
vscode-styled-components|jpo|0.0.8
Go|luk|0.6.66
php-docblocker|nei|1.3.2
annotator|ryu|0.10.1
ayu|tea|0.8.0
gitblame|wad|2.2.0
vscode-import-cost|wix|2.5.1

(9 theme extensions excluded)

---

Steps to Reproduce:
I built the extension `eslint-disable-snippets` using the starter project, but the CHANGELOG.md file isn't being displayed in vscode extension search.

1. Open vscode
2. Search extensions for eslint-disable
3. Click the `eslint-disable-snippets` extension
4. Click the changelog
5. *err* its empty
6. Extension repo was created with vscode extension scaffolding tool, https://github.com/drKnoxy/eslint-disable-snippets

Reproduces without extensions: N/A

**Comment by dbaeumer** [comment]
@drKnoxy yout .vscodeignore file contains CHANGELOG.md. As a result the file will not be packaged into the vsix for the marketplace. Simply remove the line.

How did you create the project. Using yo code. If so can you provide steps since then our generator has a problem.

**Comment by drKnoxy** [comment]
thanks for your help!
