### ISSUE TITLE
Issue about the indent of inserted new line

### ISSUE THREAD

**Issue by LIXiangChen** [Microsoft/vscode#36896]
![qq 20171025201817](https://user-images.githubusercontent.com/8857634/31998967-345f6d92-b9c4-11e7-958a-8ee08f10f684.png)

As in figure. Sublime Text doesn't have this problem. I guess Sublime copy the indent characters of last line to next line, instead of regenerate indent.

Have already set `"editor.autoIndent": false,` in settings.

Version: 1.17.2 (Windows 64 bit)

**Comment by alexandrudima** [comment]
Duplicate of #36090

The fix is available already on the [Insiders Channel](https://code.visualstudio.com/insiders) and will come with the 1.18 stable version.
