### ISSUE TITLE
Sometimes vscode not work properly

### ISSUE THREAD

**Issue by tangjwt** [Microsoft/vscode#36899]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.10
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.12
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
angular-cli-vscode|lf-|0.0.3
ts-compile-on-save|liu|0.0.3
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.16.0
easysass|spo|0.0.6

---

Steps to Reproduce:

1. Enable extensions
2.Use ng serve start angular project
3.Modify file and waiting for autoreload

note:
1.Can not be reproduced every time
2.When the problem occurs, all the extensions and code helper not work, check the activity monitor, I found code helper process's cpu usage is 100%.

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Sounds like this is caused by one of your extensions. Can you please share the full command line arguments of the process that has the high cpu usage. To see this, run:

```bash
$ ps aux | grep -i code
```
