### ISSUE TITLE
[CSharp] Have "add using ..." on top in quick fix dialog 

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/vscode#3689]
Have "add using ..." on top in quick fix dialog

This is a real timesaver as the suggestion is 99% of the time correct but it's at the bottom, requiring an extra "arrow key up" keystroke to complete the action.

It is a bit of a flow killer

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#86
