### ISSUE TITLE
Run Active File In Active Terminal doesn't work in WSL (or other non-cmd/powershell shells)

### ISSUE THREAD

**Issue by SpikePy** [Microsoft/vscode#36897]
- VSCode Version: 1.17.2
- OS Version: Win10

Steps to Reproduce:

1. Set Terminal to bash
2. Press <Ctrl>+<Shift>+<P> and type "run active file"
3. run command
4. Does not work because path to the file is windows-style and <.> is missing in front.

**Comment by namaggarwal** [comment]
Hey @Tyriar may I know which files to look at to fix this ?

**Comment by captainrdubb** [comment]
I would like to fix this. Where is a good place to start?

**Comment by Tyriar** [comment]
Looks like it was introduced in Windows 17063

https://blogs.windows.com/windowsexperience/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/
