### ISSUE TITLE
FR: Terminal on the right side

### ISSUE THREAD

**Issue by Albert221** [Microsoft/vscode#36903]
Hey! I was wondering if there would ever be a possibility to have terminal (and problems, output, debug console) on the right side of the screen. I think that very big amount of people would benefit from that. There are people who have 21:9 screens or similar and vertical space is more important than horizontal space.

Here's my screen, I attach PhpStorm with terminal on the right for comparison:
![image](https://user-images.githubusercontent.com/4085280/32002326-8a87999c-b99c-11e7-98dd-288ccbfe540a.png)
![image](https://user-images.githubusercontent.com/4085280/32002430-d17bfa5a-b99c-11e7-842c-b8eeb661a86b.png)

**Comment by Tyriar** [comment]
This was actually just done today and will be in tomorrow Insiders! https://github.com/Microsoft/vscode/issues/2806

**Comment by suciuvlad** [comment]
@Tyriar toggleMaximizedPanel doesn't work anymore. It executes the "Move to Right" command now.
