### ISSUE TITLE
I'm creating a theme and I want to select the static class to give it color in PHP

### ISSUE THREAD

**Issue by victorzevallos** [Microsoft/vscode#36908]
- VSCode Version: 1.17.2
- OS Version: Windows 10

I can not select the static class to give it color.

![captura](https://user-images.githubusercontent.com/22132891/32005511-17aba6fc-b96a-11e7-955b-62abb4146353.PNG)

**Comment by dbaeumer** [comment]
This can't be done via a Theme. Syntax coloring can only be influenced using a TextMate Grammar.

@aeschli please correct me if I am wrong.

**Comment by aeschli** [comment]
Yes, this needs to be implemented in the grammar.
The grammar we use for php is https://github.com/atom/language-php. Please file a request there so that scopes are generated for the type name.

**Comment by victorzevallos** [comment]
* For example, the "User" class has a selector:
![user](https://user-images.githubusercontent.com/22132891/32116310-bbe909b6-bb0f-11e7-89ea-bac4ba7e468f.PNG)

* Here "Route" is a static class and does not have a selector:
![route](https://user-images.githubusercontent.com/22132891/32116249-7924f4be-bb0f-11e7-9806-43b020ecc67a.PNG)
I propose this selector: "entity.name.type.static-class.php"
This is a selector in [code](https://github.com/victorzevallos/vscode-theme-laravel/blob/master/themes/laravel.json#L143).
Vscode [Documentation](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers)




* I want to achieve this:
![laravel](https://user-images.githubusercontent.com/22132891/32116461-4f67acf6-bb10-11e7-973f-f109617b5712.PNG)

* Today I have this:
![actual](https://user-images.githubusercontent.com/22132891/32116690-4ef144f2-bb11-11e7-800a-0550d67ffd55.PNG)


This is my [extension](https://marketplace.visualstudio.com/items?itemName=victorzevallos.vscode-theme-laravel).
I'm doing a theme inspired by the documentation of [Laravel](https://laravel.com/docs/5.5/routing#route-parameters) and I can not paint static classes.
