### ISSUE TITLE
Files appear in another folder in Explore bar when open a folder

### ISSUE THREAD

**Issue by lijunray** [Microsoft/vscode#36907]
- VSCode Version: 1.17.2
- OS Version: High Sierra 10.13

Steps to Reproduce:
Opening a folder in Explore and some files or folders are displayed under another folder. Not sure how it start happening but it happens randomly on my mac almost once every 2 times opening a folder.

![oct-25-2017 10-32-51](https://user-images.githubusercontent.com/14250009/32004977-1cdf7c8c-b971-11e7-9af2-c0c09417d144.gif)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please let us know how to reproduce this and then we can investigate further.
Also can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
Also if you do F1 > open developer tools -> do you see some errors in the developer console

**Comment by lijunray** [comment]
@isidorn It seems working well after I reboot the mac. And I don't see "open developer tools" after F1. I don't think I can reproduce it in insiders since it happens randomly.

**Comment by isidorn** [comment]
Please let us know if you can reproduce and if you get more details in developer tools and we will reopen this issues.
To open developr tools console menu: Help > toggle developer tools
