### ISSUE TITLE
Test: vertical panel layout

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#36906]
- [x] win @bpasero 
- [x] os x @octref
- [x] linux @Tyriar

Refs: https://github.com/Microsoft/vscode/issues/2806
Complexity: 4

We now support vertical panel layout. Please note that there is a seperate [test plan item](https://github.com/Microsoft/vscode/issues/36571) for the overflow behavior in the panel title area. Verify:

* You can switch the panel from vertical to horizontal 
* View state is preserved across sessions
* Tryout all the corner cases and verify there are no layout glitches: 
  * have activity bar on the right,
  * hide activity bar
  * hide status bar
  * zen mode
* Toggle maximized panel works as expected in both panel positions
* Workbench nicely auto relayouts on windows resize, or resize of some part
* The whole workbench layout has been touched so quickly open dev tools and take a look at the different parts of the workbench and verify they do not overflow with respect to their dimensions

**Comment by cleidigh** [comment]
@isidorn 
CoolNewFeature!

Just did some quick testing.  The Increase/Decrease View commands need to be updated to contemplate
a vertical panel.  As the original contributor of these keyboard user centric commands I can do a PR for this for the November release.  There are several issues I wanted to address.  I will create one or two issues for these tweaks (split view was also an issue pending I want to address)

**Comment by YusufTaha** [comment]
WOHOOOO!!!!

**Comment by bpasero** [comment]
@cleidigh can you report that as issue please, I also noticed that.

**Comment by bpasero** [comment]
@isidorn found quite some issues. maybe it would make sense to first get the fixes in for them and then test again. I think @Tyriar and @octref would probably just file similar issues otherwise.

**Comment by isidorn** [comment]
@bpasero yes I can look into this issues once I am done testing in an hour or so. Best case scenario I can fix some of them so that @Tyriar and @octref can test with a new insiders version once they start their work day.

**Comment by bpasero** [comment]
@isidorn sounds good, maybe some of them are just duplicates of the same underlying issue.

**Comment by isidorn** [comment]
@Tyriar @octref feel free to test this as we have triggered new builds.
Most of the issues @bpasero filed are still valid so maybe just first glance through them. Filling duplicates is also not a problem for me.

An alternative is that you test tomorrow once most of the layout things get fixed. Whatever you prefer.

**Comment by octref** [comment]
@bpasero seems to have forgot to check off so I checked off both of us.

Although there are some small issues it mostly work as expected. I can see myself using this feature quite often. Great job!

**Comment by octref** [comment]
@isidorn Is letting different windows have different layout possible? Or is there an issue for it?
I want vertical panel on my wide monitor but not on my macbook.

**Comment by bpasero** [comment]
@octref since the layout is a workspace setting that should be possible if you configure the setting there.

**Comment by octref** [comment]
@bpasero Well, but neither clicking on the toggle button nor Quick Command let me toggle it if I set it in my workspace setting. Is it possible to introduce a Ctrl+Enter to run command for current workspace? (Similar to Ctrl+Enter for opening file in another window?).

**Comment by bpasero** [comment]
@octref I think this is a matter of making sure that the value is written into the correct place. If it is defined in the workspace it must be written to the workspace, otherwise the change would not have any effect. I think @isidorn and @sandy081 are looking into the adoption of that for the places where we write to settings. 

Of course this requires initially that the value is in the workspace settings already, so it requires a bit of work from the user.

**Comment by isidorn** [comment]
@octref @bpasero What you are discussing is captured in https://github.com/Microsoft/vscode/issues/37351
