### ISSUE TITLE
Replace box is not properly sized sometimes

### ISSUE THREAD

**Issue by zesik** [Microsoft/vscode#36901]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open Find widget (choose Edit -> Find).
2. Resize the Find widget.
3. Close the Find widget.
4. Open Find widget with replace feature (choose Edit -> Replace).
5. Width of the Replace textbox is not same as the Find textbox, while expecting them to be same.

Reproduces without extensions: Yes

**Comment by moskal91** [comment]
It does not reproduce for me (Windows 10 x64, VSCode 1.17.2, extensions disabled).

**Comment by zesik** [comment]
@moskal91 Strange...I can reproduce this problem on all platforms that I have access (macOS, Linux, Windows 10 x64 in a VM) with version 1.17.2.

**Comment by moskal91** [comment]
@zesik I don't have access to other platforms now, but this is how it works for me:
![replace_bug](https://user-images.githubusercontent.com/9036050/32163945-46c1668c-bd5e-11e7-875e-09c714e4eb94.gif)

Maybe this bug appears only in VM or something.

**Comment by zesik** [comment]
@moskal91 Your recording actually shows exactly how this bug is reproduced.

Please note difference of green bounding boxes of two text boxes in the Find widget. When opened, bounding box of the Replace textbox is much wider than it of the Find textbox (where they should be same as each other). Also, please try to resize the Find widget and see how bounding box of the Replace textbox changes.

**Comment by octref** [comment]
@moskal91 I guess that's what @zesik meant:

![box](https://user-images.githubusercontent.com/4033249/32185846-9c205878-bd5d-11e7-8f52-05fac9702990.gif)

Input box of find and replace should be the same length, however they are not if you do Find -> Resize Find Box -> Replace.

**Comment by moskal91** [comment]
@zesik  @octref Ok, sorry for misleading, I thought it was about whole widget box, not just text field inside it, I see it now!
