### ISSUE TITLE
Bring back the infinity blue icon.

### ISSUE THREAD

**Issue by parwat08** [Microsoft/vscode#36909]
This logo is way better than all of the currently shown icons.
Don't why microsoft is so poor at design? What are they smoking?

![31985754-c56b8dba-b998-11e7-9705-a7f984433049](https://user-images.githubusercontent.com/19905275/32005874-1b278980-b9c5-11e7-9918-23182a0e884c.png)

And then they plan to bring this! WT*?

![31986061-a3fad734-b999-11e7-9d66-a68a091f2535](https://user-images.githubusercontent.com/19905275/32006045-7b0fe5ae-b9c5-11e7-8b76-1a4e6b99799c.png)

**Comment by bpasero** [comment]
The reasons are nicely summarised here: https://code.visualstudio.com/blogs/2017/10/24/theicon
