### ISSUE TITLE
output format error of vscode

### ISSUE THREAD

**Issue by mbzls** [Microsoft/vscode#36900]
- VSCode Version:1,17.2
- OS Version:windows 10

> 
> ID	Class
> 	xl001	xl002	xl003	xl004	xl005	xl006	xl007	xl008	xl009	xl010
The two line should be in one line.

I write a simple Perl script (test.pl) to make a file to match another. The perl script is
```
#!/usr/bin/env perl -w
use strict;
use feature 'say';

open F, "<", $ARGV[0]; #class**_.file1_**. The content is(split by \t): ID\tclass
my %hash;
while (<F>) {
    chomp;
    my @in = split( /\t/, $_ );
    $hash{ $in[0] } = $in[1];
}
close F;

open FF, "<", $ARGV[1]; #another **_file2_** to make a match. the content is (split by \t): ID	ml001	ml002	ml003	ml004	ml005	ml006	ml007	ml008	ml009	ml010
while (<FF>) {
    chomp;
    my @in2 = split( /\t/, $_, 2 );
    say "$in2[0]\t$hash{$in2[0]}\t$in2[1]";
}
close FF;
```

Steps to Reproduce:

1. **_test.pl file1 file2 >out.file.txt_**  #this perl script was run by the terminal (bash, zsh) integrated in vscode.
2. the matched line in the output file has been split into 2 lines.
3. I have made a test by cmd, all things ok. I think the problem may be caused by the default integrated terminal in vscode?

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
@mbzls can you take a screenshot of the issue within the integrated terminal and also of the desired output in cmd?

**Comment by mbzls** [comment]
![image](https://user-images.githubusercontent.com/33092483/32032749-5726bd9a-ba3b-11e7-93d9-0dd98d2a3cc3.png)
The figure is the output file, which was produced through the integrated terminal in vscode by (test.pl file1 file2 >out.file.txt).

![image](https://user-images.githubusercontent.com/33092483/32032874-de7b85dc-ba3b-11e7-96f7-f4291a7fc06d.png)
The figure is the output file, which was produced through the cmd by (test.pl file1 file2 >out.file.txt).

**Comment by Tyriar** [comment]
@mbzls which part of the code exactly is meant to be sending the line feed character? Can you identify it and come up with a minimal repro case?

Also is this under WSL?

**Comment by mbzls** [comment]
@Tyriar just follow my steps as above. you will find the problem.

yes, this is under wsl. ubuntu, downloaded from windows store.

**Comment by Tyriar** [comment]
Not sure what I'm doing wrong:

<img width="512" alt="screen shot 2017-12-28 at 11 31 42 am" src="https://user-images.githubusercontent.com/2193314/34421199-c3ac1416-ebc2-11e7-8c6c-a2fc5d501ec6.png">

What's meant to be in file1 and file2?
