### ISSUE TITLE
Windows 10 x64: High Ram Usage

### ISSUE THREAD

**Issue by seanyu4296** [Microsoft/vscode#36910]
Is this normal for a windows user? 

- VSCode Version: 1.17.2
- OS Version: Windows 10

Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/11349232/32006576-b6194140-b9d9-11e7-96cd-8eb90e1637e9.png)

**Comment by dbaeumer** [comment]
Yes, this is not unusual and expected. What kind of project do you work on?

**Comment by seanyu4296** [comment]
A Javascript Front-end project (Reactjs and webpack)

**Comment by dbaeumer** [comment]
Then these number make sense.
