### ISSUE TITLE
Search across files only searching across open editors, not all files in the open folder

### ISSUE THREAD

**Issue by billybook** [Microsoft/vscode#36917]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17017
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
php-pack|fel|1.0.1

---

Steps to Reproduce:

1.  Close all open editors in a folder
2.  ctrl+shift+f
3.  search for a term that should be in one or more files

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Are you searching in OneDrive? Does this happen in all folders or just a particular folder? 
Are there any errors in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by billybook** [comment]
The files are in OneDrive but synced locally for offline access.  I also tried it on multiple folders on multiple computers, in each case using files synced via OneDrive.  Based on your question, I copied the files outside of the OneDrive folder, and the search worked fine, so it looks like it might be related to changes that were part of the fall update to Windows.  There are no output errors.

**Comment by billybook** [comment]
Duplicate issue #35433
