### ISSUE TITLE
indexing file type feature webstorm 

### ISSUE THREAD

**Issue by thiagoadriano** [Microsoft/vscode#36918]
It would be interesting to have the same type of file indexing that the webstorm has where it can reference variables and objects even though it does not import files

**Comment by dbaeumer** [comment]
@thiagoadriano you are talking about JavaScript. Right ?

**Comment by mjbvz** [comment]
@thiagoadriano Also please describe what you are trying to achieve. Can you provide a small example project description and explain what the desired behavior of this feature would be for it

**Comment by thiagoadriano** [comment]
Yes, I speak of javascript but also of other languages ​​as well.
In javascript for example if I give an "object." I do not have an autocomplete of a javascript made in another file and arranged by an IFFE and noticed that it does not have the same autocomplete used by typescript. I also see that in other languages ​​does not have an explanation of files not referenced by import a brevity gave variables used in them.

Example:
In the webstorm we have a file called file1.sass that contains these variables:
$colorPrimary: # 000
$fontFamyly: 'Arial'

I have a second file called file2.sass where I created the style
div
  color: $

if I call the dollar sign indicating that I want to put a variable what the webstorm does is open a poup with all the variables created in the files it indexed being used publicly. as I write it is filtering showing the ones that exist with the name that I have already typed.

This helps a lot to remember the name of the variables and methods that are in other files.

Remember that I used the sass example that occurs to me now in use but this happens for both pure javascript.

I see that the autotype typecomplete is very good because of the typing of the variables and methods. More for pure javascript and other languages ​​do not work that way.

**Comment by mjbvz** [comment]
For sass, I believe we are tracking this with https://github.com/Microsoft/vscode/issues/6734

For JavaScript, I'd like to understand the desired behavior in more detail. File indexing is really more of an a implementation detail.

Can you please put together some example code or a small example project that shows what is currently not supported. A few important points:

* Are you using modules, or are you working with globals?
* Do you have a [jsconfig.json](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson)?
* If you are using a module system, how are you importing and exporting objects?
