### ISSUE TITLE
Open to the side, actually opens to the bottom

### ISSUE THREAD

**Issue by alfordt** [Microsoft/vscode#36914]
- VSCode Version:1.17.2
- OS Version: Win 10

Steps to Reproduce:

1. Right click a markdown file
2. Select Open to the Side

This also affects open preview to the side.  I don't want to view top to bottom and there appears no way to customize the interface now.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
The preview uses the standard editor layout. Support for more customizable layouts is tracked by #14909 and similar. 

Closing as correctly labeling the `open preview to side` button based on horizontal / vertical editor splitting is not possible and I don't see being prioritized within the next 6-12 months
