### ISSUE TITLE
Code formatter option

### ISSUE THREAD

**Issue by Pok-Pok** [Microsoft/vscode#36916]
In full Visual Studio there is a really neat formatter option: insert space before opening brace and after closing brace (any kind of brace, square, regular or curly). I cannot find the same in VSCode. I it is the only feature that I'm missing right now in VSCode. Or is there such an option already? Should not be tied to a particular language, but my interest is in JavaScript. This should be a feature request, but I have no idea how to mark it as such :-D

**Comment by mjbvz** [comment]
Try these settings for the built-in formatter:

```
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true
```

and possibly:

```
"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true
```

**Comment by Pok-Pok** [comment]
You hot it backwards: it should be **BeforeOpening** and Space**AfterClosing** (not **AfterOpening** and **BeforeClosing**) and no matter if it is empty or non-empty brackets :-D

**Comment by mjbvz** [comment]
Can you provide some examples of the expected formatting then
```js
foo (1, 2, 3)
```

**Comment by Pok-Pok** [comment]
Yes, that would be exactly right:

function some_name (arg1, arg2) {
    some_array [index] = arg2;
}

**Comment by mjbvz** [comment]
Yes, this is a more uncommon formatting that is no supported by the TypeScript formatter which we include. Extensions can contribute more advanced formatters though, so one of those may offer what you are looking for. [Eslint's func-call-spacing](https://eslint.org/docs/rules/func-call-spacing) for example would enable this for function calls at least. Try searching the marketplace to see if any of the formatters support what you are looking for

**Comment by Pok-Pok** [comment]
Strange that you call that „uncommon formatting”; it's actually the norm in typography. Even math text follows the rule. Anyway, I hope it will be implemented some day and I won't need to manually correct the automatic formatting :-).
In the mean-time I'll have a better look at those Eslint options, maybe I'll get out something of those.
Thanks!
