### ISSUE TITLE
onDidChangeVisibleTextEditors breaks after adding second workspace

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#36915]
- VSCode Version: Code - Insiders 1.18.0-insider (c1e079b6ccfad9ead105c44a84e862ffc5250222, 2017-10-25T04:18:36.616Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.12
githistory|don|0.2.3
tslint|eg2|1.0.12
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.4.0

---

Steps to Reproduce:

1. Using https://github.com/Microsoft/vscode-extension-samples/tree/master/basic-multi-root-sample
2. Add the following lines to the `activate` function:
```
context.subscriptions.push(window.onDidChangeVisibleTextEditors(e => {
        console.log("Changed") // Put breakpoint here
    }));
```
3. Press f5 to start debugging
4. Open a folder
5. Click around some files, notice `onDidChangeVisibleTextEditors` is being triggered
6. File -> Add folder to workspace
7. Click around some files, notice `onDidChangeVisibleTextEditors` is no longer triggered

**Comment by bpasero** [comment]
Maybe related to the extension host restart?

@CoenraadS we do not activate your extension again after a restart, so maybe your extension is not activated in this case? What is your activation configuration for the extension?

@alexandrudima I assume my statement is right, we are not re-activating extensions that were activated before restarting the extension host?

**Comment by CoenraadS** [comment]
The other events do fire (e.g. `onDidCloseTextDocument`), its just `onDidChangeVisibleTextEditors` doesn't.

Mine activates on *

**Comment by jrieken** [comment]
I'd say this is a problem with the debugger as I do see those messages being printed

**Comment by CoenraadS** [comment]
I will see if I can make a video

**Comment by CoenraadS** [comment]
If we ignore the debugger and just look at the log in dev tools, it does not log there either after the second workspace is added. This is 100% reproducible for me every time.

**Comment by jrieken** [comment]
>  This is 100% reproducible for me every time.

Please refine your steps or tell me what I am doing wrong. This my extension code and it produces the video below

```ts
    console.log('Here-6')
    context.subscriptions.push(vscode.window.onDidChangeVisibleTextEditors(e => {
        console.log("Changed -> " + e.map(e => e.document.fileName)) // Put breakpoint here
    }));

```

![oct-25-2017 19-16-20](https://user-images.githubusercontent.com/1794099/32012712-11a4615a-b9b9-11e7-9e5a-8b150b48dd27.gif)

**Comment by CoenraadS** [comment]
Ok I finally figured it out, it is related to the folder I am opening...

I was testing on this repo as my second workspace: https://github.com/CoenraadS/vscode-Disable-Ligatures

1. Open any folder
2. Add vscode-Disable-Ligatures as a second workspace

Then I get `Error: Ignoring launch.version as launch is true` as an error, but I was just ignoring it because I didn't know what it meant. But it turns out the whole extension host is now crashed or something, but I suppose it is a different issue. 

Seems to have been addressed here: https://github.com/Microsoft/vscode/issues/36808

Sorry for wasting your time.

**Comment by jrieken** [comment]
> Then I get Error: Ignoring launch.version as launch is true as an error, but I didn't pay attention to this.. But it turns out the whole extension host is now crashed or something, but I suppose it is a different issue.

@sandy081 This is interesting

**Comment by CoenraadS** [comment]
It's fixed in today's insiders and working fine :)

**Comment by isidorn** [comment]
@CoenraadS great, thanks for trying it out!

**Comment by sandy081** [comment]
Yeah, fixed it yesterday and is available in today's insiders.
