### ISSUE TITLE
Occurence highlighting of variables in file obscures text selection

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#36919]
_From @Hypernut on October 20, 2017 12:51_

- Operating system name and version: Windows 8.1
- VS Code version: 1.17.2
- PowerShell extension version: 1.4.3
- Output from `$PSVersionTable`:

When you try to select a part of the code, the selection highlighting (green) gets hidden by the  (I dont know how to call it) syntax help(?) of the variable preview highlighting (light gray). This is very annoying because you cant see what parts of the code you did hightlight. as long as the gray highlighting is there, you cant even highlight anything.

![selection](https://user-images.githubusercontent.com/17964914/31821385-3f272972-b5a5-11e7-8593-bebb37f3cde8.gif)

_Copied from original issue: PowerShell/vscode-powershell#1061_

**Comment by daviwil** [comment]
This seems like a bug with VS Code itself, I'll move the bug there for you.

**Comment by alexandrudima** [comment]
@Hypernut This will happen when using `workbench.colorCustomizations` and using opaque background colors for the editor decorations. What values are you using for `workbench.colorCustomizations` ?
