### ISSUE TITLE
Suppress annoying JSON errors

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#36922]
- VSCode Version: Code - Insiders 1.18.0-insider (aaec2980609a4bbe44d0cfe2d3f78c85cba1be83, 2017-10-24T05:11:48.927Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.5
material-icon-theme|PKi|2.2.3
vscode-eslint|dba|1.4.0
gitlens|eam|5.7.1
tslint|eg2|1.0.12
prettier-vscode|esb|0.24.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
stylus-supremacy|thi|2.5.1
vim|vsc|0.10.2

(1 theme extensions excluded)

---

As I'm editing package.json of course the file would not always be valid.
This error is very distracting:

![json](https://user-images.githubusercontent.com/4033249/32014874-362b169e-b974-11e7-97d6-5c69850ce890.gif)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Please try to reproduce it without extension. For that start VS Code with the parameter: `--disable-extensions`

**Comment by octref** [comment]
OK, I somehow can't repro it either now...With or without extensions.
