### ISSUE TITLE
Rulers are not rendered correctly when using zoomLevel

### ISSUE THREAD

**Issue by jl98** [Microsoft/vscode#36921]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
MagicPython|mag|1.0.12
atom-keybindings|ms-|3.0.2

---

Steps to Reproduce:

1. Entered "80" into array value for editor.rulers in user (not workplace) settings. Ruler rendered here.
2. Changed font size of editor from 12 to 14. Ruler did not render.
3. Later changed font size of terminal to match (changed from 12 to 14). Ruler rendered afterwards.

I couldn't reproduce this bug directly. I'm not sure what caused the ruler to not render, but it seems that it may be correlated to the different font-width of a different font-size?

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@jl98 Are you perhaps using a non-zero value for `window.zoomLevel` ?

**Comment by jl98** [comment]
I believe that might have been the case—will rulers only render properly if window.zoomLevel is 0?

**Comment by alexandrudima** [comment]
Yes, `window.zoomLevel` is [buggy](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Azoom)

For pixel perfect rendering I recommend not using zoomLevel at all and configuring `fontSize`, `lineHeight`, etc. Almost everything can be configured except the explorer and the tabs. You can upvote that in #519

I would recommend using `window.zoomLevel` only when projecting to an audience and never for professional daily usage.

**Comment by jl98** [comment]
Got it, thanks!
