### ISSUE TITLE
nothing happen after click the url in 1.18.0-insider

### ISSUE THREAD

**Issue by czmecho** [Microsoft/vscode#36927]
- VSCode Version:1.18.0-insider
- OS Version:win 10 1709

Steps to Reproduce:

1.Ctrl + click the url
Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Also not working in my environment:
- VSCode Version: Code - Insiders 1.18.0-insider (c1e079b6ccfad9ead105c44a84e862ffc5250222, 2017-10-25T04:18:36.616Z)
- OS Version: Windows_NT x64 6.1.7601

**Comment by dbaeumer** [comment]
This got fixed with the next insider build.
