### ISSUE TITLE
Markdown: Syntax highlighting not displaying correctly

### ISSUE THREAD

**Issue by DaveyD** [Microsoft/vscode#3692]
I've been writing markdown files in VScode recently, and I'm enjoying very much.
I'm having an issue with the preview display:
I can't get get syntax highlighting for code to work. In markdown view, the syntax highlighting does work, but in preview it just shows up as plain text in a gray box.  (I am currently specifically looking for VB)  

---
Here is a screenshot of what I am seeing. You can see that on the left side, I am getting syntax highlighting for Python, but not for VBnet, and on the right side, I am not getting any syntax highlighting.

[![][1]][1]

  [1]: http://i.stack.imgur.com/UXnjf.png

**Comment by mjbvz** [comment]
Just looking into this bug a little, it looks like some languages (css, php, html) are correctly syntax highlighted in the preview, while most others are not:

<img width="1098" alt="screen shot 2016-03-07 at 3 13 57 pm" src="https://cloud.githubusercontent.com/assets/12821956/13586683/50f16844-e477-11e5-8da0-46fb1fab9378.png">

Syntax highlighting in the preview and the editor also do not always match. For example, php gets highlighted in the preview but not the editor, and python gets highlighted in the editor but not the preview.

**Comment by bpasero** [comment]
Yes, we have some inconsistency. Plan to fix this when markdown gets moved to its own extension.

**Comment by mattacosta** [comment]
One of those inconsistencies is PHP only working when there is an open tag. It's not required for markdown highlighting:
```php
// Does not have "<?php" tag.
if (1 + 2) {
  $x = 3;
}
```

**Comment by nchammas** [comment]
I'm having this issue as well with Python inside Markdown code blocks. It highlights correctly in the editor, but in the preview it doesn't highlight at all.

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension we ship in June.

**Comment by dbaeumer** [comment]
Verified using simple python and php examples.

**Comment by colhountech** [comment]
Is there something different I have to do to "switch-on" for c#. Seems to work for Java but not c#

![vscode-insider](https://cloud.githubusercontent.com/assets/977872/16681015/3d1cacb0-44ea-11e6-8bbe-19a507278c92.PNG)

Running 1.3.0-insider with the c# extension 1.0.3-rc2

I have **.NET Core RC2 Preview1** *and* **.NET Core 1.0.0 RTM Preview 2** installed if that helps.

**Comment by jods4** [comment]
Works for me after upgrade to 1.3 (tested on Typescript and Html)! 👍 

One question, though: is there a way to change the default color scheme? As can be seen above, the theme is not the same in MD editor (or VS Code generally) and in the preview and honestly... the default theme in preview is too much Skittles for me 😒
