### ISSUE TITLE
Reference a type of a module from JS

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#36929]
- VSCode Version: 1.17.2
- OS Version: macOS

It's possible to do in VS Code? https://stackoverflow.com/questions/41298262/vscode-reference-a-type-of-a-module-from-js

For .e.g I tried to do this with `PhantomJS` which is downloaded auto by ATA and it gives me IntelliSense if I do `require('phantom').`, but if I use:

```js
/** @type {PhantomJS} */
let phantom;
```

I don't get any IntelliSense on `phantom` it says `any`...

**Comment by bsvipas** [comment]
I know how to make it work for `phantom`, you need to `import` instead of `require`. But why then it doesn't works with `require`?

**Works**
```js
import phantom from 'phantom';
/** @type {phantom.PhantomJS} */
let session; // PhantomJS
```

**Doesn't works**
```js
const phantom = require('phantom');
/** @type {phantom.PhantomJS} */
let session; // any
```

**Comment by mjbvz** [comment]
Posted response on SO: https://stackoverflow.com/a/46940116/306149
