### ISSUE TITLE
.deb package from APT repository has corrupt xz compression (again)

### ISSUE THREAD

**Issue by schachmat** [Microsoft/vscode#36920]
Similar to #35992 http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.18.0-1508736309_amd64.deb has corrupt xz data again.

```
$ wget http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.18.0-1508736309_amd64.deb
…
2017-10-25 19:48:45 (36.0 MB/s) - ‘code-insiders_1.18.0-1508736309_amd64.deb’ saved [43685472/43685472]
$ ar vx code-insiders_1.18.0-1508736309_amd64.deb
x - debian-binary
x - control.tar.gz
x - data.tar.xz
$ xz -d -c <data.tar.xz >/dev/null
xz: (stdin): Compressed data is corrupt
```

Could you please:

1. Fix this immediate issue
2. Set up your own monitoring for this class of issues

You should also try to find the cause of these corrupt xz compressions (the file could just be truncated?) to prevent distributing broken packages in the future.

Thanks!

**Comment by Tyriar** [comment]
@schachmat does installing via `dpkg` work? Not sure what is going on here as it appears to happen randomly and we're building the deb package with `dpkg-deb` https://github.com/Microsoft/vscode/blob/1f74e78d6640569d71b04194d292fb2161be84d0/build/gulpfile.vscode.linux.js#L113, not compressing it ourselves.

**Comment by michael-schaller** [comment]
The package isn't installable via ```dpkg```.

After a package build with ```dpkg-deb``` you can check the package with ```lintian```. If ```lintian``` succeeds you can be sure that the package itself is fine but please be aware that ```lintian``` can be quite pedantic as a package linter.

I'm not sure though if the package build is really the issue. To me it sounds more likely that the upload to packages.microsoft.com is incomplete. If you upload the package can you also verify the upload afterwards by downloading it again and doing a comparison?

**Comment by schachmat** [comment]
This is still not fixed. Do you have an update on your investigation?

Michaels suspicion with an incomplete upload seems reasonable. The .deb file is an `ar` archive, which just concatenates the content files (with a header each), so if the upload was incomplete, this would lead to this exact behavior, where the last file in the `.deb` is corrupt/incomplete.

**Comment by chrmarti** [comment]
I have removed it from the repo. Please confirm. Thanks.

**Comment by schachmat** [comment]
Thanks. That fixed the immediate problem. I've created #38324 as a follow-up item to implement a sustainable solution.
