### ISSUE TITLE
problemas tecnicos

### ISSUE THREAD

**Issue by MarkoBV19** [Microsoft/vscode#36937]
Buenas tardes... no se si alguien mas le sucedió lo mismo, pero al realizar la ultima actualización no puedo ver los cambios realizados en mi proyecto al solo actualizar...  en caso de querer verlos tengo que reiniciar mi equipo, alguna solución para esto?? 

de antemano gracias, que tengan buen dia buen día

**Comment by MarkoBV19** [comment]
puedes explicar amigo?? no comprendo

**Comment by nickcassol** [comment]
@MarkoBV19 Estoy bastante seguro que en este apartado hay personas que hablan inglés solamente, así que si quieres recibir soporte de parte de ellos, lo mejor sería comunicándote con ellos en inglés, si es que puedes, obvio.

Yo podría traducir si es que el equipo no tiene alguien de habla hispana
@dbaeumer I could translate if you guys don't have a Spanish-speaking person in your team.

**Comment by dbaeumer** [comment]
@nickcassol that would be very helpful.

**Comment by nickcassol** [comment]
@dbaeumer Ok, he is saying the following:
"Good evening, I don't know if this has happened to someone else, but with the last update I haven't been able to see the latest changes in my project by just refreshing, the only way to do it is by rebooting my pc, is there any solution to this?

@MarkoBV19 Si pudieras dar más detalles sobre tu problema sería muy útil :).

**Comment by dbaeumer** [comment]
@MarkoBV19 what exactly do you mean by changes to my project. Edits you do inside VS Code. File changes outside of VS Code ?
