### ISSUE TITLE
Visual Studio Code website favicon is still orange

### ISSUE THREAD

**Issue by SEGEEK** [Microsoft/vscode#36934]
Steps to Reproduce:

1. Browse to https://code.visualstudio.com/
2. Look at favicon color
![image](https://user-images.githubusercontent.com/3335010/32019603-64a5ebce-b993-11e7-872d-f56ef0dfd462.png)

**Comment by octref** [comment]
Thanks for pointing out, we are tracking this in an internal repo and will change it soon.
