### ISSUE TITLE
Triple click should include newline

### ISSUE THREAD

**Issue by btraut** [Microsoft/vscode#3693]
VSCode uses non-standard behavior for triple-clicking from every other text editor on the market (including Visual Studio):

When triple-clicking on a line of code, the entire line should be selected, **including the newline**. VSCode skips the newline in its selection.

**Comment by Tyriar** [comment]
The new line is correctly picked up on triple click on Ubuntu 15.10/vscode 0.10.10-insider.

**Comment by alexandrudima** [comment]
Fixed in stable channel.

**Comment by ngtrian** [comment]
How to triple click without a newline?
