### ISSUE TITLE
VSCode shows .json file imports as error.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#36935]
![image](https://user-images.githubusercontent.com/1499188/32020786-c3b74034-b9ea-11e7-88f6-a1a56e407b10.png)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/7071

See these issues for some additional context:

- https://github.com/Microsoft/TypeScript/issues/16588
- https://github.com/Microsoft/TypeScript/issues/18431
