### ISSUE TITLE
FR: Exclude workspace folders from the problem panel/linting

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#36936]
All Versions/OS

I now use the multi- folder workspaces to add a folder with utility files, issues, WIP files et cetera.
None of these folder contents are either in git or used directly in the projects, however, they
get Processed for errors unnecessarily.  I searched for but was unable to locate an option
to exclude such folders from the problem analysis.  If this does not exist, appropriate good addition?

**Comment by sandy081** [comment]
Duplicates #22289
