### ISSUE TITLE
Menus which are too tall can obscure the menubar

### ISSUE THREAD

**Issue by mcclure** [Microsoft/vscode#36938]
- VSCode Version: 1.17.2 b813d
- OS Version:  Windows 10 Pro Version 1703
Reproduces without extensions: Yes

Steps to Reproduce:

1. Open VS Code on a very short monitor. Mine is 1388x788.
2. Click the "View" menu.

Observed behavior:

![Result](https://pbs.twimg.com/media/DNAnkOZWsAEmuj-.jpg:orig)

The "View" menu is tall, and it is obscuring both the title bar of the window and the other menu titles past "View".

This is very inconvenient because it means you cannot "slide" from (for example) the File menu to the Go menu. As soon as the cursor reaches "View", View obscures the other menu items and your cursor gets caught there. In order to reach the "Go" menu from that point you have to do a strange dance of ducking the cursor backward and then looping it around View.

Expected behavior: The standard idiom on Windows, and the behavior of Visual Studio 2015, is to draw the menu strictly underneath the menu bar, cropping its lower items if it is too tall.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34822
