### ISSUE TITLE
FileSystemProvider: cannot close modified file that has been deleted from disk

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#36945]
- VSCode Version: Version 1.18.0-insider (1.18.0-insider), 509630ffe3fabf2e1f49b416bb83f5ff0877b042
- OS Version: 10.12.6

Steps to Reproduce:
1. Create a file system provider; provide file change notifications
2. Open a remote file; edit it and do not save the changes
3. Delete the file remotely
4. vscode will append "(deleted from disk)" to the file's tab
5. Close the tab
6. Observe: vscode removes the text "(deleted from disk)", but does not close the tab or ask to save it. The file cannot be closed unless you spam-click the "x".

**Comment by isidorn** [comment]
fyi @jrieken @bpasero

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by siegebell** [comment]
@bpasero I launched a code-insiders (81cca6cc606eeca3443998025bff3893fcfe3ad5) debug instance with "--verbose" and tried this out, but nothing was output to the debug console in response the deleting a file or trying to close its tab.

**Comment by bpasero** [comment]
@siegebell can you share your extension code?
