### ISSUE TITLE
Insiders links to web stopped working

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#36940]
- VSCode Version: 1.18 c1e079b6ccfad9ead105c44a84e862ffc5250222
- OS Version: Win10

Steps to Reproduce:

1. Click any link to http or https or other external resource

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
Actually, I can't follow any link in editor.

**Comment by dbaeumer** [comment]
This got fixed for the next insider build.
