### ISSUE TITLE
German translation "Forward": "Weiter" vs "Weiterleiten"

### ISSUE THREAD

**Issue by till213** [Microsoft/vscode#36952]
- VSCode Version: Code 1.16.1  27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z  - OS Version: Darwin x64 16.7.0 - Extensions: Extension|Author  truncated |Version -|-|- ng-template|Ang|0.1.7 html-snippets|abu|0.1.0 tslint|eg2|1.0.11 Go|luk|0.6.66 cpptools|ms-|0.14.0 - Steps to Reproduce: 1. 2. !- Launch with  code -disable-extensions  to check. -> Reproduces without extensions: Yes/No
 
Dear all, this is a tiny little issue (almost) not worth mentioning, but since I like Code so much I thought I'd report it anyway: it's about a German translation which is slightly misleading.

I am referring to the entry in the menu "Los" ("Go"), the second one, right after the (correct) "Zurück" ("Back"): while "Weiterleiten" is a (one of the many) correct translation of "Forward" (I assume that's the word being used in the English version) it is not the one we are looking for here. 

The one which would make sense here is "Vorwärts", which is really the opposite of "Zurück" ("Back").

Just like in English the verb "weiterleiten" is used as in "Ich leite ihnen die Email weiter" ("I will forward you this email"). But "I go forward" would be "Ich gehe vorwärts", as opposed to "Ich gehe zurück" ("I go back").

**Comment by maxibanki** [comment]
Hi,
I've created an request on [transifex](https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/vs_code/111042507). You can vote for it that it will be approved. More information about the translation process you will find [here](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).

**Comment by till213** [comment]
Hi,

Oh, it seems like everyone can contribute to the translations :) I'll have a closer look how that works.

Thanks!
  Oliver

**Comment by danyeh** [comment]
Thank you for contributing! New translation takes effect now.
