### ISSUE TITLE
[Extension API] Keybindings for caplocks

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#3695]
Related: https://github.com/Microsoft/vscode/issues/3223, https://github.com/VSCodeVim/Vim/issues/157

How can an extension distinguish between `a` and `a`+`capslock`?

In both cases, the extension sees `a` as being pressed. With the `capslock` keybinding we can tell if the key was pressed, but there's no way to determine if capslock is currently ON vs OFF.

**Comment by isidorn** [comment]
ping @alexandrudima

**Comment by alexandrudima** [comment]
@jpoon 
Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code - it shows how to capture typed characters (not through keybinding rules).
