### ISSUE TITLE
Typescript crash

### ISSUE THREAD

**Issue by morreelsm** [Microsoft/vscode#36953]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.22.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.0
vscode-npm-script|eg2|0.3.1
vscode-npm|fkn|3.3.0
output-colorizer|IBM|0.1.2
search-node-modules|jas|1.2.0
sass-indented|rob|1.4.5
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@morreelsm can you pleas provide information about how to reproduce this. Best would be a workspace we can clone that demos the behavior.
