### ISSUE TITLE
Paths in the file label get cut off at the end, in the middle of folder names, instead of at the beginning

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#36958]
| SCM viewlet | Git |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/32038715-80e43938-ba2b-11e7-9c7d-34c15c76e5e0.png) | ![image](https://user-images.githubusercontent.com/5047891/32040257-76c45d7a-ba30-11e7-861c-03c4cee65305.png) |

Notice how the paths in Git get cut-off at the beginning, and full folder names are removed (folder names are not cut-off in the middle)

**Comment by joaomoreno** [comment]
@bpasero Can we do this in the file label?

**Comment by bpasero** [comment]
No.
