### ISSUE TITLE
Window title updates with opened file name only after window resize

### ISSUE THREAD

**Issue by mtsh1000** [Microsoft/vscode#36955]
- VSCode Version: any recent stable/insiders
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Open any file
2. The window title will remain unchanged until you resize or min-max the window

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
I can not reproduce this.
On what OS are you?
Can you also reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
There are many reported issues around the title not being up to date but I never found out what the cause of this is. Very likely an electron issue though if resizing fixes it.

**Comment by mtsh1000** [comment]
@isidorn , I have updated the issue comment

**Comment by isidorn** [comment]
@mtsh1000 please answer my other question, can you reproduce with latest vscode insiders

**Comment by mtsh1000** [comment]
Yes

**Comment by mtsh1000** [comment]
This is indeed electron bug [https://github.com/electron/electron/issues/10897](url)

**Comment by isidorn** [comment]
@mtsh1000 Can you please file this one against electron then please?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31536
