### ISSUE TITLE
Integrated Terminal wrap the character after restart vscode without closing the terminal first

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#36957]
- VSCode Version: 1.18-insider Commit 8bc02c7443305a0db442c11b76e67d6f4929dc0e
- OS Version: Ubuntu 16.04

![image](https://user-images.githubusercontent.com/8751130/32039180-af2712c8-ba5f-11e7-9c69-ddf8969835d6.png)

It's happening by disable or enable all extensions

Steps to Reproduce:

1. Open VS Code
2. Launch Terminal
3. Restart VS Code without closing the terminal

Although pressing any key at terminal would fix the problem

**Comment by Tyriar** [comment]
I'm not sure what the issue is exactly, can you elaborate a little more?

**Comment by tangorboyz** [comment]
let's sat before I close vs-code, my terminal prompt is:

`(env) dhawu@tangorboyz:~/Documents/code/python/django/bitbucket/django_blog$`

After restart vs-code without closing the the integrated terminal, the terminal prompt become:

`ango_blog$ django/bitbucket/dja`

**Comment by Tyriar** [comment]
How are you restarting VS Code exactly?

**Comment by tangorboyz** [comment]
I just click the window exit button and then launch vs code  again.

**Comment by Tyriar** [comment]
@tangorboyz that will tear down the old terminal process and spawn a new one. Do you know how you got it into the good state?

`(env) dhawu@tangorboyz:~/Documents/code/python/django/bitbucket/django_blog$`

**Comment by tangorboyz** [comment]
ya, exactly. I will lose the `(env)`, Anyway terminal will lose it's state, if we close them.

But hey, I notice that the new update for insider already fix that problem.

**Comment by Tyriar** [comment]
Oh it's working in Insiders? Insiders includes changes that are coming in the next version, can we close this off then?

**Comment by tangorboyz** [comment]
Ya..
