### ISSUE TITLE
Same search result appears twice

### ISSUE THREAD

**Issue by mxschmitt** [Microsoft/vscode#36954]
- VSCode Version: Code - Insiders 1.19.0-insider (3c470706ded48fc75c05f86bc4f9c7b0f4d6c708, 2017-11-27T05:14:17.223Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.12
Go|luk|0.6.66
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.16.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Search for ushell
2. The same result will appear twice. One for the absolute path, and the other for the relative path.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/17984549/32037815-585279d4-ba27-11e7-8ebd-244231ae5290.png)

**Comment by roblourens** [comment]
Is this a multiroot workspace? Is the file open?

Can you show the output of the search output panel?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by maxibanki** [comment]
Hm, sorry for the missing information. 
I can reproduce it and think this behaviour is not the correct one.
In VS Code, I opened folder X and opened a file which is in the folder X via the file => open file menu entry. So it was not a multiroot workspace.
Here's the output of the search console:
```
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\.git' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\.svn' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\.hg' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\CVS' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\.DS_Store' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\node_modules' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\dist' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\.vscode' -g '!/Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style\**\bower_components' --max-filesize '17179869184' --no-ignore --follow --fixed-strings -- 'ushell' 'c:\Users\mxs\go\src\removed\mxs\SocketNotifier\projects\zsalt_style' 'c:\Users\mxs\go\src\removed\MXS\SocketNotifier\projects\zsalt_style\webapp\index.html'
 - cwd: c:/
 - Sibling clauses: {}
```
