### ISSUE TITLE
Add support for `@supports (...) {}` syntax in LESS

### ISSUE THREAD

**Issue by omichelsen** [Microsoft/vscode#36950]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.0
gitlens|eam|5.7.1
tslint|eg2|1.0.12
flow-for-vscode|flo|0.7.2
node-debug2|ms-|1.18.3
debugger-for-chrome|msj|3.4.0
vscode-react-native|vsm|0.4.4
---

Steps to Reproduce:

1. Write the valid CSS in a LESS file:

```css
@supports (display: flex) {
  div {
    display: flex;
  }
}
```

2. The editor will highlight `(display: flex)` as an error as well as the closing bracket in the `div`.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This works for me in the latest insiders build
