### ISSUE TITLE
When I first opened the document, the indentation always used two spaces

### ISSUE THREAD

**Issue by zrfzrf1** [Microsoft/vscode#36959]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
jquerysnippets|don|0.0.1
EditorConfig|Edi|0.10.1
tslint|eg2|1.0.11
beautify|Hoo|1.1.1
Angular2|joh|2.7.0
font-awesome-codes-html|med|0.0.7
cpptools|ms-|0.13.1
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
vscode-icons|rob|7.15.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

My Settings:
"editor.insertSpaces": true
"editor.tabSize": 4,
"editor.detectIndentation": false,

When I first opened the document, the indentation always used two spaces instead of four.
I want to start without checking the indentation, and use all four spaces, so that's settings right?

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@zrfzrf1  `EditorConfig` is an extension that constantly tweaks the editor indentation settings. Perhaps you have an `.editorconfig` file somewhere that drives that behaviour. In any case, you can disable the `EditorConfig` extension and those vs code settings should be respected.

Can you please confirm that is the case ?
