### ISSUE TITLE
Error while starting - reg.exe Access denied -> Disable Registry Access

### ISSUE THREAD

**Issue by ropetry** [Microsoft/vscode#36956]
We got this error on our Systems as the registry access is protected. Normal Users can´t use Registry reg.exe Tool .Visual Studio Code wants to get some Data via a winreg function, whichs uses reg.exe to query the local registry.
For Terminal Services or locked down workstations it is normal to deny access to reg.exe for normal users. you can use Group Policy for that or special tools.
Issue is a error message on the System if you start Visual Studio Code.
I think those requests are only for telemetry data, they are found in https://github.com/Microsoft/vscode/blob/5ebdf7319751a864157a1fc932cd21c4782e8e30/src/vs/platform/telemetry/node/workbenchCommonProperties.ts .  Function function getSqmUserId and so on.
Is there a way to disable this or test reg.exe access and continue without a error message?
If requested i can attach a hardcopy of the error.

thanks.

- VSCode Version: 1.16.1
- OS Version: Server 2008 R2 Terminal Services

Steps to Reproduce:

1. Deny access to reg.exe file via Group Policy on Terminal Server
2. Start Visual Studio Code

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
I'm not so familiar with windows, but is there not a better way to access the registry?
My idea is to **not** use the `reg.exe`. Instead use the available [syscalls](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724875(v=vs.85).aspx).
Is there the ability in NodeJS to interact with them in a clean way? (I found only very small [libraries](https://github.com/streamich/libsys), in the std libs is no syscall lib existing afaik).

**Comment by ropetry** [comment]
I tried to use the local settings to disable updates and telemetry via the config.
{
"update.channel": "none",
"telemetry.enableTelemetry": false,
"telemetry.enableCrashReporter": false
}
as the reg queries are used in the telemetry functions but it doesn´t change the error/behavior 8-).. he still tries to access the registry.

**Comment by ropetry** [comment]
@maxibanki : yes this could be a solution to get off the reg.exe command. in the meantime it would be enough to "if disable-telemetry is true, skip registry functions ". 8-).

**Comment by kieferrm** [comment]
We don't need the sqm information. I'll remove it.

**Comment by ropetry** [comment]
@kieferrm : my hero 8-) ....thx...
