### ISSUE TITLE
Support Workspace launches in a MR workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#36967]
In a multi-root workspace, support workspace launches

**Comment by weinand** [comment]
@sandy081 you mean launch configurations that are not located in the individual folder's .vscode/launch.json but globally in the workspace settings file?

**Comment by sandy081** [comment]
@weinand Yes

**Comment by sandy081** [comment]
@isidorn Implemented support for reading launches from workspace configuration file in multi root workspaces using configuration service.

**Comment by isidorn** [comment]
@sandy081 thanks for this. My work can be found in this PR which will soon me merged to master https://github.com/Microsoft/vscode/pull/41818
