### ISSUE TITLE
Insider 1.18: sidebar forgets its size

### ISSUE THREAD

**Issue by iricigor** [Microsoft/vscode#36963]
### Issue
Sidebar always returns to default width after openning

### Versions
- VSCode Version: Insider 1.18.0, Oct 27 _(it was not happening in previous build!)_
- OS Version: Windows 10

### Steps to Reproduce:

1. Open VS Code
1. Open sidebar if closed
1. Resize side bar
1. Close sidebar
1. Open sidebar

_P.S. Opening and closing side is done by clicking on Explorer icon_

### Expected behavior
Sidebar is the same size as before closing
### Actual behavior
Sidebar has default width

### Reproduces without extensions
Yes

**Comment by bpasero** [comment]
@isidorn probably a regression

**Comment by isidorn** [comment]
@iricigor great catch, thanks a lot
