### ISSUE TITLE
 Broken smooth scroll. Дрыгается скролл при одновлеменно открытой консоли в хроме.

### ISSUE THREAD

**Issue by Ineigo** [Microsoft/vscode#36969]
- VSCode Version: Code - Insiders 1.18.0-insider (509630ffe3fabf2e1f49b416bb83f5ff0877b042, 2017-10-25T05:23:13.412Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|0.24.0
---

Сложно сказать, как это воспроизвести. 
В процессе работы переключаясь из консоли хрома в редактор, перестает работать адекватно мягкий скролл. 

Reproduces without extensions: Yes

**Comment by Ineigo** [comment]
![image](https://user-images.githubusercontent.com/10618646/32045758-c0ebedb4-ba49-11e7-9922-38f545c1154d.png)
заметил что это сочетается с вкладкой Network

**Comment by dbaeumer** [comment]
@Ineigo unfortunately we don't speak Russian. Can you please provide the issue report in English.

**Comment by octref** [comment]
@Ineigo This might already be fixed in 1.8 Insiders: https://github.com/Microsoft/vscode/issues/13612#issuecomment-339961624

Can you give it a try? https://code.visualstudio.com/insiders

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612
