### ISSUE TITLE
Copy Without Syntax Highlighting

### ISSUE THREAD

**Issue by yukulele** [Microsoft/vscode#36960]
There is tow entries in menu to copy:

* Copy <kbd>ctrl</kbd><kbd>c</kbd>
* Copy With Syntax Highlighting

Both have the same effect.

Can you add a "Copy Without Syntax Highlighting" entry"?

**Comment by wolf99** [comment]
It quite surprised me that copying with formatting is the _default_.

Sure, there are sometimes it is nice to copy with the syntax highlighting etc (inserting snippets into documentation maybe), but the general expectation for light-weight editors like this is that copy-pasta is plain text and I for one would want the latter effect most of the time.

**Comment by rebornix** [comment]
Closed in favor of https://github.com/Microsoft/vscode/issues/21071#issuecomment-418887276
