### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by TryingToFindALoginWhichIsNotRegistered** [Microsoft/vscode#36962]
This is nor an issue neither than a wish: Code-folding formattes methods to:

**private function main(){...
}**

would be better (in my opinion) to change it to only one line

**private function main(){...}**

because codefolding is used to save space in the editor. (Btw, native php-support would be nice, for "PHP-Formatter" does not work).
Otherwise: **This editor is more than cool! Best I've ever used! Thanks to dev-team!!**

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Covered by https://github.com/Microsoft/vscode/issues/19690
