### ISSUE TITLE
Annoying Intellisense problem when working on a Golang project.

### ISSUE THREAD

**Issue by SamyGhannad** [Microsoft/vscode#36973]
I'm facing an annoying problem with VS Code when working on a Golang project.
The Intellisense suggestions are pretty much messed up.
1- It has some nonsense items on its list.
2- It is not limited to the target scope, for example when I'm putting a . (dot) after a package name, suggestions are not limited to it, it is actually all possible suggestions combined, including functions and variables from all other packages.
Here is a screenshot

![Bug](https://i.imgur.com/MjJFbPF.png)

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
toml|be5|0.0.3
better-toml|bun|0.3.1
vscode-markdownlint|Dav|0.11.0
python|don|0.7.0
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
json-tools|eri|1.0.2
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
php-pack|fel|1.0.1
auto-close-tag|for|0.5.2
code-runner|for|0.8.2
gc-excelviewer|Gra|1.1.15
vscode-nginx-conf-hint|han|0.0.4
docker-linter|hen|0.4.0
beautify|Hoo|1.1.1
rest-client|hum|0.15.3
phpcs|ika|0.7.0
path-autocomplete|ion|1.6.2
mysql-scratchpad|jbl|0.1.1
csharpfixformat|Leo|0.0.38
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.66
MagicPython|mag|1.0.12
HTMLHint|mka|0.4.0
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
vscode-mongodb|ms-|0.0.1
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
mysql-inline-decorator|odu|0.0.4
erlang|pgo|0.1.1
material-icon-theme|PKi|2.2.3
prettier-now|rem|1.4.9
vscode-sort-json|ric|1.10.2
vscode-format|rya|0.0.6
vscode-nginx|sha|0.4.1
stylelint|shi|0.30.0
php-formatter|Sop|0.2.4
python|tht|0.2.3
write-good-linter|tra|0.0.6
format-all-files|xyk|0.2.0
html-css-class-completion|Zig|1.11.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open a Golang project folder by going to File->Open Folder
2.Try to call a method from another package in the project
3. Check the autocomplete result.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Since this is a "Bug" of the Go extension, please create an issue [there](https://github.com/Microsoft/vscode-go).

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-go#1305
