### ISSUE TITLE
Not work with Cyrillic 

### ISSUE THREAD

**Issue by altaranenco** [Microsoft/vscode#36975]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. Try to load XML file with Cyrillic letters in file name
$xml = [xml](Get-Content -Encoding UTF8 -Path "C:\MaxPatrol_Reports\Отчет Аудит - Серверы - Сектор ИБ 06.06.2017 11-30-00.xml")
2. Have an error 

Get-Content : Cannot find path 'C:\MaxPatrol_Reports\РћС‚С‡РµС‚ РђСѓРґРёС‚ - РЎРµСЂРІРµСЂС‹ - РЎРµРєС‚РѕСЂ РР‘ 06.06.2017 11-30-00.xml' because it does
not exist.
At C:\MaxPatrol_Reports\dataset.ps1:1 char:14
+ ... xml = [xml](Get-Content -Encoding UTF8 -Path "C:\MaxPatrol_Reports\Рћ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\MaxPatrol_Re...17 11-30-00.xml:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

3. If we run same code at Visual Studio Code x32 or native PowerShell it's work without errors

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
This issue was moved to PowerShell/vscode-powershell#1074
