### ISSUE TITLE
the color of the modified file name to distinguish

### ISSUE THREAD

**Issue by DongLee0504** [Microsoft/vscode#36970]
- VSCode Version:1.17.2
- OS Version:Windows 7

In the git environment, the color of the modified file name to distinguish, so that we can quickly find, like webstorm.
![tim 20171026172633](https://user-images.githubusercontent.com/20215926/32045449-ded7bc8a-ba72-11e7-84c9-fe2b9e48292f.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/178
