### ISSUE TITLE
[feature request] support settings for extensions

### ISSUE THREAD

**Issue by txchen** [Microsoft/vscode#3697]
[Searched the open issue, seems no dup entries]

I cannot find any documents talking about per extension configuration (like atom). Supporting that will make the extension platform really useful.

**Comment by alefragnani** [comment]
Hi @txchen,

Each extension supports it own settings, and you have to look at its `readme` page. 

You configure the extension in the same place where you configure **Code** itself, via `Preferences: Open User Settings`.

For instance, this is my `User Settings` with 3 different extensions configured:

```json
    "projectManager.sortList": "Name",
    "projectManager.codePath": "C:\\Program Files\\Microsoft VS Code\\Bin\\Code.cmd",
    "projectManager.openInNewWindow": false,
    	
    "tagged.tagString": "# #day/#month/#year - #enteredText",
	
    "bookmarks.saveBookmarksBetweenSessions": true,
    //"bookmarks.navigateThroughAllFiles": true,

    "gitProjectManager.baseProjectsFolders": [
        "C:\\Users\\Alessandro\\Documents\\GitHub-Testing"
    ],

```

Hope this helps.

**Comment by txchen** [comment]
@alefragnani thanks! 
Close this issue.
