### ISSUE TITLE
"Git: Revert change" command fails with "Git: Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by kompot** [Microsoft/vscode#36978]
- VSCode Version: Code - Insiders 1.18.0-insider (509630ffe3fabf2e1f49b416bb83f5ff0877b042, 2017-10-25T05:11:41.369Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitup|Bra|0.0.2
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.11.1
json-to-ts|Mar|1.5.3
code-settings-sync|Sha|2.8.3
fish|Ted|0.0.4
vscode-custom-css|be5|2.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.0
vscode-quick-select|dba|0.2.5
githistory|don|0.2.3
javadebugger|don|0.1.5
python|don|0.7.0
tslint|eg2|1.0.12
LogFileHighlighter|emi|1.2.0
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
rest-client|hum|0.15.3
code-select-until|jak|0.6.0
search-node-modules|jas|1.2.0
TypeScriptImport|kev|1.17.0
expand-region|let|0.1.1
fish-ide|lun|0.3.0
metago|met|2.4.1
debugger-for-chrome|msj|3.4.0
typescript-hero|rbb|1.6.0
PostCSS|ric|1.0.1
vscode-sort-json|ric|1.10.2
annotator|ryu|0.10.1
partial-diff|ryu|0.3.3
stylelint|shi|0.30.0
vscode-jumpy|wma|0.3.1
vscode-open-in-github|ziy|1.2.8

(20 theme extensions excluded)

---

Steps to Reproduce:

1. Set cursor to a change/added line.
2. Run command "Git: revert change" from command palette
3. Top of the screen says "Git: Cannot read property 'toString' of undefined"

![image](https://user-images.githubusercontent.com/231635/32051812-62a9bd82-ba56-11e7-9f6d-b1c4100a2fb4.png)

4. Invoking the same command by clicking on circle arrow from changes peek view goes ok and actually reverts change

![image](https://user-images.githubusercontent.com/231635/32051900-b179b048-ba56-11e7-8566-21afa8f67d3b.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Fixed. That command shouldn't appear in the command pallete.

**Comment by kompot** [comment]
Why should not it appear there? It won't be possible to make a revert with shortcut?

**Comment by isidorn** [comment]
Verified that the command is no longer appeargin in command palette
