### ISSUE TITLE
Explorer: first root folder collapses when adding another folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#36976]
Steps to Reproduce:

1. have a single folder workspace, nothing in particular expanded
2. File > Add Workspace Folder

The added folder is expanded but the first one is not.

**Comment by isidorn** [comment]
Can not repro.
Do you see this with latest?
Of course if the first folder is collapsed I will keep it collapsed as I should imho

![expandfolder](https://user-images.githubusercontent.com/1926584/32097898-4b57d686-bb0b-11e7-8289-fa9af33f7036.gif)

**Comment by bpasero** [comment]
@isidorn yeah now I do not see this anymore, very weird. Note that I was not starting from a workspace, I started from a single-folder workspace.

**Comment by isidorn** [comment]
@bpasero Might be a timing issue. Anyways closing until you see it again.
