### ISSUE TITLE
insiders: different font

### ISSUE THREAD

**Issue by scorredoira** [Microsoft/vscode#36986]
- VSCode Version: 1.18.0-insider
- OS Version: Linux Mint 18.2 Sonya

code-insiders and code show different fonts with the same configuration:

![image](https://user-images.githubusercontent.com/1644405/32059164-9099d24e-ba6b-11e7-9bbf-6c4a165cec47.png)

I have installed MS Fonts (ttf-mscorefonts)

```
$ gsettings get org.gnome.desktop.interface document-font-name
'Noto Sans 10'
$ gsettings get org.gnome.desktop.interface font-name 
'Noto Sans 9'
$ gsettings get org.gnome.desktop.interface monospace-font-name
'Monospace 10'
```
Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Perhaps caused by #34947

**Comment by scorredoira** [comment]
Great! Will this be in the insiders build soon or do I have to build it from source with the PR to try it?

**Comment by Tyriar** [comment]
This is a good thing isn't it? The screenshot of stable is showing courier new and Insiders is no longer?

If you want the old font you can get it back with:

```js
"editor.fontFamily": "'Courier New'"
```

See https://github.com/Microsoft/vscode/issues/5742

**Comment by scorredoira** [comment]
OK, I prefer the old font, and as you say:


`"editor.fontFamily": "'Courier New'"
`

brings it back. Thank you!
