### ISSUE TITLE
"Could not find the preLaunchTask 'npm: watch'." issued when failed to parse 'package.json' 

### ISSUE THREAD

**Issue by zh4ui** [Microsoft/vscode#36988]
I was developing an extension. 
After I had accidentally added a comment line like '//...' in the package.json, pressing F5 wouldn't start the debugger. 
The error information was "Could not find the preLaunchTask 'npm: watch"
I understand comment should not appear in json file. However, maybe more comprehensive error message could be given, then I would have discovered the problem easier.

- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: 10.13 (17A405)

Steps to Reproduce:

1. add a comment line like '//...' in 'package.json'
2. run 'code .' in the source folder of an extension
3. press F5 to start the debugger mode
4. Error is issued with message "Could not find the preLaunchTask 'npm: watch'."

Reproduces without extensions: No

**Comment by lerit** [comment]
this [problem ](https://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install)tell me,package.json not allow '//'

**Comment by weinand** [comment]
@isidorn, @dbaeumer  just use this package.json:
```
{
  // an illegal comment
  "name": "corrupt",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo hello"
  }
}
```
and this launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/test.js",
            "preLaunchTask": "npm: test"
        }
    ]
}
```

F5 results in this error:
![2017-10-27_12-32-09](https://user-images.githubusercontent.com/1898161/32100040-e7588aec-bb12-11e7-9be4-73a8af7e9370.png)

All tasks in a package.json with syntax errors are invalid and should result in a more informative error message.

**Comment by egamma** [comment]
The npm task provider is now rejecting the promise and the task framework is exposing the failure in the output channel.

**Comment by weinand** [comment]
Verified that the package.json parsing error shows up in the output channel:

![2017-11-01_18-15-23](https://user-images.githubusercontent.com/1898161/32287408-02c4b856-bf31-11e7-8656-dc638053fae5.png)

However, the error message is still not helpful.
@egamma @dbaeumer @isidorn would it make sense to add 'Please check 
the Output channel for errors.' to the message?
