### ISSUE TITLE
Feature request: show line numbers only on every 10th line

### ISSUE THREAD

**Issue by wiktor-k** [Microsoft/vscode#36981]
Currently VS Code displays line numbers on every line (just like almost every other editor) but it would reduce visual clutter if only every 10th line was displayed and the rest would be empty or use some other non-distracting small character.

Delphi used similar technique to display only every 10th line + current line (sorry for bad quality image, that's as good as I could find):

![delphi-2](https://user-images.githubusercontent.com/1718963/32053860-c7452e7e-ba5c-11e7-86e9-a8751698c974.jpg)

- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code
2. See that all lines have numbers

Reproduces without extensions: Yes

**Comment by DdWr** [comment]
What do you guys think about adding a setting for line number intervals? Something like `editor.lineNumberInterval`? I could work on this.

**Comment by moguzozcan** [comment]
Hello,
I think this issue is not assigned to anyone. If that is ok, I could work on this issue. Also, some hints would be great, since this is my first issue in this project. Thank you.
