### ISSUE TITLE
When re-loaded VSCode always shows list of recently installed extensions.

### ISSUE THREAD

**Issue by technoiswatchingyou** [Microsoft/vscode#36983]
When re-loaded VSCode always shows list of recently installed extensions.
![screen shot 2017-10-26 at 10 57 46 pm](https://user-images.githubusercontent.com/25575840/32054338-751e3718-baa1-11e7-95e3-134199e5fca8.png)

- VSCode Version: 1.17.2
- OS Version: MacOS 10.13.2

Steps to Reproduce:

1. Install 10 extensions (for example)
2. Uninstall one and reload

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/34404
