### ISSUE TITLE
Cancel/timeout for "Go to definition"

### ISSUE THREAD

**Issue by fo-fo** [Microsoft/vscode#36985]
VSCode sometimes gets stuck for an overly long time with C++ code when using the "Go to Definition" feature. Trying to use the feature with a different symbol after this does nothing, and the only recourse I know is to restart the editor.

Would be nice if there was a way to cancel and/or time out the search. Unfortunately I can't give instructions for reproducing since this happens fairly randomly.

- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04.3 LTS

**Comment by dbaeumer** [comment]
VS Code actually cancel the request but it looks like the cpp extension is not reacting to it.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-cpptools#1174
