### ISSUE TITLE
Terminal seems to set `npm config prefix` and it breaks `nvm`

### ISSUE THREAD

**Issue by pablote** [Microsoft/vscode#36987]
This started happening in a recent update, it used to be working fine not that long ago. Whenever I open the built-in terminal this shows up:

```
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v6.11.1 --silent` to unset it.
```

If I now run `npm config get prefix`, I get:

```
/usr/local
```

This is different than if I run from a regular terminal. I don't get any nvm error and the output is: `/Users/pablo/.nvm/versions/node/v6.11.1`

It seems like vscode is setting that value.

- VSCode Version: 1.18.0-insider 8bc02c7443305a0db442c11b76e67d6f4929dc0e
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Install nvm
2. Open the built-in terminal in vscode

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I suspect you're not running your system terminal as a login shell, try adding this setting:

```js
"terminal.integrated.shellArgs.osx": []
```

Regardless of whether this works or not, somewhere in your `~/.bashrc` or `~/.bash_profile` or something is running `npm config set prefix` which does not work in `nvm`.

**Comment by pablote** [comment]
I'll check that setting, I doubt about the .bash_profile since this works fine from any other terminal. It only fails from vscode terminal.

**Comment by Tyriar** [comment]
@pablote most terminal emulators on macOS run the shell as a login shell which runs your .bashrc, VS Code runs as a login shell to match this which is what the setting I suggested would change.

**Comment by petrpacas** [comment]
Actually, `.bashrc` is for non-login shells, but your suggestion to remove the default `-l` flag helped me finally...

What I did:
- Moved all config from `.bash_profile` to `.bashrc` and sourced `.bashrc` from it
- Followed your suggestions to remove the `-l` arg

**Comment by pablote** [comment]
Removing the `-l` option makes the vscode terminal fail on some stuff I have on .bash_profile (iterm2 integration and showing git branch on the prompt), and the `nvm` just doesn't work anymore:

```
bash: iterm2_preexec_invoke_cmd: command not found
bash: parse_git_branch: command not found

pablo@batman spinnaker-ui $ nvm
bash: nvm: command not found
bash: iterm2_preexec_invoke_cmd: command not found
bash: parse_git_branch: command not found
pablo@batman spinnaker-ui $
```

@petrpacas I didn't quite understand what you did with the bash files, and I'd love to try that to see if it fixes this

**Comment by pablote** [comment]
Ok, got it working by only having this in `.bash_profile`:

```
source .bashrc
```

And previously moving `mv .bash_profile .bashrc`. I have no idea why this works, but hopefully it will help anyone else running into this.

**Comment by MarioTerron** [comment]
@Tyriar  Thanks! Add `"terminal.integrated.shellArgs.osx": []` worked for me.

**Comment by soorajvnair** [comment]
@Tyriar Thanks `"terminal.integrated.shellArgs.osx": []` worked for me too. All is well again.

**Comment by abdonrd** [comment]
Thanks! Add "terminal.integrated.shellArgs.osx": [] worked for me.

**Comment by Tyriar** [comment]
I just wrote a FAQ on the website about the proper fix for this issue: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched
