### ISSUE TITLE
VCS in mode multi-workspaces

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#36984]
Which system management version relates to which folder in mode multi-workspaces?

- VSCode Version: 1.18-insider, 1.17.2
- OS Version: win7pro

Steps to Reproduce:

Open multi-workspaces mode, see VCS 
![image](https://user-images.githubusercontent.com/3082812/32055217-d44ac07c-ba69-11e7-8bd3-95da124cab88.png)
![image](https://user-images.githubusercontent.com/3082812/32055219-d530a89e-ba69-11e7-9291-7a459a32a63c.png)

**Comment by bpasero** [comment]
@joaomoreno any idea why the name does not show up for a git repository?

**Comment by IgorNovozhilov** [comment]
there are no errors in the dev-tools console

**Comment by joaomoreno** [comment]
No... the name should show up...

@IgorNovozhilov In the devtools, can you show me a screenshot of the DOM explorer around those `Git` labels? There should be another DOM node with the name of the folders of the git repo roots.

**Comment by IgorNovozhilov** [comment]
![image](https://user-images.githubusercontent.com/3082812/32138046-d19cccae-bc34-11e7-89a5-b4eff35163fe.png)

**Comment by joaomoreno** [comment]
Are the names using non-ASCII characters? If so, can you give me an example?

**Comment by IgorNovozhilov** [comment]
Paths:
`d:\#MYGIT\CodeClimber`
`d:\#MYGIT\ndk`

**Comment by joaomoreno** [comment]
Is the folder literally called `#MYGIT`?

**Comment by IgorNovozhilov** [comment]
Yes, it's a valid name in windows
