### ISSUE TITLE
Not restoring last workspace

### ISSUE THREAD

**Issue by andr3medeiros** [Microsoft/vscode#36980]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: none
---

Steps to Reproduce:

1. Open a folder
2. Close VS Code
3. Reopen VS Code

**Comment by bpasero** [comment]
@andr3medeiros does it work if you start code from the console?

**Comment by andr3medeiros** [comment]
@bpasero yes, just ran. It works from the console.

here's my code.desktop:

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.23

[Desktop Action new-window]
Name=New Window
Name[de]=Neues Fenster
Name[es]=Nueva ventana
Name[fr]=Nouvelle fenêtre
Name[it]=Nuova finestra
Name[ja]=新規ウインドウ
Name[ko]=새 창
Name[ru]=Новое окно
Name[zh_CN]=新建窗口
Name[zh_TW]=開新視窗
Exec=/usr/share/code/code --new-window %F
Icon=code


I tried to remove the "--unity-launch %F" from "Exec=/usr/share/code/code --unity-launch %F", didint work.

I tried to remove the extra "code" from "Exec=/usr/share/code/code --unity-launch %F", didn't work, and the shortcut vanished from the sidebar, and I couldn't see in the search anymore.


Obs.: I installed it before updating from Ubuntu 17.04 to 17.10. I will remove and download/reinstall.

**Comment by Tyriar** [comment]
This will be fixed in v1.18, it's fixed in today's Insiders.

Duplicate https://github.com/Microsoft/vscode/issues/36695
