### ISSUE TITLE
Terminal gets corrupted display when resized horizontally

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#36989]
- VSCode Version: Code - Insiders 1.18.0-insider (de249a04dffcb9b495b9263415c80a82cbfd18ba, 2017-10-26T04:18:36.148Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 
---

![terminal](https://user-images.githubusercontent.com/641685/32060674-7b916c14-ba3d-11e7-8b4c-986b9d7ab164.gif)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
