### ISSUE TITLE
Integrated Terminal Bug

### ISSUE THREAD

**Issue by ilivestrong** [Microsoft/vscode#36993]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vscode-great-icons|emm|2.1.18
php-debug|fel|1.11.1
php-intellisense|fel|1.5.2
php-pack|fel|1.0.1

**Issue -**  I am working with an Angular2 app. I ran the application with **ng serve --o** command which opened my web browser to display the application. I pressed Ctrl + C to terminate the batch job, but instead decided to continue running it. So instead of Typing Y(for yes) I pressed N but still my batch job got terminated. 

Pressing 'N' or 'n' should have let me continue with that existing batch job.

---

Steps to Reproduce:

1. Type ng server --o command to run an angular2 app.
2. Press Ctrl + C to terminate the batch job.
3. Press 'N' as input.
![vscode_it_issue](https://user-images.githubusercontent.com/13273605/32064693-38040596-ba98-11e7-8744-992a9f7e101e.JPG)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
There is a general problem with ctrl+c tracked here https://github.com/Tyriar/node-pty/issues/7, I'll close this in favor of that as it will need to be resolved first.
