### ISSUE TITLE
Terminal initially to narrow

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#36992]
pls see the screenshot below and how the powershell welcome is wrapped. 

I suspect that the initial terminal width is not correct. It happens when ever I open a new terminal on Windows.

![image](https://user-images.githubusercontent.com/172399/32062848-f761aeb6-ba75-11e7-993f-2f5229f50076.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36541
