### ISSUE TITLE
Too many files open in filesystem triggered with react on osx

### ISSUE THREAD

**Issue by aj-badarni** [Microsoft/vscode#36998]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. open up a react project in vscode (preferably one with a few dependencies to fill out node_modules)
2. notice issues in terminal (erroring out immediately, saying too many files open, new tabs in terminal aren't always functional).

To diagnose this, I ran the following command:
sudo lsof -n | perl -pe '$x = <>; while(<>) { ($cmd, $pid, $rest) = split(/\s+/); $cmds{$pid} = $cmd; $pids{$pid}++;} while( ($key, $val) = each %pids) { if ($val > $max) { $max = $val; $maxpid = $key; } } print "pid: $maxpid ($cmds{$maxpid}) has the most ($max) filedescriptors \n";'

For me it reported that Code was using 8511 file descriptors. When I closed VSCode, the next highest was 700. I hypothesized that this was caused by the node_modules + build folder being shown, and that vscode was recursively going down those directories. I verified by reopening vscode in the src directory, and rerunning again. This time I was down to 361 processes (counted vai lsof -n | grep Code | wc -l).

I suggest a fix involving setting ignore directories in the .vscode options. 

Opening vscode in the src directory temporarily will fix the problem for me, but it means I won't have access to my configuration files and any other root level items I have (which I change often in my particular use case). It makes the experience less useful to me as a result.

Thanks!
-AJ

**Comment by bpasero** [comment]
@aj-badarni can you clarify where you saw issues popping up? in the integrated terminal?

**Comment by aj-badarni** [comment]
Issues are at the os level, processes fail to run, can't open terminal tabs, poor performance. Specifically i was using the bathroom terminal to learn why so  many files where open, using bash programs like lsof to diagnose.

**Comment by aj-badarni** [comment]
FYI - My node modules folder contains approximately 73,000 files.

To reiterate why I said before, my project layout is:
project/
     ...conf files...
     node_modules/
     build/
     src/

I'm having to use src as my root folder to go around this problem, but it means I have to use separate editors to manipulate my config files which is moderately inconvenient. 
I'm not sure why VSCode needs to "open" all files, I'm not even sure what that means in a mac context (I'm usually a PC guy), but my guess was file system watching - but whatever the case, I am definitely not utilizing having those files open so having a way for me to at least specify to VSCode that I want to ignore that directory would be great.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
