### ISSUE TITLE
How to use mono debug?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#3699]
I'm no longer sure if this is the right place to ask this question, but the mono-debug repo doesn't seem to make sense...anyway, are there instructions somewhere for mono debug? As in, what goes in the launch.json file? There are certainly fairly complete instructions for node, but the mono side seems lacking.

**Comment by isidorn** [comment]
Please check this document out
https://code.visualstudio.com/docs/editor/debugging#_mono-debugging

Also if you have some feedback on our docs feel free to file issues here
https://github.com/Microsoft/vscode-docs
