### ISSUE TITLE
[powershell] A specific regex breaks code colours

### ISSUE THREAD

**Issue by fullenw1** [Microsoft/vscode#36991]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.4.3
vscode-icons|rob|7.16.0

(2 theme extensions excluded)
---
Steps to Reproduce:

1. Paste the code below in VSCode.
2. Look at the code. Starting line 15, code colours are wrong.

The line `[validatePattern('^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$')]` seems to break code colours.

```
function New-Foo
{
    Param(
        [Parameter(
            Mandatory,
            Position = 0,
            ValueFromPipeline,
            ValueFromPipelineByPropertyName
        )]
        [ValidateNotNullOrEmpty()]
        [System.Guid]$Id,

        [ValidateNotNullOrEmpty()]
        [validatePattern('^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$')]
        [string]$SmtpServer = 'smtp.mycompany.com',

        [ValidateNotNullOrEmpty()]
        [ValidateRange(1, 65535)]
        [int]$Port = 25,

        [ValidateNotNullOrEmpty()]
        [ValidatePattern("^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        [string]$From = 'myemail@mycompany.com',

        [ValidateNotNullOrEmpty()]
        [ValidatePattern("^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        [string]$To = 'myemail@mycompany.com',

        [ValidateNotNullOrEmpty()]
        [ValidatePattern("^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        [string]$Cc,

        [ValidateNotNullOrEmpty()]
        [ValidatePattern("^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        [string]$Bcc = 'myemail@mycompany.com'
    )

    Begin
    {
        $CultureInfo = [System.Globalization.CultureInfo]'en-US'
    }

    Process
    {
        foreach ($IdItem in $Id)
        {
            $Alert = ''
            $Alert = Get-SCOMAlert -Id $IdItem
        }
    }
}

```

**Comment by aeschli** [comment]
@daviwil Hi David, do you still want to own this issue (and other Powershell issues in the vscode repo) or should I reassign? Who would be a good replacement?

**Comment by aeschli** [comment]
@rkeithhill Ok if I assign it to you?

**Comment by rkeithhill** [comment]
It would be better to move this issue to https://GitHub.com/powershell/editorsyntax.  

For issues specific to the PowerShell extension, @tylerl0706 is taking over for @daviwil.

**Comment by aeschli** [comment]
Fixed my switching having VSCode use the grammar from https://GitHub.com/powershell/editorsyntax.

@typicode @rkeithhill Note that we now use the powershell/editorsyntax grammar. From what I've see, that results in some coloring changes, but the changes look ok to me and it fixes some issues too.
I'll move incoming requests/ complaints on the powershell grammar to https://GitHub.com/powershell/editorsyntax.

**Comment by aeschli** [comment]
https://GitHub.com/powershell/editorsyntax has changed the grammar to what we had in 1.20. That means this issue is back again. Moving to https://GitHub.com/powershell/editorsyntax.

**Comment by aeschli** [comment]
This issue was moved to PowerShell/EditorSyntax#71
