### ISSUE TITLE
Use Electron ASAR to optimize file system access?

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#36997]
Have we considered using [Electron's ASAR](https://github.com/electron/asar) to optimize file system access? I imagine this could especially help Windows launch performance.

Found this old write-up from N1/Atom: https://github.com/atom/atom/issues/10163, but it seems that they have moved away from it. Is ASAR considered obsoletely? @Tyriar

**Comment by bpasero** [comment]
@auchenberg we already benefit from the fact that most of our JS code is bundled into a single file. I think where a concept like ASAR could only help us is with node modules access which in our case is not bundled in any way. 

+ @alexandrudima who recently looked into ASAR when checking for file access on startup.

**Comment by alexandrudima** [comment]
:+1:

**Comment by jens1o** [comment]
What's the planned action here for November 2017? I'm seeing this everytime I update VSCode Insiders, that they are litterally hundreds of thousands js file.

**Comment by alexandrudima** [comment]
Investigation results - https://github.com/Microsoft/vscode/pull/41353

**Comment by alexandrudima** [comment]
Pushed via #41353

**Comment by alexandrudima** [comment]
We have discovered at least 17 extensions that make assumptions about the the core `node_modules` disk layout, so they will be broken by the change to ship them as `node_modules.asar`.

We need to communicate with these authors and understand their needs, plus give sufficient time to prepare for the change.

**Comment by alexandrudima** [comment]
After downloading all our extensions, and running searches over them, here are the affected extensions:

#### `formulahendry.vscode-mysql`
```
formulahendry.vscode-mysql/out/common/global.js:26
  Global.keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
```

#### `ms-azuretools.vscode-cosmosdb`
```
ms-azuretools.vscode-cosmosdb/out/src/tree/AttachedAccountsTreeItem.js:35
  this._keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
```

#### `ms-vscode.azure-account`
```
ms-vscode.azure-account/out/src/azure-account.js:30
  keytar = require(`${vscode_1.env.appRoot}/node_modules/keytar`);
```

#### `MS-vsliveshare.vsliveshare`
```
MS-vsliveshare.vsliveshare/out/src/debugger/hostAdapterService.js:32
  let appRoot = vscode.env.appRoot;
```

#### `mshdinsight.azure-hdinsight`
```
mshdinsight.azure-hdinsight/out/src/azure/authorization.js:32
  exports.keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
```

#### `PeterJausovec.vscode-docker`
```
PeterJausovec.vscode-docker/out/commands/system-prune.js:19
  const semver = require(`${vscode.env.appRoot}/node_modules/semver`);
PeterJausovec.vscode-docker/out/explorer/models/dockerHubUtils.js:19
  const keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
PeterJausovec.vscode-docker/out/explorer/models/registryRootNode.js:27
  this._keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
PeterJausovec.vscode-docker/out/explorer/utils/dockerHubUtils.js:19
  const keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
```

#### `satokaz.vscode-memo-life-for-you`
```
satokaz.vscode-memo-life-for-you/out/src/extension.js:396
  const rgPath = path.normalize(path.join(vscode.env.appRoot, "node_modules", "vscode-ripgrep", "bin", "rg"));
satokaz.vscode-memo-life-for-you/out/src/extension.js:733
  grepcmd: (process.platform == "win32") ? "grep -nH ${PATTERN} ${FILES}" : path.normalize(path.join(vscode.env.appRoot, "node_modules", "vscode-ripgrep", "bin", "rg").replace(/\s/g, '\\ ')) + ' -n --no-heading -S ${PATTERN} ${FILES}',
satokaz.vscode-memo-life-for-you/out/src/extension.js:752
  return path.normalize(path.join(vscode.env.appRoot, "node_modules", "vscode-ripgrep", "bin", "rg"));
```

#### `vaniship.vue-ls`
```
vaniship.vue-ls/server/modes/embeddedSupport.js:13
  const tm = require(path.resolve(env.appRoot, 'node_modules/vscode-textmate'));
```

**Comment by yo1dog** [comment]
One more to add to your list. This extension is used as a dependency by other extensions as wells:
`siegebell.scope-info` (701 installs)

https://github.com/siegebell/scope-info/blob/master/src/text-mate.ts#L2

Thanks
