### ISSUE TITLE
Sidebar toggle does not restore width

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#36996]
- VSCode Version: Code - Insiders 1.18.0-insider (8bc02c7443305a0db442c11b76e67d6f4929dc0e, 2017-10-26T05:11:40.525Z)
- OS Version: Darwin x64 16.7.0

Only starts to happen this morning

![sb](https://user-images.githubusercontent.com/4033249/32068492-5ec304e6-ba3b-11e7-9da8-a4b58e13856a.gif)

**Comment by isidorn** [comment]
Fixed, dup of https://github.com/Microsoft/vscode/issues/36963
