### ISSUE TITLE
Error when trying to debug (f# on mono on OS X)

### ISSUE THREAD

**Issue by mmc41** [Microsoft/vscode#370]
When I try to debug a small hello-world like fsharp 4.0 program like the attached, I get an error "error while processing request '{_request}' (exception: {_exception})" in Visual Code 0.10.1 on OS X 10.10.5 on mono 4.2.1. The associated launch.json file is as follows:
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "mono",
			"request": "launch",
			"program": "hello2.exe",
			"args": ["test","test2","bla"],
			"cwd": ".",
			"runtimeExecutable": null,
			"env": {}
		},
		{
			"name": "Attach",
			"type": "mono",
			"request": "attach",
			"address": "localhost",
			"port": 5858
		}
	]
}

[hello2.txt](https://github.com/Microsoft/vscode/files/40396/hello2.txt)

**Comment by Oipo** [comment]
Same for me, VSCode 0.10.1, linux, using mono C#.

**Comment by borgdylan** [comment]
I can repro using a custom .NET language on Linux x86 using v. 0.10.1 as well. This used to work for plain .NET console apps in past versions.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#2
