### ISSUE TITLE
'using module [ModuleName].psm1' is not isolating functions from outside variables

### ISSUE THREAD

**Issue by aaronsace** [Microsoft/vscode#37009]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3

---

Steps to Reproduce:

1. run a function from a module (psm1 file) that was added with 'using module'
2. the function has access to variables outside it's scope when it should not (when run in PowerShell.exe the functions in the module are isolated like they are supposed to be)

**Comment by mjbvz** [comment]
Please file this issue against the powershell extension: https://github.com/PowerShell/vscode-powershell/issues
