### ISSUE TITLE
CoffeeScript syntax hightlighting of the word "class" is incorrect

### ISSUE THREAD

**Issue by gustavosotnas** [Microsoft/vscode#37004]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-custom-css|be5|2.5.0
markdown-preview-github-styles|bie|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.0
vscode-coffeescript-snippets|din|0.0.2
gitlens|eam|5.7.1
EditorConfig|Edi|0.11.1
vscode-nginx-conf-hint|han|0.0.4
beautify|Hoo|1.1.1
docthis|joe|0.5.0
svgpreview|kis|0.2.0
coffeelinter|lky|1.1.0
vscode-less|mrm|0.6.3
debugger-for-chrome|msj|3.4.0
live-server-preview|neg|0.0.4
material-icon-theme|PKi|2.2.3
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|2.8.3
vscode-nginx|sha|0.4.1
stylelint|shi|0.30.0
open-in-browser|tec|1.1.0
code-navigation|vik|0.2.0
highlight-matching-tag|vin|0.4.4
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|0.11.0

When a class name contains "class" in its beginning, syntax hightlighting of it is broken.

For example:
![image](https://user-images.githubusercontent.com/9777954/32072350-0f5c2398-ba71-11e7-9dec-b74851ce28b2.png)

---

Steps to Reproduce:

1. Open/create a CoffeeScript file;
2. Write `new` + a class name that have "class" in its name + any parameter.

This way, "class*" will appear as if were the reserved word `class`, but it isn't.

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
In VS Code we use the syntaxes from Atom. Please create an issue [there](https://github.com/atom/language-coffee-script/issues). I've tested, in Atom is of course the same behaviour.

**Comment by aeschli** [comment]
This issue was moved to atom/language-coffee-script#161
