### ISSUE TITLE
Cannot use AltGr+u with U.S. International keyboard

### ISSUE THREAD

**Issue by GeorgeHernandez** [Microsoft/vscode#37002]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
Bookmarks|ale|0.17.0
alignment|ann|0.3.0
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
ftp-sync|luk|0.3.3
mssql|ms-|1.2.0
csharp|ms-|1.12.1
java|red|0.12.0
code-spell-checker|str|1.4.10
json2yaml|tux|0.2.0
vscode-java-debug|vsc|0.2.0

---

Steps to Reproduce:

1. Turn on U.S. International keyboard in Windows.
2. Open file in Visual Studio Code.
3. Type `AltGr+u`

Reproduces without extensions: No

Issue does NOT occur without extensions. However searching keybindings for `Alt+u` does not find anything.

Issue does NOT occur for the other Spanish characters (`¡¿ÁáÉéÍíÑñÓóÚÜü`), just `ú` when entered as `AltGr+u`. 

Issue does NOT occur when entering `ú` via `'+u`.

**Comment by dbaeumer** [comment]
@alexandrudima do you have an idea why this could happen even if no extension defines the short cut.

@GeorgeHernandez can you check the contribution for each of your extensions to see whether they do define such a short cut. And can you selectively disable ( can be done in the extension viewlet) the extensions to see if we can find the extension that causes the problem

<img width="1481" alt="capture" src="https://user-images.githubusercontent.com/1931590/32073366-19deb59a-ba96-11e7-8feb-6e88d81ffa41.png">

<img width="545" alt="capture" src="https://user-images.githubusercontent.com/1931590/32073402-3328a024-ba96-11e7-819e-86f910c70377.png">

**Comment by GeorgeHernandez** [comment]
TLDNR: I've isolated it to the "Language Support for Java(TM by Red Hat" extension, but cannot be sure about the "Debugger for Java" extension.

Given [all, debug, java] where:
- all: Enabled status of all extensions except for the Debug and Java extensions.
- debug: Enabled status of the "Debugger for Java" extension.
- java: Enabled status of the "Language Support for Java" extension.

I have tested the permutations for the issue:
- [0,0,0] -> No
- [0,0,1] -> Yes
- [0,1,0] -> N/A. The Debugger is dependent on the Java extension.
- [0,1,1] -> Y
- [1,0,0] -> N
- [1,0,1] -> Y
- [1,1,0] -> N/A. The Debugger is dependent on the Java extension.
- [1,1,1] -> Y

As you can see it only happens when the Java extension is on. Since the Debugger extension is dependent on the Java extension, I could not determine if the former would also cause the issue if the Java extension were fixed.

**Comment by alexandrudima** [comment]
This is indeed caused by `redhat.java`. From their `package.json`:

@GeorgeHernandez  I wonder why `ctrl+alt+u` did not show up when you searched for `alt+u`. Did you use the keybindings UI for searching or did you open the `keybindings.json`. Both should have shown in this case the `ctrl+alt+u` binding when searching for `alt+u`.

> P.S. `AltGr` == `Ctrl+Alt+`

```
 "keybindings": [
      {
        "command": "java.projectConfiguration.update",
        "key": "ctrl+alt+u",
        "mac": "cmd+alt+u",
        "when": "editorFocus"
      } 
```

**Comment by dbaeumer** [comment]
@aeschli do you have an idea. 

@GeorgeHernandez please file the issue against the vscode java extension GitHub repository.

**Comment by aeschli** [comment]
This issue was moved to redhat-developer/vscode-java#348
