### ISSUE TITLE
poor support for SASS and PHP

### ISSUE THREAD

**Issue by lessandsass** [Microsoft/vscode#37001]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Name of classes ( already typed classes ) are not pop up as a hint.
2. Color code are not showed the color with sass variable.
3. Some important built-in are not pop up as a hint.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@lessandsass can you please create two separate issues for sass and php with some example explaining what you are missing.

**Comment by lessandsass** [comment]
## ### Poor support for SASS

- Color code are not showed the color with sass variable.
![image](https://user-images.githubusercontent.com/31947204/32147587-e5a93d00-bd0f-11e7-96e7-942c7bf99d32.png)

**Comment by lessandsass** [comment]
## Many builtin PHP functions are not pop up as hint.

-Ex: mysqli_query( ) and more...
![image](https://user-images.githubusercontent.com/31947204/32147711-a263e03e-bd11-11e7-9e55-49a1779e51d9.png)


## Difficult to type php tags

- We have to manually type the php tags as `<?php  ?>`. make easier to type php tags tabbing or with the help of emmet.
