### ISSUE TITLE
losing multiple cursors when using format on save

### ISSUE THREAD

**Issue by mgiraldo** [Microsoft/vscode#37005]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
compulim-vscode-closetag|Com|1.1.0
sublime-commands|Zar|0.1.0
prettier-vscode|esb|0.24.0
sublime-keybindings|ms-|2.9.1
expand-selection-to-scope|vit|0.2.0
sublime-text-pack|wad|0.0.2

---

Steps to Reproduce:

1. in a doc with some text that repeats
2. select one of the repeating instances
3. Cmd+D multiple times to select all repeating instances
4. multiple cursors/selections are created
5. change to something else (type 'abc')

Expected result:
Changes are saved and cursors are maintained.

Actual result:
Only first cursor remains.

Reproduces without extensions: could not launch code without extensions.

**Comment by alexandrudima** [comment]
@mgiraldo I cannot reproduce in a `.txt` file. Are you perhaps seeing this only in certain file types ?

**Comment by mgiraldo** [comment]
that's true. i'm using React. i cannot reproduce in `txt` either. try saving this code in `js` format:

```
import React from "react";
import fetch from "isomorphic-fetch";

import MainLayout from "../../components/MainLayout";
import AllExhibitions from "../../components/ExhibitionsComponents/AllExhibitions";
import Footer from "../../components/ExhibitionsComponents/Footer";
import { getCurrentUrl } from "utilFunctions";
import {
  EXHIBITS_ENDPOINT,
  EXHIBIT_PAGES_ENDPOINT,
  FILES_ENDPOINT
} from "constants/exhibitions";

const Exhibitions = ({ url, exhibitions }) =>
  <MainLayout route={url}>
    <AllExhibitions route={url} exhibitions={exhibitions} />
    <Footer />
  </MainLayout>;

Exhibitions.getInitialProps = async ({ req }) => {
  const currentUrl = getCurrentUrl(req);
  const exhibitsRes = await fetch(`${currentUrl}${EXHIBITS_ENDPOINT}`);
  const exhibitsJson = await exhibitsRes.json();
  const exhibitions = await Promise.all(
    exhibitsJson
      .map(async exhibit => {
        const exhibitPageRes = await fetch(
          `${currentUrl}${EXHIBIT_PAGES_ENDPOINT}?exhibit=${exhibit.id}`
        );
        const exhibitJson = await exhibitPageRes.json();

        const itemId = exhibitJson.find(
          exhibit =>
            exhibit.slug === "home-page" ||
            exhibit.slug === "homepage" ||
            exhibit.order === 0
        ).page_blocks[0].attachments[0].item.id;
        const filesRes = await fetch(
          `${currentUrl}${FILES_ENDPOINT}?item=${itemId}`
        );
        const filesJson = await filesRes.json();

        const thumbnailUrl = filesJson[0].file_urls.fullsize;
        return Object.assign({}, exhibit, { thumbnailUrl });
      })
      .reverse()
  );

  return { exhibitions };
};

export default Exhibitions;
```

**Comment by alexandrudima** [comment]
@mgiraldo I have just tried with the code you've provided and I could not reproduce on a default installation of VS Code. I believe one of your installed extensions might be doing something on save (editing, formatting or something) to `.js` files ?

**Comment by mgiraldo** [comment]
true... prettify does that… 🤔

**Comment by alexandrudima** [comment]
You're right, I could reproduce this using `editor.formatOnSave` with the built-in TypeScript formatter.
