### ISSUE TITLE
Toggle maximized panel no longer maximizes the panel

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37006]
https://github.com/Microsoft/vscode/issues/2806 changes maximize panel to switch sides, I rely pretty heavily on maximizing the panel (and so does @suciuvlad who called it out in https://github.com/Microsoft/vscode/issues/36903#issuecomment-339701061) and it is certainly not equivalent to switching the panel's orientation.

**Comment by Tyriar** [comment]
Even if the button was gone but the command remained that would be fine by me. I use ctrl+shift+q to maximize the terminal.

**Comment by isidorn** [comment]
Fixed in latest insiders

**Comment by suciuvlad** [comment]
Thanks!

**Comment by Tyriar** [comment]
@isidorn thanks for the quick turnaround! By the way I'm for removing the minimize/maximize button on the panel, just as long as the command is retained.
