### ISSUE TITLE
Maybe use search.followSymlinks for all searches

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37000]
`search.followSymlinks` is hooked up for searches using QueryBuilder (find in files, quickopen) but not searches initiated by extensions, or from workspaceContains. Maybe it should be.

Pro: A nice lever for people to have when they are having trouble with symlinks e.g. from cnpm/pnpm

Con: User settings should not impact extensions in this case

cc @chrmarti I said I would file this last week

**Comment by chrmarti** [comment]
Sounds good to me. We can refine it later if there is any need.

**Comment by chrmarti** [comment]
Thanks!
