### ISSUE TITLE
Inconsistent multi-file regex search with \n at the end

### ISSUE THREAD

**Issue by Thinkscape** [Microsoft/vscode#37016]
- VSCode Version: Version 1.18.0-insider (509630ffe3fabf2e1f49b416bb83f5ff0877b042)
- OS Version: OSX 10.12.6 (16G29)

### Steps to Reproduce:

1. Have 2 or more files with a line you want to replace.
2. Open search sidebar
3. Turn on Regex mode.
4. Search for something ending with a newline, i.e. `hello world\n`

### Expected

All files containing that line are displayed

### Actual

Only the first file matched will be shown in results. 

As soon as I removed the `\n` from query and search again, all other files appear.

![vscode-regex-search](https://user-images.githubusercontent.com/270528/32086908-24b62366-bb24-11e7-8693-8a62e44ef87f.gif)

------

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
We don't support multiline search, so this is expected. The 1 result may be from an open file, since the editor does support multiline search. You can use `$` to match a line end.

**Comment by Thinkscape** [comment]
I'm not trying to search across lines, i'm trying to replace a line which ends with a newline character. 

Is this some side-effect from how vscode runs its regex search across files (so it eats those `\r\n` chars?)

**Comment by roblourens** [comment]
Yes, so you can match the end of a line with `$` but not the newline character. `$` should be good enough if you just want to match the end of a line. But if you don't want to match the end of a line that doesn't end with a newline (like a missing newline at the end of a document, I don't think there's a way to distinguish between the two cases).
