### ISSUE TITLE
rg interacts badly with sshfs

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#37013]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. sshfs mount some remote folder
2. open any file in it with code
3. observe that rg takes all cpu, and system hangs

Sorry it's hard to take screen shots because the os is not responsive and I have to hard restart the computer after such operations.

**Comment by bpasero** [comment]
@roblourens this looks like it could be the cause of https://github.com/Microsoft/vscode/issues/36005 ?

We should look into this issue for October, do you agree?

**Comment by roblourens** [comment]
I'm trying to build sshfs

**Comment by roblourens** [comment]
Haven't been able to repro it so far. I don't think ripgrep is implicated in #36005.

> 3. observe that rg takes all cpu, and system hangs

It sounds like this happens every time, and immediately?

**Comment by chrmarti** [comment]
@innerlee When it hangs, does Ctrl + Alt + F1 still get you to a login screen?

**Comment by innerlee** [comment]
It happend twice when I reported. Tried again, this time it only crashes sshfs, the system is fine. I will try to find reliable reproduce steps :)
![screenshot_2017-10-31_10-52-40](https://user-images.githubusercontent.com/9464825/32205377-d610a37c-be29-11e7-8e1f-1e3bfd1e48f2.png)

**Comment by innerlee** [comment]
I think I can reproduce it. After a fresh restart, open a txt in the mounted folder make the cpu busy. 
![screenshot_2017-10-31_11-03-09](https://user-images.githubusercontent.com/9464825/32205791-52529b00-be2c-11e7-9c6d-bd32a552c5c7.png)
After the screenshot, the system is unresponsive. Ctrl + Alt + F1 works after several minutes delay. When killed all vscode related processes, I can back to the normal desktop ui. And the mounted folder becomes unavailable.
![screenshot_2017-10-31_11-14-22](https://user-images.githubusercontent.com/9464825/32205855-a8d09126-be2c-11e7-819c-027f57ee6cd4.png)

---
Some details,
The mounted remote home folder contains lots of files, big and small.
I opened a single txt file with about 20 characters. it is not under source control, and not in any project.

**Comment by roblourens** [comment]
Still can't repro. The 'rg' processes at launch come from extensions that are searching for a certain file type in your workspace.

I tried mounting one very large folder with sshfs, and saw the rg processes as expected, but they used low CPU and didn't cause any issues. I figured that the connection was too slow, so I mounted a local folder with sshfs, but the rg processes still have low cpu while the sshfs process has very high cpu. I also managed to cause macos to kernel panic when mounting the local `/` with sshfs. 

Also trying on a Linux, I see the rg processes using low CPU (on a VM). It isn't causing any loss of stability. 

It would be helpful if you can 
- Try with the Insiders build
- Try launching with `--disable-extensions`, and post your extensions list
- Get the full command line of the rg processes

**Comment by innerlee** [comment]
c# extension?
`rg --files --hidden --case-sensitive -g *.csproj -g *.sin -g *.csx -g **/*csproj -g **/*.sin -g **/*.csx --n-ignore --follow -- .`

When extensions are disabled, no problem any more :)

**Comment by roblourens** [comment]
I see you have a bunch of rg procs in the screenshot, so the C# extension probably isn't the only one. Can you try running that rg command on its own and see if it causes similar issues? Or if you can, write a script to spawn all 8 of them or whatever vscode ends up doing.

**Comment by innerlee** [comment]
They are all the same commands, so all come from c#.

**Comment by innerlee** [comment]
Running 1 instance of rg (the right one with os error 13 on screenshot) do not impact performance, except that endless `Permission denied (os error 13)` printing.
Running more rg make the cpus busy, as in the screenshot. But the error became `Socket not connected (os error 107)`.
And of course, the mount is unusable because of `transport endpoint is not connected`.
![screenshot_2017-11-01_01-08-26](https://user-images.githubusercontent.com/9464825/32237918-33cc4a1c-bea1-11e7-9f67-fbf183a9a190.png)

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode/issues/36227#issuecomment-340787750 suggests that there might be optimizations with remote filesystems that require additional error handling. Not sure if that might be at play here too.

@innerlee Are some files or folders on the sshfs under different permissions, such that, the user code runs under doesn't have permission to access them?

**Comment by innerlee** [comment]
There is a .txt file with root 
`-rw-------  1 root root  13K Oct 11 12:39 .viminfo`

**Comment by innerlee** [comment]
I know the reason now. There is a link,
`lrwxrwxrwx 1 lizz lizz   1 Aug 29 21:24 z: -> /`
which make rg search for the whole disk...
That link is produced by TeamViewer BTW.

**Comment by innerlee** [comment]
By removing `--follow`, the command finishes within seconds.

**Comment by rvong** [comment]
Please fix. Disabling symlink follow does not resolve issue.

**Comment by chrmarti** [comment]
@rvong Is this with the folder on sshfs? What is the output of the following command when run in the folder you open VS Code on:
```
time (/usr/share/code-insiders/resources/app/node_modules/vscode-ripgrep/bin/rg --files --hidden --follow --no-ignore -- . | wc -l)
```
(Replace `code-insiders` with `code` if you are using stable releases.)
