### ISSUE TITLE
the css  auto-complete box with delay about 600ms

### ISSUE THREAD

**Issue by x1nGoo** [Microsoft/vscode#37012]
- VSCode Version: Code 1.17.2 **[Unsupported]** (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.22.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.10
vscode-eslint|dba|1.4.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
autofilename|Jer|0.1.3
docthis|joe|0.5.0
easy-less|mrc|1.4.5
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vuehelper|oys|0.1.0
view-in-browser|qin|0.0.5
vscode-wechat|qin|0.0.6
vscode-icons|rob|7.16.0
background|sha|1.1.15
code-settings-sync|Sha|2.8.3
guides|spy|0.9.0
JavaScriptSnippets|xab|1.5.0
vscode-preview-server|yui|0.7.0

---

Steps to Reproduce:

1. the css  auto-complete box with delay about 600ms after I input posi

2. when I input css posir, and tab, it had not become position: relative,

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
@x1nGoo Can you try to reproduce it without extension? 
For that start VS Code with the parameter: `--disable-extensions`

**Comment by x1nGoo** [comment]
@maxibanki  it is well without extension.

**Comment by x1nGoo** [comment]
@maxibanki   it is good without extension

**Comment by maxibanki** [comment]
Please try to enable / disable extension for extension to see which extension is the cause for the long delay. Then create an issue in the github repository of it.

**Comment by x1nGoo** [comment]
@maxibanki  sorry, I found it cause by my css file, my css file is too big.  It is good in small css file

**Comment by x1nGoo** [comment]
@maxibanki sorry, I found it may be caused by my css file, my css file is too big. It is good in small css file..
but sublime and Brackets are good.

**Comment by aeschli** [comment]
You say this works well without extensions. It must be an extension that slows down everything. If you can find out which one, that would be great. Please file an issue against that extension.
My guess is that it's the 'bracket-pair-colorizer'.

**Comment by x1nGoo** [comment]
@aeschli  sorry, later I found that it is not good in large css file without extension

**Comment by aeschli** [comment]
@x1nGoo How large is your file? If the file is available somewhere, please add a link to it.
