### ISSUE TITLE
Autocomplete suggest not contain new objects after IntelliSense update

### ISSUE THREAD

**Issue by s-shamesmuhametov-parc** [Microsoft/vscode#37020]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
go-no-syntax-highlight|cci|0.0.1
githistory|don|0.2.3
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
Ionide-fsharp|Ion|3.8.3
Ionide-Paket|Ion|1.8.1
mssql|ms-|1.2.0
csharp|ms-|1.12.1
PowerShell|ms-|1.4.3
snippet-creator|nik|0.0.4
partial-diff|ryu|0.4.0
vscode-table-formatter|shu|1.2.1
enumerator|swi|0.0.6
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

Steps to Reproduce:

0. Install an extension using the Intellisense update. I use mssql.
1. Open new tab.
2. Select language SQL
3. Input "Select * From "
4. Connect to database - this triggers an update Intellisense
5. While update intelisense input part of scheme or table name and press Ctrl+Space
6. After it is updated press Ctrl+Space again - suggest not contain scheme name
7. After input any symbol - suggest work and contain schema name, but I want it to work in 6 step

Most likely this is not a mssql problem, but an IntelliSense cache issue.
This original issue in mssql https://github.com/Microsoft/vscode-mssql/issues/1011#issuecomment-339730470
It seems that this is a small problem that is actually very annoying.

**Comment by jrieken** [comment]
> While update intelisense input part of scheme or table name and press Ctrl+Space

@s-shamesmuhametov-parc  I don't understand what that mean?
