### ISSUE TITLE
Inconsistent bar colors for Git changes on left and right of editor

### ISSUE THREAD

**Issue by martinjbaker** [Microsoft/vscode#37024]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
easysass|spo|0.0.6

Lines changed since last commit are shown with a vertical GREEN bar to the right of the line numbers and a BLUE bar in the scroll area on the right. This is confusing. Colors should be consistent.

---

Steps to Reproduce:

1. Open a Git project
2. Make a change to one of the files
3. Changed lines are shown with a green bar on the left but a blue bar on the right.

see screenshot
![account_html_ _speedscriber-server_and_index_js_ _speedscriber-dashboard](https://user-images.githubusercontent.com/1586504/32092745-acc4f7b0-baf1-11e7-9f85-dd6cfe58052c.jpg)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
We don't want to overcrowd the scrollbar with too many colors, especially since red errors and green warnings appear there. So all scm changes appear as blue in there.

**Comment by martinjbaker** [comment]
Well it's just confusing to have 2 colors. Change the left hand bar to blue if you don't want blue on the right...
