### ISSUE TITLE
在linux环境下有时候来回切换二个文件的时候。二个文件的内容会变的一样

### ISSUE THREAD

**Issue by aipper** [Microsoft/vscode#37027]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.9.53-1-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.10
vsc-material-theme|Equ|1.0.5
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|2.2.3
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|0.22.0
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
python|don|0.7.0
vscode-html-css|ecm|0.1.8
code-runner|for|0.8.2
vue-snippets|hol|0.1.5
vs-color-picker|lih|0.7.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.4.0
node-debug2|ms-|1.18.3
debugger-for-chrome|msj|3.4.0
syncing|non|1.4.9
vetur|oct|0.10.1
vuehelper|oys|0.1.0
vue-beautify|pea|2.0.4
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.16.0
vue-vscode-snippets|sdr|1.0.3
css-auto-prefix|spo|0.1.4
vim|vsc|0.10.2
vscode-react-native|vsm|0.4.4
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Translated via Google Translator:
`In the Linux environment sometimes switch back and forth when the two files. The contents of the two files will change the same.`

@aipper Please give us more information and if you can reproduce it, a testcase. In english please.

**Comment by aipper** [comment]
@maxibanki sorry,but this happens occasionally,maybe it caused by some plugins.I use git checkout the file to fix it . maybe i should remove some plugins. thx.
