### ISSUE TITLE
Add syntax highlight support for PostScript language

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/vscode#37025]
- VSCode Version: 1.17.2
- OS Version: Windows 10 x64 Pro 1709 Build 16299.19

Steps to Reproduce:

1. open a postscript file
2. Click on [Plain Text] at the bottom and type PostScript 
3. No result for postscript...

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
For syntax highlighting the files from [textmate](https://github.com/textmate/postscript.tmbundle) could be used. This [one ](https://raw.githubusercontent.com/KDE/syntax-highlighting/master/data/syntax/postscript.xml)looks also good, is newer than the files from the other repo.

**Comment by maxibanki** [comment]
@wstaelens Would this okay for you?
![image](https://user-images.githubusercontent.com/17984549/32096546-0ffdafe2-bb07-11e7-91e4-c3d565d622b0.png)

**Comment by wstaelens** [comment]
sure, better this than nothing 👍

**Comment by maxibanki** [comment]
I will make an extension and notify you once it is released.

**Comment by wstaelens** [comment]
Great, thanks!

**Comment by maxibanki** [comment]
Extension is published, just search for `PostScript`.

**Comment by wstaelens** [comment]
Thanks, may be closed. works perfectly! You guys rock!

**Comment by maxibanki** [comment]
You can close it yourself, just press the `Close issue` button. :smiley:
