### ISSUE TITLE
Editor ruler setting puts a line in wrong position

### ISSUE THREAD

**Issue by zygimantas** [Microsoft/vscode#37037]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.10
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.12
beautify|Hoo|1.1.1
csharp|ms-|1.12.1
vscode-icons|rob|7.16.0
---

Steps to Reproduce:

1. Add "editor.rulers": [120] in settings.json

Reproduces without extensions: Yes/No

In VSCode:

![image](https://user-images.githubusercontent.com/102076/32103442-12929bb0-bb29-11e7-8d63-21368202b1d7.png)

The same line in Visual Studio 2017:

![image](https://user-images.githubusercontent.com/102076/32103473-3ac6e898-bb29-11e7-910e-781a904b596d.png)

The same line copied to Notepad:

![image](https://user-images.githubusercontent.com/102076/32103499-5a025ea4-bb29-11e7-8eb4-9a79382636af.png)

**Comment by alexandrudima** [comment]
I agree this might be different than Visual Studio, but we have made an explicit decision to behave this way.

> Typically, when folks want to use rulers to try to stick to a style guide, the style guide would say something like: "there should be at most 80 chars in a line". That's why I would like to maintain that configuring the rulers with 80 means that the ruler is painted at the location where 80 monospace characters (except tabs) would fit

See https://github.com/Microsoft/vscode/issues/34477#issuecomment-331393607

The description of the `editor.ruler` setting tries to convey this behaviour. I'm sorry if this +/-1 is annoying when configuring VS Code, but IMHO setting a ruler at 120 and it being painted after 120 chars (what VS Code does) is better than painting it after 121 chars (what VS does).
