### ISSUE TITLE
[folding] Ctrl click should fold/unfold all sibling regions

### ISSUE THREAD

**Issue by TryingToFindALoginWhichIsNotRegistered** [Microsoft/vscode#37032]
Code-folding formattes sometimes wrong (espacially in php, I know, it is not supported completely): If you have a comment like:

>/**
>&nbsp; * here is my comment
>&nbsp; */
>function (){
>}

is folded wrong, because the comment ends on  a different level than it starts (but it is common php-style). It would be great to have an option i.e. [ctrl] + click on the [-] in front of the function, that closes all functions at once (instead of [ctrl][k]+[ctrl][2], which does the same inside a class, but sometimes folds wrong).
What I mean is to fold all occurances by keyword (i.e. function, if, while, /**... etc.), if klicked on [-] and pressing [strg] (or another key like [alt] etc.) instead of folding by level.
 
Hope this post is no double entry.
Have a nice weekend...

    VSCode Version: Code 1.17.2 (b813d12, 2017-10-16T13:57:00.652Z)
    OS Version: Linux x64 4.9.0-4-amd64
    Extensions: none

**Comment by aeschli** [comment]
Folding the comment works for me as expected, actually thanks to the fact that it ends with a different indentaton than it starts:
![image](https://user-images.githubusercontent.com/6461412/32176286-8666fd96-bd87-11e7-9942-ff6b8adec333.png)

The function has no folding action as it has no content.

Please avoid mixing different requests. For Ctrl clicking we have https://github.com/Microsoft/vscode/issues/6472 but I think you want to fold all siblings.

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
Hi aeschli,

Ctrl-Click to Unfold All Nested like in #6472 is totally enough. I don't mind, if it's [Alt] or [Ctrl]. Just collapse all nestet, which regulary would fold all functions in one class.

Thanks for the very fast answer!
