### ISSUE TITLE
move that info banner when an action is done to some where else

### ISSUE THREAD

**Issue by sadransh** [Microsoft/vscode#37038]
- VSCode Version: 1.17.1
- OS Version: windows 10 

i think it is better to move that info banner when some action is done to some other place link bottom of page .
i mean this : 
![image](https://user-images.githubusercontent.com/12527824/32103452-4db62c4e-bb2d-11e7-9c12-a62172da66cd.png)
reasons : 
1. it comes in front of tabs and it hides them everytime i should press that close button first
2. it's better to act like notifications in main visual studio

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16278
