### ISSUE TITLE
Improve keybindings.json UI to show extension changing the shortcuts in `Source` column

### ISSUE THREAD

**Issue by KayLeung** [microsoft/vscode#37034]
When you enabled a keymap extension https://github.com/k--kato/vscode-intellij-idea-keybindings , that changed the default shortcuts. But on the keybindings.json UI, it always shows "Default" for "Source" column. It's misleading

- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install an extension: https://github.com/k--kato/vscode-intellij-idea-keybindings
2. Open Keyboard Shortcuts UI
3. To check the key changed by above plugin. It's all "Default" for "Source" column

**Comment by sandy081** [comment]
/duplicate

#110653
