### ISSUE TITLE
weird terminal fonts

### ISSUE THREAD

**Issue by hxlhxl** [Microsoft/vscode#37049]
font in terminal rendered weird in recent updates.
it's being perfect at first installation,what can I do and where to start to fix this?

- VS Code Version: 1.17.2
- OS Version: ArchLinux 4.13.8-1-ARCH
- setting: 
```
{
    "window.zoomLevel": 1,
    "files.associations": {
        "*.pug": "jade"
    },
    "workbench.colorTheme": "One Dark Pro Vivid",
    "python.venvPath": "/opt/py2venv/bin/python",
    "python.pythonPath": "/opt/py2venv/bin/python"
}
```
- Extensions: 

| ext | version | author |
|-----------|---| ------ |
|Beautify|1.1.1| HookyQR |
|C/C++|0.14.0|Microsoft|
|Go|0.6.66|lukehoban|
|Linux Themes for VS Code|1.0.1|SolarLiner|
|mssql|1.2.0|Microsoft|
|One Dark Pro|2.10.17|zhuangtongfa|
|Perview|1.3.4|Haixin Chen|
|Pug snippets|1.0.1|mrmlnc|
|Python|0.7.0|Don Jayamanne|
|React-Native|1.4.1|EQuimper|
|SCSS InterlliSense|0.6.2|mrmlnc|
|Swagger Viewer|1.4.0|Arjun|

![werid-terminal](https://user-images.githubusercontent.com/5368975/32114539-69d80354-bb76-11e7-8340-a373c3bb1b72.png)

**Comment by Tyriar** [comment]
@hxlhxl is that a monospace font? The way character cells dimensions are defined is by measuring the `W` character using the font.

I suggest changing the font, at least until https://github.com/Microsoft/vscode/issues/35681 is supported
