### ISSUE TITLE
Go to Definition not working for C

### ISSUE THREAD

**Issue by Densi27** [Microsoft/vscode#37043]
Hello,

The "Go to Definition" function is not working for C files, same for menu, F12 and hyperlink.

Kind regards,
Daniel

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
code-gnu-global|aus|0.2.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Since this is an issue for the C/C++ extension, please create an issue [there](https://github.com/Microsoft/vscode-cpptools/issues).

**Comment by dbaeumer** [comment]
@Densi27 and you need to install the Cpp extension as well to get Goto definition support for C++
