### ISSUE TITLE
Suggestion: Highlighting text in terminal should add it to clipboard

### ISSUE THREAD

**Issue by smbkr** [Microsoft/vscode#37042]
This is how most other terminal emulators work, at least in the Mac world. Could be configurable and disabled by default if most users prefer/expect the current behaviour.

Expected:
I highlight some text in the integrated terminal, it should be on my clipboard.

Actual:
The text is highlight but I have to right click or press cmd-c to copy the text.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36271
