### ISSUE TITLE
Adopt accessing configuration API correctly

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37041]
In #36623 - I warn those accessing configuration API to get  a value for resource configuration without passing a resource or to get a value for window configuration by passing resource.

**Error prone:**
- If you are accessing the value for resource configuration of a resource, you should be passing the resource.

**Good practice:**
- If you are accessing the value for resource configuration of any resource, pass `null`
- If you are accessing the value for window configuration, do not pass resource. 
- If you want to access different values, use `inspect`.

Main intention behind this is to give run-time warnings and help extension authors when they are accessing the API wrongly by mistake.

After enabling this, I see following warnings from our in built extensions those accessing resource configurations without passing a resource.

- [x] `vscode.git` is accessing `files.encoding` configuration
- [x] `vscode.typescript` is accessing `typescript` and `javascript` configurations 
- [ ] `vscode.json` is accessing `json.scripts` configuration

Owners of above extensions, go through the usages of configuration access API or go through the warnings generated in VS Code run from OOS and fix/adopt to above practises.

**Comment by mjbvz** [comment]
Should be done for typescript and markdown. Let me know if you see any further issues for these extensions

**Comment by sandy081** [comment]
Adopted on behalf of @aescli.
