### ISSUE TITLE
Integrated Terminal not loading

### ISSUE THREAD

**Issue by willielee** [Microsoft/vscode#37044]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.  Ctrl + ` (to start Integrated Terminal)

When starting Integrated Terminal, prompt never appears.

Errors in Developer Tools Console:
> [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking 
event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\xterm\lib\Terminal.js:1379 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
scorer.ts:133 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

![vscodeintegratedtermina3](https://user-images.githubusercontent.com/14075798/32107960-262aeaae-bafe-11e7-9566-c65d004386ab.PNG)

Attempts at correcting issue:
1) Reinstalled VS Code (most recent and Insiders)
    - including deleting $HOME\AppData\Roaming\Code
2) Resizing pane/window (this is not a duplicate of #34554)

**Comment by Tyriar** [comment]
@willielee what's your shell set as in your settings? This happens when a sysnative path is used on a 64-bit machine instead of a system32 path.

**Comment by teom10** [comment]
I have the same issue :(

**Comment by willielee** [comment]
@Tyriar 

**Settings:**
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",

**Also tried:**
1) Copied and pasted that into Run and Powershell opens.
2) Edited User Settings to use bash (Git Bash), same result, terminal does not load.
3) Also able to run Git Bash.

![vscodeintegratedterminal3](https://user-images.githubusercontent.com/14075798/32229509-5cf5c758-be27-11e7-877b-3bd9ef65a90e.PNG)

**Comment by josephky** [comment]
I'm experiencing the same issue, I get this message as well when it tries to open the terminal
> "The terminal process terminated with exit code: 3221225794"

this happens regardless of what terminal I use, tried powershell, cmd, ubuntu

**Comment by pexxi** [comment]
Same issue in Mac too.

**Comment by Tyriar** [comment]
@pexxi I think that's a different problem, caused by Chromium losing/corrupting the texture after sleeping (it can also happen in the minimap).

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169#issuecomment-365143720
