### ISSUE TITLE
Prompt to review license terms

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3704]
The license terms for VS Code will change slightly for March, we will remove the expiration for example. As a result, we need to let people who are automatically upgraded know and give them an opportunity to view the license.

Only if the user is being automatically updated, prompt on startup that says

"Our license terms have changed, please click 'View License' to see the updated version."

With two options "View License" and "Close"

"View License" should use the FW Link from the Help | View License menu (http://go.microsoft.com/fwlink/?LinkID=533485)

**Comment by joaomoreno** [comment]
To confirm its behaviour:

- The message should only appear to a user who was updated from a build previous to March to a build after March.

**Comment by chrisdias** [comment]
:+1:

**Comment by chrisdias** [comment]
@joaomoreno any way i can verify this now?

**Comment by joaomoreno** [comment]
Yeah. Open `package.json` of your installed Code and bump the version up to `1.0.0`. Launch Code, you should see it.

**Comment by chrisdias** [comment]
@joaomoreno 

I was not able to get the prompt.  I'm heading out on vacation, can you please ask someone else to verify?  Sorry about this.

Here is what I did.

- Downloaded the current released Insiders release (commit ef2a)
- Started it, set updateChannel to "none", closed it down
- Downloaded the latest Insiders build (commit ba06)
- Edited Contents/Resources/app/package.json: 
``` json
"version": "1.0.0-insider",
```
- Started this version of Insiders and was warned by the OS that the app was corrupted
- Deleted the app, extracted it again
- Ran it one time, closed it down
- Edited package.json (as above)
- Ran it again

Result -> No prompt
