### ISSUE TITLE
colorCustomizations 

### ISSUE THREAD

**Issue by bajras** [Microsoft/vscode#37047]
Im using the Code Insider and having issues with `editor.selectionBackground`. It doesn't work the same on different file types. It works on HTML and JSON files but doesnt on CSS or JS files. when I double click on a word it doesnt add the background color.

![screen shot 2017-10-27 at 9 25 34 am](https://user-images.githubusercontent.com/3359989/32110299-d12bb5de-bafc-11e7-92fb-dd1cb8b973cd.png)

![screen shot 2017-10-27 at 9 25 44 am](https://user-images.githubusercontent.com/3359989/32110359-f4c8a416-bafc-11e7-83a2-0bd80d9b45e6.png)

Works when I select Keyword `new` but doesnt when I select `Validation`

![screen shot 2017-10-27 at 9 27 43 am](https://user-images.githubusercontent.com/3359989/32110368-ff2c5ed4-bafc-11e7-977d-108c9d3f567f.png)
Works in JSON File

<img width="186" alt="screen shot 2017-10-26 at 9 39 19 pm" src="https://user-images.githubusercontent.com/3359989/32110387-085a3f80-bafd-11e7-84f0-1925a1acc201.png">
Not is JS file

**Comment by usernamehw** [comment]
Maybe it's a different color [Editor Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors):

`editor.wordHighlightBackground` - Background color of a symbol during read-access, for example when reading a variable
`editor.wordHighlightStrongBackground` - Background color of a symbol during write-access, for example when writing to a variable

**Comment by bajras** [comment]
@usernamehw That didnt work either.

**Comment by usernamehw** [comment]
Well, I cannot reproduce that. Are you using the latest version of Insiders? Have you tried to run it without extensions `code-insiders --disable-extensions`?

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/32177334-5c6331f6-bd8a-11e7-8736-ca0facd18865.png)
Some languages show the document highlights or word highlights more than others. That's `editor.wordHighlightBackground`,  `editor.wordHighlightStrongBackground` as @usernamehw writes.

Make sure all the selection colors use transparency.

**Comment by bajras** [comment]
Ya its strange, when im selecting `const` it works fine but not when I select `getData' or even the variable names.

![screen shot 2017-10-30 at 10 11 14 am](https://user-images.githubusercontent.com/3359989/32178564-04bcba96-bd5b-11e7-8909-04a0769d5fe1.png)
![screen shot 2017-10-30 at 10 11 35 am](https://user-images.githubusercontent.com/3359989/32178565-06853b28-bd5b-11e7-9f3a-3e2ddf8e8e01.png)

**Comment by bajras** [comment]
@aeschli Using transparency on `editor.wordHighlightStrongBackground` fixed it. Thank You.
