### ISSUE TITLE
Please allow right-click -> open preview for all markdown files.

### ISSUE THREAD

**Issue by xdaimon** [Microsoft/vscode#37045]
It seems that we can only 'right click -> open preview' for markdown files that are in the folder that's currently open in vscode.
It would be nice if we could open a preview for any markdown file that has an entry in the sidebar.

**Comment by xdaimon** [comment]
Yes, that is what I mean. It would be much more convenient :)

**Comment by mjbvz** [comment]
@bpasero Markdown already has an `explorer/context` contribution. Has there been any discussion about also showing those in the `open editors` pane?

**Comment by bpasero** [comment]
@isidorn any clue why the explorer contributions are not showing up for "open editors"? is that on purpose or by accident? Maybe when we tackle the menu debt in the files explorer we should also tackle it for "open editors".

**Comment by isidorn** [comment]
@bpasero I think it has not been thought true. Though I find it somewhat natural that if an action has context `explorer/context` that it is only shown in the explorer.
Also no other user complained about this so I do not see a big need to add this.

Of course we can revisit next milestone when we tackle debt around this area.

**Comment by bpasero** [comment]
@isidorn @mjbvz I updated https://github.com/Microsoft/vscode/issues/24900 title to also look into the open editors menu.

**Comment by mjbvz** [comment]
Closing as out of scope per discussion in #48983
