### ISSUE TITLE
inconsistent file-search-and-replace behavior depending on open files

### ISSUE THREAD

**Issue by flypenguin** [Microsoft/vscode#37055]
- VSCode Version: 1.17.2 (1.17.2), b813d12980308015bcd2b3a2f6efa5c810c33ba5
- OS Version: Mac OS 10.13 (17A405)

## Steps to Reproduce

This is about inconsistend behavior when using file-search-and-replace, so you need to perform the same search action twice with different file sets opened.

### PREPARE

Create a couple of text files which contain a couple of lines, and include the same **line** in all of them (e.g. "search me")

### FIRST CASE

1. *close* all open editor windows
2. Hit CMD-SHIFT-H to open file search and replace
3. Search for "search me\n" with regex enabled

RESULT FIRST ROUND: no finds (at least on my machine :)

### SECOND CASE

1. *open any file(s)* containing the line
2. Hit CMD-SHIFT-H to open file search and replace
3. Search for "search me\n" with regex enabled

RESULT SECOND ROUND: the string is found for any file(s) opened in an editor window (and only for those)

## Without extensions

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is expected, because multiline search isn't supported (but is incidentally supported by the editor for open files).

**Comment by flypenguin** [comment]
I really would not call that *expected* ... but well.
