### ISSUE TITLE
JSDoc hovertip incorrectly displays @typedef descriptions on next declaration

### ISSUE THREAD

**Issue by mavc** [Microsoft/vscode#37059]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create file `foo.js` with JSDoc example http://usejsdoc.org/tags-typedef.html:

```
/**
 * A number, or a string containing a number.
 * @typedef {(number|string)} NumberLike
 */

/**
 * Set the magic number.
 * @param {NumberLike} x - The magic number.
 */
function setMagicNumber(x) {
}

```
2. Hover over `setMagicNumber`

Expected:

Tooltip should display "Set the magic number."

Actual:

Tooltip displays "A number, or a string containing a number. Set the magic number."

![jsdoc_typedef](https://user-images.githubusercontent.com/706304/32124606-4986aae6-bb1d-11e7-98f9-b07e82eedb49.PNG)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19537
