### ISSUE TITLE
Integrated Terminal letter spacing too wide

### ISSUE THREAD

**Issue by agasser** [Microsoft/vscode#37051]
- VSCode Version: 1.17.2
- OS Version: CentoOS 7.4.1708

Steps to Reproduce:

1. Open Visual Studio Code
2. Open Integrated Terminal

Reproduces without extensions: Yes

The integrated terminal displays text with letter spacing that is way too wide. See the screenshot below. This started with 1.17.0, and is still present in 1.17.2.

![image](https://user-images.githubusercontent.com/1993518/32116178-2e269fe4-bb0f-11e7-8013-b6fea95ecaba.png)

**Comment by Tyriar** [comment]
@agasser do you have a custom terminal font?

The fix it to set it to a monospace font, see https://github.com/Microsoft/vscode/issues/35681

**Comment by agasser** [comment]
Changing the font for the editor or terminal does not work. The settings below have no effect, the font in the editor and the terminal do not change.

![image](https://user-images.githubusercontent.com/1993518/32117805-37aea7d6-bb15-11e7-95a0-b20ee46c7b3a.png)

As a troubleshooting step I installed Adobe's Source Code Pro font and now it is using that everywhere. That did fix my terminal display issue, so it seems this is a duplicate. Now I'll have to figure out why I'm unable to configure the font family through the settings.

**Comment by Tyriar** [comment]
@agasser if those settings didn't do anything but Source Code Pro did work, that indicates to me that Chromium isn't picking up Cantarell and Nimbus Mono properly.
