### ISSUE TITLE
I still like the blue icon.............

### ISSUE THREAD

**Issue by BigEgg** [Microsoft/vscode#37053]
- VSCode Version: 1.17.2
- OS Version: Windows 10, 2017 Fall Creator Update

Steps to Reproduce:

1. Install the VSCode
2. See the Orange Color Icon.......

Reproduces without extensions: Yes

I just want the blue icon back...

**Comment by lipis** [comment]
Be patient.. https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by biddster** [comment]
Funny this bug should be raised. Was discussing at work the other day that the icon colours were the wrong way around. Green would have indicated stable to us and orange unstable. I'm led the believe there have been psychological studies around this...(I'll go google)

**Comment by LeonLiber** [comment]
Can anyone share a high res image of the blue icon we gonna get next release? I want to make a t-shirt out of it, please

**Comment by anran800** [comment]
me too...

**Comment by lipis** [comment]
can someone actually close this issue?

**Comment by chrisdias** [comment]
@BigEgg  please see https://code.visualstudio.com/blogs/2017/10/24/theicon
