### ISSUE TITLE
docs: Show the number of downloads in Millions instead of Thousands in Top Extensions section

### ISSUE THREAD

**Issue by lipis** [Microsoft/vscode#37054]
From: https://code.visualstudio.com/docs/?dv=osx&build=insiders

<img width="771" alt="screen shot 2017-10-27 at 21 50 43" src="https://user-images.githubusercontent.com/125676/32120471-5d826226-bb61-11e7-8a17-256b869a7a06.png">

Note that in the [Marketplace](https://marketplace.visualstudio.com/vscode) it's already showing values in Millions if needed.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-website#696
