### ISSUE TITLE
Python docstring folding

### ISSUE THREAD

**Issue by MichielVanderlee** [Microsoft/vscode#37052]
- VSCode Version: 1.17.2 x64
- OS Version: Windows 10

Possibly related to #3422 

2 issues really:
1. Can't fold docstring with either `'''` or `"""`
2. When using `"""` and [Google style](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) documentation both `Args:` and `Returns:` show folding markers.
When folding `Returns:` it folds the entire rest of the the file.  Also, I can no longer fold definitions.
Work around for this is to use single quotes, in which case it won't fold the entire rest of the file.

Steps to Reproduce:

1. 
```python
def hello_world(input):
    """
    Simple docstring

    Args:
        input (str): simple input

    Returns:
        str: specified input
    """
    return input

def im_folded():
    """
    Oh the horror, I'm being folded!!
    """
    return "Noooooooooo."
```

2. Hover over side to see folding icons:
Note that only folding icons for `Args:` and `Returns:`
![image](https://user-images.githubusercontent.com/918128/32117123-939ff9d8-bb23-11e7-99f6-cadf378bfa09.png)

3. Fold `Returns:`
Note that it folds until EOF
![image](https://user-images.githubusercontent.com/918128/32117160-b5f07dd2-bb23-11e7-8ee4-9ae1f2bb7417.png)

4. Change docstrings to single quotes `'''`
![image](https://user-images.githubusercontent.com/918128/32117234-ff45be0c-bb23-11e7-97d6-a2afa7a875f1.png)

5. Fold `Returns:`
![image](https://user-images.githubusercontent.com/918128/32117256-0fb8cd06-bb24-11e7-9b07-2326b0583e8c.png)

**Comment by aeschli** [comment]
Our folding in indentation based. You are requesting language aware folding which is #3422.
