### ISSUE TITLE
When relaunch vscode after aborted vscode update then Uncaught Exception thrown

### ISSUE THREAD

**Issue by Olddude** [Microsoft/vscode#37058]
- VSCode Version: 1.17.0.0
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:

1. Update vscode
2. While updating launch a second vscode instance
3. Abort the Installation on Dialog
4. Start vscode again

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/7765809/32124091-e47e0208-bb66-11e7-97a7-f45bb92df1b3.png)

**Comment by joaomoreno** [comment]
Please reinstall VS Code. Try not to launch a second instance while it updates. We have it on our backlog to improve this experience.
