### ISSUE TITLE
Go to File does not find files when using certain files.exclude masks

### ISSUE THREAD

**Issue by oklymenk** [Microsoft/vscode#37057]
- VSCode Version:
1.17.2

- OS Version:
Windows 7 SP1 Enterprise 64-bit

Steps to Reproduce:

1. Open VSCode in the directory with the following file structure
```
/
|-- foo/
    |-- foo.js
|-- bar/
    |-- foo.js
|-- foo.js
```
2. Press Ctrl+P (Go to File...). Type foo.js in the search box. All three foo.js files are shown.
3. Add the following to Workspace Settings
```
{
    "files.exclude": {
        "f*/": true
    }
}
```
The intention is to hide the foo folder in the Explorer. In real life I have a lot of folders starting with f and I don't want to list them all, hence using a wildcard (note the / at the end). I would expect the following shown in the explorer:
```
/
|-- bar/
    |-- foo.js
|-- foo.js
```
I would also expect foo.js and bar/foo.js to be found by Go to File.

**Actual Result**:
1. The explorer only shows the 'bar' folder with both 'foo' folder and foo.js file hidden.
```
/
|-- bar/
    |-- foo.js
```
2. Go to File does not find **any** of the foo.js files, including bar/foo.js

Reproduces without extensions: Yes/No
Yes

**Comment by roblourens** [comment]
I think this is https://github.com/Microsoft/vscode/issues/36438, which is fixed in Insiders.
