### ISSUE TITLE
Terminal rendering wonky after waking up from suspended state on Ubuntu

### ISSUE THREAD

**Issue by muratg** [Microsoft/vscode#37063]
- VSCode Version: 1.17.2, Commit: b813d1... Shell: 1.7.7, Renderer: 58.0.3029.110, Node: 7.9.0, X64
- OS Version: Ubuntu 14.04

Steps to Reproduce:
1.  Open VScode and edit an ASP.NET Core app 
2.  Suspend the machine
3.  Wake the machine up

Result:
![image](https://user-images.githubusercontent.com/1808428/32127664-4606294a-bb2d-11e7-8520-62dec9f3bbe8.png)

**Comment by muratg** [comment]
After restarting vscode, I hit this issue on my terminal: https://github.com/Microsoft/vscode/issues/35798 

(At least is usable now, though)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35795

To work around the noise issue either resizing the terminal a bit or zooming (ctrl++, ctrl+-) should force a redraw and fix it.
