### ISSUE TITLE
Version 1.17.2 Breaks Theme Colors

### ISSUE THREAD

**Issue by seltzer1717** [Microsoft/vscode#37064]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Upgrade to version 1.17.2
2. Open any source file in any theme.

Reproduces without extensions: Yes/No
Yes

Symptoms:

The first thing I noticed is my theme now had green quoted text where as before it had a different text color.

Update:

Uninstalled 1.17.2, then reinstalled 1.16.1, then uninstalled 1.16.1, and then finally reinstalled 1.17.2 and the color problem went away.

**Comment by dbaeumer** [comment]
@seltzer1717 good to hear that you were able to solve the problem. I will close the issue since without knowing what has caused this it is very hard to fix.
