### ISSUE TITLE
"debugger adapter failed unexpectedly" 

### ISSUE THREAD

**Issue by diegohb** [Microsoft/vscode#37067]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.1
npm-intellisense|chr|1.3.0
EditorConfig|Edi|0.11.1
vscode-npm-script|eg2|0.3.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.2
task-master|ian|0.1.39
csharp|ms-|1.12.1
resharper9-keybindings|ms-|1.1.0
vs-keybindings|ms-|0.1.7
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.16.0

---

Steps to Reproduce:

1. ctrl+f5 to launch without debugging.

Reproduces without extensions: don't know - can't compile without C# extension.

**Comment by diegohb** [comment]
error message is "Debug adapter process has terminated unexpectedly"

**Comment by weinand** [comment]
Are you debugging C#?

**Comment by diegohb** [comment]
yes.. it's C#, aspnetcore 2.

**Comment by weinand** [comment]
Please move this issue to the C# repo (since C# is not built into VS Code).
You can use this tool: https://github-issue-mover.appspot.com

**Comment by diegohb** [comment]
I'll move it there... but "dotnet run" works against this same codebase on the same machine.. and also VS2017 IDE runs fine..  so i'm not sure how it is C#.. actually I'm not sure I know what c# repo you're referring to either .. 

?

**Comment by diegohb** [comment]
nevermind,.. i got it.. uninstalled and reinstalled c# debugger. thank you!

**Comment by weinand** [comment]
I meant the [repository](https://github.com/OmniSharp/omnisharp-vscode/issues) of the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).
