### ISSUE TITLE
JS Intellisense fights attempts to write getContext

### ISSUE THREAD

**Issue by Gochida** [Microsoft/vscode#37062]
- VSCode Version: 1.17.2
- OS Version: Win10 x64

Steps to Reproduce:

1. Write a line like this: var ctx = document.getElementById('myCanvas')
2. Try to write "getContext"
3. type an opening parenthesis
3. VSCode replaces "getContext" with "msGetInputContext"

From what I can gather msGetInputContext is an internet explorer specific function - though when googling for it any of the top links redirect to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement# so I'm not sure what THAT'S about.

In any case, here's a codepen of what I'm trying to do
https://codepen.io/Arulu/pen/MOWyQN?editors=1111

This is such that I can't get it to let me type getContext without writing it somewhere else and copy/pasting it in where I want it - which is a tad bit silly.

Reproduces without extensions: Yes/No
Yes

**Comment by mjbvz** [comment]
This is currently by-design. Both `(` and `.` will accept the current suggestion

You can cancel this behavior by pressing `esc` to close the suggestion box before pressing `.` or `(` or disable this entirely by setting `"editor.acceptSuggestionOnCommitCharacter": false`

You can also improve your intellisense by specifying the type returned by `getElementById`:

```js
var ctx = /** @type {HTMLCanvasElement} */(document.getElementById('myCanvas'))
```
