### ISSUE TITLE
Ctrl+Hover blocks e.g. Copy/Cut/Paste etc.

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#3706]
When a function call or symbol is defined in two different files, the quick open box pops up with different suggestions, effectively blocking all keyboard shortcuts outside of it's scope.

E.g. 
1. Double click on a symbol to highlight it
2. Keep the mouse still hovering
3. Press Ctrl in order to sequence Ctrl+C

The quick open box then pops up and you are unable to perform your copy.

![d60ca654-e140-11e5-985a-eaaa4ce4e611](https://cloud.githubusercontent.com/assets/1297882/13522583/9256a396-e1f0-11e5-9859-8b2967f51623.gif)
https://github.com/austin-----/code-gnu-global/issues/15#issuecomment-191892712

**Comment by bpasero** [comment]
@csholmq this seems to be the behavior of the extension you are using, could that be? Looks like on Ctrl+down they would popup a picker to select the target. I do not think this is standard Code behavior otherwise.

**Comment by csholmq** [comment]
Oh, totally missed that. I was debugging the wrong extension actually :)
