### ISSUE TITLE
Task templates still using "taskName", should be "label"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#37060]
- VSCode Version: 1.18.0 Insiders
- OS Version: Windows 10

1. Open an empty folder
2. Tasks > Configure Tasks...
3. Create tasks.json file from template

All generated tasks.json still use taskName which was deprecated with the Tasks 2.0.0 polish https://github.com/Microsoft/vscode/commit/18ca3040b1b42391501a080aef5766b2124aee7e

**Comment by dbaeumer** [comment]
Fixed that on Friday.
