### ISSUE TITLE
SCM progress indicator does not stop

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37068]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T05:12:19.123Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
regex|chr|0.1.0
ssh|chr|0.0.2
vscode-eslint|dba|1.4.0
ghlink|dt|0.0.6
tslint|eg2|1.0.13
azure-account|ms-|0.1.3
azurecli|ms-|0.3.0
github-issues-prs|ms-|0.6.0
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vscode-versionlens|pfl|0.19.1
vscode-open-in-github|sys|1.6.0

---

Not sure what triggers it, but it keeps going in one of my multi-root workspaces.

![image](https://user-images.githubusercontent.com/9205389/32131062-e56d46c2-bb59-11e7-8672-52c8026ee8fe.png)

**Comment by maxibanki** [comment]
Seems to be the same as in #36754. Should already be fixed, can you try to update to the latest version?

**Comment by joaomoreno** [comment]
@chrmarti Open `htop` and tell me what the git processes are doing.

**Comment by chrmarti** [comment]
@joaomoreno There is no `git` process running. I'll check if it still occurs with the latest version or if maybe #36754 fixed it.
