### ISSUE TITLE
Cannot read property 'panel' of undefined

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37076]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T04:19:22.491Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
EditorConfig|Edi|0.11.1
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.14.0
seti-icons|qin|0.1.3
vscode-header-source|ryz|1.1.0
ayu|tea|0.8.0
lorem-ipsum|Tyr|1.0.0
shell-launcher|Tyr|0.1.3

(3 theme extensions excluded)

---

I ran the install extensions from the command palette, not sure how that would be related though.

![image](https://user-images.githubusercontent.com/2193314/32132831-f6ac090c-bb7f-11e7-9a91-a4368082f15e.png)

**Comment by maxibanki** [comment]
Hi Tyriar,
@sandy081 closed #37026 with de42a6d9350e07ece8bb8807528768487aa291fb which fixed the same error. It seems that your version doesn't contain the commit right?

**Comment by Tyriar** [comment]
Perfect! 😄
