### ISSUE TITLE
Unable to stop Auto Indent (or Smart Indent)

### ISSUE THREAD

**Issue by mrhammadasif** [Microsoft/vscode#37074]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|2.2.4
vscode-docker|Pet|0.0.20
Bookmarks|ale|0.17.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
tslint|eg2|1.0.13
expand-region|let|0.1.2
string-manipulation|mar|0.2.0
code-beautifier|mic|1.7.2
dotenv|mik|1.0.0
vscode-scss|mrm|0.6.2
azure-account|ms-|0.1.3
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
sublime-keybindings|ms-|2.9.1
team|ms-|1.122.0
Lodash|oys|1.0.0
sass-indented|rob|1.4.5
vscode-todo-highlight|way|0.5.11
blade-runner|yuk|1.0.0

(1 theme extensions excluded)

```
// My User Preferences
{
    "editor.fontSize": 16,
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.minimap.enabled": false,
    "editor.dragAndDrop": true,
    "workbench.activityBar.visible": true,
    "window.zoomLevel": 0,
    "git.confirmSync": false,
    "php.suggest.basic": false,
    "workbench.iconTheme": "material-icon-theme",
    "editor.formatOnPaste": false,
    "editor.snippetSuggestions": "top",
    "explorer.autoReveal": false,
    "emmet.triggerExpansionOnTab": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.js": {"when": "$(basename).ts"},
        "node_modules": true,
        "bower_components": true
    },
    "git.enableSmartCommit": false,
    "editor.quickSuggestionsDelay": 200,
    "javascript.format.enable": false,
    "editor.tabSize": 2,
    "workbench.startupEditor": "none",
    "workbench.colorTheme": "Atom One Dark",
    "editor.renderWhitespace": "boundary",
    "editor.autoIndent": false,
    "files.autoSave": "off",
    "typescript.format.enable": false
}
```
---

Steps to Reproduce:

1. [See the video for the issue](https://youtu.be/YRE4a3EQvFQ)
2. It automatically Indent the Parenthesis on pressing enter (instead of setting the preferences to false in the the user pref given above)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you please share the source of some code that has this issue

**Comment by mrhammadasif** [comment]
Here you can see the snippet from the source code


```
    vm.formPromise = null
    vm.loadProducts = () => {
      vm.loadingPromise = vm.getProductFunc(Auth.user().id)
      .then(resp => {
        console.log(resp.data)
        vm.products = resp.data.data
      })
      .catch(err => {
        console.error(err.data.data.msg)
        Notification.error("Unable to get latest stores. Reload the page")
      })
    }

    vm.loadCategories = () => {
      vm.categoryPromise = CategorySvc.getTree()
      .then(resp => {
        vm.categories = resp.data.data
      })
      .catch(err => {
        console.error(err.data.data.msg)
        Notification.error("Unable to fetch latest catgories. Reload the page")
      })
    }

    $transition$.promise.then(() => {
      // vm.products = []
      vm.loadProducts()
      vm.loadCategories()
    })
```

**Comment by mjbvz** [comment]
Thanks @mrhammadasif 

I'm still having trouble reproducing this:

![default](https://user-images.githubusercontent.com/12821956/32870987-527c4d8e-ca33-11e7-808d-aca500c10fd1.gif)

What I tried:

1. Paste that code into a new js file
1. Grab settings you provided but set editor.autoIndent to true
3. On the closing brace of `vm.loadProducts`, press ender

Is that correct?

**Comment by mrhammadasif** [comment]
well I am using Typescript not Javascript
