### ISSUE TITLE
Give us a way to start or restart OmniSharp

### ISSUE THREAD

**Issue by TheBlueSky** [Microsoft/vscode#3707]
Hello everyone,

OmniSharp some times decides to play hard to get with me while working with ASP.Net Core projects :| I don't know how to reproduce it or why it happens, but it just does. The result is "OmniSharp server is not running." message.

Most of the times, fixing it means I need to make "dummy" modification to project.json file and hope that this triggers starting or restarting OmniSharp.

**Comment by isidorn** [comment]
I think you can always command palette > `Reload Window` and that will trigger the restart of OmniSharp. Does that work for you?

**Comment by TheBlueSky** [comment]
I'm not sure... will try it next time I face this issue.

Still, having at least an option next to "OmniSharp server is not running." message to start OmniSharp is still helpful in my opinion and more intuitive.

**Comment by egamma** [comment]
This command already exists
![image](https://cloud.githubusercontent.com/assets/172399/13534119/dfe160b8-e233-11e5-8f78-1ae85defb52a.png)

**Comment by TheBlueSky** [comment]
@egamma, sorry, my bad... don't know how I missed it :)
