### ISSUE TITLE
Formatter change single quote string to double quote string!

### ISSUE THREAD

**Issue by nbwsc** [Microsoft/vscode#37071]
Formatter change single quote string to double quote string.
It's kind of weird

**Comment by maxibanki** [comment]
Please give us more information. I think you are using the vue-js extension.
But give us more detailed infos via VS Code => Help => Report Issues

**Comment by nbwsc** [comment]
It's solved!Thanks.

**Comment by manico** [comment]
How is it solved? I still have this issue. :(

**Comment by maxibanki** [comment]
It's because of the vue-js extension: #36750
