### ISSUE TITLE
When my code is formatted, some single quotes are canceled.

### ISSUE THREAD

**Issue by daidaishuo** [Microsoft/vscode#37078]
![Uploading WX20171028-215412@2x.png…]()
![Uploading WX20171028-215452@2x.png…]()
like this

**Comment by maxibanki** [comment]
The Images are not working. :)

**Comment by dbaeumer** [comment]
@daidaishuo please provide steps to reproduce. Best is a GitHub repository we can clone that demos the problem.

**Comment by octref** [comment]
@daidaishuo I'm guessing you are using prettier-vscode extension that formats your code to double quotes? If that's the case you can set `prettier.singleQuote` to true.

If that's not the case, feel free to do Help -> Report issues from VS Code to create a new issue with reproduce steps.
