### ISSUE TITLE
VSCode Installer Fails on long paths since v1.17

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [Microsoft/vscode#37089]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Install or update Visual Studio Code v1.17 ( or above) using the Windows installer under a sufficiently long path (i.e. C:\Development Applications\Utility\Analysis & Editing\VSCode)

2. Installer will fail on a file move/rename, please see attached images.

![vscode_installer_error1](https://user-images.githubusercontent.com/28117424/32140102-28233bee-bc2b-11e7-8b95-049f6cb830f8.png)

![vscode_installer_error2](https://user-images.githubusercontent.com/28117424/32140104-30a179d4-bc2b-11e7-8b70-85919e39f185.png)

* Please note this only effects the Windows installer version, the zip packages unzip and operate as expected without issue. So this is not specifically a VSCode issue, but rather an installer issue.

Reproduces without extensions: N/A

**Comment by joaomoreno** [comment]
Unfortunately the only fix available is to install it on a shorter path.

**Comment by JHorvath-MaxetaTech** [comment]
Unfortunately that explanation puzzles me, because the ZIP package unzips to that same base folder, and VSCode runs 100% fine; except (unlike it's Linux TAR.GZ counter part) it is unable to check for updates. So what exactly is the reason the installer package can not extract, and or why does the ZIP package not support checking for updates?

**Comment by joaomoreno** [comment]
We're using Inno Setup, a setup framework which has long path issues. So this can't be fixed until we move away from it, which might happen in a medium time horizon. For now, it simply fails.
