### ISSUE TITLE
TM scope error with IIFE using JavaScript ES6 arrow function

### ISSUE THREAD

**Issue by jlmakes** [Microsoft/vscode#37086]
### Regular IIFE (Correct):

![screen shot 2017-10-28 at 10 07 44 pm](https://user-images.githubusercontent.com/2044842/32138059-bf03c3ca-bc2c-11e7-86b4-7ed1155c6ba7.png)

### ES6 Arrow IIFE (Incorrect):

![screen shot 2017-10-28 at 10 06 38 pm](https://user-images.githubusercontent.com/2044842/32138048-8d13ea0c-bc2c-11e7-890b-013bd900925d.png)

Above on line 1, the fragment `= (() =>`, the inner `(` is missing the `punctuation.definition.parameters.begin.js` scope.

Subsequently, on line 3 the ending `)()` is missing `meta.brace.round.js`

---

- VSCode `v1.17.2`
- OSX `v10.11.6`

Steps to Reproduce:

1. Create any immediately invoked function expression, using an ES6 arrow function.
2. Use a theme that colors `punctuation` scopes differently (such as Duotone)

Reproduces without extensions? **Yes**

_(However, no built-in themes visually show the problem, you must use the scope inspector.)_

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#536
