### ISSUE TITLE
Rate Limiting on  https://raw.githubusercontent.com/Microsoft/vscode/0.10.8/src/vs/vscode.d.ts

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#3708]
GitHub is rate limiting access to vscode.d.ts file. As a result, AppVeyor builds are failing as AppVeyor recycles across 6 IP address (https://www.appveyor.com/docs/build-configuration#ip-addresses) 

As per GitHub documentation (https://developer.github.com/v3/#rate-limiting):
> For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour.

Detailed Build Output: 

https://ci.appveyor.com/project/jpoon/vim/build/1.0.80.

> vim@0.0.11 postinstall C:\projects\vim
> node ./node_modules/vscode/bin/install && gulp init
>  
> Detected VS Code engine version: ^0.10.8
> Error installing vscode.d.ts: Error: Expected an array of tags, but received: {"message":"API rate limit exceeded for 104.197.145.181. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
>  
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x8
> 
> https://ci.appveyor.com/project/jpoon/vim/build/1.0.80

Suggestion:

* put this file behind a proxy or
* add it so typings registry (https://github.com/typings/registry)

**Comment by joaomoreno** [comment]
We hit the same issue in our builds, since we fetch many things from GitHub.

What we ended up doing was creating a [personal access token](https://github.com/settings/tokens) for one of our dev accounts and give it no permissions on any scopes. Setting the `GITHUB_TOKEN` env variable to that auth token in the Travis CI build settings will make all requests go authenticated.

Would this unblock you?

**Comment by bpasero** [comment]
Yes, the GITHUB_TOKEN environment is supported for the vscode module, please use that!

**Comment by jpoon** [comment]
Ok :disappointed: 

It's just something that **everybody** will have to do. Why not add this to the typings registry and get it through `typings install`?

**Comment by bpasero** [comment]
As far as I know, tsd does not support versioning.

**Comment by bpasero** [comment]
And btw the API limit is not hit because of downloading the VSCode.d.ts, it is hit to find out which versions we have released.

**Comment by jpoon** [comment]
> tsd does not support versioning.

`tsd` has been replaced with `typings`, but it looks like it has versioning? https://github.com/typings/typings/blob/master/docs/typings-the-registry-and-versions.md

>  btw the API limit is not hit because of downloading the VSCode.d.ts

Interesting. I'm taking a look at `install` and I see what you mean. Doing the suggested `typings install` won't work then cause it's hitting: https://api.github.com/repos/Microsoft/vscode/tags. I guess I can just set my `"engines": {"vscode":"*"}` to avoid all this.

**Comment by bpasero** [comment]
Putting in "*" will just download vscode.d.ts from our master branch. Adding a GITHUB_TOKEN is really easy though, why would you not do that?

**Comment by jpoon** [comment]
From the install script, it seems like if I put the `*` it'll download latest from master so it'll avoid this querying for releases which might also prevent this rate limiting issue.

I've added the `GITHUB_TOKEN`, but curious as to not using an existing framework (`typings`/`tsd`) to grab the typings file.

Don't mind me -- consider this resolved/closed.
