### ISSUE TITLE
The terminal process command `/bin/false -l` failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by laur1s** [Microsoft/vscode#37087]
- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. launch VS Code
2. press terminal tab

I had same issue with iTerm2 app, but `/bin/bash -l` launch command solved the problem

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Your system administrator probably set `$SHELL` to `/bin/false`, you can workaround this by adding this to your settings:

```js
"terminal.integrated.shell.osx": "/bin/bash"
```

**Comment by Tyriar** [comment]
I've made this fallback to /bin/bash happen automatically in the next version.

---

To verifier:

1. Open terminal
2. Run `export SHELL=/bin/false`
3. Run `code`
4. Open the terminal, it should open bash
5. Run `echo $SHELL` in the terminal, it should say `/bin/false`
