### ISSUE TITLE
The `workspaceContains` activation is not working correctly for Workspaces

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#37082]
- VSCode Version: 1.18-insiders
- OS Version: Windows10

Steps to Reproduce:

1.Pick an extension that has `workspaceContains` in its `activationEvents`
2.Open a folder that **does not contains** the file that activates the previous extension
3.The extension **do not** activates ..._(which is correct)_
4.Create a workspace with that folder
5.Add another folder that **contains** the file to activate the extension
6.The extension **still does not** activates ... _(which is NOT correct)_
7.Now.. another test
8.Close the Workspace
9.Reopen the Workspace
10.Now, the extension **activates** _(which I guess, is correct)_

Reproduces without extensions: No

**Comment by bpasero** [comment]
@alefragnani I tried to reproduce and cannot, here is what I did:
* set `"activationEvents": ["workspaceContains:package.json"]`
* open a folder that has no top level `package.json`
* extension does not activate
* add another folder with a top level `package.json`
=> extension activates

What are you doing differently?

**Comment by alefragnani** [comment]
@bpasero, sorry for taking so long... it was my mistake. The extensions *are* activating correctly, in all scenarios. 

Thanks for your help 👍
