### ISSUE TITLE
Microsoft.VSCode.CPP.IntelliSense.Msvc.exe holding file in use

### ISSUE THREAD

**Issue by brycehutchings** [Microsoft/vscode#37083]
There are times I find VS Code won't let me save a file. When I use Sysinternal's "handle" tool it shows me Microsoft.VSCode.CPP.IntelliSense.Msvc.exe is holding the file open. When I kill the process, I am able to save my file. This has happened several times now, but I don't know what triggers it.

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.17008
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Open a C++ project folder
2. Edit file either in the git diff view and/or as normal. Might also need to have regular Visual Studio open too? Not sure. 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
