### ISSUE TITLE
"Restart to Update" option is not updating editor

### ISSUE THREAD

**Issue by ankugarg** [Microsoft/vscode#37081]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
xml|Dot|1.9.2
tortoise-svn|fan|0.1.1
beautify|Hoo|1.1.1
PowerShell|ms-|1.4.3
team|ms-|1.122.0

---

Steps to Reproduce:

1. Click "Restart to Update option"
2. Editor closes automatically
3. Editor doesn't restart
4. Editor is still not updated

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you try to fully reinstall VS Code? That should fix it.
