### ISSUE TITLE
problems: folder exclusion

### ISSUE THREAD

**Issue by jimblue** [Microsoft/vscode#37080]
- VSCode Version: 1.17.2
- OS Version: macOS 10.13

Steps to Reproduce:

1. The CMS I use have a bunch of php file locate a top folder called system
2. To prevent linting, errors, problems I had this folder to files.exclude and files.watcherExclude
3. I still performance issue and problem notification:

**Screenshot of the bottom panel:**

<img width="324" alt="screen shot 2017-10-28 at 16 54 33" src="https://user-images.githubusercontent.com/10623367/32135515-b6f1c53c-bc00-11e7-9be9-9bc853c5eafb.png">

**My settings:**

```
   "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/CVS": true,
        "**/image": true,
        "**/cache": true,
        "**/tmp": true,
        "**/node_modules": true,
        "**/bower_components": true,
        "**/vendor": false,
        "**/system": false,
        "**/dist": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "**/image/**": true,
        "**/cache/**": true,
        "**/tmp/**": true,
        "**/bower_components/**": true,
        "**/dist/**": true,
        "**/system/**": true,
        "**/vendor/**": true,
```
Reproduces without extensions: No

**Comment by maxibanki** [comment]
> Reproduces without extensions: No

Perhaps an extension doesn't take into the files exclude setting.

But please try to set the `files.exclude` to only   `"system": false,` instead of ` "**/system": false,` because you said that your `system` folder is always under the root directory.

**Comment by jimblue** [comment]
@maxibanki, thanks for your answer but I finally found this problem come from php intellissense plugin:

https://github.com/felixfbecker/php-language-server/issues/164

**Comment by maxibanki** [comment]
Okay :) then please the issue here :)

**Comment by dbaeumer** [comment]
Closing.
