### ISSUE TITLE
Indicate unsaved state closer to file name with tabs disabled

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#37095]
I'm trying to run with tabs disabled (`"workbench.editor.showTabs": false`) and thought that the dirty marker is missing entirely:

![image](https://user-images.githubusercontent.com/101152/32141897-e1282270-bc8b-11e7-934a-8e5b28efa371.png)

It's in the top right corner but that's far from where I would normally expect it:

![image](https://user-images.githubusercontent.com/101152/32141908-0b99ee62-bc8c-11e7-83ef-9ca702f3e8cd.png)

With tabs enabled, it is where I would typically look for it:

![image](https://user-images.githubusercontent.com/101152/32141927-80b3e270-bc8c-11e7-9981-c14b8d5aed8e.png)

- VSCode Version: 1.17
- OS Version: Win10

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by borekb** [comment]
Oh, sorry, I missed it (I always search before reporting). This is a duplicate of https://github.com/Microsoft/vscode/issues/19531.
