### ISSUE TITLE
Grammar Injection doesn't not work on multi-line content

### ISSUE THREAD

**Issue by zh4ui** [Microsoft/vscode#37098]
I tried to inject TOML grammar into markdown, however the TOML colorizer only works on the first line (i.e. a = "b" in the image), it doesn't work on the following line (i.e. d = "c" in the image)

![begin-toml-end](https://user-images.githubusercontent.com/7352394/32143910-0d07814a-bc7f-11e7-80bf-c91f7e95eaec.png)

My tmLanguage.json for the injection is like:

```json
{
	"fileTypes": [],
	"injectionSelector": "text.html.markdown",
	"name": "tomlfrontmatter",
	"patterns": [
		{
			"begin": "\\Abegin\\s*",
			"end": "(^|\\G)end\\s*$",
				
				"patterns": [
					{
						"include": "source.toml"
					}
				]
		}
	],
	"scopeName": "toml.frontmatter.markdown"
}
```

The complete source code is at: https://github.com/zh4ui/vscode-markdowntoml.git

- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: macOS 10.13 (17A405)

Steps to Reproduce:

1. install the Better TOML for TOML colorizer
2. git clone https://github.com/zh4ui/vscode-markdowntoml.git
3. cd vscode-markdowntoml && code .
4. F5 to debug the code
5. Create a markdown file in the [Extension  Development Host]
6. type in the content
```
begin a = "b"
c = "d"
end
```

Reproduces without extensions: No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-textmate#57
