### ISSUE TITLE
Comment Keyboard Shortcut Context

### ISSUE THREAD

**Issue by seanfrisbey** [Microsoft/vscode#37093]
- VSCode Version: 1.15.1
- OS Version:Windows 10 Pro build 17025

This isn't a bug, so there are no steps to reproduce. This is more of a suggestion. I think Visual Studio has this, but I can't recall at the moment. What I'm suggesting is that there be a single keyboard shortcut for commenting, and the commenting functionality decides to use a comment block if multiple lines are selected, and an inline comment is a single line is selected. I tried to create a new keyboard shortcut myself that did this, but it doesn't seem that the available (documented) "when clauses" distinguish between single- or -multi-line selection.

Am I missing something?

**Comment by alexandrudima** [comment]
If this is really annoying you, you could create an extension, register a brand new command, and from that command you would invoke `editor.action.blockComment` or `editor.action.commentLine`.

**Comment by Gruntfuggly** [comment]
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.bettercomment
