### ISSUE TITLE
After "save as" it is hard to get back keyboard focus on editor panel

### ISSUE THREAD

**Issue by kghose** [Microsoft/vscode#37099]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

1. Take open, already saved file
2. Use "Save as" to save file
3. Press arrow keys - IDE navigates in Project panel rather than moves cursor in editor
4. Use mouse to click in editor panel to get back focus
5. Press arrow keys - IDE navigates in Project panel rather than moves cursor in editor still.

Solution seems to be to perform actions in Project panel and then go back to editor

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@kghose can you share a video of what you mean?
