### ISSUE TITLE
请把vscode的logo换回以前的，新logo太烂，无法接受

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#37091]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.9.0-deepin12-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|0.0.2
python|don|0.7.0
Go|luk|0.6.66

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Only english please and here is an update to this topic:
https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by shijunti19** [comment]
Yellow ribbon

When I saw it for the first time, I thought it was a yellow ribbon

黄丝带，是亲人离散后的求助标志，也是为亲人祈祷的祝福标识。
Yellow ribbon is a sign of help for relatives after dispersing, and also a blessing sign for relatives.


![u 2821243895 2991468826 fm 27 gp 0_](https://user-images.githubusercontent.com/5392211/32143794-141a7648-bcea-11e7-94d4-b852bb9359cc.jpg)

**Comment by turnerguo** [comment]
He says: **Please return back the Blue Logo!**
