### ISSUE TITLE
Grammar is in an endless loop

### ISSUE THREAD

**Issue by alex529** [Microsoft/vscode#37097]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.0.5
vscode-great-icons|emm|2.1.18
mips|kda|0.0.1
cpptools|ms-|0.14.0
debug|web|0.21.2

I am working on a c project and it happens every time i switch to a new .h file

[1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing

  | scanNext | @ | /usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2356
-- | -- | -- | --
  | _tokenizeString | @ | /usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2321
  | Grammar._tokenize | @ | /usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2089
  | Grammar.tokenizeLine2 | @ | /usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2059
  | e.tokenize2 | @ | TMSyntax.ts:354
  | t._updateTokensUntilLine | @ | textModelWithTokens.ts:367
  | (anonymous) | @ | textModelWithTokens.ts:334
  | t._withModelTokensChangedEventBuilder | @ | textModelWithTokens.ts:174
  | t._revalidateTokensNow | @ | textModelWithTokens.ts:297
  | t._warmUpTokens | @ | textModelWithTokens.ts:288
  | t.onBeforeAttached | @ | model.ts:79
  | t._attachModel | @ | commonCodeEditor.ts:888
  | t._attachModel | @ | codeEditorWidget.ts:384
  | t.setModel | @ | commonCodeEditor.ts:231
  | (anonymous) | @ | textFileEditor.ts:142
  | g | @ | winjs.base.raw.js:1170
  | enter | @ | winjs.base.raw.js:852
  | _run | @ | winjs.base.raw.js:1068
  | _completed | @ | winjs.base.raw.js:1036
  | then | @ | winjs.base.raw.js:1566
  | enter | @ | winjs.base.raw.js:747
  | _run | @ | winjs.base.raw.js:1068
  | _setCompleteValue | @ | winjs.base.raw.js:1052
  | g | @ | winjs.base.raw.js:1170
  | enter | @ | winjs.base.raw.js:852
  | _run | @ | winjs.base.raw.js:1068
  | _completed | @ | winjs.base.raw.js:1036
  | then | @ | winjs.base.raw.js:1566
  | enter | @ | winjs.base.raw.js:747
  | _run | @ | winjs.base.raw.js:1068
  | _setCompleteValue | @ | winjs.base.raw.js:1052
  | g | @ | winjs.base.raw.js:1170
  | enter | @ | winjs.base.raw.js:852
  | _run | @ | winjs.base.raw.js:1068
  | _completed | @ | winjs.base.raw.js:1036
  | (anonymous) | @ | modelBuilder.ts:148
  | emitNone | @ | events.js:91
  | emit | @ | events.js:188
  | endReadableNT | @ | _stream_readable.js:975
  | _combinedTickCallback | @ | internal/process/next_tick.js:80
  | _tickCallback | @ | internal/process/next_tick.js:104

---

Steps to Reproduce:

1. i get the error every time i switch to a new  .h file
2.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@alex529 Please attach a code sample.
