### ISSUE TITLE
git command runs indefinetely

### ISSUE THREAD

**Issue by hanxue** [Microsoft/vscode#37094]
- VSCode Version: 1.17.2
- OS Version: MacOS 10.10.5

When I run the `SCM publish` command, I can see an indicator that the git command is running. Because I do not have permission to publish, or perhaps git is prompting for credentials, the command hangs indefinitely without any other window. 

## Steps to Reproduce:

1. Clone a repository where you do not have write access to. My example was [https://github.com/bbiskup/purkinje](https://github.com/bbiskup/purkinje)
2. Create a new branch
3. Add a new commit
4. Publish the branch

Output from `Terminal` shows a few git processes running

```
hanxue          29343   0.0  0.0  2444632   1080   ??  S     2:54PM   0:00.00 /bin/sh /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/out/askpass.sh Username for 'https://github.com':
hanxue          29338   0.0  0.0  2519972   6576   ??  U     2:54PM   0:00.07 /usr/local/Cellar/git/2.14.1/libexec/git-core/git-remote-https upstream https://github.com/bbiskup/purkinje
hanxue          29337   0.0  0.0  2446940   1728   ??  S     2:54PM   0:00.01 /usr/local/bin/git push -u upstream fix-readme-config-file
```

Notice in the video there is an indicator showing an ongoing operation in `SOURCE CONTROL`

![vscode_cannot_stop_git_command](https://user-images.githubusercontent.com/760008/32141471-6a89fb44-bcbc-11e7-9615-bbe153e01454.gif)

Where is the option to terminate the git command?

**Comment by hanxue** [comment]
After terminating the `askpass.sh` process, I see some git output error

```
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Missing or invalid credentials.
Missing pipe
```

**Comment by mostr** [comment]
I've got the same (loading indicator spinning and CPU/mem load is getting high) even if the repo is perfectly fine and I can easily publish. It happens only when SCM panel is active (as soon as I open file explorer instead the load goes down). Restarting the app doesn't help here.

Here is my VSC version info
```
Version 1.18.0-insider (1.18.0-insider)
8bc02c7443305a0db442c11b76e67d6f4929dc0e
2017-10-26T05:07:28.835Z
```

**Comment by joaomoreno** [comment]
@hanxue What does running `mktemp` on your system return?
