### ISSUE TITLE
Cannot read property 'panel' of undefined when searching extensions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37092]
- VSCode Version: 1.18 Insiders dated 2017-10-27
- OS Version: Any

Steps to Reproduce:

1. Search for any extension in the extensions viewlet
2. The search is successful but an error "Cannot read property 'panel' of undefined" pops up

Call Stack in the console:
<img width="1123" alt="screen shot 2017-10-28 at 8 39 56 pm" src="https://user-images.githubusercontent.com/16890566/32140509-2968a544-bc20-11e7-9b8d-022b0a162ddc.png">

**Comment by maxibanki** [comment]
Hi Ramya Rao,
@sandy081 fixed it already and closed issue #37026 with commit de42a6d9350e07ece8bb8807528768487aa291fb. The insider builds on the download page are currently outdated and from the 27.10.2017. In my research I found out, that they are released weekly.

**Comment by ramya-rao-a** [comment]
Thanks @maxibanki !

I made the mistake of looking for dupes in opened issues instead of also looking at closed ones :)

Closing this as duplicate of #37026
