### ISSUE TITLE
更新到1.17之后vs 启动变得很卡

### ISSUE THREAD

**Issue by qianyeyixia** [Microsoft/vscode#37090]
- VSCode Version: 1.17.2
- OS Version:win10企业版

Steps to Reproduce:

1. 关于vs code刚刚打开的时候Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin文件夹下的rg.exe卡电脑cup的问题 
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@octref can you please help.

@qianyeyixia we don't speak the language you used. Can you provide the issue report in English please.

**Comment by deepkolos** [comment]
@qianyeyixia 重复了https://github.com/Microsoft/vscode/issues/36414

清空目录的node_modules, 然后使用`cnpm i --by=npm`

**Comment by octref** [comment]
@dbaeumer He's saying "After upgrading to 1.17 VS Code becomes slow".

@qianyeyixia Please give @deepkolos's solution a try.

**Comment by dbaeumer** [comment]
@qianyeyixia do you mean startup or the first typing in the editor ?

**Comment by octref** [comment]
@dbaeumer In the repro steps he mentioned rg.exe so I guess it's https://github.com/Microsoft/vscode/issues/36414#issuecomment-337935610

**Comment by dbaeumer** [comment]
OK. Thanks. Didn't see that you already closed the issue.

**Comment by qianyeyixia** [comment]
Not how attention, not bashful. It's the first time to enter the editor's card, and @octref says it's useless to try that. And the installation failed.

**Comment by octref** [comment]
@qianyeyixia 
I don't understand what you are saying.

First, are you using cnpm?

Second, did you try @deepkolos's suggestion of running `cnpm i --by=npm` in your workspace? If it errors out what's the error log?

Third, in the next version you can set `"search.followSymlinks"` to false to avoid this issue.

**Comment by qianyeyixia** [comment]
@octref没怎么注意看是什么错误错，我再试试吧。用翻译软件翻译出来的差太多。

**Comment by qianyeyixia** [comment]
@octref
Code@1.17.2 I:\Program files\Microsoft VS Code\resources\app
`-- d@1.0.0  extraneous

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:bpasero/fsevents#vscode (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! Code@1.17.2 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Code@1.17.2 preinstall script 'node build/npm/preinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Code package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/npm/preinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Code
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Code
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     I:\Program files\Microsoft VS Code\resources\app\npm-debug.log
PS I:\Program files\Microsoft VS Code\resources\app>

**Comment by qianyeyixia** [comment]
@octref
PS I:\Program files\Microsoft VS Code\resources\app> cnpm i
\ module.js:471
    throw err;
    ^

Error: Cannot find module 'I:\Program files\Microsoft VS Code\resources\app\build\npm\preinstall.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node build/npm/preinstall.js" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node build/npm/preinstall.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 3.1.4
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org
PS I:\Program files\Microsoft VS Code\resources\app>
