### ISSUE TITLE
The program is executed same as a VideoGame

### ISSUE THREAD

**Issue by andp97** [Microsoft/vscode#37104]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows 10 x64 10.0.15063
- Extensions: none
---

1. When i start visual studio on my desktop, vscode is executed by the GPU (Nvidia GTX 1050) i see it in the Nvidia panel on the tarybar and when i open the vs code start the  geforce experience software that show me the FPS (Framerate) of  this program.

**Comment by dbaeumer** [comment]
@andp97 yes, VS Code as many other programs make us of the GPU if present. I can't comment why some of your GPU experience software pops up. I think you need to control this in that software.

**Comment by andp97** [comment]
I fixed this problem with this command `code --disable-gpu` [More info](https://code.visualstudio.com/docs/supporting/faq#_vs-code-main-window-is-blank)  and the programd don't start on my gpu!

**Comment by dbaeumer** [comment]
Just to let you know that this has bad impact on performance.
