### ISSUE TITLE
Every time you open the editor is very card

### ISSUE THREAD

**Issue by taoxiaofeng** [Microsoft/vscode#37109]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.13
beautify|Hoo|1.1.1
vscode-simple-icons|Lau|1.6.2
Angular-BeastCode|Mik|5.0.10
angular2-inline|nat|0.0.17
language-vscode-javascript-angular2|nwa|0.0.11
html5-boilerplate|sid|1.0.1
autoimport|ste|1.2.2
Angular2|UVB|0.4.1

---
![vscode](https://user-images.githubusercontent.com/21038118/32150474-5e12ff54-bd4e-11e7-8d07-9ef390c2baaa.png)

Steps to Reproduce:
1.Every time you open the editor is very card。
2.Every time you open the editor is very card。
3.Every time you open the editor is very card。

Reproduces without extensions: Yes

**Comment by yoyo837** [comment]
What is `very card`?
Very Slow? Chinglish?

**Comment by dbaeumer** [comment]
@taoxiaofeng can you share a workspace that demos the behavior. Are you seeing it if you start VS Code with all extensions disabled as well. (e.g launch from the terminal with `--disable-extensions`)

**Comment by jrieken** [comment]
Please create a performance profile as describes here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-a-vs-code-window
