### ISSUE TITLE
Mac OS X terminal doesn't show characters such as: ö, ä, å

### ISSUE THREAD

**Issue by TeemuKoivisto** [Microsoft/vscode#37107]
- VSCode Version: 1.17.2 (1.17.2)
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

I have had VSCode for a half year now on my computer and this is the first time I noticed that I can't actually type in scandinavian characters eg. ö, ä, å (and I can't remember was I able before). Also copy-pasting them into terminal doesn't show anything sensible so probably the terminal's encoding has gone wrong. Actually I noticed this only because my Python code that I was running with the integrated terminal was failing because it couldn't read non-ascii characters.

I have no idea how and why it happened and I doubt it's because of my installed extensions or my own settings (haven't changed really that many). It's frustrating because now I have to open up a "real" terminal window for the project to get the non-ascii characters to work. I know, such inconvenience!

Also I just have to confess that I'm really disappointed at the new logo. Made me sad when I saw it. Too enterprisey. 

Teemu

**Comment by Tyriar** [comment]
This is what I see:

<img width="115" alt="screen shot 2017-10-30 at 8 31 21 am" src="https://user-images.githubusercontent.com/2193314/32179473-bb9cd41c-bd4c-11e7-8aba-df203dbdeab5.png">

What's in your settings.json and can you paste in the output of `echo $LANG`?

**Comment by TeemuKoivisto** [comment]
User settings
```
{
    "editor.tabSize": 2,
    "window.zoomLevel": 0,
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": false
    },
    "extensions.ignoreRecommendations": false,
    "editor.fontFamily": "'Noto Mono', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'"
}
```

echo $LANG
```
fi.UTF-8
```

**Comment by Tyriar** [comment]
Looks like that's the issue, currently we only support a shortlist of languages based on what we provide translations for. This is an easy fix though :+1:

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/23962f689313cc7c8ea3bd16ef94edf849d37ad1
