### ISSUE TITLE
Feature request: find/replace dialog selects previous query

### ISSUE THREAD

**Issue by jeffman** [Microsoft/vscode#37102]
After I use find or find/replace one time, the next time I open the find/replace dialog the cursor will be automatically moved to the Replace field and the previous query is pre-populated in the Find field.

I find this annoying; almost every time I re-open the Find/Replace dialog I intend to make a new query, and I have to shift-tab back to the Find field every time (and then re-select the old query so that I can write a new one).

This is a feature request to change the behaviour of the Find/Replace dialog so that my previous query is selected and control is sent there instead of the Replace field.

Current behaviour:
1. Open Find dialog, enter a query, press Enter
2. Close Find dialog
3. Open Find/Replace dialog
4. Previous query is pre-populated in the Find field. Control is automatically transferred to the Replace field.

Requested behaviour:
1. Open Find dialog, enter a query, press Enter
2. Close Find dialog
3. Open Find/Replace dialog
4. Previous query is pre-populated in the Find field; it is automatically selected; and control is transferred to it. If I begin typing words, it will overwrite the previous query. This is the behaviour in Visual Studio 2017, for example.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|don|0.7.0
xml|Dot|1.9.2
json-tools|eri|1.0.2
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
prettify-selected-json|vth|1.0.3

**Comment by rebornix** [comment]
let's track this issue in https://github.com/Microsoft/vscode/issues/32617 , thanks for your feedback.
