### ISSUE TITLE
Various core features not functional: e.g. format, intellisense, code navigation

### ISSUE THREAD

**Issue by esuus** [Microsoft/vscode#37108]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.0
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.5.2
code-runner|for|0.8.2
vscode-cdnjs|Jak|0.14.3
docthis|joe|0.6.0
code-beautifier|mic|1.7.2
LiveServer|rit|3.0.0
autoimport|ste|1.2.2
open-in-browser|tec|1.1.0
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

0. React, redux project (but I believe also other projects) inside of .js files: 
1. hover over a function call, intellisense doesn't load, says "Loading.."
2. hit CTRL and hover over something that previously got styled to look like a link upon CTRL+Mouseover, but now it doesn't get the link-style, and when CTRL+Clicking on it, rather than jumping to the respective file or function, a never previously seen progress bar appears, an animation where a very small blue stripe moves from left to right, right underneath my tabs:
![capture-endless loading](https://user-images.githubusercontent.com/764235/32149794-74287e84-bd0a-11e7-90d8-aa9e5a73229b.PNG)
3. right-click, Format Document doesn't do anything. Same with the corresponding shortcut. 

Do note, that I've only been coding seriously for a couple of months and there may be something that **I** am doing wrong. 

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
A few questions:

1. Does this reproduce in [VS Code insiders](https://code.visualstudio.com/insiders/)
1. Does this reproduce if you disable all of your installed extensions?
1. Does this happen for any js project you open?
1. Does your project have  a jsconfig.json project definition file?

**Comment by kumarharsh** [comment]
Maybe related: after upgrading to vscode 1.17, I seem to have lost the ability to "Go to Definition" by Ctrl+Click. Instead, a new cursor is added at the place I do a Ctrl+Click.

**Comment by mjbvz** [comment]
Closing as not actionable without more information
