### ISSUE TITLE
October Endgame

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37117]
## Endgame Schedule
- *October 30*, Code freeze for the endgame
- *November 6*, Endgame done

#### Monday, October 30
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items are created (with "complexity" but not necessarily with full description) by 11pm ZRH time (2pm PT)
- [x] All test items contain comprehensive test descriptions by 10pm PT
- Testers who cannot participate in testing check-off from list below:
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @auchenberg
  - [x] @bpasero
  - [ ] @chrisdias
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [ ] @rebornix
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @seanmcbreen
  - [x] @tyriar
  - [x] @weinand

#### Tuesday, October 31
- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A"October+2017") assigned
- [x] [All closed feature-requests either have a verification-needed or on-testplan tag](https://github.com/Microsoft/vscode/issues?q=label%3Afeature-request+-label%3Aon-testplan+-label%3Averification-needed+-label%3Aduplicate+milestone%3A%22October+2017%22+is%3Aclosed)
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

#### Wednesday, November 1
- [x] Remind team members to assign issues that they intend to fix to the October milestone
- [x] Testing
- [x] [Fixing](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22October+2017%22+label%3Abug) (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22October+2017%22)

#### Thursday, November 2
- [x] [Fixing last issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22October+2017%22+label%3Abug)
- [ ] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [ ] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22October+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
  - do not forget to update the `distro` attribute in the package.json with the commit ID of the distro repo.
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**

#### Friday, November 3
- [ ] Register new components in OSS tool
  - [x] binaryextensions@1.0.1 @mjbvz
  - [ ] bindings@1.3.0 @joaomoreno
  - [ ] byline@5.0.0 @joaomoreno
  - [x] debug@2.6.8 @weinand
  - [x] escape-string-regexp@1.0.5 @mjbvz
  - [x] gulp-rename@1.2.2 @mjbvz
  - [x] gulp-replace@0.5.4 @mjbvz
  - [ ] Ikuyadeu/vscode-R@0.0.0 (?) @aeschli
  - [x] istextorbinary@1.0.2 @mjbvz
  - [x] jschardet@1.5.1 @bpasero
  - [x] keytar@4.0.5 @chrmarti 
  - [x] markdown-it@8.4.0 @mjbvz 
  - [x] ms@2.0.0 @weinand 
  - [x] object-assign@4.1.1 @mjbvz
  - [x] readable-stream@2.3.3 @mjbvz 
  - [x] replacestream@4.0.2 @mjbvz
  - [x] safe-buffer@5.1.1 @mjbvz
  - [x] string_decoder@1.0.3 @mjbvz 
  - [x] textextensions@1.0.2 @mjbvz
  - [x] windows-foreground-love@0.1.0 @bpasero
  - [x] windows-mutex@0.2.0 @bpasero
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [ ] yo generator **@aeschli**
  - [ ] vsce **@joaomoreno**
  - [x] node-debugadapter-node **@weinand**
  - [x] node-debug **@weinand**
  - [x] node-debug2 **@roblourens**
- [ ] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) @dbaeumer
- [ ] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [ ] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @isidorn 
  - [x] OS X - @jrieken
  - [x] Linux - @bpasero 
- [x] All release notes updated - release notes are collected in a file named *`v1_18.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @octref
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-filewatcher-windows **@bpasero**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [ ] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [ ] vscode-jshint **@kieferrm**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@owner**

##### Friday 3rd/Monday 6th
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@redmond**

##### Monday 6th - Wednesday 8th
- [x] Polish release notes **@redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@owner**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Review new [multi-root workspaces documentation](https://code.visualstudio.com/docs/editor/multi-root-workspaces):
  - [x] workbench: @bpasero 
  - [x] search: @roblourens 
  - [x] settings: @sandy081 
  - [x] debug: @weinand 
  - [x] source control: @joaomoreno 
  - [x] tasks (currently missing) @dbaeumer 
  - [x] extensions: @ramya-rao-a 
- [ ] Documentation updated
  - [ ] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [ ] @dbaeumer
  - [ ] @bpasero
  - [ ] @egamma
  - [x] @isidorn
  - [ ] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [x] @octref
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [ ] @sandy081
  - [x] @mjbvz

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Thursday 9th/Friday 10th
- [ ] Merge translations **zurich**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request @Tyriar
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@owner**
    - [x] zip **@owner**
  - [x] OS X - **@owner**
  - [x] Linux
    - [x] deb package 64-bit **@owner**
    - [x] deb package 32-bit **@owner**
    - [x] rpm package 64-bit **@owner**
    - [x] rpm package 32-bit **@owner**
    - [x] archives **@owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@owner**
- [ ] Publish deb and rpms to repositories manually @Tyriar
- [x] Add version with symbols to HockeyApp @Tyriar 
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen** #

**Comment by innerlee** [comment]
`v1_18.md` I believe?

**Comment by Mlocik97-issues** [comment]
> Testers who cannot participate in testing check-off from list below:


Everyone is unchecked.

**Comment by Mlocik97-issues** [comment]
Can You add this to October Milestone?

**Comment by Mlocik97-issues** [comment]
It was really fast :D

**Comment by Mlocik97-issues** [comment]
#35875 

> November 3rd: Endgame done

#37117

> November 6, Endgame done

**Comment by Tyriar** [comment]
@Mlocik97-issues this item under the "Friday 3rd/Monday 6th" heading indicate the end of endgame (when master is open).
