### ISSUE TITLE
Inconsistent number of code references shown in typescript file

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#37113]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T04:19:22.491Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

**Description:**
The number of code references shown in a file is inconsistent after opening another file that is also part of a different `tsconfig.json`.

If the number of references is intended to be dynamic, then the count in step 3 should be the same as in step 1. If the number of references is intended to be "per-project" then the count in step 2 should be the same as step 1.

In either case, the number of references shown in the file should match the number of references shown in the peek widget however.

**Steps to reproduce:**
Set `typescript.referencesCodeLens.enabled` to `true`.

1. Double click file `Test1.ts`.
   - Class A has 1 reference shown and 1 in the peek widget.
   - Class B has 0 references.
2. Preview file `Test2.ts` and select file `Test1.ts`.
   - Class A now has 2 references and 1 in the peek widget.
   - Class B now has 2 references and 2 in the peek widget.
3. Close `Test2.ts`.
   - References are the same as step 2.
4. Reopen `Test1.ts`.
   - References are back to step 1.

**Reproduces without extensions:** Yes

**Files:**

**dir1\Test1.ts**
```ts
export class A {}
export class B extends A {}
```

**dir2\Test2.ts**
```ts
import { B } from '../dir1/Test1';
class C {
  protected b = new B();
}
```

**dir1\tsconfig.json**
**dir2\tsconfig.json**
```json
{
    "compilerOptions": {
        "outDir": "../out",
        "strict": true
    }
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20184
