### ISSUE TITLE
How to turn off copy with syntax highlighting?

### ISSUE THREAD

**Issue by snovey** [Microsoft/vscode#37118]
- VSCode Version: 1.17.2
- OS Version: Windows 7

Reproduces without extensions: Yes

I don't want to use it most of the time but I can't find a way to turn it off.

How can I turn it off so that I copy plain text only?

**Comment by snovey** [comment]
And sometimes I need the copy with syntax highlighting without background color. Is there any way to config it?

**Comment by maxibanki** [comment]
Duplicate of #21071
