### ISSUE TITLE
Test Tour: Node+express tire kicker (JavaScript)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3711]
You have an existing node application and you want to use Code to work on it. Set it up for
- intellisense
- debugging
- find and install useful node extensions

**Comment by waderyan** [comment]
I went with the popular [hackathon starter kit](https://github.com/sahat/hackathon-starter). Some things I saw that may or may not be bugs. 

**Linting** 
I installed [eslint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint). 

- `no-undef` is not fun. It shows up for all built in functions and variables (ex. `require`, `__dirname`, etc.). 

![image](https://cloud.githubusercontent.com/assets/2449568/13796350/70ae249a-eac3-11e5-944c-af9b6bd63483.png)

Fixed it with this code in my eslintrc.

```js
"env": {
		"node": true
	}
```

That wasn't tough to do but wasn't intuitive. I'm wondering if there is something we could do to help the user know what to do here. Maybe a :bulb: prompt action. 

**Intellisense**

I followed the instructions in this [doc](http://code.visualstudio.com/docs/runtimes/nodejs) and can't get intellisense to work. These are the steps I took. 

1. `npm install -g typings`
2. `typings install express node --ambient`
3. Confirmed that the typing files were added
4. Created a `jsconfig.json` file and added the contents as instructed [here](http://code.visualstudio.com/docs/runtimes/nodejs#_adding-a-jsconfigjson-configuration-file). 
5. <kbd>ctrl+space</kbd> after a variable or object, expecting to see intellisense. 

![image](https://cloud.githubusercontent.com/assets/2449568/13796917/d8602e96-eac6-11e5-82f7-ac69881592b1.png)


I couldn't get it to work. Filed this as a bug #4284.

**Debugging**

Worked great. One UX thought I had is it might be good to prompt users to click the wrench. 

![image](https://cloud.githubusercontent.com/assets/2449568/13796952/1f5278fe-eac7-11e5-87ba-8aadec5aa25e.png)

I know that I should click there, but I can see a user having a hard time knowing how to configure. 

**Find and Install Useful Extensions**

Installed eslint, vscode-npm-source, and node-modules-resolve.

**Comment by isidorn** [comment]
@waderyan I like the debug: wrench idea - created https://github.com/Microsoft/vscode/issues/4453
