### ISSUE TITLE
Can't create folder or file in new empty project opened via "Open Folder"

### ISSUE THREAD

**Issue by kibobe04** [Microsoft/vscode#37112]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
git-easy|bib|1.9.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
crane|Hvy|0.3.8
markdown-converter|man|0.0.10
vs-deploy|mkl|10.0.0
vscode-icons|rob|7.17.0

---

Steps to Reproduce:

1. Create new empty project (folder)
2. Open created folder
3. Try to create new folder or file via vscode filemanager
4. Nothing happens

Reproduces without extensions: Yes/No

**Comment by kibobe04** [comment]
UPD: it seems  that this issue is caused of cyrillic folder name in path, for example: C:\Верстка\Banners.

You won't be able to create folders or files inside "Banners" folder in vscode filemanager.

**Comment by bpasero** [comment]
@kibobe04 I cannot reproduce. I created a folder Верстка on my desktop and I can add folders within.

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by kibobe04** [comment]
Thanks for your response. Now i managed to create folder, but there where no icons and also i found another interesting bug.

No icons:
![no-icons](https://user-images.githubusercontent.com/28640315/32357970-8566b4ca-c07c-11e7-8054-6155b4a514de.png)

Steps to reproduce:

1) Wrap current project in filemanager (so you can't see contents of filesystem) 
2) Press create folder few times 
3) Open your project you'll get something like that 
![many folders](https://user-images.githubusercontent.com/28640315/32357933-2aaba59a-c07c-11e7-9ebd-1669b31306ed.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
