### ISSUE TITLE
the workspace path can't include whitespace on Mac and Linux for Python

### ISSUE THREAD

**Issue by diuming** [Microsoft/vscode#37110]
- VSCode Version: 1.17.2
- OS Version: Mac high Sierra, Ubuntu 16.04

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@diuming I am assuming you are using a extension providing the Python support. Please file the issue there. Thanks.

**Comment by dbaeumer** [comment]
If you think it is a VS Code issue, please provider steps on how to reproduce the problem.
