### ISSUE TITLE
Can't run python code in vscode with 'run in terminal'

### ISSUE THREAD

**Issue by jiangkfe** [Microsoft/vscode#37116]
Can't run python code in vscode with 'run in terminal'

- VSCode Version: 1.17.2
- OS Version: macOS High Sierra

Steps to Reproduce:
1. input python code
2. right click and try to click 'run in terminal'
3. check the right-click items

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You need to go through the command palette (cmd+shift+p), you can also assign a keybinding to the command if you want.
