### ISSUE TITLE
Cant use user snippets after setting up

### ISSUE THREAD

**Issue by ayepRahman** [Microsoft/vscode#37111]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.4
html-css-class-completion|Zig|1.11.0
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.0
react-redux-react-router-snippets|dis|0.3.5
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.14
vscode-language-babel|mgm|0.0.10
color-highlight|nau|2.3.0
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@ayepRahman can you please describe the issue you are seeing in more details (e.g. steps to reproduce, GitHub repository to clone, ...). With the provided information the issue is not actionable.
