### ISSUE TITLE
Test Tour: ReactNative getting started (JavaScript)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3712]
You have heard about ReactNative and you want to learn about it using Code.
- find and follow a ReactNative tutorial https://facebook.github.io/react-native/docs/getting-started.html
- install the ReactNative extension
- setup validation using ESLint
- use Emmet

**Comment by egamma** [comment]
To get Intellisense when using the ES6 import as is done in `index.ios.js`: 
```js
import React, { AppRegistry } from 'react-native';
```
with the `react-native` and `react-global` typings, then you must add the following setting to the jsconfig.json:
```json
 {
    "compilerOptions": {
        "allowSyntheticDefaultImports": true
    }
}
```

I've added this to the release notes and we also need to doc it.

**Comment by joaomoreno** [comment]
@egamma Even after adding a `jsconfig.json` file with those contents, I still don't get Intellisense. Any other tips?

**Comment by egamma** [comment]
@joaomoreno and you have the d.ts files (`tsd react-global react-native`) installed?

**Comment by joaomoreno** [comment]
I was missing the tsd
