### ISSUE TITLE
Lots of `Promise did not implement oncancel` in extension viewlet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37121]
1. Open extensions viewlet
2. Search for `@sort:installs`
3. Using your mouse, pick up the viewlet's scrollbar and move it up and down, pausing every now and then for 1 second at a time

Pages are cancelled if they are not needed since the user scrolled away from them. There must be some `new Promise()` somewhere which doesn't propagate cancellation.

![image](https://user-images.githubusercontent.com/22350/32160292-6de11558-bd51-11e7-94ca-dd819f45183a.png)

**Comment by sandy081** [comment]
Its also there in Stable. Will do some initial investigation to see where it is not being propogated.

**Comment by sandy081** [comment]
@joaomoreno My suspicion is that, creating the native Promise is eating up the cancellation function [here](https://github.com/microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L388)

**Comment by joaomoreno** [comment]
Close. That code doesn't create a native Promise; it creates a winjs.Promise indeed. But it doesn't know anything about cancellation... so we might have to remove `async` here... Too sad!
