### ISSUE TITLE
vscode on mac debug stuck?

### ISSUE THREAD

**Issue by cpprookie** [Microsoft/vscode#37123]
- VSCode Version:  1.17.2
- OS Version: mac os 10.12.4

![image](https://user-images.githubusercontent.com/18083815/32161173-8e737c50-bd8f-11e7-8ff0-cf12fb46fbed.png)
I installed code but found that i cannot debug. when i start debug mode, the bottom left corner will appear a progress bar (the red border area) and stuck at 11%. The only reason i could guess is that i didn't start it as root. Then  i run `sudo code .` to start it but it still looked the same as before.  If possible , please help me to fix it. thanks!

**Comment by weinand** [comment]
@cpprookie how does your launch config look like?

**Comment by cpprookie** [comment]
@weinand  
Did you mean config part in the picture?
![image](https://user-images.githubusercontent.com/18083815/32163830-8b8262aa-bd98-11e7-8324-b07f7426d2ea.png)
When i try to add one, the problem in the question appear again.

**Comment by weinand** [comment]
@cpprookie aha, you do not have a launch config.

To create a launch config click on the 'gear' icon.
You will have to decide whether you want to debug JavaScript for the "node" runtime or a browser.

Please read the documentation related to this: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

**Comment by cpprookie** [comment]
@weinand  Thanks for your patient reply. I think that's the point. But it is also my problem, After i click on the 'geer' icon, the bottom left corner progress bar turned on again  and stuck at 14% as i have mentioned before. 
![image](https://user-images.githubusercontent.com/18083815/32167968-aa9fcf12-bda5-11e7-9ddc-b3aec7e4bd75.png)

And i'm really confused about that.

**Comment by weinand** [comment]
The progress indicator in the bottom left corner shows the build progress which in general is completely independent from debug. 

I do not understand why pressing the "gear" button would start the "build" task.

Are you sure that you pressed this "gear" button:

![2017-10-30_13-01-19](https://user-images.githubusercontent.com/1898161/32169936-cba4545e-bd72-11e7-824a-04835d25cb0f.png)

**Comment by cpprookie** [comment]
@weinand, i do press the button you mark in the picture T_T. On my own windows pc, everything goes really well but  on that mac,  just turn on that progress  indicator and stucked.  So i wondered  if  code tries to find some path or open some files while i press "gear" button, for some unknown reasons  it just stuck at that progress. BTW  could i get code running  log  in some local files? 
 Really thanks for your patient reply  and put up with my awful english. :）

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by cpprookie** [comment]
It's night in china and i'm out of that mac now. I will try your suggestion next morning.  Thanks and wish you a good day :)

**Comment by cpprookie** [comment]
@weinand  I've tried `code --disable-extensions` and the problem is  still over there. Is there any other ways to locate the problem?

**Comment by cpprookie** [comment]
@weinand, I finally uninstall come java extensions and it could work as normal. Thanks a lot!
