### ISSUE TITLE
Views: initial opening a view animates all views within

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37129]
Steps to Reproduce:

1. pick a slow os (windows)
2. reload window with explorer visible
3. click on extensions view

=> the views within seem to animate from top to bottom
=> I think for the initial display we should not animate the views layouting

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32164769-c637a14a-bd60-11e7-9012-d5f3601c2f95.gif)

**Comment by joaomoreno** [comment]
This is a problem with the extension viewlet, and possible the views viewlet because it adds views a bit later.

@bpasero Are you sure it's animated? Isn't it just a view coming in a bit later?

**Comment by sandy081** [comment]
Extensions viewlet register Installed and Recommended sections and they are added at the same time to the `PanelViewlet`.

@joaomoreno May be each `add ` to the viewlet is causing the animation?

**Comment by joaomoreno** [comment]
Animation is set only when panels fire `onDidChange`, not when added/removed. So it might be this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L438

**Comment by bpasero** [comment]
Yeah I am for sure seeing an animation, maybe the video did not cover it nicely.

**Comment by bpasero** [comment]
@joaomoreno @sandy081 I am seeing a similar animation when typing into the extensions viewlet, waiting for the results to appear and then clearing the search. 2 views are animating in after that.

**Comment by sandy081** [comment]
Will talk to @joaomoreno directly to get more knowledge on this :)
