### ISSUE TITLE
fleexclude

### ISSUE THREAD

**Issue by shingkit** [Microsoft/vscode#37125]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
code-settings-sync|Sha|2.8.3
vscode-eslint|dba|1.4.0
tslint|eg2|1.0.13
vscode-npm-script|eg2|0.3.1
json-tools|eri|1.0.2
tortoise-svn|fan|0.1.1
vscode-auto-open-markdown-preview|hnw|0.0.4
luaide|kan|0.5.1
debugger-for-chrome|msj|3.4.0

---

Steps to Reproduce:

1.files.exclude  填入 “pack”:true，pack文件夹还在
2.改成“pack*”:true 正常

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
@shingkit can you please provide more details about the problem you have with VS Code. With the current information provided the issue is not actionable.

**Comment by shingkit** [comment]
My workspace has a directory named "pack"
I set files.exclude with` "pack":true` ,the directory is still there;
I changed "pack":true to` "pack*":true` ,the directory dissappear.

**Comment by dbaeumer** [comment]
Thanks.
