### ISSUE TITLE
The terminal selector is not convenient

### ISSUE THREAD

**Issue by smalllong** [Microsoft/vscode#37124]
- VSCode Version: 1.17.2
- OS Version: windows 8.1

The terminal selector on the left of the _New Terminal_ button is not so convenient. We have to click two times to change to another terminal.
I think it's better to change the selector to tabs so that we can click one time to change current terminal. Or we can optimize it so that we can use a mousedown-mousemove-mouseup style to change the terminal like the selector on the mac os.

**Comment by innerlee** [comment]
You can bind ``Alt + ` `` to `Focus Next Terminal` and ``Shift + Alt + ` `` to `Focus Previous Terminal`

**Comment by Tyriar** [comment]
Here are my personal keybindings:

```js
{ "key": "ctrl+shift+j",    "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",    "command": "workbench.action.terminal.focusPrevious" }
```

**Comment by Tyriar** [comment]
Closing this off in favor of https://github.com/Microsoft/vscode/issues/10546
