### ISSUE TITLE
Suggestion: Add native support to Ruby and Rails class mapping 

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#37135]
- VSCode Version: 1.18.0-insider
- OS Version: Ubuntu 17.10 (Artful Aardvark) - 4.14.0-3-generic

Steps to Reproduce:
1. Open Ruby/Rails project
2. Try to follow class on the Controller Declaration
3. Nothing happened.
4. Exist plug-ins but not with the native editor quality level or speed 

Reproduces without extensions: Yes

**Comment by octref** [comment]
VS Code does not support Ruby and Rails out of the box. You can give this extension a try: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

You can open an issue for enhancement in the extension repository.
