### ISSUE TITLE
state of debug actions does not reflect debug state

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37134]
For concurrent node-debug sessions I'm seeing that the debugger is confused about the debug state. The CALL STACK view and the editor both indicate that the debugger is stopped but the debug actions think that the debugger is running:

![2017-10-30_12-47-19](https://user-images.githubusercontent.com/1898161/32169529-3358cfe6-bd71-11e7-9646-7ed6c21b7a1b.png)
   
In this case I've started the node-debug server first and then launched the mocha tests as another session.

When launching the mocha tests from the terminal (hence no second debug session was created) this problem did not occur.

**Comment by isidorn** [comment]
@weinand great catch, thanks!
