### ISSUE TITLE
Html - jinja code will be pull into one line

### ISSUE THREAD

**Issue by mikusjelly** [Microsoft/vscode#37131]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601

-- 

Steps to Reproduce:

1. index.html with jinja templetes
```
{% extends "bootstrap/base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block navbar %}
<style type="text/css">
    #md5_list_id {height: 120px;}</style>
```
2. save
```
{% extends "bootstrap/base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block navbar %}
<style type="text/css">
    #md5_list_id {
        height: 120px;
    }
</style>
```

**The jinja code will be put into one line.** 

I want to format html, not jinja.

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as the underlying formatter. It's a HTML formatter, and is not aware of (most) templating languages. But you can try to file an enhancement request there. Or check out the VSCode marketplace if someone has written a jinja formatter.

**Comment by mikusjelly** [comment]
ok, got it.
