### ISSUE TITLE
Integrated terminal reports errors when launch rupa z.sh

### ISSUE THREAD

**Issue by hex2010** [Microsoft/vscode#37143]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
go-test-outline|Rom|0.1.4
code-gnu-global|aus|0.2.2
vscode-swift|kia|0.8.0
Go|luk|0.6.66
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.0

---

Steps to Reproduce:

1.  in the TERMINAL pane,  Launch z.sh (https://github.com/rupa/z/) 
2. Error messages appear,  and the `z` not works.

```
~ $ source .z.sh
sh: .z.sh: line 63: syntax error near unexpected token `<'
sh: .z.sh: line 63: `        awk < <(_z_dirs 2>/dev/null) -v path="$*" -v now="$(date +%s)" -F"|" ''
~ $ z
sh: z: command not found
```

note:  z.sh works fine with Terminal.app, version 2.8

Reproduces without extensions: Yes!

**Comment by Tyriar** [comment]
@hex2010 I think this might be to do with you running `sh` instead of `bash`, have you configured your shell as sh? What's in your settings.json?
