### ISSUE TITLE
Test: new terminal API adoption

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37149]
Complexity: 2

- [x] Linux @isidorn 
- [x] macOS @sandy081 
- [ ] Windows @egamma 

The terminal added additional API to listen to the terminal output. The pros of this API are: no ANSI escape characters and lines are reported unwrapped as they are send from the underlying program.

### Ansi escape character doesn't show up in problems

- install eslint module (not the extension)
- create a .eslintrc.json file 
- create a JS file that contains errors and warning covered by eslint
- run eslint from a terminal and ensure that the errors correctly show up and are colored.
- create the following task
```
		{
			"label": "ESLint",
			"type": "shell",
			"command": "./node_modules/.bin/eslint app.js",
			"windows": {
				"command": ".\\node_modules\\.bin\\eslint app.js"
			},
			"problemMatcher": "$eslint-stylish"
		}
```
- run that task
- ensure that all problems are capture correctly and that the messages don't contain wired characters in the problem view (e.g no ANSI control characters make it into the message).

### Long lines
- size the VS Code window small so that the output of a task gets wrapped. You can also make an error that produces a long message
- run the task that captures the error (can be ESLint, TS, ....)
- ensure that the error is captured correctly and that the whole message is available in the problems view.

**Comment by egamma** [comment]
Verified that problems are captured when the terminal has to wrap the lines onto multiple lines.
