### ISSUE TITLE
mac debug nodejs

### ISSUE THREAD

**Issue by SeongBrave** [Microsoft/vscode#37140]
![image](https://user-images.githubusercontent.com/10784393/32172334-2ff023aa-bdb6-11e7-83d8-63abd089b74a.png)

**Comment by weinand** [comment]
Please describe the problem in English and with reproducible steps.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
