### ISSUE TITLE
Formatting code does not work for me anymore !

### ISSUE THREAD

**Issue by HamadaBrest** [Microsoft/vscode#37145]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16

Formatting code does not work for me anymore !

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
What language? Can you please provide some steps to reproduce this issue

**Comment by HamadaBrest** [comment]
@mjbvz Javascript, React JS .. Ctrl+Shift+i Doesn't work anymore, I tried it even manually, nothing happen

**Comment by mjbvz** [comment]
So you have tried using the `Format Document` command, and that also doesn't work. If you disable all of your extensions and restart VS Code, do you still see this issue?

**Comment by HamadaBrest** [comment]
I disabled all my extensions and restarted my computer, guess what, it works again :) thank you

**Comment by mjbvz** [comment]
Ok. If you see this issue again, please try tracking down the extension that caused this and opening an issue against them

Closing as caused by extension

**Comment by HamadaBrest** [comment]
Copy that
