### ISSUE TITLE
Visual Studio Code window gets blank

### ISSUE THREAD

**Issue by ryaa** [Microsoft/vscode#37147]
- VSCode Version: 1.17.2
- OS Version: MacOS HighSierr 10.13

Steps to Reproduce:
The problem is intermittent and there is no specific steps that lead to it. I actively using Visual Studio Code for development and from time to time the UI shows blank page (see attached).
In console there are many errors like shell.ts:454 Cannot read property 'uri' of null: TypeError: Cannot read property 'uri' of null (also see attached)
After a while everything gets back to normal but once in a while the problem occurs again and again. It really started after I upgraded to the latest Visual Studio Code and MacOS High Sierra (not sure which of this can be causing the problem)

Reproduces without extensions: Yes/No
N/A (i did not check)
<img width="1380" alt="screen shot 2017-10-30 at 16 49 37" src="https://user-images.githubusercontent.com/3608222/32174581-5520c6ca-bd93-11e7-9d42-6cc0a03b7274.png">
<img width="1050" alt="screen shot 2017-10-30 at 16 51 18" src="https://user-images.githubusercontent.com/3608222/32174588-589a369c-bd93-11e7-8947-83a42c2b96c8.png">

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/35527

Give insiders a try: https://code.visualstudio.com/insiders, some people report it's working for them.
