### ISSUE TITLE
Test git status in explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37159]
Test for: #178

Complexity: 3

- [x] Any OS - @joaomoreno
- [x] Any OS - @mjbvz

We have added git color clues to the explorer. Please test this:

* Check that you see GIT colors and badges for modified, untracked, and ignored files
* Test that you can turn on/off colors and badges via `explorer.decorations.colors` and `explorer.decorations.badges`. 
* Check that those setting-names make sense and that they have good doc
* Test that you can configure the colors in themes or settings via `git.XYZForeground`-settings. 
* Check that those color-names make sense
* Test that the colors work well with our default themes
* Check that label/badges update nicely and that no stale information is shown
* Test that the SCM viewlet shows correct information, test that it shows resources properly that show in two buckets (staged & changed)

**Comment by MrCroft** [comment]
I'm still having problems with **ignored color**. It refuses to apply it.
Just tried setting some lime/bright green so it would be obvious, I thought maybe it's there and I'm not seeing it. But it's not.

Also, notice the "A" badges. Shouldn't those only appear on "Added" files? Right now, they also appear for "Untracked" files.

![image](https://user-images.githubusercontent.com/2809154/32212991-12eae648-be22-11e7-86b2-a837e5ef9bb1.png)
