### ISSUE TITLE
Integrated terminal causing VSCode to freeze

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#37153]
- VSCode Version: 1.17.2
- OS Version: Windows 10 build 16299.19

Integrated terminal freezes sporadically since VSCode version 1.16.

Steps to Reproduce:

1. Open and maximize a terminal
2. Make VSCode window large enough
3. Keep terminal outputting something, e.g. `node -e "var count = 0; setInterval(() => console.log(count++), 100);"`

Screenshot with normal PowerShell on the left side:

![bc8bacf1-5ae0-4bf2-9f1b-099e535c1f8f](https://user-images.githubusercontent.com/970430/32177383-2b3bb888-bdc5-11e7-97b1-0e7c54abd358.GIF)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36913
