### ISSUE TITLE
Our tslint formatter warning and TS formatter is out of sync

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37154]
Steps to Reproduce:

1. open main.contribution.ts
2. format it
3. try to commit

=> fails

Looks like our tslint checker is using different formatter rules compared to the TS version we use.

**Comment by mjbvz** [comment]
Seems to be a formatting change that TS made with 2.6. Switching to use the workspace version of TypeScript (2.5.2) fixes this

 I'm planning to pick up 2.6 for building vscode  in November, which should fix this issue

**Comment by mjbvz** [comment]
Should be fixed now that we've picked up TS 2.6
