### ISSUE TITLE
Touchpad control not smooth

### ISSUE THREAD

**Issue by Harold-K** [Microsoft/vscode#37150]
When I scroll with my touchpad on my Dell Xps 15, the scrolling is jittery

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-icontheme-nomo-dark|be5|1.3.4
path-intellisense|chr|1.4.2
vscode-great-icons|emm|2.1.17
code-runner|for|0.7.4
output-colorizer|IBM|0.1.2
Ionide-fsharp|Ion|3.8.2
plantuml|jeb|2.3.2
vscode-elixir|mjm|1.0.0
vscode-linter-erlc|Nig|0.3.0
indent-rainbow|ode|0.7.2
erlang|pgo|0.1.1
red|red|0.2.1
annotator|ryu|0.10.1
elm|sbr|0.15.1
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
terminal-tabs|Tyr|0.1.1
erlang-otp|yuc|0.2.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
@Ineigo This might already be fixed in 1.8 Insiders: https://github.com/Microsoft/vscode/issues/13612#issuecomment-339961624

Can you give it a try? https://code.visualstudio.com/insiders
