### ISSUE TITLE
Open workspace from Open File

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37152]
It seems when users open a workspace file from the Open File dialog they in most but rare cases want to open the workspace, not the file. Doing so would also allow us to remove the 'Open Workspace' action.

In the rare case where a user wants to open the workspace file, there could still be workarounds like opening the settings editor that currently shows the entire workspace file.

@stevencl Assigning to you for feedback. /cc @bpasero

**Comment by bpasero** [comment]
The motivation for separating the actions is to have deterministic behaviour: opening a file will always just do that no matter what extension the file has. It seemed weird that it would sometimes open a file to show the contents and sometimes changes the window to load the workspace.

**Comment by stevencl** [comment]
I agree with Ben. On top of that, I think removing the Open Workspace action would be detrimental to the overall experience as it would look like we have a way to save a workspace but no corresponding way to open the saved workspace. The workspace commands also make the concept of a workspace more explicit.

**Comment by chrmarti** [comment]
Fine with me. Thanks.
