### ISSUE TITLE
Feature Request - Set Zoom Percentage

### ISSUE THREAD

**Issue by bauwaerter** [Microsoft/vscode#37158]
"Persisted Zoom Level
When you adjust the zoom level with the View > Zoom In / Out commands, the zoom level is persisted in the window.zoomLevel setting. The default value is 0 and each increment increases the zoom level by 20%."

Currently the zoom is increased or decreased by a static value of 20%. It would be nice to have a setting variable to allow the user to set a custom zoom percentage like 10%.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by g13013** [comment]
@bpasero how do you guys track closed "good" feature requests?

**Comment by bpasero** [comment]
@g13013 if there are good, other people will also report them and even more people will upvote them. E.g. see: https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by g13013** [comment]
@bpasero thanks you for the clarification, I came specifically for this issue, anyways.

@bauwaerter enable `mouseWheelZoom `, it's much more precise !

```json
"editor.mouseWheelZoom": true

**Comment by bauwaerter** [comment]
Thank you! Did not know that was a setting option.
