### ISSUE TITLE
Test: Quicklook for source files supported by Code

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37165]
Tests #25843

Complexity: 1

- [ ] macOS -  @roblourens 

[File types supported by Code](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L140) should now be able to be displayed as source code when using the <kbd>Space</kbd> key in Finder: their source should be readable.

**Comment by roblourens** [comment]
I'm not clear what this change does. I can see the contents of the file with quicklook in Finder. But I can also see that when Insiders isn't installed. #25843 implies that the feature was to add syntax highlighting, but I don't see syntax highlighting for any file.

Also, it doesn't work for any `.ts` file. We also tried on Matt's mac. This makes me think that vscode actually isn't making a difference here, quick look is just working for files that macOS thinks are text files.

**Comment by joaomoreno** [comment]
True... it seems it didn't make any difference.
