### ISSUE TITLE
Folding hitboxes not correctly triggering

### ISSUE THREAD

**Issue by solidxsnake** [Microsoft/vscode#37160]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-color|ans|0.4.5
python|don|0.7.0
tortoise-svn|fan|0.1.1
diff-tool|jin|0.0.1
theme-dark-plus-contrast|k3a|0.1.101
Lisp|mat|0.1.7
cpptools|ms-|0.14.0
SystemVerilog|msh|0.0.15
VerilogHDL|msh|0.0.13
diff|raf|0.0.1
partial-diff|ryu|0.4.1
code-settings-sync|Sha|2.8.3
---

Steps to Reproduce:

1. Open any foldable code
2. Clicking on left-half of folding box will not cause code to fold. Clicking on the right-half of the box causes folding to work properly

![folding_bug](https://user-images.githubusercontent.com/8855615/32181119-0365a0ae-bd6a-11e7-88ff-bae576dcc352.gif)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@aeschli Nudged the click area by 2 pixels.

**Comment by solidxsnake** [comment]
- VSCode Version: Code - Insiders 1.19.0-insider (d6fbdcf19716910b26ea81efc95724f2fabe5aa6, 2017-11-10T05:17:03.030Z)
- OS Version: Windows_NT x64 6.1.7601

The hitbox still seems to be off in the latest build. Notice that the mouseover cursor appears when the mouse is between the folding box and the gutter border (on the right).

![folding_bug](https://user-images.githubusercontent.com/8855615/32667232-1a1ba1bc-c608-11e7-8b63-d664cbcb01d8.gif)

**Comment by joaomoreno** [comment]
Yes. The mouse cursor is lying. But the hit area is correct. That hit area is now reserved for inline changes. cc @aeschli
