### ISSUE TITLE
I cannot open a document with cmd-p and still have my current document open any more.

### ISSUE THREAD

**Issue by larrywberg** [Microsoft/vscode#37169]
When using cmd-p to find another document, i wind up losing one of my tabbed documents and it's not the current one.  It's a random previous one.  I want it to open a new tab with the document I select

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
tslint|eg2|1.0.14
skew-vscode|eva|0.7.41
cpptools|ms-|0.14.0
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
When the file is opened by single click, they are in "preview" mode and opening a new one will reuse the editor window of the current active file.

You can try setting  `"workbench.editor.enablePreview": false` or `  "workbench.editor.enablePreviewFromQuickOpen": false`.

**Comment by larrywberg** [comment]
It doesn't use the current active tab unless I actually save it to a file.  That's wrong.  I should be able to open a new tab, then click cmd-p and use that tab.  Instead it goes back to a previous tab.

**Comment by larrywberg** [comment]
that said,  changing those flags does work for me for what I want so far

**Comment by octref** [comment]
> It doesn't use the current active tab unless I actually save it to a file.

That's because that file / tab is "dirty" (having unsaved changes), and our default behavior is not to close / reuse any dirty file / tabs.
