### ISSUE TITLE
HTML comments not responding to editor customizations

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#37175]
- VSCode Version: Code - Insiders 1.18.0-insider (e6a76e4bd3f52ab07452bb181e861f5a9bfb6596, 2017-10-27T05:12:19.123Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-eslint|dba|1.4.0
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
svg|joc|0.0.9
Angular2|joh|2.10.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.30.0
Align|ste|0.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I have a theme where comments are not italic.  I decided to override this in the user settings rather than change the theme.
2. So, I added this:

````json
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  },
````

All the comments in all file types _except_ html are italicizes as expected:  js, scss, json, etc. work fine.

<img width="567" alt="screen shot 2017-10-30 at 3 54 22 pm" src="https://user-images.githubusercontent.com/835148/32192466-a35f11ba-bd8a-11e7-9f7e-13851dca80e0.png">

Comments in html are still non-italic.

<img width="551" alt="screen shot 2017-10-30 at 3 53 26 pm" src="https://user-images.githubusercontent.com/835148/32192415-7df6aba4-bd8a-11e7-8929-9ec5a1ae8029.png">

**Comment by octref** [comment]
Can you do Cmd+Shift+P -> Inspect TM Scopes and put that on the comment, and show us the screenshot?

**Comment by smlombardi** [comment]
<img width="654" alt="screen shot 2017-10-31 at 7 42 06 pm" src="https://user-images.githubusercontent.com/835148/32253862-9f9a628e-be73-11e7-8f0e-9282c1441a22.png">

**Comment by octref** [comment]
Your theme has a definition on `comment.block.html` that overrides `comment` because it's more specific.

To override over your theme, add this too:

```json
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic"
        }
      },
{
        "scope": "comment.block.html",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  },
```

**Comment by smlombardi** [comment]
Thanks, I didn't think of two entries.  I _had_ tried just `comment.block`.

I just tried this, as an alternate, and it works too:

```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment, comment.block.html",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  },
```
