### ISSUE TITLE
Strange things with Visual Code window Title happen when The window is moved, resized or another app is call on the front

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#37170]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|0.22.0
ng-template|Ang|0.1.7
vscode-custom-css|be5|2.5.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
ionic3-vs-ionView-snippets|dan|1.0.1
vscode-instant-markdown|dba|1.3.0
vscode-great-icons|emm|2.1.19
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
composer|ika|0.5.0
yii2-snippets|ima|0.0.9
ionic2-vscode|jgw|1.0.0
Angular2|joh|2.10.0
typings-autoinstaller|jvi|1.2.0
ionic-extension-pack|loi|0.0.1
markdown-shortcuts|mdi|0.8.1
gitignore|mic|1.0.1
debugger-for-chrome|msj|3.4.0
live-server-preview|neg|0.0.4
rxjs-snippets|pko|0.0.2
vscode-icons|rob|7.17.0
autoimport|ste|1.2.2
ionic2|Tha|3.0.1
Angular2|UVB|0.4.1
cordova-tools|vsm|1.2.13
markdown-authoring|yan|0.1.5

(2 theme extensions excluded)

---

Steps to Reproduce:

1.Open Visual Code: the title is Visual Studio Code: Ok
2.Resize the window: the title indicate the folder and file of the editor selected
3.Close the folder the title doesn't change
4.Resize the window the title show Welcome visual Code
5.Open another folder from the welcome the title stay whith the welcome title
6.Resize the window we get the title as in point 2.

I discover that using the screen capture or going to my web browser and coming back. So it's related to the window event

Reproduces without extensions: Yes
![image](https://user-images.githubusercontent.com/624802/32188442-20aa9b22-bda8-11e7-8fcb-5965a249f1bd.png)
![image](https://user-images.githubusercontent.com/624802/32188457-2f74ff8a-bda8-11e7-93f3-099ec1ef8d7e.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/36955
