### ISSUE TITLE
[json] Provide syntax highlighting for .ember-cli and .watchmanconfig

### ISSUE THREAD

**Issue by jeff-da** [Microsoft/vscode#37174]
VSCO currently does not support syntax highlighting for common JSON file types (like .watchmanconfig). As these file types become more and more popular, it would be really cool to see syntax highlighting for these files in VSCO.

Steps to Reproduce:

1. Open a .watchmanconfig or .ember-cli file.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Note that, in the meantime, you add the associations also in your user settings
