### ISSUE TITLE
[strange behavior] Doubleclick by resize cursor will "reduce panel" instead of "restore default size".

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#37172]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

![screenshot_117](https://user-images.githubusercontent.com/31345346/32189888-50b4ba2e-bdac-11e7-87d6-92608fbc53da.png)

doubleclick (where is cursor on screenshot)

Result:

![screenshot_119](https://user-images.githubusercontent.com/31345346/32189940-7c4d2d92-bdac-11e7-8a88-19a8ea18051e.png)

I think it should do nothing or restore default size.

Reproduces without extensions: **Yes**

**Comment by octref** [comment]
Probably related to #36963

**Comment by isidorn** [comment]
Fixed in latest
