### ISSUE TITLE
Quick suggestions not shown for `${|` template string

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37176]
Followup on #34857

**repo**
1. In a js file, type:
```
`${|`
```

2. Then type `c` at the `|`

**Bug**
Quick suggestions are not shown in this case

**Comment by Mlocik97-issues** [comment]
I said it cca 5 months ago.

**Comment by mjbvz** [comment]
@Mlocik97-issues This bug tracks the specific case:

```
`${|`
``

Case such as:

```
`${|}`
`${| `
`${| x`

were fixed by #34857

**Comment by mjbvz** [comment]
Basic issue is that we can't distinguish:

```
`${`
```

From valid code like:

```
`${`abc`}`
```

In that case, quick suggestions should not be shown since you would be inside of a string again

**Comment by mjbvz** [comment]
Broke when I changed to using selector matching instead of direct comparisons for scopes. Will require a fix on vscode textmate
