### ISSUE TITLE
Several files in resources\* are not latest

### ISSUE THREAD

**Issue by yamlfd** [Microsoft/vscode#37187]
The reprository contains outdated files. Can someone commit the latest files, please?

Here is the list of outdated files I have found for sure:

- \resources\win32\code.ico
- \resources\win32\code_file.ico
- \resources\win32\inno-big.bmp
- \resources\win32\inno-small.bmp
- \resources\linux\code.png
- `\licenses\*` folder is completly missing

The repro contains blue/wite images, but the latest setup contains orange/white ones. I guess there are more files out of date.

**Comment by octref** [comment]
Those are for VS Code dev builds. I don't know much of the details -- passing to @joaomoreno.

**Comment by yamlfd** [comment]
That is also in tagged releases source code and master. master should be the latest, but it not.

**Comment by joaomoreno** [comment]
Those are open source Code resources. The Visual Studio Code resources are not open source.

**Comment by yamlfd** [comment]
You mean the orange icon is not open source, but thr blue? Good that we are talking about this. The vscode ZIP file download from ms is open dource or closed source?

I’m currently completing the MSI setup for VSCode. I can extract all this logos from the inno setup with inno unpacker and share the WiX versions with you.

It is required to create new images of different sizes for WiX. If I‘m not allowed to use the orange logos I have a problem and cannot complete work.

I feal like ms has not understood open source and community. How should we work as community together if you only share the half files, but I need all of them for the setup???
