### ISSUE TITLE
View size set when registering views is ignored in split view

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37189]
The default view of the Extensions viewlet uses split view to show 2 views
View for Installed extensions is registered with size 200. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L148
View for Recommended extensions is registered with size 600. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L170

To ensure the sizes in local storage arent used, comment this line:  https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L651

Now run vscode from source and go to extensions viewlet.
You will see that the first section takes up most of the space and the second section gets the minimum height.

I was able to trace it down to the `resize` method in the `splitView.ts`. It first applies the `item.view.minimumSize` to both the views. Then in the subsequent calls to `resize`,  the second view maintains the min size and rest of the space gets allocated to the first view.

**Comment by joaomoreno** [comment]
@sandy081 This is slightly related to https://github.com/Microsoft/vscode/issues/36887, which we talked about last week. It's the same behavioural outcome.

But your `ViewsViewlet`, on first registration of the panels, could and should resize the panels to their right sizes. I'll leave that to you.

**Comment by mikes-gh** [comment]
I am not sure if @joaomoreno means the above post as a fix.
I have the same issue.
Resizing the installed extension view is reset on restarting vscode.
It alwys seems to reset to only show 2 extensions out of the 9 I have installed.
I would have thought the view would resize to include all installed extensions.

**Comment by sandy081** [comment]
@ramya-rao-a Fixed this.

May I know if you prefer to have a new id for extensions views state? Or is it ok to continue with current? I would prefer to continue with current, it will retain the users state.

**Comment by sandy081** [comment]
To verify,

- Have some extensions installed
- Open VS Code in a new user data director `code-insiders --user-data-dir <new dir>` 
- Open Extensions viewlet
- Installed section should take 30% and Recommended section should take 70%
