### ISSUE TITLE
Test: Updates to Recommendation Views and extensions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37186]
Complexity: 3

- [x] macOS @alexandrudima
- [x] Linux @aeschli
- [x] Windows @egamma

**Testing updates to File based recommendations**
 - Open a folder with no Workspace Recommendations. (i.e. no `extensions.json` file in the `.vscode` folder)
 - Open any java/vue/cs/python file. Corresponding extensions should get recommended via the pop up 
 - `Install` should open the "Recommended View" and install the extension
 - `Show Recommendations` should open the "Recommended View"
 - In the `Recommended View`, "Workspace Recommendations` section should be collapsed.

**Testing updates to Workspace recommendations**

- Click on the edit icon to configure workspace recommendations. (Try this in multi root mode as well)
- Save and Reload Window, you should see pop up for "Workspace Recommendations"
-  `Show Recommendations` should open the "Recommended View" with the `Workspace Recommendations` view now expanded.
- Click on the download icon on the header to install all recommendations

**Testing  Recommendation Indicators**

In the default view, ensure you have some recommendations. Type search text in the search box to get the recommendations in the search results
- You should be able to differentiate the recommended extension from rest of the search results due to the badge on the top left
- Hovering on the list item should display the recommendation reason
- The same reason should also appear in the extension editor which you can open by clicking on the list item

**Comment by alexandrudima** [comment]
:+1: I really like the green badges on recommended extensions
