### ISSUE TITLE
Code isn't launching without an internet connection

### ISSUE THREAD

**Issue by gdwnet** [Microsoft/vscode#37188]
- VSCode Version: 1.17.1
- OS Version: Windows 10

Steps to Reproduce:

1. Offline mode (no internet at all), Code will not launch.

Reproduces without extensions: Yes

Launching code in --verbose mode I see this:

C:\Program Files (x86)\code>Code.exe --verbose

C:\Program Files (x86)\code>
net.js:10
const cares = process.binding('cares_wrap');
                      ^

Error: EFILE
    at net.js:10:23
    at net.js:1645:3
    at NativeModule.compile (bootstrap_node.js:535:7)
    at NativeModule.require (bootstrap_node.js:475:18)
    at internal/child_process.js:6:13
    at internal/child_process.js:903:3
    at NativeModule.compile (bootstrap_node.js:535:7)
    at NativeModule.require (bootstrap_node.js:475:18)
    at child_process.js:12:23
    at child_process.js:542:3

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7570
