### ISSUE TITLE
Provide case sensitive "Highlight All Occurrences of a Symbol" without language server.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#37195]
- VSCode Version: 1.17.2
- OS Version:

![gif](https://code.visualstudio.com/images/language-support_document-highlights.gif)

Currently,when a language server is not enabled, if "Highlight All Occurrences of a Symbol" is case sensitive, is controlled by the find widget toggle.  

But I think in most programming language, the Symbol is case sensitive. If you highlight a variable not case sensitive, it is hard to find some typing mistakes.

And case sensitive of  "Selection highlight":  https://github.com/Microsoft/vscode/issues/34185

Do they need a seperate setting? Or case sensitive by default?

**Comment by octref** [comment]
I mean, if a LS is active, that's delegated to LS.
If not, I think what the current find widget does is reasonable. You can just enable case sensitivity in find widget.
