### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#37192]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.0.3
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-abap|lar|0.1.0
Go|luk|0.6.66
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vscode-docker|Pet|0.0.20
vscode-icons|rob|7.17.0
vscode-table-formatter|shu|1.2.1
vscode-hexdump|sle|1.6.0
addDocComments|ste|0.0.8
html-preview-vscode|tht|0.1.1
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Steps to Reproduce: (not reproduceable)

1. Open Vetur settings
2. Click on contributions

Reproduces without extensions: Yes/No

Processes: 
![procexp64_2017-10-31_00-36-29](https://user-images.githubusercontent.com/17984549/32200819-d4eee996-bdd3-11e7-84fc-76ff8eb6356a.png)
Command line:
`"C:\Programme\VSCodeInsider\Code - Insiders.exe" C:\Users\mxs\.vscode-insiders\extensions\wix.vscode-import-cost-2.5.1\node_modules\worker-farm\lib\child\index.js "C:\Programme\VSCodeInsider\Code - Insiders.exe" c:\Programme\VSCodeInsider\resources\app\out\bootstrap --type=extensionHost`
Process Explorer Performance Tab:
![procexp64_2017-10-31_00-42-11](https://user-images.githubusercontent.com/17984549/32200918-5f5fa7f0-bdd4-11e7-919d-9b19c0647d4c.png)

Hi,

I'm not so familiar with the process structure of VS Code, but in the command line arguments of the process which used so much RAM, there is the extension `wix.vscode-import-cost-2.5.1` loading. Could this process used only for this extension, so that this is the cause of the high memory usage?

I tried to run the Dev Tools Performance Profiler, but it never finished, because of the always 100% usage of my memory in my notebook I think.

Best regards

**Comment by maxibanki** [comment]
Again the same problem now with these details:

- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.0.3
jshint|dba|0.10.15
vscode-eslint|dba|1.4.0
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-abap|lar|0.1.0
Go|luk|0.6.66
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
vscode-icons|rob|7.17.0
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
html-preview-vscode|tht|0.1.1

The processes with the high memory usage are again started with these parameters.
`"C:\Programme\VSCodeInsider\Code - Insiders.exe" C:\Users\mxs\.vscode-insiders\extensions\wix.vscode-import-cost-2.5.1\node_modules\worker-farm\lib\child\index.js "C:\Programme\VSCodeInsider\Code - Insiders.exe" c:\Programme\VSCodeInsider\resources\app\out\bootstrap --type=extensionHost`

Now I removed the `wix.vscode-import-cost-2.5.1` extension, to see if the memory leak again occurs.

**Comment by AngeloCicero** [comment]
I had to stop using VSCode for the past few days because after using it for a while for Vue development (with Vetur of course), my entire computer seems to lock up and cannot even access the internet. Thanks for the investigation, I thought I was crazy.

**Comment by maxibanki** [comment]
Hi Angelo,
In the first test I had Vetur installed, and on the second not, because I thought this was the course. Now I'm thinking more and more that it's the fault of the [wix.vscode-import-cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost) extension.

**Comment by octref** [comment]
I don't really use that extension, but it seems it analyzes whatever file that's open? https://github.com/wix/import-cost/issues/18

Does it happen if you disable vscode-import-cost extension?

**Comment by maxibanki** [comment]
Hi,
I've been using it about 6-12 hours now without this extension. There were no problems, so it seems that the extension is the reason for the memory leak.

**Comment by octref** [comment]
In that case, I suggest you open an issue for import-cost or disable it.

**Comment by maxibanki** [comment]
This issue was moved to wix/import-cost#35
