### ISSUE TITLE
Edit file Over FTP from nemo at Linux Mint

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#37197]
- VSCode Version: 1.18.0-insider
- OS Version: Linux Mint 18.2 Sonya - 4.10.0-37-generic

Steps to Reproduce:
1. At Linux Mint 
2. Open file manager (Nemo)
3. Connect to external/Remote FTP Server with "ftp://" syntax
4. Click to edit file
5. Try to Save file
6. Got this system error:
`Ocorreu um erro de sistema (ESPIPE: invalid seek, write)`
7. Other editors like gedit works fine

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6854
