### ISSUE TITLE
Terminal cursors show as a outlined block when unfocused.

### ISSUE THREAD

**Issue by technoiswatchingyou** [Microsoft/vscode#37194]
Terminal cursors show as a outlined block when unfocused. No matter what settings in "terminal.integrated.cursorStyle": "". I guess it will be more natural if cursor just stop to blink or option for change cursor color if terminal unfocused.

- VSCode Version: 1.17.2
- OS Version: 10.13.2

Steps to Reproduce:

1. Open integrated terminal
2. Change focus to editor

![screen shot 2017-10-31 at 10 59 33 am](https://user-images.githubusercontent.com/25575840/32202763-9c02c11e-be2a-11e7-9749-90000281a2d8.png)

Reproduces without extensions: Yes

**Comment by levani** [comment]
This is how terminal cursor behaves in linux I believe and it's pretty good UX

![screenshot_5](https://user-images.githubusercontent.com/184472/32227917-11695766-be66-11e7-80d2-301f3b723d68.png)

**Comment by Tyriar** [comment]
Yes this is as designed, if the terminal has the cursor visible it will show like this when unfocused regardless of the cursor style.
