### ISSUE TITLE
Test Tour: Use embercli to create a web app (JavaScript)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3719]
http://ember-cli.com/

**Comment by Tyriar** [comment]
1. Installed dependencies
2. Scaffolded Ember CLI app

 :bulb: Noticed no highlighting when there could easily be on the following files:
 - `.ember-cli` (json) https://github.com/Microsoft/vscode/issues/4462
 - `.gitignore` (# comments) https://github.com/Microsoft/vscode/issues/4465
 - `.watchmanconfig` (json) https://github.com/Microsoft/vscode/issues/4463
 - `robots.txt` https://github.com/Microsoft/vscode/issues/4464

3. Built and served app
4. Looked for the view being displayed using search

 There is a ./tmp/ directory that contains output from babel as well as a ./dist/ directory containing the actual site from `ember build` which makes search very difficult to use.

 ![image](https://cloud.githubusercontent.com/assets/2193314/13902099/290cc2e4-edf8-11e5-9ff2-acd738dade25.png)

  ![image](https://cloud.githubusercontent.com/assets/2193314/13902104/531abdde-edf8-11e5-9cf1-9b1ec857c490.png)

 :bulb: Perhaps ember-cli would accept a vscode configuration file that excluded `dist/, tmp/` from the search? `tmp/` could even be hidden or faded from the file explorer.

 :bulb: When customizing the search I tried to horizontal scroll the files excluded through settings using <kbd>shift</kbd>+`mouse wheel` and found it does not scroll correctly (https://github.com/Microsoft/vscode/issues/4461):

 ![image](https://cloud.githubusercontent.com/assets/2193314/13902120/cbc95e5c-edf8-11e5-9da0-ddf5e0ef26fa.png)

5. Picked up [this tutorial](https://www.smashingmagazine.com/2016/01/write-next-web-app-ember-cli/) to build out an example app.

**Comment by Tyriar** [comment]
Make a PR to ember-cli for the `search.exclude` setting https://github.com/ember-cli/ember-cli/pull/5643
