### ISSUE TITLE
When I using Python in vscode, sometimes the debuging failed and the debug console didn't give any infomation.

### ISSUE THREAD

**Issue by landwash** [Microsoft/vscode#37207]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.7.1
python|don|0.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
VS Code does not ship with a builtin python debugger.
Please file this issue against the python debugger.
