### ISSUE TITLE
Suggestions for wordSeparators

### ISSUE THREAD

**Issue by Kurt-Shiwz** [Microsoft/vscode#37202]
- VSCode Version:
1.17.2
- OS Version:
10.13

Sometime I whill write some chinese work (not in a-zA-Z or digital, not a ascii character), I already set "editor.wordSeparators" to "\`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?`、：，。“”‘；`", but there also have some problem.
![image](https://user-images.githubusercontent.com/7554917/32206151-6a66e992-be2e-11e7-8f84-d47c09dfad88.png)
vscode can't find "test" is a word, so quickSuggestions don't effect. but if i type space it will work.
![image](https://user-images.githubusercontent.com/7554917/32206425-edf4c864-be2f-11e7-82cc-ec78806db769.png)

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@Kurt-Shiwz The word suggestions do not use `editor.wordSeparators`, they use whatever makes sense in the programming language you are working in. i.e. each programming language defines what constitutes a word for it, mostly based on the language syntax. 

What programming language are you using ?

**Comment by Kurt-Shiwz** [comment]
On plaintext or .json(string) or .cpp(string)

**Comment by alexandrudima** [comment]
Word definitions:

* plaintext: `` /(-?\d*\.\d\w*)|([^\`\~\!\@\#\$\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g `` . Defined [here](https://github.com/Microsoft/vscode/blob/83d70421713ab6ba4498c7dca868f77d1215d52d/src/vs/editor/common/model/wordHelper.ts#L32)

* json: `` /("(?:[^\\\"]*(?:\\.)?)*"?)|[^\s{}\[\],:]+/ `` . Defined [here](https://github.com/Microsoft/vscode/blob/83d70421713ab6ba4498c7dca868f77d1215d52d/extensions/json/client/src/jsonMain.ts#L166)

* C++: falls back to the same as plaintext.

PR welcome. As VS Code is aimed at authoring source code, our priority is to make the default configurations for word definitions match more those of a programming language than those of a rich text editor.

**Comment by Kurt-Shiwz** [comment]
plaintext: regexp change to that，it will be better
/(-?\d*\.\d\w*)|([^\`\~\!\@\#\$\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s[:^ascii:]]+)/g

**Comment by Kurt-Shiwz** [comment]
plaintext can use that 
```(-?\d*\.\d\w*)|(\w+)```

**Comment by alexandrudima** [comment]
`\w` would make it significantly worse:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
![image](https://user-images.githubusercontent.com/5047891/32317146-159336d8-bfb3-11e7-8ef2-ccf86c6ed70b.png)

e.g. of running with that change:

![image](https://user-images.githubusercontent.com/5047891/32317249-78be9432-bfb3-11e7-8d35-3404e71d6927.png)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
