### ISSUE TITLE
TypeError: Path must be a string. Received null: VSC Insiders

### ISSUE THREAD

**Issue by andybarlow** [Microsoft/vscode#3720]
!TypeError: Path must be a string. Received null! when trying to debug in Node using VSC Insiders. Works fine in regular VSC.

**Comment by isidorn** [comment]
Andre I believe this is a duplicate, right?

**Comment by andybarlow** [comment]
Sorry, yes - I forgot to check first….

Andy Barlow
t: +44 7830 302268


 
www.datum360.com <http://www.datum360.com/>
...delivering a measured approach to engineering information
 
Please be advised that this email may contain confidential information.

If you are not the intended recipient, please do not read, copy or re-transmit this email.  If you have received this email in error, please notify us by email by replying to the sender or by telephone and delete this message and any attachments.  Thank you in advance for your cooperation and assistance.

In addition, Datum360 disclaim that the content of this email constitutes an offer to enter into, or the acceptance of, any contract or agreement or any amendment thereto; provided that the foregoing disclaimer does not invalidate the binding effect of any digital or other electronic reproduction of a manual signature that is included in any attachment to this email.

**Comment by weinand** [comment]
This is a duplicate of #3625.
Please see work around there.
