### ISSUE TITLE
hyperlink of node_modules from .ts file to js modules without definition

### ISSUE THREAD

**Issue by evollu** [Microsoft/vscode#37203]
- VSCode Version: 1.17.0
- OS Version: mac

Steps to Reproduce:

For example following code  `var Kafka = require('node-rdkafka');`. 
- When this code is in a js file, I can cmd+click to go to the index.js file in node_modules and hovering over shows definitions.
- When this code is in a ts file, nothing happens when I hover to click. tsc compiles without any complaint so tsconfig.json should be fine.
- I tried `import * as Kafka from 'node-rdkafka'` and it is the same behavior

here is tsconfig.json
```
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "es2017"
        ],
        "outDir": ".dist",
        "sourceMap": true,
        "removeComments": false,
        "alwaysStrict": true
    }
}
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20182
