### ISSUE TITLE
The Output Start with Error Encoding printout

### ISSUE THREAD

**Issue by cyroby** [Microsoft/vscode#37209]
- VSCode Version:1.17.2

- OS Version:Win 10 Enterprise

Steps to Reproduce:

1.Debug C# Project
2.Watch the Output or Debug Console.
![errorencoding](https://user-images.githubusercontent.com/11662528/32211789-227abd68-be4f-11e7-9b25-0827c7bf183d.png)
The error encoding make me puzzling.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
VS Code does not ship with a builtin C# debugger.
Please file this issue against the C# debugger.
