### ISSUE TITLE
Allow insert code + move cursor operation to extension developers

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#37204]
- VSCode Version: 1.17.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Install https://github.com/Microsoft/vscode-cpptools/ extension
2. Start writing cpp source files. When auto-completion pops-up, select a member method and notice it only inserts name. For example, `a.doSomething` instead of `a.doSomething()` with cursor in b/w parenthesis.

More details here - https://github.com/Microsoft/vscode-cpptools/issues/1184#issuecomment-340503735

Reproduces without extensions: No

**Comment by octref** [comment]
IIRC this is totally possible with LSP with `CompletionItem.insertText` as `SnippetString`.

/cc @dbaeumer just to confirm.

**Comment by dbaeumer** [comment]
Yes, I think that is possible however it would require either snippets or additional text edits. 

@jrieken what is your take on this. How would a completion item provide best achieve this.

**Comment by jrieken** [comment]
This https://github.com/Microsoft/vscode/issues/37204#issuecomment-340936936

**Comment by dbaeumer** [comment]
@jrieken thanks for the confirmation.

Closing. Added comment to https://github.com/Microsoft/vscode-cpptools/issues/1184#issuecomment-341039314

**Comment by bobbrow** [comment]
Ok.  I see `CompletionItem.insertTextFormat` in the language server protocol.  This seems to have been added after we took a snap of the protocol types.  Looks like it's time to update them.
