### ISSUE TITLE
Error while installing new update 

### ISSUE THREAD

**Issue by salmanfarisvp** [Microsoft/vscode#37206]
- VSCode Version:1.17.2
- OS Version: Win10 Pro

Steps to Reproduce:

1.install vscode 1.15.1 
2.update vs code followed by the popup window 

Reproduces without extensions: Yes

-Screen Shot 
![vs](https://user-images.githubusercontent.com/11945360/32208750-7eeadada-be2a-11e7-9ffc-16e0fd218dd0.PNG)

**Comment by joaomoreno** [comment]
Can you please fully reinstall Code?
