### ISSUE TITLE
VSCode search is super slow when Kaspersky Endpoint Security is turned on

### ISSUE THREAD

**Issue by suheti** [Microsoft/vscode#37205]
- VSCode Version: 1.17.2
- OS Version: macOS Sierra 10.12.6 (16G29)

Steps to Reproduce:

1. With Kaspersky on, open a large project in vscode (my workspace was 250MB+, for reference)
2. cmd-shift-f search for some terms, many will take a long time (a few seconds) to finish the search.
3. Turn off Kaspersky, search for the terms, and search for some new terms in case some result has been cached, the search goes blazing fast.

Reproduces without extensions: Yes

I'm mainly writing python and django apps, if it helps. And yes the problem exists with extensions off. Any idea why this happens? Thank you!

**Comment by roblourens** [comment]
This isn't surprising, I see the same with Windows Defender sometimes. These programs are trying to protect you by scanning every file when it's opened. If you try a few times, it will probably cache the result, making the search faster. I don't think there's anything we can do on our end to improve the situation. But let me know if you see search working significantly faster in other editors with Kaspersky on.

**Comment by suheti** [comment]
Thank you roblourens for your prompt reply! My colleague whose using PyCharm report no such slowdown. (perhaps due to its indexing?) But the constant indexing of JetBrain IDEs itself could be an irritation from time to time.

**Comment by roblourens** [comment]
Yeah, PyCharm does index ahead of time, which would prevent that.
