### ISSUE TITLE
useIgnoreFilesByDefault is a bad setting name

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37210]
Refs #37179

`"search.useIgnoreFilesByDefault": true` sounds ugly, why should the word default be part of this setting name. I propose the following name:
`"search.respectIgnoreFiles"`

**Comment by joaomoreno** [comment]
Agreed. What does `byDefault` even mean in this case?

**Comment by chrmarti** [comment]
Agree, I was using the existing setting for text search, but that might not be a good fit here. (Also: #37291)

**Comment by roblourens** [comment]
`useIgnoreFilesByDefault` isn't the right setting to use for quickopen here. It determines whether the 'use ignore files' button in the search viewlet is selected by default in a new workspace.

https://github.com/Microsoft/vscode/issues/32035

Let's talk about it tomorrow @chrmarti

**Comment by chrmarti** [comment]
Fixing with #37291. Marking as duplicate of #37291.
