### ISSUE TITLE
Ignore files not applied to editor history

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37215]
Refs: #37179

OS: mac

1. Open vscode repository, open gitignore file and add `/isidor` to the last line
2. Now create a isidor top level folder and inside a hello.txt
3. Notice the hello.txt properly not being picked up by git
4. Have search.useIgnoreFilesByDefault: true and search for hello.txt in quick open -> I get results
If I reload vscode it still does not work (hello.txt is found)

I would expect the quick open to respect my gitignore and that hello.txt is not found.

**Comment by chrmarti** [comment]
This might be hard to fix without a library implementing the ignore globs.

**Comment by joaomoreno** [comment]
I'd just close this. 😄
