### ISSUE TITLE
Find in Folder... option isn't working as expected

### ISSUE THREAD

**Issue by BeauAgst** [Microsoft/vscode#37219]
- VSCode Version: 1.18.0-insider & 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project with mulitple folders and files.
2. Choose a random folder, and select 'Find in Folder...'
3. Enter a search query for a string you know exists. 
4. No results will be returned.

Example, I have a folder structure in my project like so:
![image](https://user-images.githubusercontent.com/10343831/32216487-08f766ac-be1d-11e7-8eca-03db2dc5f879.png)

I right-click 'New folder (7)' and choose 'Find in Folder...'. I search for 'string'. No results are found. I know it exists, I have the file open.
![image](https://user-images.githubusercontent.com/10343831/32216560-3d8b264c-be1d-11e7-82ff-1ece1807b411.png)

I select 'Search again in all files'. The file is found.
![image](https://user-images.githubusercontent.com/10343831/32216604-6346d9f8-be1d-11e7-99e0-afd9708da089.png)

Is this intended behaviour? It's very difficult to search for a specific string or file when you have a 100+ folder project.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is because of the `()` characters which are handled as glob characters. I don't have a great way to deal with searching folders that contain glob characters. Escaping won't work because you can also use a backslash as a path separator.

**Comment by roblourens** [comment]
#16834
