### ISSUE TITLE
No help to setup cloud shell on azure

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37214]
Refs: #37180

If I do not have a cloud shell setup on azure, upon running the action Azure: Open Cloud Shell vscode will give me the following msg
`The first time the Cloud Shell requires set up in the Azure Portal (https://portal.azure.com).`
I can open the portal and there I search for cloud shell - I find nothing. Not sure what to do next and if we can somehow improve this experience to the user. Potentially adding another action in the message mox (more info) which could take the user to some cloud shell azure tutorial.

**Comment by chrmarti** [comment]
I'm told there will be a direct link to the Cloud Shell in the future.

**Comment by chrmarti** [comment]
This was changed to open `shell.azure.com` which lands in the Cloud Shell directly.
