### ISSUE TITLE
Source Control Providers list resets to 5 visible when selecting repository

### ISSUE THREAD

**Issue by drjonnicholson** [Microsoft/vscode#37216]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
vagrant|bbe|0.5.0
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.11.0
jshint|dba|0.10.15
githistory|don|0.2.3
xml|Dot|1.9.2
php-debug|fel|1.11.1
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
latex-workshop|Jam|3.5.5
php-symbols|lin|2.1.0
vscode-antlr4|mik|1.1.10
vscode-todo-parser|min|1.9.1
HTMLHint|mka|0.4.0
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
vetur|oct|0.10.1
java|red|0.12.0
vscode-icons|rob|7.17.0
code-spell-checker|str|1.4.12
vscode-lua|tri|0.9.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0
gitblame|wad|2.2.0
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. In a folder, e.g. `c:\dev\` clone several repositories, e.g. 10.
1. Open that same folder in VSCode, so that each repository is a folder in that workspace Why am I doing this? Because it makes doing consistent search/replace across several projects/repositories very easy)
1. Go to Source Control and it will show your repositories in a list, 5 visible and the rest hidden - you have to scroll to see more.
1. Increase the size of the Source Control Providers box so that all are visible
1. Select a different  source control provider - the box will shrink back to showing only 5. Worse, the list will always show the top 5 first, not the one selected and the two either side of it, meaning you easily lose your place and have to resize the box/scroll again to continue.

Additional feature request based on this: Allow the ability to commit all staged (or all files if none are yet staged) files in all repositories with the same commit message. E.g. if I have made changes to make something consistent across many repositories in this way I would usually commit to each repository with the same commit message. This feature would save copy/paste of commit message.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Fixed in `master`. Give Insiders a try to confirm.

**Comment by drjonnicholson** [comment]
Just downloaded and tried the insiders build, and now the list doesn't automatically resize. Thanks!

How long before this'll make it through to the main release? Prefer not to use insiders for day to day development.
