### ISSUE TITLE
Edit workspace recommendations prompts for single folder

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37222]
Testing #37186

- start on an empty folder
- open the extensions view
- click on the edit icon in the 'workspace recommendations' section
- prompt shows up with a single option
    -> no prompt should be shown

![image](https://user-images.githubusercontent.com/6461412/32217971-cb8dfabc-be29-11e7-9872-250bf60cd06a.png)

**Comment by ramya-rao-a** [comment]
The action being used here is `Configure Recommended Extensions (Workspace Folder)` which brings up the prompt even when there is just a single folder.

@sandy081 If you agree, then I can add a check on the number of workplace folders and skip this prompt if there is only one folder

**Comment by sandy081** [comment]
Sure. But I use the workspace folder selection picker from @bpasero. Not sure if we would like to move that to the general picker?

**Comment by ramya-rao-a** [comment]
We dont need to change the picker. Just skip calling the picker when there is a single root.
See https://github.com/Microsoft/vscode/commit/46280eecb11c796ea9e3f5056c25132addf8b022
