### ISSUE TITLE
Uninstalled Extensions not suggested by code completion

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37225]
Testing #37186

- start with a new folder
- create a workspace recommendation file
- use code completion to add the java extension pack (`vscjava.vscode-java-pack`)
   -> no suggestion for it

![image](https://user-images.githubusercontent.com/6461412/32218417-1882cfa4-be2b-11e7-8be7-522b5d4533c8.png)

**Comment by ramya-rao-a** [comment]
I didn't even know we had completions there!!! :)

**Comment by sandy081** [comment]
@aeschli Currently only installed extensions are recommended. Is the java extension pack is installed ?

**Comment by aeschli** [comment]
@sandy081 No it's not. I wasn't aware that only installed extensions are suggested. Would be great to get the full list!

**Comment by ramya-rao-a** [comment]
This is do-able only if we can access the gallery from the extension that is providing the completions. If we do get access to the gallery, then we should add validations to the entered text as well.

**Comment by sandy081** [comment]
I do not think we will expose gallery service to our extensions. I am closing this as out of scope given that no body has requested for it.
