### ISSUE TITLE
Exception while staging the opened change 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37226]
Testing #37164

Steps:
- Open an inline change from the gutter
- Run the command `Git: Stage Change`

An exception is thrown. 

![kapture 2017-10-31 at 11 07 14](https://user-images.githubusercontent.com/10746682/32218711-2371dd50-be2c-11e7-9e92-57b598f4fa95.gif)

**Comment by joaomoreno** [comment]
Great catch, that command shouldn't appear in the command palette at all.
