### ISSUE TITLE
API: Code insiders source control blank

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode#37221]
- VSCode Version: 1.18.0-insider Commit 81cca6cc606eeca3443998025bff3893fcfe3ad5
- OS Version: Fedora 25

While making my svn extension multi-root aware the source control view is blank. The changes do get added to the resourceStates as I can dump them out.

The changes I have made work in VSCode Version 1.17.2 without any issues.

Steps to Reproduce:
1. Open an svn project with changes.
2. source control is blank and there is no badge count

**Comment by joaomoreno** [comment]
Can you show me the source code? In the exact version of what you are seeing?

**Comment by JohnstonCode** [comment]
Sure the source code is [here](https://github.com/JohnstonCode/svn-scm)

**Comment by joaomoreno** [comment]
Oh wait. I just realised you said this works fine in 1.17.2. But it doesn't in 1.18.0?

**Comment by joaomoreno** [comment]
Yup I can easily reproduce, I'll take a deeper look...

**Comment by JohnstonCode** [comment]
If it helps im using todays release 2ab10d50163f008ada9a4aa215de8c884857ce99 and the problem is even worse. The source control view is completly blank now.

**Comment by joaomoreno** [comment]
@jrieken NPE: https://github.com/Microsoft/vscode/commit/cadcedc9953b12e0e3ac57820e3b08a768c79967#diff-a1d58c39a5da1115d2ed23311e181142L197

**Comment by joaomoreno** [comment]
@JohnstonCode Great catch, thanks! Pushed a fix for it.

**Comment by JohnstonCode** [comment]
No Problem

**Comment by jrieken** [comment]
Nice!
