### ISSUE TITLE
ESLint library can not be found when installed via yarn and Node5

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37220]
Refs: #37142
OS: linux

Have node5 installed and follow exact instructions from #37142
Note that the error message is nowhere specifiying that we do not support node5 so the user is puzzled. We should just add a sentence to update to node 6 or 8 (where things work fine)

```
[Info  - 10:31:09 AM] ESLint server is running.
[Info  - 10:31:10 AM] 
Failed to load the ESLint library for the document /home/parallels/Development/monaco-editor/test.js

To use ESLint please install eslint by running 'yarn add eslint' in the workspace folder monaco-editor
or globally using 'yarn global add eslint'. You need to reopen the workspace after installing eslint.

Alternatively you can disable ESLint for the workspace folder monaco-editor by executing the 'Disable ESLint' command.
```

**Comment by maxibanki** [comment]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 6.1.7601
---

Same issue as @isidorn described for Windows. Output of the ESLint console:
 ```
[Info  - 11:03:14] ESLint server is running.
[Info  - 11:03:17] 
Failed to load the ESLint library for the document c:\Users\commentedOut\Desktop\test\main.js

To use ESLint please install eslint by running 'yarn add eslint' in the workspace folder test
or globally using 'yarn global add eslint'. You need to reopen the workspace after installing eslint.

Alternatively you can disable ESLint for the workspace folder test by executing the 'Disable ESLint' command.
```
I uninstalled ESLint which i installed via `npm` and double checked it with the `where` command (same as `which` on linux). Additional I restarted VS Code to be sure that the environment variables are up to date.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-eslint/issues/352
