### ISSUE TITLE
Exposing API to allow launching integrated terminal via command line [Feature-Request]

### ISSUE THREAD

**Issue by wongjiahau** [Microsoft/vscode#37224]
## What am I requesting ? 
I wanted to launch integrated terminal within VSCode by using command line, for example, it may look like the following : 
```
$ code newterm --name "my terminal"
```
Not only that, it may also allow arguments to be passed in as what command should be run after the terminal is created. For example : 
```
$ code newterm --command "npm run start"
```
## Why do I need this ? 
Because in projects, to startup the environment for building the project, I might need to launch several terminal, for example, one for TS compiler, one for test runner, one for React compiler.   

## How would I use this feature ? 
I will use them in a shell script file (*.sh) and execute it to launch the needed terminal, perhaps like the following : 
```
$ ./scripts/init.sh
```
Then after that I expect the terminal I needed will be launched within VSCode.

**Comment by Tyriar** [comment]
Someone else was running into a similar need and came up with this extension https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

To be able to control the terminal via a CLI I'm against as it becomes messy knowing which Window to target and as such may not act as people would expect and have very limited use cases. The extension API is the way to go if you want to drive this sort of behavior.

**Comment by wongjiahau** [comment]
Great extension!
