### ISSUE TITLE
Extension recommended explanation not really correct

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37227]
Testing #37186

- open an empty folder
- go to the extension view, filter for 'python'
- select the python extension
- in the header of the editor and in the tooltip it says:
'This extension is recommended based on the files you recently opened'
That's not really true, I never opened any Python files.

![image](https://user-images.githubusercontent.com/6461412/32218953-de9f8528-be2c-11e7-8b3f-fc0b790182ac.png)

**Comment by ramya-rao-a** [comment]
There wouldn't be any badge on it if you hadn't opened a python file in the past 7 days.
You sure you never opened a python file in the past week?

**Comment by aeschli** [comment]
Hmm, probably I have opened one at some point.
But note, when I explicitly search for `python`, I would be happy to know what the recommended extensions are.

**Comment by ramya-rao-a** [comment]
For now, only the ones "recommended for you" show up with the badge.
Going forward, we can have the badges for general recommendations
