### ISSUE TITLE
Decorators: decide on consistent label coloring or not

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37228]
Today we use a color for file labels in the explorer, but not in the SCM view, resulting in the same information showing up differently:

![image](https://user-images.githubusercontent.com/900690/32218916-c070aaf0-be2c-11e7-921a-7bf979a3d97c.png)

![image](https://user-images.githubusercontent.com/900690/32218917-c359c5bc-be2c-11e7-9605-dd36d0bbcb24.png)

I think out of the box I would prefer us to not color the file labels at all to keep the UI impact to a minimum and only show badges. This would mean the SCM view is not changing a lot (just the change of badges we did) and the explorer would show the badges, but no colors in the labels.

**Comment by roblourens** [comment]
Would there be a way for users to get colored labels too, even if it means having colored labels in the SCM viewlet for consistency?

What about gitignored files? They don't have a badge currently.

**Comment by jrieken** [comment]
> if it means having colored labels in the SCM viewlet for consistency?

Not sure if the SCM viewlet and the explorer are the same in that respect. The former is modified/untracked files only by definition and colors in the latter are to raise awareness of changes and to show where they are. 

> I think out of the box I would prefer us to not color the file labels at all to keep the UI impact to a minimum and only show badges.

The problem with is that you loose the ability to find changed files in collapsed folders and that it would be different from most other tools having this feature

**Comment by bpasero** [comment]
Yeah I see the issue with the bubbling up to parent folders, maybe there should be a generic indication that "some" child has a decoration.

**Comment by auchenberg** [comment]
Using Insiders for the past week, I'd +1 on just coloring the badges. The colored labels are quite distracting.

**Comment by jrieken** [comment]
We could use a circle on folders to signal that its children have decorations... 

<img width="353" alt="screen shot 2017-11-01 at 09 34 18" src="https://user-images.githubusercontent.com/1794099/32266480-dee16edc-bee7-11e7-9142-e56d03420952.png">

**Comment by bpasero** [comment]
@jrieken yeah something like that, just using the strongest color of the decoration

**Comment by bpasero** [comment]
Almost looks like tags in macOS finder then:

![image](https://user-images.githubusercontent.com/900690/32266887-7f840dda-bee9-11e7-8890-76ecf29e0c8a.png)
