### ISSUE TITLE
Adding a new workspace folder seems to collapse folders first and then expand

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37239]
Steps to Reproduce:

1. have some workspace folders expanded
2. add a new folder

=> the explorer seems to first collapse all folders and then expand folders again making the whole thing quite a ugly/flickering appearance.

**Comment by isidorn** [comment]
I can not reproduce with latest from source / insiders
Let me know if you are doing something differently and if you can still see it

![explorer](https://user-images.githubusercontent.com/1926584/33561470-0a5932b2-d913-11e7-8cf1-c4647a219145.gif)

**Comment by bpasero** [comment]
Probably fixed meanwhile.
