### ISSUE TITLE
Explorer still starts DND operation even if disabled

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37234]
Testing: #36990

Steps:
- disable DND `"explorer.enableDragAndDrop": false`
- open explorer
- start dragging a file
- drop it somewhere

Observe: nothing happens (which is somehow correct). But if DND is disable I shouldn't be able to initiate a DND operation.

**Comment by bpasero** [comment]
I am not convinced we should disable DND entirely, I think what people are mainly complaining about is accidentally moving a file or folder within the explorer but that does not mean they do not want to e.g. move a file into the editor area to open it in a specific tab location or to the side.

**Comment by bpasero** [comment]
The setting description is also clear around this: `Controls if the editor should allow to move selections via drag and drop`
