### ISSUE TITLE
Explorer decoration: show more information on hover

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37231]
I think it would be good if hovering a decoration in the explorer would tell more information around the decoration. 

Or, the decoration should add text to the general hover that is set by the file label if it is otherwise not possible to set a title attribute to the decoration. 

![image](https://user-images.githubusercontent.com/900690/32219327-1c8356de-be2e-11e7-8d11-d750ea2e9c02.png)

**Comment by jrieken** [comment]
Yeah, it should do that... It must have gone lost with some recent changes... It still works for errors/warnings

<img width="724" alt="screen shot 2017-10-31 at 11 31 27" src="https://user-images.githubusercontent.com/1794099/32219631-1f241710-be2f-11e7-829d-89447596510d.png">
