### ISSUE TITLE
Typescript error highlighting as if only compiling single file (ignoring tsconfig.json)

### ISSUE THREAD

**Issue by coreyog** [Microsoft/vscode#3723]
I recently updated typescript, angular, and basically every library in my project. Before I did this update the problem didn't exist. From the command line I've ensured that my code builds without errors or warnings. However, when I open the project in Visual Studio Code and make changes to a file it starts highlighting stuff as errors.

It highlights my imports at the top saying `cannot find module 'angular2/core'.` and my `@Components`, `@Output`s and `@Input`s say `Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.` It's also highlighting some of my `Window` properties that I have declared in a `.d.ts` file.

Yet this is my tsconfig.json:

    {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "inlineSourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "pretty": true
      },
      "exclude": [ "node_modules" ]
    }

It seems that when I change a file VSCode is building the single file I just changed without using my tsconfig. If I build from the command line I get zero errors or warnings. If I press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> to run the build inside VSCode then all the errors go away. Here's my tasks.json:

    {
    	"version": "0.1.0",
    	"command": "tsc",
    	"isShellCommand": true,
    	"showOutput": "silent",
    	"args": ["-p", "."],
    	"problemMatcher": "$tsc"
    }

VSCode 0.10.8
typescript 1.8.7
Linux Mint 17.3 x64

**Comment by egamma** [comment]
VS Code has built in version of TS which is TS 1.7.5 in VS Code 0.10.8. You have updated TS and as a consequence the TS versions now diverge and this can result in different errors.

You can tell VS Code to use another version of TS using the `tsdk` setting https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions. 

Can you please try this and see whether is the cause of your differences.

**Comment by coreyog** [comment]
This worked great. I don't appear to be getting any more erroneous errors. Thank you so much.
