### ISSUE TITLE
Explorer is broken when deleting a workspace root folder on disk

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37237]
**Steps to Reproduce:**

1. add like 5 workspace folders
2. expand all of them
3. rename the last one using windows explorer
4. reload window

=> explorer is badly broken, you will notice if you try to press the collapse all action and nothing happens

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32219680-573b28d2-be2f-11e7-8416-841e282efe16.gif)

**Comment by isidorn** [comment]
@bpasero I can not reproduce this behvaior.
I followed your exact steps, what happens for me is that after rename the file watcher crashes in console. Which I guess is expected @Tyriar 
After that the explorer works just fine, if you try to open some file from the renamed folder explorer shows an error which is expected

@bpasero what do you see in the console? Can you also repro with latest out of source and on mac?

**Comment by isidorn** [comment]
@bpasero good catch. Can you please code review and verify. Thank you

**Comment by bpasero** [comment]
@isidorn even though I can verify the issue no longer happens, that code is a bit crazy to be fair. In the happy case where all of the roots resolve in under 100ms, I think the code works fine, but what if one or many root need more than 100ms? We:
* schedule the refresh again
* `statsToExpand` was not emptied after the last scheduler finished so are we expanding things again that are already expanded?
* the `refreshSchedulerPromise` was already completed (either successfully or as error) from the last schedule run but now we trigger another schedule that will call the success or error handler of that exact same promise (which is a no-op)
* we always return the same `refreshSchedulerPromise` after scheduling the scheduler, but the result of that promise will always be from the first schedule invocation

This might not lead to issues, but I find the code very hard to understand in that current state.

**Comment by isidorn** [comment]
@bpasero you are right. All valid flaws.
Let me try to restructure
