### ISSUE TITLE
Improve handling of invalid entries in extensions.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37232]
Testing #37186 

- start on a new folder
- in the extension viewlet, show the recommended extensions, press the 'edit' button on the workspace recommendations
- add "foo.bar" as entry. Reload window
- dialog says that there are workspace recommendation.
Show the recommendations. Empty section is shown

Probably the best to show a dummy entry for the invalid entry, with an 'Unknown extensions' message.

**Comment by ramya-rao-a** [comment]
Fixed with #40270
