### ISSUE TITLE
Inline change view is not resized with window resize

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37233]
Testing #37164

Steps:

- Open an inline change view
- Resize the window -> increase its width from the right

Inline change view does not resize to fill the complete width. 

![kapture 2017-10-31 at 11 23 02](https://user-images.githubusercontent.com/10746682/32219352-334a4580-be2e-11e7-9d61-e731c1702d26.gif)

**Comment by joaomoreno** [comment]
Wow! Great catch.
