### ISSUE TITLE
Inline change view opens clicking on the lines where there are no changes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37238]
Testing #37164

In the following video, I was clicking in the gutter space at lines 329, 328, 327, 326 where there are no changes at all.

![kapture 2017-10-31 at 11 32 21](https://user-images.githubusercontent.com/10746682/32219687-5df698c8-be2f-11e7-8f74-c3c0043fbdb3.gif)

**Comment by joaomoreno** [comment]
#37256
