### ISSUE TITLE
Inline changes view has folding actions

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37249]
Testing #37164

<img width="1372" alt="screen shot 2017-10-31 at 12 11 21" src="https://user-images.githubusercontent.com/10746682/32221168-c9c8d034-be34-11e7-8ae9-9a8198200734.png">

**Comment by joaomoreno** [comment]
cc @aeschli

**Comment by aeschli** [comment]
The inline diff editor seems to not show the folding gutter annotations. IMO that should happen here too.

**Comment by joaomoreno** [comment]
@aeschli And how is that achieved?

**Comment by aeschli** [comment]
@alexandrudima Can you you help?

**Comment by aeschli** [comment]
The problem was that the folding decorations were created on the model, not on the editor.
So the folding icons show up also in editors that have folding turned off.
