### ISSUE TITLE
Panel: opening side by side editors does not push panel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37245]
Testing: https://github.com/Microsoft/vscode/issues/36906

Steps to Reproduce:

1. have 1 editor open in its minimal width
2. hide sidebar
3. make the panel visible vertically all the way
4. bring up a second and third editor

=> the editors go below their minimal width
=> would expect the editors to push the panel

![image](https://user-images.githubusercontent.com/900690/32220948-deec816e-be33-11e7-983f-3ad9485690b5.png)

**Comment by bpasero** [comment]
I think I can still reproduce in this case:

![panel-red2](https://user-images.githubusercontent.com/900690/32287788-29ff94ee-bf32-11e7-8862-3f30339ecc49.gif)

Also it seems like when I go from 2 to 3 editors that is a slight delay before the editors expand to the minimal size.

**Comment by bpasero** [comment]
@isidorn yeah seems to work now. that delay before the space is taken from sidebar and panel is that explainable? I always see the editor opening first and only afterwards taking the correct space. Feels a bit sluggish.

**Comment by isidorn** [comment]
@bpasero I guess that is just how the code is written. Namely the layout is listening on the change of editors and layouts if it overflows. Which is what happens in this case, one more editor gets rendered, layout gets the editor change event, sees the overflow and does the layout
