### ISSUE TITLE
Adding workspace folders only expands first in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37240]
Steps to Reproduce:

1. open empty window
2. save as workspace
3. click on "Add Folder"
4. pick 2 folders

=> only first is expanded

**Comment by AndyBay** [comment]
Another slight annoyance is if you:
1. Have three root folders in your workspace.
2. Minimize the top two root folders.
3. Expand the bottom root folder.
4. Reload the window.

Now upon reload both the top and bottom root folder is expanded, and I have to re-minimize the top root folder.

**Comment by isidorn** [comment]
I acknowledge both issues and am looking into a fix

**Comment by isidorn** [comment]
I have fixed both of these issues with one downside:
Now it is not possible to keep all your roots collapsed. If you do that I will expand all your roots when you start vscode again. However there is a colapse all action and not sure if this is an actual user sceanrio so not doing anything here until somebody complains

**Comment by bpasero** [comment]
Bold move...
