### ISSUE TITLE
[folding] Clicking on the gutter area folds even if there is no folding indicator

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37246]
Testing #37164

Check the following video, I am clicking on the gutter in the open area next to inline changes. This highlights the inline diff and there is no folding action. Clicking on it does the folding.

<img width="198" alt="screen shot 2017-10-31 at 12 04 38" src="https://user-images.githubusercontent.com/10746682/32220942-db1deb04-be33-11e7-9ab9-95a6dc8b0197.png">

![kapture 2017-10-31 at 12 04 27](https://user-images.githubusercontent.com/10746682/32220945-dceaefae-be33-11e7-997f-1087337178da.gif)

### To reproduce

![image](https://user-images.githubusercontent.com/10746682/32220975-ff7ddc0c-be33-11e7-8755-10bae7037949.png)

**Comment by aeschli** [comment]
@sandy081 Do you have the file/snippet to reproduce?

**Comment by aeschli** [comment]
@sandy081 got it, thanks!

**Comment by aeschli** [comment]
@joaomoreno The dirty decorators have a similar issue: I created #37287

**Comment by joaomoreno** [comment]
@aeschli What was your fix?

**Comment by aeschli** [comment]
@joaomoreno My bug was in the folding code. I didn't validate that the click is on the first line of the folding region.
