### ISSUE TITLE
Panel: dropdown should not push other actions out of view

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37242]
Testing: https://github.com/Microsoft/vscode/issues/36906

Steps to Reproduce:

1. have the panel to the right and open output
2. if you make the panel small enough, the "X" action is pushed out of view even though imho the dropdown could become smaller.

![image](https://user-images.githubusercontent.com/900690/32220541-66e8a20c-be32-11e7-94fa-3a1aee70a9bd.png)

**Comment by isidorn** [comment]
We are using flex underneath and it is not trivial to get this behavior right.
In the current stable we also have this for the horizontal panel.

I do not think this is a big issue, pushing to backlog until more users complain.
Of course I am open to suggestions on how to use flex to overcome this issue.

**Comment by bpasero** [comment]
I think the issue here is just the `min-width` of 110px for the select component. There must be a way to use flex and let it shrink to a certain minimum and grow to a maximum like 110px.

**Comment by isidorn** [comment]
Yes that is the issue. But on top of that that whole action bar is being pushed, he is not the one pushing which complicates a bit.

**Comment by cleidigh** [comment]
@bpasero 
@isidorn 
I am assuming this is the same issue in the other direction of the select drop-down been pushed over
and partially should with a small panel.  This makes a contextview dropDown overlap the sash sometimes.

**Comment by isidorn** [comment]
There are still some corner cases where this can happen, however I think it behaves much better overall now

**Comment by bpasero** [comment]
@isidorn isn't it still the same?

![image](https://user-images.githubusercontent.com/900690/33614581-0247fd86-d9d8-11e7-9c46-b3377f77b348.png)

**Comment by isidorn** [comment]
@bpasero it is better than before but yes it can still happen

**Comment by bpasero** [comment]
Yeah much better than before, less hectic. Fine for me.
