### ISSUE TITLE
Workbench explodes when renaming folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37243]
I encounter this while testing #37155 and while the shared process deleted the folder (old extension) I was working in before. Steps to reproduce

* open a folder, but no editor, just show the files in the explorer
* rename that folder using explorer/finder
* select F1 > Reload Window
* 💥 you see an empty window

<img width="2027" alt="screen shot 2017-10-31 at 12 00 15" src="https://user-images.githubusercontent.com/1794099/32220717-1738caa6-be33-11e7-9aad-8b945b5b9c12.png">

```
index.js:5 TypeError: Cannot read property 'configuration' of undefined
    at t.getWorkbenchState (workbench.main.js:10)
    at workbench.main.js:10
    at Object.g [as _notify] (workbench.main.js:9)
    at Object.enter (workbench.main.js:9)
    at n.Class.derive._oncancel._run (workbench.main.js:9)
    at n.Class.derive._oncancel._error (workbench.main.js:9)
    at workbench.main.js:9
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules/graceful-fs/pol…:284
    at FSReqWrap.oncomplete (original-fs.js:114)
onError @ index.js:5
index.js:5 [uncaught exception]: Error: ENOENT: no such file or directory, access '/Users/jrieken/Code/_samples/deleteme'

Error: ENOENT: no such file or directory, access '/Users/jrieken/Code/_samples/deleteme'
onError @ index.js:5
index.js:5 Error: ENOENT: no such file or directory, access '/Users/jrieken/Code/_samples/deleteme'

Error: ENOENT: no such file or directory, access '/Users/jrieken/Code/_samples/deleteme'
    at workbench.main.js:9
```

**Comment by bpasero** [comment]
I do believe that behaviour has been like that since the beginning of having a reload action. Not sure how important that is for fixing for October, but if there is a simple fix we can check it out. Best we can do is open an empty workspace after reloading window.

**Comment by bpasero** [comment]
I see the issue...

**Comment by weinand** [comment]
After "reload window" VS Code is now in non-folder mode (which seems to be the correct solution).
