### ISSUE TITLE
More dynamic adaption of window size

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37257]
Testing: #36906

If you have side bar, editors and panel visible and you start making the window small there is some ugly component overlays showing up (even above the activity bar). I think we had this issue before but I feel now it got worse.

Maybe one idea would be to collapse the sidebar and panel once the space for the opened editors becomes too small. That way we would always ensure that the space for editors is maximum.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32221790-20e841ae-be37-11e7-9b47-c1679302e68c.gif)

**Comment by isidorn** [comment]
This should be fixed with e80ca48292
![layout](https://user-images.githubusercontent.com/1926584/32232464-656f0788-be58-11e7-868e-031013a25288.gif)

**Comment by bpasero** [comment]
@isidorn awesome dude 👍
