### ISSUE TITLE
Diff shown when clicking on whitespace

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#37256]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:47:36.947Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Open a file that is SCM managed in the editor
2. Make a change -> change is shown on the left between line numbers and folding controls
3. Move mouse several lines below change indiction (you can even make the change scroll out of the view port) but in the same horizontal position
4. Click -> diff of the change made in step 2 are shown as peak diff. If you scrolled the change indication out of the view port the editor scrolls back.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@alexandrudima I believe you already have an issue for this? Clicking on space after the last line behaves as if the user's clicking on the last line.

**Comment by joaomoreno** [comment]
@alexandrudima Never mind, I thought this was about clicking after the last line. It's actually on lines which do not have any change decorations.
