### ISSUE TITLE
Cursor is lost while typing in Inline changes view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37253]
Testing #37164

Steps to reproduce

- Open an inline change
- Start typing in the inline view where you have the changes

Inline view refreshes and cursor is lost

![kapture 2017-10-31 at 12 19 51](https://user-images.githubusercontent.com/10746682/32221463-ea1a0b4a-be35-11e7-87ed-2fd838932c4b.gif)

**Comment by joaomoreno** [comment]
@sandy081 Should we make it readonly?

**Comment by joaomoreno** [comment]
Made it readonly.

**Comment by sandy081** [comment]
@joaomoreno Good that it is made readonly. But, I do not have any clue why I am not able to edit. I think we are missing UX here.
