### ISSUE TITLE
Panel: weird artifact moving the panel to the right

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37250]
Testing: #36906

Steps to reproduce:
1. only have the panel visible
2. move it all the way to the left
3. suddenly the background of the sidebar shows up with no contents?

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32221302-499b4652-be35-11e7-8fab-9274c516a02c.gif)

**Comment by isidorn** [comment]
I can not reproduce this with all the fixes.
Probably a dup of #37248

Let me know if you can still repro and I can reopen
