### ISSUE TITLE
TS auto import should support configuring whether a star or a qualified import is used.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37258]
Testing: #37177

- vscode source code opened in VS Code
- open a file that doesn't import `'vs/base/common/types'`
- type isStringArray
- select the entry from code complete list
- the following import is inserted:

```ts
import { isStringArray } from 'vs/base/common/types';
```

However what I want in this case is

```ts
import * as Types from 'vs/base/common/types';
```

and the code should become `Types.isStringArray`

Would be cool if I can control this via a setting.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19630
