### ISSUE TITLE
Default keybinding alt+shift+f to navigate to next change is already used by Format document command

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37260]
Testing #37164

Steps:

- Have some changes in the file
- Open an inline change view
- Navigate to next change using <kbd>shift</kbd><kbd>alt</kbd><kbd>F</kbd>

Expected to go to next change, but not.
It is because this keybinding is consumed by `Format Document` feature. 
Since these are out of the box keybindings, we would need a different keybinding.

**Comment by joaomoreno** [comment]
@sandy081 Any suggestion?

**Comment by joaomoreno** [comment]
Using <kbd>Alt F3<kbd> and <kbd>Shift Alt F3</kbd>.
