### ISSUE TITLE
Panel: possible to move activity bar out of view

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37261]
Testing: #36906 

1. have sidebar right
2. show just panel
3. size panel larger

=> you can move the activity bar out

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32222024-f7b6d13c-be37-11e7-873c-0809927032bd.gif)

**Comment by isidorn** [comment]
Can not repro with all the fixes. Can you please try to repro tomorrow?
Closing as dup

**Comment by bpasero** [comment]
Yeah, adding bug and removing duplicate so that I see it in my inbox to verify.
