### ISSUE TITLE
Extension cleanup code should also use UUID for identification

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37264]
1. Install an extension from the Marketplace
2. Close Code
2. Rename its folder from `pub.name-version` to `something`
3. Update the version in `package.json` to an older version
3. Launch Code, you will get an update
4. Relaunch Code

`something` should be deleted

**Comment by sandy081** [comment]
Fixed by 67e8f7813460d7dee6e5788d6fc48d509fb61aac

**Comment by joaomoreno** [comment]
@sandy081 I can still repro this.

**Comment by joaomoreno** [comment]
Seems fixed now!
