### ISSUE TITLE
unintuitive name "explorer.confirmDragAndDrop" for "move" operation

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37265]
When testing #36990 I disabled the configuration dialog on "move" from within the dialog.

Later I tried to reset this setting to the previous behaviour and I searched for "move" in the settings editor. This doesn't result in anything useful.

After some searching I found the "explorer.confirmDragAndDrop" settings.

IMO "explorer.confirmDragAndDrop" is not an intuitive name for a setting that the user associates with a "move" operation.

Could we add the word "move" to the settings description, so that users like me are able to find it?

**Comment by bpasero** [comment]
I added a description where "move" appears: ![image](https://user-images.githubusercontent.com/900690/32265772-b98e0314-bee4-11e7-9eee-b4793035d065.png)

**Comment by weinand** [comment]
@bpasero the actual comment for `explorer.confirmDragAndDrop`  in 2ab10d50163f008ada9a4aa215de8c884857ce99 says:
> // Controls if the explorer should ask for confirmation when moving files or folders **around** via drag and drop.

I suggest to remove the word "around" since it is not needed.
