### ISSUE TITLE
Panel: not possible to make panel larger if editors occupy space

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37266]
Testing: #36906

1. have side bar left, editors center and panel to the right
2. make the panel larger
=> you cannot make it larger even tough the sidebar still has size to give
=> works fine the other way around if you make the sidebar larger

I think I would expect the growing panel to steal width from the side bar if possible.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/32222643-6056d866-be3a-11e7-992a-3e5d579049b0.gif)

**Comment by bpasero** [comment]
@isidorn works nicely. Should the "Maximize Panel" action also steal space away from the sidebar in this case to truly become maximized as much as possible?

**Comment by isidorn** [comment]
@bpasero probably. Can you please file a feature request for November in case it does not maximize fully.

**Comment by bpasero** [comment]
via https://github.com/Microsoft/vscode/issues/37493
