### ISSUE TITLE
Restore Panel Size freezes for 5s

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#37267]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

---

Steps to Reproduce:

1. Have a task:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "dir",
			"command": "ls -la",
			"windows": {
				"command": "dir"
			}
		}
	]
}
```
2. Run task twice
3. Click "Maximize Panel Size"
4. Click "Restore Panel Size"

Observe: VS Code freezes for ~5seconds:

![image](https://user-images.githubusercontent.com/5047891/32222725-b6107424-be3a-11e7-8db2-6fe7181081da.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@alexandrudima this might be https://github.com/Microsoft/vscode/issues/36913

**Comment by alexandrudima** [comment]
@Tyriar this does not appear to happen every time for me, e.g. when running the commands. I noticed it specifically in this resize case, but I will keep an eye open...

**Comment by Tyriar** [comment]
@alexandrudima you still seeing this?

**Comment by alexandrudima** [comment]
No, I don't see this anymore.
