### ISSUE TITLE
Debt: extension loading code should be shared between all processes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37269]

**Comment by alexandrudima** [comment]
Also, the shared process should not do a readdir.

**Comment by joaomoreno** [comment]
We created this issue because there is an inconsistency when reading extensions from disk between several code places.

The extension runtime code, which finds the extensions to load them, doesn't respect matching extension's gallery uuids in order to determine equality between extensions. It should do that, given the work @sandy081 has done this month to support extension renaming.

This is independently of `reddir` calls, since for loading extensions we just need one `readdir` call and `read` all `package.json` files. So we should make sure that stays that way: minimal on the FS.

**Comment by alexandrudima** [comment]
I can help with advice, but I did not introduce the duplication => unassigning myself for now.
