### ISSUE TITLE
Consider not having a singleton debugConsole

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37279]
re #37167

Would it make sense to have the console on the `DebugSession`-type? It would still print to the (implementation-singleton) console but will allow us to have multiple consoles in the future (when multiple debug sessions are active). Something like this

```ts

export interface DebugSession {
  //...

  console: DebugConsole
}

```

**Comment by weinand** [comment]
Yep, I thought the same when starting to work on this API.

But then I noticed that the lifecycle of a DebugSession is the same as that of a debug adapter
which makes it impossible to output to the debug console **before** the debug adapter has started (and that is actually the main use case).

**Comment by weinand** [comment]
I do not see an alternative to introducing the debug console singleton.

**Comment by jrieken** [comment]
It is dangerous tho

**Comment by weinand** [comment]
Would it be better to use an `activeDebugConsole` instead?

**Comment by jrieken** [comment]
Maybe... It at least signals that there can be (in the future) many and that they can change... If you ever want to support showing multiple debug consoles (which I think isn't a crazy request given that I can launch many debuggers at once) in parallel then the API shouldn't be in your way

**Comment by weinand** [comment]
Renamed `vscode.debug.console` to `vscode.debug.activeDebugConsole`
