### ISSUE TITLE
Terminal not scrolling to the bottom when executing code

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#37275]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:19:39.344Z)
- OS Version: Windows_NT x64 6.2.9200
- Extensions: PowerShell|ms-|1.5.0

Steps to Reproduce:

1. Execute code that has terminal output (PowerShell code)
2. Scroll up to see the first line of output
3. Execute the code again and notice that the terminal is not scrolled down to the bottom to see the result of the latest code run

This issue has been reported in [#18362](https://github.com/Microsoft/vscode/issues/18362) and in [#17325](https://github.com/Microsoft/vscode/issues/17325). But I don't think it's fixed or possible to set this behavior without resorting to [macro extensions](https://stackoverflow.com/questions/45175883/jump-to-bottom-of-integrated-terminal-when-running-powershell).

**Comment by Tyriar** [comment]
It looks like you would be executing the code via the powershell extension so please create the issue over there https://github.com/PowerShell/vscode-powershell
