### ISSUE TITLE
search for \n with regex on gives no result

### ISSUE THREAD

**Issue by safareli** [Microsoft/vscode#37277]
- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: macOs 10.13

Steps to Reproduce:

<img width="422" alt="screenshot 2017-10-31 14 27 43" src="https://user-images.githubusercontent.com/1932383/32226029-afd55428-be47-11e7-9020-de53a10ce08a.png">

**Comment by roblourens** [comment]
The search viewlet doesn't support multiline search, so this is expected. `$` will match EOL
