### ISSUE TITLE
Missing redraw after Fold All

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#37271]
While testing #37173.

- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:47:36.947Z)
- OS Version: Darwin x64 16.7.0

Steps to Reproduce:

1. Open a large file (I used a js file with 67000 lines).
2. Put the caret in the last line of the editor.
3. "Fold All" through the command palette
-> Editor area including gutters will turn completely white. Redraw happens on scrolling.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
I wasn't able to reproduce, neither on OSX nor on Ubuntu (JSON file with 130'000 lines).
Can you point me to the file you used?

**Comment by aeschli** [comment]
@kieferrm do you have more information?

**Comment by kieferrm** [comment]
1) Open a vs code workspace
2) Replace `src/vs/workbench/browser/editor.ts` with [this version: editor.ts.zip](https://github.com/Microsoft/vscode/files/1461033/editor.ts.zip)
3) Open the editor
4) Place caret on last line
5) <kbd>Cmd+K</kbd><kbd>Cmd+1</kbd>
-> empty screen

![utcvpgo2hd](https://user-images.githubusercontent.com/4674940/32655320-5fe29728-c60d-11e7-89c1-447f87014d0d.gif)

**Comment by aeschli** [comment]
I still can't reproduce, but this looks like a rendering issue.

**Comment by alexandrudima** [comment]
I could not reproduce on Windows, not on stable or on insiders, so it might be mac specific:

I've also tried with `"editor.scrollBeyondLastLine": false` (it appears that is a setting you have from the gif):

![37271](https://user-images.githubusercontent.com/5047891/32669720-d1868e5a-c641-11e7-8c1a-c9cbb31dd8e7.gif)

**Comment by alexandrudima** [comment]
Reproduces with:
```
    "editor.scrollBeyondLastLine": false,
    "typescript.referencesCodeLens.enabled": true
```
