### ISSUE TITLE
There is an error that can not be encoded when creating a server using a flask in python

### ISSUE THREAD

**Issue by admin15290552375** [Microsoft/vscode#37274]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 
An error occurred when creating a server with a cylinder in python: UnicodeDecodeError: 'utf-8' codec can not decode byte 0xbd in position 0: invalid start byte
Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-intelephense-client|bme|0.7.2
python|don|0.7.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
phpcs|ika|0.7.0
cpptools|ms-|0.14.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please file this issue against https://github.com/DonJayamanne/pythonVSCode
