### ISSUE TITLE
Vs code git bash terminal always forgets it's history after re-open

### ISSUE THREAD

**Issue by joelharkes** [Microsoft/vscode#37273]
- VSCode Version: latest 64bit
- OS Version: win 10

Steps to Reproduce:

1. Use git bash as terminal
2. Open git bash and type `ls`
3. open vs code, type some other command  (in the integrated terminal)
4. close vs code and open again
5. do arrow/cursor up. (in the integrated terminal)

The command shown is `ls` (history from git bash instead of git bash from vs code session).

I Expect either:
* History to be remembered globally
* Or history of the commands to be remembered per project/path.

**Comment by Tyriar** [comment]
All the history is managed by the shell, in this case git bash. If you launch a single shell and exit it, the history will likely be retained. However it can be less reliable when there are multiple shells of the same type, but this happens regardless of the terminal as far as I'm aware.

**Comment by joelharkes** [comment]
How come it is only retained when I open git bash directly and is never retainer in vs code?

I'll do some more testing but s far I have never seen vs code => git bash retain anything. although opened manually it always seems to retain history

**Comment by Tyriar** [comment]
@joelharkes it's possible there's an issue on our side but it seems unlikely as we're just launching the git bash executable and that's accepting input and telling us the output. Since the git bash executable is the thing handling the input, it should be persisting the history somehow.

**Comment by joelharkes** [comment]
Seems to depend on how you close the bash: 
https://stackoverflow.com/questions/10488498/bash-history-does-not-update-in-git-for-windows-git-bash

It also seems my projects keep running when i close vs-code (and i started the project running `yarn start`)

it seems vs-code does not close integrated terminals properly?

**Comment by joelharkes** [comment]
A solution would be to either properly close git-bash on vs code close.

or enable the use of executing commands (through settings) when integrated shell closes.

the command that would be needed to execute is: `history -a`
