### ISSUE TITLE
TypeScript - check when the globally installed typescript version differs from the VS Code one

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3727]
I see several issues like #3723, the root cause is that a user run tsc on the command line and gets different errors on .ts files inside Code.

We should add a check whether the installed typescript version matches the one used by Code in the Workspace and warn the user.

**Comment by scharf** [comment]
I just ran into this problem (because I use the new [string literal types](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types) in TypeScript 1.8) .

I wonder why Code is not using the typescript compiler in` $PATH` or at least have an option to use the version in `$PATH`?

Is there a way to find out which version is actually used?

**Comment by egamma** [comment]
@scharf 

>Is there a way to find out which version is actually used?

You can hover over the version number in the bottom right corner:
![image](https://cloud.githubusercontent.com/assets/172399/13553426/411adeda-e389-11e5-8c57-66a33247ccbd.png)

**Comment by egamma** [comment]
@scharf 

>I wonder why Code is not using the typescript compiler in $PATH  or at least have an option to use the version in  $PATH ?

Code ships with a version of TS that we test that it works. The version on the $PATH can be a different one and therefore you have to enable it using the `tsdk` setting.

**Comment by scharf** [comment]
@egamma 

It does not show the version number for me:

![status](https://cloud.githubusercontent.com/assets/3731059/13554069/76268fb0-e39e-11e5-99c3-3e6fa7bc4ce4.jpg)


> you have to enable it using the tsdk setting

that's fine (see also #3748). Often projects are set up in a way that all required tools paths are in `$PATH` . Specifying the absolute (system dependent) path of a tool is not a good idea in a shared workspace settings file. I think it would be good for consistency that command line tools and the IDE use the same version of tools. And one common strategy is '$PATH`.

**Comment by egamma** [comment]
>It does not show the version number for me:

sorry, I've overlooked that this is in our development version, but it will be in Stable early this week.

**Comment by stefanaerts** [comment]
I did all of it, i put the path in settings.json and the path was used, still the decorator error.
The only thing that works is to put a jsconfig.json file or a tsconfig.json file,both work.
But only when i use as module commonjs. If i change the module to system for example i still get the error in vscode. Using the path(absolute or relative) in settings.json doesnt help.

layout of jsconfig.json or tsconfig.json that works ->
"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
	},

**Comment by katopz** [comment]
VSCode 1.4 tsdk didn't seem to work for me tho.

![ts-vs](https://cloud.githubusercontent.com/assets/97060/17688130/602fc040-63a6-11e6-8943-14f35874d432.png)

Still got `v1.0.3.0` there.
And surprisingly in my `$PATH` didn't contain any `tsc` related.

Any hint?

**Comment by jtsom** [comment]
FWIW - I'm running into the "error TS1219: Experimental support for decorators is a feature that is subject to change in a future release." issue when editing a new Angular-cli application. Without changing the Typescript compiler path, I can get the error to go away by making some changes to the tsconfig.json file (though it causes the Angular app to not build)

My typescript is the current release version:
```
bash-3.2$ tsc --version                                                                                      
Version 1.8.10
```

The original tsconfig.json file in a new Angular Cli app is:
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
     "typeRoots": [
      "../node_modules/@types"
     ],
     "types": [
       "jasmine"
     ]
  }
}
```

If I make these changes, the error goes away:
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    //"lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5"
    // "typeRoots": [
    //   "../node_modules/@types"
    // ],
    // "types": [
    //   "jasmine"
    // ]
  }
}
```

I have another Angular 2 app (not CLI generated) that has the below tsconfig.json file that doesn't have any issues:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "dist"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by RyanMcGee** [comment]
@jtsom - I had the same problem. I resolved it by adding this line to my .vscode\settings.json file

`"typescript.tsdk": ".\\node_modules\\typescript\\lib"`

I was using the Angular 2 Universal Starter which installs Typescript@2 into the node_modules. I don't have a global install of TypeScript, so I'm not entirely sure which version VS Code was trying to use, but it didn't match the version the starter expected.

**Comment by jtsom** [comment]
Yeah that's what I ended up having to do also to quiet the error.

**Comment by dbaeumer** [comment]
this got implemented a while ago.
