### ISSUE TITLE
Linux: VS Code doesn't pick up file/folder moves outside of VS Code

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#37270]
testing #36990 

- have VS Code open on a project with some files and folders
- in the Ubuntu file explorer move files/folders within the project

Observe: VS Code doesn't pick up any of those changes which results in subsequent errors like this:
![2017-10-31_13-02-29](https://user-images.githubusercontent.com/1898161/32222999-d9b310ac-be3b-11e7-9508-287f1093929e.png)

A "Reload Windows" fixes that.

The "reverse" works just fine, so the Ubuntu file explorer picks up all changes made in VS Code immediately.

**Comment by bpasero** [comment]
@weinand do you see the same when you set `"files.useExperimentalFileWatcher": false` ?

**Comment by weinand** [comment]
@bpasero setting `"files.useExperimentalFileWatcher"` to false fixes the problems for me.

**Comment by bpasero** [comment]
@egamma @Tyriar this is another regression from NSFW. I suggest to revert my change to enable `files.useExperimentalFileWatcher` by default, I am not brave enough to take all the new issues from all our users in stable that are not using multi-root. We should reserve time in November to address the file watcher issues or find another solution for file watching.

**Comment by bpasero** [comment]
@Tyriar actually it looks like I am receiving file events if I run with `--verbose` but the explorer is not updating:

![image](https://user-images.githubusercontent.com/900690/32239825-f57ae74e-be6b-11e7-93f4-869126cf3bf7.png)

Should the rename case not result in a delete and add event?

**Comment by bpasero** [comment]
Filed to NSFW as https://github.com/Axosoft/nsfw/issues/42, it looks like we are not getting enough information from the event to figure out the move properly.

**Comment by Tyriar** [comment]
@bpasero I'm also for reverting the change to minimize risk. I won't have time to invest in the file watcher for at least 2 months as I'll be out for several weeks and then focusing on accessibility.

**Comment by implausible** [comment]
Try https://www.npmjs.com/package/nsfw/v/1.2.0

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/76434
