### ISSUE TITLE
Auto imports: not working well when names clash

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37283]
Testing: #37177

1. have 2 different files each exporting a function `foo`
2. use IntelliSense to use the function in another file

=> only one import is added
=> I would expect to be asked which one to pick

**Comment by chrmarti** [comment]
Same here, IntelliSense only offers one of the two possible completions.

- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T06:24:27.011Z)
- OS Version: Linux x64 3.13.0-108-generic

**Comment by mjbvz** [comment]
Support for this was only added in the real TS 2.6.1 release which I picked up today. Please test this in the next insiders build  (make sure you have TS 2.6.1 enabled in the workspace too) and report any issues you see

**Comment by chrmarti** [comment]
Works for me in the latest insiders. Two notes:
- The path could be shorted to only start at the root folder's name.
- Selecting a completion with the mouse does not add the import, it's not clear why that would behave differently and if the completion provider has anything to do with it.

![image](https://user-images.githubusercontent.com/9205389/32298780-71734d1a-bf10-11e7-8061-bf1c965c9afd.png)

**Comment by mjbvz** [comment]
Full path issue has been fixed. Will open a separate issue for the mouse selection scenario
