### ISSUE TITLE
Auto imports does not work for extensions

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37282]
Testing: https://github.com/Microsoft/vscode/issues/37177

1. create a hello world JS extension
2. open extension.js
3. start to type `RelativePattern`
4. complete it

=> no import is added

Imho if there is no import action after accepting a proposal, we should also not show it in the IntelliSense window.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19629
