### ISSUE TITLE
Intellisense not working after update

### ISSUE THREAD

**Issue by bobysf12** [Microsoft/vscode#37285]
![image](https://user-images.githubusercontent.com/17921631/32226846-3fdf4d88-be7c-11e7-88dd-61332375886d.png)

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please test this in VS Code insiders to see if the problem still exists

If you still see this problem in insiders, please share a small sample project or some code that causes this issue

**Comment by bobysf12** [comment]
@mjbvz Thanks for your answer. The VS Code insiders works fine. But what should I do with my current VS Code? Because I've uninstalled and reinstalled it many times and the Intellisense only work once and then it's gone.

**Comment by mjbvz** [comment]
It sounds like there may be a bug in VS Code 1.17. When we release VS Code 1.18 sometime next week, please download that and let me know if you still see this issue.

**Comment by github-ganesh** [comment]
I am also facing same issue in version 1.18.1 - any update for this issues ?
