### ISSUE TITLE
diff peek view opens when clicking on empty gutter area

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37287]
- have a folder that is under git
- make a change to a line: the git dirty annotation shows up in the gutter
- click on an empty gutter area
- peek view opens for a previous change

![dirtydecorators](https://user-images.githubusercontent.com/6461412/32227133-ba6c0528-be4a-11e7-9362-c27b52815482.gif)

**Comment by joaomoreno** [comment]
@kieferrm Got there first: https://github.com/Microsoft/vscode/issues/37256
