### ISSUE TITLE
Auto imports: not suggested if local type exists

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37284]
Testing: #37177

Steps to Reproduce:

1. define a method `bar` in one file
2. try to use that method in another file where a local member `bar` is already defined

=> not suggested
=> would be nice if the type was imported and automatically aliased with a different name because of the name clash

**Comment by mjbvz** [comment]
Yes I think the current behavior is by design but this would be a nice enhancement. We would also need to ensure that the local variable is always first in the sort order in this case

**Comment by mjbvz** [comment]
Moved upstream to https://github.com/Microsoft/TypeScript/issues/20061
