### ISSUE TITLE
Strange translation of extract quick fix in TS

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37292]
Testing #37182 

<img width="470" alt="capture" src="https://user-images.githubusercontent.com/1931590/32227295-480c35b0-be4b-11e7-8ebc-402e0b03a329.png">

Very hard to understand. Better would be:

- Als lokale function von 'foo' extrahieren
- Als globale function im module extrahieren

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19610
