### ISSUE TITLE
workbench.confirmChangesToWorkspaceFromExtensions  should not be a setting

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#37298]
Testing #37133

IMHO we should store the answer to these types of "Never ask me again", "always", etc. questions in another type of storage than in the settings.

**Comment by bpasero** [comment]
@alexandrudima the reason I decide to store it in settings is so that the user has a way to unset this again. How would a user otherwise get back to the state where the checkbox is not checked if the dialog is never showing up again?

**Comment by alexandrudima** [comment]
Ugh, this is a nasty problem indeed.
