### ISSUE TITLE
Syntax highlighting failing for TypeScript template strings

### ISSUE THREAD

**Issue by penguin020** [Microsoft/vscode#3729]
Looks like the string "var" is getting misinterpreted when it starts another identifier...

![image](https://cloud.githubusercontent.com/assets/545424/13533892/8b81c19e-e200-11e5-87b0-47b17c9085b2.png)

I am using...

![image](https://cloud.githubusercontent.com/assets/545424/13533927/ae32a974-e200-11e5-8a2b-27687b830743.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2712
