### ISSUE TITLE
search.useIgnoreFilesByDefault should be a resource setting

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#37291]
Testing #37179

I would have expected that the setting "search.useIgnoreFilesByDefault" is a [resource and not a window setting](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#settings).

![image](https://user-images.githubusercontent.com/172399/32227264-2f517058-be4b-11e7-91d5-5b404c409ab6.png)

**Comment by chrmarti** [comment]
@roblourens I wonder if we should have a new resource setting `search.useIgnoreFiles` that is only used by file search for now and text search can then migrate to. It would be a little confusing while having both, but we would then end up with just one that is properly named (once you merge the two exclude buttons).

**Comment by roblourens** [comment]
This applies to the button in the search viewlet, and there is only one per window.

@chrmarti that's basically my thinking

**Comment by chrmarti** [comment]
@roblourens When (if?) you merge the two exclude buttons (Use Ignore Files and Use Exclude Settings) into one (Use Exclude Settings?), you could use `search.useIgnoreFiles` per workspace folder and the button would just be a big switch to turn all exclusions off (settings and ignore files).
