### ISSUE TITLE
Terminal does not warp lines dynamically

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37294]
Refs: #37149
OS: Ubuntu

I found this while following the test plan item, though you are probably aware of this limitation.
1. Open terminal, do a `ls`
2. Resize the window by decreasing size -> temrinal does not wrap lines on resize
3. If I do a `ls` once the window is smaller all lines get nicely wrapped

I would expect that terminal nicely wraps lines once I reduce the size of the window.
Sorry if duplicate

FYI @dbaeumer

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
