### ISSUE TITLE
The git indicators on the gutter shows improperly when the file is not encoding with UTF-8

### ISSUE THREAD

**Issue by JasonJunMa** [Microsoft/vscode#37309]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:47:36.947Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

I use autoGuessEncoding in my settings. 
When I open a file which is not encoding with UTF-8, the editor will convert it to the proper encoding. But the git indicators will show on every line which contains non-English characters.
<img width="157" alt="screen shot 2017-10-31 at 11 35 12 am" src="https://user-images.githubusercontent.com/15619964/32232983-b21a043a-be2f-11e7-9dd1-4eb3cc41dcc6.png">
<img width="150" alt="screen shot 2017-10-31 at 11 35 28 am" src="https://user-images.githubusercontent.com/15619964/32232993-b7e33d82-be2f-11e7-8ae8-6647266cf09f.png">
As you can see in the picture. I didn't change anything there, but there is still a blue vertical line shows on the gutter. That is really confused me. 
Can anyone help me with that? Thanks!

**Comment by alexandrudima** [comment]
The git created model is not using the same encoding as the file created model

**Comment by joaomoreno** [comment]
#21146
