### ISSUE TITLE
If I select text and cmd/ctrl + c more than once, it deselects all the previously selected text and copies only 1 character

### ISSUE THREAD

**Issue by morriswchris** [Microsoft/vscode#37308]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-gist|dba|1.0.0
file-icons|fil|1.0.5
color-highlight|nau|2.3.0
vscode-icons|rob|7.17.0
Align|ste|0.2.0
vim|vsc|0.10.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. cmd/ctrl + a to select file of text
2. cmd/ctrl + c multiple times
3. cmd/ctrl + v will produce only the character where the cursor last was

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
After your first Cmd+C the selection is cleared. Don't know if this behavior can be toggled via a setting.

**Comment by alexandrudima** [comment]
@morriswchris I cannot reproduce this on a default installation of VSCode. Does this reproduce for you when disabling extensions that take over input like e.g. `vim` ?

**Comment by morriswchris** [comment]
@alexandrudima you are correct *facepalm*. I should have tried disabling `vim` first.

**Comment by octref** [comment]
Well actually I use Vim too so it repros for me. I guess you can file an issue on VSCodeVim to treat <kbd>y</kbd> and <kbd>cmd</kbd>+<kbd>c</kbd> differently.

**Comment by morriswchris** [comment]
VSCodeVim has actual filed an issue with VSCode (#217) to address this as well. As a work around then mention setting `"vim.overrideCopy"` to `false`, which has seemed to solve the issue for me
