### ISSUE TITLE
After updating the version released today, my computer to run a serious fever,cause the computer to stall.

### ISSUE THREAD

**Issue by YuJinLei** [Microsoft/vscode#37306]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T06:24:27.011Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.17.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.I run the VSCode and computer fans just started running,the computer began to heat,until a period of time,the computer seriously jammed.It's not like that before,since the updated version released today,I just hava this problem.
2.null

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Can you open your process manager (like htop) to see what process is using a large amount of CPU / memory?
