### ISSUE TITLE
debugViewlet.js: TypeError: Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3730]
Whenever I debug a Mono app I run into this error:

![2016-03-04 18-32-23](https://cloud.githubusercontent.com/assets/1898161/13534871/882ca4d2-e237-11e5-9e75-bfc32780e8b2.png)

**Comment by weinand** [comment]
@isidorn aha, this is not mono-debug related. It occurs everywhere...

**Comment by isidorn** [comment]
@weinand yeah, side affect of a PR i merged this morning
