### ISSUE TITLE
Color picker is being closed prematurely

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#37304]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:47:36.947Z)
- OS Version: Darwin x64 16.7.0

---

Steps to reproduce:
1. Open a file that supports the color picker such as User settings
2. Resize the editor so that when the color picker opens it runs over the boundaries of the editor
3. Open the color picker and move the cursor within the color picker toward the right
-> When the cursor leaves the editor area but not yet the color picker, the color picker is closed.

![oshh3lag0u](https://user-images.githubusercontent.com/4674940/32229995-64328fc6-be52-11e7-9fd7-75bb39e461de.gif)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Thanks, it's dup of https://github.com/Microsoft/vscode/issues/36195 .
