### ISSUE TITLE
New position of panels are not persisted across sessions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37317]
Testing #36571

- Change the panel size
- Change the order of the panels
- Open a new VS Code window
- The updated panel size is persisted, but the order of the panels isnt

**Comment by isidorn** [comment]
Same as with the activity bar the order is workspace specific.
No user has so far complained that we keep this workspace and not user specific for the activity bar. And this two should be aligned.
Thus closing as desinged
