### ISSUE TITLE
Instruction text in Settings Editor should wrap

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37312]
Below the text "Place your settings..." should wrap

<img width="713" alt="screen shot 2017-10-31 at 9 43 43 am" src="https://user-images.githubusercontent.com/16890566/32236682-1aae92aa-be20-11e7-8ea2-f846380e15d7.png">

**Comment by ramya-rao-a** [comment]
@sandy081 Good candidate for `help-wanted` and `good-first-issue` ?

**Comment by sandy081** [comment]
Not sure. Because this involves editor zone widgets which is tricky. 

But why not, if I get help would be happy to delegate :)

**Comment by sandy081** [comment]
With new UI Layout, instruction text gets more space. But no wrapping.

Closing this as there are no plans in fixing this unless if there is a strong opinion.

Thanks
