### ISSUE TITLE
Panel titles do not get border on focus

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37318]
Testing #36571

- Enable `Tab Moves Focus` mode
- Tab around
- The actions on the right get border on focus but the panel titles and the overflow button dont

**Comment by bpasero** [comment]
@isidorn I am still seeing this, the "..." is not getting the focus border for me when I try (on macOS).

**Comment by isidorn** [comment]
Yes, there is a item capturing that for November
