### ISSUE TITLE
Debugger for Node doesn't work when project folder under TFS Git On-Premise

### ISSUE THREAD

**Issue by kevinolorenzo** [Microsoft/vscode#3731]
The debugger for VSCode does not seam to work with Typescript (or Javascript) with a project under an on-premise Team Foundation Server 2015 and Git team project.  At first I thought it may have been the folder levels or some other wierd thing with my particular project so I took the sample app https://github.com/czechboy0/Express-4x-Typescript-Sample and I built it, ran it, and debugged it outside of my source controlled folder with no issue in VSCode.  I copied the exact same folder at the highest level of my source controlled folder and now the debugger does not work in VSCode.  It will stopOnEntry just find and I have source maps enabled with the correct output directory in my launch.json but if you set a breakpoint it just gives you a  "Unverified Breakpoint" tooltip.

Just for more verification, I took my original project and copied it outside of my source controlled folder and the debugger works properly.

I also tried this on a different machine.

**Comment by weinand** [comment]
@kevinolorenzo what is the difference of the TFS project? Does it live on a UNC filesystem? Are they any symbolic links involved? Do the file names contain spaces? When specify the 'outDir' attribute could you try to change the drive letter casing.

**Comment by kevinolorenzo** [comment]
The TFS project is not a shared folder and there are no symbolic links. The root folder DOES contain spaces. Changing the outDir did not resolve the problem.   I will say that this same project under TFS DOES work on my mac using VSCode so it seems to be something Windows related.

**Comment by weinand** [comment]
@kevinolorenzo if the only difference between the TFS project and the non-TFS project is a root folder containing spaces, then you are hitting https://github.com/Microsoft/vscode/issues/3667.

The fix will be available in the next insider's release.

**Comment by kevinolorenzo** [comment]
I did some testing and the spaces are indeed the cause.  Thank you for your help and feedback.
