### ISSUE TITLE
Use existing star import instead of adding new import

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37314]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T06:24:27.011Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37177

Steps to Reproduce:

1. Use a global completion when a star import is already in the file:
```js
import * as b from "./bar";

foo|
```
2. Result:
```js
import * as b from "./bar";
import { foo } from "./bar";

foo|
```
3. It would make sense to reuse the existing import.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19628
