### ISSUE TITLE
Allow languages to define multiple folding.markers

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37319]
It seems that languages can currently only define a single folder.marker. I'd like to be able to define two or more of these if possible. For example, in some languages it would make sense to support both comment and #pragma regions.

Probably falls under the scope of #3422

**Comment by aeschli** [comment]
You can define multiple pattern like [here](https://github.com/Microsoft/vscode/blob/08b1242610cc134f9336efa99de1934c437dcd86/extensions/java/language-configuration.json#L29)

**Comment by mjbvz** [comment]
Makes sense. One case I was also thinking about was how you could use this to define markdown heading foldings. I imagine this would use a bunch of rules like:

```
// h1 folding
{
   start: #\s*\w+,
   end: #{1}\s*\w+
}

h2 folding
{
   start: ##\s*\w+,
   end: #{1,2}\s*\w+
}

...
```

to ensure each heading level would consume all subheadings

**Comment by aeschli** [comment]
IMO that's better done through language aware folding. Regexes have their limitations and can get very expensive.
Closing as dup of #3422
