### ISSUE TITLE
onDidChangeConfiguration fires unnecessary in multi folder workspace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37313]
testing #37151:

sub test: "Event is not triggered if there is no change in the effective configuration. Eg: If you change a value in User settings which already have a value in Workspace settings."

This works fine for User settings and Workspace settings in the single folder case.

But with a two-folder setup where both folders have a folder setting that shadows the user setting, the event still fires.

**Comment by sandy081** [comment]
@weinand Does the workspace settings has a value in this case? If not, change in User settings will impact resources do not belong to any of the workspace folders. Hence a change is triggered.

**Comment by weinand** [comment]
no, I did not had a workspace setting. So that explains it. Thanks!
