### ISSUE TITLE
Debug status item should default to current config in quick pick

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37327]
Testing #35904

It seems weird that the quick pick does not default to the current target, so it adds one step of selection if user wants to debug using the current config by clicking that status bar item.

![image](https://user-images.githubusercontent.com/4033249/32241807-5564019c-be2e-11e7-9009-96556009b6b1.png)

**Comment by isidorn** [comment]
@octref good catch

**Comment by weinand** [comment]
This does not work for me in 2ab10d50163f008ada9a4aa215de8c884857ce99.
Has this feature already landed in the current Insiders?

**Comment by isidorn** [comment]
Not this is not in insiders, this was fixed 3 hours ago
