### ISSUE TITLE
Redundant tooltips on panel titles

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37320]
Testing #36571

- Hover over each of the panel titles
- The text on the tooltip is exactly the same as the text on the panel titles.

This is redundant.

Tooltips are useful if
- They supplement existing information. 
- The underlying control doesnt have text.

In this case, there is no extra information to add, and so tooltips are just noise.

**Comment by isidorn** [comment]
Now we show shortcuts for each panel on hover.
