### ISSUE TITLE
Generated jsconfig.json has invalid value "CommonJS"

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37322]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T06:24:27.011Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37178 

Steps to Reproduce:

1. Settings from #37178 
2. Go to Project Config and create it:
![image](https://user-images.githubusercontent.com/9205389/32240807-82884bc2-be2b-11e7-840b-848a16357d15.png)

**Comment by mjbvz** [comment]
Good catch. Yes the generated setting needs to be lowercase for the schema (although ts doesn't actually care)
