### ISSUE TITLE
No obvious way to tell if a file is UTF-8 with or without BOM

### ISSUE THREAD

**Issue by ronmartmsft** [Microsoft/vscode#3732]
VS Code needs a UTF-8 with and without encoding (or more friendly with and without BOM) option when you do save with encoding.

**More Info**
Unlike Notepad++ which has easy to read menu options for encoding or Visual Studio which as Advanced Save Options which clearly spell out UTF-8 with encoding and without encoding, VS Code makes it very tedious to discover if your file has been saved with or without the BOM. 

This is critically important when saving markdown files in GitHub and using their pages feature - which renders in Linux via Jekyll - because if you get this wrong (like when saving via Notepad) - you can't easily identify the problem - your page just won't render. 

A typical dev test to figure this problem out is to use Notepad++ to check the encoding (or more complex is to run Jekyll locally and read the debug output).

**Comment by bpasero** [comment]
This will become available for GA: https://github.com/Microsoft/vscode/issues/751
