### ISSUE TITLE
Maximize panel icon is blurry

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37330]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
md-navigate|jri|0.0.1
theme-monokai-pro-vscode|mon|1.1.2
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
Ruby|reb|0.15.0
vim|vsc|0.10.2

(1 theme extensions excluded)

---

#36571

The maximize to the left icon looks particularly blurry:

![image](https://user-images.githubusercontent.com/2193314/32242586-6c0036d0-be30-11e7-9432-9fe360507250.png)

The maximize up icon also look blurry as the weight/AA is different to the x icon:

![image](https://user-images.githubusercontent.com/2193314/32242672-a591508c-be30-11e7-9e73-7d6618560a8b.png)

**Comment by isidorn** [comment]
@Tyriar do you also see this in the current vscode stable?
@chryw might you know what causes this, and could we align our icon more with the rest?

**Comment by chryw** [comment]
@isidorn Could be some icons are raster format (png) instead of svg. Could you help me find the actual file reference in code?

**Comment by isidorn** [comment]
@chryw thanks for jumping on this issue - but I have already fixed it. The issue was that I was using the css trick to rotate by 90 degrees instead of using a real icon (which I am doing now).
BTW really appreaciate that you are responsive on our UX issues.

**Comment by Tyriar** [comment]
@isidorn this issue was also saying that the older up/down icons are inconsistent; the AA look quite different on the X but they should look the same as they are both lines of the same width.

**Comment by isidorn** [comment]
@Tyriar please create a new issue for that and assign me and mention @chryw.
@chryw fyi what @Tyriar pointed out
