### ISSUE TITLE
In the narrow view, close button for the panel disappears

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37336]
Testing #36571

- Toggle Terminal using Ctrl+`
- Move the panel to the right
- Keep decreasing the panel size and stop before the whole panel disappears 

The close button is missing

![image](https://user-images.githubusercontent.com/16890566/32246177-5f2b1d8e-be3b-11e7-927c-df3e0260eebe.png)

- Now choose "Debug Console" from the overflow menu

The close button is back

![image](https://user-images.githubusercontent.com/16890566/32246237-938a392a-be3b-11e7-8830-f736a9341c61.png)

- Choose Problems or Output, close button disappears

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37242
