### ISSUE TITLE
Rename new git.* decorator color settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37331]
From #37159

I found the new git explorer color names, such as `"git.untrackedForeground"`, unclear when first browsing through them. Perhaps include the word `explorer` or `resource` in the name to make it explicit where these colors apply? Something like, `"git.untrackedResourceForeground"` or `git.explorer.untrackedForeground`

**Comment by jrieken** [comment]
@aeschli can you help me

**Comment by aeschli** [comment]
Maybe `gitFileDecoration.untrackedResourceForeground`.
'explorer' sounds too restrictive to me. We ended up using the file icons also in many places.

@bpasero ?

**Comment by aeschli** [comment]
Ah, there's already resource. So maybe `gitResourceDecoration.untrackedForeground`

**Comment by jrieken** [comment]
Or , `gitDecoration.modifiedResourceForeground`, `gitDecoration.deletedResourceForeground`, `gitDecoration.untrackedResourceForeground`, `gitDecoration.ignoredResourceForeground`, `gitDecoration.conflictResourceForeground`

**Comment by jrieken** [comment]
or `gitFileDecoration.untrackedForeground` etc

**Comment by bpasero** [comment]
@jrieken @aeschli are these neutral to the selected SCM provider, and if so should they be prefixed with `scm` instead of `git`?

I am fine with `gitFileDecoration.<state><foreground>` (minus the question around `git` vs `scm`)

I find `ResourceDecoration` a bit technical.

**Comment by jrieken** [comment]
It's git only

**Comment by bpasero** [comment]
@jrieken please also add to https://github.com/Microsoft/vscode-docs/blob/vnext/docs/getstarted/theme-color-reference.md#L10

**Comment by jrieken** [comment]
It was already there ;-) https://github.com/Microsoft/vscode-docs/blob/vnext/docs/getstarted/theme-color-reference.md#git-colors
