### ISSUE TITLE
When launching attach config unsuccessfully, debug status bar item does not show

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37335]
While testing #35904 

I don't know if this is as-designed, but this seems to be one of the original motivation for #31745.
When I'm pressing F5 while not focusing on debug viewlet, I got no visual feedback as to what's the debug target.

Would it make sense to enable the status bar item on launching debug instead of on launching debug successfully?

![launch](https://user-images.githubusercontent.com/4033249/32243735-7a70ab5c-be33-11e7-9cd4-30d27e46d105.gif)

**Comment by weinand** [comment]
Verified that the debug status bar item shows up in case of errors. 
But found that those errors are not shown if the debug session is launched from the status bar item.
I've created https://github.com/Microsoft/vscode/issues/37507 for this issue.
