### ISSUE TITLE
Activity bar can get into a state to always show ellipsis

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37333]
While testing #36570 on mac

![image](https://user-images.githubusercontent.com/4033249/32242913-3c23926c-be31-11e7-9ba3-db5070fd51b4.png)

Repro:

![ab](https://user-images.githubusercontent.com/4033249/32243199-f2a1d792-be31-11e7-8e36-b6d1184c4d2b.gif)

**Comment by isidorn** [comment]
Can you please write down your repro steps as it is not 100% clear from the gif.
Thanks a lot!

**Comment by octref** [comment]
1. Hide file explorer in activity bar
2. Open file explorer from Quick Open (hidden widget can still be opened from QuickOpen or shortcuts, and will show at the end of activity bar)
3. Restart VS Code

**Comment by isidorn** [comment]
@octref great catch, thanks
