### ISSUE TITLE
File not recognized as being part of a jsconfig.json

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37334]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37178

Steps to Reproduce:

1. After creating a jsconfig.json (and also after reloading the window).
2. Go to Project Configuration
3. Still asked to configure it first:
![image](https://user-images.githubusercontent.com/9205389/32243524-b0ff7eb0-be32-11e7-9a5f-dcafce99e40a.png)

**Comment by chrmarti** [comment]
Only when `foo.js` is in the `.vscode` folder which wasn't intentional...

**Comment by mjbvz** [comment]
This is by design. We ignore dot files and some common folders  such as `node_modules` by default even if you setup a jsconfig (unless you explicitly include them)
