### ISSUE TITLE
In the narrow view, panel takes precedence over editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37338]
Testing #36571

- Move the panel to the right
- Keep reducing the width of VS Code window.

**What you see:**

1. Editor narrrows first up till a min width
2. Next the sidebar narrows until it disappears
3. Next the activity bar disappears
4. Next the editor disappears

**What should happen:**

1,2,3 are fine
But instead of the editor disappearing in the end, the panel should.
The editor should always take precedence.

**Comment by isidorn** [comment]
Fixed in latest, dup of some issues baen filed
