### ISSUE TITLE
Partial PowerShell Intellisense?

### ISSUE THREAD

**Issue by MattSmith10** [Microsoft/vscode#37349]
- VSCode Version: 1.18.0-insider
- OS Version: Windows 10 Enterprise
- PowerShell Extension version 1.5.0 (installed from within VSCode)
- PowerShell Version 5.1.14393.1715

Steps to Reproduce:
(Brand new installation of VSCode)
When typing PowerShell commands sometimes the intellisense works and sometimes it does not. See images below. Is something broken here? I have tried to force the intellisense with ctrl+space.

![image](https://user-images.githubusercontent.com/8903021/32250657-cee57282-be63-11e7-930b-8c5423ec6af1.png)

![image](https://user-images.githubusercontent.com/8903021/32250682-e3104d54-be63-11e7-8067-95bcf47136f2.png)

Current user settings:
![image](https://user-images.githubusercontent.com/8903021/32250841-80beda48-be64-11e7-9495-2de655b1c3d8.png)

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please report this against https://github.com/PowerShell/vscode-powershell

/cc @daviwil
