### ISSUE TITLE
Race condition due to multiple executions of the same command simultaneously

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#37344]
I've defined the following command in one of my extensions:

```ts
async function foo () {
  return await doStuff ();
}
```

It turns out that if this is running multiple times simultaneously it may throw due to a race condition. It was surprising to find out that I can execute the same command again even if the previous execution didn't return/resolve yet.

To fix this I had to modify my code like so:
```ts
let isFooing = false;
async function foo () {
  if ( isFooing ) return;
  isFooing = true;
  try {
    return await doStuff ();
  } finally {
    isFooing = false;
  }
}
```

Shouldn't there be a better way to solve the problem than writing this kind of ~~crap~~ pattern?

**Comment by octref** [comment]
For open-ended JavaScript discussion on async, I suggest you open a question on https://stackoverflow.com/questions/tagged/javascript. Thanks.
