### ISSUE TITLE
Better hover text needed for debug status bar item

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#37342]
Testing #35904

The debug status bar item allows user to change the default.
The tooltip on it says "Debug" and does not allude to the fact that it also lets you change the default configuration.

"Change default debug configuration" is more accurate.

**Comment by isidorn** [comment]
Thanks for your suggestion, however it is not only "change default debug configuration", since it also launches.
Do you have maybe some other suggestion? I like the simple debug actually, gives the user the context.

**Comment by ramya-rao-a** [comment]
"Change and/or default debug configuration" ?

**Comment by isidorn** [comment]
Thanks for feedback, I have landed on Select and start debug configuration
Since that aligns well with a similar action which we already have in command palette
