### ISSUE TITLE
Copy code snippet to OneNote

### ISSUE THREAD

**Issue by jelez** [Microsoft/vscode#37346]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
yaml|ada|0.0.9
cform|aws|0.0.10
scala|dal|0.0.4
python|don|0.7.0
xml|Dot|1.9.2
vcterminal|esp|0.0.11
code-runner|for|0.8.2
rest-client|hum|0.16.0
terraform|mau|0.0.19
prettify-json|moh|0.0.3
perl-debug|mor|0.2.3
vscode-docker|Pet|0.0.20
bash-debug|rog|0.1.0
json2yaml|tux|0.2.0
jinja|who|0.0.8

---

Steps to Reproduce:
When copying code snippets to OneNote identations are lost
1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
This would be an issue for OneNote, not VS Code.
