### ISSUE TITLE
Selecting text and hitting tab replaces text sometimes, indents others

### ISSUE THREAD

**Issue by JBrace1990** [Microsoft/vscode#37340]
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Highlight word in editor
2. hit tab
Result: Editor replaces selection with text

1. Highlight line
2. Hit tab
Result: Indents characters

This causes you to sometimes replace text with a tab, and sometimes indent. 

Reproduces without extensions: Yes

**Comment by octref** [comment]
Yes, that's the default behavior.
