### ISSUE TITLE
Deleted tsconfig.json brought back by the Go To Configuration actions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37341]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37178

Steps to Reproduce:

1. Not sure about the initial steps yet.
2. Open .ts file
3. Go To Project Configuration
4. Choose to create one
5. tsconfig.json is created
6. Delete tsconfig.json
7. Open .ts file again
8. Go To Project Configuration
9. Choose to create one
10. Observe that the old tsconfig.json "(deleted from disk)" is opened which is unexpected and might be a leak

I have seen the same with a .js file and the jsconfig.json.

![image](https://user-images.githubusercontent.com/9205389/32247965-563b939c-be41-11e7-9c54-aa459d9ee21b.png)

**Comment by bpasero** [comment]
@chrmarti does it reproduce reliably? I tried to follow your steps and cannot reproduce. I am not seeing the "deleted from disk" thing showing up, but this may be a case of missing file events. Are you doing any file operation outside of VS Code?

**Comment by chrmarti** [comment]
No file operations outside of VS Code. It doesn't reproduce reliably, but I've just had it again without doing much else in the same session.
