### ISSUE TITLE
'Install xyz' QuickFix not properly translated

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37352]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37182

Steps to Reproduce:

1. `code --locale=de`

![image](https://user-images.githubusercontent.com/9205389/32251009-5340f6e0-be4c-11e7-86d2-73365053dc8c.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19626
