### ISSUE TITLE
Deletion git decorations bubble up in collapsed sections, but adds and modifies do not

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37357]
Testing #37164

- Have a block containing red, green, and blue git decorations.
![image](https://user-images.githubusercontent.com/323878/32251714-6f8c6fd4-be4f-11e7-88f1-046d5e4b150c.png)

- Fold the block. The delete decoration is visible, the others aren't
![image](https://user-images.githubusercontent.com/323878/32251719-7c40f042-be4f-11e7-8b14-20c749fa210c.png)

Same behavior when just one of these decorations is present. I can know that a folded section contains a deletion but not an add or modify.

**Comment by joaomoreno** [comment]
Not sure what to do here. Opinions @alexandrudima @aeschli ?

**Comment by alexandrudima** [comment]
I'm pretty sure decorations lying 100% within the folded region do not show up anymore. Perhaps that decoration starts on the first folded line or something (i.e. some edge case). Could you reproduce @joaomoreno

**Comment by joaomoreno** [comment]
The decoration in the screenshot is on line 37 which is contained in the 36-x8 range.

**Comment by alexandrudima** [comment]
This is indeed an edge case. It only occurs if the deletion is precisely 1 line into the folded range.

e.g.

| diff | non-folded | folded |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/32272767-e0adc662-beff-11e7-9694-5c5b5d60ba6d.png) | ![image](https://user-images.githubusercontent.com/5047891/32272795-ff7d1bf6-beff-11e7-92c8-382faecd9b32.png) | ![image](https://user-images.githubusercontent.com/5047891/32272813-162fdf46-bf00-11e7-9579-8fbb0276dfac.png) |
| ![image](https://user-images.githubusercontent.com/5047891/32272831-2c35eb64-bf00-11e7-93f5-8ae64aef1d43.png) | ![image](https://user-images.githubusercontent.com/5047891/32272842-38f71a80-bf00-11e7-9504-10646963559a.png) | ![image](https://user-images.githubusercontent.com/5047891/32272859-45d4a1be-bf00-11e7-9228-50e1423ead6e.png) |

**Comment by alexandrudima** [comment]
@joaomoreno It has to do with how we position the deleted range decoration. In the first row, it is positioned at precisely `(2,1)`.

Perhaps I can massage something in the view decorations to avoid this edge case.

**Comment by joaomoreno** [comment]
Thanks @alexandrudima
