### ISSUE TITLE
Clarify `ext` quickopen handler

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37359]
Testing #37163

Is `ext` on its own supposed to do something besides open the extensions viewlet? Since `ext install` exists, I see that `ext` is to "Manage your extensions" and wonder if there are other subcommands or what else it does. A quickopen handler that only shows a viewlet doesn't seem that useful, and we don't have this for other viewlets. Might be useful if I could search for extensions with `ext themes`

**Comment by joaomoreno** [comment]
`ext` is a legacy handler. We don't use it for anything else other than the Linux Marketplace instructions.
