### ISSUE TITLE
TypeScript error message not translated to "zh-CN" and "zh-TW"

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37356]
- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37182

Steps to Reproduce:

1. Screenshot shows case with `--locale=de` and `"typescript.locale": "zh-CN"`. It is the same with `--locale=zh-CN` and zh-TW.

![image](https://user-images.githubusercontent.com/9205389/32251537-9ed7b7ae-be4e-11e7-81d0-31d1069f36d1.png)

https://code.visualstudio.com/docs/getstarted/locales lists these locales.

**Comment by mjbvz** [comment]
@chrmarti Can you please try installing the final TS 2.6.1 build in your workspace and testing this again. You can also try using the next insiders build

**Comment by chrmarti** [comment]
Works for me in the latest insiders.
