### ISSUE TITLE
Build task hangs when no output

### ISSUE THREAD

**Issue by AlexeyRaga** [Microsoft/vscode#3735]
Some incremenral compilers (e.g. GHC/Stack) will not give any output when compiling sources with no changes since the previous compilation.

It looks like when a build task is set up to call such a compiler VS Code "hangs" because it expects some output. By hanging I mean that it is continuously showing a spinning progress indicator.

**Comment by dbaeumer** [comment]
@AlexeyRaga you need to configure the tasks as a watching task.
