### ISSUE TITLE
Git gutter decoration animates when setting breakpoints

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37354]
Testing #37164

![oct-31-2017 15-09-43](https://user-images.githubusercontent.com/323878/32251275-94f70c40-be4d-11e7-87a8-9350a1492b40.gif)

- Set/unset a breakpoint
- The git decoration animates

Also, there is a point between the breakpoint gutter and the line number where the git decoration isn't triggered. So moving the cursor back and forth there causes it to animate.

**Comment by joaomoreno** [comment]
This is a problem with the editor's decorations, as the breakpoint decoration is added an removed the whole decoration element is rerendered. @alexandrudima Anything you're willing to do here? If not, just close it.

**Comment by alexandrudima** [comment]
@joaomoreno Editor decorations are not dom elements that have any lifecycle guarantee. Content widgets or overlays widgets have dom elements that have lifecycle guarantees. I believe in this case CSS animations are used on a decoration dom node. CSS animations are inherently bound to the lifecycle of the dom node. The lifecycle of a decoration dom node can be as short as 1 frame.

**Comment by joaomoreno** [comment]
Yeah sure, I get it. If we're not willing to do anything here at the editor layer, I'll just close it, since animations are cool.
