### ISSUE TITLE
Clearer indication of what is input and what is output in debug console

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#37363]
**Problem**
In the debug console, it can sometimes be difficult to tell what is text you entered and what is the evaluated result:

![screen shot 2017-10-31 at 4 38 10 pm](https://user-images.githubusercontent.com/12821956/32253776-f4153e02-be59-11e7-807b-e96cd6b071e0.png)

This was improved with #35324 for literals but I still like how Chrome and Safari have little icons (and separator lines) to indicate this:

<img width="93" alt="screen shot 2017-10-31 at 4 37 26 pm" src="https://user-images.githubusercontent.com/12821956/32253805-15916600-be5a-11e7-9d1e-e905d28867e1.png">

**Comment by roblourens** [comment]
And F12. Don't forget Edge!

**Comment by isidorn** [comment]
We had these lines before and decided against it, since it is not always nicely grouped two by two. Sometimes some output comes and then the lines would not look so nice. 
@mjbvz you can probaly download a build from a year ago to check it out
@weinand do you remember the other reasons why we removed this?

**Comment by weinand** [comment]
Let's try to use the icons and see how this looks and feel. 

If we like them, then we can try the separator lines (since we made some improvements to the output stream, it could be that some of the old issues no longer exist).

**Comment by isidorn** [comment]
We could look into improving this in the future.
fyi @dgozman since you added colors in your version to make this clearer.

**Comment by isidorn** [comment]
This is how it looks, try it out and let me know.
For the arrows I am using octicon small arrows. @misolori feedback welcome if we have some better icons. Though I peronsally like these.

@weinand already pointed out that the tree expando should be closer to the element, I will look into if that is possible

![Screenshot 2019-12-02 at 16 27 33](https://user-images.githubusercontent.com/1926584/69971842-cff07300-1520-11ea-9361-71633fabceed.png)

**Comment by isidorn** [comment]
Even though the arrows are centered due to the way how the [brain processes](https://en.wikipedia.org/wiki/M%C3%BCller-Lyer_illusion) these images one looks more to the left, and one more to the right and the whole hing looks a bit messy. Suggestions welcome on how to improve!

**Comment by jrieken** [comment]
<img width="86" alt="Screenshot 2019-12-04 at 12 26 45" src="https://user-images.githubusercontent.com/1794099/70138816-5fb52f00-1691-11ea-9f53-788d1f5bff8c.png">


It is there but not really pretty, esp when expanded but I believe we already talked about it
