### ISSUE TITLE
Make navigation history stops configurable

### ISSUE THREAD

**Issue by jtremback** [Microsoft/vscode#3736]
Using goto definition and the back and forward functionality is a really great way to code, and is the main reason I have switched to VScode. Unfortunately, I often have to scroll back through a long history of cursor movements in the current file before reaching the previous file, which is where I wanted to go in the first place.

I can imagine this could be useful for editing long files, but 90% of the time I'm using the history to navigate between files. The sweet spot for me would be to only add cursor movements of over 50 lines to the history. Is there any way to make this configurable? I would even be happy with excluding cursor movements within a file from the history completely, as it would be better than the status quo.

**Comment by isidorn** [comment]
ping @alexandrudima

**Comment by bpasero** [comment]
Currently not configurable and hardcoded to be 5 lines of moving.

**Comment by jtremback** [comment]
Also, are cursor movements from the mouse are handled differently than arrow keys?

**Comment by bpasero** [comment]
No they should not!

**Comment by jtremback** [comment]
where in the source is this set? perhaps i can change it, or even add it to the prefs?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L29

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
