### ISSUE TITLE
Suggestion highlight styles not applied when result is frozen

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37367]
Testing #35538

- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:26:15.706Z)
- OS Version: Darwin x64 16.7.0

---

Steps to Reproduce:

1. Set 
    ```json
    "workbench.colorCustomizations": {
	"editorSuggestWidget.highlightForeground": "#f0f"
    }
    ```
1. Open a js file.
2. Type out `fffee`
3. See in the suggestions

     ![screen shot 2017-10-31 at 6 00 48 pm](https://user-images.githubusercontent.com/12821956/32255481-7508138a-be65-11e7-898f-c4e31f1c1f6d.png)

1. Now with the suggestions still showing, type a `v`

**Bug**

The suggestions details are lost as is the custom colorization for the results:

![screen shot 2017-10-31 at 6 01 19 pm](https://user-images.githubusercontent.com/12821956/32255509-a6962c5c-be65-11e7-830d-cd744a6bbe83.png)

**Comment by jrieken** [comment]
@aeschli This seems to be on purpose [`...:not(.frozen)`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L1103) or is this an oversight?
