### ISSUE TITLE
Approved Badges: codacy.com

### ISSUE THREAD

**Issue by bdistin** [Microsoft/vscode#37369]
I would like to use codacy/codacy badges with my extension. Could the service be reviewed for whitelisting as a trusted service?

Site: https://www.codacy.com

**Comment by mjbvz** [comment]
Should be fixed in the next VS Code insiders build

**Comment by kieferrm** [comment]
We missed to add the service also to vsce. See https://github.com/Microsoft/vscode-vsce/commit/d392126b3d3cc78aa350f4d22df19a737cfccbfa.

**Comment by kieferrm** [comment]
@joaomoreno we'd need a new version of VSCE published to npm. If you add me and @roblourens we could also publish it when needed. I assume there is nothing special about the module.

**Comment by mjbvz** [comment]
Thanks @kieferrm! I also added just `"deepscan.io"` to the list based on https://github.com/Microsoft/vscode/issues/32917

**Comment by joaomoreno** [comment]
@kieferrm @mjbvz Just published 1.35.0.

Let me know your npm login, I can give you permissions to publish the module. Do we have an NPM team for this?
