### ISSUE TITLE
Infinite input validation with no escape

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37365]
#34532

- Have an extension with some command that shows an input box, and returns a validation message.

```
        let i = 0;
        vscode.window.showInputBox({
            validateInput: () => {
                console.log(`validating`);
                return 'spooky * ' + i++;
            },
            prompt: 'happy halloween'
        })
```

- Type a character. It validates over and over ad infinitum
- I can't close it by pressing esc. The only escape is clearing the input or quitting vscode

**Comment by jrieken** [comment]
😱

**Comment by jrieken** [comment]
This is an awesome find. Quick-pick is such a disaster...
