### ISSUE TITLE
Show warning when attempting to type in a diff view's readonly editor

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37362]
**Feature Request**
Show an inline warning when a user attempts to type or manipulate text in readonly editor inside the diff view. Examples: trying to type on the left hand side of a unstaged change, or tyring to type of either side of a staged change 

Similar to #35582

**Comment by bpasero** [comment]
I am not sure this would make sense generally for readonly editors (there is more than just left hand side of diff editors, there is also staged new files in the git index or actually readonly modules during debug).

Imho we should rather find a way to show readonly editors with a different background color maybe to distinguish them from editable editors.

/cc @stevencl

**Comment by stevencl** [comment]
A different background colour would make a lot of sense I think. We'd need to be careful though not to suggest that there aren't actions that the user can take on different readonly editors (such as copying text, modifying settings etc).

**Comment by alexandrudima** [comment]
Done via #37496
