### ISSUE TITLE
Will onDidCreate/onDidDelete fire for each file when a folder is added/removed in multi root workspace?

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#37371]
Or does `workspace.onDidChangeWorkspaceFolders` need to be listened to.

**Comment by bpasero** [comment]
@bmewburn you need to listen to `workspace.onDidChangeWorkspaceFolders` for when workspace folders are added or removed, no event will be triggered via the file watcher interface in that case because the folder is actually not created on disk (just added to the workspace).
