### ISSUE TITLE
打开大文件崩溃

### ISSUE THREAD

**Issue by huoyushi** [Microsoft/vscode#37374]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
path-autocomplete|ion|1.6.2
cpptools|ms-|0.14.0
java|red|0.12.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.2

---

Steps to Reproduce:

打开大文件崩溃 大约9.5GB

Reproduces without extensions: Yes/No

**Comment by frankwei98** [comment]
Please explain your problem in English so everyone can help you. 
请用英语来描述你遇到的问题，这样才有人帮你，谢谢

**Comment by octref** [comment]
We don't have good support for file this large yet. Tracking in #13187
