### ISSUE TITLE
The Size Of Words In Html Cannot Be Output Oorrectly

### ISSUE THREAD

**Issue by tianqingqingyun** [Microsoft/vscode#37370]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-great-icons|emm|2.1.19
vscode-power-mode|hoo|2.0.0

---

Steps to Reproduce:

1.
<img width="396" alt="1 0" src="https://user-images.githubusercontent.com/33272390/32257318-6c888d40-beef-11e7-91fa-ad4234ca3596.PNG">
<img width="295" alt="1" src="https://user-images.githubusercontent.com/33272390/32257319-71db4b3e-beef-11e7-9790-d30c45ea4a65.PNG">
<img width="392" alt="2 0" src="https://user-images.githubusercontent.com/33272390/32257320-74ff5e68-beef-11e7-84fe-d4f1122cf489.PNG">
<img width="347" alt="2" src="https://user-images.githubusercontent.com/33272390/32257323-77d4d186-beef-11e7-9569-aef3e14c22d2.PNG">

2.After I changed the size ,it responded with no changes on the page.
Please fix it up.

Reproduces without extensions: Yes/No

**Comment by tianqingqingyun** [comment]
I hope it can be solved as soon as possible!

**Comment by yume-chan** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font#Attributes), the valid range for the `size` attribute is `1` to `7`, thus `10` and `100` are both invalid and act same as `7`.

**Comment by octref** [comment]
@yume-chan is correct. Besides, that has nothing to do with VS Code.
