### ISSUE TITLE
Save on resolution of merge conflict

### ISSUE THREAD

**Issue by WesleyYue** [Microsoft/vscode#37378]
I'd like to put in a feature request to save the conflicted file automatically when I resolve it using the git lens interface (GUI?). I've accidentally committed files thinking they were resolved only to realized I never saved after pressing one of the "Accept Change" buttons.

**Comment by joaomoreno** [comment]
We have another issue to warn about unsaved files when committing. That's a better approach.

**Comment by WesleyYue** [comment]
This wouldn't solve the problem in my particular use case because I normally do all my git operations on the terminal and only use the editor to resolve the conflicts. Not sure if this is considered an edge use case. Is there any reason saving on clicking "Accept Change" is undesirable?
