### ISSUE TITLE
Workspace tabs are expanded by default when launching vscode

### ISSUE THREAD

**Issue by jarshwah** [Microsoft/vscode#37372]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
Ionide-fsharp|Ion|3.9.0
swift|Kas|0.0.3
vscode-ios-common-files|Ort|1.0.4
vscode-docker|Pet|0.0.20
code-settings-sync|Sha|2.8.3
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-icontheme-nomo-dark|be5|1.3.4
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-svgviewer|css|1.4.3
whitespace-plus|dav|0.0.5
vscode-eslint|dba|1.4.0
vscode-yaml-validation|dja|0.0.1
githistory|don|0.2.3
python|don|0.7.0
pgsql|dou|0.0.8
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
code-runner|for|0.8.2
add-new-line-to-files|jdf|0.1.1
restructuredtext|lex|40.0.0
prettify-json|moh|0.0.3
azure-account|ms-|0.1.3
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
sublime-keybindings|ms-|3.0.2
debugger-for-chrome|msj|3.4.0
vscode-icons|rob|7.17.0
final-newline|sam|0.3.2
whitespace|san|0.0.4
preview-vscode|sea|1.3.4
vscode-sql-beautify|sen|0.0.4
shellcheck|tim|0.2.1
expand-selection-to-scope|vit|0.2.0
jinja|who|0.0.8
change-case|wma|1.0.0

(3 theme extensions excluded)

---

When launching vscode from the command line to open a folder (project), all of the tabs in the side drawer are expanded by default. These extra tabs are provided by extensions such as docker and gitlens. Expanding these extension tabs obscures the file tree view significantly, and always results in me manually minimising the tabs.

![expanded](https://user-images.githubusercontent.com/541083/32258857-0cf8be6e-bf11-11e7-8947-6423c153edd2.png)

All side drawer tabs should be minimised by default except for the directory/file view.

![closed](https://user-images.githubusercontent.com/541083/32258860-1108f08c-bf11-11e7-85b0-b1373da5e40c.png)

Steps to Reproduce:

1. Launch vscode on a new project `code .`
2. All tabs are expanded in the side drawer, such as gitlens and docker (as well as the project files)

Reproduces without extensions: No (extensions provide the extra tabs)

**Comment by jarshwah** [comment]
What's most annoying though, is that the bottom-most tab takes up the available space until all of them are closed. Only then do you get the space back for the file view.

![mostly-collapsed](https://user-images.githubusercontent.com/541083/32258931-73154f1e-bf11-11e7-824a-4deffeee9027.png)

**Comment by sandy081** [comment]
@jarshwah Can you please try our latest insiders in which the default behaviour is that in a new workspace all custom views are collapsed by default. 

https://code.visualstudio.com/insiders
