### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37386]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
hey @isidorn

**Comment by egamma** [comment]
good test

**Comment by isidorn** [comment]
Thanks for particitpaitng I was not getting GH notifications for the past 10 hours. Everything is back to normal now, I must have hit some limit on their side
