### ISSUE TITLE
Format: breaks rule on <wbr> (inner word break opportunity) tag

### ISSUE THREAD

**Issue by bvhme** [Microsoft/vscode#37389]
- VSCode Version: 1.17.2
- OS Version: High Sierra

Steps to Reproduce:

1. Add [a word-break opportunity `<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr). In this example we do this so the URL can be displayed well on a mobile without losing legibility.

```html
<a href="https://github.com/Microsoft/vscode">https://github.com/<wbr>Microsoft/<wbr>vscode</a>
```

2. Format or Format on save.

```html
<a href="https://github.com/Microsoft/vscode">https://github.com/
  <wbr>Microsoft/
  <wbr>vscode</a>
```

As you can see this has done the opposite as what the tag was intended for and added a bunch of spaces into the URL.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Fix is on the way. In the meantime, add `wbr` to `html.format.unformatted`
`"html.format.unformatted": "wbr"`
