### ISSUE TITLE
Git Commit Message file type respects git core.commentChar 

### ISSUE THREAD

**Issue by hanxue** [Microsoft/vscode#37387]
- VSCode Version: 1.17.2
- OS Version: 10.10.5

Steps to Reproduce:

1. Run the command `git config core.commentChar ";"`
2. Then run `git commit --amend` with vscode as GIT_EDITOR
3. Syntax highlighting still expecting `#` as comment character

![image](https://user-images.githubusercontent.com/760008/32266033-aa4290c8-bf20-11e7-8e09-93084c600dfe.png)

# Expected Result

When detecting the file type *8Git Commit Message**, vscode will respect the `git core.commentChar ` settings

Reproduces without extensions: Yes

**Comment by rcdailey** [comment]
Would the dev team be willing to reconsider reopening this issue?

**Comment by whatsupbros** [comment]
Any plans on reopening of this issue?
