### ISSUE TITLE
slowly sometimes

### ISSUE THREAD

**Issue by Cuihongwen** [Microsoft/vscode#37388]
- VSCode Version: <code>Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (4 x 2999)</code>
- Memory (System): <code>7.99GB (2.46GB free)</code>
- Memory (Process): <code>165.63MB working set (209.63MB peak, 124.27MB private, 46.32MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|796|
|renderer|require(workbench.main.js)|3341|
|renderer|create extension host => extensions onReady()|1214|
|renderer|restore viewlet|284|
|renderer|restore editor view state|0|
|renderer|overall workbench load|731|
|main + renderer|start => extensions ready|5426|
|main + renderer|start => workbench ready|4909|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by Cuihongwen** [comment]
Open the VS and do nothing with CPU usage  5%. The VS is blocked suddenly and don't react to my operation.The CPU is 50% without reason.After about 10 s ,the VS works fine and the cpu back to 5%.
This issue occurs every 5mins.

**Comment by jrieken** [comment]
Please attach a profile and the readings from the startup timers as described here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#read-startup-timers
