### ISSUE TITLE
Command to toggle panel layout

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37382]
Testing #36906 with 8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791

There is this command:

![image](https://user-images.githubusercontent.com/4033249/32262283-020d365e-be91-11e7-82c4-825297fcd9d6.png)

For the sake of consistency I think there should be one for toggling panel layout too.

**Comment by isidorn** [comment]
There is, it is call Toggle Panel Position
![screen shot 2017-11-01 at 08 19 33](https://user-images.githubusercontent.com/1926584/32264114-69d614b2-bedd-11e7-94f9-710099f644f8.png)
