### ISSUE TITLE
Open Debug View on Launch

### ISSUE THREAD

**Issue by rickvanprim** [Microsoft/vscode#37385]
Similar to `debug.openExplorerOnEnd` but on the other end, I want VSCode to switch to the Debug sidebar (or optionally a Debug view preset if those ever become a thing) when I execute a Launch.

**Comment by bpasero** [comment]
@isidorn fyi

**Comment by isidorn** [comment]
This is a fair feature request.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L875

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/37704

**Comment by rickvanprim** [comment]
Awesome, thanks for implementing this!

**Comment by isidorn** [comment]
@rickvanprim you can thank @hun1ahpu :)
