### ISSUE TITLE
Toggle sidebar also toggles "maximize panel size"

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#37384]
Testing #36906 with 8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791

![p](https://user-images.githubusercontent.com/4033249/32262828-15e8881a-be94-11e7-9a79-34fba73d1c7c.gif)

To repro:

1. Make panel vertical
2. Maximize Panel Size and resize it to make it as large as possible
3. Toggle sidebar with Cmd+B.

**Comment by isidorn** [comment]
This is fine, openeing the sidebar reduces the size of the panel thus the action becomes active / inactive. Closing as designed
