### ISSUE TITLE
Provide hooks to enable extensions to extend command line options

### ISSUE THREAD

**Issue by zspitz** [microsoft/vscode#37383]
VS Code has a set of [basic command-line options](https://code.visualstudio.com/docs/editor/command-line). However, there is currently AFAIK no way for extensions to handle additional command-line options.

My specific use case is that SQL Server Management Studio supports connecting to a SQL Server database via [parameters passed to the command line](https://docs.microsoft.com/en-us/sql/ssms/ssms-utility):

    ssms -S dbserver -U myUser -P pwd1234

which opens a new SQL editing window with the given connection parameters. If VS Code allowed extensions to handle additional command line options, then [the same could be done with VS Code, via the MS SQL extension](https://github.com/Microsoft/vscode-mssql/issues/1013).

Some additional thoughts:

* In order to prevent conflicts between extensions, some sort of naming scheme for each option might be required:

      vscode -mssql:S dbserver -mssql:U myUser

* It would probably be easier to map options to commands contributed by the extension, but I am not sure that would be sufficient. For example, in this particular scenario, there is no corresponding command to _open a new editor which is already connected with the following connection parameters_. Also, AFAIK commands don't take arguments/parameters.

**Comment by Hickory420** [comment]
Hi guys, just wondering how this was going? I would love this feature.
Keep up the good work! 

Cheers.
