### ISSUE TITLE
Can't open new window from taskbar when running as administrator

### ISSUE THREAD

**Issue by HajniO** [Microsoft/vscode#37391]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.14
beautify|Hoo|1.1.1
indenticator|Sir|0.4.2
language-stylus|sys|1.7.3

Steps to Reproduce:

1. open Visual studio Code as administrator
2. right click on icon from taskbar and select "New Window" from Tasks
3. no new instance was opened :(

The interesting part is if I try to open a new instance by using the way File -> New Window that works :)

Reproduces without extensions: not tested

**Comment by bpasero** [comment]
@HajniO does it work when you do not run as administrator?

**Comment by HajniO** [comment]
Yes, it's working fine if I'm not running as administrator.

**Comment by Hummer311** [comment]
I also experiment this. See #37712.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/37962
