### ISSUE TITLE
ts error 

### ISSUE THREAD

**Issue by Ashish142** [Microsoft/vscode#37399]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.22.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Spown** [comment]
[____](https://en.wikipedia.org/wiki/Anencephaly)

**Comment by mjbvz** [comment]
Please provide information about the error
