### ISSUE TITLE
Cloud shell doesn't open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#37394]
Testing #37180 
OS: Windows

Following the steps in #37180 opening the cloud shell results in this:

<img width="916" alt="capture" src="https://user-images.githubusercontent.com/1931590/32270496-705625ac-bef6-11e7-9bf0-79a260bdb586.png">

No prompt appears. No exception in the console.

**Comment by Tyriar** [comment]
@chrmarti there's an issue on Windows in the terminal where this typically means that the shell exited immediately.

**Comment by chrmarti** [comment]
Fixed with 4f0866d
