### ISSUE TITLE
Do not have a git plugin in the activity bar part 

### ISSUE THREAD

**Issue by Italoa2015** [Microsoft/vscode#37396]
Why my vscode does not have a git plugin in the activity bar part ? 

<img width="929" alt="screen shot 2017-11-01 at 6 43 00 pm" src="https://user-images.githubusercontent.com/12666789/32271442-d781c72a-bf34-11e7-9544-b56239644ffb.png">

**Comment by joaomoreno** [comment]
Right click that activity bar part.

**Comment by Italoa2015** [comment]
@joaomoreno Thanks!
