### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by nzozor** [Microsoft/vscode#37392]
- VSCode Version: Code - Insiders 1.18.0-insider (81cca6cc606eeca3443998025bff3893fcfe3ad5, 2017-10-31T05:19:39.344Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 
Sometimes, The cursor on the command line  console disappear. Still can type though. Im using git bash terminal integration
Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|0.0.2
vscode-eslint|dba|1.4.0
vscode-html-css|ecm|0.1.8
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|1.7.2
html-css-class-completion|Zig|1.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Can you provide a screenshot or record a gif with https://www.cockos.com/licecap/?
