### ISSUE TITLE
Got stuck after recent updates + all screen goes white

### ISSUE THREAD

**Issue by djsanj007** [Microsoft/vscode#37398]
- VSCode Version: 1.17.2
- OS Version: 10.13.

Steps to Reproduce:

1. Sometime when working on project , switch between file with ctrl+tab

![screen shot 2017-11-01 at 4 38 27 pm](https://user-images.githubusercontent.com/739586/32272275-6fc746ac-bf23-11e7-9b5b-6b6bec3c61c5.png)

**Comment by octref** [comment]
#35527
