### ISSUE TITLE
[Javascript]Cannot distinguish VAR

### ISSUE THREAD

**Issue by longque** [Microsoft/vscode#3739]
When it's in my project,VSCODE cannot distinguish VAR f,timeago and others.VSCODE says "Unused Local Var".But when it's only in a file,there's not problem.
![00](https://cloud.githubusercontent.com/assets/8530043/13547619/fcc58bf0-e314-11e5-9ed7-21f6bac1edf4.png)
![01](https://cloud.githubusercontent.com/assets/8530043/13547620/fccb57b0-e314-11e5-8a79-bdc980815f55.png)

The code file:https://github.com/longque/fairytale/blob/master/lib/Helpers.js
The function "foreach" and "moment" is copyed from https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/foreach.js and https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/date.js

VERSION:0.10.8
NODEJS(My Project):v4.2.3(I used ES6)
PLATFORM:Windows 10

**Comment by isidorn** [comment]
Our javascript validation has changed a lot in the latest version of VSCode, can you please try getting the 0.10.10-insider version. Or wait of the 0.10.10 to be out.

Also might this warning be expected? Are you using those variables `f`, `timeago`, `date`?

If you still see this issue with the latest vscode and if the warning is not expected I can reopen this issue.
