### ISSUE TITLE
Investigate why expanding a tree in the explorer would make the extension host a noticeable number of seconds slower

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#37393]
Extracted from [here](https://github.com/Microsoft/vscode/issues/36575#issuecomment-339291392).

Investigate why expanding a tree in the explorer would make the extension host a noticeable number of seconds slower. e.g. language features such as squiggles also suffer from the slow extension host...

**Comment by alexr00** [comment]
Closing to clean up since this has been around for 2 years. If someone still sees this problem please ping :)
