### ISSUE TITLE
[Info] pop ups while writing code in Visual Studio Code

### ISSUE THREAD

**Issue by andrewrgoss** [Microsoft/vscode#374]
Is there a way to turn off the [Info] pop ups that queue up while writing code in VSCode? I have to manually click to close them and I don't want them appearing while writing new code. It's driving me nuts! Tried Googling the topic and couldn't find anything.

<img width="671" alt="vscode_info_popups" src="https://cloud.githubusercontent.com/assets/1461386/11309428/cecb869a-8f91-11e5-96b6-e93aea8fb945.PNG">

**Comment by SamVerschueren** [comment]
Have you installed a plugin or something? This isn't core VS Code that's spawning the popups, it's probably a plugin that's not entirely working correctly...

**Comment by andrewrgoss** [comment]
I installed the Go Support extension before I started using VSCode. Also installed the following Go libraries:

https://github.com/rogpeppe/godef
https://github.com/nsf/gocode
https://github.com/mitchellh/go-ps

First time using VSCode so didn't realize the popups weren't part of the core code. Can you point me to documentation for restoring VSCode default settings?

**Comment by bpasero** [comment]
@lukehoban fyi

**Comment by lukehoban** [comment]
Yeah - I believe this is a bug in the `vscode-go` plugin.

**Comment by lukehoban** [comment]
This issue was moved to Microsoft/vscode-go#50

**Comment by SamVerschueren** [comment]
@andrewrgoss Try to uninstall the `go` plugin and try it again. If the popups aren't showing up anymore, it's an issue with that plugin and you might file an issue over [there](https://github.com/Microsoft/vscode-go/issues).
