### ISSUE TITLE
编辑器无法打开大图片

### ISSUE THREAD

**Issue by dmljc** [Microsoft/vscode#37409]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.10
vscode-markdownlint|Dav|0.11.0
beautify|Hoo|1.1.1
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|2.2.4
html-snippets|abu|0.1.0
project-manager|ale|0.22.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.2
git-project-manager|fel|1.4.0
auto-rename-tag|for|0.0.14
code-beautifier|mic|1.7.2
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|1.0.0
vscode-csscomb|mrm|5.2.1
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
view-in-browser|qin|0.0.5
vscode-icons|rob|7.17.0
react-beautify|tai|0.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kpatrick** [comment]
auto translates as "editor cannot open large picture".

**Comment by octref** [comment]
Please provide a sample image which VS Code cannot open.
