### ISSUE TITLE
ESLint throwing errors

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#37404]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
python|don|0.7.0
pgsql|dou|0.0.8
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.0.5
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|3.4.0
code-spell-checker|str|1.4.12

(3 theme extensions excluded)

---

Steps to Reproduce:

No idea what I did, but I'm flooded with errors I did not see last week.

ESLint log:
```
(node:9672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): TypeError: missingModuleReported.has is not a function
```

I also keep getting one of those alert bars at the top showing `sourceCode.commentsExistBetween is not a function`. I have no idea why. When I close it, it just pops up again.

I installed Node 8.9.0 today and cleaned my globally installed npm modules. I would assume some relation to that.

Disabling ESLint integration resolves both issues.

**Comment by Spown** [comment]
https://github.com/Microsoft/vscode-eslint/issues/new

**Comment by radishlau** [comment]
try restarting vs code. it worked for me
