### ISSUE TITLE
Please Support NSIS Script syntax highlighting

### ISSUE THREAD

**Issue by wbsdty331** [Microsoft/vscode#3740]
![qq 20160305230750](https://cloud.githubusercontent.com/assets/4280572/13548269/1e51a2e2-e327-11e5-9151-f97b2941c8fc.png)

> Example NSIS Script syntax highlighting

``` NSIS
Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
!include MUI2.nsh
!include ButtonLinkerLib.nsh
!include nsDialogs.nsh
!include LogicLib.nsh
```

![np](https://cloud.githubusercontent.com/assets/4280572/13548286/6dc43448-e327-11e5-9d3b-1ca170493d1a.png)

> NSIS Script In `Notepad++`

**Comment by isidorn** [comment]
ping @aeschli

**Comment by aeschli** [comment]
We currently don't plan add to NSIS highlighting to VSCode, but this could be easily added as an extension, e.g. using this text mate grammar: https://github.com/SublimeText/NSIS/blob/master/NSIS.tmLanguage 

Check out https://code.visualstudio.com/docs/tools/yocode about how to create an extension.

**Comment by wbsdty331** [comment]
> e.g. using this text mate grammar: https://github.com/SublimeText/NSIS/blob/master/NSIS.tmLanguage

I added an extension.
but It doesn't work.

**Comment by mjbvz** [comment]
Closing since this is something an extension should provide.

@wbsdty331 Please let us know if you run into any specific VSCode issues authoring the extension

Thanks
