### ISSUE TITLE
Support for wiki links (files without extension) in Markdown

### ISSUE THREAD

**Issue by KvanTTT** [Microsoft/vscode#37400]
* VSCode Version: 1.17.2
* OS Version: Windows 10 x64

Links to wiki pages should not have extensions (GitHub, GitLab). I suggest adding support for such links to VSCode.

The common link to file:

```Markdown
[Wiki page](wiki-page.md)
```

Wiki link to file:

```Markdown
[Wiki page](wiki-page)
```

The following steps can be considered for such links:

1. Try to open file without extension.
2. Try to open any file with supported extension (txt, md, etc.) if failed on the first step.

Reproduces without extensions: Yes.

**Comment by dbaeumer** [comment]
I am reopening this. It works in the editor but not in preview mode

- main.md
```
[Wiki Page](page)
```
- page.md
```
# Header
```
- open preview mode of main.md
- click on the link

Observe: page.md doesn't open. Instead you get a message saying that page doesn't exist.
