### ISSUE TITLE
Extension recommendation badge not shown for a recommended extension

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#37419]
Testing #37186 

- opened a python file
- install recommendations shows up
- select 'install'

The extension viewlet shows up, but the recommended extension doesn't show the badge

![image](https://user-images.githubusercontent.com/172399/32281489-4004b3ea-bf1f-11e7-977b-3b03134858fc.png)

The same is true for workspace recommended extensions.

**Comment by ramya-rao-a** [comment]
Well, since the view is for "recommendations", if we decide to show the badge here, all items in the list will get the badge.

That felt a little redundant.

@Microsoft/vscode thoughts?

**Comment by chrmarti** [comment]
One argument that can be made for showing it is consistency. It would also make it more obvious that you are looking at recommendations, the section title doesn't jump out. Could you attach a screenshot with the batches shown for comparison?

**Comment by octref** [comment]
I always thought badge is only for the selected extensions, not all workspace recommendations, so in that case I'd only expect Don's extension to get the badge.

**Comment by ramya-rao-a** [comment]
@octref The badge is for all recommendations for you. 

@chrmarti The default view would look like this:

![image](https://user-images.githubusercontent.com/16890566/32301809-b38ed758-bf1c-11e7-9f77-9ced106676f9.png)

**Comment by Tyriar** [comment]
@ramya-rao-a it's probably better to keep the star in the recommended pane imo as it makes things consistent and reinforces the meaning.

**Comment by ramya-rao-a** [comment]
Updated to show the badge in all views for recommended extensions

**Comment by chrmarti** [comment]
Tools related recommendations still don't have the badge, but I assume that is expected. Labelling verified.

**Comment by seanmcbreen** [comment]
I think it's worth having the '*' in both views for consistency personally.

**Comment by ramya-rao-a** [comment]
@chrmarti The tool related recommendations should have the badge and the reason on hover in the latest Insiders

**Comment by chrmarti** [comment]
@ramya-rao-a I now see the Docker and the VSTS extension both have the batch. 👍
