### ISSUE TITLE
Some shortcut keys not working

### ISSUE THREAD

**Issue by manasballav** [Microsoft/vscode#37415]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.0
python|don|0.7.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1

---

Copy line up and Copy line down is not working through keyboard shortcut.

**Comment by octref** [comment]
If you do Command Palette -> copy line up it should show the cucrrent active shortcut. What is it and how is it not working?

![image](https://user-images.githubusercontent.com/4033249/32352422-6c4852ee-bfde-11e7-963c-ea7122faf19e.png)

**Comment by manasballav** [comment]
In the Command Palette the shortcut key for copy line up shows Ctrl+Shift+Alt+UpArrow. When I press this key combination it does not work, the line does not copy.

**Comment by alexandrudima** [comment]
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by mliq** [comment]
I have this same problem on MacOS:
* Keyboard is still detected and captured and saved perfectly in the keyboard shortcut settings. 
* Keyboard shortcuts show correctly in command palette. 
* Commands work correctly if triggered through command palette. 

But keyboard shortcuts do not trigger the commands anymore in the editor as of latest VSCode update (1.18.0).

**Comment by alexandrudima** [comment]
@mliq You are most likely not having the same problem as @manasballav. 

It appears, that for you, the keybinding makes it to VS Code, but there are some keybindings rules that conflict. See below how to find conflicting keybindings:

---

Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by mliq** [comment]
@alexandrudima Thank you for the idea, but no, that is not the problem. I have no conflicts. 

Here is one that stopped working in the resolve conflicts view:
![image](https://user-images.githubusercontent.com/7573605/32741811-1e846f38-c86d-11e7-9c33-cd9052d98425.png)

It seems that many of my extension-related shortcuts stopped working, but not all, this one still works for example:
![image](https://user-images.githubusercontent.com/7573605/32741878-504e8972-c86d-11e7-8747-d1139db39dd8.png)

It might even be isolated to GitLens... Will have to do further testing.

**Comment by mliq** [comment]
I figured it out. I was overriding the default gitlens command in my `keybindings.json`, however in the latest version of that plugin the `"when"` property's value changed, from 
```
{
        "key": "alt+a",
        "command": "gitlens.toggleFileBlame",
        "when": "editorTextFocus && gitlens:isTracked"
},
```
to:
```
{
        "key": "alt+a",
        "command": "gitlens.toggleFileBlame",
        "when": "editorTextFocus && gitlens:activeIsBlameable"
},
```

Perhaps something similar for OP (@manasballav).

**Comment by mliq** [comment]
There were also some strange bugs when I was trying to debug this by commenting out or changing my `keybindings.json`. Such as, commands in the command palette would not execute (saying they did not exist) until I closed and restarted vscode.

**Comment by alexandrudima** [comment]
:+1: @mliq - If you find anything fishy going on while editing the `keybindings.json` with clear steps please open a separate issue. In theory, the worst that would happen when editing that file is that if it becomes invalid JSON it might be ignored (the defaults keybindings kick in). If you spot anything else going wrong, please create a separate issue.

---

@manasballav 
Does VSCode receive the ctrl+alt+arrow keybindings?
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
