### ISSUE TITLE
Poor support for SASS

### ISSUE THREAD

**Issue by lessandsass** [Microsoft/vscode#37410]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1.Color code are not showed with the color with sass variable.
![32147587-e5a93d00-bd0f-11e7-96e7-942c7bf99d32](https://user-images.githubusercontent.com/31947204/32276453-3a82c342-bf35-11e7-82b4-cbd1175c96d4.png)

**Comment by michaeljota** [comment]
There are plenty of extensions in the market place, one that I use is [vscode-scss](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss)

**Comment by octref** [comment]
Give @michaeljota's suggestion a try. Meanwhile if you are using sass (as opposed to scss) you can try https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented
