### ISSUE TITLE
Python extension recommendation not shown on top

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#37418]
Testing #37186 

- opened a python file
- install recommendations shows up
- select 'install'

The extension is starting to install, but I was expecting that the recommended extension shows up on top and not as shown below.

![image](https://user-images.githubusercontent.com/172399/32281300-bf27607e-bf1e-11e7-93cf-f62acec0aa07.png

**Comment by ramya-rao-a** [comment]
Ah! This happens when we have more than one recommendation for given file type.
Will fix it.
