### ISSUE TITLE
Many builtin PHP functions are not pop up as hint.

### ISSUE THREAD

**Issue by lessandsass** [Microsoft/vscode#37411]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
Steps to Reproduce:

- Ex: mysqli_query( ) and more...
![32147711-a263e03e-bd11-11e7-9e55-49a1779e51d9](https://user-images.githubusercontent.com/31947204/32276614-bdc7e0ca-bf35-11e7-88bf-2009b30c6e3b.png)

**Comment by octref** [comment]
Please file this issue against the PHP extension that you are using.
