### ISSUE TITLE
"Queue" is not resolving

### ISSUE THREAD

**Issue by zarrini** [Microsoft/vscode#3741]
Hi,
I am using Visual Studio on Mac (El Capitan) and it seems that "Queue" is not resolving, however when I run my program on Terminal, it works fine. it shows red squiggles under Queue, and Error: The value, constructor, namespace or type 'Queue' is not defined. But the code compiles and runs.
I thought it could be a bug and wanted to share it:

    open System.Collections.Generic;;
    type ListTree<'a> = Node of 'a * (ListTree<'a> list)
    let bfIter f ltr =
        let todo = Queue<ListTree<'a>> ()
        todo.Enqueue ltr
        while(todo.Count <> 0) do
     let(Node(x,xs)) = todo.Dequeue()
            List.iter(todo.Enqueue) xs
            f x

OS X El Capitan (Version: 10.11.3) - Java Studio Code: Version 0.10.9 (0.10.9), ionide-fsharp 1.2.0

**Comment by isidorn** [comment]
@zarrini what exactly do you mean when you say that 'Queue' is not resolving. What is the behaviour you would expect here? What is the behaviour that you get?

**Comment by zarrini** [comment]
Shows red squiggles under Queue, and Error: The value, constructor, namespace or type 'Queue' is not defined. But the code compiles and runs.
I thought it must be a bug

**Comment by weinand** [comment]
@zarrini since your problem occurs in F# and you have the "ionide-fsharp" extension installed, this does not seem to be a VS Code problem. Please file this bug against the "ionide-fsharp" extension.

**Comment by zarrini** [comment]
@weinand already done,but I thought you might be interested to know about it as well. btw thanks
