### ISSUE TITLE
Improve support for data instance auto-completion and validation

### ISSUE THREAD

**Issue by wisotzky** [Microsoft/vscode#37416]
vscode should support the concept of data-models and data-model instances. Currently I am looking for a platform to develop YANG models and YANG data instances using JSON, XML or YAML as data representation layer (encoding).

Conceptional when editing data instances (or even better data instance templates using templating languages like Jinja2, VTL or handlebars) it would be desired to have IntelliSense support. Therefore vscode should support a built-in repository of data-models (for example in YANG) and also search all YANG files which belong to the "project".

To support those use-cases, likely there is a dependency to the Language Server Protocol as well. For example there is a need to extend the namespaces SymbolKind and CompletionItemKind to better reflect YANG specific items. Also the Language Server needs to have knowledge about the data models (YANG files) which belong to a project.

The feature request is about providing capabilities regarding data models and instances. There are similar requirements when working with XML documents and validate those against XSD or other schema definition.

**Comment by octref** [comment]
There are some Yang extensions on the marketplace: https://marketplace.visualstudio.com/search?term=Yang&target=VSCode&category=All%20categories&sortBy=Relevance

You can try them out, open feature requests against them or contribute to them.

**Comment by wisotzky** [comment]
I've looked into the YANG-LSP extension earlier. It is indeed very reasonable, if the task is to edit YANG files itself. Main objection would be, that LSP seems to have no capabilities to render you an outline of the complete YANG data-model (including all sub-modules belonging to the module). But people playing around with YANG would like to have visibility on the complete tree - as it is available in standalone tools like PYANG and YANG Explorer.

The other issue is, that you would not like limiting yourself to YANG authoring but creating YANG instances as well. AFAIK, the LSP API does not come with the capability to have combined file support. For example, to support YANG (describing the data model) and XML (for the data model instance). YANG itself is really rich, so it contains all information to allow state-of-the-art IntelliSense support.

Please reopen this issue, to have a discussion, on what needs to be done from vscode infrastructure point of view. Once this is done, I am committed to support to author appropriate extensions for this.

**Comment by octref** [comment]
OK, I'll leave this issue open.

> render you an outline 
I'm not familiar with Yang, but UI components or rendering is out of LSP's scope.
You might be interested in VS Code's `previewHtml` API, example here: https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample
The popular Python extension is using it to render Jupyter notebooks.
When I googled PYang and Yang Explorer it seems users are mostly in Python community. Maybe you can ask @DonJayamanne for some guidance on supporting it better.

> But people playing around with YANG would like to have visibility on the complete tree
We have an API for tree view: https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
https://code.visualstudio.com/updates/v1_13#_extension-authoring

> LSP API does not come with the capability to have combined file support
You need to be more specific here and give an example.

/cc @dbaeumer

**Comment by roblourens** [comment]
I agree with @octref's comment, it's not likely that there will be more UI support beyond previewHTML and the tree api.
