### ISSUE TITLE
ConfigurationModel is slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37426]
Related to https://github.com/Microsoft/vscode/issues/34353 and #34282. When you profile start and look at the time spend in the configuration service you'll notice that it's still very slow. 

Paste `require('vs/base/node/startupTimers').ticks().forEach(tick => console.log(tick.name, tick.duration))` in the dev-tools-console and see that ~100ms is spend in building/merging/deduping the configuration model. 

Apart from `clone` it also seems that a lot of time is spend in `arrays#distinct` which as a potential runtime of O(n2)

<img width="1096" alt="screen shot 2017-11-01 at 18 15 06" src="https://user-images.githubusercontent.com/1794099/32287451-2e5f917a-bf31-11e7-8a55-d93069a0a7c4.png">

**Comment by sandy081** [comment]
@jrieken Thanks for the report. 

May I know if it is slower than before ?

**Comment by jrieken** [comment]
> May I know if it is slower than before ?

No clue, you can measure it with an old version of VS Code

**Comment by sandy081** [comment]
This is the new picture after doing following improvements:

- Merge, clone and freeze only when the configuration is requested.
- Fix from @jrieken - #37539
- Register and trigger configuration and default configurations all at a time.
- Merge user configuration service and workspace configuration service to remove duplicate merges and triggering.

![image](https://user-images.githubusercontent.com/10746682/32618860-2f0d387c-c579-11e7-8e68-8be91b686db1.png)
