### ISSUE TITLE
Powershell syntax highlight suggestion: string -format, the  {0} should be highlighted

### ISSUE THREAD

**Issue by DoTheEvo** [Microsoft/vscode#37425]
![showit](https://i.imgur.com/qDjqP0q.png)

[many ways](https://kevinmarquette.github.io/2017-01-13-powershell-variable-substitution-in-strings/) to concatenate strings in powershell.

Relatively newer but becoming popular one is format string where {0} {1} {2}.. are treated as placeholders inside string. 

Would be great if they would be highlighted as such.

**Comment by aeschli** [comment]
This issue was moved to PowerShell/vscode-powershell#1096
