### ISSUE TITLE
Formatting JSON removes blank lines

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#37422]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Create a file `foo.json` containing:
```json
{
    // part 1
    "x": 1,
    "y": 2,
    
    // part 2
    "a": 1,
    "b": 2
}
```
2. Format Document
3. The blank line is removed.

It would be nice if formatting JSON preserved blank lines (but still did things like inserting a space after a `:`).

**Comment by Spown** [comment]
would be not. formatting generally means removing extraneous whitespaces and adding missing ones where they are expected. a blank lines fall into the first category. I wouldn't mind having a user setting for this, but 👎 for making it a default behavior.

**Comment by octref** [comment]
This is indeed the behavior of the built-in json formatter. You can install prettier https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode which preserves the whitespace in JSON.
