### ISSUE TITLE
Panels: Activitybar is hectic when resizing sidebar in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37429]
Testing: #36906

Note: this might be related to https://github.com/Microsoft/vscode/issues/37427 because the initial steps are the same.

Steps to Reproduce:

1. see video for setup
2. once I resize the sidebar to the right I can see how the sidebar moves in and out of the activity bar stealing its space, but always recovering (video is not showing this super nicely, maybe you try to reproduce).

![panel-red2](https://user-images.githubusercontent.com/900690/32288070-15a92f90-bf33-11e7-8488-94ebebae55fe.gif)

**Comment by isidorn** [comment]
I can not repro this since I fixed #37427
Can you please try reproducing it again?

**Comment by bpasero** [comment]
Yeah seems to work fine now.
