### ISSUE TITLE
Issue reporter includes disabled extensions

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#37423]
- VSCode Version: Code - Insiders 1.18.0-insider (8deed535e26bc8ceebf83a9aa631580ebd610918, 2017-10-30T05:21:47.015Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.24

---

Steps to Reproduce:

1. Install an extension.
2. Set it to `Disable (always)`
3. Help -> Report Issues

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Would accept a PR here.

**Comment by shobhitchittora** [comment]
Hi @bpasero. I'd really like to work on a PR for this. Please guide me through as I'm new to Open Source projects.

**Comment by bpasero** [comment]
The [`ReportIssueAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/actions.ts#L869) is the one invoked here and the task is to hide extensions which are not enabled from the list.

**Comment by shobhitchittora** [comment]
@bpasero Thanks for pointing it out. I've fixed the issue and will create a PR.

**Comment by bpasero** [comment]
**Verify:** with no extensions disabled, with workspace extensions enabled, with global extensions disabled.
