### ISSUE TITLE
Can't open vscode, just message box

### ISSUE THREAD

**Issue by berbar** [Microsoft/vscode#37428]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.4
vscode-intelephense-client|bme|0.7.2
phpserver|bra|2.2.0
python|don|0.7.0
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
php-debug|fel|1.11.1
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
webpack|jer|2.0.2
luaide|kan|0.5.1
Lua|key|0.0.9
cpptools|ms-|0.14.0
vetur|oct|0.10.1
vscode-lua|tri|0.9.0

---

Steps to Reproduce:

1.when i carelessly set "terminal.integrated.fontSize" as "1", the vscode can't open. I must modify setting.json personally to fix it.
2.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This is fixed in the next version.
