### ISSUE TITLE
Find Files include path appears to be case sensitive on Windows

### ISSUE THREAD

**Issue by djabraham** [Microsoft/vscode#37424]
- VSCode Version: ***1.17.2***
- OS Version: ***Windows 10 Pro 10.0.15063***

Steps to Reproduce:

1. ***Put path with diff case than existing folder in the Find > files to include field***
2. ***Press enter***

Reproduces without extensions: Yes/No ***Yes***

***This cause some confusion. I would expect the case sensitivity of the Find tool to match the underlying OS. I checked for dupes, but couldn't find any prior to opening this. This seems to occur on the exclude path as well.***

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/10633

**Comment by dmitrivMS** [comment]
This is done.
