### ISSUE TITLE
Selection and hover not synchronised

### ISSUE THREAD

**Issue by peter-leonov** [Microsoft/vscode#37435]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-jest|Ort|2.4.2
vscode-docker|Pet|0.0.20
code-settings-sync|Sha|2.8.3
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.3.2
githistory|don|0.2.3
gitlens|eam|5.7.1
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
code-runner|for|0.7.4
haskell-linter|hoo|0.0.6
language-haskell|jus|2.4.0
azure-account|ms-|0.1.3
debugger-for-chrome|msj|3.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Do some extensive coding 🤣

Neither closing the tab, nor moving cursor, nor adding more lines or deleting some text helped, only restarting the VSCode application. Had this bug only once in 3 months.

Reproduces without extensions: bug gone after restart.

![screen shot 2017-10-20 at 09 01 25](https://user-images.githubusercontent.com/57961/32292614-f86170a6-bf40-11e7-9cba-6b6fc4704be7.png)

**Comment by jrieken** [comment]
@peter-leonov Your screen shot doesn't show IntelliSense but the hover. Is that what you mean? Is this JavaScript or TypeScript?

**Comment by peter-leonov** [comment]
@jrieken, yes, sure, the hover. This is JavaScript.

**Comment by alexandrudima** [comment]
@peter-leonov please let me know if you have any concrete steps. I cannot reproduce.
