### ISSUE TITLE
Middle clicking a tab to close it changes the cursor

### ISSUE THREAD

**Issue by jm-mwi** [Microsoft/vscode#37433]
When middle-clicking a tab to close it. The cursor toggles between the multi-directional (up/down/left/right) cursor. When you click on another tab to be closed you get the standard cursor again.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-devdocs|akf|1.0.1
project-manager|ale|0.22.0
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
laravel-goto-view|cod|1.1.2
bracket-pair-colorizer|Coe|0.10.10
gitlens|eam|5.7.1
php-debug|fel|1.11.1
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
vscode-import-formatter|hen|0.1.8
composer|ika|0.5.0
vscode-php-snippets|jar|0.0.9
php-namespace-resolver|Meh|0.8.0
code-beautifier|mic|1.7.2
vscode-todo-parser|min|1.9.1
vs-deploy|mkl|10.0.0
azure-account|ms-|0.1.3
php-docblocker|nei|1.3.2
laravel-blade|one|1.9.0
laravel5-snippets|one|1.3.4
vscode-docker|Pet|0.0.20
material-icon-theme|PKi|2.2.4
gi|rub|0.2.11
laravel-artisan|rya|0.0.8
highlight-matching-tag|vin|0.4.4
vscode-wakatime|Wak|1.1.21
vscode-todo-highlight|way|0.5.11
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Middle click an open tab

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16690

**Comment by bpasero** [comment]
@jm-mwi would you be willing to try out something by changing the source? The steps to build VS Code are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

I can not reproduce the middle-click scroll issue so I am searching for volunteers.
