### ISSUE TITLE
Inconsistent freezing when switching applications

### ISSUE THREAD

**Issue by juliusbartolome** [Microsoft/vscode#3743]
Hi,

I am new here in github, so my apologies.

I am getting frequent freezes when switching from code to other applications. It takes like 2 - 5 seconds freeze. I don't experience it with other applications. I tried uninstalling it on safe mode then reinstall it but still no good.

I hope you can give me some help with this, it makes the vs code useless to me :(

**Comment by bpasero** [comment]
@juliusbartolome is Code freezing, the app you are jumping to or the OS in general? Do you have extensions installed? Do you have auto save configured to save on focus lost?

**Comment by juliusbartolome** [comment]
I tried it now and it seems to be OK for now.  I will keep an eye on it. Code started freezing when I installed the latest update from the 0.10.8.

I am using Microsoft Windows 10 Enterprise (10.0.10240 Build 10240)
Extension/s installed:
 * Angular 1 JavaScript and TypeScript Snippets (0.1.15) by JohnPapa

Code is freezing when I am focusing on and off.

My auto save is configured off.

**Comment by bpasero** [comment]
Ok keep us posted, thanks.

**Comment by juliusbartolome** [comment]
Hi, I saw the main issue. I tried using the G-Sync functionality from Nvidia, I enabled it to run for windowed and fullscreen mode then it started the hang thing. The issue can be fixed once I clean install the nvidia driver using [https://www.google.com.ph/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjXyqu72tTLAhXBKZQKHWPQAscQFggZMAA&url=http%3A%2F%2Fwww.guru3d.com%2Ffiles-details%2Fdisplay-driver-uninstaller-download.html&usg=AFQjCNEJ9nAYe5bakSWLix-qMCQn0Fvqbw](Display Driver Uninstaller) in safe mode. Hope this helps.
