### ISSUE TITLE
Breakpoints not working with node v8.8.1 and v8.9.0

### ISSUE THREAD

**Issue by ggprod** [Microsoft/vscode#37431]
- VSCode Version: 1.17.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1.  Attempt to debug a Node service running node v8.8.1 or v8.9.0 in vscode with the launch config (using the Launch Program)
 {
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/src/server.js"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Port",
      "address": "localhost",
      "port": 5858
    }
  ]
}
2.  Set breakpoints in the code.  The breakpoints are not hit when using the service

I found that I can hit the breakpoints if I run node --inspect-brk=5858 src/server.js and connect with Chrome DevTools for Node. 

I can also hit the breakpoints if I run the same command above, and then connect in vscode using the 'Attach to Port' (although I have to restart the service using the vscode debugger before the breakpoints will hit)

Reproduces without extensions: Yes/No

**Comment by mherodev** [comment]
I am experience an issue that is likely related:

Automatic processId detection isn't working in Node 8.8.1 (upgraded from 6.11.0), e.g.

The following configuration attaches every time (there's only one pid in the list), however it doesn't prompt again on restart so it's clunky to use with our restarting server as the old pid will be invalid post-restart.

```
  {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "protocol": "inspector",
      "restart": true,
      "processId": "${command:PickProcess}"
    }
```

In contrast, the following config doesn't work and will toast the following error:

```
  {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "protocol": "inspector",
      "restart": true
    }
```

`Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFU...`

Note: This will appear to work once if it's configured and run after the PickProcess is successfully run one time as it seems to default to the previously used processId.

As for running with `--inspect`, this is our grunt task:

```
      server: {
        options: {
          args: process.argv,
          inspect: true,
          port: '<%= config.server.port %>',
          script: 'server.js'
        }
      },
```

Any help is greatly appreciated!

Best
Michael

**Comment by auchenberg** [comment]
@ggprod Can you try to set `trace: "verbose"` and share the output in here? I just validated a simple Node app with Node 9.0.0 and Node 8.9.0 and things seems to work for launch and attach.

**Comment by ggprod** [comment]
@auchenberg Sure, here it is attached
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1437943/vscode-node-debug2.txt)

**Comment by auchenberg** [comment]
Based on the log it looks like you are trying to set a breakpoint in `/Users/markpevec/Projects/tealbook/auth-service/src/patch-router.js

```
From client: setBreakpoints({"source":{"path":"/Users/markpevec/Projects/tealbook/auth-service/src/patch-router.js","name":"patch-router.js"},"lines":[581],"breakpoints":[{"line":581}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
SourceMaps.setBP: /Users/markpevec/Projects/tealbook/auth-service/src/patch-router.js can't be resolved to a loaded script. It may just not be loaded yet.
```

Which later is resolved

```
← From target: {"method":"Debugger.breakpointResolved","params":{"breakpointId":"/\\/Users\\/markpevec\\/Projects\\/tealbook\\/auth-service\\/src\\/patch-router\\.js/:580:0","location":{"scriptId":"1103","lineNumber":580,"columnNumber":19}}}
To client: {"seq":0,"type":"event","event":"breakpoint","body":{"reason":"new","breakpoint":{"id":1000,"verified":true,"line":581,"column":20}}}
```

So it looks like we indeed set the breakpoint when the file is loaded, but execution might have already have happened once we have connected to the Node process? Is this a route callback? Code running on boot?

If you can share a demo project/example if would make debugging much easier.

**Comment by ggprod** [comment]
yes, it does seem to be something specific to our service.  When I created a simple test express service the breakpoints worked correctly.  I also see the breakpoints work correctly if I set them early enough in our service code.  I'll see if I can get authorization to share some of our project code

**Comment by ggprod** [comment]
It seems like in our service the breakpoints are not being hit after any network calls.  Most of our network calls are made using Google cloud client libraries that connect to our GCP project so you would not be able to try to reproduce that without access.  It looks like there may be some dependency problem related to these client libraries

**Comment by ggprod** [comment]
Apologies, after some debugging it appears the Google cloud debug agent (to allow debugging deployed google cloud apps) is causing the problem.  When I remove it from our service, breakpoints work normally again.  You can close this issue and I'll open one at https://github.com/GoogleCloudPlatform/cloud-debug-nodejs

**Comment by auchenberg** [comment]
Interesting find @ggprod, thanks for clarifying this. This is the first report of stack driver causing problems. I'll close the issue for now, and we'll see if other have similar problems.
