### ISSUE TITLE
New Window command positions the new window slightly off screen

### ISSUE THREAD

**Issue by kpatrick** [Microsoft/vscode#37437]
- VSCode Version: 1.17.1
- OS Version:  Microsoft Windows [Version 10.0.14393]
- Dual monitor setup.  Display one is 1920x1080. Display two is 1920x1200.  Display two is set above display one.

Steps to Reproduce:
1. Have a VSC window open in display two
2. Select File > New Window
3. Notice that the new window opens in display two and is positioned such that the "Welcome - Visual Studio Code" is off screen. This makes the window hard to grab and move.  A workaround is to slightly adjust the bottom right corner which redraws the window properly.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@kpatrick 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
