### ISSUE TITLE
VSCode doesn't seem to detect that NPM is installed

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#37436]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.2
githistory|don|0.2.3
jquerysnippets|don|0.0.1
python|don|0.7.0
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
code-runner|for|0.8.2
docthis|joe|0.6.0
mssql|ms-|1.2.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
team|ms-|1.122.0
debugger-for-edge|msj|0.4.1
vscode-docker|Pet|0.0.20
vscode-icons|rob|7.17.0
addDocComments|ste|0.0.8
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.12.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Install NPM
2. Check NPM installed via command 'NPM -v'
3. VSCode tells you that you don't have NPM installed and checking settings confirms no detection or path.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Have you tried following the suggestions from the docs: https://code.visualstudio.com/Docs/languages/javascript#_fixing-npm-not-installed-warning-for-automatic-type-acquisition

**Comment by mjbvz** [comment]
Closing
