### ISSUE TITLE
cursor thickness for "line" and "thin-line" is the same.

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#37439]
Setting the setting "editor.cursorStyle" to "line"  or "line-thin" results in the same thickness of cursor.

"line-thin" should be the current 1 pixel width, and "line" should be 2 pixel width.

**Comment by octref** [comment]
Can you provide info on which version of VS Code and what OS are you using?

**Comment by safield** [comment]
VSCode Version 1.17.2
OS: Windows 10 version 10.0.10586

**Comment by alexandrudima** [comment]
I have just checked on Windows 10. For me, there is a clear difference:

![image](https://user-images.githubusercontent.com/5047891/32365812-beea6c06-c07b-11e7-9bbc-24e60ccd6762.png)

![image](https://user-images.githubusercontent.com/5047891/32365831-d0cd10a4-c07b-11e7-915e-e5247ca81250.png)

Are you perhaps using other settings such as `zoomLevel` or having some sort of scaling at the OS level ?

**Comment by safield** [comment]
My zoom level is -1. At this level "line" and "line-thin" are the same. At zoom level 0 there is a noticeable difference as above.  So there is no bug. But I rather a limitation for my use case.

I would love to be able to have a thicker cursor at zoom -1. I think the a possible solution is to add a "line-thick" cursor setting.

Or could the cursor scaling be clamped when scaling is < 0? 

For now I will run scale level 0 and set my font smaller, but I like have the whole UI scale smaller as well. But I like a very prominent cursor.

**Comment by alexandrudima** [comment]
I can only recommend to never use `window.zoomLevel` for daily, professional usage. i.e. use it when projecting to a live audience and you need to zoom in for them to see something.

This feature is very buggy and we cannot really [workaround some things](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Azoom).

Almost all of our font sizes can be customized except perhaps the explorer font size and family. You can upvote that in #519
