### ISSUE TITLE
Automatic process attachment not working in Node 8.8.1

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#37434]
Automatic processId detection isn't working in Node 8.8.1 (worked previous until we upgraded from 6.11.0), e.g.

The following configuration attaches every time (there's only one pid in the list), however it doesn't prompt again on restart so it's clunky to use with our restarting server as the old pid will be invalid post-restart.

```
  {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "protocol": "inspector",
      "restart": true,
      "processId": "${command:PickProcess}"
    }
```

In contrast, the following config doesn't work and will toast the following error:

```
  {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "protocol": "inspector",
      "restart": true
    }
```

`Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFU...`

Note: This will appear to work once if it's configured and run after the PickProcess is successfully run one time as it seems to default to the previously used processId.

As for running with `--inspect`, this is our grunt task:

```
      server: {
        options: {
          args: process.argv,
          inspect: true,
          port: '<%= config.server.port %>',
          script: 'server.js'
        }
      },
```

Any help is greatly appreciated!

Best
Michael

**Comment by auchenberg** [comment]
@mherodev If your second launch config doesnt work, this means that your Node process started via Grunt isn't started with remote debugging enabled (--inspect). Can you validate how the Node process is started? The arguments, etc.. 

@roblourens When do try to enable remote debugging on an already running process? when `processId` is defined, right?

**Comment by roblourens** [comment]
> prompt again on restart so it's clunky to use with our restarting server as the old pid will be invalid post-restart.

Did it prompt after restart when you were using Node 6.11?

**Comment by roblourens** [comment]
Reading this again, I guess I'm not clear how your setup works. If `inspect: true,` in your grunt task starts the process in --inspect mode, then `processID` in your launch config is unnecessary. That's only needed to put the process into inspect mode.

If the process isn't started in debug mode, then `processID` is needed, but if the attached process dies, it doesn't ask again to select a process, and as far as I know, it never did that. Maybe we could make it work that way, if `"restart": true` and `processID` are set. But just starting the process in debug mode is much simpler.

**Comment by mherodev** [comment]
Thanks for all of the quick responses! Unsurprisingly, it was user-error on our part.

`inspect: true` is not a valid option to pass to `grunt-express-server`, the correct way to do this is `opts: ['--inspect']`.

**Comment by roblourens** [comment]
Got it, thanks for the follow up!
