### ISSUE TITLE
Wrong tokenization of extended scss class names

### ISSUE THREAD

**Issue by Croccifixio** [Microsoft/vscode#37444]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.0-16-generic

---

Steps to Reproduce:

1. Create a class rule in an SCSS file.
2. Extend the class using nesting and an `&`.
3. Begin the name of the extension to the class with 2 or more hyphens.
 
![screenshot from 2017-11-01 20-48-35](https://user-images.githubusercontent.com/2574697/32294457-8df95016-bf46-11e7-810c-ebf63fa74f8e.png)

Based on the above screenshot, `__element` is tokenized as `punctuation.definition.entity.css`, which I suppose is alright.

However, `--modifier` is tokenized as `variable.css` which can lead to unsightly styling issues if the two tokens are styled differently in a particular theme (see the screenshot above).

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
We appreciate it, that you wanna contribute, but please read the information in the file header:
https://github.com/Microsoft/vscode/blob/80efcf5fdee32f7249ad23011a2abc4254fc19de/extensions/scss/syntaxes/scss.json#L2-L6

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#241
