### ISSUE TITLE
vscode is monopolizing the cpu

### ISSUE THREAD

**Issue by farzonl** [Microsoft/vscode#37441]
vscode is monopolizing my cpu before it ever gets to the point of opening a document. I collected a dump. but had to upload it to google drive. please see [here](https://drive.google.com/open?id=0B1IqtavO96o8SnZ4N0JXZFFmN3M
)
![image](https://user-images.githubusercontent.com/1802579/32295329-53c872a4-bf1f-11e7-91eb-8c7f2ae42da8.png)

- VSCode Version: ia32-1.17.2.exe
- OS Version: Windows 7 x86 2GB

Steps to Reproduce:

1. open VScode
2.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Can you get more details about the process arguments? There are a few Code.exe processes but everyone does something different. Please follow this guide to reveal more details about the process: https://github.com/Microsoft/vscode/wiki/Performance-Issues#questions
