### ISSUE TITLE
New Updates Slows my System 

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#37445]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|2.2.4
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
vscode-todo-plus|fab|1.5.3
auto-rename-tag|for|0.0.14
icon-fonts|idl|1.8.2
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.4.0
vscode-todo-highlight|way|0.5.11

(3 theme extensions excluded)

---

The New update slows my system drastically. It make everything freeze while doing intense task like building or deleting files. I pointed the delete freeze issue before. 

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
If you open VS Code by `code --disable-extensions`, does it still slow down your system?

**Comment by prasanthnv** [comment]
now it feels much better. but not that great

**Comment by octref** [comment]
I suggest you keep an eye on html-class-suggestions, npm-intellisense and path-intellisense. Try disable one of them and see if it's the culprit. Some people have reported they can be slow on large workspaces.
