### ISSUE TITLE
Find in terminal highlight is off after emojis

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37440]
- Download the file from #35114 and `cat` it in the terminal
- Search "British"
- It's off by a couple characters

![image](https://user-images.githubusercontent.com/323878/32294595-d18bbbd6-bf03-11e7-8df5-23de118c2173.png)

**Comment by Tyriar** [comment]
Seems fine now, tested on macOS:

<img width="177" alt="screen shot 2018-06-21 at 3 45 24 pm" src="https://user-images.githubusercontent.com/2193314/41700080-28c2b3d8-756a-11e8-9583-7f2e49024f3c.png">
