### ISSUE TITLE
Ruby build task never finishes; must be manually terminated

### ISSUE THREAD

**Issue by bunchjesse** [Microsoft/vscode#37446]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 
- Ruby Version: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0

---

Steps to Reproduce:

1. Open the [attached folder](https://github.com/Microsoft/vscode/files/1435837/testcase.zip) in vscode
2. Run the default build action
3. After it finishes, run it again

Notice you must manually terminate the build action. This is not the case for normal shell scripts which terminate after the script is finished.

I would expect to be able to run the default build action again immediately after it finishes and not have to manually terminate the task.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/35752
