### ISSUE TITLE
"terminal.integrated.fontSize" should have a maximum value

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37455]
Testing #36370

Steps to Reproduce:

1. Open the integrated terminal
1. While trying to set: `"terminal.integrated.fontSize": 10`, accidentally enter `"terminal.integrated.fontSize": 1009`

**Bug**
![screen shot 2017-11-01 at 5 28 06 pm](https://user-images.githubusercontent.com/12821956/32304209-d692da5c-bf2a-11e7-9297-0ba9d394c051.png)

Terminal contents start leaking outside of the panel. I also think we should set a maximum terminal font size just as we do for the minimum terminal font size

**Comment by CoenraadS** [comment]
As a bit of polish the json schema could also include these ranges so a warning will appear in the settings panel.

**Comment by shobhitchittora** [comment]
Hi,
I'd like to take this Issue up and make a PR. Thanks in advance. 

PS: I'm new to Open Source and would like your support.

**Comment by Tyriar** [comment]
@shobhitchittora great! 😃 

There's already a minimum value ([see here](https://github.com/Microsoft/vscode/blob/af6b8302fae66a2898ac8180c98221892d6c765f/src/vs/workbench/parts/terminal/electron-browser/terminalConfigHelper.ts#L31)), we just need to find a good maximum and add it there. Right now I'm thinking somewhere between 20 and 30 should be the default as that's getting into the ridiculously large territory.

There are instructions for building the project here https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by shobhitchittora** [comment]
Hi @Tyriar. I've created a PR and would like your comments.

**Comment by roblourens** [comment]
Should it match the editor max font size? The editor has some max, not sure what it is, but I can now make the text much larger in the editor than the terminal.
