### ISSUE TITLE
Git Status Indicator effect whilst doing Sync Fetch on project open

### ISSUE THREAD

**Issue by 8bitbuffer** [Microsoft/vscode#37457]
Perhaps I'm missing something - but I often start coding after opening a folder and not seeing any remote commits in the bottom left corner.     Only to notice at a later time that I've now got Merge issues as there were remote commits not sync'd when I started o code.   

This happens because it's not obvious that VSCode is checking for remote commits for several seconds after you open the folder. 

Seems like the Git / SCM status in the bottom left should have an effect that makes it very obvious that the status is being fetched until it's displayed.   If the indicators flashed / red font or some "effect"  (including the Sync icon spinning) when you first open the folder so you know it's still working on fetching all the current status info.

Maybe it's just me.... but I get caught out by this frequently - and since the VSCode merge tools doesn't seem to be very easy to use (for me anyway) - I wonder why a simple effect as I've described isn't part of VSCode???

OR... have I missed something?? 

Steps to Reproduce:

1.  Open Folder of any existing project with Git / SCM 
2.  Watch Git Status info in bottom left of VSCode (ie:  Branch Name and Sync inco)
3.  With local and/or remote commits waiting to be sync'd - it takes several seconds (even longer on slow connection) for the Status to reflect if there are any remote commits.    I've often started to code - thinking there are none - only to see at a later point that there are remote commits to sync.  This wouldn't happen if the indicators flashed / red font or some "effect"  (including the Sync icon spinning) when you first open the folder so you know it's still working on fetching all the current status info.

Reproduces without extensions:  Yes

**Comment by joaomoreno** [comment]
#34684
