### ISSUE TITLE
File paths in build output and terminal only autodetect when terminal has scrolled.

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#37453]
- VSCode Version: Version 1.18.0-insider (1.18.0-insider)
- OS Version: macOS 10.13.2 beta

Steps to Reproduce:

1. open a project window.
2. open the integrated terminal.
3. `mkdir some_dir` (or use an existing dir with a source file in it).
4. `touch some_dir/some_file.txt` (or use existing).
5. Mouse over the file path (either the typed command or the output). It will not highlight.
6. Now press enter until the terminal scrolls, and then scroll back and try again.
7. Once the terminal has scrolled, then the paths will be recognized, showing an underline and tooltip "cmd+click to follow link" on mouseover. 

Path recognition in the terminal is a fabulous feature (it makes VSCode an IDE for any script that prints `path:line:col` messages), and it is a shame that it is broken for this common case!

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36072
