### ISSUE TITLE
CMD.EXE Console output from some commands gets cut off

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#37450]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
QML|bbe|1.0.0
file-templates|brp|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.2
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.3.2
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.14
code-sync|gol|2.5.0
rest-client|hum|0.16.0
redux-snippets|jam|0.0.2
docthis|joe|0.6.0
vscode-codemetrics|kis|1.10.0
vscode-todo|Mat|0.8.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.4.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.20
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.17.0
vscode-paste-and-indent|Rub|0.0.8
cmake|twx|0.0.17
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.11.0

---

Steps to Reproduce:

1. Have several Lambdas configured in Amazon Web Services
2. in VSCode in cmd.exe, run: aws lambda list-functions

Reproduces without extensions: Yes

----

When using shell cmd.exe, I have a AWS Lambda configuration that has 5 lambda functions configured.  When I attempt to enumerate them from cmd.exe within VSCode, the display output consistently cuts off somewhere within the 2nd to 4th section of output

````
@ D:\src\car\cloudformation-template
> aws lambda list-functions
{
    "Functions": [
        {
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "Version": "$LATEST",
            "CodeSha256": "MsVPrU5GX1RXdzPcfXamxS/AYKsgH9LRKq1kZum5vgA=",
            "FunctionName": "prod-lambdas-r-ProvisionProvision-YSGP0BP32HFA",
            "MemorySize": 128,
            "CodeSize": 931,
            "FunctionArn": "....",
            "Handler": "provision.handler",
            "Role": "....",
            "Timeout": 3,
            "LastModified": "2017-11-01T22:01:45.321+0000",
            "Runtime": "nodejs6.10",
            "Description": "Provision new certificates in IoT"
        },
        {
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "Version": "$LATEST",
            "CodeSha256": "z/gxpqvVEpLrvMIj6u9Ncg67yB1sE8fmK0y7Q6fiiAk=",
            "FunctionName": "prod-lambdas-r-NotifierStackNotifier-NNLXTRJY8EMR",
            "MemorySize": 128,
            "CodeSize": 6070818,
            "FunctionArn": "....",
            "Handler": "notifier.handler",
            "Role": "...",
            "Timeout": 30,
            "LastModified": "2017-11-01T22:01:46.874+0000",
            "Runtime": "
````

Note that I have censored out some of the data with "...." so that others do not have info necessary to access my lambdas or account. :-)  

It's not consistently doing it at the same place in each run, and it does not do it if I run it in either cmd.exe in a normal Command Prompt window (or in a ConEmu window), nor does it do it from within powershell.exe or (msys git) bash.exe, in VSCode.

I don't see anything obviously weird in the output that would seem to be triggering it.

**Comment by ericblade** [comment]
Also remains in 1.18.0

**Comment by ericblade** [comment]
Remains in 1.18.1, also affects Powershell  (why Powershell started on this particular window, I have no idea)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
