### ISSUE TITLE
Source control left file Chinese garbled

### ISSUE THREAD

**Issue by michaelllh** [Microsoft/vscode#37456]
- VSCode Version:1.17.2
- OS Version:Win7 

Steps to Reproduce:

1.click Source Control in vscode
2.left file shows Chinese garbled , the right file shows correct

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
@michaelllh can you provide more info, for example, code snippet, screenshots/gifs to help troubleshoot?

**Comment by michaelllh** [comment]
It seem being solved in newest version 1.18.0.

And Thanks for the reply.
