### ISSUE TITLE
Typescript errors under Angular application don't disappear until I close and reopen files

### ISSUE THREAD

**Issue by waelkdouh** [Microsoft/vscode#37463]
I notice that VS code doesn't update the state of errors under my angular 2 application except after closing and reopening typescript files. It is random as sometimes fixing a typescript error removes the red squiggly and sometimes it doesn't. This issue is limiting my productivity as a lot of times I think I have an error in my angular 2 application to find out that my application is fine and all I had to do was close and reopen the file under question.

**Comment by mjbvz** [comment]
Does this reproduce with VS Code insiders? What if you disable all installed extensions?
