### ISSUE TITLE
run task:   too slow to display task list

### ISSUE THREAD

**Issue by xingzhuo1983** [Microsoft/vscode#37460]
- VSCode Version: 1.17
- OS Version:  windows 10

Steps to Reproduce:
1.activate "Run Task" menu
2. too long delay to display the task list
3. maybe we could display the recently used tasks imediately and load the rest
4. task is changed according to some json change or ...? maybe we could refresh the task list at different moments rather than activating.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/32467.
