### ISSUE TITLE
Explorer doesn't display some  files

### ISSUE THREAD

**Issue by roojay520** [Microsoft/vscode#37465]
- VSCode Version: Code 1.17.2
- OS Version: Windows 10.0.16299

Steps to Reproduce:

1. Open a project and new a dist fiile.
![jhgjg](https://user-images.githubusercontent.com/11495164/32308668-04ba7204-bfc2-11e7-9e90-90709e19b49c.png)
2. Use Webpack to generate some files(such as js, css) into the dist,the dist file doesn't display.
![hgjg](https://user-images.githubusercontent.com/11495164/32308767-830a3bbc-bfc2-11e7-97b3-ef3501a58076.png)

**Comment by roojay520** [comment]
Often need to click the Refresh button, it's too much trouble for the automation of me.

**Comment by bpasero** [comment]
@roojay520 how are your settings looking like?

**Comment by roojay520** [comment]
@bpasero  Which setting you mean? (webpack setting or vscode setting?)

**Comment by bpasero** [comment]
@roojay520 vscode

**Comment by roojay520** [comment]
This should be a ui display error
