### ISSUE TITLE
_generateCommandsDocumentation no longer autogenerates several complex commands

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#37468]
- VSCode Version: 1.18 Insiders
- OS Version: Windows 10

When running the _generateCommandsDocumentation command to autogenerate the complex command API used in docs/extensionAPI/vscode-api-commands.md, several commands are missing:
cursorMove,
editorScroll,
reviewLine,
editor.fold
editor.unfold
moveActiveEditor

**Comment by jrieken** [comment]
@alexandrudima Did these command change, like rename or late registration?

**Comment by jrieken** [comment]
Thanks for reporting @gregvanl
