### ISSUE TITLE
feature request:  custom task hot keys

### ISSUE THREAD

**Issue by xingzhuo1983** [Microsoft/vscode#37462]
hopefully we could define hotkeys to run  tasks 
(tasks are defined at project level, but we could provide some task names, such as build/lint/start/compile  and assign hotkeys to these names)

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
Here you go: https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks
