### ISSUE TITLE
Ruby templating syntax highlighting problem

### ISSUE THREAD

**Issue by hanxue** [Microsoft/vscode#37469]
- VSCode Version: 1.17.2
- OS Version: MacOS 10.10.5

Steps to Reproduce:

1. Open ruby code with templating. For example, https://gist.github.com/hanxue/46cb83e532792b3ec7b83a43372d6c7f
2. Ruby code will not be highlighted correctly

![image](https://user-images.githubusercontent.com/760008/32310369-bda45a64-bfcc-11e7-8667-8030ea67983f.png)

Reproduces without extensions: Yes

**Comment by octref** [comment]
We only bundle basic ruby language support. For advanced Ruby language support you can try: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby and fill issues for them.
