### ISSUE TITLE
Markdown Fenced PHP Code Block is Not Syntax Highlighted

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#3746]
When creating a code fence, the block doesn't get colored as code (stays white), but it does display as code in the preview.

    ```php
    <?php
    //Hello World
    echo ('Hello World!');
    ?>
    ```

If I tab the code with 4 spaces it does color it properly.

Here is an example:

![screenshot from 2016-03-05 16-45-51](https://cloud.githubusercontent.com/assets/1571806/13551042/cb698868-e2f1-11e5-90dc-6d83d7600fc8.png)

**Comment by bpasero** [comment]
I can still reproduce with our new extension.

**Comment by rebornix** [comment]
Firstly we missed the fenced code syntax detecting in markdown tmlanguage, just added it https://github.com/kieferrm/vscode-markdown/commit/bd395e1fdd02e99c169f8bef9c11f47bac0a42a0 .

But we still have problem with plist injecting, which makes the inner code highlighting doesn't work. I'm looking into it right now.

**Comment by kieferrm** [comment]
Adding fenced code for php was necessary but did not fixed the php highlighting issue.

**Comment by Stanzilla** [comment]
Same issue for lua

**Comment by mjbvz** [comment]
@Stanzilla Lua highlighting seems to work now:

![screen shot 2016-11-10 at 6 15 56 pm](https://cloud.githubusercontent.com/assets/12821956/20202126/be615eee-a771-11e6-91a1-ae1043d6a160.png)


Also, the indented code block version is now being correctly not colored:

![screen shot 2016-11-10 at 6 17 59 pm](https://cloud.githubusercontent.com/assets/12821956/20202160/1156dbec-a772-11e6-9468-5e7bac41ec32.png)

The main bug is still that the fenced php code block is not syntax highlighted. It is unclear what is different about the php language here. The fenced php code block is being detected and parsed properly, but the php grammar does not seem to be applied. Updating bug title to reflect this being specific to php (at least to my knowledge)
