### ISSUE TITLE
Terminal -> Unproportional maximize button

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#37476]
- VSCode Version: 15449873f130d7f3e5604a1cac94f32a1f15f604
- OS Version: Win 10

![bottom](https://user-images.githubusercontent.com/9638156/32313174-89a295c4-bfb2-11e7-95f0-da47cd07f398.png)
![left](https://user-images.githubusercontent.com/9638156/32313178-8c9bab80-bfb2-11e7-9334-745e8b1e3f74.png)

Reproduces without extensions: Yes

**Comment by octref** [comment]
@isidorn Don't know if this is related to the vertical panel you were doing.

@Tyriar fyi

**Comment by usernamehw** [comment]
Was fixed at some point.
