### ISSUE TITLE
While commenting internal JavaScript (embedded in the html document), VSCode actually puts HTML comments instead of JavaScript comments.

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#37471]
In the following example,

```
<body>

<script>
  let something = "Something";
  alert(something);
</script>
</body>
```

when I select the two lines inside script tags and press the _**toggle comment shortcut**_, I want to comment it as JavaScript as follows,
```
<body>

<script>
  // let something = "Something";
  // alert(something);
</script>
</body>
```

but VSCode comments it as HTML as follows,

```
<body>

<script>
  <!-- let something = "Something";
  alert(something); -->
</script>
</body>
```

**Comment by aeschli** [comment]
I can't reproduce that. I select line 4 and 5 , press `CTRL + /` and this results in // being added.
- is the editor in HTML mode (check the status bar, on the right)
- do you maybe have an extension installed that replace the HTML mode configuration?
