### ISSUE TITLE
为什么不能输入问号呢？

### ISSUE THREAD

**Issue by wosqqa** [Microsoft/vscode#37477]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.10.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please use English to report issues and include reproducible steps.
