### ISSUE TITLE
Switching code while VSCode Opens doesn't re-index

### ISSUE THREAD

**Issue by raybooysen** [Microsoft/vscode#37470]
- VSCode Version:  1.17.0
- OS Version: Windows 10

Steps to Reproduce:

1. Check out some typescript code and open VSCode
2. Let VSCode index until complete
3. Switch to another branch where the code is substantially different
4. Notice that VSCode doesn't always re-index so there are many syntax errors shown

Reproduces without extensions: Yes

This is an interesting case where switching branches and there is change, the IDE doesn't always pick these up and re-index.  This means that having a file open will show syntax errors.  If you go to the classes/files where the changes have taken place, then the syntax errors disappear.

**Comment by mjbvz** [comment]
Does this reproduce in VS Code insiders builds?

**Comment by raybooysen** [comment]
No.
