### ISSUE TITLE
Display encoding incorrectly

### ISSUE THREAD

**Issue by StandAlong** [Microsoft/vscode#37474]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
cpptools|ms-|0.14.0
PowerShell|ms-|1.5.0
java|red|0.12.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.Press "encoding" at the right bottom corner
2.Press "Reopen with encoding"
3.Choose an encoding mode
4.Reopen "Reopen with encoding" list

Then, you'll find that the item which is highlighted is not the choosen item or the working item.

Reproduces without extensions: Yes

**Comment by octref** [comment]
I can't repro it. This might already be fixed in insiders. Can you give it a try? https://code.visualstudio.com/insiders/
