### ISSUE TITLE
nodejs.  debug bugs 

### ISSUE THREAD

**Issue by edward12699** [Microsoft/vscode#37478]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-beautify|tai|0.3.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. start debug
2. 
![image](https://user-images.githubusercontent.com/14276262/32315169-0bc0b1de-bfe6-11e7-8a82-87c4d17e11de.png)

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
You found a bug on the Node JS debugger?
Please create an issue on repository for [nodejs-debugger](https://github.com/Microsoft/vscode-node-debug).
