### ISSUE TITLE
shift+alt+f is bound to both editor.action.formatDocument and editor.action.dirtydiff.next

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#37472]
- VSCode Version: 1.18 Insiders
- OS Version: Windows 10

Seems very problematic to try and use the shift+alt+f keybinding to go to the next editor inline diff. Usually just formats the document. Tried on both json and markdown files.

**Comment by joaomoreno** [comment]
I changed this yesterday to (<kbd>Shift</kbd>)<kbd>Alt F3</kbd>
