### ISSUE TITLE
Regex pattern not recognized

### ISSUE THREAD

**Issue by fultonm** [Microsoft/vscode#3747]
This test case does not work for Regex CTRL+F find in VS Code
https://regex101.com/r/hX5yB0/1

**Comment by vilic** [comment]
This works for me though.

![image](https://cloud.githubusercontent.com/assets/970430/13559012/e23ba3c0-e448-11e5-9ce8-aba3c2246aca.png)

**Comment by fultonm** [comment]
Oops. I was including doing /<\/value>.*?<\/value>/g
My mistake, thank you for looking into this.
