### ISSUE TITLE
Memory usesage grows indefinately when searching for files

### ISSUE THREAD

**Issue by demestav** [Microsoft/vscode#37487]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Mount a directory using sshfs
2. Open the mounted directory
2. Use CTRL+P and search for a file
3. The memory consumption of `/usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=searchService` process keeps growing indefinitely until the system hangs

Reproduces without extensions: Yes

Possibly related to  #36005 and #37013

**Comment by roblourens** [comment]
Probably related somehow. 

- Are you searching a very large folder?
- Are there lots of symlinks (or a symlink to `/` like in #37013)
- Are some files or folders on the sshfs under different permissions, such that, the user code runs under doesn't have permission to access them?
- Can you try with the insiders build?
