### ISSUE TITLE
typescript.tsdk has confusing documentation and missing validly checks

### ISSUE THREAD

**Issue by scharf** [Microsoft/vscode#3748]
When a typescript file contains a [string literal type](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types):

``` ts
let foo: "foo" | "bar" = "foo";

```

VSCode shows errors:

![foo_ts_-_simple-todos-react](https://cloud.githubusercontent.com/assets/3731059/13551436/2eb22752-e33a-11e5-8748-c3a43dc858c8.jpg)

For example the [react ambient definition uses string literal types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f0f926a12026287b5a4a229e5672c01e7549313/react/react.d.ts#L507). Everything below the error is invalid.

Using typescript 1.8 as described in https://github.com/Microsoft/vscode/issues/3723#issuecomment-192342749 does not help.

![err](https://cloud.githubusercontent.com/assets/3731059/13551459/f9081ef8-e33a-11e5-8e6f-e5a4da1f4d5c.jpg)

**Comment by scharf** [comment]
It turns out that I misconfigured `typescript.tsdk`. The description of this feature says:

> Specifies the folder path containing the tsserver and lib*.d.ts files to use.

I accidentally installed [`tsc`](https://www.npmjs.com/package/tsc) which is deprecated. But it contains everything the needed (both `tsserver` and `lib*.d.ts`):

```
$ ls -l ./node_modules/tsc/bin
total 22448
-rw-r--r--  1 scharf  staff    51201 Jun 19  2015 lib.core.d.ts
-rw-r--r--  1 scharf  staff   215410 Jun 19  2015 lib.core.es6.d.ts
-rw-r--r--  1 scharf  staff   707911 Jun 19  2015 lib.d.ts
-rw-r--r--  1 scharf  staff   649085 Jun 19  2015 lib.dom.d.ts
-rw-r--r--  1 scharf  staff   761325 Jun 19  2015 lib.es6.d.ts
-rw-r--r--  1 scharf  staff     9176 Jun 19  2015 lib.scriptHost.d.ts
-rw-r--r--  1 scharf  staff   148005 Jun 19  2015 lib.webworker.d.ts
-rwxr-xr-x  1 scharf  staff       40 Jun 19  2015 tsc
-rw-r--r--  1 scharf  staff  1375827 Jun 19  2015 tsc.js
-rwxr-xr-x  1 scharf  staff       45 Jun 19  2015 tsserver
-rw-r--r--  1 scharf  staff  1982082 Jun 19  2015 tsserver.js
-rw-r--r--  1 scharf  staff   242783 Jun 19  2015 typescript.d.ts
-rw-r--r--  1 scharf  staff  2539283 Jun 19  2015 typescript.js
-rw-r--r--  1 scharf  staff   242510 Jun 19  2015 typescriptServices.d.ts
-rw-r--r--  1 scharf  staff  2539283 Jun 19  2015 typescriptServices.js
```

So I used  `"typescript.tsdk": "./node_modules/tsc/bin"` and vscode does not complain.

I also installed `typescript` but no folder seems to contain both `tsserver` and `lib*.d.ts`:

```
 ls -l node_modules/typescript/lib/
total 28048
-rw-r--r--  1 scharf  staff      270 Feb 22 23:31 README.md
-rw-r--r--  1 scharf  staff   179761 Mar  2 02:25 lib.core.d.ts
-rw-r--r--  1 scharf  staff   229767 Mar  2 02:25 lib.core.es6.d.ts
-rw-r--r--  1 scharf  staff   233538 Mar  2 02:25 lib.core.es7.d.ts
-rw-r--r--  1 scharf  staff   730725 Mar  2 02:25 lib.d.ts
-rw-r--r--  1 scharf  staff   543339 Mar  2 02:25 lib.dom.d.ts
-rw-r--r--  1 scharf  staff   780987 Mar  2 02:25 lib.es6.d.ts
-rw-r--r--  1 scharf  staff   784758 Mar  2 02:25 lib.es7.d.ts
-rw-r--r--  1 scharf  staff     9176 Mar  2 02:25 lib.scriptHost.d.ts
-rw-r--r--  1 scharf  staff    42106 Mar  2 02:25 lib.webworker.d.ts
-rw-r--r--  1 scharf  staff  1784817 Mar  2 02:25 tsc.js
-rw-r--r--  1 scharf  staff  2469004 Mar  2 02:25 tsserver.js
-rw-r--r--  1 scharf  staff    90361 Mar  2 02:25 typescript.d.ts
-rw-r--r--  1 scharf  staff  3174675 Mar  2 02:25 typescript.js
-rw-r--r--  1 scharf  staff    90347 Mar  2 02:25 typescriptServices.d.ts
-rw-r--r--  1 scharf  staff  3174675 Mar  2 02:25 typescriptServices.js



$ ls -l node_modules/typescript/bin
total 16
-rwxr-xr-x  1 scharf  staff  45 Feb 22 23:27 tsc
-rwxr-xr-x  1 scharf  staff  50 Feb 22 23:27 tsserver
```

However, if I specify "./node_modules/tsc/lib"`, which contains the `lib.*.d.ts` files, VSCode complains (which is actually good).

**Comment by scharf** [comment]
Changed title of issue form

> Support TypeScript 1.8 string literal types

to

> typescript.tsdk has confusing documentation and missing validly checks

**Comment by mjbvz** [comment]
We've updated how the tsdk setting is used and are updating the documentation for 1.9: https://github.com/Microsoft/vscode-docs/pull/811

**Comment by dbaeumer** [comment]
Played through the scenario today and there is not path entering involved anymore.
