### ISSUE TITLE
Pasting leads to crash

### ISSUE THREAD

**Issue by readonemohamed** [Microsoft/vscode#37489]
- VSCode Version: Code - Insiders 1.18.0-insider (15449873f130d7f3e5604a1cac94f32a1f15f604, 2017-11-02T06:22:24.153Z)
- OS Version: Linux x64 4.13.0-16-lowlatency
- Extensions: none
---

Steps to Reproduce:

1. opened a file
2. Pasted text from gedit.

**Comment by octref** [comment]
This doesn't sound right -- do you mind sharing the text you are pasting? What language are you pasting this in?

Also, if you do Help -> Developer Tools, are there any error messages over there?
