### ISSUE TITLE
VSCode freezes when scrolling

### ISSUE THREAD

**Issue by Mirovow** [Microsoft/vscode#37480]
- VSCode Version: 1.17.2
- OS Version: Windows 10 Home SIngle Language 1709
- Reproduces without extensions: Yes

VSCode freezes when I scrolling the workarea. It happens when I scrolling with the touchpad, but when I use the scrollwheel it's all right! It happens only in the VSCode. In other programms it's all right. I also discovered that after resizing the window of VSCode I can scroll the workarea whithout the freeze! Its magic!

**Comment by octref** [comment]
@bpasero Could be #35475, but I don't know if it's related to precision touchpad @kieferrm.

@Mirovow Can you try this comment and post output?
https://github.com/Microsoft/vscode/issues/35475#issuecomment-338383792

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612
