### ISSUE TITLE
the code are displaying in single line while saving the document. and it is destroying my code layouts.

### ISSUE THREAD

**Issue by dipendrashahithakuri** [Microsoft/vscode#37488]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
rails-migration-list|Mah|0.1.2
TriSys-Apex-Javascript-Snippets|Tri|1.2.0
vscode-wakatime|Wak|1.1.21
html-snippets|abu|0.1.0
vscode-css-formatter|aes|1.0.0
vscode-javascript-snippet-pack|aka|0.1.5
ruby-on-rails-snippets|ate|0.0.1
rails-project-navigator|bra|0.1.2
rails|bun|0.3.0
solargraph|cas|0.9.1
vscode-standardjs|che|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.2
pgsql|dou|0.0.8
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
haml|gro|0.0.2
ruby|gro|0.0.6
rails-nav|hjl|0.0.3
ruby-linter|hoo|1.0.0
pgsql-html|hub|0.0.7
search-node-modules|jas|1.2.0
Angular1|joh|0.2.0
node-module-intellisense|lei|1.4.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.10
ruby-symbols|mig|0.1.5
js-atom-grammar|ms-|0.1.14
rails-run-spec-vscode|nok|0.1.0
vscode-ruby-ctags|oto|1.4.1
Ruby|reb|0.15.0
ruby-snippet|rob|0.1.0
rails-go-to-spec|spo|0.0.1
rails-latest-migration|tmi|0.0.1
haml|vay|1.0.1
simple-ruby-erb|vor|0.2.1
nodejs-extension-pack|wad|0.1.9
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
You probably have `editor.formatOnSave: true`. You can turn it off, or try to report a bug to the formatter you are using.
