### ISSUE TITLE
That's we need

### ISSUE THREAD

**Issue by flymeonce** [Microsoft/vscode#37485]
- VSCode Version: 1.17 
- OS Version:

Steps to Reproduce:

1.when i used the function of git ,like git pull, i need to see what message has changed! thank you!!!

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Do you mean with that, that you want to see the new commits? 
For that you could use [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory).

**Comment by flymeonce** [comment]
no,the Changes in file content，like this 

![image](https://user-images.githubusercontent.com/30708895/32318798-5a6badae-bff3-11e7-9cca-ef6e2b27f5cd.png)
