### ISSUE TITLE
Go to definition goes to the wrong place

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37483]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L667

Try <kbd>Cmd</kbd> clicking on `SCMMenuItemActionItem`. It should go to 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L61

but goes to 

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/browser/menuItemActionItem.ts#L99

**Comment by mjbvz** [comment]
This is correct. For new expressions, go to definition jumps to the constructor. As `SCMMenuItemActionItem` does not implement its own constructor, we open the parent class constructor. 

`Go to type definition` will jump to the class itself.

**Comment by joaomoreno** [comment]
I understand why it happens. But I don't think it is the correct behaviour. It should jump to `SCMMenuItemActionItem` regardless of whether it has overridden the ctor.

**Comment by mjbvz** [comment]
No, this really is how the feature is designed to work. For `new` expression we always jump to the constructor definition itself. This lookup behaves like it would for any overridable method in that is jumps to the actual implementation of that method instead of to a subclass
