### ISSUE TITLE
About Check for Updates.

### ISSUE THREAD

**Issue by cooper1x** [Microsoft/vscode#37486]
- VSCode Version: Code 1.17.1 **[Unsupported]** (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
auto-rename-tag|for|0.0.14
beautify|Hoo|1.1.1
vscode-icons|rob|7.17.0
background|sha|1.1.16
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.The latest version is 1.17.2, but I can't update, because there is no "check for updates" option 
2.I use the zip version,How can I use the check for updates function?

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
You are using https://marketplace.visualstudio.com/items?itemName=shalldie.background which modifies VS Code internal files so you lost ability to update automatically.
You can open an issue for that extension, or re-install VS Code.
