### ISSUE TITLE
The terminal are closed when I try to close the window and click Cancel button.

### ISSUE THREAD

**Issue by zuoez02** [Microsoft/vscode#37481]
- VSCode Version: 1.17.2
- OS Version: macOS High Sierra 10.13

Steps to Reproduce:

1. Create a new file and type something but do not save the file
2. Click new terminal
3. Click the button on the left-top corner of the window to close the window
4. Click 'Cancel' button to stop closing the window.
5. The terminal is already closed.

Reproduces without extensions: Yes

When I opened too many of code windows, I close them one by one by click the button on the left-top corner. But I made a mistake that I tried to close a window which should not be closed. Something important was on the terminal and something not saved yet. I click the cancel button but the terminal  has gone.

**Comment by hun1ahpu** [comment]
Doesn't seem to repro on Windows 10, vscode 1.17.2
Is it Mac only issue?

**Comment by baloran** [comment]
Same Here, on macOS Sierra 10.12.5

**Comment by Tyriar** [comment]
I expect this to happen on all platforms.

**Comment by zuoez02** [comment]
@Tyriar  Ubuntu 14.04 and code 1.17.2 not reproduce. Maybe  the problem is only on macOS

**Comment by Tyriar** [comment]
This should be fixed in the upcoming version
