### ISSUE TITLE
Decorations jumping on next line when line deleted

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37482]
Open settings, search for something that has results in your settings.json. Delete a line with a decoration, notice the decoration jumping on the following line.

![decorationjump](https://user-images.githubusercontent.com/1926584/32316486-b16aa4f4-bfb0-11e7-905d-70ae927280de.gif)

**Comment by sandy081** [comment]
I suspect, I am not updating the decorations on content change. These decorations are coming from Settings Search.

**Comment by sandy081** [comment]
Unassigning @alexandrudima. Will investigate from my side first.

**Comment by sandy081** [comment]
Yes, Confirmed that I am not updating decorations on change. Also, this is not a regression. Moving to November.
