### ISSUE TITLE
View on the right: Restore arrow doesn't work

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37499]
Version 1.18.0-insider (1.18.0-insider)
15449873f130d7f3e5604a1cac94f32a1f15f604
2017-11-02T06:07:42.390Z

MacOS

- Open the terminal on the right side
- Click on the expand arrow: View expands
- Click on the restore arrow. Nothing happens

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37491
