### ISSUE TITLE
"git pull from" should also show remote branches

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#37490]
On "GIt: Pull From..." command, There isn't remote branches list. We can only type the branch name..

![image](https://user-images.githubusercontent.com/13297000/32319352-ee8fe468-bfc2-11e7-95e4-eccc93578035.png)

**Comment by misoguy** [comment]
I'd like to take on this if no one else it on it yet 😄

**Comment by itamark** [comment]
@misoguy go for it!

**Comment by moguzozcan** [comment]
Hello,
Is this issue assigned already? If not I could work on that?

**Comment by misoguy** [comment]
@moguzozcan You can work on it if you want 👍 I didn't have much time this week 😞

**Comment by moguzozcan** [comment]
Ok I'll take this issue if that is ok, you can assign me. @itamark could you give me any hints since this is my first time in vscode. Thank you

**Comment by misoguy** [comment]
@moguzozcan I'm not authorized to assigning but I could give you some hints.
You should probably checkout `extensions/git/src/commands.ts` [here](https://github.com/Microsoft/vscode/blob/b3e6d5bb039a4a9362b52a2c8726267ca68cf64e/extensions/git/src/commands.ts#L1241).
I have roughly implemented a working version on my local pc but I thought it would be better to give someone new a chance :)

**Comment by moguzozcan** [comment]
@misoguy Thanks for your help :) I've started work on it.

**Comment by misoguy** [comment]
@moguzozcan Any updates on this issue?

**Comment by eladcandroid** [comment]
@moguzozcan Do you need some help?

**Comment by moguzozcan** [comment]
I am having problems while trying to debug the git extension. I am looking into it but it goes slowly, I may drop it maybe?

**Comment by misoguy** [comment]
@moguzozcan If you are going to drop it, I'll work on it from tomorrow :)

**Comment by moguzozcan** [comment]
@misoguy I think it's better you'll take this issue :)

**Comment by misoguy** [comment]
Understood :)

**Comment by Dozed12** [comment]
Hello, mind if I do a pull request on this? I think I have a solution for it.

**Comment by Dozed12** [comment]
Thank you. I guess that's a good sign 👍

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/39216
