### ISSUE TITLE
Panel: let the maximize action steal space from the sidebar if panel is vertical

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37493]
Imho when the panel is configured to be vertical, the maximize action could steal space from the opened sidebar.

One thing to consider is that probably this space should be restored once I click the "restore" action of the panel.

**Comment by isidorn** [comment]
Ok now I am also taking from the sidebar.
Restoring the sidebar position is a bit more tricky. Will do that if a user complains.
