### ISSUE TITLE
Difficult to know if the inline changes view is readonly

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37496]
Verifying #37253

Since the inline change view is readonly, it might confuse users when they start typing inside the editor (it looks editable) and nothing happens. We might need some UX affordance here.

**Comment by joaomoreno** [comment]
@sandy081 That's an editor problem.

**Comment by alexandrudima** [comment]
I've added a message that shows when attempting to make edits in a read-only editor:

![kapture 2018-04-17 at 16 25 19](https://user-images.githubusercontent.com/5047891/38876028-f475b4cc-425b-11e8-84a4-77eda2f30deb.gif)

**Comment by isidorn** [comment]
I would change "Cannot" to "Can not" or "Can't" but that is just me.
Adding verified
