### ISSUE TITLE
php function closure bug after <<<A A; (realy hard to read code without fix)

### ISSUE THREAD

**Issue by peon501** [Microsoft/vscode#37494]
php function closure bug.
cant minimise function when <<<A A; is written inside.

- VSCode Version: newest
- OS Version: win 8.1

Steps to Reproduce:

1. write function
![image](https://user-images.githubusercontent.com/1125765/32319781-65ae9142-bfc4-11e7-9793-b3c2f29414a1.png)
2.
![image](https://user-images.githubusercontent.com/1125765/32319816-7b61103c-bfc4-11e7-8267-1fdbcaf2d6fb.png)

**Comment by roblourens** [comment]
Folding is mainly indentation-based right now, this is one case where that doesn't look great.

https://github.com/Microsoft/vscode/issues/3422

**Comment by peon501** [comment]
I hope you will do something about it. Its really annoying...

**Comment by peon501** [comment]
yeah thats the problem because you cant use tab, space or anything before A;, so indentation-based code dont fit in this situation. Can you make exception for this in indentation-based code or it is hard to do?

**Comment by roblourens** [comment]
I see the problem, the issue I linked is for looking at other ways of doing folding.

**Comment by aeschli** [comment]
There's now API for language extensions to contribute a folding provider.
The built-in PHP extension only provides basic editing support and doesn't contain a parser.

So to get this implemented, please file a feature request against one the PHP extensions: e.g. https://github.com/felixfbecker/vscode-php-intellisense or https://github.com/bmewburn/vscode-intelephense
