### ISSUE TITLE
Font Rendering in LUbuntu OS

### ISSUE THREAD

**Issue by jongbatax** [Microsoft/vscode#37495]
I'm using monaco font, OS: LUbuntu.

after upgrade to new vscode, font not good enough rendering.

![vscode_rendering_font](https://user-images.githubusercontent.com/13173400/32319959-c55a9c60-bfee-11e7-8c9d-b3def789cc42.png)

**Comment by octref** [comment]
Both fonts in the terminal and dropdown menu seem off, so @bpasero and @Tyriar.

@jongbatax What's your `editor.fontFamily` and `terminal.integrated.fontFamily`?

**Comment by Obbi89** [comment]
Doesn't matter what font I use. All look jerky.
If I install ttf fonts from M$ (Arial, Verdana, Helvetica et al.) it's getting even worse.

Characters are misplaced and random pixel artifacts show all around the fonts.

![3502d88e56f019c7518b461cb5d6438db4b3ffb7c100856d2a41e35d3c444f96644d73983d6b47e2df9b41b43886b102e2b7fcf8bef2f02607cff84c77580f62](https://user-images.githubusercontent.com/720039/32359051-10d96b24-c04b-11e7-99f4-a5b521d61d68.png)

**Comment by jongbatax** [comment]
@octref I use monaco font, both editor and terminal....now i change to monospace, it's little help, but waiting vscode fix this font problem and back to monaco font....

**Comment by octref** [comment]
Does the Insider have the same problem on your machine? https://code.visualstudio.com/insiders/

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35675
