### ISSUE TITLE
View on the right: Grow arrow too big

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37498]
Version 1.18.0-insider (1.18.0-insider)
15449873f130d7f3e5604a1cac94f32a1f15f604
2017-11-02T06:07:42.390Z

Open the terminal on the right side
![image](https://user-images.githubusercontent.com/6461412/32320554-6a973ed0-bfbe-11e7-8e50-79ec68eca87b.png)

Note the size of the arrow, it's too big compared to the other action icons

**Comment by isidorn** [comment]
Fixed via d14265436f
