### ISSUE TITLE
Release Notes: use app icon in editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37497]
I think it would be nice to associate the app icon for the release notes in the same way we have it for welcome:

![image](https://user-images.githubusercontent.com/900690/32320601-a67893a4-bfbe-11e7-8802-f50d3198c6d9.png)

**Comment by joaomoreno** [comment]
@bpasero How does `Welcome` do it?

**Comment by joaomoreno** [comment]
Found it... it's a big hack:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.css#L202

But I can do the same...

**Comment by bpasero** [comment]
@joaomoreno oh wow, that IS a hack...

But I see the challenge because we have no way to set an icon for an editor otherwise...

**Comment by joaomoreno** [comment]
What do you want to do? 🥇

**Comment by bpasero** [comment]
@joaomoreno yeah go with the hack and throw my name in there as a todo so that we keep track of this.
