### ISSUE TITLE
Problems when starting debug from status line 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37507]
When the launch config is run from the status bar:
- no launch config errors show up, e.g. if the debug type is wrong or if 'request' attribute is missing
- the same launch config can be started multiple times

I suggest to use the identical code for launching from the status line and through the debug drop down menu.

**Comment by isidorn** [comment]
One is an action, and the other is a quick open item entry. Due to that it is not very trivial to share an implementation. THough I have tried to sharae by introducing a statis isEnabled

**Comment by weinand** [comment]
Verified ok but I've created https://github.com/Microsoft/vscode/issues/39707 to improve the weak UI.
