### ISSUE TITLE
View on right: Move to buttom not working

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#37500]
Version 1.18.0-insider (1.18.0-insider)
15449873f130d7f3e5604a1cac94f32a1f15f604
2017-11-02T06:07:42.390Z

- open a multi root workspace
- in the workspace file set the `workbench.panel.location` setting to `right`
```json
{
	"folders": [
		{
			"path": "Folder1"
		}
	],
	"settings": {
		"workbench.panel.location": "right"
	}

}
```
- In the view, click on the 'Move to button' action. Nothing happens
Note that the setting is written to the user settings where it doesn't have an effect.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37351
