### ISSUE TITLE
Deactivate breakpoints are enabled on source update

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode#37506]
Disabled breakpoints are enabled on source update

- VSCode Version: 1.17.2
- OS Version: ubuntu 17.10

Steps to Reproduce:

1. Clone andrew-w-ross/vscode-debug-issue
2. Launch Debug
3. Put a breakpoint on line 6
4. Hit "deactivate breakpoints"
5. Change the message and the breakpoint should enable

What I find odd is that if you disable the breakpoint directly it seems to behave itself.

**Comment by weinand** [comment]
@isidorn I can reproduce.
