### ISSUE TITLE
Editor in Peek view is getting focus while navigating the references tree on the right

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#37503]
See the following video, I am navigating the tree on the right using arrow and all of the sudden, focus goes to the editor and cursor moves.

![kapture 2017-11-02 at 11 29 52](https://user-images.githubusercontent.com/10746682/32321367-2e9eb590-bfc1-11e7-9508-c39d6a662ef4.gif)

**Comment by jrieken** [comment]
Repos in insiders, not on master...

**Comment by jrieken** [comment]
Likely this https://github.com/Microsoft/vscode/issues/37432

**Comment by joaomoreno** [comment]
Yup dupe of #37432. Sorry about that!
