### ISSUE TITLE
Can not search "Debugger for iOS"

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#37510]
- VSCode Version: 1.18.0-insiders
- OS Version: win10

Steps to Reproduce:

1. Search “Debugger for iOS”
2. Can not find "iOS Web Debugger for Visual Studio Code" 
3. And [this page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-ios-web) have been 404

So no longer support debug for ios webpage?

Reproduces without extensions: Yes

**Comment by auchenberg** [comment]
The iOS web debugger has been deprecated. Please see https://github.com/Microsoft/vscode-ios-web-debug for next steps.
