### ISSUE TITLE
Layout: side-editor opening gets more space only after short delay

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37513]
Steps to Reproduce:

1. move side bar max width
2. open 1 editor
3. open a split editor

=> the second editor opens in small dimensions and only later takes space away from the side bar
=> there seems to be some timeout involved

Does not reproduce in stable.

**Comment by isidorn** [comment]
@bpasero I can not reproduce this with latest vscode insiders
Please let me know what you are doing differently than me

![sidebar](https://user-images.githubusercontent.com/1926584/33550538-9b18123e-d8ee-11e7-8ab3-ed7c4a3e752b.gif)

**Comment by bpasero** [comment]
@isidorn maybe use a slow OS (I used Windows):

![before](https://user-images.githubusercontent.com/900690/33565025-464f9028-d91c-11e7-8d9f-bc6680c8ed83.gif)

Also, I am using Ctrl+2 and Ctrl+3 (though that should not make a difference)

**Comment by isidorn** [comment]
@bpasero just investigated more and I can reproduce this on Windows.
However the layout call is called only once and there are no timeouts.
Did you maybe change when the editor service is emiting events that I am depending on in the layout? I see that the [editorPart](https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/browser/parts/editor/editorPart.ts) has a bunch of timeouts but was not changed recently.

In the end this is the the expected sequence, just for some reason the layout seems to be slow on windows. Tried doing performance profile but did not find anything useful.
Let me know if you maybe have some ideas

**Comment by isidorn** [comment]
@bpasero do you stil get this with the grid?

**Comment by bpasero** [comment]
I actually do not see this anymore in insiders either.
