### ISSUE TITLE
Support emoji symbols in the statusbar (StatusBarItem.text)

### ISSUE THREAD

**Issue by Lisoph** [Microsoft/vscode#37518]
We can currently embed octicon icons in statusbar items, however emoji symbols render as `??` in the statusbar.

**Comment by fabiospampinato** [comment]
Emojis are generally handled by the OS, if yours supports them they should be displayed:

<img width="230" alt="screen shot 2017-11-09 at 15 09 40" src="https://user-images.githubusercontent.com/1812093/32609459-20372fd8-c560-11e7-9abd-f5b0e32b024c.png">

It's possible to add emoji support to all OSs, but IMHO there's quite a lot of work to do for very little to gain.

**Comment by Lisoph** [comment]
Isn't the statusbar also rendered by chromium? Because the weird phenomena for me is that emojis render properly within a document, but not in the statusbar.

![image](https://user-images.githubusercontent.com/3426722/33267189-d5eb21ce-d378-11e7-9d5b-a1685b62b2c2.png)

![image](https://user-images.githubusercontent.com/3426722/33267197-e14e1a76-d378-11e7-807c-e89db2020ba4.png)

**Comment by bpasero** [comment]
@Lisoph but that could just be an issue with the font we are using in the status bar not supporting that emoji while the editor font does (which is different)?
