### ISSUE TITLE
vscode shows error message for files not part of project

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#37511]
- VSCode Version: 1.17.2
- OS Version: windows 10

created simple test project: [link](https://github.com/CzBuCHi/vscode-wrong-error)

**how to reproduce**

open test project in editor
start debugger session (F5) - all goo so far
open random typescript file in same editor with is not in `/src/**` folder and has syntax error in it.
vscode will correctly show problems in opened file
start debugger session - this popup message appears:
`Build errors have been detected during preLaunchTask 'npm: watch'. [Debug Anyway] [Show problems] [Cancel]`
but there is not errors in terminal panel `Task - watch` (because errors are in file not relevant to tsc) so i think, that error message should not be shown ...

**Comment by isidorn** [comment]
Yes this is a known limiation of how we are detecting bugs. Namely we are not asociating errors with the source.
There are already open issues in our repository please search for them.
Closing as duplicate
