### ISSUE TITLE
hope change logo 

### ISSUE THREAD

**Issue by Tim-ls** [Microsoft/vscode#37516]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. this logo is so so so so ... ugly
2. Influence me to knock code

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Duplicate of #35783
Have you already read [this](https://code.visualstudio.com/blogs/2017/10/24/theicon)?

**Comment by octref** [comment]
https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by sseen** [comment]
Visual code team is good at writing, not icon design.
