### ISSUE TITLE
Snippet selection when pressing tab is not always correct

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#3751]
I have an extension that exposes snippets for the [AVA](https://github.com/sindresorhus/ava) testing framework, called [vscode-ava](https://github.com/SamVerschueren/vscode-ava).

I expose the following snippet

```json
"t.is()": {
	"prefix": "t.is",
	"body": "t.is(${1:value}, ${2:expected}${3:, '${4:message}'});",
	"description": "Assert that `value` is equal to `expected`"
}
```

This is what it looks when invoking the snippet

![snippet](https://cloud.githubusercontent.com/assets/1913805/13553834/afb23912-e396-11e5-9605-5989cc4c425a.gif)

As you can see, it works for the first two values, but not for the message. It might be related with the message being optional and thus having the `,` inside `$3`.

**Comment by bman61** [comment]
I am seeing the same behavior.

**Comment by SamVerschueren** [comment]
It looks like this bug is fixed. Can't reproduce anymore.
