### ISSUE TITLE
vscode shows an extra definition location

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#37526]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04

I'm writing an LSP based extension for our CSS preprocessor. 
When implementing onDefinition I see that while I send one definition in the response, vscode shows 2.
The second location is the line on which the defintion request was sent. 
This makes it harder to find the real definition, and prevents Ctrl+click from going directly to the location I send. 
Am I missing something? As you can see in the pic, I am only sending one location back (line 7).

![image](https://user-images.githubusercontent.com/1898725/32329663-57632fd6-bfe6-11e7-8ae7-1ade597bdd5f.png)

**Comment by octref** [comment]
The other definition is provided by `vscode-css-languageservice`.

@dbaeumer @aeschli I'm wondering if it's possible to disable built-in LS for particular files? I'm also interested in doing that.

**Comment by tempit** [comment]
I second that question. Is it possible to disable CSS LS for certain files? In my case .st.css
Only way I found so far is to change our extension to .stcss so it isn't considered css, but then I lose highlighting, etc.
I'd like to bale to pass the CSS LS results through my server, so I can filter out/change some of them

**Comment by octref** [comment]
My usecase is I'm writing a postcss LS and I want to have full control of LS features on *.css files for specific workspaces.

**Comment by dbaeumer** [comment]
I am not aware of such a support.

**Comment by tempit** [comment]
Ok, thanks. Related question, then:
Is it possible to make .st.css files belong to my language and not to CSS? (By registering my language and associating the extension), or will it always be handled by CSS LS because .st.css ends with .css?

**Comment by octref** [comment]
@dbaeumer There is also issues like https://github.com/Microsoft/vscode-css-languageservice/issues/47 that an option to disable CSS LS could help.

**Comment by aeschli** [comment]
Yes, you can add a file assosciation in your extension (or the user settings). The most specific association wins:
```json
    "files.associations": {
        "*.st.css": "mylanguage"
    }
```
