### ISSUE TITLE
Touch controls

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#37529]
Touch works in lots of places, but does not work in quite a few -- like tabs.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
ng-template|Ang|0.1.7
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
ionic3-vs-ionView-snippets|dan|1.0.1
vscode-eslint|dba|1.4.0
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
auto-close-tag|for|0.5.2
auto-rename-tag|for|0.0.14
ionic-preview|ion|0.0.15
cordova-dev-essentials|jew|0.0.1
ionic2-vscode|jgw|1.0.0
Angular2|joh|2.10.0
ionic-extension-pack|loi|0.0.1
rxjs-snippets|pko|0.0.2
vscode-icons|rob|7.17.0
autoimport|ste|1.2.2
ionic2|Tha|3.0.1
Angular2|UVB|0.4.1
cordova-tools|vsm|1.3.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@leegee happy to report that we fixed that for our upcoming release. feel free to give it a try from our insiders release. You can give our preview releases a try from: https://code.visualstudio.com/insiders/
