### ISSUE TITLE
Incorrect syntax highlighting for bash

### ISSUE THREAD

**Issue by mkwiczalayandex** [Microsoft/vscode#37523]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. Paste below code 
```
#!/bin/bash -e
export VAR=`python - <<EOF
print("aaaa")
EOF`

echo "test"
```
2. Select language mode to "Shell Script (Bash)"

Bug:
`echo "test"` has incorrect syntax highlighting

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#89
