### ISSUE TITLE
Feature request - Emmet - create bem child element within existing markup

### ISSUE THREAD

**Issue by joepagan** [Microsoft/vscode#37527]
Hey,

I would like to open an element in existing markup, I couldn't see if this had been requested already (sorry if a dupe).

Currently, it is only possible to use bem with emmet if you are making the parent element too.

I would like something like this:

    <div class="parent">
        .--child
    </div>

to return:

    <div class="parent">
      <div class="parent__child"></div>
    </div>

Currently, it returns this:

    <div class="parent">
        <div class="__child"></div>
    </div>

- VSCode Version:1.17.2
- OS Version:macos 10.12.6

**Comment by ramya-rao-a** [comment]
We use the emmet library to expand given abbreviations in VS Code.
The feature being asked of here is not available at the moment in emmet.
So there is no way we can do this.

Feel free to log a feature request in emmet. Please go through the api for expanding emmet abbreviations at https://github.com/emmetio/expand-abbreviation/ and log appropriate editor agnostic feature request there.
