### ISSUE TITLE
Speed up `registerTextMime`

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37521]
Telemetry shows the 90th percentile of reading the `languages` extension point takes ~32ms and it seems that this can be easily be speed up. The `registerTextMime` will be called per mime which then loops over every registered mime time which results in O(n2) runtime behaviour.

**Comment by bpasero** [comment]
I pushed a change to only ever show these warnings when:
* running with `--verbose`
* running out of sources
* running the extension host in development mode

Otherwise I question the usefulness of these warnings.
