### ISSUE TITLE
&# 65279; not highlight this unicode character

### ISSUE THREAD

**Issue by TomNolane** [Microsoft/vscode#37525]
- VSCode Version : 1.17.2
- OS Version: Win7

How to highlight invisible unicode character `&# 65279;` in Visual Studio Code??

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
There are multiple extensions that implement this functionality.

e.g. https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins
