### ISSUE TITLE
I can not open CSS part of my web page on browser

### ISSUE THREAD

**Issue by Deathstop** [Microsoft/vscode#37522]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|2.5.0
vscode-eslint|dba|1.4.2
javadebugger|don|0.1.5
vscode-html-css|ecm|0.1.8
python-traceback-jumper|lin|1.0.9
cpptools|ms-|0.14.0
open-in-browser|tec|1.1.0
python|tht|0.2.3
html-css-class-completion|Zig|1.12.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please provide more info on the problem, such as description of the problem and how to reproduce it.
