### ISSUE TITLE
Arrow-downing through search results changes focus to editor

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#37534]
- VSCode Version: Code - Insiders 1.18.0-insider (15449873f130d7f3e5604a1cac94f32a1f15f604, 2017-11-02T06:11:55.278Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.0.5
material-icon-theme|PKi|2.2.4
vscode-docker|Pet|0.0.20
quokka-vscode|Wal|1.0.74
regex|chr|0.1.0
crazy|kie|0.0.1
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-npm-script|eg2|0.3.2
vsc-travis-ci-status|fel|1.1.0
svgpreview|kis|0.2.0
Go|luk|0.6.66
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
github-issues-prs|ms-|0.6.0
debugger-for-chrome|msj|3.4.0
vscode-versionlens|pfl|0.19.1
Ruby|reb|0.15.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.2.9

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open the vscode workspace
2. Search for 'GDPR' across all files
3. Select the first match
4. Arrow down (several times)
-> as soon as you change the file the match is in the keyboard focus is moved to the editor

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
The focus is also shifted to the editor when a file is opened from the search explorer or the file explorer. So, this is a broader issue.

**Comment by roblourens** [comment]
Opening a new editor steals focus even when `preserveFocus` is true. Another place I see it is in the embedded editor for 'find all references'.

**Comment by bpasero** [comment]
I think @joaomoreno fixed this.

**Comment by isidorn** [comment]
Works in latest insiders -> verified
