### ISSUE TITLE
Feature Request: Allow copying & pasting files across windows

### ISSUE THREAD

**Issue by ajmas** [Microsoft/vscode#37538]
- VSCode Version: 1.17.2
- OS Version: MacOS 10.13.0

Currently if I trying copy a file, from the file browser, and pasting it into the file tree of another vscode window then the paste operation in unavailable, when looking at the contextual menu (cmd-v, does not work here either). Drag and dropping a file across windows does not work either.

It would be useful to at least have copy/paste support for file, across windows.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
