### ISSUE TITLE
SCM icons look like they have different sizes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37530]
Looks unbalanced (especially the discard again vs. the stage action):

![image](https://user-images.githubusercontent.com/900690/32335038-43241c8c-bfec-11e7-92d2-b577f3ea1c90.png)

**Comment by bpasero** [comment]
While this might have fixed the icon issue in the quick diff area, now I find it uneven in the changes view where icons are typically 16px:

![image](https://user-images.githubusercontent.com/900690/33475049-404eff34-d67d-11e7-9c7e-f748dd18fc1e.png)

**Comment by joaomoreno** [comment]
This is the before/after. The after does look better:

![img](https://user-images.githubusercontent.com/10583315/33131128-8389c24e-cf8d-11e7-8418-2723ece63af9.png)

**Comment by bpasero** [comment]
Yeah looks good for you. Might be my zoom level of 2 then.
