### ISSUE TITLE
Explorer: Decorations are not center-aligned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37532]
In this case:

![image](https://user-images.githubusercontent.com/900690/32335737-d969e126-bfed-11e7-9266-df68881f539a.png)

I think it would be nice if the decorations could be aligned on the same level if possible. E.g. by maybe setting a min-width so that decorations with a slim character are showing up aligned to other decorations.

**Comment by jrieken** [comment]
Not sure if that's possible with the current implementation approach...

**Comment by jrieken** [comment]
I actually don't thing centre or left alignment will improve the look. Agreed the case with the narrow exclamation mark is ugly but in a more real word case it isn't:

**left aligned**
<img width="311" alt="screen shot 2017-12-04 at 11 07 25" src="https://user-images.githubusercontent.com/1794099/33547180-8610ba22-d8e3-11e7-811f-252770e816e5.png">

**center aligned**
<img width="306" alt="screen shot 2017-12-04 at 11 07 38" src="https://user-images.githubusercontent.com/1794099/33547181-86282b6c-d8e3-11e7-922d-0107a95ced35.png">

**right aligned (current)**
<img width="298" alt="screen shot 2017-12-04 at 11 08 48" src="https://user-images.githubusercontent.com/1794099/33547182-863d7558-d8e3-11e7-9816-e4b00734433f.png">

**Comment by bpasero** [comment]
I got used to the way it looks now, so maybe not a big deal.

**Comment by jrieken** [comment]
Ok, closing until new complains come in.
