### ISSUE TITLE
Show broken symlinks in file explorer

### ISSUE THREAD

**Issue by bsander** [Microsoft/vscode#37537]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

```
mkdir -p empty-dir
cd empty-dir
code .
ln -s foo bar
# see bar not showing up in file explorer
touch foo
# see both foo and bar show up in the file explorer
rm foo
# see both files disappear again
```

I would expect to see the file in the explorer, and when selected to be notified that the linked file does not exist.

Reproduces without extensions: Yes

**Comment by ryansully** [comment]
See #11539.
