### ISSUE TITLE
Update does not work on macOS when running as a regular user (not administrator)

### ISSUE THREAD

**Issue by roustem** [Microsoft/vscode#37546]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
golang-tdd|joa|0.0.9
Go|luk|0.6.66
terraform|mau|0.0.19
gitblame|wad|2.2.0
HCL|who|0.0.5
---

Steps to Reproduce:

1. Install VSCode in the `/Applications` folder
2. When the new version is available, click the Update Now
3. VSCode restarts without updating because writing to the `/Applications` folder requires administrator password (which is not requested).

Reproduces without extensions: Yes

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-301044377

https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
