### ISSUE TITLE
Git extension Status of files outside of current folder being shown

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode#37547]
- VSCode Version:1.17.2
- OS Version:Fedora 26

Steps to Reproduce:

1. Make changes to file at root of git project
2. Open and directory in the project
3. Source control will show the changes in the root.

Prior to adding multi-root workspace this would not happen and only show you status for current open folder.

This might be a bug or design choice?

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This is a design choice. The SCM view will only work with the full repository.
