### ISSUE TITLE
Terminal Maximize/Restore button too big and doesn't restore

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37540]
- VSCode Version: Code - Insiders 1.18.0-insider (15449873f130d7f3e5604a1cac94f32a1f15f604, 2017-11-02T06:11:55.278Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
regex|chr|0.1.0
ssh|chr|0.0.2
vscode-eslint|dba|1.4.2
ghlink|dt|0.0.6
tslint|eg2|1.0.14
azure-account|ms-|0.1.3
azurecli|ms-|0.3.0
github-issues-prs|ms-|0.6.0
debugger-for-chrome|msj|3.4.0
vetur|oct|0.10.1
vscode-versionlens|pfl|0.19.1
vscode-open-in-github|sys|1.6.0

---

Steps to Reproduce:

1. Move Terminal to the right
2. Maximize/Restore is too big
3. Restore doesn't work

![image](https://user-images.githubusercontent.com/9205389/32338609-89168d40-bfb2-11e7-8a5c-d40419d787be.png)

/cc @Tyriar

**Comment by Tyriar** [comment]
I believe @isidorn already fixed this
