### ISSUE TITLE
[python] Wrong indentation in python files when declaring class

### ISSUE THREAD

**Issue by jsnjack** [Microsoft/vscode#3754]
When declaring class in python files, the next line should has indentation. For example:
 - type `class Class:`
 - hit Enter
 - the cursor should be on position 4 (for indentation 4 spaces)

On the version  0.10.8 the cursor position is 0

**Comment by misja** [comment]
When defining an asynchronous function with the new `async` syntax the next line doesn't have indentation.

```python
asycnc def hello():
    pass
```

**Comment by aeschli** [comment]
Could be done in the VSCode built-in Python extension, but rather something for the full Python support.
