### ISSUE TITLE
Maximize/restore panel icons are inconsistent with the close panel button

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37544]
Notice that the icons look slightly different:

![image](https://user-images.githubusercontent.com/2193314/32343199-f48dcc5c-bfbf-11e7-8303-b839a478ee3b.png)

They appear to be slightly different colors and weights.

/cc @chryw

**Comment by chryw** [comment]
@Tyriar @isidorn what about these?
![image](https://user-images.githubusercontent.com/7075677/32351002-445feaee-bfd9-11e7-8e7c-3511ae7fdf38.png)

**Comment by isidorn** [comment]
@chryw they look great to me. The terminal icons always looked too strong and out of place imho
Let's wait and see what @Tyriar has to say

**Comment by Tyriar** [comment]
@chryw they look good, except for the fact that they're filled on the inside and I'm not sure about the border on some of the icons (may just be AA) as they need to look good on a wide range of themes (basically all light background colors). For the fill, imagine the editor background is light yellow instead of white, if the icon fill is grey this would look strange.

<img width="220" alt="screen shot 2017-11-03 at 10 42 05 am" src="https://user-images.githubusercontent.com/2193314/32388062-b25d7688-c083-11e7-975a-1bb6291e88ea.png">

This new `+` and `x` icons are also inconsistent with the rest of the UI, I'm not sure we would want to use new icons for the `+` and `x` until we tackled the whole of https://github.com/Microsoft/vscode/issues/8017 (which I would absolutely love).

**Comment by chryw** [comment]
@Tyriar sorry I forgot to take off the halo and foreground fill. These are actually VS icons. When I "vscode-fy" them they'll only have the grey path.
[37544_PanelIcons_new.zip](https://github.com/Microsoft/vscode/files/1442354/37544_PanelIcons_new.zip)

Regarding the overall icon inconsistency #8017 , we'll need to plan better. Right now we don't have enough bandwidth. But I think it's ok to tackle these ones first as they're shown in one list.

**Comment by Tyriar** [comment]
@chryw they look good without the halo and fill :+1:. Just keep in mind if you change `x` or `+`, it would be best to change them everywhere they're used in the UI.

**Comment by isidorn** [comment]
@chryw thanks for the new icons. Now I am using them in the panel for left, right, up, down, dock
@Tyriar I did not update the Delete Terminal and Cancel icons. You can take the terminal one, and the cancel one we should tackle as part of #8017
