### ISSUE TITLE
Not possible to set filename for Typescript Compiler Options

### ISSUE THREAD

**Issue by FlippieCoetser** [Microsoft/vscode#37543]
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:
1. Create tsconfig.json
2. Ensure "experimentalDecorators": true
3. Implement Decorators
4. Change tsconfig.json filename
5. VS Code throws error where typescript decorators are used.

As a Developer,
When I use a different .json file for typescript compiler options,
I want to set the path and name of the configuration file,
so that the VS Code is able find the typescript compiler options

**Comment by mjbvz** [comment]
Tracked by #12463

Closing as duplicate of #12463
