### ISSUE TITLE
Editor model is set very late

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#37541]
I used to Timeline/Performance and `console.timeStamp`. Turns out that we instantiate the editor widget ~400ms after startup. However, setting the model only happens 2seconds later... In-between we do all kinds of things (extension parsing, tree updating etc, etc). We should look at *all* of them and justify why they are more important than `setModel`...

<img width="1325" alt="screen shot 2017-11-02 at 17 48 17" src="https://user-images.githubusercontent.com/1794099/32339039-d0bf6218-bff6-11e7-9a6c-9680d0844886.png">

The patch to get the performance marks: [timeStamp.patch.txt](https://github.com/Microsoft/vscode/files/1438622/timeStamp.patch.txt)

**Comment by jrieken** [comment]
So, the rough order of things is like this:

1. create workbench and widgets (sidebar, editor-container, editor-widget, etc)
2. explorer: resolve files & folders, then update the tree
3. extensions: start extension host, parse package.json-files, fill registries, send events
4. editor: load file from disk, set model, render model

I believe the order should be 1, 4, 2, 3. With some delaying in the extension service you can easily get to 1, 2, 4, 3 which makes the editor render roughly a second sooner.

**Comment by bpasero** [comment]
@jrieken viewlet and editor resolve in parallel if I remember correctly, the editor should never wait on the explorer to be loaed. 

I agree on pushing out the extension host loading to a later point would make sense.

**Comment by jrieken** [comment]
>  in parallel if I remember correctly, the editor should never wait on the explorer to be loaed.

Wishful thinking... Nothing happens in parallel here. Yes, both use promises and both run async operations but because the viewlet is being asked first, it always wins

**Comment by bpasero** [comment]
@jrieken well "in parallel" meaning that both components go to disk and load files and the first one that gets back control will win to do the drawing. I am not sure how reordering the editor to be called first before the explorer would change anything because in the end it highly depends on what disk IO is being done from both components.

**Comment by jrieken** [comment]
I understand the theory but in practice I never measured a run where the editor won. Maybe that's because the explorer loads it's files very eagerly when being constructed whereas the editor widget needs to get the model set. 

Despite all parallelism, I believe the *perceived* performance depends a lot more on how soon you see text and a blinking cursor and now on how fast the tree populates and because of that we shouldn't even allow that "race" but start with the editor.

**Comment by bpasero** [comment]
Yeah, let's make sure the editor wins and see why that is not the case.

**Comment by jrieken** [comment]
Let's swap 1 and 2, Call me artist. 

<img width="1646" alt="screen shot 2017-11-03 at 10 45 24" src="https://user-images.githubusercontent.com/1794099/32368019-a1069792-c084-11e7-9a73-944e8cc82b10.png">
It always l

**Comment by jrieken** [comment]
I have pushed https://github.com/Microsoft/vscode/commit/ff82f1a7529de588312459fa1f5a4dfb5ff214b1 which makes sure extension-host-startup and package.json-scanning is done after the editor is populated. This improves the perceived performance but it also causes flicker, e.g. the text is rendered without colors first, then the grammers/tokenizers are loaded, and then the text is re-rendered with colors. 

@bpasero I have also played with [`createTextEditorModel`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/textEditorModel.ts#L70) and when removing the 50ms timeout the editor loads more parallel and finishes before the tree is being populated. I'd suggestion to skip the timeout while the [`LifecyclePhase`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/lifecycle/common/lifecycle.ts#L70) is not `Running`

**Comment by bpasero** [comment]
@jrieken sounds good, I will look into that part

**Comment by jrieken** [comment]
I have disabled my late-ext-host-launch-change because of #37751

**Comment by jrieken** [comment]
I have pushed ab17bb71f6 which adds a new lifecycle event `Restoring`, it also removes the 50ms wait time when setting an editor input as the mode depends (once) on the extensions being read. Looks now like this

<img width="1116" alt="screen shot 2017-11-07 at 12 31 03" src="https://user-images.githubusercontent.com/1794099/32491659-ca5a36fe-c3b7-11e7-9886-fe9195cf0700.png">

**Comment by bpasero** [comment]
I pushed a change to restore the editor first before sidebar and panel (https://github.com/Microsoft/vscode/commit/c1bfc0501434626d89df2bbbfcd1d77a65970aad). I still see the explorer showing data first before the editor shows any data.

Next I will first get rid of `IPartService.joinCreation()` in favour of `LifeCycleService`.

**Comment by sandy081** [comment]
@jrieken @bpasero Let me know if there is any action to be taken by me here?

**Comment by jrieken** [comment]
Three things happen at the same time: (1) populating the editor, (2) populating the explorer, (3) scanning for extensions. And the reason for the editor being set so late is a big waterfall... This is what happens when calling `TextFileEditorModel#load` (this comes first, before loading the explorer or scanning for extensions)

```
 -1- // backupmodel, init
    -2- // fileservice, resolve
       -3- // mime, fs.open
          -4- // mime, fs.read
             -5- // mime, fs.end
                -6- // fileservice, createReadStream
|----------------|
0               1sec
```


1. The `load`-function checks with the back service which is [still initialising](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupFileService.ts#L137). 
3. The `load`-function ends up calling `IFileService#resolveStreamContent` which begins with calling [`resolve`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L214) which is doing a stat-call
5. Then it calls [`detectMime`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/mime.ts#L162) which does the following:  It calls `fs.open`, 
4. it calls `fs.read` (potentially n-times),
5. it call `fs.end`
6. After doing that the [`resolveFileStreamContent`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L577)-function runs. It opens the file again and streams it around.
8. We have read the file and call `setModel`


Lots of waiting and delaying.... (around 1 second) Questions:

* @Tyriar Can the backup and the actual model be resolved in parallel instead of todays blocking waterfall way of things?
* @bpasero Why do we stat a file that we want to read? Won't we get an error when trying to read a non-file?
* @bpasero Why do we read/open the file twice. I believe we should read the file in chunks (as stream or not) and detect the mime/encoding while we are doing that

**Comment by Tyriar** [comment]
> @Tyriar Can the backup and the actual model be resolved in parallel instead of todays blocking waterfall way of things?

@jrieken it's been a while since I touched this, I think the editor model needs the backup model to be initialized in order to get the content. If a particular file has a backup it needs to be loaded from the backup file in user data, not the regular file.

Here's where the loading happens:

https://github.com/Microsoft/vscode/blob/284779f5c10c5676821b2a4e7fe6e5973fe11e51/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L286

A `TextFileEditorModel` cannot `load` until:

1. The `BackupMainService` has initialized and identified the backup root path (done on Electron main process side)
2. The `BackupFileService` has been initialized with the backup root path such that it can identify which paths have backups available

Not sure if I answered your question.

**Comment by bpasero** [comment]
@jrieken we need the stat to resolve some metadata around the file (e.g. the modification time) in order to prevent dirty writes and do proper conditional get if the file has not changed. Unfortunately we do not get this info from just reading the file. 

I guess we could experiment with detecting the encoding and leaving the stream open to do the actual read of the file. We would need to be able to push back bytes to the stream though so that we can give the entire stream to `iconv-lite`. 

As for the backups: I am not sure how we could load the backup and the model in parallel because we need to know if there is a backup to resolve the file properly. Are you suggesting to load both in parallel and then see if we actually have a backup and then pick that one over the file we resolved?

**Comment by bpasero** [comment]
@jrieken now that we have the startup phases in lifecycle service, should we change [`registerWorkbenchContribution`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/contributions.ts#L35) to accept an optional phase argument and then when we instantiate the contributions respect that event to delay the instantiation? This would need to be wired into the [`setInstantiationService`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/registry/common/platform.ts#L70) call of the `BaseRegistry` I guess.

**Comment by jrieken** [comment]
> Unfortunately we do not get this info from just reading the file.

Well, fortunately not every file read does that. Question is why reading needs to wait for stating? Why doesn't the editor call `resolveFile` and at the some times reads the file? Most callers of `resolveContent` only want the content anyways and it wouldn't cause the waterfall. 

> We would need to be able to push back bytes to the stream though so that we can give the entire stream to iconv-lite

Not sure I understand that? We only give it 512 or 4096 bytes anyways. We could just start reading, buffer so many bytes require to detect encoding, guess the encoding via `detectMimeAndEncodingFromBuffer` and than bail out or surface the bytes to the reader

> As for the backups: I am not sure how we could load the backup and the model in parallel because we need to know if there is a backup to resolve the file properly. 

I believe that the blocking call is just to build the index of of backup files not loading. We could also optimistically do it in parallel and drop the "real" file once we know a back exists.

**Comment by bpasero** [comment]
> Well, fortunately not every file read does that. Question is why reading needs to wait for stating? Why doesn't the editor call resolveFile and at the some times reads the file? Most callers of resolveContent only want the content anyways and it wouldn't cause the waterfall.

@jrieken we first do the stat to prevent unneeded disk IO for reading the file in case the file has not changed. Every time you click on a tab we do this call, even if the tab has already been opened before. If we would start to always read the file from disk in that case I think we would too much unnecessary work. 

We could however think about doing this either only on startup or just create a new `resolveContentSync` method which is sync and which is only used during startup. 

> Not sure I understand that? We only give it 512 or 4096 bytes anyways. We could just start reading, buffer so many bytes require to detect encoding, guess the encoding via detectMimeAndEncodingFromBuffer and than bail out or surface the bytes to the reader

Yeah, I guess the challenge is with `iconv-lite` stream handling as you already found out.

> I believe that the blocking call is just to build the index of of backup files not loading. We could also optimistically do it in parallel and drop the "real" file once we know a back exists.

Yes, that could work.
