### ISSUE TITLE
Closing working directory/folder with the terminal open restarts the integrated terminal process and kills it's child processes

### ISSUE THREAD

**Issue by fortraan** [Microsoft/vscode#37552]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:10:17.189Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.2

---

Steps to Reproduce:

1. Open a folder/working directory
2. Open the integrated terminal
3. Run a program, ie: ```idle3``` or ```/Applications/TextEdit.app/Contents/MacOS/TextEdit &```
4. From the command bar, run File >> Close Folder
  
  
Processes spawned by the terminal will die and the terminal window will go blank (the text disappears, to be specific). Closing and re-opening the integrated terminal drops you into a new instance of the terminal/shell.  
Running processes in the background doesn't spare said processes from this issue. The same problem occurs upon opening a folder/working directory as well.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
