### ISSUE TITLE
Allow drop between folders in explorer

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#37558]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.20
sort-lines|Tyr|1.3.0
githistory|don|0.2.3
markdown-table-formatter|jos|0.2.3
Go|luk|0.6.66
prettify-json|moh|0.0.3
azure-account|ms-|0.1.3
rewrap|stk|1.5.3
gitblame|wad|2.2.0
vscode-proto3|zxh|0.1.2

---

Steps to Reproduce:

1. Select an existing directory.
2. Click the "New Folder" button at the top of the Side Bar pane.
3. Enter a name and press Enter.
4. Try to drag the new directory to the Side Bar root directory.
5. Fail to do so.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Works for me. Can you please try with latest vscode insiders 

Also let me know if you are doing something differently than me in this short video
![folder](https://user-images.githubusercontent.com/1926584/32365642-e3a69a5c-c07a-11e7-9e7d-87874f6b3b6d.gif)

**Comment by willfaught** [comment]
Oh, I see, you have to drag it on the files. That does work for me.

I was expecting to be able to move a directory into the root directory by dragging it to between two items in the root directory. Is there any interest in adding that functionality?

**Comment by isidorn** [comment]
@willfaught thanks for providing more info. I have renamed this feature request to better describe the intention of this issue.
We will not tackle it in the near future unless more users ask for this.
