### ISSUE TITLE
View does not follow cursor when jumping to matching bracket

### ISSUE THREAD

**Issue by mlucic** [Microsoft/vscode#37554]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:09.760Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.12.1

---

Steps to Reproduce:

1. Open a file containing a block that is enclosed with braces, where the opening and closing braces are not both visible at the same time in your window.
2. Set the cursor at either the opening or closing brace.
3. Enter the key combination to jump to matching brace ( Ctrl + Shift + \ ) 
4. The cursor will have jumped out of view to the matching brace, leaving the view in the same position.

Reproduces without extensions: Yes

**Comment by octref** [comment]
Does not repro for me on Windows. Can you upgrade to latest and see if this still happens?

**Comment by mlucic** [comment]
Upgraded to 1.17.1, issue is no longer relevant. Thanks.
