### ISSUE TITLE
(Windows) Uninstalling a symlinked extension deletes the target directory

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#3755]
Reporting this since installing extensions via symbolic link may soon be coming to vsce (Microsoft/vscode-vsce#78). 

On Windows, when uninstalling an extension that was added to the .vscode/extensions folder via symbolic link, the contents of target folder of the link are deleted :open_mouth:, rather than just the link.

It's the same behaviour whether it's a symlink or a junction.

Tested on 10.8 and 10.10-insiders on Windows 8.1

**Comment by joaomoreno** [comment]
I am embarrassed to ask... but how can I create one of those directories symbolic links?

**Comment by stkb** [comment]
In an elevated command prompt run `mklink /D link target` for a directory symlink or `mklink /J link target` for a directory junction.

Running just `mklink` will give you all the options. Lemme know if you want any more info.

**Comment by stkb** [comment]
You're probably already there but I guess I'll mention that I think the problem is [src/vs/base/node/pfs.ts L58-L65]
(https://github.com/Microsoft/vscode/blob/44bd2d14ea0bc5c7e009411d136e21056d1678d9/src/vs/base/node/pfs.ts#L58-L65)
``` ts
export function rimraf(path: string): TPromise<void> {
    return stat(path).then(stat => { 
        if (stat.isDirectory()) { 
            return readdir(path) 
                .then(children => TPromise.join(children.map(child => rimraf(join(path, child))))) 
                .then(() => rmdir(path)); 
        } else { 
            return unlink(path); 
        } 
```

It looks like the code is using isDirectory() to determine whether it's a real folder or link. That'll work on *nix but not on Windows, where a directory link will still show as a directory.

It needs to use [lstat](https://nodejs.org/api/fs.html#fs_fs_lstat_path_callback) instead of stat and call `.isSymbolicLink()` on the returned object. That should work on all platforms.

**Comment by joaomoreno** [comment]
Thanks!
