### ISSUE TITLE
taskDefinitions property descriptions are not localized

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37565]
In the typescript extension for example:

```
    "taskDefinitions": [
      {
        "type": "typescript",
        "required": [
          "tsconfig"
        ],
        "properties": {
          "tsconfig": {
            "type": "string",
            "description": "The tsconfig file that defines the TS build"
          },
          "option": {
            "type": "string"
          }
        }
      }
    ],
```

The `tsconfig` property's description field is not localized. Seems to be true for all `taskDefinitions` in the builtin extensions

**Comment by dbaeumer** [comment]
Not critical. Moving to next milestone.

**Comment by ramya-rao-a** [comment]
@dbaeumer Is this still for January or can we move it to Feb?

**Comment by dbaeumer** [comment]
I planned to but I was busy tracking down the startup performance problem. Will move.

**Comment by dbaeumer** [comment]
I did gulp, grunt, jake. npm is done as well. Did TS as well.
