### ISSUE TITLE
Deleting .code-workspace contents can break existing workspace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37560]
Testing #35871

1. Create a simple workspace:

```
{
	"folders": [
		{
			"path": "main"
		}
	],
	"settings": {
	}
} 
```

2. Open workspace in vscode
3. Now in a separate editor, open the workspace file itself and delete all of its contents
4. Reload the opened workspace window.

**Bug**

![screen shot 2017-11-02 at 3 54 39 pm](https://user-images.githubusercontent.com/12821956/32354251-269e0cc2-bfe6-11e7-93cc-ea2f2abd231f.png)

Developer console shows:

```
TypeError: Cannot read property 'configuration' of undefined
 at t.getWorkbenchState (file:///Applications/Visual Studio Code - 
Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10:309065)
```

**Comment by sandy081** [comment]
This works now and opens window with empty folders
