### ISSUE TITLE
Maximize panel icon is very large when in sideways view

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37567]
Testing #37330

Using 15449873f130d7f3e5604a1cac94f32a1f15f604

With the panel to the side, the maximize icon is very large compared to the other icons:

![screen shot 2017-11-02 at 5 05 11 pm](https://user-images.githubusercontent.com/12821956/32356089-0d666e98-bff0-11e7-9f38-e13dd80edd9f.png)

![screen shot 2017-11-02 at 5 05 48 pm](https://user-images.githubusercontent.com/12821956/32356093-17ab53fa-bff0-11e7-88c5-73f060ad317c.png)

**Comment by isidorn** [comment]
DUplicate
