### ISSUE TITLE
Bad MessageWidget position on wrapped line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#37568]
Steps to Reproduce:

1. Open the settings editor
2. On the left hand side, find a long setting description that wraps to multiple lines
3. Place the cursor on one of the wrapped lines
4. Try typing

**Bug**

![screen shot 2017-11-02 at 5 30 22 pm](https://user-images.githubusercontent.com/12821956/32356726-5cdfc7c2-bff4-11e7-8d4c-9c28a920b9d2.png)

Warning is shown in the correct column but on the first line of the wrapped line

**Comment by bpasero** [comment]
I am using the [`MessageWidget`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/message/messageController.ts#L114) from @jrieken so I would assume the same issue when the "No Definitions" info message pops up.

**Comment by jrieken** [comment]
@alexandrudima The `MessageWidget` is implemented as `IContentWidget` which provided its position as model-position, not viewModel-position. Is there a better widget that works with wrapped lines?

**Comment by alexandrudima** [comment]
The `IContentWidget` position is converted to view model coordinates before being painted.

See the suggest widget which is an `IContentWidget` and works correctly for wrapped text AFAIK.

So I would assume a correct model position will result in a correct view position.
