### ISSUE TITLE
UI Glitches out occasionally

### ISSUE THREAD

**Issue by mehulkar** [Microsoft/vscode#37563]
UI randomly starts glitching out flashing batches of darkness. screenshot below. No idea how to reproduce, but it has happened a few times now. Let me know if there's any more details I can collect when it happens!

![screen shot 2017-11-02 at 4 11 16 pm](https://user-images.githubusercontent.com/490968/32354803-afe12012-bfe8-11e7-8d99-f28236caee35.png)

- VSCode Version: 1.17.2 (1.17.2)
- OS Version: macOS 10.13.1 (Beta)

Steps to Reproduce:

1. Not sure 😞

**Comment by octref** [comment]
Duplicate of #35527.
