### ISSUE TITLE
Restart TS Server command loses formatting preferences

### ISSUE THREAD

**Issue by mrcrowl** [Microsoft/vscode#37561]
- VSCode Version: 1.17.2
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. In a new workspace
2. Configure workspace settings with some non-standard Typescript format settings: e.g. 
```
    "typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
    "typescript.format.placeOpenBraceOnNewLineForFunctions": true,
```
3. Paste into a new .ts file:
```
function helloWorld() 
{
    console.log("Hello, world.")
}
```
4. Run _Format Document_... does what you expect 😄 
5. Run _Restart TS Server_ (... and maybe wait a little for it to load)
6. Run _Format Document_... now ignores formatting settings 😢 

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This should be fixed in VS Code insiders already. Can you please test this using insiders?

**Comment by mrcrowl** [comment]
Great! thanks... fixed in insiders.
