### ISSUE TITLE
Import-Module SQLPS throws exception related to PowerShell Editor Services version.

### ISSUE THREAD

**Issue by toddbrownmcis** [Microsoft/vscode#3756]
Import-Module : The current Windows PowerShell host is: 'PowerShell Editor Services' (version 0.4.2.264). The module 'C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1' requires a minimum Windows PowerShell host version of '1.0' to run.At C:\Program Files (x86)\Microsoft SQL 
Server\120\Tools\PowerShell\Modules\SQLPS\SqlPsPostScript.ps1:8 char:20

**Comment by egamma** [comment]
This looks like an issue for the github PowerShell/vscode-powershell repository. I've tried to move it but it failed, pls move the issue if it is for the powershell extension.

**Comment by toddbrownmcis** [comment]
Moved to https://github.com/PowerShell/vscode-powershell/issues/109
