### ISSUE TITLE
Wrong modifcation/indent in Lua long string after pasting

### ISSUE THREAD

**Issue by XuJiandong** [Microsoft/vscode#37572]
- VSCode Version: 1.17
- OS Version: windows 7

Steps to Reproduce:

1. in any .lua file, input code like this:
<pre>
f([==[This is a long string in lua.
    This is the second line.
    Thie is the last.
]==])
</pre>

2. copy this code snippet and then paste it anywhere, it becomes:
<pre>
f([==[This is a long string in lua.
This is the second line.
Thie is the last.
]==])
</pre>

Reproduces without extensions: Yes

The content in [==[ and ]==] in Lua is long string and should not be indented (modified) after pasting.
It was OK in old version (1.15 or earlier).

**Comment by octref** [comment]
This is probably a bug in the lua extension you are using. Open a bug for them.
On the editor side you can disable `editor.formatOnPaste`.
