### ISSUE TITLE
Unable to use VSCode in multiple remote desktop sessions under same user name

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#37573]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
mock-debug|and|0.25.0
status-bar-tasks|Gua|0.2.1
color-highlight|nau|2.3.0

---

Steps to Reproduce:

1.Remote login and choose a session.
2.Open vscode.
2.Login again and choose another session.
3.Open vscode.
4.Can not see vscode window.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Are you debugging lua?

**Comment by actboy168** [comment]
No. It does not matter with the extensions,I think.
I just opened the vscode, nothing to do.

**Comment by weinand** [comment]
@actboy168 I really do not understand your problem.
- What do you mean by "Remote login and choose a session"?
- On what system do you try to login remotely?
- How do you choose a session?

**Comment by actboy168** [comment]
I recorded a video.
[2017-11-05 12-03-25.zip](https://github.com/Microsoft/vscode/files/1443753/2017-11-05.12-03-25.zip)

**Comment by bpasero** [comment]
@actboy168 could it be that when you start Code in the second session, it opens a window in the first session?

**Comment by actboy168** [comment]
Yes

**Comment by bpasero** [comment]
@joaomoreno this indicates to me that the same pipe is used on startup for communication. not sure if we can do something about it though, it seems here the same user is using it from multiple sessions.

@actboy168 can you confirm that in both sessions you are the same user?

**Comment by actboy168** [comment]
Yes, only appear on the same user but different sessions.

**Comment by joaomoreno** [comment]
Of course it's the same shared pipe, it has nothing to do with that.

What very likely happens when trying to open Code from the other session is that a second window comes up in the first session. This is my blind guess, not knowing much about Windows multiple remote desktop sessions and where Electron windows come up.

I don't think we can do anything here.

Workaround: use different `--user-data-dir PATH` locations when spawning Code on each session.
