### ISSUE TITLE
Autocomplete mais avançado

### ISSUE THREAD

**Issue by peduardodasilva** [Microsoft/vscode#37574]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.A IDE esta muito evoluída falta pouco para eu assumir como top, poderiam incluir umas funcionalidades combinadas do VS2017 e sublime text por exemplo

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Translated as: The IDE is very evolved and it's a bit lacking for me to assume as top, could include the combined functionality of VS2017 and sublime text for example

Thanks for your suggestion. Please use English to report issues.
We are working on improving the auto-completion. If you have specific suggestions feel free to open another issue.
