### ISSUE TITLE
Cannot open stddef.h (dependency of stdlib.h

### ISSUE THREAD

**Issue by namarino41** [Microsoft/vscode#37577]
- VSCode Version: 1.17
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Write simple c program.
2. #include <stdlib.h>

Reproduces without extensions: No

When I include stdlib.h, it gets a green squiggly saying that it can not load one of it's dependencies and to edit the include path. When I do that, that squiggly line goes away, but then I get error messages on some of my variables that are from other header files. None of this effects the way the program runs. Everything compiles and runs just fine.
![image](https://user-images.githubusercontent.com/31663851/32360912-bf817d9e-c030-11e7-90d4-8fb1b6ca8ad6.png)

![image](https://user-images.githubusercontent.com/31663851/32360914-c6a22d94-c030-11e7-953e-6bb41f6411ca.png)

**Comment by octref** [comment]
This should be an issue for https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools (I guess you are using it).

@bobbrow do you mind if I move the issue over?

**Comment by namarino41** [comment]
Oh yeah, absolutely! Sorry about that.

**Comment by octref** [comment]
@namarino41 It's ok. Do you mind just making a new issue here: https://github.com/Microsoft/vscode-cpptools/issues/new?

I'll close this one since there is nothing we can do from VS Code side.

**Comment by bobbrow** [comment]
@namarino41, please open an issue in the extension repo linked above.  It is related to your c_cpp_properties.json file, so if you can share it with us, we will help you resolve the problem.

**Comment by namarino41** [comment]
@bobbrow Opened an issue in the extension repo. Thanks for the help. It's #1202
