### ISSUE TITLE
TypeSCript service failure.

### ISSUE THREAD

**Issue by dukeShreyas** [Microsoft/vscode#37578]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.14

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide information about what is going wrong
