### ISSUE TITLE
You cannot open a file in an existing window if it has a workspace open

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37576]
- VSCode Version: Code - Insiders 1.18.0-insider (2ab10d50163f008ada9a4aa215de8c884857ce99, 2017-11-01T06:11:48.112Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
debugger-for-chrome|msj|3.4.0
seti-icons|qin|0.1.3

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Open multi root workspace with 2 folder
2. Run code-insiders <some_file>, a new window will appear when it should add the file to the existing window

**Comment by bpasero** [comment]
@Tyriar I cannot reproduce, do you maybe have `window.openFilesInNewWindow` set to `on`?

**Comment by Tyriar** [comment]
I didn't have that set, but it doesn't seem to reproduce anymore so I'll close it off.
