### ISSUE TITLE
Add relative directory/filepath support to snippets

### ISSUE THREAD

**Issue by mdickin** [microsoft/vscode#37570]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.3.9600

Currently, snippets allow you to resolve the current directory or filepath with `TM_DIRECTORY` and `TM_FILEPATH` respectively. It would be great to be able to get the path for these relative to the root folder, whether directly (e.g. `TM_DIRECTORY_REL`) or by providing a variable with the root folder.

I'm trying to write a snippet to create a new C# file. Visual Studio will auto-populate the file with `namespace Directory.Structure.Here`, but that doesn't seem possible in Visual Studio Code right now.

**Comment by jrieken** [comment]
We have added [*Variable Transformations*](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms) for thing like this. Please give it a try

**Comment by mdickin** [comment]
I'm not sure how that would help in this case. If `TM_DIRECTORY` resolves to `C:\dev\projects\my_projects\secret_projects\secret_project1\features\secret_feature`, how can I know where the project begins? If I have the project root at `secret_project1`, I would expect the namespace to be  `secret_project1.features.secret_feature`, but I don't see any way of reliably generating that without making assumptions about base folder structure.

**Comment by mdickin** [comment]
I could also see this used for other situations, like generating a JavaScript file that imports a common file, like `const myCommonLib = require('../../../common.js');`. In this case, if I had the relative directory, I could easily use the Variable Transformations to generate `../../../`

**Comment by jrieken** [comment]
> how can I know where the project begins?

Well, how would we know? Do you suggest to take the current folder? What if your project start one level deeper, like `src` and `test`? I like the idea of having a variable that resolves the active (workspace) folder but I don't know if it will help you. Tho, it might make it easier to craft a snippet with  transforms

**Comment by mdickin** [comment]
Sorry, when I said project root, I meant workspace root.

You're right, it wouldn't solve every situation, but I think it could be handy to have.

**Comment by Spielberg** [comment]
Any idea how to make this works using variable transformations?

**Comment by DVDima** [comment]
@Spielberg, if you hardcode root foder, you can use the next transformation:
`"const myCommonLib = require('${TM_DIRECTORY/.*src(\\\\[^\\\\]*)(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?/${1:+../}${2:+../}${3:+../}${4:+../}/}common.js');",`

**Comment by neminovno** [comment]
@jrieken "variable that resolves the active (workspace) folder" is definitely missing. How about 'custom' variable that could read string from another file? Usually, if source root is not the relative folder, it is written in some (json, xml..) file in relative folder. Beside resolving this issue, probably that new variable would provide many more options in snippets.

**Comment by GammaGames** [comment]
Workspace-related snippet variables would be very handy for plenty of cases, I was surprised they weren't included already when I went looking for them

**Comment by doggy8088** [comment]
Add a new variable `TM_WORKSPACE_ROOT` pointing to the root path of the workspace will be awesome!

**Comment by still-dreaming-1** [comment]
> Add a new variable `TM_WORKSPACE_ROOT` pointing to the root path of the workspace will be awesome!

This would be great. If we could also get a `TM_DIRECTORY_RELATIVE_WORKSPACE_ROOT`, that would be super amazing, and provide a better basis for doing what the OP is trying to do.

**Comment by still-dreaming-1** [comment]
When editing other settings for VS Code, you sometimes have access to [`${workspaceFolder}` and `${relativeFileDirname}` variables](https://code.visualstudio.com/docs/editor/variables-reference). That is what we need here. I tried just using them, but they didn't work for me here.

**Comment by still-dreaming-1** [comment]
> @Spielberg, if you hardcode root foder, you can use the next transformation:
> `"const myCommonLib = require('${TM_DIRECTORY/.*src(\\\\[^\\\\]*)(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?/${1:+../}${2:+../}${3:+../}${4:+../}/}common.js');",`

I'm really terrible at transformations and regex. Could you please provide a similar transformation that inserts the names of the directories after src/ that would produce code in this format:
`namespace SomeHardCodedThing\Directory\Structure\After\Src;`

**Comment by AoDev** [comment]
2 years ago I asked [this question on Stackoverflow](https://stackoverflow.com/questions/48366014/how-to-get-the-base-directory-in-visual-studio-code-snippet/48366340#48366340) about getting the base directory. 

Having the current directory name (and not the full path) seems to be in demand. Sure people are giving their upvote for the transform but what we really want is a simple, relatively short variable to get it. The snippets are not that obvious with these transforms repeated everywhere and not the simplest thing to maintain.

Please, consider adding some variables like the ones mentioned here.

**Comment by still-dreaming-1** [comment]
I don't mind trying to put together a PR, but I tend to have a hard time getting started in a new code base (new for me). Is someone able to point me both to the code that makes the [${workspaceFolder} and ${relativeFileDirname} variables available](https://code.visualstudio.com/docs/editor/variables-reference) in other parts of VS Code, and the code that makes [certain variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) available to snippets?

**Comment by Qusic** [comment]
Did a quick search and it is likely to be here: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L222-L290

**Comment by still-dreaming-1** [comment]
I just realized something. Even if I had a variable that provided the relative path after project directory, I would still need to use the incomprehensible snippet expansion feature to remove 'src' from the start of that variable, so it wouldn't actually help me.

**Comment by lukepighetti** [comment]
I'm trying to make a snippet always locate a Theme.js file no matter where it's created. Is there any way to say something like `$RELATIVE(/src/theme)` and have it automatically produce an output like `../theme` if we're located in `src/components/ActionBar.js`?

**Comment by morinted** [comment]
I borrowed the transformation from @DVDima and it worked pretty well for my case. It's not perfect because neighboring components will use `../` and then come back down the path, but that [could be solved by a linter.](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/no-useless-path-segments.md)

Okay, let's say you have:

- Workspace path: `~/git/my-folder`
- Path to relative library I want to create a snippet for: `~/git/my-folder/src/common/lib.js`
- Current file: `~/git/my-folder/src/special/cool/app/file.js`

The following snippet should work up to 6 levels deep:

```json
{
  "Import common lib": {
    "prefix": ["import lib from common", "common-lib", "lib"],
    "body": ["import lib from '${TM_DIRECTORY/.*src(\\/[^\\/]*)(\\/[^\\/]*)?(\\/[^\\/]*)?(\\/[^\\/]*)?(\\/[^\\/]*)?(\\/[^\\/]*)?/${1:+../}${2:+../}${3:+../}${4:+../}${5:+../}${6:+../}/}common/lib.js'"]
  }
}
```

Upon running the snippet, you should get `import lib from '../../common/lib.js'`

### Caveats

- The regex is assuming forward slashes in the directory—would need to be adjusted to backslashes on Windows or adjusted to be agnostic. A backward slash escaped in regex in JSON looks like `\\\\` and would replace `\\/` in all instances above.
- This will work 6-subdirectories deep. If you need fewer or more, you can copy-paste the optional groups `([…])?` and then place more variable insertions `${N:+../}`.

### Explanation

The regex is just trying to find as many groups beyond the common directory (`src` in the example above) and replacing them with `../`. It's very simple. Having to escape the backslashes and putting it into JSON makes it hard to read. Basically we're saying:

`in string TM_DIRECTORY, replace .*app(/[^/]*) with ${1:+../}/}common/lib.js`
 
Transforming `any-garbage-here/app/somedir` → `../common/lib.js`

Then the group for further directories needs to be repeated until you've reached what's practical for your project.

Hope this helps!

**Comment by jaydamani** [comment]
> "const myCommonLib = require('${TM_DIRECTORY/.*src(\\\\[^\\\\]*)(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?(\\\\[^\\\\]*)?/${1:+../}${2:+../}${3:+../}${4:+../}/}common.js');",
I want to do something similar but if I use this one. It results in 

>const myCommonLib = require('../,../,,common.js');

No idea how but I am getting those commas. Is there a way to remove them?

**Comment by aeschli** [comment]
Verified that the RELATIVE_FILEPATH works
