### ISSUE TITLE
Integrated Terminal Displays Nothing On heroku login

### ISSUE THREAD

**Issue by hojungan** [Microsoft/vscode#37579]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---
Letters are not visible when I log in to Heroku via integrated terminal.
Appears to be working fine to log in and push git to heroku master, but terminal displays nothing.
Steps to Reproduce:

1.Open Integrated Terminal
2.Enter 'heroku login'

**Comment by Tyriar** [comment]
Please update VS Code and create a new issue if it's still happening.
