### ISSUE TITLE
[i18n] Wrong translation

### ISSUE THREAD

**Issue by alexlur** [Microsoft/vscode#37571]
- VSCode Version: 1.17.2
- OS Version: High Sierra

https://github.com/Microsoft/vscode/blob/41d590c8ac9bba5b2b023851a730abc28fef7be8/i18n/fra/src/vs/editor/contrib/goToDeclaration/browser/goToDeclarationCommands.i18n.json#L12
https://github.com/Microsoft/vscode/blob/41d590c8ac9bba5b2b023851a730abc28fef7be8/i18n/fra/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.i18n.json#L12

should be `Aperçu`. I navigated around the transifex website but can’t find a way to fix a translation.

**Comment by danyeh** [comment]
@alexlur , I fixed the translation in Transifex according to your suggestion. Thank you for your feedback!
For you information, to fix translation, add a suggestion (of translation) and ask for more vote. 
A quick walk through in this page. https://github.com/Microsoft/Localization/wiki/Localize-an-Open-Source-Product-through-Transifex.
The fix will be pushed to above location around next Tuesday.

**Comment by alexlur** [comment]
@danyeh How do I ask for more votes? I imagine people probably don’t look at finished translations.
