### ISSUE TITLE
It's stoped when I use the cmd tools

### ISSUE THREAD

**Issue by necodon** [Microsoft/vscode#37583]
- VSCode Version:1.17.2
- OS Version:windows 7 ,use phpstudy

Steps to Reproduce:

1.if use the PHP framework Laravel 5.5,and open the laravel-master project,when I try to use the vscode's cmd tools for create a model with the database table,use commond like this: " php artisan make:model Test -m ", vscode is stoped.

2.If I try to use Ctrl+Shift+~ to close the vscode's cmd window , and open the vscode again,to run this commond ,it will be create another one cmd named php,and it's also happened again.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
So you type that command in the terminal? Then

> vscode is stoped.

What do you mean by that exactly? Can you include a screenshot or gif of the problem?
