### ISSUE TITLE
Window always on top when opened from a remote server

### ISSUE THREAD

**Issue by bmakan** [Microsoft/vscode#37586]
VS Code Window stays on top when opened from a remote server via ssh -X command.

Tested with other graphical programs and they worked fine. Didn't stay fixed "on top" over all other local windows.

- VSCode Version: 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5)
- OS Version: CentOS 7 (both remote and local pc)

Steps to Reproduce:

1. Connect to a remote server via: ssh -X uname@server
2. Open a file with vscode
3. Click on the editing field or file list or anywhere inside the window - get window into "focus". Otherwise works fine.
4. Try to swap windows with Alt + Tab
5. VS Code from the remote server stays on top - all other windows are always below until you minimize VS Code from remote. Then it fixes until you focus the remote VS Code window again.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Seems to be https://github.com/Microsoft/vscode/issues/36218
