### ISSUE TITLE
Go to the last line via "Go to Line"

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#37581]
It would be nice to go to the last line & end of the line with negative values:
```
:-1          | go to the last line
:-1,-1       | go to the end of the last line
:,-1         | go to the end of the current line
 ```

**Comment by octref** [comment]
What are those -1 values?

**Comment by usernamehw** [comment]
Any negative value.

**Comment by octref** [comment]
You can track it in https://github.com/Microsoft/vscode/issues/14162.

**Comment by usernamehw** [comment]
But that is not `  "editor.lineNumbers": "relative"`. It is for `"editor.lineNumbers": "on"`

**Comment by octref** [comment]
You can comment on that issue. Personally I'm not in favor of this feature request.
