### ISSUE TITLE
Multiple Process Debugging not possibile with integratedTerminal

### ISSUE THREAD

**Issue by vgammieri** [Microsoft/vscode#37589]
In latest version of VS Code when I debug/launch a long-running process that uses the integratedTerminal setting, and then I decide to launch another process, the latter process will be launched in the same integratedTerminal of the former one, and, because of the fact that the terminal is busy in the execution of the first process, the second one not launch.

Look at the screenshot here below

![screen shot 2017-11-03 at 8 55 09 am](https://user-images.githubusercontent.com/363278/32364423-14766514-c075-11e7-8471-f2cb0d864b28.png)

- VSCode Version: 1.17.2
- OS Version: OSX

Steps to Reproduce:

1. Setup two launch configuration that use "integratedTerminal" as console to lauch two different scripts;
2. Put a breakpoint on the fist script so it will pause and wait;
3. After the first process hit the breakpoint, launch the second one;
4. The launch of the second process will fail.

**Comment by vgammieri** [comment]
I think it's a bug, the same configuration used to launch correctly in previous versions of VS Code

**Comment by weinand** [comment]
@Tyriar did something change in this area? I haven't touched anything on the debug side.

**Comment by Tyriar** [comment]
@weinand nothing comes to mind that would have impacted this. It looks like from this file that you're launching a terminal and reusing it:

https://github.com/Microsoft/vscode/blob/af6b8302fae66a2898ac8180c98221892d6c765f/src/vs/workbench/parts/debug/electron-browser/terminalSupport.ts#L45-L53

If the shell is not accepting input because the process is still running as the screenshot suggests, this is as expected. The shell needs to be either accepting input or you need to kill it and respawn the shell.

**Comment by vgammieri** [comment]
Is it possible to create a dedicated instance of the 'integratedTerminal' for each launch configuration? So, launching two or more different process won't share the same instance. Even more, you can create a configuration key in the launch configuration to specify if you want to share or not the integratedTerminal.

**Comment by Tyriar** [comment]
> Is it possible to create a dedicated instance of the 'integratedTerminal' for each launch configuration?

It's certainly possible, this is how I was expecting it to work.

**Comment by weinand** [comment]
@Tyriar is it possible to find out whether the integrated terminal is accepting input? 

For **external** terminals I'm able to get this information (at least on macOS), so I can reuse an external terminal if it is not busy running a command.

**Comment by Tyriar** [comment]
@weinand not currently and I'm not aware of how you would. Perhaps you can pull that sort of info by running a tool like `lsof`, I've seen that used to get the `cwd` of a shell process.

**Comment by weinand** [comment]
The fix tries to determine whether the Integrated Terminal's shell process has at least one child process. If it has, we assume that the terminal is busy and a new terminal is created.
With this a compound launch should result in multiple terminals.
