### ISSUE TITLE
Ctrl+F  leads to nothing sometimes

### ISSUE THREAD

**Issue by Stone-Zeng** [Microsoft/vscode#37582]
- VSCode Version: v1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder, then press Ctrl+F.
2. No find dialog appear.
3. But from menu, edit -> find is ok, and use Ctrl+H to replace text is normal as well.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Ctrl + Shift + P -> Preferences: Open Keyboard Shortcuts -> Type in "ctrl f".

There must be some other keybindings that's bound to ctrl+f. You can disable them.
