### ISSUE TITLE
Please uninstall the 32-bit version of Code while installing this 64-bit version.

### ISSUE THREAD

**Issue by Fang3s** [Microsoft/vscode#37584]
I uninstall Visual Code to installl 64-bit version of Visual Code, but it pops up a window with the conent of "Please uninstall the 32-bit version of Code while installing this 64-bit version."

- VSCode Version: forgot
- OS Version: Windows 7

Steps to Reproduce:

1. uninstall 32-bit version of Visual Code
2. install VSCodeSetup-x64-1.17.2.exe or reboot and install it

**Comment by joaomoreno** [comment]
You can try reinstalling 32, uninstalling it and then install 64.
