### ISSUE TITLE
Unable to setup codebase of VSCode to contribute

### ISSUE THREAD

**Issue by rahul1995** [Microsoft/vscode#37595]
I cloned this repository and run scripts\npm.bat on my windows machine and got these errors:
![vscode-error](https://user-images.githubusercontent.com/7647789/32369244-7df4312c-c0ae-11e7-8960-7c757a55e729.PNG)

**Comment by octref** [comment]
@jrieken since saw your name in the error log.

**Comment by rahul1995** [comment]
Tried on home network now, it seems like cloning is done but I got another warning and error messages.
![vscode-warn](https://user-images.githubusercontent.com/7647789/32406341-b2a05fba-c19c-11e7-83c6-1444ac20d178.PNG)
![vscode-err2](https://user-images.githubusercontent.com/7647789/32406346-bab5e9c2-c19c-11e7-9812-3d2be724d109.PNG)

**Comment by jrieken** [comment]
Did you go through this guide? https://github.com/Microsoft/vscode/wiki/How-to-Contribute#installing-prerequisites

**Comment by jrieken** [comment]
Closing this because this works well on our dev machines and all our build machines. Feel free to ask more questions, but no code change from our side is planned

**Comment by rahul1995** [comment]
Of course, no code needs to be changed. But didn't anyone else get the same error yet? Or any hint after seeing my error screenshots?
