### ISSUE TITLE
Strange Characters Being Displayed in VSC Editing PowerShell Scripts

### ISSUE THREAD

**Issue by jonconwayuk** [Microsoft/vscode#37598]
- VSCode Version: 1.17.2
- OS Version: Windows 10 1607 (14393.1770) - seems to happen in all OS Versions that I have tested so far (i.e. different varieties of Windows 10 and Windows Server 2012 R2 and WS 2016)

Steps to Reproduce:

1. In some PowerShell scripts I can see strange characters, whilst in other text editors (such as ISE, Notepad and Notepad++ they appear as expected. Seems to be related to certain quotes, graves being used but other editors seem to manage fine.

2. Examples

The text being used in the first sample is:

[String] $SwitchName = 'ProdSwitch’
[String] $TeamName = ‘ProdTeam’

![image](https://user-images.githubusercontent.com/26324529/32372078-43b023ea-c08b-11e7-896b-e778b326c18c.png)
![image](https://user-images.githubusercontent.com/26324529/32372097-58172ba8-c08b-11e7-9c77-e462e73d8c72.png)
![image](https://user-images.githubusercontent.com/26324529/32372108-64a52474-c08b-11e7-8636-1c492eb9c992.png)
![image](https://user-images.githubusercontent.com/26324529/32372121-68b527f8-c08b-11e7-9163-7a651a33e3df.png)

The text being used in the second sample is:

New-VMSwitch –NetAdapterName $TeamName –Name $SwitchName –AllowManagementOS $true -Confirm:$false

![image](https://user-images.githubusercontent.com/26324529/32372227-e1c818ee-c08b-11e7-9151-a5f210cbf971.png)
![image](https://user-images.githubusercontent.com/26324529/32372238-ef7798f2-c08b-11e7-8ba4-97cae3b92365.png)
![image](https://user-images.githubusercontent.com/26324529/32372259-ffec8120-c08b-11e7-95c9-ee3302a59c2b.png)
![image](https://user-images.githubusercontent.com/26324529/32372275-14b6e01e-c08c-11e7-97a0-3caa77f39ef0.png)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I believe this is an encoding issue. ISE saves files with a specific encoding and VS Code does not automatically detect the same encoding.

**Comment by bpasero** [comment]
@jonconwayuk you might want to configure the files.encoding for powershell files to be `cp1252` or configure auto guess encoding for powershell to see if that helps.
