### ISSUE TITLE
Support %APPDATA%\Code\User\settings.json to be a symlink

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#37591]
- OS Version: Windows 10, Version 1703 (OS Build 15063.674)

In order to save and share my settings for VS Code across multiple development machines, I have created I personal git repository to store the `keybinding.json` and `settings.json` files located in `%APPDATA%\Code\User\` on Windows.

I'd like the `settings.json` and `keybindings.json` files to be symlinks so that I can store them in my Git repository instead to easily keep them up to date.

However, if I create symlinks in `%APPDATA%\Code\User\` VS Code complains everytime I try to open user settings with the error message: 
> Unable to create '%APPDATA%\Code\User\settings.json' (Error: `ENOENT`: no such file or directory, open '%APPDATA%\Code\User\settings.json').

**Comment by sandy081** [comment]
@bpasero When a user opens settings, we check if the settings file exists or not, If does not, we create one with default contents. Looks like the file exists check is returning false. 

@couven92 Can you make sure that the file exists. You can also try opening the file with VS Code directly

**Comment by bpasero** [comment]
@sandy081 yeah that makes sense, but I was assuming that the file exists as link to the actual file. 

I cannot reproduce on macOS so maybe this is an issue with the link on Windows. 

@couven92 how did you create that link?

**Comment by couven92** [comment]
@bpasero 
```.bat
MKLINK %APPDATA%\Code\User\settings.json "%PATH_TO_PRIVATE_GIT_REPO%\VsCode\settings.json"
```

**Comment by couven92** [comment]
And this only works if you enable symlinks in the Group Policy Editor on Windows. By default Windows does not allow symlinks.

**Comment by couven92** [comment]
### Workaround
Instead of symlinking `settings.json` and `keybindings.json` individually, you just create a regular NTFS junction link for the entire directory and add `workspaceStorage` to a `.gitignore` in that directory.

```.bat
IF EXIST %APPDATA%\Code\User RENAME %APPDATA%\Code\User User.bak
MKLINK /J %APPDATA%\Code\User "%PATH_TO_PRIVATE_GIT_REPO_FOLDER%"
ECHO workspaceStorage>> %APPDATA%\Code\User\.gitignore
```

**Comment by bpasero** [comment]
It is possible that node.js does not support those kind of links which would explain the file not found error.

**Comment by couven92** [comment]
Yeah, `ls` distributed with GnuWin32 also has troubles with Windows symlinks... Probably comes from poor support for symlinks when people ported Win32 to POSIX-like common APIs.

Since Junction links are exposed to POSIX-like libraries like a regular directory, I can confirm that using my workaround https://github.com/Microsoft/vscode/issues/37591#issuecomment-341669901 works just fine!
