### ISSUE TITLE
Support variables in settings.json (e.g. ${workspaceRoot})

### ISSUE THREAD

**Issue by sevein** [Microsoft/vscode#3759]
I want to override `go.gopath` from my workspace settings file (`.vscode/settings.json`). This file is likely going to be tracked by my git repository. I want the value of `go.gopath` to be something like `${workspaceRoot}:${workspaceRoot}/vendor` but vscode doesn't seem to expand variables in `settings.json`. Is there a solution to this?

**Comment by bpasero** [comment]
#2809
