### ISSUE TITLE
js extension can be transferred to the definition, but changed to jsx extension will not work.

### ISSUE THREAD

**Issue by yueduz** [Microsoft/vscode#37599]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.13.9-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
vscode-css-modules|cli|0.2.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Please report extensions specific issues in extensions repository. You'll likely need to enable them for jsx in addition to js.

**Comment by yueduz** [comment]
@octref But this feature is not from an extension
