### ISSUE TITLE
The new Logo is not easy to identify, it much harder then previous blue one.

### ISSUE THREAD

**Issue by turnerguo** [Microsoft/vscode#37597]
The new Logo is not easy to identify, it much harder then previous blue one.

**Comment by ChenyeJin** [comment]
Agree with you.

**Comment by bpasero** [comment]
The next release will have the blue logo back. See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md#blue-logo-for-stable

**Comment by kuangyazhou** [comment]
I can't agree more!!!!the blue logo is so beautiful
