### ISSUE TITLE
Integrated Terminal Displays pixel blocks

### ISSUE THREAD

**Issue by tomfriwel** [Microsoft/vscode#37593]
- VSCode Version:1.17.2 (1.17.2)
- OS Version:macOS 10.13 (17A405)

Sometimes I run a time-consuming task or lots of logs.
This is not appear in ***Terminal***.

<img width="1032" alt="screen shot 2017-11-03 at 17 00 16" src="https://user-images.githubusercontent.com/11268235/32366412-f7062218-c04b-11e7-8be6-f3a7275e2122.png">

Reproduces without extensions: Not sure

**Comment by Tyriar** [comment]
Weird, does the problem go away if you resize the terminal upwards?

**Comment by tomfriwel** [comment]
@Tyriar Yes.

**Comment by Tyriar** [comment]
Looks like the canvas is being corrupted somehow. I'm guessing this is an upstream issue as there are no concurrent draws happening.

**Comment by trent-boyd** [comment]
Following this. I'm running into the same issue in macOS 10.12.6 when running a multi-monitor setup with Code in full-screen mode. Resizing the terminal doesn't fix it. I have to move it from a full-screen space on one monitor to another and back again. Seems like that triggers a redraw somehow.

I looked for a config to disable the new canvas-based terminal in favor of the old one, but couldn't find it.

**Comment by Tyriar** [comment]
@trent-boyd I think you might be seeing https://github.com/Microsoft/vscode/issues/34320

cmd++ followed by cmd+- should workaround this problem if so.

**Comment by trent-boyd** [comment]
@Tyriar: You're correct! I guess I didn't look at the screenshot as closely as I thought I did. 🙃
