### ISSUE TITLE
Issue with Format Document feature on html file

### ISSUE THREAD

**Issue by coder054** [Microsoft/vscode#37594]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.0
vscode-intelephense-client|bme|0.7.2
npm-intellisense|chr|1.3.0
jsrefactor|cms|1.5.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.2
Vue2|duc|0.1.3
EditorConfig|Edi|0.11.1
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.2
code-sync|gol|2.5.0
vscode-firefox-debug|hbe|0.17.0
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
intellij-idea-keybindings|k--|0.2.16
csstriggers|kis|0.3.1
vue|liu|0.1.5
Go|luk|0.6.66
php-namespace-resolver|Meh|0.8.0
debugger-for-chrome|msj|3.4.0
snippet-creator|nik|0.0.4
vetur|oct|0.10.1
laravel-blade|one|1.9.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.3.4
laravel-helpers|raf|0.2.2
java|red|0.13.0
laravel-artisan|rya|0.0.8
easy-snippet-maker|tar|0.0.6
open-in-browser|tec|1.1.0
bootstrap4-vscode|the|3.0.0
vscode-java-debug|vsc|0.2.0

---

Steps to Reproduce:

1. Clone this repo then open it with vscode
2. open index.html file (in root folder)
3. Scroll to line 51 (embed vue.js)
4. Format Document (Ctrl + Alt + L) for me
5. Vue.js is delete !!!!

Reproduces without extensions: No

**Comment by maxibanki** [comment]
Which repository?

**Comment by aeschli** [comment]
Closing due to lack of information.
Likely a dup of #36574
