### ISSUE TITLE
Git current branch status indicator show hash instead of name

### ISSUE THREAD

**Issue by syts** [Microsoft/vscode#376]
The current branch shows as a hash at the left of the status bar, instead of as a name - e.g. "bac18a40" instead of "mainline"

Version 0.10.1, Linux 64-bit

**Comment by joaomoreno** [comment]
Is `mainline` a remote branch or a tag?

**Comment by syts** [comment]
Mainline is a remote branch.  When I run git status I get:
# On branch mainline
# Your branch and 'origin/mainline' have diverged,
# and have 1 and 7 different commits each, respectively.

When I run git branch -vv I get:
* mainline         bac18a4 [origin/mainline: ahead 1, behind 7]

Vscode is correctly identifying mainline as a branch since when I run "git checkout" in Vscode (by clcking on the status bar) the dropdown list shows "mainline  Branch at bac18a40".

**Comment by joaomoreno** [comment]
One more thing, what's your git version?

**Comment by ibss7270** [comment]
#281 Git remote options (push, pull & sync) are disabled

**Comment by syts** [comment]
my version is:
git version 1.7.9.5

**Comment by joaomoreno** [comment]
Absolutely, looks very similar to #281.

I suggest to try the latest version and to install git `>= 2.0.0`.
