### ISSUE TITLE
Extensions: confirmation dialog not coming 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37609]
OS: Win 10
Latest insider

1. Install some extension
2. Click to uninstal it in the extensions viewlet -> the confirmation dialog never arrives and leaves the viewlet in a bad state
3. Only once I close vscode I get the dialog

I can reproduce this constantly on my win10 vm. However I can not get this bug on my mac
Assigning to October so you investigate

**Comment by sandy081** [comment]
I cannot reproduce it in my win10 VM and also on win7 machine. 

@isidorn Unassigning milestone. We can look into this why it is happening on your VM

**Comment by isidorn** [comment]
@sandy081 sure, drop by my table whenver you want. It is probably an electron issue.

**Comment by sandy081** [comment]
@isidorn Closing this and I have not got any such complaints.
