### ISSUE TITLE
Help -> About text can't be selected

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#37608]
- VSCode Version: Code - Insiders 1.18.0-insider (168f0b2ba602dbe4a93f5b173435075f482a5c1b, 2017-11-03T05:19:36.263Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Help -> About
2. Try to select text

**Comment by maxibanki** [comment]
If the point of it is to report an issue if the information of it, then it is a duplicate of #36774. (Help => Report Issues)

**Comment by andy-ms** [comment]
In this case I wanted to comment on a TypeScript issue with the version I was using.
What is the point of providing the commit hash if it can't be copied? I'm certainly not going to be able to remember it.

**Comment by octref** [comment]
@andy-ms A temp workaround is Help -> Report Issue, which will copy the commit with other info to prefill the GitHub issue template.

**Comment by maxibanki** [comment]
Another workaround is to open the about message box and press Ctrl + C to copy the full content.

**Comment by bpasero** [comment]
Added a "Copy" button:

![image](https://user-images.githubusercontent.com/900690/33016409-b7cc90ea-cdee-11e7-8546-dfb2470c39db.png)
