### ISSUE TITLE
Smoke test: Extension test failing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37601]
Test smoke test is failing for me on Linux:

![image](https://user-images.githubusercontent.com/900690/32376311-bec6cc6e-c0a4-11e7-9322-b4f0e47af730.png)

Maybe related to @ramya-rao-a latest changes?

**Comment by mjbvz** [comment]
Just tested with master on Ubuntu 16.06 and saw this working again

**Comment by ramya-rao-a** [comment]
Thanks @mjbvz!
