### ISSUE TITLE
Tab/keys navigation in Search panel

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#37614]
When searching for a file using keyboard controls, you can use Shift+Ctrl+F to switch to the `Search` panel.

- Entering a search text, then pressing `Tab` should navigate to the next text input, which is "include files" . Instead it will first tabstop on various buttons, so you have to Tab 5 times or use mouse to click the include files input.

- It would be nice if pressing `Esc` while focused on any of the inputs would return to the Explorer panel. The rationale behind that is that in many IDEs "Search in files" is a popup window which can be closed with Esc to return back to normal edition.

**Comment by roblourens** [comment]
The first issue is https://github.com/Microsoft/vscode/issues/34676. You can use the arrow down key instead until that's fixed.

For the second, I see the point, but our model is that all the viewlets in the sidebar are tabs that you can switch between. They are all equal, not just popups over the main view.
