### ISSUE TITLE
Explorer: expands files instead of folders

### ISSUE THREAD

**Issue by petro-shkuratenyuk** [Microsoft/vscode#37612]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create file and folder with the same names.
2. try to expand folder
![untitled](https://user-images.githubusercontent.com/26718406/32380867-ec06ac02-c0b9-11e7-8e64-99f73db80b5e.png)

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
@petro-shkuratenyuk I can not reproduce this. What I did is created a folder named `labels` and a file called `Labels.js`. Clicking on the labels folder correctly expands that folder for me.
Can you reproduce this in any folder?
On what OS are you?

Can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
