### ISSUE TITLE
Toggled terminal within VSCode disappears when resizing window

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#37617]
_From @alexandreday on November 3, 2017 13:56_

## Environment data
VS Code version:   1.17.2
Python Extension version:  0.7.0
Python Version:   3.5
OS and version:    OSX 10.13 (High Sierra)

## Actual behavior
Toggled terminal within VSCode has a bug.
When resizing terminal within VSCode, causes the terminal to disappear.
By "disappear" I mean that the command line prompt is no longer available.

## Steps to reproduce:  
-  Resize VSCode window and terminal window. The bug is not always present.
-  By "disappear" I mean that the command line prompt is no longer available. 

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

_Copied from original issue: DonJayamanne/pythonVSCode#1367_

**Comment by Tyriar** [comment]
Is the logs part meant to mean there are were no logs?

Also could you show a screenshot of before and after?
