### ISSUE TITLE
Multiple line Indent Issues with vscode 1.17.1

### ISSUE THREAD

**Issue by aliwatters** [Microsoft/vscode#37618]
Highlighting multiple lines and then hitting tab to indent does not work. Using shift-tab to undent (de-indent?) - works as expected.

- VSCode Version:  1.17.2 
- OS Version: mac OS sierra - 10.12.6

Steps to Reproduce:

1. highlight multiple lines
2. click tab - no effect
3. if pre-indented - shift-tab works as expected

Extensions: 
vscodevim - 0.2.3
donjayamanne.python 0.7.0
esbenp.prettier-vscode 0.24.0
PeterJausovec.vscode-docker 0.0.20
ms-vscode.azure-account 0.1.3

Reproduces without extensions: No

Works as expected without the extensions...

Buggy capture - imagine tab being hit where nothing happens...
![indent-undent-bug](https://user-images.githubusercontent.com/1106863/32384092-06553404-c077-11e7-961e-a1a7310ba3e6.gif)

**Comment by maxibanki** [comment]
Deactivate extension by extension extension to see what causes this behavior. Then create an issue in the repository of it.

**Comment by octref** [comment]
> vscodevim - 0.2.3

It's a Vim bug. But they are already on 0.10.2 and you are still using 0.2.3? Time to upgrade.

**Comment by aliwatters** [comment]
Apologies - must have misread the version of vscodevim -- I'm on 0.10.2

I'll open a report there (or plus one an existing)
