### ISSUE TITLE
Sequence of keybindings only works when focus begins in terminal

### ISSUE THREAD

**Issue by kortina** [Microsoft/vscode#37619]
- VSCode Version: 1.17.2 (1.17.2)
- OS Version: 10.12.6

I have the following in my `keybindings.json`:

```
    // Move focus up to editor:
    { "key": "ctrl+a ctrl+k", "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"},
    // Move focus down to the terminal:
    { "key": "ctrl+a ctrl+j", "command": "workbench.action.terminal.focus", "when": "editorFocus"},
```

The sequence of multiple keys to move from editor down to the terminal works fine, but the sequence to move back up to the editor once the terminal has focus does not register.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I think the problem here is that chord keybindings don't work in the terminal, not sure what a good solution to this would be as currently the keystroke is checked if the command (`workbench.action.focusActiveEditorGroup`) is run and if it doesn't it's sent to the shell.

**Comment by Tyriar** [comment]
Unfortunately this is just a limitation of our keybinding system that we cannot evaluate chord keybindings within the terminal.
