### ISSUE TITLE
Code expand/collapse

### ISSUE THREAD

**Issue by sdwangbaotong** [Microsoft/vscode#3761]
Hi guys, I'm really look forward the official release of VSCode, I have used it for some time and what I really expected is the code expand and collapse implementation, for a long code file it realy boring to use scrollbar to locate the code line. Not sure it's in your list, it realy a simple but useful feature.

**Comment by isidorn** [comment]
Yes, this feature will be a part of VSCode 0.10.10 that will be released very soon.
Until it is released you can use VSCode 0.10.10 - insiders - which already has code expand / collapse

**Comment by sdwangbaotong** [comment]
cool, by the way what your release cycle, one build each week?

**Comment by isidorn** [comment]
One stable build each month.
Insiders builds are usually one week out before the stable build

**Comment by sdwangbaotong** [comment]
got it, thanks for your feedback.
