### ISSUE TITLE
Allow extensions to specify a different file than README to be displayed on the marketplace

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#37625]
It would be great if I could specify the path to some alternative markdown file in the ``package.json`` for inclusion in the marketplace instead of the README.md content. Essentially, if that setting is there in ``package.json``, don't include the content from README.md on the marketplace, but instead use the content of the file specified.

The reason is that I want the README.md to contain information that is really more meant for the devs of the extension: status badges for builds, instructions how to dev on the extension etc. But for the users of the extension I want different content to be shown in the marketplace.

**Comment by joaomoreno** [comment]
Moved to https://github.com/Microsoft/vscode-vsce/issues/210
