### ISSUE TITLE
vs code doesn't show vendor folder for golang project

### ISSUE THREAD

**Issue by louweihua** [Microsoft/vscode#37624]
Probably a plugin issue. gogland doesn't show it nicely (a special icon)

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
Go|luk|0.6.66
mssql|ms-|1.2.0
java|red|0.13.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Can you check your settings `files.exclude`?

**Comment by ramya-rao-a** [comment]
You mean the vendor folders don't show up in the explorer view?

**Comment by louweihua** [comment]
@octref there is no such file files.exclude in the folder
@ramya-rao-a you are right.

**Comment by louweihua** [comment]
Interesting thing happened. 
1. on a not related event, I enabled displaying hidden file on my mac (https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/)
2. restart vs code

Now the vendor folder showed up in the explorer view! btw the vendor folder is not hidden folder and gogland can show it properly before I did anything. 

Anyway, I couldn't explain why but the issue is gone now. Please feel free to close it. Thanks.

**Comment by ramya-rao-a** [comment]
If you disable showing of hidden files, then does the vendor folder show up in the Finder?

**Comment by louweihua** [comment]
It looks like that showing hidden files or not is not relevant. The issue appeared again. I don't know why it worked. Anyway, please feel free to repro it if needed. It is not a big deal. You can close this issue or I can close it. Thanks.
