### ISSUE TITLE
Explorer: loading progress shows without delay on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37622]
Steps to Reproduce:

1. open a folder
2. the explorer shows a spinning progress bar right away below the title

=> this makes me feel the entire UI loads slow and we need progress
=> compared to the editor where we are careful of showing progress directly, instead we have a delay

It seems to me we no longer have a delay in the explorer before showing progress.

**Comment by isidorn** [comment]
@bpasero No we still show it with a delay. I am not sure I can repro the exact behavior you are seing. To be more precise I see slight progress for half a second, but I seem to see the same with the current stable.

We could increase the delay [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L832)
Or we could decrease the delayer timeout [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L793)

**Comment by bpasero** [comment]
I am not sure why this only shows up now, but I pushed a fix.

**Comment by isidorn** [comment]
@bpasero thanks for fixing this
