### ISSUE TITLE
Unable to update version

### ISSUE THREAD

**Issue by hulang** [Microsoft/vscode#3762]
The version I used is:0.10.8
I see the site is written on:0.10.9
But it's in GitHub:0.10.12
Why?0.10.10/0.10.11 Where is it?

**Comment by isidorn** [comment]
0.10.10 and 0.10.11 will be released soon - probably some time this week.
On GitHub is a newer version which is currently in development and will be released only after it is tested in the future. Thus the misalignment in the versions
