### ISSUE TITLE
I want to collaborate with the translation

### ISSUE THREAD

**Issue by Isaachi1** [Microsoft/vscode#37633]
I'm interested in helping to improve the Portuguese translation of Brazil, how should I proceed?

**Comment by maxibanki** [comment]
Take a look in [the wiki](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project). Please close the issue.

**Comment by Isaachi1** [comment]
Thank you

**Comment by maxibanki** [comment]
Please close your issue, because your question was solved. :+1:
