### ISSUE TITLE
Git changes not working correctly

### ISSUE THREAD

**Issue by goleary** [Microsoft/vscode#37630]
I've noticed lately that when I click on a changed file in the source control tab I don't always see the changes to that file on the working tree.  Screenshot below shows that I have one file selected but the changes aren't being displayed.
![image](https://user-images.githubusercontent.com/16123225/32395936-7bb9d97e-c0a0-11e7-82a5-b7b436d25976.png)

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|5.6.5
vscode-scss|mrm|0.6.2
sort-lines|Tyr|1.3.0

---

Steps to Reproduce:

not sure if this is reproable but i've seen it happen multiple times

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/36556#issuecomment-341363316
