### ISSUE TITLE
VSCode Debugger halts once every time I run my application

### ISSUE THREAD

**Issue by weeco** [Microsoft/vscode#37632]
- VSCode Version: 1.17.2
- OS Version: Win 10 x64

Description:
Every time I run my application it halts at the exact same line, requiring me to press "continue". Once it's running the debugger won't halt there anymore again. It looks like this then:

![Alt text](https://i.imgur.com/9f9EZfj.png)

Steps to Reproduce:
- It's 100% reproduceable in a solution I am working on and I also experienced it in other solutions I was working on. Unfortunately I can't tell what exactly is causing it.

Reproduces without extensions: Yes!

**Comment by seanpoulter** [comment]
How are you starting the debugger? There's a `launch.json` attribute called `stopOnEntry` that will cause the debugger to break when the program launches. Have a look at `.vscode\launch.json`. You can also [refer to the docs](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).

**Comment by weeco** [comment]
I am not using this option. Below you can find my used launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/src/index.ts",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "console": "integratedTerminal",
            "smartStep": true,
            "runtimeArgs": [
                "--max-old-space-size=4096"
            ]
        }
    ]
}
```

**Comment by roblourens** [comment]
Sounds related to https://github.com/Microsoft/vscode-node-debug2/issues/144, since that's probably the entry point of your program, but you don't seem to be compiling your TS at runtime, which is the issue there.

- Which version of Node?
- Can you try the Insiders build?
- Can you set `"trace": true` in your launch config and upload the log here?

**Comment by weeco** [comment]
**Node v. 8.2.1**

**Trace log** (It wrote until line ~2160, then the application halted at the same line as shown). I clicked continue afterwards: http://www46.zippyshare.com/v/ILVfdodj/file.html

**Comment by roblourens** [comment]
The log says you have a breakpoint on line 39 of `cr-battle-log.js`, then it broke at what it thinks is the matching location in the .ts file. If you have .ts files, I recommend just setting breakpoints in the .ts file or disabling sourcemaps.

> I wasn't able to replicate the issue with the VSCode Insiders build

Good to hear but did you have the same breakpoint?

**Comment by weeco** [comment]
@roblourens I checked the js file and there was indeed a breakpoint set (in line 26) which is by the way exact the same line the debugger in the typescript file halts. I have never set this breakpoint (I never check the transpiled js files) and the breakpoint at this line doesn't make sense. It's set in the middle of a multiline text.

After removing this weird breakpoint in the js file the debugger is not halting anymore. Thanks for your input and investigation
