### ISSUE TITLE
how to choose node version for debug

### ISSUE THREAD

**Issue by linwalker** [Microsoft/vscode#37639]
- VSCode Version:1.17.2
- OS Version:

Steps to Reproduce:

1. I have set my default node version to be 7.8.0:
```
linyuhuadeMacBook-Air:koa2-note linyuhua$ nvm alias default 7.8.0
default -> 7.8.0 (-> v7.8.0)
linyuhuadeMacBook-Air:koa2-note linyuhua$ which node
/Users/linyuhua/.nvm/versions/node/v7.8.0/bin/node
```

2.howerver, when I start to debug it shows:
```
Debugging with legacy protocol because Node.js v6.10.0 was detected.
/Users/linyuhua/.nvm/versions/node/v6.10.0/bin/node --debug-brk=48477 --nolazy demo/route/index.js 
Debugger listening on [::]:48477
/Users/linyuhua/dailycode/koa2-note/demo/route/index.js:4
app.use(async (ctx, next) => {
              ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
```
the node version used for debug is stiil 6.10.0

Reproduces without extensions: Yes

**Comment by alycda** [comment]
I believe you're going to need to configure a launch.json file and set `runtimeExecutable` to `/Users/linyuhua/.nvm/versions/node/v7.8.0/bin/node`. Hope this helps

**Comment by auchenberg** [comment]
Have you restarted VS Code after changing your default Node alias? @linwalker

**Comment by auchenberg** [comment]
Have you restarted VS Code after changing your default Node alias? @linwalker

**Comment by weinand** [comment]
Please see https://github.com/Microsoft/vscode/issues/1895 or https://www.seafish.io/blog/nvm-and-vs-code/ for details.

**Comment by linwalker** [comment]
@auchenberg thank you, restart VS Code after changing default Node alias worked, the node version used for debug changed to 7.8.0

**Comment by linwalker** [comment]
@alycda your idea is another effective solution
