### ISSUE TITLE
Font "ripping"/aliasing on ubuntu 16.04 with 1.17.2

### ISSUE THREAD

**Issue by oderby** [Microsoft/vscode#37631]
After updating from 1.17.1 to 1.17.2, I'm seeing some very bad aliasing/artifacts in the code window (all fonts affected):
![image](https://user-images.githubusercontent.com/1351158/32399965-f26e2c7a-c0b7-11e7-93a5-6bbe05433e2a.png)
(notice especially on the settings pane, e.g. font for setting "ruby.rctComplete.commandPath" has strange artifacts between the characters)

Note - this problem was not present until just now, when I opened the code editor after it auto-updated to 1.17.2. That said, it's possible something on my machine is causing issues, so I'll continue to debug as I have time and report back. Any ideas of what to test/check are welcome. Finally, apologies if this is a dupe, but I couldn't find any reports similar to this.

- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04.3 LTS

Reproduces without extensions: Yes

**Comment by misho85** [comment]
@oderby try downgrading libfreetype6 https://github.com/Microsoft/vscode/issues/35675

**Comment by FacepalmMute** [comment]
libfreetype6 downgrade to 2.8.0-2 fixed it for me.
