### ISSUE TITLE
Cannot install .vsix in Code OSS

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#37644]
- VSCode Version: OSS
- OS Version: Windows

Steps to Reproduce:

1. Build and launch Code OSS from source
2. Try to install this [.vsix](https://github.com/hoovercj/textmate-bug-repro/blob/master/textmate-bug-repro-0.0.1.vsix) file from the extensions viewlet.

Expected:
It is installed in Code OSS the same as it is installed in the official VS Code release.

Actual:
Nothing happens.

Discovered while trying to install the extension to debug #37643

**Comment by sandy081** [comment]
I think this should be supported. Will investigate.

**Comment by sandy081** [comment]
Fixed by 69bffd733dfbcc4b353f78096acf08777723059f

**Comment by ramya-rao-a** [comment]
@sandy081 I can verify that we can now install extensions from vsix in Code OSS, but I see the below in the console once the installation is complete:

![image](https://user-images.githubusercontent.com/16890566/33681108-6e8696f6-da78-11e7-9091-b4daf1c385fe.png)

Also, there is no progress indicator, when the installation is well.. in progress.
