### ISSUE TITLE
Indent guides for indented statements keep going till the next statement

### ISSUE THREAD

**Issue by affanshahid** [Microsoft/vscode#37642]
There is a need to handle formatting situations like the following:
![2017-11-04 16_28_56-index js - monitori-db-nodejs-api - visual studio code](https://user-images.githubusercontent.com/17955210/32404979-c9da9d4a-c17d-11e7-9305-b41617e590f1.png)

The guides keep going even onto empty lines, until the next statement is encountered.

**Comment by alexandrudima** [comment]
I'm assuming this is a screenshot of JavaScript. 

This is as designed; that's how the line indent - indentation strategy we have implemented for C-style languages works. 

We behave in the way you describe for off-side languages. See [here](https://en.wikipedia.org/wiki/Off-side_rule) a list of off-side languages.

e.g. JavaScript (non off-side language):
![image](https://user-images.githubusercontent.com/5047891/32434304-0593e312-c2de-11e7-950c-4f1ea217d96d.png)

e.g. Python (off-side language):
![image](https://user-images.githubusercontent.com/5047891/32434333-19be97ce-c2de-11e7-96ea-85f2a9ae5374.png)
