### ISSUE TITLE
$eslint-stylish problem matcher fails on large errors messages.

### ISSUE THREAD

**Issue by Aliaksei-Martinkevich** [Microsoft/vscode#37641]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:
1. Setup task in tasks.json with $eslint-stylish problem matcher
2. Files to check with eslint should generate errors large enough (larger than terminal width). For example use big font size, long errors names and long errors descriptions.
![terminal](https://user-images.githubusercontent.com/16012334/32404828-a7d4e354-c169-11e7-8139-1eef2cfef586.PNG)
3. Problem matcher recognise wrapped part of error message as a file name.
![warning](https://user-images.githubusercontent.com/16012334/32404851-43d98e76-c16a-11e7-8e9c-74bfb4bd1dbf.PNG)
4. Click on such warning leads to error
![error](https://user-images.githubusercontent.com/16012334/32404861-72864840-c16a-11e7-8ad1-ae6dd95db10a.PNG)

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@Aliaksei-Martinkevich this is already addressed in the insider builds and will ship with the next release.
