### ISSUE TITLE
Exclude files and folders listed in .gitignore

### ISSUE THREAD

**Issue by Pym** [Microsoft/vscode#3764]
Hello,

I just tried VS Code recently and I was surprised to see it didn't exclude the files and folders listed in my `.gitignore` file.

I think an option allowing us to hide those files in the Explorer would be really nice.

Here is how Atom does it:

<img width="770" alt="screen shot 2016-03-07 at 10 31 42" src="https://cloud.githubusercontent.com/assets/89233/13565344/d476f9ea-e44f-11e5-896b-3a637ee36153.png">

And when this option isn't on, Atom colorizes the excluded files like that:

<img width="167" alt="screen shot 2016-03-07 at 10 36 52" src="https://cloud.githubusercontent.com/assets/89233/13565471/8abf97a2-e450-11e5-94ad-771193dd25c0.png">

**Comment by bpasero** [comment]
#78

**Comment by Pym** [comment]
I searched for other "gitignore" issues but didn't saw you mentioned the Explorer part in this one.

**Comment by pedrovagner** [comment]
Duplicated https://github.com/Microsoft/vscode/issues/178

**Comment by ialexryan** [comment]
PSA for anyone else landing on this issue like I just did:

As of March 2017, VS Code has supported excluding VCS ignored files from Search results, either from the search bar or in settings. [Here's how.](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_11.md#text-search-improvements)
