### ISSUE TITLE
HTML Inline SVG performance drop

### ISSUE THREAD

**Issue by pcjmfranken** [Microsoft/vscode#37646]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.22.0
vscode-color|ans|0.4.5
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.2
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.2
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
autofilename|Jer|0.1.3
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.4.0
vscode-docker|Pet|0.0.20
seti-icons|qin|0.1.3
es6-mocha-snippets|spo|0.0.5
language-stylus|sys|1.8.0
sort-lines|Tyr|1.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Create an HTML file
2. Place some reasonably long SVG code inline
3. Switch back and forth between different tabs a couple of times including the tab including the SVG
4. Seemingly at random syntax highlighting will break, Intellissense popups will stop displaying, emmet expand command will stop working altogether, VSCode will start taking a second to respond when you switch back to it from a different window and switching between tabs will start becoming slow
5. Restart VSCode and the problem is solved again

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Can you share a sample svg where you can repro this consistently?
Also, are you able to repro this in the latest VS Code version? 1.18.0 or 1.18.1 ?

**Comment by pcjmfranken** [comment]
Thanks for your reply.

With the exception of the syntax highlighting not working in long lines, I haven't been able to repro it consistently and not at all since 1.18.0. Will run more tests and update.

**Comment by codev0** [comment]
- VSCode Version: 1.19.1 (1.19.1) (0759f77bb8d86658bc935a10a64f6182c5a1eeba  2017-12-19T09:30:49.975Z)
- OS Version: macOS 10.13.2

Paste SVG bellow to html file
```
<svg width="70" height="70" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#path0_fill" fill="#F2F2F2"/><use xlink:href="#path1_fill" transform="translate(5 15)" fill="#F2C94C"/><use xlink:href="#path2_fill" transform="translate(16.684 15.11)" fill="#4F4F4F"/><defs><path id="path0_fill" d="M70 35c0 19.33-15.67 35-35 35S0 54.33 0 35 15.67 0 35 0s35 15.67 35 35z"/><path id="path1_fill" d="M.12 20.721c.148.298.393.52.699.62l7.667 2.664c.135.05.257.062.392.062.502 0 .98-.322 1.151-.83l6.013-17.755.307.111a6.154 6.154 0 0 0 4.776-.272l.747-.372a3.717 3.717 0 0 1 2.866-.173l13.986 4.881c-.146.546-.428 1.177-.918 1.524-.563.397-1.433.397-2.572 0l-6.27-2.168a1.2 1.2 0 0 0-.968.087 1.253 1.253 0 0 0-.6.768c-.012.037-.894 3.308-3.613 4.782-1.715.93-3.858.954-6.369.087a1.21 1.21 0 0 0-1.543.768 1.23 1.23 0 0 0 .76 1.562c1.469.507 2.865.768 4.163.768 1.507 0 2.89-.347 4.152-1.029 2.45-1.338 3.748-3.642 4.348-5.067l5.144 1.784c1.91.657 3.503.558 4.74-.31 1.947-1.363 2.082-4.026 2.094-4.324a1.254 1.254 0 0 0-.82-1.202L25.51 2.471a6.146 6.146 0 0 0-4.728.298l-.747.371a3.754 3.754 0 0 1-2.903.174l-1.237-.446a.806.806 0 0 0-.232-.112L8.033.068a1.21 1.21 0 0 0-1.544.768L.06 19.792c-.097.298-.073.632.062.93zM8.4 2.781l5.364 1.858-5.633 16.64-5.365-1.858L8.4 2.78z"/><path id="path2_fill" d="M1.064 31.85a3.549 3.549 0 0 0 3.074 2.006c0 .533.123 1.078.355 1.574A3.508 3.508 0 0 0 6.54 37.25a3.425 3.425 0 0 0 2.707-.173l.636-.322c.05.371.16.755.33 1.115a3.508 3.508 0 0 0 2.046 1.82 3.425 3.425 0 0 0 2.707-.173l13.925-6.9a35.839 35.839 0 0 0 8.524-5.886l3.111-2.887 7.116-3.518c.6-.298.845-1.029.55-1.636L39.522.69a1.191 1.191 0 0 0-.698-.62 1.163 1.163 0 0 0-.931.062l-7.275 3.606a1.227 1.227 0 0 0-.551 1.635l8.303 17.172-2.572 2.392a33.818 33.818 0 0 1-7.948 5.488l-13.925 6.901c-.27.137-.576.15-.87.05a1.15 1.15 0 0 1-.698-1.462c.098-.285.306-.52.576-.657l7.789-3.853c.6-.297.845-1.028.551-1.635a1.2 1.2 0 0 0-1.616-.558l-7.79 3.853-3.674 1.822c-.27.136-.576.148-.87.05a1.15 1.15 0 0 1-.698-1.462c.098-.286.306-.521.576-.657l11.17-5.526c.6-.298.845-1.029.55-1.636a1.2 1.2 0 0 0-1.616-.557L4.75 31.304a1.144 1.144 0 0 1-1.518-.52 1.163 1.163 0 0 1 .527-1.536l4.947-2.454 6.43-3.184c.6-.297.845-1.028.551-1.636a1.2 1.2 0 0 0-1.616-.557L4.065 26.373a1.144 1.144 0 0 1-1.52-.52 1.17 1.17 0 0 1 .515-1.537l5.316-2.627c.6-.297.845-1.028.55-1.635a1.2 1.2 0 0 0-1.616-.557l-5.315 2.626C.23 22.99-.504 25.16.365 26.943c.246.508.589.917 1.005 1.251a3.576 3.576 0 0 0-.306 3.655zM32.772 5.396l5.095-2.528 7.643 15.797-5.095 2.528-7.643-15.797z"/></defs></svg>
```
then Code helper doesn't respond.
![](https://i.imgur.com/GUlmAZ0.png)

Activity monitor
![](https://i.imgur.com/SdoJYMz.png)

Force quit helps to fix this issue.
![](https://i.imgur.com/072GugZ.png)

**Comment by ramya-rao-a** [comment]
@codev0 Can you share the complete contents of your file? I pasted the svg inside simple html tags in an html file, and I cannot repro the issue

**Comment by WorthyD** [comment]
I was having the same issue. I disabled the Auto Rename Tag plugin and it started working fine again.
