### ISSUE TITLE
add spell checker for commit message box in vscode

### ISSUE THREAD

**Issue by Ahmad-Abo-Saa** [Microsoft/vscode#37647]
I think we need a spell checker for git commit message box in vscode
![image](https://user-images.githubusercontent.com/10397821/32407015-babd2226-c18a-11e7-98e1-7f675a550021.png)

**Comment by maxibanki** [comment]
Duplicate of #35571

**Comment by Ahmad-Abo-Saa** [comment]
@maxibanki  I think you are right, it seems there is already a similar request, I'll close this issue, thanks.
