### ISSUE TITLE
debuggers.initialConfigurations not calling command

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#37648]
Insiders: 1.18.0-insider Commit: 154498 Date: 2017-11-02

The [docker extension](https://github.com/microsoft/vscode-docker) contributes the following in `package.json`:

``` json
    "debuggers": [
      {
        "type": "docker",
        "label": "Docker Attach",
        "initialConfigurations": "vscode-docker.debug.configureLaunchJson"
      }
    ],
```

and in the activation of the extension it registers the `vscode-docker.debug.configureLaunchJson` command:

``` typescript
    ctx.subscriptions.push(vscode.commands.registerCommand('vscode-docker.debug.configureLaunchJson', configureLaunchJson));
```

When configuring a new workspace the command is not called, instead this is generated:

``` json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": "vscode-docker.debug.configureLaunchJson"
}
```

On Stable the command is executed and the following is generated:

``` json
{
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Docker: Attach to Node",
                "type": "node",
                "request": "attach",
                "port": 9229,
                "address": "localhost",
                "localRoot": "${workspaceRoot}",
                "remoteRoot": "/usr/src/app"
            }
        ]
    }
```

So, its appears broken on Insiders only and is a regression. Not sure how many other extensions do the same contribution.

**Comment by ramya-rao-a** [comment]
See https://code.visualstudio.com/updates/v1_17#_debug-contributions-in-packagejson `debuggers.startSessionCommand`, `debuggers.initialConfigurations` were deprecated in 1.17 and support for them is dropped in 1.18

You need to implement a `DebugConfigurationProvider` and provide the initial configurations via the `provideDebugConfigurations` method in it

**Comment by weinand** [comment]
@chrisdias the deprecation of the `initialConfigurations` and `startSession` commands had been already announced in the August release notes: https://code.visualstudio.com/updates/v1_16#_debug-api-updates.

And this information was repeated in the September release notes: 
https://code.visualstudio.com/updates/v1_17#_debug-contributions-in-packagejson

**Comment by chrisdias** [comment]
fixed in vscode-docker https://github.com/Microsoft/vscode-docker/commit/9f6daa84a4cd645923240a9639f541be24e9e502
also added bug for docs: https://github.com/Microsoft/vscode-docs/issues/1237
