### ISSUE TITLE
extensions installed can not found after update VSCode 

### ISSUE THREAD

**Issue by Chris-Wen** [Microsoft/vscode#37659]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|pea|0.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@Chris-Wen what do you mean?
