### ISSUE TITLE
Using ftp-simple: file explorer not refreshing

### ISSUE THREAD

**Issue by jjphung** [Microsoft/vscode#37656]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ftp-simple|hum|0.5.8

---

Steps to Reproduce:

1. Remote into a server
2. Delete/rename a file or folder 
3. Manually press the refresh button in the file explorer (shift + command + e)

Reproduces without extensions: Don't know.

**Comment by isidorn** [comment]
@jjphung so do you see the changes in the explorer after you manually refresh the explorer? Or the changes are still mising then?
I believe this should be filed against the ftp-simple extension, so please file it there first. Thanks
