### ISSUE TITLE
Treat 'default' as keyword while auto-importing

### ISSUE THREAD

**Issue by giridharangm** [Microsoft/vscode#37655]
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.2
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0

(1 theme extensions excluded)

---  

When tried to create a default export, VSCode doesn't recognize `default` as the keyword, instead it shows the default(s) from other components.  

Like:  

![image](https://user-images.githubusercontent.com/2258588/32410996-7c83a2e4-c1f5-11e7-84a7-a5b82eb2866c.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19841
