### ISSUE TITLE
Editor settings in one folder

### ISSUE THREAD

**Issue by waferstick** [Microsoft/vscode#37650]
I really like vscode, but i'd like to know if there is a way to save all downloaded extensions, workplace settings, windows size and position (Basically all settings that I modified) directly inside vscode folder (Where the application was installed) and not in different folder (Like .vscode in my home directory).

I'm using the .zip version of vscode and deepfreeze so when I restart/shutdown my computer it return to default vscode settings.

- VSCode Version: 1.17.2 (.zip version)
- OS Version: Windows 10 Pro x64 1703 15063.632

**Comment by bpasero** [comment]
No, currently not.
