### ISSUE TITLE
Visual Studio Mac doesn't full update

### ISSUE THREAD

**Issue by residentx** [Microsoft/vscode#37652]
I had to completely delete the installation on Mac and reinstall to get the latest edition with the newer desktop icons, etc. 

- VSCode Version: I don't know
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Launch Visual Studio Code
2. Update Visual Studio Code

Reproduces without extensions: Yes/No I don't know

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426
