### ISSUE TITLE
Input textarea visible in top left corner when gutter has different background than editor and the cursor is scrolled out of view

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#37658]
`editor.background` leaks through `editorGutter.background` when you scroll past cursor

```json
"editor.background": "#F00",
"editorGroupHeader.tabsBorder": "#333",
"editorGutter.background": "#222",
```
![ok](https://user-images.githubusercontent.com/9638156/32411219-d905d80c-c1e6-11e7-83dc-ecf10d5f5254.png)
![not_ok](https://user-images.githubusercontent.com/9638156/32411221-dd0c4864-c1e6-11e7-874f-8416aa1b832d.png)

**Comment by usernamehw** [comment]
Is this element important? Am I losing something setting:
```css
.textAreaCover {
    background: transparent;
}
```

**Comment by alexandrudima** [comment]
@usernamehw nothing bad happens doing that if you don't use CJK languages or others that require composition.

**Comment by usernamehw** [comment]
Thanks.
