### ISSUE TITLE
Extensions should be store in AppData folder or elsewhere, not C:\Users\username\.vscode\extensions

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode#37663]
VS Code should store stuff in AppData or some other place, it shouldn't pollute the home folder. Starting the folder name with a "." makes no sense on Windows as Explorer still can see the folder (I thought Microsoft knows this better?).

- VSCode Version:  1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install VS Code
2. Install an extension

**Comment by joaomoreno** [comment]
#3884

**Comment by joaomoreno** [comment]
@sryze You can always use `--extensions-dir` to set the directory.
