### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by 21Vicroy** [Microsoft/vscode#37662]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: the listing length exceeds browsers' URL characters limit
---

So I'm using a **surface laptop**, upgraded it of course to the pro while I could for free.
I'm having issues with scrolling up and down on VSCode. It's not smooth at all.
This is mainly with the _track pad_.
I scroll up and it takes a few seconds for VSCode to register that I want to scroll up and it just jumps.

I have opened up other apps (slack, edge, chrome, office word, VS) and the scrolling behaves just fine and it's very responsive. Not sure why VSCode has a hard time since it's just an advanced text editor.

What is super interesting is that, when I use the touch SCREEN (not the track pad) scrolling is fine.

Steps to Reproduce:

1. Two fingers on track pad
2. move them up and/or down

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#13612
