### ISSUE TITLE
FR: SQL Highlighting is soo bad

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#37665]
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: -
(not neccessary for this)

![image](https://user-images.githubusercontent.com/11234139/32414478-01677c06-c228-11e7-8429-4cb02459004c.png)

```sql
DROP TABLE IF EXISTS wcf1_acp_search_provider;
CREATE TABLE wcf1_acp_search_provider (
	providerID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	packageID INT(10) NOT NULL,
	providerName VARCHAR(191) NOT NULL DEFAULT '',
	className VARCHAR(255) NOT NULL DEFAULT '',
	showOrder INT(10) NOT NULL DEFAULT 0,
	UNIQUE KEY providerName (providerName, packageID)
);
```

Personally, I'd be happy when the table names have a scope, all keywords (like `AUTO_INCREMENT` or `UNIQUE`) and the rows' name.

**Comment by aeschli** [comment]
We now use the grammar from https://github.com/Microsoft/vscode-mssql

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-mssql#1019
