### ISSUE TITLE
Can't pause node execution (F6)

### ISSUE THREAD

**Issue by weeco** [Microsoft/vscode#37660]
I wonder if VSCode is supposed to support code execution pause when running a node application? I have never been able to pause my running node application by clicking the pause button. Even though it shows the hover and click animation on the button, it won't pause the execution - "nothing" happens. Is it supposed to work at all?

Until today I never really needed this debugging feature, but now I do :(.

- VSCode Version: 1.17.2
- OS Version: Win 10 x64

Steps to Reproduce:

1. Start any node application
2. Click pause while it's running

Reproduces without extensions: Yes

**Comment by formulahendry** [comment]
You may want to try this extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner It could easily stop the running code.

**Comment by weinand** [comment]
@formulahendry "stopping" code has nothing to do with "pausing".

**Comment by formulahendry** [comment]
@weinand Got it. 😄 Did not go through the issue description carefully.

**Comment by weeco** [comment]
So @weinand what additional information can I provide? Is it supposed to work at all or is it just me?

**Comment by weinand** [comment]
@weeco what version of node.js are you using?

**Comment by weeco** [comment]
v 8.2.1

**Comment by weinand** [comment]
I tried to reproduce this on Windows by using this program:
```js
let i = 0;
setInterval(_ => {
    console.log(i++);
}, 10);
```

Pressing the Pause button (or F6) always stopped execution here:
![2017-11-07_18-02-23](https://user-images.githubusercontent.com/1898161/32506814-d3a19d3c-c3e5-11e7-9a65-97e389a54f3b.png)

What are you seeing?

**Comment by weeco** [comment]
This simple snippet can actually be paused on my VSCode as well. I am not sure what exactly is causing it but even a 50 lines long application which tests some RabbitMQ functions is apparently not pausable for me.

**Comment by weinand** [comment]
Could you make that application available to us?

**Comment by weeco** [comment]
@weinand Actually below you will find a shorter project where I am able to reproduce the problem:

```
import * as Promise from 'bluebird';

export class Consumer {
  dummyMethod(): Promise<string> {
    return Promise.delay(50000, "hello world");
  }
}

const consumer = new Consumer();

async function bootstrap() {
  await consumer.dummyMethod();
}

bootstrap();
```

Also a video showing what happens: https://streamable.com/atz6j

**Comment by weinand** [comment]
Yes, I can reproduce an issue even with my snippet by changing the interval time from 10 to 50000 ms.
```js
let i = 0;
setInterval(_ => {
    console.log(i++);
}, 50000);
```
In this case the program breaks after 50 seconds.

This is expected since "Pause" can only pause the execution if the program does not wait in the OS.

I see exactly the same behaviour when debugging with Chrome dev tools and pressing the "pause" button there.

**Comment by weinand** [comment]
So if you want to ensure that pausing a program is responsive, just make sure that it does not stays for a long time in the OS. So adding a 10 ms interval timer that does nothing could help.
