### ISSUE TITLE
With UTF-8 format, open a GBK coding format of Chinese novels, appear garbled, click on GBK code format open, the program stuck

### ISSUE THREAD

**Issue by TaosLi** [Microsoft/vscode#37661]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.4
vscode-docker|Pet|0.0.20
html-css-class-completion|Zig|1.12.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.2
vscode-dash|dee|1.7.1
githistory|don|0.2.3
python|don|0.7.0
vscode-npm-script|eg2|0.3.2
vscode-great-icons|emm|2.1.19
code-runner|for|0.8.3
csharpextensions|jch|1.3.0
Angular2|joh|2.10.0
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
Go|luk|0.6.67
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
open-in-browser|tec|1.1.0
python|tht|0.2.3
vim|vsc|0.10.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.With UTF-8 format, open a GBK coding format of Chinese novels, appear garbled, click on GBK code format open, the program stuck
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you attach the file?
