### ISSUE TITLE
Docker image build output blank on Windows until integrated terminal resized

### ISSUE THREAD

**Issue by marknet15** [Microsoft/vscode#37664]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
puppet|Bor|0.3.2
erb|Cra|0.0.1
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
azure-account|ms-|0.1.3
PowerShell|ms-|1.5.0
vscode-docker|Pet|0.0.20
view-in-browser|qin|0.0.5
html-preview-vscode|tht|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Build a docker image on a Windows 10 machine within VS Code.
The output is blank until the terminal is resized.  After resized all output can be seen.

Not a huge issue just something I thought I'd point out.
Before resizing (no output)
![part 1](https://user-images.githubusercontent.com/14127638/32414375-ff0c4aa0-c21c-11e7-97f1-f99f0fa18135.PNG)
After resizing (full output now seen)
![part 2](https://user-images.githubusercontent.com/14127638/32414376-ff28592a-c21c-11e7-81d9-763b926642d2.PNG)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I think you want to report this against the docker extension https://github.com/Microsoft/vscode-docker
