### ISSUE TITLE
Node debugger hangs up on specific lines when smartstep is enabled

### ISSUE THREAD

**Issue by kkeri** [Microsoft/vscode#37670]
- Node version: v8.7.0
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ohm|att|1.0.0
vscode-eslint|dba|1.4.2
easy-icons|jam|0.3.1
vscode-codemetrics|kis|1.10.0
extension-manifest-editor|ms-|0.1.5
cpptools|ms-|0.14.0
debugger-for-chrome|msj|3.5.0

---

When smartstep is enabled, I experience very long delays during step-and-trace debugging when control is transferred between a non source-mapped file and a source-mapped file.
The delay may extend to several minutes. During the delay, the debug target shows an increased memory and CPU consumption. I'm able to stop debugging by pressing shift+F5 but I can't pause execution.

Reproduces without extensions: Yes

Steps to Reproduce:

I created a minimal project and shared it on Github. Please clone the repo and follow instructions in readme.

https://github.com/kkeri/vscode-smartstep-issue

By examining launch trace I realized the possible reason. When I press F10 (`Debugger.stepOver`) on a breakpoint in a non-mapped source, the debug target correctly steps over a function call into a mapped source and stops (`Debugger.paused`) on the next line. After that, the debugger starts sending repeated `Debugger.stepInto` commands to the target until the program is terminated or another breakpoint hit. In other words, every single statement is executed individually by the debugger what causes long delay and excessive resource consumption.

For reference, here is my launch configuration.
~~~json
    {
      "type": "node",
      "request": "launch",
      "name": "launch with smartstep",
      "program": "${file}",
      "sourceMaps": true,
      "outFiles": [ "${workspaceRoot}/lib/*.js" ],
      "smartStep": true,
      "trace": "all"
    }
~~~

**Comment by weinand** [comment]
Yes, smartstep is implemented by repeated single stepping.
So this works as designed and the slowness is expected.

**Comment by weinand** [comment]
If you have ideas how to "smartstep" in a more efficient way, please let us know.

**Comment by kkeri** [comment]
Well, my problem is not slowliness here. If you take a look at my test scenario, you can see that the debugger must have stopped on line 17 but it didn't.
This is percieved as an unexpected debugger hangup on specific lines. Does your answer still apply to the situation?

**Comment by kkeri** [comment]
Probably my description is not straightforward enough. I think the delay is only a side effect of the problem. It happens after the debugger has failed to stop on the expected position.

**Comment by roblourens** [comment]
I tried it but don't understand the problem. Are you expecting it to stop in test.js? Since it doesn't have a sourcemap, it won't stop there unless there's a breakpoint on the line. I don't see any increase in CPU, it's a short script and smartstep steps through it quickly. And you mention line 17 but there is no line 17.

**Comment by kkeri** [comment]
@roblourens I'm sorry about the line numbers, it should be line 11 and 12. I compacted my code and forgot about readme.

**Comment by kkeri** [comment]
@roblourens You won't see an increase in CPU because I gave up this issue and modified the source to focus on #37678. You can find the original version here:

https://github.com/kkeri/vscode-smartstep-issue/tree/9e55928f0b97da07b7f8fa38dc5dce8728243b1d

**Comment by kkeri** [comment]
> I tried it but don't understand the problem. Are you expecting it to stop in test.js? Since it doesn't have a sourcemap, it won't stop there unless there's a breakpoint on the line. 

@roblourens Maybe I have a false assumption about this. Intuitively If I do a step over in a file, I expect the debugger to step to the next line and pause there. Should it work differently if I mix mapped and non-mapped sources?

**Comment by roblourens** [comment]
smartStep is quite simple, it autosteps over lines that don't have sourcemaps, that's it. It will stop on a breakpoint in a non-sourcemapped file but after that it will continue autostepping.

**Comment by kkeri** [comment]
Ok, now I see that I misinterpreted documentation. 

> With the smartStep attribute set to true in a launch configuration, VS Code will automatically skip 'uninteresting code' when stepping through code in the debugger. **'Uninteresting code' is code that is generated by a transpiling process but is not covered by a source map so it does not map back to the original source.** 

This part is a bit confusing. I usually write my tests in pure JS and require transpiled modules there. My test code is obviously not uninteresting, and it is not generated by a transpiling process.

I ask you to elaborate this part of the docs to make it even more clear that whole Javascript files that are not generated, will be skipped.
