### ISSUE TITLE
Support linking to localized licenses

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3767]
The Help > View License menu should redirect to the language currently being used in VS Code. We currently store the license url in `product.json`:

``` json
"licenseUrl": "http://go.microsoft.com/fwlink/?LinkID=533485#vscode",
```

I don't know why we pass in #vscode here, I don't think its necessary.

The website will take an additional parameter `lang` with the three letter language code.  So, we need to append the language to the query, for example: `lang=deu`.

These are the supported languages: enu, ita, fra, esp, rus, chs, cht, jpn, kor, deu

**Comment by dbaeumer** [comment]
@chrisdias: just to be clear. What I can add is lang='de-DE'. The OS talks 2 digit language with variants not three digit.

**Comment by dbaeumer** [comment]
Fixed. If German is picked by VSCode as the best language I append ?lang=de to the URL.

**Comment by chrisdias** [comment]
Everything on the surface looks ok. I have to remove #vscode from the FWLink and already made a PR for that. Waiting for next build so i can verify.

**Comment by egamma** [comment]
will be verified as part of #4579
