### ISSUE TITLE
Find in files no longer selects the selection

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37685]
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:35:35.044Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.3
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
debugger-for-chrome|msj|3.5.0
seti-icons|qin|0.1.3
gitblame|wad|2.2.0

(4 theme extensions excluded)

---

Steps to reproduce:

1. Highlight some work in editor
2. cmd+shift+f
3. Notice the word does is no selected in the viewlet

This is really annoying personally as I have muscle memory that I can't shake where I copy, find in files and paste.

**Comment by roblourens** [comment]
It says you have the latest build but this sounds like https://github.com/Microsoft/vscode/commit/ff6c4849cf1b1766a56656e295c86bef71bac685, and all cases work for me now. Please show me tomorrow

**Comment by Tyriar** [comment]
The selected text in the editor needs to be different to the text in the viewlet, seems to work fine when the text is the same. Will show you later today 😃

**Comment by roblourens** [comment]
Oh I do see the issue. Easy fix. But if you have selected text in the editor, then it should already copy that text to the search viewlet, so you don't need to paste, right?
