### ISSUE TITLE
vs code does not work without internet

### ISSUE THREAD

**Issue by DrMarshmellow777** [Microsoft/vscode#37680]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.17.0
clipboard-history|Anj|1.0.7
vscode-color|ans|0.4.5
htmltagwrap|bra|0.0.5
vscode-eslint|dba|1.4.2
jquerysnippets|don|0.0.1
python|don|0.7.0
vscode-html-css|ecm|0.1.8
EditorConfig|Edi|0.11.1
vscode-great-icons|emm|2.1.19
vsc-material-theme|Equ|1.1.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
file-icons|fil|1.0.5
code-runner|for|0.8.3
vscode-firefox-debug|hbe|0.17.0
path-autocomplete|ion|1.6.2
autofilename|Jer|0.1.3
vscode-gutter-preview|kis|0.11.4
vscode-simple-icons|Lau|1.6.2
MagicPython|mag|1.0.12
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.5.0
material-icon-theme|PKi|2.2.4
vscode-css-peek|pra|1.3.1
seti-icons|qin|0.1.3
view-in-browser|qin|0.0.5
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
bootstrap4-vscode|the|3.0.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

(15 theme extensions excluded)

---

Steps to Reproduce:

1. I do not have internet
2. I run the shortcut but it does not start, it does not show me more details it just does not start when I do not have internet, the internet returns now if it starts vs code

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7570
