### ISSUE TITLE
Can't build vscode on Ubuntu 16.04

### ISSUE THREAD

**Issue by SarenT** [Microsoft/vscode#37683]
Hi,

I can't build vscode on Ubuntu 16.04 LTS

- VSCode Version: Recent from github
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. git clone the project
2. installed dependencies as described on github page
3. run the ./scripts/npm.sh install --arch=x64

I get the error at some point:

> [18:55:35] Starting 'vscode-linux-x64'...
> Failed to find tag for base version, 1.18.0
> internal/streams/legacy.js:59
>       throw er; // Unhandled stream error in pipe.
>       ^
> 
> Error: connect ECONNRESET 13.85.19.92:443
>     at Object._errnoException (util.js:1024:11)
>     at _exceptionWithHostPort (util.js:1046:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

The server at that IP address is offline.

Here is the full output:

> code-oss-dev@1.19.0 gulp /home/user/git/vscode
> gulp --max_old_space_size=4096 "vscode-linux-x64"

> [18:52:50] Node flags detected: --max_old_space_size=4096
> [18:52:50] Respawned to PID: 16167
> [18:52:53] Using gulpfile ~/git/vscode/gulpfile.js
> [18:52:53] Starting 'clean-optimized-vscode'...
> [18:52:53] Starting 'clean-client-build'...
> [18:52:53] Starting 'clean-extension:configuration-editing'...
> [18:52:53] Starting 'clean-extension:css-client'...
> [18:52:53] Starting 'clean-extension:css-server'...
> [18:52:53] Starting 'clean-extension:emmet'...
> [18:52:53] Starting 'clean-extension:extension-editing'...
> [18:52:53] Starting 'clean-extension:git'...
> [18:52:53] Starting 'clean-extension:grunt'...
> [18:52:53] Starting 'clean-extension:gulp'...
> [18:52:53] Starting 'clean-extension:html-client'...
> [18:52:53] Starting 'clean-extension:html-server'...
> [18:52:53] Starting 'clean-extension:jake'...
> [18:52:53] Starting 'clean-extension:javascript'...
> [18:52:53] Starting 'clean-extension:json-client'...
> [18:52:53] Starting 'clean-extension:json-server'...
> [18:52:53] Starting 'clean-extension:markdown'...
> [18:52:53] Starting 'clean-extension:merge-conflict'...
> [18:52:53] Starting 'clean-extension:npm'...
> [18:52:53] Starting 'clean-extension:php'...
> [18:52:53] Starting 'clean-extension:python'...
> [18:52:53] Starting 'clean-extension:typescript-test-colorize-fixtures'...
> [18:52:53] Starting 'clean-extension:typescript'...
> [18:52:53] Starting 'clean-extension:vscode-api-tests'...
> [18:52:53] Starting 'clean-extension:vscode-colorize-tests'...
> [18:52:53] Starting 'clean-vscode-linux-x64'...
> [18:52:53] Finished 'clean-extension:typescript-test-colorize-fixtures' after 8.71 ms
> [18:52:53] Starting 'compile-extension-build:typescript-test-colorize-fixtures'...
> [18:52:53] Starting compilation...
> [18:52:53] Finished 'clean-vscode-linux-x64' after 89 ms
> [18:52:53] Finished compilation with 0 errors after 14 ms
> [18:52:53] Finished 'compile-extension-build:typescript-test-colorize-fixtures' after 91 ms
> [18:52:53] Finished 'clean-extension:css-client' after 191 ms
> [18:52:53] Starting 'compile-extension-build:css-client'...
> [18:52:53] Starting compilation...
> [18:52:53] Finished 'clean-extension:css-server' after 196 ms
> [18:52:53] Starting 'compile-extension-build:css-server'...
> [18:52:53] Finished 'clean-extension:extension-editing' after 198 ms
> [18:52:53] Starting 'compile-extension-build:extension-editing'...
> [18:52:53] Finished 'clean-extension:configuration-editing' after 201 ms
> [18:52:53] Starting 'compile-extension-build:configuration-editing'...
> [18:52:53] Finished 'clean-extension:gulp' after 207 ms
> [18:52:53] Starting 'compile-extension-build:gulp'...
> [18:52:53] Finished 'clean-extension:grunt' after 210 ms
> [18:52:53] Starting 'compile-extension-build:grunt'...
> [18:52:53] Finished 'clean-extension:html-client' after 215 ms
> [18:52:53] Starting 'compile-extension-build:html-client'...
> [18:52:53] Finished 'clean-extension:markdown' after 215 ms
> [18:52:53] Starting 'compile-extension-build:markdown'...
> [18:52:53] Finished 'clean-extension:npm' after 217 ms
> [18:52:53] Starting 'compile-extension-build:npm'...
> [18:52:53] Finished 'clean-extension:python' after 218 ms
> [18:52:53] Starting 'compile-extension-build:python'...
> [18:52:53] Finished 'clean-extension:merge-conflict' after 224 ms
> [18:52:53] Starting 'compile-extension-build:merge-conflict'...
> [18:52:53] Finished 'clean-extension:vscode-api-tests' after 224 ms
> [18:52:53] Starting 'compile-extension-build:vscode-api-tests'...
> [18:52:53] Finished 'clean-extension:vscode-colorize-tests' after 226 ms
> [18:52:53] Starting 'compile-extension-build:vscode-colorize-tests'...
> [18:52:53] Finished 'clean-extension:jake' after 267 ms
> [18:52:53] Starting 'compile-extension-build:jake'...
> [18:52:53] Finished 'clean-extension:emmet' after 331 ms
> [18:52:53] Starting 'compile-extension-build:emmet'...
> [18:52:53] Finished 'clean-extension:git' after 332 ms
> [18:52:53] Starting 'compile-extension-build:git'...
> [18:52:53] Finished 'clean-extension:json-client' after 332 ms
> [18:52:53] Starting 'compile-extension-build:json-client'...
> [18:52:53] Finished 'clean-extension:javascript' after 334 ms
> [18:52:53] Starting 'compile-extension-build:javascript'...
> [18:52:53] Finished 'clean-extension:json-server' after 336 ms
> [18:52:53] Starting 'compile-extension-build:json-server'...
> [18:52:53] Finished 'clean-extension:typescript' after 338 ms
> [18:52:53] Starting 'compile-extension-build:typescript'...
> [18:52:53] Finished 'clean-extension:php' after 500 ms
> [18:52:53] Starting 'compile-extension-build:php'...
> [18:52:59] Finished 'clean-extension:html-server' after 6.41 s
> [18:52:59] Starting 'compile-extension-build:html-server'...
> [18:52:59] [i18n] Generating localized messages for 'cht' resulted in the following problems:
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Message file cht/extensions/npm/out/main.i18n.json is empty. Missing messages: 1
> [18:52:59] [i18n] 
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Generating localized messages for 'kor' resulted in the following problems:
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Message file kor/extensions/npm/out/main.i18n.json is empty. Missing messages: 1
> [18:52:59] [i18n] 
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Generating localized messages for 'deu' resulted in the following problems:
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Message file deu/extensions/npm/out/main.i18n.json is empty. Missing messages: 1
> [18:52:59] [i18n] 
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Generating localized messages for 'rus' resulted in the following problems:
> [18:52:59] [i18n] 
> [18:52:59] [i18n] Message file rus/extensions/npm/out/main.i18n.json is empty. Missing messages: 1
> [18:52:59] [i18n] 
> [18:52:59] [i18n] 
> [18:53:02] [i18n] Generating localized messages for 'rus' resulted in the following problems:
> [18:53:02] [i18n] 
> [18:53:02] [i18n] No localized message found for key activeEditorShort
> [18:53:02] [i18n] No localized message found for key activeEditorMedium
> [18:53:02] [i18n] No localized message found for key activeEditorLong
> [18:53:02] [i18n] No localized message found for key rootName
> [18:53:02] [i18n] No localized message found for key rootPath
> [18:53:02] [i18n] No localized message found for key folderName
> [18:53:02] [i18n] No localized message found for key folderPath
> [18:53:02] [i18n] 
> [18:53:02] [i18n] 
> [18:53:06] Finished 'compile-extension-build:python' after 13 s
> [18:53:07] Finished 'clean-optimized-vscode' after 14 s
> [18:53:07] Finished 'compile-extension-build:css-server' after 14 s
> [18:53:09] Finished 'compile-extension-build:vscode-colorize-tests' after 15 s
> [18:53:09] Finished 'clean-client-build' after 16 s
> [18:53:09] Starting 'compile-client-build'...
> [18:53:12] Finished 'compile-extension-build:json-server' after 19 s
> [18:53:15] Finished 'compile-extension-build:npm' after 22 s
> [18:53:15] Finished 'compile-extension-build:gulp' after 22 s
> [18:53:15] Finished 'compile-extension-build:grunt' after 22 s
> [18:53:15] Finished 'compile-extension-build:jake' after 22 s
> [18:53:15] Finished 'compile-extension-build:css-client' after 22 s
> [18:53:18] Finished 'compile-extension-build:json-client' after 24 s
> [18:53:18] Finished 'compile-extension-build:html-client' after 25 s
> [18:53:19] [i18n] Generating localized messages for 'chs' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file chs/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'cht' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file cht/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'jpn' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file jpn/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'kor' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file kor/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'deu' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file deu/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'fra' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file fra/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'esn' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file esn/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'rus' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file rus/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Generating localized messages for 'ita' resulted in the following problems:
> [18:53:19] [i18n] 
> [18:53:19] [i18n] Message file ita/extensions/merge-conflict/out/extension.i18n.json not found. Missing messages: 0
> [18:53:19] [i18n] 
> [18:53:19] [i18n] 
> [18:53:19] Finished 'compile-extension-build:vscode-api-tests' after 26 s
> [18:53:19] Finished 'compile-extension-build:configuration-editing' after 26 s
> [18:53:21] Finished 'compile-extension-build:extension-editing' after 28 s
> [18:53:21] Finished 'compile-extension-build:javascript' after 28 s
> [18:53:21] Finished 'compile-extension-build:php' after 28 s
> [18:53:24] Finished 'compile-extension-build:markdown' after 31 s
> [18:53:24] Finished 'compile-extension-build:html-server' after 25 s
> [18:53:24] Finished 'compile-extension-build:merge-conflict' after 31 s
> [18:53:24] [i18n] Generating localized messages for 'kor' resulted in the following problems:
> [18:53:24] [i18n] 
> [18:53:24] [i18n] No localized message found for key are you sure
> [18:53:24] [i18n] 
> [18:53:24] [i18n] 
> [18:53:24] [i18n] Generating localized messages for 'rus' resulted in the following problems:
> [18:53:24] [i18n] 
> [18:53:24] [i18n] No localized message found for key are you sure
> [18:53:24] [i18n] 
> [18:53:24] [i18n] 
> [18:53:25] Finished 'compile-extension-build:emmet' after 31 s
> [18:53:25] Finished 'compile-extension-build:git' after 31 s
> [18:53:25] [i18n] Generating localized messages for 'chs' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'cht' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'jpn' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'kor' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'deu' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'fra' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'esn' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] [i18n] Generating localized messages for 'rus' resulted in the following problems:
> [18:53:25] [i18n] 
> [18:53:25] [i18n] No localized message found for key autoImportLabel
> [18:53:25] [i18n] 
> [18:53:25] [i18n] 
> [18:53:25] Finished 'compile-extension-build:typescript' after 32 s
> [18:53:25] Starting 'compile-extensions-build'...
> [18:53:25] Finished 'compile-extensions-build' after 1.39 ms
> [18:55:02] [monaco.d.ts] Starting monaco.d.ts generation
> [18:55:04] [monaco.d.ts] Finished monaco.d.ts generation
> [18:55:04] Finished compilation with 0 errors after 131368 ms
> [18:55:04] Finished 'compile-client-build' after 1.92 min
> [18:55:04] Starting 'compile-build'...
> [18:55:04] Finished 'compile-build' after 3.19 μs
> [18:55:04] Starting 'optimize-vscode'...
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/colorPicker/browser/images/opacity-background.png MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/previous.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/next.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/previous-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/next-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/editor/contrib/find/browser/images/close-dark.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-dirty-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/browser/parts/editor/media/close-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/current-arrow.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/debug/browser/media/continue-inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/feedback/electron-browser/media/info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/edit_inverse.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/preferences/browser/media/info.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> CSS INLINING IMAGE AT out-build/vs/workbench/parts/welcome/code-icon.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
> [18:55:10] [i18n] de has 69 untranslated strings.
> [18:55:10] [i18n] es has 4 untranslated strings.
> [18:55:10] [i18n] fr has 11 untranslated strings.
> [18:55:10] [i18n] hu has 2 untranslated strings.
> [18:55:10] [i18n] it has 74 untranslated strings.
> [18:55:10] [i18n] ja has 23 untranslated strings.
> [18:55:10] [i18n] ko has 103 untranslated strings.
> [18:55:10] [i18n] pt-br has 12 untranslated strings.
> [18:55:10] [i18n] ru has 105 untranslated strings.
> [18:55:10] [i18n] tr has 11 untranslated strings.
> [18:55:10] [i18n] zh-cn has 11 untranslated strings.
> [18:55:10] [i18n] zh-tw has 92 untranslated strings.
> [18:55:35] Finished 'optimize-vscode' after 31 s
> [18:55:35] Starting 'vscode-linux-x64'...
> Failed to find tag for base version, 1.18.0
> internal/streams/legacy.js:59
>       throw er; // Unhandled stream error in pipe.
>       ^
> 
> Error: connect ECONNRESET 13.85.19.92:443
>     at Object._errnoException (util.js:1024:11)
>     at _exceptionWithHostPort (util.js:1046:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! code-oss-dev@1.19.0 gulp: `gulp --max_old_space_size=4096 "vscode-linux-x64"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the code-oss-dev@1.19.0 gulp script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user/.npm/_logs/2017-11-05T18_01_26_833Z-debug.log

**Comment by maxibanki** [comment]
> Error: connect ECONNRESET 13.85.19.92:443

Means that he can't connect to this IP. This IP is the endpoint from the marketplace (marketplace.visualstudio.com). There is a internet connection needed to build it from the source.
For debugging proposes you could try to manually connect via a browser / curl / wget to `https://marketplace.visualstudio.com`.

**Comment by SarenT** [comment]
I have tried that and I can't connect the IP address from Firefox either. Server must be down.

**Comment by SarenT** [comment]
Why does it need to connect Microsoft servers?

**Comment by maxibanki** [comment]
The server isn't down, in my case it works fine. Maybe firewall issue? Or you are blocked by them idk.

**Comment by SarenT** [comment]
Ahhh, so much for trying MS again... Nevermind, I will use atom for platform IO.
