### ISSUE TITLE
Emmet: unable to expand abbreviations containing plus sign, like: 'ol+', 'ul+', 'table+',..

### ISSUE THREAD

**Issue by mattez** [Microsoft/vscode#37686]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. In HTML document type 'ol+', 'ul+', 'table+',.. or other abbrevation with plus sign mentioned in [emmet cheatsheet](https://docs.emmet.io/cheat-sheet/)
2. Try to run Emmet: Expand Abbreviation

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
VS Code is using [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) which doesn't support the abbreviations ending with `+`

I have logged an upstream issue for this. https://github.com/emmetio/html-matcher/issues/1

Until, we get a fix from upstream for this, you can get around this by [creating your own snippets for Emmet](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets).
