### ISSUE TITLE
Opening a new folder closes exists terminal with process in it

### ISSUE THREAD

**Issue by KEMBL** [Microsoft/vscode#37689]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.14
prettier-vscode|esb|0.24.0
auto-rename-tag|for|0.0.15
angular-essentials|joh|0.3.2
Angular2|joh|2.10.0
Angular-BeastCode|Mik|5.0.12
debugger-for-chrome|msj|3.5.0
angular2-inline|nat|0.0.17

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open VS code
2. Open terminal
3. Start some install process, like npm install -g @angular/cli
4. while it in progress in Vs code open new folder

Result: the whole vs code window is reinitialized with terminal where installation was.

Reproduces without extensions: Does not matter.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
