### ISSUE TITLE
ANNOYING BY TYPESCRIPT HERO LOG

### ISSUE THREAD

**Issue by tueve** [Microsoft/vscode#37690]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. I don't use typescript and when opening any js file, the bug log of typescript-hero appear
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This is caused by the TypeScript hero extension. Please file an issue against them
