### ISSUE TITLE
CLI does not mark files as opened

### ISSUE THREAD

**Issue by tewe** [Microsoft/vscode#37699]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-38-generic

---

Steps to Reproduce:

1. use the CLI to open two files: `code a.txt b.txt`
2. chose "Compare Active File With" from the Command Palette

I get "there are no entries to pick from". The second file only becomes available after I switched to its tab once.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@tewe this should be fine if you update to 1.18
