### ISSUE TITLE
Dragging/Selecting using Microsoft Arc Mouse is not working

### ISSUE THREAD

**Issue by caskes** [Microsoft/vscode#37697]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.2
tslint|eg2|1.0.14

---

Steps to Reproduce:

1. Microsoft Arc Mouse - dragging to select or move elements is not working
2. E.g. try to select a part of code OR try to change the size of the Integrated Console window. Both don't work as the select/drag function is no longer working using the Microsoft Surface Arc mouse together with Microsoft Mouse and Keyboard Center software.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@caskes does it not work for any part of the UI, what about resizing the sidebar?

**Comment by caskes** [comment]
@bpasero. The issue started popping up in other programs as well. Cleaned and re-installed all mouse drivers and it is now all fine again. I thought it was VCode specific as that's where it started. But it wasn't and now can no longer reproduce it.
