### ISSUE TITLE
blade html not indent

### ISSUE THREAD

**Issue by izcream** [Microsoft/vscode#37692]
- VSCode Version: 1.17.2 (1.17.2)
- OS Version: OSX High Sierra 10.13.1

Hi i have problem with Laravel blade in vscode

I got this problem around 2 month ago, create issue at extension repository(https://github.com/onecentlin/laravel-blade-snippets-vscode)

extension-creator said it happen because html(php) not worked in blade
if i change syntax to html it's work fine but when change back to Laravel blade syntax it's not indent

How to solve this problem?

Thanks

ps. sorry for my bad english
![2017-11-06 11 17 14](https://user-images.githubusercontent.com/10282500/32425310-d56adca2-c2e4-11e7-839a-190d1059248f.gif)

**Comment by aeschli** [comment]
I commented in the issue at the blade repo:
https://github.com/onecentlin/laravel-blade-snippets-vscode/issues/9#issuecomment-342758042
