### ISSUE TITLE
Empty sidebar. Files are not listed.

### ISSUE THREAD

**Issue by Sarav-S** [Microsoft/vscode#37693]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crane|Hvy|0.3.8
blockalign|San|0.6.0
php-formatter|Sop|0.2.4
php-debug|fel|1.11.1
php-intellisense|fel|1.5.1
phpcs|ika|0.7.0
sublime-keybindings|ms-|3.0.2
php-docblocker|nei|1.3.0
laravel-blade|one|1.10.0

---

Steps to Reproduce:

1. File open folder -> chose my project folder
2. I got empty sidebar with no files listed. Even ctrl + R/Recent project folder too didn't work.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Does this happen with every folder or just a particular one?

**Comment by Sarav-S** [comment]
It happens with every folder. Trying to open projects with File->Open Recents or Ctrl+R also dint work out.

**Comment by bpasero** [comment]
@Sarav-S can you make sure to update to our lated 1.17 release.

**Comment by Sarav-S** [comment]
![screen shot 2017-11-06 at 12 11 42 pm](https://user-images.githubusercontent.com/3178230/32428450-c650e0d4-c2eb-11e7-8f4f-e5ec194a0b4b.png)

I think I have the latest version @bpasero

**Comment by bpasero** [comment]
@Sarav-S can you share a screenshot how your files explorer in the sidebar looks like?

**Comment by Sarav-S** [comment]
![screen shot 2017-11-06 at 11 10 29 am](https://user-images.githubusercontent.com/3178230/32428641-c31075fa-c2ec-11e7-92c1-b5411a061791.png)

After adding folder through File->Open or File->Open Recents or Ctrl+R, I get only welcome screen.

**Comment by Sarav-S** [comment]
You can see my project title VSCode header. Actually the files are available when I do Cmd+P to open them. But it isn't available only on sidebar

**Comment by bpasero** [comment]
@sandy081 didn't we push a change so that the files explorer is never hidden?

@Sarav-S if you right click on the title of the explorer you should be able to bring back the files explorer properly.

**Comment by Sarav-S** [comment]
@bpasero I think explorer is open only except files are not listed. Please check screenshot.

![screen shot 2017-11-06 at 12 32 31 pm](https://user-images.githubusercontent.com/3178230/32429001-a8bade78-c2ee-11e7-8d82-fa2387d957f1.png)

**Comment by Sarav-S** [comment]
@bpasero I have this same issue, except for Mac OS Sierra https://screencast-o-matic.com/watch/cbnt3w634b

**Comment by bpasero** [comment]
@Sarav-S do you see this context menu:

![image](https://user-images.githubusercontent.com/900690/32432869-5aef57c4-c2d9-11e7-96b7-5cd903438741.png)

**Comment by Sarav-S** [comment]
<img width="1280" alt="screen shot 2017-11-06 at 2 48 53 pm" src="https://user-images.githubusercontent.com/3178230/32433637-ac7fc902-c301-11e7-840a-fbcaefb0a5f8.png">

You mean this one?

**Comment by sandy081** [comment]
Looks like we broke this in 1.17 while refactoring split view and views viewlet. And it is pretty bad. 

Till 1.15 we were supporting toggling files explorer visibility. In 1.16 we took off that support #32962 here also making sure previous state is not considered. After refactoring we are no longer overriding the previous state. 

I think this should be a candidate for 1.18 release.

**Comment by sandy081** [comment]
Steps to reproduce:

- Download 1.15 version of VS Code
- Open VS Code on a folder
- Hide the file explorer view
- Update to latest

Expected: File explorer is not shown and cannot be retrieved

**Analysis:**
Looks like we broke this in 1.17 while refactoring split view and views viewlet.
Till 1.15 we were supporting toggling files explorer visibility. In 1.16 we took off that support #32962 here also making sure previous state is not considered. After refactoring we are no longer overriding the previous state. 

**Impact: Low**
Users who had file explorer hidden in 1.15 release **might** not see file explorer and also cannot retrieve it after upgrading to latest version. **Workaround** is to clear cache or upgrade to insiders. Also, I only see **2** users filed this issue till now.

**Comment by Sarav-S** [comment]
@sandy081 Thanks! It worked :)

**Comment by sandy081** [comment]
Reopening it for discussion for including it in October release or not.

**Comment by roblourens** [comment]
It is quite bad, and the fix looks simple, I think we should get it in for October.
