### ISSUE TITLE
Extension tests cannot use test frameworks that call process.exit

### ISSUE THREAD

**Issue by ciampolo** [Microsoft/vscode#37708]
VSCode Version: 1.19.0
OS Version: Unix

This should be reproducable on any platform.

Steps to Reproduce:

1. Create extension boiler with yo
2. Swap out mocha for example with Jasmine
3. Run tests

Tests run properly but the extension host instance does not close saying "An extension called process.exit() and this was prevented." which makes automated testing unnecessarily complicated using anything but mocha.

I read that this was implemented in order to prevent extensions to randomly force quit the application which is a perfectly valid argument. Though when the vscode instance is running as an Extension Host it should not hook into extension calls, since it specifically was started as a testing environment.

**Comment by bpasero** [comment]
@ciampolo can you share this setup so that I can reproduce?

**Comment by ciampolo** [comment]
@bpasero https://github.com/ciampolo/vsc-jasmine-bug

**Comment by bpasero** [comment]
@ciampolo I see. I find it weird that jasmine calls `process.exit`, is there any reason for it? Maybe there is an option to prevent Jasmine from calling exit? I see no reason for it, the process will terminate just fine when the test finishes, no?

**Comment by ciampolo** [comment]
@bpasero  Actually I am very fond of the testing framework trying to kill the host after finishing. Often in the early stage of writing tests I find myself not cleaning up all the rescources since I do not have the full system implemented yet; having the framework kill the host takes away having me to write those steps which would get removed anyway after the whole system is implemented.

It's really nice of vscode trying to do that but you can't/shouldn't really expect third party software to do that.

Also regardless of that I personally think a vscode instance that was specifically started as a testing environment should not hook extenion calls. Starting an extenion host has to be done manually, there is no chance to do this "by accident" meaning there should be no need to "protect" from certain calls since you can safely assume those calls are done intentionally.

**Comment by bpasero** [comment]
Yeah makes somewhat sense, I pushed a change so that extension tests can call `process.exit()`. You can give it a try from tomorrows insider build.
