### ISSUE TITLE
RipGrep: massage glob pattern [^...] to [!...]

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37700]
It looks like RipGrep is not supporting the `[^...]` glob pattern syntax so we should massage this pattern when we find it to be: `[!...]`.

**Comment by roblourens** [comment]
This works for me in search queries. It just doesn't work in gitignore files? We can't rewrite it then because rg reads those itself.

**Comment by bpasero** [comment]
@roblourens I think RG supports this now, see: https://github.com/BurntSushi/ripgrep/commit/679198e71aaa33b777405924110a96cf594aef12
