### ISSUE TITLE
Preserve 'Keyboard Shortcuts' search string when switching between tabs

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#37706]
- VSCode Version: 1.18 Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. Open 'Keyboard Shortcuts' view and another file in another tab.
2. Type 'Trigger Suggest' in shortcuts tab.
3. Navigate to another tab and go back to shortcuts.
-> Search string is not preserved.

Would be nice if we can save query state in keyboard shortcuts tab. 
**Use case scenario:** testing newly assigned keybinding in the file and returning back to shortcuts to change it.

P. S. I think it used to work before.

**Comment by sandy081** [comment]
Duplicates #23543
