### ISSUE TITLE
VS Code not being rendered

### ISSUE THREAD

**Issue by RonaldTinashe** [Microsoft/vscode#37707]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

## Steps to Reproduce:

1.Download
2.Install
3.Open

## What Has Been Tried:

1.Rebooting
2.Reinstalling

Nothing besides the menu is being rendered. See the attached screenshot.
![2017-11-06](https://user-images.githubusercontent.com/9010496/32444005-c5221656-c309-11e7-8d9a-93a93667c7b0.png)

**Comment by RonaldTinashe** [comment]
So I just added the option --disable-gpu and it rendered perfectly. However, I'm just curious about why this is happening at all.

**Comment by lukemcgregor** [comment]
@bpasero if this is an upstream problem in electron, can you link to their issue?

**Comment by PhilippLgh** [comment]
if it is critical and one needs the UI back: 
Ctrl+Shift+P (to open command palette), 'reload window', enter will work and bring back the UI

**Comment by Tyriar** [comment]
This looks like https://github.com/Microsoft/vscode/issues/61624
