### ISSUE TITLE
Add cwd to createTerminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37709]
Couldn't find that elsewhere: Add a parameter to createTerminal to specify the root folder or more generally the current working directory.

**Comment by cleidigh** [comment]
@chrmarti 
Am I correct you mean a new optional parameter cwd to the extension API
@Tyriar - I am overdue to help with some terminal stuff, I can add to my November Q...

createTerminal(nameOrOptions: vscode.TerminalOptions | string, shellPath?: string, shellArgs?: string[]): vscode.Terminal {
				if (typeof nameOrOptions === 'object') {
					return extHostTerminalService.createTerminalFromOptions(<vscode.TerminalOptions>nameOrOptions);
				}
				return extHostTerminalService.createTerminal(<string>nameOrOptions, shellPath, shellArgs);
			},

**Comment by chrmarti** [comment]
@cleidigh Correct, that would allow for opening the shell in any of the workspace folders and also any other folder where that makes sense.

**Comment by Tyriar** [comment]
@cleidigh yeah, just adding it to the TerminalOptions prototype, not the other one though (which already has enough params).

**Comment by cleidigh** [comment]
@Tyriar 
Not sure what you mean by the "other one", but I think you do mean to alter ITerminalOptions
in vscode.d.ts  : I have never touched this file before, I assume it's sort of a base file?

export interface TerminalOptions {
		/**
		 * A human-readable string which will be used to represent the terminal in the UI.
		 */
		name?: string;

		/**
		 * A path to a custom shell executable to be used in the terminal.
		 */
		shellPath?: string;

		/**
		 * Args for the custom shell executable, this does not work on Windows (see #8429)
		 */
		shellArgs?: string[];
		/**
		 * Object with environment variables that will be added to the VS Code process.
		 */
		env?: { [key: string]: string | null };
	}

**Comment by Tyriar** [comment]
@cleidigh I mean keep the API prototype like this and modify `vscode.TerminalOptions`:

```ts
createTerminal(nameOrOptions: vscode.TerminalOptions | string, shellPath?: string, shellArgs?: string[]): vscode.Terminal
```

**Not** like this:

```ts
createTerminal(nameOrOptions: vscode.TerminalOptions | string, shellPath?: string, shellArgs?: string[], env?: ...): vscode.Terminal
```

**Comment by cleidigh** [comment]
Addressed with PR #38132

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/38132

**Comment by chrmarti** [comment]
Great thanks! (Verified in extension.)
