### ISSUE TITLE
workbench.action.problems.show is inconsistent with existing actions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37717]
In general "focus" is used instead of "show", eg:

```
workbench.action.terminal.focus
workbench.action.focusActiveEditorGroup
workbench.action.focusPanel
workbench.action.focusSideBar
```

There are a bunch of .show actions as well, but since the terminal and editors generally use focus and the fact it's more correct (show does not imply focus), it should probably be changed to "focus".

**Comment by sandy081** [comment]
Updated to `workbench.action.problems.focus`

**Comment by sandy081** [comment]
Pushed to 1.18 branch
