### ISSUE TITLE
Markdown: Support to follow local links

### ISSUE THREAD

**Issue by taoari** [Microsoft/vscode#3771]
It is possible to follow local links for the markdown?

For example, I have two splits for a markdown file: one for editing, and the other one for previewing. If I have a local link `[Installation](installation.md)`. When clicking this link in the preview split, is it possible for both the two splits automatically switch to installation.md?

Further, is it possible to sync two scroll bars for the preview split and the edit split?

**Comment by felixfbecker** [comment]
That would be nice for docs written in Markdown.

**Comment by fbehrens** [comment]
VSCODE 1.7.1 on Windown 8.1
Currently the links are working in the preview Pane, but can not be followed from editor with `CTRL` like it is possible for normal `http://` links 
![image](https://cloud.githubusercontent.com/assets/13704/20260639/e5ba3574-aa5a-11e6-81de-6a60c3c4cac6.png)

**Comment by mjbvz** [comment]
I just checked in a fix to support identifying links in the markdown editor #18821. 

#18824 will tackle clicking local links in the preview itself. Please give it a try in the next insiders build

**Comment by rafaroca** [comment]
Tried the insiders build, works as expected. Great work, thanks @mjbvz
