### ISSUE TITLE
Editor does not open when opening files

### ISSUE THREAD

**Issue by devdaddy** [Microsoft/vscode#37710]
- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Updated code-insiders
2. Open code-insiders
3. Folder opens with previously opened files, but no editor.
4. Tabs are visible, no editor.

Reproduces without extensions: Yes/No

**Comment by devdaddy** [comment]
no extensions same result

**Comment by devdaddy** [comment]
Sorry, dupe of #37698

**Comment by isidorn** [comment]
Closing as dup then
