### ISSUE TITLE
Turn off hiding of tree view buttons

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#37714]
When a tree view has some extra buttons (e.g., new file in explorer), they only appear when hovering, or focusing the tree view.

Could an option be added to not hide them? Hiding them does not return any space to the user, it simply makes the display a bit cleaner.

It took me ages to work out where I had once seen the git refresh button in the insiders build because with multiple source control providers another tree view is shown, which means the buttons which are normally on the source control titlebar are now hidden.

Personnally I think it is unfriendly UI design to make the user have to move their mouse around in order to find buttons.

**Comment by aeschli** [comment]
This is about the actions in the section headers:
![image](https://user-images.githubusercontent.com/6461412/32540379-d87581c0-c46c-11e7-8132-81ef933f7bcc.png)

**Comment by shivammittal99** [comment]
Hello, I would like to work on this.
Which property defines the property of visibility. I tried searching for it in extensions/git and also in workbench/parts/scm, but couldn't find it. Please guide.

**Comment by JacksonKearl** [comment]
Working on this
