### ISSUE TITLE
docker extension fails to load if expanded on startup

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#37718]
clone the vscode-docker extension 

``` console
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install && vsce package
code-insiders --install-extension vscode-docker-0.0.21.vsix
```

start vs code
expand the docker sash, note you can see "images", "containers", and "registries"
close VS Code
open VS code
note that the docker explorer is empty
click on refresh on the docker sash, get an error that the command is not found
open chrome dev tools, extension host shows an error that `this._state.then is not a function...`

![image](https://user-images.githubusercontent.com/1487073/32451659-3c7276bc-c2cc-11e7-8cc0-dca01e420792.png)

**Comment by bpasero** [comment]
@sandy081 maybe a 1.18 candidate?

**Comment by sandy081** [comment]
@chrisdias Is this the issue you were mentioning yesterday?

I am not able to reproduce this on latest insiders after following the steps you mentioned. If you are seeing this issue, we can do screen share and investigate.
