### ISSUE TITLE
Javascript JSON processing - IDE showing error on funcitons that has to be executed on JSON elements at runtime

### ISSUE THREAD

**Issue by bishupaulose** [Microsoft/vscode#37715]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Gradle|caz|1.1.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.2
vscode-html-css|ecm|0.1.8
vscode-spring-boot|ecm|0.0.10
tslint|eg2|1.0.14
angular-bootstrap|her|4.0.6
beautify|Hoo|1.1.1
teste|ign|2.1.2
Angular2|joh|2.10.0
intellij-idea-keybindings|k--|0.2.16
Angular-BeastCode|Mik|5.0.12
debugger-for-chrome|msj|3.5.0
polymer-ide|pol|0.6.0
java|red|0.13.0
vscode-icons|rob|7.17.0
html-css-class-completion|Zig|1.13.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Read json from a url
2. read all eno from json
3. console.log(resp.body.map(e => e.eno));
4. ide will show error on map saying body does not exist, so map cannot be applied to body (That is true body will be constructed only at runtime)
5. However this is a valid scenario in JSON processing where developers need to access elements from the JSON path which does not exist at dev time.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please share a code snippet or link to a small example project that shows this problem
