### ISSUE TITLE
Support projects with multiple tsconfig.json

### ISSUE THREAD

**Issue by Pajn** [Microsoft/vscode#3772]
We have a project that consists of multiple typescript projects, as it's conceptually the same project for us we does not want to open only subsets of it. Atom supports this case, but it would be great if VS Code supported it too.

An example of the folder structure is:
```
client/
  lib/
    app.ts
  tsconfig.json
server/
  some-service
    lib/
      service.ts
    tsconfig.json
```

**Comment by Pajn** [comment]
I don't know if this should be in this request, or in an another but I'm placing it here for now.

It would also be great that when I have a npm linked module which are also in the opened project and use _go to definition_ on something that comes from that module, I would end up at the actual location instead of inside node_modules. Or maybe easier, if I try to access a file over a symlink and that symlink resolves to a path inside the opened folder, VS Code would open the resolved file instead.

**Comment by egamma** [comment]
@Pajn the setup in your description is supported and is also a setup we use in the VS Code source code https://github.com/Microsoft/vscode. What makes you believe that this isn't supported?

**Comment by Pajn** [comment]
Before when I opened the complete project I got errors on for example async/await that I must target ES6 to use it, which we are. However those were gone when I opened sub-projects so the tsconfig.json i in the root.
However, when I open it now it seems to work so I can't really say what happened before :/

Feel free to ignore that, if I see it again I will try to track it down better. Should I close this and open a new issue for the feature request in the comment?

**Comment by egamma** [comment]
I'll close this one, pls reopen if you run into the behavour you described above again.

Please open a separate issue against microsoft/typescript about the go-to definition behaviour mentioned above. The TypeScript language server implements the go-to-definition behaviour.

**Comment by darkyen** [comment]
I have the same issue, however I am sharing a lot of my `tsconfig.json` in root. So my entire folder structure is 

```
/
    /src
       /server
          tsconfig.json <- Adds things that make sense only on server (like target es6)
       /client
          tsconfig.json <- adds jsx: "preserve" 
    tsconfig.json
```

When I use the typescript compiler (which is running via webpack's ts-loader) everything works perfectly and I get no errors. However, in the editor I constantly get warnings regarding Cannot use max unless --jsx is provided.

**Comment by darkyen** [comment]
For anyone else having this issue where your compiler does not work alongside the editor please goto `.vscode/settings.json` and add  `"typescript.tsdk": "./node_modules/typescript/lib"`. It will bring parity between the different versions.

**Comment by AnimaMundi** [comment]
I'm running into this issue now.
My main configuration file

**Comment by vasanth-asokan** [comment]
I am running into this too, exactly as @AnimaMundi says. I have tried @darkyen's suggestion and that doesn't fix the issue. @egamma could we please reopen this or could you please describe settings if any to get this setup working?

**Comment by darkyen** [comment]
Have you tried turning it off and on again?

**Comment by AnimaMundi** [comment]
@vasanth-asokan the work around that I've been using is a main `tsconfig.json` file which is configured purely to support intellisense in the editor, I don't use it in any compilation. Then I use a `tsconfig.app.json` for my main application's compilation and a `tsconfig.test.json` for test compilation. It's not ideal, but at least it works.

**Comment by egamma** [comment]
>I'm running into this issue now with multiple tsconfig files in the root directory which have different names.

@AnimaMundi I assume when use these tsconfig files with different names from tsc, then you call tsc with `tsc -p tsconfig.test.json`? I don't think that the typescript server supports tsonfig files with different names. @mattbierner can you pls confirm.

**Comment by AnimaMundi** [comment]
Yeah that's exactly what I do. I guess that restriction on TypeScript server would put the problem outside of VSCode's scope.

**Comment by borekb** [comment]
Some of our projects also use different versions of TypeScript in their respective `node_modules` folders. Is this supported by VSCodel, currently? I only see a way to set a single workspace version of TS.

**Comment by jameshulse** [comment]
@AnimaMundi I ran in to what sounds like a similar issue but managed to solve it relatively elegantly.

Typescript walks up the directories from a `.ts` file until it finds a `tsconfig.json` so put your config as close to your code as possible if you have different requirements. So in your case, that is one in the test folder and one in your app folder. Typescript configuration has a concept of 'extending' other configuration so my final setup was this:
```
/app
    /client
        client.ts
        tsconfig.json <- Client specific Typescript configuration ("extends": "../tsconfig.base.json")
   server.ts
   tsconfig.json <- Server specific Typescript configuration ("extends": "./tsconfig.base.json")
   tsconfig.base.json <- Shared configuration
```
This solved my intellisense and compilation issues.

**Comment by andreabreu-me** [comment]
I hope for a better solution. I like having all my config files in the root folder.
