### ISSUE TITLE
keymap for cursorEndSelect does not work more than once

### ISSUE THREAD

**Issue by vsundar723** [Microsoft/vscode#37723]
- VSCode Version: Version 1.17.2 (1.17.2)
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open vscode, change cursorEndSelect shortcut to a mapping 'cmd+shift+right'
2. Restarting vscode, it works one or two times and then stops.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@vsundar723 Have you searched for `cmd+shift+right` in the keybindings UI (`cmd+k cmd+s`). Perhaps there is a collision with a keybinding from an installed extension ?

**Comment by vsundar723** [comment]
I have searched and thats the only shortcut that has the keybinding. Also if I edit, try to press cmd+shift+right, it doesnt populate. Up and Down works but not left or right.

**Comment by alexandrudima** [comment]
@vsundar723 Having `cmd+shift+right` not get populated is an indicator that there is some application on your machine that "steals" that shortcut.

I cannot explain why the shortcut would work once or twice before stopping to work. Perhaps that is just a coincidence and you launch some other application that takes over `cmd+shift+right` ?

Can you reproduce this issue if you run as the Guest account ?

**Comment by vsundar723** [comment]
The weird thing is that when I open VScode with a file already opened in it, the shortcut works for couple of seconds. Then it stops.

I disabled all extensions and removed all the custom user settings, still no effect.

**Comment by alexandrudima** [comment]
@vsundar723 We only dispatch keybindings that reach us. The widget in the following gif shows which keybindings reach our logic. If it doesn't show up in that box, there is no code change we can do on our side, it means we are not receiving the keypress...

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
