### ISSUE TITLE
Can't click and drag on terminal links to highlight them anymore

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#37729]
![nov-06-2017 11-29-35](https://user-images.githubusercontent.com/323878/32459858-cbbd30aa-c2e5-11e7-94cc-34b76549fbfd.gif)

This works in 1.17

**Comment by Tyriar** [comment]
Thought this was already reported but maybe it was just in my head 😄

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1111

**Comment by Tyriar** [comment]
This has been fixed a while, assigning to milestone for verification.
