### ISSUE TITLE
Latest insider install/update broken?

### ISSUE THREAD

**Issue by osstekz** [Microsoft/vscode#37726]
Does not allow display/edit/paste of any type file (.md, .txt, .ts, ....)
However, Welcome does display and links work and FileExplorer works as well
Also tried various Change Themes, which do change the theme only

Suspect editors are not loading

Version 1.19.0-insider
Commit 432b53bc3a263fda8db6ecca83d1ce89ede04bf2
Date 2017-11-06T06:22:36.757Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1.Install latest daily update
2.

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Try to provide us more information, like the output of the Developer Tools (Help => Developer Tools).

**Comment by pwicks86** [comment]
Oops, didn't see this, I think i'm seeing the same problem with this build, see #37732

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/37698
