### ISSUE TITLE
editor.mouseWheelScrollSensitivity is not respected in workbench.

### ISSUE THREAD

**Issue by zholobov** [microsoft/vscode#37727]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
project-snippets|reb|0.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Set editor.mouseWheelScrollSensitivity in settings
2. Do a search that returns more than one screen of result.
3. Scroll the search results using mouse wheel.
4. The scrolling is not affected by the setting.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
That's a setting for the editor only, and in general, I don't think there's a way to customize the scroll sensitivity for the workbench. Not sure whether we can control this or if it's just up to Chrome.

**Comment by robermorales** [comment]
If #47230 was closed because this issue, I hope this issue must be addressed. It is a bit annoying having different sensitivities in the same window.

**Comment by usernamehw** [comment]
It's not exactly the solution but there's a new feature in [Insiders](https://code.visualstudio.com/insiders/) https://github.com/Microsoft/vscode/issues/24344 

```json
"editor.fastScrollSensitivity": 15,
```
When holding modifier key <kbd>Alt</kbd> scrolls much faster (applies to views like explorer too).

**Comment by kumarz** [comment]
I just want to check before opening an issue,
As of now, I am not able to use the mouse wheel to maximize and minimize the screen resolution
But it works with ctrl + Keyboard (+/-) key

**steps to reproduce:**

- open workbench(web version)
- press CTRL + mouse wheel scroll for either up / down to maximize or minimize
- it won't work

workaround: to use CTRL + keyboard (+/-) to bring it back to normal.

**Comment by YashKumarVerma** [comment]
I'm facing this issue and still looking for a solution 👎

**Comment by kuzivany** [comment]
Scrolling is too fast in version 1.46.1.

Setting `editor. mouseWheelScrollSensitivity` to `0.1` worked for me

**Comment by roblourens** [comment]
I think that between https://github.com/microsoft/vscode/issues/96409 and #24344 this can be closed.
