### ISSUE TITLE
Opened file shows blank screen

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#37720]
- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Open a file.
2. Nothing!

The file on disk does have content, but vscode isn't rendering anything.

![empty](https://user-images.githubusercontent.com/19274678/32453710-e2d05f24-c2d1-11e7-8710-fe131c995969.jpg)

This started happening after I updated vscode this morning. Restarting vscode doesn't fix the problem.
Not a problem in vscode non-insiders.

**Comment by stefanmaric** [comment]
Duplicated of #37698.

Also see #37703
