### ISSUE TITLE
Missing text in files and unable to type text in new files

### ISSUE THREAD

**Issue by green4ao** [Microsoft/vscode#37725]
- VSCode Version: Code - Insiders 1.19.0-insider (432b53bc3a263fda8db6ecca83d1ce89ede04bf2, 2017-11-06T06:22:36.757Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
clojure|avl|0.9.1
scala-lsp|dra|0.2.2
code-runner|for|0.8.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mcarpenterjr** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/06564be0-93e6-44c6-8479-62051bb40ae4-1226cfca-7889-4f73-83fe-a8b2afa987d4-v1.png?transparent=1&palette=1&width=246)

closing my recent issue #37728 In favor of this already established issue.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/37698
