### ISSUE TITLE
Word wrap like Sublime Text

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#37722]
- VSCode Version: 1.17.2
- OS Version: macOS

Hello, VS Code team.

I want to suggest a feature. In Sublime Text word wrap is auto which means if you're editing for e.g. `.js` file word wrap will be off, but if you're editing `untitled` or `.txt` and so on word wrap will be on. It just turns on word wrap for `.txt` files and other files which are not "source files" like `.js`, `.ts`, etc. But for "source files" it will turn word wrap off.

This helps a lot, because sometimes I write some ideas/todos in new file and I want word wrap to be on, but when I'm working with JavaScript I want it to be off.

Thanks!

**Comment by alexandrudima** [comment]
You can customize this via settings easily:

You can see we do this out-of-the-box for markdown files:

```
  "[markdown]":  {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  }
```

So, in user settings you can add:

```
  "[plaintext]":  {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  }
```

**Comment by bsvipas** [comment]
@alexandrudima Thank you very much! It works! :)
