### ISSUE TITLE
No "Open in a new tab" menu option.

### ISSUE THREAD

**Issue by joseangelyanez** [Microsoft/vscode#37733]
- VSCode Version: All
- OS Version: All

Steps to Reproduce:

1. Right click a file
2. 'Open in a new tab" option should be visible.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I believe this is a concious design decision. Forwarding to @bpasero to decide what to do here

**Comment by fabiospampinato** [comment]
I think this could be implemented with an extension, but as far as I know the new menu entry will be displayed at the bottom of the list, but it should really be close to the other "Open ..." entries.

**Comment by bpasero** [comment]
Yeah an extension can add a "Split Editor" action. Closing.
