### ISSUE TITLE
feature request: improve experience for reading long compiler error messages

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#37738]
- VSCode Version: 1.17.2
- OS Version: 10.12.6

Steps to Reproduce:

1.  Write code that produces a long compiler error message
2.  Try to interpret the error message in vscode

The best workflow I've found seems to be to copy the problem from PROBLEMS view and paste it into an editor window somewhere ...  Would be nice to have an easy way to view the full/formatted error message without having to take such explicit action ... 

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@breathe You can see the complete message when you hover on it. Let me know if it helps in seeing the complete message?

**Comment by breathe** [comment]
The biggest part of this complaint — impossible to see the full error - can be addressed by setting the typescript compiler option — noErrorTruncation.

**Comment by sandy081** [comment]
Closing this issue as there is an hover to see the message
