### ISSUE TITLE
Visual Studio Code is unable to launch debugger

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode#37734]
- VSCode Version: see log
- OS Version:see log

Steps to Reproduce:

1. Create the usual application with react-native init something
2. goto VS code open the folder try to debug.

It's probably a configuration issue 

Reproduces without extensions: Yes/No

React Native Log when launching with debugger.

OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 23246
Debugger worker loaded runtime on port 40050
SyntaxError: Unexpected token <
vm.js:74
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
.....

Here the about box in VS Code:
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:46.104Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[OK]

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by weiwolves** [comment]
+1
got the same problem,but "react-native run-ios" from terminal is OK

OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4

**Comment by andrebraga** [comment]
Heads up: this issue is the same as this issue: https://github.com/Microsoft/vscode-react-native/issues/580
And is caused by this: https://github.com/facebook/metro-bundler/blob/dbb2d44c42e23a83c1b9f51a577afa003f34e6b0/packages/metro-bundler/src/Server/index.js#L529

Namely: Metro Bundler is interpreting `debuggerWorker.js` to be processable by the caching mechanism. Because of a single letter case change.

**Comment by weiwolves** [comment]
@andrebraga so how can i bypass this problem, i am stubbled with this for hours ....

**Comment by andrebraga** [comment]
@weiwolves Downgrade to React Native 0.49.5.

**Comment by weiwolves** [comment]
@andrebraga works like a charm, thx

**Comment by weinand** [comment]
@andrebraga thanks for the heads up.

/cc @roblourens fyi
