### ISSUE TITLE
Feasibility of LTS release to enlarge release-cycles or choice of update channel

### ISSUE THREAD

**Issue by MrShoenel** [Microsoft/vscode#37737]
- VSCode Version: 1.17
- OS Version: Windows 10 Education (current)

Well, I suppose this is more of a feature-request about the release-cycles of VSCode and not a problem with the software itself.
I appreciate the ongoing development and the agile and continuous approach of VSCode's development. It guarantees a stable product with latest features.

However, now I am writing from the perspective of a casual user, who uses VSCode irregularly and less frequently (in my case roughly once every other week). As such a user, I am usually greeted by VSCode telling me that there is a new version that I can install. While the update process runs smoothly and did not cause any troubles for me so far, I am usually inclined installing the latest version to get all recent improvements or security patches. That, on the other hand, means that I have to sit through an installation process basically every time I want to run VSCode.

Therefore I was wondering, if there is some kind of LTS version planned. Me, the casual user, does not need the bleeding edge of the software, but rather a product that works the same in two weeks as it did today, not reminding or even requiring me to install its latest version. Instead of an LTS release, another option might be to choose the update-channel of the application (like I think it's done in e.g. Firefox).

**Comment by chrisdias** [comment]
We've done quite some work to improve VSCode's auto-update on Windows such that it should happen in the background when you restart, and you don't see the dialog.  worst case scenario, you can turn off automatic updates (see our [FAQ](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates)).
