### ISSUE TITLE
Cannot use a local gulp path that works on all platforms

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3774]
In my task.json I would like to use the "gulp" installed in the project's node_modules instead of a globally installed gulp. On OS X and Linux I was able to use:
```json
"command": "node_modules/.bin/gulp",
```
But this does not work on Windows because there I have to use backslashes.
 ```json
"command": "node_modules\\.bin\\gulp",
```
It would be great if this limitation could be lifted.

**Comment by dbaeumer** [comment]
You can have OS specific command sections. 

	"windows": {
		"command": "..."
	},
	"osx": {
		"command": "..."
	}
