### ISSUE TITLE
typescript intellisense opens wrong 'lib.d.ts'

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#37746]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. `npm init -y`
2. `npm install typescript`
3. `tsc --init`
4. `echo 'fetch()' > index.ts`
5. in tsconfig.json, change lib to `["es2017", "es2015.promise", "dom"]`
6. open index.ts in vscode
7. ctrl-click on the `fetch` symbol

vscode opens the wrong `lib.es6.d.ts` file. the one it opens is in `C:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib`, the one that is used by the project is in `./node_modules/typescript/lib`.

**Comment by mjbvz** [comment]
Did you also switch your workspace to use the local version of typescript? This can be done by running the `select TypeScript version` command in vs code

**Comment by Spongman** [comment]
no i hadn't done that. I would expect it to use the locally-installed compiler's libs by default.

**Comment by mjbvz** [comment]
You need to select the workspace version the first time for security reasons. Please try doing this and let me know if you still see the incorrect behavior
