### ISSUE TITLE
Can Linux verson using Chinese now?

### ISSUE THREAD

**Issue by boblao0714** [Microsoft/vscode#37747]
For some reason I had to switch to Ubuntu for a while and I still need a good editor and I've tried this before on a Ubuntu device and it just don't have Chinese.
I'm not saying that I can't use English but still a Chinese verson will be welcome.

**Comment by swituo** [comment]
@boblao0714

F1 -> [Configure Language]

![image](https://user-images.githubusercontent.com/2868877/32485933-0c859e60-c3e0-11e7-91c8-1f3631b722bd.png)

**Comment by isidorn** [comment]
@swituo thanks for jumping in
