### ISSUE TITLE
The code prompt  fails during using

### ISSUE THREAD

**Issue by ScutDP** [Microsoft/vscode#37759]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.22.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.10
vscode-eslint|dba|1.4.2
githistory|don|0.2.3
es7-react-js-snippets|dsz|1.2.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|5.7.1
vscode-html-css|ecm|0.1.8
react-native-react-redux|EQu|1.4.1
prettier-vscode|esb|0.24.0
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
code-runner|for|0.8.3
vscode-nginx-conf-hint|han|0.0.4
beautify|Hoo|1.1.1
vscode-gitk|how|1.3.2
useful-react-snippets|igo|1.1.2
path-autocomplete|ion|1.6.2
docthis|joe|0.6.0
vscode-colorize|kam|0.6.9
vscode-codemetrics|kis|1.10.0
vscode-regexp-preivew|le0|0.0.3
node-module-intellisense|lei|1.4.0
vscode-filesize|mkx|1.0.0
vscode-scss|mrm|0.6.2
syncing|non|1.4.9
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.17.0
vscode-nginx|sha|0.4.1
vscode-import-cost|wix|2.5.1
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
I don't understand. Can you please provide a description of what is going wrong and some steps to reproduce this problem. Screenshots may also be helpful

**Comment by mjbvz** [comment]
Closing as this issue is not actionable without more information
