### ISSUE TITLE
typescript has a problem

### ISSUE THREAD

**Issue by LovEoRNot** [Microsoft/vscode#37756]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.3
react-native-react-redux|EQu|1.4.1
canvas-snippets|hol|0.3.2
vue-snippets|hol|0.1.5
RelativePath|jak|1.0.0
vscode-language-babel|mgm|0.0.10
Angular-BeastCode|Mik|5.0.13
vscode-jade-snippets|mrm|1.0.1
node-debug2|ms-|1.18.4
vetur|oct|0.11.0
ejs-language-support|Qas|0.0.1
java|red|0.13.0
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
open-in-browser|tec|1.1.0
vscode-react-native|vsm|0.5.1
html-css-class-completion|Zig|1.13.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What is the problem?

**Comment by mjbvz** [comment]
Closing as this is not actionable without more information
