### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by banziFD** [Microsoft/vscode#37750]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
mssql|ms-|1.2.0
cpptools|ms-|0.14.0
java|red|0.13.0
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Mostly happens when include a headerfile.
2. Prompting Message: EBUSY:resorce busy or locked, open'path to file'

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@banziFD are you sure this reproduces when you run without extensions enabled?
