### ISSUE TITLE
Workbench never loads when trying to restore user settings editor after reload 

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#37751]
- VSCode Version (OSS) : built from e5b9b820ef7ac52f8f0088aa4a4f2f17be6884df
- OS Version: Darwin x64 17.2.0

Steps to Reproduce:

1. Build the OSS version, open up your user settings 
2. Close the editor (hot exit)
3. Reopen the editor 

The workbench process will never finish loading. This means that none of the commands will work, syntax highlighting is broken, etc. 

I believe the issue lies with this commit: ff82f1a7529de588312459fa1f5a4dfb5ff214b1, which creates a circular dependency:

- When launching the editor, the workbench attempts to restore the user settings editor. 
- The user settings editor has the default preferences editor on the left, which attempts to resolve the default preferences model. 
- The default preferences model waits for the ext host to be ready before it contributes the model (I presume so that it can get the info about the settings contributed from extensions). 
- However, the ext host will never be ready because all the editors haven't been restored yet (this is where the circular dependency is introduced). 

Simply closing the user settings editor doesn't work, because it'll just be restored when you re-open the editor. 

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
😱

**Comment by jrieken** [comment]
@ggilmore Thanks. This is a very good find.

**Comment by jrieken** [comment]
I have pushed a change that undoes what happened with my previous commit. Closing this and I'll continue the discussion in #37541
