### ISSUE TITLE
expose ConfigurationResolverService api to DebugConfigurationProvider

### ISSUE THREAD

**Issue by andxu** [microsoft/vscode#37757]
- VSCode Version: 1.17.2
- OS Version: win10 64 bit

Steps to Reproduce:

We are developing java debug plugin for vscode, while we need to validate mainClass/project/classPath according  to user inputs in DebugConfigurationProvider#provideDebugConfigurations method, but if user specifies the value in launch.json with vscode variables like ${workspaceFolder}, ${fileBasenameNoExtension}, the code cannot get the actual value after variable replacement in DebugConfiguration, can vscode side expose the ConfigurationResolverService  to outside for replacing values in DebugConfiguration or provides a replaced version? See issues: https://github.com/Microsoft/vscode-java-debug/issues/85

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@andxu I suggest to to validate the launch configuration in the debug adapter (because there variable substitution has already occurred). This is what all other debug adapters do.
