### ISSUE TITLE
F12（reference ） is not see

### ISSUE THREAD

**Issue by randscar** [Microsoft/vscode#37754]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-csharp-snippets|jor|0.2.0
unity-code-snippets|kle|1.0.0
csharp|ms-|1.12.1
mono-debug|ms-|0.15.7
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1
unity-snippets|Ycl|0.1.2

---

Steps to Reproduce:

1.Unity environment ever has reference menu（F12），but now it only have ” Change all matches ” menu  and has no Code prompt

Reproduces without extensions: Yes/No

**Comment by randscar** [comment]
![image](https://user-images.githubusercontent.com/2282311/32475580-8aa560a6-c3ad-11e7-9fec-5527e7741ee1.png)
how can i do?

**Comment by weinand** [comment]
Please file this issue against the corresponding repository.
