### ISSUE TITLE
A bug when using a precision touchpad.

### ISSUE THREAD

**Issue by TXH1997** [Microsoft/vscode#37760]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

1.Using a precision touchpad, scroll the screen in the text editor
2.You might find that the screen doesn't roll fluently.(terrible experience when coding without a mouse.)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612
