### ISSUE TITLE
Move loaded scripts explorer into VS Code

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37767]
Today the "loaded scripts explorer" is implemented in the node-debug extension and is only available for a few JavaScript runtimes despite the fact that the "loaded scripts" functionality is available in the debug adapter protocol.

To make the "loaded scripts explorer" available for all debug extensions, we should move the implementation into the VS Code debugger (and eliminate the QuickPick based variant).

**Comment by weinand** [comment]
@isidorn here is a sketch for some initial implementation:
- debug viewlet shows "LOADED SCRIPTS" view if DA capability `supportsLoadedSourcesRequest` is on (and if there are in fact loaded scripts).
- initially read all scripts via the `loadedSources` request and add them to the tree root as "Source" objects (you don't have to build a tree from them because that code already exists in node-debug and I will try to port it over). Selecting one of them should load the source from the DA.
- hook up the `loadedSource` event for `add` and `remove` and add (resp. remove) sources from the tree.
- "LOADED SCRIPTS" should only show if at least one debug session is active.
- If multiple sessions are active, the "LOADED SCRIPTS" view should show the scripts of the active session.

**Comment by isidorn** [comment]
@weinand I have pushed the initial template for the LOADED SCRIPTS view. 
To enable it simply remove [this line](https://github.com/Microsoft/vscode/blob/cad1659a76b329328c97fc9fb5dfb4200471739e/src/vs/workbench/parts/debug/common/debugViewModel.ts#L73)

The view can be found [here](https://github.com/Microsoft/vscode/blob/cad1659a76b329328c97fc9fb5dfb4200471739e/src/vs/workbench/parts/debug/browser/loadedScriptsView.ts#L19) and the things you mentioned above should be easily pluggable.

Let me know if I can help in some other way and I can jump on it. Thanks!

**Comment by weinand** [comment]
The implementation is mostly done, but the move will happen in August.
