### ISSUE TITLE
[Request] Distinguish thrown from uncaught exceptions.

### ISSUE THREAD

**Issue by crystalbyte** [microsoft/vscode#37765]
- VSCode Version: 1.17.2
- OS Version: Windows 10

I'd like to request a feature to distinguish thrown from uncaught exception where possible.
Within the last 3 days I have spent quite some time debugging exceptions I didn't have to since I forgot to uncheck the "Block on all exceptions button". In VS those types of exceptions are marked in different colors which makes it easy to instantly see why a block occurred. It'll be great if we could have something similar in VSC too.

**Comment by weinand** [comment]
There is no generic concept for this in VS Code.
What language are you using?

**Comment by crystalbyte** [comment]
You are correct, this obviously differs from language to language. I am using nodejs.

**Comment by connor4312** [comment]
When debugging Node.js, you can configure whether you want to stop on all thrown exceptions, or only uncaught ones.

![image](https://user-images.githubusercontent.com/2230985/66434887-62204300-e9d8-11e9-97ae-8f9057c1898d.png)

Are you looking for a feature where, when `All Exceptions` is ticked, you want to see whether the exception will end up getting caught or not?
