### ISSUE TITLE
Checksum error in deb package for code.desktop file

### ISSUE THREAD

**Issue by LaurentBonnaud** [Microsoft/vscode#37762]
- VSCode Version: 1.17.2-1508162334
- OS Version: Debian/Ubuntu

Steps to Reproduce:

1.
```
$ debsums -s code
debsums: changed file /usr/share/applications/code.desktop (from code package)
```

**Comment by LaurentBonnaud** [comment]
The problem still exists in this package version:
```
Package: code
Version: 1.18.0-1510145176
```

**Comment by Tyriar** [comment]
@LaurentBonnaud what's meant to happen when you do `debsums -s code`?

**Comment by LaurentBonnaud** [comment]
"debsums -s code" is supposed to display no output, which means that the package is OK.

**Comment by LaurentBonnaud** [comment]
The problem still exists in this package version:
```
Package: code
Version: 1.19.0-1513245498
```
