### ISSUE TITLE
IDE code folding and left side expansion sometimes bug

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#37763]
- VSCode Version:1.17.2
- OS Version:10.12.6

Steps to Reproduce:

1 code folding: Sometimes fold, the location will be wrong, the folded area is also wrong. Level and closed tags are all normal, only when the restart will be good.
2 left fold: sporadic, and sometimes more levels, there will be so-called "penetration", the document through other levels. The same restart just fine.
The above two sporadic almost at the same time appear, it should be a little relationship, not often found. Hope to amend.

Reproduces without extensions: Yes/No

**Comment by cw19931024** [comment]
add a image
![image](https://user-images.githubusercontent.com/15888370/32485955-cfff7562-c36a-11e7-95cf-917b92c71eb5.png)

Even the text will be folded. . .

This is normal label. Look at the picture;

![image](https://user-images.githubusercontent.com/15888370/32486150-67da1982-c36b-11e7-987d-46d236954c9c.png)

The result is the following result


![image](https://user-images.githubusercontent.com/15888370/32486299-db9341b4-c36b-11e7-8ed9-fa3682719f7a.png)

**Comment by aeschli** [comment]
The folding regions are based on indentation only. A new folding region starts when a line has a smaller indent that the following line.
I think what you are expecting is that folding is aware of the HTML constructs. The issue for that is #3422.
