### ISSUE TITLE
Terminal doesnt run.Code 259

### ISSUE THREAD

**Issue by dxyqqs** [Microsoft/vscode#37764]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17025
![image](https://user-images.githubusercontent.com/4122955/32485989-4142c34e-c3e0-11e7-8e2f-b154eaa9963d.png)

- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
vscode-express|Com|0.0.5
vscode-ipaddress|Com|1.0.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.2
Angular2|joh|2.10.0
code-beautifier|mic|1.7.2
vscode-todo-parser|min|1.9.1
azure-account|ms-|0.1.3
short-js-doc|mya|0.1.10
vetur|oct|0.11.0
vscode-docker|Pet|0.0.20
material-icon-theme|PKi|2.2.4
datetime|rid|1.0.5
vscode-icons|rob|7.17.0
code-settings-sync|Sha|2.8.5
svg-snippets|sid|1.0.1
terminal-tabs|Tyr|0.1.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. `Ctrl+~` to show terminal 
2. PS auto exit with code **259** , CMD auto exit with code **1**
![image](https://user-images.githubusercontent.com/4122955/32485956-2a487346-c3e0-11e7-9ef1-b13b97328d91.png)

Reproduces without extensions: Yes
Reproduces after re-install:Yes

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by asvetliakov** [comment]
Same thing here, easily reproduce - try to run: ```rollup -c -w``` with dumb rollup config. In my case the rollup seems to trying to clear the terminal when starting.
Sometimes it works when executed via task, sometimes doesn't.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36994
