### ISSUE TITLE
Scroll click to open new window

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#37761]
Under Windows, scroll clicking (middle mouse button) e.g the Excel or Chrome open application icon prompts a new window. It would be nice for VSCode to do so as well.

1. Scroll click the application icon in the task bar
2. VSCode opens a new window (Ctrl+Shift+N)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by csholmq** [comment]
@bpasero Right, that's what I did. However, with "Scroll click" I didn't find any. "Middle mouse click" was the key apparently.

For reference, the issue referred to is https://github.com/Microsoft/vscode/issues/13905
