### ISSUE TITLE
Error Invalid string length attempting to close VSCode after editing large file

### ISSUE THREAD

**Issue by gjmoyer** [Microsoft/vscode#37774]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
angular2-snippets|dan|1.0.16
githistory|don|0.2.3
python|don|0.7.0
vscode-generate-getter-setter|DSK|0.4.2
tslint|eg2|1.0.14
vs-code-xml-format|fab|0.1.5
beautify|Hoo|1.1.1
docthis|joe|0.6.0
prettify-json|moh|0.0.3
mssql|ms-|1.2.0
azure-account|ms-|0.1.3
azurecli|ms-|0.3.0
csharp|ms-|1.12.1
azurerm-vscode-tools|msa|0.3.7
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
vscode-sql-beautify|sen|0.0.4

---

Steps to Reproduce:

1. Have auto save enabled.
1. Open a large file.  In my case CSV file is 307MB
2. Scroll to bottom of file, and make a single character change
3. Close the file.
4. Close VSCode and should now see the error and VSCode does not close.

Reproduces without extensions: Yes

**Comment by gjmoyer** [comment]
The file is encoded as ASCII text that I am opening with CRLF line terminators.  In case that is relevant.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/32503
