### ISSUE TITLE
CSS warning about duplicate style definitions without taking RGBa into count

### ISSUE THREAD

**Issue by eyal0803** [Microsoft/vscode#37777]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
---
```css
background-color: rgb(0, 0, 0);
background-color: rgba(0, 0, 0, 0.4);
```
The CSS style definitions above yield the following warning:

> [css] Do not use duplicate style definitions

There's nothing wrong or duplicate with those definitions since I'm defining a fallback for browsers without RGBa support.

**Comment by aeschli** [comment]
It's an optional validation, turned off by default.
The setting for it is
`"css.lint.duplicateProperties": "ignore",`

**Comment by eyal0803** [comment]
I know it's an optional validation, but that's a pretty common trick to support browsers without certain features. Ah, nevermind doesn't really bother me...
