### ISSUE TITLE
Insiders build not updating on Windows

### ISSUE THREAD

**Issue by tmknight** [Microsoft/vscode#37773]
VSCode Version: Code - Insiders 1.18.0-insider (098bb77, 2017-11-04T04:43:03.436Z)
![image](https://user-images.githubusercontent.com/548588/32495882-7236d878-c395-11e7-88f1-31269cddf24f.png)

OS Version: Windows 10 Pro x64, Version 1709, Build 16299.19

Steps to Reproduce

1. Download the Insiders build for Mac and Windows from https://code.visualstudio.com/Insiders/
2. Launch and notice that it's not been updated since 04 Nov, 2017.
3. Click the gear on the bottom left of the window (the usual place) and select "Check for updates".  No updates available

See previously closed issue for potential repeat: #35390

Reproduces without extensions: Yes

**Comment by DmitriyPotapov** [comment]
Same problem, on Win 10 x64.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

VSCode Version: Code - Insiders 1.18.0-insider (af39ef5, 2017-11-07T16:42:34.634Z)

I just got an update.

![update](https://user-images.githubusercontent.com/19866231/32512327-cac97278-c3dd-11e7-87be-7be208852d22.PNG)

**Comment by tmknight** [comment]
As did I.  Closing issue report...

**Comment by tmknight** [comment]
Re-opening; updates seem to be broken again.  No updates since 8th Dec
![image](https://user-images.githubusercontent.com/548588/33894069-09a6af70-df2b-11e7-84a7-f82d190cefaf.png)

**Comment by ramya-rao-a** [comment]
An Insiders build for Windows was just released.

**Comment by tmknight** [comment]
Insiders updates ceased as of 21 Dec:
Version 1.20.0-insider
Commit f9115349ef09cfef2bed669680d10ac58b490dce
Date 2017-12-21T16:36:58.030Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by will-l-h** [comment]
Disabled until new years

https://github.com/Microsoft/vscode/issues/40871#issuecomment-354194121
