### ISSUE TITLE
Why vscode can't provide the automated build settings？

### ISSUE THREAD

**Issue by ATURBO** [Microsoft/vscode#37776]
it‘s a small IDE，
but i believe you can do better！

the problem is so clear，
i hate to configure settings every time when i begin a new pro，
some time i have to find the last settings。

not everyone should have known how to configure，
we just care the efficiency，
so，i have told my problems&concerns，
if you see，help me，help us，
let me just pay our attention to our codes，not configure..

**Comment by dbaeumer** [comment]
@ATURBO can you please provide an example with that describes what you mean. We do have automated builds for things we ship out of the box (for example TypeScript). See Task > Run Build Task.
