### ISSUE TITLE
vscode.workspace.textDocuments returns extra documents

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#37778]
I'm using the right window to debug the left window, below the tooltip there's this line: `const docs = vscode.workspace.textDocuments`. As you can see I only have 1 document opened, but `vscode.workspace.textDocuments` tells me that I have 2:

<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/1812093/32498472-1a54da52-c3d0-11e7-980a-92c176e7b9bb.png">

- VSCode Version: Code 1.17.2
- OS Version: Darwin x64 17.3.0

**Comment by jrieken** [comment]
Your file is under git source control which creates "virtual" documents holding the before state. That is used for compare etc. Generally, there can more *documents* than *editors* but never the other way around.

**Comment by fabiospampinato** [comment]
Thanks for the explanation.

Perhaps the docs should be improved, reading "All text documents currently known to the system." I'm not entirely sure what counts as "known".
