### ISSUE TITLE
[typescript] Offer IntelliSense suggestions based on method parameter or local type

### ISSUE THREAD

**Issue by rstarkov** [Microsoft/vscode#37771]
It would be useful if IntelliSense offered suggestions based on the expected type of the expression being edited. Consider the following examples:

    function Foo(thing: Namespace.Stuff.SomeClass) { ... }

    Foo(new |
            ^ here

    let x: Namespace.Stuff.SomeClass;
    x = new |
            ^ here

In these cases, "Namespace.Stuff.SomeClass" should be offered by IntelliSense at the indicated positions.

This behaviour would also be handy for enums: the enum type could be offered in the same contexts as above (without the `new` keyword obviously).

For enums there's another scenario where this would be handy, namely when I'm comparing an enum-typed local or parameter - IntelliSense should offer the enum type for autocompletion after I type the comparison operator.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19855
