### ISSUE TITLE
All breakpoints gets unverified on VSCode running a Yii2 advanced project. WHY?

### ISSUE THREAD

**Issue by MichalYosef** [Microsoft/vscode#37779]
Hello, I'm running an advanced Yii 2 app on XAMPP

- VSCode Version: 1.17.2
- OS Version: Windows 10

am trying to debug

I Disabled all extensions at the VS Code except from the PHP Debug 1.11.1
it didnt help.

every breakpoint I put gets immediatly unverified

Would appreciate a lot any hint...

**Comment by weinand** [comment]
@MichalYosef do breakpoints get immediately unverified while running a debug session or while outside of a session?

**Comment by MichalYosef** [comment]
Immediatly

בתאריך 7 בנוב 2017 18:15,‏ "Andre Weinand" <notifications@github.com> כתב:

@MichalYosef <https://github.com/michalyosef> do breakpoints get
immediately unverified while running a debug session or while outside?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/37779#issuecomment-342534382>,
or mute the thread

**Comment by MichalYosef** [comment]
immediatley

**Comment by weinand** [comment]
sorry, but "immediately" is not a helpful answer. Let's try it again:
do breakpoints get unverified while running a debug session or while not running a debug session?

**Comment by MichalYosef** [comment]
sorry but i dont understand how they can break when not running
anyways it seems like a more serious problem, right now my pc won't
restart....

בתאריך 8 בנוב 2017 00:00,‏ "Andre Weinand" <notifications@github.com> כתב:

**Comment by mradcertica** [comment]
@weinand  Interesting.  I'm having the same issue.  All breakpoints become unverified.
Open php source.
Switch to debug.
Listen for XDebug
Set breakpoint in source file.
Access page that calls into function with breakpoint.
Breakpoint becomes unverified.

**Comment by MichalYosef** [comment]
yep
same here
the breakpoints gets unverified on runtime

2017-11-08 0:33 GMT+02:00 mradcertica <notifications@github.com>:

**Comment by weinand** [comment]
This issue was moved to felixfbecker/vscode-php-debug#201

**Comment by MichalYosef** [comment]
solved it by adding to php.ini -

[XDEBUG]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
