### ISSUE TITLE
Wrong order of incoming input from adapter

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#37770]
Originaly reported by @good-bits
I can repro both with `node2` and `node` debug adapter
I tried with node 7.9, os x

Have the following node program, notice how the output is coming wrongly ordered from the debug adapter:

```javascript
for (var i =0; i < 20; i++) {
    console.log('log : ' + i);
    console.error('error : ' + i);
}
```

[Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L366) where output is recieved on the vscode side.

**Comment by weinand** [comment]
Running the program in VS Code results in this output on the debug console:
![2017-11-07_12-44-56](https://user-images.githubusercontent.com/1898161/32492127-7d6967fa-c3b9-11e7-9d87-8f467d5a2eeb.png)

If you run the program from a terminal you get this:
![2017-11-07_12-47-24](https://user-images.githubusercontent.com/1898161/32492212-d3ba213a-c3b9-11e7-8562-90e7e5520621.png)

This discrepancy is expected. Here is the explanation:

Node.js tries to detect whether its stdout and stderr streams are connect to a line-oriented device (like a terminal) or to a block oriented device (e.g a file).
In the former case it assumes that a user is running the node program interactively and node flushes buffered "log" or "error" data after one line. As a result the "log" or "error" output appears alternating.
For block oriented devices more data is buffered until it is flushed. 

By default VS Code launches node.js programs for the "Debug Console" in a way that uses block oriented streams. That explains the multi-line buffering which results in the unexpected ordered output.

To fix this, you can set the `console` attribute of a launch configuration to either `integratedTerminal` or `externalTerminal`. In this case a line oriented output device is used which results in ordered output.

**Comment by roblourens** [comment]
True when reading from stdout/err, but there is a bug here in node2 getting messages from the debug protocol. It's in the correct order in chrome devtools. Error messages will be delayed for this line: https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L896 and will end up out of order. This code needs to handle only one message at a time.
