### ISSUE TITLE
Importing unnecessary path with Angular/ngrx

### ISSUE THREAD

**Issue by rwmb** [Microsoft/vscode#37786]
When auto importing content from Angular and ngrx modules, the editor is including an unwanted path to the deepest path possible (I believe), which also gives an error that took me a few hours to find for ngrx. The feature is apparently working great for finding the files and objects btw.

- VSCode Version: 1.18.0-insider
- OS Version: Windows 10

Steps to Reproduce:
![vscode-autoimport-unwanted-path](https://user-images.githubusercontent.com/20707521/32516479-656e2dec-c3fb-11e7-8582-29ecc16060fa.gif)

1. Inside Angular project type NgModule or Component, etc and press Enter.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19840
