### ISSUE TITLE
Webview can't handle custom authenticated proxies

### ISSUE THREAD

**Issue by d0nkeyBOB** [Microsoft/vscode#37783]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.0.1
azuretoolsforvscode|bra|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-hasher|dee|1.0.1
xml|Dot|1.9.2
CppSnippets|har|0.0.13
vscode-nuget-package-manager|jmr|1.1.4
azure-functions-tools|joh|0.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
azurecli|ms-|0.3.0
cpptools|ms-|0.14.0
csharp|ms-|1.12.1
azurerm-vscode-tools|msa|0.3.7
Csharp-ASPNETCore|rah|1.0.5

---

Steps to Reproduce:

1. Update VSCode
2. Relaunch opens 'Release Notes' tab but notes are blocked by company intranet trying to launch network sign-in
3. Sign-in never actually launches, so release notes are not viewable

![vscode_releasenotes](https://user-images.githubusercontent.com/56018/32512314-9ac4348c-c3c4-11e7-8d2c-dc1ace26093f.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@mjbvz @jrieken  Have you seen this in the webview before? Have we tackled it?

**Comment by mjbvz** [comment]
I have never seen that. It looks like custom html that is being served up in place of the release notes? We block popups from webviews so that may be why no prompt is ever shown

@d0nkeyBOB In VS Code with the release notes page showing, can you please run `Developer: Webview tools` command. Are there any errors in the developer console?

**Comment by d0nkeyBOB** [comment]
`Blocked script execution in 'file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/parts/html/browser/webview.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

**Comment by mjbvz** [comment]
Yes we disable scripts in the release notes. Does your company proxy normally serve up the `Please wait...` page in place of the real requested content?

**Comment by d0nkeyBOB** [comment]
Its a redirect type system on most websites. It usually goes to the auth verification page after this if the site isn't blacklisted.

**Comment by mjbvz** [comment]
So we hit https://code.visualstudio.com/raw/v1_18.md using our standard request service which I believe does observe the proxy. After that, the webview appears to be doing the right thing with the contents it gets back. It should never be able to run scripts or launch other windows. 

@d0nkeyBOB Do you have any `http.proxy*` settings or have you configured http_proxy in your environment?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate further
