### ISSUE TITLE
Unable to find commands in published version of extension

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode#37788]
- VSCode Version: 1.17.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Install the latest Cake Extension for Visual Studio Code
2. Open command palette
3. Type `cake`
4. Select `Install a configuration file`
5. You will get the following

![image](https://user-images.githubusercontent.com/1271146/32520811-3bc17b6c-c409-11e7-9c18-0416e0e1bea4.png)

However, this same process, when debugging the source code in Visual Studio Code, works fine.

Any ideas on what could be going on here/

Reproduces without extensions: Unable to verify, as I need extensions active

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by gep13** [comment]
@bpasero The extension in question is the one that I am creating 😄 and the error I am seeing is due to the fact that the published VSIX file doesn't contain the `out` folder, which as a result means that the commands can't be found at runtime.

Having dug into this some more, it looks like there was a problem with our build process.

I am still investigating a fix...

**Comment by gep13** [comment]
@bpasero looks like I have solved the issue.  I have fixed to an earlier version of typescript, which gets us round the publishing issue just now, and we can look to increasing to higher version, once we figure out what the typescript compilation errors are regarding.  This at least allows us to get the extension out to our users.
