### ISSUE TITLE
Close all the child processes launched from the terminal on Quit

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#37782]
- VSCode Version: 1.17.2
- OS Version: Mac OSX Sierra

When press Cmd+C on a terminal instance after running my node process, apart from terminating the node process itself, it finds and closes all the child processes which were spawned.

However, if I delete the terminal instance itself or Quit VSCode then these traces or child processes are left open. This could be a resource hog if the user doesn't remember to terminate the process by themselves.

## Steps to Reproduce:

1. Run some code which spawns child processes
2. Either Quit the IDE by pressing CMD+Q or using the menu
3. Or remove the terminal instance by clicking on the bin icon on the top right side corner of the terminal

The child processes will be left running.

(the following code launches a Chrome Instance, if you press CMD+C in the terminal it will also close the chrome instance, but if you quit the editor or remove the terminal then the browser remains opened)

### Sample code:

```const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto("https://www.example.com/");

  debugger;
  // await browser.close();
})();
```

**Comment by shivammittal99** [comment]
Hello, I would like to work on this. Could you please help as to where I should get started.
Thank you

**Comment by shivammittal99** [comment]
I am on version 1.18.0 (Stable) on Ubuntu 16.04.
The chrome window does remain open even after removing the terminal. But same behaviour is shown for  the system terminal also.
Similarly for Firefox, both vscode and system terminal kill the process before exiting.

**Comment by atif089** [comment]
@shivammittal99  On Windows (and Mac) it doesn't kill the Chrome process even when VS Code is exited. However, if I press Ctrl+C in the terminal, then it kills the process properly.

**Comment by Tyriar** [comment]
Can you give more complete instructions on how to run the example code?
