### ISSUE TITLE
terminal not working

### ISSUE THREAD

**Issue by kundan4all** [Microsoft/vscode#37785]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.2.9200
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.19
prettier-vscode|esb|0.24.0
git-project-manager|fel|1.4.0
bettercomment|Gru|0.0.5
beautify|Hoo|1.1.1
Angular1|joh|0.2.0
vscode-language-babel|mgm|0.0.10
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
angular1-snippets-shark|yan|0.1.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please provide more information, what's not working about it, can you post a screenshot, what's in your settings.json file, etc.
