### ISSUE TITLE
Typescript crash

### ISSUE THREAD

**Issue by paraswatts** [Microsoft/vscode#37798]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide information about the issue

**Comment by mjbvz** [comment]
Please provide information about the issue

**Comment by mjbvz** [comment]
Closing as not actionable without more information
