### ISSUE TITLE
Hangs on startup

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#37799]
vscode will hangs on startup. Blank editor window opens, unable to move it, can only close it. This is happening more and more at infrequently.

<img width="1032" alt="screen shot 2017-11-08 at 12 59 09 am" src="https://user-images.githubusercontent.com/439226/32533865-cdaad1ba-c420-11e7-85ed-ba6667ae9441.png">

I have to kill the entire session in macos from the Taskbar sometimes to get things back to working conditions.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.11.0
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.14
debugger-for-chrome|msj|3.5.0
autoimport|ste|1.5.3
vim|vsc|0.10.2
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. type: code .

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rajinder-yadav** [comment]
Sure I'll start using the nightly-build and see if it hangs overtime.

FYI: I am not sure if this hang showed up after the I updated my MacOS to the latest 10.13.1 ?

**Comment by rajinder-yadav** [comment]
Hello I just got the same hang using code-insiders. Also once this happens, I need to completely close all running instances of vscode to get back to a working state to be able to open vscode again.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by rajinder-yadav** [comment]
I tried this and didn't see anything?

**Comment by bpasero** [comment]
@rajinder-yadav so it no longer hangs?

**Comment by rajinder-yadav** [comment]
code-insiders also did hang once, I just was not able to get any longs with the method you suggested.

**Comment by rajinder-yadav** [comment]
Closing, not seeing after using latest code-insiders. Will reopen if shows up again.
