### ISSUE TITLE
feature need, copy history list

### ISSUE THREAD

**Issue by ljyf5593** [Microsoft/vscode#37795]
the vacode can provide a copy history list feature?  like sublime text。

when in the editor copy some content , press `ctrl + k, ctrl + v` pop the copy history list. user can select some one to paste

**Comment by ljyf5593** [comment]
I found the extend [Multiple clipboards for VSCode](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-multiclip) has implement this feature, maybe we can closed this issue.

**Comment by alexmironof** [comment]
@ljyf5593 these kind of extensions are all really buggy, laggy and a bit outdated.
If plugin is loading or lagging, copy or paste doesn't work, also copy fro mexternal source doesn't work.

Looking for native solution

**Comment by govindrai** [comment]
I occasionally overwrite my last copied data when I delete a line by pressing CMD+D or CMD+X. The clipboard history would save me a bunch in sublime (CMD + K, CMD + V). It would be good to see prioritization of this feature.
