### ISSUE TITLE
Allow sharing of task environments

### ISSUE THREAD

**Issue by zjturner** [Microsoft/vscode#37796]
Various tasks need environment variable set up to work properly. Currently a task can use the "tasks/options/env" property to define additional variables per task.

However, you may have many different tasks, and all of them need the same environment. It is cumbersome to duplicate this in every single task. It would be nice if there was a syntax to inherit this somehow.

For a simple example of where this would be useful, consider the case of defining tasks for running CMake in various configurations (debug, release, x86, x64) against an MSVC toolchain.  In order for this to work, each of these will need to set up a vcvars-like environment of include paths, lib paths, etc.  The path to the headers is always going to be the same, and the path to the lbiraries will always be the same for x86 (across debug & release), and will always be the same for x64 (across debug & release).

So we should be able to define a single include environment, and 2 lib environments, and then when we define the tasks for each of the cmake configurations, simply import the two previously defined environments.

The alternative is to copy a huge mess of variables into every single task, which is pretty cumbersome.

**Comment by jeff-kilbride** [comment]
Currently, the debugger allows an `envFile` key in `launch.json` configurations. I was surprised to see that this is not available in `tasks.json`. This would be a great addition to tasks!

**Comment by dbaeumer** [comment]
Yes, dups #36769. @jeff-kilbride thanks.
