### ISSUE TITLE
Verbose "extract local constant"

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#37790]
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:35:35.044Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Many

1. In a function, extracting `createReporter()`:
```ts
	const subscriptions = context.subscriptions;
	subscriptions.push(createReporter());
	subscriptions.push(createStatusBarItem(azureLogin.api));
```
2. Results in:
```ts
	const subscriptions = context.subscriptions;
	const reporter: { dispose(): any; } = createReporter();

	subscriptions.push(reporter);
	subscriptions.push(createStatusBarItem(azureLogin.api));
```
3. Unexpected: There is an extra line and a type declaration.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19839
