### ISSUE TITLE
Clicking on filenames in terminal does not work when line is wrapped

### ISSUE THREAD

**Issue by spacem** [Microsoft/vscode#37791]
I wondered for a while why sometimes ctrl+clicking on a filename in the console doesn't open the file. I just noticed it is failing when text is wrapped. This is for a build task which has an exception I want to investigate.

For example I see the error:
    at SomeDataAccessMongo.module.exports.SomeDataAccessMongo.processCriteria (c:\work\project1\project1\something\db\some-dao-mon
go.js:43:27)

Notice the line break put in between some-dao-mon and go.js

Yes I don't have a very wide screen and this error line is crazy long.. but if I press ctrl+b to close the side panel it the console text is not re-wrapped. So I cant click on it and I cant see any way to configure the console to have scrollbars, etc unless I restart the build task with the side panel closed. After which I can see the full error text on one line and can click it fine.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
gitlens|eam|5.7.1
tslint|eg2|1.0.14
vscode-mocha-sidebar|mat|0.10.16
HTMLHint|mka|0.4.0
spellchecker|swy|1.2.13

---

Steps to Reproduce:

1. 
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746
