### ISSUE TITLE
Call out code blocks more prominently

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3779]
Currently this is how we show code blocks. 

![image](https://cloud.githubusercontent.com/assets/2449568/13575871/e01a7598-e43f-11e5-978f-cc7c447b02cb.png)

One thing I really miss from Sublime is the Bracket Highlighter package. 

![image](https://cloud.githubusercontent.com/assets/2449568/13576040/89cb07f6-e440-11e5-810d-19afc587f7b3.png)

It would be great to have some sort of option here. I don't believe there is a way to do this with the current extension api. My feature request is to expose something in the extension api or to make it a product feature.

**Comment by mjbvz** [comment]
Closing as extension-canidate
