### ISSUE TITLE
incorrect grammer selection

### ISSUE THREAD

**Issue by that70schris** [Microsoft/vscode#37794]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. set a color for "entity.other.attribute-name"
2. notice that classes and ids in css receive this color

**Comment by aeschli** [comment]
It's up to each grammar to decide which scope to use. Often it has historical reasons and can't be changed easily as many themes depend on it.
You can file a change request against the grammar itself, but I don't think they are eager to change this.
css grammar: https://github.com/atom/language-css

**Comment by that70schris** [comment]
ok, I managed to find these:
```
entity.other.attribute-name.class.css
entity.other.attribute-name.id.css
```
which helps me correct the problem.  Those scopes just look so weird to me since I don't see why attribute-name would ever relate to css class/id
