### ISSUE TITLE
somehow i have not been able to install/download VSC

### ISSUE THREAD

**Issue by Denissondesouza** [Microsoft/vscode#37792]
- VSCode Version: tried to download it. NOT successful
- OS Version: 10.12.6

Steps to Reproduce:

1. can't download
2. download timed out

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
How did you try to download? Did it work after a short while?

**Comment by Denissondesouza** [comment]
I have a Mac so click on download and keeps processing and times out. Tried qDozens of times and always time out and dont download

**Comment by joaomoreno** [comment]
Even right now? What is the URL that times out?

**Comment by Denissondesouza** [comment]
Hi John, are you Portuguese or Brazilian? 
hey one of the students here help me out, I have not been able to download, weird but not happening so a student sent me folder on google drive with the software, so I am able to use it but I think visual code should look it up and fix it. 
thank you

**Comment by joaomoreno** [comment]
I think something must be wrong with your specific setup since no one else complains about this. This might be your network blocking the download request.

**Comment by Denissondesouza** [comment]
ola tudo bem? I will check this out, i am always downloading something and it's the first time I had this problem, thanks for taking your time. tenha um bom dia!
