### ISSUE TITLE
Add platform info in code --version

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#37793]
- VSCode Version: 1.17.2
- OS Version: Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:

1. run code --version in cmd
2. see output

Reproduces without extensions: Yes

Currently, we can see only version number when run code --version, please add platform info into the output. We are developing an one-click installation script for user to setup dev env, and the script will install vscode or update vscode to the latest version for the user. So we need to know which platform of vscode does user have already installed on Windows.

**Comment by joaomoreno** [comment]
Wanna submit a PR?

**Comment by ninijay** [comment]
I would like to make my **first** PR here. I know where to print out the info, but not sure on where to get the platform information.

**Comment by joaomoreno** [comment]
`process.arch`!

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/37824
