### ISSUE TITLE
Font ligatures are not visible anymore in Integrated Terminal

### ISSUE THREAD

**Issue by VamshiKrishnaAlladi** [Microsoft/vscode#37805]
- VSCode Version: 1.17.2
- OS Version: Winodws 10

Reproduces without extensions: Yes

The user settings has following settings in it

![image](https://user-images.githubusercontent.com/9594837/32536933-84ee1278-c486-11e7-9526-79a397afd34b.png)

Yet, the ligatures do not appear as expected in the terminal window.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34103
