### ISSUE TITLE
Extension API: workspace.findFiles() has a different behaviour

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#37806]
- VSCode Version: 1.17.2
- OS Version: multi (description below)

### Preparation
Use a workspace with the following code structure:
```
workspaceroot/
├── foobar.ts
├── sub/
│   ├── subfile.ts
├── out/
│   ├── out.js
│   └── out.d.ts
└── node_modules/
    └── my-lib/
        ├── my-lib.d.ts
        └── out/
            ├── out.js
            └── out.d.ts
```

When using the `workspace.findFiles()` function with relative patterns, I'm experiencing a pretty weird scenario.
First of all I do two searches:
1. Search all files that match a certain pattern in the workspace without node modules
2. Search all files of that pattern only in the node modules.

The weird behaviour is the fact, that there are different results depending on the OS one is using. So on Linux, the ignore patterns work differently than on macOS (explained below).

The code is the same for both operating systems:
```typescript
const ignore = [
    'build/**/*',
    'out/**/*',
    'dist/**/*',
];

const ignoreWorkspace = [
    ...ignore,
    'node_modules/**/*',
];

const workspaceFiles = await workspace.findFiles(
    new RelativePattern(workspaceFolder, `{**/*.ts,**/*.tsx}`),
    new RelativePattern(workspaceFolder, `{${ignoreWorkspace.join(',')}}`),
);

const moduleFiles = await workspace.findFiles(
    new RelativePattern(workspaceFolder, `{node_modules/**/*.ts,node_modules/**/*.tsx}`),
    new RelativePattern(workspaceFolder, `{${ignore.join(',')}}`),
);
```

(A little simplified. The whole code is: https://github.com/buehler/typescript-hero/blob/develop/src/common/helpers/DeclarationIndexHelpers.ts#L102)

On a **macOS** based machine:
Workspace files work as expected, it finds `foobar.ts` and `subfile.ts`, `out` is ignored.
Module files work kinda like expected, it finds `my-lib.d.ts` and `out` is ignored.

On a **linux** based machine:
Workspace files work as expected, it finds `foobar.ts` and `subfile.ts`, `out` is ignored.
Module files work different than on macOS, it finds `my-lib.d.ts` and `out` is **not** ignored, so `out/out.d.ts` is added as well.

Is there any difference between the os implementations?

Cheers and thanks for any advice!
Chris

**Comment by buehler** [comment]
Follow up:

When the ignore patterns are changed to:
```typescript
const ignore = [
    '**/build/**/*',
    '**/out/**/*',
    '**/dist/**/*',
];
```
It works better, meaning that both OS do produce the same output.
But the question still stands :-)

**Comment by chrmarti** [comment]
@buehler `out/**/*` used to match only `out` in the workspace root. There is is a regression in 1.17 (#36438) that makes it also match nested `out` folders. In 1.18 this should be fixed. If you want to match both `out` folders, you will need your updated pattern `**/out/**/*`.

Could you check if the current insiders build shows the expected behavior with both types of patterns?

**Comment by chrmarti** [comment]
Not sure yet why it shows different behavior on the two OSes. Do you have the setting `"files.exclude"` set to anything else than the default? That setting is applied to `findFiles()` searches (#33528).

**Comment by buehler** [comment]
Hey @chrmarti 
Sorry for the late response :-)

I did use the `**/out/**/*` notation now. In response to your question about the `files.exclude`, I need to say.. nope 😅 

I don't have any files excludes or search excludes set.

Kinda strange.

But now I'm struggeling with other issues with the 1.18 release. It broke my build. But just online on travis.

**Comment by chrmarti** [comment]
@buehler Is this still an issue?

**Comment by buehler** [comment]
I remove the feature from TSHero so it does not matter anymore ;-)
