### ISSUE TITLE
Test Tour: Python

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3780]
1. Clone the [Python Django sample app](https://github.com/kirpit/django-sample-app). 
2. Install [popular Python extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python)
3. Run the app and confirm that there are no errors. 
4. Tryout python debugging

**Comment by isidorn** [comment]
I tried a simple python script which I could successfully debug with minimal configuration, however my limited python skills did not allow me to go too crazy on this tour.

**Comment by bpasero** [comment]
I can give it a try.

**Comment by bpasero** [comment]
@weinand I am not able to open an external console when debugging python, is it true that the extension writer has to implement this? because I see it working for node.js

**Comment by weinand** [comment]
@bpasero yes, external code support is different for different runtimes/debuggers. The extension writer has to implement this. Since there is no predefined builtin attribute `externalConsole`, the attribute should show a squiggly if used for the python debug type.
