### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Kemper-Diao** [Microsoft/vscode#37800]
The vscode process is not closed When I close the vscode program,and Sometimes the plugin shortcuts fail.  How to solve this problem

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
easy-less|mrc|1.4.5
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.17.0
open-in-browser|tec|1.1.0
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by maelvalais** [comment]
Wow, I just tried the Insiders and it uses so much less memory!

**Comment by bpasero** [comment]
@maelvalais how about now that 1.18 is released to stable?

**Comment by maelvalais** [comment]
nope, same issue (except the icon is now blue); I made sure I have the same extensions and everything but still huge difference in memory and CPU in the first 20 seconds after launch. Code Insiders is way lighter.

I'll continue to investigate. Is there a way to know which Code helper is related to which extension?

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Kemper-Diao** [comment]
High CPU usage problem is solved, insiders version is great。3Q @bpasero
