### ISSUE TITLE
[Windows] Add a registry key for detecting if VS Code is installed and to allow invocation from other product installers

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/vscode#37807]
We are bundling an extension for VS Code with another product installer and would like to install that extension as part of the overall product installation. However, there seems to be no reliable registry entry that would let us find the path to code.exe.

We'd like to request to add a registry key under:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\code.exe 
with the following two values of type REG_SZ:
(Default) ->  full path to code.exe
Path -> directory path to where code.exe is placed

This aligns with how other Microsoft products register their presence on the machine, for example Outlook where this information is used for installing Outlook Add-Ins.

**Comment by joaomoreno** [comment]
Are you sure there's no current registry key? I'm pretty sure you can find one. Double check that.

**Comment by StanislawStempin** [comment]
There are several entries related to shell integration and protocol handler but they are either not reliable (user can opt out during setup) or don't contain the information in the right format to be consumed by the installer. For example the vscode protocol handler entry (HKEY_CLASSES_ROOT\vscode\shell\open\command) contains a default value:
"C:\Program Files\Microsoft VS Code\Code.exe" --open-url "%1"
While this value could be used through a custom installer action that would parse it to arrive at the VS Code installation folder it is not directly consumable by WIX Toolkit that our product uses for building the installer and diverges from other Microsoft products.

**Comment by joaomoreno** [comment]
On my machine I have:

```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{1287CAD5-7C8D-410D-88B9-0D1EE4A83FF2}_is1
```

In that key, there is the `DisplayIcon` value which has the `C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe` as data.

You can rely on this.

You need to be aware that there are 4 different app ids:

- `C26E74D1-022E-4238-8B9D-1E7564A36CC9` - 32bit insider
- `1287CAD5-7C8D-410D-88B9-0D1EE4A83FF2 ` - 64bit insider (that's the one I have)
- `F8A2A208-72B3-4D61-95FC-8A65D340689B ` - 32bit stable
- `EA457B21-F73E-494C-ACAB-524FDE069978 ` - 64bit stable
