### ISSUE TITLE
Staging / Unstaging a file takes ~80ms to paint (i.e. is slow)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#37819]
- VSCode Version: Code - Insiders 1.18.0-insider (af39ef560060e7e8ba8d75983c9ec1da3f4d2a20, 2017-11-07T16:42:33.037Z)
- OS Version: Windows_NT x64 10.0.16299

---

Steps to Reproduce:

1. Have 39 staged files and 10 unstaged files
2. Stage a file. Unstage the same file. Stage the same file. Unstage the same file, etc.
> Observe: This comes in asynchronously and it blocks the UI for long enough that I notice that VS Code is slow and need to stop what I'm doing to figure out what's going on. To make it worse, this occurs a significant amount of time after I click the button, so it makes me believe that typing in the editor is slow.

In this profile, I only do these actions (stage and unstage):
[CPU-20171108T151237.zip](https://github.com/Microsoft/vscode/files/1454163/CPU-20171108T151237.zip)

![image](https://user-images.githubusercontent.com/5047891/32553561-89c5b0ba-c497-11e7-9a8f-41639b4acb47.png)

Here is the original profile (for which the search viewlet got an issue too) where also the SCM shows up with >100ms (excluding the GC).
[CPU-20171108T150231.zip](https://github.com/Microsoft/vscode/files/1454165/CPU-20171108T150231.zip)

![image](https://user-images.githubusercontent.com/5047891/32553670-d3484946-c497-11e7-9912-4a080e02983d.png)

**Comment by joaomoreno** [comment]
Alright, got a speed up of **35x**!

Got it done by finalising the work I started a few months ago: by computing the exact changes made by an extension on the SCM API side, I can apply those exact changes all the way down to the DOM. I just needed to stretch that out to the List itself, which was still rendering everything in the viewport whenever its model changed. Now, it only renders what is necessary.

### Before 🐌 

A stage and unstage resulted in two chunks of ~450ms each.

![image](https://user-images.githubusercontent.com/22350/33040587-c84d9a8e-ce3b-11e7-9470-ac3431945bfb.png)

### After ⚡️ 

A stage and unstage now results in two chunks of ~13ms each.

![image](https://user-images.githubusercontent.com/22350/33040664-0d34c80c-ce3c-11e7-943e-d55694d84aae.png)

---

Perf traces attached: [perf.zip](https://github.com/Microsoft/vscode/files/1489071/perf.zip)

**Comment by alexandrudima** [comment]
Sweet!
