### ISSUE TITLE
Test Tour: PHP 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3781]
1. Clone [php slim starter](https://github.com/xsanisty/SlimStarter)
2. Install popular [PHP extension](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug).
3. Run sample app and confirm it works as expected.

**Comment by gregvanl** [comment]
I used a WAMP server (http://www.wampserver.com/) to test PHP on Windows. 
Verified built-in snippets and IntelliSense.
Configured and tested linting with php.exe.
Installed and tested debugging with XDebug extension.
