### ISSUE TITLE
Terminal: often looks broken when I come back to VS Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37811]
Since a couple of days when I come back to my integrated terminal I see garbled UX like this:

![image](https://user-images.githubusercontent.com/900690/32541509-2be9f950-c470-11e7-9840-21e0039c2db7.png)

Some interesting facts:
* I am using macOS high sierra
* I am always using full screen
* I have zoom level of 1
* I am using tmux

**Comment by Tyriar** [comment]
@bpasero do you have an external monitor? https://github.com/Microsoft/vscode/issues/34320

**Comment by bpasero** [comment]
@Tyriar yes, I do! I only use that (e.g. just 1 monitor).

**Comment by Tyriar** [comment]
I think this is a duplicate of https://github.com/Microsoft/vscode/issues/34320
