### ISSUE TITLE
Increased tweet character limit for Twitter feedback

### ISSUE THREAD

**Issue by akigugale** [Microsoft/vscode#37816]
Twitter have officially increased their tweet character limit to 280.
 
- VSCode Version: 1.17.2
- OS Version: macOS High Sierra (10.13)

<https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html>

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
