### ISSUE TITLE
Put closing x-icon that closes the file to the left for mac users

### ISSUE THREAD

**Issue by AndrewBargan** [Microsoft/vscode#37814]
- VSCode Version: 1.17.2
- OS Version: macOS HighSierra

Steps to Reproduce:

1. Open any file in VSC
2. Take a look at the title of the file which come with x-icon that closes the file

Result:
x-icon is on the right

Expected result
x-icon is on the left as any mac user expects it  :)

**Comment by bpasero** [comment]
`"workbench.editor.tabCloseButton": "left"`

**Comment by AndrewBargan** [comment]
Thanks a lot, bpasero! )
