### ISSUE TITLE
Incorrect tip for JSON schema.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#37817]
- VSCode Version: Code 1.17.2 **[Unsupported]** (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-translate|chu|0.1.0
vscode-eslint|dba|1.4.3
python|don|0.7.0
Go|luk|0.6.67
background|sha|1.1.16
intelligence-change-case|zhe|1.1.0
vscode-proto3|zxh|0.1.2

---
See this issue report in [vscode-eslint](https://github.com/Microsoft/vscode-eslint/issues/339).
![image](https://user-images.githubusercontent.com/12682063/32547506-944644d4-c4bd-11e7-8983-77d3d8a8ee4a.png)

I found that this was cause by the builtin JSON parser for VSCode. The [ESLint JSON schema](http://json.schemastore.org/eslintrc) looks no problem, but the builtin parser read the `description` for the `definitions.rule.oneOf.*` (marked red in the screenshot), instead of `definitions.*.possibleErrors` (marked with blue).
![image](https://user-images.githubusercontent.com/12682063/32547587-e1ee3cc8-c4bd-11e7-83c4-25afabbb1ca2.png)

In other IDEs, such as `IDEA`, it looks like:
![image](https://user-images.githubusercontent.com/12682063/32547839-c52158ae-c4be-11e7-838c-6909668b2397.png)
But in VSCode, it performance correctly only if the value if an array.

I think the `description` for the `definitions.rule.oneOf.*` (marked red) should only showed when I typing to input the value:
![image](https://user-images.githubusercontent.com/12682063/32548024-2a84f9bc-c4bf-11e7-8cab-7fdac0971b5d.png)

In other case, it should show the description for the property itself.

**Comment by aeschli** [comment]
`comma-dange` is a $ref to the oneOfs
IMO both description are valid here. VSCode picks the most specific. IMO that makes sense. The alternative would be to show all descriptions, but that has the danger of duplicate messages,
I'd suggest filing this against the eslint schema (https://github.com/schemastore/schemastore/)

**Comment by zhengxiaoyao0716** [comment]
@aeschli Thanks, but I think that the `most specific` description in here is those:
![image](https://user-images.githubusercontent.com/12682063/32639406-c09f30b2-c5fe-11e7-99f2-190c29008995.png)
The other description in `definitions.rule.oneOf.*` is not for the specific properties, it defined the type and possible values set for those properties. and this works well in other IDEs, but in VSCode, almost all the properties performance incorrectly:
![image](https://user-images.githubusercontent.com/12682063/32639536-5fada80a-c5ff-11e7-80e9-b8781426dcea.png)
![image](https://user-images.githubusercontent.com/12682063/32639560-740d28e8-c5ff-11e7-8347-68334fed5548.png)
Look, for all the rules it show the same tip, this is useless.

And lets see this case, the same property with different type of value:
![image](https://user-images.githubusercontent.com/12682063/32639668-ea509d8c-c5ff-11e7-93aa-c59af8de6dda.png)
![image](https://user-images.githubusercontent.com/12682063/32639651-ddb07138-c5ff-11e7-81d7-544e1dd0176b.png)
It shows that only if the type of value is an array, VSCode would performance right. and I guess it caused by:
![image](https://user-images.githubusercontent.com/12682063/32639809-7d05a168-c600-11e7-8acd-b1c3cda79632.png)
the `array` type defined in `definitions.rule.oneOf` has no description, so you choice the only description on the property itself. so if we assuming that VSCode are right, and try to fix this problem by `eslint schema`, we would removed all other descriptions from `oneOf`, it will looks like:
![image](https://user-images.githubusercontent.com/12682063/32639936-09a95650-c601-11e7-90b3-8867ad5c00f2.png)
This would fix the problem, but it would bring another: now there are no tips if we typing to input the value of the properties:
![image](https://user-images.githubusercontent.com/12682063/32640163-35555488-c602-11e7-9404-6da43c32d7a2.png)

I don't known is there a better way to define both the description of properties and the description of the value set, if there are, I should try to report the issue to the `scheme`. but, I still think that a better way is to change the performance of VSCode builtin JSON parser to choose the special description of the properties themselves, instead their refs, or at least add a button to allow us read more details like this:
![image](https://user-images.githubusercontent.com/12682063/32640421-989329f2-c603-11e7-9ee6-aff1fe26711d.png)
After all, it works well in IDEA.

**Comment by aeschli** [comment]
IMO the most specific one is the value check, but we can argue back and forth. I don't think there is a right or wrong here. Multiple descriptions are asking for trouble. I don't want to change it just so it works with ESLint, potentially changing the behaviour for other schemas.
The underlying problem is that JSON schemas don't let you document values. We added a workaround for that in VSCode with `enumDescriptions`, but it's a VSCode internal extensions.

**Comment by zhengxiaoyao0716** [comment]
@aeschli I think `enumDescriptions` is a good idea. I'm regretful that it is only an internal extensions. And you are right, it maybe cause other potentially problems. But it also hard to change the eslint schema, because it can works well in some other IDEs. Fortunately, this problem only happen with `.eslintrc` actually, and I'll take compromise.
