### ISSUE TITLE
Bad git explorer decoration

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#37810]
1. In a clean git repo, delete a file
2. Outside of Code, create the file again with different contents

The file will appear in the explorer as a deleted file:

![image](https://user-images.githubusercontent.com/22350/32540791-0db9c8ae-c46e-11e7-8f61-eaf75a9b95a6.png)

Though it should appear as modified as it does in the SCM viewlet:

![image](https://user-images.githubusercontent.com/22350/32540796-113390f0-c46e-11e7-81f6-17c34ce008b4.png)

**Comment by jrieken** [comment]
@joaomoreno What event would I have to know this? Today the provider only listens to [`repository.onDidRunOperation(this.onDidRunOperation, this)`](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/decorationProvider.ts#L77) which seems miss some things...

**Comment by joaomoreno** [comment]
Well, there wasn't any change in the repository itself with step 2, there was only a change in the workspace.

I guess you'd have to listen to workspace file events to know this.

**Comment by jrieken** [comment]
> I guess you'd have to listen to workspace file events to know this.

Can I piggy back on the updating of the list? Somewhere the git-extension should do that right? Can we forward that event internally?

**Comment by joaomoreno** [comment]
Yeah, let me take this from you. That way I can also clean up some eventing. 👍

**Comment by joaomoreno** [comment]
Oh this was within the extension confines... so it was just a matter of switching the event. 👍

**Comment by jrieken** [comment]
Ah, likely fixed by other changes I made there... There were some change event computation issues.
