### ISSUE TITLE
[theming] Group themes by type

### ISSUE THREAD

**Issue by MrSunshyne** [Microsoft/vscode#37823]
**Scenario**
Often time developers switch themes using the extremely handy ```CTRL + ` ``` shortcut. 

![image](https://user-images.githubusercontent.com/1721611/32556038-b7feca82-c4b7-11e7-8046-1ba38dfdaa13.png)

**Problem**
However, when going through the list of themes (with instant preview in the background), the user inevitably has to go through some light themes during the navigation. This literally hurts the eyes. 

It's possible to uninstall 3rd party light themes, but the default light themes remain. 

**Suggestion**
It would be preferable to have an option to disable all light themes using ```cmd + shift + p```.
That was I don't have to uninstall my light themes, but at night, I can have the option to not get flashed by my editor

**Comment by usernamehw** [comment]
Another option would be to split themes:

* Ayu Light
* Light (Visual Studio)
* Solarized Light
* `-----------------------`
* Ayu Dark
* Dark (Visual Studio)
* Solarized Dark

Alphabetic sort should persist, but now in groups.

**Comment by MrSunshyne** [comment]
@usernamehw That'd work to. As long the user doesn't have to go bear a flash while switching themes, it would definitely solve the issue.
