### ISSUE TITLE
Allow autoSave and formatOnSave at the same time

### ISSUE THREAD

**Issue by sleutho** [Microsoft/vscode#37820]
Both of these features working together create a great development experience. It's a disappointment to turn one of them off.

This used to work, but got worse recently with many "File is busy" errors that would eventually make it impossible to save the file (C++ formatter).
Now I noticed that the settings documentation states "the file must not be auto-saved" under "editor.formatOnSave". I don't know if this has always been this way.

Please consider to find a way to have them both work together. Maybe with a separate delay on the formatter?

**Comment by bpasero** [comment]
@sleutho you can try to configure `"files.autoSave": "onFocusChange"` to see if that improves the situation. Otherwise it seems to me this issue should be filed against the C++ extension.

**Comment by sleutho** [comment]
A recent C++ Extension fix [#1040](https://github.com/Microsoft/vscode-cpptools/issues/1040) addressed this issue for me. I'll go ahead and close this ticket as not applicable. It's still odd that the documentation says these two settings are mutually exclusive, which suggests that I'm in an area of undefined behavior.
