### ISSUE TITLE
The **run browser** configuration displays old code

### ISSUE THREAD

**Issue by romulus001** [Microsoft/vscode#37828]
- VSCode Version: 1.17.2
- OS Version: Android (only tested on Android)

I debug my typescript project with the **run browser** configuration (as my project calls REST web services) after updated either my HTML or TS code, on my browser (google chrome), only my old code is showed.
For example, in my html code, if I change an **ion-textarea** to **ion-input** element, on my browser, the **ion-textarea** appears.

**Comment by weinand** [comment]
What debug extension are you using?
