### ISSUE TITLE
[feature-request] Expand snippet only when it strictly matches with the prefix

### ISSUE THREAD

**Issue by jcbp** [Microsoft/vscode#37826]
- VSCode Version: 1.17.2
- OS Version: Win7

I used to using the plugin snipMate in vim and I think I coded much faster with it.
There are mainly two differences:
- The snippets are not shown in the autocomplete list, therefore never it be inserted wrongly one for another
- The snippets are only expanded when the trigger matches exactly

This allow you to insert a snippet code without stopping to read a list, look at an icon, navigating the options with the arrow keys or something like that. You just type exactly the prefix and then press the tab key without looking at anything. You could event insert a snippet blindly.

Just as an example I created a snippet with the prefix "f" to insert a JavaScript function but when I type an "f" I have to move down in the list until 18 to select the snippet.

I think it would be great to have an option to configure this behavior.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
@jcbp Did you try tab completion? You can tell the suggestion to *not* show snippets and in return turn on tab-completions. That expands a snippet that prefix-matches when pressing tab. Have this in your settings.json file

```json
"editor.tabCompletion": true,
	"editor.snippetSuggestions": "none",
	"editor.quickSuggestions": false
```

**Comment by jcbp** [comment]
Thanks for reply. I tried the configuration you suggested and it's a great improvement. 
But when I disable the "quick suggestions" it also disabled the autocompletion when pressing tab. I would have liked to be able to use the autocomplete only when it doesn't match a snippet. If I have a snippet with the prefix "func" I would like when pressing tab insert a suggestion by typing "f", "fu" or "fun" but not for "func", i.e if it matched a snippet that gives priority to it.
In vim the list of suggestions is shown when I press tab, not before, but this happens as long as it has not matched with a snippet.

**Comment by jrieken** [comment]
> I would have liked to be able to use the autocomplete only when it doesn't match a snippet.

Understood, you can try turning quick suggestion on again and sort snippets with higher priority in the suggest list via `"editor.snippetSuggestions": "top",`

**Comment by jcbp** [comment]
In that case when I type "fu" and then I press tab it inserts the snippet (which has the prefix "func"). This is the case that would be resolved if the snippet only expands when it exactly matches the prefix.
That is, it is needed that at least one of them requires that it matches exactly so that there are no ambiguous cases. But it only makes sense that the snippets match exactly.

**Comment by jcbp** [comment]
Another problem related to the current behavior occurs when there is a snippet whose prefix contains the prefix of another snippet at the end of the string, in this case the second one never expands. E.g. if I have a snippet with the prefix "func" and another one with the prefix "iifefunc" the second one doesn't work.

This occurs with the following settings:
`"editor.tabCompletion": true,`
`"editor.snippetSuggestions": "none"`

I guess this would be fixed if the snippets only worked with an exact match.

**Comment by gatapia** [comment]
I would also really like to see this. I have a [snippets library](https://marketplace.visualstudio.com/items?itemName=GuidoTapia2.unicode-math-vscode) that is quite big (unicode character aliases for maths work).  I start each of these with a backslash and since I cannot mark these snippets as 'exact_prefix_match' it means I polute the auto-complete list in all languages.

Would love something like:

```
"\\sum": { "prefix": "\\sum", "body": "∑", "description": "∑", "exact_prefix_match": true}
```

Which would make my snippets only appear on the suggestion list when the user types a backslash.
