### ISSUE TITLE
Test Tour: React Starter Kit

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3782]
There is some overlap with other test tour, but this starter kit deserves to be hit hard. It is very popular. 

https://github.com/kriasoft/react-starter-kit

**Comment by isidorn** [comment]
@joaomoreno assigning this one to you as well, if you get too much of react just unassign one of the test tours and I wil reassign it to somebody else

**Comment by egamma** [comment]
Covered by https://github.com/waderyan/react-todo
