### ISSUE TITLE
Starting debug when a Git diff window is active, ${script} is not expanded.

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37821]
_From @rkeithhill on November 6, 2017 5:18_

We've been getting some bugs submitted on the PowerShell debugger that are related to people starting a debug session when their active editor window is a Git diff window of a PowerShell script file.  With script debuggers, it is often desirable to be able to simply start debugging the current file. As such we have debug config for this:
```
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        }
```
Normally, when we handle the resolveDebugConfiguration call we don't do anything with `config.script` or `config.cwd`.  And the debug server gets these values expanded.  However, when the currently selected file is a Git diff window, these two values come through as `""`.  

Are we handling this correctly?  And/or is this a bug?  What do you recommend when folks try to start a debug session from a Git diff window?  Personally, I think we should cancel the debug request from the VSCode extension but I'm not seeing anything in the `config` object that tells me this is a Git diff window.

cc @daviwil 

_Copied from original issue: Microsoft/vscode-debugadapter-node#134_

**Comment by weinand** [comment]
Sometimes I'm doing all my editing in a Git diff window, so for me it makes perfect sense to even start debugging from there.

I think `${file}` should not be empty in this case.

**Comment by isidorn** [comment]
Makes sense.
fyi @dbaeumer

**Comment by rkeithhill** [comment]
OK.  I will change our resolveDebugConfiguration method then to not rely on downstream VSCode code to resolve `${file}` in the config object before it is sent to our debug server.  We will resolve it within the method.  I wonder if we should be resolving all `${}` variables?

**Comment by isidorn** [comment]
@rkeithhill I think I fixed this issue 35 minutes ago :)

**Comment by rkeithhill** [comment]
Cool.  Thanks!

**Comment by weinand** [comment]
Verified.
Please note that ${file} always resolves to the file of the right hand side of the diff editor even if the  left hand side of the diff editor has focus.
So it is not possible to debug the "previous version" of a file.
