### ISSUE TITLE
Enhancement: Add option to reuse "Working Tree" window in the SCM view

### ISSUE THREAD

**Issue by swarnendubiswas** [Microsoft/vscode#37830]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 3.10.0-693.5.2.el7.x86_64
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Modify files in some Git project. 
2. Open the SCM view.
3. View changes in each modified file. VS Code open a different Working Tree comparison pane each time. 

This behavior can be cumbersome if there are several modified files. Instead, it might be easier to reuse one Working Tree buffer.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
We are actually opening in preview mode. Do you have preview disabled in your settings?

This is the default behaviour:

![kapture 2017-11-09 at 8 46 16](https://user-images.githubusercontent.com/22350/32593980-78bd8fa2-c52a-11e7-8f38-254e2557233a.gif)
