### ISSUE TITLE
Auto-temporary save

### ISSUE THREAD

**Issue by haytham-salhi** [Microsoft/vscode#37832]
It is always a good idea to have a temporary save when exiting the VSCode. That's it does not have to ask me each time whether I want to save the file or not. Just save it temporarily and let me leave the IDE.

**Comment by bpasero** [comment]
@haytham-salhi we do that and the feature is called "hot-exit". Are you saying it does not work?

**Comment by haytham-salhi** [comment]
I guess it does not work properly on Mac. I see that this feature is enabled by default and it is working well when quitting the whole app (i.e., command + q). However, it does not work when (the usual way) closing the editor from the close icon (the most top left icon, the x icon) and asks me whether I want to save the file or not.

**Comment by Tyriar** [comment]
I think you want to use `"files.hotExit": "onExitAndWindowClose"`, you can read more about it in the setting's description.
