### ISSUE TITLE
Quick outline: can no longer cycle through results from top to bottom backwards

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37835]
Steps to Reproduce:

1. open quick outline on a TS file
2. type a single character (e.g. the overall input is `@e`)
3. arrow up

=> you are not put to the last element

If you try the same while you just have `@` as input it seems to work just fine. 

Debugging this I think I am doing the right thing in `quickOpenWidget` where I eventually call [`focusLast`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/browser/quickOpenWidget.ts#L490). However, the focused element after this call seems to be `null`.

**Comment by bpasero** [comment]
@joaomoreno ok I have a theory. The tree calls [`TreeNavigator.lastDescendantOf`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeModel.ts#L655) and this seems to return an item which is actually not visible. Quick outline is maybe the only one that when you start typing is actually setting entries to be hidden via a filter instead of always setting the results again.

**Comment by joaomoreno** [comment]
Wow, that's an OLDIE!
