### ISSUE TITLE
No typescript highlighting for arrow function with line break before first param

### ISSUE THREAD

**Issue by arznaar** [Microsoft/vscode#37837]
Code below compiles correctly to javascript and runs without error.

- VSCode Version: 1.17.2
- Typescript version: 2.5.3
- OS Version: Windows 10 version 1703 build 15063.540
- Reproduces without extensions: Yes

Steps to Reproduce:

Write first param for the arrow function on the next line. Example: 
```
const goodMethod = (param1: string, param2: string) => {
}

const badMethod = (
    param1: string,
    param2: string
) => {
}
```

![vscode-bug-2017-11-08t17-15-00](https://user-images.githubusercontent.com/6916413/32563975-bdf93984-c4c3-11e7-8458-bef5c835b662.PNG)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#539
