### ISSUE TITLE
VSCode should flag errors on tsconfig.json

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#3783]
VS Code does not report errors in `tsconfig.json`, and then silently drops the ball without telling the user. This is particularly annoying since some things might continue working, while others mysteriously stop.

Errors in `tsconfig.json` come in two flavours – actual syntactical errors, but also unrecognized new properties. In particular the latter is annoying, for example when TypeScript adds new features such as `--allowUnreachableCode` (see #3428).

My suggestion would be to at least visibly and loudly report this, but preferably be more lenient about what's accepted (e.g. unrecognized properties).

**Comment by mprobst** [comment]
@rkirov FYI

**Comment by crystalgreen** [comment]
+1
I had a similar issue (non existing compiler option) and I didn't get why my configured target=es6 got not accepted. Interestingly, it worked when compiling over command line but it failed when compiling over tsserver. See also the [related](https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L1239) TS compiler code. Maybe one could get that error from tsserver back to VS code?

**Comment by nrandell** [comment]
+1
I've just had a similar issue that I've spent 3 hours working through. Adding a new typescript 2 option such as "noUnusedParameters" caused vscode to reference lib.d.ts not lib.es6.d.ts, making some of my code have errors in the editor, but not when built!
I've worked around by having a different tsconfig.json that I used for building with.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/TypeScript/issues/10473
