### ISSUE TITLE
[Feature Request] Logging snippets for Javascript

### ISSUE THREAD

**Issue by abinavseelan** [Microsoft/vscode#37839]
# Feature Request - Logging snippets for Javascript

I use VSCode as my editor of choice. ❤️

But one nifty set of snippets that I *do* miss from my time with Atom are the `log`, `warn` and `error` snippets for Javascript.

`log`  => `console.log()`
`warn` => `console.warn()`
`error` => `console.error()`

![atom-log-snippets](https://user-images.githubusercontent.com/6417910/32565352-d415fc7a-c4dc-11e7-84e6-aa07ffc9b905.gif)

Is this something that could make it into VSCode too? 🙂

I've added the list of snippets to `extensions/javascript/snippets/javascript.json` on my forked repo. I can raise a PR for this if this is something that interests the team. 😄

**Comment by mjbvz** [comment]
Yes, please submit a PR if this is something you'd like to see. Here are the built-in snippets files:

https://github.com/Microsoft/vscode/blob/master/extensions/javascript/snippets/javascript.json
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/snippets/typescript.json


Please let me know if you have any questions about adding the snippets

**Comment by abinavseelan** [comment]
@mjbvz 

Raised a PR for this! 🐨  

https://github.com/Microsoft/vscode/pull/37889

**Comment by mjbvz** [comment]
Fixed by #37889
