### ISSUE TITLE
VSCode does not handle Nested Merge Conflicts

### ISSUE THREAD

**Issue by Alexhuszagh** [Microsoft/vscode#37845]
- VSCode Version: 1.17.2, 1.17.2
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Open text file with any encoding.
2. Paste the following into the file.

```
If you have questions, please
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> branch-a
=======
>>>>>>> branch-a
```

If you paste just the inner merge conflict, VSCode properly identifies a merge conflict and provides the UI to resolve the conflict. However, for nested merge conflicts, it does not identify the merge conflicts, or does not provide a UI to resolve them.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
How do you get nested merge conflicts through a tool, not manually?

**Comment by Alexhuszagh** [comment]
@chrmarti You can get them (albeit rarely) using the standard git tool with rebases. If you are rebasing on a branch that has restructured a large section of code, and you have made small changes to that section, you can have an outer conflict with an inner conflict. I'll try to get a working example, I had one for a FOSS project I was making a PR for, but I should be able to create a minimal, verifiable, complete example.

**Comment by chrmarti** [comment]
@Alexhuszagh Did you find a reproducible case?
