### ISSUE TITLE
Resizing terminal creates additional lines

### ISSUE THREAD

**Issue by ihgsm** [Microsoft/vscode#37847]
- VSCode Version: Code - Insiders 1.18.0-insider (af39ef560060e7e8ba8d75983c9ec1da3f4d2a20, 2017-11-07T16:42:33.037Z)
- VSCode Version: Code 1.17.2
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
githistory|don|0.2.3
python|don|0.7.0
vscode-great-icons|emm|2.1.20
csharp|ms-|1.13.0
material-icon-theme|PKi|2.2.4
gitblame|wad|2.2.0

---

Steps to Reproduce:

1. Show integrated terminal
2. Click Move to Right to make it vertical
3. Now shrink the terminal by dragging the border of the terminal to the right
![capture](https://user-images.githubusercontent.com/22357476/32574075-eee02b28-c484-11e7-990e-4345f7fe5444.PNG)

Reproduces without extensions: Yes

**Comment by ihgsm** [comment]
Actually it happens with the horizontal terminal as well. Just few people will run into that in the horizontal layout.

**Comment by ihgsm** [comment]
And it happens with release build 1.17.2 as well.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26375
