### ISSUE TITLE
workbench.action.reopenClosedEditor should work with preview editors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#37849]
- VSCode Version: Code - Insiders 1.18.0-insider (098bb776d2e5fdf3cc9ea27a233754acf4309857, 2017-11-04T04:43:03.436Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.14
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
lorem-ipsum|Tyr|1.1.0

(1 theme extensions excluded)

---

Repro:

1. Single click a file in the explorer so it opens as a preview tab
2. ctrl+w to close editor
3. ctrl+shift+t to restore editor, the preview editor does not restore

**Comment by bpasero** [comment]
I guess the issue here is that I do not distinguish between a preview editor closing because of another editor opening at the same spot and the actual Ctrl+W interaction.

**Comment by sandy081** [comment]
@bpasero Looks like the reopened editor is no longer a preview editor. Is it intentional?

**Comment by bpasero** [comment]
I think thats fine given the explicit nature of this action.
