### ISSUE TITLE
JavaScript snippets changed to ES6 syntax

### ISSUE THREAD

**Issue by rnyberg** [Microsoft/vscode#37842]
- VSCode Version: 1.18.0-insider
- OS Version: Windows 10

1. Type `settimeout` in a JS file and hit enter for the first suggestion
2. Snippet `setTimeout(() => { }, timeout);` is created instead of `setTimeout(function () { }, timeout);` 

Reproduces without extensions: Yes

I'd imagine there was an opt-out setting to sneakily replacing all of the Vanilla JS snippets with ES6 syntax, as many of us still have to work with backwards compatible products and cant necessarily just slip in Babel to ease up transition. Seems like a bug/oversight to me.

**Comment by rnyberg** [comment]
There really should be some way to use the older snippets without creating them from scratch as an custom plugin.

**Comment by mjbvz** [comment]
This was an intentional change. See #35322

**Comment by mjbvz** [comment]
Closing as as-designed. Extensions and users snippets can be used to restore the old, es5 snippets
