### ISSUE TITLE
PowerShell terminal Clear-Host not working as expected

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#37848]
After dirtying up the PowerShell terminal with all types of output clear-host does not actually clear the host.  It scrolls the window to the top but leaves all the other text about it so it remains visible when manually scrolling up to it.  Can we get the Terminal Window to behave exactly like the native PowerShell terminal?

- VSCode Version: 1.17.2
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1.  Open Terminal to PowerShell
2.  Run anything to get text into the terminal
3.  Execute clear-host

Reproduces without extensions: not sure

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/30638
