### ISSUE TITLE
Add when context: editorGroupIndex

### ISSUE THREAD

**Issue by joshheyse** [Microsoft/vscode#37843]
It would be great if it where possible to use the editor group index/id in keybinding when clauses.

This would provide location context aware key commands for editorGroup/pane navigation.

Example
```
 { "key": "ctrl+h",             "command": "workbench.action.focusPreviousGroup" 
                                              "when": "editorGroupIndex != 0" },
 { "key": "ctrl+h",             "command": "workbench.files.action.focusFilesExplorer",
                                              "when": "editorGroupIndex == 0" },
```
In this case an editorGroupCount would probably also be necessary for determining if you are in the last editorGroup.

An alternative would be firstEditorGroup/lastEditorGroup, since I think most navigation rules would happen at the edges, and not in the middle of several open editor groups.

Is it possible to add where clauses in an extension, or would this functionality only be accessible after a vs code application change?

I would also be interested in submitting a PR for this, but not sure where to start in the code base.

**Comment by bpasero** [comment]
Let's fold this into https://github.com/Microsoft/vscode/issues/22755
