### ISSUE TITLE
Key binding Ctrl+Alt+L and AltGr+L are euqal but shouldn't

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#3784]
I installed the extension https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

I belive the extension is working correctly, however I see a problem with key binding.

In the "Default Keyboard Shortcuts" is like that:
``` JSON
{ "key": "ctrl+alt+l",            "command": "bookmarks.jumpToNext",
                                     "when": "editorTextFocus" },
```

According to extension docs `Ctrl+Alt+L` shuld be "jump to next" - this combination of keys is working as described.

However on my system (Windows10) the key combination: `AltGr+L` (right Alt + L and no Ctrl key) is also working for this task, and this is a problem.

`AltGr+L` on my keyboard reserved for a letter ` ł `, I can rebind the key combination used by extension but this indicate that in general there should be a difference between `CTRL+Alt` and `AltGr`.

**Comment by alexandrudima** [comment]
This is how Chromium handles keyboard input. At the JS level (where our code lives), there is no way to distinguish between `AltGr+L` and `Ctrl+Alt+L`.
