### ISSUE TITLE
ZenMode.hideTabs set to `false` still hiding tabs 

### ISSUE THREAD

**Issue by komali2** [Microsoft/vscode#37844]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.9.0-3-amd64
- Extensions: none
---

Steps to Reproduce:

1. In settings, set `    "zenMode.hideTabs": false,`
2. Try to open multiple tabs at once in the same pane, see that only one tab can be open per pane. 

Expected Behavior:

1. If `zenMode.hideTabs` is `false`, expect to be able to have multiple tabs open per pane. 

EDIT: Restarting vscode after changing the `zenMode.hideTabs` settings fixes the issue. Unsure if warrants looking into.

**Comment by isidorn** [comment]
@komali2 I can not reproduce this. Everything works fine for me even without a vscode restart.
Can you try reproducing with latest vscode insiders from here https://code.visualstudio.com/insiders/


Also make sure you do not have 	`"workbench.editor.showTabs": false` in your settings.
