### ISSUE TITLE
Debug variables string parser

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#37856]
- VSCode Version: 1.18
- OS Version: Fedora 27 Beta

Parse through text and to format/represent XML, JSON, and string literals.

Basically the same feature that Visual Studio for Windows has.

**Comment by weinand** [comment]
I do not understand the feature you are asking for.
Please explain and and give example.

**Comment by Trevinlc1997** [comment]
Sure thing. The feature I am requesting is the "Text visualizer" feature that Visual Studio currently has.

I've attached an picture example. (Top part is plain regular editors view, bottom is Visual Studios text visualizer)  

Parse through JSON, regular text, xml and format it like in the picture. 

Before: 
Get / HTTP/1.1\r\nHOST:www.google.com\r\n\r\n

After (Format and display it like this):
Get / HTTP/1.1
HOST:www.google.com

Hope this helps, I am not the best at explaining stuff.

**Comment by weinand** [comment]
@Trevinlc1997 thanks a lot. I understand now.
