### ISSUE TITLE
Switch workspace shortcut is conflict with add terminal [ctl+shirt+`]

### ISSUE THREAD

**Issue by coderkk** [Microsoft/vscode#37858]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|0.4.1
project-manager|ale|0.23.0
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
EditorConfig|Edi|0.11.1
json-tools|eri|1.0.2
git-project-manager|fel|1.4.0
terminal|for|0.0.10
minify|Hoo|0.3.0
rest-client|hum|0.16.0
classic-asp|ili|0.0.2
json-escaper|jos|1.0.1
format-indent|Kas|1.3.0
net-core-project-manager|ksu|0.3.6
git-indicators|lam|1.2.3
vscode-todo-parser|min|1.9.1
csharp|ms-|1.13.0
node-debug2|ms-|1.18.5
PowerShell|ms-|1.5.0
debugger-for-edge|msj|0.4.1
material-icon-theme|PKi|2.2.4
todotasks|san|0.5.0
code-spell-checker|str|1.4.12
spellchecker|swy|1.2.13
cordova-tools|vsm|1.3.0
vscode-react-native|vsm|0.5.2

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open a folder
2. Add folder to workspace
3. Press 'New terminal' in Integrated Terminal or [ctl+shirt+`]
4. Editor will open 'Switch workspace....' instead of New Terminal

Reproduces without extensions: Yes/No: No

**Comment by jtanx** [comment]
It actually looks like workbench.action.terminal.new is broken - even if you bind that to another shortcut, it still pops up with ' select workspace folder' instead of opening a new terminal.

**Comment by jtanx** [comment]
Oh right, it's asking which workspace you want to open the terminal in. Derp

Not very intuitive. It would be nice if it you could preference it to default to a workspace, instead of having to select every time.

**Comment by coderkk** [comment]
Yes. Better use the default like the previous one. Maybe can use another shortcut or button to allow use select the workspace before open terminal.

**Comment by Tyriar** [comment]
@jtanx I originally thought that it wasn't intuitive but after trying to use the old way (open in "active" workspace) for a while I found that it was hard to keep track of where the terminal was being opened.

**Comment by jtanx** [comment]
@Tyriar In terms of intuitiveness, I was referring to the selector itself. Having just started to use multi-root workspaces, it wasn't immediately clear what the "Select workspace folder" was trying to do; if it had said something like "Select workspace to associate terminal with" (or some better context), it would have been clearer.

But having mentioned it, in terms of opening in the active workspace, what's not intuitive about that? From my thinking, it should open based on the workspace of the currently edited document. Can we at least consider a preference for this? Having to disambiguate *each and every time* I want to open a terminal is annoying.

e.g. I think I can achieve what I want via the extension interface (but this is better suited as a preference) via:

```js
vscode.window.createTerminal().show()
```

**Comment by Tyriar** [comment]
> it wasn't immediately clear what the "Select workspace folder" was trying to do; if it had said something like "Select workspace to associate terminal with" (or some better context), it would have been clearer.

👍 

> Can we at least consider a preference for this?

I'll add another command for this so you can replace the keybinding to the get desired behavior without an extension.

**Comment by Tyriar** [comment]
@jtanx in the next version there will be a `workbench.action.terminal.newInActiveWorkspace` command with the behavior you're after. Add this to get the old behavior:

```js
{ "key": "ctrl+shift+`",    "command": "workbench.action.terminal.newInActiveWorkspace" }
```

**Comment by Tyriar** [comment]
@coderkk @jtanx thanks for the suggestions 😃 

<img width="513" alt="screen shot 2017-12-18 at 8 32 07 am" src="https://user-images.githubusercontent.com/2193314/34116634-0ce8a6d2-e3ce-11e7-935c-7d2dd5c696df.png">

**Comment by jtanx** [comment]
@Tyriar thank you! Awesome work :)
