### ISSUE TITLE
Built-In Terminal Failing to Launch

### ISSUE THREAD

**Issue by bsloan334** [Microsoft/vscode#37854]
- VSCode Version: 1.17.2
- OS Version:  MacOS High Sierra 10.13

Steps to Reproduce:

1. Use "Control + `" to open terminal, then I get the error "The terminal process command `/usr/local/bin/my_shell -l` failed to launch (exit code: 1)"

No idea how to fix it

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
This means that your `$SHELL` environment variable is set to `/usr/local/bin/my_shell` which doesn't exist. You can either set `$SHELL` to the correct value or set the `terminal.integrated.shell.osx` setting.
