### ISSUE TITLE
My Terminal is redundancy space each character.

### ISSUE THREAD

**Issue by npthinh1996** [Microsoft/vscode#37855]
For example, "m y c o m p u t e r @  a d m i n". Please help me!

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.10.0-38-generic

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681
