### ISSUE TITLE
Javascript keywords broken

### ISSUE THREAD

**Issue by loctrice** [Microsoft/vscode#3785]
"function" and "var" don't seem to be keywords in javascript now after the update. (0.10.10 FEB 2016)

**Comment by AlexChesser** [comment]
+1

**Comment by Tyriar** [comment]
This is likely because you're on the (Visual Studio) version of the theme, try changing the theme to the new defaults Light+ or Dark+ (or another theme):

- <kbd>F1</kbd>
- Type "theme"
- <kbd>enter</kbd>
- Select another theme

Reopen this issue if that doesn't fix your issue.
