### ISSUE TITLE
API for triggering a `workbench.action.quickOpen`-like quickpick

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#37852]
I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-diff) that diffs the current file with another one. For picking that other file I'm opening a quickpick with the result of `await vscode.workspace.findFiles ( '**/*' )`, basically a custom `quickOpen` action, that looks like this:

<img width="573" alt="screen shot 2017-11-08 at 23 14 04" src="https://user-images.githubusercontent.com/1812093/32577765-49be20bc-c4db-11e7-8e54-ff954ff5abba.png">

But there's already a proper `quickOpen` quickpick:

<img width="575" alt="screen shot 2017-11-08 at 23 14 17" src="https://user-images.githubusercontent.com/1812093/32577792-5d3df34c-c4db-11e7-97a1-0e7df8df2d34.png">

Why not adding an API for using it? (The selected file would simply get returned by the API instead)

**Comment by bpasero** [comment]
Maybe this could be done in a similar way as we now have it for `TreeItem` where you can specify an optional `resourceUri` property that will then take care of the icon (`QuickPickItem.resourceUri`).

@fabiospampinato to clarify, you talk about the icon right, nothing else?

**Comment by nealot** [comment]
Any update on this yet?

**Comment by chrmarti** [comment]
Icons are tracked in #16445. Groups (like Recent Files) are tracked in #11468.

Using this issue to track the request for a specialized API.

**Comment by jrieken** [comment]
Could also be a special API like:

https://github.com/Microsoft/vscode/blob/248aa630395a861582bd10c9593477d97970f678/src/vs/vscode.d.ts#L6160-L6167
