### ISSUE TITLE
Diffing a text file against a binary file breaks the text file's editor

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#37853]
![2017-11-08 23_54_22](https://user-images.githubusercontent.com/1812093/32579179-4553c310-c4e0-11e7-8cc5-682acccd675f.gif)

Why one would diff a text file against a binary file I don't know, I did it by mistake, but since the `code --diff ./text ./binary` call doesn't throw any error I don't expect it to be so brittle that stuff break.

**Comment by bpasero** [comment]
Yeah, this is a consequence of us sharing all editor inputs and the binary diff editor calling [`setForceOpenAsBinary`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/editors/fileEditorInput.ts#L113).
