### ISSUE TITLE
poor syntax highlighting for javascript/react files

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#3786]
Code looks like a plain text file, until it parses the `<>` jsx tags. Atom has way more visual information about the syntax. Is there anything missing? Is this a bug?

![2016-03-07 18_51_50-changepasswordcontainer jsx - cis-v2-frontend - visual studio code](https://cloud.githubusercontent.com/assets/941075/13584565/f6a13a9e-e495-11e5-837d-ceb85a051c7b.png)
![2016-03-07 18_53_16-changepasswordcontainer jsx c__git_rr_cis-v2-frontend atom](https://cloud.githubusercontent.com/assets/941075/13584566/f6a3fc70-e495-11e5-93f3-4f19603c8a8d.png)

**Comment by aeschli** [comment]
@luisrudge Can you paste the code sample so I can investigate?

**Comment by kumarharsh** [comment]
vscode is not highlighting object properties, objects (when their sub-properties are accessed), etc among other things, JSX tags, etc. JS looks like plaintext with some colour here and there.

![screenshot 78](https://cloud.githubusercontent.com/assets/760112/13601556/f5f02580-e556-11e5-80f7-a9c6de899e90.png)

Code Sample:

```js
export default class BaseRule extends React.Component {
  static propTypes = {
    gStyles: React.PropTypes.object.isRequired,
    value: React.PropTypes.shape({
      operator: React.PropTypes.string,
      value: React.PropTypes.oneOfType([
        React.PropTypes.string,
        React.PropTypes.number,
      ]),
      timePeriod: TimePeriodPropType,
    }).isRequired,
    label: React.PropTypes.any, // can be hidden by passing null/false
    onChange: React.PropTypes.func.isRequired,
    ruleType: React.PropTypes.oneOf(_values(RuleType)),
    onRuleTypeChange: React.PropTypes.func.isRequired,
  };

  renderTimePeriodInput() {
    const styles = this.props.gStyles;
    return (
      <TimePeriodInput
        value={this.props.value.timePeriod}
        onChange={this._handleChange('timePeriod')}
        prepend={<FormattedMessage {...intlStrings.timePeriodInputPreposition}/>}
        style={styles.timePeriodWrapper}
      />
    );
  }
}
```

**Comment by luisrudge** [comment]
here's the code:

```js
import React from 'react';
import {connect} from 'react-redux';

import {Blade} from 'c/shared/blade/';
import ChangePassword from 'c/profile/ChangePassword';

const mapStateToProps = s => ({
  ...s.changePassword
});

@connect(mapStateToProps)
export default class ChangePasswordContainer extends React.Component {
  render() {
    return (
      <Blade
        title="Change Password"
        closeUrlPath="/profile"
        lockToggle
        style={{width: 400}}
        >
        <ChangePassword {...this.props} />
      </Blade>
    );
  };
}
```

**Comment by kinolaev** [comment]
in addition:
1) argument destructuring
2) different jsx highlight in function declarations and arrow functions
3) all grey except statements inside jsx expressions
vscode@master 20160315, typescript@next 20160315
![highlight](https://cloud.githubusercontent.com/assets/1247759/13791969/a50833e2-eb00-11e5-9949-57f39c0028a2.png)

**Comment by aeschli** [comment]
#3008 is the underlying issue for this
