### ISSUE TITLE
I can not view tabbars when open multiple windows. (MACOS 10.13.1)

### ISSUE THREAD

**Issue by linhho** [Microsoft/vscode#37868]
I can not view tabbars when open multiple windows. (MACOS 10.13.1)
<img width="983" alt="screen shot 2017-11-09 at 11 11 03 am" src="https://user-images.githubusercontent.com/13704769/32588059-cc657c96-c53e-11e7-987e-92262f3198dd.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35361
