### ISSUE TITLE
when change terminal size character vestigital

### ISSUE THREAD

**Issue by Eurkidu** [Microsoft/vscode#37864]
- VSCode Version: 1.18.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. change terminal to side
2. move divide line

![terminal](https://user-images.githubusercontent.com/13271070/32586612-973cbbce-c53e-11e7-8325-fcc6f9ebb02d.gif)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/30429
