### ISSUE TITLE
扩展程序一直报这个错

### ISSUE THREAD

**Issue by amagiAmagi** [Microsoft/vscode#37865]
![image](https://user-images.githubusercontent.com/30867702/32586973-dca0642a-c540-11e7-8ce2-4b62fbf3560f.png)
求解决！！！！！急急急

**Comment by mjbvz** [comment]
Duplicate of #34385

**Comment by amagiAmagi** [comment]
So what should I do?

**Comment by xrmzju** [comment]
so what should i do

**Comment by mjbvz** [comment]
Please follow #34385
