### ISSUE TITLE
Allow to rename readonly file in explorer bar

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode#37866]
- VSCode Version: Code - Insiders 1.18.0-insider (af39ef560060e7e8ba8d75983c9ec1da3f4d2a20, 2017-11-07T16:42:33.037Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.1
tslint|eg2|1.0.14
flatbuffers|gab|0.1.0
azure-account|ms-|0.1.3
debugger-for-chrome|msj|3.5.0
peep|nwa|0.0.5
vscode-docker|Pet|0.0.21
perforce|sle|2.2.2

---

Steps to Reproduce:

1. open a readonly file
2. select file in explorer bar
3. F2 to rename file.  give it a new name

results: 
[Error] A system error occurred (EPERM: operation not permitted, open '&lt;filename&gt;') Retry | Cancel

file remains in explorer bar
file remains open in window
clicking explorer bar old filename updates editor with (deleted on disk)
ctrl-p and new filename will open the new filename, and update the explorer bar to remove the old file (but leaves the editor with (deleted on disk) file open)
right click -> create new file in same directory does not update the old / new file. (but does show the new right click file)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@vrachels does this happen for all files?

**Comment by vrachels** [comment]
ah, some followup research found a key element:
to reproduce, the file to be renamed needs the readonly attribute (which does not prevent renaming)
updated STR.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
