### ISSUE TITLE
Terminal doesn't work well with shell command clear.

### ISSUE THREAD

**Issue by fenying** [Microsoft/vscode#37862]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
githistory|don|0.2.3
vscode-generate-getter-setter|DSK|0.4.2
gitlens|eam|5.7.1
tslint|eg2|1.0.14
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
minify|Hoo|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.67
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
vscode-code-outline|pat|0.0.12
vscode-sql-beautify|sen|0.0.4

---

Steps to Reproduce:

1. Open terminal insides VSCode
2. Execute any shell command such as `ls`
3. Execute shell command `clear`

**Now You can see that the cursor would be reset, without cleaning screen!**

![terminal-display](https://user-images.githubusercontent.com/11142903/32585902-ab15f8c6-c53a-11e7-9456-d45d38b544c5.png)
![terminal-display-2](https://user-images.githubusercontent.com/11142903/32586013-57f4789c-c53b-11e7-9bf2-460762dbefdb.png)

Reproduces without extensions: Yes

**Comment by saintplay** [comment]
I don't know if this issue is duplicated, but for me it's an error from the last update

**Comment by fenying** [comment]
It seems fixed in v1.18.1.
