### ISSUE TITLE
[html] auto indentation is different if the closing tag is followed by any character or whitespace.

### ISSUE THREAD

**Issue by digitalsms** [Microsoft/vscode#37869]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.13.0-16-generic (also tested on Windows 10 x64).
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.13
vsc-material-theme|Equ|1.1.1
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.4
code-settings-sync|Sha|2.8.5
atom-keybindings|ms-|3.0.2
color-highlight|nau|2.3.0
stylelint|shi|0.30.0
ayu|tea|0.8.0
highlight-matching-tag|vin|0.4.4

(5 theme extensions excluded)

---

I ran into this bug after configuring emmet to include a comment on the same line immediately after closing tags, such as when expanding something like ".example" (using $1 to represent the cursor position):

`<div class="example">$1</div><!-- .example -->`

And then normally you'd hit enter and continue on, but in this case it gives the following:

```
<div class="example">
    $1</div><!-- .example -->
```

Instead the expected outcome of:

```
<div class="example">
    $1
</div><!-- .example -->
```

After trying out a few other scenarios, it turns out the formatting will break in _any_ situation where a closing tag has _any_ characters after it whatsoever. Even a single trailing space after a `<div></div> ` will cause it to format/indent incorrectly - and not just while manually editing after expanding an abbreviation, but also when using the built-in Format Document function.

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
Verified that this works as described. However, it's also limited to this situation only as soon as there is anything `<div>`here`</div>` the onEnter rule does not catch it.
