### ISSUE TITLE
Report "spawn UNKNOWN" when global searching

### ISSUE THREAD

**Issue by tammyrobinson03** [Microsoft/vscode#37863]
- VSCode Version: 1.18.0
- OS Version: Win7 32bits

Steps to Reproduce:

1. upgrade to the latest version 1.18.0
2. open any existing project then carry out one global search.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
- Where do you see that message?
- Can you try reinstalling?
- Does this file exist? `C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-ripgrep\bin\rg.exe`

**Comment by tammyrobinson03** [comment]
i got this error msg in the search panel just after i upgraded it to the latest 1.18.0. it used to work fine on my side before upgrading.
i have tried running without any extension, still not ok.
i also reinstalled it. but not solved.
For the rg.exe, i am not sure, since i have downgraded to version 1.17.2. but i can try it later.

**Comment by roblourens** [comment]
Please check later if you get a chance. It works for me...

**Comment by Ani-kun** [comment]
Use dumpbin to rg.exe, target is "Unknown".
```
FILE HEADER VALUES
            8664 machine (Unknown)
```

**Comment by LeThiHyVong** [comment]
#https://github.com/Microsoft/vscode/issues/37872

**Comment by tammyrobinson03** [comment]
i replace the rg.exe of version 1.18.0 with that from version 1.17.2. it works.

**Comment by roblourens** [comment]
Did you run dumpbin with some flag? I see, `File Type: EXECUTABLE IMAGE`, then a summary section with correct-looking values.

**Comment by roblourens** [comment]
@Ani-kun, what OS? Also 32-bit win7?

**Comment by LeThiHyVong** [comment]
@roblourens I ran dumpbin with /HEADERS parameter and it displayed similar value. 
[dumpbin.txt](https://github.com/Microsoft/vscode/files/1456490/dumpbin.txt)
I replace rg.exe from [https://github.com/BurntSushi/ripgrep/releases](url) and now it works.

**Comment by roblourens** [comment]
@LeThiHyVong are you using the 32 bit version as well? What OS?

**Comment by satawait** [comment]
I'm using 32-bit win7 version 1.18.0 and got the same error.

**Comment by Ani-kun** [comment]
@roblourens  Win7 32bit. Dumpbin with /HEADERS

**Comment by roblourens** [comment]
There's clearly an issue with the 32-bit rg.exe on 32-bit Win7. Will have to find a 32 bit VM tomorrow to try it.

As a workaround, it sounds like it will probably work to download https://github.com/roblourens/ripgrep/releases/download/0.5.1-patch.1/ripgrep-0.5.1-patch.1-win32-ia32.zip and copy it in place of the bad rg.exe (`.../resources/app/node_modules/vscode-ripgrep/bin/rg.exe`)

**Comment by roblourens** [comment]
We are simply publishing the 64-bit version of ripgrep with the 32-bit build, which is only an issue on an actual 32-bit OS. Will be fixed in next Insiders/update.

**Comment by wodin** [comment]
FYI - https://www.virustotal.com/#/file-analysis/MjU0ZDUwM2U1M2Q0YTk5Mjc2MGE3NTViNzEzZjRlODU6MTUxMDU2MTMyOQ==

**Comment by russgove** [comment]
Hi, is  a fix available for this?

**Comment by wasimakram-mulla** [comment]
For all those, who is facing the same issue kindly download the file sent by @roblourens mentioned above this has resolved my problem.
Thanks guys

**Comment by roblourens** [comment]
It should also be fixed in the current insiders build.
