### ISSUE TITLE
new terminal display bad

### ISSUE THREAD

**Issue by miao17game** [Microsoft/vscode#37861]
- VSCode Version:1.18.0
- OS Version:

Steps to Reproduce:

1. set settings "workbench.sideBar.location" to value "right"
2. open the console terminal
3. the bug appears : the bottom of sideBar is blocked

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
What do you mean with `the bottom of sideBar is blocked`?

**Comment by miao17game** [comment]
@maxibanki the side bar will be obscured by the console terminal bar. you'll see that when you try my steps. The windows version, i'm not sure it's the same on linux or mac.

**Comment by fabiospampinato** [comment]
@miao17game can you post a screenshot?

**Comment by miao17game** [comment]
@fabiospampinato 
<img width="419" alt="captur2e" src="https://user-images.githubusercontent.com/17511048/32609877-0bdf592a-c59c-11e7-9876-033b3dcb33a2.PNG">

**Comment by Tyriar** [comment]
I can't seem to reproduce, this might be fixed already?

**Comment by isidorn** [comment]
@miao17game please try reproducing with latest vscode inisders from here https://code.visualstudio.com/insiders/

Thanks!
