### ISSUE TITLE
Auto-import named export from default exported

### ISSUE THREAD

**Issue by janhartmann** [Microsoft/vscode#37874]
- VSCode Version: 1.18.0-insider
- OS Version: MacOS High Sierra 

Steps to Reproduce:

1. Create a file with a default export
2. Create another file where the default exported is exported as a named export
3. Try to import it

Reproduces without extensions: Yes

Thank you for this auto-import feature in JavaScript! This is something I have been awaiting for a long time! I am not sure of the limitations of this, but I have trouble auto-importing `default export`'s from an index.js file.

Take for example:

```js
// File: ProfilePhoto.js
import React from "react";
import PropTypes from "prop-types";
import injectSheet from "react-jss";

const ProfilePhoto = ({ classes, picture }) => {
    return <img src={"data:image/jpeg;base64," + picture} className={classes.photo} />
};

const styles = () => ({
    photo: {
       // Styling
    }
});

export default injectSheet(styles)(ProfilePhoto); // injects the classes argument



// File: index.js
export { default as ProfilePhoto } from "./ProfilePhoto";

```

What I am doing here is that I am using an higher order component to wrap the function and use that as the default export. But this will never be picked up from the auto-import suggestions?

Is this a limitation or is something which can be integrated in VSCode?

**Comment by zfeher** [comment]
Also want to thank you for the new auto import feature. It would be nice if you can make it work with default exports as well in the future. Here are some suggestions:

We have many default exports in the following forms
```JavaScript
// some-func/index.js
const someFunc = () => { ... }
export default someFunc

// other-func/index.js
export default function() { ... }

// other-func-with-name.js
export default function otherFuncWithName () { ... }
```

So sometimes a default name for the exported default function can be aquired from the module (this could be an extra bonus feature). 

However in general cases the module name (folder-name, folderName, FolderName) or the filename can be used (converted camelCase/PascalCase version if name is kebab-case) as a default name for auto import. So if I type `someFunction`, `SomeFunction` or `some-function` it could find the module to import. Plus it could show us an extra option like `import as` which could ask for a name.

Maybe the whole auto import could be improved later via using (fuzzy) search so we could narrow the results eg typing: `utils/feature/some-func`, `u/f/sf`, etc ... which eventually will be replaced with the found import if accepted.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19877
