### ISSUE TITLE
logo is hard to find in desktop

### ISSUE THREAD

**Issue by aifang** [Microsoft/vscode#37871]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
![5 0ou jy29o v6 55o9xu9h](https://user-images.githubusercontent.com/7665212/32588707-86d684b0-c54b-11e7-94b3-7bf212b3148b.png)

please go back to  first time I see it

**Comment by bpasero** [comment]
Currently we do not plan to change the logo.
