### ISSUE TITLE
command 'git.commit' not found

### ISSUE THREAD

**Issue by ysfscream** [Microsoft/vscode#37875]
- VSCode Version:1.18.0-insider (1.18.0-insider)
- OS Version:10.12.6

Steps to Reproduce:

git can' t work !
![image](https://user-images.githubusercontent.com/21299158/32589604-124d5238-c4db-11e7-962a-8b3d98148ec9.png)

**Comment by shivammittal99** [comment]
For me it shows the same command not found error message for any git command

VSCode Version: 1.18.0 (Stable)
OS Version: Ubuntu 16.04.3 LTS

**Comment by joaomoreno** [comment]
@ysfscream  Please provide steps. I don't understand why you mention `git.commit` not found when the screenshot says `git.openChange`.

@shivammittal99 If an issue is similar to yours but not exactly the same, then it's not the same. Please create a separate issue.

**Comment by ysfscream** [comment]
@joaomoreno Sorry for my mistake. I mean, the source code management in my VsCode can't work

**Comment by joaomoreno** [comment]
@ysfscream Please provide **steps**.

Like this:

1.  Open a workspace with changes
2. Open the SCM view
3. Click on a change

**Comment by isgallagher** [comment]
@joaomoreno I'm having the same issues.

![vs code git commit error](https://user-images.githubusercontent.com/25665920/33102489-447a7f66-ceda-11e7-8086-416ca37d760b.png)

**Comment by joaomoreno** [comment]
@isgallagher Please try with the latest Insider release. If Git is installed in a special path, please configure it in VS Code using the `git.path` configuration setting.

**Comment by isgallagher** [comment]
@joaomoreno Latest insider release is working.  Maybe my issue was I was using path to "git-cmd.exe" instead of "git.exe" prior.  Either way, thanks for the help!
