### ISSUE TITLE
Provide workbench.panel.location "left"/"top" option

### ISSUE THREAD

**Issue by 1217950746** [microsoft/vscode#37877]
<img width="1352" alt="img" src="https://user-images.githubusercontent.com/7909582/32589784-86f18106-c551-11e7-9857-aa2d8e6ad037.png">

**Comment by fabiospampinato** [comment]
I guess it makes sense if one's used to a Right-to-Left language.

And also having sidebar and panels both at the right side doesn't look right:

<img width="1440" alt="screen shot 2017-11-09 at 14 59 40" src="https://user-images.githubusercontent.com/1812093/32609081-b21e33a8-c55e-11e7-8d4b-00ae2eda3c11.png">

**Comment by shadedesignz** [comment]
This would be a great feature

+1

**Comment by briandipalma** [comment]
This is a great feature for large screens. Terminals take up more space so push the editor to a more central position, while the explorer is usually too small to center the editor.

**Comment by jacob-j** [comment]
Any progress on this feature? :)

**Comment by Tehnix** [comment]
If someone wants to take a stab at a PR for this, the code that added the support for vertical on the right was this one https://github.com/Microsoft/vscode/pull/36827.

I too would highly like this, as I always have the file tree on the right side.

**Comment by abautistah** [comment]
So is this happening? I have to turn my neck way to the left to be able to see my editor. Would be very useful to have that window on the right side and the terminal on the left!

**Comment by ted98** [comment]
Is This issue working?

**Comment by dciesielkiewicz** [comment]
At least move to left option will be very useful.

**Comment by gurmitsg** [comment]
> Is This issue working? This feature seems very useful.

Especially useful with 49 inch monitors price going down.

**Comment by zapateo** [comment]
This would be really useful.

**Comment by uday0408** [comment]
I came here looking for a way to move terminal to left position in VSCode. When can we expect this? The request has been open for an year already.

**Comment by sultanmyrza** [comment]
Please let us set "workbench.panel.location:top" right now we can only set to left and bottom
I really need a panel to be on top anyone else need panel on top?

**Comment by willin** [comment]
i need `top` option for vertical screen

**Comment by bpasero** [comment]
I reopened https://github.com/microsoft/vscode/issues/50984 to cover the feature request to put the panel to the top. Please cast your vote there.

**Comment by bilogic** [comment]
@bpasero can't seem to cast a vote on #50984, it is locked to collaborators only.

**Comment by bpasero** [comment]
Ah yeah, sorry for that. Unlocked it now.

**Comment by isidorn** [comment]
Verifier: make sure that 
* F1 > view: move panel left -> moves the panel to the left
* setting workbench.panel.defaultLocation: left gets respected for each new window

**Comment by kristajg** [comment]
The issue @bpasero mentioned only includes the top option. If we are looking for the left option as well should we vote here?

**Comment by bilogic** [comment]
Pardon me, but it sounds exhausting to have to vote for each of the 4 sides.. Almost like having a car that can only turn left until the drivers complain about not being able to turn right.
