### ISSUE TITLE
SCM: Support workspace-widget "Show {Next, Previous} Change"

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#37870]
The new inline change viewer is great, but it seems like a huge missed opportunity for "Show Next Change" and "Show Previous Change" to only work within the current file, not the workspace. Or at least they could be augmented with a pair of commands that work across the workspace. (Is there any reason that these actions don't have an `editor.action.<command>` name, by the way?)

I've also always wanted this for "Go to {Next, Previous} Error or Warning" (`editor.action.marker.{next, prev}`), which I use extensively.

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/104768
