### ISSUE TITLE
About the translation of "Extract to" in Chinese

### ISSUE THREAD

**Issue by snowwindsand** [Microsoft/vscode#37879]
- VSCode Version: V1.18
- OS Version: Windows7 X64

Steps to Reproduce:

1. use the "extract" function.
2.if should be "提取" instead of "解压缩"

Reproduces without extensions: Yes/No

**Comment by johnliu2016** [comment]
Hi @snowwindsand, thank you for reporting this loc issue, could you kindly provide a screenshot of the translation problem, it will help locate the resource string in translation files?

**Comment by Joelism** [comment]
@johnliu2016 It seems to be a TypeScript issue
https://github.com/Microsoft/TypeScript/blob/master/src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl#L3187

**Comment by johnliu2016** [comment]
Tracking on Typescript side.
