### ISSUE TITLE
CSS Suggestion Improvment 

### ISSUE THREAD

**Issue by rajnishcoder** [Microsoft/vscode#37887]
- VSCode Version:1.17.2
- OS Version: Fedora 26

Steps to Reproduce:

1. Assume I'm writing code in CSS and I'm using width for every class and whenever i typed "wi" It has to show me "width" property first in suggestion instead of "windows" property.
Because it is irritating to type "wi" and select from #3 in suggestion list.
2. It should be in every language. 

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
duplicate of #22839
