### ISSUE TITLE
Auto imports import error module name with cnpm.

### ISSUE THREAD

**Issue by Lxxyx** [Microsoft/vscode#37882]
cnpm: npm client for China mirror of npm.

Github: https://github.com/cnpm/cnpm

- VSCode Version: 1.18

Steps to Reproduce:

1. download this repo: https://github.com/Lxxyx/auto-imports-cnpm
2. install cnpm by: `npm i cnpm -g`
3. use `cnpm i` to install dependencies.
4. in index.js
![image](https://user-images.githubusercontent.com/13161470/32590887-5f90334c-c4e2-11e7-80f3-05c767076632.png)
5. but in text.js when I type render:
![image](https://user-images.githubusercontent.com/13161470/32590929-918557ce-c4e2-11e7-8df5-38673fcbd272.png)

And I Get: `import { render } from "_rax@0.4.20@rax";`

6.  The directory structrue in cnpm installed node_modules:

![image](https://user-images.githubusercontent.com/13161470/32590969-c02931ae-c4e2-11e7-828c-bc5c0f482595.png)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19893
