### ISSUE TITLE
Cannot show color in integrated-terminal

### ISSUE THREAD

**Issue by g-plane** [Microsoft/vscode#37884]
- VSCode Version: 1.18
- OS Version: Win10

Steps to Reproduce:
Open the integrated-terminal, then execute a command which will output some colored text in terminal.
Like this:
![image](https://user-images.githubusercontent.com/17216317/32591299-8192a994-c559-11e7-8859-8e126ae636f9.png)
The output text `Test created successfully.` should be in green color and the ANSI characters which are used to control the color should be hidden.

Reproduces without extensions: No

**Comment by Tyriar** [comment]
What happens when you run the same thing in a powershell.exe window?

**Comment by g-plane** [comment]
Also not worked.
![image](https://user-images.githubusercontent.com/17216317/34066473-18ce93ce-e24a-11e7-92b1-feaa3eac2595.png)

It works on Cmder.
![image](https://user-images.githubusercontent.com/17216317/34066497-7fbd37e8-e24a-11e7-9901-ece4e810dd2c.png)

**Comment by Tyriar** [comment]
@rprichard do you expect the colors to not work in winpty/PS even though cmder seems fine?

**Comment by rprichard** [comment]
Yes, winpty matches what an ordinary console window does.
