### ISSUE TITLE
Adding multiple folders to workspace on Code 1.18.0, the Workspace in File Explore is always empty

### ISSUE THREAD

**Issue by dueseven** [Microsoft/vscode#37881]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. No mater the folders were added by menu item "Add Folder to Workspace", drag and drop, command line with "--add directories", the Workspace in the File Explore is always empty, as shown in the following figure.

![2017-11-09 14-01-25](https://user-images.githubusercontent.com/7934570/32590707-9ca23036-c556-11e7-9a2a-5fd5962ede61.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@dueseven 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by dueseven** [comment]
@bpasero 

Thanks for the reply. Here are the logs generated by `code --disable-extensions --verbose` and the logs observed in Developer Console.

[vscode.log](https://github.com/Microsoft/vscode/files/1456541/vscode.log)
[console.log](https://github.com/Microsoft/vscode/files/1456542/console.log)

**Comment by dueseven** [comment]
@bpasero 

Sorry for the false alarm. I just remove all my custom settings. The multi-root function works well.

**Comment by bpasero** [comment]
@dueseven would be interesting to know what kind of setting you had that would show this issue. Can you share them?

**Comment by dueseven** [comment]
@bpasero 

I had a files.exclude setting rule used to block all hidden files showing in the file explore tree. As shown in the following list, I commented this rule out, the multi-root tree works fine now.

`
    "files.exclude": {
        "**/.repo": true,
        "**/.vscode": true,
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.o": true,
        "**/*.ko": true,
        "**/*.so": true
        // "**/.*": true
    }
`

**Comment by isidorn** [comment]
@dueseven thanks, sounds like a duplicate of #37899
