### ISSUE TITLE
Please remove gnome dependencies such as gconf and gvfs.

### ISSUE THREAD

**Issue by enihcam** [Microsoft/vscode#37886]
- VSCode Version: 1.18
- OS Version: Archlinux

Steps to Reproduce:
gconf or gvfs are gnome specific and heavy, and gconf setting entries are hard to clean after package removal. Please just remove gnome dependencies, for people who just want to use lightweight desktop environment, e.g. openbox/LXDE/etc..

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
I'm not sure where we list these dependencies... but afaik we don't have an official Arch package.

**Comment by agauniyal** [comment]
Can you collaborate with them? This is the AUR package - https://aur.archlinux.org/packages/visual-studio-code/

**Comment by dcelasun** [comment]
I'm the maintainer of the Arch package. This is a packaging concern and this issue shouldn't have been opened here. We can close this.
