### ISSUE TITLE
This XHR failed: this error is reported, the solution ~!!!!

### ISSUE THREAD

**Issue by amagiAmagi** [Microsoft/vscode#37885]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by amagiAmagi** [comment]
Very anxious, please help me to solve, thank you

**Comment by maxibanki** [comment]
Please provide us more information and use the `Report Issues` function from VS Code directly, so we can see more information about you system like the installed extensions. And give us more details when and how the error occurs.
