### ISSUE TITLE
Zombie breakpoints when editing lines around a breakpoint

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#37880]
insiders 

![image](https://user-images.githubusercontent.com/1487073/32590160-c3235f34-c4cd-11e7-82d4-0cdaf381dee5.png)

node version 8.9.0

see how there are a number of breakpoints in the gutter, but none in the breakpoints list:

![image](https://user-images.githubusercontent.com/1487073/32590139-977be054-c4cd-11e7-85b2-51f52827423b.png)

When i click in the gutter the red circles are not removed. Sometimes multiple or all breakpoints are removed when i click on a single line with a breakpoint set.

**Comment by chrisdias** [comment]
if i reload the window, all of these stray breakpoints are cleaned up.

**Comment by laimonas** [comment]
Same issue in 1.18 stable

**Comment by isidorn** [comment]
@chrisdias as always reproducable steps would be great. Can you also reproduce with the current stable
@laimonas same as chris, can you please provide reproducable steps

**Comment by weinand** [comment]
Breakpoints are based on editor decorations and decorations have changed in VS Code 1.18. So this might be a regression. 

/cc @alexandrudima

**Comment by weinand** [comment]
@chrisdias @laimonas if you can easily reproduce this problem, please verify that this occurs even if all extensions are disabled.

**Comment by laimonas** [comment]
I have php extensions.
First i run code with extensions, added some breakpoints.
Disabled all extensions, restarted code.
Attaching gif with actions
![tinytake-by-mangoapps-09-11-2017-11-39-08](https://user-images.githubusercontent.com/870178/32598899-8bb61f16-c543-11e7-918c-c3d0f4dde209.gif)

**Comment by isidorn** [comment]
@laimonas thanks for coming back on such short notice. Here are the reproducable steps (both for stable and insiders):

1. Add breakpoint on a line
2. Delete line before that line -> notice the breakpoint growing to the following line

This can lead to zombie breakpoints -> candidate

**Comment by isidorn** [comment]
I have cherry picked the fix on top of the release/1.18 branch.
@weinand can you please verify once the build is out of the oven next week?
