### ISSUE TITLE
每次打开老文档时，总是默认以utf8格式打开，导致文本乱码。如果可以的话，打开文档的默认编码改为默认猜测形式

### ISSUE THREAD

**Issue by fawdlstty** [Microsoft/vscode#37890]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by sumbrez** [comment]
你可以把设置项`files.autoGuessEncoding`改为`true`，这样就会默认猜测编码。
另外对于某种语言（至少win下是根据文件扩展名判断的），你可以设置打开这种语言的文件时使用某种编码，而不是全局默认的编码（例如#19890）。

**Comment by bpasero** [comment]
Please report issues in english. Thanks!
