### ISSUE TITLE
Don't show recommendation badge for already installed extension

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#37898]
I just don't see the point to show this badge if you have the extension installed and running.

![screenshot 17](https://user-images.githubusercontent.com/9638156/32595606-93263436-c541-11e7-9f29-28fb7249f672.png)

Not sure about disabled extensions, but I'd rather not see the badge for them too.

**Comment by innerlee** [comment]
It is equally odd if the extension loses badge once you install it :D

**Comment by ramya-rao-a** [comment]
Let's track this in #40881
Please add your thoughts there
