### ISSUE TITLE
multi-root folders: excluding dot files from a folder makes it invisible in file explorer

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/vscode#37899]
- VSCode Version: 1.18
- OS Version: linux mint 18.2, (also verified on a mac)

Steps to Reproduce:

1.  create a project, add 2 root folders to the workspace
2.  in the folder settings, add configuration to hide dot files:

  "files.exclude": {
    "**/.*": true,
}

Now the folder won't appear in the file explorer.
This used to work properly before multi-root folders got introduced, as it was used to hide all dot files from the file explorer

**Comment by bpasero** [comment]
@isidorn maybe a candidate if true

**Comment by isidorn** [comment]
I can reproduce this.
@MastroLindus thanks for reporting with nice steps.
