### ISSUE TITLE
VSCode 1.18.0 Update cause Node JS Web App failed to Run/Debug

### ISSUE THREAD

**Issue by sekhuat** [Microsoft/vscode#37891]
VSCode 1.18.0 Update cause Node JS Web App failed to Run/Debug. 

I was working on a project and everything works fine then out of sudden I got an error as shown in the attached file below. I quit the VSCode and relaunch it and it shows the VSCode is just updated to 1.18.0. From then whenever I try to run my Node JS app using the VSCode it always show the same error. 

If I run my Node JS app using the command line, my app runs fine without issue. Please help.

- VSCode Version: 1.18.0
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. Open the node js app folder using the Open.. menu item from VSCode
2. Press F5 to run/debug the node js app and select "Node.JS"
3. Just after the app run, it throws the following errors.

<img width="1680" alt="vscode-error" src="https://user-images.githubusercontent.com/13288516/32592438-a3bd5e92-c55e-11e7-89ea-3dd48f16dc49.png">

Reproduces without extensions: No

**Comment by weinand** [comment]
How are exceptions configured in your VS Code?

You can find some checkboxes in the Breakpoints view of the debug viewlet:
![2017-11-09_10-40-24](https://user-images.githubusercontent.com/1898161/32598623-836f8b2a-c53a-11e7-8575-9222b3f538ae.png)

**Comment by sekhuat** [comment]
My exceptions configuration is all checked include the “All Exceptions” as shown as below.



I had tried to remove the “All Exceptions” and now it seem working fine. Thanks.

Best regards,
Peh Sek Huat
Justnice.Net
133 New Bridge Road #09-06, 
Chinatown Point， Singapore 059413
Tel: (65) 6795 9251
www.justnice.net
Company Registration No. : 52979647C

**Comment by weinand** [comment]
Yes, that explains it.
Your program is throwing an Exception (that is caught) but VS Code shows the Exception because you have the “All Exceptions” options checked.
