### ISSUE TITLE
ini and admx files showing up on search despite being added to search.exclude

### ISSUE THREAD

**Issue by yoav-lavi** [Microsoft/vscode#37896]
- VSCode Version: 1.18.0 (Insiders)
- OS Version: Microsoft Windows 10 Enterprise Build 15063

Steps to Reproduce:

1. Add `"**/.ini": true, "**/.admx": true,` to `search.exclude` setting
2. Add settings ` "search.useIgnoreFilesByDefault": true,` `"search.useRipgrep": true,`
2. Perform search (on project with admx and ini files)

**Comment by roblourens** [comment]
Are those files open?

**Comment by glassounds** [comment]
No, closed.

**Comment by roblourens** [comment]
Can you show the output of the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)
