### ISSUE TITLE
Start debugging session from command line

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#3789]
It'd be nice to be able to start a debugging session from command line. eg:
code my_workspace --debug name_of_my_configuration_in_launchjson

Other features we could use to simulate this would be the ability for extensions to read the currently selected debug configuration, and a way to set it, or the ability to pass it as a parameter to workbench.action.debug.start.

**Comment by axemclion** [comment]
@weinand @isidorn Wanted to ping to see if this feature can make it to a sprint. 
We need this feature to support the following scenario - 

User has a ReactNative app running, and selects "Debug JS". This action starts up the ReactNative VSCode extension and we need to set the debugging mode. We would like to select launch configuration when such a command is issued.

**Comment by isidorn** [comment]
@axemclion we can investigate to introduce it in may - so the next sprint.
This sprint we are already in endgame and are no longer adding new features

**Comment by isidorn** [comment]
We now allow to call `vscode.commands.executeCommand('vscode.startDebug', 'MyConfigurationName');`

**Comment by isidorn** [comment]
We still support this, but we also support passing in the json object, please check my comment in #4615
