### ISSUE TITLE
Vscode installed the extension store installation plugin to report that error, I installed the offline plug-in also useless

### ISSUE THREAD

**Issue by amagiAmagi** [Microsoft/vscode#37893]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:44:50.318Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@amagiAmagi can you be more specific what the issue is?
