### ISSUE TITLE
No Split Editor button on 'Workspace Settings' page

### ISSUE THREAD

**Issue by drdgvhbh** [Microsoft/vscode#37892]
- VSCode Version: 1.17.2
- OS Version: Microsoft Windows [Version 10.0.16299.19]

Steps to Reproduce:
1. Open Workspace Settings
2. Observe how there is no split editor button.

Reproduces without extensions: Yes

I think this is a useful feature to have because you usually want to see how your changing your settings affects your files live. On a widescreen monitor, the settings page doesn't really need to take up the entire screen anyways.

![image](https://user-images.githubusercontent.com/21375952/32592673-d2d6e340-c4f2-11e7-8e6f-43c1eb1e754f.png)

If this feature is wanted, I would like to do the PR.

**Comment by sandy081** [comment]
PR is welcome.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/38000
