### ISSUE TITLE
Error when trying to save to root of drive

### ISSUE THREAD

**Issue by RWeigelt** [Microsoft/vscode#379]
In version 0.10.1 it is no longer possible to write to the root of a drive (which worked up to 0.9.1).
When trying to save to e.g. `r:\example.txt`, the following error message appears:
```
EPERM: operation not permitted, mkdir 'r:\'
```
Tested on Windows 7 Ultimate and Windows 10 Professional, US language, German region settings.

**Comment by bpasero** [comment]
@RWeigelt are you sure you can save there, can you try with nodepad?

**Comment by RWeigelt** [comment]
Yes, I can write a text file with notepad. And I also tried other drives.
What I found out in the meantime is that this happens only when *creating* a new file. Opening, editing and saving an existing file works correctly.

**Comment by bpasero** [comment]
@RWeigelt so you do Ctrl+N, type something and then try to save it to r: from the windows save dialog?

**Comment by RWeigelt** [comment]
Exactly. The error message appears trying to use Save, Save As or (when creating multiple files), Save All.

**Comment by bpasero** [comment]
@RWeigelt is R: some drive created with subst or a real physical drive? I assume it is not the root drive where windows is installed?

**Comment by RWeigelt** [comment]
R: is a RAM disk - so I suspected this to be the problem at first. That's why I checked on other, "real" drives (except the system drive C:), and I can reproduce the behavior.

**Comment by RWeigelt** [comment]
What I'm not sure about is why VSCode is trying to run `mkdir r:\` at all. When I do this from a command line (`cmd.exe`), I get an "Access is denied" there as well - which doesn't surprise me.

**Comment by codepic** [comment]
It actually tries to create the root path :)

If you run VS Code as non-admin, it won't even let you try to save to `C:\file.ext` but if you run VS Code as admin, it will let you try but fails on creating `c:\`.

![capture](https://cloud.githubusercontent.com/assets/3933589/11312456/e07934c6-8fde-11e5-9c12-331e543bf6a9.PNG)

**Comment by bpasero** [comment]
Thanks, will look into it!

**Comment by bpasero** [comment]
This looks like a bad regression in pfs.mkdirp(). It relies on the EEXIST error but when reaching the root drive, it ends in EPERM. @joaomoreno I think you touched this function last.

**Comment by codepic** [comment]
As of now, 0.10.8-insider build run as an administrator lets you save to D:\<filename>

As far as I can see, @bpasero this is truly closed.
