### ISSUE TITLE
Allow to reload a single file 

### ISSUE THREAD

**Issue by RMPR** [Microsoft/vscode#37901]
- VSCode Version: 1.17.2
- OS Version: Kali 2.0 2017

Steps to Reproduce:

1. Reload a single file without reloading the whole windows
2. Using a keyboard shortcut

Reproduces without extensions: Yes/No

**Comment by fabiospampinato** [comment]
In which case would you want to reload a single file? If I have a text file opened in VSC, and I edit it with some other editor, VSC updates it automatically.

**Comment by RMPR** [comment]
I generate a Java project using netbeans then I open the same project with
vsc, netbeans reload automatically a file when I modify it with vsc but it
is not always the case for vsc, so I ask a fonctionnality to do it manually

2017-11-09 14:57 GMT+01:00 Fabio Spampinato <notifications@github.com>:

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
