### ISSUE TITLE
Feature: Setting for permanently delete file in explorer.

### ISSUE THREAD

**Issue by F-loat** [Microsoft/vscode#37900]
I'm use windows 10 with recycle been disabled, so when I delete a file  in explorer I will got an error 'Falied to move ...' always.
I'm use git to manage the project and I don't think trash is useful to me so please add a setting for permanently delete file in explorer.
Thanks.

**Comment by bpasero** [comment]
@F-loat as a workaround for now if you keep the `Shift` key pressed when doing delete, it will bypass the trash (same as on Windows explorer).

**Comment by F-loat** [comment]
Yep I know this way, but I think that add a setting option is better. An invalid menu item make a little uncomfortable.
Thank you.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
