### ISSUE TITLE
Unable to select the working directory in the explorer pane

### ISSUE THREAD

**Issue by Dimpl** [Microsoft/vscode#37904]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
latex-workshop|Jam|3.6.1
cpptools|ms-|0.14.0
csharp|ms-|1.13.0
vscode-subword-navigation|ow|1.1.5
vscode-icons|rob|7.17.0
vscode-autohotkey|sle|0.2.1

---

After opening a directory in VSCode and navigating around, I find myself stuck as how to select the directory itself under certain circumstances, for the purposes of creating files and folders.

If I select its name, this minimises the directory tab, but does not actually select the directory. If the directory contains any files, I can select a file. In a smaller directory, I can expand the panel so that it shows all contents and click in the empty space after the files and folders.

However, if it is a directory containing only a large number of folders, I have not worked out how to create a file in the directory. Is there a method, or does this need to be added?

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
