### ISSUE TITLE
Bug in auto import feature

### ISSUE THREAD

**Issue by sseppola** [Microsoft/vscode#37907]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.17.0
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.0.0
Go|luk|0.6.67
java|red|0.13.0
transpose|v4r|0.0.5
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Restarted VSCode
2. Typed 'log' + enter in a javascript project to trigger a console.log snippet

This triggered VSCode to include the following import statement at the top of my file:
```js
import { log } from '../../../../../../../../../../../../../../Library/Caches/typescript/2.6/node_modules/@types/gulp-util';
```

Reproduces without extensions: Yes

Only reproducible once after launching the application.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19878
