### ISSUE TITLE
Git authentication doesn't complete

### ISSUE THREAD

**Issue by Deliay** [Microsoft/vscode#37902]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
language-haskell|jus|2.4.0
cpptools|ms-|0.14.0
csharp|ms-|1.13.0
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0

- ### Disable all extension
![00 disable all extension](https://user-images.githubusercontent.com/5661435/32596705-27587650-c56f-11e7-8b8e-a809aff2ef24.png)
- ###  End all bash
![01 end all bash](https://user-images.githubusercontent.com/5661435/32596706-27879156-c56f-11e7-8bdd-a18b28c3b483.png)
- ### run vscode
![02 run vscode](https://user-images.githubusercontent.com/5661435/32596707-27b833c4-c56f-11e7-9622-0d66909e3021.png)
- ### click sync button ( icon rotated but no other response)
![03 click sync button](https://user-images.githubusercontent.com/5661435/32596708-27e86774-c56f-11e7-8bcc-de2835bba3b4.png)
- ### or run git pull command (no response too)
![04 or run git pull command](https://user-images.githubusercontent.com/5661435/32596709-2818b8ac-c56f-11e7-99d4-5bb46235843a.png)
- ###  vs code run 3 bash instance
![05 vs code run 3 bash instance](https://user-images.githubusercontent.com/5661435/32596710-28479780-c56f-11e7-952f-d69562645add.png)
- ### exit vs code
![06 exit vs code](https://user-images.githubusercontent.com/5661435/32596711-28763374-c56f-11e7-82de-9d9d082a4ad4.png)
- ### but bash not exit
![07 but bash not exit](https://user-images.githubusercontent.com/5661435/32596714-28a55366-c56f-11e7-8fde-acf9a5c826e2.png)

---

Reproduces without extensions: Yes

**Comment by Deliay** [comment]
![20171109171537](https://user-images.githubusercontent.com/5661435/32597424-a1b56d0c-c571-11e7-8a7f-645825d4191e.png)


I change the integrated shell to default(PowerShell), but VSCode still execute bash to run git command.

**Comment by joaomoreno** [comment]
@Deliay What git authentication mechanism are you using in that repository?

Can you do `git pull` from the command line easily?

Do you have a credential manager installed?

**Comment by Deliay** [comment]
@joaomoreno 
Just HTTPS authentication.

I test `git pull` command in VSCode terminal then get error. But exectue in MinGW is work properly.

May Windows Cerdential Manager? I don't knwon , I used not install this kind of software

![1](https://user-images.githubusercontent.com/5661435/32655202-a153a74e-c647-11e7-90f9-25b806b8f06f.png)

**Comment by joaomoreno** [comment]
Can you try using the Windows Command Prompt?
