### ISSUE TITLE
terminal.integrated.shell.windows=git bash 

### ISSUE THREAD

**Issue by zhongzhong0505** [Microsoft/vscode#37908]
- VSCode Version: code insiders 1.19
- OS Version: win10

Steps to Reproduce:

1.set the terminal.integrated.shell.windows = /path/to/git bash
2.execute git log
3.ctrl+c 
4.input something...
5.not show in the terminal

Reproduces without extensions: Yes/No
No

**Comment by spencerwmiles** [comment]
I also have a similar problem. It's not consistent but when I run gitk or similar in the Integrated Terminal, I sometimes cannot exit with ctrl+c. When you close the gitk window, it appears as though the Integrated Terminal catches up to the commands that were attempted to be executed while gitk was running and the terminal closes (ctrl-d for example). Not a critical issue by any means, but it will be nice once this has been resolved.

**Comment by Tyriar** [comment]
I'm consolidating ctrl+c issues under https://github.com/Tyriar/node-pty/issues/7
