### ISSUE TITLE
Ctrl + C didn't work in Integrated Terminal

### ISSUE THREAD

**Issue by Bigdragon13th** [Microsoft/vscode#37909]
- VSCode Version: 1.18.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open Integrated Terminal
2. Try `Ctrl + C`
3. Nothing happened...

Reproduces without extensions: Yes

**Comment by k8w** [comment]
The same: Win10 / Vscode 1.19.0 insiders

**Comment by k8w** [comment]
Actually it works, but really wait so long time before response

**Comment by Bigdragon13th** [comment]
It's working now, the issue is because I binded `Ctrl + C` to terminate task (It's working before 1.18.0). Remove that keyboard binding make `Ctrl + C` works again in terminal.
