### ISSUE TITLE
Can you add to a VSCode language's auto complete?

### ISSUE THREAD

**Issue by thomthom** [Microsoft/vscode#37906]
Apologies for posting a question here, I tried StackOverflow first - but it attracted only tumbleweed: https://stackoverflow.com/questions/46718122/can-you-add-to-a-vscode-languages-auto-complete

Is there a difference place which I can ask questions?

What I was looking for was:

We got a Ruby API for our application and I'm trying to figure out if I can make an extension for VSCode that add that insight to the Intellisense feature of the editor.

With RubyMine I've done this by simply using stubs packaged as a gem. Adding the gem to the RubyMine project is all that I needed to have the editor provide code insight that included our API.

How can this be done for VSCode? I was hoping to build upon the existing vscode-ruby extension for Code. But I'm only finding examples of adding language extensions.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by thomthom** [comment]
Any suggestions to where to ask for help when StackOverflow doesn't yield any response?
