### ISSUE TITLE
Native Tab still does not work on MacOs High Sierra

### ISSUE THREAD

**Issue by aytacozkan** [Microsoft/vscode#37903]
- VSCode Version: 1.18.0 
- OS Version: MacOS High Sierra 

Dear Vs Code Team, 

This issue has been opened since version 1.17.0 on High Sierra as well as have discussed so much at the community, to solve Native Tab issue by myself, I have prepared my own electron build (on MacOs High Sierra), follow this instructions https://electron.atom.io/docs/development/build-instructions-osx/ and works great with Native Tabs again but with some issues, for example "cannot check updates" etc You have improved electron for code, How can I find your own electron implementations, Can you share with me and with community? 

Thanks, 

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35361
