### ISSUE TITLE
php.suggest.basic list appears after closing any HTML tag in a PHP file

### ISSUE THREAD

**Issue by willpower232** [Microsoft/vscode#37919]
- VSCode Version: 1.18
- OS Version: Windows 10

When typing HTML into a PHP file, the `php.suggest.basic` list appears after closing each tag (presumably on the press of the > key).

![image](https://user-images.githubusercontent.com/1619102/32600933-098c2d96-c539-11e7-8940-61f6142a063b.png)

The problem goes away if I set `php.suggest.basic: false` but it didn't do this with the previous version.

Steps to Reproduce:

1. Type HTML into a PHP file

Reproduces without extensions: Yes

**Comment by willpower232** [comment]
Similar to https://github.com/atom/ide-php/issues/47 which is the start of a trail to https://github.com/Microsoft/language-server-protocol/issues/138

**Comment by roblourens** [comment]
This was the cost of #26598, and needs Microsoft/language-server-protocol#138 to be fixed

**Comment by bmewburn** [comment]
Would checking for the `-` that precedes `>` in the completion provider solve this? If it does not exist then return an empty completion list.

**Comment by roblourens** [comment]
Yeah, that would probably be a good workaround.

**Comment by felixfbecker** [comment]
Implemented in https://github.com/felixfbecker/php-language-server/pull/527
