### ISSUE TITLE
After upgrading to 1.18.0, vscode show red error lines on almost every code line 

### ISSUE THREAD

**Issue by suadev** [Microsoft/vscode#37915]
After upgrading to 1.18.0, vscode show red error lines on almost every code line like at the screenshot.

Between, the project builds and runs properly. And idea?

![image](https://user-images.githubusercontent.com/5918811/32599774-95a941a0-c54e-11e7-8158-6de8116a3a23.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
