### ISSUE TITLE
debugger activation is no longer debug type specific 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37918]
extracted from #33803.

Previously debuggers would activate on the `onDebug:type` activation event which only fires if this type of debugging is really needed (e.g. because the user runs a launch config that refers to this debug type). So, a Java debug extension would not activate if the user only works in (and debugs) a Python project.

With the new debug API it has become necessary that debug extensions are activated as soon as any debugging functionality is triggered so that they can register their "DebugConfigurationProvider" for a specific debug type. For this we have introduced a `onDebug` activation event.

A consequence of this is that all debug extensions are activated as soon as a launch configuration is started (independent of type). As long as activation of a debug extension is cheap this is not a problem. However, there are some debug extensions where activation triggers a language server to start up which makes the original debug operation (that triggered the activation) behave sluggish.

We should find a way to mitigate this.

**Comment by isidorn** [comment]
My suggestion from the other issue: introduce new activation event `"onDebugSession:type"` which would fire everytime a session of that type is about to start. Basically would behave like the old event.

**Comment by weinand** [comment]
We've introduced the new event for a reason. Reintroducing the old event does not address the problem we tried to solve:
Activating on a specific type only would miss the case of collecting all registered DebugConfigurationProviders for the "initialLaunchConfigs" functionality.

**Comment by roblourens** [comment]
That would be an improvement. `onDebugInitialConfigurations` could still activate the go language server unnecessarily, but that shouldn't happen too often. And it would register for `onDebugResolve:go`, which is a good time for it to activate. So it seems good to me.

Having 3 similar events could be confusing though. What if we just had `onDebug:type` which was equivalent to `onDebugInitialConfigurations | onDebugResolve:type`? I guess this is the same as activating the old event for onDebugInitialConfigurations.

**Comment by weinand** [comment]
Having only `onDebug:type` with the semantics `onDebugInitialConfigurations | onDebugResolve:type` would work too, but it would mean that extensions are activated in the "initial launch configurations" case even if they do not provide any launch configs. However, that is not worse than the current solution.

**Comment by roblourens** [comment]
> even if they do not provide any launch configs

My guess is that most extensions that have a debug config provider would provide initial configs. But I don't know for sure, maybe vscode-tools could answer that question.

**Comment by weinand** [comment]
Most debug extensions contribute initial launch configs statically and declaratively through the package.json. In this case the `DebugConfigurationProvider.provideDebugConfigurations` isn't used and we could avoid the activation.

**Comment by isidorn** [comment]
I have pushed new activation events `onDebugInitialConfigurations` and `onDebugResolve:type` as @weinand specified above.

We should remember to mention this in the release notes and to update our documentation about activation events. I plan to do that end of next week.

**Comment by weinand** [comment]
I'v started to use both activation events for node-debug (instead of `onDebug`).
Please consider this for the test plan item.

**Comment by isidorn** [comment]
@weinand great!
I created a test plan item https://github.com/Microsoft/vscode/issues/39535
