### ISSUE TITLE
File menu mnemonic S duplicated

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#37911]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

You've added `Save Workspace` to the file menu but the mnemonic is `S` which breaks `Alt F S` to save file as it appears higher in the menu (though of course `Alt F S S Enter` works)

**Comment by SteveALee** [comment]
The Open File and Workspace mnemonics also clash but the order is reversed so less of a problem

**Comment by kattkieru** [comment]
Alt F A also is clashing.  Glad there was already an issue for this.

**Comment by wyckster** [comment]
This is really annoying.  Alt F S should be _File > Save_ and Alt F A  should be _File > Save As..._.

The new _File > Add Folder To Workspace..._ and _File > Save Workspace As..._ need different, non-conflicting shortcuts.

**Comment by SteveALee** [comment]
Looks like issue #38006 and commit f8a0b7d is a partial fix to this - only deals with Alt F S

**Comment by bpasero** [comment]
@isidorn since you wanted to take care of this for the "`O`" case too. Thanks.

**Comment by SteveALee** [comment]
And 'A'?

**Comment by isidorn** [comment]
@bpasero sure. So will keep this for november milestone.
