### ISSUE TITLE
statusBar.background workbench customization is not applied in new window

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#37910]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601

---

Steps to Reproduce:

1. Add setting to change status bar color, e.g.

		"workbench.colorCustomizations": {
			"statusBar.background": "#333",
		}

2. File -> New Window
3. Check status bar color (interestingly not all color settings are affected)

	![image](https://user-images.githubusercontent.com/834235/32599326-77d29080-c53c-11e7-8d68-081211422e38.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Try with `statusBar.noFolderBackground` when no folder is opened.

**Comment by brunnerh** [comment]
Oh, i get it. It seems unfortunate that the setting for opened workspaces is not prefixed at all.
