### ISSUE TITLE
[webkit-debug-adapter] Path must be a string. Received undefined

### ISSUE THREAD

**Issue by hansrwindhoff** [Microsoft/vscode#3792]
Debugging with chrome debugger extension fails with:
[webkit-debug-adapter] Path must be a string. Received undefined

this is the launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
			"file": "${workspaceRoot}/index.html"
		},
		{
			"name": "Launch chrome with localhost:3000, you must start serve seperately",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:3000",
			"sourceMaps": true,
			"webRoot": ".",
            "file": ""
		},
		{
			"name": "Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222
		}
	]
}

This used to work just fine until the 0.10.10 update.

**Comment by anwalkers** [comment]
+1 Same here...

![image](https://cloud.githubusercontent.com/assets/3085122/13589623/0fa8b2fe-e48e-11e5-9b1d-766b04d5abf3.png)

![image](https://cloud.githubusercontent.com/assets/3085122/13589637/3c18c2de-e48e-11e5-8eb0-b6754882f981.png)

`{
    "version": "0.1.0",
    // "debugServer": "4712",
    "configurations": [
        {
            "name": "test chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/index.html",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "wwwroot"
        },
        {
            "name": "launch for file",
            "type": "chrome",
            "request": "launch",
            "file": "wwwroot/index.html",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "wwwroot/out/client with space"
        },
        {
            "name": "attach to chrome",
            "type": "chrome",
            "port": 9222,
            "request": "attach",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "./wwwroot"
        }
    ]
}
`

**Comment by MichaelPetrinolis** [comment]
I uninstalled extension and reinstalled, same thing. Version 0.10.10 seems to break something

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#117
