### ISSUE TITLE
Taskbar icon problem

### ISSUE THREAD

**Issue by anurag2361** [Microsoft/vscode#37922]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
tslint|eg2|1.0.14
Angular2|joh|2.10.0

Congratulations on the update. Thanks for changing the icon back to blue.
However, when we pin the icon to the taskbar, it still remains orange.
I have tried by right-clicking the blue icon and selecting 'Pin To Taskbar' and dragging and dropping VSC from Start menu to taskbar. Icon remains orange. This is also the case in Windows context menu when we right click inside a folder to select VS Code.

Steps to Reproduce:

1. Pin VSC from Start menu to taskbar.

Reproduces without extensions: Yes

**Comment by shanesully** [comment]
Have you logged out or rebooted since the update?

Alternatively, you can manually refresh the icon cache:

https://superuser.com/questions/499078/refresh-icon-cache-without-rebooting

**Comment by Incurafy** [comment]
I had the same issue at first, but it was solved by closing all instances of VS Code and reopening it.

**Comment by AlexPasternak** [comment]
This always happens, it just needs to be cleared from cache by the system eventually.

Btw, I'm sad that icon is once again blue. I have a real blue icon fatigue, so many icons are this boring color. Just in my current Alt-Tab:

- Outlook
- Messages
- Skype
- Finder
- SourceTree
- Word
- Enpass
- AnyList

etc. Having a different color was a nice change of pace, and it's a bit bizarre that people were so opposed to it.

**Comment by anurag2361** [comment]
@AlexPasternak or, maybe you can look at it this way, that you have an instant attraction of apps with blue icons. 😄 
In my case, orange looked a little weird, not bad, just something unconventional (which can be good).

Anyways, this can be closed. Restarting fixed the issue.
