### ISSUE TITLE
Autoimport always imports relative to baseUrl

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#37928]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. ts project with provided `baseUrl`
2. add autoimport for smth from same directories sub-tree
3. see `baseUrl` relative import
```ts
/// auth/routing.ts
import {MobileStubComponent} from "auth/component/mobile-stub/mobile-stub";
```

expected import relative to current file
```ts
import {MobileStubComponent} from "./component/mobile-stub/mobile-stub";
```

Reproduces without extensions: Yes

**Comment by Martaver** [comment]
Also seeing this behavior, in 1.18 and previous, on both manually chosen import fixes and the new auto-import on completion feature.

**Comment by Martaver** [comment]
For me, removing the baseUrl entry from my tsconfig.json file fixed the issue.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19920
