### ISSUE TITLE
Feature Request: JS functions as classes

### ISSUE THREAD

**Issue by ray007** [Microsoft/vscode#37925]
Old-style javascript code has functions with prototype properties instead of classes.
Would it be possible to recognize the symbols as such, so the outline can do a better job? See also https://github.com/patrys/vscode-code-outline/issues/59

**Comment by mjbvz** [comment]
We should already do this in basic cases. Can you please provide some example code where this does not work currently

**Comment by ray007** [comment]
Basic cases?
Doesn't seem that way at all.
Much reduced test code:
```
var envBrowser = function() {
};

envBrowser.prototype.minAnimDelay = 20;

envBrowser.prototype.init = function() {
    this.y = 1;
};
```
And the code outline shows
- envBrowser
- envBrowser.prototype.init

Changing the `var envBrowser = function() {};` to `function envBrowser() {}` gives me a different icon for it in the outline, but that's it.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/19921 to track this upstream
