### ISSUE TITLE
Support for OS-specific keybindings

### ISSUE THREAD

**Issue by loganmzz** [Microsoft/vscode#37921]
- VSCode Version: 1.17.2
- OS Version: Ubuntu 17.10 / Windows 10

VS Code has already conditionnal keyboards rules through `when` clause. It will be very nice to also support OS-based condition. Some keybindings can be shared between Windows & Linux for example but some can't.

For exemple to access terminal from Windows, I use "ctrl+`" [binding](https://github.com/loganmzz/settings/blob/master/vscode/keybindings-win.json#L3) while on linux I use "ctrl+[Quote]" [binding](https://github.com/loganmzz/settings/blob/master/vscode/keybindings-linux.json#L3).

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@loganmzz I think current keybindings are already OS specific. I do not understand what more you are looking for?

Why can't you change the default keybinding and use it across using https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync extension

**Comment by loganmzz** [comment]
"`" and "[quote]" are respectively specific to linux and windows ?

**Comment by sandy081** [comment]
Do you mean you want the ability to customise key bindings per OS?

**Comment by loganmzz** [comment]
Yes exactly. However, if "`" and "[quote]" are specific (don't exist on others) to each OS, it's enought for my needs.

Currently I store them separately to be sure there's no conflict but need to manually merge common settings.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8962
