### ISSUE TITLE
Autoimport does not respect TS re-export files

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#37926]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. e.x. angular app, write `Component`
2. press enter for autocomplete/autoimport
3. see
```ts
import { Component } from "@angular/core/src/metadata/directives";
```

expected
```ts
import { Component } from "@angular/core";
```

Reproduces without extensions: Yes

**Comment by artaommahe** [comment]
Cant repoduce it with in-project re-export files. Looks like it's wrong only for lib imports

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19888
