### ISSUE TITLE
Autoimport string format

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/vscode#37927]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Currently autoimport has hardcoded format with spaces after first bracket and before last.
`import { SomeClass } from "smth/smth";`
It would be cool to have some format configuration cause e.x. in current project we use imports without this spaces
`import {SomeClass} from "smth/smth";`

**Comment by mjbvz** [comment]
This is controlled by the settings:

```json
    "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false
```

Please try setting these
