### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#37924]
- VSCode Version: 1.18
- OS Version: Arch Linux

Steps to Reproduce:

1. Install vscode-cpptools from Microsoft
2. Wait for random amount of time after opening a cpp file

Reproduces without extensions: No

```
[/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:441 [/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
mime.ts:59 Overwriting extension <<.log>> to now point to mime <<text/x-code-output>>
(anonymous) @ mime.ts:59
extensionHost.ts:191 [Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c 1: node::Abort() [/opt/visual-studio-code/libnode.so]
 2: 0x7fab28b8fa57 [/opt/visual-studio-code/libnode.so]
 3: %c0x7fab2892ddd7 [/opt/visual-studio-code/libnode.so]
 4: %c0x7fab2892dd55 [/opt/visual-studio-code/libnode.so]
 5: %cv8::internal::Factory::NewTransitionArray(int) [/opt/visual-studio-code/libnode.so]
 6: %c0x7fab28555bcd [/opt/visual-studio-code/libnode.so]
 7: %c0x7fab28405a80 [/opt/visual-studio-code/libnode.so]
 8: %c0x7fab28402a48 [/opt/visual-studio-code/libnode.so]
 9: %c0x7fab2840289b [/opt/visual-studio-code/libnode.so]
10: %c0x7fab2841a6b9 [/opt/visual-studio-code/libnode.so]
11: %cv8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/opt/visual-studio-code/libnode.so]
12: 0x7fab284081be [/opt/visual-studio-code/libnode.so]
13: %c0x7fab2840c20a [/opt/visual-studio-code/libnode.so]
14: %c0x7fab28777009 [/opt/visual-studio-code/libnode.so]
15: %c0x7fab28776de3 [/opt/visual-studio-code/libnode.so]
16: %c0x7fab28778fc7 [/opt/visual-studio-code/libnode.so]
17: %c0x7fab28776046 [/opt/visual-studio-code/libnode.so]
18: %c0x7fab2844939e [/opt/visual-studio-code/libnode.so]
19: 0x209001e0415d
%c
<--- Last few GCs --->

[28213:0x3b382b7f0000]   480464 ms: Mark-sweep 2055.9 (2192.6) -> 2055.9 (2189.6) MB, 5185.8 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 5186 ms) last resort 
[28213:0x3b382b7f0000]   485779 ms: Mark-sweep 2055.9 (2189.6) -> 2055.9 (2189.6) MB, 5312.8 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xe6925dab959 <JS Object>
    0: builtin exit frame: stringify(this=0xe6925d90771 <a JSON with map 0x347650206199>,0x2da157f02311 <undefined>,0x3f2d4dbd3111 <JS Function (SharedFunctionInfo 0x162750bdb509)>,0x3f2d4dbd2fc9 <JS Array[3]>)

    1: arguments adaptor frame: 2->3
    2: callOnRemote [/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:~4] [pc=0x209002508f53](this=0xbe9fdbd93a1 <...


index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1050)
    at Pipe.onread (net.js:581)
onError @ index.js:44
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050)
    at Pipe.onread (net.js:581)
extensionService.ts:171 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
e._onExtensionHostCrashed @ extensionService.ts:171
messageService.ts:126 Extension host terminated unexpectedly.
e.doShow @ messageService.ts:126
```

**Comment by anurag2361** [comment]
Extension issue is not a VS Code issue. These must be filed in extensions's github page. In your case, https://github.com/Microsoft/vscode-cpptools

**Comment by agauniyal** [comment]
I cannot reproduce in the previous version of vscode, I upgraded to 1.18 today and this has been happening since then only. Another thing to note, there are two processes associated with cpptools extension. First is the extension host process and the second one is vscode-cpptools process. It's the first one that goes rouge not the second one so I thought I should open issue in this repo.

**Comment by sean-mcmanus** [comment]
We also don't think it's a cpptools issue. We think Vs Code itself has a problem.

**Comment by jrieken** [comment]
> [/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:441 [/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.

@sean-mcmanus That does point towards the C++ extension. Unlikely that triggers a crash but there is some command duplication

**Comment by alexandrudima** [comment]
The crash is Out-Of-Memory in the extension host process.

We are sending a message from the extension host to the renderer process and in doing so we call `JSON.stringify`. It appears the OOM crash occurs within `JSON.stringify`. 

Perhaps it is one of those cases where we are trying to serialize a Proxy or some other nefarious object. Any ideas @jrieken ?

**Comment by jrieken** [comment]
Maybe some cyclic object that is being returned to us... Maybe from a command. @agauniyal Can you share the list of extension with which that happened?

**Comment by agauniyal** [comment]
@jrieken I've enabled these extensions for my workspace -
- [x] https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
- [x] https://marketplace.visualstudio.com/items?itemName=matthewferreira.cppcheck
- [x] https://marketplace.visualstudio.com/items?itemName=MS-DevSkim.vscode-devskim
- [x] https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

but when I looked inside htop, I saw the parent process of vscode cpptools consuming resources more than the extension process itself. So I doubt any other extension would interfere with it.

**Comment by agauniyal** [comment]
Another random encounter, opened up a project in vscode and was commenting out some lines then closed it. Somehow extension host process didn't exit with editor itself and after the fans caught my attention I managed to take an screenshot 😆 -

![2017-11-11-023532_1366x768_scrot](https://user-images.githubusercontent.com/7630575/32678537-b86e8e08-c688-11e7-80ac-8cef66068b7b.png)

**Comment by sean-mcmanus** [comment]
@jrieken The message about `[/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command workbench.action.gotoSymbol appears multiple times in the commands section.
extensionService.ts:441 [/home/agauniyal/.vscode/extensions/ms-vscode.cpptools-0.14.0]: Command workbench.action.showAllSymbols appears multiple times in the commands section.` should be safely igored, and we're not aware of any problem caused by this, so I don't think it's related to this failure. We add those commands in our package.json because they're referenced in our menus.editor/context. Let us know if there's another way to reference the commands in the menu without having the commands defined in our package.json.

**Comment by agauniyal** [comment]
Is there some way to turn on extra logging or stuff since I'm finding it much difficult to reproduce this issue each time? Meanwhile, I'll try to record my actions and find some pattern.

**Comment by zarefarid** [comment]
Hi,
I was using DevSkim on WIndows 10 and Visual Code too. My CPU and Memory is going high and high whenever this extension is existed in IDE. I got memory dump of this extension when it was active in first minuets. It is about 860 Mb.
Is this extension using our CPU and Memory for mining Bitcoin???

**Comment by sean-mcmanus** [comment]
@zarefarid We don't mine BitCoin. 860 MB is unusually high. Is this for the main Extension.exe process or the IntelliSense.Msvc.exe process? Is the process lingering after Code.exe is shutdown? Our extension generates a symbol database and parses files. You can reduce the browse.path in c_cpp_properties.json (Edit Configuration command) to do less parsing.

**Comment by zarefarid** [comment]
![image](https://user-images.githubusercontent.com/468652/32970602-c820a22e-cbfa-11e7-8811-9e83672baac1.png)
I got dump of just high memory process in task manager. Then I killed that process without killing other visual code processes. Visual code showed me an error for running DevSkim extension. Then I uninstalled DevSkim and my CPU and Memory problem solved. I think you are able to test this by adding DevSkim and opening some code. I was working on a python code.

**Comment by sean-mcmanus** [comment]
@zarefarid We don't control memory usage of the Code.exe process (Visual Studio Code). That is from VS Code itself. You can file an issue at https://github.com/Microsoft/vscode/issues , although I think that memory usage seems normal to me. It sounds like the DevSkim extension might be causing it too.

**Comment by zarefarid** [comment]
I installed DevSkim and wait a some secondes more and memory and CPU raising. It was raising so I killed the process.
![image](https://user-images.githubusercontent.com/468652/32971684-7e22eb96-cbff-11e7-9d0e-44db2c05c657.png)

The error on Visual code was.
.vscode\extensions\MS-DevSkim.vscode-devskim-0.2.0\server\devskimWorker.js:136
            this.analysisRules = validator.validateRules(this.tempRules, DevSkimWorker.settings.devskim.validateRulesFiles);
                                                                                               ^

TypeError: Cannot read property 'devskim' of undefined

**Comment by agauniyal** [comment]
Though we both have devskim extension but my htop extension clearly shows the association with vscode + cpptools. It might be a combination of both devskim and cpptools being present but I still doubt so because even when I've disabled all extensions this situation arises quite often. Now I'm not using cpptools for any medium/large sized projects so can't repro further.

**Comment by seanpoulter** [comment]
I've had DevSkim installed to while this has happened. Is there any way I can start vscode with all the dev tools open to catch what's going on (automatically, since it'll lock before I get'r open)?

**Comment by alexandrudima** [comment]
We have introduced a few serviceability features with 1.19, I was wondering if you could help us narrow down the problem.

1. Logs
Run `F1 > Developer: Open Logs Folder`. There, you can look for `exthost.log` and check what are the last logged messages before crashing.

2. Profiling of running extensions
Run `F1 > Developer: Show Running Extensions`. There, you can see which extensions are currently running in the extension host (activated). Then, you can press the black circle button to begin recording a profiling session. You can do your steps, and then stop recording. There will be graphs and new times showing which extension is consuming most CPU. The profile can also be saved.

Do any of these show anything about the two extensions: cpptools or DevSkim ?
