### ISSUE TITLE
Terminal commands stacking

### ISSUE THREAD

**Issue by krilllind** [Microsoft/vscode#37936]
When executing same terminal command multiple times, they get stacked instead of combined into one command. If you for example run:
* npm -help
* npm -v
* npm -v

And then use the up arrow key to step through the list of executed commands, I would like to only have to press the up arrow key once to get to `npm -v` and twice to get to `npm -help`, not three times as it is right now.

This behaviour will make you think that nothing actually happens, which is not good for user experience.

- VSCode Version: 2017 1.18
- OS Version: Windows 10 64bit

Steps to Reproduce:
See example above.

Reproduces without extensions: Yes

**Comment by fabiospampinato** [comment]
This does depend on the shell you are using, not on VSC.

I use [Z Shell](https://en.wikipedia.org/wiki/Z_shell) and it works exactly as you want. Perhaps you can just configure this in the shell you're already using, I don't know.

**Comment by shobhitchittora** [comment]
@fabiospampinato +1. Bash by default does what @krilllind states. While zsh does not.

**Comment by Tyriar** [comment]
Thanks @fabiospampinato @shobhitchittora for answering 😃

**Comment by krilllind** [comment]
Thank you all for these great answers!😀
