### ISSUE TITLE
Copying from VS Code into OneNote loses indentation

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#37931]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
Untabify|ili|0.0.2
wordcounter|kir|1.2.0
cpptools|ms-|0.14.0

Copying C++ code from VS Code using Ctrl-C then pasting into OneNote using Ctrl-V preserves syntax highlighting but loses indentation.

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
This is very likely a problem with OneNote deciding to remove whitespace.

**Comment by DavidA2014** [comment]
I agree it seems to be a problem with OneNote.  Please feel free to close this issue.

**Comment by rebornix** [comment]
@DavidA2014 Onenote somehow decides to remove the indents (or maybe not honoring spaces somehow), I'll see if there is any way we can make the HTML content compatible with it.

**Comment by DavidA2014** [comment]
@rebornix Thanks for considering this.  The problem is also discussed in #35954.
