### ISSUE TITLE
Bug: intellisense does not see new files.

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode#37939]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open empty folder with VS Code;
2. add empty `tsconfig.json` file in the root;
3. add empty `dir1` folder in the root;
4. add `file1.ts` and `file2.ts` into `dir1`;
2. come back to `file1.ts` and do `import { } from './'` and VS Code does not see `file2.ts`.

Reproduces without extensions: Yes

Screen shot:
![screenshot from 2017-11-09 22-51-42](https://user-images.githubusercontent.com/2286306/32629336-9274f7ba-c5a1-11e7-9fe1-a7a7b5a4cc1c.png)

**Comment by mjbvz** [comment]
I can't repo this in an empty project:

<img width="668" alt="screen shot 2017-11-09 at 10 26 54 am" src="https://user-images.githubusercontent.com/12821956/32622683-862aacde-c538-11e7-9c89-f064bf434034.png">

Can you please provide additional repo steps or a small example project that demonstrates this problem

**Comment by KostyaTretyak** [comment]
@mjbvz, yes, sorry. I rewrite my previous "Steps to Reproduce".

**Comment by mjbvz** [comment]
@KostyaTretyak I still can't reproduce this. What if you manually tigger suggestions by using ctrl+space after the `/`. Also you've disabled all extensions, right?

**Comment by KostyaTretyak** [comment]
@mjbvz, yes, right. This bug reproduce only first open VS Code and follow "Steps to Reproduce".

**Comment by KostyaTretyak** [comment]
In addition, after deleting files, `import` suggestions use deleted filenames.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20023
