### ISSUE TITLE
Create shortcut key to switch between terminals in vs code.

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [Microsoft/vscode#37937]
- VSCode Version: 1.18.0
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Ctrl+` to open terminal.
2. Ctrl+Shift+` to create new terminal.
3. Shortcut key required to switch between terminals.

Reproduces without extensions: Yes

**Comment by shobhitchittora** [comment]
This is already there in vscode. Just add the following lines in your ```keybindings.json```.

```
[
   { "key": "cmd+shift+j", "command": "workbench.action.terminal.focusNext" },
   { "key": "cmd+shift+k", "command": "workbench.action.terminal.focusPrevious" }
]
```

Duplicate #10546

**Comment by vaibhavagrawal2912** [comment]
Thanks for the help

**Comment by shobhitchittora** [comment]
@vaibhavagrawal2912 Anytime!. 
@Tyriar you can close this. 😃
