### ISSUE TITLE
HTML IntelliSense is not really intelligent

### ISSUE THREAD

**Issue by surjithctly** [Microsoft/vscode#37935]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.10240

---

Steps to Reproduce:

1. Create a div `<div></div>`
2. Now to add class, type "c" `<div c></div>`
3. Now its expected to ouput `class` as autocomplete, but instead it shows "canvas"
4. It doesn't make any sense to create a canvas tag inside the tag itself `<div c>`
5. See image below

![vscode](https://user-images.githubusercontent.com/1884712/32604797-f4ce6810-c574-11e7-86ce-e65b7f552531.PNG)

Expect results

It should show supported attributes for the tag selected. Not tag autocomplete. 

Reproduces without extensions: Yes

**Comment by Mlocik97-issues** [comment]
Related to #35128

**Comment by surjithctly** [comment]
Thank you. 

Updated to latest version. But the issue still exists, I disabled the "HTML Snippets" Extension and Fixed the issue.

Thanks a lot 👍 

~Surjith
