### ISSUE TITLE
Git Source Control. File Difference working copy should be in left side

### ISSUE THREAD

**Issue by hirenhcm** [Microsoft/vscode#37938]
The built-in Source control difference should show working copy on the left side and remote copy on the right or there should be an option to change this on user preference.

- VSCode Version: 1.18.0 
- OS Version: Mac OS 10.12.3

Steps to Reproduce:

1. Make sure you have some file that has changes and are tracked by git.
2. From the left sidebar open source control.
3. Working copy will be on the right side and remote change on the left.

Should be another way around. We should see working copy on left-hand side and remote changes on right-hand side. As most merge tools follow this and developers are used to this.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Sorry, I'm closing this issue since I don't think there is enough market demand for it.
