### ISSUE TITLE
Folder content was not populating automatically

### ISSUE THREAD

**Issue by mganitombalak** [Microsoft/vscode#37949]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
material-icon-theme|PKi|2.2.4
vscode-docker|Pet|0.0.21
code-settings-sync|Sha|2.8.5
quokka-vscode|Wal|1.0.76
html-css-class-completion|Zig|1.13.0
html-snippets|abu|0.1.0
msg|ajs|0.1.1
ros|ajs|0.1.0
project-manager|ale|0.23.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
scala|dal|0.0.4
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|1.0.14
vsc-travis-ci-status|fel|1.1.0
code-runner|for|0.8.3
terminal|for|0.0.10
Go|luk|0.6.67
azure-account|ms-|0.1.3
cpptools|ms-|0.14.0
csharp|ms-|1.13.0
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
view-in-browser|qin|0.0.5
java|red|0.13.0
vscode-yaml|red|0.0.4
vscode-icons|rob|7.17.0
jasmine-problem-matcher|sea|1.0.1
gitblame|wad|2.2.0
ReactSnippets|xab|1.4.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. When run webpack on my project it generates related js files and map files under a folder. 
2. In previous versions when files are created, if folder is expanded, i could see the generated files in siderbar asap when they got generated under related folder. But now I need to collapse and  expand it again to be able to see them.

Reproduces without extensions: No

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by mganitombalak** [comment]
Sorry for late response. I tested with Insiders version. It is working fine.

**Comment by isidorn** [comment]
Great to hear it is working fine.
So either one of the extenisions is causing this, you could find which one by disabling them ony by one and then filling a bug against that extension.
Or you can wait for the next stable release which would potentialy fix it.

In either way there is nothing to do on the vscode side thus closing this.
