### ISSUE TITLE
Python: 'Start without debugging shortcut’ has a problem.

### ISSUE THREAD

**Issue by weqopy** [Microsoft/vscode#37946]
- VSCode Version: 1.18
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Set "stopOnEntry" to false in launch.json
2. run python file with debug, it returns result fast, run it again, the result disappears and returns again
3. but when use 'ctrl + F5' to run it without debug, it's not end in fact as these two screenshots show, and there will be no response when I try to run it again with or without debug.
<img width="433" alt="2017-11-09 21 22 40" src="https://user-images.githubusercontent.com/10494196/32607746-e6918906-c594-11e7-9288-32a5a7a20d09.png">
<img width="435" alt="2017-11-09 21 22 49" src="https://user-images.githubusercontent.com/10494196/32607753-edcd73f6-c594-11e7-8014-67467adfaf65.png">
4. click the debug in status bar and runs it, VS Code returns this:
<img width="438" alt="2017-11-09 21 30 51" src="https://user-images.githubusercontent.com/10494196/32607885-513aa3e6-c595-11e7-8c67-6137817bb38a.png">
5. At last, I have to use cmd+Q to quit Code and restart it

Reproduces without extensions: Yes/No

**Comment by GreenLong** [comment]
I have same problem.

VSCode Version: 1.18
OS Version: Windows 10

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#35
