### ISSUE TITLE
It is possible configure to open one terminal for each folder of workspace?

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#37945]
I want configure my workspace to open one terminal (it would be nice to be create alias) for each folder added in my workspace.
It would be interesting switch the terminal when switch the folder of workspace.
It is possible?
I not found it inside documentation or on "issues" here.

Thanks!

**Comment by fabiospampinato** [comment]
It should be possible to implement this via an extension, I'm not aware of any existent one that does exactly what you want though.

You might want to try my [Terminals](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) extension instead. It's possible to configure it in such a way that it automatically opens one terminal instance for each root you have and it automatically closes all terminals associated with a root if you remove it from your workspace. If you execute commands through it you also get the `switch the terminal` part, but that doesn't happen automatically.

**Comment by cwberick** [comment]
@fabiospampinato thanks for you answer..
I go to test this extension.
