### ISSUE TITLE
Test debugging in python using pythonVScode stopped working upon removal of command 'vscode.startDebug'

### ISSUE THREAD

**Issue by pscelzamelo** [Microsoft/vscode#37948]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
vscode-standardjs|che|1.2.0
githistory|don|0.2.3
python|don|0.7.0
preview-vscode|sea|1.4.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please report this against the Python extension your are using.
