### ISSUE TITLE
Errors invoking VSCode from external application when debugging

### ISSUE THREAD

**Issue by GSThornton** [Microsoft/vscode#37944]
Hi,

I'm working on the integration of VSCode with Unreal Engine, specifically our source code navigation systems. I've found a problem where I have build and run the editor through VSCode, but then subsequent attempts to open a class from the editor, or navigate to a particular file/line will fail with an error message in VSCode like this:

```
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/graemethornton/Epic Games/UE4'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

```

Note that in this case, the arguments to VSCode that I passed on the command line were these:

```
"/Users/graemethornton/Epic Games/UE4/" "/Users/graemethornton/Epic Games/UE4/EngineTest/Source/EngineTest/EngineTestUtilityLibrary.h" "/Users/graemethornton/Epic Games/UE4/EngineTest/Source/EngineTest/EngineTestUtilityLibrary.cpp"
```

This only happens when I'm running the editor as a debug session from within VSCode. If I just launch the editor from the OS and then do exactly the same thing, it all works correctly.

Any ideas?

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.0
csharp|ms-|1.13.0
mono-debug|ms-|0.15.8
perforce|sle|2.2.2
vscode-lldb|vad|0.7.1

**Comment by weinand** [comment]
How does your launch config for the editor look like?

**Comment by GSThornton** [comment]
```
{
	"name": "EngineTestEditor (Development)",
	"request": "launch",
	"preLaunchTask": "EngineTestEditor Mac Development Build",
	"program": "/Users/graemethornton/Epic Games/UE4/Engine/Binaries/Mac/UE4Editor.app/Contents/MacOS/UE4Editor",
	"args": [
		"EngineTest"
	],
	"cwd": "/Users/graemethornton/Epic Games/UE4",
	"type": "lldb"
}
```

**Comment by weinand** [comment]
Please report this issue against the "lldb" debugger extension (which is not part of VS Code).
