### ISSUE TITLE
[Feature Request] Split buttons into 2 lines may better when workbench is too narrow

### ISSUE THREAD

**Issue by specter119** [Microsoft/vscode#37941]
- VSCode Version:  1.18.0 stable
- OS Version: Win10 64bit  Build 15063

Steps to Reproduce:

1. "workbench.panel.location": "right",
1.  decrease the width of the workbench

you will see `terminal`,`output` ...  shrink into `...`, I think they should always be shown. then how about splitting the buttons into 2 lines when the workbench is too narrow?

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Thanks for your suggestion. However we have really thought through the current design and we believe it is a better solution to what you have proposed. Also we do not wrap anything in two lines in other places in our UX so it would not be consistent.
