### ISSUE TITLE
Each workspace folder should be able to set shell type.

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#37952]
Steps to Reproduce:

1. In terminal you hit plus symbol (in workspace project)
2. The command palette shows the folders
3. It only uses a default shell type. Folders should be able to override this in folder settings.

So, if I have a front end in Vue or Angular I should be able to set the shell type for that in the folder settings. But, that setting may or may not be appropriate for a folder where I develop shell scripts for deployment and admin on a windows system. That folder should be able to be set as PowerShell without impacting any of the other folders.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
You can set `terminal.integrated.shell.<platform>` in the workspace settings of a folder (.vscode/settings.json), I think this allows you to accomplish what you're after.

**Comment by sosensible** [comment]
I have a folder in a dev directory where the common powershell scripts are stored. It is a folder within my workspace. I see the .vscode folder and it contains a settings.json with the following JSON.

`{
	"settings": {
		"terminal.integrated.shell.windows": "c:\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"
	}
}`

When I go to the "terminal" and select the (+) it gives me options to select from any of the workspace folders to start a terminal for that folder. It does not open powershell, it opens the default cmd.
