### ISSUE TITLE
Integrated terminal rendering underscore as spaces.

### ISSUE THREAD

**Issue by HarshitOnGitHub** [Microsoft/vscode#37959]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
python|don|0.7.0

---

Steps to Reproduce:

1. Open integrated terminal.
2. Type something having underscore like `git checkout Issue_7045`, it will render like this:
![image](https://user-images.githubusercontent.com/16687990/32614534-7bd1d4fa-c593-11e7-8440-6df0f8f3e096.png)
Although command will execute properly.

Reproduces without extensions: Yes

**Comment by shobhitchittora** [comment]
Can verify that this is not reproducible in OSX.

- VSCode Version: Code 1.18.0 (dcee220, 2017-11-08T12:44:48.751Z)
- OS Version: MacOS High Sierra (10.13.1)
- Extensions: None

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
