### ISSUE TITLE
Blue icon can't be seen in title bar when blue accent color is being used in Windows

### ISSUE THREAD

**Issue by Eldaw** [Microsoft/vscode#37958]
The new blue icon, introduced in 1.18, can't be seen in the title bar when the Windows 10 accent color is set to blue (which I bet lots of people are using). See the screenshot below.

I suggest using 2 colors (blue + black), just like the icon in the Start Menu which doesn't have this problem.

![blue_invisible](https://user-images.githubusercontent.com/3789849/32614275-d03cf2a6-c564-11e7-860b-b54a38d78280.png)

**Comment by KillyMXI** [comment]
Old one with white outline worked fine.
Orange one worked fine.

On mostly dark environment I'd prefer white outline.

_Personally, I'm fine with orange and would've prefer if you insisted on keeping orange color despite initial kickback._

**Comment by reduckted** [comment]
Here's a bit of extra information. You probably don't encounter this problem unless you've got this specific Windows color setting turned on:

![image](https://user-images.githubusercontent.com/10321525/32638733-7244f5e2-c60c-11e7-85e6-3f40ffc84a69.png)

When VS Code is unfocused, it's OK:
![image](https://user-images.githubusercontent.com/10321525/32638747-81a4cd6e-c60c-11e7-8d53-93ca9e392fe5.png)

But when VS has the focus, you can't see it:
![image](https://user-images.githubusercontent.com/10321525/32638806-b424ef8a-c60c-11e7-84ae-7231fc10ac1d.png)


If I remember correctly, the original blue icon had a small white outline around the logo, and was also filled with white. I'm not sure you could really fill the new one (there's only one closed section), but it should be possible to add a small white outline to it to make it stand out more.

Here it is on the taskbar (next to VS 2017):
![image](https://user-images.githubusercontent.com/10321525/32638637-f7263a7e-c60b-11e7-81e6-3d441cddeeef.png)

I think it looks OK as-is on the taskbar (and matches VS 2017 nicely), so I don't think it needs a white outline there.

**Comment by KillyMXI** [comment]
Worst case for taskbar:
![](https://i.imgur.com/Xo4HvUt.png)
![](https://i.imgur.com/B7RTM5S.png)
Normally I'm using Navy Blue and transparency on. So it looks like this for me:
![](https://i.imgur.com/qzazOwz.png)
Still it was notable change for worse compared to previous icons.

Any mono-colored icon can have it's own worst case, VS too, it's just happen that blue is kind of default background color. Some ways to increase contrast better be considered for all the icons across product family.

Title bar icon I can barely see:
![](https://i.imgur.com/HY4TAeF.png)
But thankfully I don't need to look for it as often as for taskbar icon.

**Comment by reduckted** [comment]
@KillyMXI Ah, I see what you mean about the taskbar now.

**Comment by katexue-cm** [comment]
I liked the orange one A LOT. In a task bar filled with blue or blue~ish icons it stands out and that was such a nice change. Then they changed it back to blue because people didn't like it.

Now, you know people who don't like it, but how about people who actually like it?

**Comment by bpasero** [comment]
There is currently no plans to change the icons, but thanks for your interest. See also https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by reduckted** [comment]
@bpasero So you don't care that the icon is invisible in the title bar on what's basically a default Windows installation?

**Comment by reduckted** [comment]
The shape of the logo is irrelevant for this discussion. This issue is about the fact that you can't see the logo on a blue title bar. That is all.

**Comment by DanAtkinson** [comment]
~~Great!~~ Now the Code icon is practically indistinguishable from VS2017! 👎 😞 

![image](https://user-images.githubusercontent.com/23440/32679585-d0cbea1a-c65e-11e7-82eb-f49bdd0d83f2.png)

**Comment by badri-n18** [comment]
Seconded. The original icon was perfect. without the white outline around the icon, it is very difficult to see the logo against many colors on the desktop (in windows)
This is a screenshot of my desktop. the new logo is barely visible against my wallpaper:

![screenshot 1](https://user-images.githubusercontent.com/19945637/32691376-ab2a9aee-c72c-11e7-90c9-d0e3d2e2d3ff.png)

**Comment by martinwilkerson-scisys** [comment]
This also affects Windows 7's taskbar when the icon overlays a correctly coloured bit of desktop background. It happens for me with the default win 7 background, the icon is before VS2015's:
![vs-code-icon-not-visible](https://user-images.githubusercontent.com/22169186/32718642-99f34422-c855-11e7-81ef-ac6550b8a078.png)

A white border like it used to have, or anything to give it some contrast against whatever colour background, would be extremely useful.

**Comment by mhco** [comment]
@bpasero This is a problem for people still on Windows. Even discounting the status bar thing, it's very difficult to see on the task bar in Windows 7. How can you say this is fine?

![vscode-icon-problem](https://user-images.githubusercontent.com/18172927/32746330-5094a978-c883-11e7-8c24-18ce283f52ed.PNG)
![vscode-icon-problem-hover](https://user-images.githubusercontent.com/18172927/32746331-509ef752-c883-11e7-86a8-e078915c27d0.PNG)
