### ISSUE TITLE
The display in terminal bar becomes strange after updating to 1.18

### ISSUE THREAD

**Issue by csy530216** [Microsoft/vscode#37956]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-98-generic

Steps to Reproduce:

1. Open Code
2. The terminal font becomes strange:
![image](https://user-images.githubusercontent.com/14756235/32613633-68c9154a-c5a6-11e7-962d-457b47e4d5a7.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Can you share your settings.json file? Also do you know if you upgraded from 1.17 or 1.16?

**Comment by csy530216** [comment]
I upgraded from 1.17.
The settings of integrated terminal is as follows:
```
  "terminal.integrated.shell.linux": "/bin/bash",
  "terminal.integrated.shellArgs.linux": [],
  "terminal.integrated.shell.osx": "/bin/bash",
  "terminal.integrated.shellArgs.osx": [
    "-l"
  ],
  "terminal.integrated.shell.windows": "cmd.exe",
  "terminal.integrated.shellArgs.windows": [],
  "terminal.integrated.rightClickCopyPaste": false,
  "terminal.integrated.fontFamily": "",
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.lineHeight": 1,
  "terminal.integrated.enableBold": true,
  "terminal.integrated.cursorBlinking": false,
  "terminal.integrated.cursorStyle": "block",
  "terminal.integrated.scrollback": 1000,
  "terminal.integrated.setLocaleVariables": false,
  "terminal.integrated.cwd": "",
  "terminal.integrated.confirmOnExit": false,
  "terminal.integrated.commandsToSkipShell": [
(omitted)
  ],
  "terminal.integrated.env.osx": {},
  "terminal.integrated.env.linux": {},
  "terminal.integrated.env.windows": {},
```

**Comment by csy530216** [comment]
It seems that the default setting 
```
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"
```
does not work properly on my computer. After I change it to
```
"editor.fontFamily": "Consolas, 'Courier New', monospace"
```
the problem is fixed.

**Comment by Tyriar** [comment]
My guess is there's a bad font on your system, since selecting another one fixed the issue. Anyway closing this off as you've resolved the problem.
