### ISSUE TITLE
Developer Tools don't load

### ISSUE THREAD

**Issue by torn4dom4n** [Microsoft/vscode#37951]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.14
cpptools|ms-|0.14.0
vscode-icons|rob|7.17.0
latex-support|tor|1.2.1
snippets-support|tor|0.2.0

---

![image](https://user-images.githubusercontent.com/27698189/32611980-9aff5a40-c599-11e7-8a28-c96e328dacbb.png)

Steps to Reproduce:

1. Open `VSCode` > `Help` > `Toggle Developer Tools`.
2. Click `workbench.main.js` to view in `Sources` but it doesn't show.

**Comment by bpasero** [comment]
This is not under our control.
