### ISSUE TITLE
Provide a mechanism to track explorer sidebar extensions and to disable them

### ISSUE THREAD

**Issue by farcaller** [Microsoft/vscode#37950]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0

Reproduces without extensions: No

Some of the extensions provide additional panels in the explorer. This is how my new VSCode window looks now:
![image](https://user-images.githubusercontent.com/693/32611573-f1e03ae6-c55d-11e7-8d84-a3d2dba38479.png)

The problem I'm having is that I have a docker extension installed only for syntax highlighting, but it forces its panel everywhere, and I have to turn it manually in each window. I'd like to see something like "Disable Always".

The other problem is that it's not possible to go from a panel to whatever extension provides it. Notice how I have two outlines: one is "Code Outline" coming from a good functional extension, the other is "Code outline" and i couldn't yet figure where did I get that one. Something like "Show Extension" in the context menu would help a lot to track those.

**Comment by fabiospampinato** [comment]
I'd love the ability to disable any kind of section **forever**. Those "Commits" and "Compare Commits" sections, **which I've never seen non-empty**, are driving me nuts.

Ps. You can hide Docker's section with `"docker.showExplorer": false`.

**Comment by pltrant** [comment]
Not that I disagree with an override setting, but the ability to permanently disable custom views should be handled by the extension itself through an extension setting.  You may want to provide feedback to said authors as a way to address this problem.

**Comment by farcaller** [comment]
> the ability to permanently disable custom views should be handled by the extension itself through an extension setting

I might agree with that, even though a global easily to find setting would be really better in terms of UX—something that could be exposed via the APIs to the extensions. It's a matter of discoverability, and sometimes it's not even possible to find the offending extension without turning things off one by one (as in my second point on code outline thing).

**Comment by sandy081** [comment]
duplicates #35462
