### ISSUE TITLE
Make Intellisense font and image size adjustable

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#3795]
I was playing around with the `editor.fontSize` setting in VSCode because I am a little nearsighted.
Is there a way to also have the font either inherit the size from the `editor.fontSize` setting or create a new one for it?
 Keep in mind when you scale the font, the images to the left need to be scaled as well.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/2465
