### ISSUE TITLE
[Feature Request] Freely move tabs at the left sidebar

### ISSUE THREAD

**Issue by ThisTNTSquid** [Microsoft/vscode#37953]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro

Requesting new feature:
What I hope it could do: Allow tabs at the left sidebar section to scale and move up and down

What it is doing now: Click the tab, and then it expands with fixed height (which require some trick to expand it to larger by expanding tabs below it then retract them back), if multiple tabs were expanded before retracting, retracting them all is feeling kind of weird.
![Imgur](https://i.imgur.com/ep7Iopk.gif)

**Comment by sandy081** [comment]
@ThisTNTSquid Do you mean to move tabs when they are all collapsed?

**Comment by ThisTNTSquid** [comment]
Both closed and expanded, just like separated expansion cards, you could move them and rearrange them

**Comment by ThisTNTSquid** [comment]
Perhaps I overlooked it, it is actually already here
![image](https://user-images.githubusercontent.com/11581624/32655494-b5572dd2-c648-11e7-8772-b5509f9197c7.png)
