### ISSUE TITLE
Can't open more than one instance when VSCode is run as administrator

### ISSUE THREAD

**Issue by joemaffei** [Microsoft/vscode#37962]
- VSCode Version: 1.19.0-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Run VSCode as administrator (either by right-clicking the icon or setting it as the default in Properties -> Advanced)
2. Try to start another instance, either by choosing "New Window" or "Visual Studio Code - Insiders"

Reproduces without extensions: Yes

It may be worth pointing out that I'm using cmder as my integrated terminal. I have not tried disabling it to see if it fixes the issue but will try that and report back.

**Comment by bpasero** [comment]
@joemaffei does it work if you run from the command line?

**Comment by bpasero** [comment]
I can reproduce:

```
Error: connect EPERM \\.\pipe\ebe3a8355186f99da77237014959374e-1.19.0-insider-main-sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by joaomoreno** [comment]
You have to use different user data directories... We don't support sharing them across users.

**Comment by bpasero** [comment]
@joaomoreno that is unfortunate. If we knew the user was running as admin, we could maybe use a different socket. Or actually we should detect this early enough that we force a different user data directory right from the beginning.

/duplicate 6560
