### ISSUE TITLE
Perl Syntax Highlighting: Issue with highlighting in certain situations when using regex

### ISSUE THREAD

**Issue by chriscapaci** [Microsoft/vscode#37966]
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

1. Download attached file and remove .txt extension so extension is .pl (Perl code)
2. Open file syntax_highlighting_issues.pl in VSCode
3. Observe syntax highlighting (comments explaining what's going on)

NOTE: All usages of regex's in the code are valid as the project I work on contains all of them. Some may be uncommon, but they are valid and work, so highlighting should work with them.

[syntax_highliting_issues.pl.txt](https://github.com/Microsoft/vscode/files/1458564/syntax_highliting_issues.pl.txt)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/perl.tmbundle#27
