### ISSUE TITLE
BUG: On the run task to transpile typescript, never ends task and still pop ups one error

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#37964]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Updated

This bug begined after update VSCode today.

Steps to Reproduce:

1. See the image:
![bug_vscode_20171109](https://user-images.githubusercontent.com/5774595/32617059-21fad2d4-c55b-11e7-98ee-3c87fa623287.gif)

**Comment by cwberick** [comment]
This bug also occurs when I restart task by menu Tasks > Restart Running Task...

**Comment by dbaeumer** [comment]
Dusp #37934.
