### ISSUE TITLE
VSCode SCM has to be case sensitivity (uncompatible with WSL git)

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#37960]
- VSCode Version: 1.18.0
- OS Version: Windows 10 1709 b16299.19

Steps to Reproduce:

1. Create file "foo/test.txt" and commit it to git repository
2. Rename directory "foo" to "FOO"

Expected: Source Control tab show this modification, as "git status" in **WSL terminal**

Actual: Source Control tab did not see this modification, but "git status" (**in WSL terminal**) see. In result we can't fix directory/file letter case bugs via VSCode. Only by command line. But our most sites are on *nix OSes where big/small letters matter...

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
If you change the casing of a file in the Explorer, are you sure `git status` sees it?

I just tried in macOS and Windows, and `git status` doesn't see it. If I change the casing of a file, `git status` won't report that the file has changed.

Can you show me a screen recording?

**Comment by SailorMax** [comment]
Missed additional information: I use WSL in terminal. "git status" in WSL terminal is case sensitivity...
Looks like problem is more complex :)

**Comment by joaomoreno** [comment]
#29812
