### ISSUE TITLE
Microsoft Visual C++ Runtime Library Assertion failed

### ISSUE THREAD

**Issue by ThisTNTSquid** [Microsoft/vscode#37969]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Launch the embedded terminal inside vscode
2. Run some prolonged task (e.g. web servers with express)
3. Terminate the task

Reproduces without extensions: Yes

![Imgur](https://i.imgur.com/G48wqOV.png)

**Comment by CoenraadS** [comment]
I get the same message but I'm not running any tasks. Just changing git branches in bash terminal

**Comment by yoyo837** [comment]
I get the same message.

Please see here. [C++ runtime library error](https://github.com/Microsoft/vscode-tslint/issues/290)

**Comment by abourrier** [comment]
Environment:
- VS Code 1.18.0
- Windows 7 Professional SP1

I get the same message every time I kill an integrated cmd.exe terminal with the trash icon, even when I didn't run any command. I also get an error message from VS Code:
> The terminal process terminated with exit code: 3

I also encounter the following problems:
- The "exit" command freezes the terminal without closing it.
- I cannot use the git-bash.exe terminal anymore (it doesn't launch).
Everything reproduces without any extension.

**Comment by ThisTNTSquid** [comment]
More info: Basically, no matter how you close the integrated terminal, as long as you close it by terminating the task inside, or throw it away with the rubbish bin icon, or what other method, the same error pops up

**Comment by ThisTNTSquid** [comment]
Also, I'm not sure whether I should open a separated issue for this or not, but I found that after updating to the latest version, the tasks running inside the integrated terminal is **no longer possible to terminate** by pressing `Ctrl-C`

I suspect whether this problem came up due to  the same cause or not, but anyways, I decided to report it here since these seemingly 2 problems has caused quite a lot trouble to me
![image](https://user-images.githubusercontent.com/11581624/32654278-97a8ab60-c645-11e7-8815-863242874bb3.png)

**Comment by 0reo27** [comment]
I can confirm that this issue is indeed present. I'm able to replicate this simply by killing the integrated terminal.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37934
