### ISSUE TITLE
FR: Saving list of installed extensions in the settings configuration file

### ISSUE THREAD

**Issue by hunterparks** [Microsoft/vscode#37963]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
material-icon-theme|PKi|2.2.4
python|don|0.7.0
gitlens|eam|6.0.0
tslint|eg2|1.0.14
debugger-for-chrome|msj|3.5.0
tsimporter|pmn|1.2.14
typescript-hero|rbb|1.7.0

---

Steps to Reproduce:

1. When copying the settings JSON file to a new installation of VS Code, a list of installed extensions in that file should allow one to install extensions from the configuration file.

Reproduces without extensions: Yes

**Comment by fabiospampinato** [comment]
This is impossible to implement since multiple extensions can contribute settings under the same key.

You might want to use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) instead.

**Comment by hunterparks** [comment]
Yes, my idea is to store an array of extension by name, not the settings for the extensions. This would allow a quick installation of VS Code extensions that can have their settings changed independently.

**Comment by sandy081** [comment]
@hunterparks I think Settings Sync also sync extensions. Please check it out.
