### ISSUE TITLE
editor.formatOnType breaks indentation

### ISSUE THREAD

**Issue by nelsonlaquet** [Microsoft/vscode#3797]
This is for version 0.10.10, when writing JavaScript.

It appears that setting "editor.formatOnType" to true breaks indentation when you add a newline. What I mean by this is that if you are at the end of a line, and hit "enter", the keyboard cursor will briefly appear at the right indentation level on the new line, but snap back to the line start after about 100 milliseconds.

Setting formatOnType to false fixes this behavior; but, of course, VS Code will no longer format on type. Perhaps whatever code formatter is being used is configured to remove all indentation for empty lines.

The only other custom setting that I have is setting "insertSpaces" to false.

**Comment by massimocode** [comment]
I have the same issue

**Comment by johnwu5** [comment]
Same issue, really annoying.

**Comment by alexandrudima** [comment]
@dbaeumer I will take a look to see if I can "tweak" the format edit if it wants to remove whitespace around the cursor

**Comment by dbaeumer** [comment]
@alexandrudima this is a problem with the tsserver and IMO we should push the TS team to fix this. The corresponding issue in TS land is: https://github.com/Microsoft/TypeScript/issues/6700

**Comment by nsgundy** [comment]
Same issue :+1:

**Comment by alexandrudima** [comment]
@dbaeumer Is this fixed on the TS side on master?

I still get it in some cases such as pressing Enter twice:

![formatontype](https://cloud.githubusercontent.com/assets/5047891/13854171/78b5e13e-ec6a-11e5-9731-45d7dd386921.gif)

**Comment by dbaeumer** [comment]
@alexandrudima it should be fixed and @jrieken and I tested it (I updated the tsserver to 1.8.9 today). But it looks like not all cases are fixed. I opt for opening a issue against TS.

**Comment by skol-pro** [comment]
What's the status regarding that today ?

**Comment by jrieken** [comment]
It's a little big fixed... The true issue is in TypeScript-land and we have refrained from massaging their text edits. @alexandrudima tracks the issue on the TypeScript-side, tho unsure what the status is?

**Comment by heroboy** [comment]
I have to say the formatOnType function is always broken. In most vscode versions , it doesn't work properly. Everytime vscode updated, I turned it on, then some minutes I had to turn it off.

**Comment by egamma** [comment]
The fix for Microsoft/TypeScript#6700 is in the nightly TypeScript build. 

Until VS code adopts a new version you can use a newer version of TypeScript by:

### Install the new typescript version globally:

- `npm install -g typescript@next`
- in the user settings define "typescript.tsdk": "_path to your folder_/node_modules/typescript/lib" 

### Install the new typescript version locally into your workspace:
- `npm install -g typescript@next`
- code will pick it up from there.

The version of the install TypeScript version is shown in the status bar at the right.

**Comment by 4kochi** [comment]
I still have the problem that @alexandrudima described. Using `Version 1.1.0-insider (1.1.0-insider)` and `typescript@1.9.0-dev.20160427`.

![apr -28-2016 09-07-43](https://cloud.githubusercontent.com/assets/1742426/14877986/dde075ca-0d20-11e6-9853-b2702461e3ef.gif)

**Comment by zhengbli** [comment]
That does look like the problem wasn't fixed yet. Thanks for the repo, I'll keep looking.

**Comment by egamma** [comment]
Clearing the milestone, since it is an upstream fix that is planned by another team.

**Comment by alexandrudima** [comment]
@dbaeumer added a workaround for this on our side in PR #6911
