### ISSUE TITLE
[BUG] If you open few folders in vscode, and in git one folder inicializate, you haven't possibility to inicializate another repo.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#37970]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
[Windows 8.1 & Linux Ubuntu 16.04 Gnome]
- Extensions: none
---

Steps to Reproduce:

If you open few folders in vscode, and in git one folder inicializate, you haven't possibility to inicializate another repo.

**Comment by joaomoreno** [comment]
<kbd>Ctrl Shift P</kbd>, `Initialize Repository`.

**Comment by Mlocik97-issues** [comment]
Y, but if I want inicializate, and I'm not using keyboard shortcut? I can't.

**Comment by Mlocik97-issues** [comment]
https://youtu.be/mdM6LNn7Btc


I want have button "inicializate  repo" in Source control panel, also if one folder in workspace is already inicializate (maybe if I want inicializate another folder).

**Comment by joaomoreno** [comment]
You can write an extension with contributes an action on the context menu of folders a command to initialise a git repository on that location. We won't do it, since it pollutes the context menu. There's a global command, and that's enough for us.
