### ISSUE TITLE
js auto-import bug

### ISSUE THREAD

**Issue by dev-fang** [Microsoft/vscode#37974]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Js auto import works well with  
 `export default class className {}`
doesn't work with
`class className{}`
`export default className`

Steps to Reproduce:
1. Create a file called test1.js
2. Type in 
`class Test1{}`
`export default className`
3. Create a file called test2.js
4. Type in new Test1, the auto import suggestion doesn't show up

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19919
