### ISSUE TITLE
Show multi root folders in bold

### ISSUE THREAD

**Issue by delmartechdude** [Microsoft/vscode#37979]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.21
referenceshelper|gay|0.2.1
VS-code-vagrantfile|mar|0.0.7
python|ms-|0.8.0
annotator|ryu|0.10.1
jenkinsfile-support|sec|0.1.0

---

Hi! Thank you so much for adding multi-root workspaces. It would be great if the root of each folder added was bolded or something. If I have folders underneath the second root I add, the font is the same as the files underneath. When you have hundreds of files and folders, this is confusing. Atom does this well by using an icon to the left.

**Comment by itamark** [comment]
Are you sure bolding is the way to go? I wrote something for this - but it still doesn't really stand out
<img width="326" alt="screen shot 2017-11-09 at 9 24 53 pm" src="https://user-images.githubusercontent.com/1757393/32625294-8c5d4132-c594-11e7-9448-846b576342ea.png">

**Comment by delmartechdude** [comment]
@itamark Not sure that bolding is the way to go, but it's better than nothing. An icon or color change, or maybe a box around it or something could be good too. Just anything but what we have now ;) Maybe let's have some UX/UI people chime in?

**Comment by itamark** [comment]
Okay - here's my commit with bold in the meantime. if the spec changes I'd love to take those PRs as well.

**Comment by isidorn** [comment]
@delmartechdude thanks for your feedback. Making the root folders distinct makes sense and we tried to achieve that with a special icon.
In the case where you have icons disabled bold might help. But let's wait and see other user feedback before we do any action.

@bpasero @sandy081 fyi

**Comment by bpasero** [comment]
If any, this could be a setting, but maybe not enabled by default.

**Comment by isidorn** [comment]
Let's wait for more feedback until we do something here.

**Comment by bpasero** [comment]
@jrieken did you ever think about allowing to make the label bold via your decorations API? That would potentially solve it.

**Comment by jrieken** [comment]
> did you ever think about allowing to make the label bold via your decorations API?

Not really, but it's possible

**Comment by delmartechdude** [comment]
@isidorn Thanks for your prompt feedback on all of this. I do not have any icons disabled or anything like that. I have a default install. However, this prompted me to investigate a bit - turns our that the default "vs-seti" iconTheme does not show any distinguishing marks for the root folder, but "minimal" does...as well as other third party icon themes. Is that a bug?

My relevant config:
```
  // Controls if opened editors should show with an icon or not. This requires an icon theme to be enabled as well.
  "workbench.editor.showIcons": true,

  // Specifies the icon theme used in the workbench or 'null' to not show any file icons.
  "workbench.iconTheme": "vs-seti",
```

**Comment by saryeHaddadi** [comment]
Hi, this issue is important for me, I have difficulties working at my easy with workspace because the root forder of each projet doesn't stand out.
It would be nive if we could have a horizontal line delimiting each project. I think this would give me a good experience.

**Comment by waterdrop01** [comment]
totally agree, it's **very** difficult to discern root/top folders when having multiple folders in the same workspace
![vscode multi folders](https://user-images.githubusercontent.com/47316824/127299481-f653cf64-adaa-404e-8de1-2bdeff9d2d90.png)

**Comment by waterdrop01** [comment]
Ok, just installed this [beautiful icon pack](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) and it perfectly solved this issue :)
