### ISSUE TITLE
Tooltip Consistency (very very minor)

### ISSUE THREAD

**Issue by davec21** [Microsoft/vscode#37978]
- VSCode Version:  1.18.0
- OS Version: Windows 10 Build 15063

Steps to Reproduce:

1. Modify an item so that the new git markers appear
2. Hovering over and M or a U has the Modified/Untracked Capitalized
3. Hovering over the dot doesn't have 'contains' Capitalized

This is super minor and I doubt 99% of people would have even noticed.

Reproduces without extensions: Yes

**Comment by itamark** [comment]
Hey @davec21  - hovering over which dot?

**Comment by davec21** [comment]
Just to clarify when I say the dot I mean the one that appears beside the directory with the modified items. The tooltip displays: 'contains emphasized items' which should probably be like 'Contains changed items' or something.

**Comment by itamark** [comment]
Hey yeah I found it - thanks!
