### ISSUE TITLE
VSIX offline installation

### ISSUE THREAD

**Issue by SpontaneousDuck** [Microsoft/vscode#37973]
- VSCode Version: 1.18.0
- OS Version: Win 7 64-bit

Steps to Reproduce:

1. My computer is on a private offline network. 
2. I clean installed VS code 1.18 and downloaded the VISX package for the C/C++ tools plugin from Microsoft.
3. Tried to install from VISX package from the drop-down in the Extension window.
4. Nothing happened. No errors but nothing installed and ~/.vscode/extensions is still empty
5. Reinstalled VS code version 1.16 and was able to use the same method with success of the same VISX package. 

Reproduces without extensions: Yes

**Comment by liangxinhui** [comment]
I got the same problem on Win10 64bit with vscode 1.18.

When i install it in cmd, it shows that maybe some dns error.

```bash
PS E:\software\vscode> code --install-extension E:\software\vscode\ms-python.python-0.8.0.vsix
Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by LouDog105** [comment]
I'm also having the same issue. Does anyone know when this will be fixed?

**Comment by sandy081** [comment]
@LouDog105 It is fixed in insiders.

**Comment by LouDog105** [comment]
@sandy081 Confirmed, thanks!

**Comment by kubaroth** [comment]
I can confirm installation completes on code-insiders but getting another error on Code startup. Any ideas?
```
Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Linux)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
```

**Comment by xeor** [comment]
Anyone know when the `code-insiders` build that fixes this is released? Is it possible to get the `vsix` bundle from code-insiders, just to get this extension in where there are no internet connection?

**Comment by mrkafk** [comment]
Same here for local vscode compilation, on Windows 7 x64, (32-bit) VSCode 1.18.1 on 32-bit node.js v7.10.1.

**Comment by apetitjean** [comment]
To me this issue is not fixed (struggling with this issue for months). 

I've just tried to install the **PowerShell Extension** (_ms-vscode.PowerShell-1.5.1.vsix_) on 2 offline computers and I get the exact same behavior. It silently fails when I install from VISX package from the drop-down in the Extension window.

I tried with vscode x64-1.18.1 (stable) and vscode x64-1.19.0-insider on 2 distinct Windows Server 2008R2 SP1 machines.

I'm on a disconnected network that will never see internet. What could I do?

**Comment by sandy081** [comment]
@apetitjean I wonder it does not work for you in latest insiders. Do you see any errors in consoles, use following commands

- `Developer: Toggle Developer Tools`
- `Developer: Toggle Shared Process`

> To me this issue is not fixed (struggling with this issue for months)

Do you mean, this was not working for you in VS Code versions older than 1.18?

**Comment by apetitjean** [comment]
Hi @sandy081,
Nope, I never succeed to make it work (installing the PowerShell extension offline).

That said, when toggling in developper mode I can see these error messages:
"ERR net::ERR_NAME_NOT_RESOLVED"

Thanks

**Comment by sandy081** [comment]
Ok, then it is not related to this issue. Is it only with Powershell extension or all extension VSIXs?

**Comment by apetitjean** [comment]
I don't know because I haven't try (yet) with another one.

Would you have a workaround to install an extension manually? I did some
tries without luck.

2017-12-12 17:32 GMT+01:00 Sandeep Somavarapu <notifications@github.com>:

**Comment by simulot** [comment]
I have same issue with "Run on Save" extension from emeraldwalk, and  some others.

**Comment by sandy081** [comment]
Please provide the vsix you are trying to install offline.. would like to reproduce it from my side. Thanks.

**Comment by simulot** [comment]
Sure:

https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave
https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run
https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

**Comment by sandy081** [comment]
@simulot First two extensions I could install successfully using VSIXes. As @apetitjean complained, installing power shell extension as VSIX when offline is failing. I know why it is happening. I will filed a separate issue for that - #40722

Thanks for reporting

**Comment by simulot** [comment]
@sandy081 Installation of Run and Save extension has finally worked on my offline machine after having reinstalled vscode latest public version.
Thanks for checking my case.
