### ISSUE TITLE
Integrated Terminal is not Loading editor.fontFamily

### ISSUE THREAD

**Issue by anguspiv** [Microsoft/vscode#37976]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Using zsh with oh-my-zsh, with [Bullet Train Theme](https://github.com/caiogondim/bullet-train.zsh)
2. Set `editor.fonfFamily` to `"'Source Code Pro for Powerline', Menlo, Monaco, 'Courier New`, monospace"`
3. Open Integrated Terminal
4. 
![screenshot 2017-11-09 10 28 48](https://user-images.githubusercontent.com/1724500/32622762-d168f50c-c538-11e7-9ee4-4c5426c6fdba.png)

Note the missing characters, indication of the specified font not being loaded
Compared to my iterm2 output:
<img width="461" alt="screenshot 2017-11-09 10 30 34" src="https://user-images.githubusercontent.com/1724500/32622853-211ae128-c539-11e7-94a2-bddd9648beaf.png">

This has worked correctly in previous versions of VSCode

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
It should pick up the font from `editor.fontFamily` on macOS, provided you don't have `terminal.integrated.fontFamily` defined. Can you share your full settings.json file?

**Comment by anguspiv** [comment]
```
{
    "sync.gist": "a85ca84993f29cc77b1b0a10faa357e5",
    "sync.lastUpload": "2017-08-09T18:25:44.043Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "editor.fontFamily": "'Source Code Pro for Powerline', Menlo, Monaco, 'Courier New', monospace",
    "editor.tabSize": 4,
    "editor.formatOnSave": false,
    "editor.rulers": [
        80,
        100,
        120
    ],
    "editor.renderWhitespace": "boundary",
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,
    "editor.minimap.enabled": true,
    "editor.minimap.renderCharacters": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "html.format.enable": false,
    "slack.teamToken": "/REMOVED FOR SECURITY/",
    "slack.username": "/REMOVED FOR SECURITY/",
    "slack.avatarUrl": "/REMOVED FOR SECURITY/",
    "typescript.format.enable": false,
    "window.zoomLevel": 0,
    "vsicons.projectDetection.autoReload": true,
    "extensions.ignoreRecommendations": false,
    "sync.quietSync": false,
    "sync.askGistName": false,
    "workbench.startupEditor": "welcomePage",
    "workbench.iconTheme": "material-icon-theme",
    "autofold.default": 2,
    "autofold.pack": true,
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/.tmp": true
    },
    "typescript.check.npmIsInstalled": false
}
```

**Comment by anguspiv** [comment]
After resolving this issue: #38248 I am now seeing the correct font load inside the terminal
