### ISSUE TITLE
Unsaved changes warning may overwrite file with 'null'

### ISSUE THREAD

**Issue by nixxquality** [Microsoft/vscode#37971]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.16
vscode-rust|kal|0.4.2
laravel-blade|KTa|0.0.1
Go|luk|0.6.67
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
vscode-coverage-gutters|rya|1.3.0
annotator|ryu|0.10.1
vscode-hexdump|sle|1.6.0

---

I'll start by saying I haven't been able to reproduce this issue after I accidentaly did it, so I'll try to describe the environment I was in.

1. I had a bunch of editors open.
2. One of the editors had unsaved changes.
3. I held Ctrl+W to close all my open editors.
4. The dialog for unsaved changes popped up and I don't remember what option I chose.
5. **Notably**: The unsaved changes dialog popped up a second time (for the same file).
6. After this, VS Code closed entirely.
7. When I opened it back up, the contents of the file had been replaced with `null`.

I tried various things to replicate the issue, but I couldn't do it.
I can sometimes replicate the issue where VS Code window closing entirely, or where it asks about unsaved changes twice.
The keys for either of those issues is having a bunch of open editors, and having them split. With about 5 files per column you start to see weird things happen when you hold Ctrl+W while one file has unsaved changes.

**Comment by bpasero** [comment]
@nixxquality the issue about the save dialog opening twice is https://github.com/Microsoft/vscode/issues/11928

I am trying to reproduce the issue with `null` showing up in the file. Could you ever reproduce that again?

**Comment by nixxquality** [comment]
I tried many times. If I had to guess what causes it, maybe choosing "No" then "Yes" in the save changes dialog is what causes it? Maybe that nulls the unsaved changes variable and then it's written when "Yes" is selecected.
I couldn't reproduce that, though, and it seems like solving the other bug would solve this as well.

**Comment by bpasero** [comment]
Closing until we have reproducible steps.
