### ISSUE TITLE
Unrelated suggestions in Intellisense

### ISSUE THREAD

**Issue by greggb** [Microsoft/vscode#37982]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 
---
Looked to be resolved initially from these issues: #22372, #27899.

I'm able to have these suggestions disappear by toggling `javascript.implicitProjectConfig.checkJs` between true and false and opening a new file, but this doesn't persist through new/existing tabs.

Steps to Reproduce:

1. Using VSCode either with extensions and settings or as a complete clean install
2. Set syntax to javascript
3. type `rcc`
4. Observe intellisense showing additional suggestions

Reproduces without extensions: Yes

I'd like the suggestions to only include things from my files and extensions, and I think this is the intent.

<img width="1136" alt="screen shot 2017-11-09 at 2 23 02 pm" src="https://user-images.githubusercontent.com/514026/32625492-561cc96a-c55a-11e7-9fa2-12cf91702c5d.png">

**Comment by mjbvz** [comment]
I don't think this is the same issue as #27899. These suggestions come from the default standard library. To disable these, create a `jsconfig.json` at the root of your project with the contents:

```json
{
    "compilerOptions": {
        "lib": [
            "es2015"
        ]
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

Now only the standard JS library should be included in your suggestions. [This page](https://www.typescriptlang.org/docs/handbook/compiler-options.html) has more info about the `lib` compiler options

**Comment by greggb** [comment]
Ah, I see, thanks
