### ISSUE TITLE
OmniSharp not working after 1.18.0 update

### ISSUE THREAD

**Issue by officer-tuba** [Microsoft/vscode#37986]
- VSCode Version: 1.18.0
- OS Version: Win7

Steps to Reproduce:

1. enter command: OmniSharp: Select Project
2. message pops up saying "Error spawn UNKNOWN"

tried to reinstall C# extension.
tried to reinstall vscode.
same results.

Reproduces without extensions: N/A

**Comment by anorborg** [comment]
Not sure if its related, but figured I'd post in case: https://github.com/OmniSharp/omnisharp-vscode/issues/1849

**Comment by officer-tuba** [comment]
thanks for the heads up, but it seems unrelated at this point.
...but only because the symptoms I'm seeing aren't specific to omnisharp after all.
