### ISSUE TITLE
[BUG] HTML suggestions / emmet doesn't suggest some new HTML5 tags (like <main>)

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#37987]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
[Windows 8.1 & Linux Ubuntu 16.04 Gnome 3]
- Extensions: none
---

Steps to Reproduce:
![screenshot_8](https://user-images.githubusercontent.com/31345346/32626382-710f5e7e-c58f-11e7-87a3-a345aab1a5d7.png)

**Comment by ramya-rao-a** [comment]
Then `main` abbreviation will be available in Monday's Insiders build.
