### ISSUE TITLE
Javascript Parameters with properties and Intellisense

### ISSUE THREAD

**Issue by Beng89** [Microsoft/vscode#3798]
Currently intellisense does not detect parameter properties see [http://usejsdoc.org/tags-param.html](url) for details.

![not-working](https://cloud.githubusercontent.com/assets/5748243/13590266/014821a2-e4a4-11e5-9d75-d75d00b6b639.PNG)

Is this something that support will be added for?

**Comment by egamma** [comment]
This is a valide feature request, moving to TypeScript.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7429
