### ISSUE TITLE
Allow arrow keys to close terminal

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#37983]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Run a task which uses terminal
2. `Terminal will be reused by tasks, press any key to close it`
3. Press arrow keys (pressing up arrow because I want to reused last command)
4. Terminal doesn't close

**Comment by moguzozcan** [comment]
Hello, 
Is this issue assigned to anyone, if it is ok, I can work on this topic. Also, some hints would be great. Thank you.

**Comment by ychi** [comment]
Arrows don't work on Mac either. Looks like keys with ascii code between 32 and 126 will work.
