### ISSUE TITLE
Cannot see underscores in terminal window on Linux

### ISSUE THREAD

**Issue by sw-carlin** [Microsoft/vscode#37989]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0

Steps to Reproduce:
1. Open terminal on Linux
2. Type an underscore _

I tried reproducing this on Windows, both in Powershell and Linux Subsystem and was unable to do so.

Reproduces without extensions: Yes
![2017-11-09 11_50_27-amp_default_1502413834383_51592 running - oracle vm virtualbox](https://user-images.githubusercontent.com/27784780/32626493-5853700a-c544-11e7-9204-949dc6b9af63.jpg)

**Comment by CoenraadS** [comment]
https://github.com/Microsoft/vscode/issues/35901

Use `terminal.integrated.fontSize": 13` as a workaround
