### ISSUE TITLE
autoimport should care about semicolons

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#37991]
i usually write my ts/js code without semicolons and there is now way to configure vscode to avoid adding semicolons to auto imports. it would be nice an automatic parsing of the tslint config or at least a configurable option in the settings.

- VSCode Version: 1.18
- OS Version: Linux

Steps to Reproduce:

1. use new autoimport feature
2. imports are always with semicolons

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19882
