### ISSUE TITLE
No custom tree views seem to work?

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#37999]
I've tried the examples from https://github.com/Microsoft/vscode-extension-samples, the zip viewer plugin from the marketplace and I've been trying to write my own.

They expand and collapse a bit, but there is nothing in them?

<img width="447" alt="treeview-fail" src="https://user-images.githubusercontent.com/376658/32633376-29981e2c-c59f-11e7-8fbe-11938a24b627.png">

This seems to be the same in the latest Insiders, 1.17 and 1.18.

**Comment by sandy081** [comment]
There are bunch of extensions contributing custom views and they seems to work. Please check your implementation.

**Comment by Gruntfuggly** [comment]
When you say the seem to work, have you actually tried them? It's not just my implementation that doesn't work. 

When I try the node dependencies example from the samples, the view appears in the explorer, but it is empty.

The JSON outline sample becomes visible when I open a json file, but the contents are empty.

The zip file explorer from the marketplace does the same.

**Comment by Gruntfuggly** [comment]
I found the code outline viewer which does work. Maybe the sample extensions and the zip extension are out of date?
