### ISSUE TITLE
Invisible to macOS window server

### ISSUE THREAD

**Issue by ksmithbaylor** [Microsoft/vscode#37993]
When starting VS Code normally via the macOS Dock, the "running" indicator appears briefly and then disappears. No UI is ever shown.

When starting VS Code with the CLI (`code .`), the Dock "running" indicator appears and then disappears just like when I start it via the Dock, but the UI _does_ appear. I can interact with the UI as normal with the mouse, but all keyboard input goes to the previously-focused window. In addition, the menu bar shows the previously-focused window.

It's as if the OS doesn't know the process is running and it can't properly respond to window focus events or keyboard input. This may very well be an Electron issue, but I thought the best first place to post this was here.

When starting VS Code with `code --disable-extensions`, the UI does not appear at all. It's the same behavior as starting it from the Dock.

The immediate crash happened in 1.17 too, but as I had a lot of work to do I just switched back to vim for a while instead of digging deeper.

Strangely, I was using VS Code 1.18 normally for a few hours earlier today with no issues.

I've made a [screen recording](https://youtu.be/0sRUDb7eqwc) of the issue as well. I'm happy to provide any further details to help track this down!

- VSCode Version: 1.18
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Start VS Code via the Dock
    - This causes an immediate crash with no visible UI.
2. Start VS Code via the CLI
    - This causes the strangely non-interactive UI to appear as described above.

Reproduces without extensions: Yes, though just the crash (not the weird UI)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Closing until further info is provided.

**Comment by ksmithbaylor** [comment]
@bpasero Unfortunately, I've been unable to reproduce this issue lately. The one time it happened a few months ago, my computer had not been rebooted in a few weeks, as was the case when I posted this issue. I will keep using VSCode and if I see it again I will report back here after trying the insider build.
