### ISSUE TITLE
Copy and Paste no Longer Work in Latest Version in macOS

### ISSUE THREAD

**Issue by anguspiv** [Microsoft/vscode#37995]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open a file
2. Select/Highlight text
3. Attempt to copy the text
   * ⌘-c
   * Right click -> copy
4. Attempt to paste into another doc

1. Copy Text from another file
2. Open a file in vscode
3. Attempt to paste the code (⌘-v)
   Nothing is pasted into the document

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I cannot reproduce given the steps, but this is not the first report of the clipboard not working. 

Possibly similar problem #37430

**Comment by anguspiv** [comment]
I can't seem to reproduce either, copy and paste was suddenly working for me the next day? But I am having other intermitent issues that I will report soon, and link to.

**Comment by alexandrudima** [comment]
@anguspiv Let's continue tracking in #37430 in this case. Please comment with any possible steps you have. Perhaps it is a series of steps involving other software besides VS Code that leads to the clipboard not working as expected.
