### ISSUE TITLE
1.18.0  All "Task" functionality broken

### ISSUE THREAD

**Issue by officer-tuba** [Microsoft/vscode#37994]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:

Clicking any of the following menu items from the "Tasks" menu:
Run Task
Run Build Task
Configure Tasks
Configure Default Build Task
...results in nothing but an output message, "Error: spawn UNKNOWN"

I originally posted this under Issue #37986, but the scope of the problem seems to be much bigger than I thought at the time.

Reproduces without extensions: **Yes**

Edit: just want to add that the symptoms persist after a fresh install.

**Comment by roblourens** [comment]
If these commands are activating an extension that does a search, or search is involved some other way, then this would be #37863.

Since it's 32-bit Windows, and the error is the same, my gut says it's the same issue.

**Comment by officer-tuba** [comment]
@roblourens, yes this turned out to be the same root cause. resolved with your rg.exe 32 bit replacement.
thanks!

**Comment by roblourens** [comment]
Thanks for trying that. It will be fixed for real in the next Insiders update or stable update.
