### ISSUE TITLE
MAKE ICON LIGHTWEIGHT

### ISSUE THREAD

**Issue by MishUshakov** [Microsoft/vscode#37996]
Hey guys, I don't like the new logo, even a blue color doesn't fix it. On Mac it looks like a old and heavy photoshop icon. The Visual Studio code is a simple and lightweight solution, so please guys, make the accent on that.

- VSCode Version: the latest
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Look at the Dock

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
I don' know what you mean with latest version, so maybe you are using 1.17 with the orange icon. For that I refer to the blog post [The Icon Journey](https://code.visualstudio.com/blogs/2017/10/24/theicon).

**Comment by isidorn** [comment]
@maxibanki as pointed out please refer to the blog post

**Comment by badri-n18** [comment]
as pointed out by @MishUshakov, blue color doesn't exactly solve the issue. The original icon was perfect. without the white outline around the icon, it is very difficult to see the logo against many colors on the desktop (in windows)
![screenshot 1](https://user-images.githubusercontent.com/19945637/32691376-ab2a9aee-c72c-11e7-90c9-d0e3d2e2d3ff.png)
.
