### ISSUE TITLE
Markdown preview does not handle links with parentheses 

### ISSUE THREAD

**Issue by dend** [Microsoft/vscode#380]
The Common Markdown spec covers the possibility of having links with parentheses (which should be considered valid links regardless).

Here is an example where the preview engine in VSCode mis-renders those:
![image3](https://cloud.githubusercontent.com/assets/1389609/11311743/8662bd8e-8f86-11e5-932f-885b5f6d7103.png)

**Comment by jepessen** [comment]
http://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses

**Comment by dend** [comment]
@jepessen SO actually fixed that and inline p-based links are now rendered properly there.

**Comment by bpasero** [comment]
@dend We are using https://github.com/chjj/marked to render the preview, can I ask you to file the bug there?

**Comment by bpasero** [comment]
Btw :+1: for the workarounds in that SO thread, seems to work nicely also for VS Code.

**Comment by dend** [comment]
Sure, will open a bug there :)

As for workarounds - sure, they work. But these are workarounds rather than a robust solution.

**Comment by bpasero** [comment]
Thanks.
