### ISSUE TITLE
Terminal sidebar close button not visible

### ISSUE THREAD

**Issue by BenjaVR** [Microsoft/vscode#38009]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
django-snippets|bib|1.1.0
vscode-styled-jsx|bla|0.1.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
gitlens|eam|6.0.0
tslint|eg2|1.0.16
vscode-npm-script|eg2|0.3.3
vsc-material-theme|Equ|1.1.1
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
beautify|Hoo|1.1.1
intellij-idea-keybindings|k--|0.2.16
vscode-github|Kni|0.23.0
MagicPython|mag|1.0.12
Kotlin|mat|1.3.0
HTMLHint|mka|0.4.0
vscode-apache|mrm|1.1.1
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.0
PowerShell|ms-|1.5.0
typescript-javascript-grammar|ms-|0.0.24
material-icon-theme|PKi|2.2.4
vscode-template-literal-editor|pli|0.8.4
java|red|0.14.0
vscode-icons|rob|7.17.0
prettier-eslint-vscode|Rob|0.7.1
code-settings-sync|Sha|2.8.5
shader|sle|1.1.2
twig|wha|1.0.2
jinja|who|0.0.8
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1. Put the terminal panel to the sidebar.
2. Make that window smaller.
3. Close button is not visible, and not reachable in any way.
![image](https://user-images.githubusercontent.com/17981138/32637934-40bdf3aa-c582-11e7-99fa-3eddda4d0695.png)
As you see here, the 'X' button should be in the upper right.

Reproduces without extensions: **Yes**

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37242
