### ISSUE TITLE
MSSQL queries not supported

### ISSUE THREAD

**Issue by mhokanson** [Microsoft/vscode#38004]
After the last update of VSCode I'm unable to execute queries against an MSSQL database using the MSSQL extension.

- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

1. Open a new tab in VSCode
2. Set the Language Mode to SQL
3. Connect to a MSSQL database
4. Write a valid query
5. Run code
6. View the Info bar stating "Code language not supported or defined."

Reproduces without extensions: No - you can't connect to a database without the MSSQL extension

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
