### ISSUE TITLE
Alt+F S no longer a single action

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#38006]
in 1.18

![image](https://user-images.githubusercontent.com/1051190/32635902-1cc3e038-c567-11e7-9a2f-3ea42a95e5fb.png)

Should have a separate underscore

**Comment by dirck** [comment]
Gonna second this one right away.  Took me awhile to figure out what was going on (Alt-F-S is a cerbellum macro).

**Comment by SteveALee** [comment]
Open File and Open Workspace still clash in the new release - but I admit they are not mentioned on this ticket

**Comment by willdean** [comment]
Save As and Add Folder to Workspace clash too (Alt-F-A is a long-standing standard for save-as)
