### ISSUE TITLE
SCSS element tags still incorrectly colored

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#38001]
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T08:06:49.288Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.5
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
project-manager|ale|0.23.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.16
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.15
vscode-text-pastry|jkj|1.2.0
Angular2|joh|2.10.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.30.0
Align|ste|0.2.0
ayu|tea|0.8.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I reported this [a while back](https://github.com/Microsoft/vscode/issues/36923).  It was bounced to atom-language-sass and was eventually closed there: https://github.com/atom/language-sass/issues/237
2. Still it persists:

![screen shot 2017-11-09 at 5 59 50 pm](https://user-images.githubusercontent.com/835148/32634192-73043b80-c578-11e7-8101-3d08290216d1.png)

These tags are all incorrectly scoped:

![screen shot 2017-11-09 at 6 05 23 pm](https://user-images.githubusercontent.com/835148/32634245-ab5dce4c-c578-11e7-9a66-42d8fec1fc89.png)

**Comment by aeschli** [comment]
Fixed by 048592897e707b5f57cc51aea3e9e35b224fc7dd
