### ISSUE TITLE
break points conflict with new added feature for in editor source control

### ISSUE THREAD

**Issue by AranDekar** [Microsoft/vscode#38003]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.21
vscode-database|baj|1.2.0
githistory|don|0.2.3
tslint|eg2|1.0.14
vscode-mongodb|ms-|0.0.1
azure-account|ms-|0.1.3
csharp|ms-|1.13.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
We are aware of this limiation. Please search our issue database for margin ux.
Closing as duplicate
