### ISSUE TITLE
Decorators should be able to change font weight and size (bold,italic,etc)

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#38005]
- VSCode Version: 1.18.0
- OS Version: Win10

I'm experimenting with adding semantic highlighting in [cquery](https://www.github.com/jacobdufault/cquery) using the decorator API (`vscode.window.createTextEditorDecorationType` and `vscode.window.activeTextEditor.setDecorations`) after the decoration performance improvements coming in 1.18.

It'd be extremely useful if I could use the decorators to control more aspects of font rendering, such as weight (bold, italic, etc) and size. Right now I can control underline, but I think it is very visually busy.

If a PR would be accepted for this I can investigate contributing one.

![image](https://user-images.githubusercontent.com/356714/32634724-d674b620-c561-11e7-9da1-c886dae8f980.png)

**Comment by alexandrudima** [comment]
Semantic highlighting is something we have on our Roadmap as a stretch goal - https://github.com/Microsoft/vscode/wiki/Roadmap

Semantic tokens should not be represented as decorations. Two objects per token (the current decoration cost) is IMHO simply too much. I would not add anything to enrich decorations now for semantic highlighting purposes, I believe semantic highlighting deserves its own clear API.

**Comment by jacobdufault** [comment]
> Semantic highlighting is something we have on our Roadmap as a stretch goal - https://github.com/Microsoft/vscode/wiki/Roadmap

Yes, I have been monitoring this API, but it has already been 8+ months so I decided to investigate hacking in support. Decorators work well enough for a temporary solution.

> Semantic tokens should not be represented as decorations. Two objects per token (the current decoration cost) is IMHO simply too much. I would not add anything to enrich decorations now for semantic highlighting purposes, I believe semantic highlighting deserves its own clear API.

I agree, but this provides a nice usability win immediately with very little tech debt (albeit at a higher memory cost). Switching to the correct/proper API down the future should be straightforward, as all of the real work is editor independent.

I don't think this improvement is particularity aimed towards semantic highlighting - it makes sense by itself, as it gives extension authors a bit more visual flexibility.

If it would be accepted, I am happy to investigate writing a PR for this.

**Comment by alexandrudima** [comment]
Very well then. 

Bold/Italics can go down the same code paths as [`textDecoration`](https://github.com/Microsoft/vscode/blob/b3648bd4930c82801387533e7b16f0f451878e93/src/vs/vscode.d.ts#L842).

**Comment by alexandrudima** [comment]
Implemented via #39701
