### ISSUE TITLE
Project change in workspace git branch doesn't change

### ISSUE THREAD

**Issue by jimmycarry** [Microsoft/vscode#38016]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
vscode-styled-jsx|bla|0.1.1
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-eslint|dba|1.4.3
python|don|0.7.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.14
vscode-great-icons|emm|2.1.20
vscode-firefox-debug|hbe|0.17.0
node-module-intellisense|lei|1.4.0
MagicPython|mag|1.0.12
azure-account|ms-|0.1.3
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.0
vue|sea|0.4.2
react-beautify|tai|0.3.0
vim|vsc|0.10.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.change project in workspace 
2.but the git  branch doesn't change in vscode bottom bar   In my opinion, the branch should be changed follow the project's branch

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
The status bar is currently showing the selected repository in the SCM view.
