### ISSUE TITLE
"Auto Import for JavaScript and TypeScript" not Inoperative on interface file and jsx file

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#38015]
- VSCode Version:1.18
- OS Version:10.13.1

Steps to Reproduce:

1.i write a interface file  it's  content is  `IGetImgCode.ts`

```javascript
export interface IGetImgCode {
    tpl?: string;
}
```

2.when i use other ts file  , it's not auto import `import {IGetImgCode} from '../../IGetImgCode'`

```javascript

function abc (a: IGetImgCode) {

}

```

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
1. How are you triggering the auto import?
1. What does your project structure look like?
1. Do you have a `tsconfig.json`?
1. If you run `TypeScript: go to project configuration` in both files, does it open the same tsconfig?

**Comment by Lxxyx** [comment]
same issue. Ensure have a tsconfig.json and in same project.

**Comment by mjbvz** [comment]
Closing as we cannot investigate the original issue without more information
