### ISSUE TITLE
syntax highlight not working version 0.10.10

### ISSUE THREAD

**Issue by Mirodil** [Microsoft/vscode#3801]
syntax highlight not working at all, 
"var", "import", "from" and so on

**Comment by XiSmartElf** [comment]
same for me

**Comment by massimocode** [comment]
I have the same issue. Var is not highlighted in JS but it is highlighted in TS.

**Comment by tstpierre** [comment]
#3791

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/3903
