### ISSUE TITLE
1.18  vscode not auto install @types file

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#38014]
- VSCode Version: v1.18
- OS Version:10.13.1

Steps to Reproduce:

1. `npm install  lodash --save`
2.then i use it in  ts file ,but vscode not auto install @types  file 

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Are using the quick fix? We don't install packages automatically, you still have to use the lightbulb to trigger this

**Comment by zhiqiang21** [comment]
when i  use it , not show lightbulb let me trigger it

![image](https://user-images.githubusercontent.com/3990411/32685215-d88cd7e6-c6c7-11e7-9036-3aab98760e8d.png)



![](http://7xs2tr.com1.z0.glb.clouddn.com/zhiqiang21/tirmw.png?imageMogr2/auto-orient/thumbnail/!80p/blur/1x0/quality/75|watermark/2/text/aHR0cHM6Ly9naXRodWIuY29tL3poaXFpYW5nMjE=/font/5b6u6L2v6ZuF6buR/fontsize/400/fill/I0ZBMEMwQw==/dissolve/100/gravity/SouthEast/dx/10/dy/10|imageslim)

**Comment by mjbvz** [comment]
@zhiqiang21 The lightbulb would be on the import itself.

```js
import * as _ from 'lodash'
```

You comment appears to show something different than what you originally reported. Is this the same issue?

**Comment by zhiqiang21** [comment]
#38015  sorry ，i comment wrong issue。this  is my origin question

**Comment by mjbvz** [comment]
For this issue, how are you triggering the quick fix?

**Comment by zhiqiang21** [comment]
yes
