### ISSUE TITLE
lose row focus when ctrl+s save

### ISSUE THREAD

**Issue by cenfun** [Microsoft/vscode#38029]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-view-readme|ans|0.2.1
jshint|dba|0.10.15
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:

1. edit row and ctrl+s save
2. the focus disappears

this is very bad  User Experience, I can NOT continue edit any next row after save 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@cenfun can you share a screenshot?

**Comment by TypedSource** [comment]
i have the same problem,

editing a html template, on ctrl+s for save the auto format happens and the focus on the edited tab is lost. 

on keypressing to continue editing the code, i automatly jump to the end of the file.

there is nothing to see in a screenshot by the way.

scr1: on editing => http://prntscr.com/hjbw66
scr2: after pressing ctrl+s without a cursor focus => http://prntscr.com/hjbwqg
scr3: version info => http://prntscr.com/hjbx0v (no updates available)
