### ISSUE TITLE
Request for filter search preview

### ISSUE THREAD

**Issue by guatedude2** [Microsoft/vscode#38024]
*Feature Request*

It would be nice to have preview when doing file filter search (CMD+P), so that I can see what file I'm trying to look for. Specially nice when having multiple files with the same name under different folders.

**Comment by roblourens** [comment]
You can open the file behind the quickopen popup with the right arrow key (or another key of your choosing). Does that help?

**Comment by guatedude2** [comment]
I was suggesting more of a preview, so if I pressed escape it would go back to how it was before I started the search, and whenever a file is selected it pops open temporarily until I hit enter. Hitting the right arrow opens the file which is not necessarily convenient. Hope that helps explain it. ha

**Comment by roblourens** [comment]
I see. I think this is covered by https://github.com/Microsoft/vscode/issues/12892
