### ISSUE TITLE
Font ligatures not working in Linux...

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#38021]
- VSCode Version: 1.18.0-insider
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Install font with ligature support, like `Iosevka Term`
2. Enable ligatures in settings:

```json
{
  "editor.fontFamily": "'Iosevka Term Light'",
  "editor.fontLigatures": true
}
```

![no ligatures linux](https://user-images.githubusercontent.com/2549985/32642071-356e709a-c615-11e7-8919-c3b5848e1148.png)

Same exact config on macOS:

<img width="528" alt="macos ligatures" src="https://user-images.githubusercontent.com/2549985/32642366-4a35efc4-c617-11e7-95ad-3d86617442ba.png">

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
We aren't doing anything differently based on OS on our side. Font rendering is implemented in Chromium. Can you reproduce by visiting/creating a page such as:

http://jsbin.com/rosewahahe/edit?html,output

If you can create a reproducible case, then please create an issue against Chromium.

**Comment by Panoplos** [comment]
I just realized I had the wrong version ('Term', with no ligatures enabled) of the font installed on the Linux box. :-(

Thanks for the reply.
