### ISSUE TITLE
Add debug.stepInto/Out/Over to terminal.integrated.commandsToSkipShell

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#38023]
- VSCode Version: 1.18.0
- OS Version: Windows 10 FCU

Steps to Reproduce:

1. Install PowerShell Extention
2. Execute command: PowerShell: Open Examples Folder
3. Select DebugTest.ps1
4. Set a breakpoint on line 12
5. In Debug view, select  "PowerShell Launch Current File"
6. Press F5 to start debugging
7. When the debugger breaks, press F10 to step.  

No joy, eh?  Our users are wondering why the heck F10 doesn't step the debugger. Well that's because the PowerShell Integrated Console got focus.  It's the REPL folks use even during debug sessions.  

Now there is no need for PSIC to process F10/Shift+F11/F11.  So can you add these commands to the built-in commandsToSkipShell?

Reproduces without extensions:  N/A but probably - point is this impacts the PowerShell extension and any other debug extension with such a REPL.

**Comment by rkeithhill** [comment]
vscodebot - go home, you're drunk.  I think this is probably best hanlded by @Tyriar  :-)

**Comment by ambrop72** [comment]
I am having an issue that F11 (enter/exit fullscreen) does not work when terminal has focus (VSCode 1.19.0, Linux).

**Comment by rkeithhill** [comment]
The PR that closed this issue adds `step-into` (F11) to the list of commands the terminal should ignore.  We'll just have to wait for 1.20 or try it in an insiders build.
