### ISSUE TITLE
files started opening on active editor tab

### ISSUE THREAD

**Issue by jas99** [Microsoft/vscode#38026]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/1231593/32644830-1cc210f2-c60a-11e7-880b-0b8726cd17a8.gif)

I was trying new multifolder workspaces; and all or sudden this crazy behaviour started happening.
Now if I open simple folder it still persists. I might have to go for fresh install of vscode to fix it; meanwhile let me know if you need more info.

- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: Mac High Sierra 10.13.1 (17B48)

Thx

**Comment by bpasero** [comment]
This should help: `"workbench.editor.enablePreview": false`
