### ISSUE TITLE
Cant re-run grunt tasks since v1.18

### ISSUE THREAD

**Issue by richardbullin** [Microsoft/vscode#38025]
I just upgraded to v1.18 and can no longer re-run a grunt task. This problem did not exist prior to this version. 

The issue only exists if you try to run the same grunt task again, i.e I can run 'task1' once and if I try to run again I cannot but I can run 'task2' but then can't run 'task2' again.

- VSCode Version: 1.18
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Run a grunt task, in this case I'm running one of my grunt tasks called 'cleanAll' which cleans up some folders. This problem exists for any of my grunt tasks though.

![image](https://user-images.githubusercontent.com/11023398/32644416-4f9e3e38-c646-11e7-8af1-8fdba79ec61e.png)

![image](https://user-images.githubusercontent.com/11023398/32644441-7df30d86-c646-11e7-80b9-cdcc96e4c631.png)

![image](https://user-images.githubusercontent.com/11023398/32644493-b8f1a35c-c646-11e7-86d7-b9d0d1e80a75.png)

2. The task runs correctly in the terminal as below

![image](https://user-images.githubusercontent.com/11023398/32644517-da79e1e2-c646-11e7-9a55-3beb98637aa3.png)

3. If I then try to rerun the same grunt task using the above steps 1-2 I get the below message

![image](https://user-images.githubusercontent.com/11023398/32644548-0876f5da-c647-11e7-906b-eff0d1cd4edd.png)

4. If I then click 'Kill Terminal' I get the below assertion failure

![image](https://user-images.githubusercontent.com/11023398/32644570-32c5a89a-c647-11e7-8d49-a4f65e136da3.png)

**Comment by richardbullin** [comment]
Oh finally I get the below error after clicking abort

![image](https://user-images.githubusercontent.com/11023398/32644740-699000d6-c648-11e7-899e-48d6aca5340d.png)

**Comment by dbaeumer** [comment]
Dups #38025
