### ISSUE TITLE
textDocument/definition request spam

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#38020]
Not sure if this is a bug in vscode or vscode-languageserver-node or extension related. When pressing F12 to go to definition the editor will jump correctly to the definition but then spam textDocument/definition requests at the new cursor location. I have seen it happen prior to 1.18 too. See gif below.

- VSCode Version: 1.18
- OS Version: Debian 9

Steps to Reproduce:
Intermittent -- F12 on a method reference

![peek 2017-11-10 13-57](https://user-images.githubusercontent.com/5885195/32641115-5e1fe6d0-c620-11e7-90b4-f57bb5b6c5d0.gif)

**Comment by dbaeumer** [comment]
The LSP only sends requests if it receives a trigger from the editor. 

I tried to reproduce this with a sample LSP extension but was not able to do so. Please file the issue against the extension that provides the functionality.

**Comment by bmewburn** [comment]
@dbaeumer it's doing full round trips from the client to the server as can be seen in the trace below. The only user input is the initial F12 to go to the definition. The extension does have some middleware to forward on requests to other language servers but if I remove so that it's going through the standard vscode-languageserver-node request/response mechanism it still occurs. Do you have any ideas how an extension could be causing this behaviour?

![screenshot from 2017-11-16 11-20-02](https://user-images.githubusercontent.com/5885195/32867470-58590ee8-cac1-11e7-8376-ad2ea61dcaf3.png)

**Comment by dbaeumer** [comment]
The only explanation I could come up with is that someone else triggers this be sending the definition command to VS Code.

If you tailor an example that demos the behavior I can close I will have a look. I tried to reproduce this is my test bed and was not able to do so. 

You could also set a breakpoint into the language client where it forwards the call to the server and see how it gets triggered. The code is around DefinitionFeature in the client.js file.
