### ISSUE TITLE
VSCodeSetup-x64-1.17.0 and VSCodeSetup-x64-1.18.0 installation failing on Windows 7

### ISSUE THREAD

**Issue by vinayjsharma** [Microsoft/vscode#38028]
![vs_errorpng](https://user-images.githubusercontent.com/33538626/32645148-b50f745c-c60b-11e7-9a6c-0dfaaabb029d.png)

- VSCode Version: VSCodeSetup-x64-1.17.0 , VSCodeSetup-x64-1.18.0
- OS Version: Windows 7 Professional Service pack 1

Steps to Reproduce:

1. Run the installer 
2. The message in screenshot start appearing for multiple files in setup and makes it impossible to complete the installation. 
![vs_errorpng](https://user-images.githubusercontent.com/33538626/32645203-15591386-c60c-11e7-9993-b3b03393a649.png)
![vs_install](https://user-images.githubusercontent.com/33538626/32645259-608ad8f8-c60c-11e7-8741-de4af5a0ba4b.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you:

1. Restart your machine
2. Fully uninstall VS Code
3. Fully reinstall VS Code
