### ISSUE TITLE
Changing color of your window borders and taskbar crashes VSCode

### ISSUE THREAD

**Issue by howiempt** [Microsoft/vscode#38034]
- VSCode Version: 1.18.0
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:
1. Open VSCode
2. Open Control Panel > Personalization > Color and Appearance
3. Set Hue/Saturation/Brightness to lowest values.
4. Slide Color intensity to highest value

VSCode crashes.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@howiempt which dialog are you in on Windows, can you share a screenshot?

**Comment by howiempt** [comment]
Dialog below:

![image](https://user-images.githubusercontent.com/13435235/33974791-501f8f4e-e0c5-11e7-86bd-2ebaf515a9ba.png)

Basically just drag the Color intensity bakc and forth very quickly :+1:

**Comment by bpasero** [comment]
@howiempt can you try to reproduce with our newer Windows build: https://az764295.vo.msecnd.net/exploration/ed422f909ea470f79e3e3e39c948803d9b764919/VSCode-win32-x64-1.22.0-exploration.zip

**Comment by howiempt** [comment]
@bpasero unable to reproduce with that build, looks good!
