### ISSUE TITLE
closing others tab shortcut not working

### ISSUE THREAD

**Issue by incubus8** [Microsoft/vscode#38033]
- VSCode Version: 1.18.0
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:
1. Update VSCode to 1.18.0
2. Do work on Javascript / Typescript codes. Open a lot of tabs with two splitted tabs window (shortcut CMD+2)
3. Change to chrome window or anything
4. Put sleep ur MacOS for 60 minutes or so..
5. Wake up your MacOS again and logged in. 
6. Change to VSCode window.
7. Now, try to close `close others tab` by using shortcut `CTRL` + `CMD` + `T`
![screen shot 2017-11-10 at 1 46 48 pm](https://user-images.githubusercontent.com/5300674/32646144-ba68deb8-c61d-11e7-9f7f-e8483eef440e.png)
8. Warn message will show and other opened tabs won't get closed
```
Warn: command 'hie.commands.showType' not found
```

Reproduces without extensions: **YES**

**Comment by incubus8** [comment]
Sorry my bad, this was caused by `gitlens` extension. Closing this issue since not related to VSCode.

**Comment by incubus8** [comment]
I am reopening this issue again, because it is happening again after my MAC sleep then open VsCode again. I can confirm that this is not related to `gitlens` extension. But rather the VSCode extension. 

To fix it, I have to install back gitlens plugin, then uninstall the plugin, after that, `reload` the vscode.

**Comment by incubus8** [comment]
@sandy081 if you have time, please help me on this. it's quite annoying behaviour.

**Comment by sandy081** [comment]
@incubus8 Can you please check what command is bound to that keybinding in your keybindings editor?

**Comment by incubus8** [comment]
My VSCode settings:
```json
// Place your settings in this file to overwrite the default settings
{
    "explorer.openEditors.visible": 0,
    "docker.showExplorer": false,
    "explorer.autoReveal": false,
    "editor.fontSize": 11,
    "editor.renderWhitespace": "all",
    "editor.tabSize": 2,
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Ayu Mirage",
    "editor.minimap.enabled": false,
    "workbench.startupEditor": "newUntitledFile",
    "typescript.npm": "/Users/angel/.nvm/versions/node/v8.5.0/bin/npm",
    "files.exclude": {
        "artifacts/*": true,
        "build": true
    },
    "workbench.editor.enablePreview": false
}
```

Keybindings bound to it, see screenshot
<img width="949" alt="screen shot 2017-11-11 at 9 28 00 am" src="https://user-images.githubusercontent.com/5300674/32685403-e403ae56-c6c2-11e7-8853-c56b29a9528e.png">


This is only happening after I reopened my laptop after 'sleep' state. 

Additional information:
I can do `CMD` + `ALT` + `T` if it were in `Keyboard  Shortcuts` tab (in above screenshot). But I still won't work after I reopened source codes file tab.

**Comment by incubus8** [comment]
@sandy081 oh my god, stupid me. I found there are the same keybindings, one is for haskell extension :(

<img width="967" alt="screen shot 2017-11-11 at 9 35 20 am" src="https://user-images.githubusercontent.com/5300674/32685430-a9a313b8-c6c3-11e7-9acd-5d2582c75f2d.png">
