### ISSUE TITLE
Python: Debug action bar disappeared when started without debugging

### ISSUE THREAD

**Issue by kenixer** [Microsoft/vscode#38036]
- VSCode Version: 1.18.0
- OS Version: macOS High Sierra Version 10.13

Steps to Reproduce:

1. Use shortcut or menu to start without debugging, in python project.
2. Can see script running in debug console, but can't see debug action bar. Also, can't stop process when I click on `stop` menu.

Reproduces without extensions: Yes

**Comment by jbdv-ife** [comment]
If it is of any use, same problem on Windows with:
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601

**Comment by kenixer** [comment]
In my case, this issue started to appear since today. How about you?

By the way, I could also see that integrated terminal's font has changed to minimum. I really want to know what ridiculous thing has happened. There was no vscode update yesterday, right? I could see only the update of python extension. Is it possible for extension to damage vscode?

**Comment by kenixer** [comment]
I'm sure this is a bug. I deleted everything about vscode and made a new fresh-install, but the issue continues. I hope this is not a feature ;)

**Comment by isidorn** [comment]
Please file this against the python extension here https://github.com/DonJayamanne/pythonVSCode
This is not a vscode issue, I tried reproducing with Node debugging and could not.
@kenixer you could also try to reproduce with a simple node program just to prove my claim

**Comment by kenixer** [comment]
Okay, thank you. Then, how can I install this old ver of extention? Looks like installation is only available by vscode extention market.

**Comment by kenixer** [comment]
I installed an extension by `.vsix` and replaced microsoft's one, but the problem continues. :(

**Comment by isidorn** [comment]
@kenixer please file an issue against the python extension and they can provide more details there. It might be that the python extension needs to be updated with repesect to the api changes vscode did but I already informed them about that.
