### ISSUE TITLE
Task Bar Icon and Icon with in Editor are different.

### ISSUE THREAD

**Issue by rathnamvemula** [Microsoft/vscode#38039]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.After installing this version, the Taskbar Icon and icon with in Visual Studio Code Editor are different colors.  
Tasbar icon is Orange, With in Code Editor it is Blue

**Comment by mizutoki79** [comment]
If I use normal size taskbar, correct icon is display.
But small icon in taskbar is old.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
