### ISSUE TITLE
Windows title bar icon disappears when the title bar color is blue

### ISSUE THREAD

**Issue by debuggings** [Microsoft/vscode#38037]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Windows title bar icon disappears when the title bar color is blue

---

Steps to Reproduce:

1. Change the windows Setting > Personal > Color to Blue. (First color tile in the third row)
<img width="532" alt="image" src="https://user-images.githubusercontent.com/668404/32646731-ed53c6f2-c628-11e7-9bde-59e7cd782270.png">

2. Open vscode, and the title bar icon will disappear.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/668404/32646743-fac0860e-c628-11e7-98b6-30c2220dd3c1.png">

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/37958
