### ISSUE TITLE
ts 调试时，有时会莫名其妙的增加了很多的断点，并且这些断点还不能取消，必须先取消所有断点，再重新打开改文档才能使断点消失

### ISSUE THREAD

**Issue by zhoutou3** [Microsoft/vscode#38032]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
vscode-express|Com|0.0.5
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
csharpfixformat|Leo|0.0.39
vscode-html-scss|P-d|0.0.42
ejs-language-support|Qas|0.0.1
code-settings-sync|Sha|2.8.5
ejs-snippets|Tao|0.1.0
Angular2|UVB|0.4.1
html-css-class-completion|Zig|1.14.0
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
Vue2|duc|0.1.3
tslint|eg2|1.0.16
vscode-nupkg|eri|0.0.8
scaffold|fir|1.0.0
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
angular-bootstrap|her|4.0.6
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.4
docthis|joe|0.6.0
Angular2|joh|2.10.0
vscode-csharp-snippets|jor|0.2.0
docomment|k--|0.0.17
Go|luk|0.6.67
HTMLHint|mka|0.4.0
csharp|ms-|1.13.0
mono-debug|ms-|0.15.8
node-debug2|ms-|1.18.3
vetur|oct|0.11.0
ionic2-snippets|oud|1.0.0
rxjs-snippets|pko|0.0.2
vscode-icons|rob|7.17.0
aspnet-helper|sch|0.6.4
vue-vscode-snippets|sdr|1.1.0
autoimport|ste|1.5.3
bootstrap-3-snippets|wcw|0.1.0
swig|zhu|0.0.5

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
> When TS debugging, it is sometimes confusing to add a lot of breakpoints, and these breakpoints can not be canceled, you must first cancel all breakpoints, and then reopen to change the document to make the breakpoint disappear

**Comment by roblourens** [comment]
I think you are describing https://github.com/Microsoft/vscode/issues/37880. Please try in the latest Insiders build or the next stable update.
