### ISSUE TITLE
Moving Folder on windows

### ISSUE THREAD

**Issue by frontthemachine** [Microsoft/vscode#38044]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.16
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.3
beautify|Hoo|1.1.1
vscode-extension-auto-import|mop|1.3.3
vscode-scss|mrm|0.6.2
python|ms-|0.8.0
azure-account|ms-|0.2.0
node-debug2|ms-|1.18.4
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.21
sass-indented|rob|1.4.5
vscode-react-native|vsm|0.5.2
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. move folder A containing folder B containing files to another root. (nothing happens)
2. move B to another root (it works, and then A is moved accordingly to the step 1.
3. sometimes a 'notPermitted' error is thrown after step 2

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
