### ISSUE TITLE
Markdown syntax highlight

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#38049]
- VSCode Version: Code - Insiders 1.19.0-insider (d6fbdcf19716910b26ea81efc95724f2fabe5aa6, 2017-11-10T05:17:03.030Z)
- OS Version: Windows_NT x64 10.0.17035

`[text] (link)` is not a link because of the space between `]` and `(`, so the syntax highlight is not correct.

![image](https://user-images.githubusercontent.com/7588612/32652129-413ea2a4-c63e-11e7-99f4-169a2a77350d.png)

**Comment by maxibanki** [comment]
I think this is as designed. I've tested the markdown interpreter of GitHub, [Stackedit ](https://stackedit.io/editor)and [Dillinger](https://dillinger.io/). I haven't found anything related about this in RFCs etc.

**Comment by shivammittal99** [comment]
Hello, is anybody working on this? I would like to work on this with some help and hints. 
Thank you.

**Comment by maxibanki** [comment]
Hi, the markdown syntax highlighting is managed [here](https://github.com/Microsoft/vscode/tree/master/extensions/markdown) in the corresponding .tmlanguage files afaik. (Most highlighting of other languages is managed via external repos from atom, but from markdown not.) I already tried to fix this issue, but there are very complex regexp as i seen.

**Comment by shivammittal99** [comment]
Yes, I also saw the regexp. I wanted to ask how do I test after changing the regexp.

**Comment by maxibanki** [comment]
Build VS Code from souce, check out the wiki [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute).

**Comment by mjbvz** [comment]
Sorry, #38328 broke things and had to be reverted. Will take a quick look at fixing it up
