### ISSUE TITLE
Sometimes integrated terminal display wrong in version 1.18.0

### ISSUE THREAD

**Issue by zuoez02** [Microsoft/vscode#38043]
- VSCode Version: 1.18.0 dcee2202709a4f223185514b9275aa4229841aa7
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open new window
2. Open integrated terminal.

Reproduces without extensions: Yes

The problem is not reproduced every time. It is looked like the bug in 1.17.0.

Open the new terminal:
![jietu20171110-162509 2x](https://user-images.githubusercontent.com/4801955/32649262-6461608c-c634-11e7-8c46-9c931e56535d.jpg)
And then edit the window's size, it becomes normal
![jietu20171110-162528 2x](https://user-images.githubusercontent.com/4801955/32649314-ae5171fa-c634-11e7-8946-d1670aeb0535.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
