### ISSUE TITLE
0.10.10 erroring on object spread properties in .js files

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode#3804]
… and I can't turn it off by setting `javascript.validate.enable` false. 

Perhaps this is a soft documentation bug: the [release notes](https://code.visualstudio.com/Updates) proudly mention `experimentalObjectRestSpread` but then say:

> Support for ObjectRestSpread is not yet provided by Salsa but it is on the roadmap (see Microsoft/TypeScript#2103).

… which is confusing and misleading.

It's confusing because the stand-out tone of core dev responses to that issue is "not until TC39 moves it to stage 3; bother them, not us", which is much less optimistic than the Feb 2016 release notes or the [TypeScript Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) itself.

It's misleading because it fails to **describe the impact** of "support… not yet provided" as **error messages you can't make go away**. If there's some way to make them go away, please describe it in that part of the release notes. If not, I don't think it's too strong to outright **advise users of object spread properties to delay upgrading**.

Without a work-around, this kills `code` for me, as I now have to dig for the real errors amongst a few dozen erroneous:
- `Property assignment expected.`
- `Argument expression expected.`
- `Declaration or statement expected.`

I trust a workaround is possible, as `code` is not erroring in JSX.

**Comment by kumarharsh** [comment]
+1

**Comment by dlong500** [comment]
I'm happy for the inclusion of the Typescript-based Salsa syntax support, but as @garthk mentions it is an odd situation that we are now in.  ESLint is also very much encouraged in the vscode docs (and I've been using it for quite some time already).

What I don't understand is why we can't have Salsa-based syntax color support (and maybe some other things as well) without forcing the Salsa (Typescript) syntax validation.  It seems to me that if ESLint is to become the standard (or at least recommended) way for validation then there should be a simple way to disable the Salsa/Typescript validation.  Apparently at the moment there is not, **and this is a very serious impediment to productivity**.

The issues with incomplete syntax color coding in past versions is highly preferable to an inability to disable code validation that isn't up to par with current coding conventions.  The musings about specs and javascript stages on the Typescript repo in regards to the object spread operator don't justify a continued lack of support for a feature that is well-established in practice and is supported in Babel.  That's fine if the Typescript devs want to hold back, but now Microsoft is forcing the Typescript opinions on everyone using vscode without an ability to disable it.  I guess I just don't understand why the original `javascript.validate.enable` option can't be used to disable Typescript validation as well.

There really doesn't seem to be a whole lot of noise about it yet, but that's probably because the February release only just came out.  Salsa support in the January release was opt-in, and given the hoops you had to jump through to enable it I'm thinking that not a whole lot of people tried it out.

If I'm missing something then please enlighten me, but I haven't found any workaround yet (not even in the vscode alpha release).

Sorry if it seems like I'm cranky.  I also just spent several hours figuring out that ESLint 2.3.0 breaks all linting in vscode at the moment.

**Comment by josebalius** [comment]
I feel the same way :/ I was looking forward to the Feb release to maybe switch from Atom but this is a blocker for me.

**Comment by egamma** [comment]
@garthk I will change the doc to make this limitation more obvious.

**Comment by egamma** [comment]
We will revive the `javascript.validate.enable` setting Microsoft/vscode#3909.

This will remove the red squiggles, but this will not fix that Salsa doesn't understand these syntactic constructs. This means the code understanding experience is limited, e.g, when it comes to intellisense, go to definition. 

@dlong500 @garthk from this feedback I conclude that these limitations are tolerable as long as the red squiggles do not get in your way. Is this correct?

**Comment by kumarharsh** [comment]
> these limitations are tolerable as long as the red squiggles do not get in your way. Is this correct?

Yes, you *can* say that. That's one major irritant because it's expected that linting run smoothly when transitioning from other editors. Linting and intellisense are separate things (from the user's perspective), and I think it's a more logical tradeoff that we'd lose intellisense support until Salsa comes up to speed.

**Comment by egamma** [comment]
@kumarharsh this explanation makes sense, thanks.

**Comment by josebalius** [comment]
@egamma reviving that setting would be great. I think it allows me to fully switch to vscode :)

**Comment by dlong500** [comment]
How is the intellisense and syntactic recognition of Salsa different from the pre-Salsa engine?  If there isn't much difference then I'm fine with simply disabling Salsa's validation.  However, if there is a big difference would it be possible to have an option to continue to use the pre-Salsa engine for intellisense at least until Salsa matures a bit?

**Comment by garthk** [comment]
@egamma removing the red squiggles and entries in `showErrorsWarnings` (⌘⇧M) will help a great deal, catching `code` back up to `subl` in workability.

FWIW, `goToDeclaration` and `triggerSuggest` are still limping along. Nice work, that.

**Comment by egamma** [comment]
@dlong500 both Salsa and the previous JS infrastructure build on the TypeScript parser and AST. The previous JS infrastructure has the same limitations when it comes to using ES7 language features, but it supported to turn off validation. 

One issue is that the TypeScript version used for the previous JS infrastructure is now really out of date. This is why we need to deprecate it as soon as possible.

 > until Salsa matures a bit?
Do you have particular concerns with regard to the Salsa maturity.

**Comment by egamma** [comment]
@garthk the plan is to bring back the option and it will be in next update in the [`insiders`](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) channel, which we plan to make next week.

**Comment by dlong500** [comment]
> both Salsa and the previous JS infrastructure build on the TypeScript parser and AST. The previous JS infrastructure has the same limitations when it comes to using ES7 language features, but it supported to turn off validation.

Ok, thanks for the clarification.  I just wanted to know if the pre-Salsa intellisense was superior but it sounds like it was the same or worse, so there's no need to keep it around anymore.

> Do you have particular concerns with regard to the Salsa maturity.

Maturity maybe wasn't the best word.  I was referring to the Typescript foundation of Salsa in regards to support for newer ECMAScript features that are already supported by other tools like Babel and ESLint.  I get the desire to be careful with language constructs that may still be in flux, but I think sometimes there is too much hesitation in supporting features that are already used in the wild and are clearly going to be in a future spec one way or another.

In any case, thanks for the quick responses and for the revival of the option to turn off built-in validation.

Quick question:  what is the difference between the insider channel and the alpha channel?  Is the alpha channel always more up-to-date than the insider channel?

**Comment by egamma** [comment]
>Typescript foundation of Salsa in regards to support for newer ECMAScript features that are already supported by other tools like Babel and ESLint.

got it, thans. This topic is discussed here https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-182195915

>Quick question: what is the difference between the insider channel and the alpha channel? Is the alpha channel always more up-to-date than the insider channel?

The alpha channel is updated multiple times a day and it is the version the development team is using. So it might be broken from time to time. The insiders channel is updated one week before a stable update, but we are looking into updating stable more frequently.

**Comment by egamma** [comment]
Given this discussion and the recommendation to install a linter for validation in JS, I'm now wondering whether we should disable the built-in JS diagnostics by default. This will help the ES6+ scenarios and I'm not sure how much an normal JS developer will loose. Any opinions?

**Comment by robcaldecott** [comment]
I'm now on 0.10.11-insiders but no sign of `javascript.validate.enable`. Did it not make the cut?

**Comment by egamma** [comment]
@robcaldecott 

>I'm now on 0.10.11-insiders but no sign of javascript.validate.enable. Did it not make the cut?

the 0.10.11 insiders only includes the same critical fixes that went into stable. We look into pushing another insider update today.

**Comment by egamma** [comment]
FYI the insiders build with the above change is out now https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build

**Comment by robcaldecott** [comment]
Great, `javascript.validate.enable` now works, so goodbye red squiggles in my stage-1 ES7 code. Unfortunately this also stops the ESLint plugin from working. Was this expected?

**Comment by kumarharsh** [comment]
The linter seems to be working, but all the errors are being shown as: `Parsing error: unexpected token (null)`

**Comment by egamma** [comment]
@kumarharsh do you have the eslint parser options configured for JSX/React? See below:

Also the error message should be prefixed with `ESLint`, this has been changed recently. If this is not the case can you update the vscode-eslint extension.

```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
```

**Comment by kumarharsh** [comment]
@egamma updating the plugin fixed it. Actually, not I understood what that error is saying:

The eslint plugin highlights the `~` part on this object:

```
borderTopRightRadius: geometry.input.radius
borderBottomRightRadius: geometry.input.radius,
~~~~~~~~~~~~~~~~~~~~
```

with the error:
```
parsing error: unexpected token (null)
```

I thought this was a because maybe the eslint plugin was throwing an error due to some internal error, but it is trying to find an eslint rule **matching** the missing `comma` and finds nothing, so it outputs `(null)`. Maybe that's something which can be fixed?

**Comment by egamma** [comment]
The vscode extension shows the message it gets from eslint and when there is a rule then it is shown

![image](https://cloud.githubusercontent.com/assets/172399/13848259/4972d788-ec51-11e5-8193-a64b646b2548.png)

There is no rule for parsing errors and this is why eslint shows (null), which is not very friendly... 

![image](https://cloud.githubusercontent.com/assets/172399/13848320/84fc02ca-ec51-11e5-8b29-e513e63045c6.png)

I suggest to file an issue against the eslint repo

**Comment by garthk** [comment]
I already gave a thumbs on on the change being available in Insiders, but came back especially to call out the March 2016 release note content on this issue. Well writ, @egamma and @gregvanl. Thanks.

I'm full time on Insiders. It's looking good.  `javascript.validate.enable` was all I needed. Thanks for turning that around so fast.

**Comment by frogcjn** [comment]
1.2.0 still has this problems?
```
const Button = (props, { theme }) => {
  const styles = getStyles(props, { ...config, ...theme });
}
```
[js] Property assignment expected.

**Comment by kumarharsh** [comment]
@frogcjn I'm sorry but I'm not getting this issue at all. Haven't gotten this issue after fixing up these issues:
1. Open the folder with the eslint module in the node_modules folder **directly under the *root* folder**.
2. Put the proper `jsconfig.json`
Here's mine:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2015",
    "experimentalDecorators": true
  },
  "exclude": ["node_modules", "scripts"]
}
```

**Comment by frogcjn** [comment]
@kumarharsh 
Could you tell me what is your typescript version?

**Comment by kumarharsh** [comment]
@frogcjn yes, you'll need to turn off `javascript.validate.enable` flag, only then will eslint be able to properly lint your files.

**Comment by frogcjn** [comment]
@kumarharsh, so the VSCode should improve on this.

**Comment by kumarharsh** [comment]
Yes, I think that has been clarified by the vscode dev team time and again. Salsa does not have es7 features, but will get it later (most probably in this year). Anyways, disabling salsa does not take away too much from the experience - the intellisense still works okay (without some features), and even gives great cross-file suggestions like say I imported constants from a 'utils/constants' file, then intellisense shows those constants in suggestions, etc.

**Comment by mjbvz** [comment]
We just picked up a new release of TypeScript (2.1.4-insiders) that I believes fixes this. You can try this out in the current VSCode insiders build (2016-12-05T07:03:07.371Z) and it will also be going in to VSCode 1.8.  

![screen shot 2016-12-05 at 4 15 31 pm](https://cloud.githubusercontent.com/assets/12821956/20907927/2ba824cc-bb06-11e6-8e8f-1be1961ba1a9.png)

Please give the latest insiders builds a try and let us know if you run into any trouble or notice any problems.

Thanks

**Comment by lizhiyao** [comment]
I found that  Object Spread/Rest not supported in .vue files.

![.vue files](https://cloud.githubusercontent.com/assets/8143023/21979000/112ee59e-dc18-11e6-885a-531f890e417e.png)

**Comment by zoltanzf** [comment]
Regarding the .vue files object/rest support the [Vue Component](https://marketplace.visualstudio.com/items?itemName=seanwash.vue) extension may help.

As I see the .vue files are recognized as HTML by vscode so the HTML syntax need to be extended with object rest/spread support.

**Comment by tforssander** [comment]
@zoltanzf Thanks for the tip, this issue have been bugging me for a while!

**Comment by lizhiyao** [comment]
My solution is [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

**Comment by ronjouch** [comment]
> My solution is [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur).

@lizhiyao vetur works for you? How? (Any particular setup / are you sure you didn't just disable JS validation?) I just tried it with a fresh profile on 1.8.1 and today's 1.9.0-insider, and I still get a `Property assignment expected` JS validation error (hence bug #19629 that I just reported)

**Comment by lizhiyao** [comment]
vs code version: 1.8.1
vetur version: 0.3.0

in my `settings.json`:

```
{
    "files.associations": {
        "*.vue": "vue"
    }
}
```
