### ISSUE TITLE
保存文件之后，鼠标的光标会跑到文件的最底部去了。

### ISSUE THREAD

**Issue by MDGSF** [Microsoft/vscode#38046]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
githistory|don|0.2.3
vscode-html-css|ecm|0.1.8
code-runner|for|0.8.3
beautify|Hoo|1.1.1
Go|luk|0.6.67
Angular-BeastCode|Mik|5.0.14
python|ms-|0.8.0
cpptools|ms-|0.14.2
open-html-in-browser|pea|0.0.2
vscode-docker|Pet|0.0.21
vscode-icons|rob|7.17.0
vim|vsc|0.10.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
English please.

**Comment by OscarZhou** [comment]
I met the similar situation. He asked that when the file is saved, the cursor will be the bottom of the file. However, in my case, the cursor will go to top of the file, which is quite annoying. I did not modify any configuration. But yesterday, it happened after I update the vs code to lastest version.( the blue logo)

**Comment by hnsxxscyx** [comment]
Yes，my vscode has similar situation. Save file and cursor will go to bottom of the file.
