### ISSUE TITLE
Incorrect font

### ISSUE THREAD

**Issue by cyp0633** [Microsoft/vscode#38040]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
pascal|ale|0.10.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.3
code-runner|for|0.8.3
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.2
material-icon-theme|PKi|2.2.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Open a document
2.Right click on a tab
The language of the software on my computer is Simplified Chinese.
The words in ”Close“ ”Show in file explorer" options are in the system default font, but the Chinese words in the option"Close all(全部关闭)","Close the unchanged(关闭未更改)“ and "Keep it open(保持打开状态)" are showed in Times New Roman.
The problem didn't appear before I updated Windows to 17025 and VS Code to 1.18.0.
![vAlhe.png](https://t1.picb.cc/uploads/2017/11/10/vAlhe.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26175
