### ISSUE TITLE
Cannot select launch target in quick pick

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#38045]
I have the following launch configurations

![image](https://user-images.githubusercontent.com/172399/32650208-35c1034a-c5fd-11e7-9ac2-bb647ae7c623.png)

When I try to switch to the tslint-server launch configuration from the picker that is shown when clicking the debug status bar item

![image](https://user-images.githubusercontent.com/172399/32650233-4e0a6522-c5fd-11e7-99d9-4ec0704fbba7.png)

Then quick pick is shown, but selecting the `Attach to Server` launch config has no effect

![image](https://user-images.githubusercontent.com/172399/32650196-24c85340-c5fd-11e7-94fd-76220be9bc07.png)

**Comment by isidorn** [comment]
I can reproduce this with latest insiders. Not with stable -> November
