### ISSUE TITLE
Release 1.18 isn't available via yum

### ISSUE THREAD

**Issue by pazderak** [Microsoft/vscode#38041]
The release 1.18 isn't available via yum.

VSCode Version: 1.18
OS Version: Centos 7.3
Steps to Reproduce:

yum update 
the last version available is 1.17.1
Reproduces without extensions: N/A

**Comment by Roeshimi** [comment]
Is it just me or does this happen on every new release that the yum repo is at least a few days behind?

**Comment by zploskey** [comment]
Is there any chance of getting publishing to the yum repo added to release scripts?

**Comment by Tyriar** [comment]
It was uploaded earlier today https://packages.microsoft.com/yumrepos/vscode/

> Is there any chance of getting publishing to the yum repo added to release scripts?

That's what we want, but right now signing for rpms is a manual process done via email (unlike with deb/apt). That combined with network access-related issues can cause delays of 1 hour to multiple days. I did query the team about progress on automating this the other day though and am waiting to hear back.
