### ISSUE TITLE
Focus of updates, where are the important resources?

### ISSUE THREAD

**Issue by adrianoresende** [Microsoft/vscode#38053]
I think the updates have some weak values like recommendation of extension, icons, visuals etc, I think they should focus on editing that need great improvements, as an example, you cannot duplicate when you don't have a line below, you need to create a line to duplicate , does not rename together with closed tag and can not delete, move, rename files by command and others features or fixs.

These are priorities and are taking a long time to update.

People are not yet ready to immigrate VSCode by having unavailable resources, downloading many extensions is bad.

**Comment by agauniyal** [comment]
You should search for existing issues and open new issues individually as Feature Requests.

**Comment by usernamehw** [comment]
> weak values

Subjective



> cannot duplicate when you don't have a line below, you need to create a line to duplicate

`editor.action.copyLinesDownAction` <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd>

> does not rename together with closed tag

https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

> can not delete, move, rename files by command

https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils

> downloading many extensions is bad

...

**Comment by bpasero** [comment]
I am closing this as "I do not understand it".
