### ISSUE TITLE
vs code fades out folding markers [-]

### ISSUE THREAD

**Issue by TryingToFindALoginWhichIsNotRegistered** [Microsoft/vscode#38056]
This is a wish, not a bug:

The folding markers are faded out, if a method is not folded [-]. The markers for folded text are shown permanently [+].
I would prefer to stop this fadingout-effect and to display the [-] as well as the [+] permanently. It's less irritating.

**Comment by aeschli** [comment]
The option for that is `"editor.showFoldingControls": "always"`. It's currently not working in 1.18 but will be fixed in 1.19

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
Thanks for the explanation and (like always) fast reaction. Great team!!
