### ISSUE TITLE
showWorkspaceFolderPick always returns the first result

### ISSUE THREAD

**Issue by dkundel** [Microsoft/vscode#38059]
Hi everyone,

I was just updating my `Advanced New File` extension to use the new workspace folders APIs and it seems like there is a bug around `showWorkspaceFolderPick`. It is always returning the same folder for me, regardless of which folder I choose.

You can see my use of `window.showWorkspaceFolderPick` here: [file-controller.ts#L288](https://github.com/dkundel/vscode-new-file/blob/dkundel/add-workspace-support/src/file-controller.ts#L288).

Cheers,
Dominik

- VSCode Version: 2.6.1-insiders.20171019
- OS Version: 10.11.6

Steps to Reproduce:

1. Have an extension that calls `workspace.showWorkspaceFolderPick` in a workspace with multiple folders
2. Attach a debugger to the extension and set a break point to the result of the picker.
3. Choose int he Picker a folder that isn't the first one. 
4. Inspect the result in the debugger and you'll see it's always the first one.

Reproduces without extensions: No

**Comment by twlamb** [comment]
You might want to update your insiders version, I know this happened to an extension I was working on in the middle of October, but it was fixed.

**Comment by isidorn** [comment]
@twlamb thanks for jumping in. @dkundel please try reproducing with latest vscode insiders, you have the one from mid october.

**Comment by dkundel** [comment]
Yeah updating the Insiders version did the trick. Not sure why the auto updating didn't work but yeah it works now :)

Thanks!
