### ISSUE TITLE
Google Tests support

### ISSUE THREAD

**Issue by raver119** [Microsoft/vscode#38058]
Hi,

Is there any plans for adding C++ unit tests frameworks UI integration? I.e. Google Tests?

**Comment by mjbvz** [comment]
This is something that an extension can add support for. Please search the marketplace to see if any existing extensions provide what you are looking for. If not, you can [create your own extension](https://code.visualstudio.com/docs/extensions/overview).

Depending on your needs, [tasks](https://code.visualstudio.com/Docs/editor/tasks) may also work

Closing as extension candidate
