### ISSUE TITLE
Option to replace debug dropdown selector with debug buttons

### ISSUE THREAD

**Issue by GeorgeWells** [Microsoft/vscode#38051]
Is there a possibility to replace the debug dropdown selector with the dropdown bar (pause, step over etc. ) when active? Maybe a setting for this?

So it somewhat looks like this:
![image](https://user-images.githubusercontent.com/23452044/32652820-830a65e2-c5fd-11e7-87a3-5edc6c487484.png)

**Comment by weinand** [comment]
The dropdown selector cannot be replaced by the debug buttons because you can always start another debug session even if one is already active.

**Comment by GeorgeWells** [comment]
Well I learnt something new! Thanks!
