### ISSUE TITLE
Feature Request: Project differentiation on multi-project workspaces

### ISSUE THREAD

**Issue by hugoamvieira** [Microsoft/vscode#38054]
Hiya there!
While I know this feature is still quite new, I'd thought I'd go ahead and contribute with my 2c.
Basically what I feel is that it's too difficult to visually identify the begining and end for 2 different projects on a multi-project workspace (particularly large projects!), as there are no visual cues apart from indentation on the workspace. And when we start drilling down into each project's folders, it becomes even more difficult.

My suggestion is to maybe introduce spacing or colour cues (or both) such that it's easier to identify where each project begins and ends!

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
