### ISSUE TITLE
Folding is whitespace sensitive

### ISSUE THREAD

**Issue by ADCJustinH** [Microsoft/vscode#3805]
In typescript this function (being ported from js) does not fold correctly due to the second line of the function being improperly indented. That seems really wonky, why does it care at all about indentation? Should it not just fold to the closing '}' for the function?

    private initPortletTools(): void {
            // handle portlet remove
        $('body').on('click', '.portlet > .portlet-title > .tools > a.remove', function(e) {
            ...
            portlet.remove();
        });
    }

**Comment by Growiel** [comment]
According to the [release notes](https://code.visualstudio.com/Updates):

> The folding regions are evaluated solely based on the indentation of each line. This first version does not yet support language agnostic folding regions, or folding markers. This is in discussion for an upcoming release (see issue #3422).

So for now I'd say for now it "intended" behavior.

**Comment by weinand** [comment]
@ADCJustinH yes, for now this is the intended behavior.
