### ISSUE TITLE
Changes in Git panel

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#38066]
https://youtu.be/Nfl2_Jp3x-s

@joaomoreno
I want have button "inicializate repo" in Source control panel, also if one folder in workspace is already inicializate (maybe if I want inicializate another folder).

#37970

I think it's good to also improve selecting repo,...

And also add new feature - git history.

**Comment by joaomoreno** [comment]
@Mlocik97-issues Please don't open duplicate issues. 

https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
