### ISSUE TITLE
Integrated Terminal: inserting emoj doesn't work

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#38064]
- VSCode Version: 1.18.0
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open the integrated terminal
2. Press `ctrl+cmd+space` (osx) and choose an emoj

What happens?
Nothing is inserted into the terminal.

What should happen?
The selected emoj should be insterted into the terminal. It works with most terminals, like iTerm, standard macOS terminal.

Note that the same problem happens with Windows10  Insiders (that adds an emoj panel when pressing `win+;`).

Reproduces without extensions: Yes

**Comment by shobhitchittora** [comment]
@warpdesign Can confirm that you cannot directly add emojis from mac emoji pane. Although you can copy and paste emojis to integrated terminal.

Need triage from @Tyriar on this. Also would like to help if needed. 😁

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35266
