### ISSUE TITLE
Auto update VS-Code version

### ISSUE THREAD

**Issue by santi0037** [Microsoft/vscode#38060]
Please add Auto update, is really boring, download new versions and install updates of VS every week manually.

**Comment by maxibanki** [comment]
When you install VS Code via the installer (which needs admin privileges) there is an auto updater integrated. In the portable versions (zip-files) there isn't one integrated yet

**Comment by santi0037** [comment]
Sorry, I forgot to comment.. i'm using Linux.

**Comment by maxibanki** [comment]
You could use the repository, so you can update via the normal update progress of your operating system. Everything else does not make much sense in my opinon.
