### ISSUE TITLE
Switch keyword has no auto-completion

### ISSUE THREAD

**Issue by Fl0xer** [Microsoft/vscode#38069]
- VSCode Version: 1.17.2
- OS Version: Windows 10

Steps to Reproduce:

```
class Foo {
        public function new() {
                var i : Int = 0;
                switch(i) {
                     case truc:
                }
        }
}
```

When I write "swi" VsCode show me all functions beginning by these letters, but not the keyword switch.

**Comment by mjbvz** [comment]
Please file this issue against the c# extension: https://github.com/OmniSharp/omnisharp-vscode/issues/new
