### ISSUE TITLE
Autocomplete import paths fails for local non-relative imports

### ISSUE THREAD

**Issue by 0x80** [Microsoft/vscode#38061]
In my project I'm using the config below. 

I use non-relative imports for all of my components starting from the src root.  So `import x from 'components/x'` is really `import x from '../../components/x'`, depending on where the import is used.

Autocomplete / intellisense knows that I have a file x at the location, because it tries to autocomplete the path for me. However if I hit enter the path always becomes `import x from 'components//x'`.

Is this something I can solve in my tsconfig file, or should this be a considered a bug?

```json 
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["es6", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "outDir": "build/dist",
    "paths": {
      "*": ["*", "src/*"]
    },
    "plugins": [{ "name": "tslint-language-service" }],
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "acceptance-tests",
    "build",
    "config-overrides.js",
    "jest",
    "scripts"
  ],
  "include": ["./src/**/*", "./node_modules/firebase/index.d.ts"]
}
```
If there's anything else weird about this config I'd love to hear about it too ;)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/19920
