### ISSUE TITLE
Inconsistent Saved state of files, after many hours

### ISSUE THREAD

**Issue by ejmvar** [Microsoft/vscode#38062]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Clean Install on LinuxMint 18.2 (Full remove of previous versions from deb package and ~/.config.Code).
2. Open angular project (excluded node_modules for performance).
3. Worked the whole day without trouble.
4. Leaved editor open for next day, not suspending CPU.
5. Several files show as saved but, when trying to close them, received a message about "Save/Cancel/Don't save" before closing 
6. Even after saving the file, the message still appears.
7. Leaving and reopening the editor (code .) solves the problem, no issues.

Reproduces without extensions: Yes

Addendum:
- I know no other task modified those files, 
- verified against last saved version (git), before and after saving when at old VSCode instance (the one running from yesterday).
- So, somehow, VSCODE did not recognize "saved status" for files, neither refresehed that status after saving.
- I verified "Save" was working because my "ng serve" was recompiling every time I ordered to save those files.

Now, I remember I saw in Output window (Ctrl+J) lots of error messages mentioning errors and failures, referred to operations or actions I was unable to interpret, but I lost them. Sorry for this.

Thanks for such an amazing tool.

Eduardo J. Martínez
ejmvar@gmail.com

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
