### ISSUE TITLE
Detecting TS file as JavsScript when shebang exists

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#3806]
```ts
// typed.ts
#!/usr/bin/env node

import Promise = require('any-promise')
```
`import` is error with: illegal import declaration (undefined) and the file is detected as JavaScript
![image](https://cloud.githubusercontent.com/assets/3254987/13593980/6b38af44-e4b5-11e5-82f5-31c1bcef0c88.png)

**Comment by unional** [comment]
https://github.com/Microsoft/vscode/issues/3532

**Comment by bpasero** [comment]
We changed our language detection and made the first line pattern the least important thing to respect.
