### ISSUE TITLE
El host de extensiones finalizó inesperadamente

### ISSUE THREAD

**Issue by Keosuve** [Microsoft/vscode#38075]
I have this problem with the new Version 1.18!!! 

![image](https://user-images.githubusercontent.com/13707550/32668451-5e5fdec4-c61c-11e7-975d-2b80fba85bb0.png)

![image](https://user-images.githubusercontent.com/13707550/32668594-c786ab4e-c61c-11e7-99f2-ada94e08c602.png)

**Comment by alexandrudima** [comment]
@Keosuve The message in the console appears that the extension host terminates with an Out-Of-Memory exception.

Can you please share the list of extensions you have installed ?

**Comment by seanpoulter** [comment]
I've had the same behavior through 1.17 and 1.18 now. How do you figure out where the extension host is hanging (and configure vscode to always start like that)? With only 4 GB to work with, my system hangs and the process quits before I can get anything useful from the dev tools.

**Comment by jrieken** [comment]
@seanpoulter This will explain you how to attach dev tools to the extension host: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process. When things go south please try to create a heap snapshot and/or a CPU profile
