### ISSUE TITLE
JS Syntax Highlighting Error

### ISSUE THREAD

**Issue by dijonkitchen** [Microsoft/vscode#38071]
I found no instance of this issue in a Github search. 

- VSCode Version: 1.18.0
- OS Version: 10.13 (High Sierra)

Steps to Reproduce:

1. Create a `.js` file that has React code
2. In the render method, using a for loop and an if statement nested within it, chain some methods like `push`. 
3. Incorrect syntax highlighting

<img width="535" alt="screen shot 2017-11-10 at 7 53 22 am" src="https://user-images.githubusercontent.com/11434205/32666445-467ca5c4-c5ec-11e7-879d-a45b9cb528f4.png">

Reproduces without extensions: Didn't test

I suspect it something to do with nesting of parentheses and multiple boolean operators in the if statement. When I add parentheses on the if statement to be more explicit, highlighting is corrected. 

This problem existed yesterday too before I upgraded to 1.18.0.

**Comment by mjbvz** [comment]
Can you please share some source code along with the screenshot

**Comment by dijonkitchen** [comment]
I can't post all of it, but I narrowed it down to this and still get the same error:

```js
// @flow
for (let i = postLen; i >= 0; i--) {
  if (node) {
    const element = ((node: any))
  }
}

for (let i = 0; i < postsLen; i++) {
  if (
    prevPost &&
    prevPost.creatorId === post.creatorId &&
    post.timestamp < prevPost.timestamp + 300
  ) {
    postsWithBreaks.push(renderPost(post, true))
  } else {
    postsWithBreaks.push(renderPost(post, false))
  }
}
```

**Comment by mjbvz** [comment]
We don't provide flow support out of the box. If i get rid of the flow bits, everything seems to work fine

Please try filing an issue against whatever extension you are using to syntax highlight flow files
