### ISSUE TITLE
High CPU usage (even when not interacting with Code)

### ISSUE THREAD

**Issue by adinastavar** [Microsoft/vscode#38070]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
path-intellisense|chr|1.4.2
python|ms-|0.8.0
cpptools|ms-|0.14.2
qub-xml|qub|1.2.1
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:

1. Launch code
2. Launch Task Manager
3. High CPU usage from code

Reproduces without extensions: No
 
Screenshot CPU usage without interacting with Code:
![image](https://user-images.githubusercontent.com/4140815/32664643-98ebb32e-c63a-11e7-98ed-cb6155440e56.png)

**Comment by adinastavar** [comment]
After approximately 15 minutes, CPU usage stabilizes.

**Comment by hienvd** [comment]
I have the same problem on macos. 

VS Code version 1.18.0
MacOS 10.12.6

High CPU usage for Code Helper.

**Comment by roblourens** [comment]
Can you follow the steps here to help us narrow the problem down? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by adinastavar** [comment]
> What is the size of your workspace/project (how many files)?  

~10, 20Gb (> 100,000 files)

> What languages are used in this project?

Languages: C, C++ 

> Do you run Code on a single-CPU environment (e.g. VM)? 

No

> Which Code process consumes the most resources?

![image](https://user-images.githubusercontent.com/4140815/32766790-1d740502-c919-11e7-9ce5-726b4e92a4cf.png)
The C/C++ extension for Visual Studio Code.

**Comment by hienvd** [comment]
Hi @roblourens ,

For more information, this is my screenshot how VS Code has ate my resources. Please notice the lines like 1 and 3 on the process panel.

<img width="1440" alt="screen shot 2017-11-14 at 11 50 24 pm" src="https://user-images.githubusercontent.com/6824457/32793158-c1649d24-c997-11e7-8c55-acd428b18f15.png">

### Experiments
I tried `code --disable-extensions` but no luck, it still happened.

**Comment by roblourens** [comment]
@adinastavar Looks like the C++ extension is taking time to index your workspace. You can file an issue on them but for a workspace that large, that might just be the way it is...

@hienvd Please see the wiki page linked about and include as many details as possible, and please open a new issue.
