### ISSUE TITLE
Workbench contribution for a LifecyclePhase

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38080]
Extracted from https://github.com/Microsoft/vscode/issues/37541:

> @jrieken now that we have the startup phases in lifecycle service, should we change registerWorkbenchContribution to accept an optional phase argument and then when we instantiate the contributions respect that event to delay the instantiation?

Yeah, the registry should be per-phase and we should revisit each contribution and decide in which phase it should get created. Maybe even add another phase like `RunningForABit` so dust can settle..

> This would need to be wired into the setInstantiationService call of the BaseRegistry I guess.

Unsure... Not even sure what that is but feels we leak a layer to low. I would suggest to have an instance of those per phase and hide the idea of phases from it

**Comment by bpasero** [comment]
@jrieken fyi I added `LifecyclePhase.RunningForABit` (via https://github.com/Microsoft/vscode/commit/fa592ef424a374edba7b58d49e8b7c69ff8114bc). The delay is a bit artifical (3s via [workbench startup](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L209)). I adopted this for [`WorkspaceStats`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/stats/node/stats.contribution.ts#L14). 

I also made [`NodeCachedDataManager`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/cache/node/nodeCachedDataManager.ts#L14) a `IWorkbenchContribution` but currently this one is executed as before on LifecyclePhase.Running. Not sure if that one should be delayed as well.

**Comment by jrieken** [comment]
> I also made NodeCachedDataManager a IWorkbenchContribution but currently this one is executed as before on LifecyclePhase.Running. Not sure if that one should be delayed as well.

That can be delayed safely
