### ISSUE TITLE
Scroll position is not being preserved when switching between tabs with OmniSharp Intellisense working

### ISSUE THREAD

**Issue by surferau** [Microsoft/vscode#38089]
VS code version 1.18

When switching between tabs the scroll position of each tab is changing. Cursor position stays correct.

Type of files: c# . "OmniSharp Intellisense"  is enabled. 

How to reproduce:
open several c# files with at least 3 full page scrolls each, have  "OmniSharp Intellisense" extension enabled(you should see reference injections appear)  and switch between files using ether tabs on top or picking files from "open editors". You will see scroll position will change on each switch.  

My guess:
Some funky thing going on during Omnisharp Intellisense reference injection. See screenshot
![screen shot 2017-11-11 at 3 07 37 am](https://user-images.githubusercontent.com/5710850/32676584-bd2cdb7a-c68d-11e7-8ca3-5d2857b6b9d1.png)

**Comment by bpasero** [comment]
Sounds like an issue with CodeLense.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/32397, let's track it there.
