### ISSUE TITLE
Don't ask for confirmation for reverting change inline

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#38086]
- VSCode Version: Code - Insiders 1.19.0-insider (d6fbdcf19716910b26ea81efc95724f2fabe5aa6, 2017-11-10T06:10:30.893Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Some

This can be undone with Undo, no need for a confirmation dialog:

![image](https://user-images.githubusercontent.com/9205389/32673197-08c55eee-c603-11e7-9a95-200f088f37dc.png)

**Comment by joaomoreno** [comment]
Unfortunately I'd rather keep it. I can see users not expecting undo to work and as soon as you close the tab or restart Code, the undo stack is gone...

**Comment by degardinn** [comment]
Inline revert is a feature I've been using a lot in WebStorm, often to remove temporary test blocks. A confirmation dialog slows this process. Most IDEs don't implement a confirmation...
So it's a bit subjective. Couldn't there be an option to select of we want a confirmation box or not?

**Comment by joaomoreno** [comment]
@degardinn Would you care enough to submit a PR for that configuration setting? 👍
