### ISSUE TITLE
[angular] CTRL+click to open link & data-ng-include=""

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#38087]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. write

`<div data-ng-include="file.html"></div>`

to HTML document.

2. CTRL+click on "link" (file.html) doesn't work.

**Comment by aeschli** [comment]
This should be added by an extension.
