### ISSUE TITLE
Feature recommendation: Going back with backscape/alt+left_key after going to source(ctrl click)

### ISSUE THREAD

**Issue by norveclibalikci** [Microsoft/vscode#38084]
I think it will be make so many people's life easier when working with a lot of files.

**Comment by Mlocik97-issues** [comment]
And what if I want in file delete something, backspace will not work?


And you have tabs, if you close tab opened by CTRL+Click, you will be back on your file.

**Comment by alexandrudima** [comment]
Let's track in #27112
