### ISSUE TITLE
Callstack is not cleared out after stop debugging in multi-thread application

### ISSUE THREAD

**Issue by richardzeng1985** [Microsoft/vscode#3808]
Repro:
 
1. Compile following C++ code 
#include <iostream>
#include <cstdlib>
#include <pthread.h>
using namespace std;
#define NUM_THREADS 5
void *PrintHello(void *threadid)
{
long tid;
tid = (long)threadid; //set a breakpoint here
cout << "Hello World! Thread ID, " << tid << endl;
pthread_exit(NULL);
}
int main()
{
pthread_t threads[NUM_THREADS];
int rc;
int i;
for (i = 0; i < NUM_THREADS; i++) { //set a breakpoint here
cout << "main() : creating thread, " << i << endl;
rc = pthread_create(&threads[i], NULL,
PrintHello, (void *)i);
if (rc) {
cout << "Error:unable to create thread," << rc << endl;
exit(-1);
}
}
pthread_exit(NULL);
}
 
2. Set two breakpoints in the lines with comments "//set a breakpoint here" 
 
3. press F5 4~6 times 
4. Stop debugging
 
Observe:
 
The VSCode is in design mode, however, callstacks is not cleared out, refer to below screenshot:

**Comment by weinand** [comment]
@richardzeng1985 this seems to be an issue of the C++ extension you are using. Let me know what extension you are using and I will move the issue over.

**Comment by weinand** [comment]
@richardzeng1985 please file this issue against the C++ extension you are using.
