### ISSUE TITLE
The call operator (&) in Powershell in MacOS and Linux

### ISSUE THREAD

**Issue by woodster999** [Microsoft/vscode#38081]
- VSCode Version: 1.18.0
- OS Version: MacOS and Linux
The call operator (&) does not work in MacOS and Linux builds of VS Code
Steps to Reproduce:

1.  Use & to try any Command or Script and it will fail and put you in Debug mode and wont let you out.
2. the PWSH Terminal runs it fine. 
3. Works fine in the Windows Build.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file this against the PowerShell extension.
