### ISSUE TITLE
Allow to drag dirty editors across windows and restore their dirty contents

### ISSUE THREAD

**Issue by mspaulding06** [Microsoft/vscode#38091]
- VSCode Version: 1.18
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Open a document
2. Make changes to the document but do not save them
3. Open another code window with cmd+shift+N
4. Drag the document's tab to the new window

Expected Result:

I expect that the changes in the document buffer will be retained when dragging the tab to the new window.

Actual Result:

The document is re-opened in the new window and all unsaved changes are lost.

Reproduces without extensions: Yes

**Comment by shobhitchittora** [comment]
@mspaulding06 IMHO this is the behavior of any text editor even ```vi```.  If you try to replicate your claim using ```vi``` , first you'll get a prompt disallowing you to edit. If you edit anyway, you wont' see your changes as they are kept in a swap file and added to original file on saving.

@sandy081  You can close this.

**Comment by mspaulding06** [comment]
If retaining the changes between windows is not possible or too difficult to implement, I would be willing to compromise and have a dialog presented to the user asking them to save their changes.  This would at least prevent loss of data and be less of a surprise to the user.

**Comment by shobhitchittora** [comment]
@sandy081 need your opinion on this. IMO this is the expected behavior.

**Comment by sandy081** [comment]
@bpasero Owns this area so assigning to him.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/81f8ee02f720704aa122a68cf60bbc9ad4d709c6

**Comment by joaomoreno** [comment]
@bpasero This doesn't work when dragged from any of the explorer views: #42815
