### ISSUE TITLE
"Quick Open Files"  is slow

### ISSUE THREAD

**Issue by ceyhunkerti** [Microsoft/vscode#38094]
it got slower with the 1.18 version. There is a delay when searching a file.

**Comment by roblourens** [comment]
- What OS?
- Can you tell me about your workspace? Is it very large? Are there symlinks?

**Comment by ceyhunkerti** [comment]
Ubuntu 16.04
Yes it is a large workspace, but i am comparing the same workspace with 1.17

**Comment by ceyhunkerti** [comment]
hw. specs;
i-7,  32g ram, ssd

**Comment by ceyhunkerti** [comment]
[vscode118.mp4.zip](https://github.com/Microsoft/vscode/files/1462980/vscode118.mp4.zip)

here is a little cast

**Comment by ceyhunkerti** [comment]
[vscode117.mp4.zip](https://github.com/Microsoft/vscode/files/1462987/vscode117.mp4.zip)

And this one is with 1.17, hope these help

**Comment by chrmarti** [comment]
I think the difference might be that in the 1.18 recording the cache wasn't populated yet.

After opening VS Code the first search will be slower because the cache is still empty, subsequent searches are faster because they can get results from the cache. This hasn't changed between 1.17 and 1.18.

Could you confirm that both versions show some delay on the first search, but not on the second?

**Comment by ceyhunkerti** [comment]
Nope, 1.17 is faster on both first and second searches. Here is another cast comparing both.

[vscode118vs117.mp4.zip](https://github.com/Microsoft/vscode/files/1463584/vscode118vs117.mp4.zip)

**Comment by ceyhunkerti** [comment]
btw. i just tried insider and it is fast again. I hope it will be so in 1.18.2

**Comment by chrmarti** [comment]
Are you on 64- or 32-bit Linux?

**Comment by ceyhunkerti** [comment]
64

**Comment by chrmarti** [comment]
I'm not aware of any changes in 1.19-insiders that would affect QuickOpen performance. (Since you mention it is fast there.)

**Comment by ceyhunkerti** [comment]
I've excluded some folders and it is faster. But, still i've no explanation why it is faster on a fresh installation without any config.
Anyway, since no one else had the same problem. I'm closing the issue. Thanks.
