### ISSUE TITLE
Some common keyboard shortcuts key are not supported

### ISSUE THREAD

**Issue by richardzeng1985** [Microsoft/vscode#3809]
Repro:
I noticed that most of the common debugging scenarios like F5, F10, F11, Shift+F11, Shift+F5 have all supported in VSCode, however, some of common shortcuts key are not support yet.
 
1. Currently "Run to cursor" only support from context menu, keyboard shortcuts key "Ctrl+F10" hasn't been supported yet,  it would be great if we can add this support as it also uses very frequently during debugging. 
2. Do we plan to add support for "Start without debugging" and the relevant keyboard shortcut key  "Ctrl+F5" ?

**Comment by isidorn** [comment]
1. RunToCursor is a global editor action, which means you can also access it via command palette <kbd>F1</kbd> or you can assign a custom keybinding via preferences > keyboard shortcuts > search for `editor.debug.action.runToCursor`
2. This is done and will be available in the April vscode release
