### ISSUE TITLE
Folder view New File/Folder Icons not detecting collapsed state.

### ISSUE THREAD

**Issue by AndrewNeudegg** [Microsoft/vscode#38098]
![](https://user-images.githubusercontent.com/12610365/32684662-cf871f66-c67d-11e7-8157-a5a192f73870.gif?raw=true)

When the active directory tree view area is collapsed, the control incorrectly renders upon the next view area opening. The control area is filled with with multiple independent text fields. This problem also occurs when pressing the new folder button. 

The control should either open the view area and display a single text area or refuse the user input.

**Comment by isidorn** [comment]
@AndrewNeudegg This is fixed in latest vsccode.
Let me know if you can reproduce with latest vscode stable

**Comment by AndrewNeudegg** [comment]
The fix is perfect, thanks.

From a use stand point it would be nice if the buttons would still be present but would just open the folder with focus set to the new file/folder text field. This would save the extra click when creating files or folders quickly.
