### ISSUE TITLE
search in files triggers runaway rg.exe

### ISSUE THREAD

**Issue by simra** [Microsoft/vscode#38093]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.12.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.0

---

Steps to Reproduce:

1.  run a text search (Ctrl-Shift-F) in a folder with very large files.
2.  rg.exe can be seen churning away and I can't figure out how to cancel the search. Clearing the search box did not help.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
You should be able to cancel the search by pressing escape. How large are the files? Are there symlinks in the folder?

**Comment by simra** [comment]
I don't remember for sure but I think escape did not cancel (my first instinct would be to hit escape, but I may not have tried that).  I will try to repro at my first opportunity. There are several multi-GB text files in the folder, no symlinks.   I think a better UX might be to skip searching these files unless the user explicitly chooses to, for instance by showing in the search pane "this file skipped because it is large, click here to search"

**Comment by roblourens** [comment]
On windows we set a max filesize of 300MB, so it should be skipping those anyway. If you can make it happen consistently, you could narrow it down by excluding some folders.

**Comment by simra** [comment]
I'm going to close as no-repro.  Escape seems to be working fine.  If I can repro again I'll re-open.
