### ISSUE TITLE
MacOS - use of non-command key related short-cuts should be avoided

### ISSUE THREAD

**Issue by ajmas** [microsoft/vscode#38092]
- VSCode Version: 1.17.2
- OS Version: MacOS X 10.13.1

Steps to Reproduce:

1. Use a US Keyboard layout
2. I need to type the character Ï in a .js document
2. I type option-shift-i

Problem: Document gets reformatted 

Expected: To be able to type a foreign accent key.

In general I would say that allowing any keyboard short-cut that doesn't involve the ctrl or command keys are problematic. The 'option' key on the Mac is used for getting to alternative printing characters on the keyboard, when used without ctrl or command keys. 

Suggestion: Possibly change to be command-option-shift-i, to prevent adverse impacts in internationalisation contexts.

Reproduces without extensions: Yes

I have looked through existing issues and could not find anything corresponding

**Comment by alexandrudima** [comment]
I agree that this would be desirable. 
Initially, **there was one problem**: no more "free" keybindings, so we shipped with `option+shift+i` as format document on OSX. 
Now, **we have a second problem**: all the folks that are used that `option+shift+i` is bound to format.

---

The workaround is to simply change the keybinding via `cmd+k cmd+s`.

**Comment by ajmas** [comment]
There are bound to be side effects to fixing this, but as it is currently we are breaking key Mac functionality. I had forgotten about this issue, until I need to type a 'ç' using a US keyboard. 

Maybe the way forward could be:
  - provide a new i18n friendly set of bindings
  - migrate to that for new installs
  - provide a way to migrate for old installs
  - warn users of limitations of using key combinations that are likely to hide system functionality?

**Comment by alexdima** [comment]
Let's continue tracking in https://github.com/microsoft/vscode/issues/1240
