### ISSUE TITLE
Vertical Panel settings appear global and not unique to a workspace or even a window. [osx]

### ISSUE THREAD

**Issue by randy5235** [Microsoft/vscode#38095]
- VSCode Version: 1.18.0
- OS Version: osx 10.12.6

Steps to Reproduce:

1. Open two separate windows.
2. Move terminal panel to the right in one of the windows.
3. Notice that the terminal panel in the second window follows
4. Move it back to the bottom.
5. Notice that the terminal in the second window follows as well.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I think this is as designed, unless you change the setting in your workspace settings.

**Comment by randy5235** [comment]
It is a bit of an odd behavior but I am happy to close the issue if that is the case. If I move the "workbench.panel.location" to the workspace setting, is is _unique_ per workspace but cannot be changed within that workspace. Leaving it in user settings makes it global for all windows.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37351
