### ISSUE TITLE
Should allow adjusting font weight

### ISSUE THREAD

**Issue by calmh** [Microsoft/vscode#381]
We have the settings `editor.fontFamily` and `editor.fontSize`, but I'm missing an `editor.fontWeight`. This is most needed when using a dark theme, as folds become visually bolder in that setting. Compare for example Code using Input Mono (regular):

<img width="928" alt="screen shot 2015-11-20 at 22 14 34" src="https://cloud.githubusercontent.com/assets/125426/11312092/3cee7ed8-8fd4-11e5-840e-f72a11390c5b.png">

with Sublime Text using Input Mono Thin:

<img width="896" alt="screen shot 2015-11-20 at 22 15 13" src="https://cloud.githubusercontent.com/assets/125426/11312097/450ac388-8fd4-11e5-9888-da919fcea386.png">

This could be either accomplished by a weight setting similar to the CSS `font-weight`, or as part of the font name (i.e. Sublime text accepts "Input Mono Thin" as the font name, while Code currently rejects that).

---

Oh, and kudos for creating an editor experience to rival the best on Mac! I never thought the day would come when I'd run a Visual Studio product on Mac, but I'm happy to be proven wrong!

**Comment by alexandrudima** [comment]
Thank you for the kind words. Will look into adding this

**Comment by torarvid** [comment]
@calmh While waiting for this, there is a workaround for us OS X users, as seen on this Issue from Atom: https://github.com/atom/atom/issues/3790

(Basically, strip spaces, and put a hyphen between the font name and the weight, so InputMono-Thin in your case. I use Source Code Pro Light myself, and so setting it to SourceCodePro-Light works for me)

**Comment by calmh** [comment]
Oh! Neat! I had resorted to disabling the variants except thin and bold in font book. :)

**Comment by mitsukuri** [comment]
Any hope for a windows workaround? Can't set bold font as of v0.10.11

**Comment by jpleau** [comment]
Hi, any updates on this? Some fonts look better when they are bold, an "editor.fontWeight" or "editor.fontStyle" setting would be awesome!

Thanks

**Comment by mehas** [comment]
For some reason the default monospace typeface for Windows (Consolas) appears bold in VSC, but others don't.

**Comment by escobera** [comment]
This feature is really a deal breakeer for me. Any news on this? @alexandrudima

**Comment by alexandrudima** [comment]
PR welcome, IMHO it is straight-forward to implement by following the `fontFamily` or `fontSize` settings.

**Comment by jpleau** [comment]
fwiw, I started work on this by implementing the "fontWeight" setting.

I had to stop for a bit since at the time, current master did not work correctly for the terminal panes, I will continue work in the next weeks after my vacation.

**Comment by conceptualspace** [comment]
💃

**Comment by ramamurthynagaraj** [comment]
Hi guys, submitted a PR for this issue. Please let me know if there are any issues.

**Comment by jpleau** [comment]
Your solution works better than the one I was working on @ramamurthynagaraj thanks!

I think this issue can now be closed?

**Comment by alexandrudima** [comment]
Thank you @ramamurthynagaraj

**Comment by vavans** [comment]
Hi, thank for the update.
Unfortunately, there is still an issue as you can see in the screenshot below; even the thinnest fontWeight is a little bold (font used : Consolas on windows 8). Same result with an integer font.

![image](https://cloud.githubusercontent.com/assets/1058175/18089090/5cf3d98e-6ebe-11e6-8e5b-0a5ba915afca.png)

**Comment by alexandrudima** [comment]
@vavans This might be caused by different font rendering engines. I don't know what Sublime uses, but our font rendering is ultimately done by Chromium. It is not clear to me if Consolas has the exact weight of 100 or some fallback logic is used by Chromium (as is described in https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)

**Comment by regs01** [comment]
Same here. 150% scaling on 2160p screen, 14pt Consolas appears a bit boldish, even with 400 or normal. Light or anywhere below 400 won't make any difference. When you look close to display it's nice and beatiful, but from 0,7-0,8 m. from display it looks like Fixedsys....

http://i.imgur.com/PU3SEmh.jpg

**Comment by mouhong** [comment]
Also not work for me (OS X EI Capitan 10.11.5).

**Comment by alexandrudima** [comment]
@mouhong Is there any difference for you in Chrome if you try it in a jsfiddle like https://jsfiddle.net/rhy7v1wp/

If not, then please create an issue against Chromium https://bugs.chromium.org/p/chromium/issues/list and link back to it here.

Thank you!

**Comment by mouhong** [comment]
@alexandrudima No difference. But `font-weight:300` works in other places. For example, if I inspect your github comment in Chrome, and set `font-weight:300` in the Styles tab, it works! The text gets thinner.

**Comment by mouhong** [comment]
@alexandrudima FYI, it'll work if I manually edit `workbench.main.css` and insert css: `.monaco-editor { -webkit-font-smoothing: antialiased; }`

**Comment by alexandrudima** [comment]
@mouhong Perhaps we can expose `-webkit-font-smoothing: antialiased;` in the form of a setting, I don't believe that works well for all folks across all OSes and across all fonts.

**Comment by mouhong** [comment]
@alexandrudima I found that, if I inspect your GitHub comment in Chrome, and manually set style `font-weight: 300`, the font will get thinner. Interesting.

**Comment by alexandrudima** [comment]
One thing to keep in mind is that I am on Chrome 53, while VSCode is on Chromium 49, so that might have an impact too.

**Comment by dkondratovych** [comment]
Doesn't work for me
> Version 1.5.3 (1.5.3)
> 5be4091987a98e3870d89d630eb87be6d9bafd27

<img width="588" alt="screen shot 2016-09-28 at 4 18 32 pm" src="https://cloud.githubusercontent.com/assets/3199501/18914812/4636d5c6-8597-11e6-85e1-64a300ffecab.png">


I am trying different values, but font looks the same

<img width="949" alt="screen shot 2016-09-28 at 4 18 03 pm" src="https://cloud.githubusercontent.com/assets/3199501/18914779/2cf4db08-8597-11e6-8c3e-7c8b30ec1ede.png">

**Comment by regs01** [comment]
It does work. It's just Consolas doesn't have light version. Don't know where to report it. But, i think, MS employees here could forward it to font devs.

**Comment by wprater** [comment]
are we able to expose `-webkit-font-smoothing: antialiased` so we can get a better rendering on macOS?

**Comment by chantlong** [comment]
I want to use a Light version of a font. Setting the font weight to "300" doesn't make any difference it seems compared to "400". If I set it "200" or below, it automatically sets it to Extra Light, but I want to use Light. Is there a way to skip the font weight and just in the font-family specify Light like in Sublime?

**Comment by regs01** [comment]
@Wong
Until we have Consolas Light alternatively you can use Source Code Pro from Adobe.
https://github.com/adobe-fonts/source-code-pro/releases

**Comment by chantlong** [comment]
@regs01 I was using Operator Mono. I found a way to make it work without explicitly setting fontWeight. I used OperatorMono-Light for family which helped set the current fontWeight. Thanks.

**Comment by gabirujoe** [comment]
Hi everyone. 
@alexandrudima What confused me is what comments are rendered with a font weigth more lighter that the rest of the code. Is it some config that you guys pass to chromium to render this way? I think if all the code render with the same weigth of comments, everybody will be happy. some idea?

![font weight](https://cloud.githubusercontent.com/assets/15944259/24435395/73d16bba-140b-11e7-94e0-c0e34645757c.png)

**Comment by austinthiel** [comment]
I'd like to hope that @gabrielnogueira is onto something here. Can anybody (no pun intended) comment on that?

**Comment by TanelS** [comment]
Part of the perceived font-weight is related to contrast between background and the font itself. For example the Monokai is quite unbearable, font colors are rather bright on dark background. Bright letters are using more sub-pixels and thus creating the too-bold-font perception. I've switched to [Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark) theme and everything looks better now. Even VS Code own softer Color Themes look better (Monokai Dimmed etc). And for the comment that comments are rendered lighter - as comments are dimmer, they are using (visually) less sub-pixels thus they are visually lighter.

**Comment by austinthiel** [comment]
@TanelS Thanks for the explanation. Although, comparing the same font + background on VS Code (left) and cmder (right), they display very differently, and cmder looks much more crisp. Is this entirely the fault of how chrome renders fonts? 
![Example](https://user-images.githubusercontent.com/14973727/29263679-bdca787a-808e-11e7-9275-c2ee8e0cca1c.png)

**Comment by TanelS** [comment]
@austinthiel VSCode uses [Electron](https://electron.atom.io/) as rendering engine. And most of the font anomalies are because of that. Hopefully the Electron devs are able to handle the font-weight problems. Meanwhile I personally use less contrasted color themes as a workaround.

**Comment by austinthiel** [comment]
I see that now. I chose the font + background on another Electron app and it's got that same fuzz-factor to it. That's a bummer, I hope it's resolved soon.
