### ISSUE TITLE
"window.title": "${activeEditorLong}" not work on windows7(64bit)

### ISSUE THREAD

**Issue by fullon9** [Microsoft/vscode#38103]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
maple|yjt|1.1.6

(3 theme extensions excluded)

---

Steps to Reproduce:

1. "window.title": "${activeEditorLong}" at user settings (settings.json)
2. Restart VSCODE and open  several files
3. The contents of title bar  stands still when I select tab of other file.
* On winodws10 It  works well as i expected

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
This is probably unrelated to the setting. We already have many issues filed against the fact that the window title is not updating on Windows 7, it seems to be an Electron issue.
