### ISSUE TITLE
Delay on "Forward delete" ~1s

### ISSUE THREAD

**Issue by playerx** [Microsoft/vscode#38108]
- VSCode Version: 1.18.0
- OS Version: macOS High Sierra (Version 10.13.1)

Steps to Reproduce:
1. Create new file (cmd+N)
2. Paste some text, for example:
```
TypeScript 2.6 is here in time for Halloween, but have no fear! We’ve got some great treats for you in this release
```
3. Press fn+delete
4. delay ~ 1 sec
5. character is deleted.

Also:
* if I will use ctrl+D, there is no delay. 
* after deleting characters multiple times using fn+delete, there is no delay any more, but if we will press any other key and then try to delete char using fn+delete, there is delay again
* issue found one month ago, in October release.

Reproduces without extensions: Yes

**Comment by shobhitchittora** [comment]
@playerx I'm not seeing this problem with my installation. 

- VSCode Version: 1.18.0
- OS Version: macOS High Sierra (Version 10.13.1)

Just to be sure can you check try re-installing or see if some other process is slowing you down.

**Comment by playerx** [comment]
@shobhitchittora  thanks for fast response, I've found the issue, it was macOS dictation.

Solution:
1. System Preferences
2. Keyboard
3. Dictation
4. change Shortcut from "Press Fn..." to something else

Btw, I had turned off dictation but I had an issue, so turning off was not solution for me.

But Also want to mention, macOS didn't have such problem with other app, like TextEdit.
