### ISSUE TITLE
Collapse all in debug console

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#38109]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.67
python|ms-|0.8.0
vscode-icons|rob|7.17.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Debug in `DEBUG CONSOLE`, and input some available variables.
2. `DEBUG CONSOLE` will be filled with some variables and its attributes

Expect:
Is it possible to add a "Collapse" button in `DEBUG CONSOLE`, like that in `DEBUG` or `PROBLEMS` window.

![collapse](https://user-images.githubusercontent.com/10704251/32688358-349868b0-c70a-11e7-9d81-6e1e79c5ff76.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
This is a fair feature request. Will not add it until more users asks for it.
It is definetely useful, I am just afraid of having too much clutter in the title area especialy with the vertical panel limited horizontal space.

I would accept a PR which adds this action to the context menu of the debug console.

Code pointer
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L424
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/viewlet.ts#L261

**Comment by shobhitchittora** [comment]
@isidorn I'd like to tab a jab at it. 😅

**Comment by svitlana-galianova** [comment]
Well, I assume nobody is working on it anymore, so I would like to take a look.

**Comment by isidorn** [comment]
Fixed by @svitlana-galianova in https://github.com/Microsoft/vscode/pull/43987

**Comment by bpasero** [comment]
@isidorn after collapse all I would expect focus to move into the input field. currently the first node seems to get focus (which is not even possible when clicking).
