### ISSUE TITLE
0.10.10 Dark theme for js is not highlight var and function

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#3810]
I think it is not expect behaviour. Other keyword like `if` `else` `return` `while` even `true` `false` `null` is highlighted but `function` and `var` is not

Is it a bug or you have any reason to?

Also `require` should be highlighted too

**Comment by robertftw** [comment]
Yep got the same problem!

**Comment by arminas** [comment]
This happens only on OSx. On windows 10 highlighter works fine.

**Comment by ndonohoe-bjss** [comment]
const, let, class are also not highlighted.

This is happening for me on Windows 7

**Comment by aeschli** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/3903
