### ISSUE TITLE
Wrong git decorations in file explorer

### ISSUE THREAD

**Issue by LaurentTreguier** [microsoft/vscode#38112]
- VSCode Version: 1.18.0
- OS Version: Fedora 26 x86_64

Steps to Reproduce:

1. Add some files in a git repository
2. Modify the `.gitignore` to ignore a certain pattern, andadd exceptions to this pattern

Extract from my `.gitignore`:
```
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

Result:
![image](https://user-images.githubusercontent.com/7602755/32689125-d372312c-c6de-11e7-9451-1bd8a020703d.png)

You can see that `.vscode/tasks.json` is grayed out because it matches `.vscode/*`, even if it shouldn't because of the `!.vscode/tasks.json` rule. However, it still has the correct `U` badge for some reason.
The file probably isn't supposed to be grayed out, since git does take it into account.

**Comment by jrieken** [comment]
From the command line, can you run this `git check-ignore .vscode/tasks.json` and post the output here?

**Comment by LaurentTreguier** [comment]
```
$ git check-ignore .vscode/tasks.json
.vscode/tasks.json
```

It looks like it's actually being ignored by git... But when using `git status`:
```
$ git status
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.vscode/
	README.md
	dub.selections.json
	source/dls/util/uri.d

no changes added to commit (use "git add" and/or "git commit -a")
```

Here it considers `.vscode/` as untracked (it only contains `tasks.json`, removing `!.vscode/tasks.json` from `.gitignore` makes git ignore `.vscode/`). So git is being a bit inconsistent here...

**Comment by jrieken** [comment]
But the `.vscode/task.json` files doesn't show up in the git viewlet, right? That's the model we use to determinate the modified and untracked/added state.

**Comment by LaurentTreguier** [comment]
Yes it does, it shows up in the git viewlet:
![image](https://user-images.githubusercontent.com/7602755/32724878-434e7ed4-c873-11e7-9c8f-ab402794906b.png)
And just like in the explorer, the badge is `U` but it's grayed out.

**Comment by jrieken** [comment]
@joaomoreno Can you help? Is this a valid git state?

**Comment by joaomoreno** [comment]
Yup, it appears `git check-ignore` has a bug. Seems to be exactly this: https://marc.info/?l=git&m=150904377104805&w=2

Related: https://marc.info/?l=git&m=150143026024244&w=2

**Comment by bergwerf** [comment]
Note that this is still not fixed (not sure if this bug is on the radar of the git team). If try to exclude files without file extensions like this:
```
# Ignore all
*

# Unignore all with extensions
!*.*

# Unignore all dirs
!*/
```
Then the whole file explorer will be greyed out...

**Comment by jrieken** [comment]
fixed via https://github.com/microsoft/vscode/pull/73890
