### ISSUE TITLE
[Freeze] Dev tool (electron & V8) freezed if in source open workbench.main.js file

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#38116]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. Help -> toogle dev tool -> source -> workbench.main.js
2. freeze, restart will not help. Dev tool is useless.

maybe not VS Code bug, but bug with V8 core.
https://github.com/v8

**Comment by bpasero** [comment]
Yes.
