### ISSUE TITLE
alt+l - I got webbrowser new card opened instead of Polish "ł" letter

### ISSUE THREAD

**Issue by slaweklasek** [Microsoft/vscode#38111]
There's an error with key binding. I can't use Polish national letter Ł with alt pressed on Mac combination.
Normally when I press alt+a, e, o, s, z, x, c, n
I get following
ą, ę, ó, ś, ż, ź, ć, ń
but NOT ł - when I want to get that letter, VC opens new tab ....

please fix this issue....

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.1
auto-close-tag|for|0.5.3
LiveServer|rit|3.0.0
html-preview-vscode|tht|0.1.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@slaweklasek Is there any keybinding on your VSCode installation for `ctrl+alt+l` ? You can search in the keybindings UI at `cmd+k cmd+s`
