### ISSUE TITLE
@types auto install helper not showing up

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/vscode#38114]
- VSCode Version: 1.18.0
- OS Version: macOs Sierra 10.12.6

Steps to Reproduce:

1. Create a TypeScript file and insert `import * as cpx from "cpx"`
2. The @types auto installer helper is not showing up

Instead I get this message 
```
Could not find a declaration file for module 'cpx'. '/Users/alan/Documents/speedy-node-core/node_modules/cpx/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/cpx` if it exists or add a new declaration (.d.ts) file containing `declare module 'cpx'
```
I noticed that for example for `lodash` the auto installer works fine.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#19970
