### ISSUE TITLE
[ Feature Request ] Multi-screen same workspace Drag and Drop Tabs outside the vscode window

### ISSUE THREAD

**Issue by Aetherall** [Microsoft/vscode#38119]
Hi Vscode Team!

In my opinion, the next step for VScode is to allow the use of multiple screens within the same workspace. Just as IntelliJ does.

The ability to drag an editor tab outside the VScode window, and then drop it to spawn a new editor pane, free to resize and move independently, would be a major improvement in term of ergonomy and confort.

We already have the possibility to open our working folder twice, but this feature would allow to keep the same state. The breakpoints could be seen on the two windows etc..

Do you think this is doable ?
Does electron allow the spawn of children views ?

Do you think VScode will one day or another implement this feature ?

Thanks for your response :)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by Aetherall** [comment]
@bpasero In fact I already used the search function, but I couldn't find the reavelant issue
can you reference it here for me ?
Sorry for bothering ...

**Comment by bpasero** [comment]
Like https://github.com/Microsoft/vscode/issues/367 or https://github.com/Microsoft/vscode/issues/8171? Was really not so hard to find it...
