### ISSUE TITLE
vsCode+Emmet autocompletion - setting to insert newline inside div after hit 'tab'

### ISSUE THREAD

**Issue by Gennady-G** [Microsoft/vscode#38121]
Greetings!

by default vsCode does not split *div* tag into lines:

`    <div></div>`

As I understand this is because *div* is a block element. But I want it to autocomplete like this:

```
    <div>
        _
    </div>
```

Underline here is cursor position.

Is there a setting for it?

What I've already found is [endWithNewLine](https://github.com/Microsoft/vscode/issues/13942), but it is different setting, for files

Best regards,     
Gennady

**Comment by Mlocik97-issues** [comment]
Is it hard to press enter? I Often need it without new line

**Comment by Gennady-G** [comment]
> I Often need it without new line

That's why I suggest setting for it, so I can turn it on, but You can leave as it is..

Or there could be a setting for all types of tags.. for example for `<p></p>`

**Comment by Mlocik97-issues** [comment]
It's not hard to press enter,  i think it's useless setting and I don't know milion settings, because it's problem to find needed setting...


And <p> is unpaired tag

**Comment by ramya-rao-a** [comment]
@Gennady-G 

> As I understand this is because div is a block element.

No, `div` being a block element has nothing to do with this. You will see the same behavior with `span` or `a` which are inline elements.

There is no setting to introduce a new line.

You can define custom snippets with the new line if you want though. See https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets

The emmet library being used is what provides the expansion of the emmet abbreviations. You can log a feature request there if you want the ability to have newlines between the tags. Though, honestly I don't see it getting implemented as you can easily add the newline manually.

**Comment by Gennady-G** [comment]
>  You can log a feature request there if you want the ability to have newlines between the tags. Though, honestly I don't see it getting implemented as you can easily add the newline manually.

Ok @ramya-rao-a , thank You much for response! :)

Best regards,     
Gennady

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!

**Comment by doktordata** [comment]
@Gennady-G you could use:
```
"emmet.preferences": {
  "format.forceIndentationForTags": [
    "div"
  ]
}
```
From [https://docs.emmet.io/customization/preferences/](https://docs.emmet.io/customization/preferences/)
> format.forceIndentationForTags
> A comma-separated list of tag names that should always get inner indentation.

**Comment by Gennady-G** [comment]
@doktordata , Your soulution works, thank You very much! :)
