### ISSUE TITLE
find slow with error "invalid regular expression" when unselected line is very large

### ISSUE THREAD

**Issue by zerog2k** [Microsoft/vscode#38129]
find slow with error "invalid regular expression" when unselected line is very large

- VSCode Version:
1.18.0
- OS Version:
lubuntu 16.04

Steps to Reproduce:

1. open very large text file which has extremely long line (e.g. a string of 131k of chars with no line break)
2. put cursor on same line (in my case there is only one line), but do not select any text
3. search (ctrl+f)
4. observe:
 a. long delay (in my case older computer, it's slow because it's taking a few seconds)
 b. error: "invalid regular expression" against the entire file (in this case one line, large string) (see screenshot attached)

Suspect that this may be because find dialog box seems to want to select whatever line cursor is on, regardless of actual selected text, and inserts this into search (find) input textbox.
Important to note that user did not select any text to begin with. This seems to be problematic behavior if line is too long. (I can reproduce this particular behavior - selecting and pre-filling find textbox with the previously unselected text on cursor line - on any file).

Reproduces without extensions: Yes

![screenshot from 2017-11-11 13-57-47](https://user-images.githubusercontent.com/3943170/32693086-1102007a-c6ea-11e7-80c9-81092ceaff40.png)

**Comment by zerog2k** [comment]
looks like it might be related to #32901

**Comment by rebornix** [comment]
You can turn the seeding from selection/cursor off by setting `editor.find.seedSearchStringFromSelection` to `false`, then we'll not try to populate what's under cursor and validate.

**Comment by zerog2k** [comment]
Thanks @rebornix just want to point out that I actually _do_ like to have the search string seeded from my _selected_ text. This saves me lots of time when the text is actually _selected_.
However the problem seems to be a somewhat different one - it is autoselecting entire line where cursor is, when the text is *not* _selected_.

@bpasero @alexandrudima 

Is there a _different_ setting in which i can turn of the latter behavior, while keeping the ability to control the former?

Thanks,
Jens
