### ISSUE TITLE
Extensions not working since 1.18 Update

### ISSUE THREAD

**Issue by deventity** [Microsoft/vscode#38124]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Home 64Bit

Steps to Reproduce:

1. Launch VSCode with the extensions listed above

Since the 1.18 update, my extensions are not working anymore

My extensions:

-> Atom One Dark Theme
-> Auto Complete Tag
-> Auto Close Tag
-> Auto Rename Tag
-> PHP Debug
-> PHP Formatter
-> vscode-icons
-> CSS Formater
-> vscode-todo

This is the error iam getting when i try to format a css file:

![cssformatter error](https://user-images.githubusercontent.com/33573453/32691065-9a72eaaa-c702-11e7-912e-13078c2aece5.JPG)

This  is the error iam getting when i try to format a php file

![php formatter error](https://user-images.githubusercontent.com/33573453/32691068-b00a566e-c702-11e7-92c4-ac3f7447dd8f.JPG)

And this  is the error when i search for todos, obviously there are JS files. 

![vscode todo error](https://user-images.githubusercontent.com/33573453/32691072-be8911d0-c702-11e7-8a6b-de84dc1608ae.JPG)

I already tried to reinstall the extensions, but no success.
This started to happen right after the 1.18 update.

Reproduces without extensions: No

**Comment by roblourens** [comment]
It sounds like those are all errors coming from the extensions. I'm not aware of anything in vscode that would cause this, and I don't know what those extensions are doing in particular, so I recommend following up with the extension maintainers.
