### ISSUE TITLE
Run to cursor doesn't work as as expected

### ISSUE THREAD

**Issue by richardzeng1985** [Microsoft/vscode#3812]
Repro:
1. Add some code similar like following: 
 
    Int FuncTest(int i)
{
     int j=10;
     int results=i+j;
     return results;
}
 
int main()
{
     int input;
     int results=0;
     cout<<"type an integer to continue:"<<endl;
     cin>>input;
     results=FuncTest(20);
     cout<<"results"<<results<<endl;
     return 0;  
}
 
2. Set a breakpoint at line 
 line: "cout<<"type an integer to continue:"<<endl;" in main() 
3. F5
4. Move to line "cin>>input;", and right click to select "Run to cursor"
  
Observe:
 
"Run to cursor" context menu still pop up there, and 
1)  It only takes effect after I move over the mouse to another place.  
2)  It only takes effect after I select the "Run to cursor" once again, and an addtional breakpoint was added in current line "cin>>input".
 
Note:  I am using a VM created from hyper-v, and this happens very frequently, however, I cannot repro this every time.

**Comment by weinand** [comment]
@richardzeng1985 let me know what C++ extension you are using and I will move this issue over.

**Comment by weinand** [comment]
@richardzeng1985 please file this issue against the C++ extension you are using.
