### ISSUE TITLE
VS Code Icon Like Visual Studio 2017 = Bad Idea 

### ISSUE THREAD

**Issue by taigosantos** [Microsoft/vscode#38127]
You have left the VSCode icon much like the Visual Studio 2017 icon, now I believe this is creating confusion for many who use both programs. You could at least disqualify the icon with a different color.

**Comment by garyng** [comment]
Seriously? What color you want now?
See [The Icon Journey](https://code.visualstudio.com/blogs/2017/10/24/theicon), #35783

**Comment by andy128k** [comment]
Warm orange **was** great.

**Comment by NicoAiko** [comment]
Let it as it is right now! It looks nice with this blue tone.

**Comment by bpasero** [comment]
We currently have no plans to change the icon.
