### ISSUE TITLE
TypeScript service restarting with Angular 5. The TS Language try to start 5 times and dies little after.

### ISSUE THREAD

**Issue by allanhal** [Microsoft/vscode#38136]
- VSCode Version: Code - Insiders 1.19.0-insider (d6fbdcf19716910b26ea81efc95724f2fabe5aa6, 2017-11-10T06:10:30.893Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.13
vscode-eclipse-keybindings|alp|0.9.6
gitlens|eam|6.0.0
mssql|ms-|1.2.1
debugger-for-chrome|msj|3.5.0
LiveServer|rit|3.0.0
vscode-icons|rob|7.17.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide more information about your project. Can you share example code that causes this issue?

Also,  open the output panel and go to the `TypeScript` section. Please share the messages that are being printed in there. This will help us track down what may be going wrong

**Comment by mjbvz** [comment]
Closing as not actionable without more info
