### ISSUE TITLE
"Close Folder" not showing up in command palette.

### ISSUE THREAD

**Issue by mgunt** [Microsoft/vscode#38135]
I occasionally use the "Close Folder" feature in the "File" menu and I would like to know why "Close Folder" does not show up in the command palette. It would be such a nice feature to have in VS Code.

- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:

1. Press `ctrl`+`shift`+`p`
2. Type in "Close Folder"

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
The command got renamed to "Close Workspace".
