### ISSUE TITLE
Can't see open window on MacOS

### ISSUE THREAD

**Issue by jelling** [Microsoft/vscode#38131]
- VSCode Version: v1.18.0
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Open Visual Studio Code; Code opens but no welcome screen appears
2. Try to open an existing project directory (ex. ~/foo)
3. No window is visible but a window is listed under the MacOS Window command (~/foo)
4. Click Window -> Bring All to Front, still can't see open window

I've tried uninstalling and reinstalling VSCode multiple times including manually deleting the preference files in ~/Library with no luck. Will try downgrading to 1.17 next. 

Reproduces without extensions: Yes

**Comment by jelling** [comment]
I downloaded v.1.19-0 Insiders Edition and the window opens. So it's either a preference file for 1.18 or the issue is fixed in 1.19.

**Comment by peterblazejewicz** [comment]
I've 1.19-0 and it persists. I think it simply reappear/disappear at random. When it strucks the following is shown in dev tools console:
```
shell.ts:175 Cannot assign to read only property 'when' of object '#<Object>': TypeError: Cannot assign to read only property 'when' of object '#<Object>'
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22749
    at Array.forEach (native)
    at s (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22664)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22730
    at Array.forEach (native)
    at Object.s [as mixin] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:22664)
    at Object.t.getExcludes (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1268237)
    at t.getExcludes (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10:340445)
    at e.globFn (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10:340135)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:2028495
```
Full snip:
https://gist.github.com/peterblazejewicz/111f7e27abe99d27b8068c65eef06147

**Comment by bpasero** [comment]
@peterblazejewicz can you report your issue as separate one, I do not think it is related to this original issue.

**Comment by bpasero** [comment]
@jelling 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jelling** [comment]
@bpasero yes, that worked. i assume i need to blow away my standard user data dir now? how do i do that / where is that ? I'm on MacOS.

**Comment by bpasero** [comment]
Sorry I am not understanding what could be wrong with your default user data directory that could cause it. Something is corrupt :-/. The default user data dir is: `/Users/<your user name>/Library/Application Support/Code`

**Comment by jelling** [comment]
I blew away that directory and re-installed and it works now. Thank you for your help.
