### ISSUE TITLE
`code --add` breaks if executed repeatedly

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#38138]
- VSCode Version: Code 1.18.0
- OS Version: Darwin x64 17.3.0

Executing a command like `code --add path1 && code --add path2 (...) code --add pathN` completely breaks the window, I only get a couple of paths added no matter what, duplicated icons in the statusbar and the entire thing basically becomes unstable/unusable.

Executing `code --add path1 path2 (...) pathN` works just fine, unfortunately for a high number of paths I can't submit this command to the terminal via the `terminal#sendText` method because of https://github.com/Microsoft/vscode/issues/38137.

**Comment by bpasero** [comment]
@fabiospampinato what exactly happens in your case? For me I just see the last folder not getting added (only 2 work) and an exception in the console. Do you also see an exception?

**Comment by fabiospampinato** [comment]
@bpasero I've made a [screencast](https://mega.nz/#!3FVADSiB!3irMMUy-VPnUkrAwzauVPHPb-BOe_aOOzc54iuH8BoM) to properly illustrate this.

Basically: I only get 2 folders, no exceptions, duplicated icons in the statusbar and the window basically freezes for a while.

**Comment by fabiospampinato** [comment]
@bpasero do you need "more info" from me? If so, what else is needed?

**Comment by bpasero** [comment]
This is a race condition where the first `--add` request causes lots of work to happening. A pushed a change to buffer the requests for `--add` for 100ms before processing them. I think that should solve the issue.
