### ISSUE TITLE
JS #region blocks do not show [-] icon

### ISSUE THREAD

**Issue by reviewher** [Microsoft/vscode#38141]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.20
flow-for-vscode|flo|0.7.2
csharp|ms-|1.13.0
node-debug2|ms-|1.18.4
vetur|oct|0.11.1
vscode-react-native|vsm|0.5.2
highlight-trailing-white-spaces|yba|0.0.2

---

Steps to Reproduce:

1. create a file with a `//#region` block
2. collapse then expand the region

Reproduces without extensions: Yes

Expectation: [-] icon shows when region is expanded, [+] when region is folded

Current Behavior: [+] shows up both places

Folded Icon:

![screen shot 2017-11-12 at 00 18 24](https://user-images.githubusercontent.com/24845478/32696182-219eeace-c73f-11e7-816b-826291950824.png)

Display when expanded (notice it is the same icon):

![screen shot 2017-11-12 at 00 18 31](https://user-images.githubusercontent.com/24845478/32696184-25bc12f8-c73f-11e7-822b-80e6562a62ee.png)

Expanded code block (notice that the icon is clearly different):

![screen shot 2017-11-12 at 00 18 52](https://user-images.githubusercontent.com/24845478/32696185-29083a68-c73f-11e7-967a-4c240e0793d9.png)

**Comment by aeschli** [comment]
I'm not able to reproduce:
![foldicon](https://user-images.githubusercontent.com/6461412/32732092-d65f2f8a-c88b-11e7-9815-61ae7332398b.gif)

**Comment by reviewher** [comment]
Removed and installed 1.18.0 and it seems to work now.
