### ISSUE TITLE
Windows Uninstaller Binary Not Properly Signed

### ISSUE THREAD

**Issue by ecnepsnai** [Microsoft/vscode#38143]
- VSCode Version: 1.18.0
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Enable User Account Control
2. Launch the VS code uninstaller from Apps control panel

![uninstaller](https://user-images.githubusercontent.com/1607109/32696656-b12b2e44-c732-11e7-910d-7954792872d5.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#2416
