### ISSUE TITLE
Icon in the context menu can't be updated after updating VSCode to the latest version

### ISSUE THREAD

**Issue by anthlu** [Microsoft/vscode#38142]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

![untitled](https://user-images.githubusercontent.com/16623398/32696535-a7d20bbe-c7b5-11e7-94b4-2d4ebe775f6b.png)

Steps to Reproduce:

1. The previous version of VSCode is 1.17.2 and the icon color of it is #d97634
2. After updating VSCode, the icon in Start Menu, the icon in Taskbar has been updated, but the icon in context menu can't be updated
3. Uninstalled it, delete ".vscode" folder, "C:\Users\<your username>\AppData\Roaming\Code" folder, restart the computer and reinstall the latest version of VSCode (1.18.0), the icon in the context menu is previous, not latest.

**Comment by bpasero** [comment]
This seems to be an issue with Windows and not VS Code. Closing as we cannot do anything about this.
