### ISSUE TITLE
[folding] Unfold should unfold based on folding history :smile:

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#3814]
```ts
{
  {
    {
      { // cursor
      }
    }
  }
}
```
Pressing [`cmd+shift+[`] several times will fold all of the code, then Pressing [`cmd+shift+]`] several time stuck at the first level.

**Comment by unional** [comment]
Same as https://github.com/Microsoft/vscode/issues/3484?

**Comment by aeschli** [comment]
IMO #3484 makes sense. There, from how I understand it, we only move the cursor on unfold if the cursor has not moved since folding.
But always move the cursor on unfold to the next folding region doesn't make sense to me. The next folding region could be far down in the unfolded region.

Let me know if I misunderstood your request.

**Comment by unional** [comment]
Basically my idea is replicated by what webstorm does. But I understand
your concern.

As I think about it more, maybe webstorm implementation is to separate
cursor and folding target. Can validate it tomorrow.

The idea is during consecutive unfold, it will automatically target the
next available folded code. And the cursor will then point to the newly
unfolded location.

What do you think?

**Comment by aeschli** [comment]
Ah, so just improve the behavior of the unfold action. If the cursor is not on a folded section, look for the next one and unfold that one. I like that idea.

**Comment by aeschli** [comment]
I implemented your last suggestion. This also fixes #3484.

**Comment by unional** [comment]
WebStorm unfolding is based on cursor history.
* Its `fold all` is a series of `fold` to the top level where no more folding is possible.
* Unfold looks at the cursor history:
  * If last cursor position is at a folded code, cursor will move there
  * If last cursor position is not as a folded code, cursor will remain at where the unfolded code is.

:+1:

**Comment by unional** [comment]
Their implementation is more predictable, i.e.:

```js
{
  {
    {
    },
    {  // cursor
    }
  }
}
```
`looking for next folded code` will:

```js
{
  {
    { // cursor
    },
    {
    }
  }
}
```

**Comment by aeschli** [comment]
Thanks for all the comments. I implemented the strategy that unfold will first try to unfold at the current cursor position. If the region at that location is not folded, unfold the first folded region inside that region.

**Comment by joaomoreno** [comment]
I did verify this.
