### ISSUE TITLE
Central storage of settings

### ISSUE THREAD

**Issue by ZeroCoolGOS** [Microsoft/vscode#38146]
This is not an issue but a request.

What I would like to see is a central storage for all user settings.  As a developer I work on multiple workstations.  With that VSCode is my go to app.

What I would imagine is a login system to my Microsoft account (settings stored in OneDrive) and whenever I would log into my account on another system my settings would come with me.

These settings would include how I run my spacing's, all the way up to how I like my UI laid out.

I could understand that some settings would not be transferred such as extensions, but having a list of "liked" extensions would also be nice so if I need to install them then I can.

Having these settings stored in something like one drive would also allow for me to directly edit them if needed or even copy my settings and email them to a friend.

Thank you for your time and the product is great.  Use it every day.

**Comment by agauniyal** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by sandy081** [comment]
Duplicates #2743.

Also there is an extension in market place to do it - https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync which might help to fix your requirement
