### ISSUE TITLE
npm 安装依赖时  放大缩小窗口， 控制台输入变化

### ISSUE THREAD

**Issue by skygst102** [Microsoft/vscode#38147]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|0.23.0
vs-code-css-comments|ash|1.0.3
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
open-html-in-browser|cod|0.1.21
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
gitlens|eam|6.0.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.20
prettier-vscode|esb|0.24.0
git-project-manager|fel|1.4.0
php-debug|fel|1.11.1
auto-rename-tag|for|0.0.15
code-runner|for|0.8.3
minify|Hoo|0.3.0
animate-css|Hri|1.0.0
task-master|ian|0.1.39
autofilename|Jer|0.1.3
docthis|joe|0.6.0
vscode-github|Kni|0.23.0
string-manipulation|mar|0.2.0
prettify-json|moh|0.0.3
mssql|ms-|1.2.1
cpptools|ms-|0.14.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
nodejs-docs|Muk|0.2.2
vscode-css-peek|pra|1.3.1
LiveServer|rit|3.0.0
code-settings-sync|Sha|2.8.5
css-auto-prefix|spo|0.1.4
vscode-gulp|tan|0.0.4
easy-snippet-maker|tar|0.0.6
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
English please.
