### ISSUE TITLE
"..\" doesn't work for "files to include" when searching files

### ISSUE THREAD

**Issue by wizofaus** [Microsoft/vscode#38144]
- VSCode Version: 1.17.2
- OS Version: Win 7 SP 1

Steps to Reproduce:

1.  Access search tab
2.  Type a word to search for
3.  Under "files to include", type ..\siblingPath
4.  Hit enter

Expected: any files under ..\siblingPath containing word/pattern are shown. Actual: get "No results found in ..\siblingPath".
Works fine if absolute path used, or relative path *below* the current directory.

This is very useful when you have a test project open but the interesting source files are in a sibling directory.

**Comment by roblourens** [comment]
`./../siblingPath` will probably work for now.

**Comment by wizofaus** [comment]
Indeed it does, thanks for that.

**Comment by jackpot1136** [comment]
No, thank you

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/common/queryBuilder.ts#L105
