### ISSUE TITLE
[php] autocomplete is not showing user variables

### ISSUE THREAD

**Issue by h2u** [Microsoft/vscode#3815]
I don't really understand how it's working. VSCode does not suggest me any of my variables. Only globals as $_COOKIE and etc.
I was trying to type few letters of my variable name and press Ctrl+Space, and it's says "No suggestions".

**Comment by weinand** [comment]
@h2u are you using a php extension for VS Code?

**Comment by h2u** [comment]
No, i don't use any php extensions.

**Comment by mattacosta** [comment]
Seems I'm only getting autocomplete suggestions when I start typing a variable name _without_ the leading $.

**Comment by h2u** [comment]
If i have variable like: $string = 'my string'; and on next line i start writing "$st" or "st" - there is no any suggestions like $string variable.

![image](https://cloud.githubusercontent.com/assets/5619582/13648673/8d9be2ac-e642-11e5-9fe4-759729297eb9.png)

**Comment by mattacosta** [comment]
Huh. Debugged a little more, seems I need to not have a leading $ AND press the up arrow on my keyboard to get it show up as a possible selection. Either way, definitely bugged.

**Comment by h2u** [comment]
Thank you, @mattacosta for information.
But how can i trigger the completion provider? :)

**Comment by felixfbecker** [comment]
Afaik the whole PHP Intellisense is only based of a list of global functions and superglobals. I already thought about writing a PHP extension for better Intellisense, that actually constructs an AST of the code and looks at the variables in the current scope etc., suggests methods for classes following PSR autoloading, but I don't have the time for it.

**Comment by DrCacho** [comment]
The same happens to me. VS Code 0.10.11 on OSX El Capitan.
