### ISSUE TITLE
Remove built-in CSS snippets

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#38152]
`"editor.snippetSuggestions": "top"` 

3 permanent CSS suggestions and they are always on top:

![suggestion](https://user-images.githubusercontent.com/9638156/32699484-a7935790-c7c7-11e7-98e4-5ee0e989af5c.png)

1. **border** – perhaps was created to make it easier to write (has 3 parts). Now can easily be replaced with Emmet.
2. **gradient** – has vendor prefixes. 
3. **transition** – has vendor prefixes

Is this a kit? All the prefixed properties you'll ever need?) Do they target certain browser versions?

I think it would be better to just deprecate and delete them (or, maybe, somehow move them into user snippets).

**Comment by aeschli** [comment]
I agree the snippets don't have much value. Snippets should always be offered by extension that users that uninstall.
