### ISSUE TITLE
search.exclude not working with projects opened from an UNC path

### ISSUE THREAD

**Issue by frame** [Microsoft/vscode#38151]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro (OS Build 16299.19)

Steps to Reproduce:

1. Open a project with a **node_modules** or **bower_components** folder (those are the default excludes) on an UNC path (`\\Server\Share\Project\`)
2. Search for string that would be present in those excluded folders (e.g. "copyright")
3. Results from excluded folders will show up.

Reproduces without extensions: Yes (Screenshot is with extensions, but I tried without any on a separate machine)

Screenshot shows the unfiltered result. I use a tooltip to show that the project is on an UNC path. "Use Exclude Settings" is enabled. There are no User- or Workspace Settings loaded to make sure they aren't interfering.

![search exclude](https://user-images.githubusercontent.com/339569/32698965-633675be-c7ae-11e7-8ab7-1a274b5fb5ca.png)

(pink parts protect privacy)

**Notes:**

- Adding a custom `search.exclude` to user or workspace settings also fails.
- Workaround: Mapping the UNC Path to a drive letter (P:\Project\) will make the search work! So my guess is the UNC path messes with the exclude pattern.
- Workaround: Enabling "Use Ignore Files" will make the search work (but will exclude not enough files in my case)
- `files.exclude` works fine when the project is opened from an UNC path, only `search.exclude` seems to be affected.

**Comment by roblourens** [comment]
Thanks, I can repro

**Comment by roblourens** [comment]
This is from https://github.com/Microsoft/vscode/issues/24677.

**Comment by roblourens** [comment]
I believe this is actually the same as #38165
