### ISSUE TITLE
command 'xxx' not found

### ISSUE THREAD

**Issue by JowayYoung** [Microsoft/vscode#38153]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.All Extensions commands are unavailable in MacOS

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Please provide more info that allow us to reproduce

**Comment by mathiasose** [comment]
* Ubuntu 17.10.
* VSCode 1.18

I also have this problem on since upgrading to 1.18.
I can bring up the actions list (CTRL+E, >) and find plugin actions there, but when I try to run them I get `error: command 'xxx' not found`.

This seems to be a problem with actions from any plugin. Actions that are not from a plugin work fine.

I tried force-reinstalling vscode, didn't fix it. I also tried disabling all plugins except a single one (Python plugin by Microsoft), and the problem was still present.

**Comment by jrieken** [comment]
So, the message is literally like this: `error: command 'xxx' not found.` with the command being `xxx`?

**Comment by mathiasose** [comment]
Correct. I have attached some screengrabs.

![screenshot from 2017-11-13 21-37-11](https://user-images.githubusercontent.com/2864935/32748050-39e4bcc6-c8bb-11e7-9083-3164a761cd3b.png)
![screenshot from 2017-11-13 21-37-17](https://user-images.githubusercontent.com/2864935/32748055-3f2de68a-c8bb-11e7-97f6-15fa19a6de81.png)

**Comment by mathiasose** [comment]
> Can you also check if your extension host has started successfully, e.g. by trying to get intellisense in a TS/JS file

I'm not entirely sure which features of vscode are intellisense and not.
Things like autocomplete while typing and emmet work fine, in Python and in JS.

**Comment by jrieken** [comment]
Is this only with commands from the python extension?

**Comment by mathiasose** [comment]
Yeah, I've been using vscode some more today and it seems to be a Python-related issue. I tried installing the `freakypie.code-python-isort` plugin, which didn't work either, but I was able to open a html file with a command from `techer.open-in-browser`. I also noticed the context menu actions like "go to definition" etc. are missing from Python files, but present in JS files.

![screenshot from 2017-11-14 12-46-54](https://user-images.githubusercontent.com/2864935/32778411-1179ee80-c93a-11e7-9da0-38e2c1065646.png)

So it seems to be some kind of problem with the Python integration that Python-related plugins rely on?

**Comment by jrieken** [comment]
Can you check the developer console (F1 > Developer Tools > Console) and also what is the exact name/id of the python extension? Background is that we did rename the extension and that might be related 

/cc @sandy081

**Comment by jrieken** [comment]
@mathiasose One more question: Does this happen with commands from the "recently used" section only or with all?

**Comment by mathiasose** [comment]
Aha, so that's where you hid the debug info.

	[Extension Host] Activating extension `ms-python.python` failed:  Cannot find module '/home/ose/.vscode/extensions/ms-python.python-0.8.0/out/client/extension'
	t.log @ console.ts:123

	console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module '/home/ose/.vscode/extensions/ms-python.python-0.8.0/out/client/extension'
		at Function.Module._resolveFilename (module.js:470:15)
		at Function.Module._load (module.js:418:25)
		at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:498891)
		at Module.require (module.js:498:17)
		at require (internal/module.js:20:19)
		at Function.a [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:4:27796)
		at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:504623
		at t._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:504735)
		at t._activateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:503297)
		at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:501475)

And the file called `extensions` is indeed missing

    ➜  ~ ls -la /home/ose/.vscode/extensions/ms-python.python-0.8.0/out/client/    
    total 24
    drwxrwxr-x 6 ose ose 4096 2017-11-10 09:29 .
    drwxrwxr-x 4 ose ose 4096 2017-11-10 09:29 ..
    drwxrwxr-x 2 ose ose 4096 2017-11-10 09:29 telemetry
    drwxrwxr-x 2 ose ose 4096 2017-11-10 09:29 typeFormatters
    drwxrwxr-x 8 ose ose 4096 2017-11-10 09:29 unittests
    drwxrwxr-x 2 ose ose 4096 2017-11-10 09:29 workspaceSymbols

**Comment by mathiasose** [comment]
Un- and re-installing the python plugin itself resolved the issue. Seems obvious in hindsight. Before I posted in this thread, I did try reinstalling vscode with `apt install code --reinstall` though, but that didn't help.

Just for the record, the isort plugin is still failing after reinstall, but that might just be an error/incompatibility in that particular plugin?

    Running the contributed command:'extension.isort' failed.: Error: Running the contributed command:'extension.isort' failed.
	    at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:412111)
	    at t.e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509277)
	    at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354645)
	    at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354335)
	    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353362
	    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355281
	    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85085
	    at e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84368)
	    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86090)
	    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:144000)

**Comment by jrieken** [comment]
Assigning @sandy081 because this points towards a bad extension rename issue

**Comment by sandy081** [comment]
@mathiasose 

By any chance, you remember what is this folder name on the disk before re-installing the python extension? 

When was the last time you updated the python extension?

**Comment by mathiasose** [comment]
This path? `/home/ose/.vscode/extensions/ms-python.python-0.8.0/`?

The Python plugin was definently on the latest version (there was no prompt to update it), but I'm not sure when it was last updated. Thursday *maybe*.

**Comment by sandy081** [comment]
Yes, all extensions are installed under `~/.vscode/extensions/` folder. When the problem was existed, It would be helpful to know what is the name and version of the python extension under this folder. Unfortunately, we cannot know this now due to the re-install which would have deleted the corrupted.

Will wait if others can reproduce it and can get this information
