### ISSUE TITLE
Electron 1.8.x: notifications are not showing up

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38155]
Somehow the message text falls out of the box:

![image](https://user-images.githubusercontent.com/900690/32700733-6f786538-c7c9-11e7-877f-f703dbe9d5e4.png)

**Comment by jens1o** [comment]
And I thought I was some kind of color blind ...

**Comment by bpasero** [comment]
Fix seems easy enough by changing the old-school `float: right` to `display: flex`.

**Comment by jens1o** [comment]
no way to get this into 1.19.1? :

**Comment by bpasero** [comment]
@jens1o this fix is only needed once we update Electron, which did not happen so far...

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43770 and can be tried out in our preview release: https://code.visualstudio.com/insiders/
