### ISSUE TITLE
npm scripts doesn't terminate when you run them as task

### ISSUE THREAD

**Issue by savarex** [Microsoft/vscode#38156]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.0.0
tslint|eg2|1.0.21
Angular2Tests|Mar|0.7.3
mssql|ms-|1.2.1
debugger-for-chrome|msj|3.5.0
wallaby-vscode|Wal|1.0.65

---

Steps to Reproduce:

1. Create an empty package.json with this content
```
{
  "name": "test-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "echo 'done'"
  },
  "author": "",
  "license": "ISC"
}
```
2. Press CTRL+SHIFT+B and select npm:build task
3. Task starts but it doesn't terminate. You have to manually terminate task clicking bin button and when you click on bin button this error appears
![capture](https://user-images.githubusercontent.com/6420148/32701595-f8c9c6a6-c7d8-11e7-9c10-91cb87ad8de7.PNG)

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Dups #37934
