### ISSUE TITLE
Garbled text on interface and code

### ISSUE THREAD

**Issue by cyphrack** [Microsoft/vscode#38159]
- VSCode Version:
1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7 Arch 64 bits
- OS Version:
Kali Linux Rolling. Fully updated.

Steps to Reproduce:

1.Open visual studio code
2. Look at text (either on the interface or code)

Reproduces without extensions: Yes

![kazam_screenshot_00000](https://user-images.githubusercontent.com/30382027/32702185-8d0c5ada-c7a8-11e7-8d4f-533ff42d2296.png)
![kazam_screenshot_00001](https://user-images.githubusercontent.com/30382027/32702186-8d225e7a-c7a8-11e7-912b-c865f4019761.png)
![kazam_screenshot_00002](https://user-images.githubusercontent.com/30382027/32702187-8d373d22-c7a8-11e7-9ea3-c82c6436d57d.png)

**Comment by alexandrudima** [comment]
Might be a dup of #35675
