### ISSUE TITLE
Both old and new icons appear on Mac

### ISSUE THREAD

**Issue by bluzi** [Microsoft/vscode#38154]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.21
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
gitlens|eam|6.0.0
python|ms-|0.8.0
azure-account|ms-|0.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open code 
2. There you go, there are two instances, one with the previous logo and one with the new logo.

When I open another project, it opens in the second instance, and then both instances are active.

When I open more than 2 projects, it gets **really** annoying, because both icons are active and I must guess which icon holds the 2 projects, and when I should use cmd+tab vs cmd+`...

![image](https://user-images.githubusercontent.com/13808883/32700287-71e140d6-c7cb-11e7-8977-17bcf16b6b84.png)

Reproduces without extensions: Yes

**Comment by garyng** [comment]
I guess Mac caches the icon? Did you try updating to the latest version (v1.18)?

**Comment by bpasero** [comment]
Yes looks like a caching issue, nothing we can do about.
