### ISSUE TITLE
Feature Request: Define settings for a set of folders

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#38162]
This is feature-request and settings

Steps to Reproduce:
1. Create workspace.
2. In "project/.vscode/settings.json" set:
`{
   "include": ["${commonWorkspacesSettingsFolder}/my-js-common-settings.json"]
}`
Where: `${commonWorkspacesSettingsFolder}` is new "(...)/Code/CommonWorkspaceSettings" folder in User Settings.
and user created "my-js-common-settings.json" file is import settings to this workspace.

Modifying "my-js-common-settings.json" changes settings for each workspace that will import this file.
This is something other than global user settings for the entire VS Code.
These are settings for similar projects, similar in many ways.

3. The imported settings may be overwritten in the "project/.vscode/settings.json" file.
Example "my-js-common-settings.json" file:
`{
   "window.zoomLevel": 0,
   "editor.fontSize": 13
}`
Example "project/.vscode/settings.json" file:
`{
   "include": ["${commonWorkspacesSettingsFolder}/my-js-common-settings.json"],
   "editor.fontSize": 14,
   "files.autoSave": "afterDelay"
}`

Value `14` overwrite value `13` from "my-js-common-settings.json" file in `"editor.fontSize"` setting.
Setting `"window.zoomLevel": 0` is common for workspaces.
Setting `"files.autoSave": "afterDelay"` is own for this workspace.

**Comment by sandy081** [comment]
@lukaszpolowczyk Can you please explain what will this new feature request achieve which cannot be done by current solution?

**Comment by lukaszpolowczyk** [comment]
@sandy081 

There are Global Settings - working on everything.
There is a setting for the Project / Folder - working only there.


Currently:
- Creates a project
- I set the settings for the project
- I do another, similar project
- I copy the settings file from the first project
- Paste the settings file into a new similar project
- I modify slightly, or not all settings for new project (there are some differences)
- I want to change the setting common to the first and new project
- I have to change the setting in one and the other setting file (sometimes I forget it, something works differently, unnecessary confusion)
- I create a third project - he has no common law with the first or second project - so these settings can not be in Global settings!

With my proposition:
- I create a project
- Set the setting for the project
- I do another similar project
- Set `include` and create a common file from this file (automatically placed in the" Code / commonSettings "folder - you need the" Create from this CommonSetting "button in the Settings tab for Wokspace).
- As I want to change something in common, I change in CommonSettings
- Done.
- The third project has its own settings, unlike the two projects. There is no problem.

**Comment by earshinov** [comment]
Another use case is synchronizing your settings across multiple computers.

For example, I would like to share most of my settings between work and home machines, except the font size. If the "include" setting was available, I could extract the common settings to a separate file, put the file into my Dropbox folder, and then "include" it into `settings.json` on my two machines.

**Comment by sandy081** [comment]
/duplicate 

#15909
