### ISSUE TITLE
Toolbar for file type (activate from extensions, example with Markdown buttons).

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#38164]
New API for Extensions.

Steps to Reproduce:

1. Open file, example "file.md"
2. In Editor top or botton show toolbar with bolb, italic, header etc. functions.

API decide in which bar in witch file types shows.
It's just an idea. How to look exactly like the API I leave more competent people.

**Comment by mjbvz** [comment]
Thanks for the suggestion. However VS Code doesn't have traditional toolbars so this is really by-design. Adding a toolbar would be out of line with what we do for other languages.

For markdown, there are snippets that can bold text and insert headers. That may offer what you are looking for
