### ISSUE TITLE
Caret moving silently backward when window moves

### ISSUE THREAD

**Issue by Rydgel** [Microsoft/vscode#38163]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-elixirc-mix-linter|PTD|0.0.3
file-icons|fil|1.0.5
vscode-elixir|mjm|1.1.0
ayu|tea|0.8.0

---

Steps to Reproduce:

1. Move the window
2. Type something
3. The carret moved backward without noticing

![bug](https://media.giphy.com/media/26u3ZtPiKlw6Zjnfa/giphy.gif)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
I could not reproduce on Windows. Will try later on a mac.

**Comment by Rydgel** [comment]
Still having the issue with VSCode Version: Code 1.18.1 FYI

**Comment by Rydgel** [comment]
Also interesting note:
When my cursor is inside an input text (like the search input), the caret moves to the **beginning** of the input when moving the window.

**Comment by alexandrudima** [comment]
This also does not reproduce on a mac. 

@Rydgel I believe there might be something off in our environment. Can you please try to reproducing when logging in as OSX guest or something ?

**Comment by Rydgel** [comment]
Yeah I just did that to a new user I created on the mac.
Still the same issue.

**Comment by Rydgel** [comment]
I don't have the issue with window.nativeTabs activated.

**Comment by alexandrudima** [comment]
I believe this is some obscure weird Electron bug.
