### ISSUE TITLE
Git: checkIgnore nested Promise/resolve bug (with PR)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#38169]
@jrieken 
@joaomoreno 

While working and testing PR for issue #37337 (warning for unsaved files before commit), I encountered
what I think are two bugs.  The first I was able to identify and fix as far as I can tell.  I am no
Typescript expert so maybe I am off-base.  Second issue not so sure about, seems to return
an extra set entry that is empty.  Have to investigate this one further.  NOTE: could this be related to
#37857 ?

For first issue:
If there are no resulting filePaths entries, an empty set should be returned via Promise.  The code
seems to return a promise within a promise which gets lost.  I presumed should be
  resolve(new Set<string>());
  NOT: Promise.resolve(new Set<string>());

	checkIgnore(filePaths: string[]): Promise<Set<string>> {
		return this.run(Operation.CheckIgnore, () => {
			return new Promise<Set<string>>((resolve, reject) => {

				filePaths = filePaths.filter(filePath => !path.relative(this.root, filePath).startsWith('..'));

				if (filePaths.length === 0) {
					// nothing left
                                        *** Nested Promise ***
					return Promise.resolve(new Set<string>());
				}

				// https://git-scm.com/docs/git-check-ignore#git-check-ignore--z
				const child = this.repository.stream(['check-ignore', '-z', '--stdin'], { stdio: [null, null, null] });
				child.stdin.end(filePaths.join('\0'), 'utf8');

				const onExit = (exitCode: number) => {
					if (exitCode === 1) {
						// nothing ignored
						resolve(new Set<string>());
					} else if (exitCode === 0) {
						// paths are separated by the null-character
						resolve(new Set<string>(data.split('\0')));
					} else {
						reject(new GitError({ stdout: data, stderr, exitCode }));
					}
				};

Fixed with PR #38170

**Comment by jrieken** [comment]
Nice find.

**Comment by jrieken** [comment]
Adding `candidate`-label for consideration

**Comment by joaomoreno** [comment]
Great catch! I actually reviewed this code and didn't catch this.

**Comment by jrieken** [comment]
Not the first time that I am wishing for a lint rule which checks all code paths inside a promise initialiser...

**Comment by jrieken** [comment]
I have cherry-picked this change for the 1.18.1 release

**Comment by cleidigh** [comment]
Thanks guys !
