### ISSUE TITLE
Use folder/project name first in application title in taskbar

### ISSUE THREAD

**Issue by jkovzels** [Microsoft/vscode#38160]
This is my life now:
![image](https://user-images.githubusercontent.com/351671/32702159-bfeb87c0-c7e2-11e7-8e11-5e3e9a0d8b62.png)

I think that it is more useful to show the name of the project or folder name in taskbar instead of the name of the file in active tab.

**Comment by bpasero** [comment]
This is configurable via the `window.title` setting.
