### ISSUE TITLE
Task with forward slashes, isShellCommand and in Windows fails to execute

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3816]
Only happens in Windows.

I have the file `folder/hello.cmd` in my workspace. When I setup the following task I always get the same error:

```
{
	"version": "0.1.0",
	"command": "./folder/hello",
	"isShellCommand": true,
...
```

```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

It appears that Code is launching a command named `.`.

When I surround the command with quotes it works:

```
	"command": "\"./folder/hello\""
```

What is happening is that due to `isShellCommand`, `cmd.exe` is the spawned process. Now, `cmd.exe`'s optional arguments always start with forward slashes, so it seems to incorrectly assume that `/folder` and `/hello` are options, leaving the `.` to be the command to execute.

**Comment by joaomoreno** [comment]
cc @egamma

**Comment by dbaeumer** [comment]
The solution for this is to use OS specific settings in the tasks.json file. Something like
```json
{
    "version": "0.1.0",
    "command": "./folder/hello",
    "windows": {
         "command": ".\folder\hello"
    }
    "isShellCommand": true,
}
```

The task framework doesn't abstract over the OS you are running on like npm does for example.
