### ISSUE TITLE
VS Code adds all files from user folder to git

### ISSUE THREAD

**Issue by olhapi** [Microsoft/vscode#38173]
![2017-11-13_03-36-34](https://user-images.githubusercontent.com/4780263/32706218-42eb12da-c824-11e7-893c-2fbe17aba1a3.png)

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|0.17.0
project-manager|ale|0.23.0
vs-code-css-comments|ash|1.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.13
vscode-eslint|dba|1.4.3
vscode-dash|dee|1.7.1
es7-react-js-snippets|dsz|1.2.0
gitlens|eam|6.0.0
vscode-html-css|ecm|0.1.8
EditorConfig|Edi|0.11.1
vscode-npm-script|eg2|0.3.3
RunOnSave|eme|0.0.16
prettier-vscode|esb|0.24.0
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
ftp-simple|hum|0.5.8
vscode-codemetrics|kis|1.10.0
HTMLHint|mka|0.4.0
vscode-attrs-sorter|mrm|2.1.0
vscode-postcss-sorting|mrm|3.0.1
vscode-stylefmt|mrm|2.5.0
node-debug2|ms-|1.18.4
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|3.5.0
vscode-jest|Ort|2.4.5
emoji|Per|0.0.3
ejs-language-support|Qas|0.0.1
vscode-icons|rob|7.17.0
sass-indented|rob|1.4.5
code-settings-sync|Sha|2.8.5
stylelint|shi|0.30.0
vscode-csstree|sme|0.5.0
vscode-react-native|vsm|0.5.2
quokka-vscode|Wal|1.0.79
vscode-todo-highlight|way|0.5.11
twig|wha|1.0.2
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Create a git repository in user folder
2. Run VS Code
3. Open any project folder with or w/o git repository inside
3. Deleting git repository from user folder fix the issue

Reproduces without extensions: *Yes*

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by olhapi** [comment]
@joaomoreno that's true, that's what I did after I found an issue. I suppose VS Code would use my project git repository instead of user folder repository, isn't that a bug?

**Comment by joaomoreno** [comment]
VS Code will use your project git repository, even if it is contained within your home directory. You just need to open a file or open the root of that repository as a folder in VS Code.
