### ISSUE TITLE
[TextEditorOptions] support end of line

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#3817]
In the [EditorConfig](https://github.com/editorconfig/editorconfig-vscode) plugin, we want to implement `end_of_line` as well. In the latest VS Code release, I noticed that we have a `files.eol` setting now. Would it be possible to expose this to the `TextEditorOptions` interface to set this on the fly?

// @alexandrudima

**Comment by alexandrudima** [comment]
@SamVerschueren I've just added a way to do that this morning via `textEditor.edit()`.

We thought to put it on the `editBuilder` since it changes the document content.

fyi @jrieken

**Comment by alexandrudima** [comment]
The relevant commit is 45906d91e44bc4e62e917184933ec3e92dbacc26

**Comment by SamVerschueren** [comment]
Awesome, thanks! The only thing that's missing for an entire `EditorConfig` integration is `charset`. There is already an open issue for this https://github.com/Microsoft/vscode/issues/824

**Comment by alexandrudima** [comment]
fyi @bpasero editor config can contain `charset` configurations.

Also missing from the API: `trim_trailing_whitespace` and `insert_final_newline`, but I think there are workarounds for these last two (submitting edits to the text editor).

**Comment by bpasero** [comment]
@alexandrudima would it make sense to have charset on the model and me picking it up from there?

**Comment by alexandrudima** [comment]
@bpasero I don't think that would work, because the charset should be used when creating the model, it would be too late to have it as a setting on a model.

**Comment by SamVerschueren** [comment]
Maybe we should track that in a different issue?

**Comment by SamVerschueren** [comment]
Is an API for changing `charset` somewhere on the roadmap? It's the last missing piece for `EditorConfig`.

**Comment by jrieken** [comment]
No plans yet, will also be a little extra work as for us. I have created https://github.com/Microsoft/vscode/issues/5318 for taht

**Comment by SamVerschueren** [comment]
Thanks @jrieken
