### ISSUE TITLE
It always pops up the git credential dialog

### ISSUE THREAD

**Issue by Fang3s** [Microsoft/vscode#38174]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
xml|Dot|1.9.2
debugger-for-chrome|msj|3.5.0

---

Steps to Reproduce:

1. Reopen vscode or every minutes (I have closed all files in last folder and restart it and open other files under another folder)
2. Automatically pop up the git credential dialog.

![image](https://user-images.githubusercontent.com/6383616/32707119-9f21df10-c85c-11e7-8f85-34debf009e44.png)

![image](https://user-images.githubusercontent.com/6383616/32707047-353cd000-c85c-11e7-8b32-d01fe609fd54.png)

![image](https://user-images.githubusercontent.com/6383616/32706995-ec7cf62e-c85b-11e7-843e-0e6cfb504000.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
#34684
