### ISSUE TITLE
Searching for "travis" in quick open, in vscode repo, doesn't find it easily

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3818]

**Comment by joaomoreno** [comment]
Not sure if you fixed or created an issue for it.

**Comment by bpasero** [comment]
Not fixed, post GA I might replace the scorer with something that works.

**Comment by bpasero** [comment]
I introduced an extra boost of +5 points for consecutive matches in a string. Other scorers seem to do that to boost those matches higher over others.
