### ISSUE TITLE
 Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38184]
Issue Id: <b>491a8c53-cfff-6865-e62d-a47912844fe1</b><br /><br />*Versions* <br />- 1.18.0<br />-  af39ef560060e7e8ba8d75983c9ec1da3f4d2a20<br />*Stack* <br />TypeError: Cannot read property '_id' of undefined<br />	at /out/vs/workbench/node/extensionHostProcess.js:4:439033 <no sourcemaps><br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/srcvs/workbench/node/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />	at <anonymous><br />

**Comment by bpasero** [comment]
Seems to originate from [`NavigateTypeAdapter.provideWorkspaceSymbols`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L406)
