### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'lineNumber' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38188]
Issue Id: <b>99167016-fdbe-0d82-a2e8-48cf5b60cf99</b><br /><br />*Versions* <br />- 1.18.0<br />-  af39ef560060e7e8ba8d75983c9ec1da3f4d2a20<br />*Stack* <br />TypeError: Cannot read property 'lineNumber' of null<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L80:58 (lineNumber)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L80:58 (lineNumber))<br />[/vs/editor/contrib/suggest/browser/suggestModel.ts#L339:16](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L339:16)<br />[/vs/base/common/async.ts#L565:3 (runner)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/async.ts#L565:3 (runner))<br />

**Comment by jrieken** [comment]
should be fixed by the fix for #38185
