### ISSUE TITLE
SCM: opening view for the first time shows weird focus in repository list

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38197]
Steps to Reproduce:

1. reload window
2. open SCM view for the first time

=> the repositories list shows both a selected repository as well as focus (thin blue border):

![image](https://user-images.githubusercontent.com/900690/32712657-0da6caac-c846-11e7-9f52-cc996d505843.png)

**Comment by joaomoreno** [comment]
@bpasero You forgot selection in the ugly `!important` rule: https://github.com/Microsoft/vscode/commit/e103c4f144b6fb262481afc686773d63aa973e20
