### ISSUE TITLE
Go to definition not working for objects in function parameters

### ISSUE THREAD

**Issue by csnv** [Microsoft/vscode#38198]
- VSCode Version: 1.18
- OS Version: Mac OS 10.12.6

Go to definition doesn't work for the following snippet, when ctrl+clicking on this.fn():
```
a({
	fn: function() {
		this.fn();
	}
});
```

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/11072

The root cause is that our IntelliSense does not understand what `this` is inside of object literals
