### ISSUE TITLE
Add a setting for a lighter settings/keybindings editing experience

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#3819]
Both for settings and keybindings:
- [x] Do not open the default read-only settings buffer
- [x] Do not show the information message
- [ ] Open settings on the side

**Comment by bpasero** [comment]
:+1:

**Comment by egamma** [comment]
:+1: it is frustrating to always close the default settings buffer, when you do not need it. 

We could provide an action/link that opens all the settings on the side.

Should we do the same for the keybindings?

**Comment by bpasero** [comment]
Yeah why not.

**Comment by joaomoreno** [comment]
Should it even be the default?

**Comment by bpasero** [comment]
Not sure, the only ones complaining so far are you and me ;)

**Comment by joaomoreno** [comment]
Yeah but I have a feeling this is one of those things that people just assume they have to live with, until they realise it doesn't need to be so. Might be wrong.

**Comment by bpasero** [comment]
Pushed a change so that (per workspace) you can decide to never show the info message again!

**Comment by joaomoreno** [comment]
:+1:

**Comment by bpasero** [comment]
We also have a setting now to disable opening default settings (`workbench.settings.openDefaultSettings`)

**Comment by bpasero** [comment]
I think we are good.
