### ISSUE TITLE
 Cannot read property 'trigger' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38194]
Issue Id: <b>0b018b94-8341-6ab2-add8-42a548540f49</b><br /><br />*Versions* <br />- 1.18.0<br />-  af39ef560060e7e8ba8d75983c9ec1da3f4d2a20<br />*Stack* <br />TypeError: Cannot read property 'trigger' of null<br />[/vs/editor/contrib/folding/browser/folding.ts#L178:50 (trigger)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/contrib/folding/browser/folding.ts#L178:50 (trigger))<br />[/vs/editor/contrib/folding/browser/folding.ts#L82:10 (onModelContentChanged)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/contrib/folding/browser/folding.ts#L82:10 (onModelContentChanged))<br />[/vs/base/common/callbackList.ts#L36:22 (apply)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/callbackList.ts#L36:22 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/editor/common/commonCodeEditor.ts#L134:34 (fire)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/common/commonCodeEditor.ts#L134:34 (fire))<br />[/vs/base/common/callbackList.ts#L36:22 (apply)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/callbackList.ts#L36:22 (apply))<br />[/vs/base/common/event.ts#L123:26 (call)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/base/common/event.ts#L123:26 (call))<br />[/vs/editor/common/config/commonEditorConfig.ts#L108:21 (fire)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/common/config/commonEditorConfig.ts#L108:21 (fire))<br />[/vs/editor/common/config/commonEditorConfig.ts#L138:7 (_recomputeOptions)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/common/config/commonEditorConfig.ts#L138:7 (_recomputeOptions))<br />[/vs/editor/common/commonCodeEditor.ts#L190:22 (updateOptions)](https://github.com/microsoft/vscode/blob/dcee2202709a4f223185514b9275aa4229841aa7/src/vs/editor/common/commonCodeEditor.ts#L190:22 (updateOptions))<br />

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/b7201a6ed13b7af42304315e47a2045f1d5ba1cc
