### ISSUE TITLE
 Cannot read property 'offset' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#38196]
Issue Id: <b>7e4dbf49-b347-466b-db1d-cf239d4c804d</b><br /><br />*Versions* <br />- 1.19.0-insider (11/10/2017 6:14:57 AM)<br />*Stack* <br />TypeError: Cannot read property 'offset' of undefined<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L226:90](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L226:90)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L222:125 (nls)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L222:125 (nls))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#L213:6](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L213:6)<br />[/vs/base/common/winjs.base.raw.js#L621:0 (Debug)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L621:0 (Debug))<br />[/vs/base/common/winjs.base.raw.js#L1052:0 (_run)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1052:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1569:0 (ex)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1569:0 (ex))<br />[/vs/base/common/winjs.base.raw.js#L1458:0 (Promise)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1458:0 (Promise))<br />[/vs/base/common/winjs.base.raw.js#L1816:0 (forEach)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1816:0 (forEach))<br />[/vs/base/common/winjs.base.raw.js#L912:0 (_progress)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L912:0 (_progress))<br />[/vs/base/common/winjs.base.raw.js#L1569:0 (ex)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1569:0 (ex))<br />[/vs/base/common/winjs.base.raw.js#L1479:0 (_setCompleteValue)](https://github.com/microsoft/vscode/blob/d6fbdcf19716910b26ea81efc95724f2fabe5aa6/src/vs/base/common/winjs.base.raw.js#L1479:0 (_setCompleteValue))<br />

**Comment by bpasero** [comment]
@sandy081 fyi this is insiders.

**Comment by Mofiqul** [comment]
I also had the same issue and it took more than 2 minutes to get vs code ready for start coding.
The error message has disappeared after removing these plugins
-- [Node.js Extension Pack ](https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack)
-- [Material  theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
I still have issue with 
-- [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
-- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
these two extension takes too long to load and make vs code ( editor only ) unresponsive.
