### ISSUE TITLE
Auto Import for JavaScript and TypeScript

### ISSUE THREAD

**Issue by sqlProvider** [Microsoft/vscode#38204]
- VSCode Version: 1.19.0-insider (1.19.0-insider)
- OS Version: macOS Sierra 10.12.6 (16G1036)

I use TSLint. I added ordered imports in my rules. Maybe imports auto alphabetized.

**Comment by mjbvz** [comment]
This falls under https://github.com/Microsoft/TypeScript/issues/10020
