### ISSUE TITLE
November Issue Grooming - review, categorization, assignment

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#38209]
During November we want to improve our issue management. As a first step we will review the assigned issues. During the review pass please make sure to:

- close obsolete/fixed issues
- each issue needs a **type** label, that is one of: `Bug`, `Feature-Request`, `Debt`, `Needs more Info`, `Question`, `Under-Discussion`, `upstream`:
  - Bug - the implementation of a feature is not correct
  - Feature-Request - request to change the proper implementation of a feature or a request for a new feature that needs to be implemented.
  - Under Discussion - not decided whether the issue is a bug or feature
  - Debt - improve the implementation/architecture
  - Needs more info - not possible to assing a type label due to missing information
  - Question - we should direct questions to SO
  - upstream - an issue used to track an issue in an upstream component
  - **Note**: All type labels are grey (Bugs grey with a touch of red).
- assign the `important` label to issues that
  -  result in data loss
  - a breakage of extension
  - critical security, performance issues
  - UI issue that makes a feature unusable
- each issue needs to be assigned to a [feature area](https://github.com/Microsoft/vscode/wiki/Feature-Areas)
- assign bugs that you plan to fix during November to the November milestone
- issues that the community can take up should be labeled as `help-wanted`
- feature requests that should be implemented as extensions should be labeled `extensions-candidate` and be closed

## Tracking:
Please make sure that you also do this grooming in our satellite repositories:
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [ ] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [ ] @rebornix
  - [x] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @mjbvz
  - [x] @octref

**Comment by bpasero** [comment]
Here is my template for closing issues that are out of scope:

> This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by alexandrudima** [comment]
November is done.
