### ISSUE TITLE
Gulp tslint !== gulp hygiene

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38207]
It seems that `gulp tslint` runs in a much stricter mode than `gulp hygiene` does, in terms of TSLinting.

`gulp tslint` seems to use `gulp-tslint` and reports many warnings... while `gulp hygiene` uses `tslint` directly and reports no warnings at all. Are the versions mismatching?

**Comment by joaomoreno** [comment]
Found the issue.

https://github.com/Microsoft/vscode/blob/322bd6136acb0423d345ea7bab9f091c5dd2abbe/build/gulpfile.hygiene.js#L232

TSLint doesn't use `failureCount` any more, but `errorCount` and `warningCount`.

**Comment by egamma** [comment]
Thanks and  I missed this API change...

**Comment by egamma** [comment]
@joaomoreno In the vscode-tslint extension I use result.failures.length > 0 to make it independent of errors/warnings (which are configurable).
