### ISSUE TITLE
SCSS: Broken syntax highlighting for nested selectors

### ISSUE THREAD

**Issue by spncrmoo** [Microsoft/vscode#38208]
- VSCode Version: 1.18.0
- OS Version: macOS High Sierra (10.13.1) and Windows 7

Steps to Reproduce:
All SCSS files now have broken syntax highlighting for nested elements since the latest update. It's the same for everyone on my team, which are split between OSX and Windows. I've done a lot of searching but somehow can't find any mention of this elsewhere, which is odd since we're all on different setups here.

![screen shot 2017-11-13 at 09 59 06](https://user-images.githubusercontent.com/13147147/32720250-d9b17df4-c85a-11e7-8005-8f4ded6734ab.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
That's what I see in 1.18 with the Dark+ theme and no extensions installed.
![image](https://user-images.githubusercontent.com/6461412/32783888-8a7d68da-c94d-11e7-91d5-0ad027ab2203.png)

Maybe there was a change in the theme that you use?

**Comment by spncrmoo** [comment]
Am I missing something? It also seems to be broken in your screenshot. I'm assuming that P tag is a different colour if you take it out of that nest?

Also from my original post - "Reproduces without extensions: Yes"

I've tried without any extensions whatsoever, and like I said it's on multiple machines.

**Comment by aeschli** [comment]
Sorry, I didn't realize you only meant the `p`. This one in now fixed in 1.19
![image](https://user-images.githubusercontent.com/6461412/32788069-83dfcc10-c958-11e7-98f2-8ead0f9db5dd.png)

**Comment by spncrmoo** [comment]
Ah great, thanks. It was the P and the H4 in my original screenshot, but it pretty much does it for all element selectors that are nested in any of my scss.

**Comment by bartech101** [comment]
**Same issues**
Not recognizing &-name as parent-selector-suffix
![image](https://user-images.githubusercontent.com/11904934/33991808-72d76e02-e0d0-11e7-9e5a-ed35a8a33b62.png)


looks like parsing problems as in same file later got not recognized closing brackets but selector suffix is recognized properly
![image](https://user-images.githubusercontent.com/11904934/33991830-93b9c5fc-e0d0-11e7-9f05-834b20eeef20.png)

Not recognizing pseudo elements correctly and double semicolon (first one is treated as punctuation separator but second as meta property value) also opening bracket is treated as part of meta property value
![image](https://user-images.githubusercontent.com/11904934/33991883-caefc1c0-e0d0-11e7-8059-d945c8705015.png)

Pseudo elements recognized as support.type.property-name same as all css properties
![image](https://user-images.githubusercontent.com/11904934/33991939-ff7a0414-e0d0-11e7-8efd-8990b2af5615.png)

Treating entity.other.attribute-name.parent-selector-suffix as variable when starts with "--"
![image](https://user-images.githubusercontent.com/11904934/33992012-40afefe8-e0d1-11e7-9860-e8e1dcb9ee62.png)

Treating "label" tag as support.type.property-name
![image](https://user-images.githubusercontent.com/11904934/33992039-5d79f0a6-e0d1-11e7-9a0c-6b63701988bf.png)

Treating nested tags as meta.property-name and not as entity.name.tag
![image](https://user-images.githubusercontent.com/11904934/33992063-74724f4c-e0d1-11e7-8b03-f37b126497e1.png)

Problem with recognizing ending brackets
![image](https://user-images.githubusercontent.com/11904934/33992096-95c594ba-e0d1-11e7-9447-4b15be556010.png)

All looks like parsing problems switching to SASS syntax for same file and everything is ok
![image](https://user-images.githubusercontent.com/11904934/33992262-346750cc-e0d2-11e7-8a96-f03ef52bedd0.png)

**Comment by aeschli** [comment]
@bartech101 There was a grammar update for 1.19 that fixed most of the issues. 1.19 will be out in the coming days.

**Comment by bartech101** [comment]
- VSCode Version: 1.19.0
- OS Version: Windows 10

Most of the issues are fixed in 1.19.0 but some still exists

'cursor' property is treated as entity.name.tag
![image](https://user-images.githubusercontent.com/11904934/33998289-643aca62-e0e7-11e7-8242-cc8a5e77bdd2.png)

BEM "&--modifier" recognized as variable
![image](https://user-images.githubusercontent.com/11904934/33998455-cf4a51f6-e0e7-11e7-891e-20a7363f0f76.png)

animation name with "-" not recognized properly
![image](https://user-images.githubusercontent.com/11904934/33998649-77c5cc20-e0e8-11e7-8ab4-766ce1b464d0.png)
