### ISSUE TITLE
">" character triggers intellisense

### ISSUE THREAD

**Issue by 207713** [Microsoft/vscode#38202]
Typing ">" character always triggers intellisense function, thus i can not close a HTML tag and hitting ENTER for a new line without inserting the first suggestion!

[https://imgur.com/hSOg5uq](https://imgur.com/hSOg5uq)

So when i type "<div>" for example and hitting ENTER i get: <div>$_COOKIE

**Comment by bmewburn** [comment]
You can set `"php.suggest.basic": false` to prevent this from happening.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/37919
