### ISSUE TITLE
Regions in Typescript has stopped working

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#38216]
- VSCode Version: 1.18.0
- OS Version: Windows 7 64bit professional

Steps to Reproduce:

1. Make some awesome Typescript code
2. Add regions some places in the code
3. Use shortcut to fold to level 2
4. notice that not ALL regions fold

PS: I've noticed that multiline comments seem to break the region functionality .. maybe...

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Sorry, I'm not able to reproduce. Can you paste a code sample that show the problem.

Note that 'fold level 2' will only fold regions that are inside a top level region. It also does not fold the region the cursor is in.
