### ISSUE TITLE
Suggestion:  Add native integrated database administration tool

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#38211]
- VSCode Version:

```
Versão 1.19.0-insider
Confirmação 0fbdfff167653b233231259ceb3109f0931887ef
Data 2017-11-09T06:19:28.857Z
Shell 1.7.9
Renderizador 58.0.3029.110
Nó 7.9.0
Arquitetura x64
```

- OS Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
```

Steps to Reproduce:

1.  Add panel to manage and administrate MySQL
2.  Like https://netbeans.org/features/ide/database.html
3. Like https://www.jetbrains.com/help/ruby/database-tool-window.html

Reproduces without extensions: Yes/No

**Comment by chrisdias** [comment]
hi - thanks for the suggestion.  this functionality can be contributed through an extension, so this is a good community project.  closing.
