### ISSUE TITLE
Trying to bind key shows "unknown"

### ISSUE THREAD

**Issue by tger** [Microsoft/vscode#38212]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open keybindings.json.
2. Press "Ctrl-X Ctrl-X" to add a keybinding
3. Press "Ctrl-X b"

Dialog says "unknown", and I cannot bind the key.

Reproduces without extensions: Yes

**Comment by tger** [comment]
This does not reproduce for me on macOS.

**Comment by roblourens** [comment]
Are you using a non-english keyboard layout?

**Comment by roblourens** [comment]
These troubleshooting tips may be helpful: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-windows-keybindings

**Comment by tger** [comment]
As a matter a fact I am using a non-english layout in that I make use of [Keyman Desktop](https://keyman.com/desktop/). It this could be made to work it would be nice (and in can be made to work because regular Emacs does get it right) but I understand that it may be more difficult in Electron.

**Comment by alexandrudima** [comment]
@tger On our side, on Windows, we are using the `keyCode` property of the `keydown` event to do keybinding dispatching.

You can see the value we receive for this `keyCode` property when pressing the key and hovering over the input box.

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by tger** [comment]
It just says "unknown":
![skarmklipp](https://user-images.githubusercontent.com/14966/32790272-483d2b16-c95e-11e7-842c-70ef41040151.PNG)

**Comment by alexandrudima** [comment]
It is possible to hover over the input box and see the `keyCode` number even for unknown.
