### ISSUE TITLE
File Changed indicator, but undo not available

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#38219]
VSCode Version: 1.18.0
OS Version: Windows 7 64bit professional

Not sure if this is a UX issue or really a bug... 

but i would think that when a file shows "modified" circle / indicator, that CTRL+Z (Undo) would be available or working. 

I can't or couldn't see what line had changed, so i had to save and then do a diff..

**Comment by bpasero** [comment]
@Montago can you provide any reproducible steps? Could it be that an extension is participating in the editing and did a change automatically without you typing?
