### ISSUE TITLE
OSX: "Save as" with "Hide extension" checked creates a new file without an extension

### ISSUE THREAD

**Issue by danielsamuels** [microsoft/vscode#38217]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
GitHubIssues|Hoo|0.1.2
Handlebars|and|0.2.0
django-snippets|bib|1.1.0
stylelint|shi|0.30.0
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
auto-close-tag|for|0.5.3
vscode-nginx-conf-hint|han|0.0.4
vue-snippets|hol|0.1.5
vue|jcb|0.1.5
vue|liu|0.1.5
MagicPython|mag|1.0.12
github-issues-prs|ms-|0.8.0
sublime-keybindings|ms-|3.0.2
PostCSS|ric|1.0.1
nunjucks|ron|0.2.3
vscode-nginx|sha|0.4.1
shellcheck|tim|0.2.1
expand-selection-to-scope|vit|0.2.0
twig|wha|1.0.2
jinja|who|0.0.8

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a file.
2. Press "Save as"
3. Ensure "Hide extension" is enabled
4. Give the file a new name and hit "Save"
5. The new file is created without a file extension

I've made a [short video](https://www.youtube.com/watch?v=BGsaczT7yxw) which demonstrates the issue.

**Comment by bpasero** [comment]
please report against electron
