### ISSUE TITLE
razor give a wrong hint [asp-anti-forgery]

### ISSUE THREAD

**Issue by xin-young** [Microsoft/vscode#38210]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
mssql|ms-|1.2.1
csharp|ms-|1.13.0
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.1
vscode-docker|Pet|0.0.21
vscode-typings|typ|0.0.5
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

---
asp-anti-forgery->asp-antiforgery
![default](https://user-images.githubusercontent.com/8943317/32721769-98a7d842-c8a2-11e7-8800-2d429e2575d0.png)
![default](https://user-images.githubusercontent.com/8943317/32721788-aa553ff8-c8a2-11e7-8ea4-d6f68555ce11.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This appears to be coming from an extension. If you know which one, please file an issue on them.
