### ISSUE TITLE
endless restart loop

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#38215]
- VSCode Version: Insiders d6fbdcf19716910b26ea81efc95724f2fabe5aa6
- OS Version: macOS

Steps to Reproduce:

1. Opened VS Code on old Workspace
2. Got this:

![2017-11-13_12-14-35](https://user-images.githubusercontent.com/1898161/32723102-81971c98-c86c-11e7-9d3e-b37ab69578b2.png)

Pressing "Restart" restarts VS Code but I end up in the same situation.

**Comment by sandy081** [comment]
@weinand Any errors in the console?

**Comment by weinand** [comment]
![2017-11-13_12-30-42](https://user-images.githubusercontent.com/1898161/32723636-83614b8c-c86e-11e7-8c23-bd7c7f476ddb.png)

**Comment by weinand** [comment]
BTW, I can reproduce this.

**Comment by sandy081** [comment]
Ok, Will come to you to check it out. Thanks.

**Comment by sandy081** [comment]
This was happening because workspace settings are being nullified when configurations from extensions are being registered in a single folder workspace. 

Marked it as important as workspace settings are not read in single folder workspace.
