### ISSUE TITLE
Workspace and .gitignore

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#38220]
- VSCode Version: 1.18
- OS Version: Win 8

Steps to Reproduce:

1. Create a multifolder workspace project
2. Set gitignore for .vscode/settings.json
3. check your git side panel and you will see it does not ignore .vscode folder content

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore
