### ISSUE TITLE
Integrated Terminal freezes vscode on `dotnet run`

### ISSUE THREAD

**Issue by Kizmar** [Microsoft/vscode#38222]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 
Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
xml|Dot|1.9.2
tslint|eg2|1.0.21
json-tools|eri|1.0.2
csharpextensions|jch|1.3.0
mssql|ms-|1.2.1
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
csharp2ts|raf|0.0.19

---

Steps to Reproduce:

1. Run `dotnet run` from a Bash integrated terminal
2. Click on "Maximize Panel Size"

It will almost always lock up vscode long enough for windows to ask me if I want to kill the process. It doesn't seem to do this if I leave the window in the minimized state - though I can't say it never happens then too. This app was scaffolded using `dotnet new aurelia` (if that helps at all).

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@Kizmar can you try do a performance profile in devtools so we can see what's taking all the time? 

How to do the profile:

1. Help > Toggle Developer Tools
2. Performance tab
3. Press record button
4. Do the issue repro
5. Press record button to stop
