### ISSUE TITLE
Workspace setting: elevated privileges

### ISSUE THREAD

**Issue by nalroff** [Microsoft/vscode#38228]
## Feature request

I would like the ability to configure a workspace (multi-root) to, upon opening the workspace, prompt for privilege elevation (UAC, sudo, etc.).

The exact purpose of this need is to keep a workspace around to edit my Gnome 3 `.desktop` files in Ubuntu--some of which reside in `/usr/share/applications`, which is owned by `root`.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
