### ISSUE TITLE
Regression (insiders build): Can't get configuration of a folder being added within the onDidChangeWorkspaceFolders event

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#38229]
- VSCode Version: Code - Insiders 1.19.0-insider (3ac890f6ed9b5a7ff9bfd222fe59d1bec9d3ddf7, 2017-11-13T13:16:25.932Z)
- OS Version: Windows_NT x64 10.0.17035
---

I'm seeing the following exception when trying to read a configuration setting based on the uri of a workspace folder being added within the `onDidChangeWorkspaceFolders` event. From looking at the code, it seems that the new folder hasn't yet been added to the internal map of folder configurations.

![exception](https://user-images.githubusercontent.com/641685/32736155-c05e97ec-c864-11e7-86fd-3a5c0b344f29.png)

Steps to Reproduce:

1. Create an extension that listens for the `onDidChangeWorkspaceFolders` event:
```ts
    workspace.onDidChangeWorkspaceFolders((e: WorkspaceFoldersChangeEvent) => {
            const excludes = workspace.getConfiguration('files', e.added[0].uri).get('exclude');
    });
```
2. Start debugging and open a workspace
3. Add a new folder into the workspace (make sure NOT to remove a folder and re-add it, it seems like the configuration is still left behind and the exception won't happen)
4. 🐛 observe the exception when the configuration is requested

Reproduces without extensions: No

**Comment by sandy081** [comment]
@eamodio I see this error but only when removing the folder from the workspace not while adding the folder. It is also true from the current code. 

Can you please check and confirm. Thanks.

**Comment by eamodio** [comment]
I'm definitely not seeing the exception in the stable release, and it is 100% reproducible for me with insiders, when adding a new folder to a workspace, with the code above

**Comment by eamodio** [comment]
I just pushed this simple repo - https://github.com/eamodio/vscode-simple and I see the exception happen  with it.

**Comment by eamodio** [comment]
After trying to add a lot more folder (rather than just the 1 or 2 I was testing with) -- it looks like for some reason, folders that are git repos don't error (or at least not consistently), but if you open a random folder that isn't a git repo it seems to always error.

**Comment by sandy081** [comment]
Finally I can reproduce it. It's all about adding folders those does not have settings. This will not trigger the configuration change event. Hence the new folder was not added to the map. It was the same in stable except that I was checking for the existence and not now. 

Above fix takes care of it. 

There is a known fundamental issue to have configuration synced along with workspace changes which will be taken care here #38315.

Closing this.
