### ISSUE TITLE
[Feature] Collaps js/map/css files in ts/scss files

### ISSUE THREAD

**Issue by danielehrhardt** [Microsoft/vscode#38223]
Hi guys,

it would be awesome if we can get a Feature like Visual Studio/Webstorm has. 
js/map and css Files should be inside the ts and scss files. 

Is there something planned or a plugin for that?

![image](https://user-images.githubusercontent.com/19570043/32727102-946adf30-c87b-11e7-943d-a864d457f5b8.png)

should become this:
![image](https://user-images.githubusercontent.com/19570043/32727232-1e04116c-c87c-11e7-8b94-17c2a3a6f239.png)

Thank you,
Daniel

**Comment by roblourens** [comment]
I think this is https://github.com/Microsoft/vscode/issues/6328
