### ISSUE TITLE
Allow to change the width of quick open

### ISSUE THREAD

**Issue by dirkseidel** [microsoft/vscode#38225]
The width of the drop down menu appearing when hitting e.g. "shift ctrl/cmd p" seems to be fixed in size.  This size also seems to be used for displaying potential results of a command. This is quite annoying, as for every single item in a list which is too large to be displayed within the given width, one has to hover over and wait for the full item to be displayed in a pop up window. 
It would be very helpful to be able to adjust/maximise the width.

**Comment by phifa** [comment]
How are we doing on this? I regularly face the issue, that I have to guess when opening files, since they are abbreviated with `...`.

**Comment by phifa** [comment]
@dirkseidel  @bpasero  just trying to figure out if there are some workarounds, hacks? for me it is `ctrl+p` which is problematic.
