### ISSUE TITLE
git-hook error messages in "Problems" tab

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#38226]
- VSCode Version: 1.18.0
- OS Version: Windows 10 1709 b16299.19

Steps to Reproduce:

1. add to git "git-hook/pre-commit" file with content:
``` bash
#!/bin/sh

echo "error line 1"
echo "error line 2"
exit 1
```
2. try to commit some changes in repository

Expected: both error lines in "Problems" tab

Actual: only first error line in popup message about commit error. Use have to search error lines in dynamic long list of "Git output".

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Unfortunately this isn't going to happen as this is not a permanent error, but an instantaneous one.
