### ISSUE TITLE
Choose integrated terminal when launching new instance

### ISSUE THREAD

**Issue by radu-matei** [Microsoft/vscode#38231]
In Windows I very regularly use both WSL and PowerShell - it would be great to have the ability to choose when creating a new terminal what shell to use. 

I know I can set in the config a default one, but would very much want to be able to choose at any point without changing my settings everytime.

Thanks!

**Comment by Tyriar** [comment]
Try https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

You can also enter a different shell from within another shell (launch powershell.exe and type bash.exe).

**Comment by radu-matei** [comment]
@Tyriar - yes, you can enter PowerShell from Bash, but formatting stops working, you cannot view command history... unusable.
Will check out the extension, thanks!
