### ISSUE TITLE
Settings option to disable text animation in "Run Selected Text in Active Terminal"

### ISSUE THREAD

**Issue by mcrumiller** [Microsoft/vscode#38238]
Running selected text in integrated active terminal now copies the text via a slow animation that mimics real typing--characters are sent one by one to the active terminal. The result is that executing large blocks of text in the terminal take a really long time, as you have to first wait for the characters to render in the terminal.

This is especially problematic when you comment out a section of code, as you have to sit there waiting for the comments to slowly render in the terminal.

There should be a setting to disable the animation.

**Comment by Tyriar** [comment]
Are you on Windows? I think this is actually the terminal being slow due to an issue in https://github.com/rprichard/winpty
