### ISSUE TITLE
No API for closing inactive TextEditors

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#38239]
Looking at the docs for TextEditor (https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor) the Hide method has been deprecated. Per the documentation, its replacement is `workbench.action.closeActiveEditor`, which only closes the currently visible TextEditor tab.

There is (apparently) no supported way to close inactive TextEditors. Would it be possible to add such an API back?

(User scenario:
Omnisharp-Roslyn is adding support for CodeActions that rename files. When a file is renamed on disk, that's open in VS Code, Code keeps open the tab for the old file name but adds "Deleted" to the tab title. Omnisharp-Roslyn would like to close editor for renamed files. With the current APIs, there's no good way for us to close files that get renamed unless they are the active editor)

**Comment by jrieken** [comment]
> There is (apparently) no supported way to close inactive TextEditors. Would it be possible to add such an API back?

For the API an inactive editor doesn't exist, only the combination of a document and editor widget is an API-editor. That's also why the `hide` method is deprecated. It will kill the editor-instance you are using it with.

Your use-case sounds similar to #10659 which is about adding a *rename file* to the `WorkspaceEdit`. 

> When a file is renamed on disk, that's open in VS Code, Code keeps open the tab for the old file name but adds "Deleted" to the tab title.

Yeah, that's not very nice... We should really offer a rename for this. @bpasero Is there anything today extensions can do to prevent this?

**Comment by bpasero** [comment]
@rchande @jrieken that is only true when `"workbench.editor.closeOnFileDelete": false` is configured, which is not the default. A rename on disk is a delete of the old file and add of the new file. There is no watcher I know of that can reliably report a rename event with old and new path...

**Comment by rchande** [comment]
@bpasero I noticed the "deleted" text behavior when implementing https://github.com/OmniSharp/omnisharp-roslyn/pull/1023. In that PR, Omnisharp will delete files on disk if Roslyn CodeActions rename them. I had the default value for that option and still saw the text show up. Do you know if any bugs were fixed in this area lately?

**Comment by rchande** [comment]
@jrieken Put differently: what API can I call to close a tab that is not the currently open tab. If there's no such API, consider this a request for it 😄 .

**Comment by jrieken** [comment]
> consider this a request for it 

It's this #15178. But what you want is #10659 which is about the data model. A rename code action shouldn't care about UI state. Closing this as a dupe.
