### ISSUE TITLE
PATH not used

### ISSUE THREAD

**Issue by muppetjones** [Microsoft/vscode#38237]
When I don't open VSCode from the command line, it cannot find `rustc`. I moved the PATH export to my `~/.bashrc`, as suggested in #22831, which does update PATH as expected.
```
$ which rustc
rustc is /Users/stephen.bush/.cargo/bin/rustc
```
```
> process.env.PATH
"<home>/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin"
```

__Edit__: The environment does not persist if you open a new workspace once VSCode is open, i.e.,
1. Launch from the command line (linter works fine).
2. Open an existing workspace (linter fails).

I think this is probably related to a similar issue I'm having with python: https://stackoverflow.com/questions/47268960/python-environment-and-vscode

- VSCode Version: 1.18.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Add `rustc` to your path in `~/.bashrc`, e.g.,
```
export PATH="${HOME}/.cargo/bin:${PATH}"
```
and source it.
2. Launch VSCode via Spotlight and trigger the `rust` linter.

Reproduces without extensions: No. But this is expected--it works fine from the command line.

**Comment by joaomoreno** [comment]
If you open the Developer Tools in a session in which `rust` can't be found, is there are error/warning in the Console? What does `process.env.PATH` contain? What about `process.env.SHELL`?
