### ISSUE TITLE
Support for locally installed npm tools

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#3823]
This is just an observation based on the Feb release notes. I just thought I'd mention it in case is a general assumption rather than just for ESLint plugin

In a coupe of places the release notes for Eslint make the assumption that it will be globally installed. I have found global installation to be an anti-pattern and now install all dev deps locally for each project. The reason is version clashes. It is possible to be working on a project that requires specific version of such tools. This is likely of you switch often. Also I use nvm-winodws for different version of node which doesn't share global installations. Also local installation means package.json much better describes the dependencies.

It's easy to run any local tool by prefixing it with ./node_modules./bin/ or better, add a npm script which add that to the path when run.

In general code and plugins should support everything installed locally.

I've not yet hopped on my dev pc to see if the new release works with my local ESLint installation and config.

thanks for listening

**Comment by egamma** [comment]
>In general code and plugins should support everything installed locally.

@SteveALee I fully agree on globally installed modules. Actually, all the linter extensions (vscode-eslint, vscode-jshint, vscode-tslint, vscode-jscs) are written so that they work with locally installed linter module. 

I'll update the release notes. 

Have you tried a local install of eslint and it didn't work?

**Comment by SteveALee** [comment]
@egamma 

> Have you tried a local install of eslint and it didn't work?

I'm not sure

When I installed the extension I had a project open with no local eslint and I got this
`Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then press Retry.`

Good.

However, neither neither the release notes or the ESLint extensions instructions actually tell me how to use it :(

In another project with eslint locally installed ido not see that warning. however I'm not sure if it is only installed on extension load or on project load. From the command line I get this

<pre>
. brian@0.1.0 lint C:\projects\brian
. eslint --env node src/server/**/*.js && eslint --env browser src/client/**/*.jsx

C:\projects\brian\src\client\index.jsx
  28:49  error  'appState' is missing in props validation             react/prop-types
  28:58  error  'appState.timer' is missing in props validation       react/prop-types
  36:18  error  'appState' is missing in props validation             react/prop-types
  36:27  error  'appState.resetTimer' is missing in props validation  react/prop-types

✖ 4 problems (4 errors, 0 warnings)
</pre>

But see nothing when I open the file in VS studio

Here is my eslint config

<pre>
{
	"ecmaFeatures": {
		"ecmaVersion": 6,
		"jsx": true,
		"modules": true
	},
	"env": {
		"es6": true,
		"browser": true,
		"node": true
	},
	"parser": "babel-eslint",
	"plugins": [
		"react"
	],
	"extends": ["plugin:react/recommended"]
}
</pre>

**Comment by SteveALee** [comment]
correct - I get red squiggles for the errors in questions. So it works just fine.

However I get another error - probably not ESLint but I can tell the source.
I'm using decorators and get this

<pre>
const appState =  new class AppState {
    @observable timer = 0;
</pre>

`'property declarations' can only be used in a .ts file.
(property) AppState.timer: number`

Is this a syntax problem with TS and decorators? I can raise another bug if useful

**Comment by SteveALee** [comment]
@egamma

>    Have you tried a local install of eslint and it didn't work?

FYI In fact it even correctly handled multiple .eslintrc files - eg server and client

**Comment by egamma** [comment]
@SteveALee 

> 'property declarations' can only be used in a .ts file.
 (property) AppState.timer: number 
Is this a syntax problem with TS and decorators? I can raise another bug if useful

pls see this comment: https://github.com/Microsoft/TypeScript/issues/6872#issuecomment-190288631 for how to enable decorators.

>However I get another error - probably not ESLint but I can't tell the source.

If you are on the latest vscode-eslint extension then errors from ESLint are prefixed with `[ESLint]`.

**Comment by egamma** [comment]
Closing - the disucssion has answered the questions.
