### ISSUE TITLE
Git: Support foreground git decorations

### ISSUE THREAD

**Issue by MrCroft** [microsoft/vscode#38242]
Would be nice to also have a color setting for newly added files (first time staged, before first commit).

Something like `"gitDecoration.newResourceForeground": "#549651"`
It does present the "A" badge in the explorer and open-editors trees, just not having the possibility to assign a color to it yet.

![image](https://user-images.githubusercontent.com/2809154/32740371-6bdd1620-c8ab-11e7-9167-2db4c129edb7.png)

**Comment by jrieken** [comment]
Actually not out-of-scope but implemented as `gitDecoration.untrackedResourceForeground` theme color
