### ISSUE TITLE
<<< in bash messes with syntax coloring.

### ISSUE THREAD

**Issue by berithpy** [Microsoft/vscode#38240]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.21
jslint|ajh|1.2.1
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
python|don|0.7.0
gitlens|eam|5.7.1
vscode-npm-script|eg2|0.3.3
hg|mrc|1.2.3
vscode-icons|rob|7.17.0
html-preview-vscode|tht|0.1.1
python|tht|0.2.3
highlight-matching-tag|vin|0.4.4
markdown-all-in-one|yzh|0.11.1

(5 theme extensions excluded)

---
Bash syntax coloring isn't working properly
Steps to Reproduce:

1.Create a bash file with `A="$(tr / _ <<<$B)"`
2.Every line below it will be wrongly colored.
![image](https://user-images.githubusercontent.com/8316977/32740393-952cad4e-c881-11e7-963c-fb0be84e86ed.png)

Reproduces without extensions: Yes

**Comment by berithpy** [comment]
![image](https://user-images.githubusercontent.com/8316977/32740495-e7b4f3f0-c881-11e7-82ba-292b7d7f4ab6.png)
I forgot to add what happens when you remove the <<<

**Comment by aeschli** [comment]
Reproduced with
```sh
X="ABC"
B="$(tr / _ <<<$B)"
X="ABC"
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#90
