### ISSUE TITLE
Cmd+P search file no longer searches file under symlinked directory

### ISSUE THREAD

**Issue by iamchucky** [Microsoft/vscode#38241]
- VSCode Version: Code - Insiders 1.19.0-insider (3ac890f6ed9b5a7ff9bfd222fe59d1bec9d3ddf7, 2017-11-13T12:40:01.309Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.0.0
quokka-vscode|Wal|1.0.79
wallaby-vscode|Wal|1.0.65
tslint|eg2|1.0.21
debugger-for-chrome|msj|3.5.0
stylelint|shi|0.30.0

(6 theme extensions excluded)

---

Steps to Reproduce:

1. cmd+p to search for a file under symlinked directory
2. file not found

Reproduces without extensions: Yes

Please note that this was not an issue with insiders 1.18 build or even the first update patch of 1.19.

I switched to stable version of vscode and I am able to cmd+p to search file under symlink directory just fine.

**Comment by roblourens** [comment]
Do you have the `"search.followSymlinks"` setting?

**Comment by iamchucky** [comment]
here is my user settings:
```
{
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "editor.fontSize": 14,
    "editor.rulers": [
        140
    ],
    "editor.tabSize": 4,
    "files.trimTrailingWhitespace": true,
    "workbench.colorTheme": "An Old Hope Classic",
    "workbench.iconTheme": "material-icon-theme"
}
```

**Comment by roblourens** [comment]
Can you do a search (from cmd+shift+f) and check if they show up there?

If not, can you show the output in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by iamchucky** [comment]
I did a search on "dx-radiopharmaceutical-info"  using cmd+shift+f, it doesn't show up for the 1.19.0 but does show up for stable build

1.19.0:
```
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Users/cyang/Development/foo/**/dist' --max-filesize '17179869184' --follow --fixed-strings -- 'dx-radiopharmaceutical-info' '/Users/cyang/Development/foo'
 - cwd: /
 - Sibling clauses: {}
```

stable:
```
rg --hidden --heading --line-number --color 'ansi' --colors 'path:none' --colors 'line:none' --colors 'match:fg:red' --colors 'match:style:nobold' --ignore-case -g '!/Users/cyang/Development/foo/**/dist' --max-filesize '17179869184' --no-ignore --follow --fixed-strings -- 'dx-radiopharmaceutical-info' '/Users/cyang/Development/foo'
 - cwd: /
 - Sibling clauses: {}
```

looks like stable version has this `--no-ignore` flag, is that needed for this to work?

**Comment by roblourens** [comment]
No, that's just because gitignore support is now enabled by default. The important flag is `--follow`.

So you're saying

- stable 1.18.0
  - cmd+p doesn't show symlinked files
  - search **does** show symlinked files
- insiders 1.19.0
  - search does not show symlinked files

Correct? Could the file be excluded by your gitignore file? That would explain this because it was enabled by default in 1.18.0 but not search until 1.19.0.

You can set `"search.useIgnoreFiles": false` to test.

**Comment by iamchucky** [comment]
more like:

stable 1.18.0
- cmd+p **does** show symlinked files
- search does show symlinked files

insiders 1.19.0
- cmd+p doesn't show symlinked files
- search does not show symlinked files

your `"search.useIgnoreFiles": false` suggestion worked, and yes our symlink dir is excluded by my gitignore 👍

**Comment by roblourens** [comment]
Ok, glad that works!

**Comment by iamchucky** [comment]
https://github.com/Microsoft/vscode/issues/37211

Might be helpful to put this change in the release notes though so that user is not surprise about this change

**Comment by kbaird5** [comment]
'"search.useIgnoreFiles": false' is not a great solution. Previous versions you could easily toggle on/off .gitignore and .exclude files from the extended search options. Now they are tied together to a single toggle. It was great to be able to "exclude: 'node-modules'", but quickly toggle to use .gitignore or not (for other uncommon files). Please restore the dual toggle?

**Comment by roblourens** [comment]
>  It was great to be able to "exclude: 'node-modules'", but quickly toggle to use .gitignore or not (for other uncommon files).

We thought quite a lot about this, but decided in the end that simplicity wins out over supporting this niche case. Two buttons confused some people, and I think that `search.exclude` is now not generally necessary in a project with a .gitignore anyway.

**Comment by kbaird5** [comment]
Here is our use case: we use .gitignore to make sure unwanted/duplicate files are not checked in. However, there are some files that we do want to search (but not check in).

To satisfy our use case, I set `"search.useIgnoreFiles": false`,  updated `"search.exclude"` to omit the most obvious files from .gitignore, but left out the ones I want to search. This works because most of our .gitignore file are similar. I guess I could update that for each workspace if they were different.
