### ISSUE TITLE
[Git - file-decorations] Untracked file shows the "Added" (A) badge

### ISSUE THREAD

**Issue by MrCroft** [Microsoft/vscode#38243]
- VSCode Version: Code - Insiders 1.19.0-insider (73830a36872aa1c168c085dad8cc6e2e1a05ff45, 2017-11-13T15:41:17.934Z)
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. In a folder that's versioned under Git, create a new file. It will show the "A" badge.
2. Stage that file.
3. Unstage that file.
Notice that after being unstaged, the file continues to present the "A" badge instead of "U" (Untracked) in the Explorer and Open Editors trees. (`a.txt` file in the attached screen capture).

The badge is updated properly under the source control tree.
**Edit:**  Also, closing and restarting VSCode shows the appropriate badges, of course.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/2809154/32740989-6838f41a-c8ad-11e7-926b-c28e0b679d98.png)

**Comment by vvs** [comment]
Weird indeed. Something is broken for sure. For me, I see different letters for the same file, depending on where I look at it. I the git tab the file I've added and staged is shown as 'A'. In the explorer tab it is shown with 'U' (untracked!).

**Comment by jrieken** [comment]
Yeah, it misses an event on the git side and it will stick with whatever it go the first time. The SCM viewlet tho will receive some kind of update

**Comment by jrieken** [comment]
fixed via https://github.com/Microsoft/vscode/commit/dbb05870323eef793a31d03ae95e18b7cd22bc76 which was about missing events
