### ISSUE TITLE
Multi-root workspace - no multiple source control providers from different drives

### ISSUE THREAD

**Issue by richrout** [Microsoft/vscode#38245]
- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new VS Code workspace
2. Add 2 git projects from 2 different drives
3. Go to Source Control tab - there will be no "Source Control Providers" list. Only first added repo will be accessible (or if multiple added from same drive, only those from same drive. other drive will be excluded)

Reproduces without extensions: Yes

**Comment by sethstha** [comment]
Exactly what I am facing right now. Confirmed the issue.

**Comment by Globegitter** [comment]
Have a similar issue, just that I see "There are no active source control providers". I added 3 folders all git projects, that is on elemantry OS 0.4.1 (based on Ubuntu 16.04) with vs code 1.18.1

**Comment by joaomoreno** [comment]
@Globegitter You obviously don't have the same issue. This is about different drive letters. It's a Windows issue. Please file another issue or simply search for that message... you'll quickly find that many other people filed that issue.
