### ISSUE TITLE
Running Code is not recognized by the OS?

### ISSUE THREAD

**Issue by anguspiv** [Microsoft/vscode#38248]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6 

Steps to Reproduce:

1. Open code either through application, or terminal `code`
2. Code window is open.
3. Application Menu is not present when working inside VSCode
![screenshot 2017-11-13 11 13 25](https://user-images.githubusercontent.com/1724500/32744255-c5db3be0-c863-11e7-9a4c-167619396fa5.png)
4. No VSCode icon in the System Dock
5. When trying to type inside VSCode, I end up typing in the last application I used (like chrome)
6. Trying to quit with `⌘+q` tries to quit previous application

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by anguspiv** [comment]
I downloaded and was able to run the Code-Insiders, without reproducing the issue.

**Comment by bpasero** [comment]
@anguspiv does a uninstall and reinstall of Code help?

**Comment by anguspiv** [comment]
1. Moved VSCode to trash and emptied my trash
2. Downloaded VSCode from the webstie and moved VSCode into my application folder
3. Launched VSCode
4. Still could not type in the window, nor saw the menu bar show for Code

I was able to close VSCode by the red window close button.
I relaunched code via `code --terminal` and got the following output
```
$ code --verbose
2017-11-15 10:52:20.363 Electron[20900:12175187] _NXSetHidesOnDeactivate: error retrieving current process
[main 10:52:20 AM] Sending env to running instance...
[main 10:52:20 AM] Sent env to running instance. Terminating...
```

**Comment by bpasero** [comment]
@anguspiv almost looks like another instance is running already, when you restart the OS does it change anything?

**Comment by anguspiv** [comment]
Yes, when I restarted the OS. Code is now working correctly, thank you for your help
