### ISSUE TITLE
Some keybidings doesn't work

### ISSUE THREAD

**Issue by MAC293** [Microsoft/vscode#38253]
When I press the format keys it says: "There is no formatter for a C# files..." or sometimes "The combination Ctrl + K, Ctrl + F is not a command". As I know is setted like this in keymap. I reinstalled and reset the keymap, but, it didn't work. 

Regards

**Comment by roblourens** [comment]
The keybinding troubleshooting guide may be helpful: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by MAC293** [comment]
Thank You. I will give it a try.

Regards

**Comment by alexandrudima** [comment]
@MAC293 We do not ship out-of-the-box with formatters for all possible programming languages. You need to search for a suitable extension that contributes a formatter for your programming language of choice.

**Comment by MAC293** [comment]
Understood. Thank You for your help!!!

**Comment by MAC293** [comment]
Can you recommend me a properly extension for it please?

Regards
