### ISSUE TITLE
javascript highlight issue

### ISSUE THREAD

**Issue by nicco91** [Microsoft/vscode#3825]
"var" is not more highlighted in blue in javascript file!

**Comment by JohnSpencerTerry** [comment]
I'm also having this issue since the last update. Looks like I'm getting no syntax highlighting whatsoever.

**Comment by nicco91** [comment]
@JohnSpencerTerry this issue seems to affect only Visual Studio light and dark themes. For the moment i'm using Light+ (default light) and it works correctly.

**Comment by sitefinitysteve** [comment]
Makes it pretty unreadable, can we get this patched asap plz?
![image](https://cloud.githubusercontent.com/assets/1542376/13604102/2f70d2c0-e50f-11e5-83d9-5309b2be7947.png)

**Comment by nicco91** [comment]
@sitefinitysteve try Light+ (default light) theme (or Dark+ if you use dark theme)... it's pretty similar to VS default, having some not annoying colors in addition.

**Comment by JohnSpencerTerry** [comment]
@nicco91 thanks for the tip. changing to dark+/light+ solved the issue (temporarily at least).

**Comment by aeschli** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/3903
