### ISSUE TITLE
Terminal doesn't support TAB TAB autocompletion

### ISSUE THREAD

**Issue by secretgspot** [Microsoft/vscode#38256]
- VSCode Version: current
- OS Version: current

Steps to Reproduce:

1.  When in in-app Terminal, tab tab autocompletion for folder navigation doesn't work and makes it hard to use.  Right click -> Open in Terminal is a nice feature to minimize that frustration but TAB TAB would be greatly appreciated. 
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please provide OS type+version, what shell you're using and what you expect to happen when you hit tab tab.

**Comment by secretgspot** [comment]
Windows 10+latest, vscode powershell terminal

**Comment by Tyriar** [comment]
I assume you're talking about the dropdown feature that shows up in Powershell/ISE (I think)? If so that's unfortunately as designed currently due to the way the VS Code terminal backend works.
