### ISSUE TITLE
Auto closing pairs are not embedded language aware

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38254]
Generalization of #30536

*Steps to Reproduce:**

1. Create a markdown file:

~~~md
```js

```
~~~

2. In the js code block, type `<`

**Bug**
`<>` inserted.

**Root cause**
Markdown defines `<` and `>` as auto closing pairs. Js does not. It appears that we always use the document language's autoclosing pairs instead of the autoclosing pairs of the embedded  language at the current cursor position

**Comment by rebornix** [comment]
Good catch, auto close should check language around cursor instead of model.

**Comment by mjbvz** [comment]
Another case:

~~~md
```js
/**
```
~~~

Based on JS's auto closing rules, we would expect completion to `/** */`
