### ISSUE TITLE
FR: Prevent code lens from shifting cursor position

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#38257]
I think usability wise, the current state of code lens is very disorienting, and I tend to disable them across the extensions I use.

The main reason I do so is that they're constantly messing with my "visual" cursor position. Every time I switch to a new file that has code lens, or the code lens appear, it's very disorienting for my cursor to suddenly jump down 2-3 lines.

I think that I'd prefer if the codelens instead were displayed in a manner that prevented the cursor position from shifting. So, for example, instead of 
```
------------------
foo
|bar
fun
------------------
```
turning into 
```
------------------
foo
CODELENS
|bar
------------------
```
it would turn into
```
------------------
CODELENS
|bar
fun
------------------
```

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/33952 and also https://github.com/Microsoft/vscode/issues/19917
