### ISSUE TITLE
Accessing extensions from tasks

### ISSUE THREAD

**Issue by Rlopez** [Microsoft/vscode#38251]
It seems like there's no mechanism to access extensions from tasks. I have come across the need in this scenario: I may want to have a build task that does something (in my case add revision info to the code) before the extension does its thing (arduino:verify, cordova:build, etc)
Now, in the case of Cordova I can make a task that does get the revision info, and chain to another that calls the command line "by hand", circumventing the extension's API. While that's okay (but confusing) for Cordova, it isn't always trivial (as in the Arduino case).

It feels like it would be a valid use case to be able to call the command palette from the task.

As a secondary wish it would also help be to able to either hide the extension's entry in the command palette OR be able to 'hook' to it in order to avoid ambiguity. It would enable us to setup VSCode for people so they can focus on solving problems and forget about the steps and toolset involved :)

thanks!

- VSCode Version:
1.18.0
- OS Version:
MacOS 10.12.6

Reproduces without extensions: No

**Comment by robcfg** [comment]
I think this would be a useful feature and would avoid having to replicate the extension's functionality through external commands.

For example, in the case of arduino.verify, it already does what is needed but if you want to run the verify command, you'd have to create a bat/bash script that runs the arduino tools from command line. That feels like a waste of time and prone to error when being able to call extension commands from a task would be a better course of action.

**Comment by alexr00** [comment]
I added this last month 😊 Added as part of #4758
