### ISSUE TITLE
Error in color preview for HSL/HSLA

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode#38250]
The little color preview box in front of the color for color systems is buggy for HSL/HSLa. The little preview box is always black, when *saturation* is 0, which is confusing.

![screen shot 2017-11-13 at 15 46 52](https://user-images.githubusercontent.com/43763/32731380-f4236c2c-c889-11e7-895b-c49c2c1f88f9.png)

- VS Code Version: 1.18.0
- OS Version: OS X 10.11.6 

Steps to Reproduce:

1  Open a .css file

2 Write 2 HSLA colors.
```css
  --color-cyan: hsla(178, 92.9%, 38.6%, 1);
  --color-white: hsla(0, 0%, 100%, 1);
```

3 Observe that the small color preview box is black for `--color-white` and cyan for `--color-cyan`.

Reproduces without extensions: **Yes**

*ref: https://github.com/anseki/vscode-color/issues/63*

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/32748726-f33b7bbe-c871-11e7-8230-76d340191200.png)

**Comment by rebornix** [comment]
It's a HSL to RGB conversion bug in CSS language server, fixed via https://github.com/Microsoft/vscode-css-languageservice/pull/53
