### ISSUE TITLE
Breakpoints are not being respected

### ISSUE THREAD

**Issue by jlira2** [Microsoft/vscode#38252]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3

I add a breakpoint on any line and after debugging for a while I can't remove such breakpoints, they are "ghosts" they show up but they are not really there. If I restart VS code the breakpoint goes away, I add it again run without changing any code and sometimes the breakpoint is not hit. one time its hit the next one it is not.

I don't really know how to reproduce but it is happening to me very frequently.
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by jlira2** [comment]
this started happening after last update. It was not happening before.

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.
