### ISSUE TITLE
Integrated terminal not displaying anything

### ISSUE THREAD

**Issue by DaBlackBeerd** [Microsoft/vscode#38262]
VSCode Version: current
OS Version: OS X El Capitan Version 10.11.6

Integrated terminal does not seem to be **displaying** any text/output. I can confirm that there is text within the terminal by: Right click > Select all > Copy, then paste within the editor and the default terminal output is pasted. 

I have disabled all extensions and restarted VS Code with no prevail. 

**This issue happened after updating to Version 1.17.2**

Screenshot below: 
![screen shot 2017-11-13 at 4 47 30 pm](https://user-images.githubusercontent.com/5934150/32753460-876f92dc-c892-11e7-8b41-794b025fd75d.png)

**Comment by Tyriar** [comment]
How did you get into this state? Did you run something in particular?

If you resize the terminal does the text show up?
