### ISSUE TITLE
Each workspace folder should be able to set shell type

### ISSUE THREAD

**Issue by sosensible** [microsoft/vscode#38264]
Steps to Reproduce: (Note this is a copy of 37952... the settings suggested work if you are NOT in workspace mode, but they fail in Workspace mode.)

In terminal you hit plus symbol (in workspace project)
The command palette shows the folders
It only uses a default shell type. Folders should be able to override this in folder settings.
So, if I have a front end in Vue or Angular I should be able to set the shell type for that in the folder settings. But, that setting may or may not be appropriate for a folder where I develop shell scripts for deployment and admin on a windows system. That folder should be able to be set as PowerShell without impacting any of the other folders.

Reproduces without extensions: Yes

**Comment by sosensible** [comment]
I have a folder in a dev directory where the common powershell scripts are stored. It is a folder within my workspace. I see the .vscode folder and it contains a settings.json with the following JSON.

{ "terminal.integrated.shell.windows": "c:\\system32\\WindowsPowerShell\\v1.0\\powershell.exe" }

When I go to the "terminal" and select the (+) it gives me options to select from any of the workspace folders to start a terminal for that folder. It does not open powershell, it opens the default cmd.

**Comment by Tyriar** [comment]
Currently `terminal.integrated.shell.*` are workspace-level settings and cannot be set at the folder level.

**Comment by sosensible** [comment]
@Tyriar , right. That is why I was requesting the feature to be added. :)

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/42165
