### ISSUE TITLE
TAB key results in bizarre indentation in C++ mode

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#38261]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.4.0-97-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
Go|luk|0.6.67
python|ms-|0.8.0
cpptools|ms-|0.14.2
perforce|sle|3.0.0

---

Steps to Reproduce:

1. See the code snippet in the screenshoot
2. Type tab with the cursor at the beginning of line 5
3. TAB mores cursor to column 33?? 

Reproduces without extensions: Yes

**Comment by tlemo** [comment]
![image](https://user-images.githubusercontent.com/13824553/32753277-10ea9852-c881-11e7-91c7-fa2a8ec49788.png)

**Comment by roblourens** [comment]
This is the editor trying to detect the indentation. It will probably be better if you set `"editor.detectIndentation": false`. I don't know whether the bad detection is a bug or not

**Comment by tlemo** [comment]
Thanks @roblourens , additional notes:

1. The described behavior is not affected by editor.detectIndentation (repros with editor.detectIndentation = false)

2. The issue only seem to happen in particular file locations (indentation works as expected around most of the file)

**Comment by alexandrudima** [comment]
This can be turned off via `editor.autoIndent: false`.

**Comment by tlemo** [comment]
Hi @alexandrudima ! Unfortunately autoIndent : false doesn't make a difference either. My settings include:

    "editor.autoIndent": false,
    "editor.wrappingIndent": "none",

**Comment by alexandrudima** [comment]
copy-paste friendly text:

```cpp

int main() {
  return 0;
}

bool Foo::bar(const string &a,
              const string &b) {
  foo();

)
```

**Comment by alexandrudima** [comment]
I have pushed a change that when using `editor.autoIndent: false`, it is respected when pressing `Tab`.

**Comment by tlemo** [comment]
Thanks @alexandrudima !

**Comment by rebornix** [comment]
For C/C++ indentation rules, let's track it in #36148, where we have comments/feedback from ms-cpp tools team. As at this moment, our indentation rules for c/cpp are not covering most user case and blocking ppl from productive c/cpp authoring, we removed indentation rules from internal c/cpp support. Please leave messages  #36148 if you have idea about how to improve it, thanks in advance!
