### ISSUE TITLE
Any way to identify which extension is causing CodeHelper 100% CPU usage?

### ISSUE THREAD

**Issue by adrianocr** [Microsoft/vscode#38260]
- VSCode Version: 1.18.0 (1.18.0)
- OS Version: macOS High Sierra (10.13.1)

Steps to Reproduce:

1. Open code
2. Work for about 15-30 mins
3. See CodeHelper at 100+ percent CPU

I've disabled all extensions and it is one of them but how do I identify which one? Does Code have some kind of task manager like Chrome where you can see which tabs/extensions are taking up memory and CPU? Or any way to profile it? Using Code without extensions basically makes it useless. 

Reproduces without extensions: No

**Comment by roblourens** [comment]
Unfortunately not. You might start by looking at the "heavier" extensions like language support extensions, or trying different types of workspaces, to narrow it down.

You could also follow these steps to profile the extension host process, which should give some clues: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process
