### ISSUE TITLE
VSCode does not find text in files managed by "OneDrive - Microsoft"

### ISSUE THREAD

**Issue by julenka** [Microsoft/vscode#38266]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
gltf-vscode|ces|2.0.9
vscode-insertdatestring|jsy|2.2.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
PowerShell|ms-|1.5.0

---

Steps to Reproduce:

1. Open a onedrive for work folder. In my case I work at Microsoft so my folder was named "OneDrive - Microsoft", ensure that you have a .txt file with the word "Test" under onedrive 
2. Search for "test"

Expected: my test file is found

Actual: The search returns no results

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Reported in https://github.com/Microsoft/vscode/issues/35433, but I have not been able to repro it. In your case, are the files on disk or only in the cloud?

**Comment by julenka** [comment]
Hi thanks for the fast reply. In my case the files are actually on disk.
Like in #35433 <https://github.com/Microsoft/vscode/issues/35433>, I am
able to search these files in other editors, for example Sublime.
