### ISSUE TITLE
After search, paste replaces the search field

### ISSUE THREAD

**Issue by mcdado** [microsoft/vscode#38263]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
format-indent|Kas|1.3.0
markdown-preview-github-styles|bie|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.3
vscode-dash|dee|1.7.1
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
smarty|imp|0.2.0
docthis|joe|0.6.0
code-beautifier|mic|1.7.2
vscode-apache|mrm|1.1.1
mssql|ms-|1.2.1
python|ms-|0.8.0
atom-keybindings|ms-|3.0.2
debugger-for-chrome|msj|3.5.0
html-preview-vscode|tht|0.1.1
vscode-todo-highlight|way|0.5.11
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Copy some text
2. Select some different text that appears more than once in the current file
3. Hit <kbd>cmd</kbd>+<kbd>E</kbd>
4. Hit <kbd>cmd</kbd>+<kbd>G</kbd>
5. Hit <kbd>cmd</kbd>+<kbd>P</kbd> 

Expected result:

The found text in the file is replaced by the clipboard.

Actual result:

The search field contents are replaced by the clipboard.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is by design, after starting a search, the focus remains in the find widget. Here are a couple workarounds:

- `cmd+f3` will select the next instance of the highlighted text, so it would replace cmd+e, cmd+g in your example
- `cmd+1` will focus the first editor group

**Comment by mcdado** [comment]
Thanks for the excellent answer, unfortunately I find the current design frustrating and idiosyncratic.
I'll try to get used to add <kbd>cmd</kbd>+<kbd>1</kbd> in my routine, since <kbd>F3</kbd> requires using the Fn' key.

**Comment by roblourens** [comment]
You can map those keybindings to whatever you want, if you want to avoid fn keys.

Is there another editor that works the way you expect?

**Comment by mcdado** [comment]
In Sublime Text 3 and Atom it depends, they behaves like VS Code only if search widget is already open, but unlike VS Code, cmd + E doesn't open the search widget in them.

So the culprit here would be opening the search interface when pressing cmd + E to use the selection as search term. It basically behaves like cmd + F, with not added value.

**Comment by roblourens** [comment]
Ok, I wasn't actually aware of the other behavior of cmd+e. In Atom, "Use selection as find pattern". I don't know whether we have a feature request for this already.

**Comment by jopotts** [comment]
If `cmd+e` did not focus the search widget and only set the find pattern, then the problem would be solved.

**Comment by rebornix** [comment]
let's track it in https://github.com/microsoft/vscode/issues/44093.
