### ISSUE TITLE
Add command to open raw settings file.

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#38277]
Opening the settings forces VS Code to use that settings editor view, which has the default settings on one side and the user's file on the other. Often i do not need or want that.

If i just want to find anything in my settings file, the results start in the default settings, which i do not care about. Also, the additional split view takes a lot of space. If my panel setup already has some splits there is near to no space left for my settings file and the default settings cannot be hidden completely.

It would be nice to have the alternative open-file-command, similar to the keyboard shortcuts:

![image](https://user-images.githubusercontent.com/834235/32762169-1017c50e-c8f8-11e7-97b7-d555d3f3d215.png)

**Comment by bpasero** [comment]
`"workbench.settings.openDefaultSettings": false`

**Comment by brunnerh** [comment]
@bpasero That is hardly ideal. If set to `false` there is no convenient way of accessing the default settings any more.

**Comment by sandy081** [comment]
Duplicates #17371
