### ISSUE TITLE
Go to definition with multiple definition shows `peek` but doesn't explain why

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3827]
- execute a go to definition where the symbol has multiple definitions
- the peek experience shows up with all the definitions

This is good, but since I wasn't aware that there are multiple definitions it wasn't obvious to me, why peek shows up and why I don't jump immediately to the definition, see below.

The peek zone should provide a hint in the title `Multiple Definitions Found` that explains why peek shows up.

![image](https://cloud.githubusercontent.com/assets/172399/13598499/5b792e4e-e51e-11e5-9201-fd0744a0f2bf.png)

**Comment by jrieken** [comment]
<img width="527" alt="screen shot 2016-03-11 at 17 17 41" src="https://cloud.githubusercontent.com/assets/1794099/13708158/5fa84e28-e7ad-11e5-8338-011a3db7a9d1.png">

will show in the title when `>1`
