### ISSUE TITLE
spawn unknow

### ISSUE THREAD

**Issue by SwiftHuang** [Microsoft/vscode#38278]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-eslint|dba|1.4.3
auto-close-tag|for|0.5.3
beautify|Hoo|1.1.1
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vuehelper|oys|0.1.0
lodash-snippets|tom|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/37863
