### ISSUE TITLE
PHP Syntax broken by PHP->CSS->PHP embedding

### ISSUE THREAD

**Issue by neerolyte** [Microsoft/vscode#38275]
- VSCode Version: 1.18.0
- OS Version: 10.13.1

Steps to Reproduce:

1. Paste code in to editor:

```php
<style type="text/css">
	<?php if ($foo) { ?>
		a {}
	<?php } ?>
</style>
<?php
# this should be a php comment
```

2. Observe odd styling:

![image](https://user-images.githubusercontent.com/1070702/32761388-2ea5f71c-c947-11e7-87b8-1f277e64acb1.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
vscode, not Atom.
