### ISSUE TITLE
Error: non-A-Z keyboard shortcuts lowercased

### ISSUE THREAD

**Issue by Liggliluff** [Microsoft/vscode#38288]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

When using a non-US keyboard, certain keyboard shortcust might use letters outside of A-Z, in which case they will be displayed in lowercase. In Visual Studio Code, to toggle the terminal, you press VK_CTRL+VK_OEM_3, which on an US keyboard is the ~` key, but on a Swedish keyboard the Ö key. When displayed, it says "Ctrl+ö" instead of "Ctrl+Ö". The same for toggle line comment, which is VK_CTRL+VK_OEM_2, which on an US keyboard is the ?/ key, but on a Swedish keyboard the Ä key. When displayed, it says "Ctrl+ä" instead of "Ctrl+Ä".

![image](https://user-images.githubusercontent.com/822352/32766711-6e330578-c910-11e7-8428-510613555940.png)![image](https://user-images.githubusercontent.com/822352/32766686-514e4990-c910-11e7-81ad-cae3a5e2da4b.png)

**Comment by alexandrudima** [comment]
The menu (right-hand-side image) is painted natively by Electron/Chromium, so we cannot change the rendering on our side.

We have chosen in-product rendering (left-hand-side image) to match the native menus (like the F1 list or the background keys).

From my double checking in Visual Studio, it appears that it also renders these shortcuts with the lower-case variant, so it might be some Windows (OS) thing that we're all respecting here, I don't know:

![image](https://user-images.githubusercontent.com/5047891/32830500-af4d71d4-c9f5-11e7-991a-b17bf62131cf.png)
