### ISSUE TITLE
Render white spaces: provide option to show white space between words

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3828]
I have a use case to render whitespace but we seem to not render whitespace between words in a line:

![image](https://cloud.githubusercontent.com/assets/900690/13599004/3708247c-e521-11e5-81a0-8bbe6d4218c8.png)

Here I cannot figure out how the help text is formatted unless I use the keyboard.

**Comment by bpasero** [comment]
Not sure if this is actually something we should by default, hence setting bug label.

**Comment by jrieken** [comment]
not implemented as such but fair request

**Comment by jrieken** [comment]
@alexandrudima fyi

**Comment by stkb** [comment]
I love vscode's current whitespace rendering precisely because it **doesn't** mark all the whitespace between words -- which I find way too noisy visually -- just at the start and end of the line where it's really needed. So I hope this would remain an option.

**Comment by jrieken** [comment]
> So I hope this would remain an option.

for sure

**Comment by davkean** [comment]
I thought this was a bug in that it was only showing me whitespace in certain cases, but realize this is the expected behavior. Undecided about the behavior as I've not yet used it, but might I suggest a better name to indicate what it really does?

**Comment by litera** [comment]
So to somewhat recap current state of possible `renderWhitespace` options which should be:

* `false`/`"none"` : no whitespaces should be displayed whatsoever
* `"selection"`: display whitespaces (all of them) when user selects a portion of text
* `"boundary"`: display all whitespace except inline single spaces (double spaces should be shown)
* `true`/`"all"`: display all whitespaces all the time

**Comment by zhoudotnet** [comment]
Hi Alexandrudima,
When this function can be implemented?

**Comment by jrieken** [comment]
this actually happened by a PR in september

**Comment by alexandrudima** [comment]
Yes, many thanks to @marktrz who implemented this in PR #11122

**Comment by alexandrudima** [comment]
To whomever verifies this: Please verify, this feature request slipped our queries and didn't get a test plan item.

**Comment by bpasero** [comment]
Cool 👍

**Comment by liuliangsir** [comment]
Cool 👍
