### ISSUE TITLE
how do i use the extensions that ive downloaded to my software in my code?

### ISSUE THREAD

**Issue by HOUS7L4** [Microsoft/vscode#38282]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
android-dev-ext|ade|0.4.1
path-intellisense|chr|1.4.2
dart-code|Dan|2.4.3
vscode-markdownlint|Dav|0.11.0
javadebugger|don|0.1.5
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
code-runner|for|0.8.3
vscode-firefox-debug|hbe|0.17.0
sde|jin|2.0.20170209
Go|luk|0.6.67
MagicPython|mag|1.0.12
perl-debug|mor|0.2.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
node-debug2|ms-|1.19.0
PowerShell|ms-|1.5.0
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
vscode-janus-debug|otr|0.0.23
vscode-docker|Pet|0.0.22
Ruby|reb|0.15.0
java|red|0.14.0
bash-debug|rog|0.1.0
nativescript|Tel|0.7.2
vscode-lldb|vad|0.7.1
vscode-swift-development-environment|vkn|2.1.1
vscode-arduino|vsc|0.2.10
vscode-java-debug|vsc|0.3.0
cordova-tools|vsm|1.3.0
vscode-react-native|vsm|0.5.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
That depends on the extensions you have downloaded:
- a language extension adds support for that language to VS Code: create a small "hello world" program in that language. The language extension should flag syntactic errors you made and provides code assist while typing.  
- a debug extension gives you a debugger: just try to debug your "hello world" by pressing "F5"
- other extensions add various other functionality to VS Code. How this is surfaced in the UI depends on the extension. Just read the introduction. E.g. for the "vscode-docker" extension that you have installed read this: https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker
