### ISSUE TITLE
code formatter error React Native

### ISSUE THREAD

**Issue by masmun12** [Microsoft/vscode#38283]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
es7-react-js-snippets|dsz|1.2.0
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.5.3
vscode-language-babel|mgm|0.0.10
node-debug2|ms-|1.18.4
sublime-keybindings|ms-|3.0.3
java|red|0.14.0
vscode-react-redux-snippets|tha|0.3.3
vscode-react-native|vsm|0.5.2
babelrc|wad|1.0.0
vscode-js-import|wan|0.12.1

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
What is the error?

**Comment by mjbvz** [comment]
Closing as not enough information to investigate
