### ISSUE TITLE
click save shortcuts many times，it will show many windows to  suggest me fill in the file name，even if I have fill already

### ISSUE THREAD

**Issue by fightinggang** [Microsoft/vscode#38299]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

click save shortcuts many times，it will show many windows to  suggest me fill in the file name，even if I have fill already

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by fightinggang** [comment]
Thank you.
