### ISSUE TITLE
Stopping a debug session should close the debug console

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3829]
- start a debug session
- the debug tool bar appears
- the debug console appears
- debug

When pressing `stop` in the debug tool bar
- the debug tool bar disappears

At this point the debug console should also be closed.

**Comment by isidorn** [comment]
After discussing with @weinand I am hiding the console on any end of a debug session. For instance, also if the user terminates the debugee

**Comment by egamma** [comment]
@isidorn I think there is nothing to verify here since we rolled back this change, correct?

**Comment by isidorn** [comment]
@egamma exaclty, we rolled back the change

**Comment by pflannery** [comment]
> At this point the debug console should also be closed.

If I understand vscode is now going hide the debug console after pressing stop. 
My problem with this change is its essential to see the output history trail of a debug session even if pressing the stop button half way through a session.

Here is an example of stopping debugging with v0.10.11 and what I see after I press stop.

![image](https://cloud.githubusercontent.com/assets/1727302/13901326/c30fa5f4-ee17-11e5-8d0d-6ea58bce33a0.png)

If this is going to forced on us can we make this a configurable debug option?

**Comment by isidorn** [comment]
Right now vscode will never automatically hide the debug console.
We are looking into adding an configuration for debug console behavior which is captured in another issue

**Comment by pflannery** [comment]
@isidorn ok, I'm probably getting the wrong idea here. I'm look forward to the next release! thanks

**Comment by isidorn** [comment]
@pflannery this was just a tryout idea which we reverted in the end.
