### ISSUE TITLE
Git: staging lines from the editor toolbar no longer updates editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38298]
Steps to Reproduce:

1. select some lines in the editor
2. invoke the "Stage Selected Ranges" from the editor toolbar

=> the editor does not update

![image](https://user-images.githubusercontent.com/900690/32768349-ba622df0-c917-11e7-9202-b585c725e27a.png)

**Comment by joaomoreno** [comment]
Seems to work in stable.

**Comment by bpasero** [comment]
@joaomoreno btw sometimes it actually works. Seems like a weird race condition to me :-/
