### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by Yensan** [Microsoft/vscode#38297]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
vscode-color|ans|0.4.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
intellij-idea-keybindings|k--|0.2.16
MagicPython|mag|1.0.12
python|ms-|0.8.0
cpptools|ms-|0.14.2
java|red|0.14.0
vscode-java-debug|vsc|0.3.0
jinja|who|0.0.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1.   write simple "hello world" code, then debug | run it.
2.   all of thing is going well, but vsCode pop up a string "Debug adapter process has terminated unexpectedly".  So annoying !

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What language are you debugging?

**Comment by Yensan** [comment]
@weinand 
python,   and sorry for forgot writing.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#158
