### ISSUE TITLE
Feature request: go to required file from require() statement

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#383]
There is some existing functionality around viewing definitions of a symbol. I would like to propose an expansion of this: when the user's cursor is on a `require` statement in CommonJS, there is a way to jump to the file that will be returned by that statement. For instance:

``` js
const getPageName = require('./get-page-name');
```

I would like to be able to put my cursor on the `require` statement, hit a hotkey, and then open the `get-page-name.js` file. If the `require` statement is for a node module, like `require('lodash')`, I would expect that hitting the hotkey would open the `main` file of the `lodash` package.

Functionality very similar to this exists in Webstorm. I use it there all the time.

I would be interested in submitting a PR for this, but I'd like to see if you think this is a good idea first.

Thanks!

**Comment by sbrinkmann** [comment]
+1

**Comment by serby** [comment]
+1

**Comment by mnemonic101** [comment]
+1

**Comment by mjbvz** [comment]
I believe this is supported now: just hover over the import string and hit 'go to definition' (<kbd>f12</kbd>):

![jan-25-2017 23-43-03](https://cloud.githubusercontent.com/assets/12821956/22323503/336db80a-e358-11e6-90ba-93bc99bac524.gif)

This will open the file for local paths and open the `*.d.ts` type definition file (or the typescript source) for any node modules that have them. It works with both `require` and `import`

Please let me know if this does not address the original issue or if you run into any bugs.

Thanks

**Comment by NickHeiner** [comment]
This works, although I'd like to see it also work for `node_modules`. If I have `require('lodash')`, then I'd like to be able to hit 'go to definition' and open the file returned by `require.resolve('lodash')`.
