### ISSUE TITLE
Change Request: Choose witch terminal will start

### ISSUE THREAD

**Issue by nao3301** [Microsoft/vscode#38305]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1.Open VSCode and open new Terminal with little plus

I  would like to have the choice with terminal i want to open.

Reproduces without extensions: Yes

**Comment by CoenraadS** [comment]
I would love this also. Currently have to use an extension such as https://marketplace.visualstudio.com/items?itemName=remcoros.startanyshell, but what I really want is one WSL Bash shell, and one Powershell, both running inside VSCode.

**Comment by smbkr** [comment]
Do you mean you wish to have the + button open an external terminal emulator, ie. iTerm or cmd.exe, or that you wish to configure the shell which runs in the integrated terminal (ie. bash or fish)?

**Comment by nao3301** [comment]
I would like to have the possibility to choose witch terminal i start when i click the + button, but integrated not external.

**Comment by nao3301** [comment]
for example powershell or cmd or bash or zsh, ...

**Comment by Tyriar** [comment]
I created an extension to cover this https://github.com/Tyriar/vscode-shell-launcher
