### ISSUE TITLE
Source control not showing any files.

### ISSUE THREAD

**Issue by yashcr07** [Microsoft/vscode#38300]
- VSCode Version: 1.19.0-insiders (73830a)
- OS Version: Windows 10 v1709

It says
> There are no active source control providers."

git gutters also not working

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by WorrenB** [comment]
same here, also 

VSCode Version: 1.19.0-insiders (73830a) x64 architecture
OS Version: Windows 10 v1709

in vs code it shows 
Source Control: Git

in vs code insiders only  
Source Control

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/38244#issuecomment-344027257

Please use `git.path` to configure where `git` is located.
