### ISSUE TITLE
Freeze when opening JS file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#38308]
Open attached JS file.

[workbench.main.zip](https://github.com/Microsoft/vscode/files/1487872/workbench.main.zip)

**Comment by tsalinger** [comment]
I reduced the file to this one line that causes the freeze.

[causesCrash.txt](https://github.com/Microsoft/vscode/files/1491791/causesCrash.txt)

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/567
