### ISSUE TITLE
Word wrap can't toggle from off to wordWrapColumn/bounded

### ISSUE THREAD

**Issue by evanwarner** [Microsoft/vscode#38303]
VSC has one "off" state for word wrapping (`off`), but three possible "on" states (`on`, `wordWrapColumn`, and `bounded`). If your default setting is any of the "on" states, then when you toggle word wrapping, it toggles between `off` and [your setting] as expected.

However, if your default setting is `off`, you can't control which "on" state VSC uses: the only possibility is to toggle to `on`. It's not possible to have word wrapping `off` by default and toggle it to `wordWrapColumn` or `bounded` when needed.

I'd love to see this flexibility implemented via settings like:
`editor.wordWrap`: `on` or `off`
`editor.wordWrapMode`: `viewport`, `wordWrapColumn`, or `bounded`

This way word wrapping is a binary state—either on or off—and you choose which "on" mode you want to utilize (per file type, if desired).

---

- VSCode Version: 1.18.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Set `editor.wordWrap` to `off` in settings.
2. Toggle word wrapping in any document. It will only wrap at the viewport.
3. Now set `editor.wordWrap` to `wordWrapColumn` in settings.
4. Toggle word wrapping in any document. It will bounce between off and your wrap column value.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@evanwarner Your description perfectly reflects what the built-in Toggle Word Wrap does today. I believe it covers the needs of the vast majority of users.

An action that toggles in more custom ways is IMHO doable via an extension which can use vscode user settings editing API to edit the value of `wordWrap` straight in user settings.

**Comment by Ho-Wan** [comment]
@evanwarner @alexandrudima I created an extension that allows settings to be toggled between any two states. There is a gif showing how to use it with wordWrap.
[https://marketplace.visualstudio.com/items?itemName=Ho-Wan.setting-toggle](https://marketplace.visualstudio.com/items?itemName=Ho-Wan.setting-toggle)
Hope this is useful!

**Comment by egamma** [comment]
@Ho-Wan thanks for the update!

Closing the issue, since this is covered by an extension.
