### ISSUE TITLE
supportsFunctionBreakpoints: false is ignored

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#3830]
See https://github.com/felixfbecker/vscode-php-debug/issues/21
I am not currently sending `supportsFunctionBreakpoints: true`, but users are still able to set function breakpoints, resulting in errors.

I just worked on implementing `setFunctionBreakpoints` and it works without having to send the flag in `InitializeResponse`.

**Comment by weinand** [comment]
duplicate of #3848
