### ISSUE TITLE
Double autocomplete suggestions

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#38306]
- VSCode Version: 1.18
- OS Version: macOS

![image](https://user-images.githubusercontent.com/30043375/32771802-98d120fa-c92c-11e7-9c24-74914e715ecc.png)

As you can see in screenshot I have double suggestions, I'm with working with several workspaces. I don't have `jsconfig.json` file. It's JavaScript project. That `col` is class `Column` which doesn't have duplicated methods :)

**Comment by bsvipas** [comment]
![image](https://user-images.githubusercontent.com/30043375/32781546-1e1e584c-c94e-11e7-844b-4bb1df3b7c2e.png)

**Comment by mjbvz** [comment]
A few questions:

1. Does this reproduce if you disable all extensions and restart VS Code?
2. Can you please provide more information about the project structure?
3. Does this happen every time you work with this project?

Also, can you try collecting the TS Server trace of this suggestions request:

1. Set `"typescript.tsserver.trace": "verbose"` in your user settings
2. Reproduce the issue
3. Open the output panel and share the output printed in the `TypeScript` section.

This should help narrow down where the duplicate entries are actually coming from

Thanks

**Comment by mrmlnc** [comment]
This is related to the auto import feature (description for suggest). First suggest is auto import, second is local function (most likely). You can disable auto import by `"typescript.autoImportSuggestions.enabled": false`.

**Comment by bsvipas** [comment]
@mjbvz 

1. Yes it is the same if I disable all extensions...
2. I have 3 workspaces (3 different folders added via VS Code new feature)
3. Yes, this happens right now 100% and it's always the same...

As I can see duplicated methods are `"sortText": "0"`. I changed `fileName` to `HIDDEN` and didn't share all trace, but I guess it will be enough.

[trace.txt](https://github.com/Microsoft/vscode/files/1473498/trace.txt)

As you can see in trace I get double suggestions.

@mrmlnc 

It is not all about `"typescript.autoImportSuggestions.enabled"` and also making it to false didn't help at all.

P.S. In 1.17.2 everything was fine.

**Comment by bsvipas** [comment]
@mjbvz I know why it's.

![image](https://user-images.githubusercontent.com/30043375/32825643-5ef5f622-c9ee-11e7-9585-612841234d7f.png)

It's my fault, I write that `@returns have Column | Row`. I'm really sorry. Closing this issue...
