### ISSUE TITLE
Allow Ctrl+S to save a dirty file of a peek editor when it has focus

### ISSUE THREAD

**Issue by cwberick** [microsoft/vscode#38317]
- VSCode Version: 1.18.0 / 1.19.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Project with Workspace (Typescript)
2. Find one external method inside other method in whatever class.
3. Press Alt+F12 to open "Peek Definition"
4. Modify the method opened in peek definition
5. Shiplá.. bug reproduced..
6. The file opened in peek definition now be opened in workspace.

Even after save the file on peek definition, the file opened on workspace continue without save.

Reproduces without extensions: No

**Comment by cwberick** [comment]
Heey..
Today I add a settings: 
"editor.wordWrap": "wordWrapColumn",

I left this configuration to default "off" and this bug not reproduced more.

**Comment by mjbvz** [comment]
Can you please clairify what the problem is. Here's what I see:

![nov-14-2017 15-11-37](https://user-images.githubusercontent.com/12821956/32810048-2598ad98-c94e-11e7-8584-157d587fd6b0.gif)


Is the error that file from the peek definition (`b.ts` in my gif) still has the unsaved indicator in the workspace, even after you save it?

**Comment by cwberick** [comment]
Yes, even after I save the file (b.ts). Pointer with focus inside peek definition, and I press Ctrl+S and after ESC to save and close peek definition the file b.ts continue with unsaved indicator. This behavior did not happen, even after I change file inside peek definition the file changed would not open.

**Comment by cwberick** [comment]
See my gif. Note that the focus is on the peek definition and when I press ctrl + s the saved file is not b.ts, but index.ts. I believe this behavior is wrong.

![bug-peek-definition](https://user-images.githubusercontent.com/5774595/32887509-439eb68a-caab-11e7-8a2f-6a59c59b7240.gif)

**Comment by bpasero** [comment]
As designed, we open editors that are dirty to prevent data loss.

**Comment by cwberick** [comment]
But this is nothing intuitive @bpasero.
See my image, not would be interesting working like this?

When change file, show the little ball in peek definition.

![suggest1](https://user-images.githubusercontent.com/5774595/32942442-35aab658-cb70-11e7-81e7-1d9c46af80b0.png)

When click to `Close (x)` or `ESC`, then show the confirmation:

![suggest2](https://user-images.githubusercontent.com/5774595/32942443-35c9ac16-cb70-11e7-8ae6-b23dac85a509.png)

**Comment by bpasero** [comment]
@cwberick and what should happen when you close the `index.ts` tab?

**Comment by cwberick** [comment]
In this case if close the `index.ts` would could execute one stack of confirmation of files changed starting by `b.ts`

**Comment by cwberick** [comment]
And if close vscode, then would be open the file `b.ts` on tab with changes before close. Like this no data is lost.

**Comment by bpasero** [comment]
I do not like that behaviour, I prefer that one modified editor maps to one opened tab, anything else makes it very hard for the user to track dirty files.

**Comment by cwberick** [comment]
ok.

**Comment by cwberick** [comment]
I've been in Visual Studio to see how it behaves and actually vscode is behaving the same way it does. However, in visual studio when we save `Ctrl+S` the file in focus inside peek definition the file opened in the tab is saved. I think vscode should behave the same way. In this case, I reiterate that saving the `index.ts` and not `b.ts` file when I am with the cursor in Peek Definition when pressing `Ctrl+S` is a bug.

![bug visual studio](https://user-images.githubusercontent.com/5774595/32946529-0897d6c8-cb7f-11e7-86f4-f9e7193b5df4.gif)

**Comment by cwberick** [comment]
@bpasero ?

**Comment by bpasero** [comment]
Yeah thats a good one, lets take this issue to reflect that.

**Comment by pranaygp** [comment]
@bpasero has there been any updates on this issue? I think this behaviour is rather reasonable and intuitive, though I'm kinda surprised this issue hasn't seen more activity (I'd expect more people to want this). I had someone ask about this very thing on my extension: [CSS Peek](tplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek) and this could really help us:
> If it was possible to save the file that you edit when you peak that would be amazing!! Then you wouldn't have to open that file at all to save it ...

**Comment by regoje** [comment]
I've found that adding the following to ```keybindings.json``` accomplishes nearly the same thing:

```
{
    "key": "ctrl+s",
    "command": "workbench.action.files.saveAll",
    "when": "inReferenceSearchEditor"
}
```

Works for me since I don't tend to keep unsaved files open often.

@pranaygp Might be useful for CSS Peek.

**Comment by Hamzeh75** [comment]
Hi
I agree with guys, that is really annoying, I'm wondering why they still didn't fix this problem ... !!! 
why Ctrl+S work in peek preview ?!? its fine in Visual Studio

**Comment by bpasero** [comment]
![Peek 2019-11-19 11-41](https://user-images.githubusercontent.com/900690/69167168-c6b0e080-0af4-11ea-8884-aa3fb2d8aa13.gif)

I pushed a change to enable this by default if the embedded editor is focused. Pressing `CtrlCmd+S` or `File > Save` will now save both the main editor and the embedded editor.

Feedback welcome, it will be in tomorrows insider build: https://code.visualstudio.com/insiders/
