### ISSUE TITLE
Weird code highlight when dragging from Explorer panel

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#38311]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.1.1
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|3.5.0
code-spell-checker|str|1.4.12

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Drag from an empty area in the Explorer panel to the source code panel.

![image](https://user-images.githubusercontent.com/1658949/32773889-edadd14c-c92a-11e7-9b63-ad826ccec669.png)

**Comment by alexandrudima** [comment]
Fixed via #44517
