### ISSUE TITLE
Code folding is not working properly

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#38314]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
jsrefactor|cms|1.5.3
jshint|dba|0.10.15
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.2.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
javac-linter|fau|1.2.6
JSDocTagComplete|Hoo|0.0.2
java-properties|ith|0.0.2
guid|kos|0.0.1
markdown-shortcuts|mdi|0.8.1
HTMLHint|mka|0.4.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
csharp|ms-|1.13.1
jscs|ms-|0.1.9
debugger-for-chrome|msj|3.5.0
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.3.0
stylelint|shi|0.30.0
addDocComments|ste|0.0.8
sort-lines|Tyr|1.3.0
gitblame|wad|2.2.0
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:
1. Have this code:

```
function test1() {

}
    function test2() {
        
    }
        function test3() {
            
        }
```

2. Try and fold each function.
3. Results here:
![untitled](https://user-images.githubusercontent.com/11310468/32776946-f7249e42-c93c-11e7-9494-c96d02d84146.png)

Problems:
1. you cannot collapse functions test1,2,3
2. if you collaps the end of test1, it will contain test2 and test3
3. if you collapse the end of test2, it will contain test3

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Appears to be a result of #3349

**Comment by andreiropotica** [comment]
It was an example, the problem is with alignment, it's not the same problem. It ocurs even with functions that have code in them.

**Comment by andreiropotica** [comment]
```
function test1() {
    'use strict';
    var x = 10;
    x++;
    if (x)
    x += 10;
}

function test2() {
    'use strict';
    var x = 10;
    x++;
    if (x)
        x += 10;
    }

    function test3() {
    'use strict';
    var x = 10;
    x++;
    if (x)
        x += 10;
}
```
You cannot fold the if from test1
**If you fold test2, it will fold untill the end of test3!**

**Comment by andreiropotica** [comment]
![untitled](https://user-images.githubusercontent.com/11310468/32837035-93046ae0-ca14-11e7-8e1f-9e20d432855e.png)

**Comment by roblourens** [comment]
That part of it is currently by design, since folding is only based on indentation. This issue is tracking smarter folding based on language syntax: https://github.com/Microsoft/vscode/issues/3422
