### ISSUE TITLE
Left-click on statusBar debugButton to launch selected debug and Right-click to select debug config

### ISSUE THREAD

**Issue by Aetherall** [Microsoft/vscode#38313]
First, thanks for the status bar update ! really helpful to avoid switching tabs every minute !! :+1: 

Current Behaviour :

Left-click => show command palette with debug pre-typed
Right-click => does nothing

Desired Behaviour :

Left-click => start debugging with selected debug configuration
Right-click => show command palette with debug pre-typed || even better, show a little selectbox with all the configs to select the one we want to use

**Comment by isidorn** [comment]
@Aetherall thanks for your suggestion.
However this would not align nicely with the other actions in the status bar which only have one execution when left clikcing on them. Right click always does nothing. Also it would be hard to discover.

Leaving open as a feature request to collect other ideas on how to improve the debug status bar

**Comment by fabiospampinato** [comment]
@Aetherall in case you want to do this because you have some projects with a single configuration, and others with more than one, you'll be better off with my [StatusBar Debugger](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-statusbar-debugger) which solves this exact problem.

**Comment by Aetherall** [comment]
@fabiospampinato oh my god thank you !! Your extension is just awesome :1st_place_medal:

**Comment by fabiospampinato** [comment]
@Aetherall I'm glad you like it! 😄 

At the moment there's no option for hiding the included launcher (see https://github.com/Microsoft/vscode/issues/37954), but that may change with the next update. If you really want to remove it now, you can do it via some custom CSS injected by [this](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension, this is not "supported" though.
