### ISSUE TITLE
Insert Cursor Below and Insert Cursor Above do not work over RDP

### ISSUE THREAD

**Issue by thomasalley** [Microsoft/vscode#38319]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
python|don|0.7.0
haml|gro|0.0.2
docker-linter|hen|0.4.0
ruby-linter|hoo|1.0.0
tf-snippets|log|0.5.0
terraform|mau|0.0.19
ruby-symbols|mig|0.1.5
terraform-snippets|min|1.10.5
ruby-rubocop|mis|0.4.0
mssql|ms-|1.2.1
PowerShell|ms-|1.5.0
vscode-ruby-ctags|oto|1.4.1
Chef|Pen|0.6.3
vscode-docker|Pet|0.0.22
Ruby|reb|0.15.0
python|tht|0.2.3
gitblame|wad|2.2.0
---

Steps to Reproduce:

1. Access machine running VS Code via Remote Desktop
2. Attempt to use Ctrl+Alt+Down or Ctrl+Alt+Up keybindings to insert cursors

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Probably the fault of your remote desktop software, I find that it messes up ctrl+keybindings sometimes. You may be able to configure this. This may be help too: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexandrudima** [comment]
@thomasalley There is also the chance that the remote desktop software you are using is eating up those keys. Please check if you can use those keys in other software.
