### ISSUE TITLE
Support for top-level await operators

### ISSUE THREAD

**Issue by jdavis61** [microsoft/vscode#38316]
Will VS Code ever support the ability to execute top-level await operators in the debug console? Currently if you try to execute await <statement> outside of an IIFE you will receive the "unexpected indentifer message". Or is there a way to resolve the promise in the IIFE?

My hope is someday the new chrome dev tools functionality may be added to WebStorm. https://developers.google.com/web/updates/2017/08/devtools-release-notes#await

- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. Open the attached code in VSCode. Set a debug break point at line 7.
2. Click Debug then Start Debbuging. In the debug console type "await testFunction(); " then press enter. SyntaxError: Unexpected identifier appears in the Debug Console.
3. In the debug console, type "(async () => { await testFunction();} )();" then press enter. Promise { pending } appears.

```
async function testFunction() {
    return new Promise((resolve) => {
        resolve('test');
    });
}

testFunction().then((res) => {
    console.log(res);
});
```

**Comment by weinand** [comment]
Node-debug doesn't preprocess the user input in any way before sending it to node.js for evaluation.
So, what you are seeing is expected but I understand it would be nice if VS Code could wrap the expression automagically into a closure.
On the other hand this "magic" could result in strange bugs that are difficult to diagnose.

@roblourens ?

**Comment by roblourens** [comment]
I believe this will come automatically with newer Chrome and Node versions. Will leave this open on myself to test and verify.

**Comment by roblourens** [comment]
Chrome sends `"(async () => {return (await Promise.resolve('hi'))})()"`

**Comment by auchenberg** [comment]
So the Chrome DevTools front-end sends a special formatted expression for top-level operators @roblourens?

**Comment by roblourens** [comment]
Right

**Comment by laggingreflex** [comment]
Does the recently introduced [experimental-repl-await](https://nodejs.org/api/cli.html#cli_experimental_repl_await) in node v10 help with this?

**Comment by roblourens** [comment]
Probably but it's not necessarily any easier than what I said before.

**Comment by roblourens** [comment]
This is actually a fairly easy vscode-chrome-debug-core feature request. I filed https://github.com/Microsoft/vscode-chrome-debug-core/issues/353

**Comment by roblourens** [comment]
I would take a PR for this. The change will be entirely inside the debug adapter, see https://github.com/Microsoft/vscode-chrome-debug-core/issues/353 and https://github.com/Microsoft/vscode-node-debug2/blob/master/CONTRIBUTING.md

**Comment by connor4312** [comment]
This appears to happen in the latest stable Chrome (77) and Node.js (12.11) versions.

```
await Promise.resolve('foo')
SyntaxError: await is only valid in async function
```

It appears that the Chrome console preprocesses expressions that contain await (if the results [here](https://github.com/ChromeDevTools/devtools-frontend/blob/1d6e57a0e314d709029cac52b98898b828f45a12/front_end/object_ui/JavaScriptREPL.js#L72) have anything returned from [this function](https://github.com/ChromeDevTools/devtools-frontend/blob/281fb455f6b1f6d26cef7df7acd9b96abad7250c/front_end/formatter_worker/FormatterWorker.js#L158)), so unfortunately this does not look super trivial to do. I think it'd be appropriate for us to preprocess console input in the same way, as I imagine that most users will expect the debug console in VS Code to behave identically to the one in Chrome.

**Comment by merqrial** [comment]
...waits patiently...

**Comment by jcrben** [comment]
I noticed the below over at https://github.com/microsoft/vscode-js-debug
![image](https://user-images.githubusercontent.com/5614134/71705102-4b487d00-2d8a-11ea-8156-5feb595cba59.png)

I tried it with https://github.com/request/request-promise-native but not sure how to resolve the promise:
![image](https://user-images.githubusercontent.com/5614134/71705151-9a8ead80-2d8a-11ea-8442-7d81483b9753.png)

**Comment by connor4312** [comment]
@jcrben this happens because Chrome/V8 does not let us await if you're paused on a breakpoint. If you're not on a breakpoint and running normally, we can evaluate the given statement(s) and get the promise result back.

**Comment by galkowskit** [comment]
This is becoming more and more relevant. Deno (a TypeScript runtime) now supports top-level `await`.

**Comment by roblourens** [comment]
I'll call this closed based on the fact that it's supported in https://github.com/microsoft/vscode-js-debug (as good as the runtime lets us) and that is the future of JS debugging

**Comment by jcrben** [comment]
@roblourens @connor4312 is the plan to at some point be able to use this when paused at a breakpoint? That's where I see this as being the most useful.

**Comment by connor4312** [comment]
You can follow this Chromium issue for that, Ben: https://bugs.chromium.org/p/chromium/issues/detail?id=833928
