### ISSUE TITLE
"typescript.useCodeSnippetsOnMethodSuggest"

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#38318]
- VSCode Version: 1.18
- OS Version: macOS

Steps to Reproduce:

1. `"typescript.useCodeSnippetsOnMethodSuggest": true`
2. Write `JSON.parse` and you will get suggestion and press Tab/Enter
3. It will be autocompleted to `JSON.parse(text, reviver)`

That autocomplete doesn't select all params you need to use Tab to move between them and you're almost always using `JSON.parse` without last param only with first one `text`. My suggestion is to make it or add new setting which will select all params when it autocompletes function, etc.

You write `JSON.parse` press Tab/Enter it will be autocompleted to `JSON.parse(text, reviver)` and text starting from `(` will be selected to the end of `)`.

WHY?

Because it is way easier to delete all params including `,` instead of moving with Tab or selecting text with mouse. This feature will make coding a lot easier.

Thanks!

**P.S. This will apply to all functions, not only `JSON.parse` it was only example!**

**Comment by bsvipas** [comment]
@mjbvz I know you're familiar with situations like this. Can you say your opinion? I really want this feature, maybe I can somehow help you to introduce it?

**Comment by mjbvz** [comment]
I think this is generally the expected behavior. The bug here is that we are fill in the optional parameter in the first place. We should only fill in required parameters for useCodeSnippetsOnMethodSuggest

**Comment by bsvipas** [comment]
@mjbvz That makes sense, fill only required parameters. But I also like that behavior explained above (I saw it in Atom with Flow). BUT any of these will be waaaay better than it's right now. As always thanks @mjbvz! ❤️
