### ISSUE TITLE
Git coloring each folder in file explorer

### ISSUE THREAD

**Issue by MarioPadilla** [Microsoft/vscode#38312]
- VSCode Version: 1.18.0
- OS Version: Windows 10 (version 1703) Enterprise 64-bit

Steps to Reproduce:

1. Add some files in a git repository

Reproduces without extensions: Yes

Currently, every folder that contains a file with changes has been coloring.
To prevent a "Christmas tree", my suggestion is **coloring the folder exclusively when is collapsed**.

# VSCode 1.18.0 (current solution)
![issue_vs1](https://user-images.githubusercontent.com/4108194/32773156-82318ab4-c928-11e7-99e1-b4663dc65402.PNG)

# My suggestion (possible modification)
![issue_vs_target](https://user-images.githubusercontent.com/4108194/32773692-4bf8d52c-c92a-11e7-9006-4e57b4ebfbd1.png) ![issue_vs_target_2](https://user-images.githubusercontent.com/4108194/32773698-50fbc232-c92a-11e7-8494-1769657af770.png)

**Comment by OlegLustenko** [comment]
I don't line it.

currently in navigation I can see what folder will be affected by push.
In your proposal it's much hard to find affected folders

**Comment by jrieken** [comment]
Not sure that's a good idea. One very important requirement of this feature is to make it easy to discover modified files in the explorer and part of that is to hint towards them even when a folder is collapsed. To reduce the visual impact of this feature we do allow to only use colors or badges (`"explorer.decorations.badges|colors"` settings)

**Comment by MarioPadilla** [comment]
I get it now. We could customize the "explorer.decorations" settings.
Thanks for your answers @OlegLustenko @jrieken
