### ISSUE TITLE
Error: Lifecycle cannot go backwards

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38325]
Steps to Reproduce:

1. make some changes to a file so that its dirty
2. click on the close window action (on macOS)
3. cancel the window close from the dirty prompt that shows up

Console shows:
![image](https://user-images.githubusercontent.com/900690/32786147-70882c48-c953-11e7-9045-98b1bcad8b5d.png)

**Comment by jrieken** [comment]
@bpasero Do we go back from `ShuttingDown` to `Running` when cancelling the shutdown?

**Comment by bpasero** [comment]
@jrieken yeah looks like it:

![image](https://user-images.githubusercontent.com/900690/32822464-ee1a09a8-c9d8-11e7-807e-d280b727ef92.png)

**Comment by jrieken** [comment]
Hm... I'd propose to not do that. Will check what the impact is

**Comment by bpasero** [comment]
@jrieken maybe we remove this phase? The only client seems to be [`textFileEditorModel`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L677) which maybe can find this out by just listening to the shutdown event?

**Comment by jrieken** [comment]
If you can migrate the `textFileEditorModel` then that would be fantastic

**Comment by jrieken** [comment]
Thanks
