### ISSUE TITLE
Add monitoring to prevent #35992 and #36920 in the future

### ISSUE THREAD

**Issue by schachmat** [Microsoft/vscode#38324]
Please setup some kind of monitoring to detect+fix/prevent bugs like #35992 and #36920 in the future. Possible ideas for how you can achieve this are in the comments of those two bugs.

**Comment by chrmarti** [comment]
The repo team recommends we use `-addfile` instead of `-addpkg` for uploading.

**Comment by chrmarti** [comment]
@joaomoreno FYI: I have updated how we push the .deb package to the repository. (In case this fails in the next insiders.)

**Comment by chrmarti** [comment]
Had to rerun the Linux 64-bit build because the scheduled one got canceled for unknown reasons. The rerun succeeded and published the Debian package (commit 38b13c8f0).

**Comment by chrmarti** [comment]
`-addfile` should be more robust than `-addpkg`. I'm closing this issue as separate monitoring really shouldn't be necessary, the publishing steps should succeed or fail reliably.

**Comment by Tyriar** [comment]
Thanks for doing this @chrmarti!
