### ISSUE TITLE
Chinese translation of `extract`

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#38326]
`extract` should be translated to `提取`, not `解压缩`.

![xxxx](https://user-images.githubusercontent.com/9464825/32786290-79eb3e2a-c98e-11e7-88b7-64dbc99b530e.PNG)

- VSCode Version: 1.18
- OS Version: win10

Steps to Reproduce:

1. debug any extension
2. view some .ts file

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/19863
