### ISSUE TITLE
I don't know what has changed lately.. but it's extremely slow.

### ISSUE THREAD

**Issue by mikeguidry** [Microsoft/vscode#38320]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.17035
- Extensions: none
---

Steps to Reproduce:
Scrolling sometimes takes 3-4 seconds before it moves.. I haven't had this issue in the past.  It happened on  fresh Windows 10 installation..
1.
2.

**Comment by roblourens** [comment]
Can you try the latest release? Is any process using lots of CPU? Is this a VM or single-core CPU?

Also please see the tips here: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by Talljoe** [comment]
Seeing this problem as well on 929bacba01ef658b873545e26034d1a8067445e9. I've jumped on #38679. No excessive CPU usage that I can see.

**Comment by roblourens** [comment]
@mikeguidry Are you using a laptop touchpad to scroll?

**Comment by roblourens** [comment]
I assume this is https://github.com/Microsoft/vscode/issues/35191

**Comment by mikeguidry** [comment]
Thanks guys.  This update I just installed fixes everything!  I'll be sure to use the guidelines next time.
