### ISSUE TITLE
Merge conflict accept all is not shown in command pallete

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#38322]
- VSCode Version:  1.18.0
- OS Version: MacOS Sierra

Hello, I was about to open a feature request because I was missing an accept-all-current command on command pallette. Then, when I was going to configure a keyboard shortcut for another git command I shaw that there is an accept-all-current command available for keybinding. However, this command does not show on command pallette, even if you have a keybinding added for it.

Regards

**Comment by patleeman** [comment]
It looks like this command is registered but doesn't show up in the package.json so it's not being added to the command palette.

The registration call:
https://github.com/Microsoft/vscode/blob/005c78dbf07331e621b7a5570e31cd456f7927db/extensions/merge-conflict/src/commandHandler.ts#L37

The command not found in the package.json
https://github.com/Microsoft/vscode/blob/005c78dbf07331e621b7a5570e31cd456f7927db/extensions/merge-conflict/package.json#L22

**Comment by martellaj** [comment]
Based on @patleeman's comment, it seemed like this was an oversight and should be in the command palette. I followed the existing convention for the other commands and created a PR (#38582).
