### ISSUE TITLE
Emmet: Wrap with Abbreviation not wrapping individual lines

### ISSUE THREAD

**Issue by TGlide** [Microsoft/vscode#38338]
- #### VSCode Version: 1.18.0
- #### OS Version: Windows
#
**Steps to reproduce:**
1. HTML example:
```html    
<ul>
    text1
    text2
    text3
</ul>
```
2. Select whole text between ```<ul>``` and  ```</ul>``` and run ```emmet: wrap with abbreviation```
3. Enter ```li*```

**Expected (as seen on the [emmet docs](https://docs.emmet.io/actions/wrap-with-abbreviation/)):**
```html
<ul>
    <li>text1</li>
    <li>text2</li>
    <li>text3</li>
</ul>
```
**Actual:**
```html
<ul>
    <li>
        text1
        text2
        text3
    </li>
</ul>
```
#

- #### Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
I guess you should use a different  command: **Emmet: Wrap Individual Lines with Abbreviation**

> To wrap individual lines in a single selection in separate tags, use the command `Emmet: Wrap Individual Lines with Abbreviation` instead of `Emmet: Wrap with Abbreviation`.

https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_other-changes

**Comment by TGlide** [comment]
That seems to solve the problem. Thanks!
