### ISSUE TITLE
Feature request: change what git is comparing against

### ISSUE THREAD

**Issue by lcruz4** [Microsoft/vscode#38339]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393

In sublime I used git gutter and always had compare against master set. That way I could see all my changes in my feature branch regardless of whether I've committed or not.

**Comment by joaomoreno** [comment]
That functionality is available in [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens), give it a try.

**Comment by lcruz4** [comment]
I have GitLens. That's not what I was referring to. I was referring to the left gutter highlighting, and now with the new 1.18 release the diff that is shown when clicking on that gutter. Most importantly I can now use f3 and alt + f3 to jump to the next change. I love this change, gut all of these things I would like to control what it's comparing against.
