### ISSUE TITLE
"alt-f, s" keyboard shortcut conflicts (windows)

### ISSUE THREAD

**Issue by mike-kaufman** [Microsoft/vscode#38335]
**VS Code Version:**
  - Version 1.18.0
  - Commit dcee2202709a4f223185514b9275aa4229841aa7
  - Date 2017-11-08T21:22:49.932Z
  - Shell 1.7.9
  - Renderer 58.0.3029.110
  - Node 7.9.0
  - Architecture x64

**OS:**  win 10

**Steps to Reproduce:**

  1.  open a workspace with VS Code
  2.  choose "alt-f"
  3.  note that s shortcut maps to both "save" and "save workspace as" commands.  See image below

**Reproduces without extensions:** Yes

![untitled](https://user-images.githubusercontent.com/8702326/32795680-5551baac-c921-11e7-8371-4294bdc93e04.png)

**Comment by kieferrm** [comment]
Dup of #38006.
