### ISSUE TITLE
中文snippets

### ISSUE THREAD

**Issue by phy0292** [Microsoft/vscode#38337]
在Sublime Text 3中，可以设置中文snippets，效果像附图中所示：
![t1](https://user-images.githubusercontent.com/15998176/32797833-ef0dbb28-c9ad-11e7-8de2-08cba0f40334.png)
而在vscode中，只能设置成英文字符开头后面带中文的snippets，比如像：
“country.中国”   这样是可以的，但是如果第一个字符是中文就不行了。
盼望能实现像Sublime Text 3中那样支持中文开头的snippets

**Comment by roblourens** [comment]
You're saying that snippets don't match with a chinese prefix? This works for me. Can you post your snippets here?

**Comment by phy0292** [comment]
Yes, very correct, that snippets can not be prefixed with Chinese, for example, this is without any effect:
```
	"中国.北京": {
		"prefix": "中国.北京",
		"body": [
			"中国.北京('$1','$2')",
			"$3"
		],
		"description": "到中国北京"
	}
```

**Comment by phy0292** [comment]
I see that the implementation of Sublime Text 3 is that each snippets is a file,
Then use the file name to match the user's input

**Comment by jrieken** [comment]
<img width="481" alt="screen shot 2017-11-23 at 15 38 19" src="https://user-images.githubusercontent.com/1794099/33177848-584308a2-d064-11e7-88ec-d0eeb429c5bc.png">

The snippet works and is shown. `中` is most likely not a word character in the programming language you are using. Closing as dupe

**Comment by jrieken** [comment]
#32201

**Comment by phy0292** [comment]
You enter the characters "中" can appear immediately snippets?
I enter "中" and then press "Ctrl + space" key will appear snippets
If snippets is in English, there is no need to press Ctrl + space will appear immediately snippets
