### ISSUE TITLE
When creating a file, you should be able to enter a path (i.e. with folders)

### ISSUE THREAD

**Issue by Zac-Garby** [Microsoft/vscode#38334]
For example, if I made a file and gave it the name `public/index.html`, it currently just tells me that it's not a valid file name. On TextMate (and probably some other editors), it realises that I've entered a path and creates the relevant directories, so it will create a new folder called `public` where I wanted to make the file, and then inside that new folder it will make the file `index.html`.

I'm not sure what the exact behaviour should be if the directory already exists (e.g. if, after my first example, I made a file `public/styles.css`), but it'd probably make sense to make the file `styles.css` in the existing `public` folder.

It should also be recursive, of course, so you could make a file `public/js/main.js`, for example.

Any thoughts?

**Comment by byronmejia** [comment]
I've always wondered this, but never questioned it... haha :man_shrugging: 

If this is to be implemented, I'm happy to give it a cheeky go. In saying that, what should the behaviour be? On *nix, I've noticed JetBrains products will auto create `files/like/this.png` but upon making a `file\like\this.png` it'll actually come up with a warning.

![screenshot from 2017-11-15 09-08-25](https://user-images.githubusercontent.com/11262664/32809969-c366b2e0-c9e4-11e7-9058-a88893263e61.png)

Would a similar behaviour be expected in vscode? I don't run windows for development, but I'm assuming the reverse behaviour would be expected. `files\like\this.png` work but `files/like/this.png` trigger the dialogue/warning.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
