### ISSUE TITLE
Selecting multiple folders to add to workspace produces "The folder name is not valid"

### ISSUE THREAD

**Issue by TaylorBarrick** [Microsoft/vscode#38336]
- VSCode Version:  1.18.0
- OS Version:  Windows 10 14393.1770

Steps to Reproduce:

1.  Open a New VSCode Window.
2.  Select Add Folder to Workspace
3.  Select multiple folders and click Add

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@TaylorBarrick I cannot reproduce, it must happen with a specific folder you pick. Does it happen always? Which folders do you pick?

**Comment by TaylorBarrick** [comment]
I have tried on a different machine and did not experience this issue,  However, on a work laptop, I am getting this regardless of the folder selection.  I have tested with deep and small paths and paths without spaces on my laptop and it is still the same.  I have also tried running code as administrator, but no luck.

**Comment by bpasero** [comment]
I also tried to reproduce on Windows now to see if that makes any difference and could not. I will close this issue until I get steps to reproduce.
