### ISSUE TITLE
Option to disable Touch Bar controls and leave control strip

### ISSUE THREAD

**Issue by mokyox** [Microsoft/vscode#38333]
[I wrote about this already in a closed issue and was recommended](https://github.com/Microsoft/vscode/issues/14653#issuecomment-344227442) to make a new issue instead.

Is there a way users can disable Touch Bar controls and leave the control strip intact? Something like this without the highlighted area.

<img width="1085" alt="touch bar shot 2017-11-14 at 11 59 33" src="https://user-images.githubusercontent.com/23492964/32794442-caf8b8a2-c960-11e7-9b01-26c56f39fc9b.png">

At the moment, the only workaround is to force the Touch Bar to display the Fn keys but of course, that means I can't use the control strip.

**Comment by bpasero** [comment]
Currently not.

**Comment by mokyox** [comment]
@bpasero Thanks for responding. Is there any chance it will be included in a future update? I keep pressing the run command button by accident.

**Comment by bpasero** [comment]
@mokyox unlikely, if you can generate 100 upvotes, then yes maybe.

**Comment by felipenmoura** [comment]
I like the idea too.
I've been working on a plugin that adds features for the touchbar, but it is limited to 6 buttons because of space.
@bpasero If you can point me the right direction where it is implemented in VSCode source, I can try and open a PR :)

**Comment by mokyox** [comment]
@felipenmoura That would be great. The option to customise the touch bar like many other apps would be very useful.

**Comment by felipenmoura** [comment]
Yes, @mokyox . We added this using the user settings.
We couldn't figure out yet, how to customize it with the same design as other apps in mac.
You can give it a try here:
https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar#overview

**Comment by mokyox** [comment]
@felipenmoura Looks good so far! My only recommendation would be to make the icon sizes bigger. Alas, I think me and the touch bar aren't meant to be and I'd rather have it empty at this point.

Also, if @bpasero can point you in the direction of where it is in the code, that would be great.

**Comment by felipenmoura** [comment]
thanks, cool.
Yep, I agree about the icons...but VSCode support for icons in touchbar is still very limited, that's why we decided to go for the ascii symbols instead.

**Comment by bpasero** [comment]
A setting could be added around here to prevent the creation of the touchbar: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L322

**Comment by viztor** [comment]
can i take this?

**Comment by bpasero** [comment]
**Verify:** via the new `keyboard.touchbar.enabled` setting on a macOS with touchbar.
