### ISSUE TITLE
Files are intermingled

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#38331]
* open `checker.ts` in the left-hand-side editor
* open user settings in the right-hand-side editor
* close and start again vscode
* The contents are intermingled:

![image](https://user-images.githubusercontent.com/5047891/32790308-61151c66-c95e-11e7-87af-066959dfbc7c.png)

**Comment by jrieken** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@alexandrudima wow great catch, I was so much into callback hell that I totally missed that issue :-/
