### ISSUE TITLE
Lock all dependencies in NPM

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38342]
A few dependencies are currently loosely locked as commits or branches in git repositories:

- [x] [`chokidar@bpasero/chokidar#vscode`](https://github.com/Microsoft/vscode/blob/73dea4143950e87d2af2152be01ab1bdd88b1c97/package.json#L26) - @bpasero 
- [x] [`v8-profiler@jrieken/v8-profiler#vscode `](https://github.com/Microsoft/vscode/blob/73dea4143950e87d2af2152be01ab1bdd88b1c97/package.json#L42) - @jrieken 
- [ ] [`xterm@Tyriar/xterm.js#vscode-release/1.19`](https://github.com/Microsoft/vscode/blob/73dea4143950e87d2af2152be01ab1bdd88b1c97/package.json#L46) - @Tyriar  

In order to improve dev performance, we shouldn't use this syntax any more. There are two options:

- Integrate the changes into the upstream project and depend on that
- Start publishing that fork into NPM under a different name

**Comment by bpasero** [comment]
@joaomoreno my latest experiments with chokidar is that we might no longer need my custom fork. It looks like I can npm install latest and it will fallback to compiling `fsevents` if `node-pre-gyp` fails. That is quite awesome! So maybe we do that as part of the yarn update 👍

**Comment by joaomoreno** [comment]
It would be great to do it in `master` first, I'll merge that over to `yarn`.

**Comment by bpasero** [comment]
@joaomoreno we bike?

**Comment by jrieken** [comment]
I wanna explore not having the v8-profiler dependency anymore...

**Comment by joaomoreno** [comment]
@jrieken Please do!

**Comment by bpasero** [comment]
I published `vscode-chokidar@1.6.1`

**Comment by joaomoreno** [comment]
@Tyriar Don't forget to also update https://github.com/Microsoft/vscode/wiki/Working-with-xterm.js accordingly once you do this.

**Comment by joaomoreno** [comment]
FYI For `chokidar`, @bpasero went with the option of creating a `vscode-chokidar` module.

**Comment by jrieken** [comment]
`v8-profiler` is gone, say hallo to to `v8-inspect-profiler` (which is on npm)

**Comment by Tyriar** [comment]
We now use vscode-xterm, instructions updated at https://github.com/Microsoft/vscode/wiki/Working-with-xterm.js

**Comment by joaomoreno** [comment]
@Tyriar Excellent, thanks!
