### ISSUE TITLE
Wrong file highlight when searching in document with Word Wrap on.

### ISSUE THREAD

**Issue by yves-dolce** [Microsoft/vscode#38346]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
githistory|don|0.2.3
gitlens|eam|6.1.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.4.12
gitblame|wad|2.2.0

---

Steps to Reproduce:

1. Set Word Wrap in a file with one or more long lines
2. Search something and try to repro... :-)

![image](https://user-images.githubusercontent.com/1760825/32803651-1021fd80-c939-11e7-909e-edb119d8f6f7.png)

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
@yves-dolce do you mind sharing code snippets for better troubleshooting? I can't reproduce
