### ISSUE TITLE
Long file paths chopped off in 'recent open' list

### ISSUE THREAD

**Issue by psrivastava** [Microsoft/vscode#38345]
![longfilepath-cutoff](https://user-images.githubusercontent.com/3742647/32803172-ac0c1692-c950-11e7-84de-f8cc3c607247.png)

- VSCode Version: 1.18.0
- OS Version: Windows 10 Ent

Steps to Reproduce:

1. Create a file deep in a folder hierarchy.
2. Open and close the file. It creates an entry for the same in VSCode 'recent open' list
3. In the list, you would see the path is long so we don't see file names. Hard to pick if we don't see the file names. Expectation is, to see filename always & show full blown path on mouse hover or in some other way.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10941
