### ISSUE TITLE
[Feature Request] Launch with external tool

### ISSUE THREAD

**Issue by rodrigoelp** [Microsoft/vscode#38358]
Something quite useful with Visual Studio is the ability to allow you to launch/open a file or folder with an external tool.

I have not seen this in so far, but it would be a pretty neat feature. I am doing react-native and I find myself constantly opening xcode from the terminal just shelling out the `open foo.xcodeproj` or `open foo.xcworkspace`

I don't really know if Android Studio has a similar behaviour but, it should be quite nice for anybody using Windows to be able to right-click on a solution file go to the `Open` menu option where other options are listed such as `in terminal`, `Open with [insert name]`

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I think this should be done as an extension. It is unlikely that we would provide this feature out of the box.
