### ISSUE TITLE
Can not read property 'filter' of undefined, when the extension starts with "ty"

### ISSUE THREAD

**Issue by rodrigoelp** [Microsoft/vscode#38357]
- VSCode Version: Code - Insiders 1.19.0-insider (73830a36872aa1c168c085dad8cc6e2e1a05ff45, 2017-11-13T15:33:24.970Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.0
xml|Dot|1.9.2
Ionide-fsharp|Ion|3.12.2
json-to-ts|Mar|1.5.3
jsx|Twe|0.0.1
markdown-mermaid|bie|0.1.1
markdown-preview-github-styles|bie|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.21
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.3
search-node-modules|jas|1.2.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
node-debug2|ms-|1.18.4
debugger-for-chrome|msj|3.5.0
Ruby|reb|0.15.0
java|red|0.14.0
vscode-icons|rob|7.18.1
vscode-java-debug|vsc|0.3.0
vscode-java-pack|vsc|0.2.0
vim|vsc|0.10.4
vscode-react-native|vsm|0.5.2
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Open an instance of vscode insiders
2. Click on extensions
3. Type anything on the filter box (search extensions in marketplace

Reproduces without extensions: haven't tried reproducing it without extensions

**Comment by roblourens** [comment]
Where do you see this error?

**Comment by rodrigoelp** [comment]
Hi Sorry for the delay.

I see this error when I got to the extensions tab (bottom left button) and once it has loaded I type anything on the filter.

**Comment by rodrigoelp** [comment]
Here is a screenshot
<img width="1035" alt="screen shot 2017-11-16 at 7 22 40 pm" src="https://user-images.githubusercontent.com/301434/32880952-a0d15c74-cb03-11e7-9f28-cdf78131f52b.png">

**Comment by roblourens** [comment]
Can you open the developer tools and check for errors in the console?

**Comment by rodrigoelp** [comment]
This is the error I get:

```
Cannot read property 'filter' of undefined: TypeError: Cannot read property 'filter' of undefined
    at w (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4442:545)
    at k (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4443:583)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4449:758
    at Array.map (native)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4449:733
    at Object.g [as _notify] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:134:449)
    at Object.enter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:137:778)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:573)
    at n.Class.derive._oncancel._completed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:14)
    at t.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4442:8)
```

**Comment by rodrigoelp** [comment]
Here is a screenshot of the error (if it gives you more info)
![screen shot 2017-11-17 at 9 07 03 am](https://user-images.githubusercontent.com/301434/32919413-d3143aaa-cb79-11e7-91a4-d8cff91454ca.png)

**Comment by ggilmore** [comment]
I'm also experiencing this here: https://github.com/Microsoft/vscode/issues/38561

**Comment by rodrigoelp** [comment]
Flipping hell!!!! Just noticed the same error with @ggilmore and the fact that he was searching for `typescript` as well... 

The error happens if the string starts with `ty`

**Comment by roblourens** [comment]
I can repro with that. The service must be returning a weird response for that particular query.

Here's the sourcemapped stack @sandy081 

```
w (extensionGalleryService.ts:205)
k (extensionGalleryService.ts:269)
(anonymous) (extensionGalleryService.ts:401)
(anonymous) (extensionGalleryService.ts:401)
g (winjs.base.raw.js:1170)
enter (winjs.base.raw.js:852)
_run (winjs.base.raw.js:1068)
_completed (winjs.base.raw.js:1036)
(anonymous) (request.ts:169)
emitNone (events.js:86)
emit (events.js:188)
endReadableNT (_stream_readable.js:975)
_combinedTickCallback (internal/process/next_tick.js:80)
_tickCallback (internal/process/next_tick.js:104)
```

**Comment by batjko** [comment]
I'm seeing the same if I enter the word `work` and I just tried for the OP's example `type`, and it reproduces as well.

VSCode Insiders v1.19.0

However, it does work for some others, e.g. searching for `todo` gives me a list of relevant extensions, as expected.

**Comment by rodrigoelp** [comment]
I can confirm the same issue as @batjko is reporting.

**Comment by sandy081** [comment]
This is caused due to https://github.com/Microsoft/vscode/pull/31487

**Comment by batjko** [comment]
@sandy081 I'm not sure how that warrants closing this issue. Does it not need to be fixed anymore?

**Comment by roblourens** [comment]
Looks like it was fixed in https://github.com/Microsoft/vscode/pull/38642 @batjko
