### ISSUE TITLE
The new update causes vs code to eat a lot of memory. 

### ISSUE THREAD

**Issue by Eigh** [Microsoft/vscode#38351]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-edifact|DAX|0.1.0
vscode-eslint|dba|1.4.3
xml|Dot|1.9.2
tslint|eg2|1.0.21
vscode-great-icons|emm|2.1.20
vsc-material-theme|Equ|1.1.2
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
mssql|ms-|1.2.1
python|ms-|0.8.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
material-icon-theme|PKi|3.0.0
vscode-icons|rob|7.17.0
edi-x12-support|Sil|0.10.7

---

Steps to Reproduce:

1. Open/editing sql files. Have attached screenshot of memory usage. When I closed vs code, memory usage dropped down dramatically.
![capture](https://user-images.githubusercontent.com/5112226/32805973-e395fbde-c93f-11e7-8e2d-439a55cb49be.PNG)

It might take a while before memory usage shoots up.

**Comment by roblourens** [comment]
Can you follow steps here to provide as much info as possible? https://github.com/Microsoft/vscode/wiki/Performance-Issues

Especially, which processes are using an unusual amount of memory?

**Comment by Eigh** [comment]
Hello Rob,

Please see below:
•What is the size of your workspace/project (how many files)?  **2.17MB/140 Files (26 Folders)**
•What languages are used in this project? **SQL, XML**
•Do you run Code on a single-CPU environment (e.g. VM)? **Nope. I am running it locally on a dual core cpu.**
•Which Code process consumes the most resources? **Found out that it is the MicrosoftSqlToolsServiceLayer.exe that was eating a lot of memory.**

**Comment by roblourens** [comment]
Ok, please file an issue on the SQL extension repo, thanks.
