### ISSUE TITLE
Icon when installing VS Code is blurry

### ISSUE THREAD

**Issue by InstyleVII** [Microsoft/vscode#38354]
- VSCode Version: 1.18.0
- OS Version: Windows 10 16299.64

Steps to Reproduce:
<img width="374" alt="code-blurry-icon" src="https://user-images.githubusercontent.com/1965742/32806375-288e8034-c941-11e7-888d-248e3840d572.png">

1. Download the installer
2. Run the installer

The image used is blurry for my Surface Laptop - resolution is 2256x1504 with 150% display scaling (the recommended setting for Surface Laptop)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
That's fine...

**Comment by InstyleVII** [comment]
@joaomoreno What's fine exactly? Why not use a higher resolution image?

**Comment by joaomoreno** [comment]
We're undergoing a cleanup of issues this month. This one just isn't important enough. Sorry about that.
