### ISSUE TITLE
.code-workspace files do not have JSON colorization

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#38350]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
QML|bbe|1.0.0
file-templates|brp|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
gitlens|eam|6.1.0
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
code-sync|gol|2.5.0
rest-client|hum|0.16.0
redux-snippets|jam|0.0.2
docthis|joe|0.6.0
vscode-codemetrics|kis|1.10.0
vscode-todo|Mat|0.8.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.22
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.17.0
vscode-paste-and-indent|Rub|0.0.8
cmake|twx|0.0.17
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Create a multi-root workplace
2. Save it
3. Open the .code-workplace file
4. witness the lack of syntax highlighting

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
`.code-workspace` is in the list of JSON extensions for a while already (added in https://github.com/Microsoft/vscode/commit/1501dbe6337827e40db6ebea42429db3d03554f1)

Maybe you mistyped the file name?
![image](https://user-images.githubusercontent.com/6461412/32833214-6b33d516-c9fe-11e7-9ea5-5f40b62fc0d9.png)

**Comment by ericblade** [comment]
Unless I'm missing some setting that I've somehow overridden...

![image](https://user-images.githubusercontent.com/1451847/32840981-38197d96-c9e7-11e7-803c-6455fde6a70d.png)
