### ISSUE TITLE
Change CompletionItem API so that some items can be marked by a class name

### ISSUE THREAD

**Issue by yangsiyu007** [Microsoft/vscode#38359]
**Feature request**

We are experimenting with a completion provider to help people find useful methods of .Net classes on [try.dot.net](https://github.com/dotnet/try), which embeds the [Monaco editor](https://microsoft.github.io/monaco-editor/). Each time completion is required, up to 5 CompletionItems are put at the top of the dropdown.

It would be great if CompletionItem can take in another string property, which will then be appended to the div's list of class names (right now it has "monaco-list-row" or "monaco-list-row focused"). This way, try.dot.net can change these CompletionItems' appearance in its css. 

First time submitting feature request - please let me know if more information would be helpful.

**Comment by jrieken** [comment]
Why can you not use `detail` or `documentation` for this? Can you attach a mockup of want you want?

**Comment by yangsiyu007** [comment]
Thanks jrieken - a mockup of what we would like to see:

<img width="588" alt="screen shot 2017-11-17 at 1 43 51 pm" src="https://user-images.githubusercontent.com/9201966/32970470-f82f87bc-cb9d-11e7-9fba-5dd4ba2da305.png">

Basically we want to be able to style some completion items differently so they are distinguishable at a glance, since they are out of the alphabetical order and may confuse the user otherwise. 

My idea for how to do this is, let CompletionItem take another string input, e.g. 'recommended', and then put that string as a part of the <div>'s class, so now this completion item will have class 'monaco-list-row recommended'. The website that embeds the Monaco editor, i.e. try.dot.net, can modify its css to give <div> with class 'monaco-list-row recommended' a different color. 

Let me know and I'll be happy to clarify!

**Comment by jrieken** [comment]
> Basically we want to be able to style some completion items differently so they are distinguishable at a glance, since they are out of the alphabetical order and may confuse the user otherwise.

Tricky because provider only own the *initial* sorting and as soon as something is typed, completion items are re-order based on how well they match that text. 

> My idea for how to do this is, let CompletionItem take another string input, e.g. 'recommended', and then put that string as a part of the div's class

That's nothing we can do for VS Code because extensions have no control/access of/to css-styles et al. Ideally, there is a solution that works for both... Having a color would fit into our model (of color customisations) but this still needs some thinking

**Comment by yangsiyu007** [comment]
Thanks jrieken. I guess customize individual completion items is tricky here. I'll log an issue in the Monaco repo to see if they can do anything there...

**Comment by jrieken** [comment]
> n issue in the Monaco repo to see if they can do anything there?

Nah, it's the same code and people ;-)
