### ISSUE TITLE
Extensions Debug breakpoint don't work

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#38364]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. use `yo code` to create a new extension, `activationEvents: *`
2. open with `--disable-extensions`
3. `F5` launch debug
4. breakpoint is attach, but stack is empty

![image](https://user-images.githubusercontent.com/227713/32813630-2dc75b02-c9e6-11e7-8fa0-e4f5fc7331ab.png)

Reproduces without extensions: Yes

**Comment by atian25** [comment]
e... it works suddenly... will reopen if kick me again.

**Comment by yume-chan** [comment]
I have met the exactly same problem.

My finding was that while the debugger adapter is downloading sourcemaps for Code components, it can't display any stack or variables information.

 I have a rather pool network, and I deleted cached sourcemaps (on Windows they are located in `C:\Users\Simon\AppData\Local\Temp\com.microsoft.VSCode\node-debug2\sm-cache`) multiple times to test.

**Comment by atian25** [comment]
@weinand it happen again, I don't know is there any more information you need ?

**Comment by wangtao0101** [comment]
@atian25 i almost go mad with this issue before i see your answer.  Waiting is worked.

**Comment by Marcholio** [comment]
@atian25 Can you verify if this is still an issue?

**Comment by atian25** [comment]
@Marcholio  1.31.0 work fine.
