### ISSUE TITLE
[uncaught exception]: TypeError: this._state.then is not a function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38360]
**Steps to Reproduce:**

On MacOS with Node 7.8

1. Clone master
2. Do clean install and build
3. Open editor. Try opening a file

**Bug**
Cannot open any files. See `[uncaught exception]: TypeError: this._state.then is not a function` errors

A bisect identifies f24ea58bf8f2db486527e42bc28b70940e1014ee as the cause of this

**Comment by mjbvz** [comment]
Both @rebornix and I have hit this.

I think [this line](https://github.com/Microsoft/vscode/commit/f24ea58bf8f2db486527e42bc28b70940e1014ee#diff-a63388ce79427f16181b4686359ff685R415) where we call `Promise.resolve(detectMimeAndEncodingFromBuffer(...))` may be the root cause of the problem

**Comment by rebornix** [comment]
After reading https://github.com/Microsoft/vscode/issues/32381#issuecomment-323317236 I suppose Promise/TPromise is the thing.

**Comment by mjbvz** [comment]
Root cause of this seems to be that:

1. `detectMimeAndEncodingFromBuffer` returns a `TPromise`
1. When this `TPromise ` is resolved, it swaps out its `.then` method.
2. At this point, I believe `Promise.resolve` has already grabbed the old `.then` implementation. It then invokes this invalid `.then`later

Tested this by changing the code:

```ts
const p: any = detectMimeAndEncodingFromBuffer(
    { buffer: chunkBuffer, bytesRead },
    options && options.autoGuessEncoding || this.configuredAutoGuessEncoding(resource));
    Promise.resolve(p.then ?
        ({ then: (x) => p.then(x) })
        : p)
```

This does seem to work

**Comment by jrieken** [comment]
😱 wow... Stupid WinJS.Promise...
