### ISSUE TITLE
[Extensions] Git error fatal: pathspec is beyond a symbolic link

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#38365]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. when debug my own extension
2. navigate to a symbolic link
3. `DEBUG CONSOLE` output: 

```bash
message:"Git error"
stdout:""
stderr:"fatal: pathspec '/Users/tz/Workspaces/eggjs/test/showcase/node_modules/egg-static/README.md' is beyond a symbolic link
"
exitCode:128
```

![vscode-debug](https://user-images.githubusercontent.com/227713/32814246-194ad98a-c9e9-11e7-8a86-8025c1601ae8.gif)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This is git reporting that there was an error. It appears in the Output pane of your extension because both your extension and git run in the same world. I can't remove that error since it is there on purpose to catch problems. Going to have to close this.

**Comment by atian25** [comment]
so `Git` do not support symbolic link?
