### ISSUE TITLE
Messy and unreadable code with UTF-16 when use built-in compare

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#38366]
- VSCode Version:1.18.0
- OS Version: Windows Sever 2012 R2

Steps to Reproduce:

1. One UTF-16 File.
2. Modify it and compare by VS code Soure Control.
3. Original file will show messy code as below screenshot.

![untitled](https://user-images.githubusercontent.com/26138585/32815656-0e156c68-c9f0-11e7-83f7-ed7d7abe8389.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/21146
