### ISSUE TITLE
cannot use chinese filename when debugging cpp files.

### ISSUE THREAD

**Issue by alanx172** [Microsoft/vscode#38368]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
code-runner|for|0.8.3
cpptools|ms-|0.14.2
vscode-hexdump|sle|1.6.0
html-preview-vscode|tht|0.1.1

---

Steps to Reproduce:

1. edit a cpp file with chinese filename.
2. compiling/building is ok.
3. debugger cannot find the source file. but it's ok when using english filenames.

Reproduces without extensions: Yes/No

yes while disabling all extensions

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1254
