### ISSUE TITLE
the global search is unable after updating.

### ISSUE THREAD

**Issue by luckti** [Microsoft/vscode#38367]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.the global search is unable after updating.
![qq](https://user-images.githubusercontent.com/11832012/32816236-9e9e915e-c9f2-11e7-8d9b-0d545de39bbe.png)

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/37863, fixed in the Insiders build
