### ISSUE TITLE
Incorrect IntelliSense if file encoding and d.ts is not UTF-8

### ISSUE THREAD

**Issue by ocheretnyy** [Microsoft/vscode#38373]
- VSCode Version:1.18.0
- OS Version:Windows 7

Incorrect IntelliSense if file encoding and d.ts is not UTF-8. If d.ts file alredy opened when IntelliSense work correctly.

Steps to Reproduce:

1.  In user settings file set    "files.encoding": "windows1251",
2. Create  d.ts file (encoding = windows1251) with russian symbols:

declare namespace qt_workbench 
_{
    /** Add dock-window 
     * Добавить Dock-окно 
     */
    function add_window(widget : QWidget,title : string,width : number,height : number,is_visible : boolean);
}_
3. Create file and write:
_workbench .add_window()_
3. Move mouse on function add_window for IntelliSense 

![p](https://user-images.githubusercontent.com/17870990/32817248-49c43056-c9ef-11e7-99fa-58b77562bb21.png)

If workbench.d.ts file opened IntelliSense work correctly
![p-1](https://user-images.githubusercontent.com/17870990/32817315-8a76e648-c9ef-11e7-8c43-7dc9e0c0ca37.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20053
