### ISSUE TITLE
Incorrect processing "set variable" while debugging with supportsSetVariable =false

### ISSUE THREAD

**Issue by ocheretnyy** [Microsoft/vscode#38370]
- VSCode Version:1.18.0
- OS Version:Windows 7

My debug adapter do not support set variable capability  (supportsSetVariable = false). In the VARIABLES Panel contex menu "Set Value" is disable (it is right p1) but if user double click on variable vscode start set variable procedure (opens the editing input p2)

![p0](https://user-images.githubusercontent.com/17870990/32816762-0a3e34c4-c9ed-11e7-9bdf-698c2c78c38e.png)

![p1](https://user-images.githubusercontent.com/17870990/32816760-09f6cc92-c9ed-11e7-8ce9-0cb767305900.png)

![p2](https://user-images.githubusercontent.com/17870990/32816761-0a1c9a08-c9ed-11e7-9649-4bb0da7e9f07.png)

Steps to Reproduce:

1. In debug adapter on InitializeRequest set Capabilities.supportsSetVariable  = false
2. Start debug 
3. Pause or make breakpoint
4. In the VARIABLES Panel do double click

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
I can easily reproduce with mock-debug.
It seems that a "setVariables" request is not called but that the UI still shows an edit box and accepts a new value.

**Comment by ocheretnyy** [comment]
If supportsSetVariable = false  - UI should not show edit box and should not send setVariables request.
In debug adapter setVariables request is call, but my adapter does not support set variable, and send empty body response

**Comment by isidorn** [comment]
@ocheretnyy good catch thanks
