### ISSUE TITLE
Right-click context menu from icon in macOS dock shows different recently opened files/folders from File->Open Recent

### ISSUE THREAD

**Issue by adamhamlin** [Microsoft/vscode#38379]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
githistory|don|0.2.3
python|ms-|0.8.0
azure-account|ms-|0.2.2
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
Ruby|reb|0.15.0
java|red|0.14.0
vscode-java-debug|vsc|0.3.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Launch VS Code, then choose a folder to open
2. Close the app
3. Right-click on dock icon; more than likely this folder will not be available as a shortcut (nor will it appear if click "Show Recents")

I would expect that the most-recently used files and folders would appear in this context menu as they appear in the File->Open Recent menu

Reproduces without extensions: N/A

**Comment by bpasero** [comment]
Good timing, just fixed this via https://github.com/Microsoft/vscode/issues/38199
