### ISSUE TITLE
Cursor will be move to EOF on file save

### ISSUE THREAD

**Issue by sisomoti** [Microsoft/vscode#38377]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
python-snippets|cst|0.1.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.21
vscode-npm-script|eg2|0.3.3
javac-linter|fau|1.2.6
vscode-npm|fkn|3.3.0
py-paste-indent|hye|0.0.2
search-node-modules|jas|1.2.0
jenkins-declarative-support|jmM|0.1.0
python-traceback-jumper|lin|1.0.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
sqltools|mtx|0.5.1
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.0.0
evilinspector|sai|1.0.3
jenkinsfile-support|sec|0.1.0
japanese-word-handler|sgr|0.5.0
perforce|sle|3.0.0
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.4.12
python-editing-terminal|ted|1.0.4
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vim|vsc|0.10.4
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Editing any file.
2. Save file by (Shortcut) Ctrl+S / (Vim) Esc->:w / (Menu) File->Save
3. Cursor moved to EOF.

Occurred file extension (I checked):

* *.htm / *.html / *.js / *.css / *.json

No occurred file-extension (I checked):
* *.cpp / *.cs / *.ts / *.jsx / *.groovy / *.py / *.rb / *.bat / *.sh / *.txt / *.log / *.yml / ...

Reproduces without extensions: No

**Comment by roblourens** [comment]
> Reproduces without extensions: No

Sounds like this is probably due to an extension. Could you figure out which one, and file an issue on them?

**Comment by ramya-rao-a** [comment]
I believe the root cause is in the core and not the extension. Logged #38728

**Comment by lostupendo** [comment]
I removed the JS-CSS-HTML-formatter extension and problem is solved.
