### ISSUE TITLE
Using console.time() and console.timeEnd() results in 2 messages printed

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#38376]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Debug a extension
2. use `console.time`
3. unexpected log at `CONSOLE LOG`

```js
export function activate(context: vscode.ExtensionContext) {
    console.time('a');
    console.timeEnd('a');
}
```

output:

```bash
a: 1.056ms  # should NOT print
a: 0.5048939995467663ms
```

1.17 work fine.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
@bpasero this happens only when running the `console.time('a')` in an extension so it is probably related to the console.logging magic. Any idea what this might be?

**Comment by atian25** [comment]
1.17 is fine, only catch this at 1.18.

**Comment by bpasero** [comment]
@weinand I am actually surprised that `console.time` does anything because we only transport a couple of `console` methods over: https://github.com/Microsoft/vscode/blob/master/src/bootstrap.js#L91

**Comment by bpasero** [comment]
I can only speculate that maybe this call forwards to `console.log` and then we get it. Anyway, I think the real request is to support `console.time` and `console.timeEnd`. We should hook this up into our patching and log properly.

**Comment by weinand** [comment]
@bpasero I've tried `console.time` and `console.timeEnd` and they seem to work fine in the EH (and it does not make sense to forward their timer functionality back to VS Code). And if they use `console.log` internally, then this is already forwarded to VS Code.

So the only question that remains is why `console.time` already calls `console.log`.

**Comment by bpasero** [comment]
@weinand @isidorn I spend 30 minutes to find out how it is possible that 2 messages show up in the debug repl and I failed. This is a mystery to me, I am not able to get to the point where the message ends up in the repl, maybe you could also debug.

I verified that `console.timeEnd()` is calling into `console.log`, so that explains at least one message. But I cannot explain the other message.

**Comment by isidorn** [comment]
I also tried debugging it and somehow the other message just strangly appears. I can not yet explain why.

**Comment by bpasero** [comment]
@isidorn I am seeing an output event fired that is causing the output to be appended to the repl:

![image](https://user-images.githubusercontent.com/900690/33882004-f5c80812-df36-11e7-9954-4e195b2b8710.png)

It looks like the debugged extension is actually printing something to stdout and we just show it. 

I do not think I can do something about it from the extension host perspective to prevent that from happening, nor do I think it would be a good idea to prevent that (there may be useful stdout data that we do not want to loose).

**Comment by isidorn** [comment]
I am all up for closing this as will not fix.
Leaving to @weinand to decide though

**Comment by weinand** [comment]
Agreed, closing.
