### ISSUE TITLE
Typescript syntax highlighting breaks when using a variable with the prefix 'var' inside a template literal

### ISSUE THREAD

**Issue by peterkooijmans** [Microsoft/vscode#3837]
I noticed this after upgrading vscode to version 0.10.10. A screenshot demonstrating the problem:

![screenshot](http://i.imgur.com/oi4Hc7s.png)

**Comment by thorn0** [comment]
It's not only in template literals: 
![image](https://cloud.githubusercontent.com/assets/94334/13603693/a7e0f34c-e547-11e5-82cf-127334c6527e.png)

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/TypeScript-TmLanguage/issues/112

**Comment by aeschli** [comment]
Caused by https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

Will be fixed in the March release.

**Comment by thorn0** [comment]
Is there an easy way to update these grammar files separately?

**Comment by aeschli** [comment]
No sorry, no easy way. I will notify you when the first insiders for of the March build is ready (should be next week).

**Comment by aeschli** [comment]
You can get the insiders build here: https://code.visualstudio.com/insiders

**Comment by thorn0** [comment]
Thanks. How do I switch the UI language to English?
