### ISSUE TITLE
New windows not working

### ISSUE THREAD

**Issue by mkmuduli** [Microsoft/vscode#38374]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
cpptools|ms-|0.14.2

---

Reproduces without extensions: Yes

when open a exiting project by "open with vscode"  or create a new windows never work menu and can't write code or open a file

**Comment by joaomoreno** [comment]
Can you show us a screenshot of what you see?

**Comment by alfeg** [comment]
I have similar issue - but I cannot launch new window or open recent project from windows task bar right click menu ( I don't remember how whole this thing called)

But I can open new window or recent project from application menu.

**Comment by joaomoreno** [comment]
Closing due to lack of information.

**Comment by mkmuduli** [comment]
new release solve my problem
