### ISSUE TITLE
Cannot use Markdown Preview feature because of extension markdown-pdf

### ISSUE THREAD

**Issue by ansidev** [Microsoft/vscode#38378]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-wakatime|Wak|1.1.21
vscode-raml|blz|3.0.1
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
php-pack|fel|1.0.1
phpcs|ika|0.7.0
[markdown-pdf](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf)|yza|0.1.7

---

Steps to Reproduce:

1. Open a .md file
2. Click 'Open Markdown Preview to the side' button
3. Nothing happened!
4. If I disable markdown-pdf, everything is OK!

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Since this only repos when the markdown-pdf extension is enabled, please try filing an issue agains this extension instead
