### ISSUE TITLE
Preview HTML Select All command

### ISSUE THREAD

**Issue by sagea** [Microsoft/vscode#38384]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.14.0
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|2.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.21
vscode-rust|kal|0.4.2
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
typescript-hero|rbb|1.7.0
LiveServer|rit|3.0.0
vscode-open|san|0.1.0
javascript-typescript|sou|0.0.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Create a readme.md file.
2. Save the readme.md file
3. In the sidebar right click the readme.md file and select "Open Preview"
4. Focus on the preview window and run the "editor.action.selectAll" command or type "cmd/ctrl A"

**Expected:**
All of the text should be selected

**Actual:**
Nothing is selected

---
I already have a possible solution and will be creating a PR with a possible solution shortly...
---

Reproduces without extensions: **Yes**

**Comment by sagea** [comment]
[Link to the PR](https://github.com/Microsoft/vscode/pull/38387)

**Comment by mjbvz** [comment]
Fixed by #54851
