### ISSUE TITLE
VS Marketplace is really slow in Chinese network

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/vscode#3838]
When I try command `ext install <something>` , it will show progress bar.
And the progress bar will run minutes, and almost noting was listed.
It may be a network connection error.

This issue happened on all my computers (PC&Mac) and all kind of network I can access.

**Comment by rebornix** [comment]
AFAIK, VS Marketplace is really slow in Chinese network, it might take about 5 minutes to load the extension list. If VS Code lost focus during the extension loading, command window would disappear immediately.

**Comment by qin-nz** [comment]
Yes, I have to wait minutes and can not do anything.
Will you change the network of VS Marketplace or fix issue about lost focus?

**Comment by rebornix** [comment]
Those extensions are stored in Visual Studio Online which is unstable in China, I'm not sure whether it can be improved. There can be two workarounds I come up with for now:

1. VS Code adds support for alternative extension registry, then we can mirror all the packages like what Taobao does for `npm` and `gem`.
2. VS Code allows users to pin the Command Palette to avoid it disappear when loading extensions.

Personally I prefer the first option but let's wait for VS Code core team's input.

**Comment by joaomoreno** [comment]
What version do you have? The latest version already addresses this with a server side cache.

How slow can you get the following URL? `https://vscode.blob.core.windows.net/gallery/index`

**Comment by qin-nz** [comment]
I used 0.10.9
I just upgrade to 0.10.10 and the issue solved.

**Comment by joaomoreno** [comment]
Awesome.

**Comment by Milewski** [comment]
i still have a really slow response from extension market.... up to never.... it keeps loading.. but never happen.. eventually with a bit of luck.. one or 2 extensions get installed .. but its really hard to download...

**Comment by joaomoreno** [comment]
cc @modigrv
