### ISSUE TITLE
Excluding files from opened folder

### ISSUE THREAD

**Issue by fatehali429** [Microsoft/vscode#38383]
Could you please allow to exclude files and folder from opened folder?
It should not delete the file just excluding from the list, similar kind of functionality is available in Visual Studio.

This feature will be more useful while developing.

Thanks and Regards,
Fatehali

**Comment by bpasero** [comment]
https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code/30142299#30142299

**Comment by fatehali429** [comment]
Thanks....
