### ISSUE TITLE
Perl - Definitions not found

### ISSUE THREAD

**Issue by Yumash** [Microsoft/vscode#38385]
- VSCode Version: 1.18.0 x64
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file 
#!/usr/bin/perl

my $test = 'a';

if($test eq '23123'){
  print 'ok';
}
2. Go to if($test...) and press F12

Definitions not found!

Perl is installed, as like as extension.
![image](https://user-images.githubusercontent.com/6568685/32823223-5c6386d2-c9ed-11e7-971c-17bf9f43003f.png)
![image](https://user-images.githubusercontent.com/6568685/32823233-64e7aa54-c9ed-11e7-9f05-01276bb1e7e6.png)

**Comment by roblourens** [comment]
Please file an issue on the perl extension, vscode doesn't provide this out of the box.
