### ISSUE TITLE
press tab key not expand abbreviation width "ul{test}"

### ISSUE THREAD

**Issue by zsedcbm** [Microsoft/vscode#38386]
- VSCode Version: v1.18.0
- OS Version: win 10

Steps to Reproduce:

1.New HTML file
2.Enter String "ul",press the tab key, it turn to  "&lt;ul&gt;&lt;/ul&gt;"
3. Enter String "ul{test}", press the tab key, editor is no response, then i press  "ctrl+shift+p" key,select command "Emmet:Expand Abbreviation", then it turn to "&lt;ul&gt;test&lt;/ul&gt;"

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Set `emmet,triggerExpansionOnTab` to `true` for triggering emmet expansion on tab.

Read [Emmet Docs](https://code.visualstudio.com/docs/editor/emmet) as well
