### ISSUE TITLE
not use the type of module being imported

### ISSUE THREAD

**Issue by iugo** [Microsoft/vscode#38390]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. `npm i node-fetch` and `import fetch from 'node-fetch'`
2. var a object as `RequestInit` type
3. the type should be `./node_modules/@types/node-fetch/index.d.ts -> RequestInit`, because I has imported `node-fetch`. But the type use`/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.full.d.ts -> RequestInit`.

Reproduces without extensions: No

**Comment by mjbvz** [comment]
How are you declaring that `a` is of the `RequestInit` type? We will not pick up the library type automatically so you'll typically have to write `fetch.RequestInit` instead

**Comment by iugo** [comment]
`node-fetch`'s d.ts does not contain namespace. But library d.ts exports the type.

I use `import fetch, { RequestInit } from 'node-fetch'` instead of `import fetch from 'node-fetch'` solved the problem. Thanks.
