### ISSUE TITLE
Configure module files available in Node.js global scope

### ISSUE THREAD

**Issue by hubletkoresh** [Microsoft/vscode#38395]
I have an MVC application, with multiple local modules, one of which being models that I install to global scope to enable runtime cyclic references. Unfortunately it also means neither I, nor my team can get Intellisense support for them. It would be really awesome if we could, e.g. in `jsconfig.json` configure such files via for example a glob pattern.

- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro N x64

Steps to Reproduce:

1. Create node.js project
2. Create folder named `models` in root
3. Put `ModelA.js`, `ModelB.js` and `index.js` to that folder
3. Models should have code similar to this
```
exports.model = class ModelA {
 constructor(){
 }

 amazingMethodA(){
    const b = new ModelB();
    b.methodIntellisenseWillNotSuggest();
 }
}
```
4. `index.js` should have code similar to this:
```
const ModelA = require('./ModelA').model;
const ModelB = require('./ModelB').model;

global['ModelA'] = ModelA;
global['ModelB'] = ModelB;

module.exports = { ModelA, ModelB };
```
What I would like is to declare somewhere that all files under folder `./models/**/*` are by default available in global scope and as such should be included in intellisense suggestions in any file defined as part of the project in my `jsconfig.json` `include`s. I know one can write typescript definitions for this, but it's seems like a lot of work for model files - we just would like simpl method suggestions with parameters. Our models have a lot of methods, since they use inheritance. Is it too big/niche feature?

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20046
