### ISSUE TITLE
Multi-root Workspace with GIT status bar branch (current file track)

### ISSUE THREAD

**Issue by sabau** [Microsoft/vscode#38399]
VSCode Version: 1.18.0
OS Version: Windows 7
Steps to Reproduce:

- Open a new VS Code workspace
- Add 2 git projects
- Navigate between files from different projects
- The current branch visible in the Status Bar is the one active in the Source Control panel, it will be great if it follows the currently active file in the editor (the multiple open files )

Reproduces without extensions: Yes

**Comment by darkvertex** [comment]
Would love to see this addressed. Sometimes I get confused what branch I'm in because it's saying one but it's not the right repo.

**Comment by joaomoreno** [comment]
Fixed this milestone!
