### ISSUE TITLE
Hope can save preference to my Microsoft account.

### ISSUE THREAD

**Issue by Exlsunshine** [Microsoft/vscode#38397]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
php-debug|fel|1.11.1
phpcs|ika|0.7.0
Go|luk|0.6.67

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
If you mean, to sync preferences between computers, there is a "settings sync" extension for this. The suggestion for vscode is tracked in https://github.com/Microsoft/vscode/issues/33688
