### ISSUE TITLE
Windows - "Open in Code" option for file or folder in contextual menu does not work when Code is open

### ISSUE THREAD

**Issue by jjaviercv** [microsoft/vscode#38396]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:46.104Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
team|ms-|1.122.0

---

Steps to Reproduce:

1. Open a folder in Code from a PowerShell prompt
2. Right click on a folder in the Explorer. Select "Open in Code"

Expected: new instance of Code opens, set to work on the folder
Actual: nothing happens

Close all Code instances and try step 2 again. It works now.

Reproduces without extensions: Yes/No

**Comment by jjaviercv** [comment]
Further info: opening folders in Code from PowerShell prompts still works. It is only the contextual menu option that does not work.

**Comment by raouldc** [comment]
I can take a look at this, if no one already has 😄

**Comment by bpasero** [comment]
@jjaviercv I cannot reproduce. Does a full uninstall and reinstall solve it?

**Comment by jjaviercv** [comment]
It does.

**Comment by jjaviercv** [comment]
Post reinstall the issue eventually reproduces again.

**Comment by jjaviercv** [comment]
Right clicking on the VSCode icon on the taskbar and choosing "new window" does not create a new window either.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/33216
