### ISSUE TITLE
Sass files syntax colouring (theme) bug

### ISSUE THREAD

**Issue by steodor** [Microsoft/vscode#38398]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.3
vscode-npm-source|dku|1.0.0
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
json2ts|Gre|0.0.6
GitHubIssues|Hoo|0.1.2
JSDocTagComplete|Hoo|0.0.2
docthis|joe|0.6.0
typelens|kis|1.5.0
node-debug2|ms-|1.18.5
node-modules-resolve|nau|1.0.2
tsimporter|pmn|1.2.14
jsx|Twe|0.0.1
vscode-react-native|vsm|0.5.2
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.6.0

---

Steps to Reproduce:

1. write some scss code with parent selectors and pseudo-elements
2. check syntax colouring (using default dark theme or ANY other theme). Here's a screenshot of the issues, rule names should be the same color, not some yellow and some white, plus that red `background` property name:
![issues sample](https://content.screencast.com/users/teodor.sandu/folders/Jing/media/879080b9-3817-4983-8d66-ad53842a06e3/2017-11-15_0953.png)

It seems to me like it's a tokenizer issue with scss syntax. Please check it out. Thanks!

Reproduces without extensions: Yes, checked

**Comment by aeschli** [comment]
This seems to be all fixed in the latest SCSS grammar (in 1.19):
![image](https://user-images.githubusercontent.com/6461412/32882384-79dc3354-cab4-11e7-80f3-42d086ce7414.png)

**Comment by steodor** [comment]
Thanks @aeschli !
