### ISSUE TITLE
Closing HTML tag not highlighting in PHP files.

### ISSUE THREAD

**Issue by inferusvv** [Microsoft/vscode#38391]
- VSCode Version: 1.18.0
- OS Version: Mac OS

Steps to Reproduce:

1. Open PHP file  with HTML
2. Put cursor on tag to see closing tag

All tags will be highlighted. Expected result: only closing tag should be highlighted.

<img width="1214" alt="2017-11-15 11 16 14" src="https://user-images.githubusercontent.com/3227120/32825737-17bd44be-c9f7-11e7-94f4-0a8ff0dd0995.png">

Reproduces without extensions: Yes

**Comment by mcarpenterjr** [comment]
#2915 ?

**Comment by aeschli** [comment]
duplicate of #2915
