### ISSUE TITLE
Feature request: in the file open shortcut, support substring searching

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#384]
I like the file opener. However, I would like it to support a wider set of queries.

For instance, let's say that I have two files called `maestro-events`:

![searching with full text](https://cloud.githubusercontent.com/assets/829827/11314808/05ac7d66-8f9e-11e5-96b3-9f74f1424857.png)

This works fine. However, I would also like to be able to search for a substring of the file name, and have the same set of files be returned:

![searching with shorthand](https://cloud.githubusercontent.com/assets/829827/11314812/0dd27928-8f9e-11e5-8477-417b9dd09c6d.png)

This behavior is supported in Webstorm. I use it there all the time.

I'd be happy to submit a PR for this if you think it's a good idea.

**Comment by chrisdias** [comment]
Happy to take pull requests!

**Comment by NickHeiner** [comment]
Looks like this has been implemented: https://code.visualstudio.com/Updates#_file-picker-improvements-and-fuzzy-search

**Comment by egamma** [comment]
correct, closing as requested, thanks
