### ISSUE TITLE
Visual studio code intellisense is very slow

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#38409]
> Originally https://github.com/Microsoft/vscode/issues/35210#issue-260888056

I am still facing issues in VS while developing angular applications.
I can give you list of extensions although i understand there are many causes which makes intellisense slow.
I have high CPU usage , Slow Intellisense

Can you guys give me some specific build i can use and without EVEN Sending stats you guys can identify the activity that cause CPU high usage and slow and **unresponsive** intellisense.

Thanks
Shan

**Comment by mjbvz** [comment]
@shanalikhan Does this still happen if you disable all extensions?

**Comment by shanalikhan** [comment]
Yes for typescript intellisense slow after disabling the extenions

**Comment by CreamFraiche** [comment]
So I dont have extensions and this happens for me. It fixes itself when it shows me an error at the top of the page that alludes to something about Chrome crashing or something. Is there some built in code that interacts with chrome?

**Comment by mjbvz** [comment]
@shanalikhan Please use process monitor or `ps` to identify the `code` or `code-helper` process with the high cpu usage.

**Comment by kevfuzz** [comment]
Hi, I have the same problem. Intellisense or even just trying to auto-format my code takes ages. I've noticed I think it's triggered being slow after I save a file.

From looking at my processes, I think it's the ng-template-0.1.7 that's maxed out for about a minute.

**Comment by mjbvz** [comment]
@kevfuzz Please open a new issue against that extension

**Comment by mjbvz** [comment]
Closing as not actionable without information on which process has the high cpu usage

**Comment by michael-ctr** [comment]
I have the same issue as well.
There is a 'code' process that jumps to 100% CPU usage for some time whenever doing a typescript intellisense operation

**Comment by michael-ctr** [comment]
Ah - looks like it might have been the TypeScriptHero sxtension causing the slowdown. Disabling that made the slowdown go away
