### ISSUE TITLE
EACCESS error when running extension tests on Ubuntu since 1.18

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#38406]
- VSCode Version: 1.18
- OS Version: Ubuntu 14.04, 16.04

Steps to Reproduce:
1. Since the upgrade to 1.18, when I run my extension tests, I get an EACCESS exception when running the extension tests.
2. It looks like the permissions in the .vscode-test folder are wrong. The error is the same one that caused #25848.
3. In local tests, I can fix this with the workaround from #25848, in CI I needed to write a special workaround, since the workaround is required in the middle of downloadExecutableAndRunTests()

Reproduces without extensions: N/A

Stack trace:
Here is the error stack:  [ 'Error: spawn EACCES',
  '    at exports._errnoException (util.js:1050:11)',
  '    at ChildProcess.spawn (internal/child_process.js:319:11)',
  '    at Object.exports.spawn (child_process.js:390:9)',
  '    at Object.t.spawnRipgrepCmd (/home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:157105)',
  '    at e.cmdTraversal (/home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:159844)',
  '    at e.call (/home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:159547)',
  '    at /home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:159275',
  '    at /home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:100643',
  '    at Array.forEach (native)',
  '    at Object.t.parallel (/home/wix/projects/stylable-intelligence/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/workbench/services/search/node/searchApp.js:4:100621)' ]

**Comment by roblourens** [comment]
I don't think that issue number is correct, can you double check?

**Comment by tempit** [comment]
I had 2 versions of the number, updated to the proper one.

**Comment by roblourens** [comment]
Ok, so this is linux, and the `rg` file has the wrong permissions? Is this an issue when using vscode, or just when running extension tests?

**Comment by tempit** [comment]
Only when running the extension tests.

**Comment by roblourens** [comment]
@jrieken Do you know how the extension development host gets downloaded and why this might happen?

**Comment by jrieken** [comment]
@bpasero might know

**Comment by bpasero** [comment]
@roblourens please check the very recent commit around permissions: https://github.com/Microsoft/vscode-extension-vscode/commit/6b8e62af5f047733c378779a32e99293f5ce58f0

could be related?

**Comment by bpasero** [comment]
@roblourens hm, I think I can still reproduce this issue even with the previous version of the vscode API module so it might not be correlated.  Can you give it a try? My test is simply doing this:

```typescript
//
// Note: This example test is leveraging the Mocha test framework.
// Please refer to their documentation on https://mochajs.org/ for help.
//

// The module 'assert' provides assertion methods from node
import * as assert from 'assert';

// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as vscode from 'vscode';
import * as myExtension from '../extension';

// Defines a Mocha test suite to group tests of similar kind together
suite("Extension Tests", () => {

    // Defines a Mocha unit test
    test("Something 1", done => {
        vscode.workspace.findFiles('*.txt').then(result => {
            assert.equal(-1, [1, 2, 3].indexOf(5));
            assert.equal(-1, [1, 2, 3].indexOf(0));

            done();
        });
    });
});
```

**Comment by guw** [comment]
@bpasero What is the recommended way to consume the insiders build for running tests? I tried setting CODE_VERSION to 1.19.0-insider but that fails.

https://vscode-update.azurewebsites.net/1.19.0-insider/linux-x64/stable

**Comment by bpasero** [comment]
@guw the only (ugly) way currently is to set `CODE_DOWNLOAD_URL` environment variable to point to an insiders release before running the tests. There is no support to configure this in a dynamic way yet to always run against the latest insider build.
