### ISSUE TITLE
Typescript build task fails if path to local tsc contains spaces

### ISSUE THREAD

**Issue by Gorea235** [Microsoft/vscode#38408]
- VSCode Version: 1.18.0 (public)
- OS Version: macOS 10.13.1 (High Sierra)
- Reproduces without extensions: Yes

Steps to reproduce:
1. Have a ${workspaceRoot} in something like `/Users/me/dev folder/project/`
2. Install a local version of tsc using `npm i typescript --save-dev`
3. Configure the default typescript build task (using the `tsc: build - tsconfig.json` preset)
4. It will generate the following:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
5. If you run the build task, it will generate the following error:
```
> Executing task: /Users/me/dev folder/project/node_modules/.bin/tsc -p "/Users/me/dev folder/project/tsconfig.json" <

/bin/bash: /Users/me/dev: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```

If I replicate the task manually, using the following
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "'${workspaceRoot}/node_modules/.bin/tsc'",
            "args": [
                "-p",
                "'${workspaceRoot}/tsconfig.json'"
            ],
            "options": {
                "cwd": "${workspaceRoot}"
            },
            "problemMatcher": [
                "$tsc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
}
```
it works fine, since the executable is wrapped in quotes.

**Comment by dbaeumer** [comment]
Dups #36588

**Comment by Gorea235** [comment]
I don't believe that it's the same issue, as this one is in reference to the compiler executable itself, whereas #36588 is talking about the config path not escaping properly on some systems (on mine that issue is actually fine, since I'm on macOS). The problem here is that when VSCode executes the build task, it uses the path directly without quoting, e.g. 
`/Users/me/dev folder/project/node_modules/.bin/tsc`

When the path is say, `/Users/me/dev-folder/project/node_modules/.bin/tsc`, the build task executes fine. I think the solution to this problem is just putting quotes around the command path, whereas the other issue is more about shell detection.

**Comment by dbaeumer** [comment]
Agree, but the handling of spacing is a general issue and when addressed will work for 'every' part of the command line.

**Comment by Gorea235** [comment]
Ah, that's alright then, I just wanted to make sure that this issue was known, since it was subtly different
