### ISSUE TITLE
Search not working after updating to new release.

### ISSUE THREAD

**Issue by gopikrishnas** [Microsoft/vscode#38405]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Today I have updated my VSCode to 1.18.0 version. After update, Find in Files (Ctrl+Shift+F) option not working. I have restarted visual studio but facing the same. Please check the below screenshot
![image](https://user-images.githubusercontent.com/10492821/32833359-a4107e72-ca24-11e7-9241-a4c1c26d1c3a.png)

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/37863, fixed in Insiders.
