### ISSUE TITLE
c# namespace 

### ISSUE THREAD

**Issue by mengwuwei** [Microsoft/vscode#38400]
- VSCode Version:
- OS Version:

Steps to Reproduce: NONE

Excuse me! Sorry,my english very bad. ^_^

namespace too long,debug Argument view find a variable difficulty,if variable 
count > 30??

I need look all namespace name ,and look variable name,

many time waste to find a variable

can use variable showing frist . namespace showing last? What do I need to do?

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1868
