### ISSUE TITLE
[C++] invalid token on closing bracket

### ISSUE THREAD

**Issue by pgrit** [Microsoft/vscode#3840]
The syntax highlighting for C++ is broken in Version 0.10.10. The results differ depending on the color scheme.

Tested on Windows 10 and CentOS 7

Dark+:
![broken_syntax_highlighting_dark](https://cloud.githubusercontent.com/assets/12607894/13601471/adbe2e5e-e530-11e5-989a-f85f22ccce06.png)

Dark:
![broken_syntax_highlighting_dark](https://cloud.githubusercontent.com/assets/12607894/13601470/adbce706-e530-11e5-872b-252ae810e345.png)

**Comment by MariusWiik** [comment]
Can confirm the same issue with python and C also. Seemed to get fixed when changing to Dark+. Tested in Mac OS X El-Capitan

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#39

**Comment by aeschli** [comment]
Python and C would be different issues and not related.

This issue has to do with the C++ grammar. It's not a regression.

**Comment by aeschli** [comment]
Looks better now in 1.10 insiders. 
![image](https://cloud.githubusercontent.com/assets/6461412/23189087/9349a182-f891-11e6-8e39-e592cbb1299d.png)
