### ISSUE TITLE
"Spawn UNKNOWN" when Ctrl-Shift-F

### ISSUE THREAD

**Issue by ericyy2017** [Microsoft/vscode#38402]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.Open any folder with couples of .C and .H
2.Search any word in folder by Ctrl-Shift-F
3."spawn UNKNOWN" shown in the text box and search cannot start

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/37863, it's fixed in Insiders
