### ISSUE TITLE
All instances of VS Code respond to requests to move the panel to the right/bottom etc.

### ISSUE THREAD

**Issue by ricanontherun** [Microsoft/vscode#38419]
- VSCode Version: 1.18.0
- OS Version: Windows 10.0.15063

Steps to Reproduce:

1. Open two or more instances of VS Code
2. Open the panel in all open instances
3. Click the move to bottom/right button on panel
4. All instances respond by moving their respective panels

Reproduces without extensions: Yes

**Comment by ricanontherun** [comment]
For what it's worth, the move to bottom/right panel button is the only control which causes this cross-instance behavior.

**Comment by shivammittal99** [comment]
Hello, I would like to work on this. I will be writing a pull request soon.

**Comment by shivammittal99** [comment]
Which ConfigurationTarget to use if no workspace is opened

**Comment by ricanontherun** [comment]
Not sure what you're referring to.

**Comment by shivammittal99** [comment]
If I don't have any workspace opened yet, where will the configuration changes be done:
USER, WORKSPACE, WORKSPACE_FOLDER, DEFAULT or MEMORY

**Comment by ricanontherun** [comment]
I'm not super familiar with these settings, but I suppose default will do?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/37351

**Comment by ricanontherun** [comment]
Thanks for looking into this.
