### ISSUE TITLE
Have a "Add recently opened folder to workspace" command

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#38416]
Add Folder to Workspace can support recently added folders, because adding needs to be again a extra step rather than using the recently opened feature

**Comment by bpasero** [comment]
@Jeyanthinath we currently open a native file dialog, what else do you suggest?

**Comment by jeyanthimuthuram** [comment]
@bpasero yup it now opens the native dialog and it is not perfect is choosing recently opened projects 

Like `add recent folder to workspace` , because that makes the jobs more easier without opening a native dialog.

**Comment by Jeyanthinath** [comment]
@bpasero yup it now opens the native dialog and it is not perfect is choosing recently opened projects

Like add recent folder to workspace , because that makes the jobs more easier without opening a native dialog.

**Comment by bpasero** [comment]
@Jeyanthinath yeah I like that idea

**Comment by Jeyanthinath** [comment]
@bpasero If it is a small PR shall I give it a try ?

**Comment by bpasero** [comment]
With the new multi root API! https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#add-remove-and-change-workspace-folders
