### ISSUE TITLE
when I close the terminal,VS Code alert 

### ISSUE THREAD

**Issue by Kemper-Diao** [Microsoft/vscode#38410]
what's the problem
![cut_105322](https://user-images.githubusercontent.com/6892550/32837173-7d3f771c-ca47-11e7-9f40-3467c40c04b5.jpg)

- VSCode Version: Code - Insiders 1.18.0-insider (af39ef560060e7e8ba8d75983c9ec1da3f4d2a20, 2017-11-07T16:42:33.037Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
Angular2|joh|2.11.0
easy-less|mrc|1.4.5
vetur|oct|0.11.3
vscode-css-peek|pra|1.3.1
vscode-icons|rob|7.18.1
open-in-browser|tec|1.1.0
quokka-vscode|Wal|1.0.80
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ericblade** [comment]
also in current release #38348 .. when using trashcan icon to close WSL terminal.

**Comment by Tyriar** [comment]
Fixed in 1.18.1
