### ISSUE TITLE
Dev setup for vscode not working

### ISSUE THREAD

**Issue by shobhitchittora** [Microsoft/vscode#38413]
<img width="1079" alt="screen shot 2017-11-15 at 6 51 57 pm" src="https://user-images.githubusercontent.com/4711855/32838288-6b5e2d9c-ca36-11e7-88c0-23e9738c0403.png">

- VSCode Version: 1.18.0
- OS Version: OSX 10.13.1

Steps to Reproduce:

1. Pull latest master
2. Install dependencies
3. Build VS Code (Cmd + Shift + b).
4. Run built binary

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Not sure what this is. How did you run it?

**Comment by shobhitchittora** [comment]
@roblourens this was probably some node modules installation thing. Removed my node dependencies and installed again. Working now.

Thanks. 😀
