### ISSUE TITLE
Buggy autoimport with Flow

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#38411]
- VSCode Version: 1.18
- OS Version: macOS

I've been wondering what was corrupting my source code each time I used some of Flow types. I just discovered that VSCode got a little smarter this release. So now it corrupts my source code.

```
import type { One, Two } from './types';
import somethingElse from './something-else';

function test(): Three {
  
}
```

Turns into some rubbish when I type `Three ` and hit enter on autosuggestion. I actually do not understand how it matches Flow types in JS files at all since they are defined with `type MyType = ..`.

Steps to Reproduce:

1. Use Flow type import in `.js` file
2. Reference any Flow entity and hit enter on suggestion. Seems like `import type {} ..` disrupts the normal functioning of  #VSCode.

Workaround:

It's incredible but if you use Flow you better disable everything in VSCode:

```
"typescript.validate.enable": false,
"javascript.validate.enable": false,
"typescript.autoImportSuggestions.enabled": false,
```

**Comment by mjbvz** [comment]
We don't support flow out of the box. Please try installing and confiruging one of the flow language extensions. You can also disable auto imports by setting ` "typescript.autoImportSuggestions.enabled": false`
