### ISSUE TITLE
Terminal pixelated after waking up the Mac from sleep

### ISSUE THREAD

**Issue by bajras** [Microsoft/vscode#38415]
Im using Version 1.19.0-insider (1.19.0-insider) of Vscode and every time I wake up my computer from sleep in Mac 10.12.6 the terminal and other tabs are pixelated and blurry until I reload the window. 

<img width="977" alt="screen shot 2017-11-15 at 8 19 21 am" src="https://user-images.githubusercontent.com/3359989/32840756-3687a01a-c9de-11e7-9f0b-d588d2a657a9.png">

**Comment by Tyriar** [comment]
Does it always only happen when characters that do not have the default background?
