### ISSUE TITLE
Accessibility: Support exposing current language to screen readers

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#3841]
NVDA supports 43 languages, we should support exposing the current language to the tool.

Here is the requirement: 

> Ensure that user agents can correctly present content written in multiple languages. For all content, the default human language must be programmatically exposed when supported by the file format. Additionally, expose the language for each passage or phrase that differs from the default language. Exceptions include proper names, technical terms, and words or phrases that have been adopted into the default language.

CC: @zersiax

**Comment by zersiax** [comment]
Confirmed, this is a WCAG requirement. I'm not sure how Chromium renders the full VS Code interface, but in HTML this would be a matter of adding a proper lang attribute to the HTML element (usually a language is preferred rather than a language + dialect) for the entire document and lang attributes on the tags that deviate from the main language of the document.

**Comment by dbaeumer** [comment]
@alexandrudima do you have an idea how I can tell the screen reader the language of the UI? The language used to render the UI is available in process.env['VSCODE_NLS_CONFIG'].

**Comment by dbaeumer** [comment]
@alexandrudima please move back if there is something I can do here.

**Comment by alexandrudima** [comment]
@bpasero I think the problem is in `electron-browser\index.html` that hard-codes `<html lang="en">`. Not sure if this is something for March?

**Comment by bpasero** [comment]
@dbaeumer if you feel brave, just make the change in index.html to pick up the language chosen. I have no clue what the implications are.

**Comment by dbaeumer** [comment]
@bpasero I will look into this for April. I am not brave enough to make this for March.

**Comment by bpasero** [comment]
:+1:

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/4433 https://github.com/Microsoft/vscode/issues/5260

I marked them as important as it's mixing up characters for the various CJK languages.
