### ISSUE TITLE
debug launch: environment variables not passed to node when using useWSL: true

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode#38425]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.0
vscode-color|ans|0.4.5
QML|bbe|1.0.0
file-templates|brp|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
gitlens|eam|6.1.0
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
code-sync|gol|2.5.0
rest-client|hum|0.16.0
redux-snippets|jam|0.0.2
docthis|joe|0.6.0
vscode-codemetrics|kis|1.10.0
vscode-todo|Mat|0.8.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.22
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.18.1
vscode-paste-and-indent|Rub|0.0.8
cmake|twx|0.0.17
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Configure a node debugging launch using useWSL: true
2. Add an environment variable such as "env": { "TEST_ENV": "This wont show up" } to launch.json
3. Run code: console.warn('*', process.env['TEST_ENV']);
4. Output is '* undefined'

Turning off useWSL works as expected.

Reproduces without extensions: Yes

**Comment by sgtoj** [comment]
It is not just limited to `env`. It affects `envFile` too.

**Comment by jordanbozas** [comment]
Hey guys, is there a workaround for this?

**Comment by ggondim** [comment]
One workaround for me is using `nodemon` and specifying a specific env config for it. Example:

- package.json
```javascript
  "nodemonConfig": {
    "env": {
      "NODE_ENV": "production"
    }
  },
```

- launch.json
```javascript
    {
      "type": "node",
      "request": "launch",
      "name": "nodemon-prod-windows-wsl",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceRoot}/server.js",
      "restart": true,
      "console": "internalConsole",
      "internalConsoleOptions": "neverOpen",
      "useWSL": true
    },
```

**Comment by BrandonLWhite** [comment]
While trying to get envFile to work, a workaround I discovered is to set the `WSLENV` to contain all of the vars you want to manifest in the WSL environment.

- launch.json
```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch copyNamespace",

            // Load personal options into the environment.
            "envFile": "${workspaceFolder}/.vscode/launch.env",

            "program": "${workspaceFolder}/whatever.js",
            "args": [
                "--env-src=$ENV_SRC",
                "--namespace-src=$NAMESPACE_SRC",
                "--env-dest=$ENV_DEST",
                "--namespace-dest=$NAMESPACE_DEST",
                "--user=$BODHI_TEAM_USER",
                "--pass=$BODHI_TEAM_PASSWORD"
            ],
            "windows": {
                "useWSL": true
            }
        }
```

launch.env
```
ENV_SRC=prd
NAMESPACE_SRC=blahblah
ENV_DEST=dev
NAMESPACE_DEST=bleeblee
BODHI_TEAM_USER=john.doe
BODHI_TEAM_PASSWORD=supersecretpassword

# This is needed in order for the vars above to manifest in WSL bash. It should be harmless for MacOS.
# I wish there was a better way to do this, but this is the only way I could make it work.
WSLENV=ENV_SRC:NAMESPACE_SRC:ENV_DEST:NAMESPACE_DEST:BODHI_TEAM_USER:BODHI_TEAM_PASSWORD
```

**Comment by ericblade** [comment]
So, I guess, now it's not technically a bug, but a feature request, since WSL now has that feature? :-D

**Comment by ggondim** [comment]
> Thank you @BrandonLWhite!
> That worked. Also directly inside the `launch.json`.
> 
> ```json
> "env": {
>   "NODE_ENV": "development",
>   "USERNAME": "testuser",
>   "PASSWORD": "testpassword",
>   "WSLENV": "NODE_ENV:USERNAME:PASSWORD"
> }
> ```

I will remove my workaround also to confirm it works for me too. If this is a feature, is a nice one and this issue must be closed.

**Comment by levrik** [comment]
@ggondim Settings the `WSLENV` is still a workaround! I would expect VS Code to set this automatically if `useWSL` is set to `true`. I could make a PR if nobody else started.

**Comment by ericblade** [comment]
weird, github sends me a notification that levrik edited my comment here, but he edited his own comment.  sounds like we need to file a bug in github. :-)

**Comment by DOTA2mm** [comment]
> Thank you @BrandonLWhite!
> That worked. Also directly inside the `launch.json`.
> 
> ```json
> "env": {
>   "NODE_ENV": "development",
>   "USERNAME": "testuser",
>   "PASSWORD": "testpassword",
>   "WSLENV": "NODE_ENV:USERNAME:PASSWORD"
> }
> ```
boring it doesn't work for me.

**Comment by poutler** [comment]
@levrik did you end up doing anything with this? I completely agree, setting useWSL to true should just make things work.

**Comment by anonimitoraf** [comment]
@poutler Did the workaround work for you, at least? It didn't for me

**Comment by weinand** [comment]
With the June release of VS Code, `useWSL` will be deprecated and we will remove support for it soon. Please use the "Remote WSL" extension instead which should not have this issue.
