### ISSUE TITLE
VSCode always reload at the first time open (even if open new another window) from version 1.18.0

### ISSUE THREAD

**Issue by lptai** [Microsoft/vscode#38423]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.11.1
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.1.0
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.21
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|1.2.0
prettier-vscode|esb|0.24.0
code-runner|for|0.8.3
ginfuru-vscode-jekyll-syntax|gin|0.0.5
vscode-jekyll-snippets|gin|0.8.7
vscode-atom-sass-snippet|glu|0.0.3
beautify|Hoo|1.1.1
Angular2|joh|2.11.0
sublime-babel-vscode|jos|0.2.9
markdown-shortcuts|mdi|0.8.1
Angular-BeastCode|Mik|5.0.15
atom-keybindings|ms-|3.0.2
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
language-liquid|nei|0.0.2
vscode-jsp|pth|0.0.2
java|red|0.14.0
vscode-icons|rob|7.18.1
sass-indented|rob|1.4.5
code-settings-sync|Sha|2.8.5
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.6.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open vscode
2. Waiting for a little bit time, vscode is reloaded (see my attached gif) 
![reproduce](https://user-images.githubusercontent.com/22133730/32866941-d01b690a-ca9c-11e7-8277-d4db56989a83.gif)

> It make the UX going to bad

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand what you mean by "reload" can you include screenshots or gifs to demonstrate?

**Comment by lptai** [comment]
I added a gif that help to reproduce

**Comment by roblourens** [comment]
Could you start code with the `--verbose` flag and check for error output?

And could you also open the Developer Tools before this, and see if there are any errors in the console?

**Comment by bpasero** [comment]
@lptai I wonder if an extension could trigger our reload command. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by lptai** [comment]
Thanks for your support.
I observed that only happen with React project (maybe related to react snippets extension) not a vscode issue.
I close it.
