### ISSUE TITLE
stop debug button with node processes using useWSL: true doesn't kill node

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#38424]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.0
vscode-color|ans|0.4.5
QML|bbe|1.0.0
file-templates|brp|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
gitlens|eam|6.1.0
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
code-sync|gol|2.5.0
rest-client|hum|0.16.0
redux-snippets|jam|0.0.2
docthis|joe|0.6.0
vscode-codemetrics|kis|1.10.0
vscode-todo|Mat|0.8.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.22
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.18.1
vscode-paste-and-indent|Rub|0.0.8
cmake|twx|0.0.17
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Configure a node debug session, using useWSL: true
2. Start debugging
3. While it is running, open Task Manager, Details, sort by Name, scroll down to 'node'
4. Click the "Stop Debugging" button in VS Code
5. 'node' process doesn't get terminated

Reproduces without extensions: Yes

**Comment by thecodingdude** [comment]
I am also having this issue.

**Comment by besser** [comment]
I am having this issue too in either Code and Code Insiders

**Comment by tonnyone** [comment]
I am also having this issue.

**Comment by thecodingdude** [comment]
@weinand any status updates? Sorry to bother but it's quite a breaking issue :/

**Comment by weinand** [comment]
fixed for "legacy" protocol (node versions < 8.0).
"inspect" protocol seems to work already.

**Comment by weinand** [comment]
To verify:
- on Windows start "bash" (to open WSL) and run "node --version". Make sure that version < 8.0. Otherwise install a 7.x version of node.
- on Windows configure a node launch config with `"useWSL": "true"`
- start debugging
- in bash run "ps -ax" to verify that a node process is running
- click the "Stop Debugging" button in VS Code
- in bash run "ps -ax" to verify that no node process is running

**Comment by dbaeumer** [comment]
verified.
