### ISSUE TITLE
Statusbar items should have a `min-width` set

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#38435]
I think they would look better if a `min-width` was set so that all items containing an icon had the same width:

![icon_width](https://user-images.githubusercontent.com/1812093/32852822-716cbd22-ca39-11e7-9353-4182a968d24a.gif)

**Comment by bpasero** [comment]
Closing as wontfix because space in the status bar is already very limited, so I would not want to bloat that space anymore than needed.
