### ISSUE TITLE
Pressing Alt + f, s highlights Save Workspace As instead of saving.

### ISSUE THREAD

**Issue by mikeatcayzen** [Microsoft/vscode#38432]
Pressing Alt + f, s
expected behavior: save the document
observed behavior: highlights the Save Workspace As option in the File dropdown menu.

This used to work prior to this release.  Please restore the behavior.  

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
ng-template|Ang|0.1.7
tslint|eg2|1.0.21
csharp|ms-|1.13.1
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mikeatcayzen** [comment]
duplicate

**Comment by jkristia** [comment]
Why did this get closed, is there any way to get old 'Alt F S' behavior back. I have used this key combination for many years and cannot get used to Ctrl-S
