### ISSUE TITLE
Cannot exit VS Code after October Update

### ISSUE THREAD

**Issue by dsjamison** [Microsoft/vscode#38430]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-markdownlint|Dav|0.11.1
jshint|dba|0.10.15
githistory|don|0.2.3
jupyter|don|1.1.3
xml|Dot|1.9.2
vscode-sql-connect|dvd|0.2.1
tslint|eg2|1.0.21
json-tools|eri|1.0.2
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
prettify-json|moh|0.0.3
mssql|ms-|1.2.1
atom-keybindings|ms-|3.0.2
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
debugger-for-chrome|msj|3.5.0
sqltools|mtx|0.5.1
vscode-sql-beautify|sen|0.0.4
python|tht|0.2.3
jinja|who|0.0.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@dsjamison I do not see this problem. Please provide reproducible steps.

**Comment by dsjamison** [comment]
When I'm running VS COde with the October Update and I click on the close (X) for the windows or I select Exit from the File menu or I press Alt-F4, VS Code will not exit.

**Comment by dsjamison** [comment]
Update: VS Code eventually disappears from the task bar and does not appear to be running in the task manager.

**Comment by dsjamison** [comment]
Update: looks like it takes about a minute to close and it does not matter if VS Code is open or minimized.

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dsjamison** [comment]
Running without extensions did not help. Now that I know that it will close after a minute, I'm no longer concerned about the issue. I'll let you know if I figure it out.

Thanks, Dave Jamison

**Comment by mrxinu** [comment]
I'm having the same problem. I've stripped out every extension and emptied my settings and it still happens. I don't have anything else to add; just throwing in a +1 here.

**Comment by roblourens** [comment]
Can you check which processes are still running between when you try to quit, and the window closes? Is there anything using lots of CPU?

Can you find those processes and get their command line args using the tips here? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by TommiTikall** [comment]
I have the exact same problem. Code will not close/exit when clicking the close button nor Alt + F4, and has to be terminated in task manager. Running code without extensions from the command line does not help either. Also tried re-installing code. Still won't close.
Running on Windows 10, v 1709, OS build 16299.64

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by dsjamison** [comment]
All,

I believe my problem is related to the Windows 10 Fall Update and the
WebRoot Security program. If I close WebRoot the problem goes away. There
is a patch for WebRoot that should be applied soon.

Thanks,

Dave Jamison

**Comment by TommiTikall** [comment]
@bpasero 
Yes @dsjamison is correct.
I too was able to solve my issues by disabling webroot.
