### ISSUE TITLE
Open with Code conflicts with Sort by on English Windows

### ISSUE THREAD

**Issue by nohwnd** [Microsoft/vscode#38439]
- VSCode Version: 1.18.0
- OS Version: 10.0.15063
![image](https://user-images.githubusercontent.com/5735905/32853842-e7252c36-ca3c-11e7-8e6c-0251b0638ada.png)

`Open with Code` context menu item uses the same letter shortcut as `Sort by` in the Folder menu and as `Open` in the File menu. Open with code can still be reached by pressing `o` twice, but `i` is not conflicting with anything in both Folder and File context menu. 

( FWIW For the folder menu the candiates are `n`, `i`, `t` ,`c`, `d`. From that only `i` is available in the File menu. )

Steps to Reproduce:
1. Have VSCode installed with the option "Open with code context menu" enabled.
2. Go to any folder and open the context menu using `Shift+F10` or the context menu key on your keyboard
3. Press `o` to `Open with C*o*de`, but get `S*o*rt by` instead.

Reproduces without extensions: Yes

If you would accept the change I would be happy to create a PR.

**Comment by joaomoreno** [comment]
What is the suggested alternative letter?

**Comment by nohwnd** [comment]
It is `i`.

**Comment by joaomoreno** [comment]
Sure... why the hell not. I'll do it, since the change is in our private distro repo.

**Comment by nohwnd** [comment]
Awesome!
