### ISSUE TITLE
Opened text document events are indistinguishable in their emitter

### ISSUE THREAD

**Issue by felicio** [Microsoft/vscode#38431]
I'm building an extension that relies heavily on `onDidOpenTextDocument` events. In it, I'm listening for `file` resources, but I'm unable to distinguish whether the document was opened by user for viewing/editing or by `vscode` on symbol hover.

Myself, I cannot classify the behaviour as buggy, but I'd like to steer the conversation in two directions. One being a possible API proposal, and the other how should one go about it now under current implementation.

**Environment:**

- Extension: https://github.com/felicio/vscode-fold/blob/1f2d0f02f558b241e8f8797c06b6c168c9913d49/extension.js#L47
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0

**Comment by jrieken** [comment]
We actually don't know that. Why do you need to know?

**Comment by felicio** [comment]
FOA, thank you for swift answer. What the extension [here][1] does is it folds opened document to a default `fold.level`. Unfortunately, it does that even when user just tries to use Go to Symbol feature (on `⌘+Mouse hover`).

I inspected the behaviour depicted in issue's description [here][2]. In it I cannot count on `window.activeTextEditor.document` being equal to just opened document since the value still results to a previous document, if any.

Interestingly enough, that's not the case for a workspace folder under source control. Since the `onDidOpenTextDocument` event is called twice for the same resource. Once with `file` and then `git` scheme. What more, in later case `window.activeTextEditor.document` is already set and the extension can make the decision to fold the document. That's why what's published in Marketplace kind of works.

[2]: https://github.com/felicio/vscode-fold/blob/1f2d0f02f558b241e8f8797c06b6c168c9913d49/extension.js#L47
[1]: https://marketplace.visualstudio.com/items?itemName=felicio.vscode-fold

**Comment by jrieken** [comment]
> What the extension here does is it folds opened document to a default fold.level. 

Folding is a UI thing, opening a text document not in all cases because you can open a text document (in the fs.open-sense) without *showing* it to the user. I believe you should use `onDidChangeVisibleTextEditors` and/or `onDidChangeActiveTextEditor`

**Comment by felicio** [comment]
What a clear explanation! Please, give me some time today so I can test all the edge cases.

**Comment by felicio** [comment]
Thanks to your insight I was able to get it all under control and operate on the right level. The `onDidChangeVisibleTextEditors` event is what I ended up listening to.

If I may have a follow up question, do you know about any limitations in current architecture that'd totally prevent **first display of document with blocks pre-folded** from realizing in the (near) future?

**Comment by jrieken** [comment]
> totally prevent first display of document with blocks pre-folded from realizing in the (near) future?

@aeschli would know that


Closing this issue as question
