### ISSUE TITLE
Add preview web page in new tab

### ISSUE THREAD

**Issue by VitaliyLavrenko** [Microsoft/vscode#38433]
Add feature to preview web page in new tab.

Not simple HTML preview like [this plugin](https://marketplace.visualstudio.com/items?itemName=negokaz.live-server-preview) in market, but open by URL address. It's allow to edit express\webpack-dev-server in VSCode and view result in editor. 

Need few button to Back\Forward, Refresh\Stop and show current page address, something like in image bellow.
<img width="1021" alt="2017-11-15 19 44 39" src="https://user-images.githubusercontent.com/2865372/32851398-84796dee-ca3d-11e7-8d34-754082c787b4.png">

And add to config file launch.json entry to open URL in new tab after launch, plus add command to Commands to open page in new tab by typing URL address.

**Comment by bpasero** [comment]
I think this has already been reported. I also think we have no plans to implement this anytime soon, so it would be best to use an extension for this. Closing.
