### ISSUE TITLE
Ctrl+F5 does not start without debugging

### ISSUE THREAD

**Issue by dasanchez** [Microsoft/vscode#38434]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.2

---

Steps to Reproduce:

1. Install Microsoft Python extension
2. Run any .py program once using Ctrl+F5
3. "Debugging" cannot be stopped, bottom status bar remains active
4. Ctrl+F5 becomes useless

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#235

**Comment by weinand** [comment]
Please file python issues against Python repo.
