### ISSUE TITLE
Double-click text selection inconsistent between file types

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3844]
When text is double-clicked to select it, the result varies between javascript files and html (and probably others). For example, if you double-click the word "form" in the below html class attribute, what is selected is actually "form-styled". In the javascript example below, if you double click the word "form" just "form" is selected which is the correct behavior. Same goes for punctuation. In an html file the punctuation is selected along with the word but not in a javascript file.

html/handlebars file (incorrect selection):
&lt;div class="form-styled"&gt;...&lt;/div&gt; <- double-click 'form' and 'form-styled' is selected
&lt;a href="#myLink"&gt;&lt;/a&gt; <- double-click 'myLink' and '#myLink' is selected

css/sass file (incorrect selection):
background-color: #000000; <- double-click '000000' and '#000000' is selected; double-click 'background' and 'background-color' is selected

javascript file (correct selection):
$("div.form-styled").(...); <- double-click 'form' and just 'form' is selected
$("#myLink").(...); <- double-click 'myLink' and only 'myLink' is selected

**Comment by alexandrudima** [comment]
@jayrosen1576 Please try the latest February release, there is a new setting `editor.wordSeparators` that allows you to set the word separators across all languages for word related cursor operations (double click, word navigation, etc.).

**Comment by jayrosen1576** [comment]
Ok that works for double-click, however, single-click still highlights (but not selects) the entire string or value. Shouldn't the single-click highlight match the pattern used for double-click selection?

**Comment by texastoland** [comment]
@alexandrudima Is there a way to customize it for a language extension?

**Comment by alexandrudima** [comment]
Not at this time, I am pretty sure we have an open issue that asks for language-specific configuration/settings (I can't find it right now) and that would cover this use-case.
