### ISSUE TITLE
Working Tree changes comparison shows UTF16LE files with wrong encoding

### ISSUE THREAD

**Issue by Systemcluster** [Microsoft/vscode#38445]
When working in a project with files in UTF16LE encoding, using git, the "open changes" file comparison opens and shows the previous file version with the wrong encoding, making it unreadable.

![Example image of the issue](https://i.imgur.com/mVR0oEA.png)

- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro N

Steps to Reproduce:

1. Create a project, save a file with UTF16LE encoding
2. Initialize a git repository
3. Commit the file
4. Change text in the file
5. Click on the file in the source control changes list to view the changes

Reproduces without extensions: Yes

**Comment by Systemcluster** [comment]
Addendum: "Open File (HEAD)" on the file in the changes list opens the file with the wrong encoding as well.

**Comment by joaomoreno** [comment]
#21146
