### ISSUE TITLE
Opening file from sftp mounted remote location - linux

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#38449]
- VSCode Version: VS 1.18
- OS Version: Fedora 27 

Steps to Reproduce:
1. Have network drive mounted via SFTP in file manager.
2. In terminal type "code sftp://user@server/location/file" 

I currently have VSCode the default application for source code, but if will not open correctly if the file is located on the remote server.

In the video I show me opening the remote file with xed, and then VS code.
![peek 2017-11-15 13-57](https://user-images.githubusercontent.com/24485362/32857373-3b8256ee-ca0d-11e7-9964-0b2b1097d286.gif)

**Edit** Trying to open file on remote server via Nemo. (without terminal)
![peek 2017-11-15 14-03](https://user-images.githubusercontent.com/24485362/32857581-dd4cdf26-ca0d-11e7-9ca7-c6efd2d546e7.gif)

 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34770
