### ISSUE TITLE
Code Helper

### ISSUE THREAD

**Issue by macasas** [Microsoft/vscode#38447]
Every time I copy and paste a small block of code I now have to wait 5 to 10 seconds for something called Code Helper to go up to 100+ CPU and then back down again.

While its doing this, I am unable to do anything else except wait.

Yesterday I liked Visual Code

Today, after their improvements??? it is a disaster.

Adding 100s of breakpoints on its own and timing out due to 
Unable to fold code anymore
And now locking itself up.

I've done a reboot, same problem each time.

![screen shot 2017-11-15 at 20 28 44](https://user-images.githubusercontent.com/910082/32856873-647d5e16-ca46-11e7-9b69-6b4d46e51134.png)

**Comment by roblourens** [comment]
Does it repro if you launch with the `--disable-extensions` flag? Can you look up the command line args of that process? Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues and include as many details as possible.
