### ISSUE TITLE
Terminal font completely different than in the editor

### ISSUE THREAD

**Issue by gonssal** [Microsoft/vscode#38448]
As requested in #35991, creating a new issue.

- VSCode Version: 1.18.0
- OS Version: (K)Ubuntu 17.10

Steps to Reproduce:

1. Set editor.fontFamily to "Verdana".
2. Open terminal
3. Look at each letter using half the screen.

Reproduces without extensions: Yes

![vscode-terminal](https://user-images.githubusercontent.com/1172272/32857188-540f2ff4-ca47-11e7-931d-e10a5aa42c83.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681
