### ISSUE TITLE
HTML formatting removes double space after sentence

### ISSUE THREAD

**Issue by freeman-g** [Microsoft/vscode#38446]
- VSCode Version:  1.18.0
- OS Version:  Windows 10

Steps to Reproduce:

1.  Create a simple HTML file like this:
```
<div>This is a sentence.  This is another sentence</div>
```
2.  Hit Shift-Alt-F to format the file

Result - the double space after the first sentence is removed and replaced with a single space.
```
<div>This is a sentence. This is another sentence</div>
```

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Isn't that the point of a formatter, removing unnecessary whitespace?
You can define which element content's must not be changed by adding that element to `"html.format.contentUnformatted".

**Comment by freeman-g** [comment]
Ok - thank you...after researching this further, I see that the double space is not really required after punctuation marks.  My generation was taught that double space after a period was proper typography, which is why I was thinking this was a bug.
