### ISSUE TITLE
Error when building VSCode on Windows

### ISSUE THREAD

**Issue by Calinou** [Microsoft/vscode#38458]
I'm using VSCode commit https://github.com/Microsoft/vscode/commit/f7bb5573e106dff75d694a124d9545b17eefe9e1 and Node.js 9.2.0 to build for Windows.

`scripts\npm install` runs sucessfully, but `gulp vscode-win32-x64-min` or `gulp vscode-win32-ia32-min` return this error:

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TLSWrap.onread (net.js:619:25)
```

This seems to happen on the `vscode-win32-x64-min` task itself, after the optimization and minification is performed.

**Comment by joaomoreno** [comment]
Try again.

**Comment by Calinou** [comment]
It works, thanks 😄
