### ISSUE TITLE
Minor localization issue

### ISSUE THREAD

**Issue by F0RIS** [Microsoft/vscode#38456]
- VSCode Version: 1.18.0
- OS Version: Win 7x64 SP1

Steps to Reproduce:

1. Open "File" menu in main menu

Just redundant space here for russian localization:

![image](https://user-images.githubusercontent.com/10178982/32865416-b401e2f2-ca6b-11e7-9acd-6c3d68b7251b.png)

**Comment by roblourens** [comment]
What do you mean "redundant space"? Our translations come through Transifex, you could improve it there: https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project
