### ISSUE TITLE
Some npm tasks are not detected

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#38452]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.4
Gradle|caz|1.1.2
javadebugger|don|0.1.5
xml|Dot|1.9.2
tslint|eg2|1.0.21
LogFileHighlighter|emi|1.2.0
vscode-great-icons|emm|2.1.20
tortoise-svn|fan|0.1.1
vscode-guid|hea|1.3.1
docthis|joe|0.6.0
svn-scm|joh|0.10.0
vscode-simple-icons|Lau|1.7.1
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
material-icon-theme|PKi|3.0.0
seti-icons|qin|0.1.3
java|red|0.14.0
vscode-icons|rob|7.18.1
final-newline|sam|0.3.2
jenkinsfile-support|sec|0.1.0
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:

1. I have package.json as follows:

```
{
  "name": "touch-core",
  "version": "13.1.0",
  "description": "StayinFront Touch Core",
  "main": "./core/core.js",
  "scripts": {
    "core": "gulp tsc-core",
    "build": "npm install && gulp build-Debug && gulp build-Release && gulp build-all",
    "watch": "npm install && gulp default-no-resources"
  },
  ...
}
```

2. I have tasks.json as follows (autogenerated):

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "core",
			"problemMatcher": []
		}
	]
}
```

3. I do "ctrl-shift-b" to run a task, the tasks dropdown only shows the "build" and "watch" tasks for "npm". It does not show the "core" task"

![image](https://user-images.githubusercontent.com/314188/32860191-c0576ed8-cab5-11e7-93d8-a6e88ab629df.png)

Reproduces when the "tasks.json" file is deleted: Yes

Also, I ran "configure task" to generate the "tasks.json" file, with following results:

Select "configure task":
![image](https://user-images.githubusercontent.com/314188/32860393-5edaa430-cab6-11e7-8ca4-3f2b90802cf5.png)

From the list, note that "core" is in the options for "npm":
![image](https://user-images.githubusercontent.com/314188/32860466-8ce01202-cab6-11e7-84de-55bb2ebe560a.png)

The generated tasks.json is as pasted above, but it made no difference either way.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Core is not a build task. User Task > Run Task. This will list the core task.

**Comment by gwynjudd** [comment]
@dbaeumer thanks, I guess that wasn't clear from the documentation. Can you explain how it decides what is a build task, and what is a "not build" task?

**Comment by dbaeumer** [comment]
We do a name match for common building names like 'build', 'watch', 'compile'. If you use non standard names you can mark a task belonging to the build group using the group property.
