### ISSUE TITLE
Feature: dynamically importing ES modules - open file under cursor

### ISSUE THREAD

**Issue by webmarkelov** [Microsoft/vscode#38454]
- VSCode Version: 1.18.0

Steps to Reproduce:

```js
const contentRenderer = () => import('./Renderers/ContentRenderer.vue');
```

**Comment by mjbvz** [comment]
We already support `go to definition` for js/ts import paths

This does not work for .vue files due to https://github.com/Microsoft/TypeScript/issues/19018 / https://github.com/Microsoft/TypeScript/issues/10939

Closing as duplicate / upstream
