### ISSUE TITLE
[bat] improve highlighting after echo

### ISSUE THREAD

**Issue by Isenlia** [Microsoft/vscode#3845]
It's not a huge issue but I'd just like to point out that the editor doesn't quite handle batch right
as it puts help in the same colour as echo and me in white when they should be green for output text

![screenshot from 2016-03-08 08 29 56](https://cloud.githubusercontent.com/assets/17724510/13603036/625f6dc4-e508-11e5-897d-69d5f705f789.png)

this can be fixed by adding quotation marks but of course the resulting output of the file would contain the quotation marks
![screenshot from 2016-03-08 08 32 58](https://cloud.githubusercontent.com/assets/17724510/13603038/62b49ea2-e508-11e5-9bce-93b7e866b74e.png)
![screenshot from 2016-03-08 08 35 30](https://cloud.githubusercontent.com/assets/17724510/13603095/c3ee5d3e-e508-11e5-80c4-297e31e215d0.png)
of course leaving the marks out causes no issue in executing but none the less they are being coloured wrong

**Comment by adamralph** [comment]
Another example:

![image](https://user-images.githubusercontent.com/677704/32717476-add65320-c851-11e7-9071-dc74f2f3d846.png)

The word "for" should not be highlighted.

**Comment by adamralph** [comment]
Related: https://github.com/Microsoft/vscode/issues/38206

**Comment by adamralph** [comment]
🎉
