### ISSUE TITLE
[html] Follow Link in Multi Root Workspace

### ISSUE THREAD

**Issue by nicocevallos** [Microsoft/vscode#38469]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063

---
Into a HTML file, if I add the "base" tag pointing to "/" it should refer to the current root workspace instead the first folder in the folder arrays of the configuration file.

Using a Workspace Configuration File like this:
![image](https://user-images.githubusercontent.com/10197397/32872143-eb360594-ca63-11e7-831c-19e77074efdb.png)

And having file distribution and a HTML file like this:
![image](https://user-images.githubusercontent.com/10197397/32872185-27935294-ca64-11e7-9300-a36a1cba9233.png)

Step 1: Follow the link to "manifest.json" file (Ctrl + Click)

Expected Result:
Open the file using the Root Workspace where the HTML file is placed (folder A).

Actual Result:
VS Code tries to open the file using the first Root Workspace folder in the list (folder B), and show the following error message:
![image](https://user-images.githubusercontent.com/10197397/32872229-660d9bd8-ca64-11e7-851c-8531666056b1.png)

**Comment by bpasero** [comment]
@nicocevallos I cannot reproduce this issue, for me it goes to the correct folder. Do you have any extensions installed? Does it reproduce if you run "code --disable-extensions"?

**Comment by nicocevallos** [comment]
I reproduced the issue without extensions before to report the issue.
Could you share the Workspace Configuration File and the HTML file you are using to reproduce it?
Please take into account my Workspace Configuration File has the folders in a no alphabetical order  and the HTML file has the <base> tag, without the tag it is not reproducible.

**Comment by bpasero** [comment]
@nicocevallos I tried with that exact setup, I cannot reproduce, sorry.

**Comment by nicocevallos** [comment]
Hi @bpasero 
I took another computer, and I could reproduce the issue following the same steps I described.
Please try opening the "test.code-workspace" file into the following zip file.
[test.zip](https://github.com/Microsoft/vscode/files/1486405/test.zip)

**Comment by bpasero** [comment]
Ok I can reproduce. It looks to me like an issue from the link provider (HTML).

**Comment by nicocevallos** [comment]
Thanks guys!

**Comment by roblourens** [comment]
Insiders:

![image](https://user-images.githubusercontent.com/323878/33688528-8b3bbfe8-da90-11e7-8a9a-172684778f37.png)
