### ISSUE TITLE
{ "when": "$(basename).ts" } is case sensitive on Windows

### ISSUE THREAD

**Issue by rjamesnw** [Microsoft/vscode#38462]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
markdown-preview-github-styles|bie|0.1.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
git-extension-pack|don|0.1.3
githistory|don|0.2.3
gitlens|eam|6.1.0
tslint|eg2|1.0.21
prettier-vscode|esb|0.24.0
json2ts|Gre|0.0.6
vscode-git-tags|how|1.1.2
vscode-nuget-package-manager|jmr|1.1.4
ts-extension-pack|loi|0.0.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0
typescript-javascript-grammar|ms-|0.0.24
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.5.0
debugger-for-edge|msj|0.4.1
tsimporter|pmn|1.2.14
typescript-hero|rbb|1.7.0
move-ts|str|1.5.0
vscode-open-in-github|ziy|1.3.0
---

I have the following config: 

```
  "files.exclude": {
    "**/*.js": { "when": "$(basename).ts" },
    "**/*.js.map": true
  }
```

And it seems to be case-sensitive on Windows.  Thus, I have class files like "MyClass.ts" compiled by `tsc` to `myclass.js` which breaks the file exclusion.  This makes me have to resort to using `"**/*.js": true`, which is not ideal, but works for now.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10633

**Comment by rjamesnw** [comment]
Ah, I was looking for it and didn’t know what to call it! lol ;) Thanks, “glob searching”, got it.
