### ISSUE TITLE
The text shown in the terminal tab cannot align correctly

### ISSUE THREAD

**Issue by EnoroF** [Microsoft/vscode#38468]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
shader-toy|ste|0.4.0

---

Steps to Reproduce:

1. the text shown in the terminal tab cannot align correctly. Eg. They are separated into many pieces and in different lines. 

Looks like this.
Windows PowerShell
版权所有 (C) 2016 Microso
<Space> ....................................ft Corporation。保留所有权利。
<Space> ....................................c:\User\Doc<Space> ....
ument\>

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Please provide a screenshot of the issue.
