### ISSUE TITLE
[css] improve "unknown property" error message

### ISSUE THREAD

**Issue by cdswyda** [Microsoft/vscode#38460]
- VSCode Version: **1.18.0**
- OS Version: **Windows 10 x64**

Steps to Reproduce:

1. In a css file
2. Such as `word-break` and `word-wrap`

![image](https://user-images.githubusercontent.com/13060680/32868258-430319c2-caac-11e7-834b-3a6cdc550ef1.png)

Reproduces without extensions: Yes

I disabled all extensions, the question remains.

**Comment by aeschli** [comment]
Can you paste the code snippet that reproduces the issue? This works for me, `word-break`, `word-wrap` are both supported.
![image](https://user-images.githubusercontent.com/6461412/32941461-25a4dbb0-cb86-11e7-9d19-92113fcfadac.png)

**Comment by cdswyda** [comment]
Thank you very much.

I find the cause about that:  before the css property, the chars is not four spaces or one tab, it is two `12288` (unicode).

The code snippet : 

```css
.mini-outputtext {
　　word-break: break-all;

　　word-wrap: break-word;
}
```

Maybe the '12288' and the css property are taken as one property.

**Comment by cdswyda** [comment]
It is not linter's problem, but think the tips can be more specific.

**Comment by aeschli** [comment]
Yes, in CSS only LF, CR, TAB and space are whitespace characters.
I'll improve the error message to include the full invalid name. This should make it clear.

**Comment by sandy081** [comment]
@aeschli Do you think it makes sense to also say why in the message as you said in previous comment?

**Comment by aeschli** [comment]
I don't not why a property doesn't exists. There are some strange Unicode in the text, so that's a hint, but the characters are not invalid.
