### ISSUE TITLE
"Property editorOverviewRuler.findMatchForeground: is not allowed."

### ISSUE THREAD

**Issue by mliq** [Microsoft/vscode#38465]
- VSCode Version: 1.18.0
- OS Version: 10.12.6

Steps to Reproduce:

1. open User Settings (`cmd+,`)
2. The following line is underlined and shows in Problems window with message "Property editorOverviewRuler.findMatchForeground: is not allowed.":
```"editorOverviewRuler.findMatchForeground:": "#FFFFFF",```

Reproduces without extensions: Yes

I haven't changed my `"workbench.colorCustomizations"` object in months, and formerly there were no warnings.

**Comment by usernamehw** [comment]
@mliq you have extra colon `:` at the end

**Comment by mliq** [comment]
thanks @usernamehw
