### ISSUE TITLE
Code predictions don't work properly with Unity 3D

### ISSUE THREAD

**Issue by mitesh504** [Microsoft/vscode#3846]
Problems in auto code completion and code prediction.
I am using VSCode for small projects but I tried to use it with Unity 3D.
But the code prediction don't work properly.

**Comment by nixbb** [comment]
The [Visual Studio Code and Unity](https://code.visualstudio.com/Docs/runtimes/unity) post details methods of using VSCode as a functional IDE for Unity 3D.

There is also an extension available in the marketplace that can help with getting the debugger working.
https://marketplace.visualstudio.com/search?term=unity3d&target=VSCode&sortBy=Relevance

**Comment by mitesh504** [comment]
Hey ,
Thanks I'll check that out.
