### ISSUE TITLE
如何关闭鼠标悬浮 css 属性的提示

### ISSUE THREAD

**Issue by varxzy** [Microsoft/vscode#38467]
![image](https://user-images.githubusercontent.com/20296852/32871809-3b4f4b76-cabe-11e7-83d8-82e5cd9fd9fc.png)

怎么关闭这个 css 属性的悬浮提示，神烦！！！
我都会敲代码了，用得着你提示吗，多事~😒

**Comment by roblourens** [comment]
Please file issues in English, I think google translate is missing something.
