### ISSUE TITLE
Discord not picking up visual studio code window for screen sharing

### ISSUE THREAD

**Issue by IkeKap** [Microsoft/vscode#38461]
- VSCode Version: 1.18
- OS Version: windows 10 autumn creators
Discord latest version

Steps to Reproduce:

1. open up a video call within discord
2. when clicking share screen (specific window mode), instead of showing a window on the code, it only shows a black screen. 

Reproduces without extensions: Yes

**Comment by IkeKap** [comment]
![image](https://user-images.githubusercontent.com/24295451/32869717-81a802b6-ca46-11e7-8c8b-d06d768c9e2e.png)

**Comment by IkeKap** [comment]
visual studio code windows is on the right (left window is unrelated to bug). might be an issue on discord's end but it is possible that it can be rectified on VSC's end

**Comment by bpasero** [comment]
I suggest you report this to them, we are not planning to look into it. You might be lucky that "code --disable-gpu" fixes it.
