### ISSUE TITLE
c/cpp function navigation issues

### ISSUE THREAD

**Issue by lianzisong** [Microsoft/vscode#38463]
- VSCode Version: 1.18
- OS Version: win 10

Steps to Reproduce:

1.  open the folders through the vscode
2. press the alt+N ,then check the result.
the cpp file navigation result :
![image](https://user-images.githubusercontent.com/16344340/32871048-d21f7512-cab9-11e7-8783-6b920f621495.png)

and the H file navtigation result:
![image](https://user-images.githubusercontent.com/16344340/32871068-eb99f828-cab9-11e7-8fac-2a9e68e75506.png)

but not all the result is the same.  some cpp may be OK.
![image](https://user-images.githubusercontent.com/16344340/32871105-1afdb3fc-caba-11e7-9f27-059e34e08c97.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I think this is a feature of the c++ extension, right? Please open an issue on their repo.
