### ISSUE TITLE
Feature Request:  Have a keyboard shortcut and toggle making the code comments transparent

### ISSUE THREAD

**Issue by halukkaramete** [Microsoft/vscode#38474]
For those people who write plenty of comment, it becomes sometimes to difficult to follow the code. 
Those comments are life saver but only when you need it to. 

I would love to have a feature to turn off all comments from showing
Since themes already know how to color code the comments, I think it would be no issue to turn them transparent in the current given theme. 

And with a quick keyboard shortcut, you can come back to the editing environment again.

**Comment by alexandrudima** [comment]
@halukkaramete you can customize any theme via user settings.

e.g.
```
"editor.tokenColorCustomizations": {
	"comments": "#FF000000"
},
```

You can easily write an extension that uses vscode API to toggle this specific setting.

**Comment by halukkaramete** [comment]
Thank you for the tip. I will integrate this into the API which I was not aware of earlier, which means you now have opened up a new territory of fun to get into. Thanks for that. 

I still think that having an editor level capability where all users can toggle this on/off with a shortcut toggle or a little button to click to toggle would be appreciated.
