### ISSUE TITLE
gutter color scheme is not intuitive

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#38471]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

These line indicators
![screen shot 2017-11-15 at 8 00 04 pm](https://user-images.githubusercontent.com/226872/32873207-af43a092-ca3f-11e7-88c5-ee8e624fa7fa.png)
are great, but the color scheme is pretty weird. As far as I can tell,
* A removed line is marked with red. Makes sense. 
* An added line is marked with green. Ok, I'm getting the picture now. These are the colors that anyone who has ever used git or any other version control system expects. Oh, and they match the color scheme that the file tree on the left-hand side of the editor. Got it.
* A modified line is marked with.... blue. Wuuuuuut?

Why not do something like the gutter in Atom instead?
![screen shot 2017-11-15 at 8 07 05 pm](https://user-images.githubusercontent.com/226872/32873464-15d591e8-ca41-11e7-9303-961ef136a987.png)

**Comment by roblourens** [comment]
You can customize those colors with

```
"workbench.colorCustomizations": {
        "editorGutter.addedBackground": "#ff0000"
},
```

**Comment by samuela** [comment]
@roblourens Ah, that's great to know. Could we get better defaults though?

**Comment by joaomoreno** [comment]
There are many themes that we ship. There are also many themes in the Marketplace. Use the one which you like best.

**Comment by samuela** [comment]
@joaomoreno Sure, having multiple themes is great and all. I can certainly customize the editor to my liking all day long, but the issue here precisely _is_ that the default theme that ships is confusing and should be adjusted. It's simply not consistent with any other VCS color scheme. It's not even self-consistent within the editor: the file tree uses a totally different color scheme than the gutter.

**Comment by joaomoreno** [comment]
cc @jrieken about the file tree
