### ISSUE TITLE
Code formatting does not obey editor.insertSpaces

### ISSUE THREAD

**Issue by nixbb** [Microsoft/vscode#3847]
It seems that the code formatter does not adhere to the indentation mode specified in the user settings.

Here's a simple example using version 0.10.10
In this case "editor.insertSpaces" is set to "auto" but this issue also manifests if it's set to false.
![codeformattingbug](https://cloud.githubusercontent.com/assets/958979/13603388/929fa584-e545-11e5-9009-8b55a45481d9.gif)

The example shows that all the indentation starts off as tabs.
The newly added line (line 11) is also indented using tabs.
When the statement is finished with a semicolon the current line and the next line is then indented with spaces.

Not shown in the gif is that an undo will revert line 11 and 12 to tabs instead of spaces.

Hope this helps narrow down the issue.

**Comment by alexandrudima** [comment]
fyi @jrieken @dbaeumer

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#93
