### ISSUE TITLE
This is a feature suggestion. 

### ISSUE THREAD

**Issue by halukkaramete** [Microsoft/vscode#38470]
- VSCode Version: All Versions
- OS Version:  All OS

Steps to Reproduce:

1. Any given time. 
2. currenty, when I do command+ or command-, I get the font size up and down. That's great. Most of the time, I want only the code font to get larger. In fact, I would wish the terminal and the project explorer sidenav on the left gets smaller as I do command+, if you know what I mean. This is all about creating a comfortble but at the same time a functional environment. My suggestion is make command+ and command- be context sensitive. If I click on the terminal, and do command-, the terminal font should get smaller, and if I click on the editor and then do command+, only the code window font should get bigger. This way, everyone can have a chance to create that perfect environment. 

Reproduces without extensions: Yes/No

**Comment by halukkaramete** [comment]
Where is the feature suggestion form here?

**Comment by octref** [comment]
You can change `editor.fontSize` which only affects font size in editor area but not other UI.
