### ISSUE TITLE
The cursor keeps jumping to the bottom

### ISSUE THREAD

**Issue by matthewfcarlson** [Microsoft/vscode#38479]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-npm-script|eg2|0.3.3
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.67
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
java|red|0.14.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Edit a go document
2. Stop typing for a second
3. Cursor focus goes to the end of the document

Reproduces without extensions: Yes/No

**Comment by matthewfcarlson** [comment]
Looks like it's a result of go-code-check running.

**Comment by Ripper1992** [comment]
Same thing is happening with me.

Steps to reproduce the error:

1 - Type some code.
2 - Hit "ctrl +s" to save the file.
3 - Hit arrow up or down.
4 - Cursor focus at the bottom

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1349

**Comment by ramya-rao-a** [comment]
I believe the root cause is in the core and not the extension. Logged #38728
