### ISSUE TITLE
Font rendering issue in all panels

### ISSUE THREAD

**Issue by animeshb** [Microsoft/vscode#38477]
I have noticed this issue with one of the 1.17.x versions earlier last month. I figured this will just go away after updating to the next version automatically. However, the issue still persists. Noto Mono (replacement for Droid Sans Mono on Debian) was the font set in user settings when I first noticed this issue. I changed it to a few other fonts and could reproduce it with them as well. I have also noticed that the issue is less prominent on certain color themes which have italics or bold characters. Also, this is reproducible for all font sizes.

![screenshot from 2017-11-13 23-57-56](https://user-images.githubusercontent.com/1550696/32742996-17e4efd6-c8d1-11e7-81f3-924caa04738f.png)

Font on the screenshot is plain `monospace`. Similar behavior can be noticed with other themes as mentioned. In case, it is not clear what I mean, check the lines 16, 19, 23 or near the import keyword at the top.

The only warning that is showing up in the dev console is shown in the screenshot.

- VSCode Version: 1.18.0
- OS Version: Debian Buster

Steps to Reproduce:

1. Open VS Code
2. See strange characters in editor, terminal, file list

Reproduces without extensions: Yes

Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T12:44:48.751Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/35675
