### ISSUE TITLE
Maximize panel size and restore panel Size 

### ISSUE THREAD

**Issue by anks333** [Microsoft/vscode#38473]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Move the terminal to Right(Vertical align) 
2. Click on panel maximise and restore button
3. You will notice maximise and restore button is not working properly 

Reproduces without extensions: No

**Comment by isidorn** [comment]
Works with latest insiders.
Please try it vscode insiders and if you can still reproduce let me know and I will reopen this issue.
Also please provide a video which ilustratest this.

https://code.visualstudio.com/insiders/

**Comment by anks333** [comment]
probably it was happening because of some extension, now its working fine, Thanks
