### ISSUE TITLE
Feature Request: Have a current page function list show on the right side

### ISSUE THREAD

**Issue by halukkaramete** [Microsoft/vscode#38475]
Feature Request: The right-side-view showing the entire page view visually is great. But.. it would be also nice to put that section on steroids and toggle between displaying a list of functions currently defined on the page.  This way, the developer can just turn that view on, list functions alphabetically, goto the one he wanted to go straight, with no typing. And additional icon next to the function can also fire up the "references" window for that function.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
