### ISSUE TITLE
Can't use Fixedsys Excelsior 3.01 font on Mac

### ISSUE THREAD

**Issue by pistacchio** [Microsoft/vscode#38485]
- VSCode Version:  1.18.0 
- OS Version: MacOS 10.12.6 

Steps to Reproduce:

1. Install the font Fixedsys Excelsior 3.01  (http://www.fixedsysexcelsior.com/)
2. Se the font in User Settings ("editor.fontFamily": "Fixedsys Excelsior 3.01")
3. Save the file
4. The font is a generic serif font (Times New Roman, I think)

![schermata 2017-11-16 alle 09 38 14](https://user-images.githubusercontent.com/192145/32881559-ece9b8e2-cab1-11e7-8078-b4fe0870ac87.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Are you sure it's installed properly, and the name is correct? Maybe try restarting vscode after the font is installed?

**Comment by pistacchio** [comment]
@roblourens Hi, thanks for the interest. Yes, the font is installed correctly and the name is right as I'm able to use that font font that name in Atom. Restarting Code doesn't solve the issue.

**Comment by roblourens** [comment]
I can repro. This is a good one. Looks like the font family needs to be quoted if it contains words that aren't valid css identifiers: https://stackoverflow.com/questions/8951584/assigning-a-css-fontfamily-ending-with-a-number

@rebornix It works for me in vscode if I quote the font-family in devtools like `font-family: "Fixedsys Excelsior 3.01"`

**Comment by pistacchio** [comment]
@robertohuertasm Wow, Roberto, I could have never figured it out. That worked, thank you :)

**Comment by rebornix** [comment]
@roblourens thanks for the investigation, a good bug.

**Comment by roblourens** [comment]
Can we just split on comma, then wrap in quotes?
