### ISSUE TITLE
Function breakpoints are sent to adapter even if debug adapter does not support them

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3848]

**Comment by felixfbecker** [comment]
Is it possible to push this in a bugfix release before March release?

**Comment by isidorn** [comment]
We'll it is already pushed, it will be release in the next insider release which will be out soon I believe.
I do not think we will make a next stable release before the March one.

Sorry if we broke your behavior. This is the reason why we have insider releases, so we can potentially find fixes for the stable release, however this one came in too late.
