### ISSUE TITLE
Documentation: CLI usage not updated

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#38486]
At https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders the documentation reads:

> Name of a folder to open. **You can specify multiple folders and there will be an instance for each folder.**

However, when doing so on 1.18, all supplied folders are opened into a single window, in a shared workspace.

I was originally searching for how to control this behavior, as the documented behavior is how it *used* to work.

**Comment by bpasero** [comment]
Moved to https://github.com/Microsoft/vscode-docs/issues/1264
