### ISSUE TITLE
Tab alignment error when typing korean

### ISSUE THREAD

**Issue by gwobbler** [Microsoft/vscode#38482]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vba|spe|1.0.17

---

Steps to Reproduce:
![screenshot_20171116_170759_001](https://user-images.githubusercontent.com/1875278/32880450-07a25682-caf1-11e7-87fc-2d5415768e61.png)

1. type korean language
- sample text
집 버프					: 90000145
펭귄바 버프					: 97000011

2. use tab for line sort
3. When indented with tabs, there may be a gap of one or more space.

korean has a width corresponding to two letters in English, and spaces are the same as korean characters.
I wonder if this is related to the problem.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
