### ISSUE TITLE
Download page doesn't show windows 64 bits edition

### ISSUE THREAD

**Issue by marcelloh** [Microsoft/vscode#38480]
https://code.visualstudio.com/Download

**Comment by Daylien** [comment]
This is the download link for the x64 version. 
https://go.microsoft.com/fwlink/?Linkid=852157
But cannot see what you mean. The download button on the [website ](https://code.visualstudio.com/Download)is for the x64 version.

**Comment by marcelloh** [comment]
Oh? I was reading ".zip | 32 bit versions" under that "button", so I assumed when clicking the logo, it would bring me to an overview of downloads with zip & 32 bit versions.

It is still unclear that the "button" gives me a 64 bit version. But of course, I could have guessed it.
_(But I hardly ever click a link where I have to guess its destination.)_
