### ISSUE TITLE
Create a global extension list

### ISSUE THREAD

**Issue by Dmytraw** [Microsoft/vscode#38488]
Hey!

This is not an issue actually, more like a proposal.

Example:
I have a home machine where I have VS Code with several plugins that I always use. At work I have another machine with VS Code installed. And I have to install those plugins again.

It would be great to have an (optional) account with login/password which will store a list of extensions somewhere and when I install VSC to a new machine all extensions will be installed automatically. When installing a new extension you could introduce an option like 'Store to extension pull' or 'Try without adding' in case a user wants to play around with it and not to store it in extensions list.

**Comment by roblourens** [comment]
This is discussed in this issue and some of the linked issues: https://github.com/Microsoft/vscode/issues/2743

The CLI options `--list-extensions` and `--install-extension` can be useful for installing a bunch of extensions at once.
