### ISSUE TITLE
Improve task configuration/creation

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3849]
- Command: Configure Task Runner
- Show Quick Box
  - Gulp (auto detect if possible)
  - Grunt
  - Jake
  - TypeScript compile
  - TypeScript specific file
  - TypeScript watch
  - msbuild
  - Dot net build
  - Generic Command (see below)
- Insert hard coded template (if not auto detected) based on the user selection
- Templates have a fwlink to the task.json documentation

`Generic template`
```
{
   // See http://go.microsoft.com/fwlink/?LinkId=733558
   // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "A Command",  // specify the command to run
    "args": [
    ],
    "showOutput": "silent"
}
```

**Comment by felixfbecker** [comment]
An npm scripts template would be nice to, as this has been asked here a couple of times and is used very often by projects. It is very simple, basically `"command": "npm", "args": ["run"]`, but new users don't know what to do.

**Comment by dbaeumer** [comment]
Done :-)

**Comment by dbaeumer** [comment]
@egamma can you please verify.

**Comment by egamma** [comment]
verified - but I would have expected that the scripts are also detected as tasks targets.

My test case was the following package.json
```json
{
  "name": "projections",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "build": "webpack --config webpack.config.js",
    "dev": "webpack-dev-server --config webpack.config.js --open"
  },
  "author": "waderyan",
  "license": "ISC",
...
```
