### ISSUE TITLE
new .vscode/launch.json does not respect value of "files.eol"

### ISSUE THREAD

**Issue by jorgenpersson** [Microsoft/vscode#38496]
- VSCode Version: 
```
$ code --version
1.18.0
dcee2202709a4f223185514b9275aa4229841aa7
```
- OS Version: Win10

Steps to Reproduce:

1. Start a new instance of git-bash.exe

2. In it bash terminal:
```
mkdir eoltest
cd eoltest
code .
```

3. In code:

- Open `Settings`
- Search for `eol`
- Verify that `files.eol` has value `\r\n`
- Add a new configuration and save the file

4. In it bash terminal execute grep command. Should produce output for all lines containing `\r`
`grep -U $'\015' .vscode/launch.json`

5. To validate the above command, convert the file to use windows line endings and run it again
```
unix2dos.exe .vscode/launch.json
grep -U $'\015' .vscode/launch.json
```

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@sandy081 assigning to you for config, may be debug-specific though.

**Comment by sandy081** [comment]
@isidorn I assume you are not using configuration service to write debug stuff. Hence assigning to you.

**Comment by isidorn** [comment]
I acknowledge the bug, here a code pointer in case some user is passionate about fixing it
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L541
