### ISSUE TITLE
Emmet expand is slow

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#38493]
- VSCode Version: 1.18
- OS Version: Arch

Steps to Reproduce:

1. Try expand

Reproduces without extensions: No

I have test it in .scss and .vue files.
![vokoscreen-2017-11-16_12-40-52](https://user-images.githubusercontent.com/11390039/32884558-cfb048a8-cacb-11e7-9bc2-70f97c2501c1.gif)

**Comment by ramya-rao-a** [comment]
@edDimensi I dont see what the issue is.
In your gif, the speed looks fine.

**Comment by edDimensi** [comment]
i have all time that bug. Then i press fz20 + tab, and it expand to `font-size: 2px`, all need press ctrl + z, and tab this again.

**Comment by ramya-rao-a** [comment]
So what you are saying is that `tab` doesnt expand the abbreivation after `ctrl+z` ?

The first time you press tab, the emmet expansion from the auto-completion list is selected.
When you press `ctrl+z`, there is no auto-completion list. And so tab does nothing.

Workaround is to either press `ctrl+space` to trigger auto-completion or add the setting `"emmet.triggerExpansionOnTab": true`.

Please also read the [Emmet Docs](https://code.visualstudio.com/docs/editor/emmet)

**Comment by edDimensi** [comment]
nope, i talk aboult slow speed working of new emmet.

**Comment by ramya-rao-a** [comment]
> Then i press fz20 + tab, and it expand to font-size: 2px, all need press ctrl + z, and tab this again.

Sorry, I am finding it hard to understand the issue here
Are you saying that the first time `fz20` expands fine, but after pressing ctrl+z and tab again it is slow?

- Is emmet slow all the time or only after pressing tab ->  ctrl+z -> tab again
- Is emmet slow even when you run vscode after disabling extensions? i.e Run `code --disable-extensions` and try emmet
- Is emmet slow in all files or only large files? Can you try in a small file?

**Comment by edDimensi** [comment]
On first time fz20 expand to `font-size: 2px;` it's not fine, after pressing ctrl + z and tab again it return fine result.
Emmet slow with extensions. I test it in .vue files and .scss fies.
Without extensions it's work's fine.

**Comment by ramya-rao-a** [comment]
Are you saying that the auto-completion list is slow to show up the first time?
