### ISSUE TITLE
[js] syntax highlighting broken in 0.10.10

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/vscode#3850]
Tested on Windows 10
![vscode-js-coloring](https://cloud.githubusercontent.com/assets/3028012/13605001/28748f7c-e54e-11e5-8abb-2354f71ff2c8.png)

**Comment by tstpierre** [comment]
Duplicate of #3825

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/3903
