### ISSUE TITLE
Auto import is not inserted in a new line when used with flow.

### ISSUE THREAD

**Issue by labidik** [Microsoft/vscode#38503]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. make sure your last import line is a type-import, e.g.:
`import { Observable } from 'rxjs/Observable';`
`import type { AppStore } from '../index';`

2. write a statement requiring an auto import:
`streamStuff(param);`

3. the new import(auto import) will be inserted in the middle of the last import, after the keyword _type_:
`import typeimport { streamStuff } from '../stuff';
 { AppStore } from '../index';`

**Comment by mjbvz** [comment]
Yes we don't support flow out of the box. If you are working in flow, try disabling this feature by setting: `"typescript.autoImportSuggestions.enabled": false`
