### ISSUE TITLE
Code Relevance

### ISSUE THREAD

**Issue by Geeprox** [Microsoft/vscode#38504]
- VSCode Version: 1.18.0
- OS Version: Windows

When I open a Project, I can't use "jump to caller", "jump to reference" or "jump to defination" if they are in a file not opened. Only if I open the destination file can I do these operations. It's very unfriendly for reading code.
I hope I can sync all the project forced in the background.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@Geeprox what language are the files?

**Comment by Geeprox** [comment]
Python and Java.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
