### ISSUE TITLE
Terminal pane focus on click

### ISSUE THREAD

**Issue by joum** [Microsoft/vscode#38502]
- VSCode Version:  1.18.0 (1.18.0) dcee2202709a4f223185514b9275aa4229841aa7
- OS Version: 10.13.1 (17B48)

I don't think this is actually a bug, just a small improvement on UX.

If you are working on a VSCode window that has the integrated terminal visible and change focus to another app window, if you try to return to VSCode's integrated terminal by clicking on it, it will set the focus to the editor if it was the last selected pane before VSCode lost focus the first time.

By other words, focus is returned in the VSCode app to the last used pane, instead of the one you actually click, ie, the integrated terminal.

It would be nice if the clicked pane became the selected one when window focus was returned to VSCode by clicking.

**Comment by joum** [comment]
I've been reading a bit on the issue queue regarding this focus behaviour, and I guess it became the adopted default behaviour when returning focus to VSCode's app window. 

While I understand that this might not be of interest to everyone, I think it would be nice and useful to maybe have a `returnFocusToClickedPane` setting that could override this default behaviour.

I have no idea on how to implement it, though! :)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/24634
