### ISSUE TITLE
Could we have explorer.autoReveal to sidebar with key binding ?

### ISSUE THREAD

**Issue by fankangsong** [Microsoft/vscode#38508]
- VSCode Version:1.18.0
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@fankangsong you mean to flip the auto reveal setting or to reveal the currently active file in sidebar?

**Comment by fankangsong** [comment]
@bpasero yes, that what I mean.

**Comment by bpasero** [comment]
@fankangsong that would be: `workbench.files.action.showActiveFileInExplorer`
