### ISSUE TITLE
Add sorting branches for git checkout feature

### ISSUE THREAD

**Issue by dmyger** [Microsoft/vscode#38507]
Could you add a simple _sorting_ feature to let easy navigation in the list of branches.
It's very simple suggestion just put a few words in the file
`code/resources/app/extensions/git/out/git.js` in function `getRefs()`:
you have to need change a line _800:_ `const result = yield this.run(['for-each-ref', '--format', '%(refname) %(objectname)']);` by adding one more argument **`'--sort=-committerdate'`**.
It would makes back reverse sorting by date of last commit, so we get a fresh branches in the top of list.
As a future improvement it would be great to have an user settings for such option.

**Comment by joaomoreno** [comment]
Care to submit a PR?

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/38563

**Comment by bpasero** [comment]
Very useful feature 👍
