### ISSUE TITLE
JSX features like in webstorm

### ISSUE THREAD

**Issue by gilaz** [Microsoft/vscode#38505]
There are some features for JSX in Webstorm, that missed in VSCode

- auto remove the closing tag on adding "/" to the opening tag
![tag](https://i.imgur.com/nz8JU8B.gif)

- and adding `{}` on pressing `=` after prop name
![prop](https://i.imgur.com/EHUoHUq.gif)

**Comment by roblourens** [comment]
These would probably be best implemented as extensions
