### ISSUE TITLE
Allow users to rate/review extensions inside Code

### ISSUE THREAD

**Issue by DanAtkinson** [Microsoft/vscode#38511]
This is a nice-to-have but I would like to interact more with extensions without leaving Code.

I appreciate that this is probably going to be rejected because it would likely need users to authenticate to their Microsoft account from within the app, but I believe that more interaction with extension developers (such as rating or reviewing) would give them more impetus to improve upon their creations.

**Comment by fabiospampinato** [comment]
Rating a **single** extension through the marketplace only adds one or two extra clicks, but I think it would be great if users had the ability to rate extensions more easily.

Perhaps once a month or something VSC could list all the installed extensions, with stars nexts to it, and ask the user for **multiple** reviews at a time, that would be great.

**Comment by sandy081** [comment]
No plans to implement this.
