### ISSUE TITLE
[feature] Interface and type names EMOJI Support!!

### ISSUE THREAD

**Issue by hsir** [Microsoft/vscode#38515]
Since all type declarations and infos will be omitted when compiled to JS, it would be safe and great to have interface and type names with emoji support !!!

Just like this:

![2017-11-16 9 19 41](https://user-images.githubusercontent.com/5260937/32893316-a365fad6-ca9e-11e7-8068-8d7c05a5a5b2.png)

**Comment by roblourens** [comment]
This would be a feature request for the typescript project :)

**Comment by hsir** [comment]
Thank you! I've posted this issue to TypeScript project.
