### ISSUE TITLE
VSCode Freezes while working

### ISSUE THREAD

**Issue by rambhavaraju** [Microsoft/vscode#38513]
- VSCode Version: 1.18.0
- OS Version: window 10 x64
![image](https://user-images.githubusercontent.com/6705212/32892167-534af472-cafb-11e7-99d1-c32b77806cd1.png)

Steps to Reproduce:

1. VSCode IDE freezes every two mins and i get the following windows prompt on my laptop. This started happening from the vscode update which i did it this morning. 
2. It is happening when i'm writing code on my Go Project.

Reproduces without extensions: Yes

**Comment by borysl** [comment]
I have near the same issue, - version 1.18 is much slower comparatively with 1.17.2 (one with orange icon)
I have node.js project (only 8 js files)

**Comment by roblourens** [comment]
Please see the questions here to help us narrow it down: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by rambhavaraju** [comment]
Looks like i got an update today i.e. 1.18.1 and after that this issue got fixed. I will let you know if i get the same error again.
