### ISSUE TITLE
git create new branch, non valid names?

### ISSUE THREAD

**Issue by mackelito** [Microsoft/vscode#38514]
I have a question about branch names.. when I create a new branch named "TypeError: undefined is not an object (evaluating 'this.customer.customerPhones')" it get's created, all is fine.. until a windows dev tries to do a pull (I'm on mac).. now the windows devs cant pull new code.. from any branch.. ?

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a new branch with the name  "TypeError: undefined is not an object (evaluating 'this.customer.customerPhones')" (or other non allowed chars).
2. On windows.. do a pull...

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/6619073/why-cant-a-branch-name-contain-the-space-char/6619113

Creating branch names like that is just asking for trouble. It's also not a VS Code issue.

**Comment by mackelito** [comment]
I agree.. if you try to do it thru the terminal git will not allow it... so I just thougt VS Code should give the same outcome.. ?
