### ISSUE TITLE
VS code does not open files on duble click

### ISSUE THREAD

**Issue by mdzieg** [Microsoft/vscode#38517]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.13.1
PowerShell|ms-|1.5.0

---

Steps to Reproduce:

1. double click on a file
2. UI is opened with empty file, waiting coursor is displayed for a while and nothing more happens

Reproduces without extensions: Yes/No

Not very stable behaviour as one time file opens correctly, then another file from the same directory does not a senconds later. UI pops up on the screen but file does not appear. It works with drag'n'drop though. Files are not locked, no access rights stuff. It just behaves unreliably which is very annoying.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
