### ISSUE TITLE
launch configuration: support to delete variables from environment

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#38510]
In the terminal config, you can set `"foo": null` to "delete" a variable from the environment, we should support the same in launch configs for node-debugging.

The corresponding DAP change is https://github.com/Microsoft/vscode-debugadapter-node/issues/138

**Comment by weinand** [comment]
Relabeled to 'debt' since this aligns treatment of env variables with value 'null' with other parts of VS Code (integrated terminal).

**Comment by weinand** [comment]
@roblourens I've added support for this in VS Code and node-debug.

**Comment by roblourens** [comment]
`Object.keys(e).filter(v => v === null).forEach(key => delete e[key] );`

Should that line be like

`Object.keys(e).filter(k => e[k] === null).forEach(key => delete e[key] );`?

**Comment by weinand** [comment]
@roblourens oops, thanks for spotting this!
