### ISSUE TITLE
Code collapse state adheres to closed state if file opened up multiple times with collapse states

### ISSUE THREAD

**Issue by SidIcarus** [Microsoft/vscode#38527]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.6.0
- Extensions: Sublime Material Theme, file-icons
---

Steps to Reproduce:

1. Create a file with two functions with doc blocks 
2. Collapse code
3. Open up same file in second panel
4. Expand single function and doc block
5. Observe collapse icon and ellipsis show up on expanded code 
Note: only tested with php as language mode

Image illustrates steps above

You can see that it will show correctly if the state is the same. But if collapsed on one, but not the other, it will show collapsed on the expanded one.
![screen shot 2017-11-16 at 10 40 50 am](https://user-images.githubusercontent.com/3842798/32900240-02e1cd02-cabb-11e7-9b81-447feb7041cf.png)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
Fixed in 1.19
