### ISSUE TITLE
Endless loop of sorts in suggest widget on master

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#38522]
* open a new untitled file
* type "hey hey"
* vscode freezes
* change the settings to `"editor.quickSuggestions": false`
* type "hey hey"
* vscode does not freeze

**Comment by jrieken** [comment]
`Trait#set` being called in a loop...

<img width="362" alt="screen shot 2017-11-16 at 15 50 30" src="https://user-images.githubusercontent.com/1794099/32897454-eb2e4fd4-cae5-11e7-8248-2ca668e729e7.png">

**Comment by jrieken** [comment]
This got introduced with the in-order-event delivery... I pushed a change to make that opt-in but we should still look into the list and why that happens. Ideally, in-order-event-delivery is the default, not the exception

**Comment by joaomoreno** [comment]
This should actually stop the recursion: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L576

hm..

**Comment by jrieken** [comment]
Yeah, problem was that a nested call to `fire` would return *before* the event have been dispatched. With that state wouldn't be updated and stuff like this would happen...
