### ISSUE TITLE
experimentalDecorators for JavaScript in User Settings

### ISSUE THREAD

**Issue by EstebanBorai** [Microsoft/vscode#38529]
- VSCode Version: **October 2017 (version 1.18)**
- OS Version: **Microsoft Windows 10 Pro**

Steps to Reproduce:

1. Modify user settings json file. Add the next line: ` "javascript.implicitProjectConfig.experimentalDecorators": true,`

Reproduces without extensions: Yes

It seems that the current setting is not making changes, decorators still looking red in the text editor

**Comment by mjbvz** [comment]
@EstebanBorai Is your javascript part of a `jsconfig.json` project? You can check this by running the `JavaScript: Go to Project Configuration` command in VS Code for the current file

**Comment by mjbvz** [comment]
Closing as not actionable without more info
