### ISSUE TITLE
Terminal and tasks related shortcuts

### ISSUE THREAD

**Issue by papadi** [Microsoft/vscode#38525]
I find shortcuts related tasks and the related terminals to be insufficient. The mouse is required even for very simple things.

For example, when the focus is in a terminal, it isn't possible to use Alt+ to access the main menu. So restarting the current task requires the use of the mouse. Same for killing a task/terminal.

Also, switching from one terminal to the next one also requires the mouse.

The same to switch from Terminal to Output and Problems.

I think that terminals should move to the same level as Output and Problems and not grouped under a Terminal tab and it should be possible to switch between them using Ctrl+Tab. Also, there should be a restart task button and shortcut for terminals related to a task.

**Comment by fabiospampinato** [comment]
I don't know what's the situation regarding tasks, but you can:

- Kill a terminal with a `ctrl+w` by adding the following to your `keybindings.json` file: 
  - `{ "key": "ctrl+w", "command": "workbench.action.terminal.kill", "when": "terminalFocus" }`
- Switch focus to the next/previous terminal by adding the following:
  - `{ "key": "ctrl+tab", "command": "workbench.action.terminal.focusNext", "when": "terminalFocus" }`
  - `{ "key": "ctrl+shift+tab", "command": "workbench.action.terminal.focusPrevious", "when": "terminalFocus" }`
- There are some commands you can trigger with a shortcut for switching to the other panels:
  - `workbench.action.output.toggleOutput`
  - `workbench.action.terminal.toggleTerminal`
  - `workbench.actions.view.problems`

> terminals should move to the same level as Output and Problems

I didn't understand this, what do you mean exactly?

I don't know how one's supposed to restart a task, but you may give my [Terminals](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) extension a try instead, it's almost a replacement for tasks. After you run some commands through it you can simply restart it with the usual `arrow up` and `enter` combo.

Hope that helps.

**Comment by papadi** [comment]
Thanks. This does help!

About having terminals on the same level as Output and Problems I mean that I don't like the fact that terminal instances are hidden in a drop down. This means two clicks to select a terminal. I would like to see them on the level of Output and Problems. One less click to find a terminal.

**Comment by fabiospampinato** [comment]
I see. There was an issue about this exact thing, but it requires a substantial change on the UI, so don't put too much hope in it. I personally don't think it's going to happen.

**Comment by urielha** [comment]
Hi,
I think this is related to this issue:
In the previous versions (included until [1.17](https://code.visualstudio.com/updates/v1_17)) there was an option to move to a specific terminal using `Ctrl + Shift + P` and mention the terminal index.

![focusterminal1](https://user-images.githubusercontent.com/5815603/33061518-1134533c-cea5-11e7-83c4-9e9bd563b7ab.jpg)

This can partially resolve the issue to open the terminal dropdown menu - in case you remember which terminal you want to go just hit `Ctrl+Shift+P` and `tX` as X is the terminal index.

It seems like this option has been omitted from the new version and could be awesome to bring it back :)

Thanks

**Comment by Tyriar** [comment]
Yeah it kind of sucks that there are so few terminal shortcuts. It's like this because the terminal was added late in the game and all the shortcuts were already taken. I encourage you to set up your own set of keybindings that you're comfortable with. Here are mine: https://github.com/Tyriar/dotfiles/blob/816f1d1cd22e09a306be4f551b5cfa817c280128/modules/vscode/config/keybindings.json#L22-L28
