### ISSUE TITLE
Go to Next/Previous Symbol Highlight should not scroll page unless necessary

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/vscode#38521]
similar: #34519

This is obviously a minor issue and thanks for implementing the new, "Go to Next/Previous Symbol Highlight" shortcuts.

But I think they should behave more like Visual Studio where if the next/previous symbol highlight to be navigated to is within the current view, then no page scrolling should occur.

As of right highlight navigation will scroll the page no matter what

**Comment by myfonj** [comment]
Nota bene, current simple "Move Selection To Next Find Match" (`editor.action.moveSelectionToNextFindMatch`) and "Find next" (`editor.action.nextMatchFindAction`) actions already have such behavior: scrolls only when next match is out of the viewport.

So it really seems that similar behavior might be expected for the "Next Symbol Highlight" (`editor.action.wordHighlight.next`) in question.
