### ISSUE TITLE
When opening a file by double click on it opens VSC, but is not loading the correct encoding of the extension

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#38520]
I made a an extension that overwrites files.encoding with a non UTF-8 encoding.
--> in my case oem850

When i now open a file from within VSC or VSC is opened already everything works fine:
![open_in_vsc](https://user-images.githubusercontent.com/17499573/32895515-99ab669c-cae0-11e7-865d-77bf2315277d.png)

When VSC is closed and i double click the same file from e.g. desktop or windows explorer the encoding isn't recognized (the extension seems to be loaded):
![open_from_desktop](https://user-images.githubusercontent.com/17499573/32895530-a32bb398-cae0-11e7-8670-a336cfde4ed2.png)

Settings of my extesion (if my error should be there):
![grafik](https://user-images.githubusercontent.com/17499573/32895569-c79fdede-cae0-11e7-8a54-c8f94e8b9004.png)

- VSCode Version: 1.18.0
- OS Version: Win 10

Steps to Reproduce:
1) Install Extension supporting non- UTF8 encoding
e.g.: https://github.com/Raydir/F-Script
2) double click it from desktop vs. open it in already opened VSC-Window.

Sample File with OEM850 encoding.
[example.txt](https://github.com/Microsoft/vscode/files/1478759/example.txt)

----
Reproduces without extensions: No

**Comment by bpasero** [comment]
@Raydir you can configure the encoding via files.encoding setting, you can also enable encoding auto detection via settings.

**Comment by Raydir** [comment]
@bpasero i do set files.encoding in my extension. To set files.encoding in the user-settings isn't the same because that would block other files like javascript as it seems.

When auto-guess is activated it "thinks" that it is OEM866 even when my extension is setting files.conding to oem850.

As said - it works if i open files when the editor is open.. direct open from windows when VSC isn't running does not work alike.
