### ISSUE TITLE
Improve the pending changes badge amount

### ISSUE THREAD

**Issue by danbovey** [Microsoft/vscode#38524]
- VSCode Version: 1.18.0
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Make 100+ file changes in a workspace with SCM.
2. View the SCM action item badge.

Feature Request:

- When the badge displays 99+ it's not very helpful and it clearly supports three digits being displayed because the plus is there.
- If there are hundreds of pending changes, it looks like it could show the exact amount without any display issues and be much more clear for users when they happen to have 100+ pending changes.
- If there are thousands of pending changes then this could be displayed as 1k, 2k etc.

**Comment by joaomoreno** [comment]
Want to submit a PR?

**Comment by shobhitchittora** [comment]
@joaomoreno can you point where in the source this filtering on count in defined?

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositebar/compositeBarActions.ts#L210

cc @bpasero

**Comment by danbovey** [comment]
Took me a while to find it... turns out I could have just searched for "99+" hardcoded, lol
