### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by csnakk** [Microsoft/vscode#38533]
I realize that this has been mentioned in the past and may not be the most appropriate channel, but I am hopeful that this post might start a dialogue and raise the request again. As a long time developer (21 years) who uses Windows, MacOS and Linux daily, vscode has become my primary editor on each of those platforms when I'm in a GUI. I'm regularly using or testing on Android and iOS devices and over the past couple years, an ipad pro has become my primary on the go device. I typically vpn/rdp when I need to do mobile development or heavy lifting that are beyond the current limitations of a mobile os / applications. Having said all that, vscode on iOS/Android would be a godsend and a game changer. I would gladly throw money at it. My deepest and most sincere thanks to everyone who has made vscode happen. Thank you!

**Comment by rodrigoelp** [comment]
I don't understand the feature request.

**Comment by csnakk** [comment]
Condensed down, I'm hoping for a future port of vscode that runs on iOS.
