### ISSUE TITLE
Electron's stdout disappears in DEBUG CONSOLE under Windows when using inspector protocol

### ISSUE THREAD

**Issue by cusr** [Microsoft/vscode#38531]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
vscode-text-pastry|jkj|1.2.0
cpptools|ms-|0.14.2
advanced-new-file|pat|0.5.1
vscode-icons|rob|7.18.1
annotator|ryu|0.10.1
code-settings-sync|Sha|2.8.5
vscode-fileutils|sle|2.7.1

(1 theme extensions excluded)

---

Almost the same problem as described in issue #2843.
But protocol is different from that issue.

Steps to Reproduce:
My launch.json is like below:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}/release",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "args" : [".", "--server","--devTool"],
      "protocol": "inspector"
    }
  ]
}
```
1. put some debug prints in app.js:
```
// app.js
console.log('test');
```
2. press F5 to run the debug. 
3. nothing shows in the DEBUG CONSOLE.

Reproduces without extensions: Yes

**Comment by pitaj** [comment]
You can use `"outputCapture": "std"` to see stdout stuff in the debug console

**Comment by cusr** [comment]
@pitaj Thank you very much! This option solve my issue.
