### ISSUE TITLE
[Feature] Add WSL path to File Explorer

### ISSUE THREAD

**Issue by msevastian** [Microsoft/vscode#38534]
For Windows installations in File Explorer add entry for file/folder "Copy WSL Path"
Before
![image](https://user-images.githubusercontent.com/28624368/32905750-8d5b5938-cb03-11e7-89e9-f9fde812d685.png)
After
![image](https://user-images.githubusercontent.com/28624368/32905764-9984fc5a-cb03-11e7-8cb0-39e0e38fce51.png)

That would be pretty much convenient for people working frequently with WSL inside VScode

**Comment by CoenraadS** [comment]
I actually encountered this myself, I made a small extension you can try: https://marketplace.visualstudio.com/items?itemName=CoenraadS.copy-wsl-path
