### ISSUE TITLE
EPERM after using Code for a while

### ISSUE THREAD

**Issue by philr-vistatec** [Microsoft/vscode#38532]
VS Code: version 1.18.0 x64 on Windows 10 Enterprise

Steps to Reproduce:

1. Suddenly after using Code for a while I now get: "Error: EPERM: operation not permitted, open ....html.

I have turned off all antivirus software, checked my firewall settings and permissions on the project folders.

I really love Code and very frustrated.

Any suggestions what further to check?

![code](https://user-images.githubusercontent.com/5450321/32904515-687deb62-caef-11e7-8fc8-a324bb38cb60.PNG)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by philr-vistatec** [comment]
I tried that before submitting the issue. Same behavior.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by philr-vistatec** [comment]
Benjamin, same behavior but much more output in the console. Log file attached.
v1.19.0 commit 34c44f872c177d6f9439706418f8e49bf125d08
[-1511012386028.log](https://github.com/Microsoft/vscode/files/1484610/-1511012386028.log)

**Comment by bpasero** [comment]
@philr-vistatec could it be a permission issue? E.g. you installed as admin and run as normal user or vice versa?

**Comment by philr-vistatec** [comment]
I don't think so. I am a local Administrator on my laptop. Whilst I get the error in Code I can still simultaneously open the project in other IDE's. Is it normal after launching Code to have so many processes (attached)?
![vsprocesses](https://user-images.githubusercontent.com/5450321/33021912-50452074-cdfb-11e7-8db2-83e6f6630950.PNG)

**Comment by bpasero** [comment]
Weird

**Comment by philr-vistatec** [comment]
:-) Does that mean I get a prize?  Any other information I can give you or things I can run to help diagnose?

**Comment by bpasero** [comment]
@philr-vistatec does this only happen when you open HTML files or any file?

**Comment by philr-vistatec** [comment]
All file types. Tried several other things. More oddly I can create a new file in the project that's giving the EPERM errors and happily edit, close, re-open, edit it. Comparing file permissions new file to existing file in Windows Explorer or bash shows exactly the same permissions. At this stage I guess I'll re-create the project in current Code version and slowly copy files from the old project to the new and see how I get on.

**Comment by bpasero** [comment]
It looks like the files you are trying to open have different permissions. Does it reproduce in all folders you try with?

**Comment by philr-vistatec** [comment]
Yes, same behaviour with 4 projects.

**Comment by bpasero** [comment]
@philr-vistatec and the file opens fine using other editor?
