### ISSUE TITLE
Inspect spelling is wrong.

### ISSUE THREAD

**Issue by arkachat** [Microsoft/vscode#38539]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-helm|tec|0.3.0
Unable to open 'Inspect': Error: unknown command "inpsect" for "helm"

---

Steps to Reproduce:

1.Right Click and click inspect chart

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Looks like this is from an extension, please open an issue on their repo.
