### ISSUE TITLE
Space character before text in "File" menu in Spanish locale

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#38537]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
material-icon-theme|PKi|3.0.0
code-settings-sync|Sha|2.8.5
sort-lines|Tyr|1.3.0
quokka-vscode|Wal|1.0.80
path-intellisense|chr|1.4.2
githistory|don|0.2.3
tslint|eg2|1.0.22
vscode-npm-script|eg2|0.3.3
php-intellisense|fel|1.5.4
code-runner|for|0.8.3
docthis|joe|0.6.0
ftp-sync|luk|0.3.3
theme-monokai-pro-vscode|mon|1.1.2
vscode-apache|mrm|1.1.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
typescript-javascript-grammar|ms-|0.0.24
vscode-code-outline|pat|0.0.12
stylelint|shi|0.30.0
vscode-coffeelint|slb|0.0.2
language-stylus|sys|1.8.0
ayu|tea|0.10.0
es-quotes|vil|0.2.6
vscode-todo-highlight|way|0.5.11
twig|wha|1.0.2
vscode-import-cost|wix|2.5.1

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Change to Spanish locale (es)
2. Open file menu

Reproduces without extensions: Yes

<img width="320" alt="screen shot 2017-11-16 at 17 48 20" src="https://user-images.githubusercontent.com/11057501/32906952-675af0e8-caf6-11e7-8c9a-06ec5ca7e3bb.png">

Problem is easily visible in this screenshot. There's a space character before "Abrir el espacio de trabajo…" (Open workspace…) and "Guardar espacio de trabajo como…" (Save workspace as…)

Doesn't exist in the English locale, not checked other locales.

**Comment by johnliu2016** [comment]
// @lukaschal, extra leading space

**Comment by lukaschal** [comment]
Not repro on version 1.20

![esn](https://user-images.githubusercontent.com/18324331/36903868-dae94a18-1e26-11e8-9fdf-bea2f36ed3d2.png)
