### ISSUE TITLE
Move editor left/right shortcuts not working

### ISSUE THREAD

**Issue by adamabernathy** [Microsoft/vscode#38530]
- VSCode Version: 1.18.0 (1.18.0)
- OS Version: 10.13.1 (17B48)

Steps to Reproduce:

1.  When using the 
`-workbench.action.moveEditorRightInGroup`,
`-workbench.action.moveEditorLeftInGroup` 
shortcuts, the the correct tab is highlighted but the panel with the document is not changed.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@adamabernathy I cannot reproduce, can you share a video? Does it reproduce with extensions disabled (code --disable-extensions)?

**Comment by adamabernathy** [comment]
Is this what you're going for? https://youtu.be/pMYisohe-QE

**Comment by bpasero** [comment]
@adamabernathy the video seems right to me, what other behaviour would you expect?

**Comment by adamabernathy** [comment]
@bpasero, shouldn’t it also change the editor to the file of the tab that was selected?

Right now it just changes the tab but not the content of the editor.

**Comment by bpasero** [comment]
@adamabernathy that action is to literally move the editor left or right. there is other actions to actually navigate within tabs. 

![image](https://user-images.githubusercontent.com/900690/32936482-b2725642-cb74-11e7-8ab9-45ca8f3d9642.png)
