### ISSUE TITLE
PHP inserts $_COOKIE after any >

### ISSUE THREAD

**Issue by CaptainN** [Microsoft/vscode#38548]
- VSCode Version: 1.18.0
- OS Version: High Sierra

Steps to Reproduce:

1. Open VS Code
2. Create PHP document
3. Type a closing html bracket character (greater than > ).
4. It suggests (autocomplete) `$_COOKIE` so while typing a new HTML tag in a PHP file, if you press return after the first tag, you get: `<div>$_COOKIE.`

Reproduces without extensions: Yes

It should instead of offering `$_COOKIE` for auto complete, most of the time add a closing HTML element. The editor handles JS inside HTML fine in this regard. PHP should work as nicely.

**Comment by bmewburn** [comment]
One option is to install (this)[https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client] and set `php.suggest.basic` to false

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/37919
