### ISSUE TITLE
VS Code uses 99% of CPU with just open it

### ISSUE THREAD

**Issue by EnzoDarling** [Microsoft/vscode#38544]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. I just execute code with or without --disable-extensions it starts to consume 99% of cpu usage
Either way, the only extensios i had was icons theme, color theme and twig syntax

**Comment by roblourens** [comment]
Please answer the questions here to help us narrow it down: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by EnzoDarling** [comment]
- Project's Size 471 MB, 15.295 files, 4728 folders
- Languages used in this Project: twig, php (Symfony's project)
- Code runs on a single-CPU enviroment
- Process list taken from Process Explorer
![screenshot_1](https://user-images.githubusercontent.com/13856358/32922734-6e80a09a-cb12-11e7-81fc-129dbc0494ef.png)

**Comment by roblourens** [comment]
vscode doesn't run very well in a single-cpu environment. All I can suggest is, open smaller folders, or maybe using `files.watcherExclude` or `files.exclude` to ignore parts of the project that you don't need may help.
