### ISSUE TITLE
Add extension recommendations for mimetypes not supported out of the box

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#38543]
There are a lot of file types that are not supported out of the box in VS Code and need extensions to provide the most basic of features like syntax highlighting and simple language support.

This feature request is to add such extensions for popular file types to our recommendation list so that the current recommendation system can prompt the user when such files are first opened.

Examples:
- sass
- stylus
- cake

@Microsoft/vscode and community members, please add more here as you see fit

**Comment by octref** [comment]
I suggest https://marketplace.visualstudio.com/items?itemName=slevesque.shader by @stef-levesque for HLSL / GLSL / Cg.

**Comment by bmewburn** [comment]
Hi @ramya-rao-a , would you consider adding (intelephense)[https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client] to the recommendations. It's PHP and there are already some recommendations for that but it is currently the highest rated most full featured PHP language server extension yet one of the least downloaded

**Comment by ramya-rao-a** [comment]
@bmewburn Right this moment, we are not taking any call. This issue is to collect feedback and suggestions. At the end of next week or so, we'll do a sweep through and pick extensions and revise the recommendations for the next release

**Comment by alexandrudima** [comment]
@ramya-rao-a This item is on November. Assigning to you to decide what you want to do

**Comment by ramya-rao-a** [comment]
An alternative to keeping track of a white list of unsupported file extensions and the corresponding recommendations is to 
- show a prompt that says `Support for files with extension `abc` is better with extensions from the marketplace.`
- One of the options in the prompt would be `Search marketplace`
- Another option would be `Never show again` which would ensure that no further prompts are made for the file extension `abc`
- Third option would be `Close`

We already have the infrastructure in place to run the said search. And #40269 is the PR for the same.

The only catch now is that we may want to maintain a whitelist of file extensions for which we DO NOT want to do the above. For example: .txt, .log

**Comment by ramya-rao-a** [comment]
Final cut:
- When a file with unknown/unsupported file type is opened, a search for related extensions in the marketplace is made in the background
- If the above search yields any results, then user is prompted about it with an option to search and display the same
- The prompt is never repeated regardless of what the user reaction to the prompt is. This is unlike the extension recommendation prompt which re-appears as long as user chooses not to do so.

**Comment by DanTup** [comment]
Just tested this out in insiders (sent here from #41866) and it works great:

<img width="1043" alt="screen shot 2018-01-19 at 19 25 56" src="https://user-images.githubusercontent.com/1078012/35167809-b864ff3a-fd4e-11e7-8cb7-5252f6b03c9c.png">

<img width="248" alt="screen shot 2018-01-19 at 19 26 05" src="https://user-images.githubusercontent.com/1078012/35167815-bd54604e-fd4e-11e7-95bc-89594c6e758c.png">

Thanks!

**Comment by aeschli** [comment]
I tried this with file `foo.stencil` and 'foo.stylus`, but never saw the prompt. Tested on Linux and OSX.
- create a file `foo.stencil'
- open the file in the editor, wait

**Comment by aeschli** [comment]
Ok, now I see it when starting VSCode on a fresh user dir. I might have clicked on 'Don't show again some time` some time, but surely not for these extensions.

**Comment by ramya-rao-a** [comment]
@aeschli Did you have `extensions.ignoreRecommendations` set to `true` before? That would disable these prompts as well
