### ISSUE TITLE
Debug window keeps horizontal resize cursor active, when closed

### ISSUE THREAD

**Issue by leonardoResendeLima** [Microsoft/vscode#38547]
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T21:22:49.932Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
1. Show Debug window
2. Move to right
3. Close and you will see the cursor on the same position

![2017-11-16 2](https://user-images.githubusercontent.com/8305641/32912884-9f448612-caf7-11e7-913b-4d7d9df799ef.png)
![2017-11-16 3](https://user-images.githubusercontent.com/8305641/32912886-a091c4e4-caf7-11e7-9fd8-066512a3f9f3.png)

**Comment by isidorn** [comment]
@Ripper1992 I do not really see the cursor on this picture. Can you please clarify what is wrong here.
What is expected here?

**Comment by leonardoResendeLima** [comment]
@isidorn here is the video. You can see when I hide de terminal pane the width adjust cursor continues to appear.

![video](https://user-images.githubusercontent.com/8305641/33088518-fb3634e4-ced4-11e7-8bbc-581e72644f36.gif)

**Comment by isidorn** [comment]
Thanks this is fixed in latest
