### ISSUE TITLE
ES6 module import improperly added to file on save

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#38541]
- VSCode Version: Code - Insiders 1.19.0-insider (0fbdfff167653b233231259ceb3109f0931887ef, 2017-11-09T06:19:28.857Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3

---

Steps to Reproduce:

1. Create new file with `#!/usr/bin/env node` in the first line (then some line breaks)
2. Type setImmediate and hit `ctrl-space` to trigger suggestions
1. Select the `setImmediate` option that auto-imports from `timers`
1. Note that `import { setImmediate } from "timers";` is prepended to the file

I don't work with ES6 modules, so I may be mistaken, but the import should come after the hashbang, no?

**Edit**: I'm likely not understanding how imports work, and selected the auto-import option by accident. How this happened I can't explain, since the "non-import" variety comes up first if suggested.

In any case, when I try to execute my file, my cursor turns into a plus-sign-crosshair and lets me drag-select a section of the screen... which is... weird behaviour.

**Comment by julianlam** [comment]
Oh interesting, somehow it triggered imagemagick to take a screenshot... and outputs a file called `timers` saved to the same directory.

```
%!PS-Adobe-3.0
%%Creator: (ImageMagick)
%%Title: (timers)
%%CreationDate: (2017-11-16T13:29:15-05:00)
%%%%BoundingBox: (atend)
%%DocumentData: Clean7Bit
%%LanguageLevel: 1
%%Orientation: Portrait
%%PageOrder: Ascend
%%Pages: 5
%%EndComments

%%BeginDefaults
%%EndDefaults

%%BeginProlog
%
% Display a color image.  The image is displayed in color on
% Postscript viewers or printers that support color, otherwise
% it is displayed as grayscale.
%
/DirectClassPacket
{
  %
  % Get a DirectClass packet.
  %
  % Parameters:
  %   red.
  %   green.
  %   blue.
  %   length: number of pixels minus one of this color (optional).
  %
  currentfile color_packet readhexstring pop pop
  compression 0 eq
  {
    /number_pixels 3 def
  }
  {
    currentfile byte readhexstring pop 0 get
    /number_pixels exch 1 add 3 mul def
  } ifelse
  0 3 number_pixels 1 sub
  {
    pixels exch color_packet putinterval
  } for
  pixels 0 number_pixels getinterval
} bind def

/DirectClassImage
{
  %
  % Display a DirectClass image.
  %
  systemdict /colorimage known
  {
    columns rows 8
    [
      columns 0 0
      rows neg 0 rows
    ]
    { DirectClassPacket } false 3 colorimage
  }
  {
    %

... with a lot more binary data afterwards
```

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/20088 to track the hashbang import issue

You can set `"typescript.autoImportSuggestions.enabled": false` to disable auto imports if they are getting in the way. The intellisense popup also shows if a symbol will be auto imported: 

![screen shot 2017-11-16 at 5 30 16 pm](https://user-images.githubusercontent.com/12821956/32924893-db90632e-caf3-11e7-8b0e-ba1a4d541a95.png)

No clue about any of the other stuff but it sounds unrelated to VS Code
