### ISSUE TITLE
Extend 'findFiles' to allow multiple patterns

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#38545]
Extended glob patterns are unlikely to be supported: https://github.com/Microsoft/vscode/issues/10851

So allowing an array of patterns would be easy to support and make those scenarios much easier to deal with.

**Comment by jrieken** [comment]
Don't we support glob-patterns like these `{foo,bar}`?

**Comment by roblourens** [comment]
Given the comment in #10851, I wonder if that isn't discoverable, or if arrays would be easier to work with.

**Comment by roblourens** [comment]
I don't think many people are asking for this, not worth changing API for it
