### ISSUE TITLE
[Feature request] Preserve JSDoc linebreaks

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#38540]
I suppose, it will be fine if VSCode could leave all handmade line breaks in JSDoc while interpret comments in popups. It will allow developers to make lists inside comment, etc.

I mean, let the comment like this
```
/**
 * List of dialogs. 
 * Note:
 *      - this is unstable
 *      - can be undefined
 */
```
interpret literally to this
```
List of dialogs. 
Note:
     - this is unstable
     - can be undefined
```

**Comment by mjbvz** [comment]
We interpret jsdoc comments as markdown, which will wrap text automatically. This wrapping is also the expected behavior in most cases.

Two options if you want to create a manual break:

End the line with two spaces (note the spaces after ` List of dialogs.`):

```js
/**
 * List of dialogs.   
 * Note:
 *   - this is unstable
 *   - can be undefined
 */
const x = 123;
```

Put in an extra newline:

```js
/**
 * List of dialogs.
 *
 * Note:
 *   - this is unstable
 *   - can be undefined
 */
const ab = 123;
```
