### ISSUE TITLE
Workspaces at a volume root show as blank in the recent workspaces of the Windows menu

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38546]
If you create a VS Code workspace at the top of a volume on Windows the 'Recent Workspaces' will show blank.

![image](https://user-images.githubusercontent.com/33490168/32910662-dc8b3a36-cad7-11e7-8ee2-ea8dc8fb5b8f.png)

Hover will show the volume name.

VS Code 1.18.0
OS Windows 7

**Comment by bpasero** [comment]
@draeger-charles-wilson I cannot reproduce, I tried by saving a workspace to `C:`. Is that what you did?

**Comment by draeger-charles-wilson** [comment]
I created a new workspace at the root of a volume.

**Comment by bpasero** [comment]
@draeger-charles-wilson ah, so that is a folder at the root? or is it a multi-root-workspace file (*.code-workspace)?

**Comment by draeger-charles-wilson** [comment]
I opened the volume root using (Open Folder) from a session of Code launched using the New Window selection in recent.
