### ISSUE TITLE
Copy/Paste a multiline Powershell commmand with ` as line separator is not honored by the terminal and each line gets executed separately

### ISSUE THREAD

**Issue by MaurGi** [Microsoft/vscode#38559]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.11.1
githistory|don|0.2.3
xml|Dot|1.9.2
mssql|ms-|1.2.1
azure-account|ms-|0.2.2
azurecli|ms-|0.3.0
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.5.0
vscode-docker|Pet|0.0.22
java|red|0.14.0
vscode-icons|rob|7.18.1
vscode-java-debug|vsc|0.3.0
vscode-java-pack|vsc|0.2.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open a PowerShell terminal 
2. Paste a multiline command with `

In my case: 
    Write-Host "Creating storage account: sql backup"
    $res = az storage account create `
        --name "test123" `
        --resource-group "test123" `
        --sku Standard_LRS

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
