### ISSUE TITLE
move extension activity bar icon to the bottom

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode#38554]
The extension view/activity button would be better suited to be on the bottom near the config activity.

It's not really a view that is often needed during work - like the search or git view.

**Comment by roblourens** [comment]
You can hide it by right clicking it.

**Comment by mojo2012** [comment]
No I didn't mean the whole activity bar (different issue). I just meant, that the extension icon/button is better suited to be near the wheel/config button on the bottom of the bar.
As it is normally nothing you would constantly use during work.

**Comment by roblourens** [comment]
You can hide the individual button too, by right clicking it.

> As it is normally nothing you would constantly use during work.

I disagree, but that's why we let you customize it.
