### ISSUE TITLE
Watermark layout takes 10ms on window resize

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38556]
**Repo**

1. Resize VS Code window

**Bug**
Notice that watermark layout takes a significant amount of time, even though it is hidden. This is due to a call to `getClientBoundingRect`

**Comment by bpasero** [comment]
This is bad, when resizing the sidebar, this is now the top hit:

![image](https://user-images.githubusercontent.com/900690/33269751-0d906734-d382-11e7-905a-2677907963bd.png)

[CPU-20171127T144842.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1506015/CPU-20171127T144842.cpuprofile.zip)

**Comment by chrmarti** [comment]
Turns out we have that size already, we just need to surface it in the event.

**Comment by bpasero** [comment]
@chrmarti thanks 👍
