### ISSUE TITLE
Move left activity bar to bottom

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode#38555]
The activity bar on the left (is it called  that way?) takes too much screen real estate.
It would therefore be better to make it horizontal and either on the top or on the bottom of the content sidebar

**Comment by fabiospampinato** [comment]
I guess it actually makes sense to do that if one's using a vertical monitor.

@mojo2012 I think you'll be better off just hiding it and learning the shortcuts for changing view. Or you may use my [Commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) extensions to add buttons for this to the statusbar:

![Example](https://raw.githubusercontent.com/fabiospampinato/vscode-commands/master/resources/demo/activitus_bar.png)
