### ISSUE TITLE
VS Code update to icons resulted in 3 different icons

### ISSUE THREAD

**Issue by tylerr514** [Microsoft/vscode#38558]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:
1. look at icon on taskbar
2. look at icon in shortcut properties
3. look at icon in taskbar shortcut's icon

Image as proof:
![image](https://user-images.githubusercontent.com/22574513/32917230-82780564-caec-11e7-9f7c-7418161a6fb1.png)

Side Note:
I have restarted my computer twice since the update and manually restarted Windows Explorer trying to fix it.

**Comment by bpasero** [comment]
This is a windows icon cache issue and nothing we can do about.
