### ISSUE TITLE
When closing modified tab, cannot move focus to "Don't save" with keyboard

### ISSUE THREAD

**Issue by TheIndifferent** [Microsoft/vscode#38565]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6.

Steps to Reproduce:

1. CMD+N to open a new tab
2. write something
3. press CMD+W to close the tab
4. try to focus "Don't save" button without using a mouse

**Comment by bpasero** [comment]
This is a macOS thing which can be changed here:

![image](https://user-images.githubusercontent.com/900690/32931858-b2119964-cb66-11e7-90dd-4bf497d24a1f.png)

**Comment by TheIndifferent** [comment]
Ah, you are right, thank you! I am sure I did that just couple of days ago, no idea how that setting got changed...
