### ISSUE TITLE
Feature request: rollup --watch problem matcher preset

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode#38560]
I am having real problems getting my [rollup](https://rollupjs.org/) build tool reporting when it fails to the terminal. My task is:

```
{
    "version": "2.0.0",
    "tasks": [{
        "label": "build",
        "command": "./node_modules/.bin/rollup -c --watch",
        "isBackground": true,
        "type": "shell",
        "presentation": {
            "reveal": "always",
            "panel": "dedicated"
        }
    }]
}
```
It will run OK, but when it fails due to a problem in my code i get an error message in the terminal, but it does not alert me. I would like it to tell me it has failed and pop up the terminal to show the error :)

**Comment by dbaeumer** [comment]
You need to defined a problem matcher and add it to the task. Look here how to define one or you might be able to reuse on of the already existing matchers. This will then capture the errors and show them in the editor and the problems view. 

https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

**Comment by David-Else** [comment]
I read that article and could not make it work for Rollup, that is why I requested a preset like there are for the majority of the other popular bundler/compilers.

Does this topic being closed mean that there is no possibility of a preset being supplied in the future? This was a feature request rather than a help topic.

Rollup is very popular, it is even being used by facebook now:

[Convert current build system to Rollup and adopt flat bundles #9327](https://github.com/facebook/react/pull/9327)

**Comment by dbaeumer** [comment]
@David-Else there are various options to solve this. Problem matchers can be contributed as an extension so that could go into one and then into the marketplace. Or we get a PR and add it to the core. The preferred version is that marketplace. I am happy to help if there is a GitHub repository I can clone with a problem matcher definition that doesn't work but the task is easy to run and produces the wanted output.

**Comment by David-Else** [comment]
Thanks for your explanation, afraid I am not experienced enough to help in this matter... one day I hope I can contribute more.
