### ISSUE TITLE
Typescript overriding accessors not understood

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode#3856]
```
class Foo {
  x: any;
  get y(): any { return undefined; }
}
class Bar extends Foo {
  x: number;
  get y(): number { return undefined; }
}
```

The two variables named x are related: Shift-F12 will find them both, and renaming one will rename the other. But the two getters named y are treated as distinct: Shift-F12 won't show both, and renaming one doesn't rename the other

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7443
