### ISSUE TITLE
Live Share support in other languages

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#38562]
We are already getting questions about when our language extension (PowerShell) will support Live Share - given that the initial preview supports only Node and ASP.NET/C#.  

Is there anything we can tell folks?  Will every language extension have to implement support for LiveSharing or is this something completely taken care of by VSCode and VSCode will handle the expansion of LiveShare to other languages?

**Comment by kieferrm** [comment]
Since Live Share goes across editors and IDEs, there is no clear cut here. Some aspects we can take care off transparently while others will need work on the extension side.

**Comment by kieferrm** [comment]
We worked with the LiveShare team on a model that allows them to support pretty much any language.   Thus, I'm closing this as there is nothing else for us to do here. All remaining questions/requests should go directly to the LiveShare team.
