### ISSUE TITLE
auto terminal cd

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#38566]
Based on https://github.com/Microsoft/vscode/issues/12094 I believe my productivity would increase if there would be a setting that the current active terminal would follow you around by automatically `cd` to the file directory you are working on or is selected without having to right click, open in terminal. Maybe a sticky icon in the terminal bar you can toggle on or off.

**Comment by Tyriar** [comment]
Request in an extension here: https://github.com/Tyriar/vscode-terminal-here/issues/9
