### ISSUE TITLE
disable hover

### ISSUE THREAD

**Issue by varxzy** [Microsoft/vscode#38569]
![image](https://user-images.githubusercontent.com/20296852/32924196-5bbf181a-cb76-11e7-8135-79b97fd20fdc.png)

How to turn off the css property suspension tips, God this is annoying! ! !

**Comment by aeschli** [comment]
Do you want to tur them off in css only, or everywhere?

**Comment by varxzy** [comment]
@aeschli I currently only notice html and css have this hint, so i want to be able to turn off prompts in css and html

**Comment by aeschli** [comment]
So I guess this should be editor setting that can be defined language specific.

**Comment by varxzy** [comment]
Hope so, I also just started using VScode.

**Comment by cangosta** [comment]
@aeschli , I'm using vs code monaco editor on my application and I need to hide the referred hover messages. Is there any workaround to disable them? I searched the whole API without luck.

**Comment by aeschli** [comment]
There's a hidden setting ` "editor.hover": false`

**Comment by varxzy** [comment]
@aeschli You guys are the best!

**Comment by megamindbrian** [comment]
This should work, but I would like to disable per file type.  E.g. Tooltips might be useful while editing Typescript, but I need to disable it for CSS.  If there's a good starting point to PR this based on the editor.hover work let me know.

**Comment by PunchyRascal** [comment]
I find most of the tooltips rather annoying, for example I am browsing the file tree (looking for a file in a complicated tree) in the explorer side bar and the structure gets covered up by endless stream of tooltips (full file paths) that I don't want atm and they get in the way.

**Comment by PunchyRascal** [comment]
BTW "editor.hover": false does not work anymore :( "editor.hover":

**Comment by dariodev** [comment]
This `"editor.hover": false` does work but it also disable color picker in CSS. We need a way to hide tooltips only. Also to show tooltips only if a shortcut key is pressed.

**Comment by audiot** [comment]
manually activate the tooltips / colorpicker:
--------------------------------------------

if you have set "editor.hover" to false you can manually activate the tooltips or the colorpicker by pressing the shortcut  "CTRL+K+I". You can close the tooltip with "ESC" (if the tooltip has lost the focus, just click on the tooltip again and press "ESC")

Thank me later :)

**Comment by fvilers** [comment]
On version 1.27.2, I found that only this parameter disabled all the tooltips: `"editor.hover.enabled": false`.
