### ISSUE TITLE
VSCode moves down by 1 title bar height on every launch

### ISSUE THREAD

**Issue by a1291762** [microsoft/vscode#38574]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 3.13.0-135-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
explorer-excluded-files|sad|1.0.0

---

Steps to Reproduce:

1. Launch VSCode
2. Ensure it is not maximized
3. Close VSCode
4. Launch VSCode again

Reproduces without extensions: Yes

More info:
I'm running Ubuntu 14.04 with MATE (Marco window manager).
This is a well known buggy pattern that I've seen heaps of times :(
Instead of doing a save/restore of window geometry, the geometry should be saved but when restoring, a move+resize needs to be done instead.

**Comment by mwcarew** [comment]
Having a similar issue but on Windows. Window offsets from the bottom on launch.

https://gyazo.com/c90d6882384da9a5e83c7fe9eabe9be9

**Comment by bpasero** [comment]
@a1291762 @mwcarew still happening?

**Comment by mwcarew** [comment]
@bpasero Still happening here. Turned off Aero Snap in Windows to make sure that wasn't it.

**Comment by a1291762** [comment]
Still happening to me.

vscode 1.20.1-1518535978 on Ubuntu 14.04 running MATE.

Here's 2 screenshots demonstrating the window movement.

![screenshot47](https://user-images.githubusercontent.com/327162/37122496-837a051c-22ac-11e8-8fc8-d7f248da944f.png)
![screenshot48](https://user-images.githubusercontent.com/327162/37122499-85cdb066-22ac-11e8-8996-8f7cdfff45d0.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by mwcarew** [comment]
@bpasero I'm no longer having this issue on Windows 10 /w Aero Snap and the most current stable version of VS Code.
