### ISSUE TITLE
Rearranging Tabs by Dragging is Ambiguous

### ISSUE THREAD

**Issue by karai17** [Microsoft/vscode#38572]
- VSCode Version: 1.18
- OS Version: Fedora 26

Steps to Reproduce:

1. Open several tabs
2. Drag one tab to be re-positioned

Reproduces without extensions: Yes

When attempting to organise tabs by dragging and dropping them, sometimes the drop is cancelled and the tab goes back to where it originally was. This happens more often than not for me, and it can take two or three attempts to have a tab actually move. I think the issue stems from there being no hinting for where the tab will land. My intuition tells me that I should place my cursor between the two tabs I want my tab to be placed between but this doesn't always seem to be the case. My next intuition is that if I drag a tab on top of another tab, it'll be pushed to the side where my cursor is located (within left 50% of tab, it gets added before tab, right 50% it gets added to right of tab). Sometimes the tab, when it does decide to move, doesn't move to the correct position. Usually in this case, it moves before the tab I am dragging it on when I had wanted it to drop after.

I think this issue could be solved in two ways:

1. More predictable behaviour (take cursor position into account)
2. Display some sort of highlight/indicator to where the tab will be dropped.

**Comment by bpasero** [comment]
@karai17 can you somehow share a video of this works for you?

**Comment by karai17** [comment]
https://www.youtube.com/watch?v=RJas2pNcEyQ

You will note that in the video, several times my attempts to move a tab get eaten. I've also figured out that the tab always moves to the side of the highlighted tab that the moving tab is going to, so if I am moving tab 4 left and drop it on tab 2, it will slot between tab 1 and tab 2, even if I have my cursor over the right side of the tab indicating I want it to slot between tab 2 and tab 3.

**Comment by karai17** [comment]
And this is how I think it should work:

![image](https://user-images.githubusercontent.com/590332/32938073-57ef14b2-cb51-11e7-99d5-0585dfe645a2.png)

**Comment by bpasero** [comment]
@karai17 there seems to be a point where when you drag over an area, no drag feedback is showing up and when you manage to drop at that point, nothing happens. Is that true?

**Comment by karai17** [comment]
something like that, yeah.

**Comment by bpasero** [comment]
I tried to reproduce on Ubuntu at least and cannot.

**Comment by karai17** [comment]
That's odd. I've been dealing with this for a long time and only got frustrated enough to post about it now.

**Comment by bpasero** [comment]
@karai17 can you try with this insider build if you still see it: https://az764295.vo.msecnd.net/insider/0c60476e5167d4bdcf01cc48558b2e1faf0edae1/code-insider-1.19.0-1511417747_amd64.tar.gz

**Comment by karai17** [comment]
I opened four tabs and dragged them around and every single drag registered. :)

What did you change?

**Comment by bpasero** [comment]
@karai17 thanks for confirming, I pushed https://github.com/Microsoft/vscode/commit/018a151c9dac6ff88121f1f1018a28bf70defeb0 to disable any mouse events while drag and drop is happening. It looks like the child elements within a tab would all trigger a drag-leave event which briefly disables the DND operation entirely. On Linux this seems to have the worst impact, on Windows it would just shortly flicker and show a different cursor for a short while.
