### ISSUE TITLE
Some problems when open link file

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#38577]
- VSCode Version: November 2017 (version 1.19)
- OS Version: Win10

Reproduces without extensions: `Yes` / ~~No~~

***
forks from [Could not open link file with absolute path](https://github.com/Microsoft/vscode/issues/29735#issuecomment-344797449)

@mjbvz I open this new issue as your suggest, take a look, thanks.

![image](https://user-images.githubusercontent.com/12682063/32870786-812e6380-cab8-11e7-9353-d0c2ca0410a4.png)
![image](https://user-images.githubusercontent.com/12682063/32870847-ba9a2334-cab8-11e7-9bcf-6f02eb7b993f.png)

> `[test](./test#L10)` # relative, pass, `L10` only works with `preview` (if in `source`, it can jump to the filr, but stays in first line, so I think `L10` don't work with `source`, but at least, it not throw error)
> 
> `[test](/test#L10)` # worksapce absolue, pass with `source`, failed with `preview` (`failed` means throw an error and could not jump to the file)
> 
> ~~`[test](E:\MyProject\Project\sd\test#L10)` # system absolute, pass with `preview`, failed with `source`, `L10` only works with `preview`~~
> 

> `<link rel="stylesheet" href="./test#L10">` pass, `L10` works well
> 
> `<link rel="stylesheet" href="/test#L10">` failed.
> 
> `<link rel="stylesheet" href="/test">` pass. it means line jump only support for relative path.
> 
> ~~`<link rel="stylesheet" href="E:\MyProject\Project\sd\test">` `no provider`, it means system absolute path doesn't work with `html`~~
>

**Comment by mjbvz** [comment]
Fixed cases like `[test](./test#L10)` with  #40140 . You can try this in the VSCode 1.20 insiders builds once those start up

We don't provide clickable links for `<link>` element href's by default. This may be coming from one of the extensions you have installed 

Please let me know if you notice any other issues around links
