### ISSUE TITLE
API Request: Provide current size of viewport

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#38575]
A long time ago, when the VSCodeVim extension was just getting off its feet, these commands were implemented for scrolling to the top/bottom of the file: https://github.com/Microsoft/vscode/issues/11127

Those were great when we were trying to emulate vim by re-implementing every command. However, with a neovim based implementation, our needs change. 

We'd like to offload all implementation of vim commands to neovim, including commands like `ctrl-d`, `zz`, and even stuff like setting `scrolloff`. It's also important in order to sync highlighting better. In addition, there are a lot of vim windowing things that we'd like to simply offload. 

We are able to manipulate the VSCode viewport with the `revealLine` command. However, in order to sync the viewport between vim and VSCode, we need to know how big the VSCode viewport is.

All we would need is some kind of state (or complex command) we can query to get the current viewport size, in terms of (height x width).

@xconverge @rebornix 

Ideally, we'd have some kind of resizeViewport event, but that seems like too much to ask.

EDIT: More specifically, I don't care about the actual viewport size. What I care about is the amount of lines that we can currently see.

**Comment by OnlyLys** [comment]
This API would be fairly useful for an extension I'm writing that needs to know the initial state of the viewport so that the extension can restore it after doing its thing.

**Comment by rebornix** [comment]
We can already fetch the first visible line in the editor and `ctrl+d` is improved months ago (a PR from me).
