### ISSUE TITLE
VS Code PowerShell debugging fails in flight mode

### ISSUE THREAD

**Issue by markgossa** [Microsoft/vscode#38576]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.23.0
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

1. Put laptop into flight mode 
2. Create a new PowerShell file, save as .ps1
3. Press F5 or F8 to run the code

It just says "Starting PowerShell" in the bottom right and doesn't start it then times out.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#1105

**Comment by weinand** [comment]
Please file PowerShell issues against the PowerShell repository.
