### ISSUE TITLE
autocomplete is slow

### ISSUE THREAD

**Issue by okabbas** [Microsoft/vscode#38571]
auto complete code in vs code 1.18.0 for java and go etc ... is very slow . please fix it .

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swift|Kas|0.0.3
material-icon-theme|PKi|3.0.0
php-formatter|Sop|0.2.4
web-search|cre|0.0.5
vscode-html-css|ecm|0.1.8
javac-linter|fau|1.2.6
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
code-runner|for|0.8.3
StackSearchExt|gcr|0.0.2
vscode-power-mode|hoo|2.0.0
Go|luk|0.6.67
MagicPython|mag|1.0.12
web-browser|mas|0.0.1
Kotlin|mat|1.3.0
python|ms-|0.8.0
java|red|0.14.0
vscode-icons|rob|7.18.1
ayu|tea|0.10.0
python|tht|0.2.3
java-snippets|tus|0.0.1
vscode-java-debug|vsc|0.3.0
vscode-java-pack|vsc|0.2.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please file issues on the specific extensions involved, and include as many details as possible.
