### ISSUE TITLE
Running multiple code --add <path> && code --add <path> results in inconsistent behaviour

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#38570]
OS: macOS 10.13.2 Beta
VSC: v1.18.0

I clicked the "Restart to update..." menu entry that's displayed after clicking the gear icon in the activity bar. I previously had 3 VSC windows opened. This is what happened a few seconds later:

<img width="1440" alt="many vsc windows" src="https://user-images.githubusercontent.com/1812093/32924249-faf5e16a-cb3b-11e7-9df1-f2f326df280d.png">

It took about 15m for the computer to be usable enough so that I could kill Code.

I hope all those windows don't get restored now that I try to open it again 🤞

**Comment by fabiospampinato** [comment]
I once had the exact same problem with Chrome, perhaps it's a Chromium/Electron issue.

**Comment by fabiospampinato** [comment]
I cannot get it to start without it trying to open those gazillion windows. Isn't there any other way to fix this other than nuking it and reinstalling?

**Comment by bpasero** [comment]
@fabiospampinato did you ever see what those windows show when they are done loading? Are you using multi-root feature, maybe all those windows are untitled workspaces that you created that we now want to restore.

**Comment by bpasero** [comment]
@fabiospampinato yeah that makes sense to me. Can you try this with our insider build to see if it still reproduces? Maybe with a little less folders on startup to not go too crazy. 

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by fabiospampinato** [comment]
I've tried a few times, adding 6 roots, and I got either scenarios:

1. Not all roots added to the workspace, and upon restart 2 windows got restored (there was actually only 1 opened when I quit it, but 2 were restored anyway).
2. Everything works fine.

I'm not sure what the problem here is, but the implementation seems to make things a little unpredictable.

**Comment by bpasero** [comment]
Ok I should revisit this then. It does not seem to be fixed.

**Comment by bpasero** [comment]
@fabiospampinato I cannot reproduce the issue though on macOS. From the command line I run `code-insiders --add` with 8 folders in total and they all get added properly. For this to try I always make sure that code-insiders is quit with no workspace or folder opened (= empty workspace). Can you try exactly that setup?

**Comment by fabiospampinato** [comment]
@bpasero  I suspect you're executing `code-insiders --add path1 path2` instead of `code-insiders --add path1 && code-insiders --add path2`.

I can still reproduce this under the lasted Insiders build (89b158e11cb1c3fe94a3876222478ed2d0549fc8 2017-11-24T06:03:48.383Z), this is precisely what I do:

1. Open Code Insiders
2. Close every windows
3. Quit Code Insiders
4. Run `code-insiders /Users/fabio/Desktop && code-insiders --add /Users/fabio/Projects/vscode-commands && code-insiders --add /Users/fabio/Projects/vscode-github-notifications-bell && code-insiders --add /Users/fabio/Projects/vscode-install-vsix && code-insiders --add /Users/fabio/Projects/vscode-no-unsupported && code-insiders --add /Users/fabio/Projects/vscode-open-in-browsers && code-insiders --add /Users/fabio/Projects/vscode-open-in-finder && code-insiders --add /Users/fabio/Projects/vscode-open-in-gittower && code-insiders --add /Users/fabio/Projects/vscode-open-in-marketplace`
5. Notice that not all roots are added properly
6. Close every windows
7. Quit Code Insiders
8. Open Code Insiders
9. Notice that multiple windows are restored

**Comment by bpasero** [comment]
Yeah I am doing the same. There could still be a timing issue, after all I picked an arbitrary delay of 100ms to collect requests to add folders before doing it. 

@fabiospampinato remind me again why you cannot do this from a single command by appending a lot of folders to the "`--add`" command?

**Comment by fabiospampinato** [comment]
@bpasero I can't, in the integrated terminal via the `sendText` method,  because if it becomes too long it will get cropped https://github.com/Microsoft/vscode/issues/38137.

But even if I could do as you said l still think this should work as expected.

**Comment by bpasero** [comment]
@fabiospampinato yeah but my point is that this is a very unlikely use case for VS Code. Fixing this might make the normal behaviour get worse (the delay of 100ms is already ugly because it makes every invocation of `--add` artificially slower). I would rather want to optimise for the typical use case if I cannot find a better fix otherwise.

**Comment by fabiospampinato** [comment]
Sure, this is by no means an important problem. I'm just saying it would be nice to have it implemented properly, I've no idea if this is worth the time effort though.

**Comment by Tyriar** [comment]
Any reason we don't support `-a dir1 dir2 ...`?

**Comment by fabiospampinato** [comment]
@Tyriar I think it's already supported, but as mentioned [here](https://github.com/Microsoft/vscode/issues/38570#issuecomment-347101413) I couldn't use it because of [this](https://github.com/Microsoft/vscode/issues/38137).
