### ISSUE TITLE
Dealing with Tabs and Split Views

### ISSUE THREAD

**Issue by karai17** [Microsoft/vscode#38573]
- VSCode Version: 1.18
- OS Version: Fedora 26

The current UX of the split view system has two specific annoyances for me:

1. Right-clicking a tab does not give the option to move it to a split view. It would be really handy if there were options to move it to an existing view (move to next/previous view) or to move it to a new view.
2. When clicking the Split View button, it creates a copy of the currently selected tab and adds it to the new view. I think a more preferred behaviour would be to move the existing tab to the new view instead of having two of the same file open. About 95% of the time I open a split view, I want the file to be open exclusively in the new view. I think only once or twice have I actually opened a file in two different views to look at different parts of the same file.

The first issue is the more frustrating one since it requires me to do several clicks to get the setup I want, though both of these being changed would be great.

**Comment by bpasero** [comment]
This requires empty editor groups imho: https://github.com/Microsoft/vscode/issues/2755

**Comment by bpasero** [comment]
Extensions can add to the tab context menu. As for the other request, please add your vote to #2755.
