### ISSUE TITLE
Cannot open directories in UNC paths by the command `code`

### ISSUE THREAD

**Issue by tats-u** [Microsoft/vscode#38587]
- VSCode Version: 1.18.0
- OS Version: Windows 10 1709 17025.1000 (Insider Preview Slow ring)

Steps to Reproduce:

1. Open PowerShell
2. `Set-Location` to any UNC paths
3. Run `code` with any arguments

Reproduces without extensions: Yes

e.g.

```
PS C:\users\user> cd \\address.to.nas\directory
PS Microsoft.PowerShell.Core\FileSystem::\\address.to.nas\directory> code .
'\\address.to.nas\directory'
CMD.EXE was started with the above path as the current directory. UNC paths are not supported. Defaulting to Window directory.
```

Cannot open the directory in Visual Studio Code.  This is because `code.cmd` is a batch script of CMD, which does not support UNC paths.  You have to make a PowerShell script named `code.ps1` that behaves like `code.cmd` to solve it.

**Comment by Tyriar** [comment]
FYI @joaomoreno
