### ISSUE TITLE
VSCode crashes when opening a particular file

### ISSUE THREAD

**Issue by yleflour** [Microsoft/vscode#3858]
Hello,

My Visual Studio Code crashes when I try to open the following file (in the zip) and I have absolutely no idea why. I just tested on one of my coworker's computer and his version crashed too. I'm using the latest (February) release of VSCode on MacOSX (and so is my colleague).

[button.jade.zip](https://github.com/Microsoft/vscode/files/163401/button.jade.zip)

**Comment by weinand** [comment]
@alexandrudima on OS X VS Code freezes when trying to open the jade file.

**Comment by yleflour** [comment]
@alexandrudima I need to add that only this particular jade file makes VS Code freeze. I could open every other jade file in the project without any issue.

**Comment by alexandrudima** [comment]
@yleflour I can reproduce on Windows too. Thank you for filing this!

**Comment by alexandrudima** [comment]
I've tracked it down to right before calling `onig_search` with the regexp `(mixin\s+)([\w-]+)(?:(\()((?:[a-zA-Z_]\w*(?:,\s*)?)*)(\)))?$` on the first line `mixin blockBtnRubric(link,libelle_line1,value_line1, libelle_line2,value_line2,picto )`

**Comment by alexandrudima** [comment]
Using https://regex101.com/#pcre with that regex and that string errors with `Catastrophic backtracking`

**Comment by alexandrudima** [comment]
Looks like it is indeed an issue with the grammar davidrios/jade-tmbundle/issues/68

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by alexandrudima** [comment]
fyi @egamma stable candidate
