### ISSUE TITLE
Typing becomes unusably slow

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#38586]
- VSCode Version: 1.18
- OS Version: Win10

Steps to Reproduce:

1. Use VS Code for editing.

Bug: When editing, the CPU usage of Code.exe on 1 thread goes to 100% and typing becomes unusably slow. I have to restart VS Code to fix it, but then then later it starts to repro again. This only started reproing in the past day or so. Pressing enter on a line takes 3 seconds or so to process, i.e. editing becomes unusable. I used the Toggle Developer Tools to capture a performance snapshot, but it completely froze after interacting with the UI so I had to terminate Code. It said most of the processing was in Scripting. The screenshot shows me just pressing the Enter button once. Let me know if there's a better way to diagnose what is going wrong.

![image](https://user-images.githubusercontent.com/19859882/32931438-101360a4-cb19-11e7-9951-d155ed09cc90.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Can you save the profile and upload it?

**Comment by sean-mcmanus** [comment]
How do I save the performance profile info? I was searching for a way to save the performance info when the entire UI permanently froze (the screenshot is of the frozen UI) and I had to restart it.

**Comment by roblourens** [comment]
I think you can right click on the UI and use "save profile"

**Comment by sean-mcmanus** [comment]
It didn't repro today with 1.18.1. Maybe it's fixed? You can close this and I could re-activate if I get another repro.

**Comment by alexandrudima** [comment]
@sean-mcmanus @roblourens  Here is how to do a CPU profile and save it:

---

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the three dots burger menu
* Choose `More Tools > JavaScript Profiler`
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it

![kapture 2017-10-21 at 13 02 25](https://user-images.githubusercontent.com/5047891/31851158-30fd860a-b660-11e7-9018-661394adb754.gif)
