### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by pradeepk1905** [Microsoft/vscode#38583]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
project-manager|ale|0.23.0
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.3
minify|Hoo|0.3.0
debugger-for-chrome|msj|3.5.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Need more details.
