### ISSUE TITLE
Minor selection highlight display glitch for multiline selection

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#38591]
- VSCode Version: Code - Insiders 1.19.0-insider (34c44f872c177d6f9439706418f8fe49bf125d08, 2017-11-17T06:08:25.346Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

---

Steps to Reproduce:

1. Create a txt file:

```

a
```

 (The first line is blank)

2. Put cursor at end of `a` and select `a` and up to the line above

**Bug**

<img width="203" alt="screen shot 2017-11-16 at 11 32 06 pm" src="https://user-images.githubusercontent.com/212305/32935879-dffc6678-cb26-11e7-959a-85bf2095c66c.png">

The selection highlight has a small break between the two lines

**Comment by rebornix** [comment]
@mattbierner nice catch!

We are trying to compare `typicalHalfwidthCharacterWidth` (the width of eol) and the width of a single character. Several places I noticed that can make them not equal

* HorizontalRange round width/left
https://github.com/Microsoft/vscode/blob/9f597f95556b087375d67083eac9d60cfe9d1646/src/vs/editor/common/view/renderingContext.ts#L104-L114
* Pixel offset cache stored width/left as Int32 https://github.com/Microsoft/vscode/blob/f031f5ea22d521a3a55ac304200b72828055e953/src/vs/editor/browser/viewParts/lines/viewLine.ts#L388 
* Float number calculation may lose precision. The result is unlikely equal to `typicalHalfwidthCharacterWidth` https://github.com/Microsoft/vscode/blob/f031f5ea22d521a3a55ac304200b72828055e953/src/vs/editor/browser/viewParts/lines/rangeUtil.ts#L105-L109

**Comment by alexandrudima** [comment]
After:

![image](https://user-images.githubusercontent.com/5047891/38896700-c21548f2-4293-11e8-82ee-6e70bae55960.png)
