### ISSUE TITLE
Wakatime plugin stuck at wakatime initializing...

### ISSUE THREAD

**Issue by developerpruthvi** [Microsoft/vscode#38590]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 3.10.0-514.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-wakatime|Wak|1.1.21

---

Steps to Reproduce:

1. Launch VS Code
2. Check Wakatime Status Icon , it is stuck at "Wakatime initializing..."

Reproduces without extensions: Yes/No

**Comment by alanhamlett** [comment]
Let's move this issue to the extension's repo since it's not a problem with VSCode itself:
https://github.com/wakatime/vscode-wakatime
