### ISSUE TITLE
Version Control icon badge

### ISSUE THREAD

**Issue by mgesmundo** [Microsoft/vscode#38596]
VS Code opened from a folder inside a git project has a wrong version control badge icon.

- VSCode Version: 1.18.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. mkdir project
2. cd project
3. git init
4. mkdir src
5. cd src
6. touch README
7. git add .
8. code --disable-extensions . // open VSCode form src folder
9. git commit -m"Commit"

VS Code show the README file as uncommitted.

Reproduces without extensions: Yes

All the best.

**Comment by joaomoreno** [comment]
I followed this step by step and this didn't reproduce. Don't forget to focus VS Code after you run `git commit`. VS Code won't refresh its git state unless the window is focused.

**Comment by mgesmundo** [comment]
Hi João,
thank you for your super fast reply!
I removed all installed plugins, installed again and after a reboot now it works.
Thank you for your time!
