### ISSUE TITLE
Search hint in collpased scope

### ISSUE THREAD

**Issue by jawensi** [Microsoft/vscode#38593]
- VSCode Version: 1.18.0 , 1.18.1
- OS Version: Windows 7

Steps to Reproduce:

1. Search for an item in a collapsed scope 
2. In prev version there would be a visual hint indicating result inside a collpased scope (where the ellipsis is). 

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
It expands folded code sections containing matches, when doing a find. Is that not what you see?

**Comment by jawensi** [comment]
If you do a find and the match is located in a collapse section, that section uncollpase. However in previus version there was visual hint indicating result inside a collapased section. 

The attach picture (version 1.16.0 ) show the search hint in a collapse section (red sign):

![image](https://user-images.githubusercontent.com/6216293/32993486-25412e92-cd59-11e7-95e1-b9710a52dd75.png)

The word searched is 'MapLayer'

**Comment by roblourens** [comment]
I don't see that in 1.16. That looks more like a bug than a feature. Actually supporting something like this in general - showing a hint when there's a hidden decorator in a collapsed section - would be difficult to support. So I don't plan to implement it any time soon.
