### ISSUE TITLE
Extension reload state is wrong when using --disable-extensions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38597]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/22350/32938820-bc179c94-cb7d-11e7-8868-0cf60efd23d8.png">

**Comment by ramya-rao-a** [comment]
I still see the "Reload" button on the disabled extensions in the Insiders build

**Comment by sandy081** [comment]
@ramya-rao-a Fixed

**Comment by ramya-rao-a** [comment]
Verified by running from source
