### ISSUE TITLE
Terminal resize cursor still appears even though terminal window is closed

### ISSUE THREAD

**Issue by beingbishwa** [Microsoft/vscode#38592]
I really liked the update of VSCode where terminal can be aligned vertically. But, even after the terminal is closed, still if we hover mouse over the place where the boundary of terminal was, we could see resize window cursor. This isn't causing any disturbances but noticed it. Can be the minor bug but can't really look over it.

**Comment by isidorn** [comment]
This is fixed in latest vscode. Please get the latest vscode where this is fixed. THanks
