### ISSUE TITLE
What is the compatibility of Razor with VSCode and Intellisense?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#386]
I'm surprised that so few people have made any comments regarding the lack of Razor intellisense support. I don't totally understand what makes this difficult. I will likely ask the folks over at Razor to see if they have anything to say, but I thought I'd ask here first because it's this tool that doesn't have the intellisense for it.

**Comment by chrisdias** [comment]
This is a known limitation, the ASP.NET guys plan on working on this soon.
