### ISSUE TITLE
CLI: code --install-extension should show reload button if vscode is open

### ISSUE THREAD

**Issue by hilleer** [microsoft/vscode#38607]
- VSCode Version: `1.18.1`
- OS Version: macOS High Sierra 10.13.1

If you use the CLI command `code --install-extension <extension>` in a terminal while vscode is open, it would be very useful that vscode realise that an extension have been updated/installed - and so shows the "reload" button, so you don't have to manually close and open vscode in order for the extension to work. Just like if you updated or installed an extension through vscode itself.

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@hilleer We do not allow accessing UI buttons directly but instead you can use commands. In this case, you can always run the command to reload the window `workbench.action.reloadWindow`

Could you please update the summary and description for the issue 1 you mentioned. Otherwise it looks like a request to provide an API which might get closed because of above solution :)

**Comment by hilleer** [comment]
@sandy081 thanks for your answer. It might be a solution to my specific case - but I do believe a solution to my first issue would be of use. 

If you use the command `code --install-extension <extension>` in a terminal while vscode is open, it would be very useful that vscode realise that an extension have been updated/installed - and so shows the "reload" button, so you don't have to manually close and open it in order for the extension to work. Just like if you updated or installed an extension through vscode itself.

**Comment by sandy081** [comment]
@hilleer Sure, I consider your first issue and can you please update the issue summary and description accordingl

**Comment by hilleer** [comment]
@sandy081  updated. Is it clear? :-)

**Comment by sandy081** [comment]
@joaomoreno Looks like, cli process is not using the shared process to install/uninstall extensions..  Was there any reason? 

Hence, VS Code windows are not getting notified when an extension is updated from CLI.

**Comment by joaomoreno** [comment]
Yeah... the CLI process runs the code itself.

One idea can be that the CLI process tries to talk to a running shared process and only attempt to do it itself if that connection fails.

**Comment by sandy081** [comment]
Sure.. That's my idea too. Let's do it tomorrow :)
