### ISSUE TITLE
Add feature to describe keybinding by pressing said key(s)

### ISSUE THREAD

**Issue by tger** [Microsoft/vscode#38602]
See [this Stackoverflow question](https://stackoverflow.com/questions/47304223/how-can-i-find-what-command-a-keybinding-is-bound-too-easily). The answer given there requires typing out the keybinding to find what it is bound too. Would it not be much nicer if I can just press the keys? Emacs "Ctrl-h K" is really convenient.

Bonus points if the description I get also includes the documentation for the command (and a link to the source of the command should the documentation be missing or insufficient). Again, see Emacs for inspiration.

**Comment by sandy081** [comment]
Duplicate of #57935
