### ISSUE TITLE
xhr failed when trying to add extention

### ISSUE THREAD

**Issue by harkamals** [Microsoft/vscode#38600]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. open .go file > install extention > fail
2.

**Comment by sandy081** [comment]
@harkamals Can you please provide more info of how to reproduce it. Above steps are not helpful. Any screenshots will be great.
