### ISSUE TITLE
Icon is inadequately differentiable from VSTS icon

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#38601]
- VSCode Version: 1.18.1
- OS Version: 16299.4

Steps to Reproduce:

1. Install VS Code
2. Install VSTS
3. Pin both icons to Start Bar

Reproduces without extensions: Yes
![capture](https://user-images.githubusercontent.com/5498936/32940267-e9b8bdcc-cbcd-11e7-8a16-5fe36271dee3.PNG)

An icon is supposed to be iconic. If it looks like something else it can't do that.

**Comment by bpasero** [comment]
This is "as designed", see https://code.visualstudio.com/blogs/2017/10/24/theicon
