### ISSUE TITLE
Command line command to install wont install if newer version already installed

### ISSUE THREAD

**Issue by hilleer** [Microsoft/vscode#38609]
- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1

### Steps to Reproduce:

1. Have two identical vsix files of an extension, but with different version tags. I made two test ones here: (https://github.com/hilleer/vscode-install-cli-test-vsixs)[https://github.com/hilleer/vscode-install-cli-test-vsixs]
2. Install the latest (version `1.1.0` from the example ones`) from within vscode or from the command line.
3. Reload / check that the extension is installed (`1.1.0`)
4. Install the old version (version `1.0.0` from the example ones) from the command line (`code --install-extension <path to vsix file>).
5. Reload vscode, and check the version of the extension - still the version of the first (newest) installed version.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
We generally do not support installing outdated extensions from gallery. But I think it makes sense to support it for vsix installations.

If you are trying to install an older versions using vsix, now, we show a confirmation asking to override the newer version with older version.

**Comment by sandy081** [comment]
@joaomoreno As part of this fix, I had to flip the order of extensions clean up.  Now, I remove first obsolete extensions and then remove outdated extensions 4fb98ff812570dd64d966614706befddc602f349. Want to confirm if the order matters or not.

**Comment by joaomoreno** [comment]
No reason! 👍

**Comment by hilleer** [comment]
Thanks for implementing this! 👍

**Comment by ramya-rao-a** [comment]
@sandy081 Verified that this works after confirming the override.
But when I press 1 for Cancel, there is a callstack printed out

![image](https://user-images.githubusercontent.com/16890566/33634433-fcb7cd60-d9c8-11e7-9a4a-9b7d6188f682.png)

**Comment by sandy081** [comment]
Good catch @ramya-rao-a 

Fixed.

![image](https://user-images.githubusercontent.com/10746682/33652291-1d44cde4-da69-11e7-9f6a-5d59cb5835aa.png)
