### ISSUE TITLE
Feature request: Generated code should follow the ts-lint rules defined in the project

### ISSUE THREAD

**Issue by nseba** [Microsoft/vscode#38603]
It would be very useful if refactoring actions such as declare member variable, implement interface/abstract class etc. would take into account the relevant ts-lint rules. At a minimum the following rules can be enforced:
* `member-access` - add explicit `public | private` modifier to newly generated members
* `member-ordering` - add the members in their right place (for example public fields after existing public fields, methods after existing public methods etc.)
* `promise-function-async` - automatically add the `async` modifier.
* `quotemark` - use the right quotes/single quotes for automatic import declarations

As a small side note implementing abstract base class refactoring should also add automatically the `async` modifier if it exists on the abstract member.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20107
