### ISSUE TITLE
namespace sense problems about cpptools in version 0.14.2

### ISSUE THREAD

**Issue by littlepiece** [Microsoft/vscode#38606]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.14.2

/////////////////////////////////////////////

describle the problem as follow:
cpptools can't sense E_GATEWAY_ERR in a AA::E_GATEWAY_ERR format when AA is a namespace and E_GATEWAY_ERR is a enum value in some enum object such as 
```
namespace AA{
enum ErrorCode{
    E_GATEWAY_ERR = 500,
    E_END
};
};
```
//////////////////////////////////////////
thanks for your attention

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#1261
