### ISSUE TITLE
Bluebirdjs Exception has occurred: Error

### ISSUE THREAD

**Issue by osmanraifgunes** [Microsoft/vscode#38619]
VSCode Version: 1.18.1
 OS Version: windows 10 enterprise *64

Steps to Reproduce:

1. Create a simple nodejs application.
2. Install bluebird.js package. (`npm install bluebird`)
3. Debug application.

I get `Exception has occurred: Error` every time when trying to debug application.

There is an opened [issue ](https://github.com/petkaantonov/bluebird/issues/1433) at bluebird.js repo but they say it is bug of visual studio code. [Another issue](https://github.com/petkaantonov/bluebird/issues/1418).

Discussed problem at [stackoverflow ](https://stackoverflow.com/questions/40153214/bluebird-throwing-exception-at-source-code) and it seems that the code block at bluebird.js is required and normal.

It is not preventing my code from running properly, but it makes debugging very hard. Every time I get a lot of exceptions before run. 

Reproduces without extensions: Yes

**Comment by weinand** [comment]
What exceptions are you seeing?
Are they expected and handled in code?
Have you tried to filter the exceptions here:
![2017-11-17_15-01-39](https://user-images.githubusercontent.com/1898161/32950869-3c992264-cba8-11e7-827c-6317cf8560b7.png)

**Comment by osmanraifgunes** [comment]
Yes. Removing all exceptions check helped. It makes it more usable. Thank you.
