### ISSUE TITLE
GoLang code completion with brackets and parameters.

### ISSUE THREAD

**Issue by Karthik1337** [Microsoft/vscode#38611]
- 1.18.1:
- Ubuntu 17.10:

I'm using vs code for golang development. Currently, the suggestions are showing function name and info for autocompletion. While selecting from the list it only adds function name like `log.Println`. I would like to suggest code completion like `log.Println(param)`. Another example for multiple parameter function `router.POST(path, handle)`.  If autocompletion like this it's become useful to the developer.

**Comment by ramya-rao-a** [comment]
You can get that by adding the setting `"go.useCodeSnippetsOnFunctionSuggest": true` in your settings file.

This repo is for VS Code. For questions/issues/feature requests related to Go when using the Go extension, please log the issue at the repo for the Go extension. https://github.com/Microsoft/vscode-go

**Comment by Karthik1337** [comment]
Thanks:)
