### ISSUE TITLE
Switching between explorer and extensions closes opened file (preview issue)

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38618]
VSCode 1.18.1
Windows 7

1. open a workspace
2. select a file from the file browser pane (note it appears in italics)
3. switch to the extensions view
4. select an extension (note that it also appears in italics and the previously open file is gone)
5. switch back to explorer view (note that both the extension and the previously open file are gone)

My expectation is that the view are independent of each other and should maintain their own state. The extension view going away on the switch is non-impactful. The file being closed is.

**Comment by bpasero** [comment]
Closing as designed, we decided to restore the last active file when going back to the explorer.
