### ISSUE TITLE
C# highlight 'namespace' and 'class' in different color

### ISSUE THREAD

**Issue by klirium** [Microsoft/vscode#38610]
Suppose we have this code:
```
using System;
using System.Collections.Generic;

namespace ConsoleApp {
    class Program {
        static void Main (string[] args) {
            System.Collections.Generic.List<string> list = new List<string> ();
        }
    }
}
```
in the text editor when we type **System.Collections.Generic.List**, we actually have two types of entities in one statement: **System.Collections.Generic** - is a namespace, and **List** - is a class. It would be nice to have ability to distinguish this two types via color highlighting. For example in Visual Studio we can highlight System.Collections.Generic in black and List in strong purple. Even more having Resharper installed and **using System.Collections.Generic;** statement at the top of the file, it could be marked as redundant and removed via refactor tools. But in VS Code if we call "Developer: Inspect TM Scopes" it will show us that these two entities have the same types:
- storage.type.cs
- regions.namespace.cs.extensions
- source.cs

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#87
