### ISSUE TITLE
Domain name of update site

### ISSUE THREAD

**Issue by mg-development** [Microsoft/vscode#38615]
What is the domain name of update server 2.17.158.186? 
Im connecting to internet cross proxy server and my proxy provider setup proxy white list as mentioned in https://code.visualstudio.com/docs/setup/network#_proxy-server-support, but there is no page like 2.17.158.186. For my provider is like "total-random-potentialy-dangerous-unknown-ip" page..
Or maybe could I download these updates and install offline?

- VSCode Version: 1.19-insiders
- OS Version: Wondows 7 6.1.7601

> Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
> Failed at stage: downloadPackages
> Error: connect ETIMEDOUT 2.17.158.186:443
> 	at Object.exports._errnoException (util.js:1050:11)
>	at exports._exceptionWithHostPort (util.js:1073:20)
>	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

Regards,
MG

**Comment by joaomoreno** [comment]
It's `vscode-update.azurewebsites.net`.
