### ISSUE TITLE
Incorrect syntax highlighting with PHP inside HTML comment

### ISSUE THREAD

**Issue by JuanFerrer** [Microsoft/vscode#38614]
- VSCode Version: 1.18.1
- OS Version: Windows 10, 64bit

Steps to Reproduce:

1. Create PHP file
2. Add some HTML code with PHP code inside it

``` php
<?php
   echo "This is a PHP file ";
?>
<!DOCTYPE html>
<div> An HTML comment
    <?php 
        echo " with PHP code inside it";
    ?>
</div>
```

3. Comment out the HTML section (even GitHub shows strange behaviour)

``` php
<?php
   echo "This is a PHP file ";
?>
<!DOCTYPE html>
<!-- <div> An HTML comment
    <?php
        echo " with PHP code inside it";
    ?>
</div> -->
```

![phpinhtml](https://user-images.githubusercontent.com/22564520/32945933-447d165e-cb8d-11e7-8e90-2d3d4b0a8be0.PNG)

4. Observe that the HTML looks commented out, but the PHP (inside the commented out tag) still received syntax highlighting. Confusing, since that PHP code won't run. Expected to see the whole tag (with the contained PHP) as a comment.

Note that if the file is an HTML, the comments look as expected:

![phpinhtmlonhtml](https://user-images.githubusercontent.com/22564520/32945979-8584569e-cb8d-11e7-9af0-b662bda656c9.PNG)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I tested it and that code will run, PHP doesn't know what an HTML comment is. I think this is correct.
