### ISSUE TITLE
VSCode Helper uses ~100% CPU

### ISSUE THREAD

**Issue by ianp** [Microsoft/vscode#38622]
- VSCode Version: Code - Insiders 1.19.0-insider (91a2020698b5220e50f60682724927a810608356, 2017-11-16T06:10:28.922Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.22
prettier-vscode|esb|0.24.0
vscode-yarn|gam|1.3.0
sass-indented|rob|1.4.5
elm|sbr|0.15.1
mark-jump|spy|0.7.2
---

Steps to Reproduce:

1. Launch VSCode
2. Issue normally occurs with 10–15 minutes of starting to use code

After a while VSCode becomes very slow (e.g. to save files), Intellisense and format on save cease to function, and one of the helper processes can be observed using almost 100% CPU. The offending process also seems to be going crazy reading from disk (see attached screenshot).
<img width="801" alt="screen shot 2017-11-17 at 13 27 02" src="https://user-images.githubusercontent.com/103420/32949611-675a44b8-cb9b-11e7-8a47-5c18ae06e9af.png">
<img width="575" alt="screen shot 2017-11-17 at 13 28 43" src="https://user-images.githubusercontent.com/103420/32949612-676f6a0a-cb9b-11e7-9f21-b8e62e4a1cd1.png">

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Please give us more detail about the arguments of that process as described here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#questions. Thanks

**Comment by ianp** [comment]
It happened again, here's the offending process (via `ps -ef`)

`501 42103 42096   0  1:57pm ??         6:41.19 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --nolazy --inspect=9000 /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=extensionHost`

I'll try some of the steps in that document and get back to you.

**Comment by jrieken** [comment]
Ok. Likely one of your extensions that is going crazy... Try what is described here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process

**Comment by ianp** [comment]
Looks like it's a problem trying to get the content marks, I'm attaching a CPU profile report, and also a screenshot of the heaviest calls
<img width="879" alt="screen shot 2017-11-17 at 14 18 04" src="https://user-images.githubusercontent.com/103420/32951586-53a90c68-cba2-11e7-922b-0fd952ab3d7c.png">
[CPU-20171117T141717.cpuprofile.gz](https://github.com/Microsoft/vscode/files/1482586/CPU-20171117T141717.cpuprofile.gz)

**Comment by jrieken** [comment]
Yep, this caused by the `mark-jump` extension. It seems to search for all files and run some regular expression on all of them... Please follow up with the extension owner.

<img width="1459" alt="screen shot 2017-11-17 at 17 13 58" src="https://user-images.githubusercontent.com/1794099/32956987-c5737438-cbba-11e7-80d8-c277ad6c3909.png">

**Comment by ianp** [comment]
Ah, cool, will do. Thanks!
