### ISSUE TITLE
Feature Request: Add scroll helper on indent line after some delay

### ISSUE THREAD

**Issue by byanjiong** [Microsoft/vscode#38629]
**Background:** After coding for hours, and dealing with long file, especially with multiple-level indent file... life become uneasy...

**Feature Request:**
1. Hover on the indent line
2. Wait for 0.5 second
3. Two tiny button appear around the cursor, "^" and "v", i.e. (going top), and (going down).
4. Click on "^", document will scroll automatically to the beginning of the current indent line, within 0.5 second, no matter how long the line is.

![Cursor](https://i.imgur.com/Ws128eU.png)

**Comment by CoenraadS** [comment]
If you don't mind keyboard based controls, you can try this: https://marketplace.visualstudio.com/items?itemName=CoenraadS.column-jump
