### ISSUE TITLE
updating can't find new version although update checker does find a new one

### ISSUE THREAD

**Issue by GameEngine1** [Microsoft/vscode#38624]
- VSCode Version: 1.18.0-1510145176
- OS Version: Xubuntu 16.04 x64

atm. when you launch CSCode it says there's an update, when you update it says it already has the newest version. restarting VSCode, and it's the same.
I think it's not updating correctly.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
It's on the way https://github.com/Microsoft/vscode/issues/38617

**Comment by GameEngine1** [comment]
fixed
