### ISSUE TITLE
Allow to place new StatusBarItems between default items of the status bar

### ISSUE THREAD

**Issue by Otiel** [microsoft/vscode#38620]
I was playing with the `priority` value of a [`StatusBarItem`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namestatusbaritemaspan-classcodeitem-id1098statusbaritemspan)s added to the status bar by an extension, and noticed that I couldn't choose the exact spot of the `StatusBarItem`, when its `alignment` is set to [`right`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namestatusbaralignmentaspan-classcodeitem-id1095statusbaralignmentspan). Setting a priority of `100` places the item on the left of all default items, while a priority of `99` places the item on the right of all default items (except for the "tweet feedback" button).

![image](https://user-images.githubusercontent.com/3851902/32948638-4511c85e-cba0-11e7-9c5e-5c6a0a083feb.png)

Would it be possible to make it so we can place new `StatusBarItem`s between the default items "Go to Line", "Indentation", "Select Encoding", "Select End of Line Sequence" and "Select Language Mode"?

**Comment by bpasero** [comment]
This landed via https://github.com/microsoft/vscode/commit/9276768aec0b6a1e85584c18bda8911df45d2959

The editor related entries still try to be close to each other, the final numbering scheme is visible in https://github.com/microsoft/vscode/blob/9276768aec0b6a1e85584c18bda8911df45d2959/src/vs/workbench/browser/parts/editor/editorStatus.ts#L278 by looking for the number passed into `this.statusbarService.addEntry`
