### ISSUE TITLE
List suffers from 1000 paper cuts

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38628]
Setting nothing in an empty list

<img width="1079" alt="screen shot 2017-11-17 at 16 25 15" src="https://user-images.githubusercontent.com/1794099/32954650-02c0137a-cbb4-11e7-921b-3f5e89be8c31.png">

**Comment by joaomoreno** [comment]
Fixed pretty much all `forEach` calls. Left `map` calls since I actually need those arrays.

Also, returning early if the `splice` call is a no-op. That fixes those 4.7ms when clearing the list on startup.
