### ISSUE TITLE
Slow editor contributions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38625]
Editor contributions like *IntelliSense*, *Find*, the *Debug Hover* etc are created when a new code editor widget is being created. Unfortunately they also slow down the editor creation. That's often due to them doing too much, esp. creating their UX eagerly. Proposed change is to create their UI only when being invoked, e.g. create the IntelliSense box only when Ctrl+Space is hit.

<img width="937" alt="screen shot 2017-11-17 at 15 05 12" src="https://user-images.githubusercontent.com/1794099/32951032-bdb80c48-cba8-11e7-9b2b-ae0b22271b45.png">

**Comment by isidorn** [comment]
@jrieken great find, thanks for this

**Comment by rebornix** [comment]
It's pretty useful to practise what I just learnt from @jrieken 's performance training.

![image](https://user-images.githubusercontent.com/876920/32966140-ad3b9a44-cb8d-11e7-9fef-9aa249a9b8a7.png)

Lazy load Find Widget and Parameter Widget.

**Comment by rebornix** [comment]
Delay Hover Widget creation as well, save around 10 to 20ms in total by postponing Find, Hover, Paramater.

**Comment by jrieken** [comment]
@rebornix Watch out with https://github.com/Microsoft/vscode/commit/fb90f23d6b0c139bdc89cbe087c30871591893b6... I will stop parameter hints as the widget creates the model that causes it to show/hide type

**Comment by rebornix** [comment]
@jrieken can you elaborate more on this? I didn't postpone creation of ParameterHintWidget as it needs to create the model. ParamaterHint model and widgets are created and binded at creation time and when the parameter hint is triggered by `type`, we then create the DOM nodes.

Current behavior of typing after reloading:
![render](https://user-images.githubusercontent.com/876920/33029692-208ca44c-cdce-11e7-853e-317ff81d64d6.gif)

**Comment by jrieken** [comment]
I am sorry, mis-read that... I stumbled over a different problem here. Things actually work. Closing, editor is fast!
