### ISSUE TITLE
Syntax selection shortcut: typing `md` does not auto-suggest markdown

### ISSUE THREAD

**Issue by muttoni** [Microsoft/vscode#38627]
- VSCode Version: 1.18.1
- OS Version: macOS

Steps to Reproduce:

1. <kbd>command</bkd> + K + M
2. type `md`
3. markdown syntax is not suggested.

If I do the same thing with `js`,  both **J**ava**S**cript & **JS**ON are suggested

**Comment by jrieken** [comment]
This isn't the IntelliSense match logic but something else

**Comment by bpasero** [comment]
@muttoni works for me what are you doing differently?

![image](https://user-images.githubusercontent.com/900690/33056811-f611dc36-ce87-11e7-8231-dccdce2943b2.png)

**Comment by muttoni** [comment]
Try typing “md”, which is the file extension. Markdown will disappear

**Comment by bpasero** [comment]
We do not match fuzzy in pickers, closing as duplicate of https://github.com/Microsoft/vscode/issues/34088

**Comment by muttoni** [comment]
Then why does typing `js` highlight **J**ava**S**cript ? Is it the capitalization? Whereas typing `md` does not highlight **M**ark**d**own.

A quick solution would be to add the default file extension as a (hidden) match parameter (e.g. `.md`)
