### ISSUE TITLE
Workspace configuration should use relative paths

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/vscode#38630]
If I create a workspace file, it would be nice if by default code created paths that were relative, not absolute as absolute paths tend to incorporate platform-specific nuances.

**Comment by bpasero** [comment]
@atrauzzi are you talking about a *.code-workspace file for multi-root workspaces?

**Comment by atrauzzi** [comment]
That's correct.

**Comment by bpasero** [comment]
@atrauzzi but that should be the behaviour, the path will be relative if the location of the workspace file can be expressed as relative path. That is, we will not put a relative path in if we had to use ".." for the path. So it will only work if the workspace file is located in a parent directory.

Can you verify that happens for you?

**Comment by atrauzzi** [comment]
When I add directories to a workspace, it uses absolute paths. That's the best I can describe it. Had to go in and change them for relative.

**Comment by bpasero** [comment]
@atrauzzi can you give some steps to reproduce, e.g. what is the location of the saved workspace file and the location of the added folders?

**Comment by atrauzzi** [comment]
Workspace shares a common parent or in some cases grandparent to the added folders.  This implies a github-like `name/name` pair.

**Comment by bpasero** [comment]
@atrauzzi so would the relative path have to be expressed with ".." to get it right? We are not doing that, only if the workspace file is a true parent of any of the workspace folders.

**Comment by atrauzzi** [comment]
That seems like both an arbitrary requirement and also a glaring oversight. What reason is there to ever coerce someone into storing platform dependent paths in files that are likely to be committed to source control?

I don't think it's at all a stretch to assume that people are more likely to reference sibling repositories in a git-styled namespace structure than have a top down hierarchy that nests repositories under a main workspace one. Even still, it makes more sense to support both scenarios versus again, storing absolute paths. Even if the path between two repositories to their common ancestor is esoteric.

Also worth noting is that Visual Studio makes this same mistake and frankly it's just death-by-a-thousand-cuts horrible.  Why repeat mistakes of the past?

**Comment by bpasero** [comment]
I am closing this as not being very constructive.
