### ISSUE TITLE
terminal: I-Beam cursor shown in scroll bar

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#38632]
[Windows]
Please see the attached screenshot. Notice that an I-Beam cursor is shown over the scrollbar instead of an arrow cursor as is shown in the editor.

![image](https://user-images.githubusercontent.com/172399/32955168-7a3422f6-cbb5-11e7-8e8d-83ed81438277.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36397
