### ISSUE TITLE
Empty explorer is slow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38638]
* make the workbench show the open editors and a folder
* also make it show one editor
* start CPU profiling and reload
* 🐌 notice that `ViewsViewlet#updateView` takes ~100ms which is slow, esp given that the explorer is empty and that there is just a single entry in 'Open Editors'

<img width="784" alt="screen shot 2017-11-17 at 17 18 32" src="https://user-images.githubusercontent.com/1794099/32957338-b6e18512-cbbb-11e7-89ba-e72d84e721f2.png">

**Comment by jrieken** [comment]
Parts of this might be #37917 but that cannot be all as it's also slow when disabling touch support locally

**Comment by isidorn** [comment]
ViewsViewlet is the splitView component so also adding @joaomoreno

**Comment by joaomoreno** [comment]
@isidorn Please investigate first.

**Comment by isidorn** [comment]
After discussing this with @joaomoreno the issue here is that the tree is being slow since it just does too much stuff for this simple scenario.
I plan to fix this by updating the OpenEditors view to use the list widget.

**Comment by isidorn** [comment]
OpenEditors is now using the list, closing this.
ViewsViewlet now takes 54ms on my machine. Though explorer is still using the tree.

**Comment by joaomoreno** [comment]
@isidorn Awesome! ⚡️
