### ISSUE TITLE
TypeScript Died?

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#38634]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-npm|fkn|3.3.0
status-bar-tasks|Gua|0.2.1
typings-autoinstaller|jvi|1.2.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
partial-diff|ryu|0.5.0

---

Steps to Reproduce:

I am working a project that is purely Javascript. I don't know why this message pops up (I am not even running WebPack, just native es6 for Chrome v61
.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce if you disable all extensions? 

Also, please open the output panel and go to the `TypeScript` section. Are there any error messages in there?

**Comment by DrYSG** [comment]
I will try to do more tomorrow (sponsors are here today). But this is what I get when I open the console:

[Info  - 12:41:39 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:41:39 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:41:39 PM] Started TSServer
[Error  - 12:42:11 PM] TSServer exited with code: 3
[Info  - 12:42:12 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:42:12 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:42:12 PM] 'getSupportedCodeFixes' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:42:12 PM] Started TSServer
[Error  - 12:42:43 PM] TSServer exited with code: 3
[Info  - 12:42:43 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:42:43 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:42:43 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:42:43 PM] Started TSServer
[Error  - 12:43:14 PM] TSServer exited with code: 3
[Info  - 12:43:14 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:43:14 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:43:14 PM] Started TSServer
[Error  - 12:43:45 PM] TSServer exited with code: 3
[Info  - 12:43:45 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:43:45 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:43:45 PM] Started TSServer
[Error  - 12:44:17 PM] TSServer exited with code: 3
[Info  - 12:44:17 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:44:17 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:44:17 PM] Started TSServer
[Error  - 12:44:48 PM] TSServer exited with code: 3
[Info  - 12:44:48 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:44:48 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:44:48 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:44:48 PM] Started TSServer
[Error  - 12:45:20 PM] TSServer exited with code: 3
[Info  - 12:45:20 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:45:20 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:45:20 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:45:20 PM] Started TSServer
[Error  - 12:45:51 PM] TSServer exited with code: 3
[Info  - 12:45:51 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:45:51 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:45:51 PM] 'docCommentTemplate' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:45:51 PM] Started TSServer
[Error  - 12:46:23 PM] TSServer exited with code: 3
[Info  - 12:46:23 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:46:23 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:46:23 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:46:23 PM] Started TSServer
[Error  - 12:46:55 PM] TSServer exited with code: 3
[Info  - 12:46:55 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:46:55 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:46:55 PM] Started TSServer
[Error  - 12:47:26 PM] TSServer exited with code: 3
[Info  - 12:47:26 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:47:26 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:47:26 PM] Started TSServer

**Comment by mjbvz** [comment]
Thanks. Looks like the TSServer is indeed crashing. Can you please try looking in the TS Server logs to see if there are any error messages or stack traces that indicate what is causing the crash:

, please collect the TypeScript server logs to see if that has any leads:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Now go to the `TypeScript` section of the output window again and look for a line that looks:

```ts
[Info  - 3:17:45 PM] TSServer log file: /var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-xdcYW1/tsserver.log
```

4. Open the TServer log at that path

 If you are able to share the logs, I can also look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by DrYSG** [comment]
enclosed are the log files
[tsserver.log](https://github.com/Microsoft/vscode/files/1497394/tsserver.log)
[ti-25676.log](https://github.com/Microsoft/vscode/files/1497395/ti-25676.log)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20286

**Comment by DrYSG** [comment]
I am out of town at a conference in Orlando, and I don't have access here to my work computer. Can you wait a day or two till I can answer?
