### ISSUE TITLE
Bot is too eager to re-lock issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38631]
I'm fighting the bot in this issue here: https://github.com/Microsoft/vscode/issues/24989

The bot should also take "since it was last unlocked" into consideration before locking.

**Comment by mjbvz** [comment]
Two options:

* Don't auto lock issues if there has been some activity on in the past X days
* Try determining last lock time and don't re-lock issues based on this. Not sure if we can do this with the github API or not yet.

Also, obligatory:

![](https://imgs.xkcd.com/comics/cd_tray_fight.png)

**Comment by mjbvz** [comment]
Added updated to check that last updated time for the issue is > 3 days ago
