### ISSUE TITLE
Typescript Auto-Import does not work for click on suggestion

### ISSUE THREAD

**Issue by tobiasviehweger** [Microsoft/vscode#38636]
- VSCode Version: 1.18.1
- OS Version: Windows 10 FCU

Steps to Reproduce:

1. Start typing a valid typescript type name, which can be auto-imported, but is currently not imported
![image](https://user-images.githubusercontent.com/2111803/32956918-92f12ec4-cbba-11e7-9b35-42b400665681.png)

2. Click on one of the types - it's not imported automatically. This works if you press Tab or Enter

Would be great to have this on click as well, especially for long type names with the same beginning, a click is faster.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Simple repo for verification:

1. Create simple workspace with two files:

`a.ts`:
```ts
export const abc = 123;
```


`b.ts`:
```ts
const ab = 123;
ab|
```

2. Trigger suggestions in `b.ts`
3. The first suggestion shown should be for `ab`.
4. Click on the suggestion for `abc` without moving through the suggestion list

**Bug**
Auto import not triggered

**Comment by tobiasviehweger** [comment]
This is nothing short of amazing, thanks for the quick fix @mjbvz @jrieken
