### ISSUE TITLE
error message with Java: "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed"

### ISSUE THREAD

**Issue by shiuchunming** [Microsoft/vscode#38637]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: Java Externsion Pack, Debugger for Java, Language Support for Java(TM) by Red Hat

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.2
java|red|0.14.0
vscode-java-debug|vsc|0.3.1
vscode-java-pack|vsc|0.2.0

Get error message "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed" after getting input from vscode debug console using BufferedReader in Java.

    import java.io.BufferedReader;
    import java.io.IOException;
    import java.io.InputStreamReader;

    public class demo {
        public static void main(String args[]) throws IOException {
            int input;
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            try {
               input = br.read();
            }
            catch(IOException e) {
                e.printStackTrace();
            }
            if(br != null) br.close();
            System.out.println("123"); // would not execute using debug console in vscode.
        }
    }

Here is the `launch.json`, which is basically a default one.

    {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "compile",
            "mainClass": "demo",
            "request": "launch",
            "args": ""
        }

    ]
    }
---

![error](https://user-images.githubusercontent.com/28855544/32956894-2b41e99a-cbf5-11e7-9c71-fd3279da9077.png)

Steps to Reproduce:
1. A console Java program getting user input with BufferedReader.
2. start debugging on debug console

**Comment by weinand** [comment]
Please file issue against Java extension.
