### ISSUE TITLE
Cannot determine recent change or authors(unsaved changes)

### ISSUE THREAD

**Issue by Chikimonki** [Microsoft/vscode#38644]
- VSCode Version: Normal version

As great as VS Code is, and as much as I love using it, just yesterday now I cannot use ctrl +S to save and run with F5. Instead I get a message before Line 1 that says "Cannot determine recent change or authors(unsaved changes)" See file attached:

Firstly it started when I opened a new file and ran it. The message appeared and I had to resave the file as, then run it. Now, I have to save and run everytime that I update the file, but still can't use F5 as I had used it before, or ctrl +S. They just won't work. It seems very odd how it just started happening, and it's a very annoying bug. Please fix it VS Code Team. Thanks.
![git 4 vs](https://user-images.githubusercontent.com/28068044/32960598-6a6f5d9c-cbbd-11e7-9ae1-4b0dea9ba59f.jpg)

I had opened the properties to find out more.
![git 4 vs 2c](https://user-images.githubusercontent.com/28068044/32961017-e53bfcf0-cbbe-11e7-9a38-d718bfd06b51.jpg)
Then I got the detailed report, which says it is fixed.
![git 4 vs 2b](https://user-images.githubusercontent.com/28068044/32961124-3ee11c68-cbbf-11e7-9392-8caa0b801adc.jpg)
![git 4 vs 2d](https://user-images.githubusercontent.com/28068044/32961090-1f2d2574-cbbf-11e7-9a19-64e4ba9bc184.jpg)
![git 4 vs 2](https://user-images.githubusercontent.com/28068044/32961075-12580a76-cbbf-11e7-8a1a-3cfa2b5d46a0.jpg)
![git 4 vs 2a](https://user-images.githubusercontent.com/28068044/32961077-132e7732-cbbf-11e7-9c7c-05c2cea6b3c7.jpg)
I don't think it's fixed?
![git 4 vs 2e](https://user-images.githubusercontent.com/28068044/32961227-9c7bbc0c-cbbf-11e7-8590-255c492da9fd.jpg)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by DFelten** [comment]
As far as I know this problem comes from the extension [Gitlens](https://github.com/eamodio/vscode-gitlens).

**Comment by Chikimonki** [comment]
Hi DFelten, I looked if I had Gitlens as an extension on the VS Code and it seems I didn't. So, maybe it's another extension that does this, but I removed other extensions and it works better now. Cheers
