### ISSUE TITLE
Integrated Terminal `ctrl-click` doesn't work after hiding

### ISSUE THREAD

**Issue by augb** [Microsoft/vscode#38646]
- VSCode Version: 1.19.0-insider (34c44f8; x64)
- VSCode Version: 1.18.1 (929bacb; x64)
- OS Version: Windows 10 Pro x64 (Build 15063)

Steps to Reproduce:

1. Ctrl-` to open integrated terminal.
2. `echo https://code.visualstudio.com/`
3. Hover over link and observe that `Ctrl-click` works.
4. Ctrl-` to hide the integrated terminal.
5. Ctrl-` to show integrated terminal.
6. Hover over link and observe that there is no link or ability to `Ctrl-click`.

Reproduces without extensions: Yes

My integrated terminal defaults to _PowerShell_.

If I re-type `echo https://code.visualstudio.com/`, the second instance has the link, but not the first that stopped working.

**Comment by augb** [comment]
Maybe related to #35662.

**Comment by pilisera** [comment]
I can reproduce this on OSX with bash. (Version 1.18.1)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36072
