### ISSUE TITLE
VSCode extension API not compatible with some strict TypeScript compiler options

### ISSUE THREAD

**Issue by PranayAgarwal** [Microsoft/vscode#38649]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0

It is currently impossible to develop a VS Code extension using TypeScript with strict-mode compiler options turned on. Some examples:

- `strictNullChecks` fails because most Provider interface methods expect `null` or `undefined` to be returned in some cases even though the typings define a concrete return type.

E.g. for `HoverProvider`
```TypeScript
provideHover(document: TextDocument, position: Position, token: CancellationToken): Hover | Thenable<Hover>;
```
But documentation says:
`The lack of a result can be signaled by returning undefined or null.`
- `noImplicitAny` fails because the test runner module `vscode/lib/testrunner` isn't typed.

**Comment by mjbvz** [comment]
Which version of the `vscode.d.ts` are you using in your extension? The current one does support strict mode

The version of the `vscode.d.ts` downloaded comes from the `"engines": {"vscode": "*"}` section of your extension's `package.json`

**Comment by PranayAgarwal** [comment]
Hmm, yeah I am using engine v1.5.0. Updating that would make the extension incompatible with older versions of vscode, which isn't desired, but bumping it up to just 1.8.0 fixes the return types, so that's good.

I'm still not able to find types for `vscode/lib/testrunner`, however.

**Comment by aeschli** [comment]
Moving to @bpasero for the `vscode/lib/testrunner`

**Comment by bpasero** [comment]
@PranayAgarwal can you file this https://github.com/Microsoft/vscode-extension-vscode/issues
