### ISSUE TITLE
Visual Code can't debug java in the new version why ?

### ISSUE THREAD

**Issue by YousefSaber** [Microsoft/vscode#38648]
![4](https://user-images.githubusercontent.com/33742499/32964649-923c5dba-cbdc-11e7-8f86-db04e9b50a4d.jpg)

![2](https://user-images.githubusercontent.com/33742499/32964555-5063679e-cbdc-11e7-85c3-48c67f303109.jpg)
![3](https://user-images.githubusercontent.com/33742499/32964557-5087c5c6-cbdc-11e7-956a-4215445042b4.jpg)
![4](https://user-images.githubusercontent.com/33742499/32964558-50aeb6ae-cbdc-11e7-894d-9f448e4b1ac4.jpg)
how can I debug java source code in the new version of VS Code ??

**Comment by weinand** [comment]
Please file issue against Java extension.

**Comment by YousefSaber** [comment]
This issue was moved to Microsoft/vscode-java-pack#11
