### ISSUE TITLE
workbench.panel.location is now broken

### ISSUE THREAD

**Issue by brandonaaskov** [Microsoft/vscode#38650]
It looks like [a recent commit went through](https://github.com/Microsoft/vscode/commit/195c79e3fd1c1f07803e0efe4c5473b3345886ee#diff-f8c4d28f66e42e803022f155241cacf7L91) that removed the recent functionality that allows me to open the integrated terminal in a vertical pane as opposed to defaulting to the bottom.

It looks like this user settings key is no longer valid, and I can't find a replacement for it:
![image](https://user-images.githubusercontent.com/445778/32965044-43d9be80-cba3-11e7-8e5f-fe6776fa14d1.png)

Was that intentional? I hope not because I was _really_ happy about that feature. It came out in the October 2017 version of VSC, and I'm hoping that it doesn't disappear in the next version.

**Comment by isidorn** [comment]
The removal of the setting was intentional, however we still support that feature. Just click on the toggle panel location button.
As to reasons why we did this you can find here https://github.com/Microsoft/vscode/issues/37351
