### ISSUE TITLE
Can't use "Configure Default Build/Test Task" commands to change the default.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#38657]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Create 2 or more build tasks.
2. Use "Configure Default Build Task" command to make one of them default.
3. Try to use "Configure Default Build Task" again to change the default. 

VSCode says "XXXXXXX is already marked as the default build task".   This behavior is not very useful.  I'd rather it just let me pick another task as default and make appropriate changes to tasks.json. 

Same applies to "Configure Default Test Task".

**Comment by alexr00** [comment]
Verification steps: In a folder with tasks, run the Configure default build task command and select a task. Rerun the command and confirm that you can now select a different task. Check the tasks.json file to see that both tasks have been updated. Repeat for Configure default test task.
