### ISSUE TITLE
Ruler disappears when zooming in or out

### ISSUE THREAD

**Issue by somewhatabstract** [Microsoft/vscode#38656]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
vscode-caniuse|aga|0.5.0
Bookmarks|ale|0.18.0
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
gitlens|eam|6.1.1
tslint|eg2|1.0.22
flow-for-vscode|flo|0.7.2
auto-rename-tag|for|0.0.15
rest-client|hum|0.16.1
path-autocomplete|ion|1.7.0
svg|joc|0.0.9
docthis|joe|0.6.0
mssql|ms-|1.2.1
python|ms-|0.8.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
sass-indented|rob|1.4.5
code-spell-checker|str|1.4.12
vscode-todo-highlight|way|0.5.11
vscode-import-cost|wix|2.5.1
ReactSnippets|xab|1.6.0
vscode-open-in-github|ziy|1.3.0

---

Steps to Reproduce:

1. Add a workspace setting of "editor.rulers": [80]
2. View a file to see the ruler
3. Zoom in
4. Swap to a different file and return, ruler is gone
5. Zoom out, ruler reappears
6. Zoom out, ruler is gone again
7. Repeat to see that ruler is only visible when on the default zoom

Note that sometimes the ruler does appear. Seems to be a side-effect of the scaling.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is a known issue. For pixel perfect rendering, please do not use `window.zoomLevel` i.e. do not use `View > Zoom In / Zoom Out`. My recommendation is to use zooming rarely, e.g. when projecting to an audience and you need to quickly be able to zoom in. 

Please customize the font size in the editor, in the terminal, and upvote in #519 that the font size can be customized for the explorer.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side, **short of removing window.zoomLevel entirely**. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.

**Comment by somewhatabstract** [comment]
Yup, makes sense. Thanks! 🙂
