### ISSUE TITLE
Write error on integrated terminal

### ISSUE THREAD

**Issue by dllerena** [Microsoft/vscode#38652]
Hi guys! Awesome work on Visual Studio Code... This is my prefer text editor so far!!
But with the latest update, I'm getting this error when I'm compiling using the integrated terminal.

make[1]: Leaving directory `F:/Directory/path/'
make[1]: write error
make: *** [..\..\Bin\[file]] Error 1

I don't know why the terminal lose write permission to this folder. :(
That wasn't happening before.
But now that I'm thinking, I'm not sure if its with the new version of Visual Studio Code or the new version of windows, because just yesterday my windows get updated and today I update to this version of the IDE.

- VSCode Version: Code 1.19.00 
- OS Version: Windows 10.0.16299.125
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vcterminal|esp|0.0.11
tortoise-svn|fan|0.1.1
CppSnippets|har|0.0.13
format-php|Kas|1.1.2
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
reloaded-cpp|rel|0.1.6
vscode-icons|rob|7.18.1
partial-diff|ryu|0.5.0
clang-format|xav|1.6.1

(2 theme extensions excluded)

---

Steps to Reproduce:
1. Open integrated terminal.
2. try to call Makefile that calls nested makefiles.
3. right at the end, you will get "write error" and compiling process stops.
4. Please refer to tehKaiN comment! that's exactly what is happening.

NOTES: this is happening after Windows newest update, I've been using VSC long time ago and never got that error before. I'm using a mingw32 environment who uses a makefile as a parameter (who calls nested ones) that calls a specific compiler for embedded systems that compiles files using ANSI C located on different project folders. I thinks this is a regular compiling process, nothing out of normal.

Reproduces without extensions: NO

**Comment by dllerena** [comment]
I got more time and I made some testing on this issue and looks like it was the recent windows update. I installed previous releases(July, August and September) from Visual Studio Code and all of them are still making the same issue with the integrated terminal.

**Comment by Tyriar** [comment]
@bitcrazed another possible issue with a new version of Windows?

**Comment by tehKaiN** [comment]
I have same problem on newest Windows and latest vscode, not sure if it happened before Windows upgrade. This error is not so big issue when calling single makefile since it errors right at the end. Unfortunately, if makefile calls another makefile, then the nested one's error prevents parent from completing its jobs.

**Comment by dllerena** [comment]
I'm using VS Code almost a year and I didn't have this issue before. At first I thought it was and issue from newest VSC update, but I installed previous version of it and I got same issue, then I remember windows get updated same day.
tehKaiN, exactly same issue is happening to me! I have multiples make files and right at the end, process stops and gets me this "write error", but if I try and try, at the end, it will build my output but it will have this "write error" message, maybe from previous calls.

**Comment by bitcrazed** [comment]
Hey @dllerena - could you please update your original post with 

* Some repro steps
* Details about what you're running inc. versions, etc.

**Comment by dllerena** [comment]
Hi @bitcrazed I updated the original post and I tried to be as descriptive as I can. I hope this help you. Let me know anything else I can help with.

**Comment by bitcrazed** [comment]
@dllerena V. helpful, thanks. To help make sure that we're directly addressing your specific issue, do you have a repo containing a problematic makefile?

**Comment by dllerena** [comment]
@bitcrazed No problem!
I don't think the makefile is the one who has the problem because I'm able to run it on Windows cmd (without admin rights) and it runs ok, also I used to ran it on VSC integrated terminal previous to that windows update and also runs perfectly!

**Comment by tehKaiN** [comment]
Okay, so I'm trying some small test cases to replicate this, but with no luck. Dunno what really triggers this bug. It's triggered in makefile here: https://github.com/tehKaiN/ACE , (write error at the end, breaks other makefiles if called from them). I guess noone will install Amiga-only compilers to replicate this. Also I had same problems in project using arm-gcc. I've tried doing something like this:

```
CC = gcc

C_FILES = $(wildcard *.c)
O_FILES = $(notdir $(C_FILES:.c=.o))

all: clear main

main: $(O_FILES)
	@echo main
	gcc $(O_FILES) -o test

clear:
	del *.o test.exe

%.o: %.c
	$(CC) -c -o $@ $<
```
but with no luck, everything works correctly.

**Comment by Tyriar** [comment]
This might be the same root cause as https://github.com/Microsoft/vscode/issues/36630, https://github.com/Microsoft/console/issues/40?

**Comment by dllerena** [comment]
I've been reading both and I think so!!! Thanks!
