### ISSUE TITLE
node.js: Show errors for things that aren't defined, etc.

### ISSUE THREAD

**Issue by Tech-a-Tech** [Microsoft/vscode#38658]
Feature Request: In JS, make squigglies and errors appear for things that aren't defined, or like any error. Or if this exists, please tell me how to enable it. I want all errors to appear in my project, it will make things much easier. Not just basic syntax errors, but all errors.

Thanks, Tech-a-Tech

**Comment by mjbvz** [comment]
Try enabling `checkJs` / `@ts-check` for your files or entire project: https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files
