### ISSUE TITLE
"cannot find module" for all modules in February release 0.10.10

### ISSUE THREAD

**Issue by alanouri** [Microsoft/vscode#3865]
I am getting a "cannot find module" error for every single require() call in my project after upgrading to February release.  I checked in procmon and VSCode is searching for the required file at the correct path and successfully reading it, so I'm not sure why I'm getting this error.  Wasn't a problem in the last release.

Any help?

**Comment by egamma** [comment]
I suspect that you have no `jsconfig.json` file in your workspace. If you do not have one, then you ran into Microsoft/TypeScript#7292. 

Does it work once you add a jsconfig.json like:

```json
{
    "compilerOptions": {
        "module": "commonjs"
    }
}

**Comment by egamma** [comment]
Other thought you are using `amd`? AMD module resolution is currently not supported in Salsa Microsoft/TypeScript#6942

**Comment by egamma** [comment]
Turns out this is a TS project.

@dbaeumer have you seen such an issue with 0.10.10

**Comment by alanouri** [comment]
This is all TS w/ CommonJS.  I wasn't previously using a tsconfig.json, but if I add one with the following contents:

```json
{
   "compilerOptions": {
       "module": "commonjs"
   }
}
```

It still doesn't work.

**Comment by alanouri** [comment]
Just a note, this is the VSTS code base and I'm available for debugging over Skype for Business if anyone would like to poke around.

**Comment by dbaeumer** [comment]
@alanouri can I close the repository somewhere. Then I can have a look

**Comment by egamma** [comment]
Reproduced the issue using the same repo.

Adding this tsconfig.json
```json
{
    "compilerOptions": {
        "module": "amd"
    }
}
```

Fixes the module not found errors. Therefore this doesn't look like a VS Code issue, but a consequence of switching from TS 1.7.5 to TS 1.8.2.

**Comment by Ronmenator** [comment]
thank you, Switching to 'amd' for module fixed the 'cannot find module...' problem on our Fayde project as well.

**Comment by lukefan6** [comment]
I had the same issue and switching module to 'amd' did get it fixed.
However I don't understand why it's TS 1.8.x issue rather than VSCode's, could anyone elaborate?
