### ISSUE TITLE
Search results don't show an "Open to the Side" option in context menu.

### ISSUE THREAD

**Issue by joseangelyanez** [Microsoft/vscode#38660]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Search for a file.
2. Right click on the file, nothing happens, no context menu is shown.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
True but cmd+click will open the search result to the side, same as other places in the UI.

**Comment by joseangelyanez** [comment]
Then at least explain in a tooltip or some other visual clue of your preference that holding the "cmd" key while clicking the item on the search will show the result to the side, at first glance there is no visual indication that this is functionality is even available.
