### ISSUE TITLE
vscode.workspace.textDocument is missing documents in "Open Editors" that haven't been activated yet

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#38665]
- VSCode Version: 1.18.1.
- OS Version: Windows

Steps to Reproduce:

1. Start debugging an extension that references vscode.workspace.textDocuments with a workspace that has multiple files open.

Bug: vscode.workspace.textDocuments doesn't include the files listed under "Open Editors" until the file is activated the 1st time. Our extension wants to check if there are any C++ files open, even if they haven't been given focus yet.

According to https://github.com/Microsoft/vscode/issues/10304 it sounds like the docs in Open Editors should belong to textDocuments.

Reproduces without extensions: Yes (uh...well, you need at least one extension, because the bug is with the extension APIs).

**Comment by sean-mcmanus** [comment]
Bug#2: When the activationEvent is "onLanguage:cpp" -- the extension doesn't actually get activated until the cpp file is given focus, even though it's listed in the Open Editors. Maybe this is "by design"? We'd prefer to be able to activate if there are any "cpp" files in the "Open Editors" if possible.

**Comment by cleidigh** [comment]
@sean-mcmanus 
Bug # 2
Your final comment is correct.  Extensions are designed to be lazily loaded when first required.  This
is a performance choice and in general works quite well, with lots of extensions installed it's a use it
when you need it set up.
Bug # 1
The text documents are added to the internal list available to the API with events.  Having just worked on
a related scenario,  I also believe it would be good to be able to capture the file list without visiting
the file first.  I doubt this is a bug, but a different behavior would be useful.

@jrieken is getting the full file list possible some way?  I have talked about this with @eamodio 
regarding the possibility of an extended save file sets capability which requires this.  If not available
but deemed useful, I would do a PR for this, but having done a bit of investigation I think it touches a lot
of code on both sides of the API.
