### ISSUE TITLE
v1.18.1 Alt+F S no longer a single action in Chinese Language("locale":"zh-CN")

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#38669]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.20
cpptools|ms-|0.14.2

---

Steps to Reproduce:

1. Set language to "ZH-CN" (Chinese)
2. Alt + F, S the Save(S) it still clash with Save To Workspace
3. Note: English language ("en-US") is not clash now.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Ah this is about chinese, I guess we need to wait for the localization to drop in.
