### ISSUE TITLE
Updated VS Code Insiders and lost Git integration 

### ISSUE THREAD

**Issue by petercr** [Microsoft/vscode#38667]
- VSCode Version: Code - Insiders 1.19.0-insider (34c44f872c177d6f9439706418f8fe49bf125d08, 2017-11-17T05:14:07.221Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
debugger-for-chrome|msj|3.5.0
LiveServer|rit|3.0.0
vscode-icons|rob|7.18.1
sass-indented|rob|1.4.5
bootstrap4-vscode|the|3.0.0
bootstrap-3-snippets|wcw|0.1.0
html-css-class-completion|Zig|1.14.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.  Updated VS Code insiders build
2. Lost Git integration in VS Code Insiders Build. It still works from the command line, VS Code Stable build, and Atom Beta. 

Reproduces without extensions: Yes

**This was after the original update**

![Shows the build number and Git working on the command line](https://user-images.githubusercontent.com/26460352/32976108-6dd6e42a-cbde-11e7-97fc-a2e19d577113.png)

**This was after an additional update**

![After I updated the daily build again to see if it fixed the bug](https://user-images.githubusercontent.com/26460352/32976125-9698e570-cbde-11e7-9e52-bcec2ccd7516.png)

**This was after the update from 11/17/2017. I also tried turning off the extensions to see if that made a difference.**
 
![Updated the build again to see if it would affect the bug](https://user-images.githubusercontent.com/26460352/32976133-aad876f4-cbde-11e7-9020-58bd30284dbd.png)

**Comment by petercr** [comment]
@joaomoreno I've left the setup as it is shown above. If you would like anymore info or for me to try anything, please let me know.
Thanks 👍

**Comment by mianfengchen** [comment]
The latest version update gives this hint

**Comment by joaomoreno** [comment]
You need to either install git from https://git-scm.com/ or to configure `git.path` to point to the location where you have installed it, if different from the default.

**Comment by petercr** [comment]
@mianfengchen I was able to get it to work after changing the `git.path` to point to the location of `git.exe`. It just seemed strange as the whole `/git/` directory is set up as a path on my computer. And both the Stable and Insiders build work fine without setting up `git.path` in the settings. 

And prior to the specific update the Git integration was working perfectly on the Insiders build without `git.path` set up. 🤔

**Comment by joaomoreno** [comment]
We had to disable using git from the PATH: https://github.com/Microsoft/vscode/issues/32739#issuecomment-341177471
