### ISSUE TITLE
One slow resolving code lens blocks rendering of others

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38661]
**Bug**
A slow to resolve code lens can block the rendering of all other code lenses.

**Repo**
1. Download and run this text extension https://github.com/mjbvz/test-slow-code-lens-ext
2. Open markdown file
3. Any line starting with the letter `x` will get two code lenses. The 🐰lens resolves immediately. The 🐢 lens resolves after 5 seconds
4. Notice that both of these are rendered after 5 seconds

**Comment by jrieken** [comment]
I know. The idea is to prevent flickering, esp. with code lenses... Agreed that resolving code lens *locations* and code lens *contents* is different and while the former leads more flicker and latter might be acceptable... We can try out things
