### ISSUE TITLE
Icon is indistinguishable in the "open with" list

### ISSUE THREAD

**Issue by foolishwolf** [Microsoft/vscode#38677]
- VSCode Version: 1.18.1
- OS Version: Win10 1703

Icon in current version has too few colors, which make it  indistinguishable against the Monochrome background in the "open with" list.
![openwith](https://user-images.githubusercontent.com/6966728/32978897-1b89c2b6-cc86-11e7-9bd4-d8b9e0ed960a.jpg)

**Comment by bpasero** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/38353
