### ISSUE TITLE
shell option in tasks.json works per task, but not top-level

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#38676]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vscode-commitizen|Kni|0.5.0
vscode-docker|Pet|0.0.22
vscode-wakatime|Wak|1.1.21
html-css-class-completion|Zig|1.14.0
yaml|ada|0.0.9
vscode-icontheme-nomo-dark|be5|1.3.4
emojisense|bie|0.3.0
vscode-eslint|dba|1.4.3
ts-tslint|eg2|0.0.4
tslint|eg2|1.0.22
prettier-vscode|esb|0.24.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.4
svg|joc|0.0.9
docthis|joe|0.6.0
graphql-for-vscode|kum|1.6.5
git-tree-compare|let|1.1.4
Go|luk|0.6.67
dotenv|mik|1.0.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
vscode-nginx|sha|0.4.1
javascript-typescript|sou|0.0.5
sourcegraph|sou|1.0.9
rewrap|stk|1.5.3
gitblame|wad|2.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

Create a tasks.json like this:
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "options": {
    "shell": {
      "executable": "pwsh",
      "args": ["-c"]
    }
  },
  "tasks": [
    {
      "label": "Run Pester",
      "dependsOn": "publish",
      "type": "shell",
      "command": "Invoke-Pester"
    }
  }
}
```

Running this task will get you
```
/bin/bash: Invoke-Pester: command not found
```

However if you change it to
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Pester",
      "dependsOn": "publish",
      "type": "shell",
      "command": "Invoke-Pester",
      "options": {
        "shell": {
          "executable": "pwsh",
          "args": ["-c"]
        }
      }
    }
  }
}
```

It works as expected

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
I tried this with the following example:

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"options": {
		"shell": {
			"executable": "C:\\Windows\\System32\\cmd.exe",
			"args": [
				"/d", "/c"
			]
		}
	},
	"tasks": [
		{
			"label": "dir",
			"type": "shell",
			"command": "dir",
			"problemMatcher": []
		}
	]
}
```

which uses for the dir task correct cmd.exe where my default shell is PowerShell. Any idea what makes your example different.

Please be aware of: https://github.com/Microsoft/vscode/issues/36342

**Comment by felixfbecker** [comment]
The only difference I see is that I am on macOS and you seem to be on Windows.
I don't think #36342 applies because I am using the `shell` task type?

**Comment by dbaeumer** [comment]
Yes, but the code to parse a tasks.json file is not really OS specific. I will give it a try under Linux / MacOS.

**Comment by felixfbecker** [comment]
What more information should I provide?

**Comment by dbaeumer** [comment]
Agree,

**Comment by dbaeumer** [comment]
In our example is `pwsh` on the path ?

**Comment by felixfbecker** [comment]
Seems to work now
