### ISSUE TITLE
No more quick fix support to download a typings file 

### ISSUE THREAD

**Issue by Umamaheswaran1990** [Microsoft/vscode#3867]
I'm not able to download type definitions for modules like angular, jquery after this update. previously when i type angular in js file i will get 'download type def' once i downloaded it will provide the intellisense for angular. but now the intellisense is just gone and im not able to download type def.

Any help?

**Comment by egamma** [comment]
Sorry, but this is a known limitation we have documented in the release notes.

As a work around can you try to use this extension https://marketplace.visualstudio.com/items?itemName=jrieken.tsd-recommender

**Comment by cleever** [comment]
There is no chance to this feature come back in near future? Or a better alternative?
This was one of my favorite features.

**Comment by Umamaheswaran1990** [comment]
@egamma It looks like the TSD has been deprecated. I was able to use the https://github.com/typings/typings which based on tsd and got the intellisense working for angular, but it looks like i have to add this line in all my javascript files. Is there any workaround to make vscode recognize this for all js files ?

/// <reference path="..\..\typings\main.d.ts" />

Thanks,

**Comment by cleever** [comment]
@Umamaheswaran1990 I did it too. But put this in all js files is impracticable.

**Comment by Umamaheswaran1990** [comment]
@cleever I agree, esp. in large projects

**Comment by PandiyanCool** [comment]
:+1: 

vscode needs to consider about adding type definitions for angular and also for other popular frameworks in the upcoming releases

it will be very impressive :)

**Comment by egamma** [comment]
@cleever automatic .d.ts acquisition is on the roadmap for [TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap). So the feature will come back and it will be even better.

**Comment by egamma** [comment]
> It looks like the TSD has been deprecated. 

correct and we have updated our docs. `tsd` still works for getting the typings.

>it looks like i have to add this line in all my javascript files. Is there any workaround to make vscode recognize this for all js files 

This is no longer required since a while. You can add a [jsconfig.json](https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson) in the root folder of your project. Make sure that the `typings` folder is included in the project context.

**Comment by Umamaheswaran1990** [comment]
@egamma Thanks it works :+1:

**Comment by Purush0th** [comment]
:boom: :+1:
