### ISSUE TITLE
Missing Important Feature: Organize Imports

### ISSUE THREAD

**Issue by rudolfschmidt** [Microsoft/vscode#38670]
Hi,

its for me hard to understand how people can code in react without a automatic import organizer that remove unused imports. You have this for typescript, but not for normal javascript. Typescript Hero is the only solution I know that offers such feature. Unfortunately Typescript Hero still support only typescript but not javascript propertly.

Its really important to have that feature!

Best Regards
Rudolf

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/10020
