### ISSUE TITLE
cursor change to resize icon when vertical terminal is closed (only in vertical terminal mode)

### ISSUE THREAD

**Issue by Yofri** [Microsoft/vscode#38672]
- VSCode Version: Version 1.18.1
- OS Version: Deepin 15.5

here what it looks like
[Bug](https://i.imgur.com/worNcdu.gif)

**Comment by Tyriar** [comment]
@Yofri can you post another screenshot? Copying and pasting into GitHub will upload it here which doesn't expire.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/38592
