### ISSUE TITLE
Save all files command without save as for unsaved or untitled files

### ISSUE THREAD

**Issue by er-sarjan** [Microsoft/vscode#38675]
- **VSCode Version:** 1.18.1
- **OS Version:** Windows 10 x64

**Steps to Reproduce:**

I have multiple unsaved files which I used for writing random things which are not part of my project folder. While working on multiple files, when I used Save All command, it shows Save As dialog for those untitled file to Save As.

Previously working with WebStorm, it has concept of Scratch file which does not show Save As dialog for scractch files.

Is similar kind of functionality available in VS Code?

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/32978624-2779fe46-cc46-11e7-98e7-9de9b1341707.png)
