### ISSUE TITLE
Git is not working on macos 10.13.1

### ISSUE THREAD

**Issue by khanhduy39nn** [Microsoft/vscode#38673]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.1.1
code-runner|for|0.8.4
contextualduplicate|laf|0.2.0
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0

------------

VSC can not detect and work on macos 10.13.1.

**Comment by roblourens** [comment]
More details please, what do you mean by "not working"?
