### ISSUE TITLE
when json file is too big, it can't auto-wordWrap

### ISSUE THREAD

**Issue by imhuay** [Microsoft/vscode#38682]
- VSCode Version: 1.18.1
- OS Version: win10

Maybe it's more serious, it has breakdown many times for a json file about 50MB without wordWrap

Reproduces without extensions: Yes/No

**Comment by phurich** [comment]
Confirm ! Actually, a regular 30-40 MB text file can reproduce this problem.

**Comment by phurich** [comment]
imhuay,
You can use notepad instead.
Back to basic, man.

**Comment by roblourens** [comment]
This is expected, long lines can not word wrap.

**Comment by phurich** [comment]
roblourens,
I don't think so. Since the older version such as 1.13.1 can do word wrap correctly.

**Comment by alexandrudima** [comment]
For memory savings reasons (i.e. avoid an Out Of Memory crash and be able to open the file), files over 300k lines or over 50MB do not get tokenization, and do not get a ViewModel allocated, which means no: folding or wrapping.
