### ISSUE TITLE
调试适配器进程已意外终止

### ISSUE THREAD

**Issue by 107350qin** [Microsoft/vscode#38684]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
> The debug adapter process has terminated unexpectedly

When debugging Python? Please open an issue on their repo with more details.
