### ISSUE TITLE
openTextDocument logs error to console when opening binary file

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#38687]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063

VSCode developer tools will open with errors when trying to open a binary file via the `openTextDocument` API. I expect it to return an error, but not open the dev console.

Steps to Reproduce:

Where `filename` is a path to a binary file
```
    vscode.workspace.openTextDocument(Uri.file(filename)).then(doc => {
        // Success
    },
        (err) => {
            // This gets called, but still developer tools open
            vscode.window.showErrorMessage("Cannot display: " + filename);
        }
    );
```

Developer tools output:
```
[uncaught exception]: Error: File seems to be binary and cannot be opened as text
onError @ index.js:41
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\init.js:135
index.js:44 Error: File seems to be binary and cannot be opened as text
    at new t (files.ts:554)
    at fileService.ts:241
    at Object.g [as _notify] (winjs.base.raw.js:1170)
    at Object.enter (winjs.base.raw.js:852)
    at n.Class.derive._oncancel._run (winjs.base.raw.js:1068)
    at n.Class.derive._oncancel._completed (winjs.base.raw.js:1036)
    at stream.ts:75
    at FSReqWrap.oncomplete (original-fs.js:114)
onError @ index.js:44
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\init.js:135
```

**Comment by jrieken** [comment]
This is crazy... We do have error handles et all attached in the right places. They even get called but the error still bubbles up globally...

**Comment by jrieken** [comment]
fyi @joaomoreno

**Comment by ramya-rao-a** [comment]
@jrieken Using today's Insiders and the sample code from @CoenraadS above, I still see the below in the dev tools

![image](https://user-images.githubusercontent.com/16890566/33686811-ec7379fa-da8a-11e7-91e5-5e6ec21e65ef.png)

**Comment by jrieken** [comment]
I don't see that... Assigning to @ramya-rao-a for more information

**Comment by ramya-rao-a** [comment]
@jrieken If the expectation is that dev tools no longer open, then yes i can verify the fix

If the expectation is that dev tools no longer open + no errors logged to console, then that expectation fails, as a single error still reaches the dev tools as shown in the screenshot in https://github.com/Microsoft/vscode/issues/38687#issuecomment-349783776

After going through this issue again, I believe the former is the expectation, and so will close this issue and mark as verified.

**Comment by jrieken** [comment]
The extension shows an error using the `showErrorMessage`-function and the rule of the workbench is that every error showing in the UI is also shown in the console.
