### ISSUE TITLE
Goto definition in ruby never not work :(, rubymine goto definition works very well!!!

### ISSUE THREAD

**Issue by reinaldorossetti** [Microsoft/vscode#38689]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.4.1
gherkin-indent|Ara|2.0.0
solargraph|cas|0.9.1
vscode-markdownlint|Dav|0.11.1
githistory|don|0.2.3
windows-explorer-context-menu|ele|2.0.0
git-project-manager|fel|1.4.0
code-runner|for|0.8.4
haml|gro|0.0.2
ruby|gro|0.0.6
vscode-simple-icons|Lau|1.7.1
ruby-symbols|mig|0.1.5
ruby-rubocop|mis|0.5.0
python|ms-|0.8.0
atom-keybindings|ms-|3.0.2
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|3.5.0
vscode-ruby-ctags|oto|1.4.1
material-icon-theme|PKi|3.0.0
Ruby|reb|0.15.0
vscode-findinpage|sat|0.2.4
cucumber|ste|0.9.6
python|tht|0.2.3
terminal-tabs|Tyr|0.1.1
vscode-react-native|vsm|0.5.4
status-bar-customize|zhe|0.0.1
editorzoom|zol|1.0.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1. f12 in function only.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
We don'tprovide this out of the box, but if you're using a Ruby extension, please file an issue on their repo.
