### ISSUE TITLE
Color of status bar

### ISSUE THREAD

**Issue by torava** [Microsoft/vscode#38688]
Color choice of status bar is odd. Otherwise colors of editor are muted but then for some reason this status bar strikes to your eyes and takes your attention. On UX field it's known that bright colors should be avoided in the background layers. Other elements than code editor are definitely in the background. The color should be possible to change somewhere. I just need to hide it all the time.

**Comment by fabiospampinato** [comment]
This is customizable, just add the following to your settings and tweak the colors to your likings:

```json
"workbench.colorCustomizations": {
    "statusBar.background": "#000000",
    "statusBar.foreground": "#dddddd",
    "statusBar.debuggingBackground": "#007acc",
    "statusBar.debuggingForeground": "#dddddd"
}
```
