### ISSUE TITLE
Option for linux style ${workspaceFolder} Variable Substituion 

### ISSUE THREAD

**Issue by JohnKozell** [Microsoft/vscode#38685]
Using VSCode on Windows 10, the Variable Substitution for ${workspaceFolder} returns a backslash-based path (ex: **c:\users\john\documents\myproject**). 
This makes it difficult to pass a working directory to a GNU-style makefile, which expects a format such as: **/c/users/john/documents/myproject**

- VSCode Version: 1.18.0
- OS Version: Windows 10.0.15063

Steps to Reproduce:
1. Create a tasks.json file, similar to: 
```
{
"version": "2.0.0",
"echoCommand": true, 
"tasks": [
    {
        "label": "build",
        "type": "shell",
        "group": {
            "kind": "build",
            "isDefault": true
        },
        "command": "make",
        "args": [
            "APPDIR=\"${workspaceFolder}\""
        ]
. . .
}
```

2. The MAKEFILE receives a windows-based **workspaceFolder** path for the **APPDIR** argument. Ex: **c:\users\john\documents\myproject**

Suggest having a Variable Substitution modifier to transform Windows paths to Linux. 
Or, create additional substitution variables that always return Linux-style paths: ex: **/c/users/john/documents/myproject**

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Labeling as WSL since we collect these issue there.

**Comment by jmagosta** [comment]
Similarly, the menu command "copy path (Alt-shift-c)" in the file explorer right-click menu should be configurable to generate bash-style forward-slashed paths when using a bash terminal type.

**Comment by lfurzewaddock** [comment]
I recently created a VS Code extension: [WSL workspaceFolder](https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-wsl-workspacefolder), which may help.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
