### ISSUE TITLE
MVC Web site run fails in VS Code

### ISSUE THREAD

**Issue by Tarjei99** [Microsoft/vscode#38699]
- VSCode Version: 1.18.1
- OS Version: Microsoft Windows [Version 10.0.16299.64]

Description of problem.
It looks like VS Code can't build and run the code. I have no problem when I use the command line "dotnet restore ; dotnet build ; dotnet run". The code works fine with VS2017 also.

It looks like MvcMovie.dll is generated in a directory where VS Code can't find it. There is a bin\BNB directory which seems to not be expected by VS Code.

Error : launch: program 'c:\temp\VS_code\MvcMovie\bin\Debug\netcoreapp2.0\MvcMovie.dll' does not exist.

BTW It is somewhat annoying that the error message is not echoed in the terminal pane.

The build log :
----  8<  --------------------------------------- >8 -----------------
> Executing task: C:\Program Files\dotnet\dotnet.exe build c:\temp\VS_code\MvcMovie/MvcMovie.csproj <
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
MvcMovie -> c:\temp\VS_code\MvcMovie\bin\BNB\Debug\netcoreapp2.0\MvcMovie.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.01
Terminal will be reused by tasks, press any key to close it. 
----  8<  --------------------------------------- >8 -----------------

Steps to Reproduce:

1.Open tutorial "Getting started with ASP.NET Core MVC on Mac, Linux, or Windows" folder.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/start-mvc
2. Select "Start debugging" or "Start without debugging"

Reproduces without extensions: No, sort of.
Error message with extensions disabled : 
    Configured debug type 'coreclr' is not supported.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1882
