### ISSUE TITLE
Console and Up arrow key causes the console to get all messed up. If I go through my command history, anything that was more than one line will start overwriting letters on top of of other letters. I always have to "cls" before using the Up arrow to look at my command history.

### ISSUE THREAD

**Issue by squatOn** [Microsoft/vscode#38694]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

1. type out a command that spans more than one line. Keep the console small physically so that you can test a shorter command.
2. Run it enough times so that each line of the console's viewable area has text on it.
3. Hit the up arrow key and watch the text start overlaying on top of previous text.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't see this, can you post a screenshot?

**Comment by isidorn** [comment]
@squatOn do you see this in the debug console or in the integrated terminal?
And yes a screenshot would be great. Also can you reproduce with latest vscode inisders https://code.visualstudio.com/insiders/

**Comment by squatOn** [comment]
Once it happens again, I will definitely post a screenshot.

**Comment by squatOn** [comment]
<img width="864" alt="starstarstarabcstarstarstar" src="https://user-images.githubusercontent.com/8438217/33102154-7822d37c-cee9-11e7-84c4-09d035bb0e22.png">

In that first screenshot, I manually typed "***ABC***" in the console. You will notice "be)> dfgdfg" written right beneath that. The "be)> dfgdfg" is left over from earlier output. I notice this happening a lot when I change the size of the VS code UI (e.g. docked right to full screen).

<img width="864" alt="efghi" src="https://user-images.githubusercontent.com/8438217/33102229-c7234fc4-cee9-11e7-9264-13000922e0cb.png">

And this second screen shot, I backspaced my "***ABC***" and typed "EFGHI". You can see that the same output remained in the screen and is just hanging there. If I "cls", I get a fresh new terminal.

**Comment by squatOn** [comment]
<img width="864" alt="vscode_issue" src="https://user-images.githubusercontent.com/8438217/33105194-f88c4b00-cef9-11e7-85ba-e6da5d2ac229.png">


here's another instance. in red is what I typed to display the issue happening. circled in green is the output from a previously run function. thanks.

**Comment by squatOn** [comment]
Here are a couple more screenshots. One is a before and the other one is an after.

**BEFORE**. Here I was pressing the up arrow to go through my command history.  At some point I ran a multi-line command. All is well right now...until....

<img width="864" alt="vscode_issue_before" src="https://user-images.githubusercontent.com/8438217/33150810-3700ddd4-cfa3-11e7-9b27-b92ad81df045.png">

....**AFTER**. If I keep continue going through my command history and get to something that was not as many lines as you see in the BEFORE screenshot, it doesn't play well. No idea why.

<img width="864" alt="vscode_issue_after" src="https://user-images.githubusercontent.com/8438217/33150938-c65c2d8a-cfa3-11e7-896e-fa023a4e2a33.png">

**Comment by Tyriar** [comment]
@squatOn does resizing the terminal window a little bit correct the issue?

**Comment by Tyriar** [comment]
@squatOn by reproduced do you mean it fixes the problem?

**Comment by squatOn** [comment]
@Tyriar No. If I start over with a clean console or new VS Code window, I can recreate the problem by resizing either one of those things and I can make the problem appear.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
