### ISSUE TITLE
Add a "Save Without Formatting" command

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#38695]
Would be really nice to add a command that allows bypassing automatic formatting while saving a file, if the user has it enabled.

Specifically, saving using this command would skip the changes caused by enabling either:

```
"files.trimTrailingWhitespace": true,
"files.insertFinalNewline": true,
"editor.formatOnSave": true,
```

(Not sure if there are more transformations that can be triggered on save)

It probably doesn't need to be bound to any specific keyboard shortcut by default.

Reasoning: Very often I find myself having to patch a third-party package, by either cloning their repo and submitting a PR, or by directly editing the package inside `node_modules` (Using the `patch-package` tool), and it will usually produce a large/ugly diff because of the several changes caused by automatic formatting. I can surely disable the setting temporarily (or add a `.vscode` folder inside `node_modules` disabling the options), but neither is an ideal solution.

Thanks in advance!

**Comment by bitjson** [comment]
I definitely think this should be built-in to VS Code.

Until then, here's a great workaround: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.save-without-format#overview

**Comment by bpasero** [comment]
There is now a new command "Save without Formatting" with the keybinding `Cmd+K S`. If someone has a better name, feel free to suggest (initially I had "Save without Participants" but that seems a bit too technical).

**Comment by bpasero** [comment]
**Verify:** see https://github.com/Microsoft/vscode/issues/38695#issue-275100856

**Comment by coreh** [comment]
Thanks! 🎉🎊🍕🎈

Are there extensions with participants unrelated to code formatting in common use? If so "Save without Transforms" or "Save Verbatim" might also make sense. Otherwise, "Save without Formatting" sounds good.

**Comment by bpasero** [comment]
@coreh yeah "Save without Formatting" would even mean that any extensions cannot participate even if not doing any formatting.

But my rationale was to cover the 99% case of why one would actually use that action in the first place and that is probably to prevent any kind of format to happen.

**Comment by jrieken** [comment]
Maybe "Save without Extensions". This will disable all kind of code actions that run on save and that's actually a thing.

**Comment by bpasero** [comment]
I am not convinced. People might confuse this to "save the file without a file extension". I am not sure there is any use case for using this command other than preventing any formatting from happening, so I would stick with the name.

**Comment by vivaldus** [comment]
@bpasero I tried to save a file without formatting following your suggestion: "Cmd+K S", but instead of saving without formatting, VSCode just brought up the menu for key bindings. (VSCode can be so confusing at times. I used to happily use `shift+option+s` to achieve this, then it stopped working, and now I can't seem to get a simple answer for how to achieve this. Would really appreciate some guidance here!)

**Comment by LukeFlego** [comment]
@vivaldus looks like the keybind changed...

![image](https://user-images.githubusercontent.com/2726761/47573068-c12fa800-d97f-11e8-8bf8-e2995550e6f1.png)

Remember you can usually (if not always) search within Visual Studio Code. Yay for VS Code being such a useful tool.
