### ISSUE TITLE
`String is not an URI: [UriError]: Scheme contains illegal characters.` when using github URL in package.json

### ISSUE THREAD

**Issue by drazisil** [Microsoft/vscode#38696]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
pgsql|dou|0.0.8
EditorConfig|Edi|0.11.1
vscode-npm-script|eg2|0.3.3
json-tools|eri|1.0.2
prettier-vscode|esb|0.24.0
code-runner|for|0.8.4
search-node-modules|jas|1.2.0
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
nodejs-docs|Muk|0.2.2
vscode-docker|Pet|0.0.22
Ruby|reb|0.15.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
prettylintednode|Zer|0.3.0

`String is not an URI: [UriError]: Scheme contains illegal characters.` when using github URL in package.json

---

Steps to Reproduce:

1. Have a `"url": "git@github.com:user/repo.git"` line in your package.json

Example:

```
  "repository": {
    "type": "git",
    "url": "git@github.com:drazisil/repo.git"
  },
```

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Where do you see this error?

**Comment by drazisil** [comment]
When I hover over the url in the package.json, and also in the problems tab. I can provide a screenshot if needed.

**Comment by joaomoreno** [comment]
@aeschli Can you fix the schema? I don't know where it's located.

**Comment by drazisil** [comment]
It seems to be https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L24

I didn't try messing with it because it appears to be conforming to an RFC, so I was not sure the best way to approach it.

**Comment by demisx** [comment]
Seeing the same warning.  I guess it doesn't like `@` in the URL.

**Comment by aeschli** [comment]
The problem is with the schema. I filed https://github.com/SchemaStore/schemastore/pull/376
