### ISSUE TITLE
Support to subsystem commands

### ISSUE THREAD

**Issue by leonardovilarinho** [Microsoft/vscode#38690]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Change `git.path` to `bash -c git` or similar.
2. Restart VSCode
3. Try execute anywhere action with Git.

We can define an flag to comunication with wsl, e.g. `git.path`: "bash -c 'git ${args}'".

With it call `bash -c 'git log' command  for example.

It can use whit `npm`, `pyhton`, `npm`, anywhere commands.

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/9502
