### ISSUE TITLE
Horizontal scrollbars weird behaviour

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#3869]
I have splitted the editor and the two horizontal scrollbars have a very weird behaviour. The bug seems easy to reproduce.

Just resize the width of the splitted screens (20%-80%, then 80%-20%, then 50-50), then look at the horizontal scrollbars. Their widths are sometimes not correct, they are not scrolling the editors content correctly...

**Comment by alexandrudima** [comment]
@Nimzozo Here I am trying to reproduce what you describe, but I am not seeing anything weird:

![scrollbars](https://cloud.githubusercontent.com/assets/5047891/13619163/ead14f9a-e587-11e5-89ed-13170a10f0c8.gif)

**Comment by Nimzozo** [comment]
Actually, it's not so easy to reproduce in a precise way, but only by quite randomly resizing the screens.
I'm going to try to give more info with a gif file.

**Comment by Nimzozo** [comment]
![animation](https://cloud.githubusercontent.com/assets/16692999/13620055/2b986090-e58d-11e5-8aaf-1d50d9d9242d.gif)

Here the left scrollbar has just disappeared, the right one works but has a weird size.

**Comment by alexandrudima** [comment]
@Nimzozo Thank you! I was also able to reproduce, also randomly by resizing the split editors a lot.

**Comment by alexandrudima** [comment]
To verify, please look at the commit or try resizing a lot...
