### ISSUE TITLE
Error TS5023 compiling typescript in a folder with a hyphen in the name

### ISSUE THREAD

**Issue by drazen64** [Microsoft/vscode#38704]
- VSCode Version: 1.18.1
- OS Version: Window 10 Enterprise, 1709, 16299.64
- node.js v9.2.0

Steps to Reproduce:

1. Create a folder with a hyphen in the name with at least one space from both sides. For example "C:\Test - TypeScript"
2. Create a typescript project inside and run a build task.
3.  The project does not compile:
> > Executing task: tsc --watch -p "d:\Test - TypeScript\tsconfig.json" <
> 
> error TS5023: Unknown compiler option '-'.
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it.

4. When I execute 
>  tsc --watch -p "d:\Test - TypeScript\tsconfig.json"

from the command prompt, it does not return an error.

5. When the folder name does not have space characters around a hyphen, build task completes without an error inside the VSCode.

> Executing task: tsc --watch -p "d:\Test-TypeScript\tsconfig.json" <
04:00:13 - Compilation complete. Watching for file changes.

 

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
@dbaeumer Here is that argument we pass to `ShellExecution`:

```
tsc -p "c:\test\sub - space\tsconfig.json"
```

In windows, this command works when run on the command line but fails when run through vscode

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/32400
