### ISSUE TITLE
Welcome pages takes focus all the time

### ISSUE THREAD

**Issue by alexgvozden** [Microsoft/vscode#38700]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.10
vscode-markdownlint|Dav|0.11.1
xml|Dot|1.9.2
provides-module-intellisense|ben|0.4.0
prettier-vscode|esb|0.24.0
file-icons|fil|1.0.7
text-transform|flo|0.1.0
vscode-auto-open-markdown-preview|hnw|0.0.4
path-autocomplete|ion|1.7.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
sensitive-replace|vil|0.1.1
vscode-js-console-utils|wht|0.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open VS Code
2. Try entering something in terminal and press enter
3. It will not accept enter as it gets focused on Welcome page
4. Same goes for other tabs if you open them while Welcome is open it will constanly shift focus to Welcom

Reproduces without extensions: Yes/No

**Comment by chrmarti** [comment]
Does this reproduce when starting with `code --disable-extensions`?

**Comment by alexgvozden** [comment]
you are right it is some plugin, will try to determine which one and let you know
