### ISSUE TITLE
Linux: dragging something shows white background first (flashes)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38709]
Looks like on Linux when you start to drag (e.g. a tab), there is first a white background popping up and then going away:

![before](https://user-images.githubusercontent.com/900690/32989526-5971693e-cd18-11e7-8488-d00bec2948f0.gif)

Setting the background does not really help. Looks like setting a high opacity seems to be working but then almost nothing else is visible.

/cc @Tyriar

**Comment by agauniyal** [comment]
Oh I thought something was wrong with my tabs so I disabled(hide) them 😆

**Comment by PoiSoNz** [comment]
Hi, do you mind me and my partners solving this issue for a school project? If so, could you help us on which files should we be looking for?

**Comment by bpasero** [comment]
@PoiSoNz I don't mind at all! The code that initiates the drag and drop starts from [`tabsTitleControl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L748)

I fear though that this might be a tough thing to fix. And it is happening on Linux only...

**Comment by PoiSoNz** [comment]
Thank you for your help!

**Comment by christianbender** [comment]
I use Linux, too. And the effect occur with me, too

**Comment by christianbender** [comment]
@bpasero  

In file [tabsTitleControl](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L748) 
I have played with line 760.

``` typescript
	e.dataTransfer.effectAllowed = 'copyMove';
```

 And have changed the effects. But this white background is still there.

**Comment by Tyriar** [comment]
FYI I suspect this is an issue with Chromium and therefore probably not a good first issue 😄

**Comment by bpasero** [comment]
This seems fixed with Chr61

**Comment by bpasero** [comment]
Closing as the update to Electron 2.0.0-beta.6 landed via https://github.com/Microsoft/vscode/commit/88603b377d56ead7b5c4cfc6bc3a64e5f832cd60. It should be in insider releases end of this week.

**Comment by bpasero** [comment]
Reopening as we had to revert the update.

**Comment by bpasero** [comment]
Closing, as we did the update.
