### ISSUE TITLE
search in single project in multi-root workspace

### ISSUE THREAD

**Issue by bardware** [Microsoft/vscode#38701]
- VSCode Version: 1.18.1
- OS Version: Win 10

Steps to Reproduce:

I use the new multi-root workspace feature to be able to look into multiple similar projects I'm working at at the same time.
The [documentation ](https://code.visualstudio.com/docs/editor/multi-root-workspaces) says to use the `files to include` input to filter a single project. It's a lot of work to enter the folder name every time I want to search.
I'd like to start the search with a mouse click on the context menu of the single root to select the single project I want to search.
In eclipse for example I can select multiple roots with the mouse STRG + click to select the different  roots and then hit search to limit search over a few projects.

**Comment by roblourens** [comment]
You can, if you right click click and select "Find in Folder". Only single selection is supported at the moment.
