### ISSUE TITLE
The text is not highlighted

### ISSUE THREAD

**Issue by joengan** [Microsoft/vscode#38707]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.Visual Studio Code vs Notepad ++
The text is not highlighted(As shown in the figure)
![2](https://user-images.githubusercontent.com/33801143/32989232-57c8f1f8-cd4d-11e7-961b-4bd36f3e501e.jpg)

2.

**Comment by roblourens** [comment]
Can you post the full text? Which theme is it?

**Comment by joengan** [comment]
line 330 to 430 have no color

[spacecp_blog.zip](https://github.com/Microsoft/vscode/files/1488197/spacecp_blog.zip)

**Comment by roblourens** [comment]
Seems to work in Atom but not vscode, with the same grammar.

**Comment by roblourens** [comment]
Is this a different templating language, or a syntax of PHP that I haven't seen?

**Comment by joengan** [comment]
This is HTML and javascript

**Comment by roblourens** [comment]
This looks ok after the last grammar update

![image](https://user-images.githubusercontent.com/323878/34218892-5b25031c-e564-11e7-8ccc-900f5950a582.png)
