### ISSUE TITLE
Wrong TypeScript syntax highlighting

### ISSUE THREAD

**Issue by PiranhaGreg** [Microsoft/vscode#38703]
- VSCode Version: 1.18.1 x64
- OS Version: Windows 10 Pro, Version 1709, Build 16299.64

Steps to Reproduce:

![vscode](https://user-images.githubusercontent.com/3635737/32985395-174e67cc-ccba-11e7-8fa4-24dbf038feb4.png)

Reproduces without extensions: Yes

Everything important is in the screenshot. Minus sign cause bad coloring of data type...

**Comment by sagea** [comment]
I found what was wrong and will put in a PR here shortly

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#543
