### ISSUE TITLE
Integrated terminal color is changing after running the node commands unable the see the output

### ISSUE THREAD

**Issue by himavan** [Microsoft/vscode#38706]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
polymer-snippets|chi|1.0.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
auto-close-tag|for|0.5.3
language-polymer|jon|1.0.3
debugger-for-chrome|msj|3.5.0
polymer-ide|pol|0.6.0
vscode-css-peek|pra|1.3.1
view-in-browser|qin|0.0.5
terminal-tabs|Tyr|0.1.1
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

![image](https://user-images.githubusercontent.com/20299233/32987228-8653ae06-cd0b-11e7-8b6a-92213d4b64d5.png)

Integrated terminal color is changing after running the node commands unable the see the output

**Comment by Tyriar** [comment]
@himavan do you have a custom theme set on cmd.exe or powershell.exe?

**Comment by himavan** [comment]
I had done the operating system reset, after that this issue has been solved. thanks for your commitment towards visual studio code. Your dedication never goes waste. I hope visual studio code evolves the best one
