### ISSUE TITLE
Navigating Items In Git Panel

### ISSUE THREAD

**Issue by oldbasilbear** [Microsoft/vscode#38708]
I would like to have the ability to navigate between the files listed in the Git Source Control Panel, using the keyboard. This ability exists with the File Explorer, Extensions and Search panels. (The Search Panel also allows F4 to be used to move to each search match location).

- VSCode Version: 1.18.1
- OS Version: Ubuntu Linux 16.04

Steps to Reproduce:

1. Open the Git Panel (Ctrl-Shift-G)
2. Unable to navigate from one item to another with keyboard  

Reproduces without extensions: Yes

**Comment by cleidigh** [comment]
@oldbasilbear 
after you open the git panel the commit input has focus if you press Tab you will give focus to the list
then press the down arrow in the first item will have focus/highlight.  Do you see this behavior?
Works for me with Windows and OS X.

**Comment by oldbasilbear** [comment]
@cleidigh Oh my word, how did I miss that so many times? I can only think that because I pressed tab too many times, the focus moved away from the Git panel to an open document tab. 

Yes it works as you described. Thank you for sorting me out - very grateful to you!

**Comment by cleidigh** [comment]
@oldbasilbear 
Actually I can guess what you missed it.  I think there are some inconsistencies in the sidebar navigation.
For instance you can narrow down from the search Input whereas you need to Tab in the git widget
I have gotten used to mentally remembering the different ways to get to the list itself... but as a keyboard only user I've had to get this in my head all the time
Cheers
