### ISSUE TITLE
Serious memory leak

### ISSUE THREAD

**Issue by rmal30** [Microsoft/vscode#38705]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Launch visual studio
2. See memory usage over time

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Please see the tips at https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more details to help us narrow this down.
