### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by shubhankartarkar** [Microsoft/vscode#38719]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No
The Refresh Button does not work

**Comment by maxibanki** [comment]
Please give us more information what you mean with that. Thanks :)

**Comment by shubhankartarkar** [comment]
Sorry but than I realized that it was my computer working slowly
