### ISSUE TITLE
Issue with font

### ISSUE THREAD

**Issue by imrahul81** [Microsoft/vscode#38718]
- VSCode Version: 1.17.2
- OS Version: Parrot OS 3.10 (Debian based ) kernel 4.13

Reproduces without extensions: No
There is an issue with vscode fonts. There are unwanted lines on menu as well as code. This seems to happen only in the OS I am using. In Ubuntu it works fine.
Screenshot attached.
![screenshot at 2017-11-19 18-53-59](https://user-images.githubusercontent.com/23965016/32991140-e15e5eae-cd5b-11e7-9ea3-486aded72c55.png)

**Comment by roblourens** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/35675
