### ISSUE TITLE
断点不暂停

### ISSUE THREAD

**Issue by HBat11233** [Microsoft/vscode#38710]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
python|tht|0.2.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by wangtao0101** [comment]
Running into the same problem, I can't debug my extension any more now.

**Comment by roblourens** [comment]
Please provide more details
