### ISSUE TITLE
xhr failed when trying to add extention

### ISSUE THREAD

**Issue by anjoyhui** [Microsoft/vscode#38716]
- VSCode Version:1.18.1
- OS Version:ubuntu 16.04

Steps to Reproduce:

1.![vscode :XHR failed](https://user-images.githubusercontent.com/26049458/32990726-2a197a6a-ccf4-11e7-9ae4-d4efb3c7dadf.png)
2.![vscode :XHR failed](https://user-images.githubusercontent.com/26049458/32990736-49635602-ccf4-11e7-8601-e81ce914ee06.png)
3.
![1111](https://user-images.githubusercontent.com/26049458/32990877-b86b3c34-ccf6-11e7-967b-8a67090489a0.png)
4.
![11111](https://user-images.githubusercontent.com/26049458/32990879-bec2d34e-ccf6-11e7-9542-05ee2f764285.png)

please help me

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Are you behind a proxy? Any http.proxy settings set? Do you have a network connection when you try this?
