### ISSUE TITLE
sometimes it freeze for 5s 

### ISSUE THREAD

**Issue by tanthanhkid** [Microsoft/vscode#38713]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
code-beautifier|mic|1.7.2
material-icon-theme|PKi|3.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please provide as many details as possible.
