### ISSUE TITLE
Setting based on file extension support

### ISSUE THREAD

**Issue by lethevimlet** [Microsoft/vscode#38717]
Currently I want to disable javascript validation only on files that have an specific file extension,

For example I associate the extension **.js.test** to javascript using glob pattern like so
```
   "files.associations": {
        "*.js.test": "javascript"
    }
```
Now I want to disable javascript validation but not in all javascript files just on the ones that end with **.js.test** is there a way to do so?

I've seen other suggestions of implementations for this like
```
   "files.settings": {
        "*.js.test": {
             "javascript.validate.enable": false
         }
    }
```
but as far as I know, this is not possible at the moment. 

Is there a way to archive this without having to create a custom language extension?

**Comment by mjbvz** [comment]
Possible dup of #35350

**Comment by sandy081** [comment]
Yes.
