### ISSUE TITLE
Moving multiple selected lines with alt-up/down results in chaos

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#38723]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.0
vscode-color|ans|0.4.5
QML|bbe|1.0.0
file-templates|brp|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
gitlens|eam|6.1.1
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.0.15
code-sync|gol|2.5.0
rest-client|hum|0.16.1
redux-snippets|jam|0.0.2
docthis|joe|0.6.0
vscode-codemetrics|kis|1.11.1
vscode-todo|Mat|0.8.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.22
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.18.1
vscode-paste-and-indent|Rub|0.0.8
cmake|twx|0.0.17
sort-lines|Tyr|1.3.0
unity-debug|Uni|1.2.1
gitblame|wad|2.2.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Select several consecutive lines in a file, such as using Shift-Down a few times
2. Use Alt-Up to move those lines upwards, a few times
3. Different lines become selected, and the lines move around a bit chaotically

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Which language? Can you include a gif or screenshots?

**Comment by ericblade** [comment]
.... well, it *did* occur to me 100% in all languages .. until I just started Code after a cold reboot earlier due to a power loss.  It's been bothering me ever since I got 1.18.1 .. but now it just stopped.  I guess I'll mark this closed, and re-open if it comes back.  My apologies!
