### ISSUE TITLE
Installed Tools and Languages on welcome page

### ISSUE THREAD

**Issue by Tes3awy** [Microsoft/vscode#38726]
- VSCode Version: 1.18.1
- OS Version: Windows 10
- Reproduces without extensions: Yes

On the welcome page, the **Tools and Languages** used to be dimmed. However; starting from Version 1.18.0, the Tools and Languages are no longer dimmed. They are already installed though!. And every time a **_Language_** or **_Keyboard Shortcut_** is clicked it's installed again toggling its state from enabled to disabled.

Is this a new feature or is it a bug in the new version?

_In the following snapshot, JavaScript, TypeScript, PHP, and Atom keyboard shortcuts are installed._

Snapshot:

![ven09](https://user-images.githubusercontent.com/11368432/32994166-4121b15a-cd6c-11e7-9d90-cea9287672e5.png)

**Comment by octref** [comment]
This one is partially working. @chrmarti I created #39838 for you.
