### ISSUE TITLE
Tasks 2.0 schemas

### ISSUE THREAD

**Issue by teom10** [Microsoft/vscode#38720]
I'm configuring some tasks but I'm confusing about schema versions, I create a simple task:
``` javascript
{
  "version": "2.0.0",
  "tasks": [{
    "label": "Install",
    "type": "shell",
    "command": "npm install",
    "problemMatcher": []
  }]
}
```
But when I save the file vscode write an error in the tasks output:

```
Error: tasks must provide a taskName property. The task will be ignored.
{
    "label": "Install",
    "type": "shell",
    "command": "npm install",
    "problemMatcher": []
}
```
The [documentation](https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200) says: use the 'label' property instead of taskName.

Where can I find valid examples?
Can I still use the property 'dependsOn'?

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.7.0

Reproduces without extensions: Yes

**Comment by torn4dom4n** [comment]
I think `taskName` change into `label` from VSCode 1.18.0. You will try the lastest of VSCode.

**Comment by dbaeumer** [comment]
Thanks @torn4dom4n for jumping in. Yes, `taskName` got deprecated and replaced with label for consistency. You need to use 1.18.0.
