### ISSUE TITLE
feature request: open debug panel in bottom view instead of left view

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#38725]
The debug view on the left is rather inconveniently sized for usage, it would be much more convenient to have an option to move it into the bottom panel (preferably having it visible along with Debug Console if possible).  Same goes for the Source Control panel.  Both are very inconvenient to use in the left view.

(if there's a way to move these already, please let me know)

**Comment by isidorn** [comment]
DUp fo https://github.com/Microsoft/vscode/issues/38765
