### ISSUE TITLE
How can we run and capture the output npm scripts

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#3872]
I have npm scripts for all my build tasks. How do I run these from Code? To be honest it's not a major problem switching to a console but it would be nice to run from within code. 

I would have thought this was a candidate for standard behaviour shipped with code?

I looked at creating  tasks and the output processor but got quite lost. For example there seems to be only one task allowed.

**Comment by felixfbecker** [comment]
Create a tasks.json like this:
```json
{
  "version": "0.1.0",
  "command": "npm",
  "isShellCommand": true,
  "args": ["run"],
  "showOutput": "silent",
  "tasks": [
    {
      "taskName": "watch",
      "isWatching": true,
      "problemMatcher": "$tsc-watch"
    },
    {
      "taskName": "compile",
      "isBuildCommand": true,
      "problemMatcher": "$tsc"
    }
  ]
}
```
Unfortunately, you must duplicate the tasks if you want to run them from VS Code.
There is a feature request for auto-detecting NPM scripts just like VS Code does it with Gulp and Grunt:
https://github.com/Microsoft/vscode/issues/1777

**Comment by SteveALee** [comment]
Thanks for the example! I agree is a pain having to add each script!

**Comment by dbaeumer** [comment]
Closing this one in favor of #1777
