### ISSUE TITLE
"Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again."

### ISSUE THREAD

**Issue by Abstractcats** [Microsoft/vscode#38731]
- VSCode Version: 1,18.1
- OS Version: WIN8.1 X64
I've tried the x32, and x64.
Trying to zoom in/out, causes error.
Also, trying to change color scheme, causes the same error:
"Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again."
Steps to Reproduce (For trying to zoom, and change color scheme):
1.  Using Control +/-
2. Trying to zoom in/out, from the View drop down.

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@Abstractcats Can you please open your settings and check if there are any errors in that file?

You can do that from File -> Preferences -> Settings

**Comment by Abstractcats** [comment]
@sandy081 Sure, here is a screen shot, of what is in the file. Thanks.
![vs codetheme zoom error](https://user-images.githubusercontent.com/20057965/33030991-e2d4cf9a-cdea-11e7-9d68-7cba1c431188.jpg)

**Comment by sandy081** [comment]
@Abstractcats There is a reg squiggle which mean the file has some errors. You can also see that in Problems view. Hence, the actions are not working. Please fix the file by removing all errors and try again.

**Comment by Abstractcats** [comment]
@sandy081 Got it, thanks! I removed the second line of code("clang.executable: "clang" ") and it fixed both issues.
