### ISSUE TITLE
question: dealing with key confusion when using user snippets and code completion

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#38734]
So, when I try to use snippets, it is really difficult, because tab switches between fields in the snippet ($1, $2, etc), but it also is used for code completion.  

Anyone know a way to re-bind some keys or some settings options that might help with this?  I always find myself auto-completing things that i don't want, instead of going to the correct field in the snippet, and having to do some undo actions to get it right.

**Comment by user3323** [comment]
I've changed it in keybinding to "Shift + Enter"

command "`jumpToNextSnippetPlaceholder`" is responsible for this:

![image](https://user-images.githubusercontent.com/24613274/33000932-85747e5e-cdb3-11e7-8af3-54b34caf6427.png)

couple of days and I've got used to it.
