### ISSUE TITLE
Git Unbearably Slow

### ISSUE THREAD

**Issue by murphmar** [Microsoft/vscode#3873]
Myself and a few co-workers have fully switched over to Code and so far so good, except for git speed. The git integration works, but it's ridiculously slow. I'm talking 5+ minutes to sync. Just connecting to a very small private GitHub repo. I'm not sure how to fix this or how to narrow down what the possible issues could be on our end. Is there any way to get a verbose logout of what's happening, perhaps?

Running the latest release of VS Code, and Windows 7.

**Comment by joaomoreno** [comment]
Code simply spawns `git.exe`, so whatever speed that gives you is what Code gives you.

What version of git do you have? How big is your repository? Is it in a network share or locally? Is it slow just for you or for your co-workers as well? What exactly is slow, showing the list of modified files, staging files, committing, pushing, pulling?

**Comment by murphmar** [comment]
Ahh, ok. Fair enough.

Latest version of Git for Windows is installed. The repo is very small, just a small angular app and it's stored on GitHub. It's slow for all of us. Basically any of the actions are slow. Syncing in particular.

**Comment by joaomoreno** [comment]
What version **exactly** of git do you have? Is it also slow in the command line: when you open the Command Prompt and run some git commands there, for example? Can I have access to the repository?

**Comment by murphmar** [comment]
You can close this. I appreciate the help, though, considering it didn't appear to be anything really Code related :).

My git install actually was older, and i don't believe i had the cache option before. In addition to that my global .gitconfig was stored on a very slow network drive (admin set $HOME that can't be changed), which has since been moved. Everything is moving along nicely now!

**Comment by joaomoreno** [comment]
Very happy to read that! Keep the feedback coming!
