### ISSUE TITLE
The constant in lower case is defined as a variable

### ISSUE THREAD

**Issue by dedmazayukr** [Microsoft/vscode#38735]
Why the constant in lower case is defined as a variable ? The constant must be constant, regardless of the register.

- VSCode Version: Version 1.18.1
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Write for example: (lowercase and uppercase)
    `const variable = 'as variable.other.readwrite';`
     `const CONSTANT = 'as variable.other.constant';`

2. Press `ctrl+shift+p`, and select `Developer: Inspect TM Scope`

3. Click on word `variable` --> variable.other.readwrite (wrong)
![image](https://user-images.githubusercontent.com/22115961/32995597-8f387d7a-cd7f-11e7-81b7-2498691091c7.png)

4. Click on word `CONSTANT` --> variable.other.constant (correctly)
![image](https://user-images.githubusercontent.com/22115961/32995622-da314cb2-cd7f-11e7-8b72-41ccc073a317.png)

Reproduces without extensions: Yes
Languages: javascript and typescript

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#542

**Comment by dedmazayukr** [comment]
I want to pay attention, this behavior is not only in the typescript , but also in the native javascript.
