### ISSUE TITLE
Terminal process crashes when canceling a cancel

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#38732]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063

---

Steps to Reproduce:

1. `yo code` -> new Typescript extension
2. `ctrl + shift + b` to start build task
3. In terminal, `ctrl + c` to cancel build task
4. `Terminate batch job (Y/N)?`
5. `n` (I don't want to cancel)
6. Terminal crashes

```
The terminal process terminated with exit code: 1
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9
```

**Comment by Tyriar** [comment]
Tracking in https://github.com/Tyriar/node-pty/issues/168
