### ISSUE TITLE
There are no active source control providers.

### ISSUE THREAD

**Issue by mustafawm** [Microsoft/vscode#38737]
- VSCode 1.18.1 (1.18.1)
- macOS 10.13.1

Hello,

VSCode is not picking git repos! although git lens and git blame seem to work fine (when enabled).

![screen shot 2017-11-20 at 11 33 13 am](https://user-images.githubusercontent.com/13101565/32997648-ce8e8228-cde6-11e7-9a45-891af2105830.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Interesting. Where is your `git` executable located?

**Comment by mustafawm** [comment]
whereis git returns : `/usr/bin/git`
If it helps, i've recently switched to `fish` shell, but i just switched back to `zsh` and had the same issue
I even tried the insider latest (1.9) edition, same :\

**Comment by mustafawm** [comment]
also if it helps, phpstorm seems to work with no problem :\ (the only problem is that it is not vscode)

**Comment by mustafawm** [comment]
Solved by manually setting `"git.path": "/usr/local/bin/git"` in settings

Although `type/which git` returns `/usr/local/bin/git` so vscode should have been able to read it right? 

Anyway! Thanks for your collaboration and the great work you guys are doing on VSCode :) 

Cheers,

_closing it, unless you want to investigate further_
