### ISSUE TITLE
Open File dialog gets screwy over time

### ISSUE THREAD

**Issue by Toadmyster** [Microsoft/vscode#38741]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
spfx-debug|eli|0.0.3
spfx-essentials|eli|0.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
json-to-ts|Mar|1.5.3
sp-tools|Mik|0.3.0
mssql|ms-|1.2.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
autoimport|ste|1.5.3

---

Steps to Reproduce:

1. Use VS Code for a while working on SPFx web parts
2. Try to Open File while working with an open folder
3. The file picker is missing icons, mapped drives, and is almost unusable (see images below)

VS Code Open  File Dialog
![image](https://user-images.githubusercontent.com/25941076/33001040-677bce14-cd60-11e7-8da2-39f842c88cb6.png)

Should look like this--Notice I can't open files from my mapped SharePoint drives
![image](https://user-images.githubusercontent.com/25941076/33001138-ed497aaa-cd60-11e7-8b09-89ca360150e3.png)

Reproduces without extensions: Yes/No: YES, problem still exists.  Only a reboot fixes

**Comment by bpasero** [comment]
Nothing we can control on our end, maybe a Windows insiders issue? Closing.

**Comment by Toadmyster** [comment]
It doesn't happen to notepad++ or any other software that uses the system file picker. Doesn't that kind of point to VS Code and they way it implements the system interface?  It's not a memory issue as I have 32GB of RAM and never go over 40% utilization. Besides, closing Code and verifying no processes are still running would also eliminate that possibility. I can work around the issue by using Notepad++ but I still think someone should look into this.
