### ISSUE TITLE
Mac - my vscode cannot identify "printf"

### ISSUE THREAD

**Issue by KingOfDuck** [Microsoft/vscode#38742]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
vscode-eslint|dba|1.4.3
CppSnippets|har|0.0.13
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.2

(5 theme extensions excluded)

    Here is my settings for paths

"name": "Mac",
            "includePath": [
                "/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/bits",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/tr1",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/tr1",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/bits",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]

  The file is "main.cpp" , a cpp file.
  I've included stdio.h also, but there's always an error occurs in my editor, others such like std::string do not have the same problem.
  I can still compile my works with gcc/clang, though the editor occurs the problem. 
  When I press "command" and move my mouse to the 'printf' function, the editor can even jump to its declaration... How could it say "printf is unidentified"... 

  I'll upload pictures to explain this strange problem...
<img width="523" alt="printscreen" src="https://user-images.githubusercontent.com/6134155/33001289-cc21a456-cde7-11e7-9f32-7e41c10f90ab.png">

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#1268
