### ISSUE TITLE
Need option(s) to remove (less useful) status bar indicators

### ISSUE THREAD

**Issue by guardrex** [microsoft/vscode#3874]
I built the Status Bar Tasks extension to solve I problem I was having getting VS Code Tasks to fire off quickly.

![sbt](https://cloud.githubusercontent.com/assets/1622880/13609851/94ac27a2-e50f-11e5-947f-2ea24591aa0f.PNG)
https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks

I've noticed recently that default (less useful to me) status bar indicators are taking up a lot of real estate in the status bar on my laptop (smaller screen width than my PC monitor), so I can't fit all of my Tasks in the status bar on my laptop.

I'll ask over in the OmniSharp repo about removing the word "Running." Having indicators for the spacing, character set, end-of-line sequence, language mode, and feedback icon are totally useless to me and can be accessed easily enough via the cmd palette  ...

![sb](https://cloud.githubusercontent.com/assets/1622880/13609873/ab2e3f7e-e50f-11e5-8a90-fedd4dc47dc2.PNG)

I don't see anything on SO or in the docs on how to turn some or all of these indicators OFF. If it can't be done currently, may I suggest workspace option(s) as a feature to remove some/all of them (the VS Code ones anyway ... I understand third party ones would need to be addressed by those vendors)?

**Comment by Tsourdox** [comment]
Any updates on this? Would be super nice to be able to hide some items! ✌️

**Comment by asilvadesigns** [comment]
@Tsourdox as a temp solution, I'm doing the following:
```
/**
 * STATUS-BAR | hide a few items
 */
.monaco-workbench .editor-status-indentation,
.monaco-workbench .editor-status-encoding,
.monaco-workbench .editor-status-eol {
  display: none !important;
}
```
Using this plugin for custom css: 
https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

There are a few more items that can be hidden, but those were among the few which had css classes. Hope that useful.

**Comment by flipdoubt** [comment]
Why we always need to know the current tab size in the status bar escapes me.

**Comment by iansan5653** [comment]
At the very least, we should be able to click and drag to rearrange the items. I have 18 different items sitting in my status bar and some of them are far more useful than others.

**Comment by olafurpg** [comment]
One possible solution would be to have a setting to control what installed extensions are allowed to create status bar items. For example, it would be nice if it was possible to disable status bar items created by the Live Share extension but not the Python extension.

**Comment by ryansully** [comment]
My idea was to be able to configure a number-weighted priority system for status bar items, so if the window becomes too small to display all the items, the ones with lower priority would be removed first.

**Comment by lonix1** [comment]
@ryansully Who decides the priority?

**Comment by ryansully** [comment]
@lonix1 Priority would be user-configurable, so the user would rank status bar items as they see fit.

**Comment by iliyang** [comment]
To add to the above comment, a default priority (e.g. 0) could be assigned to every status bar item all status bar items, and the user could override the priority for each item/extension in their settings.

**Comment by Nxt3** [comment]
Could you guys stop commenting on unless you have something useful to add?

Spoiler alert: you have no new information to add unless you're a Microsoft employee and commenting on this sends and email to hundreds of subscribers! Please ceasenyout commenting.

**Comment by ryansully** [comment]
Seeing as this is an open source project, I'm sure contribution in any form is welcome from more than just Microsoft employees.

In the meantime, here is something you will hopefully find more useful.
![Screenshot_20190525-234936](https://user-images.githubusercontent.com/51629/58378448-d3d78300-7f48-11e9-9805-df6f885859f9.png)

**Comment by Nxt3** [comment]
"Me too" comments aren't helpful.

**Comment by iansan5653** [comment]
I see two potential solutions here:

The Firefox method: toolbar items can be dragged and dropped to rearrange, and any that the user wants to hide can be dragged into an overflow menu. This has the advantage of making all items easily accessible at all times, but because they are different widths, an overflow menu of the items would be awkward.

The Windows method: items can be dragged and dropped to rearrange, and shown/hidden with checkboxes in a context menu. This means that the user could hide an item and totally forget it exists, but this may be desired by many.

**Comment by bpasero** [comment]
Pushed an initial version to master:

![grid-tw](https://user-images.githubusercontent.com/900690/59035480-ab675700-886d-11e9-9842-f0369a5df0e8.gif)

Limitations:
* currently due to our extension API you can either show or hide all contributions of one extension to the status bar (reported as https://github.com/microsoft/vscode/issues/74972)
* currently the editor status is still composed of just one entry and I will look into splitting them up into many so that they can individually be hidden

Feedback welcome (will be in insiders tomorrow).

**Comment by bpasero** [comment]
This is now complete, each editor related entry is now an individual item that can be disabled. They also individually overflow when the window size is small allowing for more info to be shown on small space (previously the entire thing would hide).

![before](https://user-images.githubusercontent.com/900690/59110222-ec7b6c00-893e-11e9-9e43-c95a1db35020.gif)
