### ISSUE TITLE
TS died 5 times

### ISSUE THREAD

**Issue by actionsmile** [Microsoft/vscode#38747]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
beautify|Hoo|1.1.1
vsc-material-theme-italicize|Ser|0.0.14
vscode-nextgenas|bow|0.7.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
react-redux-react-router-snippets|dis|0.3.5
gitlens|eam|6.1.1
tslint|eg2|1.0.22
file-icons|fil|1.0.7
vue-snippets|hol|0.1.5
atom-keybindings|ms-|3.0.2
node-debug2|ms-|1.19.0
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vscode-react-native|vsm|0.5.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open project
2. Nothing to do
3. Wait some time (for about 5 minutes)
4. …
5. PROFIT!

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce if you disable all extensions? 

Also, please open the output panel and go to the `TypeScript` section. Are there any error messages in there?

**Comment by actionsmile** [comment]
this is unpredictable bug :) Absolutely random defect

**Comment by mjbvz** [comment]
Anything in the output panel?

**Comment by actionsmile** [comment]
nope… suppose it happened occasionally and I think it was other_application/ram/weather/ufo problem.
