### ISSUE TITLE
TS AutoImport style config enhancement

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/vscode#38743]
I love the new TS autoimport, saves so much time having to manually type out imports, also getting auto complete for things not even in your file is amazing.

That being said, a few configuration options would be nice:
- Our style guide means no semicolons, but the code automatically adds one (so I have to cursor up to delete it).
- Additionally our style guide also calls for absolute imports to come before relative ones, but code just places it at the end (so I have to go and move it manually).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20161
