### ISSUE TITLE
Disable workspace

### ISSUE THREAD

**Issue by dps999** [Microsoft/vscode#38752]
Hi,
i'm working in Unity and should have ability to open different folder/ projects from the Unity.
After workspace feature released i can't open single project without losing all windows opened.
It always open untitled workspace. How to back to single workspace by default without losing widows?

**Comment by dps999** [comment]
Want to add, sometimes it open different project at once, project which i've just closed and new one.
And it can be a problem if the projects are the same and just backup copy. I don't know why it open 2 projects at the same time, i've even not saved workspace.
Just disable workspace feature will help
![2017-11-20_10-24-36](https://user-images.githubusercontent.com/1697478/33006858-08a417e8-cddd-11e7-8a75-d9e2014ca4e8.png)

**Comment by ccbentlee** [comment]
Yeah! ~ i have the save problem here, it always open two windows and i don't know why.

**Comment by Tyriar** [comment]
You can avoid the workspace feature by not converting your windows to workspaces by avoiding adding folders to the workspace.

If you're in a workspace and want to get out of it you can close the workspace via the file menu.

**Comment by dps999** [comment]
Unfortunately i not converted anything.
Unity by default opens it like a workspace.

I tried to close workspace but anyway it opens like workspace and if i try to open separate c# file from Unity it opens it in the new workspace always.

**Comment by Tyriar** [comment]
Sounds like it's an issue with an extension then if it always opens as a workspace and/or that's the UX they chose to go with.

**Comment by dps999** [comment]
Thank you @Tyriar 
I will redirect my question to the Unity extension developers.
