### ISSUE TITLE
Git: warning: LF will be replaced by CRLF in .vscode/launch.json.

### ISSUE THREAD

**Issue by ntiller123** [Microsoft/vscode#38755]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ntiller123** [comment]
on git  commit error stopping all changes beign commited

**Comment by joaomoreno** [comment]
Please configure your git not to do that. https://git-scm.com/docs/git-config#git-config-coresafecrlf
