### ISSUE TITLE
Settings Issue - Wrong Syntax 

### ISSUE THREAD

**Issue by lucical** [Microsoft/vscode#38759]
Hi,

After updating to the newest VCS version I have the problem with user settings. Not sure how to fix it as I don't see a syntax error.

Could you please take a look?

Thanks! 

![screen shot 2017-11-20 at 09 56 00](https://user-images.githubusercontent.com/24703586/33010051-56823ac0-cdd9-11e7-8d15-6e9fa3b9a68c.png)

**Comment by CoenraadS** [comment]
```
{
Your settings here
}
```

**Comment by sandy081** [comment]
Above fix should be fixing your issue.
