### ISSUE TITLE
Emmet's bem filter cuts out part of a class name after dash.

### ISSUE THREAD

**Issue by yerzhant** [Microsoft/vscode#38768]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.10.0-38-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.22
php-intellisense|fel|2.0.1
path-autocomplete|ion|1.7.0
vscode-scss|mrm|0.6.2
partial-diff|ryu|0.5.0

---

Steps to Reproduce:

1. type `.block>.-my-element|bem`;
2. press _Tab_ or _Enter_;

`-element` gets cutted out.

**Comment by ramya-rao-a** [comment]
Logged upstream issue for this https://github.com/emmetio/html-transform/issues/6
