### ISSUE TITLE
Black Screen was displayed after sometime inactivity or when windows goes to sleep 

### ISSUE THREAD

**Issue by bhargavkonkathi** [microsoft/vscode#38760]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode with and open files which you want to edit. Edit some files and keep open editors for files.
2. Wait for windows to lock your screen , i.e windows will sleep your computer.
3. Go back to VSCode, it will display blackscreen unedited files and all opened editors will be shown as block , not even clickable
4. Same problem is happening for shell also. After sometime of inactivity black screen was displayed.
 

Reproduces without extensions: Yes/No

Screenshots
![image](https://user-images.githubusercontent.com/24550636/33010472-9e55127e-ce00-11e7-9acd-2848d05672cb.png)

**Comment by bpasero** [comment]
Does it reproduce if you run `code --disable-gpu`?

**Comment by bhargavkonkathi** [comment]
Yes, It is happened in both cases.  But I usually launch VSCODE normally not from command prompt. 
It would be nice to see this issue get fixed, May be I'm the one only getting this issue. It feels like black screen after inactivity of windows can't do anything. Again We need to reopen VSCode to work normal.
Thanks.

**Comment by fab35** [comment]
I have the same issue.
After days opened (or over a week-end) VScode becomes unusable. 
Same issue on both Win10 and Win7 pro x64.

**Comment by igloo** [comment]
On Mac, with a Parallels VM Ubuntu 18.04 I have the same black screen problem when Ubuntu is suspended for inactivity. May be we have missed something?

**Comment by kinghuthman** [comment]
Understanding that this issue was closed with it being fixed?
