### ISSUE TITLE
Where to find sharing option in vscode?

### ISSUE THREAD

**Issue by baj9032** [Microsoft/vscode#38763]
Just look at my question on stackoverflow

https://stackoverflow.com/questions/47388279/where-to-find-sharing-option-in-vscode

**Comment by maxibanki** [comment]
Not public yet, see => https://code.visualstudio.com/blogs/2017/11/15/live-share

**Comment by itssuyog96** [comment]
How to start sharing in the latest build for master branch? Or is it on the different branch? Please clarify.

**Comment by maxibanki** [comment]
still not public yet
