### ISSUE TITLE
Viewlets in the panel area and vice versa

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#38765]
Since both viewlets and panels are composites it would make sense to allow users to drag n drop viewlets into the panel area and panels in the viewlet area.

**Comment by clankill3r** [comment]
Why is this out-of-scope?

**Comment by isidorn** [comment]
This is actually now almost posisble, just use drag and drop of views between viewlet and panel area.

**Comment by clankill3r** [comment]
I don't get what you mean.

**Comment by Outcue** [comment]
You can drag an individual "view", such as the VARIABLES view into the panel area below the text editor. You can then drag additional views from the Run view on the left into the VARIABLES view you just dragged. You will then have two views in the VARIABLES panel.  As Isidor said, "It mostly works." It would be nice to have a pre-populated panel just for debugging.
