### ISSUE TITLE
Settings group header is not correctly rendered

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#38769]
- VSCode Version: Code - Insiders 1.19.0-insider (c8c6b13528c03986b8dad654cb1d3e796e8dbe97, 2017-11-20T05:13:59.281Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Open user settings.

![image](https://user-images.githubusercontent.com/1330321/33013463-22750c08-ce1f-11e7-8c16-3368d1838077.png)

The `Editor` group should be *above* the `Workbench` group, the spacing is not correct either.

![image](https://user-images.githubusercontent.com/1330321/33013517-59d2992c-ce1f-11e7-93cd-4a5af43f1eb3.png)

When expended, the `Editor` group title overlaps with its content.

My investigation shows that the `Editor` group header is in invisible area thus it has 0 height. (Maybe hided by these lines)

https://github.com/Microsoft/vscode/blob/0d438de58d22d7ac7883f712bcefba3c97d93bcb/src/vs/workbench/parts/preferences/browser/preferencesRenderers.ts#L397-L402

Only Insiders version affected, 1.18 is ok.

**Comment by yume-chan** [comment]
Seems it has been fixed in today's Insiders build. Thanks.

**Comment by sandy081** [comment]
Yes. Fixed yesterday
