### ISSUE TITLE
Support git commit message syntax highlighting

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3876]
Now that it is possible to set the vscode as git's cli editor (https://github.com/Microsoft/vscode/issues/744), it would be great to highlight `COMMIT_EDITMSG` [like Atom does](https://f.cloud.github.com/assets/671378/2402807/fbebfeea-aa26-11e3-94c0-7caffd1774e8.gif).

**Comment by felixfbecker** [comment]
Please also hunks. It's when you use `git add -p` and press `e`, the default git editor pops up to edit the patch manually. You have `+`, `-` or a space in the first column (all indentation breaks should get shifted +1 column), `@@` line indicators and comments with `#`

**Comment by bpasero** [comment]
@Tyriar why don't you go ahead and publish an extension from the Git TM bundle? I found it here: https://github.com/textmate/git.tmbundle

Would be nice to have it :)

**Comment by bpasero** [comment]
I started a first cut of the extension here: https://github.com/bpasero/gitmode

**Comment by joaomoreno** [comment]
:heart:

**Comment by Tyriar** [comment]
This would be included in extensions/ eventually right? Thoughts:

- Intellisense is on which is pretty annoying for commit messages
- I created https://github.com/Microsoft/vscode/issues/3991 to add styles for the new/changed/deleted file styles
- My `.gitconfig` looks great

**Comment by bpasero** [comment]
Using https://github.com/textmate/git.tmbundle as extension now for git commit message and git rebase. I did not add it for gitconfig because our existing Ini support already picks it up.
