### ISSUE TITLE
Emmet: Wrap Individual Lines can't handle words containing periods

### ISSUE THREAD

**Issue by bennyschaefer** [Microsoft/vscode#38766]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro build 16299

**Steps to Reproduce:**

1. Enter list of filenames in a file (or any word containing a period without neighboring spaces; also happens with config parameters like `module.parameter.name`)
```
photo1.jpg
photo2.jpg
```
2. Select list with cursor
3. "Emmet: Wrap Individual Lines with Abbreviation" (via F1)
4. Enter `ul>li*`
5. Hit Enter

Reproduces without extensions: Yes

**Expected Results:**
The individual lines should be treated as text in the resulting HTML.
```
<ul>
    <li>photo1.jpg</li>
    <li>photo2.jpg</li>
</ul>
```

**Actual Results:**
The individual lines are treated as a link which is also appended to the parent tag, resulting in invalid HTML.
```
<ul>
    <li href="http://photo1.jpg">photo1.jpg</li>
    <li href="http://photo2.jpg">photo2.jpg</li>
</ul>
```

**Comment by ramya-rao-a** [comment]
@bennyschaefer Nice catch, Thanks for reporting!

**Comment by ramya-rao-a** [comment]
Logged upstream issue https://github.com/emmetio/expand-abbreviation/issues/15

**Comment by ramya-rao-a** [comment]
Upstream issue has been fixed with https://github.com/emmetio/html-transform/pull/8
The fix will be out in the Insiders build of Dec 4th
