### ISSUE TITLE
Two VSCode opens up with Unity3D and Unreal Engine

### ISSUE THREAD

**Issue by RubyGemer** [Microsoft/vscode#38771]
When ever I open C# script from Unity3d or C++ from Unreal Engine. Two instances of VSCode opens up. How do fix this issue? 

Please watch this video on Youtube to clearly understand this bug  ---> 

https://www.youtube.com/watch?v=FNdLJat0kow&feature=youtu.be

**Comment by bpasero** [comment]
@RubyGemer I cannot reproduce but this might depend on user settings. Do you have any?

You seem to have an untitled workspace (the first window) which we restore on startup. If you close that window we ask you to save the workspace and if you chose not to, it will go away. You can also save the workspace and this issue will also be gone.
