### ISSUE TITLE
Potentially incompatible/unsupported import statements added to code by default

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#38773]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.1.2
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.5.2
output-colorizer|IBM|0.1.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|3.5.0
code-spell-checker|str|1.4.12

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Type `re` and press Enter.
2. Code will "auto-import" `read` from `fs`.

Even if we wanted this behavior, the import statement is inserted at the wrong location and violates our style rules. `import` is also only at experimental support level in Node (behind a flag), so I really don't understand this behavior.

**Comment by mjbvz** [comment]
You can disable auto imports by setting `"typescript.autoImportSuggestions.enabled": false` or by pressing `esc` before accepting the completion

Can you please provide an example of where the import being added incorrectly?

**Comment by oliversalzburg** [comment]
> typescript.autoImportSuggestions.enabled
Thanks a lot!

I'm not sure what controls this behavior. As in, what modules it suggests for auto-import. This just started happening in projects where it didn't happen before. These are NodeJS projects, but I don't know how Code identifies those. But this happens in all the projects I'm working on.

I've tried to reproduce this in https://github.com/villadora/express-bunyan-logger because I have it open right now and it happens there as well:

![image](https://user-images.githubusercontent.com/1658949/33076044-cf09dcda-cecb-11e7-8a36-46984e4c16f8.gif)

IMHO there are many things wrong with the current approach. The most important one being that it is enabled by default.
Other than that, it generates invalid code for the current context, the place where the code is inserted is potentially undesirable (no control over sorting of imports, code inserted above file headers), being other things on the list.

**Comment by oliversalzburg** [comment]
`typescript.autoImportSuggestions.enabled` does not seem to have any effect when put into the settings of my workspace.

**Comment by alirobe** [comment]
I'm having the same issue. This is an absolutely terrible default, and it should be turned off.

**Comment by Nighthawk22** [comment]
My best auto import so far 
`import { Dispatch, Dispatch } from '../../../../../Library/Caches/typescript/2.6/node_modules/@types/react-redux';` 😂

**Comment by alirobe** [comment]
Related but not the same: I've requested the entire feature be disabled. I can't see why anyone could want this behavior by default.

https://github.com/Microsoft/vscode/issues/38911

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/20292 to track using require for auto imports and the import being inserted in the wrong location relative to existing requires.
