### ISSUE TITLE
Some of my files get erased

### ISSUE THREAD

**Issue by lateek35** [Microsoft/vscode#38777]
Version:
- VSCode Version: 1.18.1
- OS Version: Mac OS 10.13

It first happened when I was trying to solve a compiling problem in my project. Suddenly I figured out that somes of my files get in some way empty. Still exist in the project but 0 bit. So I guessed it was probably something that fucked up in my gulpfile or maybe wrong operation from my side. But today it happened again. 
I used `CMD + R` to open another recent project (not the same build system), all my tabs get restored but one file was empty. It was not pushed to git, so that half a day of work lost. So annoying :/
I can't give you any step to reproduce because I have no ideas of when it happens. It will probably not be enough to solve it but maybe someone already had this horrible bug and know where it come from.

**Comment by bpasero** [comment]
Without steps this is hard to tell :-/
