### ISSUE TITLE
Customisable welcome page (feature request)

### ISSUE THREAD

**Issue by msageryd** [Microsoft/vscode#38778]
It would be great if we could customise the welcome page per project (workspace). This would be a great place to introduce new developers to a project and point out good to know things.

This might be the README.md file from the repo or a specially crafted welcome page with links, hints, etc.

**Comment by fabiospampinato** [comment]
An extension could be created in order to automatically open the `readme.md` file.

**Comment by msageryd** [comment]
Yeah, it would be good. But I was thinking of being able to build a welcome screen with for example the following elements:

- "Show welcome page on startup" checkbox
- Links that will open certain files in the editor
- Links to related projects. Could be opened in a new editor.
- Columnar layout as the current welcome page

**Comment by fabiospampinato** [comment]
I still think this is a good extension candidate, addressing your points:

1. The extension can have a setting that disables it, or simply manually disabling it on a per-workspace basis would be enough.
2. These kind of links can already be defined in Markdown, they look like this `[my file](file.foo)`
3. A link to a related project can simply be a Markdown link. Opening it in a new editor would be tricky to do, how does it know where it's stored in my system? If the point of this is switching between different projects fast I'd recommend my [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus) extension.
4. Columns can be added in Markdown as well.

**Comment by msageryd** [comment]
Great, I didn't know that vscode could follow file links in markdown. I'm actually using "Project Manager". I forgot that it is an extension. The projects in Project Manager is the ones I thought of linking to, but this is the least important point. 

I'm not an extension author. Have never tried it out. But you, sir, seem to be a fine extension author. I'll check out Project+ for sure. Feel free to give the **WelcomePage+** extension a stab =)

Or maybe include this functionality in Project+?

**Comment by fabiospampinato** [comment]
I think it would be better to have a separate extension for this. 

Actually now that I'm thinking about it I don't think there's an API for knowing if there are any files opened  (https://github.com/Microsoft/vscode/issues/15178) 🤔. I'll ponder on this when I'll get some more free time.

**Comment by chrmarti** [comment]
See also #31450.

**Comment by isobarbaric** [comment]
has there been any progress on this :(

**Comment by dseynhae** [comment]
I was totally surprised that this request does not exist already. And it definitely should NOT be addressed through an extension, it should be built-in behavior.

I work at a major hardware/software provider, and I'm looking for the best way to introduce developers to shared projects: all our projects are repositories on GitHub... We can make no assumptions on what extensions would be installed in the VS Code environment that the user has.

So picking up and rendering a "Welcome.md" from the main WorkspaceFolder with be absolutely perfect... 

This would allow us to provide:

* the requirements for the project
* instructions to get started
* links to all relevant information sites
* important announcements (release branching,...)
