### ISSUE TITLE
[insiders] VS Code no longer finds GIT

### ISSUE THREAD

**Issue by AndyBay** [Microsoft/vscode#38775]
Using the latest Insiders on Windows 10.
I have GIT installed at `C:\Git`.
![vscode_git_find_problem_warn_msg](https://user-images.githubusercontent.com/1170184/33017129-73164e20-cdf1-11e7-9db3-9325a1c99b3f.png)
![vscode_git_find_problem](https://user-images.githubusercontent.com/1170184/33016987-eacda91e-cdf0-11e7-9a91-538dab6d922f.png)

**Comment by joaomoreno** [comment]
Please configure it using the `git.path` setting, like the alert box suggests.
