### ISSUE TITLE
Source control providers

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#38787]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open folder which has in some subfolder other repositories like:
  - /.git/...
  - /libs/PHPWord/.git/...
2. switch to "Source Control" tab

Expected: "Source control providers" block with both repositories.

Actual: no "Source control providers". Just active repository of the root of the opened folder.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/37947
