### ISSUE TITLE
Format code makes HTML vanish when prior <div> block is collapsed

### ISSUE THREAD

**Issue by uclnj** [Microsoft/vscode#38783]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
vuejs-extension-pack|mub|0.2.1
vetur|oct|0.11.3
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.  Take div block, collapse it, format code below the collapsed block.  The code after the <small> tags disappears (not just hidden, removed.)

![screenshot 2017-11-20 08 04 48](https://user-images.githubusercontent.com/835685/33019842-037e7faa-cdca-11e7-92c6-998055a5127d.png)
![screenshot 2017-11-20 08 04 55](https://user-images.githubusercontent.com/835685/33019843-03869c8a-cdca-11e7-952f-c83efed7ce95.png)

2.  expand the collapsed div block, format code, works as expected.  I tried with a stripped down version of the page and the formatting works as intended.  Vue/Lint show no missing tags or malformed HTML.

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
@uclnj I'm not able to reproduce, Can you paste a code sample that shows the problem?
Do you use 'Format Document' or 'Format Selection'?
