### ISSUE TITLE
feature request: add ability to generate info to file a bug into a new text window

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38784]
VSCode 1.18.1
OS Windows 7

It would be really helpful to have an item in the 'Help' menu which generated a text dump of the VSCode configuration information (version, OS, extensions, etc.) into a text window. This would give us the ability to copy and paste the information most helpful to the Code team into issues, especially for those of us who file issues on different machines than the running instance of Code.

Additionally, this capability could also be used to send queries to the installed extensions to disgorge their configuration information (in the case of the 'C/C++' extension, current database names, sizes, etc.)

**Comment by bpasero** [comment]
I don't think that is needed anymore, you can do Help > Report issue and I recently added a "Copy" button to the about dialog.
