### ISSUE TITLE
option to always show Source control providers

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#38785]
Can you add option to always show "Source Control Providers" in Source Control tab? Even if it has only 1 repository.
It helps to get before eyes current branch name when user preparing next commit.

thank you.

**Comment by shobhitchittora** [comment]
@joaomoreno I'd like to take this up, as I already have some context with the vscode source and would like to learn about scm and viewlets.

**Comment by joaomoreno** [comment]
@shobhitchittora Go for it!

**Comment by shobhitchittora** [comment]
@SailorMax  I think you can very well check the current branch in the status bar at the bottom. You can look at this and know the branch you'll be pushing to. 

Please check the screen-grab below.

<img width="294" alt="screen shot 2017-11-26 at 12 46 23 pm" src="https://user-images.githubusercontent.com/4711855/33237932-dafe1f26-d2a7-11e7-992d-545f47208964.png">

@joaomoreno I think this is redundant and request can be closed.

**Comment by SailorMax** [comment]
@shobhitchittora 
I don't agree. This is user unfriendly keep useful information of single action in different corners of possible large window. When I prepare commit in top left corner I need to see target branch in top left corner. Not in any other corners.
I ask to add setting. You did not see any changes if you don't need it.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/39245. Setting is `scm.alwaysShowProviders`.
