### ISSUE TITLE
FTP not connect !

### ISSUE THREAD

**Issue by toniupper** [Microsoft/vscode#38792]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.23
php-debug|fel|1.11.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.8
phpcs|ika|0.7.0
text-marker|ryu|0.10.1
bootstrap4-vscode|the|3.0.0
vim|vsc|0.10.4
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please include enough details to repro the issue. If this is from an extension, please file an issue on their repo.
