### ISSUE TITLE
Spelling mistake: "Uncought Exception"

### ISSUE THREAD

**Issue by Arnaud73** [Microsoft/vscode#38799]
- VSCode Version: 1.18
- OS Version: Mac OS Sierra

At some point Visual Code got stuck on an exception that was not handled.

The dialog was referring to an "uncought exception" (with an O)

**Comment by joaomoreno** [comment]
A full text search for `uncought` in our sources doesn't find anything. This must be caused by an extension. Please figure out which one it is and file it in the appropriate extension repository.
