### ISSUE TITLE
PromiseSource and Barrier are the same thing

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#38796]
We `PromiseSource` and `Barrier` and I am very sure they both do the same. Please let only one survive.

**Comment by joaomoreno** [comment]
We must FIGHT to the end.

**Comment by joaomoreno** [comment]
I don't understand though... Are they really the same thing?

**Comment by jrieken** [comment]
I believe so... Both expose a promise that can be resolved from the outside [`Barrier#open`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/node/barrier.ts#L31) vs [`PromiseSource#complete`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/async.ts#L280).

**Comment by alexandrudima** [comment]
I prefer to keep Barrier, because I like to think of it as a separate synchronization mechanism than promises, even if it uses promises as its implementation.

So, I would live with the "duplication".

**Comment by jrieken** [comment]
Well, the *single* usage of the `PromiseSource` seems like a good usage for `Barrier` because it seems to synchronise on the shared process startup/spawning

**Comment by alexandrudima** [comment]
:+1: To replace the usage of `PromiseSource` with `Barrier` in `SharedProcess`.

@joaomoreno It does look like you have a barrier type of usage going on in the `SharedProcess` class. The only implementation diff I can spot is that the `PromiseSource` can be canceled, but that might be an implementation mistake. The `PromiseSource` can also be `errored`, but that appears to be not used.

**Comment by joaomoreno** [comment]
Well, there is a `wait()` method which returns a `Promise`... so Promises don't seem to really be an implementation detail. Also, I don't think the word `Barrier` conveys the right meaning to the functionality it provides.

But sure. All for the glory of less code. I had to move it down, so I just replaced `PromiseSource` with it in `vs/base/common/async`.
