### ISSUE TITLE
The new node 8 debug not work with jasmine-node cli

### ISSUE THREAD

**Issue by GregorBiswanger** [Microsoft/vscode#38795]
- VSCode Version: 1.18.1
- OS Version: Windows 10
- Node Version: 8.6.0

I can debug my jasmine-node specs and implementation with Node 7 and VS Code. On Node 8 the debugging break up with the following debug output:

> Debugging with inspector protocol because Node.js v8.6.0 was detected.
> node --inspect-brk=45352 node_modules\jasmine-node\lib\jasmine-node\cli.js . 
> Debugger listening on ws://127.0.0.1:45352/717c6150-abd0-4bab-a960-4f74829da5b8
> Debugger attached.
> Waiting for the debugger to disconnect...

Steps to Reproduce:

1. git clone https://github.com/GregorBiswanger/KataDictionaryReplacer.git
2. cd KataDictionaryReplacer && npm install
3. [ctrl] + [shift] + [b] (Start TypeScript)
4. Press F5 for Debug

The launch.json that works with Node 7 but not with Node 8:
```

{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}\\node_modules\\jasmine-node\\lib\\jasmine-node\\cli.js",
    "args": [
        "."
    ],
    "cwd": "${workspaceRoot}",
    "sourceMaps": true
}
```

More details about the sample: [http://www.cross-platform-blog.com/coding-dojo-katas/javascript-coding-dojo-dictionaryreplacer-kata/](http://www.cross-platform-blog.com/coding-dojo-katas/javascript-coding-dojo-dictionaryreplacer-kata/)

**Comment by roblourens** [comment]
With node 8, you're required to set `outFiles` to point at your generated js files, like this: `"outFiles": ["${workspaceRoot}/**"]`. For me, it works when I add that.

**Comment by GregorBiswanger** [comment]
Thanks!
