### ISSUE TITLE
File > Save and File > Save Workspace As share the same keyboard shortcut

### ISSUE THREAD

**Issue by paulmarshall** [Microsoft/vscode#38794]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
debugger-for-chrome|msj|3.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@paulmarshall if you update to 1.18.1, it should be fine.
