### ISSUE TITLE
Your Plugin Failed error dialog is blocking the interface of the application and there is no way to clear or suppress it other than hitting report.  Bad UX

### ISSUE THREAD

**Issue by light24bulbs** [Microsoft/vscode#38791]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
vscode-eslint|dba|1.4.3
gitlens|eam|6.1.1
vetur|oct|0.11.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by light24bulbs** [comment]
https://imgur.com/a/jWktF

**Comment by mjbvz** [comment]
This error means that all TypeScript and JavaScript language features are broken. You can press escape to cancel out if you really don't want to report the issue. 

To see what is causing the problem in the first place, please open the output panel and go to the `TypeScript` section. Are there any error messages in there?

**Comment by mjbvz** [comment]
Closing as not actionable without more information
