### ISSUE TITLE
Syntax highlighting broken for docker files named as Dockerfile.something

### ISSUE THREAD

**Issue by dskdas** [Microsoft/vscode#38797]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
vscode-docker|Pet|0.0.22
githistory|don|0.2.3
gitlens|eam|6.1.1
tslint|eg2|1.0.23
git-project-manager|fel|1.4.0
Go|luk|0.6.67
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
vscode-glide|vit|1.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Install Docker extension by Microsoft
2. Create a file called Dockerfile and edit it to notice that docker language support and syntax highlighting is present.
3. Rename the file to Dockerfile.xyz and notice that syntax language support is now missing. (This used to work till recently, not sure when it got broken)

Reproduces without extensions: Yes/No

**Comment by dskdas** [comment]
I used to be able to create a dockefile as Dockerfile.build and it was being detected as a Dockerfile. Since last release or somewhere in recent releases this doesnt seem to work anymore.

I noticed that if i switch the file name to build.Dockerfile that is OK.

Is this intentional?

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository. https://github.com/Microsoft/vscode-docker
