### ISSUE TITLE
Bogus settings warnings

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#38803]
- VSCode Version: Code - Insiders 1.19.0-insider (c8c6b13528c03986b8dad654cb1d3e796e8dbe97, 2017-11-20T05:13:59.281Z)
- OS Version: Windows_NT x64 10.0.17035
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.1.1
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.0.0
vscode-open-in-github|ziy|1.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a workspace that you used previously 
2. Go to the problem panel
-> All the commonly Used settings are reported as `Duplicate object key` problems on `vscode://defaultsettings/0/settings.json`

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Fixed already and is a dup.

**Comment by benlakey** [comment]
It may be helpful for people who find this issue in the future (like me) to have linked to the issue of which this was a duplicate.
