### ISSUE TITLE
Slow GPU Performance

### ISSUE THREAD

**Issue by esetnik** [Microsoft/vscode#38805]
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: 10.13.1 (17B48)

Steps to Reproduce:
1. Use Nvidia 1080TI eGPU on macOS 10.13.1 with 4k monitor
`/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron .`
```
GVA info: Successfully connected to the Intel plugin, offline Gen95
2017-11-20 13:10:55.445 Electron[5785:218950] *** WARNING: Textured window <AtomNSWindow: 0x7ff43648da10> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```
2. Open a large js file. File takes several seconds to appear on screen and scrolling is extremely laggy.
3. `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron . --disable-gpu`
4. Open large js file. File opens immediately, scrolling / interface is responsive. However visual flashing / glitches appear on screen during scrolling.

Reproduces without extensions: Yes

Also tested with [VDADecoderChecker](https://github.com/cylonbrain/VDADecoderCheck):
```
/Applications/VDADecoderChecker ; exit;
GVA info: Successfully connected to the Intel plugin, offline Gen95 
Hardware acceleration is fully supported
```

Also tested chrome `chrome://gpu` with `#ignore-gpu-blacklist` set to enabled
```
Graphics Feature Status
Canvas: Hardware accelerated
CheckerImaging: Disabled
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Hardware accelerated
Rasterization: Hardware accelerated
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

**Comment by bpasero** [comment]
@esetnik does it reproduce with `code --disable-gpu` ?

**Comment by esetnik** [comment]
No, as I mentioned in the initial description it does not reproduce with `--disable-gpu` but visual studio shows flashes and glitches with that flag enabled and I see a CPU spike.

**Comment by esetnik** [comment]
I tested against `1.19.0-insiders` (af232487ebcdc9758da537ea9a58977c373bc2be) and am no longer experiencing flashes / visual glitches with `--disable-gpu` and it makes my editor gpu performance much better. But if I use defaults in insiders I still get gpu performance issues. I've also tried `--ignore-gpu-blacklist` and `--force-gpu-rasterization`, but neither of them result in performance rivaling `--disable-gpu`.

**Comment by esetnik** [comment]
It may also be the same issue as https://github.com/Microsoft/vscode/issues/9432 since I have dual 4k monitors in scaled resolutions and am using Nvidia 1080 TI.

**Comment by schultyy** [comment]
I noticed something that might be related to this problem.

My system:

- Dell XPS 13 /w Core i7 and Name	Intel(R) Iris(TM) Plus Graphics 640 graphics card.
- Windows 10 Enterprise Version	10.0.16299 Build 16299
- Code 1.18.1

Scrolling a medium sized JavaScript file (~ 100 LoC) is very laggy when my computer runs on battery alone. When I open code with `code --disable-gpu .` it works fine. Also when I have my machine plugged in to a power source everything works smoothly again without `--disable-gpu`.

**Comment by esetnik** [comment]
Confirmed this is still not working in `1.19.0 stable (816be6780ca8bd0ab80314e11478c48c70d09383)`

**Comment by esetnik** [comment]
May be related to https://github.com/Microsoft/vscode/issues/25934 https://github.com/Microsoft/vscode/issues/38067

**Comment by hartshorne** [comment]
@esetnik I have an LG 5k display connected to a MacBook Pro with built-in graphics. My gpu-process would use 100% of CPU when scrolling around any file. In another thread, someone mentioned that removing and re-installing "Visual Studio Code.app" fixed this for them. It seems to have fixed the problem for me. Worth a shot?

**Comment by hartshorne** [comment]
@esetnik I think this may be a macOS bug:

- https://discussions.apple.com/thread/8122451
- https://forums.macrumors.com/threads/2017-mbp-15-radeon-gpu-does-not-work-after-resume-from-long-sleep.2076334
- https://www.reddit.com/r/MacOS/comments/71alv3/gpu_perfromance_in_high_sierra_drops_after/

I have a MacBook Pro with a Radeon Pro 460 connected to an LG 5k display. My gpu-process would use 100% of CPU while scrolling around a 250 line file. It would go away for a bit if I shut the computer off and then turned it back on, but it always came back.

I tried upgrading to macOS 10.3.3 beta, and that's solved the problem for me. Everything is snappy after about 30 minutes of use. gpu-process does not use more than 16% of CPU as I scroll around a document. Try joining here: https://beta.apple.com/sp/betaprogram/

Make sure you shut the computer right off and start it back up once you've installed the update. Seems like there is some kind of GPU driver issue causing the problem, and you'll want to make sure you get the fresh driver loaded before getting back into your work. Let me know if this works for you!

**Comment by hartshorne** [comment]
@esetnik I spoke too soon. I was able to reproduce the problem in the 10.3.3 beta as well. If I turn on a custom color profile for the display before launching vscode, I get terrible performance. If I quit vscode and switch back to the default profile, performance is fine. Do you have a custom color profile installed? If so, how did you create it?

**Comment by ardhitama** [comment]
@hartshorne Turning back to default color profile does fix it for me on OSX 10.3.1. Thanks for the tip, I’ve been struggling for so long.

**Comment by hartshorne** [comment]
@ardhitama I used DisplayCAL to produce the profile. The default "high quality" profile was pretty big, something like 700 KB, and was causing trouble with vscode (and Chrome). I generated a small "low quality" profile, and it seems to work fine.

**Comment by ardhitama** [comment]
@hartshorne Will try to do that, mine also 700+ KB ICC profile made by DisplayCAL. I hope electron can come up with a fix soon.

**Comment by vlasenko** [comment]
@bpasero Is it possible to pass command line argument `--ignore-gpu-blacklist` to Chromium that is used inside VS Code? Or is there any other way to access Chromium `chrome://flags` inside VS Code?

**Comment by bpasero** [comment]
I think so, from the command line.
