### ISSUE TITLE
mySql commands on visual code

### ISSUE THREAD

**Issue by Eliudnjai** [Microsoft/vscode#38801]
- VSCode Version:1.18
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1.The IDE highlights my variables of name and password as part of MySQL commands.
2.When i switch to Atom my code works fine,this happened
![screenshot from 2017-11-20 12-36-27](https://user-images.githubusercontent.com/20261031/33032547-89762ac0-cdef-11e7-9057-c8aea1d268b7.png)
 when the update released.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
I wasn't able to reproduce: I tried with this sample to reproduce:
```py
if (request.method=='POST' and form.validate()):
	password=sha256_crypt.encrypt(str(form.password.data))

	#execute
	cur.execute("INSERT INTO users(name,username,email.password)");
```
- please disable all extensions and see if that makes a difference
- please attach the sample that shows the example
- put the cursor on the blue words, and invoke the 'Developer: Inspect TM Scopes` command and send me a screenshot of the dialog.

**Comment by Eliudnjai** [comment]
I disabled the extensions and the problem was solved.
Thanks.
![screenshot from 2017-11-23 20-44-48](https://user-images.githubusercontent.com/20261031/33192255-2cdd3356-d08f-11e7-85a5-d4f6ad108a1d.png)

**Comment by Eliudnjai** [comment]
The problem is the python extension for vscode.
![screenshot from 2017-11-23 20-52-25](https://user-images.githubusercontent.com/20261031/33192391-4baca702-d090-11e7-87b9-ce986d9d56c6.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-python#284
