### ISSUE TITLE
Automatically publish manually 'released' Debian packages

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#38804]
When we manually release a build the Debian package should be released automatically.

**Comment by SecurityInsanity** [comment]
Is there anything third parties (such as myself) can do to help with this? The apt repo is out of date again, and every time it happens it's very annoying to see the update dot.

**Comment by Tyriar** [comment]
@SecurityInsanity no, and there's little I can do as we rely on another team. https://github.com/Microsoft/vscode/issues/45868 is tracking the issues with 1.21.1 publishing

This particular issue is also an internal one that would allow us to press a button to publish instead of running a script.

**Comment by chrmarti** [comment]
It is done for Insiders. We should also do it for stable releases to reduce the manual work involved.

**Comment by chrmarti** [comment]
Now also publishing stable and exploration builds.
