### ISSUE TITLE
VS Whitespace huddle together

### ISSUE THREAD

**Issue by jianjin** [Microsoft/vscode#38800]
I asked on stackoverflow, but no response: https://stackoverflow.com/questions/47276657/weird-whitespace-display

- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Type into multiple whitespaces
2. Then some whitespace will be displayed as huddled together.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
![img](https://i.stack.imgur.com/a0O8q.png)

**Comment by alexandrudima** [comment]
@jianjin I cannot reproduce with default settings + using `editor.renderWhitespace` to visualize spaces.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/5047891/33181785-c1e813e4-d071-11e7-8f21-9c38a280ee19.png">

Are you perhaps using some custom font family ? Does this reproduce when disabling all extensions ?

**Comment by jianjin** [comment]
ah, font thing. I used a PingFang SC font. Thanks
