### ISSUE TITLE
Emmet abbreviation: Text, doesn't expand text containing unclosed quotes (well)

### ISSUE THREAD

**Issue by ericnjuki** [Microsoft/vscode#38807]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Home

**Steps to Reproduce**:

1. Use emmet text abbreviation with any html tag in a html file. Text within braces must have odd number of apostrophes/quotes:
`p{this doesn't work, for me}`

2. Attempt to expand abbreviation: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.1. Try uh, deriving context menu? (Ctrl+Space)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.2. Running Emmet: Expand Abbreviation
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.3. Adding `"emmet.triggerExpansionOnTab": true` and hitting tab

3. Use with concatenation (odd number of quotes in at least one of the braces):
`p{this doesn't work, for me}+div{'this' doesn't work too}`
and repeat step 2

Reproduces without extensions: Yes

**Expected results**
for steps
2: `<p>this doesn't work, for me</p>`
3: `<p>this doesn't work, for me</p><div>'this' doesn't work too</div>`

**Actual results**
for steps:
2.1: Expand abbreviation doesn't appear
2.2: Error Failed to expand abbreviation
2.3: Error Failed to expand abbreviation
(errors...)

3: `<p>this doesn't work, for me}+div{'this' doesn't work too</p>`
(weird expansions)

**Comment by ramya-rao-a** [comment]
The upstream issue https://github.com/emmetio/abbreviation/issues/8 was fixed
The changes have been absorbed to the emmet extension via https://github.com/Microsoft/vscode/commit/41e7dbc0df0d5be8dee67b2d1a0f66152a15b170
