### ISSUE TITLE
CMD terminal output line is cut at point where it wraps panel width. problem matcher only gets truncated string.

### ISSUE THREAD

**Issue by pr-yemibedu** [Microsoft/vscode#38806]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro 1709
- CMD terminal output line is cut at point where it wraps panel width. problem matcher only gets truncated string.

Hello, (Stable 1.18.1) When I have my terminal (cmd) width short enough to wrap, the problems window cuts the text at the wrapping point of the text given. I did not already see an issue it. I was wondering if someone else noticed this too?

Steps to Reproduce:

1. Have CMD as your default terminal
2. Make sure the window width is small enough where terminal text of a message would wrap to at least two lines for the message.
2. Run a task that will output to the terminal and has a problem matcher.
3. Look at the cut off messages in the problem matcher with a sigh.

Reproduces without extensions: Yes

Screen shot small width:
![image](https://user-images.githubusercontent.com/22304841/33034892-4e80d016-cdf7-11e7-883a-e592ebf8d2a1.png)

Screen shot large width:
![image](https://user-images.githubusercontent.com/22304841/33034939-6827526a-cdf7-11e7-8d0c-89cf2175a066.png)

You can see with the larger width, more is available.

**Comment by Tyriar** [comment]
@dbaeumer shouldn't this be fixed in v1.18.1? https://github.com/Microsoft/vscode/issues/32042

**Comment by dbaeumer** [comment]
@Tyriar yes, this should be addressed. 

@pr-yemibedu can you provide a GitHub project I can clone that demos the behavior with steps to reproduce. This got fixed and verified: https://github.com/Microsoft/vscode/issues/32042

**Comment by pr-yemibedu** [comment]
Hello,
 @dbaeumer I will try to get one done this afternoon (EST) with a minimal project. Thank you. Good day.
