### ISSUE TITLE
Please allow html and js hinting and formatting in PHP extensions like brackets and sublim. 

### ISSUE THREAD

**Issue by jhashailesh3108** [Microsoft/vscode#38802]
I am a PHP developer and I often encountered with the problem when I use HTML and JS in .PHP files. There is no hinting, formatting and closing tags highlighter. It irritates me every time when I use VS code. Otherwise, it is awesome.
Thank you
Shailesh Kumar Jha

**Comment by bmewburn** [comment]
The extension below will do that. Combined formatting is currently not supported. 
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by jhashailesh3108** [comment]
Thanks brother, It is working smooth for me. Thank a alot.
