### ISSUE TITLE
vs code crash

### ISSUE THREAD

**Issue by tidjean** [Microsoft/vscode#38812]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-16-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
docker-explorer|for|0.1.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
