### ISSUE TITLE
onDidChangeActiveTextEditor fires twice

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [Microsoft/vscode#38818]
- VSCode Version: 1.18.1
- OS Version: Linux Mint 18.2

Steps to Reproduce:

1. Make HelloWorld project as in tutorial
2. In the end of activate function add code like this
```
vscode.window.onDidChangeActiveTextEditor(function (editor) {
        console.log("onDidChangeActiveTextEditor" + editor.document.fileName);
    })
}
```
3. Run Debug session, open two ordinal files, activate extension via run command, change active editor from file 1 to file 2, and then back from file 2 to file 1.

As result in debug console there are messages like this
```
Congratulations, your extension "vsct" is now active!
onDidChangeActiveTextEditor /home/john_16/Projects/file2.py
onDidChangeActiveTextEditor /home/john_16/Projects/file2.py
onDidChangeActiveTextEditor /home/john_16/Projects/file1.py
onDidChangeActiveTextEditor /home/john_16/Projects/file1.py
```
I am expected that log messages must be only 2, instead i see 4. Its mean that if i use in this event a real function that it will execute twice - that is not what i expect.

Is it a bug or i doing something wrong?

Reproduces without extensions: no info

**Comment by jrieken** [comment]
Proper bug report. Thanks @EvgeniyMakhmudov.
