### ISSUE TITLE
command "Select all currencies of Find Match" is broken in 1.18.1

### ISSUE THREAD

**Issue by pistolilla** [Microsoft/vscode#38819]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
sort-lines|Tyr|1.3.0
replacerules|bhu|0.1.1
rest-client|hum|0.16.1

---

Steps to Reproduce:

1. Open any file
2. Go to Edit > Find
3. Search for any expression
4. Once you find highlighted matches
5. Try "Select all currencies of Find Match"
6. It will overwrite your search and will not find the matches you saw highlighted before
7. Also search history will be lost.

Reproduces without extensions: Yes/No

**Comment by pistolilla** [comment]
This error only happens when command "Select all currencies of Find Match" is triggered from the Commands shortcut (Cmd+Shft+P)

**Comment by roblourens** [comment]
You may want `editor.action.selectAllMatches` (alt+enter) instead, but I'm not sure what problem you're seeing. Can you share a screenshot or gif?

**Comment by pistolilla** [comment]
Attaching animated gif. Thanks!
![in](https://user-images.githubusercontent.com/31317105/33044145-91a31e94-cdfc-11e7-9913-799f39c9438a.gif)

**Comment by rebornix** [comment]
The command is not working with regex options, a good catch!

**Comment by pistolilla** [comment]
however "alt+enter" bypasses the error. Thanks for the quickest follow up ever!

**Comment by roblourens** [comment]
@rebornix I think there are two different commands, so that might be basically by design, but the current situation is confusing. See https://github.com/Microsoft/vscode/issues/20453 also.

**Comment by pistolilla** [comment]
I'm sure it's a regression because, I had been using that command on regular basis (with regex) .. and it simply stopped working after updated to version 1.18.1

Also note that the search history is lost, by no reason.

**Comment by pistolilla** [comment]
Just checked with version 1.17.2 and it works perfectly there.

**Comment by rebornix** [comment]
@pistolilla thanks for the verification.

@roblourens thanks for the pointer. For non-regex search, there is no such confusion so I'd like to see this one as a regression. #20453 is more or less a UI thing.
