### ISSUE TITLE
App added in the windows system path after VScode are not accessible in the terminal

### ISSUE THREAD

**Issue by bakarydiarra** [Microsoft/vscode#38810]
- VSCode Version: 1.18.1
- OS Version: Windows 7

Steps to Reproduce:

1. Add application like grade in the system path after the vscode bin entry.
2. Start vscode and open a terminal
3. Try to execute the application in the terminal

After investigating the root of cause of the issue, I moved the gradle entry before the vscode one in the system path and it started working.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You probably had another VS Code window open as when first launched VS Code will inherit the system's environment. Restarting and reopening should fix the issue on Windows.

**Comment by bakarydiarra** [comment]
@Tyriar  No, I had not. I had just restarted my computer.

**Comment by Tyriar** [comment]
@bakarydiarra could you run `echo %PATH%` within the terminal and see what the PATH value is? Then open devtools (Help > Toggle Developer Tools) and run `process.env.PATH` in the console and inspect that value? This will help diagnose at what level the problem is starting.

**Comment by bakarydiarra** [comment]
I have re-tested using the version 1.19.1 of vscode and was not able to reproduce the issue.
Thank you
