### ISSUE TITLE
No nodejs intellisense after latest upgrade 0.10.10 

### ISSUE THREAD

**Issue by tacho87** [Microsoft/vscode#3881]
No nodejs intellisense after latest upgrade 0.10.10  on mac. Also, tab is behaving wrongly. (All extensions removed)

**Comment by egamma** [comment]
This looks like a duplicate of Microsoft/TypeScript#7292. Pls see https://github.com/Microsoft/vscode/issues/3791#issuecomment-193690551 for a work around.


Regarding
> Also, tab is behaving wrongly.

pls file a separate issue with steps for how to reproduce the wrong behaviour.
