### ISSUE TITLE
Terminal slow zoom even when it is not visible

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38811]
**Steps to Reproduce:**

1. Open vs code
2. Open terminal
3. Switch to a different panel, such as `output`
4. Zoom in using `cmd` `+`

**Issue**
The terminal takes ~200ms to rebuild the character atlas, even though it is not currently visible:

![screen shot 2017-11-20 at 10 50 54 am](https://user-images.githubusercontent.com/12821956/33035650-c3f29c7e-cde0-11e7-956b-62783af8ad4b.png)

Also happens if the output panel has been hidden

**Comment by Tyriar** [comment]
A workaround for this may be to use this experimental setting:

```
"terminal.integrated.experimentalTextureCachingStrategy": "dynamic"
```

**Comment by Tyriar** [comment]
dynamic is now the default, I think this is fixed now.
