### ISSUE TITLE
Ctrl+Q should confirm

### ISSUE THREAD

**Issue by dbandstra** [Microsoft/vscode#38823]
Ctrl+Q (one key away from Ctrl+W) quits the application, including multiple open windows, without confirming. This is my nemesis in a number of applications, not just VS Code. I think a confirmation prompt should be added, at least if there are multiple windows open.

- VSCode Version: 1.18.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Press Ctrl+Q
2. Lose a bunch of windows

Reproduces without extensions: Yes

**Comment by LeThiHyVong** [comment]
I think if Ctrl+Q trigger the SIGKILL or SIGSTOP then there is no way to catch it in application. 
(http://tille.garrels.be/training/bash/ch12.html)

Signal name | Signal value | Effect
-- | -- | --
SIGHUP | 1 | Hangup
SIGINT | 2 | Interrupt from keyboard
SIGKILL | 9 | Kill signal
SIGTERM | 15 | Termination signal
SIGSTOP | 17,19,23 | Stop the process

SIGKILL and SIGSTOP
--
SIGKILL and SIGSTOP can not be caught, blocked or ignored.

Maybe you can try switching the shortcut?

**Comment by dbandstra** [comment]
Duplicate of what other issue?
