### ISSUE TITLE
"editor.tokenColorCustomizations" for types doesn't work in .c files.

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#38822]
- VSCode Version: 1.18.1
- OS Version: Windows 10 (Build 1709)
- Reproduces without extensions: Yes

Steps to Reproduce:

1. Create 'file.c'
2. Create any function
3. Setting a custom color for the "types" value in the  "editor.tokenColorCustomizations" setting, will not overwrite the type color for .c files.

This behavior is very strange, as the other variables: "comments", "functions", "keywords", "numbers", "strings" and "variables", all work for .c files.

I'm thinking that .c files are probably not the only ones where some of the colors won't be applied.

**Comment by aeschli** [comment]
Now 'types' includes all rules we use for types in the default themes.
But note that each language has their own way of giving scopes to syntax elements. If more is needed, you can directly write textMateRules as described here: https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme

**Comment by mjbvz** [comment]
Verified. Types in c use `storage.type` which is controlled by the `keywords` setting:

![screen shot 2017-12-05 at 5 04 54 pm](https://user-images.githubusercontent.com/12821956/33639070-768bad04-d9de-11e7-98fe-68832e8024fd.png)
