### ISSUE TITLE
Ctrl+Delete removing entire line when used at the end of line

### ISSUE THREAD

**Issue by twlamb** [Microsoft/vscode#3882]
If you have some lines in a file such as:
```c#
public void Add( int x,
                          int y )
{
    // some code
}
```

If you place your cursor at the end of the first line, and hit `Ctrl+Delete` it removes the entire line, so you end up with just
```c#

                          int y )
{
    // some code
}
```

I would expect it to remove all the space between the current position and the next word:

```c#
public void Add( int x, int y )
{
    // some code
}
```

This is on Windows 7 if that's relevant or not.

**Comment by SmilyOrg** [comment]
I think it's a regression in the latest update (0.10.10?). Pretty annoying :)

**Comment by bpasero** [comment]
@alexandrudima I end up with this after the first Ctrl+Delete:

```
public void Add( int x,                          int y )
{
    // some code
}
```

Please reopen if your fix wanted to get me to this as suggested by the issuer:
```
public void Add( int x, int y )
{
    // some code
}
```

**Comment by alexandrudima** [comment]
I like the suggestion, saves an extra `Ctrl+Delete`.

My change was to fix the blatantly wrong behavior of `Ctrl+Delete` that would delete the current line.

**Comment by bpasero** [comment]
:+1:
