### ISSUE TITLE
Tasks keeps running forever

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#38824]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.8.4
cpptools|ms-|0.14.2
Ruby|reb|0.15.0

---

Steps to Reproduce:

1. Create a dummy foreground shell task (echo test)
2. Run the task
3. Try to run again

Reproduces without extensions: Yes

When I run the task, vscode thinks it is still running even after it has successfully finished. In order to be able to start it again, I have to manually terminate it. This issue only affects the Mac version, on Linux the behavior is as expected, the task ends and the terminal can be reused by another task.

**Comment by dbaeumer** [comment]
Sounds like a dub of #37846. 

@g-arjones is this a Beta version of the Mac OS?

**Comment by g-arjones** [comment]
> Sounds like a dub of #37846.

Yes, sounds like it. 

> is this a Beta version of the Mac OS?

Not Beta, MacOS 10.13. 

The only information I have that is not in the other issue is that it works just fine on Linux.

**Comment by dbaeumer** [comment]
Do you have a reproducible test case. Best is a GitHub repository to clone ?

**Comment by g-arjones** [comment]
That would be an empty folder with a tasks.json with some shell command/process in it. I can create a repo for you guys to clone it, does it help?

**Comment by dbaeumer** [comment]
That would be perfect.

**Comment by g-arjones** [comment]
No problem, here you go: https://github.com/g-arjones/vscode-task-test

I was wondering, is there a way to run the tasks in an external terminal instead? If this is a issue with the integrated terminal rather than with the tasks service maybe I could use that as workaround in the meantime..

**Comment by dbaeumer** [comment]
@g-arjones no. The reason why we run it in the internal terminal is to capture the output and scan for problems.

**Comment by g-arjones** [comment]
Fine, thanks!

**Comment by dbaeumer** [comment]
I mark this as a dup of #37846 since the tast case looks very very similar.

**Comment by dbaeumer** [comment]
@g-arjones please see https://github.com/Microsoft/vscode/issues/37846#issuecomment-345787978

Can you give 10.13.1 a try.

**Comment by g-arjones** [comment]
This is weird.. I just updated to 10.13.2 (beta) today and the issue persists. Can't downgrade to 10.13.1, sorry. I guess we have to wait until the next stable but I think it is unlikely that it won't be there
