### ISSUE TITLE
Font gets totally corrupted in integrated terminal

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#38826]
- VSCode Version: Version 1.18.1 (1.18.1)
- OS Version: MacOS

Steps to Reproduce:

1. Not sure
2. Not sure

Reproduces without extensions: Not sure

This only happens after about an hour of use with the IDE, pretty bizarre. I have used other IDEs and never seen anything like that.

See these screenshots:

![screenshot 2017-11-20 17 09 11](https://user-images.githubusercontent.com/11139560/33049613-d1289c1a-ce15-11e7-99dd-a55103e02ef8.png)

![screenshot 2017-11-20 13 46 43](https://user-images.githubusercontent.com/11139560/33049622-db93da70-ce15-11e7-8e08-51a181d9d76c.png)

**Comment by z333d** [comment]
I have the same problem.

- VSCode Version: Version 1.18.1 (1.18.1)
- OS Version: MacOS

**Comment by rafasoares** [comment]
I've had that happen to me on macOS High Sierra, usually when I change from an external (larger) monitor to the built-in display (smaller), for instance, when I unplug the external monitor.

Using zsh, oh-my-zsh, powerlevel9k theme and Adobe Source Code Pro font (patched for powerline). Only the prompt is messed up, though. The commands I type show correctly.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
