### ISSUE TITLE
Use yarn workspaces for built-in extensions?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#38825]
**Problem**
#30602 Many of our built-in extensions have duplicate dependencies: `vscode-nls`, `application-insights`, ...

**Proposal**
[Yarn workspaces](https://yarnpkg.com/en/docs/workspaces) are one way we could de-dup some of these. For example, changing `extensions/package.json` to:

```json
{
  "private": true,
  "name": "vscode-extensions",
  "version": "0.0.1",
  "description": "Dependencies shared by all extensions",
  "dependencies": {
    "typescript": "2.6.2-insiders.20171120"
  },
  "scripts": {
    "postinstall": "node ./postinstall"
  },
  "workspaces": [
    "css",
    "html",
    "markdown",
    "php",
    "typescript"
  ]
}
```

results in all of the listed extensions sharing the same `applicationinsights` and `vscode-nls` instance

**Blockers**
TypeScript does not know about workspaces, so it will start suggesting auto imports for all shared `node_modules` exports in every extension

**Comment by joaomoreno** [comment]
That is AMAZING. Let's do it!

**Comment by mjbvz** [comment]
@mhegazy Any thoughts on intellisense in this scenario? The new project layout would be something like:

```
package.json
node_modules/
     share-lib/
     ts-specific-lib/
markdown-extension/
     package.json
     tsconfig.json
     index.ts
typescript-extension/
     package.json
     tsconfig.json
     index.ts
```

We want intellisense in `typescript/index.ts` to see both `shared-lib` and `ts-specific-lib`, but in `markdown-extension/index.ts` we only want access to `shared-lib`. Currently, both extensions would have access to both libraries
 
I believe some similar issues have been brought up in https://github.com/Microsoft/TypeScript/issues/3469

**Comment by mhegazy** [comment]
//cc @RyanCavanaugh

**Comment by joaomoreno** [comment]
This doesn't behave as I expected it to.

It installs each workspace as a dependency in `node_modules`. I added all extensions as workspaces, but they just ended up being installed in `node_modules`:

- `node_modules/git`
- `node_modules/html`
- etc...

**Comment by joaomoreno** [comment]
Marking out of scope. The endgame for built-in extensions is to move the out of the repo.
