### ISSUE TITLE
Green squiggles are missing for Information diagnostics on the Insiders build

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#38829]
- VSCode Version: 1.19.0-insider
- OS Version: Windows.

Steps to Reproduce:

1. I'm using the C++ extension which reports Information diagnostics for missing headers. I think this issue would repro for any Diagnostic with a Information severity. Red squiggles with the Error severity still work.

Bug: No green squiggles appear. It works with 1.18.0. Our extension wants squiggles to appear for our Information diagnostics.

Reproduces without extensions: Yes -- I'm using the C++ extension to repro, but this isn't a bug with that extension.

**Comment by aeschli** [comment]
Good catch, thanks!
