### ISSUE TITLE
Why are settings and keybindings not in the same directory as extensions?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3883]
On Linux extensions are stored at: `~/.vscode[-<quality>]/extensions`

But settings and keybindings are stored at: `~/.config/Code[ - <quality>]/User`

Why is all user config not in `~/.vscode` (or the other way)?

**Comment by bpasero** [comment]
Historic reasons, we should move them out.

**Comment by bpasero** [comment]
Lets continue this in #3884
