### ISSUE TITLE
テキストが表示されない

### ISSUE THREAD

**Issue by kyamamoto03** [Microsoft/vscode#38830]
マルチディスプレイで起動した時は正常にテキストが表示されるが、シングルディスプレイで起動するとテキストが表示されない。
メニュー表示される。
テキストが表示されるエリアにマウスを持っていくとポインターが変化するので、
表示の問題だと思われます。

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1
vscode-docker|Pet|0.0.22
markdown-all-in-one|yzh|0.11.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Sorry, it's hard to understand your problem. Please file the issue in English, and remember: a picture is worth one thousand words!
