### ISSUE TITLE
Mouse wheel to scroll left and right, you can not control the horizontal scroll bar

### ISSUE THREAD

**Issue by JiGuangYuan** [Microsoft/vscode#38831]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
intellij-idea-keybindings|k--|0.2.16
cpptools|ms-|0.14.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Mouse wheel to scroll left and right, you can not control the horizontal scroll bar

Reproduces without extensions: Yes/No

**Comment by WillyMoselhy** [comment]
I have a mouse that supports horizontal scrolling and it does not work in VS Code, is this resolved?

**Comment by JiGuangYuan** [comment]
Yes, I found that there is still this problem, but I have just tried to come up with the solution, must be vscode to minimize and then restore he can work, can you solve it?

vscode 1.91.1 X64
windows 10



------------------ 原始邮件 ------------------
发件人: "WillyMoselhy";<notifications@github.com>;
发送时间: 2017年12月26日(星期二) 下午3:29
收件人: "Microsoft/vscode"<vscode@noreply.github.com>;
抄送: "Mirage·’"<jiguang-yuan@foxmail.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Microsoft/vscode] Mouse wheel to scroll left and right, you cannot control the horizontal scroll bar (#38831)




I have a mouse that supports horizontal scrolling and it does not work in VS Code, is this resolved?

**Comment by JiGuangYuan** [comment]
Yes, I found that there is still this problem, but I have just tried to come up with the solution, must be vscode to minimize and then restore he can work, can you solve it?

vscode 1.91.1 X64
windows 10

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13612
