### ISSUE TITLE
Pin VScode on Windows10  desktop deck will open old code when git conflict

### ISSUE THREAD

**Issue by EasonWang01** [Microsoft/vscode#38839]
- VSCode Version:lastest
- OS Version:windows 10

Steps to Reproduce:
1.Pin Vscode on windows desktop deck
2.pull code from remote then resolve some git conflict and merge
3.reboot computer
4.click the pined vscode on desktop deck
5.which will then open up some old vscode windows
6.open the project then add & commit & push 
7.the new commit log will show that step6 push overwrite the step2 code merge with old code.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
This sounds like a windows issue and nothing we can fix.
