### ISSUE TITLE
Wrong syntax highlight for pseudo class in SCSS file.

### ISSUE THREAD

**Issue by vinnlee** [Microsoft/vscode#38838]
Don't know this actually is a issue or not 🤔 but I see some pseudo class in my SCSS file is wrong highlight.

![image](https://user-images.githubusercontent.com/20036316/33055039-b5f42668-ceaf-11e7-9d8f-bec7b3091a1e.png)

**Comment by pawelogrodnik** [comment]
I have the same issue after one of latest updates - any solution to this?

**Comment by aeschli** [comment]
It's fixed in insiders (1.19)
