### ISSUE TITLE
Add Mouse Clicks to Configurable 'Keyboard' Shortcuts

### ISSUE THREAD

**Issue by ccroy** [microsoft/vscode#38849]
- VSCode Version: 1.18.1
- OS Version: Windows 10

It would be nice to have mouse clicks (left & right) as configurable keybindings under the keyboard shortcuts settings. I really like Ctrl + LeftClick for go-to-definition and would like to be able to map Ctrl + RightClick to the go-back command (which is default mapped to Alt + LeftArrow).

Having configurable mouse bindings may also cover some of the other issues/requests made by users (#38588 for instance).

**Comment by KamasamaK** [comment]
Related to #3130

**Comment by Saigut** [comment]
Is there any progress?

**Comment by Gibyeng** [comment]
It is a good suggestion, I also want this feature :)

**Comment by ectoanonymous** [comment]
I thought they have this feature, so googled it 'how to set it' after not finding in the app. I was pretty much shocked after seeing this thread that VS code doesn't support mouse key bindings.
I've a mouse which have many keys, I wanted to configure those keys according to my taste. 
This feature was available in PyCharm, A lil bit disappeared but I think it would be possible in future updates 👍

**Comment by jonathanhart** [comment]
Come on wonderful VS Code devs, this would speed us up so much, please add it!

**Comment by Divide-By-0** [comment]
Bump @bpasero, is there any way to have priority on this increased?

**Comment by mrpcampos** [comment]
Are there any updates?

its very disappointing that this is being ignored for so long.

**Comment by jdagnin** [comment]
Does VS Code not support mouse key mapping ?
Even notepad++ has keybindings for mouse keys - very convenient to mouse4 / mouse5 switch between previous / next open file.

**Comment by Alveona** [comment]
+1 would be useful to remap go-to-definition to go-to-implementation

**Comment by aqumus** [comment]
I would like to bind Logitech Mx mouse keys for `navigateForward` & `navigateBack` to quickly switch cursor position, not sure if there's any plugin for mapping mouse buttons
