### ISSUE TITLE
cannot open workspace in a normal way

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#38846]
New update screwed up the workspace opener.

You can attach workspace by drag and drop, but i was not able to open workspace from the menu, when an existing workspace already opened. (so i would have liked to replace it)

When you click on open of the folder chooser, it's just going back to a folder. (you cannot choose a folder!!!)

Ubuntun 16.4.3

**Comment by bpasero** [comment]
@fssrepository can you maybe record a video what you are doing and trying to achieve?
