### ISSUE TITLE
Visual Studio Code Version does not match commit id

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/vscode#3885]
Reproducing this on Mac Visual studio code. 
VS code shows the version as 0.10.10
expected 0.10.11
![vscodeversionerror](https://cloud.githubusercontent.com/assets/80310/13616462/ebddb5f8-e52e-11e5-8cef-62f0c55d813e.jpg)

**Comment by rkavalap** [comment]
<img width="288" alt="vscodeversionmismatch" src="https://cloud.githubusercontent.com/assets/80310/13616600/78097846-e52f-11e5-8790-e621cd85bf3d.png">

**Comment by bgse** [comment]
![vscode_version](https://cloud.githubusercontent.com/assets/8385202/13631124/4d13795c-e5e3-11e5-80b2-538425910098.png)

Windows 8.1

**Comment by joaomoreno** [comment]
We incorrectly called it `0.10.11` initially. The right version is `0.10.10`, which matches 5b5f4db.
