### ISSUE TITLE
Specific color for specific folder base on folder name

### ISSUE THREAD

**Issue by Cloze** [Microsoft/vscode#38857]
it would be so good if we able to change a color ( icon either ) of a specific folder base on the folder name. ( I think it can be a extension too )
something like : 

![foldercolor](https://user-images.githubusercontent.com/1060150/33064483-111a5a3e-cebb-11e7-91cd-7f52609e214c.jpg)

because when we have too much folders and file we easily get lost in those folders and we should put some times to find what we want. of course you might say there is a search but sometimes you cannot remember the name of the file or folder and you scroll through the explorer to find it.

**Comment by dehghani-mehdi** [comment]
Color is good enough, but I like to see custom icon option too.

**Comment by Cloze** [comment]
is it possible to make this as an extension ?
I mean it there any API to manage the coloring boxes ?

**Comment by isidorn** [comment]
@Cloze currently it is not possible to do this using the extension API

**Comment by Cloze** [comment]
@isidorn how about just adding the text? I mean having like 10 colors and naming them like "Black" "White" "Green etc.  and not using those color boxes.

**Comment by Cloze** [comment]
@isidorn  hah ?

**Comment by JensPliester** [comment]
Would be happy to see that feature, too. This would greatly help keeping overview in explorer tree

**Comment by idlethumbs** [comment]
+1

**Comment by malutanpetronel** [comment]
+1

**Comment by jimmybrawn** [comment]
+1

**Comment by arkanmgerges** [comment]
+1

**Comment by kiplip** [comment]
need that for sure.

**Comment by lepinekong** [comment]
This is really scandalous that this issue has been closed 👎

**Comment by chihangc** [comment]
Using workspace with multiple root folder. I would like to have a different color for different root folder and show that color on the tab which allows me to distinguish which project the file from

**Comment by Cloze** [comment]
Looks like its possible ...

![color](https://user-images.githubusercontent.com/1060150/46739137-b8b34e00-ccac-11e8-8c21-57f6ce938871.jpg)

**Comment by jacobus** [comment]
> Looks like its possible ...
> 
> ![color](https://user-images.githubusercontent.com/1060150/46739137-b8b34e00-ccac-11e8-8c21-57f6ce938871.jpg)

How did you manage to do that?

**Comment by Cloze** [comment]
> > Looks like its possible ...
> > ![color](https://user-images.githubusercontent.com/1060150/46739137-b8b34e00-ccac-11e8-8c21-57f6ce938871.jpg)
> 
> How did you manage to do that?

Thats the git extension.

**Comment by jacobus** [comment]
Thanks!

**Comment by joshua-fogg** [comment]
pwees kthnx

**Comment by Aarbel** [comment]
@Cloze which "git" extension ?

Have you found an alternative / solution ?

**Comment by Cloze** [comment]
@Aarbel THE original git extension for VSCODE.

nah, no alternative solution for this.

**Comment by Aarbel** [comment]
How do you change folders colors with it ?

**Comment by techsin** [comment]
https://github.com/microsoft/vscode/issues/62104

**Comment by hosseinse1919** [comment]
add css to "C:\Users\???\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css"

can change color of folders like this ... **but you may need to Reinstall VSCode**  cuz after that it will show you `error `

.monaco-list-rows > [aria-setsize="17"][aria-expanded] .monaco-icon-label-container  {
    letter-spacing :1px;
    text-transform:uppercase;
    padding-left:24px;
    color: #ffcc00;
  }

**Comment by JosePereiraUA** [comment]
Maybe it's time to re-visit this idea? I would be extremely useful!

**Comment by R1D3** [comment]
IT WOULD BE REALLY REALLY USEFUL !!! WE NEEDED THIS !!!

**Comment by Refzlund** [comment]
I suggest this approach
**Git**
- "git.coloredLabels": false     ; False:  Git won't colorize the text (just show the icons M, U etc.

**Explorer**
- "workbench.folderLabelColor": "#555555"    ; Changes the colors of texts for folders

**Comment by Sa1Sa** [comment]
would be super helpful. can be done in PyCharm using 'scopes'... sadly still lacking in VScode

**Comment by milosFromSerbia** [comment]
any info im migrating from PhpStorm and this will be useful to keep things organized

**Comment by db-developer** [comment]
Microsoft: Sunsetting Atom (June 2022)
Me: Switching to vscode
Microsoft: ... but we cannot colorize project folders ...

Oh come on! Maybe copy the code from Atom? (not really, but it feels like...)

**Comment by yuklia** [comment]
+1

**Comment by jacob-j** [comment]
Using FileDecorator API, I created this extension. It has its limitations (source control overrides color etc), but at least it does some sort of separation. I created it just now, so there might be some issues, feel free to report if you find any. I will be using and testing it vigorously in our monorepo.

https://marketplace.visualstudio.com/items?itemName=VisbyDev.folder-path-color

<img width="1019" alt="CleanShot 2023-06-05 at 07 43 26@2x" src="https://github.com/microsoft/vscode/assets/5649576/2aa9ba17-c25e-40b0-b478-4da80d6a3b93">

**Comment by N30** [comment]
> Using FileDecorator API, I created this extension. It has its limitations (source control overrides color etc), but at least it does some sort of separation. I created it just now, so there might be some issues, feel free to report if you find any. I will be using and testing it vigorously in our monorepo.
> 
> https://marketplace.visualstudio.com/items?itemName=VisbyDev.folder-path-color
> 
> <img alt="CleanShot 2023-06-05 at 07 43 26@2x" width="1019" src="https://user-images.githubusercontent.com/5649576/243261401-2aa9ba17-c25e-40b0-b478-4da80d6a3b93.png">

It would be awesome only if it worked, just spent an hour and won't work for me.

**Comment by jacob-j** [comment]
> > Using FileDecorator API, I created this extension. It has its limitations (source control overrides color etc), but at least it does some sort of separation. I created it just now, so there might be some issues, feel free to report if you find any. I will be using and testing it vigorously in our monorepo.
> > https://marketplace.visualstudio.com/items?itemName=VisbyDev.folder-path-color
> > <img alt="CleanShot 2023-06-05 at 07 43 26@2x" width="1019" src="https://user-images.githubusercontent.com/5649576/243261401-2aa9ba17-c25e-40b0-b478-4da80d6a3b93.png">
> 
> It would be awesome only if it worked, just spent an hour and won't work for me.

The issue was related to Windows, I only tested on Mac and Linux.
If you upgrade to 0.0.12 it should now work for Windows machines as well
