### ISSUE TITLE
My extentions keep on uninstalling themselves. Everytime i go back on there are uninstalled, please fix this. Thank you

### ISSUE THREAD

**Issue by Mornedeklerk** [Microsoft/vscode#38850]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:41.632Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@Mornedeklerk Can you please provide more information for understanding and reproducing the issue? What extensions are uninstalling and how did you get into this state?
