### ISSUE TITLE
Settings : File seems to be binary and cannot be opened as text

### ISSUE THREAD

**Issue by saketthakare** [Microsoft/vscode#38869]
When I try to open my Settings from File->Preferences I get a prompt 

> Error File seems to be binary and cannot be opened as text

 Same message even if I disable all the plugins.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.23
prettier-vscode|esb|0.24.0
docthis|joe|0.6.0
angular-essentials|joh|0.3.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0

---

Steps to Reproduce:

1. Ctrl+ Comma
2. ![issue-vscode](https://user-images.githubusercontent.com/6807080/33071221-b083cf22-cee0-11e7-9089-9766b1c3783b.png)

Reproduces without extensions: Yes

**Comment by saketthakare** [comment]
On VS code startup

> Error : Unable to open 'User Settings': File seems to be binary and cannot be opened as text.

![issue](https://user-images.githubusercontent.com/6807080/33109250-823a0e8e-cf66-11e7-8624-0249d374ed9e.png)

**Comment by bpasero** [comment]
This can only happen when the settings file turned into binary garbage.

**Comment by saketthakare** [comment]
Correct the settings.json was turned into Binary garbage.
[settings.zip](https://github.com/Microsoft/vscode/files/1494839/settings.zip)

**Comment by sandy081** [comment]
@bpasero I think we are showing proper message here to assist users what was wrong.

**Comment by bpasero** [comment]
@sandy081 yeah that is for sure but I thought it would be interesting how @saketthakare got into this state in the first place (e.g. by us writing into the config)?

**Comment by saketthakare** [comment]
Works after deleting the file `settings.json` from 

> %APPDATA%\Roaming\Code\User

**Comment by saketthakare** [comment]
@bpasero Exactly. How did the file turned into binary garbage?

**Comment by sandy081** [comment]
@bpasero I am doubtful if writing into the config would have caused it. It uses the same path as how a normal file is modified and saved. 

Any Extensions?

@saketthakare Any idea, if you have performed any actions before getting into this state?

**Comment by saketthakare** [comment]
I overwrote the settings and installed these Extensions

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.23
prettier-vscode|esb|0.24.0
docthis|joe|0.6.0
angular-essentials|joh|0.3.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0

I am not sure about the sequence though.
