### ISSUE TITLE
Ctrl+D / Cmd+D cause wholeWords:true kept unexpectly.

### ISSUE THREAD

**Issue by 100pah** [Microsoft/vscode#38862]
- VSCode Version: 1.18
- OS Version: macOS 10.12.6

This new feature has been introduced in `1.18`:
> Ctrl+D / Cmd+D improvements
> Due to popular demand, the Add Selection to Next Find Match (⌘F1) action has been modified to behave differently when you start adding multiple cursors with no selected text. In this case, the action will temporarily ignore the Find widget search options and will always search for whole words and case sensitive matches.

But this behavior brings some trouble to me, which is probably a bug I guess:

Steps to Reproduce:
1. At the begining, the `find` state is `wholeWords: false` and `caseSensitive: false`.
2. Use keyboard shortcut to `editor.action.moveSelectionToPreviousFindMatch` or `editor.action.moveSelectionToNextFindMatch` (which I have customized to `alt+up` and `alt+down`) , then some text will be selected with `wholeWords: true` and `caseSensitive: true`.
3. Use keyboard shortcut to `workbench.action.previousEditor`(`cmd+alt+left`)  and then `workbench.action.nextEditor`(`cmd+alt+right`). 
4. Type some charaters in editor.
5. Press `cmd+f` to `actions.find`, then the state of `find` keeps as `wholeWords: true` and `caseSensitive: true`. It brings me some trouble, where I have to close `wholeWords` and  `caseSensitive` manually each time.

Thanks~

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@100pah There might be a bug, but I cannot reproduce:

![kapture 2017-11-22 at 11 07 42](https://user-images.githubusercontent.com/5047891/33121555-63052742-cf75-11e7-9146-73d1e66eafc3.gif)

**Comment by 100pah** [comment]
To reproduce the issue, the two tabs should in the same group ~
![cc](https://user-images.githubusercontent.com/1956569/33131303-14b47d2a-cfd1-11e7-95a8-a41d656fb6ed.gif)

**Comment by alexandrudima** [comment]
Simplified verification steps:

* open two files in the same tab group
* open the find widget (have all toggles off)
* press cmd+d without a selection on a word
* the find widget toggles become on
* press cmd+alt+left/cmd+alt+right to change tabs
* it should be that the find widget has all toggles off because the toggles were on temporarily due to cmd+d
