### ISSUE TITLE
Debugger blocked when stepping over(OSX)

### ISSUE THREAD

**Issue by meetzoo** [Microsoft/vscode#38867]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.6
project-manager|ale|0.23.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
ReactCodeSnippets|haz|1.2.1
diff-tool|jin|0.0.1
python|ms-|0.8.0
azure-account|ms-|0.2.2
debugger-for-chrome|msj|3.5.0
node-modules-resolve|nau|1.0.2
vscode-icons|rob|7.18.1
require-complete|sen|0.1.0
Align|ste|0.2.0
react-redux-es6-snippets|tim|2.1.0
beauty|yhp|0.0.2

Steps to Reproduce:

1. Start debugger, set breakpoint, launch request, breakpoint reached
2. Click on F10(step over), instead of going to next line it jumps to next breakpoint. If no breakpoint is set in the function then vscode remains in an uncertain state, with step over, step into and step out disabled(greyed-out) as if it waits for other requests, but the server does not send back the response. If I reload the debugger it releases the request and the server continues with the code processing.

Reproduces without extensions: Yes

**Comment by razvip91** [comment]
+1

**Comment by weinand** [comment]
What version of node.js are you using?

**Comment by meetzoo** [comment]
node:8.2-alpine with docker swarm

**Comment by meetzoo** [comment]
> The result of a "Step Over" is not always a stop in the next line.
> If there is a breakpoint somewhere in the code being stepped over, the debugger will break there.
> And if the code being stepped over contains a loop (e.g. a server) then the debugger will not break at all.

The problem appeared when VSCode was updated. Until then step over functioned normally, just like debugging in Chrome.
Now if I click on step over it never breaks on the next line. If there is another breakpoint later in the function it breaks there(expected), otherwise it continues the rest of the function.
The same thing happens on my colleague's mac.
I'm surprised this does not happen to other people.
Is there a way for me to upload the 
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1537992/vscode-node-debug2.txt)

**Comment by meetzoo** [comment]
https://github.com/Microsoft/vscode/issues/24678
it seems that 'smartStep:true' was the issue. I removed the line from the launch config and now it works.
Still, this issue started after the latest vscode update.

**Comment by roblourens** [comment]
Are you debugging sourcemapped code? It should always step over code that doesn't have sourcemaps.

**Comment by meetzoo** [comment]
Probably not. It is a nodejs project run inside a docker container with pm2.

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by meetzoo** [comment]
```
        {
            "type": "node",
            "request": "attach",
            "name": "local-Rest",
            "address": "127.0.0.1",
            "port": 5858,
            "restart": true,
            "protocol": "inspector",
            "smartStep": "true",
            "sourceMaps": false,
            "localRoot": "${workspaceRoot}/server",
            "remoteRoot": "/opt/mo/server"
        },
```

I removed the smartStep line and now it steps over normally again.

**Comment by roblourens** [comment]
Like https://github.com/Microsoft/vscode/issues/24678 says, smartStep only is for use with sourcemapped files. If you aren't using sourcemaps then this sounds like correct behavior.
