### ISSUE TITLE
breakpoints in typescript doesn't work.

### ISSUE THREAD

**Issue by laoqiren** [Microsoft/vscode#38863]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.0.0
ejs-language-support|Qas|0.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.1.2
tslint|eg2|1.0.23
docthis|joe|0.6.0
python|ms-|0.8.0
cpptools|ms-|0.14.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. I tried to debug typescript using vscode, and here is my `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/dist/main.js",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "console": "integratedTerminal"
        }
    ]
}
```
and here is my `tsconfig.json`:
```js
{
    "files": [
        "src/**/*.ts"
    ],
    "compilerOptions": {
        "module": "commonjs",
        "removeComments": true,
        "allowJs": true,
        "target": "es2015",
        "outDir": "./dist",
        "sourceMap": true,
        "types": [
            "node",
            "lodash"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```
I have checked that `gulp` has build `.ts` to `.js` and `source maps`.  But when I start debugging, it jump over the break points and come to end directly.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
what version of node.js are using?

**Comment by laoqiren** [comment]
@weinand V9.0.0

**Comment by roblourens** [comment]
Can you run the `.scripts` command in the debug console and post the result here?

**Comment by laoqiren** [comment]
@roblourens I don't understand what you said.

**Comment by roblourens** [comment]
Start the debug session again, type `.scripts` in the console, and it will print out the paths to your scripts, which will help us debug it. https://github.com/Microsoft/vscode-node-debug2#the-scripts-command
