### ISSUE TITLE
Crashes very often

### ISSUE THREAD

**Issue by jawahar5** [Microsoft/vscode#38860]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.11
vscode-npm-script|eg2|0.3.2
prettier-vscode|esb|0.24.0
flow-for-vscode|flo|0.7.2
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
code-runner|for|0.8.4
vscode-flow-ide|gca|1.2.0
vscode-flatland-icon-theme|geb|0.0.6
beautify|Hoo|1.1.1
Angular2|joh|2.11.2
vscode-styled-components|jpo|0.0.9
graphql-for-vscode|kum|1.6.3
node-module-intellisense|lei|1.4.0
Angular-BeastCode|Mik|5.0.16
vscode-duplicate|mrm|1.2.0
sublime-keybindings|ms-|3.0.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
vscode-jest|Ort|2.4.2
vscode-versionlens|pfl|0.19.1
promise-snippets|pro|0.2.3
sass-indented|rob|1.4.5
todotasks|san|0.5.0
preview-vscode|sea|1.3.4
code-settings-sync|Sha|2.8.3
indenticator|Sir|0.4.2
vscode-react-native|vsm|0.4.4
quokka-vscode|Wal|1.0.74
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.4.0
html-css-class-completion|Zig|1.12.0

(2 theme extensions excluded)

---

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
There is not enough information to investigate. Please see our guide on how to report an issue: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues
