### ISSUE TITLE
Feature request - Open file in a different monitor.

### ISSUE THREAD

**Issue by shauliz** [Microsoft/vscode#38874]
Hi,
Used to work with VS2017 on multiple monitors. When I needed to compare or work with 2 files at the same time, I was able to open both files in 2 different screens by just dragging one file out side from VS. I find that in VS Code this feature is absence.

It would be great to have this feature in VS Code as well.

Thanks!
Shaul

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/33112440-84019ae2-cf53-11e7-93af-57195a69a0f0.png)

**Comment by shauliz** [comment]
Thanks!
