### ISSUE TITLE
Syntax highlighting not correctly identifying var, let

### ISSUE THREAD

**Issue by davidwebber10** [Microsoft/vscode#3887]
It appears the words 'var' and 'let' are highlighted whenever they are the beginning letters of a variable. Those specific letters inside the variable name are highlighted with dark blue, and then the variable value (which should be highlighted with the red) is actually highlighted as a variable with light blue.

This appears to affect all themes that do alternate highlighting for words like 'var' and 'let'.

![screen](https://cloud.githubusercontent.com/assets/7406786/13618187/bd582be2-e550-11e5-9152-bfe48ea627b2.jpg)

**Comment by aeschli** [comment]
That's https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

It will be fixed in the coming March release
