### ISSUE TITLE
feature request: 'File > Recently Closed' files

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38872]
VS Code 1.18.1
OS Windows 7

'File > Recently Opened' only show file recently opened via the file menu and not any other mechanism, such as double clicking in the explorer view (reported by team as 'by design').

Please add an auto-populated item 'File > Recently Closed' which tracks files opened via any mechanism in such a way as to keep them in the tab list and then closed. It should be straightforward to track such files as their 'keep open' state is known at the time of closing.

**Comment by bpasero** [comment]
You can use Ctrl+P for that purpose, we keep a list of recently opened editors in there.

**Comment by draeger-charles-wilson** [comment]
It's nice that there exists numerous keyboard shortcuts.

The point of a graphical user interface it to expose obvious and common use cases. It's not a shortcut if there is no other way of accessing the functionality.
