### ISSUE TITLE
Copy property path option in Debug window

### ISSUE THREAD

**Issue by sebastijandumancic** [Microsoft/vscode#38871]
Using Variables window in Debug mode, it would be VERY usable to have copy property path, like in debugging tools console. 

VS code: 
![screen shot 2017-11-21 at 13 15 13](https://user-images.githubusercontent.com/7857336/33072070-4ac06ea6-cebe-11e7-98c7-6dc49543768e.png)

Chrome console:
![screen shot 2017-11-21 at 13 18 11](https://user-images.githubusercontent.com/7857336/33072128-7f370d16-cebe-11e7-8f18-a02de7c4f7fb.png)

Chrome console gives you ability to copy property path which gives something like this: 
` ... soap:Envelope][soap:Body][0].GetResponse[0] ...` while VS code gives you only copy value and currently selected item. This is very useful when fetching deeply nested API information. 

In chrome I can just dig through the tree and copy last property path, while in VS code everything needs to be typed out manually. 

Thanks for considering this feature :)

**Comment by weinand** [comment]
@isidorn since the DAP provides the path as an evaluatable expression, this sounds like low-hanging fruit.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19580

**Comment by isidorn** [comment]
@sebastijandumancic as mentioned in the other issue, this is low hanging fruit and a PR is welcome
