### ISSUE TITLE
CTRL+d or CMD+d for duplicate line

### ISSUE THREAD

**Issue by sas05** [Microsoft/vscode#38875]
to duplicate a line now I think, CTRL+c; CTRL+v and from OSX CMD+c; CTRL+v. isn't it make sense to have it like CTRL+d and CMD+d

**Comment by TroX-oO** [comment]
Just add the shortcut in your preference:

```
{
  "key": "ctrl+d",
  "command": "editor.action.copyLinesDownAction",
  "when": "editorTextFocus && !editorReadonly"
}
```

Be careful, it will override the current `ctrl+d` shortcut (which is to add to selection the next string matching your current selection)

A common usage is `ctrl+shift+d`, but it is totally your choice.
