### ISSUE TITLE
Error debugging PHP running Listen for XDebug

### ISSUE THREAD

**Issue by juanqui66** [Microsoft/vscode#38882]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
ionic3-vs-ionView-snippets|dan|1.0.1
githistory|don|0.2.3
php-debug|fel|1.12.0
vscode-git-tags|how|1.1.2
cordova-tools|vsm|1.3.1

---

Steps to Reproduce:

1. Press in 'Listen for XDebug'.
2. Appears: 'El proceso de adaptación del depurador finalizó inesperadamente' Twice.

Until now, the PHP debugger worked correctly. Since a few minutes I see this error (in Spanish) without having changed any configuration, simply restarting VS Code.

Any ideas?

Thanks in advance.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file this issue against the repository of the php extension you are using.
You can use this tool to move the issue: https://github-issue-mover.appspot.com
