### ISSUE TITLE
HTML closing tag proposal filtered out

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#38880]
- create a HTML file:
```
<body>
	<
```
(tab character before <)
- code assist after `<`
- `/body` should show up, but is filtered out by the suggest widget

- set a breakpoint in `completionModel.ts`, line 164, after `fuzzyScore`: https://github.com/Microsoft/vscode/blob/b22bd4778f03e3382fda585ab5dc18bb5ce7724d/src/vs/editor/contrib/suggest/completionModel.ts#L164

The proposal is special as its text edit also adjusts the indentation: it replaces from the start of the line. Therefore, the `filterText` also contains the leading indent and `<`.

Note that things work if you replace the tab with a space.

**Comment by jrieken** [comment]
@aeschli Your completion doesn't seem to pass the `filterText` check. You have a special edit (selecting more) your `filterText` must also include that. Maybe a good usage for additional edits

**Comment by aeschli** [comment]
@jrieken As explained, the filterText contains all of the replaced text. When you debug you see that the filter starts with the current word, `suggestion.filterText.substring(0, word.length) === word` is true.
My suspicion is that there's a bug in the filter code regarding whitespace handling.

**Comment by jrieken** [comment]
> My suspicion is that there's a bug in the filter code regarding whitespace handling.

Yeah, we do ignore leading whitespace in the pattern/word and that's done for a reason. I need to digg it up again

**Comment by jrieken** [comment]
@aeschli I don't see that...

<img width="286" alt="screen shot 2017-11-24 at 12 12 52" src="https://user-images.githubusercontent.com/1794099/33208170-d193c546-d110-11e7-9c86-b049e915f858.png">

**Comment by aeschli** [comment]
That is strange. Now I only get it with two tabs:
![image](https://user-images.githubusercontent.com/6461412/33209491-5ad42274-d116-11e7-9e8d-46b8c07eeaf8.png)

**Comment by aeschli** [comment]
There's a related issue after `</`:
![image](https://user-images.githubusercontent.com/6461412/33209537-924a0250-d116-11e7-926d-3b28806a3ae1.png)
