### ISSUE TITLE
Dedents on regex ending in `*`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#38886]
- VSCode Version: Code - Insiders 1.19.0-insider (c8c6b13528c03986b8dad654cb1d3e796e8dbe97, 2017-11-20T06:15:17.286Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Type: 
```ts
function f() {
	return f();
}
```
2. Type `/.*/` inside the call to `f();`.
3. It undoes the indentation, giving you:
```ts
function f() {
return f(/.*/);
}
```

(Moved from Microsoft/TypeScript#17031)

**Comment by rebornix** [comment]
`*/` triggers unindent.

**Comment by mjbvz** [comment]
Closing as this appears to have been fixed at some point. I can no longer repo it in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)
