### ISSUE TITLE
Show both Output and Debug Console at the same time

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#3888]
Hi,
Is it possible to show both Output and Debug Console at the same time?
If not, could you please add such a feature?

It might also be interesting, if we could show several output channels at the same time too.

**Comment by felixfbecker** [comment]
this goes in line with my feedback on https://github.com/Microsoft/vscode/issues/2806

**Comment by JanKok** [comment]
I'm relaying an idea by @WebFreak001: Put tabs on the window so you can choose between Output, Debug Console, etc.

**Comment by bpasero** [comment]
Closing, we currently do not plan to work on this.
