### ISSUE TITLE
When word wrap is disabled text still wraps. Setting wordWrap to on then off doesn't help it either.

### ISSUE THREAD

**Issue by daneshmandi** [Microsoft/vscode#38881]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

I have set  the following in User Settings:
  "editor.wordWrap": "off",
  "editor.wordWrapColumn": 300

but still it wraps the following line in code as follow:
const componentFactory = this.componentFactoryResolver.resolveComponentFactory(
        ButtonWidgetComponent
      );

Reproduces without extensions: Yes/No

**Comment by jbeaudoin11** [comment]
Yeah sometime it still wrap for some reason.. Try to reload the window via the command F1 + Reaload Window, it worked for me.

**Comment by daneshmandi** [comment]
@jbeaudoin11 It didn't work for me. BTW here is all my User Settings:

{
  "workbench.colorTheme": "Default Light+",
  "workbench.sideBar.location": "left",
  "window.zoomLevel": 0,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "editor.renderWhitespace": "all",
  "editor.acceptSuggestionOnEnter": "on",
  "editor.autoClosingBrackets": true,
  "editor.autoIndent": true,
  "editor.find.autoFindInSelection": true,
  "editor.matchBrackets": true,
  "editor.acceptSuggestionOnCommitCharacter": true,
  "editor.find.seedSearchStringFromSelection": true,
  "editor.suggestOnTriggerCharacters": true,
  "editor.minimap.enabled": false,
  "typescript.format.placeOpenBraceOnNewLineForFunctions": true,
  "typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
  "typescript.format.insertSpaceAfterTypeAssertion": true,
  "workbench.panel.location": "bottom",
  "javascript.format.placeOpenBraceOnNewLineForFunctions": true,
  "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
  "editor.wordWrap": "off",
  "editor.wordWrapColumn": 300
}

**Comment by daneshmandi** [comment]
@jbeaudoin11 I just added to see if it has any effect which has not.

**Comment by sjee** [comment]
This happens to me when I save. A line of code such as this:

`myElement.style.position = 'absolute';`

changes into:

```
myElement.style
        .position = 
        'absolute';
```

Or:
`console.info('testvar: ', testvar);`

becomes:

```
console.info(
        'testvar: ',
        testvar);
```
Basically, Visual Studio Code wraps after each assignment, opening bracket and dot notation despite the fact that wrapping is disabled (as far as I can tell).

**Comment by alexandrudima** [comment]
@daneshmandi If you search for `wordWrap` in user settings, by default, VS Code ships with:
```
"editor.wordWrap": "off"
...
"[markdown]":  {
    "editor.wordWrap": "on",
    ...
}
```
which means, **out of the box, word wrapping is enabled for markdown**.

**When opening a file that is dominated by long lines VSCode will also word wrap**. e.g. try opening `jquery-3.2.1.min`. In such cases we show a button at the top of the editor:

![image](https://user-images.githubusercontent.com/5047891/33121223-706033d8-cf74-11e7-8455-c9d063b4a723.png)

---

Now, all of that is the default, out-of-the-box behaviour. Extensions have the possibility to overwrite that behaviour. @daneshmandi @sjee Can you reproduce when disabling extensions ?

**Comment by daneshmandi** [comment]
@alexandrudima Thanks for the help. I confirm that my issue was because of an extension (Prettier-Code formatter) that was installed as part of "Angular Essentials Extension". When I disable the extension it work as expected with no wrapping.

**Comment by AbdelElrafa** [comment]
Hey guys, sorry to open this again but I tried this with no extensions and a fresh install and I'm having the issue that JS files have word wrap turned on always. Even if wordwrap is off it's always on for js files, unless I toggle it in that file. But when the editor opens back up the wrapping is enabled again.

**Comment by sjee** [comment]
In my case, I removed "JS-CSS-HTML Formatter" and the problem was resolved. 
_(That extension was changing the formatting when saving files.).

**Comment by AbdelElrafa** [comment]
I don't have that plugin.
