### ISSUE TITLE
Feature Request: "Autocomplete" should add the function signature

### ISSUE THREAD

**Issue by RonanC** [Microsoft/vscode#38887]
When you tab to `autocomplete` you get the function name but not the function signature.
It would be great to have it auto-populate the signature and place the cursor in each position letting you overwrite the input parameter name.
Similar to the way you can autocomplete a `for` loop:
<img width="369" alt="for" src="https://user-images.githubusercontent.com/6930753/33084471-f930d64a-ced9-11e7-98b3-294364181ed3.png">

I've been searching for a plugin or native way to do this for a while and came up with nothing.

An example of where I would like to see this feature is for `window.addEventListener`:
<img width="217" alt="window" src="https://user-images.githubusercontent.com/6930753/33084494-0fad4232-ceda-11e7-85ae-912c4e3e2369.png">

**Comment by misoguy** [comment]
I'd like to give this a shot if no one is on it yet 😄

**Comment by misoguy** [comment]
@RonanC I've looked into this issue and found that there is already an implementation for this feature. If what you need is autocompletion for `js` files turn on the `"typescript.useCodeSnippetsOnMethodSuggest"` to `true` and check if this is what you wanted.
If it doesn't work or wasn't what you wanted please leave a comment 😄

**Comment by RonanC** [comment]
That looks like it solved it for me!

**Comment by misoguy** [comment]
I guess this issue can be closed then 😄
