### ISSUE TITLE
Code completation for HTML is broken

### ISSUE THREAD

**Issue by lealcy** [Microsoft/vscode#38883]
- VSCode Version: Code - Insiders 1.19.0-insider (d294b25f2dd5c96d89bd23f82bd5fd2c0958a4bd, 2017-11-21T06:34:51.660Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Create a new HTML file.
2. Type HTML<space>. In other builds  it show na auto-completation context menu. In this last one not is showing.

**Comment by lealcy** [comment]
Ah, i got why. My extensions vanished. Never happen before.
I know it is a strange question, but does the change of motherboard I did have something to do with it?

**Comment by aeschli** [comment]
Maybe make a clean install of VSCode? I this is still reproducible, please add a small code snippets and steps that demonstrate the problem. Screenshot are also useful.
