### ISSUE TITLE
`http.proxy` in settings does not work, but command line option `--proxy-server=` does

### ISSUE THREAD

**Issue by nauhygon** [Microsoft/vscode#38888]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
(1 theme extensions excluded)
---

As in title. Thanks!

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Yes. That is already documented: https://code.visualstudio.com/docs/setup/network
