### ISSUE TITLE
Color highlighting bugs with PHP code inside <style> element

### ISSUE THREAD

**Issue by matthewslouismarie** [Microsoft/vscode#38885]
Hi. Sorry if this is in the wrong repo (wasn't sure if it should be in vscode-html-languageservice because it also involves PHP).
- VSCode Version: 1.18.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a PHP file outputting HTML outside the PHP tags
2. Include a file within a style element

![vsbug](https://user-images.githubusercontent.com/17742458/33083486-660eea52-ced7-11e7-9769-8f651537dbe8.png)

Reproduces without extensions: Yes

**Comment by jens1o** [comment]
@roblourens yeah, they have been commits in the grammar which maybe fix these issues.
