### ISSUE TITLE
Tab groups "for components"

### ISSUE THREAD

**Issue by jbeaudoin11** [microsoft/vscode#38889]
Hi,

I was looking to do an extension for vs code. I'm currently developing with Angular 1.6 and i'm building many components. Each one of them as 4 files : index.js, ctrl.js, template.pug, style.scss. I open a lot of tabs and i just end up not using them cause i have too many.. So i just search the file in the tree instead it's quicker.
![image](https://user-images.githubusercontent.com/10903391/33082494-efd55b36-ceaa-11e7-9457-b7d1d20ee58e.png)
![image](https://user-images.githubusercontent.com/10903391/33082533-070b76be-ceab-11e7-89eb-fab0fa8a3f97.png)

I'm sure we could do something about that ! My main idea is to add tab groups. This is an example of what i mean :
![image](https://user-images.githubusercontent.com/10903391/33084279-86a9b6d4-ceaf-11e7-9d80-e17475c64490.png)

It would need to be configurable because, we don't all have the same structure..  With all the component base frameworks out there i think there is definitely a lot of people that would benefit from this :)

But i have no experience with vs code extensions and i think there is no way of doing this since we don't have DOM access :/. So what do you guys think of this ?

**Comment by phil294** [comment]
This would be a very helpful feature. Maybe another way of imagining this:

Make tabs be either a **file** or a **group**. Groups are marked visually to distinguish them. Adding a group does not show anything inside it, it is an empty tab. Anything you open while that group is active, becomes a new **tile** that is draggable. This way, you can switch tabs, and some tabs can contain multiple tiles.

**Comment by jbeaudoin11** [comment]
My main idea was to group tabs if they share some context. Should it be detected via folder structure ? Maybe, but it would be hard to please all.. Maybe it could be done manually as a first iteration and test if it does indeed helps with the problem.

I posted that a while ago.. not sure if it will be done tbh. Someone with more time could try to do it in a fork and who knows what MS will do with this.

**Comment by iliyang** [comment]
The way I see it, this problem would be solved by the general concept of _tab hierarchy_, i.e. having not just a flat list of open documents but a tree of tabs. In most cases this tree would have two levels, but I can see the benefit of having it deeper.

The concept itself is relatively straightforward. Figuring out the UI would be more tricky, I imagine.

**Comment by bhaskar-nair2** [comment]
So, wassup?

**Comment by jonas-k** [comment]
In my opinion the feature should be built as simple as possible to prevent a cluttered UI / too many settings.
From my understanding three options would suffice:

1. No Tab Groups
2. Tabs grouped by folder (all open files that are in the same folder are displayed in a group (similar to the original feature request)
3. Tabs grouped by folder and filename

Option 3 is helpful if the files are named MyComponent.html, MyComponent.js, MyComponent.css but is also great for C++ developers which have MyClass.cpp and MyClass.h.
The UI is also straight forward: simply have a tab with the file name without extension and separate buttons for the file extensions.

**Comment by CWempe** [comment]
The new Chrome version has this feature now.  

![image](https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Tab-Groups-Organization-Example_v1r1.gif)

https://blog.google/products/chrome/manage-tabs-with-google-chrome

I think vscode should do this in a similar way.

**Comment by PalmTreeBlvd** [comment]
Really excited for this feature when it comes 🙏

**Comment by bpasero** [comment]
Even though https://github.com/microsoft/vscode/issues/100335 is newer, I think it makes sense to merge the two.

/duplicate https://github.com/microsoft/vscode/issues/100335
