### ISSUE TITLE
Don't indent after brace in comment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#38890]
- VSCode Version: Code - Insiders 1.19.0-insider (c8c6b13528c03986b8dad654cb1d3e796e8dbe97, 2017-11-20T06:15:17.286Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Type:
```ts
function f() {
```
2. Hit enter.
3. Next line is indented -- but we're in a comment, so we probably want to align with the start of the previous line.

**Comment by rebornix** [comment]
Thanks @andy-ms , it's a dup of https://github.com/Microsoft/vscode/issues/38890, let's track it there.

**Comment by andy-ms** [comment]
This is #38890
