### ISSUE TITLE
VSCode deleted my project's files 

### ISSUE THREAD

**Issue by Perdouille** [Microsoft/vscode#38894]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-1-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
php-debug|fel|1.12.0
phpcs|ika|0.7.0
mssql|ms-|1.2.1
sublime-keybindings|ms-|3.0.3

---

Steps to Reproduce:

1. No idea at all. I was coding, and it deleted everything in my project. It happened twice on 2 different computers, I have no idea what triggered it. Both computers were using 1.18.1

Reproduces without extensions: No idea

**Comment by joaomoreno** [comment]
Try to reproduce without using any extensions. If you can, you can file another issue.
