### ISSUE TITLE
Allow multiple cursors between split panes

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#38893]
When working with a large file, I often use split panes to see multiple parts of the file simultaneously to avoid lots of navigating back and forth.

Sometimes I find the need to use multiple cursors where one part of the code is in one pane, and another part of the code is in another pane.

I don't believe that it's possible to work with multiple cursors across multiple panes, but it would be great if it was possible. The shortcut for adding multiple cursors across panes would probably have to be different from the default, to avoid unexpected behaviour.

**Comment by GCrispino** [comment]
I was about to create a issue for this feature, it would come in handy in some use cases, like scrolling at the same time in different files

**Comment by theseanco** [comment]
This would be a great feature if it could be implemented

**Comment by len-samuelson** [comment]
I think this feature exists. Here's how I do it using Code 1.37.1 (Linux, x86_64):

I have "n" panes open with the file of interest open in one of them, then I ctrl-drag the tab referring to the file from the pane where it's open to the pane where want to edit the duplicate view of the file.

I switch panes without changing the location of the target pane's edit cursor by clicking in the tab for the pane where I want to continue editing. Cursor position is preserved (unlike the case when clicking in the main editing area).

This is a wonderful feature that I use all the time, particularly for files in languages such as C/C++ with separated static declarations (usually near the top) and usage (elsewhere). I just checked and cursor state is preserved consistently across the views, including the magic multiple-cursor ctrl-click trick.

Never being satisfied.... It would sure be nice if this sort of simultaneous active multi-view capability could be applied across separate top-level windows, for those of us spoiled by having multiple monitors. At present, it is possible to *see* a file in separate windows, but file edit state is not exchanged between them, and forgetting that fact can lead to "difficulties"...  :-)

**Comment by drzamich** [comment]
I need this a lot as well. My use case: modifying parameters list in function declaration and all the places the function is run at the same time.

**Comment by luca-serra** [comment]
Hey! Still interested in this in 2024 👀

**Comment by TheOnlyWayUp** [comment]
This would be awesome

**Comment by sian2005** [comment]
I second this issue aswell :)
