### ISSUE TITLE
check the update on mac osx 10.13 

### ISSUE THREAD

**Issue by jyear** [Microsoft/vscode#38896]
- VSCode Version:1.19.0-insider
- OS Version: mac osx 10.13

Steps to Reproduce:

1.when i click check update,
2.show the error: 'Could not create temporary directory:权限被拒绝'

Could not create temporary directory: 权限被拒绝
Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426
