### ISSUE TITLE
(macOS) Can't view 'BS' in vscode

### ISSUE THREAD

**Issue by yzlnew** [Microsoft/vscode#38897]
- VSCode Version: 1.18.0
- OS Version: macOS 10.13.1

Steps to Reproduce:

Casual typing in default Chinease input method.

Reproduces without extensions: Yes/No

Maybe due to the default Chinese input method, I'm keep tying 'BS' (0x08 in ASCII) in vscode, which is annoying but I can't view.

In vscode:
![jietu20171120-141005](https://user-images.githubusercontent.com/4904877/33064693-8434a3f0-cee1-11e7-919b-1c1cbd4df823.jpg)

In Sublime Text:
![jietu20171120-140935](https://user-images.githubusercontent.com/4904877/33064713-917e89cc-cee1-11e7-8f37-97e303c52648.jpg)

**Comment by alexandrudima** [comment]
That would be `BACKSPACE`. 

@yzlnew What input method are you using ? Do you have any steps ?

**Comment by yzlnew** [comment]
I'm using the default Pinyin input Apple provided. 
Maybe it's because of tying English in Pinyin input method, but I'm not quite sure. It happens ocasionally.

**Comment by rebornix** [comment]
@yzlnew did you ever open Markdown Preview during using VSCode?

**Comment by yzlnew** [comment]
@rebornix Nope. I'm using LaTeX-Workshop. Anything to do with the preview?

**Comment by alexandrudima** [comment]
@yzlnew Would `View > Toggle Control Characters` at least alleviate the issue for you ?

**Comment by rebornix** [comment]
@yzlnew LaTeX-Workshop preview does the same trick. If you once preview your Latex content, it opens a webview, and that webview will trigger a Chromium IME bug and while you are typing Chinese (in composition), a backspace may emit the control character. Can you help confirm that?

**Comment by yzlnew** [comment]
@rebornix Yes, I can confirm that. With a webview open, type anything in Pinyin and press Backspace twice can reproduce this bug.
Also @alexandrudima 's method works, I can see a tiny 'BS' now.

**Comment by rebornix** [comment]
We already have an issue tracking this IME/Electron issue https://github.com/Microsoft/vscode/issues/37114 , thanks.
