### ISSUE TITLE
debugAdapterCrash, "Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by jmperro** [Microsoft/vscode#38895]
- VSCode Version: 1.18.1 x64
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Open folder with php files and php debug configurations
2. Press F5

The listening port of XDebug at php.ini and the launch.json is the same.
I've no other app listening on this port.

This is the error 
![2](https://user-images.githubusercontent.com/3727544/33085769-68bf15e6-cec4-11e7-940e-9d1be81fafb9.png)

**Comment by weinand** [comment]
This issue was moved to felixfbecker/vscode-php-debug#204
