### ISSUE TITLE
UI glitch when hovering "Stage Changes" 'plus' button

### ISSUE THREAD

**Issue by joaosardinha** [Microsoft/vscode#38891]
- VSCode Version: 1.19.0-insider 2017-11-21
- OS Version: Fedora 27 on Gnome 3.26

Steps to Reproduce:
1. edit a file that has no git changes so it gets added to the list of files with changes
2. hover the "plus" button to stage changes
3. see glitch

This just happens the first time you hover, if you revert the changes and add changes again you can reproduce again. 

![23804271_1559930387437181_471916345_n](https://user-images.githubusercontent.com/15181917/33084720-95ea21bc-ceda-11e7-9f13-8eef5f003b87.jpg)
(Sorry for photo, clicking my screenshot buttons would unfocus the mouse and remove the hover)

I know this is very minor and not at all annoying but I just thought I should report.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/8901

**Comment by carestad** [comment]
Sure this is related to #8901? This seems related to https://bugs.chromium.org/p/chromium/issues/detail?id=442111

**Comment by joaosardinha** [comment]
Same issue happens in Discord, so very likely a Chromium/Electron issue. Feel free to close.
