### ISSUE TITLE
[less] support inner selector completions after '.abc:'

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#3890]
After the latest release less intelisense is broken.

Please see the attached images for the difference in intellisense when selected mime is less vs. css

![css](https://cloud.githubusercontent.com/assets/8544875/13621750/feaf8548-e5ed-11e5-8fb6-44f67b6ed25e.JPG)
![less](https://cloud.githubusercontent.com/assets/8544875/13621792/487007ca-e5ee-11e5-87d8-6a49489333a9.JPG)

Also when changing mime type from less to css you get syntax errors as expected, but when changing from css to less the syntax errors do not refresh it keeps the same state until you close the file in working files and reopen
![less_syntax_erros](https://cloud.githubusercontent.com/assets/8544875/13621917/0d61f304-e5ef-11e5-8b13-3194dd37a8f2.JPG)

Thanks

**Comment by aeschli** [comment]
If I understand right, this is a similar snippet:
```less
.btn-group {
  .btn:

}
```
and you try to do code completion after the `:`

This is a bit of a tricky case for the LESS parser to detect, and never worked. Why you get some results in CSS is that the CSS parser went into error recovery after seing the inner class name.

**Comment by eByte23** [comment]
Yes your snippet is similar.
I though previously I had used it.
CSS though the pseudo's already work when there is no error(using straight CSS)
