### ISSUE TITLE
Ruler disappears after reloading window with zoomLevel < 0

### ISSUE THREAD

**Issue by WesleyYue** [Microsoft/vscode#38901]
- VSCode Version: Version 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Set a ruler in user settings
2. Zoom out
3. Reload window

Any change to the ruler length fixes it temporarily.

Reproduces without extensions: Yes

Related: #9634

**Comment by alexandrudima** [comment]
Duplicate of #38656
