### ISSUE TITLE
Support user-specific per-workspace settings (eg. settings.user.json)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#38902]
Currently if you want to set a setting for a specific project you need to put it in the workspace settings file (eg. `.vscode\settings.json`). It's often useful for this file to be committed to source control (eg. it might contain formatting settings or other settings useful to share with your team).

Sometimes it's also convenient to have settings that are not shared - for example an SDK override path. It's not always appropriate to move these to user settings because you may only want to override them for a specific project.

As a concrete example, in my Dart extension I want to allow the user to set the path of the Dart SDK - it should be per-project because different project types require slightly different SDKs. We don't want to add different settings for each project type because it ends up being 6 options and it would be confusing for a user to know they should set (for example) `dart.flutterDartSdkPath` instead of just `dart.sdkPath`. It wouldn't make sense to commit, since it's a path that's local to the users machine.

It would be great if we could have two files for settings within a folder (eg. `settings.json` and `settings.user.json`) so that one would be excluded from source control while the other is committed. The user one should override the general one also allowing the user to override settings if they wished without changing the source-controlled settings file.

**Comment by sandy081** [comment]
@DanTup 

We have released a new Multi-root Workspace Feature where you can open multiple folders in a workspace. This introduces a new abstraction in settings.

`User -> Workspace -> Folder`

Settings under `.vscode` folder are called now `Folder` settings in a Multi-root workspace. You also have `Workspace` settings those get applied for complete workspace. For more information refer [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings).

You can open a folder in a workspace as follows and can use `Workspace` settings here as user specific workspace settings for the folder.

- Open an empty window and add the folder to it.

Please try it out and let us know if that solves your issue

**Comment by DanTup** [comment]
@sandy081 Thanks for the info, though unfortunately it doesn't really work for my scenario because the setting is written by the extension, not the user. I have a UI in my extension that lets the user quickly switch between versions of the SDK:

<img width="638" alt="screen shot 2017-07-15 at 20 16 05" src="https://user-images.githubusercontent.com/1078012/28242084-79ac87d8-699a-11e7-8dc0-8c856c1549aa.png">

When the user selects an SDK I want to write it into the Folder-level settings (this makes more sense than setting in User-level settings because it's likely a temporary thing for a single project). If course, if the user has that file checked in, this will show up as a change to commit.

**Comment by DanTup** [comment]
I've started the work on upgrading Dart Code for multi-root support and realised that setting this option at the folder level wouldn't actually work! The SDK path is a `window`-scoped setting (since we use one analysis server for all folders) and therefore we wouldn't be able to use a folder-level setting anyway.

That said - it might still be useful for people to commit their workspace files, so I think it's still a reasonable request at that level - allowing user-specific workspace-settings that don't get committed, while still allowing a file with shared settings to be?

**Comment by sandy081** [comment]
@DanTup Good that you revisited the setting and defined as window scoped. 

I agree that having non-shareable workspace settings are useful. For such scenarios, I am trying to advocate to use new Workspace features and collect feedback. Hence, I would like to close this request as out of scope until we get more feedback from users. Thanks for understanding.

**Comment by DanTup** [comment]
@sandy081 Understood. Thanks for the info!
