### ISSUE TITLE
Autocomplete for export default glitch

### ISSUE THREAD

**Issue by Mickey0001** [Microsoft/vscode#38907]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. In a JavaScript React file start typing "export default" at the bottom to export a component 
2. After using tab to auto-complete "default"  following incorrect import shows up at the top: 
"import default from '../reducers/reducer_posts';"

Screenshot:
![image](https://user-images.githubusercontent.com/23509920/33102135-6d1dd710-cee9-11e7-954e-24060a3a177f.png)

Here is the code:
```

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { fetchPost } from '../actions';




class PostsShow extends Component {
    render() {
        return (
            <div>
                Posts Show.
            </div>
        );
    };
}


```

**Comment by mjbvz** [comment]
This is https://github.com/Microsoft/TypeScript/issues/19841

Please try the latest VS Code insiders which should have already fixed this issue

**Comment by Mickey0001** [comment]
Thanks, it's okay now I can no longer replicate the issue after the last update.
