### ISSUE TITLE
Cannot open CSV file

### ISSUE THREAD

**Issue by gtaranti** [Microsoft/vscode#38900]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13 & Windows 10 x64

Steps to Reproduce:

1. Try to open a small csv file like the one I'm submitting. (I've changed  the extension to *.txt in order to be allowed to submit it) 
[2017-11-21-OILUSD.txt](https://github.com/Microsoft/vscode/files/1492700/2017-11-21-OILUSD.txt)

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
It's because the mimetype in this file is `application/octet-stream`. You can check it for example [here](http://checkfiletype.com/). But why, i don't know. I did some research in this file and viewed it in hex, but I found nothing that I could explain it to myself.

**Comment by gtaranti** [comment]
Maybe b/c this file is created by a C# console app with `StreamWriter` : 

`foreach (...loop...) {`
`var date = DateTime.Now.ToString("yyyy-MM-dd");`
          `  using (StreamWriter w = File.AppendText(date + "-OILUSD.csv"))`
         `   {`     
                `w.WriteLine(args.Text.Replace(' ', ';'));`
          `  }`
`}`

Is it because I don't explicitly close the file? But it's `using` job to do that.
Either way, I think vscode should open files of this mime type. Other electron apps dp.

**Comment by bpasero** [comment]
@gtaranti the file seems to be detected as binary file on our end because it contains 0-bytes which are never present in text files unless the file is UTF-16. If the file is UTF-16 it requires a BOM in the beginning. Once that is there you should be able to open the file in VS Code.

**Comment by bpasero** [comment]
Actually the file seems to be literally binary:

![image](https://user-images.githubusercontent.com/900690/33112733-ffef059e-cf54-11e7-9df1-8209cd3d1428.png)

**Comment by gtaranti** [comment]
True.
In creating the file from C# I stripped the `\0`s from the strings before writing to file and now vscode opens the file w/o problem.
