### ISSUE TITLE
Go to definition not working (F12)

### ISSUE THREAD

**Issue by lobo2301** [Microsoft/vscode#38910]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
ng-template|Ang|0.1.7
vscode-html-css|ecm|0.1.8
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
smarty|imp|0.2.0
diff-tool|jin|0.0.1
partial-diff|ryu|0.5.0
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by funkyLover** [comment]
same here
- VSCode Version: Code 1.18.1
- macOS 10.12.6

**Comment by mwlpeeters** [comment]
Have the same problem

- VSCode Version: Code 1.18.1
- Windows 10

On top of my code window a blue bar is endlessly moving from left to right.

**Comment by mjbvz** [comment]
@lobo2301 There is no information to work with here. Please see this guide for reporting issues: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues

@funkyLover and @mwlpeeters Please open new issues
