### ISSUE TITLE
Autocomplete bug in PHP

### ISSUE THREAD

**Issue by saharso** [Microsoft/vscode#38919]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:19:36.079Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---
Pressing the ">" is very common when writing php and html.

whenever i use this sign for example to close an html tag and hit "enter", an autocomplete window opens and if i ignore it, the string "$_COOKIE" is automatically printed, which foreces me to manually delete it or press the "esc" key to close the autocomplete window.

This is intrusive to my workflow and slows down my work.

You can see it in the attached image.

Please fix this in the next update.

Thank you !

![bug](https://user-images.githubusercontent.com/19216444/33109496-87a92dda-cf4a-11e7-89e4-72e820c70ffa.jpg)

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
#37919
