### ISSUE TITLE
Keep the order of files which I have set even after the new file has been opened

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode#38918]
**Feature Request:**

- VSCode Version:

![](https://i.imgur.com/RSrLQq2.png)

- OS Version:

`Win 8.1`

**Use case:**

I would like to keep the order of files which I have set even after the new file has been opened. Now it opens the new file in between the already ordered files. Which is a really annoying thing.Please see the attached `youtube video` for more info.

**Youtube video:** https://youtu.be/l1b8LafK24w

**Comment by bpasero** [comment]
you can do this via `"workbench.editor.openPositioning": "last"`

**Comment by Sampath-Lokuge** [comment]
Oh.. Thanks a lot. I have used "workbench.editor.openPositioning": "first" @bpasero
