### ISSUE TITLE
High CPU usage on Mac OS.  Drains battery on laptop.

### ISSUE THREAD

**Issue by rchavez-nejmgroup** [Microsoft/vscode#38913]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
swagger-viewer|Arj|1.4.0
vscode-generate-getter-setter|DSK|0.4.2
xml|Dot|1.9.2
replace-smart-characters|DrM|0.0.2
beautify|Hoo|1.1.1
swift|Kas|0.0.3
cform|aws|0.0.10
open-html-in-browser|cod|0.1.21
json-tools|eri|1.0.2
auto-close-tag|for|0.5.3
rest-client|hum|0.16.1
json-escaper|jos|1.0.1
lambda-snippets|log|0.2.0
prettify-json|moh|0.0.3
copy-json-path|nid|0.0.1
qub-xml|qub|1.2.1
typescript-hero|rbb|1.7.0
vscode-statusbar-json-path|ric|1.0.7
guides|spy|0.9.1
stardog-rdf-grammars|sta|0.0.5
code-spell-checker|str|1.4.12
higlight-matching-tag|vin|0.1.1
vscode-apielements|vnc|0.6.7
vsc-jsonsnippets|wmo|0.1.4
ab-html-formatter|zov|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Just start up VSCode and open a file
2. Open Activity Monitor and find Code Helper chewing up CPU

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by rchavez-nejmgroup** [comment]
Will give this a try.  Thanks!

**Comment by rchavez-nejmgroup** [comment]
I did launch VSCode from the command line: code --disable-extensions

Still seeing the high CPU usage
![2017-12-05_08-46-05](https://user-images.githubusercontent.com/12071955/33610301-186ccf4a-d999-11e7-8baf-ec7cb6c1a55f.png)
 - this doesn't seem to be an extension problem.
