### ISSUE TITLE
Auto import inserts import into a comment

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#38914]
- VSCode Version: Code - Insiders 1.19.0-insider (d294b25f2dd5c96d89bd23f82bd5fd2c0958a4bd, 2017-11-21T06:34:51.660Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create a new folder
1. Open in Code
2. `npm i @types/node`
3. Create `index.js`
4. Type `/// <reference types="node" />`
5. Type `setTimeout`, select the auto import suggest.

Expected Result:

````JavaScript
/// <reference types="node" />

import { setTimeout } from "timers";

setTimeout
````

Actual Result:

````JavaScript
/// <reference types="node" />import { setTimeout } from "timers";



setTimeout
````

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20293
