### ISSUE TITLE
来自洛桑

### ISSUE THREAD

**Issue by luluyiluchangtong** [Microsoft/vscode#38917]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  Cannot select multiple files at the same time, then delete
2.  The quotation mark, the curly braces need to add a space to be able to auto complete
```js
 <div>{</div>   // won't auto-complete
 <div className="></div>   // won't auto-complete
```

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
