### ISSUE TITLE
Indentation breaks code folding

### ISSUE THREAD

**Issue by westy92** [Microsoft/vscode#3891]
I am using the latest version on Windows 7 Pro x64.
![image](https://cloud.githubusercontent.com/assets/290167/13622648/c1ccb5de-e565-11e5-937b-ab3e2d2fe9b5.png)

This may be by design, but a single-line code block cannot be collapsed.
![image](https://cloud.githubusercontent.com/assets/290167/13622492/a6196d10-e564-11e5-8e91-6ec333496578.png)

However, changing the indentation "allows" it.
![image](https://cloud.githubusercontent.com/assets/290167/13622309/63dabd24-e563-11e5-9fe0-7533bd104446.png)

But when I try to collapse it, it does this:
![image](https://cloud.githubusercontent.com/assets/290167/13622313/75507864-e563-11e5-879d-5d7ca2b760d1.png)

If I remove the single-line code block, things look as expected:
![image](https://cloud.githubusercontent.com/assets/290167/13622426/4c13678a-e564-11e5-9160-e578e19ce331.png)

Changing the indentation proves problematic, allowing me to collapse from the end brace:
![image](https://cloud.githubusercontent.com/assets/290167/13622450/6bda47aa-e564-11e5-982a-b9a50f316eb8.png)

Doing the collapse:
![image](https://cloud.githubusercontent.com/assets/290167/13622480/9201c0b6-e564-11e5-80c7-aa3a9c318d45.png)

I'm not sure if the language matters, but this is in a PHP file.

**Comment by aeschli** [comment]
What's currently implemented is a indentation based folding strategy. It purely looks at the indentation of the lines. When a line is followed by one or more line that have more indentation, then this is a foldable region. Empty lines are ignored.
If you look at your screenshot, you see that strategy applied.

The next step will be to make folding strategy customizable, e.g. per language, to e.g. use brackets as beginning and end of a region. https://github.com/Microsoft/vscode/issues/3422 is the issue for that.
