### ISSUE TITLE
telemetry.enableTelemetry does not display "false" when set to false

### ISSUE THREAD

**Issue by cwillhelm** [Microsoft/vscode#38916]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Latest Build

Steps to Reproduce:

1. File -> Preferences -> Settings -> Telemetry set to False

These settings are after a restart of VSCode. 

I'm not sure if it is intended behavior for the GUI to display both "true" and "false" to the user, but I personally find it visually confusing and misleading as to whether the setting is actually turned off or not.

![image](https://user-images.githubusercontent.com/14843838/33108572-ea3fef3c-cf0a-11e7-9579-07faf9fd726c.png)

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@cwillhelm In the settings editor, Left hand side are default settings and the right hand side are settings you override. Since the default value for the setting is `true` LSH shows `true`.

If you have any suggestions, please provide [here](https://github.com/Microsoft/vscode/issues/17847)
