### ISSUE TITLE
Error: Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by ShrivastavAnurag** [Microsoft/vscode#38925]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|0.2.1
react-redux-react-router-snippets|dis|0.3.5
es7-react-js-snippets|dsz|1.2.0
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|1.4.1
react-native-react-redux-snippets-for-es6-es7-version-standard|EQu|1.0.3
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
jsx-beautify|gog|0.0.5
beautify|Hoo|1.1.1
mssql|ms-|1.2.1
node-debug2|ms-|1.19.0
react-beautify|tai|0.3.0
jsx|Twe|0.0.1
vscode-react-native|vsm|0.5.5
(1 theme extensions excluded)

---

Steps to Reproduce:

1. I had updated my VS code to the latest version 5 days ago, now I tried to debug but the debugger is not working.
2. I got an error: Debug adapter process has terminated unexpectedly.

Reproduces without extensions: Yes/No

**Comment by behzad888** [comment]
I have same error on ubuntu 16.0.4

**Comment by behzad888** [comment]
fix it for me. 
You have an error in your project, I think it's happened on uses extensions such as 'Gradle'  in RN.

**Comment by ShrivastavAnurag** [comment]
Resolved.

I was using xDebug. I tried to uninstall xDebug and install it again and it worked for me.

**Comment by mjbvz** [comment]
Ok, closing since it sounds like the issue has been solved
