### ISSUE TITLE
Respond to accessibility concerns properly

### ISSUE THREAD

**Issue by stopthatastronaut** [Microsoft/vscode#38927]
https://github.com/Microsoft/vscode/issues/38898

Closed with "yeah nah"

I literally cannot tell the icon for VS Code apart from the Visual Studio icon. My solution? Uninstalling the hell out of both and switching to JetBrains Rider. Well done. I'm sure that was the intended effect, right?

This is *not* how you respond to accessibility concerns.

**Comment by joaomoreno** [comment]
Icon customization will certainly not happen.

But we can fix the current Windows icon by putting a white border around it. Would that be enough for you?

**Comment by stopthatastronaut** [comment]
Sure, a white border would help. 

It's propping up a fundamental misunderstanding of how human visual systems work, but it'll do. It'll maybe save me 20-30% of the times I accidentally open VS instead of VSCode 

I _could_ just compile a DLL for myself with the orange icon in it, and apply that, but that won't help the other developers like me who happen to have a visual impairment and literally can't tell VS and VSCode apart on our taskbars.

Just give me a properly different icon. 

![vs-vscode](https://user-images.githubusercontent.com/9834169/33154085-f9449be2-d039-11e7-8054-4e379afcfb5b.PNG)

**Comment by stopthatastronaut** [comment]
My little eyedropper utility says the VSCode ison is #007ACC and visual studio's icon is #865FC5

Visually, I can't see a color difference, no matter how hard I try. I can see the little chopped-out bit on the left, but that's not sufficient in a quick window switching moment.

**Comment by joaomoreno** [comment]
> I could just compile a DLL for myself with the orange icon in it, and apply that, but that won't help the other developers like me who happen to have a visual impairment and literally can't tell VS and VSCode apart on our taskbars.

There is actually support for switching an icon without so much trickery: https://www.digitalcitizen.life/how-change-icon-shortcut

And the Taskbar itself is accessible by providing tooltips, and screen reader mode.

Are these two points enough to address the accessibility constraints, since a white border doesn't seem to do so?
