### ISSUE TITLE
Code Installation appears to be corrupt?

### ISSUE THREAD

**Issue by codesign5** [Microsoft/vscode#38922]
I recently added these two lines of code in workspace settings
{
  "editor.fontSize": 14,
  "window.zoomLevel": 1
}

It works fine at the time of vscode opened but when I reload or open it again, the settings crash and I keep getting this error, image attached.

![646caf352b5b2421a0855c84de73b267](https://user-images.githubusercontent.com/6308712/33111453-347d1a16-cf74-11e7-84fa-5a681c6edbe5.png)

I need to again edit the text on workspace settings in order to make it work but again it crash after reopen the vscode.

**Version - 1.18.1**

**Comment by bpasero** [comment]
@codesign5 a full uninstall and reinstall should make this go away.
