### ISSUE TITLE
Go to definition does not always work

### ISSUE THREAD

**Issue by lepkon** [Microsoft/vscode#3893]
If the function is defined in another js file especially when in same directory, Visual Studio doesn't find it which is weird.

**Comment by lepkon** [comment]
I have updated to latest version.

**Comment by egamma** [comment]
Do you have a jsconfig.json defined in your folder, pls see https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson?

Can you add a small example that illustrates the problem.

**Comment by egamma** [comment]
Closing this looks like a duplicate of https://github.com/Microsoft/vscode/issues/3936

**Comment by MohamedMahmoud299** [comment]
hi I have set a jsconfig file and still can't use go to definition
