### ISSUE TITLE
can't add dir  to existing  dir by drag or parse in vscode

### ISSUE THREAD

**Issue by bailihua93** [Microsoft/vscode#38939]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. since vscode can add another dir  to workbench, i can't copy dir to dir existing in workbench as a son dir by dragging or  parse.  the only way is to open  the dir in  the explorer ，then parse。 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
You should be able to drop a folder onto the editor area to open it as before.
