### ISSUE TITLE
 When I use the Path Intellisense plugin

### ISSUE THREAD

**Issue by 513352928** [Microsoft/vscode#38933]
- VSCode Version: VSCodeSetup-x64-1.18.1
- OS Version :windows 8

Steps to Reproduce:

1.  .div{background: url(‘./’)} 
//在css样式表里面的地址不能自动感应，但是在js 里面 src属性使用的时候是正常的
//The Path in the CSS stylesheet is not available，but it can be used good in attribute “src=”

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
