### ISSUE TITLE
Terminal: Mercurial occasionally crashes in the middle of output of certain commands

### ISSUE THREAD

**Issue by MHHenriksen** [Microsoft/vscode#38938]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
live-html-previewer|hdg|0.3.0
rest-client|hum|0.16.1
restructuredtext|lex|43.0.0
Go|luk|0.6.67
MagicPython|mag|1.0.12
hg|mrc|1.2.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.22
qub-msbuild|qub|0.6.3
java|red|0.14.0
vscode-hexdump|sle|1.6.0
robotframework|viv|0.1.3
vscode-java-debug|vsc|0.3.1

---

Mercurial occasionally crashes in the middle of output of certain commands, especially log and diff, with the following error:
```
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
** Mercurial Distributed SCM (version 4.3.1)
** Extensions loaded: purge, rebase, record, strip, extdiff, highlight, shelve, largefiles, share, show, convert, amend
Traceback (most recent call last):
  File "hg", line 45, in <module>
  File "mercurial\dispatch.pyc", line 81, in run
  File "mercurial\dispatch.pyc", line 185, in dispatch
  File "mercurial\ui.pyc", line 914, in flush
  File "mercurial\windows.pyc", line 180, in flush
ValueError: I/O operation on closed file
```
I have not reported this to the Mercurial bugtracker as the error suggests, as it seems more likely to me to be caused by the vscode integrated terminal closing stdout too soon. I never see this error in a plain Powershell terminal.

Steps to Reproduce:

1. Have Mercurial installed (I'm using 4.3.1)
2. Open in VS Code a Mercurial repo with a little history to it, or some working dir changes
3. Open a Terminal tab (I use Powershell)
4. run `hg diff` and/or `hg log` (it may take a few tries). `hg help config` can also trigger it rarely, but it seems to have a better chance of failing the longer the command takes to print the results.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Please create this against the powershell ext repo https://github.com/PowerShell/vscode-powershell

**Comment by MHHenriksen** [comment]
Ok, I will, thanks!
