### ISSUE TITLE
PHP snippet "<?php" error

### ISSUE THREAD

**Issue by sasha6806** [Microsoft/vscode#38931]
- VSCode Version: 1.18.1, 1.17 and early
- OS Version: windows 10 pro

Steps to Reproduce:

1. If I want to call a php snippet "<?php" by typing "ph+TAB" at beginning of a .php file, it will appear 
`ph<?php` instead of `<?php`
2. as the same, when I type "php+TAB" with result of `php<?php` instead  of `<?php`

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
I tried to reproduce it, but there is not `<?php` snippet available when I start typing with `php`.
![image](https://user-images.githubusercontent.com/17984549/33116620-c4b38f98-cf65-11e7-9561-5526cbe57802.png)
When I start with `<?` then I can choose it without any issues.
![image](https://user-images.githubusercontent.com/17984549/33116614-bd87e4a8-cf65-11e7-9299-17c1b3f11121.png)

**Comment by Lantaros** [comment]
I'm working on this issue

**Comment by roblourens** [comment]
I also don't see it - it must be coming from an extension. If you can figure out which one, please file an issue on them.
