### ISSUE TITLE
 vs code  shows the incorrect branch of my project

### ISSUE THREAD

**Issue by nzwzc** [Microsoft/vscode#38937]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.My editor, there are two different root directory file, I call them A and b. A file on the develop branch, B on the master. When I switch on the terminal to A file, I modified B file in one file. Then from the sidebar of the pilot into I modified the file, the lower left corner shows the master branch, should show the develop branch of A file. When I remove the file B, still shows the master branch. No matter how to use the * git checkout develop * or show master
 **我的编辑器有两个不同根目录文件,我叫他们a和b. a文件在develop分支上,b在master上.当我在终端上切换到a文件时,我修改b文件的中某一个文件.然后从侧边栏的调试点进我修改的那个文件,此时左下角显示的master分支,应该显示的是a文件的分支.当我移除b文件时,任然显示master分支.无论怎么使用*git checkout  develop*还是显示master**
2.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Sorry, but I really can't understand this. Please try to get an English speaker to file the issue for you.
