### ISSUE TITLE
Renaming file in VSCode does not rename references in source

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#38936]
![image](https://user-images.githubusercontent.com/512816/33118585-90f83d00-cf6c-11e7-93a6-16b122837620.png)

Typescript app.

VSCode details:

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
ng-template|Ang|0.1.7
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
ionic3-vs-ionView-snippets|dan|1.0.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
ionic-preview|ion|0.0.15
cordova-dev-essentials|jew|0.0.1
ionic2-vscode|jgw|1.0.0
Angular2|joh|2.11.2
ionic-extension-pack|loi|0.0.1
debugger-for-chrome|msj|3.5.0
rxjs-snippets|pko|0.0.2
vscode-icons|rob|7.18.1
autoimport|ste|1.5.3
ionic2|Tha|3.0.1
sort-lines|Tyr|1.3.0
Angular2|UVB|0.4.1
cordova-tools|vsm|1.3.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by leegee** [comment]
However, Code does beautifully make sure my open editor reflects the change in file name!

**Comment by joaomoreno** [comment]
This is beyond Code's scope. I would file this issue in TypeScript.
