### ISSUE TITLE
It is possible to getConfiguration('editor') in "vscode/src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts" file?

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#38943]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Version: 1709 Build: 16299.64

Steps to Reproduce:

1. Go to contribution instructions and run from source

I want to suggest following option to VSCode to make multiply cursors with same style (without transparency):

```
'editor.sameCursorStyle': {
	'type': 'boolean',
	'default': EDITOR_DEFAULTS.contribInfo.sameCursorStyle,
	'description': nls.localize('sameCursorStyle', "If true then multiply cursors will have same style")
},
```

If this option will be `true` then `this._domNode.setClassName('cursor secondary')` in `"vscode/src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts"` [(line 69)](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/viewCursors/viewCursor.ts#L68-L69) does not set `secondary` class.

But when I trying to get `editor` config in `viewCursor.ts` with:

```
import { workspace } from 'vscode';
const sameCursorStyle = workspace.getConfiguration('editor').get<boolean>('sameCursorStyle');
```

on `yarn run watch` I got error in VSCode Defeloper Tools:

```
Error: Cannot find module 'vscode'
```

![1167edda8c](https://user-images.githubusercontent.com/20873402/33123454-1b522e72-cf2f-11e7-97ab-fc713ac3a198.png)

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
In viewCursor, please access `this._context.configuration.editor` for editor configuration.
