### ISSUE TITLE
Add Folder To Workspace crashes code

### ISSUE THREAD

**Issue by teterovic** [Microsoft/vscode#38942]
- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: MacOs High Sierra

Steps to Reproduce:

1. Click on Open
2. While the Open dialog is still open, click on the File menu and select "Add Folder To Workspace"
![image](https://user-images.githubusercontent.com/7413906/33121132-31feaade-cf74-11e7-8dce-53f0bce8d03c.png)

VS Code becomes nonresponsible will crash soon after you close the open dialog and click on something
![image](https://user-images.githubusercontent.com/7413906/33121051-134e5a3a-cf74-11e7-8f44-98eb250a3093.png)

**Comment by bpasero** [comment]
@teterovic I might have fixed this for insiders, can you try to reproduce there: 
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by teterovic** [comment]
@bpasero Seems to be fixed 👍
