### ISSUE TITLE
Resource-scoped FormattingEditProvider 

### ISSUE THREAD

**Issue by azz** [Microsoft/vscode#38945]
When implementing multi-root functionality in to the [Prettier VSCode](https://github.com/prettier/prettier-vscode) extension, we've encountered a limitation of the current API. Prettier supports a growing amount of languages, so rather than register formatters for all the languages it supports, we have a setting `"prettier.disableLanguages"`, whose value is an array of language IDs, allowing other extensions to be used for specific languages.

In a multi-root scenario, I don't believe there's currently a way to only register a formatter based on the value of this setting, since the extension activation is too early, upon formatting is too late, and `"scope": "window"` does not apply.

A solution would be to allow a predicate function to be passed to `register*FormattingEditProvider`, such that we can do:

```ts
languages.registerDocumentFormattingEditProvider(
  ["typescript", "javascript"],
  editProvider,
  (doc: TextDocument) => {
    const { disableLanguages } = workspace.getConfiguration('prettier', doc.uri);
    return !disableLanguages.includes(doc.languageId);
  },
)
```

This would be backwards compatible.

**Comment by azz** [comment]
Looking through the implementation, if `[]` is returned from the provider, it appears to skip to the next formatter. Maybe this is just a sentence missing from the docs.

https://github.com/Microsoft/vscode/blob/d8debf468b7ddaa474d192201c4609d73316172a/src/vs/editor/contrib/format/format.ts#L61-L70

**Comment by azz** [comment]
Returning `[]` doesn't work as I thought it might, but throwing an error seems to have the desired effect of skipping the formatter. Is that an API that can be relied upon?

**Comment by jrieken** [comment]
> In a multi-root scenario, I don't believe there's currently a way to only register a formatter based on the value of this setting, since the extension activation is too early,

What do you mean with that? Are you saying the extension has activated *before* the configuration value is available?

**Comment by azz** [comment]
Not before the config is available, but before there's any way to determine _which_ workspace folder is active.

```ts
export function activate(context: ExtensionContext) {
  workspace.getConfiguration('prettier', ???);
}
```

**Comment by jrieken** [comment]
Ok, if you want to filter/limit this to a specific workspace folder then you should use the `DocumentFilter` and its `pattern` property.

**Comment by azz** [comment]
Unless I'm missing something, that doesn't help. You need to get the resource level configuration in order to make that distinction, which you cannot do upon extension activation (file isn't in `ExtensionContext`)

**Comment by jrieken** [comment]
You should be able to get the configuration per workspace folder upfront, check the `WorkspaceConfiguration#inspect` function

**Comment by azz** [comment]
It's possible by doing:

* On activate, for each `workspace.workspaceFolders`, do:
  - `workspace.getConfiguration("prettier", folder.uri)`
  - `registerDocumentFormattingEditProvider`
* Listen to `workspace.onDidChangeWorkspaceFolders`:
  - for each `removed`, dispose the provider
  - for each `added`, `registerDocumentFormattingEditProvider`

But we'd need a `Map` for those subscriptions and it'd be a bit messy to implement.

What currently seems to work is throwing `Error` from `provideDocumentFormattingEdit`. It's much cleaner an implementation. Will this API be maintained?

```ts
provideDocumentFormattingEdits(document: TextDocument): Promise<TextEdit[]> {
    if (this._skipFormattingDocument(document)) {
        throw new Error("Skip this file!");
    }
    return this._provideEdits(document, {});
}
```

**Comment by jrieken** [comment]
> What currently seems to work is throwing Error from provideDocumentFormattingEdit

You can also just return `undefined`. The disadvantage of the solution is that as soon as a provider is registered the editor content menu show the 'Format document' command given a wrong impression to users. Not sure what's messy to implement when using a map. Sounds natural to store something about workspaces when feature is specific to a workspace

**Comment by azz** [comment]
> feature is specific to a workspace

The feature doesn't really have anything to do with workspaces. Before multi-root, workspaces wouldn't even fit into the question. But when supporting multi-root we now need to keep more state inside the extension, which is unfortunate.

How does the API suggested in the original post sound? It would actually provide a greater level of flexibility because we would look at (e.g. `.prettierignore`) files and not show the "Format Document" command if a files is included in it.

**Comment by azz** [comment]
More powerful idea: Add a `predicate` function to `LanguageFilter`.

**Comment by azz** [comment]
I implemented this here: https://github.com/azz/vscode/commit/0c788b5082d91aea63e001cc229a88b4f775da74


The implementation on the extension side would look like:
```ts
function disableLanguagesPredicate(uri: Uri): boolean {
  const { disableLanguages } = workspace.getConfiguration('prettier', uri);
  return !disableLanguages.includes(doc.languageId);
};

languages.registerDocumentFormattingEditProvider(
  ["typescript", "javascript"].map(language => ({
    language,
    predicate: disableLanguagesPredicate
  }),
  editProvider
);
```

@jrieken What are your thoughts on this API? Should I open a PR?

**Comment by jrieken** [comment]
> How does the API suggested in the original post sound?

A document selector must execute synchronously on the main process, no forgein code can be executed esp. not when it sits in a different process.

**Comment by azz** [comment]
Ah, of course. Scratch that then...

**Comment by jrieken** [comment]
Closing this with the recommendation to return `undefined` when a provider isn't 'responsible' for a certain resource or to use the workspace-aware file pattern support we have.
