### ISSUE TITLE
VS Code sources are linked against wrong `lib.d.ts`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#38944]
Seen on `master`, macOS.

1. Using Insiders, open https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/dom.ts#L21
2. Go to definition of `removeChild`

Notice how you end up in `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.d.ts`.

We somehow don't have a `lib.d.ts` in our source tree... not do we have `dom.d.ts`... has this always been this way?

This obviously needs fixing since our sources don't flow with our release.

**Comment by joaomoreno** [comment]
The build is picking it up from the right place: https://github.com/Microsoft/vscode/blob/master/build/lib/compilation.ts#L75

So this just seems like it's the language service that's doing the wrong thing!

**Comment by mjbvz** [comment]
Yes, the lib/dom typings file come from TypeScript. If you use the workspace version of TS, we pick up the local versions of these files: `/Users/matb/projects/vscode/node_modules/typescript/lib/lib.d.ts` for example

**Comment by joaomoreno** [comment]
@mjbvz So... shouldn't we fix the language service for editing our sources? Both pillars should do exactly the same, right?

@isidorn Hit one issue in which the definitions were different in a DOM API. The build would compile fine but VS Code would complain about the error (or vice versa).

**Comment by mjbvz** [comment]
This is the designed behavior since the TS team has decided to ship these d.ts files as part of TypeScript proper. The fix is to use the workspace version of TS when in the vscode project. This will ensure that we pick up the right `lib.d.ts` files in the editor and during compile

**Comment by joaomoreno** [comment]
@mjbvz And how can we do that?

**Comment by mjbvz** [comment]
Just run the `Select TypeScript version` command or click on the TS version number in the status bar

**Comment by joaomoreno** [comment]
Oh, I see!

Shouldn't this be the default for our workspace? Can you check in some setting which makes it that all of us use the workspace version by default?

**Comment by mjbvz** [comment]
No, we cannot load this version of TypeScript automatically for security reasons. That's why we still require a manual `select typescript version` step

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode: Be aware that the TypeScript version (as well as the corresponding `lib.d.ts`) in VS Code's language service will not match the build language service. So if you see errors in Code but not in the build, or vice-versa, please remember this.
