### ISSUE TITLE
documentation is not available offline

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38949]
VS Code 1.18.1
OS Windows 7

The program's documentation, available via 'Help > Documentation', takes you to
https://code.visualstudio.com/docs#vscode

As the program has many aspects which differ from use patterns established by over 20 years of IDEs, the documentation should be available offline and updated as with any other extension.

**Comment by iulia4radu** [comment]
I tried to open a new project and I receive the note that all sources I need are off lines

**Comment by draeger-charles-wilson** [comment]
Being informed that you have everything you need and having what you need are two distinctly different things.

**Comment by joaomoreno** [comment]
Being such a high velocity project, we want to keep our docs as fresh as possible, so they are available online only. If you want an offline copy, I suggest to use something like [HTTrack](https://www.httrack.com/) to download them.
