### ISSUE TITLE
error TS5023:Build:Unknown compiler option '-'

### ISSUE THREAD

**Issue by laultman** [Microsoft/vscode#38955]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
csharp|ms-|1.13.1
csharp2ts|raf|0.0.19

---
When creating a TypeScript project following the guide [here
](https://code.visualstudio.com/Docs/languages/typescript) the Tasks: Run Build Tasks... results in and error TS5023:Build:Unknown compiler option '-'

Steps to Reproduce:
The problem occurs when the source code folder path contains ' - ' character embedded surrounded by spaces in the path string. My default path for a OneDrive for Business path. 
"C:\Users\LarryA\OneDrive - Intact Partners Inc\VSCprojects\tsconfig.json" 

This fails: "C:\Users\LarryA\OneDrive - Intact Partners Inc\VSCprojects\tsconfig.json" 
This passes: "C:\Users\LarryA\OneDrive-IntactPartnersInc\VSCprojects\tsconfig.json"

1. Use the folder configurations above.
2. Follow the guide to create the HelloWorld project ( https://code.visualstudio.com/Docs/languages/typescript )
3. Execute the Task: Run Build Tasks... as directed. The terminal window reports the error.

Reproduces without extensions: Yes/No

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/32400
