### ISSUE TITLE
Bugs on terminal

### ISSUE THREAD

**Issue by am54ful** [Microsoft/vscode#38953]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---
Laravel Mix not showing build successful when using bash terminal. Sometimes in appear and sometimes it does not appear

Steps to Reproduce:

1. Install Laravel
2. Install NPM
3. npm run watch

**Comment by Tyriar** [comment]
Can you provide a screenshot of the issue? Also what specifically are you referring to when you say "bash terminal"?
