### ISSUE TITLE
How can I get the little color icon next to color names in my custom language?

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#38959]
Writing an LSP extension for our CSS preprocessor, I notice that when I get a color completion from CSS (I proxy the CSS service through mine) I get the little color indicator next to the value, but in the file itself there is no indicator (see pic).

![image](https://user-images.githubusercontent.com/1898725/33132786-493bed7c-cfa3-11e7-93be-5104cee1f37f.png)

I haven't found anything in the LS Protocol or in TM grammars to make this possible in my language.
Is it at all possible to get the color icon through an extension / grammar, or is it a special VSCode feature for CSS only?

- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
It's a proposed protocol extension. See
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.colorProvider.proposed.md
Check out the [css client](https://github.com/Microsoft/vscode/blob/d691f07af7d2745b7f2147a4f052d35ae9bc4b04/extensions/css/client/src/cssMain.ts#L56) and [server](https://github.com/Microsoft/vscode/blob/d691f07af7d2745b7f2147a4f052d35ae9bc4b04/extensions/css/server/src/cssServerMain.ts#L207) on how to use it.

**Comment by tempit** [comment]
Is it possible the vscode.d.ts version that is downloaded doesn't have these features? 
I can't find languages.registerColorProvider, and get multiple errors from vscode-langugeclient:

node_modules/vscode-languageclient/lib/client.d.ts(1,139): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'ProviderResult'.
node_modules/vscode-languageclient/lib/client.d.ts(1,272): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/client.d.ts(1,648): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/client.d.ts(1,679): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'TextDocumentWillSaveEvent'.
node_modules/vscode-languageclient/lib/client.d.ts(1,706): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'WorkspaceFolder'.
node_modules/vscode-languageclient/lib/codeConverter.d.ts(11,46): error TS2694: Namespace 'vscode' has no exported member 'TextDocumentWillSaveEvent'.
node_modules/vscode-languageclient/lib/codeConverter.d.ts(36,31): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(18,57): error TS2694: Namespace 'vscode' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(21,122): error TS2694: Namespace 'vscode' has no exported member 'CompletionList'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(66,49): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(67,53): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(69,72): error TS2694: Namespace 'vscode' has no exported member 'DocumentLink'.
node_modules/vscode-languageclient/lib/workspaceFolders.proposed.d.ts(1,10): error TS2305: Module '"/home/wix/projects/stylable-intelligence/packages/client/node_modules/vscode/vscode"' has no exported member 'WorkspaceFoldersChangeEvent'.

**Comment by aeschli** [comment]
It's in 1.18. Make sure that you have
```json
"engines": {
    "vscode": "1.18.x"
  },
```
in your extension's `package.json`and do a `npm install` to get `vscode.d.ts` updated.

**Comment by tempit** [comment]
Thanks. My engine was outdated.
You can close #39036  as well, it's the same issue.
