### ISSUE TITLE
Workspace exclusions break find in files

### ISSUE THREAD

**Issue by jswigart** [Microsoft/vscode#38958]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
moonsharp-debug|xan|1.8.3

When using a workspace filter, find in files does not work.

I had this set up in my workspace to exclude certain files from the workspace.

{
    "files.exclude": {
        "*/**/**.meta": true
      }
}

and when this is in place, the search functionality is broken, with the following error message dropped down under the search

![screenshot 2017-11-22 08 18 55](https://user-images.githubusercontent.com/4065267/33132083-235c0dd4-cf5e-11e7-887d-2ebefe597d1d.png)

---

Steps to Reproduce:

1. paste the above exclude lines in your workspace settings file
2. attempt to do a find in files(it does it with and without the pictured "include files" field filled in)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
The `**.meta` part is technically not valid - it's allowed by some parts of vscode but search is more strict. `*.meta` will work.

**Comment by jswigart** [comment]
*.meta doesn't recursively ignore that file extension like the expression I was using does

**Comment by roblourens** [comment]
`**/*.meta` is ok. `**/**.meta` is not.
