### ISSUE TITLE
Feature request: Selection TreeView style for Source Control

### ISSUE THREAD

**Issue by nunesvictor** [Microsoft/vscode#38956]
- VSCode Version: 1.18.1
- OS Version: Ubuntu Linux 17.10 x86_64

I would be very nice to have an optional way to stage changes on Source Control. The current way (add a file by selecting them and clicking in a + sign) can be very tricky when working with multiple files and folders. A Selection TreeView could be a little more intuitive, I think.

Image exemplifying the functionality:
![screenshot-2017-11-22 captura de tela de 2017-11-22 11-00-07 png imagem png 3840 x 1080 pixels](https://user-images.githubusercontent.com/5093514/33131345-ff524284-cf74-11e7-9eed-22379b24d7f9.png)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/14582
