### ISSUE TITLE
Ctrl+P not mapped to print

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#38950]
VS Code 1.18.1
OS Windows 7

Unlike every other mainstream Windows and Macintosh application release over the past 20 years, Ctrl+P is not mapped to Print capability. Even Windows regedit uses this key mapping.

**Comment by usernamehw** [comment]
1. Print from vscode is not even supported https://github.com/Microsoft/vscode/issues/5953
2. You have the ability to remap keybindings
