### ISSUE TITLE
Touch: regressions from touch refactoring

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38961]
There are a couple of places where touch no longer seems to work:
* to resize views by touching on sashes
* when clicking on status bar entries
* clicking on view headers to collapse/expand
* the "..." in the search view to expand details
* any input field to move focus into the input field

**Comment by isidorn** [comment]
good catches investigating

**Comment by bpasero** [comment]
@isidorn did you mean to close this? from the change it is not so obvious how it could fix the other areas I reported

**Comment by isidorn** [comment]
@bpasero yes. There are 2 commits attached to this issue

**Comment by bpasero** [comment]
@isidorn ok thanks

**Comment by bpasero** [comment]
I cannot resize split-views with touch but not sure if that is a regression.

**Comment by isidorn** [comment]
@bpasero as in the other touch issue I'll give it another spin next week with the touch laptop, not critical imho
