### ISSUE TITLE
Search in Workspace

### ISSUE THREAD

**Issue by mcuneyda** [Microsoft/vscode#38967]
- VSCode Version: 1.18.1
- OS Version: Windows 10

can i search in workspace? like visual Studio 2017

**Comment by roblourens** [comment]
Yes, see the magnifying glass icon on the left side or ctrl+shift+F.

**Comment by mcuneyda** [comment]
no, i'm not want like this. i just want press one key and search to file.

like - > https://im3.ezgif.com/tmp/ezgif-3-e9d29ac091.gif

(sorry my bad english)

**Comment by roblourens** [comment]
I see a 404 message for that gif.
