### ISSUE TITLE
Use typescript namespace in JSDoc comments

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#38964]
When I install npm package, VS Code nicely shows typescript definitions in javascript file:
![typescript definitions inside js](https://user-images.githubusercontent.com/3494407/33133824-4523ffd6-cf9e-11e7-8629-3641e76e88c7.png)

I would expect, that I will be able to use these definitions in JSDoc comments:

```javascript
/**
 * compiles application javascripts using specified bundler, either browserify or watchify
 * @param {browserify.BrowserifyObject} bundler
 * @param {string} bundleFileName - output javascript file
 */
function compileJs(bundler, bundleFileName) {
```

But the parameter type is still reported as any:
![image](https://user-images.githubusercontent.com/3494407/33133976-c7ede3f0-cf9e-11e7-87ea-bd543d814bde.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20281
