### ISSUE TITLE
Change debugging tab to be tasks tab

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#38969]
I run a lot of tasks in VSCode. I just can't see why there is such a big difference between running a debug process and a task. And maybe it is just me, but I think pressing <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and then select `Run Task` and then selecting the running task, is just too much.

For optimal experience, I suggest the following:

* A tasks should have a **play** button.
* A background task should have a **play** and **stop** button
* A debug tasks should **play**, **stop**, **resume**, **step into**, **step over**, **step out**, **restart**, **disconnect**.
* A task can depend on an another task.
* Pressing **start** should start the tasks and all its dependencies.
* Pressing **stop** should stop the tasks and all its dependencies.
* Being able to run multiple tasks.

When I debug task begins, the "normal" sidebar for debugging is overlayed over this task list.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/28235.
