### ISSUE TITLE
Open Editors: opening an editor refreshes view 2-3 times

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#38960]
Steps to Reproduce:

1. put a breakpoint into `treeImpl.refresh()`
2. open an editor

=> the open editors viewer refreshes 2-3 times for each editor opened

**Comment by isidorn** [comment]
I plan to rewrite the open editors to the list so hopefully that will tackle this

**Comment by isidorn** [comment]
With the latest code, the open editors views gets refreshed only once for an editor open. And we do not refresh the whole view, but just the editor that changed
