### ISSUE TITLE
emmet not providing suggestions

### ISSUE THREAD

**Issue by rwmb** [Microsoft/vscode#38973]
Emmet stopped working for me after the last update. I tried changing configurations but nothing worked. When I type Emmet Expand Abbreviation in the command palette it works, but the suggestions are not showing like they usually do in the stable version as shown bellow. Even deleting the folders in appdata, user and install dir did not work for me.

- VSCode Version: 1.19.0-insiders
- OS Version: win10

Steps to Reproduce:
clean install of code-insiders, no configuration changes:

1.type anything that would normally popup as emmet suggestion in html file
![emmet-not-working](https://user-images.githubusercontent.com/20707521/33141512-4b7bf20a-cfab-11e7-9a1a-b78bb3cac36f.gif)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Thanks for reporting @rwmb!

This occurs when there is no parent html node when trying to expand emmet abbreviations.
A recent refactoring caused the issue.
I have pushed in a fix.

The next Insiders build that will be out on Monday (27th Nov) will have the fix.

**Comment by rwmb** [comment]
Amazing! Thanks for the quick solution and response @ramya-rao-a !

**Comment by ramya-rao-a** [comment]
No problem at all @rwmb 
I really appreciate you and others on Insiders using emmet.
I don't use emmet much at all, and having folks like you catch me when I make mistakes like this is very helpful.

Happy Coding!
