### ISSUE TITLE
Spinner does not stop for a custom typescript watch ($tsc-watch) task

### ISSUE THREAD

**Issue by guidojo** [Microsoft/vscode#38970]
**Explanation:**
I want to have a custom typescript watch task for my project. This is because I want to use specific options and a specific typescript compiler. My example below is a simplified version of the problem, so it easy to reproduce.
The problem is that the problem matcher does no recognize when the task is done with compiling. This worked perfectly for the `0.1.0` version of the tasks "engine". I want to switch to the new tasks engine, because I like the new features you are implementing, but this issue keeps me from doing that.

**Situation:**
- VSCode Version: `1.18.1`
- OS Version: `Linux`

**Steps to Reproduce:**
Create a `tasks.json` with the following content:
```json
{
  "version": "2.0.0",
  "tasks": [
      {
          "label": "typescript",
          "type": "shell",
          "command": "./node_modules/.bin/tsc",
          "args": [
            "--watch",
            "-p",
            "./tsconfig.json"
          ],
          "problemMatcher": ["$tsc-watch"],
          "group": {
            "kind": "build",
            "isDefault": true
        }
      }
  ]
}
```

Below is the old `tasks.json` that does work:
```json
{
  "version": "0.1.0",
  "tasks": [
    {
      "taskName": "Watch client",
      "command": "./node_modules/.bin/tsc",
      "isBuildCommand": true,
      "isShellCommand": true,
      "args": [
        "-w",
        "-p",
        "./tsconfig.json"
      ],
      "showOutput": "silent",
      "isBackground": true,
      "problemMatcher": "$tsc-watch"
    }
  ]
}
```

**Comment by dbaeumer** [comment]
The task 2.0.0 version is missing the `"isBackground": true` setting which is still necessary.

**Comment by guidojo** [comment]
@dbaeumer thank you! I feel stupid for not seeing this in the documentation
