### ISSUE TITLE
VS Code Software Updates default to Program Files on Windows

### ISSUE THREAD

**Issue by blusk0** [Microsoft/vscode#38974]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-simpler-icons|dav|1.5.2
angular-extension-pack|dog|0.9.0
githistory|don|0.2.3
vscode-generate-getter-setter|DSK|0.4.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.23
prettier-vscode|esb|0.26.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.1.4
docthis|joe|0.6.0
Angular2|joh|2.11.2
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.3
Angular-BeastCode|Mik|5.0.17
mssql|ms-|1.2.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
typescript-javascript-grammar|ms-|0.0.24
debugger-for-chrome|msj|3.5.0
material-icon-theme|PKi|3.0.0
tsimporter|pmn|1.2.14
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Install Code to directory other than Program Files on Windows
2. Install Code software update from within the software

Reproduces without extensions: Yes

This is not a critical issue, but one that has persisted for a long time and I just wanted to make a note of it. I work somewhere where group policy restrictions on the Program Files and Program Files (x86) folders cause strange behavior from VS Code. I work around this by installing code directly to my user profile. Whenever I download a software update from within the application, it installs automatically to Program Files.

**Comment by joaomoreno** [comment]
That is definitely strange. In my machine, the update hits the exact same folder as before.

Can you try to fully uninstall, reinstall Code on a different path than the default and see whether the following update would still misbehave?
