### ISSUE TITLE
Search Excluding `./src` with "Use Exclude Settings" selected

### ISSUE THREAD

**Issue by kenhowardpdx** [Microsoft/vscode#38979]
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. open project with a `src` folder in root
2. go to search pane
3. ensure "Use Exclude Settings" is selected
4. search for camelCase symbol in `./src` folder

Reproduces without extensions: Yes

![search-bug](https://user-images.githubusercontent.com/1892667/33146213-2b1fa25a-cf78-11e7-9c15-338b676bf063.gif)

**Comment by roblourens** [comment]
Your results are in .js files, and it looks like it just doesn't work when "use exclude settings" is selected, and sure enough the output pane shows an exclusion for `**/*.js`. I don't see you trying it with "use exclude settings" + `src` so I don't know that `src` vs `./src` makes a difference.

There must be an exclude setting in your user or workspace settings for `**/*.js`.

**Comment by kenhowardpdx** [comment]
@roblourens I do have this:
```
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.js": {"when": "$(basename).ts"}
    },
```

**Comment by kenhowardpdx** [comment]
![search-bug-2](https://user-images.githubusercontent.com/1892667/33155792-59ed8fe0-cfa8-11e7-9f79-a2f2232cb1ca.gif)

**Comment by roblourens** [comment]
Oh, I do lose the 'when' clauses when searching with `./`. Thanks for the report!
