### ISSUE TITLE
Debugger crashes when stepping over ES6 destructing statements executed by Node

### ISSUE THREAD

**Issue by alenny** [Microsoft/vscode#38978]
- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Write the following ES6 code (this code can run successfully)
```
const searchMatrix = function (matrix, target) {
    if (!matrix || matrix.length === 0 || matrix[0].length === 0) {
        return false;
    }
    return matrixBinarySearch(matrix, target, 0, 0, matrix.length - 1, matrix[0].length - 1);
};
function matrixBinarySearch(matrix, target, fromRow, fromCol, toRow, toCol) {
    if (fromRow > toRow || fromCol > toCol) {
        return false;
    }
    let midRow = (fromRow + toRow) >> 1;
    let midCol = (fromCol + toCol) >> 1;
    let midValue = matrix[midRow][midCol];
    if (midValue === target) {
        return true;
    }
    if (target > midValue) {
        let [nextFromRow, nextFromCol] = midCol === matrix[0].length - 1 ? [midRow + 1, 0] : [midRow, midCol + 1];
        return matrixBinarySearch(matrix, target, nextFromRow, nextFromCol, toRow, toCol);
    }
    // if target < midValue
    let nextToRow, nextToCol;
    if (midCol === 0) {
        [nextToRow, nextToCol] = [midRow - 1, matrix[0].length - 1];
    } else {
        [nextToRow, nextToCol] = [midRow, midCol - 1];
    }
    return matrixBinarySearch(matrix, target, fromRow, fromCol, nextToRow, nextToCol);
}
let ret = searchMatrix([[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 50]], 3);

```
2. Set a Breakpoint at or before the line: [nextToRow, nextToCol] = [midRow, midCol - 1]; (around line 26)
3. Press F5 to start debugging
4. Press F10 to keep stepping over the breakpoint. Then the Debugger should crash and you can the following error information in Terminal:

> [nextToRow, nextToCol] = [midRow, midCol - 1];
>          ^
> TypeError: Cannot read property 'next' of undefined
>     at matrixBinarySearch (C:\github\leetcode\src\index.js:29:10)
>     at searchMatrix (C:\github\leetcode\src\index.js:7:12)
>     at Object.<anonymous> (C:\github\leetcode\src\index.js:34:11)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
>     at ontimeout (timers.js:386:14)

Reproduces without extensions: Yes

**Comment by eamodio** [comment]
I've seen this same behavior if you are debugging and step over it (it works fine when run).

```ts
// This code works
for (const e of reposToDelete) {
    this._repositoryTree.delete(e[1]);
    e[0].dispose();
}

// This code crashes vscode
for (const [r, k] of reposToDelete) {
    this._repositoryTree.delete(k);
    r.dispose();
}
```

**Comment by roblourens** [comment]
Both work for me in Node 8.9. Is it an older node version? Can you try in chrome devtools?
