### ISSUE TITLE
Using import in index.d.ts breaks IntelliSense in .js files' JSDoc

### ISSUE THREAD

**Issue by liqwid** [Microsoft/vscode#38980]
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: Os X 10.13.1 ( High Sierra )

Steps to Reproduce:

1. In an empty project create two files along each other just as in a gist
https://gist.github.com/liqwid/10685a93415f165be548cdd5eab47795
2. IntelliSense is working inside JSDoc in index.js
3. Add any import statement to index.d.ts like `import { resolve } from 'path'`
4. IntelliSense inside JSDoc in index.js stops working

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` at the root of your project with the contents:

```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This will ensure that both the `*.d.ts` and `*.js` file are included in the same javascript project
