### ISSUE TITLE
Use .gitignore to hide files in the explorer panel

### ISSUE THREAD

**Issue by TaQk** [Microsoft/vscode#38984]
Hello!

It is a little bit burdensome when my project has a lot of unnecessary (from programmers perspective) files which are displayed on the file tree.
If I understand well the only way to hide them is explained here -
[link to stackoverflow](https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code
)

It will be nice if we could automatically hide files and folders based on .gitignore in the project. 

What do you think about this idea?

Regards

**Comment by usernamehw** [comment]
A duplicate of https://github.com/Microsoft/vscode/issues/38878
