### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by mladenbruck** [Microsoft/vscode#38989]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.2
vscode-arduino|vsc|0.2.10

This is error compiling suddenly start to show:

c:\users\mlade\appdata\local\arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2\bin\../lib/gcc/avr/4.9.2/../../../../avr/bin/ar.exe: unable to rename 'core\core.a'; reason: File exists

---

Steps to Reproduce:

1. Don't know how to reproduce....
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Hard to figure this one out without repro steps. Closing due to lack of information.
