### ISSUE TITLE
[loc]Request to add Lithuania language to VS Code

### ISSUE THREAD

**Issue by slowas** [Microsoft/vscode#38986]
Hello, 

I noticed that more and more people are programming in our country. Therefore, I think it's very difficult for beginners especially (for small developers) to learn how to use the editor. I would like to contribute to the VSCode project and help my country's programmers.

My transifex profile:

https://www.transifex.com/user/profile/slowas/

**Comment by maxibanki** [comment]
Please read the guide [how to request a new UI language](https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project).

**Comment by EmilisM** [comment]
Willing to participate in translation process.

https://www.transifex.com/user/profile/EmilisM/

**Comment by Jusys** [comment]
I'm waiting for this for 7 months now :/

![clipboard01](https://user-images.githubusercontent.com/30110941/34073409-f098d150-e2a1-11e7-969e-b34a7d4569f7.jpg)

**Comment by EmilisM** [comment]
Well thats because more contributors need to specify/show interest in contributing to this issue thats why it doesnt catch attention, there is specified in the guidelines that it needs to catch more attention

**Comment by thekWzon** [comment]
It`s needed.

**Comment by Jusys** [comment]
https://www.transifex.com/user/profile/MartynasJs/

**Comment by danyeh** [comment]
Thank you for showing interest to contribute! Lithuania (lt) has been enabled in Transifex now.
