### ISSUE TITLE
CompletionItem can't replace text left and right of the cursor

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#38982]
While trying to clarify https://github.com/Microsoft/language-server-protocol/issues/264 I discovered that a completion item can't repace text left and right of the cursor

Extension code:

```
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    vscode.languages.registerCompletionItemProvider('plaintext', {
        provideCompletionItems: (textDocument, position) => {
            if (position.line !== 0 || position.character !== 1) {
                return undefined;
            }
            const result: vscode.CompletionItem[] = [];
            let item: vscode.CompletionItem = new vscode.CompletionItem('wxyz');
            item.insertText = 'wxyz';
            item.range = new vscode.Range(0, 0, 0, 4);
            result.push(item)
            return result;
        }
    })

}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

- text file with content
```
a<cursor>bcd
```

Open code complete. No entry is listed.

**Comment by dbaeumer** [comment]
I played a little and the problem is that the text start with a and the replacement text starts with w (which is !== a). If the text is `w<cursor>bcd`.

**Comment by dbaeumer** [comment]
I understand why it is filtered (it doesn't score I guess) but I am not sure that this is intentional.

**Comment by tempit** [comment]
As someone writing an LSP extension, I think this is the proper behavior. 
If I wanted to insert 'wxyz' between 'a' and 'bcd' I would send a TextEdit with range (0,1,0,5), not (0,0,0,4).
If sending a range that overlaps a string, the string should match the relevant part of the replacement text, or be filtered out (or way down), IMO.

**Comment by jrieken** [comment]
Yes, nothing is shown because the suggestion select `a` to replace but it doesn't set a filter text. That means we'll compare `a` with `w` which isn't a match. Either set a filter text or use this sample `w<cursor>bcd`.

<img width="214" alt="screen shot 2017-12-01 at 15 47 38" src="https://user-images.githubusercontent.com/1794099/33487908-2b1dcabe-d6af-11e7-8dff-c8c827e89872.png">
