### ISSUE TITLE
Allow to zoom into individual viewlets/panels instead of entire workbench

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#38988]
Let say I only want to zoom the file explorer panel and preserved the source editor panel. Is that possible?

**Comment by alskdj21** [comment]
Maximizing a panel? The way how the integrated terminal can be maximize.

**Comment by tangorboyz** [comment]
not maximizing, just zoom in or zoom out.

**Comment by alskdj21** [comment]
Ah yes, it does zoom all panels. My bad.

**Comment by bpasero** [comment]
@tangorboyz do you really want to zoom or just change the font size maybe?

**Comment by tangorboyz** [comment]
I want to zoom the file explorer but leave the source editor as it is.
