### ISSUE TITLE
Increase feedback length to new Twitter280 limit

### ISSUE THREAD

**Issue by jaller94** [Microsoft/vscode#38983]
https://github.com/Microsoft/vscode/blob/9f1746820c505e671a4d5197f29f2ca23b9adaf1/src/vs/workbench/parts/feedback/electron-browser/feedbackStatusbarItem.ts#L47

- VSCode Version: 1.18.1 and current master 9f1746820c505e671a4d5197f29f2ca23b9adaf1

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/35214
