### ISSUE TITLE
Output folder widening

### ISSUE THREAD

**Issue by mladenbruck** [Microsoft/vscode#38985]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.2
vscode-arduino|vsc|0.2.10

Every bulid add more deepher direcory path in output folder, until it is to long where it is imposible to build project any more.
This is folder structure after first compile, where output folder is "build":
..\build\sketch
after second compile:  \build\sketch\build\sketch
third compile: \build\sketch\build\sketch\build\sketch
4th compile: \build\sketch\build\sketch\build\sketch\build\sketch
and so on...
..
---

Steps to Reproduce:

1.  Add output folder in arduino.jsdon as follow:
{
    "board": "arduino:avr:nano",
    "configuration": "cpu=atmega328",
    "sketch": "Trusioma.ino",
    "output": "build"
}
2. Bould project (ctrl-alt-r) several times

Reproduces without extensions: Yes/No

**Comment by mladenbruck** [comment]
This is final error: 
open sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\preproc\ctags_target_for_gcc_minus_e.cpp: The system cannot find the path specified.
[Error] Exit with code=1

and this is path created:
..\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\sketch\build\preproc

**Comment by dbaeumer** [comment]
This looks like a problem of the vscode-arduino extension. Please file the bug report against that extension here https://github.com/Microsoft/vscode-arduino
