### ISSUE TITLE
Fail to display breakpoint in editor

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#38991]
- VSCode Version: Code - Insiders 1.19.0-insider (d294b25f2dd5c96d89bd23f82bd5fd2c0958a4bd, 2017-11-21T06:26:09.478Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.11.1
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
autoimport|ste|1.5.3
vim|vsc|0.10.5
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

After setting the break point in a C++ program and then running, the breakpoint indicator disappears.

---

Steps to Reproduce:

1. Open up C++ code
2. Set breakpoint
3. Debugs

Sometime later the breakpoint indicator is not shown.

![bp](https://user-images.githubusercontent.com/439226/33155540-4ecd639e-cfbf-11e7-9e2a-647725da987d.png)

Reproduces without extensions: Yes/No

**Comment by rajinder-yadav** [comment]
Also if you toggle the breakpoint checkmark, the breakpoint indicator is still not displayed.

**Comment by isidorn** [comment]
@rajinder-yadav can you also reproduce this if you do never start a debug session?
So just by adding them in the editor do they disapear?
Or the breakpoint only disapears once you start debugging?

**Comment by rajinder-yadav** [comment]
@isidorn I am seeing the breakpoint disappear once I start debugger and the session ends.

**Comment by weinand** [comment]
@rajinder-yadav what happens if you select the breakpoint in the BREAKPOINTS view? Does a new editor open and the breakpoint is visible?

**Comment by rajinder-yadav** [comment]
@weinand If I select the break point from the BREAKPOINTS view it shows up again. Just disappears after each debug session.

**Comment by isidorn** [comment]
@rajinder-yadav please file this against the C++ extension here with exact reproducable steps https://github.com/Microsoft/vscode-cpptools

What I think is happening is that the extensions is sending sources with wrong casing / path and then the source gets displayed multiple times, thus you do not see the breakpoint.
