### ISSUE TITLE
keybindings.json has a wrong command

### ISSUE THREAD

**Issue by zsedcbm** [Microsoft/vscode#38998]
{
        "key": "ctrl+[",
        "command": "editor.emmet.action.previousEditPoint"
    },
the right command is  "  editor.emmet.action.prevEditPoint  "

**Comment by usernamehw** [comment]
Is this command inside default keybindings or yours?

**Comment by ramya-rao-a** [comment]
I believe `editor.emmet.action.previousEditPoint` was the command id before the move to Emmet 2.0 that was made in the July release.
In the move, all the emmet actions were re-implemented and the command id got changed to `editor.emmet.action.prevEditPoint`

@zsedcbm You must have added the keybinding before the move and so it doesnt work anymore.
Sorry for the trouble.

**Comment by zsedcbm** [comment]
@ramya-rao-a  @usernamehw   thanks.
I forgot when I set it up keybindings, There's no problem now. it's fine.
