### ISSUE TITLE
Auto intellisense for jquery doesn't work in 1.18.1

### ISSUE THREAD

**Issue by RenRongrong** [Microsoft/vscode#38994]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
rest-client|hum|0.16.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|5.0.17
csharp|ms-|1.13.1
angular2-inline|nat|0.0.17
vsc-angular-cli|web|1.0.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.open folder with node-modules which contains jquery
2.open a js file

Reproduces without extensions: Yes

In previous versions it can automatically show the intellisense of jquery once there is a node_modules folder in the project which contains jquery. But it doesn't work in version 1.18.1.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20282
