### ISSUE TITLE
How to beautify freeMaker code

### ISSUE THREAD

**Issue by Catcheer** [Microsoft/vscode#38995]
- VSCode Version:1.18.1
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
