### ISSUE TITLE
40% CPU and Gigs of memory used parsing a map

### ISSUE THREAD

**Issue by bootstraponline** [Microsoft/vscode#38993]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Version 1709 (OS Build 16299.19)

Steps to Reproduce:

1. `git clone https://github.com/bootstraponline/hex.git`
1. `git checkout dbf422b1856d054b01bd28193ca52ed9c4033ceb`
2. Open `hex/ts/` in Visual Studio Code
3. Change anything in the TypeScript files
4. Observe gigs of memory used.

![image](https://user-images.githubusercontent.com/1173057/33155892-70741f6c-cfc2-11e7-82cc-cf7e3c95ac82.png)

![image](https://user-images.githubusercontent.com/1173057/33155972-370ef5e8-cfc3-11e7-95c7-254ffd7b79a2.png)

Reproduces without extensions: Yes

- [codes.ts](https://github.com/bootstraponline/hex/blob/dbf422b1856d054b01bd28193ca52ed9c4033ceb/ts/src/hex/codes.ts#L12905)

I have a large map. That appears to make TypeScript crazy. I'm not sure if there's a way to disable processing on a per file basis. This issue does not happen when using JSON instead of a map.

```javascript
export let codes = new Map([
   ['03310001', ['Potion', 'Battle Items [0]', true]],
   // ...
]);
```

**Comment by KuromiAK** [comment]
Change the code in this way seems to help?
```
export let codes = new Map<string, [string, string, boolean]>([
   ['03310001', ['Potion', 'Battle Items [0]', true]],
   // ...
]);
```

**Comment by bootstraponline** [comment]
This helped the most. I'm not sure what causes gigs of memory usage. Maybe giant arrays in the constructor is an edge case.

```
// Use map to preserve iteration order. Object.keys is undefined
export let codes: Map<string, [string, string, boolean]> = new Map();
export function initCodes() {
  if (codes.size > 0) { return; }

  codes.set('03310001', ['Potion', 'Battle Items [0]', true]);
  codes.set('74500001', ['Power Ex', 'Battle Items [0]', true]);
  
...
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20279
