### ISSUE TITLE
LinkedList.iterator is deopt

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39001]
![image](https://user-images.githubusercontent.com/323878/33158101-f62ea2d2-cfbb-11e7-921c-3d44c7a0a803.png)

> Not optimized: Object literal with complex property

The JS here has

```js
var element = {
	get done() { return _done; },
	get value() { return _value; }
};
```

and also 

```js
return {
	next: function () {
        ...
```

not sure which one it's complaining about.

https://github.com/vhf/v8-bailout-reasons#object-literal-with-complex-property

**Comment by jrieken** [comment]
Will, check... Wanted to be smart and not create new objects all the time

**Comment by roblourens** [comment]
I saw this a lot while running a search and profiling.

**Comment by jrieken** [comment]
Pushed a fix to use just an object and to enforce readonly-ness on TypeScript's level. Time drop from 5.9ms to 0.9ms when profiling startup on my machine 🚀
