### ISSUE TITLE
File Search: Inconsistent exclude settings button outline

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#39005]
The new file search input options include/exclude appear to have an inconsistent button outline
for the exclude settings.  As far as I can tell there are no other action bar buttons with this  outline style.
It is also a very similar color to the default outline color of several themes.  See below where I have the primary search input focused and it also looks like the button is focused.

![image](https://user-images.githubusercontent.com/25272315/33159866-507e29fa-cfe5-11e7-8a85-42f9375de239.png)

![image](https://user-images.githubusercontent.com/25272315/33159938-43a1db72-cfe6-11e7-9a2e-5c259ca8eaaa.png)

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/33164764-1d3eb4d4-cfe9-11e7-9666-77d93b792962.png)

The toggle button is enabled and it has the same border color as the other search viewlet buttons when they are enabled.
