### ISSUE TITLE
快捷键删除后，怎么恢复

### ISSUE THREAD

**Issue by deepcc** [Microsoft/vscode#39009]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-css-formatter|aes|1.0.0
vscode-es-beautifier|dai|1.0.0
vscode-markdownlint|Dav|0.11.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
wpy-beautify|doi|2.0.10
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.20
mithril-emmet|Fal|0.6.1
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
mdmath|goe|2.0.7
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.5
vscode-picture|Jak|1.0.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.10
evermonkey|mic|2.4.0
code-beautifier|mic|1.7.2
vscode-fileheader|mik|0.0.2
sublime-keybindings|ms-|3.0.3
vs-keybindings|ms-|0.1.7
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vuehelper|oys|0.1.0
vue-vscode-snippets|sdr|1.2.0
ejs-snippets|Tao|0.1.0
JavaScriptSnippets|xab|1.5.0
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
