### ISSUE TITLE
Windows ZIP Version Does Not Support Update Notifications

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [Microsoft/vscode#39006]
Unlike the Linux *.tar.gz version, which at least checks for updates (even if it only redirects you to the website to download the latest version), the Windows *.zip version just doesn't check, forcing the user to manually check the website regularly just to keep up to date. It would be nice if this feature was implemented for the Windows *.zip version.

- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Download and Unzip the VSCode ZIP Package for Windows
2. Run VSCode
3. "Check for Updates" is missing from the Help menu
4. Clicking the gear in the lower left hand corner shows "Updates Not Available"

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Unfortunately that's gonna stay that way for now. Sorry about that. Updates are only supported via the Setup.
