### ISSUE TITLE
Can't remove a leading space of a file name. 

### ISSUE THREAD

**Issue by Ivraie** [Microsoft/vscode#39017]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
xml|Dot|1.9.2
seito-openfile|Fr4|1.4.0
vscode-ungit|Hir|1.1.1
autofilename|Jer|0.1.3
material-icon-theme|PKi|3.0.0
vscode-docker|Pet|0.0.22
better-comments|aar|0.1.3
yaml|ada|0.0.9
npm-intellisense|chr|1.3.0
regex|chr|0.1.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|6.1.2
tslint|eg2|1.0.23
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.20
githd|hui|1.0.0
testing-regex|jus|0.0.2
vscode-regexp-preivew|le0|0.0.3
vscode-todo-parser|min|1.9.1
lit-it|moh|1.2.12
azure-account|ms-|0.2.2
typescript-javascript-grammar|ms-|0.0.24
vscode-json-transform|oct|0.1.2
favorites|ole|1.0.2
vscode-versionlens|pfl|0.19.1
node-tdd|pra|0.2.4
vscode-yaml|red|0.0.6
vscode-sort-json|ric|1.10.2
json-organizer|rin|0.0.3
edit-locations-history|sad|0.2.5
code-spell-checker|str|1.4.12
json-schema-validator|tbe|0.1.0
es-quotes|vil|0.2.6
vscode-import-cost|wix|2.5.1
vscode-jumpy|wma|0.3.1

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Create a new file in VS Code. Save it with a name that has one or more leading blank spaces. 
2. Remove the blank spaces by using the VS Code editor (F2 or rename of the context menu). 
3. Press enter to validate the new name.

It happens that the blank spaces are still there. 

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I am closing this because I find that a file with leading spaces is not very common and VS Code is not trying to replace the native file manager tool, so there can be some bugs/differences and that imho is tolerable.
