### ISSUE TITLE
"clone git repo" missing on welcome page

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#39016]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.23
python|ms-|0.8.0
cpptools|ms-|0.14.2
java|red|0.14.0

---

Steps to Reproduce:

1. Start VSCode

Reproduces without extensions: Yes

---

As of today, my installation of VSCode is missing the "clone git repo" on the welcome page. It used to be on the top left under "Start", now there are only the links "New File", "Open folder", "Add workspace folder"

**Comment by AlCalzone** [comment]
Or is there any other way to start working on a github hosted project with just a few clicks? I can't seem to find this functionality anymore.

**Comment by rosesonfire** [comment]
I am having the same problem. I just installed on Ubuntu 16, 
```
Visual Studio Code
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
```
git version 2.7.4
```

**Comment by chrmarti** [comment]
I replaced it with "Add workspace folder", thinking that this will be an important action with multi-root workspaces and I didn't want to increase the number of actions to keep it clean. You can still invoke the action through Ctrl + Shift + P and then filter for 'Git: Clone'.
