### ISSUE TITLE
Unable to remove vscode insiders shell integration

### ISSUE THREAD

**Issue by caraya** [Microsoft/vscode#39010]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
latex-workshop|Jam|3.7.0
vscode-docker|Pet|0.0.22
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
toml|be5|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
code-runner|for|0.8.4
CppSnippets|har|0.0.13
path-autocomplete|ion|1.7.0
docthis|joe|0.6.0
pwa-tools|joh|0.1.0
mdhelper|jos|0.0.11
Go|luk|0.6.67
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
python|ms-|0.8.0
azure-account|ms-|0.2.2
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
wordcount|ms-|0.1.0
debugger-for-chrome|msj|3.5.0
open-html-in-browser|pea|0.0.2
Ruby|reb|0.15.0
vscode-icons|rob|7.18.1
RustyCode|sav|0.19.1
wordpress-snippet|tun|1.1.2
vscode-todo-highlight|way|0.5.11
vscode-import-cost|wix|2.5.1
JavaScriptSnippets|xab|1.5.0
markdowion-all-in-one|yzh|0.11.1

---

Steps to Reproduce:

1. Install VSCode Insiders Build while the stable VSCode build is installed
2. Enable shell integration
3. Disable shell integration
4. Uninstall VSCode Insiders Build
5. Enable shell integration in VSCode stable
6. In a terminal try to run `code .`. The following error appears: **LSGetApplicationForInfo() failed with error -10814 while trying to determine the application with bundle identifier com.microsoft.VSCodeInsiders.** 

I expect code . to open the current directory in the stable version of VSCode. 

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What does `which code` return? As well as `ls -la $(which code)`

**Comment by caraya** [comment]
`which code` returns an empty prompt.  `ls -la $(which code)`  list the content of my current directory

**Comment by joaomoreno** [comment]
You need to run this action:

![image](https://user-images.githubusercontent.com/22350/34094648-4f46ecc8-e3ce-11e7-80f2-2025230dbfa1.png)

This will install a proper code CLI launcher.

**Comment by caraya** [comment]
I did install it and it didn't work
