### ISSUE TITLE
the node problem in the terminal

### ISSUE THREAD

**Issue by Miaite** [Microsoft/vscode#39012]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
intellij-idea-keybindings|k--|0.2.16
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
open-in-browser|tec|1.1.0

---

Steps to Reproduce:

1.the terminal in vscode show me this below:
```
npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v9.2.0 --silent` to unset it.
```
2.and I can't use node or npm
3.but I can still use node or npm in the original terminal in the macOS

Reproduces without extensions: Yes/No

**Comment by Miaite** [comment]
reboot system and it's all right

**Comment by zanza00** [comment]
I have the same problem, if I ran the second command, `nvm use --delete-prefix v8.9.1 --silent` in my case, node return avaliable.

I am using insider version and nvm and using default version as node 8

**Comment by Miaite** [comment]
Run `npm config delete prefix` or `nvm use --delete-prefix v9.2.0 --silent` is useless.
 And node  v8.9.1 is avaliable  with `nvm use --delete-prefix v8.9.1 --silent`

**Comment by Tyriar** [comment]
The problem is likely related to the terminal's environment. Could you run something like this to check the differences between the environments? `env | grep NVM`

**Comment by zanza00** [comment]
In my case inside vscode is
```
❯ env | grep NVM
NVM_CD_FLAGS=-q
NVM_DIR=/Users/zanza00/.nvm
```

in iterm is
```
❯ env | grep NVM
NVM_DIR=/Users/zanza00/.nvm
NVM_CD_FLAGS=-q
NVM_BIN=/Users/zanza00/.nvm/versions/node/v8.9.1/bin
```

if I type nvm use 8 (inside vscode) the NVM_BIN variable is correctly set
```
❯ nvm use 8
Now using node v8.9.1 (npm v5.5.1)

❯ env | grep NVM
NVM_CD_FLAGS=-q
NVM_DIR=/Users/zanza00/.nvm
NVM_BIN=/Users/zanza00/.nvm/versions/node/v8.9.1/bin
```

let me know if you need more info 😄

**Comment by Tyriar** [comment]
@zanza00 where ever you're running `nvm use 8` in your setup scripts is not being run in VS Code. Either of the following settings may fix the problem:

```
"terminal.integrated.shellArgs.osx": [ "-l" ]
"terminal.integrated.shellArgs.osx": []
```

**Comment by zanza00** [comment]
@Tyriar sadly neither of those works :(

I think that the problem is that I use the `default` approach (`nvm alias default 8`) listed here https://github.com/creationix/nvm#listing-versions and not using `nvm use 8`

So i started digging in my `.zshrc` and found the reason

with this two lines for initializing nvm *does not work*
```
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
```

however if i change it to one line *it works*
```
export NVM_DIR="$HOME/.nvm/usr/local/opt/nvm/nvm.sh"
```

**Comment by Tyriar** [comment]
Aren't they doing different things though? The first one is exporting `$NVM_DIR` and then sourcing `/usr/local/opt/nvm/nvm.sh`, the second is setting `$NVM_DIR` to something different? 😕

**Comment by Tyriar** [comment]
@zanza00 you could try adding some `echo` statements in the scripts in question to understand which scripts are being called and in which order. You could also diff the environments in each terminal which will give you similar hints.

**Comment by Tyriar** [comment]
I just wrote a FAQ on the website about the proper fix for this issue: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched
