### ISSUE TITLE
How to open a new file in new tab using quick open short cut

### ISSUE THREAD

**Issue by jeyanthimuthuram** [Microsoft/vscode#39014]
I tried both `ctrl + e` and `ctrl + p` , both are used to open files quickly. But the bad thing I saw there is both are replacing my old opened files , It is irritating , it is closing the files randomly.

Is there any shortcut there to open a file always in new tab ? if not please fix this.

**Comment by bpasero** [comment]
You can either configure this for everything you open via `"workbench.editor.enablePreviewFromQuickOpen": false` or get our latest insider build where yesterday I pushed a change to allow for `Alt+Enter` to open as a permanent tab. 

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
