### ISSUE TITLE
Underscore is not visible in the Terminal

### ISSUE THREAD

**Issue by sklrsn** [Microsoft/vscode#39018]
- VSCode Version:1.18.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1.type A_B in the terminal
2. you will see A B

Reproduces without extensions: Yes/No
![image](https://user-images.githubusercontent.com/13186099/33166703-dbd55920-d043-11e7-8201-0d81ca97e27e.png)

**Comment by bochen2014** [comment]
got the same issue here

**Comment by mpoeter** [comment]
Same here since I updated to v1.18 - v1.17 did not show this behavior.

**Comment by maxibanki** [comment]
Duplicate of #38133

**Comment by bochen2014** [comment]
ok. I'll just past the answer here for ppl's convenience
```json
"window.zoomLevel": -0.001
```
by @suonto [here](https://github.com/Microsoft/vscode/issues/38133#issuecomment-346372521)
