### ISSUE TITLE
[Feature Request]: Add support for embedded languages inside other languages

### ISSUE THREAD

**Issue by Modelmat** [Microsoft/vscode#39026]
I want to be able to write code inside VSCode in other languages, such as SQL (or JSON), inside python.
For instance, say I am using the `sqlite3` library, and I am writing a SQL command:

     cur.execute("DROP TABLE Servers")

I would like the SQL structure to be able to autocomplete itself, using the "SQL" language syntax already inside of VSCode.

This would work similarly for JSON as well, and any other "embedded" languages in Python or other languages.

**Comment by usernamehw** [comment]
A duplicate of https://github.com/Microsoft/vscode/issues/1751?

**Comment by Modelmat** [comment]
Yes, it is. I thought I search pretty well...
