### ISSUE TITLE
Ability to keep only the current directory expanded in the Explorer

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#39025]
- VSCode Version: 1.18.1
- OS Version: macOS 10.12.3

After opening many different files within different subdirectories in a project, many directories will be expanded in the file tree in the Explorer pane. This makes it difficult to subsequently browse the file tree without having to first hit the Collapse All button.

It would be great if there was an option to only expand the directory tree of the currently focused file, so each time you switch to another file all the other directories in the tree are collapsed.

**Comment by boblauer** [comment]
This extension seems to do the trick - https://github.com/hoovercj/vscode-api-playground/tree/master/AutoCollapseExplorer
