### ISSUE TITLE
python format document sometimes does work (have to restart vscode)

### ISSUE THREAD

**Issue by donglixp** [Microsoft/vscode#39023]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063 (for ubuntu, also the same issue)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
json-tools|eri|1.0.2
auto-close-tag|for|0.5.3
code-runner|for|0.8.4
latex-workshop|Jam|3.7.0
pomodoro|lky|1.0.2
python|ms-|0.8.0
sublime-keybindings|ms-|3.0.3
subtle-brackets|raf|2.1.0
code-settings-sync|Sha|2.8.6
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. python format document sometimes does work
2. have to restart vscode in order to make it work again
3. go to step 1

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: Python.
