### ISSUE TITLE
The programe can not run !

### ISSUE THREAD

**Issue by GitSoftwareNow** [Microsoft/vscode#39028]
when I download vscode in offficial website and run in console but the console says ./code: symbol lookup error: ./code: undefined symbol: g_bytes_unrefce
my glib version is 2.0 os is centos6.5

**Comment by maxibanki** [comment]
Duplicate of #23232.
As @Tylor said:
> We don't support < RHEL7 and its derivatives as per the el7 in the filename and this page https://code.visualstudio.com/docs/supporting/requirements#_platforms

**Comment by joaomoreno** [comment]
Thanks @maxibanki
