### ISSUE TITLE
Test: touch support

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39021]
- [x] win @dbaeumer
- [ ] linux @kieferrm 
- [x] [standalone editor](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#running-the-editor-from-source) @alexandrudima

Refs: https://github.com/Microsoft/vscode/issues/37917
Complexity: 3

We have refactored how we are listening to touch events in the workbench and the editor. Take a touch laptop and verify we behave as before:
* You can use touch tap to focus / execute varios parts in the workbench (status bar, input boxes, activity bar, editor)
* You can use scroll using touch in the editor / tree / list and this respects the balistic scroll behavior (the faster you touch the faster it scrolls)
* You can use touch to trigger a context menu

If you are not sure what the behavior should be you can just take the current stable vscode and compare against it.

**Comment by octref** [comment]
I don't have any touch laptop. How do I test it?
And AFAIK there is no Mac that has touch screen.

**Comment by alexandrudima** [comment]
I think @kieferrm has a surface book tucked somewhere ... so giving to you.

I agree @isidorn can remove the mac option.

**Comment by kieferrm** [comment]
@alexandrudima anybody ever tried touchscreen testing on a Surface Book? I created a live USB ubuntu 16.04.3 LST drive and can boot from i. But the touch screen is not detected as an input device and `xinput list`confirms that. It seems I need to run patched kernels and even then would have only limited chances to get the touch screen reliably working.

**Comment by kieferrm** [comment]
@Tyriar does your linux laptop has touch screen support and does it work?

**Comment by alexandrudima** [comment]
I have never managed to use a touch device on Linux either, so removing Linux now.
