### ISSUE TITLE
Macros are missing from the Visual Studio Code

### ISSUE THREAD

**Issue by kashif-khan** [Microsoft/vscode#39022]
- VSCode Version: 1.18.1
- OS Version: Windows 10 PRO 10.0.14393

Steps to Reproduce:

1. There is no Macros in the Visual Studio Code like in the Notepad++

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/4490

**Comment by joaomoreno** [comment]
Thanks, @usernamehw
