### ISSUE TITLE
Support installing pre-release (alpha/beta/insiders) versions using VSIX

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39024]
Currently, extension authors get their pre-release versions tested by the community using VSIXs. But VS Code does not support installing alpha/beta/insiders versions. This force authors to always use patch for pre-release versions. 

By supporting alpha/beta/insiders versions, author can generate VSIXs like `pub.extname-0.11.0-beta` or `pub.extname-0.11.0-beta-2`. At the end, they can publish the release version `pub.extname-0.11.0` and all users who are using pre-release versions will get the release update.

**Comment by sandy081** [comment]
To verify:

- Disable auto updating extensions
- Publish an extension with version `0.10.0` that has a command which will print its current version when invoked.

- Compute a VSIX of the above extension with version `0.9.1` and prints `0.9.1` as its version
- Install it and confirm it prints `0.9.1` as its version
- Make sure the update to `0.10.0` is shown

- Compute a VSIX of the above extension with version `0.11.0-insiders` and prints `0.11.0-insiders` as its version
- Install it and confirm it prints `0.11.0-insiders` as its version

- Compute a VSIX of the above extension with version `0.11.0-insiders-2` and prints `0.11.0-insiders-2` as its version
- Install it and confirm it prints `0.11.0-insiders-2` as its version

- Publish the extension with version `0.11.0`  that prints `0.11.0` as its version
- Make sure the update to `0.11.0` is shown
- Install it and confirm it prints `0.11.0` as its version

- Uninstall the extension and make sure extension is not shown in the viewlet
- Quit and Start VS Code and open Extensions folder and make sure above extension folder does not exist.

**Comment by felixfbecker** [comment]
I wish the marketplace just supported release channels (e.g. `latest`/`stable`, `next`/`unstable`/insiders`, ...)
