### ISSUE TITLE
[Feature request] Get a clear message popup after "git push" succeed/failed

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#39039]

**Comment by joaomoreno** [comment]
Sorry, won't happen. We'll just get two users complaining that the message is irrelevant.

**Comment by eladcandroid** [comment]
So you can give an option to cancel it.. and even set it to false by default.. The messages system exists in Atom for example. 
Please reopen the issue and give the community play its voice...

**Comment by joaomoreno** [comment]
Sure.

**Comment by pr-yemibedu** [comment]
@eladcandroid did you have a specific ui layout that you would like to see? Hopefully you did not want their to be a modal dialog popping up in the middle of a developers workflow? In Atom, the notifications are by default color coded in the upper right. That overlay has its good and bad points:

  -  speed it shows the next message
  -  length of time the existing message lasts
  -  color palette meaning for a message
  -  ability to get to a history of notifications
  -  noise level to the current user

I dare not speak of what who finds what to be good or bad, just pointing out that with the problem view, output window, and status bar, their should be a thoughtful way to include this to get beneficial utility. Maybe a growl or native platform notification would be better?

The last one looks cool.
[Atom Growl](https://atom.io/packages/atom-growl)
[Growl Atom](https://github.com/matth/growl-atom)
[Atom Notifier](https://github.com/benjamindean/atom-notifier)
[Node notifier](https://github.com/mikaelbr/node-notifier)

**Comment by eladcandroid** [comment]
@pr-yemibedu As you said, the ui for this "growl" needs to be with the minimum "noise" for the user and with settings like auto close delay time, font size etc..  about the overall look - we can choose one of the options you suggested.

**Comment by eladcandroid** [comment]
Example for existing "growl" popup that shows up when trying to check for updates in VSCode:
![image](https://user-images.githubusercontent.com/13297000/33832844-466f3bfc-de86-11e7-8131-f89cf2049f75.png)

**Comment by MohamedCharaf** [comment]
I think this would be very useful, For example where I live the internet connection is so bad that I have to check the git output panel every time I push to make sure commits have been pushed.
