### ISSUE TITLE
Error al reiniciar el host de extensiones

### ISSUE THREAD

**Issue by EnrikeGonzaloLegarra** [Microsoft/vscode#39038]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
modl|ao|0.1.21
vscode-icontheme-nomo-dark|be5|1.3.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-npm-source|dku|1.0.0
githistory|don|0.2.3
xml|Dot|1.9.2
scopes|dua|0.28.0
gitlens|eam|6.1.2
tslint|eg2|1.0.23
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
node-version|fiv|0.0.1
theme-rusty-icons|ion|0.0.1
search-node-modules|jas|1.2.0
vsclassic-icon-theme|jez|1.1.0
atom-keybindings|ms-|3.0.2
cpptools|ms-|0.14.2
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
node-tdd|pra|0.2.4
typescript-hero|rbb|1.7.0
chai-spec-generator|rin|0.4.0
jasmine-problem-matcher|sea|1.0.1
nodejs-extension-pack|wad|0.1.9
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Error al reiniciar el host de extensiones
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
