### ISSUE TITLE
[js] syntax highlight for 'var' and 'function' not working in Default VS theme 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3903]
0.10.10 (Feburary build) has a regression is that the following JavaScript keywords are no longer highlighted in the Dark Visual Studio & Light Visual Studio themes:
`var ` `let ` `const` `function` `get` `set` `class` `interface` `module` `namespace`

This only affects JavaScript (not TypeScript).
The workaround if to switch to the Dark+ Default and Light+ theme.

Note that there are other colorizing issues open, not caused by this regression: e.g. 'import' and 'from'. See https://github.com/Microsoft/TypeScript-TmLanguage/issues/37

**Comment by Thaina** [comment]
Not sure if intended but delete is not highlighted too

**Comment by aeschli** [comment]
'delete' is also https://github.com/Microsoft/TypeScript-TmLanguage/issues/37

**Comment by nevir** [comment]
It also appears to get confused about `var` when it is part of another identifier (which throws off all styles beyond that point):

![image](https://cloud.githubusercontent.com/assets/41373/13653299/c85f1cc0-e605-11e5-889b-ae98cc9e819a.png)

**Comment by Thaina** [comment]
delete still not highlighted. Is it intended?

**Comment by aeschli** [comment]
'delete' is Microsoft/TypeScript-TmLanguage#37 and will be fixed in the March release.

**Comment by aeschli** [comment]
Yesterday, we created a new release that contains the fix for the coloring of `var`, `let`, `const`, `function` etc.
Please update...

**Comment by NickHeiner** [comment]
`yield` is still not highlighted with version f291f4ad600767626b24a4b15816b04bee9a3049. Is that intended?

**Comment by nkhanhcong** [comment]
seem like import isn't highlighted
