### ISSUE TITLE
Search in Workspace

### ISSUE THREAD

**Issue by mcuneyda** [Microsoft/vscode#39037]
- VSCode Version: 1.18.1
- OS Version: Windows 10

can i search in workspace? like visual Studio 2017
i just want press one key and search to file.

like - > https://i.hizliresim.com/Qp0z4r.gif

(sorry my bad english)

**Comment by tverboon** [comment]
With Command + P on the Mac you can start typing a filename and open when found, so it's probably CTRL+P on Windows.

**Comment by roblourens** [comment]
I think the gif shows typing to search in a tree view, I've missed that as well.
