### ISSUE TITLE
Terminal: suspend when not visible

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39031]
Consider a long running job that is executing in the terminal with lots of output produced periodically. When the integrated terminal is not visible in VS Code I would assume that it becomes a no-op for the renderer at least. 

It looks like the integrated terminal is not suspending work when hidden and the upstream issue is: https://github.com/xtermjs/xterm.js/issues/880

**Comment by Tyriar** [comment]
Put a PR out to do this using [IntersectionObserver][(https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) https://github.com/xtermjs/xterm.js/pull/1144

**Comment by bpasero** [comment]
Cool!

**Comment by Tyriar** [comment]
To verify, run some command that outputs text every second and background the terminal. Looking at a performance timeline should show only parsing related scripting, not rendering.

**Comment by bpasero** [comment]
@Tyriar much better. the remaining things I see are:

![image](https://user-images.githubusercontent.com/900690/35571265-e0fa8894-05d1-11e8-95fc-e70648efecbd.png)

and

![image](https://user-images.githubusercontent.com/900690/35571298-f921f3e4-05d1-11e8-9c3d-62a0447a576b.png)

**Comment by Tyriar** [comment]
🎉
