### ISSUE TITLE
The automatic build with webpack doesn't work where the project is in the workspace!

### ISSUE THREAD

**Issue by wangyi7099** [Microsoft/vscode#39030]
- VSCode Version:1.18.1
- OS Version:Ubuntu  16.04 lts

Steps to Reproduce:

1.When I run code in the nodejs + webpack + react + vscodeworkspace . I typed the npm run dev start nodejs server with  webpack plugin ''webpack-hot-middleware'' that can detect the file changes and automatically  build project .  But it seems that it doesn't work at all when I changed files and save. And when I process the project by a singe project rather than in a workspaces, It works well. SO.. I don't know whether this is a bug or not, and give this issue..
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
It's very hard to understand. What is the specific issue with **VS Code** that you are facing?

**Comment by wangyi7099** [comment]
@joaomoreno 

I'm so sorry to my poor English !   
 I mean that when I run the  react code with the VSCDOE's new feature Multi-root workspaces.
The express plugin "webpack-hot-middleware" which can detect the changes on the files and auto publish  doesn't work. But when I run code without Multi-root workspaces, the plugin works well...

**Comment by bpasero** [comment]
This sounds to me like an issue with webpack not VS Code. Closing.
