### ISSUE TITLE
Symbol not recognized in the workspace affecting autoimport

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#39032]
- VSCode Version: 1.18.1, Typescript 2.6.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install the most recent update and restart the editor
2. Go to Symbol in Workspace... try finding a symbol in your utils folder with no luck
3. Try invoking the import suggestion with no luck

![image](https://user-images.githubusercontent.com/2313018/33171634-3fd5c38e-d04d-11e7-83fe-ba619ebfa350.png)

4. Open the file with the concerned export and leave it on another tab
5. Auto importing now works.

![image](https://user-images.githubusercontent.com/2313018/33171685-80be7cb0-d04d-11e7-9b2f-9290b200cbb4.png)

Since I opened new editor (without a file), the Go to Symbol still didn't work.

6. create new file `x.js` anywhere in the project and try the import and Go To Symbol again.
7. Now it all works

![image](https://user-images.githubusercontent.com/2313018/33173239-b6a32b4a-d053-11e7-85ac-30e12ba79bab.png)

8. If you close the exporting file, the symbol can't be find again and the autoimport suggestion won't work.

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your workspace with the contents:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VSCode to treat all js files in your workspace as part of the same project

**Comment by ackvf** [comment]
This helped with the issue. Thanks.
