### ISSUE TITLE
Support to terminate extension host through IPC

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3904]
For the 'Run without debugging' we need a way to shut down the extension host when the user has pressed the debugger's Stop button.

see #3905 for the related UI item.

**Comment by bpasero** [comment]
@weinand is a IPC broadcast good enough for you guys?

**Comment by weinand** [comment]
@bpasero from discussions with @isidorn I got the impression that IPC broadcast is enough.

**Comment by bpasero** [comment]
@isidor it is not via broadcast but basic IPC to the main side and it goes like this from the renderer:

```javascript
import {ipcRenderer as ipc} from 'electron';
ipc.send('vscode:closeExtensionHostWindow', 'extension development workspace path');
```

the extension development workspace path is used to find the window that runs this extension.
