### ISSUE TITLE
Collapsing code in code view breaks when # (hash) present

### ISSUE THREAD

**Issue by jonasao** [Microsoft/vscode#39040]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-17-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python-docs|Muk|0.8.3
vscode-docker|Pet|0.0.22
nativescript|Tel|0.7.2
MagicPython|mag|1.0.12
python|ms-|0.8.0
python|tht|0.2.3

(1 theme extensions excluded)

---
Minimizing methods/functions in code view by clicking the plus-sign next to the method-/function name does not work correctly when code is commented out using # (hash) in python. 
Code is only minimized from the start of the method/function until the 1st line of commented code.

Steps to Reproduce:

1. Create a method without any comments
2. Click the plus-sign next to the name of the method and observe that the code is minified/collapsed, only displayin the line with the method name and arguments itself.
3. Expand the method's code
4. Add a comment beginning with a # (hash) in the middle of the method.
5. Click the plus-sign next to the name of the method and observe that the code is minified/collapsed only to the commented code.

Reproduces without extensions: Yes

**Comment by shivammittal99** [comment]
Hello, I would like to work on this.

**Comment by aeschli** [comment]
Our folding is currently purely indentation based. The request to have language aware folding is #3422. Having that, we can creat folding regions based on the information of a language server  from where to where a comment goes.
@shivammittal99 This is not a trivial issue to implement. It needs work on the language servers to return language aware folding regions as well an efficient way of communicating this information across processes.
As a workaround you could think of using the folding regions in your code: `#region` and `#endregion`.

Closing as dup of #3422
