### ISSUE TITLE
CLI Process: missing machine identifier

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39044]
While cleaning up the machine identifier I noticed that [`cliProcessMain`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cliProcessMain.ts#L208) does not have the machine identifier property set. Since we store the machine identifier within `storage.json` it could easily get it out of there.

**Comment by joaomoreno** [comment]
While you're there, do you mind finishing it up, then?

**Comment by joaomoreno** [comment]
![hears](https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy-downsized-large.gif)

**Comment by roblourens** [comment]
Where does the CLI service log telemetry? I don't see any

**Comment by bpasero** [comment]
@roblourens I think it does via the extension service. E.g. when you install an extension via CLI. But maybe we took this out lately?
