### ISSUE TITLE
When expanding folder not all files are shown

### ISSUE THREAD

**Issue by andreleon** [Microsoft/vscode#39049]
- VSCode Version: 1.18.1
- OS Version: macOS Sierra Version 10.12.6

Steps to Reproduce:
![large gif 364x330](https://user-images.githubusercontent.com/1391492/33182682-4b405b9e-d075-11e7-93a9-835432f8b436.gif)

Reproduces without extensions:
No, but also not after re-enabling them.

**Comment by isidorn** [comment]
If you cannot reproduce without extensions then there is nothing we can do here.
Can you reproducae with latest vscode insiders https://code.visualstudio.com/insiders/
If yes can you please give us exact reproducable steps
