### ISSUE TITLE
VSCode needs updated in fedora repo

### ISSUE THREAD

**Issue by AlwaysMind** [Microsoft/vscode#39041]
Please update the vscode build stored in your yum repo.

I've tried to run dnf update
and dnf check-update but nothing appears so I assume that your repo has not been updated.

Can you please confirm if the repo has the older version?

**Comment by RevoluPowered** [comment]
Is this fixed

**Comment by Tyriar** [comment]
Looks like it contains 1.18.1 https://packages.microsoft.com/yumrepos/vscode/

**Comment by RevoluPowered** [comment]
It does but running dnf update doesn't upgrade it to the new version, yet every other package does.

When I remove the package and reinstall it upgraded.

I also tried dnf upgrade, dnf check-update. but it wouldn't update without explicitly removing it, which made me believe that it was out of date

**Comment by Tyriar** [comment]
1.19.0 will be going out in a few hours, let me know if you experience the same issue and I'll ping the repo team.
