### ISSUE TITLE
The keybinding of "Show SCM" is inconsistent。

### ISSUE THREAD

**Issue by hujianxin** [Microsoft/vscode#39046]
"Show Explore"      -> "shift+cmd+e" -> good!
"Show Debug"        -> "shift+cmd+d" -> good!
"Show Extensions" -> "shift+cmd+x" -> good!
"Show Search"        -> "shift+cmd+f" -> good!

"Show SCM"            -> "ctrl+shift+g"  -> why?????!!!!!!

If the keybinding is like this, will be great!

```
[
{
        "key": "shift+cmd+g",
        "command": "workbench.view.scm"
    },
    {
        "key": "ctrl+shift+g",
        "command": "-workbench.view.scm"
    },
    {
        "key": "ctrl+shift+g",
        "command": "editor.action.previousMatchFindAction",
        "when": "editorFocus"
    },
    {
        "key": "shift+cmd+g",
        "command": "-editor.action.previousMatchFindAction",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+g",
        "command": "editor.action.nextMatchFindAction",
        "when": "editorFocus"
    },
    {
        "key": "cmd+g",
        "command": "-editor.action.nextMatchFindAction",
        "when": "editorFocus"
    },
    {
        "key": "cmd+g",
        "command": "workbench.action.gotoLine"
    },
    {
        "key": "ctrl+g",
        "command": "-workbench.action.gotoLine"
    }
]
```

**Comment by hujianxin** [comment]
I mean if the default keybinding like above, will be great.

I keybinding I showed above. `ctrl+g` and `ctrl+shift+g` are related to `Find Action`. `cmd+g` is binded to `goto line` which will be good to. And `shift+cmd+g`  is binded to `Show SCM ` which will be consistent with other `Show xxx` actions.

What about my opinion?

**Comment by joaomoreno** [comment]
But if you're focused on the editor then the shortcut will open the find widget.

We won't change the default. You're free to change your own keybindings.
