### ISSUE TITLE
Debugger Icon only shows up after debugger has started

### ISSUE THREAD

**Issue by Puresoft** [Microsoft/vscode#39058]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
jshint|dba|0.10.15
gitlens|eam|6.1.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.23
docthis|joe|0.6.0
markdown-shortcuts|mdi|0.8.1
vs-deploy|mkl|11.1.0
azure-account|ms-|0.2.2
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22

---

Steps to Reproduce:

1. Just open vscode, debugger icon and debug bar are not visible
2. Hit F5 and debugger is starting up
3. Icon is visible again

Reproduces without extensions: Yes

Hi, this happens since the last update on every restart of vscode.
Project is a typical angular 4* CLI project.

![image](https://user-images.githubusercontent.com/5886651/33188397-da7e32ee-d099-11e7-990b-30d44d04f844.png)

**Comment by weinand** [comment]
Did you disable the debug view via the context menu?
![2017-11-23_22-18-12](https://user-images.githubusercontent.com/1898161/33188712-47bfc8f2-d09c-11e7-9f25-42c9629b25d4.png)

If yes, then the debug view (and its icon) appears when you start a debug session (F5).

**Comment by Puresoft** [comment]
Mmmmm, definitely not on purpose but you are right.

Sorry for that.
