### ISSUE TITLE
request: more customization of build task presentation

### ISSUE THREAD

**Issue by liamstask** [Microsoft/vscode#39064]
I'm using the C++ extension on version 1.18.1 and have successfully set up a default build task. I'd like to further customize it:
* add an option to `presentation.reveal` to only present the output panel if there's an error, as detected by the selected problemMatcher - if my build succeeds I'd rather not pop up the panel.
* add an option to `presentation` to specify the tab in the panel that is shown, if it is revealed - in my case I'd like to show the `Problems` tab rather than the `Terminal` tab (can always switch over to the terminal for more detail if needed, but Problems tab is quicker to skim)

These options aren't currently listed at https://code.visualstudio.com/Docs/editor/tasks but please let me know if there's another way to achieve this. Thanks for listening!

**Comment by dbaeumer** [comment]
I have two separate issues already requesting these features. I will mark the issue as a duplicate.
