### ISSUE TITLE
"Go to File" limited to recently opened files

### ISSUE THREAD

**Issue by ScoutsOut** [Microsoft/vscode#39061]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
EditorConfig|Edi|0.11.1
ReactSnippetsStandard|Tim|1.1.0
html-css-class-completion|Zig|1.14.0
vscode-caniuse|aka|0.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
vscode-new-file|dku|4.0.0
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.10
vscode-colorize|kam|0.6.9
atom-keybindings|ms-|3.0.2
vscode-template-literal-editor|pli|0.8.4
vscode-icons|rob|7.18.1
ignore-gitignore|stu|1.0.1
vscode-import-cost|wix|2.5.1
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.7.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. CMD + P
2. Search for any file that has not been recently opened/accessed

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@VeteranPatriot what is the issue?

**Comment by iamstevendao** [comment]
@VeteranPatriot were you trying to search a file which is in your  `.gitignore` and you enabled `search.useIgnoreFiles : true`?

**Comment by itomek** [comment]
Hi, I am having the same exact issue. For instance I have the following files in the current open folder:

- vault-dashboard
    - vault-dashboard.component.html
    - vault-dashboard.component.scss
    - vault-dashboard.component.spec.ts
    - vault-dashboard.component.ts
- vault-item-share
    - vault-item-share.component.html
    - vault-item-share.component.scss
    - vault-item-share.component.spec.ts
    - vault-item-share.component.ts

and I recently opened `vault-dashboard.component.ts` but *NOT* `vault-item-share.component.ts`...

When I use *Go to File* to search and type in "vault" I only see "vault-dashboard.component...." files listed. This happens for all files in open folder.

**Comment by itomek** [comment]
Here is a video of the issue being reproduced: https://1drv.ms/v/s!AsWzMHwD7gfb8RwKTBdVTs6c64f7

**Comment by roblourens** [comment]
Does it still happen if you enter `"search.useRipgrep": false`?

**Comment by chrmarti** [comment]
@itomek Could you share your settings? Does this only occur with these two subfolders or also others?

**Comment by itomek** [comment]
@roblourens that seemed to have fixed it.

@chrmarti 
`{
    "editor.minimap.enabled": false,
    "workbench.colorTheme": "One Dark Pro",
    "terminal.integrated.shell.osx": "/usr/local/bin/bash"
}`

**Comment by roblourens** [comment]
`"**.*.trx": true` That's right, ripgrep doesn't allow patterns like that. 

@chrmarti In text search, an error message would pop up, but we don't have anywhere to surface messages like that in quickopen.

**Comment by itomek** [comment]
Thank you everyone!

**Comment by chrmarti** [comment]
@roblourens Ripgrep's exit code has changed to 1 in this case. We ignore that exit code because we assume it means no results were found.

**Comment by roblourens** [comment]
The handling for this in text search is: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/ripgrepTextSearch.ts#L124

If there were no results, and there was some stderr output, and the stderr matches a whitelist of error messages, then return that as an error.

**Comment by roblourens** [comment]
I only see the message in a single folder workspace...
