### ISSUE TITLE
Bash command to move to end of line (ctrl + e) does not work as expected. It opens a command bar instead

### ISSUE THREAD

**Issue by dpaulino** [Microsoft/vscode#39062]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 3.10.0-693.5.2.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
bash-beautify|sha|0.1.1

---

Steps to Reproduce:

1. Open terminal 
2. Press ctrl+e

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
To get this working you will either need to:

a. Redefine `terminal.integrated.commandsToSkipShell` in your settings and remove `terminal.integrated.commandsToSkipShell`
b. Unbind quickOpen in your keybindings.json:

```js
{ "key": "ctrl+e",                "command": "-workbench.action.quickOpen" },
```
