### ISSUE TITLE
Can't deselect text by clicking on it

### ISSUE THREAD

**Issue by ctusch** [Microsoft/vscode#39065]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|0.10.0
vscode-icons|rob|7.18.1
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Select text in the editor.
2. Try to deselect the text by clicking on it.

I can only drag and drop the text. Releasing the mouse button in place does nothing. To deselect I have to click on unselected text. When all text is selected I can only deselect by pressing escape. I don't have this issue in other programs.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/issues/28636, please drop more info there, thanks!
