### ISSUE TITLE
vscode更新后，打开文件cpu过高

### ISSUE THREAD

**Issue by zhangshuaidan** [Microsoft/vscode#39068]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
prettier-vscode|esb|0.26.0
auto-rename-tag|for|0.0.15
sublime-keybindings|ms-|3.0.3
vetur|oct|0.11.3
view-in-browser|qin|0.0.5

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
