### ISSUE TITLE
can not built

### ISSUE THREAD

**Issue by GitSoftwareNow** [Microsoft/vscode#39079]
when I built the vscode it say 

[root@localhost vscode]# yarn run watch 
yarn run v1.3.2
$ gulp watch --max_old_space_size=4096
[12:42:58] Node flags detected: --max_old_space_size=4096
[12:42:58] Respawned to PID: 20425
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by joaomoreno** [comment]
What is your OS? Have you tried cleaning the whole repo and install all dependencies again? `git clean -xfd . && yarn`

**Comment by GitSoftwareNow** [comment]
os is Redhat linux  CentOS I tried git clean -xfd . && yarn
nfo "windows-process-tree@0.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/12] ⠂ gc-signals: GET https://atom.io/download/electron/v1.7.9/SHASU
[6/12] ⠄ node-pty: GET https://atom.io/download/electron/v1.7.9/iojs-v1
[3/12] ⠄ keytar: https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.t
[4/12] ⠄ native-keymap: http GET https://atom.io/download/electron/v1.7
error /root/桌面/vscode/node_modules/gc-signals: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /root/桌面/vscode/node_modules/gc-signals
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | linux | ia32
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at _errnoException (util.js:1024:11)
gyp ERR! stack     at TLSWrap.onread (net.js:615:25)
gyp ERR! System Linux 2.6.32-642.11.1.el6.i686
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/桌面/vscode/node_modules/gc-signals
gyp ERR! node -v v8.9.1





[root@localhost vscode]# yarn run watch
yarn run v1.3.2
$ gulp watch --max_old_space_size=4096
[12:42:58] Node flags detected: --max_old_space_size=4096
[12:42:58] Respawned to PID: 20425
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by joaomoreno** [comment]
Make sure you can compile `gc-signals`. In a new folder: `npm install gc-signals`. What error comes out?

**Comment by GitSoftwareNow** [comment]
npm install gc-signals

> gc-signals@0.0.1 install /root/桌面/source-read/vscode/node_modules/gc-signals
> node-gyp rebuild

make: Entering directory `/root/桌面/source-read/vscode/node_modules/gc-signals/build'
  CXX(target) Release/obj.target/gcsignals/src/gcsignal.o
In file included from /usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/8.9.1/include/node/v8.h:21,
                 from /root/.node-gyp/8.9.1/include/node/node.h:63,
                 from ../src/gcsignal.h:5,
                 from ../src/gcsignal.cc:2:
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
In file included from /root/.node-gyp/8.9.1/include/node/node.h:63,
                 from ../src/gcsignal.h:5,
                 from ../src/gcsignal.cc:2:
/root/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.9.1/include/node/v8.h:333: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/8.9.1/include/node/v8.h:350: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/8.9.1/include/node/v8.h:357: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/8.9.1/include/node/v8.h:365: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/8.9.1/include/node/v8.h:394: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/8.9.1/include/node/v8.h:396: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/8.9.1/include/node/v8.h:401: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/8.9.1/include/node/v8.h:441: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/8.9.1/include/node/v8.h:775: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/8.9.1/include/node/v8.h:800: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/8.9.1/include/node/v8.h:812: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.9.1/include/node/v8.h:838: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/8.9.1/include/node/v8.h:1187: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h:1193: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/8.9.1/include/node/v8.h:1733: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.9.1/include/node/v8.h:3198: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/8.9.1/include/node/v8.h:3839: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.9.1/include/node/v8.h:4108: 错误：函数定义未声明形参
/root/.node-gyp/8.9.1/include/node/v8.h:4164: 错误：expected unqualified-id before ‘&’ token
/root/.node-gyp/8.9.1/include/node/v8.h:4164: 错误：expected ‘)’ before ‘&’ token
/root/.node-gyp/8.9.1/include/node/v8.h:4164: 错误：expected ‘;’ before ‘&’ token
../src/gcsignal.cc:96: 错误：expected ‘;’ at end of input
../src/gcsignal.cc:96: 错误：expected ‘}’ at end of input
../src/gcsignal.cc:96: 错误：expected unqualified-id at end of input
../src/gcsignal.cc:96: 错误：expected ‘}’ at end of input
/root/.node-gyp/8.9.1/include/node/v8.h:3305: 警告：使用了内联函数‘void* v8::Object::GetAlignedPointerFromInternalField(int)’但从未定义过
make: *** [Release/obj.target/gcsignals/src/gcsignal.o] 错误 1
make: Leaving directory `/root/桌面/source-read/vscode/node_modules/gc-signals/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-642.11.1.el6.i686
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/桌面/source-read/vscode/node_modules/gc-signals
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gc-signals@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gc-signals@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-29T05_35_21_757Z-debug.log
[root@localhost vscode]#

**Comment by joaomoreno** [comment]
OK great, please file an issue in https://github.com/Microsoft/node-gc-signals
