### ISSUE TITLE
References not working, keep on loading...

### ISSUE THREAD

**Issue by github-ganesh** [Microsoft/vscode#39076]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 
![image](https://user-images.githubusercontent.com/21304821/33195430-7690746c-d12b-11e7-830c-6352d7d0651c.png)

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.11.1
tslint|eg2|1.0.23
task-master|ian|0.1.39
vscode-nuget-package-manager|jmr|1.1.5
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
java|red|0.14.0
vscode-gulp|tan|0.0.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
From `IEnumerable`, I suspect this is C#. Please file this in the appropriate extension repository. https://github.com/OmniSharp/omnisharp-vscode
