### ISSUE TITLE
Terminal is frozen.

### ISSUE THREAD

**Issue by JonnyBeoulve** [Microsoft/vscode#39073]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by cleidigh** [comment]
@JonnyBeoulve 
Can you provide more information.  Sequence to reproduce, consistency, behavior after disabling all extensions, et cetera.
