### ISSUE TITLE
Seperate headers and source files via virtual folder

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#39072]
- VSCode Version: 1.18
- OS Version: Fedora 27

If C++ is detected in the file explorer add a virtual folder to separate headers and source files. Example is shown in picture.

Main goal is to keep file explorer clean.
![vscode](https://user-images.githubusercontent.com/24485362/33193072-ad417f06-d08b-11e7-96cd-bcbedf1d3a8a.png)

Reproduces without extensions: Yes/No

**Comment by kobalicek** [comment]
Should be opt-in, please don't make this by default.

**Comment by Gruntfuggly** [comment]
Try this:
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.virtual-folders

It's not perfect, but it does the job.
