### ISSUE TITLE
High CPU usage when opening any file

### ISSUE THREAD

**Issue by dqw** [Microsoft/vscode#39074]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
beautify|Hoo|1.1.1
intellij-idea-keybindings|k--|0.2.16
Go|luk|0.6.67
vscode-icons|rob|7.18.1
vim|vsc|0.10.5

---

Steps to Reproduce:

1.Open any file，the CPU usage  over 75%
2.Close all file， the CPU usage down to 10%
3.@rebornix When I disabled vim extension，the problem solved

Reproduces without extensions: No
![1](https://user-images.githubusercontent.com/1411456/33202656-51ce024a-d138-11e7-8fd4-d9b65787da25.png)
![4](https://user-images.githubusercontent.com/1411456/33202747-9a409380-d138-11e7-8675-fbe0653dfc90.png)
![2](https://user-images.githubusercontent.com/1411456/33202662-5603d042-d138-11e7-8989-0865bf277366.png)
![3](https://user-images.githubusercontent.com/1411456/33202665-5c2787fc-d138-11e7-8e3e-60d9530dd0f3.png)

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#2176
