### ISSUE TITLE
Debugger attached happened later than the execution at the breakpoint if I run with npm start

### ISSUE THREAD

**Issue by qiulang** [Microsoft/vscode#39078]
- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: macOS 10.13.1
- NodeJs: v8.6.0

If I used "Launch Program" configuration, the execution will stop at any breakpoint I set, which is what I want. But if I used "Launch via NPM" configuration, although I saw "Debugger attached." printing out, the execution did not stop at the breakpoint I set.  Then I realized the Debugger attached must happen after the execution running pass the breakpoint I set. 

Is this a bug or I did not set the configuration correctly?

Steps to Reproduce:

1. Let Code add npm configuration, I only changed runtimeArgs "debug" to "start"

```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "start"
            ],
            "port": 9229
        },
```
2. npm script is simple

"scripts": {
    "start": "node --inspect ./bin/www"
  },

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Your setup looks fine.
Since you've closed the issue I assume that this is now working fine for you?
