### ISSUE TITLE
[css] API/configuration to extend the CSS language server

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#39088]
https://github.com/Microsoft/vscode-css-languageservice/issues/44 wants to extend the CSS language server with a formatter.

**Comment by octref** [comment]
@aeschli Would you want to use prettier which has support for css/scss/less for this one? Vetur is using prettier and people like it.

**Comment by aeschli** [comment]
This is just about adding API so that other products can add it to the language server.
For VSCode this should come from an extension.

**Comment by octref** [comment]
Do you mean having extension contributing to the css-language-feature extension? I don't feel that complexity is needed. The real blocker is https://github.com/Microsoft/vscode/issues/41882 which doesn't handle multiple formatter as good as we do for completion items / hover. IMO a better solution should be making it possible for multiple registrations of formatters, and making the formatters selectable.

**Comment by aeschli** [comment]
It's about new language server API. See https://github.com/Microsoft/vscode-css-languageservice/issues/44 as the motivation for this request.

**Comment by octref** [comment]
I don't think this would happen any time soon, or should happen at all.

1. From https://github.com/microsoft/vscode-css-languageservice/issues/44 it seems @angelozerr still wants CSS LS to bundle a few formatters out-of-the-box, thus all formatter failure blames are on VS Code.
2. Let's say we have such a setting `css.formatter` where you can choose among an enum. How does it resolve formatting settings? Under some options in `css` (do we have to add settings for all formatters under `css.*`?) or if I'm using `css.formatter: "prettier"`, `prettier.*` options? How can users understand how the settings are applied?
3. We don't easily bundle external features/dependencies into VS Code, if the functionality is easily implementable by an extension. In this case, you can write another Language Server for CSS just for formatting.
