### ISSUE TITLE
separate settings for autoImport and Suggestions [USER SETTINGS]

### ISSUE THREAD

**Issue by saikatharryc** [Microsoft/vscode#39083]
- VSCode Version: `1.18.1`
- OS Version: `Linux 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

while accepting a suggestion its importing automatically in that file. 
while its not required. 
*suggestions and Import settings needs to be separate.*

**USER SETTINGS :**
```
 // Enable/disable auto import suggestions. Requires TypeScript >=2.6.1
  "typescript.autoImportSuggestions.enabled": true,
```

**Comment by mjbvz** [comment]
If I understand this, the new setting would just disable adding the import, however you should still see all project exported symbols in the suggestion list. Accepting one of these exported symbol suggestions would leave the code in an invalid state, so some manual fixing would be required afterwards

Is that the expected behavior here?

**Comment by saikatharryc** [comment]
as we can see this import settings is only valid for TypeScript.
but when we are using simple Express.js where i'm not writing any  TypeScript. 
in a simple `.JS` file. its performing that import action. where don't need it.

**Comment by mjbvz** [comment]
Can you please provide small code example of a case where an import is unnecessarily added? I'm still inclined to disabled global/exported symbol suggestions altogether as ` "typescript.autoImportSuggestions.enabled": true` does, rather than just disabling the addition of the import statement

**Comment by Panoplos** [comment]
I second this suggestion. I just ran into a serious bug where VS Code auto-imported `clearInterval` from `timers`, which is not the same as the browser implementation and resulted in `clearInterval` not working on timers created by the browser's `setInterval`. In fact, my experience has been pretty terrible with Auto Import so far. For instance:

1. When adding components from `material-ui` it auto imports as `material-ui/Component/Component`.
2. I do not use semicolons for line terminus. Auto Import does, breaking the code style.

**Comment by mjbvz** [comment]
But is the user experience for suggesting global symbols but not performing the auto-import when you select one of them any better? Just completing a global symbol name without any import will also break your code

**Comment by saikatharryc** [comment]
hey @mjbvz  ,
The Import happening here is not required.
This code is not TS. 
![import](https://user-images.githubusercontent.com/15653282/33472317-bbb24bd0-d697-11e7-824d-53b218860401.gif)

**Comment by Panoplos** [comment]
@mjbvz What if you enabled import as a key-combo? Like <kbd>Shift</kbd>+<kbd>Enter</kbd>?

**Comment by mjbvz** [comment]
@saikatharryc In that specific case, I think the expected behavior is not to show suggestions for `resolve` or `reject` at all. That's what ` "typescript.autoImportSuggestions.enabled": false` already does. We don't yet support parameter intellisense for cases like `new Promise((|))`
