### ISSUE TITLE
Cannot set GOPATH under tasks.options.env in tasks.json

### ISSUE THREAD

**Issue by avence12** [Microsoft/vscode#39087]
- VSCode Version: 1.18.1
- OS Version: OSX 10.11.6 

Steps to Reproduce:

1. edit tasks.json
2. Add following
```
{
    "version": "2.0.0",
    "type": "shell",
    "presentation": {
        "reveal": "always",
        "panel": "dedicated"
    },
    "tasks": [
        {
            "label": "test Golang",
            "options": {
                "env": {
                    "GOPATH": "bbbbbbbb",
                    "GO_FAKE":"ccccccccc",
                    "ZZZZ":"aaaaaaaa"
                }
            },
            "command": "env",
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
```
3. execute task and get following:
Note that `GOPATH` is missing on list.

```
> Executing task: env <
ZZZZ=aaaaaaaa
GO_FAKE=ccccccccc
.... {other environment vars}
```

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This works for me under Linux & Windows

![capture](https://user-images.githubusercontent.com/1931590/33205854-aeb9caa0-d108-11e7-95d0-f562c66281ff.png)

@isidorn can you please do me a favor and check under MacOS

**Comment by isidorn** [comment]
Here's what I get. GOPATH does not seem to get overwritten

![screen shot 2017-11-24 at 11 28 57](https://user-images.githubusercontent.com/1926584/33206479-af57ddec-d10a-11e7-97b8-1e95ec85cd93.png)

**Comment by dbaeumer** [comment]
@isidorn thanks. How do you set the GOPATH. In a .bashrc profile or similar. If so it will override the one you pass in the env.

**Comment by isidorn** [comment]
@dbaeumer I did not set it up, it was there long ago and i have no clue how it got there

**Comment by dbaeumer** [comment]
@isidorn thanks !

**Comment by avence12** [comment]
@dbaeumer @isidorn  looks like the issue only exist on OSX.

Tested on Golang standard env and find `GOPATH`, `GOROOT`, `GOBIN` are all discarded.
```
# tasks.json
{
    "version": "2.0.0",
    "type": "shell",
    "presentation": {
        "reveal": "always",
        "panel": "dedicated"
    },
    "tasks": [
        {
            "label": "test Golang",
            "options": {
                "env": {
                    "GO_FAKE":"foo",
                    "GOPATH": "gopath",
                    "GOROOT": "goroot",
                    "GOBIN": "gobin",
                    "ZZZZ":"bar"
                }
            },
            "command": "echo $GO_FAKE $GOPATH $GOROOT $GOBIN $ZZZZ",
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
```

Results:
```
> Executing task: echo $GO_FAKE $GOPATH $GOROOT $GOBIN $ZZZZ <

foo bar
```

**Comment by dbaeumer** [comment]
@weinand do you have an idea if there is something special with env variable under Mac. Are they 'initialized' when a shell is spawned?

**Comment by weinand** [comment]
I do not see this problem on macOS:

![2017-12-05_14-58-45](https://user-images.githubusercontent.com/1898161/33610838-ced66db2-d9cc-11e7-8c9c-f3613991a26f.png)

**Comment by dbaeumer** [comment]
@weinand thanks. Just to clarify. `GOPATH` has not the value you set. `GOROOT` has.

**Comment by weinand** [comment]
@dbaeumer yes, I mixed up the names.

**Comment by dbaeumer** [comment]
@weinand could it be that the GOPATH is set somewhere in a .*rc or profile script on your machine. These scripts are evalutated later and if they tweak the environment again they win.

**Comment by weinand** [comment]
Since I'm setting the GOPATH in ".bash_profile" I think what we see in my case is expected:
Tasks is setting the env vars and then launching a new shell (bash in my case), that inherits the env vars and overrides GOPATH when processing the ".bash_profile".

**Comment by weinand** [comment]
Ok, we came to the same conclusion. But that does not really explain the problem @avence12 is seeing (assuming that he has not empty definitions for those variables in his ".bash_profile").

**Comment by avence12** [comment]
I did not setup `GOPATH`, `GOROOT`, neither `GOBIN` in my `.bash_profile` but the `env` section in tasks.json should override the environment variables. 

Note that I have disabled all my extensions so I expect this would be nothing to do with `Go` extension.

**Comment by dbaeumer** [comment]
Technically the env section can't override variable set by a profile or by sourcing other files into the shell. The env set in the tasks.json is set before the process / shell starts. If the shell does something different it wins. 

This seems to work for @weinand under Mac and for me under Windows and Linux. So there must be something different with @avence12 machine. @avence12 can you think of anything ?

**Comment by weinand** [comment]
@avence12 you said:
> but the env section in tasks.json should override the environment variables

That is correct, but the real problem is that the "test Golang"  task defined in tasks.json starts another shell process that reads some .*rc file which itself overrides the vars from the env section in tasks.json.
Please try to find in which .*rc file GOPATH, GOROOT, and GOBIN are set. Most likely that is the file that is processed when you run the "test Golang"  task.

**Comment by avence12** [comment]
After thoroughly investigating my profiles, I find the Golang related environment vars are cleared by https://github.com/moovweb/gvm.  I can setup correct env value after disabling it. 
Thanks for your kindly investigation.
