### ISSUE TITLE
编辑器里的文件居然不能复制到桌面

### ISSUE THREAD

**Issue by peng2013** [Microsoft/vscode#39086]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
svn-scm|joh|0.10.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
debugger-for-chrome|msj|3.5.0
prettify|whi|0.0.2
shark-angular4-generator|yan|0.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
