### ISSUE TITLE
Should allow changing font.weight to 'lighter' , may be the font rendering is not good in VS Code.

### ISSUE THREAD

**Issue by Dheerusuthar** [Microsoft/vscode#39082]
- VSCode Version:1.18.1
- OS Version:Window 10 home premium

Steps to Reproduce:

1. try to adjusting theme and fond setting
2. seeing thick and slightly bold fonts.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@Dheerusuthar can you share a screenshot?
