### ISSUE TITLE
cannot read property openconfigfile of undefined

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#39080]
- VSCode Version: 1.18.1

Steps to Reproduce:

for single file debugging which doesn't need to generate launch.json, seems only `resolveDebugConfiguration` would be called, and if for some case I'd like to abort the launch by returning undefined, it will pop up en error message `cannot read property openconfigfile of undefined`. Any idea why? Thanks.

**Comment by weinand** [comment]
duplicate of #38674
