### ISSUE TITLE
Extension Description pages do not display images

### ISSUE THREAD

**Issue by MonkeyNinja** [Microsoft/vscode#39093]
![image](https://user-images.githubusercontent.com/5145906/33206758-38cb729e-d103-11e7-9a7f-162ab3eb0a48.png)

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-caniuse|aka|0.5.3
vscode-raml|blz|3.0.1
Gradle|caz|1.1.2
vscode-svgviewer|css|1.4.3
vscode-jq|dan|0.0.18
vscode-eslint|dba|1.4.3
javadebugger|don|0.1.5
xml|Dot|1.9.2
LogFileHighlighter|emi|1.2.0
php-debug|fel|1.12.1
scriptcsRunner|fil|0.1.0
macros|ged|1.2.1
gauge|get|0.0.2
gc-excelviewer|Gra|1.1.15
live-html-previewer|hdg|0.3.0
raml|jep|1.0.1
apex|Joh|0.0.2
ForceCode|Joh|0.5.35
visualforce|Joh|1.0.2
testing-regex|jus|0.0.2
vscode-xslt-snippets|mar|0.1.0
vscode-clang|mit|0.2.2
ecdc|mit|0.11.0
easy-less|mrc|1.4.5
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.5.1
jpm33errordecoder|non|0.0.1
cs-script|ole|1.3.2
vscode-docker|Pet|0.0.22
Ruby|reb|0.15.0
java|red|0.14.0
elastic|ria|0.8.1
html5-boilerplate|sid|1.0.1
vscode-autohotkey|sle|0.2.1
vscode-hexdump|sle|1.6.0
shader-toy|ste|0.4.0
code-spell-checker|str|1.4.12
pdf|tom|0.2.0
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1. Click extensions icon
2. Click extension, observe lack of images

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Is the extension installed? Are you behind a proxy?

**Comment by MonkeyNinja** [comment]
No proxy then the images load, With proxy the images are not loading


Image below shows Fiddler of session
(1) initial request for intellisense.gif  302s to raw.gith..(see 2) , https negotiation at (3) shows Proxy auth req(407) Proxy Auth succeeds at (4) - but there is no request to r.g.c for intellisense.gif


![image](https://user-images.githubusercontent.com/5145906/33260424-af257ca4-d357-11e7-812a-0a6f1c9e4107.png)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/37783
