### ISSUE TITLE
Links are not recognised sometimes in terminal

### ISSUE THREAD

**Issue by shivammittal99** [Microsoft/vscode#39094]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
MagicPython|mag|1.0.12
python|ms-|0.8.0
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
python-extended-snippets|tus|0.0.1

---
![vscode_bug](https://user-images.githubusercontent.com/25584932/33207472-dce28cac-d133-11e7-9dd5-4f14f1237d62.gif)

Reproduces without extensions: Yes/No

**Comment by shivammittal99** [comment]
Reproduces without extensions

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36072
