### ISSUE TITLE
CallStack context for contributed commands

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39091]
Currently extension writers can contribute commands to the debug call stack context menu. However we do not allow the extensions to decide on which call stack elements to contribute, so we always show commands for all: program, thread and stackframe.

Issues around this: https://github.com/Microsoft/vscode/issues/19180, https://github.com/Microsoft/vscode/issues/36394#issuecomment-346753658
Documentation for contributing commands https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands

To solve this we could introduce a new debug context key which could allow extension writers to specify for which call stack elements they wish their commands to be shown.

An example would be `callstackType` which could have the value `program`, `thread` or `stackframe`. So the node debugger could in the toggle skipping files command specify
`"when": "inDebugMode && debugType == 'node' &&  callstackType == 'stackframe'"`

As @weinand points out a thing to keep in mind for the future is that some adapters may want to enable context menu command only for custom "types" they contribute. However this could be covered by the above proposal, the main question is should this be called "type"?

@sandy081 is there a way for contributing commands to the custom tree for extensions, and if yes coudl you point us to it just so we can compare.
@roblourens @testforstephen fyi

**Comment by sandy081** [comment]
@isidorn Custom tree views support contributing commands. Refer [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/treeView.ts#L376)

**Comment by isidorn** [comment]
This is fixed in May.
The context is called `callStackItemType`. Here's a part about it in our release notes

A `callStackItemType` context key has been introduced to control what contextual commands appear for focused items in the CALL STACK view. The following values are available:

* `'stackframe'`: when a stack frame is focused in the CALL STACK view
* `'thread'`: when a thread is focused in the CALL STACK view. Threads are shown only for multi-thread debugging.
* `'session'`: when a debug session is focused in the CALL STACK view. Debug sessions are only shown if more than on session is active.
