### ISSUE TITLE
Git modification indicators don't appear on file explorer until window gets focus

### ISSUE THREAD

**Issue by wutangpaul** [Microsoft/vscode#39098]
- VSCode Version: 1.18.1
- OS Version: Win 7 Pro, 64bit

UX issue

Steps to Reproduce:

1. Check out a git project and expand file explorer tree view
2. Modify a file and save, observe M (modified) flag beside file in tree view. 
3. Open a console in another window, navigate to project folder, git stash the change you just made
4. Without focusing back to VSC, you will see that the stash live updates the code in the open file, however the M flag remains in in the explorer tree view.
5. Focus back on the VSC window, the tree view will remove the M now.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I think "as designed".

**Comment by joaomoreno** [comment]
Code only updates its git status when it's focused. This is for both performance and conflict reasons.
