### ISSUE TITLE
Autodetect ksh / fish shell scripts using firstLine

### ISSUE THREAD

**Issue by 2-5** [Microsoft/vscode#39096]
- VSCode Version: 1.18.1

Steps to Reproduce:

1. Open shell script which has `#!/bin/ksh` or `#!/bin/fish` shebang
2. File is not automatically recognized as a Shell Script

Fix is to add `ksh` and `fish` to `firstLine` here:
https://github.com/Microsoft/vscode/blob/master/extensions/shellscript/package.json#L15

ksh - https://en.wikipedia.org/wiki/KornShell
fish - https://en.wikipedia.org/wiki/Friendly_interactive_shell

**Comment by joaomoreno** [comment]
Would you like to submit a PR?

**Comment by alexr00** [comment]
verification steps: create a new file and save it as a ksh script. The file type should be recognized as a shell script.
