### ISSUE TITLE
"workbench.editor.enablePreview": false not working anymore

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#39092]
"workbench.editor.enablePreview": false

not working anymore, which is very frustrating!!!!!!!!!

Who the hell found out this automatic closing functionality, only this tiny issue got me thinking to replace my whole editor to something else.

It does not make any sense to me.
"This setting cannot be applied now. It will be applied when you open this folder directly."

**Comment by cleidigh** [comment]
@fssrepository 
I use this function frequently, currently not having any problems on Windows 7.
Can you provide more information:
- code version, OS version, installed extensions
- steps to reproduce, behavior when all extensions disabled

**Comment by bpasero** [comment]
@fssrepository could it be that you configured this on a folder level but not workspace or global level?
