### ISSUE TITLE
Make input for console application easier

### ISSUE THREAD

**Issue by ZZYSonny** [Microsoft/vscode#39097]
Debug console can be used to watch values and program outputs. However, I can't input values to my program through it (especially for most of official language plugins). To make input possible, I have to use external console and switch between code and my program. This is really inconvenient. Since most of the feature of current debug console can be done by "debug on the left side (watch)", I have these possible suggestions (any of them might solve the problem) .

1. Add a combo box at the beginning of input of debug console. And two options are "Program", "Debug". Depending on the value chosen, the input is sent differently.

2. Add another label "Program" only shows program output and runtime error information. input from this is sent to program. While Debug console works separately. I think this is the best one.

**Comment by weinand** [comment]
Some debuggers support a "console" attribute in the launch config where you can specify an "integratedTerminal" instead of the debug console. 
The "integratedTerminal" supports program input (but it cannot be used as a REPL).
