### ISSUE TITLE
Open in terminal should open new terminal window

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#391]
Bug: Open in terminal should open new terminal window. 
I am using mac osx 10.11. I opened a terminal, with tmux .
I ssh login into remote server debug.

now, open VSCode, open some folder, choose any one file right click mouse, then choose open in terminal.

The VSCode just open new tmux screen ? what the hell...

**Comment by TurkeyMan** [comment]
I was about to report that open-terminal seems to do nothing at all on my machine (Linux).
I'm not sure what it's meant to do. I was kinda hoping it would open a terminal... ;)

**Comment by Someguy123** [comment]
For me on OSX 10.10, opening any folder in terminal half the time just creates a new tab in iTerm 2, and it's hit or miss whether it actually CD's into that folder or not.

**Comment by luisantoniojr** [comment]
Hi! I had the same issue, when i tried the option, open in terminal, with right click of the mouse on any file. I'm using vscode 0.10.5.

**Comment by sijad** [comment]
isn't better to run `open -a Terminal.app {path}` instead of using apple script and run 'cd {path}; clear'?
iTerm also supports this too
