### ISSUE TITLE
I can't use git.

### ISSUE THREAD

**Issue by kxbk100** [Microsoft/vscode#39104]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.23
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
HTMLHint|mka|0.4.0
mssql|ms-|1.2.1
cpptools|ms-|0.14.2
java|red|0.14.0
vscode-java-debug|vsc|0.3.1
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Need enough details to reproduce the issue.
