### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by marekw2143** [Microsoft/vscode#39108]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-77-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.5
csharp|ms-|1.13.1
scorpio|whi|0.0.4

---

Steps to Reproduce:
With ASP .NET Core MVC application opened, try to use code-completion -it either waits very long  with text "loading" . When run without extensions, code completion seems to suggest words which are present in currently opened file.

Doing "dotnet clean" followed by "dotnet build" does not solve the problem.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository. https://github.com/OmniSharp/omnisharp-vscode
