### ISSUE TITLE
List/Tree: introduce commands for "Open to Side" and "Open Pinned"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#39101]
We have a good set of commands for our list/tree widgets [in our system](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L26). However, these commands do not cover:
* `Ctrl/Cmd`-click to open a resource in a side-by-side editor (adopted in most places)
* `Alt`-click to force open the resource pinned (for quick open via #30530)

I think there should be new commands besides `list.select` that handle those cases. It is unclear however how to name such a generic command because after all, the target tree/list decides how to handle them. We could have something like `list.selectAlt1` and `list.selectAlt2` for the two things and adopt it, though its not easy as a user to understand the impact

The goal would be to make pinning and opening to the side configurable via keybindings editing. 

I have a feeling that once we adopt multi-select for the explorer (via https://github.com/Microsoft/vscode/issues/1023) this will be a more requested thing because we will probably have to change `Ctrl`+click in the explorer to no longer open to the side but to be used for multi select.

**Comment by nadeemkhedr** [comment]
Is this on the agenda to implement?
