### ISSUE TITLE
right click 'open with code' will open two windows

### ISSUE THREAD

**Issue by zlcnup** [Microsoft/vscode#39111]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
code-runner|for|0.8.4
mdmath|goe|2.0.7
rest-client|hum|0.16.1
latex-workshop|Jam|3.7.0
python|ms-|0.8.0
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
code-settings-sync|Sha|2.8.6
vscode-gulp|tan|0.0.4
bootstrap4-vscode|the|3.0.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@zlcnup can you share a screenshot of the 2 windows?

**Comment by zlcnup** [comment]
@bpasero  When you close all workspaces, then right click a folder, and select 'open with code'. It will popup two windows. Following is the screenshot.
![image](https://user-images.githubusercontent.com/11495192/33229281-ebd64cd4-d206-11e7-961f-baa175b41124.png)

**Comment by bpasero** [comment]
@zlcnup it looks like the first window is an "Untitled Workspace" that is being restored automatically until you explicitly close that window and either discard it or save it as workspace. Can you verify this goes away when you try that?

**Comment by zlcnup** [comment]
@bpasero 
You're right. When I save or discard the 'Untitled Workspace', it won't open two windows next time. Thanks a lot.
