### ISSUE TITLE
mssql bug

### ISSUE THREAD

**Issue by baker0611** [Microsoft/vscode#39114]
reasult cannot copy,

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.14.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.3
vs-code-xml-format|fab|0.1.5
vscode-clang|mit|0.2.2
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
