### ISSUE TITLE
Terminal does not show autocomplete suggestions in ipython/jupyter console.

### ISSUE THREAD

**Issue by toniatop** [Microsoft/vscode#39118]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic (Ubuntu 16.04)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.8.0
latex-workshop|Jam|3.7.0
sdlang|Lau|0.1.2
lualinter|dcr|1.0.3
dlang|dla|0.9.0
jupyter|don|1.1.4
Lua|key|0.0.9
python|ms-|0.8.0
cpptools|ms-|0.14.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open terminal
[1b. Install jupyter/ipython (pip install ipython )]
3. Starts ipython or jupyter console
3. Try to autocomplete anything pressing tab. For example type `import math`. In the following line type `math.[tab]` 
4. A grey box will appear, and the text is not shown. See pictures below, comparing the normal behaviour in gnome-terminal vs the vscode terminal. Also, it was working fine in 1.17 afaicr.

Gnome terminal
![selection_064](https://user-images.githubusercontent.com/5911007/33227863-418f9a44-d1f9-11e7-8e64-e8e6d2a35b09.png)
vscode terminal
![selection_065](https://user-images.githubusercontent.com/5911007/33227871-6f1ba976-d1f9-11e7-84f0-453b8d2c4cbe.png)

Reproduces without extensions: Yes

**Comment by tangorboyz** [comment]
Same here

**Comment by Tyriar** [comment]
How do I launch ipython/jupyter?

![image](https://user-images.githubusercontent.com/2193314/33900885-d4017860-df24-11e7-911b-d9d7eceabb12.png)

**Comment by tangorboyz** [comment]
you need to run pip with `sudo` if you want to install ipython globally or omit `sudo` if it would be installed it inside a virtual environment.

**Comment by toniatop** [comment]
I think that you installed ipython correctly. 
I believe that the issue is that the <python_env>/bin folder is not in your $PATH, such that it cannot find the executable `ipython`. 
A quick way to find <python_env>: 
pip show ipython
It will show a bunch of stuff and something similar to:
`Location: /home/myusername/folder/lib/python2.7/site-packages`
In that case the executable ipython is in `/home/myusername/folder/bin`. Just add the folder to $PATH.

Let me know if it helps!

**Comment by Tyriar** [comment]
Thanks for the help, I got it set up. Hey this is pretty cool autocomplete :smile: 

Seems to work for me:

![image](https://user-images.githubusercontent.com/2193314/34117023-3ba2851e-e3cf-11e7-96a3-69e1306f91dd.png)

I'm guessing this is related to themes. Could you try changing the theme (ctrl+k, ctrl+t) and see if it works on some? If so there's an issue with the theme(s) that needs to be fixed.

**Comment by toniatop** [comment]
I tried a bunch of different themes, with no luck:

![selection_076](https://user-images.githubusercontent.com/5911007/34150140-346b62d2-e4f3-11e7-93b9-a6ac783d9e02.png)
![selection_079](https://user-images.githubusercontent.com/5911007/34150226-763e3d56-e4f3-11e7-985a-8de137b62ebc.png)

(This is now in 1.19, by the way).

Let me know if I can do something on my side to further test it!

**Comment by Tyriar** [comment]
I'm a bit stumped why you're seeing it then. Could you try the theme I was using?  https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

**Comment by toniatop** [comment]
Apologies for the late answer.

Indeed, with your theme, (in dim,bright and normal) autocomplete is somehow readable!.

![selection_084](https://user-images.githubusercontent.com/5911007/34504208-cf7f4236-f068-11e7-9911-0a490669bb6f.png)
![selection_083](https://user-images.githubusercontent.com/5911007/34504184-a213ed56-f068-11e7-83c1-4b76d2a2cdab.png)

By the way, I believe that the autocomplete functionality in ipython is taken from prompt_toolkit (https://github.com/jonathanslenders/python-prompt-toolkit) and other python shells based on the same package, show the same issue (for example, https://github.com/jonathanslenders/ptpython/).

**Comment by Tyriar** [comment]
Strange how yours is coming up at white and mine is grey though :confused:
