### ISSUE TITLE
javascript indentation customization failed

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#39115]
- VSCode Version: Version 1.18.1
- OS Version: Arch linux

My user settings:

```json
    "[javascript]" : {
        "editor.tabSize": 2
    },
    "[json]" : {
        "editor.tabSize": 2
    },
```

But the indention for .js and .json files are still using 4 space indentation. What's wrong? 

Thanks a lot.

**Comment by rcjsuen** [comment]
@sgon00 Are these new files you're opening or what? You might want to want to try setting `"editor.detectIndentation": false`.

**Comment by sgon00** [comment]
@rcjsuen thank you very much for your help. That setting works very well. Actually, I tried to delete all the contents from a .js file to make it empty and then started coding from scratch in that file before. I thought that was a new file but it's not. It still remembers the indentation detection setting. After setting `"editor.detectIndentation": false.`, it works well. Thanks a lot. :)
