### ISSUE TITLE
Comment Available Selection

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#39129]
If there is a selection it would be much more productive to comment out the block of selection instead of the whole line:

**Current behaviour**
code will comment this
```ts
function Test(first: number, second: string): void { ... }
```
to
```ts
// function Test(first: number, second: string): void { ... }
```

**Requested feature behaviour**
code will comment if there is a selection (brackets are representing selection start - end)
```ts
function Test(first: number[, second: string]): void { ... }
```
to
```ts
function Test(first: number /*, second: string */ ): void { ... }
```

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.bettercomment
