### ISSUE TITLE
Build task not finishing

### ISSUE THREAD

**Issue by EagleEYErus** [Microsoft/vscode#39127]
- VSCode Version: 1.18.1
- OS Version: 10.13.2 beta 4 (17C79a)

![2017-11-25 14 09 16](https://user-images.githubusercontent.com/15634499/33230015-de4f3adc-d1eb-11e7-8802-305e8cf29e11.png)

Every time I run the build task, the script runs successfully, but it does not stop working and the task remains unsuccessful and remains running.
I think the problem is in the Mac OS beta version. On two of my devices this problem is traced and on both devices a beta version of the OS is installed. And my friends all work correctly on a stable version of the OS.

In the insider build this issue is not solved

Reproduces without extensions: No

**Comment by dbaeumer** [comment]
Dups #37846
