### ISSUE TITLE
Debugger add configuration not showing C++

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#39124]
- VSCode Version: Code - Insiders 1.19.0-insider (89b158e11cb1c3fe94a3876222478ed2d0549fc8, 2017-11-24T06:07:59.584Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.23
cpptools|ms-|0.14.2
debugger-for-chrome|msj|3.5.0
autoimport|ste|1.5.3
vim|vsc|0.10.5
markdown-pdf|yza|0.1.7

I am not shown C++ when I try to create a Debugger configuration for a new project. I have to click on install plugin, then click on the already install C/C++ plugin. Go back to Debugger and select, Create configuration for the C++ option to show up.

---

Steps to Reproduce:

1. Click on Debugger icon
2. Select "Add Configuration..."

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#1287

**Comment by weinand** [comment]
@rajinder-yadav please file C++ issues against the correct repository.

**Comment by rajinder-yadav** [comment]
@weinand I am just using the "Report issues" from vscode. I am not intimate with the project to be directing my issue. However for vscode-cpptools, I will try to remember for next time.

**Comment by weinand** [comment]
@rajinder-yadav in VS Code select the extension you want to file an issue against in the extensions view, and click on the "Repository" link:

![2017-11-25_14-16-12](https://user-images.githubusercontent.com/1898161/33230883-a9c61416-d1eb-11e7-8af8-47e983a7643f.png)

Then find the "Issues" tab and create a "New Issue":

![2017-11-25_14-20-54](https://user-images.githubusercontent.com/1898161/33230897-ed281b5a-d1eb-11e7-9902-015fb6661a52.png)
