### ISSUE TITLE
[FEAT] Moving Folded Chunk of Block

### ISSUE THREAD

**Issue by achillesrasquinha** [Microsoft/vscode#39121]
Feature Request

VSCode Version - 1.18.1
OS - Mac OS Sierra

Currently when a snippet of code has been folded, it attempts to move only the initial line using the shortcut keys to move.

![](http://g.recordit.co/UOOvL531Ci.gif)

It'd be nice if this were to move the complete folded block instead of a single line. Need to know what the community thinks of this first?

**Comment by aeschli** [comment]
Just select until the next line: That's shift + cursor down.
![image](https://user-images.githubusercontent.com/6461412/33259861-7ee02272-d35e-11e7-9097-0dad1cec4482.png)
