### ISSUE TITLE
Cannot display _ in terminal.

### ISSUE THREAD

**Issue by smallp** [Microsoft/vscode#39120]
- VSCode Version:1.18.1
- OS Version:Ubuntu 16.10
![2017-11-25 14-03-18](https://user-images.githubusercontent.com/10028968/33227922-6aa900a6-d1e9-11e7-8d6e-7a48760d7812.png)

Steps to Reproduce:

1.print `_` in bash
2.cannot display `_` but it exist.
Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
Duplicate of #38133

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/35901
