### ISSUE TITLE
[theme] Find/replace left border toggle

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#39130]
Is there a key to change the find/replace left border color?

<img width="437" alt="screen_shot_2017-11-25_at_15_39_20" src="https://user-images.githubusercontent.com/10454741/33231596-0d1fe256-d1f8-11e7-9182-91f1a27d5788.png">

- VSCode Version: 1.19.0
- OS Version: MacOs

**Comment by equinusocio** [comment]
Any update on this quick fix? :)

**Comment by rebornix** [comment]
The border color will be controlled by `editor.findWidgetResizeBorder`, if that doesn't exist, it will fall back to `editorWidget.border`.

**Comment by equinusocio** [comment]
Thank you! Is this already shipped with the latest insiders build?
