### ISSUE TITLE
eslint report error

### ISSUE THREAD

**Issue by zhouLion** [Microsoft/vscode#39131]
- VSCode Version: lastest
- OS Version: win10

Steps to Reproduce:
problems like this:
![image](https://user-images.githubusercontent.com/19882767/33231505-4436ff0c-d231-11e7-9f0f-83287808b8b4.png)
consoles:
```
file: 'file:///d%3A/codespace/vue-electron-1/src/renderer/router/index.js'
severity: 'Error'
message: '',' expected.'
at: '17,7'
source: 'js'
```

1. no matter how i fix my jscode, this line always reports this error msg.
my .eslintrc here: 
![image](https://user-images.githubusercontent.com/19882767/33231575-2c1bb7b8-d232-11e7-817f-30ab3edacee4.png)

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please share the text of the code in the screenshot. Also, does this still occur if you disable all extensions and restart VS Code?
