### ISSUE TITLE
Text rendering issues

### ISSUE THREAD

**Issue by denis4net** [Microsoft/vscode#39139]
- VSCode Version:
```
$ code -v
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```
- OS Version:
```
$ uname -a
Linux dell-laptop 4.13.0-1-amd64 #1 SMP Debian 4.13.13-1 (2017-11-16) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux buster/sid \n \l
```

Steps to Reproduce:

1. Open any file in vscode

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/2119348/33233776-bdf6a090-d22c-11e7-80fe-5396afe820be.png)

**Comment by mgoku** [comment]
I think it is duplicate of #35675

**Comment by denis4net** [comment]
Exactly! I solved this issue by disabling anti-aliasing settings:
![image](https://user-images.githubusercontent.com/2119348/33240666-e83e2ae6-d2ca-11e7-9537-e8895c97545b.png)
