### ISSUE TITLE
Questions about adding multi-root support to extension

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#39132]
I'm [planning](https://github.com/Dart-Code/Dart-Code/issues/453) on updating Dart Code support multi-root workspaces and have some questions I can't find answers to in the [Migration Guide](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs). I suspect these are common questions but don't know if they've been asked/answered before (I've tried searching, but they're somewhat difficult to search for).

## 1. Detecting when a folder becomes/ceases to be my project type

Currently I have activation events to tell Code when to load/unload my extension. With multi-root a user might have a Dart folder loaded alongside a non-Dart folder so I need to ensure I don't waste resources trying to do things for the non-Dart folder.

I figured I could just perform my own version of the search that activation events do (eg. search for any `.dart` or `pubspec.yaml` file inside each folder). However, it then occurred to me that an open workspace folder might become a Dart project later (eg. a user adds a `.dart` file to it). This means creating `fileSystemWatchers` and trying to detect when a folder becomes something I might be interested in (which is also duplication of something that already exists in Code for activation/deactivation).

If this is a common need for extensions, would it be useful to add new APIs for:

- Checking if a specific `WorkspaceFolder` meets the activation events in `packages.json`
- Events that fire when a `WorkspaceFolder` transitions from meeting those criteria to not or vice versa (without having to just create their own fileSystemWatchers on every folder and manage this manually)

(I've seen that there's `workspace.findFiles` in the migration guide, but it seems like this is going to scan the entire tree for all matching files, but seems inefficient if all I need to know is if there's any single `.dart` file - the search should be able to terminate early).

## 2. Filtering `showWorkspaceFolderPick` to relevant folders

I have commands that can be run from the command palette (for example `pub get` which is similar to `npm install`). When a user invokes this, I would previously invoke it from the workspace root. Now I need to ask the user which folder to invoke it for, but it doesn't make sense for them to select a non-Dart folder.

It would be great if we could filter this list (in my case I'd like to apply the same criteria from the activation events - only folders that contain a `.dart` file or a `pubspec.yaml`).

## 3. How long will old APIs (eg. `rootPath`) be supported?

Have you decided how long the old APIs will be supported? Migrating away is somewhat complicated for me (due to many design decisions rather than technical work) so it could be a while before Dart Code can by fully migrated.

**Comment by bpasero** [comment]
@sandy081 and @alexandrudima can maybe comment on the first question. I think an extension should configure a proper `workspaceContains` activiation pattern and not do anything else. 

As for the second question: not possible currently.

And third: probably until we decide to ship 2.0 where we can justify to remove deprecated API. But we do not have any timeframe for that yet.

**Comment by DanTup** [comment]
>  I think an extension should configure a proper workspaceContains activiation pattern and not do anything else

Currently I have these:

```js
		"onLanguage:dart",
		"onView:dartPackages",
		"workspaceContains:**/pubspec.yaml",
		"workspaceContains:**/*.dart"
```

Though probably I can get away with just the bottom two. I'm trying to avoid writing my own code to check which workspaceFolders match those, since you probably already have efficient code that does it (it seems like many extensions probably need to do this, and they shouldn't have to all write their own tree-searching code and ensure it bails out early when it finds a match).

> As for the second question: not possible currently.

Do you think it's a reasonable request? Should I raise a specific case for it?

> And third: probably until we decide to ship 2.0

Ok thanks; wanted to make sure it wasn't imminent! It's actually gone much smoother than I expect; and I reckon probably I'll be converted (at least, the major functionality - I'm ignoring concurrent debugging sessions for now) next week 👍

**Comment by sandy081** [comment]
I would request @alexandrudima to answer first question as he is much aware of how `workspaceContains` activation pattern.

**Comment by alexandrudima** [comment]
@sandy081 I don't know who adopted workspace contains to multi root, but it was not me. I believe it was @jrieken with https://github.com/Microsoft/vscode/commit/f8eb2fa3b85da6f1949887c757d916ebaa8e3094

**Comment by bpasero** [comment]
@DanTup I think the request is too specific for this use case. You are always free to bring up your own picker and ask the user for the workspace to use by checking if it is a dart workspace or not.

**Comment by DanTup** [comment]
Maybe my first point has been misunderstood. `workspaceContains` seems to work fine. My extension activate/deactivates as expected. The request is about that with multi-root there's now some additional work we need to do that we didn't before. Let's assume you open a workspace that has three folders:

1. Dart web app
2. C# Server app
3. Java app

My extension activates but now rather than just sending `workspace.rootPath` to my analyzer, I now need to figure out which of the `workspaceFolder`s are actually Dart projects to ensure that I don't start scanning the C# or Java apps. It seems like a) this is a requirement for all extensions - since the C# extension probably also doesn't want to scan my Dart or Java folder and b) this logic is effectively duplication of what Code already has inside the `workspaceContains` implementation.

Additionally, if someone adds a .dart file to the C# app then I need to inform my analyzer it *should* start scanning that folder.

So it seems like language extension authors are all going to have to write much of the same code to:

- Be able to figure out which workspaceFolders are relevant to them
- Create watchers to check if a workspaceFolder gains a file that makes it relevant to them or if it loses the last file that made it relevant

It would be much nicer if Code provided APIs that let me filter the workspaceFolder list to just those that would have activated my extension if they were loaded individually, and also events for when a workspaceFolder changes from satisfying/not sanctifying the activation criteria (or vice versa).

(Note: I haven't yet been through any of the existing multi-root language extensions to see how they're handling this; but if you think it's more straight forward than I expect and they have elegant solutions, I'm happy to dig through and try to copy them)

**Comment by alexandrudima** [comment]
@DanTup I agree with you.

But IMHO this belongs in library/utility code that can be shared between extensions via npm published node modules.

The purpose of activation events is to cover the most common lazy-activation scenarios. But sometimes, it will not cover all of them. For example, as you point out, someone opening an empty folder and then creating a certain file name will not result in the `workspaceContains` being evaluated again.

But it is always possible to activate on `*` and load a **single file**. That single file can then use `vscode` API to determine a more involved activation condition, which, when it holds, will load the rest of the extension.

**Comment by DanTup** [comment]
> For example, as you point out, someone opening an empty folder and then creating a certain file name will not result in the `workspaceContains` being evaluated again.

Actually, I assumed Code already handled this. If it doesn't, then maybe less of the code I need already exists inside Code ;-(

That said; it seems rather inefficient if all extensions are creating their own watchers across all workspace folders to be able to start/stop analyzing projects as required. For now I'm tempted to just hand this all off to my language service (my current implementation does just send all folders to it) under the assumption that probably all of the folders are Dart projects in my case and then I can avoid the watchers entirely.

On that basis, there's probably nothing more to do for this case. Maybe if other extension authors come asking the same questions in future it's worth thinking about; and for now I'll see how it goes analyzing everything (and either showing the full folder list or doing my own filtering when I need a specific folder).

Thanks for all the input!

**Comment by sandy081** [comment]
@alexandrudima Was there any conclusion on this? Do we have to make any improvements on our side?

**Comment by DanTup** [comment]
Nothing here is holding me up. I think there are some reasonable feature requests here but I'm happy if you decide they're not worth doing unless other language extensions are asking for them or also having to code around the same things.

**Comment by sandy081** [comment]
@DanTup Thanks for the summary. Will close it as there is no action to be taken for now.
