### ISSUE TITLE
Node version confusion with useWSL flag

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#39148]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17025
Steps to Reproduce:

1. Install Node on Ubuntu  (I installed 8.9.1 using nvm)
![image](https://user-images.githubusercontent.com/5593825/33239591-38e3e9e8-d2a5-11e7-9255-e847b24f797f.png)

2. Debug config
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch in WSL",
            "useWSL": true,
            "program": "${workspaceFolder}/hello.js"
        }
    ]
}
```

3: In the file `hello.js`, contents: `console.log(process.versions);`

4: Debug

![image](https://user-images.githubusercontent.com/5593825/33239598-84d8e056-d2a5-11e7-8953-a1d355da4d33.png)

It says inspector protocol is using `Node.js v9.2.0`

`process.versions` also returns `node: 9.2.0`

I expect `v8.9.1`

**Comment by CoenraadS** [comment]
Update: I must use `nvm alias default`, instead of simply `nvm use`.

**Comment by weinand** [comment]
Yes, that's expected. `nvm use` only affects the shell where it was executed and VS Code runs node in a different shell.

**Comment by CoenraadS** [comment]
Yes, it was my mistake expecting it to work like the Windows version, which only has `use`, and no `alias default`. rtfm 👍
