### ISSUE TITLE
Error: Extension ... cannot use PROPOSED API 

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#39146]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Steps to Reproduce: 
1. Import proposed Color API, as shown in the demo in #38959
2. Run extension (either in test mode or launch mode). 
3. Get an error: 
Extension 'wix.stylable-intelligence cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

I've tried to add --enable-proposed-api wix.stylable-intelligence wherever applicable, and tried 'enableProposedApi':'true' in package.json, but to no avail.
Am I missing something?

Reproduces without extensions: N/A

**Comment by jrieken** [comment]
Can you share your extension with us?

**Comment by tempit** [comment]
Gladly.
It's at https://github.com/wix/stylable-intelligence
FWIW, I'm still getting this error, but the extension works fine on users' machines...

**Comment by tempit** [comment]
Also,when trying to publish, VSCE threw an error:
Error: Extensions using proposed API (enableProposedApi: true) can't be published to the Marketplace
So I removed all the enableProposedApi, and everything still works fine except for the aforementioned error.

**Comment by jrieken** [comment]
> Error: Extensions using proposed API (enableProposedApi: true)

Yes, you cannot publish with proposed api enabled. If you want to share your extension you can can do that in via visx-bundles. 

> So I removed all the enableProposedApi, and everything still works fine except for the aforementioned error.

That flag is required for proposed api usage, the command line is only to enable proposed API for production runs (for which proposed api is usually disabled).

**Comment by jrieken** [comment]
Closing this as question

**Comment by tempit** [comment]
Thanks, but I'm not sure I understand...
1. Currently the extension is published, and uses the proposed API successfully. The only instance of this error is when I'm developing. Is that error removable somehow? It did still occur when enableProposedApi was true in package.json

2. Am I doing something wrong by having a published extension use a proposed API? What may break?
2a. Basically, all I'm doing with this API is forwarding it to your (vscode) CSS service. Is it wrong to rely on something VSCode itself relies on?

3. If I can't (shouldn't) publish my extension with proposed API usage, how do proposed parts get accepted into the main API?

**Comment by jrieken** [comment]
> Currently the extension is published, and uses the proposed API successfully. 

I don't not believe you, when you unset the flag in package.json you won't have access to proposed api. Other things, that don't rely on proposed api, will work but proposed api will not exist for you. 

> Am I doing something wrong by having a published extension use a proposed API? What may break?

Yes, that is bad and everything in your extension may break. We change proposed API as we like at our pace and with prior notice. That works with built-in extensions because we have a mono compile setup and won't push breaking changed. For external extension this doesn't work.

**Comment by tempit** [comment]
Sorry again, but what do you mean by 'you won't have access to proposed api'? 
The extension is currently accessing it successfully, without the flag being set. 
I feel like I'm missing something here...

Also, assuming I re-enable the flag in package.json, and return to sending out .vsix bundles, how do I get rid of the original error?

**Comment by jrieken** [comment]
> The extension is currently accessing it successfully, without the flag being set.

I don't think so, because you see this error: `Extension ... cannot use PROPOSED API`

**Comment by tempit** [comment]
But the functionality works as expected, the error does not seem to prevent anything.

You can check it yourself - install the extension, open .css file that has 'color:red' in it.
Change the file extension to .st.css - you can see this is Stylable now because the CSS icon is lost.
But the color square and color picker still work fine.
If you open the 'Output' tab, you can see LSP trace, including textDocument/documentColor and textDocument/colorPresentation being answered.

**Comment by jrieken** [comment]
> But the color square and color picker still work fine.

Those things aren't proposed API anymore

**Comment by tempit** [comment]
I must have misunderstood.
@aeschli said here: https://github.com/Microsoft/vscode/issues/38959#issuecomment-346568410 that it's a proposed extension, that was 4 days ago.
The types are imported in the link he provided (and my code) from vscode-languageserver-protocol/lib/protocol.colorProvider.proposed.
And, adding this code caused the original error which led to this issue (and still does).

How come this is not proposed anymore? Or did I completely mix something up?
[Great to hear it's in, BTW, we love the color squares]
And if so, back to the original issue - what causes the error I see, and how do I get rid of it?

**Comment by aeschli** [comment]
ok, sorry:
- For the vscode.d.ts api: It was proposed in 1.17, and now official in 1.18
- For the language server protocol: its a proposed protocol extension

**Comment by tempit** [comment]
Does that basically mean it's safe to use in vscode 1.18.x?
