### ISSUE TITLE
Inconsistent settings between Linux and macOS environments cause hard to track issues in the integrated terminal

### ISSUE THREAD

**Issue by didenko** [Microsoft/vscode#39145]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1
- Reproduces without extensions: Yes

## Steps to Reproduce:

1. Add an environment variable in `.bash_profile`, like this:
```bash
export MYVAR=A
```

2. Configure the integrated terminal in any setting location to set the same variable:
```js
"terminal.integrated.env.osx": {
  "MYVAR": "B"
}
```

3.  Potentially restart _VS Code_ to ensure that the configuration is in effect.

4. Open the integrated terminal and expect:
```bash
$ echo $MYVAR
B
$
```

5. See that the actual result is:
```bash
$ echo $MYVAR
A
$
```

## Analysis

It is a known problem which causes time-sink issues, like #33077 (specifically [this comment](https://github.com/Microsoft/vscode/issues/33077#issuecomment-326069347)) and hard-to replicate issues like [at the end of the issue #14973](https://github.com/Microsoft/vscode/issues/14973#issuecomment-344474035).

The integrated terminal's environment is set before its start. So the child shell in it, while executing startup scripts, overrides that environment. The specific default configuration responsible for the behavior is:

```js
 // The command line arguments to use when on the Linux terminal.
  "terminal.integrated.shellArgs.linux": [],
...
  // The command line arguments to use when on the OS X terminal.
  "terminal.integrated.shellArgs.osx": [
    "-l"
  ],
```

Note the difference between _Linux_ and _macOS_. The `"-l"` argument in is an alias for `"--login"`, which triggers execution of `bash` startup scripts.

## Questions/Requests

Why is the _macOS_ treated differently in this case?

Does it make sense to unify the behavior to non-login shell in _macOS_, given how much grief it causes?

I would certainly prefer to rid of the `"-l"` parameter in _macOS_ - it is a cleaner default. It can be, and should only be enabled by those who need it - most environments should not need it. The downside is that shell customizations will not be applied to integrated terminal's sessions.

## Workarounds

An obvious workaround is to override the offending setting at a desired scope (global, workspace, or folder), like this:

```js
"terminal.integrated.shellArgs.osx": []
```

Here is the relevant snippet from the bash manual:

_When bash is invoked as an interactive login shell, or as a  non-interactive  shell  with  the --login  option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable. The --noprofile option may be used when the shell is started to inhibit this behavior._

Note, that `--noprofile` option is not reliable as in some implementations it is applied only to interactive shells.

Another workaround is to only set the variable in `.bash_profile` if it is not set yet, like so:

```bash
export MYVAR=${MYVAR:=A}
```

That way the specific variable will not be overridden as it already has a value.

**Comment by Tyriar** [comment]
There are fundamental differences between how terminals typically behave on Linux and macOS unfortunately. The way it's currently set up I believe is closest to gnome-terminal/Ubuntu for Linux and Terminal.app for macOS. You can read about some of the history here:

https://github.com/Microsoft/vscode/issues/7266#issuecomment-328593137
https://github.com/Microsoft/vscode/issues/22971
