### ISSUE TITLE
copy something from vsc and then paste, why with style and background color

### ISSUE THREAD

**Issue by GarmitesJin** [Microsoft/vscode#39147]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.1.1
pgsql|dou|0.0.8
gitlens|eam|6.1.2
Go|luk|0.6.67
cpptools|ms-|0.14.2

---

Steps to Reproduce:
use mac book
1. copy something
2. paste

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
What program are you pasting the content into?

**Comment by GarmitesJin** [comment]
textedit， mail client or any other program of mac OS

**Comment by rebornix** [comment]
please see https://github.com/Microsoft/vscode/issues/21820 for more info.
