### ISSUE TITLE
Sync extensions for all Code installation.

### ISSUE THREAD

**Issue by thatgustavo** [Microsoft/vscode#39141]
Sync extension feature
-----------------------

Say i have some bunch of extensions and want them to be available on all my vscode installations. What do you think of providing a way to create an user account and when that user perform a new installation, login into that account and all extensions are automatically installed?

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.3.9600

**Comment by jens1o** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync does this job
