### ISSUE TITLE
Remove the copy and paste options!!!

### ISSUE THREAD

**Issue by luka-lazov** [Microsoft/vscode#39154]
Everybody is saying, never repeat yourself, it is a bad practice! So why copy and paste even exist?!

Simply remove them. This will enhance DRY principle of software development aimed at reducing repetition of software and will stop all the evil in this world. :top:  :top:  :top:

**Comment by KamranMackey** [comment]
Uh, this is a really BAD idea. And there's no way on this planet that Microsoft is going to remove those options. So this, imo, was kind of a silly issue to open dude.

**Comment by luka-lazov** [comment]
What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?What is the point of copy and paste anyway?

By the way I will close this issue. This was like a troll silly issue, but if you really think about it, I would say it was novel :smiley:
