### ISSUE TITLE
findFiles broken in Insiders?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39158]
`findFiles` in the `vscode-docker` extension appears broken with Insiders `1.19.0-insider` commit `89b158e11cb1c3fe94a3876222478ed2d0549fc8`.  In a workspace with a `Dockerfile` it now returns `undefined` in Insiders. Works fine in Stable and earlier builds on Insiders.

here's the code:
``` javascript
return await vscode.workspace.findFiles(new vscode.RelativePattern(folder, DOCKERFILE_GLOB_PATTERN), null, 1000, null);
```

https://github.com/Microsoft/vscode-docker/blob/06feefaf11b090a43cc58150b58f3963395413da/commands/build-image.ts#L9

- clone the [`vscode-docker`](https://github.com/microsoft/vscode-docker) repo
- `npm install`
- open in insiders, `F5` to run the workspace
- open a folder with a `Dockerfile` (or just open a folder and create a new file called `Dockerfile`)
- open command palette, run > docker: build image

**Comment by bpasero** [comment]
Good catch.
