### ISSUE TITLE
Does not maintain scroll position in release notes

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#39157]
- VSCode Version: Latest
- OS Version: Latest

Steps to Reproduce:

1. Open release notes
2. Scroll down
3. Switch to another tab
4. Come back

Note in the gif that the scroll position is lost on tab switch and return. "Source control" does not remain at the top.

![release-notes](https://user-images.githubusercontent.com/79215/33245245-df1b3032-d2b9-11e7-9ccb-3a694c7f760f.gif)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/34369
