### ISSUE TITLE
Regex replace not working

### ISSUE THREAD

**Issue by zaynr** [Microsoft/vscode#39159]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
xml|Dot|1.9.2
latex-workshop|Jam|3.7.0
mysql-scratchpad|jbl|0.1.1
Go|luk|0.6.67
python|ms-|0.8.0
PowerShell|ms-|1.5.1
material-icon-theme|PKi|3.1.0
convert-markdown-to-html|sak|5.8.1
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Global scope search (ctrl + shift + f)
2. Type in regex, and replace
3. Regex not working
![qq 20171127102456](https://user-images.githubusercontent.com/17906065/33248013-477f68de-d35d-11e7-8b09-4141236173b1.png)

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
@zaynr Groups are working for me for example

Regex `(extensionTreeItem)(:)` with replace terms `$1[]$2` replacing `extensionTreeItem:` with `extensionTreeItem[]:`

![image](https://user-images.githubusercontent.com/10746682/33544236-4ee876f6-d8da-11e7-9d5d-6a82b4542a91.png)

Can you please provide 
- regex 
- replace pattern
- text to be replaced
- replacement text

This will be helpful to reproduce it easily. Thanks
