### ISSUE TITLE
Autoindent doesn't trim trailing whitespaces

### ISSUE THREAD

**Issue by narutse** [Microsoft/vscode#39153]
- VSCode Version: 1.18.1
- OS Version: Debian GNU/Linux 9 (KDE 5.8.6)

When I hit return, auto indent keeps the white spaces after the original cursor into the new line after the indentation. Here is a gif on how to reproduce the behavior:
![screen](https://user-images.githubusercontent.com/15129634/33243330-ac8d685c-d2a9-11e7-9753-a536ab5bd969.gif)
Steps to Reproduce:
Repeat the following sequence:
Home -> Backspace -> Enter -> End 

To illustrate how this occurs, here is what happens when there is a text after the cursor when I hit return.
![screen 1](https://user-images.githubusercontent.com/15129634/33243421-735ccb34-d2ab-11e7-9b39-eabf206ae8d8.gif)

I tried this in other editors. In the first case, they would trim the trailing white spaces. And in the second case they would put the expression (return true; in this case) at the correct indentation. This is an issue for me because I often use the End key to get behind quotes and parentheses to find out that there are too many white spaces in between.

(I have editor.trimAutoWhitespace set to true.)

Reproduces without extensions: Yes

**Comment by PoiSoNz** [comment]
Do you mind me and my partners solving this issue for a school project? If so, could you help us on which files should we be looking for?

**Comment by rebornix** [comment]
@PoiSoNz thanks for helping us out ;) The indentation related issue might be a bit complex (too many corner cases) so I'd like to suggest you to start from https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 , how does that sound? Let me know if you need any help from me.

**Comment by rebornix** [comment]
@narutse what language are you working on? It looks like C/CPP, for which we don't have a good set of indentation rules.

**Comment by narutse** [comment]
I'm working on C++. It is probably an indentation rule issue rather than editor issue. I expect the 'correct' behavior from C++ editors that I use on coding sites and contests. I tried the same thing on Atom and it did something similar to vscode. So, I guess it's language-specific.

**Comment by rebornix** [comment]
We stop doing *smart* indent with cpp as there are too many edge cases our rough indentation rules don't cover, please keep an eye on https://github.com/Microsoft/vscode/issues/36148 . Thanks for your input on this again ;)

**Comment by narutse** [comment]
Thank you. I will check out the other thread.
