### ISSUE TITLE
Shift+Click = lose focus of selected code

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39151]
- VSCode Version: 1.19.0
- OS Version: win7x64

All clicks in the GIF, I make with the pressed Shift key:

![shift click](https://user-images.githubusercontent.com/24613274/33240437-9102ed72-d2be-11e7-86e2-2d674c608800.gif)

So, in my opinion, the third click (and sixth one) should select part of code to that place.
Where from? Well, I think it should be from the first click. It will make sense.

Instead of it, the third click with pressed Shift - makes focus of previous selected code to get lost.
Not good.

**Comment by rebornix** [comment]
Already fixed https://github.com/Microsoft/vscode/issues/28688, thanks!
