### ISSUE TITLE
Quote-mark autocompletion before comma/dot

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39150]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

If there is a comma (or a dot) right after the quote-mark you type - there will be no second quote-mark, as you expect.

![one quotemark](https://user-images.githubusercontent.com/24613274/33240333-2c28867e-d2bd-11e7-8fc1-b3b8aa0a1415.gif)

**Comment by rebornix** [comment]
Unfortunately that's part of how we decide whether to auto complete or not right now, if there is following characters after current cursor, we stop being smart about auto completion as it has high possibility that an automatic auto complete is not necessary.
