### ISSUE TITLE
List of function properties should put the Function.prototype methods at the bottom of the list

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#39160]
This is a feature request - the problem is demonstrated in this video

basically, we have  a function

```js
interface ItHook {
  (t) => any;
  foo: 3;
  bar: true
}
```

when we list the function properties, it will list the `Function.prototype` methods before it lists foo or bar, etc.

https://www.useloom.com/share/1a0f1e84083049ff8f745a3a1f17ac03

You can go to 2:53 in the video to see the problem.

https://github.com/Microsoft/TypeScript/issues/20274

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20283
