### ISSUE TITLE
中文结果无法复制（mac）

### ISSUE THREAD

**Issue by baker0611** [Microsoft/vscode#39168]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.14.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.3
vs-code-xml-format|fab|0.1.5
vscode-clang|mit|0.2.2
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
open-in-browser|tec|1.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
Pls see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
