### ISSUE TITLE
[decorators] editor.rulers don't move with a before decoration

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#39165]
- VSCode Version: Code - Insiders 1.19.0-insider (89b158e11cb1c3fe94a3876222478ed2d0549fc8, 2017-11-24T05:14:03.606Z)
- OS Version: Windows_NT x64 10.0.17046
---

This is somewhat similar to https://github.com/Microsoft/vscode/issues/28628

Originally reported https://github.com/eamodio/vscode-gitlens/issues/210

Reported by @Merryweather

>Steps to Reproduce:
>
>Note: I am not sure if the issue lies with vscode or gitlens.
>
>1. Ensure the GitLens extension is installed and active.
>1. Open a source file that has some Git history.
>1. In VSCode 'User Settings', set "editor.rulers": [140]
>Observe the ruler appears in the source tab and it is positioned correctly.
>1. Select the 'Toggle File Blame Annotations' command, provided by the GitLens extension.
>(There's a button on the toolbar at the top right of the screen)
>This will insert a panel to the left of the code. Content of the panel is, I believe, irrelevant.
>Observe that the code has been shifted to the right to accommodate the extension's panel, but the editor ruler has not moved. The editor ruler is now in the wrong position in relation to the code.
>
>Expected behavior:
>I was anticipating that the ruler would be shifted to the right, in the same way as the code.
>
>Observed actual behavior:
>The ruler remained in the same position after the extension had added a panel to the left of the code resulting in the ruler being positioned incorrectly in relation to the code.

Reproduces without extensions: No

**Comment by OmeGak** [comment]
Is there really no intention to solve this issue? It's still present and very noticeable within features like `Gitlens: Toggle File Blame Annotations`, as @dalongi showed in #90182:

> w/o gutter:
> ![image](https://user-images.githubusercontent.com/716307/156538084-dcaaea59-8c90-44ea-b634-d6143bbb681a.png)
> 
> w/ gutter:
> ![image](https://user-images.githubusercontent.com/716307/156538134-6eb78fac-bc51-44b4-bf8a-a760a74ac445.png)

@alexdima replied also in #90182:
> The problem here is that inline decorations are defined per line, so the width of each inline decoration can vary across lines. The editor lacks the understanding that all of those inline decorations align in such a way and that they push all the content to the right across all lines.
> 
> I think we would need to have special editor API for rendering these blame annotations in order to get everything working great, the current usage of inline decorations is ok, but lacks certain semantic info.

What would be the best way to launch a discussion for that special editor API?
