### ISSUE TITLE
The editor is freeze every time I try work and I do not know what's happening

### ISSUE THREAD

**Issue by raudin17** [Microsoft/vscode#39167]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
vsc-material-theme|Equ|1.1.2
mithril-emmet|Fal|0.6.1
beautify|Hoo|1.1.1
python-docs|Muk|0.8.3
vscode-python-docstring|aza|0.0.5
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|0.26.0
git-project-manager|fel|1.4.0
code-runner|for|0.8.4
code-python-isort|fre|0.0.3
live-html-previewer|hdg|0.3.0
Python-autopep8|him|1.0.2
githd|hui|1.0.0
emoji-code|idl|0.4.0
node-module-intellisense|lei|1.4.0
MagicPython|mag|1.0.12
vscode-language-babel|mgm|0.0.10
vscode-exec-node|mir|0.5.0
python|ms-|0.8.0
csharp|ms-|1.13.1
python-coding-tools|nil|1.0.1
vscode-icons|rob|7.18.1
sql-snippets|sad|0.0.4
vscode-sql-beautify|sen|0.0.4
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
JavaScriptSnippets|xab|1.5.0
plsql-language|xyz|1.1.2

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Does it reproduce with `code --disable-extensions`?

**Comment by raudin17** [comment]
Yes, but the same thing is still happening

**Comment by joaomoreno** [comment]
Are you sure? Close VS Code completely. Then, from a terminal run: `code --disable-extensions`.
