### ISSUE TITLE
i want to say,every time i press F12,then!!!!!  I can not come back,can you modify it like others

### ISSUE THREAD

**Issue by onemorningspringend** [Microsoft/vscode#39169]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.23
beautify|Hoo|1.1.1
docthis|joe|0.6.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
HTMLHint|mka|0.4.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
preview-vscode|sea|1.4.2
guides|spy|0.9.1
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
Pls see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
