### ISSUE TITLE
can't type % symbol (shift+5) anywhere

### ISSUE THREAD

**Issue by sunnyskc** [Microsoft/vscode#39164]
- VSCode Version: 1.18.1 
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Open VS Code (no extensions installed)
2. Go to any html or javascript document and try to type %, nothing happens. In fact I can't type this symbol anywhere (search, quick open, etc..) Interestingly in an HTML document it jumps the cursor between tag open and close, but I am unable to actually type the modulo symbol needed for my code.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Open your keybinding preferences. Search for `%`. There will be a command which steals that keybinding for sure. Find out where it comes from.
