### ISSUE TITLE
Application has failed to start because its side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by dr3x** [Microsoft/vscode#39161]
[StackOverflow writeup](https://stackoverflow.com/questions/47502917/cant-run-visual-studio-code-1-18-1-0-sidebyside)

- VSCode Version: VSCodeSetup-x64-1.18.1.exe
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Run VS Code
2. Observe the failure message

Reproduces without extensions: Yes

C:\Program Files\Microsoft VS Code>code
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

C:\Program Files\Microsoft VS Code>code --disable-extensions
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

**Application Event Log Error Message**
Activation context generation failed for "C:\Program Files\Microsoft VS Code\Code.exe". The setting http://schemas.microsoft.com/SMI/2011/WindowsSettings^disableWindowFiltering is not registered.<br/>
Source: SideBySide<br/>
Event ID: 79<br/>

**Using the sxstrace tool:**

    SxsTrace Trace -logfile:SxsTrace.etl

run the erroring app here...

    sxstrace Parse -logfile:SxSTrace.etl -outfile:SxSTrace.txt

**The result output to SxSTrace.txt:**

> INFO: Parsing Manifest File C:\Program Files\Microsoft VS Code\Code.exe.<br/>
> INFO: Manifest Definition Identity is (null).<br/>
> INFO: Reference: Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="&#x2a;",publicKeyToken="6595b64144ccf1df",type="Win32",version="6.0.0.0"<br/>
> ERROR: The setting http://schemas.microsoft.com/SMI/2011/WindowsSettings^disableWindowFiltering is not registered.<br/>
> ERROR: Activation Context generation failed.

**Comment by dr3x** [comment]
Wondering if there is a typo in the xml of the manifest; based on the link below, maybe there should only be a namespace on the outside wrapper and the date should be 2011 instead of 2005 (see the link below, searching under disableWindowFiltering):

https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

`sigcheck.exe -m code.exe`

	<asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
		<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
			<dpiAware>true/pm</dpiAware>
			<disableWindowFiltering xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</disableWindowFiltering>
		</asmv3:windowsSettings>
	</asmv3:application>

**Comment by joaomoreno** [comment]
Never seen anything like this. @bpasero you?

**Comment by bpasero** [comment]
@joaomoreno no did not see this before. Maybe something broken with the runtime libraries? https://support.microsoft.com/en-ie/help/2525435/prevent-the-application-has-failed-to-start-because-its-side-by-side-c

**Comment by dr3x** [comment]
Did you see my comment about the manifest?

**Comment by dr3x** [comment]
Since my system seems to have an issue with the setting, I looked at the manifest of the Code.exe component and it is different than the example at the link. 

The example shows this:

 	<asmv3:application>
    	<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">
      		<disableWindowFiltering>true</disableWindowFiltering>
    	</asmv3:windowsSettings>
 	</asmv3:application>

In the example above, the namespace is only specified 1x; in the manifest (xml snippet above in the comment thread) the namespace is specified 2x and the year is inconsistent which could cause problems in parsing the data:

`xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings"`
`xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings"`

I used this command line to dump out the manifest of the exe:

`sigcheck.exe -m code.exe`

**Comment by dr3x** [comment]
@joaomoreno - Was able to install the same version on another Windows 10 machine so only an issue on this machine.  

Tried reinstall, also tried an earlier version (VSCodeSetup-x64-1.17.2) but still doesn't run.  

I did recently install VS 2017 Community Edition (with lots of components), can't think of anything else that would affect it.

**Comment by joaomoreno** [comment]
Do you have the same issue with [vanilla Electron](https://github.com/electron/electron/releases/download/v1.7.9/electron-v1.7.9-win32-x64.zip)?

**Comment by dr3x** [comment]
Yes, same issue.

Found the manifest in their repo that may be the relevant one (and wrote up
an issue):
https://github.com/electron/electron/issues/11339

When I get a chance, I'll build it with a modified version of the manifest
and see if it makes any difference.

**Comment by joaomoreno** [comment]
Excellent!

**Comment by dr3x** [comment]
Was able to build electron and recreate the issue; when I removed the line from the manifest the issue went away.  How would I pull that patch into VS Code?

**Comment by dr3x** [comment]
@joaomoreno or @bpasero - can you point me to info on how to bring that patch into vs code? Just need to make a minor tweak to the manifest file but I'm not finding it in source...

**Comment by joaomoreno** [comment]
If you have the same issue in Electron, you have to go to https://github.com/electron/electron and fix it there. We'll get the fix upstream.

**Comment by dr3x** [comment]
I can compile both apps from source. Is there a way I can get a local fix?

**Comment by joaomoreno** [comment]
> Is there a way I can get a local fix?

I don't understand what that means. It's best if you create an issue in https://github.com/electron/electron and see if they are willing to take the fix.

**Comment by dr3x** [comment]
I just want to get it working so I can use it on my machine; don't want to
wait for the Electron fix.

Do you have the steps to pull a locally patched Electron into the VS Code
build?

**Comment by joaomoreno** [comment]
No we don't. VS Code uses Electron, so fixing it upstream is only fair. Why would we keep good fixes away from our underlying platform, which everyone could possibly benefit from?

**Comment by dr3x** [comment]
I'm just trying to get a fix now so I can use the app, can you help me with
that?

I'm talking about getting VS Code working for me while I wait for Electron
to get fixed upstream.

On Dec 12, 2017 12:58 AM, "João Moreno" <notifications@github.com> wrote:

No we don't. VS Code uses Electron, so fixing it upstream is only fair. Why
would we keep good fixes away from our underlying platform, which everyone
could possibly benefit from?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/39161#issuecomment-350986771>,
or mute the thread

**Comment by joaomoreno** [comment]
Got it! If you have our sources in disk and can launch `scripts\code.bat`, then it means there is a `.build\electron` folder in the repo. Go into it, you'll find Electron in there. This is the Electron we use for development. You can make the change there and use `scripts\code.bat` to run it.

**Comment by dr3x** [comment]
Excellent! Thanks

**Comment by bpasero** [comment]
Does this still happen?
