### ISSUE TITLE
References CodeLens not shown when there is another variable in the same name

### ISSUE THREAD

**Issue by shalomdotnet** [Microsoft/vscode#39174]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
gitlens|eam|6.1.2
tslint|eg2|1.0.23
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
vscode-multiclip|sle|0.1.3

---

Steps to Reproduce:

1. Set 'typescript.referencesCodeLens.enabled' to true.
2. Open new .ts file.
3. Enter this code:
```
class Class1 {
    static var2;

    private var1;
    private var2;
    private var3;
}
```
The result is:
![image](https://user-images.githubusercontent.com/16134688/33259829-c32af148-d366-11e7-81bf-e93305b24f13.png)

Expected behavior:
References CodeLens will shown also on line 5 (`private var2`)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/20288 upstream to track the root cause of this
