### ISSUE TITLE
FTP/SFTP is not working

### ISSUE THREAD

**Issue by sarathjasrin** [Microsoft/vscode#39170]
FTP is not working. I tried many plugins. None of them working. Same FTP working with other IDEs like PHPStorm.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.17040
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
php-debug|fel|1.12.1
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
ftp-sync|luk|0.3.3
vscode-autoprefixer|mrm|2.1.2
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Due this is not a VS Code issue create one in the repository of the [ftp-sync plugin](https://github.com/lukasz-wronski/vscode-ftp-sync). Thanks :)

**Comment by sarathjasrin** [comment]
Yes I can understand. But they could try to give basic features such as FTP connections.
