### ISSUE TITLE
Search for sub-symbols via dot-notation

### ISSUE THREAD

**Issue by pretodor** [Microsoft/vscode#39179]
I would like to request the dot-notation be supported when searching for sub-symbols in a file.

### Example:

```python
# file.py:

class C:
    x = 10
    y = 20
    

class D:
    z = 30
```

After we press `Ctrl+P` and type `@:C.` what should get returned is:
```
x
y
```

**Comment by dbaeumer** [comment]
@pretodor are you using any extension for python. If so please file the PR against that extension. If not please consider using one since the Python support we ship in the box is limited to syntax highlighting and word complete / symbols.

**Comment by pretodor** [comment]
@dbaeumer I am using the Python extension by Microsoft. But this request is not Python-specific. Here is an example in JavaScript:

```javascript
// file.js:

let o = {
    p: 10,
    m() {}
};

function f() {}
```

After we press `Ctrl+P` and type `@:o.` what should get returned is:
```
p
m
```

**Comment by dbaeumer** [comment]
For the JS example please file a separate issue. This has to be addressed by the TS extension which we ship in the box. The the Pything extension you need to file a issue against the pithing extension repository. https://github.com/Microsoft/vscode-python
