### ISSUE TITLE
perl sytax regexp literal not display properly

### ISSUE THREAD

**Issue by Antisunny** [Microsoft/vscode#39172]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.17046
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
python|don|0.7.0
tslint|eg2|1.0.23
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
code-runner|for|0.8.4
vscode-perl|hen|1.14.4
beautify|Hoo|1.1.1
rest-client|hum|0.16.1
crane|Hvy|0.3.8
phpcs|ika|0.7.0
perl-syntax|jac|0.0.4
vscode-rust|kal|0.4.2
mojolicious|kra|1.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.3
MagicPython|mag|1.0.12
vscode-apache|mrm|1.1.1
python|ms-|0.8.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
sublime-keybindings|ms-|3.0.3
sass-indented|rob|1.4.5
bash-beautify|sha|0.1.1
php-formatter|Sop|0.2.4
javascript-typescript|sou|0.0.5
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vim|vsc|0.10.5
jinja|who|0.0.8
html-css-class-completion|Zig|1.14.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. e.g. /^#/, the # will be parsed as comment
2. more and more and more and more

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
The TM token type is `string.regexp.find.perl`. 

Pls see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
