### ISSUE TITLE
Can't use "#" to find all results by symbol?

### ISSUE THREAD

**Issue by Ltre** [Microsoft/vscode#39175]
- VSCode Version: Code - Insiders 1.18.0-insider (2ab10d50163f008ada9a4aa215de8c884857ce99, 2017-11-01T05:19:21.302Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.1
vscode-markdownlint|Dav|0.12.0
jshint|dba|0.10.15
java-debug|DSn|0.0.2
EditorConfig|Edi|0.11.1
windows-explorer-context-menu|ele|2.0.0
tortoise-svn|fan|0.1.1
php-debug|fel|1.12.1
php-intellisense|fel|2.0.1
php-pack|fel|1.0.1
composer|ika|0.7.1
vscode-todo-parser|min|1.9.1
team|ms-|1.122.0
php-docblocker|nei|1.3.2
material-icon-theme|PKi|3.1.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Typing CTRL+P, and typing "#symbol" to search file results which contain symbol.
2. Then the editor shows just one result for me.

For example, I searched "#jsonOutput", then return this result.(see the picture below)

![image](https://user-images.githubusercontent.com/7886064/33261879-4d7952da-d39f-11e7-8981-b50f07d8e90e.png)

For actually, I have many files contain the symbol "jsonOutput", this symbol is a function name in PHP class.(see the picture below)

![image](https://user-images.githubusercontent.com/7886064/33262019-ce094838-d39f-11e7-8e74-0f1da41c01db.png)

But in SublimeText Editor, I can type CTRL+SHIFT+R to search by "jsonOutput", then editor shows the result "jsonOutput".  
Immediately follows above, typing RETURN on keyboard, then editor shows many results which contained "jsonOutput".
(see the picture below)

![image](https://user-images.githubusercontent.com/7886064/33262510-728d268a-d3a1-11e7-99ba-e3f8558c07ca.png)

So, I mean VS-code exits a small small bug at symbol searching. It occurs in multi-projects or multi-files.

Thank you for resolving it  :)   :+1: 

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please file this issue on the repo for the PHP extension you're using, this support comes from the extension.

**Comment by Ltre** [comment]
@roblourens 
I confirmed this bug is caused PHP extension.
However, how to find all results contain the symbol I need? 
Thx!
