### ISSUE TITLE
Allow to diff 2 files in VS Code with command line arguments

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3917]
Thinking of the following syntax that would open a new window with the 2 files diffed:

`code --diff <file1> <file2>`

**Comment by protoEvangelion** [comment]
Is there documentation for this?

**Comment by bpasero** [comment]
@protoEvangelion like what?

**Comment by protoEvangelion** [comment]
Is the syntax for this diffing feature simply: `code --diff <file1> <file2>` ?

**Comment by bpasero** [comment]
@protoEvangelion yeah see the help output:

![image](https://user-images.githubusercontent.com/900690/29527947-9b2188ce-869a-11e7-8f8f-d43e4f17caf6.png)

**Comment by protoEvangelion** [comment]
@bpasero Nice! It looks great and thanks for the quick response :)

**Comment by gayanhewa** [comment]
Does the vscode api expose an interface that lets you do this with two document objects or Uri's
