### ISSUE TITLE
Search in bad sate,

### ISSUE THREAD

**Issue by jj05y** [Microsoft/vscode#39187]
Hey, 
The search box has got into a bad state. previous search results are still present, cannot click on them.
Multiple different highlights from different searches.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.20
diff-tool|jin|0.0.1
Angular1|joh|0.2.0
python|ms-|0.8.0
csharp|ms-|1.13.1
github-issues-prs|ms-|0.9.0
typescript-javascript-grammar|ms-|0.0.24
team|ms-|1.122.0
annotator|ryu|0.10.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please include enough details to reproduce the problem. Screenshots or a gif would be very helpful too.

**Comment by jj05y** [comment]
I can't repro or provide screen shots. Just informing that it happened.

More Details:
In the search results area were the search results of two distinct searches. There were view items relating to each of the searches. Neither were clickable or had any means of interaction.
To fix I restarted the application.
