### ISSUE TITLE
Fix flatpack icon

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#39189]
There is a Visual Studio Code flatpack,

https://flathub.org/apps.html

But the icon is missing. Fixing the icon would make it look more "finished".

**Comment by urbanit** [comment]
Why is it a vscode issue?

**Comment by cossio** [comment]
Is the *vs code* flatpak. Who takes care of it?

**Comment by Tyriar** [comment]
This is not an official package, be aware that it could contain anything. We will announce if we choose to distribute a flatpak in https://github.com/Microsoft/vscode/issues/7112
