### ISSUE TITLE
Git Sidebar Filters and Sorting

### ISSUE THREAD

**Issue by imperez** [Microsoft/vscode#3918]
Forgive if this is already submitted but I couldn't find a similar ticket when I searched the issues. I love the Git integration in VSCode but what do you think about add filters to the Git Sidebar? My thought is that you have toggle buttons for different Git Statues (Added, Modified, Deleted, Confict) and then an input field that allows you to filter the list. This would make large amounts of changes such as those in a merge conflict so much easier to deal with it and finding the right file.

**Comment by Deilan** [comment]
Related: #11208 #23775.

**Comment by sean-mcmanus** [comment]
I can't view Open Changes to a document if I can't find it in the giant list. Visual Studio solves this problem by having a filename filter I can use to locate the file I'm interested in viewing changes for.
