### ISSUE TITLE
Panel: composite bar layout is called even though panel is hidden

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39185]
Steps to Reproduce:

0. start JS profile
1. open a couple of editors and the explorer
2. resize the explorer for a couple of seconds

=> notice how the PanelPart.layoutCompositeBar takes a significant amount of time even though the panel is not visible. 

Independent from this issue while the panel is hidden, you might maybe also check why this call is so expensive when the panel is visible and you have to do it.

![image](https://user-images.githubusercontent.com/900690/33267632-7f88a1a6-d37a-11e7-8a7b-df53d90260d6.png)

[CPU-20171127T135435.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1505860/CPU-20171127T135435.cpuprofile.zip)

**Comment by isidorn** [comment]
Changed the activity bar part, sidebar and panel to not layout if they are not visible.
As for your other concern I have pushed a seperate commit which I am not sure will help but the only way to improve that is to debounce the composite bar layout which I do not want to do yet. e.g in my testing after all the changes I could only get it to 180ms after 10 seconds of constant draging the sash around
