### ISSUE TITLE
Restart and Update Do Not Happen

### ISSUE THREAD

**Issue by calendee** [Microsoft/vscode#39196]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
python|ms-|0.8.0

---

Steps to Reproduce:

1. Receive notification of an update
2. Choose Update Now
3. VS Code closes and never re-opens
4. Manually re-open VS Code
5. Open Code menu option and choose "Check For Updates"
6. Start back at step 1

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
We're using Squirrel behind the scenes. In rare cases the update gets corrupted. We don't have a reproducible case for this yet. Please uninstall VS Code manually and reinstall it. Thanks!

**Comment by calendee** [comment]
Each time this happens, I manually update but it has never fixed the problem for the next update.
