### ISSUE TITLE
Search and Replace keep losing the selection

### ISSUE THREAD

**Issue by firepol** [Microsoft/vscode#39190]
- VSCode Version: 1.18.1
- OS Version: Windows 10
Steps to Reproduce:

1. Select a block of text (you want to replace occurrences of a word only in that block, not in the entire file)
2. Press Ctrl + H (Edit > Replace in files)
3. Insert a word to be replaces, and the replacement in the next input box
4. Click the "In selection" toggle (if not toggled already), eventually click it again

Expected behavior: if you toggle/untoggle the "in selection", the selection should stay. Now it's not the case.

Also if you keep the search and replace dialog open, and try to select other portions of texts to apply the same replacement, it doesn't work.

Other major editors works well for this case, but Visual Studio Code doesn't work.

See a video demo here, comparing other editors to Visual Studio Code:

https://www.youtube.com/watch?v=0MRqXJQb0Yc

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/17563 and https://github.com/Microsoft/vscode/issues/34679
