### ISSUE TITLE
vscode 1.18 "files.hotExit": "onExit" behavior

### ISSUE THREAD

**Issue by qqmech** [Microsoft/vscode#39193]
- VSCode Version: 1.18
- OS Version:10.13.1

Steps to Reproduce:

0. Previously I was running vscode (1.15). I have unsaved files in multiple tabs, I can close vscode and it doesn't ask to save.  I reopen vscode and the same tabs with unsaved files show up.  This is good, expected behavior.
1.Upgrade to vscode 1.18
2.Open vscode and it opens previous 'unsaved'(untitledx) files  - good!
3. When closing vscode it asks to save the 'untitled' files - not good.

    I checked the currently running settings file and see this
"files.hotExit": "onExit"
and there is no user override.

Thanks!

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I think you will prefer this setting:

```js
"files.hotExit": "onExitAndWindowClose"
```

This makes untitled files trigger the save dialog only when you do *not* have a folder opened.
