### ISSUE TITLE
Breakpoint marker is deleted even though the breakpoint still exists

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#39198]
_From @DatGuyJonathan on November 27, 2017 16:4_

When the user deletes a breakpoint from the UI, the marker is removed right away then the adapter gets a `setBreakpointsRequest` for that URI without that line breakpoint, so the adapter figures out the breakpoint was deleted. If the adapter fails to delete that breakpoint on the server side, my adapter sends a response that it's still a verified breakpoint. I have an adapter that needs to make a network call to create/delete a breakpoint, so it's possible a delete fails. In this scenario, the client UI says the breakpoint is deleted, but the server still has it enabled.

What's the suggested way to stop VS Code from deleting that breakpoint?

_Copied from original issue: Microsoft/vscode-debugadapter-node#139_

**Comment by weinand** [comment]
@DatGuyJonathan how does your adapter sends a response that a deleted breakpoint is still a verified breakpoint?

**Comment by DatGuyJonathan** [comment]
@weinand , here's the`SetBreakpointsResponse`:

```{"seq":0,"type":"response","request_seq":7,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"source":{"name":"ExceptionConstructs.cls","path":"/tmp/force-app/main/default/classes/ExceptionConstructs.cls"},"line":6}]}}```

**Comment by weinand** [comment]
@DatGuyJonathan this cannot work.
The breakpoints in the response array must map to the breakpoints passed to the SetBreakpointsResponse request. Since deleted breakpoints are **not** passed to the SetBreakpointsResponse request, they cannot have a corresponding result.

I suggest to create a BreakpointEvent with a 'removed' reason. That should re-create the breakpoint in VS Code.
