### ISSUE TITLE
TS arrow functions in classes break theme coloring.

### ISSUE THREAD

**Issue by nozzlegear** [Microsoft/vscode#3919]
Adding an arrow function to a TS class breaks the VSCode theme. Compare this screenshot:

![before-arrow-function](https://cloud.githubusercontent.com/assets/2417276/13641293/8111095a-e5dd-11e5-8dea-7c61de385ffc.png)

To this one, after changing the `Test` function to an arrow function:

![after-arrow-function](https://cloud.githubusercontent.com/assets/2417276/13641299/86fc9816-e5dd-11e5-8f94-068f447ed4fc.png)

I've tested this in both the Dark default and Light default theme, bug is present in both themes. It's also present in both .ts and .tsx files. I'm using VSCode version 0.10.10.

Steps to reproduce:

1. Create a new TS file and give it a class.
2. Add two normal functions to that class (i.e. `public SomeMethod() { } public OtherMethod() { }` ).
3. Change the first function to an arrow function ( `public SomeMethod = () => { }` ).
4. Theme colors on all functions below `SomeMethod` are now broken.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#119
