### ISSUE TITLE
Having one git repository opened make all the folders on a workspace to be under version control

### ISSUE THREAD

**Issue by danielo515** [Microsoft/vscode#39194]
- VSCode Version: 1.18.0
- OS Version: MacOS sierra

Steps to Reproduce:

1. Open a workspace without git control activated (no `git init`)
2. Add another workspace with git control, basically a git repository
3. Now you can see changes pending for the repository that does not have git activated

**Comment by joaomoreno** [comment]
Please provide exact steps. Give me example path names. Make sure that if a path is contained in another one, you reproduce that in the example names.
