### ISSUE TITLE
Changing the capitalization of a publisher ID

### ISSUE THREAD

**Issue by RavinduL** [Microsoft/vscode#39208]
Is there any way to change the capitalization of a publisher ID? I doubt this will break any extensions as publisher IDs are seemingly not case-sensitive.

Alternatively, is there any way to change a publisher ID _while there aren't any extensions published under it_?

**Comment by sandy081** [comment]
@RavinduL You can always rename your extension (publisher name or extension name). Market place team will help you to do that. @modigrv Can you please point the user to the doc/page where the user can request rename for.

Thanks.

**Comment by RavinduL** [comment]
@modigrv
> Can you please point the user to the doc/page where the user can request rename for.

Thanks 😄
