### ISSUE TITLE
vscode associated with file management and folders in KDE Plasma

### ISSUE THREAD

**Issue by ebastos** [Microsoft/vscode#39204]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.0-17-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
go-test-outline|Rom|0.1.4
golang-tdd|joa|0.0.9
Go|luk|0.6.67
python|ms-|0.8.0
python|tht|0.2.3
vscode-glide|vit|1.0.2

When installed with a Plasma Desktop vscode associates itself with folder management.
If Dolphin is not installed it makes vscode the primary app to manage the filesystem, which is less than ideal.

---

Steps to Reproduce:

1. Install vscode with a KDE Plasma Desktop Environment (plasma-desktop if using Ubuntu)
2. Click on the start menu, select "Computer" and then "Home"

Expected behavior: If no file managers are installed, ask to user pick application.
Actual behavior: vscode is invoked.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I think this is happening because VS Code is registered as a handler of text files and folders which it is. I'm not aware of a way to conditionally do this based on whether there is a "true" file manager.
