### ISSUE TITLE
Split integrated terminal when docked to the side

### ISSUE THREAD

**Issue by dvidsilva** [Microsoft/vscode#39209]
Feature Request. 

- VSCode Version: 1.18.1
- OS Version: mac Os High Sierra, 10.13.1

Now that the terminal can be docked to the right, there's a lot of vertical space that can be utilized. Most projects require a tasks or command to run it and we need to pay attention to the output sometimes, but also have another terminal to run other commands. So being able to see more than one at the same time can be super useful. 

<img width="2022" alt="vscode split terminal" src="https://user-images.githubusercontent.com/1588753/33291225-1aa1e900-d393-11e7-9aa1-c294ae7b6065.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7504
