### ISSUE TITLE
Doc bug on python debugging page

### ISSUE THREAD

**Issue by breathe** [Microsoft/vscode#39200]
https://code.visualstudio.com/docs/python/debugging

Recommends using deprecated ${config.} property

> Points to the Python interpreter to be used for debugging purposes. The standard configuration uses the interpreter identified in the python.pythonPath setting by referring to ${config.python.pythonPath}. To use a different interpreter, specify its path instead.

This property is marked as deprecated by vscode:

<img width="362" alt="screen shot 2017-11-27 at 9 56 06 am" src="https://user-images.githubusercontent.com/434034/33278594-3d9a9482-d359-11e7-9d94-ce5106f6fe79.png">

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1274
