### ISSUE TITLE
Adding extensions to vscode which was built from source (Windows)

### ISSUE THREAD

**Issue by OferRosenberg** [Microsoft/vscode#39205]
Hi,

I've managed to build the win32-x64 version of vscode. the application is working good, I'm managing to open files/folders/etc. However, unlike the pre-build version which exists on https://code.visualstudio.com/ , the extensions tab is empty - see attached picture. 

![vscode_extension](https://user-images.githubusercontent.com/33768003/33282192-c03bcf48-d35c-11e7-993a-9136f0cb3339.JPG)

Is there some configuration to point the app to the extension ? (and the marketplace)

Thanks,
Ofer

**Comment by maxibanki** [comment]
To enable the extension market you need to add: 
```json
  "extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	},
```
to your `product.json` file. :)

**Comment by kieferrm** [comment]
The extension marketplace may not be accessed by a non-product version of VS Code.
