### ISSUE TITLE
Not possible to adjust vertical size of activity bar items. Please provide a way to do it incl. bindable action.

### ISSUE THREAD

**Issue by petval** [Microsoft/vscode#39210]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063

I find it very strange that it isn't possible to change the heigth of activity bar panes. It's really annoying to have to scroll up and down when I have so many files open that I don't see all the file tabs. 

Please provide a way to adjust the width. It doesn't make sense to have fixed height, there is a lot of unused space especially if after panes are collapsed.

Pic for clarity, arrow indicates where the increase/decrease height functionality should be available. It would be awesome if you also provide action to switch between expanding the height to fill all the unused space and collapsing to the default height so we could bind a hotkey.

Steps to Reproduce:

1.  Open cca 8+ files
2.  Try to increase the heigth of the 'Open editors' pane.

![image](https://user-images.githubusercontent.com/7311676/33290921-867fa0aa-d3c4-11e7-991a-02b0e479d2e0.png)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
dup of https://github.com/Microsoft/vscode/issues/491
