### ISSUE TITLE
Not possible to use arrow keys when renaming file

### ISSUE THREAD

**Issue by kohlikohl** [Microsoft/vscode#39211]
- VSCode Version: Code - Insiders 1.19.0-insider (3c470706ded48fc75c05f86bc4f9c7b0f4d6c708, 2017-11-27T06:07:45.718Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
prettier-vscode|esb|0.26.0

---

Steps to Reproduce:

1. Go to a file you want to rename
1. Hit ENTER to switch into the rename view
1. use left/right arrow keys to attempt to move cursor between letters
1. cursor does not move, instead the folder tree is opened/closed

![renaming](https://user-images.githubusercontent.com/1196216/33292190-25a06806-d37d-11e7-9564-a05e058eca22.gif)

Reproduces without extensions: Yes

**Comment by delgermurun** [comment]
Couldn't type `o` character also (although I didn't tested every key).

**Comment by SEAPUNK** [comment]
i think it assumes that we're passing in a keyboard shortcut command (pressing `a` stops the new folder creation dialog and starts a new file creation dialog)

**Comment by bpasero** [comment]
@joaomoreno this sounds like a regression from your list service changes

**Comment by SEAPUNK** [comment]
It broke again.

Version 1.19.0-insider (1.19.0-insider)
d8989c95964ce06c64ffebc2fb400a0327bd447d
2017-12-08T10:04:48.458Z

**Comment by SEAPUNK** [comment]
Repro is not the same as OP, though: Arrow keys seem to work, but pressing letters (e.g. `a` perform actions instead of entering the letter 'a').

**Comment by bpasero** [comment]
@SEAPUNK what action did you configure for `a`? Do you have any VIM extension installed?

**Comment by Narkoleptika** [comment]
I can confirm that it broke again. In addition to a, h, j, k, l, and backspace don't work while naming a file or folder.

- VSCode Version: Code - Insiders 1.19.0-insider (d8989c95964ce06c64ffebc2fb400a0327bd447d, 2017-12-08T10:09:06.896Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.6
html-snippets|abu|0.1.0
calculate|aca|1.1.1
project-manager|ale|0.23.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
octobercms-template-language|dqs|0.2.1
gitlens|eam|6.3.0
vscode-html-css|ecm|0.1.8
php-debug|fel|1.12.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
MagicPython|mag|1.0.12
vscode-apache|mrm|1.1.1
mssql|ms-|1.2.1
python|ms-|0.8.0
atom-keybindings|ms-|3.0.2
azure-account|ms-|0.2.2
cpptools|ms-|0.14.3
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vetur|oct|0.11.3
vscode-icons|rob|7.18.1
vscode-nginx|sha|0.4.1
code-spell-checker|str|1.5.1
language-stylus|sys|1.8.0
vscode-todo-highlight|way|0.5.11
jinja|who|0.0.8
change-case|wma|1.0.0
markdown-all-in-one|yzh|0.11.2

(1 theme extensions excluded)

**Comment by joaomoreno** [comment]
I've submitted https://github.com/VSCodeVim/Vim/pull/2213 which will fix it for the VIM users.

The correct `when` clause to use now is: `listFocus && !inputFocus`.

**Comment by SEAPUNK** [comment]
@bpasero I'm using atom keybindings.

**Comment by joaomoreno** [comment]
Oh, it seems @auchenberg already fixed this in https://github.com/Microsoft/vscode-atom-keybindings/issues/44, for the Atom keybindings. Thanks @auchenberg!
