### ISSUE TITLE
Show line number on search

### ISSUE THREAD

**Issue by yuric18** [Microsoft/vscode#39219]
Hi, I would like to request the feature of showing the archive line number next to the code found when I search some piece of code. I think it could be added as a setting such as `"search.lineNumbers: "on"||"off"` just like `"editor.lineNumbers"` setting. Do you guys think that is possible?

Just an example below:
![image](https://user-images.githubusercontent.com/18277197/33296176-0665e364-d3c1-11e7-80da-c43d4340e725.png)

**Comment by roblourens** [comment]
Reasonable request, but since the viewlet is so narrow, it would have to take up horizontal space or get cut off.

**Comment by yuric18** [comment]
What if it's enabled automatically when expanding the viewlet? Just like the extension icons and other info? Just like below.

![image](https://user-images.githubusercontent.com/18277197/33333596-671edb74-d44e-11e7-9b4e-3c73c556304a.png) 
![image](https://user-images.githubusercontent.com/18277197/33333617-7431ae22-d44e-11e7-820a-f5381c1d5645.png)

**Comment by dan-h-ch** [comment]
+1 for this - moving over from another IDE I use this to quickly ascertain if results are in same method so I don't have to worry.

**Comment by adammhaile** [comment]
+1 as well. It's the one thing I miss from Atom

**Comment by zhaoterryy** [comment]
+1

**Comment by gianlucaborello** [comment]
I probably spend 30% of my vscode time navigating through search results like a maniac, so having line numbers would be a terrific productivity improvement, especially now that we have `"search.location": "panel"`. Thanks!

**Comment by vresch** [comment]
+1 After Atom looks like an obvious functionality

**Comment by rob-ubnt** [comment]
+1 for this. JetBrains does this and it's incredibly helpful.

**Comment by onqtam** [comment]
how to get this to work?

I got the version from 3 days ago and cannot find the option

**Comment by RMacfarlane** [comment]
@onqtam The setting is `search.showLineNumbers`. This is available in the current insiders version, 1.29. You can download the insiders version or wait until our monthly release next week
