### ISSUE TITLE
Icon color is still wrong in a couple places.

### ISSUE THREAD

**Issue by jmkulwik** [Microsoft/vscode#39217]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

Right click on the icon
![wrongcolorvscode2](https://user-images.githubusercontent.com/8324574/33295878-17d24f9a-d38d-11e7-8a4d-fae831e7c789.PNG)

Search for VS Code in the Start menu
![wrongcolorvscode1](https://user-images.githubusercontent.com/8324574/33295879-17e64bc6-d38d-11e7-9a97-ca5b8a742b49.PNG)

1. See the above pictures

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
@jmkulwik The OS caches application icons and sometimes hangs on to the old ones. The easiest is to open the properties of the executable, go to the Shortcuts tab, and Change the Icon. This invalidates the cache and you should see the change being picked up everywhere.  This is easier than trying to flush the icon cache as described here: https://github.com/Microsoft/vscode/issues/36665#issuecomment-339230850.
