### ISSUE TITLE
JavaScript highlighting broken after template string.

### ISSUE THREAD

**Issue by martinbilles** [Microsoft/vscode#3921]
Syntax hightlighting for JavaScript breaks if a variable used inside a template string escape sequence starts with the characters "var":

```javascript
var objid, varname;
{
    console.log(`${objid}.${varname}`);
}
thisPartIsWrong();
```

Here, the variable name ```varname``` is incorrectly highlighted, the "var" part is highlighted in the keyword color, while the rest of the variable name is colored correctly. After the template string, all remaining code is colored in the string color.

![vscode-highlighting-bug](https://cloud.githubusercontent.com/assets/5391834/13643515/9a63e41a-e621-11e5-92c9-a050cb167492.png)

This is only true if the variable's name starts with "var" or "let". If any other keyword is used, e.g. "constname", "ifname", there is no error. if there is no wrapping block statement around the code containing the template string, the error also doesn't appear.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#120
