### ISSUE TITLE
intellisense or code search for workspace, the preferable behaviour is that for the grep to only search within the same folder rather than across all folders in workspace, or make it configurable :)

### ISSUE THREAD

**Issue by joycechangeorg** [Microsoft/vscode#39215]
- VSCode Version: 1.18.1
- OS Version: 10.13.1

Steps to Reproduce:

1.  open a workspace and add some folders 
2. open up editor for one of the codes inside one of the folders, try to find references.  If the other folders are irrelevant, code search will still search inside the other projects.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Which language are you working in? Can you please provide a small example project or description of your code structure?

**Comment by joycechangeorg** [comment]
I'm working in Python.  In my workspace, I have more than a couple directories representing different code bases (different repos) opened in Visual Studio Code.  I was trying to do a find references in one of the class names, and then VSC spends a very very long time looking for it even though the class is in a file in the same repo.  But if I just have a workspace with just that repo opened, then it returns results immediately.

**Comment by mjbvz** [comment]
Please file an issue against the python extension: https://github.com/Microsoft/vscode-python/issues
