### ISSUE TITLE
API request: support overriding editor.wordSeparators on a per-file type basis

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode#39218]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.2.1

**Notes**
This is an API change request. 
- We've had 2 issues [143](https://github.com/Microsoft/sqlopsstudio/issues/143) and [224](https://github.com/Microsoft/sqlopsstudio/issues/224) opened against SQL Operations Studio that reflect this, but it also applies to the `MSSQL` extension in VSCode which has the same limitation.
- Essentially the `@` character is expected to be part of the word for .sql files but in most others it's fine to treat as a separator. 
- The request is to support extensions defining a per-language word separator list to override the default. 

Steps to Reproduce:

1. Install the MSSQL extension 
2. Open a .sql file and type in `DECLARE @var int;`
3. double-click on @var, only 'var' is selected

**Comment by jrieken** [comment]
You do that when contributing a language: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages. There the `wordPattern` field that allows to define a regular expression for this. Also, when asking a document for a word, you can provide a word pattern to be used.

**Comment by kevcunnane** [comment]
@jrieken thanks - this is a great place for us to start looking. Will see if we can make changes there. I'll close this for now and reopen if we find blockers.
