### ISSUE TITLE
Programmatically closing textDocuments in VSCode

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode#39214]
At present, we use temporary files to show temporary json results. We dispose these resources in the dispose function to ensure we don't have too many temp files created. 

However, this leads to a side-effect on restarting VSCode - we get a error messages of not being able to locate the temp files. Issue logged [here](https://github.com/Microsoft/vscode-cosmosdb/issues/226).  

I came across [this commit](https://github.com/Microsoft/vscode/commit/d625b55e9ec33f95d2fe1dd7a4b7cb50abb4772c#diff-4654cd1aa2a333bc6cc7ca0d19fdfb6e) on the GitHub repo, saying that we cannot programmatically close textDocuments. 

I came across [a hack](https://github.com/eamodio/vscode-restore-editors/blob/17e0217bd20f6d08bb5ada6cf265b9423fdad47e/src/documentManager.ts#L35) using workbench and `vscode.command.executeCommand`, mentioned in #15178. 
This seems more over-reaching than for our use-case (remove temp files from editor tab on window close). 

Is there a way to dispose these resources nicely (on top of merely deleting the files in the dispose method) so that VSCode has a smoother experience? 

- VSCode Version: 1.1.9.0
- OS Version: Windows 10 Creators Update

Steps to Reproduce:

1. Open a workspace
2. Create two files, save both of them. 
3. While VSCode is open, reveal each of them on Finder/Explorer/Nautilus
4. Delete both these files.  
5. Reload the VSCode instance. 

Expected : 
VSCode is aware of the files that are deleted, and does not prompt the user. 

Actual : 
Prompts the user about the temp files. 

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
> Is there a way to dispose these resources nicely 

No, we do not allow to close/dispose resources. 

> At present, we use temporary files to show temporary json results.

This sound like a use-case for virtual documents for which you just provide the contents and which lifecycle is lighter. See https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1434

**Comment by PrashanthCorp** [comment]
> This sound like a use-case for virtual documents for which you just provide the contents and which lifecycle is lighter. See https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1434

Thanks for the suggestion! Unfortunately, we need to display editable documents (read-only would not suffice here). 

Is there a way to view the set of editor tabs within a ViewColumn? I see #15178 asking about the same thing. 

More Info - 
- The documents are read-write, [link to code](https://github.com/Microsoft/vscode-cosmosdb/blob/840130b908c9e350a29b9d181a736db2498dea5a/src/util.ts#L47). 
- They are meant to be [temporary](https://github.com/Microsoft/vscode-cosmosdb/blob/840130b908c9e350a29b9d181a736db2498dea5a/src/DocumentEditor.ts#L24)

**Comment by jrieken** [comment]
Sounds like a scratch-pad use case. Editable, volatile documents and editors... Needs some thinking... Until then I'd stick with the close-all-command

**Comment by changsi-an** [comment]
Would like to have this feature too. We will open some document from a debug session that dose not necessarily have files back them up on the local file system. After the debug session terminates, it does not make sense to display those files. It just cause more troubles leaving them there. 

I want to be selectively close some of the tabs.

**Comment by jrieken** [comment]
A while back we have added [`FileSystemProvider`](https://github.com/Microsoft/vscode/blob/b07b57d9119030ca50ff55f816674e3addc448b7/src/vs/vscode.d.ts#L5316)-APIs that allow to implement this.

**Comment by bcherny** [comment]
@jrieken Following up on this - what's the right API to use to close a tab I created with `executeCommand('vscode.previewHtml', uri, displayColumn)`?

Code is here: https://github.com/bcherny/better-asciidoctor-vscode/blob/3d376d82525544b910fcd4c09b1904a3f1abddc0/src/AsciiDocProvider.ts#L86
