### ISSUE TITLE
Ability to perform find/replace only for open documents

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode#39220]
VSCode appears to support find/replace for the following:

- Current document
- Selection within current document
- Files in a particular folder(s) (with optional exclude filters)
- Files in entire project (with optional exclude filters)

This is great, but one thing seems missing--the ability to search "all open documents" (as you can with Visual Studio).

Is this possible? If not, could you please consider this a feature request?

**Comment by roblourens** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/20530
