### ISSUE TITLE
Markdown in cpptools CHANGELOG.md is rendering incorrectly.

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#39225]
- VSCode Version: 1.18.1
- OS Version: Windows.

Steps to Reproduce:

1. Click the Changelog tab in the C/C++ extension page.

Bug: The 1st line renders as
﻿# C/C++ for Visual Studio Code Change Log

When we view our markdown via the Markdown: Open Preview it renders correctly. I don't think our extension could be causing this, although I couldn't find any other extension that was having this problem. The text we use is just `# C/C++ for Visual Studio Code Change Log`. This used to work for us. We haven't done anything new except add additional lines to the file.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I believe this is caused by the BOM (char code 65279) at the start of your changelog. Please try removing this

**Comment by sean-mcmanus** [comment]
Thanks -- yeah, the encoding somehow got changed to UTF-8 with BOM in the past month.
