### ISSUE TITLE
C#: Intellisense Autosuggests in Comment Summary Block

### ISSUE THREAD

**Issue by garethwarry** [Microsoft/vscode#39228]
**Versions**
- VSCode Version: 1.17.2
- OS Version: Windows 10
- OS Build: 15063.674

**Summary**
C# supports XML comment blocks without XML tags (assumes summary). This was not taken into consideration, as intellisense attempts to autocomplete words with XML keywords. This makes commenting extremely difficult. Intellisense does assume summary block correctly when hovering over an identifier.

**Expected**
From MSDN on language specification: "Note that if you do not specify a summary tag explicitly, you should not specify other tags, such as param or returns tags."

**Steps to Reproduce**
1. Write a comment block with /// and without XML tags.
2. When pressing . (period), auto-complete suggests XML tags.

```
/// Start listening for incomming connections from the client. For each
/// client, create a new accept callback to asynchronously process 
/// data packets. Checks reset event for server closing.
```

**Reproduces without extensions:** Yes

**Comment by kieferrm** [comment]
I was unable to reproduce the problem with a vanilla VS Code install. Pls file the issue against https://github.com/OmniSharp/omnisharp-vscode/issues.
