### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by rtalwar26** [Microsoft/vscode#39229]
## I am unable  to add ts watch task  in Visual Studio Code on Mac

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0

# Error - 

`
env: node: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.`

-----

This is the task.json, when i try to run the task, the  above mentioned error is thrown .

# tasks.json ->

```json
{
 
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ts compile",
            "type": "shell",
            "command": "./node_modules/typescript/bin/tsc -w -p .",
            "windows": {
                "command": "node_modules\typescript\bin\tsc -w -p ."
            },
            "group": "build",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": [
                "$tsc-watch"
            ]
        }
    ]
}
```

![screen shot 2017-11-28 at 9 58 01 am](https://user-images.githubusercontent.com/385499/33302518-b592c670-d422-11e7-8c31-648d4997143e.png)

**Comment by rtalwar26** [comment]
I guess i figured out the problem,

Under VSCode -> user-settings , I am using 

```json
terminal.integrated.shell.osx : "path/to/zsh"
```

But I guess by default the task runner uses `bash` on mac/linux. After exporting `path/to/node` in 
`~/.bash_profile` the error is no longer shown.


But I guess Vscode should pick the `shell` am using and try to get `node`'s path

**Comment by dbaeumer** [comment]
@rtalwar26 by default the task runner uses the shell that you see in the intergrated terminal. Will this be bash or zsh in our example?
