### ISSUE TITLE
TERMINAL background color issue

### ISSUE THREAD

**Issue by lssbq** [Microsoft/vscode#39222]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.24
Angular2|joh|2.11.2
vscode-exec-node|mir|0.5.0
python|ms-|0.8.0
team|ms-|1.122.0
material-icon-theme|PKi|3.1.0
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:
On my Windows10 I changed the **cmd** background color to grey.
In VS Code dark theme, the TERMINAL background color is the default black.
But when running global command like 'npm', 'bower' etc. the background color of these commands output will turn to other color(whit or light grey) so the output is hard to read.
![20171128101447](https://user-images.githubusercontent.com/17997151/33299099-0b3bc4e4-d425-11e7-930d-791cc990a6a3.png)

**Comment by mazlanmohdnor** [comment]
yeah, i having this problem also

**Comment by Tyriar** [comment]
> On my Windows10 I changed the cmd background color to grey.

This is the issue, unfortunately you cannot use cmd.exe themes as they mess with VS Code's terminal.
