### ISSUE TITLE
XHR 

### ISSUE THREAD

**Issue by zotanika** [Microsoft/vscode#39221]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by maxibanki** [comment]
Please give us more information, such as the error message, reproducible steps and more.
