### ISSUE TITLE
File Explorer Directory Tree shuffles position after deleting a file, and it can cause major disorientation

### ISSUE THREAD

**Issue by amackintosh** [Microsoft/vscode#39223]
- VSCode Version: 1.18.1
- OS Version: Win 10 Pro

Steps to Reproduce:

1. Open VS Code
2. Open a project that has lots of folders and files
3. Expand a bunch of directories in the File Explorer (left-hand-side directory tree)
4. Create a new file inside any folder, arbitrary name
5. Ensure there is a scrollbar
6. Open a few files from other areas of the directory tree (not close to the file you just created)
7. Now, open the file you just created a few seconds ago
8. Right click the file in the File Explorer
9. Delete the file

10. Notice how the directory tree shifts violently
11. This is the issue I do not like

Reproduces without extensions: Yes

I see what VS Code is doing. When I delete a file while it is currently open, the editor shifts to the previously open file, or whatever file it goes to, but this is very jarring. It happens to me almost every time I delete a file. My current focus is the file I deleted and its position in File Explorer.

It is very disorienting and sometimes I do not recall exactly where the file was that I just deleted, mostly because it was a garbage file somewhere that I was browsing.

I think there is a better solution that needs to be implemented here. I leave that open to interpretation. I do not like how it is currently, and I know others experience this also. Maybe if there was a transition animation so it slowly transitioned away, so I could at least see which direction the directory was.

Right now, I can't even tell if I need to scroll up or down after VS Code shuffles my position. That is the basis of why it's so confusing. I just want to go back to where I just deleted a file.

Here is an animated GIF of me reproducing it:

https://gifyu.com/image/pESP

**Comment by bpasero** [comment]
@amackintosh you can disable the explorer from auto revealing via `"explorer.autoReveal": false`
