### ISSUE TITLE
Can't get complete error message which is showed on top of the vscode

### ISSUE THREAD

**Issue by Yang09701194** [Microsoft/vscode#39226]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
---

Hi, when I got error message on the top of vscode, the message is cut off so I can't get the whole message (show in the picture).

 I would like to request the feature to get complete message, such as right click on it and there's `copy full message` menuitem to select, or `expand the message panel` to see the complete message, thank you.

![image](https://user-images.githubusercontent.com/23180780/33301110-dbfa8f6c-d42e-11e7-94c3-bde1e9ad7372.png)

**Comment by kieferrm** [comment]
Hovering over the message box shows you the full error message.
