### ISSUE TITLE
Performance in v1.18.1 Mac OS cpu>100% on CodeHelper

### ISSUE THREAD

**Issue by rich1383** [Microsoft/vscode#39230]
- VSCode Version: 1.18.1
- OS Version: Mac OS El Capitan 10.11.6
Problem started immediately after update from 1.17.1 to 1.18.1

Steps to Reproduce:

1. Start VS Code on any project (tried two different projects, each with 700-800 files total, including GIT directory)
2. Open any source code file (PHP, JS, HTML) for viewing
3. Watch cpu go and stay over 100%
4. Close all open editor windows and cpu drops immediately (codehelper procs go away)

ps aux output:
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
dt209788         73438 107.4  2.0  4441824 331276   ??  R    11:41PM   1:56.10 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=6ADBFB5C498D4B425B906FDBA41623E8 --lang=en-US --app-path=/Applications/Visual Studio Code.app/Contents/Resources/app --node-integration=true --webview-tag=true --no-sandbox --background-color=#002b36 --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,34037;2,11,34037;2,12,34037;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,34037;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,34037;4,13,3553;4,14,34037;4,15,34037 --service-request-channel-token=6ADBFB5C498D4B425B906FDBA41623E8 --renderer-client-id=14

Reproduces without extensions: No

**Comment by kieferrm** [comment]
Pls see https://github.com/Microsoft/vscode/wiki/Performance-Issues.  Which extension is causing it?

**Comment by rich1383** [comment]
Thanks.  I was going to start that process of plugin elimination, but since this post, after my CPU ran hot/100% for a full day or so, it stopped doing that.  Things are back to normal with all 11 plugins running; no updates that I know of... quite odd.
