### ISSUE TITLE
php v5.4 short array syntax not supported

### ISSUE THREAD

**Issue by rtpHarry** [Microsoft/vscode#3923]
Since PHP v5.4 it has supported a short array syntax which replaces `array()` with `[]`:

```
<?php
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);

// as of PHP 5.4
$array = [
    "foo" => "bar",
    "bar" => "foo",
];
?>
```

http://php.net/manual/en/language.types.array.php#example-96

I'm using Visual Studio Code v0.10.10

```
Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:38:23.764Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

Every time it comes across one of these it shows highlight errors:

![image](https://cloud.githubusercontent.com/assets/1038062/13643752/345b1bd6-e61a-11e5-9eba-619676bd4c49.png)

and

![image](https://cloud.githubusercontent.com/assets/1038062/13643767/425390d8-e61a-11e5-9979-7c45ad023f3e.png)

Implementing #776 should fix this issue as well.

**Comment by mattacosta** [comment]
VSCode gets its squiggly information from the version of PHP installed on your system. If you haven't configured the "php.validate.executablePath" setting, then it tries to find the executable using your system environment settings (so for Windows, the PATH variable). In this case your system appears to have a really old PHP version, installing a newer version and setting the executablePath to it should fix those errors.

**Comment by rtpHarry** [comment]
I've just checked and I had an old version higher up the path. Thanks for the clarification.
