### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by zhenglincheng** [Microsoft/vscode#39235]
when I develop vscode plugin ，
i want to import  ifxnjs@6.0.7  
debug extension  , this is error report : "A dynamic link library (DLL) initialization routine failed" 。
ifxnjs  is  Informix native node.js driver 。
ifxnjs can be loaded by normal node projects。

**Comment by kieferrm** [comment]
Please provide a minimal workspace showing the issue.

**Comment by zhenglincheng** [comment]
[helloworld.zip](https://github.com/Microsoft/vscode/files/1512757/helloworld.zip)
a minimal extension  can show the issue  (run command Hello world)
I just added the following in the extension.ts file ：
>import ifxdb = require('ifxnjs');

env :

**Comment by zhenglincheng** [comment]
I've tried rebuild ifxnjs on nodejs 7.9.0  。But still did not solve the above problems

**Comment by kieferrm** [comment]
I'm guessing your environment is not configured correctly.  Here is how you can confirm your environment:
- remove the dependency on `ifxnjs` in your `extension.ts` file
- launch your extension using your `Extension` launch config
- in the launched instance open the Developer Tools using the command palette
- in the console of the dev tools run process.env and inspect your `PATH` variable

**Comment by zhenglincheng** [comment]
when i remove `ifxnjs `in `extension.ts` file，this extension works well 。
The following is the output of process.env 
![image](https://user-images.githubusercontent.com/10069335/33408798-43f100b2-d5b3-11e7-997c-a6ce7eadbc6e.png)

![image](https://user-images.githubusercontent.com/10069335/33408786-2c03f0c2-d5b3-11e7-9213-2f8052a41bcf.png)

**Comment by kieferrm** [comment]
@weinand any idea why this could happen although PATH is supposedly set correctly in the launch environment?

**Comment by kieferrm** [comment]
https://github.com/kieferrm/vscode-keytar-sample shows the same issue on Windows when I compile it for electron 1.7.9 and then run `npm start`. I.e. I don't have to debug. When the extension is loaded in the extension host the problem occurs.

**Comment by weinand** [comment]
This problem is independent from PATH or debugging issues.
If I build and then install the "helloworld" extension from above, I see the DLL init problem as soon as I try to run the "hello world" action (and the extension activation occurs).

**Comment by bpasero** [comment]
@weinand sounds like a native node module cannot be loaded because it was not compiled against the same headers that we ship with?

**Comment by weinand** [comment]
@zhenglincheng, @kieferrm and I compiled the DLLs for electron 1.7.9.
Is this not the version VS Code is using?

**Comment by bpasero** [comment]
@weinand you can always find out from the dev tools:

![image](https://user-images.githubusercontent.com/900690/33713300-ffccfa24-db4a-11e7-8a02-dfb62e2e66ee.png)

**Comment by weinand** [comment]
Sure, I did exactly that (it was more a rhetorical question).

**Comment by bpasero** [comment]
@weinand I do not think this library is compiling itself properly, rather it ships prebuilt binaries which likely are unsupported for Electron: https://github.com/OpenInformix/IfxNode

**Comment by weinand** [comment]
@zhenglincheng please make sure that you compile ifxnjs against the electron version you are using. Currently it is 1.7.9. But @bpasero explained how to find out.

**Comment by kieferrm** [comment]
As mentioned in https://github.com/Microsoft/vscode/issues/39235#issuecomment-349842079 I have the same problem with `keytar`. This one does not come with pre-built libraries. I used 
`npm install --runtime=electron --target=1.7.9 --disturl=https://atom.io/download/electron` to compile keytar.  When activating the extension that uses the keytar module that was built this way I see the DLL issue indicating that there is an issue with the `keytar.node` file.
So, for the sake of experimenting I replace the self-built `keytar.node` file in my extension with the one from the vscode insiders.  After that the extension activates just fine. So, the issue is with how the native modules are built.

**Comment by kieferrm** [comment]
Nevermind, it works as it should. I.e. when the modules are **properly** compiled against 1.7.9. In my case the command line arguments were not passed correctly to npm because of a local configuration issue. In this case, the reachable nodejs is being used which was v8.9.1 instead of v7.9.0.

**Comment by zhenglincheng** [comment]
Thank you！
