### ISSUE TITLE
Feature request: Support for themes to be tied to projects.

### ISSUE THREAD

**Issue by wezz** [Microsoft/vscode#39238]
I suggest adding support so that projects can have a themes tied to them.
When dealing with similar projects I often find myself wishing that I could have different themes in the different editor windows.

**Comment by sandy081** [comment]
@wezz Do you mean having different themes per workspace?

**Comment by wezz** [comment]
@sandy081 Exactly!
A more detailed usecase:
I'm developing a project that can be run standalone and as a dependency. 
When hunting for bugs when it's run as a dependency I usually edit directly in my node_modules folder, while having the source project open in another vs code window.

So unfortunately it happens that I continue coding in the wrong project since it's the same code base and it has the same project name. Essentially I need to look at the file paths to see which project I'm in at the moment.

If I could set the source project's vs code window to have one theme and another theme (or default) in my other vs code window it would help quite a lot.

**Comment by sandy081** [comment]
Did you try using workspace settings to configure themes?

**Comment by wezz** [comment]
@sandy081 I just tried it and it works as expected. I had missed changing where to save the theme setting (the dropdown at the top).

It would be great if this could be mentioned on the VS Code blog. It helps a lot to have different themes for each workspace.

This issue can be closed
