### ISSUE TITLE
How about add a function return type for TypeScript snippet?

### ISSUE THREAD

**Issue by Heatwave** [Microsoft/vscode#39231]
Hello everyone

I have send a pull request to add a return type for TypeScript **function** snippet: #39133 

```json

{
 	"Function Statement": {
  		"prefix": "function",
  		"body": [
 -			"function ${1:name}(${2:params}:${3:type}) {",
 +			"function ${1:name}(${2:params}:${3:type}): ${4:return} {",
  			"\t$0",
  			"}"
  		],
 		"description": "Function Statement"
 	}
}
```

Because I think it should be a best practice for the TypeScript that to always specify the function return type. 

When you define a function, you should able to know what type you want to return. If you return other type, the compiler will tell you there is maybe a mistake:

![image](https://user-images.githubusercontent.com/7134217/33303287-3f6b6586-d43d-11e7-90fa-8adc1d6d7bba.png)

So I think we should always specify the function return type.

But @mjbvz think TypeScript can correctly infer the return type in the majority of cases and some users would end up deleting the return type in the snippet.

Please give your comments. Thanks.

**Comment by mjbvz** [comment]
Thanks for filing the issue. However since it has not received much attention in the past 3 months, I'm going to close it out. If this is really bothering you, you can write a custom snippet that adds a return type
