### ISSUE TITLE
Failed to open a integrated terminal when it is in a `git difftool` window

### ISSUE THREAD

**Issue by TorosFanny** [Microsoft/vscode#39239]
- VSCode Version: Version 1.18.1
- Commit 929bacba01ef658b873545e26034d1a8067445e9
- Date 2017-11-16T18:34:22.110Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- OS Version: ArchLinux

Steps to Reproduce:

1. open a git repository, and create a new file, <new_file>. And `git commit -a`
2. Then use `git difftool HEAD~ <new_file>` to open it.
Then you will notice that the new tab will be opened in a new window, and the former opened window will be closed. Normally, when <new_file> has an older version in git will be opened in the opened window, but it is not the case when <new_file> doesn't have an older version in git.
In the new created window, press 'Ctrl+\`', then error report appears as "The terminal process command `/bin/bash` failed to launch (exit code: 1)". But in fact, my shell is not bash but fish shell.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What is your configured `difftool`?

**Comment by TorosFanny** [comment]
[diff]
    tool = default-difftool
[difftool "default-difftool"]
    cmd = code --wait --diff $LOCAL $REMOTE

**Comment by bpasero** [comment]
@TorosFanny can you attach a screencast how this looks like, I cannot get where you are at:

![image](https://user-images.githubusercontent.com/900690/33565477-89cd1266-d91d-11e7-94a9-0c87752505f9.png)

**Comment by TorosFanny** [comment]
I can't recurrent now either. I'm sorry for that. When I come into this problem some time later, I will post it here. But VS's behavior is strange sometimes. In the embedded terminal of VS,  type `code <file>`, sometimes VS will open `<file>` in the already opened window as a tab, but sometimes will open in a new window. I have to use `code -reuse-window <file>` every time.

**Comment by bpasero** [comment]
@TorosFanny do you maybe have the setting `window.openFilesInNewWindow` configured? Also, when this happens, could it be that the new window has the full folder of that file as context and not just the file?

I know we have some code that tries to be smart about opening the actual parent folder of a file when that file is inside a folder which looks like a VS Code project (e.g. by checking for a .vscode folder with settings).

**Comment by TorosFanny** [comment]
Sorry for being late.  No, I leave "window.openFilesInNewWindow" as the default value "off", which is what I want. But I couldn't remember whether the side bar was open or not. I'm sorry for that.

**Comment by bpasero** [comment]
Ok please check next time.
