### ISSUE TITLE
Rename navigation not working properly

### ISSUE THREAD

**Issue by rwmb** [Microsoft/vscode#39246]
I tried to rename a file and when trying to use navigation keys, the focus stayed on the explorer instead of the text for renaming the file, so when I pressed the End key it went all the way to the end of my project files.

- VSCode Version: 1.19.0-insider
- OS Version: win10

Steps to Reproduce:

1.Press F2 in the explorer or try to rename a file.
2.Press the navigation keys (up, down, left or right arrows, end and home).

![vscode-rename-navigation-problem](https://user-images.githubusercontent.com/20707521/33317140-3aa8e1f4-d42e-11e7-8ed1-1b81498d2cb9.gif)

Reproduces without extensions: Yes

**Comment by AntonPuko** [comment]
have the same, it's now a nightmare to create/edit files with vim-bindings enabled.
