### ISSUE TITLE
SCM tracks folder even after removing it from workspace (multi root)

### ISSUE THREAD

**Issue by shivammittal99** [Microsoft/vscode#39243]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
MagicPython|mag|1.0.12
python|ms-|0.8.0
cpptools|ms-|0.14.3
debugger-for-chrome|msj|3.5.0
python-extended-snippets|tus|0.0.1

---

Steps to Reproduce:

1. Open multiple folders with git initialised
2. Remove a folder from workspace
3. We can still stage, commit to the folder

![vscode_bug](https://user-images.githubusercontent.com/25584932/33314105-a1a54414-d452-11e7-9a1b-3f8d1e3a6a46.gif)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
You have to remove the repository itself: right click on the repository and close it.
