### ISSUE TITLE
UTF-8 BOM setting and indicator

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3924]
**Assignees:**

- [x] Windows @gregvanl 
- [x] OS X  @jrieken 
- [x] Linux @aeschli 

We added a new encoding to the list of encodings to indicate UTF 8 with BOM
* Verify you can convert files to UTF 8 with and without BOM from the encoding picker in the status bar
* Verify the status bar correctly shows UTF 8 with BOM if the file has a BOM
* Verify you can set a workspace or global setting to save files with UTF 8 BOM

**Comment by Raydir** [comment]
@bpasero is it possible that selecting UTF-8 with BOM from the econding Picker is only available in the inside-build?

**Comment by bpasero** [comment]
@Raydir no

Stable:
![image](https://user-images.githubusercontent.com/900690/32773007-0b1fd110-c928-11e7-81e8-cb8fa046c033.png)

**Comment by Raydir** [comment]
![grafik](https://user-images.githubusercontent.com/17499573/32773666-3463a64e-c92a-11e7-9dd6-aff5c2df36d5.png)

ahm..  this ist form my actual Version 1.18.0?
![grafik](https://user-images.githubusercontent.com/17499573/32773689-49a64e80-c92a-11e7-98ad-e798e0f0bb24.png)

**Comment by Raydir** [comment]
@bpasero  it got it: it seems there is a difference betweek OPEN and SAVE --> it does not work when you try to REOPEN.

**Comment by bpasero** [comment]
@Raydir yes, because it is the same as UTF-8. If you want to add a BOM, you need to re-encode it.

**Comment by Raydir** [comment]
Got it. Thanx
