### ISSUE TITLE
workspaceRoot is not recognized in terminal.integrated.env.windows

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#39242]
- VSCode Version: 1.18.1
- OS Version: Windows 10 x64

### Steps to Reproduce:

1. add this to the workspace settings

```
"terminal.integrated.env.windows": {
    "PYTHONPATH": "${workspaceRoot}"
}
```

2. open a new terminal
3. run `echo %PYTHONPATH%`

### Expected behaviour:

prints `c:/path/to/my/project`

### Actual behaviour:

prints `${workspaceRoot}`

### Reproduces without extensions: Yes

**Comment by marckassay** [comment]
@cprogrammer1994, I believe this is the same as: #2809

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34337 #2809
