### ISSUE TITLE
power mode extension broken in Insiders, are others affected?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39259]
Insiders on MacOS
Version `1.19.0-insider (1.19.0-insider)`
commit `af232487ebcdc9758da537ea9a58977c373bc2be`
`2017-11-28T06:03:32.906Z`

The Power Mode extension is broken in Insiders, see: https://github.com/hoovercj/vscode-power-mode/issues/20

I'm opening an issue here because something changed in VS Code recently that causes the extension to not work properly, and perhaps that change will affect other extensions. 

To repro:
Install the Power Mode extension
enable it through the `powermode.enabled = true` setting
start typing

result: "explosions" only occur at start of line
expected: as in stable, explosions track the cursor

**Comment by alexandrudima** [comment]
Yes, I changed how inline decorations are rendered for #37401

It might affect rendering scenarios outside of our decorations scope (i.e. hacks).

**Comment by hoovercj** [comment]
Power mode is definitely a hack and I anticipate it will break again in the future, but thanks for letting me know when it does! It is fixed (for now) in version 2.1.0.
