### ISSUE TITLE
Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute

### ISSUE THREAD

**Issue by bstaks** [Microsoft/vscode#39251]
I am getting issue when build a project 
my scenario is I have one solution file and added one project
and another project added same solution with folder library when i build library so it's successfully build but sln and project file in same folder then i build project then i am getting error, which are mention below 

obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(10,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(11,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(12,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]

Build FAILED.

obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(10,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(11,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(12,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]
obj\Debug\netcoreapp2.0\myDotnetapp.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\ABKSR\myDotNetApp\myDotnetapp.csproj]

**Comment by weinand** [comment]
If you really consider this a bug (and not a misconfiguration of your project), you could file this against the C#/dotnect extension you are using.
