### ISSUE TITLE
.vscode/settings.json of each folder is ignored in multi-root-workspace

### ISSUE THREAD

**Issue by dj-hedgehog** [Microsoft/vscode#39250]
- VSCode Version: 1.19.0 (Insider)
- OS Version: 10.12.6

*Steps to Reproduce:*

1. Add multiple folders to a workspace
2. Add settings inside one of the folders .vscode/settings.json

*Expected result:*
The settings from every `.vscode/settings.json` are applied

*Actual result:*
The settings set in the files `.vscode/settings.json` are ignored.

**Comment by sandy081** [comment]
Could be a duplicate of #39192
