### ISSUE TITLE
Whitespace inserted with unicode BOM

### ISSUE THREAD

**Issue by aaayushsingh** [Microsoft/vscode#39258]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.12.12-custom
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
python|ms-|0.8.0
cpptools|ms-|0.14.2
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Launch VS Code and create a new JavaScript file
2. use VSCode to insert BOM.
3. run `eslint filename.js` this will throw illegal whitespace error on 1:1

if we copy BOM and paste it into file using normal text editor, no irregular whitespace error is thrown by linter

Reproduces without extensions: No (since eslint is disabled)

**Comment by dbaeumer** [comment]
@bpasero adding you since you know about the save BOM code. Please note that @aaayushsingh runs eslint from a terminal.

**Comment by bpasero** [comment]
@aaayushsingh can you attach both the file from VS Code that has the BOM and produces the error as well as a version of the file with BOM that does not cause the error?

**Comment by aaayushsingh** [comment]
[vscode.zip](https://github.com/Microsoft/vscode/files/1514625/vscode.zip)

labRat.js is the file with error, noWsError is clean.

Also note that vscode doesn't recogonise BOM without the whitespace(probably, because I didn't get any), while I pasted it into google search bar andit was recogonised as BOM.
"﻿". <-- the BOM is between these quotes(sounds funny, but when you select the quotes, you'll have to press space an extra time).

**Comment by aaayushsingh** [comment]
> eslint labRat.js
> fakePath/labRat.js
>   1:1   error  Irregular whitespace not allowed               no-irregular-whitespace
>   6:1   error  Unexpected console statement                   no-console
>   6:33  error  No magic number: 65279                         no-magic-numbers
>   6:49  error  Newline required at end of file but not found  eol-last
> 
> ✖ 4 problems (4 errors, 0 warnings)
>   1 error, 0 warnings potentially fixable with the `--fix` option.

could this be a problem with eslint?

**Comment by bpasero** [comment]
@aaayushsingh labRat.js contains the UTF-8 bom twice:

![image](https://user-images.githubusercontent.com/900690/33414527-be08aa2e-d592-11e7-92df-9bb8f7a62094.png)

Do you know how you got into that state?

**Comment by aaayushsingh** [comment]
@bpasero looks like a totally different issue. The BOM is initially there, but not recogonised, and when added using the option in vscode, I get double BOM as in the image you put. I have attached a small demo video(screen recording) in the zip that show file with and without box and the hex dump of the file as well. You'll understand when you see the video.

[vscode.zip](https://github.com/Microsoft/vscode/files/1518191/vscode.zip)

**Comment by bpasero** [comment]
@aaayushsingh you clicked on "Fix this unicode BOM problem" and it added a second BOM is that what happens?

**Comment by aaayushsingh** [comment]
@bpasero Yes.

And initially the bom that was actually present wasn't recogonised as you can see in the video.

**Comment by bpasero** [comment]
@aaayushsingh do you know from which extension this command is popping up? Could it be ESLint itself? It is not an action VS code provides.

**Comment by aaayushsingh** [comment]
@bpasero I initially posted this in the vscode-eslint repo. See [this](https://github.com/Microsoft/vscode-eslint/issues/356). should I repoen the issue there? They said this was an issue by vscode.

It could only be the vscode-eslint extension.

**Comment by bpasero** [comment]
Yes it can only be vscode-eslint (or ESLint), this action is not coming from VS Code.

**Comment by dbaeumer** [comment]
I can't what the video (for unknown reasons) but the action comes from ESLint itself. The VS Code eslint extension doesn't add any fixes besides those provided by the ESLint npm module.

@

**Comment by dbaeumer** [comment]
Actually the seems to be an issue with ESLint (the npm module) detecting the first BOM. @aaayushsingh as I understand you eslint (run in the terminal) will output an error even on the file that has the BOM.

**Comment by dbaeumer** [comment]
Lets continue the discussion in https://github.com/Microsoft/vscode-eslint/issues/356. There is an issue with ESLint itself since we do the checking in memory and not on disk.

**Comment by aaayushsingh** [comment]
@dbaeumer when I run eslint from terminal, it works fine. It is only it's integration with vscode that has issues with BOM. Also BOM inserted using Gedit doesn't have any whitespace error.
