### ISSUE TITLE
Goto File then right arrow no longer opens file

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39256]
Stable
Version `1.18.1 (1.18.1)`
Commit `929bacba01ef658b873545e26034d1a8067445e9`

`CMD+P` to bring up goto file
Press `P` a few more times while holding down `CMD`
Press `right arrow` to open a file in the well, but not close the goto file pick list

result: file is not opened
expected: used to work, see https://youtu.be/wSPEfm7jlGQ?t=1097

**Comment by bpasero** [comment]
@chrisdias this feature works for me in stable, but not anymore in insiders and I suspect this is a regression from the list service (@joaomoreno).

**Comment by chrisdias** [comment]
I can't get it to work in Stable either, but I will show you that on Thursday.

**Comment by bpasero** [comment]
@chrisdias I think it never worked if you also press the Cmd button, so that might be a separate thing. Can you try with 1.17?

**Comment by chrisdias** [comment]
got it... you have to release the CMD key and then right arrow will open the file ...

**Comment by joaomoreno** [comment]
@bpasero You gotta stop telling everyone about changes to the list service breaking everything. 😢

**Comment by chrisdias** [comment]
@joaomoreno it was the list service that was making me keep my finger on the CMD key...   ;)

**Comment by bpasero** [comment]
Weird, I could swear I was in a state where I could not even get the normal behaviour of pressing arrow key and opening the file in the background. But seems to work fine now.
