### ISSUE TITLE
Test: code yeoman generator new options that enable more checking 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#39257]
- [x] any os @chrisdias 

Complexity: 1

The yeoman generators for TypeScript and JavaScript extensions where enhanced, test the following configuration options:
- TypeScript
  - additional prompt for more strict TS checking options
  - additional prompt for setting up tslint
  - recommends the vscode-tslint extension in `extensions.json`
- JavaScript
  - additional prompt to enable type checking in JS files 
  - recommends the vscode-eslint extension in `extensions.json`.

**Comment by chrisdias** [comment]
LGTM
