### ISSUE TITLE
I want to display the total number of characters in sentences

### ISSUE THREAD

**Issue by k-fujtia** [Microsoft/vscode#39254]
- VSCode Version:1.18.1
- OS Version:Windows 10 1709

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Currently you can only select the sentence and see the character count in the button right status bar:
![image](https://user-images.githubusercontent.com/17984549/33321696-e77a16ec-d446-11e7-8f4c-950b9cfcde30.png)
In this case there were 52 characters selected.

**Comment by k-fujtia** [comment]
It also includes newlines. Also, I always want to display the number of characters.
