### ISSUE TITLE
Enhancement : Jump to next/prev block 

### ISSUE THREAD

**Issue by Aarbel** [Microsoft/vscode#39268]
Could you implement this feature inside the Editor ?

jump with the cursor vertically across space separated blocks, skipping empty lines.
This helps to quickly navigate thru our code, it's possible in many editors.
![screenshot](http://i.imgur.com/VZk2uX4.gif)

Thanks !

**Comment by rebornix** [comment]
It's a good extension candidate, AFAIK Vim extension implements this feature.

**Comment by Aarbel** [comment]
I'm too busy next weeks to read the VSCode API doc and build an extension :/

Could be very quick for anyone who already knows how to build one. Who wants ?  @rebornix
