### ISSUE TITLE
Editor freezes when file got modified

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39266]
* have a largish file open (~1.5MB)
* tab to another tools, e.g terminal and run a command the updates the file
* tab back to VS Code and notice that its frozen for a minute

<img width="785" alt="screen shot 2017-11-28 at 14 50 24" src="https://user-images.githubusercontent.com/1794099/33327199-38c764b8-d457-11e7-8fbd-b100e520417e.png">

**Comment by alexandrudima** [comment]
To the verifier:

Please also check the steps in #41184
