### ISSUE TITLE
Output handling improvements

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3926]
**Assignees:**

- [x] Windows @bpasero 
- [x] OS X @waderyan   
- [x] Linux @aeschli 

We are handling output in a better way. Related issues #3609, #3896, #3897. Verify:
* You can not cause VSCode to freeze or crash by spamming it with output from an extension
* No duplicate output is received, nor any output is missing - particularly if you open and close the output panel

**Comment by isidorn** [comment]
@bpasero feel free to add details if you are feeling creative

**Comment by aeschli** [comment]
@isidorn Can you give some testing steps? Write an extension and write to the console?

**Comment by isidorn** [comment]
The bugs linked in the original issue did not work before.
Testing steps is to write an extension and use our [output API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2518) to send content to the console and try to be creative in crashing it #3609 uses this api for instance

**Comment by waderyan** [comment]
I used the extension code from this [comment](https://github.com/Microsoft/vscode/issues/3609#issuecomment-193997733). Couldn't reproduce the bug. Looks good :1:
