### ISSUE TITLE
Not downloading or installing dependencies

### ISSUE THREAD

**Issue by servicios-digitales** [Microsoft/vscode#39267]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
python|don|0.7.0
php-intellisense|fel|2.0.1
csharpextensions|jch|1.3.0
mssql|ms-|1.2.1
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
material-icon-theme|PKi|3.1.0
view-in-browser|qin|0.0.5
java|red|0.14.0
vscode-icons|rob|7.18.1
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

(12 theme extensions excluded)

Steps to Reproduce:

1. Added a C# project folder to the workspace
2. This shows in the Output section for C#:

Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.26.3.zip' Downloading package '.NET Core Debugger (Windows / x64)' 	Retrying from 'https://vsdebugger.blob.core.windows.net/coreclr-debug-1-13-0/coreclr-debug-win7-x64.zip' 
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished

Reproduces without extensions: No

Additionally I can download the ZIP file by Ctrl + clicking on the link, if you could point me in the right direction to manually install it, that'll OK by me.. thanks in advance.

**Comment by kieferrm** [comment]
Pls file this issues against the C# extension: https://github.com/OmniSharp/omnisharp-vscode/issues
