### ISSUE TITLE
Can't paste or use navigation keys when renaming a file

### ISSUE THREAD

**Issue by danyhoron** [Microsoft/vscode#39260]
- VSCode Version: Code - Insiders 1.19.0-insider (af232487ebcdc9758da537ea9a58977c373bc2be, 2017-11-28T06:07:41.602Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
export-index|Bru|0.0.3
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.24
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.5
mssql|ms-|1.2.1
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1

---

Steps to Reproduce:

1. Open an existing project/folder. ( mine is Angular 4)
2. Select any file in the project
3. Hit enter or right click / rename
4. Hit the Left arrow key a few times

Instead of moving through the filename characters, it collapses the folder.

Reproduces without extensions: Yes

**Comment by guillaumep** [comment]
The same issue happens for other keys: home button, up and down arrows, etc.
