### ISSUE TITLE
Automatically activate "Find in selection" when opening the find/replace dialog and text is already selected

### ISSUE THREAD

**Issue by orobert91** [Microsoft/vscode#39269]
The "Find in selection" button of the find/replace dialog should automatically be selected when text is selected at the opening of the dialog. This is the behavior of Visual Studio.

Also, the problem with the actual behavior is when you follow logical steps like these:
1. Select multiple lines text
2. Ctrl+F
3. Write something in the search box
4. Text that was selected is no longer selected

Text has to be reselected again. To prevent this counter-intuitive behavior, the "Find in selection" button must be manually activated before typing text in the search box, I find this counter-intuitive.

Activating that button automatically when text is selected would solve all of this. I must also add that differentiating from the selected/non-selected state of this button is very hard when using the dark theme.

**Comment by rebornix** [comment]
We already have `editor.find.autoFindInSelection`, thanks!

**Comment by orobert91** [comment]
Oh, didn't know that option, thank you!
