### ISSUE TITLE
Feature request: Public API for modifying recently opened list

### ISSUE THREAD

**Issue by davidkpiano** [Microsoft/vscode#39265]
Currently, being able to read/update/delete the mRU (most recently updated) list is unavailable as a public API, and ideally, an extension should be able to:
- access the mRU
- manually delete items from mRU
- ~update entires in the mRU - not necessary for now~

Our current use-case is for extensions that dynamically create "transient" named workspaces that exist in a temporary folder in the file system, and are deleted at some point. Despite being deleted, they still show up in the mRU list, especially on the welcome screen, and they aren't removed from mRU until opening them is attempted, with error (this is by design).

**Comment by bpasero** [comment]
@davidkpiano wouldn't it be better if you had API to add a folder to the currently opened workspace and let VS Code deal with how to present it? That would be covered with https://github.com/Microsoft/vscode/issues/35407

Unless the user saves such a workspace, it will be an untitled workspace that will not show up in the MRU list and will go away once the window is closed and not saved as saved workspace.

**Comment by davidkpiano** [comment]
@bpasero That would suffice. Thanks!
