### ISSUE TITLE
--install-extension with a local VSIX file does not work 

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/vscode#39276]
Installing a VSIX from the command line does not work.
Followed instructions from here:
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

No error occurs, but no extension gets installed.
Instead the GUI starts (undesirable), no errors reported (undesirable), and the GUI remains open (also undesirable).

Installing the extension through the GUI works.
The lack of this ability restricts the ability to use this tool in an autobuild.

- VSCode Version:
Version 1.19.0-insider
Commit d88e71355feeb2b0deb02c021d33cb968531726e
Date 2017-11-28T05:13:37.597Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows Server 2016 Standard.

Steps to Reproduce:

1.   "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" --verbose --install-extension "C:\Example\ALLanguage.vsix"

Produces output:

[main 11:15:17 AM] Starting VS Code in verbose mode
[main 11:15:17 AM] from: c:\Program Files\Microsoft VS Code Insiders\resources\app
[main 11:15:17 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'install-extension': 'C:\\Example\\ALLanguage.vsix' }
[main 11:15:17 AM] Resolving machine identifier...
[main 11:15:17 AM] Resolved machine identifier: 2b6ee32963a8123706eab425fc99bab248ac7c7bc2ec39815f81dd7c81853e2f
[main 11:15:21 AM] IPC#vscode-workbenchLoaded
[main 11:34:22 AM] Lifecycle#window-before-close 1
[main 11:34:22 AM] Lifecycle#unload() 1
[main 11:34:22 AM] Lifecycle#window-before-close 1
[main 11:34:22 AM] Lifecycle#window-close 1
[main 11:34:22 AM] Lifecycle#window-all-closed
[main 11:34:22 AM] Lifecycle#before-quit
[main 11:34:22 AM] App#will-quit: disposing resources

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
You need to run `code-insiders --verbose --install-extension "C:\Example\ALLanguage.vsix"`. 

`code-insiders` is in "C:\Program Files\Microsoft VS Code Insiders\bin" and should be in your PATH.
