### ISSUE TITLE
Excessive CPU Code.exe!SandboxedProcess+0x2c78da0

### ISSUE THREAD

**Issue by andyboyne** [Microsoft/vscode#39270]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-great-icons|emm|2.1.20
auto-close-tag|for|0.5.3
auto-rename-tag|for|0.0.15
diff-tool|jin|0.0.1
vscode-icons|rob|7.18.1

(5 theme extensions excluded)

---

At some point of continued use the CPU for code.exe pins an entire core.

Steps to Reproduce:

1. Use VSCode 
2. Over time you will notice things lagging and Code.exe is pinning a core.
3. Run a performance profile in debug tools -> no plugin or vscode javascript is reported to be executing.
4. Inspect threads using Process Explorer: Code.exe!SandboxedProcess+0x2c78da0 
 Full Stack:
ntoskrnl.exe!memset+0x61a
ntoskrnl.exe!KeWaitForMultipleObjects+0xd52
ntoskrnl.exe!KeWaitForSingleObject+0x19f
ntoskrnl.exe!PoStartNextPowerIrp+0xbd0
ntoskrnl.exe!PoStartNextPowerIrp+0x186d
ntoskrnl.exe!PoStartNextPowerIrp+0x1ae7

Reproduces without extensions: Yes/No
Unable to verify as the trigger is not known.

**Comment by andyboyne** [comment]
I should also add that exiting VSCode once it gets into this state leaves the rogue Code.exe processes hanging around, taking up a core. They have to be manually killed.

**Comment by kieferrm** [comment]
Pls see https://github.com/Microsoft/vscode/wiki/Performance-Issues.
