### ISSUE TITLE
Option in ActivityBar/SideBar for opening a new terminal:

### ISSUE THREAD

**Issue by anthcool** [Microsoft/vscode#39279]
Hi,

Not sure if there's a new feature request out there for this yet or not, but it would be nice if you could add another ActivityBar/SideBar option/button to open a new terminal window instead of having to hit the keybinding sequence for it every time.

Thanks!

**Comment by fabiospampinato** [comment]
@anthcool Unfortunately the activity bar is not extendable, however you can add that button to the status bar via my [commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) extension.

**Comment by Tyriar** [comment]
We experimented with adding the panels to the bottom of the activity bar but we ended up adding the full titles to the top of the panel itself. If you have the panel open you can access any panel with a single click:

![image](https://user-images.githubusercontent.com/2193314/33856168-1e40c34e-de7c-11e7-8c08-835b5f22bd32.png)
