### ISSUE TITLE
How to speed up scrolling by shortcut 

### ISSUE THREAD

**Issue by cmoon2000** [Microsoft/vscode#39275]
The shortcut "*scrollLineDown*" and "*scrollLineUp*" make scroll over just one line. Does it have any way to speed up that. I like to have scroll with change cursor position. Maybe any way in *keybindings.json" to do it like:
for example to scroll down 10 lines
```json
{ "key": "alt+pagedown",
  "command": "scrollPageDown",
  "when": "editorTextFocus",
  "args": {
      "lines": "10" 
  }
}
```

**Comment by usernamehw** [comment]
https://stackoverflow.com/a/43950204/5590193

**Comment by cmoon2000** [comment]
I created a macro.

```json
"macros": {
        "scrollLineDown3x": [
            "scrollLineDown",
            "scrollLineDown",
            "scrollLineDown"
        ]
    }
```

Unfortunate, I still scroll only one line

**Comment by usernamehw** [comment]
Works for me with `"editor.smoothScrolling": false`. But you wanted 
> to have scroll with change cursor position

So:
```json
"scrollLineDown3x": [
    "cursorDown",
    "cursorDown",
    "cursorDown"
]
```

**Comment by cmoon2000** [comment]
It's was mistype. I should've written **without** change cursor. I'm sorry about that
