### ISSUE TITLE
VSCode freezes after closing when launched from command prompt.

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/vscode#39277]
When starting VSCode from the command line, it will freeze after the GUI closes.
This restricts the ability to use VSCode within an autobuild or unattended environment.

VSCode Version:
Version 1.19.0-insider
Commit d88e713
Date 2017-11-28T05:13:37.597Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS Version: Windows Server 2016 Standard.

Steps to Reproduce:

1. From a command line ""C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe""
2. Close the GUI.
3. Freezes until a user presses the enter key in the command window.   Appears to be freezing while disposing resources.

Last few lines when in verbose mode are:
[main 11:36:37 AM] IPC#vscode-workbenchLoaded
[main 11:49:07 AM] Lifecycle#window-before-close 1
[main 11:49:07 AM] Lifecycle#unload() 1
[main 11:49:07 AM] Lifecycle#window-before-close 1
[main 11:49:07 AM] Lifecycle#window-close 1
[main 11:49:07 AM] Lifecycle#window-all-closed
[main 11:49:07 AM] Lifecycle#before-quit
[main 11:49:07 AM] App#will-quit: disposing resources

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
Can you please confirm that when you follow your steps above that you still see a VS Code process running in Task Manager?

When I follow your steps I see the behavior your describe but all VS Code processes terminate correctly.   I think what is happening is that a New Line is written to standard out which interferes with the prompt of `cmd`. When you press <kbd>Enter</kbd> you issue and empty command and you get your prompt back in the right place.

**Comment by kieferrm** [comment]
Also, pls use `code-insiders` rather than the exe file.

**Comment by coffeecup007** [comment]
Correct, task manager shows no process.

**Comment by kieferrm** [comment]
Thanks for checking. Then when using `code-insiders` you're all good.
