### ISSUE TITLE
Support hyperlink ansi escapes in the integrated terminal

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/vscode#39278]
Cross-posting from xterm.js for discovery. Hope that's ok.

> Terminal emulators are [starting to support hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). While many terminals have long detected URL's and linkified them, allowing you to Command-Click or Control-Click them to open a browser, you were forced to print the long unsightly URL's on the screen. As of spring 2017 [a few terminals](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) began supporting HTML like links, where the link text and destination could be specified separately.

> Example from iTerm2 3.1:
> <img width="1004" alt="screen shot 2017-11-28 at 12 08 20" src="https://user-images.githubusercontent.com/170270/33316814-8b35c2d4-d435-11e7-8524-da4fa076e6fb.png">

https://github.com/xtermjs/xterm.js/issues/1134

**Comment by ssbarnea** [comment]
Is this ever going to be fixed because lack of it makes the intergrated terminal a subpar of almost any  other terminal around there.

For example, I do have file:// urls which point to locally build docs, like:
```
Documentation available under `file:///Users/ssbarnea/c/os/ansible-lint/.tox/docs/html/index.html`
```

At this moment only the file path is recognized as a link and opens the html file in editor instead of opening the URL in browser. If it would not have had the URI suffix, it was normal and desired but the URI header should make it open using the system, not the editor.

**Comment by Tyriar** [comment]
@ssbarnea what you're point out is by design, the file is recognized and is opened in the editor just like any other file. You can create a feature request for this if you would like, as I don't think it has anything to do with this issue.

**Comment by ssbarnea** [comment]
3 years later and most terminals already implemented the hyperlink extensions, still the one from vscode does not. This is quite an issue for tools that produce human friendly terminal output (hint human friendly means to avoid displaying a long and ungly url and displaying only a title for it).

**Comment by kdelmonte** [comment]
this would be a great addition!

**Comment by itsme-alan** [comment]
Even Windows Terminal supports this:

![Hyperlink in Windows Terminal ](https://user-images.githubusercontent.com/75578443/104676677-d7b3ac80-570d-11eb-80df-07013381909a.png)

**Comment by pnsak** [comment]
Any updates on this?

**Comment by ericsampson** [comment]
Any tips on what it would take to make a PR to implement this feature?

**Comment by Tyriar** [comment]
@ericsampson there's some discussion in https://github.com/xtermjs/xterm.js/issues/1134 as this is primarily an upstream request

**Comment by ericsampson** [comment]
thanks @Tyriar I found that link after I posted.
I read the last two comments from you and jerch, but they talk about things that are pretty inside-baseball for a new contributor to understand what needs doing 😅

**Comment by Tyriar** [comment]
Verifier test case: `printf '\e]8;id=abc;http://example.com/\e\\This is a link中国\e]8;;\e\\\n'`
