### ISSUE TITLE
VSCode reports errors on opening directory with templates that looks like csproj/cs files

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/vscode#39283]
I open a directory with a yeoman generator. It contains several templates. One of templates is a csproj file. But it's not a valid csproj file as it has `<%` sections inside it (it's a template).
VSCode while opening that directory reports errors in output like this:
```
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj'.
c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Name cannot begin with the '%' character, hexadecimal value 0x25. Line 6, position 21.  c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj ---> System.Xml.XmlException: Name cannot begin with the '%' character, hexadecimal value 0x25. Line 6, position 21.
```

It'd be nice to allow to mark a directory as "content" to tell VSCode not to parse files inside.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
githistory|don|0.2.3
python|don|0.7.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vscode-reveal|evi|1.0.0
vscode-lua|gcc|0.1.2
rest-client|hum|0.15.3
vscode-nuget-package-manager|jmr|1.1.5
Go|luk|0.6.69
mssql|ms-|1.2.0
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
azurerm-vscode-tools|msa|0.3.7
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.18
material-icon-theme|PKi|3.1.0
java|red|0.14.0
code-settings-sync|Sha|2.8.6
markdown-all-in-one|yzh|0.11.2

(2 theme extensions excluded)

---

**Comment by kieferrm** [comment]
This is a configuration that should live with the C# extension. Please file an issue against https://github.com/OmniSharp/omnisharp-vscode/issues.
