### ISSUE TITLE
Build documentation should explain that building on WSL is not possible

### ISSUE THREAD

**Issue by sgharms** [Microsoft/vscode#39286]
Per:

https://stackoverflow.com/questions/47531475/launch-vscode-from-source-through-wsl

both I and "taylorstine" had the same experience when building vscode from source in WSL. We got past the dependency installation challenge to find that when we ran `./scripts/code.sh` that something was *clearly running* (i.e. was persistent in the process table) but the GUI never materialized. Both of us had an X server up and running that was able to "catch" other X apps and display them (xeyes, in my case).

Could we update the Wiki to clearly state that WSL is not a build platform at present? I have updated the Wiki to reflect this reality: https://github.com/Microsoft/vscode-wiki/pull/40.

**Comment by dbaeumer** [comment]
Yes, we know. The corresponding WSL issue is: https://github.com/Microsoft/WSL/issues/2293

**Comment by sgharms** [comment]
@dbaeumer 

Thank you for the reference to that issue. Foremost it was a wonderful description of debugging a hard problem that, frankly, ought be included in most programming education. Thanks, as well for the additional context. From the VSCode perspective, it looks like the VSCode docs **should** say that WSL is not a build target _until_ Microsoft/WSL#2293 is resolved.

**Comment by dbaeumer** [comment]
Done.
