### ISSUE TITLE
Issues - Typescript debugging with Chrome

### ISSUE THREAD

**Issue by github-ganesh** [Microsoft/vscode#39288]
Unable to debug typescript files, I am getting below error.

SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:5000/dist/tryCatch.js.map
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:5000/dist/vendor.js?v=RCvRrqPvM2Kc5BlkEQ045FeXR6gPMRIwfn51ludN14I, sourcemap: tryCatch.js.map
SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\Users\slakshminarasi\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (C:\Users\slakshminarasi\.vscode\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:53:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
tslint|eg2|1.0.24
task-master|ian|0.1.39
vscode-nuget-package-manager|jmr|1.1.5
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
java|red|0.14.0
vscode-gulp|tan|0.0.4

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Can you post the contents of the sourcemap from http://localhost:5000/dist/tryCatch.js.map?

**Comment by auchenberg** [comment]
Can you provide a few more details on your bundling/compiler setup, @github-ganesh?

**Comment by github-ganesh** [comment]
Added test project 

[TestApp.zip](https://github.com/Microsoft/vscode/files/1515819/TestApp.zip)

**Comment by github-ganesh** [comment]
unable to find tryCatch.js.map  fil



Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=6K9pTDL0d5hM7jcCUMqLE2MiK-DKJH2DmNevMCVDRBQ  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 48.6298ms 200 application/javascript; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 48.6298ms 200 application/javascript; charset=UTF-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/tryCatch.js.map  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/__webpack_hmr  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js.map  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/tryCatch.js.map  
SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:5000/dist/tryCatch.js.map

**Comment by github-ganesh** [comment]
Found the issue changed Chrome launch configuration

----------Old------------
{
           "type": "chrome",
           "request": "launch",
           "name": "Launch Chrome",
           "url": "http://localhost:5000",
           "sourceMaps": true,
           "webRoot": "${workspaceRoot}/"
       },
 ------------New -------------
{
           "type": "chrome",
           "request": "launch",
           "name": "Launch Chrome",
           "url": "http://localhost:5000",
           "sourceMaps": true,
           "webRoot": "${workspaceRoot}/**ClientApp**/"
       },

**Comment by roblourens** [comment]
Glad you figured it out! The webserver must be returning some response to get 

> SyntaxError: Unexpected token v in JSON at position 0

for the sourcemap. I'll check out that error message...
