### ISSUE TITLE
I have installed Visual Studio Code, but on Welcome window, it stands "Add workspace folder..." where it is supposed to be "Clone Git repository"

### ISSUE THREAD

**Issue by MariaRoginskaya** [Microsoft/vscode#39284]
- VSCode Version: Code - Insiders 1.19.0-insider (af232487ebcdc9758da537ea9a58977c373bc2be, 2017-11-28T06:13:45.474Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by cleidigh** [comment]
@MariaRoginskaya 
For clarification can you give more information.
Do mean that when you click "Open WorkSpace Folder" that the command "Clone Git Repository" is executed?

**Comment by MariaRoginskaya** [comment]
Dear Christopher,
I have already listed out the problem: On the Welcome page one replaced "Clone Git Repository" shortcut by anouther one. The problem is really that in a course on how to use Visiual Studio Code given by Microsoft through Edx.org, the teacher shows the old version (and does not give an alternative to the use of the shortcut), so you may expect some other students assuming that something is wrong.
Best regards,
Maria Roginskaya

________________________________________

**Comment by cleidigh** [comment]
@MariaRoginskaya 
Since this was an issue with an old version can we go ahead and close this?

**Comment by MariaRoginskaya** [comment]
sure



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by chrmarti** [comment]
The command was indeed replaced with the new one when we shipped multi-root workspaces. You can still invoke Clone using the command palette: Ctrl+Shift+P and then search for Clone.
