### ISSUE TITLE
Bot message for out of scope is misleading

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#39287]
Current message:

"This issue is being closed to keep the number of issues in our inbox on a manageable level. We are closing issues that have been on the backlog for a long time but have not gained traction: We look at the number of votes the issue has received and the number of duplicate issues filed. If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.\n\nIf you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nThanks for your understanding and happy coding!"

This message is misleading. We also close items that are out of scope even when they have not been on the backlog for a long time.  Also, the wording is rather stiff and formal.

**Comment by chrmarti** [comment]
That has been updated since.
