### ISSUE TITLE
Support console.dir in debug console

### ISSUE THREAD

**Issue by clshortfuse** [Microsoft/vscode#39282]
- VSCode Version: 1.18.1
- OS Version: 10.13.1

Steps to Reproduce:

1. use any console.dir options

compare:

`console.dir({ a: 1234 });`

`console.dir({ a: 1234 }, { colors : true });`

Reproduces without extensions: Yes

The `options` object is being outputted to the console similar to `console.log`:

    Object {a: 1234}
    Object {colors: true}

You can see the specifications here: https://nodejs.org/api/console.html#console_console_dir_obj_options

Related https://github.com/Microsoft/vscode/issues/29602

**Comment by weinand** [comment]
What version of node are you using?

**Comment by clshortfuse** [comment]
I'm using v8.9.1 (which is LTS), though the `console.dir` options have been been available since v0.12.

This doesn't happen when you using Terminal. So far, I've only seen it on the Debug Console.

If I had to guess, this happens because all of the arguments for `console.dir` are being passed instead of just the first.

https://github.com/Microsoft/vscode-chrome-debug-core/blob/604b0e167d68b08069bce28a7dd6c4b75d81ca97/src/chrome/chromeDebugAdapter.ts#L942

https://github.com/Microsoft/vscode-chrome-debug-core/blob/f3784e4fa3a74aed28b92ecfc86062f3633d7e20/src/chrome/consoleHelper.ts#L25
