### ISSUE TITLE
Regular expression search replacements show with literal $1 if grouping added to query after initial search

### ISSUE THREAD

**Issue by PeterJCLaw** [Microsoft/vscode#39281]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-98-generic (Ubuntu 16.04.3 LTS)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
django-html|bib|1.2.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
python|ms-|0.8.0
final-newline|sam|0.3.2
rewrap|stk|1.5.3
spellchecker|swy|1.2.13
jinja|who|0.0.8
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Create a python file containing a Python 2 style print statement (as an example replace target -- `print "foo"`)
2. Open the search pane
3. Enable regular expression based searching
4. Add a search of `print .*`
5. Search
6. Add a replacement of `print($1)`
7. Open one of the search results to preview the change
8. (Realise you need to modify the search string)
9. Modify the search string to be `print (.*)`
10. Open one of the search results to preview the change
     * Minor bug: the replacement doesn't show up yet, which is odd
11. Close the file tab used for the preview (this causes the replacement results to now be previewed in the search pane)
    * Bug: the replacement results all show as the literal `print($1)` rather than the expected `print("foo")`. Doing the replacements at this point also replaces the text with `print($1)` rather than the expected `print("foo")` (etc.).

It's possible to work around this by re-triggering the search by toggling the regular expression mode or by clicking in the query box and pressing Enter.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
I can't repro this, 11 doesn't cause the replace to show up. But this doesn't really sound like an issue - you changed the search string without triggering the search again. When you changed the search string, it invalidates the replace preview and just shows the previous results as is. You can confirm that by changing the search query to something with different matches - you can see that it isn't running the search again.

**Comment by PeterJCLaw** [comment]
@roblourens Thanks for having a look. I'll double check the instructions tomorrow, though I do think there's an issue here. (For my understanding: are you trying to reproduce with the same build, or with something else?)

I realise that I'm not explicitly triggering a new search to run after the modification of the query string, though from what I recall the UI _does_ change from showing just the search results (orange) to showing replace results (red/green). If it would be useful I'll see whether I can record a video of it.

**Comment by PeterJCLaw** [comment]
@roblourens I've checked the instructions and the issue definitely reproduces for me. I've recorded a demo of my screen at https://youtu.be/d36QSz2lsIo in case that helps.

I can see what you mean about the search not being re-run, though I hope you'll agree that the changes to the UI while altering the query can create confusion.

**Comment by roblourens** [comment]
I see what you mean. There was no group, so there was nothing to replace `$1` with. And when you change the query without running the search, we can't really show a useful replace preview. So I'm not going to change anything here.

**Comment by PeterJCLaw** [comment]
Yeah, I think the confusion comes from the results display changing when the regex is invalid. If that didn't happen it would avoid the impression that the search had been re-run.
