### ISSUE TITLE
Debugger not being attached when debugging a WebDriver.IO project

### ISSUE THREAD

**Issue by markwalsh-liverpool** [Microsoft/vscode#39296]
Hello, I am trying to debug some acceptance tests (It's been a while since I've debugged and I've definitely upgraded VSCode since then).  When I run this via the debugger (Start Debugging) the application runs however I see this message:

**Cannot connect to runtime; make sure that runtime is in 'legacy' debug mode.**

As you can see in my launch configuration below, my protocol is in legacy mode already

**Launch Config**

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "protocol": "legacy",      
      "port": 5859,
      "name": "WebdriverIO",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio.cmd"
      },
      "cwd": "${workspaceRoot}",
      "console": "integratedTerminal",
      // This args config runs only the file that's open and displayed
      // (e.g., a file in test/spec/):
      "args": [
        "--spec",
        "${relativeFile}"
        // To run a specific file, you can also do:
        // "--spec", "specs/testSpec.js"
      ]
    }
  ]
}

```

This produces the following command which is run

**cd 'c:\GitRepositories\acceptance-tests'; c:\GitRepositories\acceptance-tests/node_modules/.bin/wdio.cmd --spec specs/testSpec.js**

If I omit the protocol and port properties I this command is run

**cd 'c:\GitRepositories\acceptance-tests'; c:\GitRepositories\acceptance-tests/node_modules/.bin/wdio.cmd --inspect=46317 --debug-brk --spec specs/dynamicChannel/keywordCoding/chartSpec.js**

And this produces this error message.

**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:46317).**

- VSCode Version: 1.18.1
- OS Version: Windows 10 x64 
- Node Version (in VSCODE): 7.9.0

Steps to Reproduce:

1. Setup a new WebDriver.IO project with a test spec file
2. Use my aforementioned launch configuration

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Is 5859 the correct debug port used by the "${workspaceRoot}/node_modules/.bin/wdio" executable?

If you do **not** specify a port then VS Code will add a "--debug-brk=nnnn" to the executable. If "wdio" cannot handle the "--debug-brk=nnnn" argument then you can prevent VS Code from doing by specifying a "port". But this typically requires that you have to pass another argument to "wdio" explicitely, e.g.:
```js
{
      "type": "node",
      "request": "launch",
      "protocol": "legacy",      
      "name": "WebdriverIO",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
      "runtimeArgs": [
         "--dbg=5859"
      ],
      "port": 5859,
      "console": "integratedTerminal",
      // This args config runs only the file that's open and displayed
      // (e.g., a file in test/spec/):
      "args": [
        "--spec",
        "${relativeFile}"
        // To run a specific file, you can also do:
        // "--spec", "specs/testSpec.js"
      ]
    }

```

I made the "--dbg=5859" argument up. You will have to figure out yourself how to bring "wdio" into debug mode.

On the other if "wdio" accepts a "--debug-brk=nnnn" then you can safely remove the "port" and the "runtimeArgs" from the launch config.

BTW, I've removed "cwd" because it uses your value by default.
In addition the "windows" section should no longer be necessary because VS Code tries the "*.cmd" extension on Windows automatically.

**Comment by markwalsh-liverpool** [comment]
Thanks, you got me on the right track, I changed my launch config to this (protocol change to inspector being the only difference)

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "protocol": "inspector",      
      "port": 5859,
      "name": "WebdriverIO",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio.cmd"
      },
      "cwd": "${workspaceRoot}",
      "console": "integratedTerminal",
      // This args config runs only the file that's open and displayed
      // (e.g., a file in test/spec/):
      "args": [
        "--spec",
        "${relativeFile}"
        // To run a specific file, you can also do:
        // "--spec", "specs/testSpec.js"
      ]
    }
  ]
}
```

And I changed my wido.conf.js file to this:

```
exports.config = {
    debug: true,
    execArgv: ['--inspect=127.0.0.1:5859'],
// cut for brevity
}
```

And it attaches.
