### ISSUE TITLE
Environment variables in launch.json is not processing ${auto-detect-url}

### ISSUE THREAD

**Issue by corretge** [Microsoft/vscode#39294]
When I try to put a launch variable in launch.json
```
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ENV_GLOBAL_CURRENT_URL" : "${auto-detect-url}"
            }
```

I get this value:

```
"${auto-detect-url}"
```

instead

```
"http://localhost:5000"
```

- VSCode Version: 1.18.1 
- OS Version: Windows 10

Steps to Reproduce:

1. Create a C# project
2. Set environment variables for a debug configuration as explained at begin
3. Add  Environment.GetEnvironmentVariable("ENV_GLOBAL_CURRENT_URL")
4. Debug until this instruction

**Comment by weinand** [comment]
I'm not aware of any VS Code variable named `auto-detect-url`.
What is this?

**Comment by corretge** [comment]
Hi @weinand, this is not an environment variable, at the end I want to convert it to one :)

I use this variable because when you add a Debug configuration, automatically is generated this configuration:

```
[...]
            "name": ".NET Core Launch (web)",
[...]
           "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
```

And ```"args": "/C start ${auto-detect-url}"``` works fine

Apologies for my delayed answer.

**Comment by weinand** [comment]
This must a C# thing. Moving issue...

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1933
