### ISSUE TITLE
azure AD is erroring out while invoking FETCH api while using visual studio code

### ISSUE THREAD

**Issue by mahesh8488** [Microsoft/vscode#39299]
I have already posted this question stackoverflow, but not getting any response: https://stackoverflow.com/questions/47469156/azure-ad-is-erroring-out-while-invoking-fetch-api-while-using-visual-studio-code 

Working on VisualStudioCode - 1.17.2
Not working on VisualStudiocode - 1.18.0

The Azure AD authentication for FETCH API is not working in react native after I switched updated VisualStudioCode. I was forced to use Headers in a different way as shown below: 

    fetch("SOMEURL", {
    method: 'GET',
    headers: [['Accept','application/json'],
                    ['Content-Type', 'application/json'],
                    ['Authorization', "Bearer " + token]]
    })

The above call doesnt go past the SignIn page. However, if I change it to the old way, it worked. For this to happen I had to pick a Visual Studio code version which was not the updated.

    headers: {
                        "Accept": "application/json",
                        "Content-Type": "application/json",
                        "Authorization": "Bearer " + token
                    }
The FETCH call with above headers succeeds in older version of Visual studio code. I am using package react-native-azure-ad (0.2.4)
Is this a known issue ?

**Comment by maxibanki** [comment]
What do you mean with `in`? Do you use an extension which live previews your react application?
In general your first code snippet is not correct. The second example should work (i also use the fetch API with such a syntax.)

**Comment by mahesh8488** [comment]
Yes. I use react-native-azure-ad to authenticate my mobile app using AzureAD authentication
