### ISSUE TITLE
Create new file, not input name and scroll can cause file explorer tree to enter a bad state

### ISSUE THREAD

**Issue by wvkmind** [Microsoft/vscode#39297]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unity-tools|Tob|0.1.9
project-manager|ale|0.23.0
Lua|key|0.0.9
python|ms-|0.8.0
cpptools|ms-|0.14.3
Ruby|reb|0.15.0
vscode-icons|rob|7.18.1

---

Steps to Reproduce:

1.选择一个文件夹右键新建文件
2.滚动文件树
3.新建的文件所在位置会出错
（显示bug，重启后没事儿）

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
Translation: After creating a file in File Explorer and scrolling it using mouse, the file's location is not correct on File Explorer.

@wvkmind Can you use English for issue filing?
Can you provide a screenshot of gif showing the problem?

**Comment by wvkmind** [comment]
[2017-12-04 15-38-32.flv.zip](https://github.com/Microsoft/vscode/files/1526069/2017-12-04.15-38-32.flv.zip)

select a folder, new a file ,not input string ,scrolling the files tree.

**Comment by octref** [comment]
@joaomoreno I'm giving this to you since Ben assigned #39343 to you. I'm guessing you did something to add navigation to file explorer recently (Didn't see anything on plan).
