### ISSUE TITLE
Option to switch SCM is not shown

### ISSUE THREAD

**Issue by nikunjkothari27** [Microsoft/vscode#39292]
Visual Studio Code Version: **1.81.1**
Operating System: **Windows x64**

I'm trying to use Perforce as my SCM for my projects, but I'm not able to switch from GIT to Perforce. 
![image](https://user-images.githubusercontent.com/4386901/33359435-c433d944-d4f4-11e7-9454-a7b14b4ef10d.png)

Even the option to switch SCM from the command pallette is not available.
![image](https://user-images.githubusercontent.com/4386901/33359483-fd40ad5c-d4f4-11e7-8c75-211307d3e9c9.png)

This is a clean installation of Visual Studio Code, with only Perforce for VS Code installed.
![image](https://user-images.githubusercontent.com/4386901/33359510-1ed5cdbc-d4f5-11e7-967d-d529e9be44ab.png)

**Comment by Ramaqmar** [comment]
# __[](url)

**Comment by joaomoreno** [comment]
@nikunjkothari27 There is no more switch since a few versions. Multiple providers now coexist in the SCM view.

Your view shows that none are registered though. Did you open a Perforce repo with Code?

**Comment by nikunjkothari27** [comment]
@joaomoreno Sorry I do not understand what you exactly mean by "Did you open a Perforce repo with Code?"

**Comment by joaomoreno** [comment]
Did you login to Perforce at all?
