### ISSUE TITLE
Auto Intelisense for C#

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#393]
It's a use case scenario where a user has already visual studio and c# tools 
Installed on his PC . even then he has to manually setup the vs code for C# Intel'sense 

So why don't we make it automatic .. Either in the first setup process or as an extension that checks 
Ur PC for new compilers and etc...

**Comment by egamma** [comment]
Good idea, but unfortunately the underlying infrastructures (VS uses Roslyn directly, VS Code is using OmniSharp) are too different.
