### ISSUE TITLE
Font Size isn't consistent with other editors

### ISSUE THREAD

**Issue by joeeames** [Microsoft/vscode#3930]
I have noticed that the rendered font size in VS Code is quite a bit smaller than other popular editors for the same font face. In General, I have to set a font size to 15 or 16 to match a 12 pt font in something like sublime. I Have included several screenshots of my windows 8 computer, with the monitor set to 1280x720 (to keep the images small & the differences noticeable), with side by side comparisons of VS Code, Sublime 3, and Word (for reference).

Notice that VS Code is at 16 pt font, and sublime and word are at 12pt font, and they are all darn close to showing the same # of lines. The line spacing also isn't significantly different.

My VS Code Settings
![vs code settings](https://cloud.githubusercontent.com/assets/1072285/13648263/fca8f7aa-e5f4-11e5-9085-085f2b15cadf.png)

My Sublime settings
![sublime-settings](https://cloud.githubusercontent.com/assets/1072285/13648280/0d9df8d0-e5f5-11e5-83e6-94b04c435597.png)

VS Code and Sublime side by side
![vscode vs sublime](https://cloud.githubusercontent.com/assets/1072285/13648284/10674378-e5f5-11e5-95a8-0135e20630d3.png)

Settings in Word
![word settings](https://cloud.githubusercontent.com/assets/1072285/13648285/12c912f4-e5f5-11e5-8dd9-fc453708782b.png)

VS Code & Word Side by Side
![word vs vscode](https://cloud.githubusercontent.com/assets/1072285/13648287/153cbb9e-e5f5-11e5-92c2-7c7c89a6cea5.png)

Here I set both Sublime and VS Code to 16 pt font. The difference is stark.
![sublime at 16 pt](https://cloud.githubusercontent.com/assets/1072285/13648382/81b1569a-e5f5-11e5-82dd-fe9269c0db52.png)

And Finally, I have put the same word side by side with sublime and VS Code both at 16 pt font. Sublime has the dark background, VS Code the light one
![words at 16 pt](https://cloud.githubusercontent.com/assets/1072285/13648433/cd75e730-e5f5-11e5-8603-a03c4900c874.png)

**Comment by alexandrudima** [comment]
The root cause is that our `editor.fontSize` is expressed in pixels (CSS pixels). I will make a change to make this clear in the setting description.
