### ISSUE TITLE
While renaming a file in the explorer, hit Tab to rename the next file

### ISSUE THREAD

**Issue by adigourdi** [Microsoft/vscode#39306]
Hello,

While working on Ionic projects, I happen to duplicate entire folders (Ionic pages), and therefore I have to rename all the files in the folder to match the new folder's name

It would be great to just hit Tab to focus the next file in the list and let me enter the new name for the said file

Thanks in advance

PS. Currently hitting Tab gives focus to the tabs

**Comment by isidorn** [comment]
Fair feature request. We accept PRs that fix this
Code pointer https://github.com/Microsoft/vscode/blob/runtime-extensions/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L392

**Comment by adigourdi** [comment]
Any update on this ? can anybody test the referenced commits to test if they're working ?
I'd be happy to do it myself if I knew how to
