### ISSUE TITLE
Type checking does not work for javascript files

### ISSUE THREAD

**Issue by artin-phares** [Microsoft/vscode#39305]
- VSCode Version: 1.18.1
- OS Version: win7

Reproduces without extensions: Yes

Steps to Reproduce:

1. Create `.js` file with type error, for example:
```js
// @ts-check
let easy = 'abc'
easy = 123 // Error: Type '123' is not assignable to type 'string'
```

**Expected**: line 3 'easy' is highlighted with red, hovering over it shows type error
**Actual**: no highlights

Example taken from [vscode docs](https://code.visualstudio.com/docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files)

Tried all 3 options (none of them help):
- file - `// @ts-check` 
- user settings - `"javascript.implicitProjectConfig.checkJs": true`
- tsconfig.json - `"checkJs": true`

Only works if `Select Language Mode` - `TypeScript`

**Comment by maxibanki** [comment]
![image](https://user-images.githubusercontent.com/17984549/33375841-8a86ee36-d50b-11e7-9192-401325b9805b.png)

**Comment by artin-phares** [comment]
Yep, I've tried `1.19.0-insider` and it works for me either.  

Looks like I need to wait for vscode update. Closing.

**Comment by artin-phares** [comment]
Ok, I got it. There is no such bug in v1.18.1.  
Just had `"javascript.validate.enable": false` option in settings.
