### ISSUE TITLE
Cannot make tweets with more than 127 *Latin* characters in CJK locales

### ISSUE THREAD

**Issue by smikitky** [Microsoft/vscode#39303]
- VSCode Version: Code - Insiders 1.19.0-insider (6e90f8995da4bd999e8983b8e480a34045c1dfcf, 2017-11-29T05:14:15.979Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

This is a continuation of #35214, #35224, #39109 , etc.

Steps to Reproduce:

1. Set Code's `locale.json` to one of `ja`/`ch-*`/`ko` and restart Code.
2. Open "Tweet us your feedback" dialog at the right of the status bar.
3. Type 127 Latin ("single-byte" or "single-width") characters in the box, and it still says "0 characters left" (localized) even after the patch #39109.
    ![screenshot](https://user-images.githubusercontent.com/7779406/33371416-fd096ac4-d53d-11e7-8436-a8e0277d6945.png)

----

What can be tweeted should not depend on the locale. The proper solution is to calculate the ["weighted length"](https://developer.twitter.com/en/docs/developer-utilities/twitter-text.html) of the tweet, possibly using `twitter-text` library, and always compare it with 280.

Also note that, although the "weighted length" itself does not depend on locale, the "characters left" should be displayed differently according to the user's locale.

- In `ja`/`zh`/`ko`, "characters left" displayed on screen has to be `Math.floor((280 - weightedLength) / 2)`. People in those countries still believe the character limit is (roughly) 140, and want to treat `あ`, `漢`, `안` and so on as "one character". This is the behavior we see when we set the language to one of those on the Twitter's default web app.
- In the other locales, "characters left" is simply `280 - weightedLength`.

**Comment by smikitky** [comment]
If calculating the correct weighted length using `twitter-text` seems too much, I think it's better to remove the "character(s) left" function altogether and only display the simplest `length` of the string (like `Using 172 characters`). There are few people who don't know the character limit, and Twitter will do the final validation, after all.

**Comment by smikitky** [comment]
@bpasero I consider this a bug introduced by the recent PR you merged. If VSC won't count the weighted length correctly anytime soon, that's fine. But could you at least remove the pointless check [here](https://github.com/Microsoft/vscode/pull/39109/files#diff-29cee7725da10d621834e130779a81cbR48)? Blocking valid tweets based on the wrong rule is worse than doing no checks. All tweets are eventually correctly validated by Twitter themselves, and VSC's current implementation is leaky even for English speakers, after all. (In English locale you can try to send 200-character emoji tweet, which is invalid)

**Comment by bpasero** [comment]
Yeah I agree, you end up on this screen after submit and after all that is where the validation of length is happening properly:

![image](https://user-images.githubusercontent.com/900690/33494433-865d19b6-d6c3-11e7-95d1-00188f9a31a2.png)

We now have the limit of 280 even though it is not 100% accurate.
