### ISSUE TITLE
Reporting Git failure on Discard changes

### ISSUE THREAD

**Issue by awerlang** [Microsoft/vscode#39308]
- VSCode Version: 1.18.1
- OS Version: Windows 10
- Git: git version 2.15.0.windows.1
- Node: v6.9.1

Steps to Reproduce:

1. Stage a change
2. Click Discard all changes

In fact, it discards the changes, but there's always an annoying messsage: **Error**: Git: Failed to execute git

**Comment by awerlang** [comment]
Is there anything I could do on my part to help troubleshooting this issue? The git output says nothing about it.

**Comment by joaomoreno** [comment]
This always reproduces? Can you send us a screen recording?

**Comment by awerlang** [comment]
It only happened on a specific repo.

I found the culprit in this post-checkout hook:

```
#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git checkout branchname` if a specified file was changed
# Run `chmod +x post-checkout` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2" 
}

check_run package.json "npm run update"
```

It was returning always exit code 1, so VS code would show a failure.

"Solved" by adding a `return 0`. Don't know why it didn't happen before (like a couple weeks, since I moved to a new computer & reinstalled everything)

Thanks for your help!
