### ISSUE TITLE
Stage change jumps right to top after clicking add

### ISSUE THREAD

**Issue by carestad** [Microsoft/vscode#39307]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Click green edge next to line number so the stage change popup appears.
2. Click add button on one of the changes in the middle of document.
3. Watch the popup jump straight back up to the first one after the add button is pressed.

Quite annoying if you want to add two changes in the middle of the document and click the add button and need to scroll a few hundred lines of code down again. It is easier to use `git add -p` right now.

Reproduces without extensions: Yes

![peek 2017-11-29 13-41](https://user-images.githubusercontent.com/65263/33375796-621c7646-d50b-11e7-98d1-a871df3f6ce8.gif)

**Comment by carestad** [comment]
To be fair, I would actually prefer it if I could just add the diff patches without any jumping around, and that it just closes after each add. So maybe a setting to control its behavior?

**Comment by joaomoreno** [comment]
Yeah... maybe closing after each add would be preferable.

**Comment by ramya-rao-a** [comment]
@joaomoreno Is this still for January or can we move it to Feb?

**Comment by mifas** [comment]
When this gonna release

**Comment by mifas** [comment]
@ramya-rao-a Can you please tell us when this gonna be release?

**Comment by ramya-rao-a** [comment]
@mifas As you can see, there is no fix done at the moment for this issue.

You are most welcome to give it a try. Am sure @joaomoreno can provide pointers as to where to get started.

**Comment by joaomoreno** [comment]
It would probably be around this area: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L677

**Comment by tomholub** [comment]
Would you guys accept a PR that introduced a setting, eg `jumpOnRevertChange = true` that, when set to `false`, would prevent any jumping from happening?

**Comment by joaomoreno** [comment]
No setting, just close the widget.
