### ISSUE TITLE
VsCode update everyday!!!!

### ISSUE THREAD

**Issue by PedroGao** [Microsoft/vscode#39300]
I have a question!  Why my vsCode update everyday! I opened it and it tell me,it should be update!!!
WHY!
Please give some solutions! Thank you!

**Comment by DickvdBrink** [comment]
What version are you on? Are you using insider-preview?

**Comment by kieferrm** [comment]
You seem to have our insiders version installed (the one with the green application icon). Please uninstall and install our stable version from https://code.visualstudio.com/Download.  Stable updates every 4-5 weeks.
