### ISSUE TITLE
JSON comments not allowed in JSON files (i.e. tsconfig.json) in latest nightly: code-insider-1.19.0-1511936183_amd64.tar.gz

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode#39317]
Ditto.

**JSON comments not allowed in JSON files (i.e. tsconfig.json) in latest nightly: code-insider-1.19.0-1511936183_amd64.tar.gz**

**Expected behavior:**

_No errors in JSON with comments_

**Actual behavior:**

_The ghost of Douglas Crockford won and all comments are marked as errors._

--R

**Comment by maxibanki** [comment]
No, comments of the form //… or /*…*/ are not allowed in JSON. This answer is based on:

> http://www.json.org
> RFC 4627: The application/json Media Type for JavaScript Object Notation (JSON)
> RFC 7159 The JavaScript Object Notation (JSON) Data Interchange Format - Obsoletes: 4627, 7158

Source: https://stackoverflow.com/a/4183018/6512681

**Comment by kieferrm** [comment]
This comes from the JSON LS.

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/f846ade88025b0ba4d937ac36d065cb503778303
