### ISSUE TITLE
Scrolled position represented as a percentage

### ISSUE THREAD

**Issue by banjoh** [Microsoft/vscode#39320]
I've been using vim for a while and I find it very handy how I can tell the approximate position of my view relative to the entire size/length of the file e.g 50% would mean I've scrolled halfway so far. VScode already gives some of the info in the status bar as ```Ln 455, Col 30``` and a scroll bar position. However, at times the scroll bar is not visible for example when a prevalent word is highlighted.

As a plus it would be awesome to be able to **jump to 40%** by typing ```:40%``` on the command pallete.

**Comment by rebornix** [comment]
It's a good extension candidate ;)
