### ISSUE TITLE
Cannot recognition the destructor name

### ISSUE THREAD

**Issue by LiZeC123** [Microsoft/vscode#39321]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic
- Extensions: 
 C/C++ for Visual Studio Code
Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3

---

Steps to Reproduce:

1. define a class with destructor, such as ~Token()
2. click this destructor with Ctrl key
 Then it will goto the constructor,that's mean it cannot recognition the destructor name

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please try filing an issue against the C++ extension
