### ISSUE TITLE
git code manager window refresh issues

### ISSUE THREAD

**Issue by o02112** [Microsoft/vscode#39322]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2

---

Steps to Reproduce:

1.npm run build compress the code
2.git observer the files change like app.js & app.map.js
3. but VSCode's left side git code manager window is empty, some times you must refresh it manually then it'll show the changed files

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?
