### ISSUE TITLE
.vscode being added in subfolder of workspace

### ISSUE THREAD

**Issue by chriskarkowsky** [Microsoft/vscode#39323]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Start with new (untitled) workspace.  File -> Add folder to workspace.  Select Folder 1 (can be folder with nothing in it)
2. In Debug menu, click Configure or fix 'launch.json'
3. Choose Environment (Node.js) for me.
4. launch.json will be opened.  The path to the file will be in Folder1/.vscode/launch.json

I believe that the .vscode folder should be kept at a workspace level, or you should be able to define where it goes. I would like to have several different apps within my workspace that I can launch separately, and it wouldn't make sense to launch an app from a folder from within another app.

 If using source control on folder1, the configuration of your VSCode debug environment gets added to the project (of course you can tell source to ignore it).

How does VSCode determine the default path to place the .vscode directory?  Can it be edited?

**Comment by isidorn** [comment]
Open debug viewlet, dropdown and you can choose in which folder to create a launch.json
If you just do it via the start debug action we just choose the first

Having a launch.json as a worksapce level we already have a feature request for, thus closing as duplicate

![screen shot 2017-11-29 at 17 55 29](https://user-images.githubusercontent.com/1926584/33387892-be81d99e-d52e-11e7-8dfe-1fad90c2a90e.png)
