### ISSUE TITLE
Allow horizontal split in file editor (like Visual Studio editor)

### ISSUE THREAD

**Issue by jsmarsch** [Microsoft/vscode#39327]
I love the Visual Studio feature that lets me split a view on a file by dragging the handle in the upper-right-hand corner.  (so that I have 2 regions in the editor, each showing a different part of the same file).  Would love to see that feature in VS Code.

**Comment by bpasero** [comment]
You can do so via the split editor action:

![before](https://user-images.githubusercontent.com/900690/33413165-35a2cf0e-d590-11e7-8aee-b4de19fa6875.gif)
