### ISSUE TITLE
TypeScript extension spends a long time creating markers due to slow configuration API

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#39329]
* download `checker.ts` from the TypeScript repo
* type in the editor and profile the extension host
* observe large stall >400ms in the extension host because the file has many errors

[CPU-20171129T163855.297Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1514618/CPU-20171129T163855.297Z.cpuprofile.txt)

![image](https://user-images.githubusercontent.com/5047891/33387168-d7d73cc4-d52c-11e7-82d0-0ae2284449b8.png)

**Comment by alexandrudima** [comment]
It also shows up in the git updating model:

[CPU-20171129T164818.731Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1514655/CPU-20171129T164818.731Z.cpuprofile.txt)

**Comment by mjbvz** [comment]
Looks like this was introduced by calling to `reportStyleCheckAsWarnings` in TS for every marker. We can cache the `reportStyleChecksAsWarnings` setting value to avoid this

**Comment by mjbvz** [comment]
Fixed the TS calls with ae28e56

**Comment by sandy081** [comment]
I see that `getConfiguration()` is being called many number of times. Each call always clones the contents so that any modifications do not impact the originals. I am not freezing the contents. Probably a quick fix is to get the configuration value outside the loop as @mjbvz does.

**Comment by jrieken** [comment]
I think we should consider some sort of copy-on-write solution. Betting on extension authors to use the API in the right ways is a little too brave for my taste.

**Comment by jrieken** [comment]
Also pushed a workaround for git, tho with a bad feeling... The `getConfiguration()`-function shouldn't suck so badly. Basically every extension calling this is some kind of loop it busted.

**Comment by sandy081** [comment]
Yes, agreed. `getConfiguration` was designed such way.

- give access to configuration contents copy for update resilient
- contents are mixed into the configuration object.
- cannot easily access the `value` given a `key`.

`copy-on-write` solution is interesting. @jrieken Any more insights how we can detect that?

**Comment by jrieken** [comment]
Nothing that I have tried but I believe you can hand out a proxy object (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) of the actual underlying configuration object (the truth) which simply forwards read requests and which copies the object when a modification happens

**Comment by sandy081** [comment]
Thanks @jrieken, I will look into that.

Let me know if anybody has concerns in closing this issue and extracting a new issue for investigating above approach?

**Comment by sandy081** [comment]
Closing this and opening a new issue for proxying configuration object - https://github.com/Microsoft/vscode/issues/39576
