### ISSUE TITLE
Show a "*" after the file name for dirty files to make them more obvious

### ISSUE THREAD

**Issue by SebTardif** [Microsoft/vscode#39335]
We cannot tell by looking at the context of the file if it has been modified but not yet saved, it's possible to know that 'maybe' it's the file not yet saved by looking at the Explorer icon (representing all the files open), and we can tell if it's the file IF the explorer tab is selected. Why not putting a * close to the file name on the tab of the editor, which is always visible?

**Comment by ZombieProtectionAgency** [comment]
What version are you running? It looks like it always shows to me.

Open Editors
![image](https://user-images.githubusercontent.com/9204874/33396697-5d6f603e-d517-11e7-81b9-fab840dd9d88.png)

Unsaved file focused with another unsaved file not focused
![image](https://user-images.githubusercontent.com/9204874/33396724-6c6b85d6-d517-11e7-93d6-6ee493a6c317.png)

Saved focused, unsaved not focused
![image](https://user-images.githubusercontent.com/9204874/33396754-829868b0-d517-11e7-93c7-e814c7625641.png)

Unsaved focused, save not focused
![image](https://user-images.githubusercontent.com/9204874/33396773-91a0877a-d517-11e7-974a-a2f832ac8a42.png)

**Comment by webmasterMeyers** [comment]
I agree, while there is an indicator, the grey circle in place of the "close x" it is not obvious and I often wonder which open editor is unsaved. I know something is unsaved because of the blue circle containing the number of dirty editors, that I like.

**I would like to request that a simple '*' be placed to the right of the filename of the "dirty" editor.**  This is fairly standard across many programs and platforms.

**Comment by bpasero** [comment]
@SebTardif ?

**Comment by SebTardif** [comment]
I do now see the dirty clue, which is using a circle instead of the x. And the x disappear if it's not the current tab, but not the circle.

I had to study it to understand it. Similar to what webmasterMeyers is saying, it's kind of an original way of doing this, and not that obvious.

**Comment by imakin** [comment]
this should be crucial, if someone edit so many files he will get lost at which files he has modified and should check one by one on the tab. it should be visible in the side panel. i'm using version 1.19.1

**Comment by dragonwolf83** [comment]
I had no idea about the circle either. It is not intuitive coming from previous editors nor does it stand out from the rest of the tab. By replacing an existing icon, `X`, it is hard to see it change when you save or modify the file. It is better to have motion indicate a change is taking place.

**Comment by usernamehw** [comment]
IDK
```css
.tab.dirty,
.explorer-viewlet .monaco-list-row.dirty {
    background-image: radial-gradient(circle at center, transparent 0, rgba(65, 166, 217, 0.152) 60% , rgba(65, 166, 217, 0.274) 100%);
}
```
![radial_gradient](https://user-images.githubusercontent.com/9638156/34698508-76942d0a-f4e9-11e7-9623-a4a08ebc12b2.png)
![radial_gradient_explorer](https://user-images.githubusercontent.com/9638156/34698739-c875e392-f4ea-11e7-8aa4-602c395b219a.png)

**Comment by usernamehw** [comment]
Related: https://github.com/Microsoft/vscode/issues/26284

**Comment by sumonto** [comment]
It would be nice if VSCode followed the precedent of VSStudio or any other commonly used editors.
This would be an important feature for me for sure!

**Comment by fleed** [comment]
Honestly I was surprised that I couldn't find any evidence on tabs of modified state for files.. I thought that maybe there are some settings that I didn't enable or that the themes that I'm using just don't support the feature.
What's the state here?

I'm using 1.22.1 on Mac with Ayu light theme.

**Comment by bpasero** [comment]
@SebTardif does https://github.com/Microsoft/vscode/issues/26284#issuecomment-427756092 help you?
