### ISSUE TITLE
Save dialog in new workspace window has wrong current directory

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#39336]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1

Steps to Reproduce:

1. For a terminal, run `code .`
2. A new, blank untitled file will be ready. (Doesn't matter. You can also close it and do "New file.")
3. Hit `Cmd+S` to save.
4. The file dialog offers a completely different directory than the workspace directory. To get anywhere sensible, you have to right-click on the workspace root and select "New file", or you can open an existing file and _then_ do "New file".

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@atombender I cannot reproduce, what directory is picked for you? was there maybe another file active in the editor before from which we took the parent directory because it was the last used file?

**Comment by atombender** [comment]
Here's a movie: [vsc.mov.zip](https://github.com/Microsoft/vscode/files/1518696/vsc.mov.zip).

I'm opening a project for the first time. The workspace has no open files from before. The dialog offers me a directory from a different window I was working in before.

**Comment by atombender** [comment]
Thanks!
