### ISSUE TITLE
Tabs name are not visible!

### ISSUE THREAD

**Issue by faycito** [Microsoft/vscode#39338]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.1.0
gitlens|eam|6.2.0
path-autocomplete|ion|1.7.0
autoimport|ste|1.5.3
gitblame|wad|2.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by kieferrm** [comment]
Just in case...there is a setting for editor tabs: `"workbench.editor.showTabs": true`.
