### ISSUE TITLE
Get prompted to install recommended extensions after having installed all recommendations

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#39332]
- clone this repository: https://github.com/Microsoft/vscode-connect2017
- open the workspace contained in this repository `ConnectDemo.code-workspace`
- open the workspace
- you get recommendations
- select 'install all' 
- wait until all the extensions are installed
- reload
- you get prompted to install the recommended extensions (see below).

![image](https://user-images.githubusercontent.com/172399/33388309-ead6e286-d52f-11e7-8e61-76d5006bf6ca.png)

**Comment by ramya-rao-a** [comment]
Occurs when any of the recommended extensions are listed using the wrong casing.
Fix is to make the check case insensitive

**Comment by tysonmatanich** [comment]
I em encountering this with the following:

**Comment by ramya-rao-a** [comment]
@tysonmatanich What version of VS Code are you using?

**Comment by tysonmatanich** [comment]
1.19.1

**Comment by ramya-rao-a** [comment]
@tysonmatanich I can repro in 1.19.1 but not in the latest Insiders from https://code.visualstudio.com/insiders. Can you try the Insiders?

**Comment by tysonmatanich** [comment]
Also repros in 1.19.2 but is fixed in 1.20.0-insider. Thanks!
