### ISSUE TITLE
hsl / hsla color swatches are incorrect for 0% saturation

### ISSUE THREAD

**Issue by AmeliaBR** [Microsoft/vscode#39339]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. In a CSS file, define a property value with `hsl(0,0%,100%)` or `hsla(0,0%,100%,1)`
2. Wait for the color swatch to appear
3. The color should be white (100% lightness), but instead appears as black.  The pop-up color picker is likewise initialized to rgb(0,0,0).

The problem is specific to 0% saturation value; isn't affected by the hue value, and applies for any lightness value (e.g., 50% lightness should be gray).  Probably incorrect handling of a divide-by-zero error in the color conversion functions.

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Already fixed, you can have the correct one in Insider or wait for our next Stable.

**Comment by AmeliaBR** [comment]
Thanks! I should have remembered to search *closed* issues, too,
 so I would have found https://github.com/Microsoft/vscode/issues/38250.
