### ISSUE TITLE
Slow search in vscode workspace on Windows

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#39341]
1) Open the vscode workspace
2) Go to the search viewlet
3) Enter the following search string: `Comments are not permitted in JSON`
4) Deselect the 'use exclude settings and ignore files` button
5) <kbd>Enter</kbd>

-> search takes > 3 minutes
-> render active at 18%
-> rg active at 4.5%

**Comment by roblourens** [comment]
Must be MsMpEng then right?

**Comment by kieferrm** [comment]
For perceived performance it doesn't matter what slows down the search.  I haven't run traces, but we should do so.
