### ISSUE TITLE
Cannot type certain characters in rename

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#39343]
Using latest insider:

1. Try rename a file in File Explorer
2. Type j or k
3. Active selection goes up / down (instead, j / k should go to new file name)

**Comment by njustice4all** [comment]
Type a, j, k, l weird action

**Comment by schnabel45** [comment]
a, j, k, l, and backspace seem to be working for me. Home, end, delete and arrows are all broken for me though, this means using ctrl for jumping between words is also broken.

Version 1.19.0-insider
Commit 6e90f8995da4bd999e8983b8e480a34045c1dfcf
Date 2017-11-29T05:14:15.979Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by joaomoreno** [comment]
This is already fixed.
