### ISSUE TITLE
Minimap box shadow show up just after scroll, not by default

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#39355]
Hello,

- VSCode Version: 1.18.1 (x64)
- OS Version: Windows 10

Screenshot #1 (Before scroll)
![01](https://user-images.githubusercontent.com/9152330/33419876-a4f975a2-d5c1-11e7-989d-9a3468d75610.png)

Screenshot #2 (After really small scroll)
![02](https://user-images.githubusercontent.com/9152330/33419889-b6307e10-d5c1-11e7-992b-dfc1750b987b.png)

Thanks.

**Comment by JackMordaunt** [comment]
My guess is that this is not a bug. The box shadow indicates your page is "under" the minimap. 
When the full page is in view, it's not underneath anything, so no shadow. 

The same behaviour can be observed for the page tabs. The shadow appears once your page is "underneath" or in a "scrolled" state. 

This way you can more easily visually identify when your page is in it's (0, 0) position or somewhere scrolled in the middle. 

Please correct me if I'm wrong! :)

**Comment by dehghani-mehdi** [comment]
If I got you correctly, after a very tiny scroll, I got back to no-scroll position, but because of that scroll, I can see box-shadow.

For pages/tabs that has not any scroll (because of few lines of code), minimap has no box-shadow, obviously because of no ability to scroll the page.

**Comment by JackMordaunt** [comment]
Yes, that's my take on it.

**Comment by alexandrudima** [comment]
@JackMordaunt is correct. We add that shadow when the `scrollLeft` is not at its maximum value, to indicate that text *might be behind the minimap*.
