### ISSUE TITLE
Garbled code is shown when opening changes in source control if a file is encoded with UTF-16 LE

### ISSUE THREAD

**Issue by tonkon** [Microsoft/vscode#39351]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.3.0
githistory|don|0.2.3
gitlens|eam|6.2.0
vscode-great-icons|emm|2.1.20
azure-functions-tools|joh|0.3.1
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.4.0
vscode-azurefunctions|ms-|0.2.0
vscode-cosmosdb|ms-|0.2.1
mssql|ms-|1.2.1
azure-account|ms-|0.2.2
azurecli|ms-|0.3.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
vscode-azureextensionpack|ms-|0.0.7
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
vscode-docker|Pet|0.0.22
vscode-hexdump|sle|1.6.0
usql-vscode-ext|usq|0.2.7
application-insights|Vis|0.4.1
azure-iot-toolkit|vsc|0.4.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Initial a Git repo 
2. Open the repo by VS Code and create a new JSON file, save with encoding UTF-16 LE
3. Commit the JSON file
4. Change a little bit in the JSON file
5. Go to "Source Control" view, double click the file and the garbled code will be shown.
![vscodesourcecontrolviewgit](https://user-images.githubusercontent.com/3355407/33417354-1b7a9eee-d5dc-11e7-8d94-d89c2d89e1cc.png)

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/21146
