### ISSUE TITLE
Editor cursor moves to document end after save

### ISSUE THREAD

**Issue by computer0101** [Microsoft/vscode#39350]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.4.0
LiveServer|rit|3.0.0
vscode-icons|rob|7.18.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by computer0101** [comment]
After saving file the cursor goes to end of document instead of staying at current position. This is really annoying.

**Comment by cleidigh** [comment]
@computer0101 
Can you give some more details, file type, sequence of events, behavior with all extensions disabled...

**Comment by computer0101** [comment]
This usually happens in files having extensions like html, js, css.
Whenever I save the file cursor moves immediately to last line of document instead of staying on current line(the line I was on when I save the document.) so I have to scroll all over to top where I have to edit the document.

**Comment by bmewburn** [comment]
I've experienced this too in PHP files. Though not on save, it seems random and intermittent and I haven't found a way to reliably reproduce. It has happened prior to 1.18 too.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
vscode-intelephense-client|bme|0.8.2
php-docblocker|nei|1.3.2

**Comment by ramya-rao-a** [comment]
This is caused by the JS-CSS-HTML-Formatter extension and is being tracked in https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/83
