### ISSUE TITLE
Please return ReactJS syntax highlight from the old Dark+ theme.

### ISSUE THREAD

**Issue by technoiswatchingyou** [Microsoft/vscode#39353]
Please return ReactJS syntax highlight from the old Dark+ theme.

![screen shot 2017-11-30 at 5 22 40 pm](https://user-images.githubusercontent.com/25575840/33418888-b2cbe7f0-d5f3-11e7-88d7-48954deba92d.png)

- VSCode Version: 1.18.1
- OS Version: Mac OSX 10.13.1

**Comment by mjbvz** [comment]
This change was made in 1.13, so unless you have been using a really old VS Code build I suspect something else changed on your machine.

You can always use a custom theme if you would like to change it back
