### ISSUE TITLE
Themes doen't uninstall in reloaded VSCode, cause by prev uninstalled theme

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#39354]
Hello,

- VSCode Version: 1.18.1 (x64)
- OS Version: Windows 10 (x64)

Steps to Reproduce:

1. Open up VSCode
2. Install two themes say A and B
3. Reload VS Code
4. Head to Extensions
5. Select one of installed theme, click on `Uninstall` button (_VSCode shows a confirm dialog)
6. Click on `OK`
7. Click on `Relaod` button
8. Now uninstall the second theme

Expected: Confirm dialog should be shown and the theme should be uninstalled.
Observed:  The `Confirm` doesn't show up and the theme will not Uninstalled even after 5 mins

How to fix?
Simply by closing and re-opening the VSCode

Reproduces without extensions: No, _it's related to extensions I think_

Thanks.

**Comment by sandy081** [comment]
@dehghani-mehdi After step 5, does the uninstalled them is still shown in installed extensions list?

**Comment by dehghani-mehdi** [comment]
@sandy081 no, the first try is successful, but after reload (cause by successful uninstall) the issue happens.

**Comment by sandy081** [comment]
@dehghani-mehdi So, you do not see the extension in the `Installed extensions` list after reload? So you search for the extension again and Install it again?

**Comment by dehghani-mehdi** [comment]
@sandy081 here is example/more details:

I installed 2 theme, (let's say) `theme A` and `theme B`. both installed successfully. 
Then I decided to remove both, so in extensions tab/section select `theme A` and click on `Uninstall` button, confirm shows up, click on `OK`, after few seconds the `Reload` button shows up, click on that, after reload `theme A` doesn't exist anymore (thanks to VSCode), the problem is, if I select `theme B` and click on `Uninstall`, 2 things will be happened:
1. The uninstall confirm won't show up
2. The theme won't be removed and the `Uninstalling` stay for ever

_Notice that if I close the VSCode (click on X button) and open it again, I can uninstall the `theme B` with no issue._

So, are we okay on this?

**Comment by sandy081** [comment]
@dehghani-mehdi I cannot reproduce it. Please see the attached video if I am missing any steps.

![kapture 2017-12-05 at 9 57 08](https://user-images.githubusercontent.com/10746682/33598360-bc612016-d9a2-11e7-9805-dea56bd28581.gif)

1. Can you check if there are any errors in console. Use commands `Toggle Developer Tools` and `Toggle Shared Process`

2. Can you check to reproduce it on latest insiders - https://code.visualstudio.com/insiders/

**Comment by dehghani-mehdi** [comment]
@sandy081 I'll try, but can you click on the theme name and click on uninstall button in main area instead of selecting Uninstall from context menu?

**Comment by sandy081** [comment]
Yeah, I tried from the editor too and it is working

**Comment by dehghani-mehdi** [comment]
It's weird, I could not reproduce the issue!
Sorry and thank for your time, if I faced to the issue again, I'll update this issue with more info.
