### ISSUE TITLE
Images / media files cause error in git preview

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#3935]
This is a small issue but happens to me often. 

I can see .png and other media files fine until I use git features in VS Code. When I click on an image in the git viewlet I get the following error. 

```
Error: Unable to open "<image name>": File seems to be binary and cannot be opened as text. 
```

This may be intended behavior, but I believe it should be changed. I'd like to see the image and not have to see an error each time I click on a file.

**Comment by joaomoreno** [comment]
#35749
