### ISSUE TITLE
git推送问题

### ISSUE THREAD

**Issue by picksun** [Microsoft/vscode#39356]
用vscode打开过项目之后，代码就无法commit了，commit就报错，不用vscode打开，就可以commit，请问是什么原因

**Comment by Rhuaer** [comment]
这种问题是不会有人给你解答的。因为你也没有指明vscode版本，也没有说明os的版本，装了什么extension，在别人的机器上是否必现，不能commit时有没有错误信息。

建议自己做一个排除测试，实在不行，那就不用vscode呗。

最后，这里使用英文发issue更方便沟通，起码自己用Google翻译一下再放上来呗

**Comment by RobertoMalatesta** [comment]
@picksun 
它看起來像在git配置中的一個問題，vscode git工作正常。
嘗試從項目目錄中的命令行使用git。再見！

_It looks like a problem in yout git configuration, vscode git works OK.
try using git from the command line in the directory of your project._ 

--R
