### ISSUE TITLE
Debugging now takes more time to initiate. 

### ISSUE THREAD

**Issue by Bizay** [Microsoft/vscode#39352]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-dash|dee|1.7.1
jupyter|don|1.1.4
python|don|0.7.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.0.2
php-pack|fel|1.0.1
Angular2|joh|2.11.2
vscode-codemetrics|kis|1.11.1
python|ms-|0.8.0
azure-account|ms-|0.2.2
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
vscode-react-native|vsm|0.5.7
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What type of debugging are you talking about?
Please provide steps and explain what you are experiencing.
