### ISSUE TITLE
can not use width bootstrap comfortably

### ISSUE THREAD

**Issue by qiphon** [Microsoft/vscode#39358]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
php-debug|fel|1.12.1
php-intellisense|fel|2.0.2
php-pack|fel|1.0.1
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
phpcs|ika|0.7.0
mark-as-excluded|jcm|0.2.5
webpack|jer|2.0.2
rem-px|ris|0.0.3
open-in-browser|tec|1.1.0
python|tht|0.2.3

---

Steps to Reproduce:

1. when i writed "div.form-group" over.The "Tab" can not finish my tag
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Are you trying to use emmet? What type of file?
