### ISSUE TITLE
Code not reopening last used folder when launch from gnome-shell

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#39357]
- VSCode Version: 1.19 insider
- OS Version: Ubuntu 17.10 x64

Steps to Reproduce:

1. Open Code by clicking the icon within gnome-shell (using bash directly will not trigger issue)
2. Notice that a file named stdin-\<some letters\>.txt is opened instead of the last folder.

**Comment by borgdylan** [comment]
This will only reproduce by launching through the GUI shell ie. by means of a .desktop file. Whenever I used code-insiders command in bash, this did not happen. I have code pined on my task bar, so I tend to press the icon to launch quickly instead of launching from bash.

**Comment by bpasero** [comment]
This would indicate that the gnome-shell is executing our script that should only be used from a terminal. @Tyriar any clues?

@borgdylan can you share a screenshot or screencast how you launch Code?

I cannot reproduce doing it like this:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/33422500-2dca2e00-d5b6-11e7-9045-4804f324ba05.gif)

**Comment by borgdylan** [comment]
The shell is executing my custom script. The issue does not happen if I execute the script from a terminal.

**Comment by borgdylan** [comment]
#!/usr/bin/env bash

export PATH=$PATH:/home/dylan/android-toolchain/sdk/platform-tools:/home/dylan/xamarin-android/tools/scripts

cd /home/dylan/Downloads/vscode-insiders
exec "./bin/code-insiders" $@

**Comment by borgdylan** [comment]
That script is due to me needing to put android tools on the path when building.

**Comment by borgdylan** [comment]
I will try that.

**Comment by borgdylan** [comment]
That worked.

**Comment by borgdylan** [comment]
I had to change the way I install code on disk. Had to move my custom script to the bin directory alongside the script. I also changed my path and the .desktop file. All is in order now.  Thank You.

**Comment by bpasero** [comment]
@borgdylan great!
