### ISSUE TITLE
Cant exclude emmet from php filetype

### ISSUE THREAD

**Issue by drKnoxy** [Microsoft/vscode#39369]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
sort-lines|Tyr|1.3.0
vscode-custom-css|be5|2.5.0
vscode-icontheme-nomo-dark|be5|1.3.4
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
eslint-disable-snippets|drK|1.1.4
prettier-vscode|esb|0.26.0
php-debug|fel|1.12.1
php-intellisense|fel|2.0.2
code-runner|for|0.8.4
macros|ged|1.2.1
vscode-styled-components|jpo|0.0.10
Go|luk|0.6.67
php-docblocker|nei|1.3.2
annotator|ryu|0.10.1
ayu|tea|0.10.0
gitblame|wad|2.2.0
vscode-import-cost|wix|2.5.1

(9 theme extensions excluded)

---

Steps to Reproduce:

1. update your user setting to include `"emmet.excludeLanguages": ["php"]`
1. open a .php file
2. in a function start typing `var_dump($bt`
3. *err* you get emmet suggestions

Reproduces without extensions: Yes

user settings, tried toggling the php.suggest.basic with no success
```
// Place your settings in this file to overwrite the default settings
{
  "editor.cursorBlinking": "solid",
  "editor.fontFamily": "Consolas, Source Code Pro, Lobster",
  // Consolas, Source Code Pro, Menlo, Go Mono,  Fira Code,
  "editor.fontSize": 15,
  "editor.formatOnSave": false,
  "editor.letterSpacing": 0.7,
  //   "editor.lineHeight": 22,
  "editor.minimap.enabled": false,
  "editor.renderWhitespace": "boundary",
  "editor.rulers": [100, 160],
  "editor.tabSize": 2,
  "explorer.autoReveal": false,
  "explorer.openEditors.visible": 0,
  "vscode_custom_css.imports": ["/Users/awknox/.vscodestyles.css"],
  "files.associations": {
    "*.js": "javascriptreact"
  },
  "files.trimTrailingWhitespace": true,
  "workbench.editor.enablePreview": false,
  "workbench.iconTheme": "vs-nomo-dark",
  "workbench.colorTheme": "Ayu Dark",

  // Plugins
  "prettier.singleQuote": true,
  "prettier.printWidth": 100,
  "prettier.trailingComma": "es5",
  //   "php.suggest.basic": false,
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 0,
  "workbench.panel.location": "right",
  "macros": {
    "revealSide": ["workbench.files.action.showActiveFileInExplorer", "workbench.view.explorer"]
  },
  "emmet.excludeLanguages": ["php"]
}
```

**Comment by ramya-rao-a** [comment]
The setting `emmet.excludeLanguages` works as expected for syntaxes directly supported by emmet like html, css etc.
php is mapped to html and such mapped languages weren't getting excluded.
This has now been fixed.

Thanks for reporting @drKnoxy

**Comment by drKnoxy** [comment]
thanks @ramya-rao-a !
