### ISSUE TITLE
Color scheme of code

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39368]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

I'm not quite sure is it a bug, or not.
I've done minimization of code with "webpack -p" command, and I've got bundle.js file, that looks like this:

![color-scheme](https://user-images.githubusercontent.com/24613274/33429747-bf1e2198-d5d6-11e7-90c2-fec742337325.png)

So, is it OK, that starting from line 24, code is just simple white, without any colorization?

**Comment by mjbvz** [comment]
We do not attempt to syntax highlight any lines longer than 20000 characters for performance reasons
