### ISSUE TITLE
Extension host terminated unexpectedly 

### ISSUE THREAD

**Issue by oluwatimilehin** [Microsoft/vscode#39366]
- VSCode Version:  1.18.1
- OS Version: Windows 10 Home 1703

Steps to Reproduce:

1. Install ms-python extension from Microsoft
2. Wait for an amount of time after opening Python file

Reproduces without extensions: No

I don't think it's the python extension causing the issue because I haven't been able to use VS code for months because of the "Extension host terminated unexpectedly" with or without the python extension. This is a clean install of VSCode and the only extension I have is the python one from Microsoft.  

I'm getting this error on the console.
`
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9 Extension host terminated unexpectedly.
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9'

**Comment by isidorn** [comment]
Reproducalbe steps would be great.
Also can you reproduce without any extension.
Also you could use vsocde insiders, f1 > runtime extensions to detect what extension might be causing this

**Comment by OraCool** [comment]
I am getting the same problem.
![image](https://user-images.githubusercontent.com/127194/33549864-021f790a-d8fd-11e7-80af-8c302ec97471.png)
**VS Code**:
Version 1.19.0-insider
Commit 8a12b294de610aab61c32c02c7c148d981cf07e4
Date 2017-12-04T05:14:19.063Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
**OS:**
![image](https://user-images.githubusercontent.com/127194/33549933-3b3c1d42-d8fd-11e7-9602-bfeb370b452b.png)
Steps to Reproduce:

- Install ms-python extension from Microsoft
- Create new empty py file.
- Wait for an amount of time after opening Python file. Error appears.

Reproducible with all extensions disabled for the workspace

**Error in developer tools console:**
![image](https://user-images.githubusercontent.com/127194/33550120-d7473578-d8fd-11e7-87f7-d09da13499d1.png)

**Comment by isidorn** [comment]
Please file these issues to the extension here https://github.com/DonJayamanne/pythonVSCode

**Comment by oluwatimilehin** [comment]
@isidorn 
It's not just that extension. I've tried it with many other VS Code extensions and I have been getting that error for months. Except you're claiming that many major VS Code extensions are faulty.

**Comment by isidorn** [comment]
@oluwatimilehin please file issues for all extensions that are causing this.
As I already mentioned you can get vscode insiders and try the F1 > runtime extensions to more easily detect which extension is to blame. Thanks
