### ISSUE TITLE
When I hit a breakpoint vscode opens a new readonly version of the file in Vagrant

### ISSUE THREAD

**Issue by stilllife00** [Microsoft/vscode#39360]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
debugger-for-chrome|msj|3.5.0
ReactSnippets|xab|1.7.0
---

Steps to Reproduce:

1. Use Vagrant (Linux guest on a Windows 10 host)
2. Debug a project
3. Hit a breakpoint
4. The file which hits the breakpoint is open as read only and his path is the vagrant box path /vagrant/myfolder/myfile which is ofcourse not a valid path in the Windows host
5. The other files (without breakpoints) they have the proper path windows path (C:\dev\myfolder\myfile)
**IMPORTANT NOTE**: I am using webpack with devtool set to `cheap-module-source-map`, it might have an impact on this

Reproduces without extensions: Yes

**Comment by weinand** [comment]
If you are using WSl the you might want to try the "useWSL" flag in your launch config.
See the WSL topic under https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging
