### ISSUE TITLE
Focus lost from editor when clicking into area below suggest docs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39367]
Steps:
* open suggest with docs to the side
* click into the seemingly empty area below docs

I would expect suggest to close. Instead focus seems to be somewhere but not in the editor anymore, so that e.g keybindings navigation does not work anymore.

![image](https://user-images.githubusercontent.com/900690/33425355-c468f636-d5be-11e7-8c3e-7e7c7749ef89.png)

**Comment by kieferrm** [comment]
@ramya-rao-a there is a suspicion that this is related to recent changes in the list service.

**Comment by bpasero** [comment]
@kieferrm @ramya-rao-a I talked to @joaomoreno and we think it is unrelated

**Comment by ramya-rao-a** [comment]
Duplicate of #38484
