### ISSUE TITLE
Test: code --status

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39376]
Refs: https://github.com/Microsoft/vscode/issues/39262

- [x] macOS @rebornix 
- [x] Linux @mjbvz
- [x] Windows @weinand 

Complexity: 3

We added a new command line argument "`code --status`" that prints some diagnostics output to the console. You can run this command only when Code is already running (otherwise an info message is printed). 

Verify that the output:
* contains environmental info about the system
* a full list of processes that are running including their CPU/Memory usage
* some information about the folders opened (works across multiple windows and also for multi root workspaces)
* under Windows ensure that it works with a 64 and a 32 bit version of VS Code.

**Comment by dbaeumer** [comment]
@weinand can you please retest. I fix the space problem under Windows.

**Comment by weinand** [comment]
will do.

**Comment by weinand** [comment]
@dbaeumer "--status" on Windows is very slow: it takes 8 seconds until the output appears in the console.
But I believe this is expected because Windows has no historical cpu load and memory data and the "--status" command needs to accumulate that first, correct?

**Comment by dbaeumer** [comment]
@weinand yes that is expected. Windows doesn't have any historical data so I sample for 5 seconds. May be we should print something to the console that under Windows this may take some time.
