### ISSUE TITLE
Feature request: Make the command palette symbol configurable

### ISSUE THREAD

**Issue by huettenhain** [Microsoft/vscode#39379]
My preferred way to access the command palette in Visual Studio Code is to access the quick open interface and type the character `>`. Unfortunately, with a German language keyboard layout, the character `>` is an uncomfortable choice, `:` would be much easier to type. It would be great if the symbol was configurable via `settings.json`. I am picturing a setting like
```json
{
    "workbench.commandPalette.commandSymbol": ":"
}
```
I do realize that there are workarounds for this and it is certainly not a high priority enhancement. However, I somewhat hope that the effort of implementing this is equally small.

**Comment by usernamehw** [comment]
What's wrong with accessing it with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> or <kbd>F1</kbd>?

**Comment by huettenhain** [comment]
@usernamehw I will, again, confess that there will be many workarounds for the problem and I would like to avoid digressing, there is no need to have a lengthy discussion about my personal preferences. I have already thought of the following workarounds so far:
- Configuring two different keyboard shortcuts for command palette and quick open, similar to what you suggest
- Configuring two keyboard shortcuts chording from the same first combination
- Configuring a shortcut for the command palette and accessing quick open by pressing backspace after that

Frankly, I would prefer a configurable bang to all of these. Again, this is personal preference, and I can understand completely if this were not considered for lack of interest by the community and/or the developers.
