### ISSUE TITLE
Rename symbol on a HTML tag inside of JSX globally renames all tags

### ISSUE THREAD

**Issue by xirzec** [Microsoft/vscode#3937]
1. Open a project that uses TypeScript + JSX (with react.d.ts loaded)
1. Put the cursor over a common HTML tag like `<div>`
1. Hit F2 to rename symbol
1. Rename the div to something else (like span)

Expected: Just the matching open/close is renamed to `<span>`
Actual: Every div in **every** JSX file is now a span and even react.d.ts has had its div attribute in the HTML tag names renamed to span

VS Code version: 0.10.10

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7458
