### ISSUE TITLE
[BUG] Moving Code Blocks mess up Code Spacing

### ISSUE THREAD

**Issue by achillesrasquinha** [Microsoft/vscode#39373]
- VSCode Version: 1.18.1
- OS Version: mac OS Siera

Not sure whether this is ES6 specific but after moving the code block top to bottom and top again, the code spacing get's messed up.

![](http://g.recordit.co/iAfQWkwUqU.gif)

**Comment by achillesrasquinha** [comment]
Also, vscode fails to add the `bug` label after stating it on my title. :smile:

**Comment by rebornix** [comment]
@achillesrasquinha thanks for reporting, dup of https://github.com/Microsoft/vscode/issues/33025, let's track it there.
