### ISSUE TITLE
Display number of open terminals next to TERMINAL link

### ISSUE THREAD

**Issue by papadi** [Microsoft/vscode#39372]
It would be nice if we could see the number of open terminals. See suggested screenshot...

<img width="1110" alt="screenshot_3" src="https://user-images.githubusercontent.com/3359377/33438976-94df97a2-d5ec-11e7-8323-f79644d457b5.png">

**Comment by Tyriar** [comment]
No plans to make this change since no other panels do this (and it would shift the UI around). This will eventually be fixed by having tabs in the terminal https://github.com/Microsoft/vscode/issues/10546

**Comment by papadi** [comment]
Absolutely! I suggested this in another ticket but it was explained to me that this is unlikely to be implemented. I'm happy that it's possible!
