### ISSUE TITLE
Animated gifs not working in extension gallery

### ISSUE THREAD

**Issue by oliversturm** [Microsoft/vscode#39374]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.10

I have just published this small extension: https://marketplace.visualstudio.com/items?itemName=oliversturm.fix-json

In the browser, this page correctly shows two animated gifs. Both images are also shown correctly in VS Code when I select the file in my extension project (in Explorer). I guess this means that the images are technically intact - however, when I find my extension in the Extension Gallery in VS Code, the README shows up without the images:

![image](https://user-images.githubusercontent.com/4730969/33441702-38346c72-d5eb-11e7-8437-11d020426df9.png)

I can't see that content in Developer Tools, so I have no idea why the images aren't loaded.

**Comment by mjbvz** [comment]
Doesn't seem to work in browser either: 

![screen shot 2017-11-30 at 11 18 47 am](https://user-images.githubusercontent.com/12821956/33450318-43c2616e-d5c0-11e7-8c77-51db49df5d88.png)

**Comment by oliversturm** [comment]
Hm... okay, thanks for this, @mjbvz  :)

I think I have found out what the problem is. It turns out the github repo I was using to develop the extension is private, and the marketplace page links to the images in the github repo.

Obviously my repo isn't meant to be private. However, before I change it - I don't understand why that breaks the images. As far as I saw, a call to `vsce package` packs up the images together with the README.md from the project. I was expecting the marketplace site to use the content of that archive that is uploaded, and to serve those images directly. Instead it uses the links to github that don't work right now. Is that the intended behavior?

**Comment by mjbvz** [comment]
What does the markdown look like for the images?

**Comment by oliversturm** [comment]
Like this: `![Running Fix JSON](images/run.gif)`

**Comment by mjbvz** [comment]
I believe that vsce defaults to rewriting relative image urls relative to your extension's github page: https://github.com/Microsoft/vscode-vsce/blob/61050cfe886484dc19e25bc0fd6cf6585855b420/src/package.ts#L409

As far as I know, we don't separately serve package contents on the marketplace, so images must be served from somewhere else

@joaomoreno Can correct me if this is wrong

**Comment by oliversturm** [comment]
I just found that [this page](https://code.visualstudio.com/docs/extensions/publish-extension) states: 

> A README.md file at the root of your extension will be used to populate the extension's Marketplace page's contents. vsce will modify README links for you in two different ways: If you add a repository field to your package.json and if it is a public GitHub repository, vsce will automatically detect it and adjust the links accordingly. ...

According to that, the links should not have been modified in my case. Perhaps this is a bug of some kind.

I'm going to make my repo public now.
