### ISSUE TITLE
Memory leak when using integrated Powershell and large log outputs

### ISSUE THREAD

**Issue by michael-golfi** [Microsoft/vscode#39378]
- VSCode Version: 1.18.1
- OS Version: Windows 10 v1709
- Build: 16299.64

Steps to Reproduce:

1. Open a powershell window
2. Run a command that spews a large log to the window

Reproduces without extensions: Yes

![capture](https://user-images.githubusercontent.com/1388500/33450439-a6ecfdda-d5c0-11e7-8cb6-936ef9124908.PNG)

I was running the commands and getting the output [over here](https://github.com/golang/dep/issues/1417) and VSCode doesn't seem to be able to cleanup powershell output well. Likewise, the powershell process in the same task manager ran the same commands. I needed to use a native powershell console in order to continue so that VSCode doesn't lag.

I believe this should be reproducible with any large log output in VSCode.

**Comment by michael-golfi** [comment]
I'm not too familiar with the "new" GPU metric but I'm also curious, why does VSCode consume any GPU - let alone 17%?

**Comment by Tyriar** [comment]
For integrated powershell please create an issue against the extension repo https://github.com/PowerShell/vscode-powershell

RE GPU: The terminal is rendered using the GPU, read more here https://code.visualstudio.com/blogs/2017/10/03/terminal-renderer
