### ISSUE TITLE
Reopen last files

### ISSUE THREAD

**Issue by MichaelCsitkovics** [Microsoft/vscode#3938]
If I close vscode and open it again the window is empty. Before 0.10.10 vscode have saved the file(s) and reopend the file(s) on the next start.

**Comment by sci4me** [comment]
Maybe make it an option in preferences?

**Comment by bpasero** [comment]
@MichaelCsitkovics I would hope we did not introduce a bug here, are you sure this used to work before 0.10.10? We only reopen files if you open a workspace folder, but not for an empty workspace.

**Comment by MichaelCsitkovics** [comment]
Thx, works perfect in 0.10.11!
