### ISSUE TITLE
Terminal is unusable. 

### ISSUE THREAD

**Issue by lramirez925** [Microsoft/vscode#39383]
When launching code and trying to start the integrated terminal I am not able to enter text. 

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-cflint|Kam|0.2.4
vscode-docker|Pet|0.0.22
gitignore|cod|0.5.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
gitlens|eam|6.3.0
vscode-html-css|ecm|0.1.8
vs-code-xml-format|fab|0.1.5
live-html-previewer|hdg|0.3.0
coldfusion|ili|0.0.11
mssql|ms-|1.2.1
PowerShell|ms-|1.5.1
java|red|0.14.0
jenkinsfile-support|sec|0.1.0
vscode-todo-highlight|way|0.5.11

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes

**Comment by lramirez925** [comment]
So reinstalling from a download via the visual studio code site did not fix the issue but when i reinstalled via brew cask it seems to have fixed the issue.

**Comment by lramirez925** [comment]
After further testing it looks like the prompt is being pushed out of screen when the terminal window is a certain height. When I dock it to the right the prompt disappears out of screen and when I increase the height when it is docked at the bottom of the screen at about 1/3 my window size the prompt disappears out of screen.

**Comment by Tyriar** [comment]
Sorry about the delay, was on vacation. Can you post a screenshot demonstrating the issue?
