### ISSUE TITLE
[debug] `runInTerminal` request fails if terminal command prompt is not clean.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#39385]
- VSCode Version: Version 1.18.1
- OS Version: Ubuntu 16.04

1. Debug adapter sends `runInTerminal` request to spawn debuggee in the integrated terminal.
2. Debug session ends.
3. User types something into the terminal that is left over (possibly by mistake).   
4. A new debug session starts, debug adapter sends `runInTerminal` again with the same title, so terminal is reused.
5. Because VSCode runs commands in its terminal by simply sending them to stdin, the garbage on the command prompt is executed as prefix to the command.   This usually causes a syntax error in the shell, but in the worst case might accidentally execute something the user would *definitely* not like to be executed (think `rm -rf / ;`).

**Comment by weinand** [comment]
I have no idea how to fix this.

**Comment by weinand** [comment]
Thanks for providing implementation ideas.
Since I do not deem this problem as really important, I have no plans to fix this anytime soon.
But may be you are interested in submitting a PR?
