### ISSUE TITLE
Markdown: Change Preview Security Settings command does not work when preview is active

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39387]
Steps to Reproduce:

1. Open markdown preview
2. Make sure markdown preview is active editor
3. Run the `Markdown: Change Preview Security Settings` command in the command palette

**Bug**
Nothing happens

**Comment by mjbvz** [comment]
Root cause is that `vscode.window.activeTextEditor` is undefined for html previews

**Comment by mjbvz** [comment]
Fixed work switching markdown previews to use webviews

**Comment by aeschli** [comment]
Trying to verify there is still nothing happening when the preview has the focus:
![markdown](https://user-images.githubusercontent.com/6461412/36854918-8cf3baf0-1d72-11e8-8a84-873c3ddf2107.gif)

**Comment by joaomoreno** [comment]
Seems OK now.
