### ISSUE TITLE
Allow "Go Back" to jump back to a diff editor if initiated from there

### ISSUE THREAD

**Issue by ggilmore** [Microsoft/vscode#39386]
- VSCode Version: Code - Insiders 1.19.0-insider (dc84f454ea245a1131e28557de1204b8cd1cc320, 2017-11-30T06:07:29.674Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
Go|luk|0.6.69
MagicPython|mag|1.0.12
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0

---
See this video: https://cl.ly/2O1R15403018

Steps to Reproduce:

1. Have a folder that is a git repo open 
2. Make changes to a file 
3. Open the diff view from the scm viewlet for that file 
4. Right-click >  jump to definition on a token in the diff view that is originally defined in another file
5. Use the back action (`^-`) - the back action doesn't take you back to the diff view

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
