### ISSUE TITLE
Azure Resource Manager Tools - Bad Linting

### ISSUE THREAD

**Issue by mxplusb** [Microsoft/vscode#39380]
```
VSCode Version:            1.18.1
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
```

Steps to Reproduce:

1. Install the Azure Resource Manager Tools plugin.
2. Use [this JSON](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/application-gateway/templates/azuredeploy.json), written by Microsoft.
3. Multiple linting errors around API versions and resource types not accepted. For example: `Microsoft.Network/virtualNetworks/subnets` -> `Value is not accepted. Valid values: "Microsoft.Web/sites/config".`

Reproduces without extensions: No

**Comment by mxplusb** [comment]
@mjbvz the link to report bugs for this extension [points here](https://visualstudio.uservoice.com/forums/293070-visual-studio-code), and it tells users to file bugs here. Please reopen this.

**Comment by mjbvz** [comment]
Azure resource manager tools is wrong here. We only use this repo to track core vs code issues.

I'll try reaching out to them about setting up a proper issue reporting channel

**Comment by mxplusb** [comment]
Thanks. Can you please update this issue with the proper reporting channel once you have it so I can file it in the right place?

**Comment by mjbvz** [comment]
Try here: https://github.com/Microsoft/vscode-azurearmtools/issues
