### ISSUE TITLE
Make debug configurations available per-language

### ISSUE THREAD

**Issue by Ketsuban** [Microsoft/vscode#39389]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299

It appears there are only two ways to provide debug configurations in Code:

* Globally, through the `launch` key in User Settings, which makes the configuration available to all projects regardless of language;
* Per-project, through the file `.vscode/launch.json` inside a project folder.

There's a missing ground between these two: per-*language*. I expected this to be possible by putting the `launch` key inside language-specific settings, but Code doesn't recognise the key in this context.

I have two debug configurations which are suitable for any Rust project using Cargo for dependency management and build automation; making these configurations available globally is nonsensical, but making them per-project requires manually recreating them for every project, often without any changes, leading to many duplicate `launch.json` files.

**Comment by weinand** [comment]
Launch configs are scoped to a project, not to a resource.
A resource has a language, but a project has not.
So scoping a launch config to a language does not have any meaning.

I see your argument with the duplicated launch.json files.
But the only way to address that would be to introduce a "project type" and have launch.jsons bound to a project type.

However, this is not is scope at the moment, but you might want to file a feature request for project types.
