### ISSUE TITLE
Undo is broken in file search field

### ISSUE THREAD

**Issue by zneak** [Microsoft/vscode#39384]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0

---

Steps to Reproduce:

1. Create new text document that spells out "SOME_EXAMPLE_VALUE"
1. Use ⇧⌘F to bring up the search bar
1. Type "hello"
1. Blur search field by focusing text document (the purpose of this step and the next one is to create some undo history)
1. Select search field again with mouse and use backspace to remove the last 2 characters.
1. Select "SOME_EXAMPLE_VALUE" in your text document
1. Use ⇧⌘F to select search field again. This updates the value of the search field to "SOME_EXAMPLE_VALUE"
1. Press ⌘Z to undo

Expected result: search field contains "hello" again. 
Actual result: search field now contains "SOMloE_EXAMPLE_VALUE"

Reproduces without extensions: Haven't checked, but almost certainly given how bare my installation is

**Comment by roblourens** [comment]
This is annoying but it's not really straightforward for us to fix.
