### ISSUE TITLE
Feature Request: When Terminal Focus CMD + t opens New Terminal 

### ISSUE THREAD

**Issue by reggi** [Microsoft/vscode#39397]
Right now to open a New Terminal the shortcut is CTL+SHIFT+~ can we base it on the focus? If the focus is the terminal CMD + t opens New Terminal?

**Comment by fabiospampinato** [comment]
You can do this today. I'd use `cmd+n` instead since the same shortcut is used for creating a new editor (tab), just put this in your keybindings file:

```json
  { "key": "cmd+n",                  "command": "workbench.action.terminal.new",
                                       "when": "terminalFocus" }
```
