### ISSUE TITLE
syntax error hightlighting disappeared after upgrading to Version 0.10.10

### ISSUE THREAD

**Issue by dingquan** [Microsoft/vscode#3939]
I just upgraded to the latest version (0.10.10)
and suddenly I don't have javascript syntax error highlighting any more. for example, if I type a variable name without defining it first, I use to see the variable name being underscored in red, it's not showing that after the upgrade.
How do I get it back?

**Comment by holyman2k** [comment]
I had the same issue. I fixed it by complete remove the app and reinstall it again, btw I'm using Mac or I need a third party app to completely remove all files

**Comment by dingquan** [comment]
@holyman2k how did you completely remove the app? I use mac as well. I deleted the app from the Application folder and reinstalled the program and the issue remains. :(

**Comment by aeschli** [comment]
Highlighting is #3903. Workaround is to switch to the Light+/Dark+ theme.

**Comment by egamma** [comment]
We have deprecated the built-in linting in favor of existing linters. Pls see the release notes https://code.visualstudio.com/Updates#_languages-javascript the section migration, eslint.
