### ISSUE TITLE
Git revert window jumps to first change and can't select original lines 

### ISSUE THREAD

**Issue by localhosted** [Microsoft/vscode#39393]
I'm not sure if these are expected behavior, but there are two points that make the git revert window a bit of a pain to use:

1. Whenever a change is reverted, the window jumps to the first change in the file. This completely changes focus, especially since odds are I just want to revert code near where I am at.
2. When the git revert window is open, I can't select the original lines. This is a bit of a pain since I usually just want to use the revert window to check on the original code, or want to copy a segment without having to: a) copy the changes, b) revert changes and c) modify the code and paste the changes.

- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce (revert window jumps to beginning):

1. Open git revert window trough shortcut on the left on changed lines
2. Revert changes
3. Revert window jumps to first change in file

Steps to Reproduce (can't select original lines):

1. Open git revert window trough shortcut on the left on changed lines
2. Try to select original lines
3. Only the changed lines can be selected

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Please file one bug per issue.

Also, both of these already exist a duplicates.
