### ISSUE TITLE
Feature Request: Only have Terminal Up / Dock Icon Just for terminal

### ISSUE THREAD

**Issue by reggi** [Microsoft/vscode#39396]
Just a thought I sometimes want to use the vs code integrated terminal without code up. It would be nice if the terminal had the option to consume the whole page, not have a sliver of the welcome page or untitled document and it would be cool to have a mac-app in the dock that is the vs code terminal.

**Comment by fabiospampinato** [comment]
You might want to take a look at [Hyper](https://hyper.is/), it's a terminal implemented using web technologies. I think they'll switch to [xterm](https://github.com/xtermjs/xterm.js) at some point in the future, when they do it will basically become what you're asking for.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34442, be sure to 👍 it 😃
