### ISSUE TITLE
VScode is no longer responding

### ISSUE THREAD

**Issue by Illyrix** [Microsoft/vscode#394]
![1](https://cloud.githubusercontent.com/assets/12008675/11316709/0eda6498-904d-11e5-9cc9-c35d3d80a669.png)
this situation is occurring while coding "xxx".
![2](https://cloud.githubusercontent.com/assets/12008675/11316710/10585f64-904d-11e5-973d-66b661a72330.png)

**Comment by bpasero** [comment]
Likely #160 .
