### ISSUE TITLE
Regression:  Search no longer auto fills search term (via mouse click)

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#39400]
- VSCode Version:  1.18.1
- OS Version:  Windows 10

Steps to Reproduce:

1.  Highlight some text in the editor
2.  Select the file search panel by clicking on the magnifying glass

Reproduces without extensions: Yes

In versions prior to 1.18 highlighting text and clicking on the file search bar/pane would auto fill the search term with the highlighted text.

Note:  pressing ctrl+shift+f works as expected.

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/38854
