### ISSUE TITLE
I opened some big number of files (), tried to search in them with Ctrl-Shift-F, but I got a message: spawn ENAMETOOLONG. 

### ISSUE THREAD

**Issue by retepaskab** [microsoft/vscode#39406]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|0.18.0
vscode-color|ans|0.4.5
close-all|ben|1.0.2
vscode-npm|fkn|3.3.0
gdl-22|pba|1.22.4
guid|kos|0.0.1
vs-color-picker|lih|0.7.0
color-highlight|nau|2.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. open lots of files - don't know how much, vscode doesn't tell it, about 100-200
2. try to search in files
3. -> spawn ENAMETOOLONG
4. close some of them
5. search OK 

![image](https://user-images.githubusercontent.com/5570057/33473653-939a7192-d677-11e7-8411-cc2d4dd52777.png)

Reproduces without extensions: Yes

**Comment by mkavidas** [comment]
Could not reproduce this on:
OS: Debian x64
VS Code version: 1.20.1

Tried with 100,200 and 500 files open.

**Comment by roblourens** [comment]
This is probably with individual files opened, not with files in an opened folder @mkavidas if that's what you tried

**Comment by mkavidas** [comment]
I tried it with both. First opened a folder with > 500 files then kept opening files while trying to reproduce the bug. Was never able to. I have seen that some other students in my class have also not been able to reproduce this.

**Comment by retepaskab** [comment]
It's possible that this has been fixed, I opened large number of files recently and didn't see the message.

**Comment by mkavidas** [comment]
@retepaskab  Did you open the files one at a time or did you open a folder with 448 files?

**Comment by sleutho** [comment]
This happens when I open a WSL workspace on windows:
The workspace path is something like this:
C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\<username>\foo\bar

Search is always broken in there. Either because the pathnames are all too long, or because those are LF files.

**Comment by roblourens** [comment]
This should not happen anymore, however that's because now only the editor searches spare open files. It may miss some if the model is unloaded from the editor, there is another issue for this.
