### ISSUE TITLE
Import/export settings

### ISSUE THREAD

**Issue by garethnic** [Microsoft/vscode#39407]
I don't know if this is already possible, but it might be a cool feature to be able to export/import settings.

Being able to export the settings, keyboard shortcuts and a list of installed plugins/themes to a json file. Importing this file could possibly trigger installing the plugins. 

Would be awesome to save the setup I currently have in a gist for backup purposes.

**Comment by benedekAdam** [comment]
While it's not a native solution, but there's an extension for it:
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
It lets you sync you extensions and settings between multiple computers.

**Comment by garethnic** [comment]
@benedekAdam That's actually pretty cool. Thanks.
