### ISSUE TITLE
Javascript colorization defining multiple var

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#3940]
When defining multiple var in JavaScript the colorization is not working properly after the first defined variable if they are on separate lines. 

![varcolor](https://cloud.githubusercontent.com/assets/12900364/13656001/3a3e5a38-e618-11e5-8e29-f01b87bf83cc.JPG)
`var wm1 = new WeakMap(),
	wm2 = new WeakMap(),
    wm3 = new WeakMap();`

On the same line they are correctly colorized 
![varcolorworking](https://cloud.githubusercontent.com/assets/12900364/13656046/80e0f5f4-e618-11e5-82a2-f729c81ce286.JPG)

Expected: wm2 and wm3 should be the same color as wm1 regardless of the line they are on.

Version 0.10.12-alpha
Commit e8d5a7932b99f6b7559d48536bfc84732bfc8582
Date 2016-03-09T09:53:18.387Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#121
