### ISSUE TITLE
Memory leak and massive CPU usage

### ISSUE THREAD

**Issue by efficientportal** [Microsoft/vscode#39411]
OS - Linux Mint 18.3
Ram: 32Gb
HD space: 1.5Gb free

Issue: Simply launching VSCode  causes my CPU to run one of it's cores at 100% pretty much non-stop even if I am not doing anything with the program. In addition, While watching the system monitor, I noticed that, even though I am not doing anything with the program, it is using more and more memory over time. 

The process that is doing this is actually three processes that launch called, "code". There are a total of 8 processes launching called, "code" and staying in memory.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: none
---

Steps to Reproduce:

1. Launch the program
2. Launch the System monitor

**Comment by efficientportal** [comment]
Update: I tried uninstalling and reinstalling the program. While this appears to have dealt with the overabundant CPU usage, the memory leak is still there.

**Comment by kieferrm** [comment]
@efficientportal can you pls have a look at https://github.com/Microsoft/vscode/wiki/Performance-Issues and provide us with additional information? Thanks a ton!

**Comment by efficientportal** [comment]
I am not sure what info you need from Htop so I just took a couple 
screen shots.

Again:

No extensions installed.
No projects loaded.
Fresh install of VSCode.

You have a big memory leak and one of the Code files is pounding the 
crap out of my cpu.

Thanks,

Ron

**Comment by efficientportal** [comment]
I think I forgot to attach the files last time. Here you go.

**Comment by kieferrm** [comment]
@efficientportal I don't see any file attachments. Thanks!
