### ISSUE TITLE
Shared process should start only when needed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39412]
With https://github.com/Microsoft/vscode/commit/b71255501de5b4c8a890abf7f6579ac1394c5d8e we are (quite artificially) delaying the creation of the shared process window by 5 seconds. However, typically the renderer will trigger the creation of the Window earlier than that from [`shell#initServiceCollection()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L279).

So we are still paying the price of a window opening at the same time when the workbench is busy restoring the editor. 

Can we just push out the shared process to the point where the workbench signals it is ready (after viewlet and editor restore)?

**Comment by alexandrudima** [comment]
@bpasero What is the correct code change to delay the creation of the shared process ?

I pushed that change with blessings from @joaomoreno ...

**Comment by joaomoreno** [comment]
@bpasero What is the event to listen to?

**Comment by bpasero** [comment]
@alexandrudima @joaomoreno wouldn't it be safe to assume that the shared process is only triggered from a window and not from the main side? If so, we could maybe remove the creation altogether from the main side and on the renderer side use `lifecycleService.when(LifecyclePhase.Running)`? This will wait until editors and views have restored.

**Comment by joaomoreno** [comment]
The shared process is used in two places from the main side:

- [telemetry](https://github.com/Microsoft/vscode/blob/spdlog/src/vs/code/electron-main/app.ts#L309)
- [windows service](https://github.com/Microsoft/vscode/blob/spdlog/src/vs/code/electron-main/app.ts#L357), though this one is used the other way around... the shared process listens to events from the main side

So I don't think it's a good idea to have a window creating the shared process.

The main side should be able to listen on every window's lifecycle events. The infrastructure is all there, can you expose those events to the main side, @bpasero?

**Comment by bpasero** [comment]
@joaomoreno each window has a [`ready()`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L323) method that resolves when the workbench has restored. It should be possible to connect the shared process to the window that opens.

**Comment by joaomoreno** [comment]
@alexandrudima Should we keep the 5s now or attempt to fix this today?

**Comment by bpasero** [comment]
I would vote for changing this in December and not on the last day of the endgame...

**Comment by alexandrudima** [comment]
I agree we should move this to December.

**Comment by joaomoreno** [comment]
Keeping the 5s delay that is?

**Comment by alexandrudima** [comment]
The change has been reverted. The shared process is not delayed anymore. See #40505
