### ISSUE TITLE
Add support for amending and reusing the message

### ISSUE THREAD

**Issue by fxn** [Microsoft/vscode#39415]
Would be handy to add support for something like

```
git commit --amend --no-edit
```

which I use a lot.

This could be in the form of a dedicated menu item, but also could be as simple as pre-filling the textfield for the message when amending, so that hitting Enter will reuse it.

**Comment by joaomoreno** [comment]
Do you simply want to change the last commit message, then?

**Comment by fxn** [comment]
Hey @joaomoreno! Not really, what you do with that command is to amend to last commit without changing the message.

So, you are working on a patch and perform a tentative commit, but you later refine the patch itself, the message is good.

**Comment by joaomoreno** [comment]
Have you tried running the `Git: Undo Last Commit` action? It will show all your changes as staged and restore the commit message in the box. Seems to do exactly what you want.

**Comment by fxn** [comment]
Not sure it is the same. I want to stage something new, and amend.

I mean, it is amending (for which VScode has support), with the special case that you do not want to edit the commit message. That is a need that justifies the existence of `git commit --amend --no-edit`.

Could it be the case that you believe `amend` is only for amending the message?

**Comment by joaomoreno** [comment]
![kapture 2017-12-04 at 11 38 43](https://user-images.githubusercontent.com/22350/33548537-bf0b069e-d8e7-11e7-8a8f-ae9abcbadf60.gif)

**Comment by fxn** [comment]
That is a different workflow. When amending the workflow is:

1) Stage the new changes (which possibly modify changes made in the last commit).
2) Amend.

If I stage the new changes and undo last commit, then the staged changes go back to the changes section and need to re-stage.

If "undo last commit" was equivalent, then VScode would not need to have support for amending. This ticket is about implementing one special case of amending. It is amending, only the workflow is faster because there is commit message to ask for, you just amend the last commit reusing the message.

Undoing an initial commit gives a fatal error, by the way, but that would a minor remark. The main argument to ask for this feature is above.

Of course, implementing this is your call, I respect that. But would need to use the console, undo last commit is not the same.

**Comment by joaomoreno** [comment]
Actually, what you want is already implemented in Insiders. Did you give that a try?

**Comment by fxn** [comment]
Ah! Just downloaded Insiders and you're right, the message field when amending is pre-filled. That's enough. Thank you!
