### ISSUE TITLE
intellisense  lack

### ISSUE THREAD

**Issue by ilovesusu** [Microsoft/vscode#39414]
- VSCode Version:1.18.1
- OS Version:debian testing

Steps to Reproduce:
Just open simple script.js file,
get your input by it's id
and then try to get value of this input.

1.var str1 = document.getElementById('str1');
2.str.v
In the tip, it only have str1.nodeValue，has no str1. value

**Comment by kieferrm** [comment]
@ilovesusu Based on your example: In ES6  `getElementById` returns an `HTMLElement` that does not have a `value` attribute.  If you know that you have a `HTMLTextAreaElement` or `HTMLInputElement` in your hands you could assign provide a type hint using JSDoc.
