### ISSUE TITLE
add an indicator to the file name about errors

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#39418]
display an indicator (red dot?) next to the name of a file with errors in

- explorer view

![image](https://user-images.githubusercontent.com/937933/33483593-8ce1b884-d66c-11e7-9f59-6eb0a504c09b.png)

- source control view

![image](https://user-images.githubusercontent.com/937933/33483555-5cd77890-d66c-11e7-9a3d-38f2417b25fb.png)

**Comment by jrieken** [comment]
duplicate of #782
