### ISSUE TITLE
Exiting git log with ctrl+c

### ISSUE THREAD

**Issue by hochas** [Microsoft/vscode#39419]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.23
prettier-vscode|esb|0.24.0
beautify|Hoo|1.1.1
angular-essentials|joh|0.3.2
Angular2|joh|2.11.2
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.5.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.0.0
typescript-hero|rbb|1.7.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Right click project in workspace -> Open in Terminal 
2. Write something, press enter. Entered command should be visible.
3. Write `git log`
4. Exit with `ctrl+c` (`ctrl+z` works)
5. Write something. Entered text is no longer visible

Reproduces without extensions: Yes

**Comment by hochas** [comment]
I just noticed the exact same behavior in JBoss Developer Studio 10 when I use the integrated terminal there.

**Comment by Tyriar** [comment]
I'm consolidating all ctrl+c related issues under https://github.com/Tyriar/node-pty/issues/7
