### ISSUE TITLE
Show tab shrinking overflow differently (no "...", shadow?)

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#39417]
- VSCode Version: 1.19.0-insider (5b0fa2e Date 2017-12-01T06:14:38.596Z )
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

As he talked to @bpasero , he asked to be tracked in a new case. From #15048

[Comment @Tekbr #15048 ](https://github.com/Microsoft/vscode/issues/15048#issuecomment-347947030)

> @bpasero An idea ... Instead of using the '...', why not use the style of Microsoft Edge, Mozilla Firefox and Google Chrome? 😉 The text is below the "X" (erased slightly) as the guide decreases.
> 
> ![tab](https://user-images.githubusercontent.com/19866231/33483130-757386f2-d683-11e7-816c-4e5867c9e907.PNG)
> 
> Particularly, I prefer the style of Firefox.

[Comment @bpasero  #15048](https://github.com/Microsoft/vscode/issues/15048#issuecomment-348098172)

> @Tekbr good suggestions. I am not a big fan of how Edge is simply clipping the text at the end of the tab. I really like what Firefox/Chrome are doing with the fading out in the end, if anyone wants to chime in with a reasonable PR (not too crazy, just CSS), feel free.
> 
> What I can change though is to not leave the room for the close button. I realized that when shrinking is enabled, the close button should only show up on hover, but otherwise not consume any space:
> 
> ![33417693-cc896aec-d5a2-11e7-93aa-f6f2b9a33923](https://user-images.githubusercontent.com/19866231/33483212-df57b804-d683-11e7-9da1-db4a73984605.gif)

[Comment @Tekbr #15048](https://github.com/Microsoft/vscode/issues/15048#issuecomment-348166221)

> @bpasero Thanks for the feedback!!
> 
> I was happy with your move !! 😄 👏 👏
> 
> By your comment it seems like something simple to do (or not) 🤔 , but after going through the team tests .. or even before (if you think better) maybe crawl for a new case suggesting for beginners, no? Referring to this case and the test case, with my comment and your comment (if you think you should). That way, someone can locate it more easily! 🤔
> 
> Anyway, thanks again for the feedback! 👍

[Comment @bpasero  #15048](https://github.com/Microsoft/vscode/issues/15048#issuecomment-348212991)

> Sure, feel free to create a new issue for it and we can ask for help.

@bpasero If necessary, update the case. Make the necessary modifications / simplifications. (do it please.)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Would be willing to look into a reasonable PR for this that is not too crazy. E.g. ideally CSS only change.

**Comment by bpasero** [comment]
Thanks to @Dari-K, tabs now fade out when set to shrink:

![image](https://user-images.githubusercontent.com/900690/35801800-f8c5770e-0a6d-11e8-8266-f026c5b2f01c.png)

**Comment by Tekbr** [comment]
@bpasero  and @Dari-K I really liked it very much .... ❤️ ❤️ ❤️ 

I delayed responding until I got the Insiders version 1.21.0

Just one question ... do you think this overlap might be a little longer? Put a little more word for word?

Ex: By the image above, in the second tab (image), half of the letter 'g' would also have the shading.
Just to have an idea .. if you could increase.

This would extend to when we hover over and the 'X' appears to close.

Anyway the work was great ... it was good, much better than '...'  😍  Congratulations on the beautiful work. 👏 👏 👏 

Thank you!!

**Comment by bpasero** [comment]
Yeah I also thought that the shadow is very subtle, I wouldn't mind expanding it a bit.

**Comment by bpasero** [comment]
@Dari-K your call, I think `10px` is fine.

**Comment by Tekbr** [comment]
@bpasero From `5px` to `10px` there is almost no difference .. at least `15px`. What do you think?

**Comment by bpasero** [comment]
**Verification:** 
Configure `"workbench.editor.tabSizing": "shrink"` and open enough tabs so that they shrink. See a shadow instead of a ellipsis at the end of the tab label. The shadow works fine in light and dark themes.
