### ISSUE TITLE
Explorer: Dynamically created or deleted files not appearing

### ISSUE THREAD

**Issue by eleonorsomosot** [Microsoft/vscode#39410]
Dynamically created or deleted file does not automatically appear on the explorer tab whether it be via code or manually created/deleted in OS's file explorer app.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
beautify|Hoo|1.1.1
material-icon-theme|PKi|3.1.0
html-css-class-completion|Zig|1.14.0
alignment|ann|0.3.0
vscode-intelephense-client|bme|0.8.2
vscode-eslint|dba|1.4.3
phpunit|ema|2.1.1
vscode-great-icons|emm|2.1.20
php-debug|fel|1.12.1
auto-close-tag|for|0.5.4
terminal|for|0.0.10
composer|ika|0.7.1
Untabify|ili|0.0.2
theme-monokai-pro-vscode|mon|1.1.2
sublime-keybindings|ms-|3.0.3
php-docblocker|nei|1.3.2
snippet-creator|nik|0.0.4
advanced-new-file|pat|0.5.1
CSSLint|ray|0.0.3
vscode-icons|rob|7.18.1
vscode-fileutils|sle|2.7.1
php-ci|sma|0.2.8

(4 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
@eleonorsomosot can you reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, do new files get seen if created from witih vscode?

**Comment by eleonorsomosot** [comment]
hi @isidorn will try to install that one and will get back to you later. don't have my laptop with me now.

**Comment by eleonorsomosot** [comment]
file explorer is working on insiders. I tested stable version again with code that runs on local machine and its working. I think it was because of the delay of the remote server. that issue occurred when I was working with remote server files. thanks for the help @isidorn.
