### ISSUE TITLE
VS Code constantly trying to phone home without obvious notification of attempt or failure

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#39420]
VS Code 1.18.1
OS Windows

open Code to show the Welcome screen
toggle developer tools ('Help > Toggle Developer Tools')
there are 128 warnings called out

![image](https://user-images.githubusercontent.com/33490168/33487291-b68486ea-d67a-11e7-9298-221393ad4f36.png)

Here's a chunk of the 128 warnings

![image](https://user-images.githubusercontent.com/33490168/33487326-d0012560-d67a-11e7-8568-e024f218f634.png)

and with more detail

![image](https://user-images.githubusercontent.com/33490168/33487337-df0c8bee-d67a-11e7-9ec4-aede93b1f6e3.png)

It appears that someone is attempting to phone home.

![image](https://user-images.githubusercontent.com/33490168/33487355-eb9de696-d67a-11e7-98c1-19e5cdc8977f.png)

**Comment by kieferrm** [comment]
You can disable telemetry with the following settings:
```json
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false
```
