### ISSUE TITLE
Snippets are squiggled

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39421]
I see this in `scripts/code.sh`, not in todays insiders 

<img width="459" alt="screen shot 2017-12-01 at 15 43 37" src="https://user-images.githubusercontent.com/1794099/33487713-703c3a32-d6ae-11e7-8b0b-7964cae04c39.png">

**Comment by aeschli** [comment]
I can't see it neither when starting from the dev workspave nor the insiders. Tried on Linux and Mac.
To debug, open the "JSON language server' output channel, look for the chromdev link and open it.
Set a break point `jsonSchemaService.js`, line 412 (iterating over `filePatternAssociations`) and open the snippet file.

**Comment by jrieken** [comment]
went away after a 'yarn install'
