### ISSUE TITLE
every upgrade destroys my settings

### ISSUE THREAD

**Issue by jimwill3** [Microsoft/vscode#39426]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.14.2
MagicPython|mag|1.0.12
vscode-azurefunctions|ms-|0.2.0
python|ms-|0.8.0
vscode-ai|ms-|0.1.4
azure-account|ms-|0.2.2
csharp|ms-|1.13.1
azure-hdinsight|msh|0.0.9
vscode-docker|Pet|0.0.22
python|tht|0.2.3
usql-vscode-ext|usq|0.2.7

---

Steps to Reproduce:

1.add configuration setting for CNTK to settings.json and launch.json for a python project. work cleanly
2.do any upgrade to VS code  lose all settings that worked for CNTK and have to redefine it each and every time. it is driving me insane

Reproduces without extensions: Yes/No

**Comment by sandy081** [comment]
@jimwill3 Couple of questions

- What are CNTK settings?
- Do you loose all settings or just settings from an extension?
