### ISSUE TITLE
failures of the telemetry system should be alerted to the user

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#39428]
Presently, if a fault occurs in the telemetry system, this results in a warning which is invisible unless you have the developer tools enabled (Help > Toggle Developer Tools).

Failures of this system should be reported to the user with guidance as to the setting responsible.

- telemetry.enableCrashReporter
- telemetry.enableTelemetry

**Comment by ramya-rao-a** [comment]
Can you provide reproducible steps to generate such a warning?

**Comment by draeger-charles-wilson** [comment]
Do a standard install, block internet access. Like most corporations we use a fairly restrictive firewall.

**Comment by ramya-rao-a** [comment]
I only see this

<img width="807" alt="screen shot 2017-12-08 at 10 36 58 am" src="https://user-images.githubusercontent.com/16890566/33779948-cf33e77e-dc03-11e7-936c-4175bd95d3a5.png">


Do you see anything else?
