### ISSUE TITLE
telemetry settings should be defaulted to false

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#39427]
The telemetry settings:

- telemetry.enableCrashReporter
- telemetry.enableTelemetry

should be defaulted to 'false' (opt-in).

**Comment by ramya-rao-a** [comment]
@draeger-charles-wilson Please see https://github.com/Microsoft/vscode/issues/17790#issuecomment-270695861 for a detailed answer on a similar feature request.
