### ISSUE TITLE
Code + Microsoft Teams Save All Files Conflict

### ISSUE THREAD

**Issue by spietrek** [Microsoft/vscode#39424]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
jsx|Twe|0.0.1
html-css-class-completion|Zig|1.14.0
Bookmarks|ale|0.18.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|0.26.0
auto-close-tag|for|0.5.4
auto-rename-tag|for|0.0.15
vscode-sort|hen|0.2.5
vscode-styled-components|jpo|0.0.10
vscode-codemetrics|kis|1.11.1
node-debug2|ms-|1.19.0
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
convert-css-in-js|pau|1.0.0
parker-code-extension|ray|0.0.2
vscode-icons|rob|7.18.1
stylelint|shi|0.31.0
rewrap|stk|1.5.3
vscode-react-native|vsm|0.5.7
vscode-import-cost|wix|2.5.1
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.5.0
ReactSnippets|xab|1.7.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open Microsoft Teams (1.0.00.30651)
2. Open Code (1.18.1)
3. Open a project in Code.
4. Make changes to multiple files.
5. Try to save multiple files using shortcut (Cmd-Alt-S). Nothing happens.
6. Close Teams and try step #5 again. It works.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
I believe the issue lies with Microsoft Teams where they register this keybinding globally. Perhaps they have a setting somewhere to remove that keybinding.

I believe you can reach out to the Microsoft Teams folks at https://techcommunity.microsoft.com/t5/Microsoft-Teams/bd-p/MicrosoftTeams

**Comment by Borntofly** [comment]
@spietrek did you find workaround? have the same problem

**Comment by spietrek** [comment]
@Borntofly a new version of Microsoft Teams released this week resolved the issue for me.

You have Microsoft Teams Version 1.0.00.34151. It was last updated on 12/18/17.
