### ISSUE TITLE
There is no vscode.executeResolveCompletionItem complex command

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#39438]
I'm forwarding requests using `executeCommand`. There is a `vscode.executeCompletionItemProvider` but I don't see a matching command for resolving the item in the docs or https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostApiCommands.ts

**Comment by jrieken** [comment]
There is now an optional argument for the number of completions to be resolved when calling `executeCompletionItemProvider`.
