### ISSUE TITLE
Display/Font issues on Ubuntu xfce4 desktop

### ISSUE THREAD

**Issue by Gman47** [Microsoft/vscode#39433]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.14.3

---

Steps to Reproduce:

1. install editor
2. see weird dots between letters, and sometimes between lines. If you look at the attached screenshot you should be able to see what i'm talking about. I've tried about 10 different fonts in different sizes, each one has similar issues, although the problem spots tend to move around a bit with different fonts.

Reproduces without extensions: Yes/No

**Comment by Gman47** [comment]
I fixed it. I had to chanage my Sub-pixel order from RGB to None.

**Comment by isidorn** [comment]
@Gman47 great
