### ISSUE TITLE
Build Task Fails with No Explanation

### ISSUE THREAD

**Issue by Sh0es** [Microsoft/vscode#39434]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Build 15063

Steps to Reproduce:

1. Open VSCode
2. Run C:/MinGW/bin/g++.exe -g sauce/ArrayList.h sauce/ArrayTest.cpp -std=c++0x

Result: The terminal process terminated with exit code: 1. No error message is given.

**Comment by Tyriar** [comment]
@Sh0es can you check the devtools console for errors?
