### ISSUE TITLE
Monokai theme: parameters are not colored in Orange

### ISSUE THREAD

**Issue by infctr** [Microsoft/vscode#39439]
So I'm about to bring this issue up https://github.com/Microsoft/vscode/issues/1504, coz it doesn't seem it was resolved. I'm a big fan of Monokai theme, but this keeps bugging me. 

These lines of code don't seem to work for some reason 
```
		{
			"name": "Function argument",
			"scope": "variable.parameter",
			"settings": {
				"fontStyle": "italic",
				"foreground": "#FD971F"
			}
		},
```
taken from https://github.com/Microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json

So I have 
![image](https://user-images.githubusercontent.com/15550153/33505980-c19dfffa-d6fe-11e7-8cdc-9749ec1fe351.png)

Expected
![image](https://user-images.githubusercontent.com/15550153/33505992-c8aa1cde-d6fe-11e7-869f-ba7da6dde64a.png)

Does it have anything to do with VS Code issuing tokens? 
Many other monokai themes turn out to be broken too

- VSCode Version: 
```
code --version
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```
- OS Version:
macOS High Sierra

**Comment by aeschli** [comment]
That's what I see with the built-in TypeScript/JavaScript grammar and Monokai theme:
![image](https://user-images.githubusercontent.com/6461412/33554990-15bb0cd4-d8ff-11e7-92a5-e86c1f24815a.png)
```typescript
var f = (state = {}, {a,b,c}) => {
	
}
```

**Comment by aeschli** [comment]
To find out which scope is created where and what rule is matched to it, use the `Developer: Inspect TM Scopes` command:
![image](https://user-images.githubusercontent.com/6461412/33555889-4ee2aa8c-d902-11e7-87c9-fe567e0674df.png)

**Comment by infctr** [comment]
@aeschli thanks for the debug tip!  
I had to turn off the extension https://github.com/dzannotti/vscode-babel/ to get proper tokens for the theme

**Comment by infctr** [comment]
However syntax highlighting breaks when function arguments are placed on individual lines 

![image](https://user-images.githubusercontent.com/15550153/33575488-e2bf6b14-d94d-11e7-8059-14dceaf47b2a.png)

And it looks like there's no way to address this lonely argument

![image](https://user-images.githubusercontent.com/15550153/33575504-eda57988-d94d-11e7-9768-c752727241ae.png)

Object rest arguments can be addressed as `meta.var.expr.js meta.object.member.js variable.other.readwrite.js` tho

**Comment by aeschli** [comment]
That has to do with the way the textmate grammar engine works. It only sees one line at a time, and once processed can not make adjustments later (e.g. when on the next line). So I speculate that until one sees the `=>` you don't know its a function declaration.
The textmate grammar for TypeScript/JavaScript is at https://github.com/Microsoft/TypeScript-tmlanguage. You can make improvements suggestions there, but think of the Textmate limitations.
