### ISSUE TITLE
[WebSite] The default download option for VS Code on Linux machine is displaying for OS X.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#3943]
OS: Linux Raspbian 
![p_20160308_110556](https://cloud.githubusercontent.com/assets/17735796/13656543/9ad28618-e61c-11e5-9b3b-604c34c58f80.jpg)

Download URL: https://code.visualstudio.com/ 
 
Steps:
1. Try to install VS code from https://code.visualstudio.com.
2. Verify the default download option (displaying with download button).

Actual: The default option is showing up for OS x.
Expected: It should find the OS type and display default option accordingly. In this case "Download for Linux".

**Comment by jasonyueyang** [comment]
CC @Tyriar

**Comment by gregvanl** [comment]
No repro on Ubuntu 14.4

**Comment by gregvanl** [comment]
On Ubuntu 14.4, the button shows "Download for Linux x64" with link to "32bit version" below.

**Comment by Tyriar** [comment]
[Midori](http://midori-browser.org/), "a browser for linux and windows" identifies [itself as a macintosh running OSX](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=71898)... Oh how [I hate the state of user agents](http://www.growingwiththeweb.com/2014/04/get-your-nose-out-of-my-user-agent.html).

```
User-Agent = Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-us) AppleWebKit/535+ (KHTML, like Gecko) Version/5.0 Safari/535.22+ Midori/0.4
```

@gregvanl you can catch this by checking the UA for `Midori/\d+\.\d+`, though you will need to verify what the UA looks like when installed on Windows and Linux. Also I believe [you need to rebuild from source](www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx) as we don't build vscode for arm.

**Comment by gregvanl** [comment]
I just tried Midori on Windows and the download button looks correct (Download for Windows). Closing. If this is still an issue with the latest version of code.visualstudio.com, please enter an issue at https://github.com/Microsoft/vscode-website/issues
