### ISSUE TITLE
[VSCodeEndGameTesting-Aditi][Command-Palette] Getting error when trying to run command for dnx.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#3944]
OS: Windows 10
VS Code Version: 0.10.12-alpha
Node: 4.1.1
Steps:
1. Launch VS code.
2. Launch command palette by pressing CTRL+P and inter ">dnx" and selection option for Run command.
3. Verify editor response.
Actual: Getting error "omniSharp" server is not running.
Expected: It should run the command and ask for re-start.
![omnisharperrorwhilerunningdnx-cmd](https://cloud.githubusercontent.com/assets/17735796/13656787/de360a68-e61e-11e5-82b8-7bec1a817665.jpg)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#84
