### ISSUE TITLE
TypeScript `renameLocation` offset isn't respected

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#39445]
```ts
function foo(x, y, z) {
    x = y = z;
}
```

1. Extract function to global scope on the second line

   ![image](https://user-images.githubusercontent.com/972891/33509619-f9b5a538-d6b7-11e7-8d95-85bdb11b021b.png)

2. Cursor is placed on line 2 col 39 instead of line 2 col 17

   ![image](https://user-images.githubusercontent.com/972891/33509653-408c2cd4-d6b8-11e7-92fc-cf41c240f41a.png)

**Comment by mjbvz** [comment]
Here's what I see:

![dec-04-2017 11-04-15](https://user-images.githubusercontent.com/12821956/33570804-e5ae6372-d8e2-11e7-981e-2c6a37cb55e1.gif)


What VS Code version, TS version, and OS are you on?

**Comment by DanielRosenwasser** [comment]
VS Code 1.18.1 on Windows
TypeScript 2.6.1

**Comment by mjbvz** [comment]
Thanks. Only seems to happen on windows for me. Line endings don't seem to make a difference

**Comment by mjbvz** [comment]
I bet it's a path casing issue. Before triggering the rename, we do a quick check to make sure the active editor is the same one that triggered the refactor. This just compares the two paths
