### ISSUE TITLE
tasks: Problem Matcher - pattern : to support appending regex match groups

### ISSUE THREAD

**Issue by revanth98** [Microsoft/vscode#39446]
- VSCode Version: 1.18.1
- OS Version: ubuntu

I have a compile error where the directory is displayed in one line and filename is displayed in another line.
Can you please add a way to concatenate the regex match groups to form the file name.

example:
make[1]: Leaving directory `/home/user/directory/src/project1/src'
../src/test.cc:488:59: error: ‘dfsdfsd’ was not declared in this scope

"pattern": {
                    "regexp": "^(.*)`(.*)'\n(.*):(\\d+):(\\d+):\\s+(error):\\s+(.*)$",
                    "file": 2, // want to display as 2+3 = "/home/user/directory/src/project1/src/../src/test.cc"
                    "line": 4,
                    "column": 5,
                    "severity": 6,
                    "message": 7
                }

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/11663
