### ISSUE TITLE
Process launched by Task unexpectedly closes on Ubuntu

### ISSUE THREAD

**Issue by seanpoulter** [Microsoft/vscode#39447]
Do you have a question? **Already asked [here](https://stackoverflow.com/questions/47582132)**

- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04.3 x64

Steps to Reproduce:
1. Clone this repo that's one Task and an HTML file:
    ```
    git clone https://github.com/seanpoulter/vscode-39447
    ```
2. Open the repo folder in Code
3. Run the *"Open with default browser"* Task
4. If the default browser is not open, it will not open. If the browser is open, the page will not open.

**Bonus points**: Add a chained delay to the command, like ` && sleep 10`. The browser will open until the sleep returns, then it will exit.

Reproduces without extensions: N/A -- will extensions modify Task behavior?

**Comment by dbaeumer** [comment]
@seanpoulter if you run the command directly in the integrated terminal what happens there?

**Comment by seanpoulter** [comment]
Running in the integrated terminal behaves as expected.

**Comment by alexr00** [comment]
This is by design. When a task finishes, the process is torn down which means the launched browser will be killed. You could throw a longer sleep in to keep the file open, or write a command instead. You could also accomplish this by using a `process` task instead of a shell task.

**Comment by seanpoulter** [comment]
Thanks for following up @alexr00. If I remember correctly (but didn't put it in the ticket), this behaved differently on my Windows box.

You've suggested writing a command instead. Do you mean starting a command when the task finishes? There's mention of `postAction` as a hook to use in #7090 but the issue is still open and there are no public docs on https://code.visualstudio.com/docs/editor/tasks.

**Comment by alexr00** [comment]
I haven't been able to find a ton of info about it, but you're using `explorer` to do the launch on Windows. I'm guessing `explorer` doesn't tie the new process to the one started by VS Code so we don't know how to clean it up.  I did some digging on `xdg-open`, and I can see that the browser process has a pointer back to the VS Code process. 
![image](https://user-images.githubusercontent.com/38270282/50700609-45bb3880-104b-11e9-9d35-6f4cc14a4798.png)
