### ISSUE TITLE
Go to File not showing files that show up fine in Explorer

### ISSUE THREAD

**Issue by tpejsa** [Microsoft/vscode#39440]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:57:00.652Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3
trailing-spaces|sha|0.2.11

---

I'm working with a huge codebase (100,000+ files in the visible tree, plus another 1,000,000+ in excluded directories).

I noticed that some files don't show up in Go to File. These files are not excluded and they show up fine in Explorer. They can also be opened just fine in the editor. In fact, after you open them, they start showing up in Go to File!

Steps to Reproduce:

1. Open a huge codebase.
2. Ctrl + P
3. Type in name of some file in the tree. Repeat until you find one that should show up, but doesn't.
4. Find the file in Explorer.
5. Open the file.
6. Ctrl + P
7. Type in the name of the file. It should show up now.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Hm, I can't repro in the Chromium codebase which is my test for huge workspaces. We have a result count limit, but that applies to actual results, not the workspace in general.

Is it possible that it's excluded by a `search.exclude` setting? Is there a consistent set of files that are missing, or just random ones sometimes?

**Comment by tpejsa** [comment]
This definitely happens for files that are not in search.exclude or file.exclude. Interestingly, if I delete .browse.VC.db, all the files start showing up again, but after a while some of them stop showing up again. It's like the index gets partially corrupted after a while.

I can't say for sure whether this happens for random files or always the same set of files. Seems more like the former.

**Comment by roblourens** [comment]
`.browse.VC.db` is from the cpp extension, shouldn't affect this issue.

**Comment by tpejsa** [comment]
Maybe restarting vscode is what fixed it then.

**Comment by roblourens** [comment]
I notice that you're on a slightly old version, can you try downloading the Insiders' build and tell me whether it reproes there? I tried some more and still can't repro.

https://code.visualstudio.com/insiders

**Comment by ElranKadosh** [comment]
Windows 10
VSCode 1.18.1

Hi guys,
I'm having the same problem for both my web(default support) and Python(with the official Python extension installed) projects. For some of those(web projects) VSCode works fine but for the others that indexing problem occurs. I deleted any cache/settings both for my user and projects and even uninstalled(then re-installed) VSCode but it still occurs in the same projects. For those(with the indexing problem), I can only find files(quick open, search in files, etc.) that has been opened already in the editor. I tried the Insiders build and it doesn't seem to be solved(yet) there.

Regards,
Someone who really wants to use this editor more

**Comment by roblourens** [comment]
@ElranKadosh This issue is about very large projects - 100,000+ files included. Is that the case for your projects? If not, open a new issue and look very carefully at your `search.exclude` and `files.exclude` settings at the folder and user level.

**Comment by ElranKadosh** [comment]
Hi Rob, FYI, I just did:
https://github.com/Microsoft/vscode/issues/40076

**Comment by chrmarti** [comment]
@tpejsa Did you have a chance to retry with a recent version?

**Comment by kzhui125** [comment]
I have the same issue, go to file is unusable for me..
@roblourens

**Comment by kzhui125** [comment]
![image](https://user-images.githubusercontent.com/11925432/35195747-fac779c4-ff02-11e7-9931-c66aa9cf25fc.png)
![1](https://user-images.githubusercontent.com/11925432/35195751-ff1c8190-ff02-11e7-9ada-fd9ea0f7b455.gif)

**Comment by kzhui125** [comment]
Update:
after deleting .gitignore it works.

How to use "ctrl + p" to search files ignored by .gitignore?

**Comment by roblourens** [comment]
You can set `"search.useIgnoreFiles": false` to disable this.
