### ISSUE TITLE
macOS: In the integrated terminal, can't use CMD + Left/Right arrow to go to the beginning/end of the line

### ISSUE THREAD

**Issue by rafasoares** [Microsoft/vscode#39442]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0 (macOS High Sierra version 10.13.1)

### Steps to Reproduce

1. Open the integrated terminal
2. Type some text
3. Press <kbd>⌘ command</kbd> + <kbd>←</kbd>

Reproduces without extensions: Yes

### Expected outcome

The cursor should go to the beginning of the command prompt / line.

### Actual outcome

An uppercase `D` is inserted.

### Observations 

The same happens with <kbd>⌘ command</kbd> + <kbd>→</kbd>, with an uppercase `C` being inserted instead.

Using the <kbd>Home</kbd> and </kbd>End</kbd> keys on a full-sized keyboard work as expected, although it's not how macOS apps are expected to behave.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11314
