### ISSUE TITLE
Inconsistency of color of text written between tags in HTML and JSX in Quiet Light theme

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#39449]
"Add" text in these screenshots.

JSX
![screenshot from 2017-12-02 08-20-38](https://user-images.githubusercontent.com/26769888/33511050-6ab4ad92-d73a-11e7-866a-8f46975120fa.png)

HTML
![screenshot from 2017-12-02 08-20-33](https://user-images.githubusercontent.com/26769888/33511055-7c35035a-d73a-11e7-9d91-3c46ccace1db.png)

**Comment by aeschli** [comment]
That's just how it it. All depends on what scopes the differents grammars (html: no scope), jsx: `tag.meta`) use and the decisions of the themes on what to colors.
The workround is to use a theme that doesn't color `tag.meta`, e.g. the default light theme.
Closing as won't fix.

**Comment by aeschli** [comment]
fixed by #39451, thanks @ajitid
