### ISSUE TITLE
Explorer view is not localized

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#39452]
- VSCode Version: Code - Insiders 1.19.0-insider (adcde8ddeb37f7a5881494707b13353e3f560097, 2017-12-01T05:15:02.148Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.3.0
tslint|eg2|1.0.24
python|ms-|0.8.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Change display language to "ja"(any)
2. Click Explorer view in activity bar
3. result
![fe44b53bd56cddff48a2c605034fa346](https://user-images.githubusercontent.com/8474118/33513157-615893b2-d780-11e7-85d8-8415aadd8b36.png)

Reproduces without extensions: Yes

---

I confirmed translated text exists in i18 folder.

similar issue : https://github.com/Microsoft/vscode/issues/29098

**Comment by EbXpJ6bp** [comment]
I can't reproduce in 9eb01697d327df8934154c8e75069a5ae368d402 on Code built by me.
I will close this after checking Insider-build.

**Comment by isidorn** [comment]
@EbXpJ6bp yes, please try with latest insiders

**Comment by EbXpJ6bp** [comment]
![a7f684b46f90809daa6d82a7c7ae55b8](https://user-images.githubusercontent.com/8474118/33547805-a0e6849a-d928-11e7-8d3d-9294767ad953.png)

thanks!
