### ISSUE TITLE
undescore not working in integerated terminal

### ISSUE THREAD

**Issue by krishna-akula** [Microsoft/vscode#39456]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mips|kda|0.0.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
java|red|0.15.0
vscode-yacc|se2|1.1.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
Duplicate #37989
