### ISSUE TITLE
Cursor jumps to the last row of document

### ISSUE THREAD

**Issue by kyleamadio** [Microsoft/vscode#39455]
If I press CTRL + S - this saves then if I press Downarrow - the cursor jumps to the last row of document.

Sorry really annoying !

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-41-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.1.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
jquerysnippets|don|0.0.1
tslint|eg2|1.0.24
vscode-JS-CSS-HTML-formatter|lon|0.2.3
view-in-browser|qin|0.0.5
java|red|0.15.0
html-preview-vscode|tht|0.1.1
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Edit a Document
2. Press CTRL + S
3. Press Up or Down Arrows

Cursor will jump to bottom current document

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
Duplicate #39350
