### ISSUE TITLE
[VSCodeEndGameTesting-Aditi][Intellisense] Intellisense pop-up is not displaying at right position and options are misleading.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#3945]
OS: Windows 10

Steps:
1. Launch VS code.
2. Open C# coded UI project.
3. Updated field name for class object to get some compilation error.
4. Click on intellisense icon to fix the error.
4. Verify suggested options in intellisense pop-up and try to apply.
Actual:
1.  Intellisense Pop-up is displaying at wrong position.
2. Options like " Create Field", "Create property" are not working (no action when user tries to fix with those options).
3. Once user apply the given options then it should not display again but when I selected option "Declare local variable" then it is showing same option again in intellisense pop-up though action has been taken (in my case I applied "created local variable" and local variable has been created but I am getting same option again and each time when I select that I will create a new variable") .

Expected: User should not get redundant options like "Create Field", "Create Local Variable", "Create property" etc. The correct option for end user is "Generate field in class.

![irrelevant-options-declare local variable](https://cloud.githubusercontent.com/assets/17735796/13658026/9ebee418-e628-11e5-910d-5021ae7b18de.png)
![pop-up position](https://cloud.githubusercontent.com/assets/17735796/13658025/9eabc9fa-e628-11e5-9c87-7154c23d569e.png)

Actual:

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#85
