### ISSUE TITLE
Bug in closing brackets 

### ISSUE THREAD

**Issue by OfficialFused** [Microsoft/vscode#39468]
- VSCode Version: Code - Insiders 1.19.0-insider (34c44f872c177d6f9439706418f8fe49bf125d08, 2017-11-17T05:14:07.221Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-html-css|ecm|0.1.8
vsc-material-theme|Equ|1.1.2
php-intellisense|fel|2.0.2
StackSearchExt|gcr|0.0.2
Go|luk|0.6.69
python|ms-|0.8.0
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
open-html-in-browser|pea|0.0.2
java|red|0.15.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
JavaScriptSnippets|xab|1.5.0

---

If the block code isn't indented correctly it doesn't close the whole bracket block but just what's indented

**Comment by ramya-rao-a** [comment]
@OfficialFused Please provide reproducible steps along with sample code

**Comment by OfficialFused** [comment]
Create and if block with for example 3 statements
Select the three statements
Press shift+tab
Now try closing the whole if block with the little minus at the left of the
if statement
It doesn't close it at all... Just like of ot recognizes the if block by
indentation instead of brackets

Il 11 dic 2017 8:57 PM, "Ramya Rao" <notifications@github.com> ha scritto:

**Comment by ramya-rao-a** [comment]
@OfficialFused After pressing Shift-Tab on the lines inside the if block, I no longer see the minus sign for collapsing the if block.

And yes, the regions (the + and the - signs for expanding and collapsing regions) are identified by indentation and does not depend on the actual code or the language.

You can define your own regions as well. See https://code.visualstudio.com/updates/v1_17#_folding-regions.

Hope this helps.
