### ISSUE TITLE
vscode 1.18.1 rg.exe cpu 90% what is?

### ISSUE THREAD

**Issue by richard1015** [Microsoft/vscode#39463]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.3.10
cssrem|cip|0.0.3
angular2-snippets|dan|1.0.16
vscode-simpler-icons|dav|1.5.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Can you please follow this steps and provide more information https://github.com/Microsoft/vscode/wiki/Performance-Issues
