### ISSUE TITLE
[Extension dev] Errors caught by promise.then and try/catch clause are not typical Error object

### ISSUE THREAD

**Issue by LazarusX** [microsoft/vscode#39465]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|1.1.15
r|Iku|0.5.1
latex-workshop|Jam|3.8.0
vscode-docker|Pet|0.0.22
gitignore|cod|0.5.0
tslint|eg2|1.0.24
python|ms-|0.8.0
azure-account|ms-|0.2.2
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
java|red|0.15.0
vscode-icons|rob|7.18.1
azure-iot-edge|vsc|0.1.1
azure-iot-toolkit|vsc|0.4.2
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. Use the yo-code generator to scaffold a TypeScript extension
2. Replace the `activate` function in extension.ts with the following code
```typescript
export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.window.showQuickPick(new Promise((resolve, reject) => {
            setTimeout(() => {
                reject(new Error("does not work"));
            }, 2000);
        })).then(null, (error: Error) => {
            vscode.window.showErrorMessage(error.message);
        });
    });

    context.subscriptions.push(disposable);
}
```
3. Set a breakpoint on the line of `vscode.window.showErrorMessage(error.message);`
4. Start debugging
5. In extension development host, invoke command palette and execute the "Hello World" command
5. Go back to the original window, type `error.message` and `error.stack` in console.
6. The expected value for `error.message` should be `"does not work"`, but the actual value is `undefined`. See the below screenshot:
![image](https://user-images.githubusercontent.com/716650/33516279-2d10e5e8-d7ab-11e7-9e09-27f3074a6df6.png)

**Comment by formulahendry** [comment]
Add more info: If the Promise in `vscode.window.showQuickPick` return `reject`, the spinner of the dropdown list is still always showing the `loading` status.

**Comment by formulahendry** [comment]
Hi, is there any update about this issue? We have several Azure extension using `showQuickPick` API to show the Azure Resource list, and sometimes it is always showing the `loading` status.
