### ISSUE TITLE
CompletionItem.sortText doesn't appear to influence sorting

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#39464]
In the screen shot below `__call` has `"sortText": "zzz"` yet it is first in the list when compared against `aCall` and `bCall`.

![screenshot from 2017-12-02 23-27-45](https://user-images.githubusercontent.com/5885195/33515534-288cc27c-d7b9-11e7-88b5-620386481946.png)

**Comment by jrieken** [comment]
You also need to set the sort text of the other items as we only compare sortText with (other) sortText
