### ISSUE TITLE
Low contrast of attributes of HTML in Quiet Light theme

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#39460]
VSCode highlights its occurence first and then highlights its selection on top of it, making attributes in JSX to get hidden completely.

JSX code ->

Occurence highlight
![screenshot from 2017-12-02 15-14-34](https://user-images.githubusercontent.com/26769888/33514125-d8281196-d773-11e7-852b-0a0b754dece9.png)

Selection highlight
![screenshot from 2017-12-02 15-14-24](https://user-images.githubusercontent.com/26769888/33514130-ee043030-d773-11e7-9e97-c3802e1ee088.png)

Also attribute names, because of their low contrast, are very hard to read.

**Comment by aeschli** [comment]
fixed by #39451
