### ISSUE TITLE
git.enabled in multi-root workspace

### ISSUE THREAD

**Issue by Cardinal90** [Microsoft/vscode#39479]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Is it possible to make `git.enabled:false` config setting work per folder in multi-root workspace? I understand, it may be tricky, if two folders have the same provider. I'd like to have that option mostly to hide unneeded providers in the source control panel (they can be closed of course, but only until restart). 

Also `git.enabled` can't be used in workspace settings. You can't disable git integration at all in multi-root mode, which seems counter-intuitive.

**Comment by joaomoreno** [comment]
You can configure pretty much any setting per folder in multi-root workspace.

Open your settings. There will be a section called `Folder Settings`.
