### ISSUE TITLE
IntelliSense is not really that intelligent

### ISSUE THREAD

**Issue by aircatcher** [Microsoft/vscode#39476]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
xml|Dot|1.9.2
vsc-material-theme|Equ|1.1.2
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
material-icon-theme|PKi|3.1.0

(1 theme extensions excluded)
---

The IntelliSense popup is not really helping me, need to keep switching the filetype in the bottom right corner in order to have that function properly, it is annoying and I don't want to have too many text editing software alternatives on my computer just for that.

I know that I can just install snippets, but that is just unecessary really, unlike Sublime Text

**Comment by Ramaqmar** [comment]
html-snippets
abu
0.1.0
xml
Dot
1.9.2
vsc-material-theme
Equ
1.1.2
cpptools
ms-
0.14.3
csharp
ms-
1.13.1
material-icon-theme
PKi
3.1.0

**Comment by jrieken** [comment]
Please include *reproducible* step, I'll then reopen this issue
