### ISSUE TITLE
Unescaped markdown in "Failed to move to trash" message

### ISSUE THREAD

**Issue by cauebs** [Microsoft/vscode#39474]
- VSCode Version: 1.18.1

Reproduces without extensions: Yes

Image example:
![2017-12-02-17 20](https://user-images.githubusercontent.com/6764500/33519020-80d2b934-d785-11e7-8c4a-ae0b3baaaf8b.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34367
