### ISSUE TITLE
Add support for CSS-in-JS syntax highlighting and autocomplete

### ISSUE THREAD

**Issue by kripod** [Microsoft/vscode#39481]
I think it would improve the developer experience by a lot if there was built-in support for CSS-in-JS solutions like [emotion](https://github.com/emotion-js/emotion), [glamorous](https://github.com/paypal/glamorous) and [styled-components](https://github.com/styled-components/styled-components).

**Comment by Ramaqmar** [comment]
1.18.1

**Comment by auchenberg** [comment]
We are working in a generic TypeScript extension that enables this, https://github.com/Microsoft/typescript-styled-plugin 

@mattbierner can explain you more.

**Comment by mjbvz** [comment]
Yes, this can be handled by an extension. See https://github.com/Microsoft/typescript-styled-plugin for an example of intellisense for styled-components
