### ISSUE TITLE
Keybinding to run a terminal command

### ISSUE THREAD

**Issue by johnpyp** [Microsoft/vscode#39482]
Is there any way to make a keybinding that runs a terminal command? For example, I use the sequence

`git add . && git commit -m "{message here}" && git push`

a lot and I'm wondering if there is a way I could bind that to a key combo so I don't have to type it into terminal all the time.

**Comment by fabiospampinato** [comment]
There's a way. Install my [Terminals](https://github.com/fabiospampinato/vscode-terminals) extension, define your commands there and give them a name, then define a keybinding that executes the following command: `terminals.runTerminalByName`, and pass the name you just used to it via the `args` key.

**Comment by johnpyp** [comment]
Works great! Is there any way to make it so I can use logout or exit depending on my OS? On windows the command is exit and linux it is logout, but I'd like to use the same settings for both.

**Comment by fabiospampinato** [comment]
The extension doesn't support this kind of conditional commands.

You can solve this by aliasing `logout` as `quit` in linux, and `exit` as `quit` in windows, they you can use `quit` for both.

**Comment by johnpyp** [comment]
It seems this kind of thing works, just running both of the commands. Since the other command are unknown on each system, it just returns an unknown command error and runs to the next one. If the valid command is the first one in line, it quits the terminal and I'd imagine doesn't run the second one.

```
{
      "name": "git",
      "focus": true,
      "commands": [
        "git add .",
        "git commit -m \"Keybind push\"",
        "git push",
        "exit",
        "logout"
      ]
    }
```
