### ISSUE TITLE
Disable obtrusive recommendations

### ISSUE THREAD

**Issue by andig** [Microsoft/vscode#39489]
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: High Sierra

I'm new to vscode. After playing for some days I keep getting the `Git project manager` as suggestions (`Would you like to install...`) popping up everytime I'm switching a workspace. I had the extension installed and removed. The `disable (all)` option is not available since it's not installed currently.

How can annoying/repeated recommendations be disabled?

Reproduces without extensions: No

**Comment by fabiospampinato** [comment]
Maybe you can disable recommendations altogether by adding `"extensions.ignoreRecommendations": true` to your settings, I'm not sure 🤔

**Comment by andig** [comment]
I've solved for time being by installing and the disabling everywhere. It would still be good if recommendations- if that is the problem- were not to appear every single time a workspace is switched or vscode restarted.

**Comment by ramya-rao-a** [comment]
@fabiospampinato 
The `Would you like to install` message is not coming from the recommendation service. So the setting you mentioned will not help.

@andig Did you happen to click on the "Install" button for this extension from the [Marketplace](https://marketplace.visualstudio.com/vscode) and then maybe cancel or remove the extension?

**Comment by andig** [comment]
@ramya-rao-a 
> Did you happen to click on the "Install" button for this extension from the Marketplace and then maybe cancel or remove the extension?

Correct. I had the extension installed, tested and then removed:

> I had the extension installed and removed. The disable (all) option is not available since it's not installed currently.

**Comment by ramya-rao-a** [comment]
In that case, this issue is being tracked in #34404

Can you try the below?
- Close all VS Code windows
- Open VS Code
- uninstall the extension
- Reload VS Code.

Do you still see the message?

**Comment by andig** [comment]
> Can you try the below?

I had done this below with out success as far as remember. The workaround was globally disabling the extension.

Repeating this process now- after enabling extension again- it works. 

It's gone for good now, I'll still check #34404. Thanks for the link!
