### ISSUE TITLE
chinese JSdoc can't linefeed

### ISSUE THREAD

**Issue by mianxiu** [Microsoft/vscode#39480]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.3
vscode-great-icons|emm|2.1.20
easy-icons|jam|0.3.1
search-node-modules|jas|1.2.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
stylelint|shi|0.31.0
vscode-autohotkey|sle|0.2.1
unity-tools|Tob|0.1.9
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Pleae provide more details I have no clue what you are talking about

**Comment by mianxiu** [comment]
@isidorn 
think for you help .I think i find some way to revolve it.
when i  using chinese like this in JSdoc
`/*`
`*-测试`
`*-其他`
`*/`
or
`/*`
`*测试`
`*...`
`*/`
no space and`*`,it can linefeed when i use function on the tip.
but if `* 测试`,the tip can't linefeed..
(sorry for  my english...)

**Comment by isidorn** [comment]
As far as I understood you have found a way to resolve it. If not you can probably find a duplicate in our repo similar to this issue.
