### ISSUE TITLE
quickopen: lookup files in `search.exclude` locations

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#39484]
- VSCode Version: 1.18.1

`search.exclude` filter out files and keep the search clean. That's great.

However, at times I wanted to look for files at those locations and have to either locate the file manually from the folder or change the `search.exclude` value just to look for that file.

Would be great if we can have a command that can search at all locations or search at all excluded locations.

### use cases

- Look at transpiled file otherwise excluded from searches normally.
- Open files in node_modules to place breakpoint there for debugging
- Open files in node_modules where currently `F12` always point to the typings files.

**Comment by roblourens** [comment]
There is a button to support this already - in the search viewlet, click the `...` button to expand the details section, and see the toggle button in the 'files to exclude' box which will disable the exclude settings. Anything else would be covered by https://github.com/Microsoft/vscode/issues/20530

**Comment by unional** [comment]
That's not what I'm asking. I'm asking for this:
![image](https://user-images.githubusercontent.com/3254987/33542775-47b46ea4-d889-11e7-9a01-75032fe72eda.png)
And have a way to find all files.

**Comment by roblourens** [comment]
Oh, got it. We did discuss adding a matching button in quick open. I don't know of an existing issue.
