### ISSUE TITLE
Extension installation suggestion fails on Windows with git bash

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/vscode#39494]
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. Have git-bash as the terminal in windows
2. Have pylint installation suggested by VSCode
3. Click install

The command uses a windows path but git-bash requires a unix path

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Looks like this is due to the python extension, please create an issue here https://github.com/Microsoft/vscode-python
