### ISSUE TITLE
Keyboard is not working within the visual studio code

### ISSUE THREAD

**Issue by bilalMlaik** [Microsoft/vscode#39498]
Keyboard is not working within the visual studio code 
VSCode Version: Code 1.18.1 
Operating system : win 8.1 
It is working fine in my office machine but not in home machine please help me to solve this issue

**Comment by cleidigh** [comment]
@bilalMlaik 
Can you provide more information.
- Code does not react to any keyboard entry?
- have you disabled all extensions?
- any more information on the exact behavior?

**Comment by bilalMlaik** [comment]
vs code react to a few keys and do not react according to those keys behavior   
no i have not disable all extension but i uninstalled a few extension to resolve issue but problem remain same
i think, one or more extension is doing problem because when i installed vs code it was working perfectly but after installing a couple of dozen extensions it started to behave incorrectly

**Comment by ramya-rao-a** [comment]
@bilalMlaik As you have figured out, one of the extensions you have is causing the issue.
Please figure out which extension it is and log an issue in the repo for that extension
