### ISSUE TITLE
Ctrl+P fuzzy finder - no finding files when project folder on SFTP Drive

### ISSUE THREAD

**Issue by ryanerwin** [microsoft/vscode#39493]
- VSCode Version: 1.18.1
- OS Version: Windows 10.0.16299.64

Steps to Reproduce:

1. Use SFTP Net Drive to export WSL home folder as a Drive (under Advanced, whether you choose Fixed, Removable or Network, the same behavior results)
2. Press "Ctrl+P" to open Fuzzy Finder
3. Start typing, searching for some file to open... Only previously opened files can be located...

I saw some related posts that the fuzzy finder was slow over network drives, but using the fuzzy finder over a locally mounted drive from WSL shouldn't be too bad... Is there a configuration option to enable the fuzzy finder on non local drives or non NTFS drives?

I also backed up and removed the AppData/Roaming/Code folder to make sure it's not a configuration issue, but even with the default configuration, same behavior.

Reproduces without extensions: Yes

**Comment by ryanerwin** [comment]
FYI, turning off ripgrep fixed it for me... Now if only I had some idea why...
```
“search.useRipgrep": false
```

**Comment by MikeShi42** [comment]
The fix above helped for me, but since GDrive is pushing users to switch to using Google Drive File Stream, being able to use VSCode over a mounted drive I imagine is even more important now.

**Comment by gondar00** [comment]
@ryanerwin Thank you !!! It worked like a charm.

**Comment by roblourens** [comment]
Sorry for not responding earlier. Let me know if you're still having issues. Also try the Remote-WSL extension if developing inside WSL.

**Comment by lcharbon** [comment]
@roblourens Can confirm this is still and issue in Google File Stream 33, VS Code 1.39 and Mac0S Catalina(10.15). Also affects global find. Sublime finds files without issue with same setup.

**Comment by roblourens** [comment]
Ok, this is actually a duplicate of https://github.com/microsoft/vscode/issues/69333 which had some investigation already
