### ISSUE TITLE
File Structure View in Main Window

### ISSUE THREAD

**Issue by SuperDevGuru** [Microsoft/vscode#39495]
- VSCode Version: Latest version. (1.18.1)
- OS Version:

Steps to Reproduce:

1. There isn't any function to display the folder structure in main window. I can only view the folder structure only in side window now.
I think, this will be better if there is a function to display folder structure in main window. (By clicking menu item in context menu.

Thank you.

Reproduces without extensions: No.

**Comment by bpasero** [comment]
@SuperDevGuru can you explain what you mean in greater detail?

**Comment by SuperDevGuru** [comment]
Okay. Now I can see the folder structure only in side window. You can check it in the screenshot.
![screenshot1](https://user-images.githubusercontent.com/31942867/33526678-9d0c8f82-d83c-11e7-883b-76ade051e968.jpg)
It is difficult to see the folder structure if there are too many files only in side window.

**Comment by bpasero** [comment]
@SuperDevGuru so where would you expect to see it otherwise?

**Comment by SuperDevGuru** [comment]
In main window. If I click a menu item for it in context menu.
Is it possible?

**Comment by bpasero** [comment]
@SuperDevGuru you want the entire folder structure and all files as a menu up here:

![image](https://user-images.githubusercontent.com/900690/33526876-85f70042-d847-11e7-81f7-f7613f0cfab5.png)


?

**Comment by SuperDevGuru** [comment]
Hmm, Yes, that's okay I think.

**Comment by bpasero** [comment]
@SuperDevGuru very unlikely to happen. However what you can do to quickly find and open a file is to use Ctrl+P and type the name.
