### ISSUE TITLE
Feature Request: Allow full path of a folder or file to be opened via open dialog on OSX

### ISSUE THREAD

**Issue by flyinbutrs** [Microsoft/vscode#39499]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aws-cloudformation-yaml|Dan|0.2.0
vscode-docker|Pet|0.0.22
overtype|ada|0.2.0
project-manager|ale|0.23.0
unique-lines|bib|1.0.0
vscode-puppet|bit|0.4.5
hiera-eyaml|bra|1.0.1
gitlens|eam|6.3.0
terraform-autocomplete|erd|0.0.8
git-project-manager|fel|1.4.0
shell-format|fox|1.1.1
puppet-vscode|jpo|0.8.0
tf-snippets|log|0.5.0
Go|luk|0.6.69
MagicPython|mag|1.0.12
terraform|mau|0.0.19
prettify-json|moh|0.0.3
python|ms-|0.8.0
sublime-keybindings|ms-|3.0.3
Ruby|reb|0.15.0
bash-debug|rog|0.1.0
bash-beautify|sha|0.1.1
terraform-snippets-complete|Log|0.0.1
json2yaml|tux|0.2.0
vim|vsc|0.10.5
better-align|wwm|1.1.6
markdown-all-in-one|yzh|0.11.2

---

On OSX, the "File: Open" and "Workspaces: Add Folder to Workspace" commands result in a window like this:

![image](https://user-images.githubusercontent.com/1248221/33527401-273981e8-d81e-11e7-80de-7926a5dffe82.png)

If I have the path of a folder of file I want to open in my clipboard, there's nowhere to paste it to actually open that file. This may be just a weakness of OSX Finder. If it's not possible to fix directly, a possible solution as follows:

1. User clicks/selects Open or Add Folder to Workspace
2. Check if contents of clipboard represents a path to a file or folder which exists and is readable.
    1. If it does not exist, open file dialog as normal.
    1. If exists and readable, open dialog box to ask if the user would like to open that specific path.
        1. If user says yes, do so.
        2. If user says no, open file dialog as current

**Comment by bpasero** [comment]
Try with Cmd+Shift+G in that dialog. 

![image](https://user-images.githubusercontent.com/900690/33527495-3f1edf54-d852-11e7-94b6-be9ec1d210e2.png)

**Comment by flyinbutrs** [comment]
Thanks for that! I feel silly not having known that earlier...

![facepalm](https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif)
