### ISSUE TITLE
macOS: Cannot open directories by dropping on dock anymore

### ISSUE THREAD

**Issue by 0ff** [Microsoft/vscode#39496]
- VSCode Version: Code - Insiders 1.19.0-insider (5b0fa2eddbe82df90fb07eea120c9447c93dbd2f, 2017-12-01T06:07:42.474Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
vscode-standardjs|che|1.2.0
nasc-touchbar|fel|1.8.2
terraform|mau|0.0.19
vscode-language-babel|mgm|0.0.10
cpptools|ms-|0.14.3
node-debug2|ms-|1.19.0
platformio-ide|pla|0.8.2
project-snippets|reb|0.5.0
vscode-react-native|vsm|0.5.7
vscode-todo-highlight|way|0.5.11
debug|web|0.21.2
markdown-all-in-one|yzh|0.11.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Install latest insider build
2. Drag a directory on the dock icon (or the icon in `/Applications`) - you can't.
3. Repeat with latest release, observe it working

Reproduces without extensions: Yes

The issue seems to be this PR here: https://github.com/Microsoft/vscode/pull/37106
As it doesn't even seem to fix the actual problem (see https://github.com/Microsoft/vscode/issues/25843) I propose reverting it so drag & drop keeps working.

**Comment by bpasero** [comment]
@0ff I can reproduce. how did you find out it could be caused by https://github.com/Microsoft/vscode/pull/37106

@joaomoreno fyi

**Comment by 0ff** [comment]
As this also happens when VSCode is not running at all, I just diff'ed the Insider `Info.plist` against the Release `Info.plist`, then removed the recently added `LSItemContentTypes`, verified it worked again and then traced the change back to this PR.

Please not that the dock is not the only place where this happens (though it's arguably the most used one). This also happens when trying to drop on the application icon in the finder itself.

**Comment by joaomoreno** [comment]
Reverted: https://github.com/Microsoft/vscode/pull/39541

Thanks for the thorough investigation!
