### ISSUE TITLE
4 suggestions (F12 behaviour, scroll page and line behaviour and keyboard title bar)

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#39491]
Hello,

I would like to make 4 suggestions:
1. Make F12 jump to def in another file in PYTHONPATH. I'm using VS Code 1.18.1 and VS Python extension 0.8.0 and it only jumps to defs in the same file, folder or in the Python source code. I added some modules path in launch.json, like this
`"env": {"PYTHONPATH": "${env:OneDrive}/python/my_modules/my_modules"}`
and the program works (it accesses the modules in that path), but F12 doesn't.

2. Keep the screen-wise cursor position for scrolled PgUp/PgDn. Eg. if I'm on the 15th line of the current shown lines (let's assume the line numbers shown are from 100 to 150, and the cursor is in line 115) when I press Alt+PgDn it would show lines 150-200 but the cursor position would be in the same 15th line of the screen (in this example in line 165).

3. Keep the screen-wise cursor position for scrolled Up/Dn. Eg. if I'm on the 15th line of the current shown lines (let's assume the line numbers shown are from 100 to 150, and the cursor is in line 115) when I press Ctrl+ArrowDn it would show lines 101-151 but the cursor position would be in the same 15th line of the screen (in this example in line 116).

4. When listing keyboard shortcuts, keep the title bar visible when scrolling down.
In fact, please consider making this a default wherever you show a list that we can scroll.

Best regards,

JM

**Comment by isidorn** [comment]
@jcrmatos htnkas for the suggestions, however it would be great to have the suggestion per one issue. Please try following these suggestions when filling issues nad then we can decide if those are feature request, bugs, questions and so on
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
