### ISSUE TITLE
use control plate to roll is not smooth.other app is didn't have this question. 

### ISSUE THREAD

**Issue by mengfu188** [Microsoft/vscode#39490]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3
sublime-keybindings|ms-|3.0.3
java|red|0.15.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Sorry, I have no clue what you are saying. Please try to follow this when filling issues https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
