### ISSUE TITLE
Unclear setting description

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#39504]
```json
// Ignore extension recommendations
"extensions.ignoreRecommendations": true
```

To this day, I have no idea what this option does.

**Comment by prograhammer** [comment]
When you open a project a message appears at the top telling you there are recommended extensions for that project. This is typically a workspace level setting. Also, when you open the extensions panel, you'll see the list of recommended extensions there too. Turn this setting to `false` if you don't ever want to see these.

**Comment by usernamehw** [comment]
@prograhammer what do you mean?
> Turn this setting to false if you don't ever want to see these.

`false` is the default value. Are you saying that by default I shouldn't see recommendation panel? Recommendation notification popup?

**Comment by ramya-rao-a** [comment]
Updated the message to `If set to true, the notifications for extension recommendations will stop showing up.`
