### ISSUE TITLE
VS Code hanging onto process on port 9229

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#39508]
- VSCode Version: Insiders 1.19.0
- OS Version: macos 10.12.6
- Node version: 8.9.1

![image](https://user-images.githubusercontent.com/1202528/33529026-74b4f5b4-d838-11e7-90b1-719361f226d9.png)

Steps to Reproduce:

1. Run a node process with `node --inspect` in VS Code (via npm scripts)
2. CTRL-C the process
3. Repeat step 1

I get the error that the address is in use. 

```
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

I run the command below and see this
![image](https://user-images.githubusercontent.com/1202528/33529040-bc1e6444-d838-11e7-95b8-23cd86004938.png)

Then I reload the VS Code window. The process is no longer shown when I run the same `lsof` command.

Interestingly ... when I run the same commands from an external terminal I don't have a problem running it repeatedly.

This repo here is what I used ... https://github.com/johnpapa/angular-ngrx 
- I ran `npm run dev-proxy` to reproduce this

**Comment by johnpapa** [comment]
cc @chrisdias as FYI

**Comment by Tyriar** [comment]
I can't seem to reproduce. Not sure what we can really do here anyway as this is all you shell running and stopping the processes, we don't do anything. @johnpapa anything else that might help a repro case? Did this happen for you 100% of the time?

**Comment by roblourens** [comment]
This may have been https://github.com/Microsoft/vscode/issues/39813 as well, although I think that would have caused `node --inspect` to fail. Can you try again in the latest Insiders?

**Comment by johnpapa** [comment]
yep. i'll try again today. if i can reproduce it, i will make a video.

**Comment by johnpapa** [comment]
I can no longer reproduce this. Perhaps one of the insiders versions that came out recently fixed it ... or it was an aberration. Let's close this, and if it happens again I'll reopen it.
