### ISSUE TITLE
Javascript snippets es target version

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#39500]
- VSCode Version: 1.18.1
- OS Version: Win

I think after last update the inbuilt JS snippets are targeting es6. My project is more or less es3 (configured so in ``jsconfig.json``). Is there a lang option somewhere that I can't seem to find? Even if there is I think inbuilt snippets schould respect ``jsconfig.json``.

![](https://drive.google.com/uc?id=1BdrgVyXbyMuzOUorNK8NaZ67jeDU0JZN)

Thank you.

**Comment by mjbvz** [comment]
No, there is no option to change this. We decided to update our builtin snippets to ES6 since many users are now targeting it.

If you are writing ES3 or es5, I recommend looking on the marketplace to see if there are any snippet extensions that work or writing your own snippets

**Comment by Spown** [comment]
While I wouldn't argue about node.js side of this, since it is developer's responsibility to keep his app up to date, browser-side js is still better kept es3-comliant, because developer has little to no control over what type of browser end-user will be using. I still think it should be respecting ``jsconfig`` maybe even in a way how jshint does it - with a subfolder config file overriding the one higher.

AnywayI can write my own version of user-snipets for js, but how do I turn off the standard ones?

![](https://drive.google.com/uc?id=1Tjt7xz6qzFrEsyb3bW6qORkKp2YRTnfr)

The option below disables everything, not only snippets.

```
"[javascript]": {
        "editor.snippetSuggestions": "none"
    }
```
