### ISSUE TITLE
Retain the tree expansion state after tree refresh

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39505]
To reproduce

- Install the [jsonOutline extension](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/package.json) (Clone it, build it and link it in extensions folder)
- Open any json file, that will show the json outline view
- Expand and collapse some nodes
- Refresh the complete outline / or any node 

Expected: Expansion states are preserved.
Observed: Expansion states are reset to initial state.

![kapture 2017-12-03 at 20 16 39](https://user-images.githubusercontent.com/10746682/33528786-10033714-d867-11e7-87ba-105c680b78d9.gif)

**Comment by sandy081** [comment]
![kapture 2017-12-03 at 20 13 06](https://user-images.githubusercontent.com/10746682/33528767-6a33d924-d866-11e7-817f-6122f0a2baf2.gif)

**Comment by letmaik** [comment]
To clarify, how are two tree items before and after a refresh matched up to determine that they are the same? It seems each item has a string ID constructed from the tree path.
So:
```
a
  - b
  - c
```
Where `a` has an ID of `0/0:a` and  `a/b` has `0/0:a/0:b`. However, if I had the following updated tree:
```
a/0:b
b
  - c
```
Then the first tree item would likely also have the ID previously assigned to `a/b`: `0/0:a/0:b`. Or is there some escaping going on? I know, it is an artificial example and probably no tree item ever will have such a weird label.
I'm not saying this is an issue, just trying to understand it and find corner cases that may blow up something.

**Comment by sandy081** [comment]
@letmaik Good point. There is no escaping happening. Had similar assumption that this is not a practical scenario. But do not like to leave this case open. Will do the escaping.

**Comment by weinand** [comment]
@letmaik I have similar issue with IDs because in my case tree node labels (and hence IDs) change dynamically. Please find a workaround in https://github.com/Microsoft/vscode/issues/40018#issuecomment-351685226
