### ISSUE TITLE
Intellisense not working after downloading tsd script for npm downloaded modules version 0.10.10

### ISSUE THREAD

**Issue by sarkarstanmoy** [Microsoft/vscode#3950]
Hi,

In version 0.10.10 intellisense is not working after downloading typescript for the modules which I have downloaded using npm like express, firebase etc. But version 0.10.08 is working fine and I am able to see intellisense working flawlessly.

**Comment by egamma** [comment]
Duplicate of #3791, see this comment https://github.com/Microsoft/vscode/issues/3791#issuecomment-193690551
