### ISSUE TITLE
Can't disable popup when input colon in html file

### ISSUE THREAD

**Issue by sergeos** [Microsoft/vscode#39502]
After entering a colon, a pop-up menu appears, which I do not need. 
This menu appears only if the file type is HTML. 

![popup](https://i.stack.imgur.com/DE0iP.png)

How possible disable this popup?

**Comment by aeschli** [comment]
Trigger characters can't be user configured. You can, however, turn of trigger characters fully:
```json
	"[html]": {
			"editor.suggestOnTriggerCharacters": false
	}
```

**Comment by aeschli** [comment]
@jrieken to decide if such fine grained configurability is planned.

**Comment by jrieken** [comment]
> if such fine grained configurability is planned.

Nope. That is seems that HTML defined `:` as word character
