### ISSUE TITLE
Does vscode support TODO list?

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#39516]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

I mean a source code that commented with special some mark, for example in python we could have a comment like: `# TODO: need to get EmailAddress object from user object`. Then we could have a have a special command that list all of them and we could jump to that file and line.

This would be useful when we have some unclear idea or a problem that we couldn't fix right away, and we want to make a note about it. We could jump to another problem and when we ready we could just jump right back for it.

I think jetbrains support this feature.

Oh and `# NOTE: `

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

**Comment by tangorboyz** [comment]
Not so helpful, as list all todos not working for python. In my case it only list the todo in javascript. It list all todos in output panel; to jump to the file, we have to `alt+click` to follow link and `alt+click` not working on my ubuntu.
It would be helpful if todos have it's own panel.

**Comment by usernamehw** [comment]
So, you have 2 other problems: 
* You did not read the extension description
use `"todohighlight.include"` property to include `"**/*.py"`
* cannot follow link on Ubuntu

**Comment by tangorboyz** [comment]
Ok, it's `ctrl+alt+click` to follow link on ubuntu #34710
I just think about todos own panel.
