### ISSUE TITLE
Provide Symbolic Icon

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/vscode#39511]
- VSCode Version: 1.18.1
- OS Version: Fedora 27 (64bit / GNOME 3.26.2), effects all Linux distros esp those using GNOME3

Steps to Reproduce:

1. Open VSCode
2. Look at topbar

Reproduces without extensions: N/A

GNOME displays the current application icon in the topbar next to the application menu

Where possible a symbolic icon is used in place of the full-colour icon

As VSCode does not provide a symbolic icon it looks rather out of place:
![screenshot from 2017-12-02 18-14-44](https://user-images.githubusercontent.com/17074021/33518435-d0dae60c-d78c-11e7-86fc-4609b9a4af43.png)
The blue broken infinity just dissapears into a world of gray and black

However by placing an svg [such as this](https://gist.github.com/ZanderBrown/9690f1c3858c1fbd467c186058f7f96b) in `[prefix]/share/icons/hicolor/symbolic/apps` as `code-symbolic.svg` we get a much better effect whilst retaining the full colour icon in the applications menu and app switchers

![screenshot from 2017-12-02 17-55-11](https://user-images.githubusercontent.com/17074021/33518359-9f77d1d4-d78b-11e7-9076-e5016bd7950e.png)

In GNOME symbolic icons are also used in high contrast mode instead of the colour icons

Whilst this primarily effects GNOME it may be of benifits to other Desktop Environments and GNOME is used on Ubuntu, Fedora and many other distros by default

**Comment by bpasero** [comment]
We are currently considering our icon as final. Please see https://code.visualstudio.com/blogs/2017/10/24/theicon and thanks for understanding.

**Comment by ZanderBrown** [comment]
No! I'm not suggesting the colour icon is replaced, I'm suggesting a symbolic icon is provided to complement the colour icons on the Linux releases as is common in the GNOME environment.

For example, GNOME Calculator has a full-colour standard icon used in the Applications menu, Search, About ext
![screenshot from 2017-12-04 17-29-53](https://user-images.githubusercontent.com/17074021/33566866-40e2e3f4-d919-11e7-8727-ebc4adf81de0.png)

However, when running a symbolic icon is used on the topbar
![screenshot from 2017-12-04 17-30-01](https://user-images.githubusercontent.com/17074021/33566845-3064cf42-d919-11e7-87a0-af2f9bd912c7.png)

**Comment by ZanderBrown** [comment]
@bpasero  consider reopening?

**Comment by bpasero** [comment]
Please see https://code.visualstudio.com/blogs/2017/10/24/theicon
