### ISSUE TITLE
[php] Provide more specific PHP scopes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3951]
_Requested on http://stackoverflow.com/questions/35894983/vscode-theme-color-for-php_

Currently `class`, `function`, `public`, etc. are only scoped with the `keyword` scope. It would be good if more specific scopes for more granular theming was possible, `function` should have the `function` scope as per https://manual.macromates.com/en/language_grammars for example.

This may be fixed doing away with the current implementation and taking up a community plist for tokenizing instead.

**Comment by roblourens** [comment]
Looks like this is not the case anymore.
