### ISSUE TITLE
Feature request: Sharing of user settings and extensions between machines and/or users

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#39514]
Hello,

I would like to suggest sharing of user settings and extensions between machines and/or users.
This could be something as simple as selecting a network share or a OneDrive/Dropbox/etc share.

Best regards,

JM

**Comment by auchenberg** [comment]
We have an extension for this in the marketplace, https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
