### ISSUE TITLE
Search term should not be retained when closing and reopening Settings/keybindings editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39512]
Steps to reproduce

Keyboard Shortcuts - Second Situation:

- Open Keyboard Shortcuts / Settings editor and provide a filter
- Close the editor and reopen it

Expected: Filter is not retained
Observed: Filter is retained

**Comment by sandy081** [comment]
@bpasero What is the current expected UX behaviour in this case?

**Comment by bpasero** [comment]
@sandy081 depends. we typically retain as much view state as possible when reopening a file (e.g. cursors, folding). 

I would not expect that settings or keybindings editor preserve the state of the filter though.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@sandy081 I do not think you got what I said !!

It is not to save what I researched in the field when I close the editor. (Must be kept as is)

Not to save anything !!

What it is to change: What I said is that it still saves when you open settings, search something, close the settings tab and reopen again.

When closing the editor it really should not bring anything that was previously searched.

Let me know if you get it now !! Or if Google Translator betrayed me again.

**Comment by sandy081** [comment]
@Tekbr I think the summary/description of this issue aligns to what you mentioned in above comment.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@sandy081 Uhmm .. I put a gif tried to explain ...

![settings-key](https://user-images.githubusercontent.com/19866231/33612965-689aa82c-d9ba-11e7-942d-40c980b193d0.gif)


**Note:** If Settings or Key are open when Reopening the VSCode these can keep what was searched.


> @Tekbr I think the summary/description of this issue aligns to what you mentioned in above comment.
Anyway, it gets a boost. I think translation confused me with what @bpasero  wanted to say.

Sorry for the misunderstanding. 😊 😊

**Comment by sandy081** [comment]
Filters are part of the state we retain when settings/keybindings editor are closed and opened. Closing this as designed.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@sandy081 I still see with a problem. For a comparison, Atom does not keep the information after we close the Settings tab. I hope that in the future it will be changed.
If I closed the tab I do not want to search for what was typed.

**Comment by sandy081** [comment]
I see Atom does it that way. But we have this behaviour for a long time and it is good (not many complaints). Not sure if I would like to change the behaviour now which is not buggy.

**Comment by Tekbr** [comment]
@sandy081 All right ... Anyway thanks for the feedback. 👍
