### ISSUE TITLE
Split alias of built in commands between category and title

### ISSUE THREAD

**Issue by qcz** [microsoft/vscode#39510]
- VSCode Version: Code - Insiders 1.19.0-insider (adcde8ddeb37f7a5881494707b13353e3f560097, 2017-12-01T05:15:02.148Z)
- Also reproducible in VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.20
vscode-todo-plus|fab|1.7.1
debugger-for-chrome|msj|3.5.0
sort-lines|Tyr|1.3.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1. Change VS Code language to Hungarian/German etc.
2. Open the Command Palette. Original command category names (displayed in the second line after the translated command) are duplicated in the command palette and the first is randomly translated when using a non-English localization:

![image](https://user-images.githubusercontent.com/304384/33529423-056fdc4e-d871-11e7-8562-57ce30224a9b.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@jrieken likely a regression from https://github.com/Microsoft/vscode/commit/65d45fd985e6b41fcb5900ad4cbbacb637a5e8ac#diff-b90278b8812101a32d844114fa0dc752

Reproduces in stable.

**Comment by Tekbr** [comment]
@bpasero  @jrieken In fact since Portuguese Brazil was released for the Insiders, I realized that. On the one hand I find it good since the translated name becomes strange (yes, it has translations that are wrong / it does not make sense to put the name / or have not yet been translated.)

Here is an example of wrong translation / meaningless.

![traducao](https://user-images.githubusercontent.com/19866231/33609390-09e0c45c-d9af-11e7-9e86-f90e18b77e71.PNG)


I vote for a settings to bring the two, both English and the selected language. And if the user does not want the same can disable.

I would still like the search field to continue searching for English and the selected language even if the function is disabled.

Thoughts? 🤔

**Comment by jrieken** [comment]
> Thoughts? 🤔

I think you are on the wrong issue. This is about label duplication and half-half-translation. I do agree on having the untranslated bit invisible and still search/match on it but should file a new issue for. Or, bonus points, find an existing issue about it. Thanks

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@jrieken Why do you think that? 🤔 🤔 😊 😊 

Is not it about that question? (picture below)

![traducao2](https://user-images.githubusercontent.com/19866231/33626466-cee81872-d9e1-11e7-8267-b2bc71d70a17.png)


Of appearing in another language and English at the same time in the Command Palette?



If not, I'm sorry. Google Translator betrayed me one more time. 😊 😊 😊

**Comment by qcz** [comment]
@Tekbr: No, this issue is about the duplication of the category name in the original, English command. For example on the screenshot you can see 'Preferences: Preferences:' (there should be only one 'Preferences:') and 'Beállítások: Preferences:' (there should be no translated category names in this line).

(PS: I actually like that the original command name is displayed below the translated command.)

**Comment by jrieken** [comment]
This is too many changes for November and also needs to better idea. @bpasero It seems that the translated version is always two strings: (1) the category, e.g 'Developer' and (2) the actual label, e.g 'Show Dev Tools' but the untranslated variant (alias) is always the concatenated string, e.g 'Developer: Show Dev Tools' which is weirdly asymmetric and not sure why that is... Is that model purely driven the UI piece which happens to show both together?

**Comment by bpasero** [comment]
Yeah ugly, ideally we can contribute built in commands with an alias category and an alias command name. For now I pushed https://github.com/Microsoft/vscode/commit/33ed3168fe6ea7817ebe09170653cdc2ae0d4f82 to not show the alias category to avoid duplication. I am not seeing any extension command that uses this feature anyways, so I do not think we are loosing much.

**Comment by jrieken** [comment]
I have pushed a better workaround which simply splits the alias into category and label (when separated by ` :`). This restores the old functionality... 

I'll leave the proper fix to you and I'd use the `ILocalizedString` in that API thing

**Comment by Tekbr** [comment]
> @Tekbr: No, this issue is about the duplication of the category name in the original, English command. For example on the screenshot you can see 'Preferences: Preferences:' (there should be only one 'Preferences:') and 'Beállítások: Preferences:' (there should be no translated category names in this line).
> 
> (PS: I actually like that the original command name is displayed below the translated command.)

-- Sorry for the English, I used Google Translator --

Ahhh ... yes ... @qcz , your explanation was a lot more enlightening to me than @jrieken . Thank you!! 😄 

@jrieken , sorry for the disturbance !! 😊 😊 😊 😊 :stuck_out_tongue::stuck_out_tongue: 😊
