### ISSUE TITLE
go to definition does not work with #define, which is certainly a definition

### ISSUE THREAD

**Issue by negspect** [Microsoft/vscode#39517]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
unity-debug|Uni|1.2.1

go to definition does not work with #define, which is certainly a definition

---

Steps to Reproduce:

1.  make a c# document that looks like this:

#define SQUARE_INPUTS

#if SQUARE_INPUTS
#endif

2.  right click on the second instance of SQUARE_INPUTS and select go to definition.  you will be presented with an error message, even though it is clearly defined directly above

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this agains the c# extension, thanks
