### ISSUE TITLE
cannot download .deb from site

### ISSUE THREAD

**Issue by bnovf** [Microsoft/vscode#39513]
- VSCode Version: 1.18
- OS Version: ubuntu 17

Steps to Reproduce:

1. https://code.visualstudio.com/
Download link does not work
```
This site can’t be reached

az764295.vo.msecnd.net’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by Tyriar** [comment]
Works for me, maybe it's an issue with your network?
