### ISSUE TITLE
JSX attribute hint only displays for stateless functional component

### ISSUE THREAD

**Issue by escapiststupor** [Microsoft/vscode#39520]
- VSCode Version: 1.18.1
- OS Version: MacOS Sierra 10.12.6
- React Version: 16.2.0

Steps to Reproduce:

1. I have created a repo with create-react-app 'as is' and imported a functional component;
<img width="642" alt="screen shot 2017-12-04 at 11 13 31 am" src="https://user-images.githubusercontent.com/8017959/33534715-45f1520c-d8e4-11e7-91fa-9b2e28553652.png">
 at this point VS Code gives correctly the JSX attribute hint
<img width="651" alt="screen shot 2017-12-04 at 11 13 40 am" src="https://user-images.githubusercontent.com/8017959/33534718-4cb91228-d8e4-11e7-8a70-62b9e167f1f8.png">

2. However if I switch to use a react class component
<img width="596" alt="screen shot 2017-12-04 at 11 16 00 am" src="https://user-images.githubusercontent.com/8017959/33534761-8efb69ce-d8e4-11e7-83fe-9c681e419c7b.png">
VS Code no longer gives any hint about the props.
<img width="660" alt="screen shot 2017-12-04 at 11 17 06 am" src="https://user-images.githubusercontent.com/8017959/33534777-b050c5ce-d8e4-11e7-81cf-785e6dfbebbd.png">

Reproduces without extensions: Yes

Here is my sample code:
Hello.jsx
```
import React from 'react';
import PropTypes from 'prop-types';

export default class Hello extends React.Component{
    constructor(){
        super();
    }
    render(){
        <h1>Hello {this.props.name}!</h1>;
    }
}
// Hello.propTypes = {
//     name: PropTypes.string.isRequired;
// }

// export default ({name}) => <h1>hello {name}</h1>
```

The other files are as created by create-react-app.

Thank you in advance.

**Comment by mjbvz** [comment]
You still need to tell our language service that a property called `name` exists. Try using jsdocs like:

```js
/**
 * @augments {React.Component<{name: string}>}
 */
export default class Hello extends React.Component{
    constructor(props){
        super(props);
    }
    render(){
        return <h1>Hello {this.props.name}!</h1>;
    }
} 
```

The `{name: string}` section defines the properties of the component
