### ISSUE TITLE
Suggestion Widget bigger than visible

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#39529]
![](https://drive.google.com/uc?id=1OuushKcdLY-tgSs6MuQWbyOG5BFYLFXI)

This additional area is probably "reserved" for the description box, but when there is no it is still there and it makes everything underneath unclickable until I close the widget. 

- VSCode Version: 1.18.1
- OS Version: Win

**Comment by ramya-rao-a** [comment]
Thanks for reporting @Spown 
This is being tracked in #38484
