### ISSUE TITLE
Error: "No tests ran, please check the configuration settings for the tests."

### ISSUE THREAD

**Issue by garytyler** [Microsoft/vscode#39521]
I am getting error message "No tests ran, please check the configuration settings for the tests."
![capture3](https://user-images.githubusercontent.com/15917021/33537560-f5be2e86-d889-11e7-924d-420a50d97774.PNG)

The tests run fine in command line:
![capture2](https://user-images.githubusercontent.com/15917021/33537569-ffa21f0c-d889-11e7-84a4-9439818066f5.PNG)

Here is the sample code I am using:
![capture4](https://user-images.githubusercontent.com/15917021/33537573-03ee2e8e-d88a-11e7-86df-719071ea4154.PNG)

Here are my settings:
![capture](https://user-images.githubusercontent.com/15917021/33537576-080c057c-d88a-11e7-9b6f-79689c87eb4b.PNG)

I have looked through what little docs I could find and am out of ideas.

**Comment by jdayton3** [comment]
@garytyler I'm having this issue too.  What fixed it for you?
