### ISSUE TITLE
[json] Add telemetry event when user edit a json file for Azure RM.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#3952]
When we refactored JSON to an extension, we lost the telemetry on how many users edit a JSOMN file for Azure RM. We need to add it back with the support telemetry support that @SofianHn added.

**Comment by SofianHn** [comment]
@aeschli I will mark this as verified, I would highly recommend though to update the definition in [here](https://github.com/Microsoft/vscode/blob/e3ddd0074e60c77867ba9ec0bec17ea15f7250b3/extensions/json/server/src/jsonSchemaService.ts#L203) to make the telemetry service grab bag data is a `string:string` dictionary. 
```typescript
export interface ITelemetryService {
	log(key: string, data: {[key:string]:string}): void;
}
```
