### ISSUE TITLE
executeWorkspaceSymbolProvider should accept empty string

### ISSUE THREAD

**Issue by craig006** [Microsoft/vscode#39522]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1 

Steps to Reproduce:

1. Debug an extension on a C# project
2.  run executeCommand vscode.executeWorkspaceSymbolProvider with "" or "*" as a filter
3. either an error is thrown "Illegal argument 'query'" or no results are returned

I would like to prompt the user, from my extension, to select a symbol from the workspace for further processing. I don't have any filter text at this point so would like to show all symbols. I cant seem to get a list of unfiltered symbols using executeWorkspaceSymbolProvider... I need similar functionality to whats available in "Go To Symbol in Workspace...".

Any idea why this does not work?

Example code below. Executing this will result in a zero length array. I cant find any filter value that works as a wildcard. 
```vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "*").then(
            (things: any) => {
                console.log("vscode.executeWorkspaceSymbolProvider")
                console.log(things)
            }, (reason) => { 
                console.log(reason)
            });
```

if I change the filter above to "Service" for example, I get all the coorect results as I would expect:

```
vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "Service").then(
            (things: any) => {
                console.log("vscode.executeWorkspaceSymbolProvider")
                console.log(things)
            }, (reason) => { 
                console.log(reason)
            });
```

**Comment by jrieken** [comment]
> Any idea why this does not work?

No, not without some sample code

**Comment by craig006** [comment]
> No, not without some sample code

I have added a code snippet. Sorry :)

**Comment by jrieken** [comment]
Yeah... That's how it is in our tests: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/test/electron-browser/api/extHostApiCommands.test.ts#L187. Maybe one of your extensions?

**Comment by craig006** [comment]
@jrieken Sorry, I'm not following. I assume that its not possible to query all symbols then? Similar to how cmd+t does it?

**Comment by jrieken** [comment]
You sample looks legit and this is how we test the code. Yes, the command is more or less what the UI calls so everything should work. However, there is always the chance of an extension throwing errors. What again the *exact* error you are seeing?

**Comment by craig006** [comment]
This is everything I have tried:

```
vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "*").then(
            (things: any) => {
                window.showQuickPick(things).then(test => {})
                console.log("2")
                console.log(things)
            }, (reason) => { 
                console.log(reason)
            }); 
```

This returns `Array[0]`

Next I tried:
```
vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "").then(
            (things: any) => {
                window.showQuickPick(things).then(test => {})
                console.log("2")
                console.log(things)
            }, (reason) => { 
                console.log(reason)
            }); 
```
This throws error:
```

Error: Running the contributed command:'vscode.executeWorkspaceSymbolProvider' failed. Illegal argument 'query' - Search string
codeActionProvider.js:249
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:411939)
    at e.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:411279)
    at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:488349)
...
```
Do you think its the omnisharp extension throwing an error? How does the `Go to symbol` command get a full list of symbols from omnisharp?

**Comment by jrieken** [comment]
> Do you think its the omnisharp extension throwing an error? 

Maybe... I don't find this error in our source code. So, either you are on ancient version of VS Code (please try insiders) or this is from an extension (try with `--disable-extensions`)

**Comment by craig006** [comment]
@jrieken I created an issue with Omnisharp and they seem to have found the error in VS code: https://github.com/OmniSharp/omnisharp-vscode/issues/1904

**Comment by jrieken** [comment]
There actually is an issue on our side and that's about the empty string. It should pass the string-constraint but doesn't

**Comment by craig006** [comment]
Awesome! I have resorted to a bit of a filthy hack in the interim...
