### ISSUE TITLE
命令行提示是否要终止运行？ 选择了N，控制台还是把正在编译的进程给关掉了。

### ISSUE THREAD

**Issue by 307914070** [Microsoft/vscode#39524]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this issue in english and follow our suggestions when filling issues

https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
