### ISSUE TITLE
Terminal codes (colors, spacings, etc.)

### ISSUE THREAD

**Issue by khooz** [Microsoft/vscode#39533]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17025
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
php-pack|fel|1.0.1
live-html-previewer|hdg|0.3.0
phpcs|ika|0.7.0
Angular2|joh|2.11.2
format-indent|Kas|1.3.0
phpmd|lin|1.1.4
gitignore|mic|1.0.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
laravel-blade|one|1.10.0
laravel5-snippets|one|1.3.4
vscode-docker|Pet|0.0.22
java|red|0.15.0
sass-indented|rob|1.4.5
laravel-artisan|rya|0.0.14
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Make Laravel migrations with error or just run `php artisan migrate` in a production environment (or any other color coded string)
2. Watch jumbles.

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Can you share a screenshot?
