### ISSUE TITLE
No auto update data in opened tabs

### ISSUE THREAD

**Issue by kobzar** [Microsoft/vscode#39538]
Hello. 
The problem with auto update data in opened tabs . 
For example - we open some json file in new tab. Next we make changes some data in other editor and save it. But VSC doesnt show changes before this file will be reopened.
 I think it’s not good for any developer.

**Comment by rcjsuen** [comment]
I tried this with VS Code 1.18.1 on Windows 10 and could not reproduce the problem. I opened a .txt file and a .json file in Notepad and when I saved it the editor in VS Code updated itself accordingly.

**Comment by kobzar** [comment]
Hmm.
After i reopen VSC - all working fine. OS X.
Thanks.
