### ISSUE TITLE
Class with Regions in Typescript folds inadequate 

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#39539]
- VSCode Version: 1.18.1
- OS Version: Windows 7 pro x64

Steps to Reproduce:

1. Have TS Code with Class+Methods and Regions inside class eg:

```ts
class yada
{
    //#region asdasd
    public yada()
    {
         let x = 5;
    }
    //#endregion
}
```

2. Fold to LEVEL 2
2b. Alternatively try to fold to LEVEL 3
3. notice that methods are not folded inside the regions

it seems that Regions and Methods are same level or hides one another... 

Expected:
Methods should be folded inside the region - SAME AS VISUAL STUDIO PROFESSIONAL 2008, 2012, 2013, 2015, 2017

**Comment by aeschli** [comment]
I'm not able to reproduce with your example code in 1.19
- have a typescript file with your code sample.
- press `Ctrl + K Ctrl 3` (fold level 3): This folds away line `let x = 5;`
![image](https://user-images.githubusercontent.com/6461412/33557645-15101ff0-d908-11e7-815f-f5138461bcde.png)

- press  'Ctrl + K Ctrl + J` (unfold all)
- press `Ctrl + K Ctrl 2` (fold level 2): This folds away the region

**Comment by Montago** [comment]
maybe i should be more specific...

I want to fold level 2 AND 3 at the same time when folding level 2 !

regions AND methods..

**Comment by aeschli** [comment]
Well thats how the `fold level` commands are designed: Just the level, not recursive.
You'll have to press two shortcuts...

We currently have no plans to add additional commands, as the number of fold commands is already quite big.

**Comment by Montago** [comment]
But that makes the function rather unuseful... 

the point of folding is to make large documents more maintainable, and if there is no real difference between using Regions and Not folding, then the value of regions fade away. 

maybe it should be an option to recursively fold upper levels of code - making the fold function more useful.

**Comment by Montago** [comment]
I fixed this issue with a macro...

still think the folding feature is bugged though.

**Comment by aeschli** [comment]
In 1.19 there's also a command to only fold/unfold marker regions (the ones with `#region`).
There are so many different ways of using markers and folding levels, I don't think there is a one-fits all set of commands. What is perfect for your setup, might be unusable for others.
So creating your own macro, for example in an extension, is the way to go.
