### ISSUE TITLE
Test: debug activation event

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39535]
- [x] any os @aeschli   (Linux)
- [x] any os @ramya-rao-a 

Refs: https://github.com/Microsoft/vscode/issues/37918
Complexity: 2

We have introduced two new extension activation events `onDebugInitialConfigurations` and `onDebugResolve:TYPE` (example: `onDebugResolve:node`). Write an extension which activates on these events and verify you extensions gets activated at the right time:

- `onDebugInitialConfigurations` is called whenever a "launch.json" needs to be created 
- `onDebugResolve:type` is called whenever a specific debug session is about to be launched

**Comment by ramya-rao-a** [comment]
@alexandrudima I'd like to volunteer to test this item
