### ISSUE TITLE
ColumnSelect - Cannot read property 'lineNumber' of undefined

### ISSUE THREAD

**Issue by Springrbua** [Microsoft/vscode#39532]
- VSCode Version: 1.18.1 (2017-11-16)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Define a shortcut for command `columnSelect`
2. Use this shortcut to enable `columnSelect`, and the following error message should appear:  
![image](https://user-images.githubusercontent.com/18258317/33542011-8dcd1470-d8d1-11e7-952d-dfb39ffc050e.png)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
That specific command, `columnSelect` is invoked by the mouse handling part of the code and passes in an object where the mouse is. For keyboard column selection operations, please customize. e.g.:

```
{ "key": "shift+alt+cmd+down",    "command": "cursorColumnSelectDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+left",    "command": "cursorColumnSelectLeft",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+pageup",  "command": "cursorColumnSelectPageUp",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+right",   "command": "cursorColumnSelectRight",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+up",      "command": "cursorColumnSelectUp",
                                     "when": "editorTextFocus" },
```

**Comment by Springrbua** [comment]
@alexandrudima I am already using those keybindings. I just thought, that this command is similar to the "Block Selection Mode" in Elcipse. If enabled, you can use normal selection (keyboard or mouse) and you will automatically select columns.  
So instead of using the different commands to select left, right, up, down, you enable columnSelect and use only left, right, up, down keys.  

How exactly do I use the `columnSelect`-Command?

**Comment by alexandrudima** [comment]
@Springrbua You can invoke it from a VS Code extension. Otherwise, using it from the `keybindings.json` is not very helpful, as it takes in an absolute (lineNumber;column), and not relative values.

That command is invoked when you do shift+alt+mouse ops.

**Comment by Springrbua** [comment]
Ah okay, I understand. So it probably should not be shown in the settings?

**Comment by alexandrudima** [comment]
Do you mean at the bottom of `keybindings.json` ?

That list is generated by taking all the registered commands and dumping them there. There are quite a number of commands which do not really make sense to appear there:

e.g.
```
// - default:compositionEnd
// - default:compositionStart
// - default:cut
// - default:paste
// - default:replacePreviousChar
// - default:type
```

I can look into removing them from there...

**Comment by Springrbua** [comment]
@alexandrudima Thanks for the quick response and the information!  
It's nothing important, I can live with the extra-entries in the `keybindings.json`-file :)
