### ISSUE TITLE
How to filter problems log to show only errors, warnings?

### ISSUE THREAD

**Issue by peon501** [Microsoft/vscode#39531]
- VSCode Version:newest
- OS Version:win8.1

Steps to Reproduce:
How to filter problems to show only errors, warnings?
Can I add 2 filters by type or text somehow?

**Comment by sandy081** [comment]
@peon501 Type `error` in the filter box.

Re: #8305

**Comment by peon501** [comment]
@sandy081 but if I want errors and warnings ?

**Comment by peon501** [comment]
can you do split by ' ' or ',' or ';' and show results in array ?

**Comment by sandy081** [comment]
@peon501 #8305 issue is tracking such requirements
