### ISSUE TITLE
vscode version 0.10.10 update failed on ubuntu 14.04 x64?

### ISSUE THREAD

**Issue by dhnnjy** [Microsoft/vscode#3953]
dotnet version output

    .NET Command Line Tools (1.0.0-beta-001675)
    Product Information:
     Version:     1.0.0-beta-001675
     Commit Sha:  N/A
    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  14.04
     OS Platform: Linux
     Runtime Id:  ubuntu.14.04-x64

I updated vscode to version 0.10.10. Then I installed csharp extension. Then I logged off my computer for half an hour. when I returned I saw an error, 

> csharp is not compatible with 0.10.8, please un-install.

so I checked the version, it was 0.10.8. I restarted the machine and still same error. I'm clueless how this happened. update was successful, otherwise it would not let me install csharp extension.

**Comment by dhnnjy** [comment]
I updated again, but after restarting the machine I'm getting the same old version.
Steps I'm following.
1) Download package from [https://code.visualstudio.com/docs?dv=linux64](url)

2)Extract and run Code.

3)Check version =>0.10.10

4)Restart computer.

5) launch vscode and check version =>0.10.8

**Comment by joaomoreno** [comment]
Your system must have something that is reverting your installation.

Code doesn't update itself automatically in Linux. It is not implemented.
