### ISSUE TITLE
Problem seeing hebrew

### ISSUE THREAD

**Issue by boazdori** [Microsoft/vscode#39537]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-eslint|dba|1.4.3
codecpp-full|dod|0.0.1
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|6.3.0
php-intellisense|fel|2.0.2
code-runner|for|0.8.5
CppSnippets|har|0.0.13
ctags-support|jay|1.0.18
vscode-clangd|llv|0.0.1
Go|luk|0.6.69
cmake-tools-helper|mad|0.1.1
MagicPython|mag|1.0.12
vscode-clang|mit|0.2.2
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
vscode-docker|Pet|0.0.22
llvm|RRe|0.0.1
python-editing-terminal|ted|1.0.4
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|0.10.3
jinja|who|0.0.8
clang-format|xav|1.6.1

---

Steps to Reproduce:

1.
import pandas as pd  

df = pd.DataFrame()
df=['שקל', 'מדד']
print(df)
2.
if i run this to the notebook it prints right if i try to run the code to terminal i get reverse code if i try to print to output i get ???
how can this be fixed??

Reproduces without extensions: Yes/No

**Comment by boazdori** [comment]
the same problem occures in visual studio 2017 when running the code i get symbols when running line to jupyter notebook it works ok i sent visual studio a notice on this

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28571
