### ISSUE TITLE
November Endgame

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#39540]
## Endgame Schedule
- *December 4*, Code freeze for the endgame
- *December 11*, Endgame done

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

#### Thursday/Friday week 2
- [x] Merge translations PR (if it makes it in time) **endgame master**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request **@tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@owner**
    - [x] zip **@owner**
  - [x] OS X - **@owner**
  - [x] Linux
    - [x] deb package 64-bit **@owner**
    - [x] deb package 32-bit **@owner**
    - [x] rpm package 64-bit **@owner**
    - [x] rpm package 32-bit **@owner**
    - [x] archives **@owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@owner**
- [x] Publish deb and rpms to repositories manually **@tyriar**
- [x] Add version with symbols to HockeyApp **@tyriar**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen**

---
---

#### Monday

- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items are created (with "complexity" but not necessarily with full description) by 11pm ZRH time (2pm PT)
- [x] All test items contain comprehensive test descriptions by 10pm PT
- Testers who cannot participate in testing check-off from list below:
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @auchenberg
  - [x] @bpasero
  - [x] @chrisdias
  - @chrmarti
  - [x] @dbaeumer
  - @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - @octref
  - [x] @ramya-rao-a
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - @seanmcbreen
  - @tyriar
  - [x] @weinand

#### Tuesday

- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A"November+2017") assigned
- [x] [All closed feature-requests either have a verification-needed or on-testplan tag](https://github.com/Microsoft/vscode/issues?q=label%3Afeature-request+-label%3Aon-testplan+-label%3Averification-needed+-label%3Aduplicate+milestone%3A%22November+2017%22+is%3Aclosed)
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

#### Wednesday

- [x] Remind team members to assign issues that they intend to fix to the November milestone
- [x] Testing
- [x] [Fixing](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22November+2017%22+label%3Abug) (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22November+2017%22)

#### Thursday
- [x] [Fixing last issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22November+2017%22+label%3Abug)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22November+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
  - do not forget to update the `distro` attribute in the package.json with the commit ID of the distro repo.
  - Create list for team members to enter new OSS usage into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**

#### Friday
- Register new components in [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss)
  - [x] `bindings@1.3.0` **@joaomoreno**
  - [x] `byline@5.0.0` **@joaomoreno**
  - [x] `Ikuyadeu/vscode-R@0.0.0` **@aeschli**
  - [x] `@types/source-map@0.1.29` @roblourens
  - [x] `async-limiter@1.0.0` @jrieken
  - [x] `atom/language-shellscript@0.0.0` @alexandrudima
  - [x] `chrome-remote-interface@0.25.3` @jrieken
  - [x] `commander@2.11.0` @jrieken
  - [x] `file-type@7.2.0` @joaomoreno
  - [x] `mkdirp@0.5.1` @joaomoreno
  - [x] `mmims/language-batchfile@0.0.0` @alexandrudima
  - [x] `noice-json-rpc@1.0.1` @roblourens
  - [x] `remove-trailing-separator@1.1.0` @weinand or @roblourens
  - [x] `spdlog original@0.14.0` @joaomoreno
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node-debugadapter-node **@weinand**
  - [x] node-debug **@weinand**
  - [x] node-debug2 **@roblourens**
- [x] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) **@dbaeumer**
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows @dbaeumer 
  - [x] OS X @sandy081 
  - [x] Linux @bpasero 
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22November+2017%22)
- All release notes updated - release notes are collected in a file named *`v1_19.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - @ramya-rao-a
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - @tyriar
  - [x] @weinand
- Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section:
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-filewatcher-windows **@bpasero**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@danyeh**
  - vscode-github-issues-prs **@chrmarti**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - Trigger new insider build and publish it manually **change author**

#### Friday or Monday week 2
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@gregvanl**

#### Monday week 2 - Wednesday week 2
- [x] Polish release notes **@gregvanl**
- Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **change author**
- Build `Insider` from `release/<x.y>` **endgame master**
- Manually release `Insider` **endgame master**
- Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [x] @rebornix
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @tyriar
  - [x] @weinand

**Comment by Tyriar** [comment]
Closing as we shipped v1.19
