### ISSUE TITLE
search 'files to include/exclude' should allow ';' as a separator

### ISSUE THREAD

**Issue by draeger-charles-wilson** [Microsoft/vscode#39549]
VSCode 1.18.1
OS Windows 7

Search should allow semicolon (';') as a separator in the file inclusion / exclusion specifiers in addition to comma (',').

**Comment by roblourens** [comment]
Is there a problem with comma?

**Comment by draeger-charles-wilson** [comment]
The separator within VisualStudio proper is a semicolon. It would be nice to have an added bit of consistency.

**Comment by Peteraya** [comment]
Where can we find in the code the function that "trims" the strings put in "files to include"? I'm trying to find where in the code we see the separation of the files with the comma, but I'm not finding it.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/daf63a3ad169cd8161ddbadf3fe3f2a414f93800/src/vs/workbench/parts/search/common/queryBuilder.ts#L306
