### ISSUE TITLE
Preview file content while searching/using navigation (CMD + P)

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#39546]
Hello, I want to suggest feature.

Right now in Sublime Text 3 you can preview file content while you're searching with CMD + P, like it is right now in VS Code, BUT difference is we can't see file content in VS Code like it's in Sublime Text 3.

How it works? Use CMD + P and file is opened automatically, but in preview mode. So if you change it to another file the last one content will be replaced with new one. I guess better is to simply download ST 3, and try to navigate between files with CMD + P and you will understand better what feature I want to suggest.

You don't need to cache file content, just simply open it, but keep it in preview mode. This helps a lot to search not for filename, but also for file content.

If you don't want to download ST 3, you can go to the website https://www.sublimetext.com/ and you will see preview. This feature is called Goto Anything.

**Comment by smuuf** [comment]
Have you tried switching `workbench.editor.enablePreview` to `true`? *(that's even the default option)*

It's true that the file is _not_ simultaneously opened in the background while you type, but that would still be pointless with files longer than your screen's height.

**Comment by bsvipas** [comment]
@smuuf Yes, but it's not the same feature I'm talking about. It's not pointless, because you can keep it open and scroll if you want and then navigate to another one. Just check ST 3 website or download it to understand better.

**Comment by roblourens** [comment]
There is another issue for this here: https://github.com/Microsoft/vscode/issues/8939

But also you can use the right arrow key when quickopen is visible to preview the selected file.
