### ISSUE TITLE
Open a diff of 2 files from the command line

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3954]
**Assignees:**

- [x] Windows @dbaeumer 
- [x] OS X @bgashler1 
- [x] Linux @joaomoreno 

You can now bring up the diff editor on any 2 existing files by using the command line in the form:
 `code --diff <file1> <file2>`
* Verify this opens the diff editor on the provided files
* Verify this works for when code is running or not
* Verify corner cases (e.g. files do not exist, one path instead of two, etc)
* Verify our rules for picking windows are respected (`-r` to force reuse a window is respected)

**Comment by felixfbecker** [comment]
That is pretty cool.

**Comment by bgse** [comment]
:+1: 

For your convenience, there is an issue open on this: https://github.com/Microsoft/vscode/issues/1768

**Comment by bpasero** [comment]
Nice, I knew we had duplicates on this :)
