### ISSUE TITLE
Allow additional fuzzy search within files found via CTRL+P

### ISSUE THREAD

**Issue by smuuf** [Microsoft/vscode#39542]
- VSCode Version: 1.18.1
- Feature request

How about **allowing users to fine-tune their fuzzy searching within a project/workspace?** This could be done by treating the `:` character *(which AFAIK is not an allowed character in Windows and Unix filenames)* as a separator.

Format: `<fuzzy matching file paths>:<fuzzy matching text inside found files>`
Examples/use cases:
- `function:getnode` - Find files with path *fuzzy-matching* the string `function` that also contain lines that *fuzzy-match* string `getnode`.
- `controller:action` - Same logic. Could be used for example to trivially find all `controller`s that define at least one `action` *(yes, possibly with some false positives*).

# Example

### Current behaviour
1. `ctrl+p`, enter `function`
2. Search would find these files: ![image](https://user-images.githubusercontent.com/6860713/33548244-e2a776e2-d8e6-11e7-9c8a-901b8e804f81.png)

### Proposed behaviour
1. `ctrl+p`, enter `function:getnode`
2. Seach would return these files: ![image](https://user-images.githubusercontent.com/6860713/33549134-cafc0f28-d8e9-11e7-91e7-2d13af1858ee.png)

And would find only these two files, because contents of the files ...

- `...\nikic\php-parser\lib\PhpParser\Builder\Function_.php`
- `...\nikic\php-parser\lib\PhpParser\Node\Stmt\Function_.php`

... match `getnode` *"fuzzily"*:
1. First one contains a line with "**get**Sub**Node**Names" and
2. Second file contains just "**getNode**"

**Comment by smuuf** [comment]
Maybe it would be better for the separator to be `#`, as that's what *Sublime Text* uses for the same functionality, AFAIK.

**Comment by brandondrew** [comment]
I don't know ultimately whether `:` is better or `#` is better, but I definitely find `:` *much* easier to type, and I don't think that compatibility with Sublime is important.  The key could be configurable for those users who care about consistency with Sublime, but the default should be chosen to:

1. not conflict with characters that will be needed as part of a file name
2. be convenient and easy to type

with criteria number 1 being far more important.

**Comment by smuuf** [comment]
My favourite choice would be the `:` character, too.

**Comment by syntaxseed** [comment]
This would be great. An awesome feature that exists in SublimeText.

**Comment by roblourens** [comment]
Sublime has this feature? I can't get it to work

**Comment by roblourens** [comment]
Never mind, I do see it with `#`
