### ISSUE TITLE
settings.json --> no highlighting of matched words in the scrollbar area

### ISSUE THREAD

**Issue by user3323** [microsoft/vscode#39543]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

For example, I'm trying to look for word "terminal" in my settings, to organize options that belong to terminal. But there is no highlighting of found word in the scrollbar area:

![image](https://user-images.githubusercontent.com/24613274/33550302-1179d190-d8f6-11e7-9f61-669d401ca2f7.png)

**Comment by hyperion0201** [comment]
seem this feature only works in editor-mode.

**Comment by alexandrudima** [comment]
@sandy081 when adding decorations, you can use `overviewRuler` to render them also in the scrollbar.

**Comment by user3323** [comment]
@sandy081  hello.

Any progress?

**Comment by sandy081** [comment]
@user3323 Not planned yet.

Happy to take PR if interested.
