### ISSUE TITLE
Sometime I get a wired error message when running --status under Windows

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#39557]
When running --status under Windows I sometime gets a wired error message like this:

![capture](https://user-images.githubusercontent.com/1931590/33559576-8e476824-d90d-11e7-8309-81dfc8784567.png)

@bpasero do you have any clue why this is happening

**Comment by dbaeumer** [comment]
Seems to be a timing issue. When I create less sample for the CPU profile (which takes then less time) this doesn't happen.

**Comment by bpasero** [comment]
I added a check to not show this dialog when `--status` is used. But it would still be interesting why it takes more than 10 seconds for the other side to respond.
