### ISSUE TITLE
code formatter ads space before decorators on constructor/methods

### ISSUE THREAD

**Issue by x1c0** [Microsoft/vscode#39554]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1

Hello, this is a very silly question, I searched and could not find a similar issue.

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/2421483/33557704-4041fb62-d908-11e7-8103-bd0c75377343.png)

Format the file

![image](https://user-images.githubusercontent.com/2421483/33557756-6395c68e-d908-11e7-8b85-d42168d07920.png)

This space this added before the decorator, and that does not happen with a normal argument. 

There is any setting to disable this? Thank you

**Comment by mjbvz** [comment]
Thanks! Opened https://github.com/Microsoft/TypeScript/issues/20449 to track this upstream
