### ISSUE TITLE
The ESLint extension would like to know whether a file open in the editor has a BOM

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#39558]
For the discussion see here: https://github.com/Microsoft/vscode-eslint/issues/356

A user has enabled BOM checking but the editor content does not contain the BOM which is correct. Since we validate the file in memory it looks like ESLint checks the BOM even in memory and errors about it. To handle this correctly we would need to know whether a file has a BOM or not.

**Comment by jrieken** [comment]
related to #5735 (which won't happen anytime soon) which is about the actual bytes of a document...

**Comment by dbaeumer** [comment]
OK for me. I have only one user complaining about it in ESLint right now.

**Comment by jrieken** [comment]
closing as dupe and re-opening the other
