### ISSUE TITLE
[JavaScript] highlighting in Template literals broke with 10.10 update

### ISSUE THREAD

**Issue by ElfenLiedGH** [Microsoft/vscode#3955]
![1](https://cloud.githubusercontent.com/assets/9973357/13668452/f82414c4-e6cd-11e5-99a7-3eb94704769f.png)

exmp:

it's working 
`var varww
var ww = `Неккорректное внешнее присоединение '${связь.запрос}' в ${this.constructor.name}`;
testProp = AAA;`
![1](https://cloud.githubusercontent.com/assets/9973357/13668526/4e8fcd6c-e6ce-11e5-8fc9-8ff3d5892098.png)

it's not working
var varww
varww = `Неккорректное внешнее присоединение '${связь.запрос}' в ${this.constructor.name}`;
testProp = AAA;
![1](https://cloud.githubusercontent.com/assets/9973357/13668541/65b18b0c-e6ce-11e5-9a30-e7db179b56a6.png)

only number or cyrilic braking only template
![1](https://cloud.githubusercontent.com/assets/9973357/13668573/b2045ca0-e6ce-11e5-9473-3584dccf1e70.png)

it's like that keyword+varibale = brake

**Comment by aeschli** [comment]
This problem was https://github.com/Microsoft/TypeScript-TmLanguage/issues/84 which is now fixed and will be fixed in the March release.
