### ISSUE TITLE
Invoke-Web-Request with piped vscode: No control is given back until file's closed

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#39555]
- VSCode Version: Code - Insiders 1.19.0-insider (8a12b294de610aab61c32c02c7c148d981cf07e4, 2017-12-04T05:14:19.063Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.0.3
markdown-emoji|bie|0.0.7
vscode-remind-me|cg-|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.1.0
gitignore|cod|0.5.0
compulim-vscode-closetag|Com|1.1.0
gitlens|eam|6.3.0
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
composer|ika|0.7.1
smarty|imp|0.2.0
vscode-apache|mrm|1.1.1
php-docblocker|nei|1.3.2
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.18.1
code-settings-sync|Sha|2.8.6
lorem-ipsum|Tyr|1.1.0
vscode-todo-highlight|way|0.5.11
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open internal terminal
2. Enter `iwr http://getcomposer.org/installer | code-insiders`
3. See, that the file is being opened.
4. You can't prompt new commands until the file is closed.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/39682
