### ISSUE TITLE
Bug on launch

### ISSUE THREAD

**Issue by HallEffect** [Microsoft/vscode#39551]
Today I got the next message
![image](https://user-images.githubusercontent.com/4431592/33557242-c9fd0766-d917-11e7-8563-e61182954aa4.png)

**Comment by isidorn** [comment]
@HallEffect can you reproduce this issue every time you run vscode?
Please give us more details. Can you also reproduce with vscode insiders
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
