### ISSUE TITLE
Add keybindings to move up and down across frames in debug call stack

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#39560]
- VSCode Version: Version 1.19.0-insider (1.19.0-insider)
- OS Version: macOS 10.13

I do not see any way to move between frames of the debug call stack with key bindings. This would be very useful complement to the existing keybindings for stepping forward, in and out.

Thank you!

**Comment by isidorn** [comment]
F1 > focus call stack > up / down arrows will tkae you through the call stack
You can also bind a custom keybidning to the focus call stack action

**Comment by gwk** [comment]
@isidorn thanks. I was able to accomplish what I want with the macro extension:

```
  "macros": {
    "callStackUp": [
      "workbench.debug.action.focusCallStackView",
      "list.focusUp",
      "list.select"],
    "callStackDown": [
      "workbench.debug.action.focusCallStackView",
      "list.focusDown",
      "list.select"]
}
```
