### ISSUE TITLE
Windows: code --status PS script should be signed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39566]
Otherwise you end up with this error:

![image](https://user-images.githubusercontent.com/900690/33563599-b2dcaafe-d918-11e7-94ec-795afaf6959a.png)

/cc @joaomoreno

**Comment by bpasero** [comment]
To clarify, after the following command I could run the script:

`Set-ExecutionPolicy -Scope CurrentUser RemoteSigned`

And before that my policy was:

![image](https://user-images.githubusercontent.com/900690/33563725-fc27d242-d918-11e7-962e-51c4e82659d1.png)

**Comment by joaomoreno** [comment]
I don't think signing it will help. [The default execution policy level is `Restricted`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-5.1#required-parameters). Nothing gets run in that level.

**Comment by dbaeumer** [comment]
I found a way to make it run even if it is not signed and execution policy is restricted :-)
