### ISSUE TITLE
Make sure extension don't accidentally run in 'debug'-mode

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39569]
re #39568

With the extension runtime we make the extension host always run with `inspect`. Some extensions take that as a (false) signal that they should also run in debug mode. We should make sure that doesn't happen

**Comment by jrieken** [comment]
@dbaeumer please verify

**Comment by dbaeumer** [comment]
Verified that the ESLint server is started in non debug mode if no debug is requested.
<img width="468" alt="capture" src="https://user-images.githubusercontent.com/1931590/33710486-022352dc-db41-11e7-8856-9c2c904fab5b.png">
