### ISSUE TITLE
(Out of Dev) Dialog is not shown while uninstalling an extension

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39561]
To reproduce

- Enable extensions gallery in dev
- Install an extension and reload
- Uninstall the extension. 

No dialog is shown.

**Comment by sandy081** [comment]
@bpasero Anything to do with the work you did for dialogs?

**Comment by bpasero** [comment]
@sandy081 I am seeing this dialog:

![before](https://user-images.githubusercontent.com/900690/33566388-1fdfb860-d920-11e7-8939-096c4f777fad.gif)

**Comment by sandy081** [comment]
It is working for me in latest insiders. Could be some local issue.
