### ISSUE TITLE
vscode - tasks do not start

### ISSUE THREAD

**Issue by teom10** [Microsoft/vscode#39567]
We have a set of tasks, but in windows is not working fine. These tasks run fast and fine in macOs sierra.
When I run a simple tasks (just run npm install) many times never start, so I terminated that task through the menu task, but the task still running.

**package.json**
``` js
{
  "scripts": {
    "start-auto": "webpack-dev-server --config webpack.dev.js",
    "startw-auto": "node server/app.js",
    "build-dev": "webpack --config webpack.dev.js"
   }
}
```

**tasks.json**
```
{
  "version": "2.0.0",
  "tasks": [{
      "label": "Install",
      "identifier": "InstallDependencies",
      "type": "shell",
      "command": "npm install",
      "options": {
        "cwd": "${workspaceRoot}"
      },
      "problemMatcher": []
    },
    {
      "label": "Build",
      "identifier": "BuildWithWebPack",
      "command": "npm",
      "type": "shell",
      "options": {
        "cwd": "${workspaceRoot}"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": [],
      "args": [
        "run",
        "build-dev"
      ]
    },
    {
      "label": "Server",
      "command": "npm",
      "type": "shell",
      "identifier": "RunNodeServer",
      "options": {
        "env": {
          "ENVIRONMENT": "dev"
        }
      },
      "problemMatcher": [],
      "presentation": {
        "panel": "new"
      },
      "args": [
        "run",
        "startw-auto"
      ]
    }
  ]
}
```

---

Steps to Reproduce:

1. Run "Install" task.
2. vs code open a new console to run this task.
3. If the task not start, go to menu Task -> Terminate Task.
4. The console is closed.
5. Go to menu Task -> Show Running Task
6. The task "Install" appears in the list.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.3.0
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.20
vsc-material-theme|Equ|1.1.2
file-icons|fil|1.0.7
sass-lint|gle|1.0.0
beautify|Hoo|1.1.1
csharpextensions|jch|1.3.0
Angular2|joh|2.11.2
docomment|k--|0.0.17
vscode-mocha-sidebar|mat|0.14.6
HTMLHint|mka|0.4.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vscode-docker|Pet|0.0.22
material-icon-theme|PKi|3.1.0
node-tdd|pra|0.2.4
sass-indented|rob|1.4.5
npm-link-status|rob|0.0.3
vscode-sass-format|sas|1.1.2
bunker|sld|1.1.6
ayu|tea|0.10.0

**Comment by dbaeumer** [comment]
This works for me in a simple setup. @teom10 can you please provide a GitHub repository I can clone that demos the problem with steps to reproduce.

Does the problem exist if you run with all extensions disabled (e.g. `--disabled-extensions`)

**Comment by teom10** [comment]
I tried without extensions and It still occurs.

Sometimes the issue happens after I run the tasks a few times. For example, I run the following tasks "Install" then "Build", then "Start", the error occurs.

Currently the code it´s on a private repository, I will try to replicate in a clean environment (new repo) and will share it with you..

**Comment by dbaeumer** [comment]
Thanks
