### ISSUE TITLE
Improve keybinding documentation

### ISSUE THREAD

**Issue by gwk** [Microsoft/vscode#39562]
- VSCode Version: Version 1.19.0-insider (1.19.0-insider)
- OS Version: macOS 10.13

First let me say that the VSCode team is doing a fabulous job on the whole, andI moved to VSCode from Sublime Text specifically because the documentation on task configuration was superior.

However, I still find myself wasting a lot of time hunting around for the right configuration key for nearly every customization effort I make. The documentation is great for intro articles, but quite weak as reference material.

For example, take this article section: https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization

> The list above isn't exhaustive and you may see some when contexts for specific VS Code UI in the Default Keyboard Shortcuts.

What this means in practice is that if I want to use a "when context" I have to pour over 1000+ lines of Json. I just spent the better part of an hour discovering `inDebugRepl`. In fact I resorted to writing a script to extract all of the defaults and contexts and format them out as a quick reference. This was not very hard, and I think it would be well worth it if VSCode started publishing generated reference material like this. Then the article could just link to a complete list that was up to date. I suspect there are other areas that would also benefit greatly from more autogenerated docs as well.

Thanks for taking the time to consider this!

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1288

**Comment by gregvanl** [comment]
There is also https://github.com/Microsoft/vscode/issues/9303 to provide when clause context IntelliSense in keybindings.json.
