### ISSUE TITLE
[C#] Syntax highlighting issue

### ISSUE THREAD

**Issue by achardes** [Microsoft/vscode#3956]
Hi,

It seems there is an issue with the syntax highlighting, see the below capture:

<img width="1027" alt="screen shot 2016-03-10 at 13 49 49" src="https://cloud.githubusercontent.com/assets/10247912/13669930/0a7fc296-e6c7-11e5-9e0f-658efc2f753e.png">
All the code below this method keep this color.

Perhaps this is a duplicate, in this case, sorry for the noise. 
(I found the same kind of issues but not for C#...)

Vs code version: 0.10.10 (0.10.10)

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#89
