### ISSUE TITLE
The typescript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by tferullo** [Microsoft/vscode#39563]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.1.0
vscode-eslint|dba|1.4.3
prettier-vscode|esb|0.26.0
bem-expand|luk|0.1.4
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1

(7 theme extensions excluded)

---
I have large files and directories ignored using `files.watcherExclude`

Reproduces without extensions: Yes

I know this bug has been reported many times. I've been experiencing this bug anytime i try to use vs code and  I recently switched `files.useExperimentalFileWatcher` to true. That was working fine for a few days up until a couple minutes ago.

**Then i noticed something that I'm hoping might help**:
I pressed return to start a new line, I didn't immediately type, after about 5ish seconds the new line deleted itself, then the cpu usage for Code Helper sky rocketed from about 0.3% to 130% about a minute later I got the typescript error.

this seemed to be the first error that kicked it off in my tslog:
```
[Info  - 11:01:16] Started TSServer
[Info  - 11:02:08] TSServer exited
[Info  - 11:02:08] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-K1ujp2/tsserver.log
[Info  - 11:02:08] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:02:08] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-zfxAib/tsserver.log
[Info  - 11:02:08] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Error  - 11:02:08] 'getApplicableRefactors' request failed with error.
Error: Service died.
```

since then it keeps failing with:
```
[Info  - 11:16:55] Started TSServer
[Info  - 11:17:45] TSServer exited
[Info  - 11:17:45] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-sqzNNl/tsserver.log
[Info  - 11:17:45] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:17:45] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-JgjwIV/tsserver.log
[Info  - 11:17:45] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Info  - 11:17:45] Started TSServer
[Info  - 11:18:32] TSServer exited
[Info  - 11:18:32] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-JgjwIV/tsserver.log
[Info  - 11:18:32] Using tsserver from: /private/var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/AppTranslocation/33554DC8-C7F0-49E9-979D-CC7B49080467/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 11:18:32] TSServer log file: /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tsserver-log-DzloKx/tsserver.log
[Info  - 11:18:32] Forking TSServer
PATH: /usr/local/opt/openvpn/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[Info  - 11:18:32] Started TSServer
```

seems to be restarting itself in some sort of infinite loop.

Hope this provides some insight.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20446
