### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets not adding space before closing bracket.

### ISSUE THREAD

**Issue by charlieprynn** [Microsoft/vscode#39571]
- VSCode Version: 1.18.1
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Set `javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets` to `true`
2. Auto indent `[{ name: 'Main' }]`
3. It becomes `[ { name: 'Main' }]` instead of `[ { name: 'Main' } ]`

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20456
