### ISSUE TITLE
Bug: can't drag and drop files on VSCode icon to open directly inside it.

### ISSUE THREAD

**Issue by adel-bassiony** [Microsoft/vscode#39575]
- VSCode Version: Version 1.19.0-insider (1.19.0-insider)
- OS Version: MacOS HighSierra 10.13.1

Steps to Reproduce:

Please fix it.. i can't drag and drop files to open directly in VScode like before.
now i must to open the VScode window and drag and drop the file in the app window :/ 

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
We fixed this meanwhile, should be OK tomorrow 👍
