### ISSUE TITLE
Collapse code block ignore comments inside this block

### ISSUE THREAD

**Issue by Ciget** [Microsoft/vscode#3957]
Hi guys,

In 0.10.10 collapse of block of code does not works well with comments. I attach images that explain in details how to reproduce this issue. So, you need to write any block of code that you can collapse with comments inside:

![expand](https://cloud.githubusercontent.com/assets/2539541/13671183/1501b962-e6d7-11e5-8014-04b2172fd0db.png)

Then collapse this block, and you will see that comments still present. But ideally, we need to collapse these comments with codes in this block:
![collapse](https://cloud.githubusercontent.com/assets/2539541/13671230/59ee17dc-e6d7-11e5-9d95-ef36948fc491.png)

Thanks.

**Comment by aeschli** [comment]
We currently only look at the indentation of a line to determine the folding regions.
As the comments in this example all start on the first line, they are not counted to any region that starts earlier.
To implement your request we need to add more language knowledge to the folding regions. We have issue https://github.com/Microsoft/vscode/issues/3422 for this
