### ISSUE TITLE
Log Service: in renderer should also log via console.log

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39577]
That allows us to use the log service as drop-in replacement for console.log/warning/error.

**Comment by joaomoreno** [comment]
@bpasero Went ahead and implemented it.

**Comment by bpasero** [comment]
@joaomoreno cool! A bit odd that we now show this on every reload though:

![image](https://user-images.githubusercontent.com/900690/33706550-c60d20ea-db34-11e7-9e3e-9a2b8ad79449.png)

**Comment by joaomoreno** [comment]
We can remove!

**Comment by bpasero** [comment]
Done

**Comment by joaomoreno** [comment]
Actually, not great, since it means the log file is empty by default which looks broken. Let's leave something smart in there. Like `workbench started in 100ms`.
