### ISSUE TITLE
Inconsistent autoimport vs ctrl+. import suggestions.

### ISSUE THREAD

**Issue by OlekNg** [Microsoft/vscode#39573]
- VSCode Version: 1.18.1
- OS Version: Win10

Steps to Reproduce:

1. ng new someApp
2. In AppComponent start typing `@Input`

VSCode suggests import from `@angular/core/src/metadata/directives` (which is the wrong one btw):
![autoimport-wrong](https://user-images.githubusercontent.com/785741/33566066-3648f8f6-d91f-11e7-9b52-c90871454b05.png)

Instead you can try to add import through `ctrl+.` which suggests different import `@angular/core` (correct one btw):
![import-good](https://user-images.githubusercontent.com/785741/33566075-3c1eccec-d91f-11e7-85b9-3c3358acdde1.png)

Expected behaviour:
In both cases there should be same suggestion `@angular/core`

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you please try this in VS Code insiders and let me know if you still see this issue

**Comment by OlekNg** [comment]
Using insiders version the problem still occurs (i'm getting exactly same results like screens from first post)

**Comment by prussian-blue** [comment]
Same happening here :(

**Comment by mjbvz** [comment]
Yes, this is https://github.com/Microsoft/TypeScript/issues/19888 

This should be fixed in `typescript@next`. You can try this out by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions
