### ISSUE TITLE
Extra tabstop on VSCode snippet

### ISSUE THREAD

**Issue by dfee** [Microsoft/vscode#39579]
- VSCode Version: Version 1.19.0-insider (1.19.0-insider)
- OS Version: MacOS 10.13 (17A365)

Steps to Reproduce:

1. Add a user-defined snippet as such:
```json
"pylint": {
    "prefix": "pylint",
    "body": "# pylint: ${1|disable,enable|}=${2|R0102\\, simplifiable-if-statement,R0101\\,too-many-nested-blocks|}",
    "description": "Add a pylint comment"
},
```
2. For some reason it stops on [`disable`, `enable`], then on `=` ?!, and then again (appropriately) on [`R0102, simplifiable-if-statement`, `R0101, too-many-nested-blocks`].

Why is it stopping on the equals sign? I believe this is a bug.

Etc: *[EBNF for snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar)*

**Comment by jrieken** [comment]
@dfee Not sure what you mean. You have two choice elements, select them with tab

**Comment by dfee** [comment]
@jrieken I put the snippet in there so that you could add it to your snippet file and reproduce it. That is a snippet for `python`, but I'm not sure that's a relevant detail.

I assume you've not comprehended the second point?

> For some reason it stops on [`disable`, `enable`], then on `=` ?!, and then again (appropriately) on [`R0102, simplifiable-if-statement`, `R0101, too-many-nested-blocks`].

![demo](https://user-images.githubusercontent.com/262602/33624293-c60ff58c-d9a8-11e7-898c-dd1ef2bd5818.gif)

You'll see a tabstop after `enable` on `=`, but that shouldn't be there.

**Comment by jrieken** [comment]
>  but that shouldn't be there.

Why not? The snippet reads `${2...`, so yeah there is a second tabstop defined

**Comment by dfee** [comment]
The `${2...` is after the equal sign. Not before. Again, why is there a tab stop immediately before the equal sign?!

**Comment by jrieken** [comment]
Choice elements are treated as regular (nested) snippets and we always jump to the end of snippet when it's "finished". That's why the cursor stops there. Unlikely that we will change this behaviour. Closing as designed

**Comment by dfee** [comment]
Interesting. I just tested it with this snippet:
```json
	"dummy": {
		"prefix": "dummy",
		"body": "# dummy: ${1|this,that|} - ${2|is,was|} - ${3|good,bad|}",
		"description": "a dummy snippet",
	},
```
and it indeed appears that tabstops stop before **and after** choice elements.
