### ISSUE TITLE
Proxy configuration object on extension host to avoid cloning

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39576]
From @jrieken [comment](https://github.com/Microsoft/vscode/issues/39329#issuecomment-348230104)

Nothing that I have tried but I believe you can hand out a proxy object (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) of the actual underlying configuration object (the truth) which simply forwards read requests and which copies the object when a modification happens

**Comment by jrieken** [comment]
@sandy081 This should not be on the backlog. From #39329 you can see how seconds are wasted by extensions using the slow implementation.
