### ISSUE TITLE
Test macOS Global Find Clipboard

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#39585]
Re https://github.com/Microsoft/vscode/pull/35956 

Complexity 2:

* [x] macOS @weinand 
* [x] macOS @alexandrudima

When you use cmd+g to launch Find Widget, the search query will be populated automatically and the search query is from global find clipboard. A simple workflow can be

* Search something in your browser
* Cmd+g in VSCode

**Comment by wprater** [comment]
> Search something in your browser
> Cmd+g in VSCode

is this not how it's supposed to work?  at least Id expect it to on macOS.  try the same points, but after the second point, try opening a find inout in Terminal or Safari.
