### ISSUE TITLE
Test: Extension repository link

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39584]
Tests https://github.com/Microsoft/vscode/issues/27331

- [x] @RMacfarlane 
- [x] @kieferrm 

Complexity 1

Make sure extensions which have an associated repository in the Marketplace show the `Repository` link in the extension _editor_: https://github.com/Microsoft/vscode/pull/31487

**Comment by kieferrm** [comment]
Covered Mac and Windows.
