### ISSUE TITLE
Feature Request: Extensions Manifest

### ISSUE THREAD

**Issue by jbalbes** [Microsoft/vscode#39581]
When working on a project with others or across multiple machines, it is annoying to have to track extensions for each computer and keep them in sync. For example, if I am using TS Lint in my project, I want to make sure that the TS Lint extension is installed for all developers that clone the project. If I'm using Angular, I'll want the Angular Language Service, etc.

Please add an option in .vscode/settings.json or similar to list VS Code extensions that are recommended to be used with a project, and create an 'Install all recommended extensions' button.

**Comment by sandy081** [comment]
There is a workspace recommendations feature that will allow you to configure recommendations for your project which can be shared.

- Open Extensions View
- Select `Show Recommended Extensions` action from `...` menu
- This shows `Workspace Recommendations` which can be configured

**Comment by jbalbes** [comment]
Thanks!
