### ISSUE TITLE
Electron debugging doesn't work anymore since the new update

### ISSUE THREAD

**Issue by MbProg** [Microsoft/vscode#39589]
Today I have run the new update of visual studio code and since then the debugger of electron does not work any more and get the same error message I got before installing Version 1.17. Version 1.17 solved that issue but now 1.18 brought it again. It is a disaster!! Can't I downgrade my version of visual studio code?

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.0.12
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by auchenberg** [comment]
@MbProg How does your `launch.json` config look and what Electron version are you trying to target?

You seen our Electron debugging recipe? https://github.com/Microsoft/vscode-recipes/tree/master/Electron

**Comment by MbProg** [comment]
Thanks for the quick answer. I am using exactly the same launch.json that is used in the link you sent.
Now I am getting the following error message: 
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:48793).

**Comment by weinand** [comment]
What version of Electron are you using?
And please see https://github.com/Microsoft/vscode/issues/30105

**Comment by MbProg** [comment]
Thanks. Now it works. I had to change the launch.json which was in the link and set the "protocol" attribute to "legacy" instead of "inspector" as described in this [thread](https://github.com/Microsoft/vscode/issues/26411).
But thanks. Now it is working.

**Comment by auchenberg** [comment]
Glad to you it working, and thanks for opening an issue.
