### ISSUE TITLE
VSCode intelligent not work whitout require with node modules

### ISSUE THREAD

**Issue by MadSummer** [Microsoft/vscode#39598]
- VSCode Version: VSCode Insiders 1.19.0
- OS Version: Win10

Steps to Reproduce:

**intelligent work:**
1. code in a.js
![tim 20171205094318](https://user-images.githubusercontent.com/15519586/33586361-06bdd018-d9a4-11e7-8651-58a76a4829ac.png)
2.code in b.js , intelligent  work 
![tim 20171205094309](https://user-images.githubusercontent.com/15519586/33586383-218280f6-d9a4-11e7-8f0c-1d89452619f1.png)

**intelligent not work:**
1. code in a.js
![tim 20171205094459](https://user-images.githubusercontent.com/15519586/33586397-2fec0ea0-d9a4-11e7-986d-1a209d1296eb.png)
2. code in b.js (intelligent is not working)
![tim 20171205094513](https://user-images.githubusercontent.com/15519586/33586470-83b37dca-d9a4-11e7-9a9c-7b3697cd6bbe.png)

**intelligent work if require the module:**
5. code in b.js whit require , intelligent  working well
![tim 20171205094610](https://user-images.githubusercontent.com/15519586/33586497-94299900-d9a4-11e7-9e04-ee97fb9b7406.png)

**Comment by mjbvz** [comment]
This is by-design. Once you use `module.exports` in a file, that file becomes a module and it will no longer export global symbols

**Comment by MadSummer** [comment]
@mjbvz thinks for your answer. 
But sometimes i just only want use @param to indicate the param is an instance of any class,so i can use intelligent. At now, i need import the module to resolve it and remove the improt code if all work done.
Can this be a feature-request ? 
Thank you!
