### ISSUE TITLE
Problems with nested snippet insertion

### ISSUE THREAD

**Issue by tnrich** [Microsoft/vscode#39594]
I couldn't leave a comment on any of the many issues that seemingly address this error: 

https://github.com/Microsoft/vscode/issues/26907

https://github.com/Microsoft/vscode/issues/27015

https://github.com/Microsoft/vscode/issues/26915

https://github.com/Microsoft/vscode/issues/27015

because they were all locked. I am still definitely hitting this error and am on the latest possible stable vscode version: 
![image](https://user-images.githubusercontent.com/2730609/33581307-44e1ee8c-d905-11e7-9827-cfad9e4136c8.png)

Here is a screenshot of the issue popping up: 

![image](https://user-images.githubusercontent.com/2730609/33581345-671c9ad8-d905-11e7-984c-d7b024deda77.png)

I'm not sure what causes the error to start occurring, but once it starts, every time I try to tab complete anything I get this annoying message and the cursor position gets off in a funky way such that I can't use my regular snippets.

**Comment by ramya-rao-a** [comment]
Can you open the console (Help -> Toggle Developer Tools -> Console) and share any error messages there with call stacks?

**Comment by tnrich** [comment]
I will once I'm able to reproduce it. I restarted so it might be a little bit before the error starts up again.

**Comment by Braincompiler** [comment]
I'm getting this error with a custom code snippet (elm.json, for elm language in this case):
```json
"Function definition w/ 2 arguments": {
	"prefix": "fn2",
	"body": [
		"$1 : $2 -> $3 -> $4",
		"$1 $5 $6 =",
		"    $0"
	],
	"description": "Function definition w/ 2 arguments"
},
```

while this is working:
```
"Function definition w/ 1 arguments": {
	"prefix": "fn1",
	"body": [
		"$1 : $2 -> $3",
		"$1 $4 =",
		"    $0"
	],
	"description": "Function definition w/ 1 arguments"
},
```

The developer tools:
![image](https://user-images.githubusercontent.com/142524/33634039-151056e4-da13-11e7-9c40-c4f30be91bef.png)

**Comment by jrieken** [comment]
Exciting... I have been getting this via error telemetry since a long time but was never able to reproduce.

**Comment by jrieken** [comment]
Not exciting... @Braincompiler I jump on your snippet but it seems that you are taking this issue hostage as it unrelated to the invalid argument issue mentioned before. Still, please try to prodive *reproducible* steps. Just inserting the snippet doesn't do it, sadly...

**Comment by jrieken** [comment]
@tnrich I am sorry but we do need steps for this... Also, don't believe that all illegal-argument errors have the same cause. It's a general we use and it can occur in different places and be triggered in different ways

**Comment by james-woodbridge** [comment]
I am getting the same issue when simply trying to tab indent at the beginning of an empty Powershell function definition. The error messages is:

```
Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011239
    at t._changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951992)
    at t.changeDecorations (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:951213)
    at e.move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1011003)
    at e._move (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1017225)
    at e.next (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1017013)
    at e.next (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1423074)
    at n.handler [as _callback] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1423601)
    at n.t.bindToContribution.n.runEditorCommand (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1292448)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9:1292838
```

Screenshot of the file in question attached

![image](https://user-images.githubusercontent.com/7914837/33666505-15ce5d0e-da92-11e7-9703-5661b133a1c9.png)

**Comment by james-woodbridge** [comment]
@jrieken why was my comment deleted?

**Comment by jrieken** [comment]
Because you are taking this issue as hostage. There is roughly 20 different places the code that can trigger this error. @tnrich Has not yet provided reproducible steps nor a stack trace which means it's no clear how and when this happens. So I wonder what data points make you believe that you encounter this exact same issue? Why are you so sure it's not a different issue? Last, why do you think saying me too, also without reproducible steps, if of any help?

**Comment by james-woodbridge** [comment]
@jrieken I find your tone and response to be overly aggressive and dramatic, and not a good way to carry out user support. My issue also occurred whilst using tab to autocomplete things, hence why I commented and although I didnot include reproducible steps, I did include error information and a screenshot. 'Taking hostage' is a gross exaggeration, I did not deman a solution, I simply contirbuted extra information.

Perhaps, instead of just deleting the comment without comment, you could have asked me for further information, and thus sped up the resolution of an open issue?

**Comment by jrieken** [comment]
> Perhaps, instead of just deleting the comment without comment, you could have asked me for further information, 

Yes, you are right. Deleting the comment wasn't the nice thing to do and I am sorry for that. To explain my self (not to justify): When you get lots of issues every day you'll develop an allergy towards missing information. 

Again, please file a new issue. It doesn't cost much. When an error occurs try to remember what you just did and then try to reproduce. That's the most valuable thing to do. Thanks

**Comment by jrieken** [comment]
> every time I try to tab complete anything 

@tnrich Please clarify you understanding "tab complete". Is this

1. the suggestion widget shows and you hit tab to select an item?
2. you have enabled tab-completion (`"editor.tabCompletion": true,`), typed the prefix of a snippet, and you have hit tab?
3. you have enabled emmet-tab-expansion (`"emmet.triggerExpansionOnTab": true,`) and the error occurs
4. none of the above

**Comment by james-woodbridge** [comment]
> Again, please file a new issue. It doesn't cost much. When an error occurs try to remember what you just did and then try to reproduce. That's the most valuable thing to do. Thanks
@jrieken I understand, I handle support for clients too and deal with missing information daily. I have opened a separate issue. I will leave this thread now. Good luck narrowing down the problem :)

**Comment by tnrich** [comment]
Okay, it started happening again. Not sure what caused it to start still. Here is the stack trace @ramya-rao-a 

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1011239
    at t._changeDecorations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:951992)
    at t.changeDecorations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:951213)
    at e.move (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1011003)
    at e._move (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1017225)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1016877
    at e.pushEditOperation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:426645)
    at t._pushEditOperations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:963461)
    at t.pushEditOperations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:962458)
    at e.merge (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9:1016691)
```

**Comment by jrieken** [comment]
@tnrich Interesting and I'd really like to know the steps leading up to that but this isn't the 'Illegal Arguments' error you have mentioned in the beginning. Is it that this error happens and that it also shows the error message in the UI?

**Comment by jrieken** [comment]
Drilling into this black hole... There is something off with nested snippets. I can tell that by the stack traces and I have seen this via error telemetry. It's just not clear to me how exactly that happens 😕 

The 'Invalid arguments' error is, I believe, a side-effect of that. The snippet-logic wants to compute the next cursor positions, fails, and computes an empty array of selections. The editor will refuse to accept that and throw that error... (there are many other code paths leading to this but I take this as the most likely case).

**Comment by jrieken** [comment]
This is related (likely the same) as #36330 and #36329

**Comment by jrieken** [comment]
I have pushed a change that prevents the 'in-your-face-error' and that adds lots of logging, esp. it will write the snippets and merge attempting to a log-file. That is information we cannot automatically collect as telemetry... @tnrich @Braincompiler This requires you help. When snippets, esp. snippets or IntelliSense inside another snippets, act weirdly check the error log (F1 > Show Logs... > Renderer) for line around `snippet_error`. Thanks

**Comment by james-woodbridge** [comment]
@jrieken I have noticed that my issue also occurs when using snippets - particulary one of my custom snippets? Would you like me to provide information here if I am able to reproduce, or would you prefer that I keep it to issue #1118 ?

**Comment by jrieken** [comment]
Sure this is #1118? 

Yeah, maybe yours is the same... Initially I was not aware that the bad snippet behaviour can cause the 'Invalid arguments' error to pop up. Because of that I mentally put things into different bugs. Separate issue or not doesn't matter much at this point. What I need is repro-steps... 

Is this plain snippets and completions or anything fancy like starting with multiple cursors?

**Comment by james-woodbridge** [comment]
My steps to easily reproduce are using the following custom snippet in powershell:

```
"Convert self to JSON":{
		"prefix": "Convert",
		"body": "$1 = ConvertTo-Json $1",
		"description": "One liner to convert a object into a JSON version of itself."
	},
```

As you can see it uses multiple cursors. Either this will cause the issue straight away, or the next time IntelliSense is used the issue occurs. If that enough info? If not I will happily try to get more, or bow out.

**Comment by jrieken** [comment]
@james-woodbridge I owe you a beer. I mean it, I am in London early next Feb.

I believe the culprit is changing the selection when inside a repeated placeholder and when invoking another snippets (nested insertion). Steps to reproduce this: 

* empty test.ps1 file
* insert snippet [from above](https://github.com/Microsoft/vscode/issues/39594#issuecomment-349944144)
* manually set selection (via mouse) to the end of that line
* insert that snippet again
* 💥

**Comment by jrieken** [comment]
Pushed a fix, will be in next insiders build. Tricky, crazy issue... The snippet controller tracks the current selection while a snippet is being inserted and cancels snippet mode when the selection leaves a placeholder range. That logic was flawed and wouldn't cancel snippet mode when the selection changes from n to 1 while still being on a placeholder (see above staying on `$1` but on just one of them). Subsequently, nested snippet insertion would explode because it relies on that behaviour...

**Comment by james-woodbridge** [comment]
@jrieken I will take you up on that beer - there are quite a few good pubs around here and it's always good to meet new people :)
Glad to hear you found the flawed logic around snippet mode,  I look forward to the next insider's build!
