### ISSUE TITLE
Source Control doesn't integrate with 2017 version of GitHub Desktop (unlike previous version).

### ISSUE THREAD

**Issue by Rafyelzz** [Microsoft/vscode#39590]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.6
html-css-class-completion|Zig|1.14.0
project-manager|ale|0.23.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-great-icons|emm|2.1.20
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
php-pack|fel|1.0.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vscode-css-peek|pra|2.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
What do you mean, "integrate with 2017 version of GitHub Desktop"? Please be very specific and include enough details for us to reproduce the issue.

**Comment by Rafyelzz** [comment]
Having GitHub desktop installed and Visual Studio Code, in the previous version, I’d have commands here (for which now I don’t):

[cid:329C7F6A-D501-42C2-BF05-94056DDC9DC1]

On the other hand, GitHub Desktop seems to recognise that Visual Studio Code is installed (just like in the previous version):

[cid:95135FDA-1994-4A0E-BD84-4570A70FE079]

I’m aware that the previous version is referred as “native” online the new one (link for reference https://github.com/desktop/desktop/issues/2885)

Thanks


On 4 Dec 2017, at 22:57, Rob Lourens <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you mean, "integrate with 2017 version of GitHub Desktop"? Please be very specific and include enough details for us to reproduce the issue.

**Comment by roblourens** [comment]
If you tried to attach screenshots, they didn't make it through, you'll have to upload them directly on this issue.

**Comment by Rafyelzz** [comment]
<img width="387" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/13495357/33579079-d4cf6a72-d948-11e7-8df9-42cd0d8bbb5c.png">
<img width="475" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/13495357/33579083-d6ea048e-d948-11e7-9bf4-d2193690f996.png">

**Comment by roblourens** [comment]
The only thing that matters on VS Code's end is whether there is a git repo in the open folder. Is there a `.git/` folder in your folder?

**Comment by Rafyelzz** [comment]
Yes, it does:


<img width="652" alt="screen shot 2017-12-05 at 8 08 36 am" src="https://user-images.githubusercontent.com/13495357/33594282-9e374322-d993-11e7-87f6-ca1ad5c2ca23.png">

**Comment by joaomoreno** [comment]
@Rafyelzz With this new version, you need to install the official Git release from https://git-scm.com/

More info: https://github.com/Microsoft/vscode/pull/35965
