### ISSUE TITLE
taskService.run promise should always complete

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3959]
Currently `taskService.run` returns a promise, but this promise does not always complete.
IMHO this promise should always complete with a `TaskSummary` as it would make the `taskService` API nicer and easier to program against.

**Comment by dbaeumer** [comment]
@isidorn: I agree the promise should always complete. Do you have steps in which it doesn't. Please be aware that it completes when the process running the task completes. So if you have a watching task it can take a long time until it does.

**Comment by isidorn** [comment]
@dbaeumer well my case is that I have a watching task. And the `run` promise never completes because the task is not terminating. I would still expect the promise to complete since I am calling `run`, the task has just been ran thus the promise should complete imho.
If you do not agree, then how should I get a task summary for a task just `run` with a never completing promise?

For repro steps:
1. Generate hello world extension
2. Put breakpoint in `debugService.ts:645`
3. Notice `Promise` never completes

**Comment by dbaeumer** [comment]
IMO this got addressed by firing corresponding events. Since tasks are external programs I can only complete the promise when the external program completed. @isidorn please ping if you think there is additional work I need to do.
