### ISSUE TITLE
`vscode.window.activeTextEditor` become undefined after issuing `workbench.action.nextEditor` command.

### ISSUE THREAD

**Issue by changsi-an** [Microsoft/vscode#39597]
- VSCode Version:1.18
- OS Version:16.04.1-Ubuntu 

Steps to Reproduce:

I have the following code:
```javascript

const switchHandler = vscode.window.onDidChangeActiveTextEditor((editor: vscode.TextEditor) => {
    lastActiveEditor = editor;
    // One-time handling.
    switchHandler.dispose();
    resolve(editor);
});

vscode.commands.executeCommand('workbench.action.nextEditor');
```

In the callback, the `editor` parameter becomes undefined. Also at the same time, the value of `vscode.window.activeTextEditor` is undefined too. I have at least two opened documents that I can switch between.

The same issue does not occur if I issue a `workbench.action.closeActiveEditor` command.

Reproduces without extensions: No opportunity to check, I am developing an extension.

**Comment by jrieken** [comment]
> In the callback, the editor parameter becomes undefined.

That's the designed behaviour. There is a time in which the editor is undefined, esp when switching

**Comment by changsi-an** [comment]
Can you explain why it is by design? On the UI, I can clearly see a new tab is switched to and activated. Why the activeTextEditor does not reflect that? It does not feel logical.

Otherwise how can I get the next editor that is switch to after I issue 'workbench.action.nextEditor' ?
