### ISSUE TITLE
Arrow function in object literal does not have function syntax color

### ISSUE THREAD

**Issue by cubeDhuang** [Microsoft/vscode#39592]
- VSCode Version: 1.18.1
- OS Version: Microsoft Windows 10

Steps to Reproduce:
1. Inside of an object literal, create an arrow function, like
```javascript
{
  someFunction: () => something()
};
```
2. someFunction should be colored as a function (yellow in dark+).

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#548

**Comment by mjbvz** [comment]
Looks like we special case this in our Light+/Dark+ grammar. However the other built-in grammars all colorize:

```js
({
	someFunction: () => something(),

	someFunction2() { something() }
});
```

the same way
