### ISSUE TITLE
Multiple problem matchers in tasks.json

### ISSUE THREAD

**Issue by sbrw** [Microsoft/vscode#39604]
Feature request redirected from the C/CPP extension project:
https://github.com/Microsoft/vscode-cpptools/issues/1286

**Original issue at cpptools:**
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

I find it unfortunate to mix intellisense/lint errors and build errors/warnings in the "Problems" tab. I might have multiple folder in a workspace, some with broken intellisense include paths and others without. I would  still want to build a project and only attend to the build specific compilation errors in the "Problems" tab. Not interleaving it with non build related errors and warnings. Perhaps grouping problems in a single Problems tab, displaying in separate tabs, attending to build issues by clicking on them in the build output...

Another feature would be to have multiple "problemMatcher" per task in tasks.json. I have for example a  two-stage compilation with unique output. First linting and then compiling, file by file. The linter and compiler have different output and need a specific problem matcher.

Alternatively a problem_matcher.json to define regex for the tools used, and match the build output against it.

**Comment by dbaeumer** [comment]
You can have n problem matchers per task. Simply provide an array instead of a single matcher. Does this work for you?

**Comment by sbrw** [comment]
Thanks! Seems to work. Great! My bad...

Still think mixing lint, intellisense, build errors and other problems in the same window get me distracted. Is there a way round that?

**Comment by dbaeumer** [comment]
No currently not. Feel free to file an issue requesting this. One idea would be to be able to apply filters.
