### ISSUE TITLE
[html] code completion for script types

### ISSUE THREAD

**Issue by Veid-Zhang** [Microsoft/vscode#39606]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
vscode-html-css|ecm|0.1.8
open-in-browser|tec|1.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.<script type="">
In the type tag
The code can not be automatically completed
For example, can not be automatically completed：text/javascript

Reproduces without extensions: Yes/No

**Comment by YanQi-Zhang** [comment]
<img width="672" alt="default" src="https://user-images.githubusercontent.com/33930171/33593465-8c0443f8-d9ca-11e7-8ca3-d518f6419090.PNG">
The code can not be automatically completed

**Comment by YanQi-Zhang** [comment]
？？？

**Comment by YanQi-Zhang** [comment]
<img width="532" alt="default" src="https://user-images.githubusercontent.com/33930171/33660905-97eca998-dac0-11e7-8c6d-b60e3a021b60.PNG">
Is not value option
var var1=document.getElementById('num1').value;

**Comment by YanQi-Zhang** [comment]
<div> Is not align  option
<img width="575" alt="default" src="https://user-images.githubusercontent.com/33930171/33713782-8f542942-db87-11e7-8e34-fc6ad89c06fb.PNG">
