### ISSUE TITLE
cygwin command failed in the console

### ISSUE THREAD

**Issue by jiaolu** [Microsoft/vscode#39600]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
python|ms-|0.8.0
cpptools|ms-|0.14.3
shader|sle|1.1.2

---

Steps to Reproduce:

1.in the integrated command console
2. use cygwin linux command ,like ls and tee
3. it will have exception like these
"16324 handle_exceptions: Exception: STATUS_ACCESS_VIOLATION
   1711 [main] ls 16324 open_stackdumpfile: Dumping stack trace to ls.exe.stackdump"

Exception: STATUS_ACCESS_VIOLATION at eip=74EB3880
eax=00000000 ebx=00001000 ecx=000002F8 edx=7FFB001C esi=0A739000 edi=0241E598
ebp=0241CB60 esp=0241CB18 program=C:\dk\dk\win\gnu\cw1.3.12\bin\ls.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0241CB60  74EB3880  (000004E4, 00000000, 0A7382F8, 00001000)
0241EBA0  61016F2F  (000001B5, 0241EBE8, 000004E4, 0A7382F8)
0241FC00  61019EF4  (61680F0C, 0A7382F8, 0A738337, 0A738000)
0241FC40  6101A46F  (61680F0C, 0A7382B0, 00000087, 00000001)
0241FCA0  61071896  (00000001, 0A7382B0, 00000087, 610705EB)
0241FCC0  610B0C86  (610BF030, 00000001, 0A7382B0, 00000087)
0241FCF0  610ACDBA  (610BF2F0, 0A7382B0, 00000087, 610BF2F0)
0241FD10  6109EB01  (610BF2F0, 0A734A60, 0A732628, 00405506)
0241FD30  6109D72B  (0000000A, 610BF2F0, 0241FDB0, 004056EC)
0241FD50  610A0512  (0000000A, 610BF2F0, 00000058, 00404598)
0241FDB0  00405723  (00000000, 0A7348E0, 00000058, 00404598)
0241FDD0  0040474E  (0A730400, 00000000, 00000001, 0040E1B2)
0241FE30  00403966  (0A730410, 00000000, 0241FE60, 0040171D)
0241FE60  004019C9  (00000001, 0A7303A0, 0A730278, 00000001)
0241FEC0  61005B8E  (610C29AC, FFFFFFFE, 000000DC, 610C28D0)
0241FF20  61005E2C  (00000000, 00000000, 00000000, 00000000)
End of stack trace (more stack frames may be present)

Exception: STATUS_ACCESS_VIOLATION at eip=74EB3880
eax=00000000 ebx=00001000 ecx=00000A1F edx=7FFB001C esi=02410000 edi=0240D37A
ebp=0240C790 esp=0240C748 program=C:\dk\dk\win\gnu\cw1.3.12\bin\tee.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0240C790  74EB3880  (000004E4, 00000000, 0240FA1F, 00001000)
0240E7D0  61016F2F  (000001B5, 0240E818, 000004E4, 0240FA1F)
0240F830  61019EF4  (61680704, 0240FA1F, 0240FDF0, 0240F000)
0240F870  6101A46F  (61680704, 0240F9F0, 00000400, 00000001)
0240F8D0  61071896  (00000001, 0240F9F0, 00000400, 0240F8D0)
0240F8F0  610B0C86  (610BF030, 00000001, 0240F9F0, 00000400)
0240F920  610ACDBA  (610BF2F0, 0240F9F0, 00000400, 610714FD)
0240F960  610AD0F8  (610BF2F0, 0240F988, 00000601, 00000000)
0240F9B0  6109F9C5  (0240F9F0, 00000400, 00000001, 610BF2F0)
0240FDF0  004017C7  (00000001, 0A7E03A4, 0240FE30, 004015C1)
0240FE30  004015D6  (00000002, 0A7E03A0, 0A7E0278, 00000001)
0240FEC0  61005B8E  (610C29AC, FFFFFFFE, 000000E8, 610C28D0)
0240FF20  61005E2C  (00000000, 00000000, 00000000, 00000000)
0240FF50  00405073  (00401480, 00000000, 00000000, 00000000)
0240FF80  0040103D  (003F6000, 74448630, 9899B05D, 0240FFDC)
0240FF94  74448654  (003F6000, 9BA23A78, 00000000, 00000000)
End of stack trace (more stack frames may be present)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Where does the error appear? Can you provide a screenshot?

**Comment by jiaolu** [comment]
![capture](https://user-images.githubusercontent.com/858509/33875334-eb3238e8-df5c-11e7-93f7-7ef8cbedf708.JPG)
here are the picture

**Comment by jiaolu** [comment]
any more info?

**Comment by Tyriar** [comment]
What's in your settings.json? If you're using cygwin it seems a bit flaky sometimes which is probably what's causing the problem.

**Comment by jiaolu** [comment]
// Place your settings in this file to overwrite the default settings
{
    "window.openFilesInNewWindow": true,
    "window.zoomLevel": 0,
    "editor.renderWhitespace": "boundary",
    "python.pythonPath": "C:\\Users\\jiaolu\\AppData\\Local\\Programs\\Python\\Python35\\python.exe",
    "terminal.integrated.shell.windows": "cmd.exe",
    "git.confirmSync": false,
    "window.menuBarVisibility": "default",
    "workbench.statusBar.visible": true,
    "workbench.iconTheme": "vscode-icons",
    "workbench.activityBar.visible": true,
    "python.linting.enabledWithoutWorkspace": false
}

this is my settings.json
any setting can be configured to fix this issue?

**Comment by jiaolu** [comment]
forget to mention it seems to be regression to me , since it does not happen in the windows 1703 and old  VS code.

**Comment by Tyriar** [comment]
@jiaolu Why do you say cygwin? It looks like you're using cmd.exe in both your screenshot and settings? 

Also Windows 1703 was fine, are you still on that version or have you updated?

**Comment by jiaolu** [comment]
Hello,  i am use the cygwin prebuilt "ls" and "tee" command in the visual studio code integrated console.

**Comment by jiaolu** [comment]
My machine is updated, so i can not access 1703 right now.

**Comment by Tyriar** [comment]
@jiaolu what version of Windows did you update to?
