### ISSUE TITLE
Test Tour: Manual Test Script Node (JavaScript)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3960]
Test basic scenarios Use the following Templates:

•Create a new Starter Azure Node.js Express 3 Starter Project (JavaScript) in c:\src using the project template in Node.js -> JavaScript 
•Create a new Starter Azure Node.js Express 3 Starter Project (TypeScript) in c:\src using the project template in Node.js -> TypeScript

If you are testing io.js follow the "Configuring your project to use io.js" steps to configure your project:
• https://github.com/Microsoft/nodejstools/wiki/io.js-and-ES6-support#configuring-your-project-to-use-iojs 

Walk through these steps with both templates
•Wait for  npm install  to finish executing in the background (see details in the Output npm pane)
•Set a breakpoint in app.js at the line (or app.ts):

var app = express()
•Set a breakpoint in routes\index.js (or routes\index.ts) at the line that begins with

res.render('index'
•F5 to start debugging
◦Ensure the browser launches (http://localhost:1337)
◦Ensure both breakpoints are hit
◦Ensure the url loads successfully 

•Walk through the “Profiling” and “Start your profiling session” sections in the Profiling docs, and verify things look as they do in the screenshots ◦ https://github.com/Microsoft/nodejstools/wiki/Profiling#profiling 
◦https://github.com/Microsoft/nodejstools/wiki/Profiling#start-your-profiling-session

•Walk through the “Browsing/Installing new npm packages in the GUI” section ◦ https://github.com/Microsoft/nodejstools/wiki/Npm-Integration#browsinginstalling-new-npm-packages-in-the-gui 
◦Try different VS themes, and make sure things are readable and nothing looks out of place.

•Walk through the Test Explorer documentation: ◦https://github.com/Microsoft/nodejstools/wiki/Test-Explorer#test-explorer

•Browser/Node.js-side editing ◦Create a new directory named “hello”, and right click to add a new javascript item “item1.js” to the directory
◾Verify that the directory display name changes to “hello (node)”
◾Verify that Ctrl + Space in item.js produces a completions list with “process” in it. 
◾Right click the directory, and select “Set as Content (Browser code)”
◾Verify that the directory display name changes to “hello (browser)”
◾Verify that the build action of the item.js file is now set to “Content”
◾Add a new javascript file, “item2.js” to the directory, by right clicking the directory and using “Add New Item”
◾Verify that the directory name is still set to “hello (browser”)
◾Ctrl + space in the “item2.js” file that has opened, and verify that “document” appears in the completions list
◾F2 to change the name of the directory, and verify that the edit label is “hello”
◾Type a new directory name - “goodbye”
◾Verify that the name of the directory is “goodbye (browser)”

•Right click the project, Add new item, select the “Dockerfile” item template, and verify that the file is generated successfully.
•Interactive window ◦Open the Node.js Interactive Window using Ctrl+K, N
◦Run  .npm install azure --save-dev  
◦Verify that the output is readable and doesn’t include any odd characters once the command finishes executing 
◦Verify that a new entry has appeared in the  npm > dev  node in Solution Explorer and there are no errors/warnings

**Comment by egamma** [comment]
@weinand This is the ExpressApp created in Visual Studio using the started sample

[ExpressApp1.zip](https://github.com/Microsoft/vscode/files/177643/ExpressApp1.zip)

**Comment by egamma** [comment]
@weinand this is the TypeScript one

[ExpressApp2.zip](https://github.com/Microsoft/vscode/files/177646/ExpressApp2.zip)

**Comment by weinand** [comment]
@egamma this tour doesn't make much sense for VS Code.

- VS Code does not launch a browser on F5
- the TypeScript template does not have any TypeScript setup (no dev-dep in package.json, no compile or watch scripts)
- the 'Profiling', 'Test Explorer' and the remaining sections apply to VS not VS Code.

**Comment by egamma** [comment]
@weinand sorry the plan was that the this gets adapted to VS Code //@mousetrap

**Comment by Tyriar** [comment]
ping @mousetraps
