### ISSUE TITLE
Tab shrink: further reduce padding when close button is left

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#39603]
Testing #39331

![image](https://user-images.githubusercontent.com/323878/33591139-8a91ec38-d938-11e7-9363-9f4f315df7c6.png)

It feels like the tabs under "shrink" take up a lot of space for the amount of text you get. I think it's the same amount of padding as the full width tabs, but maybe it could be tightened up for smaller tabs?

**Comment by roblourens** [comment]
Actually I realize that's with `tabCloseButton: left`. On the right,

![image](https://user-images.githubusercontent.com/323878/33591237-3b04158c-d939-11e7-8971-eee8d87a5ddf.png)

I can see much more. The text is going all the way to the edge with the close button on the right.

**Comment by bpasero** [comment]
Yeah I can see if I can also tweak the layout if the button is on the other side.

**Comment by bpasero** [comment]
I am actually not sure what to do here. If someone has an idea with a reasonable (ideally CSS only) PR, let me know.

**Comment by joshunger** [comment]
Did you want to always want to reduce it on the left?  See PR.

This is what is looks like -
![image](https://user-images.githubusercontent.com/2301847/34352619-f49eb666-e9e0-11e7-83f8-aae30cf9f514.png)

However, the welcome tab feels a little tight -
![image](https://user-images.githubusercontent.com/2301847/34352603-d76189ac-e9e0-11e7-84b6-617bfbd58b07.png)

**Comment by bpasero** [comment]
@joshunger I think what I would expect as solution is the same thing we do for the close button when `"workbench.editor.tabSizing": "shrink"` is configured and the close button is on the right:

![before](https://user-images.githubusercontent.com/900690/34403973-c1a1ad78-ebab-11e7-9a08-c4b8fe107180.gif)

**Comment by joshunger** [comment]
@bpasero Got it.  I'm assuming you want it to overlay the icon?  Anything else I need to know?

**Comment by joshunger** [comment]
@bpasero do you have a `claim` bot so contributors can claim issues?  How do you know who is working on it if it is labeled `help-wanted`?

**Comment by bpasero** [comment]
@joshunger yeah I would say overlay anything that is at that location, keep in mind that icons can also be turned off. 

There is no "claiming" of issues so far, but agree it would be useful.

**Comment by joshunger** [comment]
Thought this was cool https://github.com/devtools-html/debugger.html/blob/master/docs/issues.md#claiming-issues
