### ISSUE TITLE
Ability to contribute and run a command when Double Clicking on a node in custom views

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39601]
Requested use case needs ability to contribute and run a command when Double Clicking on a node in custom views

_From @changsi-an on December 5, 2017 2:3_

After a node debug session is launched. I cannot pin a script file in the text editor by double-clicking it. While I can do so for the files in the Explorer viewlet. 

A work around to pin a document is to double-click its tab in the text editor after it's opened. (At the same time the font changes from italic to normal). 

_Copied from original issue: Microsoft/vscode-node-debug2#155_

**Comment by roblourens** [comment]
This would need support from the custom tree view extension API. Since we're using it as a second file explorer, it would be nice to be able to implement other file explorer features for it.

**Comment by roblourens** [comment]
cc @weinand

**Comment by fernandoescolar** [comment]
I have a (ugly) workaround for this issue: https://github.com/fernandoescolar/vscode-solution-explorer/blob/master/src/commands/OpenFileCommand.ts

But It would be great if the treeitem could have different events like the doubleclick one.

**Comment by sandy081** [comment]
After discussions we decided not to expose double click command.

There should be only one command and executing this command on single click or double click is up to application. There is a setting `workbench.list.openMode` to configure this behaviour.
