### ISSUE TITLE
Find All input should be populated with Global Search Buffer

### ISSUE THREAD

**Issue by wprater** [Microsoft/vscode#39609]
After this PR https://github.com/Microsoft/vscode/pull/35956, the find all input should also be input with the Global Search Buffer.  This is how other add and editors behave in macOS that use the global search buffer.

https://github.com/Microsoft/vscode/issues/39585

/cc @rebornix @alexandrudima @melvin0008 @liyanage

**Comment by rebornix** [comment]
The bot is smarter than me, it's about Search indeed ;(

**Comment by roblourens** [comment]
When should the search viewlet get the global search buffer? Anytime it opens/cmd+shift+f is pressed?

**Comment by wprater** [comment]
> When should the search viewlet get the global search buffer? Anytime it opens/cmd+shift+f is pressed?

@roblourens I would argue that whenever a window gains focus, it should update all the search input fields.

likewise on change events on the input fields which should be updated the global buffer and most all cocoa apps would update their search input fields on window focus.

**Comment by melvin0008** [comment]
@wprater I would like to confirm the feature request. 

This feature request states that similar to #35956 , we should also populate the 'find all' clipboard.

Is the above correct?

**Comment by roblourens** [comment]
Right

**Comment by roblourens** [comment]
If the find widget is already visible, then it doesn't take the global buffer until cmd+g/f3 is pressed. So it seems like the search viewlet shouldn't have its query replaced when it's already visible and is possibly in the middle of a search. But the search viewlet is obviously used differently and could be open when it isn't being used.

**Comment by wprater** [comment]
how do we handle the find all pane then?  if it were not visible Id expect the global search buffer to populate all search input fields (find and find all) in all the project windows.  

this is how Ive operated across many app and editors for years.  

wonder if I need to write a more complex example, or do we all agree on the functionality that's standard for mac users?

**Comment by roblourens** [comment]
I don't disagree that it's standard - just thinking out loud about whether the search viewlet is a different case. But trying it some more in different apps, I guess not - I think it should work as you say.

I also just can't get over the fact that I've never seen or heard of this before, but now I can't help but notice it.

**Comment by wprater** [comment]
Yeah, its a really nice feature!  I generally will cmd+e in Safari to put text into global search buffer, then go to the Terminal, XCode, or an editor and use cmd+g to find items in the window or use find all command.

**Comment by wprater** [comment]
@roblourens is this in insiders yet, as Im not seeing this fixed as of yet.  

If the Find all viewlet is already open, its not being updated with the updated buffer.

**Comment by roblourens** [comment]
Yes, it's only updated when the text box gets focus

**Comment by wprater** [comment]
This is by design? Makes going from one project to another to use Find All with the Global Search Buffer a non-starter tho?

**Comment by roblourens** [comment]
How so? It works fine for me, does it not work for you?

**Comment by liyanage** [comment]
Hm it's working for me today. A few days ago I also thought that it wasn't working.

Re-reading @wprater's comment, I realize that it only updates when the editor pane has the focus. If for example a file in the sidebar is selected and the app is brought to the foreground, the search box doesn't update.

That is not intuitive, and it is not how other Mac apps work. Other apps update the search text immediately when they are brought to the foreground, and I think VSC should behave the same.

See the video below for the difference. Another oddity shown in the video is that the global find clipboard's contents are ignored/overwritten when I hit Cmd-F with something selected or with the cursor in a word. In any other Mac app, Cmd-F just brings up the find UI, but does not change the current search string.

![vsc-vs-textedit-global-find-clipboard](https://user-images.githubusercontent.com/52640/34316579-3abd37fc-e74e-11e7-9b58-c9781f11ee6c.gif)

**Comment by roblourens** [comment]
@liyanage This is about the search viewlet (cmd+shift+f) not editor find.

**Comment by liyanage** [comment]
Got it.

I just tried that, and it is not working at all there. It never gets the global clipboard contents.

**Comment by roblourens** [comment]
It's only implemented in the Insiders build.

**Comment by wprater** [comment]
Im still seeing broken behavior, should I open a new bug?

If you have the findAll pane open and highlight text and him cmd+e, it will not be populated on all projects find and findAll inputs, but it likely should.

**Comment by roblourens** [comment]
It is for me, when the text input box is focused. Should it be set immediately instead?

**Comment by wprater** [comment]
ahh, I see what you're saying now.  Its working like that for me as well.  however, I think its a better UX to see the input fields update after you set the global buffer vs. on focus.  

I think this leads me to another bug, where after I hit cmd+e the find inout field is focused.  feels like odd behavior, as I use it to set the global buffer, but I may still wish to navigate around the editor pane a bit.

**Comment by roblourens** [comment]
cmd+e is the same as cmd+f, so that's just a missing feature. I don't know whether it has an issue, you can open one (for @rebornix) if you want.

I'm not sure about setting the search viewlet text immediately - it's very visible and if it takes the text from the editor find widget every time I do a search in a file, then people will definitely file bugs about that. Filed #40955 to consider it some more.

**Comment by bpasero** [comment]
I am glad this is turned off by default, needs `"search.globalFindClipboard": true`

**Comment by aeschli** [comment]
But the default settings are not consistent...
```
  // Controls if the Find Widget should read or modify the shared find clipboard on macOS
  "editor.find.globalFindClipboard": true,

  // Controls if the Search Viewlet should read or modify the shared find clipboard on macOS
  "search.globalFindClipboard": false

**Comment by bpasero** [comment]
Yeah indeed.

**Comment by roblourens** [comment]
@rebornix and I thought that it makes more sense in the find widget because of the way it's used. It's only in the search viewlet where it annoys me. And it matches how it's enabled by default in other editors.
