### ISSUE TITLE
Shift-clicking highlighted text deselects text

### ISSUE THREAD

**Issue by msaffold** [Microsoft/vscode#39602]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
search-node-modules|jas|1.2.0
node-module-intellisense|lei|1.4.0
lambda-snippets|log|0.2.0
java|red|0.15.0
java-snippets|tus|0.0.1
colonize|vms|2.2.2
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Highlight text
2. Shift-click somewhere in the highlighted text.

Selection should be reduced.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This works as expected for me. Can you post a shot video / gif which shows this issue

**Comment by ramya-rao-a** [comment]
I can repro in 1.18.1
I can also verify that this somehow got fixed in 1.19 Insiders

@msaffold You can wait for the release of 1.19 in a few days or get the Insiders from https://code.visualstudio.com/insiders
