### ISSUE TITLE
Fix running extensions view in High Contrast theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39613]
Testing #39568

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/22350/33598269-636c4c2e-d9a2-11e7-8539-7dc1d9df19b0.png">

The report issue button is especially problematic. It is also a brand new UX button... why not re-purposing the extension actions button?

<img width="160" alt="image" src="https://user-images.githubusercontent.com/22350/33598325-a02befde-d9a2-11e7-8bc7-11357a242c23.png">

**Comment by ramya-rao-a** [comment]
In the latest Insiders (https://github.com/Microsoft/vscode/commit/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee):

Below is high contrast: 

![image](https://user-images.githubusercontent.com/16890566/33679925-e95d2272-da74-11e7-84d5-7e29abf3aabd.png)


Below is dark theme:

![image](https://user-images.githubusercontent.com/16890566/33679946-f69c8cca-da74-11e7-97b0-aab3f6d44529.png)


Light themes are good

**Comment by isidorn** [comment]
Dup of #39815
