### ISSUE TITLE
New setting to exclude folders from file watching

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#3961]
**Assignees:**

- [x] Windows @alexandrudima 
- [x] OS X @seanmcbreen 
- [x] Linux @weinand 

A new setting `files.watcherExclude` can be used to modify the list of excluded folders from file watching. The format is glob patterns and we always had a hardcoded default that now is the default setting.
* Verify you can change the setting and after a restart you do not get file events for configured patterns (e.g. verify in the explorer)
* OS X only: verify that for a very large folder (e.g. chromium sources, typescript) you see a short CPU spike in the beginning that drops after a while). now add a setting to exclude the large folder and verify the CPU spike no longer occurs.

**Comment by weinand** [comment]
@bpasero What is the reason that `files.watcherExclude` use a different pattern than the other settings?

```json
	"files.exclude": {
		"**/.git": true,
		"**/.DS_Store": true
	},
	"search.exclude": {
		"**/node_modules": true,
	},
	"files.watcherExclude": {
		"**/node_modules/**": true
	}
```

Would this not work?

```json
	"files.watcherExclude": {
		"**/node_modules/": true
	}
```

**Comment by bpasero** [comment]
@weinand yes I believe you are right, could you verify this during testing? If so we could change our defaults.

**Comment by weinand** [comment]
@bpasero I've tried both patterns and could not find a difference.

**Comment by bpasero** [comment]
@weinand great I can change the default then :+1:
