### ISSUE TITLE
Uninstalling extension does not show the 'reload' tag

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#39612]
Testing #39593

Version 1.19.0-insider
Commit 6bc5a14bf34e44b3af5508350cc1221fcc999ceb
Date 2017-12-05T06:14:37.864Z

- Started my existing workspace the first time, clicked on uninstalling an extension
- 'Uninstalling' is shown, but does not turn into 'Reload'
- No error in the dev tools

I thought that extension was disabled before

![image](https://user-images.githubusercontent.com/6461412/33595215-804a8da2-d997-11e7-9992-5e21951b8747.png)

**Comment by sandy081** [comment]
@aeschli Did you get the confirmation dialog to Uninstall?

**Comment by sandy081** [comment]
I think, I was seeing yesterday in out of dev build. But was not seeing this in latest insiders. Related https://github.com/Microsoft/vscode/issues/39561

**Comment by aeschli** [comment]
@sandy081 I didn't get the dialog.
On restart, the extension is still present. 'Uninstall' then shows the dialog and all went fine.

**Comment by sandy081** [comment]
@aeschli I am not able to reproduce it. Let me know if it is consistently happening on your system, so that I can take help of yours to debug on your system?

**Comment by aeschli** [comment]
Sure, I haven't since then. Ok to close.

**Comment by admmasters** [comment]
@sandy081 I'm getting this now. Have had it occur on 2 different machines - both Macs one on High Sierra and the other on Sierra.
