### ISSUE TITLE
html format problem in vue

### ISSUE THREAD

**Issue by forzeny** [Microsoft/vscode#39615]
- VSCode Version: 1.18.1
- OS Version: macOS HIGH win10

## Steps to Reproduce:
html file before format
![image](https://user-images.githubusercontent.com/18499153/33598326-4d3d19e8-d9dd-11e7-9083-8d58c987c6d8.png)
after format 
![image](https://user-images.githubusercontent.com/18499153/33598349-6149085c-d9dd-11e7-8f77-2a4765db3de7.png)
it caused the new line, and the vue expression can not render in win10 but can render in macOS
## Reproduction link
https://github.com/forzeny/bug-report

## vscode config
```js
{
  // 将设置放入此文件中以覆盖默认设置
  "files.autoSave": "off",
  "window.zoomLevel": -1,
  "vsicons.projectDetection.autoReload": true,
  "[javascriptreact]": {},
  "vsicons.dontShowNewVersionMessage": true,
  "extensions.ignoreRecommendations": false,
  "editor.fontSize": 15,
  "editor.tabSize": 2,
  "vetur.format.defaultFormatter.js": "vscode-typescript",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "indent_size": 1,
      "html": {
        "end_with_newline": false,
        "js": {
          "indent_size": 1
        },
        "css": {
          "indent_size": 1
        }
      },
      "css": {
        "indent_size": 1
      }
    }
  },
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  },
  "eslint.validate": ["javascript", "javascriptreact", "html", "vue"],
  "eslint.options": {
    "plugins": ["html", "vue"]
  },
  "vetur.format.defaultFormatter.html": "js-beautify-html",
  "prettier.useTabs": true,
  "prettier.tabWidth": 2,
  "prettier.singleQuote": true,
  "prettier.semi": false,
  "sync.gist": "5ef1601d2e0c195f1775418242a8c58c",
  "sync.lastUpload": "2017-11-09T12:06:47.212Z",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "workbench.colorTheme": "Monokai",
  "merge-conflict.decorators.enabled": false,
  "merge-conflict.codeLens.enabled": false,
  "git.enabled": false,
  "python.disablePromptForFeatures": [
    "pylint"
  ],
  "workbench.startupEditor": "newUntitledFile",
  "editor.renderIndentGuides": true,
  "editor.wordWrap": "on"
}
```

**Comment by octref** [comment]
Linking https://github.com/vuejs/vetur/issues/570

@aeschli He's formatting this file: https://github.com/forzeny/bug-report/blob/master/src/components/hello.html
So it's the html formatter.

**Comment by aeschli** [comment]
It's an HTML formatter... You can use it for Vue or other templating languages at your own risk, but it will not understand the Vue syntax.
@octref I think vue needs its own formatter. Alternatively, file an issue against https://github.com/beautify-web/js-beautify and convince them to add an option to preserve `{{ .. }}` blocks

**Comment by forzeny** [comment]
so I'm going to give up split vue template to single html file

**Comment by forzeny** [comment]
it was interesting that it can render in macOS and Windows cannot render
