### ISSUE TITLE
Layout issues in Running Extensions view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39614]
Testing #39568 

- Notice the flex glitches
- Notice how the three textual labels are all vertically misaligned 
- The only UX indication that the three textual labels are actually related to one another becomes evident only when the user hovers a row with the mouse

<img width="647" alt="image" src="https://user-images.githubusercontent.com/22350/33598350-b5010282-d9a2-11e7-82df-acd5e0a38431.png">

**Comment by ramya-rao-a** [comment]
In the latest Insiders (https://github.com/Microsoft/vscode/commit/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee):

`Report Issue` buttom is not aligned when there is a warning/error for the extension or extension name is long

![image](https://user-images.githubusercontent.com/16890566/33679769-80e9ef7c-da74-11e7-8260-d4349f39fb89.png)

**Comment by isidorn** [comment]
That is fine for now. Since we plan to move it to the extensions viewlet either way
