### ISSUE TITLE
Clicking the profile canvas in Running Extensions doesn't select the row

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39616]
Testing #39568

Click the canvas with the mouse:

<img width="1127" alt="screen shot 2017-12-05 at 09 58 59" src="https://user-images.githubusercontent.com/22350/33598421-f60a3500-d9a2-11e7-8928-4177d3bc7586.png">

Same goes for right click: no context menu

**Comment by alexandrudima** [comment]
I believe this is a bug in the list. That is an `<svg>` element and we don't have any `mouse` / `click` listeners where we would prevent default or anything in the `runtimeExtensionsEditor.ts`.

**Comment by joaomoreno** [comment]
SVG automatically captures mouse events. 😢 

Get a `pointer-events: none;` in there, yo.

**Comment by joaomoreno** [comment]
I just pushed that line.

**Comment by alexandrudima** [comment]
wow, good to know! thanks!
