### ISSUE TITLE
multi-root workspace settings not using json w/comments mode

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39619]
testing #39588

open a folder 
file | add folder to workspace
open settings

result -> workspace settings language mode is JSON, not JSON with comments.

![image](https://user-images.githubusercontent.com/1487073/33599352-2e9fd14c-d9a6-11e7-99cb-eeeeb27bbf9d.png)

**Comment by aeschli** [comment]
@sandy081 Instead of `workspace.json`, can you name the file `workspace.code-workspace`? 
That way it would match the configured file extensions for `jsonc1. I can also add `workspace.json` but thought that this is quite a common name that might be used for regular JSON files as well.

**Comment by sandy081** [comment]
@bpasero is creating this file on the main side for unsaved workspaces. Ben, over to you.

**Comment by bpasero** [comment]
@sandy081 @aeschli please come up with another solution, there are untitled workspaces for all our multi root users called `workspace.json` so this would not be a solution. If it helps, these files are all in a well known location ([`workspacesHome`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/common/environment.ts#L90)).

**Comment by chrisdias** [comment]
@aeschli yes, comments do not error and i can have trailing commas

**Comment by aeschli** [comment]
Then it's just the editor language mode that is lying, as with other files. Closing as ok.
