### ISSUE TITLE
Mouse click no response

### ISSUE THREAD

**Issue by illinux** [Microsoft/vscode#39610]
-
![default](https://user-images.githubusercontent.com/30189427/33595439-21493236-d9d3-11e7-822e-27c03bf39c3b.gif)
 VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
vscode-great-icons|emm|2.1.20
code-python-isort|fre|0.0.3
output-colorizer|IBM|0.1.2
easy-icons|jam|0.3.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
start-git-bash|McC|1.2.1
vscode-filesize|mkx|1.0.0
python|ms-|0.8.0
azure-account|ms-|0.2.2
team|ms-|1.122.0
vscode-docker|Pet|0.0.22
vscode-icons|rob|7.18.1
code-settings-sync|Sha|2.8.6
guides|spy|0.9.1
html-preview-vscode|tht|0.1.1
python|tht|0.2.3
bootstrap-3-snippets|wcw|0.1.0

(11 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Check out the part about submiting good issues 
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by illinux** [comment]
The selected content can not be clicked to cancel the selection

**Comment by isidorn** [comment]
What does some time mean? Please file reproducable steps as we can not get this behavior on our machines.
Can you also reproduce without extensions?

**Comment by ramya-rao-a** [comment]
@illinux 

I cannot repro either.
Run `code --disable-extensions` and see if you can still repro this way with all extensions disabled.
Also, try our Insiders build from https://code.visualstudio.com/insiders where the issue might already be fixed.
