### ISSUE TITLE
Plain text file shown as binary, too large

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39623]
re #39583

Not yet sure how this happened, but it is bad

![dec-05-2017 10-30-42](https://user-images.githubusercontent.com/1794099/33599763-63ac7b32-d9a7-11e7-89c8-51112c61d458.gif)

**Comment by jrieken** [comment]
Did this:

* open an images with changes
* select the 'Show Changes' button
* open a text file with changes
* select the 'Show Changes' button

![dec-05-2017 10-33-57](https://user-images.githubusercontent.com/1794099/33599884-df8af152-d9a7-11e7-95e8-d49ada66e7e1.gif)

**Comment by jrieken** [comment]
This is actually always with this file. Likely because it is around 40000 lines (which shouldn't be too large for a diff)

**Comment by joaomoreno** [comment]
This happens if a file is over 1MB now. Need to relax that a bit.

**Comment by jrieken** [comment]
Not sure it's smart to use that encoding thing for text files

**Comment by joaomoreno** [comment]
We don't use the encoding thing for text files, but we do need an upper limit on file size and warn that the file is too big.
