### ISSUE TITLE
Duplicate Running Extensions views when stopping profiling

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39624]
Testing #39568

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/22350/33599777-721a16a2-d9a7-11e7-8a38-99530cee805a.png">

1. Open a split layout like in the picture
2. Start profiling
3. Focus the editor on the right
4. Stop profiling in the status bar

You will end up with two Running Extensions views

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/22350/33599836-a83a0580-d9a7-11e7-9a10-662ebacb0e41.png">

**Comment by isidorn** [comment]
@bpasero is it possible to limit the view to only be showed once at most?
I believe I was somehow achieving this while the REPL was an editor?

**Comment by bpasero** [comment]
@isidorn could probably do this if you set `revealIfOpened` as editor options. This will try first to reveal the editor if it is opened in any editor group, even if not visible.
