### ISSUE TITLE
Can't read CPU profile

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39629]
Testing #39568

I just recorded a CPU profile:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/22350/33600035-6121a3b4-d9a8-11e7-857a-6166ad87cb48.png">

I exported it:

[CPU-20171205T093642.146Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1530569/CPU-20171205T093642.146Z.cpuprofile.txt)

Nothing shows up when I open it in the Devtools:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/22350/33600193-d88bcb00-d9a8-11e7-8a19-eaf9976cc828.png">

What am I doing wrong?

**Comment by jrieken** [comment]
Devtools only opens files with the `.cpuprofile` ending. We still append `.txt` because GH won't let you upload it otherwise

**Comment by joaomoreno** [comment]
@jrieken Same result, after renaming the file.

**Comment by jrieken** [comment]
Well, it's a CPU profile. Make sure to use the CPU profiler (hidden in the overflow menu).

**Comment by joaomoreno** [comment]
Oh that was it! I was dragging it over the Timeline. Thanks!
