### ISSUE TITLE
JSON: workspace.rootPath is deprecated

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39625]
Testing #39568

<img width="705" alt="image" src="https://user-images.githubusercontent.com/22350/33599896-e977200a-d9a7-11e7-98b3-3cb21fdbf6ba.png">

**Comment by aeschli** [comment]
@dbaeumer The language server client does that. I wonder if we should add a configuration setting to the language server client to signal that the server doesn't need it, or a rule to our extension profile tooling to ignore it.

**Comment by dbaeumer** [comment]
@aeschli having a setting for this sounds wired. What if there is another deprecated API. Should I leave that out as well then.

I think what we can do is to use workspaceFolders[0] which is equal to rootFolders. Opened https://github.com/Microsoft/vscode-languageserver-node/issues/285

**Comment by aeschli** [comment]
Closing then, all is fine here.
