### ISSUE TITLE
Cannot go back from image diff

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39626]
re #39583

* Open changes for an image
* the upper right keeps showing 'Show Changes' instead of the back-to-file-action

<img width="645" alt="screen shot 2017-12-05 at 10 36 25" src="https://user-images.githubusercontent.com/1794099/33599977-2df47aac-d9a8-11e7-8d19-f8f3ee070876.png">

**Comment by joaomoreno** [comment]
I like @isidorn's better: https://github.com/Microsoft/vscode/issues/39636

**Comment by jrieken** [comment]
Less to verify for me 👯‍♂️
