### ISSUE TITLE
Collapse all and close all icons too similar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#3962]
Currently the 'collapse' and 'close all files' icons are very similar. It would be cool if they were more easily distinguishable, especially since they appear in nearby locations.

fyi @bpasero

<img width="339" alt="screen shot 2016-03-10 at 16 35 35" src="https://cloud.githubusercontent.com/assets/1926584/13674538/2ab9303a-e6de-11e5-8705-902f388f7e1b.png">
<img width="333" alt="screen shot 2016-03-10 at 16 35 43" src="https://cloud.githubusercontent.com/assets/1926584/13674539/2ab9a6b4-e6de-11e5-8d1c-330312b422f1.png">

**Comment by bgashler1** [comment]
Totally agree.  I think this will address your concern.

![correctedicon](https://cloud.githubusercontent.com/assets/11839736/14162037/26983932-f69d-11e5-863d-5e171ae77fe7.png)

**Comment by bpasero** [comment]
I think we went over this issue in time.
