### ISSUE TITLE
Images at 3.5MB don't open

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39620]
re #39583

The test plan says that images at ~5MB should open. They don't, not from the explorer nor from the SCM viewlet.

<img width="1153" alt="screen shot 2017-12-05 at 10 23 48" src="https://user-images.githubusercontent.com/1794099/33599419-65cddbdc-d9a6-11e7-9d2e-1e7d73620920.png">

**Comment by bpasero** [comment]
The test plan is wrong, the max is 1MB: https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L118

**Comment by jrieken** [comment]
Is that fairly useless given that a screenshot costs ~10MB

**Comment by joaomoreno** [comment]
Whoops sorry for the wrong limit!

**Comment by bpasero** [comment]
I don't.
