### ISSUE TITLE
An invalid LanguageConfiguration.wordPattern can cause vscode to crash

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#3963]
This is an odd set of circumstances, but it causes v10.10 to crash (on Windows), and it didn't in 10.8, so I'll report it anyway. I was experiencing a lot of crashes while developing autocomplete in an extension, and found that it boiled down to this:

If an extension provides a *LanguageConfiguration* with a *wordPattern* that can match an empty string (eg ```/\w*/```), and it then registers a *CompletionItemProvider* that provides no completion items (an empty array): the intellisense will show "Loading..." for about 10 seconds, then vscode will crash.

Here's example code ([full sample attached](https://github.com/Microsoft/vscode/files/167431/abc-completionitems.zip)). This extension creates a new language "abc" with extension ".abc".

``` ts
import * as vscode from 'vscode';
import { TextDocument, Position, CancellationToken, CompletionItem, languages } from 'vscode';

const languageConfiguration: vscode.LanguageConfiguration = {
	wordPattern: /\w*/
}

export function activate(context: vscode.ExtensionContext) 
{
	context.subscriptions.push(
		languages.setLanguageConfiguration('abc', languageConfiguration));
		
	context.subscriptions.push(
		languages.registerCompletionItemProvider('abc', new CompletionItemProvider()));
}

class CompletionItemProvider implements vscode.CompletionItemProvider {
	provideCompletionItems(
		document: TextDocument, position: Position, token: CancellationToken)
		: CompletionItem[]
	{
		return [];
	}
}
```

Both conditions must be true: if the completion provider provides at least one result then it's shown without a problem. If the wordPattern is a valid one then the intellisense shows "No suggestions." for an empty array without problem.

I think it can also cause crashes with a hover provider too but I haven't pinned that one down.

**Comment by jrieken** [comment]
@stkb It does crash :scream: Will drill into this asap. Thanks for reporting such awesome steps.

**Comment by jrieken** [comment]
@alexandrudima This is happening with the `textualSuggest` and us never returning from `MirrorModel._wordenize`

**Comment by jrieken** [comment]
<img width="839" alt="screen shot 2016-03-11 at 09 59 21" src="https://cloud.githubusercontent.com/assets/1794099/13697778/094a8466-e770-11e5-861c-a6796ede7834.png">

**Comment by jrieken** [comment]
@stkb wondering if you have shipped your extension with such a word definition. Now we will throw an exception from `setLanguageConfiguration` which might be to harsh

**Comment by stkb** [comment]
@jrieken Thanks, it's in the [vscode-elm](https://github.com/sbrink/vscode-elm) extension, and was of course a bug, so throwing an error seems fine. It just didn't get noticed until v10.10 where I experienced the crashes. Have submitted a fix there.

Some other people have also reported crashes with that extension (sbrink/vscode-elm#41), but hopefully that was the reason.

**Comment by jrieken** [comment]
great
