### ISSUE TITLE
Break point is not visible in break points view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39634]
Testing #39099

Steps to reproduce

- Open VS Code workspace
- Start Launch VS Code launch
- Add a break point in the code

Expected: Break point should be visible in break points view

![image](https://user-images.githubusercontent.com/10746682/33600711-564c1a12-d9aa-11e7-93db-454886fda8f1.png)

**Comment by isidorn** [comment]
Following your steps this works for me.
Can you please provide more precise steps. How do you hit the breakpoint in the image shown? Can you also reproduce if you are not stopped at that point?

**Comment by sandy081** [comment]
Not sure how I got into this state.. I am not getting it now after doing it fresh.

**Comment by sandy081** [comment]
Yes, I was able to see this even when the program was not launched.

**Comment by sandy081** [comment]
Sorry, cannot reproduce anymore.

**Comment by isidorn** [comment]
Ok, in case you get it again let me know.
Also check if adding more breakpoints fixes the issue or the view stays in a broken state (in case it happens again)

Thanks
