### ISSUE TITLE
strange bug in my distributed system pc

### ISSUE THREAD

**Issue by rainnnnny** [Microsoft/vscode#39635]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.3
sublime-keybindings|ms-|3.0.3

(1 theme extensions excluded)

---

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/15228876/33600374-03ebd156-d9e4-11e7-9517-e8c610ce7fa2.png)

the only special thing of my pc is that it bases on a distributed system( I dont got physical machine, using a terminal device to connect ), no steps, the prompts above just keep appearing no matter what i choose, and restarting vsc or pc are both useless
(btw, I wanted to disable the linter and choose yes for the st plug-in)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please file this against the python extension github repository
