### ISSUE TITLE
Git diff images: not specific enough message for large image

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39631]
Refs: https://github.com/Microsoft/vscode/issues/39583

Get some large image. For instance https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Pizigani_1367_Chart_10MB.jpg/800px-Pizigani_1367_Chart_10MB.jpg

Try to open it in the editor, notice the nice error message that the image is too large

![screen shot 2017-12-05 at 10 47 55](https://user-images.githubusercontent.com/1926584/33600532-ca6bba2a-d9a9-11e7-8885-6725f8729eb2.png)

Now try to open it in the git diff view, as expected the file is not displayed but the error message is not specific enough:

![screen shot 2017-12-05 at 10 47 33](https://user-images.githubusercontent.com/1926584/33600510-b68e9db0-d9a9-11e7-971d-3c9d6d7fe76d.png)

**Comment by bpasero** [comment]
@isidorn not possible because the image is actually not a file on disk but a data URI.
