### ISSUE TITLE
extensions.json does not use "JSON with comments" mode

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39633]
testing #39588

create a new file `extensions.json` in a `.vscode` folder

result: language mode is `JSON`
expected: `JSON with Comments`

That said, comments are allowed in this file along with trailing commas.

![image](https://user-images.githubusercontent.com/1487073/33600588-fc0a439e-d9a9-11e7-9f7a-16de269c5a03.png)

**Comment by aeschli** [comment]
If comments are accepted, then all is ok.
As said the language mode is lying here, that's expected.
