### ISSUE TITLE
locale.json does not use "JSON with comments" mode

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39630]
testing #39588

`locale.json` uses the `JSON` language mode, not the `JSON with comments` mode.

That said, comments in `locale.json` are not errors and I can having trailing commas.

`F1`
`Configure Language`

result:

![image](https://user-images.githubusercontent.com/1487073/33600424-7d4365a4-d9a9-11e7-975d-c46155e226e6.png)

**Comment by aeschli** [comment]
If comments are accepted, then all is ok.
As said the language mode is lying here, that's expected.
