### ISSUE TITLE
code-insiders --help does not mention --log

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39648]
Refs: #39572

Comand line, `code-insiders --help`
--log option is not mentioned

**Comment by ramya-rao-a** [comment]
Do we log by default?
If yes, then the help should mention the default being used.
If no, then the message should say something like `Enables logging abc to xyz. Allowed levels are ...

**Comment by sandy081** [comment]
Default is `info`. Will mention that in the description.
