### ISSUE TITLE
Use Location type?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39647]
re #39553

The `SourceBreakpoint` has a source and a location... Two thing that I'd favour

* use the `Location`-type which is defined in the API
* tweak the name of `source` and `location`. We usually just use `uri` for a URI and `position` for a position.

**Comment by weinand** [comment]
The only reason why I refrained from using "Location" is that it is based on a "Range" instead of a "Position" (and the DAP doesn't support a range as a spec for a source breakpoint).
But I see the point of API consistency and regularity.

**Comment by weinand** [comment]
new proposed SourceBreakpoint:
```ts
	export interface SourceBreakpoint extends Breakpoint {
		/**
		 * Breakpoint type 'source'.
		 */
		readonly type: 'source';
		/**
		 * The source and line position of this breakpoint.
		 */
		readonly location: Location;
	}
```
