### ISSUE TITLE
json lang is not complaining about comments

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39642]
Testing #39588

- Open the snippet file for typescript
- Language shown is `json`

Comments are not getting complained

```
{

	// Place your snippets for TypeScript here. Each snippet is defined under a snippet name and has a prefix, body and
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the
	// same ids are connected.
	"Print to console": {
		// Example:
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	}

}
```

**Comment by aeschli** [comment]
It's just the status bar that lies. The editor is in jsonc mode, as it should.
Some modes we can't discover based on the file name, but only on the schema (which matches against special file paths).

**Comment by aeschli** [comment]
Closing, behaves as expected. This will eventually work when we introduce a snippet file extension (.vscode-snippets) (As discussed with @jrieken )
