### ISSUE TITLE
Log: a simple explanation what each process does could be helpful to the user

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39649]
Refs: #39572

Currently the user is presented with a choice to choose for which process to check the logs. In case he wants to investigate on his own it might be useful to put a simple one sentence description what each process is for. There is definetly space in the quick open

![screen shot 2017-12-05 at 11 29 19](https://user-images.githubusercontent.com/1926584/33602448-a1171c54-d9af-11e7-8319-1eac03bce2d0.png)

**Comment by sandy081** [comment]
Since this is a developer command, names are self explanatory. We do not provide any more details for other similar commands. For example

![image](https://user-images.githubusercontent.com/10746682/35438642-9c43b5dc-0297-11e8-851a-7360e6327c3c.png)
