### ISSUE TITLE
Pipe output does not seem to guess the encoding

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39658]
Refs: https://github.com/Microsoft/vscode/issues/39330

Ubuntu terminal:

`LANG=de_DE.UTF-16`
`ps aux  | code-insiders`
Notice that the file nicely openes with the output however the status says UTF-8, I believe I setup the encoding properly and he should have guesed it is UTF-16.

**Comment by isidorn** [comment]
Another example where this seems to be hit is

1. Have a folder named `Zürich`
2. Browse to the parent of that folder in the terminal
3. `ls | code-insiders`

Notice broken encoding

![screen shot 2017-12-05 at 12 11 45](https://user-images.githubusercontent.com/1926584/33604239-7a18b030-d9b5-11e7-8887-c524e7aae53f.png)

**Comment by bpasero** [comment]
@isidorn the resulting file will always use the configured encoding of VS Code (UTF-8 in most cases). 

Your encoding is only correctly set in the system if "`locale charmap`" prints it. Can you try?

**Comment by isidorn** [comment]
locale charmap prints out only UTF-8
If you want I can look into lunc how to correctly set the encoding so this charmap picks it up

**Comment by bpasero** [comment]
@isidorn yeah I think it needs more. http://www.linuxfromscratch.org/lfs/view/systemd/chapter07/locale.html

**Comment by isidorn** [comment]
After setting the locale I could make code pick up `Zürich` nicely
So I guess closing since it seems to work for my example
