### ISSUE TITLE
Cancelling an extension uninstallation still deletes the CachedExtensions/user file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39650]
Testing #39593

1. Click `Uninstall` on an extension
2. Cancel it

The `CachedExtensions/user` file will be gone.

**Comment by alexandrudima** [comment]
Good catch, but IMHO that is ok. The promise chain in the `uninstall` code is just ... crazy. So as soon as that is beginning, the cache is dropped. Nothing horrible happens, the next window start will recreate the cache.
