### ISSUE TITLE
Regexp search and replace works differently for "in-file" and "workspace"

### ISSUE THREAD

**Issue by Junkern** [Microsoft/vscode#39656]
- VSCode Version: 1.18.1
- OS Version: macOs Sierra 10.12.6

Steps to Reproduce:

1. Make a new file with one line `import { ref } from '../../helpers'`
2. Open the ("in-file") search and replace and search for `import { (.*) } from '(.*)'` and replace with `const { $1 } = require('$2')` => This works
3. If you type in (or copy) the exact search regexp in the "global search", the regexp is apparently not valid and produces an error: `Error parsing regexp near ' rt { (.*) ' at character offset 9: Not a valid base 10 number: "`

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You just need to escape the `{` because they are regex characters. Search uses the Rust regex engine which is a little stricter about things like that.
