### ISSUE TITLE
Use singular when only one user has rated

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39651]
When only one user has rated we show the tooltip `Rated by 1 users`. We can change that to `Rated by 1 user`.

**Comment by zemafaz** [comment]
Where does that issue happen?

**Comment by ramya-rao-a** [comment]
@zemafaz The tooltip being referred to here is the one that appears when you hover on the ratings on an extension in the extension viewlet in 1.19 Insiders
