### ISSUE TITLE
Indent with CallExpression

### ISSUE THREAD

**Issue by waitingsong** [Microsoft/vscode#39653]
- VSCode Version: 1.18.1
- OS Version: Win7 x64

Steps to Reproduce:
1. set settings with "editor.tabSize": 2,

2. create new file test.ts, and then input below:
```js
import * as $ from 'jquery'

$.get('foo')
.then(
  (res) => {
    console.log(res)
  },

  (err) => {
    console.log(err)
  }
)
```

3. Shift+Ctrl+F to format
expect:
```js
$.get('foo')
  .then(
    (res) => {
      console.log(res)
    },

    (err) => {
      console.log(err)
    }
  )
```
result:
```js
$.get('foo')
  .then(
  (res) => {
    console.log(res)
  },

  (err) => {
    console.log(err)
  }
)
```
The indent of func parameters of .then() not my expectation.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/5830
