### ISSUE TITLE
javascript syntax colors in space-less for loop

### ISSUE THREAD

**Issue by tionkje** [Microsoft/vscode#3965]
In the image below i have a snippet. In the body of the loop the syntax colors seem messed up.
The way to fix it is adding a space before the < and then the colors are normal.

I have this problem in version 0.10.10 and had it in the previous version.

![syntaxcolors](https://cloud.githubusercontent.com/assets/2932769/13675051/24d87098-e6e0-11e5-9735-33b45a379967.png)

Snippet:
```
for(var i=0;i<10;++i){
  // Weird colors
  for(var i=0;i<10;++i){
    // Weird colors
  }
}
// Normal color
for(var i=0;i <10;++i){
  for(var i=0;i <10;++i){
  }
}
```

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/11
