### ISSUE TITLE
Node runtime missing when executing Debug -> Start without Debugging

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#39661]
Steps:

- fresh workspace
- app.js
```js
console.log(process.env.TESTPASS);
```
- Debug -> Start without Debugging

Observe: the node runtime is missing

<img width="794" alt="capture" src="https://user-images.githubusercontent.com/1931590/33604695-39ca9d2a-d9b7-11e7-9504-efc06e654c1e.png">

**Comment by weinand** [comment]
@isidorn this is probably a missing activation event?

**Comment by isidorn** [comment]
Fixed via dbf8d61dd0
