### ISSUE TITLE
allowing breakpoints everywhere triggers a breakpoint event

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39666]
re #39553

* have this config `"debug.allowBreakpointsEverywhere": true`
* listen to breakpoint events and have already a few breakpoints
* toggle the `"debug.allowBreakpointsEverywhere"` from `true` to `false`
* two more breakpoint changes are fired

notice that those events are empty
<img width="533" alt="screen shot 2017-12-05 at 12 42 52" src="https://user-images.githubusercontent.com/1794099/33605394-dbc90d80-d9b9-11e7-8cad-2babddc26f3f.png">

**Comment by weinand** [comment]
@isidorn I can avoid sending out those empty events but why are you generating them in the first place?

**Comment by isidorn** [comment]
Great catch.
I had a problem where on each file event I was checking what breakpoints I need to remove since the file might be deleted by a file event. And after figuring out no breakpoints need to be deleted I would still cal the remove method with an empty array which would generate an event.
