### ISSUE TITLE
breakpoint position is bogous

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39665]
re #39553

* debug the breakpoints API
* in your debuggee set a breakpoint on line 13 
* the breakpoint object has a location with just a line but no character. It uses 1-offset instead of 0-offset numbers and it doesn't seem to be an instance of `vscode.Position`

<img width="1041" alt="screen shot 2017-12-05 at 12 38 10" src="https://user-images.githubusercontent.com/1794099/33605244-2b3aee2a-d9b9-11e7-83e9-d09cef2cd51e.png">

**Comment by weinand** [comment]
fixed:
- SourceBreakpoint.location is a proper vscode.Position
- SourceBreakpoint.location.character defaults to 0 if internal breakpoint has no column info
- SourceBreakpoint.location.{line,character} are 0-based
