### ISSUE TITLE
wrong color for arrow in inline div

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39667]
* Have added code
* show the inline diff
* the arrow uses the wrong color

<img width="505" alt="screen shot 2017-12-05 at 12 45 15" src="https://user-images.githubusercontent.com/1794099/33605482-4bb19c2a-d9ba-11e7-91d1-f6341374fbab.png">

**Comment by joaomoreno** [comment]
Peek view owner? ⚔️

**Comment by jrieken** [comment]
should be a ctor-option

**Comment by joaomoreno** [comment]
I guess the theme team never adopted it fully:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/peekViewWidget.ts#L107

**Comment by jrieken** [comment]
Not sure... It should be the frame color and does it work for inline errors/warnings and references...

**Comment by joaomoreno** [comment]
Found it, I just wasn't propagating the arrow color https://github.com/Microsoft/vscode/commit/65cd84391d96a46023085c3f937362088202b9a8. They should actually just be a single color, tho.
