### ISSUE TITLE
Spelling of "unique"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#39660]
testing #39586:

![2017-12-05_12-16-37](https://user-images.githubusercontent.com/1898161/33604435-486917ae-d9b6-11e7-9faa-43a6eb797db2.png)

"Uniq" is the name of a Unix utility but not a proper (alternative) spelling for "unique".
I suggest to remove it and just use "Identifier:" instead.

**Comment by joaomoreno** [comment]
Fixed in https://github.com/Microsoft/vscode-vsce/commit/092988ec7c08aa578176764c94062d28a9ec8153
