### ISSUE TITLE
object destruction breaks vscode intellisense 

### ISSUE THREAD

**Issue by moeinrahimi** [Microsoft/vscode#39662]
- VSCode Version: 1.18.1
- OS Version: windows 10 64bit

hi, I'm using object destruction to organize my helpers in one file, when i require libraries using object destruction vscode intellisene doesn't work anymore .
example : 
``` javascript
const appDir = process.env.PWD
const co = require('co');
const db = require(appDir+'/model')
const helper = require(appDir+'/controller/helper')
module.exports = {
    co : co ,
    db : db,
    helper : helper

}
```
and using it in other files : 
``` javascript
const { co, db, helper } = require(appDir + '/components/modules')
```
now i don't access to methods and properties in these files like before .

**Comment by mjbvz** [comment]
I don't think its the object destruction. Rather, our intellisense is not able to resolve import paths such as `require(appDir+'/controller/helper')`. This is a known limitation (https://github.com/Microsoft/TypeScript/issues/18656) 

Does IntelliSense start working again if you change the `require` calls to use a static string path?

**Comment by moeinrahimi** [comment]
@mjbvz 
removing appDir and using relative path doesn't solve the issue 
'../../controller/helper'

**Comment by mjbvz** [comment]
@moeinrahimi Can you please share a description of your project structure
