### ISSUE TITLE
Windows: try to be smarter about encoding detection

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39664]
Instead of hardcoding the encoding to cp850, should actually check the output of running chcp and find some well supported encodings we could use instead.

Refs: https://ss64.com/nt/chcp.html

**Comment by roblourens** [comment]
Verification steps? Is this for the integrated terminal?

**Comment by bpasero** [comment]
@roblourens this is for https://github.com/Microsoft/vscode/issues/39330

**Comment by roblourens** [comment]
I don't think I'm doing it right, here's what I've tried

- `chcp 866` for Russian
- `echo 'глаголь добро есть' | code-insiders`
- Change encoding in vscode to `CP 866`
- Result is random characters

-

- Have a file encoded as `CP 866` with russian text
- `type russian.txt | code-insiders`
- Change encoding in vscode to `CP 866`
- Result is random characters

Same with Greek, 1253

**Comment by bpasero** [comment]
@roblourens we are not carrying over the encoding into VS Code, so the file in VS Code will be whatever your default encoding is (most likely UTF-8). If you see the characters you type showing up properly in VS Code, you have verified this bug.

**Comment by roblourens** [comment]
I fix the encoding in vscode manually, but even then, the characters are not correct.

**Comment by bpasero** [comment]
@roblourens I see. I think the issue here is that you are only changing the encoding for the current running terminal session and when VS Code starts, I run `chcp` again but in a different terminal. I think this only works if the terminal encoding is set more permanently and not per the current session.

**Comment by roblourens** [comment]
You're right, it works great after changing my system locale to Russian.

**Comment by bpasero** [comment]
@roblourens thanks for testing this!

**Comment by heroboy** [comment]
@bpasero please add `936:"cp936"` for Simplified Chinese.
I modified `cli.js`, and tested `dir|node`, it works.

**Comment by bpasero** [comment]
@heroboy ok I can add it.
