### ISSUE TITLE
Mac OS X :: 0.10.10 :: Regex find for new line isn't working

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3966]
I'm trying to use a regular expression to replace the new line character `\n` with null. The regular expression isn't being matched, however. This is blocking me from performing some very basic text manipulation, that I would have naturally expected would work with ease in Visual Studio Code.

Am I doing something wrong here, or is it a bug?

<img width="536" alt="screen shot 2016-03-10 at 9 27 44 am" src="https://cloud.githubusercontent.com/assets/466713/13676338/a02e564c-e6a2-11e5-94ae-18457946749f.png">

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by alexandrudima** [comment]
You're not doing anything wrong, it is simply not implemented yet. Dup of #313
