### ISSUE TITLE
[php] Highlighting / Colorization of Variables in Strings

### ISSUE THREAD

**Issue by jstunkat** [Microsoft/vscode#3967]
This is broken or just not there, see the examples on the PHP Page.

http://php.net/manual/de/language.types.string.php
http://php.net/manual/de/language.types.string.php#language.types.string.parsing

It would be nice to have this, its really difficult to spot variables in strings without it.

Example (simple case):
echo "This is a {$variable}";
echo "This is a $variable too";

The variable {$variable} and $variable should be highlighted.

Example (a bit more complex from PHP page):
<<<'EOT'
My name is "$name". I am printing some $foo->foo.
Now, I am printing some {$foo->bar[1]}.
This should not print a capital 'A': \x41
EOT;

All this is a string, so no highlighting (Nowdoc), variables are not parsed.
In Heredoc there should be highlighting as variables are parsed. (see linked page above)

**Comment by aeschli** [comment]
We don't have that yet. I'll add it to our backlog.

**Comment by roblourens** [comment]
Looks like this works except for heredoc.

**Comment by mjbvz** [comment]
Here's what I see in 1.17: 

<img width="406" alt="screen shot 2017-10-11 at 9 07 49 pm" src="https://user-images.githubusercontent.com/12821956/31478889-5148dfbc-aec8-11e7-94e1-c3dd879d19c2.png">

@roblourens Does this look correct now?

**Comment by roblourens** [comment]
Yes!
