### ISSUE TITLE
Javascript React mode using ".jsx" file extension can not jump to the code definition,

### ISSUE THREAD

**Issue by yueduz** [Microsoft/vscode#39676]
JavaScript React mode using ".js" file extension can jump to the code definition,
Javascript React mode using ".jsx" file extension can not jump to the code definition

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.14.3-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
html-css-class-completion|Zig|1.14.0
vscode-css-modules|cli|0.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please provide a description of your project and some steps to reproduce the problem

**Comment by yueduz** [comment]
Symbol is a video. jsx can not jump to the definition of F12, I changed to js he can use F12 jump to the definition
[2017年12月06日 屏幕视频 12时12分29秒.zip](https://github.com/Microsoft/vscode/files/1533856/2017.12.06.12.12.29.zip)

**Comment by mjbvz** [comment]
Thanks.

Can you please share the contents of your `jsconfig.json`. Also, if you run the command `JavaScript: Go to project configuration` in these two files, does it open up the same `jsconfig.json`?

**Comment by yueduz** [comment]
Yes, he opens the same one jsconfig.json
```js
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

Symbol is the project file
[dgj_project.zip](https://github.com/Microsoft/vscode/files/1539293/dgj_project.zip)

**Comment by mjbvz** [comment]
Thanks. To work with JSX files, you'll need to set `"jsx": "preserve"`:

```js
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "jsx": "preserve"
    }
}
```

This should fix the module resolution
