### ISSUE TITLE
Store user extensions cache file in the user extensions folder

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#39675]
Testing #39593
When manually updating an extension, you start VSCode and have to wait 10 seconds to get a  dialog that asks to reload until you see your extension.

I often test my extensions like that, it would be great if the experience could be improved:
- reduce the timeout
- place the cache file in the extension folder, with a good name (`extensions.cache`) so I can delete it myself if needed
- check the folder mtime as suggested in #39652

**Comment by alexandrudima** [comment]
* The timeout is set to 5 seconds. I will not reduce it further as to not risk overlapping with the startup sequence.
* Let's track the mtime in #39652

==> I suggest we leave this issue about moving the cache file to the user extensions folder.

**Comment by alexandrudima** [comment]
I haven't received any other complaints about the cache location. I will close this for now, please speak up if you consider it to be super important...
