### ISSUE TITLE
VS Code should detect changes on NFS mounts when focused

### ISSUE THREAD

**Issue by joliss** [Microsoft/vscode#39673]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Reproduces without extensions: Yes

---

Steps to Reproduce:

1. Mount an NFS volume on macOS ([as described here](https://serverfault.com/a/716351)). My macOS client has the following mount: `sujin:/home/ubuntu on /net/sujin/home/ubuntu (nfs, nodev, nosuid, automounted, nobrowse)` (NFS v3)
2. Launch VS Code on macOS and open a file on the NFS mount.
3. Change the file on the NFS server (not through the client), e.g. by SSH'ing into the server.

VS Code does not detect the change when you Cmd-tab into it. Only if you change tabs and change back to the original tab does it detect the change.

My understanding is that network file systems don't generally do file watching very well, but the situation would be much improved if VS Code additionally checked for modifications when the window gets focus, not just when the tab is changed.

**Comment by bpasero** [comment]
We do this since a while now.
