### ISSUE TITLE
Tune data posted to extensions with File Issue

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39678]
testing #39568

when creating an issue for an extension, for example the `workspace.rootPath is deprecated` issue, I get 2 identical messages in the json that is put on the clipboard. Does mean there are 2 instances of it?  why are there so many `null` values?

![image](https://user-images.githubusercontent.com/1487073/33608489-f375783c-d9c4-11e7-872a-8f3fbe806552.png)

``` json
	"messages": [
		{
			"type": 2,
			"message": "workspace.rootPath is deprecated",
			"source": null,
			"extensionId": null,
			"extensionPointId": null
		},
		{
			"type": 2,
			"message": "workspace.rootPath is deprecated",
			"source": null,
			"extensionId": null,
			"extensionPointId": null
		}
	],
```

**Comment by isidorn** [comment]
@chrisdias I can not reproduce the duplicated message. I tried with your docker extension. For what extension where you filling a bug?

As for the `null` that is just how the data looks like, I could take out all the nulls but I do not really see the point

**Comment by chrisdias** [comment]
Its the docker extension `PeterJausovec.vscode-docker`.  weird, i can't reproduce it now either... but at least i have proof: https://github.com/Microsoft/vscode-docker/issues/188.

As an extension author that gets these issues, what do I do with the `source`, `extensionId`, and `extensionPointId` data, even if they were not `null`?

**Comment by isidorn** [comment]
Currently we do not have an end ot end story that we only give the useful data to the extension author and he can see what he wants to do with it.
We just dump everything, some can be useful, some can not. We can definetely refine this in the future if this aciton ends up being popular. No action until then though
