### ISSUE TITLE
"Profile extension host for 5 seconds" should be in "Developer" category

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#39679]
testing #39568

The `Profile extension host for 5 seconds` command should be in the `Developer:` category, such that the command is:

`Developer: Profile extension host for 5 seconds`

Also, how is this command related to the ability to start/stop profiling on the 'Running Extensions` editor?

**Comment by jrieken** [comment]
Added the category but I believe we shouldn't have this anymore... We now have the elaborated runtime view of extensions and this is the baby steps towards it. 

@aeschli Ok with removing this?

**Comment by aeschli** [comment]
Yes, ok to remove.

**Comment by jrieken** [comment]
Nuked
