### ISSUE TITLE
Git gutter always displays status of first folder in workspace

### ISSUE THREAD

**Issue by kdheepak** [Microsoft/vscode#39670]
- VSCode Version:

```
$ code-insiders --version
1.19.0-insider
8a12b294de610aab61c32c02c7c148d981cf07e4
x64
```

- OS Version:
OSX High Sierra 10.13.1

Steps to Reproduce:

1. Create a workspace
2. Add multiple git repos
3. Git gutter displays master
4. Open file in second folder, open the terminal and change branch to develop
5. Git gutter does not change from master to develop

Reproduces without extensions: Yes

**Comment by kdheepak** [comment]
I've attached an image to clarify what I mean by "git gutter". 

<img width="1440" alt="screen shot 2017-12-05 at 5 27 07 am" src="https://user-images.githubusercontent.com/1813121/33607091-0c13daa2-d97d-11e7-87b6-fdd2dd22185f.png">

The left most label. The right side of the status bar changes based on file as expected.

**Comment by joaomoreno** [comment]
The status bar will show the information of the last selected repository in the list of repositories. If you pick another repository in the list of repositories, does it update?

**Comment by kdheepak** [comment]
How do I find the list of repositories? If I select the folder in the tree view that corresponds to a different repository the status does not change.

**Comment by joaomoreno** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/22350/33611555-1688a01a-d9cf-11e7-9a01-cb0281729a4f.png">

**Comment by kdheepak** [comment]
You are right. I had the source control hidden and failed to realize that could be the way to affect the gutter status. Thanks for the prompt replies!
