### ISSUE TITLE
Focused suggestion keeps alternating back and forth as I type

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39685]
![kapture 2017-12-05 at 14 54 21](https://user-images.githubusercontent.com/22350/33610599-344de82e-d9cc-11e7-80f8-33a390d1a932.gif)

I got into this state 30 seconds after starting to test #39550

Here's the contents of my `storage://workspace/Users/joao/Work/vscode/suggest/memories/typescript`:

```json
[["abstrac",{"insertText":"AbstractCaseAction","type":"variable"}],["abstra",{"insertText":"AbstractCaseAction","type":"variable"}],["abs",{"insertText":"AbstractCaseAction","type":"variable"}]]
```

**Comment by jrieken** [comment]
What happens is that `abstract` is the best match and as long as you type a prefix of it it will be selected *unless* one of those prefixes has been used previously for another suggestion (`AbstractCaseAction` in this case) and that's what's happening here. 

@joaomoreno Not sure what you are expecting/suggesting

**Comment by joaomoreno** [comment]
I do understand why it happens, and I do not know what I'm suggesting either... 😕 But I don't expect the default choice to switch back and forth. Have you experimenting with only incrementing the focused index, and never decrementing it?

**Comment by jrieken** [comment]
Yeah, an experiment would be to stay on the last selected suggestion until a better (different) selected suggestion comes a long (or when it doesn't match anymore....)
