### ISSUE TITLE
Missing "focus" command to focus on the project

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#3968]
There's options for *View: Focus into Side Bar* and *View: Focus on Working Files*, but there isn't any option for *View: Focus into Open Project*. Please add this.

<img width="425" alt="screen shot 2016-03-10 at 9 33 58 am" src="https://cloud.githubusercontent.com/assets/466713/13676522/6a4932c6-e6a3-11e5-9f89-0c9855675ac9.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by bpasero** [comment]
You mean an action to focus the opened file in the editor?

**Comment by pcgeek86** [comment]
@bpasero Not exactly. I mean, set focus to the currently opened project in the Side Bar, instead of the `Working Files` section.

**Comment by bpasero** [comment]
View: Show Explorer (Cmd+Shift+E).
