### ISSUE TITLE
Tab close button left could overlay icon if present

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#39681]
Testing https://github.com/Microsoft/vscode/issues/39331

It is currently inserting a strange space at the left for no good reason if an icon is present.

<img width="79" alt="capture" src="https://user-images.githubusercontent.com/1931590/33609249-b4b31566-d9c7-11e7-9fbc-6a5a08e013b2.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/39603
