### ISSUE TITLE
VSCODE一打开就拓展宿主意外终止，删掉git文件夹也不行

### ISSUE THREAD

**Issue by chenxli** [Microsoft/vscode#39687]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cmake-tools-helper|mad|0.1.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
cmake-tools|vec|0.10.3

---

Steps to Reproduce:

1.only use it to compile one day ,and the second it started to show "拓展宿主意外终止" when I open it.
2.someone suggest me to delete to git in the D:/Microsoft VS code /resources/app/extensions/git, but still not successful.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please follow our suggestions when filing issues, with the current data we can not do anything
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

So more details. Reproducable steps please
