### ISSUE TITLE
Unexpected use of find clipboard on focus

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#39693]
Testing #39585

MacOS find clipboard gets activated when focusing the find widget.

* search in another program for "hello"
* open a file , go to an empty line or something
* press cmd+f3
* the find widget pops up empty
* click inside the find widget
* the search string gets populated with "hello" unexpectedly.

**Comment by wprater** [comment]
I'm curious why this is being filed as a bug? this is how I'd expect it to behave. 

https://github.com/Microsoft/vscode/issues/39585#issuecomment-349217426

**Comment by wprater** [comment]
as per https://github.com/Microsoft/vscode/issues/39609 all find inputs should be automatically populated with the global search buffer.  

for example, if Im to be in one workspace and cmd+e over highlighted text (places into global search buffer), Id expect to see this string in all my cocoa apps search input fields (Terminal, Safari, Chrome, etc.)

currently when I cmd+e to place in buffer in one workspace and then head to another to perform a find all, the input in the find all is not populated with the global search buffer as it should be.

**Comment by rebornix** [comment]
@wprater thanks for your feedback. I dropped my thoughts in https://github.com/Microsoft/vscode/issues/39422#issuecomment-349500651 , the global find clipboard works as you described. But for this command `Find Next Selection`, we may want to save the selection to global find clipboard as it's what the command asks for.

**Comment by melvin0008** [comment]
@rebornix we are currently saving the selection to the global find clipboard.

You may try this by selecting a text using Cmd+E and then switching the application and using Cmd + G to find in that application.

But I feel the bug here is when an empty line is clicked the find widget should not be populated to which I agree.

**Comment by melvin0008** [comment]
I will look into it and fix it

**Comment by alexandrudima** [comment]
I don't expect the search string to change on focus gain via mouse click. **I have not seen any application that changes the search text on focus gain via mouse click on OSX or any other OS**.

Here I do the steps I describe:
* search for "hello" in Chrome
* open VSCode
* press cmd+f3
* click in the search input
* it is unexpected that "hello" appears **when** clicking in there.

![kapture 2017-12-06 at 11 31 06](https://user-images.githubusercontent.com/5047891/33657273-1031a96e-da79-11e7-96a1-23cf0aa2de35.gif)

**Comment by rebornix** [comment]
@alexandrudima thanks, you are right. It should not be triggered by clicking. If `editor.find.globalFindClipboard: true` and the clipboard service is available (macOS), we read from the global find clipboard only when

* The cursor is not on a word and there is no selection, then users run Find (Cmd+F)
* Users run Find Next (Cmd+G, F3)
* Users switch from another application back to VSCode and the Find Widget is visible at the same time

Others work the same way as before.
