### ISSUE TITLE
VSCode: Incorrect syntax highlighting/coloring in js file

### ISSUE THREAD

**Issue by PhilRB** [Microsoft/vscode#39695]
- VSCode Version: Version 1.18.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Enter for following code into a js file:
```js
function foo(x, y){
    if(x < y || (x > (y))){
    }
    return 'of the jedi';
}
```

2. Observe that the syntax coloring from "< y || onwards is incorrect, and for any further methods/code added after this function. (variables/functions are colored green).

3. Delete the brackets inside the if(....){ expression.

4. You can see that the syntax highlighting was previously incorrect, now it is fixed.
![dllhost_2017-12-05_14-40-57](https://user-images.githubusercontent.com/33292978/33612933-148b16ca-d9cb-11e7-9992-5ab7e3bb33de.png)

[https://pasteboard.co/GWOw6gU.png](https://pasteboard.co/GWOw6gU.png)

Reproduces without extensions: **Yes**

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#549
