### ISSUE TITLE
Can I clean storage ~/Library/Application Support/Code/User/workspaceStorage on my macOS 10.13.1?

### ISSUE THREAD

**Issue by llv22** [Microsoft/vscode#39692]
- VSCode Version: 1.18.1
- OS Version: 10.13.1

Steps to Reproduce:

1. enter h~/Library/Application Support/Code/User/workspaceStorage on macOS
2. found the total size is about 4GB on disk

I installed visual code one from 1.0 to 1.18.1. I'm not sure if I can clean-up on disk to save space.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
All extension should be able to recreate their storage although they might answer some questions. @llv22 is there a folder that is especially big? Would be good to know if there is an extension leaving garbage behind.

**Comment by dbaeumer** [comment]
In general this dups https://github.com/Microsoft/vscode/issues/32461. Keeping open to find out if there are special extensions causing this.

**Comment by llv22** [comment]
@dbaeumer I found that all of large file on disk is generated by redhat.java, see https://marketplace.visualstudio.com/items?itemName=redhat.java. almost 4.0GB together, I manually clean them by analyzing the time of folder.
Do you have better suggestions to avoid such dirty work? thanks a lot ^_^

**Comment by dbaeumer** [comment]
We are looking into having a UI in VS Code to do the cleanup. The discussion about how to best do this is on #32461.

Thanks a lot for letting us know that the most storage was taken by the Java extension.
