### ISSUE TITLE
Syntax highlighting with JSX-Fragments broken

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#39694]
- VSCode Version: 1.19.0-insider 6bc5a14bf34e44b3af5508350cc1221fcc999ceb
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Create a `.tsx` file
2. paste this:
```tsx
const foo = <><p>Hello</p><p>World</p></>;
```
_Note:_ Requires `TypeScript >= 2.6.2`
_Note:_ The opening fragment tag (`<>`) is recognized as `invalid.illegal.tag.incomplete.tsx` as tm scope.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Not able to repo this:

![screen shot 2017-12-05 at 9 51 34 am](https://user-images.githubusercontent.com/12821956/33622171-e88e5600-d9a1-11e7-9099-70104cd1f9d3.png)

The document's language mode is `TypeScript React`? And this repos without any extensions enabled?

**Comment by marvinhagemeister** [comment]
@mjbvz Thanks for having a look at this! Turns out, that I had the `Latest TypeScript and JavaScript Grammar` extension installed which broke highlighting. Removing it fixed the issue for me. 👍

**Comment by mekwall** [comment]
Actually, it is broken without the extension as well. Here's an example where it gets totally borked:

![image](https://user-images.githubusercontent.com/37091/33714147-3bcf0320-db4e-11e7-86e7-1a2257af76a1.png)

Here's the code if anyone else want to try out:

```
import * as React from "react";

export default class App extends React.Component<{}, {}> {
    render() {
        const test: any[] = [];
        return (
            <>
                Highlighting does not work as expected with fragments.
                {Object.keys(test).map(key => {
                    return (
                        <p key={`date-${key}`}>
                            It's totally broken here.
                        </p>
                    );
                })}
            </>
        );
    }
}```

**Comment by marvinhagemeister** [comment]
@mekwall I can't reproduce this with latest insiders build. Works fine for me.
