### ISSUE TITLE
VSCODE调试，弹出窗口出现故障，没有办法弹出正常的窗口。

### ISSUE THREAD

**Issue by chenxli** [Microsoft/vscode#39691]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.14.3
cmake-tools|vec|0.10.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please follow our rules for filling issues and I will reopen
