### ISSUE TITLE
SCM view shows Source control providers from other workspaces

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39690]
Steps to reproduce:

- Open a Workspace with folders `vscode`, `vscode-distro` (Workspace 1)
- Open a new Window and add `vscode` and `vscode-distro` folders to the new window (Workspace 2)
- Workspace 2: Switch to SCM view, you see two repos 👍 
- Workspace 2: Switch to Explorer view, remove `vscode-distro` from the workspace
- Workspace 2: Switch to SCM view, you still see two repos 🐛

**Comment by joaomoreno** [comment]
I don't want to close repositories automatically... I leave it up to the user to close the repository in the SCM viewlet.

Workspace folders != repositories

**Comment by sandy081** [comment]
@joaomoreno But looks like you close the repositories if you have different folders in Workspace 2 and one of the folders is removed. Is there some inconsistency?

**Comment by joaomoreno** [comment]
@sandy081 Please check whether you had any open files from the removed folder.

**Comment by sandy081** [comment]
FYI, following is returning true 

```
function isParent(parent: string, child: string): boolean {
	return child.startsWith(parent);
}
```

**Comment by joaomoreno** [comment]
Repro steps: you need one folder to be the prefix of another. Eg:

- `/Users/joao/Work/vscode`
- `/Users/joao/Work/vscode-distro`
