### ISSUE TITLE
Activity bar: lots of time spend in layout when resizing explorer?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39699]
* open explorer and an editor
* resize explorer left/right for a couple of seconds

=> in the performance trace you can see lots of time is spend in the activity bar layout call
=> I wonder why, because resizing the explorer should not have any impact on the activity bar?

**Comment by isidorn** [comment]
@bpasero great find. I was unware that calling `.clientWidth` and similar are very expensive calls. Due to that the layout in the `activityBarPart`, `panelPart` and `repl` were expensive.

I have fixed all of this now by doing better caching.

**Comment by bpasero** [comment]
@isidorn cool! here is a full list of properties that - when accessed - will cause a relayout: https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by isidorn** [comment]
@bpasero thanks!
