### ISSUE TITLE
Feature Request: add a Structure Inspector for TS, JS

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode#397]
It would be really nice to have a tab showing a hierarchy tree of all used/available namespaces,classes, objects, generics, interfaces, functions etc.

Thank you for your time and to Microsoft for this brilliant gift to Node/JS/TS community.

-- RM

**Comment by fantacytyx** [comment]
@egamma When will develop this feature？

**Comment by RobertoMalatesta** [comment]
On some projects where LOC > 10k and with 50+ files and classes, it is a serious drawback.

File Explorer is very basic and gets clobbered quickly.

Having a tab (on the right of screen) listing all entities at least for Typescript and .d.ts definitions would allow a smarter navigation inside the code.

Tsc compiler API should be able to provide it:
https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

And *no*, I don't think it should be a plugin, but a permanent inbuilt feature of VSC.

-- RM

**Comment by egamma** [comment]
@fantacytyx  currently this item is on the backlog and has no planned date, sorry.

@RobertoMalatesta did you try the `Open Symbol by Name` action (typing # in the command palette followed by the symbol name).

**Comment by RobertoMalatesta** [comment]
To use  ^P# when you're already knowing what you're looking for. 
Its interaction is less immediate than a toggable right column that starting from tsconfig.js lists all symbols in a tree. The latter is a birdseye view and inspector of the whole project structure. With that you can visually click-inspect an review the shape itself and the functionalities of the Project.
Much like any C++ Editor/Rad has for C/C++ 

>> @fantacytyx currently this item is on the backlog and has no planned date, sorry.

Is this feature really in the backlog with no planned date?
The lack of this and of some more effective file manager is a showstopper to VSC adoption on large projects then.
