### ISSUE TITLE
Add option to collapse all comment blocks

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#39704]
- VSCode Version:  1.18.1
- OS Version: Windows 10

This is a feature request.  Some developers can get a little excessive with JSDoc comments, which can destroy the flow of the code, making it hard to read.  Some sort of option / ability to auto-collapse all comment blocks on a page would be incredibly helpful.

I looked, and couldn't find any existing option, or even a plugin for this, so apologies if I missed it.

**Comment by aeschli** [comment]
Duplicate of #11524, fixed in 1.19

**Comment by arackaf** [comment]
@aeschli sweet!  Thanks!  I assume 1.19 will be coming in early January??

**Comment by aeschli** [comment]
@arackaf Should be out in about a week
