### ISSUE TITLE
Improve UI that prevents user from starting debug session multiple times

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#39707]
While verifying #37507:

Trying to launch the same session twice through the statusbar results in a Quickpick drop down where I can still select the same launch config but nothing happens.

Trying to do the same with the debug drop down gives no feedback either (but at least there is no selection feedback).

I suggest to show an alert in both cases.

In the future we could even consider to have an option to allow multiple sessions for the same config.

**Comment by isidorn** [comment]
I use the following wording 
There is already a debug configuration "Launch Program" running.

**Comment by misolori** [comment]
Verified
![image](https://user-images.githubusercontent.com/35271042/41999907-e57275ba-7a13-11e8-9ca3-a2c670b929b4.png)
