### ISSUE TITLE
"[js] Invalid character." for private class fields

### ISSUE THREAD

**Issue by errorx666** [Microsoft/vscode#39703]
- VSCode Version: 1.19.0-insider
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open or create a JS file
2. Paste in the example code from https://github.com/tc39/proposal-class-fields#private-fields
```js
class Counter extends HTMLElement {
  #x = 0;

  clicked() {
    this.#x++;
    window.requestAnimationFrame(this.render.bind(this));
  }

  constructor() {
    super();
    this.onclick = this.clicked.bind(this);
  }

  connectedCallback() { this.render(); }

  render() {
    this.textContent = this.#x.toString();
  }
}
window.customElements.define('num-counter', Counter);
```
3. Observe `#` characters are marked as invalid

Reproduces without extensions: Yes

**Comment by maxibanki** [comment]
This isn't integrated into the JavaScript standard ECMA Script yet:
> Private class fields are now at Stage 2 in the JavaScript standard process. It's not finalized yet, but the JavaScript standards committee expects the feature to be developed and eventually included in the standard (although it may still change). [Source](http://thejameskyle.com/javascripts-new-private-class-fields.html)

> Paste in the example code from https://github.com/tc39/proposal-class-fields#private-fields

Your linked page is only a proposal, not a standard.

**Comment by errorx666** [comment]
@maxibanki They are at stage-3, which means they are ready for implementation by user-agents.  I'm not experiencing any errors with other stage-3 proposals in VSCode right now.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/9950
