### ISSUE TITLE
Minimap: always show all lines from document regardles of code folding

### ISSUE THREAD

**Issue by CzBuCHi** [microsoft/vscode#39700]
I usually fold all code that im not currently working on so it not distracting me - but that will also remove it from minimap preview ...
O would like to see that code in minimap (maybe with diff back color like VS) so i can identify parts of folded code, that needs closer look without need to unfold all and then fold back uninteresting parts...

**Comment by DanielAsher** [comment]
This would make the minimap feature much more useful.
