### ISSUE TITLE
Filter out --status process when running in Integrated Terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#39709]
Re #39376 

`code --status` process is "fire and forget" so maybe we can filter out it and its children when running the command in Integrated Terminal.

Feel free to close it as I'm simply expecting the same result when running in external/internal terminal.

**Comment by bpasero** [comment]
It's a good idea but I see no straight forward way how to exclude that process from the list. I also see no harm in showing it actually.
