### ISSUE TITLE
--status detect process for extension debugging

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#39711]
Re #39376

```
    0	   229	   window (Welcome — vscode-vs-keybindings)
    0	    49	     watcherService
    0	    49	     terminal
    0	     0	       /bin/zsh -l
    0	   213	     extensionHost
    0	    66	       electron_node jsonServerMain.js
    0	    49	     searchService
    0	    49	     /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap ms-vscode.extensionHost {"common.vscodemachineid":"xxxxxxxx","common.vscodesessionid":"xxxxxxx"} xxxxxx    
    0	   131	     electron_node stdForkStart.js nodeDebug.js
    7	   328	   window ([Extension Development Host] - main.ts — vscode-ruby)
    0	    33	     terminal
    0	     0	       /bin/zsh -l
    0	    49	     watcherService
    0	   213	     extensionHost
    0	   147	       electron_node electronForkStart.js tsserver.js
    0	    49	         electron_node typingsInstaller.js
    0	    49	       electron_node server.js
    0	    66	       electron_node jsonServerMain.js
    0	    49	     searchService
```

* We may want to give `/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap ms-vscode.extensionHost` a proper name
* We may want to hide machine id.

**Comment by bpasero** [comment]
I see this only when starting to debug (e.g. an active debug session). Not sure we should treat this any special.

**Comment by weinand** [comment]
Yes, we should detect and properly label debug adapters.

**Comment by ramya-rao-a** [comment]
@weinand Is this still meant for the January milestone? If not, can you move it to February milestone?

**Comment by ehausen** [comment]
Is this implemented?

**Comment by weinand** [comment]
@ehausen VS Code supports a `--status` option but debug adapters are not detected as such and just appear like any other process.

**Comment by ehausen** [comment]
`code --status`
Currently only outputs
```
CPU %	Mem MB	   PID	Process
    4	    61	 75035	code main
    0	    20	 75036	   gpu-process
    0	    41	 75249	   shared-process
```
shouldn't there be some more info?

**Comment by weinand** [comment]
Do you have a VS Code window open?
"code" by itself doesn't have more processes.

**Comment by ehausen** [comment]
I have it open.

I already had in running in window, then installed the _code_ in my path.
Then ran command `code --status` without closing the VS Code window. 
I have many extensions.

**Comment by weinand** [comment]
Individual extensions are not showing up as processes because they all share a single extension host process (per window).
Here is an example for the "--status" output if a single VS Code window ("simple.js") is open:
```
Version:          Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS Version:       Darwin x64 18.2.0
CPUs:             Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)
Memory (System):  32.00GB (0.20GB free)
Load (avg):       2, 2, 2
VM:               18%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %	Mem MB	   PID	Process
    1	    98	 18452	code main
    0	    66	 18453	   gpu-process
    1	    98	 18651	   shared-process
    0	   295	 18733	   window (simple.js — simple)
    0	     0	 18734	     /bin/bash
    0	    98	 18775	     extensionHost
    0	   131	 18903	       electron_node tsserver.js
    0	    98	 18925	         electron_node typingsInstaller.js typesMap.js
    0	    33	 18927	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=18775
    0	    33	 18874	     watcherService
Workspace Stats:
|  Window (simple.js — simple)
|    Folder (simple): 17 files
|      File types: js(10) json(5) txt(1) java(1)
|      Conf files: jsconfig.json(1) package.json(1) launch.json(1)
|                  settings.json(1)
|      Launch Configs: node(13)
```

BTW, VS Code has a dynamically updating view for the same information, just use the "Open Process Explorer" action from the bottom of the Help menu:

![2019-01-11_15-09-40](https://user-images.githubusercontent.com/1898161/51038250-ef9e4600-15b2-11e9-9a7f-bcaae4d462a6.png)

**Comment by ehausen** [comment]
Also my Process explorer looks like this:
![screen shot 2019-01-11 at 15 38 46](https://user-images.githubusercontent.com/6204129/51038365-b0282780-15bb-11e9-91a9-5b55cce81423.png)

How do I "expand" the shared process to show sub process?

**Comment by ehausen** [comment]
in Activity monitor I get this. Does it mean I found a bug?
![screen shot 2019-01-11 at 17 28 29](https://user-images.githubusercontent.com/6204129/51043057-6c86eb00-15c6-11e9-9e42-76ab8934e4aa.png)

Unfortunately I don't seem to have a way to log which extension is using all the CPU sometimes.

**Comment by weinand** [comment]
Yes, that looks like a bug. I suspect that we stumble over your number/time/date formatting (e.g. comma instead of '.').
You can try to temporarily set your number/time/date formatting to US and see whether this makes a difference.

BTW, please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for how to track and report performance issues.

**Comment by ehausen** [comment]
setting date, etc to US format made no difference.

I have created issue at: https://github.com/Microsoft/vscode/issues/66400

**Comment by danger89** [comment]
https://github.com/microsoft/vscode/issues/66224 ISSUE IS NOT SOLVED!

Its a big performance issue. I also randomly suffer from the `/usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=watchService` that is not only using a lot of CPU. But mainly causing a lot of IO on my disk, which sometimes even lead to a non-working computer (lock-ups). :fearful:

**Comment by juandetoro** [comment]
are the issue solved?

**Comment by yanlee26** [comment]
So when will solve?

**Comment by Delagardi** [comment]
Hey
any updates?

**Comment by weinand** [comment]
I do not see anything that needs to be done here.
