### ISSUE TITLE
Cannot copy without line numbers

### ISSUE THREAD

**Issue by Hongbo-Miao** [Microsoft/vscode#39716]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1

## Steps to Reproduce:
After updating to VSCode 1.81.1.
Every time when I paste the code, it always includes line numbers after copying from VSCode.

    39	  // demo
    40	  let a = 1;
    41	  a = 2;
    42	  a = 3;

I reinstalled VSCode and the issue was gone.
But I were happy too early, the issue was back on second day.

## Launch with `code --disable-extensions` to check

When I run 
```bash
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-extensions
```
The issue is gone.
However, I never installed any extension before:

![image](https://user-images.githubusercontent.com/3375461/33626173-a2aaea38-d9ae-11e7-880c-f720c19d2ef4.png)

**Comment by rebornix** [comment]
@Hongbo-Miao do you mind sharing a gif to help troubleshoot, especially with below info

* Do you do copy in VSCode? If not, where?
* Do you paste it in VSCode editor? If not, which application are you pasting into?

**Comment by Hongbo-Miao** [comment]
Oh, I will try to capture a GIF if I see it again, I just reinstalled it because I need get my work done.
I am copying from VSCode to Word.

**Comment by Hongbo-Miao** [comment]
Cannot reproduce any more... I will reopen if I saw it again.
