### ISSUE TITLE
Add "Edit breakpoint" to breakpoint view context menu

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39714]
Testing #39099 

Steps to Reproduce:

1. Create a breakpoint in a node program
2. In breakpoint view, right click on that breakpoint

**Feature Request**
Add a context menu item that triggers edit on that breakpoint

<img width="369" alt="screen shot 2017-12-05 at 10 55 21 am" src="https://user-images.githubusercontent.com/12821956/33625065-4677a330-d9ab-11e7-96ee-6a06272c8646.png">

**Comment by isidorn** [comment]
@mjbvz and what would that edit action do exactly?
Open the editor, find the breakpoint and trigger the edit experience for the condition? It is too disconnected from the view UX thus I am not a big fan of this

**Comment by mjbvz** [comment]
Yes, something like that flow sounds like my expectation. I think this can help with discoverability of conditional breakpoint support

**Comment by isidorn** [comment]
Why the hell not, you can always convince me with discoverability.
Please verfiy this works as expected
