### ISSUE TITLE
Clicking on staged new image opens a new editor without icon

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39710]
- VSCode Version: Code - Insiders 1.19.0-insider (8a12b294de610aab61c32c02c7c148d981cf07e4, 2017-12-04T05:14:19.063Z)
- OS Version: Windows_NT x64 10.0.17052
- Extensions: 

Testing #39583

---

Steps to Reproduce:

1. Stage new image
2. Double click on staged image

Reproduces without extensions: Yes

**Problem**

The new editor tab has no icon and a weird data uri path. 

![a](https://user-images.githubusercontent.com/12821956/33623055-96c60fcc-d9a4-11e7-9347-869dfbbcf016.gif)

**Comment by joaomoreno** [comment]
@bpasero It's a `git:` resource, but the file extension is there.

**Comment by bpasero** [comment]
Yeah this is a consequence of using a data URI that does not end with a proper file extension and so our icon label cannot find a suitable extension. 

Currently no plans to fix this.
