### ISSUE TITLE
search box showing cached results?

### ISSUE THREAD

**Issue by andycmaj** [Microsoft/vscode#39717]
- VSCode Version: insiders 1.19.0
- OS Version: osx high sierra

Steps to Reproduce:

not sure how to repro but this is the result:

![vscode search weirdness](https://user-images.githubusercontent.com/97470/33626841-9a2a31dc-d9b0-11e7-866f-52ff10d02c08.gif)

Reproduces without extensions: not sure... after opening the files that had wrong search results, no longer see the results, not sure how to repro.

**Comment by roblourens** [comment]
Are the wrong results always from files that are open? What caused the change in the files? 

My guess is that the file watcher didn't pick up the changes. And when files are open, we get search results from what vscode has in memory for that file, not what's currently on disk.
