### ISSUE TITLE
Double click in Debugger watch panel should trigger new watch UI

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#39719]
Setting new watches in the Debugger watch panel requires you to click the tiny plus icon. We should    make it easier to set new watches.

My proposal is to make double clicking inside the blank area of the watch panel trigger "add new watch" just like if you had clicked on the plus icon.

**Before:**
![doubleclick](https://user-images.githubusercontent.com/173559/33627049-2b484b36-d9b1-11e7-8e93-d8461a4103d7.gif)

**After:**
![doubleclick_2](https://user-images.githubusercontent.com/173559/33627053-2e16f15a-d9b1-11e7-894b-3ef71de03161.gif)

**Comment by auchenberg** [comment]
@isidorn I can verify in tomorrows build?

**Comment by isidorn** [comment]
@auchenberg you can verify in the insiders from Friday, since until then we keep insiders frozen so our insiders community can test out the bits we plan to ship as stable.
If you want to verify right away you can run vscode out of source.
