### ISSUE TITLE
code --status hangs while open file dialog is open

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39729]
- VSCode Version:
- OS Version:

Testing #39376

**Steps to Reproduce:**

1. In code inside, open system file browser
2. Run `code --status` from another command line

**Bug**
`code --status` is blocked until the file explorer is closed. Same happens for modal alerts

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Interesting. This seems like a general problem with our IPC communication on startup. I can reproduce like this easily:
* start code
* from the CLI run "code <some folder>"

=> the folder will not open

**Comment by bpasero** [comment]
Marking as duplicate of https://github.com/Microsoft/vscode/issues/39536

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/40211
