### ISSUE TITLE
Test task for Windows console program fails unless the task is of type shell

### ISSUE THREAD

**Issue by 0xabu** [Microsoft/vscode#39720]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions:  (I disabled all extensions in this workspace.)

---

I have the world's least interesting win32 console application:
```
#include <windows.h>
#include <stdio.h>

int
__cdecl
wmain(
    _In_              int     argc,
    _In_reads_(argc)  LPCWSTR argv[]
    )
{
    wprintf(L"Hello world\n");
    return 0;
}
```
(This was built with msbuild in debug mode as an x64 binary against the latest Windows SDK, but I doubt it matters.)

I also have a test task that should run it and display the output:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "test",
			"group": {
				"kind": "test",
				"isDefault": true
			},
			"command": "x64/Debug/demo.exe",
			"type": "process",
			"presentation": {
				"reveal": "always",
				"focus": true,
				"panel": "new"
			},
			"problemMatcher": []
		}
	]
}
```

The first time I run this task, it launches, but produces no output and never terminates, although the process it spawned, if any, is long gone.

Attempting to start a new instance of the task fails because it says I need to terminate the existing one. After doing that in the UI, (tasks: terminate menu), the task still shows as running, but now I can try to start a new one. That results in the error "Terminal with ID *N* does not exist (has it already been disposed?)". (I've seen N = 1, 2, or 3 thus far.) This seems related to Issue #31737

Invoking this task either from the builtin shell (e.g. the default powershell), or by changing "type" to "shell" in `tasks.json` works fine, e.g.:
```
> Executing task: x64/Debug/demo.exe <

Hello world
```

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This works for me make sure two things:

- the command uses `\` instead of `/`. Since this is a Windows process `\` will not work
- the path is absolute. I need to see why a relative path is not working. It should

We know about a problem in the terminal system that if a process can't be found the terminal doesn't correctly signal this. We have an issue for this.

**Comment by 0xabu** [comment]
Thanks for the suggestions. The problem was the relative path. I was able to get it to work using:
```
"command": "${workspaceFolder}/x64/Debug/demo.exe",
```
(either forward or backslashes work fine).

I'd suggest there are two bugs here:
1. Relative paths ought to work
2. A non-existent executable (or other errors from CreateProcess) ought to be reported as such and not wedge the task in this intermediate semi-started state. I was able to recreate this using ```"command": "c:/nonexistent.exe"``` which presumably should be an easy error to catch.

**Comment by dbaeumer** [comment]
Agree, and this what I described in my comment. For 2 we have an issue already for 1 I will use this one.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/tree/dbaeumer/39720. Will be merged after current endgame.

**Comment by dbaeumer** [comment]
Has to wait for Feb. Was busy with LP

**Comment by dbaeumer** [comment]
Merged the fix into master.
