### ISSUE TITLE
`code-insider --status` starts app when none is running

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#39722]
While testing #39376.

- VSCode Version: Code - Insiders 1.19.0-insider (6bc5a14bf34e44b3af5508350cc1221fcc999ceb, 2017-12-05T06:08:29.821Z)
- OS Version: Darwin x64 16.7.0

1) close all instances of vscode
2) `code-insiders --status` 
-> warning is printed, app starts, shell script keeps running
Expected: warning is printed, shell scripts finished

**Comment by bpasero** [comment]
Pushed a change to just quit the app if you run it with "--status" and it is not running yet. The other thing that was suggested cannot easily be done because at the time the CLI script starts we do not know yet if Code is running or not.
