### ISSUE TITLE
Find widget does not show what is being searched for.

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#39726]
Testing #39585.

1) Search for "browser" in Safari
2) Got to VS Code
3) <kbd>Cmd+G</kbd>
-> find widget is shown but does not contain "browser" however all occurrences of "browser" are highlighted in the editor.

**Comment by rebornix** [comment]
![cmdg](https://user-images.githubusercontent.com/876920/33640135-9cc9fc46-d9e3-11e7-8e0c-bf2327417df8.gif)

@kieferrm I didn't reproduce this issue, any missing step in above gif?

**Comment by kieferrm** [comment]
After some experimentation, we figured:
- When you restart vscode and don't search in any editor before you do <kbd>Cmd+G</kbd> coming from another app the find widget is not populated correctly.
- If you search before you use <kbd>Cmd+G</kbd> coming from another app the find widget populated correctly.
