### ISSUE TITLE
stopOnEntry

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#3972]
Should we support this at some point:

**Stop at Entry**
Setting the stopAtEntry flag will cause the debugger to break immediately on the entry point to the application. This allows you to start stepping through your code without setting breakpoints.

**Comment by weinand** [comment]
@rkeithhill I think 'yes', but that's your decision. 'Stop on entry' is nothing that the VS Code debugger UI or the debug protocol prescribe.

**Comment by rkeithhill** [comment]
@weinand  Sorry man.  That was meant for the PowerShell/vscode-powershell repo.  Doh!

**Comment by weinand** [comment]
@rkeithhill no worries ;-)
