### ISSUE TITLE
Node.js debug always uses 'legacy' on the first run

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39723]
- Open any node app
- Set `"protocol": "inspector"`, and debug
- See it launch with "legacy"
- Start debug again
- See it launch correctly with "inspector"

This doesn't happen when I start node-debug in the extension dev host. I attached to the actual extension host and what I see is, I start the debug session, then node-debug is activated, but the config provider is not invoked. On the second launch it is invoked. Related to `"onDebugResolve:node"`?

**Comment by isidorn** [comment]
Getting the timing right of this activation event proved to be quite a tedious effort.
In the third try I think I got it right.
There was one case I was missing which you nicely uncovered in this issue

**Comment by dbaeumer** [comment]
Verified that the process is started with --inspect-brk.
