### ISSUE TITLE
Temporary files created for stdin, when started without TTY

### ISSUE THREAD

**Issue by aniljava** [Microsoft/vscode#39728]
https://github.com/Microsoft/vscode/blob/a90eaf59e2ee2ea6605bf484d857d554ec35688e/src/vs/code/node/cli.ts#L88

Test case:
Execute visual studio code using any OS keyboard shortcuts such as xbindkeys, xfce4 keyboard shortcuts. A temporary file is created with following output in verbose:

    Reading from stdin via: /tmp/stdin-hsyxsk.txt

xbindkeys and xfce executes without a TTY attached, making vscode to believe there is a stdin to read from, which is not the case.

**Comment by bpasero** [comment]
@aniljava can you explain why these tools execute our command line script when they should execute our executable directly? Did you configure this maybe to execute the CLI script?

**Comment by mac-pro** [comment]
@bpasero 

I'm not sure if you need my info. In my case the Xfce shortcuts can be set via a dialog:

- I entered the short `code` command and saved.
- From desktop, pressed the shortcut.
- The system called `/usr/bin/code` and it reproduced this bug (on 1.19.0, commit 816be6780ca8bd0ab80314e11478c48c70d09383).

I changed the shortcut command to `/usr/share/code/code` and it worked correctly.
