### ISSUE TITLE
When "save file" dialog pop-up, I would like to push "space" for "do not save" button

### ISSUE THREAD

**Issue by pycckuu** [Microsoft/vscode#39735]
- VSCode Version: 1.18.1 
- OS Version: MacOs High Sierra

Steps to Reproduce:

1. Create file
2. hit save it
3. There is no available shortcut for "do not save"

Reproduces without extensions: Yes

When I save the file, I would like to have an option for pressing "Enter" to save file and pressing "Space" for discard changes or "do not save". I have this option in other editor and it is very convenient.

Thanks

**Comment by bpasero** [comment]
@pycckuu this is entirely up to macOS to support. You can enable keyboard access for dialogs on this system preferences page:

![image](https://user-images.githubusercontent.com/900690/33647959-e1d6739a-da57-11e7-8f15-4b4439973913.png)
