### ISSUE TITLE
command key vs hover

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#39739]
version 1.18.1 OSX
Could be golang plugin specific but I think it will be for all plugins. 

Hovering over a function will give you the definition of the function but when still hovering and keep pressing the command key at the same time will open the definition twice stacked. It should detect if the definition popup is already open.

Also there is no way to scroll a large definition popup when holding command button

**Comment by joaomoreno** [comment]
Yeah that's Go. Here's TypeScript as an example:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/22350/33659817-eb737a2c-da81-11e7-8260-08b5f7489c2f.png">

**Comment by ramya-rao-a** [comment]
@joaomoreno This is not Go specific. Even in typescript, on hover you see function definition and docs. Cmd/Ctrl when hovering, adds a new section above the existing hover section. The new section peeks into the function definition

**Comment by joaomoreno** [comment]
> Hovering over a function will give you the definition of the function but when still hovering and keep pressing the command key at the same time will open the definition twice stacked. 

The hover widget gives extensions two views to render stuff in. The user mentions that Go repeats information on both views. TypeScript doesn't seem to repeat it: it uses the first for the symbol's declaration and the second one for the its definition.

If there's no change in Go, I will simply close this.

**Comment by gertcuykens** [comment]
PS I will create a new one specifically for the `not able to scroll` issue on command key hover

**Comment by ramya-rao-a** [comment]
> The user mentions that Go repeats information on both views. 

The 2 just look similar, but they are not. So am ok with closing it. Thanks for the clarification.
