### ISSUE TITLE
Can't open files using VS Code when already one instance is running

### ISSUE THREAD

**Issue by kiluavineeth** [Microsoft/vscode#39736]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.3.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
search-node-modules|jas|1.2.0
vscode-stylefmt|mrm|2.5.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
stylelint|shi|0.31.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1. Open Visual studio code.
2. Now Go to desktop and select any *.js file => right click => Open With => Select VS Code to open it. It will not be opened in Visual Studio code.

**Comment by bpasero** [comment]
@kiluavineeth does an uninstall and reinstall of VS Code fix this?
