### ISSUE TITLE
Opening a new file replaces other currently open

### ISSUE THREAD

**Issue by joa-quim** [Microsoft/vscode#39732]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Somewhat recently VSC has started an extremely annoying behavior where when I open a new file from workspace it replaces the one that was previously active. This is so annoying that I'm resisting quit using VSC altogether.

**Comment by bpasero** [comment]
@joa-quim does it get better if you configure `"workbench.editor.enablePreview": false` ?

**Comment by joa-quim** [comment]
Yes, it did, now it works. Thanks. But it's still strange because the
behavior that I described doesn't occur all the times. I have Editors where
it happens and others where not and it remembers about that because closing
and reopening makes no difference.

**Comment by bpasero** [comment]
@joa-quim well as soon as you start typing in the file or you double click the file to open, we will not open it as "preview" and instead keep it around. That is probably what you were seeing.
