### ISSUE TITLE
Git clone prompt should handle ~

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39738]
Given https://github.com/Microsoft/vscode/issues/31878, I should be able to 

- Run `Git: Clone`
- In parent directory prompt, enter `~/foo`
- Get popup `Git: EACCES: permission denied, mkdir '~'`

**Comment by ampzord** [comment]
@joaomoreno Hasn't this issue been solved before ? https://github.com/Microsoft/vscode/pull/32222
If it hasn't I'll try to fix it.

**Comment by joaomoreno** [comment]
@ampzord Actually it seems the current solution can only handle `~` in the config setting... but not in the input box!

**Comment by pfongkye** [comment]
@joaomoreno hello
I could take a look at the issue if no one is already assigned. It would be my first one.
Regards,
Pascal.

**Comment by pfongkye** [comment]
Hi @ampzord, let me know if you're working on the issue. I think I've found a solution.

**Comment by ampzord** [comment]
go for it @pfongkye !
