### ISSUE TITLE
code --status should display (1) next to file types with only a single occurrence in the workspace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39730]
**Bug**
Super nit-picky but when a workspace contains a single file of a given type, we should display `(1)` next to it as we do for other file-type counts. Currently the count is omitted if there is only one file (see `ts` in the second workspace folder):

![screen shot 2017-12-05 at 1 42 42 pm](https://user-images.githubusercontent.com/12821956/33632389-593c29fc-d9c2-11e7-9aa8-b22d621e11e3.png)

**Comment by bpasero** [comment]
@mjbvz where exactly?

**Comment by mjbvz** [comment]
In the `test2` folder info under `File types`. I think that line should instead read:

```
File types: ts(1)
```
