### ISSUE TITLE
Don't print stack when cancelling CLI extension install

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39733]
- VSCode Version: Code - Insiders 1.19.0-insider (6bc5a14bf34e44b3af5508350cc1221fcc999ceb, 2017-12-05T06:08:29.821Z)
- OS Version: Darwin x64 17.2.0
- Extensions: the listing length exceeds browsers' URL characters limit

![image](https://user-images.githubusercontent.com/323878/33633955-6e8e7a9e-d9c7-11e7-87b2-499521ba18a2.png)

**Comment by joaomoreno** [comment]
This is fixed.
