### ISSUE TITLE
Debug config status bar item is only visible after the first launch

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39746]
This: ![image](https://user-images.githubusercontent.com/172399/32650233-4e0a6522-c5fd-11e7-99d9-4ec0704fbba7.png)

Seems like it should be visible whenever the workspace has a launch config.

**Comment by isidorn** [comment]
There is a configuration you can change 
	"debug.showInStatusBar": "always"

Closing as desgined
