### ISSUE TITLE
Disable smooth scrolling in the webview

### ISSUE THREAD

**Issue by theFroh** [Microsoft/vscode#39745]
- VSCode Version: 1.19.0-insider 6bc5a14bf34e44b3af5508350cc1221fcc999ceb
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. In user settings, set "editor.smoothScrolling" to false.
2. Observe that scrolling in the settings, and in code is correctly not smoothed.
3. Open the extensions sidebar and click an extension to open its Marketplace page.
4. Assuming the extension has a readme that is long enough to permit scrolling, observe that the scrolling is smoothed.

Expected Behaviour:

Disabling smooth scrolling disables it application-wide.

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Looks like the request is to support smooth scrolling across application.

**Comment by bpasero** [comment]
This probably has to do into the list/tree widget.

**Comment by joaomoreno** [comment]
@bpasero This clearly has nothing to do with the list/tree widget; the user is referring to the webview... cc @mjbvz 

@theFroh Note that the setting starts with `editor.`, so it only applies to the editor.

**Comment by bpasero** [comment]
I am clearly sorry for the inconvenience I caused...

**Comment by theFroh** [comment]
@joaomoreno Good call mate, I didn't connect 'editor' specifically to the text editing views.

I suppose I was referring more to this behaving like the --disable-smooth-scroll flag (which I've tested anyhow, knowing that it'd not work due to the way views work here).
