### ISSUE TITLE
automatic imports break when using flow type imports

### ISSUE THREAD

**Issue by jlyons-bgl** [Microsoft/vscode#39743]
- VSCode Version: 1.18.1
- OS Version: macOS 10.12.6

The new automatic import feature is great! but I have an issue when using it with Flow.

starting with:
```
import { TAccount } from './TAccount'
import type { SimilarTransactionJson, TAccountJson } from '../../types/BankingTypes'
```
and selecting an auto import intelisense option I end up with:
```
import { TAccount } from './TAccount'
import typeimport { Entry } from './Entry';
 { SimilarTransactionJson, TAccountJson } from '../../types/BankingTypes'

```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Yes, we don't provide built-in support for flow and cannot guarantee that our built-in js language support will not break flow specific syntax like `import type`. You can disable auto imports by setting: `"typescript.autoImportSuggestions.enabled": false` if this feature is getting in the way
