### ISSUE TITLE
'Open To The Side' button in main workbench.

### ISSUE THREAD

**Issue by anurag2361** [Microsoft/vscode#39744]
- VSCode Version: 1.18.1
- OS Version: Windows 10

It would be really helpful if you can add an 'Open To The Side' button in workbench tabs. Currently, i can only open a file on a side tab by going in the Explorer list view and right clicking the desired file. If you can just add the option to open it through tab on the workbench too, it would be really helpful to me and would save me from opening the explorer again and again. Just like Visual Studio's 'Open Vertical Tab Group' button.

**Comment by bpasero** [comment]
You can click on the "Split Editor" icon to the right of the tabs:

![image](https://user-images.githubusercontent.com/900690/33647981-00f8690e-da58-11e7-8cb7-f84b47a9409e.png)
