### ISSUE TITLE
After disabling Markdown security warnings, I can't change the markdown security policy

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39740]
Testing #32251

- Open markdown preview with disabled content
- Click warning
- Disable warnings
- Run command `Markdown: Change Preview Security Settings`
- Nothing happens :bug:

I should still be able to change it manually.

**Comment by mjbvz** [comment]
Sounds like a duplicate of #39387. Can you please try switching back to the markdown editor and see if the commands work then

**Comment by roblourens** [comment]
Oh yeah, I guess so
