### ISSUE TITLE
Suggestion details become hidden when suggestion results become frozen

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39742]
Same repo as #37367

1. Open a js file.
2. Type out `fffee`
3. See in the suggestions

    ![screen shot 2017-12-05 at 3 59 12 pm](https://user-images.githubusercontent.com/12821956/33637336-42bb6bf8-d9d5-11e7-9e33-81dcff16604e.png)

1. Make sure details are expanded
1. Now with the suggestions still showing, type a `v`

**Bug**

The suggestions details are lost

![screen shot 2017-12-05 at 3 59 43 pm](https://user-images.githubusercontent.com/12821956/33637352-5ba52fb4-d9d5-11e7-9525-78e9464f73f6.png)

You also cannot re-expand the suggestion details from this state by clicking on the `i`:

![screen shot 2017-12-05 at 4 00 32 pm](https://user-images.githubusercontent.com/12821956/33637371-73e01580-d9d5-11e7-9ed3-93be45ae5462.png)

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
That decision is being made in the suggest widget itself: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L705
