### ISSUE TITLE
Support angle brackets in launch.json

### ISSUE THREAD

**Issue by donfiguerres** [Microsoft/vscode#39748]
Some of the cmd tools I maintain support angle brackets as symbols for 'greater than' and 'less than' filters. These can be escaped in the cmd using ^ but I can't find a way to use the angle brackets in vscode.

- VSCode Version: 1.18.1
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Add an angle bracket argument.
![image](https://user-images.githubusercontent.com/12525903/33640923-4db5288e-da6e-11e7-9602-d8b6a0c1b85e.png)

2. Check if the the angle bracket is included in the arguments passed to the program.
![image](https://user-images.githubusercontent.com/12525903/33640982-9082bb0e-da6e-11e7-9f7d-9dc999448ea7.png)

Reproduces without extensions: Not sure, but I do need the vscode-cpp extension for debugging

**Comment by sean-mcmanus** [comment]
I don't believe this is caused by the cpptools extension. Looks like the bot should reopen this.

**Comment by sean-mcmanus** [comment]
Actually, looks like our extension might be the cause...
