### ISSUE TITLE
Add copy context menu action to REPL

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#3974]
Could you please add a copy button? Also trying to select some text, and scrolling to finish the selection, and then copying it doesn't seem to do what I'd expect it to do.

**Comment by isidorn** [comment]
When you say copying it you mean pressing <kbd>ctrl c</kbd>? On what vscode version are you?
You would like a copy button in the context menu?

Also be aware of this limitation https://github.com/Microsoft/vscode/issues/2163

**Comment by digeff** [comment]
@isidorn Yes, what I'm reporting is related to the "virtual view". My suggestions are:

1. If you are using a virtual view you should use a virtual caret, so the virtual view is indistinguishable from a real view. 
2. It'd be nice to have a Copy button, like you have for output channels

**Comment by isidorn** [comment]
1. already captured in #2163
2. changed the title of this issue to reflect this flaw
