### ISSUE TITLE
trimFinalNewlines clobbers undo history

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#39750]
- VSCode Version: 1.18.1

Steps to Reproduce:

1. Settings:
{
	"files.trimFinalNewlines": true
}
2. Open a file. Type something. Undo. Save.
3. Note that Redo doesn't work, even though no newlines were trimmed.
(Even if it did trim newlines, is it friendly to clobber the undo history anyway? Hmm...)

trimTrailingWhitespace doesn't have this problem, despite its similar functionality.

Note that with "autosave after delay" on, trying to redo anything is effectively toast.

Reproduces without extensions: Yes

**Comment by AiryShift** [comment]
I'll have a look at this since I was the one who wrote the code in the first place, my bad. Should I look to use `executeEdits` instead of `pushEditOperations`?
