### ISSUE TITLE
El editor inicia pero no se puede ver nada, aparece todo negro

### ISSUE THREAD

**Issue by elultimocapo421** [Microsoft/vscode#39754]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|0.1.3
jsrefactor|cms|2.1.2
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
es7-react-js-snippets|dsz|1.2.0
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
php-pack|fel|1.0.1
jsx-beautify|gog|0.0.5
useful-react-snippets|igo|1.2.2
csharpextensions|jch|1.3.0
react-component|jer|1.0.1
vscode-language-babel|mgm|0.0.10
code-beautifier|mic|1.7.2
atom-keybindings|ms-|3.0.2
csharp|ms-|1.13.1
node-debug2|ms-|1.19.0
live-server-preview|neg|0.0.4
LiveServer|rit|3.0.0
react-native-snippet|san|0.6.0
js-jsx-snippets|sky|0.0.6
react-beautify|tai|0.3.0
ReactSnippetsStandard|Tim|1.1.0
vscode-react-native|vsm|0.5.7
vscode-todo-highlight|way|0.5.11
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
> The editor starts but you can not see anything, appears all Black

**Comment by mjbvz** [comment]
@elultimocapo421 Did this just start happening? Can you please provide a screenshot of the problem
