### ISSUE TITLE
Unknown characters and broken format in Terminal

### ISSUE THREAD

**Issue by Onfealive** [Microsoft/vscode#39751]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro - 10.0.16299 N/A Build 16299

Steps to Reproduce:

1. Run codecpetion
2. Check the output

My settings:
{
    "typescript.check.npmIsInstalled": false,
    "window.zoomLevel": 0,
    "files.associations": {
        "*.html": "html"
    },
    "workbench.panel.location": "bottom",
    "editor.renderWhitespace": "boundary",
    "editor.mouseWheelZoom": true,
    "files.trimTrailingWhitespace": true,
    "editor.wrappingIndent": "indent",
    "php.suggest.basic": false
}

Reproduces without extensions: Yes
![bug-1](https://user-images.githubusercontent.com/18258131/33642720-c608cb7a-da6d-11e7-99d8-c100715b100e.png)
![bug-2](https://user-images.githubusercontent.com/18258131/33642721-c643fd9e-da6d-11e7-82b4-08c2ff8304be.png)

**Comment by Tyriar** [comment]
What did you run to get into this state? How does the terminal appear initially after launch?

**Comment by Onfealive** [comment]
I run `php codecept run api XXX` command.
The previous version is worked, but now it's broken. It must be like:

![](https://pceuropa.net/blog/wp-content/uploads/2017/03/yii2-unit-functional-test.jpg)
