### ISSUE TITLE
File explorer is not showing my project files.

### ISSUE THREAD

**Issue by aqeelcodeenterprises** [Microsoft/vscode#39756]
Hi,

Here is a problem in my Visual studio code that appeared after updating or upgrading to the latest version a few days ago.

**The problem is**: A project was opened when I upgraded visual studio code, but after successful updating the project files are not showing in _(Left side)_ file explorer and it remains empty while for all other projects or folders which I open in VS Code it works very well and file explorer shows the files under all other projects except this one...

Please help to solve this problem.

Any help would be appreciated in advance.

Thank you.

**Comment by isidorn** [comment]
Just remove all your extensions one by one and delete your settings one by one and you will find the issue.
