### ISSUE TITLE
False prompt to reload window

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39767]
After todays update I got a prompt to reload because of modified extensions

<img width="1354" alt="screen shot 2017-12-06 at 09 49 05" src="https://user-images.githubusercontent.com/1794099/33652743-c9cbbb4e-da6a-11e7-8441-bdaef7c49da3.png">

**Comment by alexandrudima** [comment]
You were correct that there will probably be a dup -- #39765
