### ISSUE TITLE
[C++] Semicolon in string literal messes up highlighting for rest of file

### ISSUE THREAD

**Issue by swgillespie** [Microsoft/vscode#3976]
Repro:

![screenshot from 2016-03-10 10-46-57](https://cloud.githubusercontent.com/assets/1871912/13680508/ab011482-e6ad-11e5-91ae-266d624e7939.png)

Repro'd on `22dd214678739e71bf51fcba7697e98f33ce191d` for me. This only repros in C++ mode - C mode correctly ends the string literal in the right place.

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#38

**Comment by aeschli** [comment]
Found the issue (on our side)
Duplicate of #4769
