### ISSUE TITLE
Extensions have been modified, after update

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39765]
Got in this morning, got the update and the window which popped up after the update showed me the message:

<img width="2180" alt="image" src="https://user-images.githubusercontent.com/22350/33652007-08502894-da68-11e7-8aac-6e7dcdcf2472.png">

**Comment by aeschli** [comment]
Same for me

**Comment by sandy081** [comment]
Marking this verified as I did not see this after update today

**Comment by alexandrudima** [comment]
:+1:
