### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by veggiemonk** [Microsoft/vscode#39763]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
vscode-docker|Pet|0.0.22
clojure|avl|0.9.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
Go|luk|0.6.69
VS-code-vagrantfile|mar|0.0.7
python|ms-|0.8.0
vscode-icons|rob|7.18.1
vscode-parinfer|sha|0.6.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. open a javascript file in a subfolder
2.

Reproduces without extensions: No

It seems the problem occurs when the extensions are loaded.

**Comment by mjbvz** [comment]
So this does not happen when you disable all extensions? If so, can you please try tracking down which one causes this error

**Comment by veggiemonk** [comment]
The error does not happen when all extensions are disabled.
Suggestion: change the PR template to make the yes/no answer easy to understand.
--> `does the issue happen when all extensions are disabled?`

**Comment by veggiemonk** [comment]
I haven't been able to reproduce the issue and some extentions have been upgraded. 
I will close this issue as there is no more reason to investigate since it is not reproducible
