### ISSUE TITLE
Visual Studio Code's Terminal Paste option is not working

### ISSUE THREAD

**Issue by devendraYebhi** [Microsoft/vscode#39766]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.Open Terminal using Ctrl+`
2. And try to paste anything in terminal, As I tried Ctrl+Shift+v but nothing happening

**Comment by maxibanki** [comment]
You are using VS Code 1.3.1. Please update to the latest one from [here](https://code.visualstudio.com/download).
