### ISSUE TITLE
Commands should provide the alias as well

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39778]
In our command palette we have a feature where we show the english label when the language is not configured to be english:

![image](https://user-images.githubusercontent.com/900690/33657978-4d8a9ae4-da7b-11e7-9c8d-cc8ebbf47eb8.png)

A lot of our commands moved to extensions (e.g. git, emmet) and we no longer have the alias information. We should make sure that our extensions provide the alias from the `package.json`. This can be done via:

```
"contributes": {
  "commands": [
    {
      "command": "git.clone",
      "title": {
        "original": "Clone", // <- this is the one used as alias
        "value": "%command.clone%"
      },
      "category": "Git"
    }
}
```

I am seeing the following candidates:
* [ ] Git @joaomoreno 
* [ ] Emmet @ramya-rao-a 
* [x] Markdown @mjbvz 
* [x] Merge Conflict Decorator @chrmarti 

// cc @dbaeumer to comment if this can be automated. it also seems that currently our schema in `package.json` prints an error when using that syntax.

**Comment by dbaeumer** [comment]
I looked into this and using { value, original } should work. Looks like the schema is not up to date. I know that we discussed automatic this and didn't at the end. I need to recap why. Might be that we can't ensure English being the string typed into the package.nls.json file.

**Comment by dbaeumer** [comment]
Checked and it is indeed a schema issue:

![capture](https://user-images.githubusercontent.com/1931590/33663109-ea396e48-da8e-11e7-8da3-95cdd112431e.png)

**Comment by bpasero** [comment]
@dbaeumer do you know where we define this schema?

**Comment by dbaeumer** [comment]
Yes, and I fixed it. See https://github.com/Microsoft/vscode/issues/39799

**Comment by dbaeumer** [comment]
Will push as soon as endgame is over.

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode/tree/dbaeumer/39799

**Comment by bpasero** [comment]
@dbaeumer ok good 👍

**Comment by joaomoreno** [comment]
@dbaeumer Does this mean we get it for free?

**Comment by dbaeumer** [comment]
No, I just updated the schema. If we want it for free there is some more coding involved.

**Comment by joaomoreno** [comment]
Because this is just repetitive work... I'm already providing the English strings, now I must provide them twice?

**Comment by dbaeumer** [comment]
Now I remember: the challenge is that we read the extension translation generically when the `package.json` is loaded. No extension point parsing happens at that time. We simply replace %....% with the translated value. Reading the English value can't be done generically there since we don't know which strings need the English original value unless we use some special key patterns which then replace the string into a literal with value and original. Alternatively we could read the English string when we parse the extension point but I would argue that we should not do any NLS work there.

**Comment by chrmarti** [comment]
@bpasero How do you enable the mode for showing the alias in QuickOpen?

**Comment by ramya-rao-a** [comment]
@chrmarti When you open code in a non English language, the aliases appear automatically. For eg: `code --locale de-de`

**Comment by ramya-rao-a** [comment]
@bpasero @dbaeumer I can see the English labels for Emmet in 1.19.2 without making any specific changes

![image](https://user-images.githubusercontent.com/16890566/35005179-69f7a176-faa7-11e7-87d9-69d5051a7bd3.png)

**Comment by dbaeumer** [comment]
@ramya-rao-a how do you provide these commands ?

**Comment by ramya-rao-a** [comment]
I declare them in the package.json https://github.com/Microsoft/vscode/blob/master/extensions/emmet/package.json#L191 and register the commands in the extension activation https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/extension.ts#L56

What other way is there?

**Comment by dbaeumer** [comment]
Actually I am not sure why you do get the English strings since the package.json doesn't contain an original English strings. May be someone is now reading both the translated and the English version of the package.nls.*.json file. I need to touch that code this week anyways for the language pack so I will have a look if something changed there.

**Comment by joaomoreno** [comment]
@dbaeumer I still see bad schema warnings:

![image](https://user-images.githubusercontent.com/22350/35524812-095af0c6-0523-11e8-8576-344e4e9a392a.png)

**Comment by joaomoreno** [comment]
For others, I've automated this process with this script:

```js
const fs = require('fs');

const packagePath = process.argv[2];
const nlsPath = process.argv[3];

const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
const nls = JSON.parse(fs.readFileSync(nlsPath, 'utf8'));
const regex = /^%(.*)%$/;

for (const cmd of pkg.contributes.commands) {
	if (typeof cmd.title === 'string') {
		const match = regex.exec(cmd.title);

		if (match) {
			cmd.title = { original: nls[match[1]], value: cmd.title };
		}
	}
}

console.log(JSON.stringify(pkg, null, 2));
```

I ran it like so:

```
node script.js extensions/git/package.json extensions/git/package.nls.json
```

This outputs the new contents of `package.json`.

**Comment by mjbvz** [comment]
Thanks @joaomoreno! Used your script to update markdown and TypeScript

**Comment by ramya-rao-a** [comment]
I still dont see why we need to do this.....

**Comment by dbaeumer** [comment]
I was in the code today and there is no need for this anymore. The English strings is filled in automatically if a default nls file is found. You can still provide the English string in the translation as well.

**Comment by ramya-rao-a** [comment]
So we can close this issue then?

**Comment by dbaeumer** [comment]
Yes.

**Comment by joaomoreno** [comment]
Reverted my commit.
