### ISSUE TITLE
some "code --status" paths start with "\\?"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#39775]
testing #39376:

some "code --status" paths start with "\\\\?" or "\\??":

![2017-12-06_11-17-16](https://user-images.githubusercontent.com/1898161/33657210-da54ce52-da78-11e7-911f-ef5a033c172b.png)

@dbaeumer I don't know how helpful this is. Should we clean this up?

**Comment by dbaeumer** [comment]
@weinand  In theory a process could come from a UNC drive \\server\.... So we should only remove this if it os \\?\ or \??\. We best do that in ps.ts. Then the data coming from the script is somehow original. Feel free to assign to me to do this.
