### ISSUE TITLE
Tab title shows './'

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39771]
I have two test.ts-files open. One in the workspace root and another in a nested folder. The former shows as `test.ts ./` which not very helpful. I'd rather not add more information here

<img width="331" alt="screen shot 2017-12-06 at 11 03 55" src="https://user-images.githubusercontent.com/1794099/33656075-47c98d3c-da75-11e7-87db-3bc50a224144.png">

**Comment by bpasero** [comment]
This came in via #27718 and we settled on the decision to show an indicator to emphasize that the file is in root.
