### ISSUE TITLE
Set toggleFindCaseSensitive and toggleFindWholeWord default values

### ISSUE THREAD

**Issue by idanwe** [Microsoft/vscode#39773]
After upgrading to v1.18 I noticed a change.
When I open a file, the default behavior of find in find (cmd + f) is Match Case and Match Whole Word, and in order to search only by part of a word try to look for a function or variable in a file I need to toggle it off.

Is there a place to change that it will be always off by default?

- VSCode Version: 1.18.1
- OS Version: macOS 10.12.6

**Comment by rebornix** [comment]
@idanwe we remember the options you use last time that's why you still see it but by default, Match Case and Match Whole Word are turned off.
