### ISSUE TITLE
Add support for scroll active terminal switching

### ISSUE THREAD

**Issue by ganlub** [Microsoft/vscode#39779]
Right now you need to open the dropdown to do it. It would be really cool to be able to just scroll on the dropdown to switch between them.

This is how it works on Tilix:
![def](https://user-images.githubusercontent.com/1272617/33657701-5d7de84e-da7a-11e7-9f4c-9731ce137869.gif)

There are probably shortcuts for doing this, but I'm guessing implementing this would be quite trivial.

**Comment by Tyriar** [comment]
We eventually want to move to tabs instead of a dropdown: https://github.com/Microsoft/vscode/issues/10546

In the meantime you can setup keybindings to move focus:

```js
{ "key": "ctrl+shift+j",    "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",    "command": "workbench.action.terminal.focusPrevious" },
```
