### ISSUE TITLE
Keybindings editor: steals focus in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39780]
Steps to Reproduce:

1. open keybindings editor and some other files
2. open quick open (Cmd+P) and pick some of the other files and press Arrow-right
3. the other files focus in the background but quick open stays open
4. now try this on the keybindings editor

=> focus is lost to the keybindings editor, it eagerly puts focus into its input field

//cc @sandy081

**Comment by sandy081** [comment]
Thanks @bpasero
