### ISSUE TITLE
[php] PHP globals hovers on html tag

### ISSUE THREAD

**Issue by rtpHarry** [Microsoft/vscode#3978]
In a file called header.php.

Hovering over the html5 `<header>` tag shows a php `header()` tooltip:

![image](https://cloud.githubusercontent.com/assets/1038062/13682336/37890e78-e6f9-11e5-83f6-90fdb2e87a00.png)

It also shows it on the `</header>` tag.

I have php 7 installed on the system.

**Comment by roblourens** [comment]
This is annoying, but the builtin PHP support is very simple, and so it isn't easy to fix. I suggest using a PHP extension.
