### ISSUE TITLE
Import autocomplete suggests not exported types and interfaces

### ISSUE THREAD

**Issue by klis87** [Microsoft/vscode#39785]
- VSCode Version: 1.18.1
- OS Version: Linux

Steps to Reproduce:
1. Install `redux-saga-requests` library with `yarn add redux-saga-requests`
2. Start typing `import {} from 'redux-saga-requests'` and use autocomplete feature between `{}` with `ctrl + space`. You will see types and interfaces not exported in typings TypeScript file.

For example, I have a following in my `index.d.ts` file:
```typescript
interface ActionTypeModifier {
  (actionType: string): string;
}
```
but I can still see `ActionTypeModifier` hint. The problem is, that autocomplete is polluted with many internal types, which are not part of public API. Is it an expected behavior?

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20584
