### ISSUE TITLE
Running Extensions: move into extensions viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39783]
Testing: https://github.com/Microsoft/vscode/issues/39568

Imho we should move the UI of the "Show running extensions" into the extensions viewlet. I would expect an extension to show up like other extensions do today and maybe even have the same actions (I might want to quickly disable an extension that causes significant CPU time). 

Maybe this could show up in a new split-view in the viewlet only once you execute the action from the command palette?

**Comment by isidorn** [comment]
More split views in the viewls would only bring more mess.
IMHO it should be a new view which gets triggered by a special filter, e.g "running:"
Similar to how we have the elipses actions to show installed, we could have one to show running

**Comment by joaomoreno** [comment]
Special filters start with `@`, like `@outdated` or `@recommended`. I suggest `@running`.

**Comment by bpasero** [comment]
@joaomoreno yeah very good idea, I like the `@running` thing

**Comment by isidorn** [comment]
I am not passionate about this.
Ping @ramya-rao-a @sandy081 who own things in the extension view in case they want to reopen and look into this

**Comment by ramya-rao-a** [comment]
There is some user interest in having this and is being tracked in #57969

**Comment by ramya-rao-a** [comment]
We should definitely support the `@running` query in the search box. This is being tracked in #57969
