### ISSUE TITLE
relative pythonpath in .env is expanded wrt current file

### ISSUE THREAD

**Issue by elypma** [Microsoft/vscode#39788]
- VSCode Version: 1.18.1
- OS Version:Windows 7
- Python v0.8.0

Steps to Reproduce:

1. Create an .env file in root of workfolder
2. add 'pythonpath=.\_common\packages
3. Try to debug and the relative addition (see 2.) to the pythonpath is added relative to the current work directory of the file being debugged.

Reproduces without extensions: Yes (depends on epython extension)

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#358
