### ISSUE TITLE
"Emmet: remove/update tag" matches wrong tag pair.

### ISSUE THREAD

**Issue by theGivingTree** [Microsoft/vscode#39789]
- VSCode Version: 1.18.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Type this:
``` html
<div>
  <input>
  <div></div>
</div>
```
2. Put cursor on child div and run *Emmet: remove/update tag*
3. parent div takes effect

### Additional Notes
+ List of [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) that show the same result when they replaces `<input>`
  + `<col>`, `<embed>`, `<input>`, `<param>`, `<source>`, `<track>`
+ Slash before closing bracket prevents the malfunction. (like `<input/>` instead of `<input>`)

Reproduces without extensions: Yes

**Comment by davidkwan95** [comment]
I'm on Linux Mint and this is reproducible as well. I can try and take this one. Any guidance?

**Comment by ramya-rao-a** [comment]
@davidkwan95 

This is an upstream issue. We use the https://github.com/emmetio/html-matcher module to parse the html document to get a tree. This module maintains a list of [empty elements](https://github.com/emmetio/html-matcher/blob/5abce0082a2a1ad7ddbefef3e676c729fcc12706/index.js#L22) which is missing `input`, `col` etc.

So, submit a PR to https://github.com/emmetio/html-matcher to update this whitelist as per the  [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements).

I can then absorb those changes in emmet in vs code.

**Comment by ramya-rao-a** [comment]
Thanks for the fix @davidkwan95!

There are a few other upstream emmet issues that I need help with.
Feel free to reach out if you are interested in tackling any of them.

**Comment by davidkwan95** [comment]
Hi, I would like to try and tackle it @ramya-rao-a . Could you give me the links to the issues?

**Comment by ramya-rao-a** [comment]
@davidkwan95 You can try https://github.com/emmetio/html-matcher/issues/2 and https://github.com/emmetio/html-transform/issues/2
