### ISSUE TITLE
Aligning imports statements  & stuff like PHPStorm/WebStorm does

### ISSUE THREAD

**Issue by vhb56** [Microsoft/vscode#39786]
It's a feature request.

It would be nice if VSC could align imports & stuff like phpstorm/webstorm does.
Found myself doing it manully without thinking.
These are little things, but i am really depend on it.
Code is so much cleaner with them.

From:
```
import * as ts from 'typescript';
import {doSomething} from 'modues/boo';
import {bar} from 'modules/foo';
import {fooo} from 'modules/foo';
```
To:
```
`import * as ts       from 'typescript';`
`import {doSomething} from 'modues/boo';`
`import {bar}         from 'modules/foo';`
`import {fooo}        from 'modules/foo';`
```

**Much more readable.**

Also aligning by colon(:), assignment(=,+=,-=,*=,/=) and arrow(=>).
Something like this plugin, which i use daily, not perfect, but near:
https://marketplace.visualstudio.com/items?itemName=wwm.better-align

From:

```
let a: string = 'xxx';
let ccccccc: Something = new Something();
let bb: number = 42;

let obj = {
 bar: 'xxx',
 fooopp: 'yyy',
 smth: 'zzz'
}
```

To

From:

```
let a      : string    = 'xxx';
let ccccccc: Something = new Something();
let bb     : number    = 42;

let obj = {
 bar   : 'xxx',
 fooopp: 'yyy',
 smth  : 'zzz'
}
```

**Comment by mjbvz** [comment]
Our built-in formatters do not provide these more advanced formatting options. Please try looking in the marketplace for an extension that does
