### ISSUE TITLE
Can you please ditch HTML and tranform vscode to native

### ISSUE THREAD

**Issue by medmedin2014** [Microsoft/vscode#39782]
VSCode is great editor and can support multiple languages especially C#, but what makes it slow in running and debugging code and consuming so much memory is the fact that it's interface is coded using such slow/cheap web framework, please ditch it and rewrite it using a good languages like C, C++ or Java.

**Comment by isidorn** [comment]
Thanks for the suggestion. However this is not on the current plan, but we accept PRs that fix htis.
