### ISSUE TITLE
VSCode no longer shows errors in folded code

### ISSUE THREAD

**Issue by prmph** [Microsoft/vscode#39787]
- VSCode Version: 1.18.1 (1.18.1)
- OS Version: Mac OSX Version 10.10.5

Steps to Reproduce:
1. Open Visual Studio Code
2. Set the user setting as follows:
```
{
"window.zoomLevel": 0,
"editor.fontSize": 12,
"extensions.ignoreRecommendations": true,
"workbench.startupEditor": "none",
"editor.detectIndentation": true,
"editor.minimap.enabled": false,
"emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly",
"emmet.showAbbreviationSuggestions": false,
"typescript.disableAutomaticTypeAcquisition": true,
"workbench.colorTheme": "Default Light+",
"typescript.autoImportSuggestions.enabled": false,
"explorer.confirmDragAndDrop": false,
"explorer.confirmDelete": true,
"problems.decorations.enabled": true,
"telemetry.enableTelemetry": false
}
```
3. Open an empty folder
3. Add a tsconfig.json file with the following contents:
```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "commonjs",
        "moduleResolution": "node",
        "traceResolution": false,

        "lib": [
            "es7",
            "es6",
            "es5",
            "dom",
            "es2015.promise",
            "scripthost",
            "dom.iterable"
        ],

        "jsx": "react",
        "allowJs": false,

        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "suppressImplicitAnyIndexErrors": true,

        "noImplicitAny": true,
        "noImplicitReturns": false,
        "strictNullChecks": true,
        "noImplicitThis": false
    },
    "include": [
        "./src"
    ]
}
```

4. Create a file named test.ts and add the following content to it:
```
function eureka(): string {
    let result = 123
    return result
}
```
5. Fold the eureka() function just added; there is no indication of an error in the code file itself (although the files explorer shows test.ts in a red color indicating an error)
6. Expand the eureka() function; a squiggly line appears under line 3

Previous version of VS Code would show squiggly lines indicating a type error next to folded code blocks. This feature was very useful for quickly noticing problem areas in large code files before compilation. For some reason, this feature is no longer working in recent versions of VS Code. 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is intentional.

* Errors from folded regions still show up in the overview ruler to the right (as before) and in the status bar (as before).
* We have checked with other editors and none of them render squiggles from the folded areas near the "..."
* We have removed those for performance reasons (sometimes, there would be tens of thousands of decorations that would land on those "..." and painting those would cause stalls)

<img width="1003" alt="screen shot 2017-12-07 at 12 07 23" src="https://user-images.githubusercontent.com/5047891/33712336-5af35096-db47-11e7-84e9-3ed3286cafc0.png">
