### ISSUE TITLE
Close debug console when debugging is stopped

### ISSUE THREAD

**Issue by jayrosen1576** [Microsoft/vscode#3979]
I believe this worked in a prior version. Now the debug console stays open even after stopping the debugger. It should automatically close. Also, if the debug console is closed manually it should not reopen when the debugger is restarted since it takes up valuable screen real estate if it is not needed.

**Comment by isidorn** [comment]
This has been fixed and will be available in the march vscode release

**Comment by jayrosen1576** [comment]
Perfect!
