### ISSUE TITLE
After closing the "terminal"-panel, the resize-cursor is still showing when hovering

### ISSUE THREAD

**Issue by TryingToImprove** [Microsoft/vscode#39798]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open new file
2. Toggle panel **on right side** (notice it's position)
3. Call "View: Close panel"
4. Move cursor to it's "start position "

Reproduces without extensions: Yes

I tested this with the panel on the right side.
Windows is not happy with taking screenshots with the cursor, so I could not take a picture.. :/

There are pictures in the comments

**Comment by isidorn** [comment]
This is as designed so you can drag it over from being minimized.
If I undrestood your problem correctly, and that is the resize cursor is like that near the status bar when the panel is hidden. Did I understand correctly?

**Comment by TryingToImprove** [comment]
No. 

When opened, I can resize:

![image](https://user-images.githubusercontent.com/1690457/33670867-5b2e430a-daa6-11e7-9d7e-dc927fc48b63.png)

When it is closed and I move my cursor to the place where it "rendered to" before the cursor is still shown (red stuff in middle is resize-cursor)

![image](https://user-images.githubusercontent.com/1690457/33670933-87605a44-daa6-11e7-8075-2665c743d0b7.png)

**Comment by isidorn** [comment]
Ok good catch, I acknowledge the bug and will look into a fix

**Comment by TryingToImprove** [comment]
It seems like it only a issue on "right" panel's

**Comment by isidorn** [comment]
Exactly, that's why I did not see it until you posted a picture

**Comment by bpasero** [comment]
@isidorn verified, however it looks like the sash is still visible and now all over to the right. I can still get the cursor when I move my mouse all the way to the left but I cannot drag to pull it in:

![image](https://user-images.githubusercontent.com/900690/33762165-d8355d46-dc0b-11e7-8379-9e6baaaf4c11.png)

Maybe we should hide the sash when in this case?

**Comment by isidorn** [comment]
@bpasero agree, we should hide it. Though not something I want to do last minute, reopening and assigning to decmber

**Comment by bpasero** [comment]
@isidorn yeah sounds good
