### ISSUE TITLE
setting pythonpath in launch.json fails

### ISSUE THREAD

**Issue by elypma** [Microsoft/vscode#39790]
- VSCode Version: 1.18.1
- OS Version: windows 7

Steps to Reproduce:

1. Create an empty .env file in the ${workspaceRoot} (which is confusing with multiple folders)
2. Set the pythonpath in launch.json: 
       "envFile": "${workspaceRoot}/.env",
       "env": {
                "PYTHONPATH": "${workspaceRoot}/_common/packages"
        },
2. This only works when the "envFile" setting is completely removed or when the .env file is deleted.

Reproduces without extensions: No (depends on python extension)

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#376
