### ISSUE TITLE
click events on visual studio code with a pen tablet (Wacom Intuos Pro) are randomly missed

### ISSUE THREAD

**Issue by kingmatusevich** [microsoft/vscode#39801]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
nativebase-snippets|Gee|0.5.22
vscode-docker|Pet|0.0.22
Bookmarks|ale|0.18.0
project-manager|ale|0.23.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-dash|dee|1.7.1
azure-account|ms-|0.2.2
node-debug2|ms-|1.19.1
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.18.1
react-beautify|tai|0.3.0
vscode-react-native|vsm|0.5.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Have a Pen Tablet, with drivers and else.
2. Open VIsual Studio Code.
3. Use the app.
4. Suddenly, clicks are missed and are only accepted from other pointing devices.

Reproduces without extensions: Yes/No

**Comment by kingmatusevich** [comment]
When this starts happening the solution is closing the app and opening again, which sometimes is workable if it takes some time to resurface, but half the time it resurfaces after a couple of minutes.

**Comment by kingmatusevich** [comment]
to clarify, it creates weird behaviours, of course you cant switch a specific line of code, but on top of that trying to select a different tab marks the button as a selected control, but doesn't execute the tabswitch, requiring a spacebar to confirm selection. Selecting text with the pen when the bug is ongoing causes the text to appear selected, but on a different color as the regular selection of text, and typing to overwrite a selected text wont work, requiring a click from a mouse or trackpad to recover a text cursor to type from.

**Comment by kingmatusevich** [comment]
I use the pen for RSI reasons, so I would greatly appreciate a fix, having to use the mouse is a dealbreaker for me.

**Comment by kingmatusevich** [comment]
In my limited testing, it appears to be triggering to the app's transitions between the foremost app and not, and/or the usage of another of the input devices (example, I use the trackpad for scrolling, and doing quick mousing towards the secondary monitor).

**Comment by isidorn** [comment]
@kingmatusevich can you please try this with the latest vscode insiders since we have changed a bit how we handle touch input
https://code.visualstudio.com/insiders/

**Comment by kingmatusevich** [comment]
Will do, report back in 12 hours / after the bug triggers again, whichever occurs first.

**Comment by isidorn** [comment]
Ok, thanks

**Comment by kingmatusevich** [comment]
This is still happening on the Insiders version.

**Comment by isidorn** [comment]
@kingmatusevich ok thanks. However this is not on our immediate backlog, also we do not have a machine like that to try it out.
So we would accept PRs that fix this.
[Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/touch.ts#L114)

**Comment by jansensan** [comment]
I was intermittently facing this issue with recent releases, however now all text editors are completely non-functional with a Wacom tablet. The file navigator remains functional.

**Comment by kingmatusevich** [comment]
Yes, the issue is worsening. It's gotten so bad I switched to Sublime Text for most of my work, which is sad, because I find VSCode a lot better for all of my uses, but the accessibility angle of not being able to use a Wacom Tablet is a problem for me.

**Comment by davision** [comment]
Why is this still an open issue? And yes, it's getting worse with each new version. Crazy.

**Comment by GarryPlays** [comment]
bought an intuos today since my wrist is killing me from all this scrolling in visual code
it's just utter rubbish, you can't even drag and scroll, you can turn of this windows popup window for writing, makes the clicks at least detect, with 0.5s delay
but scrolling, which was my main reason to get a wacom, not possible in visual code, works great in notepad++, browsers, everywhere, but code
I think the issue is the automatic code completion trigger, or auto highlighting
anyway, yeah, that's just sad

**Comment by kingmatusevich** [comment]
I'm not confirming anything yet, but it seems to me since the last update (where the Chromium version used was increased) that the issue of clicking is fixed. At the very least, I haven't yet encountered the issue again, but my testing hasn't been intensive enough to confirm that yet.

**Comment by GarryPlays** [comment]
Cool, broke completely for me, no more left clicks. Hours later I figured I have to create a custom app and then in Mapping tab turn off the checkbox 'Use Windows Ink', now code works again

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
