### ISSUE TITLE
running as root doesn't show up anything

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#39809]
- VSCode Version:1.18.1
- OS Version:Ubuntu 17.10 on Wayland

When I try to open a directory as root it doesn't show up anything, even any terminal message.

Steps to Reproduce:

1. `sudo code /var/www/html/ --user-data-dir=/home/user/.vs-root`
2. VS Code window won't appear.

Reproduces without extensions: No

**Comment by Tyriar** [comment]
We don't have any plans to improve running VS Code as sudo any time soon. In the meantime I suggest symlinking html to your home directory and from working there.
