### ISSUE TITLE
Adopt spdlog 0.16.0

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39807]
https://github.com/gabime/spdlog/pull/570#issuecomment-349662833

> btw if you use aync logging, you might want to upgrade to 0.16.0 that will be released in the next few days.
> Most notably in async logging, the back thread busy wait loop (when the queue is empty) will be reduced from 5/sec to 2/sec to reduce cpu waste.
> 
> Also, rotated log files will preserve their extension (“log.3.txt” instead of the current “log.txt.3”)

cc @sandy081

**Comment by sandy081** [comment]
@joaomoreno Adopted output panel to the change in rotating file format. Thanks.

**Comment by joaomoreno** [comment]
Verification: logs still work as expected
