### ISSUE TITLE
Nuke the log-decorator

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39806]
re #39572

```ts
@log(LogLevel.Info, 'CommandService', (msg, id) => `${msg}(${id})`)
executeCommand<T>(id: string, ...args: any[]): TPromise<T> {
  // ..
}	
```

This looks very pretty and I believe it's a prime-sample for a decorator but once you wanna debug calls to `executeCommand` you will hate it. Really hate it. My recommendation is nuke it or not recommend it...

**Comment by joaomoreno** [comment]
We nuke and treat it as a BUG!

**Comment by mjbvz** [comment]
Verified no more `@log` in code and that logging still happen as expected
