### ISSUE TITLE
Tasks didn't stop running using PlatformIO extension on macOS

### ISSUE THREAD

**Issue by sstaub** [Microsoft/vscode#39804]
- VSCode Version: Code - Insiders 1.19.0-insider (bd11a1f64eb870a927f3d0e5e4628b3fa066d90c, 2017-12-06T06:07:57.990Z)
- OS Version: Darwin x64 17.3.0 [10.13.2 Beta (17C85a)]
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.3
platformio-ide|pla|0.8.2
debug|web|0.21.2
---

When using tasks of PlatformIO extension, the tasks don't stop running, the cpu load rises very high.
**This happens only on macOS, on windows (WIN10) the problem doesn't occur !!!**
The developer of the PlatformIO IDE can't figure out that problem (making a team viewer session on my macbook with no results).

Steps to Reproduce:

1. Install the PlatformIO IDE and all dependencies  (cpp, debug) the installation needs some time, all dependencies  (cpp, debug) will load automatically!
2. Create a project with an Arduino board like UNO within PlatformIO, there is a new project with a src/main.cpp file, you don't need to make additional code.
3. At the first time, the IDE download the necessary files for building Arduino, be patient!
4. Build it.
5. The build task (and also other tasks) didn't stop (see screenshot).
6. Press ENTER in terminal, the task stops.

<img width="1108" alt="screenshot vsc platformio build" src="https://user-images.githubusercontent.com/6450325/33670864-5a3c92b2-daa6-11e7-93e5-87bd608a41de.png">

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/37846
