### ISSUE TITLE
Make use of trailing semicolons optional

### ISSUE THREAD

**Issue by demisx** [Microsoft/vscode#39802]
Many programmers are no longer using a semicolon to terminate code lines in languages where it's optional. Our team doesn't use trailing `;` when programming in TypeScript and/or JavaScript. However, when Intellisense inserts a line, it automatically terminates it with `;`. Would be really helpful if the option whether to end each line with a semicolon or not was configurable globally per language. Then, Intellisense and other plugins could honor it to make one's coding more efficient.

- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Remove import statement for an existing type
2. Accept Intellisense suggestion to add import statement
3. When import is added  a `;` is auto added at the end of the line

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you please explain what specific action is triggering the semicolon to be inserted?

**Comment by demisx** [comment]
Sure. It's just as I wrote in the description pretty much.
1. Let's say I write this line where `IAd` is a new type:
```ts
const ad: IAd = ctx.request.body
```

1. The Intellisense kicks in and suggests me to import it, i.e. 
![screen shot 2017-12-06 at 10 32 47 am](https://user-images.githubusercontent.com/4452412/33678536-d82a1680-da70-11e7-9ea0-71627b9b581a.jpg)

1. I accept the suggestion and this is what's added to the import block. Note the trailing `;`
```ts
import IAd from './ad.interface';
```

I'd like to be able to instruct VS Code that I don't use ending semicolons in some language, e.g. TypeScript, JavaScript etc. And then have Intellisense, plugins, snippets to honor that setting. Currently, I have to take care of the semicolons myself and that makes coding less efficient.

Hope this helps. Please let me know if you need more info.

**Comment by mjbvz** [comment]
Thanks for the additional info. This falls under https://github.com/Microsoft/TypeScript/issues/18780 and  https://github.com/Microsoft/TypeScript/issues/19882

Using the TSlint workaround from the SO question may help for now: https://stackoverflow.com/a/47667384/306149

Closing as upstream

**Comment by demisx** [comment]
@mjbvz Thanks. Will those cover other languages (besides TypeScript) that also have `;` optional?

**Comment by mjbvz** [comment]
Yes, those issues apply to both JavaScript and TypeScript. The TypeScript project is what provides our JS language support
