### ISSUE TITLE
Don't always log extension host init data

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39805]
re #39572

The extension host init data is a monster, depending on your configuration and installed extensions easily 1MB. We always log this (level=info) and to make matter worse we serialise it again... So instead of taking the monster string we have send over, we take the just parsed object and create yet another monster string... Two things I'd do different: don't use log level info, log the extension IPC which is already strings

**Comment by joaomoreno** [comment]
We don't have a log service that early in the game, so I'll move the init data logging to a trace level.
