### ISSUE TITLE
Log level persistence

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#39803]
re #39572

* set log level to OFF
* shutdown & restart VS Code
* logging is on again

**Comment by joaomoreno** [comment]
Should we really persist this? I'm not so convinced...

**Comment by jrieken** [comment]
Maybe as setting. That's how TypeScript does it but not persisting feels weird to me. When I don't want logging or worst when I want terse logging to reproduce something which requires many restarts when I don't always want to start from the command line.

**Comment by joaomoreno** [comment]
Yeah it makes sense. The problem will be reading the settings that early in the game.

Maybe an env variable would help?
