### ISSUE TITLE
JSON language server always starts in debug mode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39813]
_From @jdalton on December 6, 2017 16:42_

I noticed when trying to use Node `--inspect` in my iterm console on macOS that it would fail saying the address is already in use. 

```
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

If I enabled [nodejs-v8-inspector-manager](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj) to auto open then I see vscode opening an inspect session 

<img src=https://user-images.githubusercontent.com/4303/33673347-526a4b6e-da61-11e7-94eb-6d3bbc864cb9.png width=40%>

If I close vscode then Node `--inspect` works.
How do I stop vscode from hogging Node `--inspect`?

_Copied from original issue: Microsoft/vscode-chrome-debug-core#259_

**Comment by roblourens** [comment]
@aeschli, is it intentional for the json language server to always start in debug mode? It hogs the default debug port for Node debugging which can be annoying.

**Comment by aeschli** [comment]
It only starts with ---profile is the extension host is in debug mode.
Verifying that on the latest insiders, I don't see the port being opened:
![image](https://user-images.githubusercontent.com/6461412/33705974-af0913e2-db32-11e7-92a8-24e6c583f7f7.png)

Please reopen if you still see this.

**Comment by jdalton** [comment]
Hmm.. yay! The insider build updated and it's no longer doing it.
