### ISSUE TITLE
Advanced Search Options: Add option for normal javscript regex engine file find and replace

### ISSUE THREAD

**Issue by paulthomas75** [Microsoft/vscode#39810]
- VSCode Version: 1.18
- OS Version: windows 10

Idea:  Should ideally be an option to bypass restricted RUST search engine at that point of advanced searching.

Scenario:  Refactoring hundreds of relative paths to use alias or paths. No easy way to reduce multi-level paths to an alias.

Issue:

1. Create files test1.ts test2.ts and populate with:

import { AnyOldService } from "./module/1.service";
import { AnyOldService } from "../module/2.service";
import { AnyOldService } from "../../module/3.service";
import { AnyOldService } from "../../../module/4.service";
import { AnyOldService } from "../../../../module/5.service";

2.  CTRL+SHIFT+F

3.  Find box:  (from ")(.*)(?=odule\/)

4. Replace box:  @exampleAbsoluteModule

5. Select Regular Expression Icon - 

Issue: No matches:  

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
You can set `"search.useRipgrep": false` as a workaround.
