### ISSUE TITLE
Strange behavior for multiple matching completions

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#39819]
- VSCode Version: Code - Insiders 1.19.0-insider (bd11a1f64eb870a927f3d0e5e4628b3fa066d90c, 2017-12-06T06:14:27.050Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Have a global variable `verify`, and also `@types/node` in scope. (This was reproduced by adding a new file to `tests/cases/fourslash` in the TypeScript repo.)
2. Start typing `verify`.

I would expect the expected completion to always be `verify` because that's always the best match, but it seems to switch to `createVerify` when the text is `verif` but change when I type `y`. When I try reproducing it again it's sometimes the opposite and typing `verify` completes to `createVerify` even though there's already an exact match!

![completions](https://user-images.githubusercontent.com/19274678/33677925-3d0fe0a4-da6f-11e7-9925-cad6754472c3.gif)

**Comment by jrieken** [comment]
This might be due to us now remember a previous choice. In case you have selected `createVerify` once with the `verif` prefix we will automatically select it again. Please try with latest, latest insiders from today which has a slightly tweak variant of this (it will stay on the selected item).

**Comment by andy-ms** [comment]
I can't reproduce this behavior any more, thanks.
