### ISSUE TITLE
Dark theme in running extension view

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#39815]
Testing: #39568 

- VSCode Version: Code - Insiders 1.19.0-insider (12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee, 2017-12-06T14:13:53.506Z)
- OS Version: Windows_NT x64 10.0.17046

Looks good in light theme - not so good in Dark.

![image](https://user-images.githubusercontent.com/1051190/33675538-bf36228a-da67-11e7-94cb-8ab82631527f.png)

**Comment by ramya-rao-a** [comment]
Verified by running from source
