### ISSUE TITLE
Crash Code 3221225477  on starting Nodejs project

### ISSUE THREAD

**Issue by Skuriles** [Microsoft/vscode#39818]
- VSCode Version: Latest VS Code (1.18.1) and Insider Release 1.19.0 (tested with both)
- OS Version: Win 10 

Steps to Reproduce:

1. Open Nodejs project
2.Start with F5 
3. Crash 

The project worked until yesterday perfectly in VS...changed nothing in launch config or installed/uninstalled any extensions since then

launch config
  ```
      {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\bin\\www"
        },
```
        

Reproduces without extensions: Yes/No => disabled all extensions. Clean install of insider release (without any extension). Both crash on starting the nodejs project
Insider Release
![errorvs](https://user-images.githubusercontent.com/7985622/33676618-7fe7fb40-dab6-11e7-8f09-6375367f6e3a.png)

VS Code 1.18.1
![image](https://user-images.githubusercontent.com/7985622/33676650-972cb732-dab6-11e7-822f-92f3201b7ca3.png)

**Comment by weinand** [comment]
Does it help if you restart your computer?

**Comment by weinand** [comment]
3221225477 shown in HEX is 0xC0000005 which is a STATUS_ACCESS_VIOLATION code on Windows.

@alexandrudima @jrieken does this ring a bell?

**Comment by Skuriles** [comment]
@weinand 
Restart didn't change anything. Still error occurs

**Comment by Skuriles** [comment]
I have another project (Angular 5 with Anuglar Cli). If I try to start this one directly from VS Code the same error occurs. 
So it seems that it does not depend on the project type. In Angular Cli there is a nodejs script implemented, but the error immediately hits after pressing F5 in VS Code, no console output or anything but the error messages from dev console I've already posted. If I can do anything (providing logs or anything else let me know)

**Comment by jrieken** [comment]
@Skuriles Can you try adding this `"git.decorations.enabled": false,` to your settings file?

**Comment by Skuriles** [comment]
Will try it as soon as I'm back home

**Comment by Skuriles** [comment]
@jrieken 
Tried it in both (insider and normal VS Code) without success (restarted PC => tried again). 
Still get exact the same error

**Comment by jrieken** [comment]
Ok... Next try: Please start from the command line with the `--inspect-brk-extensions=9334` option. Then open Developer Tools and check the console for a chrome-dev-tools URL. Open that in Chrome and it should be the extension host process in debug mode. Enable break on errors/uncaught error and  resume the process. If it's a problem in JS-land you should now see it.

**Comment by Skuriles** [comment]
Hm.. I've started it like you said. It breaks on some promise rejects (git not found) but no exceptions as far as I can see. 
If I start it in this mode and press F5 to run the application it works!!
If I re-start it "normal" it still rejects launch. 
I've already updated Git to latest version and even tried to ""git.enabled": false," but still same problem.. really strange

I will attach all errors the debugger breaks on

![image](https://user-images.githubusercontent.com/7985622/33726130-7792dcc6-db74-11e7-8dd4-e2d231d7b641.png)

![image](https://user-images.githubusercontent.com/7985622/33726160-8ca2ba78-db74-11e7-8e71-7459e126d01b.png)

There are a few more (think this are following errors, if you need more, I will add everything)

**Comment by Skuriles** [comment]
Just remark: I used Git before without any problems in this project.

**Comment by jrieken** [comment]
> I used Git before without any problems in this project.

A rejected promise doesn't mean git doesn't work. It's part of the discovery and more a bug in the debugger as those errors are usually handled. @Skuriles Please continue the break on error walk until the last error before crashing

**Comment by Skuriles** [comment]
As I said: The problem is that the debugger stops at this rejected promises on startup. But then Visual Studio Code works as long as I start it with --inspect-brk-extensions=9334 parameters. 
So there are no errors if I press F5 to launch the project.
I will try to re-do my tests this afternoon and check if there are any breaks on launching the projects.
Feels a little bit like a caching/timing problem which is resolved by open the dev tools in a web app :-)

If I start VS Code without these parameters I can't start the project with F5

**Comment by jrieken** [comment]
Also try with latest insiders please. thanks

**Comment by weinand** [comment]
@Skuriles to avoid stopping on rejected promises just uncheck the exception options in the Breakpoints view:
![2017-12-08_10-44-28](https://user-images.githubusercontent.com/1898161/33760064-cbe53b3a-dc04-11e7-9cdf-8d65d379fe7d.png)

**Comment by Skuriles** [comment]
Tried with latest insider version:
If I start it with --inspect-brk-extensions=9334 parameters it works, same as in 1.18.1. The only thing is a warning in dev tools if I start the app ("Message Debugging with inspector protocol because Node.js {0} was detected. didn't get externalized correctly..."). 
As you can see it is running.:

![image](https://user-images.githubusercontent.com/7985622/33770472-f820cb78-dc2d-11e7-84e0-94f1ffa29d0a.png)
The dev tools I've opened in Chrome show nothing and don't break on any exception

In 1.18.1 it is exactly the same behavior (works with parameters, crashes without): 
![image](https://user-images.githubusercontent.com/7985622/33770869-5bce9d70-dc2f-11e7-8f6d-e749d5d47296.png)

Dev Tools show this warning. Dev Tools opened in Chrome show nothing

Starting without parameters shows this
![image](https://user-images.githubusercontent.com/7985622/33770984-bc55ffc6-dc2f-11e7-9d59-231eb15bf3d2.png)

**Comment by jrieken** [comment]
Funky... @bpasero You had crash insights and how they are logged on windows, right?

**Comment by bpasero** [comment]
@jrieken yeah lately I had some luck in getting core dumps when installing Debug Diagnostic Tool: https://www.microsoft.com/en-us/download/details.aspx?id=49924

When started it allows to stop on exception on a process (you can pick it). If you are lucky, a core dump is being produced with more data.

Alternatively you could also try to attach to the process with VS which should basically do the same thing when it crashes. But for users it may be easier to go with the debug diagnostic tools.

**Comment by jrieken** [comment]
@Skuriles See https://github.com/Microsoft/vscode/issues/39818#issuecomment-350286739. Thanks

**Comment by Skuriles** [comment]
@bpasero 
As I never used this tool: Is there a step-by-step manual how to use it with VS Code? 
I found some old ones, but not for the latest 2.0 or I just don't get it. I can only analyse dmp files, but how to get them for VS Code?

**Comment by bpasero** [comment]
@Skuriles see https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows

**Comment by Skuriles** [comment]
Oh my bad. I searched for the tool in windows search and just found the analyser :-b

Report file created form the analyser tool:
[report.zip](https://github.com/Microsoft/vscode/files/1548714/report.zip)

I can also provide the complete dump file but it is 83 mb. Shall I upload it anywhere?

**Comment by bpasero** [comment]
@Skuriles that file has a weird ending, are you sure you attached the right thing? It looks like a multi part message.

**Comment by Skuriles** [comment]
This is the report file extracted from the created dump files with MS Debug Tool analyser. 
I can perfectly read it in browser.
As I said, I can upload the whole dump file, but Git threw errors (think 83 MB were too big) so I can't upload it here

**Comment by bpasero** [comment]
@Skuriles yeah I see it now.

The stack seems to be this:
 
```
ntdll!RtlDispatchException+104
ntdll!KiUserExceptionDispatch+2e
ucrtbase!wcsncpy+3c
node!uv_tty_set_mode+247d
node!uv_tty_set_mode+1fe0
node!uv_tty_set_mode+230e
node!uv_spawn+278
node!v8::HeapStatistics::total_physical_size+76b7
node!v8::HeapStatistics::total_physical_size+7340
node!v8::HeapStatistics::total_physical_size+7471
node!v8::internal::AllocationSpaceName+12cf0
node!v8::internal::Builtins::WasmStackGuard+27f2
node!v8::internal::Builtins::WasmStackGuard+2be1
node!v8::internal::Builtins::WasmStackGuard+2a2b
```

I cannot remember seeing something like that before though.

**Comment by jrieken** [comment]
Looks like it crashes when spawning a process... (`uv_spawn`)

**Comment by Skuriles** [comment]
Let me know if you need more information about my system or any other information

**Comment by Skuriles** [comment]
Are there any updates on this?

**Comment by Skuriles** [comment]
I re-tried it with newest 19.2 Version. Uninstalled everything, removed %APPDATA%\.vscode folder. Re-installed. 
With Insiders 1.20 it is an other error message (Debugadapter process crash) but still not able to start a simple node project...

**Comment by bpasero** [comment]
@Skuriles are you able to reproduce with this insiders build that is using a new node.js version: https://az764295.vo.msecnd.net/exploration/395608d787740e20d207d278c4d1494995a719a9/VSCode-win32-x64-1.22.0-exploration.zip ?

**Comment by Skuriles** [comment]
@bpasero There were some minor issues with the 1.21 (or a late 1.20) but since then everything seems to work again (with stable and insider). Sorry, forgot to mention that here!
I will try the new insider version today at home but I've working with 1.21 for the few last days/weeks without any issues concerning this bug.
So I think we can close it!
