### ISSUE TITLE
Only show `Report Issue` link when the manifest has one

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#39817]
Testing: #39568

In the view for reporitng issue we include this link even if the package.json does not profile an issues or bug link.

![image](https://user-images.githubusercontent.com/1051190/33675974-41fcea54-da69-11e7-9400-ff7c4672fadf.png)

This is for: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-ai

They do have a GitHub repo so we could fall back to that repo + the issues deep link i.e.
https://github.com/Microsoft/vscode-tools-for-ai/issues

Sean

**Comment by isidorn** [comment]
Nice catch @seanmcbreen 
In this particualr case the problem was that my string magic was cutting of the end of their repo url. That is now fixed.
Apart from that if the xtension is external and has no repo field specified aI do not show the report issue action

**Comment by ramya-rao-a** [comment]
Verified by running from source
