### ISSUE TITLE
When launching extension, debug console shows errors on sourcemap downloads 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39824]
- VSCode Version: Insiders 1.19
- OS Version: Windows

Steps to Reproduce:

1. Launch any extension from its source code
2. The below appears in the debug console
3. The debug config used is the one that's in the snippet for `VS Code Extension Development`

SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\git\out/staging.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\git\out/api.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/services.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\git\out/autofetch.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/documentTracker.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/extension.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/documentMergeConflict.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/mergeConflictParser.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/codelensProvider.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/contentProvider.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/interfaces.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/mergeDecorator.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/delayer.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\merge-conflict\out/commandHandler.js.map
SourceMaps.loadSourceMapContents: Could not download sourcemap from https://ticino.blob.core.windows.net/sourcemaps/12f10aba98bab2f1e5547ba4a5f8fce6d535c0ee/extensions\git\out/decorationProvider.js.map

**Comment by roblourens** [comment]
This is because there's no mac build for that commit (for some reason). I don't want to get rid of the warning. It will go away...
