### ISSUE TITLE
When launching code with --disable-extensions, all extensions show up in the Enabled view

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39823]
- Run `code-insiders --disable-extensions`
- Open the extensions viewlet
- Using the menu, select `Show Enabled Extensions`

**Expected**: No extensions should show up in the viewlet
**Actual**: All installed extensions (other than the ones that may have been disabled using the UI before) show up in the viewlet

**Comment by sandy081** [comment]
Duplicate of #38597

**Comment by ramya-rao-a** [comment]
Well, its not really a duplicate though the root cause might be the same and the same fix, fixed both issues.

Regardless, verified the fix by running from source
