### ISSUE TITLE
Error in console when installing extension from vsix

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39827]
- VSCode Version: Insiders 1.19
- OS Version: Windows

Steps to Reproduce:

1. Install an extension from vsix

**Expected**: Progress Indicator until the success message shows up
**Actual**: No Progress Indicator.

2. Once the success message shows up, open the console

**Expected**: No errors
**Actual**: `Cannot read property 'mainfest' of null`

![image](https://user-images.githubusercontent.com/16890566/33684624-c5c4a92a-da83-11e7-98f7-ff0098b511af.png)

**Comment by sandy081** [comment]
@ramya-rao-a Good catch. Fixed.

**Comment by ramya-rao-a** [comment]
Verified by running from source
