### ISSUE TITLE
[VSCodeEndGameTesting-Aditi][CMD prompt] Command line arguments for "Locale" and "extensions disable" is not working as expected (when app is running).

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#3982]
OS: Windows10
Build #:0.10.12-alpha

Steps:
1. Install app and change the system language setting from command prompt (I set German).
2. Launch app from command prompt with > code-alpha
3. Add C# extension.
3. Try to launch an app again (different instance) from command prompt with locale argument (below commands).
>code-alpha --locale=de-DE
Repeat step 3 with below command.
>code-alpha --disable-extensions

4. No action has been performed.

Actual:
1. Looks like it is trying to re-launch an app but no changes reflected on the UI (still displaying in EN-US or extension remains as it is).
2. There is no message on command prompt about the command result: Success, Failed or error.

Note: When there is no instance of an app running and user try to launch from command prompt then it is working properly.

Expected: When user try to launch an app from command prompt  with argument then it should reflect the changes on the fly, instead of forcing the user to close all the active window and re-launch to get the changes.

**Comment by dbaeumer** [comment]
@bpasero I move this to you since this is a general workbench issue. We can only specify command line args once. I am in favour of closing this. Supporting this is a lot of work for a corner case we fix.

**Comment by bpasero** [comment]
@dbaeumer we actually pass all command line arguments from the second instance to the first but I am not sure where --locale needs to be picked up in order to get the translation.

I would think this is not really a usecase for a user though.

**Comment by bpasero** [comment]
I verified that the second instance gets the right configuration but I am not sure if it is picked up in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/index.html#L101

**Comment by dbaeumer** [comment]
@bpasero  Sorry, wrong explanation on my end. When trying to implement that I noticed that the code for the main menu window is only executed once. So I don't honor the setting in the browser since that would result in mixed UI. Is this still correct?

**Comment by bpasero** [comment]
@dbaeumer if the locale needs to be set on the main side, then yes, a second instance would not change it. However, anything that happens within a window can be changed by passing in CLI args.

**Comment by dbaeumer** [comment]
@bpasero but that would mean the menu bar for example is in English and the window content is in German. I wanted to avoid this since I am pretty sure I would get a bug on this which I couldn't fix.

**Comment by bpasero** [comment]
@dbaeumer good point, I forgot about the menu. I think under this condition we should not do anything and I would not assume this to work with multiple windows and different languages.

**Comment by v-pavanp** [comment]
To add more on this I tried to launch an app by targeting Chinese locale > code-alpha --locale=zh-CN and app didn't launch at all. Also when I tried with >Code-alpha --locale=zh-HK app is launching but it is targeting to English.
I also tried with > code-alpha --locale=fr-FR and code-alpha --locale=de-DE and app is launching with targeted locals. So looks like there are some issues with Chinese locale.

I am following below matrix for the localization :
i.	English VS on English Windows - Passed
ii.	Chinese VS on English Windows - Failed
iii.	German VS on English Windows - Passed but app is not localized across all the sections refer issue # 4204
iv.	English VS on Chinese Windows - NA
v.	Chinese VS on Chinese Windows - NA
vi.	English VS on German Windows - NA

**Comment by dbaeumer** [comment]
Regarding Chinese: the support locale strings are zh-cn & zh-tw. But there seems to be a deeper issue here. The problem might be that the locale string must match the casing on disk which can result in problems.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/4206

**Comment by dbaeumer** [comment]
For the problems in https://github.com/Microsoft/vscode/issues/3982#issuecomment-196495606 see https://github.com/Microsoft/vscode/issues/4206.

I will close this issue since we can't switch the locale in a running VSCode instance.

**Comment by dbaeumer** [comment]
Verified that nothing can be done here.
