### ISSUE TITLE
VSCodeEndGameTesting-Aditi][PHP] Function autocomplete not formatting correctly

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#3983]
OS: Windows 10

Steps:
1. In a php file type "fun" to get function autocomplete.
2. Press Enter.
![phpautocomplete](https://cloud.githubusercontent.com/assets/12900364/13687935/4b252190-e6d3-11e5-80e1-fa3b0bf6f647.JPG)

Expected:
Formatting should be the same as when right-click-> Format Code
![phpautocompleteexpected](https://cloud.githubusercontent.com/assets/12900364/13687963/78eeba96-e6d3-11e5-95fb-b0fac6bef1e1.JPG)

**Comment by aeschli** [comment]
Note that you can customize the templates using Preferences > User Snippets.
For that reason I don't think we should run a formatter on them, as this would change the snippet. The creator of the snippet might have added empty lines and such on purpose.
