### ISSUE TITLE
Editing on long line that exceeds viewport resets viewport

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#39835]
- VSCode Version: Code - Insiders 1.19.0-insider (bd11a1f64eb870a927f3d0e5e4628b3fa066d90c, 2017-12-06T06:07:57.990Z)
- OS Version: Darwin x64 16.7.0

Steps to Reproduce:

1. Have one long line that exceeds viewport
2. Cmd+Right
3. Cursor moves to end, but viewport flickers and stays in the same view so cursor is not in view
4. Cmd+Right again, viewport goes to right which is correct

![view](https://user-images.githubusercontent.com/4033249/33688914-310d6132-da92-11e7-8f30-1e238727196e.gif)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@octref I cannot reproduce. For me, with default settings, the cursor is always revealed.

![kapture 2017-12-07 at 12 30 06](https://user-images.githubusercontent.com/5047891/33713160-68c3f51a-db4a-11e7-97a0-fe2f733651cb.gif)

**Comment by octref** [comment]
It seems to be this extension causing it: https://github.com/TickleForce/vscode-scrolloff/issues/3

Sorry, should've disabled all extensions and run it. I thought only Vim could cause it so I only tested this after disabling vim.
