### ISSUE TITLE
Typescript error displayed as warning

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#39831]
VSCode Version: Code - Insiders 1.19.0-insider (bd11a1f, 2017-12-06T06:07:57.990Z)

Repro steps:
1. Have tsconfig with "noUnusedLocals": true
2. Define and never use a variable in a ts file

Variable has green squiggle under it and a warning is shown in the problems panel.
![image](https://user-images.githubusercontent.com/3672607/33687883-729edf1c-da8e-11e7-86b4-a12818a5a703.png)
Trying to compile results in an error, not a warning. In the stable 1.18 build, this is shown with a red squiggle and marked as an error in the problems panel.

**Comment by mjbvz** [comment]
Thanks. This change was intentional. See https://github.com/Microsoft/vscode/pull/37616  for more info
