### ISSUE TITLE
Git Repo Not Showing

### ISSUE THREAD

**Issue by PhilSykes** [Microsoft/vscode#39848]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vim|vsc|0.10.5

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide reproducable steps and please follow our issue filing steps
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
