### ISSUE TITLE
Guide doesn't grow

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#3984]
As more and more lines are added to a file the guide(s) on the right do not move down when you scroll

**Comment by alexandrudima** [comment]
For verification:
* create empty file
* configure `editor.rulers`
* create many more lines
* Rulers should never "end"

**Comment by jrieken** [comment]
![screen shot 2016-03-21 at 14 02 30](https://cloud.githubusercontent.com/assets/1794099/13919411/99fc271c-ef6d-11e5-8d9c-29cb53e4e09d.png)

Still happens for me (18ebb4a4f5491af7b16e91e42fc36410bbb2e4d7)

**Comment by alexandrudima** [comment]
@jrieken You should verify with ef2a1fc

**Comment by jrieken** [comment]
ok, insiders build is very old then

**Comment by alexandrudima** [comment]
No, we get "updated" to the one from last week.
