### ISSUE TITLE
How to always open markdown file in left hand editor for the right hand editor to preview？

### ISSUE THREAD

**Issue by V0idk** [Microsoft/vscode#39849]
in other word，i want to always active the left hand editor。

[vscode User Interface](https://code.visualstudio.com/docs/getstarted/userinterface)
> Whenever you open another file, the editor that is active will display the content of that file. So if you have two editors side by side and you want to open file 'foo.cs' into the right hand editor, make sure that editor is active (by clicking inside it) before opening file 'foo.cs'.
  When you have more than one editor open you can switch between them quickly by holding the Ctrl (Mac: 'Cmd') key and pressing 1, 2, or 3.

**Comment by bestvow** [comment]
https://marketplace.visualstudio.com/items?itemName=hnw.vscode-auto-open-markdown-preview

**Comment by V0idk** [comment]
抱歉，原来我用的markdown-preview-enhanced有这个问题。auto-open-markdown-preview没有这个问题。但是markdown-preview-enhanced有mathjax渲染。这就尴尬了
