### ISSUE TITLE
[VSCodeEndGameTesting-Aditi][Search][Ember] Searching a large folder causes unresponsive window when running Ember serve

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#3985]
Using Ember-cli server
Steps:
1. Open an ember app folder in VS Code
2. Run ember serve command in Cmd prompt
3. Go to search menu in VS Code
4. Search "welcome"
5. Nearly hangs VS Code window and is very slow when loading files

It seems like it is not filtering out files generated by the server, or the search returns too many results when it usually restricts the number of results.

OS: Windows 10
Version 0.10.12-alpha
Commit d253e034e2a6a17422df292acd2ee3a568606bcd
Date 2016-03-10T11:08:57.021Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by bpasero** [comment]
#3012
