### ISSUE TITLE
Code editor automatically pastes clipboard data

### ISSUE THREAD

**Issue by Keuter** [Microsoft/vscode#39858]
- VSCode Version: 1.18.1 (but also earlier versions)
- OS Version: Ubuntu 17.10, Ubuntu 16.04, macOS High Sierra 10.13.1

Steps to Reproduce:

1. Copy some text
2. Work in VS Code

It is hard to reproduce but me and my co-workers experience the same thing: sometimes text seems to be pasted automatically at multiple locations.

I initially thought it might be my touchpad that I accidentally touch when typing. But also after disabling it, the problem keeps occuring. It happens multiple times per day.

**Comment by rebornix** [comment]
@Keuter can you try `code --disable-extensions` to see if it still happens?
