### ISSUE TITLE
Explorer file sorting

### ISSUE THREAD

**Issue by qifanrui** [Microsoft/vscode#39851]
- VSCode Version:1.18.1
- OS Version:

Steps to Reproduce:

1.我有一个建议，在资源管理器中文件的排序问题，我选择了按文件类型排序，但是我发现它不能满足我的要求。我期望可编辑的文件能排到上边，像图片等不可编辑的文件排在下边。
![1](https://user-images.githubusercontent.com/9126408/33704059-c44fa396-db65-11e7-95d2-052052aa8e49.png)

2.I have a suggestion to sort the files in Explorer, I chose to sort by file type, but I found that it does not meet my requirements. I expect editable files to be routed to the top, and non-editable files like images are listed below.

Reproduces without extensions: Yes/No

**Comment by ljporljp** [comment]
Images can also be editable. But vscode can put a setting table containing  file types sorted by user to meet this, that may meet your need.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27286

**Comment by qifanrui** [comment]
@ljporljp How to operate? Thank you!
