### ISSUE TITLE
Azure Account Sign-In does not work in VSCode when behind proxy

### ISSUE THREAD

**Issue by sathish331977** [Microsoft/vscode#39854]
- VSCode Version:1.8.1
- OS Version: Windows 10 Profssional

Steps to Reproduce:

1. View->Command Pallete-> Azure : Sign In
2. The popup to provide the code to run in browser does not open. This results in not able to sign in to Azure account.
3. Try this without proxy. All works fine. Able to connect Azure account.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
