### ISSUE TITLE
Can't use cursor keys in breakpoint rename input box

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#39855]
This is a general problem with the ListService and using context keys to deal with each command's enablement.

The explorer (or rather workbench tress) does it in a very strange and specific way: it [reacts on tree focus, selection and highlight changes](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L174) and updates the _list is focused_ context key with a debounce of 50ms.

The right way to do this is to have a global context key which is set to `true` every time you're in an `input` or `textarea`. That way we could fix this for every workbench list and tree.

cc @bpasero @isidorn

**Comment by joaomoreno** [comment]
@bpasero This fix also removes the 50ms debouncing. Can you review?

**Comment by bpasero** [comment]
@joaomoreno I left some comments
