### ISSUE TITLE
Formatting html part in vue file (ALT + SHIFT + F) does not work anymore after the update

### ISSUE THREAD

**Issue by thejasper10** [Microsoft/vscode#39859]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: Beautify, Vetur, VueHelper

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
google-complete-me|jay|1.0.6
weex|jay|0.4.0
csharp|ms-|1.13.1
vetur|oct|0.11.3
vuehelper|oys|0.1.0

---

Steps to Reproduce:

1. Create a vue file
2. Make a section <template><span    ></span></template>
3. Press alt+shift+f. Nothing happens

Reproduces without extensions: Yes/No

**Comment by octref** [comment]
https://vuejs.github.io/vetur/formatting.html#js-beautify-html
