### ISSUE TITLE
Add code folding for markdown based on heading level

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [Microsoft/vscode#39852]
Following was closed as duplicate:
https://github.com/Microsoft/vscode/issues/3347
of:
https://github.com/Microsoft/vscode/issues/3422

However 3422 added generic code folding not markdown header folding.

With the latest version of vscode (1.18.1) if I do a foldall it folds the list items starting with `-` and not the headings.

![image](https://user-images.githubusercontent.com/6263572/33705554-a75808c4-db28-11e7-8134-a775969386f3.png)
![image](https://user-images.githubusercontent.com/6263572/33705563-b023aa08-db28-11e7-970c-47b11e4df8fb.png)

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines and ends when there is a line with the same or smaller indent.

To be smarter and to, for example, understand go markdown header syntax, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
#3422 will enable language providers (such as the Markdown plugin) to report language aware folding regions.
