### ISSUE TITLE
Markdown preview: images are not showing up anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#39857]
In our release notes I am no longer seeing images as preview:

![image](https://user-images.githubusercontent.com/900690/33709330-4fb6a548-db3d-11e7-9d49-514a47253409.png)

I think this worked yesterday.

**Comment by bpasero** [comment]
Output in the console:

![image](https://user-images.githubusercontent.com/900690/33709911-34812e22-db3f-11e7-9c98-41ee5840ec0d.png)

Even after disabling the security feature the images to not load.

**Comment by mjbvz** [comment]
Thanks @bpasero! Yes I completely broke this yesterday. Reverting my change with  ebfd5dc to fix things
