### ISSUE TITLE
Check VS Code engine compatibility while installing VSIX extension

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#39853]
Extracted from [here](https://github.com/Microsoft/vscode/issues/33905#issuecomment-349841721)

**Comment by Almenon** [comment]
This would be nice - just ran into this when testing [arepl-vscode ](https://github.com/Almenon/AREPL-vscode)with an older build (may 2017) of vscode.

> Extension is not compatible with Code 1.13.1. Extension requires: ^1.14.0.

**Comment by sandy081** [comment]
Fixed by #47828
