### ISSUE TITLE
Keyboard shortcuts stop working after a while

### ISSUE THREAD

**Issue by DuncanFaulkner** [Microsoft/vscode#39862]
Keyboard short cuts stop working after using VS Code for a while.

- VSCode Version: 1.18.1
- OS Version: ubuntu 16.04

Steps to Reproduce:
1. No really steps to produce this error just happens after using vs code for a while (over an hour or so). Need to reboot VS Code now so will time it and report back.

will need to test this but I've not added any extensions for a while.
Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide more details like reporducable steps and follow our issue filling guidelines
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by DuncanFaulkner** [comment]
Not sure I can add much more to this, the keyboard short cuts just stop working after a while (a few hours from what I can tell) and VS Code needs to be restarted. Code can still be edited and saved (using menu items and not keyboard). Nothing appears to change with VS Code it still looks and operates  as normal, but shortcuts seem to stop working. Not added any new extensions for several months and these don't appear to require any updates as far as I can see at least. 
There are no steps to reproduce this, it just seems to happen at random times.
This seemed to appear in 1.18.1 update, can't say I had noticed it before 1.18.0 and certainly not in previous versions.

I am happy to close this issue, after all, this could be just my installation of VS Code and next release may resolve it.

**Comment by isidorn** [comment]
@DuncanFaulkner please try using vscode insiders and let us know if you can still reproduce the behavior there
https://code.visualstudio.com/insiders/

**Comment by frlinw** [comment]
Same here after an upgrade to version 1.18.1

**Comment by ramya-rao-a** [comment]
@frlinw Do you also see it in the latest Insiders? https://code.visualstudio.com/insiders/

**Comment by DuncanFaulkner** [comment]
Have been running the insiders version all afternoon and I've not experienced the same keyboard short cut issue, will continue to run this for this week at least and will let you know the out come, so far so good.

**Comment by ramya-rao-a** [comment]
Since there has been no update here, I am going to assume that this issue no longer repros in the latest update of 1.19.0

If you do see it again in 1.19.0, feel free to re-open this issue or open a new issue

**Comment by frlinw** [comment]
I can confirm, it's fine in 1.19.0
