### ISSUE TITLE
Clicking on documentation links leads to the wrong link

### ISSUE THREAD

**Issue by ezra100** [Microsoft/vscode#39864]
- VSCode Version: Windows 10
- OS Version: 1.18.1

Steps to Reproduce:

1. Open a JS/TS file and insert the following code:
```
/**
    * @see {@link https://api.jquery.com/each/}
    */
function each()

each()
```
2. Hover over the function call 'each'.
3. Once the popup window shows click the link.

Expected behavior:
The following link should be open [](https://api.jquery.com/each/)
Actual behavior:
The closing bracket is added to the link so it goes to [](https://api.jquery.com/each/})

I'd think that the problem was with the documentation (that it's missing a space before the closing bracket) but since clicking the link on the document itself (not in the popup window) goes to the right link than I guess the problem is with the parsing in the documentation popup window.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This link comes from the TypeScript hover.

**Comment by mjbvz** [comment]
Yes, jsdoc links are currently not parsed properly. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/16498
