### ISSUE TITLE
Rename refactoring not preserved for untyped variable in single source file

### ISSUE THREAD

**Issue by kberg** [Microsoft/vscode#3986]
Consider this snippet of code.

```
interface Person {
    firstname: string;
    lastname: string;
}

function greeter(person : Person) {
    return "Hello, " + person.firstname + " " + person.lastname;
}

var user = {firstname: "Jane", lastname: "User"};
document.body.innerHTML = greeter(user);
```

If I single-rename Person to Blah I get

```
interface Blah {
    firstname: string;
    lastname: string;
}

function greeter(person : Blah) {
    return "Hello, " + person.firstname + " " + person.lastname;
}

var user = {firstname: "Jane", lastname: "User"};
document.body.innerHTML = greeter(user);

```

which is good. If I rename firstname to fname I get
```
interface Blah {
    fname: string;
    lastname: string;
}

function greeter(person : Blah) {
    return "Hello, " + person.fname + " " + person.lastname;
}

var user = {firstname: "Jane", lastname: "User"};
document.body.innerHTML = greeter(user);
```

and a compiler error because user.firstname wasn't renamed.

My colleague's assessment:

> I guess the problem here is that "var user;" gets inferred its own local object type (i.e. an anonymous type that has specific properties). Now when you rename, this type is distinct, and the fact that its value is cast into User at some point is not recognised by the refactoring tooling.

> I think the latter is a valid bug to file against MS. It should be reasonably fixable in the tooling.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7478
