### ISSUE TITLE
Should ask for required permissions if cannot save file because of EACCES

### ISSUE THREAD

**Issue by esmirnov** [Microsoft/vscode#39863]
- VSCode Version: 1.18.1 929bac
- OS Version: macOS 10.13

Steps to Reproduce:
1. Open a file for which user doesn't have permission to write.
2. Change file content
3. Try save file
4. Error message will appear.

Reproduces without extensions: Yes

**Comment by esmirnov** [comment]
@bpasero Could you point me to the duplicated issue?

**Comment by bpasero** [comment]
@esmirnov https://github.com/Microsoft/vscode/labels/run-as-admin
