### ISSUE TITLE
Git popStash doesn't work for non latest stash

### ISSUE THREAD

**Issue by Frozenfire92** [Microsoft/vscode#39867]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Stash multiple things in a git repo
2. Use the `Pop Stash...` from the `...` menu in `Souce Control`
3. Select a stash > 0
4. Notice that the latest stash was used (and not selected index)
```
git stash list
git stash pop
```

Expected

```
git stash list
git stash pop stash@{2}
```

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Verified by running from source
