### ISSUE TITLE
no way to scroll a large definition popup when holding command button

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode#39861]
version 1.18.1 OSX

Step 1) Press command key
Step 2) Hover over function while keep holding cmd
Step 3) If the description is large enough there is no way to be able to scroll the popupbox

**Comment by kieferrm** [comment]
This is also an issue on Windows. When a modifier key is pressed the hover closed when the mouse pointer leaves the bounds of the identifier. This is not the case when no modifier key is pressed. Then the mouse pointer can wander into the hover and the hover stays open.
