### ISSUE TITLE
can not recognize Custom variables in  angular4

### ISSUE THREAD

**Issue by hedonghui** [Microsoft/vscode#39860]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
tslint|eg2|1.0.24
tortoise-svn|fan|0.1.1
Angular4|joh|4.11.2
Angular-BeastCode|Mik|5.1.6
vscode-extension-auto-import|mop|1.3.3
tsimporter|pmn|1.2.14
view-in-browser|qin|0.0.5

---

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/25732160/33710440-802aeb92-db7b-11e7-9c84-49b5202f9158.png)

![1512642328 1](https://user-images.githubusercontent.com/25732160/33710660-3eae226e-db7c-11e7-9f01-975013bf62aa.jpg)
App has no problem (running) , but in vscode  it has wrong

**Comment by aeschli** [comment]
The error does not come from the built-in HTML support. You have to file this against the Angular extension that you use.
