### ISSUE TITLE
Clicking a search result makes the previously shown search result vanish

### ISSUE THREAD

**Issue by tmquinn** [Microsoft/vscode#39874]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.6
vscode-eslint|dba|1.4.3
gitlens|eam|6.3.0
prettier-vscode|esb|0.26.0
vscode-sort-json|ric|1.10.2
code-spell-checker|str|1.5.1

---

Steps to Reproduce:

1. Get a list of global search results
2. Click first result
3. Click second result

Expected:
First search result does not disappears

Actual:
First search result disappears from the list and the total found results counter decrements by 1

Reproduces without extensions: Yes/No

**Comment by tmquinn** [comment]
So this is only occurring on SOME combinations of search terms and files to include

**Comment by roblourens** [comment]
The main reason this would happen is if you're doing a regex search. When the file is opened, the search is refreshed using the javascript regex engine.
