### ISSUE TITLE
Cannot have Diferent layout of terminal in diferent windows

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#39872]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.1.3
jshint|dba|0.10.15
vscode-stylesheet-formatter|dba|0.2.0
vscode-uriencode|die|0.0.1
githistory|don|0.2.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
javac-linter|fau|1.2.6
JSDocTagComplete|Hoo|0.0.2
pgsql-html|hub|0.0.7
java-properties|ith|0.0.2
guid|kos|0.0.1
markdown-shortcuts|mdi|0.8.1
HTMLHint|mka|0.4.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
csharp|ms-|1.13.1
jscs|ms-|0.1.9
debugger-for-chrome|msj|3.5.0
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.3.1
stylelint|shi|0.31.0
addDocComments|ste|0.0.8
sort-lines|Tyr|1.3.0
gitblame|wad|2.2.0
bootstrap-3-snippets|wcw|0.1.0

---

Steps to Reproduce:

1. Open 2 windows
2. Open terminal for both
3. Switch to Vertical view on one
4. Expected only one to change, but both changed.

**Comment by isidorn** [comment]
Fixed in latest stable.

**Comment by andreiropotica** [comment]
Nope, I have the latest stable version.

Maybe it's not released?

**Comment by isidorn** [comment]
It will be released in a couple of days.
If you need it imediatly get the latest vscode insiders

**Comment by andreiropotica** [comment]
Ok, thanks.
