### ISSUE TITLE
Area nearby the snippet's list, that transforms cursor from "text" to "default"

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39876]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

If you look for the specific snippet in the list - there can be some huge descriptions of them, so after expanding (ctrl+space) one of them - it will transform the cursor from "text" state to "default". 

![non-clickable area](https://user-images.githubusercontent.com/24613274/33724416-0d2c0f16-db78-11e7-9024-062f5369d120.gif)

**Comment by ramya-rao-a** [comment]
This is being tracked in #38484
