### ISSUE TITLE
Option+Arrow to move lines mishandles indentation

### ISSUE THREAD

**Issue by TrevorSayre** [Microsoft/vscode#39879]
- VSCode Version: 1.18.1
- OS Version: 10.13.1

Steps to Reproduce:

1. Make a nesting JavaScript object
2. Move a section of the object down using Option+ArrowDown

Reproduces without extensions: Yes

I did specifically quit and relaunch with extensions disabled and was still able to reproduce.

It seems to be okay when moving up through the object, but not okay when moving down through the object. Both cases are shown in the gif below.

![](https://media.giphy.com/media/3oxHQxuHUJP7Kp7wDS/giphy.gif)

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
