### ISSUE TITLE
Sometimes tab is closing when I open other file

### ISSUE THREAD

**Issue by MikailBag** [Microsoft/vscode#39875]
- VSCode Version: 1.8.1
- OS Version: windows-32

Steps to Reproduce:
(I experience this problem not always)
1. Open file A
2. Open file B
3. Tab with file A closes

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by MikailBag** [comment]
Thank's.
It works)
