### ISSUE TITLE
License missing from code.visualstudio.com

### ISSUE THREAD

**Issue by gehrhorn** [Microsoft/vscode#39871]
The license link on https://code.visualstudio.com/License is 404ed. I'm not sure where to submit this. It didn't look right to submit under the docs repository. 

- VSCode Version: any
- OS Version: any

Steps to Reproduce:

1. Visit [https://code.visualstudio.com/License](https://code.visualstudio.com/License)
2. Get a 404

Reproduces without extensions: Yes

**Comment by octref** [comment]
Thanks for letting us know and sorry for the problem! This has been fixed.
