### ISSUE TITLE
Git bash history does not record commands.

### ISSUE THREAD

**Issue by juliandavidmr** [Microsoft/vscode#39877]
- VSCode Version: 1.18.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Ctrl+ñ
2. Type a command in the git bash opened
3. Click to _trash icon_ and close git bash tab
4. Repeat step 1 and 2
5. Press key up in the keyboard. __Note that the command written in step 2 has not been recorded in the gitbash history__

This is not a recent problem, it has been for a long time. Nor is it a git bash problem, since all the commands written in the gitbash (not being embedded in vscode) are stored.

Reproduces without extensions: Yes/**No**

**Comment by Tyriar** [comment]
This appears to be happening because of the way we forcefully kill the git bash process when killing a terminal. Running `exit` works just fine. Let me know if anyone has ideas on how to improve.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43557
