### ISSUE TITLE
Error when terminating a launch config when debugging multiple configs

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39886]
- Launch "Search and Renderer processes" config in vscode repo
- Open quick open to kick off the search process
- Terminate the search process attach config
- See this error:

![image](https://user-images.githubusercontent.com/323878/33733215-f6245d4e-db3d-11e7-9b62-f4443b5eed83.png)

**Comment by isidorn** [comment]
@roblourens I can not reproduce when running out of latest source. I simply follow your steps with doing nothing special on top
Can you maybe stop on exception thrown and find a stack trace that is causing that message? It does not look like it is coming from debug land

**Comment by roblourens** [comment]
On latest insiders, I still see it 100% of the time but only after the first run after reloading the window.

The error itself comes from the extension host. This stack:

```
t.getChildren (extHostTreeViews.ts:103)
e.$getChildren (extHostTreeViews.ts:62)
e.invoke (abstractThreadService.ts:42)
e._invokeHandler (rpcProtocol.ts:109)
e._receiveOneMessage (rpcProtocol.ts:96)
(anonymous) (rpcProtocol.ts:32)
(anonymous) (rpcProtocol.ts:157)
(anonymous) (event.ts:382)
e.fire (event.ts:142)
(anonymous) (ipc.net.ts:81)
emitOne (events.js:96)
emit (events.js:191)
readableAddChunk (_stream_readable.js:178)
Readable.push (_stream_readable.js:136)
onread (net.js:560)
```

**Comment by roblourens** [comment]
It's not coming from one of my installed extensions

**Comment by isidorn** [comment]
My best guess is that it is coming from the loaded scripts view. Thus assigning to @weinand 
@roblourens Can you also reproduce if you hide that view?
