### ISSUE TITLE
background not show f1 and f4?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#39887]
![image](https://user-images.githubusercontent.com/962340/33733974-6be78e50-db59-11e7-8205-5c0672977e5b.png)

background tips could show f1 for commands and f4 for find in files maybe? is that only windows? anyway useful shortcuts that should be shown beside f5?

thanks

**Comment by chrmarti** [comment]
We only show the first shortcut. Showing multiple shortcuts made it much harder to read when I tried.
