### ISSUE TITLE
Running Extensions: Alternate rows do not seem to be using the right color for certain themes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39881]
- VSCode Version: Built from source
- OS Version: Any

Use the `Tomorrow Night Blue` or `Red` theme
The alternate rows use the same grey color which seems out of place for the themes

<img width="409" alt="screen shot 2017-12-07 at 9 14 15 am" src="https://user-images.githubusercontent.com/16890566/33728374-12cf42a6-db2f-11e7-9b84-2c1c0cb47baf.png">
<img width="384" alt="screen shot 2017-12-07 at 9 14 26 am" src="https://user-images.githubusercontent.com/16890566/33728377-14a02992-db2f-11e7-9b30-192c493c8ecf.png">

**Comment by isidorn** [comment]
Will not fix.
Will be addressed by https://github.com/Microsoft/vscode/issues/39783
