### ISSUE TITLE
Lose place in file tree when closing file. 

### ISSUE THREAD

**Issue by realseanp** [Microsoft/vscode#39884]
- VSCode Version: 1.18.1
- OS Version: High sierra

Steps to Reproduce:

1. Open a project with many folders and files (mono repo)
2. Open two files from two separate project folders
3. Close one of the files.
4. Next tab will become active and also the file tree will update to show the newly opened file. This is very inconvenient when working in large file trees and when you want to keep the place in the file tree of the last file that was open, because you are working in that project.

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`
