### ISSUE TITLE
Terminal does not quit after submitting 'exit' command.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#39883]
![image](https://user-images.githubusercontent.com/1499188/33731562-53cf53c4-dba5-11e7-9abb-fbc1aad1b55e.png)

This happened after upgrading macos to 10.13.2.

**Comment by lgw4** [comment]
If you press _return/enter_ a second time, the integrated terminal will exit.

**Comment by ravshansbox** [comment]
Thank you, that worked. Any reasons why?

**Comment by lgw4** [comment]
@ravshansbox I have no idea why. This is certainly a bug with either Visual Studio Code or macOS 10.13.2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37846
