### ISSUE TITLE
Running Extensions: Alternate rows eat up the border 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#39880]
- VSCode Version: Latest Insiders
- OS Version: Any

Steps to Reproduce:

1. Run the "Running Extensions", click anywhere inside the editor
2. A Focus border appears on the editor with the alternate rows eating it up

<img width="871" alt="screen shot 2017-12-07 at 9 01 31 am" src="https://user-images.githubusercontent.com/16890566/33727614-673a625a-db2d-11e7-8745-87aa418b4159.png">

**Comment by isidorn** [comment]
I can not get the border. Where did you click exactly?

**Comment by ramya-rao-a** [comment]
Anywhere inside the editor
