### ISSUE TITLE
Opening a file from command line with line number (--goto) is broken

### ISSUE THREAD

**Issue by arturl** [Microsoft/vscode#39891]
- VSCode Version: 1.18.1
- OS Version: Windows 10 (Fall Creators Update)

Steps to Reproduce:

1. Create a text file `test.txt` with notepad (any file, as long as it has at least 3 lines of text)
2. Try to open it with `code` with a specific line number, such as `code test.txt:3` 

Expected behavior:

Code opens test.txt and places cursor at the 3rd line of text. If the file is already open, code should activate that window and place cursor at the desired position.

Actual behavior:

Code starts but the file does not open. If the file was open, it's not activated. Using `-g` or `--goto` makes no difference.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@arturl I cannot reproduce, can you share a video how this works for you? Does a uninstall and reinstall make any difference?

**Comment by arturl** [comment]
@bpasero, please find the repro [here.](https://1drv.ms/v/s!Akl4awkR2w4lkpVP0FLXD8z9IQZBSw)

As you can see, Code process opens but the file test.txt does not open.

Did not try to reinstall, but I see this problem on two of my PCs that I recently set up.

**Comment by bpasero** [comment]
@arturl the right command would be "`code -g test.txt:3`". Can you try that?

**Comment by arturl** [comment]
You're right, `-g` before the file name works. Sorry for misunderstanding the doc -- I expected it to work like Sublime or Notepad++ (`sublime_text.exe test.txt:3`) Thanks for your help.
Do consider a better error message.
