### ISSUE TITLE
OSS tool fails for v8-inspect-profiler

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#39898]
ERROR: v8-inspect-profiler@0.0.6: No license detail found at repositoryURL: null

Problems:
* the `package.json` lacks a repositoryURL
* it is not under /Microsoft/

**Comment by jrieken** [comment]
> the package.json lacks a repositoryURL

Pushed a new version with a repo-url and updated our dependency to 0.0.7

> it is not under /Microsoft/

It where it is because I was able to create it under MSFT... Not sure that's vital for the OSS tool
