### ISSUE TITLE
WSL: does not run through our CLI script

### ISSUE THREAD

**Issue by spboyer** [Microsoft/vscode#39892]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_19.md#pipe-output-directly-into-vs-code

Version 1.19.0-insider
Commit 3656454687c62594949b71651c8fa70065d16494
Date 2017-12-07T05:15:37.456Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Using WSL as Terminal.

Steps to Reproduce:

1. Use WSL as Terminal
2. `ps aux | grep code | code-insiders`

Does nothing, just line return. Commands without the `|` return the expected data in terminal window as expected.

![image](https://user-images.githubusercontent.com/7681382/33737932-cbb988ae-db65-11e7-9544-d1c82ddbbad3.png)

**Comment by bpasero** [comment]
@spboyer can you run `ps aux | grep code | code-insiders --verbose` and attach the output? Also maybe share your exact setup with WSL so that I can setup my environment like that.

**Comment by Tyriar** [comment]
@bpasero do you need the cli to pipe data to VS Code? The CLI is disabled in WSL https://github.com/Microsoft/vscode/blob/29aeb102dc0ea5ebdfda1b96acf26412b8c6cd03/resources/win32/bin/code.sh#L9

**Comment by spboyer** [comment]
@bpasero the `--verbose` flag just freezes the command. If you want to setup your environment like mine, use this setup from @jldeen
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/jldeen/dotfiles/wsl/configure.sh)"`

* http://jessicadeen.com/tech/microsoft/badass-terminal-fcu-wsl-edition-oh-my-zsh-powerlevel9k-tmux-and-more/

* https://tattoocoder.com/setting-up-my-wsl-environment-azure-cli-docker-and-net/

**Comment by bpasero** [comment]
@Tyriar yes, we need our CLI and I would actually suggest to try hard to get our CLI to work also for WSL. There are many more things that will likely not work if we do not use CLI, for example `--wait`.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/WSL/issues/1494#issuecomment-266757120 this may work to move the environment over now, not sure about whether the streaming data would work across the wsl/batch boundary though?

**Comment by bpasero** [comment]
@Tyriar why exactly is CLI disabled in WSL?

**Comment by Tyriar** [comment]
@bpasero 

```
	# If running under WSL don't pass cli.js to Electron as environment vars
	# cannot be transferred from WSL to Windows
	# See: https://github.com/Microsoft/BashOnWindows/issues/1363
	#      https://github.com/Microsoft/BashOnWindows/issues/1494
```

We need to run electron as node for the CLI. I think there are workarounds for that now though in the comment links.

**Comment by bpasero** [comment]
@Tyriar oh I see, that is odd. So this is only an issue because `ELECTRON_RUN_AS_NODE` does not end up in Electron? I wonder if there are other ways to tell Electron to run as node, e.g. as command line argument.

**Comment by Tyriar** [comment]
@bpasero the workarounds suggest a wrapping bat script which sets the env based on cli args: https://github.com/Microsoft/WSL/issues/1494#issuecomment-266787121

```
./launch_win.sh FOO="bar && rd /s/q %HOMEPATH%\Documents" echo Hello
```

**Comment by bpasero** [comment]
@Tyriar how would that work though? That script seems to leverage `cmd.exe` to set the environment but then we would execute Code through the windows system again and we would basically end up not running Code through the WSL? That can only work if the paths we pass on are actually Windows paths and not Linux paths but since we are in bash, all our paths are Linux paths (`/mnt/c/...`).

**Comment by bpasero** [comment]
@Tyriar actually is sounds like https://github.com/Microsoft/vscode/issues/13138#issuecomment-345358576 is exactly the solution to that problem with a `wslpath` script.

**Comment by bpasero** [comment]
I filed https://github.com/electron/electron/issues/11455 to have an alternate way of forcing Electron to run as node.

**Comment by Tyriar** [comment]
@bpasero 

> then we would execute Code through the windows system again and we would basically end up not running Code through the WSL

Yes, we only support launching the Windows executable via WSL. It is possible to run the Linux version by installing an  server but it can be hard to get working and is flaky/weird. AFAIK the console team doesn't recommend launching GUI apps via WSL generally.

> actually is sounds like #13138 (comment) is exactly the solution to that problem with a wslpath script

Yeah that's to convert the paths, I didn't move on that because wslpath looked so large (and was python), we'd probably want to roll our own converter in the CLI JS.

**Comment by bpasero** [comment]
Isn't this fixed?

**Comment by Tyriar** [comment]
Was merged in May, not the right issue annotation on the PR though https://github.com/Microsoft/vscode/pull/44945
