### ISSUE TITLE
Provide command to open most recently closed file/editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3989]
As far as I can tell a command doesn't exist to do this.

**Comment by bpasero** [comment]
Can you clarify? Would Ctrl+Tab work?

**Comment by Tyriar** [comment]
Essentially <kbd>ctrl</kbd>+<kbd>tab</kbd> with the default keybindings set. However I want it to work when using [`closeFile` and `closeAllFiles` commands](http://www.growingwiththeweb.com/2016/03/simulating-tabs-in-vscode.html) so it behaves like <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>t</kbd> in most tab management systems.

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/726
