### ISSUE TITLE
"The task 'make' is already active..." when trying to run task a second time.

### ISSUE THREAD

**Issue by kisielk** [Microsoft/vscode#39899]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.1.0
haskero|Van|1.3.1
haskell-linter|hoo|0.0.6
vscode-ghc-mod|hoo|1.2.0
hoogle-vscode|jca|0.0.4
language-haskell|jus|2.4.0
vscode-rust|kal|0.4.2
python|ms-|0.8.0
cpptools|ms-|0.14.3
phoityne-vscode|pho|0.0.16
vscode-icons|rob|7.18.1
vscode-tidalcycles|tid|0.4.1
cmake|twx|0.0.17
cmake-tools|vec|0.10.3
vim|vsc|0.10.5
vscode-todo-highlight|way|0.5.11
clang-format|xav|1.6.1

---
Steps to Reproduce:

1. Run my default build task, "make"
2. The task completes in console, make exits, but Code thinks it is still running. Verified task processes complete with `pstree`.
3. I am only able to run the task again after I manually terminate it with the "Tasks: Terminate Task" command.

This just started happening today, as far as I can tell. The only major change was I installed the latest High Sierra update yesterday.

My `tasks.json` is below:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "make",
            "command": "make",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        },
        {
            "label": "clean",
            "command": "make clean",
            "type": "shell",
            "group": "build",
            "problemMatcher": []
        },
        {
            "label": "release",
            "command": "make release",
            "type": "shell",
            "group": "build",
            "problemMatcher": []
        },
        {
            "label": "test",
            "command": "make test",
            "type": "shell",
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
```

Reproduces without extensions: Yes

**Comment by harikrishnan94** [comment]
+1

**Comment by dbaeumer** [comment]
Dups 37846.
