### ISSUE TITLE
[c++] c++11 raw strings not highlighted properly

### ISSUE THREAD

**Issue by jepessen** [Microsoft/vscode#399]
When I write a raw string in c++11 that span among many lines, it's not highlighted properly.

What I see:

![raw-string-bad-highlighted](https://cloud.githubusercontent.com/assets/13927767/11317640/0049bbf8-9035-11e5-813a-6da9d0c034ef.png)

As you can see, raw string has not the string uniform color.

**Comment by aeschli** [comment]
We use the text mate bundle from https://github.com/textmate/c.tmbundle which doesn't seem to support raw string.

**Comment by jepessen** [comment]
Ok. If I try to modify it in order to support raw strings, then should I try to create a pull request for this repository, for the textmate one  one or for both?

**Comment by aeschli** [comment]
For both would be perfect. Otherwise it also works if you do it for text mate first and once accepted, I bring it over.

**Comment by jepessen** [comment]
Ok I'll check when I'll have some time. Regards.

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#30

**Comment by infininight** [comment]
This has been added to the TextMate repository, should be fixed next time the bundle is ported over.

**Comment by mjbvz** [comment]
I believe this is fixed in 1.7+:

![screen shot 2016-11-29 at 2 27 20 pm](https://cloud.githubusercontent.com/assets/12821956/20731613/f50de1e2-b63f-11e6-95d0-6d14fdfaabbb.png)
