### ISSUE TITLE
Typescript extract method fails on methods with arguments of class or interface type

### ISSUE THREAD

**Issue by cristian3d** [Microsoft/vscode#39900]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. On a class, create a method that gets an argument of a class or interface type, ie.
``` 
   public someMethod(hola: SomeClass) {
        console.log(hola);
    }
```
2. Try to extract method on a piece of code that uses that argument. For the exacmple, try to extract `console.log(hola);` It should fail
3. Note that if you change `hola` type to `number`, `string`, etc.  then extract method works. And also if you try to extract code that does not use that argument.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Does this reproduce in VS Code insiders?

**Comment by cristian3d** [comment]
Just tried insiders for the first time. It works fine there, thanks!
