### ISSUE TITLE
The processes PHP and Code Helper make the fan start a few seconds after VSCode is started

### ISSUE THREAD

**Issue by rpkoller** [Microsoft/vscode#39903]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0 (El Capitan 10.11.6)
- MBP 13" early 2011, 8 Gig RAM
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
ACF-Snippet|ant|1.8.3
vscode-twig-pack|baj|1.0.0
vscode-intelephense-client|bme|0.8.2
gitignore|cod|0.5.0
drupal-8-snippets|dss|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
phpcs|ika|0.7.0
VS-code-drupal|mar|0.0.12
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.5.0
php-docblocker|nei|1.3.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I have installed the extensions listed above and loaded a Drupal site folder into my VSCode window
2. I have added the following two lines to the settings in regard of linters: 

```
    "phpcs.enable": true,
    "phpcs.standard": "/users/danton/.composer/vendor/drupal/coder/coder_sniffer/Drupal"
```
3. As soon as VSCode is started the fan starts to run more or less instantly with the PHP and Code Helper processes peaking up to 100% and more processor load when running the `top` command  in the terminal alongside. 
4. If I deactivate PHP Debug, PHP Intelephense, PHP Intellisense and PHPCS and restart, the tasks don't show up anymore and the fan stops. As soon as I reactivate e.g. only PHP Intellisense the processes show up again and the fan starts immediately. Same if I reactivate any of the other extensions or a few of them together. 

If you need any further informations let me know. Best regards Ralf

**Comment by roblourens** [comment]
PHP Intellisense is indexing your php files, which is a work-intensive process. If there's any problem with it you can file an issue on the extension.

**Comment by rpkoller** [comment]
@roblourens  oh haven't noticed the indexing status line. :/ sorry my bad. thanks for the heads up and the fast response!
