### ISSUE TITLE
Different color for the same thing in Monokai Dimmed

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#39905]
![dimmed](https://user-images.githubusercontent.com/9638156/33747180-833fc24c-dbd2-11e7-899c-16ec61e38465.png)

The first one has applied TM selector `variable.other.property`
The second - `variable.other`

What is it?
* Both should be pink
* Both should be blue
* As designed

**Comment by aeschli** [comment]
The JavaScript grammar seems to give the following scopes, 
`variable.other.property.js`
`variable.other.object.property.js`

Not clear why not both times `other.object.property`.
Moving to to https://github.com/Microsoft/TypeScript-tmlanguage

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#553
