### ISSUE TITLE
Las update crashes windows 10 

### ISSUE THREAD

**Issue by jerichoruz** [Microsoft/vscode#39907]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide more details as with the current data we can not do anything.
Here's how to report a good issue https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
