### ISSUE TITLE
Flickering weird pixels between chars

### ISSUE THREAD

**Issue by up-to-you** [Microsoft/vscode#39909]
- VSCode Version: 1.18, 1.19
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. update libfreetype to 2.8.1 (2.8.1-0.1~zesty)
https://www.freetype.org/
2. open any file with or without syntax highlighting
note : 
right - between r and i
border - r and d
inherit - r and i
![weird_pixels](https://user-images.githubusercontent.com/18654738/33748283-aac299c4-dbd8-11e7-9b26-54a67d75f6be.png)

it reproduces on other chars too, depends on zoom level

Reproduces without extensions: Yes

**There are no problems with freetype 2.8.1 in chromium, chrome, electron, cef**

**Comment by alexandrudima** [comment]
Possible dup of #38307 or #35675
