### ISSUE TITLE
Adding a new debug configuration prompts intellisense for another debug config

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#39908]
**Steps:**

1. Open folder with no `launch.json`
2. Go to debug view
3. Click target dropdown and select "Add configuration"
4. Select Node

**Actual:**
Launch.json is generated but focus is set with intellisense dropdown open, which is confusing as pressing enter will select the first dropdown option and generate another launch config.

<img width="1552" alt="screen shot 2017-12-07 at 6 07 29 pm" src="https://user-images.githubusercontent.com/173559/33747831-0b44a83c-db7a-11e7-8f6e-838509d8497e.png">

**Expected:**
Launch.json to be shown with NO dropdown open.

**Comment by weinand** [comment]
I still see this behaviour.

**Comment by isidorn** [comment]
Oh yeah, I confess I broke this when doing some refactoring.
Not a big deal imho -> backlog
