### ISSUE TITLE
Autocomplete popup without having to type property value

### ISSUE THREAD

**Issue by sky47sky** [Microsoft/vscode#39902]
Very interested in Visual Studio Code, however there is a big issue for me in regards to CSS autocomplete behavior. Visual Studio Code makes you start typing a value before it shows the autocomplete popup. However, it should show the available values _before_ you start typing a value. Such as these programs do:

Dreamweaver https://www.screencast.com/t/WXpzqKZps
Atom https://www.screencast.com/t/yqcWFaoQ1nF
Brackets https://www.screencast.com/t/nqgLSZu67

But as you can see in Visual Studio Code, the autocomplete popup doesn't show and forces you to type before it does show: https://www.screencast.com/t/unmcJcfN5I

This is pretty critical for me since I've been accustomed to that method for years. I like just hitting Enter on a property autocomplete, then going straight to the arrows to select a value, without having to start typing a value first. 

Is there an addon that does this if there's no settings to make this happen? Or are you planning on implementing this behavior by default soon hopefully?

**Comment by jrieken** [comment]
@sky47sky Not really sure what you mean. Can you express your thoughts in bullet points? Do you want to show completions on cursor move? So without typing ctrl+space nor without typing?

**Comment by sky47sky** [comment]
Hi sure thing. Here's what I'd like to happen...

- In CSS, I type "te", which brings up autocomplete options like "text-align", "text-decoration" etc.
- I then select "text-align" using the arrows and then the Enter key
- at the same time I press Enter, the available values for "text-align" automatically appear (center, right, left) _without_ me having to type anything

To see what I mean just do the above those other editors I mentioned, and then VSC. You'll see that those editors give you the autocomplete popup automatically after hitting Enter, while VSC waits for you to type part of a value, like "c" for "center" etc.

**Comment by jrieken** [comment]
Ok, please try this with a recent version of VS Code, like https://code.visualstudio.com/insiders/. @aeschli will know since when we have this

![dec-13-2017 10-10-50](https://user-images.githubusercontent.com/1794099/33930646-eb61414c-dfed-11e7-829f-cb329c45ba59.gif)

**Comment by sky47sky** [comment]
Oh wow. That works perfectly! I wasn't even aware of that Insider version. Thanks so much :)

**Comment by jrieken** [comment]
Great, good to hear

**Comment by sky47sky** [comment]
I will point out one issue I'm having though. After I downloaded the Insider version, I added a few of my own snippets. And for some reason my four custom snippets are showing on top of the available values for "text-align", but they have nothing to do with text-align.

![2017-12-13_0443](https://user-images.githubusercontent.com/25274541/33939532-6fb611c6-dfc0-11e7-8e68-2461c7367b61.png)

![2017-12-13_0446](https://user-images.githubusercontent.com/25274541/33939598-a13bd2d0-dfc0-11e7-960e-6a6ae4c9e754.png)

Maybe I'm missing something, but I don't think it's good behavior for every single custom snippet to be showing above the values that are actually relevant to the current property. In the "text-align" instance... center, left, right, etc. should be on top and the custom snippets shouldn't be showing at all. They should only be showing when their specific prefix is being typed out.

I'm going to be adding another 20 or so custom snippets, so it'd be really weird always having to scroll through 20+ custom snippets to get to the relevant ones. Obviously that wouldn't make any sense. Hopefully this can get fixed? Or if there's an add-on that fixes this behavior I'd love to know about it. Thanks for your time.

**Comment by jrieken** [comment]
Running with `"editor.snippetSuggestions": "top",` by any chance?

**Comment by aeschli** [comment]
The original request is a duplicate of #31948, fixed for 1.19.
The snippet issue (better sorting and filtering based on context) should be discussed in a different issue. @jrieken might know if there are already duplicates for those.

**Comment by sky47sky** [comment]
@jrieken that solved it. You're the man.

Sounds good @aeschli Feel free to close this. Thanks for the help.
