### ISSUE TITLE
auto import on typescript class is not working properly

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#39913]
Steps to Reproduce:

The simple way to reproduce, if you follow this one minute guide to create an ionic blank project
https://ionicframework.com/getting-started/

1, create a class .ts and try to add a Hostlistener
2, type HostListener (angular class), it's showing a popup with the available options.
3, Select HostListerer from the popup list (angular class)
4, new import line has been inserted
`import { HostListener } from '@angular/core/src/metadata/directives';`
which is wrong and breaking the build also. I have to copy over to the `@angular/core` import line.

I had an import already "`import {Directive} @angular/core`", and it should have been added there.

Some classes of mine is working as expected, so it's not creating new import line, but frameworks like ionic and angular has got problems.

It's a very annoying basic stuff, which breaks the core functionality of the VSCode.

**Comment by mjbvz** [comment]
Thanks. Tracked by https://github.com/Microsoft/TypeScript/issues/17705 upstream
