### ISSUE TITLE
After using the "Fold All",  the Code line "plus/minus icon" can't change when unfolding.

### ISSUE THREAD

**Issue by Evoque** [Microsoft/vscode#39914]
VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
OS Version: Windows_NT x64 10.0.14393
 
Steps to Reproduce:
    Just using `Fold All`, and click the "plus" icon to unfold.  

AS titled, I Fold the total code of one file use command `Fold All`, But later, I Click the "plus" icon to unfold some line, the code is unfolded, but the icon doesn't change to "minus". 

The screenshots below:
 
 - use the command "Fold All":
![fold](https://user-images.githubusercontent.com/3809046/33750359-6bf17dd8-dc0e-11e7-83d8-73542d9a9d68.png)
- after clicking the "plus" icon:
![unfold](https://user-images.githubusercontent.com/3809046/33750363-6efeccf6-dc0e-11e7-9656-51fdf8e43251.png)

**Comment by Evoque** [comment]
![fold](https://user-images.githubusercontent.com/3809046/33750431-e6fc5e30-dc0e-11e7-88f0-9371e955ac0b.png)

![unfold](https://user-images.githubusercontent.com/3809046/33750435-ebdbc094-dc0e-11e7-8240-e2f573b3c252.png)

**Comment by aeschli** [comment]
This got fixed for 1.19.

**Comment by aeschli** [comment]
duplicate of #38527
