### ISSUE TITLE
Ctrl+k Ctrl+p should prefer fewer segments over more segments

### ISSUE THREAD

**Issue by ad8e** [Microsoft/vscode#39916]
- VSCode Version: 1.18.1

Ctrl+d's algorithm, if "il" is typed, will equally prefer "bu**il**ding" and "s**i**ght **l**ine". It makes more sense to prefer a phrase with fewer separations. For example, with the word "extract", "un**extract**able" should be preferred over "**e**steemed e**x**ac**t**ing **ra**dio **c**on**t**rols".

**Comment by alexandrudima** [comment]
@ad8e Out of the box, <kbd>Ctrl</kbd>+<kbd>D</kbd>, will add a selection to the next instance of the selection, so it will not do any sort of fuzzy searching.

What feature are you referring to ?

**Comment by ad8e** [comment]
I'm sorry, I meant ctrl+k ctrl+p. I forgot I rebound it.

**Comment by alexandrudima** [comment]
I think it is quick open

**Comment by bpasero** [comment]
@ad8e can you show a screen shot of which quick open you mean?

**Comment by ad8e** [comment]
1.18.1.
![test](https://user-images.githubusercontent.com/19739817/34030362-924d828e-e13a-11e7-96c9-9d820588c04a.png)
3 copies of the word anticipation, which is "antici **pati** on". Bottom two aren't matched with "pati", last one has a missing p. The splintered match is preferred over the contiguous "pati", but the contiguous match is preferred when sorting. Having a "better" match places the result behind.

**Comment by ad8e** [comment]
1.19
![test2](https://user-images.githubusercontent.com/19739817/34030953-317766a2-e13d-11e7-9200-ecfd61893319.png)

**Comment by bpasero** [comment]
@ad8e yeah I think this issue is fixed in 1.19, would you agree?

**Comment by ad8e** [comment]
I haven't touched my "lots of files" folder in a week, so I don't know. Finding testcases for this is hard without it. Since fuzzy search has changed in unspecified ways in 1.19, if I encounter problems again in the new version, I'll file a new bug. Closed for 1.18.1.
