### ISSUE TITLE
[theme] Dark+ and Light+ should support git commit message scopes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3991]
Once https://github.com/Microsoft/vscode/issues/3876 is implemented, the following scopes will be available for themes in git commit messages.

- `git-commit.deleted`
- `git-commit.changed`
- `git-commit.inserted`

Example:

```

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   a
#	deleted:    b
#	new file:   c
#
```

**Comment by bpasero** [comment]
@joaomoreno to verify please look at "git commit" as well as "git add -p" because the styles are used in both cases for added, changed and removed. Applies to light and dark theme as well as high contrast.
