### ISSUE TITLE
[off-topic] In likes we trust.

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#39915]
- VSCode Version: 1.19.0-ins
- OS Version: win7x64

Four months ago, on August 10, 2017, I've created an issue https://github.com/Microsoft/vscode/issues/32201, called "24x7 IntelliSense only at the end of words".

That issue was created because of user snippets, which do not appear in the snippets list after we type a dot.

For example, I have `"ael"` snippet, which is responsible for expansion of `addEventListener("click", func);`

![image](https://user-images.githubusercontent.com/24613274/33750500-00c3d85c-dbdd-11e7-8a70-d9cb7a05a878.png)

... and when I type `"ael"` after the dot - the snippets list will suggest you literally everything, **BUT** your custom snippet:

![image](https://user-images.githubusercontent.com/24613274/33750611-dcbf7d7a-dbdd-11e7-8999-ccb2007dda7c.png)

... if you choose the basic addEventListener snippet, it would be like this:
![image](https://user-images.githubusercontent.com/24613274/33750682-5538a6e6-dbde-11e7-8db0-b4d548668969.png)
.. so it has nothing! No tabstops on "event" and function, not even simple parenthesis. Like it's not a method at all. So, my point is - I do not need these basic ridiculous "snippets".
I have to work with my own snippets to minimize the time I have to write the iterative code.
So, here is how expansion of `"ael"` should be look like:
![image](https://user-images.githubusercontent.com/24613274/33750890-9bd1f660-dbdf-11e7-9cb8-a02e775d44d4.png)
... with tabstop on `"click"`(to change it or not), with tabstop on `func`, with semicolon at the end.
And talking about basic snippets - **that's how basic snippets should be look like!**
But let's get back to "after dot" issue.
Seems like at least 70% of all snippets go AFTER THE DOT. Really tons of snippets go after the dot. And in spite of that, VS Code can suggest us to use only that snippets, which you type from the beginning (not being a part of word)? How come?
Ok, it makes a little bit of sense, when snippet cannot appear IN THE MIDDLE of the word. But, why is it so hard to implement a rule, that will tell VS Code, that **_a dot_** is the evident symbol of the end/beginning. So, everything AFTER THE DOT would be counted as "typing from the beginning".
If you don't think that this feature should be implemented by default, just make an option in settings for those people, who be in extra need of that.

Yesterday I've noticed that after on of the latest updates (insiders build) this issue's got even worse. Like it wasn't bad enough...

That's how it worked before:

![ael - before update](https://user-images.githubusercontent.com/24613274/33751439-87971258-dbe3-11e7-91c6-4bb607778f7d.gif)
... you type `"ael"`, do not see your snippet, delete one letter, type it again and it shows up.

That's how it "works" now:
![ael after update](https://user-images.githubusercontent.com/24613274/33751510-034ec60c-dbe4-11e7-8573-3169d412b3d7.gif)
... so now it's not enough to delete and retype a letter. Now you have to type something after your snippet, then delete it, delete one letter of your snippet, and retype it ..... and voila!

I wrote a comment, describing my gratitude, telling "huge thanks" to all participants of this **_as-designed feature_**.

@jrieken deleted it, and wrote that issue does have a chance to be considered. But only after he will see some thousand likes on it. He needs exactly "likes" on the issue. A fact, that he himself made a dozen of references from another issues, where people ask and request to implement that feature - not enough for him.

He needs likes. And subscribers. And something that can heal of the YouTube-mania.

Ridiculous as hell.

**Comment by jrieken** [comment]
fyi @chrisdias @egamma
