### ISSUE TITLE
不能自动判断编码是 UTF8 或 GB2312

### ISSUE THREAD

**Issue by yangzhencheng** [Microsoft/vscode#39912]
- VSCode Version:1.18.1
- OS Version:Win10

Steps to Reproduce:

1.打开编码为GB2312的html文件
2.看到中文乱码

**Comment by viciousstar** [comment]
是啊，我也有这个问题

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps so we can react on it

**Comment by yangzhencheng** [comment]
this soft is not support to analyze file encoding format by itself. such as: gb2312.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
