### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by henryoh007** [Microsoft/vscode#39911]
- VSCode Version:  VSCodeSetup-x64-1.18.1
- OS Version: windows 10 pro 1709

Steps to Reproduce:
 downloaded latest version of visual studio and it shows a black screen with top menu cannot toggle any side bar windows, cannot open projects .. BLACK SCREEN

1.
2.
![image](https://user-images.githubusercontent.com/4348214/33748842-9e028996-db7f-11e7-9b13-e1fc7e853063.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by henryoh007** [comment]
I tried .opening files but all I get is a black screen  I downloaed the nightly insiders build ? Can you provide me with older build .. ?? 

Thanks Henry  415 678-6320. I am available earlier morning 9:00 AM PST 
![image](https://user-images.githubusercontent.com/4348214/33783745-d93908bc-dc12-11e7-98b8-a95e12732a79.png)

**Comment by bpasero** [comment]
@henryoh007 does it reproduce if you run `code --disable-gpu` ?

**Comment by henryoh007** [comment]
OMG that worked ...YES !!  Thanks a ton  Henry

**Comment by henryoh007** [comment]
Now that it is working was expecting a new version that will launch and have --disable-gpu in default settings.. How can this task be accomplished in the default settings ??
