### ISSUE TITLE
How to quickly jump.Less files？

### ISSUE THREAD

**Issue by Linbubin** [Microsoft/vscode#39910]
I can ctrl + left mouse  to  jump js files
![image](https://user-images.githubusercontent.com/19225429/33748306-b38d5e02-dc02-11e7-85fe-0900189487ba.png)

but when I do it for .less file, no reaction

Is there any configuration or plug-in that can quickly locate the corresponding .less file

**Comment by aeschli** [comment]
duplicate of #29899
