### ISSUE TITLE
[Feature] Allow us to change between pull and rebase

### ISSUE THREAD

**Issue by KingDGrizzle** [Microsoft/vscode#39917]
- VSCode Version: 1.19.0-insider Commit bc206bbacc13e48d4422b8c73334aa9dd6f782df
- OS Version: Windows 10 Fall Creators Update x64

So, when I do git commits, and someone else does git commits on the same files, they use rebase so that they avoid `merge commits`. When I click this button (the circle one) ![link](https://i.kingdgrizzle.ml/2017/12/S3M6q9.png), it does a pull, then a merge commit.

I'd like if we are able to change this instead of me having to go `F1 -> Git pull -> Arrow Down -> enter`, or going to the git tab, clicking the 3 dots and clicking `Pull (Rebase)`

If this is already possible please let me know

**Comment by joaomoreno** [comment]
Usually, people just configure pull to use rebase in their repo:

```
git config pull.rebase true
```

Is this information sufficient for you?

**Comment by KingDGrizzle** [comment]
I'll try this and let you know. But yeah, this is probably what I wanted 😃
