### ISSUE TITLE
Travis errors often due to Github request limit for vscode.d.ts

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#3992]
With the new method of fetching `vscode.d.ts` during `npm install` my Travis CI builds error because of exceeding the GitHub API rate limit. This becomes very irritating. I am unsure if this is an problem with how Travis' servers connect to GitHub (seems unlikely due to their relationship) or how `node_modules/vscode/npm/install` requests the file. Possibly requesting the file from a different hosting solution may be an option as well.

Here is my Travis CI page https://travis-ci.org/tht13/gerrit-vscode

See the error below, Travis attempts `npm install` 3 times before giving up.

```
> node ./node_modules/vscode/bin/install
Detected VS Code engine version: ^0.10.8
Error installing vscode.d.ts: Error: Expected an array of tags, but received: {"message":"API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Comment by bpasero** [comment]
@tht13 if you set the GITHUB_TOKEN environment variable, this issue is gone.

**Comment by tht13** [comment]
Thanks @bpasero  :smile:

**Comment by bpasero** [comment]
@tht13 actually I pushed a new version of vscode@0.11.8 that in case of GH rate limit error just falls back to a well known list of tags. So you should be good either way.

**Comment by tht13** [comment]
Even better :+1:
