### ISSUE TITLE
Problems connecting to Azure App

### ISSUE THREAD

**Issue by Alistair67** [Microsoft/vscode#39922]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.4.0
azure-account|ms-|0.2.2

When I try to sign in to the Azure account for the app I want to manage I am taken to a page that asks me to enter a code the application sent to my device. I am using my boss's Microsoft Account as that is the account used to create the app on Azure. The code has not come to his phone or work PC and so I assume is being sent to his personal PC which we don't have access to in the office. Is there any way to get the extension to connect me using the login and password, or is there some way to get the code to go to a particular device on his account like his work PC or phone?

Sorry if this is not the right place to post this, but I can't find anything about this online and it is getting extremely frustrating. Any help appreciated.

Cheers, Alistair

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
