### ISSUE TITLE
link problems to raw terminal output

### ISSUE THREAD

**Issue by doudou** [microsoft/vscode#39920]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

VSCode's problem matcher is really limited right now (especially for multi-line messages). One thing that would improve the situation quite a bit would be to allow moving between the output and the reporter, i.e. to jump to the line in the raw output where the problem matched.

The cherry on top would be to allow for patterns that don't register anything *but* would add hyperlinks to the console output (to file/lines). We could this way easily browse backtraces in the raw output, without necessarily changing the reporting system.

**Comment by dbaeumer** [comment]
This dups https://github.com/Microsoft/vscode/issues/21928 which is blocked by https://github.com/Microsoft/vscode/issues/23263

**Comment by doudou** [comment]
#21928 is really the "cherry on top". The gist of this feature request was to be able to jump to the specific output line in the terminal, from the problem (in the problem view) that was matched there.
