### ISSUE TITLE
initialize workspaceFolders with an empty array instead of leaving undefined

### ISSUE THREAD

**Issue by doudou** [Microsoft/vscode#39923]
- VSCode Version: 1.18.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. generate a new extension (let's call it `workspacefolders-init-value`)
2. add breakpoint in the extension's activate method
3. run the extension in the debugger
4. activate the extension
5. inspect the `vscode.workspace.workspaceFolders` value. It is `undefined`

I would have expected `[]` (i.e. no folders), which is to me a more natural null value for this attribute in this context.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
That is on purpose and describes the different between not opening a workspace (e.g. just a file) and opening a workspace without any folders.

**Comment by doudou** [comment]
I indeed misread the documentation. Sorry for the noise.
