### ISSUE TITLE
open integrated terminal instead of system default terminal

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#39925]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:44:48.751Z)
- OS Version: Linux x64 4.10.0-40-generic
- Extensions: none
---

Steps to Reproduce:

1. right click exporer of the vscode
2. click  Open in Command Prompt
3. integrated terminal shown

expected:
system terminal => gnome-terminal 
shown.

**Comment by Tyriar** [comment]
The default explorer terminal was changed to the integrated terminal not too long ago. You can go back to the external terminal with the setting:

```js
"terminal.explorerKind": "external"
```
