### ISSUE TITLE
Markdown: whitespace removed on save

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#39928]
Insiders, OS X

Have  no settings in your settings.json, open a markdown file, have a whitespace on the end of a line. Cmd + S = removes the whitespace, why? formatOnSave should be false by default?

Also, if I turn on autosave, he always removes whitespaces and I can not edit my markdown in any reasonable way. I find this issue quite frustrating.

**Comment by carlca** [comment]
I'm getting this exact problem using Insiders on OS X. Would installing one of the Markdown Prettier extensions help, I wonder?

**Comment by isidorn** [comment]
After writing the release notes I found it very frustrating, adding important to raise awarness

**Comment by carlca** [comment]
I've just discovered that if I have FrontMatter like this:
![screen shot 2017-12-08 at 16 09 45](https://user-images.githubusercontent.com/260612/33774189-4f2b982c-dc32-11e7-87ef-39ade17a4ad5.png)

Then my whitespace is preserved.

If my FrontMatter is bounded by +++ then all the whitespace disappears.

The only `format-on-save` thing I have is part of my Golang setup and shouldn't be affecting things here.

**Comment by carlca** [comment]
I spoke too soon. I've some indented text like so:

![screen shot 2017-12-08 at 16 32 27](https://user-images.githubusercontent.com/260612/33775183-7ffae6b2-dc35-11e7-8daf-5a9125853c12.png)

Doing Cmd S messes up the formatting to give:

![screen shot 2017-12-08 at 16 34 27](https://user-images.githubusercontent.com/260612/33775275-bcd79cc4-dc35-11e7-9366-f2dc48f9ccf8.png)

It's really frustrating!

**Comment by mjbvz** [comment]
We don't ship any built-in markdown formatter. @isidorn Do you ahve `  "editor.trimAutoWhitespace": true` or `  "files.trimTrailingWhitespace": true` set? How about with extensions disabled?

**Comment by carlca** [comment]
I've just tried it in VSCode (Stable) and the problem does not occur.

**Comment by carlca** [comment]
I've just tried in in VSCode (Insiders) and the problem is present.

**Comment by regs01** [comment]
Indeed trimmig shouldn't trim if there are 2 trailing spaces in markdown.

**Comment by carlca** [comment]
@regs01 So are you suggesting that at the end of every line we leave 2 trailing spaces or at the end of the file. Please be more specific, thanks.

**Comment by regs01** [comment]
i'm talking about new line break (two trailing spaces)

**Comment by isidorn** [comment]
@mjbvz my bad, the issue is that the workspace has `"files.trimTrailingWhitespace": true`
However I would not expect that it behaves this badly in markdown.
Also I am sure that this changed in the last milesonte, so not sure if somebody added that option to the vscode-docs reposotiory or the behavior changed

**Comment by eteisman** [comment]
Here are my settings:

    "files.trimTrailingWhitespace": true,
    "[markdown]": {
        "files.trimTrailingWhitespace": false
    },

With this, the trimTrailingWhitespace settings is ignored for Markdown files.

**Comment by TheIncorrigible1** [comment]
@eteisman Are you experiencing the problem in the issue?  or are you sharing your config so they can fix their own issues?

**Comment by mjbvz** [comment]
@isidorn Do you see the same behavior in other file types? Is it only effecting the currently line you are working on or corrupting the entire file?

**Comment by isidorn** [comment]
@mjbvz I only see it in markdown. It is only affecting the current line while I am typing.
Can you not repro this on your mac? Just open the vscode-docs repository?

If you need more details or a live sharing session just ping me on slack :)

**Comment by mjbvz** [comment]
@isidorn All I see is the whitespace at the end of the line being removed whenever the file is saved. I don't understand what this breaks or why this prevents editing the file. Can you you post up a gif of the problem

**Comment by isidorn** [comment]
@mjbvz no longer happening with latest insiders. It seems like somebody fixed it. Closing.
I believe the issue was that the auto save event was firing the same way as if I would hit manually cmd + s which triggers the removal of whitespace (as expected).
