### ISSUE TITLE
Python process does not terminate after Ctrl+F5

### ISSUE THREAD

**Issue by alonke** [Microsoft/vscode#39927]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Ctrl + F5 on a python script

The script runs for the first time. Afterwards neither F5 or Ctrl+F5 work anymore. Only running it from the command palette as "debug Python" will run it. At this point the call stack shows two python processes. The running one and the one ran using Ctrl+F5, which is is not possible to terminate.

Reproduces without extensions: No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-python#379
