### ISSUE TITLE
Terminal text become unreadable in Mac

### ISSUE THREAD

**Issue by JiatangDong** [Microsoft/vscode#39937]
![screen shot 2017-12-08 at 10 09 14 am](https://user-images.githubusercontent.com/2363256/33779062-3da39ffa-dc00-11e7-806f-64c29daa332e.png)
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3

---

Steps to Reproduce:

1. Just leave the window idle for a while.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
