### ISSUE TITLE
Feature request: List editing in markdown

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [Microsoft/vscode#39932]
Pressing enter at the end of a list item should create a new item:

- Item1 
- Item 2 `<enter>`
- 

Unless the current item is blank, in which case the list ends:
- Item1
- `<enter>`

This is supported in sublime text and makes list editing very convenient.

**Comment by mjbvz** [comment]
duplicate of #14010

Try using the https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one extension
