### ISSUE TITLE
Comment block should handle nested comments

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#3993]
![image](https://cloud.githubusercontent.com/assets/7921431/13696010/8e716974-e79e-11e5-89c7-87a537c246c8.png)
after `ctrl+/`
![image](https://cloud.githubusercontent.com/assets/7921431/13696033/9eda04a6-e79e-11e5-941c-a8b3d4cf6ac7.png)

**Comment by aeschli** [comment]
@alexandrudima To solve that, commenting probably needs to be done by the language mode As to correctly parse the commented region.
But I'd say to close. Limitation as designed

**Comment by alexandrudima** [comment]
The command, as designed, inserts /* before the selection and */ after the selection. It does not examine the selected text in any way. e.g. a follow up feature request could be to comment in such a way as to not introduce syntax errors, which is outside of the scope of such a command.
