### ISSUE TITLE
is there an api can control the highlight process in the completion list?

### ISSUE THREAD

**Issue by siumennel** [Microsoft/vscode#39938]
I am developing an extension to deal with Japanese feature file. not as English word separated by space, Japanese words don't have space to separate each other. I found that the filter to the completion list starts with the word which has space before it.

for example:
there is a complete list :
i have a dream
i have an icecream
when i type 'a' then ctl space, the 'a' and 'an' are highlighted.

but in the Japanese language,
there is a complete list :
私は夢ひとつを持ってます。
私はアイスクリームひとつを持ってます。

ひとつ　means a,one.
when I type 'ひとつ' then ctl+space, the 'ひとつ' cannot be highlighted. and even worse, the completion list itself cannot be shown.

So I tried this.
there is a complete list :
私 は 夢 ひとつ を 持って ます。
私 は アイスクリーム ひとつ を 持ってます。
when I type 'ひとつ' then ctl+space, the 'ひとつ' can be highlighted!
but in fact, Japanese language does not need this kind of space-separated style.
I want an API can make me control the filer and highlight process and implement my own logic process . is it possible?

**Comment by jrieken** [comment]
@siumennel Is this word based suggestion you are referring too? So some text and you want each "word" of that text be suggested, right?

<img width="357" alt="screen shot 2017-12-11 at 10 42 10" src="https://user-images.githubusercontent.com/1794099/33824839-f481b07a-de5f-11e7-9068-cab906cdf586.png">
