### ISSUE TITLE
**Warn** command `markdown.extension.onBackspaceKey` not found.

### ISSUE THREAD

**Issue by cba85** [Microsoft/vscode#39930]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
format-php|Kas|1.1.2
html-css-class-completion|Zig|1.14.0
html-snippets|abu|0.1.0
color-info|bie|0.5.0
path-intellisense|chr|1.4.2
gitlens|eam|6.3.0
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
php-pack|fel|1.0.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
php-cs-fixer|jun|0.1.51
mssql|ms-|1.2.1
php-docblocker|nei|1.3.2
vscode-todo-highlight|way|0.5.11
markdown-all-in-one|yzh|0.11.2
vscode-open-in-github|ziy|1.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

When I open a markdown file with HTML code inside, like `<p>lorem ipsum</p>` and want to delete the tags using keyboard (`<p>` for example), I have this message:

**Warn** command `markdown.extension.onBackspaceKey` not found.

The error appears for tab key too:

**Warn** command `markdown.extension.onTabKey` not found.

Reproduces without extensions: No. I suspect Markdown All in One.

**Comment by mjbvz** [comment]
Please file this issue against your markdown extension
