### ISSUE TITLE
typescript stop five twice

### ISSUE THREAD

**Issue by terrilltang** [Microsoft/vscode#39934]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|3.5.0
language-stylus|sys|1.8.0
stylus-supremacy|thi|2.6.1
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Provide nice details about reproducing and I will reopen
