### ISSUE TITLE
Consider renaming "args" to "applicationArgs" in launch.json

### ISSUE THREAD

**Issue by niieani** [Microsoft/vscode#39941]
I've often struggled to know and remember which parameter in launch.json is the right one to pass to Node vs to my application ("args" / "runtimeArgs"). Today on Twitter I saw that [I am not alone](https://twitter.com/linclark/status/938934075016048640) with this issue. 

Both "args" and "runtimeArgs" are somewhat ambiguous. The word "runtime" has two meanings ("[runtime environment](https://en.wikipedia.org/wiki/Runtime_system)" or "[execution time](https://en.wikipedia.org/wiki/Run_time_(program_lifecycle_phase))") which make it prone for misunderstandings. On the other hand "args" has no prefix. As a solution I propose renaming "args" to "applicationArgs" (or at least aliasing it, to avoid breaking changes). `applicationArgs` is pretty unambiguous and intuitively means that these arguments will be passed into your app, and not to the Runtime Environment.

Explicitly prefixing both parameters has the extra benefit of making it easier to infer there are other types of `-args` that you may configure.

CC: @auchenberg

**Comment by weinand** [comment]
We have been there before: initially we had "programArgs" vs. "runtimeArgs". Before we shipped VS Code 1.0 we decided to use the shorter and more common "args" for the 95% case and the longer "runtimeArgs" for the 5% case.
Changing this again is no longer an option.
In addition all these launch attributes are not defined by VS Code but by the individual debug adapters. So we can only change this for node-debug. But all the other debug extensions that copied us, wouldn't follow us. So we would end up with more confusing inconsistencies.
