### ISSUE TITLE
파이썬 디버깅이 안걸려요..!!

### ISSUE THREAD

**Issue by jueyini** [Microsoft/vscode#39943]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
vscode-boot-dev-pack|Piv|0.0.2
vscode-boot-java|Piv|0.1.1-201711272258
vscode-boot-properties|Piv|0.1.0
vscode-bosh|Piv|0.1.1-201711272258
vscode-concourse|Piv|0.1.1-201711272258
vscode-manifest-yaml|Piv|0.1.0
java|red|0.15.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
---

Steps to Reproduce:

1. 코드..
print ("Hello World")   <-- 중단점
print ("Hello World")   <---중담점
raise NotImplementedError
print ("Hello World")

2. 디버깅 모드 'F5'로 실행

3.  
중단점(break point)을 걸어도 해당 지점에서 디버깅되지 않고 그냥 실행됨
그리고 디버그 사이드 바에서 예외에 경우에도 중단점이 걸리게 했는데
디버그콘솔창에 두번째 Hello World 까지와 예외 메시지를 뿌리고는
중단점이 걸리지 않고 디버깅 모드가 그냥 종료됩니다.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Please file this issue against the Java extension.
