### ISSUE TITLE
Add link handler command for html previews

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#39946]
**Problem**
#39945. In the the markdown preview, we would like to treat links to `./a` the same as `./a.md`. To do this, we can use a command link instead of regular file link, i.e:

```md
[link](./a)
```

becomes

```html
<a href="command:markdown.openLink?./a">link</a>
```

Then, the `markdown.openLink` command can try to open either `./a` or `./a.md`

We can already make this change manually in the markdown extension, but I think that other extensions may benefit from being able to control what happens when a user clicks on a link in a webview.

**Proposal**
Add a new field on `HtmlInputOptions` called `linkCommand`:

```ts
export interface HtmlInputOptions {
	allowScripts?: boolean;
	allowSvgs?: boolean;
	svgWhiteList?: string[];
        linkCommand:? string;
}
```

When a link is clicked in the webview, invoke `linkCommand` with the uri of the link. The markdown preview for example would pass  `markdown.openLink` as the `linkCommand`

This would allow the extension to perform its own validation before opening a link and also implement custom link handling logic

**Comment by roblourens** [comment]
> In the the markdown preview, we would like to treat links to ./a the same as ./a.md

Why do you want to do that?

**Comment by mjbvz** [comment]
@roblourens Because this is how many wiki and docs systems work, including github. The behavior for clicking on `./a` would be:

1. Open `./a` if it exists
2. Otherwise fallback to opening `./a.md`

**Comment by octref** [comment]
I'm not against it, but I'd appreciate some docs on the options.

This issue is the first time I learned about the `HtmlInputOptions`. We also have a bunch of other `complex commands` (the name itself is confusing) with a param called `options`, but we don't document any of the options: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by jrieken** [comment]
No surprise but I am against adding more and more complexity to the preview command. The whole webview things is sketchy and we shouldn't continue to embrace it with more (semi) official APIs. 

Can't you solve your problem (`./a` vs `./a.md`) in the the md to html phase? So, when encountering a link like that do what you command will do later and simply generate a different link?

**Comment by mjbvz** [comment]
@jrieken Yes, the fix is pretty easy in the markdown extension. Either:

- Rewrite all markdown local links to command links in the markdow->html stage
- Add a custom onclick link handler to webview page itself. We already do this in the top level webview logic to handle links in the first place

However this functionality could be useful for other webviews for the same reasons it is useful to the markdown preview. The other potential benifit is that an extension could use this to explicitly forbid links from being opened by registering a noop handler or to only allow links to certain content (such as only opening links to https://developer.mozilla.org for example)

**Comment by jrieken** [comment]
> However this functionality could be useful for other webviews for the same reasons it is useful to the markdown preview

Do we have anyone asking for this or being blocked by this? My plan is to not grow on the webview because it's such a mess and we will promise things it cannot hold up to. Everything we add for the webview-today we will have to support in a future, more stable, solution and because we have no clue what that will be yet it's risky to add more features.

**Comment by mjbvz** [comment]
Ok. Will do special case handling of this case in the markdown extension
