### ISSUE TITLE
Caret position is wrong after select a candidate from auto-complete for Powershell New-object cmdlet

### ISSUE THREAD

**Issue by Isa-rentacs** [Microsoft/vscode#3994]
Here are the steps to repro.

1. Launch VSCode
2. Change the mode to Powershell
3. Type ` $obj = New-Object ""`
4. Move the caret between double quotations.
5. Type` system.col`
6. Auto-complete shows Collections (For System.Collections)
7. Choose it

Expected:
"Collections" will be inserted and the caret will be moved just before the second double quotation. 

Actual:
"Collections" is inserted but the caret remains the same position.

Note:
VS Version 0.10.10

**Comment by weinand** [comment]
@daviwil is this a problem in the PowerShell extension or in VS Code? If the former I can move this issue over.

**Comment by daviwil** [comment]
That depends on what VS Code uses to determine where the caret goes after the completion.  I'm able to reproduce this issue also.  Nothing has changed in our completion provider in the last couple PowerShell extension updates.

Is it possible that the semantics of CompletionItem.textEdit have changed in this release?

**Comment by alexandrudima** [comment]
@daviwil I just looked into this and the edits I get in the editor:

The file contents are (the `|` denotes the cursor):
```
$obj = New-Object "system.col|"
```

And the generated edit from accepting the suggestion is replace `"system.col"` with `"System.Collections"`

This makes it that the cursor is inside the replaced range, in which case it stays put.

If the generated edit from accepting the suggestion would be replace `system.col` with `System.Collections` <-- notice that double quotes are left untouched then the cursor is at the end of the replaced range, in which case it goes to the end of the new inserted text.

Here is the current behaviour:
![collections-current](https://cloud.githubusercontent.com/assets/5047891/13786463/f4b81e6c-ead7-11e5-8926-ce868ef81d45.gif)

And here would be the behaviour if the suggestions would not contain the leading and trailing double quotes:
![collections-patched](https://cloud.githubusercontent.com/assets/5047891/13786479/0386416c-ead8-11e5-9c52-ff2df8217489.gif)

**Comment by daviwil** [comment]
Thanks for looking into this, Alex!  Even if we removed the quotation marks aroung the completion text, the problem still remains that the cursor is not being placed after the quoted string (which is the behavior in the PowerShell ISE:

![intellisense](https://cloud.githubusercontent.com/assets/79405/13787033/73a18dda-ea97-11e5-9207-a628c6d7d1ee.gif)

Since we're replacing a whole substring, is there any way we can have the caret be placed just after the completed substring?  Could we possibly add some way to configure the cursor position after the completion?

**Comment by daviwil** [comment]
Awesome, thanks a lot for making that change Alex!  It seems like this behavior should come automatically with no extra work on my side, correct?

**Comment by alexandrudima** [comment]
Yes, here is the behaviour on master:

![ps-cursor-position](https://cloud.githubusercontent.com/assets/5047891/13840588/a2a02212-ec23-11e5-8e78-4088d547ae8e.gif)

It is still not what the OP wanted, but that can only be changed by providing different suggestions.
