### ISSUE TITLE
Zalgo eats my terminal

### ISSUE THREAD

**Issue by SomeKittens** [Microsoft/vscode#39940]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Terminal: iTerm 3.1.beta.4, zsh, oh-my-zsh, `mh` theme.
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.11.1
code-settings-sync|Sha|2.8.6
vscode-javascript-snippet-pack|aka|0.1.5
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
angular2-switcher|inf|0.1.4
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.11.2
prettify-json|moh|0.0.3
python|ms-|0.8.0
sublime-keybindings|ms-|3.0.3
angular2-inline|nat|0.0.17
sass-indented|rob|1.4.5
trailing-spaces|sha|0.2.11
autoimport|ste|1.5.3

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open a previously-used terminal via cmd+`
2. Resize the terminal
3. H̡̬̮̝̍̈́ͩẺ̹̪̙̪͑ͥ̉ͣ̈ ̵̻̝̞͉ͭ̂ͬC̥̙̜͍̃ͧ̊̿̓̽͞Ȏ̠͍͔͎̔̏̃M̑E̶̞̹̗̮̱͙̠ͨ̀͗͊ͫ̃ͤṠ̻͈́

<img width="1416" alt="screen shot 2017-12-08 at 11 07 02 am" src="https://user-images.githubusercontent.com/1616464/33781093-22d50bfc-dc08-11e7-8f94-303991be5d7c.png">

Further resizing does not fix this, nor does opening and closing the terminal drawer.  I have to kill the current session entirely.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901

@SomeKittens if something more than the text is being cut off could you create add more details on how the terminal breaks? Everything seems to work fine for me apart from the trimmed chars on macOS/Linux.
