### ISSUE TITLE
color preview & popup in json?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#39948]
![customa](https://user-images.githubusercontent.com/962340/33789609-d279a5ec-dc47-11e7-9064-a6028d618a7b.png)

please show the color preview & popup for json files too

https://github.com/Microsoft/vscode/issues/34663

**Comment by aeschli** [comment]
As described in #34663, color decorators are shown in JSON files when the JSON file is associated to a JSON schema, and the schema pf the property describes the property with `"format": "color-hex"`.

colorExample.json:
```
{
    "$schema": "./colorExample.schema.json",
    "someColorProperty": "#F00"
}
```
colorExample.schema.json:
```
{
   "type": "object",
   "properties": {
       "someColorProperty": {
           "format": "color-hex"
       }
   }
}
```
Find more information on JSON schema and schema associations here:
https://code.visualstudio.com/docs/languages/json#_json-schemas-settings
