### ISSUE TITLE
tasks.json without "label" property gives error with old property name

### ISSUE THREAD

**Issue by obiwanjacobi** [Microsoft/vscode#39958]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
CppSnippets|har|0.0.13
csharpextensions|jch|1.3.0
Go|luk|0.6.69
cpptools|ms-|0.14.3
csharp|ms-|1.13.1
node-debug2|ms-|1.19.3
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
java|red|0.15.0
classynaming|ref|1.1.1
rust|rus|0.3.2
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1. Create a new task in tasks.json but do not specify the 'label' property.
2. Run the task
3. > Error: tasks must provide a taskName property. The task will be ignored
4. "taskName" is not even a valid property name anymore.

Reproduces without extensions: No, then it comes with a different error:
"error TS5014: Failed to parse file '[project]/tsconfig.json/tsconfig.json': Unexpected token u in JSON at position 0." which is why I was making tasks in the first place - to work around this problem.

**Comment by dbaeumer** [comment]
This got already addressed for the next stable build
