### ISSUE TITLE
Again SQL Syntax Highlighting not working when escaping strings

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [Microsoft/vscode#39950]
I'm creating again this issue because @isidorn closed #39822 and didn't even took a moment to test if the issue is really part of the core or an extension.

- VSCode Version: 1.18.1
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Create a SQL query escaping something inside a string (See GIF)
![error_vscode_3](https://user-images.githubusercontent.com/5341310/33680479-5d3d8a58-da87-11e7-9f67-ec8b74ed551b.gif)

Reproduces without extensions: Yes

IT CAN BE REPRODUCED WITHOUT ANY EXTENSION ENABLED

**Comment by isidorn** [comment]
@MikeVelazcoMtz sorry about that, my mistake

**Comment by aeschli** [comment]
We use the SQL grammar from https://github.com/Microsoft/vscode-mssql.
When fixed there, we will update our grammar file.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-mssql#1047
