### ISSUE TITLE
WSL in tasks not load .bashrc or .profile, can't find my npm

### ISSUE THREAD

**Issue by Wyntal** [Microsoft/vscode#39953]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vscode-icons|rob|7.18.1

---
**condition**
I installed linuxbrew in WSL, and use linuxbrew to install node, npm.
I want to use vscode to launch npm scripts in WSL, but I found the `npm` is not found in tasks `PATH`.
![image](https://user-images.githubusercontent.com/2631733/33791396-21521df6-dcc6-11e7-8e53-3a21b2d76908.png)

So I echo PATH in tasks and found the PATH is not correct.
But if I open the terminal, the PATH is correct.

I searched a lot, found `.profile` or `.bashrc` will be loaded in bash.exe in terminal if I use `-ic` option.
Does tasks add these options?

Steps to Reproduce:

1. set bash.exe in settings.json
```json
{"terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\bash.exe"}
```
2. config a task in tasks.json
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "start win",
      "type": "shell",
      "command": "echo $PATH; echo `which npm`",
      "group": "build",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
      }
    }
  ]
}
```
3. I add debug msg in `.profile` and `.bashrc`. if they are loaded, the msg will be echoed
![image](https://user-images.githubusercontent.com/2631733/33791345-5dadd2dc-dcc5-11e7-8a0f-14e92cd30f8c.png)
![image](https://user-images.githubusercontent.com/2631733/33791347-6c1bf394-dcc5-11e7-94d3-8954e920a216.png)

4. run task `start win`, the output is 
![image](https://user-images.githubusercontent.com/2631733/33791278-63c26dbe-dcc4-11e7-9064-1b03ccfd6c93.png)
You can see, `.prifile` or `.bashrc` are not loaded, and `which npm` result is empty.
5. If I run the same command in cmd.exe, the result is correct
![image](https://user-images.githubusercontent.com/2631733/33791307-bf2cb556-dcc4-11e7-86fb-f04bc53f8541.png)
6. If I open the terminal, the result is also correct
![image](https://user-images.githubusercontent.com/2631733/33791311-d8533f8c-dcc4-11e7-9169-87be2033cbb6.png)

Reproduces without extensions: **Yes**(I disabled all extensions)

**Comment by dbaeumer** [comment]
No, tasks starts by default only with the -c option since this is standard in most tools to start a shell. However you can control this using the `options.shell` setting in the tasks.json. As executuable use the `bash.exe` and as args pass `'-i', '-c'`;
