### ISSUE TITLE
Vscode incorrectly handling Powershell Param parameter

### ISSUE THREAD

**Issue by joejank** [Microsoft/vscode#39955]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
xml|Dot|1.9.2
vscode-PSStackoverflow|Dou|0.0.2
codeshell|Kip|0.2.2
vscode-devskim|MS-|0.2.0
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.3
code-runner|for|0.8.5
terminal|for|0.0.10
net-core-project-manager|ksu|0.3.6
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
PowerShell|ms-|1.5.1
team|ms-|1.122.0
startanyshell|rem|0.3.1

Steps to Reproduce:
In the following example:
#
Param (
    [String] $JJDummy='/Users/joejank/Documents/log/', # default
    [String] $OutDir='/Users/joejank/Documents/log/', # default
    [String] $FileSelect="*prompt*", #default
    [Switch] $DebugJJ
)
In Vscode the above resolves to:
$outdir=/Users/joejank/Documents/log/
$jjDummy=212

but works fine in powershell terminal. This seems to always to be a problem with the first parameter.
1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Since this is running in the PS extension, please create an issue in https://github.com/PowerShell/vscode-powershell
