### ISSUE TITLE
Workspace Contains PythonPath

### ISSUE THREAD

**Issue by Modelmat** [Microsoft/vscode#39954]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.1.1
discord-vscode|icr|1.3.0
python|ms-|0.8.0
csharp|ms-|1.13.1
autodocstring|njp|0.1.2
material-icon-theme|PKi|3.1.0
datetime|rid|1.0.5
code-settings-sync|Sha|2.8.6
bootstrap4-vscode|the|3.0.0
unity-tools|Tob|0.1.9
unity-debug|Uni|1.2.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Create a workspace for python
2. Sync it to another computer (e.g. via onedrive) that has python in a different install location.
3. Run that workspace, you have to change the location.

It is slight but it is really irritating.

![image](https://user-images.githubusercontent.com/25718989/33791698-2b8fe136-dce4-11e7-8492-b3888fc5859e.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by Modelmat** [comment]
@bpasero I'm afraid this is not true, I can fix this issue (manually) by removing `pythonPath` from YOUR .workspace file. If I uninstall the extension, this does not affect it. OneDrive syncs the .workspace file, with the path in it.
