### ISSUE TITLE
打开php项目，提示扩展宿主意外终止

### ISSUE THREAD

**Issue by hyd1213126** [Microsoft/vscode#39957]
- VSCode Version: VSCode-x64-1.19.0-insider
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
php-debug|fel|1.12.1
php-intellisense|fel|2.0.4
php-pack|fel|1.0.1
csharp|ms-|1.13.1

---

Steps to Reproduce:

1.打开vscofe
2.文件-打开文件夹，选择一个php项目，加载之后提示安装git或者配置git路径和扩展宿主意外终止，安装之后任然提示扩展宿主意外终止，打开开发人员工具，报错如下：
![image](https://user-images.githubusercontent.com/23204803/33793277-bd937de4-dcef-11e7-919e-e22a8d2663d5.png)
![image](https://user-images.githubusercontent.com/23204803/33802388-43ccf176-ddb1-11e7-8ce7-d967f51aa123.png)

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Are there any errors in the developer tools? (Help > Toggle Developer Tools)

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

**Comment by hyd1213126** [comment]
![image](https://user-images.githubusercontent.com/23204803/33800850-70109e4a-dd84-11e7-995c-6f2bf1756b5b.png)
按照提示安装了git客户端，但是仍旧没有解决

**Comment by roblourens** [comment]
Can you post the text of the second error so I can translate it?

**Comment by hyd1213126** [comment]
![image](https://user-images.githubusercontent.com/23204803/33800883-1c3f0256-dd85-11e7-8bc5-d80c1aafa5e4.png)

2.
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t._onExtensionHostCrashed @ /G:/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4043
/G:/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2744 扩展宿主意外终止。

**Comment by hyd1213126** [comment]
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
t._onExtensionHostCrashed @ /G:/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4043
/G:/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2744 扩展宿主意外终止。
e.doShow @ /G:/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2744

**Comment by roblourens** [comment]
Sorry for the late response but I don't think we can do anything without steps that can reproduce the issue.
