### ISSUE TITLE
Breakpoint set but not yet bound  (Windows 10, VSC 1.18.1 to pi Node 8.9.3)

### ISSUE THREAD

**Issue by johngrabner** [Microsoft/vscode#39956]
- VSCode Version: 1.18.1
- OS Version:Windows 10

Steps to Reproduce:

1.on pi launch
sudo node --inspect-brk=192.168.2.27:9229 charger.js
2.on windows 10
{
            "type": "node",
            "request": "attach",
            "name": "Attach to Remote",
            "address": "192.168.2.27",
            "port": 9229,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "\\RASPBERRYPI/PiShare/purple_charger"
        }

debug console display output on both the visual studio code and the raspberry console.
Break point stay in state "Breakpoint set but not yet bound "

 .... tell me how and I will
Reproduces without extensions: Yes/No

**Comment by johngrabner** [comment]
issue appears intermittent .
I restarted every piece a couple of times before opening this bug.
Now on the 5th,6th  attempt, it is working.

what should I collect the next time I see this?

**Comment by roblourens** [comment]
Use the `.scripts` command to check whether the scripts are loaded and resolved to local scripts with the correct paths.

And if that looks correct, set `"trace": true` in your launch config, run it again, and upload the log here.
