### ISSUE TITLE
there is no hint when writing javascript in html file

### ISSUE THREAD

**Issue by Dongep** [Microsoft/vscode#3995]
but it is normal in a javascript file

**Comment by dbaeumer** [comment]
@aeschli why me :-)

**Comment by dbaeumer** [comment]
@Dongep are you talking about linting ?

**Comment by egamma** [comment]
I suspect this is intellisense inside script tags which is a known limitations.

**Comment by butterandfly** [comment]
This feature is so important to Polymer.

**Comment by mjbvz** [comment]
Closing this as a duplicate of #3465, which tracks supporting intellisense and other language features for js inside of html script tags.
