### ISSUE TITLE
Snippets in directories and not in file

### ISSUE THREAD

**Issue by ribafs** [Microsoft/vscode#39966]
I like VSCode a lot. It is my favorite code editor.
Something that I feel lack in VSCode is snippets in directories like Sublime Text. Snippets in just a file is very limited.

- VSCode Version: News
- OS Version: All

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Amparose** [comment]
Ah I didn't see this and created new issue that is pretty much the same request: #39989

**Comment by jrieken** [comment]
ok, closing as dupes of #13182 and #22661
