### ISSUE TITLE
Suggested CSS font-family values should be quoted

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#39963]
- VSCode Version: 1.18.1
- OS Version: Windows 10

When VSCode suggests CSS font-family values with white spaces like Times New Roman, it's not quoted. 

Edit : Actually, many are quoted. I just found the suggestion `Cambria, Cochin, Georgia, Times, Times New Roman, serif` where the quotes are missing.

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode-css-languageservice/commit/ece7dbdeb9a16104d0d8952d3d99d1d8df01711a
