### ISSUE TITLE
Unable to install VSCode on Windows 10 Build 17046?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/vscode#39964]
- VSCode Version: VSCode-Setup1.18.1x64
- OS Version: Windows 10 Build 17046

Steps to Reproduce:

1. Double click the VSCode installer, and no set-up window shows.

**Comment by LYP951018** [comment]
It seems that it's a Windows bug. https://aka.ms/Bviw9j

**Comment by isidorn** [comment]
@LYP951018 if it is a windows bug there is nothing we can do on the vscode side
