### ISSUE TITLE
Cursor indistinguishable in some situation in integrated terminal

### ISSUE THREAD

**Issue by Misairu-G** [Microsoft/vscode#39968]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open integrated terminal
2. `ccmake` some target

Reproduces without extensions: Yes

Not sure this is because cursor is not blinking or the cursor does not invert color correctly.

VSCode integrated terminal
![VSCode integrated terminal](https://i.imgur.com/DEXuV75.png)

Gnome terminal
![Gnome terminal](https://i.imgur.com/z2UmEHB.png)

**Comment by Tyriar** [comment]
I suspect this might be fixed now, let me know if it's not 😃
