### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Hortule** [Microsoft/vscode#39961]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

I'm just installed vcode and get error "Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
e._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:9"

Reinstall did not help.

**Comment by Hortule** [comment]
I install insider version, problem only in stable.

**Comment by Hortule** [comment]
I solved the problem in a stable version through the installation of git, the insider version gave me a normal git failure message, in a stable js error message. After seeing the message about the lack of git in the insider version, I installed git and installed a stable version, so I solved the problem. Add a check for git in the stable version.

**Comment by Tyriar** [comment]
FYI @joaomoreno
