### ISSUE TITLE
We should not show the JS light bulb for files generated from TS

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#3997]
Steps:

- open a file from the out folder

Observe: you get a 
![capture](https://cloud.githubusercontent.com/assets/1931590/13697057/3e5879a6-e76b-11e5-9905-efde15a67101.png)
light bulb asking to set up a jsconfig file.

**Comment by jrieken** [comment]
@dbaeumer how would we know that it's a generated file?

**Comment by dbaeumer** [comment]
@jrieken I think the best we can do is to look if we find a tsconfig.json file in one of the parents directory.

**Comment by jrieken** [comment]
Which is an information piece I'd like to get from tsserver TBH

**Comment by jrieken** [comment]
for March and continued discussions

**Comment by jrieken** [comment]
will add *ignore* action such that won't see this again
