### ISSUE TITLE
First debug session for clean install doesn't show exception breakpoints

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#39973]
- Launch code with a clean `--user-data-dir`
- Start a debug session

Breakpoints tree view doesn't expand to show the exception breakpoint options. I can't drag to resize it.

![dec-09-2017 17-11-45](https://user-images.githubusercontent.com/323878/33801078-0f0c810c-dd04-11e7-988d-27208649fcfb.gif)

**Comment by isidorn** [comment]
I can repro this, but as soon as I stop the debug session the breakpoints view gets nicely expanded. Thus it is not critical.
