### ISSUE TITLE
Publish RipgrepParser as npm package?

### ISSUE THREAD

**Issue by rmccue** [Microsoft/vscode#39975]
Hi! I'm working on a tool that uses ripgrep, and it would be great to have the [RipgrepParser class](https://github.com/Microsoft/vscode/blob/7696c91e398df8fc2b6b811b08b75f077581cad7/src/vs/workbench/services/search/node/ripgrepTextSearch.ts#L162) as a reusable package.

The colour-parsing is pretty unique, and the [only npm package](https://github.com/alexlafroscia/ripgrep-js) uses regular text parsing, which can't get the column end number (due to https://github.com/BurntSushi/ripgrep/issues/244). It would be great to be able to use this outside of vscode. :)

**Comment by roblourens** [comment]
Hm, I would much rather have more complete and parseable output from ripgrep, than try to productize that code. 

I'm curious what your usecase is for it?
