### ISSUE TITLE
"Extension-candidate" Question

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#39982]
The official guide for [VS Code states that a possible way to find an extension idea](https://code.visualstudio.com/docs/extensions/overview#_writing-an-extension), one can search the vs code repo for "extension-candidate". I clicked on the link provided, and no issues came up. I removed the is:open marker, left only extension-candidate, and no issues were found either.

Is that still relevant?

**Comment by wildeyes** [comment]
Now I see, the official site should point to `*extension-candidate` instead of just `extension-candidate`.

**Comment by usernamehw** [comment]
In addition to typo not all closed `*extension-candidate` implemented.

**Comment by gregvanl** [comment]
Fixed with vscode-docs commit https://github.com/Microsoft/vscode-docs/commit/467458fda4d0aa2cbe2e726fc771c78227fa2a22
