### ISSUE TITLE
Intellisense doesn't work with jsconfig.json > compilerOptions.paths

### ISSUE THREAD

**Issue by Zephir77167** [Microsoft/vscode#39983]
Disclaimer: I have found this issue reported a lot on the vscode repository, but never with a tangible reproduction repository. I hope this one will be easy enough to showcase the issue.

- VSCode Version: 1.18.1
- OS Version: MacOS High Sierra 10.13.1

Steps to Reproduce:

1. Here is a repository which showcases the issue: https://github.com/Zephir77167/vscode-intellisense-bug
2. Try to type the imports in `packages/app1/test.js` and `packages/shared/utils/sharedUtil2.js` by hand.

->

Going to the definition works, but Intellisense doesn't.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks for the example project! I believe this bug is already tracked by   https://github.com/Microsoft/TypeScript/issues/19113

Closing as upstream
