### ISSUE TITLE
Running `code-insiders .` on WSL leaves the terminal in a non-standard state

### ISSUE THREAD

**Issue by nickjj** [Microsoft/vscode#39987]
- **VSCode Version**:
Version 1.19.0-insider
Commit 3656454687c62594949b71651c8fa70065d16494
Date 2017-12-07T05:15:37.456Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- **OS Version**: Windows 10 Professional (Fall creators update)
- **Terminal**:
[ConEmu](https://github.com/Maximus5/ConEmu) running Bash through WSL fails with the error reported
Default Bash terminal through WSL fails with the error reported
PowerShell works as intended (Code runs in the background)
ConEmu running PowerShell instead of Bash through WSL works as intended

**Steps to Reproduce**:

1. Run `code-insiders .` from WSL (Ubuntu) to open the current directory.
2. Code runs in the foreground of the terminal, `CTRL+C` frees the terminal, but Code continues to run.

**Expected**?

1. Run `code-insiders .`
2a. Have Code run in the background (personally I would prefer this).
2b. Have Code run in the foreground but `CTRL+C` would kill it.

**Reproduces without extensions**: Yes

**Comment by Tyriar** [comment]
The Windows executable is being run when launching from WSL, not the Linux one.  This may be a limitation of WSL that it called launch Windows executables in the background.

**Comment by nickjj** [comment]
Correct, I am running the Windows version of VSCode.

VSCode does not run on Linux through WSL because it fails to render the window. There are bugs open for that in other repos / places.

**Comment by Tyriar** [comment]
Yeah and that's unlikely to change. I mean if launching Windows executables in the background is not allowed by design then this issue should be closed.

**Comment by nickjj** [comment]
Oh. I didn't know that was a limitation, since VSCode was the only graphical app I've tried to launch from WSL.

It just seems weird having to `CTRL+C` to regain that terminal window (while the app still runs), but you are right, that this is a WSL thing and should be closed.
