### ISSUE TITLE
Integrated terminal doesn't quit

### ISSUE THREAD

**Issue by szastupov** [Microsoft/vscode#39986]
- VSCode Version: 1.18.1
- OS Version: 10.13.2

Steps to Reproduce:

1. Onep integrated terminal
2. Quit the terminal (ctrl-d)
3. Terminal should close but instead it hangs with "kernel_task"

Reproduces without extensions: Yes
Also reproducible with Code insiders.

Actually, it started to happen after the recent update to High Sierra, so I'm blaming apple, but not sure.

**Comment by szastupov** [comment]
<img width="1364" alt="screen shot 2017-12-10 at 16 20 06" src="https://user-images.githubusercontent.com/24799/33805763-9cf3f3d4-ddc6-11e7-8e18-7cfbbf5d23ae.png">

**Comment by szastupov** [comment]
Just asked a colleague to test it on his laptop and he's been able to reproduce it. Now i'm confident that it's related to High Sierra 10.13.2 update.

**Comment by ianthomas0** [comment]
I am seeing a similar issue. Tasks never complete.

**Comment by ianthomas0** [comment]
I have reproduced the issue on two computers locally. I experienced the issue on a computer I recently updated, then tested on a machine running 10.13.1, and everything was fine. I then updated that second machine and the problem showed up on that one as well. Running the build task spins and never completes.

**Comment by carlca** [comment]
By default I have Ctrl ` mapped to toggle the terminal on and off, and that works fine. I can reproduce the “kernal_task” error with Ctrl D, but that keystroke is not even listed in my list of Key mappings. I suggest trying try Ctrl `. An added enhancement is to install Daniel Timms (@Tyriar) extension "Terminal Here" which opens the terminal in the CWD of the current source file. I have that mapped to Ctrl ` . The only problem is that invoking it again doesn't toggle the view.

**Comment by szastupov** [comment]
>I can reproduce the “kernal_task” error with Ctrl D, but that keystroke is not even listed in my list of Key mappings.

Ctl-d is a standard keystroke for EOF in Unix.

**Comment by szastupov** [comment]
The build and test tasks are left hanging as well.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37846
