### ISSUE TITLE
delay while save file

### ISSUE THREAD

**Issue by adrianriyadi** [Microsoft/vscode#39984]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-intelephense-client|bme|0.8.2
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.1.3
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
gitlens|eam|6.3.0
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
laravel-blade|one|1.10.0
laravel5-snippets|one|1.3.4
material-icon-theme|PKi|3.1.0
Ruby|reb|0.15.0
LiveServer|rit|3.0.0
laravel-artisan|rya|0.0.14
code-settings-sync|Sha|2.8.7
vscode-fileutils|sle|2.7.1
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

Sometimes, it takes 2 to 3 seconds to save file after I modified something, to make it back normal, I need to restart my vscode. Please fix this soon, I think it related with Git integration in vscode.

Reproduces without extensions: No

**Comment by Tex-wz** [comment]
Me too, same problem, even my extension is less than you. It also take 1 to 2 seconds to save my file.

**Comment by bpasero** [comment]
@adrianriyadi @Tex-wz 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by adrianriyadi** [comment]
@bpasero hey.. thanks for respond my thread. I recently disable all the extensions, sometimes it does happen, but sometimes it doesn't. But according to my observation, it often occurs when there's a bunch of untracked file (git) in my project folder. So I think it correlated with integrated vscode git

**Comment by bpasero** [comment]
@adrianriyadi it would be good if you could try to reproduce this without git to see if it really is git or not. You can e.g. configure `"git.enabled": false` to test this.
