### ISSUE TITLE
vscode forgets previously opened folders when opened by double-clicking an associated file.

### ISSUE THREAD

**Issue by destenson** [Microsoft/vscode#39988]
- VSCode Version: ALL
- OS Version: Windows 10 (probably all)

Steps to Reproduce:

1. Configure vscode to reopen previously open windows when starting.
2. Open several folders in different windows.
3. Carefully close vscode using the Exit from the File menu so that it will surely remember to reopen them next time you start vscode. (I've had issues in the past on Linux where it wouldn't save the open window list if you used the close button. I don't know if that still exists, I don't do it anymore.)
4. Double-click a file whose file extension is associated with vscode.
5. The file opens in vscode, but no other vscode windows open.
6. Now there is no way to get vscode to open those windows that were previously saved to be reopened.

Reproduces without extensions: Yes, not related to extensions.

**Comment by bpasero** [comment]
"window.restoreWindows": "all" can be used to restore the other windows, but the last active one will be replaced with the request to open that file. For that we have https://github.com/Microsoft/vscode/issues/15949
