### ISSUE TITLE
Add option to wrap text only after whitespace

### ISSUE THREAD

**Issue by mlainz** [microsoft/vscode#39981]
I usually use vscode to write latex and I have text wraping en. There is a behaviour that I find very annoying.

If I have a text at of the line separated by a comma of a point, such as "these,words", vscode splits them as
"this,
words".

I would expect that it would keep them together and wrap them to the next line. Would it be possible to add the option to only split words if they are separated by an space?

PS: sorry for my English

**Comment by mlainz** [comment]
![ezgif com-crop](https://user-images.githubusercontent.com/2137391/33804740-005766b0-ddac-11e7-87f7-cd664ed32173.gif)

**Comment by alexdima** [comment]
Another example from #52178:


Currently:
![currently](https://user-images.githubusercontent.com/587742/41530960-22b09bec-72f2-11e8-90ea-d3a83a64849f.png)

Should be only like:
![between controls](https://user-images.githubusercontent.com/587742/41530959-2292fcae-72f2-11e8-9640-ae1d1d73eec8.png)
or
![inside controls](https://user-images.githubusercontent.com/587742/41531088-8a6a519c-72f2-11e8-9dba-98476adbb27c.png)
