### ISSUE TITLE
Support on OS X: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error)

### ISSUE THREAD

**Issue by HJavier-CastilloSuazo** [Microsoft/vscode#39997]
- VSCode Version: 1.16.1 and 1.18.1
- OS Version: macOS High Sierra 10.13.2

I'm able to run but cannot debug a node.js + serverless project. Same project is running and debugging in Win 10 (changing some properties and paths to match Win style). 

I'm getting this error:

**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error)**

This is the configuration snippet in launch.json:

    "configurations": [
		{
			"name": "Debug",
			"type": "node",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": "npm",
			"runtimeArgs": [
				"run-script",
				"debug"
			],
			"port": 5858
		},

And the package.json snippet:

    "scripts": {
		"start": "./node_modules/.bin/serverless offline -s dev",
		"debug": "export SLS_DEBUG=* && node --debug ./node_modules/.bin/serverless offline -s dev",
		"test": "mocha"
	},

I've disabled all the extensions on VS Code.

Some hints?

Code to reproduce is in the project:
https://github.com/OneMuppet/local-lambda-debug

From this post:
https://medium.com/@OneMuppet_/debugging-lambada-functions-locally-in-vscode-with-actual-break-points-deee6235f590

Thanks in advanced!

Steps to Reproduce:

1. Clone repository
2. Run on Workspace $npm install 
3. Click on Debug (Shift-Cmd-D)
4. Select 'Debug' configuration
5. Click on play icon and wait for 10 seconds

Reproduces without extensions: Yes

**Comment by weinand** [comment]
You seem to be using an node.js version < 8.0 (because the npm script uses the --debug flag).
However, VS Code assumes a version >= 8.0 by default.
Please add `"protocol": "legacy"` to your launch config.

**Comment by HJavier-CastilloSuazo** [comment]
Thank you @weinand!

Yes I'm using (I must use) a lower version of node.js. I'll try that when I'm back to home in my computer.

Thank you so much!

H. Javier

**Comment by weinand** [comment]
Please close this issue if it works for you after the change.

**Comment by HJavier-CastilloSuazo** [comment]
Thank you @weinand, it works (great) now!

I'm going to post another issue/question regarding the package.json file. It is possible to have different values/settings for debugging offline no matter if it's from a windows or macos machine.

I mean, in a Win machine I shoult to use:

```
"scripts": {
    "start": "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless offline -s dev",
    "debug": "set SLS_DEBUG=* && node --debug %USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless offline -s dev",
    "test": "SET NODE_ENV = test && mocha --recursive test"
  }
```

And for a macOS:

```
"scripts": {
    "start": "./node_modules/serverless/bin/serverless -s dev",
    "debug": "export SLS_DEBUG=* && node --debug ./node_modules/serverless/bin/serverless offline -s dev",
    "test": "export NODE_ENV = test && mocha --recursive test"
  }

```

Due to some times I work from a Windows machine and some other times (same repository) from a macOS machine. How can I handle this situation without dealing with GIT merge conflicts?

Thanks in advanced!

**Comment by weinand** [comment]
@HJavier-CastilloSuazo I cannot speak for npm and package.json but if you are willing to drop the use of the npm scripts, you could use this VS Code launch config on all platforms:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Debug",
			"program": "./node_modules/serverless/bin/serverless",
			"args": [
				"offline",
				"-s",
				"dev"
			],
			"env": {
				"SLS_DEBUG": "*"
			}
		},
```
If there is a problem with the "program" path you could try this variant:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Debug",
			"program": "./node_modules/serverless/bin/serverless",
			"windows": {
				"program": "${env:USERPROFILE}\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless",
			},
			"args": [
				"offline",
				"-s",
				"dev"
			],
			"env": {
				"SLS_DEBUG": "*"
			}
		},
```
However, I do not really understand the reason why you need to reach into the USERPROFILE on Windows but not on macOS.

**Comment by HJavier-CastilloSuazo** [comment]
Thank you @weinand
