### ISSUE TITLE
Slow IntelliSense  in files with 4000+ lines

### ISSUE THREAD

**Issue by skhtml** [Microsoft/vscode#39994]
- VSCode Version: 1.18.1 (latest)
- OS Version: MacOS 10.12.5

Steps to Reproduce:

1. Open SCSS (or css) file with 4000+ lines of code
2. Try to quick type  dn (tab)  it must write display:none;  but it take around 1 second wait and only after it shows suggestions. 

So as much larger scss (css) file as much slower works intelliSense, in files with 5000 lines i need wait about 1 second until it works. 
**In file with 11000 i need to wait  2-3 seconds.**  
Here is a ScreenCast (video)  so you can see this issue in REAL life. 
https://monosnap.com/file/cERAp6q0qTuQks723H4ZVLfZgeuEG8

Reproduces without extensions: Yes

**Comment by wbhob** [comment]
Anything will be slow at that many lines. I'd suggest breaking the file up, because that will slow VS Code down.

**Comment by skhtml** [comment]
Thanks for the answer, but in my opinion it shows bad optimisation  of vscode, because i have been tested same files in  PhpStorm, and SublimeText3, and everything works perfect and super fast.

**Comment by wbhob** [comment]
Hmm maybe reopen it for a response from the team, but I doubt they’ll say anything different. VS code is very well optimized, so it could just be that you’re dealing with a massive file.

**Comment by skhtml** [comment]
Okay i open issue again,  I just want to say , the file is very small it is only 100KB starting slower, and with 250KB i need to wait 3 sec for IntelliSense .   Editor works perfectly, nothing lagging , tabs switching very fast, the problem is only with IntelliSense.

**Comment by ramya-rao-a** [comment]
@skhtml Do you have any extensions installed that are providing intellisense other than what is already built in?

For css/scss, there are 2 built in extensions that provide intellisense
- css
- emmet

Run `code --disable-extensions` (to disable external extensions), add the below in your settings to disable emmet from providing intellisense and let us know if that makes any difference.
`"emmet.showExpandedAbbreviation": "never"

This will help us in narrowing down which of the extension is causing the lag.

**Comment by skhtml** [comment]
For testing i already disabled all extensions.  
As you ask, i disabled emmet in  vscode config with line 
`"emmet.showExpandedAbbreviation": "never"`
After that , all emmet siggestions was gone, but build in suggestions was remain.  
Also when Emmet was enabled  i wait 3 sec for suggestions, now i wait only 1-2 seconds.

I make a little video(screencast)  for you , so you can see  problem 
https://monosnap.com/file/uM9lE7U6zNdMG7m6IRoI24otF8Yk2x

I will test it on Windows too later

**Comment by ramya-rao-a** [comment]
@aeschli Thoughts on the 1-2 seconds time taken by css completions? Is that expected or we want to work towards a better experience for large files?

**Comment by skhtml** [comment]
Actually, even 1 seconds it is very long,  because when  coders write css  they  use suggestions  everytime (every Line)  like:   
w10  ->  width:10px;    
r10p -> right:10%;   
fz12 -> font-size:12px;   
and etc. 
on others Editors suggestions shows immediately (in files 100KB +)  but here it takes time (around 1-2 sec on each suggestion)
Thats why i create issue, it need work.  Also i think this is not only emmet problem because default suggestions also slow.  

If it helps, I can give you 2 .SCSS files . one small (where suggestions works fine) ,  and one big (250KB) where its work bad.

**Comment by aeschli** [comment]
@skhtml If you can provide the files that would be great so I can investigate what's slow.

**Comment by skhtml** [comment]
Here is archive with 2 files
[scss-for-test.zip](https://github.com/Microsoft/vscode/files/1555293/scss-for-test.zip)

**Comment by aeschli** [comment]
Thanks for the examples. I made some performance improvements, please give it a try.
