### ISSUE TITLE
node debug source mapping webpack bundle to original files not working

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#39995]
- VSCode Version: 1.18.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. basic webpack bundle - to be run in node, not the browser, sourcemaps enabled, resulting in a bundle.js file and a bundle.js.map file side by side
2. node npm run "runtimeExecutable" launch config

```
    {
      "type": "node",
      "request": "launch",
      "name": "Launch via NPM",
      "outFiles": [
        "${workspaceRoot}/dist/**/*.js"
      ],
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run",
        "--prefix",
        "../",
        "e2e"
      ],
      "port": 9229
    }
```

Reproduces without extensions: Yes

I can debug the resulting bundle file just fine, I'm trying to map it back to my original ts files and that's where the issue is.

**Comment by mikehaas763** [comment]
I'm wondering if it's because an equivalent to the chrome launch type `sourceMapPathOverrides` property is needed for the node launch type

**Comment by roblourens** [comment]
Could you type `.scripts` in the debug console and paste the result here?

**Comment by mikehaas763** [comment]
I have a large list that printed out after this, how do I copy it all? I can click and drag or "cmd+a" etc
