### ISSUE TITLE
VS CODE consuming to much memory and cpu

### ISSUE THREAD

**Issue by ChicoFernandes** [Microsoft/vscode#39992]
- VSCode Version:  1.18
- OS Version:  windows 10

Steps to Reproduce:

1. i open the vs code and the memory just starts increasing and im not even typing 

2. i stay a little longer and the vs code goes to 2gb of use so i cant code because  start lagging my pc to much and make the vs code slow.

I already desinstalled vs code and it still have the same problem i used revo unistaller and i have no extensions please help

and the pc start to make noise has if it was a game with good graphics 

[https://uploaddeimagens.com.br/imagens/screenshot_1-png--922](url)

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
In order for us to investigate this further we would need more details. Can you please follow this page to provide for useful information https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by ChicoFernandes** [comment]
my pc is good i have a i7 and a gtx 1060 and 8gb RAM.
 i dont need to a  have a project open i just need to open the vs code and starts to consuming memory non stop.

here is a picture  [https://ibb.co/gsmUZb](url)    https://ibb.co/gsmUZb

the language im triyng to code is in javascript but that doesnt matter i think because the problem is with the vs code

**Comment by weinand** [comment]
Please upgrade to the latest VS Code 1.19 and let us know if the problem still exists.

**Comment by ChicoFernandes** [comment]
the problem is solved the problem was on my pc i formated Thanks

**Comment by weinand** [comment]
Thanks for the update.
