### ISSUE TITLE
Linted items missing from Problems pane

### ISSUE THREAD

**Issue by demoran23** [Microsoft/vscode#39991]
I'm trying to integrate eslint results into the Problems pane.  I've got a task set up that gives me *partial* results.  Specifically, I have 68 linting issues in the project as reported by eslint, but only ~50 of them show up when linked to vscode.

When the matcher tries to process the line, it fails to match because the line spit out by eslint is being broken half way.  It put some console.logs in to try and track it down, and see this:

> problemMatcher.ts:342 LINES: ["C:\\Users\\redacted\\Source\\Repos\\redacted-file-name.js: line 17,"]
> problemMatcher.ts:342 LINES: ["col 8, Error - 'variableName' is defined but never used. (no-unused-vars)"]

The eslint-stylish logger had an even worse time getting items in.

===

- VSCode Version: 1.18.1
- OS Version: Microsoft Windows 10 Pro 10.0.16299 N/A Build 16299

Reproduces without extensions: Yes

**Comment by demoran23** [comment]
I exported the linting results to a file and inspected the cited problem.  I thought that maybe eslint itself was throwing a newline in a weird place (between line and column).  This is not the case.  When viewed in Notepad++ with *Show All Characters* on, the only `LF`s in the file are at the end of each line.

Taking the contents of the file and pattern matching it against the regex defined for `eslint-compact` (via https://regex101.com/) results in all 68 items being matched.

**Comment by dbaeumer** [comment]
@demoran23 can you provide a Github repository that demos the behaviour you are seeing with steps on how to reproduce.

**Comment by demoran23** [comment]
@dbaeumer I've created [a repository with basic lint error spam](https://github.com/demoran23/39991-example).  

After generating 600 linting errors in a single file and failing to replicate the issue, I created a file with a few different linting errors and a script to copy it 100 times.  While the Problems pane doesn't let me know exactly how many linting errors it sees in total (and the status bar text simply says **99+**), *they all seem to be accounted for*.

Of course, real life doesn't happen in such a sterile environment.  Something is going on where the terminal stream is being consumed haphazardly when my actual project is being linted - perhaps from the various imports we've got.  It is a react native codebase.  I think maybe the linter is slowing down in its processing and we're grabbing and using what we can when we can.

**Comment by dbaeumer** [comment]
The pipe lint from the output over the terminal to the problem matcher is stream based. So we shouldn't loose anything. If the problem matcher is not fast enough to scan the output it will slow down the actual liniting process / terminal. But we will not drop lines. 

However there are some tricks we do to signal lines to the problem matcher due to ansi escape sequences. For example if the same line is written over and over again only after a successful newline the line is reported. But to my knowledge eslint problem reporters do not make use of this.

Without being able to reproduce it is very hard to fix. Any possibility you can share the project that show the problem.

**Comment by demoran23** [comment]
I haven't forgotten about this one.  I've been busy, but I intend to create a new React Native project that uses all of the same imports we use in our closed codebase and replicate the issue there.

**Comment by dbaeumer** [comment]
Reopening the issue then.

**Comment by demoran23** [comment]
I've updated the aforementioned repository with the dependencies and devDependencies of my actual project.

On my local machine, I couldn't get eslint compact to actually show compact results (it was showing stylish) - so I've changed the problem parser to stylish and removed the compact formatter from the lint script.

Oddly enough, nothing seems to be showing up in the problem pane now.
