### ISSUE TITLE
slow startup and hang on terminal on Ubuntu 17.10 gnome

### ISSUE THREAD

**Issue by bravomikekilo** [Microsoft/vscode#40003]
- VSCode Version: 1.17.2, 1.18.1 
- OS Version: Ubuntu 17.10 gnome

Steps to Reproduce:

1.  click code icon from applications, it immediate open a window but take long time to load, every reload is very slow
2.  use `code` command from terminal will do nothing, it just hang, even --help will not list any thing

Reproduces without extensions: Yes/No Yes

**Comment by Tyriar** [comment]
I haven't seem anything like this, can you try launch using `code --disable-extensions`?
