### ISSUE TITLE
JS FORMATTER IGNORES MY SETTING in VUE: "javascript.format.insertSpaceBeforeFunctionParenthesis": true

### ISSUE THREAD

**Issue by fabioroldan** [Microsoft/vscode#40004]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
copy-relative-path|ale|0.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.0.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
code-runner|for|0.8.5
firebase-snippets|has|0.0.1
Python-autopep8|him|1.0.2
search-node-modules|jas|1.2.0
weex|jay|0.4.0
vscode-gutter-preview|kis|0.12.2
start-git-bash|McC|1.2.1
python|ms-|0.8.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
okazukiplantuml|oka|0.2.2
java|red|0.15.0
preview-vscode|sea|1.4.2
git-merger|sha|0.3.6
markdown-preview-enhanced|shd|0.3.1
indenticator|Sir|0.4.2
pdf|tom|0.2.0
vscode-terminal-here|Tyr|0.0.5
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
quokka-vscode|Wal|1.0.84
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.5.0

**Steps to Reproduce:

1.Type function foo () { }
2.Format the code (shift alt f)
3.Code is formatted to function foo() { } with no mechanism to override

JS FORMATTER IGNORE MY USER SETTINGS in .VUE and .HTML files, in js it works.
"javascript.format.insertSpaceBeforeFunctionParenthesis": true
And of course I get an error in the standard style
[eslint] Missing space before function parentheses. (space-before-function-paren)**

**Comment by mjbvz** [comment]
Please file this against vetur
