### ISSUE TITLE
Visual code suddenly has stop working

### ISSUE THREAD

**Issue by luanft** [Microsoft/vscode#40009]
Visual code suddenly has stop working. I have attached my screen shoot. Please help to resolve this problem.

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/11657076/33824999-c4089b9c-de92-11e7-9efb-be841a2ba111.png">
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 3.10.0-693.2.2.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.14.0
vscode-npm-script|eg2|0.3.3
python|ms-|0.8.0
vscode-code-outline|pat|0.0.12

---

Steps to Reproduce:

1. No special steps. Just typing new code and fall into this problem!
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
- Did you see any errors in the console? (Help -> Toggle Developer Tools -> Console)
- Was there any errors showing in the UI?
- Can you consistently repro this? If yes, then can you repro this with your extensions disabled? (Run `code --disable-extensions`

**Comment by luanft** [comment]
I did see any error in the console. VS is not responding. So I can't do anything to find out the problem. Does it have any log file?
In the previous version I didn't fall into this problem.

**Comment by luanft** [comment]
My screen is the only thing I can show you!

**Comment by ramya-rao-a** [comment]
Run `code --verbose` from your terminal and share the output

**Comment by ramya-rao-a** [comment]
Also follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues and share any crash related data you can

**Comment by bpasero** [comment]
@luanft does it help if you run `code --disable-gpu`?

**Comment by luanft** [comment]
Hi, this is the output when run ` code --verbose`
[log.txt](https://github.com/Microsoft/vscode/files/1554520/log.txt)

**Comment by luanft** [comment]
I think this problem can reproduce by scrolling up & down a long source file multiple times.

**Comment by bpasero** [comment]
@luanft does it help if you run `code --disable-gpu`?

**Comment by luanft** [comment]
@bpasero I'm trying with this option. I will share the log if the problem happen again.

**Comment by luanft** [comment]
@bpasero  I tried this option `code --disable-gpu` for few days. Visual code works well with this option.

**Comment by arrowplum** [comment]
any idea of when we can stop with the `code --disable-gpu`? Did the latest release address this issue?

**Comment by arrowplum** [comment]
is it an electron bug? is there a ticket number?

**Comment by arrowplum** [comment]
Or no?

**Comment by arrowplum** [comment]
@bpasero what is the upstream bug? Just tried with Version: 1.25.0 and verified it still exists. I would really like to know what ticket to watch instead of randomly trying every once in a while.

**Comment by arrowplum** [comment]
But you are sure it is electron, @bpasero?

**Comment by bpasero** [comment]
Does this still happen?

**Comment by bpasero** [comment]
Ok, closing thereby.

**Comment by arrowplum** [comment]
I just got this same issue yesterday with the latest. So for me anyways.. still happening. You sure you want to close?

**Comment by arrowplum** [comment]
@bpasero

**Comment by bpasero** [comment]
@arrowplum what is your setup?

**Comment by luanft** [comment]
I think that the issue is from the video memory card. On window I have 128MB but on linux I only have 16MB.
