### ISSUE TITLE
i write jsx when i write settimeout  it will auto import timers

### ISSUE THREAD

**Issue by zhiqiang21** [Microsoft/vscode#40001]
- VSCode Version:1.18
- OS Version:macos 1.13.2

Steps to Reproduce:

1.i write jsx when i write settimeout function ,

```
componentWillReceiveProps(nextProps) {


        setTimeout()
    }
```

2.then vscode will auto import  times .it's  not my wanted

```
import {setTimeout} from 'timers';
```

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Yes, our auto imports sometimes pick up unexpected symbols. Look in the suggestion list to see if the suggestion is an auto-import or not (top right side):

<img width="651" alt="screen shot 2017-12-11 at 10 10 29 am" src="https://user-images.githubusercontent.com/12821956/33846423-a2ca5768-de5b-11e7-8efd-754947267233.png">

And you can disable auto imports entirely by setting: `"typescript.autoImportSuggestions.enabled": false`

**Comment by MrNovado** [comment]
@mjbvz This should be off by default, this wasted almost 3 hours of my life, coz I couldn't figure out why my timeouts suddenly stopped invoking callbacks
