### ISSUE TITLE
js file highlight can't be seen

### ISSUE THREAD

**Issue by TYZRPVX** [Microsoft/vscode#40002]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
githistory|don|0.2.3
vscode-great-icons|emm|2.1.21
output-colorizer|IBM|0.1.2
plantuml|jeb|2.3.3
prettify-json|moh|0.0.3
python|ms-|0.8.0
partial-diff|ryu|0.5.1
code-settings-sync|Sha|2.8.6
vscode-hexdump|sle|1.6.0
JavaScriptSnippets|xab|1.5.0
markdown-all-in-one|yzh|0.11.2

![image](https://user-images.githubusercontent.com/7645818/33817016-128a44d4-de78-11e7-92c8-21579792b88d.png)

---

Steps to Reproduce:

1. Suddenly one day I open vscode, it comes to this situation

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please provide reproducable steps so we investigte his furhter.
Here are nice rules how to file good issues https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

Also can you reproduce if you disable all extensions?

**Comment by mjbvz** [comment]
It looks like the file is in plain text mode. Please try changing the mode back to JavaScript: https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file

This could be caused by your user or workspace settings, or perhaps by an extension

**Comment by TYZRPVX** [comment]
Thanks a lot.
