### ISSUE TITLE
open is not response，and no error report

### ISSUE THREAD

**Issue by zhaobingchun** [Microsoft/vscode#40006]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.1.2
Bookmarks|ale|0.18.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-markdownlint|Dav|0.12.0
jupyter|don|1.1.4
xml|Dot|1.9.2
gitlens|eam|6.3.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
code-runner|for|0.8.5
beautify|Hoo|1.1.1
ftp-simple|hum|0.5.8
path-autocomplete|ion|1.7.0
Lua|key|0.0.9
Go|luk|0.6.69
mssql|ms-|1.2.1
python|ms-|0.8.0
cpptools|ms-|0.14.3
vscode-docker|Pet|0.0.22
material-icon-theme|PKi|3.1.0
view-in-browser|qin|0.0.5
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
jinja|who|0.0.8
local-history|xyz|1.6.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
Please provide some details and we can reopen this issue.
Here are some good advice on how to file good issues https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by zhaobingchun** [comment]
sorry, it maybe my computer problem, I reboot my computer and it can open
