### ISSUE TITLE
Disable Right Click to Paste in Terminal

### ISSUE THREAD

**Issue by accedomesa** [Microsoft/vscode#40008]
- VSCode Version: 1.18 and older
- OS Version: Windows 10

Steps to Reproduce:

1. Copy something, like a chunk of code or a few thousand lines of logs
2. Accidentaly right click inside the integrated terminal (or intentionally, expecting the usual context menu)
3. Enjoy figuring out what happened, especially fun when the text contained ">" or git commands

Reproduces without extensions: Yes

Kill it with fire and dont look back.

**Comment by usernamehw** [comment]
`settings` => `"terminal.integrated.rightClickCopyPaste": false`

**Comment by Tyriar** [comment]
This is the standard behavior in cmd and powershell which is why it's the default under Windows. It can easily be turned off as indicated above.
