### ISSUE TITLE
Polish diactric marks

### ISSUE THREAD

**Issue by Mikolaj98p** [Microsoft/vscode#40015]
I cannot use Polish diactric marks.
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.14|
|terminal|formulahendry|0.0.7|
|mediawiki|jakeboone02|2.1.0|
|dokuwiki|kirozen|1.4.0|
|cpptools|ms-vscode|0.10.2|
|csharp|ms-vscode|1.7.0|
|bash-debug|rogalmic|0.0.7|

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
Please update to the latest version, if you're still having an issue please create another issue with more information and a screenshot.

**Comment by Mikolaj98p** [comment]
No change. I can use only "Alt Gr + EASLZX = ĘĄŚŁŻŹ" and I can't use "Alt Gr + O = Ó" this entering to powershell, "Alt Gr + N = Ń" this return "Info: Code language is not supported or defined" and "Alt Gr + C = Ć" this return nothing.

**Comment by Tyriar** [comment]
If you're talking about within the terminal you're likely seeing https://github.com/Microsoft/vscode/issues/35901

**Comment by Mikolaj98p** [comment]
I need only text editor with dark theme, terminal for me is optional.
