### ISSUE TITLE
Leak testing

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4001]
- [x] @jrieken 
- [x] @SofianHn 

Use the Chrome profiler's snapshot feature to identify leaks for important scenarios:

- [x] open/close an editor
- [x] use code assist
- [x] type into an editor
- [x] search
- [x] git push, pull
- [x] output
- [x] extension host
- [x] quick open etc

**Comment by bpasero** [comment]
I added "output" to the summary, because we can receive output from the background we must ensure that we are not leaking there.

**Comment by jrieken** [comment]
:+1:

**Comment by isidorn** [comment]
@jrieken just a reminder to check off the items which you tested so @SofianHn can do the rest
