### ISSUE TITLE
Copy / Paste if without bracket - wrong indention

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#40016]
When copy/paste JS-Code there is a strange behavior, when there is an if-statement without brackets.

Steps to Reproduce:
Write:
```
if(x == 1)
  do(1)
else if(x == 2)
  do(2)
```
now highlight, copy & paste the else-statement. Now you get:
```
if(x == 1)
  do(1)
  else if(x == 2)
    do(2)
```
Paste it couple of times and it will be intended more and more
```
if(x == 1)
  do(1)
  else if(x == 2)
    do(2)
    else if(x == 2)
      do(2)
      else if(x == 2)
        do(2)
        else if(x == 2)
          do(2)
```

**Comment by Veyhunk** [comment]
same problem 
fix it pleace

**Comment by mjbvz** [comment]
Fixed by setting: `"editor.formatOnPaste": true`

Closing this due to lack of further community interest over the past few years
