### ISSUE TITLE
Open editors: drag image is not the same as explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40012]
Steps to Reproduce:

1. drag an editor from the open editors view

=> the drag image is not the same as the explorer where we show the name, instead we drag the entire list element it seems

**Comment by isidorn** [comment]
fyi @joaomoreno I had to copy what the tree is doing here https://github.com/Microsoft/vscode/blob/release/1.19/src/vs/base/parts/tree/browser/treeView.ts#L1304

**Comment by joaomoreno** [comment]
Why not bring this down to the list?

**Comment by isidorn** [comment]
@joaomoreno i can do that. However the list would need to ask the client for the drag label. Should that be a part of list options or how would you like this?

**Comment by joaomoreno** [comment]
Oh yeah forget it... we made it that the list user implements dnd, completely spaced out there. Nevermind!
