### ISSUE TITLE
start from command: 'code ./' with runtime error

### ISSUE THREAD

**Issue by lovetingyuan** [Microsoft/vscode#40017]
- VSCode Version:
- OS Version: windows
![2017-12-11_190019](https://user-images.githubusercontent.com/7310471/33828078-9082d662-dea5-11e7-90f1-83f2a5ddca30.jpg)
 
![2017-12-11_190629](https://user-images.githubusercontent.com/7310471/33828276-6f00be5e-dea6-11e7-88ac-4ed4bb661238.jpg)

Steps to Reproduce:

1. I use git bash, I enter my project dir, I run `code ./`
2. then errors happend, the editor is empty and no response
3 the probability is not 100%, but quite high

Reproduces without extensions: Yes/No
![2017-12-11_190442](https://user-images.githubusercontent.com/7310471/33828205-2a5426a6-dea6-11e7-8caa-e02671cbd6a0.jpg)

**Comment by lovetingyuan** [comment]
@ramya-rao-a  yes! I run it in admin mode, it is the same bug with #36029

**Comment by ramya-rao-a** [comment]
The original issue in #36029 was of blank window which has been solved.
But the errors in the console as mentioned in this issue and in https://github.com/Microsoft/vscode/issues/36029#issuecomment-344954619 still applies to 1.18.1

So re-opening this issue

**Comment by ramya-rao-a** [comment]
@lovetingyuan Can you try our latest Insiders from https://code.visualstudio.com/insiders and see if you see the same issue?

**Comment by lovetingyuan** [comment]
@ramya-rao-a  I have tried the insider version and it runs well without any error(`code-insiders .`)

**Comment by bpasero** [comment]
@lovetingyuan sounds like a permission issue with the stable install then. please uninstall and reinstall with proper permissions.
