### ISSUE TITLE
Terminal steels 600ms startup perf

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#40025]
Profiled an issue about localstorage on @egamma's machine and found that creating the font atlas takes 600ms. That seems quite slow and it also messes with the perceived performance as this operation blocks the editor and explorer being populated. 

<img width="717" alt="screen shot 2017-12-11 at 15 43 34" src="https://user-images.githubusercontent.com/1794099/33836614-24a0cd2a-de8a-11e7-8403-f226685c593f.png">

[f01c-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1548147/f01c-renderer.cpuprofile.txt)

**Comment by Tyriar** [comment]
This cost will become asynchronous and move onto a separate thread once we have access to `OffscreenCanvas` with Chromium v60. Once this happens the terminal can even start rendering before the texture is generated.

Upstream issue: https://github.com/xtermjs/xterm.js/issues/955

**Comment by Tyriar** [comment]
@jrieken would a `setTimeout` with 0 delay be sufficient? Otherwise I'm not sure what number would be best; too much would lead to lack of responsiveness for ~200-600ms (depends on screen DPI and zoom level).

**Comment by jrieken** [comment]
Ideally you participant in the global lifecycle and only do these things in the [`Running`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/lifecycle/common/lifecycle.ts#L51)-phase. That's after the editor and viewlet have rendered once. A timeout of 0 would probably be not enough

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/41823
