### ISSUE TITLE
ghost problem after a commit

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#40029]
I've seen this a few times but never know how to get into the situation.  After a commit I end up with this strange error that eventually goes away on its own:

![image](https://user-images.githubusercontent.com/1487073/33840025-a003d620-de48-11e7-9b14-dab65e590742.png)

Clicking on the problem brings up a new but empty tab for the file (in this case `package.json`).

**Comment by joaomoreno** [comment]
This is a `git:` resource. It complains that the resource `git:/d%3A/src/...` has the error. Which it does.

We've gone through this problem many times. I thought the validation would skip non `file:` resources by now. cc @dbaeumer @aeschli

**Comment by dbaeumer** [comment]
Yes, we discussed that many times and for a short period of time document selectors got scoped to 'untitled' and 'file'. But that change got reverted and there is not general story for this. Each extension needs to handle this by itself.

**Comment by aeschli** [comment]
It's a dup of #33046.
Showing the error is ok if the git-diff is open in an editor, but not ok if the textDocument is only used programmatically. We need an API to distinguish the two, and the LS-client should only sync documents open in editors.
