### ISSUE TITLE
Intellisense not appearing in correct position

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#40020]
- VSCode Version: Code - Insiders 1.19.0-insider (d8989c95964ce06c64ffebc2fb400a0327bd447d, 2017-12-08T10:45:40.870Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.3
EditorConfig|Edi|0.11.1
git-project-manager|fel|1.4.0
vscode-scss|mrm|0.6.2
cpptools|ms-|0.14.3
seti-icons|qin|0.1.3
vscode-header-source|ryz|1.1.0
ayu|tea|0.10.0
lorem-ipsum|Tyr|1.1.0
shell-launcher|Tyr|0.1.4

(4 theme extensions excluded)

---

Steps to reproduce:

1. Launch an extension (this likely happens in a normal window too)
2. Open user settings
3. Trigger intellisense via ctrl+space

![image](https://user-images.githubusercontent.com/2193314/33830888-cdb1424c-de2a-11e7-8549-56d2b0d1e534.png)

Type again and it positions correctly:

![image](https://user-images.githubusercontent.com/2193314/33831504-25fa1148-de2d-11e7-9a85-605d88a3a15a.png)

**Comment by ramya-rao-a** [comment]
@Tyriar You seem to have only textual completions on. How is that?

**Comment by Tyriar** [comment]
Not sure why, it was on my home Windows PC

**Comment by ramya-rao-a** [comment]
Tracking in #36778
