### ISSUE TITLE
Hide autocomplete box on click to another tab

### ISSUE THREAD

**Issue by 100Errors** [Microsoft/vscode#40026]
- VSCode Version: 1.18.1
- OS Version: Windows 10 .0.16299

Steps to Reproduce:

1. Open Visual Studio Code
2. Split the window by clicking on the split button on the right top / by clicking CTRL+^
3. Write the first words of an instruction like "alert"
4. now switch to the other tab
5. the description box will be in the way so you cannot see a part of your code
6. if you click anywhere in the first tab the tab will disappear, so why not on the second too? 
![image](https://user-images.githubusercontent.com/34282308/33837310-3d56e80c-de8c-11e7-8990-bf0090a3bde7.png)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
This bug is a regression and has the same root cause as #38484 which has been fixed for 1.19
