### ISSUE TITLE
tsserver version should not be shown in the status bar

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#4002]
IMHO, it acts as a confusion. Is it the version of the language (i.e. ES6), is it the version of vscode (since it sits next to the smily). Does it add any value to the average user? Do most people use Salsa in other contexts than VSCode? Probably not, therefore, they don't need to know the version. Maybe only show it on hover or something?

![image](https://cloud.githubusercontent.com/assets/5047891/13698039/d88a2640-e771-11e5-9829-a6e33fea6a6a.png)

**Comment by egamma** [comment]
It has value when the user is using tsdk to use another version than the one we bundle. So I suggest to only show the version in the status bar when the tsdk setting is set.

**Comment by alexandrudima** [comment]
Thank you!
