### ISSUE TITLE
Wrong versions of node, angular cli and npm is displayed in terminal after changing node in NVM. 

### ISSUE THREAD

**Issue by marekdano** [Microsoft/vscode#40028]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
EditorConfig|Edi|0.11.1
material-icon-theme|PKi|3.1.0
quokka-vscode|Wal|1.0.84
react-pure-to-class-vscode|ang|1.1.1
react-food-truck|bur|1.0.1
simple-react-snippets|bur|1.1.0
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.3.0
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.0
css2react|got|0.0.4
vscode-tfs|iva|0.6.0
angular-essentials|joh|0.3.2
Angular2|joh|2.11.2
vscode-elixir|mjm|1.1.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
angular2-inline|nat|0.0.17
vscode-import-cost|wix|2.5.1
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Change version of node through nvm outside of VS Code.
2. Open VS Code and check version of node, angular cli and nvm in VS Code terminal.
3. The versions in VS Code terminal are different comparing with the versions checked outside VS Code. 

NOTE:
When I run VS Code from terminal with the command "open /Applications/Visual\ Studio\ Code.app" the versions of node, npm and angular cli are changed, matching versions in the terminal outside of VS Code.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
How are you launching VS Code (via cli, bottom dock, etc)?

**Comment by marekdano** [comment]
I'm on mac. When I start VS Code from from Applications and then I open integrated terminal from menu View in VS Code, I'm getting the wrong versions. 
If I launch VS Code from Terminal shell after checking versions of node, npm and angular cli with this command "open /Applications/Visual\ Studio\ Code.app" and open the terminal in VS Code, I get the correct versions.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by marekdano** [comment]
Where can I find that file? I have no file settings.json under my project folder. Thanks for your time to check the issue.

**Comment by Tyriar** [comment]
cmd+, should bring up your settings on the right side

**Comment by marekdano** [comment]
Thanks for your help !!!

I have following settings:

    {
       // Controls the rendering size of tabs in characters.
       // If set to auto, the value will be guessed based on the opened file.
       "editor.tabSize": 2,

      // Controls if the editor will insert spaces for tabs.
      // If set to auto, the value will be guessed based on the opened file.
      "editor.insertSpaces": false,
      "window.zoomLevel": 0,
      "workbench.iconTheme": "material-icon-theme",
      "workbench.panel.location": "bottom"
    }

**Comment by marekdano** [comment]
I didn't mention the message content below. When I open terminal in VS Code the message is:
 
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local" Run `npm config delete prefix` or `nvm use --delete-prefix v8.9.1 --silent` to unset it.

**Comment by Tyriar** [comment]
That error happens when you have prefix set somewhere in your scripts. Try running `npm config delete prefix` and relaunching the terminal, if that doesn't work you need to find where it's getting set and remove it.
