### ISSUE TITLE
Allow running the same task concurrently

### ISSUE THREAD

**Issue by abmantis** [Microsoft/vscode#40027]
Currently, it is not possible to launch a task that is already running, with vscode displaying the "task is already running" popup.
Sometimes it is useful to have the same task in multiple instances. For example, I have a task which launches my app, and sometimes I need to run the app, change code, run the app again and compare both.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/32264 which requests more features like terminate and restart and specifying an instance count.
