### ISSUE TITLE
terminal for task does not realize it's finished if task contains certain clear commands

### ISSUE THREAD

**Issue by joelhock** [Microsoft/vscode#40034]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---

---

Steps to Reproduce:

1. create task with:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "command": "clear ; echo hi; clear; echo bye",
            "type": "shell",
            "args": [],
            "presentation": {
                "reveal": "always",
                "echo": false,
                "panel": "dedicated"
            },
            "label": "test"
        }
    ]
}
```
2. note that when finished terminal does *not* output `Terminal will be reused by tasks, press any key to close it.`
3. try to run task again
4. vscode complains that task is already running `The task 'test (foo)' is already active. To terminate it use 'Terminate Task...' from the Tasks menu.`
5. note that if second `clear`  is removed from the `command` string, terminal behaves as expected.  removing first `clear` but leaving the second still causes the issue.

This used to work fine; not sure if it was a newer version of vscode or mac OS that broke things.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/37846.

**Comment by joelhock** [comment]
recent insider's build with fix from https://github.com/Microsoft/vscode/issues/37846 does indeed solve this issue.  thanks!
