### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by sanrzdz** [Microsoft/vscode#40037]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.3
PowerShell|ms-|1.5.1
typescript-hero|rbb|1.8.0

---

Steps to Reproduce:

1. Open Code
2. Error message pops up

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
Do you see this error consistently?
Are there any errors on the console? (Run Help => Toggle Developer Tools -> Console)

**Comment by jwuliger** [comment]
Hello, @ramya-rao-a I have been running into this problem consistently to the point where it makes it impossible to use the editor. My best guess is a typescript version conflict and/or a node version issue.

My environment:

I am using the same extensions as mentioned by @sanrzdz.

Node: 8.9.1 LTS
OS: win32 x64

VS Code Version:
![vs-code-version](https://user-images.githubusercontent.com/14036569/33863701-10a10bbe-deb7-11e7-9ec7-a63ac399a3fa.PNG)


Here is a screen grab of my vs code debug console:

![vs-code-extension-host-error-01](https://user-images.githubusercontent.com/14036569/33863576-6c58378a-deb6-11e7-958b-a84a7477f6f6.png)

I hope this information can help. Please let me know if I can be of any assistance. Thanks!

**Comment by ramya-rao-a** [comment]
@jwuliger Looks like you also have the mrmlnc.vscode-scss extension installed which is failing to set up the language client in time.

Can you disable that extension and see if you still see issues?

**Comment by ramya-rao-a** [comment]
cc @sandy081 for the issue with `applyEditsToBuffer` which has the same callstack as #31348

**Comment by sanrzdz** [comment]
Hi @ramya-rao-a, here is a screenshot of my console:

![image](https://user-images.githubusercontent.com/4968845/33876253-e64afb66-df1c-11e7-9f54-d7c393553427.png)

**Comment by sandy081** [comment]
Yes `applyEditsToBuffer` got fixed in #38196

**Comment by ramya-rao-a** [comment]
@sanrzdz Looks like the typescript-hero extension is causing the issue.
Can you disable that extension and see if you still see the issue?

**Comment by mgmarlow** [comment]
I was running into the same issue and noticed that the memory of vscode was sky rocketing until the extension host terminated itself. Disabling Typescript Hero resolved the issue.

**Comment by geekgonecrazy** [comment]
Same kept happening last few days and finally came looking and saw a typescript hero was common and disabled on mine.  Seems to be working now. :+1:

**Comment by weinand** [comment]
Please try the latest VS Code 1.19 and let us know if the problem still exists.
