### ISSUE TITLE
Uninstalling Extension Stuck

### ISSUE THREAD

**Issue by luhagel** [Microsoft/vscode#40035]
- VSCode Version: 1.19 Insiders ( December 11th Build )
- OS Version: MacOS 10.13

Steps to Reproduce:

1. Open the extension view
2. Try uninstalling any extension
3. Cog icon turns grey, extension page shows `uninstalling`, but nothing happens
4. Restarting/Rebooting doesn't fix the issue

Reproduces without extensions: Kinda hard to test

**Comment by luhagel** [comment]
Fixed by redownloading the .app

**Comment by briangonzalez** [comment]
For anyone else who comes this way, I deleted straight from the extensions dir:


- Windows `%USERPROFILE%\.vscode\extensions`
- Mac `~/.vscode/extensions`
- Linux `~/.vscode/extensions`
