### ISSUE TITLE
renaming files doesn't allow me to erase characters

### ISSUE THREAD

**Issue by mac40** [Microsoft/vscode#40032]
- VSCode Version: 1.19.0-insider
- OS Version: Windows 10 Home

Steps to Reproduce:

1. create a new file in file explorer with the a shortcut (atom keymap)
2. cannot delete written characters even after creation

Reproduces without extensions: No

**Comment by isidorn** [comment]
This should be a duplicate, assigning to @joaomoreno just to be sure
@mac40 are you on latest?

**Comment by mac40** [comment]
Not sure what you mean for latest.
If u're referring to vscode-insider version i should be on latest version (there are no available updates)

**Comment by ramya-rao-a** [comment]
@mac40 is on Windows and there hasn't been a Windows update to Insiders in a few days

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode-atom-keybindings/pull/45
