### ISSUE TITLE
Surface save participants in UI

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#40030]
When save participants like format or the `onWillSave`-event run, and take longer, users won't know. We should show an UI piece when they run.

**Comment by jrieken** [comment]
Such a formatter we don't call.

**Comment by ramya-rao-a** [comment]
> Such a formatter we quickly won't don't call any.

I dont' understand...

I tried testing using a slow formatter because of what's described in https://github.com/Microsoft/vscode/issues/40030#issue-281077930

**Comment by jrieken** [comment]
To verify: 

* open a huge JSON file (+ 10000 lines)
* set the `formatOnSaveTimout`-setting to something large, e.g 5sec
* save the JSON file
