### ISSUE TITLE
Adjacent characters are given a  lower rank in command palette than distant characters

### ISSUE THREAD

**Issue by brandondrew** [microsoft/vscode#40044]
When using the command palette, ordering of results fails to take into account adjacency of characters.  

Whether this is a bug report or a feature request really depends on whether effort was already made to make the search results account for adjacency or not.  The only other issue I can find related to this is https://github.com/Microsoft/vscode/issues/21019, but that seems to be dealing with a different matter, so I will include version information, but I'm proceeding under the premise that this is a request for a new feature rather than a bug report.

# The case for the value of this feature #

![image](https://user-images.githubusercontent.com/9854/33850770-f37d7e16-de82-11e7-94ea-6460891d3b89.png)

Although the ability to search through commands without having to type in every consecutive character is valuable, it seems to me that users will virtually never want or expect the results of their search to prioritize results with a disconnected match above results with a connected match.  In the image above, I typed "vim" and expected to see all commands related to Vim mode at the top of the list.  I cannot imagine a case where I would type in the characters <kbd>v</kbd><kbd>i</kbd><kbd>m</kbd> and expect "View: Minimize Other Editor Groups" at the top of the list.  If I were looking for "View: Minimize Other Editor Groups", I would expect to have to type more characters, and certainly be prepared to do so.  I would most likely type <kbd>v</kbd><kbd>i</kbd><kbd>e</kbd><kbd>w</kbd><kbd>:</kbd><kbd>m</kbd><kbd>o</kbd><kbd>e</kbd><kbd>g</kbd>—unless the command I wanted rose to the top before I finished typing that.  

Hopefully the example I've given is enough to demonstrate that the behavior I'm describing would be preferable.  But if I've left any questions unanswered, please ask for more information.  

Thanks!

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0
- Extensions: the listing length exceeds browsers' URL characters limit

Steps to Reproduce:

1. Ensure that you have the Vim plugin installed.
2. Open command palette with <kbd>F1</kbd> or <kbd> ⌘ </kbd><kbd> ⇧ </kbd><kbd>P</kbd>.
3. Type "vim".
4. Note that expected results appear at the bottom of the list.

**Comment by usernamehw** [comment]
@bpasero, is it covered in another issue? How is this not a bug?

**Comment by usernamehw** [comment]
Looks like a duplicate of #14727 which is in the backlog, but it has fewer (5) upvotes...
