### ISSUE TITLE
Ruby auto-indent inconsistencies

### ISSUE THREAD

**Issue by TeeSeal** [Microsoft/vscode#40042]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0

There are some auto-indent inconsistencies with the Ruby language. I really want to switch to VSCode as my daily driver but these small things keep me from doing so.

1. `case` statements
![case](https://a.safe.moe/1Aasf.gif)
The cursor should auto-indent one tab after a case statement but it doesn't making the indentation inconsistent when a `when` clause is added. I also mentioned this in #29970.

2. Variable definitions using an `if else` statement.
![if](https://a.safe.moe/znKUb.gif)
I think this one is self explanatory. While normal if statements indent properly, when you attach a variable to it, it does that. Needless to say, I experience the same behavior when attaching a variable to a `case` statement, as shown in the first example.

That's everything I've been able to find so far (after 1 day working with VSCode), I'll stick to it for now and see if I can find more issues and add them here if I do.

**Comment by jens1o** [comment]
cc @rebornix who manages the ruby extension

If you want to contribute, here you go: https://github.com/Microsoft/vscode/blob/d8aec33ba6cfd0d45ef1734bd045581f2cf23251/extensions/ruby/language-configuration.json

**Comment by TeeSeal** [comment]
Oh so this stuff is manage just by 2 big ass regex expressions 🤔
Will see how I can fix it once I figure out how to test it lol.

**Comment by rebornix** [comment]
Thanks @TeeSeal for your help.
