### ISSUE TITLE
changes made in user settings doesn't save

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#40043]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: dracula theme

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
sublime-keybindings|ms-|3.0.3
sass-indented|rob|1.4.5

(2 theme extensions excluded)

---

![image](https://user-images.githubusercontent.com/29014463/33850385-ba0df23a-ded9-11e7-8350-e6d1262678ed.png)

**Comment by ramya-rao-a** [comment]
What is the error in your User Settings file?

**Comment by mittalyashu** [comment]
This is the error I am getting.
![image](https://user-images.githubusercontent.com/29014463/33872320-6080a466-df3c-11e7-98cd-7fe1cb9aa048.png)

What happens, when I am able to edit the user setting file manually, but it doesn't work when I do change the theme or do some other changes.
![image](https://user-images.githubusercontent.com/29014463/33872378-ab5f2a2a-df3c-11e7-8084-e44575794170.png)
![image](https://user-images.githubusercontent.com/29014463/33872395-bf2cbefa-df3c-11e7-85be-0451c72c8b39.png)

**Comment by ramya-rao-a** [comment]
Do you see any red squiggles in the user settings file? If yes, then hover and share the error message there

**Comment by mittalyashu** [comment]
Red squiggles? I am not sure about it.

**Comment by sandy081** [comment]
Can you please Open Settings (File -> Preferences -> Open Settings) and see if there are any errors/red squiggles in the file

**Comment by mittalyashu** [comment]
I am not sure what red squiggles you are referring to, so here I have uploaded the screenshot of the user settings.

![image](https://user-images.githubusercontent.com/29014463/33892215-3c3d630e-df7e-11e7-8b5c-218174506376.png)

**Comment by sandy081** [comment]
Red squiggles indicate if there are errors in the file where as green indicates warnings. I think there should be an error in the file at line 10 because of missing comma in previous line. Not sure why the error is not shown, @aeschli Any idea.

@mittalyashu Can you put a comma `,` at the end of line 9 and try?

**Comment by mittalyashu** [comment]
Sure. But I haven't edited a single line in the users setting, then how this happens.

**Comment by sandy081** [comment]
No idea!

**Comment by mittalyashu** [comment]
When I got this error
![image](https://user-images.githubusercontent.com/29014463/33898184-b177de7e-df8d-11e7-9525-de5559bf7df7.png)

I try to re-install the visual studio code, but then also I got that same error.

**Comment by mittalyashu** [comment]
Yup. I know that now, but I am new to visual studio code, so I not sure
what that error means.

**Comment by sandy081** [comment]
@mittalyashu Error means that your settings file has some errors in it. As message says, you have to open it and fix those.

Let me know if fixing the errors in that file has fixed your issue?
