### ISSUE TITLE
can't installing c# extension

### ISSUE THREAD

**Issue by aaronswiftming** [Microsoft/vscode#4004]
no matter auto install or  ext install ,it doesn't  work.

**Comment by aaronswiftming** [comment]
it's working now

**Comment by weinand** [comment]
@aaronswiftming what did you do to make it work?

**Comment by aaronswiftming** [comment]
> On Mar 11, 2016, at 10:03 PM, Andre Weinand <notifications@github.com> wrote:
> 
> @aaronswiftming <https://github.com/aaronswiftming> what did you do to make it work?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Microsoft/vscode/issues/4004#issuecomment-195376922>.
> 


It’s the first time to use vs code ,so I’m acting so stupid, and then I try more times ,and wait more some minutes ,,finally it’s downloaded and installed 
successfully.
Forgive my foolery.
And thanks for your attention.

**Comment by weinand** [comment]
@aaronswiftming no worries.
Installing the C# takes some time and we do not show progress. We have improved this for the March release.

**Comment by aaronswiftming** [comment]
After I download and install  asp 5 and other stuff , and then C# can be download and install, perhaps.

**Comment by javafun** [comment]
Still can't install C# extension and receive the following error 

Failed to execute git
