### ISSUE TITLE
Cross-platform settings in package.json and launch.json for Windows and macOS

### ISSUE THREAD

**Issue by HJavier-CastilloSuazo** [Microsoft/vscode#40047]
- VSCode Version: 1.16.1 and 1.18.1
- OS Version: macOS High Sierra 10.13.2 | Windows 10

It is possible to have different values/settings for debugging and running offline no matter if it's from a Windows or macOS machine?

I mean, in a **Windows** machine I should use in the **package.json**:

```
"scripts": {
    "start": "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless offline -s dev",
    "debug": "SET SLS_DEBUG=* && node --debug %USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless offline -s dev",
    "test": "SET NODE_ENV = test && mocha --recursive test"
  }
```

And for a **macOS** the same **package.json**:

```
"scripts": {
    "start": "./node_modules/serverless/bin/serverless -s dev",
    "debug": "EXPORT SLS_DEBUG=* && node --debug ./node_modules/serverless/bin/serverless offline -s dev",
    "test": "EXPORT NODE_ENV = test && mocha --recursive test"
  }

```

And in the **Windows** machine in the **launch.json**:

```
"windows": {
    "runtimeExecutable": "npm.cmd"
}
```

And for **macOS** in the same **launch.json**:

```
"runtimeExecutable": "npm"
```

Due to some times I work from a Windows machine and some other times (same repository) from a macOS machine. How can I handle this situation without dealing with GIT merge conflicts? It would be really nice to use those platforms (npm + node.js) and tools (Visual Studio Code) as true cross-platform ecosystem.

Code to reproduce is in the repository:
https://github.com/OneMuppet/local-lambda-debug

From this post:
https://medium.com/@OneMuppet_/debugging-lambada-functions-locally-in-vscode-with-actual-break-points-deee6235f590

Thanks in advanced!

Steps to Reproduce:

1. Clone repository in a Windows machine and clone also in a macOS machine
1.1. Tweak package.json (script section) and launch.json (runtimeExecutable property) in Windows machine to work properly
2. Run on Workspace $npm install 
3. Now the files package.json and launch.json have different versions of code on each machine to achieve the same behaviour.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
We support cross platform settings in launch.json more about this can be found here https://code.visualstudio.com/docs/editor/debugging#_operating-system-specific-properties

As for the package.json we do not support that and for that I would suggest to create a new feature request which would focus only on this case. Thanks

**Comment by HJavier-CastilloSuazo** [comment]
Thanks @isidorn
