### ISSUE TITLE
Expose log level and log path to extensions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#40053]
**Problem**
The TS extension currently provides its own logging logic to write TSServer events to a file on the disk. We would like to allow extensions like TS to make use of the new logging infrastructure that was added VS Code 1.19, so that logs from both core and extensions can be written to a common logging directory

**Proposed API**
Add two new properties on `ExtensionContext`:

```ts
export interface ExtensionContext {
    ...

    loggingLevel: LoggingLevel;

    loggingDirectory: string;
}
```

The loggingDirectory would be unique to each extension and created when the extension first accesses the property. This prevents two extensions from overwriting each other if both use a file called `log` for example

**Comment by mjbvz** [comment]
A similar API was previously prototyped here: https://github.com/Microsoft/vscode/blob/verbose-logging-mode/src/vs/vscode.proposed.d.ts#L251

That version used different model for enabling or disabling logging: starting code with the `--verbose-logging` flag would enable all logging. You could also pass in scopes to specify that only specific items should log `--verbose-logging typescript`. Here, only the TS extension would have logging enabled since the `"typescript"` scope was passed in. The scopes were just strings

**Comment by mjbvz** [comment]
// cc @joaomoreno @sandy081 @jrieken

**Comment by joaomoreno** [comment]
> The loggingDirectory would be unique to each extension and created when the extension first accesses the property. This prevents two extensions from overwriting each other if both use a file called log for example

It should be unique to each `(extension host, extension)` tuple, otherwise you'll have multiple instances of the same extension using the same folder.

**Comment by jrieken** [comment]
Yeah, why don't we expose a logger? Like `vscode.env.logger`. Each extension would get it's 'branded'-logger and we tell extensions to simply use that...

**Comment by roblourens** [comment]
In cases like debug adapters or language servers, it would take extra effort to pipe log messages back into the extension host, and would create a ton of unnecessary IPC traffic, so it's better to let them write directly to some file. But I would support having a logger and also exposing their log folder.

**Comment by roblourens** [comment]
Working on this -

```
export interface ILogger {
		logDirectory: Promise<string>;
		onDidChangeLogLevel: Event<LogLevel>;
		getLevel(): LogLevel;

		trace(message: string, ...args: any[]): void;
		debug(message: string, ...args: any[]): void;
		info(message: string, ...args: any[]): void;
		warn(message: string, ...args: any[]): void;
		error(message: string | Error, ...args: any[]): void;
		critical(message: string | Error, ...args: any[]): void;
}
```

**Comment by mjbvz** [comment]
Looks good overall. Not sure if `logger` should be on `env` or `ExtensionContext` though, considering  that we want `getLogDirectory` to return a unique dir per extension.

**Comment by roblourens** [comment]
LogLevel is never synced across processes currently, right?

**Comment by sandy081** [comment]
@roblourens Log level is synced across processes during start up. But when changed afterwards using the command, then it is applied only to current renderer process. I am planning to sync it across processes. 

I suppose each extension gets its own instance of logger thereby logging into a separate file (one log file per extension)?

**Comment by roblourens** [comment]
> I suppose each extension gets its own instance of logger thereby logging into a separate file (one log file per extension)?

Yep, that's what my PR does.
