### ISSUE TITLE
Resolving custom env variables in task commands

### ISSUE THREAD

**Issue by brandonmbare** [Microsoft/vscode#40054]
I'm trying to define custom env variables somewhere in our project and have them resolve in the task commands, however it doesn't appear to be working.  I tried setting up `tasks.json` like so:

```
{
	"version": "2.0.0",
	"options": {
		"env": {
			"CUSTOM_TOOL_PATH": "<path_to_custom_tools>"
		}
	},
	"tasks": [
		{
			"label": "Run custom tool",
			"type": "shell",
			"command": "${env:CUSTOM_TOOL_PATH}/custom_tool.exe",
			"group": "build"
		}
	]
}
```

When the task runs, `${env:CUSTOM_TOOL_PATH}` is empty.  I tried moving the definition of `CUSTOM_TOOL_PATH` to `settings.json` under `terminal.integrated.env.windows`, but the result was the same.  I verified this behavior by debugging vscode and when the task command name is being resolved, the configuration resolver service object does not contain a member for `env:CUSTOM_TOOL_PATH`.

On the same note, any env variables overriden in the same manner never seem to be updated on the configuration resolver.

Is there any chance this is a feature already in progress or something that could go in the backlog?

**Comment by dbaeumer** [comment]
This is not working since the options field is used to specify the environment for the task to execute. The ${env:variable} resolves existing variables. 

You can simply use $CUSTOM_TOOL_PATH to resolve the variable assuming you run on bash/sh. Use the corresponding notation when running in cmd or powershell.
