### ISSUE TITLE
uri module lowercases drive letters on Windows

### ISSUE THREAD

**Issue by janicduplessis** [Microsoft/vscode#40057]
Hello, we are using vscode-uri (https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts in this repo) to deal with URIs in https://github.com/flowtype/flow-language-server (a Language Server Protocol implementation for flow) and noticed an issue when converting fs paths to uri then back to fs path we lose drive letter casing, which then causes diagnostic not to show properly in atom.

Here's what happens:
`C:\my\path` -> `file:///c/my/path` -> `c:\my\path`

Looking at the code, this lowercasing is definitely intentional and was wondering why it was done, and if it would be possible not to do it since it would fix my use case. If there is a valid reason why it is done and could cause issues I can just fork it but wanted to ask here first :).

PS: The irony of posting a flow/atom issue in a ts/vscode repo 😆

**Comment by jrieken** [comment]
> If there is a valid reason why it is done and could cause issues

We wanted consistency and picked on of two options ;-). I wonder why that's an issue for you?

**Comment by janicduplessis** [comment]
@jrieken  My guess is that atom uses strict comparison for file paths so C:\my\path !== c:\my\path when displaying diagnostics. I just debugged the inputs / outputs and noticed the paths were different when converting a fs path to uri then back to fs path, I don't really know more than that.

Technically it should work on Windows since paths are not case sensitive by in practice this is not always the case. I feel like fixing it here would probably be easier than fixing all paths comparisons and make sure they are not case sensitive on Windows (Are you doing this in vscode?).

**Comment by jrieken** [comment]
> I feel like fixing it here would probably be easier than fixing all paths comparisons and make sure they are not case sensitive on Windows

Yeah, we kind of do that. When creating paths/uris we know how we create them, when accepting uris from 3rd parties, e.g. extensions & user content, we normalise them.
