### ISSUE TITLE
[folding] Make it more obvious where a region is collapsed

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#4005]
After coming back to some code after a few hours, I had forgotten that I collapsed a method. It was not obvious where the region was after spending a moment scrolling up and down the file a couple times looking for the method. The little plus sign, and really faint ellipsis, just isn't enough and is probably why VS puts a big white box around their ellipsis symbol. A horizontal line across the editor might also work (if multiple lines are collapsed).

**Comment by FeaRCODE** [comment]
I recommended something like Visual Studio's implementation. Check here : https://github.com/Microsoft/vscode/issues/4096
