### ISSUE TITLE
Wording issue

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode#40064]
https://github.com/Microsoft/vscode/blob/c70c818503e961f7f380e2a0037f97d167f1d7ce/src/vs/workbench/api/node/extHostTypes.ts#L94
https://github.com/Microsoft/vscode/blob/c70c818503e961f7f380e2a0037f97d167f1d7ce/src/vs/workbench/api/node/extHostTypes.ts#L97

Might better to be ".... must be non-negetive"

**Comment by jrieken** [comment]
>  must be non-negetive

Why is that?

**Comment by jdneo** [comment]
https://github.com/Microsoft/vscode/blob/c70c818503e961f7f380e2a0037f97d167f1d7ce/src/vs/workbench/api/node/extHostTypes.ts#L93-L95

This is not a big problem, according to the if condition, the line number is also valid if it is zero, so not only positive right? 😄

**Comment by jrieken** [comment]
Right. Take a shot, this is a good PR candidate

**Comment by pfongkye** [comment]
hi @jdneo @jrieken 
would you mind if I provide a PR for this one?

**Comment by jdneo** [comment]
@pfongkye That's OK for me.
