### ISSUE TITLE
Git editor and -w / --wait mode for Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4006]
**Assignees:**

- [x] Windows @SofianHn
- [x] OS X @joaomoreno 
- [x] Linux @jrieken  

We added a new command line option `--wait` that makes sure the command only returns after the Code window is closing. This is useful in scenarios where you want to use Code as editor for other tools (e.g. Git)
* verify the command line option makes the command line only return when the window closes or the application exits
* verify this works both when Code is not yet running as well as when Code is running
* play around with configuring Code as editor for git to see how this works (see below)
* verify you get coloring for `git commit` message, `git add -p` patches and `git rebase` interactive

**Configure Code for Git**
There are some areas where it makes sense to use Code for Git
* `git config --global -e` allows you to edit git config with Code
* `git rebase HEAD~3 -i` allows to interactive rebase using Code
* `git commit` allows to use Code for the commit message
* `git add -p` followed by <kbd>E</kbd> for interactive add
* `git difftool <commit>` allows to use Code as diff editor for changes

From the command line run `git config --global -e` and make sure to have the following entries

```ini
[core]
	editor = code-alpha --wait
[diff]
	tool = default-difftool
[difftool "default-difftool"]
	cmd = code-alpha --wait --diff $LOCAL $REMOTE
```

Note: you will need `code-alpha` on the `PATH` (you can use F1 to install)

**Comment by felixfbecker** [comment]
May I suggest that you also test `git add -p` and pressing <kbd>E</kbd> to edit a hunk?

**Comment by bpasero** [comment]
@felixfbecker now we just need coloring I guess ;)

![image](https://cloud.githubusercontent.com/assets/900690/13701458/5b9f1674-e788-11e5-8779-be4ff21df750.png)

**Comment by bpasero** [comment]
Getting there: 

![image](https://cloud.githubusercontent.com/assets/900690/13701528/bd8ae69c-e788-11e5-835b-e4455a8f840f.png)

**Comment by felixfbecker** [comment]
@bpasero Nice. I use this very often.

**Comment by bording** [comment]
With other text editors, for example Sublime, I also need to specify the `-n` option to make sure that a new editor window always opens and to ensure it only needs to wait for that one window to close before returning to the command line. Otherwise, I find myself needing to close all instances of the editor before it returns.

How is this currently working in Code? How do `-w` and `-n` interact?

**Comment by bpasero** [comment]
@bording good point, I decided to force a new window always when `-w` is specified because opening it in an existing instance seems weird. Closing the window causes the script to terminate, independent if there are other windows open or not. I hope @Tyriar and @joaomoreno can verify all these corner cases during testing next week :)

**Comment by felixfbecker** [comment]
@bpasero Isn't VS Code always opening a new window anyway if `-r` is not specified?

**Comment by bpasero** [comment]
@felixfbecker yeah typically it is, there is a setting though `window.openFilesInNewWindow` which can cause any files to open in the last used instance. `--wait` overrules this now. Same as overruling `-r`.

**Comment by bording** [comment]
Just doing a quick test with 0.10.10, if I run `code.cmd` from the command line, I don't see a `-r` option listed. If I run it without any options, it reuses an existing window. I have to use `-n` to get a new window.

**Comment by bpasero** [comment]
The help was outdated in 0.10.10 and we since fixed that. Can you share some steps and your Code settings for me to reproduce? I suggest to do this from a new issue and not here.

**Comment by robsonpeixoto** [comment]
How to wait only for open files?
Here a gif how textmate works:
![small](https://user-images.githubusercontent.com/124390/27516658-8c5012bc-5994-11e7-963c-9b11d17f7f4d.gif)

**Comment by felixfbecker** [comment]
@robsonpeixoto git will wait until the process exits, no matter the editor. you can use -n to open a new window with just the file open.

**Comment by 98Anushka** [comment]
![screenshot 6](https://user-images.githubusercontent.com/26124158/27768296-17e384a6-5f2d-11e7-86cf-4167a4025397.png)
$ git config --global core.editor "C:\Program Files\Sublime Text 3\sublime_text.exe" -n -w
Even after configuration, my commit command is not working properly.

**Comment by felixfbecker** [comment]
Why Sublime?

**Comment by 98Anushka** [comment]
Because I've been using it for some time now and I'm comfortable with it.

**Comment by felixfbecker** [comment]
But why do you post your sublime config on this issue?
