### ISSUE TITLE
feat: ability to navigate terminal to arbitrary folder using the file explorer

### ISSUE THREAD

**Issue by thefliik** [Microsoft/vscode#40063]
### Feature Request:

Ability to select a folder in the file explorer, right click, and select a dropdown option to make the terminal window automatically `cd` into that folder.

### Why

To improve the experience of using tools like angular cli, which can generate files and place them in the current terminal folder. Also, `cd` ing through many folders gets tedious, and it would be nice to use the vscode terminal / explorer integration to jump around.

Love your work on vscode btw!

**Comment by ramya-rao-a** [comment]
Have you tried the `Reveal in Terminal` option in the context menu on the file explorer?
It does exactly what you described.

**Comment by thefliik** [comment]
Wow, I don't know how I missed that <face_palm>. Thank you!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
