### ISSUE TITLE
Clear command inside docker container clear entire area is vscode terminal

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#40069]
Clear command used inside the docker container clears the whole terminal 

Steps to Reproduce:

![docker clear](https://user-images.githubusercontent.com/2253649/33869374-5c5c2814-df2e-11e7-88bd-267ae4b3af80.gif)

**Comment by Tyriar** [comment]
Isn't this as expected?

**Comment by Jeyanthinath** [comment]
@Tyriar I feel the clear inside docker should clear upto the forked shell ( I mean docker shell ) , not the entire shell isn't it ?

**Comment by Tyriar** [comment]
@Jeyanthinath I don't think any other terminals do this though do they? The terminal emulator doesn't know that it's running inside something else, it just gets instructions to clear the buffer.
