### ISSUE TITLE
UI messy

### ISSUE THREAD

**Issue by Oohyo** [Microsoft/vscode#40065]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
GBKtoUTF8|buk|0.0.2
path-intellisense|chr|1.4.2
python-snippets|cst|0.1.0
vscode-instant-markdown|dba|1.3.0
jquerysnippets|don|0.0.1
Vue2|duc|0.1.3
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
vscode-fileheader|mik|0.0.2
python|ms-|0.8.0
cpptools|ms-|0.14.4
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vscode-html-scss|P-d|0.0.42
vscode-icons|rob|7.19.0
background|sha|1.1.17
markdown-preview-enhanced|shd|0.3.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
prettify|whi|0.0.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Oohyo** [comment]
[C:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.14.4]: 命令“workbench.action.gotoSymbol”多次出现在“命令”部分。

**Comment by ramya-rao-a** [comment]
@Oohyo Please explain what your issue is with reproducible steps.
