### ISSUE TITLE
Can not find `Rename Symbol` in editor while edit `.vue` file

### ISSUE THREAD

**Issue by chinaHewei** [Microsoft/vscode#40062]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
vsc-material-theme|Equ|1.1.2
beautify|Hoo|1.1.1
material-icon-theme|PKi|3.1.0
vscode-docker|Pet|0.0.22
html-snippets|abu|0.1.0
vscode-caniuse|aka|0.5.3
vscode-database|baj|1.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.3.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
flow-for-vscode|flo|0.7.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
vscode-flow-ide|gca|1.2.0
vscode-nginx-conf-hint|han|0.0.4
vscode-exec-node|mir|0.5.0
easy-less|mrc|1.4.5
mssql|ms-|1.3.0
debugger-for-chrome|msj|3.5.0
editorconfiggenerator|nep|0.2.1
vetur|oct|0.11.3
vscode-nginx|sha|0.4.1
code-spell-checker|str|1.6.0
open-in-browser|tec|1.1.0
vim|vsc|0.10.5
vscode-todo-highlight|way|0.5.11

(3 theme extensions excluded)

---

Steps to Reproduce:

1. open `.vue` file
2. try to rename symbol
3. can not found `Rename Symbol`

Reproduces without extensions: No

---

Relevant screenshots

![image](https://user-images.githubusercontent.com/20341343/33863592-750ab872-df23-11e7-88f7-5437a71be2ab.png)

**Comment by octref** [comment]
That's correct. We don't have it implemented yet. You can track https://github.com/vuejs/vetur/issues/97

**Comment by chinaHewei** [comment]
All right, thank you
