### ISSUE TITLE
update is not override the old version but reinstall

### ISSUE THREAD

**Issue by AdoBeatTheWorld** [Microsoft/vscode#40061]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
lua-debug|dev|1.1.0
Lua|key|0.0.9
Go|luk|0.6.69
debugger-for-chrome|msj|3.5.0
typescript-hero|rbb|1.7.0
java|red|0.15.0
python|tht|0.2.3

---

Steps to Reproduce:

1. my vs code is installed in f: disk version 1.15
2. every time i followed the tips do the updates, the latest verison 1.18 was installed in my c: disk
3. next time when i run the shortcut of vs code on my desktop it would remind me to update again

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you completely remove Code, and reinstall it in `F:` again?

**Comment by AdoBeatTheWorld** [comment]
1. the vs code present in the control panel is 1.18
2. go to the vs code 1.15 directory in the f: disk, and run the unintall.exe removed the 1.15
3. download the 1.18 installer and run
4. suceess 

i remember it appeared on my mac too.
follow the tips update the vs code can not replace the older version,
every time i run vs code via terminal it is the older version.
now i remember there is another editor extended from vs code installed on both machine.
i checked the package.json in the directory,
`"dependencies": {
...
"vscode-debugprotocol": "1.15.0",
    "vscode-textmate": "2.3.2",
    "winreg": "1.2.0",
    "xterm": "git+https://github.com/Tyriar/xterm.js.git#vscode-release/1.9",
...
}
  "devDependencies": {
...
 "vscode-nls-dev": "^2.0.1"
...
}
`

**Comment by joaomoreno** [comment]
Please completely remove **all** instances of Code in your machine. Then reinstall it.
