### ISSUE TITLE
jsconfig.json guidance

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4007]
- [x] win @egamma  
- [x] os x @chrisdias 
- [x] linux @isidorn

Make sure that you get guidance to

* create a jsconfig.json when working with JS files
* exclude big subfolders in a large project (>500 files)

**Comment by isidorn** [comment]
ping @chrisdias this item was accidently not assigned to march, so pinging you so you are aware that we have to test this

**Comment by chrisdias** [comment]
@isidorn done with testing, biggest thing found was #4254, same problem on OSX.
