### ISSUE TITLE
Feature Request: Alt+Click on file in Source Control Side Panel opens file

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#40077]
VS Code is very convienient when revieweing work. The source control panel allows one to quickly skim the changes, and asses one's next step. 

Something I do constantly, after I review my work midway, is open a file from the list to continue working on it. I right click, click `open file` (in contrast with `open changes`).

It be nice to bind it to alt+click.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/32129
