### ISSUE TITLE
Bring back activity progress

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40079]
https://github.com/Microsoft/vscode/commit/21814bb341ef28d2300e78872a4e79a8681f2f6c removed the progress.

Let's implement what @jrieken suggests:

> Well, you already have it. You can return a promise that is composted from multiple different promises and that reflects all different activities. There is no reason to calling withScmProgress from different (competing, overlapping) spots

**Comment by joaomoreno** [comment]
Was a bit trickier than anticipated since the activity service didn't have the notion of priority between the badges, but all is good.

**Comment by bpasero** [comment]
@joaomoreno steps?

**Comment by joaomoreno** [comment]
Basically, the SCM activity icon should display a progress badge on long operations. 👍
