### ISSUE TITLE
font in terminal console looks too wide

### ISSUE THREAD

**Issue by kinshines** [Microsoft/vscode#40071]
- VSCode Version:1.18.0

Steps to Reproduce:

1. I set the editor fontFamily as:  "editor.fontFamily": "'Segoe UI', Consolas, 'Microsoft YaHei'",
2. the font in terminal console looks too wide so that it can not display the output totally

![qq 20171212142949](https://user-images.githubusercontent.com/7374965/33870655-cc5ca560-df49-11e7-8820-aa60e943ed6e.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
You will need to use a monospace font, see https://github.com/Microsoft/vscode/issues/35681
