### ISSUE TITLE
Extension Info page reload and scrolled to top when switch back from other tab

### ISSUE THREAD

**Issue by susan51531** [Microsoft/vscode#40072]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
php-formatter|Sop|0.2.4
html-snippets|abu|0.1.0
vscode-opennewinstance|chr|0.0.4
vscode-eslint|dba|1.4.3
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
rest-client|hum|0.16.1
Go|luk|0.6.69
python|ms-|0.8.0
cpptools|ms-|0.14.4
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|3.5.0
vetur|oct|0.11.3
vscode-icons|rob|7.19.0
language-stylus|sys|1.8.0
vim|vsc|0.10.5
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1.Clicked an installed extension to open its info tab, scroll down few pages in the new tab.
2.switch to other tabs
3.switch back to the tab opened in the first step.

I don't know whether this is a feature or not. Just feel a little annoy have to scroll a little when switching back from other tabs if the info page is very long. The result I expect is not reloading or just keep the old scroll position. I usually open the online doc for reference.

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
duplicate #27498
