### ISSUE TITLE
jsonValidation fileMatch as glob pattern?

### ISSUE THREAD

**Issue by hilleer** [Microsoft/vscode#40082]
- VSCode Version:
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. In an extension, in `package.json` add a `"contributes": {}` object, and add a property `"jsonValidation": [{"fileMatch": ".jshintrc", "url": ""}]`

2. Can we have jsonValidate.fileMatch take a glob pattern, rather than just a file association so you could target multiple patterns in the same setting, rather than duplicating? 

[jsonValidation documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation)

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
You can use `*` in the pattern, isn't that good enough?

**Comment by hilleer** [comment]
@aeschli what if you want to target specific filename pattern? 

**Example:** `**/?(patternOne|patternTwo|patternThree|)`.

**Comment by aeschli** [comment]
You have to repeat the contribution point:
    "jsonValidation": [
      {
        "fileMatch": "*.patternOne",
        "url": "http://schema/foo#"
      },
      {
        "fileMatch": "*.patternTwo",
        "url": "http://schema/foo#"
      },
      {
        "fileMatch": "*. patternThree",
        "url": "http://schema/foo#"
      }
    ]

I think repeating is acceptable here and not much of a burden.

Unless there is a association that can not be expressed, I suggest to close this issue.

**Comment by hilleer** [comment]
That's how I solved it. Just thought the possibility of having something like my example, would have been a nice addition to the feature. 

Thanks for your time. Closing.
