### ISSUE TITLE
VS code crashing repeatedly - Log

### ISSUE THREAD

**Issue by kiranbose** [Microsoft/vscode#40081]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
tortoise-svn-for-vscode|cds|0.1.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-svn|eli|0.1.0
auto-close-tag|for|0.5.5
beautify|Hoo|1.1.1
vscode-angular2-emmet|jak|2.0.3
vscode-paste-and-indent|Rub|0.0.8
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please read https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues and https://github.com/Microsoft/vscode/wiki/Performance-Issues and share more details

These pages have steps on how best to report issues regarding perf and crashes.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
