### ISSUE TITLE
Add option to disable search widget scrolling file above first line

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#40085]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
find-related|eam|0.6.0
vscode-duplicate|mrm|1.2.0
oracle-plsql|myc|1.0.3
gitblame|wad|2.2.0

The way the file is stretched is very weird and confusing and random. In my view the search widget should not do this or it should be possible to disable this behavior.

This was introduced here: https://code.visualstudio.com/updates/v1_13#_find-widget

---

Steps to Reproduce:

1. open search widget (Ctrl+F)
2. file scrolls several lines down

Reproduces without extensions: Yes/No

**Comment by Simran-B** [comment]
But what if you need to see what is beneath the find widget? Scrolling above the first line allows the user to unveil what's hidden by the widget.

![image](https://user-images.githubusercontent.com/7819991/34293225-45678986-e704-11e7-9e8f-e5e83aa550d7.png)

**Comment by usernamehw** [comment]
@Simran-B Making the widget draggable?

**Comment by PunchyRascal** [comment]
There are many ways, much more sensible than creating "virtual" lines above line 1, which is quite obscure solution if you ask me.

- draggable dialog
- semi-transparent dialog (if needed)
- detached dialog (similar to draggable) - as in word processors
- dedicated space in chrome of the editor, not in the actual file's text - such as is used in Android studio

**Comment by Simran-B** [comment]
Draggable and semi-transparent dialogs, like found in Notepad++, have much worse UX in my opinion.

Draggable means, that it is opened again at the old location, which can be unexpected, or at the initial position again, which can also be undesired.

Semi-transparent doesn't work well. Either the text beneath it, or the stuff in the widget will be hard to read. This is still true, if the widget becomes more opaque when focused.

There is still the problem of the dialog overlapping a match. In Notepad++, the dialog moves to avoid it, which fulfills the purpose, but it's visually annoying.

> dedicated space in chrome of the editor

You mean like the global search, but limited to the current file? That would certainly need to be combined into one panel. But then you need to change options all the time, depending on what you want to do (local search, global search, search in files).

**Comment by PunchyRascal** [comment]
No I mean like e.g. in Android studio:
![image](https://user-images.githubusercontent.com/821272/34298599-d55b18e0-e71e-11e7-90e3-7424b6e90b3e.png)

**Comment by Simran-B** [comment]
That would essentially fill the space above the first line, and make the widget non-floating:

![image](https://user-images.githubusercontent.com/7819991/34298882-3649646c-e720-11e7-98e4-90ff58fe6262.png)

When opening it, the text needs to be pushed down. That means, the text will jump, although nothing really happened. With the current floating widget, there is no such movement.

**Comment by PunchyRascal** [comment]
Please stop negating all I post, and if you're interested, try the search in Android studio and then post, because what you say is not true. It is a little tiresome really.

**Comment by rebornix** [comment]
Thanks, all your feedback are received. Let's track this issue in https://github.com/Microsoft/vscode/issues/28390 .
