### ISSUE TITLE
Invisible underscore in integrated terminal

### ISSUE THREAD

**Issue by programmer04** [Microsoft/vscode#40084]
- VSCode Version: 1.18.1
- OS Version: Fedora 26 (4.13.13-200.fc26.x86_64)

Steps to Reproduce:

1. Go to integrated terminal.
2. Type something, which contains an underscore, for example `MY_VARIABLE="test"`
![screenshot from 2017-12-12 12-04-49](https://user-images.githubusercontent.com/9593424/33881323-becf4796-df34-11e7-9bb2-a749e4b118c3.png)
Underscore is invisible.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
