### ISSUE TITLE
jsconfig target

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#40094]
- VSCode Version: 1.18.1
- OS Version: macOS

Steps to Reproduce:

1. Create array:
```js
const arr = [];
```
2. Try to get autocomplete for `includes`. There's no such, because you need to create `jsconfig.json` and set target to `es2016`.

My suggestion is to use `"target": "es2016"` by default in VS Code instead of `es2015`. I don't really like the idea to create `jsconfig.json` if I want to get proper autocomplete.

Thank you!

cc @mjbvz

**Comment by mjbvz** [comment]
@DanielRosenwasser / @ RyanCavanaugh Any thoughts on this? We set `"target": "es6"` for inferred projects currently

**Comment by DanielRosenwasser** [comment]
Set `"target": "esnext"`

**Comment by mjbvz** [comment]
As the default for all users though?

**Comment by DanielRosenwasser** [comment]
Tagging @RyanCavanaugh properly.

I guess it's a matter of weighing the risk of serving up declarations that won't exist against the confusion of your declarations not showing up. I'm biased towards showing users the suggestions and then restricting the settings after the fact if that's not what you want, but TypeScript itself takes the opposite approach. I've heard users complain about the current TypeScript setup, but I have no way to gauge the situation if we had gone the other way.

It's going to be 2018 in 3 weeks, so switching to `"lib": "es2016"` or `"target": "es2016"` is probably a good idea minimally.

**Comment by bsvipas** [comment]
@mjbvz @DanielRosenwasser Thank you very much! 🎉
