### ISSUE TITLE
Missing command to set focus to "currently open project" in side bar

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4009]
Someone closed out the last issue I had open for this, without a proper answer, so I'm creating a new one.

https://github.com/Microsoft/vscode/issues/3968

> There's options for View: Focus into Side Bar and View: Focus on Working Files, but there isn't any option for View: Focus into Open Project. Please add this.

<img width="425" alt="screen shot 2016-03-10 at 9 33 58 am" src="https://cloud.githubusercontent.com/assets/466713/13676522/6a4932c6-e6a3-11e5-9f89-0c9855675ac9.png">

The "answer" that was authoritatively posted into that thread, only works if focus was not previously set to the _Working Files_ section of the Side Bar. If _Working Files_ was the last "area" to have focus in the Side Bar, before focus was moved away, then the `CMD + SHIFT + E` shortcut will simply return it to _Working Files_ instead of the project.

**SIDE NOTE**: I'd recommend allowing people some time to respond, before closing out their GitHub issues. People who don't administer the GitHub project **cannot** re-open their issues, if they're closed out by a project member. Recently, I've been quite diligent about following up on tickets that I've reported, so I'd appreciate an opportunity to hash things out fully, instead of assumptions being made. The Visual Studio Code team has been doing some very good work; it's my hope that this continues.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by bpasero** [comment]
@pcgeek86 sorry but what is wrong with commenting on the closed issue so that I can reopen it? Am I missing something?

**Comment by pcgeek86** [comment]
@bpasero Because there is a good chance that it will not be re-opened by someone, and disappear under closed issues long term. Perhaps with the VS Code team this is less of an issue, but I've seen it happen on other Microsoft projects, so I'm investing my time and effort in a way that I know it'll get noticed.

**Comment by bpasero** [comment]
@pcgeek86 try it out please :)

**Comment by pcgeek86** [comment]
@bpasero Thanks a lot! I'll test this out once it's available.
