### ISSUE TITLE
Bug: Tabs in mac (High Sierra) not work

### ISSUE THREAD

**Issue by nicobytes** [Microsoft/vscode#40091]
- VSCode Version: 1.18.1
- OS Version: High Sierra

Steps to Reproduce:

1. Open vscode
2. File -> New window
3. Tabs in mac not work

![vscode](http://i.cubeupload.com/d5Dofb.png)

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/35361
