### ISSUE TITLE
vscode started 7 processes and took up 200+M memory even with NO files opened

### ISSUE THREAD

**Issue by shikouzhong** [Microsoft/vscode#40093]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.4
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. just start vscode, and no files opened;
2. the task manager shows that it started 7 processes and took up 200+M memory!
3. if I open any other files, more processes begins working.

I don't know weather it is normal or a bug.

**Comment by bpasero** [comment]
This is normal, VS Code is a multi-process application.
