### ISSUE TITLE
Feature Request: Editor/Extension profiles per project

### ISSUE THREAD

**Issue by lunsdorf** [Microsoft/vscode#40109]
Since VSCode became a solid platform for developing software in many different languages, it would be nice to have something like an editor profile per project, so that only relevant extensions would be loaded for that project. Ideally, extensions could be installed automatically if I would checkout an existing project that contains a profile and requires extensions that I don't have, yet.

**Comment by leocb** [comment]
Yes! This would be very useful, maybe also add a menu with `workspaces` that set the active extensions, configuration and themes, just like adobe does with their products. For example, one could create a workspace named `Angular development`, then another one named `PHP development`, with a option to save the current configuration to the project folder and some way to manage and edit/copy the workspaces.
Such options would make the process of creating the scaffold a lot easier for new projects and would help teams sincronize their environments.

**Comment by jcrben** [comment]
Is this different from https://github.com/Microsoft/vscode/issues/40239?

**Comment by lunsdorf** [comment]
Indeed, both of these features seem to target the same goal.

**Comment by jcrben** [comment]
There's also [Persisting "disable by workspace" settings in source control](https://github.com/Microsoft/vscode/issues/18386)

The fact that there's currently a disable by workspace which saves to local storage makes it seem like this may not be a very big lift.

**Comment by jcrben** [comment]
@lunsdorf perhaps close this as a duplicate to focus attention on the earlier issue?

**Comment by lunsdorf** [comment]
@jcrben Which issue do you refer to, #18386 or #40239? I think the latter one is more like a subset of this one. Implementation of #15611 is great, although I don't know how installation of new extensions is handled by that.
The way I though about this was, that if I am a new developer on an existing project, I would simply checkout the source files, open it in VSCode and the editor would then ask me if it should install/configure all depending extensions and if I would hit the "yes" button everything would be setup and ready to go :-)

Besides that I agree on focusing on just one issue and wouldn't mind closing this one if the other requests the same feature.

**Comment by jcrben** [comment]
I think #40239 should be closed as duplicates this one.

And I think this one would be best implemented by focusing on improving the current system with https://github.com/Microsoft/vscode/issues/18386.

>  I would simply checkout the source files, open it in VSCode and the editor would then ask me if it should install/configure all depending extensions

There's already Extension Recommendations https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extension-recommendations - does that not accomplish the prompt for install? A similar recommendation ssytem also applies for the folder-level settings.json as well I think.

So the last step is to automatically enable extensions after installing them, which is covered by https://github.com/Microsoft/vscode/issues/18386

**Comment by lunsdorf** [comment]
Closing this issue in favor of #18386 and #39272.

**Comment by jcrben** [comment]
If everyone who voted for this would vote for those two, it might get noticed more.  That  https://github.com/Microsoft/vscode/issues/15611 had 61 votes and I think most of those people really would like this more complete solution (@sandy081).

Also, for per-project profiles while sharing a team project settings, there's [Add ability to extend from other settings files](https://github.com/Microsoft/vscode/issues/15909) which I discussed in a bit more detail at https://stackoverflow.com/a/49213663/4200039
