### ISSUE TITLE
Format Document saves files immediately without prompting

### ISSUE THREAD

**Issue by RoscoP** [Microsoft/vscode#40117]
- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open an unformatted json file
2. Select "Format Document"
3. Notice the file is saved after formatting without any prompting to the user (or just left as modified in the editor).

I have no *format settings in my user/workspace settings.

**Comment by ramya-rao-a** [comment]
I cannot repro. The json file does not get saved when I format it.

Maybe one of your extensions is interfering.

Can you run `code --disable-extensions` and try again?

**Comment by RoscoP** [comment]
Weird, I tried this again with the `--disable-extensions` param and I was able to reproduce it.

**Comment by jrieken** [comment]
@RoscoP Please update your steps as this doesn't reproduce for me. Also there no save-call in the whole format-logic, so I have doubt you ran without extensions or that you don't have auto-save enabled

**Comment by RoscoP** [comment]
Sorry for the hassle, found it in my users settings:
`"files.autoSave": "afterDelay"`
