### ISSUE TITLE
Angular Language Service extension abandoned and buggy?

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#40118]
- VSCode Version: Code - Insiders 1.19.0-insider (d8989c95964ce06c64ffebc2fb400a0327bd447d, 2017-12-08T10:45:40.870Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
githistory|don|0.2.3
tslint|eg2|1.0.24
auto-rename-tag|for|0.0.15
Angular2|joh|2.11.2
json-to-ts|Mar|1.5.4
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|1.7.2
prettify-json|moh|0.0.3
csharp|ms-|1.13.1
material-icon-theme|PKi|3.1.0
view-in-browser|qin|0.0.5

(2 theme extensions excluded)

Any chance that the Angular Language Service can either get rolled into the core VS Code, or the extension get some attention? There's been no updates for a while, and it has major bugs (intellisense issues, crashing, etc.)

**Comment by kieferrm** [comment]
@jtsom We'll reach out to the angular team. We won't bring Angular support into the core though.
