### ISSUE TITLE
Option to have debug sidebar not appear when starting/restarting debugging

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#4011]
I work with the sidebar normally closed so it's very annoying for me that the debug sidebar keeps popping out whenever starting or restarting debugging. It's not just having to press ctrl+b each time; it's also jarring visually. Would very much appreciate this option :)

Even if the just sidebar only popped out when starting and not every time when restarting that would be an improvement.

**Comment by isidorn** [comment]
This has already been reported by the user (for some reason I can not dig up that bug).
We have fixed it and it should not be happening with the latest vscode (0.10.10) Just tried and I can not reproduce

**Comment by stkb** [comment]
Hmm now you mention it, it happens less than I thought!
But it definitely happens in one case, and that is when you're developing an extension, and have a secondary vscode window (the one spawned by debugging). If you press ctrl+r in that window to refresh, the debug sidebar will pop out again in the main window.

I think it can happen in other cases too, but the next time I have it, I'll try to work out the steps to reproduce.

**Comment by isidorn** [comment]
Yeah, steps would be great - thanks
