### ISSUE TITLE
"files.trimTrailingWhitespace": true - does not work anymore

### ISSUE THREAD

**Issue by mwager** [Microsoft/vscode#40113]
The config `"files.trimTrailingWhitespace": true,` does not seem to work anymore. I cannot figure out why. It worked in some version before.

Version 1.18.1 (1.18.1)
929bacba01ef658b873545e26034d1a8067445e9
On a Mac

My User settings:

```
{
    "files.autoSave": "onFocusChange",
    "workbench.colorTheme": "Solarized Dark",
    "editor.wordWrap": "on",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "window.zoomLevel": 0,

    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#135564", //For when you highlight a selection
        "editor.selectionHighlightBackground": "#135564" //For when the editor highlights all similar words
    },

    "html.format.wrapAttributes": "force",

    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.detectIndentation": true,
    "editor.codeLens": false,
    "explorer.confirmDragAndDrop": false
}
```

With this settings, if I have trailing whitespace in a file and save, it does not get trimmed.

**Comment by ramya-rao-a** [comment]
I just tried on my Mac using VS Code 1.18.1 and your settings and the trailing whitespace is getting removed as expected on save.

Can you run `code --disable-extensions` and try again?

**Comment by mwager** [comment]
Nevermind, uninstall and fresh installation fixed it. Closing.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
