### ISSUE TITLE
Add LinqPad c# coding execution support to VSCODE please

### ISSUE THREAD

**Issue by bgaldamesdtm** [Microsoft/vscode#40116]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vstortoise|flo|1.1.1
svn-scm|joh|1.4.5
csharp|ms-|1.13.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
This is a feature request for an extension and not the core VS Code product
