### ISSUE TITLE
Allow  'Show On Side 'To Appear When Right Clicking Open File Tab

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#40119]
Hi I clicked 'Request a missing feature' in VS Code and was taken to this page.

So here is the request:
When I have multiple files open, I would like to be able to right click on one of the file tabs and have option to select 'Open to the Side'.  This enhancement would be a bit quicker than having to find the file again in Explorer and selecting 'Open to the Side' from there

**Comment by bpasero** [comment]
This landed as part of https://github.com/Microsoft/vscode/issues/14909#issuecomment-393870565

![image](https://user-images.githubusercontent.com/900690/40872648-198c9946-6652-11e8-9a53-35e298809ae0.png)

**Comment by MarkPhillips** [comment]
Not sure what the above response is intended to indicate. I am using VSCode Version 1.23.1 on Windows 10.  Currently none of the Split menu items listed above are appearing when I right click a file tab.  Is this change coming out in the next release? 

![filecontextmenu](https://user-images.githubusercontent.com/4471426/40894801-032f23d4-677a-11e8-90f1-b9eed61b531c.PNG)

**Comment by MarkPhillips** [comment]
If you added this new feature.  Thank you very much!!!

**Comment by bpasero** [comment]
@MarkPhillips that is why I pointed you to https://github.com/Microsoft/vscode/issues/14909#issuecomment-393870565
