### ISSUE TITLE
Cursor appears before decoration on empty lines

### ISSUE THREAD

**Issue by nicksnyder** [microsoft/vscode#40127]
Extensions like Gitlens register a decoration that appears before each line.

For lines that have content in them, everything works as expected: if you click on the decoration the cursor is placed at the beginning of the line AFTER the decoration.

For lines that do not have any content, the cursor is place BEFORE the decoration. This behavior seems strange.

![screen recording 2017-12-12 at 10 46 am](https://user-images.githubusercontent.com/754768/33902415-c898b862-df29-11e7-808e-39370896988f.gif)

**Comment by eamodio** [comment]
@nicksnyder does GitLens always display the annotations chopped like that (where the heatmap is going through the date)?

**Comment by nicksnyder** [comment]
@eamodio it looks like a bug with gitlens. Filed https://github.com/eamodio/vscode-gitlens/issues/228

Broken configuration:
```
"gitlens.blame.file.lineHighlight.locations": [
        "gutter",
        "overviewRuler"
    ],
    "gitlens.annotations.file.gutter.compact": false,
    "gitlens.annotations.file.gutter.format": "[${author|20?}] ${message|20?} ${ago|14-}",
```

Working configuration
```
"gitlens.blame.file.lineHighlight.locations": [
        "gutter",
        "overviewRuler"
    ],
    "gitlens.annotations.file.gutter.compact": false,
    "gitlens.annotations.file.gutter.format": "${id} [${author|15?}] ${message|20?} ${ago|14-}",
```

You should be able to reproduce (the screencap is from mainThreadStorage.ts in vscode).

**Comment by nicksnyder** [comment]
(even with a working configuration, the issue I reported here still exists)

**Comment by eamodio** [comment]
@nicksnyder thanks!

**Comment by alexandrudima** [comment]
Here is the extension I've tried with (which works for me):

* `package.json`:
```js
{
    "publisher": "alex",
    "name": "40127",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	var dectype = vscode.window.createTextEditorDecorationType({
		before: {
			contentText: "1234567890",
			color: "#ff0000"
		}
	});
	vscode.window.activeTextEditor.setDecorations(dectype, [
		new vscode.Range(0, 0, 0, 0),
		new vscode.Range(1, 0, 1, 0),
		new vscode.Range(2, 0, 2, 0),
		new vscode.Range(3, 0, 3, 0),
		new vscode.Range(4, 0, 4, 0),
		new vscode.Range(5, 0, 5, 0),
		new vscode.Range(6, 0, 6, 0),
		new vscode.Range(7, 0, 7, 0),
		new vscode.Range(8, 0, 8, 0),
		new vscode.Range(9, 0, 9, 0),
	]);
}
```

![kapture 2018-04-27 at 10 34 52](https://user-images.githubusercontent.com/5047891/39352969-a5b5f74a-4a06-11e8-9c85-056df8c02028.gif)

@eamodio Do these lines get both before and after inline decorations ?

**Comment by eamodio** [comment]
@alexandrudima yeah, if you have the inline blame turned on, the selected line will also get an after at the end of the line.

**Comment by alexdima** [comment]
To verify:
* `package.json`:
```json
{
    "publisher": "alex",
    "name": "40127",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
	const dectype1 = vscode.window.createTextEditorDecorationType({
		before: {
			contentText: "1234567890",
			color: "#ff0000"
		}
	});
	vscode.window.activeTextEditor.setDecorations(dectype1, [
		new vscode.Range(0, 0, 0, 0),
		new vscode.Range(1, 0, 1, 0),
		new vscode.Range(2, 0, 2, 0),
		new vscode.Range(3, 0, 3, 0),
		new vscode.Range(4, 0, 4, 0),
		new vscode.Range(5, 0, 5, 0),
		new vscode.Range(6, 0, 6, 0),
		new vscode.Range(7, 0, 7, 0),
		new vscode.Range(8, 0, 8, 0),
		new vscode.Range(9, 0, 9, 0),
	]);
	const dectype2 = vscode.window.createTextEditorDecorationType({
		after: {
			contentText: "abcd",
			color: "#00ff00"
		}
	});
	vscode.window.activeTextEditor.setDecorations(dectype2, [
		new vscode.Range(0, 1000, 0, 1000),
		new vscode.Range(1, 1000, 1, 1000),
		new vscode.Range(2, 1000, 2, 1000),
		new vscode.Range(3, 1000, 3, 1000),
		new vscode.Range(4, 1000, 4, 1000),
		new vscode.Range(5, 1000, 5, 1000),
		new vscode.Range(6, 1000, 6, 1000),
		new vscode.Range(7, 1000, 7, 1000),
		new vscode.Range(8, 1000, 8, 1000),
		new vscode.Range(9, 1000, 9, 1000),
	]);
}
```

Have an empty line at the beginning of the file. The cursor and the indent guides should render precisely between the before and the after decoration:

![image](https://user-images.githubusercontent.com/5047891/72653196-0f1c3b80-398a-11ea-86ca-8c712adb2626.png)
