### ISSUE TITLE
The New Auto Import feature importing modules from wrong path sometimes 

### ISSUE THREAD

**Issue by Manzurkds** [Microsoft/vscode#40124]
- VSCode Version: 1.18.1
- OS Version: macOS 10.13.1

I found this bug while working with Angular so the steps apply to that.
Steps to Reproduce:
1.Open vscode
2. autocomplete for Router (It imports router from '@angular/router/src/router' but it should import from '@angular/router' as importing from the former gives error)

This also occurs for some related packages and also some other time but I don't remember exactly, I'll keep updating this as and when I found

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I believe this is  https://github.com/Microsoft/TypeScript/issues/19888 

This should be fixed in `typescript@next`. You can try this out by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions
