### ISSUE TITLE
Getting Bad Pool Caller/Request BSOD while working with files in ClearCase on Windows

### ISSUE THREAD

**Issue by KronoSKoderS** [Microsoft/vscode#40128]
- VSCode Version: 1.18.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

1. Open Networked Clearcase Folder in VS Code
2. Right Click on folder
3. BSOD with the following information:

BAD_POOL_CALLER (STOP: 0x000000C2 (0x7, 0x2805E380, 0xFFFFFA802E5AA070))

**Comment by KronoSKoderS** [comment]
Disabling the extensions *appears* to initial solve the problem.  I'm going to slowly re-enable the extensions one by one and see if there are any specific to blame.

**Comment by KronoSKoderS** [comment]
Update: Had to uninstall all extensions and then start from there.  The first extension installed was Python and immediately ran into the issue.  Will confirm that it is just the Python extension and not others next.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
