### ISSUE TITLE
emmet work properly

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#40126]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: emmet

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5

(1 theme extensions excluded)

---

why doesn't emmet work properly?

**Comment by ramya-rao-a** [comment]
> why doesn't emmet work properly?

why dont users report issues with details and reproducible steps?

Read [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) and [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet), and then re-open this issue if you still have problems with emmet

**Comment by mittalyashu** [comment]
Can't you add all the feature of emmet in the VSCode itself?

**Comment by ramya-rao-a** [comment]
@mittalyashu What features of emmet do you not find in VS Code?

**Comment by mittalyashu** [comment]
Does VS Code work with all the features listed in the file?

[emmet-cheatsheet.pdf](https://github.com/Microsoft/vscode/files/1609889/emmet-cheatsheet.pdf)

**Comment by ramya-rao-a** [comment]
We have adopted [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) which are the newer set of emmet modules written by the same author who wrote the Emmet library that is used in most editors. 

See [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) to know more about it.

There are a few Emmet abbreviations that don't work in the new Emmet 2.0 As far as I know, they are:
- Abbreviations with `@-` used for getting numbers in descending order in repeaters. See 
- Abbreviations ending with `+` like `select+`, `ul+` etc.

Both of these are addressed in [Emmet Common Questions](https://code.visualstudio.com/docs/editor/emmet#_common-questions)

If you come across any other abbreviations that don't work as expected, feel free to bring it to our attention.
