### ISSUE TITLE
terminal fontSize should default to editor fontSize

### ISSUE THREAD

**Issue by mikelward** [Microsoft/vscode#40131]
- VSCode Version: 1.18.1
- OS Version: Debian Linux

Steps to Reproduce:

1. Change editor.fontFamily and editor.fontSize
2. Open integrated terminal (Ctrl+`)

Expected:

Integrated terminal uses same font family and size.

Actual:

It uses the same font family, but the size is smaller.

Since terminal.integrated.fontFamily defaults to editor.fontFamily, I think it would make sense for terminal.integrated.fontSize to default to editor.fontSize.

**Comment by shobhitchittora** [comment]
This relates to #37455, where we fixed a maximum value for integrated terminal fontSize. 
This might help - 
https://github.com/Microsoft/vscode/blob/430d61688aafa594ea17feeef78a02f6d622be3a/src/vs/workbench/parts/terminal/test/electron-browser/terminalConfigHelper.test.ts#L90 

Need triage from @Tyriar. Also should I extend the `terminalConfigHelper.test.ts` for our previous PR (#37636)

**Comment by Tyriar** [comment]
It used to be like you suggest but I ended up changing it because none of the other panels scale based on the editor's font size. See https://github.com/Microsoft/vscode/issues/16446
