### ISSUE TITLE
Problems with the launch.json system

### ISSUE THREAD

**Issue by carlca** [Microsoft/vscode#40137]
VSCode (stable) 1.18.1
VSCode (Insiders) 1.19.0
macOS 10.13.2 High Sierra

Reposted from https://github.com/Microsoft/vscode-go/issues

Hello, again, I don't know whether this problem is peculiar to VSCode-go but I'm having problems understanding and getting my launch.json mechanism under control.

![screen shot 2017-12-12 at 20 44 36](https://user-images.githubusercontent.com/260612/33913539-2631c154-df92-11e7-9623-c85462a74930.png)

In the attached screenshot we can see the dropdown with just one launch.json available to run, namely gotwitter. Yet, the launch.json that I want to run, the one being edited, is not available for running or is it in the list of ones to be added. That launch.json is in a separate folder called sqlservertest and is entirely separate from the sqlserver folder. How do I get it to be associated with the sqlservertest.go file and run when selected from the Debug dropdown?

**Comment by carlca** [comment]
In the replies to Microsoft/vscode-cpptools#396 it says how there is supposed to be a "Configure or Fix launch.json button in the Debug pane". Where is this button. I cannot find it?

**Comment by carlca** [comment]
In my case, I deleted the existing `gotwitter` config. Whereupon, the `Configure or Fix launch.json button in the Debug pane` came back. The problem is that regardless of which file is being currently edited, pressing the `Configure or Fix` button merely adds the `launch.json` for the first item in the drop-down list, in my case, `Alfred`. Sorry to say it, folks, unless I am missing something very obvious, this mechanism appears to be broken, and as such, completely unusable.

**Comment by carlca** [comment]
I have a `.go` file called `sqlservertest.go`. It lives in a folder called `sqlservertest` (`sqlserver` in the drop-down list is a separate folder). The `sqlservertest` folder has a sub-folder called `.vscode` which contains a file called `launch.json`. In that `launch.json` file I have the following lines:

```
{
  //
  // go run sqlservertest.go -debug=true -user=sa -password=<MyPassword> -server=192.168.99.100
  //
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch - sqlservertest",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "remotePath": "",
      "port": 2345,
      "host": "localhost",
      "program": "${fileDirname}",
      "env": {},
      "args": [
        "-debug=true",
        "-user=sa",
        "-password=<myPassword>",
        "-server=192.168.99.100"
      ],
      "showLog": true
    }
  ]
}

```

All I want to do is to debug the `.go` file with the above config. How do I do this? It should be this difficult surely...

**Comment by ramya-rao-a** [comment]
@carlca Let's continue this discussion in the issue you logged in the vscode-go repo (https://github.com/Microsoft/vscode-go/issues/1403)

Am closing this issue. If we determine there that this is indeed a VS Code problem, then we can re-open it
