### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by arielylin** [Microsoft/vscode#40136]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-console-wrapper|fab|0.4.0
sublime-keybindings|ms-|3.0.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please read [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) and provide details along with reprodcible steps when logging an issue.
