### ISSUE TITLE
HTML: add `data-` attribute autocomplete

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40149]
```html
<div da|></div>
```
1. Trigger autocomplete at `|`
2. No `data-` attribute item

**Comment by aeschli** [comment]
Could offer `data-` and all other `data-` attributes used somewhere else in the document.

**Comment by pfongkye** [comment]
Hello @aeschli ,
I could take a look at this issue. Any hint/code pointer will be appreciated.

**Comment by aeschli** [comment]
@pfongkye, cool. The code (and the PR) would go here: https://github.com/Microsoft/vscode-html-languageservice/blob/65ef21648eaa199b948309f4580d8e79412ffb4f/src/services/htmlCompletion.ts#L149
The easiest is to just work with the tests
https://github.com/Microsoft/vscode-html-languageservice/blob/65ef21648eaa199b948309f4580d8e79412ffb4f/src/test/completion.test.ts#L93

**Comment by pfongkye** [comment]
@aeschli 
Can you tell me if I'm on the right track? https://github.com/pfongkye/vscode-html-languageservice/blob/df0c3b3fba06bb9baa51c999ac83daa86920b155/src/services/htmlCompletion.ts#L179
The code works for root nodes only atm. I still need to figure out how to add the data- attributes from children.
I've added two test cases: 
https://github.com/pfongkye/vscode-html-languageservice/blob/df0c3b3fba06bb9baa51c999ac83daa86920b155/src/test/completion.test.ts#L374
Let me know what you think.
Thanks in advance.

**Comment by pfongkye** [comment]
Using regexp instead to capture the data attributes in document:
https://github.com/pfongkye/vscode-html-languageservice/blob/86854ba509e8505298457e207df5dbe2c7d4b9eb/src/services/htmlCompletion.ts#L179

And added another test:
https://github.com/pfongkye/vscode-html-languageservice/blob/86854ba509e8505298457e207df5dbe2c7d4b9eb/src/test/completion.test.ts#L385

**Comment by aeschli** [comment]
@pfongkye You are on the right track. To find the other 'data' attributes, you should use the first approach and use the HTMLDocument to find the attributes. Using the regex will fail if `data-` appears in comment, values and element contents.

Please make a pull request, then I can comment directly in the code.
Some stuff that I saw:
- create a separate function/method for your code
- when comparing the proposals, make sure the attribute name starts with `data-` (not just _contains), and filter duplicate occurrences 
-  I don't think adding the suggest command does anything in your scenario. The suggest command will retrigger code assist after inserting the proposal. That's only useful if we have proposals there.

**Comment by pfongkye** [comment]
@aeschli thanks for your feedback. I'll make a PR ASAP.

**Comment by usernamehw** [comment]
@pfongkye very good. Is it not too late to make a few modifications?
1. When you autocomplete existing attribute cursor gets after quotes, not inside them:
```html
<div data-id=""|></div> <!-- now -->
<div data-id="|"></div> <!-- desired -->
```

2. Is it possible to include quotes and equal sign with `data-` attribute:
```html
<div data-|="|"> <!-- 2 tabstops -->
```

**Comment by pfongkye** [comment]
hey @usernamehw 
I could take a look at first case.
For the second one, better if we can get some feedback from @aeschli

**Comment by usernamehw** [comment]
@pfongkye  Maybe simply using `$0` `$1` would work?
