### ISSUE TITLE
Emmet not working with TAB

### ISSUE THREAD

**Issue by prasanthnv** [Microsoft/vscode#40143]
**Emmet** abbreviation not working while clicking tab... it's working with ctrl + space

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-98-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
ng-template|Ang|0.1.7
material-icon-theme|PKi|3.1.0
quokka-vscode|Wal|1.0.84
vscode-intelephense-client|bme|0.8.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
vscode-todo-plus|fab|1.7.1
auto-rename-tag|for|0.0.15
icon-fonts|idl|1.10.1
code-beautifier|mic|1.7.2
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|3.5.0
vscode-todo-highlight|way|0.5.11

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please read [Emmet with VS Code](https://code.visualstudio.com/docs/editor/emmet) and re-open this issue if you still cannot use emmet with tab after setting `"emmet.triggerExpansionOnTab": true`
