### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Andy-007** [Microsoft/vscode#40144]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|1.4.1
beautify|Hoo|1.1.1
swift|Kas|0.0.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
cpptools|ms-|0.14.4
vetur|oct|0.11.3
vscode-icons|rob|7.19.0
react-beautify|tai|0.3.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@Andy-007 What error did you encounter?
