### ISSUE TITLE
Delete on subst drive doesn't work anymore

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4014]
Windows

* subst a drive
* select a file, execute delete
* Confirm OK
* Message appears that the file can't be moved to trash. Select 'Delete Permanently'

Observe:
* file quickly disappears in the explorer and then reappears

**Comment by bpasero** [comment]
@dbaeumer good catch, I put in a typo while fixing another thing you reported to no longer ask for confirmation. So now the experience should be: Delete, Move to trash, fails, delete permanently => gone
