### ISSUE TITLE
Load iconv-lite module async

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#40147]
It looks like we are loading some NPM modules directly on startup that we could load async via this style: `(import('module')).then(module => ...)`. Running `code -p` I see the time it takes to load such modules on startup (printed after the name):

* [`fast-plist`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/colorThemeData.ts#L17) 6ms @aeschli 
* [`gc-signals`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadHeapService.ts#L10) 10ms @jrieken  

I filed a separate issue for `xterm` (that takes the longest to load) where we do load it async but it seems to load sync: https://github.com/Microsoft/vscode/issues/40146

**Comment by jrieken** [comment]
I'd also add `"iconv-lite"` to this list and `"vscode-textmate"`

**Comment by jrieken** [comment]
btw, timing are crazy different between runs:

<img width="469" alt="screen shot 2017-12-13 at 09 37 53" src="https://user-images.githubusercontent.com/1794099/33929312-5192cda0-dfe9-11e7-8eb3-2505c2a184c1.png">

**Comment by joaomoreno** [comment]
I argue to let `spdlog` untouched. It always needs to be loaded right in the beginning, since logging is necessary as early as possible. Making it async is just an exercise in promisifying the startup code of all processes.
