### ISSUE TITLE
Support link with line numbers in the markdown editor

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#40140]
From #38577

**Steps to Reproduce:**

1. In project:

`a.md`:
```md
[b](./b.md#3)
```

`b.md`:
```md
1
2
3
4
5
```

2. Click on link `./b#md3` in the markdown editor

**Expected**
Opens `b.md` with line 3 at top

**Comment by mjbvz** [comment]
For verification, this should also work for paths such as:

```
[b](b.md#L3)
[b](/b.md#L3)
```

As well as working in the markdown preview

**Comment by bpasero** [comment]
Seems to work fine, though I would probably expect the cursor to move as well, not just the viewport.
