### ISSUE TITLE
Add variable to insert value from clipboard to a snippet

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode#40153]
It would be great if we had some snippet variable among others (e.g. `TM_CLIPBOARD`), which, when used, would be replaced with current clipboard content.

I'm coming from Sublime Text where I've been using custom macros to simplify logging (e.g. copy value to clipboard -> go to new line and press `ctrl+alt+e` -> `console.log('${VALUE}', ${VALUE})` appears. With Code's custom snippets I could reproduce this behavior almost fully except for clipboard functionality.

**Comment by jrieken** [comment]
@evenfrost In sublime is `${VALUE}` for the clipboard or also other smarts?

**Comment by evenfrost** [comment]
`${VALUE}` is just a random name here to show how I accomplish this, not a defined placeholder. E.g., if I copy to clipboard `foo`, press `ctrl+alt+e` (my custom hotkey), then `console.log('foo', foo);` appears. Again, I'm using this in Sublime via macros, and in Code it could be done with snippets out of box, it's just `TM_CLIPBOARD` variable that is missing.

**Comment by jrieken** [comment]
Yeah, I like... TextMate recommend embedded shell code, e.g. `<a href="`pbpaste`.html">$TM_SELECTED_TEXT</a>` but that's still a long way from supported in VS Code. I'll give it a shot

**Comment by jrieken** [comment]
I have pushed a first version of this to master. I have named the variable just `CLIPBOARD` because those prefixed with `TM_` are TextMate compatible.

This isn't multi-cursor aware (and I am unsure if it should be). In the editor, when you have `n`-cursors and your clipboard is `n`-lines, paste inserts just one line per cursor, not `n`. This is a little more tricky...

**Comment by jrieken** [comment]
Pushed another change just picks for each selection/cursor/snippet the corresponding line when there are `n`-snippets and `n`-lines in the clipboard. 

![dec-13-2017 16-33-59](https://user-images.githubusercontent.com/1794099/33947076-c6699a34-e023-11e7-883b-022f6cb4da9c.gif)

**Comment by evenfrost** [comment]
Awesome, thank you!
