### ISSUE TITLE
Extension market not popping out, can't install extensions

### ISSUE THREAD

**Issue by DimitriCuzor** [Microsoft/vscode#40159]
- VSCode Version: Code - OSS 1.10.2 (376986b10a9221f40b0971d4b4e0746071de9fdb, 2017-05-23T23:59:12.689Z)
- OS Version: Linux x64 4.13.0-17-generic
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@DimitriCuzor We cant understand much from just the title of this issue. Please add details with reproducible steps.

For future reference, also read [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)

**Comment by weinand** [comment]
Please use a recent version of VS Code. The latest is 1.19.0. You are 9 releases behind.
