### ISSUE TITLE
asking to remove alias from .bash_profile

### ISSUE THREAD

**Issue by winnemucca** [Microsoft/vscode#4015]
Why would this be asking me to remove function code from my bash profile for the update?  Is this correct?  

````
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

//Code needs to change the 'code' shell command. Would you like to do this now?
//Please remove the 'code' alias from '/Users/steven/.bash_profile' before continuing.

````

**Comment by joaomoreno** [comment]
Yes. The new update brings in a new way of launching Code from the command line. Following the instructions will let you update to that. I recommend doing it.

**Comment by mmgreiner** [comment]
I did comment the function code () ... , but I'm still getting this question every time?

**Comment by joaomoreno** [comment]
With #4169 we started detecting that you may have commented it out and wouldn't pester you about it, but that will only come next release, unfortunately.

You'll have to remove the line for now.

**Comment by qapi** [comment]
When this message appears there is ```cancel``` button. Shouldn't my choice be persisted in case I want to continue as it is? It is little bit annoying having to press ```cancel``` button every time editor launches. I have my own command that I called ```vcode``` not ```code``` but I still get this message and on next step there is a message ```Please remove the alias referencing 'com.microsoft.VSCode' in...``` Thanks for the good work!

**Comment by joaomoreno** [comment]
You definitely want to remove the alias referencing `com.microsoft.VSCode` as it will eventually break. Why do you want to keep it?

**Comment by qapi** [comment]
Well default ```code``` command doesn't work well for me. For example if editor is already open and close it and I run command to open new one with path to specific folder, path would be ignored and command would reopen project I was working on before. Only if I quit editor completely command would open project I want to open. Which is kinda annoying if you need to switch between different projects often.  So I have this command:

```vcode () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}```

which I sticked to ```.bash_profile``` and in works as expected. But then editor complains about using ```com.microsoft.VSCode```

**Comment by joaomoreno** [comment]
That is odd. The behaviour you describe should work. That is:

1. Have Code open in a folder.
2. Quit Code.
3. Type `code another_folder` to open another folder

Code should open with `another_folder` open, not the original folder.

Are you sure you don't get this behaviour using the _official_ `code` launcher?

**Comment by qapi** [comment]
Yes, step 2 is the problem.

So here is an example. Let's say I want to have two different folders open at same time so I can compare something:
1. Run ```code folder_1``` - Code editor will open on ```folder_1``` ✅
2. Without closing editor run ```code folder_2``` - Code editor will not open on ```folder_2``` instead it will focus on editor with ```folder_1``` ❌

Here is another example:
1. Run ```code folder_1``` - Code editor will open on ```folder_1``` ✅
2. Close editor but do not quit application ✅
2. Run ```code folder_2``` - Code editor will not open on ```folder_2``` instead it will open editor with ```folder_1``` ❌

**Comment by joaomoreno** [comment]
Both those examples work for me.

Are you absolutely sure you are using the launcher that you install via the Command Palette? Make sure you install it, totally comment out the alias, and restart the Terminal before retrying.

**Comment by qapi** [comment]
Ok so here is update. I tested provided official command on two different MacBooks and it doesn't work. Both have encrypted hard drive if that makes any difference? I remember I had similar problem with Atom editor command when I encrypted my hard drive. I know it sounds weird. 🙄

**Comment by joaomoreno** [comment]
That is definitely weird. Let's just create an issue for it: #9524

**Comment by qapi** [comment]
Thanks
