### ISSUE TITLE
diff view doesn't not retain its scroll position across switching tabs

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#40151]
1. open a diff view
2. scroll down
3. switch to a different tab
4. get back to the diff tab
5. observe diff view scrolled all the way to the top

**Comment by jbsulli** [comment]
It scrolls so that the caret is in view no matter where I was last scrolled to.

**Comment by dwarburt** [comment]
duplicate of #10663 I think, in case anyone else has trouble finding it like I did.
