### ISSUE TITLE
TypeScript implemented interface syntax highlighting inconsistent for multiple interfaces

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#40161]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.13.10-1-ARCH

---

Steps to Reproduce:

1. Create class that implements more than one interface
2. Check highlighting (last one should be colored differently) ![image](https://user-images.githubusercontent.com/834235/33936797-13196530-e001-11e7-9265-e06e61b62276.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/551 to track this upstream
