### ISSUE TITLE
The output type list can't work correctly when toggling the OUTPUT window after installing some extensions.

### ISSUE THREAD

**Issue by anthlu** [Microsoft/vscode#40167]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.8.0
cpptools|ms-|0.14.4
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
clang-format|xav|1.6.1

---
![snipaste_20171213_213444](https://user-images.githubusercontent.com/16623398/33944545-7999c7ae-e057-11e7-889e-9dfce4f2f7e0.png)

Steps to Reproduce:

1. After updating the C/C++ extension (ms-vscode.cpptools) and reloading the vscode window to enable, it will automatically download and install some dependent packages.
2. Toggle the OUTPUT window to review the status, click the output type list to choose the "C/C++", but the list can't show anything (marked in the image). Click again, it works correctly.

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
This occurs on and off in the dropdown menu for the debug configuration in the debug panel as well.
@bpasero might be related to electron
Occurs only in Windows

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/25700
