### ISSUE TITLE
massive leakage with search viewlet

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#4016]
* Set up a workspace as outlined here: Microsoft/TypeScript#7444
* show search viewlet, search for `bab` once, wait for results, clear results
* take a heap snapshot
* search again for `bab`, when done press *refresh*, repeat 5 time
* clear results
* take another snapshot, heap grew by ~30MB

**Comment by jrieken** [comment]
It's the file matches that leak cos they are referenced by the remove action which seems to be referenced via the action bar...

[Archive 2.zip](https://github.com/Microsoft/vscode/files/169422/Archive.2.zip)

**Comment by jrieken** [comment]
Problem seems to be that `ActionRunner@11221` get more and more listeners registered with ever unregistering...

**Comment by bpasero** [comment]
Looked into this with Joao and it turns out that every call to Tree.setInput() would not clean up templates for rows created from the previous run. Specifically the cleanupFn is not being called which actually is the one to dispose the action bar used on each row.
