### ISSUE TITLE
Updater icon invisible on Windows

### ISSUE THREAD

**Issue by mxschmitt** [Microsoft/vscode#40163]
- VSCode Version: Code - Insiders 1.19.0-insider (951f5a20fc820e32a65ca05bb87af86f65027470, 2017-12-12T21:32:54.471Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.2.0
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
gitlens|eam|6.4.0
tslint|eg2|1.0.24
markdown-table-formatter|jos|0.2.3
Lua|key|0.0.9
Go|luk|0.6.69
debugger-for-chrome|msj|3.5.0
tmlanguage|Tog|0.8.4
vscode-import-cost|wix|2.5.1

---

Steps to Reproduce:

1. Wait that an update is released
2. Update via the integrated updater

Looks like that:
![image](https://user-images.githubusercontent.com/17984549/33939611-1e2b7b1a-e00c-11e7-9731-f82de642a8a7.png)

**Comment by warpdesign** [comment]
I noticed this issue too. This happens during the first phase of the setup process: `preparing...`. Once it goes to the `installing` phase the icon appears.

Note that this first phase can take 10-15 seconds on my computer, and during this phase, clicking on the empty icon in the taskbar does nothing: it doesn't bring the setup window to front, as expected.

**Comment by maxibanki** [comment]
Yeah, for today's insider release, I've been watching that. It is only invisible for the "Prepare update" part. The icon then appears for the rest of the process.

**Comment by joaomoreno** [comment]
This no longer happens with Windows background updates.
