### ISSUE TITLE
so long progress

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#40165]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/5047891/33939881-1dc425ae-e00d-11e7-875d-cc4a20d96bd4.png">

https://github.com/Microsoft/vscode/blame/5761b7320b7d898dc57e346bef4a5eb89e977265/src/vs/workbench/services/progress/browser/progressService2.ts#L173

**Comment by joaomoreno** [comment]
Ehehe so long! https://github.com/Microsoft/vscode/commit/c1cf8ef371b9ec9fadc3c1b4978d563aeee35538
