### ISSUE TITLE
Folder/File Hierarchy Screwed up in Explorer Pane

### ISSUE THREAD

**Issue by Tetheta** [Microsoft/vscode#40173]
- VSCode Version: Code - Insiders 1.19.0-insider (3656454687c62594949b71651c8fa70065d16494, 2017-12-07T05:15:37.456Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|0.23.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
gitlens|eam|6.3.0
vsc-material-theme|Equ|1.1.2
prettier-vscode|esb|0.26.0
node-debug2|ms-|1.19.0
debugger-for-chrome|msj|3.5.0
indent-rainbow|ode|0.7.2
material-icon-theme|PKi|3.1.0
vim|vsc|0.10.5
vscode-react-native|vsm|0.5.7
vscode-import-cost|wix|2.5.1
html-css-class-completion|Zig|1.14.0

---

![vscodeissue](https://user-images.githubusercontent.com/3209941/33955042-16622824-dfef-11e7-9658-62a4515171bb.png)

As you can see here, it thinks that date is at the same level as the componentDemos folder, despite it (and the corresponding index, text, number, etc files) being inside of it.
It repeatedly glitched around, at one point showing check.js as being the folder's name with things inside it (obviously impossible) and then showing it as a child of the test folder above which isn't even in the same tree. I had to restart and things have been working fine since then. Just figured I should log it. I'll update if it happens again.

Steps to Reproduce:

1. Work normally in the latest visual studio Insiders
2. ??? I'm afraid I haven't been able to reproduce it yet. I was creating new files and had to move a few over a folder. So I'm guessing that's what did it.

Reproduces without extensions: No since I haven't been able to reproduce.

**Comment by isidorn** [comment]
Please try to reproduce without extensions. Otherwise I would have to blame this on the extensions. Also if it was something in the core others users would also complain as this is some basic rendering being screwed up.

**Comment by Tetheta** [comment]
I've tried to reproduce even with extensions and I can't, so I'll close this for now. No idea why it screwed up like that, if it happens again I'll try and see if I can get a better cause.
