### ISSUE TITLE
Opening VS Code from Bash on Ubuntu on Windows hangs terminal until window is closed

### ISSUE THREAD

**Issue by pd93** [microsoft/vscode#40174]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Ensure that the VS Code bin directory is in your Windows path and all VS Code windows are closed
2. Enable/Install Bash on Ubuntu on Windows
3. Open the Ubuntu app
4. Navigate to a windows directory. eg. `cd /mnt/c/Users/<user>`
5. Run `code .`

Expected result: VS Code will open in a new window and the script will exit successfully allowing another command to be input immediately. This is what happens when running the same command from cmd or Git Bash

Actual result: VS Code opens in a new window, but the script hangs until the user closes the VS Code window or exits the script manually (`CTRL+C`)

*Note*: It actually works as expected if another VS Code window is already open.

I've worked around the issue for now by prefixing the `timeout` command in an alias.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#13138

**Comment by pd93** [comment]
@joaomoreno This is not the same issue as #13138. That issue refers to opening an instance of the *Linux* version of VS Code via Xming. This issue refers to opening the *Windows* version of VS Code *via* the WSL.

**Comment by joaomoreno** [comment]
Oh I see, my bad!

**Comment by scottned** [comment]
When you start, it is running in the foreground.  You can "ctrl-z" and then "bg" to run it in the background and regain your terminal.   You could also run "code . &", which works but I get a "nice" warning.  Not sure what's causing that.

**Comment by lucasreppewelander** [comment]
Don't really know if this is even within the same issue, but on another bash/unix cmd when I write `code .`, eg. on my mac, VSCode opens up that folder too, when I do this within the WSL it opens up the `System32` folder, is this meant or is there a workaround for this? I  tried to search but couldnt find anything that refers to the `dot` functionality like thie issue.

**Comment by pd93** [comment]
@ellismarkf Sorry for the slow reply. The command I was using looked like this:
`timeout 1 code .`

However, since December, VSCode has started producing output (see sample below). This seems to output, even after the timeout command has completed. 

`Code.exe` output:
```
[main 10:14:37] update#setState checking for updates
[main 10:14:40] update#setState idle
```

Previously reported behaviour is still happening

**Comment by Tyriar** [comment]
This works now when you have installed the Remote-WSL extension
