### ISSUE TITLE
Feature Request: Quick Fix All

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/vscode#40170]
Now that [this issue](https://github.com/Microsoft/TypeScript/issues/14549) is supported in Typescript, can we enable Quick Fix All in VSCode?

It was originally tracked with [this issue](https://github.com/Microsoft/vscode/issues/22220) until it was closed as external.

We'd like to have Quick Fix All for the powershell extension and I believe there's some work in VSCode itself to enable it. Please correct me if I'm wrong.

Thanks!

**Comment by tylerl0706** [comment]
@mjbvz what version of vscode is this in? I'm on insiders and I'm not seeing Quick Fix All.

**Comment by mjbvz** [comment]
Current master or install typescript@next on d21e6a3e388897a2250cb10ae897b6481e0bd61d

**Comment by tylerl0706** [comment]
Got it, when does that usually flow down to insiders?

**Comment by tylerl0706** [comment]
@mjbvz @octref how can I enable this feature for languages other than JS and TS? Example: PowerShell.

**Comment by tylerl0706** [comment]
Gently ping

**Comment by mjbvz** [comment]
@tylerl0706 Each extension/language can implement quick fix all using the existing `CodeActionProvider` API. We did not add a new API for quick fix all
