### ISSUE TITLE
changing collapsibleState to expanded does not expand node

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#40179]
Steps:

- for a `TreeItem with collapsibleState !== TreeItemCollapsibleState.Expanded` set the collapsibleState to `TreeItemCollapsibleState.Expanded` and fire a `onDidChangeTreeData` event.

Observe: the tree item starts to show a expand triangle but the node does not actually expand.

**Comment by sandy081** [comment]
Duplicate of #30918
