### ISSUE TITLE
Ability to show tooltips for overflowed inputBox prompts

### ISSUE THREAD

**Issue by davidkpiano** [Microsoft/vscode#40177]
For prompts that overflow, it would be helpful to either:
- show the full prompt as a tooltip
- have the ability to specify a `tooltip:` parameter in `showInputBox(options)`.

Details:
- VSCode Version: 1.19.0-insider (latest at time of writing)
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Open up an input box from the command palette that has a clipped prompt (with ellipses shown)
2. Hover over the prompt

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Lets merge into https://github.com/Microsoft/vscode/issues/33181
