### ISSUE TITLE
Files missing in tree but not explorer

### ISSUE THREAD

**Issue by jackmusick** [Microsoft/vscode#40178]
- VSCode Version: 1.18.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. `npm install`
2. Go to `node_modules\.bin` within VS Code, files are missing.
3. Open in Explorer, files aren't missing.

---

When using VS Code in Windows, my `node_modules/.bin` folder is empty. If I check it in Explorer, it's not. I'm getting the following error from the debugger as a result:

`Attribute 'program' does not exist ('c:\Users\jack\GitHub\vrp-guestbook-serverless/node_modules/.bin/sls').`

Here is the portion of my launch.json file referencing that, which works on my Mac.

```
{
            "name": "run GetAgent By Property",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/.bin/sls",
            "args": [
                "invoke",
                "local",
                "-f",
                "Agent",
                "--path",
                "events/agent/get-by-property.json"
            ],
            "skipFiles": [
                "${workspaceRoot}/node_modules/**",
                "${workspaceRoot}/lib/**"
            ]
        }
```
If I change the program to the direct location under `node_modules/serverless/bin/serverless`, it works just fine.

**Comment by isidorn** [comment]
It seems lik you have vscode misconfigured. Please check out your settings, especaily the "files.exclude"

The debugger error is unrelated.
