### ISSUE TITLE
VSCode Terminal Has No Prompt

### ISSUE THREAD

**Issue by mtpultz** [Microsoft/vscode#40175]
- VSCode Version: 1.8.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. None it just isn't working this morning

Reproduces without extensions: Yes

I tried disabling all extensions, shutting down and restarting, and uninstalling/reinstalling VSCode, but regardless the `Terminal` tab contains no prompt just a solid cursor.  There are also no logs in the console of the `Developer Tools` indicating an issue.

![image](https://user-images.githubusercontent.com/599498/33957430-d13829aa-dffe-11e7-8f05-70a6c46d34d4.png)

**Comment by ramya-rao-a** [comment]
Can you share your terminal related settings?
Do you see the same issue for every new terminal you create (say by using the plus sign in your screenshot)?

**Comment by mtpultz** [comment]
Hi @ramya-rao-a, sure can they are included below.  I also tried unsetting them by commenting them out and the issue is still evident.

```
// External Terminal
"terminal.external.windowsExec": "D:\\Installs\\ConEmu\\conEmu64.exe",
// Integrated Terminal
"terminal.integrated.shell.windows": "D:\\Installs\\Git\\bin\\bash.exe",
```

**Comment by Tyriar** [comment]
Does changing it to cmd work via this command?

![image](https://user-images.githubusercontent.com/2193314/34007801-ec5bc69c-e0b7-11e7-9fc7-b01da29ea8ca.png)

I suspect bash.exe is crashing for some reason and unfortunately atm on Windows the terminal will just hang like that.

**Comment by mtpultz** [comment]
Hi @Tyriar, I tried selecting the default shell `cmd` and `power shell`, but I get the same output for both.  I also just commented out my settings previously to allow for the default.

![image](https://user-images.githubusercontent.com/599498/34012567-872bf14c-e0d1-11e7-96bd-8ec4deeadf37.png)

**Comment by Tyriar** [comment]
@mtpultz hmm, do you have any errors in your devtools console? (Help > Toggle Developer Tools)

**Comment by mtpultz** [comment]
@Tyriar I don't have any errors in the developer tools console.

![image](https://user-images.githubusercontent.com/599498/34027734-d72576c4-e11b-11e7-9771-f75730164704.png)

**Comment by Tyriar** [comment]
@mtpultz do you have any anti-virus software that could be intercepting the process creation? I've had reports before that some of them do things like this due to the use of winpty https://github.com/rprichard/winpty

**Comment by mtpultz** [comment]
@Tyriar just Windows Defender, which doesn't appear to use that plugin, and it's been used with VSCode for the last year or more without any issues.

**Comment by Tyriar** [comment]
You're not giving me much to go on 😄 I can't seem to reproduce.

Could you try set up the demo for https://github.com/xtermjs/xterm.js and see if the problem occurs there as well? If you have node setup it should be pretty easy to get running:

```
git clone https://github.com/xtermjs/xterm.js
cd xterm.js
npm i
npm run dev
```

**Comment by mtpultz** [comment]
Yah @Tyriar there's isn't much to go on it was working on my desktop the night before and wasn't working the next morning.  I can't reproduce it on my laptop which is set up exactly the same as my desktop except my desktop is Windows 10 Pro instead of Windows 10.  As I mentioned above I also tried uninstalling and reinstalling VSCode thinking that would at least reset the issue and nothing changed.

I set up a basic project that pulls in `xterm` and just uses the example code provided in `Getting Started` with an interval and it works in Chrome.  Is there anything specific you want me to try?

```
<script>
      var term = new Terminal();
      term.open(document.getElementById('terminal'));
      term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ');

      setInterval(function () {
        term.writeln('Test');
      }, 2000);
</script>
```

![image](https://user-images.githubusercontent.com/599498/34146661-221d2214-e458-11e7-8df0-9e1974e61d6d.png)

**Comment by mtpultz** [comment]
@Tyriar Uninstalled VSCode deleted ~/.vscode/extensions and deleted C:\Users\mtpul\AppData\Roaming\Code and reinstalled VSCode v1.19.1 in an attempt to have a clean install with no residual settings etc and the terminal still doesn't work.

Is there a way to absolutely reset everything?  I wouldn't have thought using Electron there would be much in the way of residual files outside of what I've already deleted above, and I can't see the update to Windows 10 Pro from Windows 10 being the cause, but it's the only update that has occurred on this computer in the last month.

**Comment by Tyriar** [comment]
If you got rid of the roaming data and extensions and uninstalled you removed everything AFAIK.

**Comment by mtpultz** [comment]
Thanks @Tyriar not sure how to proceed from here.  I even tried to see if maybe it was somehow zoomed out really far but after trying some basic commands nothing was run after checking the external terminal.

**Comment by Tyriar** [comment]
Nothing's coming to mind here. It's difficult to investigate unless I can reproduce it unfortunately.
