### ISSUE TITLE
fix awkward `null` requirement for refreshing the root of a tree.

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#40185]
The documentation for `onDidChangeTreeData`says:
> An optional event to signal that an element or root has changed. To signal that root has changed, do not pass any argument or pass `undefined` or `null`.

I don't understand this strange requirement.

I do understand that a `null` passed to `getChildren.TreeDataProvider` indicates to return (or create) the root element. However, after this root element has been created, it is no longer `null`.

Every tree model has a root element. This is never `null`.
Why do I have to convert my model's root element into `null` in order to refresh it?

This requirement results in the following awkward code: 
```
const changed = calculateRootOfChanges(...);
if (changed === this._root.getId()) {
    changed = undefined;
}
this._onDidChangeTreeData.fire(changed);
```

This feels wrong and is error prone, because if the real non-null root is used to refresh the root, it has no effect (and does not even throw an error).

I suggest to eliminate this requirement and allow that the non-null root element can be used as well (in addition to the `null`). 

/cc @jrieken your opinion?

**Comment by alexr00** [comment]
Tested fireing `onDidChangeTreeData` with the actual root, and that does work to refresh the tree.
