### ISSUE TITLE
Very slow resizing when lots of content is in output panel

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#40187]
Steps to Reproduce:

1. Set `"typescript.tsserver.trace": "verbose",`
2. Work in vscode code base for a while in order to generate a lot of TS logs
3. Open output panel on bottom
4. Resize the sidebar to trigger a resize of the output panel

**bug**
Very bad resizing performance. Closing the output panel fixes this. Here is the log:
[Profile-20171213T161858.json.txt](https://github.com/Microsoft/vscode/files/1557549/Profile-20171213T161858.json.txt)

Main culprit seems to be `splitLinesCollection._constructLines`:

![screen shot 2017-12-13 at 4 22 28 pm](https://user-images.githubusercontent.com/12821956/33969389-d5a220a4-e021-11e7-827f-9de90604344e.png)

**Comment by alexandrudima** [comment]
When changing the width of a word-wrapped editor, the wrapping points have to be recomputed.
So, the entire buffer is walked over, character-by-character to recompute the wrapping points.
How large was the TypeScript log (number of lines, size on disk?)

**Comment by mjbvz** [comment]
~3MB at 50,000 lines or so. Some lines be very long however

For TS specifically, we usually only care about the most recent ~1000 lines. Any way to easily limit the buffer size

**Comment by isidorn** [comment]
@mjbvz this comes close to the output log viewer feature request we have been discusing in the standup

fyi @sandy081

**Comment by alexandrudima** [comment]
Duplicate of #21196
