### ISSUE TITLE
Intellisense when specifying object properties

### ISSUE THREAD

**Issue by Bibliofile** [Microsoft/vscode#40181]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Create a new `.ts` file with the following code (Copied from [Typescript/17352](https://github.com/Microsoft/TypeScript/pull/17352))
```ts
/**
 * @param {object} o - has a string and a number
 * @param {string} o.s - the string
 * @param {number} o.n - the number
 */
function f(o) { return o.s.length + o.n; }
```
2. Start typing to call the function

![image](https://user-images.githubusercontent.com/6462247/33965639-e57354ba-e019-11e7-9fc7-d76f031cf764.png)

I would expect the comment `the string` to show up when modifying the `s` property, however `- the number` is always shown. 

Using Typescript types does not fix this issue (and is my primary concern): 

```ts
/**
 * @param o - has a string and a number
 * @param o.s - the string
 * @param o.n - the number
 */
function f(o: {s: string; n: number }) { return o.s.length + o.n; }
```

Related: [Typescript/11597](https://github.com/Microsoft/TypeScript/issues/11597)

**Comment by mjbvz** [comment]
In your example under 2, I believe the key should be `s`, not `o`

**Comment by Bibliofile** [comment]
You are correct, however fixing that does not resolve my problem unfortunately. (Though at least I'm getting the comment for `o` now)

![image](https://user-images.githubusercontent.com/6462247/33969787-9c5dbd7a-e02c-11e7-94f6-6571a3a02347.png)

**Comment by mjbvz** [comment]
Do you still see this in the latest vscode insiders?

**Comment by Bibliofile** [comment]
Whatever has changed has improved this quite a lot! I now see `@param` with the comments when typing out the function call, which is very useful. 

However, it still isn't perfect. 

Using

```ts
/**
 * @param a first
 * @param b second
 */
function g(a: number, b: number) { return a * b; }
```

When typing, depending on what argument I am typing VSCode will show "first" or "second" as expected. However with the original code, I will always see the comment for `o` - never for `o.s` or `o.n`. 

Since they are available under the `@param` list below the first comment, this isn't a big deal, but it would be nice if the first comment changed as well.

**Comment by mjbvz** [comment]
Yes that sounds like https://github.com/Microsoft/TypeScript/issues/22350 

We'll keep investigating this on the TS side. Closing as upstream
