### ISSUE TITLE
Editor window hangs if network share disappears.

### ISSUE THREAD

**Issue by awiebe** [Microsoft/vscode#40188]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
crane|Hvy|0.3.8
php-formatter|Sop|0.2.4
dot|Ste|0.0.1
vscode-eclipse-keybindings|alp|0.9.6
jsrefactor|cms|2.2.1
prettier-vscode|esb|1.0.0
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
php-pack|fel|1.0.1
angular-bootstrap|her|4.0.9
ftp-simple|hum|0.5.8
vscode-ebnf|igo|1.0.3
php-symbols|lin|2.1.0
cpptools|ms-|0.14.3
debugger-for-chrome|msj|3.5.0
php-docblocker|nei|1.3.2
bootstrap4-vscode|the|3.0.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Open a directory on a samba share
2. Cause a disconnect on the share(e.g. disable wireless card)

Reproduces without extensions: Unknown, problem tends to happen overnight, will attempt, and attach comment.

**Comment by bpasero** [comment]
@awiebe what does it mean that it "hangs". Can you record a screencast of what happens?

**Comment by awiebe** [comment]
@bpasero By hang I mean freeze, specifically VSCode reports:
"This window has ceased responding"
[Close] [Reopen] [Keep Waiting]

I've run it for a while now without extensions and it appears it may have been caused by an extension, so I don't know if there's anything to be done about it- but you guys might care if an extension shouldn't be able to cause that.

Without extensions on it seems a notification appears, which does not happen with them off.
Unable to open 'filename.php': File not found (file:///Volumes/www/filename.php). [create file] [cancel]

I'll keep code running a few days and see if it freezes again.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
