### ISSUE TITLE
Test localized product

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4018]
**Assignees:**

- [x] Windows @alexandrudima, @egamma
- [x] OS X @waderyan 
- [x] Linux @aeschli 

**Items:**
Please note that minor parts of the product are still not translated. We have in total 136 untranslated strings. If a strings shows up in the user interface untranslated and you want to check if the strings is correctly externalized start in locale=pseudo and check if the string is enclosed in [ ] and has doubled vowels. 

* Start VSCode from the command line and pass the --locale argument. Test the following values and ensure that the UI is at least partly localized: de, es, fr, it, ja, ko, ru, zh-cn, zh-tw.
* Test that language reduction works. Start code with --locale=de-DE and ensure that you get a German user interface
* Test that VSCode picks up your OS setting. So switch the OS to one of the above locales and start VSCOde WITHOUT the locale parameter. Ensure that the user interface is rendered in the correct language.

**Comment by alexandrudima** [comment]
I did not test detecting the OS setting. Erich mentioned that it worked for him in the stand-up, as he got VS Code in German.

**Comment by waderyan** [comment]
@dbaeumer am I testing this correctly? 

I'm on OSX. I have the latest alpha version - `Version 0.10.12-alpha`

I have tried each of these commands, but have not seen any translations.

```
code-alpha --locale=de .
code-alpha --locale=psuedo .
code-alpha --locale=de-DE .
code-alpha --locale=es .
code-alpha --locale=zh-cn . 
```

Because `psuedo` doesn't work I can't determine what should be externalized. Here are the places I am looking. 

Search bar. 

![image](https://cloud.githubusercontent.com/assets/2449568/13756311/95663274-e9dc-11e5-91fb-1c4df2aa6a66.png)


Git.

![image](https://cloud.githubusercontent.com/assets/2449568/13756325/a64041f2-e9dc-11e5-963f-be237487ee1d.png)

File Menus.

**Comment by dbaeumer** [comment]
That should work and @weinand tested this. Not sure why this doesn't work for you. Can you check if you see files like this in your installation:

![capture](https://cloud.githubusercontent.com/assets/1931590/13757116/44e4df20-ea23-11e5-9263-3d6d6dac3bab.png)

Using the corresponding paths under Mac

**Comment by waderyan** [comment]
Looks like they are all there. Am I using the command line correctly? I'll check on some of the other Mac machines here. 

![image](https://cloud.githubusercontent.com/assets/2449568/13759792/0d528e44-e9ed-11e5-998f-bd0a8cd5ef98.png)

**Comment by weinand** [comment]
@waderyan make sure that VS Code is not running before you launch it from the command line. Otherwise the locale flag is ignored.
And make sure to spell "pseudo" correctly ;-)

**Comment by waderyan** [comment]
Ha. That was it (both the running app and the spelling problem). Works now.

**Comment by waderyan** [comment]
Found an issue with OS detection. logged [here](https://github.com/Microsoft/vscode/issues/4209)

**Comment by isidorn** [comment]
@waderyan are you done testing this item? If yes you forgot to check off the checkbox?

**Comment by waderyan** [comment]
@isidorn I have finished testing but there is still an outstanding issue #4120. From your question i'm assuming I should still mark testing as complete even with an outstanding issue.

**Comment by isidorn** [comment]
@waderyan yes, once we are done testing we check off the test item. The issues track the state of that, not this test plan item
