### ISSUE TITLE
Make VSCode available in the Windows Store

### ISSUE THREAD

**Issue by orobert91** [Microsoft/vscode#40195]
Is there a reason why is VS Code not in Microsoft's own app store? Can't this be done easily with the Desktop Bridge ("Centennial")? This would remove the need to manually update the app on every new version and offload that action to the OS. Also, Microsoft putting their on apps on the Store would make it more appealing for devs to move to the new app platform. I can't wait to ditch old Win32 installers.

**Comment by ramya-rao-a** [comment]
This is tracked in #10759
