### ISSUE TITLE
Test new tasks.json creation

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4019]
**Assignees:**

- [x] Windows @egamma 
- [x] OS X @chrisdias 
- [x] Linux @isidorn

**Items:**
The UI for creating a new tasks.json file got reworked. To test do the following:

- workspace without tasks.json file
- run Configure Task Runner action
- you should be presented with a picker like this:

![capture](https://cloud.githubusercontent.com/assets/1931590/13729547/a26ecae4-e937-11e5-84e4-debf5129a8a5.png)

- test all the different entries. And ensure that they generate a proper tasks.json file. Please not that for running a task the tools referred by the tasks.json file must be installed (e.g. gulp, jake, grunt, tsc, ...)
- if you have a gulpfile.js, jakefile or gruntfile ensure that the auto detection is run and that the tasks.json contains a detected build tasks. For the following gulpfile.js 
```JavaScript
var gulp = require('gulp');

gulp.task('build', function() {
    console.log('build'); 
});
```
the autodetection should detect the build task.
- also ensure that if a gulp, jake or grunt file exist and you select any other entry no auto detection is run and the proper tasks.json file is generated.

**Comment by felixfbecker** [comment]
there is a typo in the grunt description (it says jake file)

**Comment by dbaeumer** [comment]
@felixfbecker thanks. Fixed the typo.
