### ISSUE TITLE
Inconsistent formatting in integrated terminal (powershell formatting 'bleed-through')

### ISSUE THREAD

**Issue by confusingbits** [Microsoft/vscode#40190]
- VSCode Version: 1.18.1
- OS Version: Windows 10: 1709

I have been having this issue with the vscode integrated terminal for probably 6 months now. The terminal appears to become 'corrupted' while running scripts like webpack or jest running in the terminal. Powershell formatting settings appear to 'bleed through' and make the terminal unreadable. I have reinstalled VScode with no effect as well as reset powershell's formatting settings with 'Set-PSReadlineOption -ResetTokenColors` to no effect.

I am not using any terminal setting that I am aware of and using Dark+ (default dark), which I believe to be completely stock. (I've tried every setting that I can think of.) The problem will persist with other themes.

Here is what it looks like:

![bug](https://user-images.githubusercontent.com/6851336/33971414-ee5de8be-e03d-11e7-8e57-47022319fe4a.PNG)

I believe that I have identified a workaround by enabling 'legacy mode' in powershell, which can be done by opening a full powershell and choosing properties > options > 'Use legacy console (requires relaunch)'.

As demonstrated here:

![console fix](https://user-images.githubusercontent.com/6851336/33971500-6250b6d4-e03e-11e7-81a7-f5c6d48a7ffd.PNG)

This appears to resolve the immediate issue, however, if one attempts to use bash, you will now receive the error: 'Unsupported console settings. In order to use this feature the legacy console must be disabled.'

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@rprichard this seems to be a pretty common issue, have you seen this before?

**Comment by Tyriar** [comment]
Let's track this in https://github.com/Microsoft/vscode/issues/40327
