### ISSUE TITLE
The pop-up box displayed incorrectly

### ISSUE THREAD

**Issue by dotlnk** [Microsoft/vscode#40191]
When using google-style docstring (python), the pop-up tips does not wrap between items (summary, args, return ....).

**Comment by dragfire** [comment]
Could you please attach a screenshot?

**Comment by dotlnk** [comment]
![4](https://user-images.githubusercontent.com/3285467/34021209-8bbfdb54-e173-11e7-89e5-06e08d5f2a7e.png)
like this?Docstirng generated by the plugin --  "autodocstring". @NilsJPWerner
