### ISSUE TITLE
VSCode on Ubuntu 16.04 does not popup

### ISSUE THREAD

**Issue by ccic** [Microsoft/vscode#40192]
- VSCode Version: 1.18.1 929bacba01ef658b873545e26034d1a8067445e9
- OS Version: Ubuntu 16.04.3 LTS

Steps to Reproduce:

1. Install VSCode either through "sudo apt install code" or "dpkg -i code_1.18.1-1510857349_amd64.deb"
2. Start VSCode on a terminal console  in Ubuntu Desktop by typing "code"
3. No VSCode window popup. Instead, you will see the icon of VSCode on the left bar of desktop.
![screenshot from 2017-12-14 10-14-10](https://user-images.githubusercontent.com/19297121/33972495-11bd9522-e0b9-11e7-8e0c-c66b7af59f02.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
What does `code --verbose` return?

**Comment by ccic** [comment]
xxxx:~/VSChina/SignalR$ code --verbose
[main 5:37:21 PM] Starting VS Code in verbose mode
[main 5:37:21 PM] from: /usr/share/code/resources/app
[main 5:37:21 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false }
[main 5:37:22 PM] IPC#vscode-machineId
[main 5:37:23 PM] IPC#vscode-workbenchLoaded

**Comment by joaomoreno** [comment]
And a Window doesn't open?

**Comment by ccic** [comment]
No window was opened.

**Comment by ccic** [comment]
I guess it is not an issue of VSCode. I found my chrome or eclipse cannot pop up either. It looks like an issue of Ubuntu Unity. I'm investigating.

**Comment by joaomoreno** [comment]
Great, let us know if you find a fix eventually!
