### ISSUE TITLE
It is not possible to see any error output from crashed debug adapter extension

### ISSUE THREAD

**Issue by omusil24** [Microsoft/vscode#40198]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.5.0
Bookmarks|ale|0.18.0
cpptools|ms-|0.14.4
swaggitor|qns|0.1.1
qore-vscode|qor|0.2.6
cmake|twx|0.0.17

(2 theme extensions excluded)

---

I am developing a debug adapter extension but even through extensive logging, it's sometimes hard to find problems when the debug adapter crashes because VS Code just shows an error message `Debug adapter process has terminated unexpectedly`. There's no output in any of the terminals and debug consoles. It would be very useful if VS Code showed the exit code and stderr output which was produced by the debug adapter.

Steps to Reproduce:

1. Create a debug adapter extension.
2. Start debugging it.
3. Try to debug some file using it.
4. Make the debug adapter crash.

Reproduces without extensions: Yes

**Comment by omusil24** [comment]
Just found out that in the `[Extension Development Host]` window, in the `Extensions` tab of the `Output` terminal, there's stderr output. I guess this makes this issue solved.

But nonetheless, if VS Code opened this terminal tab in case of extension crash automatically, it would be useful. Or if it somehow made it more visible that there's a tab of the terminal with new unread output.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/41190
