### ISSUE TITLE
Column/Box selection using a mouse was gone in Official Build 1.18.1

### ISSUE THREAD

**Issue by whizkidwwe1217** [Microsoft/vscode#40193]
- VSCode Version: Official Build 1.18.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Press Alt + Shift + Mouse Drag
![2017-12-14_11-41-54](https://user-images.githubusercontent.com/1977391/33974528-ea02ef04-e0c3-11e7-80e0-0b783ff270fe.gif)

It's working in Insider Build 1.19.0-insider
![2017-12-14_11-49-36](https://user-images.githubusercontent.com/1977391/33974725-ea181626-e0c4-11e7-85e3-4a734ec427ae.gif)

Reproduces without extensions: `Yes`/No

**Comment by ramya-rao-a** [comment]
@whizkidwwe1217 We will be releasing 1.19 soon (in a day or 2) which will have the desired behavior as you have already seen in the 1.19 Insiders.
