### ISSUE TITLE
Linux block select

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#402]
The linux build doesn't seem to support block select like the Windows build; alt-shift-cursor keys.
I'd like (an option at least) for the cursor mechanics to behave identical in linux as windows. I shouldn't need to retrain my decade+ old muscle memory every time I need to fix/test the linux build.

**Comment by joaomoreno** [comment]
Is there really block select in the Windows build?

**Comment by TurkeyMan** [comment]
I could have sworn there was? I don't have a Windows build with me now, but I distinctly recall remarking to myself when I tried it out that the block selection worked correctly...?

**Comment by joaomoreno** [comment]
Nah.. never implemented. ;)
