### ISSUE TITLE
Panel shows 2 active sections

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40207]
1. Open the panel
1. Resize workbench until only 3 sections and `...` are visible in the panel header (like in screenshot below)
1. Switch to `Output`
1. Close panel in the `X`
1. Run `View: Toggle Integrated Terminal`

![image](https://user-images.githubusercontent.com/22350/33987228-7a91551e-e0c0-11e7-93fa-77e5db5668ac.png)

**Comment by isidorn** [comment]
@joaomoreno thanks for great steps
