### ISSUE TITLE
CSS Url() Path not  intelliSense

### ISSUE THREAD

**Issue by GiantLiu** [Microsoft/vscode#40203]
- VSCode Version:1.81.1
- OS Version:Win 10

Steps to Reproduce:

1.CSS Url() Path not  intelliSense

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Are you saying you are not getting path intellisense inside Url()?

**Comment by GiantLiu** [comment]
yes.in css file .set class background url().
eq: background: url(/PMimages/M14/gp1211/close.jpg)
input "url(/" or "url(../", i need intellisense "PMimages".
but now the vscode not support

**Comment by GiantLiu** [comment]
if input src="" in css file
the css file has intellisense path

**Comment by aeschli** [comment]
duplicate of #2037
