### ISSUE TITLE
re.exe cpu too high

### ISSUE THREAD

**Issue by PlutoCA** [Microsoft/vscode#40200]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular1-code-snippets|ale|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
gitlens|eam|6.4.0
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
canvas-snippets|hol|0.3.2
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
python|ms-|0.8.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vetur|oct|0.11.3
view-in-browser|qin|0.0.5
bootstrap4-vscode|the|3.0.0
python|tht|0.2.3
Angular2|UVB|0.4.1
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please read our wiki on [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and share more information so that we can help you.

**Comment by weinand** [comment]
Not enough info. Closing.
