### ISSUE TITLE
Allow to press "Tab" key to select an item from quick open

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#40204]
VSC 1.18.1 OSX 

Am I the only one that tries to press tab to select the highlighted text?

![image](https://user-images.githubusercontent.com/863731/33985718-b487593a-e0bb-11e7-9d5d-d6fc4eb41003.png)

I believe Tab auto completion for command panel is a feature we need

**Comment by bpasero** [comment]
Can be done via keybindings customization:

```
{
	"key": "tab",
	"command": "workbench.action.acceptSelectedQuickOpenItem"
}
```

**Comment by gertcuykens** [comment]
Wait a minute not so fast :P what happens if you press tab twice :) would be great to cycle through all the Terminal commands
