### ISSUE TITLE
Extension Host terminated

### ISSUE THREAD

**Issue by alexpolgithub** [Microsoft/vscode#40219]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
code-ngrx-snippets|dav|1.1.1
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.0.0
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
rest-client|hum|0.16.1
csharpextensions|jch|1.3.0
angular-essentials|joh|0.3.2
Angular2|joh|2.11.2
Angular-BeastCode|Mik|5.1.8
import-sorter|mik|1.1.1
mssql|ms-|1.3.0
csharp|ms-|1.13.1
debugger-for-chrome|msj|3.5.0
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.0.22
material-icon-theme|PKi|3.1.0
typescript-hero|rbb|1.8.0
partial-diff|ryu|0.5.1
aspnet-helper|sch|0.6.4
code-settings-sync|Sha|2.8.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You will need to provide more details on the issue if you want us to look into it.
