### ISSUE TITLE
In visual studio code console log does not print raw data but in terminal works?

### ISSUE THREAD

**Issue by chandhravadanan** [Microsoft/vscode#40215]
- VSCode Version: 1.17.2 (1.17.2)
- OS Version: macos seirra 10.12.6

Steps to Reproduce:

1. create sample.js file with following nodejs code

```
var fs = require('fs');
fs.readFile(process.argv[1], function callBack(err, data){
    if(err){
        return;
    }
    console.log('raw data ::', data);
    console.log('string ::', data.toString());
});
```

2. run the code

Issue : raw data statement itself not printed in vs code debugging console but works in terminal

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
This is because Node tells us that an object with some id has been logged, and by the time we request details of that object, the process has terminated. I'm not sure it's 100% fixable but we can probably do better.

**Comment by ThomasGHenry** [comment]
I'd love to see this working. I have to use the react native debugger for now.
