### ISSUE TITLE
Open file in project by typing partial name

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#4021]
I'm using Mac OS X with Visual Studio Code 0.10.10.

How do I use the keyboard to open a file, using its partial name, in the currently open project? I can't find a command in the Command Palette that would enable me to do this. As best I can tell, there is a command that does this for Working Files (see screenshot), but **not** for the currently open project.

<img width="606" alt="screen shot 2016-03-11 at 8 40 18 am" src="https://cloud.githubusercontent.com/assets/466713/13707082/31ea5ec4-e765-11e5-843b-43029439388d.png">

http://stackoverflow.com/questions/35944316/vscode-open-file-in-project

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by bpasero** [comment]
You can use Cmd+P to open a file by its name.

**Comment by pcgeek86** [comment]
@bpasero Thanks! Does that map to a VS Code command? I looked through the list and didn't see one. I might have missed it.

**Comment by Tyriar** [comment]
The command is `workbench.action.quickOpen`, you can check this by opening up the default keybindings through the command palette and seeing what's assigned to <kbd>cmd</kbd>+<kbd>p</kbd>.
