### ISSUE TITLE
save files when build

### ISSUE THREAD

**Issue by biztechlanka** [Microsoft/vscode#40217]
Is that possible to save the file when we build the project

**Comment by dbaeumer** [comment]
@biztechlanka we do save as @Gruntfuggly points out correctly. Do you have steps how to reproduce this. Can you provide a github repository I can clone that demos the behaviour.

**Comment by biztechlanka** [comment]
may be am wrong but if we got a settings to set when we build from terminal, lets say ng build should save the files but is not. Is that possible ?

**Comment by dbaeumer** [comment]
This would be a feature request against the terminal and very hard to implement since the VS Code actually doesn't know when it would be a could time to save.
