### ISSUE TITLE
Missing symbol in integrated terminal

### ISSUE THREAD

**Issue by tomintaiga** [Microsoft/vscode#40214]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.4.0-101-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
dot|Ste|0.0.1
python|ms-|0.8.0
cpptools|ms-|0.14.4
csharp|ms-|1.13.1
RustyCode|sav|0.19.1
cmake|twx|0.0.17
vscode-lldb|vad|0.7.1
cmake-tools|vec|0.10.3

---

Steps to Reproduce:

1. Open integrated terminal
2. Type echo "__pycache__"

No symbols "__" while typing and in echo output. If I have such directory ant type "ls", symbols are shown.

Reproduces without extensions: Yes

**Comment by kyranf** [comment]
The integrated terminal cannot display the '_' char at all. I just had a 30 minute "wtf" moment where I was printing file names to cout in my C++ program running from the integrated terminal window, and the names were not showing the underscores so i thought maybe the underlying filename parsing code was breaking somehow. 

The underscore characters are replaced by spaces in the output when printed.  I figure this is exactly the same bug as I was having ,so I have not opened my own Issue

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/35901
