### ISSUE TITLE
Quick info from tsserver

### ISSUE THREAD

**Issue by kv4sha** [Microsoft/vscode#40216]
How can I get the quick info from the tsserver in my own extension? 
I want to get all this information:
![image](https://user-images.githubusercontent.com/13916346/33996805-66078932-e0f3-11e7-81b7-efb96952fd26.png)

**Comment by mjbvz** [comment]
What are you trying to do?

**Comment by kv4sha** [comment]
I'm trying to get static properties from a class when I press Ctrl+Space.
I'm writing an extension.

**Comment by mjbvz** [comment]
We don't expose the TS server. Try using the `vscode.executeDocumentSymbolProvider` command: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands This should return symbol that you can then process to extract static properties
