### ISSUE TITLE
NPE when editing `.gitignore`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40218]
Simply edit `.gitignore`. The following error shows up in the devtools:

![image](https://user-images.githubusercontent.com/22350/33998496-ef5cb7b8-e0e7-11e7-96a3-25561e2a8486.png)

cc @jrieken

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/commit/a0b608d9b7b6f98fb005960d6b13cca9507ad28e
