### ISSUE TITLE
Status bar debug launcher should only be visible when debug view is closed

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#40212]
It seems daft to fill up with status bar with another widget when the configuration selector and start button are already available.

**Comment by isidorn** [comment]
Currently we have the `"debug.showInStatusBar"`
We could introduce another value "whenViewHidden" which could behave like you wanted
Code poitner https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugStatus.ts#L45

**Comment by Gruntfuggly** [comment]
Is "debug.showInStatusBar" documented? It's flagged as an unknown configuration setting when I try it, but it does seem to work.

**Comment by isidorn** [comment]
@Gruntfuggly try with latest vscode insiders, it should work fine there

**Comment by Gruntfuggly** [comment]
Works fine with 1.19 - thanks.

**Comment by isidorn** [comment]
Ups, accidently closed
