### ISSUE TITLE
Powershell Console Output inconsistant when running tasks

### ISSUE THREAD

**Issue by romero126** [Microsoft/vscode#40221]
- VSCode Version: 
- OS Version:

Steps to Reproduce:

1. write-host "Example"
2. dir *

Output will be as follows
Contents of Directory
"Example"

Reproduces without extensions: Yes

Developer Notes:
PowerShell instance is running code (Note this is example code and prolly wont compile):

	instance = PowerShell.Create();
	instance.InvocationStateChanged += Event_InvocationStateChanged;
	instance.Streams.Debug.DataAdded += Event_Debug_DataAdded;
	instance.Streams.Error.DataAdded += Event_Error_DataAdded;
	IAsyncResult result = instance.BeginInvoke<PSObject, PSObject>(null, psObjectHandler);
	#ReadResults of instance.Streams.Information
	
Need to Add (In order to process this data real time otherwise you get stuck with an out-of-order output stream):
 	instance.Streams.Information.DataAdded += Event_Information_DataAdded;

**Comment by ramya-rao-a** [comment]
Are you running these powershell cmds in the integrated terminal?

I dont understand what your "Developer Notes" are for

**Comment by romero126** [comment]
Hi Ramya,

I do have a project that might help with visualizing output...

I am using a Tasks.JSON to create a Build Task
{
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
"version": "2.0.0",
"tasks": [
{
"taskName": "build",
"isBuildCommand": true,
"command": ".\\test.ps1",
"isShellCommand": true,
"showOutput": "always",
"problemMatcher": []
}
]
}

When I press the Build option using these settings, Results of the commands
show up much later after I send write-host commands. So Output it becomes
Out of Order.

However both Write-Host and Object Return results are both mixed together.

**Comment by romero126** [comment]
Repro Steps in Github
https://github.com/romero126/PSKringle
ctrl+shift+b to Repro Steps

**Comment by dbaeumer** [comment]
@romero126 Running this produces the following output for me:
```
Herro World
WARNING: Duplicate Name already exists in this list.
List
-----------------------
CALL: Get-SecretSanta
Object Output: Get-SecretSanta


Snitch
-----------------------
CALL: Get-SecretSantaSnitch

Pairing List
-----------------------
CALL: Get-SecretSantaPairing

Finished Script

Name     EmailAddress   isPaired
----     ------------   --------
Waffles  test@gmail.com    False
a        test@gmail.com    False
b        test@gmail.com    False
c        test@gmail.com    False
d        test@gmail.com    False
Waffles2 test@gmail.com    False
Object Output: Get-SecretSantaSnitch
Joon     test@gmail.com
Object Output: Get-SecretSantaPairing






Object Output: Get-SecretSanta
Waffles  test@gmail.com     True
a        test@gmail.com     True
b        test@gmail.com     True
c        test@gmail.com     True
d        test@gmail.com     True
Waffles2 test@gmail.com     True
```

which I also get when executing in the integrated and in an external terminal. Can you please explain what you think is not working correctly

**Comment by romero126** [comment]
Hi Dirk, if you look at the output that gets produced. Write-host “Finished
Script”
Is the last command that is ran in the script. so the object output being
tacked on to the end and not being placed in its correct order.
Running the same commands in a powershell window result in the correct
order however in VSCode it does not.

**Comment by dbaeumer** [comment]
This is not true for me. Here is what I see with a native PowerShell terminal

<img width="698" alt="capture" src="https://user-images.githubusercontent.com/1931590/34037486-35ebaabc-e189-11e7-908f-3fa04cf5ef26.png">
