### ISSUE TITLE
code --status doesn't work if your shell is PowerShell

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#40228]
- VSCode Version: 1.19.0
- OS Version: Windows 10 FCU

Steps to Reproduce:

1. Open up the integrated terminal (VSCode on Windows) - defaults to PowerShell
2. Execute:  `code --status`

Outputs:
```
7:98ms> code --status

[main 1:37:36 PM] SyntaxError: Unexpected token S in JSON at position 30814
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:132:425)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Reproduces without extensions: NA - I get the same behavior if I start CMD or PowerShell directly and run `code --status`.

FYI, code on my system resolves to `C:\Program Files\Microsoft VS Code\bin\code.cmd`.

**Comment by zackschuster** [comment]
just tested this on my machine; works fine for me on insiders, using both the built-in powershell & powershell 6 rc from integrated, as well as built-in powershell from `Win+X`+`I`. curious if this might be a configuration issue or maybe a $psprofile override?

**Comment by rkeithhill** [comment]
I don't think it is a `$Profile` issue.  If I press `Win+R`, and execute powershell like so `powershell.exe -noprofile`.  The `code --status` still errors in the same way for me.

**Comment by bpasero** [comment]
@dbaeumer this seems to be from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/ps.ts#L182).

**Comment by rkeithhill** [comment]
Interesting. BTW for this line:
```javascript
const cmd = spawn('powershell.exe', ['-ExecutionPolicy', 'Bypass', '-Command', commandLine]);
```
I would recommend adding the PowerShell parameter `-NoProfile`.  For execution of this command I don't think you need to wait for PowerShell to process various profile scripts.

RE paths with spaces, while the following code handles spaces it doesn't handle `()` which are special characters in PowerShell::
```javascript
const script = URI.parse(require.toUrl('vs/base/node/ps-win.ps1')).fsPath.replace(/ /g, '` ');
```
For example, the `()` in `Program Files (x86)` causes the command to fail - ditto for `[]`.  I also have this problem on a machine with the 32-bit version of VSCode.

I would recommend quoting the `${scriptName}` path **instead** of trying to escape spaces and other PowerShell special characters e.g.:
```javascript
const commandLine = `"${script}" -ProcessName ${execMain} -MaxSamples 3`;
```
Now that the script is a string, you can't use -Command the same way.  You could just change `-Command` to `-File` unless you're examining the script's exit code.  If you need the exit code, use `-Command` but the invocation is a bit more complex e.g.:
```posh
powershell -executionpolicy ByPass -Command "& {& 'C:\Program Files\Microsoft VS Code\resources\app\out\vs\base\
node\ps-win.ps1' -ProcessName code -MaxSamples 3}"
```
If you have any follow up questions, don't hesitate to ask - I'm a 12th year PowerShell MVP.

**Comment by dbaeumer** [comment]
@rkeithhill thanks for the great suggestions. I will do the necessary changes.

When you see the failure do you use VS Code as a 32bit version? Otherwise I would not see why the changes would solve your problem which we should as well.

**Comment by dbaeumer** [comment]
@rkeithhill I went with -Command since I couldn't get -File to work :-(. I need to quote the execMain as well since it has spaces in its name when running insider builds.

I now do the following:
```ts
const execMain = path.basename(process.execPath);
const script = URI.parse(require.toUrl('vs/base/node/ps-win.ps1')).fsPath;
const commandLine = `& {& '${script}' -ProcessName '${execMain}' -MaxSamples 3}`;
const cmd = spawn('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', commandLine]);
```

I would appreciate if you could point out to me how to do this with -File. Just to know it for the future.

**Comment by dbaeumer** [comment]
And I would also appreciate a review of the ps-win.ps1 script. I am not a PowerShell expert at all.

**Comment by rkeithhill** [comment]
Big +1 on adding `-NoProfile`.  However, the whole command has to be quoted.  From `PowerShell /?` usage:
```
-Command
    Executes the specified commands (and any parameters) as though they were
    typed at the Windows PowerShell command prompt, and then exits, unless
    NoExit is specified. The value of Command can be "-", a string. or a
    script block.

    If the value of Command is "-", the command text is read from standard
    input.

    If the value of Command is a script block, the script block must be enclosed
    in braces ({}). You can specify a script block only when running PowerShell.exe
    in Windows PowerShell. The results of the script block are returned to the
    parent shell as deserialized XML objects, not live objects.

    If the value of Command is a string, Command must be the last parameter
    in the command , because any characters typed after the command are
    interpreted as the command arguments.

    To write a string that runs a Windows PowerShell command, use the format:
        "& {<command>}"
    where the quotation marks indicate a string and the invoke operator (&)
    causes the command to be executed.
```
We want the `string` format so I would tweak this line:
```js
const commandLine = `& {& '${script}' -ProcessName '${execMain}' -MaxSamples 3}`;
```
to
```js
const commandLine = `"& {& '${script}' -ProcessName '${execMain}' -MaxSamples 3}"`;
```
FWIW I have a machine at home where I use 64-bit VSCode and the command works fine.  Of course, I have another where I use 32-bit VSCode and it chokes here:
```
code --status

[main 9:28:44 AM] Startup error: x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ c:\Program` Files` (x86)\Microsoft` VS` Code\resources\app\out\vs\bas ...
+                     ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
````
So this fix you correct the 32-bit VSCode case.  I'm still curious why my machine at work where I use 64-bit VSCode fails.  I suspect my profile spits out some text that this tries to read in as JSON and kaboom - it fails.

**Comment by rkeithhill** [comment]
Yup, that is what it was e.g.:
```
180:103ms> powershell.exe -executionpolicy bypass -command "& {& 'get-date' | ConvertTo-Json}"
{
    "value":  "\/Date(1513357446619)\/",
    "DisplayHint":  2,
    "DateTime":  "Friday, December 15, 2017 10:04:06 AM"
}
Saving command history...
```
I have a registered a PowerShell engine exit event handler and in that I write out the message `Saving command history...`.  So the fix for me (and I suspect others) is to use `-NoProfile`.

**Comment by dbaeumer** [comment]
@rkeithhill thanks for the code review.

I have tried to put the command line into double quotes
```
const commandLine = `"& {& '${script}' -ProcessName '${execMain}' -MaxSamples 3}"`;
```

However this makes the command fail if the script path has no blanks or '(' / '[' characters. Is this intended. Since users can specify the install location of VS Code the command needs to run in these install locations as well.

**Comment by dbaeumer** [comment]
When executing the command Powershell simply print `& {& 'p:\mseng\VSCode\vscode\out\vs\base\node\ps-win.ps1' -ProcessName 'Code - OSS.exe' -MaxSamples 3}` to stdout.

**Comment by dbaeumer** [comment]
I retested it and using the commandLine variable as is (without the double quotes around it) works for me with a path having ` (x86)` in it. IMO the double quotes are only necessary if the command is type in a terminal but it is passed to a PowerShell process as one arg element. 

@rkeithhill did the insider build containing the fix still fail for you ?

**Comment by rkeithhill** [comment]
I suppose node's `spawn` command is quoting the entire contents of command `commandLine` since there are spaces in it.  So yeah, it appears you don't have to quote them again.  I'll check the x86 issue later tonight.

**Comment by dbaeumer** [comment]
@rkeithhill thanks for verifying.

**Comment by dbaeumer** [comment]
I will reopen this to propose it as a candidate for the recovery build.

**Comment by dbaeumer** [comment]
Looks like node does something here. Using a process explorer and looking at the command line it looks like this:

```
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& 'c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1' -ProcessName 'Code - Insiders.exe' -MaxSamples 3}"
```

**Comment by dbaeumer** [comment]
The flag to control this is `windowsVerbatimArguments `

**Comment by dbaeumer** [comment]
Cherry picked on release/1.19

Note that @rkeithhill already verified on Windows.

If we need to verify again do:

- install both a 64 and a 32 bit version of Windows
- make sure --status works

If you install the zip make sure that the installation path for

- 64bit contains spaces (e.g. `c:\My Program Files`)
- 32bit contains (x86) and spaces (e.g. `C:\My Program Files (x86)`)
