### ISSUE TITLE
VSCode window starts slightly offset from bottom of screen

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#40227]
Copy/paste from Reddit:

I'm on WIndows 10 Pro running 64-bit VSCode 1.18.1. I usually snap the VSCode app to the right side of my 3440x1440 screen. When I close and then restart VSCode, the bottom of the window has moved up a tad and the right side of the window has moved in ever so slightly. Can reproduce with and without using Windows' window snapping.

Not a big issue but the gap on the bottom drives me nuts.

https://www.reddit.com/r/vscode/comments/7jtlh4/vscode_window_starts_slightly_offset_from_bottom/

**Comment by mwcarew** [comment]
I posted that. Was a really minor thing and I wasn't entirely sure it was an issue with VSCode.

**Comment by mwcarew** [comment]
https://i.gyazo.com/c90d6882384da9a5e83c7fe9eabe9be9.gif showing the small gap at the bottom.

**Comment by auchenberg** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/28323 and https://github.com/Microsoft/vscode/issues/22010
