### ISSUE TITLE
Test new Java/Type-script settings

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#4022]
**Assignees:**

- [x] @jrieken 
- [x] @SofianHn

**Items**

The following settings have been added for both typescript and javascript:

`"typescript.validate.enable": boolean;` enabls/disables validation. If set to `false` no problems should be shown. Make sure the setting updates dynamically

Additional formatter settings: play with them and ensure that the formatter behaves correctly. 

```
"typescript.format.insertSpaceAfterCommaDelimiter": boolean;
"typescript.format.insertSpaceAfterSemicolonInForStatements": boolean;
"typescript.format.insertSpaceBeforeAndAfterBinaryOperators": boolean;
"typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": boolean;
"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": boolean;
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": boolean;
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": boolean;
"typescript.format.placeOpenBraceOnNewLineForFunctions": boolean;
"typescript.format.placeOpenBraceOnNewLineForControlBlocks": boolean;
```

Also ensure that the settings are independent of their javascript counterpart and apply to their respective mode. E.g.`javascript.validate.enable: false` and `typescript.validate.enable: true` is a valid configuration and problems are only shown in TS.

**Comment by SofianHn** [comment]
validated javascript/typescript validation options. Still waiting on #3980 for extra formatter options. @dbaeumer please ping me when it's done.

**Comment by dbaeumer** [comment]
@SofianHn #3980 is done. You can test it with the latest nightly build
