### ISSUE TITLE
--wait does not return on editor tab close

### ISSUE THREAD

**Issue by Aex** [Microsoft/vscode#40226]
- VSCode Version: 1.18.1
- OS Version: Windows 10 version 1703 (OS Build 15063.726)

Steps to Reproduce:

1. Open Cmd
2. Run ```git config --global core.editor "code --wait"```
3. Open VS Code
4. Run ```git config --global -e``` (Opens editor tab in existing VS Code Window)
5. Close .gitconfig Tab, with or without saving, but do not close VS Code Window.

Expected Result:
Control should be returned at the command line after Editor is closed.

Actual Result:
Command line is still waiting for the entire VS Code window to close.

Reproduces without extensions: Yes

Notes:
I receive the expected results on another system with the VSCode and OS Version below:
- VSCode Version: 1.18.1
- OS Version: Windows 7 version 6.1 (Build 7601: Service Pack 1)

**Comment by bpasero** [comment]
@Aex I cannot reproduce and it looks like you can also not reproduce on another system. What are your settings looking like? And can you attach the output of running code --verbose from the command line like so:

* `git config --global core.editor "code --wait --verbose"`
* `git config --global -e`

**Comment by Aex** [comment]
[main 8:07:22 AM] Sending env to running instance...
[main 8:07:22 AM] Sending some foreground love to the running instance: 4876

This is the point at which I close the editor tab, but leave the VS Code window open (due to other tabs). When I close VS Code completely down, I receive

[main 8:09:04 AM] Sent env to running instance. Terminating...

***Settings***
```
{
    "editor.fontFamily": "Fira Code, Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.rulers": [
        100
    ],
    // "editor.wordWrapColumn": 120,
    // "editor.wordWrap": "bounded",
    "editor.cursorBlinking": "phase",
    "editor.cursorStyle": "line",
    "editor.renderWhitespace": "boundary",
    "editor.renderControlCharacters": false,
    "editor.renderLineHighlight": "line",
    "editor.formatOnSave": true,
    "editor.minimap.enabled": false,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/K",
        "C:\\cmder\\vscode.bat"
    ],
    "terminal.integrated.fontFamily": "Fira Code, Consolas, 'Courier New', monospace",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorBlinking": true,
    "workbench.iconTheme": "vscode-icons",
    "files.associations": {
        ".env": "ini",
        ".env.example": "ini",
        ".docker.env": "ini"
    },
    "extensions.ignoreRecommendations": false,
    "prettier.eslintIntegration": true,
    "prettier.tabWidth": 4,
    "workbench.colorTheme": "Monokai Dimmed",
    "gitlens.codeLens.locations": [
        "document",
        "containers",
        "blocks"
    ],
    "gitlens.gitExplorer.enabled": false,
    "prettier.printWidth": 100,
    "window.menuBarVisibility": "default",
    "emmet.includeLanguages": {},
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": false,
        "suppressWelcomeNotice": true
    },
    "explorer.confirmDragAndDrop": false,
    "window.zoomLevel": 0
}
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Make sure to set `code-insiders` as editor for git.

**Comment by Aex** [comment]
I changed the editor value to `code-insiders -w` and I received the expected results. It appears to work correctly with the insiders build.

**Comment by bpasero** [comment]
Ok so it must be fixed meanwhile.
