### ISSUE TITLE
Integrated terminal toggle shortcut works only when caps lock is ON

### ISSUE THREAD

**Issue by iMasoud** [Microsoft/vscode#40220]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.12.0-2-amd64
- Extensions:  
vscode-icons|rob|7.19.0

---

Steps to Reproduce:

1. Open VSCode
2. Press ``` ^` ``` shortcut (ctrl+`) (default shortcut for workbench.action.terminal.toggleTerminal) while caps lock is off. Nothing happens.
3. Press same shortcut while caps lock is on. Integrated terminal toggles.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@iMasoud Have you tried our troubleshooting guide? https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
