### ISSUE TITLE
Notification of new update avaialble while using latest version

### ISSUE THREAD

**Issue by jpmckearin** [Microsoft/vscode#40222]
- VSCode Version: 1.19.0-insider
- OS Version: macOS 10.13.1

Steps to Reproduce:
1. Install latest VSCode Insiders (v1.19.0)
2. Wait for automatic updater to run
3. See notification for new version (which the v1.19.0)
4. Attempt to update and VSCode will not automatically restart as expected

Reproduces without extensions: Yes

Expected Results:
VSCode should match latest version and should not notify user that a new update is available.

<img width="1432" alt="code-insiders-issue" src="https://user-images.githubusercontent.com/6679168/34004379-5c70dc4c-e0bd-11e7-9355-dd3b19f9686c.png">

**Comment by joaomoreno** [comment]
You seem to have #7426

While running Code, what does `ps ax | grep Code` return? Can you paste the output here?

**Comment by jpmckearin** [comment]
I was able to fix it by running the following commands:
`xattr -dr com.apple.quarantine "/Applications/Visual Studio Code - Insiders.app"` (I don't think this did anything)
`sudo chown -R $USER ~/Library/Caches/com.microsoft.VSCodeInsiders`
`sudo chown -R $USER ~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt ` (As soon as I ran this, VSCode-Insiders **immediately** opened to the updated version.)

Output of `ps ax | grep Code` before and after fix:
https://gist.github.com/jpmckearin/28c4a03ee90cd0f2137e9e2322205283
