### ISSUE TITLE
invisible character accidentally inserted while using chinese ime.

### ISSUE THREAD

**Issue by gaoliang** [Microsoft/vscode#40223]
- VSCode Version: 1.18.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. use an chinese ime (sogou pinyin ime or macOS default chinese ime).
2. type space and then type an letter using the ime and do not enter ,just keep the ime float.
3. then press backspace. then presumably a � character will be added after the first space . and it is invisible in vscode unless push it to github as a markdown file.  some in the end of  this[ file](https://github.com/gaoliang/webpack-demo/blob/master/readme.md)
4. here a [video ](https://youtu.be/sxCSHyO3T1I)for this 

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Thanks, dup of https://github.com/Microsoft/vscode/issues/37114
