### ISSUE TITLE
Inconsistent buttons on warning dialogs

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#40224]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 10.0.16299
---

The warning messages we show to users should use consistent labels for buttons and should also be order the same where it makes sense. See the following example:

![screenshot](https://user-images.githubusercontent.com/4674940/34008653-e930302c-e0ba-11e7-81ea-e8193a0ec93a.PNG)

I propose
- to use `Never Show Again`
- to show `Never Show Again` right of `Close`, i.e. to not show an message again is a more deliberate motion than just clicking the right-most button.

We should think about enforcing the sequence of buttons in our code. I.e. shape the methods/APIs to declare whether a well-known button should be shown or not rather than where it should be shown.

**Comment by bpasero** [comment]
@kieferrm all of that will change with the new notification UX, you should join our UX call next time Steven presents it.

**Comment by nicksnyder** [comment]
> you should join our UX call next time @stevencl presents it.

I would be interested in this if it hasn't already happened yet. Is there info somewhere?

**Comment by bpasero** [comment]
@nicksnyder we will have a discussion in the team first, this is happen in these days. We can then share with broader community.

**Comment by aeschli** [comment]
- [fileService](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/fileService.ts#L113) has the button order `Don't Show Again` / `Close`
- [extensionTipsService](https://github.com/Microsoft/vscode/blob/519088548b09221e9d590d2e10e14ec6d27ac79a/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L46) still is lower case

These are checkboxes, but just to note:
- [fileActions](https://github.com/Microsoft/vscode/blob/e72ab44393a9a2ba9b6538deac7a66860346d695/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L700) and [explorerViewer](https://github.com/Microsoft/vscode/blob/e72ab44393a9a2ba9b6538deac7a66860346d695/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L897) uses `Do not ask me again`

**Comment by aeschli** [comment]
@bpasero Please close if this is as designed.

**Comment by bpasero** [comment]
@aeschli thanks for the findings, lets move to Feb.
