### ISSUE TITLE
Spawn pidof ENOENT when opening with extensions

### ISSUE THREAD

**Issue by McStuffins** [Microsoft/vscode#40237]
The error that continuously pop up when I install a package is: `spawn pidof ENOENT`

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
extension:
tslint|eg2|1.0.24
gtk-dark-titlebar|fkr|1.1.0
beautify|Hoo|1.1.1
docthis|joe|0.6.0
material-icon-theme|PKi|3.1.0
vscode-icons|rob|7.19.0
gi|rub|0.2.11

Steps to Reproduce:
1. install a package
2. reload

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
Does this happen for any particular extension or have you tried with a couple of different extensions?
How are you installing the package?

**Comment by McStuffins** [comment]
Any package. I believe that it had something to do with not having the 'git.path' set. After installing git to the proper programs directory that vs code is looking for, the error went away. I am not sure what the error exactly is.

**Comment by ramya-rao-a** [comment]
In that case, I'll close this issue
We have a separate issue tracking the git.path problem
