### ISSUE TITLE
Closing Brace auto-indent doesn't work properly

### ISSUE THREAD

**Issue by akshita31** [microsoft/vscode#40235]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: Extensions are disabled
---
Steps to Reproduce:

1. Add spaces between opening and closing brace of a method
2. Move the caret to a position in between the spaces and hit enter

Expected 
The closing brace is indented properly

Actual Behavior
The spaces preceding the closing brace are retained

![ezgif-4-4fb6926784](https://user-images.githubusercontent.com/12554141/34018716-15372a2a-e0e0-11e7-9eff-74ce698cc4bc.gif)

Reproduces without extensions: Yes

**Comment by akshita31** [comment]
Any updates on the issue ?

**Comment by colombod** [comment]
Is there any action or update on this item?

**Comment by colombod** [comment]
@rebornix do you have any ETA, we have a  [PR 1906](https://github.com/OmniSharp/omnisharp-vscode/pull/1906) that is blocked on this item

**Comment by vcipriani** [comment]
Can this be prioritized?  Its preventing omnisharp from implementing standard C# bracket formatting.  See https://github.com/OmniSharp/omnisharp-vscode/pull/1906 and https://github.com/OmniSharp/omnisharp-vscode/issues/1591).  This makes using VS Code for C# a non-starter in my org.

**Comment by pengshao82** [comment]
Yes, this is particularly frustrating that being a flagship language made my Microsoft and a flagship editor made by the same company, they cannot make such a simple thing work out of box, for years.

**Comment by sr229** [comment]
Keep in mind this is not the same as Visual Studio (they're probably not the same team as well), so this kind of feature may take a while as it may break existing functionality @pengshao82

**Comment by sr229** [comment]
Do we have any updates regarding this? The issue that this has linked has been open since 2017.

**Comment by pengshao82** [comment]
@sr229 I know, that is why I was referring vscode as flagship "editor" instead of IDE. VS on the other hand handles this just fine as I use it in my daily work. But for performance reason we are thinking of encouraging people to switch to VS code and this bug was pretty much a joy killer that took us by big surprise...

**Comment by swaidi** [comment]
the problem i'm facing now
even if i correct it manually, when i press save it goes to the wrong position
any help will be appreciated

**Comment by mjbvz** [comment]
Closing this since after 3 years it has one upvote (plus a handful of comments that are essentially upvotes)

While this is a bug, it does not break the code and is fixed by running format (protip: try enabling format on save!)

**Comment by nicholasoxford** [comment]
I think saying this has one upvote is short sighted. There are multiple issues linked to this and someone complained 9 days before you made your message. I am still having this problem as well

**Comment by dawesi** [comment]
there are several other editors that have preferences panels for this, it's about time vscode was less prescriptive considering how many developer communities it supports. The original team dismissed this and said there was only two ways to do code bracing and indenting 'ever', and I've argued this config panel since day 1 of vscode. It would solve a lot of developer issues just to give control to the DEVELOPER on how they format code so that plugins for languages could also default to what THEY use, not what core team think in theory what you should use.

The limited support for bracing, indentation and brackets has made this editor frustrating (and laughable) for years. Why not just look at other editors and see what they have done, then do similar... tried and TESTED solutions. #sigh instead of this elitist 'we know better' about how you should code 'theory'. Pretty much EVERY other editor has implmented this, why? because it makes sense. 

#intentingispersonal

https://mondrian.pentaho.com/images/code_indentation.png
https://www.nikialeksey.com/assets/imgs/code-wrapping-settings.jpg

**Comment by MJakeShapiro** [comment]
I truly hope y'all reconsider this issue. Yes it might not break anything but the simple things that make life easier are what make people stay.

**Comment by taglia24** [comment]
Still having this issue. Most annoying thing in VS Code for me.

**Comment by gabrieldechichi** [comment]
Would also like to voice my frustration on this. It prevented me from using VSCode with C# for years now. And I don't think there are only a handful of users who are frustated by this, is just that the git issues are hard to find on google (i.e searching for "vscode C# place brace on new line" on Google does not point to any of the relevant issues)

**Comment by gabrieldechichi** [comment]
For anyone seeing this in the future. I've found a workaround to automatically place braces on a new line by using `keybindgs` and `snippets`. Adding the following to your `keybinding.json` config should do the trick:

```
{
        "key": "Shift+[",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus",
        "args": {
            "snippet": "\n{\t$0\n}"
        }
}
```
This is not a perfect solution, as it jumps the line when you type `{` instead of waiting for you to hit `enter`, **but** it's been working quite nicely for me since the combo `{ + enter` does exactly what you would expect in other IDEs like VS (you'll have an open brace in new line, and your cursor in the middle of both braces)

**Comment by taglia24** [comment]
I got @gabrieldechichi's solution to work when `enter` is pressed.
First download [this extension](https://marketplace.visualstudio.com/items?itemName=geddski.macros) to add `macros`.

Add to settings.json:
```
// See keybindings.json for use information
"macros": {
    "newLineAndFormat": [
        {"command": "type", "args": {"text": "\n"}},
        "editor.action.formatDocument",
    ],
}
```
Add to keybindings.json:
```
// C# only
{
    // Format on enter pressed
    "key": "enter",
    "command": "macros.newLineAndFormat",
    "when": "editorLangId == csharp && editorTextFocus"
}
```
This keybind is active while editing C# documents only.
The language can be customized by replacing the `language id` with one from [this list](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers).

This solves pretty much all of my formatting issues.

**Comment by gabrieldechichi** [comment]
> // C# only
> {
>     // Format on enter pressed
>     "key": "enter",
>     "command": "macros.newLineAndFormat",
>     "when": "editorLangId == csharp && editorTextFocus"
> }

@taglia24 Does your format action takes the cursor to the beginning of the line, instead of respecting current indentation? 

![image](https://user-images.githubusercontent.com/15620434/121604459-c5614480-ca07-11eb-98b6-dea5f08f8a5e.png)

**Comment by taglia24** [comment]
It seemed to work fine after disabling some extensions, but it's back @gabrieldechichi.
For me it happens everytime the code is formatted.

I was trying this (really cheap) trick:
```
"macros": {
    "newLineAndFormat": [
        {"command": "type", "args": {"text": "\n"}},
        {"command": "type", "args": {"text": "§"}},  // Place placeholder
        "editor.action.formatDocument",
        // Delete command  // Remove placeholder
    ],
},
```
Anyway formatDocument seems to work asynchronously, so some some sort of onCompletion event is needed to time the placeholder removal.
Also I couldn't find a command to delete single characters from the text buffer.

If anyone is willing to mess around a bit I leave a shortcut to the full [list of commands](https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing).

I miss Visual Studio a bit more for every minute I spend on this.

**Comment by sarkh200** [comment]
A workaround is to add this to settings.json while having the macros extension added
`"macros": {
      "curl": [
        {"command": "type","args": {"text": "\n{\n\n}"}},
        "cursorUp",
        "tab",
      ],
    },
`
and then adding a keybinding to keybindings.json
`		// C# only
	{
    "key": "shift+enter",
    "command": "macros.curl",
    "when": "editorLangId == csharp && editorTextFocus"
	}`

**Comment by D-B-Daugh** [comment]
Since somehow none of the above worked for me, I went ahead and made a (probably) needlessly long macro to do what I wanted.

For this as above you will need the macro extension.

Put this in settings.json:
```
"macros": { "curlForm": [ "cursorLeft", {"command": "type","args": {"text": "\n"}}, "cursorRight", 
        {"command": "type","args": {"text": "\n"}}, 
        {"command": "type","args": {"text": "\n"}}, 
        "cursorUp", "tab" ], },
```

Put this is keybindings.json:
```
// C#
    { "key": "shift+enter", "command": "macros.curlForm", "when": "editorLangId == csharp && editorTextFocus" }
```

**Comment by HoveringGoat** [comment]
Ironcutter that worked for me! I spent wayyyy too long trying to solve this. But i'll be damned if i have confusing bracket placement.

**Comment by Ironcutter24** [comment]
I wrote a really minimal vscode extension ([C# Curly Formatter](https://marketplace.visualstudio.com/items?itemName=Ironcutter24.cscurlyformatter)) to solve the curly brackets indentation problems.
I'm also going to make it keep tab spacing in new lines, like in regular Visual Studio, as soon as I can.
Hope this helps, let me know if you encounter any issues with it.

**Comment by HunterLintz** [comment]
> I wrote a really minimal vscode extension ([C# Curly Formatter](https://marketplace.visualstudio.com/items?itemName=Ironcutter24.cscurlyformatter)) to solve curly brackets indentation problems. I'm also going to make it keep tab spacing in new lines, like in regular Visual Studio, as soon as I can. Hope this helps, let me know if you encounter any issues with it.

You ABSOLUTE Legend

**Comment by gudiugudiu** [comment]
> I wrote a really minimal vscode extension ([C# Curly Formatter](https://marketplace.visualstudio.com/items?itemName=Ironcutter24.cscurlyformatter)) to solve curly brackets indentation problems. I'm also going to make it keep tab spacing in new lines, like in regular Visual Studio, as soon as I can. Hope this helps, let me know if you encounter any issues with it.

Hero!
