### ISSUE TITLE
100% cpu load after upgrading to 1.19.0

### ISSUE THREAD

**Issue by marco-ms** [Microsoft/vscode#40232]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.4.0-103-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
project-snippets|reb|0.5.0
code-spell-checker|str|1.6.0
gitblame|wad|2.2.0

Often 100% cpu load

---

Steps to Reproduce:

1. Open VSCode 1.19
2. Open a project

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please read our wiki on [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and share more information so that we can help you.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
