### ISSUE TITLE
Terminal use `code -help` command with wrong output

### ISSUE THREAD

**Issue by bestvow** [Microsoft/vscode#40238]
![image](https://user-images.githubusercontent.com/24888709/34022536-ccd9e024-e17a-11e7-9b69-992d7e94ceb2.png)
![image](https://user-images.githubusercontent.com/24888709/34022537-cee2958c-e17a-11e7-8966-6ceef5291295.png)

**Comment by Tyriar** [comment]
Looks like the CLI formatting on Windows is off when the language is set to Chinese? The question mark makes me thing this is probably winpty.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
