### ISSUE TITLE
Git not found after Nov 2017 update

### ISSUE THREAD

**Issue by davesbrown** [Microsoft/vscode#40236]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
bracket-pair-colorizer|Coe|0.10.14
githistory|don|0.2.3
gitlens|eam|6.4.0
mssql|ms-|1.3.0
PowerShell|ms-|1.5.1
vsnotes|pat|0.4.3
vscode-icons|rob|7.19.0
html5-boilerplate|sid|1.0.1

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by McStuffins** [comment]
I am having the same issue. The `git.path` is not being set.

**Comment by McStuffins** [comment]
I found out what the issue was. The install path for git was going to a user specific directory instead of the global one. You have to run setup as admin and then set it to `C:\Program Files\Git` and then VS Code will recognize it when opened.

**Comment by davesbrown** [comment]
Right, seems it is now looking for it in Program Files and not looking at a \Users\<me>\AppData\Local\Programs\Git\cmd.git.ext

Seems like a breaking change to me, since it worked fine before the update.

VS Code Output
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Git installation not found.

**Comment by jmlntw** [comment]
+1 here.

I think it should use the global path to find git instead of the specific directory. There are some people using Portable Git, like me.

**Comment by auchenberg** [comment]
This is a duplicate of https://github.com/Microsoft/vscode/issues/40229

**Comment by ebgs** [comment]
Same with GitHub portable edition
