### ISSUE TITLE
side bar search dose not sync with find text in file

### ISSUE THREAD

**Issue by shaozi** [Microsoft/vscode#40231]
- VSCode Version: Version 1.19.0 (1.19.0)
- OS Version: MacOS 10.13.2 (17C88)

Steps to Reproduce:

1. Search some text in the file view panel, either by highlight the text then press ctrl-e, or by press ctrl-f and type in the text.
2. Now click the search magnifying glass on the side bar to show the global search bar, the search text in step 1 is not in the global search field.

Expected behavior:

The text in the global search field should sync with the text in the edit find search field. It was this way two versions back.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
The two have never synced, but previously the search viewlet was more aggressive about taking text that's selected in the editor. I restored that behavior recently in https://github.com/Microsoft/vscode/issues/38854, so you should see the same thing in Insiders shortly.
