### ISSUE TITLE
Test release notes notification

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#4023]
Related to #3525

### Assignees

- [x] OS X @isidorn 
- [x] Windows @bgashler1 

### Description

A notification should now appear every time you update Code to a new version, in order to get more users to read the release notes:

![image](https://cloud.githubusercontent.com/assets/22350/13709038/27db44c8-e7b2-11e5-88ba-e9e77edc7fb5.png)

- You should get this message every time Code updates to a new version.
- You should not get it when you install a brand new Code.
- Note that it is the *semver* version that needs to change in order to get this popup, not the commit ID.
- The previous version is always stored in the storage key `storage://global/releasenotes/lastversion`. It is the value used to figure out whether an update happened, so feel free to edit this when testing.

**Comment by pcgeek86** [comment]
@joaomoreno Can I help test this somehow? I see there's a storage key, but I'm not sure how to access that, to change the version number.

**Comment by joaomoreno** [comment]
Sure. [The Chrome dev tools lets you modify local storage values](http://stackoverflow.com/a/9404841/261019).

**Comment by bgashler1** [comment]
Whoops, shouldn't have closed this, since there was a remaining open issue referencing this.

**Comment by isidorn** [comment]
We close testplan-items once all the testers have checked off. So it is fine to close this
We do not track state of issues here.
