### ISSUE TITLE
Auto imports still produce broken code

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#40234]
- VSCode Version: 1.19

I'm reopening #38551 to get some attention and as it was closed while not fixed, as it's a major problem.

Unlike what was announced, VS Code 1.19 doesn't solve the issue of broken auto imports, so it will be two months (at least) with an automatic feature producing broken code activated by default. That's just incomprehensible...

Or TS 2.6.2 should have included the fix, or TS 2.7 fix should have been backported in VS Code, or PR #38552 to temporatily disable auto imports by default until TS does its job well should have been accepted, but the current situation is just bad.

**Comment by mjbvz** [comment]
As I noted in #38551, this will be fixed by TS 2.7 which we will pick up in January. Until then, you can either disable auto-imports or use `typescript@next`
