### ISSUE TITLE
can‘t find Git

### ISSUE THREAD

**Issue by screamsyk** [Microsoft/vscode#40240]
- VSCode Version:1.19
- OS Version:

Steps to Reproduce:

1.I install Git in E
2.Update VSCode to 1.19
3.Open my file ,can't find git in C
4. Other version of VSCode can find Git

Reproduces without extensions: Yes/No

**Comment by auchenberg** [comment]
Most likely a duplicate of https://github.com/Microsoft/vscode/issues/40240

**Comment by ramya-rao-a** [comment]
This is being tracked in #40229
