### ISSUE TITLE
[file icon] file icons for JSONC files

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#40244]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.4.0-103-generic (Ubuntu 14.04.5)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.4.0
nightswitch-lite|gha|2.0.3
Go|luk|0.6.69
cpptools|ms-|0.14.4
shader|sle|1.1.2
cmake|twx|0.0.17
code-navigation|vik|0.2.0
vscode-todo-highlight|way|0.5.11
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

---

Steps to Reproduce:

1. "Open folder" with .vscode directory inside
2. Press Ctrl-P to search for files
3. Type "settings" or "settings.json" (w/o quotes)

Result: settings.json doesn't appear in found files. Some icons are also appear incorrect. JSON icons are not assigned to launch.json, settings.json, tasks.json, but launch.json and tasks.json appear in search results (as "recently opened"). If i rolllback to 1.18.1 the issue goes away.

In 1.19:
![screenshot from 2017-12-15 04 04 49](https://user-images.githubusercontent.com/993454/34024181-797b941e-e151-11e7-986b-79662a4d8bf2.png)

In 1.18.1:
![screenshot from 2017-12-15 04 10 48](https://user-images.githubusercontent.com/993454/34024182-7b557b6a-e151-11e7-96c5-3ac597e8bd79.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Weird. @bpasero for file icons?

Are any other files missing from quick open? Is it just in that folder, or others?

**Comment by alekseyt** [comment]
> Are any other files missing from quick open?

I'm not sure if this is related, after you mentioned this, i've noticed that some directories are "grayed out" in 1.19 and files under them do not appear in quick open: 

1) .vscode/
2) all directories that soflinked to workspace, e.g. ``ln -sf ~/Dropbox/mydir ~/workspace/mydir``, then files under mydir/ doesn't appear in quick open in workspace/.
3) build/ directory is also grayed out for some reason, hard to tell why, it's not soflinked, neither .vscode/. Files under it are missing from quick open too.

![screenshot from 2017-12-15 06 12 40](https://user-images.githubusercontent.com/993454/34026487-1c5672c8-e15f-11e7-8ef8-bfbb16b00ecf.png)

Note how .vscode/ and build/ are in different shade of gray, soflinked dirs has this shade too. In 1.18.1 mentioned directories are also "grayed out", but quick open on them works.

> Is it just in that folder, or others?

I can reproduce this in 1.19 on another workspace if i copy settings.json to relevant .vscode directory.

**Comment by roblourens** [comment]
Sounds like they are probably covered by your .gitignore file. Is that the case?

**Comment by alekseyt** [comment]
Yeah. Removing those directories from .gitignore makes them appear in quick open, i've also checked settings and found this option in 1.19:

`"search.useIgnoreFiles": false,`

This works too. Although has no effect on icons.

**Comment by roblourens** [comment]
Are you using an extension for file icons? Which theme/extension?

**Comment by alekseyt** [comment]
II don't think i do, my file icons theme is "Seti (Visual Studio Code)".

But if i install e.g. "Material Icon Theme" (picked first in search) and enable it, then correct icons appear on all JSON files, switching back to "Seti" produces correct icon only on c_cpp_properties.json again, other JSON files under .vscode has "text file" (i think) icon again. 

"Minimal (Visual Studio Code)" shows the same icon on all files no matter JSON or not. "Nomo Dark Icon Theme" (picked second in search) works same way as "Material Icon Theme" (fixes icons). Seemingly reproduces on "Seti" only.

Also JSON files in other directories has correct icons. Reverting to 1.18.1 also fixes this.

I have this in global settings:

```
  // Specifies the icon theme used in the workbench or 'null' to not show any file icons.
  "workbench.iconTheme": "vs-seti",
```

No overloads in user settings or workspace settings. 

I do use not default color theme, i've uninstalled it, but that had no effect. Switching to default light or default dark didn't help either.

I can try to remove ~/.vscode or ~/.config/Code and see if it helps, just not sure if this would help to debug the issue.

**Comment by alekseyt** [comment]
On the second thoughts, i tried to temporarily move ~/.vscode and ~/.config/Code to another directory and restart vscode 1.19 - didn't help. JSON files under .vscode are still the only ones affected except c_cpp_properties.json.

Same as on original screenshot.

**Comment by roblourens** [comment]
I can also repro that. Seems to be due to the new "JSON with comments" language mode.

**Comment by bpasero** [comment]
@roblourens I think the missing icons for e.g. `launch.json` could be due to the fact that we introduced a new "JSON with Comments" mode? Maybe @aeschli could confirm that theory.

**Comment by aeschli** [comment]
Yes, the missing icons has to do with the new language mode. I might add a fix for this, but IMO not critical, the generic icons are ok too.
