### ISSUE TITLE
git 路径缺失

### ISSUE THREAD

**Issue by KbSimon** [Microsoft/vscode#40245]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
cssrem|cip|0.0.3
bracket-pair-colorizer|Coe|0.10.14
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
php-pack|fel|1.0.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
openchrome|hua|0.0.3
path-autocomplete|ion|1.7.0
vscode-github|Kni|0.24.0
vue|liu|0.1.5
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|1.0.0
easy-less|mrc|1.4.5
vscode-csscomb|mrm|5.2.1
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|3.5.0
color-highlight|nau|2.3.0
vetur|oct|0.11.4
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.1.0
vscode-css-peek|pra|2.0.2
view-in-browser|qin|0.0.5
LiveServer|rit|3.0.0
vscode-icons|rob|7.19.0
background|sha|1.1.17
quokka-vscode|Wal|1.0.84
bootstrap-3-snippets|wcw|0.1.0
change-case|wma|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
This is being tracked in #40229 and #40243
