### ISSUE TITLE
Extension recommendations: jshint

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40247]
Is it possible to **not** recommend `jshint` if `ESLint` is already installed?

**Comment by ramya-rao-a** [comment]
@dbaeumer @seanmcbreen @chrisdias Thoughts?

**Comment by dbaeumer** [comment]
That makes sense to me. We should also then not recommend ESLint if JSHint is installed.

**Comment by seanmcbreen** [comment]
Yes I see no issue.

That said it fells like it could get complicated if I generalize the desire e.g. I have chosen to use X extension for Y and you keep recommending me another extension.  I'm happy with what I have - so stop bugging me.

I wonder if we should (when we make a recommendation/in the list of recommendations) have a gesture to say - stop recommending this thing.  A user would take this action vs us trying to be smart about any combinations.

**Comment by ramya-rao-a** [comment]
Yes, it would be nice to have a way to remove a recommendation

**Comment by usernamehw** [comment]
Should this be closed as a duplicate of #48743 ?

**Comment by ramya-rao-a** [comment]
Yes, it can be. /duplicate #48743
