### ISSUE TITLE
Tabs for integrated terminal instead of dropdown

### ISSUE THREAD

**Issue by anandchakru** [Microsoft/vscode#40246]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6

---

Steps to Reproduce:

1. View -> Integrated terminal
2. Click on the plus in the top-right of the terminal panel
3. Enhancement request: Switching between terminals could be easy with tabs instead of dropdown

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546
