### ISSUE TITLE
is there any way to exclude files when auto-importing

### ISSUE THREAD

**Issue by oyb81076** [Microsoft/vscode#40248]
some typescript will compile into library/ temp/ build/ folder, is any way to exclude this folder,

**Comment by mjbvz** [comment]
I just answered this question over on SO: https://stackoverflow.com/questions/47796545/how-to-disable-auto-import-from-specific-files-in-vscode

In summary, no there is not a way to only exclude a file from auto import. You should exclude those files from your `tsconfig` project
