### ISSUE TITLE
 there is  no  active source manage system program .

### ISSUE THREAD

**Issue by WallenHan** [Microsoft/vscode#40242]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
ng-zorro-vscode|cip|1.1.3
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vsc-material-theme|Equ|1.1.2
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
vscode-npm-dependency|how|1.1.4
webpack|jer|2.0.2
Go|luk|0.6.69
font-awesome-codes-html|med|0.0.7
vscode-language-babel|mgm|0.0.10
Angular-BeastCode|Mik|5.1.8
vscode-extension-auto-import|Nuc|1.4.1
material-icon-theme|PKi|3.1.0
LiveServer|rit|3.0.0
px-to-rem|sai|1.2.3
vscode-i18n-tag-schema|sko|2.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
![ir jrh2 4w t gj8slnpvc](https://user-images.githubusercontent.com/5639544/34023928-6f87b95c-e182-11e7-9760-30ba72cadb7f.png)

2. there is  no  active source manage system program .

i had setted the git path

Reproduces without extensions: Yes/No

**Comment by WallenHan** [comment]
Actually I find  the git can work  when i use use the command pannel (crtl + shift + p),   but  only in the source manage pannel display  not work ,

**Comment by ramya-rao-a** [comment]
This is being tracked in #40243
