### ISSUE TITLE
when update this version the git.path set null.

### ISSUE THREAD

**Issue by Tony1952466760** [Microsoft/vscode#40243]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.4.0
EditorConfig|Edi|0.11.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
docthis|joe|0.6.0
Angular1|joh|0.2.0
docomment|k--|0.0.17
node-module-intellisense|lei|1.5.0
code-beautifier|mic|1.7.2
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|1.0.0
mssql|ms-|1.3.0
csharp|ms-|1.13.1
vetur|oct|0.11.4
Csharp-ASPNETCore|rah|1.0.5
java|red|0.15.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5
annotator|ryu|0.10.1
markdown-preview-enhanced|shd|0.3.1
stylelint|shi|0.31.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
markdown-all-in-one|yzh|0.11.2

---

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/11804148/34024109-78632c86-e183-11e7-8c6d-61288c3e37cc.png)

1. when i update this version ,my git.path set null.
2.

Reproduces without extensions: Yes/No

**Comment by sumbrez** [comment]
The same issue. I hadn't noticed this git path setting but I remember that after installing git on Windows, `<Git ins dir>\cmd` was added to `Path`, and vscode detected git.exe successfully. But now in ver 1.19, I have to set git.path manually otherwise the warning about git comes out.
