### ISSUE TITLE
Can't debug with random ports after upgrading to vscode 1.19.0.

### ISSUE THREAD

**Issue by yisiqi** [Microsoft/vscode#40254]
- VSCode Version: 1.19.0
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Add config to launch.json
```json
{
      "name": "Debug Tests WebSocket",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/.bin/jest",
        "--runInBand",
        "src/websocket"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
```
2. Launch it.
3. After a few seconds, got the Error info: connect ECONNREFUSED 127.0.0.1:13098

Reproduces without extensions: No

**Comment by yisiqi** [comment]
I just tried to set a specific port number. And it's works fine.

**Comment by weinand** [comment]
@yisiqi what version of node.js are you using?

**Comment by yisiqi** [comment]
Thanks @weinand , it's works.
And I do using node.js >= 8.0. But the old launch config works fine with vscode 1.18.x. I feel a little confused.

**Comment by weinand** [comment]
The launch config was always wrong.
But luckily long standing bug #16173 made the bogus launch config work.
In VS Code 1.18 we've fixed the bug and that affected your launch config.
Sorry for that.

/cc @roblourens
