### ISSUE TITLE
Git on Windows must use git.exe on %PATH% also

### ISSUE THREAD

**Issue by liaoya** [Microsoft/vscode#40253]
- VSCode Version: 1.19.0
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Install git on different path instead of the following 
  - `C:\Program Files\Git`
  - `C:\Program Files (x86)\Git`
2. Remove `git.path` on User Settings
3. Then VSCode will prompt

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
```

Reproduces without extensions: Yes

As a workground, I have to set `git.path`

**Comment by ljporljp** [comment]
already duplicated

**Comment by julytian** [comment]
nice work

**Comment by ramya-rao-a** [comment]
This is being tracked in #40229

**Comment by GHcodetyper** [comment]
@liaoya , thanks! works for me
