### ISSUE TITLE
Task ${relativeFile} slash style

### ISSUE THREAD

**Issue by purocean** [Microsoft/vscode#40256]
- VSCode Version: 1.19
- OS Version: Windows 10

Steps to Reproduce:

## VSCode 1.18
${relativeFile} is Linux Style like **a/b/c**

## VSCode 1.19
${relativeFile} is Windows Style like **a\b\c**

So when I run some task in WSL，Windows style slash will wrong。

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This is a more general issue since WSL needs to be treated as a Linux environment but VS Code thinks is is running under Windows and correctly uses `\`

**Comment by purocean** [comment]
@dbaeumer Variable support replace sub string `${relativeFile/a/b/}` replace `a` to `b` in *Sublime Text*，I want this feature in VSCode.

**Comment by dbaeumer** [comment]
Nice idea. Can you please open a separate issue for this.

**Comment by weinand** [comment]
@bpasero changed the behaviour of `${relativeFile}` with this commit:
https://github.com/Microsoft/vscode/commit/4a8327aa4b2e4173e43f9231be94a0278fd352de 

The change was good because it fixed the problem that `${relativeFile}` was using forward slashes on Windows.

However this broke the WSL use case (which only worked by accident before).
In general, VS Code variables are resolved on the Windows side. So they all should use backward slashes.

**Comment by bpasero** [comment]
fixed via https://github.com/Microsoft/vscode/commit/313a21df3af062a1726e33da78f65145b3876b13

@dbaeumer or @weinand please verify 👍

**Comment by dbaeumer** [comment]
@bpasero @weinand what will be the path forward. Using slash under Windows can cause problems when used in tasks. So IMI we should use `\` and break this. But we should announce this.

**Comment by weinand** [comment]
@dbaeumer yes, I fully agree: environment variables should always use the correct OS path separators. So for VS Code 1.20 we should announce that `${relativeFile}` will be consistent with all the other path variables.

**Comment by dbaeumer** [comment]
Would be cool to get https://github.com/Microsoft/vscode/issues/40288 for 1.20. Then a user has a nice way of controlling this. @isidorn any concerns ?

**Comment by bpasero** [comment]
My intent was to restore the previous (broken) way it was, not to fix the underlying issue.

**Comment by weinand** [comment]
Yes, we understand this. @dbaeumer was asking for "the path forward". And I think we have a story for that now.

In general I like #40288. But we'll have to coordinate this with some other requests for variables: #38381, #38327, #38977

**Comment by bpasero** [comment]
Sounds good 👍

**Comment by weinand** [comment]
verified on all platforms: `${relativeFile}` uses forward slashes on all OSes
