### ISSUE TITLE
Git tracked Workspace‘s files should can directly diff with workbase

### ISSUE THREAD

**Issue by ljporljp** [Microsoft/vscode#40251]
- VSCode Version:1.19
- OS Version:Windows_NT x64 6.1.7601

Steps to Reproduce:

1.open files that with git tracked like this one:
![20171215112844](https://user-images.githubusercontent.com/5728237/34025581-923d6d30-e18b-11e7-8e55-01169fc42774.png)

2.rightclick file name or file context can popup menu containing "diff with workbase" item

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
The `diff with workbase` command comes from an extension. Please file an issue to that extension.

**Comment by ljporljp** [comment]
Sorry, i can't find that extension you just said,Could you point out this for me? I'm unfamiliar with the framework.
