### ISSUE TITLE
cursor is automatically going to end of html tag.even when i try to type in body tag.

### ISSUE THREAD

**Issue by mohanacchu** [Microsoft/vscode#40258]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-refresh-html|baj|0.0.2
git-easy|bib|1.9.1
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-PSStackoverflow|Dou|0.0.2
gitlens|eam|6.4.0
vscode-npm-script|eg2|0.3.3
StackSearchExt|gcr|0.0.2
beautify|Hoo|1.1.1
path-autocomplete|ion|1.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|5.1.8
material-icon-theme|PKi|3.1.0
LiveServer|rit|3.0.0
vscode-icons|rob|7.19.0
guides|spy|0.9.1
html-css-class-completion|Zig|1.14.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please provide reproducible steps, sample code and screenshots
