### ISSUE TITLE
\extensions kills

### ISSUE THREAD

**Issue by Ants-double** [Microsoft/vscode#40250]
I have a question 
env:
code :1.19.0
816be6780ca8bd0ab80314e11478c48c70d09383
x64
os: Windows_NT 10.0.16299
I try reinstall code and nodejs ,but i also meet the question ,i find only debug node type can meet the question ,the other can't not find the question,i also try delete extends file or git file floder ,not ok,so ,i geuss the node evnoke the question.thanks ,i am now one.
![360 20171215112356121](https://user-images.githubusercontent.com/32797983/34025370-7a48e80e-e18a-11e7-908d-a4f4938df16b.jpg)

**Comment by jrieken** [comment]
@Ants-double Can you please follow the steps in this guide: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.

**Comment by Ants-double** [comment]
Thanks ,i fix the question when i rebuild the OS. but i guess the node.js extends have some question at my reconfigure the info ,i fix the node config some setting ,then the vscode vill give me the tips.so i now keep the nodejs setting is default ,i can't meet the question .Sorry  my OS rebuild  can't give you back as soon as .my error . next . I will give more information .but this time i don't have enough time to get other information of the issues .




At 2017-12-20 18:51:33, "Andre Weinand" <notifications@github.com> wrote:


This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
