### ISSUE TITLE
updated

### ISSUE THREAD

**Issue by xcsweb** [Microsoft/vscode#40259]
- VSCode Version:
- OS Version:

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/20693737/34028978-fbebe76a-e1a0-11e7-9828-e2f460159c8e.png)

1.
![image](https://user-images.githubusercontent.com/20693737/34028667-9a834050-e19f-11e7-8fc4-cf54e828d1a5.png)
how can solve a problem?

![image](https://user-images.githubusercontent.com/20693737/34028963-ede6e19c-e1a0-11e7-814b-7c92fc3f8716.png)

**Comment by julytian** [comment]
@xcsweb ,[vetur issue #580](https://github.com/vuejs/vetur/issues/580)

**Comment by wzc0x0** [comment]
me too , annoyed . Please resolve as soon as possible!

**Comment by julytian** [comment]
@wzc0x0 ,  set ` "vetur.validation.template": false `to your vscode user setting

**Comment by wzc0x0** [comment]
Thanks , but it's for the moment

**Comment by ramya-rao-a** [comment]
This is caused by the vetur extension. Please log an issue in the repo for vetur
