### ISSUE TITLE
No progress indicator when installing VSIX

### ISSUE THREAD

**Issue by dlebu** [Microsoft/vscode#40257]
VSCode Version: Insiders 1.19.0
    OS Version: MacOS

Steps to Reproduce:

    Install an extension from vsix

Expected: Progress Indicator until the success message shows up
Actual: No Progress Indicator.

@ramya-rao-a

**Comment by egamma** [comment]
@dlebu discussed it with @sandy081 and the plan is to show progress in the status bar as some other extensions (e.g. C#) do it when they download and install additional code.

**Comment by sandy081** [comment]
Duplicate of #41759
