### ISSUE TITLE
BUG:无法代开rsStructuredText插件对rst文件进行预览

### ISSUE THREAD

**Issue by FontTian** [Microsoft/vscode#40268]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
restructuredtext|lex|44.0.0
python|ms-|0.9.0

---

Steps to Reproduce:

1.BUG:无法代开rsStructuredText插件对rst文件进行预览
2.

Reproduces without extensions: Yes/No

**Comment by jrieken** [comment]
Please change to English, please add steps

**Comment by FontTian** [comment]
VSCode Version: Code 1.19.0 (816be67, 2017-12-14T09:56:48.842Z)
OS Version: Linux x64 4.10.0-42-generic
Extensions:
Extension	Author (truncated)	Version
restructuredtext	lex	44.0.0
python	ms-	0.9.0


BUG: the rsStructuredText plugin is not able to preview the RST file

Steps to Reproduce:

1. open a .rst file
2. open the preview to the side
3. connot open (in chinese) "Preview'preprocessing_target.rst" :Error 

Reproduces without extensions: No
