### ISSUE TITLE
js doc function no found

### ISSUE THREAD

**Issue by Tony1952466760** [Microsoft/vscode#40266]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|6.4.0
EditorConfig|Edi|0.11.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
docthis|joe|0.6.0
Angular1|joh|0.2.0
docomment|k--|0.0.17
node-module-intellisense|lei|1.5.0
code-beautifier|mic|1.7.2
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|1.0.0
mssql|ms-|1.3.0
csharp|ms-|1.13.1
short-js-doc|mya|0.1.10
vetur|oct|0.11.4
Csharp-ASPNETCore|rah|1.0.5
java|red|0.15.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5
annotator|ryu|0.10.1
markdown-preview-enhanced|shd|0.3.1
stylelint|shi|0.31.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
markdown-all-in-one|yzh|0.11.2

---

Steps to Reproduce:

1. Prior to this release ，i use '/**' + enter ，auto finish
```
/**
 *
 */
```
but now ,this function no found. only leave Document This Extensions
![image](https://user-images.githubusercontent.com/11804148/34030252-117577ee-e1a7-11e7-8fc0-5938cfc30012.png)

2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
Please try disabling the document this extension and restarting VS Code. It seems to be causing this issue
