### ISSUE TITLE
Vim Extension Fails to Load on Extension Update

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#40260]
- VSCode Version: 1.19.0
- OS Version: n/a -- various

Everytime we [VSCodeVim] push an update, we always seem to see cases where the extension fails to load. The recommendation I've been giving folks is to delete ~/.vscode/extensions/vscodevim and reinstall.

Reference: https://github.com/VSCodeVim/Vim/issues/2226, https://github.com/VSCodeVim/Vim/issues/2227, https://github.com/VSCodeVim/Vim/issues/2185

**Comment by jpoon** [comment]
Another one: https://github.com/VSCodeVim/Vim/issues/2231

**Comment by jpoon** [comment]
Oops, meant to just comment.

**Comment by diminutivesloop** [comment]
You can also uninstall and then reinstall the extension via the command `code --install-extension vscodevim.vim`. That fixed the issue for me without having to delete all my other extensions.

**Comment by jpoon** [comment]
Optimally, users shouldn't need to do that.

**Comment by jpoon** [comment]
We pushed an update to the extension and got more reports of the upgrade breaking: #2287. Reinstalling the extension resolves the issue. 

Is this just effecting VSCodeVim? Or are other extensions having issues when users are updating?

**Comment by sandy081** [comment]
@jpoon Can you please give us more specific details about what is not working? And also are there any consistent steps to reproduce this which will be helpful?

**Comment by jpoon** [comment]
@sandy081 Whenever we push an update to vscodevim, we often get issues stating that the new extension fails to load. We've seen this issue since likely the beginning of extension, but I've linked a few of the issues of people having failed to upgrade from 0.10.4->0.10.5, 0.10.5->0.10.6, 0.10.8->0.10.9, 0.10.9->0.10.10. I've linked a couple of issues and the general symptom is the extension fails to load. The call stack in here: https://github.com/VSCodeVim/Vim/issues/2185, might be helpful.

**Comment by sandy081** [comment]
@jpoon From the stack trace it looks like the extension was not completely downloaded. Can you please ask users if this is the case?

**Comment by sandy081** [comment]
After investigating more, I figured out that root cause is Auto update feature triggers updating the  extension from all open windows and we try to install (download, delete existing and extract) the extension multiple times. 

This can lead to different failures like 
- errors while deleting the existing folder
- partially extracted extensions
- error while accessing the extracted folder

**Comment by aeschli** [comment]
Validated by:
- create a new extension, install new extension
- disable auto update
- open 3 vscode windows
- publish new version
- in each window search for the extension
- enable auto update, observe that all windows have updated the extension
- verify that the extension still works

**Comment by jpoon** [comment]
Thanks @sandy081 and @aeschli :)

**Comment by jpoon** [comment]
We received a couple more reports of this happening for users updating to the latest version of VSCodeVim. The theme so far has been users have been all on Windows -- linked two issues above.

**Comment by jpoon** [comment]
@sandy081 another reported case, also on windows: https://github.com/VSCodeVim/Vim/issues/2420
