### ISSUE TITLE
Broken workflow with 1.19 update

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#40264]
- VSCode Version: 1.19
- OS Version: Arch Linux

Steps to Reproduce:

1. `cd someFolder && code .` vscode will be opened with current folder as root
2. use dmenu to launch vscode. It will open up empty file(code-stdin-xxx) in tmp folder.

Previously it used to open last opened folder (ie someFolder) as root folder in the current instance too.

Reproduces without extensions: Yes

> https://wiki.archlinux.org/index.php/Dmenu

**Comment by bpasero** [comment]
@agauniyal make sure that `dmenu` is not launching our CLI script but the actual Code binary. Then it should be fine.

**Comment by agauniyal** [comment]
@bpasero can you help me out with that 😅  -
```
cat /usr/bin/code 
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# If root, ensure that --user-data-dir is specified
if [ "$(id -u)" = "0" ]; then
	for i in $@
	do
		if [[ $i == --user-data-dir=* ]]; then
			DATA_DIR_SET=1
		fi
	done
	if [ -z $DATA_DIR_SET ]; then
		echo "You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument." 1>&2
		exit 1
	fi
fi

if [ ! -L $0 ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname $0)/.."
else
	if which readlink >/dev/null; then
		# if readlink exists, follow the symlink and find relatively
		VSCODE_PATH="$(dirname $(readlink -f $0))/.."
	else
		# else use the standard install location
		VSCODE_PATH="/usr/share/code"
	fi
fi

ELECTRON="$VSCODE_PATH/code"
CLI="$VSCODE_PATH/resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by dcelasun** [comment]
I'm the maintainer of the Arch package and this is an already fixed packaging issue, it shouldn't have been reported here.

**Comment by bpasero** [comment]
@dcelasun great

For anyone else hitting this issue, make sure to execute the `Code` binary directly and not the `code.sh` terminal script which is only intended to be called from a real terminal.

On Ubuntu for example the binary is: `/usr/share/code/code`

**Comment by crumblingstatue** [comment]
Is there any reason `code.sh` could not detect when it's running in a tty, and not try to open stdin when it's not in a tty?
