### ISSUE TITLE
Courier fonts rendering issue

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#40263]
_From @douglarek on December 14, 2017 9:48_

![image](https://user-images.githubusercontent.com/1488134/33985921-ed09d2fc-e0f6-11e7-973e-2c9a9f7670b8.png)

_Copied from original issue: Microsoft/vscode-go#1407_

**Comment by alexandrudima** [comment]
@douglarek perhaps you want to turn off `editor.fontLigatures` ?

**Comment by douglarek** [comment]
thx
