### ISSUE TITLE
Cmd+A from explorer no longer selects all in editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40261]
Steps to Reproduce:

1. press Cmd+A when focus is in explorer
2. nothing happens, it used to select all in the editor

@isidorn @joaomoreno fyi this may be a candidate for recovery.

**Comment by joaomoreno** [comment]
Is that really a feature?

Also, it does not _reproduce_ in the stable we just released.

**Comment by joaomoreno** [comment]
This happens because I introduced a [`list.selectAll` command](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L304). I can make that command depend on whether the underlying widget supports multi select.

**Comment by bpasero** [comment]
@joaomoreno sorry, I thought this would reproduce in stable.

To be fair, if we implement multi select in the explorer for this milestone, Cmd+A should probably select all in the explorer and then we are also fine. 

I think quite a number of people bugged me a while ago that Cmd+A would not select all in the editor, but rather be a no-op.

**Comment by bpasero** [comment]
Thanks, the fix sounds good to me, only do it when the list/tree actually supports it.
