### ISSUE TITLE
switch git branch and the file explorer doesn't update

### ISSUE THREAD

**Issue by Adamwu1992** [Microsoft/vscode#40277]
- VSCode Version: version 1.19
- OS Version: macOS 10.13.1

Steps to Reproduce:

1. open iTerm, `cd` to the project folder and use `code .` to open in VSCode
2. switch git branch in iTerm
3. the file explorer in left doesn't update
4. use `code --disable-extensions` to open it again, it fixed
5. use `code .` to open it, the bug doesn't show again

Reproduces without extensions: No

**Comment by Adamwu1992** [comment]
the bug shows again

**Comment by joaomoreno** [comment]
The file explorer updates only when Code's window is focused. Can you confirm that that's the case?

**Comment by Adamwu1992** [comment]
I use `code --disable-extensions` to fix it and it doesn't appear until now 😂😂😂

But it is not the case.

When i change branch in iTerm and focus on VSC, i can see the branch name in left bottom changed, but the explorer is wrong.

**Comment by joaomoreno** [comment]
What if you manually make some file system changes (delete a folder, create a file, etc)... Do these changes appear in the explorer?

**Comment by Adamwu1992** [comment]
I will try when it appears again.
Thank you for responding.

**Comment by joaomoreno** [comment]
OK I'll wait
