### ISSUE TITLE
VSCode doesn't remember the state of the horizontal scroll

### ISSUE THREAD

**Issue by 21region** [Microsoft/vscode#40271]
- VSCode Version: 1.19.0
- OS Version: Microsoft Windows 10 Enterprise 2016 LTSB (10.0.14393 N/A Build 14393)

Steps to Reproduce:

1. Open two *.txt files: **a.txt**, **b.txt**. Let's say **a.txt** is wide enough to make VSCode show horizontal scroll bar.
2. Scroll contents of **a.txt** horizontally to the right.
3. Switch to a tab with **b.txt**.
4. Switch back to **a.txt** tab. It is now scrolled back to the left.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Moving to @alexandrudima, all I do is restore the view state that I get.

**Comment by 21region** [comment]
Did this fix get into version **1.19.1**?

**Comment by alexandrudima** [comment]
No, we typically only fix important (high severity) issues for recovery releases. Here are the 7 issues we fixed in `1.19.1`: https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22November+Recovery+2017%22+is%3Aclosed
