### ISSUE TITLE
Quick search file doesn't work after update to 1.19

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#40272]
- VSCode Version: 1.19
- OS Version: Mac OS

Steps to Reproduce:
After update to 1.19 the quick search file stop working for me. Based on this gif:

![](https://raw.githubusercontent.com/Microsoft/vscode-tips-and-tricks/master/media/QuickOpen.gif)

When I type `App.js` in quick search, the list return only 1 result (recently opened) instead of whole list with results.

It seems like project is not indexing?

Reproduces without extensions: Yes

**Comment by ldrick** [comment]
Seems the same on Ubuntu 17.10.
I have 2 folders in my workspace, the first one seems to be indexed correctly, CRTL+P shows results.
But the second one returns not a single result, before 1.19 both returned results.

In an other workspace is only one folder, this one seems to work.

Could it be, that only first folder is indexed now?

**Comment by PixelT** [comment]
I don't use workspaces ;) and it also doesn't work for me (symptoms like in first post)

**Comment by ldrick** [comment]
Could fix it for me by adding `"search.useRipgrep": false` to my settings. This even doesn't need a restart of vscode o.O
Tried everything mentioned here and played around: #40076

**Comment by PixelT** [comment]
I read that issue and next problem is that I'm on Mac :) but yes, when I set:
`"search.useRipgrep": false`
the quick open seems to work properly....

**Comment by roblourens** [comment]
Which results are you missing? There are lots in that list, are you sure they aren't just sorted somewhere else?

Does text search work to find results in those files?

**Comment by IcyPoint** [comment]
> I read that issue and next problem is that I'm on Mac :) but yes, when I set:
"search.useRipgrep": false
in my settings, the quick open seems to work properly....


This works for me either.

**Comment by PixelT** [comment]
As I wrote here:
> When I type App.js in quick search, the list return only 1 result (recently opened) instead of whole list with results.

Whole list I mean all files which have in name `app.js` (like on screenshot from 1 post)

**Comment by ldrick** [comment]
@roblourens For me neither search in files, nor searching files with CRTL+P works.
I have tested again now with one file with a unique name, which won't show up at all.
If, like I wrote before, ripgrep is disabled, the file shows up in both searches again.

**Comment by jrseliga** [comment]
Can also confirm this issue on Ubuntu 17.04 & 17.10.

Setting `search.useRipgrep` to `false` has corrected the behavior, though not sure what the consequences are in doing so.

**Comment by PixelT** [comment]
For me also now set `search.useRipgrep` to `false` doesn't work....

**Comment by roblourens** [comment]
Everyone besides @PixelT please open your own issue, it sounds like there are some different symptoms.

@PixelT You have a strange problem if it still doesn't work after disabling ripgrep. 

> Whole list I mean all files which have in name app.js (like on screenshot from 1 post)

I see - the screenshot is from 1.18. Does text search work to find results in those files? If not, are there any errors in the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by mirao** [comment]
I have the same issue with quick search in subfolder "vendor" in my [Codeception](http://codeception.com/) project.
The subfolder is created after running "composer install" and it's not a part of my Git repository.
I can confirm that workaround `"search.useRipgrep": false` works for me.

Not sure it's a regression in vscode 1.19, but I'm sure it worked well in some of previous versions.

Used SW:

- vscode 1.19.1/1.20 insider, Ubuntu 17.10

**Comment by PixelT** [comment]
@robertohuertasm 
- Output tab is clean
- When I'm using Search to find some content which is in this file, it's normally showed this file in result pane.

**Comment by PixelT** [comment]
Any updates here?
It's annoying to using the quick search now, which incidentally, does not work...

**Comment by roblourens** [comment]
> When I'm using Search to find some content which is in this file, it's normally showed this file in result pane.

So when you do a text search, it finds results in that file, but quick open doesn't find that file? Or was that after setting `"search.useRipgrep": false`?

Are the files covered by your .gitignore file? Or any `search.exclude` or `files.exclude` settings?

**Comment by PixelT** [comment]
> So when you do a text search, it finds results in that file, 

Yes

>but quick open doesn't find that file?

Finally it would find the file, but it takes much time, sometimes up to 1-2 minutes...

> Are the files covered by your .gitignore file? Or any search.exclude or files.exclude settings?

No

**Comment by roblourens** [comment]
So before you were saying that it didn't find the files at all, but now it does find them, but it takes a long time?

**Comment by PixelT** [comment]
No no, the files are alwasy founded, but in version 1.18 and earlier it take max. 10s, after update into 1.19 and newest it take much longer time, as I said up to 1-2 minutes before the quick search result some records.

+ When I switch to: `"search.useRipgrep": true` it always return: 'No results found'

I would also add, the problems exist when I have a project with a lot of files (magento2, ~100k files except `node_modules` folders), in small project (up to 100 files, I do not see  these symptoms)

**Comment by roblourens** [comment]
Ok, we should focus on what happens with `"search.useRipgrep": true` because that's the default setting and should work.

So when you have that setting, and you do a text search, then you should be missing the same files, right? Please try that, then show the contents of the search output pane:

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by PixelT** [comment]
I've checked it on Insiders version and Log(Window) return:
```
[2018-01-26 19:10:12.474] [renderer1] [info] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/.history' -g '!**/.vscode' --no-ignore-parent --follow -- '.'
 - cwd: /Users/krzysiek/px_projects/magento2
 - Sibling clauses: {}
```

**Comment by roblourens** [comment]
Is this the magento2 repo here: https://github.com/magento/magento2

Can you try with `"search.useIgnoreFiles": false` just to make sure we can eliminate that?

**Comment by PixelT** [comment]
OK, what I did:
- I disabled all extensions
- I removed all custom settings (**use defaults settings now**)

I would like to find:
- file `product/list.phtml`
- string `$_productCollection = $block->getLoadedProductCollection();`

Tip: this string above exist in this file (product/list.phtml).

I recorder each step here:
https://www.dropbox.com/s/itnaqzj9duwsgi4/vscode-search.mp4?dl=0
I hope it will help!

> Is this the magento2 repo here: https://github.com/magento/magento2

Yes is should be this, but this I think are only sources, on my local I have installed Magento2 and there are a lot files (see on demo above)

**Comment by roblourens** [comment]
In magento2's gitignore file, I see `/vendor/*`, which should cover the file you listed. Can you try with "search.useIgnoreFiles": false?

**Comment by PixelT** [comment]
It seems that change `search.useIgnoreFiles` to `false` helped...

**Comment by roblourens** [comment]
Great, sounds like that was it

**Comment by mirao** [comment]
It seems that the setting `search.useIgnoreFiles` was changed in #37211

**Comment by PixelT** [comment]
It seems that this problem back in `1.21.1` ...
