### ISSUE TITLE
CSS syntax misspelled include

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode#40287]
On [line 1061](https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json#L1061) of the CSS syantax, I believe it should be `#property-values` since `property-value` does not exist. This is just based on my limited understanding of Textmate grammars.

@aeschli

**Comment by aeschli** [comment]
duplicate of #40157. I created https://github.com/atom/language-css/issues/133
