### ISSUE TITLE
Startup Issue Slow

### ISSUE THREAD

**Issue by tomy8910** [Microsoft/vscode#40284]
[-](url) VSCode Version: <code>Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T06:08:07.643Z)</code>
- OS Version: <code>Darwin x64 17.2.0</code>
- CPUs: <code>Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)</code>
- Memory (System): <code>8.00GB (0.34GB free)</code>
- Memory (Process): <code>199.15MB working set (0.00MB peak, 127.31MB private, 74.46MB shared)</code>
- Load (avg): <code>10, 6, 4</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|110|
|main|app.isReady => window.loadUrl()|770|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|644|
|renderer|require(workbench.main.js)|2303|
|renderer|create extension host => extensions onReady()|2039|
|renderer|restore viewlet|79|
|renderer|restore editor view state|46|
|renderer|overall workbench load|644|
|main + renderer|start => extensions ready|6136|
|main + renderer|start => workbench ready|4509|

---

[343d-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1562347/343d-exthost.cpuprofile.txt)
[343d-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1562348/343d-main.cpuprofile.txt)
[343d-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1562349/343d-renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Two items stand out: (1) code loading and (2) extension host creation. The first should resolve itself since we create v8 cached data after a short while the latter might depend on the extensions you have installed

@tomy8910 Please go 'F1 > Show Running Extensions' and check their activation time.
