### ISSUE TITLE
OutputService: TypeError: Cannot read property 'setInput' of undefined

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#40281]
This happened when trying to reproduce https://github.com/Microsoft/vscode/issues/40229. You can reproduce it by, in Windows, uninstalling Git. Then start up Code from `master` and you'll get:

![image](https://user-images.githubusercontent.com/22350/34037023-7fd11f56-e187-11e7-8900-c8013cb7a483.png)

This might be related to the latest changes in the service?

**Comment by joaomoreno** [comment]
Actually, better repro steps: just run `Git: Show Git Output`

**Comment by sandy081** [comment]
Yeah related to my changes. This happens when

- Output panel is hidden
- Open output panel by running `Git: Show Git Output`

Temporary workaround until fix: Use Toggle Panel.
