### ISSUE TITLE
array#coalesce don't coalesce sparse arrays

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#40289]
* have a sparse array
* use coalesce on it
* the resulting array is still sparse

**Comment by bpasero** [comment]
@jrieken added some tests via https://github.com/Microsoft/vscode/commit/9812d210d6e509f9d04eb2cca782ead8fc5d39ad but cannot reproduce, which case is not working?

**Comment by jrieken** [comment]
Hm, had something different in mind... Added b2df3e8be0 which seems to work
