### ISSUE TITLE
Breakpoints not responding in debug mode.

### ISSUE THREAD

**Issue by mudassir-ngineous** [Microsoft/vscode#40280]
- VSCode Version: 1.18.0 (yet to observe on 1.19.0)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Breakpoints marked during debugging maximum time don't impact or work. This very random behvior, Need to restart VScode finally

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Please provide reproducable steps. What language are you debugging?
Please clarify what you are trying to state. 
Please follow our issue submiting rules https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
