### ISSUE TITLE
Detect extensions on templates

### ISSUE THREAD

**Issue by ephracis** [Microsoft/vscode#40285]
I have a lot of files that are templates. They are usually named like so:

- my_file.yml.ejs
- another_file.coffee.j2

Currently Code assumes that all `ejs` are HTML files but this is not always the case. It would be better if Code could detect both the `yml` part and the `ejs` part, and properly highlight the code according to this.

Now I have to manually switch language on all files which is tedious, and I also lose the proper highlighting of the template tags. This affects more than just pretty colors to. For example when I paste in large blocks of code I get the wrong indentation if the language is not correct.

**Comment by myrdd** [comment]
as a workaround, I'm using file associations like the following:

```json
{
    "files.associations": {
    "*.html.j2": "html",
    "*.ini.j2": "ini",
    "*.yml.j2": "yaml",
  }
}
```

**Comment by ephracis** [comment]
Yeah I'm doing that too right now. But that won't make VS Code detect the jinja. 😒

**Comment by theballdredge** [comment]
started some work with templates recently, this would be super nice
