### ISSUE TITLE
what is "Would you like to enable auto fetching of Git repositories?"

### ISSUE THREAD

**Issue by awebdeveloper** [Microsoft/vscode#40282]
- VSCode Version: 1.19
- OS Version: osx

Include info on what is "Would you like to enable auto fetching of Git repositories?" along with the alert

--- 

**Feature Explanation:** Code can automatically and periodically fetch refs from your remotes. It calls `git fetch` periodically. That way it can show you how many incoming/outgoing commits you might have. This is the feature that the popup asks about.

**Comment by puranik3** [comment]
I was just Googling for the same :)

**Comment by ryanbuening** [comment]
> I was just Googling for the same

Same here. Does anyone know what this is?

**Comment by joaomoreno** [comment]
I've added an explanation in the first comment of this issue:

---

**Feature Explanation:** Code can automatically and periodically fetch refs from your remotes. It calls `git fetch` periodically. This is the feature that the popup asks about.

**Comment by taivu** [comment]
how would i disable/enable this in after making a selection?

**Comment by SandyGlantz** [comment]
Same question as @taivu. Plus, will anything on the current VSC set-up change if I select "no" to the prompt?

**Comment by briancodes** [comment]
Firstly I don't think this should have been raised as an issue. 
See https://github.com/Microsoft/vscode/issues/34684
Think this setting was previously true by default, now it's false. The prompt is just to remind you to enable if you wish.
Configured via ```"git.autofetch": false```, so can be easily undone

**Comment by joaomoreno** [comment]
**Verification**

I've improved the message to:

> Would you like Code to periodically run `git fetch`?

I've also added a `Read More` link to https://go.microsoft.com/fwlink/?linkid=865294 which will soon talk a bit more about this setting: https://github.com/Microsoft/vscode-docs/pull/1307
