### ISSUE TITLE
Jasmine typings in .spec files not found

### ISSUE THREAD

**Issue by twjacobsen** [Microsoft/vscode#40283]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

I reported this issue last month (#39364), but was told that it was caused by an extension.

As you can see in the data above, I've removed *all* extensions, and the issue still appears.

I've now found, that it is *not* related to extensions, but to the typescript version picker.

When I pick the VSCode built-in (2.6.2 as of writing this), typings are found as expected.

If I pick the workspace version (2.5.3 as of writing), it does *not* find the typings.

For technical reasons, we can't upgrade TS in our project, but I have a hard time seeing why this issue has been introduced?

More details can be found in issue #39364

Edit: 

After further investigation, it might not be a VSCode issue, but a Typescript issue.. I tried upgrading the workspace ts version to 2.6.0-rc, 2.6.1 and 2.6.2 (latest), and the typings were broken in 2.6.0-rc, but not in 2.6.1

**Comment by mjbvz** [comment]
Yes, if this is also broken when you run `tsc`, it is either an issue with your project or a TypeScript issue. What error are being reported?

**Comment by twjacobsen** [comment]
`tsc` runs fine (through webpack).

VSCode just reports `cannot find name [it | describe | beforeEach | anyJasmineOperator]`.

And its only jasmine typings in the spec files. All other typings work just fine. 

Note, that adding `import * from jasmine` to the file does fix the issue, but my colleagues (webstorm users) don't see the issue, so I'd prefer not adding imports specifically for my editors happiness

**Comment by mjbvz** [comment]
Ok, since this works in more recent versions of TS, I'm going to close this issue. It sounds like there was a bug in 2.5 that has since been fixed in 2.6

If you need to stay on 2.5, you can use 2.6 in your workspace but 2.5 for compile. Or you can also try asking on stackoverflow where someone may be able to provide more detailed help on configuring TS 2.5 to work
