### ISSUE TITLE
Feature Request: Tasks variables replacing

### ISSUE THREAD

**Issue by purocean** [Microsoft/vscode#40288]
*Sublime Text* has this feature
> `${relativeFile/a/b/}` replace `a` to `b`
> http://sublimetext.info/docs/en/reference/build_systems.html#variables

I use WSL script for work in VSCode. So I need change file or dir path slash, or change suffix some times.

I think this will be a useful feature.

#40256

**Comment by dbaeumer** [comment]
@isidorn assigning to you since this would nicely fit into the configuration resolver service.

**Comment by weinand** [comment]
We'll have to coordinate this with some other requests for variables: #38381, #38327, #38977

**Comment by isidorn** [comment]
We accept PRs that fix this issue
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/electron-browser/configurationResolverService.ts#L23

If noboy volunterees to look into this I can investigate second half of January

**Comment by pradeepmurugesan** [comment]
@isidorn this is interesting. I can give a shot. 

The code pointer still holds good ? Looks like its pointing to an import statement now.

**Comment by isidorn** [comment]
@pradeepmurugesan the code pointer is decent, it is that file still.
For the PR to be accepted please try to implement it in a clear and simple way if possible.

**Comment by pradeepmurugesan** [comment]
@isidorn Sorry if my question is too naive.. Where will the user execute the command ```${relativeFile/a/b/}```

I mean is it in the command window of vscode ( cmd + Shift + p )  or somewhere else ?

**Comment by weinand** [comment]
it is a variable in a launch configuration (from launch.json) or a task (from task.json).
Here is an examples from VS Code's own launch configurations: https://github.com/Microsoft/vscode/blob/master/.vscode/launch.json

Everything starting with '$' is a variable. Most of them are simple and just evaluate to a filesystem path.

**Comment by pradeepmurugesan** [comment]
@weinand  Thanks for the explanation.

So  ```${relativeFile/a/b/}``` is a string replace, and the modified string will be used by the task or launch configuration ?

Am I understanding it right ?  

Initially I thought it should move the file in the filesystem to the new name.

**Comment by weinand** [comment]
`${relativeFile}` is a simple variable and `${relativeFile/a/b/}` is basically a `${relativeFile}.replace('a', 'b')`

**Comment by stefaneidelloth** [comment]
Would like to see this feature. Also see https://stackoverflow.com/questions/45132566/how-to-fix-jest-no-tests-found-on-windows-10/57522638#57522638

**Comment by anavalaka** [comment]
can we also do substring as well?
