### ISSUE TITLE
[v-test][PHP] Debug add to watch doesn't show value of array item

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4029]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

When adding a single array element to the watch list, it doesn't correctly show the value of the element.
Adding the entire array to the watch list works as expected.

Example:
![phpaddtowatcharrayfoo](https://cloud.githubusercontent.com/assets/12900364/13712617/845f6c9e-e779-11e5-9825-1d677bb88a95.JPG)

**Comment by felixfbecker** [comment]
Afaik VS Code doesn't include a PHP debugger, so in case you are using my extension, you might want to move the issue to https://github.com/felixfbecker/vscode-php-debug

**Comment by weinand** [comment]
This issue was moved to felixfbecker/vscode-php-debug#26
