### ISSUE TITLE
ALT + . does not work in integrated terminal

### ISSUE THREAD

**Issue by scriptum** [Microsoft/vscode#40291]
- VSCode Version: 1.18.1
- OS Version: CentOS 7.3

Steps to Reproduce:

1. Open integrated terminal
1. Run some command e.g. `cd /tmp`
1. Press `Alt + .`

Expected result: word `/tmp` appears in terminal input.

Reproduces without extensions: Yes
Reproduces with all default keybindings (fresh installation): Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11314
