### ISSUE TITLE
Can't launch debugger with runtimeExecutable that has a space in the path

### ISSUE THREAD

**Issue by bfrost2893** [Microsoft/vscode#40301]
- VSCode Version: 1.18
- OS Version: Windows 7

Steps to Reproduce:

1. Create a launch config that runs a yarn/npm script, or any other `runtimeExecutable` with a space in the path
2. Run the launch configuration

Example launch config: 
```json
{
      "type": "node",
      "request": "launch",
      "name": "yarn test",
      "runtimeExecutable": "yarn",
      "runtimeArgs": ["test"],
      "cwd": "${workspaceFolder}",
      "outFiles": ["${workspaceFolder}/dist/**/*.js"],
      "stopOnEntry": false,
      "sourceMaps": true
}
```

Alternatively, the `runtimeExecutable` could be `C:\Program Files (x86)\Yarn\bin\yarn.cmd`, or whatever the absolute path to your `yarn` program is.

**Console Output**
```
Debugging with inspector protocol because a runtime executable is set.
C:\Program Files (x86)\Yarn\bin\yarn.cmd --inspect=45818 --debug-brk 'test' 
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Reproduces without extensions: Yes

**Comment by weinand** [comment]
I cannot reproduce this problem in VS Code 1.18.1 and 1.19.1 ("legacy" and "inspector" protocol) on Windows.
My launch config is:
```
 {
     "type": "node",
     "request": "launch",
     "name": "Launch Program",
     "runtimeExecutable": "C:\\Users\\weinand\\foo bar\\nodeX.exe",
     "program": "${workspaceFolder}/test.js",
     "protocol": "inspector",
     "outputCapture": "std"
}
```

**Comment by bfrost2893** [comment]
@weinand I don't know if Windows 7 would make a difference, but that is the OS I was running.

**Comment by weinand** [comment]
Same results for Windows 7 and VS Code 1.18.1: I cannot reproduce.

@roblourens since you have targeted this for January: are you able to reproduce?

**Comment by roblourens** [comment]
At first I thought this was the same as that issue where we send text to the terminal, and when the terminal is powershell, we don't escape spaces correctly. But this is different. Spaces shouldn't matter when we are just doing `cp.spawn('c:\\program files\\...')`, so I have no idea what would cause this.

**Comment by weinand** [comment]
@bfrost2893 since we are not able to reproduce this, we need more detailed steps for the latest version of stable VS Code (1.19.1).

**Comment by weinand** [comment]
This could be an instance of https://github.com/nodejs/node/issues/7367
Pls see https://github.com/Microsoft/vscode/issues/45832.
