### ISSUE TITLE
Typescript syntax highlighting breaks when method return type has a number in the name

### ISSUE THREAD

**Issue by bryceg** [Microsoft/vscode#4030]
When my return type on a method has a number in it, the syntax highlighting breaks for that method.
I'm using 0.10.10

![image](https://cloud.githubusercontent.com/assets/2497408/13712868/cb0f9c26-e77a-11e5-9bb4-e1e639924441.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#125
