### ISSUE TITLE
cmd creation of component generates error in module

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#40302]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
git-tree-compare|let|1.1.4
debugger-for-chrome|msj|4.0.0
background|sha|1.1.17

---

Steps to Reproduce:

1. `ng generate component componetName`

Reproduces without extensions: Yes

Explanation - Whenever you generate a component through the terminal, when it generates the references in the module it creates errors for those references. 
i.e:
`import { MaintainUserComponent } from './maintain-user/maintain-user.componen;
import { NotFoundComponent } from './not-found/not-found.component't';`

And

`@NgModule({
    declarations: [
        MaintainUserCompone,
        NotFoundComponentnt,`

It's simple to fix, it's just monotonous. I've had this problem in three different projects

**Comment by ramya-rao-a** [comment]
> Whenever you generate a component through the terminal

Are you referring to the integrated terminal or external terminal or it doesn't matter which?

Can you elaborate on what the errors are and how you fix them?
Screenshots help a lot

**Comment by JohnstonCodyMTO** [comment]
It's happening in both integrated and external terminal. 
Here's a screenshot of what happens:
![problem on module](https://user-images.githubusercontent.com/33288271/34055072-b363e542-e19b-11e7-991a-5097bfbfee0c.jpg)

So the errors are generated when it creates the component and tries to add the new components reference to the related module.
I fix it just by going in and fixing the values that broken. Nothing really technical, it's just a small problem I found.

**Comment by mjbvz** [comment]
This seems like an issue with the `ng` command, right?

**Comment by mjbvz** [comment]
Closing as I believe this is an external issue
