### ISSUE TITLE
Visual Studio Code Powershell New-PSSession Command Access Denied

### ISSUE THREAD

**Issue by rweir4** [Microsoft/vscode#40306]
- VSCode Version: x64 1.18.0
- OS Version: Windows 2012 R2

Steps to Reproduce:

1.$cred = Get-Credential
$O365_Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.protection.outlook.com/powershell-liveid/ -Credential $cred -Authentication Basic -AllowRedirection
2.Error message: "Connecting to remote server ps.protection.outlook.com failed with the following error message: Access is denied."

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Your repro steps has only code and the error message.
It doesn't contain actual steps as to what we are to do with the given code to get the given error.

Please provide as much details as possible
Hint: Assume that we know nothing of Powershell

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
