### ISSUE TITLE
Focus should remain in code-window after pressing F8

### ISSUE THREAD

**Issue by logg-sar** [Microsoft/vscode#40304]
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open any Powershell-Script
2. Mark one line (yes, the line should make sense - but Write-Output "TEST" should be enough)
3. Press F8 to execute the line
4. Focus changes to Terminal window

Expected/desired: focus should remain in the coding window. At the moment I have to grab the mouse and click in the window to be able to select next line.
In the ISE the focus remains in the coding window.

Thanks

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
