### ISSUE TITLE
Workbench Panel Location Preferences Gone

### ISSUE THREAD

**Issue by stnguyen90** [Microsoft/vscode#40309]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
vagrant|bbe|0.5.0
Gradle|caz|1.1.2
python|ms-|0.9.0
java|red|0.15.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-java-test|vsc|0.1.0
markdown-all-in-one|yzh|0.11.2

---

Steps to Reproduce:

1. Open Settings
2. Search for workbench.panel.location

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_19#_workbenchpanellocation-is-deprecated

**Comment by ramya-rao-a** [comment]
Thanks for the link @usernamehw :)
