### ISSUE TITLE
[PHP] Running format code with leading indented php tag deletes php

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4031]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

If you have an opening `<?php` tag indented (with either tab or spaces) at the beginning of a php file and right click -> Format Code, it deletes all the php code included until the closing `?>` tag.
Additionally, if there are no html tags later on in the file, Format Code seems to do nothing.

Steps:
1. Open a new PHP file.
2. Add a tabbed `    <?php    ?>` 
3. Add any html tags `<html> <body></body> </html>`
4. Right click -> Format Code or Alt+Shift+F
5. Removes leading php tags and any included code.

Expected:
Formats PHP code and does not delete it.

**Comment by aeschli** [comment]
@vsccarl Format is not implemented for .php files. Did you install an extension? Or is this in a .html file?

**Comment by vsccarl** [comment]
@aeschli Ah yes, it is most likely an issue with the PHP Code Format extension. I'll open it there.

**Comment by vsccarl** [comment]
Moved to [https://github.com/kasik96/VSCode-PHP-Format/issues/27](url)
