### ISSUE TITLE
Scrolling on Surface Trackpads is stuttery/laggy

### ISSUE THREAD

**Issue by uditrana** [Microsoft/vscode#40319]
- VSCode Version: <code>Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)</code>
- OS Version: <code>Windows_NT x64 10.0.16299</code>
- CPUs: <code>Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)</code>
- Memory (System): <code>15.93GB (8.51GB free)</code>
- Memory (Process): <code>219.50MB working set (310.93MB peak, 198.38MB private, 53.46MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|49|
|main|app.isReady => window.loadUrl()|298|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|269|
|renderer|require(workbench.main.js)|1101|
|renderer|create extension host => extensions onReady()|737|
|renderer|restore viewlet|0|
|renderer|restore editor view state|395|
|renderer|overall workbench load|476|
|main + renderer|start => extensions ready|2473|
|main + renderer|start => workbench ready|2200|

---

Additional Steps to Reproduce (if any):

It's an intermittent issue and can't find any particular pattern to reproduce but fast scrolling with my Surface Pro 3 and Surface Book 2 can really lag, stutter, and skip. Maybe a Surface only issue or a precision trackpad driver interaction issue. Scrolling with an external mouse connected to the same machine in the same session works perfectly though. Touch scrolling also works perfectly.

**Comment by bpasero** [comment]
#13612
