### ISSUE TITLE
[css] warn when using whitespace characters in identifiers

### ISSUE THREAD

**Issue by jacquelinclem** [Microsoft/vscode#40317]
Hi,

I work with visual studio code for my .scss file.
Sometime, when I write a class like : `.class {}`, I got an unwanted char (No break space[NBSP]) between the name of my class and the bracket. Which break all my style.css.

The result I was waiting for is to get a space, not a no-break-space.

I don't know how to reproduce the bug with precision, there is no "pattern".

Hope you can help me ...

- VSCode Version: 1.18.1 (1.18.1)
- OS Version: Mac Book Pro - OS X El Capitan - 10.11

Screen of the bug : 
![vscodebug](https://user-images.githubusercontent.com/17112884/34054989-92015cae-e1cd-11e7-9e48-8ee59f0c37a8.png)

Screen of my extension : 
![vscext](https://user-images.githubusercontent.com/17112884/34055020-b995438e-e1cd-11e7-8015-c836b1f10aba.png)

**Comment by jacquelinclem** [comment]
Ok my bad, here is what I've found : 
The "No break space[NBSP]" is the key `alt + space` on mac.
And when I write class on css I press `alt + space + (` which render ` {`.
By pressing to fast the `alt` key, I create a unwanted "No break space[NBSP]".

It's not a bug, just myself pressing some key "to fast".

**Comment by aeschli** [comment]
If I understand the spec correctly, NBSP (ascii 255) is a valid identifier character.
https://www.w3.org/TR/CSS21/syndata.html#tokenization.

I could add an optional warning when used.

**Comment by jacquelinclem** [comment]
Yep, took me a long time to discover what the problem was because I had not the activated the option "show space & tab" ...

**Comment by octref** [comment]
Syntactically your code is valid. If you still want some warning, consider asking other linting extensions (such as CSSLint: https://github.com/CSSLint/csslint)  or write your own extensions.
