### ISSUE TITLE
Move Selected Lines indentation is buggy...

### ISSUE THREAD

**Issue by alejandrodbm** [Microsoft/vscode#40310]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions:

Extension|Author (truncated)|Version
---|---|---
goto-documentation|cxf|0.0.1
Go|luk|0.6.69

---

Steps to Reproduce:

1. Create several nested loops and put a simple "if statement..."
2. Select the "if statement" and move it up and down, you will see a buggy indent behavior.

**Graphical example:**

Before move selected lines
<img width="457" alt="screen shot 2017-12-15 at 12 36 05 pm" src="https://user-images.githubusercontent.com/28928280/34051474-20e1cab4-e195-11e7-956d-1d01698f462f.png">

After move selected lines
<img width="521" alt="screen shot 2017-12-15 at 12 36 23 pm" src="https://user-images.githubusercontent.com/28928280/34051484-2a096296-e195-11e7-8693-c9ae22ea1ae1.png">

Reproduces without extensions: Yes

**Comment by KJanos1396** [comment]
+1

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
