### ISSUE TITLE
--status fails for default Windows 32 bit installation location

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#40316]
- VSCode Version: 1.19
- OS Version: Windows 10

'code --status' returns:
[main 10:12:35 AM] Startup error: x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ c:\Program` Files` (x86)\Microsoft` VS` Code\resources\app\out\vs\bas ...
+                     ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Looks like ' (x86)' is causing a problem

**Comment by bpasero** [comment]
I suspect this is our powershell execution @dbaeumer

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/40228.
