### ISSUE TITLE
Support `CompletionEntry.isRecommended` from TypeScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#40325]
**Feature request**
TS 2.7 adds a new `isRecommended` property on `CompletionEntry` (https://github.com/Microsoft/TypeScript/pull/20020) This is marked so we can figure out that a type makes sense in a given location. We should observe this property in VS Code to order our completions

**Comment by mjbvz** [comment]
@jrieken Yes actually suggest memory messes up other sorting smartness like  #40311 as well

Could we could borrow the TS concept of `isRecommended` on completion items?

**Comment by jrieken** [comment]
Yeah, we can think of exposing something in the API and that will then over-rule the memory
