### ISSUE TITLE
update, I close the program, I open again and returns the previous version. (bucle)

### ISSUE THREAD

**Issue by luisherdethh** [Microsoft/vscode#40323]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
numbered-bookmarks|ale|0.11.0
githistory|don|0.2.3
vscode-html-css|ecm|0.1.8
beautify|Hoo|1.1.1
vscode-power-mode|hoo|2.0.0
html-tag-wrapper|hwe|0.2.3
path-autocomplete|ion|1.7.0
vscode-docker|Pet|0.0.22
java|red|0.16.0
LiveServer|rit|3.0.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5
searchdocs|rob|0.0.3
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-preview-server|yui|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you fully reinstall Code?
