### ISSUE TITLE
Extension host crash

### ISSUE THREAD

**Issue by fchevitarese** [Microsoft/vscode#40322]
I already tried to remove some extensions, but idk what is happening... 
Suddenly... crash :( 

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
vscode-simple-icons|Lau|1.7.1
vscode-docker|Pet|0.0.22
expressjs|ama|2.0.0
vscode-icontheme-nomo-dark|be5|1.3.4
django-snippets|bib|1.1.0
simple-react-snippets|bur|1.1.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.0
auto-close-tag|for|0.5.5
code-python-isort|fre|0.0.3
vue-snippets|hol|0.1.5
html-tag-wrapper|hwe|0.2.3
python|ms-|0.9.0
node-debug2|ms-|1.19.0
appidocsnippets|mya|0.1.15
vetur|oct|0.11.5
typescript-hero|rbb|1.8.0
java|red|0.16.0
react-beautify|tai|0.3.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-react-native|vsm|0.5.7
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please share more details as instructed in our wiki on [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues)

**Comment by ramya-rao-a** [comment]
- Can you repro this when running `code --disable-extensions`
- If not, then one of the extensions you have installed is the root cause, please log an issue against the repo of such extension.
- Do you see any perf issues just before crashing? If so, then follow the wiki linked above and share more details

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
