### ISSUE TITLE
Can VSCode be built from source with Node 6?

### ISSUE THREAD

**Issue by mattdsteele** [Microsoft/vscode#40324]
According to the Build From Source instructions [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute), Node 8 is now required. There's also a preinstall check under `build/npm/preinstall.js`.

Is this a hard requirement? My company does not have access to Node 8 (we're planning on staying with 6.12 and jump to 10 when it hits LTS), so this check is precluding me from creating a build.

I'd try commenting out the check and building, but am running into other issues with our corporate proxy. So before I go too far down this path, I want to check whether I have any chance of creating a build with Node 6, or if I should find another approach?

Thanks!

**Comment by joaomoreno** [comment]
There shouldn't be any big blockers preventing it. Except maybe Yarn, which requires Node 8. If you can achieve it, awesome.
