### ISSUE TITLE
[Git] Add better support for rebasing

### ISSUE THREAD

**Issue by KingDGrizzle** [Microsoft/vscode#40320]
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T05:15:38.886Z)
- OS Version: Windows 10 FCU x64

Currently, it seems like VSCode really dislikes rebase pulls. While it does support it (to some extent), you need to manually type `git rebase --continue` after choosing which file you want. Is there any way to make rebases easier?

Steps to Reproduce:

1. Commit changes to a file, but don't push
2. Ask someone to edit and push the same file
3. Run `Pull (Rebase)`, and accept your changes
There seems to be no way of completing the rebase in VSCode after choosing the file version. Either that or I missed it

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
#6614
