### ISSUE TITLE
vscode 安装后重复提示需要安装的问题

### ISSUE THREAD

**Issue by sy-suyin** [Microsoft/vscode#40328]
当 vscode 没有安装在C盘,安装在其他盘时,更新后,vscode 更新文件会更新到C盘,而不是安装的位置,更新完成后,关闭vscode再打开又会再提示需要更新

**Comment by ramya-rao-a** [comment]
Using Google translations: 

> When vscode is not installed on the C drive, installed in other disk, after the update, vscode update file will be updated to C drive, rather than the installation location, after the update is complete, close vscode and then open again will prompt the need to update

**Comment by xinsnake** [comment]
Using Human translations:

> When vscode is installed on drives other than C drive, vscode will still put upgrade files in C drive when performing an upgrade instead of where it is installed. In this scenario if you restart vscode after a successful upgrade it will prompt you to upgrade again.

**Comment by xianghongai** [comment]
管理员权限？
便捷版？

另外一个话题：

古董IT从业者都会告诉你软件要安装在其它盘，系统跑得快。其实，除了Foxmail要安装在其它盘外（数据备份用），其它软件没什么卵用，系统瘫了一样没辙。所以，第一次给C盘分个128G，所有软件默认安装目录，注意去掉全家桶就是了！
