### ISSUE TITLE
main window is blank and no further responses after 1.19

### ISSUE THREAD

**Issue by pennwang23** [Microsoft/vscode#40329]
I think my problem is just as the 'main blank is blank' problem listed on FAQ page of official website.
I tried `code --disable-gpu` `code --disable-extensions`, but doesn't work.
And I tried vscode insider, well it works fine before I sync the settings using 'sync settings' extension, then the same issue happend. Even if I deteled .vscode-insiders located in C:\Users\username.

- Computer: HP 340 G4 | AMD Radeon(TM) R5 M430 | Intel(R) HD Graphics 620

- VSCode Version: 1.19
- OS Version: windows 10 64bit

Steps to Reproduce:

1. updated to 1.19
2. open vscode
3. blank main page, all the operations get no responses.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/10656991/34069477-26b9f652-e28d-11e7-987a-0a3f8df27178.png)

`code --verbose`
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181628.909:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.

[15888:1216/181629.807:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181629.808:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181629.808:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181629.808:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181629.808:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
[15888:1216/181629.808:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.

developer tools errors
![image](https://user-images.githubusercontent.com/10656991/34069507-d72b5b98-e28d-11e7-822f-02f28d551bf1.png)

**Comment by ramya-rao-a** [comment]
Do you still see the issue when running `code --user-data-dir <path to some empty folder>`?
Keeping the blank window open, run `code --status` and share the results with us

**Comment by stvreumi** [comment]
Hello, I have the same issue here.
After I update my vscode around 15:30, 2017/12/16(GMT+8), my vscode open with blank plane and nothing I can select.
I have tried reinstall and it is still the same.
I also using command `code --disable-gpu` `code --disable-extensions`, and it is also give me blank page.😢
- VSCode version: 1.19
- OS version: macOS High Sierra(10.13.2)

- my vscode looks like:
<img width="1280" alt="2017-12-16 3 33 26" src="https://user-images.githubusercontent.com/15280812/34068612-2dbabb9e-e279-11e7-8809-f8df245e5aa2.png">

- But I can open the debugger, it give me the message:
<img width="974" alt="2017-12-16 3 26 09" src="https://user-images.githubusercontent.com/15280812/34068614-3b761e54-e279-11e7-97a2-446c35631b4c.png">

**Comment by ramya-rao-a** [comment]
Thanks for that call stack @stvreumi 
@pennwang23 Can you check if you see the same?

`setCustomTokenColors` is coming when trying to set the theme. cc @aeschli

**Comment by ramya-rao-a** [comment]
@stvreumi Can you answer the questions in https://github.com/Microsoft/vscode/issues/40329#issuecomment-352167047?

**Comment by stvreumi** [comment]
@ramya-rao-a 
Hello, I just reinstall the older version and it's fine for me.
I update to the latest version and the bug still happen.
However, using the command you give ('code --user-data-dir <path to some empty folder>`), I can open vscode with no blank!
But the bug still show up after I quit vscode and restart again.

**Comment by bpasero** [comment]
@stvreumi I moved your issue to https://github.com/Microsoft/vscode/issues/40339 because I do not think it is the same as @pennwang23 

@pennwang23 does it reproduce if you run `code --disable-gpu` ?

**Comment by pennwang23** [comment]
still doesn't work, `code --user-data-dir` works for once, but didn't work after restart. @ramya-rao-a

**Comment by pennwang23** [comment]
yes, it reproduces @bpasero

**Comment by pennwang23** [comment]
thank you guys, I found the problem, there are some errors in my user settings of vscode. very simple syntax errors. @ramya-rao-a @bpasero

**Comment by ramya-rao-a** [comment]
@pennwang23 Can you give us more on information on what errors you found in your user settings?

@stvreumi 

> However, using the command you give (code --user-data-dir <path to some empty folder>), I can open vscode with no blank!
But the bug still show up after I quit vscode and restart again.

Looks like there is an issue with your user settings file just like @pennwang23

**Comment by pennwang23** [comment]
the link in my last post is my settings, could you open it ? unfortunately I can't see where the issue is @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@pennwang23 Yes, I can open that link. I tried all the settings from there and the culprit is `editor.tokenColorCustomizations`.

The default value for this setting is `{}`
But in your settings, the value for this is `null` which is causing the issue.

I can repro the blank window issue by setting `editor.tokenColorCustomizations` to `null` in my settings.

@stvreumi Can you check if you have `editor.tokenColorCustomizations` set to `null` in your settings file (you can find it at ~/Library/Application Support/Code/User/settings.json). If yes, then set it to `{}` instead and then try opening VS Code.

**Comment by stvreumi** [comment]
Hello @ramya-rao-a 
I really set `editor.tokenColorCustomizations` to `null`, in the line 13 of my setting.json
Here is my setting.json:
https://gist.github.com/stvreumi/3d7a3ee4bb474b66f3db9130638929bb
After I change it to `{}` and update to the latest version, I can see my workspace normally.
I think I add this setting because of the extension: *vscode-icons*.

BTW I check the console in the developer tools, there is no error appear.

Thank you @pennwang23

**Comment by ramya-rao-a** [comment]
Thanks for confirming @stvreumi!

cc @bpasero @aeschli

**Comment by pynklu** [comment]
Had the same issues (also using vscode-icons) and confirming that editor.tokenColorCustomizations was indeed set to null after the latest update

**Comment by aeschli** [comment]
duplicate of #40339

**Comment by pennwang23** [comment]
you're welcome. @stvreumi 
thanks for your work. @ramya-rao-a
