### ISSUE TITLE
Python IntelliSense not working in v1.19

### ISSUE THREAD

**Issue by nikhilwason** [Microsoft/vscode#40336]
After the latest update to 1.19.0, Python IntelliSense has stopped working.

- VSCode Version: 1.19.0
- OS Version: mac OS 10.13.2 (17C88)

Steps to Reproduce:

1. Open a Python file, workspace or folder in VS Code
2. Press Ctrl + space - the IntelliSense autocomplete tooltip gets stuck with a loading message.
3. Start typing the name of a variable declared above in the code - no autocomplete tooltip appears.

Reproduces without extensions: No (this issue is related to a Microsoft supported extension)

**Comment by goldenercobra** [comment]
Can confirm, it's highly annoying.
