### ISSUE TITLE
[v-test][PHP] Poorly formatted php does not hit set breakpoints

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4033]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

When debugging php with XDebug, if the code is not correctly formatted a breakpoint will not hit.
Example:
![phpbreakpointpoorformat](https://cloud.githubusercontent.com/assets/12900364/13713473/fb0090cc-e77d-11e5-992b-deb4d17fbca4.JPG)

**Comment by weinand** [comment]
This issue was moved to felixfbecker/vscode-php-debug#25
