### ISSUE TITLE
Type error: cannot read property comments of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40339]
Extracted from https://github.com/Microsoft/vscode/issues/40329#issuecomment-352168035

Hello, I have the same issue here.
After I update my vscode around 15:30, 2017/12/16(GMT+8), my vscode open with blank plane and nothing I can select.
I have tried reinstall and it is still the same.
I also using command `code --disable-gpu` `code --disable-extensions`, and it is also give me blank page.😢
- VSCode version: 1.19
- OS version: macOS High Sierra(10.13.2)

- my vscode looks like:
<img width="1280" alt="2017-12-16 3 33 26" src="https://user-images.githubusercontent.com/15280812/34068612-2dbabb9e-e279-11e7-8809-f8df245e5aa2.png">

- But I can open the debugger, it give me the message:
<img width="974" alt="2017-12-16 3 26 09" src="https://user-images.githubusercontent.com/15280812/34068614-3b761e54-e279-11e7-97a2-446c35631b4c.png">

**Comment by joaomoreno** [comment]
@ramya-rao-a @aeschli Should't the fix be cherry picked to `release/1.19`?

**Comment by aeschli** [comment]
Ported to release/1.19 with https://github.com/Microsoft/vscode/commit/47372c62f73ec2a0a68f02e07f2e18492d2f0962
