### ISSUE TITLE
Insiders: Ctrl+Tab to switch editors of single group brings editor into focus before releasing Ctrl key

### ISSUE THREAD

**Issue by ayyash** [Microsoft/vscode#40333]
- VSCode Version:
1.20.0-insider
- OS Version:
Windows 10 x64

Version 1.20.0-insider
Commit 08ec16001adaab8a86183431f6aec09209caa4ab
Date 2017-12-15T05:15:38.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Recently the behavior of Ctrl+Tab between open editor changed, it switches to the file and puts it in focus, in the past it waited for the release of Ctrl key to do that. This destroys the sequence of the most recently open files in the Ctrl+P panel. Tried few workbench.editor settings but nothing seems to affect this behavior.

**Comment by bpasero** [comment]
@ayyash that should not happen, can you share which editor is stealing focus? Maybe attach a video too?

**Comment by ayyash** [comment]
[https://1drv.ms/v/s!AmCfg5Cb-j0doTUI-_-1YjhSnrp- ](mp4)
This is the behavior, what I expected is that after multiple Ctrl+Tab, the file I am originally on would retain its position, until I release the ctrl, it becomes second. It doesn't, every file jump is treated as a release event

**Comment by bpasero** [comment]
@ayyash I see what you mean. So you are OK that the editor gets focus in the background but you do not like the fact that the editor history (`Cmd+P`) changes due to that?

**Comment by ayyash** [comment]
I'm okay with it as in: it doesn't bother me much, but it would be more consistent with other apps if it doesn't show at all (like in visual studio). But changing history stack is a very nasty thing to do :/ it kind of disorients me and makes me lose focus.
