### ISSUE TITLE
Add a shortcut to toggle Show/Hide "Activity Window"

### ISSUE THREAD

**Issue by RefX32** [Microsoft/vscode#40334]
Add a shortcut to toggle Show/Hide "Activity Window". Example, Ctrl + A would hide activity bar. Pressing it again would show activity bar. This is useful for when you want maximum space on your vs code ui.

**Comment by ramya-rao-a** [comment]
There is a command for this called `View: Toggle Activity Bar Visibility` that you can use from the command pallet.
You can assign any keybinding you want for it.
You can read about how to do so in https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts
