### ISSUE TITLE
how to use github.desktop's git.exe in vscode?

### ISSUE THREAD

**Issue by Aragamiz** [Microsoft/vscode#40335]
i found 2 of git.exe in client.and replace seetings git.path,but can't use.
path lisk these 
"git.path": "C:\\Users\\colla\\AppData\\Local\\GitHubDesktop\\app-1.0.11\resources\\app\\git\\mingw64\\bin\\git.exe",
and
"git.path": "C:\\Users\\colla\\AppData\\Local\\GitHubDesktop\\app-1.0.11\resources\\app\\git\\cmd\\git.exe",
i'm sure that's no invaild escape in these path.how to solve it?it's feature or bug?

**Comment by joaomoreno** [comment]
You actually shouldn't: https://github.com/Microsoft/vscode/pull/35965

Please install [Git for Windows](https://git-scm.com/).
