### ISSUE TITLE
auto save unsaved file not work

### ISSUE THREAD

**Issue by rawbin-** [Microsoft/vscode#40331]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0
vscode-hexdump|sle|1.6.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Please provide more details with reproducible steps.
Also read [Submitting Bugs](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)
