### ISSUE TITLE
snippet

### ISSUE THREAD

**Issue by abeaczg** [Microsoft/vscode#40347]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Closing this issue as there is not enough information in either the title or the description.
Please read [Submitting Bugs](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) and then re-open this issue if you have more information to share
