### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by Y914602509** [Microsoft/vscode#40348]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-runner|for|0.8.5
HdsCppSnippets|hua|0.0.1
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.4

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

Sorry, I meet a problem after updating vscode. It cannot formating the code. What I mean is that it take no response when I want to format the code.

**Comment by jens1o** [comment]
What language do you want to format?

**Comment by Y914602509** [comment]
C++
