### ISSUE TITLE
User settings doesn't update after uninstalling theme

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#40346]
Hello,

- VSCode Version: 1.19.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install any theme (_let's say Atom One Dark_)
2. Set "Atom One Dark" (_using `Ctrl + K + T` or menu_) as main theme
3. VSCode added `"workbench.colorTheme": "Atom One Dark"` to Settings section
4. Without changing theme, uninstall "Atom One Dark"
5. `"workbench.colorTheme": "Atom One Dark"` remains in settings section

Thanks.

**Comment by aeschli** [comment]
Yes, that's expected. A warning will be shown in the settings, and the default theme is used.
But there can be several reasons why the user doesn't want to have the setting removed:
- the extension is temporarily disabled (e.g. by the user or by running code with `--disable-extensions`
- the extension is temporarily uninstalled (e.g. when updating)

For these reasons we rather leave it to the user to manually remove the setting or pick a different theme.

**Comment by dehghani-mehdi** [comment]
You can ask user about removing the entry in setting section or leave that to user (manually removing or whatever).

As user/developer I think it's a bug.

**Comment by aeschli** [comment]
We want to avoid to bother the user with unnecessary dialogs after startup. As with other obsolete settings, the user will see a squiggly line when opening the user settings and can, if he really bothers, remove the settings. Likely, he will pick a new theme, which solves the problem.
Please vote on the issue and I will reopen if many users feel the same.
