### ISSUE TITLE
很好用，但有几点问题

### ISSUE THREAD

**Issue by leigang123** [Microsoft/vscode#40342]
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T05:15:38.886Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

1、debug快捷键跟一般的差的有点大哎
2、类的方法列表每次需要输入@ 好麻烦
3、html跟sublime的不太一样

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
vscode-html-css|ecm|0.1.8
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
php-pack|fel|1.0.1
laravel-blade|KTa|0.0.1
php-docblocker|nei|1.3.2
html5-boilerplate|sid|1.0.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by xinsnake** [comment]
Hi @leigang123 ,

Regarding to your concerns and feedbacks:

1. If you would like to change the keyboard shortcut please refer to the documentation here: https://code.visualstudio.com/docs/getstarted/keybindings
1. Can you please clarify what do you mean by it's combersome to use @ symbol?
1. Can you please clarify what is different in the "html" you are mentioning?

Thanks!

**Comment by hua03** [comment]
你说的的那个类的方法列表默认快捷键是`ctrl+shift+o`，它绑定的指令是`workbench.action.gotoSymbol`

**Comment by xianghongai** [comment]
快捷键这块：

很多都类似ST，如`@`,`#`,`:`。

我这指令都是自己调教，杂糅了vs、st，还有自己按照各符号配置。

当年用st时候就提过，所有插件和额外操作都不要设默认操作方式，全命令行，开发者自己配置，仅提供ctrl cvxwq这类基础操作。
