### ISSUE TITLE
node_modules/vscode-ripgrep/bin/rg ENOENT on arm32 

### ISSUE THREAD

**Issue by apit** [Microsoft/vscode#40340]
- VSCode Version: master@4c00fcd
- OS Version: ubuntu 16.04 armv7l 

Steps to Reproduce:

1. ./scripts/npm.sh install --arch=armhf
2. xiwi ./scripts/code.sh
3. Ctrl + P

Reproduces without extensions: Yes

Snippet from running `./scripts/test.sh`
```
FileSearchEngine
[10764:1216/153640.966998:INFO:CONSOLE(116)] "spawn /home/stupoh/src/vscode/node_modules/vscode-ripgrep/bin/rg ENOENT", source: file:///home/stupoh/src/vscode/out/vs/workbench/services/search/node/fileSearch.js (116)
[10764:1216/153640.971128:INFO:CONSOLE(81)] "Uncaught AssertionError: false == true", source: assert.js (81)
```
```
node_modules/vscode-ripgrep/bin$ file rg
rg: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=5a11692dca33e90dba8e583c1c1eea0713a7d021, stripped

node_modules/vscode-ripgrep/bin$ ldd rg
        not a dynamic executable
```

**Comment by roblourens** [comment]
I don't have an ARM build of ripgrep yet, so that won't work. But if you add the setting `"search.useRipgrep": false`, that will work around it.

**Comment by lilianmoraru** [comment]
It is very easy to get an ARM build of ripgrep(I compiled and run it on a very weak Qualcomm Modem at work - works great).
Do you need help with this?

**Comment by roblourens** [comment]
Actually I was wrong, we do have an ARM build of ripgrep, which I guess you will get if you build vscode from sources on ARM. @apit does it work if you invoke that `rg` binary directly? I haven't tried it myself and I'm not sure what the problem is.

**Comment by apit** [comment]
@lilianmoraru it is part of vscode arm build, but the resulting rg binary is non executable
@roblourens 
```
(xenial)me@localhost:~/src/vscode/node_modules/vscode-ripgrep/bin$ ./rg
-su: ./rg: No such file or directory
```

**Comment by roblourens** [comment]
Does a `chmod +x` help? Since we don't ship an ARM build of vscode, and I don't have an easy way to test this, I'm not going to investigate myself. But if you know what the problem is, I can fix it on my end if that's possible.

**Comment by apit** [comment]
no. 

actually, i just compare the `file` output of rg binary and others in my system. it is linked against non-existent `/lib/ld-linux.so.3`, instead of `/lib/ld-linux-armhf.so.3`.

i was following/adopting instruction in Cross compiling wiki,  perhaps mistake in my part; i'm totally inexperienced in this kind of thing :D. anyway, it works now. yeah!

**Comment by lilianmoraru** [comment]
> actually, i just compare the file output of rg binary and others in my system. it is linked against non-existent /lib/ld-linux.so.3, instead of /lib/ld-linux-armhf.so.3.

This might be because the [build instructions](https://github.com/roblourens/ripgrep/blob/vscode/VSCODE_BUILD.md#linux) are for the `softfp` ABI, not for the `hardfp` ABI.

To install the `hardfp` toolchain and cross-compile with it, you can do this:
```
$ sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross
$ rustup target add arm-unknown-linux-gnueabihf
$ printf "\n[target.arm-unknown-linux-gnueabihf]\nlinker = \"arm-linux-gnueabihf-gcc\"" >> "${HOME:?}/.cargo/config"
$ cargo build --release --target=arm-unknown-linux-gnueabihf
```

Easier with the `musl` target but you need the ARM musl toolchain.

**Comment by apit** [comment]
@lilianmoraru you mean vscode when cross-compiled or build on actual ARM is configured for `softfp`?

**Comment by lilianmoraru** [comment]
@apit The `arm-unknown-linux-gnueabi` is a `softfp` target.
Since the instructions mention it, my guess is that `softfp` is used to build the binary.
Considering that `hardfp` is supported by most ARM devices, I think that should be the main target(`arm-unknown-linux-gnueabihf`).

**Comment by roblourens** [comment]
Thanks @lilianmoraru, I'll use that next time I publish new binarise.

**Comment by lilianmoraru** [comment]
@roblourens I would recommend to actually install `gcc-4.8-arm-linux-gnueabihf` and use `linker = "arm-linux-gnueabihf-gcc-4.8"`(or 4.7) because you might get a newer version than desired.
RPI is on GCC 4.9.3 - to avoid ABI/API incompatibilities between the `glibc` versions, I would recommend to specifically mention version <=4.9.3.

**Comment by roblourens** [comment]
Thanks for the heads up
