### ISSUE TITLE
[feature] Refactor, like find all references and rename them, must be full match

### ISSUE THREAD

**Issue by William-Python-King** [Microsoft/vscode#40341]
- Often I want to rename a variable, function, object or class.
- I use F2 but it usually rename an identifier in one file.
- It cannot rename all references and some are missed so I have to search and rename it manually.
- I really need this feature because my project are big and complex.

**Comment by ramya-rao-a** [comment]
These features are implemented by different extensions for different languages. Find the extension that is providing these features for the language you are working on and log an issue in the repo for that extension
