### ISSUE TITLE
[html/css/scss/less] Textual suggestions missing in 1.19.0

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#40349]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.0
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
vscode-icons|rob|7.19.0

I set
```JSON
"[html]": {
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    }
```
In 1.18.1, vscode suggests strings, however, it does not work in 1.19.

---
1.18.1
![181](https://user-images.githubusercontent.com/24318019/34071847-199afec8-e2b8-11e7-8405-a76ac5689bbd.png)
1.19
![190](https://user-images.githubusercontent.com/24318019/34071853-28e0e47e-e2b8-11e7-9de5-132d321355c6.png)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes

**Comment by jrieken** [comment]
Problem is that there are providers from the html-extension that all return something.
