### ISSUE TITLE
Git Host Key Verification failed/Open Git Log does nothing

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#40350]
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T05:15:38.886Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
coldfusion|ili|0.0.11
search-node-modules|jas|1.2.0
wordcount|ms-|0.1.0
material-icon-theme|PKi|3.1.0
htmlescape-vscode-extension|ray|0.0.4
spellchecker|swy|1.2.13
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. In the Git UI, select Pull
2. The error, Git Host Key Verification failed
3. Select "Open Git Log"
4. Nothing happens.

So I'm sure the issue is my fault, but asking for the log is doing nothing in VSC.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
There is a bug in the output pane right now in `master` which prevents `Open Git Log` from opening. Closing as a duplicate. cc @sandy081
