### ISSUE TITLE
Update Information on Fedora

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/vscode#40356]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.14.3-300.fc27.x86_64

---

Steps to Reproduce:

1. Install code through the official dnf repo
2. Check for updates in GNOME Software

Reproduces without extensions: Yes

VSCode can be successfully updated through `gnome-software` however it is shown under 'OS Updates' along with libraries rather than as an Application, I suspect the appdata.xml is missing some required information

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37813
