### ISSUE TITLE
Environment variables on Windows should not be case-sensitive

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode#40358]
- Version 1.19.0
- Commit 816be6780ca8bd0ab80314e11478c48c70d09383
- OS Version: Windows 10.0.16299.64

Steps to Reproduce:

1. On a machine where `WINDIR` is actually `windir` (seems to have changed case on Win10 or at some point in the past), use "${env:WINDIR}" in .vscode/launch.json, e.g.: ${env:WINDIR}/System32/WindowsPowerShell/v1.0/powershell.exe
2. Launch the task. Debug output says /System32/... is not found (note no prefix, e.g. C:/Windows)

Environment variables on Windows are not case-sensitive, and they change. For example, my PATH is always PATH. I often override this as one of my first machine set up steps. It was always PATH in the past, as it is on other platforms. Windows 10 or perhaps 8 changed the case. So developers across Windows versions can't use a checked in launch.json (or tasks.json, etc.)? That's not a practical expectation.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Dup of #4895

**Comment by heaths** [comment]
Thanks. I looked prior but didn't see that one.
