### ISSUE TITLE
IntelliSense Stops Working After a While

### ISSUE THREAD

**Issue by serioth** [Microsoft/vscode#40367]
- VSCode Version: 1.19.0
- OS Version: Windows 10 Pro, 64-bit

Steps to Reproduce:

1. Create a new folder
2. Create index.js file
3. Type: "var http = require('http');"
4. Type: "http." and see what IntelliSense comes up with

After first creating a file, it works as expected, firing up all the methods and variables belonging to the http module.

After a while (a few minutes), this stops working. No IntelliSense suggestions come up for the http module, or any other node module I have require'd in my file.

I have not been able to find a pattern, or the reason for why it does not work.

I have tried:
* Reinstalling Visual Studio Code
* Reopening the file/folder outside a workspace
* Disabling all extensions, restarting VSC, then reopening the files

Reproduces without extensions: Yes

**Comment by hua03** [comment]
I encountered the same problem with you. You can try to run node to solve it. But it sometimes fail. This is my solution #40332 .

**Comment by serioth** [comment]
@hua03 I tried it, but unfortunately it did not work. It seems you were right to reopen your ticket.

I am not familiar with the process here. Will a VSC technician get back to us?

**Comment by hua03** [comment]
Yes, Near Christmas, they may have a holiday.

**Comment by mjbvz** [comment]
Can you please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. From a js file, run the `TypeScript: Open TS server log` vs code command

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by hua03** [comment]
I noticed when starting vscode, it will cache dts file.
Whether it is because of the need to cache too many files, causing this service to start a bit slow.

**Comment by hua03** [comment]
It happened again this afternoon.I read the log file, which add the following:
![20171219174345](http://opd59bmxu.bkt.clouddn.com/20171219174345.png)

**Comment by mjbvz** [comment]
@hua03 Look in the `tsserver.log` file too. That has the full server logs.

The `ti-xxx.log` files are typings installers logs. I believe the messages in your screenshot are expected in this case.

**Comment by hua03** [comment]
@mjbvz  Sorry, this is tsserver log [tsserver.log](http://opd59bmxu.bkt.clouddn.com/tsserver.log).

**Comment by hua03** [comment]
@serioth  Here's another way to avoid this problem. That is, manually installing @types file in the project.Like this:

```shell
npm i --save-dev @types/node

//or
yarn add -D @types/node
```
@mjbvz I noticed that the @types file is globally installed.I suggest that @type file associated with the library or framework is only installed in the project, not installed in the global environment.Only language-based @types files remain in the global environment, like `JS`, `es6`.

**Comment by mjbvz** [comment]
@serioth Do you still see the original issue in  the latest vscode insiders build? 

@hua03 The types are installed globally in order to not pollute your local `node_modules`. It is just a shared cache of typings file that we pull from as needed

**Comment by hua03** [comment]
@mjbvz you are right. I ignored this.
