### ISSUE TITLE
Format Code appears to indent differently than expected

### ISSUE THREAD

**Issue by brennanMKE** [Microsoft/vscode#4036]
I'd like to know if this can be configured with a workspace setting. I have tried adjusting `editor.wrappingIndent` but it does not appear to influence behavior. Below I have examples that you can try yourself.

Either there is a bug in configuring workspace settings or there is no way to configure this behavior. My team is using different IDEs for TypeScript and I want to make my settings match what the rest of the team is expecting.

### My .vscode/settings.json

```json
{
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.wrappingIndent": "same"
}
```

### Extra Indenting (Things.ts)

```ts

export let Things = [{
  Hat: 'hat',
  Glove: 'glove',
  Umbrella: 'umbrella'
},
  {
    Salad: 'salad',
    Burrito: 'burrito',
    Pie: 'pie'
  }];
```

### Expected Indenting (Things.ts)

```ts
export let Things = [{
  Hat: 'hat',
  Glove: 'glove',
  Umbrella: 'umbrella'
},
{
  Salad: 'salad',
  Burrito: 'burrito',
  Pie: 'pie'
}];
```

**Comment by dbaeumer** [comment]
This is a problem with the TS formatter we use. Moving the issue.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7503
