### ISSUE TITLE
Can you provide Linux commands support in vs code terminal in windows?

### ISSUE THREAD

**Issue by VenPot** [Microsoft/vscode#40369]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by smuuf** [comment]
Why would they do such a thing? Why should it be editor's responsibility to simulate non-native command-line tools for you? *Just use a different terminal.*

**Comment by VenPot** [comment]
Thanks for the comment. What terminal do you suggest and how do you
configure it to work with vs code?Appreciate your time!

On Dec 17, 2017 7:05 AM, "Přemysl Karbula" <notifications@github.com> wrote:

Why would they do such a thing? Why should it be editor's responsibility to
simulate non-native command-line tools for you? *Just use a different
terminal.*

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/40369#issuecomment-352250944>,
or mute the thread

**Comment by smuuf** [comment]
If you're on Windows and want your terminal be more *linux-like*, you can use*, for example,* Git's `MINGW64` shell *(if you have Git installed)*. To use that as terminal in vscode, just have something like this in your vscode settings:

```
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
```

***If you use WSL*** you should be able to use "native" Linux shell inside your Windows installation of Visual Studio Code. Try looking here for more info: https://github.com/Microsoft/vscode/issues/22317

**Comment by VenPot** [comment]
@smuuf Perfect ,  I am closing the issue 

Here are some other tips i came across while researching the issue. sharing in case if there are others looking for the same answer-

"Press and hold Ctrl + ` to open terminal. Inside terminal type 'bash' without the quotations to use gitbash in terminal. Note: Make sure you have gitbash installed on your machine.

If you wish to use powershell again, just type 'powershell' without the quotations in terminal. To use Windows command line type 'cmd' in terminal.

The setting you choose will be used as your default."
