### ISSUE TITLE
Feature - Most Recently Used npm scripts

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#40361]
Feature request

When using the command palette to run npm scripts, they are alphabetized. OFten we run the same 1 or 2 repeatedly. It would be nice if the most frequently run script appeared first (once VS Code has seen them a few times). Kind of like how the most recently used files show up

**Comment by ramya-rao-a** [comment]
Are you referring to options you get when running the command `Tasks: Run Task`?

**Comment by johnpapa** [comment]
No. Sorry. running command palette then type “npm” to get a list of the npm run scripts.

**Comment by usernamehw** [comment]
@johnpapa Isn't this an extension contribution?

**Comment by dbaeumer** [comment]
Yes this is an extension contribution maintained by @egamma. The task runner does use an MRU list.

**Comment by johnpapa** [comment]
Ah. Didn’t realize where it came from. I’ll close this and post there as an idea
