### ISSUE TITLE
Linux: Signal better startup notification when app is truly loaded

### ISSUE THREAD

**Issue by ZanderBrown** [microsoft/vscode#40363]
* VSCode Version: Code 1.18.1 (929bacb, 2017-11-16T18:34:22.110Z)
* OS Version: Linux x64 4.14.3-300.fc27.x86_64

Steps to Reproduce:

* Open VSCode
* Immediately interact with the window of another application
* Watch notifications

Reproduces without extensions: Yes

Linux has [startup notifications](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/) to signal when an application is ready. In GNOME3 this is surfaced as a notification when a window opens in the background.

It seems that code sends the signal as soon as a window is mapped, ideally, it should only be sent when the window is ready to accept input

**Comment by bpasero** [comment]
@ZanderBrown I am not really understanding what you are asking for...

**Comment by ZanderBrown** [comment]
[The GNOME Foundation has some guides](https://developer.gnome.org/integration-guide/stable/startup-notification.html.en) which may [better explain](https://developer.gnome.org/platform-overview/stable/dev-launching-startupnotify.html.en)

When an application is started it may use a [startup-notification](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/) to signal that it is ready. In most instances this information is used for things like a busy cursor. However in GNOME (and probably other DEs as well) if the application is loading in the background (e.g. the user is actively working with a GitHub issue in Firefox whilst vscode starts) the startup-notification hint/signal is used to show a notification to the user:

![screenshot from 2017-12-17 09-39-28](https://user-images.githubusercontent.com/17074021/34078529-0acf3538-e314-11e7-8eef-8460d1e8395c.png)
(The title of 'Visual Studio Code' is taken from the desktop file, as is the icon-name, whilst the 'Visual Studio Code' in quotes is the title of the window when gnome-shell received the startup-notification)

If the user neither interacts with code or notification interact with the notification moved to the tray

![screenshot from 2017-12-17 10-30-29](https://user-images.githubusercontent.com/17074021/34078637-f5375492-e315-11e7-9876-8bb64863c64d.png)

Where it follows the current title of the window (Here VSCode has restored a previous folder)

What I'm suggesting is that VSCode delays this signal to the DE until the window is genuinely 'ready' with the workspace ready for interaction
