### ISSUE TITLE
Git view dies when editing a large TS project

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#40365]
- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: OSX Sierra

Steps to Reproduce:

1. Open Typescript project. Build it using 'gulp local'
2. Edit some files in tests/cases/compiler
3. Run 'gulp runtests'
4. Run 'gulp baseline-accept'

The git view seems like its dead. The buttons show click animation but no actions are taken. The terminal works with 'git status and git add' but built in git view is unresponsive.

Typescript has a large number of files in tests/baselines/** folder. 

It seems like the git view does a lot more than one would expect. E.g `git status` works super fast but git view shows the loading line for a long time. Git push, pull, commit all work fast from command line but take forever in git view or git view dies without any error to user.

Explorer window cannot show diff between files as well

**Comment by joaomoreno** [comment]
How fast does `git status` run? How many changes (modified, untracked, etc) are there in total?

**Comment by nojvek** [comment]
`Git status finishes in less than a second`. Total of 7 modified + untracked files. 

Works well for 5 mins. After a new commit + push through UI, or clicking the sync button on bottom bar seems to crash something. I don't see anything standing out in git log too.

**Comment by joaomoreno** [comment]
How about in the devtools console?

**Comment by nojvek** [comment]
```
[Extension Host] Error: EMFILE: too many open files, open '/Users/nojvek/git/TypeScript/tests/baselines/reference/project/referenceResolutionRelativePathsRelativeToRootDirectory/amd/diskFile1.d.ts'
```

It seems ripgrep might be opening too many files somehow causing git to have issues

```

console.ts:123 [IPC Library: Search] Error: spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg EAGAIN
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by nojvek** [comment]
@joaomoreno How does one re-open the issue?

This problem is very evident with Typescript repo. Just build + do a simple ctrl+shift+f search and git will stop working. Pressing refresh button won't work anymore too.

**Comment by joaomoreno** [comment]
@nojvek Have you tried increasing the file count limit? https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

**Comment by nojvek** [comment]
I did and that somewhat alleviates the problem, but I guess Typescript has too many files in its baseline folder that it does die at times. The issue though is why does find + search break git, that it becomes unresponsive, when `git status` in vscode console works totally fine.

**Comment by joaomoreno** [comment]
So, running a find and then running `git status` works fine?

**Comment by nojvek** [comment]
That works totally fine.

I really wish @vscodebot would at-least give a warning before It closed an issue automatically. 

Feel like its too aggressive. I also understand vscode team members have a 100 million other things to do as well.

**Comment by joaomoreno** [comment]
@nojvek No worries, we're still paying attention.

**Comment by nojvek** [comment]
This is no longer happening for me. Whatever magic you magic elves have been doing is working. Thank you.
