### ISSUE TITLE
Terminal does not like UTF8

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode#40362]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.9.0-4-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
vscode-intelephense-client|bme|0.8.2
ayu|tea|0.10.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Copy and paste some utf8 in terminal (trying to type ctl+shift + u[CODEPOINT] doesnt work)
2. Hold arrow keys repeatedly left then right over text.

Reproduces without extensions: Yes/No

![vscode-terminal-ascii](https://user-images.githubusercontent.com/5885195/34073975-ef940092-e2f9-11e7-964c-56ca5b6f25e6.gif)
![vscode-terminal-utf8](https://user-images.githubusercontent.com/5885195/34073977-f67e05ba-e2f9-11e7-8f41-34ed6f594ec3.gif)

**Comment by Tyriar** [comment]
Can you paste in the 'tect' text to the issue that's causing the problem

**Comment by bmewburn** [comment]
тест

**Comment by Tyriar** [comment]
Interestingly this works just fine on macOS, I wonder if this is your shell misbehaving or not having the right config? Which distro/version are you using? Also could you share the output of `echo $LANG`

**Comment by bmewburn** [comment]
I'm on Debian 9 VSCode 1.19.1 with default shell config. A native terminal works fine, the `$LANG` value has a different locale than the integrated one -- `en_AU.UTF-8` on native, `en_US.UTF-8` on integrated.

**Comment by Tyriar** [comment]
I'd expect en_US.UTF-8 to work as that's what most terminals have. It works fine for me on Ubuntu 17.10 as well. Note that I'm testing with just `echo 'тест'` as I don't have PHP installed.


![image](https://user-images.githubusercontent.com/2193314/34442897-2ece2e5c-ec7a-11e7-956d-f53d84ac1297.png)
