### ISSUE TITLE
VSCode 自动格式化时会吃掉几行代码

### ISSUE THREAD

**Issue by zhcpku** [Microsoft/vscode#40376]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.9.0-deepin13-amd64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
code-settings-sync|Sha|2.8.7
markdown-latex-renderer|agu|0.0.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
mdmath|goe|2.0.7
python|ms-|0.9.0
cpptools|ms-|0.14.4
java|red|0.16.0
code-spell-checker|str|1.6.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
vscode-todo-highlight|way|0.5.11
markdown-pdf|yza|0.1.7

---

Steps to Reproduce:

1. 在一个窗口里长时间写代码
2. 设置"editor.formatOnSave": true
3. 看运气（不能稳定重现）

Reproduces without extensions: No

**Comment by zhcpku** [comment]
补充说明一下，出现问题的时候大多在代码写到600多行的时候

**Comment by ramya-rao-a** [comment]
@zhcpku What language are you using? Is it typescript/python/C++?

**Comment by zhcpku** [comment]
@ramya-rao-a python & Java，各自出现过一次

**Comment by xianghongai** [comment]
我这今年所有项目都是用的vscode，还没出现过这种问题，吃掉是丢失？还是因为注释、空行、代码块模式化造成？应该不是编辑器问题。
