### ISSUE TITLE
a

### ISSUE THREAD

**Issue by Davaakhuux** [Microsoft/vscode#40375]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by jens1o** [comment]
b

**Comment by ramya-rao-a** [comment]
c?

**Comment by ramya-rao-a** [comment]
Closing this issue as there isn't enough information in the title or description to work on.
