### ISSUE TITLE
mssl is not working 

### ISSUE THREAD

**Issue by nareshnookal-devrabbit** [Microsoft/vscode#40378]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 3.16.0-77-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
git-easy|bib|1.9.1
plsql|cas|0.0.3
es7-react-js-snippets|dsz|1.3.0
svn-scm|joh|1.4.5
hg|mrc|1.2.3
mssql|ms-|1.3.0
team|ms-|1.122.0
git-autoconfig|shy|0.0.1
perforce|sle|3.0.0
react-beautify|tai|0.3.0
ReactSnippets|xab|1.7.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
What is msssl?
Please provide more details and reproducible steps while logging an issue.
Also read [Submitting Bugs](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)
