### ISSUE TITLE
Add default setting for panel location

### ISSUE THREAD

**Issue by koaleksa** [Microsoft/vscode#40373]
**Feature request**

Newest version (0.19) deprecated ```workbench.panel.location``` setting. Position now defaults to ```bottom```. Please add setting to decide default panel location.

Since vscode added possibility to move panel to ```right``` i have exclusively used it that way and the newest behavior, even though i understand it's intended and it takes only one click to move the panel to desired position, is annoying because the panel pops unexpectedly on the bottom even though i almost never want it there.

**Comment by isidorn** [comment]
This is a fair feature request. We accept PRs that fix this.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L638

**Comment by pfongkye** [comment]
Hi @isidorn 
I could take a look at this one if no one else is working on it.

**Comment by isidorn** [comment]
@pfongkye great. Make sure the setting is only used as the default value. The value from the storage service should have priority. Due to that I would call this setting "workbench.panel.defaultLocation"

**Comment by koaleksa** [comment]
Thanks for accepting this. Much appreciated!

**Comment by isidorn** [comment]
@pfongkye thanks for the PR, I will review in the next couple of days. No tests for this are needed and it is not so easy to test. Thanks for offering though.
