### ISSUE TITLE
Release Notes Page isn't opening

### ISSUE THREAD

**Issue by ashraf-jabr** [Microsoft/vscode#40374]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
markdown-toc|Ala|1.5.6
ignoregit|And|1.0.1
vscode-database|baj|1.2.0
vscode-refresh-html|baj|0.0.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
angular2-snippets|dan|1.0.16
vscode-markdownlint|Dav|0.12.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
beautify|Hoo|1.1.1
copy-markdown-as-html|jer|1.0.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.0.12
markdown-shortcuts|mdi|0.8.1
font-awesome-codes-html|med|0.0.7
Angular-BeastCode|Mik|5.1.11
python|ms-|0.9.0
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0
java|red|0.16.0
nativescript|Tel|0.7.2
html-preview-vscode|tht|0.1.1
python|tht|0.2.3
Angular2|UVB|0.4.1
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
gitblame|wad|2.2.0
markdown-pdf|yza|0.1.7
html-css-class-completion|Zig|1.14.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Open VSCode
2.Click Release Notes from Help Menu

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
Any errors from the console? (Help -> Toggle Developer Tools -> Console)?
