### ISSUE TITLE
Javascript typing tips

### ISSUE THREAD

**Issue by agsea** [Microsoft/vscode#40379]
Now, i want to konw how can i get js snippets from a js file (generally, it's a js library, such as the three.js) while i'm working in other js file. As far as i can see, existing plugings for js in vscode not has the function.

**Comment by RobertAKARobin** [comment]
Possibly duplicated by https://github.com/Microsoft/vscode/issues/40392

**Comment by mjbvz** [comment]
Please provide a code example and describe the expected behavior

**Comment by GoToSea** [comment]
[code_example.zip](https://github.com/Microsoft/vscode/files/1577560/code_example.zip)

**Comment by GoToSea** [comment]
Here is sample code and two shortcut of the expected behavior in the 'code_example.zip' file.

[code_example.zip](https://github.com/Microsoft/vscode/files/1577582/code_example.zip)

**Comment by mjbvz** [comment]
Duplicate of #26338
