### ISSUE TITLE
Hide file extensions in editor tabs

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#40386]
It would be great to have the option to display only the file names in editor tabs — removing the extensions.

This is preferable for those of us who use icons — removing the redundancy of a "JS" icon combined with`.js`, for example.

**Comment by vinhpz** [comment]
I think `"workbench.editor.showIcons": false,` will help you

**Comment by Haozun** [comment]
and  "workbench.editor.tabSizing": "shrink", helps a little

**Comment by jabacchetta** [comment]
Thanks for the suggestions. Unfortunately neither of those are what I'm looking for.

**Comment by jabacchetta** [comment]
@bpasero I can work on this in the near future if this is a PR that would be accepted?

I'm thinking a `"workbench.editor.showExtension": false` setting?

**Comment by bpasero** [comment]
I am merging this into https://github.com/Microsoft/vscode/issues/43806 which is the more general request.
