### ISSUE TITLE
Automatic import feature + Automatic type acquisition = ugly imports

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#40385]
- VSCode Version: 1.19.0
- OS Version: Windows 10 16299.125

Steps to Reproduce:

1. Create a basic JS project, with a default `package.json` and a blank `index.js`
2. Install a random dependency via NPM (e.g. `graphql`)
3. Type in `require('graphql');` in index.js
4. Summon IntelliSense, and pick one of the suggested types (e.g. `GraphQLID`)
5. You'll get a really ugly import, like:

```javascript
import { GraphQLID } from '../../../../AppData/Local/Microsoft/TypeScript/2.6/node_modules/@types/graphql/type/scalars';
````

Added to the top of your file.

This is a pretty broken experience, 😕 for a number of reasons:

1. It's importing from the .d.ts file, instead of importing from the actual library it refers to: 

```javascript
import { GraphQLID } from 'graphql';
```

2. It's importing a .d.ts file _in JavaScript_;
3. It's using `import { } from '...'` syntax, even though I never specified that ES6 imports were valid. (e.g. on my `jsconfig.json` file) Running this, for example, on the current version of node without special flags will result in an error;
4. It's using a relative path, that's specific to where the project is located on my machine, and probably won't work elsewhere
5. It's exposing a OS-specific and VS Code-specific temporary directory

I understood what happened and simply removed the auto-generated lines, however an inexperienced JavaScript developer, without knowledge of the TypeScript ecosystem and of VS Code features would probably be really confused. It's also possible that while editing a large, existing, file, the newly added line wouldn't be easily spotted.

Both automatic type acquisition and automatic imports are really nice, useful features, but perhaps the default settings of both should prevent accidental triggering like this.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20757
