### ISSUE TITLE
Markdown outline preview and file manage function ,just i need, thank you.

### ISSUE THREAD

**Issue by qingkong1998** [Microsoft/vscode#40383]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Outline for the markdown file or for the markdown preview file?
What do you mean by "file manage function"?

**Comment by qingkong1998** [comment]
Markdown文件大纲，就像MsWord或者文件资源管理器一样，对单个的Markdown文件可以有PDF文档那样的标签

**Comment by mjbvz** [comment]
Try using `Go To Symbol`: https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol

This lists all headings in markdown files and let's you quickly jump to them
