### ISSUE TITLE
editor.lineNumbers description needs to be updated to include the new "interval" setting. 

### ISSUE THREAD

**Issue by dhaynespls** [Microsoft/vscode#40398]
- VSCode Version: 
1.19.0
816be6780ca8bd0ab80314e11478c48c70d09383
x64
- OS Version: Fedora 26

A new toggle for the lineNumbers setting was added but the string wasn't updated to include that new option. The absence is slightly confusing.

See:
https://github.com/Microsoft/vscode/blob/b5ef98e6015d201104df4798d6859afdd02df958/src/vs/editor/common/config/commonEditorConfig.ts#L214

Steps to Reproduce:

1. Open the settings.json and look at the editor.lineNumbers description. 

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Fixed by PR #40388
