### ISSUE TITLE
Theme color reference documentation missing one prop

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#40390]
https://code.visualstudio.com/docs/getstarted/theme-color-reference#_lists-and-trees

Missing: `list.inactiveFocusBackground`

**Comment by bsvipas** [comment]
Also there's is missing color references for new function `Developer: Show running extensions`.

**Comment by aeschli** [comment]
@bsvipas These are unrelated issues. Please file a separate issue to make 'Show running extensions' themable.

**Comment by bsvipas** [comment]
@aeschli Okey. Thank you!

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-docs/commit/67697a7543006c8670bc355112c1ec05103f40f5

**Comment by egamma** [comment]
Removing the recovery milestone since this is a vscode-docs change.
