### ISSUE TITLE
Suggestions continue to show up, despite disabling

### ISSUE THREAD

**Issue by RobertAKARobin** [Microsoft/vscode#40392]
- VSCode Version: 1.19.0
- OS Version: Mac 10.13.1

Steps to Reproduce:

1. Create a new JS file
2. Type `express.static(`
3. Observe a suggestion explaining middleware show up:

![screen shot 2017-12-17 at 3 04 02 pm](https://user-images.githubusercontent.com/6268177/34083981-d4a8338a-e33e-11e7-9c66-f7dba334559f.jpg)

Here are my current settings:

```json
{
	// Text formatting
	"editor.fontSize": 11,
	"editor.wordWrap": "on",
	"editor.scrollBeyondLastLine": false,
	"window.zoomLevel": 0,
	
	// Whitespaces
	"editor.renderWhitespace": "all",
	"editor.insertSpaces": false,
	"editor.detectIndentation": false,
	"files.insertFinalNewline": true,

	// VSC-specific stuff
	"editor.minimap.enabled": false,
	"workbench.startupEditor": "newUntitledFile",

	// Trying to disable most kinds of autosuggest
	"workbench.tips.enabled": false,
	"html.autoClosingTags": false,
	"editor.lightbulb.enabled": false,
	"javascript.nameSuggestions": false,
	"jsDocCompletion.enabled": false,
	"editor.suggestOnTriggerCharacters": false,
	"editor.wordBasedSuggestions": false,
	"editor.quickSuggestions": {
		"other": false,
		"comments": false,
		"strings": false
	}
}
```

Reproduces without extensions: No. However, I do not have any extensions installed.

**Comment by GoToSea** [comment]
I think we're not talking about the same problem.

**Comment by mjbvz** [comment]
Those are parameter hints. Set `"editor.parameterHints": false` to disable them
