### ISSUE TITLE
ui is screwed up

### ISSUE THREAD

**Issue by Katthewm** [Microsoft/vscode#40393]
I am new to coding and am trying to follow tutorials, but I cant even start because my ui looks and acts completely different. How the heck do I fix this? When I try to find solutions people say to go to the Tool menu, but I don't have that?!?!? Any help would be appreciated.
![capture](https://user-images.githubusercontent.com/34632839/34084155-88e9e1de-e341-11e7-9c19-b882366e3f68.PNG)

**Comment by dhaynespls** [comment]
Could you link the tutorial? It's probably not an issue with the project but with the instructions that you're looking at being vague.

**Comment by ramya-rao-a** [comment]
For VS Code, you can start with these [introductory videos](https://code.visualstudio.com/docs/getstarted/introvideos) or the [Getting Started Docs](https://code.visualstudio.com/docs)
You can follow that up with [VSCode Tips and Tricks](https://code.visualstudio.com/docs/getstarted/tips-and-tricks)
