### ISSUE TITLE
Visual Studio Code should natively support css, razor, and xml formatters

### ISSUE THREAD

**Issue by luronumen** [Microsoft/vscode#40391]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. Try to format (Alt+Shift+F) an css or razor (cshtml) or xml (csproj) file: Sorry, but there is no formatter for 'filetype'-files installed.

Important Notes:
- This issue does not happening with other very common file types where formatters are natively supported: cs, json and js

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
There is no out of the box formatting support for cs either. For you it seems to be coming from the c# extension that you have installed.

The only languages that have formatting support out of the box are ts/js, html and json.
