### ISSUE TITLE
Breaks with xml file bigger than 55MB

### ISSUE THREAD

**Issue by oscarlagatta** [Microsoft/vscode#404]
I opened an XML file without knowing was that big, VS Code broke immediately couldn't open that file xml file.

**Comment by msallin** [comment]
May or the same as #139 & #177.

**Comment by alexandrudima** [comment]
Indeed, it most likely runs OOM because the file is being sent over to the two web workers. I most likely introduced a regression in this area, where before files above a certain size wouldn't travel to the web workers at all. Let's track this either in #139 or #177,
