### ISSUE TITLE
 不支持vue语法格式

### ISSUE THREAD

**Issue by chenli8** [Microsoft/vscode#40403]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
git-easy|bib|1.9.1
path-intellisense|chr|1.4.2
beautify|Hoo|1.1.1
debugger-for-chrome|msj|4.0.0
vuehelper|oys|0.1.0
view-in-browser|qin|0.0.5
vscode-icons|rob|7.19.0
vue-ls-snippets|van|0.0.5

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
You can install the vetur extension for Vue support
