### ISSUE TITLE
SCM telemetry events are not prefixed

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#4040]
SCM telemetry events used to be prefixed with `workbench.action.git.*`, this made it possible to track all SCM activity based on the event name prefix. Now I noticed it's not the case anymore, causing all of our reports related to SCM usage to drop. I will be reprocessing those but I think we need to get back to prefix those events for easier processing in the future. 

I suggest something as `workbench.action.scm.*`. 

@seanmcbreen for fyi

**Comment by joaomoreno** [comment]
Nothing really changed recently here, the change *if it happened* was already some time ago.
