### ISSUE TITLE
CTRL+F 搜索后 焦点不在代码上了 在搜索框上 F3很尴尬

### ISSUE THREAD

**Issue by lupin888** [Microsoft/vscode#40407]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.17.0
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
luaide|kan|0.3.7
python|ms-|0.8.0
change-case|wma|1.0.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by xianghongai** [comment]
这是正常的逻辑。

多个关键字匹配，F3直接下一个位置，而不是焦点。

如果是代码获得焦点，发生了新的修改，搜索如何再次缓存？只能再次CTRL+F某关键字。
