### ISSUE TITLE
Git diff not working for UNC paths 

### ISSUE THREAD

**Issue by yuugou727** [Microsoft/vscode#40408]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
htmltagwrap|bra|0.0.6
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.0.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
code-runner|for|0.8.5
beautify|Hoo|1.1.1
vscode-cdnjs|Jak|0.14.3
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.5
vuehelper|oys|0.1.0
material-icon-theme|PKi|3.1.0
LiveServer|rit|3.0.1
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. Make some change after git commit.
2. The Git window cannot show difference and comparison ( or lost it? ). But the command-line `git diff` still works correctly.

![default](https://user-images.githubusercontent.com/22387083/34088216-cdb1ae4a-e3e2-11e7-8c7c-cd2fd295e8a8.PNG)

**Comment by mkszepp** [comment]
i have the same problem, but only with UNC-Folders like (\\localhost\projectname).

**Comment by joaomoreno** [comment]
@yuugou727 Is your issue also related to UNC folders?

**Comment by yuugou727** [comment]
@joaomoreno Probably. My project is on a remote LAN path like \\192.168.X.X\dev\. I also found same inline-diff issue which @mkszepp mentioned.

**Comment by joaomoreno** [comment]
@yuugou727 @mkszepp Was this working in 1.18 for you guys?

**Comment by mkszepp** [comment]
yes, in 1.18 it was working

**Comment by joaomoreno** [comment]
Code review: UNC paths only work properly for `file:` resources. So, in [the fix](https://github.com/Microsoft/vscode/commit/5f87a2ad405b43eca3dac2ac90464278b80f06b6), if we see a `git:` resource, we must get the path from the `path` component which is JSON stringified and URL encoded.
