### ISSUE TITLE
[BUG] when i renaming the filename, it trigger my keyboard shortcut incorrectly!

### ISSUE THREAD

**Issue by pspgbhu** [Microsoft/vscode#40415]
- VSCode Version: 1.19.0 (1.19.0)
- OS Version:  macOS Sierra 10.12.6 (16G1036)

Steps to Reproduce:

#### 1. I bind shortcut `a` to create new file
```json
{
    "key": "a",
    "command": "explorer.newFile",
    "when": "explorerViewletVisible && filesExplorerFocus"
  }
```
#### 2. focus file explore and then to rename a file
when i input letter `a`, it will trigger `explorer.newFile` event, rather than go on to input.

**This problem occured after version 1.190**

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
You need to add `&& !inputFocus` to your `when` clause.

**Comment by pspgbhu** [comment]
i have add `&& !inputFocus`, But it is not ok.
```
{
    "key": "a",
    "command": "explorer.newFile",
    "when": "explorerViewletVisible && filesExplorerFocus && !inputFoucs"
  }
```

If I delete this shortcut, there is no problem when I rename a file. But if bind this rule, the problem always occurred.

**Comment by joaomoreno** [comment]
You have a typo: `inputFoucs`. It's `inputFocus`.

**Comment by pspgbhu** [comment]
@joaomoreno oh! thank you very much!

**Comment by mcdado** [comment]
As I commented [here](https://github.com/Microsoft/vscode/issues/40511#issuecomment-356693581), I think this keymap is redundant, and my suspect is that it is created by the Atom Keymap extension.
