### ISSUE TITLE
The color of a changed file when the Explorer is in focus

### ISSUE THREAD

**Issue by chimit** [Microsoft/vscode#40410]
- VSCode Version: 1.19.0 (1.19.0)
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Make any changes in a file (Git project)
2. Click on the file in the Explorer

Reproduces without extensions: Yes

Explorer is not in focus:

![2017-12-18 11 21 27](https://user-images.githubusercontent.com/839349/34088658-a46730a2-e3e5-11e7-8e2d-ea6ad016af99.png)

Explorer is in focus:

![2017-12-18 11 21 35](https://user-images.githubusercontent.com/839349/34088657-a4424292-e3e5-11e7-9f80-c3a7b8ecfea3.png)

The file name color is changed to normal white and doesn't clearly indicate that the file was changed. Maybe it would be better to always leave it yellow.

**Comment by jrieken** [comment]
> The file name color is changed to normal white and doesn't clearly indicate that the file was changed

Well, there is a big 'M' next to the name :-) The reason for falling back to white is that most highlight colours don't match well with the 'modified'-color... Unsure if the label itself is support this (@bpasero) and I would align with that.

**Comment by bpasero** [comment]
I would stay away from changing the color when the item is selected, I think that is the reason why we have the badge next to the name. In most cases the foreground color will not work with the background color of the selection color in the list/tree widget.

**Comment by jrieken** [comment]
Closing to align with the label behaviour and because of the aforementioned reasons.
