### ISSUE TITLE
Need help with several theme color props

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#40419]
How to reproduce these color props?

`editorGroup.background`
`editorGroupHeader.noTabsBackground`
`statusBarItem.prominentBackground`
`statusBarItem.prominentHoverBackground`

I read the documentation, but still I can't find them in VS Code.

cc @aeschli

**Comment by usernamehw** [comment]
`editorGroup.background` - split editor => drag **not** a tab but a **tab group**
`editorGroupHeader.noTabsBackground` - `"workbench.editor.showTabs": false`
`statusBarItem.prominentBackground` - change mode `Toggle Tab Key Moves Focus` from command palette

**Comment by bsvipas** [comment]
`editorGroup.background` How I can drag not a tab, but tab group? I'm with macOS. I can't select more than more tab.

**Comment by bsvipas** [comment]
@usernamehw Thank you very much!!!!

**Comment by usernamehw** [comment]
@bsvipas I can't say for macOS, but on Windows when you hover over tab group cursor changes to "grab" and you are able to move tab groups left or right.

**Comment by bsvipas** [comment]
@usernamehw I understand now everything, thanks to your help!

**Comment by aeschli** [comment]
Thanks a lot, @usernamehw. I updated the descriptions and the docs with the additional information.
