### ISSUE TITLE
Missing Extension/Settings Export or Google Sign in to port VS code to my other devices

### ISSUE THREAD

**Issue by DadyByte** [Microsoft/vscode#40417]
I request a feature using which I can auto import my extensions and settings when I install vs code on my new machine.

**Comment by ramya-rao-a** [comment]
There are extensions to help you sync settings. See https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

For extensions, you can check in workspace recommendations in your repo and then get prompted to install those in the new machine. See https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

Also see #2743

**Comment by DadyByte** [comment]
i know recommended extensions but I want the etensions which I have installed. I have around 30 extensions how can i export them on multiple pcs?

**Comment by ramya-rao-a** [comment]
At the moment there is no solution for that.
Please add your thoughts in #2743

**Comment by ramya-rao-a** [comment]
For now, here is what you can do for your extensions.
- Make a list of the ids of your extensions and add them as workspace recommendation on a personal repo
- Clone this repo to the new machine, open it in VS Code
- When prompted about workspace recommendations, select "Install All". Or run `Extensions: Show Recommended Extensions` and and then choose the "Install All" button in the workspace recommendations view.
