### ISSUE TITLE
Cannot find git install.

### ISSUE THREAD

**Issue by RyanJEC** [Microsoft/vscode#40412]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-nuget-package-manager|jmr|1.1.6
Go|luk|0.6.69
csharp|ms-|1.13.1
qub-msbuild|qub|0.6.3

---

Steps to Reproduce:

1. Startup Visual Studio Code
2. Cannot find git install

Even added git.path in settings and still not working.

**Comment by cleidigh** [comment]
@RyanJEC 
Can you provide more information.
- Did you install git from https://git-scm.com/ ?
- Can you perform git commands from the command line?
- any specific error messages?

**Comment by DOTA2mm** [comment]
I also encountered this problem, add  'git.path' user setting to resolved temporarily.

**Comment by takdol** [comment]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.0
Angular2|joh|2.11.2
debugger-for-chrome|msj|4.0.0
angular2-inline|nat|0.0.17

(1 theme extensions excluded)


---

Steps to Reproduce:

1. Open project through CLI - (code .)
2. "Git not found" prompt shown


Reproduces without extensions: Yes

Getting the same issue as well. Just updated VS.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/40229

**Comment by xihesi** [comment]
更新VSCode 后不能自检GIT.path，需要手动设定。
