### ISSUE TITLE
Create rpm package test plan

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4041]
#4214 **Issue:** #3595
**Assignees:**

- [x] Linux - CentOS @dbaeumer  (couldn't fully test. See my comments below)
- [x] Linux - Fedora @SofianHn (similar to @dbaeumer I am blocked). 

**Details:**

*Test the rpm package install and uninstall*

1. Setup VM/machine
2. Download .rpm package from https://vscode-builds.azurewebsites.net/alpha
3. Install by opening .rpm package though the GUI (double click the file)
4. Ensure it installed correctly:
 - Opening "Code" through the launcher works
 - Running `code-alpha` through the terminal launches code
5. Uninstall: `sudo yum remove visual-studio-code-alpha`
6. Ensure it uninstalled correctly:
 - `/usr/bin/code-alpha` should not exist
 - `/usr/share/code-alpha` should not exist
7. Install via command line: `sudo yum localinstall vscode-x86_64.rpm`
8. Repeat steps 4-6.

**Comment by dbaeumer** [comment]
I could only test the UI since the CentOS installation didn't except any sudo commands. Not sure what is wrong with the installation. @Tyriar any hint

**Comment by dbaeumer** [comment]
@Tyriar I fixed the sudo issue, however my CentOS default install doesn't have apt-get either. Are these steps supposed to be working?

**Comment by SofianHn** [comment]
@Tyriar I was blocked too. I am able to install and verify that 1-4 runs nicely. But then Fedora does not have apt-get by default. I tried to install it and then use it to remove VSCode that did not work. Tried to use DNF as well and this does not work. Is this supposed to work?

**Comment by isidorn** [comment]
@SofianHn @Tyriar I fixed typo in step 5, can you please re-test

**Comment by SofianHn** [comment]
I verified with dnf.

**Comment by dbaeumer** [comment]
Finish testing. Closing.

**Comment by Tyriar** [comment]
Sorry about no response guys, I've been completely offline for the last 2 days. `apt-get` is a Debian thing, you should use `yum` to test (I thought I changed it from `apt-get` to `yum` when copying the .deb test over).
