### ISSUE TITLE
Is it necessary to alert "This workspace has extension recommendations" when they're already installed.

### ISSUE THREAD

**Issue by zuoez02** [Microsoft/vscode#40418]
- VSCode Version:  1.19.0 816be6780ca8bd0ab80314e11478c48c70d09383
- OS Version:  macOS High Sierra 10.13.1 (17B1003)

Steps to Reproduce:

1. Open old workspce
2. The editor alert "This workspace has extension recommendations".
3. Open extensions by clicking left side button.
4. search "@recommended "
5. It shows workspace recommendations and they're already installed.

Reproduces without extensions: No 

I added ".vscode/extensions.json"  when I use the earlier version of Code, and it didn't ask me to install workspace recommended extensions. But it ask me in this version(1.19.0). Will it alert in other workspace if I click "Don't show again"?

**Comment by dchitwood3** [comment]
I'm wondering the same thing. Could it not check & only prompt the user if one of the extensions is not installed & enabled?

I don't want people to click 'Don't show again' because a new extension might be added to the .vscode/extension.json later. After selecting "Don't show again", it's not prompting when changes are commend to the file.

PS. The recommend extensions feature is great. Thanks for adding it.

**Comment by ramya-rao-a** [comment]
If all the recommendations in the `.vscode/extensions.json` file are already installed, then the prompt should not appear.

I just tried it on the VS Code repo itself and I cannot repro the issue
- Uninstall the 3 recommendations thats in https://github.com/Microsoft/vscode/blob/1.19.0/.vscode/extensions.json
- Reload VS Code -> I get prompted -> click on "Show recommendations" -> Installed all the workspace recommendations
- Reload VS Code -> No longer getting prompted.

If you have a consistent repro, then can you help me debug this?
- Help -> Toggle Developer Tools -> Source
- Ctrl+P and look for `extensionTipsService.ts`
- In this file add a few breakpoints in the `_suggestWorkspaceRecommendations` method
- The code there is pretty simple and you should be able to step through.

**Comment by zuoez02** [comment]
@ramya-rao-a I debug the code in `extensionTipsService.ts` and set a breakpoint at line 356. In my current workspace, the variable `allRecommendations` includes `EditorConfig.EditorConfig` and other extensions with uppercase character in the name. But it use lowercase to check if it exists.
```typescript
const recommendations = allRecommendations.filter(id => local.every(local => `${local.manifest.publisher.toLowerCase()}.${local.manifest.name.toLowerCase()}` !== id));
```

![image](https://user-images.githubusercontent.com/4801955/34187054-65ddabbe-e56a-11e7-8035-b7a27ec9b2b3.png)

**Comment by ramya-rao-a** [comment]
Good catch!
I am on vacation at the moment, so will take a while to push a fix.
Feel free to send a PR to make a case insensitive check instead.

**Comment by ramya-rao-a** [comment]
@dchitwood3 can you check if yours is the same case? You can do this by lowercasing all the recommendations in the extensions.json file and then reloading vscode. You shouldn't get a prompt

**Comment by dchitwood3** [comment]
Yes, I have EditorConfig.editorconfig in mine as well. Note, I was using 1.18.1. I just moved to the Insider build and noted different behavior. It is working better. Thank you.

Here's my extensions.json:
```json
{
    "recommendations": [
        "dbaeumer.vscode-eslint",
        "donjayamanne.githistory",
        "eamodio.gitlens",
        "EditorConfig.editorconfig",
        "HookyQR.beautify",
        "michelemelluso.code-beautifier",
        "pranaygp.vscode-css-peek",
        "Zignd.html-css-class-completion",
        "PKief.material-icon-theme"
    ]
}

```

**Comment by ramya-rao-a** [comment]
This has already been fixed in the Insiders build
