### ISSUE TITLE
global declaration not found when declared inside symlinks directories

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#40422]
The title is quite self explanatory.
I use the insider version

I join 2 sample projects. In each the actual vscode project is the "project" folder.
In one(working) the global is defined inside a file in a subfolder
In the other the global it s defined inside a symlink subdirectory (thus the deep structure).

[testVSCode_notworking.zip](https://github.com/Microsoft/vscode/files/1567170/testVSCode_notworking.zip)
[testVSCode_working.zip](https://github.com/Microsoft/vscode/files/1567171/testVSCode_working.zip)

**Comment by mjbvz** [comment]
I see this working on MacOS. What OS are you on?

Also, can you try creating a simple `tsconfig.json` at the root of your project:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by farfromrefug** [comment]
@mjbvz  I am on MacOs Sierra

I made a lot of tests
1 / Simply open the project, i see the error
<img width="851" alt="screen shot 2017-12-19 at 09 35 39" src="https://user-images.githubusercontent.com/655344/34148238-dc82e704-e4a0-11e7-9a50-8c58106c78eb.png">
2 / Open test2.ts in another tab, the problem is gone
<img width="851" alt="screen shot 2017-12-19 at 09 36 01" src="https://user-images.githubusercontent.com/655344/34148241-dcae34a4-e4a0-11e7-9d66-02f831882291.png">
3/ Close and open the project again, VSCode opens last open files, thus test2.ts. The problem is still there
<img width="871" alt="screen shot 2017-12-19 at 09 36 22" src="https://user-images.githubusercontent.com/655344/34148242-dcd64336-e4a0-11e7-9782-8d98d0ce8538.png">
4/ Create a empty tsconfig.json, close and open the project. The problem is gone
<img width="847" alt="screen shot 2017-12-19 at 09 40 28" src="https://user-images.githubusercontent.com/655344/34148244-dd24635e-e4a0-11e7-84e6-2d85176d9053.png">

Now why do i have the problem in my full blown projects? I do have a tsconfig.json in those:
```
{
    "compilerOptions": {
        "target": "es6",
        "moduleResolution": "node",
        "module": "commonjs",
        "preserveConstEnums": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "outDir": "build/ts",
        "noImplicitUseStrict": true
    },
    "include": [
          "Resources/**/*.ts"
      ]
}
```

Also the behavior is different for me with no symlink

**Comment by mjbvz** [comment]
@farfromrefug In your full project, if you run `TypeScript: Go to project configuration` in both the project file and the symlinked definition, does it open the same `tsconfig`?

Also, try adding an explicit `exclude` section to your `tsconfig`:

```json
 "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
```

**Comment by farfromrefug** [comment]
@mjbvz Thanks for pointing me to the right direction. I actually used ```include``` instead of ```exclude``` and thus it was not finding my symlink.

I am really sorry for bugging you !

As a side note vscode should propose you to create a tsconfig.json. In the sample project i send you it was difficult to understand why the definintion was not found.

Thanks again
