### ISSUE TITLE
VS Code is not remembering all the functions from Wordpress Folder

### ISSUE THREAD

**Issue by ta-riq** [Microsoft/vscode#40427]
I'm Developing WP theme in VS code.

_Now my point is:_ 

> As i'm working under the Wordpress folder, VS code is not showing any **function reference** when i type couple of their first letter...

 
![screenshot_11](https://user-images.githubusercontent.com/26002422/34100082-8d508780-e40b-11e7-8ff6-738432683e30.png)

As you can see in the image above , i'm in `functions.php` file

But when I write `add_action() `, VS code doesnot showing the full add_action() ro me when i start to write `add_ac`

IS there any settings to make it rue or Its not available in VS code ? 

Please help me..

**Comment by bmewburn** [comment]
You need to install a PHP extension like [this](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)

**Comment by weinand** [comment]
Please file this issue against the php extension you are using.
