### ISSUE TITLE
Go to define not working

### ISSUE THREAD

**Issue by blling** [Microsoft/vscode#40429]
- VSCode Version: 1.19.0
- OS Version: Linux 16.04 LTS

Steps to Reproduce:

1. git clone `https://github.com/react-boilerplate/react-boilerplate.git`
2. open project `react-boilerplate` use VSCode
3. Ctrl+P find file `app/contaners/homepage/index`
4. Ctrl+F find `import H2 from 'components/H2';`
5. Select `H2` and press Ctrl + F12
6. Error `No implementation found...` and then could not go to define of H2.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` at the root of the project: https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson

**Comment by blling** [comment]
@mjbvz i have one,  could you try my reproduce step? if you do not have the problem please share your `jsconfig.json`. some other packages can `go to define` but `components/*` maybe its a bug?

**Comment by mjbvz** [comment]
Try setting `baseUrl` and `module`:

```json
{
    "compilerOptions": {
        "baseUrl": "app",
        "module": "system",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This should make paths like `components/H2` resolvable. More info: https://www.typescriptlang.org/docs/handbook/module-resolution.html
