### ISSUE TITLE
MacBook heating up and high CPU usage when using VSCode

### ISSUE THREAD

**Issue by Lopierdis** [Microsoft/vscode#40423]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 16.7.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1.Open VSCode on macbook pro 15" with touchbar

[CPU-20171218T111947.txt](https://github.com/Microsoft/vscode/files/1567292/CPU-20171218T111947.txt)
[CPU-20171218T111952.txt](https://github.com/Microsoft/vscode/files/1567293/CPU-20171218T111952.txt)

**Comment by nishantagrawal25** [comment]
Did you found a solution? My new MacBook pro is also heating as soon as I open up VSCode even if I don't do anything temperature rises to 72 °C and just closing VSCode drops it to 50 °C. Is there any solution to it related to VSCode

**Comment by gilesbutler** [comment]
I'm experiencing this too. Would love to know what's going on as I have to close Code and re-open every 10-20 minutes!
