### ISSUE TITLE
Keyboard language switch results in wrong keybindings

### ISSUE THREAD

**Issue by korenchkyn** [Microsoft/vscode#40428]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.2
cpptools|ms-|0.14.4
vscode-icons|rob|7.19.0
(5 theme extensions excluded)
---

Steps to Reproduce:
1. A command is bound to the "ctrl + ~" for example
2. I switch the keyboard language to Hungarian for example
3. The key bining becomes "ctrl + ö" 
4. On most of the HUN keyboards ö is not in the place of ~. Certain notebook keyboards works this way, but it really depends on the 104/105 key variants of a keyboard layout, and also it works quite differently if you use the so called 101-key HUN layout.

Suggestion:
Make an option for keybindings on different keyboard layouts, or make an option to exclude this behavior. (I was not able to find such a setting in User Settings.)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
This is as designed. On Windows, our default keybindings are bound to key codes. 

When switching keyboard layouts, Windows changes two logical mappings: first it changes the mapping scan code => key code, and second it changes what each key code + modifier keys produce.

If you wish to have a keyboard layout agnostic binding (scan code binding), you can do so by yourself:

This will bind to the scan code of `Backquote` which is always the physical key to the left of <kbd>1</kbd>, irrespective of keyboard layout.
```
    {
        "key": "ctrl+[Backquote]",
        "command": "workbench.action.terminal.toggleTerminal"
    },
```
