### ISSUE TITLE
Is it possible to use custom root directory for aliases nested into 2 or deeper level for imports? 

### ISSUE THREAD

**Issue by ScarySkeleton** [Microsoft/vscode#40435]
In VSCode we able to use aliases for one level nested:
![image](https://user-images.githubusercontent.com/25486085/34105574-81b85faa-e3fd-11e7-91a2-27ce58611f81.png)

And VScode successfully resolves that. 
But if I try to add second level nested aliases, for example: 
![image](https://user-images.githubusercontent.com/25486085/34105610-b3f902b2-e3fd-11e7-82b6-688c33a2cd2d.png)

The VSCode couldn't resolve it and I didn't get intelligence support 
![image](https://user-images.githubusercontent.com/25486085/34105669-eaf9008c-e3fd-11e7-9f00-fba8bd356735.png)

(The first one has the second level nested and the second one - first and VSCode successfully resolve it)

**Comment by weinand** [comment]
@ScarySkeleton what configuration file are the two screenshots from above showing?

**Comment by ScarySkeleton** [comment]
@weinand tsconfig.app.json

**Comment by weinand** [comment]
@ScarySkeleton you really mean `tsconfig.json`, right?

**Comment by weinand** [comment]
Oh I see, this is Angular?

**Comment by ScarySkeleton** [comment]
@weinand, exactly. Built with Angular CLI

**Comment by weinand** [comment]
I don't think that VS Code's typescript automatically understands the "paths" attribute of "tsconfig.app.json". But @mjbvz might know.

**Comment by ScarySkeleton** [comment]
@weinand VS Code's typescript is understood relative paths of 1 level nesting, as shown from above, but I don't exactly sure, that it can understand more than 1.

**Comment by leonadler** [comment]
@ScarySkeleton `tsconfig.app.json` is used for building the app, `tsconfig.json` for intellisense / editor lookup. VSCode does not care about the contents of `tsconfig.app.json` or its existence.

Do you also have a `paths` entry in your regular `tsconfig.json`?
If not, adding it / copying from `.app.json` might fix your issue.

**Comment by weinand** [comment]
I've closed the question since I believe that @leonadler's answer is correct.
