### ISSUE TITLE
Breakpoints doesn't work for esm files

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode#40434]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.4.0-104-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
project-manager|ale|0.23.1
vscode-color|ans|0.4.5
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
git-extension-pack|don|0.1.3
githistory|don|0.2.3
vscode-coffeescript-preview|dre|0.1.4
gitlens|eam|6.4.0
vscode-great-icons|emm|2.1.22
vscode-apache|mrm|1.1.1
vetur|oct|0.11.5
spellchecker|swy|1.2.13
ayu|tea|0.10.0
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

1. Unpack: 
[esm_debug_bug.zip](https://github.com/Microsoft/vscode/files/1567653/esm_debug_bug.zip)
2. Run `npm i` in folder
3. Open vscode in folder
4. Set some break points in `continuousLoader.mjs`
5. Add the following launcher:
```json
{
  "type": "node",
  "request": "launch",
  "name": "ESM debug",
  "args": [
    "--experimental-modules",
    "${workspaceFolder}/continuousLoader.mjs"
  ]
}
```

Reproduces without extensions: **Yes**

Only by using the `debugger` keyword am I able to stop execution. When I see the file in vscode debug mode, it is read-only. Don't know if that is significant. - The title is *"continuousLoader.mjs read-only core module"*

**Comment by auchenberg** [comment]
We have an issue open for this for our Node debugger. Root-cause is bug in Node. https://github.com/Microsoft/vscode-node-debug2/issues/158

**Comment by dotnetCarpenter** [comment]
Ref: https://github.com/nodejs/node/issues/17340
