### ISSUE TITLE
Discarding file changes crashes VS Code

### ISSUE THREAD

**Issue by soylens** [Microsoft/vscode#40433]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1.Open any file or create a new one
2.Type in anything without saving
3.Close the fiile and select `Don't save`
4.VS Code should crash

**Comment by soylens** [comment]
I think something is not right with my VS Code installation.
How would I have a clean uninstallation?
I deleted .vscode and %APPDATA%/Roaming/Code but didnt help, I did it on another Computer and couldnt reproduce

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by soylens** [comment]
Well I restarted and it appears no more. I think the hibernation screwed something up. I get this kind of problems quite frequently though.
