### ISSUE TITLE
[Debug] Hover tooltip stays after leaving the editor window

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4043]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

Steps:
1. Debugging JavaScript
2. Some var definitions in the first 2 lines
Ex. 
`var express = require('express');`
`var path = require('path');`
3. Hover over 'path' to bring up tooltip
4. Quickly move cursor to the debug actions menu at the top
5. Tooltip for 'express' will stay open on the editor window until you move the cursor back into the editor.

The same happens if you quickly hover, then move the mouse out of the editor window at the right speed, a tooltip will stay open.

![tooltipopen](https://cloud.githubusercontent.com/assets/12900364/13716262/e399b632-e78e-11e5-9a92-0879ff85eaf3.JPG)

Expected:
Tooltip disappears when leaving the editor window.

**Comment by isidorn** [comment]
This is fine, closing as designed.
