### ISSUE TITLE
'Show running extensions' themable

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#40432]
Right now 'Show running extensions' is not themable:

![image](https://user-images.githubusercontent.com/30043375/34105289-5711e0f6-e3fc-11e7-92b6-3025c6a2b513.png)

As you can see every second row have another color and it's impossible to change it.

cc @aeschli

**Comment by alexandrudima** [comment]
I don't think this is super high priority, as it is a development tool. For example, the Developer Tools are not themable.

**Comment by bsvipas** [comment]
Of course it is not super high priority, but if there's no property to edit such color try to use it like it's for 1 row for whole background and every second one make for e.g. `#fff2` to be a little bit darker.

**Comment by isidorn** [comment]
We accept PRs that fix this.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/runtimeExtensionsEditor.ts#L90

**Comment by bsvipas** [comment]
Good, thanks for pointing which file it's I will try to open PR with fix.
