### ISSUE TITLE
Clear --inspect* / --debug* arg when starting extension host

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#40443]
To be able to better track down problems with the extension host we start the extension host always with --inspect. The LSP forwards this to the LSP servers. As a consequence all servers are now started in debug mode as well. It might also have impact on node processes that are fork since command line arguments are preserved.

For LSP server the problem might be:

- the server could be started with --debug-brk which might stop the server and not running at all.
- if the server is running in an runtime different than node running in debug might have performance impact.

The proposal is as follows: when in production we still start the extension host in debug / inspect mode but we clear the argument from process.argv so that the servers start in non debug mode. If we are in dev mode we don't clear the argument.

To verify:

- start VS Code
- open a JSON file
- open a process explorer and inspect the command line of the JSON language server

Ensure that the server is started without --debug* / --inspect*

**Comment by alexandrudima** [comment]
This has already been fixed in #39569
