### ISSUE TITLE
Piping output to Code does not release command prompt until Code is closed.

### ISSUE THREAD

**Issue by admsteck** [Microsoft/vscode#40448]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1.  Launch cmd.exe or Powershell.exe
2.  Run `dir | code`
3.  Observe that the command prompt is frozen until Code is closed.

Reproduces without extensions: Yes

This would be acceptable behavior if I had specified `dir | code -w` or `dir | code --wait`.  But since those aren't the default option I would expect the command prompt to return after the command is complete without the need to close the Code window.

**Comment by bpasero** [comment]
We cannot change this, if you take this example: `ping heise.de | code` there is no output if we would not imply `--wait`. Since we do not know when the last data is piped in we cannot just stop the calling terminal command after Code has opened.
