### ISSUE TITLE
Insiders version does not show any updates daily on Ubuntu

### ISSUE THREAD

**Issue by svictoreq** [Microsoft/vscode#40442]
- VSCode Version: Insiders 19.0 commit 816be6780ca8bd0ab80314e11478c48c70d09383 DATE 2017-12-13
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Install Insiders version on Ubuntu with .deb package
2. Run `sudo apt update` and `sudo apt list --upgradable` daily to check for updates
3. No Insiders updates available

Reproduces without extensions: Yes

I have to manually download Insiders updates from the website, but this problem is recent. Two weeks ago I received an update everyday, but now I haven't receive any updates since about December 13.

**Comment by Tyriar** [comment]
We pause insiders just before we put a release out, we also froze it during the end of the year as many people are out (just incase something goes wrong). See https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/ for all the versions that are published.
