### ISSUE TITLE
Unix terminal delete word support (alt + backspace)

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#40444]
`Alt + Backspace` is common shortcut across unix terminals to delete word (to the first non alphanum character). Add it's support please.

**Comment by Yanpas** [comment]
No they don't. On windows when I hit Ctrl+Backspace I see `^W` in the terminal. I will try on linux, the behavior of Ctrl+Backspace should not differ from readline utility used in any terminal.

**Comment by Yanpas** [comment]
Tested on linux: it works the same as `Ctrl + W`, but it's not what unix users are used to.

E.g. imagine that this line is entered in the console and the cursor is in the end: `ls /home/user/Documents`
After pressing Ctrl+Backspace in vs code you get `ls ` and after pressing `alt+backspace` in any terminal you get `ls /home/user/`

**Comment by Tyriar** [comment]
On Windows it's harder to support, see https://github.com/Microsoft/vscode/issues/31821

On Linux/macOS the behavior is indeed identical to ctrl+w, if you have a better alternative to use please suggest, we defer this functionality to the shell as vscode has very little knowledge about what's inside the terminal, what's prompt, etc.

**Comment by Yanpas** [comment]
On linux most probably readline is used inside. It seems like vs code blocks "alt + backspace" and nothing happens

**Comment by Tyriar** [comment]
Thanks @Yanpas for the info, found what was wrong because of it.

Upstream issue is https://github.com/xtermjs/xterm.js/issues/1179, we'll now be sending \e^? which triggers `backward-kill-word` in bash. I was a little unsure whether it should be `\e^h` or `\e^?` though which both trigger the keybinding. If you have any insight I'm all ears :smile:
