### ISSUE TITLE
Only one tab is open at the same time

### ISSUE THREAD

**Issue by timobehrens** [Microsoft/vscode#40440]
- VSCode Version: Version 1.19.0 (1.19.0)
- OS Version: MacOS 10.13.1 

Steps to Reproduce:

1. Open VScode
2. Tabs are broken

Reproduces without extensions: Yes!

For some strange reasons, my tabs are completely broken. As you can see in the screenshot, I have multiple "OPEN EDITORS" (top left), but only one tab is present at a time. Furthermore, the x to close the tab is all the way on the right. 

![image](https://user-images.githubusercontent.com/15941188/34113379-cb132c04-e40f-11e7-8a3c-6d60c0f4b1b8.png)

When I click on the tab, the "Go to file" menu opens. When I open another file, the current active file is replaced by that one. Really kills my workflow.

![image](https://user-images.githubusercontent.com/15941188/34113297-8dc3b648-e40f-11e7-9d61-b2620bda8d19.png)

**Comment by bpasero** [comment]
@timobehrens maybe you disabled tabs, make sure you have this setting:

`"workbench.editor.showTabs": true`

**Comment by timobehrens** [comment]
I don't know what kind of magic did this, as I didn't touch vscode settings at all. The `"workbench.editor.showTabs"` setting was indeed set to `false`. 
Thanks @bpasero
