### ISSUE TITLE
Changing the debugging configuration while debugging doesn't work

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#4044]
1. I star a debugging session with "Launch configuration 1".
2. While it's running I change the configuration to "Launch configuration 2".
3. I stop the debugging session.
4. I start the debugging session, and while the label says "Launch configuration 2" it's actually using the configuration from "Launch configuration 1"

**Comment by isidorn** [comment]
How can you change the configation to "Launch configuration 2" while debugging? While debugging is running the select dropdown in debug pane is disabled for me - so it should be unable to change launch configurations

What version of vscode are you using? What OS are you using?

**Comment by digeff** [comment]
@isidorn You are correct and when I just launch it I can't change it... But for some reason sometimes after a while I can. I'm not sure how to reproduce it, but I've seen this happen several times in several versions and I'm pretty sure I've seen it both on Win 10 and OSX:
![vscode-change-launch-configuration](https://cloud.githubusercontent.com/assets/14098140/13749454/bdc71a58-e9be-11e5-9d34-66f229ad6c4c.gif)

**Comment by isidorn** [comment]
Closing until user provides more details.
