### ISSUE TITLE
File /tmp/code-stdin-XXX.txt is created and opened on launch via hotkey in Ubuntu

### ISSUE THREAD

**Issue by davegregg** [Microsoft/vscode#40441]
- VSCode Version: Code - Insiders 1.20.0-insider (bcc46316b497d1a316dd47ae86481df3ca5784ee, 2017-12-18T11:54:10.001Z)
- OS Version: Linux x64 4.13.0-19-generic (Ubuntu Artful Aardvark, Budgie desktop)
- Extensions: none
---

Steps to Reproduce:

1. Set Code to launch with hotkey via Keyboard (either `code-insiders` or `code-insiders -a`).
2. Launch via hotkey.
3. Observe a new file open at `/tmp/code-stdin-XXX.txt` (where `xxx` appears to be a randomly generated sequence of lowercase alphabetical characters).

This problem does not occur when launching via terminal or shortcut icon. This problem also does not occur with Atom or Gedit. I am currently unable to test on Gnome, so I can't say whether this is reproducible on Gnome.

**Comment by davegregg** [comment]
Correction: I *am* able to test on Gnome. And yes, I can reproduce the problem using the same steps as above, so I think we can rule out Budgie as the source of the problem. Both, however, use the same Keyboard settings panel in `gnome-control-center` to manage hotkeys.

**Comment by leonadler** [comment]
Will be fixed in the next version, apparently.

https://github.com/Microsoft/vscode/issues/40351#issuecomment-352432867

**Comment by leonadler** [comment]
Workaround for now: 
1. Open terminal
2. Type `code`
3. Close terminal

**Comment by bpasero** [comment]
Closing as duplicate.
