### ISSUE TITLE
Provide more options for customizing code completion items

### ISSUE THREAD

**Issue by seizir** [microsoft/vscode#40459]
One of my favorite features of Jetbrains IDEs is that they show complete signatures when giving suggestions. This is very useful when working with unfamiliar code as it gives complete information at a glance. It is also almost necessary in languages which (ab)use function overloading.

![image](https://user-images.githubusercontent.com/30301860/34128602-87b187a8-e441-11e7-8ee2-c56708d711bc.png)

For comparison, C# in VSCode gives very little information. The function name is redundantly repeated in the detail string. Full signature is visible only for the selected item. There is an issue open for this particular problem #39441

![image](https://user-images.githubusercontent.com/30301860/34128238-4d4712fa-e440-11e7-82e0-cd77a5ec0a23.png)

The Java extension works around this by putting the entire signature in the name but that looks quite ugly and cluttered because it's all the same color and it doesn't work well with longer signatures.

![image](https://user-images.githubusercontent.com/30301860/34127836-da5e06f0-e43e-11e7-95c9-e33c6c5fc443.png)

IntelliJ has a nice way of dealing with items that are bigger than the suggestion widget. They become fully visible when they are selected.

![image](https://user-images.githubusercontent.com/30301860/34128145-fbdc5948-e43f-11e7-83b7-85a0f19982b1.png)

Extensions should be able to at least change the style and color of the font so that they can show additional information in suggestions without sacrificing clarity.

**Comment by ramya-rao-a** [comment]
> Extensions should be able to at least change the style and color of the font so that they can show additional information in suggestions without sacrificing clarity.

Changing UI behavior like style and color is not exposed to extensions in VS Code. So, this cannot be supported.

@seizir Sorry, but its not clear to me what is it that you are asking for here apart from what is already covered in #39441

From your first screenshot, I can gather the need for what is tracked in #39441 plus the docs shown on the side.
The latter is doable in VS Code as well. Hit Ctrl+Space once the suggest widget is already open, and a detailed section will open to the right
