### ISSUE TITLE
Indent guides missing or partially rendered when zoomed out

### ISSUE THREAD

**Issue by dlchen** [Microsoft/vscode#40452]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
quokka-vscode|Wal|1.0.84
markdown-mermaid|bie|0.1.1
vscode-eslint|dba|1.4.3
gitlens|eam|6.4.0
markdown-shortcuts|mdi|0.8.1
vscode-code-outline|pat|0.0.12
code-spell-checker|str|1.6.0
vscode-mermaid-preview|vst|0.8.2
gitblame|wad|2.2.0

---

Steps to Reproduce:

1. Have indent guides on
2. Zoom out with `cmd` + `-`
3. Indent guides are missing or partially rendered

Reproduces without extensions: Yes

Screenshot
![image](https://user-images.githubusercontent.com/7862409/34124914-820a1be2-e3e9-11e7-9f3e-c285b4f97e20.png)

**Comment by weinand** [comment]
@dlchen I cannot reproduce this.
Can you repro this when running `code --disable-extensions`?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
