### ISSUE TITLE
--status throwing error

### ISSUE THREAD

**Issue by Chiliyago** [Microsoft/vscode#40451]
- VSCode Version: 1.19
- OS Version: Windows 7

Steps to Reproduce:

1. type 'code --status' at command line while VS code running
2.

Reproduces without extensions: Not sure
 This is the error:

[main 11:11:14 AM] Startup error: x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ c:\Program` Files` (x86)\Microsoft` VS` Code\resources\app\out\vs\bas ...
+                     ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/40228
