### ISSUE TITLE
Incorrect JSX fragment formatting

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#40454]
Currently they are auto-formatted to something bad
```js
const foo = () => (
	<div>
		{true ? (
			<>
			<div>lol</div>
			<span>k</span>
			</>
		) : (
				<div>
					bar
			</div>
			)}
	</div>
);
```

OS: linux
vscode: 1.19.0

**Comment by ramya-rao-a** [comment]
Can you repro this without extensions? Run `code --disable-extensions` and try again

**Comment by caub** [comment]
![Uploading 2017-12-18-221209_1283x729_scrot.png…]()

**Comment by mjbvz** [comment]
What is the starting code?

**Comment by caub** [comment]
Sorry I don't know what you mean by starting code, this `index.js` file? I don't really run it, it needs babel

**Comment by mjbvz** [comment]
Please paste up the code from before formatting and then from after formatting

**Comment by caub** [comment]
this is what I'd expect: 

```js
const foo = () => (
	<div>
		{true ? (
			<>
				<div>lol</div>
				<span>k</span>
			</>
		) : (
			<div>
				bar
			</div>
		)}
	</div>
);
```

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/20650 and https://github.com/Microsoft/TypeScript/issues/20766

**Comment by caub** [comment]
Thanks, ok
