### ISSUE TITLE
`delete` key does not work when renaming file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#40456]
- VSCode Version: Code - Insiders 1.19.0-insider (bc206bbacc13e48d4422b8c73334aa9dd6f782df, 2017-12-08T06:13:46.629Z)
- OS Version: Linux x64 4.4.0-21-generic
- Extensions: none
---

Steps to Reproduce:

1. Open the file explorer.
2. Right-click on a file and select "Rename".
3. Press the `delete` key.
4. Nothing happens. Using `backspace` works. I expected it to delete text to the right of the cursor like it normally does when editing text.

This does seem to work in vscode non-insiders.

**Comment by bpasero** [comment]
@andy-ms did it work before?

/cc @joaomoreno maybe another regression from list refactoring?

**Comment by joaomoreno** [comment]
Some extension defines a keybinding and needs to add `&& !inputFocus` to it... Maybe we should reconsider how that business is done...

@andy-ms Open your Keyboard Shortcuts view, search for `Delete`. What extension defines a keybinding for `Delete`?

**Comment by andy-ms** [comment]
![screenshot from 2017-12-19 07-22-03](https://user-images.githubusercontent.com/19274678/34164070-71223eaa-e48d-11e7-8664-63b46773e569.png)

**Comment by andy-ms** [comment]
Actually, it looks like updating vscode-insiders this morning fixed the problem, and I don't see any changes to the keyboard shortcuts after updating.
