### ISSUE TITLE
Cannot navigate to exact error line while run Python file in terminal

### ISSUE THREAD

**Issue by xuananh-viosoft** [Microsoft/vscode#40468]
- VSCode Version: 1.19.0
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Run Python file in terminal (internal terminal)
2. Error happen, I cannot navigate to error line using ctrl + click, it only jump to error file, not exact error line

This issue was reported at vscode-python repo: [https://github.com/Microsoft/vscode-python/issues/450](url)
but one person told me report this issue here
Does anyone know about this issue?

Reproduces without extensions: No

**Comment by Tyriar** [comment]
Please provide the exact format of the link, ideally with a screenshot as well

**Comment by xuananh-viosoft** [comment]
Following is the sequence that I create this issue
For instance, I created an error at line 26
![1](https://user-images.githubusercontent.com/22319798/34428217-183605a4-ec7d-11e7-8120-a6cf22d164df.png)

Then I move the cursor to another line, for instance, line 57
![2](https://user-images.githubusercontent.com/22319798/34428265-866dbb98-ec7d-11e7-8e9e-d2cb455da5c1.png)

Then I run Python file by right click on this file and choose Run Python File in Terminal as below
![3](https://user-images.githubusercontent.com/22319798/34428270-8f5db3de-ec7d-11e7-9c84-6d00df511665.png)

Then error happen at line 26 as below
![4](https://user-images.githubusercontent.com/22319798/34428284-a8c4e9b4-ec7d-11e7-9f96-e231eaf412c1.png)

Then I try to navigate to error location by ctrl+click to error message in terminal, but the cursor is still at line 57, it does not move to line 26, which is error line that I have created earlier

**Comment by Tyriar** [comment]
To verify, echo a valid link of the form `"(file path)", line 45` and make sure it works.

**Comment by xuananh-viosoft** [comment]
I did as you said, but It didn't work, It have worked on insider version,
I am using version:
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Tyriar** [comment]
@xuananh-viosoft it should only work in Insiders atm 👍
