### ISSUE TITLE
[Themes] Holding Up or Down key when selecting a theme hangs the application

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4046]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

Steps:
1. Press F1 to open commands
2. Type Theme, Enter
3. Hold Up or Down key
4. Tries to keep up changing themes on the fly/demo them but can't and freezes after a few seconds.

**Comment by bpasero** [comment]
Maybe we should buffer applying the theme with a timeout.
