### ISSUE TITLE
Emmet expansion does not work for React custom components

### ISSUE THREAD

**Issue by tvojtech** [Microsoft/vscode#40463]
- VSCode Version: Code - Insiders 1.20.0-insider (bcc46316b497d1a316dd47ae86481df3ca5784ee, 2017-12-18T11:47:43.298Z)
- OS Version: macOS High Sierra

---

Steps to Reproduce:

1. You have React Components `Inner` and `Outer`
2. In `Outer`'s `render` function write `Inner` and press `Tab`. Nothing happens. (div and other html tags work fine)

Reproduces without extensions: Yes

**Comment by ramya-rao-a** [comment]
See https://code.visualstudio.com/docs/editor/emmet#_common-questions

**Comment by tvojtech** [comment]
Well, it seems to work for MyTag or anything that is not defined in source. But for component that are already defined (imported or defined inline) it does not work. 

imagine an example

file Inner.js
```
export default () => <div>Inner</div>
```

file Outer.js
```
import Inner from './Inner'

const Outer = () => Inner.someClass<<Tab>>
```

Pressing tab key does nothing, the expression does not get expanded. 
(Expanding of `Inner.someClass` does work if `Inner` is not imported.)
(Expansion of MyTab does not work in any case. I have to add some more complex expression to get it work)

**Comment by ramya-rao-a** [comment]
Can you try adding the setting `"emmet.triggerExpansionOnTab": true`?

**Comment by tvojtech** [comment]
I've tried. Does not work either.

**Comment by ramya-rao-a** [comment]
How about running the command `Emmet: Expand Abbreviation` when the cursor is at the end of `Inner.someClass`?

**Comment by tvojtech** [comment]
Does not work too.

**Comment by ramya-rao-a** [comment]
I see that the files are `.js` and not `.jsx`
What is the language mode you see in the bottom right corner of VS Code? Javascript or JavacriptReact?

**Comment by tvojtech** [comment]
I've tried it for both Javascript and Javascriptreact. Everything written above holds true for both languages.

In my user settings I have

```
"emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
```

so Javascript === Javascriptreact for emmet.

**Comment by ramya-rao-a** [comment]
I am truly stumped now.
We do have code in place to not present emmet expansion in autocompletions when what was typed is of the form `a.b` where a is one of the symbols in the file. This is to avoid scenarios where you might be typing `someobject.someproperty` which is often.

But this restriction doesn't apply to tab (when "emmet.triggerExpansionOnTab" is enabled) or the `Emmet: Expand Abbreviation` command itself.

Since I cannot repro, will you consider trying to debug from source?

**Comment by ramya-rao-a** [comment]
If you want to give debugging this issue at try,

- Clone the vscode repo from https://github.com/Microsoft/vscode
- Follow the steps in [Build and Run](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run)
- Open the folder `extensions/emmet` from the cloned repo in a new VS Code window
- Add a breakpoint at https://github.com/Microsoft/vscode/blob/1.19.0/extensions/emmet/src/abbreviationActions.ts#L101 and hit F5 to launch a new VS Code window where you can open your file and try to repro the issue

**Comment by tvojtech** [comment]
I will try to debug it during Holidays.

**Comment by tvojtech** [comment]
It seems to be an extension problem so closing the issue. Thanks for your support.
