### ISSUE TITLE
Left toobar is not display

### ISSUE THREAD

**Issue by roojay520** [Microsoft/vscode#40469]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
---

After the automatic upgrade to 1.19.0 version, the left toobar is not display.
![bug1](https://user-images.githubusercontent.com/11495164/34138546-102bd322-e4ab-11e7-98a2-7cf170c469da.png)
![bug2](https://user-images.githubusercontent.com/11495164/34138547-1103b986-e4ab-11e7-9d19-012eb84d03b3.png)

**Comment by bpasero** [comment]
@roojay520 when you right click into that area you should be able to bring back the icons there:

![image](https://user-images.githubusercontent.com/900690/34142501-d0a66ab4-e487-11e7-8a22-31aec99a61c8.png)

**Comment by roojay520** [comment]
thanks 👍
