### ISSUE TITLE
Unable to save files after some time - v1.19 

### ISSUE THREAD

**Issue by jiayisheji** [Microsoft/vscode#40479]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-svgviewer|css|1.4.3
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
code-runner|for|0.8.5
beautify|Hoo|1.1.1
vscode-git-tags|how|1.1.2
githd|hui|1.0.0
output-colorizer|IBM|0.1.2
docthis|joe|0.6.0
vscode-commitizen|Kni|0.5.0
Angular-BeastCode|Mik|5.1.12
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
vscode-filesize|mkx|1.0.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.1
chai-spec-generator|rin|0.4.0
LiveServer|rit|3.0.1
vscode-icons|rob|7.19.0
git-merger|sha|0.3.6
stylelint|shi|0.31.0
open-in-browser|tec|1.1.0
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1. After a period of use, I can not save it.
2. I do not know what plug-in conflict
3. I try to remove the plug-in, there is still a problem
4. I restart it and I can work again

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@jiayisheji 
Are you saying that you cannot save any files after a while?
Does it matter how many files were the type you have open?
Also did you disable all the extensions?
Are you getting any errors or warnings or just no reaction to the request?

**Comment by jiayisheji** [comment]
@cleidigh 
Can not save the file, my home is win10, there is no problem，
I do not know which plug-in conflict, or I configure the conflict

```json
{
    "git.path": "D:\\Program Files\\Git\\bin\\git.exe",
    "workbench.iconTheme": "vscode-icons",
    "search.exclude": { // 搜索排除文件夹
        "**/node_modules": true,
        "**/bower_components": true,
        "**/dist": true
    },
    "eslint.autoFixOnSave": true,
    "tslint.autoFixOnSave": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue",
        "vue-html"
    ],
    "beautify.config": {
        "indent_size": 4
    },
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json"
            ],
            "filename": [
                ".jshintrc",
                ".jsbeautifyrc"
            ]
            // "ext": ["js", "json"]
            // ^^ to set extensions to be beautified using the javascript beautifier
        },
        "css": [
            "css",
            "scss"
        ],
        "html": [
            "htm",
            "html"
        ]
    },
    "sublimeTextKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "editor.formatOnPaste": true,
    "git.autofetch": true,
    "vsicons.projectDetection.autoReload": true 
}
```

**Comment by cleidigh** [comment]
@jiayisheji 
So it sounds like you have a work machine with the problem but your home machine does not exhibit the problem and both systems are Windows 10 with VSCode 1.19  , yes?

Did you disable all extensions?

**Comment by jiayisheji** [comment]
@cleidigh 
I first disable extension so try

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
