### ISSUE TITLE
Support modifying the name of every terminal

### ISSUE THREAD

**Issue by jianzhou520** [Microsoft/vscode#40478]
- VSCode Version: 1.19.0
- OS Version: windows 10.0.162299   version 16299

Steps to Reproduce:
Can't modify the name of every terminal 
![image](https://user-images.githubusercontent.com/11852997/34142449-27b1de9e-e4c2-11e7-97a0-7007224b03bc.png)

Reproduces without extensions: Yes

**Comment by cleidigh** [comment]
@jianzhou520 
If I understand your request, rename any terminal to any name,  there is already a command for that:
Terminal: Rename

I don't think there is a default key binding so if you press F1 for the command pallet
then type Terminal and you will see all the terminal commands including rename terminal for the currently active terminal.  You can rename every terminal that way.

**Comment by jianzhou520** [comment]
That helps. Thanks!
