### ISSUE TITLE
php cannot go to the function,error:"register" is not defined

### ISSUE THREAD

**Issue by yecanlin** [Microsoft/vscode#40474]
- VSCode Version: 1.9
- OS Version: windows 64

Steps to Reproduce:

1.
![90 hvunr 1a 8l5x ihv9](https://user-images.githubusercontent.com/17768200/34139242-9782256c-e4ae-11e7-8422-846778213e5d.png)

2.
![c3_eybezia 8sa pjo 2](https://user-images.githubusercontent.com/17768200/34139257-bf57c9ca-e4ae-11e7-9509-501114a6ae8a.png)

3.
![dmv a x4e9 z n h 28 z o](https://user-images.githubusercontent.com/17768200/34139290-eb51ab4a-e4ae-11e7-8c9e-2785dc273332.png)

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue was moved to felixfbecker/php-language-server#553
