### ISSUE TITLE
F12，ctrl+shift+o do not work

### ISSUE THREAD

**Issue by lindaoling** [Microsoft/vscode#40470]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
alignment|ann|0.3.0
path-intellisense|chr|1.4.2
githistory|don|0.2.3
php-debug|fel|1.12.1
auto-close-tag|for|0.5.5
Align|ste|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@lindaoling 
I am using Windows 7 and do not see this behavior with Code 1.19 or Insiders.
I tried both Python and typescript.

Can you give more information?
- File type you are using
- Any errors or warnings
- Behavior with all extensions disabled

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
