### ISSUE TITLE
Emmet "Wrap with abbreviation" : ".something|c" doesn't seem work

### ISSUE THREAD

**Issue by sueharaluke** [Microsoft/vscode#40471]
- VSCode Version: 1.19.0 (1.19.0)
- OS Version: macOS High Sierra 10.13.1 (17B1003)
- Reproduces without extensions: Yes

Steps to Reproduce:

1. In your vscode preferences, enter this setup: 
```
"emmet.preferences": {
        "filter.commentAfter": "<!-- /[#ID][.CLASS] -->"
    }
```
2. In a html file, using the Emmet "Wrap with abbreviation" enter something like ".container|c".

3. You should get an error saying "Failed to expand abbreviation".

---

It works beautifully when I simply add elements without the "Wrap with abbreviation", for example ".container|c" outputs:
```
<div class="container"></div><!-- /.container -->
```
"Wrap with abbreviation" also works fine without the "|c". 

Thanks in advance !

**Comment by ramya-rao-a** [comment]
Thanks for reporting!

**Comment by sueharaluke** [comment]
Ms. Ramya Rao, that was incredibly fast !
Thank YOU !
