### ISSUE TITLE
 Unknown actor eExtHostDocumentsAndEditors

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#40482]
Issue Id: <b>45a044fe-b209-521b-9cb8-6ebb1035c811</b><br /><br />*Versions* <br />- 1.19.0<br />-  929bacba01ef658b873545e26034d1a8067445e9<br />-  dcee2202709a4f223185514b9275aa4229841aa7<br />*Stack* <br />Error: Unknown actor eExtHostDocumentsAndEditors<br />[/vs/workbench/services/thread/node/abstractThreadService.ts#L35:9](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/thread/node/abstractThreadService.ts#L35:9)<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L109:39 (invoke)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L109:39 (invoke))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L96:36 (_invokeHandler)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L96:36 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L32:65 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L32:65 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#L157:4 (onMessage)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L157:4 (onMessage))<br />[/vs/base/common/event.ts#L382:86 (call)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/event.ts#L382:86 (call))<br />[/vs/base/common/event.ts#L142:15 (call)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/event.ts#L142:15 (call))<br />[/vs/base/parts/ipc/node/ipc.net.ts#L81:22 (fire)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/parts/ipc/node/ipc.net.ts#L81:22 (fire))<br />    at emitOne (events.js:96:13)<br />    at Socket.emit (events.js:191:7)<br />

**Comment by bpasero** [comment]
Also:

```
Error: Unknown actor eExtHostWindow 
at t.e.invoke (/out/vs/workbench/node/extensionHostProcess.js:515:897) 
at e._invokeHandler (/out/vs/workbench/node/extensionHostProcess.js:357:580) 
at e._receiveOneMessage (/out/vs/workbench/node/extensionHostProcess.js:357:270) 
at /out/vs/workbench/node/extensionHostProcess.js:356:206 
at /out/vs/workbench/node/extensionHostProcess.js:358:204 
at /out/vs/workbench/node/extensionHostProcess.js:85:988 
at e.fire (/out/vs/workbench/node/extensionHostProcess.js:87:218) 
at Socket.<anonymous> (/out/vs/workbench/node/extensionHostProcess.js:135:717) 
at emitOne (events.js:96:13) 
at Socket.emit (events.js:191:7) 
```

**Comment by alexandrudima** [comment]
I have looked at the code for quite some time. The only way I can reproduce this error is if something fails in the initialization path of the extension host. e.g.

![image](https://user-images.githubusercontent.com/5047891/35739189-1a0a0680-0831-11e8-9c67-26808a413892.png)

Then, the listeners for various extension host features are not registered and the errors show up:
![image](https://user-images.githubusercontent.com/5047891/35739204-2c193184-0831-11e8-8877-d13fa0b08b57.png)


But these are second-level errors. i.e. the root cause is the error before, i.e. this error says that the extension host is broken, but the previous error would say why ...

So. annoying, but no code change ...
