### ISSUE TITLE
 Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#40483]
Issue Id: <b>61b4428b-b730-3412-63d1-5c496dd5907b</b><br /><br />*Versions* <br />- 1.19.0<br />-  929bacba01ef658b873545e26034d1a8067445e9<br />-  1e9d36539b0ae51ac09b9d4673ebea4e447e5353<br />-  b813d12980308015bcd2b3a2f6efa5c810c33ba5<br />-  d6fbdcf19716910b26ea81efc95724f2fabe5aa6<br />-  dcee2202709a4f223185514b9275aa4229841aa7<br />-  0c60476e5167d4bdcf01cc48558b2e1faf0edae1<br />-  3afa3348c5cc8ee7fb29458e303cf476b0887f0a<br />-  c1e079b6ccfad9ead105c44a84e862ffc5250222<br />-  be377c0faf7574a59f84940f593a6849f12e4de7<br />-  6bc5a14bf34e44b3af5508350cc1221fcc999ceb<br />-  989c40066d124cde846cf5ded8364251246e100e<br />-  6e90f8995da4bd999e8983b8e480a34045c1dfcf<br />-  d294b25f2dd5c96d89bd23f82bd5fd2c0958a4bd<br />-  f6ef4bef42fa2948426c99fefa340235e67a0c5e<br />-  dcd1aa35dfa590b4a528e1ab55e957002f430f17<br />-  aaec2980609a4bbe44d0cfe2d3f78c85cba1be83<br />-  e6a76e4bd3f52ab07452bb181e861f5a9bfb6596<br />-  08ec16001adaab8a86183431f6aec09209caa4ab<br />-  dc84f454ea245a1131e28557de1204b8cd1cc320<br />-  4b01451cea60f32412098735709fddcac567b33d<br />-  3495b0b185acbe8188e821ccb3ae807274703a9c<br />-  86e057cd25756811781237b5d84b8228f99e59ab<br />-  fd1c9a12cc12dd2ca131f8edafc6214dc722cd09<br />-  d88e71355feeb2b0deb02c021d33cb968531726e<br />-  91a2020698b5220e50f60682724927a810608356<br />-  89b158e11cb1c3fe94a3876222478ed2d0549fc8<br />-  d8989c95964ce06c64ffebc2fb400a0327bd447d<br />-  af6ca44db81f5186d3104226c8e76e026789ce20<br />-  15449873f130d7f3e5604a1cac94f32a1f15f604<br />*Stack* <br />RangeError: Maximum call stack size exceeded<br />    at processList.findIndex.v (\node_modules\windows-process-tree\lib\index.js:12:41) <no sourcemaps><br />    at Array.findIndex (native)<br />    at buildProcessTree (\node_modules\windows-process-tree\lib\index.js:12:31) <no sourcemaps><br />    at children.childIndexes.map.c (\node_modules\windows-process-tree\lib\index.js:22:37) <no sourcemaps><br />    at Array.map (native)<br />    at buildProcessTree (\node_modules\windows-process-tree\lib\index.js:22:28) <no sourcemaps><br />    at children.childIndexes.map.c (\node_modules\windows-process-tree\lib\index.js:22:37) <no sourcemaps><br />    at Array.map (native)<br />    at buildProcessTree (\node_modules\windows-process-tree\lib\index.js:22:28) <no sourcemaps><br />    at children.childIndexes.map.c (\node_modules\windows-process-tree\lib\index.js:22:37) <no sourcemaps><br />

**Comment by ramya-rao-a** [comment]
@Tyriar I can repro this consistently when closing the panel

**Comment by Tyriar** [comment]
@ramya-rao-a have you seen this since? I haven't (but I haven't uses Windows too much).

**Comment by ramya-rao-a** [comment]
@Tyriar I haven't seen it since

**Comment by Tyriar** [comment]
Let me know if you hit it again 😃
