### ISSUE TITLE
inspect, update methods on WorkspaceConfiguration do not work for language specific settings

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#40489]
Example of a default language specific setting 
```
"[go]": {
    "editor.insertSpaces": false
}
```

In an extension,
- `vscode.workspace.getConfiguration('[go]')['editor.insertSpaces']` gives `false`
- `vscode.workspace.getConfiguration('[go]').inspect('editor.insertSpaces').defaultValue` gives `undefined`
- `vscode.workspace.getConfiguration('[go]').update('editor.insertSpaces', vscode.ConfigurationTarget.Global)` doesn't add anything to User Settings

**Comment by jurosh** [comment]
Probably none of override configurations (in Workspace) are working, I've wanted to use:

```
 "[javascript]": {
    "editor.formatOnSave": true
  }
```

But it's not working too. In normal non-workspace project it's working fine.

**Comment by sandy081** [comment]
We never supported this for language specific settings. They are treated as normal settings. So setting is `[go]` and value is `{ "editor.insertSpaces": false`}. 

You can only inspect/update using the setting key but not with a combined key.

vscode.workspace.getConfiguration('[go]').inspect('editor.insertSpaces').defaultValue is true because there is no setting called `[go].editor.insertSpaces`. Same for update.

**Comment by aamarks** [comment]
Ug, spent too much time trying to get that to work before seeing this issue. Is there really no way then to set an editor setting and have it only apply to the language of my extension then? 

I can do it through a declaration in the package.json but I want the user to be able to change my setting that I easily present in my extension settings without them having to worry about the vscode settings I modify to accommodate that. (i.e. I present a single column setting that then sets a ruler there and wordwrap and gives me a value to use for error checking, and it doesn't make sense for that to apply to files not marked as the language of my extension)

**Comment by sandy081** [comment]
This should be supported now.

#26707

**Comment by aamarks** [comment]
As far as I can tell it doesn't, though I may have the syntax wrong:

```
vscode.workspace.getConfiguration().update('editor.rulers', [50], vscode.ConfigurationTarget.Global)  // this works

vscode.workspace.getConfiguration().update('[myextensionlang]editor.rulers', [78], vscode.ConfigurationTarget.Global)  // no go
vscode.workspace.getConfiguration('[myextensionlang]').update('editor.rulers', [79], vscode.ConfigurationTarget.Global) // no go
```
(I installed the Insiders VSC today just in case it's very new.)

**Comment by sandy081** [comment]
You are not using the API correctly. Please refer to our sample - https://github.com/microsoft/vscode-extension-samples/blob/b5fc559a93bc6326d4f0fef580a19d8c647b1cd9/configuration-sample/src/extension.ts#L188

**Comment by aamarks** [comment]
Aha, thank you! I was looking at an old version of that sample on my computer that didn't have language specific setting edits.

Working now with `getConfiguration('', { languageId: 'myextensionlang' } `
...tho that's being marked as an error that has to be overridden. TSLint not updated yet? I'm not seeing https://code.visualstudio.com/api/references/vscode-api#ConfigurationScope in intellisense.
