### ISSUE TITLE
Please higlight New Files Or Folders created from explorer pannel

### ISSUE THREAD

**Issue by tluanga34** [Microsoft/vscode#40488]
When the list of files is long in the explorer panel, creating a new folder or file requires me to enter the name at the bottom of the current list, but it moved up sorted after a name is given. In this case, it becomes difficult to search it.

It would be great if it scrolls automatically to the viewport and is highlighted.

**Comment by isidorn** [comment]
Please try reporudcing this with latest vscode insiders https://code.visualstudio.com/insiders/
Can you still reproduce it there?

**Comment by tluanga34** [comment]
Downloading...

**Comment by tluanga34** [comment]
Here is the test result with the Insider preview.

1. New File - This work as expected. It scrolls into the viewport and highlights the new file.
2. New Folder - When new folder created, It scrolls into the viewport which is as expected, but it doesn't highlight the new folder.

**Comment by isidorn** [comment]
I think this behaves just fine.
If this is still misbehaving for you please let us know and post a screenshot and I can investigate more

Thanks
