### ISSUE TITLE
 Cannot read property 'result' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#40481]
Issue Id: <b>96a37e89-60aa-11b3-665d-c82b64ae398c</b><br /><br />*Versions* <br />- 1.19.0<br />-  8598659abef5b83e0854c4a12fbd79cf5817b6ad<br />-  951f5a20fc820e32a65ca05bb87af86f65027470<br />*Stack* <br />TypeError: Cannot read property 'result' of null<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#L481:31 (result)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L481:31 (result))<br />[/vs/platform/extensionManagement/node/extensionGalleryService.ts#L716:0 (resolveMarketplaceHeaders)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L716:0 (resolveMarketplaceHeaders))<br />[/vs/platform/extensionManagement/node/extensionGalleryService.ts#L716:0 (resolveMarketplaceHeaders)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L716:0 (resolveMarketplaceHeaders))<br />[/vs/base/common/winjs.base.js#L11:0 (Promise)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.js#L11:0 (Promise))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/816be6780ca8bd0ab80314e11478c48c70d09383/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />

**Comment by bpasero** [comment]
@alexandrudima fyi this is the top crash in 1.19, not sure we need to treat this as candidate.

**Comment by alexandrudima** [comment]
The error is 100% benign. If our telemetry service can take the volume (26k hits / 4days) I suggest we fix this in December/January.

The crash occurs in the code which will check if the extension cache file is valid and which would delete the cache file if it is invalid. The cache file is already deleted by someone else. I suppose it can be triggered by loading up a workbench and doing something with the extensions (e.g. update) in the first 5s.
