### ISSUE TITLE
[Node.js] Debugging Node.js stops responding after a number of step-over requests

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#4048]
OS: Windows 10
Build#: 0.10.12-alpha
Node: 4.1.1

Node.js seems to stop responding after a certain number of step-over requests.

Steps:
1. Open provided Node.js project folder.
2. Set breakpoint in app.js at line 13. `var msg = "hello world";`
3. Start debugging
4. Step-over or press F10 about 40 times.
5. Node.js stops responding after reaching line 114 of timers.js
"Error: Node.js did not respond to request 'continue' in a reasonable amount of time"

Expected:
Node.js continues to debug

Files:
[311ExpressApp.zip](https://github.com/Microsoft/vscode/files/170061/311ExpressApp.zip)

**Comment by weinand** [comment]
@vsccarl you are stepping into node's shutdown code by doing the 40 steps. The last step will not return so VS Code is running into a timeout. This is expected.
Node-inspector will not return either but they are not even showing the timeout message.
