### ISSUE TITLE
Code does not find git from search path

### ISSUE THREAD

**Issue by db6edr** [Microsoft/vscode#40499]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-svgviewer|css|1.4.3
empty-indent|Dmi|0.2.0
githistory|don|0.2.3
gitlens|eam|7.0.0
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
latex-workshop|Jam|3.10.0
latexcompile|mat|0.7.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|4.0.0
material-icon-theme|PKi|3.2.0
java|red|0.16.0
annotator|ryu|0.11.0
final-newline|sam|0.3.2
view-in-default-application|see|3.3.0
code-settings-sync|Sha|2.8.7
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Install git for Windows in a non-standard path like c:\sdk\git, add it to %PATH%
2. Verify git can be called from CLI (git bash, Windows cmd) 
3. Install and launch VS Code

Reproduces without extensions: Ye

Expected behavior:
VS Code uses the installed and available git without further ado.

Actual behavior:
Starting with version 1.19, VS Code says "Git not found in ..." and asks user to configure it properly. With older versions, git just worked. See screenshot.

![vs_code_git_not_found](https://user-images.githubusercontent.com/264334/34147927-b411cbce-e49f-11e7-8539-7b3c7ad7cf64.PNG)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/40229
