### ISSUE TITLE
editor.showFoldingControls: always is ignored

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#40495]
- VSCode Version: 1.18.1
- OS Version: Windows 7 x64 Pro

Steps to Reproduce:

1. set editor.showFoldingControls to "always"
2. notice that folding boxes are not showing ALWAYS. 

Reproduces without extensions: didn't check (haven't installed extensions lately)

PS: This functionality stopped working when i updated VSCODE lately.

**Comment by weinand** [comment]
I cannot reproduce this in VS Code 1.19 on Windows 7:
![2017-12-19_11-14-06](https://user-images.githubusercontent.com/1898161/34152111-c1967a3e-e4ad-11e7-90a9-09fce94664f9.png)

Please try to reproduce this in the latest version of VS Code (1.19).

**Comment by Montago** [comment]
This issue was fixed in 1.19 

after updating it's working again

**Comment by weinand** [comment]
Thanks for trying the latest!
