### ISSUE TITLE
'window' is no longer tracked by intellisense as of 1.18

### ISSUE THREAD

**Issue by realratchet** [Microsoft/vscode#40498]
I've been looking for someone to report this issue as of 1.18 release but 1.19 is already out and no one seems to notice. When assigning extra variables to '_window_' IntelliSense no longer picks up on it. This is an issue when trying to add something to global namespace.

I've been opting for using 1.17 until this is resolved. I could resolve this by changing the way code is structured however, that's not up to me and I'm stuck with this.

- VSCode Version: 1.18+
- OS Version: Debian Jessie

Steps to Reproduce:

```
// Example 1
import THREE from "three";
THREE.Object3D  // Works, but it's not part of global namespace.

// Example 2 (this is how code is set up)
window.THREE = window.THREE || require("three");
window.THREE.Object3D // Doesn't work

// Example 3
window.THREE2 = require("three");
window.THREE2.Object3D // Doesn't work.
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20783
