### ISSUE TITLE
Dependencies are missing in apt repository when using X11 forwarding

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#40491]
There seem to be missing dependencies when installting VSCode on Ubuntu 16.04 in a **vagrant box with X11 forwarding**.

- VSCode Version: 1.19.0 816be6780ca8bd0ab80314e11478c48c70d09383 x64
- OS Version: Ubuntu 16.04 Xenial Xerus

Steps to Reproduce:

1. Start up vagrant box

```bash
vagrant up --provider virtualbox --provision
vagrant ssh -- -Y
```

3. [Run installation script from documentation](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions)
```bash
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
```
3. Install vscode

```bash
sudo apt-get update
sudo apt-get install code
```

4. Run VScode (error)

```bash
/usr/share/code/bin/../code: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

After some investigation, I found out these packages are missing in order to work:

- libgtk-x11-2.0
- libxss1
- libasound2

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13089
