### ISSUE TITLE
F5 doesn't start program at all

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode#4049]
Just installed Code 0.10.10 on Windows 8.1 and installed PowerShell x86 debugger extension.
If I click the green triangle, it runs my program. If I hover over the green triangle, I get a hover message "Start (F5)", but if I press F5, I get a file explorer opened to the workspace root. I looked in Microsoft Mouse and Keyboard Center and found that the F5 key was set to the Open function. I changed the setting to Disable this key and now F5 does nothing in Code (even after restarting Code). Here is my launch.json file:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "PowerShell x86",
			"type": "PowerShell x86",
			"request": "launch",
			"program": "${workspaceRoot}\\Compare.ps1",
			"args": ["arg1", "arg2", "arg3"]
			//"cwd": ""
		}
	]
}
```

**Comment by ianwesterfield** [comment]
I've recently seen VS Code (0.10.10-insiders) F5 attach hiccup - not do anything, or take an unusual amount of time in doing so - in OSX (10.11.3). Sporadic, so can't include steps to reproduce, but will comment further if I find a situation where it is.

**Comment by isidorn** [comment]
If you open preferences > keyboard shortcuts do you see <kbd>F5</kbd> assigned to `workbench.action.debug.start`.
What happens if you assigne some other key to `workbench.action.debug.start`? Can then this other key start debugging for you?

**Comment by JanKok** [comment]
I found this in Default Keyboard Shortcuts:
```
{ "key": "f5",                    "command": "workbench.action.debug.start",
                                     "when": "!inDebugMode" },
```
I added this to keybindings.json:
```
// Place your key bindings in this file to overwrite the defaults
[
{ "key": "f6",                    "command": "workbench.action.debug.start",
                                     "when": "!inDebugMode" }
]
```
After that, pressing f6 would cause the current window to be exited, or cause Code to exit, which I guess is due to the system default "close" action of f6. I went into Microsoft Mouse and Keyboard Center and disable the default action. Then pressing f6 in Code does nothing.

**Comment by isidorn** [comment]
Does restarting vscode help? Do any of the other F actions work, like F1, F10 to step and so on.
Might you have reverse F keybindings - that you have to press fn + F to get the real F1 behavior?

**Comment by JanKok** [comment]
Thanks, @isidorn, I just needed to press F Lock on my Microsoft wireless USB keyboard.
Sorry, I had hardly ever used the F keys before now (I was wondering why F1 didn't seem to work right either!)
Has anyone else fallen into this manhole? @ianwesterfield ? If so, maybe we should find a way to avoid other people having the same problem (for example trap whatever the keyboard was sending for F5 and treat it as F5). If not, I consider this closed.

**Comment by isidorn** [comment]
Glad we found the bottom of the issue. None of the other users complained so closing
