### ISSUE TITLE
fichier 'include'

### ISSUE THREAD

**Issue by Luc-Sot** [Microsoft/vscode#40497]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299

bonjour,
pourquoi l'éditeur ne reconnait-il pas le contenu d'un fichier type include

il ne complète pas le nom des variable défini dans ceux-ci
il ne connait pas les fonction défini dans ceux-ci

ce qui pour un cross-reference n'est pas pratique

merci
Luc

**Comment by weinand** [comment]
@Luc-Sot what language/extension are you using?

**Comment by Luc-Sot** [comment]
j'utilise le language PHP 
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by weinand** [comment]
This issue was moved to felixfbecker/php-language-server#554
