### ISSUE TITLE
Output window dropdown renders buggily

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#40492]
- VSCode Version: 1.19
- OS Version: Windows, although I think it repros on Linux/Mac too.

Steps to Reproduce:

1. Install the C/C++ extension, which during installation creates a C/C++ pane in the output window. This issue repros without this step, but it's random or something.
2. Select the dropdown box in the Output pane.

Reproduces without extensions: No

Bug: The dropdown box renders buggily (the exact nature of the buggy rendering can change, i.e. sometimes it renders at the wrong location). It render correctly the 2nd time the dropdown is expanded.

![image](https://user-images.githubusercontent.com/19859882/34146156-b25cecca-e44d-11e7-896d-b04651c9e9d3.png)

**Comment by dbaeumer** [comment]
@bpasero I think that got fixed with the custom drop down you mentioned.

**Comment by isidorn** [comment]
This is a duplicate, and yes it is fixed with the custom dropdown.
