### ISSUE TITLE
I can not jump to definition.

### ISSUE THREAD

**Issue by TXZdream** [Microsoft/vscode#40496]
- VSCode Version: 1.19.0
- OS Version: win 10 latest update

Steps to Reproduce:

1. `go get -u https://github.com/golang/tour`
2. Choose a function and press F12

Reproduces without extensions: No

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-go#1414

**Comment by weinand** [comment]
Please file "go" issues against the go extension.
