### ISSUE TITLE
Support video in markdown preview

### ISSUE THREAD

**Issue by Timmmm** [Microsoft/vscode#40507]
- VSCode Version: 1.19.0

It would be nice if the markdown preview supported some kind of proper video format, so extension authors don't have to resort to massive GIFs. I would suggest that the simplest way is to use the same syntax as images, i.e. `![alt text](my_video.mp4)` and convert it to a `<video>` if the file name ends with a supported video type (I guess just `.mp4` and `.webm`). I found a (long) discussion about the syntax [here](https://talk.commonmark.org/t/embedded-audio-and-video/441/97), with no conclusion.

Alternatively, the `<video>` tag could be whitelisted, like `<b>` and `<img>` already are. That might be easier and cleaner.

**Comment by mjbvz** [comment]
We target commonmark so I'm hesitant to add any customize behavior for `![]` images. However this could be added by a markdown extension extension: https://code.visualstudio.com/docs/extensionAPI/api-markdown

The playback failure of video elements themselves if caused by #32540
