### ISSUE TITLE
Tasks: Configure Task opens menu with one item

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#40508]
I only have one tasks file with one task, so when I do Tasks: Configure Task, why does it pop up a menu with one option that I have to select?

With version 0.1.0, the only option is to open the tasks file (regardless of the number of defined tasks). With 2.0.0 it lists the defined tasks, but if I only have one, I shouldn't need to select it from the list.

It's not exactly high priority, or even particularly frustrating, but it seems wrong. 

Maybe if I type in a new task name it should create an empty task in the config file, with the correct format?

**Comment by dbaeumer** [comment]
For the configure it would make sense. To terminate or start we wanted to keep it consistent so that users see what will happen.

**Comment by alexr00** [comment]
Should also include "Show Output".

**Comment by alexr00** [comment]
To verify, open a folder that only has one task in it. Execute the Configure Task command. Verify that the tasks.json is opened to that one tasks and that no additional quick pick choose a task is shown.

**Comment by roblourens** [comment]
I am seeing a quick pick blink after running that command, which is confusing, can that be avoided?

![Oct-29-2019 15-14-35](https://user-images.githubusercontent.com/323878/67813489-e0fc1f00-fa5e-11e9-95d8-4d996eead4c1.gif)

**Comment by alexr00** [comment]
It can't be avoided without changes to the quick pick (@chrmarti) since we need to pass a promise for the quick pick items into the quick pick,. If I just pass an array of quick pick items into the quick pick then in cases where there are multiple tasks there is zero UI feedback that the tasks are loading.

**Comment by chrmarti** [comment]
@alexr00 You could keep the old QuickPick around until you know how many items you have and let that indicate progress. Currently you would have to use the new interfaces to show progress in that existing QuickPick: https://github.com/Microsoft/vscode/blame/master/src/vs/platform/quickinput/common/quickInput.ts#L142

**Comment by alexr00** [comment]
Good pointer, thank you!

**Comment by alexr00** [comment]
Will make the change with https://github.com/microsoft/vscode/issues/83648

**Comment by eamodio** [comment]
Looks good.
