### ISSUE TITLE
Clicking a newer popup bar button kills old popup bars

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#40504]
- VSCode Version: 1.19
- OS Version: Linux (probably repros with all OS's).

Steps to Reproduce:

1. I installed the C/C++ extension on a new Linux machine.

Bug: Our extension showed the important "Reload" popup, but afterward VS Code showed the unimportant popup regarding something like "Do you want to receive recommended extension" and I clicked no, but that killed the Reload popup that I didn't want to kill. Older popups that come from different sources should not be closed by newer popups (maybe this would be fine if the popup was from the same source).

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
That should not happen. How does it look like, can you capture this as a screencast?

**Comment by sean-mcmanus** [comment]
Is there a way I can trigger a VS Code popup again? I reproed it with the extension recommendation popups on a new machine, so I don't know how to get that popup to reappear.

**Comment by bpasero** [comment]
Yeah maybe if you try the steps with insiders version again: You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sean-mcmanus** [comment]
Unfortunately, installing VS Code on CentOS7 is a severe pain and gives "the file is not supported" when I try to download it. I was able to do various workaround to get it to work with the normal VS Code, but I can't remember the steps. It'd be nice if there would be a way to "reset" VS Code's stored state. uninstall/reinstall doesn't seem to do this.

**Comment by sean-mcmanus** [comment]
I tried to repro on my Ubuntu VM with Insiders, but I could not repro it -- I think it was some strange race condition regarding involving the 2nd popup. I'll follow up if I ever get another repro.
