### ISSUE TITLE
Auto forcus terminal at first time press CTRL + J (Windows)

### ISSUE THREAD

**Issue by pierreneter** [Microsoft/vscode#40509]
- VSCode Version: 1.19.0
- OS Version: Microsoft Windows [Version 10.0.16299.125]

Steps to Reproduce:

1. Open VSCode
2. Press `CTRL + J`
3. The terminal isn't focused at the first time. (Work with ``CTRL + ` ``)

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
A duplicate of https://github.com/Microsoft/vscode/issues/40416 ?

**Comment by pierreneter** [comment]
@usernamehw Looks the same but not. I will send a gif.

**Comment by usernamehw** [comment]
@pierreneter did it ever work before? I guess I've seen a similar issue before: https://github.com/Microsoft/vscode/issues/19400

**Comment by Tyriar** [comment]
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/40416 to me, please provide more info
