### ISSUE TITLE
jQuery Intellisense is incorrect

### ISSUE THREAD

**Issue by notAlaanor** [Microsoft/vscode#40506]
- VSCode Version: 1.19.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open folder
2. Initialize NPM
3. Install jQuery via NPM
4. Attempt to use jQuery selector

Intellisense suggestions for `$(".selector").` are the suggestions that should appear for `$.`, they are plainly incorrect. As far as I can tell, it began after updating to 1.19.0.

![vscodeissue](https://user-images.githubusercontent.com/17591936/34150754-6a018fc0-e4fd-11e7-9729-91fa022aebba.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Here's what I see:

![screen shot 2017-12-19 at 1 24 13 pm](https://user-images.githubusercontent.com/12821956/34179481-eeea4c10-e4bf-11e7-9422-053d9f2c364a.png)


* Are you in an html or js file?
* How are you importing `jquery`/`$`?

**Comment by notAlaanor** [comment]
I'm in a .js file & using `var $ = require('jquery')` to import jQuery.

**Comment by mjbvz** [comment]
Thanks. Looks like https://github.com/Microsoft/TypeScript/issues/20282

Closing as upstream. Will keep investigating on the TypeScript side
