### ISSUE TITLE
Delay the start-up of the shared process

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#40505]
See #40425

I have had to revert our commit via 4e3205ff36e09eeeb0ef9968679e8f4b1d6f1ba7

**Comment by sandy081** [comment]
Issue #40368 could reoccur if shared process start up is delayed.

**Comment by joaomoreno** [comment]
@sandy081 What was the problem with #40368? As far as I can see from the code, every client to the shared process should wait for it to be running. [Here's the shell, for example](https://github.com/Microsoft/vscode/blob/ce745369d0cb68ab9f07ba9bff4cbf2ae8080134/src/vs/workbench/electron-browser/shell.ts#L362).

@bpasero @alexandrudima Do you have any suggestion as to until when to delay the spawn?

**Comment by bpasero** [comment]
Yeah it would be great if the workbench could signal back some event when editors are restoring, but we currently do not have that. Who is waiting for the shared process to be ready, is it just telemetry and extensions management? We have to be careful to not introduce another deadlock area...

**Comment by joaomoreno** [comment]
Hmm it ain't the services themselves who wait but the container of them. AFAIK, both the workbench shell and the issue reporter wait for the shared process to start.

**Comment by bpasero** [comment]
@joaomoreno the workbench does not really wait right, it just runs that code in parallel to the rest of the workbench loading.

**Comment by joaomoreno** [comment]
The workbench will show. But every call to a shared process service will wait until the shared process has started serving the socket. For example, extensions won't show up in the viewlet until the shared process appears.

**Comment by sandy081** [comment]
@joaomoreno It was a guess from @bpasero analysis and also from testing/verification that removing the delay fixed the dialog issue. I do not think we have a concrete reason why is it depending on the delay.

**Comment by joaomoreno** [comment]
OK. So it seems we can easily delay it. @bpasero Can you find a signal in the main process at which point we should spawn it?

**Comment by bpasero** [comment]
@joaomoreno somewhere in [`afterWindowOpen`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L399) possibly with some delay?

Alternatively the call to opening a window ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L395)) returns the opened windows and there is a [`ready`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/windows/electron-main/windows.ts#L48) promise you could join on. That one is literally resolved when all editors have restored in VS Code.

**Comment by joaomoreno** [comment]
@bpasero But the shared process already starts only [after that `afterWindowOpen`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L448). Should we just put a timeout then? That would make this change exactly what @alexandrudima did last month. I'm not saying it's wrong, just stating the fact.

**Comment by bpasero** [comment]
@joaomoreno yes I think what should get delayed is the creation and opening of the shared process window.

**Comment by sandy081** [comment]
Just note that I have removed the uninstall dialog last milestone. So this might not be an issue any more.
