### ISSUE TITLE
auto rename html tag

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#40512]
- VSCode Version: 1.19.0
- OS Version: Ubuntu 16.04

Let say I have a pair of paragraph tag like: `<p>...</p>`, If I rename `p` to `span` on its opening tag then its closing part should be renamed to `span` automatically.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by weinand** [comment]
VS Code has no builtin functionality for this.
