### ISSUE TITLE
option to exclude a few brackets from autoClosingBrackets

### ISSUE THREAD

**Issue by krish300** [microsoft/vscode#40514]
- VSCode Version: 1.19.0
- OS Version: Windows 7

It would be great to have an option in preferences to exclude specfic type of brackets from auto closing,
basically should override the autoClosingBrackets option. 

**Something like:**
"editor.autoClosingBrackets.exclude": ['<', '{']

Reproduces without extensions: Yes

**Comment by krish300** [comment]
I would like to make this change. I never contributed opensource before. Can get a kickstart, please?

**Comment by philippHRO** [comment]
I support this. This has been annoying me for a while. VSCode doesn't let me type a closing bracked or parenthesis or the like ( ")", "]", "}") when there is already a closing symbol of the same type.

[In this WEBM](https://imgur.com/a/d3Jq9) you see me try to set another set of brackets and VSCode skips the closing bracket. This is extremely annoying.

**Comment by aviau** [comment]
Yes! I would love this.

I like auto closing brackets but not parentheses

**Comment by irrationalRock** [comment]
So if you want a quick fix, you can change the language-configuration.json file.

You need to remove what ever parenthesis you what from the `autoClosingPairs`.

**Comment by alexandrudima** [comment]
Let's track in #38352
