### ISSUE TITLE
How I can build VSCode

### ISSUE THREAD

**Issue by christianbender** [Microsoft/vscode#40519]
How I can build vscode (as developer)?
I have do the following steps.

https://github.com/Microsoft/vscode/wiki/How-to-Contribute

- VSCode Version: current repository
- OS Version: Linux Mint 

Steps to Reproduce:

I have installed all dependencies for my OS.

1. Clone the repository.
2. cd vscode
3. type ```yarn run watch ```

``` ERROR: [Errno 2] No such file or directory: 'run' ```

If I typed ``` yarn ``` I get the following error.

``` ERROR: There are no scenarios; must have at least one. ```

``` make ``` do the same .... error

**Comment by usernamehw** [comment]
Do you have the right yarn? https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

**Comment by christianbender** [comment]
@usernamehw  Thanks, in fact this was the problem.
