### ISSUE TITLE
File rename issue

### ISSUE THREAD

**Issue by ibsenleo** [Microsoft/vscode#40511]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
htmltagwrap|bra|0.0.6
path-intellisense|chr|1.4.2
githistory|don|0.2.3
prettier-vscode|esb|1.0.1
php-debug|fel|1.12.1
godot-tools|gee|0.3.4
vue-snippets|hol|0.1.5
vscode-todo-parser|min|1.9.1
python|ms-|0.9.0
vetur|oct|0.11.5
material-icon-theme|PKi|3.2.0
seti-icons|qin|0.1.3
live-sass|rit|1.1.0
LiveServer|rit|3.0.2
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5
annotator|ryu|0.11.0
todotasks|san|0.5.0
language-stylus|sys|1.8.0
wordpress-snippet|tun|1.1.2
vscode-apielements|vnc|0.6.7
vscode-todo-highlight|way|0.5.11

(8 theme extensions excluded)

---
When i try to change a file name, if i press "a" a new file is created and is not possible to edit the name even if the file name is selected for editing
Steps to Reproduce:

1. Select a name for editing from explorer panel
2. Try to set a name with "a" character

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Can you repro this when running `code --disable-extensions`?

**Comment by ibsenleo** [comment]
Hi,
Yes, it happens running code that way too.

**Comment by joaomoreno** [comment]
Can you open your Keyboard Shortcuts and find what command is being run with the `A` key?

**Comment by ibsenleo** [comment]
Indeed. "a" is binded to newFile command as user setting. 
I will remove to be able to use an `A` for file names.

The thing is my vscode configuration worked before one of the two lasts updates (don't know exactly which but max 2 updates). and suddenly stops to work.
I could be able to write with this `A` when the focus was in the file name edition/rename textbox. And when the focus was in the explorer panel, just creates a new file

It is not a very fundamental bug, but worked before and now it doesn't. 

my settings: 
```
{
  "key": "a",
  "command": "explorer.newFile",
  "when": "explorerViewletVisible && filesExplorerFocus"
}
```
Thanks

**Comment by joaomoreno** [comment]
Got it. You just need to add `&& !inputFocus` to that `when` context. 👍

**Comment by ibsenleo** [comment]
Nice, it worked! Thank you.

**Comment by mcdado** [comment]
@ibsenleo I had the same issue, but I don't remember setting those keymaps by hand. Maybe they came from the Atom Keymap extension, in my case.

**Comment by ibsenleo** [comment]
@mcdado Thanks for the answer. 
Yep. i came from atom. When i started to use vscode i installed the keymaps from that extension. Maybe that was the problem.

**Comment by mcdado** [comment]
I think it was fixed only a month ago: https://github.com/Microsoft/vscode-atom-keybindings/pull/45

That’s why who installed and uninstalled it like me but kept the keymaps the issue came out.
