### ISSUE TITLE
[theme] Copy input from theme picker when no theme was found

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#40518]
When you type theme name that you don't have installed it focuses on `Install Additional Color Themes`
![picker](https://user-images.githubusercontent.com/9638156/34160785-67818d0e-e4df-11e7-95a8-ddac7425df86.png)

But after you hit Enter your input is lost: 
`category:themes`
I suggest moving what you typed to extensions search input (excluding similar to "Install" queries?)
`category:themes palenight`
![extensions](https://user-images.githubusercontent.com/9638156/34160829-8e5940e8-e4df-11e7-916c-f35187b37aab.png)

**Comment by aeschli** [comment]
@usernamehw Did you close it intentionally?

**Comment by usernamehw** [comment]
Yep.

**Comment by aeschli** [comment]
I just happened to start working on a fix today. I will finish it after the inbox shuffling.
