### ISSUE TITLE
SelectBox doesn't close on second click

### ISSUE THREAD

**Issue by the-ress** [Microsoft/vscode#40513]
- VSCode Version: Code - Insiders 1.20.0-insider (2e55941ce82de979a1393dfce60c66b34401ff23, 2017-12-19T07:32:34.862Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Show Debug panel
2. Click the top SelectBox
[SelectBox expands]
3. Click again at the same spot

Expected result: SelectBox closes.
Actual result: It stays expanded.

It affects SelectBox on Debug and Output panels. Terminal panel SelectBox closes as expected.

**Comment by isidorn** [comment]
@the-ress thanks for the nice bug report, forwarding to @cleidigh 
fyi @bpasero

**Comment by cleidigh** [comment]
@the-ress 
Thanks, good bug find!

**Comment by cleidigh** [comment]
Fixed With: #40547

**Comment by bpasero** [comment]
@cleidigh thanks. the verified label should not be added until our endgame where we verify all the bugs we had during a milestone. I will remove it so that we can have someone else verify the bug.

**Comment by the-ress** [comment]
Thanks
