### ISSUE TITLE
Search does not respect search.exclude

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#40510]
1. Insiders, mac, open vscode repository
2. Search for something, notice that the .js files show up as result even though we have `search.exclude` configued in workspace settings to not include these

Please note that I have no user settings. And that this works properly in vscode stable on the same vscode workspace.
Assigning to december since it looks like a regression.

**Comment by roblourens** [comment]
Are those .js files open?

**Comment by isidorn** [comment]
It might be that I somehow opened those files by accident and then they were always being shown. However since I use the no-tab mode and no open editors I don't really have a notion of what is opened and what not and this is was confusing. Why do we search in open files even though they are excluded? Is this expected by users?
I think searching in the active editor might make sense, but not in all opened files imho

Removing the milestone since I can not repro this anymore without opening the files.
You can do with this issue as you see fit.

**Comment by roblourens** [comment]
It's kind of old bug https://github.com/Microsoft/vscode/issues/31819, long story. Will call it a dupe.
