### ISSUE TITLE
Ability to name individual terminal sessions

### ISSUE THREAD

**Issue by Arackow** [Microsoft/vscode#40517]
Feature request

I would like to be able to name individual terminal sessions, I sometimes have as many as 4 terminals running in the same workspace doing various things and being able to give them names would make it easier to remember what each is doing so i can navigate between them better.

Right now they all say `#: bash` which is cool to tell me which type of CLI I'm using but, for me at least, they are always going to be bash. It would be cool to see `#: bash (runserver)`, `#: bash (cronjobs)`, `#: bash (unittests)`, etc... some way to at a glance know what each is doing.

OS: Windows 10
VSCode: 1.20.0-insider

**Comment by cleidigh** [comment]
@Arackow 

There is a command for that:

Terminal: Rename

I don't think there is a default key binding so if you press F1 for the command pallet
then type Terminal and you will see all the terminal commands including rename terminal for the currently active terminal. You can rename every terminal that way.

**Comment by cleidigh** [comment]
*Duplicate: #40478
