### ISSUE TITLE
Marketplace - Unsubscribing from "[Succeeded] Extension publish on Visual Studio Marketplace" emails

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#40522]
How do I unsubscribe from the new emails being sent when an extension gets published?

I see this if I click the "unsubscribe" link at the bottom of the email: 

<img width="281" alt="screen shot 2017-12-19 at 17 15 57" src="https://user-images.githubusercontent.com/1812093/34166847-548ee40c-e4e0-11e7-9885-9e20b143cce3.png">

Unsubscribing from "Publisher contact notifications" didn't change anything, and I obviously want to receive emails about reviews and questions.

**Comment by weinand** [comment]
Yes, this new "feature" is annoying.

**Comment by Almenon** [comment]
I would want to get a message upon failure or status change rather than on success.

**Comment by vishalkiri** [comment]
@fabiospampinato, @weinand, @Almenon Apologies for delay in response. We had updated the behavior in December to following:

![image](https://user-images.githubusercontent.com/21079184/38186264-ae9a3cae-366f-11e8-9850-ddd6fb841d2f.png)

You can choose to unsubscribe from the Success and In Progress messages now.
