### ISSUE TITLE
Swipe directions are reversed for macOS

### ISSUE THREAD

**Issue by MobileVet** [Microsoft/vscode#40526]
VSCode 1.19.0
macOS 10.13.2

Steps to Reproduce:

1. Navigate to an open file
2. Click on another file to open
3. Swipe from right to left
4. Notice that one is taken 'back' to the first file.
5. Swipe from left to right
6. Notice that one is taken 'ahead' to the second file

Reproduces without extensions: Yes

Issue:
Going 'back' in a view stack should be done by swiping from left to right.  (as you are pushing the current view off to the right and going 'back' to the left)  One can consider turning the pages of a book as an example.

**Comment by MobileVet** [comment]
Interesting... turns out this may be either a macOS bug or 'feature'.  It is connected to the use of 3 fingers for the swipe gesture.  Swapping my touch pad to 3 finger 'back' resulted in this change across the system (Safari etc).  Changing it back to 2 finger 'back' reverted to the expected directions.

Ideally VS Code would support the 2 finger gesture... but that appears to be a non starter.
https://github.com/Microsoft/vscode/issues/25325
https://github.com/Microsoft/vscode/issues/25447

One thing for sure, if you run the typical setup of 2 finger 'forward' & 'back' gestures, switching to 3 finger with this macOS issue is not going to happen.  So no fancy gestures for VS Code for a while...

**Comment by bpasero** [comment]
Closing, we do not have control over the native swiping gesture of the OS.
