### ISSUE TITLE
vs code 1.19版 终端执行命令失败  

### ISSUE THREAD

**Issue by haohigher** [Microsoft/vscode#40527]
- VSCode Version:1.19
- OS Version: Win 10.0.16299.125
Steps to Reproduce:

1.本机安装的nodeJs是在d盘下，重新设置了npm安装的global和cache目录以及环境变量。全局安装eslint模块后，在系统打开的cmd窗口中运行eslint --init正常。在vs code的终端窗口中运行eslint --init提示不是内部或外部命令。

![1513707133 1](https://user-images.githubusercontent.com/23725387/34172659-c58cc320-e52d-11e7-8720-f61549b49a22.jpg)
![1513707276 1](https://user-images.githubusercontent.com/23725387/34172671-cb902d70-e52d-11e7-880a-d368f9123c89.jpg)

2. 这里似乎遇到同样问题，是通过修改环境变量解决的，但个人觉得这种解决方法似乎不是太好的解决方法。希望能得到回复指点，谢谢。
https://stackoverflow.com/questions/45354778/visual-studio-code-windows-not-detecting-global-npm-modules

Reproduces without extensions: No

**Comment by Tyriar** [comment]
You're running powershell in VS Code and cmd.exe in Windows. You can try setting cmd.exe as your shell via the "Select Default Shell" command (<kbd>F1</kbd>, "Select Default Shell", Enter)

**Comment by haohigher** [comment]
Thank you for your reply.
