### ISSUE TITLE
[Feature Request] Improve search usability by merging the global and local search widgets

### ISSUE THREAD

**Issue by yuval-gilboa** [Microsoft/vscode#40523]
Currently there are two separate search widgets, one for global search in the activity bar on the left, and one for local search inside the file editor. Each search comes with separately colored results, a separate set of keyboard shortcuts to navigate the results, etc. Both searches can be active at the same time showing mixed search results within the same file. This is confusing and cumbersome to use for most search scenarios.

To improve usability I propose to merge the two search widgets (at least as a configurable option) so there will only be a single search widget in the activity bar, with single set of search results, single set of navigation keys, etc. Just add a search scope selector (`all files` | `current folder` | `current file`), that can be used to quickly select over which file(s) the search should be performed. Consequently the local search widget inside the editor will no longer be needed and can be removed from view (solving also the overlap issue it creates with the top of the edited file).

**Comment by roblourens** [comment]
I disagree - they cover different use cases and so are optimized for different cases. Also this matches what I'd expect coming from other editors. I'll file this under https://github.com/Microsoft/vscode/issues/20530 for scoping the search viewlet.
