### ISSUE TITLE
Allow to move editor to specific group

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode#40525]
- VSCode Version: 1.19.0
- OS Version: Ubuntu 17.10

I'm coming from Sublime where I used extensively editor groups, and there were keybindings for moving an editor to specific editor group (e.g. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>1</kbd> moves an editor to the first group, <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>2</kbd> to the second etc.). Here in Code we have commands like `moveEditorToNextGroup` and `moveEditorToPreviousGroup`, along with `focusFirstEditorGroup`, `focusSecondEditorGroup` etc.

It would be handy if we could move an editor to specific group with shortcut, not only to the left/to the right with commands like `workbench.action.moveEditorToFirstGroup`, `workbench.action.moveEditorToSecondGroup` etc.

**Comment by bpasero** [comment]
I would accept a reasonable small PR for this.

**Comment by shobhitchittora** [comment]
@bpasero I'd like to work on this. Any pointers?😇

**Comment by bpasero** [comment]
Maybe take a look at `MoveEditorToPreviousGroupAction` and `MoveEditorToNextGroupAction` as inspiration in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorActions.ts#L1533
