### ISSUE TITLE
What is the correct behavior of running Code 0.10.10 from the command line?

### ISSUE THREAD

**Issue by bording** [Microsoft/vscode#4052]
As requested by @bpasero in #4006, I'm opening an issue on this.

Using 0.10.10, when I run Code from the command line without any options specified, it always reuses the existing window. To get a new window, I have to specify the `-n` option.

Based on the `--help` output, this seems to be the expected behavior, but @bpasero seemed to think that it was unusual.

I have tested this on two different Windows machines and a Mac, and the behavior is the same in all cases.

I don't have any custom user settings on any of the installations, so I don't think anything is interfering there.

As far as repro steps go it's pretty simple:

1. Make sure Code isn't running
2. Open a Command Prompt / PowerShell window / bash terminal
3. Type `code` at the prompt
4. Repeat this several times and see that the focus goes to the existing window and no new windows are opened.
5. Type `code -n` at the prompt and a new window will open.

Is this the expected behavior for 0.10.10, or is something wrong?

**Comment by Tyriar** [comment]
I think that's behaving as expected, unless the default was changed to `-n` even if it's not specified? @bpasero?

FYI here is the usage from a recent build on master, not all of these will work in 0.10.10:

```
Usage: code [arguments] [paths...]

Options:
  -d, --diff            Open a diff editor on two files.
  --disable-extensions  Disable all installed extensions.
  -g, --goto            Open the file at path at the line and column (add
                        :line[:column] to path).
  -h, --help            Print usage.
  --locale=LOCALE       Use a specific locale, "pseudo" can be used to test
                        localization.
  -n, --new-window      Force a new instance of Code.
  -r, --reuse-window    Force opening a file or folder in the last active
                        window.
  -v, --version         Print version.
  -w, --wait            Wait for the window to be closed before returning.
```

**Comment by ianwesterfield** [comment]
Just a personal preference: I think the existing behavior is perfect. Type code over and over, as suggested by @bording focuses the already open editor, however opens a new window if I `code /someotherpath`

**Comment by bpasero** [comment]
@bording for me it opens 2 windows:

![untitled](https://cloud.githubusercontent.com/assets/900690/13727949/437be39e-e907-11e5-9bbd-fc8541c8ca54.gif)

Can you doublecheck your global settings and maybe also the "code" script you use? Maybe it appends "-r"?

**Comment by bording** [comment]
Ah, the difference between what you're doing in that gif and what I'm doing is that I'm just typing

`code` and not supplying any file name.

**Comment by ianwesterfield** [comment]
@bording same here

**Comment by bording** [comment]
@bpasero If I also include a filename, then I see the behavior you show in the gif.

So, it seems like the behavior is inconsistent between including a filename and not.

**Comment by bpasero** [comment]
I see, you want to open an empty instance. Yes in that case we just give focus to the last active instance.

**Comment by bpasero** [comment]
And I am with Ian that I think this behavior is good even though not consistent.

**Comment by bpasero** [comment]
Closing as designed.
