### ISSUE TITLE
c++ auto convert Dot to ->

### ISSUE THREAD

**Issue by spphinslove** [Microsoft/vscode#40520]
- VSCode Version:1.19
- OS Version:Linux 4.14.6-1-ARCH 

![2017-12-19 22-56-55](https://user-images.githubusercontent.com/11383988/34162798-f2b83c12-e50f-11e7-8d0a-c1a7631a53fb.png)

**Comment by weinand** [comment]
Please suggest this to the C++ extension (VS Code has no builtin C++ support).
