### ISSUE TITLE
"Right click" Goto declaration is not working not ctrl+F12

### ISSUE THREAD

**Issue by thkrishn** [Microsoft/vscode#40528]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

Below are my settings json 
(I mainly use cpp to code)
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe",
    "workbench.panel.location": "bottom",
    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
    "editor.detectIndentation": false,
    "editor.tabSize": 4,
    "workbench.colorTheme": "Solarized Dark",
    "terminal.integrated.rightClickCopyPaste": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "git.ignoreMissingGitWarning": true

**Comment by Tyriar** [comment]
For C++ you'll want to report an issue to https://github.com/Microsoft/vscode-cpptools
