### ISSUE TITLE
For VSCode on windows , I have configured it to use the bash for windows ; but however the key strokes are visibly slower (on VS code BASH) when compared to using BASH on windows directly 

### ISSUE THREAD

**Issue by thkrishn** [Microsoft/vscode#40536]
- VSCode Version: 1.19
- OS Version: Win 10

Steps to Reproduce:

1.
2.
Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I think the root cause of this is in the upstream lib we use winpty which we can't do much about on our end.
