### ISSUE TITLE
Editor present bugs since last update

### ISSUE THREAD

**Issue by GitbyWe** [Microsoft/vscode#40537]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-html-css|ecm|0.1.8
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
minify|Hoo|0.3.0
Angular1|joh|0.2.0
vscode-autoprefixer|mrm|2.1.2
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
vscode-preview-server|yui|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open an existing project file (will block the editor)
2. Or launch a review on brower (with VS Code Preview Server extension)

I removed some extensions but when I preview on browser, the page doesn't stop load.

Reproduces without extensions: `Yes/`No

**Comment by weinand** [comment]
Can you repro this when running `code --disable-extensions`?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
