### ISSUE TITLE
Toggle needed to allow comments in JSON

### ISSUE THREAD

**Issue by Ngranger** [Microsoft/vscode#40538]
- VSCode Version: 1.19
- OS Version: Windows 7 & 10

Following the v1.19 update from v1.18 my JSON files that include comments now throw error messages because they aren't allowed in strict JSON. What I'd like is for a **User Setting** to be added that allows me to turn off the error messages just for the comments in the code but not for any other errors.

**Comment by aeschli** [comment]
Just use the editor mode switcher to change the mode.
![image](https://user-images.githubusercontent.com/6461412/34203528-c6faee8c-e57b-11e7-9259-1c839d4196d2.png)

You can save this in the user settings as well:
```json
    "files.associations": {
        "myfile.json": "jsonc"
    }
```
