### ISSUE TITLE
Navigating macOS voiceover to the end of VS Code using ctrl+option+right will eventually read "true true object object"

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#40535]
<img width="497" alt="screen shot 2017-12-19 at 2 11 13 pm" src="https://user-images.githubusercontent.com/2193314/34181304-95233708-e4c6-11e7-91e5-f89fbce5e58f.png">

<img width="650" alt="screen shot 2017-12-19 at 2 10 54 pm" src="https://user-images.githubusercontent.com/2193314/34181300-93be2206-e4c6-11e7-80e8-0a57c83570a5.png">

**Comment by alexandrudima** [comment]
This key combination is some form of navigating across the workbench:

![kapture 2017-12-20 at 9 41 45](https://user-images.githubusercontent.com/5047891/34198265-0a92e97c-e56a-11e7-88f3-26ef5f766033.gif)

**Comment by bpasero** [comment]
@Tyriar not reproducible for me

**Comment by Tyriar** [comment]
@bpasero when do you clear out the live region? It looks like it's not being cleared at some point. I'm starting to support voiceover in the terminal and I'm clearing when the terminal is blurred or any key is pressed.

**Comment by bpasero** [comment]
@Tyriar what is the live region? You mean the alert thing that we have in the DOM?

**Comment by Tyriar** [comment]
@bpasero yes that's the live region
