### ISSUE TITLE
Auto show tag suggestions when you type < in jsx

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#40539]
From #24524

**Feature Request**
Automatically show tag suggestions when you type `<` in a jsx file

**Comment by mjbvz** [comment]
We would likely only want to enable this for cases like:

```
(
    <div>
        <|
    </div>
)
```

where the user is typing inside of jsx already. Otherwise, we would risk triggering on the less than operator `<`

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/21012

**Comment by roblourens** [comment]
I don't understand what I should see. Seems the same as 1.23

**Comment by mjbvz** [comment]
Thanks for taking a look @roblourens. This only applies if you are inside of a jsx context already. For example try typing `<` at the `|` in:

```js
const a = <div>
	|
</div>
```

After typing the `<` you should now automatically see suggestions

**Comment by roblourens** [comment]
Oh I do see it in jsx but not in tsx, is that right?

**Comment by roblourens** [comment]
Actually, I see it in tsx in one case. But it seems kind of flaky. Trying in several files, it seems like it works in some and not others.

**Comment by roblourens** [comment]
![may-30-2018 22-08-58](https://user-images.githubusercontent.com/323878/40762544-148bade0-6456-11e8-8290-415abe7f9b54.gif)

**Comment by roblourens** [comment]
But then after reloading the window it worked
