### ISSUE TITLE
Can't debug a file with no extension

### ISSUE THREAD

**Issue by mattcdavis1** [Microsoft/vscode#40532]
- VSCode Version: 1.19.0
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. Create a debug configuration similar to below
```json
{
    "type": "node",
    "request": "launch",
    "name": "ACE",
    "program": "${workspaceRoot}/ace",
    "args": [
        "crawler",
    ],
    "console": "integratedTerminal"
}
```
2. Run debugger

Expected result: debugger runs successfully
Actual result: Debug / script execution fails on error: " because corresponding JavaScript cannot be found."

The context for this issue is that i am attempting to debug an AdonisJS console command.  The AdonisJS ships with a file name "ace" (no .js extension) which is used to run the console commands.  For example, `node ace mycommand myarg1 myarg2`.  

It's possible to workaround this issue by simply renaming the `ace` file to `ace.js` but this shouldn't be necessary.  I don't see why VSCode can't just run the file without an extension.  Other very popular projects that have a similar approach to the console file naming (no extension) are Laravel (artisan - no `.php` extension) and Yii (yiic - no `.php` extension).

**Comment by weinand** [comment]
you have two options:
- add the "shebang" `#! /usr/bin/env node` as the first line to "ace". With this VS Code should recognise the file as JavaScript.
- move the "program" attribute to the "args" attribute:
```
{
    "type": "node",
    "request": "launch",
    "name": "ACE",
    "args": [
        "${workspaceRoot}/ace",
        "crawler",
    ],
    "console": "integratedTerminal"
}
```

**Comment by mattcdavis1** [comment]
got it - thanks!
