### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode#4053]
Something that seems to be missing (and I would have found helpful as I was setting up and learning how to use Code) is an overview of the setup steps needed to create a usable code development environment. The documentation is very clear about how to add a debugger, but I had several questions about how to get other things set up. As an example of what I would like to see, this could be added to the Next Steps section near the end of docs/editor/setup. (I'd recommend moving the Additional Tools section after Next Steps section):

### Next Steps
- Read The Basics - Basic orientation around VS Code
- Add a debugger for your programing language (link to Debugger page)
- Customize the launch.json and tasks.json files for your development environment and workflow. See (here) for essential information about the syntax and available parameters that can be used in these files. **<-- This documentation is badly needed by those of us who aren't familiar with JSON**.
 - Customize launch.json to launch your application and supply command line arguments. (link)
 - Customize launch.json and tasks.json with a preLaunchTask that can build your application before running it. (link)
 - Customize tasks.json with a problem matcher to allow stepping through compiler errors and quickly navigating to the error locations in your source code. (link)
 - Customize for source control (link)
- Add an IntelliSense extension to provide "code understanding," highlight syntax errors in your code, help you find definitions of code objects (variables, functions, types...), etc. (link)
- Read Editing Evolved which introduces the features of IntelliSense.

(Put the Additional Tools section here.)

**Comment by Tyriar** [comment]
This issue was moved to Microsoft/vscode-docs#228

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/vscode-docs/issues/228
