### ISSUE TITLE
IFileService.watchFileChanges stops watching when there are more than one watcher

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#40533]
File watching using [IFileService](https://github.com/microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L142) does not work when there are more than one watchers watching the same file and one of them [stops watching](https://github.com/microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L147).

Steps to Reproduce

- Watch a file using [fileWatching](https://github.com/microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L142) at two different places. 
- Stop watching the file at one of the place.

Expected: Watching should continue as one of the watchers is still there.
Actual: Watching is stopped

Steps to Reproduce (in Product)

- Open VS Code in Verbose mode
- Open Log (Window) in Output channel
- Open the file associated to this channel using the action in the output panel
- Toggle side bar couple of times and see that Channel and File editor are updated
- Close the Panel
- Toggle side bar again couple of times

Expected:  File editor should be updated.
Actual: File editor is not updated.

**Note:** This is also true when you close the File editor instead of Panel and output panel does not get updated.

Underneath, output panel and file editor are using file watching and one of them is stopping watching when they no longer need it.

**Comment by bpasero** [comment]
@sandy081 yeah sucks, probably needs some ref counting and ideally instead of an `unwatchFileChanges` we just return a `IDisposeable`. There is also additional complexity that within the watching we [detect a delete](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L1010) and then recreate the watcher under the hood.

If you wanna drop in with a PR, let me know.

**Comment by sandy081** [comment]
Sure, let's do it.

**Comment by bpasero** [comment]
@sandy081 pushed a change to do ref-counting, let me know how it goes 🏄
