### ISSUE TITLE
The integrated terminal cannot find certain files (commands)

### ISSUE THREAD

**Issue by rakesh-k** [Microsoft/vscode#40544]
- VSCode Version: 1.19.0
- OS Version: linux-mint 4.10.0-38-generic

Steps to Reproduce:

1. cd /usr/bin
2. ls go

Within integrated terminal:

```
rakesh@linux-mint /usr/bin $ ls go
ls: cannot access 'go': No such file or directory
rakesh@linux-mint /usr/bin $ ls -ld .
drwxr-xr-x 2 nfsnobody nfsnobody 36864 Dec 31  1969 .
rakesh@linux-mint /usr/bin $
```

in an external shell:
```
rakesh@linux-mint /usr/bin $ ls go
go
rakesh@linux-mint /usr/bin $ ls -ld .
drwxr-xr-x 2 root root 69632 Dec 19 21:50 .
rakesh@linux-mint /usr/bin $ 
``` 

Wonder why the id's are diff for the /usr/bin directory under the integrated terminal.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Do you know what nfsnobody is? My guess is this is something to do with users/permissions and the fact that the VS Code terminal is inheriting the environment from VS Code.

**Comment by rakesh-k** [comment]
the nfsnobody is the group-id 65534 and actually it is listed as nogroup within the /etc/group file. But I am surprised as to why the integrated terminal can not find the files within the directory when it has the right permissions? 

Linux mint installation shows the programs under the startup menu and I execute from there rather than from shell. Do let me know what other information can I provide and would be glad to do so.

**Comment by Tyriar** [comment]
@rakesh-k does the same thing happen when you launch from a terminal?

**Comment by ishunyu** [comment]
@rakesh-k I had the same problem when I installed vscode from the Software Manager. Instead I used the independent deb file to install and the problem went away.

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/44646, the problem is with the unofficial flathub package. Using the official deb instead as @ishunyu suggests is the fix.
