### ISSUE TITLE
Integrated terminal: Vscode don't open automatically another terminal when run multi Python files concurrently

### ISSUE THREAD

**Issue by xuananh-viosoft** [Microsoft/vscode#40543]
- VSCode Version: 1.19.0
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Run first Python file in Integrated terminal
2. Run second Python file, command issue at the same terminal, it should open automatically second terminal to run second Python file

Reproduces without extensions: No

**Comment by Tyriar** [comment]
How are you running the python file?

**Comment by xuananh-viosoft** [comment]
I right click on first Python file and choose "Run Python File in Terminal", Terminal appear with python command to run this file.
Then I do right click on another Python file and choose "Run Python File in Terminal". The command to run the second file issue at the same Terminal.
