### ISSUE TITLE
Can't distinguish from SCM repositories with the same name

### ISSUE THREAD

**Issue by anthonymclaughlin** [microsoft/vscode#40548]
After adding the various folders paths and names in the workspace settings file:

<img width="245" alt="workspace-settings" src="https://user-images.githubusercontent.com/3053515/34190492-efbb9bf4-e4f5-11e7-8da6-c5bc4a99d0ef.png">

The user is presented with a nice list with the desired names displayed:

<img width="301" alt="workspace" src="https://user-images.githubusercontent.com/3053515/34190491-efa4bc86-e4f5-11e7-836f-c0508e7ca300.png">

Upon switching to the source control tab, the folder's corresponding git repository is shown with only the last part of its path as its name:

<img width="289" alt="source-control-providers" src="https://user-images.githubusercontent.com/3053515/34190490-ef91a54c-e4f5-11e7-9206-c451c5a87302.png">

As you can see, if the folders that are added to the workspace have similar names at the end of their paths it will cause a bit of confusion!

It would be nice if the Source Control Providers either picked up the "name" portion of the workspace folder or took it's name from a separate setting in the `.code-workspace` file.

**Comment by joaomoreno** [comment]
Yeah we definitely need a distinguishing factor. I wouldn't allow to rename, though.

We may just have to do a better job at showing where the root of each repository is.

**Comment by kumarharsh** [comment]
Perhaps the same logic which was used to detect and display the tab names (https://github.com/Microsoft/vscode/issues/12040) can be used here?

**Comment by G018** [comment]
Hello! @juliapagnucco and I were planning to tackle this issue for a Software Engineering class at the University of Michigan with Prof. Wes Weimer. It seems like the displayed identifiers can still be ambiguous (we were able to replicate the issue) and like we wouldn't be stepping on anybody toes (hopefully). Although not tagged "good first issue", it seems attainable within a few weeks so we hope to make a PR soon, but let us know if there are any tips or guidance. Thanks!
