### ISSUE TITLE
workbench.files.action.closeFile closes all split editors, not just the active file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#4054]
This is likely happening due to the recent change that makes closeFile close editors so it can close things like the default keybindings. When the command is run on a split editor it should only close the active editor.

cc @bpasero

**Comment by Tyriar** [comment]
It seems to work sometimes. I notice it happens when the file in each split editor is the same.

I also managed to get it into a broken state where it refused to close the active file. This happened when I had 3 editors open on a small css file.

**Comment by bpasero** [comment]
@Tyriar if you can give me steps for the broken case please file a separate issue.

We actually close any file that is opened when you invoke "Close File". I add this to the list of UX issues we have around "Close File" vs "Close Editor".

**Comment by bpasero** [comment]
#224 should address this too
