### ISSUE TITLE
Integrated terminal display malfunction

### ISSUE THREAD

**Issue by michmich112** [Microsoft/vscode#40542]
- VSCode Version: 1.18.0
- OS Version: OS X El Capitan 10.11.6
- Machine: Mac Book Pro (early 2015, not the one with only USB-C)
- What I am using: zsh with Oh-My-Zsh (latest)

When disconnecting from a display integrated terminal becomes blurry and when trying to input or resizing the terminal, display becomes raw un-organized UTF-8 characters (with the wrong font size)
When typing A (U+0041) it displays z(U+007A)
typing z (U+007A) gives us å(U+005E)
typing x (U+0078) gives us á(U+00E1)
(checked and there are no apparent correlations bitwise or spanwise)

Steps to Reproduce:

1. Connect mac to display (HDMI cable) and close the laptop to only use the attached display
2. Use VSCode a bit
3. Disconnect the cable and open up your laptop -> the terminal can't display correctly :(

Way to make it work again: open a new tab and close your old one.

![image](https://user-images.githubusercontent.com/20456444/34187701-b15c60d6-e500-11e7-983e-f12941f84f8f.png)

![image](https://user-images.githubusercontent.com/20456444/34187750-f1177f30-e500-11e7-9732-4f9a032d5214.png)

![image](https://user-images.githubusercontent.com/20456444/34187713-c0be7122-e500-11e7-87e8-f350f7243f2e.png)

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
