### ISSUE TITLE
  打开文件夹直接闪退 Open folders directly flicker

### ISSUE THREAD

**Issue by parker-wang** [Microsoft/vscode#40556]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
vscode-eclipse-keybindings|alp|0.9.6
markdown-preview-github-styles|bie|0.1.0
translation|dus|0.0.4
code-runner|for|0.8.5
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.1.1
python|ms-|0.9.1
vscode-jsp|pth|0.0.2
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@parker-wang can you share more details what happens?
