### ISSUE TITLE
[Feature Req] Allow running code in customizable external command prompt.

### ISSUE THREAD

**Issue by 1600** [Microsoft/vscode#40558]
Currently user can only invoke standard command prompt in windows via:

`{ "key": "ctrl+shift+c",          "command": "workbench.action.terminal.openNativeConsole",
                                     "when": "!terminalFocus" },`

There are ways to run code directly in customized integrated console but it seems you can't do the same for external command prompt such as cmder or git bash.

**Comment by Tyriar** [comment]
Good candidate for an extension, no plans to add this to the core editor.
