### ISSUE TITLE
Syntax highlighting in groovy code breaks

### ISSUE THREAD

**Issue by nickoz5** [Microsoft/vscode#40551]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|1.4.6
Go|luk|0.6.70
python|ms-|0.9.1
cpptools|ms-|0.14.5
PowerShell|ms-|1.5.1

---

Steps to Reproduce:

1. The following line of code is causing the syntax highlighting to fail for all subsequent lines of code in a groovy script file:

`{ it / excludedRegions("/build/.*\r\n/src/${branchPath}release/product/Hotfixes/.*") }`

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/groovy.tmbundle#14
