### ISSUE TITLE
Extension was automatically removed (probably upgrade issue)

### ISSUE THREAD

**Issue by schlamar** [Microsoft/vscode#40554]
- VSCode Version: 1.19.0
- OS Version: Win 7, 64bit

Yesterday, I had VSCode with Python extension v0.9.0. Today, I started VSCode and the Python extension was missing. 

I assume this is some upgrade issue. VSCode wanted to install v0.9.1 but failed and the old version was already removed.

I checked the output view, the development tools console and %APPDATA%\Code\logs, but couldn't find anything relevant.

**Comment by sandy081** [comment]
@schlamar 
- Can you please check in your extensions folder what extension do you have there?
- We never remove an extension during update. By any chance have you uninstalled the extension before from any open window?

Can you please try following steps to reproduce it
- Open the extension folder
- Change the version in the name of the python extension to `0.9.0`
- Open `package.json` under the python extension folder
- Also change the version here to `0.9.0`
- Quit and restart VS Code

This will trigger the update to `0.9.1` and let's check if you see the issue

**Comment by schlamar** [comment]
> Can you please check in your extensions folder what extension do you have there?

![ext](https://user-images.githubusercontent.com/238652/34200786-a22267ce-e572-11e7-82b3-41c83965fbba.png)

> We never remove an extension during update. By any chance have you uninstalled the extension before from any open window?

No.

> Can you please try following steps to reproduce it

Mhh, this does a proper update, so I can't reproduce it...

**Comment by sandy081** [comment]
Hmm everything looks good.

I would add more logs to the system during install flow and next time you see it, hope the logs will help out what is happening.

May I know if you are ok with that?

**Comment by schlamar** [comment]
Yes, just tell me what I should do :)

**Comment by sandy081** [comment]
Please install the latest insiders and when you see this issue again please provide us the logs. You can see the logs in the Output channel.
