### ISSUE TITLE
Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again.

### ISSUE THREAD

**Issue by benqzq** [Microsoft/vscode#40550]
I use Windows10 home in English, build 16299.125.

I get the following message each time I try to change a color theme:

> Unable to write into user settings. Please open User Settings file to correct errors/warnings in it and try again.

But my user settings does indeed seem writable, as I've already went to `File > Preferences > Settings` and added under "_User Settings_" the following code, and saved without problem:

```
{
    "window.zoomLevel": 1
    "editor.minimap.enabled": false
}
```

Given my user settings are indeed **writable,** I don't understand why I get the above error when changing a color theme. I'm just a humble student for web development, not a local software developer, and it seems to me like a bug it was important for me to report.

I read I might need to create a settings.json file but as said, I can already change my settings so it seems such file was already created by VSCODE, but just isn't writable when I try to change a color theme so it seems to me like a bug.

**Comment by usernamehw** [comment]
Have you tried adding a comma after property?
```diff
- "window.zoomLevel": 1
+ "window.zoomLevel": 1,
```

**Comment by benqzq** [comment]
Much thanks @usernamehw , indeed, I've added the comma before the first command there and no longer had an error indication (red diagonal line under `"editor.minimap.enabled"`) and could change color scheme successfully.

I understand VSCODE will add a coma after the last one as well but just as a principle I've added commas after both commands.
