### ISSUE TITLE
Cannot compare changes for git conflicts after upgrade to 1.19

### ISSUE THREAD

**Issue by tanmaybhatt** [Microsoft/vscode#40557]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.4.0-103-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.0.4
vscode-eslint|dba|1.4.3
vscode-protractor-snippets|dee|1.0.5
tslint|eg2|1.0.24
vscode-cosmosdb|ms-|0.3.0
azure-account|ms-|0.2.2
debugger-for-chrome|msj|4.0.0
autoimport|ste|1.5.3
JasmineSnippets|xab|1.0.1

---

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Please provide steps how to reproduce.
What is the problem you are seeing?

**Comment by tanmaybhatt** [comment]
So, when you merge two branches on git, you see conflict in the source control section.

![screenshot from 2017-12-21 10-55-01](https://user-images.githubusercontent.com/16023331/34241735-81c66f54-e63d-11e7-9532-1db558736b09.png)

Now when I click Compare changes on the conflict in the file, I get this error

![screenshot from 2017-12-21 10-57-14](https://user-images.githubusercontent.com/16023331/34241759-bfe75ad2-e63d-11e7-954a-f5f17f7d9e6f.png)

And it is happening with all my team members on version 1.19

**Comment by ambroselittle** [comment]
Also happens on Windows 10 x64 v1709 Build 16299.192 and VS Code v1.19.1.

**Comment by atzex** [comment]
#me2
