### ISSUE TITLE
Broken font

### ISSUE THREAD

**Issue by ekevjn** [Microsoft/vscode#40555]
- VSCode Version: 1.19.0
- OS Version: Ubuntu 16.04

This is my VS screenshot:
![screenshot from 2017-12-20 14-32-20](https://user-images.githubusercontent.com/8857062/34196098-27598862-e593-11e7-9bc8-f332d8778a47.png)

I done those step below but nothing work
- Tried to lunch VS with command "code --disable-extensions"
- Tried to change my screen resolution
- Tried different font-family

Reproduces without extensions: Yes

Any help is greatly appreciated.

**Comment by ekevjn** [comment]
I found that it cause by system system kernel, not VS itself. So i close this issue.

**Comment by teguhteja** [comment]
sorry @bpasero for open this ticket

hello @ekevjn 
how to solve this problem? i have some issue with this

**Comment by ekevjn** [comment]
Hi @teguhteja, i tried to install some packages that damaged my system and some how cause ubuntu render broken font. Since i don't have time for fixing brokens kernel lib one by one so i boot into ubuntu install disk and let it recover broken lib for me. Sorry that i don't have specific answer for you.

**Comment by teguhteja** [comment]
@ekevjn thank you for your advice. 
i think will do what you suggest.

**Comment by teguhteja** [comment]
hai @ekevjn 
i found the problem from github too. thank you for keyword so i can search in google
here go : https://github.com/Microsoft/vscode/issues/35675

so the problem is bug in skiia and if we want font in vscode not bad we must downgrade the libfreetype6
