### ISSUE TITLE
PHP syntax highlight is wrong when comment out at last line of MySQL query string

### ISSUE THREAD

**Issue by vuongggggg** [Microsoft/vscode#40564]
- VSCode Version: 1.19.0 (x64)
- OS Version: Windows 10

Steps to Reproduce:

1. Write the MySQL query in a string and comment out look like below picture.
![wrong_syntax_highlight](https://user-images.githubusercontent.com/3168632/34200610-4f39176a-e5a4-11e7-9ee2-757a740655ee.PNG)
2. The syntax highlight apply for below lines will be wrong. In above picture, `$askName` is right, `$askAge` is wrong.

Reproduces without extensions: **Yes**

**Comment by usernamehw** [comment]
1. Don't post code as screenshot
2. You didn't close double quote
```php
$sql = "SELECT * FROM users
        WHERE `username` = 'Vuong'
        --OR `age` = 20";
        ";
$askAge = "How old are you?";
```

**Comment by mattacosta** [comment]
No, the string is quoted correctly. The SQL highlighting should end at the closing double quote.

Also, you should file this issue over at [atom/language-php](https://github.com/atom/language-php).

**Comment by roblourens** [comment]
It's not really clear that this is a bug, when a multiline string is not terminated.

**Comment by vuongggggg** [comment]
@roblourens Did you read the comment of @#mattacosta ?

**Comment by roblourens** [comment]
Works in Atom, but not in vscode with the same grammar.

**Comment by roblourens** [comment]
Works now
