### ISSUE TITLE
Multi-root: Search for file names with same name can't include "project name" in search terms

### ISSUE THREAD

**Issue by perlun** [Microsoft/vscode#40565]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383)
- OS Version: Darwin x64 17.2.0

Steps to Reproduce:

1. Create a multi-root workspace with multiple projects that has a file name with the same name.
2. Press Cmd-P (on Mac) to search for a file:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/630613/34200946-9e20db0c-e57b-11e7-8ce9-b33a14370342.png">

It _works_, but what if I want to be able to search for a file in a particular project?

<img width="866" alt="image" src="https://user-images.githubusercontent.com/630613/34200975-aef42fba-e57b-11e7-85c9-a6ebd5f4cfa2.png">

IMHO, the search function should include the "project name" as part of the searchable tokens somehow, so that you can find files _in a particular project_ if you happen to know its name.

(This is more of an annoyance than a huge problem. I just started to use multi-root workspaces the other day, a great feature - thanks a lot for implementing it! 🍰)

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/32444 - I really want this too.

**Comment by perlun** [comment]
Ahh, thanks @roblourens - I didn't realize that it was the same. Eagerly awaiting Santa Claus! 😉
