### ISSUE TITLE
Save AS

### ISSUE THREAD

**Issue by fernandobenato** [Microsoft/vscode#40569]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:44.860Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
classic-asp|ili|0.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.3.0
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
java|red|0.16.0
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1. paste xml in new file.
2. select language XML
2. format document
3. SAve as
4. program fail

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Can you repro this when running `code --disable-extensions`?

**Comment by fernandobenato** [comment]
Hi, I had not run with code --disable-extensions.
I took the test now disabling all extensions and it worked, correctly. Thank's.

**Comment by weinand** [comment]
Try to enabled one extension at a time to find the extension that has the problem.
Then file the bug against that extension.
