### ISSUE TITLE
Display a window with the list of all the available VS Code Predefined Variables along with their current values.

### ISSUE THREAD

**Issue by Harsha-Yalagach** [Microsoft/vscode#40567]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 3.10.0-693.11.1.el7.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-processes|and|0.0.4
cpptools|ms-|0.14.5

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
What do you mean by vs code predefined variables? You mean available when you are developing an extension?
