### ISSUE TITLE
Terminal doesn't create link to file if it's path contains non letter-or-digit symbols.

### ISSUE THREAD

**Issue by dmitryshunkov** [Microsoft/vscode#40560]
- VSCode Version: 1.19.0
- OS Version: Microsoft Windows [Version 10.0.17046.1000]

Steps to Reproduce:

1. Run any command in terminal window with full path in result (for example `dir | select FullName`).
2. Point on any file item in result.
3. If path contains non letter-or-digit symbol (for example '+'), no link is present.

![image](https://user-images.githubusercontent.com/22297233/34198192-22f29636-e572-11e7-8cc2-4732687f7b21.png)
![image](https://user-images.githubusercontent.com/22297233/34198214-3873dc40-e572-11e7-8e63-f2a8c55a8829.png)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Right now link detection is done via a regex here https://github.com/Microsoft/vscode/blob/07e0ad322475d1019f3dbf4761e614e9c9523d76/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L22

`+` is more likely to separate a path than be part of a path so it's not included in the allowed characters list. Eventually I hope the link detection will get a lot better by using a proper parser to scan the text to find the links, let's close this out in favor of https://github.com/xtermjs/xterm.js/issues/583 as that's the first step in improving the links.
