### ISSUE TITLE
File unloaded when using Quick Open ⌘P (inFilesPicker && inQuickOpen)

### ISSUE THREAD

**Issue by growdigital** [Microsoft/vscode#40566]
- VSCode Version: 1.19.0
- OS Version: Mac OS 10.13.1

Steps to Reproduce:

1. Press shortcut ⌘P to bring up Quick Open (workbench.action.quickOpenNavigateNextInFilePicker)
2. Type part of filename to bring up list of files to open
3. Navigate to file, press return ↵
4. File loads
5. Press shortcut ⌘P to bring up Quick Open 
6. Type part of filename to bring up list of files to open
7. Navigate to file, press return ↵
8. **If previous file is unedited**, it is unloaded, replaced by latest file

"Proper" behaviour would be to leave previous file(s) in editor. This is probably a feature request!

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

or

`"workbench.editor.enablePreviewFromQuickOpen": false`

**Comment by growdigital** [comment]
ahhh, thank you, that really helps 👍
