### ISSUE TITLE
Hashtag "#" in path breaks intellisence

### ISSUE THREAD

**Issue by kristjan-halldorsson** [Microsoft/vscode#40568]
- VSCode Version: 1.19.0
- OS Version: Windows 10

I'm working with powershell scripts.

Steps to Reproduce:

1. Put a hashtag "#" in the path where the source code is. Ex. "C:\\#temp\source\..."
2. Try the intellisence, it won't work. Loading symbols won't work either (CTRL+SHIFT+O and CTRL+T).

Reproduces without extensions: Didn't try it
Only have one extension: Powershell 1.5.1

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#1129
