### ISSUE TITLE
Have a global command which triggers the About dialog, or shows version information

### ISSUE THREAD

**Issue by thibran** [Microsoft/vscode#40574]
- VSCode Version: 1.19.0
- OS Version: openSUSE Tumbleweed (Linux)

Steps to Reproduce:

1. press `Ctrl+Shift+P`
2. enter "version"
3. results in no entry, but should

As enhancement it would be nice if the show-all-command would have an entry to display the Visual Studio Code version (I know that I could pass the `--version` flag on the command-line).

Such a feature exists e.g. in Emacs, where it is possible to enter `M-x version` and get the current Emacs version displayed.

**Comment by shobhitchittora** [comment]
@joaomoreno I'd like to take this up. Any pointers? 😇

**Comment by joaomoreno** [comment]
No need to execute `code --version`, that information can be obtained by requiring `vs/platform/node/package`. Output is good, but a [message box](https://github.com/joaomoreno/vscode/blob/tree-list/src/vs/platform/windows/electron-browser/windowService.ts#L123) is better.

**Comment by shobhitchittora** [comment]
@joaomoreno raised a PR. Currently added in the action under `Shell Command`.  Any better section to add this in?
