### ISSUE TITLE
Missing icons in the sidebar

### ISSUE THREAD

**Issue by mubaidr** [Microsoft/vscode#40577]
- VSCode Version: 1.20
- OS Version: Windows 10

Steps to Reproduce:

1. Don't know what caused this
2. Only one icon at a time is being shown in the sidebar (Explorer, SCM, Debug, Extensions, Search)
3. When I choose one of the  (Explorer, SCM, Debug, Extensions, Search) from the view menu, its icon is shown in the sidebar than others are hidden. 

Reproduces without extensions: Yes

![capture](https://user-images.githubusercontent.com/2222702/34206704-7d686d66-e5a9-11e7-9fa1-5e727586352b.PNG)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/40531

As a workaround right click -> enable all the views
And let me know if you would like to do a live debugging session with me via skype
