### ISSUE TITLE
Add possibility to have two programming languages at a time in a singular file

### ISSUE THREAD

**Issue by mortinger91** [Microsoft/vscode#40576]
- VSCode Version: 1.18.1
- OS Version: Debian 10 testing

Steps to Reproduce:

1. select a language
2. be on a file of some language

Reproduces without extensions: Yes

When i'm on a .php file for example, php language get detected from the extension of the file, but if i want to debug some html inside that same file i need to manually change language to html, same if i want to debug some js script inside that same file. It would be great that vscode automatically detects the language not only from the file extension but also from what part of the file i'm in with the cursor. In a php file use php if i'm between php tags, or html if i'm out or javascript if i'm inside a script element with type="javascript".
Of course it would be good to have that feature enabled or disabled via a string in the setting file.

**Comment by octref** [comment]
I don't have php debug experience. I guess you could come up with more concrete use cases (such as a small repo and steps as to how you are debugging it), and create an issue for https://github.com/felixfbecker/vscode-php-debug.
