### ISSUE TITLE
Markdown preview: fixed font styling?

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#40578]
Is there a way to change the fixed font styling?

It doesn't change size when markdown.preview.fontSize is set.

**Comment by mjbvz** [comment]
What setting value are you using? Here's what I see after saving a new font in my user settings:

<img width="876" alt="screen shot 2017-12-20 at 10 59 24 am" src="https://user-images.githubusercontent.com/12821956/34223619-db8471f4-e574-11e7-9fb1-4fe627f2a635.png">

**Comment by Gruntfuggly** [comment]
I mean the font which is displayed when you use fixed font formatting - enclosed in back ticks

e.g. 

```
Alternatively, open Visual Studio code, press `Ctrl+P` or `Cmd+P` and type:
```

produces:

![image](https://user-images.githubusercontent.com/376658/34315781-f19c02e0-e77c-11e7-9254-4c89725abf7c.png)

**Comment by mjbvz** [comment]
The font for code in the markdown preview is taken from `editor.fontFamily`. You can override this by using your own css: https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css
