### ISSUE TITLE
Problem passing args to PowerShell program in launch.json

### ISSUE THREAD

**Issue by JanKok** [Microsoft/vscode#4057]
I'm trying to use Code on Windows to develop a PowerShell script. I encountered some difficulties when I tried to cut and paste a Windows path into the "args" parameter in my launch.json file.
1. I had to change "\" to "\\\\" to avoid a syntax error. That's inconvenient and ugly.
2. I haven't found a way to pass a space (blank) character embedded within a single argument.
3. The (x86) in the path causes PowerShell to give an error: x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program.

So if my launch.json file contains:
```
		"type": "PowerShell x86",
		"request": "launch",
		"program": "${workspaceRoot}\\Compare.ps1",
		"args": ["C:\\Program Files (x86)", "arg1a arg1b"]
```
And the program is
`Write-Output "args:", $args`
Then when I run it, I get
```
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:48
+ c:\Src\Tools\BnA\Compare.ps1 C:\Program Files (x86) arg1a arg1b
+                                                ~~~
```
On the other hand, if I call my program from a PowerShell window, it parses the command line with two arguments just as I want:
```
PS C:\Src\Tools\BnA> Compare.ps1 "C:\Program Files (x86)" "arg1a arg1b"
args:
C:\Program Files (x86)
arg1a arg1b
PS C:\Src\Tools\BnA>
```
I think there are some bugs here, but maybe also a limitation in the allowed json file syntax. Right now single quotes aren't allowed in the json file for quoting strings. Would it be possible to have single quotes be a "stronger" type of quote mark that avoid any sort of interpretation, string substitution, etc. as much as possible, so file paths and other sorts of strings with funny characters can be passed in to the target program without a struggle?

**Comment by weinand** [comment]
@JanKok the PowerShell is not part of VS Code. Please move this bug to https://github.com/PowerShell/vscode-powershell/issues

**Comment by JanKok** [comment]
I think the real problem is lack of documentation about the format of the json files. In this particular case, I needed to know how to pass filenames containing various funny characters to the target program. This is a problem with ALL target programs and tasks regardless of language, hence, it should be documented primarily by VSCode team. I'll file an issue with vscode-docs.

**Comment by weinand** [comment]
@JanKok VS Code only prescribes the fact that launch.json is a json file. The structure and semantics of individual launch configs is contributed by individual debugger extensions via a schema and individual interpretations in the debug adapter.
So the PowerShell debug adapter could accept forward slashes on Windows (like the node debug adapter). 
Not being able to pass a space (blank) character embedded within a single argument is definitely a problem of the PowerShell adapter and not a problem of a lack of documentation of the json format.

**Comment by JanKok** [comment]
Thanks for the clarification. That's good to know.
The fact that both the PowerShell and code-debug (C/C++, gdb) extensions implemented argument passing in non-obvious ways indicates a need for some guidance from the VSCode team.
I'll add to my issue at vscode-docs and file issues at vscode-powershell and code-debug, but I bet most of the extension projects need to know about this issue, namely
* need for detailed documentation of launch.json and similar files, in particular regarding how args are passed, and
* (possibly) a need to modify how args are passed to adapt to the needs of the individual languages (but I'd prefer to see this done in a consistent way across all languages - hence my call for guidance from VSCode team).

**Comment by rkeithhill** [comment]
You can use forward slashes in a path with PowerShell. WRT can you try putting single quotes inside the double quotes e.g. `"'C:/program files (x86)'"`.

**Comment by weinand** [comment]
@rkeithhill in node-debug and mono-debug the debug adapter takes care of quoting arguments if they contain spaces. So 

```json
"args": [ "-g", "foo", "bar", "hello world" ]
```

will just work on all platforms and terminals.

**Comment by cdutta** [comment]
thanks @weinand
