### ISSUE TITLE
Checking for updates gets stuck after hibernating Windows

### ISSUE THREAD

**Issue by bermicallef** [Microsoft/vscode#40571]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
csharp|ms-|1.13.1
sass-indented|rob|1.4.5
jsx|Twe|0.0.1
ReactSnippets|xab|1.7.0

---

Steps to Reproduce:

1. Launch vscode
1. Hibernate Windows
2. Restore previous session by starting the machine
3. Check for updates (unless context menu is already stuck)
4. Context menu gets stuck in "Checking for Updates..." state

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/25632
