### ISSUE TITLE
problem with snippets regex

### ISSUE THREAD

**Issue by asaadmohammed74** [Microsoft/vscode#40570]
i want to make a snippet that give the path of current open file relative to ${workspaceRoot}/src so i made this
```
{
"get path": {
		"prefix": "gp",
		"body": [
			"${TM_DIRECTORY/.*src(.*)/$1/}",
		]
	}
}
```
this work's but for files like `/home/username/MyProject/src/dir1/dir2//foo.cc` this gives `/dir1/dir2` so i changed it to this
```
"get path": {
		"prefix": "gp",
		"body": [
			"${TM_DIRECTORY/.*src[\/](.*)/$1/}",
		]
	}
}
```
so now i expect it to show `dir1/dir2` instead it expands to this `${TM_DIRECTORY/.*src[/](.*)//}` and this happen with any regex that contain `\/`

same with this `"${TM_DIRECTORY/[\/](.*)/$1/}",` expands to `${TM_DIRECTORY/[/](.*)//}`
and for some reason this `${TM_DIRECTORY/.*src[\\/](.*)/$1/}` works and expands to `dir1/dir2`
but on `https://regex101.com` this is invalid

**Comment by jrieken** [comment]
Good find... Seems to be a problem with not seeing the escape character...

**Comment by jrieken** [comment]
This is actually not an issue with missing the escape character but the lack of yet another escaping backslash. In JSON, to encode a backslash you need another backslash. So, change you snippet to `${TM_DIRECTORY/.*src[\\/](.*)/$1/}` will do the job. Sorry for not seeing this immediately.

**Comment by jrieken** [comment]
This is another reasons to investing in tooling that helps when writing snippets: #16702
