### ISSUE TITLE
Node types keep getting lost

### ISSUE THREAD

**Issue by marcoms** [Microsoft/vscode#40586]
After a while using VSCode, hovering over Node symbols like `require` will yield `any`, where they used to show `NodeRequire` instead. Likewise all intellisense for Node will be lost.

I can fix this by removing the `~/.cache/typescript` dir and allowing it to be regenerated, but it keeps happening. Looks like a VSCode bug since the contents of the typescript folder look good.

![screenshot from 2017-12-20 16-13-11](https://user-images.githubusercontent.com/4211302/34216692-f81c8f64-e5a0-11e7-9efa-66f03d1d1dbf.png)

After removing `~/.cache/typescript`:

![screenshot from 2017-12-20 16-16-11](https://user-images.githubusercontent.com/4211302/34216759-2d20db48-e5a1-11e7-968e-ad2d12f27b60.png)

```sh
$ ls -a ~/.cache/typescript
./  ../  2.6/

$ ls -a ~/.cache/typescript/2.6/
./  ../  node_modules/  package.json  package-lock.json

$ cat ~/.cache/typescript/2.6/package.json
{
  "dependencies": {
    "types-registry": "^0.1.315"
  },
  "devDependencies": {
    "@types/axios-mock-adapter": "^1.9.0",
    "@types/chai": "^4.0.10",
    "@types/chai-as-promised": "^7.1.0",
    "@types/circular-json": "^0.4.0",
    "@types/mocha": "^2.2.44",
    "@types/nock": "^9.1.0",
    "@types/node": "^8.5.1",
    "@types/node-fetch": "^1.6.7",
    "@types/proxyquire": "^1.3.28",
    "@types/request": "^2.0.9",
    "@types/sinon": "^4.1.2"
  }
}

$ ls -a ~/.cache/typescript/2.6/node_modules/
 ./   ../   axios/   debug/   follow-redirects/   is-buffer/   ms/  '@types'/   types-registry/

$ ls -a ~/.cache/typescript/2.6/node_modules/@types/
./  ../  axios-mock-adapter/  chai/  chai-as-promised/  circular-json/  form-data/  mocha/  nock/  node/  node-fetch/  proxyquire/  request/  sinon/
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20836
