### ISSUE TITLE
Format Code broken with JavaScript after upgrade to vscode 0.10.10

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode#4058]
I'm maintaining [vscode-standard-format](https://github.com/chenxsan/vscode-standard-format/blob/master/src/extension.ts#L37) extension, after upgrade to the latest Code v0.10.10, `Format Code` does not work when I try to format JavaScript code.

When debugging, I found the [`format`](https://github.com/chenxsan/vscode-standard-format/blob/master/src/extension.ts#L8) function registered with `vscode.languages.registerDocumentFormattingEditProvider` was never called.

I checked some other format extensions like https://github.com/kasik96/VSCode-PHP-Format/blob/master/extension.js#L67, it works in php language.

## screenshot

<img width="719" alt="screen shot 2016-03-12 at 13 03 25" src="https://cloud.githubusercontent.com/assets/1091472/13720963/e2f26eda-e852-11e5-85ba-f7529349b6fb.png">

**Comment by dbaeumer** [comment]
This works for me in the latest build target for end of March. Please ping if you still see the issue in the upcoming next build.

**Comment by chenxsan** [comment]
@dbaeumer Just updated to 1.0, still not working.

**Comment by dbaeumer** [comment]
@chenxsan can you provide a sample workspace demonstrating the problem?

**Comment by chenxsan** [comment]
@dbaeumer My project is forked from vscode-eslint, so the souce code might be familiar to you.

Code sample below:

```
var a=5;
```
I would expect these two commands in the screenshot to output the same results

<img width="642" alt="screen shot 2016-04-18 at 17 21 57" src="https://cloud.githubusercontent.com/assets/1091472/14599478/26adaf00-058a-11e6-9b7e-d1f2e60d7565.png">

Because their functions are the same as the code https://github.com/chenxsan/vscode-standard-format/blob/master/src/extension.ts#L37 and https://github.com/chenxsan/vscode-standard-format/blob/master/src/extension.ts#L49 show.

But when `Format Code`, i got:

```
var a = 5;
```

and the result of `Format code with standard-format` is:

```
var a = 5

```
And i found that `format` function was not executed when `Format Code`.

**Comment by chenxsan** [comment]
I think it's fixed in the latest VSCode 1.3.0
