### ISSUE TITLE
Tab not autoCompleting code

### ISSUE THREAD

**Issue by alannaidon** [Microsoft/vscode#40588]
- VSCode Version: 1.19.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Type `aja` (Or any other command that may have autocomplete.)
2. As the "ajax" suggestion appears, press `TAB`

- Reproduces without extensions: With and Witout extensions. 

Curious it works if you type `try` it completes try/catch with ENTER, but never with tab. Can't create a block of code with `/** + TAB` as we used to do with Sublime.

Already set `"editor.tabCompletion": true`.

**Comment by hoangnamitc** [comment]
Confirm! I meet this problem too. After update vscode :(

**Comment by alannaidon** [comment]
Anyone? :)

**Comment by jrieken** [comment]
What happens when you type `aja` and press Ctrl+Space?

**Comment by alannaidon** [comment]
@jrieken  Nothing happens, it just make a tab normally. 

also, if Y type "php" + TAB nothing happenas aswell =(
