### ISSUE TITLE
Crashes everytime on startup. 

### ISSUE THREAD

**Issue by avatarsystems** [Microsoft/vscode#40583]
Got notice of update.  Update halted due to files in use.  Closed everything but was still getting file in use error.  I clicked Abort and it rewound install of update.  I rebooted. Now every time I sign in, I get this crash:

![visualstudiocodecrash](https://user-images.githubusercontent.com/34716303/34213821-03733772-e566-11e7-94af-15f4f2ed5634.jpg)

- VSCode Version: 
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Sorry for the trouble. You'll have to fully uninstall and reinstall Code.

**Comment by avatarsystems** [comment]
Uninstall and reinstall worked.
