### ISSUE TITLE
Force version for workspace recommended extensions

### ISSUE THREAD

**Issue by Seblor** [Microsoft/vscode#40587]
- VSCode Version: 1.19.0
- OS Version: Windows 7

Following [this article](https://code.visualstudio.com/docs/editor/extension-gallery), I added some extensions to my workspace. As it is not stated and could not find any information on this particular feature, I was wondering if I missed something, or if it was possible to add it as a feature in a future release.

Thanks !

**Comment by weinand** [comment]
I do not understand what you mean by "Force version for workspace recommended extensions". Please explain.

**Comment by Seblor** [comment]
By "forcing" the version, I mean beeing able to fix a specific version of the extension, to prevent it from updating.

**Comment by weinand** [comment]
Extensions don't update automatically. So what would "forcing the version" really mean?

**Comment by Seblor** [comment]
They don't ? Sorry, I assumed they would automatically update, as I heared some people say. My bad, then.

**Comment by weinand** [comment]
Auto update of extensions is controlled by the setting "extensions.autoUpdate".
