### ISSUE TITLE
How to modify the plug-in installation path

### ISSUE THREAD

**Issue by keyiwu** [Microsoft/vscode#40584]
- VSCode Version:1.19.0
- OS Version:win10 x64

Steps to Reproduce:

1.Plug-ins consume a large number of disks

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
You can use the `--extensions-dir` command line option to configure where to store extensions.
See our documentation: https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options
