### ISSUE TITLE
Intellisense doesn't show information generated at runtime

### ISSUE THREAD

**Issue by rosyatrandom** [Microsoft/vscode#40585]
- VSCode Version: 1.19
- OS Version: Ubuntu

```
const correct = n => n*2
let incorrect = [1, 2]
incorrect = s => s*2

correct
incorrect
```

On hover, code hints are:

- correct: `const correct: (n: any) => number`
- incorrect: `let incorrect: number[]`

The issue that's led me to report this is that I wish to construct objects at runtime, and have Intellisense show their contents correctly. As a trivial example:

```
const doSomethingCurried = a => b => {/* something with a, b */};
const doSomethingWith = Object.assign(
  {},
  ...['a', 'b', 'c'].map(
    v => ({ [v]: doSomethingCurried(v) })
  )
)
```

This should end up equivalent to:
```
const doSomethingWith = {
  a: doSomethingCurried('a'),
  b: doSomethingCurried('b'),
  c: doSomethingCurried('c')
}
```
So that, when typing `doSomething.`, the hint should show properties `a`, `b`, and `c`.

I can see how tricky this might be to look into :-/

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20824
