### ISSUE TITLE
Too slow at reopening after sleep

### ISSUE THREAD

**Issue by hughet** [Microsoft/vscode#40581]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
beautify|Hoo|1.1.1
html-css-class-completion|Zig|1.14.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
auto-comment-blocks|kev|1.0.1
color-highlight|nau|2.3.0
vetur|oct|0.11.5
sass-indented|rob|1.4.5
vscode-csstree|sme|0.5.0
css-auto-prefix|spo|0.1.4

(3 theme extensions excluded)

---

Steps to Reproduce:

The only problem is when reopening Visual Studio Code after a while minimized. Too slow and often it crashes. Maybe because I have a core i5 dural-core and 4GB of RAM in my Dell notebook. But it is really dramatic sometimes.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
I don't think, that there's a big performance issue which should be solved. On my laptop on work I also have only 2 Cores, 4GB and that's also an i5. (Dell Latitude E5450 - i5-5300U CPU) There works VS Code like a charm.

**Comment by weinand** [comment]
@hughet Can you repro this when running `code --disable-extensions`?

**Comment by hughet** [comment]
I use another monitor besides the notebook screen. VSCode stays on the notebook's screen. When I stay on the monitor for a long time and then come back to VSCode on the notebook, it takes a long time to get back. I use just a few extensions. I use Ubuntu gnome, maybe that's it too. My notebook is a Dell 5548

**Comment by bpasero** [comment]
@hughet next time you want to restore can you first run "`code --status`" and attach the output?
