### ISSUE TITLE
SelectBox Custom: Alt-Up  triggers native dropdown, should trigger custom

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40595]
New SelectBox implementation

Must prevent default event that triggers native control instead of custom select box.

**Comment by bpasero** [comment]
@cleidigh make sure you set the milestone to the current milestone for things that are fixed so that these issues get verified at the end of the milestone 👍

**Comment by cleidigh** [comment]
I will get it right sometime..  :1234:

**Comment by bpasero** [comment]
:)
