### ISSUE TITLE
"code --status" x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by tolgabalci** [Microsoft/vscode#40591]
- VSCode Version: 1.19.0
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

1. run from powershell.exe or cmd.exe "code -s" or "code --status"
Results in error:
[main 12:17:23 PM] Startup error: x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was

![image](https://user-images.githubusercontent.com/2467618/34221532-50ca52c4-e586-11e7-8c58-57e27bad6ad7.png)

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This got fixed for the 1.19.1 update.
