### ISSUE TITLE
jsonc icon was hit with an ugly stick

### ISSUE THREAD

**Issue by runtimeware** [Microsoft/vscode#40594]
Can we get a prettier icon for jsonc files?  The json icon stands out as it's green and actually looks like json.  jsonc seems to be hit with an ugly stick and blends in too much with the filenames.  Also the icon doesn't hint as to what the contents may be without looking at the file extension.

- VSCode Version:  November Release
- OS Version: W10

Steps to Reproduce:
1.  Add user setting to associate .json files with jsonc (eliminate comments error)
2.  Observe ugly icon in folder view

Reproduces without extensions: Yes

**Comment by aeschli** [comment]
All depends on the icon theme, which one do you use?

I think what you see is probably the default text icon. 
I fixed this in https://github.com/Microsoft/vscode/issues/40244. Now if a theme does not have a specific jsonc icon we use the regular json icon.
