### ISSUE TITLE
VS Code provides odd hover expression to debug adapters if the expression has '.'s

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#4059]
This may well be by design, but if so I would suggest updating the documentation: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L475

When hoving over an identifier that doesn't start with a '.', the debug adapter just receives the identifier. This makes sense.
When hoving over an identifier that does start with a '.' the debug adapter seems to receive the full line of text.

I don't have a problem with making it the debug adapter's responsibility to find the start of the expression. But if I am reading [this code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugHover.ts#L97) code correctly, the UI seems to special case '.'. So I think we should either have the UI provide the debug adapter what it thinks is the right text (joining the dots together) or we should more fully move this responsibility to the debug adapter to handle more things (ex: '->' in C++).

**Comment by isidorn** [comment]
Fixed by pr #9821
