### ISSUE TITLE
HTML CSS comment syntax active beyond scope

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode#40602]
- VSCode Version: 1.19.1

CSS comment within HTML document extends outside of `style` section.

Steps to Reproduce:

1. Enter `/*` within `style` tags in an HTML document

Example:
![html-css-comment-syntax](https://user-images.githubusercontent.com/22951521/34231540-7faf652e-e5aa-11e7-8ccf-4ce14691fa9a.png)

**Comment by aeschli** [comment]
duplicate of #20488
