### ISSUE TITLE
When opened via git, caret placed in last edited location

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#40603]
- VSCode Version: 1.19.0
- OS Version: 10.13.1

![vsc3](https://user-images.githubusercontent.com/50314/34231898-d691be72-e5ab-11e7-98e6-75e902db5140.gif)

Steps to Reproduce:

1. `EDITOR="/usr/local/bin/code --wait -r"`
2. Editor shows commit message, but with caret placed somewhere random

Presumably this is because git uses `.git/COMMIT_EDITMSG`, and VSCode remembers the location. VSCode has an option `-z`, but it doesn't let me pass in `-z :1:1` to avoid it remembering the last location.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@atombender if you could tricky Git into executing "`code --goto <file>:1:1`" it would force selection on line 1 and column 1. Is that possible?

**Comment by atombender** [comment]
@bpasero I was thinking VSCode wouldn't get the right `COMMIT_EDITMSG` because the git's cwd would not be predictable, but it looks like git always sets the cwd to the root of the repo, and this works:

```shell
GIT_EDITOR="/usr/local/bin/code --wait -r -g .git/COMMIT_EDITMSG:1:1"
```

Howver, git uses other files such as `.git/rebase-merge/git-rebase-todo`. After some testing, this seems to work:

```shell
export GIT_EDITOR='/usr/local/bin/code --wait -r -g $1:1:1'
```

Case solved, I think! That said, it took a while to discover, and it might be easier for other people to solve this if Code could support an invocation such as `--goto :1:1` or something else that means it should not remember any file history for that file.
