### ISSUE TITLE
How to support git from subfolders?

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#40600]
- VSCode Version: 1.19
- OS Version: MacOS

Is source control support git from subfolders? If yes, what I should to do to show the changes in this source control tab? Because by default I don't see it.... 

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Sure. Just open a file inside those repositories... they will instantly show up in the SCM view.

**Comment by PixelT** [comment]
I'm afraid it doesn't work in this way.
I worked daily in subfolder which has git repository, but it's not visible in source control....

**Comment by PixelT** [comment]
Maybe the depth of the folder have matters? Because I have the folder with git as 5th or 6th in path
`project/folder1/folder2/folder3/folder4/folder5` and the git repository is in the `folder5`

**Comment by PixelT** [comment]
@joaomoreno I found what is wrong!
When I have .git in root folder, then git repositories from subfolders are ignored.
I renamed (temporary) .git folder in root to .git1, then I edit file in subfolders and then the changes are showed in SCM tab.
Could you check it and / or add possibility to support git in root / subfolders at the same time?

**Comment by joaomoreno** [comment]
@PixelT Glad you found it. That feature request is https://github.com/Microsoft/vscode/issues/37947
