### ISSUE TITLE
shortcut entry for adding watch expression manually

### ISSUE THREAD

**Issue by LeonardAB** [Microsoft/vscode#40608]
A small feature request,

Steps to Reproduce:

1. open keyboard shortcuts (Ctrl+K Ctrl S)
2. search for 'watch'

![image](https://user-images.githubusercontent.com/14308605/34234463-a604c69a-e62e-11e7-8dfa-101152279b07.png)

What I wanted to do was to to create a shortcut key to **add a watch expression _manually_**. The currently available entry is **adding _selection_** (currently selected expression in the editor) **to watch**. This is useful, but sometimes I want to add a custom expression, not just a variable. Let's say I have a large numpy array `a`. What I want to watch when debugging is not the content of `a` itself, but instead its size or shape by adding `np.shape(a)` to the watch list. The way I do this is by clicking the add button in the watch pane and type it manually. If I don't want to use my mouse, that will be difficult. I do not always such expression in my own code so _adding selection to watch_ cannot help me directly on this one. I could add the expression `a` using **add selection** and then **focus on watch**, focus on that new expression (by using arrow key), press F2, and edit that expression. That is at least 4 steps of work.. 

Even when I am focused on the watch pane, there is no shortcut entry possible to add new watch expression. I have to click the button. I wanted to create a shortcut for this, similar to the shortcut for creating new file in explorer view.

I think that can improve debugging experience. Thank you in advance!

(Currently I am using vscode mainly for python. If this request is irrelevant to other languages and if I should move this request to python extension repo instead, please let me know)

**Comment by isidorn** [comment]
Currently the easiest way to do this is 
Assign a keybinding to the Focus Watch command. Press that keybinding and then a combination of `shift + tab` and `tab` until you get focus on the plus.

I understand that this is not the fastest way to do this.

As for your feature request I would wait to see if this creates more user traction before I consider to accept PRs that fix this.

**Comment by adeel-raza-azeemi** [comment]
> This iteration we focus on issue grooming. This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.
> 
> If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Thanks for your understanding and happy coding!

Loved to have a feature like that; analogy is of netbeans where simple pressing a key combination (Ctrl + shift + F7) will popup a dialog. simple write what you wanna find value of the expression and it will you the value. 

Actually VSCode can add expression with mouse but there is no shortcut key of it.

**Comment by TryerGit** [comment]
I would love a keyboard shortcut that accomplishes this. I use multiCommand and have now opened an issue to see whether it is possible via multiCommand. Please see https://github.com/ryuta46/vscode-multi-command/issues/29

**Comment by Phidel** [comment]
try command 
```json
{
  "key": "...",
  "command": "workbench.debug.viewlet.action.addWatchExpression"
}
```
