### ISSUE TITLE
VoiceOver reports search results as an "empty table"

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#40601]
Turn VoiceOver on and then focus the search viewlet when there are results:

<img width="482" alt="screen shot 2017-12-20 at 2 21 11 pm" src="https://user-images.githubusercontent.com/2193314/34231460-0d1c84b0-e591-11e7-9a20-8da56fbe84ef.png">

Think it's because of `role="presentation"`:

<img width="438" alt="screen shot 2017-12-20 at 2 19 35 pm" src="https://user-images.githubusercontent.com/2193314/34231441-f3513076-e590-11e7-9c03-7d985fdb844e.png">

**Comment by roblourens** [comment]
This seems to be the case for all instances of the tree.

**Comment by joaomoreno** [comment]
@bpasero Did most of the accessibility work for trees, maybe he has an idea?

**Comment by bpasero** [comment]
Yeah this is because of `role: tree`.  I think VoiceOver does not support the concept of trees at all and treats it as table.

**Comment by roblourens** [comment]
If this didn't come up in the accessibility review, maybe it's not an issue. I tested this some more and I don't think it's blocking anyone from getting the necessary info from VoiceOver. Actually I had to click around for awhile before I got it to read "empty" again.
