### ISSUE TITLE
VScode Update

### ISSUE THREAD

**Issue by AlexIrina** [Microsoft/vscode#40610]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@AlexIrina 
Please provide more information.  Is this a problem updating?  Information on versions, errors, extensions etc.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
