### ISSUE TITLE
C++ syntax highlighting is not correct

### ISSUE THREAD

**Issue by milesxu** [Microsoft/vscode#4061]
When I use vscode to browse the `db_bench.cc` in the source code of rocksdb, I found the syntax highlighting of C++ is incorrect. Illustrated below:
screenshot of syntax highlighting in vscode,
![vscode-cpp](https://cloud.githubusercontent.com/assets/2003731/13722206/6afe3726-e878-11e5-98d5-c5413a0eea9e.png)
whereas, the same content displayed in atom
![atom-cpp](https://cloud.githubusercontent.com/assets/2003731/13722208/82f1d590-e878-11e5-875d-63c96e6be337.png)

The colors used in atom editor is much richer, and it will not misinterpret keywords in strings such as `if` or `for`.
Environment:
ArchLinux 4.4.5 64bit
vscode 0.10.10
atom 1.5.3

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#40

**Comment by aeschli** [comment]
duplicate of #4769
