### ISSUE TITLE
Issue with nvm and integrated terminal on macOS

### ISSUE THREAD

**Issue by kun-zhou** [Microsoft/vscode#40612]
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Install nvm thru `brew install nvm` or install it thru the official way (`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash`).  Make sure appropriate lines are added to `~/.bash_profile`. Then install node v8.9.3. Make sure everything works fine with `Terminal.app`

2. Open the built-in terminal in Code and encounters the error 
```sh
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v8.9.3 --silent` to unset it.
```

Reproduces without extensions: Yes

The issue persists on all workspaces, not just the workspace for my web dev projects. It started occurring with a recent Code release. `nvm` works without an issue with my default `Terminal.app` which is set to start a login shell which reads `.bash_profile` just like Code ('yes, Code also start a login shell, I made sure of that'). 

Issue #36987 also reported this issue and a potential hack but was closed without a satisfactory solution or bug fix. I think there is something wrong with the integrated terminal, maybe some unexpected configuration files are read which set `npm config  prefix`.

**Comment by Tyriar** [comment]
Did you try running `npm config delete prefix` and restarting code?

**Comment by kun-zhou** [comment]
@Tyriar Running it gives `env: node: No such file or directory`. Basically both `node` and `npm` are not in `$PATH`. The `nvm` script  encountered and error and did not end up setting the path.

**Comment by Tyriar** [comment]
Try setting `terminal.integrated.shellArgs.osx` to `[]`, that fixes this issue for some users.

**Comment by thirdgen88** [comment]
@Tyriar Your suggestion fixed the issue for me.   Also, looking at the default setting for the `terminal.integrated.shellArgs.osx` of `-l`.  According to the zsh (which I'm using) documentation, this flag, like `bash` causes the shell to start as a "login" shell.  This should cause it to read `/etc/zprofile`, which contains the following:

```
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
        eval `/usr/libexec/path_helper -s`
fi
```

Commenting out the call to this guy in `/etc/zprofile` also solves the issue, but for now I'm leaving it as is and just omitting the login shell in vscode..  Thanks for the helpful fix--perhaps others might have some additional insight?  I looked through the differences in `PATH` and didn't see anything on first pass.

**Comment by kun-zhou** [comment]
@Tyriar  I use bash and getting rid of `-l` does work. But this is a **hack**, not a **solution**. And this is why I filed this issue after reading issue #36987 as mentioned in my original post. macOS `Terminal.app` defaults to login shell and it works just fine which I also described in my original post, so there is not reason why in Code we need to get rid of `-l`. Maybe Code unintentionally or intentionally set some environment variables before or after `.bashrc` is read?

**Comment by Tyriar** [comment]
@kun-zhou if you're aware of environment variables being set that are causing the issue I'd be more than happy to look into it but I'm not aware of any that would cause issues like this though, since I can't reproduce it's tough for me to say.

**Comment by Tyriar** [comment]
I just wrote a FAQ on the website about the proper fix for this issue: https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched
