### ISSUE TITLE
unsupported encoding:cp936

### ISSUE THREAD

**Issue by tornadocs** [Microsoft/vscode#40615]
![1](https://user-images.githubusercontent.com/10612939/34238434-891d7e88-e63c-11e7-833f-0b162d3a1529.png)

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
pascal|ale|0.10.0
plsql|cas|0.0.3
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.12.0
jshint|dba|0.10.15
vscode-gist|dba|1.0.0
bower|don|0.0.3
githistory|don|0.2.3
javadebugger|don|0.1.5
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|7.0.0
LogFileHighlighter|emi|1.2.0
git-project-manager|fel|1.4.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.1.1
vscode-power-mode|hoo|2.0.0
rest-client|hum|0.16.1
java-properties|ith|0.0.2
Scala|itr|0.1.7
Angular2|joh|2.11.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Go|luk|0.6.70
MagicPython|mag|1.0.12
vscode-todo|Mat|0.8.0
vscode-exec-node|mir|0.5.0
prettify-json|moh|0.0.3
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.0.0
vscode-docker|Pet|0.0.22
vscode-jsp|pth|0.0.2
java|red|0.16.0
annotator|ryu|0.11.0
todotasks|san|0.5.0
preview-vscode|sea|1.4.2
code-settings-sync|Sha|2.8.7
python|tht|0.2.3
java-snippets|tus|0.0.1
gitflow|vec|1.1.2
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0
vscode-open-in-github|ziy|1.3.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Some GB2312 character set of documents
2. open folder with vscode
3. ctrl+shift+f

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
cp437 isn't supported by ripgrep which provides our search. It isn't part of the whatwg standard: encoding.spec.whatwg.org/#names-and-labels

But if it works in the editor, it should work if you disable ripgrep with `"search.useRipgrep": false`

**Comment by tornadocs** [comment]
thanks.
My workspace settings problem. I changed `"files.encoding": "cp936"` to `"files.encoding": "gb18030"` and it worked.
