### ISSUE TITLE
New suggestion: show the path of current active file in the window title

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40621]
please add a new funciont that :  show the path of current active file in the window title

**Comment by bpasero** [comment]
@midGitub there are various way to customize the title using the `window.title` setting, did you try that?

![image](https://user-images.githubusercontent.com/900690/34243660-1e438db0-e622-11e7-93d9-cb2161ab75ab.png)

**Comment by midGitub** [comment]
thank you very much for telling me that feature.  i just search this function on the extension market but not read all the setting yet ~. : )
