### ISSUE TITLE
Parsing args: --status assumed when using -reuse-window

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#40622]
Steps to Reproduce:

1. run `code -reuse-window` (note just 1 dash)
2. code assumes it was started with `--status`

Looks like an issue with our CLI arguments parsing library?

**Comment by joaomoreno** [comment]
Minimist parses in the UNIX way: double dash for long options, single dash for short options.

That's how `rm -rf` works: `r` and `f` are two short options.

So `code -reuse-window` is triggering a LOT of short options: `r`, `e`, `u`, `s`, etc...

**Comment by bpasero** [comment]
@joaomoreno ah yeah true, thanks for enlightening me 👍
