### ISSUE TITLE
A bug when search keyword in two tab when split the editor

### ISSUE THREAD

**Issue by IronLu233** [Microsoft/vscode#40623]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
EditorConfig|Edi|0.11.1
latex-workshop|Jam|3.10.0
sharecode|Rol|0.4.1
code-settings-sync|Sha|2.8.7
ReactSnippetsStandard|Tim|1.1.0
vscode-wakatime|Wak|1.1.22
typescript-react-snippets|abo|0.2.0
html-snippets|abu|0.1.0
vagrant|bbe|0.5.0
plsql|cas|0.0.3
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
vscode-dash|dee|1.8.0
githistory|don|0.2.3
scala-lsp|dra|0.2.2
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vscode-yarn|gam|1.3.0
webpack-snippets|gog|0.0.3
Scala|itr|0.1.7
webpack|jer|2.0.2
mssql|ms-|1.3.0
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0
vscode-paste-image|mus|0.9.5
vetur|oct|0.11.5
java|red|0.16.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.5
code-spell-checker|str|1.6.2
react-redux-es6-snippets|tim|2.1.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
vim|vsc|0.10.6
JavaScriptSnippets|xab|1.5.0
vscode-open-in-github|ziy|1.3.1

---

Steps to Reproduce:

1. split editor (use `command + \` shortcut)
![image](https://user-images.githubusercontent.com/20639676/34244015-86267ea6-e65e-11e7-92a6-1a4c2cb196a1.png)

2. search a keyword in one tab, for example, I search `ratings`
![image](https://user-images.githubusercontent.com/20639676/34244050-ad0ca270-e65e-11e7-91b8-b032d214a998.png)
3. search a keyword in another tab, I search `termViewset`
![image](https://user-images.githubusercontent.com/20639676/34244156-0a8988be-e65f-11e7-979b-3fc953ff7dac.png)
4. focus on the first tab, then the first keyword in search input become `termViewset`
![image](https://user-images.githubusercontent.com/20639676/34244215-4020f476-e65f-11e7-83e7-56c13ed8899b.png)

Another example (this one disabled extensions)
![12 -21-2017 15-09-47](https://user-images.githubusercontent.com/20639676/34244631-2c757936-e661-11e7-985a-230002c23024.gif)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
We implemented this feature (global clipboard) a while ago but now we turned it off by default.
