### ISSUE TITLE
Smartscreen blocked download of VSCode installer from Edge 

### ISSUE THREAD

**Issue by GeorgeJoy** [Microsoft/vscode#40624]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Click download button on https://code.visualstudio.com/docs/?dv=win from Edge Microsoft Edge 41.16299.15.0
2. Download starts. Smartscreen error saying content is unsafe.

Reproduces without extensions: Yes/No

**Comment by egamma** [comment]
I've reported the issue using the Defender feedback form.

**Comment by kieferrm** [comment]
Downloads are no longer flagged by SmartScreen.
