### ISSUE TITLE
Making a selection and launching Replace (cmd+alt+f) shows matching in file and shows matches in selection only after placing cursor to type in find box

### ISSUE THREAD

**Issue by uday0408** [Microsoft/vscode#40629]
- VSCode Version: 1.19.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Have 3 copies of similar text, containing some chars to find/replace.
2. Perform find/replace in 1st copy by selecting that region and launch Replace (cmd+alt+f)
3. Type some valid text in Find and some text in Replace boxes. Run replace all (alt+cmd+enter).
4. Selection 2nd copy and launch Replace again.

What happens:  Matches are not restricted to selected 2nd region; even those in 3rd copy are shown. 

Expected: Only matches in selected region should be shown.

Feature or Workaround? : When the Replace UI is shown, if cursor is placed in the Find box, then matches are restricted to selected region. This is confusing because unless I intend to modify the text for find/replace I should not need to place cursor in Find box.

![vscode_find_replace_issue](https://user-images.githubusercontent.com/4966157/34248002-4a6f4f84-e5e9-11e7-8b17-2cd4542ee196.gif)

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
The experience for toggling Replace when you select a range changed in Insiders already. When you select a whole range of text and we will focus on the find input box first (we select the query then you can quickly decide if you want to change it to a new one or not). With this change, we no longer see find matches in the editor out of sync. 

For this particular issue, it no longer exists but let me know what you think of it (probably not used to the new experience). thanks !
