### ISSUE TITLE
[suggestion]Adjust the panel layout by keyboard shortcuts

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40628]
Is there some way(API) to adjust the height of the panel height

for example. i type a bigger number value to change the height of the panel when i want the terminal panel large. type a tiny number to let it smaller. or after i press down a set of key value . and then cursor jump to the edge of the layout panel, then support a up/down arrow to change then height or width.

**Comment by isidorn** [comment]
Yes, you can assign custom keybindings to Decrease Current View Size and Increase Current View Size commands.
