### ISSUE TITLE
IntelliSense not working after updating to 1.20.0-insider

### ISSUE THREAD

**Issue by secsilm** [Microsoft/vscode#40625]
- VSCode Version: Code - Insiders 1.20.0-insider (280ca1dc90b8ce8da4d72453ba50b4a1e76ca077, 2017-12-21T06:31:48.901Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
markdown-preview-github-styles|bie|0.1.0
vscode-markdownlint|Dav|0.12.0
vscode-instant-markdown|dba|1.3.0
githistory|don|0.2.3
jupyter|don|1.1.4
vscode-html-css|ecm|0.1.8
mdmath|goe|2.0.7
markdown-shortcuts|mdi|0.8.1
python|ms-|0.9.1
cpptools|ms-|0.14.5
autodocstring|njp|0.1.2
code-settings-sync|Sha|2.8.7
markdown-preview-enhanced|shd|0.3.1
markdown-pdf|yza|0.1.7

(7 theme extensions excluded)

---

IntelliSense not working after updating to 1.20.0-insider and also the formatting file option is gone. All packages have no lint, such as numpy, pandas, tensorflow

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
What language are you working in?

**Comment by secsilm** [comment]
Python

**Comment by mjbvz** [comment]
Please file an issue agains your python extension. We don't ship with built-in python support
