### ISSUE TITLE
The line number corresponding to the message in debug console is not clear

### ISSUE THREAD

**Issue by webtjw** [Microsoft/vscode#40627]
When I used vs code to debug nodejs project, I found that it's not easy to confitm which place info was corresponding to the log message  on the left side, just like something below:

```javascript
log message1                                                       log.js:111
log message2                                                       app.js:111
log message3                                                       main.js:111
log message4                                                       do.js:111
```

you will realiz that it becomes much more difficult to id when you have a width screen, and I hope that you guys may add a bottom-border or something else below each message.

thanks a lot.

**Comment by isidorn** [comment]
Wasn't there an feature like this requested by @roblourens
