### ISSUE TITLE
Two finger touchpad scrolling is very laggy

### ISSUE THREAD

**Issue by utk-dev** [Microsoft/vscode#40632]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
material-icon-theme|PKi|3.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Open any file.
2. Two finger scrolling on any laptop's touchpad (Microsoft's Precision Driver) is very laggy and unresponsive.
Reproduces without extensions: Yes

**Comment by bpasero** [comment]
#13612
