### ISSUE TITLE
[git syntax] add update script for diff.tmLanguage

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#40637]
https://github.com/Microsoft/vscode/commit/9f131c176203f405a9a5e447e91eccff6dedfd53 added the diff.tmLanguage grammar file.

-> add a update script
-> add a test case

**Comment by aeschli** [comment]
@joaomoreno Have a look, maybe you want to add a bigger test sample.

**Comment by aeschli** [comment]
@joaomoreno I assumed you didn't make any manual changes to the grammar...

**Comment by joaomoreno** [comment]
@aeschli Alles gut!
