### ISSUE TITLE
Small layout defect when opening a new editor tab after Edit-Replace dialog

### ISSUE THREAD

**Issue by TheIndifferent** [Microsoft/vscode#40639]
- VSCode Version: 1.19.1
- OS Version: OSX 10.13.2

Steps to Reproduce:

1. open new editor tab
2. open Edit - Replace dialog
3. open new editor tab.
4. see that first line is some distance from the top of the frame, around like 4 in the first editor tab.

Reproduces without extensions: Yes

**Comment by Simran-B** [comment]
Seems perfectly valid to me. The replace dialog is still open, so you don't want it to partially cover the first line of the new file:

![image](https://user-images.githubusercontent.com/7819991/34293186-141f4526-e704-11e7-8bb9-52633abd5c38.png)

**Comment by rebornix** [comment]
We move the editor down then it won't be covered by the find widget. For more information, please see https://github.com/Microsoft/vscode/issues/28390
