### ISSUE TITLE
我在使用更改设置后重启，界面显示全乱了，重启无效   我在使用更改设置后重启，界面显示全乱了，重启无效 I restarted when I used the change background settings, and the interface was all messed up and restarted.

### ISSUE THREAD

**Issue by PlutoCA** [Microsoft/vscode#40630]
- VSCode Version: Code 1.19.1 **[Unsupported]** (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.1.8
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
canvas-snippets|hol|0.3.2
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
docthis|joe|0.6.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
color-highlight|nau|2.3.0
vetur|oct|0.11.5
view-in-browser|qin|0.0.5
background|sha|1.1.17
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@PlutoCA VS Code has no "background" settings. Please file this issue against the extension that provides the "background" settings.

**Comment by shalldie** [comment]
嗨，不好意思，应该是因为background插件的问题。
我是background的作者 =。=

我无法重现这个现象，但是确实曾经碰到过一次。 需要重新安装vscode才能解决(原因是vscode的一个样式文件在重写过程中出现问题。)

再次抱歉，，，我这个周末再检查一下代码，看看bug在哪里。
