### ISSUE TITLE
CSS intellisence not working properly

### ISSUE THREAD

**Issue by smishr4** [Microsoft/vscode#40640]
- VSCode Version: 1.19.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open css file
2. Try typing transition

Reproduces without extensions: Yes

Check the 1. current screenshot, it doesnt show me css autocomplete snippet for `transition` property, I am attaching a 2. screenshot of how it should work (which works fine on my windows system):
![screenshot_2017-12-21_17-16-33](https://user-images.githubusercontent.com/10207276/34254723-5c90c0dc-e673-11e7-960e-dce150216592.png)
![vscode](https://user-images.githubusercontent.com/10207276/34254765-9df8a396-e673-11e7-8f74-b716fa81bded.PNG)

**Comment by usernamehw** [comment]
They were removed as obsolete https://github.com/Microsoft/vscode/commit/0843571ee7d1313352f948f30bdd2291e2539bf5. You can add them in your User Snippets.
execute `Preferences: Open User Snippets` from command palette.
type `CSS`
insert (for instance all 3 deleted snippets):
```json
{
  "transition property": {
    "prefix": "transition",
    "body": [
      "-webkit-transition: ${1:property} ${2:duration} ${3:timing-function} ${4:delay};",
      "-moz-transition: ${1:property} ${2:duration} ${3:timing-function} ${4:delay};",
      "transition: ${1:property} ${2:duration} ${3:timing-function} ${4:delay};"
    ],
    "description": "The transition property across browsers"
  },
  "border": {
    "prefix": "border",
    "body": [
      "border: ${1:width} ${2:border-style} ${3:color};$0"
    ],
    "description": "[width] [border-style] [color]"
  },
  "gradient": {
    "prefix": "gradient",
    "body": [
      "background-image: -webkit-gradient(linear, left top, left bottom, from(${1:start-color}), to(${2:end-color}));",
      "background-image: -webkit-linear-gradient(top, ${1:start-color}, ${2:end-color});",
      "background-image: -moz-linear-gradient(top, ${1:start-color}, ${2:end-color});",
      "background-image: linear-gradient(to bottom, ${1:start-color}, ${2:end-color});"
    ],
    "description": "Set the 'background-image' property to a linear gradient"
  }
}
```

**Comment by aeschli** [comment]
Thanks @usernamehw, we removed the built-in css snippets.

**Comment by smishr4** [comment]
Thanks @all I have copy pasted these snippets in my settings and its working just great. :)
