### ISSUE TITLE
Feature Request: planned support for Q#?

### ISSUE THREAD

**Issue by alongalky** [Microsoft/vscode#40644]
Microsoft recently released their [Quantum Development Kit](https://marketplace.visualstudio.com/items?itemName=quantum.DevKit), which looks amazing but is unfortunately only available for VS / Windows.

Are there plans to release a VS Code compatible version of it? I would love to see it.

**Comment by weinand** [comment]
Duplicate of https://github.com/Microsoft/Quantum/issues/16
