### ISSUE TITLE
VS Code getting stuck while typing or using arrow keys - 

### ISSUE THREAD

**Issue by Metrophobe** [Microsoft/vscode#40648]
- VSCode Version:  1.19.0
- OS Version:  Windows 10 Pro 64 bit
- Hardware Dell XPS 15 9560 (just in case)

Create an Angular app and while typing things in ts. files, the app hangs completely (yet momentarily) and then continues to work normally after a while. 

Ensure that the laptop is in battery mode and not on power 

Steps to Reproduce:

1.  Create an ng app with ng new appName 
2.  Go into the ts file and start coding regularly 
3. Also no extensions are installed 
4. I do not know if it affects but I was using a device in the usb c port to project the screen on multiple displays but I am not sure if it is really related because not other application (such as word) gets stuck while typing. 

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
