### ISSUE TITLE
broken values in german i18n

### ISSUE THREAD

**Issue by Macilias** [Microsoft/vscode#40649]
- VSCode Version: master
- OS Version: macOS

Steps to Reproduce:

check german context menue

Hi,  detected 2 bugs within the code context menu 
1.st: there is unjustified leading space before the command.stash value
2.th: there is inconsistent punctuation usage: "Pop für Stash ausführen..." uses ... while , "Pop für letzten Stash ausführen", does not, for no clear reason.

You can consider the fix from this pull request:
https://github.com/Macilias/vscode/pull/1

**Comment by jens1o** [comment]
Hi @Macilias!

What about doing this on your own? See https://aka.ms/vscodeloc to learn how you can start contributing(and fix that grammar mistake)

**Comment by Macilias** [comment]
Hi Jens,

I tried the link you send me yesterday and was sadly faced with usual microsoft experience after trying to follow the steps for over 1H.
Either the documentation is broken or outdated, since there is no option in the right corner to request a membership neither you get
Something meaningful when typing Microsoft in each of the input fields.
It just felt like the bad old days, so either you fix the wrong strings or provide me access your self.

Thx.


-- 
Maciej Niemczyk 
Software Entwickler  




E-Mail: maciek.niemczyk@vitraum.de 
Internet: www.vitraum.de 

Vitraum GmbH 
Am Sandtorkai 71  
D-20457 Hamburg

Vertretungsberechtigte Geschäftsführer: Alexander Schwaab, David Ranft, Martin Treusch von Buttlar 
Amtsgericht Hamburg, Registernummer: HRB 137090

**Comment by maxibanki** [comment]
@Macilias What's the problem or where are you stuck? I think the documentation is really clear. You create a account at transifex and create there a change request on the translation which you want to improve.
Let me hear if you have any questions.

**Comment by danyeh** [comment]
1st issue: no leading space in [Transifex](https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#de/$/116961375?qt=Stash ausf%C3%BChren). I copied over a new one to try. Need another round of export to isolate.
2nd issue: source string has ... (Pop Stash...) so [translation ](https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#de/$/117509013?qt=Pop f%C3%BCr Stash ausf%C3%BChren) is consistent with source.

**Comment by danyeh** [comment]
@Macilias , it will be great that you share what block you to sign up Transifex and VS Code project there. I revised a link in https://aka.ms/vscodeloc and point to this link (can be found in page navigation in the right as well.)
https://github.com/Microsoft/Localization/wiki/Localize-an-Open-Source-Product-through-Transifex

**Comment by danyeh** [comment]
Fixed. https://github.com/Microsoft/vscode/blob/master/i18n/deu/extensions/git/package.i18n.json
Thank you fro your feedback!
