### ISSUE TITLE
Duplicate line down is not multi cursor aware

### ISSUE THREAD

**Issue by StyleShit** [microsoft/vscode#40646]
When I have N cursors on the same line and i duplicate the line, it's being duplicated N times instead of 1 time.
Can u change it to be 1 line? I think it would be more comfortable.

Thnx :)

**Comment by dustinpoissant** [comment]
I have a similar request but I also request that the multiple cursor positions be preserved on the new line. Like atom.

**Comment by dustinpoissant** [comment]
I fail to see how that issue is a duplicate. They are completely different things in my opinion. Perhaps there is a single bug that causes both issues but that has not been indicated here

**Comment by alexdima** [comment]
This has been mitigated by PR #52645, with the changes in that PR each line will be at most copied once.
