### ISSUE TITLE
Copy File name is not working in explorer in VS CODE

### ISSUE THREAD

**Issue by HGautam25** [Microsoft/vscode#40656]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
aio-compiler|azt|1.0.2
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
markdown-all-in-one|yzh|0.11.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
@HGautam25 what do you mean by "Copy File name"?
The explorer only has a "Copy" and a "Copy Path" action.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
