### ISSUE TITLE
Source Control should remember view sizes

### ISSUE THREAD

**Issue by apiarian** [Microsoft/vscode#40650]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|1.1.2
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.7
yaml|ada|0.0.9
githistory|don|0.2.3
RunOnSave|eme|0.0.16
vscode-power-mode|hoo|2.0.0
rest-client|hum|0.16.1
Go|luk|0.6.70 (custom build)
terraform|mau|0.0.20
python|ms-|0.9.1
show-offset|ram|0.0.3
rewrap|stk|1.5.3
json-schema-validator|tbe|0.1.0
ayu|tea|0.10.0
vscode-todo-highlight|way|0.5.11

---

Steps to Reproduce:

1. Open a multi-root workspace using git for each root
2. Go to the source control sidebar panel
3. See the source control providers view sized small at the top of the screen
4. See the selected provider's git view sized to fit most of the screen height
5. Switch to a different sidebar
6. Switch back to the source control sidebar panel
7. See the source control providers view take up most of the screen height
8. See the selected provider's git view on the lower part of the screen.
9. Resize the selected provider's git view back up to a larger size
10. See the size jump back to a small view when hiding and restoring the sidebar or switching sidebar panels.

Reproduces without extensions: Yes

**Comment by tsck** [comment]
Just a note in case it help pinpoint the bug, this bug isn't introduced until the the functionality to resize the selected providers git view is introduced, which appears to be when there are six or more roots open.

**Comment by apiarian** [comment]
Is it forgetting the size? The first time you open the panel it's a reasonable size. Every other time the panel is shown, the size is awkwardly small. Or is it a problem with it defaulting to the wrong size on subsequent loads?

**Comment by trickymast3r** [comment]
I just turn off that git ... use terminal it's good

**Comment by joaomoreno** [comment]
/duplicate #35036 

Fixing that one will get this for free
