### ISSUE TITLE
Improving the `onDidOpenTextDocument` API docs

### ISSUE THREAD

**Issue by seanpoulter** [Microsoft/vscode#40653]
VSCode Version: 1.19
Reproduces without extensions: Yes
<br/>

There is ambiguity in the language used for the `onDidOpenTextDocument` API. As an extension developer, I expect the event to fire when "document is opened and displayed to the user (in a document group) for the first time". To my confusion, @jrieken [explained in #22561](https://github.com/Microsoft/vscode/issues/22561#issuecomment-286863397) that the event also fires when resources are opened (e.g.: from extensions):
> There is a subtle difference between seeing a tab for a document and the document being open. Generally, when selecting a different tab we will (a) re-use the editor, (b) set the new document, and (c) close the former document.
<br/>

Can we please update the [`workspace` API docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace) to explain the lifecycle?

It'd also be good to clarify the event timing mentioned above -- when will the `document` from `onDidOpenTextEditor(document)` be assigned to one of the documents in `vscode.window.visibleTextEditors`?

**Comment by jrieken** [comment]
> I expect the event to fire when "document is opened and displayed to the user (in a document group) for the first time".

Nah, that's not correct. You can open a text document without showing it, e.g. just for feeding it into another tool. A visible text document is referred to as an editor and for those different events exist

**Comment by seanpoulter** [comment]
Thanks @jrieken. Can I help with the docs?

I'm happy to open a PR to add notes like:
```diff
onDidOpenTextDocument: Event<TextDocument>
An event that is emitted when a text document is opened.
+For changes to visible text documents, use the `window` events that are
+emitted when the TextEditors change. When a text document is opened in more
+than one visible text editor, this event will only fire when initially opened.

onDidCloseTextDocument: Event<TextDocument>
An event that is emitted when a text document is disposed.
+This fires after a document is closed in all visible text editors.
```

**Comment by jrieken** [comment]
Yes, please go ahead

**Comment by seanpoulter** [comment]
Thanks for your help @jrieken! Both PRs are merged and the docs are live. 🎉
