### ISSUE TITLE
Expose the vscode.TextEditor id property

### ISSUE THREAD

**Issue by seanpoulter** [Microsoft/vscode#40652]
VSCode Version: 1.19
Reproduces without extensions: Yes

As an extension developer, it is necessary to use the unique ID for each text editor. I'd like to expose this in [`vscode.d.ts`](https://github.com/Microsoft/vscode/blob/509108f986e813e87949beb03e84ba476dc098a7/src/vs/vscode.d.ts#L1026) and update [the API docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoraspan-classcodeitem-id318texteditorspan). As an example use case, it is necessary to track if you've added decorations to a document the first time it's opened -- "opened" as in "displayed to the user in a tab group for the first time", and not the `onDidOpenTextDocument` resource has been opened that @jrieken [explained in #22561](https://github.com/Microsoft/vscode/issues/22561#issuecomment-286863397).

**Comment by jrieken** [comment]
Not very eager on adding ids. @seanpoulter using the (object) instance as identify (e.g. with ES6 Map and Set) should work.

**Comment by seanpoulter** [comment]
Good call @jrieken.
