### ISSUE TITLE
Extension prompts for constant Reload 

### ISSUE THREAD

**Issue by joshvito** [Microsoft/vscode#40655]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|2.11.2
vscode-todo|Mat|0.8.0
csharp|ms-|1.13.1
sublime-keybindings|ms-|3.0.3 <<<<<<<<<<
debugger-for-chrome|msj|4.0.0

PROBLEM: Keybinds don't all work, and VSCode UI prompts for infinite `Reload`

Clicking reload causes the editor to reload, but the Extension still requests a reload, and it doesn't work as expected.

![image](https://user-images.githubusercontent.com/1249866/34259525-90d81dc4-e630-11e7-98bf-06f67c64b638.png)

---

Steps to Reproduce:

1. Install `Sublime Text Keymap` v. 3.0.3
2. Click Reload

Reproduces without extensions: No, problem is with Extension

**Comment by weinand** [comment]
File issue against the "Sublime Text Keymap" extension.

**Comment by joshvito** [comment]
filed: [https://github.com/Microsoft/vscode-sublime-keybindings/issues/70](https://github.com/Microsoft/vscode-sublime-keybindings/issues/70)
