### ISSUE TITLE
Document switching now loads document in background - annoying

### ISSUE THREAD

**Issue by gordody** [Microsoft/vscode#40657]
- VSCode Version: Code - Insiders 1.20.0-insider (08ec16001adaab8a86183431f6aec09209caa4ab, 2017-12-15T06:08:07.643Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
MochaSnippets|Ala|0.0.1
markdown-toc|Ala|1.5.6
xml|Dot|1.9.2
EditorConfig|Edi|0.11.1
JSDocTagComplete|Hoo|0.0.2
output-colorizer|IBM|0.1.2
vscode-mocha-two|Mys|1.2.1
vscode-docker|Pet|0.0.22
lorem-ipsum|Tyr|1.1.0
Bookmarks|ale|0.18.0
project-manager|ale|0.23.1
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
eslint-disable-snippets|drK|1.1.4
gitlens|eam|7.0.0
restore-editors|eam|0.2.1
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.5
docker-linter|hen|0.5.0
rest-client|hum|0.16.1
search-node-modules|jas|1.2.0
docthis|joe|0.6.0
restructuredtext|lex|45.0.0
vs-rest-api|mkl|2.0.0
lit-it|moh|1.2.12
python|ms-|0.9.1
azure-account|ms-|0.2.2
createGUID|nwa|0.0.2
proto|pet|0.0.2
vscode-icons|rob|7.19.0
code-spell-checker|str|1.6.2
vscode-open-in-github|sys|1.6.0
vscode-js-console-utils|wht|0.7.0

---

Steps to Reproduce:

1. Use Ctrl + Tab to switch documents
2. Document loads while Ctrl + Tabbing between them

This is pretty annoying and unnecessary. The document list still covers most of the document so it's still hard to see the contents + the title should be enough to know what's in it. Please at least let me turn this "feature" off.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Yeah I took it out again, make sure you update to latest.
