### ISSUE TITLE
all js intellisense can't work.

### ISSUE THREAD

**Issue by wu38607** [Microsoft/vscode#40651]
os: ubuntu 16.04
version: 1.19.1
plugins:Atom One Dark Theme,Bracket Pair Colorizer,open-in-browser,vscode-icons.

But sometime reopening the project will appear once and then disappear again.
Return to 1.18 all ok.

1.19
![1 19](https://user-images.githubusercontent.com/22634735/34298683-f6cfb3ba-e759-11e7-8d69-a34b011aa31e.gif)

1.18
![1 18](https://user-images.githubusercontent.com/22634735/34298691-fdac22b8-e759-11e7-8804-756dc1e1e2a3.gif)

**Comment by Mlocik97-issues** [comment]
I can't reproduce.

**Comment by mjbvz** [comment]
Please provide more info about the problem. What type of file are you in? What does the general project structure look like?

**Comment by wu38607** [comment]
@mjbvz I updated gif.

**Comment by mjbvz** [comment]
@wu38607 Does this still happen if you disable all extensions and restart vs code? You can also launch code from the command line using `code --disable-extensions` to check this
