### ISSUE TITLE
Search results in tree structure

### ISSUE THREAD

**Issue by MstfTkrsln** [Microsoft/vscode#40661]
When i search a phrase via search bar, All files that contains the phrase appears but all in the same level.I think its maybe more useful if the files appears as tree structure by its parent folders.

- VSCode Version:  1.19.1
- OS Version: Windows 10
Reproduces without extensions: Yes

**Comment by roblourens** [comment]
/duplicate of https://github.com/Microsoft/vscode/issues/20224
