### ISSUE TITLE
Edits no longer appear in gutter with v. 1.19.1

### ISSUE THREAD

**Issue by johnmhoran** [Microsoft/vscode#40668]
With the latest version of Visual Studio Code running on Windows 10 Fall Creator's Update, file edits no longer are displayed in the gutter.  If I revert from 1.19.1 to, e.g., 1.15, the gutter displays edits as expected -- but Visual Studio Code then promptly updates itself to the latest version.

I've experimented with, e.g., disabling all extensions, changing color themes, uninstalling and reinstalling Git Bash/Git for Windows -- all to no avail.

Does anyone have any suggestions?

- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro Version 1709

Steps to Reproduce:

1. Open Git Bash
2. Navigate to project.
3. Checkout correct branch.
4. Run `code .`
5. In Visual Studio Code, open the file to work on.
6. Make a change in the file and save.
7. Changes/edits are not displayed in the gutter as they used to be with all prior versions.

Reproduces without extensions: Yes

**Comment by johnmhoran** [comment]
I get the same result with the next-to-last version, 1.18.1: the gutter displays edits as expected.  And I misspoke re updating: at least today, Visual Studio Code is alerting me to the existence of an update but is not forcing that update.

**Comment by joaomoreno** [comment]
Anything special about your project? Network share?

If you switch to another file and then back, do the gutter decorations appear?

Are the changes displayed in the scm view at all?

**Comment by johnmhoran** [comment]
Hi @joaomoreno .

There's nothing special about the project -- no network share, all files are local.  If I switch from file to file, the gutter decorations do not appear.

What is the "scm view"?

**Comment by harshavarma** [comment]
I'm having the same issue and VSCode version is 1.19.1. Tried both disabling and removing all extensions and a fresh install of the software. Then I tried opening a different repository and now the gutter indicators work properly.

**Comment by joaomoreno** [comment]
This is the SCM view:

<img width="531" alt="screen shot 2018-01-08 at 12 00 38" src="https://user-images.githubusercontent.com/22350/34667963-93bce422-f46b-11e7-8e1e-702aab2951b2.png">

**Comment by johnmhoran** [comment]
Thank you, @joaomoreno .  Since my initial post here, I've been using 1.18.1, which displays edits in the gutter.  Have just updated again to 1.19.1 to answer your question: the `SCM view` does display the edits as diffs, but there still are no gutter indicators.  I'm going to uninstall 1.19.1 and reinstall 1.18.1 so that I can see my edits in the gutter as I work.

Do you have any ideas what might be causing this behavior?  Any suggestions?

**Comment by joaomoreno** [comment]
@johnmhoran Do all other git features work fine?

**Comment by johnmhoran** [comment]
@joaomoreno I use the integrated terminal (running Git Bash) for most git work.  To the extent that I use git features in VSCode (e.g., discarding changes), I've encountered no other issues.

**Comment by joaomoreno** [comment]
So, you can stage, unstage, discard changes, the status bar reports git status, etc?

It's really just the gutter margin?

Can you reproduce this in any git workspace, or is it specific to this single workspace?

**Comment by johnmhoran** [comment]
Yes to all your questions.  Everything seems fine except the gutter indicators, and this occurs in each local repo I've tried it in.

**Comment by joaomoreno** [comment]
Does it reproduce with the [insider release](https://code.visualstudio.com/insiders)?

**Comment by johnmhoran** [comment]
@joaomoreno I haven't tried the Insiders release before, just downloaded and installed, opened a Python project, and the gutter indicators display properly.  Version info:
```
Version 1.20.0-insider
Commit ca023a700f35212071dfe9544272719cbbf80e4c
Date 2018-01-12T05:14:50.541Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
Hopefully this means all will be well gutter-wise once 1.20 is officially released.

**Comment by joaomoreno** [comment]
Yes it does!

**Comment by johnmhoran** [comment]
Thank you, @joaomoreno !  Can you share any insights as to what led to the behavior I encountered?

**Comment by johnmhoran** [comment]
@joaomoreno I just downloaded and installed 1.20 on my Windows 10 laptop -- same laptop mentioned above.  

The problem I experienced with 1.19 has grown: now, the gutter indicator does not display changes, and the source control icon on the left also does not display changes.  The latter is a new problem not present in 1.19.  At first glance it seems I may again have to revert to 1.18.
