### ISSUE TITLE
search.useIgnoreFiles: true ignores the settings in search.exclude.

### ISSUE THREAD

**Issue by chrisajimenez** [Microsoft/vscode#40667]
The latest update to vscode included a commit https://github.com/Microsoft/vscode/commit/e99c765f443a93eee6c647e96ce4d2e958dcac62 that switched the default of ```search.useIgnoreFiles``` to be true.

This caused node_modules to be not searchable because of the .git_ignore file that was in my root, even though my user settings had been overriding the default behavior of search.exclude for some time. The fix for me was to turn ```search.useIgnoreFiles``` off again.

I think a better solution would be to have the settings defined in ```search.exclude``` be the last override that is applied to the search.

- VSCode Version: 1.19.1
- OS Version: mac os 10.11.1

Steps to Reproduce:

1. Include a .git_ignore with ```/node_modules/```
2. Override the user setting "search.exclude" to be
```js
"search.exclude": {
    "**/node_modules": false
}
```
3. Searching node_modules does not work as expected.

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
Unfortunately we don't have control over the code that's reading the gitignore file, so it's not really possible for us to disable specific gitignore patterns through search.exclude. Setting the useIgnoreFiles setting like you've done is my recommended workaround here.
