### ISSUE TITLE
No file type icons are displaying

### ISSUE THREAD

**Issue by stevenhay** [Microsoft/vscode#40665]
- VSCode 
                Version: 1.20.0-insider
                Commit 509108f986e813e87949beb03e84ba476dc098a7
                Date 2017-12-21T12:31:52.865Z
                Shell 1.7.9
                Renderer 58.0.3029.110
                Node 7.9.0
                Architecture x64
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Load VS Code
2. Create any file with a known filetype.

Reproduces without extensions: Yes

Same build on my Elementary OS machine works fine.

![image](https://user-images.githubusercontent.com/26744309/34267743-e5594c34-e675-11e7-94bf-f4b37d85bc25.png)

![image](https://user-images.githubusercontent.com/26744309/34267785-10333cda-e676-11e7-8804-aa15435eba8a.png)

**Comment by stevenhay** [comment]
Screenshots from my Elementary OS build:
![image](https://user-images.githubusercontent.com/26744309/34267897-988a54a6-e676-11e7-8ece-56e986f4c7bc.png)

![image](https://user-images.githubusercontent.com/26744309/34267929-bea28ce4-e676-11e7-8ace-2057c36ce406.png)

**Comment by usernamehw** [comment]
I can reproduce only for `seti-icons`. All other icon themes seems to work fine.

**Comment by usernamehw** [comment]
It was fixed and already in the next build: https://github.com/Microsoft/vscode/issues/40636

**Comment by stevenhay** [comment]
Can confirm the next update fixed it. Thanks. Closing the issue.
