### ISSUE TITLE
XUnit code lens (run test, debug test) not appear in solution workspace

### ISSUE THREAD

**Issue by luktar** [Microsoft/vscode#40666]
VScode version: 1.19
OS: Mac OS X Hight Sierra

Similar [https://github.com/OmniSharp/omnisharp-vscode/issues/1292](url)

XUnit code lens appears in the project like workspace (one project only - csproj on top level).
XUnit code lens does not appear in the solution like workspace (sln on a top level, projects inside folders).

Steps to reproduce:
1. Create solution 'dotnet new sln'
2. Create test folder 'mkdir Test', 'cd ./Test'
3. Create test project 'create classlib'
4. Put this to csproj

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>
</Project>
```

5. Open workspace on csproj level, open test class - code lens appears.
6. Open workspace on sln level, open test class - code lens doesn't appear.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1934
