### ISSUE TITLE
Improve display of resource labels that use file paths without file:// scheme

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#40662]
I have a TextDocumentContentProvider used to open files read-only when a user does Go-to-Definition on external packages (which live on disk as source).

My provider is pretty simple and looks like this:

```ts
export class DartPackageFileContentProvider implements TextDocumentContentProvider {
	provideTextDocumentContent(uri: Uri, token: CancellationToken): string {
		return fs.readFileSync(uri.fsPath).toString();
	}
}
```

I'm invoking it like this:

```ts
// let filePath = "M:\\path\\file"
let uri = vs.Uri.file(filePath).with({ scheme: "dart-package" });

vs.workspace.openTextDocument(uri).then(document => {
	vs.window.showTextDocument(document, { preview: true });
}, error => { });

```

However once opened, if I hover my mouse over the tab, the path is displayed with a leading slash. If I put a breakpoint inside the file, the leading slash is included, which means it doesn't match up with breakpoints added to the file if opened from the explorer (I added the top highlighted breakpoint by opening from explorer but the bottom one from within the readonly view).

![paths](https://user-images.githubusercontent.com/1078012/34263591-e7d44e36-e667-11e7-8036-6df54bc82c8c.png)

**Comment by bpasero** [comment]
@DanTup you seem to not use the URI in the openTextDocument call? Instead of:

`vs.workspace.openTextDocument(filePath)`

Try

`vs.workspace.openTextDocument(uri)`

**Comment by DanTup** [comment]
@bpasero Sorry, that was just a bad copy/paste when I tried to put the code into a simple chunk to explain it. I'm actually passing the URI to a command, and then the command runs the rest of the code. I'll tweak my post for clarity.

**Comment by bpasero** [comment]
I have a feeling that this is our `URI` behaviour and how it deals with file paths only specially when the scheme is `file` (but @jrieken can confirm). 

It seems to me that something is missing here: opening files as readonly and having to use a text document provider seems wrong to me.

**Comment by DanTup** [comment]
@bpasero I agree - I previously raised this at #31410 but was advised to do it this way. I think it would be better to have a simpler API for this (and ideally, be able to mark sections of the explorer tree that should open read-only, such as a packages folder).

**Comment by bpasero** [comment]
@DanTup just to confirm, everything works fine, it's just the hovers looking weird?

**Comment by DanTup** [comment]
@bpasero There are two issues - the hover looking weird is just cosmetic, but if you set breakpoints while in it, they get a path in that form too, which means Code treats them separately to if the file had been opened "normally" and added there (see the red box in bottom left of the screenshot - I have two breakpoints that are actually the same, but Code thinks they're different).

**Comment by bpasero** [comment]
@DanTup i suggest to split this issue up into 2 then, can you create a new one for the breakpoint/debug issue. Btw it is unlikely that we support this scenario and it likely requires a lot more API because the debug engine is not aware of your URIs.

**Comment by DanTup** [comment]
@bpasero In that case, would it be better to re-open #31410 and support opening files readonly and I can ditch this? That would certainly be preferable to me, and I think it would generally be a better change for Code too?

**Comment by bpasero** [comment]
@DanTup let's wait for @jrieken comment on that. He is on vacation and back next year.

**Comment by jrieken** [comment]
@DanTup Is the scheme of that uri `M`? Can you provide its full contents (as returned by toString) and what rendering you expect?

**Comment by DanTup** [comment]
@jrieken The scheme is `dart-package`. I'm using it to allow opening files as readonly (I don't want users typing into files opened from packages folder, since they're managed by the package manager). This was suggested at https://github.com/Microsoft/vscode/issues/31410#issuecomment-317972423 because there's no proper read-only support.

So, I'm basically doing this:

```ts
// Get the file path of the file to open
let filePath = "M:\\path\\file.dart"

// Create a Uri.file but change the scheme to the one we've registered to handler
let uri = vs.Uri.file(filePath).with({ scheme: "dart-package" });

// Open the text document for this uri
vs.workspace.openTextDocument(uri).then(document => {
	vs.window.showTextDocument(document, { preview: true });
}, error => { });
```

and the handler for `dart-package` does this:

```ts
export class DartPackageFileContentProvider implements TextDocumentContentProvider {
	provideTextDocumentContent(uri: Uri, token: CancellationToken): string {
		return fs.readFileSync(uri.fsPath).toString();
	}
}
```

Now I look at it, I'm surprised so much of this works (I replace the scheme, yet uri.fsPath still works correctly).

Note: I don't think this is a good idea; I would rather delete all of this and have `openTextDocument` (or similar) support opening files as read-only. This feels like a bit of an abuse of the document content providers. I think read-only library files are quite common (eg. in TypeScript if you F12 into some node packages, probably you'd prefer them to be readonly). So, in my opinion it might be best to re-open https://github.com/Microsoft/vscode/issues/31410 and close this one, but I'm somewhat biased towards what's best for me =)

**Comment by jrieken** [comment]
> So, in my opinion it might be best to re-open #31410 and

Not sure yet. "Yes" if the file is readonly by OS-means not sure for other cases tho. I think what you do is fair and with everything around [remote-ing](https://github.com/Microsoft/vscode/issues/29194) we will have to support showing other-then-file-uris in a good way anyways.

**Comment by DanTup** [comment]
@jrieken One of the complications here is that this affects debugging too. Eg. if I open a file this way and then the user adds a breakpoint, I want Code to consider the breakpoint the same as if the file had been opened with File -> Open but it's currently not (see the bottom-left corner of the original screenshot). I don't know whether fixing this issue (the display) would extend to that; in which case I'm not sure it resolves all my issues (which is why I think read-only support would really be better).

I don't know if any other languages handle this well; I'll have to do some testing (I presume most languages support F12ing into library code that the user shouldn't, or cannot, modify, but should be able to add breakpoints and have them behave as expected).

**Comment by jrieken** [comment]
Understood...

**Comment by bpasero** [comment]
We do not have an explicit readonly mode for files so far that would prevent any modifications. The resource editor (as in this case) comes close in a way that we set the editor to readonly (with the `readOnly` option of the editor). 

If a file is readonly on disk by the OS we actually do not detect that and the editor is still editable. But we throw an error once you save and allow to remove the readonly bit if needed.

**Comment by bpasero** [comment]
The label for non-file URIs came in via https://github.com/Microsoft/vscode/commit/80aefe9aff01217d3aa361b148f7dad52662d48b so this seems to be something that was only added for remote scenarios and seems to need tweaking.

**Comment by jrieken** [comment]
We know include the scheme for path that aren't from disk or untitled, like so

<img width="267" alt="screen shot 2018-01-12 at 08 56 38" src="https://user-images.githubusercontent.com/1794099/34886025-a55a1566-f776-11e7-944f-9ab78bc1b850.png">

**Comment by DanTup** [comment]
@jrieken For me, I didn't actually want the user to see the scheme. As far as the user is concerned, this is just a file-system file. The only reason I use the scheme is because it was suggested as a way to open a file as read-only.

Is there any possibility of a way to do this that doesn't make the file look different to the user? It's probably useful for many languages - for ex. today if I F12 on a typescript def it takes me to `.d.ts` files in `node_modules` that are editable but ideally would be read-only.
