### ISSUE TITLE
Click + Scroll on long lines of code, jumps to adjacent rows 

### ISSUE THREAD

**Issue by ahinkle** [Microsoft/vscode#40663]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.4.1
laravel-goto-view|cod|1.1.3
php-debug|fel|1.12.1
ftp-simple|hum|0.5.8
python|ms-|0.9.1
laravel-blade|one|1.10.0
laravel5-snippets|one|1.3.4
vscode-icons|rob|7.19.0
code-spell-checker|str|1.6.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Highlight a long line of code
2. Barely move the mouse to the row above or below it will automatically go to the beginning of the line

Really annoying for simple highlight and change edits. Is there anything that sets the threshold before it moves on to the next row?.. or even to not scroll to the beginning of the next line?

At the moment, I only use my arrow keys as an alternative.. or I have to be very careful and not get close to the row above and below the line I'm working on. I've attached a GIF as an example.

I've looked in the settings for "scroll" options and i'm unable to find anything. Anyone have any ideas?
https://stackoverflow.com/questions/47928841/vscode-scrolling-to-next-line-on-long-lines-of-code

GIF:
https://i.stack.imgur.com/cFWCV.gif

Reproduces without extensions: Yes

**Comment by ahinkle** [comment]
Small Update: Updated to version 1.19.1 and used `code --disable-extensions`. Still getting the same issue.

**Comment by weinand** [comment]
I've compared this behaviour with other editors (Sublime and TextMate) and see no difference.
What do you suggest should VS Code do? Introducing a hysteresis?

**Comment by ahinkle** [comment]
Yeah, I just tried with sublime too - I'll be more careful with my mouse movements.  Thanks
