### ISSUE TITLE
JavaScript syntax highlighting fails with ternary operator

### ISSUE THREAD

**Issue by elisee** [Microsoft/vscode#4067]
Hi!

Running Visual Studio Code v0.10.10, the following JavaScript lines are incorrectly highlighted:

```js
let a = true ? true : true; // the last "true" should be colored
let a = true ? true : `this is ${incorrectly} highlighted`;
this should not be in yellow.
```

Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/446986/13723459/738bcb36-e866-11e5-9742-cad114fa71e4.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#124
