### ISSUE TITLE
There seems to be a strange issue with smooth scrolling

### ISSUE THREAD

**Issue by yardenhochman** [Microsoft/vscode#40670]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
react-pure-to-class-vscode|ang|1.1.1
react-food-truck|bur|1.0.1
simple-react-snippets|bur|1.1.0
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.3
prettier-vscode|esb|1.0.1
css2react|got|0.0.4
vscode-lebab|jer|1.0.2
PowerShell|ms-|1.5.1
sublime-keybindings|ms-|3.0.3
vscode-docker|Pet|0.0.22
material-icon-theme|PKi|3.2.0
ejs-language-support|Qas|0.0.1
vscode-icons|rob|7.19.0
vscode-import-cost|wix|2.5.1
JavaScriptSnippets|xab|1.5.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.ctrl+mouswheel down
2.ctrl+mouswheel up

the texts jumps in sizes. Disabling smooth scrolling on windows solves the issue.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Can you repro this when running `code --disable-extensions`?

**Comment by yardenhochman** [comment]
Will do

**Comment by alexandrudima** [comment]
@yardenhochman 

`ctrl+mouse wheel` will not do anything out of the box.

There exists a setting, `editor.mouseWheelZoom`, which, once you've set to `true` will make it that `ctrl+mouse wheel` will increase/decrease the font size of the editor.

I'm not sure what exactly the problem is.
