### ISSUE TITLE
CMD

### ISSUE THREAD

**Issue by VgsdStudios** [Microsoft/vscode#40675]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---
Hello, I was working on Visual Studios to create my own Discord Bot, but now that I'm trying to make my Package,json file, I notice that the terminal wont run npm init.
I saw hat the Terminal the application is using, is CMD. I decided to open CMD on my computer and I ran the npm init command and it worked there. I was wondering if I could be told on how to Change the terminal to the one that is working or how to fix the current one. Thanks!!

**Comment by Tyriar** [comment]
Have you tried restarting VS Code? You can also try comparing the PATH of the external and integrated terminal by running `echo %PATH%`
