### ISSUE TITLE
Explorer order files names with underline

### ISSUE THREAD

**Issue by im-andresgs** [Microsoft/vscode#40679]
- VSCode Version: 1.19.1
- OS Version: Windows 10
- My setting:
  - "explorer.sortOrder": "default"

Steps to Reproduce:

1. See Explorer
2. Create files 
 - app.txt
 - app_a.txt
 - app_a_a.txt
 - app_a_b.txt
 - app_a_b1.txt
 - app_a_b2.txt
 - app_b.txt
 - app_c.php
 - app_d.txt

Like that is the normal order but in VSCode it shows like this:
 - app_a_a.txt
 - app_a_b.txt
 - app_a_b1.txt
 - app_a_b2.txt
 - app_a.txt
 - app_b.txt
 - app_c.php
 - app_d.txt
 - app.txt

** In case that u see: ".php" vs ".txt" I think is correct the order by type.

![sin titulo](https://user-images.githubusercontent.com/29309543/34279030-741b4fe8-e67c-11e7-8ca1-168a33105182.png)

**Comment by gjsjohnmurray** [comment]
Since April 2022 [Explorer file nesting](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting) offers a solution to this.
