### ISSUE TITLE
Inconsistent strange behavior with TypeScript

### ISSUE THREAD

**Issue by jchitel** [Microsoft/vscode#40672]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 15.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
vscode-todo-highlight|way|0.5.11

Before the 1.19 update, I was getting very strange behavior working with TypeScript where some new files that I created (sometimes when copying as well) would be using some different TypeScript configuration than the one it was supposed to be using. I have VS Code configured to use my local TypeScript configuration. The only way to fix this issue was to switch to VS Code's TypeScript version, then back to my own. Closing and reopening the file wouldn't work, and restarting VS Code didn't work. This was quite annoying but the workaround was simple enough.

Now, after the update, the behavior seems to have manifested itself in a different way, in addition to the original issue. In some files, when I am dealing with a TypeScript error, sometimes the error underline stays even after I fixed it. The text range of the error seems to be trying to stay where the error was previously, even when I move the text around by adding/removing characters before the error. To fix this, I need to close and reopen the file. The TS version switch didn't work, and restarting VS Code didn't work.

I also had one instance where I wanted to use the "Ctrl+." feature to add an import for a missing value. The TypeScript server in the background seemed to reflect the change, removing the underline for the error, but the editor had not changed at all. Killing and restarting VS Code was the only way to fix this issue, and I was able to see the line that was added.

It's getting to the point where I can't trust that my code actually has no errors, or even if the TypeScript server even has the same code that I'm looking at. Due to the inconsistent nature of the problems and the fact that not all of the problems are solvable the same way, this seems to be a very obscure combination of problems.

---

Steps to Reproduce:

I have not yet found an even remotely reliable way to reproduce any of these issues.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Please try setting: `"typescript.tsserver.trace": "verbose",` in your user settings. Then, the next time this error happens, open the output panel and go to the `TypeScript` section. Look for any errors messages or stack traces in those logs

**Comment by jchitel** [comment]
Will do, thanks!

**Comment by jchitel** [comment]
I just ran into a simple example of what I've been seeing.

I created a new .ts file and moved an interface from an open file to that new file. When I came back to the original file, there were (expected) errors on references to the interface. Normally, I would be given a code fix to quickly import the interface from the new file, but in this instance I was not given one. The verbose trace showed as much. I saw a request for code fixes, and an empty list as a result. But there is a lot of text here, and I have no idea what I'm looking for.

I was able to get the expected behavior by switching to the VS Code TS Config and back to mine, just like before, and I still see no errors.

I do see a few responses that come back with `success: false` before I switched the configs. Might that have something to do with it?

```
[Trace  - 23:13:48] Sending request: signatureHelp (12542). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/<path-to-new-file>.ts",
    "line": 61,
    "offset": 33
}
[Trace  - 23:13:48] Response received: signatureHelp (12542). Request took 4 ms. Success: false . Message: No content available.

...

[Trace  - 23:14:00] Sending request: quickinfo (12557). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/<path-to-new-file>.ts",
    "line": 27,
    "offset": 70
}
[Trace  - 23:14:00] Response received: quickinfo (12557). Request took 1 ms. Success: false . Message: No content available.

...

[Trace  - 23:15:10] Sending request: quickinfo (12572). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "<path-to-old-file>.ts",
    "line": 17,
    "offset": 32
}
[Trace  - 23:15:10] Response received: quickinfo (12572). Request took 1 ms. Success: false . Message: No content available.
```

**Comment by jchitel** [comment]
This just happened to me again, same as above. I just realized that the "quickinfo" requests are what happens when I try to mouse over something. In this case, when I get a "Success: false" I get no quickinfo pane at all. I able to consistently get this behavior in this file that I have open, but when I reset the config, the problem goes away. I still have no idea what causes this weird state to happen. The verbose output is not showing enough information in this instance.

I realize how frustrating this must be with no steps for reproduction. I'm trying to figure it out too. I noticed this happening right after I got finished fixing some TS errors, but there are still errors left in the file.

**Comment by jchitel** [comment]
It seems to only happen at times when I've created or renamed multiple files within a few seconds. These are the kinds of issues I see:
- not recognizing aliases that I have in my tsconfig.json
- some expected code fixes are not available
- some quick info is not available
- some compiler settings (such as strictNullChecks) are not on in the offending file(s)

**Comment by jchitel** [comment]
I should note that I use VS Code on Windows and OS X and I have never seen these issues on Windows, only on OS X.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?
