### ISSUE TITLE
Feature Request - Format Document (K&R Style)

### ISSUE THREAD

**Issue by cruzjessie8** [Microsoft/vscode#40678]
- VSCode Version: Version (1.19.0) 
- OS Version: Version (10.13.1)
- Extensions: Cannot find any good ones.

Question:
1. Are there any good vs code formatting extensions that follow the K&R Style?
- Out-of-the-box, vs code does not format this way and was wondering if they can have this option in future updates. 'Eclipse' formats very well (cmd+i) for java but I would like a general formatter that also does this for C, for example. Thank you.

**Comment by weinand** [comment]
Please file specific requests against the Java or C/C++ language extensions.
