### ISSUE TITLE
Provide a global hotkey to launch VS Code

### ISSUE THREAD

**Issue by epilande** [Microsoft/vscode#40677]
- VSCode Version: 1.19.1
- OS Version: 10.13.1

It would be nice to have the ability to toggle VSCode with a global system-wide hotkey. 

Example: 
![image](https://user-images.githubusercontent.com/3210082/34278591-a88bfbfe-e660-11e7-8456-93b7532eab48.png)

**Comment by weinand** [comment]
I don't quite understand what you are asking for.
On macOS I can use Command-H to hide all VS Code windows.
Where does the screenshot from above originate from?

**Comment by epilande** [comment]
Ah yes, I'm currently doing that too. I use `cmd` + `h` to hide then `cmd` + `tab` to bring it back. 
Though I still think it would be beneficial to toggle VSCode with a hotkey. So I can go between multiple apps and switch back to VSCode easily. 

I use a couple of applications that allow for this option.
That screenshot above is from iTerm.

Todoist: 
![image](https://user-images.githubusercontent.com/3210082/34279566-80ad15c2-e666-11e7-80f1-1ba6bf6ebe36.png)

Bear App:
![image](https://user-images.githubusercontent.com/3210082/34279587-9827f6ae-e666-11e7-99c5-543dc543f038.png)

**Comment by bpasero** [comment]
@epilande I am not sure what VS Code can do here, isn't that something that should be configured per OS using OS mechanisms?

**Comment by fabiospampinato** [comment]
@epilande for this kind of things I would rather configure something like [phoenix](https://github.com/kasper/phoenix).

**Comment by epilande** [comment]
@bpasero @fabiospampinato I've tried setting something up with MacOS but had no luck. I've resulted in using a third party application to achieve this, similar to Phoenix. Though it would be nice if I didn't have to open a different application and if VSCode can support this as a configurable option. 

This is really just a workflow thing. Not everyone will use this option but this is something that helps boost my productivity and how I develop applications. My example workflow is, I work on my laptop a lot (small screen), so I like to have my applications take up the full screen (but not in fullscreen mode, the animation takes too long and lose context..😕). For example, my editor, chrome/firefox, slack, notes, etc. then toggle between applications by showing/hiding my editor. So having a global hotkey to show/hide VSCode would be extremely helpful. 

The point of this is to remove friction from switching between apps. I know there's `cmd` + `tab`, but what happens when a user switches between 3 or 4 apps, they'll have to hit `cmd` + `tab` multiple times. Another example is using `cmd` + `h` to hide and using Spotlight or Alfred to reopen, this can be simplified with a global hotkey to toggle show/hide. 

Nonetheless, great job with VSCode! I've completely switched from iterm + vim + tmux to VSCode. Thanks for a solid application 👌

**Comment by nylqd** [comment]
@epilande I am trying find solution for this show/hide operation as well, so I am wondering what kinds of solution you end up to. Since there do not have native support from VSCode, a 3rd party application would also be appreciated.😀

**Comment by epilande** [comment]
@nylqd I'm currently using [BetterTouchTool](https://www.boastr.net/), it's a paid product but it's pretty powerful, it lets you remap your keys, mouse, touchbar, applications, etc..

**Comment by weinand** [comment]
@nylqd yep, that's a good approach for this feature.

**Comment by nylqd** [comment]
@epilande Unfortunately this issue is closed, still,  thank you for ur recommendation, much appreciated.
