### ISSUE TITLE
Small window with 7611 pops up

### ISSUE THREAD

**Issue by szhongren** [Microsoft/vscode#40685]
Seems like a weird config issue with my computer or something, but when I do ctrl-shift-P a small window pops up with 7611 in it. Happens even with extensions disabled. ctrl-P works fine though, as does using ctrl-P and then >. Any clues where I should start looking to figure out what's happening?

My machine is a Gigabyte Aero 15x, just got it, so I have no idea what could be causing this. 

VS Code version 1.19.0 x64

Extensions:

- azemoh.one-monokai
- christian-kohler.path-intellisense
- dracula-theme.theme-dracula
- eamodio.gitlens
- Equinusocio.vsc-material-theme
- formulahendry.code-runner
- HookyQR.beautify
- humao.rest-client
- kalitaalexey.vscode-rust
- lukehoban.Go
- ms-python.python
- ms-vscode.cpptools
- robertohuertasm.vscode-icons
- vangware.dark-plus-material
- vscodevim.vim
- zhuangtongfa.Material-theme

**Comment by weinand** [comment]
Please provide a screenshot of the problem.

**Comment by szhongren** [comment]
Sorry, here's a screenshot of what it looks like. Running Windows 10 x64.

![image](https://user-images.githubusercontent.com/8567599/34312509-51c50a5c-e72a-11e7-9147-5d6eb7527fef.png)

I reinstalled VS Code, as well as all my extensions, and the number changed. I seem to get 6667 now instead.

**Comment by weinand** [comment]
But you can 100% reproduce this when running VS Code 1.19.1 (the latest) from the command with `code --disable-extensions`?

**Comment by szhongren** [comment]
Yes.

![image](https://user-images.githubusercontent.com/8567599/34312891-f428019e-e72c-11e7-97e0-fa5d17ea1386.png)

**Comment by weinand** [comment]
@bpasero have you seen something like this before?

**Comment by weinand** [comment]
What happens when you type ctrl-shift-P outside of VS Code (or when VS Code is not running)?

**Comment by szhongren** [comment]
Oh my god. I'm an idiot should have tested that first. Seems like a firmware issue with this particular make.
