### ISSUE TITLE
I can't assign 'Alt+J' to {   "key": "",   "command": "editor.action.addSelectionToNextFindMatch" }

### ISSUE THREAD

**Issue by ChrisZ-B612** [Microsoft/vscode#40688]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vetur|oct|0.11.5

---

Steps to Reproduce:

1. Try assign 'Alt+J' to 'editor.action.addSelectionToNextFindMatch'
2. It's just not working at all.

Reproduces without extensions: Yes/No

**Comment by alexandrudima** [comment]
@ChrisZ-B612 is `alt+j` a keybinding which VS Code receives from the OS?

What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
