### ISSUE TITLE
How to debug QT application written in C++ code on Windows platform using VSCode?

### ISSUE THREAD

**Issue by 10manjunath** [Microsoft/vscode#40689]
I'm unable to debug qt application step by step using GDB. I have setup a launch.json with cygwin GDB on windows. I tried the both "launch and attach" methods to debug. When I use the attach mode, it's successfully showing the call stack with some threads in it, but VSCode is still not debugging line-by-line and encountering my breakpoints. The step in/over buttons are disabled.

![image](https://user-images.githubusercontent.com/7700267/34284444-f010abac-e69f-11e7-8739-de59e0cc72a3.png)

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode-cpptools
