### ISSUE TITLE
Test TypeScript and JavaScript grammar updates

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#4068]
**Issue:** 
**Assignees:**

- [ ] @jrieken 

**Details:**
The TypeScript/JavaScript grammars have been updated. They include multiple fixes, in particular:
- https://github.com/Microsoft/TypeScript-TmLanguage/issues/37 
- https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

- check out multiple TS and JS files and have a look at type references and keywords.
- test all our 4 default themes

As this update also required changes to our default themes, we also need to test the default themes with other languages:

- [x] Bat @weinand 
- [x] Clojure @weinand 
    Known change: The light blue for definitions is gone. This was an accidental match.
- [x] Coffeescript @weinand 
- [x] C  / C++ @weinand 
- [x] C#
- [x] CSS @isidorn
- [x] Docker @isidorn
- [x] F# @isidorn
- [x] Go @isidorn
- [x] Groovy @bpasero 
- [x] Handlebars @bpasero 
- [x] HTML @bpasero 
- [x] Ini @bpasero 
- [x] Jade @isidorn 
- [x] Java @isidorn 
- [x] Javascript
- [x] JSON @isidorn 
- [x] Less @isidorn 
- [x] Lua @isidorn
- [ ] Make @alexandrudima 
- [x] Markdown
- [ ] Objective-c @alexandrudima 
- [ ] Perl @alexandrudima 
- [ ] Php @alexandrudima 
    The PHP meta tag now has the same color as other html tags
- [x] Powershell @isidorn 
- [x] Python @isidorn
- [x] R @isidorn
- [x] Razor @isidorn 
- [x] Ruby @bgashler1 classes are no longer colored when used (still colored when defined).  Seems to follow TypeScript's style.
- [x] Rust @bgashler1 
- [x] Sass @bgashler1 
- [x] Shaderlab @bgashler1 classes are no longer colored when defined. What used to be their color is now used for types.  Both of these differences seem odd (I don't use Shaderlab currently, though).
- [x] Shellscript @SofianHn 
- [x] Swift @SofianHn 
- [x] Tsql @SofianHn 
- [x] Typescript
- [x] Vb @SofianHn 
- [x] Xml/Xls @gregvanl
 The xml meta tag now has the same color as other xml tags on Dark+ and Light+. I think that's a good thing. It had been purple.
- [x] Yaml @gregvanl Attribute value blue is brighter on Light and Light+ themes.  Easier to read.

**Comment by isidorn** [comment]
@jrieken @aeschli do we plan to do more testing here? If not please close the issue once done.
If more help is needed I can assign someone from redmon

**Comment by isidorn** [comment]
Always reload this page before checking off so no checkboxes are lost (due to bad git hub conflict management)
