### ISSUE TITLE
focus position changed after press ctrl+s saving file

### ISSUE THREAD

**Issue by cenfun** [Microsoft/vscode#40684]
- VSCode Version:  Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: windows 10

![lose-focus-after-ctrl s](https://user-images.githubusercontent.com/334577/34282293-356cacdc-e6ff-11e7-804e-90c0d944d9f5.gif)

Steps to Reproduce:

1. click any where in the code
2. press ctrl+s save the file
3. the focus positon changed(move to end). it should stay in the position where step 1 clicked

this is so bad I can't type any next code after ctrl+s saving the file.

this is previous issue:
https://github.com/Microsoft/vscode/issues/38029

it doesn't fixed in new version.

**Comment by weinand** [comment]
Can you repro this when running `code --disable-extensions`?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.

**Comment by cenfun** [comment]
@weinand thanks, I just found it's caused by JS-CSS-HTML-formatter extension when disable this extension the problem will gone. I post a new issue to JS-CSS-HTML-formatter:
https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/87

**Comment by weinand** [comment]
Thanks for letting me know!
