### ISSUE TITLE
Integrated terminal stopping in the middle of program execution

### ISSUE THREAD

**Issue by akhiln28** [Microsoft/vscode#40683]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
vscode-great-icons|emm|2.1.22
easy-icons|jam|0.3.1
python|ms-|0.9.1
cpptools|ms-|0.14.5
sublime-keybindings|ms-|3.0.3
java|red|0.16.0
dot|Ste|0.0.1
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

`int main()`
`{`
`for(int i = 0;i < 100;i++)`
`cout << "hello world " << i << endl;`
`}`
1.consider the above program, running it in the integrated terminal doesn't print upto 99(hello world 99). It stops randomly in the middle. (stops at 65,85.. and even 2)
2.I tried with three different terminals (command prompt, git Bash, developer command prompt for visual studio). The same happens for all of them.
3. The above three terminals work perfectly file externally.
I searched everywhere in the internet but could find similar result.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
I'm not too familiar with building C++, can you provide instructions to build or a script in another language if it repros there.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36787
