### ISSUE TITLE
title doesn't change when switching open files via tabs

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#40686]
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:36:58.030Z)
- OS Version: Win7 64bit    Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
xml|Dot|1.9.2
gitlens|eam|7.0.0
json-tools|eri|1.0.2
Go|luk|0.6.70
cpptools|ms-|0.14.5
java|red|0.16.0
cmake|twx|0.0.17
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Open VSCode, and open a few files.
2.switch open files via tab, the title doesn't change to the right file path.
3.if I change the size of the VSCode window, or minimize then maximum, the title is refreshed to the currently open file path.

I reported this issue in VSCode 1.18.0-Insider, [issue](https://github.com/Microsoft/vscode/issues/36018),
but it still exists in Win7 OS in the most recently insider version.
In my Win 10 OS, there is not the bug.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31536
