### ISSUE TITLE
When i publish my extension the README.md is not displayed

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#40697]
I made an extension for our specific scripting-language and wanted to try the publishing now.

Extension files are here for reference only - i removed the published extension again atm:
https://github.com/Raydir/F-Script

If I publish the extension using vsce publish everything works fine - except that the README.md and CHANGELOG.md etc. are not shown. The message says KeineINFODATEI (aka No README).

![grafik](https://user-images.githubusercontent.com/17499573/34288607-83a5b198-e6ee-11e7-87a5-fe6479cff9bd.png)

I dont get what I'm doing wrong - if i install the extension via VSIX it works.

Any advice would be wellcome- not sure if this is a bug or if i'm doing something wrong.

**Comment by joaomoreno** [comment]
Can you publish your extension again, so I see it in the Marketplace?

**Comment by Raydir** [comment]
@joaomoreno  done. You may seek for Opacc F-Script

**Comment by Raydir** [comment]
ahm... @joaomoreno  did you do something in the meantime? it seems that the README.md is working now?

**Comment by Raydir** [comment]
problems seems to be solved... i close this issue again.
