### ISSUE TITLE
default keybindings view

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40696]
i have chose wrap words but in this view . left panel is still not wrap. which make difficult to compare the content. hope can wrap words and if can not edit. please make it auto format...  some of ugly now.

**Comment by weinand** [comment]
I don't understand your problem. Please provide screenshot.

For me the keybindings view looks fine without wrapping:
![2017-12-22_10-35-40](https://user-images.githubusercontent.com/1898161/34293201-280e8b28-e704-11e7-8184-5ef6a84ed389.png)

**Comment by midGitub** [comment]
click
![image](https://user-images.githubusercontent.com/20261416/34293879-2ef208ba-e741-11e7-8865-b73d0963f127.png)
the view below is not wrap word
![image](https://user-images.githubusercontent.com/20261416/34293847-18391730-e741-11e7-8046-46aa02fe0308.png)

**Comment by weinand** [comment]
With the setting `"editor.wordWrap": "on",` json files have word wrap:
![2017-12-22_11-57-28](https://user-images.githubusercontent.com/1898161/34295816-a2f1c35e-e70f-11e7-9b09-1e3f4a98258b.png)
