### ISSUE TITLE
Selection enhance

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40694]
remember last selection state like sublime.
press ctrl+z to the pre selection state

**Comment by weinand** [comment]
VS Code already remembers the last selection after a restart.
So your "enhancement" is just asking for the "undo" history being preserved as well?

**Comment by midGitub** [comment]
the situation is some kind of complicated.
when i do double-clicked to select words . it will recover the cursor to then the beginning of the last selected word. and do not recover the selection state.

**Comment by alexandrudima** [comment]
We have two "undo" actions implemented:
* ctrl+z - `undo` - this is the classic undo. It will undo the selection to the state it was before the last edit
* ctrl+u - `cursorUndo` - this is a softer undo. It will undo only the selection state, up to, but excluding of the last edit.
