### ISSUE TITLE
[seti] ts icon should be blue

### ISSUE THREAD

**Issue by anetegithub** [Microsoft/vscode#40691]
# You're my boy, Blue!

- VSCode Version:  1.20.0-insider
- OS Version: Windows 10 1709 (16299.125)

Please, return back dark-cyan color for *.ts files, Yellow really annoying.

**Comment by aeschli** [comment]
This happened when seti added a yellow icon for .spec.ts.

**Comment by bpasero** [comment]
Still yellow for me:

![image](https://user-images.githubusercontent.com/900690/35680484-cf6651fa-075a-11e8-8232-8b99a2a069d0.png)

**Comment by aeschli** [comment]
@bpasero I don't see this. Are you sure you are on the latest? You should also see an icon for `test.jsonc`

**Comment by aeschli** [comment]
Ah, spec.ts is should be yellow, as defined in the seti theme: https://github.com/jesseweed/seti-ui/blob/16dc5ccb7db6329f99c20c75fc7b536965765a96/styles/components/icons/mapping.less#L315

**Comment by aeschli** [comment]
IMO all is fine. @bpasero Please reverify: `.ts` should be blue `.spec.ts` yellow

**Comment by bpasero** [comment]
Yeah that is what I see.
