### ISSUE TITLE
adding entry into workspace settings causes chaos.

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#40699]
- VSCode Version: 1.19.0
- OS Version:  Microsoft Windows 10 Enterprise 10.0.16299 Build 16299

### Some context
* I'm developing an extension.
* I add an entry at `configuration` part in `package.json`.
* I read the value by `vscode.workspace.getConfiguration("myextension").get<string>("test")`
```
"myextension.test": {
            "type": "string",
            "default": "default",
            "scope": "window"
          }
```

### Steps to Reproduce:

1. At first, `"myextension.test"` is not specified in either `user settings` or `workspace settings`. The value is `default`, as expected.
2. Add `"myextension.test": "user"` in `user settings`, and save it.  The value now changes to `user`, as expected.
3. Add `"myextension.test": "workspace"` in `workspace settings`, and save it.  The value now changes to `default`, which is NOT as expected.
4. Moreover, now remove the entry (added in step 3) from `workspace settings`, and save it. The value remains to be `default`, which is NOT as expected.

Result of Step 3 & 4 are not as expected, it's very confusing, so I think it's probably a bug.

From my expriments, if the configuration entry is not set in `workspace settings` at the very begining(e.g. before opening/reloading the window), the action of adding the entry will cause its value fallbacks to default.

Reproduces without extensions: Not tested, I think it's nothing todo with other extensions.

**Comment by sandy081** [comment]
@Eskibear I am not able to reproduce it. Can you please provide your example code so that I can use it to reproduce.

**Comment by Eskibear** [comment]
@sandy081 I forgot to say that, it only occurs in **multi-root** workspace.

![image](https://user-images.githubusercontent.com/2351748/34318310-a677898c-e7ff-11e7-9ca2-8389e36f4e6b.png)

**Comment by Eskibear** [comment]
### More details

* It only occurs in **unsaved multi-root workspace**. 

After I save the workspace as `somename.code-workspace` somewhere, it works well then.

### Repro Steps
1.  Open a new window, and open a  folder, call it `folder-a`.
![image](https://user-images.githubusercontent.com/2351748/34375196-37ca00f4-eb20-11e7-88d1-15f6453d586c.png)

2. **[IMPORTANT]** Trigger `Add Folder to Workspace ...`, and open another folder, call it `folder-b`.    **So now it's an unsaved workspace.**  
![image](https://user-images.githubusercontent.com/2351748/34375700-c033d0d0-eb22-11e7-8475-b687fa5d109d.png)


3. Specify sth in `workspace settings`. Then you can find that the value doesn't actually apply, it fallbacks to the default value.
![image](https://user-images.githubusercontent.com/2351748/34375668-a31606b2-eb22-11e7-9f31-bcaa49af60ae.png)



That's it, I've tried this on multiple machines, all successfully reproduced. 
FYI : )

**Comment by sandy081** [comment]
@Eskibear Thanks for the steps. I will try to reproduce it.

**Comment by Eskibear** [comment]
Supposed to be resolved. Close it.
