### ISSUE TITLE
Looking fo a tool can format razor

### ISSUE THREAD

**Issue by MLittleToo** [Microsoft/vscode#40698]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
mssql|ms-|1.3.0
csharp|ms-|1.13.1
aspnet-helper|sch|0.6.4

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
I'm not a aware of an extension that provides razor formatting.

**Comment by ahdung** [comment]
What extension? and why @vscodebot so like close issue?

**Comment by weinand** [comment]
"Please ask your question on StackOverflow. We have a great community over there. They have already answered thousands of questions and are happy to answer yours as well. See also our issue reporting guidelines."
