### ISSUE TITLE
TypeScript tsserver error after yeoman generation of extension

### ISSUE THREAD

**Issue by jeryanders** [Microsoft/vscode#407]
I created a new TypeScript extension for Code by running `yo code` and I received this error when I opened the extension folder in Code:

The path /Users/jranderson/workspace/dot-net-apps/Hello World/node_modules/typescript/lib doesn't point to a valid tsserver install. TypeScript language feature will be disabled.

I ran `npm i -g typescript` and installed it. However, I still get the error.

**Comment by bpasero** [comment]
@jeryanders you should have a typescript folder in your node_modules! We do not pick up the global typescript, so please install into the extension.

**Comment by jeryanders** [comment]
Got it! Works now, thanks!
