### ISSUE TITLE
Go to definition not working when using tilde for project root

### ISSUE THREAD

**Issue by dreszczyk** [Microsoft/vscode#40707]
As you can see in the screenshot i'm importing `AppPage` from `core/components` and `ctrl + click` is not working on it (just jumps to the import). When I try the `Go to definition` option on the `components` in the import it opens `index.js` in `core/components` folder (which is fine).

![image](https://user-images.githubusercontent.com/5095527/34291392-5b18615e-e6fc-11e7-9582-a646820f11c2.png)

I tried this `tsconfig.json` file I found online in the project root, but with no luck (paths are changed):
```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "allowJs": true,
        "baseUrl": "/home/user/project/",
        "paths": {
            "~/*": [
                "client_side/app/*"
            ]
        }
    }
}
```

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
If you run the `JavaScript: Go to project configuration` vscode command in that file, does it open your `tsconfig?`

Also, what is the path to the root of your workspace? Can you use a relative `baseUrl` instead like `"baseUrl": "."`?

**Comment by Piotr-Aueternum** [comment]
Firstly remove `tsconfig.json` from react project then create `jsconfig.json` with setup:
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "ES6",
        "module": "es6",
        "jsx": "react",
        "baseUrl": "./",
        "paths": {
            "~/*": [
                "./app/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
