### ISSUE TITLE
[API Counsel || Suggestion] About the auto Navigation file in Side-bar Explorer

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40705]
[API Counsel | Suggestion] About the auto Navigation file in Side-bar Explorer

Specify the use situation.
add a function that set it auto navigation the file in explorer view or not auto-navigation.

and add a function that and jump to explorer view and navigate then active file when then focus is in editor.

**Comment by isidorn** [comment]
Try this option `"explorer.autoReveal": true`

**Comment by midGitub** [comment]
it works ,thank you :)~
