### ISSUE TITLE
Support for relative path for sources when gdb set-substitution is used

### ISSUE THREAD

**Issue by 0x00deaf** [Microsoft/vscode#40701]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:34:22.110Z)
- OS Version: Linux x64 4.14.4-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vsc-material-theme|Equ|1.1.2
material-icon-theme|PKi|3.2.0
vscode-docker|Pet|0.0.22
code-settings-sync|Sha|2.8.7
jupyter|don|1.1.4
json-tools|eri|1.0.2
vscode-text-pastry|jkj|1.2.0
cppcheck|mat|0.2.1
vscode-clang|mit|0.2.2
hg|mrc|1.2.3
python|ms-|0.9.1
cpptools|ms-|0.14.5
autodocstring|njp|0.1.2
vscode-icons|rob|7.19.0
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.6.0
change-case|wma|1.0.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by 0x00deaf** [comment]
Hi, when using gdb its quite often that path substitution is used that uses relative path instead of absolute path (e.g something like set path-substitution /workspace/cpp ./cpp) This works in GDB but seems to be not working in visual studio. I would expect this to be resolved relatively to the workspace directory which is specified in debugger launch.json. This would be expected behavior I suppose. Thanks.s

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by 0x00deaf** [comment]
Makes sense. Raised https://github.com/Microsoft/vscode-cpptools/issues/1370
