### ISSUE TITLE
Allow per workspace keybindings configuration

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40703]
there is setting.json in folder .vscode,  but not when new a keybinding.json , it is not effective.

**Comment by fabiospampinato** [comment]
@midGitub In which case would a local shortcut make sense but not a global one? 🤔

**Comment by alexandrudima** [comment]
There is no work planned here. An in-depth explanation - https://github.com/Microsoft/vscode/issues/10708#issuecomment-241330047
