### ISSUE TITLE
Errors detected while running the preLaunchTask on every task run

### ISSUE THREAD

**Issue by ibhub** [Microsoft/vscode#4070]
I have message "Errors detected while running the preLaunchTask" on every task run. But my preLaunchTask does not contain errors, when I run task via "F1->Tasks: Run task" there is no problem.

**launch.json:**
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run local debug",
			"type": "node",
			"request": "launch",
			"cwd": "${workspaceRoot}/build",
			"program": "${workspaceRoot}/build/server.js",
			"outDir":  "${workspaceRoot}/build",
			"stopOnEntry": false,
			"sourceMaps": true,
			"preLaunchTask": "Build debug local"
		}
	]
}
```

**tasks.json:**
```
{
	"version": "0.1.0",
	"command": "npm",
	"isShellCommand": true,
	"showOutput": "silent",
	
	"tasks": [
		{
			"taskName": "Build debug local",
			"suppressTaskName": true,
			"args": ["run", "gulp", "--", "--stand=local"],
			"isBuildCommand": true
		}
	]
}
```

**gulpfile.js:**
```
gulp.task("default", function(done) {
	done();
});
```

**package.json:**
```
{
...
  "scripts": {
    "gulp": "./node_modules/.bin/gulp",
  }
...
}
```

**Comment by isidorn** [comment]
Can you please attach a screenshot of your whole vscode with the error message you get.
Do you have some errors shown in the lower right corner of your screen?

**Comment by ibhub** [comment]
This issue don't reproduce after restart vscode. Debug works perfectly. Please close it. Sorry.

Message displayed at top of window. Debug console was empty. In ouput console was not errors.

**Comment by haoliangwu** [comment]
hi all, 

I encounter the same issue seems like this.

When I started debugging at the first time(with F5), then error message didn't display. Then if I try to reconnect to debug instance(with Ctrl + Shirt + F5), the error message display. 

I defined a task that compiles code from ES6 to ES5 and added it to `preLaunchTask`. Via "F1->Tasks: Run task" there is no problem.

something like this:
![_007](https://cloud.githubusercontent.com/assets/6328186/14135743/cf569250-f691-11e5-9850-14841405252e.png)

Anybody can help me? Although it wasn't a big problem, but it was really noisy.

Thx a lot.

**Comment by isidorn** [comment]
Do you have some errors shown in the lower right corner of your screen?

**Comment by haoliangwu** [comment]
@isidorn 
Sorry for the delay, I didn't see any errors shown in the lower corner of my screen.

**Comment by isidorn** [comment]
Then we would appreciate if you could create a repository on github where we can reproduce this behavior so we can investigate. Or some other way to reproduce this issue.

**Comment by haoliangwu** [comment]
@isidorn 
It seems that the issue only occurs on Ubuntu, caused I've tested it on Win 7 and Mac OS, the error message didn't display. Maybe it caused by some operations related to super user permissions. If I run VS Code by the super user, the error messages went away. 

Anyway, thanks for your help.

My learning extension project is [HERE](https://github.com/haoliangwu/vscode-poshi) if you need it for further discovery.

Hope you have a nice day !!

**Comment by mattflix** [comment]
This is happening to me as well on Mac OS X.

When the error message starts appearing, clicking "Continue" on the message allows debugging to proceed normally (apparently the preLaunchTask, in my case a build step, actually worked fine).

In cases where the "errors detected" message appears on launch, there ARE errors listed at the bottom left of the VS Code window, but they don't appear to have been generated by my build preLaunchTask.  

Instead, they are syntax errors that VS Code has found in an open editor file, unrelated to the preLaunchTask.  In my case, these errors were about the "require" call: [js] Cannot find name "require"

The problem with launching only starts appearing after a file is opened in the editor that contains syntax errors (generating errors like the one above).  Closing the file does not clear the errors, and so all subsequent launches begin displaying the "errors detected" message.

The errors can be cleared by restarting VS Code, so perhaps that is why some people have reported that the launching problem often (temporarily) goes away after restarting.

**Comment by vuhrmeister** [comment]
To me this happens as well. 

First run is fine. But re-running fails. After a restart of vscode it works (only) once again.

In my case it happened after I installed some typings (`typings install registry:env/meteor --global`). When I remove them it works again.

**Comment by isidorn** [comment]
@vuhrmeister can you please file a new issue with reproducable steps (possible a small repository I could access to investigate this issue) - thanks!

**Comment by vuhrmeister** [comment]
@isidorn will do, thx
