### ISSUE TITLE
Suggestion About SmartExpandSelection

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40704]
when using the command : "editor.action.smartSelect.grow", provided by the vs-code . 
when the text like this: 

    {
        "key": "alt+oem_4",
        "command": "editor.action.smartSelect.grow",
        "when": "editorTextFocus"
    }, 

the cursor is behind "+", execute this command will select the quotation as well.

now i used a extension named "expand-region", it's result will not select the quotation at the first time and when do next expand . it will select the quotation as well.

**Comment by weinand** [comment]
I don't understand what are you exactly suggesting.
Should VS Code provide the same behaviour as the "expand-region" extension?

**Comment by midGitub** [comment]
yes... i hope it more specific  .

**Comment by jrieken** [comment]
dupe of #4795
