### ISSUE TITLE
Scroll position above first line with Find widget open not retained when switching tabs

### ISSUE THREAD

**Issue by Simran-B** [microsoft/vscode#40713]
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have some long text or a narrow window, so that there is text up to the right border
2. Open Find widget and scroll to the very top
3. With the widget open, one can scroll above the first line in order to see the text under the widget
4. Switch to another tab. It is scrolled to the first line, so text may be partially covered. One can scroll further up though.
5. Switch back to the first tab. The scroll position is reset to the first line.

Expected result: the first tab should had retained the scrolled position above the first line, so that the text stays fully readable. Instead, the widget partially covers it again, and one has to scroll up once more.

I'm not sure if the second tab should automatically scroll to the very top above the first line in this case.

Demo: https://youtu.be/YFenQU9ThQw

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@rebornix giving to you to investigate. I am pretty sure it is some timing problem, where the view state is restored at a time when the find widget didn't create the view zone, or something along those lines...
