### ISSUE TITLE
SCM: Support sort

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#40712]
I find the git panel showing modified files a bit of a mess: files don't seem to be sorted in any way (maybe by full path?):

![vscodegitstatus](https://user-images.githubusercontent.com/199648/34293827-5a2ab080-e706-11e7-905b-fae1a4f28fd9.png)

I find it really difficult to find:

 - which files have been modified
 - which files are untracked
 - a particular file by its name

As a comparison, here is the result of running `git status` in the same workspace:

```
On branch bpmn_shapes_17016
Your branch is ahead of 'origin/bpmn_shapes_17016' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../pom.xml
        modified:   app/scripts/app.js
        modified:   app/styles/onmap.rappid.css
        modified:   app/views/ui-components-module/generic-form.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../../.eslintrc.json
        ../../.vscode/
        ../../Untitled-1.txt
        ../../Untitled-6.json
        ../../chrono.gif
        ../../iframe.html
        ../../npm
        ../../package-lock.json
        ../../pom-standalone.xml
...
``` 

In a quick look I can see that only four files have been modified.

Suggestions:

 - add an option to group by status (ie: untracked, modified, added)
 - add an option to sort files by name

Sort could work like this:

 1. if option is set: sort by status
 2. sort by name

Having a way to filter this list will be a good addition too: in case you want to see the status of a particular file using its name. Like you can do in the settings panel for example, when you look for a specific option.

**Comment by adel-bassiony** [comment]
also please add ability to sort them by folders.
this will be very helpful <3

**Comment by repl-albert-chu** [comment]
I second this. It would be really useful to have this functionality.

**Comment by marcelh-gh** [comment]
especially in multi-root workspaces at least a grouping by root folder would help a lot

**Comment by 0reo27** [comment]
This is a huge feature if added  👍

**Comment by ooHmartY** [comment]
👍

**Comment by avlaguta** [comment]
I second this too!

**Comment by TrustableMe** [comment]
👍🏻

**Comment by ngocmanh1712** [comment]
still waiting for this

**Comment by sniarn** [comment]
When handling a large amount of changes this would be very helpful indeed! +1

**Comment by bravo2zero** [comment]
why is this thing still open after 2 years? working with multiple git repos in root folder is really annoying without control over sorting.

**Comment by fsesterh** [comment]
I'd welcome this too.

**Comment by ngirard** [comment]
Just can't believe this still hasn't been implemented...

**Comment by progonkpa** [comment]
Wanted to switch from PhpStorm to VSC (because cheapskate), then this happened..

**Comment by joaomoreno** [comment]
Grouping is #14582

**Comment by ngirard** [comment]
@joaomoreno, great, thanks !

**Comment by progonkpa** [comment]
@joaomoreno awesome!

**Comment by evangrayk** [comment]
It would be really nice if the SCM API exposed a way to sort files (such as a sort key). This would let us provide our own sorting options. For the original issue, the git extension could provide status / filename / file type. Other extensions could also detect e.g. auto-generated files and sort those lower.

**Comment by wesinator** [comment]
this is badly needed for usability with multi-file projects. 
Should be able to sort both by git status (modified files first), and alphabetical. 

Right now, there is no logical sort order. (1.40.2)

**Comment by bernardoadc** [comment]
I find it useful to sort by modified date/hour.

So if I did a small change and want to commit right away, I easily see where it is, on top. Or, if there is some modification that is still pending (and dont want to stash) it will be on the bottom.
