### ISSUE TITLE
Command to list only methods in a single file

### ISSUE THREAD

**Issue by mayanksingh0821** [Microsoft/vscode#40711]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Command "Goto Symbol in File" (macOS: Command-SHift-O, Windows: Control-Shift-O).

**Comment by mayanksingh0821** [comment]
This command shows all the symbols, assuming there are 20+ methods and 20+ variables, it becomes hard to go through the symbol list. 
Hence we need a command to only list methods along with their signatures like done in visual studio latest versions

**Comment by weinand** [comment]
see https://stackoverflow.com/questions/36154283/method-list-in-visual-studio-code
