### ISSUE TITLE
Breakpoints are not floating correctly together with edits

### ISSUE THREAD

**Issue by DrDelete** [Microsoft/vscode#40715]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
debugger-for-chrome|msj|4.0.0
vscode-docker|Pet|0.0.22

---

Steps to Reproduce:

1. Create some breakpoints
2. Put some edits in the file where the breakpoints are
3. The breakpoints are fixed at the original lines and are not recalculated when new lines are added or lines are removed.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
This works fine for me.
Can you please post a sample file with exact steps on where you place breakpoint, what you edit and what you wuold expect
