### ISSUE TITLE
Test Output Panel

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#40716]
Complexity: 4

- [x] anyOS @chrmarti 
- [x] anyOS @octref 

The underlying implementation of Output channel is changed to use File for storing content  instead of in-memory storage. This made Output panel to be memory efficient and also increased the threshold of channel size to 30MB.  

Purpose of this test plan item is to make sure existing Output channel functionalities are retained without regressions. Following set up will help you in testing it:

<details>
  <summary>Set Up</summary>

Create a sample extension that can do following 

1. Create an Output Channel
2. Append content to output channel
3. Clear content in output channel
4. Show/Hide the output channel

You can use and build on top of following sample

``` typescript
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	let channel, timer, counter = 1;
	const getChannel = (): vscode.OutputChannel => {
		if (!channel) {
			channel = vscode.window.createOutputChannel('Test Channel');
		}
		return channel;
	};
	vscode.commands.registerCommand('testExtension.clearChannel', () => getChannel().clear());
	vscode.commands.registerCommand('testExtension.showChannel', () => getChannel().show());
	vscode.commands.registerCommand('testExtension.hideChannel', () => getChannel().hide());
	vscode.commands.registerCommand('testExtension.startAppending', () => {
		if (!timer) {
			timer = setInterval(() => getChannel().appendLine(`${counter++} // Cancellation that controls whether or not we can cancel in the middle of type checking. In general cancelling is *not* safe for the type checker.  We might be in the middle of computing something, and we will leave our internals in an inconsistent state.  Callers who set the cancellation token should catch if a cancellation exception occurs, and should throw away and create a new TypeChecker.`), 1000);
		}
	});
	vscode.commands.registerCommand('testExtension.stopAppending', () => {
		if (timer) {
			clearInterval(timer);
			timer = null;
		}
	});
	vscode.window.onDidChangeVisibleTextEditors(editors => {
		for (const editor of editors) {
			console.log(editor.document.uri.fsPath)
		}
	});
}
```
</details>

### Test

- **Append content:** Content is inserted into the channel. `appendLine` API should insert new line where as just `append` API should not.
- **Clear content:** Currently shown content is cleared in the channel. 
-- Verify this by using the available `clear` action in the Output panel and also by API.
-- Content is cleared properly, while the content is being added
- **Show Channel:** Should show the selected channel (Verify from Dropdown and API)
- **Hide Channel:** Should hide the Output panel (API). 
- **Toggle Scroll Lock:** Test this action in the UI to lock / unlock the scrolling
- **No content loss:**
-- Make sure that channel content is not lost when you switch between channels or toggle the panel or while performing any other action.
-- Make sure that channel content is not lost while the content is being appended but the channel is hidden.
- **Reset:** Test the content is reset when the channel reaches to the threshold limit. Use the setting `output.threshold` to customise the threshold limit **Note:** This setting is temporary and was introduced only for testing.
- **Visible Editors**: Test that only currently opened channel document is listed in the visible editors. If Output panel is hidden, none of the output channel editors are listed.
-- **Random:** Run commands from the above sample and also available Output actions in the UI randomly and test the results are as expected.

**Comment by chrmarti** [comment]
@sandy081 What would I set `"output.threshold"` to? A number meaning bytes or megabytes?

**Comment by sandy081** [comment]
@chrmarti its number of bytes
