### ISSUE TITLE
Feature to save code snippets online

### ISSUE THREAD

**Issue by fitdhruv** [Microsoft/vscode#40710]
It would be really useful to have a feature to save code snippets online using a login which would eliminate the need to use other similar apps

**Comment by jrieken** [comment]
>  login which would eliminate the need to use other similar apps

Not sure what that means? Can you provide a more detailed use-case please

**Comment by fitdhruv** [comment]
Sorry, missed punctuating that line. I meant to say that the vs code should have a feature to save code snippets and save them to the cloud using a login.

**Comment by jrieken** [comment]
hm, you can kind of do that with extensions that contribute snippets. They are in the cloud but not restricted to some users. We do have a request to allow snippet-files to be in the `.vscode`-folder which might cover your needs.

**Comment by fitdhruv** [comment]
Apologies again for not explaining the use of the word 'snippets'. By it, I mean my code gists that I want to save for future reference.

**Comment by jrieken** [comment]
Haha, that's very different. Yeah, we actually will have support for this. It's a larger story, summarised here: #29194. Other items in the area can be found using the 'remote'-tag: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aremote.
