### ISSUE TITLE
Restarts required when changes are made in AL code

### ISSUE THREAD

**Issue by PhilDOakley** [Microsoft/vscode#40714]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
What do you mean by AL code?

**Comment by PhilDOakley** [comment]
VS Code extension Microsoft AL for Dynamics Nav

**Comment by weinand** [comment]
This issue was moved to Microsoft/AL#1289
