### ISSUE TITLE
Base classes in C++ multiple inheritance not highlight properly

### ISSUE THREAD

**Issue by vlukyanets** [Microsoft/vscode#40720]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
gitlens|eam|7.1.0
vscode-npm-script|eg2|0.3.3
git-project-manager|fel|1.4.0
search-node-modules|jas|1.2.0
python|ms-|0.9.1
cpptools|ms-|0.14.5
bash-debug|rog|0.1.0
cmake|twx|0.0.17
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.Write down C++ class with multiple inheritance
2.For second and next base classes, inheritance accessor (private/public/protected) and base class name aren't highlight

Reproduces without extensions: Yes

**Comment by vlukyanets** [comment]
Reproduced in big project with hundred files and few hundred classes. In small example from one file all is ok.

**Comment by weinand** [comment]
Please file C++ issues against the C++ extension you are using.
