### ISSUE TITLE
RFC: folder specific tsdk setting in a workspace

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#40724]
I found this issue that discusses the "not allowed" wording: https://github.com/Microsoft/vscode/issues/31564

I'd like to request that we be allowed to set tsdk for each folder within a workspace. I have one folder that is a "parent" project that requires typescript 2.5. In that folder is another folder for a separate project (trying to go monorepo) that requires typescript 2.6. It would be nice if based on the file that's open the correct tsdk is used

**Comment by mjbvz** [comment]
Is the version mismatch currently causing any issues?
