### ISSUE TITLE
winpty-agent.exe disk load.

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#40729]
- VSCode Version: 1.19.1
- OS Version: Win10x64

``%PROGRAMS%\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe`` constantly at 500Kbps load on my drive, and thats in 2 instances. Whether in debug or idle. 

![](https://drive.google.com/uc?id=1qU29IRwWjjZNbVV_5p3ajZasPE92uRX5)

Why? How to make it stop?

Thank you.

**Comment by Spown** [comment]
There are also 2 ``conhost's`` started at the same time the winpty's are started - these do additional 20Kbps each:

![](https://drive.google.com/uc?id=1A3NbVg19th3ggFWxYh-NIPLSZcX3vCca)

**Comment by Tyriar** [comment]
The only way to make it stop is to not use the integrated terminal on Windows as winpty-agent.exe enables the feature.

FYI @rprichard
