### ISSUE TITLE
OmniSharp outputs error The "GetReferenceNearestTargetFrameworkTask" task was not found.

### ISSUE THREAD

**Issue by pquiring** [Microsoft/vscode#40721]
- VSCode Version: 1.19.1
- OS Version: Win10 1709

Steps to Reproduce:

1. Load certain .csproj files
2. Get following error message:

OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
The "GetReferenceNearestTargetFrameworkTask" task was not found.
Check the following:
1.) The name of the task in the project file is the same as the name of the task class.
2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface.
3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin" directory.

Reproduces without extensions: No (OmniSharp is an extension)

This problem only happens with certain projects.  When it happens OmniSharp doesn't run.  I've tried many solns posted on stackoverflow such as make sure .Net 1.x is installed ,etc. 
Problem is somewhat erratic, hard to find cause.

**Comment by pquiring** [comment]
Seems to happen to projects that reference another project.  Standalone projects seem to work fine.

**Comment by pquiring** [comment]
Has to do with having Visual Studio installed.  Output shows both are installed and OmniSharp picks VisualStudio instead of .NET Core.  
How do I tell OmniSharp NOT to use Visual Studio?
I have to uninstall Visual Studio to fix this issue.

**Comment by pquiring** [comment]
Here is sample output:
OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.5.27130.2010 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\User\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"

**Comment by pquiring** [comment]
This is actually an OmniSharp bug so I've opened a bug there:

https://github.com/OmniSharp/omnisharp-vscode/issues/1941

**Comment by dbaeumer** [comment]
@pquiring thanks. Closing then.
