### ISSUE TITLE
Format Typescript info on symbol/error hover

### ISSUE THREAD

**Issue by andersekdahl** [Microsoft/vscode#4072]
We use type aliases in our code instead of classes and interfaces. For larger types it becomes almost impossible to make any sense of the text that Typescript outputs because it can be more lines than what fits on a small screen.

It would be more than awesome if the text displayed on hover would be parsed and formatted. Perhaps collapse large types and make it possible to expand them by clicking on them?

**Comment by mjbvz** [comment]
This is something that the TypeScript team is currently investigating: https://github.com/Microsoft/TypeScript/issues/14662

Closing as upstream
