### ISSUE TITLE
Installing Power shell extension as a VSIX when offline is not working

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#40722]
- Install the Power shell vsix from here (https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)
- Go offline
- Install above downloaded vsix 

Expected: Should be installed and seen in the installed extensions after reload
Observed: It shows installed successfully, but not shown in installed extensions after reload, and also not running in the system

**Comment by sandy081** [comment]
Looks like the above extension has dependencies. In offline mode it is failing to get and install dependencies from market place. But, if the dependencies are already installed it should not go to market place. 

Fix is not to go to market place when dependencies are all installed.

**Comment by Manzoor-TUC** [comment]
@sandy081 : I am having the same issue 'Not able to install the PowerShell Extension in VS code offline'. I went through all the comments and performed the above mentioned steps, but still not able to install it.
VS code Version: Windows 7, x64, 1.19.3
Powershell Extension: ms-vscode.PowerShell-1.5.1.vsix
Can you please help me with this?

Thank you.

**Comment by sandy081** [comment]
@Manzoor-TUC May I know which version of VS Code are you using?

**Comment by gdmyghacc** [comment]
There's currently a problem installing the PowerShell extension version 1.5.1 on VSCode 1.19.x as per https://blogs.technet.microsoft.com/pstips/2018/01/14/using-vscode-and-the-powershell-extension-in-an-offline-environment/ - have you tried extracting the contents of vsix manually? Please try the method described in that post.

**Comment by Manzoor-TUC** [comment]
@sandy081 I am using VS code 1.19.3.
Previous I tried with VS code version 1.18.1 , but I was still not able to install the extension.

**Comment by Manzoor-TUC** [comment]
@gdmyghacc: I read this page already and tried with the steps mentioned for version '1.19.3' but still no luck.
