### ISSUE TITLE
A directory with modified content, untracked content throws error unable to open file is a directory in git

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40727]
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: MacOS Sierra 10.12.6

A directory with modified content, untracked content throws error unable to open file is a directory in git

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/2301847/34306541-fe71e1f0-e700-11e7-9b25-652789168529.png)

![image](https://user-images.githubusercontent.com/2301847/34306571-24425fc2-e701-11e7-8714-b9f512772415.png)

What is the correct behavior in this scenario?

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
@joshunger Is this a submodule?

**Comment by joshunger** [comment]
@joaomoreno I think Visual Studio thought it was a submodule, incorrectly

**Comment by joaomoreno** [comment]
Are you sure? Git ignores directories. Unless they are submodules. What does `git submodule` return?

**Comment by joshunger** [comment]
I'll work on a repro for you.

**Comment by joshunger** [comment]
@joaomoreno I'm working on repro steps but how do I re-open?

**Comment by joaomoreno** [comment]
Done! 👍

**Comment by joaomoreno** [comment]
Once more.

**Comment by joshunger** [comment]
@joaomoreno hah thanks going to have time next week

**Comment by Deviad** [comment]
Same issue here.

**Comment by Deviad** [comment]
Same issue here:
Version 1.20.0-insider (1.20.0-insider)

```
Extension | Author (truncated) | Version
-- | -- | --
ng-template | Ang | 0.1.9
react-native-react-redux | EQu | 1.4.1
EditorConfig | Edi | 0.12.0
gitflow4code | Gre | 1.0.0
crane | Hvy | 0.3.8
Angular-BeastCode | Mik | 5.2.9
material-icon-theme | PKi | 3.2.2
code-settings-sync | Sha | 2.8.7
html-css-class-completion | Zig | 1.16.1
vscode-color | ans | 0.4.5
color-info | bie | 0.5.0
markdown-preview-github-styles | bie | 0.1.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
jsrefactor | cms | 2.11.4
vscode-eslint | dba | 1.4.5
gitlens | eam | 7.5.10
tslint | eg2 | 1.0.24
vscode-npm-script | eg2 | 0.3.3
prettier-vscode | esb | 1.1.2
php-debug | fel | 1.12.1
githd | hui | 1.1.1
rest-client | hum | 0.17.0
check-npm-updates | iak | 1.3.0
phpcs | ika | 0.7.0
relativepathrefactor | jak | 0.9.0
Angular2 | joh | 2.12.0
intellij-idea-keybindings | k-- | 0.2.19
refactorix | kri | 0.3.6
vscode-language-babel | mgm | 0.0.12
postcss-language | mhm | 2.0.3
vscode-scss | mrm | 0.6.2
debugger-for-chrome | msj | 4.1.0
color-highlight | nau | 2.3.0
rxjs-snippets | pko | 0.0.2
typescript-hero | rbb | 2.1.1
sass-indented | rob | 1.4.6
stylelint | shi | 0.32.0
javascript-typescript | sou | 0.0.5
autoimport | ste | 1.5.3
vscode-react-native | vsm | 0.5.7
vsc-angular-cli | web | 1.0.0
```

**Comment by joshunger** [comment]
@Deviad can you please post repro steps?

**Comment by Deviad** [comment]
@joshunger just right click on a file or use ctrl + shift + p and then select compare file with revision.

**Comment by joaomoreno** [comment]
> compare file with revision

@deviad That is not a feature we ship with. That is very likely another extension. Please check which one it is and file an issue on them.
