### ISSUE TITLE
Separate section for "errors and warning" output

### ISSUE THREAD

**Issue by rogierlommers** [Microsoft/vscode#4073]
See screenshots below; I use VCS for Golang development and after saving a file, the output goes into the "Errors and Warnings" section. However this is ONLY visible in the status bar on the bottom of the editor. I would like the output to be visible in a separate section of the screen. Is this possible now? Or is there some kind of extension which does this?

I know I can use `COMMAND + SHIFT + M` to open it, but I would like to have it visible directly after saving my file.

[edit]
Kind of related: https://github.com/Microsoft/vscode/issues/1135

![screen shot 2016-03-12 at 19 02 45](https://cloud.githubusercontent.com/assets/3907131/13724459/c24dcbbe-e886-11e5-8641-96cb73e91b8f.png)

![screen shot 2016-03-12 at 19 02 59](https://cloud.githubusercontent.com/assets/3907131/13724457/a611e106-e886-11e5-9195-95be0d1fded9.png)

**Comment by bpasero** [comment]
@alexandrudima did you not start this?

**Comment by alexandrudima** [comment]
The Error List is in limbo.

It can be enabled with a hack I use every now and then: 
* Reveal Debug Console (`Ctrl+J` on Windows)
* Open developer tools
* Go to Resources -> Local Storage
* Find the key containing the folder + `workbench.panelpart.activepanelid`.
* Edit from `workbench.panel.repl` to `workbench.panel.errorList`.
* Reload window.

Works until the Debug Console is shown again.

**Comment by bpasero** [comment]
@alexandrudima cool, I think this is a good start to demo for UX to get an idea, adding the label.

**Comment by bpasero** [comment]
Closing, we have problems panel for a while now.
