### ISSUE TITLE
SelectBox Custom, List: Low contrast for foreground, hover colors in Light themes

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40731]
Light themes have relatively low contrast for foreground and hover colors.
ideally we do not need to create a new color.  Either we can tweak the default list colors
which are used for quick pick , SelectBox, Explorer et cetera.

Light Default:

![image](https://user-images.githubusercontent.com/25272315/34310264-7c41dffe-e724-11e7-90de-d4083eb71917.png)

Bad Hover contrast:

![image](https://user-images.githubusercontent.com/25272315/34310295-b335924e-e724-11e7-98ef-b260d4da6122.png)

I suggest we increase the contrast for the default listHoverBackground applicable to all users.

For the foreground color we could make this slightly darker again for the default.

I don't see why we would create new colors either, I think whatever is good for selectBox should be the same and good for the quick pick

Tagging this "under discussion" hopefully that is correct.

**Comment by cleidigh** [comment]
@weinand 
@bpasero 

I finally figured out the listFocusForeground has no default, it's inherited from Monaco-shell.
If we define it and listFocusHover in light-defaults we won't create any other colors.

Below light+ with foreground, hover darkened:
foreground  ===  #454545 originally #6c6c6c
hover  ===  #e8e8e8

![image](https://user-images.githubusercontent.com/25272315/34314596-1de10934-e743-11e7-8b44-154d88c44021.png)

**Comment by bpasero** [comment]
@cleidigh can you make a PR for me to try out your suggested color change?
