### ISSUE TITLE
Extensions that use schemastore.org make requests over HTTP (not HTTPS)

### ISSUE THREAD

**Issue by tonyc** [Microsoft/vscode#40736]
I noticed that the javascript and typescript extensions both make requests to schemastore.org port 80. I realize this isn't the most sensitive piece of data, but as a security-aware user, I would prefer external HTTP requests to actually be HTTPS :)

Doing a little research, I came across SchemaStore/schemastore#12 which involved some discussion about making secure requests for these files.

I've got a commit handy that changes the URLs to use the pattern, which allows Code to make these requests over HTTPS.

- VSCode Version: 1.19.1
- OS Version: All

Steps to Reproduce:

1. Install a network monitor tool (e.g. Little Snitch on MacOS)
2. Launch VS Code
3. After a few moments, the network monitor will report a request to schemastore.org:80

![image](https://user-images.githubusercontent.com/10182/34315168-0bf7121e-e742-11e7-8951-eb2cefd2d85d.png)

Reproduces without extensions: No

**Comment by mjbvz** [comment]
Fixed by #40737

**Comment by tonyc** [comment]
Thank you!!! ❤️

**Comment by bpasero** [comment]
@mjbvz there is no steps to verify so I did a code review and verified that we no longer use HTTP URLs.
