### ISSUE TITLE
Synchronise dirty editor buffers across windows

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#40739]
- VSCode Version: 1.19.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open the current active file in a new windows (e.g., CTRL-K O)
2. In either windows modify the file.  In the current window the the editor tab will show the file has been modified, but the other open window does not indicate as such.  

Note: When the file is saved the other window does pick up the changes.

**Comment by shobhitchittora** [comment]
@bpasero Any code pointers for this? Would like to take this up.😇

**Comment by bpasero** [comment]
@shobhitchittora I think this would be a too large area for a PR to accept, sorry. Issues where we expect help are labeled "help wanted", see https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
