### ISSUE TITLE
Python `pass` keyword outdent

### ISSUE THREAD

**Issue by pythoncoder01** [Microsoft/vscode#40733]
- VSCode Version: 1.19.1
- OS Version: MacOS 10.13

Steps to Reproduce:

1. Install python.
2. Type pass in a block of code.

It would be more useful if it automatically removed one level of indentation after pressing the ENTER key, since there can't be anything in the statement other than `pass`.

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Please file this issue against the Python extension.
