### ISSUE TITLE
File does not exist. "undefined" when trying to debug

### ISSUE THREAD

**Issue by juanmas07** [Microsoft/vscode#40730]
- VSCode Version: 1.19.1
- OS Version: macOS 10.13.1 (17B1003)

<img width="1078" alt="screen shot 2017-12-22 at 16 02 48" src="https://user-images.githubusercontent.com/2141907/34309637-c76fa698-e731-11e7-9d80-1efb194cb1ff.png">

`{
    "name": "Python",
    "type": "python",
    "pythonPath":"${config:python.pythonPath}",
    "request": "launch",
    "stopOnEntry": true,
    "console": "none",
    "program": "${workspaceFolder}/merger.py",
    "cwd": "${workspaceFolder}",
    "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
    ],
    "env": {"name":"value"},
    "args": "asd asd",

}`

From python configuration:

..."python.pythonPath": "python",..

So I'm not able to run the debugger.

**Comment by juanmas07** [comment]
is it caused by an extension? seems like debuguer is included in vs code

**Comment by isidorn** [comment]
No, python is not part of vscode. Please file this against the python extension. Thanks
