### ISSUE TITLE
SelectBox Custom, List: Monokai Dimmed uses the same color for listSelection, listHover

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#40732]
All other themes have some contrast between selection and hover colors.  

Unfortunately I cannot quote images by voice, hence the full screen shots...

Current Monokai Dimmed: (selection is first, mouse is hovered over second entry - screen lacks mouse)

![image](https://user-images.githubusercontent.com/25272315/34310554-22644c4a-e726-11e7-9a5a-1cce58d37010.png)

Current Molokai - Hover it's dark but completely different from selection color:

![image](https://user-images.githubusercontent.com/25272315/34310600-6bcc9504-e726-11e7-82bf-526e469e070b.png)

**Comment by cleidigh** [comment]
Current listSelection and listHover color:  #707070
Suggested Alpha tweak for listHover : #70707065
This does not conflict with other list colors.

Mouse Hover on second entry:

![image](https://user-images.githubusercontent.com/25272315/34311713-2302ce54-e72d-11e7-8ee9-c2dc02d5014a.png)

Mouse over cmd set.txt

![image](https://user-images.githubusercontent.com/25272315/34311742-639d5c2c-e72d-11e7-8026-0454c74ec4d1.png)

**Comment by Tyriar** [comment]
The color proposal seems fine to me, prefer the solid `#444444` though to reduce the amount of work the compositor needs to do.

**Comment by cleidigh** [comment]
@Tyriar 
Thanks for chiming in, and I learned a new term , compositor  - do you have any references
that give a picture describing why #444444 is faster than #454545.  I could not find something
concerning this.  It would be great to understand for future color choices.

**Comment by bpasero** [comment]
@cleidigh feel free to tweak via a PR and I will review.

**Comment by cleidigh** [comment]
Fixed With: #40914
