### ISSUE TITLE
visual code not return python result

### ISSUE THREAD

**Issue by zezto** [Microsoft/vscode#40738]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
Not able to get the statement I want to print 

---

Steps to Reproduce:

1.Open file and enter print(2+4)
2. when press run in terminal it returns nothing it comes back blank 

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
This is likely due to a command provided by the Python extension, if so please file an issue at https://github.com/Microsoft/vscode-python
