### ISSUE TITLE
The ''Format document" context menu item contradicts  Eslint rules

### ISSUE THREAD

**Issue by Ofer-Gal** [Microsoft/vscode#40735]
- VSCode Version: 1.19.1  64 bit
- OS Version: windows 10

Steps to Reproduce:
1. Right click and choose "Format document"
2. Eslint complains there should be a space between the function name and the parenthesis.

Reproduces without extensions: No ESLint is an extention.

**Comment by weinand** [comment]
Please file this against the ESlint extension.

**Comment by Ofer-Gal** [comment]
I see in https://github.com/Microsoft/vscode-eslint/issues/103 that ESlint does not provide formatting.
I want to tell VSCode to format using the ESLintrc rules.
Is it not possible?
