### ISSUE TITLE
Code Deleted All Of My Ffiles!

### ISSUE THREAD

**Issue by uloga** [Microsoft/vscode#40748]
By clicking on folder in code editor, all of it's files have disappeared and the files are nowhere to be found!  I've googled it and found that most user are experience the same issue. I'm using mac sierra.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
@uloga can you recap with more details what you did? maybe attach a screenshot what you did and what happened? did you use Git?

**Comment by uloga** [comment]
I cannot add screenshot, everything is gone. Screenshot from what? Editor? I opened the code editor as usual. In file explorer I've clicked on the project folder, opened src folder, after opening different project folder, the files of the previous opened project disappeared and are nowhere to be found.

**Comment by uloga** [comment]
I'm using git but haven't used git just opened the code and everything I mentioned above happened within 3 clicks.

**Comment by bpasero** [comment]
@uloga are you sure the files are gone from disk? maybe Code is just not showing them for some reason. Also, what OS is this?

**Comment by uloga** [comment]
The files are gone! Mac Sierra.

**Comment by uloga** [comment]
Same issue as reported here. 
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b32e47a9-d86c-473a-9449-a7f5c202463c/visual-studio-code-just-deleted-all-my-files?forum=visualstudiogeneral

**Comment by bpasero** [comment]
@uloga hence my question if you are using git, that link you refer to is from a user that was invoking an action to undo all outgoing changes:

![before](https://user-images.githubusercontent.com/900690/34318240-753541de-e7c3-11e7-8929-a425e1e77da4.gif)

**Comment by uloga** [comment]
I'm using git as command line tool, but I've disabled it in @bpasero code because of known bugs.

**Comment by bpasero** [comment]
Could it be that you accidentally moved a folder from one to another via drag and drop from the VS Code file explorer?

**Comment by uloga** [comment]
I don't know if it has anything to do with that - that I'm using windows at my office and macos at home. I'll try to reproduce this issue. @bpasero thanks for taking time and trying to help out.

**Comment by bpasero** [comment]
> that I'm using windows at my office and macos at home

Is it that you synchronise files on disk between these 2 machines that could have an impact on some files suddenly disappearing from the macOS machine?

**Comment by uloga** [comment]
@bpasero could be.

**Comment by uloga** [comment]
I'm still trying to reproduce this issue. I've created a new typescript project from scratch where I'm using webpack to compile everything into a ./dist/bundle.js  Weird thing is that the bundle.js is accessible via browser but my dist folder is empty in vscode and finder. I'm using yarn instead of npm btw.
