### ISSUE TITLE
There is no suitable font size

### ISSUE THREAD

**Issue by Totoross** [Microsoft/vscode#40747]
- VSCode Version: 1.19.1
- OS Version: win10

Steps to Reproduce:

1.There is no suitable font size

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
I do not understand your problem. Please explain.

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
