### ISSUE TITLE
Can not save as utf8 

### ISSUE THREAD

**Issue by Yensan** [Microsoft/vscode#40743]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601

Can not save as utf8. **This is a new issue in 1.19.** 

Steps to Reproduce:

1. creat a file--------- appearance: utf8 is auto slected by VScode.
2. edit some characters beyond latin-1, such as Asian words, save ------- appearance:  turn to mess code
3. reopen as Windows OS default encode 'GB 2312', --------- appearance: all words well
conclusion: can open with many decode, but can not save with encode.

**Comment by bpasero** [comment]
@Yensan not sure I can follow, can you share a screencast what happens?

**Comment by hua03** [comment]
I guess you turned on this feature `files.autoGuessEncoding`. When the Chinese in the file is too small, VSCode can not guess the character set correctly

**Comment by Yensan** [comment]
Merry Christmas for all of you !!! :gift: 
@bpasero  In this office I could not transfer graphic info, I wiil cut a screenshot for you latter.
@hua03 I guessed you are right. So I set  `"files.autoGuessEncoding": false` But, it turns out, Not at all, man.

**Comment by Yensan** [comment]
@bpasero 
can you tell me, how to shot a video such as [VScode](https://code.visualstudio.com/docs/editor/codebasics) used in this Doc? maybe this will give you more info to track

**Comment by Yensan** [comment]
@bpasero Hi, I can't follow now, too.
So I close this issuse. If it reappear in future, I will reopen for you and give you more info.

**Comment by Yensan** [comment]
This issue show up again. But I don't know to  to reproduce.

**Comment by Yensan** [comment]
> {
> 	"folders": [
> 		{
> 			"path": "LinuxAndC-master"
> 		},
> 		{
> 			"path": "intlij_pro"
> 		}
> 	],
> 	"settings": {
> 		"git.enabled": false, // 如果你不用git，我建议你关闭它
> 		"typescript.check.npmIsInstalled": false,
> 		"workbench.colorTheme": "One Dark Pro", // 主题 Vivid
> 		"workbench.iconTheme": "vs-seti", // icon
> 		"workbench.colorCustomizations": {"editorCursor.foreground": "#ffffff"},
> 		"editor.tokenColorCustomizations":{"comments":"#688c9c"  ,"functions": "#52ADF2"}, //定制颜色
> 		"files.trimTrailingWhitespace": true, // 保存时，删除每一行末尾的空格
> 		"files.insertFinalNewline": true,
> 		// "files.trimFinalNewlines": true, // 启用后，保存文件时，文件末尾只有一个新行，多退少补
> 		// "files.autoGuessEncoding": false, // 启用时，会在打开文件时尝试猜测字符集编码
> 		// "files.encoding": "utf8",
> 		"files.exclude": {"**/.git": false,"**/.svn": true,"**/.hg": true,"**/CVS": true,"**/.DS_Store": true,
> 				"**/.md": true, "*.epub": true,"*.mobi": true }, //不显示某些类型的文件
> 		"editor.fontSize": 14, "editor.fontFamily": "Consolas, 微软雅黑, Menlo", // 控制编辑器字体
> 		"editor.minimap.enabled": false, // minimap，就是右边那个东西
> 		"editor.dragAndDrop": false, // 选中文字，可以拖动它们调整位置
> 		// C/C++ 的设置
> 		"C_Cpp.intelliSenseEngine": "Default",
> 		"C_Cpp.autocomplete": "Default",
> 		"C_Cpp.intelliSenseEngineFallback": "Disabled",
> 		"C_Cpp.errorSquiggles": "Disabled",
> 		"[cpp]": {"editor.quickSuggestions": true},
> 		"[c]": {"editor.quickSuggestions": true},
> 		"files.associations": {
> 		  "*.h": "c",
> 		  "*.i": "c",
> 		  "cstdio": "c",
> 		  "*.tcc": "c"
> 		},
> 		// java/python/others
> 		"java.errors.incompleteClasspath.severity":"ignore",
> 		"java.home":"C:/Program Files/Java/jdk1.8.0_131",
> 		"code-runner.executorMapByFileExtension": {
> 			".puml": "cd $workspaceRoot &&java -DGRAPHVIZ_DOT=\"C:/Program Files/graphviz/bin/dot.exe\"  -jar F:/Note/plantuml.jar $fullFileName"
> 		},
> 		"code-runner.executorMap": {
> 		  "python": "cd $workspaceRoot &set p=$dir&&set PYTHONPATH=%p:\"=%;$workspaceRoot&& C:/Python3632/python $fullFileName", // python 使用PATH默认py    C:/Python3632/python $fullFileName && endlocal
> 		  "java": "cd \"$workspaceRoot\" &del /q/s *.class & cd $dir & javac -d $workspaceRoot/out -encoding utf-8 $fileName && cd $workspaceRoot/out/ && java $fileNameWithoutExt",
> 		  "c": "cd $workspaceRoot && $workspaceRoot/out/$fileNameWithoutExt.out",
> 		  "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
> 		  "kotlin": "cd $dir && C:/kotlinc/bin/kotlinc $fileNameWithoutExt.kt -include-runtime -d $fileNameWithoutExt.jar && java -jar $fileNameWithoutExt.jar"
> 		},
> 		"code-runner.saveFileBeforeRun": true,
> 		"code-runner.preserveFocus": false,
> 		"code-runner.clearPreviousOutput": true,
> 		"code-runner.fileDirectoryAsCwd":false,
> 		"code-runner.runInTerminal": true,
> 		"code-runner.showRunIconInEditorTitleMenu": false,
> 		"code-runner.customCommand": "echo Hello",
> 	}
> }
>

**Comment by Yensan** [comment]
@bpasero  Hi, Pasero, maybe I catch it. 
Steps to Reproduce:
1. install redhat  java plugin (I'm not sure this is redhat's issue, but ask you to trace and comfirm)
2. creat `Test.java` file 
--------- appearance: utf8 is auto slected by VScode.
3. Edit this file as normal java class. Hello world thing is not enough. More complexity within classes is better. 
--------- appearance: utf8, ASCII is well.
4. edit some characters beyond latin-1, such as Asian words, (insert by keybord and paste by other file ) save
 ------- appearance: utf8, ASCII is well, Asian words turn to mess code
5. reopen as Windows OS default encode 'GB 2312', 
--------- appearance: GB 2312, all words well


- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
java|red|0.16.0

**Comment by bpasero** [comment]
@Yensan can you share your settings?

**Comment by Yensan** [comment]
already pasted above ...

**Comment by bpasero** [comment]
@Yensan can you tell me what exact chinese characters you type or paste into the editor so that I can reproduce?

**Comment by Yensan** [comment]
@bpasero Pasero, I must say, not.  :laughing:  Because every chinese characters will be mess, Any!!! But, are you use Windows VScode and java plugin? I found this issue in office's Windows. but I have not encountered this issue in myself Mac air. And when I turn off java plugin, every character is OK.
If you need some chinese character: 
-  Insert --- Maybe you have install a chinese input software:  https://pinyin.sogou.com/    OR  search `输入法` in baidu.com and find your favorite one.
-  paste --- In my case, when I turn on redhat's java plugin, insert chinese by input software with keybord OR paste by ctrl c   ctrl v   all cause this issue.  If you need, there is a large amount of chinese character in my github, and you will be satisfied. :rofl:  https://github.com/Yensan/LinuxAndC/blob/master/90_Design_Pattern_2.md
- With java. Paste for you

ONLY ASCII
```java
public class CharacterTest{
    Ascii ascii;
    public void test() {
        System.out.println("");
    }
}
```

With Chinese character
```java
public class CharacterTest{ // in comment 注释会乱码呀~~~
    Ascii ascii;
    public void test() {
        System.out.println("字符串也要乱码~~~66666");
    }
}
```

**Comment by bpasero** [comment]
@Yensan just to make sure, you can clearly NOT reproduce this when the Java extension is disabled?

**Comment by Yensan** [comment]
I am annoyed by this issue so I test it again, then tell you:
clearly **NOT** reproduce this when the Java extension is disabled
So, if you want to reproduce, `Win + VScode + redhat java plugin`

**Comment by bpasero** [comment]
@Yensan can you then please report this issue to the Java extension here: https://github.com/redhat-developer/vscode-java/issues

**Comment by Yensan** [comment]
Sure. https://github.com/redhat-developer/vscode-java/issues/405

**Comment by Yensan** [comment]
#https://github.com/redhat-developer/vscode-java/issues/394

**Comment by bpasero** [comment]
Thanks, closing this one then.
