### ISSUE TITLE
unable to gitignore .vscode/settings.json

### ISSUE THREAD

**Issue by peonmodel** [Microsoft/vscode#40742]
- VSCode Version: 1.19.1
- OS Version: High Sierra

Steps to Reproduce:

1. added .vscode/ to .gitignore
2. unsure

Reproduces without extensions: Yes

<img width="535" alt="bug" src="https://user-images.githubusercontent.com/12645203/34316590-907394da-e7d4-11e7-8c28-c618a8ae77fa.png">

as seen in the image, despite adding `.vscode/settings.json` and `.vscode/` in the gitignore file
the file still shows up in source control for git
adding it in `.git/info/exclude` doesnt make a difference

other files in `.vscode/` directory is ignored, except for `.vscode/settings.json`

the settings.json file is previously mistakenly commited to the remote repo, but that has been corrected

problem does not occur for other local repo, the `.vscode/` in .gitignore works fine

other things i also tried, 
1) uninstall VSC and reinstall it, 
2) gitignore ONLY `.vscode/` or `.vscode/settings.json`
3) `git clean -d -x -f`

user settings
```json
{
  "editor.fontSize": 10,
	"editor.tabSize": 2,
	"editor.insertSpaces": false,
	"editor.minimap.enabled": false,
	"window.zoomLevel": 0,
	"git.autofetch": true
}
```
workspace settings
```json
{
	"search.exclude": {
    "**/.meteor/local": true
  },
  "files.useExperimentalFileWatcher": true,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/.meteor/local": true
  }
}
```

**Comment by ddwwcruz** [comment]
have you committed . vscode/settings.json previously? if so you might have to commit that you've deleted the file so git stops tracking it

**Comment by peonmodel** [comment]
i just committed the file, pulled, resolve merge conflicts and push to remote but problem still exist

**Comment by ddwwcruz** [comment]
hmmm... can you try using a different git client like gitkraken? does the error also happen there? if it does this might be a git problem instead of a vscode problem.

**Comment by peonmodel** [comment]
it seems to be a git issue
```
user:folder user$ git check-ignore -v ./secretnotes.md 
.gitignore:4:secretnotes.md	./secretnotes.md
user:folder user$ git check-ignore -v README.md 
user:folder user$ git check-ignore -v .vscode/settings.json
user:folder user$ git check-ignore -v .vscode/
user:folder user$ git check-ignore -v imports/
user:folder user$ git check-ignore -v imports/lib
.gitignore:5:imports/lib/	imports/lib
```

my .gitignore file
```
node_modules/
.vscode/
settings.json
secretnotes.md
imports/lib/
public/fonts/
```

**Comment by peonmodel** [comment]
fixed, somehow the cached wasnt cleared

this fixed it
```
git rm --cached .vscode/settings.json
```
