### ISSUE TITLE
arrowkeys conflict with page up and page down keys

### ISSUE THREAD

**Issue by abhimhasagar** [Microsoft/vscode#40746]
my windows laptop dont have the numberpad, the arrowkeys are the same As page up/page down/home/end button, so when press the arrow keys to move forward its goes end of the page, its happen hell out of time. same things i tested on atom, brackets but its working properly

- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.1.0
php-pack|fel|1.0.1
angular-essentials|joh|0.3.2
Angular2|joh|2.11.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|5.1.14
debugger-for-chrome|msj|4.0.0
angular2-inline|nat|0.0.17

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
Did you try to change the keybindings?

**Comment by weinand** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please refer to our guidelines for filing issues. Thank you for your contributions.
