### ISSUE TITLE
Autocomplete config jsonc files with trailing comma

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40753]
The same way Edit🖊 button in `settings.json` does and autocomplete in the middle of object or array.
```javascript
{
  zoomlevel|
}
```
1. Trigger suggest
2. Accept suggestion
3. No trailing comma

- [x] settings: Edit button: first level of nesting
- [ ] settings: Edit button: other levels of nested objects or arrays
- [ ] settings: end of object or array
- [ ] keybindings ~~
- [ ] user snippets ~~

**Comment by aeschli** [comment]
I'm not convinced. We are tolerating trailing commas, but we should not encourage them.

**Comment by usernamehw** [comment]
I'm gonna close this in favor of auto-fix https://github.com/Microsoft/vscode/issues/42232
