### ISSUE TITLE
Starting a task using vscode's extension development API

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#40758]
Hello everyone,

How can I start a `vscode.Task` using vscode's extension api? I am using `vscode.executeCommand("workbench.action.tasks.runTask", "Task Name")` but this is both hacky and makes it impossible to track the task. I am looking for something equivalent to `startDebugging(folder: WorkspaceFolder | undefined, nameOrConfiguration: string | DebugConfiguration): Thenable<boolean>` for tasks.

Sorry for asking this question here but I could not find an answer anywhere else and it seems unlikely that it's not possible. Thanks!

**Comment by Gruntfuggly** [comment]
Don't think it's possible - I'd love it to be implemented though.

**Comment by g-arjones** [comment]
@dbaeumer Would you confirm this, please?

**Comment by dbaeumer** [comment]
This is correct. There is currently no API to start a tasks from an extension.

**Comment by EricJizbaMSFT** [comment]
@dbaeumer this is being solved by https://github.com/Microsoft/vscode/issues/45664 correct?  I would also like this support, but only found this issue originally and didn't realize it was being worked on - posting for the sake of others

**Comment by dbaeumer** [comment]
@EricJizbaMSFT yes. Closing as dup of #45664. The API is in proposed state for the next release.
