### ISSUE TITLE
Can't take screenshots of linter tooltips

### ISSUE THREAD

**Issue by brunolemos** [Microsoft/vscode#40755]
Just a little annoyance, but currently it doesn't seem  to be possible to screenshot linter tooltips because if you press `Shift` it closes itself. _The screenshot shortcut is `Shift+Cmd+4`._

Use case: Reporting some typing errors to a repo and trying to include screenshots.-->

<!--![vscode-screenshot](https://user-images.githubusercontent.com/619186/34319917-d3e5fd48-e7d4-11e7-990d-8d51d10eebd3.gif)

Version 1.20.0-insider

**Comment by brunolemos** [comment]
Workaround: [Add screenshot button to touchbar](https://9to5mac.com/2017/02/23/how-to-take-screenshot-touch-bar-macos-mac-101/)

**Comment by weinand** [comment]
Just take a timed screenshot.

**Comment by brunolemos** [comment]
k
