### ISSUE TITLE
C# Code coloring glitches after method that returns Task of tuple

### ISSUE THREAD

**Issue by ahmadalli** [Microsoft/vscode#40754]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.5.0
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. Have a c# code with a method that returns task of a tuple.
2. this happens (take a look at the coloring of lines 73 to 98):

![image](https://user-images.githubusercontent.com/2167301/34319878-f05904e8-e801-11e7-9d2b-49b208a3c53d.png)

Reproduces without extensions: Yes (the image above is taken with `--disable-extensions` flag)

**Comment by weinand** [comment]
Please file C# issues against the C# extension.

**Comment by ahmadalli** [comment]
I disabled c# extension. this is just code doloring

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#97
