### ISSUE TITLE
Instant resource overuse problem, typing will be very caton

### ISSUE THREAD

**Issue by zhangzhengyi12** [Microsoft/vscode#40756]
Used in version 1.19.1 webpack dev server function occurs, crazy inform browser automatically refresh, lead to take up too much resources, typing in the editor is very card, I am not very clear this is vscode webpack or problems.In that instant browser and vscode CPU usage is very high, using translation software thank you

**Comment by zhangzhengyi12** [comment]
It doesn't look like he's related to webpack, and I'm still having this problem in some parts of the editing file after I've disabled webpack.

**Comment by weinand** [comment]
Does the problem persists after restarting VS Code?
Can you repro the problem when running `code --disable-extensions`?

**Comment by weinand** [comment]
need
