### ISSUE TITLE
only files and search bar is showing on the Activity Bar

### ISSUE THREAD

**Issue by ni7in** [Microsoft/vscode#40759]
- VSCode Version: 1.19.1
- OS Version: win-64 bit

Steps to Reproduce:

1. Just installed an extension **Auto rename HTML tag**,
2. After reloading I found that the debugging, git and extension tabs have vanished 
3. Restarted after disabling all the extensions even installed vs code again but they didn't appear.
This is strange idk what to do

Reproduces without extensions: Yes
![capture](https://user-images.githubusercontent.com/25779687/34321522-fa5d6724-e836-11e7-8044-ff2e197d6901.PNG)

**Comment by usernamehw** [comment]
A duplicate of https://github.com/Microsoft/vscode/issues/40531 ?

**Comment by ni7in** [comment]
FIXED!! thx for referencing
