### ISSUE TITLE
Feature Suggestion: Add copy file option

### ISSUE THREAD

**Issue by dianagastrin** [Microsoft/vscode#40751]
Feature Suggestion

- VSCode Version: 1.18.1
- OS Version: windows 10 pro

Can you add "Copy File" option, for actually copying the file as you do in the FS?

I think this is the right place to put it in (under copy path) : https://i.imgur.com/ujaURF6.png

Thanks!

**Comment by isidorn** [comment]
Thanks for the suggestion, however we already have a copy option in the File Explorer (on the left).
And in the tabs we do not put fs operations. Thus closing as designed

**Comment by isidorn** [comment]
I think there is already an open issue about copy file across window - you can search it in our repo.
@bpasero might you know the issue number for this

Still this should not be in the tab menu but the explorer action should just work across windows

**Comment by dianagastrin** [comment]
Found the issue:
Paste files across windows #27837

Cool, Thanks!
