### ISSUE TITLE
(low priority) Ruby syntax highlighting issue for regex literals with ! - or + operators

### ISSUE THREAD

**Issue by jeff-hykin** [Microsoft/vscode#40769]
- VSCode Version: 1.19
- OS Version: macOS 10.12.6
- tested with extensions disabled

Steps to Reproduce:
```
audience = "world"
thing = ! /hello #{audience}/
puts thing 
#>>> true 
```

The syntax highlighting for `/hello #{audience}/` is screwed up. The problem also exists if the - or + operators are used, however the ~ operator has the correct highlighting.<br>
### Solution:
This is a pretty small problem, so mentioning this in the ruby.tmLanguage.json is probably sufficient.<br>
I'm somewhat familiar with language files so I might be able to add a fix and create a pull request in the next few weeks.

**Comment by aeschli** [comment]
This issue was moved to textmate/ruby.tmbundle#115

**Comment by aeschli** [comment]
@jeff-hykin A PR against textmate/ruby.tmbundle#115 would be fantastic!
