### ISSUE TITLE
Why you don't put all user defined things to an independent place ???

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode#40768]
Install x64 version, ask uninstall x86 at first, which result lost all setting/snippet .
Why you don't put all user defined things to an independent place ???
Uninstall doesn't mention buckup or export , that's really really bad .

Now I have to recollect my snippet and write settings.

**Comment by weinand** [comment]
We are very sorry that you've lost your settings but we doubt that VS Code is culprit. As stated in our release notes VS Code preserves all user data when upgrading from 32 to 64 bit:
https://code.visualstudio.com/updates/v1_15#_windows-64-bit

- Could it be that you accidentally installed the Insiders version when upgrading? The Insiders version does store its settings in a different place as Stable.
- Could it be that you have a tool installed that automatically clears settings after installing a program?

**Comment by eromoe** [comment]
1. nope,  I download vscode x64 from  https://code.visualstudio.com/Download
2. nope,  x64 installation tell me to uninstall first, then I goto my vscode folder ,  execute `unins000.exe` to uninstall . Then  install x64 to same folder.

**Comment by weinand** [comment]
I do not understand what you mean by "vscode folder". If you mean the place where VS Code is installed, you should not really have to deal with that location.

The correct way to uninstall a program on Windows is through the "Programs and Features" control panel:

![2017-12-24_14-44-31](https://user-images.githubusercontent.com/1898161/34327019-2fbf9a1c-e8ba-11e7-8279-68b6cf35d4d8.png)

And the VS Code Installer will install VS Code into the correct location too.

VS Code does **not** store user data in that location.
Instead it uses the location `%APPDATA%\Code\User\settings.json` (which is under `AppData/Roaming` on my System):

![2017-12-24_14-50-02](https://user-images.githubusercontent.com/1898161/34327012-12d7c6d6-e8ba-11e7-9f62-72ec8d2db723.png)

Even the Snippets are stored there.

(for details see https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)

This location is the same for 32 bit and 64 bit versions of VS Code. So upgrading does not affect that location in any way and it does not delete that data either.

**Comment by weinand** [comment]
I think your question "Why you don't put all user defined things to an independent place ???" is sufficiently answered now:
We do store user data independently from the VS Code program.
