### ISSUE TITLE
Failed to import TextMate grammar

### ISSUE THREAD

**Issue by svanimpe** [Microsoft/vscode#40760]
- VSCode Version: 1.19.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. yo code
2. Select 'New Language Support'
3. Enter the path to the attached grammar (unzip it first of course).
4. Crash:

```
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. (Problems loading language definition file: ENOENT: no such file or directory, open '/Users/steven/Desktop/stencil.tmLanguage ')
    at constructor.emit (events.js:186:19)
    at Immediate._onImmediate (/usr/local/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/base.js:446:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
 ```

This grammar has been written using TextMate and works fine there.

[stencil.tmLanguage.zip](https://github.com/Microsoft/vscode/files/1584364/stencil.tmLanguage.zip)

**Comment by maxibanki** [comment]
Hi,

I tried to reproduce this, and I failed.
> ENOENT: no such file or directory, open '/Users/steven/Desktop/stencil.tmLanguage '
According to your logs, you put a space at the end of the filename at your path. Maybe Copy Paste failure.

Best regards

Max

**Comment by svanimpe** [comment]
To my embarrassment, that was indeed the problem.
It appears macOS adds a space when you copy/paste a path or drag in a file from Finder. I did not notice this at all. Thanks for noticing it!

**Comment by maxibanki** [comment]
Maybe we could add that spaces will be trimmed of the path.
