### ISSUE TITLE
Interpreter version selection error

### ISSUE THREAD

**Issue by Spacebody** [Microsoft/vscode#40765]
- VSCode Version: 1.19.1
- OS Version: MacOS 10.12.6

Steps to Reproduce:

if use such code on the python3 file:
```python
from abc import ABCMeta, abstractmethod

class class_name(metaclass=ABCMeta):
    def __init__(self):
        pass
```
when click run button at the top right corner, the running result goes syntax error:
 ```bash
  class class_name(metaclass=ABCMeta):
                              ^
SyntaxError: invalid syntax
```
even I have chosen the version 3.6.3 as interpreter.

Might be a bug?

Reproduces without extensions: Yes

**Comment by Spacebody** [comment]
I have test on terminal there is no syntax error on such code. Changing a computer also get such error.

**Comment by weinand** [comment]
Please file python issues or questions against the Python extension (or on Stackoverflow).

**Comment by Spacebody** [comment]
@weinand I doubt that VSCode cannot choose correct python version for running when click the button on the top right corner. The code can be used under py3 but not py2. It seems that VSCode choose python2 by default even setting python3 as default.

**Comment by Spacebody** [comment]
Or any other method to solve this problem? Thanks forward.

**Comment by weinand** [comment]
VS Code does not know anything about Python.
It is the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) that implements anything Python.

This repository is for VS Code. If you have a Python issue, please file the issue against the corresponding repository, e.g.:

![2017-12-24_15-01-42](https://user-images.githubusercontent.com/1898161/34327070-6fd5940c-e8bb-11e7-99ec-77d69c907022.png)

**Comment by Spacebody** [comment]
@weinand Okay, understand now. Thank you.
