### ISSUE TITLE
关于调试node子进程的问题

### ISSUE THREAD

**Issue by ruixinMRK** [Microsoft/vscode#40766]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
vscode-jasmine-es5|dee|1.0.1
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
path-autocomplete|ion|1.7.0
vscode-postcss-sorting|mrm|3.0.1
debugger-for-chrome|msj|4.0.0
better-less|rad|0.4.3
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7
stylelint|shi|0.31.0
JavaScriptSnippets|xab|1.5.0

---

Steps to Reproduce:

1.我在调试node子进程发现，child_process fork的子进程，无法进行调试，但是直接用node main运行则可以，是bug吗还是要安装插件

Reproduces without extensions: Yes/No

**Comment by yoyo837** [comment]
Hi, girl, please speak English to get more people involved in the discussion.

**Comment by weinand** [comment]
Bing translate:
I found in the process of debugging son son, child_process fork son process, unable to debug, but directly run with the node main can be a bug or you want to install the plug-in

**Comment by Spacebody** [comment]
@weinand I am Chinese,  I can help.
What he said is:
I found that when debugging the subroutine of node, the subroutine which child_process forks cannot be debugged, however, it can be directly ran be node main. Is there any bug or need of any extension?

Hope the translation will be helpful.

**Comment by Spacebody** [comment]
@weinand issue title is: The problem about debugging subroutine of node

**Comment by yoyo837** [comment]
@Spacebody good job, I am Chinese too, but my English is poor and I generally cannot translate this like you.

**Comment by ruixinMRK** [comment]
@Spacebody thank you

**Comment by weinand** [comment]
Thanks everybody! Even if your English is poor, please try to use a translator tool.
I had to use the bing translator and got basically the same translation.
But it makes my life easier if you use the translator.

**Comment by weinand** [comment]
please see: https://stackoverflow.com/questions/16840623/how-to-debug-node-js-child-forked-process
