### ISSUE TITLE
Language extension not working (The mode has failed while tokenizing the input)

### ISSUE THREAD

**Issue by svanimpe** [Microsoft/vscode#40761]
- VSCode Version: 1.91.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Create a new language extension using the attached tmLanguage file (I've also attached the extension itself.
2. Install it.
3. Create a .stencil file.
4. Enter for example `{{`.

This results in the following error:
```
ERR target of repeat operator is invalid: Error: target of repeat operator is invalid
    at createOnigScanner (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:1346:12)
    at RegExpSourceList.compile (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:1399:30)
    at BeginEndRule.compile (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:1554:45)
    at matchRule (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2240:28)
    at matchRuleOrInjections (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2256:23)
    at scanNext (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2346:17)
    at _tokenizeString (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2339:9)
    at Grammar._tokenize (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2107:25)
    at Grammar.tokenizeLine2 (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js:2077:22)
    at e.tokenize2 (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4447:652)
messageService.ts:126 The mode has failed while tokenizing the input.
```

Reproduces without extensions: No
This language grammar has been developed in TextMate and works perfectly there.

[stencil.tmLanguage.zip](https://github.com/Microsoft/vscode/files/1584462/stencil.tmLanguage.zip)
[stencil.zip](https://github.com/Microsoft/vscode/files/1584463/stencil.zip)

**Comment by u2berggeist** [comment]
I'm having a similar issue at the moment. I'm working on a language extension and when I try to debug it and open a script file of the language, I get this error, not quite sure why. It's my first time making a language extension, so it might be user error (on my part, can't speak for @svanimpe). 

- VS Code Version: 1.19.1
- OS Version: Windows 10

**Comment by svanimpe** [comment]
I'm not so sure this is a user error. I have tried other TextMate grammars as well. There may just be something missing in the documentation as not all TextMate grammars seem to be supported.

This one (linked in the documentation) does work:
https://raw.githubusercontent.com/textmate/ant.tmbundle/master/Syntaxes/Ant.tmLanguage
But this one doesn't:
https://raw.githubusercontent.com/textmate/swift.tmbundle/master/Syntaxes/Swift.tmLanguage

**Comment by u2berggeist** [comment]
Interesting. My issue also comes straight from the Yeoman extension generator, so there may be something wrong with the base code itself. I didn't tell Yeoman to base the language off of anything initially since the language I'm working with is very specialized (it's honestly closer to a settings file than anything else).

**Comment by u2berggeist** [comment]
So after some investigation, I've figured out the issue. The tmLanguage file had some invalid Regex expressions. Once I fixed those, I didn't have any issues and it worked fine. Found that out through tracking the error through the devloper tools' console.

**Comment by svanimpe** [comment]
@u2berggeist What exactly was invalid about the expressions? And can you tell me how exactly I can track the error (I am new to VS Code).

**Comment by u2berggeist** [comment]
In my particular case, I had a few characters that should have had a `\` put in front of them (`*`, `+`, and `/`). I was able to track down the issue via `Help>Toggle Developer's Tools` and looked at what errors were popping up in the console (circled in red in the screenshot). In my case, I also had an error that it directly pointed to the `language-configuration.json` file. That I just messed around with until it fixed itself, so I'm legit not sure what was wrong there. Then, I just Googled "The mode has failed while tokenizing the input" and found a few issue reports on Atom that pointed to a Regex failure. After that, I just went searching through for the issue and found a few mistakes I had made.

If you're looking into the `.tmLanguage` file, I'd recommend glancing through [this](http://www.apeth.com/nonblog/stories/textmatebundle.html) post. It explains the grammar format really well and points to some good Regex resources.

Hope this helps!

![image](https://user-images.githubusercontent.com/20801821/34489757-7dd1ac8e-efab-11e7-98d6-bc147a638c66.png)

**Comment by svanimpe** [comment]
@u2berggeist Thanks for the tip. All my regular expression work in TextMate so I didn't expect them to be invalid. After commenting out everything and adding them back in one by one, I found the culprit:

```
\b?-?(?:0|[1-9]\d*)(?:\.\d+)?\b
```

In particular, it is the first question mark (after `\b`) that is giving me issues. I've added this because I want a non-greedy version (a greedy version will consume the minus sign). I have found workarounds such as using `[\b]?` or using spaces instead, but I don't understand why this expression was invalid.

**Comment by u2berggeist** [comment]
I'm not sure why that's not working. I'm not a regex or tmLanguage expert by any means (I pretty much started doing it). I've run into a few issues myself where the regex (to my knowledge) is right and Rubular agrees, but VS Code doesn't.

**Comment by alexandrudima** [comment]
@u2berggeist You are spot on, thank you!

TextMate uses oniguruma as a regular expression library. For any editor to support TM grammars, and in order to be compatible, it must also use oniguruma or reimplement it bug-for-bug, feature-for-feature.

In VSCode we've chosen to reuse oniguruma for this part (usually we use JavaScript regexes), but for tokenization purposes we use oniguruma. Here is the version of oniguruma that we use --- it is the same one Atom uses --- as that project from Atom binds the C++ regex library to JavaScript we're using it too --- https://github.com/atom/node-oniguruma/tree/master/deps/onig

It might not be 100% the same version used in TextMate. 

In this case, the error comes from Oniguruma -- https://github.com/atom/node-oniguruma/blob/41bba013783364215a52a54c5c08f253cba9608c/deps/onig/regerror.c#L99 I, unfortunately, don't know why that happens, I can only speculate it is caused by a version difference;

**Comment by svanimpe** [comment]
@alexandrudima Perhaps this specific version of oniguruma does not support `?` after `\b` and that's what the error is referring to?

I wasn't even sure this was allowed, as some documentation mentioned that `\b` is zero-size, so `?` may not make sense. But in TextMate, this did what I hoped it would do, so I assumed it was allowed.
