### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:33867)

### ISSUE THREAD

**Issue by sumanac** [Microsoft/vscode#40767]
VsCode debugger was working before upgrading to 1.19.1. Now getting the timeout error.
Vscode: 1.19.1
Node: 8.9.1

launch.json:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Jest",
      "runtimeArgs": [
        "--inspect-brk",
        "./node_modules/jest/bin/jest.js",
        "-i",
        "--config",
        "./jestconfig.json"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "sourceMaps": true
    }
  ]
}

terminal shows correct (default) host and port:
C:\SFB\adminportal> cd 'c:\myproject; node --inspect-brk ./node_modules/jest/bin/jest.js -i --config ./jestconfig.json --inspect-brk=33867
Debugger listening on ws://127.0.0.1:9229/359b4152-a45e-4a43-92f7-6bc8e1f72a9e

Tried to follow instructions on similar issue thread, but did not work. Appreciate any help.

**Comment by auchenberg** [comment]
See if this configuration helps you, https://github.com/Microsoft/vscode/issues/19566#issuecomment-301254539

We have a yet to add an official recipe for Jest, tracking here https://github.com/Microsoft/vscode-recipes/issues/37

**Comment by sumanac** [comment]
Thanks for adding an official recipe for Jest. I added the suggested configuration and it solves the timeout error, but the debugger does not stop at break points anymore and it can't find any test files which are declared in jestconfig.json. I will play with the configuration to see if I can solve the problem.

**Comment by auchenberg** [comment]
@sumanac Have you tried, https://facebook.github.io/jest/docs/en/troubleshooting.html#debugging-in-vs-code?

**Comment by jkettmann** [comment]
I had the same problem and just added a port number to the config and appended it after the --inspect-brk cli option as well. My jest config looks as follows now:

```
{
  "type": "node",
  "request": "launch",
  "name": "Debug Unit Tests",
  "port": 9230,
  "runtimeArgs": [
    "--inspect-brk=9230",
    "${workspaceRoot}/node_modules/jest/bin/jest.js",
    "--runInBand",
    "--watch"
  ],
  "runtimeExecutable": null,
  "console": "externalTerminal",
  "internalConsoleOptions": "neverOpen",
  "env": {
    "BABEL_ENV": "testing"
  }
}
```

**Comment by auchenberg** [comment]
@jkettmann We just landed a recipe for Jest, https://github.com/Microsoft/vscode-recipes/tree/master/debugging-jest-tests

**Comment by sumanac** [comment]
@auchenberg, Thanks for jest recipe. It takes care of the timeout issue and it seeps promising. However, I have a source map problem now as the debugger can't file any test files. I will update the thread when my test issue is resolved. 
@jkettmann, your config also solve the timeout problem,but having same source map problem. Thanks!

**Comment by jkettmann** [comment]
@auchenberg I tried the recipe yesterday and it wasn't working, tried it again today and it is working :-). I will use the recipe now. Thanks a lot

**Comment by pollingerMaxi** [comment]
Hello, i have same problem as op

This is my launch.json
`{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\compiledServer\\start.js",
            "cwd": "${workspaceRoot}\\compiledServer",
            "sourceMaps": true,
            "outFiles": [],
            "restart": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858,
            "outFiles": [],
            "protocol": "inspector"
        }
    ]
}`

I dont have tests nor Jest.

When i press F5 to launch program this is result i get in debug console
`Debugging with inspector protocol because Node.js v8.2.1 was detected.
node --inspect-brk=42021 start.js 
Debugger listening on ws://127.0.0.1:42021/7c66b692-e413-4131-ac8e-8cab615dd6ce
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:42021/7c66b692-e413-4131-ac8e-8cab615dd6ce`

**Comment by auchenberg** [comment]
@pollingerMaxi Can I get you to open a new issue with more details about your setup such as Node version, VS Code version, and then we can debug it there without spamming this issue?

**Comment by pollingerMaxi** [comment]
@auchenberg Of course, done.

**Comment by sumanac** [comment]
Finally, One of my teammates who knows more about Jest:) helped me resolving my debugging problem using the latest Jest recipe. He added  the following changes to the launch.json to make the "Jest Current File" debugging work. Posting in case it helps others. Thanks! 
{
      "type": "node",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceRoot}/node_modules/jest/bin/jest",
      "args": [
        "--config",
        "./jestconfig.json",
        "${fileBasename}"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
