### ISSUE TITLE
Provide a full variables overview

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#40779]
Reproduces without extensions: Yes

While working on `package.json` for a debugger extension I saw variations of the variables pattern (e.g. `${workspaceFolder}/${command:AskForProgramName}` and `${workspaceFolder}/${1:Program}` -> see the mock debugger extension) which made me wonder what else is supported and I did an online search, which returned nothing. After digging a bit more I found the [variables substitution](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution) for tasks, which is a rather cheap explanation.

Variable substitution is not only limited to tasks and the [Tasks page](https://code.visualstudio.com/docs/editor/tasks) is a rather obscure place for variables , so I'd like to request a new web page that explains variable substitution within vscode in all it's glory. List all supported variables, explain every special form with examples (like `env:`, `command:`, `1:` etc.) and mention where variable substitution is supported. Thanks.

**Comment by dbaeumer** [comment]
This makes sense to me. 

@gregvanl can you start on this and then @isidorn and me can review.

**Comment by gregvanl** [comment]
Existing vscode-docs issue https://github.com/Microsoft/vscode-docs/issues/1027 covers creating a single shared variable substitution page. We should make sure it covers the prefix features mentioned above.
