### ISSUE TITLE
cv2 can't autocomplete 

### ISSUE THREAD

**Issue by yuboona** [Microsoft/vscode#40773]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04
1. I have successfully installed the "Python" addon.
2. I also successfully installed opencv for python using "pip install opencv-python"
3. For other modules,the function can be autocompleted.But when comes to opencv I can't get autocompletion by typing "cv2.VideoCapture"

**Comment by weinand** [comment]
Please file this issue against the Python extension.
