### ISSUE TITLE
Provide *.desktop file for help create an icon launcher easily in *Linux

### ISSUE THREAD

**Issue by leandrw** [Microsoft/vscode#4077]
I tried create a *.desktop launcher, but didn't worked. I copied atom.desktop and replaced some strings, but it seems not bind with app code. Code from my *.desktop launcher:

```
[Desktop Entry]
Name=Visual Studio Code
Comment=Build and debug modern web and cloud applications.
GenericName=Visual Studio Code
Exec=/usr/share/code/code %U
Icon=/usr/share/code/resources/app/resources/linux/code.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
```
The result:
![screenshot from 2016-03-12 23-20-59](https://cloud.githubusercontent.com/assets/1456009/13726509/3c68aafa-e8a9-11e5-8935-354b469d1911.png)

**Comment by bpasero** [comment]
@Tyriar fyi

**Comment by Tyriar** [comment]
This is coming in the upcoming release along with deb and rpm package files. If you're interested the file used is https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop
