### ISSUE TITLE
[Terminal, NPM, MR] [BUG] "npm install electron --save-dev" install electron to last folder in MR instead to selected Folder.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#40777]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.3.9600
   Windows 8.1 & Linux Ubuntu 16.04 Gnome 3
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.14.5

---

Steps to Reproduce:

1. Open folder [FolderN1] in VSCode explorer, Open one more folder [FolderN2]. Select first folder.
2. Open terminal, try install electron or anything else by npm.

Result:

You will install electron to FolderN2 instead to FolderN1 (which you have selected)

Reproduces without extensions: Yes

**Comment by Mlocik97-issues** [comment]
By Open in Terminal it work correctly, but over Ctrl+ not. So Can you improve this?

**Comment by Tyriar** [comment]
ctrl+\` will create the terminal in the previous opened *file's* location, not the selected folder in the explorer. If you're using multiple roots you should prefer ctrl+shift+\` which will show a selector
