### ISSUE TITLE
Can support quick open dirctory?

### ISSUE THREAD

**Issue by techbirds** [Microsoft/vscode#40771]
In the big project will be very useful. (eg: [Webstorm search everywhere ](https://www.jetbrains.com/help/webstorm/quick-start-guide.html#search_everywhere))

thanks.

**Comment by roblourens** [comment]
I prefer what VS Code is already doing, it's not likely that we'll add something like what Webstorm has.

**Comment by techbirds** [comment]
First of all, very grateful vscode such a good product, but the search directory function is still very useful, very much looking forward to vscode able to add this feature, and hope vscode team can seriously consider.

thanks again.
