### ISSUE TITLE
TAB SCROLL BUTTON

### ISSUE THREAD

**Issue by jhashailesh3108** [Microsoft/vscode#40770]
Hi,

I  have some requests 
1.please provide a tab scroll button so we can scroll through tabs with ease as it is in Sublime. 
2. For PHP  not all the functions are showing links as in sublime. It is best for JS development but not that great for PHP.
Thank You

**Comment by usernamehw** [comment]
The first one looks like a dup of https://github.com/Microsoft/vscode/issues/39059

**Comment by jhashailesh3108** [comment]
Thanks,  I was not aware of that.

**Comment by roblourens** [comment]
> 2. For PHP not all the functions are showing links as in sublime. It is best for JS development but not that great for PHP.

I don't understand, can you explain this some more?

**Comment by jhashailesh3108** [comment]
Like in sublime,  when  you hover over any function in php. it shows the
clickable link for that function location and on click it jumps to that
particular function at main location where functions is described. I wish
it could be possible for vs code as well. VS code has this feature but that
does not work so fine for PHP. Hope you understand now.

On 24 Dec 2017 8:51 pm, "Rob Lourens" <notifications@github.com> wrote:


   1. For PHP not all the functions are showing links as in sublime. It is
   best for JS development but not that great for PHP.

I don't understand, can you explain this some more?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/40770#issuecomment-353789761>,
or mute the thread

**Comment by roblourens** [comment]
I see. That functionality is provided by at least a couple extensions for PHP, but not built in. You should check out the extensions.
