### ISSUE TITLE
get (or set) function shows description from *both* get and set function on hover

### ISSUE THREAD

**Issue by kleinfreund** [Microsoft/vscode#40775]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.13.0-21-generic
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. View the following code with language mode set to JavaScript

   ```js
   class Test {
     constructor() {
       this.value;
     }
   
     /** Getter text */
     get value() {
       return this.value;
     }
   
     /** Setter text */
     set value(value) {
       this.value = value;
     }
   }
   ```

2. Hover over the `value` getter (or setter) function

**Expected behavior**:

`Getter text` (or `Setter text`) appears in the box as the function description.

**Actual behavior**:

`Getter text Setter text` appears in the box as the function description.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20966
