### ISSUE TITLE
Markdown incorrect styling in editor

### ISSUE THREAD

**Issue by KamasamaK** [Microsoft/vscode#40787]
- VSCode Version: 1.19.1

In Markdown files, the editor is incorrectly styling every other inner word surrounded by underscores as italicized. The preview correctly shows them as not italicized.

![markdown-italic-bug](https://user-images.githubusercontent.com/22951521/34328490-4d360aa6-e8ae-11e7-9490-5ec85fb3acd4.png)

**Comment by bpceee** [comment]
I think this is what Text Mate grammars' behavior. Tried in TextMate 2.0 (latest), same there.
![image](https://user-images.githubusercontent.com/4188573/34555030-b297430a-f16a-11e7-8f94-3668daaa7e13.png)

**Comment by mikaoelitiana** [comment]
I think @KamasamaK is right on this. The editor has an error as it interprets the other word as if it was a separate word starting and finishing with `_` (that would be italized). 
It is correctly displayed on Github editor : `MULTIPLE_WORDS_SEPARATED_BY_UNDERSCORE`

**Comment by mikaoelitiana** [comment]
I created a PR to fix this #41466
