### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by sandbarTrue** [Microsoft/vscode#40789]
- VSCode Version: VSCodeSetup-x64-1.19.0
- OS Version:6.1.7601 Service Pack 1 内部版本 7601

Steps to Reproduce:

1. open a web project 
2.

![image](https://user-images.githubusercontent.com/17819209/34330031-90c512ce-e950-11e7-8084-75d0f4f257fe.png)

Reproduces without extensions: Yes/No  YES

**Comment by weinand** [comment]
I do not understand Chinese and I cannot translate the message in the screenshot. Please provide this information in English.

Can you repro this when running `code --disable-extensions`?
