### ISSUE TITLE
error while installing the vscode in ubuntu

### ISSUE THREAD

**Issue by inyee786** [Microsoft/vscode#40788]
here is the log 

Setting up code (1.19.1-1513676564) ...
/var/lib/dpkg/info/code.postinst: line 70: /etc/apt/sources.list.d/vscode.list: Is a directory
dpkg: error processing package code (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 code

**Comment by Tyriar** [comment]
`/etc/apt/sources.list.d/vscode.list` is a directory for some reason? Try running `sudo rm -rf /etc/apt/sources.list.d/vscode.list` and trying again. You may also want to double check what's inside using `ls /etc/apt/sources.list.d/vscode.list` before removing it.
