### ISSUE TITLE
Retrieve output from a programmatically created Terminal

### ISSUE THREAD

**Issue by igorskyflyer** [Microsoft/vscode#40795]
- VSCode Version: 1.19
- OS Version: Windows 10, version 1709

Steps to Reproduce:

1. create a Terminal, using the createTerminal function,
2. only SendText function is available

This feature would be useful for creating utilities/extensions that use terminals, i.d. command prompts.

Reproduces without extensions: Yes.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13337
