### ISSUE TITLE
characters in 2017 editor cannot be changed easily with good UIX

### ISSUE THREAD

**Issue by nadir-almarzouki** [Microsoft/vscode#40790]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. open js file with editor of VS 2017 WIN WAY
2. N/A

**Comment by weinand** [comment]
I do not understand "WIN WAY2". Please explain.
