### ISSUE TITLE
window.openFoldersInNewWindow seems hiding new windows

### ISSUE THREAD

**Issue by HQidea** [microsoft/vscode#40796]
- VSCode Version: 1.19.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. settings:
```
"window.openFoldersInNewWindow": "on",
```
2. open a fold in the File menu
3. new windows are hidden in the back, not the active ones

Reproduces without extensions: Yes

**Comment by niamleeson** [comment]
I'm having this issue as well but only in one Mac

The Mac with the issue:
VSCode Version: 1.19.1
OS Version: OS X 10.13.2

The Mac without the issue:
VSCode Version: 1.19.1
OS Version: OS X 10.12.6

Steps to Reproduce:
1. Add to settings:
`"window.openFoldersInNewWindow": "on",`

2. File > Open > Select a folder

3. The new window is focused, but is not displaying in front of the old window. CMD + Tilde twice brings the new window to the front.

Reproduces without extensions: Yes
