### ISSUE TITLE
Python Debbuger can't read PATH variable in os module (KeyError: 'PATH')

### ISSUE THREAD

**Issue by frantel90** [Microsoft/vscode#40797]
When I try to debug a Python script that uses environment OS variable 'PATH' it throws an exception, but it runs fine from terminal.

script:
import os
print(os.environ["PATH"])

Traceback:
    print(os.environ["PATH"])
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.13.0-21-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
code-python-isort|fre|0.0.3
python|ms-|0.9.1
csharp|ms-|1.13.1
Csharp-ASPNETCore|rah|1.0.5
vscode-icons|rob|7.19.0
python|tht|0.2.3

---

Steps to Reproduce:

1. Create this script 
2. Debug (f5)

Reproduces without extensions: Yes/No

**Comment by luoguizhou** [comment]
Yes, it meets me, too
