### ISSUE TITLE
Install code in PATH does not persist restart or relaunch

### ISSUE THREAD

**Issue by abhayghatpande** [Microsoft/vscode#40809]
- VSCode Version: 1.17.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Install `code` using the command palette 
2. Restart VSCode or Terminal

It is basically the same as issue #17475, the issue was closed but the problem still exists.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7426
