### ISSUE TITLE
操作git dif 或者 git log 后，然后想要输入任何命令行都显示不出来，必须重新开一个窗口 

### ISSUE THREAD

**Issue by Rudy24** [Microsoft/vscode#40806]
- VSCode Version: Code 1.19.0 **[Unsupported]** (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
path-intellisense|chr|1.4.2
githistory|don|0.2.3
EditorConfig|Edi|0.11.1
vscode-great-icons|emm|2.1.22
auto-close-tag|for|0.5.5
beautify|Hoo|1.1.1
output-colorizer|IBM|0.1.2
docthis|joe|0.6.0
vscode-fileheader|mik|0.0.2
debugger-for-chrome|msj|4.0.0
vetur|oct|0.11.5
vuehelper|oys|0.1.0
vscode-icons|rob|7.19.0
background|sha|1.1.17
code-settings-sync|Sha|2.8.7
Align|ste|0.2.0
JavaScriptSnippets|xab|1.5.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
automatic translation:
After operating git dif or git log, and then want to enter any command line will not be displayed, you must re-open a window

**Comment by weinand** [comment]
Please provide detailed steps so that we can reproduce.

**Comment by dulowski-marek** [comment]
I have also come across this issue - it occurs, when you exit interactive git commands (like `git log` or `git diff`) with Ctrl+C instead of q. Bash `reset` command fixes this.

Is it expected?

**Comment by joaomoreno** [comment]
Sounds like terminal related.

**Comment by Tyriar** [comment]
@dulowski-marek can you elaborate a little? I'm unable to exit `git log` and `git diff` using ctrl+c, AFAIK git captures ^C
