### ISSUE TITLE
Goto Defination is not working in html css

### ISSUE THREAD

**Issue by uzhiyaan** [Microsoft/vscode#40801]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.4.0-104-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
crane|Hvy|0.3.8
html-css-class-completion|Zig|1.14.0
vscode-intelephense-client|bme|0.8.4
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.1.3
goto-documentation|cxf|0.0.1
php-debug|fel|1.12.1
php-intellisense|fel|2.2.1
php-pack|fel|1.0.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
code-runner|for|0.8.6
![screenshot from 2017-12-25 11-19-15](https://user-images.githubusercontent.com/32426698/34333726-bb6ffd30-e965-11e7-9124-71c311d1436b.png)

live-html-previewer|hdg|0.3.0
php-import-checker|mar|0.0.1
debugger-for-chrome|msj|4.0.0
vscode-css-peek|pra|2.0.2
LiveServer|rit|3.0.2
salesforcedx-vscode-apex|sal|41.12.0
code-navigation|vik|0.2.0
highlight-matching-tag|vin|0.4.4
better-align|wwm|1.1.6

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
This isn't something that we provide out of the box by default, but there might be an extension that provides it.
