### ISSUE TITLE
window resize bug

### ISSUE THREAD

**Issue by eaglewu** [Microsoft/vscode#40805]
Demo: https://imgur.com/Opi9sMd

- VSCode Version: 1.19.1 (1.19.1)
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. Drag the window

Reproduces without extensions: Yes

**Comment by weinand** [comment]
I don't understand what you mean and the "demo" from a above is just a blurry static screenshot.
Please explain how to reproduce this.
