### ISSUE TITLE
HTML code folding? 

### ISSUE THREAD

**Issue by Nimeshka** [Microsoft/vscode#40807]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:56:48.842Z)
- OS Version: Linux x64 4.4.0-104-generic
- Extensions: none
---
When you fold html code blocks, it only folds up to the current indentation level. Any unindented lines cause folding to stop at that particular line. It would be nice if the editor is aware of the language and fold the matching tag instead of looking for the indentation. I'm not sure if this qualifies as an issue, but I think its a nice feature to have, because I don't have to worry about indentation much while I develop (or specially when working on shared files)

Steps to Reproduce:

1. Write a simple html block including children tags.
2. Change the indentation of a child element to the parent's indent level.

**Comment by aeschli** [comment]
You are looking for language aware folding: #3422
