### ISSUE TITLE
I need to add canvas intellisense hints, and the canvas plugin currently in extension doesn't work

### ISSUE THREAD

**Issue by bymomo** [Microsoft/vscode#40819]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  我需要添加canvas智能感知提示,目前在扩展中的canvas插件并不好用
2.I need to add canvas intellisense hints, and the canvas plugin currently in extension doesn't work

Reproduces without extensions: Yes/No  yes

**Comment by Tyriar** [comment]
Is this canvas in JavaScript? If you're using TypeScript you can get intellisense for canvas APIs:

<img width="749" alt="screen shot 2017-12-27 at 3 36 32 pm" src="https://user-images.githubusercontent.com/2193314/34396098-bc62ea2e-eb1b-11e7-8129-98af7c11fd57.png">
