### ISSUE TITLE
Scrolling in Surface Laptop makes VSCode to get stuck for a few seconds before scrolling action starts.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [Microsoft/vscode#40816]
I have notice that VSCode doesn't respond nice to scrolling file content when using the Surface Laptop trackpad. Is this a known  issue? scrolling with a touch gesture is even more responsive. other applications do not show this lagging response when using the trackpad.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
azuretoolsforvscode|bra|1.3.0
azure-functions-tools|joh|0.3.1
vscode-azureappservice|ms-|0.5.0
vscode-azurefunctions|ms-|0.4.0
mssql|ms-|1.3.0
azure-account|ms-|0.2.2
azurecli|ms-|0.3.0
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
vscode-azureextensionpack|ms-|0.0.8
team|ms-|1.122.0
azurerm-vscode-tools|msa|0.3.7
vscode-docker|Pet|0.0.22
usql-vscode-ext|usq|0.2.8
application-insights|Vis|0.4.1
azure-iot-edge|vsc|0.1.3
azure-iot-toolkit|vsc|0.5.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by gauravsaini** [comment]
Fixes when you reload the extensions after disabling them.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13612
