### ISSUE TITLE
Terminal interface display bug.

### ISSUE THREAD

**Issue by Duobe** [Microsoft/vscode#40817]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
vscode-docker|Pet|0.0.22
ReactSnippetsStandard|Tim|1.1.0
quokka-vscode|Wal|1.0.85
alignment|ann|0.3.0
vscode-exports-autocomplete|cap|0.5.4
vscode-wxml|cod|0.1.9
riot-tag|cri|0.1.7
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
flow-for-vscode|flo|0.7.3
code-runner|for|0.8.6
vue|jcb|0.1.5
code-beautifier|mic|1.7.2
vscode-autoprefixer|mrm|2.1.2
vscode-less|mrm|0.6.3
python|ms-|0.9.1
azure-account|ms-|0.2.2
github-issues-prs|ms-|0.9.0
node-debug2|ms-|1.19.2
vscode-wechat|qin|0.0.6
vscode-icons|rob|7.19.0
preview-vscode|sea|1.4.2
vscode-react-native|vsm|0.5.7
html-less-class-completion|wan|0.0.6
react-playground-vscode|wmi|0.0.11

---

Steps to Reproduce:

1.Open the terminal with a project containing the Chinese name
2.Drag and drop to another display
3.press Enter.(You will found the  chinese become very small.)
4.when enter cmd. Some font size also become very small. sometimes cannot read clear the texts.
![image](https://user-images.githubusercontent.com/10445790/34345758-56c9849c-ea2c-11e7-86fb-a2533b39cb26.png)

![image](https://user-images.githubusercontent.com/10445790/34345354-40dee2a6-ea29-11e7-9520-c7c2cc9690be.png)

Reproduces without extensions: No

**Comment by evolucionapp** [comment]
The same visual problems on Terminal are being experienced on my end as well, but I don't have Chinese characters in my project path, not even latin characters, at most, spaces and dashes.

I have not been able to find a way to reproduce this issue, it happens sometimes. If I open a new terminal on the same VSC instance, that new terminal opens correctly, and I can go back to the first one and close it. Somehow the second terminal never gets corrupted as the first one.

This is how it looks when the first terminal gets corrupted:

![screenshot 2017-12-26 08 30 45](https://user-images.githubusercontent.com/763974/34357679-18c36524-ea17-11e7-9af9-440ea7ae1548.png)

And this is how it should look (and how the 2nd terminal looks):

![screenshot 2017-12-26 08 34 59](https://user-images.githubusercontent.com/763974/34357751-b7c8d500-ea17-11e7-8144-720ce84c68f8.png)

I am using Version 1.19.1 (1.19.1) on Mac OS high Sierra (10.13), MacBook Pro (Retina, 15-inch, Mid 2015), Processor: 2.8 GHz Intel Core i7, Memory: 16 GB 1600 MHz DDR3, Graphics: AMD Radeon R9 M370X 2 GB, Intel Iris Pro 1536 MB.

Extensions:

.ejs version 0.0.1 by Qassim Farid.
C# version 1.13.1 by ms-vscode.
ESLint version 1.4.3 by dbaeumer.
Material Icon Theme version 3.2.0 by PKief.
npm version 0.3.3 by eg2.
npm Intellisense version 1.3.0 by christian-kohler.
Partial Diff version 0.5.1 by ryu1kn.
PHP Debug version 1.12.1 by felixfbecker.
PHP Extension Pack version 1.0.1 by felixfbecker.
PHP IntelliSense version 2.2.2 by felixfbecker.
Preview version 1.4.2 by searKing.
SVN version 1.5.0 by johnstoncode.
Vetur version 0.11.15 by octref.
vscode-base64 version 0.0.1 by adamhartford.
XML Tools version 1.9.2 by DotJoshJohnson.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34320
