### ISSUE TITLE
Auto import uses camel case for lowercased filenames instead of pascal case which is against airbnb guidelines

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40810]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
prettier-vscode|esb|1.0.1
intellij-idea-keybindings|k--|0.2.17
debugger-for-chrome|msj|4.0.0
vscode-fileutils|sle|2.7.1

---

Steps to Reproduce:

1. Create a file called 'airbnb-style-guide.js` with the following content -

```
const AirbnbStyleGuide = {
  es6: {
  },
};

export default AirbnbStyleGuide;
```

2. Create a second file and start typing "Air" and notice auto complete.

EXPECTING: `import AirbnbStyleGuide from './airbnb-style-guide.js`
ACTUAL: `import airbnbStyleGuide from "./airbnb-style-guide";`

![image](https://user-images.githubusercontent.com/2301847/34340362-fa3370e0-e93f-11e7-8232-fc8f3b7c0d8c.png)
![dec-25-2017 06-55-28](https://user-images.githubusercontent.com/2301847/34340444-d9abcd4e-e940-11e7-8515-00e43489efc0.gif)
![image](https://user-images.githubusercontent.com/2301847/34340458-0143c802-e941-11e7-8104-cb87e4afe1d9.png)

https://github.com/airbnb/javascript#naming--PascalCase-singleton

I'm guessing this is filename guessing since a file called `AirbnbStyleGuide.js` works correctly.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20967
