### ISSUE TITLE
i need mactype support！ why you change the render way！

### ISSUE THREAD

**Issue by nnnevermore** [Microsoft/vscode#40815]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
html-snippets|abu|0.1.0
html-class-suggestions|And|1.0.7
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
gitignore|cod|0.5.0
javadebugger|don|0.1.5
xml|Dot|1.9.2
vscode-html-css|ecm|0.1.8
vscode-auto-open-markdown-preview|hnw|0.0.4
OpenVim|mat|0.0.8
code-beautifier|mic|1.7.2
python|ms-|0.9.1
cpptools|ms-|0.14.5
ravi-debug|rav|0.0.23
shader|sle|1.1.2
vscode-hexdump|sle|1.6.0
shader-toy|ste|0.4.0
ignore-gitignore|stu|1.0.1
html-preview-vscode|tht|0.1.1
vscode-lua|tri|0.9.0
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
html-css-class-completion|Zig|1.14.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@nnnevermore Can you provide some more context? What are you doing that now no longer works? Was something working for you in a prior version of VS Code that now no longer works in 1.19.1?

**Comment by aeschli** [comment]
Closing, not enough information provided.
