### ISSUE TITLE
How to specify view column when adding a local html link that is previewed by vscode?

### ISSUE THREAD

**Issue by ansyral** [Microsoft/vscode#40818]
Hi, I'm trying to use the following snippet to add a local link in html:
```
const href = encodeURI('command:vscode.previewHtml?' + JSON.stringify(uri_with_self_defined_scheme));
```
it works great, but my problem is that I want the link would be rendered in current view column, however right now if i click on the link, it would always be rendered in another view column. Any query string that i could add to specify the view column? Thanks

**Comment by jrieken** [comment]
@ansyral Can you provide a little more code, e.g. you extension? I am actually a little surprised that it open in another column and not the current one.

**Comment by ansyral** [comment]
@jrieken Here is the [code](https://github.com/Microsoft/vscode-java-test/blob/master/extension/src/testReportProvider.ts#L51) . One thing to mention is that I rendered the html in ViewColumn.Two, not sure whether it is related. Thanks.

**Comment by jrieken** [comment]
Try to encode all arguments as array, so something like this `passedUri: 'command:vscode.previewHtml?' + encodeURIComponent(JSON.stringify([URI, Column]))),`. From looking at the code that should do it.

**Comment by ansyral** [comment]
Thanks, @jrieken. My fault, I misunderstood the meaning of viewcolumn. What I need is to show the link in current *tab* of the view column, not in another tab, the image below shows current behavior, I now try to add `target="_self"` attribute in the html, but seems it still opens in another tab
![image](https://user-images.githubusercontent.com/1982828/34657686-d62e558c-f463-11e7-9f57-1990c0391548.png)

**Comment by ansyral** [comment]
another question is that sometimes the link doesn't work(couldn't repro in a regular pattern) and there isn't any error thrown when rendering the html, and `provideTextDocumentContent` method isn't hit so I guess it is related to the previewHtml command.  should I create another thread to track this?
![image](https://user-images.githubusercontent.com/28860891/34431241-7533db0c-eca8-11e7-95b9-2e450c55b352.png)

**Comment by jrieken** [comment]
> Thanks, @jrieken. My fault, I misunderstood the meaning of viewcolumn. What I need is to show the link in current tab of the view column,

And you know or you don't know the current tab?

**Comment by ansyral** [comment]
> And you know or you don't know the current tab?

Is there any way to get to know the tab info in vscode?

**Comment by jrieken** [comment]
No, you cannot ask for the active view column. However, when not passing one it will fallback to the active one... You can also try using `ViewColumn.Active`

**Comment by ansyral** [comment]
Just to make sure I don't misunderstand. vscode splits the editor to several view columns and in each column you could open several tabs. Am I correct? When clicking the link, it opened in another tab of the active view column, so I'm afraid ViewColumn.Active might not work?

**Comment by jrieken** [comment]
> When clicking the link, it opened in another tab of the active view column, so I'm afraid ViewColumn.Active might not work?

Yes, you can reference and re-use a column, not a tab (that's being tracked here #15178). With a webview you might be able to workaround this, e.g. replace the contents of it without workbench interaction, just by setting/updating the current document.
