### ISSUE TITLE
'Project' management via extension?

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#4081]
Is it possible to customise the project tree area via extension?
Let's imagine I wanted to write an MSBuild extension which would read a .sln and present solution/projects the same way VS does. Is this possible? What is required to get there?

There are other project systems that would be nice to support in the same way (a lot of IDE's can parse a makefile and populate a project from that), and it would be great if extensions had the power to populate the tree, and register some project-associated commands, like 'set active project', build and run.

**Comment by jrieken** [comment]
That's currently not possible.

**Comment by TurkeyMan** [comment]
I didn't think so. I think it would be a mighty fine goal for extensions. If we reached a point where we could load regular VS solutions (and/or develop other application specific project systems), that would be quite amazing.

**Comment by chrisdias** [comment]
While this was an earlier bug, the work to support this scenario happened in #12163. Closing in favor of that issue, sorry for the ordering.
