### ISSUE TITLE
VScode extension: Catching an exception while chaining Thenable object returned by vscode utility functions.

### ISSUE THREAD

**Issue by gouravgupta92** [Microsoft/vscode#40812]
Hi,

I need to take multiple inputs from user for which i am using `vscode.window.showInputBox`.

```
var modelName, visibility;
vscode.window.showInputBox({ prompt: 'Enter Model Name', ignoreFocusOut: false })
.then(input => {
    modelName = input;
    return vscode.window.showInputBox({ prompt: 'Is model public or private', ignoreFocusOut: false }) ;
})
.then(input => {
    visibility = input;
})
.catch(err => {
    console.log(err);
})
```
I am getting error 
```
TypeError: vscode.window.showInputBox(...).then(...).then(...).catch is not a function
```

I know that i can get error as second parameter in `then`. But in chaining of then, is there and way to work out with only one catch or only one error handler.
```

**Comment by jrieken** [comment]
The `showInputBox`-function is defined to return a `Thenable`, *not* a promise. There are a few differences and basically the `Thenable` only has `then` but no `catch`. The reason for that is that we use a different promise implementation (for historical reasons). To workaround your issue use `Promise.resolve`.
