### ISSUE TITLE
Extensions Path Settings

### ISSUE THREAD

**Issue by XiuyeXYE** [Microsoft/vscode#40811]
I'd like to use vscode.But I don't like that there is no privilege to set paths of relation with user who have right to do it.Why not give us customed settings of extensions path!If most of extensions in little capacity of  "C:",my OS eventually may not run because of fullness.If there is a option of Extensions Path,where or which line in settings.json

**Comment by weinand** [comment]
You can use the `--user-data-dir` and `--extensions-dir` options from the command line.
See https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options

**Comment by XiuyeXYE** [comment]
@weinand 
Command line is one way of path setting.I can wirte "bat" or "sh" for startup.But I want it to set as default on startup clicking "code.exe".I have done it ,using "mklink" to link extensions path with another path I want.
