### ISSUE TITLE
ES6 syntax highlight seems not working

### ISSUE THREAD

**Issue by leechen** [Microsoft/vscode#4082]
I updated to latest version, the syntax highlight is only partially working for ES6. Here is my jsconfig.json at the root of project:
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}

keywords such as "if", "return", "default" are colored correctly, but keywords such as "let", "import" are not. I am using react with file extension as .js

**Comment by aeschli** [comment]
duplicate of #3903
