### ISSUE TITLE
Integrated Terminal Font Abnormalities

### ISSUE THREAD

**Issue by MaxNvy** [Microsoft/vscode#40823]
The integrated terminal is inserting abnormal letter spacing.  This seems to be a recurrence of an issue that appeared around the October time frame and was since corrected -- now reoccurring. The issue is present on both 'cmd' and 'powershell' terminals. Issue persists through save, shut down, restart and clean reboot.  Was successfully reproduced with over 20 different fonts.

**Use Factors**
- VSCode Version: v.1.19.1 [stable]
- OS Version: Windows 10 v16299.125[Home]
- Extensions (listed below)

**Steps to Reproduce:**
1.  Active use of Integrated Terminal following upgrade to 1.19 (.18?)
2.  Menu > File > Preferences > Settings > User Settings > alter font; (save)
```
"terminal.integrated.fontFamily": "Advent Pro",
```
or
``` 
"terminal.integrated.fontFamily": "Advent Pro, sans-serif",
```

**Reproduces without extensions: Yes**

**SS#1 -> Terminal example of "Advent Pro font"**
![image](https://user-images.githubusercontent.com/28637298/34350368-70705ca6-e9e4-11e7-9c56-375a54a3668d.png)

**SS#2 -> Editor example of "Advent Pro font"** [Font appears correctly spaced]
![image](https://user-images.githubusercontent.com/28637298/34350334-46106c8a-e9e4-11e7-9b01-467b2aa88b75.png)

- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Aurelia|beh|1.2.2
jshintrc-generator|ben|1.0.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.12.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
vscode-instant-markdown|dba|1.3.0
xml|Dot|1.9.2
gitlens|eam|7.1.0
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
vsc-material-theme|Equ|1.1.2
git-project-manager|fel|1.4.0
vscode-npm|fkn|3.3.0
terminal|for|0.0.10
pug2html|gin|0.0.5
githd|hui|1.0.0
Angular2|joh|2.11.2
functional-js-snippets|kol|1.0.2
vscode-jade-snippets|mrm|1.0.1
vscode-puglint|mrm|2.3.0
mssql|ms-|1.3.0
debugger-for-chrome|msj|4.0.0
live-server-preview|neg|0.0.4
material-icon-theme|PKi|3.2.0
highlight-matching-tag|vin|0.4.4
gitblame|wad|2.2.0
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.14.0

(1 theme extensions excluded)

---

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35681
