### ISSUE TITLE
Provide instructions on how to use Google Canary for the Chrome Developer Tools

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40824]
- VSCode Version: code-oss-dev 1.20.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Is there a way you can provide instructions on how to use Google Canary for the Chrome Developer Tools?

**Comment by Tyriar** [comment]
This is not possible, we ship a specific version of Electron which is based on a numbered version of Chromium.
