### ISSUE TITLE
When I Scroll The Explorer, Some Item be Fixed.

### ISSUE THREAD

**Issue by trylovetom** [Microsoft/vscode#40825]
- VSCode Version: 1.19.1
- OS Version: MacOS High Sierra

Steps to Reproduce:

1. Just Scroll Explorer

Reproduces without extensions: Yes

When I Scroll The Explorer, Some Item be Fixed. Bug ?

![xcodebug](https://user-images.githubusercontent.com/13268073/34351811-ccbb13dc-ea59-11e7-9451-5c653db8d587.gif)

**Comment by isidorn** [comment]
I can not reproduce this. Can you please try reproducing this with the latest vscode insiders https://code.visualstudio.com/insiders/

Can you please provide reproducable steps to see this.
fyi @joaomoreno

**Comment by trylovetom** [comment]
When I open too many items, it's happened irregularly.

**Comment by isidorn** [comment]
@trylovetom that does not really help us to reproduce.
Can you reproduce with vscode insiders and if you disable all extensions?

**Comment by joaomoreno** [comment]
This is #22269
