### ISSUE TITLE
Clipboard not working when launched in tmux

### ISSUE THREAD

**Issue by maxis1718** [Microsoft/vscode#40820]
- VSCode Version: 1.19.1
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Open a new tmux session: `$ tmux`
2. launch vscode by `$ code`
3. open a new file, try to copy/paste something (but not working)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Read https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
