### ISSUE TITLE
F12搜索某个function的时候导致卡死

### ISSUE THREAD

**Issue by DouglasLiu2016** [Microsoft/vscode#40821]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.14.5
team|ms-|1.122.0
java|red|0.16.0
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0

(5 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
What language are you using?
