### ISSUE TITLE
Error TypeScript

### ISSUE THREAD

**Issue by alexnfsc175** [Microsoft/vscode#40838]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.14.8-1-ARCH
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.1.1
Angular-BeastCode|Mik|5.1.15
php-debug|fel|1.12.1
docthis|joe|0.6.0
Angular2|joh|2.11.2
vscode-phpfmt|kok|1.0.17
vscode-scss|mrm|0.6.2
mssql|ms-|1.3.0
node-debug2|ms-|1.20.0
sass-indented|rob|1.4.6
autoimport|ste|1.5.3
react-beautify|tai|0.3.0
vscode-react-native|vsm|0.5.7

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
@alexnfsc175 How can this bug be reproduced? What were you doing when you encountered this error?
