### ISSUE TITLE
Make VScode remember wordwrap preference

### ISSUE THREAD

**Issue by jwalantsoneji** [Microsoft/vscode#40830]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
sort-imports|ama|4.1.1
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.14
vscode-generate-getter-setter|DSK|0.4.2
vscode-firefox-debug|hbe|0.17.0
dependency-cleaner|jac|1.0.3
docthis|joe|0.6.0
debugger-for-chrome|msj|4.0.0
typescript-uml|ott|1.1.2
vscode-icons|rob|7.19.0
move-ts|str|1.6.0

---

Steps to Reproduce:

1. Open VSCode
2. Press F1 and select word wrap toggle

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
You can set word wrap in your user settings (ctrl+,):

<img width="688" alt="screen shot 2017-12-27 at 3 27 29 pm" src="https://user-images.githubusercontent.com/2193314/34395996-83565096-eb1a-11e7-8ef5-f78819f4a4ca.png">
