### ISSUE TITLE
Add a way for edit files including HTML with GUI editor.

### ISSUE THREAD

**Issue by STEdirisuriya** [Microsoft/vscode#40831]
Improvement!

- VSCode Version: 1.19.1
- OS Version: Windows 10 and Linux Ubuntu 16.04 both
Add a way for open files in browser or another window and edit text, edit animations, add pictures, etc...

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Most of this is possible with extensions, if you have a specific API request please create a new issue.
