### ISSUE TITLE
Icons on activity bar disappear after adjusting the size of the window

### ISSUE THREAD

**Issue by YongjiLiuGit** [Microsoft/vscode#40835]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.3.9600
---

Steps to Reproduce:

1. Stretch the window to a very small size, maybe minimum, until you can't see all the five icons on the activity bar. When you strectch the window to a minimum, you can see the icons changing to a three point icon like this.
![1](https://user-images.githubusercontent.com/32985998/34358429-b416e87a-ea8a-11e7-9fe3-09b43219cb12.PNG)

2. Now just resize the window to a normal size, the other four icons will be lost.
![2](https://user-images.githubusercontent.com/32985998/34358439-c85a2f5e-ea8a-11e7-99ec-860fad7353a2.PNG)
![3](https://user-images.githubusercontent.com/32985998/34358584-e329695c-ea8b-11e7-9fc4-1e8fe5077cbc.PNG)

3. I've tried several settings, but nothing works.

Reproduces without extensions: Yes/No
Yes

**Comment by YongjiLiuGit** [comment]
em, I just find this...
![4](https://user-images.githubusercontent.com/32985998/34363415-eb101b0e-eab6-11e7-9744-87918125075e.PNG)
I'm sorry, I'm a new user.
I suggest it can restore automatically when resizing the window, just as automatically hiding.

**Comment by bpasero** [comment]
We fixed this issue in insiders meanwhile. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

@isidorn fyi
