### ISSUE TITLE
Autoupdate on Mac does not work if user doesn't have sudo privileges

### ISSUE THREAD

**Issue by dankirkpatrickmp2** [Microsoft/vscode#40839]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a user on Mac without sudo privileges (in System Preferences->Users and Groups, uncheck the box for "Allow user to administer this computer"
2. Allow autoupdate to run in VSCode... the new version will be downloaded, and you'll get the dialog saying VSCode is ready to restart with the new version, but after restarting, you have the old versions.

A preferred solution would be to ask the user on installation for the administrator user/password if the user is not able to administer the machine.

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
