### ISSUE TITLE
VSCode does not kill a window's zsh shell process when closed with another window open, resulting in High CPU usage.

### ISSUE THREAD

**Issue by nozzlegear** [Microsoft/vscode#40837]
I've been running into this for a couple months now and was finally able to track it down and reproduce it. Using Zsh through WSL on Windows, if I open one VSCode window with Zsh shell, then open another instance of VSCode with Zsh shell and close either one, the closed window does not kill its Zsh processes. Instead the Zsh processes start using crazy amounts of CPU, 25-35% for each closed window. Eventually it slows my machine to a crawl until I open the task manager and kill the zombie Zsh processes.

- VSCode Version: 1.19.1
- OS Version: Windows 10 build 16299
- Zsh Version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

Steps to Reproduce:

1. Use Windows 10 with Windows Subsystem for Linux
2. Set the VSCode integrated shell to use Zsh through WSL: 
    -  `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe"`
    - `"terminal.integrated.shellArgs.windows": ["-c","zsh"]`
3. Open the Windows task manager and scroll to the bottom of the Background Processes list.
4. Open your first VSCode instance. It doesn't matter what files are in the folder.
5. Open the integrated Zsh terminal.
    - In the task manager you'll see that there are now two `Zsh5` processes.
6. Open another instance of VSCode.
7. Open the second instance's Zsh terminal.
    - There are now four `Zsh5` processes.
7. Close either window.
    - There are still 4 `Zsh5` processes and one of them will be using a large amount of CPU.
8. Close the last window.
    - All Zsh processes *may* have closed, or they may not have closed and now there are two using large amounts of CPU. Haven't been able to reliably reproduce this part.

![2017-12-26](https://user-images.githubusercontent.com/2417276/34359912-7d6f1478-ea21-11e7-9970-64308f500c60.png)

I've tested this using both powershell and bash (without zsh) as the integrated terminal and this doesn't happen. Using bash, VSCode will only spawn one instance of the `bash` process per window where Zsh spawns two.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@bitcrazed something funny happening with zsh processes under WSL? A fix I added recently was to kill all console processes when a terminal was killed so I'm surprised to see this happen:

https://github.com/Tyriar/node-pty/blob/12caa78c871caa388b013ab9d2e327f2b0a3a76e/src/windowsPtyAgent.ts#L92-L105

@nozzlegear do you have another application creating the wslbridge processes? I don't think VS Code creates these.

**Comment by nozzlegear** [comment]
It looks like the wslbridge process is coming from the [wsl-terminal](https://github.com/goreliu/wsl-terminal) terminal that I use on Windows. I did some testing without that terminal/process open and the problem still occurs with VSCode. It does look like that terminal also opens two `zsh5` processes, so maybe two processes is just a zsh thing.

**Comment by nozzlegear** [comment]
A little bit more investigation: VSCode will fail to kill its zsh processes when there are *any* other zsh processes open, whether they're from another instance of VSCode or from completely separate terminal. I thought this might just be a zsh problem, but this behavior only occurs from VSCode; my terminal will kill its zsh processes just fine.

Steps to reproduce:

1. Open a terminal window that uses zsh through WSL.
    - There are two `zsh5` processes.
2. Open VSCode with zsh terminal.
    - There are four `zsh5` processes.
3. Close either VSCode or the terminal.
    - There are still four `zsh5` processes and one is using 25-35% CPU.

If you had opened two terminals instead of VSCode this wouldn't happen at all, all `zsh5` processes would stop as expected when the terminal windows are closed.

**Comment by Tyriar** [comment]
@nozzlegear could you get processexplorer and see what the process tree is before and after you quit? Is zsh5 getting orphaned for some reason? https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by nozzlegear** [comment]
I haven't used the process explorer before so let me know if there's something specific I should do. Here are screenshots of what it's showing while I reproduce this issue:

One VS Code instance open with Zsh terminal:

![image](https://user-images.githubusercontent.com/2417276/34391253-14644f5e-eb0a-11e7-84fc-64f7672d5a29.png)

Second VS Code instance open with Zsh terminal:

![image](https://user-images.githubusercontent.com/2417276/34391277-314247f2-eb0a-11e7-9337-5b8e9cc28903.png)

Closed the first VS Code instance, zsh process using around 25% CPU:

![image](https://user-images.githubusercontent.com/2417276/34391296-4a1d472c-eb0a-11e7-83bd-69696908090e.png)

If I'm reading this correctly, it looks like the second instance's zsh process, the one that's still open, is the one that goes crazy with CPU usage.

**Comment by Tyriar** [comment]
Well it looks like the problem is because the process is detached, even before you close the session. Is this the standard `zsh` executable? How did you install it? I'm guessing this is a WSL bug based on this.

**Comment by nozzlegear** [comment]
It's standard zsh as far as I know, it's installed via `apt-get` with `sudo apt install zsh`. I'm using `oh-my-zsh` with it. I'll note that my terminals also spawn detached zsh processes, but the terminal closes them fine. It's just VS Code that doesn't, but I'd be happy to file an issue with WSL for this.

**Comment by Tyriar** [comment]
@bitcrazed it appears `zsh` inside WSL is launching detached processes which are not being returned as "console processes" via the [`GetConsoleProcessList `](https://docs.microsoft.com/en-us/windows/console/getconsoleprocesslist) API. When a terminal in VS Code is killed we fetch the console process list and forcefully kill them here:

https://github.com/Tyriar/node-pty/blob/59a7d4357cb33a063a2bfbc745a0e614a4db1ca2/src/windowsPtyAgent.ts#L94-L99

**Comment by nozzlegear** [comment]
I've updated Windows to the latest insider build (17063) and this issue has gone away, so it does indeed some to be a problem with WSL that will be fixed in the next release. I'm not sure why it only affected VS Code and not my terminals, but now I can work without having to keep a task manager window open!
