### ISSUE TITLE
Debugging with chrome and vscode

### ISSUE THREAD

**Issue by weeco** [Microsoft/vscode#40833]
- VSCode Version: 1.19.1
- OS Version: Win10 x64

I am not able to attach with the chrome debug tools once the VSCode debugger is attached. If I start node manually with the correct parameters I am able to attach the Chrome debugger. I assume it's not possible to attach two debuggers simultatenously then, but how could I detach the VSCode debugger? (If I start without debugging, it won't set any parameters such as debug-brk and port).

**Steps to Reproduce:**
1. Launch application in VScode with "Start debugging" using the below pasted configuration. Check debug console to see on what ip and port the debugger is listening on.
2. Open chrome, visit "chrome://inspect", Devices -> Configure -> Add the ip and port printed in the debugger console at step 1 -> click done
3. Wait until the new Remote Target appears, click inspect and see that nothing will happen.

Reproduces without extensions: Yes

**My launch config:**

        {
          "type": "node",
          "request": "launch",
          "name": "Express server",
          "program": "${workspaceRoot}/src/index.ts",
          "outFiles": [
            "${workspaceRoot}/dist/**/*.js"
          ],
          "outputCapture": "std",
          "smartStep": true
        },

So what's the proper way to debug with chrome once I started my node application with VSCode: 

> Debugging with inspector protocol because Node.js v8.2.1 was detected.
> node --max-old-space-size=4096 --inspect-brk=10483 dist\index.js 
> Debugger listening on ws://127.0.0.1:10483/1ecd4817-f62c-4563-8467-44407f03d4a7

**Comment by auchenberg** [comment]
If you don't want to use VS Code as your debugger, you should consider using Tasks instead of `launch.json` to launch your Node process in debug mode.

You can read more about tasks here https://code.visualstudio.com/docs/editor/tasks
