### ISSUE TITLE
Add user snippets line in the cog button

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#40843]
Basically, a feature request:
https://stackoverflow.com/questions/47976988/how-to-add-user-snippets-line-to-the-settings-cog-in-vs-code

Should I rewrite everything to this post?

**Comment by dragfire** [comment]
@jrieken I would like to work on this.

**Comment by electriccode** [comment]
please review https://github.com/Microsoft/vscode/pull/41090, addresses #40483, cc @jrieken @Tyriar

**Comment by jrieken** [comment]
done via #41090
