### ISSUE TITLE
Duplicates in IntelliSense 

### ISSUE THREAD

**Issue by umnovI** [Microsoft/vscode#40846]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.1
sftp|lix|0.9.5
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0
code-settings-sync|Sha|2.8.7

---

Steps to Reproduce:

1. type 'func' in js editor (not only 'function' duplicates)
2. you'll see too many the same functions
![image](https://user-images.githubusercontent.com/30232564/34364747-de00a7a2-ea99-11e7-9e3a-3b5dbd342cb4.png)

In function description says: 'Automatic import from core-js...'

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
If all the `Function` entries are from separate packages / files, this is by-design. We show a suggestion for every unique, exported symbol found in your project.

You can disable auto-import suggestions by setting: `"typescript.autoImportSuggestions.enabled": false`
