### ISSUE TITLE
Release custom TSLint rules in tslint and/or tslint-microsoft-contrib?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#40845]
https://github.com/Microsoft/vscode/tree/master/build/lib/tslint

These are some useful rules! I'd love to see them added to other code bases. Can we triage which ones are:
* Completely internal to VS Code, and can't be genericized?
* Generic enough to release in tslint-microsoft-contrib, but too opinionated for TSLint?
* Generic & non-opinionated enough for TSLint?

**Comment by jrieken** [comment]
Hm, except for the 'no_duplicate_imports'-rule that are rather specific to our setup and the tools we are using... Tho having said that everyone can take inspiration from them

**Comment by joaomoreno** [comment]
We'll probably not invest in this... But the code is out there for people to use!

**Comment by JoshuaKGoldberg** [comment]
@joaomoreno why close the issue? I'd be happy to do all the work.

**Comment by joaomoreno** [comment]
@JoshuaKGoldberg That's pretty cool. If you actually extract the rules into separate entities, ping us for possibly adopting them.
