### ISSUE TITLE
I can´t write my personal settings

### ISSUE THREAD

**Issue by leandro-sds** [Microsoft/vscode#40840]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

I'm trying to change the editor font family and I can't write the new font family in the right area

**Comment by leandro-sds** [comment]
Yes. But now is working. Some days later I tried again and changed the font

**Comment by sandy081** [comment]
Thanks. Closing it as it is working.

Please reopen it when you see it again, with necessary steps to reproduce.
