### ISSUE TITLE
C++: Syntax highlighting is off when combining digit separator and user-defined literal

### ISSUE THREAD

**Issue by cjdb** [Microsoft/vscode#40847]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|0.9.1
cpptools|ms-|0.14.5
shader|sle|1.1.2
cmake|twx|0.0.17

---

Steps to Reproduce:

1. Visit https://twitter.com/cjdb_ns/status/945780226944061440 for a visual
2. Launch a C++ project
3. Use a user-defined literal _and_ the digit separator (e.g. `1'000_nm`).

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
