### ISSUE TITLE
[Suggestion] remember the last input words in command palette.

### ISSUE THREAD

**Issue by midGitub** [Microsoft/vscode#40853]
[Suggestion] add a function to remember the last input words in command palette. and can change this option in setting.json

**Comment by shobhitchittora** [comment]
@midGitub Code already remembers the last used (`recently used`) command in the palette.
<img width="630" alt="screen shot 2017-12-27 at 10 33 10 am" src="https://user-images.githubusercontent.com/4711855/34371236-7881978a-eaf1-11e7-932a-66ff10c8ec17.png">

Not sure how remembering just the last entered text would help anything?

**Comment by midGitub** [comment]
the last entered text will filter the commands, and no need to type again when i am finding some command .just a suggestion.

**Comment by bpasero** [comment]
`"workbench.commandPalette.preserveInput": true`
