### ISSUE TITLE
TS syntax highlight regression

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#4085]
A lot of my code written in TS is wrongly syntax highlighted in the latest release:

<img width="179" alt="screen shot 2016-03-13 at 18 02 42" src="https://cloud.githubusercontent.com/assets/1324476/13728062/cc0da920-e945-11e5-820c-b1ed6b409c31.png">

**Comment by aeschli** [comment]
@tinganho Can you give me some more information:
- What version are you?
- What theme are you using?
- Are you sure this is with TypeScript (not JavaScript).
- Can you add the code snippet here?

**Comment by tinganho** [comment]
@aeschli I'm in version `code@0.10.11 #f291f4ad600767626b24a4b15816b04bee9a3049`

And I'm using `typescript@1.9.0-dev.20160313`.

It seem to only affect tsx files.

```ts
'use strict';

import { Topics } from './Topics';
import { Topic } from './Topic';
import {
    Element,
    ContentComponent,
    DOMElement,
    PageInfo,
    Collection,
    autobind,
    HTTPResponse,
    ErrorResponse,
    TimedCallback
} from '../Library/Index';
import {
    SubmitButton,
    FormMessage,
    ImageCrop,
    ConfirmDialog,
    ToogleButton
} from '../Components/Index';

interface TopicsProps {
    name: string;
}

function getAddButton(id: string) {
    return (
        <div ref='addButton' id={id} class='AddButton'>
            <div class='AddButtonVertical'/>
            <div class='AddButtonHorizontal'/>
        </div>
    );
}

interface FileReadResult extends File {
    result: string;
}

interface FileEventTarget extends EventTarget {
    files: FileReadResult[];
}

interface FileChangeEvent extends Event {
    target: FileEventTarget;
}

interface FileReadEventTarget extends EventTarget {
    result: string;
}

interface FileReadOnloadEvent extends Event {
    target: FileReadEventTarget;
}
```

**Comment by aeschli** [comment]
Thanks for the clarification. This is #3903 (applies to both JS and TSX)

**Comment by aeschli** [comment]
@tinganho We delivered a fix in a update last Monday. Please update your VS Code installation. Thanks!

**Comment by tinganho** [comment]
This issue doesn't appear to be fixed yet.

```ts
import { Element, ContentComponent, PageInfo, Data, autobind, DOMElement, RequestInfo } from '../Library/Index';
import { SocialNetworkLinksView } from './SocialNetworkLinksView';

interface MenuItemInfo {
    text: string;
    link: string;
    ref: string;
}
```
The interface above is not highlighted correctly in a tsx file.
