### ISSUE TITLE
Windows 10 version 10.0.162999 hangs a lot whenever I fire up vscode

### ISSUE THREAD

**Issue by ace411** [Microsoft/vscode#40856]
- VSCode Version: 1.19.1
- OS Version: Windows 10 version 10.0.162999

Steps to Reproduce:

1. Restart my computer
2. Change the directory in which I am working

Reproduces without extensions: Yes/No

Hello. I just downloaded version 10.0.162999 of Windows 10. The OS ran smoothly when I was working on one PHP project in vscode and hung when I ran a few git commands on another PHP project in the same text editor. Below are the screenshots of the disk usage spikes vscode created:

![vscode3](https://user-images.githubusercontent.com/11040337/34372297-c436a3a8-eae4-11e7-9619-9fb0dc85535e.JPG)
![vscode](https://user-images.githubusercontent.com/11040337/34372301-cca23160-eae4-11e7-9341-5d16caec9573.JPG)

**Comment by Tyriar** [comment]
Your disk can only handle 0.4MB/s? Do you know what sort of hard drive you have? Also have you had similar disk max out issues in other programs?

**Comment by ace411** [comment]
I have a TOSHIBA MQ01ABD100 hard disk with the following specifications: 512 Bytes/Sector, 931.51 GB size, 121,601 cylinders, and 1.953 million sectors. And, no, I do not experience much disk difficulty with other programs.

**Comment by Tyriar** [comment]
Have you tried running with `code --disable-extensions`?

**Comment by ace411** [comment]
Not yet. I have, however, disabled the PHP Intellisense extension. Everything seems to be working fine. Thank you so much.

**Comment by Tyriar** [comment]
Great 😃 

FYI @felixfbecker
