### ISSUE TITLE
Allow to hide TypeScript declaration files conditionally

### ISSUE THREAD

**Issue by DusterTheFirst** [Microsoft/vscode#40850]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
discord-vscode|icr|1.5.1
code-beautifier|mic|1.7.2
LiveServer|rit|3.0.2
vscode-hexdump|sle|1.6.0

---

### Steps to Reproduce:

1. Add `"**/*.d.ts": { "when": "$(basename).ts" },` to `files.exclude` in your `User Settings`
2. See all `.d.ts` files disappear, even without a sibling .ts file

### Probable cause:
`filename.d.ts`'s `$(basename)` is `filename.d`, not `filename`
therefore, `$(basename).ts` matches itself, because `filename.d` + `.ts` = `filename.d.ts`
  

**Reproduces without extensions**: Yes

**Comment by nicojs** [comment]
Understandably out-of-scope (probably a lesser known feature), but I believe this would be helpful. Anyone reading this that thinks the same way, please keep up-voting so @DusterTheFirst can ask reopen this issue.

**Comment by SomaticIT** [comment]
👍

**Comment by forivall** [comment]
I took a brief look into what it would take to fix this, and i can think of 2 solutions:
1. (easy) Add an extra property to the `when` clause, so it would read `"**/*.d.ts": { "when": "$(basename).ts", "ext": ".d.ts" }`, or
2. (hard) Infer the extension from the glob itself in the glob parsing function.
