### ISSUE TITLE
The `Ctrl + ñ` keyboard shortcut works in Microsoft Windows versions 8, 10, but in Ubuntu it does not work.

### ISSUE THREAD

**Issue by juliandavidmr** [Microsoft/vscode#40854]
The `Ctrl + ñ` keyboard shortcut works in Microsoft Windows versions 8, 10, but in Ubuntu it does not work. *This shortcut opens the command terminal.*

- VSCode Version:  1.19.1
- OS Version: Ubuntu 17 _`(4.13.0-21-generic)`_

Steps to Reproduce:

1. Ctrl+ñ

Reproduces without extensions: Yes/**No**

**Comment by alexandrudima** [comment]
@juliandavidmr When you run VSCode in Ubuntu,
* do you sit physically at the Ubuntu machine which runs natively on the hardware you are sitting at? (or are you using a VM or some form of remote desktop connection)
* what keyboard layout have you configured
* what shortcut is displayed next to `F1 > View: Toggle Integrated Terminal` by VS Code. Does pressing that shortcut execute the action or not?

Finally, have you tried our keybinding troubleshooting page for Linux -- https://github.com/Microsoft/vscode/wiki/Keybinding-Issues
