### ISSUE TITLE
Problem with tsc and tasks

### ISSUE THREAD

**Issue by mhallak** [Microsoft/vscode#40868]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Follow: https://code.visualstudio.com/docs/editor/tasks  - TypeScript Hello World
2. In details: mkdir mytask; cd mytask; tsc --init; code .
3. Create HelloWorld.ts:
class Startup {
    public static main(): number {
        console.log('Hello World');
        return 0;
    }
}

Startup.main();
4. When you Ctl+Shift+B, there is the following error:
```
Executing task: tsc -p "/home/robil/test/csharp++/mytask/tsconfig.json" <

/usr/lib/nodejs/typescript/tsc.js:37290
            var jsonOptions = json["compilerOptions"];
                                  ^

TypeError: Cannot read property 'compilerOptions' of undefined 
```
5. If you run from terminal: 
`tsc -p "/home/robil/test/csharp++/mytask"`, everything is OK.

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
@mattbierner does that ring a bell. This is the contributed TypeScript tasks. I thought I ask before I start investigating if this is a task execution engine problem.

**Comment by dbaeumer** [comment]
I tried it under Windows and I get

```
error TS18003: No inputs were found in config file 'p:/mseng/VSCode/Playgrounds/bugs/myTask/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.
```

which seems correct using tsc version 2.6.2
