### ISSUE TITLE
When coding in java CANNOT type Chinese words

### ISSUE THREAD

**Issue by TolemyW** [Microsoft/vscode#40860]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
xml2json|bui|0.2.1
mavensmate|Dav|0.15.0
githistory|don|0.2.3
xml|Dot|1.9.2
unicode-normalizer|esp|0.0.1
git-project-manager|fel|1.4.0
code-runner|for|0.8.6
CppSnippets|har|0.0.13
Go|luk|0.6.70
vscode-fileheader|mik|0.0.2
vscode-clang|mit|0.2.2
mssql|ms-|1.3.0
python|ms-|0.9.1
cpptools|ms-|0.14.5
PowerShell|ms-|1.5.1
vscode-docker|Pet|0.0.22
java|red|0.16.0
vscode-icons|rob|7.19.0
python|tht|0.2.3
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.11.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  create a.java file
2.  type some chinese words like 中文
3.  after saving this change it will turn the messy 
4.  change the **file.autoSave** from **autodelay** to **off**
5.  change the **file.autoSave** back

**all will be right**

Reproduces without extensions: Yes/No

**Comment by rcjsuen** [comment]
So this only applies to Java files? If you create a `a.txt` file, the bug doesn't occur?

**Comment by Tyriar** [comment]
I suspect this is related to encoding, @alexandrudima should know more.

@TolemyW what does the encoding part on the right side of the status bar say? In the below it's "UTF-8"

<img width="328" alt="screen shot 2017-12-27 at 3 15 50 pm" src="https://user-images.githubusercontent.com/2193314/34395868-f0e2fcc4-eb18-11e7-9874-a048666500a7.png">
