### ISSUE TITLE
Global var declarations not being autocompleted from ATA

### ISSUE THREAD

**Issue by ferdaber** [Microsoft/vscode#40867]
It seems that the automatically-acquired types for Jest, which declares global variables and namespaces, are not working in autocomplete. I can confirm that the Jest types are downloaded into this directory ~/Library/Caches/typescript/2.6/node_modules/@types/jest/index.d.ts.

A snippet of the vars that are not being autocompleted:
```ts
declare var beforeAll: jest.Lifecycle;
declare var beforeEach: jest.Lifecycle;
declare var afterAll: jest.Lifecycle;
declare var afterEach: jest.Lifecycle;
declare var describe: jest.Describe;
declare var fdescribe: jest.Describe;
declare var xdescribe: jest.Describe;
declare var it: jest.It;
declare var fit: jest.It;
declare var xit: jest.It;
declare var test: jest.It;
declare var xtest: jest.It;
```

`describe` not working:
![image](https://user-images.githubusercontent.com/12239873/34384386-e5a0cd98-eae9-11e7-8f16-af349e056198.png)

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
copy-relative-path|ale|0.0.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
gitlens|eam|7.1.0
prettier-vscode|esb|1.0.1
file-icons|fil|1.0.7
auto-close-tag|for|0.5.5
search-node-modules|jas|1.2.0
docthis|joe|0.6.0
vscode-styled-components|jpo|0.0.10
vscode-language-babel|mgm|0.0.10
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|0.9.1
debugger-for-chrome|msj|4.0.0
typescript-hero|rbb|1.8.0
open-in-browser|tec|1.1.0
markdown-all-in-one|yzh|0.11.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Add Jest as a dev dependency in package.json
2. Create a new JS module, and start typing in the jest globals (`describe`, `it`, etc...)

Reproduces without extensions: Yes

**Comment by ferdaber** [comment]
I should note that this does work if I manually install `@types/jest` into my project's own node_modules directory.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20975
