### ISSUE TITLE
Colour dialog box doesn't open on html files

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#40862]
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:27:29.385Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-markdownlint|Dav|0.12.0
EditorConfig|Edi|0.11.1
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
prettier-vscode|esb|1.0.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
vim|vsc|0.10.6
markdown-pdf|yza|0.1.7

(2 theme extensions excluded)

---

Steps to Reproduce:
![screen shot 2017-12-27 at 5 07 18 am 2](https://user-images.githubusercontent.com/439226/34378548-4caba2b8-eac4-11e7-9616-efdd543a8020.png)
1. Open html document
2. Hover over a colour box

Colour selection dialog does not show.

Reproduces without extensions: Yes

**Comment by rajinder-yadav** [comment]
In this case the file extension was '.scss'

**Comment by rajinder-yadav** [comment]
Correction this works, but only when you hover over the colour name or value. I recall it also worked when I hover over the colour box, and now it does not.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/40634 which is the earliest one, thanks all for your feedback.
