### ISSUE TITLE
VS Code doesn't show credential window for GitHub when using GitHub Desktop's git install

### ISSUE THREAD

**Issue by u2berggeist** [Microsoft/vscode#40872]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
code-runner|for|0.8.6
python|ms-|0.9.1
code-settings-sync|Sha|2.8.7

---

Steps to Reproduce:

1. Set `git.path` to the `git.exe` found through a GitHub Desktop install
2. Attempt a push from a repository

So in the [VS Code Version Control: Common Questions](https://code.visualstudio.com/docs/editor/versioncontrol#_common-questions) it states that you can use the `git.exe` that is automatically installed with GitHub Desktop. While the system was able to pull data from a GitHub repo through VS Code, it was never able to Push updates successfully. When you asked VS Code to push (or any other command involving push), it would simply hang (the Git Output window in VSC would simply have `git push` and nothing else). If I went through Git directly or through GitHub Desktop, it pushed perfectly fine, but it would not work through VS Code. After I installed Git in an independent installation, selecting push from inside VS Code finally came up with a credential window and pushed fine. Before the independent installation, a credential window never came up.

All my issues are resolved, but I figured I let you know of the issue I encountered. I believe the issue lies in the credential window not showing up (and thus not letting me login to push). 

Reproduces without extensions: Did not check

**Comment by joaomoreno** [comment]
VS Code simply doesn't support GitHub's Desktop's git. Thanks for your information.

**Comment by u2berggeist** [comment]
Welcome. Are there plans to correct the Common Questions answer? Because I was just going off of that.

**Comment by joaomoreno** [comment]
Oh thanks for pinging on that, I missed it! I've fixed the docs: https://github.com/Microsoft/vscode-docs/commit/726b040dccad4ec0e06040b479ff91414a42ad36

**Comment by u2berggeist** [comment]
Welcome!
