### ISSUE TITLE
Intellisence not working

### ISSUE THREAD

**Issue by blinkspark** [Microsoft/vscode#40879]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.5.5
materialize-snippets|len|1.2.2
python|ms-|0.9.1
LiveServer|rit|3.0.2

---

Steps to Reproduce:

1.create a new folder and init with npm init
2.open whith code
3.reqire a node module
4.Intellisence not working (projects that already exists before I upgrade to this version works fine)
![codeissue](https://user-images.githubusercontent.com/3829294/34397341-5e8dfda4-ebb0-11e7-9247-c29a883e0eea.PNG)

Reproduces without extensions: Yes

**Comment by blinkspark** [comment]
My workding directory is : "D:\Development\Node".
I installed a new module useing npm and the Intellisence of that module is ok
And this is my settting
![tim 20180101135204](https://user-images.githubusercontent.com/3829294/34465818-fbb885a2-eefa-11e7-844e-1f4dee0740fc.png)

**Comment by blinkspark** [comment]
I left vscode open for a long time(3 hours?) and it works fine now.
Is that the problem?

**Comment by mjbvz** [comment]
@blinkspark So it is working now? If not, can you please try manually installing the node typings by running `npm install --save-dev @types/node` in your workspace

**Comment by blinkspark** [comment]
Yeah, but it appears randomly,when I create a new project.
Install types/node solve this issue.
Seems vs code sometimes won't install typings automatically. 
@mjbvz do you need me to close this issue?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20988
