### ISSUE TITLE
GIT on Large Projects not working in GUI

### ISSUE THREAD

**Issue by carstengrimm** [Microsoft/vscode#40873]
I am running GIT successfully on several project folders but for one project it is not recognized by vscode.

![poly_-_visual_studio_code_2017-12-27_22-39-53](https://user-images.githubusercontent.com/5014509/34394024-fccec5ac-eb56-11e7-9f12-83b81840af64.jpg)

I have set a custom path towards my portable installation of git in settings which has been working for other projects as well:

```
"git.path": "C:\\Portableapps\\PortableApps\\PortableGit\\bin\\git.exe"
```

_It also seems to be the case that git is recognized as within the terminal window it'll show the git version._
EDIT: But i guess my terminal is external, since i have also set a remote cmder...

![new_issue_ _microsoftvscode_-_firefox_developer_e_2017-12-27_22-40-00](https://user-images.githubusercontent.com/5014509/34394863-91376e74-eb5c-11e7-9406-9fc5aae7e646.jpg)

when manually using git commands via terminal such as 

```
git push origin master 
```
it seems to recognize these ocmmands as well.
but in the git/scm section it seems nothing is recognized.
when doing coding there is no highlighting for changes, and nothing i am used to.

this certain project only difference is that it includes several thousand image files which i tried to exclude in .gitignore. there's nothing like any error log whatsoever. when manually doing git commands, i also tried deleting the .git folder to restart from scratch, but it still does not seem to recognize anything.

![visual_studio_code_2017-12-27_23-14-26](https://user-images.githubusercontent.com/5014509/34394759-b0a933ba-eb5b-11e7-8047-abac8de731a7.jpg)

Windows 10 64 Bit

Steps to Reproduce:

1. Have huge project
2. Setting git path
3. check git panel where git is not recognized

Reproduces without extensions: Yes
Running without extensions does not change anything.

As mentioned before. Other projects seem to work fine on the same configuration.

**Comment by joaomoreno** [comment]
How long does `git status` take to execute in this workspace?

Is there anything different about this project other than having large images? Is it in a network share, etc?

**Comment by carstengrimm** [comment]
I've run git status and it showed the result (of changed commits) almost instantly. (remote terminal though)

I also removed my .git folder to reinitialize the whole project, as well as removing the huge file colletion of pictures. So this project is pretty much the same as all others with roughly 150 mb 5000 files 

- yet the built-in functions do not seem to recognize anything. 
- changing a file does still not show within sources tab
- source tab still wants to be setup, does not recognize git

being inside a terminal window with git functions do seem to recognize the master branch and stuff though.

all other projects (opened with "open folder") with identical setup seem to be working without a problem....

**Comment by joaomoreno** [comment]
What does _ remote terminal_ mean?

**Comment by critesjm** [comment]
I've been having this problem for a few weeks now too. I don't know if it's _caused_ by a large repo but I can say my largest repo is the one that I see the problem while working in. `git status` and pretty much every other git command run perfectly fast in the terminal (both integrated and external). This problem is relatively recent as I've been using VS Code on this codebase for around a year now and have only seen the slowdown with git recently. If it helps, I've also noticed a huge slowdown in TS activating/parsing/whatever (hover tooltips just say "loading..." forever and I get no intellisense) and when trying to save files. Usually I see two or more of these symptoms at the same time.

**Comment by joaomoreno** [comment]
@carstengrimm What does remote terminal mean?
