### ISSUE TITLE
No Insiders update on Windows since Dec 21

### ISSUE THREAD

**Issue by will-l-h** [Microsoft/vscode#40871]
Version 1.20.0-insider
Commit f9115349ef09cfef2bed669680d10ac58b490dce
Date 2017-12-21T16:36:58.030Z

Checking for updates says none available.

**Comment by usernamehw** [comment]
Maybe because there is none?

**Comment by will-l-h** [comment]
Could be, but there have also been a couple issues this year that prevented updates (one was a cert issue, don't know what caused the other).

**Comment by usernamehw** [comment]
Well, it's holidays, there weren't much commits these days.

**Comment by Tyriar** [comment]
We've disabled daily insiders until after new years as team attendance is a little patchy.
