### ISSUE TITLE
Visual Studio configured itself to use GIT as source control after update, then checking into Source Control deleted all my solutions contents.

### ISSUE THREAD

**Issue by jhodges13** [Microsoft/vscode#40878]
- VSCode Version: Visual Studio 2017, latest updates as of today 12-27-2017
- OS Version: Windows Server 2008R2

Steps to Reproduce:

1. Applied an update to Visual Studio, it unexpected changed my source control from TFS to GIT

2.Tried to add a prototype solution to source control (something I had been working on a week), when I noticed it was trying to check into GIT I undid it to try to use TFS instead.

3. This deleted a lot of code that I had been working on for a week. I have no desire at all to use GIT, we use TFS for everything, and it's confusing to me why the application would suddenly configure itself to GIT and then the workflow of undoing that check-in would lead to having my code deleted. 

4. Can you tell me how to look at the default GIT repository for my code? I didn't configure it so I have no idea where it lives or how it works. This is a very dangerous feature.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
This repository is about VS Code, not Visual Studio. https://stackoverflow.com/questions/30527522/what-are-the-differences-between-visual-studio-code-and-visual-studio
