### ISSUE TITLE
node does not fork process correctly when Node.js project code run with F5

### ISSUE THREAD

**Issue by eljamaki01** [Microsoft/vscode#40875]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1
debugger-for-chrome|msj|4.0.0

---

Steps to Reproduce:

1.Have Node LTS version 8.X installed
2.Create a node project and have the following lines
```javascript
var cp = require('child_process'); // Forking a separate Node.js processes
var node2 = cp.fork('./worker/app_FORK.js');
node2.send({ msg: 'REFRESH_STORIES', doc: result.value });
```
3. The first thing you notice is that if you look in task manager, you do not see the node processes running and the send() function errors saying that it was closed.

If you run with <ctrl>F5 it works.
You see in Resource Monitor the two node.exe processes running. The parent and the forked child.

Reproduces without extensions: Yes/No

**Comment by weinand** [comment]
A 'fork' passes the command line arguments of the parent to the child. Since the parent is configured for debug mode with something like `--inspect-brk=5858` the child receives the same. This results in some "port already in use" error. And because `--inspect-brk` is used, the child process waits for the debugger to attach, so it does not start up.

See https://stackoverflow.com/questions/16840623/how-to-debug-node-js-child-forked-process

**Comment by eljamaki01** [comment]
I miss-typed something originally. I corrected it.
If you run with CTRL-F5 it works. F5 does not work.
I am not trying to debug the fork, just get it to launch at this point.
My console.log statements in the forked code only print when I start with CTRL-F5.
F5 does not seem to work right, the fork is not happening.

**Comment by weinand** [comment]
"F5" launches your program (the parent process) with the "--inspect-brk" flag. Your program calls "fork" which passes the identical "--inspect-brk" flag to the child process.

An "--inspect-brk" stops the program on entry and waits for a debugger to attach. In your case the VS Code debugger attaches to your program successfully but no debugger attaches to the child process. So the child process is stopped and cannot continue.

If you only want to debug the parent process make sure that no "--inspect-brk" flag is passed to the child process.

"CTRL-F5" just **runs** the program without debugging. In this case no "--inspect-brk" flag is passed to your program and "fork" has nothing to pass to the child process.

**Comment by eljamaki01** [comment]
I tried the folllowing with F5 and still do not see that the child process is running:
var node2 = cp.fork('./worker/app_FORK.js', [], { execArgv: ['--inspect=9229'] });

**Comment by eljamaki01** [comment]
BTW, this use to work for me in the past and just stopped working recently about the time I updated to Node version 8.9.3
