### ISSUE TITLE
I can not use Template strings in vscode.

### ISSUE THREAD

**Issue by igkim** [Microsoft/vscode#40888]
- VSCode Version: 1.19.1
- OS Version: Window10

Steps to Reproduce:
1. Use typescript@2.6.2.
2. Use the ECMA6 template string syntax.
The code is as follows.

Reproduces without extensions: Yes/No

```
import { Injectable } from '@angular/core';
import { LANG_INFO } from './langInfo';


@Injectable()
export class LangSupportService {

  langCode = 'ko';
  private welcomMsg;
  constructor() {

  }
  
   getWelcomMsg(userName :  string){

      const langData = LANG_INFO.find(sellang => sellang.code === this.langCode);     
      return '${greetingMsg}, ${userName}!';  // $ {} does not work.  
       //$ {greetingMsg}, $ {userName}! The shape is displayed in the browser as it is.

   }

}
```

**Comment by Kirides** [comment]
As far as my googling brought me:

The Templating Syntax requires Backticks (`) instead of regular ticks (')

ex.: `string text ${expression} string text`  
(source: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings)

**Comment by igkim** [comment]
Thank you very much. ^^
