### ISSUE TITLE
High memory usage of gpu-process.

### ISSUE THREAD

**Issue by shinima** [Microsoft/vscode#40886]
- VSCode Version: 1.19.1
- OS Version: Windows 10 1709
- Screen Resolution: 3840 * 2160

Steps to Reproduce:

1. Open any folder and open the integrated terminal
2. Maximize the panel size of terminal
3. Type some commands until there is a scrollbar on the right
4. Try to use the mouse wheel to scroll the terminal many times

Reproduces without extensions: Yes

Reproduces with powershell: Yes

![high-memory-usage](https://user-images.githubusercontent.com/5550931/34401612-4e11fd82-ebd7-11e7-87ca-f538fe5ce1d8.jpg)

![status](https://user-images.githubusercontent.com/5550931/34401627-5f3ba388-ebd7-11e7-8cc5-cdc5674404c5.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/40502
