### ISSUE TITLE
VS Code c++ code navigation hangs forever if you once click on a function it cannot find

### ISSUE THREAD

**Issue by lamerman** [Microsoft/vscode#40887]
Suppose you have a c++ project. You click once with CTRL to the function (to navigate to its definition) that it cannot find and then navigation hangs forever and does not work anymore until you restart VS Code. Maybe timeout would be a good option, or ability to search in parallel. If one search hangs, you still can perform the other.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
python|ms-|0.9.1
cpptools|ms-|0.14.5

---

Steps to Reproduce:

1. Try to go to definition of some function that VS Code cannot find. Press CTRL and then click to that function.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
