### ISSUE TITLE
Extensions icon has dissapeared

### ISSUE THREAD

**Issue by dixon13** [Microsoft/vscode#40885]
The extensions button has disappeared for me. I just opened up my VS Code and it was gone. The day before, the extensions icon was there but now it is not there. I have found a way to view the extensions page by clicking on one of the links in the customize section on the welcome page. When I do this, the extensions icon returns and I can manage my extensions. I can also view the extensions page by using the command palette.

![image](https://user-images.githubusercontent.com/7998881/34401390-0510e8e8-eb58-11e7-9aac-7b2b130dec02.png)

**- VSCode Version:** 1.19.1
**- OS Version:** Windows 10 64-bit

**Steps to Reproduce:**
No steps to reproduce. Just happen to open up my VS Code today and my extensions button was gone.

**Reproduces without extensions:** Yes

**Comment by ofmyice** [comment]
yes,i also have this problem too.

**Comment by WilfriedMaris** [comment]
We had the problem too with the latest update of VSC. Just right click in the sidebar to enable the button again.

**Comment by bpasero** [comment]
Yes, you can bring the icons back from the context menu on the bar:

![image](https://user-images.githubusercontent.com/900690/34405302-e2303ca6-ebb2-11e7-9e17-2129a2e628ce.png)


This issue is fixed meanwhile in insiders. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dixon13** [comment]
Thanks for the quick responses. Didn't know there was a context menu for that. I'm still learning about VS Code even after using it for a year lol
