### ISSUE TITLE
quickopen and search command  doesn't work

### ISSUE THREAD

**Issue by shunjinchan** [Microsoft/vscode#40884]
- VSCode Version: 1.19.1
- OS Version: macOS High Sierra

Steps to Reproduce:

1. `cmd + p`, type `filename.**`
2. cannot find `filename.**` in `./src` and `./dest`

[![](https://ws2.sinaimg.cn/large/006tNc79gy1fmwedg4tnuj311a0zan14.jpg)](url)

- Reproduces with extensions: Yes
- Reproduces without extensions: Yes

**search.action.focusActiveEditor** had the same problem. But they were working normally on the vscode 1.18.1

**Comment by roblourens** [comment]
Do you have any `file.exclude` or `search.exclude` settings  that could impact this? Can you run a search that should find a result in that config.js, and show the output of the search output pane?

![image](https://user-images.githubusercontent.com/323878/32013959-89edf3e4-b971-11e7-8f3d-9f4b4b7790e9.png)

**Comment by shunjinchan** [comment]
@roblourens 

1.

![](https://ws3.sinaimg.cn/large/006tNc79gy1fmwhs97q07j30vk0ag0te.jpg)
![](https://ws3.sinaimg.cn/large/006tNc79gy1fmwhsibustj30n40e0gmz.jpg)

`./src` and `./dest` folders are not exclude.

2. 

Search `modules/site-info` 

![](https://ws1.sinaimg.cn/large/006tNc79gy1fmwi33jgrkj31kw0v0154.jpg)

Search `modules/site-info` with `./src`, 5 `modules/site-info` were found

![](https://ws3.sinaimg.cn/large/006tNc79gy1fmwipsboeaj31kw0ue13y.jpg)

I think search `modules/site-info` in project root path, 1 `modules/site-info` was found because `./src/core/config.js` was open. It's really weird.

My English is very poor, hope you can understand it. 😂

**Comment by shunjinchan** [comment]
@roblourens 

I found another strange problem, use the same workspace settings, `quickopen` and `search.action.focusActiveEditor` work normally. Maybe this is the problem of my project, not the bug of vscode.

**Comment by shunjinchan** [comment]
@roblourens 

I found the cause of this problem.

The project (A) is the submodule of another project (B), and the `.gitignore` file of B project had `/static/src` and `/static/dest` configuration. so vscode exclude these two folders.

**Comment by roblourens** [comment]
Thanks for the investigation - you can also set `"search.useIgnoreFiles": false` to disable using gitignore files.

**Comment by roblourens** [comment]
I think it's confusing to use .gitignore files from parent directories... I will push a fix to not do that.
