### ISSUE TITLE
Color schemes need to assure contrast

### ISSUE THREAD

**Issue by BobFrankston** [Microsoft/vscode#40883]
- VSCode Version:  1.19.1
- OS Version: W10

Steps to Reproduce:

1. Set a color scheme with a white background
2. Use Gulp

Message are white on white ...

Reproduces without extensions: Yes/No yes

**Comment by BobFrGit** [comment]
Just tried the terminal with a dask blue background -- gulp messages are still invisible. So not sure what is going on.

**Comment by Tyriar** [comment]
Do you have a custom theme in cmd.exe set in properties?

**Comment by BobFrGit** [comment]
I just tried the default light and dark themes and the results were the same - I didn't see the gulp error messages. So something else is wrong. I ran the same gulp command in a regular command window and got (blue background) and it worked fine. So it's not the color scheme per se. Ideas? Note that if I copy the text to the clipboard and paste into another editor it's all there -- just invisible in VSCode.

This is standard powershell but I also tried cmd (by typing cmd to get a command subwindow)

![image](https://user-images.githubusercontent.com/5490484/34427174-3402e128-ec0d-11e7-9dae-15acd44776e7.png)

**Comment by Tyriar** [comment]
I mean the theme inside cmd.exe:

1. Launch cmd.exe (outside of VS Code)
2. Right click on the title bar and select properties
3. Find the color options

**Comment by BobFrGit** [comment]
I'm not sure what you are looking for -- the colors work fine outside of VSCode. It seems gulp-specific. I just tried using the task "browserify app.ts -p [ tsify ] -o bundle.js" and it worked fine reporting errors in grey on the the white background.

**Comment by Tyriar** [comment]
@BobFrGit I know the colors work fine, but it could be related to using non-standard colors in cmd.exe due to the way [winpty](https://github.com/rprichard/winpty) works.

**Comment by BobFrGit** [comment]
If so then something is strangely broken since the text doesn't show if I dark background and if I have a light background.

**Comment by jaredly** [comment]
iTerm2 has a "minimum contrast" setting which is invaluable to making sure that all text shows up, regardless of color scheme / background color.
![image](https://user-images.githubusercontent.com/112170/41439441-098a62fe-6fe8-11e8-9810-c7c46c356cfd.png)

For example, the text to the right is basically unreadable, unless I select it, in which case it becomes marginally readable.
![image](https://user-images.githubusercontent.com/112170/41439475-3206254c-6fe8-11e8-9347-48b0270f63cd.png)

**Comment by jaredly** [comment]
brought over to xterm, which is I guess what vscode uses? https://github.com/xtermjs/xterm.js/issues/1514

**Comment by Tyriar** [comment]
Let's track this in https://github.com/xtermjs/xterm.js/issues/1514, each theme should handle their own contrast. Also for Windows specifically that is due to winpty in https://github.com/Microsoft/vscode/issues/45693
