### ISSUE TITLE
Add support for emmet in JSX constructs inside .js files

### ISSUE THREAD

**Issue by StanShumsky** [Microsoft/vscode#4088]
Since Salsa support JSX in JS files, I would like to have emmet for JSX constructs inside (.js) files, as it works for (.jsx) files: Tab key to expand the abbreviation, class -> className filter.

**Comment by egamma** [comment]
In the March update the user can associate a .js file with JavaScript React (see below) and then you get emmet support in the .js file. 

![image](https://cloud.githubusercontent.com/assets/172399/13738811/b3a757a0-e9c7-11e5-972f-8bb7748f6f06.png)

A setting to enable emmet inside .js files doesn't make sense give the user can now associate files. 

Keeping the issue open until users can try out this approach.

**Comment by egamma** [comment]
Support for associating .js files with the JavaScript React language is now available - closing.
