### ISSUE TITLE
vscode python opencv problem 

### ISSUE THREAD

**Issue by aytacozkan** [Microsoft/vscode#40893]
- VSCode Version: 1.19.1
- OS Version: macOS High Sierra 10.13.2

vscode intellisense does not work properly and so slow especially with `opencv` as well as I cannot use `go definition` property.  

<img width="767" alt="screen shot 2017-12-28 at 12 12 45" src="https://user-images.githubusercontent.com/5284755/34406221-e4ac5d32-ebc8-11e7-952d-bb7953c1330a.png">

Reproduces without extensions: No
1. https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/issues
