### ISSUE TITLE
When building and running from source, Report Issue shows commit and date as unknown

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40895]
- VSCode Version: code-oss-dev 1.20.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Follow the steps on https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
2. Help > Report Issue
3. Notice commit and date.

EXPECTING: a non-unknown commit and date based upon when I built it and my repo

ACTUAL: unknown

**Comment by joaomoreno** [comment]
That's fine. That feature is only meant for the final product.
