### ISSUE TITLE
AutoSave Feature

### ISSUE THREAD

**Issue by afrcracks** [Microsoft/vscode#4089]
Please Visual Studio Code team bring the **autosave** feature back in Visual Studio Code. As it it is the essential feature for every programmer

**Comment by bpasero** [comment]
@afrcracks it is still there, what are you missing?

**Comment by weinand** [comment]
make sure to have this in your settings:

```json
"files.autoSave": "afterDelay"
```

**Comment by afrcracks** [comment]
Thanks it is now working good 😊
