### ISSUE TITLE
code.sh does not support command line parameters / interface

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#40894]
- VSCode Version: code-oss-dev 1.20.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Steps to Reproduce:

1. Follow the steps on https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
2. Try to execute the following command -

```
./scripts/code.sh --list-extensions
```

EXPECTING: shows extensions and doesn't load vscode

ACTUAL: loads vscode without showing extensions

**Comment by bpasero** [comment]
@joshunger `./scripts/code-cli.sh --list-extensions`

**Comment by joshunger** [comment]
I'm wondering if the documentation should be updated?  https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
