### ISSUE TITLE
Extensions inside a multi-root workspace. Do they work?

### ISSUE THREAD

**Issue by theodorDiaconu** [Microsoft/vscode#40897]
My plan is to use: https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete

Inside my project. All gut, I can, at workspace settings level define some pathMappings. But then I want some custom pathMappings inside a folder, in it's own folder settings.

It seems that those settings are completely ignored.

I want to know if this is a limitation of the extension or is there something extra that we need to do to enable folder configuration for our extensions ?

**Comment by bpasero** [comment]
Yes, please follow https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs
