### ISSUE TITLE
debug bug: cannot connect to runtime process

### ISSUE THREAD

**Issue by dotnetCarpenter** [Microsoft/vscode#409]
I sometimes get this cryptic error message: *Error cannot connect to runtime process (reason: [object Object])* when I launch the debugger. After I get it, I can not debug at all, until I have closed all open instances of VS code.

The main issue here seems to be that the error message is unreadable.

OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601
System Type	x64-based PC

![vscodedebugerror](https://cloud.githubusercontent.com/assets/43763/11318681/5580081c-905c-11e5-811b-bc685f39225a.png)

**Comment by weinand** [comment]
The unreadable error message has been fixed.

**Comment by dotnetCarpenter** [comment]
It seems to **not** have been fixed. Using VSCode 0.10.2 I get this:
![unreadable-error](https://cloud.githubusercontent.com/assets/43763/11472204/41fa85fe-976b-11e5-91ff-3d92ff4497f1.png)
![unreadable-error-version](https://cloud.githubusercontent.com/assets/43763/11472208/44b6fb56-976b-11e5-8944-9577f6a4c25b.png)

**Comment by natarajanmca11** [comment]
Hi, I am also facing the same issue if I turn off the wifi. I hope internet is not required to debug the source code. Please guide me.

**Comment by weinand** [comment]
@dotnetCarpenter the fix for the unreadable error message will appear in the December release

**Comment by weinand** [comment]
@natarajanmca11 If you see this problem on Windows then you are probably running into this node.js on Windows bug: node-inspector/node-inspector#645

**Comment by isidorn** [comment]
Verified that we now show a better error message
