### ISSUE TITLE
Operating system specific args don't override args defined in the task

### ISSUE THREAD

**Issue by tiagovcosta** [Microsoft/vscode#40905]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
python|ms-|0.9.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
cmake|twx|0.0.17

---

Using the task below:

```
{
            "label": "build test",
            "type": "shell",
            "options": {
                "cwd": "${workspaceRoot}/build/debug"
            },
            "command": "make",
            "args": [
                "-j", "8"
            ],
            "osx": {
                "command": "xcodebuild build",
                "args": ["oops"],
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error|fatal error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
            "group": "build"
}
```

If I run it on MacOS, the command `xcodebuild build -j 8 oops` is executed instead of the expected `xcodebuild build oops` (as described in [the docs](https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties))

Looks like platform specific args are being appended instead of overriding.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
Verified. Note that the above task will be run as `'xcodebuild build' oops` resulting a 'command not found: xcodebuild build' error.
