### ISSUE TITLE
after update to 1.19.1 git panel not showing

### ISSUE THREAD

**Issue by fenchu** [Microsoft/vscode#40900]
After update to v1.19.1 I need to press ctrl+shift+G to get git panel. I really miss the old where it showed all the time. I would have believed this as progress if it commited on save and autopushed to the git repo, but that is not the case. If I save and close folder and reopen it again. git panel is gone again.

Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Comment by bpasero** [comment]
@fenchu you can bring it back when you right click on the background where the view is and from the menu ensure that the view has a checkbox set. 

Alternatively, please use insiders where this issue is fixed. You can give our preview releases a try from: https://code.visualstudio.com/insiders/
