### ISSUE TITLE
Tab title control should drop actions and use commands instead

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#40910]
This would allow me to get rid of a lot of commands which are now only lying around because the tab title control needs them.
Here's an example [action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorActions.ts#L738)

**Comment by isidorn** [comment]
@bpasero do you want to look into this or I can also tackle it since I have cycles this milestone?

**Comment by bpasero** [comment]
@isidorn let me look into it and get back to you for help 👍

**Comment by isidorn** [comment]
@bpasero sounds good, thanks

**Comment by bpasero** [comment]
@isidorn pushed my changes, I could get rid of some actions but others are still being used for the tool bar in the open editors view.
