### ISSUE TITLE
Closing a tab closes entire application when running in Docker

### ISSUE THREAD

**Issue by ajhoekst** [Microsoft/vscode#40912]
- VSCode Version: 1.19.1
- OS Version: Debian 9.2 (Container) on Ubuntu 17.10 (Host)

Steps to Reproduce:
1. Build docker container with following Dockerfile
```
FROM library/debian:9.2

RUN apt-get update \
 && apt-get install -y \
        git \
        g++ \
        cmake \
        curl \
        libnotify4 \
        libnss3 \
        gnupg \
        libxkbfile1 \
        libgconf-2-4 \
        libsecret-1-0 \
        libgtk2.0-0 \
        libxss1 \
        libasound2 \
 && curl -o vscode-amd64.deb -L https://go.microsoft.com/fwlink/?LinkID=760868 \
 && dpkg -i vscode-amd64.deb \
 && apt-get purge --auto-remove -y curl \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /src/*.deb \
 && useradd -m vscode -s /bin/bash

USER vscode

ENTRYPOINT [ "code", "-w" ]
CMD [ "/home/vscode" ]
```
2. Run container with following command (change your-container-name and your-image-name)
`sudo docker run -it --net host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/snd --name <your-container-name> <your-image-name>`

3. Close a tab (e.g. the welcome tab or a newly created file)

Reproduces without extensions: Yes

**Comment by James226** [comment]
If you roll back to 1.18.1, this seems to work as expected.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
