### ISSUE TITLE
No 1.19.1 package available for el7 in the repo 

### ISSUE THREAD

**Issue by lig** [Microsoft/vscode#40919]
- VSCode Version: 1.19.0
- OS Version: Fedora release 27 (Twenty Seven)

Steps to Reproduce:

1. Install VS Code from yum repo, see https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
2. Open VS Code
3. Notice "New version available" notification
4. Click release notes
5. Notice 1.19.1 is the newly available version
4. Try to update using `dnf`
5. Notice 1.19.0 is the latest version available in the repo

Reproduces without extensions: Yes

**Comment by sryze** [comment]
I noticed this too. VSCode says that there is an update but I went to the site and followed repo install instructions for Fedora, and apparently there is no package for 1.19.1 yet.

**Comment by Tyriar** [comment]
Published, see https://github.com/Microsoft/vscode/issues/40972#issuecomment-354776671
