### ISSUE TITLE
Interactive playground: "error underline" unclear

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#40915]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Help / Interactive Playground

Under heading **IntelliSense**, the text reads:

> ... In the below example, position the text cursor ***in front of the error underline,*** right after the dot and press Ctrl+Space".   

It it unclear what *error underline* means, I don't see any underline or error.

**Comment by usernamehw** [comment]
```javascript
app.get('/', function (req, res) {
    res.send(`Hello ${req.}`);
//                       ^^[js] Identifier expected.
});
```
![error](https://user-images.githubusercontent.com/9638156/34423975-050acbb4-ec31-11e7-8add-2e71f8731fc3.png)

**Comment by usernamehw** [comment]
I can reproduce on the 2nd time:

1. Open playground
2. Close tab
3. Open playground
4. No errors shown & IntelliSense is not working

**Comment by BurtHarris** [comment]
Yes, opening playground a second time seems to be key to all the problems I was having with it.   Thanks.

**Comment by serialprimate** [comment]
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-22T06:14:07.615Z)
- OS Version: Linux x64 4.9.72-1-lts
- Extensions: none

Also happens every time for me in Interactive Playground with no extensions loaded w/ insiders on linux.

If restarting vscode repeatedly, sometimes syntax highlight also fails.

**Comment by martin-podlubny** [comment]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none

I just got VSCode for the first time, fresh install on macOS, and experienced the same issue with different features in the Interactive Playground described here by the peeps above. Don't have much to add in terms of describing/reproducing the issue, just posting here for completeness that the issue affects 1.19.1 on OSX as well.

**Comment by chrmarti** [comment]
@mattbierner I see this when opening without a folder. The missing errors also reproduce in an untitled file in JavaScript mode (code actions seem to work in this case). Code actions do not work in the interactive playground when the workbench is not open on a folder. Could you take a look?

**Comment by mjbvz** [comment]
Note that this still requires this upstream fix from TS (https://github.com/Microsoft/TypeScript/pull/21338)
