### ISSUE TITLE
Support npm auto detection

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#4091]
Hello,

It would be great to avoid creating or modifying a task in tasks.json file each time you update something.
I use nodejs with npm scripts in package.json (step1) and I need to create a task in tasks.json (step2) then add it in preLaunchTask (step3). I think step2 is not necessary in my case and I'm loosing time each time I update or create a new script in package.json.
So I think it would be necessary to avoid it when possible by specifying the tool needed in launch.json:

```js
"preLaunchTaskProvider":"npm",
"preLaunchTask": "run mynpmscript"
```

The preLaunchTaskProvider could be npm, gulp, grunt, jake or vscode(tasks.json), even shell (npm run clean && npm run build) ...

I hope this could improve vscode and help others.

Thanks in advance for your comments.

**Comment by isidorn** [comment]
I would need api from the task framework to support something like this, since I do not want to handle running tasks in the debug world. So forwarding to @dbaeumer first

**Comment by dbaeumer** [comment]
This should go away if we had auto detection support for npm modules in task land like we do for gulp.

**Comment by dbaeumer** [comment]
Dups #1777
