### ISSUE TITLE
Ctrl + p is not searching inside vendor folder in a laravel project in the vscode 1.19.1

### ISSUE THREAD

**Issue by carvemerson** [Microsoft/vscode#40918]
- VSCode Version: 1.19.1
- OS Version: linux Ubuntu 17.04

Steps to Reproduce:

1. Press Ctrl+p and try do find a file that is inside vendor folder in a laravel project

In the vscode version 1.18.* the Ctrl+p command works normally. But in the version 1.19 it is not working to find files inside vendor folder.

How can I fix it? Are there any configuration that I need todo?

Reproduces without extensions: Yes

**Comment by usernamehw** [comment]
```json
"search.useIgnoreFiles": false,// ?
```

**Comment by roblourens** [comment]
Is it in a gitignore file? If so you can tell vscode to not look at gitignore files by setting `"search.useIgnoreFiles": false` like @usernamehw says.

**Comment by carvemerson** [comment]
That's work for me! 
Thanks!!

**Comment by rufatZZ** [comment]
@usernamehw Thanks, maaan! :) It works :)
