### ISSUE TITLE
WSL/Ubuntu : Can't Run Build Task for GCC 7.2.0 Compiler.

### ISSUE THREAD

**Issue by sus007** [Microsoft/vscode#40922]
* Operating System and version: **Windows 10 Pro Insider Preview / Version: 1709 / OS-BUILD: 17025.1000**
* VS Code version: 
    * **Version 1.20.0-insider**
    * Commit f9115349ef09cfef2bed669680d10ac58b490dce
    * Date 2017-12-21T16:36:58.030Z
    * Shell 1.7.9
    * Renderer 58.0.3029.110
    * Node 7.9.0
    * Architecture x64
* C/C++ extension version: **Version 0.14.5: December 18, 2017**  
#### As you can see I've both versions of the GCC compiler installed, GCC 5.4 (Default) and GCC 7.2 (Newer), 
![image](https://user-images.githubusercontent.com/7630815/34403352-cb8344d6-ebcf-11e7-82d6-ac201a9139b5.png)  

#### But, still I couldn't **Run Build Task** with my GCC 7.2 from within my VSCode. 
![image](https://user-images.githubusercontent.com/7630815/34403448-6a8dd564-ebd0-11e7-9c31-1ee7dd3585c3.png)

#### My **`tasks.json`** file looks like this
![image](https://user-images.githubusercontent.com/7630815/34403513-bb09a2d4-ebd0-11e7-9762-57a0fe36f23e.png)

**Comment by sus007** [comment]
I've set `bash.exe` as my default terminal for VSCode. I can execute both of the commands `g++` & `g++-7.2` from my Ubuntu/Bash Terminal, but only `g++` command from within my VSCode. Why's that ?
> #### With only `g++` command in `tasks.json`
![image](https://user-images.githubusercontent.com/7630815/34424201-fae78ef6-ec49-11e7-9cef-3d28f416ad16.png)  

> #### With `g++-7.2` command in `tasks.json`
![image](https://user-images.githubusercontent.com/7630815/34424264-664cfbb8-ec4a-11e7-92e8-1f8cbddf7425.png)

> #### Both commands in `bash.exe`
![image](https://user-images.githubusercontent.com/7630815/34424412-727456ba-ec4b-11e7-81e7-a5831d3b0ba2.png)

**Comment by dbaeumer** [comment]
Dups 33232
