### ISSUE TITLE
git.enableLongCommitWarning

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/vscode#40920]
- VSCode Version: 1.20.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Enter a Git commit message which is longer than 72 characters.

Reproduces without extensions: Yes

The `git.enableLongCommitWarning` setting appears to be gone. How can we turn off this warning in the current version?

See here where I originally complained: https://github.com/Microsoft/vscode/issues/12089

**Comment by usernamehw** [comment]
```json
"scm.inputCounter": "off",
```

**Comment by JoshMcCullough** [comment]
Now, in v1.21.0-insider, `scm.inputCounter` appears to no longer be valid. Please advise!

> Version 1.21.0-insider
> Commit 70e020b2377f12894ca11254548ce365a0e435f1
> Date 2018-02-15T05:17:01.988Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

![image](https://user-images.githubusercontent.com/4859660/36311933-ecc8ff8a-12fa-11e8-81c3-8a168ab31f7d.png)

**Comment by usernamehw** [comment]
`"git.inputValidation": "off",` ?

**Comment by JoshMcCullough** [comment]
Thanks, that's it. Must have missed it as I perused the settings.
