### ISSUE TITLE
IntelliSense does not work after associate css to postcss syntax (provided by vetur).

### ISSUE THREAD

**Issue by zyy7259** [Microsoft/vscode#40929]
- VSCode Version: 1.19.1
- OS Version: macOS High Sierra 10.13.2

Steps to Reproduce:

1. install extension https://marketplace.visualstudio.com/items?itemName=octref.vetur
2. add configuration `"*.css": "postcss"` to `files.associations`
3. css intelliSense does not work in css file anymore.

Reproduces without extensions: No

**Comment by HerringtonDarkholme** [comment]
Hi @zyy7259, vscode doesn't support postcss. And what vetur provides is only syntax highlighting in postcss file type. 

Intellisense isn't available since css file isn't handled by vetur.
