### ISSUE TITLE
Can it support Fixedsys font?

### ISSUE THREAD

**Issue by jasonsstao** [Microsoft/vscode#40928]
Can it support Fixedsys font?

**Comment by Tyriar** [comment]
Did setting `editor.fontFamily` not work?

**Comment by jasonsstao** [comment]
Not Work!

**Comment by Tyriar** [comment]
Can you post a screenshot?

**Comment by JohnDDuncanIII** [comment]
Apparently not? Does vscode not support raster monospaced fonts?

![fixed](https://user-images.githubusercontent.com/9257785/36931040-0a5574a2-1e7c-11e8-93d9-72b141362f54.png)

**Comment by Tyriar** [comment]
VS Code supports whatever fonts can be drawn in Chromium. For the editor that setting is translated into `font-family: FixedSys`, so this is a bug in Chromium if anything.
