### ISSUE TITLE
Feature Request: Action to focus active editor file in explorer

### ISSUE THREAD

**Issue by spalger** [Microsoft/vscode#40924]
I'm looking to setup a keybinding that will focus the current editor file in the explorer, giving me a visual frame for renaming/moving/adding this or nearby files. I currently accomplish this with a combination of `workbench.files.action.showActiveFileInExplorer` and `workbench.files.action.focusFilesExplorer`, but just focusing the files explorer scrolls to the top of the list.

**Comment by isidorn** [comment]
F1> view: show explorer should do the trcik
ctrl + shit + e
or cmd + shift + e

**Comment by spalger** [comment]
oh, thanks @isidorn!
