### ISSUE TITLE
Incorrect spacing when inserting new line after multiple folded blocks of vode

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode#40926]
- VSCode Version: 1.19.1
- OS Version: Windows 10.0.16299 Build 16299

Steps to Reproduce:

1. Copy this code:
```
foo = {
    foobar: function(){
        this.foobar();
    },
    foobar: function(){
        this.foobar();
    },
    foobar: function(){
        this.foobar();
    },
    foobar: function(){
        this.foobar();
    },
    foobar: function(){
        this.foobar();
    },
}
```
2. Collapse all functions
3. Use alt+click to select the space to the right of the closing bracket
4. Press enter/paste text with a new line in it

Reproduces without extensions: Yes

it seems like its effected by any insertions containing new line . The display is correct if you change tabs and go back it looks as expected. The issue appears to be across more than one language, it is still present in this code:
```
<?php
    class Foo
    {
        public function bar() {
            $this->foobar();
        }
        public function bar() {
            $this->foobar();
        }
        public function bar() {
            $this->foobar();
        }
        public function bar() {
            $this->foobar();
        }
        public function bar() {
            $this->foobar();
        }
    }
```

Expected:
![image](https://user-images.githubusercontent.com/7832163/34426253-b23ebed4-ebf1-11e7-860e-7b909fe4fc69.png)
Actual:
![image](https://user-images.githubusercontent.com/7832163/34426237-66b3a39e-ebf1-11e7-918d-72e363100b86.png)

**Comment by aeschli** [comment]
I can reproduce. Looks like a bug updating the view model. When the view model is updated with the new lines it seems to refer to hidden lines that have already the updated locations.
![image](https://user-images.githubusercontent.com/6461412/97970174-69737500-1dc1-11eb-9a08-f9f4e5a651a1.png)

When offset is considered to be inside hidden region, it's breaking up that hidden region resulting in a hidden region without any folding indicators. See line 13.

![image](https://user-images.githubusercontent.com/6461412/97970630-1221d480-1dc2-11eb-96ad-0271a0eb8d1d.png)
