### ISSUE TITLE
file position wrong in my workspace

### ISSUE THREAD

**Issue by xieyx** [Microsoft/vscode#40935]
Hi there,
file position wrong when i open floder routes, the floder is deep in my workspace.
![image](https://user-images.githubusercontent.com/19400528/34434439-1df09506-ecc1-11e7-897d-091a40bdc4de.png)

![image](https://user-images.githubusercontent.com/19400528/34434617-3a68fc18-ecc2-11e7-8a78-0aa1859c9e1e.png)

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.4.0
vscode-docker|Pet|0.0.22
vscode-svgviewer|css|1.4.3
vscode-dash|dee|1.7.1
phpunit|ema|2.1.1
json-tools|eri|1.0.2
php-debug|fel|1.12.1
php-intellisense|fel|1.5.2
php-pack|fel|1.0.1
swagger-doc-viewer|mim|1.0.4
mssql|ms-|1.2.1
php-docblocker|nei|1.3.2
partial-diff|ryu|0.3.3

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I think this is the same underlying issue as in https://github.com/Microsoft/vscode/issues/22269
