### ISSUE TITLE
Editor's left-side markers do not appear (breakpoints, git change markers, ...) in master - with bisected commit

### ISSUE THREAD

**Issue by doudou** [Microsoft/vscode#40939]
- VSCode Version: 1.20 insiders (master's HEAD as of 29/12/2017, 80e2fcaf4339a1faedc8f2fd3824fe65f8427992)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. build and run the VSCode version as above
2. try to set breakpoints or look for Git changes in the editors (left side markers)
3. nothing appears

Reproduces without extensions: Yes

I ran a bisect between this version and 1.19.1, and it appears that 51b36999f6b208beb3f95056e3653364085e6d95 is the first commit where the markers disappear.

**Comment by jackesdavid** [comment]
The Same here
 VSCode Version: 1.20 insiders
OS Version: Ubuntu 16.04

**Comment by ciampolo** [comment]
Can confirm (running on Linux as well). The commit pointed out by @doudou seems to be the culprit. Every commit prior to the 21st works fine, everything after 22nd has this bug. Hovering over the gutter renders the markers properly but clicking on them to add a marker does nothing.

**Comment by doudou** [comment]
Just noticed that the debug "control panel" (with step / continue / ...) also disappeared.

**Comment by jackesdavid** [comment]
debug occurs, but you cant see the debug information, the point hinted and so on...

**Comment by BenMaruchu** [comment]
Same Here 
Using VSCode version : 1.20.0-insider(Head 5153c9a)
OS Version: Manjaro 17.1

Badge for number of files changed in activity bar is not showing,
also the git branch at the status bar is not showing.
![look like this](https://user-images.githubusercontent.com/7030859/34600517-07031af6-f209-11e7-92b4-5ce1d640ebd1.png)

**Comment by joaomoreno** [comment]
@doudou @jackesdavid @ciampolo Can you show me screenshots of what you mean?

**Comment by doudou** [comment]
Damn... That was the obvious thing to do :(

I'm going to try, but it's pretty time-consuming and I have little time for this right now.

**Comment by joaomoreno** [comment]
I'll be waiting 👍

**Comment by doudou** [comment]
It seems to be fixed on today's master.

**Comment by jackesdavid** [comment]
Well done friends, fixed! thanks a lot!
