### ISSUE TITLE
MS Python plugin: Autocomplete extra paths does not work on map network drive

### ISSUE THREAD

**Issue by luanft** [Microsoft/vscode#40937]
I'm using VS Code on a network drive. Everything is working well. The only problem is extra paths for autocomplete works well on local drive, but it doesn't on network drive.(I'm using map network drive of window to create Z:// drive)
Here is the config file:
`// Place your settings in this file to overwrite the default settings
{
    "window.zoomLevel": 0,
    "editor.insertSpaces": true,
    "workbench.colorTheme": "Default Dark+",
    "editor.formatOnSave": false,
    "typescript.check.npmIsInstalled": false,
    //"python.formatting.provider": "autopep8",
    "typescript.npm": "C:/Program Files/nodejs/npm.cmd",
    "python.autoComplete.extraPaths": [
        "Z:\\proj\\python\\lib\\mchp",
        "Z:\\proj\\python\\lib\\mchp\\kits",
        "Z:\\proj\\python\\lib\\mchp\\util",
        "Z:\\proj\\python\\sites\\ipmsys"
    ],
    "python.pythonPath": "C:/Python/python.exe"
}`
Thank you for your excellent editor!

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-npm|fkn|3.3.0
python|ms-|0.9.1
vscode-code-outline|pat|0.0.12

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python
