### ISSUE TITLE
crash when there is an excel file(.xlsx) in the directory

### ISSUE THREAD

**Issue by CharlesMei** [Microsoft/vscode#40930]
- VSCode Version: 1.19.1
- OS Version: windows 7

Steps to Reproduce:

1.  put any *.xlsx file in a directory
2.  open that directory in vs code
or 
1. open a directory, then put any *.xlsx file in that directory 

vs code will crash like this, even when you choose "reopen" 
![image](https://user-images.githubusercontent.com/6946734/34430663-4f16c124-eca2-11e7-8a01-48dda36ce7e2.png)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@CharlesMei I cannot reproduce, can you attach the file that causes the crash?

**Comment by CharlesMei** [comment]
@bpasero Thank you for your reply. In my pc, an empty file named a.xlsx can cause the crash. My windows is Chinese edition while i set the vs code to use English, i don't if this matters.

**Comment by bpasero** [comment]
@CharlesMei would you be able to follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#windows to get a crash dump?
