### ISSUE TITLE
ctrl+z closes tab

### ISSUE THREAD

**Issue by caub** [Microsoft/vscode#40936]
Steps to Reproduce:

1. focus in a tab
2. press ctrl+z, the tab gets closed unexpectedly
3. try to click edit > undo (nothing much happen as well, but it didn't close the tab)
4. ctrl+shift+z completely crashed vscode

It's not easy to reproduce (with or without `code --disable-extensions`), it seems to happen after a while. I'll try to capture a video, once it happens again today (it already happened in the past)

Infos
```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS Lubuntu 17.10

```

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
