### ISSUE TITLE
Help in finding the import libraries

### ISSUE THREAD

**Issue by DilipKumarPogaku** [Microsoft/vscode#40938]
This is the request for the new feature 

Need help to get the library name suggestion in import statement like regular visual studio suggest the name of the namespace / library

For example, I have written the following at the top of the component/ service

import { async, inject, TestBed}

and right click in the Visual studio code , provide an option for list library names as a suggestion

**Comment by mjbvz** [comment]
We do provide path/module-name intellisense:

![screen shot 2018-01-02 at 2 10 20 pm](https://user-images.githubusercontent.com/12821956/34502075-b5713f22-efc6-11e7-8aee-1ed9d5f908b3.png)

You can trigger this manually using `ctrl+space`. It will also be trigger automatically when you start writing the quotes for the path
