### ISSUE TITLE
vsc with ruby, autocompletes end with endef

### ISSUE THREAD

**Issue by bbtdev** [Microsoft/vscode#40940]
- VSCode Version: 1.19.1
- OS Version: Win 7

Steps to Reproduce:

1. Type end, autocompletes show endef
2. You press enter, for next line, it autocompletes with endef

I have to press esc everytime, not a big deal of course

Reproduces without extensions: Yes

**Comment by pdeona** [comment]
I have narrowed down one of the factors in reproducing this:

type `end` on a new line (with no whitespace after the cursor) => expected result
type `" "` (an empty whitespace character) _then_ move your cursor back to the beginning of the line and type `end` => autocomplete will suggest `def` upon typing `d`

**Comment by pdeona** [comment]
I have narrowed down one of the factors in reproducing this:

type `end` on a new line (with no whitespace after the cursor) => expected result

create a nested, double-indented block:
```
class TestClass

  def test_method
  end
# typing 'end' here, at the wrong indent level, causes this error consistently, i.e.:
#  end => 2 spaces, no problem
#     end => 4 spaces, causes auto-reindent and autocomplete suggests 'def'
end
```

**Comment by rebornix** [comment]
I no longer see this issue with vanilla VSCode or Ruby extension.
