### ISSUE TITLE
Add option to not auto load submodule Git repos

### ISSUE THREAD

**Issue by will-l-h** [Microsoft/vscode#40947]
The addition of submodule support in the Source Control pane a couple months ago is likely really helpful to some, but there are cases where I don't want the submodules to be loaded automatically; I'd rather just see the specific repo that I'm currently working on.

Could we get an option to not automatically load submodules? Or maybe after they are manually closed (right click, close repo), don't re-open them on subsequent loads of VS Code.

**Comment by joaomoreno** [comment]
Option is `git.detectSubmodules`
