### ISSUE TITLE
Add open-collective to trusted badge providers

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#40948]
![Backers on Open Collective](https://opencollective.com/vsc-material-theme/backers/badge.svg?style=flat-square)
```
![Backers on Open Collective](https://opencollective.com/PROJECT-NAME/backers/badge.svg?style=flat-square)
```

![Sponsors on Open Collective](https://opencollective.com/vsc-material-theme/sponsors/badge.svg?style=flat-square)
```

![Sponsors on Open Collective](https://opencollective.com/PROJECT-NAME/sponsors/badge.svg?style=flat-square)
```

**Comment by mjbvz** [comment]
What are the badge provider urls fo open-collective? Please provide an example badge

**Comment by equinusocio** [comment]
`[![Backers on Open Collective](https://opencollective.com/vsc-material-theme/backers/badge.svg?style=flat-square)]`

`[![Sponsors on Open Collective](https://opencollective.com/vsc-material-theme/sponsors/badge.svg?style=flat-square)]`

**Comment by equinusocio** [comment]
@mjbvz Sorry, updated.

**Comment by equinusocio** [comment]
@mjbvz Is this already shipped?

**Comment by octref** [comment]
@equinusocio It's scheduled to be shipped around next Friday.
