### ISSUE TITLE
Editor Ruler doesn't cover additions to the file

### ISSUE THREAD

**Issue by KyleMayes** [Microsoft/vscode#4094]
![brokenruler](https://cloud.githubusercontent.com/assets/1016104/13730861/ff16c5ae-e931-11e5-8e44-9ba4780aada7.png)

To recreate:

1. Open a new file
2. Press <kbd>Enter</kbd> a bunch of times
3. Scroll down

This is on Ubuntu, I haven't tried it on any other platforms.

Switching to another file and back fixes it.

### Version

```
Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:30:20.458Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by anseki** [comment]
I also met this issue in Windows.
And ruler lines are not re-drawn when I change Code Folding sometimes. (I don't know when it occurs expressly yet.)

The lines are re-drawn correctly when I change window size.

**Comment by alexandrudima** [comment]
Thank you for spotting this. Dup of #3984
