### ISSUE TITLE
Allow to copy diff left or right via keybindings in diff editor

### ISSUE THREAD

**Issue by Brickcaster** [Microsoft/vscode#40943]
If this is already a feature then I can't figure out how to enable it.

Using a tool like WinMerge, I could do ctrl-left or ctrl-right to copy the selected difference to the left pane or the right pane respectively.  I would like to have this functionality in VS Code when comparing files.

(One of these days I'll figure out how to set up git for my particular use case...)

**Comment by generalov** [comment]
#22003

**Comment by alexandrudima** [comment]
Let's track in #25887
