### ISSUE TITLE
Need a fast way to del chars in integrated terminal

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/vscode#40942]
- VSCode Version: Dec 2017
- OS Version: Windows 10 (Latest stable)
- Integrated Terminal: Powershell (With no user profile)

Steps to Reproduce:

1. Open integrated terminal
2. Type something
3. I suddenly want to remove these commands.
4. Then I try Ctrl+C (This works in Powershell)
5. But VSCode just adds a ^C after the command, doesn't start a new line.
6. Then I try Ctrl+[Backspace] (Also works in Powershell)
6. But VSCode just adds a ^W after the command, doesn't behave like Powershell (remove a block.)
7. So I have to long-press on [Backspace]
/** 8. Then I found I can Ctrl+A then [Backspace] */

Reproduces without extensions: Yes/No
Yes.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/31821
