### ISSUE TITLE
console.log(log) does not output in the console in debug node

### ISSUE THREAD

**Issue by MbProg** [Microsoft/vscode#40946]
I am using VS Code 1.18.1 and node v6.10 and have an electron application. When running the application not in debug mode, the logs are shown in the terminal.
But when running the app in debug mode, the log is not shown in the terminal or Debug Console. There is no output! The function console.log(logString) has no output in any of the consoles.
How can I solve that to get output while debugging my code?

**Comment by isidorn** [comment]
@MbProg first of all I suggest upgrading to latest vscode and trying then. Also upgrading to latest version of Node might also help.
In case you still see the issue then we could use some reproducable steps. Could you post your repository on GitHub so we try to reproduce?

**Comment by MbProg** [comment]
As you requested, I have updated vs code and also Node (VsCode: 1.19.1 and Node: 9.3.0). But the problem still remains. 
Here is the repository: https://github.com/MbProg/BT

**Comment by roblourens** [comment]
I see the logs in the debug console - 

![image](https://user-images.githubusercontent.com/323878/34490636-51bba304-ef95-11e7-8bfd-bdb2135e1f5e.png)

That's not what you see? By the way, I had to install several dependencies manually to run your app.

**Comment by MbProg** [comment]
Yes. I don't see these logs. What is the reason for it?
(what dependencies have you installed? Wasn't it working after you run the command "npm intall"? That was stated in the Readme file)

**Comment by roblourens** [comment]
I ran `npm install` but there are several that aren't in the package.json. Can you start with `"trace": true` and upload the log file here?

**Comment by MbProg** [comment]
Yes. Here is the log file:
```
c:\Users\mb7\Documents\UNI\BT\BT-master/node_modules/.bin/electron.cmd --remote-debugging-port=9223 . --debug-brk=40492 
7276: _attach: address: 127.0.0.1 port: 40492
7276: _attach: connected
7276: __initialize: got process id 3580 from node
7276: _initialize: target node version: v5.1.1
7276: _injectDebuggerExtensions: code injection successful
7276: _startInitialize: stopped: true
7276: NodeV8Protocol hook: ref cache size: 36
7276: _startInitialize: no entry event after 10 retries; giving up
7276: NodeV8Protocol hook: ref cache size: 44
7276: _startInitialize2: fire initialized event
7276: _startInitialize2: remember to do a 'Continue' later
7276: setBreakPointsRequest: {"name":"data-initializer.js","path":"c:\\Users\\mb7\\Documents\\UNI\\BT\\BT-master\\js\\general\\data-initializer.js"} [{"line":25},{"line":49}]
7276: setBreakPointsRequest: {"name":"main.js","path":"c:\\Users\\mb7\\Documents\\UNI\\BT\\BT-master\\main.js"} [{"line":23},{"line":168}]
7276: setBreakPointsRequest: {"name":"visualizer.js","path":"c:\\Users\\mb7\\Documents\\UNI\\BT\\BT-master\\js\\views\\visualizer.js"} [{"line":35},{"line":357},{"line":363}]
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\js\\\\general\\\\data-initializer\\.js$","line":24,"column":0}
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\js\\\\general\\\\data-initializer\\.js$","line":48,"column":0}
7276: _updateBreakpoints: result [{"verified":true,"line":25,"column":1},{"verified":true,"line":49,"column":1}]
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\main\\.js$","line":22,"column":0}
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\main\\.js$","line":167,"column":0}
7276: _updateBreakpoints: result [{"verified":true,"line":23,"column":1},{"verified":true,"line":168,"column":1}]
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\js\\\\views\\\\visualizer\\.js$","line":34,"column":0}
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\js\\\\views\\\\visualizer\\.js$","line":356,"column":0}
7276: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\mb7\\\\Documents\\\\UNI\\\\BT\\\\BT-master\\\\js\\\\views\\\\visualizer\\.js$","line":362,"column":0}
7276: _updateBreakpoints: result [{"verified":true,"line":35,"column":1},{"verified":true,"line":357,"column":1},{"verified":true,"line":363,"column":1}]
7276: setFunctionBreakPointsRequest: result []
7276: setExceptionBreakPointsRequest: []
7276: configurationDoneRequest: do a 'Continue'
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 23
7276: _loadScript: 104
7276: NodeV8Protocol hook: ref cache size: 24
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 22:0 -> couldn't be mapped to source -> use generated file
7276: __readFile: c:\Users\mb7\Documents\UNI\BT\BT-master\main.js
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 94
7276: _loadScript: 101
7276: _loadScript: 70
7276: NodeV8Protocol hook: ref cache size: 95
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\node_modules\electron-prebuilt\dist\resources\default_app\main.js' 251:22 -> couldn't be mapped to source -> use generated file
7276: __readFile: c:\Users\mb7\Documents\UNI\BT\BT-master\node_modules\electron-prebuilt\dist\resources\default_app\main.js
7276: NodeV8Protocol hook: ref cache size: 96
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\init.js' 131:9 -> couldn't be mapped to source -> use generated file
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\init.js' 133:3 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 4
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:4 -> couldn't be mapped to source -> use generated file
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 14
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 5
7276: _loadScript: 123
7276: NodeV8Protocol hook: ref cache size: 6
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 24:4 -> couldn't be mapped to source -> use generated file
7276: __readFile: c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 19
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 10
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 48:15 -> couldn't be mapped to source -> use generated file
7276: NodeV8Protocol hook: ref cache size: 29
7276: _getArraySize: array.length
7276: _getArraySize: array.length
7276: NodeV8Protocol hook: ref cache size: 31
7276: _getArraySize: array.length
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 43
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 11
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 48:15 -> couldn't be mapped to source -> use generated file
7276: NodeV8Protocol hook: ref cache size: 30
7276: _getArraySize: array.length
7276: _getArraySize: array.length
7276: NodeV8Protocol hook: ref cache size: 32
7276: _getArraySize: array.length
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 44
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 11
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 48:15 -> couldn't be mapped to source -> use generated file
7276: NodeV8Protocol hook: ref cache size: 30
7276: _getArraySize: array.length
7276: _getArraySize: array.length
7276: NodeV8Protocol hook: ref cache size: 32
7276: _getArraySize: array.length
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 44
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 11
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 48:15 -> couldn't be mapped to source -> use generated file
7276: NodeV8Protocol hook: ref cache size: 29
7276: _getArraySize: array.length
7276: _getArraySize: array.length
7276: NodeV8Protocol hook: ref cache size: 31
7276: _getArraySize: array.length
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 44
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 4
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:4 -> couldn't be mapped to source -> use generated file
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 14
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 5
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 24:4 -> couldn't be mapped to source -> use generated file
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 18
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _stopped: got break event from node
7276: _stopped: new ref cache
7276: stackTraceRequest: backtrace 0 1
7276: NodeV8Protocol hook: ref cache size: 10
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\js\general\data-initializer.js' 48:15 -> couldn't be mapped to source -> use generated file
7276: NodeV8Protocol hook: ref cache size: 24
7276: stackTraceRequest: backtrace 1 19
7276: NodeV8Protocol hook: ref cache size: 34
7276: _createStackFrameFromSourceMap: gen: 'c:\Users\mb7\Documents\UNI\BT\BT-master\main.js' 167:44 -> couldn't be mapped to source -> use generated file
7276: _terminated: node v8protocol error
7276: _terminated: node v8protocol error
7276: _terminated: node v8protocol close
7276: _terminated: target exited
7276: _terminated: target closed
7276: shutdown: kill debugee and sub-processes
7276: disconnectRequest: send response

```

**Comment by MbProg** [comment]
Sorry. As I am not an expert in electron, should I update the package.json file for that? If so could you show me how your package.json file is looking like?

**Comment by roblourens** [comment]
I don't think it has anything to do with this issue, but if you run `npm install --save` for each dependency, then npm will add them to the package.json automatically.

**Comment by MbProg** [comment]
I installed all the packages and so my package.json was updated to the following:
```
{
  "name": "discopop_visualizer",
  "productName": "DiscoPoP_Visualizer",
  "version": "1.0.0",
  "description": "DiscoPoP_Visualizer",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js",
    "watch": "watchify app/app.js -t babelify -o public/js/bundle.js --debug --verbose"
  },
  "author": "Nicolas Morew",
  "license": "MIT",
  "dependencies": {
    "ace-builds": "^1.2.9",
    "bootstrap": "^3.3.7",
    "bootstrap-colorpicker": "^2.5.2",
    "bootstrap-menu": "^1.0.14",
    "colresizable": "^1.6.0",
    "d3": "^4.12.2",
    "dagre": "^0.8.1",
    "dagre-d3": "^0.5.4",
    "electron": "^1.7.10",
    "graphlib": "^2.1.5",
    "handlebars": "^4.0.11",
    "jquery": "^3.2.1",
    "jquery-ui": "^1.12.1",
    "jstree": "^3.3.5",
    "lodash": "^4.17.4",
    "nconf": "^0.10.0",
    "sizeof": "^1.0.0",
    "viz.js": "^1.8.0"
  },
  "devDependencies": {
    "electron-packager": "^10.1.1",
    "electron-prebuilt": "^1.4.13"
  }
}
```
But now the debugger does not work at all and I get the following error messages:
`Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (e:\Projects\BT\DiscoPoP_Visualizer-graphviz\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (e:\Projects\BT\DiscoPoP_Visualizer-graphviz\main.js:2:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)`
And: 
`Cannot connect to runtime process, timeout after 30000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9223).`
My launch.json file is the following. Maybe here is the problem:
```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "protocol": "legacy",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "runtimeArgs": [
                "--remote-debugging-port=9223",
                "."
            ],
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            }
        },
        {
            "name": "Electron: Renderer",
            "type": "chrome",
            "request": "attach",
            "port": 9223,
            "webRoot": "${workspaceRoot}",
            "timeout": 30000
        }
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron: Main",
                "Electron: Renderer"
            ]
        }
    ]
}
```
I tried it with `protocol="inspector"`, but I get the following error message:
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5492).`
What is the reason for that?

**Comment by roblourens** [comment]
Maybe there was a breaking change in there somewhere, you jumped a bunch of electron versions.

**Comment by MbProg** [comment]
So it worked on your machine. Can you please show me your launch.json and package.json file? If I use them, it should work for me, too, isn't it?

**Comment by roblourens** [comment]
I didn't try upgrading electron

**Comment by MbProg** [comment]
Yes, I realized that if I just use:
```
  "devDependencies": {
    "electron-packager": "7.0.3",
    "electron-prebuilt": "0.36.2"
  }
```
it works.
But then the origin problem still remains. I get no output in my debug console, as you are getting.
![image](https://user-images.githubusercontent.com/7150069/34500147-c6645880-f009-11e7-95e4-e9c01434b75e.png)
I go to the debug panel, select Electron:Main (if I select Electron:All, it is the same) and start. It halts at the breakpoint, but after moving over it, there is no output in the debug console. 
Where could be the problem? You said that you haven't updated electron, too. So what is the difference between our settings, that I don't get any output in my debug console?

**Comment by roblourens** [comment]
Thought it might be mac vs windows, so I tried on Windows, and it works there too. 
![image](https://user-images.githubusercontent.com/323878/34502155-16a8042e-efc7-11e7-9587-cb2c84e309a5.png)

**Comment by MbProg** [comment]
Maybe this could help. I have downloaded the electron-quick-start [sample](https://github.com/electron/electron-quick-start.git) and just added an console.log in the main and tried to debug and seeing if there is an output in the debug console. But again, I have no output on my machine:
![image](https://user-images.githubusercontent.com/7150069/34502545-35a8e4c2-f014-11e7-9d9a-23b437f1586d.png)
The changed solution is [here](https://github.com/MbProg/ElectronQuickStart/).
I don't know if this helps, but here are some general informations:
My machine: Windows 8.1 Pro
![image](https://user-images.githubusercontent.com/7150069/34502619-8d7ebeb0-f014-11e7-9a1b-e011867d02ad.png)
node --version: v9.3.0
So there must be a reason, why it is not working here.

**Comment by roblourens** [comment]
If you run the same command from the terminal, do you see output there?

**Comment by MbProg** [comment]
No. I don't see anything. But if I also run the debugger Electron:Renderer and refresh the page in the browser, the breakpoint in renderer.js can be caught and then I will have an output in the debugger window. But just in this case.
![image](https://user-images.githubusercontent.com/7150069/34504221-7bddad52-f01d-11e7-9f33-13a1772786bb.png)

**Comment by roblourens** [comment]
> No. I don't see anything.

Then it's not going to show up in the debug console because the "legacy" debug adapter is only looking at output from stdout.

**Comment by MbProg** [comment]
So, have I to change legacy to inspector? Unfortunately the debugger isn't able to run and raises error when switching to inspector mode, which could be related to the old version of electron I am using. But upgrading the electron version raises the same error in debug mode which I have posted earlier.
Is there a workaround?

**Comment by roblourens** [comment]
If Electron isn't even writing the log messages to stdout, then there seems to be something very wrong. I don't know what that would be, sorry.

**Comment by jens1o** [comment]
Perhaps it is logging to STDERR?

**Comment by MbProg** [comment]
Where is STDERR? I tried to google about it, could not find an explanation. Could you please explain it?

**Comment by roblourens** [comment]
That doesn't matter, it would show either one. If you launch it from the terminal, that will show electron's stdout/stderr output. If it doesn't show up in the terminal, then the console.log messages are getting lost somewhere.

**Comment by MbProg** [comment]
So how can this problem be solved? Is that a bug of visual code?

**Comment by MbProg** [comment]
I think this cannot be the problem, because as I told you I have downloaded: The [electron-quick-start](https://github.com/electron/electron-quick-start) and there in the package.json I have installed the latest electron: 
```
  "devDependencies": {
    "electron": "^1.7.10"
  }
```
But still I get no output in the debug window! So there is another reason than the current version of Electron. But I still don't know what? I think this thread should stay open and maybe someone knows an answer.

**Comment by roblourens** [comment]
You said that you were getting that error message after you upgraded electron, `Error: Cannot find module 'app'`, so I assumed it's broken. Do you get the output in the terminal in that case? If you can fix that, and use "inspector" instead of "legacy", that would be a good thing to try.

**Comment by MbProg** [comment]
As I said I get this message in my app. When I am downloading the [electron-quick-start](https://github.com/electron/electron-quick-start) there is no error message. In the [electron-quick-start](https://github.com/electron/electron-quick-start) they use 'inspector' instead of 'legacy', but unfortunately it does not solve the problem and I have still no output in my debug console when using console.log in the main.js. I get just output when using Electron:Renderer debugger and using console.log  in renderer.js. See pictures in [above comment](https://github.com/Microsoft/vscode/issues/40946#issuecomment-355137798#issuecomment-354903534)

**Comment by roblourens** [comment]
Ok, so you got it working with the latest electron version, but it still doesn't write anything to the terminal. That's still weird, but vscode can't show any output that doesn't exist.

**Comment by MbProg** [comment]
I don't understand your last statement:
> vscode can't show any output that doesn't exist.
The problem is that the vscode does not show output that does exist. We are using console.log and vscode does not show it in the debugger console.

**Comment by roblourens** [comment]
But if this output doesn't show up in the terminal, then it's getting lost somewhere.

Using the electron app with 'inspector', could you try setting `"trace": true`, and upload the log here? Maybe it will give some clue.

**Comment by MbProg** [comment]
With setting that in the  [electron-quick-start](https://github.com/electron/electron-quick-start), I have now the following launch.json file:
```
{
    "version": "0.2.0",
    "configurations": [
    
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "protocol": "inspector",
            "trace": true,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "runtimeArgs": [
                "--remote-debugging-port=9223",
                "."
            ],
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            }
        },
        {
            "name": "Electron: Renderer",
            "type": "chrome",
            "request": "attach",
            "port": 9223,
            "webRoot": "${workspaceRoot}",
            "timeout": 30000
        }
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron: Main",
                "Electron: Renderer"
            ]
        }
    ]
}
```
But I have just this output in the debug console:

{    "version": "0.2.0",    "configurations": [            {            "type": "node",            "request": "launch",            "name": "Electron: Main",            "protocol": "inspector",            "trace": true,            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",            "runtimeArgs": [                "--remote-debugging-port=9223",                "."            ],            "windows": {                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"            }        },        {            "name": "Electron: Renderer",            "type": "chrome",            "request": "attach",            "port": 9223,            "webRoot": "${workspaceRoot}",            "timeout": 30000        }    ],    "compounds": [        {            "name": "Electron: All",            "configurations": [                "Electron: Main",                "Electron: Renderer"            ]        }    ]}

Add Configuration...
PROBLEMS
OUTPUT
DEBUG CONSOLE
TERMINAL
Verbose logs are written to:
```
C:\Users\MF6D8~1.BRA\AppData\Local\Temp\vscode-node-debug2.txt
c:\Users\m.braei\Downloads\Temp\electron-quick-start/node_modules/.bin/electron.cmd --remote-debugging-port=9223 . --inspect=17281 --debug-brk 
Debugger listening on port 17281.
Warning: This is an experimental feature and could change at any time.
```
But I realized if I don't set the protocol to inspector or auto, but to legacy, the first time I am getting an output in the debug window. 
![image](https://user-images.githubusercontent.com/7150069/34546027-778ccb64-f0f1-11e7-8b7f-020c20966b0f.png)
The only problem is that it does not halt at the breakpoint in the debug mode, but just runs the program and outputs in the debug console window.

**Comment by roblourens** [comment]
I don't think you actually have the latest electron installed, because it doesn't even include the legacy debug protocol (`--debug-brk` flag), so you won't be able to attach to it. You can double check by checking the version in node_modules/electron/package.json.

**Comment by MbProg** [comment]
As I know the latest version is 1.7.10 and here is the file node_modules/electron/package.json:
```
{
  "_from": "electron",
  "_id": "electron@1.7.10",
  "_inBundle": false,
  "_integrity": "sha1-Oj6D2WX9f6/kc76N349HJWG2JT0=",
  "_location": "/electron",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "electron",
    "name": "electron",
    "escapedName": "electron",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#DEV:/",
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/electron/-/electron-1.7.10.tgz",
  "_shasum": "3a3e83d965fd7fafe473be8ddf8f472561b6253d",
  "_spec": "electron",
  "_where": "C:\\Users\\m.braei\\Downloads\\Temp\\electron-quick-start",
  "author": {
    "name": "Electron Community"
  },
  "bin": {
    "electron": "cli.js"
  },
  "bugs": {
    "url": "https://github.com/electron/electron/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@types/node": "^7.0.18",
    "electron-download": "^3.0.1",
    "extract-zip": "^1.0.3"
  },
  "deprecated": false,
  "description": "Build cross platform desktop apps with JavaScript, HTML, and CSS",
  "devDependencies": {
    "home-path": "^0.1.1",
    "path-exists": "^2.0.0",
    "standard": "^5.4.1"
  },
  "directories": {
    "test": "test"
  },
  "homepage": "https://github.com/electron/electron#readme",
  "keywords": [
    "electron"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "electron",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron.git"
  },
  "scripts": {
    "cache-clean": "rm -rf ~/.electron && rm -rf dist",
    "postinstall": "node install.js",
    "pretest": "npm run cache-clean",
    "test": "standard"
  },
  "types": "electron.d.ts",
  "version": "1.7.10"
}
```
It seems to be the latest one.

**Comment by roblourens** [comment]
Ok. I the screenshot above doesn't actually show the debug adapter attaching to electron, just capturing the output until the app quit.

Can you try with 'inspector' again? And set `"trace": true` and attach the log file.

**Comment by MbProg** [comment]
First success! Now setting 
"protocol": "inspector",
"outputCapture": "std",
halts at the breakpoint and also has output in the console. The first time!
Then also tried with "trace": true with two options:
1. without "outputCapture": "std" -> vscode-node-debug2withoutStd.txt
2. with "outputCapture": "std" -> vscode-node-debug2withStd.txt
[vscode-node-debug2withoutStd.txt](https://github.com/Microsoft/vscode/files/1602844/vscode-node-debug2withoutStd.txt)
[vscode-node-debug2withStd.txt](https://github.com/Microsoft/vscode/files/1602845/vscode-node-debug2withStd.txt)

**Comment by roblourens** [comment]
I'm glad that works, but all the log shows is that electron is not sending notifications about the log messages, which is weird.

**Comment by MbProg** [comment]
Any idea where the problem can be? Or why I need `"outputCapture": "std"` with` inspector`?

**Comment by roblourens** [comment]
No clue
