### ISSUE TITLE
C# for Visual Studio Code extension causes high CPU usage in non-C# projects

### ISSUE THREAD

**Issue by mphonic** [Microsoft/vscode#40950]
When C# for Visual Studio Code is enabled, and a Node.js project, for instance, is open, CPU rarely dips below 10%, even when idle. After a period of editing, CPU can easily run into 90-100%.

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.13.1

---

Steps to Reproduce:

1. Install and enable C# for Visual Studio Code
2. Open a folder that contains a Node.js project

Reproduces without extensions: No

**Comment by Tyriar** [comment]
FYI @DustinCampbell

**Comment by joaomoreno** [comment]
Can you reproduce the issue again, but first:

- Open `Developer: Show Running Extensions`
- Click the `Start Extension Host Profile` button at the top right, it's the circle
- Reproduce the issue
- Stop profile

You can show me a screenshot of the profile result. You can also send me the profiling results.
