### ISSUE TITLE
Update search viewlet with global search buffer text immediately

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#40955]
Continuation of #39609

Should we update the search viewlet text immediately when the global search buffer is changed? This would mean

- The search viewlet text is changed every time the editor find widget is used
- And when the window is focused, after doing  a search in another file

Currently it only is updated when the input box is selected

**Comment by wprater** [comment]
Thanks for continuing this, interested to see what others think.

**Comment by wprater** [comment]
I have an issue where cmd+e places focus on the find input after its action emits. I would think the cmd+e should populate the find input fields immediately.  

You see, I dont think its the same as cmd+f, its the same as the action when one hits return in the find input field, but when I press cmd+e, I do not expect any input fields to be selected or my cursor to lose its focus. 

For example I want to find some matching strings and remove the lines, so I hit cmd+e to place into bugger and then I wish to remove the line Im on, cmd+g to find another occurance, remove that line, etc. 

Currently, find will receive focus after cmd+e, so my workflow breaks and I have to move cursor to the editor pane again.

**Comment by roblourens** [comment]
I think that's what #39904 is for

**Comment by wprater** [comment]
thanks for linking me back to my own issue :) for some reason I thought that one had been closed.

**Comment by roblourens** [comment]
Will consider this part of #41156, which is to consider this experience in general.
