### ISSUE TITLE
Syntax highlight breaks when Bash heredocument delimiter is indented 

### ISSUE THREAD

**Issue by benqzq** [Microsoft/vscode#40956]
Syntax highlight breaks when Bash heredocument delimiter is indented:

### Indented

![indented](https://user-images.githubusercontent.com/31392185/34449232-deaccb6a-ecfe-11e7-978c-15731cc2e29f.PNG)

### Not indented

![not indented](https://user-images.githubusercontent.com/31392185/34449234-e6c5655a-ecfe-11e7-8ef2-2519c0378b29.PNG)

## Why this phenomenon shouldn't happen

Bash functions (and even external heredocuments) tgnore/trim out, all indentations.

Hence, indenting a delimiter shouldn't effect syntax highlight, IMHO.

**Comment by aeschli** [comment]
@benqzq Can you attach a (complete) sample that shows the problem?

**Comment by benqzq** [comment]
@aeschli  https://github.com/benqzq/wsla/blob/master/wsla.sh

**Comment by aeschli** [comment]
@benqzq I get a 404 when accessing the link

**Comment by benqzq** [comment]
@aeschli I fixed the link.

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#100
