### ISSUE TITLE
Install-upgrade extension action is not user friendly and user can trigger same action multiple time

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4095]
OS: WIndows10
App Version:

Steps: 
1. Launch an app and open ASP .net 5 C# project.
2. Update correct settings for the targeted runtime and SDK in project.json and global.json file.
3. Open any c# file and verify status bar for extension or run command >DNX run and verify status bar for extension.
4. Click on extension info icon in the status bar to get missing extension, it will launch a command palette to install extension.
![statusbarextensioninfo](https://cloud.githubusercontent.com/assets/17735796/13731608/9d38e36e-e92a-11e5-89aa-d793826b11e0.png)
5. Install extension from command palette and wait for the completion.
6. Click again on the icon to upgrade extension and click on update icon from command palette.
7. Verify status bar and wait for completion.

Actual:
1. There is no pop-up about the extension installation\upgrade progress.
2. If user perform multiple action to upgrade same extension then upgrade progress is showing up  forever in the status bar.
3. It is showing the status of 'n' installation in status bar. Where 'n' is the number of times user performed upgrade action for same extension.
![extension-upgrade](https://cloud.githubusercontent.com/assets/17735796/13731578/bf170408-e929-11e5-8490-8e3164210ff6.png)

Expected: 
1. Update icon should be disabled when installation is running in background.
![update-icon-enabledallthetime](https://cloud.githubusercontent.com/assets/17735796/13731592/30d4d296-e92a-11e5-81ae-453dd858f82c.png)

2. User should not be able to trigger same action before completion of previous action.
3. User should get proper notification if he is performing same action. Like:
           a. Installation is in progress
           b. There is no update for this extension. or You have the latest version of extension already installed.

**Comment by joaomoreno** [comment]
Fixed since #637
