### ISSUE TITLE
With Split Editor Text Disappears When Tab Made Smaller

### ISSUE THREAD

**Issue by jdonnelly-apixio** [Microsoft/vscode#40951]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:51:12.123Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
python|ms-|0.9.1

---

Steps to Reproduce:

1. I split the editor into 2 (or more) groups.
2. If I move the divider to make a pane smaller, the text will disappear at a certain point (rough estimate ~140 characters of size 12 default font).

Reproduces without extensions: Yes/No

**Comment by jdonnelly-apixio** [comment]
Also.. It seems to only happen when I have the entire window stretched across two monitors that are side by side.  If I resize the window itself (and not the divider between the editor panes), the text will not disappear.

**Comment by bpasero** [comment]
@jdonnelly-apixio can you share a screenshot or video what you see?
