### ISSUE TITLE
Unable to uninstall extensions

### ISSUE THREAD

**Issue by vincen** [Microsoft/vscode#40964]
uninstall vim, and other extensions, have this issue.

- VSCode Version: 1.19.1
- OS Version: mac os 10.13.2

Steps to Reproduce:

1. disable the extension
2. reload
3. uninstall the extension

then the extension is uninstalling, and there is no response.

**Comment by robertmain** [comment]
What error messages do you get? Have you looked in the debug console?

**Comment by vincen** [comment]
No error messages.
![96a23750-aac9-4f2f-a7b4-2918b6763c23](https://user-images.githubusercontent.com/378205/34458839-d6292614-ee1b-11e7-88ac-b04df0ddf3fa.png)

**Comment by robertmain** [comment]
@vincen have you tried starting code with all extensions disabled?

**Comment by vincen** [comment]
1. Disabled all extensions
2. uninstall four extensions
and, as shown in picture below.

<img width="1391" alt="qq20171231-132039 2x" src="https://user-images.githubusercontent.com/378205/34459686-7824c8d6-ee32-11e7-8548-d7250ce0de9b.png">

and I removed these extentions from ~/.vscode/extentions/ folder. and I checked logs, there is no messages about this problem.

**Comment by tsujp** [comment]
Also getting this on windows with any extension.

OS: Windows 10 64-bit build 16299
VS Code: 1.19.1

**Comment by Tyriar** [comment]
Can people who can reproduce the problem check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by vincen** [comment]
There wasn't an alert window in previous uninstalling. I can't reproduce the problem, it's uninstalled this time.

![d261cbc0-8b69-4c31-8a36-016a66ebd656](https://user-images.githubusercontent.com/378205/34490776-e5ce8bfc-f01b-11e7-873a-ece775508009.png)

**Comment by jedcalkin** [comment]
I had the same problem, opening the devtools allows the extensions to be uninstalled.

**Comment by sandy081** [comment]
Duplicate of #40368
