### ISSUE TITLE
Unusable scrolling performance since update

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/vscode#40963]
After upgrading just now VSCode scrolling performance in the code tree (at least with two finger scrolling) is unpredictable sometimes its smooth, sometimes it doesn't work at all until attempt no x. Was fine before and fine in all other apps. CPU load is quite low.

EDIT: Same issue in code editor window
EDIT2: With 1.18.1 it is much better. It is also a little sluggish in the beginning (still loading or something) but turns out ok after 3-4 seconds while in 1.19.1 it stays bad.

Will have to find a way to downgrade again.

Here is a video showing the issue: https://photos.app.goo.gl/ZUsHHM8OGL70K3sa2. And yes I try to scroll all the time. 

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Laptop: Surface Book 1 GPU 512 SSD
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
createuniqueid|don|0.0.3
githistory|don|0.2.3
gitlens|eam|7.1.0
tslint|eg2|1.0.24
vsc-material-theme|Equ|1.2.0
genuuid|esp|0.3.3
text-transform|flo|0.1.0
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
path-autocomplete|ion|1.7.0
docthis|joe|0.6.0
python|ms-|0.9.1
cpptools|ms-|0.14.5
debugger-for-chrome|msj|4.0.0
proto|pet|0.0.2
material-icon-theme|PKi|3.2.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.19.0
vscode-flow|rto|276.3.0
gitblame|wad|2.2.0

(7 theme extensions excluded)

---

Steps to Reproduce:

1. Open up project with enough files to allow for scrolling in the file sidebar
2. Try scrolling with mouse-wheel (two-finger touchpad gesture)

Reproduces without extensions: **Yes**/~~No~~

**Comment by Tyriar** [comment]
I believe this is https://github.com/Microsoft/vscode/issues/13612, try maximizing and restoring the window

**Comment by matthiasg** [comment]
@Tyriar will try
