### ISSUE TITLE
Writing to stdout causes IOError in VS Code's Integrated Terminal

### ISSUE THREAD

**Issue by brianpursley** [Microsoft/vscode#40966]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
classic-asp|ili|0.0.2
vue|jcb|0.1.5
python|ms-|0.9.1
PowerShell|ms-|1.5.1

Reproduces without extensions: **Yes**

**Steps to reproduce:**

1.  Have python installed.
2.  Open VS Code Integrated Terminal
3.  Execute this command:

`python -c "for i in range(10000): print i"`

> 0
> 1
> 2
> -------- Output cut for ease of viewing --------
> 161
> 162
> 163
> 164Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> IOError: [Errno 0] Error
> 

If you change the python script to use a smaller number for the range, like 10, it completes fine.

`python -c "for i in range(10): print i"`

> 0
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9

This problem is isolated to the VS Code Integrated Terminal.  If I run the commands from a normal Windows command prompt, I do not get the error.

This may also be related to the following issues, but unlike them, my problem is unrelated to docker or docker-compose:

- https://github.com/docker/compose/issues/5019
- https://github.com/Microsoft/vscode/issues/36630

**Comment by Tyriar** [comment]
Dupliate https://github.com/Microsoft/vscode/issues/36630
