### ISSUE TITLE
Extension button not showing up

### ISSUE THREAD

**Issue by Luisdv93** [Microsoft/vscode#40968]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
project-manager|ale|0.23.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.14
vscode-svgviewer|css|1.4.3
file-icons|fil|1.0.7
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.2.0
vscode-css-peek|pra|2.0.2
vscode-icons|rob|7.19.0
markdown-preview-enhanced|shd|0.3.1
Align|ste|0.2.0
ayu|tea|0.11.1
open-in-browser|tec|1.1.0
expresssnippet|vla|0.1.0
html-css-class-completion|Zig|1.15.0

(3 theme extensions excluded)

---

Steps to Reproduce:

1. Open VS Code
2. Extensions button doesn't show up, I can still access it using Ctrl+Shift+X.
![image](https://user-images.githubusercontent.com/7731089/34456952-456b57b2-ed82-11e7-96e7-c028ca46e255.png)

![image](https://user-images.githubusercontent.com/7731089/34456954-5630d69e-ed82-11e7-9380-1816d6aaf952.png)

Reproduces without extensions: Yes

**Comment by robertmain** [comment]
Yeah, I'm having this same bug. A temporary workaround is to also press `F1` and type `ext` and then `Install Extensions`

**Comment by Tyriar** [comment]
Are you sure you didn't hide the viewlet manually by right clicking the viewlet?

<img width="185" alt="screen shot 2018-01-02 at 6 26 07 am" src="https://user-images.githubusercontent.com/2193314/34486697-d62fe056-ef85-11e7-91f2-2f0f8846b65f.png">

**Comment by robertmain** [comment]
@Tyriar that fixed it for me - I didn't even know that was possible. I must've done it by accident, thanks! :D

**Comment by Luisdv93** [comment]
@Tyriar Same case for me, didn't know there was an option for it, I tried searching for it using the command pallate but I couldn't find it. Anyway I'll close this. Thank you!
