### ISSUE TITLE
Improve largest possible zooming font size

### ISSUE THREAD

**Issue by xieranmaya** [Microsoft/vscode#40965]
- VSCode Version: not important
- OS Version: not important

Steps to Reproduce:

1.zoom in the editing area
2.the largest possible font size is about 26.6px(I viewed via DevTools)

This font size(26.6px) is somehow a little smaller then I need, for instance I'm using a projector and some audience siting in the back could not see clear enough.

Although the UI of the editor can also be zoom in, but that would be occupies too many spaces.   

Reproduces without extensions: not important

**Comment by Tyriar** [comment]
@xieranmaya are you zooming the workbench in as well? ctrl++ (or cmd++ on mac)

**Comment by xieranmaya** [comment]
@Tyriar yes, but that way the workbench is occupying too many spaces and is not good looking

**Comment by isidorn** [comment]
Can not really verify on my montior, adding verified by code review
