### ISSUE TITLE
New feature - Clear Workspace

### ISSUE THREAD

**Issue by Salomar** [Microsoft/vscode#40967]
- VSCode Version: 1.19.1
- OS Version: Windows 10

I think a neat feature that could be added to VS Code is the option to clear the workspace.
Sometimes using the ftp-simple I need to re download the ftp folder (I think that's what it does). 
A clear workspace option would make it easier to do that. Besides Im sure its probably helpful in other scenarios.

Love the program :D

**Comment by robertmain** [comment]
Clear the workspace?....like...delete everything in the current workspace?!

**Comment by Salomar** [comment]
Yeah, something like this:


The one one the left has a 'non cleared' workspace, the one on the left 
has a 'clear workspace'.
I dont know if Im being clear.

Thanks for the quick response.

------ Mensaje original ------
De: "Robert Main" <notifications@github.com>
Para: "Microsoft/vscode" <vscode@noreply.github.com>
CC: "Salomar" <ignaciofiora@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 30/12/2017 17:45:34
Asunto: Re: [Microsoft/vscode] New feature - Clear Workspace (#40967)

**Comment by robertmain** [comment]
Doesn't look like there's an image attached - but out of interest what's wrong with just doing `rm -rf $(pwd)` ?

**Comment by Salomar** [comment]
I dont know what that command does, or how to use it.
Im re-sending you the image.

Thanks for the response :)

------ Mensaje original ------
De: "Robert Main" <notifications@github.com>
Para: "Microsoft/vscode" <vscode@noreply.github.com>
CC: "Salomar" <ignaciofiora@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 30/12/2017 18:02:24
Asunto: Re: [Microsoft/vscode] New feature - Clear Workspace (#40967)

**Comment by robertmain** [comment]
It's a bash command... deletes everything in the current working directory. `rm` means remove, the `r` in the `rf means "recursive" - basically it will go down into subdirectories and the `f` means "force" which means it won't prompt you for each individual file(which can be tiresome)

**Comment by Salomar** [comment]
Hey,
I didn't mean to delete the files in the workspace, I meant just 
clearing it so nothing appears in it.

I hope this is useful in some way
Thank you
Ignacio

------ Mensaje original ------
De: "Robert Main" <notifications@github.com>
Para: "Microsoft/vscode" <vscode@noreply.github.com>
CC: "Salomar" <ignaciofiora@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 30/12/2017 18:02:24
Asunto: Re: [Microsoft/vscode] New feature - Clear Workspace (#40967)

**Comment by robertmain** [comment]
Oh...ok

What do you mean by "clearing it" then? I'm a bit confused :s

**Comment by Salomar** [comment]
I've attached a picture to help you understand, the window on the right 
has a 'Cleared' Workspace, the one on the left hasn't.

I hope this helps
Happy new year :)

------ Mensaje original ------
De: "Robert Main" <notifications@github.com>
Para: "Microsoft/vscode" <vscode@noreply.github.com>
CC: "Salomar" <ignaciofiora@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 2/1/2018 14:14:44
Asunto: Re: [Microsoft/vscode] New feature - Clear Workspace (#40967)

**Comment by robertmain** [comment]
I'm sorry - I'm not seeing any pictures. It doesn't look like GitHub is displaying them

**Comment by Salomar** [comment]
I uploaded the picture:
https://i.imgur.com/n8Iz5EW.png

------ Mensaje original ------
De: "Robert Main" <notifications@github.com>
Para: "Microsoft/vscode" <vscode@noreply.github.com>
CC: "Salomar" <ignaciofiora@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 2/1/2018 14:20:37
Asunto: Re: [Microsoft/vscode] New feature - Clear Workspace (#40967)

**Comment by robertmain** [comment]
Oh, I think I understand now - you want a button that will let you just close any open folders in the workspace?

**Comment by Salomar** [comment]
Exactly 😁

**Comment by robertmain** [comment]
Can I suggest changing the title of your issue then to say something like that - otherwise it just implies (as I imagined) that you just want to delete everything in the workspace :)

**Comment by bpasero** [comment]
File > Close Workspace
