### ISSUE TITLE
Output random code

### ISSUE THREAD

**Issue by NASCUNO** [Microsoft/vscode#40961]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.1
java-debug|DSn|0.0.2
code-runner|for|0.8.6
vscode-javac|geo|0.0.47
beautify|Hoo|1.1.1
python|ms-|0.9.1
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
team|ms-|1.122.0
java|red|0.16.0
vscode-icons|rob|7.19.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscode-java-debug|vsc|0.4.0
vscode-java-pack|vsc|0.2.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by maxibanki** [comment]
Please give us more information, which your given information we can't reproduce it or can't do anything. :)
Also try to disable all extensions by using the `--disable-extensions` parameter.

**Comment by isidorn** [comment]
Once more data is provided I will gladly reopen this issue
