### ISSUE TITLE
[folding] Visual Studio-like code folding decoration

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#4096]
Can VScode inherit cold folding from Visual Studio:

| Normal: | On Hover: |
| :-: | :-: |
| ![image](https://cloud.githubusercontent.com/assets/6901336/13731861/e31a29d0-e941-11e5-9a41-dc3f63a56aa9.png) | ![image](https://cloud.githubusercontent.com/assets/6901336/13731855/d67e369e-e941-11e5-9828-5069333bbb97.png) |

and having the fold on the same line like this:
![image](https://cloud.githubusercontent.com/assets/6901336/13731870/0feb5178-e942-11e5-9fe7-90fa1b325510.png)

**Comment by FeaRCODE** [comment]
@weinand @aeschli  I should have stated it more clearly. Can VScode inherit cold folding from Visual Studio.

**Comment by weinand** [comment]
@FeaRCODE VS Code is not based on Visual Studio, so I assume that you use "inherit" in the metaphorical sense, correct?

**Comment by FeaRCODE** [comment]
Sorry, correct. I would like the styles and functionality to be the same.

**Comment by FeaRCODE** [comment]
Any updates on implementing a more clear representation of folded code?

**Comment by aeschli** [comment]
@FeaRCODE Sorry, there is currently no work in the folding area planned for the coming month.

**Comment by FeaRCODE** [comment]
I think VSCODE has come very far in this area, I can close this issue.

**Comment by aeschli** [comment]
duplicate of #19690
