### ISSUE TITLE
SelectBox Custom: DropDown does not close, becomes orphaned if open on panel close

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#40962]
- VSCode Version: code-oss-dev 1.20.0 (a83a46d9a7356e955ed9a3dcc75193040588d35c)
- VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:36:58.030Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Open OUTPUT  or TERMINAL view 
2. Show SelectBox
3. Close the Panel
4. bug

![gif](https://user-images.githubusercontent.com/8474118/34454108-b7029510-eda6-11e7-9a1f-70a2f875cc69.gif)

I used Code-OSS because Insider has not been updated for over a week

**Comment by maxibanki** [comment]
I can reproduce it with the same version.

**Comment by cleidigh** [comment]
@EbXpJ6bp 
@maxibanki 
Nice catch, and thanks for reproducing !

I have been able to reproduce this, no blur event is fired on panel close which is usually used to close the drop-down.  I have a fix will post soon.

**Comment by cleidigh** [comment]
Fixed with: #40974

**Comment by bpasero** [comment]
Good catch!
