### ISSUE TITLE
stop notifying me when new version is ready! or provide a way to set the frequency of update notification.

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#40978]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|1.0.0|
|vscode-stylesheet-beautify|n23|0.0.3|;

---

Steps to Reproduce:

1. open vscode for a while, then "存在可用更新。" will shown everytime when there is an update.

expected:
1. stop notifying automatically
2. provide a way to set the frequency of update notification.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21651
