### ISSUE TITLE
sick and tird of being sat

### ISSUE THREAD

**Issue by SURVIVOROFSUICIDE** [Microsoft/vscode#40973]
- VSCode Version: Code - Insiders 1.18.0-insider (3495b0b185acbe8188e821ccb3ae807274703a9c, 2017-10-17T04:23:54.942Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.3
python|don|0.7.0
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-intellisense|fel|2.2.2
php-pack|fel|1.0.1
beautify|Hoo|1.1.1
svn-scm|joh|1.5.0
hg|mrc|1.2.3
cpptools|ms-|0.14.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
sublime-keybindings|ms-|3.0.3
team|ms-|1.122.0
debugger-for-chrome|msj|4.0.0
vscode-icons|rob|7.19.0
perforce|sle|3.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@SURVIVOROFSUICIDE 
Please include information, steps to reproduce.

**Comment by robertmain** [comment]
...and possibly a more descriptive title?
