### ISSUE TITLE
Add Live Local Server Preview

### ISSUE THREAD

**Issue by vk9000** [Microsoft/vscode#40977]
please add a live local server preview feature for html pages (like the one available in adobe brackets) in future release.this is very much missing in vs code(ps: im not sure if its already there.)

**Comment by David-Else** [comment]
It is provided by this excellent extension:

https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by vk9000** [comment]
Thankyou david

**Comment by maxibanki** [comment]
@vk9000 Please close your issue, since it seems to have been done. :)
