### ISSUE TITLE
The v1.19.1 rpm package isn't published in the yum repo

### ISSUE THREAD

**Issue by tlindsay42** [Microsoft/vscode#40972]
- VSCode Version: 
```text
$ dnf list code
Last metadata expiration check: 0:12:14 ago on Sat 30 Dec 2017 03:08:11 PM CST.
Installed Packages
code.x86_64                                  1.19.0-1513245647.el7                                  @code
```
- OS Version:
```text
$ cat /etc/os-release 
NAME=Fedora
VERSION="27 (Workstation Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

Steps to Reproduce:

1. Open Visual Studio Code and it prompts to update
![image](https://user-images.githubusercontent.com/11078689/34457441-da73ad62-ed75-11e7-9d4c-53a5be3654b9.png)
2. Attempt to update
```text
$ sudo dnf update --refresh
[sudo] password for username: 
Last metadata expiration check: 0:00:00 ago on Sat 30 Dec 2017 03:27:26 PM CST.
Dependencies resolved.
Nothing to do.
Complete!
```
3. List packages in yum repo and filter for version 1.19.  Note that version 1.19.1 is missing, but is available for manual download here: https://go.microsoft.com/fwlink/?LinkID=760867.
```text
$ curl -s https://packages.microsoft.com/yumrepos/vscode/ | grep code-1.19
<a href="code-1.19.0-1513245647.el7.x86_64.rpm">code-1.19.0-1513245647.el7.x86_64.rpm</a>              15-Dec-2017 04:59            68221902
```

Reproduces without extensions: Yes/No
Yes

**Comment by David-Else** [comment]
This lack of RPM repo update to the 'recovery build' happens every month now, it's really boring and annoying. Please automate it!

**Comment by Tyriar** [comment]
It cannot be automated as we're blocked on another team who have their own priorities. The particularly large delay this release is because I need to be on campus to get the signed bits.

**Comment by Tyriar** [comment]
Published https://packages.microsoft.com/yumrepos/vscode/
