### ISSUE TITLE
Don't use denying settings texts - Always use "approving" names

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#40987]
_"Denying options ain't no good"_ ... Many options in Visual Studio Code settings force the developer to double-deny his choice:

    "Don't use ..." : True
    "Don't vote for ..." : False
    "Disable logging ...": False

_"I didn't say I didn't do it"_ is so much more awkward than just writing: _"I said I did it"_.

Establish a coding guidline to refrain from using denying options. I.e.: change all options from "Don't" to "Do":

    "Use ..." : False
    "Vote for ..." : True
    "Enable logging ...": True

See also [here](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/32776153-don-t-use-denying-option-texts-always-use-appro).

**Comment by sandy081** [comment]
I assume this meant for all those settings in VS Code with denying text. 

@SetTrend Can you please list those settings with this pattern?

**Comment by sandy081** [comment]
@SetTrend Sorry, I am not sure if you listed any real settings you observed in the description

**Comment by SetTrend** [comment]
Here we go:

```
  "diffEditor.ignoreTrimWhitespace": true,
  "editor.hideCursorInOverviewRuler": false,
  "zenMode.hideActivityBar": true,
  "zenMode.hideStatusBar": true,
  "zenMode.hideTabs": true,
  "debug.hideActionBar": false,
  "typescript.disableAutomaticTypeAcquisition": false,
  "extensions.ignoreRecommendations": false,
  "git.ignoreLegacyWarning": false,
  "git.ignoreLimitWarning": false,
  "git.ignoreMissingGitWarning": false,
```
I manually browsed the settings. So this list may not be comprehensive.

**Comment by sandy081** [comment]
@Microsoft/vscode opinions?

**Comment by Tyriar** [comment]
Doing something like this plus an overall consistency/typo fix would probably be a good thing in the long run, it would be a lot of breakages in the short term though. At some point @bpasero had some setting deprecation code which may have been removed which would be necessary if we were to do something like this.

**Comment by bpasero** [comment]
@Tyriar that was for command IDs, but not settings.

**Comment by bpasero** [comment]
my 2 cents: I find `regardLimitWarning` much harder to understand than `ignoreLimitWarning`, but maybe thats just me.

**Comment by roblourens** [comment]
Some of these might read better with a negative phrasing, when `false` is a good default. But I think the zenMode settings would sound better flipped around, especially when we have `workbench.editor.showTabs`, `workbench.statusBar.visible`, etc.

**Comment by SetTrend** [comment]
@bpasero : You're right for sure. English is not my native tongue, I'm afraid. How are chances that there's a better, more juicy equivalent to "regard"?

Basically, I feel it rather hard to apprehend that when you're checking an option you're actually _unchecking_ it.
