### ISSUE TITLE
OS X - double-click on menu title bar to restore window size is not working

### ISSUE THREAD

**Issue by mpab** [Microsoft/vscode#40989]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vsc-prolog|art|0.8.7
vscode-opencl|gal|0.1.3
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-cudacpp|kri|0.1.1
cpptools|ms-|0.14.5
pdf|tom|0.2.0

---

I couldn't find this issue reported, exactly as described, so apologies for any duplication.
Steps to Reproduce:

1. On OS X High Sierra, open VS Code
2. Double-click on the VS Code application title bar - the application maximises correctly.
3. Double-click on the VS Code application title bar - the application does not restore correctly.

The application should be restored to its original dimensions.
The window can still be resized, by hovering the mouse at the edge of the screen and dragging, but it's a little awkward.

Other information: I have a multi-monitor setup.

Reproduces without extensions: Yes/No UNKNOWN
 - Can't check - this flag is not working either(!)

**Comment by bpasero** [comment]
You can fix this by setting: `"window.titleBarStyle": "native"`
