### ISSUE TITLE
option "--unity-launch" not documented in "--help"

### ISSUE THREAD

**Issue by eszlari** [Microsoft/vscode#40986]
- VSCode Version: 1.20.0-insider
- OS Version: Linux

Steps to Reproduce:

1. start VSCode with "code --help"
2. notice that the option "--unity-launch" is not mentioned

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I have no clue we have that option. What does it do?
Closing as designed as I think this is not supported, though feel free to correct me if I am wrong.

**Comment by eszlari** [comment]
```
$ grep unity /usr/share/applications/code.desktop
Exec=/usr/share/code/code --unity-launch %F
```
