### ISSUE TITLE
Please sort 'locals' window into alphabetical order in ms-python debugger

### ISSUE THREAD

**Issue by MikeTheGreat** [Microsoft/vscode#40980]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-devdocs|akf|1.0.3
Bookmarks|ale|0.18.0
githistory|don|0.2.3
todo-tree|Gru|0.0.11
RelativePath|jak|1.0.0
font-awesome-codes-html|med|0.0.7
python|ms-|0.9.1
csharp|ms-|1.13.1
view-in-browser|qin|0.0.5
startanyshell|rem|0.3.1
vscode-multiclip|sle|0.1.3
jinja|who|0.0.8

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start a test using the debugging option
2. Look at the 'Locals' window

When I look at my 'Locals' window I see lots of variables, in the same order that they were declared in the function, like so:

![unsortedlocals](https://user-images.githubusercontent.com/551619/34460807-1bbaf61a-edce-11e7-9d1e-4a314bdd0b77.png)

It would be easier to find the variables if they were in sorted order (such as alphabetically sorted order)

Reproduces without extensions: Not without the ms-python extension :)

**Comment by isidorn** [comment]
This feature is coming from the python extension as that adapter is choosing in which order to return the variblaes. So please file this aginst the vscode python extension

**Comment by MikeTheGreat** [comment]
Sorry for mis-posting this!
I figured that since it's MS's python extension this would be an ok place to post it but that's clearly not true (and that's fine :) )
I'll go figure out where their repo is and post it there.
Thanks!
