### ISSUE TITLE
Middle mouse button doesn't scroll editor window

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#40985]
My mouse has a mouse wheel with middle mouse button functionality.

Many editors I know I can scroll the editor panel's contents while keeping the middle mouse button pressed. VS Code doesn't support this functionality.

Can we please get this functionality in VS Code?

![msdn](https://user-images.githubusercontent.com/9283914/34461823-7ccaaf24-ee35-11e7-9ae9-39a0413e5f88.png)

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/16514 or https://github.com/Microsoft/vscode/issues/6302

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/6302
