### ISSUE TITLE
Debug _.each loop or functions of delegates

### ISSUE THREAD

**Issue by MbProg** [Microsoft/vscode#40996]
Hello, I am using vsCode 1.19.1 and try to debug my electron app with javascript. The debugger is working correctly. But there is a problem: the debugger is unable to go stepwise through _.each loops e.g.:
 ```
     _.each(startNodes, function(root) {
        if (root.type == 0) {
		  hiddenNodes.push(root);
          functionNodes = functionNodes.concat(root.children);
        } else {
          functionNodes.push(root);
        }
      });
```
Here the debugger does not go inside it or when I set a breakpoint inside the block it does not stop there. Is there no way in vscode to debug the block of code in such a .each loop?
The same problem exists for functions in delegates:
```
graphContainer
	.delegate(
			'g.cluster',
			'click',
			function() {
				editorController.unhighlight();
				editorController.highlightNodeInCode(nodeData[this.id]);
			});
```
Also here I have no possibility to debug the code in the anonymous function. Setting a breakpoint there, also does not make the debugger stop.
So is there way to debug these codes in vscode?

**Comment by auchenberg** [comment]
What's your setup like? Debugging the main process of Node? Using Babel? Any transpilers?

Could be a sourcemap issue.

**Comment by MbProg** [comment]
I am programming an application in Electron. If it helps, here is the source code: [https://github.com/MbProg/BT](url)
You could debug it with vscode and you will see the problems I have stated here

**Comment by MbProg** [comment]
Another problem that I realized with vscode is that if I write any console.log in such a function, then the console is not writing in the terminal!!! Here the code:
```
graphContainer.delegate('g.node', 'dblclick', function(
	event) {
console.log("g.node dblclick");
...
});
```

**Comment by auchenberg** [comment]
I took at quick look at your application, and first you have a few dependency issues that needs to get resolved before a clean check-out can run. 

Secondly it looks like none of your source files containing your loop code is loaded into your rendering process. You can debug this using the [`.scripts` command](https://github.com/Microsoft/vscode-node-debug2#the-scripts-command), which shows that only `BT/js/views/index.js` is loaded in your renderer process. This seems to be your root-cause, and you can't debug your JavaScript in Chrome DevTools either.

Also, your console seems to work fine from your Main and renderer process, as I see your console.logs and Bootstrap errors showing up.

<img width="604" alt="screen shot 2018-01-02 at 11 31 38 am" src="https://user-images.githubusercontent.com/173559/34473018-9dbc32d0-efb0-11e7-9c19-43338b0260f3.png">

So the fix here would be to make sure the parts of your application is loaded in your renderer process, and then you should be able to debug the code, once it's loaded.

**Comment by MbProg** [comment]
Sorry for the question, because I haven't developed this application and I just want to add some features in it. I thought that So does it mean that I am not able to output in the console in the main process? In this project I am using a file "**graph.js**" to make some computation which is run in the main process. It is called from renderer process via IPC. So how can I make **graph.js** print output in the debug console? Is it not possible since it is in the main process? Have I move the whole code in a renderer process file like **visualizer.js** to can use console.log in debug mode? 
In the answer I couldn't figure out why I was not able to go stepwise through a `_.each` loop in vscode? How can I debug the code inside the block` _.each(startNodes, function(root) {...})`?

**Comment by MbProg** [comment]
How do you get this output in your debug console? I don't get any of them in the debug console? No "Hello" or any other of them? What can be the problem?
