### ISSUE TITLE
Folder rename failure clears dirty state for all open documents

### ISSUE THREAD

**Issue by kt215** [Microsoft/vscode#40993]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Open vscode
2. Open a folder, named `Test`
3. Create a file in the `Test` folder named `Test.txt`
4. Edit `Test.txt` with some data (vscode shows edit indicator on document tab).
5. Open Integrated Terminal, CD into `Test` folder; the folder is now locked.
6. In vscode explorer, try to rename `Test` folder.
7. Two errors appear `File not found` and `A system error occurred (EBUSY: resource busy or locked`.
8. File `Test.txt` no longer shows edit indicator on document tab.
9. `Test.txt` can be closed without save prompt, causing potential data loss.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@kt215 I cannot reproduce, please make a screen cast of the flow and share it

**Comment by kt215** [comment]
I spent A LOT of time testing and retesting this issue before reporting it. I have not had any time since then to create an additional video. I found that the steps provided, clearly reproduced the issue. Now you automatically close it after only 10 days? This is a serious data loss bug in vscode.

**Comment by pranaydutta89** [comment]
this is still an issue , i am into ubuntu 17.10 vscode 1.2.0
