### ISSUE TITLE
"files.defaultLanguage" does not work

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#40994]
- VSCode Version: 1.19.1
- OS Version: Sierra 10.12.4

Steps to Reproduce:

1. Set `"files.defaultLanguage": "javascriptreact"`.
2. Create new file through the sidebar.
3. See that the defaultLanguage of the file is **Plain Text**, not Javascript React.

Reproduces without extensions: Yes/No
Tried to **Launch with `code --disable-extensions to check`.** Got:
`-bash: code: command not found`

**Comment by bpasero** [comment]
This setting only has an impact on new untitled files being created (File > New File).

**Comment by LAITONEN** [comment]
Any possibility of adding the same feature for the files created through the sidebar?
