### ISSUE TITLE
Feature request: word wrapping by file type.

### ISSUE THREAD

**Issue by emxjay** [Microsoft/vscode#40997]
It would be sweet to be able to set the option `editor.wordWrap` according to the opened file's type.

**Use case:** Word wrapping is useful when working with plain text (diary, to-do lists, etc.), and less useful on source code files (where the norm suggests short lines).

Cheers.

✌🏽

**Comment by usernamehw** [comment]
```json
"[todo]": {
  "editor.wordWrap": "on"
},
"[plaintext]": {
  "editor.wordWrap": "on"
},
```

**Comment by emxjay** [comment]
Oh! That will do.

Thanks, @usernamehw.
