### ISSUE TITLE
Coloring broken on startup

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4099]
There is no coloring in latest vscode for all languages
VScode version 64a83fe3adc13da0cea55373cecccf50ec7dc747

I see this on os x el capiitan

**Comment by aeschli** [comment]
@isidorn  Do you see the 4 default themes in the theme picker? Do they work?

**Comment by isidorn** [comment]
@aeschli yes, once I change the theme via the theme picker all is good.
I am pretty sure I had the light+ theme picked, so my speculation is that the update somehow unset my chosen theme to no-theme-set. Is this possible?
