### ISSUE TITLE
Task running a quoted .cmd file name fails

### ISSUE THREAD

**Issue by robinmattern** [Microsoft/vscode#40995]
If a Windows .cmd file name is included in quotes, why is the task failing on a parse error??  

Steps to Reproduce:
1. Create a shell task with a ")" in the command file name
```
 { "label"         : "Test Paren in File Name",   
   "type"          : "shell",
   "command"       : "\"sc71231)_Test.cmd\"",
   "presentation"  : { "echo": true }
 },
``` 
2. Run it
```
> Executing task: "sc71231)_Test.cmd" <

At line:1 char:8
+ sc71231)_Test.cmd
+        ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

The terminal process terminated with exit code: 1
```
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
printcode|nob|1.0.4
vscode-docker|Pet|0.0.22
html-preview-vscode|tht|0.1.1
---

Reproduces without extensions: Yes/No

**Comment by robinmattern** [comment]
This issue is the same as this one: \" doesn't work correctly in tasks.json #31722

Basically anytime  "\" ... \"" is used in a shell task command, if there is a space or invalid character in the path or file name, the task fails.  In particular, this "\"${file}\"" fails for the same reason.

**Comment by dbaeumer** [comment]
There is more to is than the ". In PowerShell `)` has a special meaning when pass on the command line. Have you tried to put this in single quotes. E.g. `'sc71231)_Test.cmd'` ?

**Comment by robinmattern** [comment]
Thanks for the reply.  I understand the ')' is problematic, but I just that any filename inside double quotes should be ignored.  
- I can't put `"command": 'A file'` in the tasks.json file as it is not legal JSON
- Doing this `"command": "'A file'"` just prints out the file name
- If I try to pass the file name to CMD, I get this error due to the space in the file name
![image](https://user-images.githubusercontent.com/1158299/34678192-5bad6102-f460-11e7-9a17-d531c9ecb4d5.png)
- What I really want to do is execute the current file being edited with the associated program for the file's extension, as follows: 
![image](https://user-images.githubusercontent.com/1158299/34678132-3069f604-f460-11e7-975c-4779feee05dc.png)

**Comment by dbaeumer** [comment]
This got fixed via https://github.com/Microsoft/vscode/issues/45576. You can now have a comment
```
{
   "value": "sc71231)_Test.cmd",
   "qouting": "strong"
}
```

which will do a strong quoting of the command to execute on all know shells (PowerShell, cmd, ...).
