### ISSUE TITLE
Git disabled but still looking for it

### ISSUE THREAD

**Issue by bobsort** [Microsoft/vscode#40991]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. setting adjusted to
    "git.enabled": false,
    "git.autorefresh": false

2. restart Code.exe
 output window shows

Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Users\Bob\AppData\Local\Programs\Git\cmd\git.exe

and a warning asking to install git

**Comment by joaomoreno** [comment]
#40421
