### ISSUE TITLE
Utilize default Node - don't install your own

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#40990]
Can we have VS Code utilize the NodeJS installation that's already present on a machine, and, alternatively, have it download and call the installer of the most recent stable official NodeJS source if it isn't already installed?

I feel I'm getting more and more dragged down into maintenance hell since the invention of NodeJS.

After having installed VS Code and Visual Studio 2017 my machine already contains 5 instances of NodeJS - and I didn't even install NodeJS itself yet. Each coming with its own `node_modules` and everything.

I feel we should refrain from burdening developers more than necessary by cluttering up the disk with different collections of NodeJS packages in different locations and different conditions. NodeJS has become stable enough to be utilized monolithically across a whole machine.

If a different NodeJS version was required indeed, we could easily use Docker/Containers or virtual machines for that purpose.

I feel we should start getting settled now and keep things easy to maintain, so we developers can regain focus to our own development goals.

See also [here](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/32811538-utilize-default-nodejs-installation-don-t-instal).

**Comment by joaomoreno** [comment]
VS Code simply depends on, and ships with, Electron. You don't have to install NodeJS to run VS Code.
