### ISSUE TITLE
Downgrade Code to a previous version

### ISSUE THREAD

**Issue by der-Daniel** [Microsoft/vscode#410]
Hi folks,

the new version 0.10.1 has a really bad performance on my system. 
Everything is slow, letters appears seconds after I have typed them, the windows loads row by row and so on.
I spend like the last 30 minutes searching the web for a previous installation of vscode. The last version, that worked on my system was 0.9.1.
Where can I find it / How can I downgarde?

GitHub Releases do not cover this version, nor does the website.

Cheers
Daniel

**Comment by mackenza** [comment]
you may want to indicate what platform you were on. Keep in mind that prior to 0.10, VSC was closed source and MSFT has no obligation to provide access to it.

Perhaps you could help the project and describe what you are seeing as far as *bad performance*?

**Comment by der-Daniel** [comment]
Oh ok, I thought this was open source right away.

Of course I can provide more details, I thought the downgrade was just a matter of not known the download link ;)

*My system:*
Model Name: **Dell XPS 15 9530 (Late 2013 Version)**
Processor: **Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz**
Operation System: **Ubuntu 15.10**

*What is the term *bad performance* referring to:*
The general work flow of the program is weird. When I start Code, the program window is not loading "instantly", but the windows builds from the top to the bottom. Think about it like loading a massive image in your web browser with a shitty connection. 
When I am typing, the letters does not appear "instantaneous", but appear of like half a second.

I did not go into more weird behaviour, since this already kills the whole experience. I though this was caused, because I am using 15.10 and the version 0.10.1 is labelled as beta.

If more information about my system is needed, just let me know.

**Comment by mackenza** [comment]
that should be helpful. 

VSC was only made open source with the 0.10.1 release last Tuesday or so. I think they wanted to get it to a certain level before they open sourced it. The prior versions were free, but not open source. Thus there only being the open source releases here on GH

**Comment by eugen-v** [comment]
I'm having the same problem. Reported here: https://github.com/Microsoft/vscode/issues/162
It seems to be a problem that occurs with Atom also.
I found that the problem "is less of a problem" (to say so) when Visual Studio Code's window is running on a screen with a lower resolution.

To downgrade (and keep using VSCode), I've looked into past downloads and found this link, for 0.9.1: https://az764295.vo.msecnd.net/public/0.9.1/VSCode-linux64.zip

**Comment by mackenza** [comment]
If it's similar on atom I bet it's an Electron issue.

**Comment by der-Daniel** [comment]
@eugen-v thank you sir! that saves me till a fix
@mackenza what are your referring to by "Electron"?

**Comment by mackenza** [comment]
Electron is the native shell that VSC runs in. Inside the Electron shell is essentially a web app running in a wrapped version of the chromium browser. The reason I brought it up is because Atom also uses Electron (Electron is formerly known as atom-shell) and it could be that performance issues on Linux with both editors *may* be related to the common shell.

**Comment by der-Daniel** [comment]
I should add the information, that I am using a retina display at resolution of 3200x1800.
That may play a role..

On Nov 22, 2015 23:38, Andrew MacKenzie <notifications@github.com> wrote:

Electron is the native shell that VSC runs in. Inside the Electron shell is essentially a web app running in a wrapped version of the chromium browser. The reason I brought it up is because Atom also uses Electron (Electron is formerly known as atom-shell) and it could be that performance issues on Linux with both editors may be related to the common shell.

**Comment by eugen-v** [comment]
Oddly enough, if you switch VS Code to full screen mode, the slowness is gone and everything works smooth.

**Comment by joaomoreno** [comment]
You can now find links to older builds in [Previous Releases](https://github.com/Microsoft/vscode/wiki/Previous-Releases).

**Comment by bsell93** [comment]
These don't seem to exist anymore?

**Comment by toshuo** [comment]
Since VSCode's recent move to powershell broke my dev workflow (https://github.com/Microsoft/vscode/issues/21753), I'm also in need of a downgrade. Do you have a current link to downloads of previous releases, @joaomoreno ?

**Comment by joaomoreno** [comment]
@toshuo Why don't you configure the integrated terminal to use the Command Prompt, instead of PowerShell?

**Comment by toshuo** [comment]
@joaomoreno I never configured it either way. The default behavior used to work. Now it's broken. I spent a bit of time googling the error messages and poking around in the options and help within VSCode and then looking for a way to downgrade before switching back to my mac, where VSCode still works for my tech stack.

If the default remains broken for Elixir for too long then, I'll just switch editors.

**Comment by joaomoreno** [comment]
@toshuo Let's try to keep you using Code for a while longer. But I'm going to need your help... are you with me? If so, let's just continue the discussion in #21753

**Comment by toshuo** [comment]
@joaomoreno Sure. There's one thing that might be relevant here, though, The reason I found this thread is that I was looking for a way to downgrade and the reason I messaged you was that the link didn't lead to those instructions... Just for the sake of future search engine traffic that might make sense to answer if there does exist a doc with downgrade instructions.

**Comment by joaomoreno** [comment]
But why would you want to downgrade, if unlocking you means changing a setting?

**Comment by toshuo** [comment]
There are lots of things that could cause that. The opener of the issue wanted to downgrade due to performance issues. Unless there's never another problem with an update again, it's a good thing to know how to do!

**Comment by gomker** [comment]
I would agree - the latest update broke the "better merge" functionality that was recently included causing me major headaches, I would like to revert back to the previous version.

**Comment by onury** [comment]
I need to downgrade due to #30449

**Comment by youurayy** [comment]
Please reopen this issue. The previous releases are nowhere to be found again.
