### ISSUE TITLE
https://guides.github.com/feed/index.xml#

### ISSUE THREAD

**Issue by bigsby1978** [Microsoft/vscode#41001]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.4
php-intellisense|fel|2.2.3
auto-close-tag|for|0.5.5
vscode-icon-theme|jtl|1.6.1
php-symbols|lin|2.1.0
code-beautifier|mic|1.7.2
hg|mrc|1.2.3
mssql|ms-|1.3.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.14.5
node-debug2|ms-|1.20.0
team|ms-|1.122.0
material-icon-theme|PKi|3.2.0
vscode-svn|sim|0.0.8
perforce|sle|3.1.0
ayu|tea|0.11.1
vscode-react-native|vsm|0.5.7

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No @

**Comment by maxibanki** [comment]
Please provide us more information, with only the feed URL to the GitHub Guides we can't do anything.
Thanks!
