### ISSUE TITLE
Terminal suddenly goes black (Powershell)

### ISSUE THREAD

**Issue by Yomag84** [Microsoft/vscode#41009]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:02.926Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
phpserver|bra|2.2.0
php-autocomplete|bsc|0.4.2
vscode-markdownlint|Dav|0.12.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
vscode-generate-getter-setter|DSK|0.4.2
Vue2|duc|0.1.3
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.24
php-debug|fel|1.12.1
php-pack|fel|1.0.1
vscode-javac|geo|0.0.47
beautify|Hoo|1.1.1
composer|ika|0.7.1
phpcs|ika|0.7.0
vscode-react-typescript|inf|1.0.12
debugger-for-phantomjs|ira|0.1.1
code-file-nav|jak|0.7.2
Angular1|joh|0.2.0
Angular2|joh|2.11.2
awesometypescriptproblemmatcher|Jua|0.3.0
format-indent|Kas|1.3.0
format-php|Kas|1.1.2
php-symbols|lin|2.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
phpcsfixer|mak|0.0.1
HTMLHint|mka|0.4.0
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.26
debugger-for-chrome|msj|4.0.0
debugger-for-edge|msj|0.4.1
debugger-for-ios-web|msj|0.1.2
tsimporter|pmn|1.2.14
ts-import-assistance|Sam|0.0.10
php-ci|sma|0.2.8
php-formatter|Sop|0.2.4
rf-intellisense|Tom|2.0.0
Angular2|UVB|0.4.1
cordova-tools|vsm|1.3.1
bootstrap-3-snippets|wcw|0.1.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Please include enough details to reproduce the issue

**Comment by Yomag84** [comment]
How?

**Comment by Tyriar** [comment]
@Yomag84 what did you do before the terminal went black? What's in your settings.json file, can you show a screenshot of the "black" terminal before/after?

**Comment by Yomag84** [comment]
I noticed every time I run some ionic cmd (like testing a live reloading of an app), then leave it for sometime to check up on some other things for like 3 to 5mins and above. By the time I check up to continue, it'll have already turned black.

Initial status
![terminal-bfore](https://user-images.githubusercontent.com/7047105/34575918-93312a8c-f17c-11e7-8262-992ac204f536.png)

Later
![terminal](https://user-images.githubusercontent.com/7047105/34575929-9aeb65a8-f17c-11e7-9f2d-da0715ed8739.png)

**Comment by Tyriar** [comment]
Whoa it's really black, I haven't seen this before. Does resizing fix the issue? If not does zooming the window in and out fix it (ctrl++, ctrl+-)?

I'm guessing somehow the canvas is getting corrupted similar to what can happen when the computer sleeps (upstream Chromium bug).

**Comment by Yomag84** [comment]
Yes, resizing fixed the issue.
