### ISSUE TITLE
Hide extension list in issues under <details> tag

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#41008]
<ul>
<li>VSCode Version: Code - Insiders 1.20.0-insider (f9115349ef09cfef2bed669680d10ac58b490dce, 2017-12-21T16:36:58.030Z)</li>
<li>OS Version: Windows_NT x64 10.0.16299</li>
<li><details><summary>Extensions</summary>

| Extension | Author (truncated) | Version |
| --- | --- | --- |
| vscode-docker | Pet | 0.0.22 |
| githistory | don | 0.2.3 |
| tstools | iBo | 1.1.3 |
| docthis | joe | 0.6.0 |
| restructuredtext | lex | 47.0.0 |
| code-beautifier | mic | 1.7.2 |
| debugger-for-chrome | msj | 4.0.0 |
| typescript-hero | rbb | 1.8.0 |
| java | red | 0.16.0 |
| vscode-icons | rob | 7.19.0 |
| sonarqube-inject | sil | 1.3.1 |
| autoimport | ste | 1.5.3 |
| vscode-java-debug | vsc | 0.5.0 |
| vscode-java-pack | vsc | 0.2.0 |
| ReactSnippets | xab | 1.7.0 |
| markdown-pdf | yza | 0.1.7 |
| markdown-all-in-one | yzh | 0.11.2 |
</details>
</li>
</ul>
Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

---
Use cases:
* Issue that doesn't give any useful information (only title **notign Works!!!Fix!**)
* Known issue of the release
* Known issue in general
* Author specified `Reproduces without extensions: Yes`
* Less visual noise in any way

**Comment by Tyriar** [comment]
@octref I think you were working on the new issue reporting stuff so I guess this should go to you. Tbh I'm not sure if this is good or bad as people could potentially gloss over the fact that the report has extensions active.
