### ISSUE TITLE
Lack of correlation between action identifier and label ("editor.action.commentLine")

### ISSUE THREAD

**Issue by ivan-radic** [microsoft/vscode#41003]
Essentially this is version, extension, and architecture independent, but it was tested on:
- VSCode Version: 1.19.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open Default keybindings file
2. Search for "toggle comment" or "toggle line comment"
3. Nothing is found
4. Give up
or
5. Spend some time doing google search
6. Discover "editor.action.commentLine"

Proposal:
I propose to rename vague term "editor.action.commentLine" into much more explicit "editor.action.toggleComment".

Rationale.
All editors I am aware of use term "toggle line comment" for toggle operation. New users, like myself, might conclude that editor does not support this operation simply because "editor.action.commentLine" lacks key term "toggle".

Proposed solutions:
1. Rename "editor.action.commentLine" to "editor.action.toggleComment" in keybindings file.
You might also need to change other source code files, but I presume it would just be a global replace operation.
Consequences: This would not be backward compatible with any extension that might use "editor.action.commentLine". I can think of key remapping extensions, but others might be affected too.

2. Add a comment next to "editor.action.commentLine", stating something like // this command performs toggle opration
Consequences: None

Personally, I would prefer solution1, but I cannot predict all the consequences of it, as I am not familiar with VSC code base at all.

Cheers and thanks for a great editor!
Ivan

**Comment by ivan-radic** [comment]
Hi,

just noticed, while looking for something else, that editor is already using term "toggle" in command bar options (in edit menu):

![2018-01-06 17_59_13-](https://user-images.githubusercontent.com/12585358/34641942-9bc6e05c-f30b-11e7-8caa-a66777e69e6d.png)

I guess that would be another reason to go with proposed solution 1, and to use `editor.action.toggleLineComment` and `editor.action.toggleBlockComment` wording.

Cheers,
Ivan

**Comment by alexandrudima** [comment]
The root problem here is that there is no correlation between an action identifier and action label when editing keybindings in "expert" mode via `keybindings.json`. `keybindings.json` uses action identifiers, which will be different from labels, especially for localized versions of VS Code. 

For example, the Italian label `"Attiva/Disattiva commento per la riga"` has almost nothing in common with `editor.action.commentLine`.

We have tried to compensate for this problem with the keybindings editor (ctrl+k ctrl+s) which should cover most of the scenarios, but you are correct, when going to `keybindings.json` there is no correlation between id and label.

---

We cannot change action identifiers. Users might have built `keybindings.json` files using the existing identifiers and once they are out, they become sort of API, they must continue to work.

---

I am thinking we should perhaps enrich the bottom section of `keybindings.json` with a list of id <-> label.
