### ISSUE TITLE
error when launching visual studio

### ISSUE THREAD

**Issue by lilletech** [Microsoft/vscode#41006]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
githistory|don|0.2.3
tstools|iBo|1.1.3
docthis|joe|0.6.0
restructuredtext|lex|47.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|4.0.0
typescript-hero|rbb|1.8.0
java|red|0.16.0
vscode-icons|rob|7.19.0
sonarqube-inject|sil|1.3.1
autoimport|ste|1.5.3
vscode-java-debug|vsc|0.5.0
vscode-java-pack|vsc|0.2.0
ReactSnippets|xab|1.7.0
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.11.2

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

Once more details are provided I will gladly reopen
