### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by kumardeepak** [Microsoft/vscode#41007]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.5.0
yaml|ada|0.0.9
jslint|ajh|1.2.1
npm-intellisense|chr|1.3.0
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
svn-scm|joh|1.5.0
debugger-for-chrome|msj|4.0.0
swaggitor|qns|0.1.1
react-beautify|tai|0.3.0

(2 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by cleidigh** [comment]
@kumardeepak 
Please provide some information and a better issue title.
