### ISSUE TITLE
The 'find in file' shortcut Ctrt+Shift+F not work

### ISSUE THREAD

**Issue by warmilk** [Microsoft/vscode#41014]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.12.0
vscode-eslint|dba|1.4.3
wpy-beautify|doi|2.0.10
vscode-html-css|ecm|0.1.8
vscode-npm-script|eg2|0.3.3
vscode-element-helper|Ele|0.5.1
auto-close-tag|for|0.5.5
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
vue-snippets|hol|0.1.5
beautify|Hoo|1.1.1
path-autocomplete|ion|1.8.0
NodeAssertionSnippets|jay|0.1.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
start-git-bash|McC|1.2.1
code-beautifier|mic|1.7.2
vscode-csscomb|mrm|5.2.1
vuejs-extension-pack|mub|0.3.0
vetur|oct|0.11.5
vuehelper|oys|0.1.0
sass-indented|rob|1.4.6
vscode-sass-format|sas|1.1.2
html5-boilerplate|sid|1.0.1
JavaScriptSnippets|xab|1.5.0
html-css-class-completion|Zig|1.15.0

---

Steps to Reproduce:

1.Below is my user setting
2.
![image](https://user-images.githubusercontent.com/14016918/34474074-0a7fb1cc-efb5-11e7-92e7-4b3330dbc194.png)

Reproduces without extensions: No，all extensions is working

**Comment by usernamehw** [comment]
Can you explain: what are you trying to achieve with this? 
btw, the 2nd command does not exist: `workbench.action.findInFilesWithSelectedText`.

**Comment by usernamehw** [comment]
Are you trying to alter its behavior or just make it work? If you comment out all 4 - it will use the default keybindings.

**Comment by warmilk** [comment]
the setting all 4 - are copy from default setting,
but the ctrl+shift+F don't work when the course focus on editor

**Comment by warmilk** [comment]
I found the cause of the problem, because the sogou Chinese pinyin input method hot key occupancy
