### ISSUE TITLE
Dimmed Monokai Theme  scope conflict

### ISSUE THREAD

**Issue by u2berggeist** [Microsoft/vscode#41012]
- VSCode Version: 1.19.1
- OS Version: Windows 10

More of an "FYI, this probably isn't right", than a bug or anything. 

For the `dimmed-monokai-color-theme.json`, there are two color definitions for the scope `constant.language`. The name of the conflicting themes are `Built-in Constant` and `Language Constant`. Personally, I think the color used in `Built-in Constant` is much better, but that's probably above my pay-grade.

**Comment by Tyriar** [comment]
@u2berggeist nice find! Do you have some example code that would be styled with these scopes? Would be good to compare. I'm also hesitant to change the existing color unless it looks really out of place.

**Comment by u2berggeist** [comment]
It's less "this color looks really out of place" and more "I was looking through the file and noticed something".

I'm working on creating a Language support extension (hence why I'm looking through the theme file), so I'll reference that for right now. I totally might not be defining scopes correctly for my language though. 

The variable `pi` is a constant predefined in the language, so I've set it as `constant.language`. You can see that the `pi` in Monokai Dimmed sticks out quite a bit while in Monokai regular it's a good bit more subtle.

### Monokai Dimmed:
![Monokai Dimmed](https://user-images.githubusercontent.com/20801821/34490898-5b6ff7dc-efaf-11e7-9c8d-84b09e367ad3.png)

### Monokai Regular:
![Monokai Regular](https://user-images.githubusercontent.com/20801821/34490813-1064aabc-efaf-11e7-9120-5f90b3981ffc.png)

The color code that the theme is diverting to is for the `Language Constant` dictionary entry:
![#FF0080](https://user-images.githubusercontent.com/20801821/34491346-19a54b8e-efb1-11e7-9459-ca592886d330.png)

The color code for `Built-in constant` is this:
![#408080](https://user-images.githubusercontent.com/20801821/34491414-54bae436-efb1-11e7-97c7-d8cfe7378b5f.png)

IMO, the `#FF0080` kinda sticks out from the more mellow color pallet than `#408080` does. Either way, I mainly brought this up due to the conflict rather than the color choices.

Let me know if you need anything else.

**Comment by Tyriar** [comment]
Thanks for the info, I removed language constant as it does looks a bit out of place. It was probably just left over from the original conversion from monokai.
