### ISSUE TITLE
 更新后写ReactNatieve没有代码提示了，比如 <Touchable onPress={}>  After updating, ReactNatieve has no code hints, such as <Touchable onPress={}>

### ISSUE THREAD

**Issue by caozhepeng** [Microsoft/vscode#41023]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
file-icons|fil|1.0.7
vscode-angular2-emmet|jak|2.0.3
console-log-snippet-javascript|lev|0.1.0
node-debug2|ms-|1.20.0
sublime-keybindings|ms-|3.0.3
debugger-for-chrome|msj|4.0.0
vscode-stylesheet-beautify|n23|0.0.3
js-jsx-snippets|sky|0.0.7
react-es6-class-migration|thi|1.0.2
vscode-react-native|vsm|0.5.7
html-snippets|wge|0.1.5

(1 theme extensions excluded)

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by mjbvz** [comment]
1. Does this repo with all extensions disabled?
2. Please provide a code example or small example project
