### ISSUE TITLE
i can't see the explorer, git and extension icons in the left sidebar

### ISSUE THREAD

**Issue by mouadFahsi** [Microsoft/vscode#41021]
- VSCode Version: 1.19.1
- OS Version: windows 10

Steps to Reproduce:

1. launching the app normally
i can't see the explorer, git and extension icons in the left sidebar 
![2018-01-02_vscode](https://user-images.githubusercontent.com/20311674/34478986-f10ffc06-ef9b-11e7-9907-920fd0f439e2.jpg)

**Comment by jens1o** [comment]
Could you try reinstalling the editor?

**Comment by mouadFahsi** [comment]
I did that and removed the .vscode folder (i think that is the name of the folder) but the issue is still there right now i'm using the insiders version

**Comment by jens1o** [comment]
What happens if you click on those three dots?

**Comment by mouadFahsi** [comment]
Nothing happend, but if i used the keyboard shortcuts like alt + ctr + e the explorer icon showes and if i used shortcuts for the extensions or the git the explorer icon disappear and the new icon showes

**Comment by isidorn** [comment]
@mouadFahsi sorry about that. Right click on the activity bar and you can select the viewlets to bring them back.
You can also use the insiders version which has a fix for this.
Closing as duplicate

**Comment by craigneasbey** [comment]
Can someone please link this "duplicate" to the bug?  I am unable to find it.

**Comment by isidorn** [comment]
@craigneasbey this should be fixed in latest vscode. Just first use right click on the left bar to bring back all the views. If after that it still happens please let me know.

**Comment by craigneasbey** [comment]
@isidorn I am on the latest released version, 1.19.3. Yes, I can right click and get one activity bar item at a time back but when I restart, it goes back to the mobile activity bar again. Thanks.

**Comment by isidorn** [comment]
@craigneasbey What do you mean by the mobile activity bar? 
So you bring them all back, and they always disapear on restart?

**Comment by craigneasbey** [comment]
@isidorn "Mobile" = responsive three dots.
Yes, they disappear on restart except they do not all come back, only one at a time, when you click on another one in the right click menu, it replaces the other one. There is only ever one there.

**Comment by isidorn** [comment]
@craigneasbey can you also reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/

Can you also reproduce in vscode stable if you delete `workbench.activity.pinnedViewlets` from your storage? F1 > developer tools > application > Local Storage >

**Comment by craigneasbey** [comment]
@isidorn Sorry for the delay. I have not installed insiders build yet.  I may in the future.

Deleing _workbench.activity.pinnedViewlets_ from _storage://global/workbench.activity.pinnedviewlets_, manually right clicking and adding the activity items back fixed it.  It was an empty array.  After adding back in its value is now: _["workbench.view.explorer","workbench.view.search","workbench.view.debug","workbench.view.scm","workbench.view.extensions"]_

thanks for your help.
