### ISSUE TITLE
Search leads to incorrect locations when clicking the results

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#41026]
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

When searching for something, clicking on the search results will sometimes lead to incorrect locations, searching again will fix it, I can't reproduce this reliably though.

It's important to note that I haven't searched, modified these files and then click the results.

**Comment by roblourens** [comment]
I haven't seen this - would be very helpful if you can find a consistently reproducible case.

**Comment by eyalsk** [comment]
@roblourens I'll close it for now, atm I don't work on any PHP project and I it only happened there, might be related to the PHP plugin I've used, not sure. :)
