### ISSUE TITLE
Feature: Optionally filter intellisense errors from problems pane

### ISSUE THREAD

**Issue by lurium** [Microsoft/vscode#41028]
- VSCode Version: 1.19.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install C++ extension
2. Open a C++ file that won't compile
3. See a pre-emptive list of assumed compilation errors in the problems pane

Desired behavior:

Optionally filter intellisense errors from problems pane.  These errors are not often useful because of compiler differences.

Reproduces without extensions: No

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
