### ISSUE TITLE
README and CHANGELOG in marketplace: UTF8-BOM breaks heading in first line

### ISSUE THREAD

**Issue by MofX** [microsoft/vscode#41025]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Create a README or CHANGELOG file of an extension with encoding utf8-bom and add a markdown markup, that has to start at the beginning of a line in the first line (e.g. # for heading)
2. Look at the file in the extension marketplace. The markup is ignored

[README.txt](https://github.com/Microsoft/vscode/files/1597480/README.txt)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
We could maybe strip the BOM in VSCE...

cc @modigrv

**Comment by MofX** [comment]
Stripping the BOM sounds like a bad workaround for a bug in the markdown parser. Is the markdown parser for the extension a different one than in the markdown preview window? Because it works perfectly there.

Can stripping the bom result in a wrongly detected encoding? I like utf8 or 16 with bom, because it explicitly defines the encoding of the file.

**Comment by joaomoreno** [comment]
> Look at the file in the extension marketplace

Do you mean the browser, at https://marketplace.visualstudio.com/?

**Comment by MofX** [comment]
No the embedded one in vscode. I haven't tried publishing with the BOM

**Comment by joaomoreno** [comment]
Can you show me a screenshot?

**Comment by MofX** [comment]
![withbom](https://user-images.githubusercontent.com/1215681/35317099-5ccacae4-00d5-11e8-8cbc-b325f0358271.png)
![withoutbom](https://user-images.githubusercontent.com/1215681/35317100-5ce13d74-00d5-11e8-95d0-8c3dad86452b.png)

**Comment by joaomoreno** [comment]
@mjbvz Can we strip BOM before giving it to the Markdown parser?

**Comment by mjbvz** [comment]
Closing due to lack of further user interest expressed in this issue over the past two plus years
