### ISSUE TITLE
Documentation on commands/actions

### ISSUE THREAD

**Issue by tuckermiller** [Microsoft/vscode#41038]
Is there a comprehensive list of commands/actions in the VS Code documentation? If so, I think it should be more clearly linked to from the keybindings page and if not (I couldn't find it personally) there should be. For example, from the keybindings page:

"You can invoke a command with arguments. This is useful if you often perform the same operation on a specific file or folder. You can add a custom keyboard shortcut to do exactly what you want.

...

The type command will receive {"text": "Hello World"} as its first argument and add "Hello World" to the file instead of producing the default command."

^ That's very useful information to know, but unless you put it there as an example how would I even find out about the type command? How am I supposed to know what commands take arguments? Etc etc. From the same page:

"Below are the some of the possible when clause contexts which evaluate to Boolean true/false:

...

The list above isn't exhaustive"

Where is the exhaustive list? It would really be useful if this was available, anywhere, for people to read.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-docs#1328
