### ISSUE TITLE
File association "lang-cfml" is broken

### ISSUE THREAD

**Issue by adamharlow** [Microsoft/vscode#41034]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: ilich8086.coldfusion

Extension|Author (truncated)|Version
---|---|---
coldfusion|ili|1.0.1
vscode-icons|rob|7.19.0
shell-launcher|Tyr|0.1.6

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Under files.associations, set *.inc to "lang-cfml"
2. Try to enter ColdFusion or HTML code in .inc file

Reproduces without extensions: N/A (extensions required)

**Comment by aeschli** [comment]
What language is `lang-cfml`?

The language that coldfusion contributes has id `cfml`:
![image](https://user-images.githubusercontent.com/6461412/35451263-f08844fc-02c2-11e8-8e3e-01d0adc58114.png)
