### ISSUE TITLE
Chinese (zh-Hans) translation of keyboard shortcuts keymap wanted

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [Microsoft/vscode#41035]
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

# i18n & L10n

> zh-Hans is wanted!

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows-zh.pdf

**Comment by auchenberg** [comment]
@gregvanl Should we move this to the docs repo?

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1363
