### ISSUE TITLE
New feature : Workspace switcher

### ISSUE THREAD

**Issue by Stephan256** [Microsoft/vscode#41031]
**Request for new features**

Why not add an accordion with Workspace shortcut ?

_And VS Code would still be so much better..._

___

- VSCode Version: 1.19 
- OS : Windows 10

**Comment by bpasero** [comment]
There is a fast way to switch workspaces:

![image](https://user-images.githubusercontent.com/900690/34513261-c10dc1ce-f067-11e7-973c-3debe983dc62.png)
