### ISSUE TITLE
restoreWindows setting ignored by vscode

### ISSUE THREAD

**Issue by fonnesbeck** [Microsoft/vscode#41039]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 17.4.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|3.11.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|7.2.0
file-icons|fil|1.0.7
shell-format|fox|1.1.1
mdmath|goe|2.0.7
Python-autopep8|him|1.0.2
MagicPython|mag|1.0.12
python|ms-|0.9.1
jinja|who|0.0.8
markdown-pdf|yza|0.1.7
markdown-all-in-one|yzh|0.11.2

(6 theme extensions excluded)
---

Steps to Reproduce:

1. Set the following preference `"window.restoreWindows": "none"`
2. Close `vscode`
3. Restart `vscode`
4. Observe previous documents open, despite setting

When I open a new session under the setting above, I expect no open windows, yet previous windows always appear on startup.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@fonnesbeck I cannot reproduce, for me an empty window opens. How do you restart VS Code? Can you share a screencast?

**Comment by fonnesbeck** [comment]
I restart the app via `code .` from the Terminal. [Here is a screencast of the behavior](https://d.pr/i/gM5ed0).

**Comment by bpasero** [comment]
@fonnesbeck weird. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by fonnesbeck** [comment]
The problem does not reproduce in the nightly build, so I will just look forward to having this fix show up in a future release. Thanks.

**Comment by fonnesbeck** [comment]
Actually, scratch that -- I just opened a nightly build window in a directory via `code-insiders .` and it re-opened windows from a previous session. Can this issue be re-opened, or shall I open another?
