### ISSUE TITLE
Reload when debugging an extension does not always reconnect debug session

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4103]
1. Create a 'hello world' VSCode extension
2. Start to debug that extension from VSCode, a secondary window will be launched
3. Reload the seconday window, VSCode does not always reconnect. Sometimes it does, sometimes not so it might be a timing issue

I did not touch code in this area, so giving first to you. Give back to me if you think it is on the vscode side - I quickly checked and did not find anything very obvious.

**Comment by isidorn** [comment]
I also see some 'evaluate' exception in the console so this might be related to the changes you mentioned in the standup - being able to evaluate `Promise`

**Comment by weinand** [comment]
could not reproduce.
