### ISSUE TITLE
Explore new text buffer for performance improvement

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#41042]
Currently our text buffer is on top of an array which stores all lines of a file, it behaves well in most cases (accessing, editing, etc are all fast). When the size of a file or the line breaks count increases, it takes more time to build the text buffer as we are splitting the content by line breaks, and holds more memory. We'll explore some other text buffer implementation to improve the performance and memory usage of above case, with reasonable time loss of line accessing, editing, etc.

Benchmark: Performance and Memory Usage Metrics
* Model Builder (*for file loading*)
* GetLineContent (*for display and tokenization*)
* GetLineContent after edits
* Edits
* Search and Replace

**Comment by rebornix** [comment]
It's difficult to tell which implementation is better, whether two buffers are behaving similarly, or whether the text buffers scale or not, by reading tables. Here I converted them to charts and then we can have an intuitive feeling of the benchmarks.

### Model Building/File loading
![image](https://user-images.githubusercontent.com/876920/35404101-a32a0f86-01b6-11e8-9c3f-77e59237f39e.png)

### Mem usage
![image](https://user-images.githubusercontent.com/876920/35404118-b1a37d4a-01b6-11e8-97dc-d61c13c694c5.png)

Memory usage of Piece Tree is close to the real file size.

### Edits
1000 random edits

![image](https://user-images.githubusercontent.com/876920/35404181-e7d6ee60-01b6-11e8-9505-48f2c899290e.png)

1000 sequential inserts
![image](https://user-images.githubusercontent.com/876920/35404192-f081aff0-01b6-11e8-8a12-6fd557935e74.png)

Line Model chokes when the file size increases, while Piece Tree is really stable.

### Read All Lines

![image](https://user-images.githubusercontent.com/876920/35404228-19b1e64c-01b7-11e8-8141-543cf88508d9.png)

![image](https://user-images.githubusercontent.com/876920/35404230-1c9875ba-01b7-11e8-8d69-cd5ff6410a83.png)

This is a big TODO for piece tree, search caching can boost it a lot and we'll revisit this benchmark once that's done.

### Read 10 random windows

![image](https://user-images.githubusercontent.com/876920/35404542-2fc6cc8a-01b8-11e8-8124-9ba3da41d5c6.png)

![image](https://user-images.githubusercontent.com/876920/35404546-340af280-01b8-11e8-956a-169d9317e9eb.png)

Similar to Read All Lines, we can optimize this case but single digit ms is good always.

### Replace All

![image](https://user-images.githubusercontent.com/876920/35404607-6ddd34d2-01b8-11e8-8f16-c0a09935d7b9.png)

![image](https://user-images.githubusercontent.com/876920/35404610-70d7639c-01b8-11e8-96bc-6b76044d2e18.png)

![image](https://user-images.githubusercontent.com/876920/35404614-736d560c-01b8-11e8-8be0-a161c29b72e0.png)

At this moment, our Piece Tree doesn't do bulk edits, which gives us some space to improve.

**Comment by rebornix** [comment]
As mentioned above, we have some ways to improve the speed of `getLineContent`. Adding search cache is one obvious solution but after profiling, I found that more time is spent elsewhere

* Originally there is one internal api on Piece Tree buffer `getLineRawContent`, which contains the line break. To make the buffer appeal to text model api, I create a new function will will trim the line break at the end. And without surprise, when you have a lot of lines and the string is long, trimming is costly
* Instead of using `(position: Position)` as parameter, using `(line: number, column: number)` reduces object creation and gc

![image](https://user-images.githubusercontent.com/876920/35939856-40564658-0c02-11e8-8318-4eb95f8bbaf7.png)

![image](https://user-images.githubusercontent.com/876920/35939868-4769e364-0c02-11e8-814c-66111d23a6d3.png)

This optimization is easy and effective, just avoid bad code.

**Comment by jens1o** [comment]
> and some manually created large files (I'll replace these files once I found realistic large files)

Password lists ftw 
https://github.com/danielmiessler/SecLists/tree/master/Passwords

**Comment by rebornix** [comment]
@jens1o ideally we should do that and we already did similar things like when the document is readonly, we can opt in a simple version of text model. However for current situation, switching between Line Model and Piece Tree is not a good idea because

* Line Model works better when the file size is small **and** line count is small.
* Users can' tell the difference between Line and Piece Tree when the file is small
* The way to know if the file is small is easy as we check file metadata at the very beginning, checking how many lines a file has is costly, it requires going through the whole content. It means we can't know about this info in advance.
  * Piece Tree Model Builder ~= Going through the content and find line break
  * Line Model ~= Going through the content, find line break and do line splits (heavy operation). 
* Model switching simply means more time in file opening.

Let's explain the last bullet point, why modeling switching makes file opening slower.  Say the line count magic number is 1 million, file size is 64MB.

If we choose Line Model Builder as the default one, it's simple when no model switching needs to happen. When it does

* Say we receive 1000 chunks (64KB each) and we know the line count is already larger than 1M.
* We handle following chunks by Piece Tree Model Builder
* We need to sanitize the first 1000 chunks as it has 1M lines, we can't simple use them as 1M chunks as that would slow down all operations
* The way to do sanitization is string concatenation, reconstructing 1000 chunks from 1M lines

The last step is costly and on top of that, when we access these chunks next time, V8 will flatten these cons-string and GC will kick in. For short, going this way will lead to longer file opening and potential UI freezing for ~100ms for large files. 

If we choose Piece Tree Model Builder as the default one, then for all small files, our file opening is slower than before as 

And then if we do text buffer switching, this is the moment as we know if the line count exceeds a magic number or not. Then we need to build Piece Tree from what we already have. Piece Tree is chunk based while Line Model is line based, should we do string concat to make each chunk 64KB again? If not, we lost all the benefits of having readonly original chunks; If we do so, say we do string concat and make the chunk size around 64KB, once we access this string next time (find, substr), V8 will flatten the string and gc may kick in.

**Comment by jens1o** [comment]
Thanks for your advanced explanation, and yes, it makes sense. Thanks for the heads up!
