### ISSUE TITLE
Format Document not working for .c and .cpp files in several archlinux workstations

### ISSUE THREAD

**Issue by acauquil** [Microsoft/vscode#41044]
- VSCode Version: Code 1.19.1 (0759f77, 2017-12-19T09:41:01.414Z)
- OS Version: Linux 4.14.6-1-ARCH
- Extensions: ms-vscode.cpptools,  austin.code-gnu-global

Hi folks !

I'm having an issue when trying to use Format Document command in .c and .cpp files. No indentation is happening, thus working on javascript and all other languages I tested. Same issue with a coworker with the same up-to-date archlinux install, with and without extentions [C/C++] by Microsoft and [C++ Intellisense] by austin.

**Comment by mjbvz** [comment]
Please file this issue against the Cpp tools extension
