### ISSUE TITLE
Explore improvements to settings editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#41040]
Things to investigate

- Left-side editing
  - Context menu option to edit value
  - ~CodeLens to edit value~
  - ~Move pencil icon to value~ It actually was on the right side previously. It may actually be less noticeable after a long value, it may wrap to the next line, etc. Putting it in between the key/value seems weird, and we don't want it to overlap any text.
  - Replace the pencil icon with a highlight over the value. Clicking anywhere on it shows the edit menu. It acts functionally more like a dropdown.
  - ~Make pencil icon always visible~ 
  - Indicate the value of an edited setting on the left
    - Or just indicate that a setting is overridden by something on the right
- Right-side editing
  - ✅ Auto fix missing commas #42232
  - Autosave when editing manually
- Search
  - Can't focus the cursor at the current setting with the keyboard
  - ✅ Weird `<enter>` nav order #42126
    - ~~Should go over all overridden settings first~~
    - ~~Navigate through the other settings domains?~~
  - Can't see if a setting is actually overridden in another settings domain tab
    - ✅ After a search, the number of matches should be shown in the User, Workspace, Folder tabs https://github.com/Microsoft/vscode/issues/42377
  - ✅ Add keyboard shortcut to trigger edit of selected setting #42124
    - Or the setting under the cursor
    - Or to focus (one of) the editors so we can then do something with the cursor
- Right side
  - Reorder and group User Settings
    - Or make an extension to do this
  - Filter User Settings
- Quick Open to manage settings (like @sandy081's extension)
- Easy editing of common settings from the welcome page
- Add quick fix for settings from non-installed extensions on the right side. Example: `lcov` settings in vscode workspace settings

**Comment by roblourens** [comment]
Photoshop mockups

- Context menu option to edit value
![contextmenu](https://user-images.githubusercontent.com/323878/34496432-65b36eb4-efae-11e7-99b4-381b38f89642.png)

- CodeLens to edit value
![codelens](https://user-images.githubusercontent.com/323878/34496444-7388624c-efae-11e7-9bb8-7ac22d6d712d.png)

- Move pencil icon to value
![value_widget 0 hidden](https://user-images.githubusercontent.com/323878/34496450-7cf144a2-efae-11e7-9418-c975655ae8f8.png)
![value_widget 1 visible](https://user-images.githubusercontent.com/323878/34496451-7e192afc-efae-11e7-980f-6e5e5eb4baba.png)
![value_widget 2 expanded](https://user-images.githubusercontent.com/323878/34496453-7f86615c-efae-11e7-8f05-79cf6b20a012.png)

- Indicate the value of an edited setting on the left
![current value 0](https://user-images.githubusercontent.com/323878/34496481-9e9747be-efae-11e7-97a3-8a4845957bf4.png)
![current value 1](https://user-images.githubusercontent.com/323878/34496482-9eae9d10-efae-11e7-8980-f889063e89fd.png)
![current value 2](https://user-images.githubusercontent.com/323878/34496483-9ecc6a52-efae-11e7-914a-c081a49a1530.png)

- Or just indicate that an extension is overridden by something on the right
![indicator](https://user-images.githubusercontent.com/323878/34496501-abc84d16-efae-11e7-80fa-a21789c271c9.png)

**Comment by sandy081** [comment]
@roblourens I liked the one which you demoed in slack that showing some affordance on hover and clicking on it shows the context menu. Not sure if there are improvements on top of it.

**Comment by patrys** [comment]
>Indicate the value of an edited setting on the left

What if left side indicated the effective value and the comment said `// default is "off"`?

**Comment by roblourens** [comment]
Click on value to edit:

![jan-05-2018 11-58-03 1](https://user-images.githubusercontent.com/323878/34732809-2dedd290-f51b-11e7-8590-087386ef453b.gif)

@patrys One complication is that the setting can be overridden by User, Workspace, or Folder settings. If we show the value for the currently selected settings scope, it might confuse someone if that setting is overridden in a different scope. And if it's overridden differently for different folders in a multiroot workspace, then there is no one "effective value".

**Comment by patrys** [comment]
If there are multiple values then which scope would be affected when I click to change the value?

**Comment by roblourens** [comment]
The one that's selected on the right - same as what happens currently when you edit a setting using the pencil button.

That's what keeps this from just being a typical dropdown.

**Comment by sandy081** [comment]
@roblourens How about providing some assistance to inform users that the value change will happen in the right hand side editor? Otherwise, it might confuse new users who are not aware of this.

**Comment by roblourens** [comment]
> Add keyboard shortcut to trigger edit of selected setting

![jan-17-2018 18-26-23](https://user-images.githubusercontent.com/323878/35077849-08449a3e-fbb4-11e7-9428-0084dae117a7.gif)


Demo in https://github.com/Microsoft/vscode/tree/roblou/editPreferenceCommand

**Comment by roblourens** [comment]
> Auto fix missing commas

![jan-17-2018 21-26-38](https://user-images.githubusercontent.com/323878/35082168-3314a9de-fbcd-11e7-9d62-64ac28dfb2aa.gif)

Adds a save listener to the configuration-editing extension, which parses the document and fixes missing commas, the best it can.

**Comment by patrys** [comment]
@roblourens Since autocomplete knows that it's completing a setting name, could it not, at the moment you accept a *setting name* as a suggestion, take care of inserting a missing comma at the end of the previous non-empty line? It seems that this would be less magic and less error-prone than trying to fix an entire file on save.

**Comment by roblourens** [comment]
It should work whether you are using intellisense, or typing the full name, or copy/pasting from the left side, or anything else.

Also, the intellisense completion would be changing the previous line at some arbitrary position, which I think isn't possible for basic completions.

**Comment by sandy081** [comment]
Moving to February to follow up on further improvements

**Comment by fabiospampinato** [comment]
My experience with editing settings would be much better if there was a "Open Raw User Settings" command. Always splitting the editor makes it hard to edit the settings while having them to the side

**Comment by fabiospampinato** [comment]
But that's not something you always want, just sometimes. An additional command would be much more usable.

**Comment by fabiospampinato** [comment]
@roblourens pushing again for an `Open Raw User/Workspace Settings` command, I hope we do agree that there's a problem if it's more ergonomic to edit a workspace's settings file in another VSC instance, just to avoid the split editor (I'm making a theme, so editing the settings on one side and checking the results on the other):

<img width="1440" alt="screen shot 2018-05-08 at 19 21 09" src="https://user-images.githubusercontent.com/1812093/39772491-b5dc8010-52f5-11e8-88c8-2b1ee399b8f6.png">
<img width="1440" alt="screen shot 2018-05-08 at 19 21 33" src="https://user-images.githubusercontent.com/1812093/39772493-b5fae528-52f5-11e8-998a-7ed5ae7ba763.png">

**Comment by roblourens** [comment]
I opened https://github.com/Microsoft/vscode/issues/49495 for it
