### ISSUE TITLE
"Reveal Active File In Side Bar" should focus into Side Bar

### ISSUE THREAD

**Issue by jefk** [Microsoft/vscode#41043]
- VSCode Version: 1.19.1 
- OS Version: Mac OS 10.13.2

Steps to Reproduce:

1. Open the command palette and select "File: Reveal Active File in Side Bar"
2. Notice that focus is still inside the active editor, not Side Bar

Reproduces without extensions: Yes

## Reveal active file in side bar should focus into Side Bar

It's really handy to be able to see and open what files are in the same directory as your currently active editor. If the side bar was focused after revealing, users could use the keyboard to navigate files in the same directory, and easily open them without the mouse.

**Comment by nocash** [comment]
@jefk Try using the command "File: Focus on Files Explorer". I think that behaves more like you're expecting.

**Comment by jefk** [comment]
Command naming could be better, but that's a separate issue. I'll close this one.
