### ISSUE TITLE
First debug start has no effect if 'preLaunchTask' is watching

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#4105]
1. Have a `launch.json` with a 'preLaunchTask' that is watching
2. Start debugging - no effect, only the second start does the job

**Comment by isidorn** [comment]
@joaomoreno  about 2 weeks ago you filed an issue about an error from a watch task is not bein respected and that debug gets run anyways. We need to verify that scenario again. I tried to dig up that bug, but could not. Can you give me a pointer to that bug if you can find it on github please

**Comment by joaomoreno** [comment]
@isidorn This is all I could find #2370

**Comment by isidorn** [comment]
That's not the one I was looking for, anyways when verfying this please try the following 4 scenarios:

* watching task that does not produce errors
* watching task - errors
* non watching task - no errors
* non watching task - errors
