### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by alanneese** [Microsoft/vscode#41056]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.0
vscode-eslint|dba|1.4.3
tslint|eg2|1.0.24
vscode-great-icons|emm|2.1.22
seito-openfile|Fr4|1.4.0
classic-asp-html|jtj|0.0.9
vscode-duplicate|mrm|1.2.0
sublime-keybindings|ms-|3.0.3
LiveServer|rit|3.0.2
vscode-icons|rob|7.19.0
markdown-preview-enhanced|shd|0.3.1
html-css-class-completion|Zig|1.15.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Stretch out the app VS code to the top of the screen and to the bottom of the screen.
2.  Close the app and restart VS code.  The bottom of the app will not be to the very bottom of the screen.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Likely same as https://github.com/Microsoft/vscode/issues/22010
