### ISSUE TITLE
Copy / Paste does not  work when going to a 32-bit program 

### ISSUE THREAD

**Issue by msrost** [microsoft/vscode#41055]
When copying from VS Code unable to paste copied contents into a 32-bit Oracle PL/SQL Developer program. I am able to paste into Notepad.exe and Chrome.exe

Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open VS Code 64-bit
2. Open File
3. Ctrl + A to select all contents
4. Ctrl + C to copy selection
5. Go to a 32-bit program (I'm using Oracle PL/SQL Developer 32-bit) 
5. Ctrl  + V does not paste copied contents from VS Code

What does work: 
1. Open VS Code 64-bit
2. Click Help Menu -> About
3. Click Copy button
4. Go to 32-bit program (I'm using Oracle PL/SQL Developer 32-bit)
5. Ctrl + V (Works!)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
I can't reproduce this issue with other 32 bit applications.
