### ISSUE TITLE
New feature : Multiline find selection fill for regex search

### ISSUE THREAD

**Issue by axlan** [microsoft/vscode#41050]
This would be a very simple partial solution for https://github.com/Microsoft/vscode/issues/15727

I'm working on making a really hacky version of this feature as an extension: https://github.com/axlan/vscode-multiline-find

In implementing this I realized that when regex search is enabled and you do ctrl+f with text highlighted VSCode already escapes all of the regex special characters when they're copied to the search widget.

For example right now `+.\\2\n` is added to find as `\+\.\\\\2\\n`

It seems like it would be an improved behavior if instead of ignoring multiline selections when the regex toggle is on, the new lines were just added the regex copied into the find widget.

My proposal is that:

```
+cats+\n
+dogs+
frogs
bats
```

get copied as:
`\+cats\+\\n\n\+dogs\+\nfrogs\nbats`

This wouldn't need to be aware of the documents line ending type since it would just do a replace of \r and \n with the escaped versions.

The logic to ignore multiline selections is in:
https://github.com/Microsoft/vscode/blob/2aa628bec349dc37827ee8077977064c02e5d714/src/vs/editor/contrib/find/findController.ts#L34
and the regex escape is at:
https://github.com/Microsoft/vscode/blob/2aa628bec349dc37827ee8077977064c02e5d714/src/vs/editor/contrib/find/findController.ts#L253

To implement this, the logic would need to be rearranged a bit, but would probably be around 10 lines.

It looks like the regex escape logic  currently doesn't apply to "find in files ctrl+shift+f" which is a little inconsistent, but this feature could be added there as well.

The downsides of this change are that the behavior might be unexpected, or that it might accidentally lead to dumping a huge amount of text in the find field. However, I think this is in line with the current behavior, and if there was a concern about copying too much text, addressing this explicitly would be the better option, since you can already dump a huge single line into the find widget.

- VSCode Version: 1.19
- OS Version: Windows 10

**Comment by xuejianxianzun** [comment]
thanks, you tool is work well. :-D

**Comment by roblourens** [comment]
Do you see any issue with removing the single-line restriction @rebornix?

Also, I can't decide whether this should only work when the find/search widget is already in regex mode, or should put the find widget in regex mode.

**Comment by rebornix** [comment]
We already support searching multiple lines ;)

**Comment by dwelle** [comment]
@rebornix not for `actions.find`, at least it doesn't auto-populate the input when you press `ctrl+f` (though you can copy/paste into that box — but that doesn't auto escape symbols when you have regex search enabled). Can repro on Insiders.
