### ISSUE TITLE
Clickable file paths in Debug Console.

### ISSUE THREAD

**Issue by lazyfingers** [Microsoft/vscode#41053]
This would be a huge usability boost if file paths would be clickable:
i.e. filename:linenum:charnum

instead, I have to either cmd+p and type the filename:line myself or copy/paste the very line from the debug console.

**Comment by usernamehw** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/27713 ?

**Comment by lazyfingers** [comment]
Duplicate or not, this is an obvious usability upgrade. It can literally save a ton of time wasted on code navigation between the problematic code points via clicking/typing. But thanks for pointing that duplicate out!

**Comment by lazyfingers** [comment]
"Happy Coding!", coding will be happier with a previously stated improvement :)
