### ISSUE TITLE
"overflow-scrolling" property is not supported?

### ISSUE THREAD

**Issue by ddryo** [Microsoft/vscode#41067]
Please excuse my poor English.

- VSCode Version: 1.19.1
- OS Version: mac OS X (10.11.6)

Steps to Reproduce:

1. When use "overflow-scrolling" property on css/scss files, vscode output "Unknown property: 'overflow-scrolling' ".

**Comment by usernamehw** [comment]
Can you give a link to Standard or Specification of `overflow-scrolling`?

I can only find non-standard webkit-specific `-webkit-overflow-scrolling`: 
 https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by ddryo** [comment]
Oh, I see, I was wrong!
Thank you for answering.
