### ISSUE TITLE
vscode needs to support html/js/css mixed mode

### ISSUE THREAD

**Issue by laoshaw** [Microsoft/vscode#41066]
For frontend development I often need embed html inside JS files, or vice verse, etc, i.e. the mixed code snippet mode. vscode really should be able to detect these html/js segments instead of just depending on a simple file type, and then apply intellisense and indentation to these segments.

now, if I embed script into html, or put some html into javascript, all the vscode smartness are lost for those embedded code.

**Comment by AmitJoki** [comment]
+1 

I have a similar problem when working with Rails.

May be we could add something along the line
```
# lang: js
//js code
# endlang
```

The VS Code could parse such comments and make a segment of editor and assign the value given in the lang parameter (in this case: js) to the language mode of the segmented editor.

By segmented editor, I mean like the one used in Interactive Learning in one of the start pages of VS Code.

**Comment by aeschli** [comment]
Please be very spcifc here, as most embedding scenarios are different.
We have language support for CSS/JavaScript in HTML. if that doesn't work for you, please file a issue with a code example.

Embedding HTML in JavaScript: We have support for React. For other cases, again please give a code example.

**Comment by AmitJoki** [comment]
Think of it this way:
```
<html>
   <body>
<span>I am HTML, I need to be in HTML Mode. Currently Format Document doesn't work,
 but what if I was only HTML and let JS, CSS have their own segmented editors?</span>
      <script>
        // lang: js
            var a = 1;
b = 2;
var c = "I am unintended and javascript intellisense doesn't work here";
if(segmented == true){
  // then I can have full blown javascript support
  // I can format the document with beautify
  // Intellisense will work perfectly cause it only has to be javascript specific within this 
 //segmented editor
}
        // endlang
      <script>
<h1>Similarly I on the other hand can be formatted on my own because I am HTML only. 
Extensions targeting HTML can be activated on my editor alone letting JS and CSS be alone.</h1>
<style>
/* lang: css */
I literally have no Intellisense in here, just like my brother JS.
I have no CSS linting as is the case with JS. 
I have no formatting option whereas when I was alone in a .css file, I had all these luxuries! :(
/* endlang */
</style>
<blockquote>
But, if we could replace the contents between lang: {id} and endlang and 
put in a segmented editor with its language id set correctly,
 everything will work perfectly.</blockquote>   
   </body>
</html>
```

The language support is *not* really a support actually if all the above problems persist. It is just that coloring is done to some extent. 

When I type 

`<div class="hi"><div class="baby"><div class="hi"></div></div></div>` in a `.html` file, and do Format Document, it becomes:

```
<div class="hi">
    <div class="baby">
        <div class="hi"></div>
    </div>
</div>
```

That's not the case if I had written the same in `.html.erb` which is a Rails View, with some JS and CSS thrown in. I don't get HTML language support, nor of JS's and CSSs. All I get now is coloring with no actual language supports and the extensions which are targetting the three don't work because they are designed to work based on language id.

With my suggestion, we can get to separate the languages onto their own segmented editors and have the extensions, linting, formatting be language specific and it would work like a charm.

**Comment by aeschli** [comment]
When changing`<script>` after `// endlang` to </script> and save this as a HTML file, I get code assist inside the script as well as the style element.
![image](https://user-images.githubusercontent.com/6461412/34836851-606b33b8-f6f9-11e7-85ff-37fe48d59aad.png)
![image](https://user-images.githubusercontent.com/6461412/34836867-68051fee-f6f9-11e7-990f-1d4f0f2b0d37.png)
Also formatting works for me.

Inside a 'html.erb' file this won't work, as this is ruby. It looks like HTML, but in general, 'html.erb' file are not valid HTML. There are additional escaping rules to be followed and variables can be placed anywhere, breaking the HTML syntax rules. 
Enabling the HTML language mode for such files might work in 60%, but we will be flooded with bugs for the remaining 40%.

**Comment by AmitJoki** [comment]
> Inside a 'html.erb' file this won't work, as this is ruby. It looks like HTML, but in general, 'html.erb' file are not valid HTML. 

Sorry, but I beg to differ. The `.erb` is nothing but a decorator for Ruby to understand that this file needs to be parsed. Other than that, whatever extension comes before `.erb` is actually what the file is going to be after compilation. So, a `.html.erb` *is* a valid HTML file. Same is the case for `.js.erb` or `.css.erb`.

Most of the times, the Ruby written will be in sparse amount within a view. The larger part will be HTML and by large, I mean that Ruby is negligible for most part of it. A `html.erb` is just HTML and I'd expect it to be treated like one.

I am not asking for language support for Ruby which is like a needle in the haystack in a `.html.erb` but hey, at least we could get the main language HTML support!

Also this is not `.erb` specific.  What is `.aspx` if not HTML + support for C#?

```
<%@ Page Language="C#" Inherits="System.Web.Mvc.ViewPage" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
<title>Index</title></head>
<body>
<div>

The current date and time is
<% Response.Write(DateTime.Now);%>
</div>
</body>
</html>
```

The above is a sample view and is a microcosm for most of such pages. HTML is in large parts while C# itself is in sparse amount. Now, I pasted the above file in a new file with `.aspx` extension and saved. The thing to be noted is, there's no `.aspx` support built-in within VS Code, but the language mode got selected to HTML and I got the following output upon saving(I have Format on Save option enabled)
```
<%@ Page Language="C#" Inherits="System.Web.Mvc.ViewPage" %>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

    <html xmlns="http://www.w3.org/1999/xhtml">

    <head id="Head1" runat="server">
        <title>Index</title>
    </head>

    <body>
        <div>

            The current date and time is
            <% Response.Write(DateTime.Now);%>
        </div>
    </body>

    </html>
```

Not, perfect but does work for about 90%. I can just select the whole thing upto the first line and press `Shift + Tab`. 

The same goes for PHP too. It is just HTML with support for embedded PHP, although we now don't get neither PHP language support or HTML's.

>There are additional escaping rules to be followed and variables can be placed anywhere, breaking the HTML syntax rules.

I hear you. It is indeed an overkill to be working on the syntactic sugar like `<% %>`, `<?php ?>`, but we could leave them be to be a child of a parent node, as it currently does. 
```
<div>
The current date and time is
<% Response.Write(DateTime.Now);%>
</div>
```
becomes
```
<div>
    The current date and time is
    <% Response.Write(DateTime.Now);%>
</div>
```

which is better than nothing, of course the coloring is off, but then there are extensions for coloring.

I tried to work on an extension with my segmented editor idea, but then I couldn't set the language ID via javascript of which I've opened an issue [#40337](https://github.com/Microsoft/vscode/issues/40337) which was closed in favour of [#1800](https://github.com/Microsoft/vscode/issues/1800).

Also see, #41366, where the user is requesting a very similar thing which can be solved with segmented editor approach.

There's no such folder-based text editors that does this and VS Code could stand out if it were to implement this. And WE DO HAVE embedded editor feature as is obvious in the **Interactive Playground** help feature. So why not use it to provide a truly multi-language support within a single file?

**Comment by aeschli** [comment]
@AmitJoki Thanks for the input. I don't think there nothing easy here as soon as you dive into the details. 
But I'm afraid we still don't know the issue of the original reporter.
@laoshaw As mentioned, we already support mixed html/css/js files. Can you add an example of HTML in JS?

**Comment by aeschli** [comment]
Closing due to lack of information
