### ISSUE TITLE
Code folding for #ifdef #endif in Fortran

### ISSUE THREAD

**Issue by changliao1025** [Microsoft/vscode#41062]
- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. any subroutine containing 
#ifdef something
    dosomething("");
#endif
2. When click +/- to fold/unfold, the above will interrupt the subroutine.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
You are looking for language aware folding: #3422
