### ISSUE TITLE
[tslint][Extension] Unable to install tslint extension from the extension recommendations list.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#4107]
OS: WIndows10
Build:0.10.12-alpha
Steps:
1. Launch an app and open folder for "starter Azure node Express 3" app.
2. Open app.ts and click on extension info icon from the status bar.
3. Select option for "Show Extension Recommendations".
4. try to Install tslinit extension.

Actual: 
1. There is no alert of successful or failure.
2. When I verified in the installed extension tslint is missing.
![image](https://cloud.githubusercontent.com/assets/17735796/13740122/34c7a0ce-e98c-11e5-9629-23fe98105956.png)
3. After some time when I check "Show Extension Recommendations"  I could see tslint is showing up again as a recommendation.
![image](https://cloud.githubusercontent.com/assets/17735796/13740039/d2791bb4-e98b-11e5-8f88-709fdf725681.png)

Expected:
User should get a notification whether extension installed successfully or not.

**Comment by joaomoreno** [comment]
I cannot reproduce not being able to install the extension. Works nicely here.

The lack of notification is as designed, until we remove it from the quick open widget.
