### ISSUE TITLE
中文版 默认设置.json 的 renderWhiteSpace 选项被翻译了

### ISSUE THREAD

**Issue by elia-is-me** [Microsoft/vscode#41079]
版本 1.19.1
提交 0759f77bb8d86658bc935a10a64f6182c5a1eeba
日期 2017-12-19T09:46:23.884Z
OS Version: Windows 10 Home Build 17025

默认设置文件里：
`  // 控制编辑器中呈现空白字符的方式，可能为“无”、“边界”和“全部”。“边界”选项不会在单词之间呈现单空格。
  "editor.renderWhitespace": "none",
`
其中“无”、“边界”和“全部”都不应该翻译或者如其它配置项的注释应为“none"(无)、"Boundary"(边界)、"all"(全部)

Reproduces without extensions: No

**Comment by danyeh** [comment]
@elia-is-me , it will be great if you can help to correct directly in [Transifex](https://www.transifex.com/microsoft-oss/). See https://aka.ms/vscodeloc on the process. Thank you!

**Comment by danyeh** [comment]
Fixed by voting the right translation. https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hans/$/111043223?q=Controls how the editor.
