### ISSUE TITLE
Feature request: Quick access to custom views

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#41071]
- As more and more extensions add tree views, my explorer is too cluttered.
- I find myself having to use more clicks for common tasks
    - clicking to expand, collapse, move, resize to see what I want
    - it just feels cumbersome and will only get worse
- I would much rather have a way to view each tree view contribution on its own panel with some toggle (key binding, command etc) to view or show so I can instantly navigate between them and they all appear in predictable locations.  In other words, my eyes can immediately fixate on the top of the tree view because it will always be the only thing in the panel.

**Comment by sandy081** [comment]
@dakaraphi How is it helping the cluttering issue when it is moved from one location to another location? 

- If the custom views are not helpful you can hide it.
- If the extension contributing custom view is not helpful you can either uninstall or disable it.

May I know, if there are issues that are not being solved by above approaches?

**Comment by dakaraphi** [comment]
@sandy081 
What I'm suggesting is that each view contribution can be accessed independently of all the others.  There wouldn't be one single explorer with all of them.  Each tree view exists on its on panel that I can toggle open or close etc.

- Functionality that can only be used in a tree view is not optional to hide.
- I don't install extensions I don't plan to use.

The tree view implementation is making vscode feel more like a cumbersome IDE.  It breaks the spirit of what made vscode so great.  You can do virtually anything with the keyboard and do it fast.
The tree view now has slowed down my general use of the all functionality that is in the tree view.

If you find an alternative way to meet the following goals, then that's fine.  Here is what I'm asking for.

- Fast access to all of the tree view contributions.  I should be able to access them immediately through palette command and key binding
- When a tree view is shown, it should be predictable where it is shown.  This is why I think they all need to be on their own panel.  If I want to view bookmarks, I don't want it maybe open at the bottom of the explorer, or the middle or who knows where because I have 5 or 6 other tree view contributions.
- Generally, I'm never using multiple contributions at the same time.  That is impractical anyway.  They get in the way of each other.  I now have to use my mouse to click drag, collapse, open etc every time I need to switch to a different contribution.  This is really annoying because it takes me out of my flow.  I have to pickup the mouse and do all these actions just to view something.  Then undo it all to view something else.

**Comment by dakaraphi** [comment]
@sandy081 
> If I understand correctly, your argument is that not all views belong to the Explorer and some deserve their own side bar entries.

Yes exactly.

> I think this will be solved mostly with above two right?

Yes I agree.

Thanks!

**Comment by sandy081** [comment]
@dakaraphi I extracted two requests into two issues. This one handles the first request for quick access of views. #41686 handles the second request - contribute views to other locations.

**Comment by sandy081** [comment]
@dakaraphi We already have commands to quickly access views. `Open View` and `Quick Open View`. I added custom views to this list that will make this consistent with the existing story.

<img width="708" alt="screen shot 2018-01-16 at 16 30 26" src="https://user-images.githubusercontent.com/10746682/34998941-a7f25a3c-fae0-11e7-9dd5-1756f080eab5.png">

**Comment by dakaraphi** [comment]
@sandy081 Thanks.  This change looks helpful.

However, it is not clear to me where #41686 clearly captures the 2nd part.  That being to have an option that each tree view contribution can be viewed on its own panel, vs all of them on the explorer.

**Comment by dakaraphi** [comment]
@sandy081 nevermind, I see it now in the other issue. thx.
