### ISSUE TITLE
Intellisense not working for VSC 1.19

### ISSUE THREAD

**Issue by sillym** [Microsoft/vscode#41074]
- VSCode Version:Version 1.19.1 (1.19.1)
- OS Version:Mac OS Sierra 10.12.6 (16G1036)

Steps to Reproduce:

1. When I download a new version 1.19 VSC, I found the Intellisense is not working any more.(e.g. functions in lodash can not be loaded.)
While for the same code base, Intellisense in V1.16 VSC is working. Could you pls help?
2.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Please provide some example code and steps to reproduce the problem

**Comment by sillym** [comment]
Thanks for the reply.
I am still new to node so I just created an new express app.
Code snapshots are attached.
Not sure why the intellisense is working on 1.16 version, but not on 1.19, in same code directory.
Please kindly share if I made something wrong.

![v1 16](https://user-images.githubusercontent.com/13677254/34557636-e705947e-f175-11e7-88ee-32e6673c368e.jpg)
![v1 19](https://user-images.githubusercontent.com/13677254/34557662-fa89a666-f175-11e7-868a-7b943af2c101.jpg)

**Comment by EyePlusPlus** [comment]
@sillym Could you try removing the `jsconfig.json` file, then restarting vscode and see if the problem still persists?

**Comment by sillym** [comment]
@EyePlusPlus Thanks for the reply. I tried but there's no luck. But v1.16 is still working.
Attached is my `jsconfig.json`. Is there anything wrong with it?
![jietu20180105-102736 2x](https://user-images.githubusercontent.com/13677254/34593826-4c8bb44e-f208-11e7-8f08-001a8b659e3b.jpg)

**Comment by the-spyke** [comment]
I have a similar problem. For example `Go To Definition` doesn't work for `dependencies` in `package.json` specified by a path. But it works if I delete `jsconfig.json` file

**Comment by mjbvz** [comment]
@sillym Do you get intellisense for local variables and types? Typing acquisition may be failing. It has a cache per TypeScript version so VS Code 1.16 may have the lodash types in its cache already

**Comment by sillym** [comment]
@mjbvz Thanks for reply. 
![jietu20180122-160743 2x](https://user-images.githubusercontent.com/13677254/35210775-88e434fa-ff8e-11e7-942e-b54d9b9aef3f.jpg)
I think it's working locally for both versions. Please see the snapshot.

**Comment by mjbvz** [comment]
Please collect the typing installer logs:

1. Set `"typescript.tsserver.log": "normal"`
1. Restart VSCode and reproduce the issue
1. Run the `TypeScript: Open TSServer log`  command in vscode from a js or ts file. This should open a folder
1. Look in the `ti-xxx.log` file from this folder

Near the top of this file there should be an error message about why typings install failed. See https://github.com/Microsoft/TypeScript/issues/18344 for example

**Comment by sillym** [comment]
@mjbvz please forgive me about my little knowledge. How should I run `TypeScript: Open TSServer log` command?

**Comment by mjbvz** [comment]
Use the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette). You must be in a js or ts  file for it to show up
