### ISSUE TITLE
Is VSCode closing all open terminals and processes when closing a window?

### ISSUE THREAD

**Issue by Aminadav** [Microsoft/vscode#41077]
I have two VSCode windows.

In one window I I have 5 terminals.
One terminal has Node app.
The other has something other.

Then I close that window. Is those terminals and process inside are automatically killed?

I'm using Windows.

**Comment by Tyriar** [comment]
Yes on Windows all "console processes" are killed, that means that if you open cmd then powershell inside then notepad.exe, only cmd.exe and powershell.exe would be killed.

There is an option `terminal.integrated.confirmOnExit` that warns when you exit the Window, but currently it warns if you have *any* terminal instance open, not just ones that have sub-processes. See https://github.com/Microsoft/vscode/issues/23808
