### ISSUE TITLE
Disable Alt-key for toggle menu when another keybinding is provided

### ISSUE THREAD

**Issue by AmitJoki** [Microsoft/vscode#41070]
- VSCode Version: The latest one as of writing this
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Have some keybindings with Alt
2. Put workspace.editor.menuBarVisibility: "hidden"
3. Assign some other key to toggle menu bar in case you need it. I assigned [Pause Break] key
4. Use [Pause Break] key or whatever that is you've assigned to toggle menu bar.
5. A pop up shows [Info: You can also use Alt to toggle menu bar]

That is annoying because Alt is still being considered for toggling the menu bar when I want it to overwrite with some other key.

This also causing annoyance when I press Alt + Tab to go to other programs. If I don't press Alt and Tab fast enough, the menu bar toggles itself into view. The same is with the keybindings with Alt I said in the first step of the reproduction.

Reproduces without extensions: Yes

**Comment by lyallh** [comment]
Discussed in #35010

**Comment by bpasero** [comment]
@AmitJoki @lyallh I think you will have to report this against [Electron](https://github.com/atom/electron), there is no control (as far as I know) from VSCode to control this.

**Comment by bpasero** [comment]
@AmitJoki @lyallh can you please check this build (https://az764295.vo.msecnd.net/exploration/b1513227ace6929e278c5d531250bc1d0cf89e2f/VSCode-win32-x64-1.22.0-exploration.zip) to see if the issue persists. It includes the fix for https://github.com/Microsoft/vscode/issues/35010

**Comment by lyallh** [comment]
@bpasero I'm runing linux-x64 not win. Is it just my upstream electron fix?

**Comment by bpasero** [comment]
@lyallh here is the Linux version: https://az764295.vo.msecnd.net/exploration/51470c58bd748e1689ba3d82811fe3df9efa72d4/code-exploration-1.22.0-1521641787_amd64.tar.gz

That one comes with Electron 2.0.0-beta.5

**Comment by bpasero** [comment]
@AmitJoki @lyallh can you please try out from our latest insider builds if you still think this bug is valid? We updated to Electron 2.0.x meanwhile.

You can give our preview releases a try from: https://code.visualstudio.com/insiders/
