### ISSUE TITLE
Can't install extension offline

### ISSUE THREAD

**Issue by jungopro** [Microsoft/vscode#41075]
- VSCode Version: 1.19.1
- OS Version: Windows 10 x64

Steps to Reproduce:

I'm on a computer without internet access

1. downloaded vsix from the marketplace
2. code --install-extension yzhang.markdown-all-in-one-0.11.2.vsix
3. Error: getaddrinfo EAI_AGAIN marketplace.visualstudio.com:443
at Object.exports._errnoException (util: .js:1050:11)
at errnoException (dns.js:33:15)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

similiar with powershell extension 1.5.1

It doesn't happen with all extension, many others install just fine without internet access

Reproduces without extensions: No

**Comment by sandy081** [comment]
Duplicate of #40722
