### ISSUE TITLE
Extensions symbol not showing anymore

### ISSUE THREAD

**Issue by AO17** [Microsoft/vscode#41076]
- VSCode Version: 1.19.1
- OS Version: Windows 10

My extensions are not visible anymore, not even the symbol on the left side is visible.
Only when pressing Ctrl+Shift+X the symbol appears again.

Steps to Reproduce:

1. Start VS Code

![git](https://user-images.githubusercontent.com/30864075/34512034-d9893326-f05f-11e7-97f4-82d380f7fdaa.PNG)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/40531
