### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#41080]
Issue Id: <b>09b2db67-ec5b-f02f-7f98-25f92608977c</b><br /><br />*Versions* <br />- 1.19.1<br />-  816be6780ca8bd0ab80314e11478c48c70d09383<br />-  951f5a20fc820e32a65ca05bb87af86f65027470<br />*Stack* <br />TypeError: Cannot read property 'uri' of null<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L143:56 (uri)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L143:56 (uri))<br />[/vs/workbench/parts/extensions/browser/extensionEditor.ts#L325:16 (repository)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/browser/extensionEditor.ts#L325:16 (repository))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L505:16 (setInput)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L505:16 (setInput))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L395:28 (doSetInput)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L395:28 (doSetInput))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L348:14 (doOpenEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/browser/parts/editor/editorPart.ts#L348:14 (doOpenEditor))<br />[/vs/workbench/services/editor/common/editorService.ts#L206:25 (openEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/editor/common/editorService.ts#L206:25 (openEditor))<br />[/vs/workbench/services/editor/common/editorService.ts#L163:15 (doOpenEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/editor/common/editorService.ts#L163:15 (doOpenEditor))<br />[/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L427:28 (openEditor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L427:28 (openEditor))<br />[/vs/workbench/parts/extensions/browser/extensionsActions.ts#L92:34 (open)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/parts/extensions/browser/extensionsActions.ts#L92:34 (open))<br />[/vs/base/common/actions.ts#L226:31 (run)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/actions.ts#L226:31 (run))<br />

**Comment by KamilSzot** [comment]
also present on 1.19.2, prevented me from installing cjsx extension

**Comment by KamilSzot** [comment]
Fix is in the same style as special case for default icon if icon asset is missing.

**Comment by joaomoreno** [comment]
@sandy081 I'm forwarding this and the respective PR to you, I'm sure you'll know immediately how to review it.
