### ISSUE TITLE
Suggest: Show Outdated Extensions => Show Extension Updates

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#4108]
I find it much easier to understand what the action does because it is about updates and not about outdates :)

Refs: https://github.com/Microsoft/vscode/issues/4024

**Comment by joaomoreno** [comment]
But it doesn't show you *extension updates*. It shows you the extensions that are out of date.

**Comment by jayrosen1576** [comment]
If you select "Show Installed Extensions" you won't see the update button but if you select "Install Extension" and search for an already installed extension that has a newer version available, the update button is visible. Is this part of this bug or is this something else?

![image](https://cloud.githubusercontent.com/assets/1121098/13755571/4ed2b1be-e9f2-11e5-8c63-5633329fb6ba.png)

![image](https://cloud.githubusercontent.com/assets/1121098/13755584/583f7606-e9f2-11e5-886c-b30a7ea796fd.png)

**Comment by joaomoreno** [comment]
@jayrosen1576 It's a separate one, I created it for you: #4255
