### ISSUE TITLE
Enable run mode as option on debug config

### ISSUE THREAD

**Issue by carlcheel** [Microsoft/vscode#41087]
We can launch a run configuration with run mode by pressing Ctrl+F5 (https://code.visualstudio.com/docs/editor/debugging#_run-mode)

Could we enable this as an option in the launch.json file, for example:

```
{
            "type": "node",
            "request": "launch",
            "name": "Some name",
            "runtimeExecutable": "npm",
            "cwd": "${workspaceRoot}/client",
            "console": "integratedTerminal",
            "runtimeArgs": [
                "run",
                "start"
            ],
            runMode: true <--- could we add this?
}
```

Reason:

1. If I have a compound run config, I want one process to run without debug and one to run with debug, Ctrl+F5 doesn't solve this problem, without running them one by one manually.

2. It's nice to start an app from the debug window by clicking the play button, sometimes we don't want to attach the debugger.

**Comment by isidorn** [comment]
This is currently possible by adding
`"noDebug": true`
To a launch configuration.

However this is currently not documented and expoesed. I would consider adding this if more users ask for this as I understand your use case. For now closing as a question, will reopen if rasies traction among users
fyi @weinand
