### ISSUE TITLE
 Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#41081]
Issue Id: <b>58456b89-1194-2cc9-4331-689ee3ee1fe3</b><br /><br />*Versions* <br />- 1.19.1<br />-  816be6780ca8bd0ab80314e11478c48c70d09383<br />-  d8989c95964ce06c64ffebc2fb400a0327bd447d<br />-  951f5a20fc820e32a65ca05bb87af86f65027470<br />-  bc206bbacc13e48d4422b8c73334aa9dd6f782df<br />*Stack* <br />TypeError: Cannot read property 'getBoundingClientRect' of null<br />[/vs/base/browser/dom.ts#L548:18 (getBoundingClientRect)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/browser/dom.ts#L548:18 (getBoundingClientRect))<br />[/vs/editor/contrib/quickFix/quickFixWidget.ts#L68:23 (getDomNodePagePosition)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/editor/contrib/quickFix/quickFixWidget.ts#L68:23 (getDomNodePagePosition))<br />[/vs/editor/contrib/quickFix/quickFixWidget.ts#L47:15 (_toCoords)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/editor/contrib/quickFix/quickFixWidget.ts#L47:15 (_toCoords))<br />[/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L40:28 (getAnchor)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L40:28 (getAnchor))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/0759f77bb8d86658bc935a10a64f6182c5a1eeba/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />    at _combinedTickCallback (internal/process/next_tick.js:73:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:104:9) <no sourcemaps><br />

**Comment by alexandrudima** [comment]
Looks like the editor is not in the DOM when this code executes...
