### ISSUE TITLE
code 安装损坏

### ISSUE THREAD

**Issue by BOSSLMH** [Microsoft/vscode#41089]
每次打开vs code 顶部总是显示  警告 code 安装损坏 请重新安装  我卸载了  重新安装  还是出现这个情况  为什么

**Comment by rebornix** [comment]
@BOSSLMH what version of Code are you using? What platform are you on? From your description it's dup of https://github.com/Microsoft/vscode/issues/780

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
