### ISSUE TITLE
Breakpoint ignored if attach process with some webpack sourcemaps

### ISSUE THREAD

**Issue by wip0** [Microsoft/vscode#41083]
- VSCode Version: Code - Insiders 1.20.0-insider (8697a5e4ec152832a2612929c87d56302dbb2e79, 2018-01-03T05:14:21.686Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
MochaSnippets|Ala|0.0.1
Handlebars|and|0.2.0
quills|chr|1.0.0
bracket-pair-colorizer|Coe|0.10.14
tslint|eg2|1.0.24
LogFileHighlighter|emi|1.2.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-favorites|how|1.1.6
search-node-modules|jas|1.2.0
language-julia|jul|0.9.1
cpptools|ms-|0.14.5
Align|ste|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Start node program
2. Attach the node with vscode

Below is launch.json
```json
 {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach SxSService",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/**/*.js",
                "!${workspaceRoot}/node_modules/**/*.js",
                "${workspaceRoot}/node_modules/@trs/**/*.js",
                "!${workspaceRoot}/node_modules/@trs/**/node_modules/**/*.js"
            ],
            "trace": true
        }
    ]
}
```
Here are some of console logs

> 15860: _attach: address: 127.0.0.1 port: 5858
15860: _attach: connected
15860: __initialize: got process id 18084 from node
15860: _initialize: target node version: v6.7.0
15860: _injectDebuggerExtensions: code injection successful
15860: _startInitialize: stopped: true
15860: NodeV8Protocol hook: ref cache size: 35
15860: _findSourceMapUrl: source map url found at end of generated file 'd:/@misc/eikonnodejs/DesktopSxs/index.js'
15860: _registerSourceMap: d:/@misc/eikonnodejs/desktopsxs/index.ts -> d:/@misc/eikonnodejs/desktopsxs/index.js
15860: _registerSourceMap: webpack:///webpack/bootstrap 7ed651a3abd4e59b6658 -> d:/@misc/eikonnodejs/desktopsxs/app.js
15860: _registerSourceMap: webpack:///external "path" -> d:/@misc/eikonnodejs/desktopsxs/app.js
15860: _startInitialize: no entry event after 10 retries; giving up
15860: NodeV8Protocol hook: ref cache size: 42
15860: _startInitialize2: fire initialized event
15860: _startInitialize2: in attach mode we guess stopOnEntry flag to be 'true''
15860: _startInitialize2: fire stop-on-entry event
15860: _mapSourceAndUpdateBreakpoints: src: 'd:\@misc\eikonnodejs\DesktopSxs\index.ts' 21:0 -> gen: couldn't be mapped; breakpoint ignored
15860: _mapSourceAndUpdateBreakpoints: src: 'd:\@misc\eikonnodejs\DesktopSxs\app.ts' 82:0 -> gen: couldn't be mapped; breakpoint ignored
15860: _mapSourceAndUpdateBreakpoints: src: 'd:\@misc\eikonnodejs\DesktopSxs\index.ts' 6:0 -> gen: 'd:\@misc\eikonnodejs\DesktopSxs\index.js' 8:0
15860: _mapSourceAndUpdateBreakpoints: src: 'd:\@misc\eikonnodejs\DesktopSxs\index.ts' 21:0 -> gen: couldn't be mapped; breakpoint ignored
15860: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[dD]:\\\\@misc\\\\eikonnodejs\\\\DesktopSxs\\\\index\\.js$","line":8,"column":0}
15860: _updateBreakpoints: result [{"verified":true,"line":7,"column":1},{"verified":false,"message":"Breakpoint ignored because generated code not found (source map problem?)."}]

**Comment by wip0** [comment]
With the same launch.json, VSCode below is OK.
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:02.926Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by wip0** [comment]
The correct path is d:/@misc/eikonnodejs/desktopsxs/index.ts. Somehow, my comment always show only d://desktopsxs/index.ts. Don't know why? (It shows correctly if I edit)

**Comment by roblourens** [comment]
If you use the newer node debug adapter, by upgrading node to 8+ or setting `"protocol": "inspector"` in your launch config, then this may work automatically.

If it doesn't, depending on your webpack config, then you may need to investigate with the `.scripts` command to set `sourceMapPathOverrides` to remap the paths manually. See https://github.com/Microsoft/vscode-node-debug2#the-scripts-command

**Comment by wip0** [comment]
@roblourens I confirm that breakpoint does not work with or without webpack. (VSCode Insider used to work in the last month version. I cannot remember exactly version). I cannot upgrade node version neither.

I am trying .scripts command.

**Comment by wip0** [comment]
Actually, the breakpoint was hitted. But there was no current line and a breakpoint indicator. Please see image below. (In VSCode Insider) I put a breakpoint at line 10.
![2018-01-04_11h08_37](https://user-images.githubusercontent.com/20312631/34550076-7e078f02-f140-11e7-9255-eb7010e94a0b.png)

---
Below is captured from VSCode (Work)
![2018-01-04_11h09_33](https://user-images.githubusercontent.com/20312631/34550094-a6365fe4-f140-11e7-88f3-99367b2c245e.png)

**Comment by wip0** [comment]
@roblourens  If I disable the theme "quills" in VSCode Insider, everything is OK.
Whereas "quills" in VSCode, it still works.

**Comment by roblourens** [comment]
So the current line indicator and breakpoint are invisible, when you're using the "Quills" theme in Insiders?

If you click in the call stack, do they appear?

**Comment by wip0** [comment]
If I remember correctly, they did not appear. 
But after I reinstall "Quills" and/or restart VSCode insider, everything is OK now.

**Comment by isidorn** [comment]
@wip0 ok so let me get this straight you can no longer reproduce this?
If you can not then there is unfortunetely nothing we can do. If you can please provide reproducable steps and I can investigate. Thanks

**Comment by wip0** [comment]
@isidorn I cannot reproduce this any more. Please close this issue. 

Thank you for your help.
