### ISSUE TITLE
TYPO -> VSCode Intellisense -> `border-radius` property hint 

### ISSUE THREAD

**Issue by peacefulseeker** [Microsoft/vscode#41095]
Hello.
My current environment:
- OS Version: Windows 10
From VScode About:
```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

```
**How should I label typos in intellisense hints?**
Inside CSS/Scss files hovering on `border-radius` property gives: 
`Defines the radii of the outer border edge.`
So radii should be radius.

**Comment by aeschli** [comment]
Looks funny, but _radii_ is the plural of radius. See https://en.wiktionary.org/wiki/radii
