### ISSUE TITLE
Feature Request: Find in Open Files

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode#41099]
- VSCode Version: 1.19.1
- OS Version: Ubuntu 17.10

It would be great if there was a possibility to search open editors like `Find: In Open Files` command in Sublime Text. As for possible implementation, there may be a placeholder in `files to include` called `<open files>` or `<open editors>` (similar to `<open files>` in Sublime), which would allow to find in currently opened editors.

And for the future, there could be such placeholders for various stuff (e.g. `<staged files>` to search staged files etc.)

Possibly related: https://github.com/Microsoft/vscode/issues/15178.

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/20530

**Comment by evenfrost** [comment]
Ahh, I failed with issue search, sorry for duplicate.
