### ISSUE TITLE
Extenshion host terminated unexpectedly.

### ISSUE THREAD

**Issue by Dandelosreyes** [Microsoft/vscode#41092]
I already tried searching for other treads. But none of solutions are working :(.
Before trying the insider version i already did try the stable and still no luck . 
- VSCode Version: Code - Insiders 1.20.0-insider (8697a5e4ec152832a2612929c87d56302dbb2e79, 2018-01-03T05:14:21.686Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
(1 theme extensions excluded)
---

Steps to Reproduce:

1. Fresh install vs code insider.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
You have no extensions installed? Can you share a screen recording of the issue?
